 8 1000
t1        CGTGCGCGAGACCCCGGCAGCCCGACCTCTGCGGCACTTAGTCTCGGTACTCTTGGACCT
t2        CGAGCGCGAGACCTCGGCAGCCCGACCTCTGCGGCACTTAGTCTCGGTACTCTTGGACCT
t3        AAAGCGCGGGATCCCGACGGCCTGATCTTTGAGTTCTACACTACCGGCACTCCTGGGCCT
t4        AATCCACAACATTTCAGCGGTCTGCGCCCCGCGATCCCCATCCTCAGCAAATCCCTAGTA
t5        CGTCTGTGAACTCGCCTCGTCGAAATGTCTGGAGTCAGCGTTCCCAGTTGCGTAGCGCTT
t6        TGCAAGCAAGATCGGGGCGACGAGCTGTGCCCGTTAGATGATCTCGTTGCGCTAGTAGTC
t7        AGGTCGTGAAACTGCTGGGACTAGTCTAGGGGGCCGTACACTTTCGATGAGCCCGCGACC
t8        AGCATACTGGCGTACAGCATGTTTTTTTTGGGTATTACCATTTCTCTAAAATCTGGCCCT

          ACTGCATTGAAGTCTCCTTTTCTAATATATTCACCGCACCGTGAAGATGTGGTAGGCGGT
          ACTGCATTGAAGTCTCCTCATCTAATATATTTACTGCACCGTGAAGATGTGGTAGGGGGT
          ACCGTATCAAGGTTGATTTTTCTAACATTCTCACTGGAACGCGACGATGCAGTGAGCGGA
          ATTGTTCTAAGTACGTTTCTGTTCACTCCTTCAATATTATGTACCGACTTGTTGGGCAGT
          GCTGCCTTGGGCCCACTGCAATCGCGGTGTCCCACCCCGTGGAGCGTTTTTCGGTGCAGA
          GCTTACATGTGCCCATAAGAGATTAATTCCACCACCCCAGAAAGAGCCTTGCAGGGAAAC
          GCGGCTTCGCGTCCGCTACAGCGTTGATCTCAAATCCCGTGAGAAGGTTCCCTAGACGAC
          CTTGGGCTGTGCCCGCTGATGCCGAGGTCGTTATGTACACAGAGACATGTCCTGCAGGTA

          GTTACGAAGTCCATATTCGTGGCGACCACTTACGCGTCACAGGAGCTGAATATCGTTATG
          GTTACGGAGTCCATATTCGTGGCGACCACTTCCGCGTCACAGGAGCTGAATATCGTTATG
          TTTATAAGGTCCATATTCGTGGCGAACATCACCAGGTCACTAGAACTGTCCATCGTTATG
          ATAACAAAGTCAAAATTTGCTGCGGTCGCATATGGATCCCAGTGAACGACCGCCGCTTAA
          GCGGTAGCTTGGCGATTTACAGTGGCCCCTTCATGACAGCCAATGGCTATGAACGTTAGG
          TTAGCCCGAAAAGGATTTTCAGGACTCCACTCGCACTCCGCGTACGTCGTGATTGTTCAG
          AAGGTCAAAGAATGGTGTCTCGTATCGCACTGCGGGATTACATGAGCAGCGCCAGTGAAG
          TCGACGGCACGAGGAATGGCCGAGTCTTCCATGGGCTATCTAGGGTGAATACTCGTACTC

          ACCTGGGTACGGAATCACTACTCTGTCGAGTTATGAGCTATAGCAATGCGACTCGCGCCT
          ACTTGGGTACGGAATCGCTACTCAGTCGAGTTATGAGCTATAGCAATGCGACTCGCGCCT
          TCCAGAATCCGGCATTGGCCTCCAGCTGAATCGTGAATTGTAGCCATGCGACTCATGCCT
          GTAAAATCCCCGGAGCGACCATCAGGAAAATCCCAATCTGCCGTAGTGTCTCCTGCGGGT
          GCGGAATATGTGGAAAGGACCTCATTCCGGTCATGAAGTAGCGTAACCCTTATGCTGTCT
          GAGGGAGGGGGACGAGGATCCTTAGTCACGTGCGAACGCAGGGCAATCCGATTGCCCAAA
          ACAAGATTTAAAAGTAGGGTCTGGCAGAGACGGAGAACCATAGTCAAGCCCTCCCTGGTT
          GTATCCTCCTTTGGCAAGCCTTGGGATAGCCGAGCGGGGTGGTCCTATATATCATCGGTT

          ACGTCTTGCTTTTCTAGGAATGGCTTTCTGGCGTATAGAGCTCCGAAGTGTCATCCCGCC
          ACGTCTTGCTTTTCTAGGAATGGCTCTCTGGCGTATAGAGCTCCGAAGTGTCATCCCGTC
          ACGTCCGGATTTTCTAGGAATGGCTCTTTAGCGCAAAGAGCTTTGAAGTGTCGTCCCGTC
          ATGCCTAGTCTATTCATAGGCGGCCTTACAGGCCTTGGGCCCTGGCAGACATGAGTTGTG
          TTGCTTGGGTATTCACTATAGATTCCTAACGACCAAGTAGTCTTAGGGATTCGCCATACC
          GAGTTTTTCCGATCATGTATGGTAGCATGGTGCAACAAGGACCCATAATTGGGTTCTTTC
          TTGCCTGGTCACCACTGCCTCGGAACTCGGACTTACGATGTAGTCCCATCTCAATTCGCA
          GCGCTCAGACATGATAGAGTTATTAACTACGTTACGACAGCGAGCCATCTAGGTATAGCT

          GTGTAGTTGTAAGCTCGTAGTGAGACAAGCGTGCCGGCATACAGCTAAAGCCATACTCGT
          GTGCAGTCGTAAGCTCGTAGTGAGACAAGCGTGCCGGCATACAGCTAAAGTTATACTCGT
          GAAGAGTCGGTGGTCCATGCTGAGTAAGGTGTGCCGGTTCACAGTCAAAGCCATTCTCGT
          ACAGAGTACCGTACTCGGACCGTGCAATGTGCGACGGATTTCGGTTTCGACTATCGTCAT
          GTGTCGGCCCACCGTTGAATAGCGATCTCAGTATAGTTAAGCAGGCAACGGTGAGTCATC
          TTAAAGCATTGACATAGGCATTGAGCGTCAGTGACGTAATCCACATGTGACCATGACCCT
          GTCGGGTGATTCTCTCGCATCGAGGAGTCGGCACTGAAATCTAGGCGGTGGTCGGACCTA
          ACGCGGGGATACTTAGTTACCCCGGCCCATTAAAGGGAGAATAGCGGTGACTCAACACAA

          GCATACCCAGTGTAAACACGAACTGGTCGGTTGTATTCGAATCATACACGGCGTTTATAC
          GCATACCCAGTGTAAACTCGAACTGGTCGGTTGTATGCGACTCACACACGGCGTTTATAC
          GAACACACAGTTAAAACCCGATCTTGTCGGCTCTGTACGAATCACATATCGAGTGTGTAC
          GCATATGCAAGACCAGCACGAGGGCGACAAATATTCTGGCATCCCACTTCGTATTTGCCG
          CAGCACTCAGAGCCAATTCGGCACCCTTGGGGTACCCAGCACCTACCACAATAACTCTAC
          TGGTCGGAAGCCAGAGTATTGCTTCGAGGGCTCCTCGAGTATCCGCTGTGGTGCCCAACC
          AGATCTTCAGGAGAAGCAAGTCCTTGCGAGCAGGTAGTAGATCCTTCCAGGTAACGAAAT
          TAAGGCCAGAAGTTCGATTAAGAAAACAGCACTAGACAAATGTCTCCGGCGTTGAAAGGC

          AGCACAGCTGGGGCGCGCTAGCAGATACGATTCGATTATTAACTATACAGCGACTTGACG
          AGCACAGCTGGGGCGCGCTAGCAGACACGATTTGATTATTAACTATACAGCGACTTGACA
          CGCATATGTTGGGCGCGTTAGCCAATACACGTTTACAACTCGTCAAACTGCGACGTGAAG
          ATCATAGGTTTTGCGCGCTAGTTGATACAAACCAAGGGTGAGCCTGCTTGTAGATTAAGA
          AGTGAGGTAAAGCAGGAATTTTGAAGTCAGGTGTCCAATTTGGGTCCCCGACTATTTGGT
          TGGGCCGGTTAGGCGTAGTCGCAGGTCCCGCTGATAGGCCGGGATCATTATATCTTCCGC
          AATCGAAGGAGGACAAGACGGCAAATTTTATCCCGGAAGACGACGTTCCGCCGATCCACT
          GGCATCAATGTGACGAGCCCTAGCGCGCACCTTGTGTTCCACGCGTTCCCTGGAGCGAGC

          GTTAGGCCTCTTAAGCTGTGCCGCTCTTAAGGGCGCTTTAGCCCTCCTCTTTCTGCGAAT
          GTTAGGCCCTTTAAGCTGTGTCGCTCTAAAGGGCGCTTTAGCCCTCCTCTCTCTGCGAAT
          GTTAAGCGCTTTAAGCTGTGCCGCCCGACCGGGTGTTTGAAGCATCCTTCTCCGACGAAC
          CTATAGCCTTTAAACCCATGCCGGTTGGATGATCGTCGGAAACACGTTCCCTCTGTACAT
          CTACCGAAACTTCGTGAATGACTGTTGTAGCAGCAACCGCACTTTGATTGCTACCCTTAA
          CCAGAGTGAGTTATGTGGACCCGGCAATCGCGGTATGCTACGTATGCATGCTTACCATGA
          GGGAGAAATCTGAACCAGCACAGACTGTGGCTGTATCCGATCTACAGACGCTTCCTTTAG
          GTCTGGGGACTCCCGCGAAACTCGCTACTGTCCCTGTAAAATTATCACGCATTGCAACAT

          CTAGGTGTCTATCGCGACATGTGCTAACGATTCAGCGCATACTATTCCATCGTGATCGGC
          CTATGTGTCTATCGCGATATGTGCTAACGATTCAGCGCATACTATTCCATCGTGATTGGT
          ACTTGTGCCTACGACGACCGGTGAGAACAATTTAGCACATATCGCTCTACCCTGCCCGGG
          TTCTGCGGCTGACGCGATAGCCGCAGAAATTTTACGCCATATAATATCACCCTGCCCGGT
          TCGCATGGACTACCAGGCGCTGCGCGTCCATCTGACACATAATTACAACCGCTGTCTGAT
          TCGTATGGCGGAATGGATAACTGGCGACGCACACCTATGTAGTATTCATAGCCCTATGAA
          CTGGTCGATAGTCCGGGCCCTTGAAAGAGTTATGCCGCGCTAACCTCCGTGGTGAACCGT
          CTACGTCAACGTTCACACACTCGGTCGCTCTTGGCGTGATTAGACGTGTTGGGACAAGAG

          TGCCTCGAGGTCGATTGTTGAATACGCCCTCCGTTAAAGCGTGCTTCCCTGTTAAATGGT
          CGCCTAGAGGTCAATTGTTGAATACGACCTCCGTTAAAGCGTGCTTCTCTGTTAAATGGT
          CACATCCAGGTCGACTCGTCAACCCGCTCCCCACGAATCCTTGCTCTCCCGATATCTAGC
          TGTACGAAGGTTTCCAAACTCACACGCCCCCCACCACAGCGTACCACTACAATACCCAGC
          CGGTAGACTGGAGAGTAGCTAGCTCGCAGGCTCTTATAGCACCCTTCTTACCATTGTAAC
          GCGACTCCTACCAAAGATCATACCGTATGGCGATAGATACGAGTGCATAAGTCCTGCACG
          CTAGCCAGTCCTTAGGAGGATACCGCAATGTTAGCTATACACACTTGACGGCACGGCAAT
          TAGGGCAGTGATGAAGATCAAATTGTTTGAATAATGCTATTTGCCTACCCCTGGCGGCGG

          CTTCTGATAGCCAATACTGAAGAATAAGGTAGCACTAACTTTATCAGACGTACAGCGATC
          CTTCTGATAGCCAATACTGAAGAATAAGGTAACACTAACTTTATCAGACGTACAGCGATC
          CTGCAGATTGCTGGACCTGGACGATAAACAAGCACTTACCTTATCCGACGTCAACTGGTG
          CGTTAGGCAGCCCGACCTGGGGAAAAAGGTGGGACTGCACAGAACCGCCGAATCCCGGTG
          TCTGCAACTCAGAAACTGGGGGATTACGACTCCATGCTTCACGTCTGACGTTCACCGCAA
          GGTTGACTCGCAGTGCCATACGGACGCACCACTAACCTATTCACTTGATATTTGCCGTAA
          AGTGAATTTGTGAGATTTGACAACTTTCCGACTATTCAACAAGAGCGATGGTTAGGCCTA
          TGTACTGCTTGGGGAAACCAGAGCTGTCGAGGTCGGCTCTTTGTCAGTCTACAAGCTGGG

          GCGCGTACAACACTTTCAAACAAGCAGTCCGGTGTAAACGGCGCTGAAACAAATGTCTGA
          GCGCGTACAACACTTTTAAACAAGCAGTCCGGTAGGAACGGTGCTGAACCGAATGCTTGA
          ACGTGCTCGAAATTTTCTCAAAAGAACTCCGGTCGGAACAGTGCAGAAGAAAACCCTTGG
          AACGGAACCAAGGTCTAAGACTAGTAACCCGATTGGAGCAGCGTCGAAGCATACTACCAC
          CAGGACACGAGAGATTTCGGCATATATCCCAGACGCAAGGCCGGCTTAATTTAGGGGGGA
          CATGGAATGGTTGGTAGGCTCCAGCAGTATAAAAGGAGTGGTAAGTCCAATGAATAAGGG
          TACTCATCAATTCACCCTGTCCACCTCGTCGAAACGACGAGTAGTATTACGCAGGTTAGA
          CAATAGACTCTAAACTCAGCCAACTTCTTCAACTGACGAACAGATTTCCGGCGACAGCGG

          TCTCGCGGGCACGAAGGTAACCGCAAGTCACTGCGTACGTCTTCAAGTCTCACAGATCGA
          TCTCGCGGGCACGTAGGTAACCGCAAGTCACTGCGTACGTCTTCAAGTCTCACAGATCGA
          TCCTGCAAGTTCATAGGTGAATGCATATGACCGCGTACATCTCCAAGTCTCACGGAACGA
          TCCAGCATATAGGTAACTGATTGTAGGAGACTGCGCCTAGTTGTGCAACTCTTTATCTGT
          ACATTGAAATGTTACGGTAGAACGAGAATATGAAAAGCATTTATCAGACCGAGGCGTTTA
          CTTGACAGAGTAGATCCTAATCAACGAGATTTGATCGCCGCAGCGTCTCTGAGTCCGTGA
          CAACCAAGAGCCGGCAATGATCGACGAACGTTGCCGGCTATAAAGGGACCGGACATCCCA
          AGTCCCGATAGTTTCAAAAGCTAGGTGGTAACGTAAGTTGCTAGGTCTTAACGTAGCTTG

          CCAAGCCTTGTAAATCTTATGTATCAAGGGGGAATATAGGGGCCAATTCTTCTCTACGTT
          CCAAGCCTTGCAAATCTTATGCATCGAGGGGGAATATAGGGGCCAACTCTTCTCTACGTT
          CCATACCCTATAAATCTTATGTTACACGGGATAATATAGAGATCGATTCTCCTATACCTT
          TTAACTTTTGTGTACTTCACGCCAAATGCAATAATTTAGAAGACATTCCTCCCGACTTAT
          TCTTGTTCTTGATACTTCAAATCACGCTGAAAGTCGCACCCAGTTCCCCAGACATACGCT
          TGCTGTTGTGTTCACCGCAGCTTCCATCGGACGACGTGCTGAGCGTCTATTGCGCATGTC
          CACCATTGCATGATTACCCGAACACTCAGTGTGTTGTGAATAGTTAGCGCCGCGCGCCCC
          CGGTGCACAACATGTTCCGGCTTGTATTGGCCACCGTATGTAAAGCTCGAAGTCCATATT

          TCGACCGATATAGGCACTGTATCTCAACAGTCCGGGTCGTGACATTATTCGGTGTCGTAA
          TCGACCGATATAGGCACTGTAACTCAACGTTCCGGGTCGTGACATTATTCGGTGTCGTAA
          TCGACCGACATAGGCAAGGTAATTTAACAGTCCGGATCGCGACCTCGCTCTGTATTGTAA
          TTGACCGGTATGTTCACCTTATATTCATGAGGAGGATTGGGCCCTGGTTTTGGATGGTCG
          GAGACGGGTGCGATCGTCTTACGTAACGAGGCACTTTTGGAAAAGACCCCGGTGGCGTCG
          TTACTTGGGTTGTGTGGTGAGTATGTAGGCGGAAATGTGGAGATTAATCTGTGTGGGCAA
          ATAATTAACTCGAGGAACCAATCAGCTGAAATTCTTGAAAAGGCGCGCCAACTACGGAGG
          GCGACAGTCCTGCCTGCTGTGCTCAATGGAGGTGAACCGGTAAGCCGTTTAAGGCGGGAA

          CTGTAAGAACATCAATAACGATGGATGAAGTGGTTAATAT
          CTGTAAGAACATTAATAACGTTGGATGAAGTGGTAAATAC
          CTACAAGGATCTCCATTGCAACCCTCGAAGTTGTATAAAT
          CCACACAGATAACCACAATAAGGGATCGACTCGTAAATAG
          CAAAAGAGTTCCCCATGGGAAAGACCTTATGGTCGAGTAG
          GTTTGAAGAGTAACTCACAGAAGAGTAAGTCGCCAAAGGA
          CATTGGAAGACTTTATCTCGACAGATCAGTCTCAAAACGG
          AGAAACTATTCCGTGACGCATGTGACGAGGTACTAACTGA

