 8 1000
t1        AGGTATCGGGCTTTGACCGTCCTCAGCGCTCCCTCGGGGACGGAGTAGAAGCCGTCTAAT
t2        ATCTAATGTGCACAGACCATCGTGAGATTCCTCTGGCGGTTGGAGTCAGCATCATCTAGG
t3        TACTACTGACGTTACAGGATTGTAAGAGCTAATCGTCCGTCTGTTTGATCAATTCCCAGC
t4        AACCACAGCCGTAATAAGATTGAAGGAACCAAGCGGTCGCCTGTTTGATTAATTCTCAGC
t5        AACCTCCATACTTCTTTTCAAATTGATGGCGCCGGTCGTATCGGACGGCGGTTGCTTAGC
t6        AACCGCCATACTTCTTTTCGAATTAATGGTGCTGATTGTATCGCACGGCGGTTGCCTAGC
t7        TATTCGAGCGTTTCGCCTAACAGTGGGGGTAACTACAAGATCGTTCGAGTGATGCTCGGG
t8        TATCCGAGTGCTCCGACTTATACTGGAGGCACCTGTGTGGGCATTTGAGTGTTGTCCGGA

          GCGGACACCTTACTGGATAGACGAACGCATCCTATGCGGACACCTGCGCGGAGAAAGTTT
          AACCACTCTCGTATAAATAGGGGGATGCACCTTACGCGGGCGGTTGCACGAAAAATCTTT
          ACGGGCAAGCCTATAGATTCTGAAAAATGTCTCGCGCAGTTGTCTACATAGAGTAATTTA
          ACGGGCGAGTTTATAAATCTTGAAAAATATCGTGCGCAGCTGTCTGCATTGAGTAAATTA
          GACTTATTGTTTATTACTCGTACAGGTTATGCCAGGAAGAAGACTGTGTCACCTCCCCAG
          GACTTATTGTTCATTACTTGTACAGGCTGTGCCAGGAAGAAGAATATGTCAGCTCCTTAG
          CACCCCACGTTTAGGGAACAAGAGGAATAGTGCTTGCCAGATATGAGGATAGTTATCTGC
          TAATCCTAGCTTAAGGGACAGGCGAAATAGTCGCCGTCCAATAACATACAAACTATCTGT

          CTATGGTTGTAACGCTTTGACTACGCCGGAACTAGCCTCTTGCGTCCACGTTCTCGAATG
          ATCCACCTGATATGCTCCAACCGGGCCGTAATTGACGTGTTGGGTTCAAGCCGTCGACCG
          AAACTGTTACGGATAAAAGGCTGTGCGACAACTAATAGTTTGAATGCAAGCTGCGGAACA
          ATACTGTCAAGGATACAAGGCTGTGCGACGACTAATATTTCGAATGCAAGCTGTCGCACA
          CGGCTGCCTCACCACCATGCCCGCTTACTACTATGTCCCTGGGGGTCGGTACGCTTTGCA
          TGGCTGCCTTACCATCATGTCCGCTTACTACCAAGTCCCTGGGGGTCGGTACGCTTTGCA
          CTGCAGTACCTGGCCCAACCCTACCTAACTGTGCTTCCGTCCGCACTCTCGTGCTAGTTG
          TTGTGCTTTCTGACATAATACCATGTAATTGGACCTTCGCTGGGACTTTCAAGCTAGTGG

          AATCCGTCCATTGAGACCGGTGGTACTAGCGATTTACTATCCTTGTGCTGATCTTATCAT
          AACATATTCATCGAGTCCGACGACGCCAAACATCCAGTGATACGATACAGAAGTCATCGG
          TATCAACCAATTAAAACATGAGAAGGCAGCGATCCATTGTCTTCACACAGAATTCAGTTG
          CATCTACGAGTTAAAACATGAGATGGCCGCGATCCACTGTTTTTATACTGTACTCCGCCG
          GGCCCAAGCAGTTTTTATAGATTTCACAGCACATCGTCGCTACTTCACTGCGATTGCTGA
          TGCCCAAGGACTTTTTATAGGTCCCGCAGCACATCGTCGGTACCCCACTGCGTTCGCTGG
          TGCCTATATTCGAGCAATGGGATCGACAATACCCTACGGAACTCTCACTCGAATAGGCTC
          CCTCTACATTCTACCATTAGGGCCGGTTGGGCTCTGCGCACCCTTGATTAGTGTAGGATT

          GATCTGGTAGAGACCCTCCGGCCGATGTTAGGTAGCGAAATTCCCATATAAACATGGCGC
          AACGCGCTAGACATCTGCCGTTTGTTTACTCGCTGTGCCGGTTGCGCGCCAACAAAATCC
          GGATCGCCAAGGACTCCCCGGAAGACGATGATCTCTTCCGACCGTGTACGGCTACTGGCC
          GGTTTGCCAGGGACTCCCCGGAAGATGATGAATTCTTCCGACCGTGTACGGCTACTGGCC
          TCATAAAGATATACGTCCTAGCGGCCACCTCACGGTTCGAATCAATTGCTCCGACTTGCC
          CCATAAGGGTATACGTCCTAGCGGCCAACTCACGGTTCGAATCACTTGTTCCGGCCTACC
          TCTCAATTGCGGATCACAGAGCTGCCGCTGCGATCCCCTACGCCTTCGTTATCGCCTACC
          CCCCGACGGGAAACCGAAGAGCCGCCGTTGAGATCCACCACGTCATTATGATTACTTACA

          GCAATACTGTGCCTGCACATAGACCGCGCGTGCCCATTATGCTGAATCTAGTAATAATGA
          TCAGTTGTATGCCCGTGTGCCGAGTAACTGTGCCCATCATGCCCAGTCTCGCGATCACGC
          GTTATGACTTGTCCGTATATCGATTCCGGGTGCCCCCCAGATTTAATTACGTCAGTACAT
          GTAATGGCTTGTACGCATATCGATCGCGGGTGCCTCCTGTACTTAATTGCGTCATTACAT
          GTTATATTTAAGCGATGCGATGCCTTAGAACTATACCCGTGTGTTACTTACCAGGAGCAA
          GTTATATTGAAGCGATGCGATGCCTCCAAAATATACTGGTGTATTATTTACCAGAAACAA
          AGCGTTGGCGGATCTTACGACGATCCTGGAAAATTTGTGAGCTTGGATCCACTGTAGTGT
          AGCAACAGCGGCTTTCACGATGCTCCCAGACGATTATCGGGCCTGGTCCCACCGACACGA

          CCCCCTTATTCTGTAGTTGAATTAGAACGCGCCCTCTACACGTATCTGCTTCCACCCCCA
          GGTCGGTACTCGGCCGCTCAATCGGTACGAGGTCCACAAATGGATATGTTCTTCCGACCT
          GCGTTCACTTAGGCCGGCAAAGAAGTACGTGATTTAGGATGGTATGCACTGTCAACTGCA
          CCGCTCACTTAGGCCGGCGTAGAAGTATGTGATTCGGGTTGGTATACATTGCCAACTACA
          CTGTTTTCGTCAGACGGAAAGCTGTGAGGATCGCTCGCCAGAAGAGTAAGTAGTTCAGTA
          CTTTTTGCGTCAGACGTATAACTGGGAGGCTCGCTCACCAGAAGGGTGAGCGGCACAGTC
          CCGGGTTATTCGACTGGCCAACAATCACATAAGCCCCGGAACTGGGTTCGGGCATTGACG
          CCCGGTTGCCCGATAGGCAAATAAATATCGAAGCTCTTGAAGTGGGTTCAGGCATTAGTG

          TATCGCTGAACTCCATGCCGAGGGAAGCCCTGATGAGTGACACGAGCCGGAGGCGTTAAA
          CCTCGCTAACCTCCTCGCCAAGAAGAGTTCTAATACGTTCTGCAAACTGGGGGCGCCCAC
          TCTTCCTGAACCCACCGTTGGGAAGTGCTCCCGTCATTATCGCGAACTGGGCACATAGGA
          TCTGCCTGAACCCACCGTCGGGAGACGCTCCAGTTTTCGCCTCGCACTGGGTACATGGTC
          TACTGATAGTCTAGGAACGGTCGGACCTTCTGTAAGACCATACTGCTCGTCGACGGCAGA
          TCCTTATAGTCTAGGAACAGACGGACCTTCTGTAACACCATTCCGCTCGTTGACGGTAGA
          ATCGGAGATAGAGCTAGACAGTTCTGGATCTGTTAGCATGGGCTGGGTGCGAACCATCGT
          ATATGTGAATCAGATAGTAAGTTTTAGTATTGCTGGCTTAAGTTGGGTGAGAATGACCGA

          CACCGATCACTTGACTTTACAATGTTGACCTGTAGGCCAACCTCAGTATTGGCGACGTGC
          AATAGAATGCCTAAGCCTACGGTGCACACTATTTAGTGTAGTCGCCCGTCGGCGACGCGT
          TCTCGAGCGATCCGGTACGGATCATAGTCCGGTTTGCCTCTCAAGCGCTTCGTTTTTTGC
          CCTCGATCGATCTGGTCCGGACCGTAGTCCCGCCTGCCTTTCACGCGCCTCGTTTTTTGC
          AACAAGAATTTCGCGTCCTTATTGTAGCCTGGTACGTGCCATATATAGCCGGCCCAACCT
          AACAAGTATTTTGTGTCCTCATCGCAGCACGGTACGTGCCATATCTAGCCGGCCCAACCT
          TATTGCTATGCTAAATGTTCTAAGTAGCGCCGCTTAATCTCGGTCTGACATATTTTTAAT
          CACTGCTACGCTAAATTCCCAAAGTAGCCCGGGCCGACTTTGGTCTGACGTATTGTTAAT

          AGGGACCAGTAGGAGCGAATTGCCACCAGTGATAGTATACATCGATGGAGTCCTTATCTT
          GGGGAGCCACAGTAGTGGATTGTCGCCACCGATGTTATATACAGGTGCGATCTCGGCGAT
          ATGACCCTGTGACACCAACTCATTGCTGTTTGTGGTAGTCGCAGCTAAAATCTAAGCGGC
          GAGACCCTGTGAAATTAGAACATGGCCGCTTGTGATAGACGCAGCCAAAATCCTAGCGGC
          AATAATATACCTAACTCTGCTTTTGTCTTCTATCGCGAACTTCATCGTTGGTCATCAAGC
          AATAACATACCGAACCCCGTTTTTGTCTTCCACCGCGAACTTCATTGACGGTCATCAAGC
          ATGTGACAAACGAAGAAGGTCTTCGACTCTCATCCTGTCAAACGCCCTTACCTCCGAAGC
          GTGCGACAAGTGAAACTGGTTTTCGATTCTCGTGCTGTTTAATGTCCCTATTCCCGAAGC

          AGCATCCTGATCGGTGTCTTAGGGGTTCGCCAGCGGTAGTCACTTTAGCAATCCTGGTAT
          AGCATTCTGGCTCGTGTCGTGAGAAGTAGCCAGCGTTTTTATTTATAGCTAACCTGGTTA
          GGCATCCTGGACTGTGCCGTGAAATACTAGAAGCACTGGTGGATACAGCTACCCTTCACT
          GGCATCCTGGACTGTGTCGTGAGAGACTTAAAGCAGTGGTGGATACAGCCATCCATCATT
          TGAGTCGCTGGTGCTACAGCCAGGCGTTTCCAGCGTCTGTTTGAAAATGATCTGTGATAG
          TGAGTCGCTGGTTCTATAGCCAGGCGTTTCCAGCGTCCGCTTGAAAATGGTCTGCGATAG
          CGGACTTTGAGAGCCTTATTCAGACGGTACAGGTGACCTGTTAGCTAGGAGACGGGTTAA
          CGGGTCCTGACAGCCATACATAGCCTGAATAGCTAGCACCCTCTCTAGAGGATCCCAAAA

          GTGCTTGTTCGAGGGACTGAGAAACGCAAGACCGGATTCGCGCAGCCGGTCTGGGACAAT
          GTCCACCCTAGAGAGAAAGGGGATTGCAGGGTTGTAGTTGAGTAGCCATCACTCGAGATT
          AAACGTGCCCGAGAGCCTGTGCACTACTCGGCTGCAGCAGCGCTGACAAGGGTCTACCCT
          AAACGTGCCCGATGAAGTGTGAACTACAAAGCTGTGGCAGCGCTGCTAAAGGTCTACCCT
          CCTCACTCTAGAGGGGCCAGGACGGCTTAAACTAGTTTCGACACTTTACCTCCGGACATG
          TCTTACGCTAGAGGGGCCAGGACGGCTTAGACTAGTATCAACACTTCACCTCTGGCTACG
          TACTACCTTATCAATGTTGGGTATAGCTATTTTCGCCAGACCATATTACGGTGGGCTAAG
          TACCACCTCTTCGACTTTCAGGACAACTATGCCGGCCCCACGACATTACCATATGCCAAG

          TCTGTTGTGTTTGCCGTTAGACATGGCTCGGTTTCCCGAGTCGTGCAGAAAGATGGAAGT
          AGGTCCGATACCGCCAGCTCATTCGGTTCGGTCACTTGTCATCCTATGATGCACGGGCTA
          ATATACATCGTCACTATGTGTAACGAATGGGTCCGCTAAGCTCTCAGCATAACGGAGTTG
          ATATACATCGTGGCTATGTAAAACGAATGGGTTCGCTAAGCCTACAGGATAACGACGTTG
          CTCATCATCAAAGCGGTACGAGTGCGATGCGGTTATCCGAGCTAATCGACAAGGGGACTG
          CCGATCATCAAGGCGGTACGGGTTCGATGCATACGTCCAAGGTAATCGACAAGAGGACTG
          ACAGCGGCCACCGGTATACGCCATTTATTAGGCAGTTCGGGTAAATTCATATGTGGGTCG
          ATAGCGATATCGTCCATACGCCACTGATTTGCCAGTTCAGGCTGAACAATACCTGGCTTG

          TCAGCATGCAGCTAGTATCAAACGTAGTAAAGTTAAGTGCCGCTCCATTTTGGAACTGAT
          CGATTCTGCAAACCTCATCACACCGGATGAAGTTAGGGCTCTCATCGTTTTGGAGCCCCT
          CGGTTCCGAAGTTCTTATTAAATGTGATGGAAGTTTCGTGCCACTCGTGCTGGAACCCTG
          CGGTTCCTAAGTTCTTATTAAATGTCACCGAACTTTCGTGCATCATGTGCTGGAACCCCG
          CGCATTTCTCGAGCGATTTACACGCGACTACACAAAACGGACCGCCCATGCGTGATATCA
          CGCATTTCTCGTGTGATTTCCATGCGACAACACAATATGGACCGCTCATGCATGGTATCC
          TGTAAGCACTAAGCGCGTTTCACCGGGATGTGCCTAGAAAGTCTCTATTTCCAAACTTCC
          CGTAGGGACTGAGCACCATTCATCGGGAAGTGCCCGGGACGGGTTAATCTCCGAACGTCG

          AAGACATGTTTGAGTGCCTCTGGGGATGGACGGAGGCTGGTCGCACGCCAAGCTTTCGTA
          AGGATGTGTTGCGCTGCCTCCCGAGACAATCGCAGGTCCGCCCACTGACGAAAAATATGA
          AGTATGTGCCTGATCTCCTGTGGAGACCACAAGTGGCTCGCTCGGTCCTGGACTCCAGGC
          AGAGCGTGTCTGATCGCCTGCGGGGACCACAGGCGGCTCGCTCGGCTCTGGGTTTTAGGC
          GGACCGACCCCAGCCCGTAACGGTGTAATGTGGATGCGGGCTCTACTAGATTAAAGTCGT
          TGAATGACCTCAGCCTGCAACGGTGTAATGTGGATGCAGGTTCTACTAAGTCAAAGTCGT
          AAGGCATGCATCGGCAACTACGGTGTCAACGGGCCGAAAAACCCCCGCGTTGGACATCGT
          AGGGCATGCTGAAGCAACACTAGTGCCAGCAAGGGGAGGAGCCTCTTTGCTCACTGATGC

          TGGTATCCAAGTTTTCGACTCAAAATGCTACAACGTGTTGTATTGCACCTACTCCTGAGG
          CGCTTTCTGAGCCTTCCCCCCAGGACGTAACAAAATGTTCCAAAACGAGTCCCCACAAGG
          TACCCTCGGCACTTTACATAGGTTATGACACAATAGTTCGCGCTAAAGGGTCTATCGAGG
          TATTCCCAGAACCTTTCACACGTAATGACACCATACTTCGCGCTAAAGGGTCTATCGAGG
          GAACATTTAGCCGTTCCTACTGCGGTGACGGTGTCACGCCACTTGAGGGCCCTTTCGAGC
          GAACATTTAGCCGTTCCCACCGCGTCGCCGTGGTCATACCACATGAAAGTCCTTTCGAGC
          CGAGAAATATGCGTTCATCACAGGCAATTAGATTTGTACCCATAAAGGGGCCTCAAAAAG
          CGAAAAATATCTGTCCGCCACAAGCTACCAGACCAGTTCTAGACAAGGGGCCTTAAAAAG

          TACGGTGGATCTGCGCCGACAGATCGAACCCTTTACCAAT
          CTTTGTAGCTCGTCGTTGCCAGATCGAGCCCCAGCCCAGC
          TATTGTCCCCCCGCTTAGTAAGTCTGAGACTGTTAGGTAG
          TATTGTCCTCCCGCTTAGTAAGTTTGAGTCTGTTAGGTGG
          TGATTGATAGTCTTTCGCTCACCCATAGCCCTCTTGAAGC
          TGAGTCCGAGTCATTTCCTCGCTCTTAGCCCTCCTGAAGC
          TCCTATAATCGGCTTTGTGTATTCCCTGACCCAAGCCTGT
          CCTTTTGCATCCCTTTCATTGTCTCAGGACTCATGCTTGA

