 8 1000
t1        CAATGCGCGATAATACCCAAGAGGGTGTGCTTTCTATAAAACCGTACACCCTCCGCCCGA
t2        TAATGCGCGATAATACCCAAGGGGGAGTGCTTTCTACAAAACCGTACACCCTTCGCTCTA
t3        CTATGTTTGATAATAACCTAGAGGGCGGGTTCTCTGTATAACCGCACACCATCCGATCGC
t4        CAGGATCTGAATAGGTCTCTAAAAATGCGCGCTCCACGGAATTGTGTTGCTACCGTCGCC
t5        AGGGGTGTGGTGCCACTTCTAACTTCTGGGCCCTCATTATAACATGTAACGGTCACAAGT
t6        TGGCCTACTACTACATTATCCTGAATTCAACCGATATAAGAATAGAACCGAATGATCATC
t7        AGACATGCGGAGGCAAGCCTGGTAGCTCTGCCCTCCAAGAACTGCGTTCTCAGTATCAGT
t8        GAGAGTGCGTATCTGAAGCTCGTAGGATGAGCTCCTTGAGCTCACAATTTCGCTGACTAC

          CTCATTTCGTGTTTTAGTGTAACTGCGGCGATAAAATTCTATCCGTAAATTTCCACAGCC
          CTCATTTCATTTCTTAGCGTATCTGCGACCATACAATTCTATACGCAATTTTCCCCAGGC
          ACTGTCCCATCTACTTATGGACCTATGAACCTACAATTATACTCGTAACTATTTACGGGC
          CCCATTACGTCTTTCAATAAATGCTTTAAACTAGAACTATATCCAAAACCTTTCCTGGTT
          TCCACGTTATTAACAGGTGGATCCACAGACGCAGAATGTCAACTTCTTCCCCCAAAGGAG
          CTTCTCTTACAAAGTGGCTGCCGTGCGCGCAATAACCATACCCTTTCACCATCATGGGTG
          TCTACCTCATACACTTGTGAAGGCGAACGCATACAGTGTTAGCCGTTACGCGTCGAGGCG
          TTTTTCAGCCCACAAATTTGTAAGAAGTGGGTGATGCCCAGCCCCTGGCAATCTCAACTT

          ACTGATCCACTGCTCTGCTTCTCGTCTAGCCGGCCAAAACTTCTTAACGGGACGAGCGCT
          ACATACCCACGGCCTTGCTTCTTGCCTAACCGGCCTAAACTTTCTAACAGGTTGAGCGCG
          ACACTCCGACGGCTTTAATTCTTGTTTAACAGGTCCAAACCTCTTGATAGTACGGGCGCC
          GCATGCTCGAGGCTTCTACATCTCTGGCCTCACTCCAACTTATCTAACAGGAGCAAAACC
          TCACATTCAGAACGTGCTAATTCCTAGACCCTACTTCACTTATCTTTTGAGAGAGGCAAA
          GTTTACGCGAGACCGATATCTCGTTCACATCCGTCTCTAATATTCCATCATGAACCCGTC
          GCAAATCAGAAATCCTAAGAGGCATGAAACTCTGTCACACACACTTTTCACCCACGTGCC
          TTCCCTCGAAGATCGGTACCTCTCTGAAACCCATACCCCCAATTGGCCAGAAAAAACTAA

          ATCTGGCGCGATATACACCCAAAACGCAGGTAACCTAGGACCCCGTGACGCTTCTCCCCC
          GTCTGGCGCGCTATACGTCTAAGAAGCCGGTAACCTTGGACTTCTTGACCCTATATCCCC
          CTCTGGTGCCATATACGGACAAATTGCAGTTAACACCGGACCCCCCGACCTTACACCCAC
          CCACGACTTAGAAAGTGGGGAAAGGGTTAGCCGCACCCGACCCCGCGGATTTATGGATCA
          AGATATTAGGAGGAACGCCTAAATGTAAAACTACTGTGAGTCTGTCGGCCTATAACAGTC
          GATGATATCGGGGAAGGGTTGTCGACATATTGCTTCTTATACTAGCTGTTATCCCGTCCC
          GCCTGTGTTAGCGATCGGCCGAATTAATGGACGGATGGGTTACGGCGAATTCAGACTCCT
          AACCCTATCAGAGGAGGACCGGGCACCCACGTCTTGTTTGTTCGCTATAACTATATGCCC

          TAGAGAGCGGGTAAGTAGAGAACGTCGCACAGACGTGTGCGAGATGACGTCCCCCGAGAT
          CAGAGAGCGGGTAACTGGGGAGTGTCGCATGAATATGCGTTGGATGACGTCCTTCAAGAG
          TCGAGAGCAGATTTATGAAAGACGTCGCATGAGCATGCGCAAAATGACTTCCCTCGAGAC
          CTGGATGCGGATATATCTAGCAAGTGAACCGCACACGCGAGAACTTCTCCCCCGAGGAAG
          GGAAGTATAGATCAGCAAAGAGTTTTTACTGAACAAATATGTAATGCCTTAACACGACAT
          CCGGTGCCTTATTGTGGCGGGGCCACTGTCCTGCGCAAGGGAAAAGTTTTTGCGCGCGAT
          AGACGAGCAACTCAAAGAGTAGCTAGGCTCGATAGAAAGAAACTTTCCACCCACTGCGAC
          CCGGAGGGAAGACAACAGAGGCCAGGAGCCAGACAGCACACGGTCGACACCTCGCACTCC

          ATAAGGATCCCTGCCCTTAGGCAAGCGCTTAACGCGACATGAAGCTGCCTCACACACTTG
          ACAAGGATCCCTCCTCTTAGGTAAGAGCTTAACGCGACATGAAGTCGCCTCATACAATTG
          AAAGGGATCCCTCCCCCTACGTAAGAGCTTAGCGCGACATGAAGTCGCCTTACACAATTG
          CAGCCGATCCCCCGACCTAAAGGAACCGTGTATACCATGTAAAGAAGACTTCTCTCATTG
          ACAGGGACTCTGATTCCAGCTCTGAAATCTCTCACGCCCCGGAGGAGTCTCACACTCGGT
          TGAGCGACCGTATACACTGGGCCAACACCTCGACTTGAAGGTTGTTAGCTCCCGTAATTG
          TACGTGGCTCCATTCCCCAAATCACAGGCTTTCATTAACCATGGCTCTGAGCCTTTCTTG
          GTAACTAACTCGAAGGCCGCGGTGACCATTCTTTTGAAATGTGGGCGGTCCACCTCGCCG

          GAGTGCTGCCACTTCACCCAAGCGTATATCCAACTCCACCCGCGACGGTTACCCTTTCTG
          GAGTACTGCGACTACACCTCAACGTATTCCCAGCTTCACCCCCGGGGGTTTCCTTTTCTC
          GGGTACTGACGCTGTACCATAGTGCAGTTCCAGCTTCAACCGCGCCGGCTCCCTTCGACG
          CCGTATCGCCACACTACCGAATCGCAACCTCAGCCGCACCTGCTCCGAACCACGAGTCTA
          ATATGTCGCCGATTTACCTTTACGCGGTCATATCACCGCGAAATCCTACGTTCTCCGTGG
          TTCAGCCGATAGCGTTGCCCGGCGCGGCTCCAAGTTCACTTGCGTCGAGTTCCTGACTGA
          ACTGGCTGATCGAACTATTCGGCAGGAATCAAAGCTCAACTGATCTGAACTGAACCCTTG
          GTCGTTATCAAGCACCACTCGAAGAGAGCGAGGTCTGTGCTGACTTGTGTTTCTCCTCTG

          TACAGAGTAGTTGATTATGTTCTGCAACCTCGGGTGGCGGATTCAGATGCCTGATCCGGA
          TATAAAGGAGTTGATCATTTTCTGTAAGTTCGGGTGACGGATTCGGACGCCCGATCCGGA
          TAATGAGTAGTTTATCATGCTATCCAACATTGGGTGGCAGATCCGGACGTCCGAGCCAAA
          TTGAGAGCAGTAAAATATGTCATGCACTATTGCGTGGGTCGCTTGGATGTCAGGTACGAA
          CAAAGCCTGGCAGACCATTACACGTATTAACGTACCGCCCGTCCTGAAGTCGATAAAAAA
          CAACAGCTGACGGCATGTACTAGAAAGCGATGGCCGGCAGACCTCGTGGACTTATATAGA
          TAACCTCTTCTAAACCATGAAGACATACTATACGGGAGGGGACACGGCCTCAGGTACTGA
          CAGATGCTAATCGACACTGTCCTCCACGGTAAAGCGGTAGGCGAAGACGTTGCGCTGACC

          TGGCGATGAGTGCCACGGTCCTGCGTTCCCGGGCAGAGTGGTTTTCGGGGTAATGTCGCT
          TGGCGATAAGCGCGACGGCCTGGCATTCCTGGGCGGAGTGGTTCCCGGGGCACTGACGTT
          TGGCGACAAGTTCCACGGCCCGGCTTCAAAGGAAAGGGTCGTTTTCGGGGTAACGTCATC
          ATAGGAAAGATTGAACGGTCGGACCCCCCTTAGTCGCGTAGACCGGTGTATATTGGCTTG
          ATAAGAAAGGCCACTCGGTTCGATGCCACAGGGCTGAGTGGGCAGGTGAGTGACTGACCT
          ACCTGCCGGGGTATGAGTTGAGGAAGGGTACGTCTTTGATGCTCTGCGACGATTAACCCA
          GTATACTGAACTACGTATCCGAACGTACTAAGGCACTGTCGTTAGGAGAAAGAGAAGACC
          GCGTATCGGTTCTCAGGGACCGGTACACCTAAATGAGAGTGTCAGAAAGAGAGTTCCACT

          ACAGCTCTCCTACAGCCGCCATTTCAACTGATGACCTAAGCCCCCTGATATGGAGTGAGT
          ACAGCGGTTCTACAGCTGACACTCCAAGTGATGGCGCGAGCCCCCTGATACGGCGCGAGC
          AAAGCCGTCACAAGGCTGTCATATCAGCTCATGACGTTGGCTCCTTAATACGGTGTGAGT
          ACAAGGATTGTACGGTTGTCAATACAAATGGTGTCGGATCGCTAGCGGTTTAGGTAGAAC
          ATGGCGGCATCTATATTGTTACCCTGGGCAGCGTTGAGACTTTCCCAACACCGCGCGATT
          TGGAGCACCCACAACTCGTTACTACAAGTAGGATCGCCAAAGACCAAACGCGGCGAGACT
          AGTAGGAGCTTAAGCATGCAAGTCTGGGCGGCACCACGATACACCACACTCGACGACAGC
          CTAAATGCCTTTGTATTGCGGACTCAGACAGAGATGTGGTAAAGTGAGGACGTTGCAAAG

          ACCCAAACCACCCCATCATTAATAACGGAAGCCTACCGGCGTCGCCGCTGCTAAGGGGTC
          ACCCAAACCATCTTATCATTAATAACGAAAGTCTACCGCCGCCGCTGCTGTTAAGGGGTC
          ACCCAAAACTCCTTATTGTTAATAACGGGAGTCGACTGCTGCCGACGCTGCCGGGGGGAT
          ACCCGAGGCGATCTATAACTAGTGAGGGAGTTACGGTGATACCGACGTCAGCTCAGAGCC
          GCTTCTGTAACCCCGCTATAAATTATGGAGGCTTACCAACGTCATTGCTGCCTGATTGCT
          TTTTTAAGAACCCTACCATAAACGGTGAATAAGCAGTGCCGCTGGCACTGTCGAAGCGTT
          CCTACCATCATCAAATCACAAACACAAACTAGAACCCGCAGGCACGCTGGGTTATCGGGA
          CTGGAAACCTCCGGATAAGGTGCCACGGAGCTATAGTCTAGAGGCATCGGACTGGGCGGA

          CGGGCCCTACGCAGATTGGGTGCCTTAAAGTGAGGAGCGCAGGCCGGTGTGTCAGCTCTC
          CGGGCTCTACACAGATTGAGCGTCTTCACGTGAGTAGCGCGGATCGGGGTGTCAGGGCTC
          TGGGTCCCAAGCAGATTGGGTGTTTATATGTTCGCAGAACAGGTTGCCGTCTCAGGTCTC
          TGGATTCCACACAGTTTAGATACTTGCACCTAGACTACTCAGTTTGTAGACTTAAATTCC
          TACGTTTCAAACGAATCAGACGGCTGCGACCAGGTAGTCCGGGTCGCAATTTGTAACGCG
          TGAGTTTTAAATGGTACTGATACTCCCGCATAGACTGTATAGTTTTACGAACGGGACCTT
          TTCGTCTCGGATCTACTCCGTGCGTATGCTCAGTCGAGACGGTGCAATGGCTCCAATTCT
          CAGTTTCGGTGACACTTCACAGTCCACGCCCCGGTCGCATGTTTCCACCCTGGTTCGCAC

          TCGAAAGCCCCCATCGCTGTTCGAATTGGATGTTCCAGTGGGTCTATCCAGGTGTGTTTG
          TCGAAAGTCCACATTGCCGTTCGATTCGAGAGTCCCAGTGGGTCCGTCTTGGTGCCTCTG
          TCGAGAGTCCGAATTTCTGGTGGAATCGGAAGCGCCAGTGAGCTCGTCCGAGCGTGTTTG
          CAGGAAATATGCATAGGCGTGCGCAATCTACATGGCCGTAGACGCTCCTTAGCGCCCTTG
          TCATAAATCCACGGCCTGGAATGAGTATCGAAATTGTGTCGACCTTGCCTGTGGATCGTG
          CCGAATTGCTGAAACCTCATGGATAGCACGTGAGCGTATAAGCCATCAGCAGCAGTAGCG
          TTTAATGGCTGTACCTAAGCAAGCTCAATGGATACATGGTAGGTTCATGCGCCGAAGTTT
          ACGAGTGGTTGATTGTTGCTAAGGTTTACACATGTGCGTCAGCCAACTACTACACTTCGT

          ACTCAGAATCGGGTGTTCACGACGCAATCCGGCCCTATTATCTCTCGTATCCAGCTATTT
          ACTTCGGATCGGGCGCTCACGACGCAATCCGGCCCAATTATCTCTCGTAAAGAGCTATTC
          AAACCGACATGAGTGGTTAAGACTCAAGCCGGCGCCGCTCTCTCTCGTTTAAGGCTGGTC
          TCCTTAAGTAACGGAACTACGACACTGGTCAGCACACAGATACCTCTTCAAGTTTTACTC
          TACTTGGGAGTCACATTTATTGCATACCTTCACCTTGCTTACCTTGGGTAATTGCTCCAT
          TTCATGGACCGGGGGCCCATTATCTGTTCATGTACGTCTTCCATCGGTGAGCCATTATGC
          CACATGGGATCCGTCATTGTTGCGGAGTTAGGCTTCTTTCACCGTCTATCTGCCCTTTAC
          TCGCTAGACTATGGGTTTACGGTAAGTACAACCATTCTCTCCATTTGCGAATCCTCTACA

          AAGCGCCTTGGACTCGCTCTTAACTAGATAGCCAATCAGGACTTTAGAATAGTTCGGCCA
          AAGCGCTTCGGACATGCTCCATACCGCATTGCCGTTTAGAACTTCGGAATAACCCGATCG
          AAGCGCCCTGTCCTTGTCCCATGCTGGATAGTCACTCAAGATCTTGGAATAGTCCCCGCG
          GTAGACCGCAGTTGCGCATCAGCCCTGCTAGATTCTAAGGAATATGGGGTCAGCGCGGTA
          TGACGGCAGAACCGCTAACTAGCAGAACTGACCCCATGGCGCCTTGGTTTCGATGTATAA
          CAGCACACCGCCCATATTGTGTGTGGGACGGGCATGGAGAATTTCCACTCGGGGAGATGG
          GAATACCCGGACCGCGTAGCCTTTGATCTCACTTCAGAGGAAGGTGGGTCCATACAACTA
          CCAGATCCAGTTGGTAAAGAAAGTCGCACTTTAGGGTGGTACCACACGATTGAAAGCACA

          GCTTAAATCCACTTGCTTCTTCGAACGAGTTACATCGGATCCCGGTCCGCGACCTATGTG
          GCTTAAATTCAACTGCATCTTCGAACGAGTTACAGTGGACCCCGGACTGTCATCTGTTCG
          GTTTTAAATCACTTGTGTTTTCGAACGGATTATCCTGGATCCCGGCCCATCACTTTCGTG
          GGAAAACTCGCCCTACTATATCGATCGCTCTACTTAAAATTACGGATCATGATCTTAGCG
          GCTCGACGTGGTTGTTTCTGCCGCTTGGAATATGAAGAAGCCTAGATTGCTGCTTCGGGG
          AATTATGGACGCCTCTTCGTTCGTCCGGCCAGCGTAAGATTCTGAATCGCAATCACAGTA
          CGGTGACGTCTTCTGCTGTTGAGCCCGGCCTGCCAGGACACTTAGAACGATGGCCTAGGA
          GGTCAGCATTTCCTCATGCCCAAAGCGGTTGGATCAGGCTATTGTGCCAGCACTTTATAG

          GTTGCTTCGTTTGGGTGAACCGGGGTATATTACGATAGTA
          GCCGCCCCACCTGGGTGAACCGGGGTATATTACATTAGTC
          CATGGCTTGTTTGGGTGATTCGGGATACATTATGTTAGTC
          AAGAGTTTAAGTGTGCGGCACGGCGAGTCCTACTTGACTT
          ACGGAGTCGATTGAAAGAAGAATCAAATTTCGTTTTGATT
          CAAATGCTGAGTTAGGGATACAGTATGCTGCGATCCATAT
          AGGATTTCGGGTGTGCGTTCCAGCGAGATTCGCCTCATCC
          GGGGGGCCAGTTGTATAACGAGGATCTACTCTTTTGCAGA

