 8 1000
t1        ATCCTTTTTTGTAGGAGGCCTATCTATCGTTCATACTGTACATCCCGATCCCATAAGCGA
t2        ATCCTTTTTTGTAGGAGGCCTATCTATCGTTCATTCTATACAGCCCGATCCCATAAGCGA
t3        ATCCTTTTTTGTAGGAGACCTATCTATCGTTCATACTATACAGCTCGATCCCATAAGCGA
t4        TAACCTTTTCATAGGGGGCATACCTACCATTCATCCTCTAGATCCCGTAGCCATGAGCGG
t5        CACTTGCTCCGCAGGAAGTCTGCGCCTAGCTCTTTGAACAGACCTCGTACATATCTGCTG
t6        CTATTACTTTCCAGGTGGTGTGCAAACAGCCCATATCGTAAACACCGTGTCCGTAAGCGG
t7        TAACCTTATTCCGCAGCCGCCGCCTACAGCCTACTCCCTATCTCTCAAGTGTTATTGCGG
t8        TGATCCCTTTTAGGAATTAGTTTACAGGACGAAAACGACACAAAATACACCCACTGCTTT

          TCTTCCCCTACTGTGAGCTTGTCCTAGGAATGATGCATTACCCATTGCGCACGCTGCCTA
          TCTTCCCCTACTGTGAGTTTGTCCTAGGAATGTTGCATTACTCATTACGCACGCTGCCTA
          TCTTCTCCTACTGTAGAATTGATCTAGGAATGTTGCACTACCCATAGCGCACGCTGTCTA
          CCCTCCGTTATTGTGGAGCCTTTCTACGAACGCTACATCACCCGTTGCGCGCGCCGCCTA
          ATATCCCTCATTGTGGGACTTTCGCAGGGATATCGGTCTGTCTCTTCCTCGTTTAGCCTC
          TCGCCTTTCGTCATGGGCTCTTTATCGGAATGATGCGATAGCTAACGTACGTGCTACCAA
          CTGCCCATTGCCCCGGCTACGCCAAGGGGATGTTCGTATTTCGACGTAAAATATTATAAA
          CTGATCTAATTTAAGGTCGTTTTGTCGTTATGCTAATACCTACTGGTTCTAGGTGATTCA

          GAAGGTTCTGTGGTAGTGTCACAGCCCGGGCACAGAAAGCAAGGCGGCGTGATTGGTATG
          GAAGGTTCTGTGGTAGTGTCACAGCCCGGGCACAGAAAGCAAGGCGGCGTGATTGGTATG
          AAAGGTTCTGTGGTAGCGTCACAGCCCGGGTACAGTAATCAAGGCGGCGCGATTGGTATG
          GAGGAACCTGTGTTAATGACATGACCCGGGTACAGAAAGCAAGGTAGTGCGACCGGTATG
          GCAGGTCCCAAAGAGGAGCAACACTGTTGGCGACACCAGCGGGGGGACGAGACCGGTAAG
          GCTGGTTACACATTTATGCAACGCCGCCGGCATTGAAAGCATAGCAACGCGAACGCTCAA
          CAAGCACTTATAAACATACAATACAAAGCGTTTTGCATCTAACACGAGGGGCCGGGCTCA
          AAAAGTTTTACAGGCACACGACATAGTCACTCCCCCATAACGGAACGCTTGCGCATCCTG

          CATCGATCGCAAGCCCTACACCGTGTACCCTGACCTCCAATTTAGTCTGAGAGTTGTGTG
          TATCGATCGCAAGCCCTACACCGTGTACCCTGACCTCCAATTTAGTCTGAGAGTTGTGTG
          CTTCGACCGCAGGCCCTACACCGTGCACCTTAGCCTACAATTTAGTCTAAGAGTTGTGTG
          ACCTGCCCGCAAATTCAGCACCGGGTATCTCGGCCCTTAACCCAGTCTGAGATTTGTGTG
          TCATAGTATCAGCTTAAGCATCGTTCATGTTTGCCTCCCGTACTATCCGAGGCATCGGTG
          ACTCACCGGCAGTTTAAACACAGTATCTGTTGAGACGCGATCCTGTCTGTGGTTTAGGTG
          CTTCAGGTGCAACTTAGGGACAAGCTTGCCTGGCACGCTGCCTCACACAAGCTTTCTTTA
          AGTTCTTAATAGACCTAGACCGTCTTGCTTCGGTTGGGGGCTTTGCATGAAACGGTGGCC

          GAGTACCCCGATGGCAAAGGTACGGACCTGACATCGAAGAATTAAGTCACGTCAATGCCA
          GAGTAACACGATGGCAAAGATACGAACCTGACATCGAAGAATTAAGTCACACCAATGCCA
          GAGTACCCCTGTGGCAAAGATACGAACCTGACATCGAAGAATCAAGTCACACCAATGCCA
          AAGCACTCCTTTGGTAGAATGATGAGTCCGATATCGGCGAATTAAGCCATTTCATTACCA
          GAATTCTGCCTGGGTGAATTAGAAATTACGATATACGCTAACCAATTTGTGGAGGTCGAG
          ACGGGTCTCTGTCTCACACCAGACGACCTCTCATCGTCTATACAAGTTAGGTCAAGACTG
          CGGAACCCTCCCGGTGCCTTACCGTGGGTAACTGACGTTAGACCTGAGCTAGCCAGCGTA
          ACACGCATGTAGGGAATCGTTGTCTAAATGACGATGCACTAGAATGATGTGCCAACCGCT

          TTCAATGGTGCCGCCATCTATACCCTTCGATGTTTATAGGCCGTAACTGGCCCCTGTCTC
          TTCAATGGTGCCGCCATCTATACCCTTCGATGTTTGGAGGCCGTAACTGGCCCCTGTCTT
          TTTAATGGTGCCGCCATCTATACACTTCCATGCTTGTAGGCCGTAACTGGTCCCTGTCTC
          GCTCCCTGTGTAACTGTTAGTATTTTTTTGTTCTTGTAAGCCATAACCTGCCTCTGTCTC
          TCCACATATGATGTTCCCAGCAATGAGCTTTTCCTGTGACCGGTAACTAATTCTCATCTT
          CCACAAAGTTACGCTATTTGCAAAGTCTTCGGCACGCAGCTTTCAACTTGTCTCTCTTTC
          TTCGGACACGCCACGAACTACACGGATCATTGCTCACAGTATATCAACCTTATCGGCACC
          ATGAGATTCGATAGTACTGGGACGGAGCACCGAGGACTATGCGTTCAATCCCATGATTAG

          TGGTCACTGGAATACTTGAGGGTGCTGAACCCCGCGACGGCATGTTTTAGCCCGCTCCTC
          TGGTCACTGGCATACTTGAGGGTGCTGAACCCCGCGACGGCATGTTCTAGCCCGCTCCTC
          TGGTCACTGGAATACTTGAGGGTGCTGGACACTGCGACGGCATGTTCTAGCCGGCTCCTC
          TGATCTCCGACGTCTGTGAGGGCATCGATCCCTCCGAAGGCGTGTCCTCGCCCGCCTATC
          TGGTCCAATGCAATAAGGGTCGAGCAAACCACTGCTATGGACCGTTGACGACCATTCCCT
          TCAGCATGGGCAACTATGGTAGAGCGAAATCGTGTTATCAGCCATCCTATACTGCTATCT
          CAACTACTGGCGTATTTGGGAGAATGATACGCAGACATCAGATATTTCGGCCGGCTTGTC
          CTCTAAAGTGCTTCTCACGATCATCATTTCCCCGTTACCGAACGGCTTAATTTTCCCATA

          GGGTACCAGCGCACAAGACATGGCATTCGTCTAAACAGCCGAGTTACGCTCGACTACTCC
          GGGTACTAGCGCACAAGACATGGCATTCGTCTAAACAGCCGAGTTACGCTCGTCTATTCC
          AGGTAACAGCGCACAAGACATGGCACTAGTTTAAACAGCCGCGATATGCTCGACTATTCC
          GAGTACCAATCTACAAATCGTACTACTAGTTTACACAGCCGCACTATACCCGACCATTCA
          TGCGGCCAGACCTCCGGGTACTGTGCCGGCCCACGTCGCTGGGTCATGACTACCTCGCGC
          GGGAACGTATTTCTCGTGTATGGTACCCGAAAAGTTGAACGCGTATTGTCCTACTATCTC
          CAGTAGCGACTTCGTTAATACGAGATCTATACACTTGACCCTCCCACATGCCACCCCCTA
          GGTAGCATCCGCTCGGGATTTAACGCCCGTGCCTCCAACTCCACTTCAACTCATCCCTGG

          AACTAGGAGCTAAACGGGATCACTTCTATATTCAGTAATGTGCACTTGGAGCGACCCGAG
          AACTGGGAGCTAAACGGGATCACCTCTACATTCAGTAATGTGCCCTTCGAGCGACCCGAG
          AGCTGGGAGCTAAACGGGATCTCTTCTATATTCAGTAATGTGCCCTTCGAGCGACCCGAG
          AATTAACAGCTAGACGGGCTATATCCTATGTTCACTAATGTGCACCTTGAGCGACTTAAG
          AAATCGTGAACATGTGTTTCGTTTCCTCTGTTTACCGACCAGCACCTCGAGCAAATCAAC
          AAATGGTGGACAGTCGACCCGCTCGCACTTTTTCCGAGCGTTAGTCTCGGGTTGTCCAAG
          TAGCGGCAGTTGGACAATTTACTCGCTTGATTCATGAGTAAGTGCATCGAGTGAGTTGGG
          ATTCGAAGGCCAATAGGTTAAGCAGCATACCTTGCTTACTAACATCGTAAGTCATTCGGG

          GTTCAATATACTATTTAAGGTTCGCGGGGTTGTCGCTGAGGACTCTATCCAATATCTGTC
          ACACAATATACTATTTAAGGTTCGCGGGGCTGTCGCTGAGGACTCTATCCAATATCTGTC
          ATACGACATAATATTTATGGCTCGCGGGATTGTCGCTGAGGACTCTATCCAATACTTGTC
          ATACGTCACACTCCCCACGGCTCCTGAATTCGTCGGCGACAACTTAGTCGTTTTTCTTTT
          CAAGCTAGCGTCTTTTCCTCATACCGCGCCTATTAGCAGGAACTACTATCTGTGAGTCTC
          CCAGACAGCCACCTTCATGCCTTCAAGATCTATCGTTTGGAATCATCGGATGCTCCCCTC
          TAACAAGATCTACTTCTTACTTCCCACACTCTCTGCTCAGAACTAATAGTGGCGCACTAG
          AGATGGTAGGGACTGAGTGCCGTTGCTGGGCATCGTGGCAAAAAAACTAAGACGTCCTAA

          GATAACATGATTAGAATACGACCGAGTTGAGGTTCGACTGGAGCTCCGGTGGCCTAGTTA
          GATAACATGATTAGAATACGACCGCGTTGAGGTTCGACTGGAGCTCCGGTGGTCTAGTTA
          GGTGGCACGATTAGAATACGACCGCGCTGAGGTTCGACTAGAGCTCCGGTGGCCTAGTGA
          AATAGCAGGATTTAGACGCGACCGCGTTGTGGTCCAACTGGAGGTCCGATGGTCCATTAA
          CATGGTACAGTCCACGTGTAGCCGCTGTGCCGCCCCCCCCGAGCGTCTGGAGTCCGCGCC
          AATATCACGTTCGAAAGATATTCATGCCGTAGCTCCCGCGGTGTCTCGACAGTCTTCCCA
          TGTGACACATTGACACCCAGAAGACGACCTAAACTGCCCAAATATCCGCTGGACTCCTCA
          ATGAGCTCTCACCGAATGGGTGTCTATCATGGCCCCTCCTATGATGTAGTGGAGTCTGAG

          CTGCGACTCATACCTAGCTGAGGCGCACCCCGATCCCTTAGTGCTGGATGCCATCAACAC
          CTGCGACCCATACCTAGCTGAGGCGCACTCCGATCCCTTAGTGCTGTATGCCATTAACAC
          CTGCGACTCATACCTAGCTGCGGCGTACCCCGATCTCTTAGTGCTGGATGCCATCAGCAC
          TTGGAGCTCACGCATGGCTACGACGAACTCTGAGCTTTAAGTGGTAGAAGCCATTAACAC
          TTTAGGCAGGTGTCGCATTGCACTAACCCACGACCCCAGAGACGTAGGTAGTATAAACGC
          GTGAGGTCAGTATATTACCGCGATATGCCGTGAAACTAAGGTGGTGGAGACCACTAGCAT
          GCTAGGCTAAAGTATTACAGTGGAAGCTCTAGGACCTCACGGGCCGGTTCATAATAGGAT
          GGGCTAACCTACACTGGATACAGAATCTTTAAGCACCTATGGGGTTAACCGCGCAGGGAA

          GAAGCGGGTTCGCAAACCTCGGCTGTGGCTCTGAACTACACTGCAGGCCGACTACGGTTG
          GAAGCAGGTTGGTAAACCTCGGCTGTGGCTCTGGACTACACCGCAGGCCGACTACGGTTG
          GAAGCGGGTTCGTAAACACCGGCTGTGGCTCTAAGCTACACATCGGGCCAACTATGGTTG
          GAAGATACTCTGTTAACCTGGGCTGTGGAACTTAGCTATCTAGCGGGCCGACTGCTGCAA
          GTAGTAATGTCGACCCACGGAACCGCTACATGGATTTGTGCCACAGTCTGAACCCCGTGG
          GCGCCGACGTCGCTGATTGTGACTGGCAGACAAAGTCTCGTCGCCCGTAAACTGCTGCGA
          GTGCCAACCTTCTCACACGAGGTCATATAAAAGCACCAAATCTCTGATCGCATCTTTGGA
          GCTGTACTAAAGCCATATGAGAGTTTAGTGCAAGGTTATCTAGTGCTATGGCAGCTACAA

          AATCACCGAACGGCCTTGAACGTCGGGCATGATCACGACGCAAACGACGACTCGAGGCAA
          AATCACCGAACGGCCTTGAACGTCGGGCATGATCACGACGCAAACGACGACCCGAGGCAA
          AATCACCGAACGGCCTTGAATGACGGGCATGATCCCGGCGCAAACGACGACCCGAGGCGC
          AATCGTTGATCGGATCTAAATGATGGGTCTAATTATGAAGCAAATAATAGGACAATGCGT
          AATTATGGAAAAGACTCGAAAACAAAGCGATTCTGAAGCCCATATGGCGTTATGTCGCGG
          GACTATCAATCGGAATTCAGCAGAGAGCCCTCTTATAACGAAGTCGACAGCCCGACACTA
          GCCTAGCGAGATTGGCCGGACCTCAGCTGTGTCGTTGGCATGATCGTTAGTCAGGCCGTT
          TGGGATTGCATGTGAAGGTGCCGGCAGCATAAGATCCTCGCGGACATCAACTAGTACAGT

          TGGCACAGGGGGCTATTTATGCTGGCACTTTGGTTCGTGCATAATTTCGAATGCCGTTGG
          TGGTGCAGGGGGCTAGTTATGCTGGCGCTTTGGTTCGTGCATAATTCCGAATGGCGTTGG
          TGGCATAGGGGACTATCTATGCTGGCGCTCCGGTTCGTGCATAACTCAGAATGGCGTCGG
          TGGTAGTGCGGGGTATCTGCCTCGGTGGTTCGGCTCGCGTATCTTTCCGCATGGCGTCGG
          TGGCACAGCTATAAAATTATTCTCGCGCACCGGCCCGCAGGTCAATTTTAATGAAGGAGA
          TGACATAGCCGTTTACCCACGGAAATGTCCCGGTTGTCATGTTTCTACGAATGGAGTAGA
          CAGGATATTATGAGTTTTCCTTCCGTGACTTAAATTGTTTGCCGGTCCAAGCAGGGAGGC
          TGGGGCTGCTATGTTGGTCCTTGTACAGGCGTATTCATGCGACTCTGGAACGGGTGCACC

          ATCTTCATGGGAACTGCGATCCCCGCGAAAACGTCACTGACTTGATCCCAAGCTCTAGTA
          ATCTTCATGGGAATTGCGATCCTCGCGAAAACGTCACCGACTTGATCCCAAGCTCTAGAA
          ATCTTCACAGGAATTATGATCCCTGCGAAAACGTCAATGACTTGAACCCAAGCTTTAGTA
          ATCTGCATAGGACACGTAATCCCCCCGAAAATGGATGTGACATGATCTTCAGCCCCAGTT
          AACTCCATTAAATGAGGGACCCACCCCAGCTCGATGGTATCTATATTTTGCGTTTCCGCA
          CTCTTCAAAAGAATCATAGGCGCGCGCAAGGCTACGTCGTGTGGGCTCCTGGCACCTGTA
          AGTTTCGTGTGTAAGTTGATCGCTCCGAAAGCGGCGTCAGCATAGCCTCCGCCCTTCGGA
          AATATTAACCATAGAGATTCCGTACAGAAAGTTATATATGCTCGACTTTAGTTCTTTGGA

          CTAGGACAAAGTGACATCCGTTGGTTGATAATGGAGGAAA
          CTAGGACAAAGTGACATCCGTTGGTTGGTAATGGAGGAAA
          CTAGGACAAAGTGACATCCGTTGGTTGATAGTGGAGGAAA
          CTCGATAAAGGCAAGATCCATTGGCCTGTAACGGAAGAAA
          TCTAGAGGTGGCTTAACTTGTTTGCCGATGATGGAAGGAA
          TTCGCAACGGGCGGACCGTGTCGAGTGATGCAGGTGGACG
          CTCAGAACAGGTTAGCAGCTACGATGCACGATTGAGGGAA
          TCGTTTATAGCCTCTAGTTCTACGCACAAGGTGAAGGAAA

