 8 1000
t1        ATCCATTGTATTACCCTGGAGAGCTAAGGGCCACCCTGAAAGGACGCTAAAACTACTATC
t2        ACTCATTGTATTACCCTGAAGAGCTAAGGCCCACCCTGACGGAGTGCTAAGATTACTCTC
t3        ATTCACCATCCTGTCACAAAGAGCCAAAGATCACACCGGAAGAGTGTTATTATTCCTATC
t4        ATTCATCATCCTGCCACAAAGAGCCAAAGATCACACCGGAAGCGTGCTATTATCCCTATC
t5        ACTCATTGTCGGGCACTGAATTTACTATAGCAGCGTAGGCAAAGCCATGGTTCTTAGAGT
t6        GAGACGTGACCCTTAATGGGCTGGTGCTCGCTATACTCGTAAATCCATTGGGAGAGCGCA
t7        ATTTTCCGCCTCCATACTCCCCATCTCAGATGATGACGCCGACGTAGGGCCGCCCTGACC
t8        ATCATCCGCATCCATGCCCCTCATCTAAGATCATGCTGAGGATGTTGGGCTGTCTTGACT

          GGGTTCGGATGTATTACCTTAGAGTCAAATGCAGCGTAGTTCAGGACCTCCAGGCTCCTT
          GGGTTCAGGTGTATTACCCTACAGTCAAACGCAGCGTAGTTTAGGACTTACAGGCTCCTC
          GAGCTCGGAAATAACGTCACGGGGTTCAATGCAGCGGACTTCCGGGATCCCTGGTCCATT
          GAGTTCGGAAATAACGTCATGAAGTTCAATGCAGCGGACTTCCGGGAGCGCTGATCCATT
          ATGCTTGAGATCGGGCTGATTATGAGAATTCAAATATGGCCATGGTCACTCAAAAGGACA
          TAGTTATTGCCATTCCAAGCTATGCGGACTATGACGCCCCTTTAGATAACCTGTAGAACT
          AAGTAACGGTTTTTGCGTGCAGCAGCGCACCGGGAAATGCCTCCAAAACTCTGGTCCTGT
          AAGTCGTGATTACTGTGTACTGCGCCCCACCAGGACATGCCTCCAAAACTCTAGCCCCGT

          TCCTGAAGGCCACAACAGCGCCGTCTTCCCCCTTATTCGGGCTCACCAGCGGCCCACAAC
          GCCTGAAGGCCACAACAACGGCGTCCTTCCCTTTACTTGGGCTCGCCAGTGGCCCAAAAC
          GCAGGAGAGCTACATTCACACCATCGGCCCCGTCACTTGAGTTCGCCAGCCGCGACAATC
          CCAAGAGAGCTACATTCGCACCATCGACCCAGTCACTTGAGTTCGCCAGCCGCTACAAAT
          CCTCGGTGGCGTCGGGCTTGTTGCCCTGTTGTAGAACGAGAGATGTCTGCCAAAATCTTC
          GTCGCTGTGTGGCACATTCTACGGCGTACGCCCGGCTACGTGAGACCATAGATCAACATT
          CTATCCGAGATACATAGCCGTAGACACTGTTACGTCCGGAACTCGCTGGCTAACGAGGAG
          GGCTCCGAAATGCATAATCGTAGACACTGTTACACCCGGGGCTCGTCGGCCAATGACGAC

          GAATTAGCAGCAAGACGTGCGTACAGTCAACATGGCGTCACGTATTCATGGAGCCTAAAT
          GAATTAGCAGCTGGGCGTGCGTACAATCAACATGGCGCTACGTATTTGTGGAGCCCAAAT
          TCGCTAGTCCTAGGACAAGTGTACGGTTGAGGTCGCGCCACGTGTTTGCAAAAGACAACC
          TTGCTAATCATGGGATAAGTTTACGGTTGAGATCGCGCCACGTGTTTGCAAAACTCAACC
          ATGATAGAGCAGTCGTACGAGTATAAGCTCAGAAAAAATAGTTTTGTTTGGGAGTTAGCA
          CTATTGACCTCCTTAGATAAGTCAGAACAACCATAAATCCGGGTCGTGGAACACCTGCGG
          TACAAGGTTCAAGCACGTCCGAATAAGCCTACAGGACTTTGCTCAACGTGCGTATCAGTG
          TCTCAACATTGTGCGTACCTGAAAAAATACATAGGAACCTGTTTTATTTGGGCTTCAGTG

          ACTTGTCTCCACCCCGCGTGCCTACTGTGAGTCGCGTTCCAGAAACAAAATTATCAAGGT
          TATTGTCTCCACTCCGTGTGCCTACTGTCAGTCGCGTTCCAGAAACAAGATTGTCAAGGT
          AGTCGCTCGTTCTCAGGGACTCCACAGTAGCCGACGCCCCCACGCCAGAATCCCCATAGT
          AGTTGCTCGTTCTCAGGGACCCCACTGCAGCCGACGCCCCCACGCCAGAATCCCCAAAGT
          GCCAGTCTGCCCTGAGTCTAGTTATAGTTTACCCGACACTGGCATGATGCTACCCAAAAA
          GTCTTGTTGCTTCAGGTTTGGCAAGTGCGAGTTTTGTTCTCACGCAGCGACAAATTGAAT
          AATTCGTTCACTCTTATAAACTCAGAGCATGTTGCGTCTAGACGATGGACTGTTTAAAAC
          GATCGTCTCATTTTCTTAAAGTCAGTGCACGTTGCGTCTTGACGACAGCCTGCTCTGACC

          GGCGTGAGGTATGGTGCTAAACGGGCGCGTCGAAGATAGCGGCACCAGCACCCAGGAGGG
          GGCGTGAGGTATGGTGCAAAGCGGGCGCGCTCAAGGTAGGGGCACCTGCACCTAAGAGGG
          AACTAAAGGTCTGGTGCGAAGAGGCTTCGTTTTAGTTATAGGCTCCAGCGTCCCTGACGG
          AACTAAAGGCCCGGTGCCAAGAGGCTTCGTTTAAGTTATAGGCTCCAGCGTCCCTGTCGG
          TGGAGTGCATGCTATTCTAACGCTCGACAGTGGTGAGACAAGTATTCCCGCTAGTACGAA
          ATGTTGGCACACGCAACCGAACGGTTGTGAAGATGCAGTACTTATATAAGCTCAGATCGT
          TGCACGAGGGTCCATTGGGGAAAGGTGAGATCGGGTTGATAGTAAATCAATTCGGGGCCG
          TGGGTGAGAATCCGTTCAATAAAGGCGGGATAAGGTTGATAGTACACGCATTCGGAGCTG

          ACACCTCCACTAAGAAGAAACTTGGGCTGGGCCTCACTTCTAGAACCACGCGATTTACAT
          ACACAGCCACAGAGAAGAAACTTGGGTGGGGCCTCACTTCCCGAGCCACGCAAATTGCAT
          AAACCTTTCCCGTGAACCCCTTACAGATGGGCCCGATTCCTCCAACTACACGGCTTGTAT
          AATCATTTCCCGCGAACCCATTACGGATGGGCCCGATTCCTCCAACTACACGGCTCGTAT
          CCTCTTCAGCACTAAATACGCCCGGGTGAGTTTTCAGCGTTCCAATCGACTGCGTCTTTT
          AATCCCCAACTATTCGCGGAGATGGGCGGGTATTCAATGTTCGAGGGATATGGAGGATCG
          TCCACCTGCCTGGGTCTGAACCCGGGTTGGCTTCTGCGGCCCTCTGTATGCCGACCCAAG
          TTCGTATACATATGTCCAAACCATGGTTGGTTTCTAACGGTCTACCTATACTGGCCTATG

          TTCGTTCTATACTTACTGGCAATATTGGCGGAGTACACCCGACAACCCCGGGCACCTCAG
          TTCGGTCCCTACCCACTGGCTATATTGGTGGAGTGCACCCGATAACTCCGGGAACCTCAG
          TTAGTCTTCCGTTCACCATGGCCCTGGACGGTGTTAACCTATCGATTTCTAATACCCTCC
          TTAGTCTTCTGTTCACTATGGCCTTTCACGGTGTTAACCTATCGATTTCCAATACCCTCC
          AGTTTTCTACATCCAGTGGCGCTTTCAACGCTGTTGGCCACCCCGACTTAGAGGGAACCG
          AACCCCTGTTGCCCCTGACCACCGCCAATGCGGTCGGTCCATCAACCGCTCAATAGCTTA
          TACGTTTCTGTCTTGACTTTACAACTTGCGGAGTAAAGTTACGGAGCACTGGCGCACCCT
          TTCATGTCCGTCCCTACCTTGCAGTTCGTGGAGCCAAATTATAAAACGTTGGCGCGCTCT

          CGTAGGCTGTCAAATAAATACACCAGACCAATATCAGTCTGCATCCTGGGGCCCGGCAGA
          CGTAGGATGTCAAATAAATATACCAGACCAAAATCGGTCCGCATCCCGGGACCCGGCAGA
          TAGAGGCGTATAAGATAGTTTGTCTGGTTAAAATCCGCCCACAATCTAGAACATGTCAGA
          TAAAAGCGTATAAGATAGTTTGTCTGGTTAAAGCCCTCCCACAATCTAGAAAGTGTCAGA
          ACTTATCTCTCTGCTTTATGGCCGTTCCCGAAGCCGGCAAACGACTATCGGCGATACCTG
          TGTTAGTTTACTGATTACTATGCGTGGACACAGTCAGAGAGGTTCTAGGGTGTTGGCAAG
          TGACAACTTCTTCGTGCATGTCGGCTCTTTAGGACCGTCCAAAGTCCTAACTCGCTCTGA
          TGACAGTTTTTTCCTTCAAGTCTGCACCCGAGGGCCGTTCGGACCCCCAATACGCTCCGA

          TATTTGATGTACGCAGCGGGTTCACTTAGCTAACTAGTAGGGAACAAGTCAGAAGGGCAC
          TTTCTAATGTATGCATCGGGTTCACTTAGCTAACTAGTAGGGAACAGGCCAAAACGGCAC
          CACCAGATGCTCGGATCATGTTCATCTAGGCGGATAGAAGAGAACCAGCCAGTACGGAAT
          CACTAGACGCTCGGATCATGTTCCTTCAGGCGGACAGAAGAGCACCTGCCAGTACGGAAT
          CTCCACATACACTCGGGAAAATGTCATCAAGATCTGAGAGGACGGGGTCGCGCAGCCCGA
          TGCTGACGTCTCAAGATGGAACGTTAGAACTGAACGTGGAAAGGCACAATGTTGCATTAC
          AGTCGACTAATTGGGTTTGGATAGTCCAGCTGTAACGTCAAGGAAGTGCAACCGCGAACT
          ATAAGACTGTTAGGCTCTGGACAGTCCATCTCTATCACTAGGGGCGTATGTCCGTAGGGT

          TAAGTGGGCTTTAAAGACAAAGTACACCGGTAGCCTTCGTCATAGGGCTCTCATCTAGTA
          TAAGTGGGCCTTAAGGACAAAGTAAACCGGTAGTTTTCGTCATAGGGCTTTCATCCAGTA
          CGAGTGGGTCCTAAGAACGACATGTTATGGCAGTTTCGACTGGAGGGCTCATTTCTAGCA
          CGAGTGGGTCTTAAGAACAATATGTTATGGCAGTCTCGACTAGAGGGCTCACTTTTAGCA
          GATGTACGTTTCAGACACGATAAAGCCACCCGCCTTCTTTTTTAAGGCTCGGCATGAGTA
          GGTGTCGACTTTGACTCCCGATTGGGTCGTTGCGTACGTTCCCAAAGTTTTTCTCCGAAG
          CTGGTCTAGTCCCTACCTGCTGAGTTAGAACCCCATGAGCGTGCCCGCTCCCCGCCAACA
          TCGGTTCGGTGCTAATCTGCAACGTTCGCGCTCTCTGGGCTCACTAGCTTTTCTCCGTCA

          ACGGCTAGTGGATGAGAGCGTCCATTGATGGTGTAGTCTGACTAAAGCACTGTAGGGTGT
          ACGGTTAGTGGACGAGGGCATCCATCAACGGTGTAACCTGACTAAGGCACTGTAGGTTGT
          AAGGCTGGCCGCCATGAGTGCACGTCAGAGGTTAATTATGACTATGTCACCGTAGCTCAA
          ATGGCTGGCCGCCATGAGTGCACGTCAGAGATTAAATATGACTATGTCACCGTAGTTCAA
          CGAGTCGATAGTGAGTTACGTGTCCGGGCCGCCCATTACTGCAAAACCCGGAAAGGAACT
          TAGGTGCCTTAGGGTTAACAAGTGGCTACACTTTCCTCTCCCCAGGGTGAGGCAATATCC
          ATATCCAGCTGCCGTGCTTACAGATTAGTTGTGTCATCCAACCGGAAAAAGGAAATTAAC
          GTGACTAGTTACCCCTCTTCCAGTTCGGTTATGTCGCCCATTTGAGATGAGCCAATCAAC

          TCAGTAGGAACCGGAACAATGCTTACTGGATGAGGGATAAAGATCTCCGCACGATCCCGT
          TCAGTACGACTCGGAACAATGCTTACTGGTTGAGGGTTTAAGTTCTCTGCACGATCCCAT
          CCCGTGGAACTCGGCACAGCGCTTCCCGTACGCAATTCTAGGCTCTCCGCGCATATACTT
          CCCGCAGGACTCCGCACTGCGCCTCCCGTACGCAGTTCTAGGTCCTCCGCGCATACACTT
          TCCGACACACATATTCTAGTTCTTCTGGGACACTCTTTTGACTAATTCGATTTGCTTTTG
          ATTGCTAAACTTTTTCGAGCCATCCAAATCTTGCCTGAGTGCCGATTTTCGCTGCCCTAT
          TTAGTCACGCCGGACGCGGTAATTCCTGATCTATCTTACCTTGGGGGAACCTGGCCCTTG
          TCAGTCAGTTCCGACGCGACGATCCTTAATATATTCTAGCTTGGCGGTACCTGGTTCCTG

          TCCCATGTTGGCGTAGTCAGGGGGGACCTCACCACTATTATGAGCTTTGGCGGCCTTCGG
          TCCCATGTTAGCGTAATCACGGGGGACCTCACCACTATTGTAAGCCTCGGCATCCTTCGG
          ATCCCTCTTAGGTTGGTTAGGGGGGGCTTTACTGTCCCATCTATCCTTGCAGCCCGTAGG
          ATCCCTCTTAGGTTGATTAGGGGGGGCTCTACTGTCCCAGTTATCCTAGCAGCCCGTAGG
          ACGTTAGTGATCGGTGTTACCACGAAGCGTTCAAAGTTTGTAACCTGGATTGTTTTTGAG
          GAAACTCTAAGGAGTGCAGGTGTAATTGATCTTTCTTCGGATGTTCGGATAGCCCTAACG
          CTCCTACCGTGCGCTACAGGATTGCACATTTAAGTAACCTCATTTTAGCTCGTCTATGCG
          CTCCTACAATGTTCTGACAATTAGCACATTTAAGCAACCCCACCTTATATCGTTTACTAG

          TACGGATAACCGTTTCGATTAACCACGTTACTGAAGCTTGAAACGCTCATGTTGGGAAGA
          TACGGATAACCGTTTCGATTGACCACGCTGTCGGAGTTTGAAACGCTCATGTTGGGAATA
          TATGGCGATTTAAACCCATCATTTACGCTGTCACAAGCTGACACGCAGACACTAGGGAGA
          TATGGCGAACTAAACCCGTCATTTACGCTGTCACAAGCTGACACGCAGACACTAGGGAGA
          TTCTGCTCATAGCTCTTGAAATACCTTATCAAGTATAGCGGCTAATACGCAAAAGAACAA
          CGTCATCTATGGGTCCCCTCGCTGGACCATATAATCGGTAGGGACCATGTTTATCCAACT
          TGCCGCAAGCGGGTCACAATATTGGGTCGCTTAAGTAGGAAGTTATCTCAAATTGAGGAT
          CGCGGCGAGTAGGCGACACCCTCAGGTTCTTTGAATAGAGGTCCGTTTTGAGCAGAGAAA

          GCCTCTCTGACAAGCGTGATAGCACACCCCTTAGTGTAATTCTTAATTGTTTGGAGTAGT
          GCCTCTCTGATAAGCGTGATAGCAAACCCCTTACTGTAACTCCTTAGTGTCTGGAGTGAT
          ACTTACGCGACAGGGGTATTAAAAAACCTTTTAATGGCCATCGTTAATGATCGGGGTGAG
          ACATACCCGACAGGTGTATTAACAAACCTTTTAGTAGCCATCGTTAATGATCGGGGTGAG
          CAGTCCCGTCCTAACATACCAGGTCCATCCCGTATAGTGGTCAGGTACCTGCATGGAGAA
          CGACAGCTTTACGTCGTGTTCCTTGGTAGTGATGCCTCGGCGGTGAGCTGTTGAGCACGC
          GCACTACTTCAGTATTGAGGTTCGGGCTGCGACCAAAGCAATGGGGCCTGGGACAAGAGT
          GCGCAATTTAATAGTAAGGGTTTGGGGTGCGACTCAAGGGATGGCGCCTGGCACGAAGGT

          TAAGATGCCGCCACTGGTAGAGTCATTTCTGCCGAGCCCG
          TAAGATGCCGCCGCCGGTAGAGACATGTCTGGCTAACCCG
          TAAAGTACTGTCACAGGTGGAGCGTCATCCTATTCTTCAA
          TAAAATACTGTCACGGGTGTAGCGTGATCCCATTACTCAT
          TACGGCTCAGGAAACGCGGGCCTTCCTATGGGCAGTCCCG
          CGTACTCGGGATACGCAAAGCCCCACTCCAAACCGCCCAG
          CCAGGTTTGGAAACAGGCGAATGGTCCCTCGATTCCTGGC
          CTGGATACGGAGAAAGACGTATGGCACCTCGACTACCGAC

