 8 1000
t1        AGGGGGCCGCTTGATTGGAACGAATACCGAACAGTTCAGCGACTAATACATGTGAAACTT
t2        CAGGGGCCGTCAGGCCGGCAAGAGTGCCGAAGAGTATAATGAGTAGTACATTTGGGAGCC
t3        GTGGCGTATCCCCGCGCGATCGATTGCCGAAAATCATGATAACCTCTCCTCATAAAAGTT
t4        GACACGTGATCTCGTGGCATAGCGAGGTAACTAGCTCATCTACCAAGTCGTAGGGAAGAC
t5        AAGGAATCGTCACAGGGGCAGGAGTATTTTTAAGCCTATCGACTGCCCCGTGAGGAGTCT
t6        GGAGGATGGTGTTACGTGTCTCGGTCAGTTATAGCCCAGGTACTATTATGCGCCTCGTTA
t7        TCAGGGCAGTTTCGCCGGCTCAAAAGCAGAGGAGTCAAGTGCTCATCATGTGCGGTACGA
t8        CAAGTCTAATCGAAGATCCATAGTCGAATCGGAGTGCGGCGACTTTTTGGAGTGAAGAAT

          GTAAAGCTCTAAGTCGTCTAGAATTGAAAGAGGACTAGGTCTCGCTGATATGTCAAGCCA
          CTAAAGCCTCTTGTCCTCTAGGGTTGAGAAAAGATTATTTTCCGCTCGTACCTTGAGCCG
          ACAAAGCTCACCAGAAATAGCGGTAGTGAGGGGAAGGCCCCGGCTTTACGTGACGCGGCG
          CCAAGATTTTGTGTTGACGGGAGACGTTACTGCGTTCACATGGGGTTACGTACTGTGGTA
          TTCAGGCTCACTGCTTATATAGGCCAGCAGAGCTGTGCTTCGAGAACACACGTATAGACG
          TCTAGACCCTTCTCTGGTAGCACCCGGTTCTGGGATGTCTTAACGTCGGGCAGTGACATC
          TTCGCACCTCTAATTGGCTCGCTGTACGGAGGCCATGTTCAGAGGCCATCCGTTGTAGAG
          ACCGGACCTTCCAGTTAGTGGAGTCGAGTGTGCGGTTCCCTATGAGTGTCAGACGCAGCC

          GAGAGGAATGAATGACGGAATCATGCGATCATCCAGGAAATGGTAGGATTTATAAAGACG
          ACGAGGAACAAGTGGAGGATTCAAATAGTCATCCAGGAAATGATAAGGTTTATAAACACG
          GCAACCCCATAACTCAAGCGTTATGGGATCACTCCACAATTTGAAAGGCTTGTAATAATA
          GCAAACGCAGTTTGTAGCCCATACGCAACTACCCTTCTAAAGGTATACAGAATAGACGTG
          GGGCTCTCTCCTGGCATTCAGTGTAGAATTAAAATCCACAAAGTATGGTCGACAAACATG
          GTAAGTATCGGATGTAATGGTCACAAAACATTACTGTGTGCAATGCGTTAAGCAAGGGTA
          GCAGCCTCTCAGTGTGATACTTGCGTAGGCATATCTGGAGTTGTATTGTTGATTGGAATT
          ATACGTCCTTTGTGTGACCGACGTGTTGTTTTCCCTAGATGTATGTTACTAACAAGTGGG

          ACGCTAAACGTTGGGGCGTCATTTTTTAGTATCACTGATCCCTGGTGCCCTTAGAATAAT
          ACGTTAAATGTTGGGGGGCTAGTCTCTAATATCTGTGATCCTTGGTGCCCCTAGAATAAT
          GTCCTAAAGGCCGGGTTGTGAGTATCACAGACCGCTAACACTTCATTCCTTCACACTAGG
          ATTTTAAGTGTTATGGTATCATTCAAACGTTTTCCCAAGGTATGGAACTCACAGATATTG
          GGCTCTACCCGGGTGGCACCAACTCTATCGCATTTCGCAATTCTGCTCCAGAAATTAGGC
          GTTCTAAATATTATAGCAACAGGCTAACAGCGCCTCTGCAACCAACGTCGTAAACCTGCT
          TAGCTAAAAATCAATGTACAGGCCCTACTGAAGCCAGGCACTGACATTTCATAATTGGTA
          AAGCCACGTTTCAGGGTCCAATACTTACTAAACTCAGATTATTTGTATCAAAGACCGAAG

          CCCTGATGAATCAAACCTCACGTGTATTATGCTTCGTCATCCCTCCGCTCTGACCGTACG
          CCTCGTTGAATCAAGCCTCACGCGCACTACGCTCTGTCATTCTTTCGCTCCGATCGAACT
          TATCGCTCTACCCGATGTCAGACTCAGCAACTGTAGACGCTATATCGTCTCAACAGTGAT
          CTTGGCCGATATTACGGCTATCTGGGTGTCACCTGGACATTTTTTAGATTTCATTGCCCT
          TTGCGTCGAAACTAATGTAAAACCCGAGGCAGCGGTTAGCCCTCCCCACTCGTCTGCGGG
          TACTAACGATCTTTTCATATGACCCGTCATCCCTGGAGGCCATATTACTTCGATTCTGCC
          TGCCCACAGCTCAAATATAGGGATCCCTAAATCTAGAAAACCCACCTCCTCGAATACGCC
          GGGTACAGAAGTCCGTGTAAGGATCCTATCTCCTCTGAAGTCCCCTAACTTTTCCATGAT

          AACCGACCCGCAAACGAGGCACCGTGCAGCTGGACACTCTGGTATGCCGTTATCGGACAC
          CAGCGGCCCCTAGACAAAGCACCGTGCAGCTGGGCATTCCGGTACCCCGTTATCGGACAC
          CATCGGCCTGTGGCTTGGACACAGTCCAACAGGACGCTTCGCTACCTCACAATTGCGTAA
          CATTGTCCTGCGACTAATGTGACAATATATGGGGAACTTAGACGTTCCTCTATAAGGCTG
          TTTTAGCTAACCACCGAAGTCTTCCTCGATTGAAGACACCATTATACAAGCGGTGCGTAC
          CCCAGGTCCATCGTTGGGGTCATTCCCGGCTGGGGACTCAAGTGTTTCCTTGCAGAGCAA
          TTTGAATGGATTGAGGGAGCTCATTTAAGTTATAAACTTATGAATTCTTCCGCCGTCTAG
          TCCTAGCGAGCATAATGAAAACTCCTGGTTTTCTTACTTGAGCCTGTGGAATTCTATTTT

          TGATATGATAGGGGTGTGACTTCCTGCACAAAGTAATCCCTGTATTTGCTGCTAAAACTA
          TGACATGATTGGGGTGCGCCGCCCTGCACAAAGTTTCCTCTAGACTTGTAGTTGAAATCA
          CGACAAAGTATCGGTACACTTACTAATCCCGGATCAACCTTGAGATCAAGGTTAGACTCG
          TGACATCTGAACATGGTGCGCTTCCGTCGAAGACCATCCCCGACGTCGACATCCAGACCA
          TCAGACGGAACGTGAGTGCTCCTTCATCATAAGTCAGGCCTGACAGTGATTCCAGGCTAA
          GGGAACATTAAACATTTACCCCTAGGCAGTGAGGACGGGCTACCTTTCCTACTTTGCGTA
          CTGGGGGGTAAAGTACCGCTGTACTGTTGCGGGTGCGGTTCGGAGTCGTTTTTATGTCTT
          CCTTGTGGGATGATACTTGCCCTTCATTGTGTGCGCCGTTTGGTGTCGGCGCAGGATTCC

          GGGAAGTCGGGCTAAATTACGGGGACTTTGAGAGGATTACAGCTGCTGTTAATTCCAAAG
          GGGAACCCGGATTAAACCACGAGGATCTTGAGTGGATCAATGCTTTAGTCTCTCCTAGCG
          GGGTATTCCGTTTTAAATACAAGTAGCGCGAGTAAACCTTGGTCGCTGTCTGTTTCGGGG
          GTCATGTTTATACCGATTGCGAGAACTCCGGTATTGCAACGATAGGCACTCGCTCTGGTA
          TGTTACTTGGTTTATTAAACAGGCGTTACGAGAATTTGGTTGTCGTATTCCGGATCACCG
          GGCAGCTCTCGCAGACCTATCAGGGTCTCATAAAGTCTATCACAGTTAACAGATTCTCCA
          TCTGAGCCTGTTCGTGCTACAATCACCCGCACTATTGAACAGGAGCTTAACCGTTACTTA
          GGACTATGAACCTAGTCTGTGGAGCAGATAAGAATACTACTGCCATTCTAGAGTTCATTA

          CCTGTTACTGGTGAGCCTTACTCATGGATTAGTTCCTCAATCAGTGACCAGTGCTATTAT
          GCTCTGACTGGTGGGCTTCAGTCACGCGTGAACCTCTGGGTTTGTAGTTAGCGCTATCGT
          GTTACTTTGGCTGAGCTGTGTACACGAACGAGCCTCGGAATTTTCAATGAACCTCATCAC
          GCTCTCTGCCGCGGGCCTCGGCTATAAATATAGTCTGGAACTATGAATGACTACCACTAT
          GCTCCCCGAGGGGTGCCTAGATCGTGCATGCACCCACTATACGTCTTTAGTCCATCTACC
          GCTAAAATCAGTGTATTGTTCCCAACAACCAATCGCCTCACGCTAGTTGACGATTCCTCC
          GTTGACACCGGCGCGGTTTGTTGATCAAAGTACTATCAGCGCCTTACCAATCGTAACTTT
          TTGTCTTTCGCTGACTCATATCCATGAGTGCAAGTCCACACTTGTGATGAGCTAAACGCG

          CTCACCGTATCCCCGAGGGGGTATTAGGATTCATGCAAGTCATCGAGCATTTAGATCATC
          CTAACCGTATACCCGAGGGAATACTAGGATTTCCGCAAGATATTCTCCATTTGGATCACT
          GCGAACGTCTATCCTAGGGGGTCATTAAGCTCACGTAAGACATTTTTAAATTGAGTCGTA
          TAACGCTTCTTACTGATGGAACTTCAGACTCTAGTCTAGACAGTTGCAACTCGGACTATG
          TGGAGAGCTCATCATATGTGGCCCCCGAACTTATGGCAAATCCCCATTCGTCATAGATTG
          ATCGACATCCATCGGTAAGGGTTCTTTCGTTCTGATCTGTGTTATCCCAACTGTGGCTTA
          ACATACACAAGCACAATGTCGAGCTTTTACGCTCGCCATAATTCTTAAGTCTACAGCACC
          TCAAACACACATCTGACCGGGCCTCAGTCCCACCCGGGGGGTAAATCAACCATCGTTCTA

          GCGATGCACGTCTAGGCATGGCGGTTGGACGGCCCTGTAAAATCGAGTTTACACAAGGAG
          ACTACGTAGACCGAGGCATGGCGATTGGACGGCGCTGTTTAACCAAGTTTATGCATAGGG
          ACTGCGTACGCCTCGGCCCTGCATCGAGACGGTGTCGTCTGATTGAGTCCAATGATGGGA
          GCGTCGCATGCTGCCGTATTGAGGTTAGTTGTCGTTGTGTCAACGCGCTCAGTTTAAGGA
          ATGAAGCGTGTCTAGGTTACGTGTTGACTGCGTGCTACGGGAATAAGCCTGCGAGTCGAT
          GCAACGCATGGTACGGATTTGCGGCCGTTTTGCATTCTACATTGTTGTCCTGGCGGATAC
          GTAACACGGGTATACGATTCTCAAGAAGAAGGTATTGCATAGCAATGCTTTCGCAAAGAA
          ATGGTATAATCGGTAACCCTTTAGTGGGTCGGCACGAAGACATTTAAATATCGTAAAAGG

          GGAGAACTTACCAATTTGACCTCCGGCTTCTTTATGGTATCGTACGGTCTGAAGGGAGCT
          GAAGAACGCATTCACTTCATGCCCGGTGCATTTCTGCAGCCGTGTGTTCCTCAGGGAGAT
          GAAAGGCAAGGTATCCAGGCGTCCGGCCCTTGCCTAGAGTTGTATAGCTTCAAAAAGACA
          TGGGGACCAAGGAGTACCGTGGGCTGTTCTTTGCTGGAACTCTCCGGCACCTGGATGGGG
          GCTAGAGAGTTCAATCCTTTACTACGTCCATCGTCAACATCCGGTGAAATCTGGTTGGGT
          AAGGGGCTATCCAATCGGGCGGTTTGCCCGTCTTTGTAAAAAGGTTGCTATGGAGTTGCC
          AGAGGCAGGGAGAAAGCGCCAGCCGGTCTACGATCGAATCTACAGCGCTGCCGGAAAGAT
          TGAGATCAGTCCAACCTTCCTTGACATCTATCCTGCGGAGTGCACCGCTATTCAAGAGCT

          TATTACATGACACTACACAAGTACGGTGTGAAGTACGAGCCGATATCATCGTCTGGGTCT
          TGTTTGAAGACACGACATAAGCACGGGGAGACGTACGAGCCGATATCACCGTCTGGGTCT
          ACACTAACACCCGCACTCCGAAGCAATACGGCGCAAGAGGCGACACCGCTGTTTAGACTT
          GACTGGATATGGTGACTATGTCGCGGGATGGGGATGGGAGCTACACCACAATTAGCGTAT
          GACACAATATGACCTCTTTTACCCGGGGCGGGGTAGGGGACAGTACTGTTATTTAAGACG
          TGTTAGAAGTAACCGCCTTGCTTAGAAGTCGAAGAAAGGATTATAGCACAACTTCACCTA
          TCGTGATTGTCGACGTTCTCCTTAGGTCCTGAGCAAGTGATAGTACGACACCTGTTGTTT
          TCTATCACCAAGCTCACAAGCTTTGTTCTAAGATCAAGAATTATTTGCTACTTTAAACGA

          AGAGGTTGCAACCCGGTCGTATCTCCCACATCTAATGTAATAGGTCGCATAGCTAATCCA
          TGAGGTTACCGACCGGTTGTGTCGTCTACACTTAATGTAGTAGTGCATATAGCTAGTCCC
          CGGGGCTTTGTTTAGGTCGGGTCCACCGTGTCCTGTGTACTAATTCATACAGAAGGCTCT
          TGAGGCTACCGTCAAGGCATATATAAAGTGCTTTGCGCGCCTGCTCCTTCGTCGATATTG
          AGGAGCTAGGACTGGACCGCATTTTGATAGTTACACATCATTGTCTCTCTAACTAGTTCT
          GGAAGCTAAGTTTGTATAGTATACCGACGGCGCGCTTCCCCTTGCTTTGGCGCTAATCTG
          GAGCGTCTATTACGGGAAATGTTTGACATACAGATCAGATTAGTCTATTCAACCAGCCTA
          GGGAATGATTCTTGTGCAGAGCTGCTAGTAGCGCTCTTTTCACCTCCTATGGCCTGACGG

          TTCAGGGTAATACAGCCATCGGCACTATTAGTTTTACAGGTCAGCTTCGCCTAGAGGAAC
          CTCATGGTGATTCAGCCACCGGCATGTTTAGCCCATTAGGTCGGTATCGCCTGGAAGGAC
          TCCAGAGCAGTTCGGTACCGGGACCGCTCAACCCGCCGGGTTCGCATCGCCTGAACACAC
          TTCAGACAGGTGCCACTTTGGGCGGAATAAAAAGATGGGGGTTGGGGTATTGGAGTGAAA
          ATAGGACAAGTATTACTACGAGTTGGTCAAGCTCGTCTGGCGCACTTTGTCGTGGTCAAA
          ACTAATGGACCGAGATCATTAGGAGCTGCAATTAAGAGGGTACATTCTTTCTGAATAAGA
          CTTGAACCGAGATTACTAATAGAGTGTTAGTGAGGAAATATTTGCTGTACGTTCCTGATT
          GTTGGCCCTTTGTTACAGTAAGTGCCATATCTTTGAATAGGTCACGGACACGGGCGATGT

          AAAGAAGTTAATAATTCTGTGGGTACACTCGAAGGAGGTTCAAATATCACCGAGTCATGA
          AATGAAATTAATACCTCTGTAGGTTCAGCCGGTGGGGGTTTAAACATTATTTCGTCAGGA
          AATAATGGTGGACTACCTAGCGAACCCGTTGAAAGAAGATTCAACGTCACCAGGCCACAA
          GGAAACAGCGATCGGTTTGGCGGTTCCCTAATAAATATGAGACAGATGACCGGCTGAACG
          AGAGGCGATAGTATGTTCGACGGTGACCCTTGGAAAATAGTCCGATTGGGCAGGTCGGGC
          GGTGTACGTGTACTACAGGGTGGTCGCGATGAAGGTAGACATTTAGACTTAAGGGCTATG
          AGAACTCATTGAGCACACTCGCGGTGCTTGGTCAAAGGATATCCAAATGTCGTAGTAGGG
          GGAGTCAACCGGAGGCCCTATACAAGCTTTTGAGCAGGCTCTTGAACCATCGTTCTGGAA

          GACTGAGCCGCTACCATCATGGCCAGTCGTTTTTTGTGGC
          AGCCGAGTTACGAGTTTCCTCTCTAAGCGCCCCTTGTGCC
          GATCGCGCGGTGATTGCACAGGCAAATCGAATAATGTAGC
          CATCTGGTGATTTCTCTACTGCTTAATCCCCTCTCGCAGC
          GTCAGCGCGATGGTTTACATCCTCACTCTCAGCTTGTAGA
          GTCGACACCATCGAGATAAACACAGTTCATTCCTCGTAGT
          GATGGGGTTGCAGACCATCAGGGGTATGGTAGGGCCCGAT
          GATGCTATAGTTGACCATGGGGTCAAATAAACCCACTCGA

