 8 1000
t1        TTAGGAAACAATATCCCACTTTCCACAAGCTTCCCAACCTGAAGTGCTCGCGTTACCTCT
t2        CTAGGGGAAAATTTCCCCATTTCTTTAAGCATCCCAAGCAGGGTCACCCACGTCGCCTCT
t3        CAAGGGTAATGACCTCTTTTTTGGCAAATACACCTACGATGAGCGGATCCTCTCGCTCAT
t4        CAACGGTAACGACACTCCCTATGGGAGAAGCACCTCTAAAGCGCCTACTCACTGGTCTAT
t5        TAATAGAAGGCACTTGGACTTTCCTGACAACTTATCATCATGCGCGACCACAACAAATGC
t6        TAACAGGCTATAGACTGCCCTAGGTCAGGTAAACTAAGTTCGTGTGCCGACCTTAAATGC
t7        CTACATTTACGGTTCCCACCTCGTATATAACGTCTGTGGTCGTGATGCCGTGTCGGAGGC
t8        TGTTGGCTACGGTTCACAACTTGTGTCGACCATTTGGAGTCGAAGTGTCGCCTTTGACAT

          TCCGTAGCCACAGCGTAACTTCTTCCCTGTTGGAATATAAAATCAGGATTTATCCGAGAC
          TCCATAATTAAAGCGTGCTCTCTTAACCGATGGAGCGAAGAGGCAAGCTCTATACGAGAC
          AAAGCCATTAGATCATACTCATTTCCAGAGGTGAGCATGACACCACCCTCGCTTGAGGAC
          CCCGGTACTTTTCTTTATTGATTCACAAAGGTGAGCATCACACCAATTCCAACTGAGGAC
          AACTTTAACAAGACACTTCCGTTGTTATGCTCTGACACTACGTCGAATTAGATAAGGTAT
          ATTGTTACGTTAGTCTGTAGCCTTTTTTACTGGGGCATCCAGATACACTAAACGGAGTTG
          CTCACTAAGAAAGCCATTGGACTCTCCGGTAAAAGCAGCACAGCGGGGCTATCAGTGGAC
          GCCCTCAAGTGTGCCCGTGGCACTCCTTGTAAGAGCCTTTAGCCGGGGCTAACATCGGCT

          TGCTACTTTGATGCATGCTGACTAGGCATTCTAAAGTAGCTTAGGCAGCGCGATTCGACA
          TAGCCTCATGATGCACACTGGCTCGGCAATCTATGAAAGCTAAGGCACCGGAACGCGACC
          CGGTGCTAGAAAGGGCGTGGAGTCCGTGAACAAAATATACGGGAATGGAAAGTCATGAAT
          GAAAGCTAGATAGCGCCCGGAGCTGGTAACCAAAACGTGATAGAAGAACCCGCGCCAAAC
          TTATTAATGGTTAGCAGCCTAAAATGTAATAAAAGGTGGCGTGGGAGGGAGGCTGAGTAA
          CACTACTTGGAGTCCGCTTGCGGAGAGGGAGCGCGGAGGGAAAAGTGAGACGCCGGGCAT
          TGTCTCATCAAACGATGTCGAGAGTGATTTCAATGGAGCCGTCCGGTGAAGGTTGAGGGT
          CACGACGATCGAAGCTACAGAGATAATCCCTACTGGTAGTATCTGACGAAAGCTGGAAGC

          CCTTATCTAAGTATCCGCTGTCAAGTACTCCTTGTGAAGTACTCAGCCCCCAGGGAACGA
          GCTGTACTGGATAAACGCCGCCAAGTTATAACAGCGAAGTGTCCAATCCCCTGAGAGTGC
          TTGCATTAAAAAATCCGCTCTCAAGTAGGTCTCGCAAAATACCTTTATTGATAAGTGGGC
          CTGCATCCGACAGCGTGTTCCTGGGGAAGACGTAAGACGAATTAAGACAGTGAAACGAGT
          GCTAATCGAGAAACTTACTCTTACGTACGCGTTGCACACAATTTGGAGACTAGGCAGAAA
          CTCCGAGGAGCAACAAGCCTTTGCGTCTACGCCGCTATTATGTTAGGTGCCCGGCGTGAA
          TTTGTCCTAGATACACACTTCTTGCCAGGTGTCGTGAAATTCCTGGTACCCCCGCCTGGG
          CCTTATCTTGATACACGCTTCTTGTCAGGTGCTACTAAATTGATTGCATGCCGGCGCGGA

          CCGCGGCTCCCTGTAGAAGGGACGAACGGACTCTCTTTGAAACCCTCTATCGAGGATGCG
          CTACGACCTTCTCCAGGGAGCACAGACGAACCCTCCTTGACATCCCCCACCGAGGATATG
          ATAGGATCGACAATTGTAAACTTAAGACGGCTCCTATGGTTCTGCTCAACGGGCGCTAAC
          ATGCAATAGACAGTAGTGGACGCGACGTTGGTTTTACCGTTGCACCTAATGGGCGCTACT
          TCAAGATGCGCCTTGACATACATTCGCCGACTCCTACATCAGTACGTTTTCAGAGAGTTA
          ATCTACGACTATGGAATATGCACACATTGTCTCTTTCCAAAGGTCGGACATGTTGGATTA
          CCTCTTAAGAATGGGAGAGATTTTTGCCGATCCATTAAGTTCTACACTCTCCACAATATA
          TCCCACGAGAGTGAGATACGCCCGCACTGGATCATCATGTCCAACATCACTCATTATCTA

          GGCGGAGTCCTGTCCTCGGAGTGACAGAGTTGCAGTAAAAGCACTGGTTCGATTATGGCA
          GAAGGTGTCCTGGCCTCGGGGTGACTGAGTCGCAGTAAAAGCACTGGTTCGATCGTGTCG
          GATACCGACTTCCCGCAATGAATAAGACGACGATTCGGCGATAAGGTCCAGAAGCCGTGA
          GGTACCGTCTACGCCGAACGGTGGGACTTTTGAGTTGAGGGCGAAATCTCAAACCCGTGG
          TATAACGACTCCATAATAACGGGAATGCGTTTGGGGGACATGACTTATTTGACACAACGG
          TACATTGAGTTTGTTGGAGGCAGTATCAGGTGGGTAAACAAAAACAACACGAATTAGTAA
          GAGAGTTTTTGTGCTCGCCCGGGTGTGCGCCGGGGGCATTAGGTCAACCGGCCCGACCCG
          AGGAACGAATCTCTTGTTATTGGAATGCATCGGGGTAACCGCGGAAAACGGGCCTAGCTG

          CAGATTCCTTACGTGTCGACGCACCCTTGCTCTCGTCGGGCAGGAATAACTGGGGCAGCT
          CCGATCCATTGCGTGCCGATAAATTCTTGTTCATGTATGGGAGGTATGAATTCTGTAGTT
          TCCGACTATAGGGCGTCCATGAGCTCTTGGTTTTTCTTAGCACGAACAATTTGGCCACGC
          TCGGGCCATTTGGAGTCAACGTAAGTGCACCTATACGTAACATAAGAAATTGAATTATTC
          TGGGGGGCTAAACGTCATATTAGCACCTATGCTAACCAGTCCGATCTGGGTAAATTGCTC
          TCAATCGTTTACACGCATAGGACCGATTATGCAAGTAGGGACCGATTAGGAGGGGCGCCC
          GACGACACTTATGCTGTAACTAACGACCCCCAATAGAAGAACGGCAGATATAGCACCCCC
          CATCATTTTCACATGAGCGTTAGTAGTCATTGACAAGCGGGTGGGTGAGCCTCGACGTCC

          TTGGGAGATACTTAGACCGCCTCGGGCCTATGAGGGCCGTCATGCCGCATGTCTGGCCCC
          TTGGGAGGCAATCTCGCCGTCTCAGACTTCCGAATGCCGTCATGCTGTATATCCGGACGC
          CCGGTTGACGCTAGGGTGGCCCGGCTACCCTCGGTCTTCGGGAATTAGGCTCATCAGAGA
          CTGATTAAACCCAGGGCCGCCCAGAGTCCCATCGTGAATGGAACTTGGATGTACAAACGA
          GCCAAAGGCGCCTAGGGCGCACAGTGTAAGAAGGAAAAGCAGGAAGACGCACATGACTGT
          GTGGGGACTGCAACAGTCGTCTAGAGACAACAGGTGCGTACCGCCATAACCTACTGTTGA
          CAGGTAAACAGTCGAGCTTACCAGTGGCTACAATCGCCCAACGATGCTCTTCAACACGGA
          AAGGCAGACTGTTAAGTCTACTATTGCCTATAAGCGTACTACTTCTCTTCGGATTAAGCA

          TGTTCGGGAGATTCTCTTCGCTGTGGTAACAATAGACGATGCCGCACGTGCATTGGGAGG
          CGTTCTGGGAATTAATTTCGCGGTGCCAGTAAAAGATGACACCGGATGTGCGTTTGAAGG
          TTTGACATGGATCACTAGCTTAGTGCTCTTGCAATATGAAGCGTATATCCTACATGGTCC
          TTCAGTATAACCCAAAATTTTGGAGACTTTGGCATAAGCCGGGAACGCCTCACATGGTAT
          CTCCCAATAATTGGCTAATTTAATAATCGTCACAACTGGTACAAGAATCCAGTCTGGCGA
          GGAGCGCCAGCGTTATAACGTGTAGTGCGCGCTGAGCTCAGGTTACTTCTTATCTCGTAA
          GGACCAGAGGCCGGCCACTACGGTAAGCGAGATCACCAGCGCACAACGTTTACCCCGCTA
          TACGCTGCAGTTAGACACTACACTGGGCGTAACCGATATCGGATAACATTAGCCCCCCCA

          CTGATATTACTCGGTCATTGCGGGTAGCACTTGGTACCGCACGTGCATGCAGTCACATAA
          CCGGTACTGTAGGATTATTGTGGGCCGTGTTTGGCAACATACCTATCTACTGTCGTCTAA
          AAAGCGGCATTCGGCAATGCAGACTGTCGCACGGTGGTGTTGGAGGTGGGCGTAGTTCTT
          GAGGCGCTATTCGACTACGCTGCCCTCTGCATGGCGACGTACCAGGTGGCTATAAACTTT
          CCGGTAGGTGTTGGTTATTGTAAATCCCATGTCCGACTGTTCTAGTTTCTCCCAGCATCT
          TTGGCTCCACTGATCACCCGCGGTCTTAGCATGATTTTATTATTATTTCTTTTAGCCTCT
          TGGAAGTTACTCATCATTTGCTGGCTTTTCTCGTTGGCGATCCTGACATTAGTTGACGCT
          CGGATGTCCCCCGTTGTTAAAGGATCTATTTTACCATTGTTGCTAATATTCATGGACCCA

          TAGGCGGCGCGGTCAATACGCACCTGTTCAGTTTCACGCCACCGGGAACGTGGCGACAAG
          CAGCGGGACAGGCCAATAAAAATAAGCTCGGTTTCCTGCAGTTGCAAATGTGGTGATAAG
          CTGCAACTAGCGCCACGGGGTGTCCACTCGGCTTCAGGAGTGCATAATGCACTCTACGAG
          CAGCTAGTTGGTCCAATGTACTCCCTTTTGGTTCCTTCAAATCGGAAGTCATTTCAGGAG
          TGAGTTGATAGACGCGAGTGCAACCATCCTGTGGGATGGGGTCACTTTTTGCTGGGAATC
          TGGCTAAAACGAAGAAAGGGGATATATTGCGTCTTATCAGATCCAACCCTGAGTTCTAAG
          CGGCCGAGTAACTGTCTGGGAAACTAATTTACTTTATGAGGCCGCACCGTTCGTGGTCAG
          CGGCCGAATAAATGCCCGCAACGTTATCCTATCCAGCGAGGCAGCACCCTTTGGAATCCA

          CGACCCTCAAATTACGGAGCATATTTAAATAAAGATGCTCGAGAGAAAGTTAGTGGTTCG
          GGACACTACGATTACGAAGCATGCGTAGATTAAAATGCCCAAGAGAAAAACAATATGTTG
          TGACTTGGGGATCCACAACTGCATCTTAATCATCCCAGACTAGAGGTCGCCCGTTAGCCA
          AAACCCCGGGGACCACTGATGTACCATGACTTTCCTACCTCAAGGATATTCATCCTGGTA
          GAGTTTATTAAAAGATGCACGTGTTTTCCGCGTACTGGGAGAAGCGCTAATGTTCCGTTT
          ACGTCTGGTAATTCAGTTTTGAATCTCCAGCGTTGTGTCCGAGTCATGATCAATGCTTCT
          GAAAACTGCAGTGGAACGTTCATATGGCCAACTTGGGAATGAATAGATAACTCACCGCCA
          GATAGCCGTAGCTGCTCATTTATTTACCAAATCCAGGCCTGAAGATATAATCTGATGCTG

          GAAAGGGATGGATAAGTATGCATACGCGCATTAGTTACACCTAGAAGAAAAGGGTGAAAC
          GAATGTGATGGATGTGTGTGATTATGGACATTAGTGTCACCCGGAGGGAAAGAATGTAAT
          GGCACTGTCAATGAGAGGAGTGTTCGGTGTAAGGCCATAATCGGGGGGAAAAGGCACAAA
          GGTGTTGTTAGTGCCAAGACCGCCCCGGAACAAAAAGTCCTTGGAGGCAAAAAACTTAAA
          ACTAGTATCCAAAGACTGATTAAGTTCCTAGTATTTTTGACGTTCGATTAAAGGTACAGT
          TAGGGTGCAGGTAGGTTGATCCAATGGTTGCCTGCTCTTCTTATGAACTTGACAGATGAC
          GCATATGTTGCTATGACGATCGAGCAAGCACCAATTGTCCCCTTGTAATACAAAACAAGT
          TTACATACTAATATTACAAACATCCTAGTACTTATCATCTCCCTGGGATGTGCACATGGC

          GACGGTAGATGAATCTGGCGCTGACGGCCGTTTGAATTTAAGTCTTGCCCTGCTATTCGG
          GATCGCCGAGGACCTTGGAGCCGAAGGTTGTACGGAGTTGAATCCCGCTCTGTCCTCCGG
          TGCGTATAAGAGTCGCTTTTGATGTGTACACTTGGCGATTAGCCTCCCCCTGCGATCCTA
          TATGCCTTAGATTCGATCTTACTGAGGGCGCTTCCTGAATGGTTTGCCAATACGGCCCCG
          GGTAATAAGGGAACTTCCTGCCCCTGGTCATAAGTAAAAATTACAGCACGAATAACCCCA
          AATCCTAGACAGTGCTTCCATTTCGGAACGACAGCGGTGGCACTAGTGCGTATTACCGTG
          GATTGTCGGGGCCAACTCCATCTGCAGTCGGATCCAGAGCAGAGGTTAAGTGCTACCACC
          GGTAATCGAAGATGCTTCTCTTTGCAGTCACAAGCGGGGTAAACAGAGTAGGCTGCCCTT

          TTCGGCTTCCTAGTTGAGCTTACAGTGACATAAAGAGAGGGTTGCGTCAGATAAGTAACC
          TCTGATCTTTACGTTGAGCTAGGTGTACTACATAGCCGGAATTATGACTCATAAATAACC
          TACAACCCGTGAATCAGATCTGGGTTGCGGCACAACATACACGAGGCAAGTAACTAAACC
          TGCACAATGAGACTGCGATCTTGATCGGGGCCCGATGTCAAATATGTAAGGAACTACACC
          GCACCATTGGGACATAGGGTTGAGGAAGAGTACAGTTCGCAACTTCTACCACCACTCATC
          TATATCTCGAGGGGCTGAGCCGGTGAACGACTGGGTGAGCACACTGCTCCAAATTTTACT
          TATGTCTTGTCATACGGGGTGTGGAAAGGTCTTAACGCAGCCAGCGTGGCACCTAACGAC
          CATGCTTTCCCGTGTGGGCCGCCAAAAGGACACAGCGCAGTTTGGCCATTGCTAAGAGGT

          CTTTGGTTACTGGATCCGCACATCGGACACCCGGCATGTAATCTATATCCTTCCTGCTCA
          TTGAGTTTGTCGGATCCGCACAATGGAAAGCCGGTATGGAATTAACATCCCCCCCGTACC
          GGATCGTCAACTGGTGGCTCTCTTTCATACTTTTATAGAAGCTCTCACGGCCCTTCATTG
          GAGTCCCTAGCCAGCGCGTCCTACTACTAGTCTTAAGGTAATATAGATGGCATCCCGCCA
          GTGCTTCTAATGGACGGAAGGGATTTCCGGGAATCATGTCCTTAGCGTGCGTCCATTCTC
          GTAAGTTTTCCGGATAGGGAAGTGCCTTAACGGTAAACCGATCATTGTCTCCCTATTTTG
          TCGCTCCTGCCCGAAGGGCGCGCGCAATTGGGGTATATTCTTTTATATTTACGTAGCCTA
          CTGCTCATGACTGAGGGGTTTGCGCATCTGGGGCACAGCCGCTGCCACTTACCTTACCGA

          CATCCTACTAATCCAGAGTTTGTTCCATTGGAAGTGTTAC
          TGCCATAACAATTAAGAGCTTAATCCATTGGGAACGCTGC
          TATCACAGTAACCAAGAGGAAAGCACGCACAGCGGTGATT
          TACGGTAGTAGTTGTGAGCCGCTCACTTACAAAGGCGACC
          TTCTGCCGCATTTTACGATCCGTTTTGCCGATATAAGATT
          TCAAGTAGTGTTCGCTGGGCTGCTTGGTTTTTCACGCGAC
          TAACGGTTCACGTGGCAAACCGCACCATGCCCTGATCAGC
          TCACAGTTAACTCGGCCAATTGTTCTATGTGCTGATCGCC

