 8 1000
t1        AAGTCCTAAACCCCTATGCTATACTAGGAGTTTAGGTGTAAATGGAAGAACGGCCCCGGG
t2        ATGCCGTAAACCCCCATGCAATACGAGGAATTTAGGTATAAATCGCAGAACGGCCCCGGG
t3        GCAATGCACATTGTCATGCTGTGCCGAAGGAAGTAACACAACCGATTTCATTTTTCGGAT
t4        TGATTGAACGGCGTTTCGCCGTGCACGAAGACATGCCTAACCCTATTACCTTTCTAAAGT
t5        TCACTGTGGATTTCGATGCTCCGCCTGGCTTCCAAAATAAATCGCTGCTCTTTAATTAGC
t6        TCTCCGTGTCTTACGAAGCCTTACCTGGCTTCTAAAGCAATTTGCTCTGAGACCCTATAT
t7        TATCCCTGAGCCCTAACGCGGGACCGGATTATATCTCCGATCCGAACTTTGCGCTCAAGT
t8        CCTTCCTGTACCTCAACACGGAATAGGAGTTTATTTACAGTTTGGACCACTTGCCCACGT

          TCCGTTATAAACCAGTCGGTACGTGCGAGTGAACCACGCCCGCTTAAGGGACTATTCACG
          CCCTCTACAACTCTGACCGTGCTTGTGAGGTAGTCATACTTGTTTCCGGGGATAGTTTTA
          GTGCATTCACCGGTCGCAGCACGACTATCAATGTAGTGCTAACTCGGAGTGCGGTCGGCA
          GTGACTTCGTATGCTGTGCTTACTCCTAGCACACGGCGCTCATCCTTGGGTAAACCGGTC
          TTTTGCTTGGGGCACATCGAGGTCGGGTACCAATGATGGTGATTGTAGCGAGCCTCCGGG
          ATTTACTCCATGCGTCTTGAAGTAGAGTATCTATGGCGTTGATCGCACCGAGACCCCGAG
          TGAGGTTCGTTCCACACTGAGGTGACCCATACGTTTCGTCGTACAGATCCTAATTTCTAG
          TTAAGTTCACTTTGTGGTCAGATTATACGCGTGCTGCGTTGGAGGGAGTATCATTCTGAG

          ATGATCCCTAGGGGACCGGATGAATTCCATGATTACAAGTCGATTCTAGCATGACTCCAG
          ACAGTCTCGAATGAACCATGTGAAATCCCAACCGCAAAGTCCACTCTATCATGAGTTTAA
          TGTCTTAGGGAAACGCAGATAGTAGTTCCGCTGTTTGTGCCGGGCCTTATCCTGGACATT
          CCCCTACTGGGGGGGTGGATAGTGATCTCGCACCGATAGTCTTCCCTAACCCGGGTTACG
          GTATTCAAGTGGGAACTGTCATGAATTCCGGAGTATGCGCCTAACTTCGTAATCAACAGG
          GCAGTTGACTAGAAACTGCCGCAGATTCTGGAACAGCCACCTCGCTTCCGGAACAATAGG
          CCGTCCGCTTCGAAACTGACCAAATATTGGGTATGGTGTCCCGACCTCTCTCCGATCATG
          CCTTTCACATAAGAGCTATAGAAAGGTGGGGAATGCTCGTCCGATTACCGTCAAAAAAGG

          CCATTCGGACGCTAAGGACGTCCTCATTTCTCCCATACTGTCCGTCTGTCGCCGATTATC
          CGCTCCGGACGCTAGGAATGTCTCCCTGTCTCTCTAACCGTTCGCCTGTCGACACCTACC
          CTCCCTATGTTTTAGAGGTGGGTGTACTTCCCATCAAAGGTTCATCATTGCACGTTCATC
          TTGCCCGGGCTGCAATTCGAAACACTCTCCTGACTCGTTAAGTGCTGTCCGGCGTCCGTC
          CGTATCTCGTTAGGTATCCATTCGCCGGGATCATTGCCCCCTTGATGCATGCCGATAGGC
          CTTATTCTAGTAGGAATCTACCCGCAGGAGTCATTGTCCCCTTAATCTATGTCGATAGGC
          TGCCGTAGGTTAGGGACTGGGTCATAGTAGCTATCGCGCGCTAGGTGGTACTTGTTCACA
          TCCCACGTGGCGATGACAAGTACACAGCGGCTATCACTCACTAGATGCTATTCGCCATTC

          CTGGGCTAACGGAATTATAAGGAGCTAGCGTCCCGCCGCGCCTGAACGGCCAAGCAAGAA
          CTGGGCCAAGGGGATTGCAAGTAGCTAGCGCCTTGCTGCGTCTGTACCGGCATATAGAAA
          AAGGATGGAAGTGTCCGCGGGTGGCCAGCGTCTAAGGTTGGAAGAACCCGCAGATCAGGT
          CTTAATAGAGGCAAGCATCTATGATTGGAACCACAAAAGGAAGGCACCCTCAGGTAATCT
          CCGGGGGAATCACGATCCCAGGCCATTACACCGCGAGAGTGACGGGCTGAAAGATCAGAT
          TTGCGGGAATCCATATGTCGGGTTATGCCATAGTAAGAGTAAGCATAAGCAGGTTCAAAT
          CTGCACGGGATAGTCTGTTACCTAGTTGCACCATGGAAAAAAAGATTTATACGCTCGCAC
          CTACATGAGGTAGACTGTTACTCTGTTGTAATGCAAGGATGCATATCCATACCCCCGCAT

          ATGCGCCATAAATTACCGGCCAATTTCGGTCATGTATTAAGCTGTTCGCAGGAGGTCCCA
          ATGCGCCCTAAATTACTGGCCAACTTTGGTCTTGTCTCGAGCAGACTGTTGGAAGCCCCG
          CAGGAGTAAAAGCGCATGGTTTATAAGGCCAAAAAACCTTGCACTTGCCGGTCAGCCCTT
          AATCTGCCAGCGAACGCCGCTAATTCTGAGTCCATTATTAGTTTTTACTAGGTAGTACAC
          ACTCCCTCTAGGCGAGAAGATGATTCTACTTGTGCTTCAGGCCCCCCTGTGCCCGTTCCC
          ACTTCCTCTAGGCAGGACCGCATCTGAACACGCGCTTCAAGTCTTACTCTACGCGCCCTT
          GCCACCCCGCGCCCTGGAATTAGCGTTTCCTAGGCCGCTAGCCTCGTTCCGCCAATTCCA
          ACTCTGCCGTGTTAACAGACTATCACCCCCCGGGCTTCTCGTCTTGCTCCGTCAATTTAG

          TTTGATACAAGTAATCTTGGTCAAACCTTAATTCCGTAAAATCAACCTGAAAACAATGTA
          TTAAAAGCCCGTAATTTTGGCCAGAACTCAACCCAGTGCAATGGACCGTATAACAATGTA
          CTACCTCGTTGACGCAGGCCCAGTCCGCAGAACATTTCAATTATGAACAGCCATCAGTGG
          TTACGGCCGAGTCGCCCAAGGACCAATCCAACTTGATCCTGTCAGGTTAAATGCCACCGC
          AAGTACCACAAAGGCATATGTGACCGTTTTTATTCGTCATCAAAGAATAAACACTGCGGT
          AAGAAAAACCTTGGGGTGTGGGTGAGTTTCTTTCTACTGAAAACGACCTAACACTGCGGT
          TTAATCAGAGAGAGTGTATATAGCCGCTATAACCCATCGAGAAAGGTCTATCAATGTGAC
          TTAGATATCGCGCGTATGTGCAGTCGTTCTACCCCAACAGACAAGACCTAACAATATCAC

          AAGGACGCTACGCCGCACAATAACAAGCGATCCACACACCATAGTCTTCGACTATCGTAT
          AAGGATGTCACGCTGTGTAATAACAAGCGACTCCGCCAACGTGGTCCTCGAGCGTTGTTT
          GGAGGATCGAGCCCTGGTAGAAGAACGCGGCTCATTCCATCTGGCTAGTGGTTAAAGTGT
          GTAGAATTTGACAAGAGTACGAAAGCTGACACCCGTCTTTCTAGTAACTGAACAAGGGTA
          ACGAAACTCAACTAATCCAGTTCTAGACGGCGGAGGACATCATACCATTAATTCCGATTG
          ACGTAGTTTTATTTAAACTGTTCTAGACGTTGCATCCTATCGTACTATATGGTTCAATTG
          CTTGAGTTTAACTCCGATGAATATAATTCGGGTAGTTTCCCAGGTCAATATTTGTAGCCT
          CCGGAGTGCAGCTATAACGATCACGAACGGGGTGGTACCCCATGCCGATAAATGTTGGTC

          CGATGCGGGTAGTGTCGCTCCAGCCCCTGTAGTCAGGTATCACGCTAGTCATTCCGCGGA
          CGCAGTGGGTAAAGTCGCTCTAACCTATGTGGTCCAATATCCCCCTAGCCGCTCCGCGGT
          AGGGGGAGGTAGAGTTTTTACAAGATCCGAAGCTACGCACGTTATGCTGCTCCCGACTGG
          GTAAAAGAACAGTTGAAGAATAAGCTTTACGACTTGGCCCTCCTCTTTGCCTTCTGCCGT
          CAAAATACGCAATAGTCATATTGTCTACACGGCCATGTTACCGCGTTTGCTCTTACTGGG
          CGAAAAGCGCTGTAGACACGACATATAGGTGGCCATGCTACTAAGTTTGTTCATATCGGT
          GTAGAGCCGCAGCGATTTCTTTGTTTACGCATTGGTGCTAATATGTATGGTTGTGTCACG
          CAAAAGTAGCACCGGTCCCCTCGTACACGCGTTAGAGCTTTCGTAAGTGAGTTGGATGTG

          ACAAGGCAAACGGGGGTCATACAGGTCTGTGTGGCATGGACGTACACGCATGGTGATTAT
          GCAAGGCAAAGAGGGGTCATCCAGAACTGAGCAGCATCGCCGCTCAGGCCTGGCGATTAT
          CGAAGGATGCCAAAGGAGATCTAAACTGTGGGAAGATAGTGGCGTGACTCCCGGTGACGA
          CAAAGACCTCCTGTGGATACGCTAACCAATGAACAATACAGCCATCGACTTAGGGGGCCA
          CCTTGACCGTATGAACCCACTCGAAGTTGACTGATAATACAGCATATCTTTCGAGGTTGA
          CCTTGTCAGTTTGAGCCCCTGAGGAATGGACTGATTGTGTTGCTTACCCTTGGTGATTGT
          TTCCGTTAATTCTAATCTATGCACGAGTACTCAGTTTTATCATATTGTCTCCAAAGTAGC
          TTCCTCTAATTTAAACCCACGTAAAAGTGTTTTTTCCATACACATGCTCTTCGATGTAGA

          AGTATGGATTTTTTTAGCTTTGATTACTTACGCCGCAGTTGCCCCATAATAGGCCGAGCT
          AATACAGAGCTTTTCACCTTTAATAAGCTATGCTGCGGTTGTGACACAACAGGCCGTGCC
          GGCAAATTTTCCCCTCTTTCCAAACAGTCAAATCCCCTTCCAATTATAGATCATGTGACC
          GTCGTTATCGCTTTTTACCTCATATTATCAGTGCCTGATGCCGTTGTCCTCCATCCAAAG
          GAGCAGTAAGCTTCTGAAGGCTATTGAATCGATTCTTGAGAGGTCATACGATCCTCTGCA
          GGTCGGCTGCCCTCTGAAAACAATGGATTTGCCCCTTAAGCTAATAAGAGATCTTCTCCA
          AATCAACTAACATAAGCACGCAACCCAATCAGTTCTAGCTCCGATTTGAATCGCTTCCAA
          GATCCTCCACTATACCCAAGCTGTTGATCAAAACAATTGTTCGGATCGAACCGCTTCCAG

          GGGTGGAAGGTATCTATATAAGAACGTGTCCTGGGGCTGCATGCCCAGTACAACCGGCAC
          GCGTGGATGGCAACGATTTCAAAACGTGCTCTGGGTCCGCAGTGGTTGCACCATTAGCGC
          AGACGAGGCGCGCTCAATTGTAAAAATAGGTCTGAATCACAATAAGTGGATGGTTAAGGT
          AGTTACGACGTTCCCAATCCCGACAATGGCCTCCGATATCGATTACCGAGGAGGTAATAC
          GTTACTGCTGTGGCCAAAGTGGAACGGTGATTGGGCCCACCTCAGCCATTGAGGCTTCCA
          GCTATTGCTGTGTCGAAAGTGCGACGTTCGTCGGTCCGACAGCAGCTAAACGGGTTTTCA
          CTACATACTTTGTGCGCAAAGAGTCAGCCAACGGCGCAATGCTGATGGAACAGATCAATT
          TCGCACGATTCGTGCCCAAGATAGCGCCATTTGGAACACAAGCGGAAGAAATGAGAACTT

          ATAATACCTGGTGAGAGCGCGTCTTCTTTTGATCGCAACCAAGTGCTGTGGACCGCGTAA
          ATAATACCTGGTGGGAGCGTTCCCTCCTCCGTCCTTGGCTAGATGCCCAGGGCCGCGGAG
          ACGGTCCGGGATTAATGCTTTAGACTCGTTCATCGCGGCCATGAGTCCTGGATTGTGTAG
          TCAAGTCGGGACGAAAGAGTCCGACTCACTCATCGTGACCAAAGGTCTTGGACAATGTAG
          GGGTGTAGGATTACGTAAGTCCAGCCAAACGCGACGGGCACAGTCGTTAGGATTAAAAGA
          GGGCGTGGGATGGCGAACCTCAAGTACACCGGAAAGGGTGATACTGCCAGGATGGAATGA
          GAGCGCGGGGTTAAGAGAGCCGGGTACGCCTGTAAGAACACCCGTCCCAGAACTAAATAA
          GCGTACAAAATTACATGTTTTGAGATCTTCCGTGAGTGCTGCCGCTCTACAATTAAAAGT

          GATGGTTGGGGAACTTTATACCAGCGTTCATAAAGACCTTTGCCCTGTCTTGTATGGATC
          GATGGTTGGAGAACTTTACCCTGGCATTCAGAAAGCTCCTAGTCCTGCCTTGATTGGACT
          GTTGGGTAAGGCCGCCAACGCGAAATAGCCGAAAATTACCTTTGATTCTCAATCCTGAAT
          GCTGGACAAGACAACCATACTAGGGCAGCCGAGTATCGTTTTTACTCTTCTGACTAGGCG
          CGCATCCAAGAGCCGCAACGCTGAAGGCTTTCAGATCGACCATGCCGGCTCCTACCGTTA
          AGAATCTAAGAATCGTTACCTTAAAGGCTTTAAAACCCACCATGCTTGGCCTTATCATTC
          GGTTGAATGTGAACGTCAGTTCAAGGGTCCGAGAGTCTACTAAGTCGCCCTCTTCTGATA
          CATTACTCGTGAACGTCAGCCGAAGGGCCTGCAAGTCCTCAATTTCTTCCTGGTCACATA

          CAACTCATGATGAGAAGTGCTTTGATCTATTATATATATACCATGAAGCTGGGCAGGATC
          TGTCTCACGAGGAGAAGTGCTTCAATCTTATATAGATGTATCATGAAGCTGGGCCTAACC
          GGTGTTGGAAAGAGCAGGCTACCAGTTCGATATGCAATATGAAAACATCAACGTCCGGGC
          ATTGTAGCATGGCACAAGGCAACACCGGAGTTTGCCCGCCATATACACTCGTGTTCGGGC
          GCTACCATATGGACCAATGTTCCAATTCCGTAGGCAATCACGAGCGCATCGCGCCAAGTC
          AACAATAAATTACCCATCGTTCCGTCTCATCGTGCAGTTAAGAGGGGATTGTGTTCGGCG
          GGGACGATATCAAGTAACTCCACGGGTCAGCCTTTAGTGGGCTGGGCTCCGCTCTTGGCG
          CGAGGTTACGCAAACCAAGCTTCGGACTATCGCCCAGTGGCGGCAGCGCCGTTTATTGCT

          GGCGCACGGGCCTAAGAGCTGTCATTGAGCGCGGAGTTTGTTTTGCTGGCAAACGAGGCC
          GGCGCACGGATTTAAGACCTCATTTTAGTGGCTGCGTTCGTTTTGCTAAAAAGCCAAGCC
          GAATTGGATGGTCGATACCTTTGCCTTGTCTCGATACTCACCTACTCAATGGTCTGCTTT
          GGAATGGGCACTCAGCGCCCGGCTGCCCGGTCGGTGTTTGCTCGAGCACAGAATCGGACC
          GTCGCACAGCCATCATCCCGGCTACAGCTCTAGGTTACGAATGTCCCGTTAGCTGCGTAT
          AACGAATAGGCACCACTCCTCCTTCTGTTCGAGGCCTTGACTGCATCGATATGTACAAGT
          GAATAAAGACAAAGTTCTCCCGTACTACTCAGGGAGCACACTGCTCTCTTCGTCCCGAAA
          GAAAAAAGATACCGGTGCCTTCACTGGATTCGGGAGCTCATCGTTCTAGTAGAGCTAAAG

          CCGTACAGTGTTGTTGATAAACAGGAACAACTCTTACTCT
          CCGAACAGTCTCGTTGACAAATAGGAACATTCCTCACTTG
          GAATCTGATGTTTACGTTCACCGAACTCATTACTCGGTTG
          GTAAGCGGTGACCAAGGTTTACCAGAGAAACCCTTGGTAC
          CCGCGTAGACTCAGCGGAAACTAGGGCGAAGTTTTCCTAT
          CCGCGTTGAACCGACGGACACTAAGGCGGAGACCCGTTGT
          TTGGGCTAAACGAACGCTGGGCAGGATCGACACCCATTCC
          CCGGGCCATGCAAGCTGTCGGAGAGATCGACATCCACCCT

