 8 1000
t1        CTATGGATTCATTGGAAGTCATGTGTAGGGCTAACACGTGTCGGCTGTAGTAGACGACAC
t2        AACTGCTTCCGTTTCCAGCGATGTTAAGACCTTAAAAGCATCGTTTGTTGTAACTGGTGA
t3        AGCCCTCTCGAGCGGGGTTAGTGCGCTCATTCCTATAACTCGGTTTACTAAGGTTATTGA
t4        CGATGTTTTCAGTGAGAGTAACTTATATAGCGCTAAAGGGTCATTGATTGAAATTGTTGG
t5        ATCCAGCACCGCCAAGGTAAAGATAGGGTCCGCGAGACAATAACGTAAGAACTGGTCCAA
t6        ATCCAGCACCACCTAGGTAAAGACGGGATCCGCGGAACAATTCCGTACGAACCTGCCCAC
t7        TTCTAGCAACGCGTTGGTAACGATGAGGGTTGTGCGACAGTTCCGGCAGAACCTACCGAG
t8        TTCTAGCAACGCGTTGGTAACGATGAGGGTCGTGCGACAGTTCCGGCAGAACCTACCGAG

          TATCATATCCGGACCAAAGTTGAGTGATGACCTTCAGCGTATGCTGACCTACTTTGCGAG
          TCATCCAGATGTCTCGGCGCAAGCCGCTCCCCAACCCTATAGGTTAGTCTAGTTGTGGGG
          ACACGTACCAATTTCGAAGTATGCCCGAAGATACCTTGATGAGCCATTCTTTGTAGCGTG
          ACGCGAGTCCATAATGATGCTAGTTGGGGTCGACCAGCGTAAGTGAGCCCATGTGGGGAG
          CCGGATGACTCCGCCAAAGCCGACGATTCCCTCATCACCAAAGTAGCGCCGTTCAAGGAG
          TTAGCCAACACCGCCAAAGCTACTCATTCTCATATCAACAAAGCGGCGCCATTTTTGCAG
          CCAGCTAGCACTGTCTGAACCGACCGTATCCGTATCATGAACGTAGGACTTTCGGACGAA
          CCAGCTAGCACTGGCTGAACCGACCGTAACCGTATCATGAACGTAGGACTTTCGGACGAA

          AAACGATACTCTGTCGCTCTGCGGAGGAGCGGCTGCTACTTCCGACTAGGCAGTAGAAAT
          GGATGATGTTCTGCGCTTCATCGCGATCGTAGGCAAAATTTTTGATGACACGGGGGTTAC
          TGCTGCCAACCCCGTGTCTAGCGAAAACGTGCGCGTCATGCCGGAGCGAAAGACGAAATC
          CGATGTCACTCTTATGGCCAGCCGGGCCGTTTGTGTCACGTTGGTGTGGTATGCGAAATC
          AAACCAAAGGCGCTTCCTAGGCCCGGATGCAGGAACTAGATTGGTATTGAAAGTTTTGAC
          GCACCGAAGGCGCTCCCTAGGACCGGCTATAGAATCTATCTTGGTATTAAAAGTGACGAC
          AGACCATAAGCGTTATCCAGACCCAGCCATACAGTTCAACTCAGGATTAATGGCAGTGAC
          AGACCATAAGCGTCATCCAGACCCAGCCATACAGTTCAACTCCGGATTAATGGCAGTGAC

          CAGCCATTGCCTCAGCAGCAAACACCGCTTGTGAAGCAACTGAACTCCTCTCGCCTCAGC
          CCGCTGTCGCCCTCATATCCATTACGGCATACTATACTCCCAAGTTTCAGCCGGCCGACT
          ATGCCACTCCTACATCGGCTATCCCCAATCAAGATCCCGGTATACCAACACTTAGGCAGC
          ATGGCAATTGTAGGTCACTGAAGCCCACTCATGTTATCAATGATTTTTTCTTTTGAAAAT
          ATGCCGCACCCCTGCTACTCCATTTGGTTAATCACGGGCCTGGGCCAGCCAGATTATGAC
          ATGCCCCACCCATGTCGTTTTATTCGGTTAACCGCTGGGCTGAACCAACCACATTATGAA
          GTGTCACACCTCGGCCACTTTACTCGGTTTACAACAGAAGTAAGCCAACAGCAACGTAGA
          GTGTCGCACCTCGGTCACTTTACTCGGTTTACAACAGAAGTGAGCCAGCAGCAACGTAGA

          TTCATGATGGCGTACGAGGGCAAATCCGATAGCTACCGGCGGTGCTAATTCTTGGCAACT
          TTCACGGCGATAGTTGATAGAGAATGTGTTACCTTATGATGTCCCCGGAACCTTGTGGGG
          TTCACAGCAACGGAATTCGGCTAAAACTATTACCACTTGTGATCTATCTCTCAGGTGGAG
          TACTCGCTAGCAGAATACAATAAATACGGTTTGCACCTGCGCTACAGCTCACAGATTGAA
          TTTGCGGATATCGATCAAATTAATCGGAGATCCAGCACCTCGCTTTGCTCTCGGGGAAGA
          TATGCGGAAATTGATCGTATCAATGGGAGACCTAGCACTTCCTTTTGTACTTGGAGAAGG
          TTTGGGGAAATAGAGCGTATCCATGAAAACCTTTGGCCTGCCTCCAGCTCGAAGAGAAGC
          TTTGGGGAAATCGAGCCTATCCATGAAAACCTTTGGCCTGCCTCCAGCTCGCAGAGAAGC

          GACCCTATCGGCTAGCGGATACAAATCAGGTCGGTTGGCCTGAGGTATGCATTCCCGGTA
          GGACTGATTTGCAACCCAACTCTACAATTAAGAAATGACCTTTGGTTTCCAGTTTCGAGC
          CAGTTTACATGTGTATGAAAACCAGTTGACCCAGCTGAGCCGTTGAAGACGATCCTTTTG
          CAGTTGACGCACGCCTGAATACGGTTTGATCTAACTGAGCCCCGGAACCTGATTTTCGTA
          AGCGCCGCTCATGCGCCTCTCTTATTCAATTCCTCCGTTAAAATATACGTATGATTGAAG
          AGCCCCGCTCACGCGACATGGCAACTCATCTCTTCCGCTGTAATATACGTACGATCGAGG
          AACGATGCATATGACTCTTTTTAAATTGCGACTCCCGCTGTAAAACAAGTGCGTTGAAGG
          AACGATGCATATGACTCTTTTTAAATTGCGACTCCCGCTGTAAAACAAGTACGTTGAAGG

          ACGCCCATACGTAGCCATAGTCGACCCGCGTTCAAAGGGCGACTCCTCATCAATGGTATG
          TGCCACATATACGCTCATTGTCAAAATGCTCTTACGAAGAGCTACCCCTCAGAGAGAATT
          GGCCTGACATGCCTGCGCCCTTGTGGCACACGTACGCATAAATTCCTAGTAATCGGCGTG
          GGTCGCGTGTTTTAGGTACGCTGTAGTAGTCTCCCGCACACATGATTATGAAGTGATGCA
          GTGTCAATAGTTTAAACCAATCGTAGCGCATTTCCAAACCAATCCCATACCGGTAAGTAT
          GGTTCAATGGTTCAGGCTAATCGTATCGCATTCCCAACCTAGTCCCATGCCAGTAAGCAT
          GCGCCGTAGGATTAGGCTAATTGAAGCGAATCCTCAAACCTGTCTCATGCCCGCAGGTCT
          GCGCCGTAGGACTAGGCTAGTTGAAGCGAATCCTCAAACTTGTCTCATGCCCGCAGGTCT

          GATTCTGATAAACCCCCCATTTGGAATCGAGTGTCGCTCACGTCATCGGCCGGAGGACCA
          GTCCTAGACGAATAACCCTGTCGGGAAGGATCCCCGGGTTCTTCAAACCGGATATAATCT
          GTTTGTGACATGCACCCTAATCGGTCGCGAAGATCGTGCCGGAGTATGTGACTTCAAGCG
          ATCCTCGACGGACCACCCGGTAGGTCCGGAGGTTTAGAATAGAGAAAGCAGTCCGAACCA
          GTCTTTGTCTTAGTACACGAGATGGCAGCACTCTTAAGTCTTCGTGAGCATTTCAACATT
          AATTTCGTCTCTGTGTCATGAGTTATTGTACTCATAGGTCTTCGCGTACGTTTCAACTTT
          GAGCTCGTTCTTATACTACTGATGGTAGCGGCGTTGGGTCGCCGTATGGGCCGTAGCTTT
          GAGCTCGTTTTTATACTACTGATGGTAGCGGCGTTGGGTCGCCGTATGGGCCGTAGCTTT

          TCGCAGTACATCAGTCAACACAAAAGTTTCTGTCCATACAGAACTCGGTGCCTAGGGGTC
          CCGTGATGCCTAAGGTCAGTGACGGGTAACCGTCCTTTGCATGATCAGCCGTTGAGGGCC
          GCCCACGTCCAAGCTTTTAATAATATTTGTGGTTCCTACAGAAACTAATGTTTAAACGAT
          ACCCAGTCCCCAGTACTCCGTAACACTTATAGTCAATACATAAGCCAATGGTTGGACTAC
          AAATAGCTTCCAATTTTAGAGACAGGGCGACGTAAGCTTACCGGAAAGTATTCTGCTAGG
          AAATAGTGTTTAATTTTGGAGAATCTGAGACGTAACCTTATTGATGATTTCTTTGTTAGG
          TAATTGCGTCTAACGATGTACAACGCGCTGCCCAACCTTATCGGCAGTCGCCAACTCAGC
          TAATGGCGTCTAACGGTGTACAACGCGCTGCCTAACCTTATCGGCAGGCGCCATCTCTGC

          GTAACTATCGCAAGCACGACTGCTTCGGACCACATGACGCTACGTCGCAGGTCACGTGCT
          GGATTTATCGCATGCATGCTCAATCTAGATCACTCGTTATTACCCTTCGCGTTCAGAATC
          GAAACTAGAGTTGATATGCGTGACCCCGGCGCTTAATTGCAACGAATTGGGACTCCAAGG
          GAAACTAAGTTCGACATGCACCATCCCGGTAGTACATCGCGAGATTATCCACCTCGACTG
          AAGACCGTTGGAGTTAGATCAGATGGCGGGCTGCCGGCCAGCTGCACCCAATTTTAGGGC
          AAGATTATTGGAGTCACATCAGCTAGCAGGCTGCCGGCCAGCTAGAGCCAATCCTAGCGC
          AAAATGATTCCAATTAGATTAGTTAAAAGGCTATTGGCCCGTTATATCCACTCCCGGTGC
          AAAATGATTCCAATTAGATTAGTTAAAAGGCTATTGGCCCGTTATATCCACTCCCGGTGC

          AACTTGATGTGAGGCCCTAGCCAGTTCCGACACAGCAAGCTTCGCGTTTAGTGCGAGAAC
          ACTTGCACGATCGGTCCTAGTGTGAAATGACATCACTGACCGGATACTCAATCCGACGCG
          ATCCTGCTGCGTAGGCGAGCATCGTGGCGATCGGATTACATGCAGATCTTAATAATTTCA
          AACCTATGATTTAATCAAATCTGTGCACGATCACTATACCCGCGGATGCTAGCAGTTGCG
          AACCGGTTTTAAATCCGACGTTCGTGTCATTCACGCCGTATGTGAATGTATCACGTGCGA
          GACAGGTTTTATCCCCGACGTTTGTGTCATCCATGCCGCACGTAGTTGTATCTGGCGTAC
          AACTGCTCTTGAAACCAAAGAACGAGCCATCCGTGCTGGTCGTCGACGTACTTGGCAAGC
          AGCTGCTCTTGAAACCAAAGAACGAGCCATCCGTGCTGGTCGTCGACGTACTTGGCAAGC

          ATTTTCTAAGAATACTTGCTATTTGCACAGGCAGTCGCAGTGAGGACACTAATAGATTCA
          ATTCCAACGTTGTACTCCTTCCATAAGCAGGTAATTTCGGCAAACAAACAACTCTTCCTA
          ACTGCGTGGATGCATTTGGTGTCAACGTGTTGCGCTTCGGTAAGTTCCTAGCCCTCTCCG
          GCCGCACAGATATATTTGGCGCTCCCGCGTCTACCGACGATCGGCTCCTGTTCCTTTTCA
          GTTCGTGTAATAAACATGGCAAGTATGGAGGGCAAGCTGGGAGGCTCTCGTTTATTCTTG
          GCTTGCGTAATGAATATGGCAAGCCTGGAGGGTAAGCTGAGCGGAGATTTCTCATTTTCG
          GTCTGAAGAATAATTAAGGGTCGTTCGAAGGGTGCGACGCGCAGTAATTCTTCTATTTCG
          GTCTGAAGAATAATTAAGGGTCGTTCGAAGGGTGTGGCGCGCAGCAATTCTTCTATTTCG

          CCAACAATGCTTCGCATCTAATGTTAGCCGGGGCCCGACCCAGGTGAATGCCAGCCGTAT
          CCTACAATAAACTATGTACTAACTCAATCTGGTCCCGACCTGGGTGCCCGATAGCCCAGT
          ATGACCAAGAACTAGATCCAGGGCCTGTTGACTTAAGATCTATATAAAAACAAGTCTAGT
          CTGACGACAAGTTTGGCCAAGGGATTGCCCCATTAATATCTAGGTAACCGGAAGTTCTGT
          ATCACCTAATGTCTGCAATATAGCCAGCTCACCTTACTTTCGCACAGATCGTAGACCAAC
          ATCACTTAGTGCCCGCAATCTAGCCAGTCCACCCTTTTTGTGCGCAGATCGGGGACTGAC
          GGCCACTCGCGGCCGTAAATTCGCGGGCACACTCCACTTACGCGCAGATGATGGATTGAT
          GGCCACTCGTGGCCGTAAATTCGCGGGCACACTCCACTTACGCGCAGATGATGGATTGAT

          CCACACATAGGCAGGTCCCCTCTATGCCCATAGGGCCCATGGTTACCTGACGAGATTTTC
          TCCGAGACGGGTACTTCCCTTATAATGTGATCCTGCGCTTGGACAACAGGGGTGATTGTG
          CATTTTAGTGCCATTTTTTACTCAGACCCATTCAGCATGTGACCTTCGGCCGCAACCGGG
          CTCTCTAGCGCCATCCTATATTATGTCGGTGTCCATATACGGTCGACGGTCGCTAACGCG
          TACATCATGTAACAGTAATTCTCTACGACGTGCGATAAGCAACTCACGTTTAACGGCGTC
          TACTTTATGTGCGCGTAATACTGTATGAGGTTCGACAACCGGTTGACGCTTAACAATGTG
          TGTCGTGTGTGCTGGTAATAACATGTGGCTCCCAACAGCCCATCATTACTTGGCGGCGCC
          TGTCGTGTGTGCTGGTAACAACATGTGGCACCCAACAGCCCATCATTACCTGGCGGCGCC

          GCTTCCGGACGCGCGTCGGCGTTCAAGCGAGCTACGGGCGTACGTCTAGTGTTACCTCAA
          GTTCCTGGACACTAACCGTCGGTACAGCACGTTATATCTGAACGGCCAGCATTGTTACAC
          GGTGCCAGATGCTTGCCTCCAGCAAGGTGTAACACACTCGTGGGGTTGGCGCTGCCACAA
          GACGCCCCGAGATTGGCTGCACCAAGATGTGATGCCCTGATTGGGATAGCGTTGATACGA
          TGATAGTAGTTCAGCTTAGAAATAGCAACCAGGTCGTACGGGCAACGGCCCCAACCCTCC
          TGATGTCGGTTCAGCAAAGAAATGGCAATCAGAGCATACGGCCAACGGCTCTTATCTCGT
          TACCAACGGTTCACCCTAGAAATGGGAGACGGGCGATCTAGCCAAAGGTTATTACCCCCT
          TGCCAACGGTTCACCCTAGAAACGGGAGACGGGCGATCTAGCCAACGGTTATTACCCCCT

          GGTACAGGCGGTTCGGGGCACCTCGTGAGAGATGTGATTGGCTGAGCTGATAAACCGAGA
          AAGCTTGATGGCTTTTCGCACCCCACAAATACTGCGACAAGACAGGTCGACCAAGGGACG
          AGATGAGGCTTTTTAAGGTTCTTCACAGGGCAAAACATTGGCAAATCGGAGGCCGTACAA
          AGCTGAAGCGCCTATAGGCCTTACACGAATTCCGACGCCGCCGCATCAAAAGGAACGTAG
          GGGATTGGTAGCCCAGAGCTACCGGCCGATTGCGTTAGACTAACATCAGCTCAGGTGTGA
          AGGGCCGGCAGTCCCGAACCACCGGCTGATTGCTGCAAAAGAATATTAGCTTAGGTGTGA
          GGGATCGGTAGTTGAGGGCAACCGTACGTTTACAGTCTACTCACCCAAACCAGACTGTGA
          GGGATCGGTAGTTGAGGGCCACCGTACGTTTACAGTCTACTCACCCAAACCAGACTGTGA

          ACCCTCCGGCATCCCGGATAATATTTCGTACTGCACTCGA
          AATTCCTACATTCTTGGGCAACATCGTTTCTTGCACACAC
          AGTCTCTAGACCGCCGGCCAATATCATGCTTTATTTACTC
          GACTTTCTGATCTCCGGACTACTATAAGCTGTATTTATAG
          ACATTTCCTGGACTCGACGGGCACCGGACAGCATATGCCC
          ACATTACTTGGGTCCGGCGGGCAGTGGACAGTATATGTTG
          ATTCTCACCAATTTCGACAGACATTGGTCAGCGTAATTGA
          ATTCTCACCAATTTCGACAGACATTGGTCAGCGTAAATGA

