 8 1000
t1        GCCCCCCACCGCTTATCGTGGATCGACCCAACCACTCTTGGGGTAATCGGGTATTCACCA
t2        GCCCCCCACCGCTTATCGTGGATCGACCCAACCACTCTTGGGGTAATCGGGTATTCACCA
t3        GCTCTTCGCTGTCTCGCATGGACTGGCGTATCCACTCCAAAGCTACTCGAAATATGAATA
t4        GTGTTGGACGATTGTTATTCATTGGCGGACGATACGCCGAATTGGCCAGATCTCAACATA
t5        ATCTACGATAACCAGTCGACAATGGATGATGCTCCACGAGTAAGACCAGAACTTGCCGTC
t6        GCTCGCGGCTCGCAAACTGTCTTCGGGGCTATGACCCTCTCGCGTCTTCAATCGACCGGA
t7        GCTAGACGACGGAATGTTCTTGTCCGCGCTGTAACACTCACTTGGTTTTAGACTCCTGCC
t8        ACCATATAAATAGTAGTTCAGCTGGGTCACGTAGGGTTATAGTGGGTCGCAAAGAGTGGG

          ATTGGTGACTGTCTTCAATCAATCTGATTTTGTCCTCATCAAAAGGTCTTTGGTGATACC
          ATTGGTGACTGTCTTCAATCAACCTGATTTTGTCATGATTAAAAGGTCTTTGGTGATACC
          TTTGGTGACTGCCTTGAAGTGATTAGATGGGTTAGTAATCAAAAAACCTTAGGTAGCGCC
          CAGGATACAGACATTCGTATTTCTCTCCTTAGAGACTTACCTTGAGCAGGAGGCAGAGGC
          CCGTCACGCATTCGTTATTTCTCTAATTTCTATGGCCTAATATAAAACCCACACGAGGGC
          CTGTACCACCACTCCAACTGTTTGTAACAAAGAGACACGCTCGATTTGACAAGCCCCGGA
          TCGACTCCTTGTCGAGTATAGATACAGCAACATCGACGAAAGTAGATCCAGAATTGAGGT
          TCGGCTTCACACTTAAGCTTCGTCCTGATCATTGGTTAAACATAAAAGGGAGCACAGGAT

          ACCCAGCGGTCCCCCTCGAGGACGCTGACAACGCCTTATCTTCAACTCGGTTTCACGTCT
          CCTCAGCGGTCCCCCTCGAGGACGCTGACAACGCCTTATCTTCAACTCGGTTTCACGTCT
          CTAGAGCGGTGCCCCCTGTGGACGTAGACTAAATTTCACCTTCGATACGGTCCGTGGGAT
          GTCGTCCGATAATAGCTGGTGACTCAACTAGTGTATCAGGCGCGTAATGACCCCCTGTTG
          TTATCTTGGTCACTCCACATGGGGTTGTTCGCACGACAAACAGTATACAGAGCTTCACGA
          CTAGATTGACTAATTCCGATCGTTCAGAGAATCACACCGATCCGGCGTAGGGGTTTGTGA
          ATAACTCGACGATTCACCGCGACGTGGCCTTTGGGCCCGGACAAGCAAAGCTTGATGTTG
          CAAATTCGATTAATGAGGACCCTGTAACAGTCGGCGAGTTCTCCTACAGATGTCAAATGC

          CCTTTCCTGCAGGAACCTTTTGTCAGCACAAAGGAAAGTTTAAGTCGTCCACCCAGCAAA
          CCTTTCCTGCCGGAACCTTTTGTCAGCACAAAGGAAAGTTTAAGTCGTCCACCCGGCAAA
          CTTCAGCCGCAGGAGCCTGGTGGCAGGACAAAACGAAATCAAGTTCGTCCAAGAGGTAAC
          ACTCCTCGGCGGAGATCCTACAGCGGGGATCAGTCATATCTTCTGCGTGAATAAGGCGAT
          AATCCTTTGTGGTTCATTTGACGCCGACTGAGGTGCTGACCAATGCCTATGAGGGGCGTA
          AGTGTTAAGACGTTTAGACTCGATAAAACGTTGCTACGTCTATGCTGTCCACGGGTAGCC
          CGGCCCACATGATAACTAGGTTGCTGAGCATAGCTGCTTCCCCATTATCTGCAACTCCGG
          GGATCTGCCTGATTGCAACGTGGCAGAATCTAGCAGCTCTTCTTACAACTACGGTAACGA

          TACATGCGCGCGATAGATCACCTCCCCGCTTAGCAGAACGAATTAGCTATATCCAGTAGG
          TACATGCGCCCGATAGATCACCTCCCCGCTTAGCAGAACGAATTAGTTATATCCAGTAGG
          CACATATGCCTAGAAGCTCGGCCCTTCGCCCAGCAGAGCAAATAAGTTGCCTTAGGTGGG
          CCCATCTGTCCCACGGCAGCGATCGATAGTGAATCGAAGCAAAGTGCTGTTCTTGCTAAG
          TATGTTTGTCCTGCAGGTATAGCCCCCATCAGACGGAGTAGATACATGGTAGTTGGTACT
          AATGCACGGCCTACAGCTGAGCTACTCGCTGAACATAGCACGGCATTCGCGTCCCAGGGC
          GATTACTGACGGAGGGGTAACGGATACTCTCAGACGAGTACGCTCTTCACGTGTCGAATG
          TATGTTTAGCTTAGAGATTAGGAGCTTGCTTACTGCCCTATGGTCCCTGTGGATTAATTG

          GCTTCCTCTGCGTGTGACGGCCGGAAAGCGTTCTATCATAACTTAAGACGCACAGCCCCA
          GCTTCCTCTGCGTGTGAGGGCCGGAAAGCGTTCTATTATAACTTAAGACGCACAGCCCCA
          TCTTGATATGCGTGAGTGGTCGGGTAAGCGTTGTTCCCTCGCTTAAAACGCATGGCCAAA
          AATTCGGTTCTGCGAGGGGTCAGACAGCCACGCTTGTCTGTTCCGAAGTACTGCAACGGA
          GTTCAAACTCCCAGAGGAGATTAGCACCTACTGTTGCTCGTTATCTAGCTCACGGCCAAC
          CTCTGTTCTACTGGAGGAGTTCGCCGGTTATTGACGTCTATTAGCAAGCTTGTCATTCGG
          GCTCATGCCGCTTACAAAGACGTGCACAAACTGGAGGCCTTTGTTAAACATGTCATTGGG
          CTTTATGCTACGCGGGAGGCCCAACGCGTAGTGCCGAGCGATATTACGTCGAGTTCCCAG

          TGGAACTCATAAAGTTTCCCCATTCTAGGTGCGCACCAGGCTATCCCAGGGAGGCAGACC
          TGGCACTCATAAAGTTTCCCCAATCTAGGTGCGCACCAGGCTATCCCAGGGAGGCAGACC
          TGATGTTTATAATGTTTCTCCTCCCTGGAGTTTCCCCAGGACGATACAAGAGGGCCAACC
          TCGTCATCTCGCCATCTCTGCATCTCCCTGTCCCATTAGTACACGTAAACCGAGTTGGAC
          TAGGCCTTTTTCCGCTCTCAAAGCCTGAAGACCGACTGATTAAGAGTTGGTACGTCACGC
          CAAGTAGGGCATTCGAGCCAAAATGTAAGGACCAATCGTTGTCTGGAAAACAGGCCCATC
          TCAGCACTACTAGGTCCAGATAGAGCGGAGGGGCCTCAGGGTCCGAACTGTTCCTGAACC
          CGGGGGCCGGGAGGGGTGAAAGGACTCCTAGTGTATAACATGCAGACTAGTTCGATGACC

          TAGAACCAATGACGCTCCATTGCAGTGACGTTCACCTCAATCGGTCTGAACGAATTGGTG
          TAGAACCAATGACGCTCCATTGCAGTGACGTTCACCTCAATCGGTCTGAACGAATTGGTG
          CGGGACTAATGATCTCCCTTTGTAGCGCCGTTAACTTCACCCGGTCCTGGCGAATCGGTG
          TGGGTTAAATGACGATGCTCTCGGGCCCGGCTTGCTACGATAGATCCGAGCGGTATGATT
          CACGACAGGACATCCAAATTCGAAATCTTGGTGAAGAAAATCGTATGGGCCGCAGTGGAA
          GGAAGGAAGCGACCTAAACCGAGGGCGTAGGTTAGGGCGGTTGACTCTGATAATGTTACG
          GGGACGAGTTCAATCGACTCTGGTCCACTAGAGGGAATAGCTAGTTCGGGGCCAACCGGC
          GAAAACTTCTAAGGAGCCAATGCAGTATCAACGTCTGCCTGTGGGCCGGGTGCAAACGGG

          ACACGTTCGCATCAAGGGCTAGCATTACGGATAGCAGTGGCCTTGATTGTACGGAATTTC
          ACACGTTCGCATCAAGGGCTAGCATTATGGATAGCAGTGGCCTTGATTGTCCGGAATTTC
          GCGTGTTCGCCCGAAAAATCAGCACTTTCGCAAGTAGCGGTTTCAAACGATCGCAACGAC
          AAACCGTTGATTTAACTCCGGGATATTGGGGTTGCGGACTGATGGATCACTATGTCTAAA
          GGGTGGTTGAACTACATTATGGCTTTCGATACTGTAATGGTCCGGTTCGTGCGCGTACAA
          TAGCGGTCGCCGCCAGAGCGAATACTCATCGTGTTCAGATTTTGGTTTAGGGAGCTATAA
          ATGTACTAACAAGATGTCCGGTAAGGCATAGTGACAAAGGGTCCGCTATCCGAGCTACAC
          CGGCCGAAAGACTTGTTTCAGTGCGTACCCCCAGTGTTGATTCTCTCTCCTAAGCTGGGC

          AGTGTTTTTAGGCTTTAGAACTATCTGTTTATCGGAAGCTGGAACTTAGTTCCCAGGCTC
          AGTGCTTTTAGGCTCTAGAACTATCTGTTTATCGGAAGCTGGAACTTAGTTCTCAGGCTC
          AGTGCCTATCAGCCTAAGAACCTTTTCTCGATGGAAAATCTGGGCGAAGCTCATTTGTTT
          AACATTCCCTGGATCCCGTTACTTTTGTTTATAAATGGTATGAAACTGAGCTATATCCTA
          GACGTGCGTCCCCCACCGGTGATACTACCTGCCATCAGCTCAGGCCCGGCCCGCATCCGA
          AGCGTATGTGAGGCACGGGAATTTCTAATTGAATCGCCCTTGGGTGTATTTCATCTTTCA
          AGTCGCCGACAGCCTCCGGACGTTCGGATAGTCACAAGTCCGAGTGCCGATTGCAAGTCG
          GGTGACATCTAGGTAGTAATGCGGTCGTTCGATACAGTTTCCAGTTAAAGTCAGAGACAA

          CTACGAACCTTATTACTAGTGCTGTATGCCGCCATGTTGCCATATCCCGAAAAGGTTCTA
          CTACGAACCTTATAACTAGTGCTGTATGCCGCCATGTTGCCATATCCCGAAGAGGTCCTA
          GTACCAGCCAAGTTGCCAGTGCTACAAGTCGCTAAGGTGGCATATTTCAGGGAGAACCCA
          CCTCTGGAATAAGTAACTTGCCGAGCTGCTATCCTTTAGCCGCTACCTGAGGACGTCCTC
          TTAGACAAGCGGTCCTTAGAGAGCACTGTCAACAATGAGTCGAATTCCGACCGTTACAGT
          CACTTTTCGCTGACATCGATGTACGTACTTTCTGACGGAGCGTTAAACCGTCCGTGCCAG
          TCGCTAAAGCAGGCGAAAGTTCGTGACTCTATCGGAGACACGGGTATCATTTGATGGCTA
          TGGTCTGGGGACCCCCTGTCTCGATGTTTGCCTGCAGATCCAACTTACCCCCGTTACTGT

          ATGGTCCCTAGATCACTCATTGATAACGGGGAAAACCGCCTCTCTCAAACCCTGGATTGT
          ATGGTCCCCAGATCACTCATTGCTAACGGTGAAAATCGCCTCTTTCAAACCCTGAATTGT
          ATGCCACCGCGATTATTCCTTACTAACTTAATAAATCGTTCCGGACAAACATATTATCGG
          ATCATTTGTGGCTTAATCTCCTCATAGTAAGAGGGCCTTCGCAAGCAGGCGGTCAACTGT
          ATGTCTGGCGAATTTACCGCCGGACAATGGATACGTTTCTACTTACGCGTCTAGTAACCC
          GCGTCTATTGCGTTTTCTCTAGTAAGTTAAACCCGACTTCGTGTAGGACCCATGTATCGG
          CTGGTCAGTGGCCTCTATGCCGACGCATAACTAAGTTATTGCGGGCGTGCTTCTAATTGA
          TTCTTTAACAGATTATGGGGTAACGGATAGAATACATTGGCACTCAAAGGACATTAAAGA

          TTACTGCATGCACGATTTATGGCCAGGATCATTTCCGGCGGGTCTATAGCTGAAATAGTG
          TTACTGCATGCACGATTTATGGCCAGGATCATTTCCGGCGGGTCTATAGCTGAAATAGTG
          CTGTCACTCGCACGATTTATGACCCAGGTCATTTTCGACGAGGTCCGACGTGACCAAACG
          TCGGAGCCTCTACGAGTTTGCCCAAGGGACATACTTGACTATATGCAGTCAGCTCGCGTG
          AGGCGCCTCTAACAGCCATGCATTCAGGCTATTCCCAACAGTACGCATGTCGACTGTTAA
          CAGCGGCAGGTAAGACCATAGATCGCTAACGACAGTGTTGAAACGTGTTTTCAGCATACA
          TTAAAGCCCTCATGCTATCCCCCTCGCGATATCGTGGGATGTATGAACACCGCAATCCTA
          ACGAAGTCGTGATGGGCCAATATCCAAAATCTCTTCGATAACATACATGCAGGCCAGCTT

          GTGTGAGTGACCGCCAGGGACCATCAAATGAATAGTTATGTGTGCCGCAGAAAGCTGCAA
          GTGTGAGTGACCGCCAGGGACCAGCAAATGAATAGTTATGTGTGCCGCAGAAAGCTGCAA
          GTCTAATTCATCTCCAGGGTATGGCATATGGATGGTGTAGTGTGCAGTGGACAGCTTCCG
          GTCTGGATTAATACTACAAAAAAAGACGCAGTTCTCTGGACGGAGGACGTGGTGAGTTAT
          GTCCTGAAGATGTGCGTCAATTAGGGACTCCATTTAACTACATCGGTCGGCCTCCCTAAA
          GCCTTAATGACTCTATCGGGCAGGAGAGTAGATATCTTCTGATGGGGCGGACCCTTTTTG
          AGACCAATAGCTCCTCAGAGTCGGCGTCAAGGATGCTTATCGAACCATAGAGCCCTGACG
          CCTTCTTCAACGACACAAGCAAGGCCTCTAGGTTTTCACCGACGAGGAGGGAATTCTTAT

          TTTTAACCTGCCCGCTCCGCTCTCGTCTCAATGGGTATAGCTAAATCGGGATGGCTTGCC
          TTTTAATCTGCCCGCTCCTCTCTCGTCTCAATGGGTATAGCTAAATCGGGATGGCTTGCC
          TTTCTATCGGCTCGCCCCACATGTGTTCCAATGGTCATCGTTAAACTGGGGATGCCTATC
          CCTATTCGGCCTCGTAAGACACACCATGCCAGGGCTACAATAGTGTTAGATTCGTCCTTA
          CCCCGTCTAAATTGTATGGCAAAACATCAGGGTACCACCCCATAGCCACATTTCGTTTCG
          CCCCTATTGGTCGTTATTAATAGCCGGTTACCAGCACTTCGCCTATATTGCTCTCTCCCA
          CCTTGGCCGGAGCAATTCATAAACAGTTGCGGAACCACAAGGAACTCGCTTCCCTTTCCG
          CCCGATGCACGGCGGATAATGCACTCTTGGGTAACCGCTACATTCTCGTACGAAATTTCA

          GCGGAATGTAAAGCCACATGCCCAGCCTGTACTGAGACTTCATAGGGTCGCCACTCCGAC
          GCAGAATGTAAAGCCACATGCCCAGCCTGTACTGAGACTTCATAGGGTCGCCACTCCGAC
          ACAGATTGCATCGACAAATGCGGAGCCTGTCCTGAGATTTTGTCGGGTCAGAACGACGTC
          CCGGACGAAGATACCCTAAGGCGAGGCTAATCCATTACGATACTGTATCAGACCGGCGGC
          GTGGACACAGAAAGATTCATAAGAATCCTATGGATTACCAACTGCGCTCCGACCGAAATA
          TAGATCTGTGTTTGACTAAGGGTAGACTTCGCTGCTAGAAACATGGACAGATCTAGAGGC
          GGCGTTAACGCTAGGTCAGGGTTACAGCACCACGCACGTGTACACGTTTTACCTGAGGCC
          CATTCGAAAACTACGGCAGCCGCTGCGCACCCCGCGCATTTATTGGATCCGGTTAGCATT

          AAGGCCTGCAAACCACCCACACGTGCCGGCTGGTATGGCT
          AAGGCCTGCAAACCGCCCACACATGCCGGCTGATATGGCT
          ACGGATTGCCAGTGATATACACGAGCCAGGTGACATGACT
          ACAATCAGACTAAGGTTTGTATAAATAGGATCTTTTAGGT
          ACACTACGAAACCAGTTGGCATTAACAGCTCGTATCCGCC
          GCCAACTAACACCCGATGAGTCACCTTGGAGGTCACCGTC
          ACCGGATCGTGCTTGTCGCGGCACATTGAACGCCACAGAA
          TTGATTCAATACAGACAATAACGAACATTATTATACCGTT

