 8 1000
t1        TAAGTGTTATCTGTATGGGTCTTGATAAATACGTGTCTCTATGTAACGTTTCGGACCTCG
t2        TTAGAGCCATCCCGGCGAGTCATCACAAGTGCACATCTACTTTAAATGCCTTGGACTTGG
t3        CTAGCGACACATCAGGAGGTGGTAGGTATCGTGAGTCTATCCGCAATTCGCCGGGTGTGG
t4        CCGCTGGAGGCGGGGCCGGCGGCGGCCCTTGTATGTGTGTATGAATCTCTTTAAACCTCG
t5        TATTTGGAACTGCGGACATCAACGGACTACGGACGCCAATTTGGGCTACTCCACACCCGG
t6        TCCTTGGAACGTCGGCAGTTAACGGTCCACGGATCCCCATTTGAGGCACTACACACCCGG
t7        TTTAGAGCCGGTTTGAGTCGCTTGCCATACGCGCATTTACATCCGTTTCATTGCCTTCCA
t8        TTTAGAGCCGGTTTAAGCCCCTTGCCATACGCGCATTTTAATCCGTTGCATTGCCTTCCA

          GTAAAAATGTAGAGTAGACTCAGGAACTTGGTAATCTTCCATAGTTACCGTAGGCACCAA
          GACATGCTTTAGGCAAATCATTGCAGACCGGTACTTTTCTATAAGACTAGCGTGAAACAG
          GGGATGGCCCGTACACAGTAGGGGAGTCAGGCTTGCTACCAAACGCTTTGCCACAGATGG
          GGAATAAACCCTAATATACCACAGCGATTTGAGCTCTCTGATTCACGTAGCGAATAGCTG
          GCGAGCGTTGGGAGTGGACCGGTAAGCCTGTTACCGACTAGCAAGCTCCGCCAGGGGCCG
          GCGAGCGTTGATTGTGAAATGGCGTATCTGCAGCCCATTAACATGTTCCGCCGTAAGCTG
          GAGATTCATCCAGAGGTTTCATCGGACACGCAGCCAGCTAATCCTTCCTTAGCCCTACTC
          GAGACTCATCCAGAGGTTTCATCGGACACAAAGCCAGCTAATCCTTCCTTAGCCCTACTC

          CAAAGGCACTACTACACCCAGCGCACACCAGCACACCATTATGTCGTATTTAGCATCAAC
          TAAACATAGCAACGGATGCGCTGTGTGTTCGCAACGCATCATGCCGCTTCTATTAGTTTA
          CATATACGGCTAGCTATGTGGCGCTCGCCCGTCACGGATTGCGTTGTATTCACTAGCTGA
          CTTATAAGGATAAATCTGCATAGCACACTCGAGAAGCATCTTGCGGTGCCTTTCTGATGA
          GGGTCGACAATCTCTTCACGGCCTAATCGAAAATTCCCTCTGACAAAGATTGCCCGGTAA
          CGGAAAACAATTTGTTCGTCGCGTAACCCGAATCTGCATCTCACAAGGATCACCCCCCAG
          CAAGTTCAGTTGCGGTTGCGGTGACCGCGTAATTGCCGTTAGTATGAAGCAATTAAGTAC
          CAGGTTCAGTTGCGGTTGCGGTGACCGCGTAATTACCGTTACTATGAAGCATTTAAGTAC

          ACTGCTCAGCATTGTTAGAAATATCGCAGCATGATCGAACGGATATGTCTCGTGGCGCCT
          ATTCCTCATGATTATTAGACAAATTATAGAGCTGGCGAACGGATAACTAGAGCGACTTCC
          CCTCTTTATCATTATCCGGCACATCGTAGTATGGGCAGGAGGATGTCCCCGGTGCTGTCC
          CTTGCCACATAATGAAATCTAAATTCCGATATGAACCGGAGGCTGATCTCGATGGACAGC
          ATGTCTGCTTCTATCAATGAAATCGCTGACCTAAGTATTCGGATAATACCTTTACCCTCC
          GTACTCCCGTTTATCATCGGAGGCGCTGACCCTAGTAATAGGATGATATCGGCATCCCCC
          GTACGTACCAAATGTGAAGCATAAAAGCCCCTGAGAGCGTAGCCGGAGACAGGAGGTTCG
          GTACGCACCAAATGTGAAGTATAAAAGCCCCTGAGAGCGTAGTCGAAGATAGGAGCATCG

          CTCATACGGTACACATATGTGATTACCGAAATGGCCGTTTGTTATGGCGTGTCCGGAAAA
          GATCTCTAGCCATACCAGGAGATCATCGGAATGTCGGTTCGATTTAGAGTACCCTGGTGC
          GTCTAGAAGCTCTCATGGAAGGTCGATGTCCTGAAGGCTTGATTCGGGGACCGAAGACAC
          GAAGTGTTGCCTTCCCGATGGGGCGACAAGCAGCGGATGTGTCCAAGGAGCTGCAAGGCA
          AGATAGTTACGTCAACGAGGGGGGCAGACACTACGGTGTGACCCAGGAGCCGCGTCAGAG
          ACTCAGTTCCGTTCATAAGCTGGGAATGGTAAGTGGATCAAATCAGCAGCTGTGGCAAAG
          TGATACTCGCTTACGATGATGATATAAGAATCGAGGGTGTAAGCAGAGGACGCAGGGGAA
          TGATAGTTGCTTACAATGATGACGTAAGAATCGAGGATGTAAGCAGAGGACTCAGGGGAA

          CTTGCACTGCGCTCCATGAAGTAGATGGAGCCGCACACTGACTTATAAAGGTTTTTCTCC
          GATTCGCAGACACTTTACGATGCAGTGGGATGGCATATCCACATGTTAAAAATTTCCTTC
          CCTACGCCAGCCCTCTTAGAGTGACCTGAACGGCAGAACCTTACGCATAGGTTCTGGTAT
          TCTATTCTGAATAATAAGGATCGGTTTACATCACAGGACCTAAAATGGAAGGTCTTTTCT
          TGTCCTTAGAGAATTTGACCACGCCGGGAATAAATCCAACCTCACGATTAAATTTGACCT
          TCTTATCAAAGAGCTTGCTTACGTCGAGAATGAATTCAATCACACCACAGGATCACATGT
          CGATGTTAAATGACTCGGGCGTAGTCGAAACCCTTGAATTCGCTGTATAGTTCGGATTTT
          CGATGTTAAATGACTCGGGCATAGTCGTAACCCTTCAATTCGCTGTATGGTTCGGATTTT

          CAGATGGACTAGGTGTTATCGGGGCCCTACCTCAAAAACCTGGGTGTGAAAACCAAGCAC
          CTGACGGACACCGGGAAGCTGTAGTGCCATCTAAGAGACAACCCCGAGAAAACCAAGCAT
          TGAGAGGTCGTGACGGGTCAGAGAACGCATATATGGGATTCTAATGGATCAATTACGAAA
          CATTCGGATCCAGTGACGATCAGACTCTTTTTACAGAGTAGCCGCAAGAGTGCCAGGTTC
          AAGCACAGTTTGAAAACGTTCGGGACTGCGCTAACGCATAACAGCGTGAGCCGTGTTGAC
          AAGCCCAACTTGAGAATGTTGGGGACGGTTACGAATGACAACAACTTGGGCCGTGTCGAC
          TAATTGATACTAACGCACCTCGAGCTAGTATCGTGATTCACCGCCGTGTGGATTAGTCAT
          TAATTGATATTGACGCACCCCGAGCTAGTATCGTGATCCATCGCCGTGTCGATTGGTAAT

          GCTTTTCACGGACGCACCGGTCCCAAACTCTTACTTCCGCGCGTCTTCTTACGAGCGGAC
          GCTCTTAATGGATACCGGGCTCACAGAAGCTTGCTTCCGCGTGAACTCTCTCGAGCAAAC
          ATCGTTCACCGATGCTCGGAGCGCGGAATCTCATTTTTGCAGCTCTTCCTTGGAATGACA
          GTTTCTAATGGACGACTTCGCCCCCAAGACTTTATCATACGCGTTCACCTAATAAAGTTA
          TCTTTTAGAGGATGTCTGAATCTTTGTGTCCCGCGGCTCTCTATACATCCACCAGTTGAA
          CTTTTTAGTGAATATCTTGTTATTTGCGCCCGAAACCTCCCTATCTCCCCACGCGTTGAA
          GCGCGTCGCGTCTACACGGGATCATTGGTATGGTGGTCGCCCGTGACCCTGTTAGCTAAC
          GCGCGCCGCATCCACACGGGATTATTGGTATGGTGGCCGCCCGTGAACCTGTTAGCTAAC

          CACGTAAAAGTATCACCCTATACAGGGAGTAATAAGACTCATCTACCTCGCGCTTGCCAA
          AAGACAGGATCCTCAACCCGCAGAGAAGATACAAATATTGCTTCACCAGACACTCGTTAT
          AACGAAACAAAGTTGATCAGTATAGGAGATTATAATCCTGCTCCTCCACGGGCACCCAAC
          AATATGAAGGTATCGATTCGTAGAGGATTGCGATGTACCCAGTGGTCCTCAGTTCCACAC
          AACACAGAGGCACTTTCTCGTGTGAGGCACTGGGATTTTGCGATTTCTTAATACAGCATC
          AGCTTAGAAACGTCACCTCGTTTGAGAAGCTGGGATTCTACTATTCTACGCTATTAATCC
          GGAGCAAATAAATTAATGTTCCCCATCGGCCGCGATACTCATATGCCAAACGTCCGTAAA
          GGAGCAAATAAACTATTGTTCCCCATCGGCCACGATGTCCATATGGCAAACGTCCGTCAA

          GAACGTTGCTTAGGTGCTGCATGGGGCCGTTTCGGGGCTGTGACGGCATCAGTGGCGGGC
          GCAAACTACCGCCCTTTCGTTAATGCTTGTACAGCATGTGCGGCAACCGGAGTAGTAAAC
          TAAGAACACCGAATTGTCGTACAGGTTAGTTTGACGTATGTAGCGAATTAAGTGGCTGGC
          GTTGGCTTCCAATGTTCGTAGCGAGCTCCTCTGGTATAGGCGACAGTCAAAATGCCAGGC
          TCAAGCAACTATCTCCCTTACTATTCGTCCGCGACAAATCCTATGCCAAGTGAATCAGAT
          CGAGCCTACACTCGCTTTTCCTAATCGTGAGCGGGAAAGCCTACACGACGTGTATCAGTT
          GAAGACCACCGACGAGCTCTGCATTTCCTTGAGGTGGAGGTGCTGGACCGAGTACAGGTT
          GAAGTTCACCGACGAGGTCTGCATTTCCTTGAAGTGGACGTGCTGGACTGAGTACAGGCT

          TGGATGCTCTCCCATCTCGCTCATTGTGCTTGCGGAAGACGACCAAGGCCCAGGCTTGAA
          TGAAAACCCTATCGGCTTGAACTGGATCCTAGGGGTAGCTGACTACAGCCTTGGACCGTA
          TTAAAACGCTTTCATCTAGATCATGGCGTCTGTGGGAGTAGATTACAGCATAAGCTCTGG
          TTTACATCCCGTAGTTAAAGCTATAGTTCCGGCGGGAGCATAACCTGGCTTTATTGTAGT
          TTCCACACCGGAGATAGCGGTCCTCGTTCGAGCAAGCTTAGGCTAAGGTGCCGGCCTCCA
          TTCCACCTTGGCGATAACAGTTCTCGCTTGAGCAGGCCTAGACAAAGATTCTAGCCCCCC
          TAGAGACCCCGTGGTCACGGTCTTATGGTGTTTTAAAATAATCTCAGGTCCAAATACGGG
          TAGAGACCCCGTGGATGCGGTCTTATGGTGTTTTAAAATTATCTCAGGTCCAAGTGCGGG

          TAGTCATGTTATCGGCCTATTTCCTGAGCCGTCTTGTACAATTCCATGCTTCCTTGGTAT
          CCAATGCGCAACCCGGCCGCCTACTACCCCACCTTGTACACTTCGAAGCTCTTAGGGTGC
          CAGATATACTTCCAGGCTACCTAGAGAGCGGTCTATTCCTAATTTGACCATTTGGGGTGA
          TAAGAACCCCGGGGAGATGCCAAGTGGGCCTTCTGATAAATCTTCTAGCCAATAGTTCAG
          TGCGAGCCTTGTCTGCACGCAGAAGGTGACCTAGTAAGAAACTTTAAGCCCTAGCATTGC
          TGGGAGCCTCGTCAGCACGTACAAGGCGACCTGGGAAAGAGTTTCAATCGTCAGGAGAGT
          CAGCTTTACTGTTCGGACAACTCAGCCCTAGTCTAGTGAAACGATGCGATGCTGTCGGTC
          CAGCTTTACTGTTCGGACAACCCAGCCCTAGTCTAGTAAAAAGATGCGATGCTGTCGGTC

          AGTAGCTAACCTTATGAACCGGTGCCCTCTCGGCCGTTGCGCGTACATAATACCTAACAA
          GGTATCCAGCCTCCTCAACATGCACTTTCGTGGCCCACGTGATTGTGCAAAAACCGACAT
          GGCATCTAGCCTAATAAGATCGCAATATTACGGCTCATATGGGCGGATGCCCACTTCCTT
          CAAGCTCAGCTTTATAGGACCCTGGTCTAATGGCATATACGAGGGAGTACCGGTCTCTTG
          CATCCCGAACTAGATAAGTCCGGTGTGCGACAGGTAATACGCTGTTGAGGAGATATGAGG
          TGTACCCAACTGGATAAGTGTGTCGTACGGTAGGTGAGATAATGTCACGGAGACCCATGA
          TGTTGCGGGCAACCGTTTGCGGTGGTTCGCGAGAATTTACGGGGCACGAGAGGTGGGATG
          TGTTGCGGGCAACCACTTACGGTGGTTCACGAGAGTTTACGGGGCACGAGAGGTGGGATG

          ACCCCGCAGAGAAGTTCCCCCTTATCGCGTTTGGTTAGCCTTGGTAAAAGAGCCTTTGTC
          ACAGCTTAGACTAGGCCGCATGAATCGCGTGTGGGTCGTCTTGGCAGAAAGGTTCTACAC
          ATAGCTCAAGCACATCCCTATGACCCAAGTGCAGGCGGCCGCGGTGGACGGGTCCCATAC
          AAGGCCGGCCCTTGGTCATCAGCTTTTTGCGCTAGTCCCCTTGATAGGCGTGTACTCATT
          GGATCCCAGAAAGACTGAGGTCTTTTAGGTGCGGACGGTGCGACTAGGCGAGCTCCAGAC
          GGATCCCCGAAAGTCCCTGGGCTCGTGCGTGCGGACGGTATAAATAGACGAGCTACAGAG
          CGACACCTAACGCCCGCTGCCCATCCGTTACTAGCTAGTCGCAATTGACGGTACACATGC
          TGACCCCTAACACCTGCTGTCCATCCGATACTAGCAAGTCGCCATTGACGGTACACATGC

          GAATCACATCCCGGTTACAACTCGAACTTGATTTCGACAAGTAGCTAGAAGGACGCGAGG
          GATTTTGCCCCCAAATGTAGCTTGAAGCAGGCCGTGACGGATCGCTGCTAAGACCCGAGG
          GATTCCGACCCCGTCGCCGTGTCGTAGTGGATTATCATAGGTCAGTTAATGAACCCTACG
          ATCCCAAAGTCTACCCCTTATCACGAACCGGTTGTTAAAGGCCGACTAAATGGCTACACA
          GTGCATTTTTTCCGTAAAGATTACACTACTGCCGATGTAACCCTTTGGCTGGACTCTACA
          GTGCCATTTCTCGTCGCTGATTAGGTATCAGCTGCTGTAACCCTCCGGACACACTGTAAA
          CCGAGATCATCTGCTATTGCATTAGAGCAGACAATCTAAGCGTGTCTAGCAACACCGACT
          CCGACATCATCTGCTGTTGCATTAGAGCAGACAATCCAAGCGTGTCTAGCAATACCGACT

          TCTCCTTTGTCAAGAGGTCAGTGATAACATGGTGAAGAGTAATTCAGCTCGTCCGGTTCG
          CACTTATAGATAGGAATTCTATACCGCCGTGGCGTACGGCTGTTAAGTCAGGATGACATG
          TCTCCACAGAGAGAAAAGTGAGACTGCAGTAGAGTAGAGGTGCTAGGCCTGATCAGCGAC
          CCACAAGAATTGGGAAAGTTGATTCGGTACAGTGAATCACTGTTAACGCTATGGAGTATG
          GCTAGTTACGACCGTGGAGGGAATGATGCTCGAAAGTCGCATCGTGAAACGCGATGCAGT
          ACTAGCTACGACCGAGAAGGGTATAGCGCTCAAATACCGCATTGAGTCACGTGTGGTAGT
          CCCGATCCCACCGGTTATCAAAGGGTGGGCAGTGAACCTTGCTCTAGTTGAAAGGTCATT
          CCCGATCCCACCGGCTATCAAAGGGTGGGCGGTGAACCTTGCTCGAGTAGAGAGGTCATT

          TCCGTGTAAAGGGCTGCAGCGAAGTTTAAGCAACTATCGG
          TCCGCCCCACTAAGTGGTGAGGACCTTTTAAGACCACCGG
          TGGGTACAAGGGGCCGCAATGGAGTTTATCTTAGGCTCGG
          TCCATGCAGAGCACCACAGAAGAAACCAGAGTAGAGTCAG
          TTCACAGACAGAGGTCTAGAAAAGATTTCGCGAAAGCGCG
          TTTATAGGCAAGGGTCTAGAAAAATTTAAGCGCAGCCGCG
          CCTCGACAGAGTCGTGTTAGTGGGTCTCCTGCAATCTGTA
          CCTCGACAGAGTCCTCTTAGTGGGTCTCTTGTAATCGGTA

