 8 1000
t1        GTCGGGCGAAACTTCCCCTTTTAATTGGTCAACGAAGTCCACGGTTCTCAGTAGTTTGTC
t2        GTCGGGTGTAGCTCACCCTCCTAATTGAACAATATAGCACCTAGCACTCAATTCTCCGTC
t3        GTCGCGCAGAGCTTGCCCTCCCAATTGATCAACGAAGCGCAGATTCCCCTACAGGTCGCC
t4        ATGGAGCACAGGTTAGCGCTCCAACCCATCAACAGGGTGCGTAGTTCCCAGTAACTTGCC
t5        GCTCAGGGACTCGCAGAAATATAATCAATCGATAATGTGCGCGACTCCTAACGACCTGCT
t6        GGCGACGGCCACCCGAAACAGAAATCAATAGGGGATGCATGTAATACCGAATGGCTCGCC
t7        ACAGCGGAGGTCTAAAAAACTTAGGTTAACCACAATATCTCCGCCGACCGAAGTTTTGCT
t8        GCTAGAGGCTCTATCGCATTATAGCAAATATGTACCACCCGCGGTGACTGAGTTTTCGCT

          GATAGCGCGGTAAAACCGCTCCGTATACTAGCGTCTGTGAATCCGGCAGATGAGTGACGC
          GATAGAGCGGTTAAACCACCCCGAATATTAGCGTTAGTGGATACGGCACGAGAGTGATGC
          AATTAAACGGTGCAACCACTCTGCACATGAGCGTTACTGGCTCCGGTAAGCGCCTGGCGC
          GAATGGCCGGTTAAACCTTTTCTCGCACGGACGCGACTAGCGACGGTCGGCGCGTGCCGC
          TCTAAGGCAGTGAAATCCCTCCGCATACGAACGCTACCAGGCAAGGTAGAAGATCGTAGT
          TCCAGGATGGTGGCACCTTCTTGCATGCGAGCCCTAGTAGGCACAGCAGATGGGAACTGT
          TTCACGTCGCCTTGTAGCTTACGGATCCAAGCGGGCTTGTCGGTTATGTAAGTTCGGTGG
          GTGGAGGTGGTTGGGCGGCTTGGGGACCACCTATCTTGGGAGGCTCGGATATACCGATGC

          ACTTCTTGGTCACGTGCGCCGACCACAAAGTCAGATTAAGCTAACCATAGCTGTGTGACC
          ATTCCTTGGTCACGTTAGCTAATCACAAATCATAACTAAACGAACCATGCCTGTGTGACA
          ACTCCTTGTTCCCGTGAGTTAACCTCGAACCCAACCCAAATTAGTCCTAATTGTCTAACC
          ACGCCTCATTAATGACCGCCAATCACGTCTCCAGATCATACTAACGGCGGCCTTCTGACC
          GTTCCTCGTCCCCAAACATCGATTTCGACCCCACATTACAATAACTATCGCTCTACGAAT
          GTTCTAGGACCACAAACGCAGATTACGAATCCTCGTTATACGACTCATCGCTCTATGGGT
          TTGCCATAGCTCTGATCCCCGCGTATGGACACTCATTTAATCCGACGTCTAGTGGGATCT
          CTGTCGAAAATCTGCCATCTAGGAGTAAATACACTCCACATACTACGCCCGGCAGGGTTT

          AGCACTAATCGTCTAGGTTTGCTTTAGACAATTCTTTCTGATCCAGTAAACTTGTTCGTT
          AGTGATAATCGTTATGGTGTGCCTCTGACAATTCATCCTGACCCCATATTCTCATTCGTC
          AGGATTAATTTGCAAGGTTTACCTTTGACTATTTATTCCGGCCCAATGTCCCCATCTGTA
          AAGACCAATCGTCGAAGTTCGCCTTTGACCACTCACTCCAACCTATTACCCCCATTAGTT
          AGGACTACTTGCGAAAGTCTATCGCTGGACAGTCAGGATGTCTCAATGCACCCATTTTAA
          GGGTTCATTCACACGAGTTTGTCATTGGACGGTGACGTTAATCCGATGCCCCCACTAACA
          TCAGAAACAGTAATCAGTATCTGACAGCCGGGTTAGGTAAAATTGGCGGTTGTAGCCATA
          AGTTAAATCGCTGTCTATCCCCTGTCGCTTACTAGCGATGCAACGATAGTTGTATACGCT

          CATGGAGTATGAAACTGTGGACATGGAGTCAGTCACACGGTATTGCCTAATCGATCAAGT
          CATGAAGTAATTAACAGTGAAAACGGAGTGCGTCACATAGTACCGCCTAGAACATCAAGA
          CGTGAGGTACGTATCAGTGAGAACACAGCGAGTCATACAGTATCGCCTTGAGGAGCAAGT
          TGTGAGGCATACAAAAGTTAAACCGGAGGGAGCAATATAATTCCTTTTAAGTTGTGCGAC
          CATAATGCAGATACTGCCATCAGCAGAGAGAGCAATGTAGTTTACTCAGAGCAGCCTCGT
          TATGTTGTTGCCATAGGTCAAGGCGGAATGAGCAATACAGTCTCTTTTGAGCGTCATTGC
          AGTAACAGACACAGCAAAACATGCTTACCAGAAAGTAAAGGCTCACCTGAACCAACTTGA
          GATTACTAGTCCAGTTACGCAGAAACGCCAGGTACTAGAGCTGGATTCGTATTGACATGA

          GTACACATATGCTACAGGTGAAATCTTCCAAAGTTTGACACCATCCCGCGGCTTTTGGAT
          GTGCAAATACAGCAGACCCCAGACCTCTGATAGTTTTATATGCTCACGCGGCAACTGGAT
          TTTCATATACGGTACCCCCGGTACCTGCAAAAGCTTCACACGCTTACGTGGTCATTGGAT
          CTTCATGACCGCTGATCTAGGGATCCACGCAAGCTCTACGCATTTGTGTGGCGCTTGGAC
          GCATATATGCCCTGTCGCGGGACCTGCTGTGCACCGAAAGTACACGTCTACCTCGCAAGC
          ATTCATCCGTATTATGACTGGAACGTCCGTGTTGCTCAAACACGTGCGTACCACTTTAAT
          CCCACGTCGAATAATAACGATCGCTGTTATACTTATCCAACTCTCGCGAGGTGTGACGTT
          CCCCGGTTGTCCTTCTGTCGGCGCCGTTATGCTGCTTCTGTTTCAACGCCCTTTCTGGAT

          GTGGGACTCTCTTGTAACAAGTTCTGCAGTTGCTCACTAGAACCTTTGTGCCCGTCGCGG
          GTGGGACTCTTTTGTAATCAATTTCCCAGTTGTTCACAGGAATTCTTGTGCTCGTTGGGG
          GTCGGCATTCCGTGTAACAAGACTTTCGGATGTTCCCAAGAATCTTTGTGCTCGTCTGAA
          GTGGGCCACATATGCCATAGACCCTTCAATTGCCCAGAAGAAAATTCGCGGTTGTATGCG
          TTCGACCCTATGTCAAACTTTCCTCCCATTGAATTACGGAAATTCATGTTTGTACCATGG
          GCTAGTCCTGCGTGAGGCCATCTCGCCAGAGAACCATAGGACTCTTTGTCTGTGTCGTGA
          GAATGACCTAAAGGAGGCGCATTTTAACGCTCAAGTTCTACGCTCTTCTTGGAATTCAAG
          GAAGGGCTTGAAAACAATAAACCACATTATCCTAGCTGGAAGTTCCTCCTAGCGTCATAT

          CGATCCTACGGGTGCCAGCCAACCACCCGCCGCGCATCAGGCGGAGATTGAACGAACAGA
          TAATTACTCGGGTGCCAGTTAACAGCACGTCGCTTAACGGGCTGAGATTAATCAACCAGC
          TAAATCCCAGGGCGTCAGATGTAATCACGTCGCGCAATGGGCTGAGATTAAGAAACCAGG
          CAACCCCCTGAAAGCCGGCTGAAACGACAACGCTCGGTGGGAACAGATCAAACAGACGGA
          TAATTCCTTGGGAGCACAACGACAAACGGGTCCCCGACAGCGGACGGCTAAAGAGCTAGT
          TAAATTTGTGGGTGTAGACTGATACCTCGTCCCTTGGAGAAGTGTGACTAGAGAGTATGT
          CAATTCCGCTCCTATTGCGCCGATTTATTTCACCTGCGCCGTAAAGTTTATGACTATAGA
          TGAGCTCTAACTTAGTGCGCGCTTTGACGGTGAAACAGCGGAAGAGTCTGGGCGGGAAGG

          TCTCGGAAGCAGTACGATACTGTGACTCACGTGCTGCTTGATAATGCGATGGTTGGGGCA
          CCCTAGAAGTAGCGCAGTATTGTCACTCACGTACTGCATGATAGTAGTATGGTTGAGGAT
          TCTCAGCAGTACCGAGGTACCGTCGCTTCCGTGCGGCATAACAGTAGAATGGCTGAGGCG
          TTCCATACGTAGCCCTGCGTCGCCACCTCAGTATTGTATAACAAGGGAATGATCCGGATA
          AGCTGGACGTTGCGCCGTATCATAACTATAACCTCACTCGTTTTAAGAACGGGTGGGGGC
          CGCCGGAAGTTAGAACATACATCAAGCTTAATATTACACAACGGTAGTACGGTTGGAAGC
          ACTCGGGCGATACGGGCAGGAATGCCCTCGCGATCGAACCTGGTTGGACTAGTTTGTGAG
          TAGAGGGTGATATTGCTCGTAATGCTCCGCGAAAAGCTATCGAGGCGATTAGATAGCTAG

          CCGAACCTTATATCTTGTACTGCTAGTCCTTTAACCTCCTATGCATGATTCTGACATCAA
          CCCAACCTAATATCTCGCACAACAAGTCCACTGTACTCCTAAGCATGATTCTGATGTAAA
          CCCAGCCTTCTACTTCGGGCAGCCAGTCAGTTATCCCCCTATGACTGACCGCGAGATGGA
          TTTAGTCTGCGGTCTTGCCTCGCGAGTCTTTCCAATTCCCACGCGTGCCTCGGGCGCGAA
          ACAGACACACGGATTTGGCAAGCGAGTGGTTCACCTTTGTATACCTGCTCCCTGTGCGAA
          CAGAACCCGCCGATTTGTGCAGTGAACGGCCCAGTCTCACCCTTATAGCCCCTATGCGAA
          TCTCACGTGTATACTACCCTCGCGTGCGCATTAGTAGCGCTAGTTTAGTCTTCGTACCTA
          TCCCGTTGGCAGCATACGTCGCGGGACGTACCAGTCGTTCCCACGGACTCGTCCGGCATA

          TAACGACTACGCATGAAAGCGTCGCCAGATATTCCGGCTAAGGGCATGTGGTCCTGACCC
          TACCGACGGCGCATGCAAGTGTCACCAGATATTCCAGTTAAGGGCATTCGGCCCTGAGTT
          TGCCGATAACGTACAAAAATGTCAGCAGCTGCACTAGCCATCGGCATTCAGTCCTGAATT
          CACCGACGCCAAAGGAAAATATTGCCAGACCTTCCGGCTGAAGTTATTACGTCCAAAGCC
          TCCAGATGTGCAGTAATGGTGTCTCGAGGCATAGCAGTCAAGGGCATTGAGCTCTTGATG
          TAACAAGACACAATGACTGTGCCGCAAGGTACCGTAGTCAGGGTCACTAAGCTCCGGATG
          CAAATTGGCGCGATGGAACCGAACTCTGTCCACCAAATTTTGGAAAGGCCTTGTTGCTTG
          TATACGATCTGGTTGGGGCCAACATCCATTACAAGCTTTGTCGAGTGCGAGCAACGCTTA

          GGGTTCTTGTGAAAGTTGAGCTGGACCTTTATGTGTCTCGGAGCATTCTTACGCTTATGC
          GGGTATCTGGAAAAGCTGAGCTGGACTCTTTTACGTGCTACAGCATTCATTCCTTTAATG
          GGAAGGCTGTTAATGATGAGTTGGATTCTTGTATGTACCGCGGTATCCTCGTCTTAAGTC
          GATGATCAGCAAAAGGCGGGTCGGATCCTTCAATGCATCACGGAATTTCCCGCTCGAGCT
          AAGTACTCGTGAAAGACGAGTCTATTCCTACCTAGTCTTACGTAGTGTACCACCCTGGTC
          AAGGACGCGAGGGAGACGGGGTGACTCTCTTAGGGTCCCGCACGGTAACCTGCCCTGGAT
          CATCGAAATCAAGCCAGACATTGTTCGTTTCTGAGTGACATAGATCTCGACAGACATATC
          AATCGCCACCAAAGGAATGGTAGCCGATCTCCTATAGTCGCAGGGCTCAACAGCCGAAGC

          GCTCTTTTGAAAGGTCCCCGTGTTAGAATTCGGCACCATCACTGACTACAGATCATCGAG
          GTTCTATTGGAAGGTTTCCACGTTAGAATTCGGCACCACTACTCGTTACAGATTATCCAC
          CCCATATATAAGGATCCTTGTGCACGATCTTGGTACCACTCATAATCACTGATTATGCAT
          ATGCACTCAAGAGGTTTCAGTGTTAGACCCTGGCATCGGTACTAACTACAGATTGCCCAT
          GATAGTCATAATGCTCTCTTGGCAAGATCCCGATATTGCTGTTAGACGGATTCCATATGA
          GAGGGTTTAATTGTCTTCTAAGCCAGCCTTCGGTCTTGGCATGAATCGTAGTTCACACGA
          GCAGGCATGCCTGATTTGGTAGGTAACCTTCGAGGCGTCGCCTGACTGTATCTCTCGTAA
          CGGAGACCATTTGAACTAGTAGGTGCAGGCCGGAAAGCCATCTGACAACCGTTCTTTCGA

          TGCAGACTATCTATTTCCAGATCGAGATATACCAGTCTGTCTAGGTACAGAATATATTAT
          TCCCTCCTGTCTGTCTACAAATTGAGACATATCAGTCTACTTAGGTGAAGTATATATTGC
          TGCAGCCCATACCTTCATAAGTCCAGAAATACTAGTTTGCCTAGCGAAAAAATATATAGT
          CTCAGCCTATTACTTGAGGATAGGGGATGAAACCGTTCGCAACGGTAAAACGCGTATAGC
          CGTACCACCCCTCTTTAAATACTCAGACGTAACCGCTGGTCAGAGCATGGCAGATGTAGC
          TACAAATCGCTCCCACACCTACAACGATAGAACGAACAGCTTGGGCGTGACATATACAGC
          ATATACTTGGCCTCCTCTCGTCCTAAAAATGGGGATCTGACATCATTGGAATTGCGCAAA
          GCCTAACAATCCTGATTTTATAGCACACACGGGCATGTGTAACGGCAAGAACTGTGCTTG

          GCGTACCGGCCTTCACTTGAATCAAGTGTCTTTTGTGAGTTACGGGAACCCATACTCCGG
          GCACACCGGCCTTCACTTCCATTACGTGTCCTCTGTGAAATAAGGTAACCATCGCTCCGG
          GTGTACCAACCTCCATATCCCCTAAACGTTCTCTGTAAATTATAAGGATCGCAGCATCGG
          GTGCGTTGGCATCGACTCGTTACAATCGTCCCTCGTCGATTGAGGTGATCCGAGCTCGGG
          GTGTAATGGCTCCCAGAGGAATCAGAGATACGCTGTGGACCGAGGGGTTCCATGCTGTAA
          GTGTACAAGGCCTCTGCGGAATTGAAAACTCGGTGTAGACTGGTGAGCTCTATGTTTTAG
          GATTGCAGGCAGAGTGCACTGCCAAGCGCAAGGTGGGGATTTAACCATTACAGGGCAAAG
          ACTCACTGGTGACCTGCGCGCCTAAATTTGTGCTGTGGCATGGTACATTAATTCCATCTA

          CATAGCCCCCTAGATTGGGACTCACAGGAGCAATTTCCACGTCAACCTAACTGGAGACTC
          TAACACCCCCTGGGTTGGAACTCACGGGACCAATTTCTACATCGACGTACCTGGAGCTGC
          CCTAGAGGCCCTGATCGGAACCGAAGGAATCAGTCCCTAGATCAGAATAACTGTTGCTGC
          TGAATGACTCTAAACCCGAGCCGAGGAGGGTACCATTATCGCCGCTCCAACCGCGGTAGC
          TAGCAAGTTCTCAATTAGGGCTTAAGAGGGCGATACCCTCGTAGATCTAATTGTTAGTGC
          TCGAAAGTTATCAATGGGGCTCTGAGAGGCCGCTGCCCTTGTATTCCCAATTACTGTTGC
          TGCCCTGAAACGAATTATAACCTGCGAGCGCTACCTTTTTCGCATTTGGTCTTTTTTTCT
          TTATCTACCGCGAGTAAAGGCTACAGAAATCGTCCCCCTCATTGCTTGCTCTATTAATAC

          TCGTGAAACTATCGAAAAGATGATCGATCCTCTGTTAATG
          TCGCAAGGCCGACGAGAGGATGGTTGATCCATTGTTAACA
          TCGCAAGGCTGACAAGAGGAGGAACGATCATCCGTTTATG
          TCGCAAGACTAATGGGGAGATGATAAAATCATTGCTAATG
          GCGCATGACAAGCGAGGGGATGATGAATCATTTCATTACA
          GCGCAAGTTCAGTGAGGACGTGATAACTTGTTATATTTCA
          GTGCTTAGGGAATCCCCAGGCTATCTATTCCGCCCCAATC
          TCGCACCCGGAGAAACAGCGTGAATTGATTTTCCCCGACC

