 8 1000
t1        ATGGCCCCCCATGAGTCTCCTGGGGGTCAAGCCATCAAAGAATTGGGCTCACTCCAGGGG
t2        ATACCTCCCTGTGTTCGACTCATTGAGCTTAACCCCGCGGGGTCACCTTAGCCCTATGAG
t3        GCGTTCTGACTAGGTTTTCTTAGGCGACAAGGCACCTAGCCGCTATCCAGAATTTTTGGT
t4        ATGCACCGCGAGCTTTCTCCCGGATAATACGTCACTACGGACTTATCTCGGTTCCCAGAG
t5        GAAGGCCTTTGCTCTTACTGGCAGGATCATCCTTTCCTGGAATTATCCTTGAAGACCAGA
t6        GGGGATATTTGACCGTGTCCTGAGAAGCGGCATTTGCCGAAGCTTCATCGGTAGGTCGGC
t7        AGTCCTCAAAAGTAACGCTTCTAGACGAGAAGTCCTCCCCACTCCTCCGGGACTTGTGTA
t8        CGTTTTTTGAATATGCGTGCCTAAATTCGAGGCCTACTTCGGTCTTTTGGGTCTACCACA

          TTCTTGAATTAGTTCGGCTGTAGAAGTGATGGGATCGATGTCGATACGTTGCACAGCGGC
          ACGCCGTCGCTACTTTAATAGCACAGCATAGGCGTCATTCACCTCCTTCTGATGAAAAGA
          CTGTCCGGGCTAGTCGATTTACACACTTAAGGTAGAGTCATTTAATCCCCGGCAGGCCGA
          CTGCTGATATCACAAGGATTAAATACCGAAGGTATAATCATACCTTTCGTGGGGATAGAA
          GGGCAGGCGGTGCCCAGAGGGCGAATCTCGCTTGTTACTCTCTAAGCCCATCCGAGGGGC
          ACGCCTCCCCCGCTAAGACAGTGACTCAAAAGACCCATTCTCCTTCCCGGATCGGGAAGC
          ATGTCGCCACCGCTTTTCATACAAAGCTAAGGAATTCACCACTTACTTCAATTAGGCTAC
          ATGTCGCTATCGTCTTGAGTGAAAAACCAAGGGCTTCAATACTTCCTACAATTGGACATC

          AATACACGAGAGTATGGCAGTATTTGCATGTAGTCGTGCGTTCAAGGTACCAGCAGCGCA
          AGGATATGAAAGTACAAGCCCACCGATGAGCGCCCGTGTCCCTCGGATACCTGATGAGTG
          AGGATAGGAAAGCTTTGACCCGTCCCAAAATGAAAGCGTTTACCGGCAACTTGCCATGCG
          AACATAGGAAAACACTGCCTTAATCTCAACCGAAGGTGCTTTCAGAGTGCTCAAAAGTCG
          GCCAAAGTGTGGTTCTAGCTTCCTGTTGAGCCGCCCAAGCTTCCCAGCCTGTAAGAAGTA
          ACTTTTAGCGGACTGTTCCTCCCCATCCAACTGCTCAGTATCTTGCGCGTCTGGCGCTAG
          ACATAAGGCATATGTTGGCCTCGTGCCTACTAACCTCTTCCCCTGGGAACGCGTCGTGCG
          ACTTGGGGGATGCGGTTACCTCGTAGTCAGCCATTTTTACCTTTGGGTCTACATTGTGCA

          GACACACGTGTGCACCAACATCAGGGAACCCTTTCTGCGTTTACAAATAGGATGAAAAAG
          TGTTTTCGGAAATGGGGATCCAAAGGGGTTGTCGCTGGGATTTATAAAGGACTCAAGTAT
          GGACGGCGAATGCGGACTCTTTTGGCTCTGAATTCACTTATAACTATTGGCACGAAGCAG
          GGGGGGCTGAAGAGGGCCAACCCGGCTAGCGTCTCTTTCACGCTCGTTAGGAAGATCCTG
          GCGCTTTCTAAGTTGACATGTCCCAAAGGGACCCGGGTAATGAGGAAGGGGACCAGGTCG
          GGATCCATGCGACCGTTGTTACCGATGTCGGCTTGAATGGTCCGTGGGGAACTTATCTCC
          AGCCTTCCGACGCCGATCCTTTCGGAGGTTTCTGGTTTGACTGATCGGGGGACTAAGCTG
          TGTCTTCAGGTGCCGATCCATCAGAAGGCTTCTGCTTCGACTGGCAACGGGACTAGGCCT

          AGATTCTGGAATATCCAATGTGTTAGTATTATCTACAACAACCATCCAGGGGGCGTCAAA
          AGACTTTAAGATCGTTTAAATCCTTTTCGAGTCAGAGGGGACCAATCAAACGTCCTCGAA
          GAGTTCTGCGATACTCATTCGCTCCCCACAGTTATTAGCAAATTAATTAAGGATCACGCC
          AAGCTTAGGGATAGTTGGTCCCCTGTTAGGGTTAACACTAATTGGCTCCGGGATGCGTTG
          TGGCCCCCAAGCGAGCTAGCTTCCATCGAGAACCACAGAAGCATTTTAGCATGCGTTAGG
          ACGTTTTCGCCTAAGTCGGCTCCGGTTGAGATTGTTAATAATACACCGACGGAGGTTTCG
          GTATTGCCAATTACGTATACCACTTCCGGATTCGCCATCGATATTCCGAAATAAATCGCG
          GAGTCGCGAACTACGTCAACTATTTGTGGGTCTCCTATCGAAATTTCGAAAGAAGCCTTG

          AAAGCTCTTCGCGTACACCCACTTGTCGTATCCAGGCATTTCCGTATCATTGCATCAGCC
          TAGTTGCCACCAGTACATCCGAGCTGCATGTCCCCAGACCATCACGCTATTTTCATGGCC
          GAATAGTTGTGCTTCCTCTTTTCCGAGGAACGCAGATACTACTATTAGTAAGTGCAGGCC
          GAAACACTATATGGTCACTTGTGTTGGGCGTAGGAGTACCATTATAATTGCAACCCAGAC
          CGCTCTTCAGATCCGTCTTAAGATACGTCCGGATCACCCAATAGCATCTTACCCCCAGTG
          AAATCCCTGGCACGGCTTAGGCGCTAAAACAACTAGCGGAGCAACATCTGACATTTAGCA
          GTGTCTCTGGACTCGTTGGGCTCCTCGACGATTAAGTCCTGCAGTGCCTGCGGACTGGCG
          CAGTCTTTGGGCCGGCTGAAGCCCCTGACTATATGTCCTTATATTGCCCTAGCACTGGCG

          TCTACCCTCAGCTACGTGGTGGAATTTCGTGGTCCGCGAGATGTATACGATCGCTGTGAA
          CGGGACCTTGATCTAACTGTTGAATCCTTCACTGGGTATGGAGCGTGTCAGAGTCTAGAG
          CTAATTCGCAGTCATGTTGAGAACTTTTCCTTCGGATGCGATGTGTTCAGACGACGCAGG
          TCAGCTAGTCACCATGTTGAGCAAGCTTTTTTGGAGCACCATCTTCGTGATACTTGGGCA
          CGATATCGGAGAAACCGTTCCCCCTAAACGTCCATGTTCATAGCATGTATAGCTCCCGGA
          TAGGCATAGGAATTTACCCTAAAACGTATAATTGTATCCAGCTTAAATTTGAACTGCATT
          CGAGTCTTGGGTCACGCAGCGTAACTCAACTCCGAACGCAAATAACTTTTAGCTCTCGGC
          TGAATCTTTAGTTACGTTGCGAAACTTAACTGCGATTGCAAAGGACCTACAACTACCCGT

          CTGGTGGTTCGGGCGGGCTCAAGTAACTTGGCACCATACCCTTACGATGGTCTGTAAAAT
          ATAGCGCCCCCAGTACTTTAGGATGTCACTACACTGTACCTCAGCAGCGTCCCGAGAAAT
          CTCTCTACTCATAGTGGACAAGACAGGACATGAATTTACTTCCATAAGGGAATGTCACCC
          GTAATGGTCTATATTGTCCCATATGAGGTAATGAGCCATCTCTCTCTAAGCTTAGCAATC
          CAAATTTCTTTGCTGGCCTTAATCCATCTAGTCGCGGACCAACTTTTTGTCACTCTGCAC
          TGCACATTGTCTTGGAACCTAACCCTCCTGACCGGGCGTCACCATCACTACGCGTGGAAC
          TAAGTAATACTTCCTGCACTGAGCTGATAGATGGCTTTCAACCATCCTAATACGTTGAGC
          TGAGCAATTCTCTGTGATTAAAACCGCCAGATTACCCTTGACAACCCTTCCGCGTCGTGA

          GCTCGTAATAGTGCGTAATATGTGTAGCCCATCATTTCTAATATCATATTATACTAACCT
          AACCGTGCAAATATCTAAATCGGACGCCCCGCCACTCCGGAGAACGCTCCGAAGTCAGTT
          GCTGACGACAGAGTGTCTCCGCTATGGTCCCTTGCTTAAGCATCCAAAGTGAGTGCAGTG
          ACCCAAAAGCATGTGAGCACGTAGCGCAGTAGTGACCCTAAATCCAAAACGGACGACAAT
          TAATGAACGAGGTCCCCCCCGGCGTCATATGCACACTGGTTAATTCGGGTAGGAGCAATT
          ACACATATTTGCGAGCTTCGCGTGCAACTTACCTACTAACAAGCACAAGTTAGTACAATC
          AGTGGCGCCATAAGGCTAACCGGTTGTCTTGTCAATCCGAGGGCCCATATTAGTACAGCT
          ATCCACGTAAAACGGGCATATCGTTATCCTCCTAACTAGCAGGCCAACCTTACTATATAA

          TTAACTGGCTGTCTGAGCCGACCGCTTGCGCCTTCCGCAGGATTACGACTCACATTGCAA
          CATACCGGTAGCTTTAACTATCTGTCTATGTTCTTTGCGAAGTCGGAGCCCGGTTCCACG
          CGGCTTTGATATGTTAAAGTTCTGCCTGGATTGCCGGCTGGACTGATCTGTTGATCCGAG
          AAGATATGAAACAGCAATTATGCGTTCGTCGTACTGTCCGGGCCGGGCAGTTGAGTGAAG
          TAAGTATCCAGCTCCATATAAATGCCTGCGCTGTCATCCAACACTCGTCCCCGCCGACCC
          CTTATCTGCGACTCAAGTGATCAAACAACTCTCCAACTCACTGTACTCAATCATTCGATT
          CGTGCTATCAGGTCCGCCTGTCCACGTGATTAGCCAAATGTATAGATCAACAGGCGTATC
          CATGGCTTTAGGTCTACGTGTATGTGTTACTAACTACGTAAACCGTCCAACCGGGCAGCT

          ACCAACGCCCTAGTATGAGCCTGGAGTTACTAGAAGACCATTAACTACTTCGGTAGAGCG
          ATGACTACACAAATTCGCACTAATTTTTATCGCCAGACGATGTGGCTCGTTCGCTAAGAG
          CCAAAAGGTGAAACGAGCTCAGTGGCGCACTCAAGTTTTCCGTTCTCTTTGGGATCATTA
          CCCTTTGCCTGATTGCGCGATTTCACACACCCAGAATTAACTGCAACTCTGAAACGGCTC
          CGTGGTTCCGTGATGGATGATTACGAATCACATGGATCATGATCATTCTGCGCTCTAGTG
          TGTAGTTTCGGCGAGCAGCATAGCAGGCTTAAAGCAAAATAGGTGCCTTAGATGCTGAGC
          CGCCGCATCGATGTGTATACTAACTAATCCTAAGGGCACGCAATTTCACGAAGACTAAGA
          TGCCATACCAGAGCATTTATCGACTGGTACCAAGGGCTCAAAACCCCACGTAGAATGAAG

          TACGCGCATATTTAATTATTATCCAATCCGAGCGTGTGGTGTATATGGTAATTGGCCCAT
          CACGGTCGTGGCTGATTCTTATCCAAGCCCACCCTCTGCGTATAGTAGAAACTTTCGTAT
          AACGACTGCCGTCAGTCCTCATATCATCAGACGATTTGTCACCTCAGATTGTTCATGAAC
          CGCGCCAGAAGCTAAATTACTCGAAACCAGACGATTTTCTGTGAACGACAGCAAAAGTAG
          TGTCCACCCGCCATCCGATCAGACGGCCTTATCAGCGGCGAAATTACTCACCCTTAGTAC
          AGGGACTAAAGTCACTCACGCGCCGATCAATATAGAGTGAGCAATCAGCAGATCCTGTAG
          TTTACTGGCGACCGCCTATTGGTTGAATACTTTAAAAATTGACCAAGATACTATCAAAAC
          AATATTGGTGATTGTCTATCGGTTAAAAAACCTATAAGTGGCATAAGGTGCATCCAGCAT

          TGACCTATCATTGATATGAGCCCAACAAGGAAAGGATATTGTAACGCGGTTTAATTTATA
          CGTCCGACCACGGAGGCAACTCGTACCATCATGTGAGTGTGCGTCGCGAGTACAACTGTT
          TACGCTTCCAATTCATTACTATGTTCCATGACGGGACGATGCTACGTGCATTAACTCATC
          TGCCGATCCAGTGGTTGTATACTCTTAGTCGCAAGTTGGCGCTCCTCGATCCAGCCTTTA
          TGACCATTCATCGGAATGCGGACTACAAAATTCTGTTTATACCAAGCATACCGTCGCGTC
          TGATACGTCAACCACACATGGGGTGGTTAGTTATGTGTGCACAGACTGAACGAATAAACC
          TGGCTCGACGGTAGTCTTAAACTCTATAGATTATACCTTCATTGTGCACCCATATACGCT
          TAGCTCATCGATAATCTCTAATTCCAGGGATACCATTTTAGCCTCGCGCAGAGATGCGCA

          CGTCGGCCGTCCGGCGTGCCGTCTCTTCGGCTGTCACCCATTTACAATTAAGACGGCACC
          TATCGACCTATTAGTCCCCGGCTGCACTTGTTACTACATATTTCCATTACGTGAGTTCGC
          CAGAAGTCCCCTCGCCTGCGAATTTAAGCCCGGCTGCGATGCTGCGTTAAGGCAACAAGC
          TGGGGATGAACTATTTCGCCAAAACAAGTTTGGTGATACTCTTCCATTTCAGTGGCTCGC
          ACTCACCTAGATGCCTCGTCGCTTCACTCCTCGGTCCGCGCTTATGAATGCGAAACGTGC
          AGACGGCCGCATGGTCTATTCGACAGACCCCCGCCTCTCCGACCCTCATGTGACCTACGC
          TGCTGTCCTATTGGCCAACTACAACGCGATTCGGCTTCCGCCGGAGAATCCCATATCCGT
          CGCCGTTTCATTGACCCAAGATTTCGCGTTCCGGCTCCTATCGAAGCATATCAGATCCGT

          AGAGCGTTAAGCCGTACATACGTCGAGCCTCAGAGTATGTTCCTCGAATCCTGCACGTGG
          GGTGTGCAGAGGCTAATTTGTGTTGGCTTTCAGAGTGTATCTTTCTAACCCCGAAGATCA
          AATGCTGATGGTAACCTTTGTAGCTCCTACCAGGGGTGGCTTTCCATATTTTGACAGAGT
          GACGTGGGCAGCTAGTCTTATCGATCCCATAATCTTTTGCTTCCCGTGTTTTACAAGTAA
          CGCGCGATCTAAGGTCAAAACGACCCTATAAAGCAATTTCCGATCGTACACTGGTGGTAT
          CGGGGAATCACGGACGATCCTGGGCTCAACAAACCTCGTATCGTTCCCATCTGATGGAAA
          TACACGCATTAGAATAATGAATGGCCCCACGAGTGCCCTTCCATTGTTTTCAGACAGTAC
          GGGATAGGTGAGAACAGTAATAAGCTTCACGAGAGGCCTACCATTGATCCGAGACAGCAC

          CGAAGCGCAACAACCCTAAATTCCAGGATGCAGCGCAGCAAGCTCTGGCACCGCCAGGAC
          AGCCGAGACTTATCCCCAATTCGGCAAGCGCAGTGTACTAGACCATGTAATTTTCTGGAA
          TGAAGAGCCTCGTACGTTCCTGCACATGTCAGGGGACCGCGACCGTGATGTACCTAGGAC
          GGCAGAGCGCCACCCCTTACATCATGTGCACCGGGCATCGAGTCCTGATGGTCTGAGCAT
          CGGCGTGCACGACTATCGACGCGTTGGGCTTAGGGCCGCAGATTGAAATAAGCCTCAGAG
          CGGTGTCAGTCCCTGTTCATAATCTACGAATAGGACTATCGTCAGTAACGCGATTACCAA
          CCGCGTGCGCTGTGAATGAGTCCTTCGACCTAATATAACGGATCCCACAGTGAACTTGCC
          CGATGCACGCGGTCAGTGAGTTCGTTGGCGTAGTGGAAGGGGTCTCACGGTCTTTCAACT

          GGCCGTCATTCGGCTATATAACGCAGGAGCGGGTTGGAGG
          CCGTGTGTTCTCTTCGCCGCTCTCCGGTGGGAAACAGCGG
          ACCCTGACCTCCGATGCAACTACTCTTGGGAAGGCGGCGG
          TCTCCTACTCTAAGTGTACCGTACAACCCGGAACCAACGG
          CTGGATCTACCGACTACCTCTAGACTGGTATCCCCAGTAG
          GTGGTTCCTCAGCGGGTCCACAACTTGCTACTAACGGAAG
          CTCCTTATCCCAGTTAGGTTGAACCAACGACCCATATTGG
          CCTGTTAACTCAGCCAGCCTTAACTAGTGAAATAGTATGG

