 8 1000
t1        CCTTTACTGTGTTCGATCCTGTAACAAGAATAGAAGTACGGCGGGGAATCGCCTACAGGT
t2        TCTTTACTGTGTTCAATCCTGTAACAAGAATGGAAGCACGGCGGGGTATCGCCTACAGGT
t3        GTCTTTTCGTGTTTGTCTCCGTAATTATAACAGACAATTAACAGGATACTGCGTAGGTGC
t4        TAGGTTGCGCACTTGACTCCAGGTTACAACGACTTCTAGTACGAGGCTCTACGTAGAAAT
t5        CTGATCATGTATCCGTCTATGCCTCCCGTACGAACACAAAACGGAATGTTGACCAAGGAT
t6        CGGACTCTACAATCGCCTTCAACTGTTGCGCGTAGAAATTACGAATTGTTGCACAAACTT
t7        ACCGGTGTACAATCAAATAAACACTCACTACGCGTCTCGGGGGGAATACAGGATAGAGGC
t8        AAAGGTGAGTAGCTAGCTTGATACCTTACAAGCGCGACGCGCGGGAAGCAGCATAGAAAT

          ATCAAGATTGGTCATTCCACCTGCTGGTCCCATTCATACAGAATAGAGCTTGTGATTCAT
          GTCACGATTGGTCATTCCACCTGCTGGTCCCATTCATACAGAATAGAGCTTGTGATTCAT
          GTCAGAGCTGGTCACTTAAGTTGCAAATTCCATAGGTGTGAAATGGAGCGTGCACTGCAC
          GAAAAAGATAGCCTGTCTGGCTCCAGGGTCGATACACACCAAGCGGTGTGAGTGACGTGT
          ATCAGAGATGGCATCCTTCACTGTTAATCAAGAATGAGCCCGACGCGGACTCCAATGCGC
          GTTCTGAGTAGCCCTCTCTATTGGAGGCACAACGCGGTCTGAATCAGAGTTACGATATTC
          AGCGAGATCGGACTACCTATACGGCGGTCACGCGGGAGTTGAAACCTCCAGCGGTCACGT
          ATTGGAACCGGTTTGCCTGTCCGCTGCTCAAGTGGGAGCTAGCCTACGCACAGGATGTGC

          TTATCACCGAAGGCGCAGGATTCGGACGTCAGGCCGGTTGAAAGTACTCTCCCACAGTAG
          TCATCACCGAAGGCGCAGGATTCAGACGCCAAGCCGGTTGAAAGTACTCTCCCACCATAG
          TTACCATTGGCGCAGTGACACTTAATTACTATATGGCTGCGATGGAATCTTCCGCACCCT
          TGAAAGACGGAAGGTCGCCCTTCAGTTATCAAAAGGAATAGAGGTGCCTTCCTGCAGGGG
          AACCACCAGGACACGTGACATCTAGTCAACAAAAGCACCTGGAATTCTCTCGGGGCGACG
          CCGAAAACGTGCATGCGGTCTTTGGGCGTCCAACGGACGGAAGGGCGATTGTTGTAACGT
          CTTTAAGTGAGCTAAATGTGTCCTCAAACAAATCGCGGTTGACGGCTCCACGCGTGTAGA
          CCAAGGGTACACAGACGGCCAGATTTAGCATCTCGTAGCCGAAAGCTTAGTTTGCTGTGA

          TATCTGCAGCCAAGTATGAGACTTGACAAACTTTATTCTACATTAGAGCTCCAAGGGAAT
          TAACTGCAGCCACGTATGAGACTTGACAAACCTAATTCTACATTAGAGCTCCAAGGGAAT
          TCCACGCTGCGACCGACGGCCCCGGTCTGGTTTTATTCGACATCAGAGCCTCAAGTGACT
          GTTGGATTGGGACCTACAGGCTTATTCAGAACCCTGTCGTCGCGAGCTCGCCAGGGCGTC
          CACAAGTTGCGCAATACGACTTTGGTTAATCCTTTAGCTCCGAGAGCCCGTTAAGACCTC
          CTAAGGCTATGAACAGCAGTTCGGCACAGCCGTGAATTCATGTGTGATCACAACGGTAAC
          GACACAGCAAGTTCTCAATCGTAAGGTACCAGGTACTCTTTTCATTATATATGGTCGACT
          AGTATGGCAAGCCCAGTATCGTGAGCTACCTAGTACACCGGCTAATTCATTTTGCGTCGG

          TTCAAGCGTTCCCCTCTGACGTCGAATTCATGTACACTGCTTACAAATCGATCGCGTATT
          TTCAAGCGTTCTCCTCTGACGTGGAATTCATGCACACTGCTTACAAATCGGTCGCGTATT
          TCCAGGCGATATCGTTCGACTTGGAGTCCACGTTCAGCGACTATAAATCGATTGCCCATT
          AGCGGATAATCCCCCCTGGAACCACGCATGCGTTATGCAGTCACAAGTTAATTGGCCGTT
          TTAACAGAATAGCCATCAAAGCGTTAATGATGCGAGGAGTCTGTCCACTGATTGCCCACT
          ATAAGGGACTTTTCTATTAACCGTTCCCCTCATGCTATATCACTGCACCAACTGTTTCCT
          TTTCGTATGACTCTTTCGGGGAGTTAATGTTTTTCTACGGGGTCACTTTAACTATCTTTT
          TTTCAGTTGCCCCCATTGGGCCCTGTATATACCGCTACGACGCCGCCATGATGACCTATC

          GAGTGTTGGACCCTTGAGCAGTCGACTAGTGTTAACGGTAGAAAGCTATTAATTGGCGAG
          GACTGTTAGATTCTTGAGCGGTCGACTAGTGTTCACGGTAGAAAGCTATTAATTGGCGAG
          GACCGTAAGACGCTTGGGAGCCATCCTGGCTGTTCTAGTAAAGAGTGGCCAACCGGAGAC
          GCGCAACTGATGCGCGGTGGGAATGGAATAATCATCCATGAATACCCTGGATCTGACGCA
          AATCGCGGTACATCTGTAGGGTCTGACTACAAAGCCGAATGGCATCCGGTAATCATGCTA
          TTTTAGTTATTGCCTGCGAGGCGTGGTGCCGATATCTCTATATCGATACTGGCAGTGTCA
          AATTGGCTAATCTGGGGGGCCAGTCCGGACTGTCTTGAGAAAAATTTGCCATCACCGAAA
          AGTGGACTTACCTGAGGGGTTACTCCGGACCGTCTTTAGAAAACTTGGACACCGATGGAC

          GTATGATTGATTCGAGGGAGCAAACGTCTGGCGGAGTGCAGTGGGCTTTATGAACGGGGT
          GTATGATTGATTCGGGTGAGCAAACGTCTGGCTGAGTGCAGTGGGCTTTATGATCGGGGT
          GTATGTTTAGATCGAGGGAGCGGCCGTCCGGTGTAGCGCAGCGATATTCAAGACTATAGA
          GCATGTTTGCACTACGAGCGCGCCAGTGCGAAGCGGCGCCACTAGCTGAGTGAATAGGCT
          TCTATTGCGAGTTGTGCCCAGGTCTACTCGGCGCGATCCCCTGTAGCGTATGTACAAGGT
          CCTTCTCTTAACCGATCGCCCGCTAGCCCTCCGTGGTATAATTAAGAATACAGAAGGATT
          GCAGTTGGAACTCAGCGACAGGTCCAACCTGCCACACGTAGCGCATTCAACTAATAGGAA
          GACGATTGGGCTGTTCGGAACAATTGACCTGTCCCACTTCGGCCACCAAACTAGTAAGAA

          AATCCTGAGATGCATACAATAGGTCTCTGTTTACGGTTAGTGCAAATTAGCACAGTGGCT
          AATCCTGAGCTGCATACAATAGGTCTCCGTGTACGGTTAGTGCAAATTAGCACAGTGACT
          GACCCCAGAATGCACCCGATCACCCTTTGGTGGCGGCTAGAGCAAATTAGGACAGTGGTG
          GCTCGAAGGAAACATACATGCGTGCCATAAAAGGGGGGGGAATTATCCAGTGTAGGAGCG
          AATCATAGTACCCTTATCAGGTATCCTTACTTCTATGACAAAACATTCAACGTCTTCCTA
          GATCAGGAGGTGTATGCTGGGCCTCGCTTTCAGCGCGATGCGACGACTAACGTGGTCCCT
          CTCTACCTTACATCGATCAGCCCTGGGCCAAAGAGAATCGCAACGATGAAGCAACATCCT
          CAATTGCAGCGATCGGTTGGACCTGGCATGCGCAACGATACAACGATAAACCGAGGCTCT

          GTATACGATACGGAGTGTGTACTTACTCTCGACACGTCATACGGATAACTCTGAACAGCA
          GTATACGATACGGAGTGTGTACTTACCCTCGACACGTCTTACGGATAACTCTAAACAGCA
          ATACTGGTTGCGAAATGTAAAGCCACTTAATTTACGCCCCACACATAACCTGAAACAATA
          GTATGCGTGTCGGCGGGAGAGGCCACCTGAATCCAGCATTGTGGAGGGTCTGATACGGCC
          TTGTATAGTGCGGTCTGCAGTACTTCCTATATTGTAAGCACTGGACAGCTTAAGCGCTTA
          GGGTATGGCGTGATGCGTGATGAACCTCCGATCATACACTTCGCGTTTTATTTACATCTA
          CCATGTAGTGGTGCAGGTGCGACCAGCGTGGCTCATTGACGCAGAGTCTACAAAAGTTTA
          TTAAGGAGTGGCACAGGAAGGAACCCTGCAGTCGAAAATGCTAGAACCACCAAAAACTCA

          TGCGCTGAAAATGGTGGGTGCCCCGAGACTCATTCCAACCTGTTGACCTGTCCTCTGTTT
          TGCGCTGAAAATGGTGGGTGCCACGAGACTCATTTCAACCTGTTGACTTGTCCTCTGCTT
          ACCCCTATGTATGCTGCGCACCCTTAGACCTCTCTCGCATAGTCAACTTAACCTTCGCTC
          AACACTGACTATGGAGGGCACCGATTTTTATGGGTAGACCGTTGATCCGGACCTAAGCTT
          CGGACCTGAATTGGTGAGTACCATGAAAGCCTCGCCTACTCGAATACCCGTTCGACATTC
          TGAGCTGCAACCCTTGTGGGCTGAAAGGTCCCCTTAGATAGGAATGCTAATCCGAGGCCA
          AAACTCGGAGCGGAGCTGCAGACGAAACACAACACCGGATATGGAGTTTATGAGGAACCA
          GTCACCGAAGAGCTTAAGCAAACGAGATCAAATATCTAGGTTTAAGCGTGTAAGGCGACA

          CGATTCGTCATGGACCCCAATGAGCCTTGGAGGGCTGCCTGTGCCGACACACGGAATTAT
          CGATTCGTCAAGGACCCCAATAAGCCTTGGAGGGCTGCCTGTGCCGACACCCGGAATTAT
          CCATTAGCCGGAAATCTTAGTAAGCCACAGTTCACCGGCTGTGCGGATACACAGAGTCGT
          TAGTCGTCAATTGACTTACACAAATAACTGGCAGATGAACGTACGAGAAGATAGGATTAT
          CAGACAGTATAAAGCAGTAAATCCTACAAGGTAAGCGGGTGGGCTTACGGATGGATTCGC
          CAATTGCCTGCGGCTCCCAGCCCGCGATAGGCACTAGACTCTGAATGAACGTGGGAAGGT
          TGGTCGGTCAGATCGTTTTACTAGGATAGGGCTAAACAACGCGAACGATTCTGGCCTCGT
          TGGAAGACAGGTATACAGTGCCGAACCCCTGTAATGGCATACATATGTCGTCCGCGCCGC

          TACCTAGACGCCCTCGTGTGTCACCGATCAGTGTAAGAGTGGTCACATCGCAAGTAATGT
          TACCTAGACGCCCTCGTGTGTCACCGATCAGTGTAAGAATGGTCATTTCGCAAGTAATGT
          TATATAAAGGCACATCCTAATTTCTGTTAAGAGTTGGGCTAATAATAGTGTGGGTAATAC
          CGGGTAGGTGCAACTAAGAGCCTCTTATCAAGGCAAGTATGATGGTCGTGATTGGAGTAG
          CGAATAAGCACTACTGCAGATTTCTAGTGAAGGTAAGACTGATGGGCGAAGACGTGCTAG
          TGTCCTAAAACACCTGGGCGCCCCTAAGAGGAGCAGAACTGGTAAGAGAGGACGTCTCAA
          CATGAAGGTCACGTAAGACGTGCCGTTAAACAAAATAACTAATGAGTCGGGGGCTAGTTA
          CGATGAGGGGTTGTCGCTTGTGGACCTACGTGACAAATCGAGGACACGAGGGCGTCGTGT

          ATCCAGGGGACTAAGCACTATCACGGCTTGCGACAGTTGCATCACAGATAGCCGGGACCG
          ATCCAAGGGACTAAGCACTATCACGGCTTGCTACAGTTGCATCACAGATAGCCGGGACCG
          ACCTAATGGACTCACCGTTTTCGTGTGTTGTGACAGTATCATAACGGATAGAAGGGGTCC
          ATCCACTAGACACGTGGCTCTTACGGGCAGTGGCCATGGTTTCGGAGAAGACACGGCCAC
          TTACGTCCGCCACCCTACATGCGCAGAGGTGGTCAACGGGCACTCGTCCTGAATAAGTAT
          GGTCAATTGTCACAGCGCATGGGGGGCCATGGCAACTAGGCACGAGAACCGAGTGGATAT
          ATTTGTGCATAAAAGGTTGGGTGCTGCCCTCAGTAGTACTCACAAGGTTGGCATTGCTGT
          TCTTGCGTGTCCAAGGTCTGTTGCCGCTAGGAGTAACGCCCGAAGGAAAGGTAGGCTTGC

          CGTTCCACTAGAGTGGGTTGCACCTGAAAATTGGACTTCTCATTAGGATTTGGTATATCA
          CGTTCCATTAGAGAGGGATGCACCTGAAACTTGGACTTCTCATTGGGATTTGGTACATCA
          TATCTTATCTGAGCTCGATGCCCCCCACAACGAACCATCACATTGGGGAGTACTACGTTA
          TTCACCACTGGGGAGGCCTATATTCAAAATCGAGCCATTACGTCGGGGGTACGTGCGTCG
          TCCTTGTACTTAGCGCATGGTCGATAGAGACGAGTCCCTTTCAAAGGATTTAGTCCGTGG
          GGTCTACCCTATACGCGCCGCGCGAGAGCGAGGGCTCCTATAATAGACTTCTGTGCGTAA
          AGCATGCGCGCTGGGGGCCGTGCCCTCAGATAACATGGTCTCGATTGACTAAATGTGGCC
          CCTCCGTGGTTAAAGCAGGACCTTTCCAAATATCGGGTCATGTCTTATCCTAACACAACC

          GAAGGTTCATTACGCGTTCCTGACGCTAGATTCCGTTTGCTGGAAGATCAAGCGCTTCGT
          GAAGGTCCGTTACGCGTTCCTGACGCTAGATTCCGTTTGCTGGAAGGTCAAGCGCTTCGT
          GAAAGGACGCCAAGTATATTTGAGGATAGGCTCCGGTTTTTTGGAGGTTTAGTGCTTTGA
          CATGAACCGTTGAGTTACACTATTGGCTGTATCTGCATGGTTGTGGGTCATACGATCTAT
          ATAAGCTCGTTGCACCGATGTGGTATAGGGCTTCGCCGTTGCCGCGATCGAGAATCCTAT
          GGACGAAATCTTAGCAGGTTCCGGTTTAACTTTCAACCCCATAACAAACCAGAGTGCAGA
          GAAAGACCTTCGAATTTGTAGATTGCATGGATCACAATGGCCGAACGCCCCAAGACCCGG
          GGGAGACCTCCGAATTTGTAAGTTATACAATGTACCGTTCGAGGAGAATCCAAGTTCGAC

          AGATGGGAGACGGCCACCACGCGGCTGCTGCGCCAGGCGCCTGGCTAAATCGGCGGGTGA
          AGATGGAAGACGGCCACGACGCGGCCGCTGCGCCAGGCGCCTGGCTCAATGGGCGGGTGA
          TAATGAAGGACCTTCATGTCGCAAAAGTCGCGCCCGGAGCTTAGGTCTACAGTTGGATGA
          AGAGGTTCGTGTGCAACGAAGTGACTTCCTCTTCCCGTCTAGGCTGTTAGAGGGGGATGG
          TTAGTTCCGAGCGGAAGTTAGCAACTGGTGCGACTACCATGGGGTACCATCTGGGTCCGG
          TGGGGCCCGCTTGTGGTGCCGTACTGACAGGACCTCGAATAGTGCACTATTCGGGTCCGT
          GGGAGTAAAACTGCGAAGCTGAGGCCCATGTAGTAGGTACACCGTAGCATTAAAATTTGT
          GGAAACATGACCGCTAAGTCGCAGCGAACTAAATTCGACCATTGCATCACTCGGGCACCT

          AATTAGTCTCAGACGACCAGCAATTAGTCGCCTTGGACTT
          AATTAGTCTCAGACGACCAGCAATTAGTCGCCTTGGACTT
          AACTCGAGTATGCCTGCACGCGATACATGGACCTAGCATC
          AACATGTTCCCGCAACTCCGCAGTCTGTCCCGGTAGCTCC
          AGAACACTCTCCTTTATCTACATTCTAATTCTCAGGAGCC
          AGATAATAATCTTTCGTCCACCACCCTCATTACATGAACT
          GCGATTAAACTACCTGATGTCTCAACTTCCACCCGGCTGT
          GTAGCGAATTTTTCCCATGCCACAATATCCATTCAGCGCT

