 8 1000
t1        CGCTATTGCGAGATGCCACTTGAACATTTATTAGGTTCCGCCAGGACAAGAGAGTGAGAC
t2        CGCCATTAAAAGATGCCCTATGATTAGATATTATGTTTCGCTAGACCAAAAGACTGAGTC
t3        GCCTCTTATAGGCATTCTTACGAAGATTCACTAAGTTCCGCTGCGCCACAAGTGCCGGTC
t4        AAGTCCTATAAATCCTTCATTGGCTGTCGGTTTGGGCCTCGATAACCGCGAGACCCAGGT
t5        AGGATTCATACGTCATGTGGCGAATTTAGGCTCGGCAGTTTTAGGCCCGAATCTTAGAGC
t6        GGGCTTAATACGTTCCGTTACGAACGTCAGTTACATAGTGCAACGCTCTAATACCACAGT
t7        CGCCGTCGTAAGCCGTACTAATAATGCTAGTTAAGCTTTACAATACGAACCCAACGGAGG
t8        CGCCCACGAGGGATTACCGATGCAAACTGGTCACAAGTCGAATATGAAAGAGCGCAAAGT

          ACGAGGGCGGTTCGGGGTACAACTCCCAAGGCTCTCCTCATCCCGCCGTCACGAACTATT
          ATGAGGATGGTTCGAGGCACAGGTCGCAAGACTCACCATACCACGCCGCCTCGCACTCTT
          AGGGGATTTGATAGAGGTTCAGGGCTACACATTGTTTCTCTTGCCCCTCCCTGACCTTTT
          AAAAAACTGGTTATAGGTGCGCCTGCCAAGGGTAACTTTTCTATGCCCTTGCGCGAATTT
          TTGAGGTTGGCAAAACGTCGAGTTCCCTCGCTCGTCTCCCACATGCTTTGGTTCGCTGAT
          AGGAGAGTACTCAGAGGACCTGGGCCTAACGTTGCTTTGTTTACGTCTTCAGACACTCGA
          GGATGGTCGGCTGAGGACGGCAGCTGTACGGATCACCTCGCGGAGCTCTTGCAGACAATG
          CGGGTGCACAATGTAGAATTTCGCCCAACAAGCTCACGTGCACCCCCCTCGCAAATATCG

          TGGTCCTGGTGCCCAGCCTCCCAAACCGTACCATGGATTTATTGTCCCCTTATCTATGGT
          TGGCCCCTCCGCCCAGCGTCTCAAACTGTGCCATGCATTCTTTGTCCTCTTACCTCCGGT
          GGAGAAAACCGCCTAGCCATCCGCAAGGTGCCGTGGGTCCACGAGGCTTTTTTTTCCTAC
          TAGCTCGTGCTTTTAGGTCAAAACAGAGTACCATGGACTTATAGAACTTTGGCCCGGCGT
          TGGTTGACGCTTCTAGGAAATACTGTCTCAGACTGGATCGATGGCTCCCTTATCTCCTGT
          CAGTTCAGCCCTCCACGTATAACCATCGCACCCTGAATCCATGACTTTCACTTCCTATGC
          CGATATTCGTGTCTGCCTTTTAGTCGAGCGCGATACAAATATGCACAGGATTGCTAAAAA
          CGTCCAAACGGTTAGCTTGACTTCTCCATGTGTTAGAACTACGTACCATAACTTTTCTAG

          GGCTTTGCACAGTGCACGCCTTGGGCTGGGGGAGTGGCGTAAACGGGCGAGGGTTAGTCG
          GGTTTTGCATTGTGCACGCCTTGGGCAGGGGTAATGGTAAGGACAGACGAGGATTTGAGA
          CGCAGCGCACCGCATATGGATTGCGTCGGGAGAGTAATCGAAACAAACAGCAATGTGTTA
          TACGTTCCCTTGTGTTAGCCTTCGGTGGGGGAGTTGACGGGAGGCGGATGTGACTTTTCG
          CGTCATGTCTCGCATCCGCTTTATGTCGGAAGAGCGGTAAAAACAGGCCGAGTTTTAAAG
          AACAGTAGACCGCATTCTCTCCGTGACCGAAGAGTGACAAGGTCAGTTTGGGCCTCAATG
          AGGTATTTATTAGCGGCGTGAAGGGCCGCTGATGGAAACAATGCAGGCTGGCTAAATTAG
          CCGCACGCGCCACAGGTGCCCTGGTCGTCGGGCAGGAGAGAAGCATCCCACTCGACACTG

          ACACGGGCCCCAGCTACCTCATCGCGCTCATAAACAGTTTCAGAGGGGAATTAGCGGATG
          CTACGGGCTACAGTTACCGGAATGAGCCAATAAACCGTATCGGAGGTTAATCAGTGGATG
          GAAAACCGTTCGGTTCCTGCACCGTTTTGAGCAGCGACGCTAGAGGGGCATCGACGATTG
          ACAAAAAACAACGCTTTGGCAACACGCTTAGTGGCCACGCTAGAGGGGGGTACGGGCACC
          GTAGAACGCCATGTGATGCCAATATGATAAGAGGTAACACTAGGGGAGAGTCGTTATAAC
          ACGGAGTGCCAAATTGTTGACTCGCGTTAACTAGCAACACAAGAGGGTAGACGTAGCGTT
          GTCAAGCGTAGTCATTTTGTGTTGCACCCGGACGCAGCGGCAGGAATGTTATATCATTCC
          CTACGAGACTACGGTGTTTCGATGCGCATGCCAGTTCTCTTAGGCGCCGCGAGTCATATC

          TCCGACGTAATTATAATCCCCAAGGTCAGGATTATGATTGACCTCATTTAGGACGTCGTC
          CCTGACGTAATGCTGATCTCCAAGGTTAAGACCATGATTCCCTCCACTTAGGGTGACGTT
          CTTAGAGTAAAAGGAATCTATAGAGGCTGGATGGTGGCCTCCCTGAAATTAAACGTCGTC
          TTCAGTGCAGAGTGGGATCCCAGGGTTAGGACCCCAAATCTCTTGGGGTACGGTGTCTTT
          AACTGCGTGAAACTGACCTATAGAATCTGGACCGAAATTCACTACAGTCAAGACGTCGGT
          TATGATGTCAAACCGGTATATAAGATCCAGAGCGTATTTCGCTTAGCCTCAGATGACTCT
          AGGAATTGAGATCGATTTTGAGGTCTAGGAACGGCGGCGGACGTAAATTTAACCGTTGAA
          TCTATTGCAGAGCCACAATGGGAGTGGGGGCTCGCAGCTGTCTCGGGTAGGAGCGGGATG

          TGTACCAATAAGGGGCGCGGACATCACCTTATTCATGAAAAGTGCTTGTGGTAGCATGAC
          TGTACTCGTAAGGGGCACTGACACCAGCGTATCCATGAACAACGCCCGTAGCAGTGTGAC
          CACGCATGTAGGGGCTGACGTCCGAAACGTAGTTTAGAAAGCCGTTTGCTTTGGCTAGAT
          GGAATGCGACAGGGGCATAAGCTCGTACGTAGTCACTAAAGTCGGAAACGACGGTATAGT
          TGCACCAGTAAAGGCCCCACATTTAATCGGATCTCTTAAAGTGATCCACGACATCGCAAT
          TGTGCTTGTCAGGGGCGCCGATTTAACCAGATTCCTCATAGCCTTCTTCGAAACTGTGAT
          CGTGATTACATGTTGATTCGGCTGCTGTAAGTGATTTTCAGGAGATCATAATCACCCCCC
          GGCGCCTGTACAAGGATTTGGCTCAAGCGTCATTCTGTCCGACACTTATGGCAGTATAAC

          TCGCTTATACGTCGAGTTCGTGTTCTTGCCCACCTGAAAATTTCATTTACGAAAAGAAGC
          TCGTTTATACGTCTAGTTCACGCTTTCGCACAGCTGAATATTTCAATTTCAATAAGAGGC
          ACGATCATTTTTCGAGCCCGTGCGTACCTTCAGGAGAAGATCTCGCCCACAGTAAAATGT
          CCACTGGCCCGTGGGGCCTACGTCTCCGCGCATGTGAAAATCGAAGGCATAAAAAAAGGA
          CTGTTACTAACTTGAGTCTGCGCCTCCGTATGGGAGAGGATCTTAGATACAAGTAACCGA
          TACTCTAAACCCGGCGTCCGCGCCTCGATATGGGAGAAGACATTAGCCTCAAGTAAACGC
          CCACGAACTAATATGCCTAGGGCGCCAGGTTGACTAAGGATCGCATATATTCTGCCCCAC
          TTGACGACATGGAGGCTCTAGTCCCACATCTTATTAAAGGCTATTCCCGTGGTTTCTTGC

          GCCCACGGATTACGTTACGATCCGCCACGGGAACCACTGGGCGGCCGAAAGATTAGTGAA
          AACTATGGATCACCTAACGACTCGCCACGGGAACCAACGAACGGCTGGAAGGTTAGTAAC
          AATTCCGGTCCGTGGCTCACCACTCTGTGAAAGCTTACTAGTGACGGAGAGGTAGGAACC
          CGCTCCAGGTCGCTAAGTGACCCCAAAGGGGAGTGTTTAAGGGGCCAGGCTCAATGTGAA
          ATTTCCAGAACTTTACATGGCTTCTAGGGGACAATTCTAATGTGTGGTGTAGTAGGTCAA
          AGTCCTGGGACTTCACGCAGGTCCCTGTAGATGGCTGTAAGTTGTTGGAATGTAGGGTAG
          CATGCCGGTATGCCTATTAGTCCTGCACGAGGTTTCGCGACAAGCGCAGACGGGGGCAGA
          CTCATCGTACCACCGTTGGGTTCGACCTGAAAGGGTATGCAAAGGATTGCCGGGGCCGAC

          AGTTAAAGTAGGTCCAGAGACCCTGATCAAACGCTACTCAACTTCGTACCCTCTCAACCT
          GAAATGAGTAGGTTAAGACACCCAGACCAACTGCCATTCGATTCCGCGCCCTTCCTATCC
          TGTCCAAACAAGAAATGGGACTTTGTCCGACAGCCAGTCAGTCTGCCACGTCGTAACCCC
          AACTTTGTCGCGCTAAGAGATCAGCCGCAATCACGTTTCGAACGATACCTAACGTAGCCA
          CAACCTAATGAGGTAAGAAACTGTGCTCAACGATCTTCAGCGTGATCTTCCTCTTGGCCT
          GATTGTCACGATATAAGAGATCCGACCATACTCCTCAGAGTCCGCTCTTTCCTCCGGCCT
          CCGCTCAGTATAAGCATAGCAGCGCCCATTGTACATACAAACTGTTCTTTGCTTTACAGC
          GTACATAGCTACCACAGTGATTTTAGCTCGGTTTCTATAGATTCTCTGGCATTCCCGACC

          TTGTCCGGCTGATGGCTATAGTATCCCTTCGGTATCCCCAACGTGTGTGATAAGACGGAA
          TTACACGGCTAATGGCTATAGTATCCGCACGGATCATTCAGTGTGTGTGGTGAGACAGAC
          TGGTCAAGCCTGCGATATGTTACTCCCCTCGGCGGTTTTAGTGTGTGGGGCGTGATGGAG
          CCATTCGGCTCACAGTTGTACTACTTCCCCCTAGACCTCTGCCAGTCTGGCCTATTGGGT
          CTAACTGGTGCGCGGCTGTATCGTCCTCTCGAAGATCCTCACCTATCGGATGCGCCAACG
          CTGCTCGGCTGGCATCTTTTCTGTCTCCTTGGAAAATCCCGTTTGTGGGTAGAGCTGAAA
          CAATAGGTCCAGTTACTGTTCTTGCTTCTCGGAGGCTCTATTATGTCCCCTAGCGATTCA
          TTACGAAGGCGGCAGACACCTTCCTATTTAAGAACTTCTCTGGTATACCTTGGGCGACTG

          ATAAAAGTTCTACTGAGCTCTCGCCGATGGGGACCCGCGGAAAAATGACCTGTATTAGCA
          GCAAAAGTTCTACTAGGGTCGCGCTAGCAGGGACCCGCGGGAGACCGACTTACTTTAGCT
          CTGAATATGCTACTAAGCACCAGTCACAGGCGCCGTGCTCAGCAAAGTTTCGTGCCAATC
          ACAACAACGATCCTGGACACTAGGGGGCAGCGGCTCGCGAGACGCTTATTTGCTTTGGTC
          CACCAATAGCCAAATAACTCTTGCTACCTACAACGCATGGTATGTCCGGCGGTCATATTC
          CTATTCGCTCAAGGTGACACCCACAAATAGACGGGTGCGGTACGTCTGAGGACTTCAACC
          AAACAATCTTTTTGCGAACCGTTGTGACGGCAAGGTCTAAGAAGTTGGGTCTTCGCGGCC
          AGGCGCTCAATGTCGGTCACAGCCTAGTAGTATCTCACCAGATGGTAACCCGTCCCGGTA

          TATTGTCCAGTAATGATTGCATCCAAACTTCCTTTCGACGACGCGAGGACCTATCTGTGC
          CACTGTCCAGCCGCGATCGCATCCCAACTTTCTTTCGATGACACGAAGACCTATCTGTGT
          CTTCACACCGTTTCGGCACCAACTCGAAAGAACCCCGGCGACGAGCAATACTCTCTGTAT
          GATCACTCAGGCTTGATCCAGTCCTGGCTTATTTTTGGCGTTTTACATAGACTCTTGTGT
          AAGCGCCCAGGCCGAGATAAATTAAGATTTTTGTCCGGAACCACCCAAATCTACGCGTGG
          GCCTGGCCAGGCCGGAACGGCCCAAACAGCGTCGACAATGAAACTTGCGTCTACGCGTGT
          TAGTATCATGACTTATCTACGGGTTCAAATAGCGTAGGAGGTGCGAGTGCGTGCTTGTGC
          TGTCACTGAGCCCGGATTGAACTATGAACTTCATCCGTAAAAGTATTCTAGTGTTTTCGC

          AAGCCTATCGAATTTCAAACTCAGTGTAGACATGCTGTGCTGAGACGAGTGGGTATTACT
          AAGCTCATCGCGCATCAGGCAGAGTGCAGGAGTGCTGTATGGAGACCAGTCGACATTTTT
          CAGGCGTCCCTGAATCGCGTAGAGGTGAAACAAGGTCCGCATCTTCCAGTGGATGATCTC
          CACCCGCTCAAGACTCGTCGTTGTGGTGGATGCGAACCGTGGTATATGTGAATCGCCCCC
          CATATGCTCAGAGGTTATGTTAACACACGGCACACCCGGCGATTTCTGTGGCCTCTTCCT
          CAGGTGTTCACGCGTCAGGCAAGAGAAGGGGACATATCGCGATTAATGTAGATACTTCGA
          CCAATACGAGTGTTGCCGGCGCAACCAAAGAGAACACGGCACAAAGTGCTGGAGGCCGTT
          ATCGTGTTGCGTTCCCTCAAATTAGGTTTATTTATTGCGTTCCCGGCGCAGACGAGATCC

          GATATTTAGTGCATTCCTATCTAGCCCGTATATAACATAGAAGGGTACTCTACGAGGTGC
          GTTAGCCCGTACATTCCCATCTGGCTTGTATATAACGTAGAAGGGCTCGCTATGAAGTTA
          GAGTTGTAGTGCATATAAATCAAGTATGTGAGCATCATAGAAGGCTTCCCCCTAGCACAC
          CCAAAGCAGTGTATTCACTCGCTAACTACACCCAGCGCAGGGGGACTCCTCTCGAGGTGT
          GGTAGCAGGCGTATTTACCTCTTCCTTATTCAAAGCATAGGGGGGCTTTTCCAAAGCAGT
          CGCAGTTCGTTCATCTTCCTTTCTCCTTTGAAAGGCGCGGAGGGGTCTACGAAGAGGCCC
          CGGGCTTTTTGCTTAATACTTCAACTACCATCATACGCCGCTAGGGATAACCCGGGAGTA
          TGTGTGGGACGGCTCAGTTTCAGAGTAAGAGAAGGTGGAATCTGGCTTGCCGTGCGGGGT

          ACTCGTGTTTACCTCTAGTTAAAGTATATGCGTTGCACCGGAATGGTAACGCCTATTAAG
          ACTCATGTTTACCTTTCGTTAAAGTAGGCGCGTCGCTTAGAAACGGTGACACTGACCAAG
          AGCTAAGTTATACTTTAATGGAAATGGTCATACTTCTCTCAAACGGAAATACTGACAGAG
          GGCCTTGGTACATGTCTTCCAAGCTAATAATGGCTTTCCGCAGCAGCAGCGTTACTTAGA
          GGGCCAGCTACACCATAATTAAAGTCGTAGCAGTGCTCTGAGCCTGCTATGCCCCTTCTG
          AAAGTCGTTATGCTCTAACAAAGATGATAGTGACATACTGGACCGGCTACATCGCTCCTG
          GTTAAGATTACGATGCGGTTACTGCAGAAGAGTCGTTGCGAACCCCCTGCCCAGAGTCCG
          GAGCGTTCTCAGGTTTCTCTATCGGCGACGAGCCGCTTCTTATTTCTTGTCACCGTCTTG

          GACCATCTTAGGTGTTATATTACAGACCATTAGTCGTGGA
          CACTATATTTGGCGTTAGACTGCCGATTACTTGTCTTAGG
          TATTAACCTTGGCAATATACGTCGGGATTCCGATTGTTTA
          GCCTGGTTCAGGGGACATGCATTGGCATCTAGGCCATACT
          GATAATACCTGGCGCACAACGTGAAAAGGTTAGTTATCCA
          GTTTCGCTATAGCACTCGATGTCGCAATGATAGCTGTACA
          TCTAGTCGCAGGTACTACACGGCGGCACATCAACCAAGTC
          GAATGTTGTCCTAGCCGCAGGCGAAGCTACTAGTCTATTA

