 8 1000
t1        TTGTCCGCGGGGATTTCTTCTAGCGTTGGTCCGATTCATCGGCTCTGTCGGGGTTAGGGC
t2        CTGCCGGTGCGAGTTTCTGACGGCGTCAACGTGACTCATCTGCTCTGCAGGAGTCAAGAC
t3        TAATCGTCAACAGTTCACCGCGAAGTCGATTCAATAAACCGGCAGTATAGGCATGAAGGA
t4        ATGGGGACACTCGATTGTCCTCGAGTCAGCCTGACGCCCTAGATCCCTTTGGATAGAAAG
t5        TCGAGAACGCCTAGTTCCACTAGGATCGGCCTGATGCGATAGTTCACCCATGTCGATGGG
t6        TTTGAGTTACCCGAGAGTAGTGAAAATGGTTTTATGAGTCGATTCTCCTGCGCTGGCGGT
t7        TCGTTCCCAACCGGTTGCACCCGGATGCGGTGTGTCTATCAGTTCTCCCAGAACTGATGC
t8        TTGCCCTCAGCTGGACGCACCTAGGCGAGGGATTTTAACAAGCCCTCACAGGGCTGGTGT

          TCACTACCTGTAGGCGTTCGCTCGAGTAGATGGGGGCCGTACGCTTGCAGTGTGATTTGG
          TCACAGCCTGCAGGCGTTCGTCCGAGTATATGCAAACCTTACGCTAGTGAAGTGACTTGG
          TCTGCACTTTCAAGCGTCCATTCGTGGACCAACCGCTGGTGCTGCAGGGATTGAGCTTAG
          TCCACACTCGCCGGCGGACCCGCTTGCGACCATAGCCCTGCCTGTAATAAGATCACTTGG
          GTCCAATAGGGGCGCGGTGCCTAGAGCGCTTAAACGATGAGCGGGCACTTTTTGACCCGT
          CTACGGCATGTGCACGCTAACAAGAGTCGCAACAGGCGGACACGAAGTCATGTCCCCTAA
          TAGTCTCCTGTAAGTGCGTACCTATACGGCAGTGGAGACGATCCACGCTAATTCCGCTTG
          CTCTCCCGTAAAACTGGCTAGCGGCGCGGGCGCGAAGGTGACCCCGCCTCCTTCGCCGAT

          GTCTTAGGCGGGTGCTGGCCCGGCGCACTACGCGGTGCACTTGATCGTTGTAAGGACTTC
          GCCTTCGGTGGGTGTTGGACCGAGGTGCTAAGTAGTGCATTTGATCGTTGTATACATTTT
          AGTTTGGAGGAGCGCTCGACTTCAGGCCTATGGTAGCTATCCAGTTCACGGAAATAATCC
          GTTCTAAGGACAAGCCGAACCAGCCCCGTACGAAGCGCTCTTAGACCTTAGAATTCATAT
          GCTGCCCAAAGGAACAAAGTTGGCGCCTGACGAACTGCCCACAGCTCTCCTTATTATTAT
          GCCCTGCCCAGGTGCTACTCGCTAGCCCGCCTAAGCTACTAGCAATCTGAGTGGCGCTGT
          CCCCCGATGTAACGACGGGCATGTCGGTAAATAAACTTTTTCGAGCTTCTATACCCGAAA
          CCCTAGGAAAAGTAATCAGCACACTTGTAGATAGCTTTTTTTGAGCTACTAGATCTGAAA

          TTTTCACGTATTGGGTGCACAACACCTCCAGGACATAGTATTCCTTGACAGTTGGTTCAC
          TTCTTATGTATTGTGTGTACGACAGCCTCATGATATAGTCTCTCCCGATAGTTAATTTGC
          CTACTCCGTAGCATAGGGGCTTCGCTTGTCAATCTGAACTCTCCTGTAACGTTAGTCCGC
          CAAGTATGAGTACATCGCGGTGCTTCGTTGAAAAACAAACATGTTCGATTGCTAATACGA
          TGACTGGGTCTTGTTAGGGTGCTATTTAGTAGGCGTTCTGGCCTGTAGGCGTAGCCCTCT
          AAATTCGGCATAATTTGATTGAATCCCCTTAACTATTGCGGCTCGAAAATCTGGCCCTAC
          CAAATGCCGATCGGCTTTTATAGGTTCACGGCGCACTGTAATGGGAGCATCACATTCCCA
          TAGTCGCTTCTCGGCTTGCAAAAGTTCAGAAAGCCTTGCTCTACAGGCACCACATTCCGC

          ACCACTATGCGTTCGGGATAGTGGAGGCTTTGATGGGCTGTGCCGTGTAGTTAGAACGAG
          ACAACCATGAGTCAGGTATAGTAGAGGCCTTGCTGGCCAGTGTCGCGAATATGGACCGAG
          ATCTTTCTATGCAAGGATGAACCCATGCGCCGCTAGTTCGCGCTGTGCGACTGGAATCAG
          GTCCTCTTGGGGCGGGTAGTCCTAAGGGCAAGGACCCTCGTGCCGTGCAAATCGCGGGAG
          GGTCTGTCGCACTACAAAGTCTAAGGATCCCAATGATCGGTGCCGCTTGGACGGACCAAA
          GTCCCACCAAGTCTGGGGGTGCGCGGTTATCACACGCCGGCATTGCGCGAGGGGATCAAA
          GTCCCGCCGCGTCCATGCGATTGACAGAGTTCCTGGCATGAGGCGCGCTAGGTACATTAC
          ACCTTGTAGCTCCAAAGCGACCGGCAGAATCGACGACACGTGCCGCACCAAGAATAGGAC

          CTAAATTAAACCGCTTTCAACCGAGGCCTTATATAGGAGTTAGATAACAACCATGGTACA
          CAAAATCAGATCGCAGTTACGCGGAGCTATATTAAGGAACTAGTCACCAACAATGGATCA
          CGAGCTTGCCCTGCCATCCTCCGTAGCTTGATGTGGAGCTTTAACAACGTTACTCACTTA
          CGGAACCACTACGCCCACAACTGAGGCTCAAAGCTGGCTCTAGGTCCTCTTACTGGCCAA
          CAAGATCACCGTTCTATCTAAGTCAATTGGTAGGAAGTTCTAGCTTGGCACACGTGTGGG
          GAAGAATACTGTAGGGTCTAATGTTACCGGGAGATAGTACGGTTTCACGGCGTTTGCGGG
          TGGCTCTGTTTAAGTTGCGCCCACAACCGAGGTCTGTAACAAATGAGGGTTAATTGTTGG
          GTGCACTGCACGAGTCACTTAAATAACCGGGGACGGGCAAAAGCGAGCCGTACTTGTTGA

          AGCTGGAAACGAAACTTGTCCGGCCGGTCCGATGAAGTATCACCTCGTACGGCGCAAATT
          AGCCGGTAAAGGAACTCATTTGAAAGGTTCGGTGACGTTTCACTACTTACGATGAAAATC
          AGTAGGAAAAAAGGATTATGAGCATCTCATGACTACGCTTCTCCGTGCGCCATAAGAGAT
          GGTCGGCAAGGATGAATGTCATATGGACAAGACGTCGCCAGACTTCTCGGTGCGAGAAAC
          GAGGGGAGAAAAAGCATACCAGCCAACGTAGGTGGCGTTTGCAAGAGTTCACTAGGGGAC
          GAGGTGGTGAGAGCCAAATTCGATTAATAAGGCGGCGTAGCAACGCACCTATTCAGAGAA
          TGGTCGCTAAAGCTCTTACCGGGACTACATGATCCAGCAATGATCCATTCGACCATAGGT
          TCGCTGAAGCAGGTCTTATTAAGATTTCAAGACTGAACACAGACCCATCGACCCATCAGT

          ATACACCGAGTTCCAGTGGACCCTCTTCGCTAGAACTCCAGGCGTGCGCGAAGTTGCGAG
          ACACTTCGAATTCCAGTGGACCCCCTTTGCTACAACTCCAGGTGTCCACGAAGTTGCGTA
          GCACCCTTAGCGCCAGTAGACAGTGCTCGGTGAGACCGTAGATGGGTGAGAGAATACTTT
          GTTCTTTTAACCCAAGAGGGCTCCATTTGCCAAGTCAGTAGGAAGGGGTGAGGACGCCTC
          AATTACTTAGTAAGAGTAGACTCCATTCGTCAAGGTCCCATGTGGGCCTTCTGGGCTTCC
          AAGTCGTCCATGTGAGAAAGCTGCCGCACCTCGGATTCTTGACGTGGTAAGATCCGTCCT
          CTTTATCCACCGCTCGATGCTTCTACTAGTCCGAGCTGTCGACGGGCTAGCCGCCAATTT
          TACCGTTCATTGCCCGTCCTTACCGTATAATAAAATTGACGGCGAACGGCTAACCGCCGT

          AAAGTAACATGCTCGGCCAGAGGGGGTATACAGGCCCACGCCCCCACTAGCAGAGAGTCG
          AAAGAGACATGATCGGTCTGAGGGGATACGTAGGCTCATATTTACACTTTCGGCGAGGCG
          CTCCAGGATTGACCGGTTACGGAAACTATCCACGCTCAGCCGTTTCCCAGTTGCTTATGG
          TTTATGGCAGAACTCGCAGATGGGGTAATGTTAGGTTGAACACTCATGTGATCGATCGAA
          CTTAAAATTAAGGTTGAAGGGGAGATACCGCCAGGCCGTCCTCATACATACGGTGCAGCG
          ATAAAGATAGAATTGCTGGGGGATTCATTGTTGGCCAGTCCCCACTACGATTAAGCGGGT
          ACCCAAGTTCGTTTATGATTGAACTTTGGGTGCCGAGGTCCCCTAAAAAATCACGGATTG
          TCTATGATGTGTCTATTATTGTACTCTATGCGCCCGGGTCTCCCAAGGGATCCCGGATTG

          AGCACTCTCAAATAAGGCTGTTGCTACAGCGAACGCTTACAGTTCGCAGGCCCATTCGAC
          AGTACCCCGCAGTCAGGTATTTAATACCGTAATCGCTCATGGTCCTCAGAACCACCTGAC
          AATATTTCGATGGTGGGTATCAGTCATTGAGTGTGTCTCACCCACGTAAAATTCTCAATC
          TGTATCTCACTCTTCGATGAGTGTGACCGTATAACTTCACGATCAGTCGACCCTCTAAGC
          AGGGGTCCACAGCGAGGCATTTGATCCCGTGCACTAATTGGACATGTCGGTTTCCATCCG
          AATATCTTAGAGCACGGTTTTTACCTTTGGCGCAATCCTAATCCTGACGGACCCTAACAC
          AGCCCAGCACCGCCAAGGATCTGTCACCGCACGATTTTTGAGGTAGGTCGCTTGCTAATA
          GCCACGATTACGGGGGGGTTCTATCAATGCCAGACTCCTAAGCCCAGCGATACAATTGTA

          ATTGACGGTCGCCTCGGTCATGTAGAAAGGCGAAAGTAATTGCTAGTTTAGTTGACTTGT
          CTAGCAGGTCGCCTCGGCTATGTCGAGTGGTGATGGCAACCGTTAGCGTAACTGATCTAT
          CGTGGGAACCCTTTCTATCACGCAACTCCATGAAAATTGTTCAAAGCTCGTCCGATCCGC
          AGCAATCTTATACCCAGGTTAGCATTTCTGAACAGTCCGCATAAGTTCGCACCGGTTTGT
          GTTGCGCCATGGCCAGGATCTCCAGGGCGCTCCGCCCTGGTCACGGACGGGTTCATTGGC
          ATAACGCTCAGACCAGGCCTAGCGTACTAGCATAATCCGTCACCAGACTCGCATTACCGG
          TTTAAGACGAACAGCAATTTCGGGACTTGGCGAACGCGCTGTTGAGCTTTACCGGTCCGC
          TGTAATACGTCTCTGCGTTCCTGGATCCGACAAACGGGCTGCTGAGCTTCACCGATCTGC

          CCTTTGGATAGTCTAGAGAGAATCGCGATAGTAATACCTTGGACCGGAGAGCTAGATGAG
          GGTGCGGACATCCCAGGGAAATTTGAGAGCGTAATACCTGGTTAGAGAGAGCTATCGGAT
          GACACAGACGCTTCAAAAGAAGTAGCGCTCAGAACATTTTTTTAAGCAAGGTTATACAAG
          ATTGTGGTTGTCACATAGGAATTAGTGTAAGTATCACACCTTCGGGTAGCGCTGCGTGGG
          TCTTGGACCTGTATTACTGCCTCGGTACACGAATCTATTCATTGTAGTTCGCTAACCGCA
          ATCTGGGCGTGTATCGTTGGGTCAAGATACATTGCAGACTAGTGAGGATTACTAACTGCA
          TCAATGTCAACCGGCAGGAGGTTTGAATGCTGATTCAATTGCTGCGGTAACTGCCATGTT
          CTGGAAACTATTGGCACGGGACCAGGATATCGGTCGAAATTTTGAAAGAGAACCCGTATT

          TCGGATAACCCACTAACCCTTCCAATTAGCGATACCCAGCCGAGTTGATATTCCGGAGGA
          TCCAGCATCCACCCAACGCCTCTACGGCGAAGCATCCACCTGGCTTGGTATTTAGGGGGA
          TCAGGCTACTAAGCAAATCCCCTAGTTAGTTACTGCCATCGCGATTGCCATTCAAAAGGT
          GCCGGCTATCGATCCTTTGGTCTCGTTAGCCCTTGCTACACGTTTCGTCCGATAGACGAA
          GAATTTCCTCGGTCCAAGTCTAGGACTATCTGCTCCCAGTAAGTCGGTGAACGAGAGAAA
          GCCGGTCATCAGTCATAATACTGAATCAATTACTAGTTATTGACATGAATACTAGTAGTA
          GACTCCGAACGGCTCTTCTGGCCGCCAAACCACTAACAGGTCGCCTACCTAACATGGGGG
          GGACGCGAACAACTATCTTGGCCGTCTAGTCACCAACTGGTCGCCTGCCTAACGCGGGGG

          CCCAACTGGCTGTGTTTGCCATCAACACCCAGCTAGCACTTTCATAGCGGCGCTAAGTCT
          AACCATTGGCTGTGGCTGTTATATACACACCGGTGGCACTCTCATAGTGGCGTTCAGTTT
          ATTCACAGGACGTGAGTGTCAGTAACACTGCACTGGCGGCCTTTTGTCAGAGCCTATCCC
          GTCTACCGGGTTTGGTCGATAACCCCATCCTGCCTGCTCACCTCTGCTGAAGAACCAACG
          CATAGTTGTTCGCTGATGTCTAGGGAATCGGCGAAGCAGATTTTTGTAGCAGCCACTACC
          CTTAGGCGTCTGTAGCCAACAACAACGTTCGGGCAGCAGATACTAGCTACAACCGAGACT
          CATGGGTGATCAAGGTAACATGGAGGATTCGCGTGGATCATTAGTGCTGGGATAATGATA
          TACAGGCGATCGTGATCACCCGGAACGTTTGCATAAATCAGCCTCGTCGGGGTGACAATA

          CCGTTCGCAGGTCGTCCCTCCGCTGCTCGTGCATCGTTGTCTTAAATAGAGTCTGGAGCC
          CAGTTTGCAGGCTGTCCGTCCGCGGTTTACGCACCGCCTTCTAAAAAGGAGTTCATAGCC
          TAACTCGGGCCATGCTATTCGACTGTCTAACAACTGCGAAGCTCGATCGTGTTGGAGGTT
          CCGTATGCGCATCGTCGCTCGCTTAGTCCTTAAATGTCAACCTCTATAAGGTCCTGCATT
          TTGAAAGCGGGTAGGGATTAGATCATGGGTGAACTGCAACCCACGAGCGTGGTAAGGGCA
          TCGGTTCTGAGGAAGTATTAGGTATCACAAGCAACAGGAAGTCCGAGAGCGCTTGGGGTC
          GCAACCGTGGGGTAGACCGAGGCCACACCCGACACATAAACCTAGCTTCAGACCCCAATG
          GCAATCGCGACGGTTACTGAGAGCACACCCGATGCGTGACACTCGCTCAAGACGGTAATG

          ATTCCCTACTCCGGAGCAACACACGCGCTTGAACGAGTCAACGCCGGCACCTAACAACGG
          ATACCTCACCCCGGAACAGCATATTTGCCCGGCTGAATTATCGCCGGTACTCATCAACGG
          GCCTCGCACTTCGCGCTTGTACTTCGATTGAGTAGCATCTTCGCAGGTATTCTTAGGTGA
          GTCCCATAACTGGGATCTTTACACTTACCTCTCTATGCCTTCGTAGGCAACTTCATTTTG
          GCACGCAATTCTCAGGGCGCGCCCTTAGACCGCTTCGGGACCCACGAAGCACCCTATCCA
          ATACTAGATTTTGAGTCAGCAGGGCCGGCCGATTCCGGCGTGGTTGAATCTCCCTATAGG
          GGGCTTTATCCTAAATCCCTGTGATTATGCAACCTAAATTACGACGCAGCTCCCAAACAA
          GGGCTATATTCCGAACACTCTATATTACGCACCCGAAAATGTGACAGGGCCTCCCACTAA

          CGGCGCCCGTATGAAGCTCGTCCTCGATCCAGGTCCCTCC
          CGTCGCCCGTGTGAAACACATCCTCGACCTAAGACTATAC
          CTCAGACTGTATTCAATCGGAACTCTGTCCGGGATGTTAT
          CTAGAATCGCATGTAAGCCGGGCTTGAGTACAGACCCTAC
          CATTGATGCGGTGGGCCCTTGGTGTAATCTGAAGGCCTTT
          AGTCAAGATTGCGGGTCTCACGGGGGAATCTAGATATTCT
          ACCCGTCTGTTAAAAAAAGCAATAAGTCAATTCACACTAC
          ACTTACACCCGTACGAAAGTAGTAAGTCCATTAATGCCTT

