 8 1000
t1        AGTTAATAGCTGCAAGGTGGCGCTCCTACCCGTATACCGGTATCTTTCTAAACCGCGCAG
t2        ATCAAACAGGCGCATGCTGGCAACCTCAGCCGCGTACAGGCATTTTTTTAAACCGCGAAG
t3        ATCAAACAGACGTACGGCTAGACTCCCCCTCGACCACCGGCATTTTTCTATACTGCGAAG
t4        AACCAGGAAATGAGCACTCGGACTGGCCGGGGTCTTGCGATTGTTCATGGTACCATGGTC
t5        TCCAAACAAACGTGTGTCGGCGTAGGCTCCGACGAAGCGACACTCCTTTAAGTGAAAGGG
t6        GTTGAACAGGAGTCTTCCAGCGCCGGCTGCGACGAACCGACACTCCTCTAAATGACAGCG
t7        AGTTGGTCCATACGCGCCGTGATTGCTTGCGAACGACTGATACTCGCTTGAGACAAGACT
t8        ATTAGGTCCCTGGTAGTTGTCCATCGCCGCGAATAACATCTTCTACATTGCCCTAAGGCT

          CCATGCAGGCTGTTGCGATCAAGCCAATTTGGCGGTCCTAAAGGTTCCTGTAAGTTATTC
          TCACGCAGTCCGCTGTGTCCTAGATCGGCTGGCGAGCTCAAAAGTTCCCTTACGGTATAC
          CTATGCATCTCGCTGCACTTAAGTTCGACTGGTGGCACATCAGATTTTGGTATACTGTCT
          TCATGCTGTTGGCCTCGCTGAAAAACCACAAACACGGTAACGGATCTCCATTCACTACTC
          CCACATAGTACCCTCTGTCCTAGATTGTGGTACGATCGAACAGGTCTCCGTCCGTCAAAT
          TTCTAAGATGCTCATTGTTCTATATCAGTATGCGGTCTCACGGATTTCCACCCGTTAAAA
          CCATCATACGATACTCACCTAAGATAGATAGTAGGGAAGGCGCGCTAAACCAGCCTATTC
          TTGCCATGACACGACCGTAACCGATTGAGGCAGGGCCAGGAAGGCCCTGCCCGCACACAC

          ACGCCTCTCTAATCTGGGCCTAGGCGCCTCAATACCTTACACGACTTACACTTTTGCATG
          ACGTTTTCTTCATCTAGGCCAAATTAAACTAATACCTTATGCGATTAACACTTTTGCATG
          ACGACTATCCATTCTGGACTACGTCGCCGAAACGCCTTACGCGATCAGTGCTTGAGCGGG
          GTGCTTCCTGCATTAAATGTATGTTTCACCCATGTCCCACGCAGTTTACCCTTTTACAAC
          ATATATTTCTCAGCAAGTTCTAACTGGCATTCTGCCCAATATGGCATACCCTTCATCACC
          TAATCTCTCTTCACCGGCCCTGGTTGCGATTCAGTGCAACACGACTCACACGTTACCACC
          CGTGATCACGAAGCGCGCTTAAGTCGGCCCTAATTTGGGGGTTGTCAACCAACCTGTCCG
          GGAGTTAATGAGTTTGGACAGCTAGATTTGCTTTTAGATGGTAGCCTGCCTCCATGGATG

          CCCGATTTGCGATCCCGGGTGGCCTGATCCACTTAACTTCGGGCGGCTTAAGCGCGTATC
          CCCAACTCGCGGTCCCGGACGGTCCGACCCCCCTGGTTTTGCGCCGTTTAATAGCGCTCC
          CATAATTTGCGATCTGGCGAGGCTCGTGCCATTTGGCTATGATCGATTCAGCAGCGTAAT
          CTCGATTTGTAACGCGCGCTAGCCTGCTACGTTACACCTTTTCTAGAGCGAGTTTGTACA
          TCAAAATAGTAACATCCGACGACTCGGTATTCTCCACCTTTAATATCGTAACTGCATATC
          TCAAGATTGTGACTCCCGGCTGACCGAAACGCCCAGTCTTCATCATTCCAACTCCATATC
          TAAGAAGTTGGCTATCTAGCTAACCGTCGTTTTAACTTTCGCACAGCCACGATTTGCGGT
          CTGGACCAAAGATTCTCGGTCACCTGCGTCATCCTGTATTTACCGATTACCTTCCCCGAG

          CCTCCCTAGTCACAAGGGCTTGTAGCGTCCGCTGCGGGGCGAAAGTGCTAAGCCCTCCTC
          CCTGAACGGGTACAGGGGCTCAAAGCTTCTCGTGGGGGGCGGAAGTGCTTAGTCCCGCTC
          TTTTCACGGGCACAAGAGTTCCTAATTTCCCCTGGGAGGTGAAGGTGCCAGGTCCCCCTG
          ATCATACCCGGAGTGGGGCTTGGTACCACTCGTGGCGTGCGAACATAAAGGGTCCTAATC
          TCTCCCACCTGGTAGGGGCTGTCTACCGCATGCGGGGGAAACAAGTGAGGCGCCGATCTC
          TAGCTTCTCAGGAAGGAGTTATCTTCCCAGCGTGGAAGGAGCATGTGAGGTGCCCACCTC
          ATTTTCCGGGTGGTAACGGGTCTCGGGAACGTCTCACCGCTCGAGCTCCGAGCTGACATC
          CCTTGTATACGCGAGGTGCACCGCCCGTCCCGAACGCGCCTTAGAGACGGAGTACTATTC

          AATTGCTGTTTCTACTCCTTGAGTCTGCCTGGAACGGAGGATCGAATAGCATTGCATGTG
          AATTGCTGTTCCTATCTTCTACGTCTGCCCGGAACGGAGTTCCGAACAGCATTAAATGTG
          AATTGTCGCTCCTACACTTTAGGACTGCCCAAAACTGAAAGCCTATTAGTATAACCTGTA
          GATAACCGCTTCCATTCTAAGCGGCGATCTGAATCCTACGAGAGGCTGAATATCTGTATA
          GACTGCCGGGTTGATCCTCTATGGAATTTTGCGCCTTACACTCGAAAGACAGTATATGTT
          AACGGTTGGTTTACTTCTTTATGGCTACCTGCGCCTTAAAGTTAAATGACCGTGAATGTA
          AGGCGCAATCCATGGTGAACATGCCGTACCGGGCTCGGAAACGCAACGCCCGCCCTACGT
          AAGTGACTAATTTGACACATTCGCACTACTAATTTCTCAAATTCAGCGTGAACCCTTACG

          TGCCGGACCGCAAGAATATATTAGTTCGGGTACGTGTGTTATAATATCCCCCAAGAAGTT
          GGTCGAATCCCGAGAACATGCTGTACCGGGTATGTGTGTTATAGTAGATCCTAAGAAGTA
          GGGCAGACGCTGTGAATCTGTCTTCTCGTATCTGTCTGTCGATGTCGTCTCTTAGCAACC
          AGCCGGAGCTAAAGAACTTGACAAAGAAAATCCAGGCGCCATAATGGGTTCTCATATGTC
          GCACGCGAGCTGGGAATATCTCAGCGGGGTTCTGTGTGTCCTCACGGGTTCCTGAACCCG
          AATTACGTGCAGGAAAGAAACATACGTGGCTCTACGCTCCACAACGCTGTCTTGTTTTCC
          TTGCAAGCACCTCAGAGACGCCACTTAACCTCCAAGCATCCTGGCAGTATAATGAAACCA
          GTACAAGAGTTCAAGTCACCCGGTTTTCAATCTTACTCGTATTGTGATTCGCCGCGATTT

          TTTACAGTGCGTTTTGTGGCAACATAAGAGTACGCGGTCTTCGATAGGCGGCGAGTACAC
          TGAGTAATGCGCTTGGTGGCAACAATAGGGTGGGCGATTTCCAATCGGGGCCGAGTATAC
          CGAGAATAGGGTCTTACGACGACAGCAGGGCGCGTGTATCTCGAATGAAGTTAAGCGCAC
          TGTAGGTCGCATCTGTCTACTATAATAGAAGGGGCACACCTTAATCAGGGATGACAAAGT
          AACGTGCTATGCCAAGTAGCTACGATGGACTCAAAAGTTCCTAGATGGAGGTGGCCGTTC
          GCCATGATATGCCTAAGAGAACCGGCTCACTGTGCGGTTCTCAGTTGGAGGCGGACGTTC
          CAGAGGAATCAGCAGCTCGTTGTATCCCGTTATCTAAAGATTCTACAATGTGACCTGCGC
          TAGACCAACTATGACCTGGCCTTCTATTATCCGGGGATGCACTTATCGGCGGAGCCATGA

          AGGTTCTTTGTAGCTTTCCTGTCGTTCCTGTGATATTACTTTGAACTCATACTGGTGCCT
          TGGTATTTCACATCTCTATTGTAATTTCTGGGGTATTAACTCGCACGCATTCAGGTGCCC
          TGGTATCCCGCACCTTCTCCGTGATCTAAATAGTGTCGCCCTGAATGTACCCGGGTGCCT
          GGATATCGTACGTTGTCACTGACTCCTAGACGGTGCCAAGACGGTTCGAACGAGCTCCTC
          ATACCACGTATGTCTCCCCAAATATAACGATACCGTCGCGGAGGCTGAAGCCGGACTATC
          ATATTACCCATTTTTTTCTTAGCATAACAGGACCGTTGAGTAGGCCGTAATACGGCGAGC
          TAGGATTGTCTACGCTTATTCTGATTACGGTCACACTAGTCCTGTGACGGAAATAAGCAG
          TAATCCCGTGTAATTATCGAGGGGCTAAATCGTACCCAATTCGGCAATTGGAAAATATAT

          CCCTGCTCATCCAATCCATAAGATCATTACGGACTTTTCCTCGGAAAGCGACACGCTTAT
          TCCAGCCTATTCTTTGCCTAGGGTGACAACGGATTCTTCTTTGGAAAGTGACCCGCTGAT
          TCCTGCCTATCCATTCTTTAGAGTGACGAGGCGCTCTTCTTTGGCAATTGACCCACTGAT
          TATTCTGTGCCCCAACTAACTTCCGACAGAAAGGCTTTTGCTGGGAAGGATCGAAAACAG
          TCGATTTTGTCGTGTCCCCCACTTCGAAAGGAGCTGTCAACGGATTGGGAATCGCATAGT
          CTGGGCCTGTCTGGTCACTTACGTCGAGAGAGGCTGTCAACTGACTGGGGATCCCGCAGG
          TAGATGCCATCTTGAGCCTATCCACGTGCAAAGTCGGGGATATGGGGGTGATATACGATT
          TCACAGACATCCTGCGTATTGTGTAGCAAAAATCAACGGACGGCAGGACAGTACGCAACT

          AATAACGGCAGGACAATATGTAAAATTATGACGTATTTGCTGTCCGTCCGTACTTCACGT
          AGGGACGGCAGGACAATAACGATCATTATGCCATACAGGCCGGCTGTCCGTATGTCGTGT
          ATTAACGGTAAGATGTTGCTGACAACATTGGCGCCTATCTTGAACGGCTACACGATACGC
          AGCATCGACAGAATAGTAGCGGAAATTGTGACCTAGTAATGCAAAGCCTGTAAGTTCCGT
          AAGAGTCTTAGGAAAGCGTAGGTAACTGAGGTATACTTGTCGACCAGCTGCAGATCCCGA
          AAGGGTATCATTAAAGCGGCGGTCCTCGCGGCCCATACATCGCCCGAGTGCGGACCCCGA
          TAGGGAGTTCCGTTGAGATTGACTCTGGTCGTAAGACCGCCTTCTGTGAATGCTCTTTAC
          CGTTGAGCTCTGTAAGAACCAGCGTCCGCGGCTTGCTCGCATTCCGCTGGGTCCTTCTGA

          ATGTGTTACGGGACACACGGCGGCACACATTTTAAATCAATAATTGTCGATACACAAGGT
          GCGTGCTCGGGGGCATATGACAGCGCACATTATTTATTATTGACAGTCGGTGTCCCGGGT
          GCGTGTTTTGGAGTGCGTGGCAGCTCACGTTATCATTTACAAATGGTCGGTGGCCTAAAT
          GGTGACTCTGGCCCACGACCCAGATCACACCTAGTTTTAGACATTGCTGATGCCCTAGAA
          TCGCTCGTTCGGACATGTTGAGGCCCATCCTTATGCTAACAAACTGTCGCTACCTTGGGG
          CCTTCCCTTCGGACATGTTGCGGTTCATAACTACCCTGCAAAACGGTCACCGCCCTCGAG
          ATAAGCTACAAGTCGCCCTAAAATCTGAATATTTACCTAAGGGTACTGGCTGCCTGCATG
          ATCAGCTCTTGCACACTCGGCAGTCCGTATTTCTTCATACAACTAATTCATCATGACCTG

          CAAGCATGTGAATTAAACACGTACCGCCACTTAATGAGCCGTAAGGTGACATCAAGCTAT
          CAGTCATGTGACTCAAACATCTTCTGCTTTTAAGCTTGCCGTCAGGTGAGATCAAGCTGC
          CGCACATGTGTCCCGAGCACCTATCGCTTTCCAATTATCCGTCGGGGGATGGCAGACTGT
          CTGATCAGCATAGCACTAACGCACGAATTCCAATCTACACTCCAGCTAGCATTAAAAGAT
          CCAATCATATACACAATGGTCTTACGCCCTCAGCCAGGTTTGCAGATCGTATTAAGGCGT
          CTAATTGGTATCATGACTGACTACCACCTTCAGTTTACTCCTCAAACAGTATCAAGTCGT
          TTCACCCGACACGGATTGGAATGCCTTTTAAACGAGACTCTTGAAAACGTATTCAACGGC
          TTCTTCTGTGTTAGATATCCTTGTTACTTTTCCTTGATTGTCTAAGCGGTAACACAAAGA

          CGGGGCTGCAACGTCCCTTAGGGTGTAACCTCAGCTGTAGCGTTGACTCGTCAAGAGTTC
          CACGACTGTGGCGGCTAATAGGGTGTAAGCTCACCCACAGCGCTGGTTCGTCAAGTGTTA
          CGGGGCTTCAACCACCTATAGATCGTAATCTCATTCATATCATCGGCACGTCGAGAGTCC
          CCGAAGGTTAGTTCTCTTTATAGGGTCGGCCATTTCCACGCGCTGACCTGCAGGGGGTTT
          CCAAGATCCATTCCATACCAAAGGACACCATCCTCCACGTTGACGGCCTGTCTATGGCCG
          CGGCTCTCGATTCTTCACTAGAGTGTACCATCATCCACGTCGCAGGCTGTTATATGGGCT
          CTTCGTTTACCCGGATAGTAAGTTGTTCCCCAAGCGCGACTATAGGATGGGTAAGTGGCT
          TTACTCTAATATCGGATGCGTACGACGGGCACCACCCAGAGCTAAGATTGCCATGCGGCT

          ATTCGTGTAGCAACAGAAGCCAGTGGAATAAACCCAAGCAATAGCTCACACCGATGCCAT
          TTTCGTCAAGAGTTAGAAGTCAGCCGAATAAACCCAAGCAGTAACCTTTACCTGAGCCAT
          CATCCTGACGCAGTAGATGTCAAAAGAGCGAATCTACGAAGTAACCTTTATACGCGTCAT
          TCGGATACTACAAGATGAAGCAGAGCTGCCGCCGCTGACGACCGGCGATAGTTACTTTAT
          CCTGGCGGCATGCCTTGGATCAAAGATGCAAACTCAACTTTCCGTCTCTCGACACGTCGT
          TTTGGCAGCTCACCATGGGTTAACTGTGCAAATTCACATGGCTGTTTCGAGCCACATTGT
          GCTTTAGATATGTTAACAAGCTGCCCCACAGCCCGATACTGCAGGCCATGGGAACGGCGA
          AGTTCCGGAAAGGTAACTGCGCGCCACCTAGTATTAGCCAATGGGGCGGCAACGCTACTT

          TATGCCTTTTCTTCACTTCCCCGGTTAAATCGGCGCAACGCGCGGCCAATTTTTCTATTG
          TATGCCGCTTATTAAATTCCCCTACTATACCGGAGTGATGTAGGGCTAATTTTCTAATCG
          TACTTCGACTCCTAATTTCTCCTGTTAAACCGCGGCGATGTACGGCTAGTGTTCTTATTA
          AATATCACTTCTTACCTTCCCTAGTGACAGAGGTGTAACAATCGACTGGCCAGTCTGTCG
          CAATTCAGCATCTCGCCTCACACGCGCCGTCCCTGCCATCATCCGGCGCCCCCCGCAGCG
          TACTGCAATATTTCGCCTTATATGCGAAACGTGTGCGAATCTCAGGCTATACCGGCATCG
          CATGTCAATTTGTTCTTGCTCTAACAAAGTACCCCGAACTTATCGAGGGTCTATGTCGCA
          TACTCGAACCCGTCGTCACCTACGGAAGGCGGTTCCCAGGTAACGCTAAATCACAATGTA

          CGTGGGCGTCATCTCAAATTCCCCACAATCCGTCTACTAA
          CGCAGGTGTTTTCACGTATTATCCACTATCTCTTAGTAAA
          CGCACGCGTTCTCACGTAATTCCCAGAATCTGAGTACTAA
          CGTTAGCGCCCCTTGGCATTGCCTGGGGTCAGGATAACAA
          CGCTGGCGACGCCCCGCGCGTCACTAATTGATTACAACAC
          CGCCAACGCCTTCCTGCTCGCCGCAGATTTGCTATAAGAG
          CGTGGGACTTCGCTTTAGTCGGCAGCCATCGTATTTCTGA
          CGCGGGCAAGTTTGCGCGTTCCCCATTCTCAGGACTTTGT

