 8 1000
t1        CAGACATGAAACACGTGCGTTCACCCTGCACGTACGAACGGTACTATCGTGCACTAAGTC
t2        CCTCAACGAAATTAGCATGAGAGTTCGATAAGTGGGGACACCAGCTATACCCCCCGAGTT
t3        CCACTATAGTGGATCGGTAAGGACCCAGTAAGCGAACGAGGTACTTTCGAGTGTCGATTT
t4        CTTTCATGGTGTAGGGATAAGGCCTGAGCAAGTATAAGCGACACCGTCTATTGCCGAGCC
t5        CCCCTCGTGCATGAAATCTCTAGGCCTGCCAAAAGTCTCGTCACTTGGGGCTAGTACGGG
t6        GTCCTTTTATATGAAGTCTTTAGGTGTGACAGAAGTGGCGCCATTGGGGCTTATTACGAG
t7        TCACACCGGTACTTCGTCACTTCACCTACGGGGGGCACCACCCTTGCGGCCCAAGTAGAG
t8        TCGCTCAGGTACTATATTACCCGGCTTACTAGCGGCAACTGGCCCATGTCATATAAGGAG

          GACCAGCACCACTACATCATGCGGTCCGTATAAATACTCACTTAGCCTCTGAGCGCTTCG
          GCTTCGGAGCCCTATATTAGTACGCCGACACGGGTCACTTTACGGCATCTGGGTGTCTAG
          GAACAGCGATTCGCCGTTCCTGTGTCTTTGTAAAGTCGTCTACAGTTCCGCGGAGACTAG
          CAACCGTACCTCCGAGGACCTGGGTCTGCGCAAATTCATCCACAGTTTCTAGGAGACCAG
          AACAATGTGCTTGATATGCAGAACGCGGCTCGGACCCATTTTTGCAACACCGAAGCCTTG
          TAAGATGTTCTTGACGCGCAGAGCCCGGCACATACTCGTTTTGGCAACGAGGTAACCCAG
          TATAGTCGAATTACCGCATTCGATATTGCTCGAGTCTGTCTTTATTCAAGCGATGTGCGG
          CAGAAGCGCACTGCCGGAATGTCGCTTGACTCGGTTTGTGCCTAAGTCAATTGCGTGGGG

          CTCATAGAAACACACGAATTTGCAGTCTGTGGAATTGTCCGCATGTTGGAGCGCTGGCGG
          CTCGCTAATGGTCGTCCATACATGGTCCGTGGATCCGTCAGAATGTCGGAGCATTAGGGT
          CAGGGAGATGAATGCGAACATGTCGATCACTGGGCCCTTTGCACATCGGCGTTCTCGGAA
          CTCGGAGATGATCACCGGCCTGCGGCTTAACGAGCTCTTCGCACGATGAAGTACTTGGGA
          CCCAGACGTAGCAGGCGGTAAGGGCATTGGCATCACCAACTCGTGTTCGTATATTTAGCC
          CCCGGACGCAGCTCGCGGTATGGGCATTAACAACACCATCTCATGTTCGCATATCTAGCC
          TCTTGTTATCGTTGATAGAATATGACTTGTCGGCCTTCTGACCGGCATACGAGTTTAATG
          TCCGTCCGAGGCCGATTATACGTGGATTGTAGACTTTTCGACGGATTTGCGAATTTAATA

          AACGCCATTCCCGGCTGACACACCAGTTGTCACATGGAAGTATCCGAATGGCACGGCGCG
          GATGTAAAGCCTGGCAAGCGCTCCAGTCTTAGCATGGAAGCACGCAAACGTCATGGCGCA
          GATGCGCCCCATCGTGAGCCTTTCAGTCTTCGGGCGAAAAGGCGCCGTTGTCATGATGCG
          GATGTGGTCCATGAAGGGCCCCTCTGTTTTTGACCGAATACGAATCAATGTCATGGCCTG
          GGTTGTAATCGCATTGCGTTTGTACTGTCACCATACCTTTACATTGGAGCATCTAGTTAA
          AGTTGCAATCGCATCCCATTTGATGAACCACCGCAGCTTTCCATTGGAGCATTTAGCCAT
          GTCTCGGATATTGTAGTACTATCGAACTCCTGAGCGGTGCATTTAATACCTCCCGGGACT
          GAAGTAAGATTCTACGCCCTCTGGAGTTATCGAGTATTTTCTACTATACGACGAGGAATA

          GATTGCGTTACTTCCTGGTAATACTCATTCGGGCTCTACCCAATCGAATCACTCGCCCGA
          GCATGTAACTCCCCTAGATCCTGCCCATTTGGCCATACCTCCGCCGCGCTTTCGGAGCGG
          GGATTTCCTCATGAAGAGAAATGCACATTCGGTCGTAGCCACGTTGCGTACGCTGAAAGC
          GGCCAGGTTCCATAAGAAACATGTACATCCTGTTTTACCCAAGCTGTGCTCGCTGACCGG
          ACATGGGGATACTCGAAACAATGTAAACAAGATTTACACCTATCGATCCAGAACAAAGGG
          ACATGGAGATAATCAAGACATTGTATACCAGACGTACATCTATCTACCTCTAACAAAGTG
          GTATTGCCCTTCGTGGAGACCTACGGGCTAGAAAAGAGTCAAGCCACCCTAGGTAACGCC
          ATGACGTACCCCGCGGGAATGCGTGGGCTCGACGGGTTTTAAGCGTCCCCAAGCGCGGCC

          GAGTCATCCTCTGCAATGGAAGGTGCTTTTCACACTTCCAATGCGGACGCGTTTCGATGT
          AAGCCCTGCGGTGCCGCTGGAGGCGAAGCCTGCGCTGTCACTATTAAGGAATATAGAGGT
          CAGTCATGTTGCAATGTGAACGGCGCCACCCGCGTCGTCATTGAAACCAGAAGCGTATGT
          CGGGAATGTTGGGATACGAGAGGGGTCAGTTCCAATGTCTTTAAAGTGGGATACGGATGT
          AGAGCTTGATAACTTTTAGTGGGCACAACACGCGTAGATAGTTGAATTGGTACAGACATC
          AAAGATTGATAACAGCTAGCGAGCCCGACGCGAATGGAAAGCTGCTAGGGCAATAAAATC
          GCGAGTTTTCGACGCACGACCGGCACGACAAACTTAACTACGAAATAGGACCGTACGCTT
          AATCGTCGTTGGCGTGCGAGCGGCACAATTAGTCTCGCTAAAGGGAAGGATTCAAAGTTC

          GTGTGGCCGTGACTCACGTCGTCGTTGGTTGACCTAGTCAAAGGGCGCACCTATTCACAA
          GTAGAGCCAGGAGTTTGAGCGCGGCCGTTTGACGAAGTGCCCGAGTCCACCCTTCTATAC
          CAGAGCCCGGACCCTCCTGAGCTGTCGAGTGATTTCGCGAACGGACCTCTCCTACTAAAC
          TTAAGCCTGGGTTTTCCTACGTCGTCAGGTAATTCGGGCCATGGATTTATCTAACTACGA
          GCAAGGCGTGGGTTATAATCTTCACTGGGCATGGCACCCCATCGACTTGCTACTTTTGCC
          GCAAGGTGAGGGTTATAATAACTATTGGGAAAAGCACCCCATCGGTTTACCAGTTTTGCC
          GTTGAGCTAAGGTAATACAGGTTTTCAGCCAGACTAACCTTTAGATTTAGAACTCAAACT
          GTTAGAGTAGACTTATACGAATTGGCTGGCAATATAATCCTCCGACAACATCTCCTAATT

          CGACGCACAATGAGCCTTGGGGCCCGGAATGCGCTTACGCCTTGGATGACGTGGTGGGAT
          GGTAGTGCAAAGTGACGTGGGACCCGGCACGCACCCACGTCGCCGCTACCACGGCGCAAT
          TGGCGGAGAATCGGTAATGCGCTCCGCGACGCCACTACGCGGGTGTTACCGTGACGCAAT
          TGGCGGATTACCTTCCATGGACCCGGGCATGCCCTCAAGCCGATGATATCGCGGCCCAAA
          TAACGTACGATGTGGTTAGGCAGCCTACGAAGTCTAGGGTTGTGAACAGCGTGAATCCTA
          TGATGGACAACATGACCAGACGGCTCACGTAGTAAAAAGCTGTGCAAAGACTGAATGCCA
          CAAGGGGCGACGTATTTCGGTAGTAAAATCACCCGTAATTTGCGTATACTGACGATCGTT
          CAAATGATAACGCGCTCAGCTGGACAAGCTGTTCATAAGATGCGAATATGGGCGGTTTTT

          TGAATCGTCAGTTGAGTTAGAAGTTCCGCCCTGGGTCACGGGGATTACTGCACCACCAAG
          GGATTTGTTTCTCATGCTTAAAGCTGAACGGGAGACGAAGATGATTCTCGTATCAGGTCG
          AAAGATGTTAGTTGTGCGGTAAGAGAAGCACTAGCCCTCGATAACTACAACATCCCTCGA
          TAAGATGTAATTTGCGTGGCAAGCGAAATCTTAGCCACCGGCACTTACCACAACACCTGA
          TATGATGGAAGCTACGGAATGGAACCTGAGCACGCAGCCGAGAGACGATGTACTTGCCGG
          TATGATGGAAGCTACACAATGTGACTCGAGCTTATGGCTGAGCGCCGACGTTCTTGCCTG
          CATAGCGTAGATCCCAAGGTGTGCAGCGAGCATATTCCAAAAAACCCCCAAGTTCATGAG
          CACAATGATCACGATGATGCATATAGCGAGCACGCTTTGAAAGATTTTCGAGTGTGTCAG

          TCTGCACCCCCCATAAAGGCAGATCGCGGATAATGTTCCGTGGTATACCTTTGAGAGGTA
          ACAAAAACCTTTTTGTTGGCCGTTCGGGAGCAGAGCTTCTGAGGATCCCCTGGAGATGAT
          TTTGCATCCTTAAGGGTGACTGGTGTAGCACTTCGCTACAGAATGTACCTTTCAGAGGCG
          CTCATTCTCCCCCAAGTGTTTGGAGTAGCGTTTCGTTCAAGCGCGCCTGTCGCAGAGGAG
          TATTCAGGTATGGTAATGGATGAAGCTGTGTTGCGGTATTGACCTCTTTCCTCCAATCTG
          TTTTCAGGTATAGTGACGGATGCAGCTGCGTTGAGTCTTTGACCCTTCTCTATCCATTTG
          TTTGCAACCTTAAAAGCGAATAAGTCGGCTGAGGGCCGAGGGCGTTCTACTTTTGCAGAC
          GTTACAGCTTCAACCGCGGATGCGGCGGCGACGGGTTCTCGTGGCTTTTCTTCTTTAGAG

          TTTGAGCCGCCTGAGAGTGCGCGAGCTGAAGTTCACTACTTAGAGGGTTGTAGAATCAAG
          TTCGAAGTGCCAGGGCGTGCTGACGCAACCCGATTTCACCTAAAGGAGGGGAATATTTAA
          CCCTAGTAGTCCAGGCTCCTGCAGACCGAGTAAAATCCTTCAGAGGGGGCGAATGTCTAT
          TTCAAGCAGGCTGGGCTTTTACAAGCTGGCTTATGCCACTCAAAGGAGACGAGCGTTCAG
          GTTGGACTACTGGGATGCCCACATTTTTTACTACGTACGTACACGGACACCGATGCTCTG
          GCTGGATTGCAGGGATGATCACTCCCCCTACCACGTACGTGCATGGATAATGATGCTCTG
          TCAGATTCAACACGCTACGCTTGGGCAGTGTGCCTACTGCTTACATAGGAAAATGACACG
          ACAGGCTCACGCAGTTACCCATGATAAGCGCTTTTCCCAACCAACCAGGACAACGCCTCG

          GGAATTGGACTAGGGCGATGTAAAGGTGCTATACAGAGTTCGGGAGTACACCGTGGACGC
          GCATTTAGTCTATGAGAATTCAAAAACGCTGCATAAACTCTGAAGCTTCAGCCTGGGCAT
          GGGGCTAGTCAAGATAGGTATCTGATTCCTGGTGTCAACTAGCGTCCTTACTTTGGAACC
          GTACTTGGAGAAGGTGGATGTGAAACTCCTGTACCCTATTTGAGTCCTCACTCCGAGACC
          TAAATTTAACGGGAAGAGCCTTCAATATTTGCCCCCGGTCATTGTGAGTAACCCCGGGCC
          CAAATTGGATGGGAAGAGCCCTCAACACTTCCCCTCGGTAACCGTGAGTTGATCCGGGCC
          GGGGACTGTCTGGACTGCCCTATATAGCTCACAAATAGTTCGTAGACTCACTCGATAACT
          GGAAGCACTCTGAGCGCACTCAGACCGTTAATGCCCAGATAACACCATTTACTCGTTGCA

          TATTCATCCGTGGGAGGTGTCCGTACCATCGTTTCACTGGTCTGCTTAAAACGCTCATTT
          TACAGGTTCGTATCTGTTGCTCACATTTGCTTCTGCTAGGCCTTTATCAAACCCTATTCT
          TACTCTTCCACGTCAAGCCTAGATTTTTGGGCGCATTTTACACCCGAGAAATGCTACTAG
          TAGACCCTCATATCGAGCGTAGATCTCGGCGTCAACTTTGCATCTTCAGATGACTACTCG
          ACCGATGTTCTCTCGAGTGTTGTCACTCCCAATCACTACTGGTGTATCTCGTCTCCCATC
          ACCATTGTTTTTTCGAGTGACGTCACTCCCAATAACCACTGGTGTATCACGTACTCCATC
          ACGAAGGCCGAGATAGCAGTCGCTGTATACGCTTATCAAACTCCTGTTAGATTGTGCATT
          ACAACCGCTGAGGCCGGTATTACCACTTCTCCTCGTCCCCTCCACACTACATTACATATC

          ATAGCACTTCTCTGTATTAACGGTCCCCCAGGGGTCACACAACACCCCTTACAGATACCC
          AACGCTTCTATCCTCGGCAGGGGCTCCGATGTCGATACAGGTCGCTCCACGCGGGTGTGT
          ATTTTAGTTCTATTACTAGTGAGTCCCCAGATTGGTACGCGATTCTTTGCATGAAAAGAA
          AGTGTACTTTCGCCTCCCGTAGGATCCTACATTGGTATGTGGTTCTTTTCACGAGCAGAA
          GGTACAAACCCCGTTGGCGACGGGCAAAATACAGAAGCACGCACTCCGACTCGGTAGCTG
          GCGGAAAACCCCATCTGCGACGGGACACATTCAGCAGTCCGAATTCCGTCCTGGCAGGTA
          TGTGGAGACCGCACAACTGTCCAATTTTGTATAAACGGAGCTGTTTCGCACAAGCAAAAT
          TAAGCAGCCCCGAGAAATGGCCTAGTTTATATAGATCTTCAAGTCCCGCCACCGAAACAA

          GGCAAGTCTCAACTGTTGTGTGAACTCTAGTATATAAACAGCTAAGGAGAGACCTGTAGT
          GGTTTAAGAGGATCGACAGATGGGGTCGCCAGTTTAAAATGAGAAAAGGAAAACCCTTGA
          AGACACCTTCGAGGGAGCTATGACAATGGCTACTTAAACCGCAGAGGAGGAGTCCAGGTA
          AGATAGTCTCGAATGAGTCATAAATCCTATTGATTGAACTGAAGACAAGGGATTTAAGGA
          GGCTCACACCAGTCCAGTAACTGTGATGACCATCCGTATGTGCTCGGCCACCATCAACGT
          GACCGAGAACAGTCAAGTACCTGCGATGAGTACTCGTGCGCGCTCGGACACCATCAACAT
          GTACCTTGCTGACTGAGAGACAGTTTTTAGCAAAGAATCGCCTCTGACCGCAATTATCCC
          AACCATCGTTAGTTGCACTGCAGTTTTTGATCATGTTTTCCCTCTAACTACACTTAGTAC

          TCTTACCAAAATTTTTTAGCTACCAGGGAGGCAATGTTCCGGCCCTACCAGCTGCTTCTC
          CACTGATCAGTCTTGTTACTATTGAAGGAAGCAACCTCCTAAATCCACAAGCTGTATACC
          TATTCGCCCTACTCCTTAGCATCGGGGGAGGTCATCCCGCGAATCTCCGAAAGGTGTGTA
          TATTACCTGTACTCTCTAATATCGGAGATGGTGAGTCCCCGACAGTCCAGCCTGTGTGCC
          TATATTTTGAAAATCTCGAAAGCGAGGGAACTCAGGATCATAGTACTGATGATGTCTAAG
          TACATTCTGTAAAACATAAAAGCTAGGGAGCTCAGGATCAACGTCCTGATGATGTTTAGG
          GACAGTTCATAACATATAACCGTCAGGCATCATAAAGACTTAGTCTTACGGATACCCACT
          GATCGTAAATAATTCACAGTTGTTACGGGCGATAGGAACTCAGCTTCCTGCACGACTAAT

          TCCGTGTTTGATTGTTCATGGCTCGAATATGAGGGAATCT
          GACGCGCTCTAGAGTGCTTGCTCTCCTGATGCGAGATTTT
          ACTATGTGCCGTGGAATCTGTGCAGATTACAATGGCCCCT
          AACGTGTGCGGTGACTCTCGGCAACCTTGCAGTGGCGCCT
          TTTAAACGCAACTTTGATGAGTTTAGCGACGGTAGCGCCG
          TTCGATCATAACAGTGAAGAGGCGGGCGACGGTCTCGCCG
          TGCAAATGTAGTAGCTAGCCGCTCGCCAACGGTAGCGCCG
          AGCAGAAACAGCAATTAACTGTCTATTAGTTGTAGCCGCA

