 8 1000
t1        CTGTCAATATCTAATTCACTTATGCGAGTTGTTGGACGATTAACCATAACGCGGCTCTAA
t2        CCGTCAATAACTAATTCACTTATGCGAGTTGTTGGACGATTAACCATAACGCGACTCTAA
t3        GCCTCAGTAACTGACTACCTTATGCGAATTATTAGACGATGAACTACACCGCGGCCCTAA
t4        GTCATAATCACTGCCGGTCTAGGCCGAGTTATCTGGCGGTTAACCATTGCGCGGCTTAAG
t5        ATGTTAATGACCGTGGCACTTATATGTGTCTATGATTTATCGACCAAGGCGCAGCAAGAG
t6        TCGTGGGCTAGTTTTGTTCTTTGAAGTGCTGATCGATAAGAATTTCTGAGATGGTCTTAA
t7        CCTGGTTCAATGTTCAATGCCGTTTGGGGCGACCGCTGATTAGATCGTATAGGGACCCAA
t8        CGTAGCTTAATGCCACCCTTTGTGAGGACCTAGGAAAGCTGAATTTTCCCACAGCCTAGC

          GATTGATGTTATAGTCCGACACCGCACTCGCGCGACGCGAAGCGTAGCTCTAGCCTAACC
          GATTGATGTTATAGTTTGACACCGCACTCGCGCGACACGAAGCGTAGCTCTAGCCTAATC
          GAGTGATTTTATAGTCTGCCTTCGCACGCGGGACACGCAGACCGTAGCTTTGGCCTAGCA
          GAACGAATCTACTGACCGGTTCCCCGACCGCAGAACGTGAAGCGCAGTCCGGGCCGAACA
          TACCGGTATCCCAGGCCAACGACTCATTCGTGGGGCGCAGCGTAAAAATCCAGGAGGGCT
          GGTCAGGCATAGAGGCTACTGACTTGTGCACCGCAGTCTAAGCACGTTCACTTGCCAGTA
          TATCGTCACTCCAAGACATCGTATTGATCTTAGACGCTGGCCCTCGACTCGGGAGGTATG
          GGCACTTCTCAACCAGCCTGATCTCTTGAGAGGAAAACGATACGCGGCTCCGGGAAACCA

          CTTGGCAGCACATTGCATTTGTTGGAGATACCCCCCCATGTGATACACCAATGGGGGACG
          CTTGCCAGCACATCGCATTTGTTGGAGACACACCTCCATGTGATACACCAATGGGGGACG
          CAGGCCAGCATAACGCACCCTTTGGAGACGCACCGTCATGTGATAGACCAGTTGGGGGCG
          TCTGCTAGGGCAACGTACCCTTTTGAGGCACATTATCATCTGATGAAAACGTTAGGGGTG
          GCAGCTAACGTCGAAGTGTTCATTATATTTAATCTGCATTTTGAGTGCTCAACCCGGACC
          GGCGCCTATATGAGAAAATTTTCTGAGAATAACAGTCGTCTGTCTAGTCAAATTGGCCCC
          AGACCTAGTCCTAACGTAGCACCCATGATACACTGTCCTTAAATACGTCCCGTTCATGAT
          TATTTTATTTGGAACGTACCTTAATTATAATGCCACGATTACCTGATACGCGCCCTGGAT

          GACTGCCTGGTACGCGCTAATAGTCATCAGATGGAAGCTTACGTCAATGTGCGCGTCTGC
          GACTGCCTGGTACGCGCTAATAGTCATCAGATGGAAGCTTACGTCAATGTGCGCGTCTGC
          GATTCCTTGGTACGCGATAACAGTCACCAGATGGAAGTTTACGCAGATGCGCGTGTCCGC
          GCCCACTTGATATACGATACTATTCGTCAGGTGAAAACCTTCGTTGTCATGCGCGCCCAC
          TAAGCCCCCGAACCCATCAGTCAATTTGTATCTAGGATTCAGGTGATAAGTCACAACCAT
          TCACCACATGGTCATTCAACCGGCTTTCATAACGAGAACTTCACGGCTCTGTGTAGTTCT
          GACCCTTTTCATTCTCTCGTTGACCTCCGATACAACGTTAAATTTGTTCTGGACTGCTAC
          TAAACGTTTGATCCGACTATTAACCCATATGGCAAAATAGACGTGTTCACATGCCTCTGT

          GTTCAGGCGAGGGTACCGAAATGCATGTATACTACAAACACTCATGTCTGCAGCGACTGG
          GTTCAGGCGAGGGTACCGAACTGCATGTATCCTGCAAACGGTCAGGTCTGCAGCGATTGG
          GTTCGGTCAGGGGTACCGAGCTGCATGTGCCTTGCAAATACTTAGGTCTGCTGCGGATAG
          GTCCGGCCGCAGCTACTAAGCCACACATGTCCTGCAAACACCTAGGTTCGCAGCATCCGG
          GCCCGACCAAAACTTCGTAACCGCATACACGCCGGGGCGGCCCGTCCCCCTCTCAACTAC
          GCTTGACCATAGCCCTATCGCTGCTGGTACTACTTCGTCGAATGCACTGCTATAAGCAGC
          ACCCTGTACTTTCCGCCGTAAAAAACGACACCATTTAGGACATAAATCGCCACTACCCAG
          CCTTTCCTCTTGCGACTGTAACTCTTTAGCTACCACGGTAGGTGAATAGTTGTCGTCAGG

          CCCCTGTTTCGACAGCCGTCAAGGCCCCGATGCAAATGGAACTTGGGTACATAGGAAAGA
          CCTCCGTTTCGACAGCTGTCAAGGCCCCGATGCAGATGGAACTTGGGTACATAGGAAAGG
          ATCCCGGTCCGACAGATGTCGAGGCAACGGTATAAACCAGTCATGGGTAGATAGCAAAGG
          CTGCTTATCCCTCCGATGTTAACGAGTCGCTTCCAAACCGGCTTGAGCATATTGGAAAAG
          TGCCTAGAAGATTACTATTTAACGAATTAATGTTGCACAAGTTAGACTCCATGTTGAATG
          TTATCACCTTATACCGCCTTTGTGTGACAGCTCTACCACGGTTCGGTGGAACATAGTATA
          TCCTAAAACCAGTATCAGCTGTAGCTCTATTACTCTATCGGATCAAATCTAAGGTATTTG
          TTTTGGGCTTGGTACGCCGCTGAATTCGAGGACTTCGTTAGCACGGAAGCTCACTAAGTG

          CTGCGGTCTTGCGCTCAAGTGGGTATGGAGAAAGCGCGCGCTTAAGAACCAGTGCCTGCT
          CTGCGGTCTTGCGCTCAAGTGGGTATGGAGAAAGCGCGCGCTTAAGAACCAGTGCCTGCT
          CTGCGATTCTGTGCTCAAGTAGCTATGCAGAAAGCGCGCGGCTAAGATCCCGTGTCTGCT
          ATGCGGTAAGCCGACCTAGTCAGCATAGAGAACGCACGAGTTCAAGAGCAGATGGTCGAT
          CAGCCGTCTAGCGTCGAGGGCGGTGTGGGACGTACTTAAGCCTATGAGTGAGTGTTCGTA
          CAGGGAGATGTTCACAATCCCGATAAAGGACGCATCATTGACCGCACATGGACTATGGTC
          GCTCAAACTGCAATCTAGTCCAGTATGAGACTTGCACATACCCACTAATGAAGTCAGGGA
          TCGAGTCTTGCCTCCGGACTTCGAAAAGAATATGATTGCGCTTATAGCCTAGTCGCCACA

          GTATAATCATCGGGTGTAAGACGGCCCGCGGTGGGATAGGGGTTCGTCGCTGGTGTTAAC
          GTATCATCATCGGGTGTAAGACGGCCCGTGGTGCGATAGGGGTTCGTCGCTAGTGCTAAC
          GTCTCATCATTGGGTGTAAGACGGTCTTTGGTGGGATAGGGACTCGTCGACTGTGTGAAC
          ACGTATTCAGCAGGTGTGAGACGATTCGCGGTGGGATGGGTCTTCGTCCCCTATGGGAGG
          GTGTACTCATCACATGTCGGAGTACATGCATCCGCGTAGGGCTGAGTGGCTGGGGTGACA
          CTGGGCCAGTCGGCTACCAAGATATACGTGTTAACGTCTTCCTTAGATACGGAAGTGGCG
          TCACCCTCAACGGCAATTAAAGCCTGAGTATAGATACAGGGCCGTATCGTAGTGATAATG
          CTAGGTAAGCGCGTTTATTGGTAAAACACGCTTGCATCCTGAGGCCGTGACGAGATGTCA

          ATGCGGTTTAAGGACAACGGGTACACATCGCCTTCGTGGCCGAACTGCTTTGCCGTTAAA
          ATGCGGTTTTAGGACAACGGGTATACATCGCCTTCGTGGCCGAACCGCTTTGCCGTTAAA
          ATGCGGTTTGAAGACATAGGGTATATTTTGCCTTCGTGGCCGAATTGCTTTGGCATTAAC
          CTGTGGTCTAGGGACATCCGACCCCGCTTGCGTTCACGGACGCCATGGTGTGGCGCCCAG
          CGGTCGTCTAGGGCTAATAGATGACCGCCGGCGTTATCCCCGTATTACGCCGCAGTGAAT
          TCATGTTTTTGAGACGAACCCGTACCGACGAACCGTATCGCATTTCATTACCACAAGATG
          TAGTGGACTACGGCCGGATTGAAAACGTTGATTCGAAAATGTCTCGTAAACCGAATAGCT
          CGGCAGTTCTGGGCCTATCATAATACCCTGACCTTATACCCGTAGCACTGAGACATGTCG

          TCTCGGTGGAGGGCCTTCGGATCTCTCAGTCAAGTTTAACTGGAGCGGCCGCTACACCTT
          TCACGGTGGAGGGCCTTCGGATCTCTCAGTCAAATTTAACTGGAGCGGTCGCTACACCTT
          TTACGGTAGAAGCACGTAAAATCTTTTAGACAAGGTTATCAGGAGCCGTTTCTACTCCTT
          ATACGATGGCAAGACTTTGAATTATTCAGTCAAGCCTAAACCGAGCGGTCTCCACACCTT
          CGGTGGTCGGAAAGAATCATCCCCGTTAAGGTACCACAATGGGAATAGTCTTAACGTTTT
          GAATAGTTCACTACTCCCTTATCTCCTAGATAAATAAAGCTCGTGTGTCCCGTATGGCTC
          GATCGGTCTATGAGTTTCTTCTATGCCTGGCGTCCACGTCTCCAGGTACTCGTCTGCGAC
          TGACAGCGTTTGCGCCTCCTTGTACCGCCATCTTTCTGATATGCATGAACTATATTTATC

          TTTGAGCGACGAAATTGGGTTATACAGGATGCACTGCCCGCATTTAAGTAGCCAGCCAGT
          TTTGAGTGATGAAACTGGGTTATAAAGGATGCACTGCTCACATTTAAGTAGCCAGCCAGT
          CCTGAGCGACGAAACTGGGTTCGACAGGATACACTGCGCAAACTTATCTAGGCTATCAGT
          TTTAAGTGACGAAACCGGGTTGTATAGTGTACATTGCGTAAATGTACGTAGCTCGGCAGA
          GCATGGTTTCGTGTACAAGACACGAGGAATATATAAGACACCCGAAAGAAGTGCGATGTG
          AGCTGTTAATCATTTAAGGTCTTGTAGTGCCCGTTCCGATCTTGGGGGGGGTTCAACAGA
          ACCCCTCCAGGATTATAGGGCCTAGAATTCACGTCTTAGCCCCGCAGGGATTCCTACGAT
          ACCGTCAAGTGGGTCCGGGTGTAAAAACGTAGTCTGCCGCCGGGATTGGACTGCGTTGGT

          GTCCCCTGGAGTGGCCGGGCTTTCTGCGCGAACTAATCGACTACCCGCCTTGATACAGGT
          GTCCCCTGGAGCGGTCGGGTTTTCTGCGCGAACGAACCGGCTACCTGCCTTGATACAGGT
          GTACTATGGAGCGGCCGAGTTTTCCGCGAGAATTAAACTACTACCTGCTTTAAAACATGC
          GACCTTTGGATCGGCTGACTGTCCCCTGTGAACTAGCCGGCTGCTTGCATGCAAATGTAC
          ATGCGTTGGTAAAGTGAAGCCCACTGTCCGCGCCAGGAGACTGACCGTGCAGATGAACGC
          AACCTGAGCAAGGGCACTCGTTCCCGTGCGAAACGGAAACTTGCCATCTCCGATAAGCGC
          CGTACCGAAATGGAGGTAGATGCCTGCGAGGAATGGGCGGCTGCCGAGGATAGCGCTTGC
          CAACCTATGAATAAATAAACACCCGGCGCGCACTGGAGAGTTATTGATACACATGACCGA

          CGGGGGGGTGTACGTATACGTCACAACCCGGACATGTAAGGAAACACTCTGCTTCGACAG
          CGGGGGGGTGTACGTATACGTCACAACCCGCACATGTAAGGAAACACTCTGCTTCGACAG
          TGGGGGAGTGTACGTATACGCCAAAACCCGGCCATGTGAGCAACCACACTGCATTGACCG
          GGGGAGGATGTACGTCCACGGCACAACTTGTCCATGCCATTAAGCCTCACAAGCCGGTCG
          CTAAGGAATGTCTGTTTACGGCACAAATCGATAGAGTAATGAAGCCTTATGACGCAAAAG
          GAGGGGGACGAGCGTACATAGTGCGTATCGATACAGCTATCCAGTGATTACAAAGGTCTG
          AGGCTGTACCCACAGTCATGCCACCATCTCATGAAAGCGCGCGGTCTTGAAATAAAGAAA
          CGAAGGAAAAGATGGCCGCTATTCCATACAAAATAGCGGCGGGACTCTTGGAGCGGGTCT

          TAGCAGGACTTGGCGGGGGGCAATCTACGTTGCGAACTCCGCTATTACATATTCCATAGT
          TAGCAGGCCTTGGTGGGGGGCAATCTACGTTGCGAACTCTGCTATTACATATTCCATAGT
          CATCAAGCTGTGGTGAGGGGCGAACCATATTGTGAACCCGACAACTACATATGCCATAGT
          TATTAGGCCTTCGAGAGACTAGCATCACGGCCTGGATTCGGTATCGACAGAAGAAGTACT
          GACTACTTTTTTGGGAAACGTGCGCCCTGCATCAGACTTAGCGCACTTATGCGCAGTAAT
          TATCCGCGTTAGACATCACGGGTTTTATATGTAGGGATTGGTTGTTCCAGGTATACATCC
          TGTCACGAGTCTGAGCCAAACGCGTTCCCTTTTGAAACAAATGTCCATGCGTGCGGTTTG
          GACTAGCCTCATGGTTCCAGTGCGGTCCCAATTACAAATGCAAACGCCAGCTGCACTCCT

          ATTGATACTATCTCCAAGAAGATTGTGACTTGAACAGCTGTTTCAATTACTAAGTCGTTT
          ATTGATACTATCTCCAAGAAGATTGTGACTTGAACAGTTGTTTCAACTACTAAGTCGTTT
          ACAGATACTCTCAACAAGAAGATCATGACTTAAACGGTCGTTTTTACTACTCAGTTGCTT
          ACTTACAGTCCTTAGAGGAAAATTTCAACTTAATCGGTTATCTTCGCTACCAAACTTCCT
          AGATATAACAGTCGTTATTGTATCTACATTCAGACGGTCGATTCTACACTCAAGTTACAG
          AGCGATGAAATTTGTAGTAATTATTCTGCCCGCCATATTGTCACTCTGCCCGTCCCCTTC
          TTCGAACGGACCCATGGTCGGTCTGTGACTTCCAGCGTTTTCGTGTCCTCTAAGCGTAAC
          TTTTAACCCATTCCCCAGTGATTTTCGTAGTGCTTGAATGTCATTCTAGAATAATCGTCC

          CTGATACAGCAATAGAGTCAACTAATCAGACACGACATCAGCGACGGGGAGCGTAATTAC
          CTGATACAGCAATAAAGTTAACTAACCAGACACGACCTCAACGACGGGGAGCGTAATTAT
          TTAATACAGCGACAGAGTTAACTGATTATGCACGGTATTAATGACAGAGAGTGTAACTAT
          CTAGTGTGGCCATTCTGGTAACTACTCAAATGCCGTGTTAAGGACTGGATGTGTATTAAG
          TATCTGCAACGTTCCGATGGTTTGACAGTATCGAAGAACATCGTTTTAGAGAACGCTTCA
          GCCTTGTACTACTATGAGTAAACGGCGACACAAATTGCTTTAGTAACATAGCTGAGTAGT
          TTTCTGAAACCGTAGAATACATACCAGTAGTAAGATTCCGTTAGAGTTATGTATGACGCT
          CCCTCGAGATCTCATTCCGAGTAACGGTTCTTTTCCGTTACCGGCGGGAATTAGGGCGGT

          GCACAGCTTGTATCGTACGAATTTACATTCGCGCGTTTAG
          GCACAGCTTGTATCGTACGAATTTACATTCGCGCGTTCAG
          GCACAGCTTGTACCATCCGTATTTACATTCTAGTGCTTGG
          GTATAGCCCGTACCGCTTGAGCCTATATTCCCGCGGTCCA
          ATAAAGCGCGCAACATATCGTCTGACCGTTCCGTATCTAG
          TCGTGATTTGTTTTGTTCGTACTAACCACCTAACCCGACC
          TCAAATTGTAATCTACCAGTGCAGGGTTTTTTGCTATTAG
          GCGTGGCGCATGTAGCTGTATGCCTCGTCGACCATGGTTA

