 8 1000
t1        TTGTACGGACATTTTGGATAAACTTAGTCAAGTGTACTGAAAGCTGCACTAGACGTTGCA
t2        TTGTACGGACATTTTGGACAAATTTCGTCAAGCGTACCGAGACCTGCACTAGACGCTGCA
t3        GTGTGCGCACATTTCCGACGTATAAAGTCGTCAGCGTTAGTCGTCGATATCGTCGCTCAA
t4        TCATGTGTGTACTTTTCGCGTAAAGCGTCCTCACCACTACTAATCGGTTATGGCCTCGTA
t5        TCGCATAAAACCGCGCCACTGAATGAAATGGTTATTCCTTTGAAAGATCTAACCGCTAAG
t6        CCCCGGGGAAATTCCCAACGGGATGAGGCCGCCCGATACTAGGATCGGCTGCGCAGCAAA
t7        TCGAGAAACCTCGGCTAGTGACACGAGATTCCTGTAACGAGGGCCGAAGGTGACGTGATG
t8        ATGAACACCCACTCTTAGTAGAACGCGTCCCTTATGTTGAGGATTACAGATGGCGCAGCG

          TATGACCAACGCTAGGACGAGAGCCTCGCATTTGTCGCTCGTTACTTCCTATTCCTTTAG
          AATGACCAACGTTACGACAAGAGCCTCGTATCAGTCGCTCGTTACTTCCTACTCCCTTAG
          TGTGAGCAGTTGCTGACCGGGGGTCTCATAATAACCATTTAATCGAGCATCGCTCGCGAA
          TGCGAATCCCCCTCTGGGTGCTCCGATGTTCCAGGTGCAGACTAATGCAATGTACAAAGA
          GACGTGGCCTGGCTATTACGCCATTCAGCGTTTACAGAACATTTCCATTTGCGTTTTGAT
          CAGGAGTTATTGCCGACTGGATGTTTAATATTCCTGTCGTATAAACGTGTAGCGGAGATG
          GGAGGCCTTTAACCCGAGCGCCGCTAGTTAGTAGTTGGCCTATGTTCGAAACCACAACTC
          GTGACTTTACGACTCGGGCGTCGTTAGGTATTACAAACAAGGAATCAGACATTGCAAATG

          TCGAGTAAGGTACAAACCGTGGGTGCTCCTGCAAAATTGATTCATCTCACAATACGTGCA
          TCGAGTAAAGCACAAAACGTGGGTGCTTCCACGAAATTGATACATCCCACAATGCGTGCA
          TAATGCTGTGTAGAACTGTAAGGCATGTACGTGAAAACAACCGCTTTAGTACTCCGTGGA
          CATCGGACTGTAGGCGAAGGCGACTTGTATTTATCCCCGATAGAGTCGGCGCCCCATTTT
          AGGCGAAGCGTCAAATTAAAGGATGTCACAGAACTATCAGTAGATGCGGAATAAAGTCGG
          TAGCGGAGTTGTCGGCCAAAGGACGCCCTCGCTTCCATAACCGCCGCGATGTGACTCGTA
          TAGCGGCGTAACCGTACAGAGCGCGCGCCCGGGCGTTTCACTGTCTCGCGATTTGATGGC
          TAGCGGGGTAAGAGCATAAAAGGCAAGCCCGCGAGATTGACCCTCGCAGAACCTTACGGA

          GAGCGAAGTTCCGTTAAGGCTTGAAAAGTTCTATGCTTGTTCTCCAGTGGTCCTCTACGT
          GCGTGGAATCCCGTTAAGGTTTGAAAAGTTGTGGACTTGTTCTCCGGTGGTCTTCTACGT
          GCATGCAACCCCGTCGAAGCTCGACGGGCTTTCCACGCTCATCATGGAGGTCTTTTCCGC
          ACCAGCCCTTCCTACTGCCTTTGGTTAAAACCACACCTGCCCGGGTATGCGAGAATAAAC
          TGAGGAACTTCCCTGCGCGACCAACGGTTCTTTATTTCATCATTACTGAATTCCGCCGCT
          GCGCTCAAGTACATCCGCCTCCCTTAGACACCGTGTTCTTCTCATCGCGTTTCCATGTAA
          ATGTGTAACTAACGCAAAATTCGAATAACCTCTTCCTCGCTTGATTAGACGAGGCTACTC
          CCGTTTCGCTCACTTAGACTTTGATGAATCTAACATCCACTTGGCAGCAGATGGATATCC

          ACTGTCGTAACGATGTCTCTCTCTCCCTTGGCGATGGTTAGGTTGCAAACAGTGCACAAT
          ACTCTCGTGACGTTATCTCTCCCTCCCTTGGTGGCAGTTAGGTTGTAAACAATGCACAAT
          GCTGCAGTAGCTCTGCGTCAGGCGTTCTCGGAACGAATCGTCGCCGCAGAAGCTAATAGC
          GCCAGAGTGATCAGTTTCTCCTTTTTTTAAATAAGGGAAATGGTGATAGAATCTCGCGCT
          CCTCAAGCAGCCATAACACCTACTTCTATCATGATACTGAAGATGACATTTACCAGTCAT
          TATGAGTGTGTGGTATTCCAGTTCCTCGCACCGGTAATGACGACAACCTGGGGCACCGGT
          GCCGAAGTGTCAGCCCCTGCGCTTATTAAAACCGCGTCGACACTGGTTGGGCCTATGGTT
          CCTGGGGTGACAGTCCCCACCATTACTAGATCGGTCCTGCCACTGATAAGGCCTGCGGTC

          AGATTTTTATTATGAAACGCAACTGTGCTATCTATTTACACTCGCTAGACGCCAATATCA
          TGATCTTTATCATGAAACGCAGCTGCGCTATCTATTTACACTCGCTAGACGCGAGTATTA
          TAACCGTTTTGCAGTATTATGGGTGCTCCATGTACCTTCGCTTGATACAAGCGGAGATAG
          AGATCAGGGTGAGACAAGTCTCGGCCTTTACTAGCCTAGATGATAGTTGTTTAGATTCTC
          CGCCCGGCGATCCCTAGACAAGCCGCAACGTCTGGGACAGTTGGACCTGTGTTCTTGCTG
          TAGTCTAGATACTGGATAGACGCCACTACACTTACAATTAGTTAACTAGCGGTAATAGTC
          CCAGTTCTCAAAGGTCCGAGAATATCCAAACCTATTTGAGAAAGTCGTGTGTTTGCTTTG
          GGGCTTACGGCAAATGCCAGCGTATTTGTGTTTATATAAGATTGTCATGAACTGGCGAGG

          AGCTCCCAGCTCAAGCAACGGGATACGTGCATACTCCTTGAGGGCCCTGACTCGTGCTAG
          AGCTCCCGCCTCAAGTAACGGGAAACGCGCATACTCCTCGATGGTCCTGACTCGTGCTAG
          AGTCATCAACGCACTTAACAGTAATCACGTGCCATTCCCCAGGACTTTACGGCGTGTCAG
          CCTCTTAAGGTACCATGCTGGCTGGAATTTGCTAAAGTACGAGGCTATCAGGTGCGTAAA
          TCTCACGGCAACGGCTCGCAGCTAGTCTGTAACTAGACTATAGGGTTACTCGTGTGCCGG
          ACGGCCAAAGAAATACATGTATTTGGTTCGCTCCCCACTCAGAGCTTCAGTTGCTATTGG
          TTCTGCGGAGTTTCATTAACAACGTAACCTGTCCTCGCGTACGGCTAACACGCGTGCAGA
          CAATACAGACATGTTTCAATTACGTAGTCTGCCAACACGTACCGTTAACTCGCCCGCAGG

          GCGGCACTCGTTCTGCACTGTCGCCTGGCTTGTTATACTGCCTGTTTGGAAACGGTACCG
          GCGGCACTTGTTCAGCACTGTTGGCTGGCCTGGTATACTGCCTGTTTGGGAACGGTACCG
          GTGCCTTCTCTACAAAACGAACGACTGGTTCATTATCGCCCATAGCAGTTCGCGAGGCCG
          ACCGCTTGCGTGCCGCGTTAGCGGTCGCTTTCAGTAAGCAAGAATCTAAGCAACCTGGAC
          GCCAATAGTCTCCAGAACTGACCATGGTTTCAGTATTGAACCTGAATAAGTACTTCACGA
          AACTACTATACATTGGATCAGAAGCGGGTATGGTGGTGCTCTTCCCCTCGGTAACGAACC
          GCGAAGTCCTTAAGAAGAAAATGGATGCTTCTCCCCACCACAACTCGGGCGCCATTTCGG
          CCGCTTACCCAGAGTTGGGGACAGCCGACCCTATCTCTAACAAGCCCCGGATTACTCAGG

          GATCGGATCCCAACCTAGCGGGCATCTTCTTTTCCTAGACTTGAGGAGCTTATACTCAAC
          GATCAGATCCCAACCTAGCGGCTCTCTCTTTGTCTTAAACTTGAGGAGCCTGTACTCAAC
          GATCTAATCTCTACGTTGCGGTTGCTCTCCTGTTTTGATACTCAGGCGCTCTTAGCTAAA
          AATTAGTCGCGAGCAACGGGATCATATCACAACGACTTAGGCTTCAATCGCGTAAGCTAC
          AGAATGCTTTGAGAATCTCTCCTCCACTCCGTCGTATGAGCTCCCGAGCCCGTTACCCGA
          GGGATATTTTCTCGTGCCCGGCCAGTCCACGAGTTGCCGTCGTCCACACATTATGCCTGC
          GTAAGGCCAACAGGCTCTCAGCCAGTGCACGCTTCTCTAGTTAGTATGTAAGCAGTCGAC
          GCAAGGCCAGTAGGTCATCGACCCGTGAACACATTAACAGTTACTATGTAAGCGGGATGT

          CACTCCTGCCACGTGCAACACATAACTGGCTCAACATCACAACACATATTGGACAAGCAC
          CACTCCCGCAATGCGCAACACAGCACTGACCCAACATCACAACACACATTGGACAAACTC
          TTCTCGCGGCTTGGGCCCCGCTGTACCCTAACAACGTTACTACCAGGATAGGACAAACAA
          CTAAATCGGGGCCGGTTGTGAATCATTATCTACGCGAGCTAGTCAGCCATTGACAAACAG
          CTTCAGCCAGCTTTACACCACATGCACGTTTCTAATGGTCAGCCCGTTCATGAATATTCC
          ATCTGGCCTATTCAAGATCGCCAAGTCATCCTCACAGAAAGGCATCATTCAGCCAGGTCA
          TTCTTGAGCGCTGTAATCTTCCGCTGTATGGGGGAGTACAAAAAAAAGTTAGCCGCACTG
          TACTAAGGCGGCGAATTTTCCGGCGATAATTCGGGGCGGCACGAAAACACAGCTGCACTC

          AATGTCCGAACCGCTGCTGTCTCGGTCAATTCATTGTGCCTTCCATGCCTATGGCGAAGA
          AATATCCGAACAGCTGCTGTCTCGGCAAATTCATTGTGCCCTCCATGCCTATGGCTAAGA
          ACATATTGACTAATCACCGTAGCGACGCGTTAAGCTGCTCCTATGCGCTGGTGTCAGAGA
          TTCTGACCCATGGACGGTGCTACGTAGGGACAGGCACCGCCAAACTGCCTTTGGCAGAGA
          TTAGTCCTAAAGGTTCCTGTACCAAGGTAACAATGCTTCACATATGCTATTTGTTAGAAA
          CAGAGCTTGACCTTCATCGTTTTGGGACGGAGCATCGAACTGGCGAACTTGTGGTATAGG
          CTATCCCGCTTGGTTACCATACTAACACGAGTAAGATGTTCCGCACCCCCACAGTAAAAA
          CCATTCTGCCCAGCCGTTACCTCGGCAAAAAGAACAGGTTCCACCTTTTCGTGGCACTGA

          GTAGAACTTTGAGTTGCCTTCGATCACGCACCTTACACGATCCGCCTATGTTAGTGTGAT
          GTAGAACCTCGAGCTGCTTCCGATCGCGCACCTAACACGATCCGCCCGTGTTCGTGCGAT
          GCAGCACTTAGTCACGCTGTCTGAAGCTGGCCCGAACTGGCACACTCGCGACTCCAATGA
          GCTCAGCTTACCATTGGTGCACTGACTACTTTAACGACAATCCCGTGATGCTTGCCACGG
          GTTACATGCAACCGAACTTCCTGGGGATCAATGAAATCACTGCGGCTGTAGTCACCAATC
          GTCTGACCCGGCGGACCAAACTGATCGTTTCATAAAATTGCCTATGTGTGGACGTGACAG
          GACAATCATAACTGATTTGTCCACGGTCCGCTGCGAAAATCAAACCTTCAACTGTGCGAG
          GTTAAGTATACCGTCGCCTCATTCGGTGCGTTGGGAGCGGTAGATGATGTACCGCGTGAG

          CGAATTTAACTTCACCTCATGCTATAAGCACATTTGTGTCGTGCGGGGGACGGAATAAAG
          TGAATTCAACTTCACCTCATGCTAGAAGCACAATCGTGCCGTGCGGGAGACAGAATAAAG
          TGAACCGAACTATACTTTTTGTTAAATGAGGCCCCGAGGCATAGTAATTACTGTATGTAG
          ATAATGATAATTCATGGTTCACAAGACGGGATGCCTTCTTAGTCAGCCGACAGTTGCATA
          GTTAATGGCTTCTGCTAAAGATCTCAGGGGGAGGGCTACAATAATCGATGCCTCGTGGCC
          TACTGTGGGTTCTGCCAAGTAACGGGGCGGCCAAGCGCTTGCTTCGATTCCGGGATTACG
          AAAGTCGTGTAGAATTGCATGATATGAGGACTGGGTTCACCTGCGGTTGACACTCCCCTG
          CATGTTACGTATAAGCGCACGGTAGAGGGCCTAGGTCGGACTACACCGCACCTCCTTGTG

          ACGTAGAGTCTAGAAATGACCCGGGGGTCGTCTCCGGCGTTAAAACGGAACTATTCGACG
          ACGAAGAGTCTGGGAATGACCCAGGGGCCGTCTCTGGCATCACAACGGAACTATTCGACG
          AAAAAACGTCTACAACTGCCTTAAGGGTTCATTCTAATGTACCACTTAAAATGACCGACG
          AGGGCAAGCTAAACCCAACTGCGAAAGCACCCTGTTATATGTGACCCGATATAACCTTCA
          GGGCCGTGATCTTGCATTACCGCGAGGGAGTTGATCGCATTCCAATTAATGTATAATACA
          CCCCCGGTAGCTCTCCGCGTGAGGGGGCCGCTCACAGGAAGCTGAGTGTGAAACCCCAGG
          GGGGCGATGCTGTATCAAGCTAAGGGGTTACTCAAGGCATGTTTGTCGTTAGAAGAACGG
          GGGGCAGGTCTATGATCGCGGCCGGGATCGCCCAGTCGATATTAGCTGGAATAGGTACTG

          CTGCCTTCTAACAATAATCTCGATAATCATGTTCAACGGACCTACGGACTAATCATCAAA
          CCGTTCTCTAACAGTAATCTCGATAACCATGTTCAGCGGACTCACGGACTAATCATCAAA
          CCATCATTTTATTGTATTTTGAATAGCCGAAACCAGCGCATCTTATAGCCAAGTACCTCA
          TTTACACTTCGTTGTGTTTTTATGCTCCCGGACTAGCGGGGTGACGTACACAACAAATGG
          ACGCGGCTAGGTGGGGCAGCAACTCGCTCATTTTAGAGGAACACCCGGCATTATTTGTTG
          GGCACAATGGGTAGTGCTCCCGACTGCCGATTGTGTTCAATTGATAGAGACACGGGCCTG
          TCCCCCTTCTCTGTCGTGCCGAATTGCTACATTCGCCGGACTTATACACTAAATCATGGT
          TCCCACTTCGCCGACTCACAAATCAGTTAAGATTAGACAAGAAAAACGCCAAGTTAAGTC

          GCATACTTACGTGACTAATAACCGAATAATATGAACACAGCATATCAGTGTTCCCGTCCG
          GCATGCTCACGAGTCTAATAACCGGACAGTTTAAACACAGCGTATCAGTCCTCCCGTCCG
          TGACGGTTTCACGATTAATAGTATGATAGTTCGAATGCGACGCCTGAGTAATTCTGCACG
          ACCCGGCGACACACGAAATGGCGCGGCCCTTTAGTTAGCACGCTCGATTTCCTAGGTCAT
          GCATGATTCCCAGACGGAAAAGCCGTACATCCGGTGACTTCACTCAAATCTACCTCTCAG
          GCAAGGTCCTCCAGGCAGAAACTTAAGTCCCCACACTCGGCGAGCCGACACATAACCAGC
          ATATAACCTACTGTTCGGGTATGGGAAAACTTAGTTGTTATGTCCCTGCGGACCAGTTAT
          TCATGGTCTTATGCTCGGGCACCGGACCACTTAGCAATAGCACCCCGGCGGCTTAGTCAT

          TGCGCCGGTTGGTACGCCACTAGTTTGACAATTAGGTCGT
          TGCGCCGGTTGGTACGCCACTAGTTTGAAAATTAGGTCGT
          TACACTGGCAAGGAGCACAGGTGCCCGTCAATTTAGCCGT
          GCGGAAAGAGAACATAATATTGAACTACTGTCTTCGTATG
          ATTGACTGCAAGGAGGGCAGCGGTGTGCCAGCCCGACCGA
          CCTTATAATTACCCGTACCACAGCTTGTCAATGTAGTCAG
          GCGGGCAGCGGGGAGCCAGCCGGTCTTAGTCAAAATTTGA
          GCTAATAGTGAGGAGACTGTCAGGGTACGTGCTAGCTCAC

