 8 1000
t1        TTACCCTCCCCTTGGCATGATTATCGCCAGGTCCCGTTAATACTCACGGAATCCCACTCA
t2        TTACCCTCCCCTTTGCATGATTATCGCTCGATCCCGTTAATACTCACTGAATCTCACTCA
t3        CCGCCCTCCCCTTCGTATGATGAGAGCCCGATCCCGCCAATATTTACGGAATCCCACTCA
t4        TCGCCCTCCACTTTGCATGATTAGTGCCCAATCCCGTCAATATTTACGGAATCCCACTCA
t5        AGGTTTTAAGGGTTGGGGAAGCCGACACTAAGGTTGATTGCATTTACTAGCCCATTTTCT
t6        ATGTATAAAGGGCTGGGGAAGCCGACACCAAGGTTGATTGCATTTACTGGCCCTTGTTCT
t7        ATGTTTAAAGGGCTAGGGAAGCCGACACCAAGGTTGATTGCATTTACTGGTCCTTGTTCT
t8        ATGTTTAAAACGTTCGTGGAGCCGACACCAAGGTTAATTACATTTACCGGTCCTTGCGTT

          ACTTGACAACCTAGCTTTACCCTCAGCACCCTATGTTCTCACCTGCGCGTTTACCATGTG
          ACTTGACAACCTAGTCTTACCCTCAGCATCCTATGTACTCACCCGCGCGTTTACCATGTG
          ACCTGACAACCTAATCTTCCCTTTAGCACCTTATGTACGCATCTGCGAGTCTACTATATA
          ATCCTACAACCTAGTCTCACCCTTAGCACCCTATGTACGCACCTGCGAGTTCACCATGTA
          CTCCCAGTCAAAATATACCCGACTCATTGTTTGCCTGTACGCGAATGAACAGTACGATCT
          CTCCGAGTCAACATATTTCCGACCCATTATTAGCCTGTACACAAATGAACAGCGCGATCC
          CCCCGAGTCAAACTATACTAGACTCATTGGTTGCCCGTATACTAGTAAACTGCACGTTCC
          CTCCGAATCAAAATATATTAGGCTCTTTATTAACCCGTACACTAATGAACTGCCCGATCA

          TAGGAACGTCTGAACTAACCGCGGGGTGGAGCCTTCGACTTAGCCTCCGTGCTAGAGGGC
          TAGGAACGTCTGAACTAACTGCGGGGTGGAGCTTGCGATTTAGCCTCCGTGCTAAAGGGC
          AAGAAACGTCTAAGCTTACTGCGGGTTTGGGCCTGCGTCTTTGCCCCTGTGCTCGAGGGC
          AAGAAACGTCCAAATTTACCGCAGCCTGGAGCTTGCGACCTTAACCCCGTGCTCGAGGGC
          TATCTCCACTAGGGATCCCTGAAGATTAAGGCATTGAAGCCTTATGTTCTAGAATCGGGT
          TATCTCCACTAGGGATCCCTTAAGATCAAGGCATTGCAGCCTTGTGTTCTAGCATAGGCG
          TATCTCCACTAGGGCTCCCTAAGGATTGGAGCCTTGCAGCCCCACGTTCTAGCGTCAGGA
          TATTTCCACTAGGGCTCTCTAAAGACTAAGGGCTTGCAGCCCTATGTTCTAGCGTCGGGA

          CGTTCTCGGTCATATGCATTCTACTGTGACTCCCTGAAGACCAGGTATGTCTGGTCGGTT
          TGTTCTCGGTTATATGCATTCCACTGTGACTCCCTGAAGACCAGGTAAATCTGGTCGGTT
          TACTCTCGGTCTTACGCATTCTACTGTGCTCCCCCGAAGACCAGATAAATCTGGTCTGTT
          TGGTCTCGGTCCTATGTACTCTTCCGTTCCACCCCGAAGACCAGATAAATCTGGTCGGTT
          TGCTGACCCTTTTATTTCCGTAGTAAGCTCCAGAACAGATAAACGTGTGCCATGAGTCCG
          TGTTAAGCCTTTTACTTACGTAGTAAGCACCAGAACAAATAAACGTGAGTCACGAGTCCG
          TACCGAGCTTTTTACTTACGTAGTATGCTCCAGAACAAATAAATGCGAGTCGCGCGCTCG
          TGCTGAGCTTTTTATTTACATAGTAAGCCTCAGAACAAATAAACGTGAGTCGCGCGCCTG

          AAAGACGCTTGACACAACCTAACTTATCAGTTGCTGCTGCCCGGAGGGTTCTGCCGCAAA
          AAAGACGCCTGACACAACCCACCTTATCAGTTGCTGCTGCCCGGGGGCTTTTGCTGCAAA
          AAAAACACTTGATAAGACCCACCGTATGAGTTGTCGCTGCCCGTGGGGTCCTGCCGTGAA
          AAAAACACTAGATACGACCCACCTTATCGGTTGTCGCTGCCCGGGGGGTTCTGCCGTTAA
          CAGCATAACCGGAGCATCACCCATCACTCTCACCTGGTATTTCAGAGGACGCAAGCAAGT
          CAGCATAAACGGTGCAACACTTACCGCACTCTCCTGGTAATTCAGAGGAGGCAAGCAAGC
          CAGCATAACCAGTGCACCACCCTTCACAACTACTTGGTATCTCAGAGGACGTGAGCACGT
          CAGCATAGCCGGTGCACCTCCCTTCATTCCCACCTGGTAATTCAGAGGGAGCGTGCATGC

          GTGAGTCTAGGGAGTCGGCTTCGTCGCGGGCGTCAGATGTCGCGGTGATTCTAACTCATT
          GCGGGTATAGGGAGTCGGCTTCGTCGCACACGTCAGATGTCGCGGTGATTCTAACTCACC
          ATGGGCACAGTGCGTCGTCTTCGTTGCGCACGTCAGCCGTCGCCGGGCATCTAACTCAGC
          GTGGACACAGTGCGTCGACTCCGTTGTGCACGTCGGACGTCGCGGGGGGTTTAACTCACC
          AGACACAGTCGATGCCGGATCTGCTCCCACGTTTTGGCGTTATGAGAGGCTCGCAGAAAT
          ATACACAGTCGATGCCGGATCTATTCCCTCGTCTTGGCGTTATGAGAGGCTCGCCGAAGT
          ATTCACAGTCGATGCCGGCTCCACTCCCACTTATTGGCGTTATGAGAGTTTTGCCTAAAT
          ACACACAGTCGATGCCGGATCCGCTCCTACGTATTGGCGTTATGAGAGCTTCGCCGAAAC

          CAGCGCTCTCGCTTTGCAAAGGGGTGGTGACTTATCCCGTATAACAAACTACTTACTTCC
          CAGCGCTCTCGATCTGCAAAGGGGCGGTGTCTTATCGCGTATGACGAACTACTTACTTCC
          CAGTGCTCTCGCTTTGCAAAGAGGCGGTGACTTACCCTGGACAACAAACTACTTACTGCC
          CAGTGCCCTCGCTACACAAAGGGGCGGTGACTTACCCCGGACAACAAATTACATACTCCC
          TAACGTTCATGAAACACAACACAGTAATGCTTTAATCCCCCATGCTGGAGATCTGCCCTA
          TAACGTTCATGAAACACAACACAGCAATGTTATAATCCCCCATGCTGGAGATCTGCCCTA
          TAACGTCTTTAGCACACAATACCGTAAAGTTTTAGTTCTCCATACTCAAGATCCGCTCTC
          TAACGTTCTTGGCACATAATCAAGTAACGTTTTAACCCCCCATGCTAAAGATCTGCCCCT

          GGGTGACTATTCGGCCGCCTACTTACGAAATTGCACTCCATGGACTCGGGAAAAATAACA
          GGGCGACTATTCGGCCGTCTACTTACGAAATTGCGCTCCATGGACTCGGGAAAAATAACA
          GGGTGAATATTTGGCCGCCTACTTACGAAGTAGCGCGTAATGATCTCGGGTAGTATATCA
          GGGTGACTATTCGGCGATCTACTTACGAAATTGCCCGTAATGGACTTGGAAAATCTATCA
          GGGTAGGTTCTTGCCAGCTGATCTGTAGTATCACGGCTGCGGAGCCAACCGTACACGCCG
          GGGTAGGTTCACGCCAACTTAACCGTAGTATTACGGCTGCGGAGCCAGCCGTACACGCCG
          GGGTAGGTGCATGCCAGCTTGTCTCTATTATCACGGCTGCGGAGTCACGCGTACACGCCG
          GGGTGGGGGCACGCGAGGTTATCGCCAGTATCTCGGCTGTGGAGCCACGCGCACACGCCG

          GGTCCCAACACCTCTTAGTGGCGGTCCGGCATGGTGTCGGCAAAGAGACGTTACGCTTGG
          GGTGACGACACCTCCTATTGGCGCTCCAGTATGGTGCGGGCAATGAGACGTTACGCTTGG
          GGCCATGACACCCCCCATTGACGCTCCAGCATGGTGCGGTCCGAGAGACGTTACGCTTGG
          GGTCACGACACCCCATATTGACGCTACAGTATGGTGCGGGCCAAAAGACATTACGCTTGG
          GGCCGGGCTGAGCTGCGTTAGTATTTCCACGCGCAGGCGGGCGGATAGTTTATCACTCAA
          GGCCGGGCTGAGCTGCGTTAGTACCTCCACGCGCAGGCAGGCGGATAGTGTATCAATCCA
          GGTTGGGCTAATCTGTGTTAGTGTTTCCAAGCGCGAGCAGGCGTATAGTGAGTCGACCCG
          GGCTGTGCTGATCTGTGGTAGTATTTCTAAGCGCAGGCAGGCGGATAGTGTGTCGATCCG

          AAACACTTAATACGATGCGCTCCCAATCCGGAATAACACACCATTATTATTGAAGGCAGC
          AAACCCTTAGTACGATGCGTTCCCAATTCGGAATAACACCCCATTATCATTGAAGGCAGC
          AAACCCTTCGTACGATGCGTTTCCAAATCGAGATAATACACTCTTATTATTGGAGGCAGC
          AAACCCTTAGTACGATGCGTCTTCAAATCGAAATAAGACACTCATGTTATTGGAGGAAGC
          TAACGCGGAAAATTTCACTACATGGTCATACAGTCGCGGAATTTTCTCCTGCTATACAGT
          TAGCGCGAAAAATTTCACGGCATGGCCATACAGTAGGGAAATTTTCTCCTGCAATACGGT
          TAGCGCGAAGAATTTCACGACATGACCATACAGTCGTGAAACTTTCTCCTGCCATACAGT
          TAGCGCGAAGAATTCTATGGCATGGCCATTCAGTCGCGAAGCTGTCTCCTGCCATACAGT

          GGGATATACGTGCTAGACACCAGTGACACGTGACAGCAGGACGTTCGGTTTGATAATGGG
          AGGAAATACGTGCTAGACACCAGTGACACGCGACAGCAGGACGTTCGGTTTGATAATGGG
          TTGATATACGTGCTGGGTACCAATGACACGTGACAGTAGGGCGTCCGGCTTGTTAATGGG
          CGGAATTCTGTGGTAAGTAACAATGACACGTGACAGTAGGACGTTCGGCTTGTTAATGGG
          GTAGCTGCGAAGGCGGACTTCATCGACCGCTTTCGATTAATCACTTGATCAACCTGTTGT
          GTAGCTGCGACGGCCGACTTCATCGACCGAAATCGCCTAAACGCTTGATCAGCCTGTTGT
          GTAATCGTGACGGCCAACGTCATCGACCGATATTGCCGCCTCGCTTGACTAACGCGCTGT
          GGGATCGCGACGGCCGACGTCATCGACCGTTACCGCCCCCCCGCTCGACCAAAGCGTTGC

          GTGGGTTTCGCTCCATGTCGCCCGAATAACGCAGCCTGCCGCCATGGGCGGCAAAGCAAC
          GTGGGTTCCACTCTATGTCGTCCGAATAACGCAGCCTGCCGCCATGGGCGGCAAACCAAC
          ATGGGTTTCACTCCTTGTCGTCCGAACAACGTAGCGCACCGTCACGGACGGCGAAGCAAC
          GTGGGTTCCACTCCAAGTCGTCCGAACAACGTAGCATGCCGTCATGGGCGGTAAAGCAAC
          GCTAGTTAACATTTGCTTAGAAAAACAGACATTGGGGGGTGCTTCATGGCGCAAGGTCCG
          GCCAGCTTACACTTGCTTAGAGAAATAGACATTGGCAGGGGCTTCATGGCGTTGGCTCCG
          GCTCGCTAACATTTGCTTCGGAAACCCGACTCTGTGAGTCGCTTGATGGCGCAAGGTCCG
          GCTAGTTAACATTTGCTGAGGAAACCAGACACCGTGAGCTGCTTAATGGCGCAAGGTTCG

          TAGGGTGTGATTCGAAGCAGTATTTTTCGGCTGGCTCGCTCGCCGATCCCCAGACGTATC
          TAGGGTGTGATTCGAAGCACTATTTTTCGGCTGGCTCGCTCGCTGATCCCCAGACGTATC
          CAGGGAGTAATTTGTATCAGCATCTTTCGGTTGGATCGCCGGCTGATCCCTAGACGTGTC
          TAGGGTGCATTTTGTAGCAGCATTTATCGGTTGGATCGTCGGCTGACCCCTGGACGTGTC
          CACGATCCCTAGCTCCGTTGTCAAACAAGTTCTGTGCCTGCATTGAGGGACGAGCGGAGT
          TAAGATCCCTAGCTCGGTTGACATACAAGTTCTATGTTTGCATTGAGGGACGAGCGGAGT
          CTCGATCCCCTGCTCCTTTGTCATACAAGTTCTACGTCTGCACTGAGGAATGAGCGGAAT
          CTCGATCCCTTGCATCTTTGTTAAACAAGTTCTACGTCCGCATTGAGGAACGAGCGGAGT

          CTGAGCATCTACCTCTAAGTAGCAACGGGTGCATAGCACATCACGAATGGGCGTGCATAC
          TTGAGCCTCTACCCCCAAGCAGCAACGGGTGCATAGCGCATCACGAATGAGCGTGAATAC
          TCGATCATACACCCCCAAACAACAACGGTTTCATAGCGCACCAAGAGCGGGCGCGAATAC
          CCGAACATCCACCCCCAAGCAACAACGCGTCCATAGCGCACCAAGAATGGGCGCGAAAAC
          TTGTGAGATACCGATCGCGTTATACTGAGCCGGTAATAATTCTGAGAGAAGTGTATGCAA
          TTGTGAGATAACACTTTTGTTATACTGAGTCGGTAACAACTCTGAGAGGAGTGCATGCAA
          TTAAGAGATACCAATCTCGTTATACTGAGCAGGTAAAAATTCTGGGAGAAGTCTATGCAA
          CTGAGAAATACCAATCTCGCTATACTGAGCCGGTAATAATTTTGAGAGAAGTCTATGCAA

          GTAGCCCGGCTGTGCCGCACAACTGAACGGGTGCCTGGTCTTCAGACCTATTAGTGGTAC
          GTAGCCCGGCTGTGCCGCACGACTAAACGGGTGCCTGGTCTTCGGACTGACGAGTGCTAC
          GTAGTCCGGCTGCGCTGCACGACTAAGCAAGAGCTTGGTCTTCGGACTGACTTAGGCTAC
          GCAGCCCGGCTGCGCCGCACGCCTAAACAGGAGCTTGGTCTTCGGACTGACTTGGGCCAC
          GTGATGCGGTAACGTATTCACGTCCCTCGTGTTACACCCCCCCTGAAAACGCCTCGGTTC
          GTGATGCGGTAACGTATTAACGTCCACCGTGACTCACCTCCCAGGAGAACGCCTAGGTTC
          GTGAAGCGATAACGTATCAGGGTCCAGCGTTCTTCATCTCTTGTGAAAACGCCCAGGTTC
          GTGATGCGGTAACCTATCAGTGTGCACTGCGCTTCATCTCTCCTGGAAACGCCTAGGTTT

          TTAGTGGACTTTATATGCAACACTGGACTAGGGAGTGTGGGCATCTTTGGATCATGCGGT
          TTAGTGGACTTTATATGCAACACTGGACTAGGGCGTGTGGGCATGTTTGGATCATGCGGT
          CTAGCGGACTTTACATGCGACACTAAACTTGGGAGTGTAGGTATGTTTGCATCATGCGGT
          ATAGCGGTCTTCACATGCGACACTAGATTTGGGAGTGTGGGCATGTTTGGATCATGCGGT
          CTGTTCTTGCCAGGGCCTGTCATTGTCCCCAGGCTGCAGGATTAATTAGAGCAATCATTT
          TTGTTCCTGCCAGGGCCCGCCATTGTCCCCAGGCTGCAGAATTAATTAGAGCCATCATTT
          CTGACCTTGCTAGGGTCTGCTATTGTCCTCAGGCTGCAGAATTAATTAGAGCAATTATTT
          CTGTGCTTGCCAGGGTCCGCCATTATCCTGAGGCTGCAAGATTAATTAGAGCAATCATTT

          AGTCGCCTGTGGGATCCTGACTGTCGCTCGTCACACTGGG
          AGTCGCCTGTAGGGGCCTGACTGTCGCCCGTCTCACTGGG
          ATCCGCCCCTGGGGTCCTGACTGTAGCTCGCCAAGCCGGG
          AGTTGCCTCCGAGATCCTGACTGTCGCCCGCCAAACCGGG
          AGCGATAACTATACCCCCATCATGGTCTGGCGGGCTTGTA
          AGTGATAACTACCCTCAAGTCATGCTTTGGCGGGCTTGTA
          AGTGATAGTCACCCTCCTGCCATGCTCCGGTGACCTTGTA
          GGTGATAATTACCCTCCTGCCATGTTGTGGTGGGCTTGTA

