 8 1000
t1        TGAGCCAGTAGCGGCGCTGAACTCCCTTCATTACACAACTATAGATCTTTTTGAAGATAA
t2        AGTACCAAAACCTCTGGTGTCCCCCTTTTTATAGACAATGGTAAATTCATCGTAAGCAAA
t3        TGAATCGCGATCTTAAATCACACCCCTTCCAACCAAGGACGATGGGGTATTTCTAACAGA
t4        TGAATCGTCATCCAAAATCACGCCTGTTCCAACCAAGGATGTTGGCATACTTGTAACAGA
t5        TCAGCAGTAGCAGCACCCCTCGTACTTTTTGTTAGAAATTACCACTCACTTACTTGGTTC
t6        TGAATATGAACTTCGCCTCTTGAAGTTCTCCTGAGTGAATTTTTTTTTCTAACTTAGTGG
t7        CCAACACCGGCCGTGCATCATGGACATCCTCTGAGAGAGAACTTGTTCTTCACTCAGAAT
t8        TCAATACCGGCCGCGCACCATGAACATTATACGCGAGAGCACTTGCCCCTCATTTAGAAT

          GCTTTGAGATGCCATTCGCATTGAAAACCGCTCGAGTAAGTGCTTCAGGACCCAAGTATA
          GTACTGTGACGCCACCGCTTATAAATCCCACTAGAGATAGAGATCCAGAACCCAAGAATG
          ATACTGAGGGTCTCGGCGTGGCTAAAAGTGAACCCGGATCCATCTTAAGTATCAAATACG
          ATACTGAGGAATCCGGCGCGGCTAACAGCGAAATCGGATTCATCTAAAGTATTATCTACG
          GTACATGAGCAGCTGTCATTCTTTAGCTTTCTGATTGATGATTACCCGTTTCATGGCGTA
          GAACCAGAGCCGCAGACATCCTATTACTCGTCTACGTGGGAATCCGGATTCTATTGCGTT
          ATCTGCTACGTGCTGTTATTGCCCTACTTGCCTGCGGAGGTATTCCGATCAAGCAGGGTT
          ATACGCCATGTGCTACTAATTTCTTGCTCGTCTGTGGAGGGGTCCTGATCCAGCAGGGTC

          TCATTATATATCCCATGCTCTGTAGTCAGCGAGCTAACGGGGCTAGTTGTGCGCCGGGAG
          CCAGTGCATACCACCCGCCCGGTAAAATGTGTGCTCTATGTCCCACGCCCGAGTCGAAAA
          GTCTCGTTCAATGCACGTGGGGCACACAACAAGCTCCTTGAGCTGCTTTTGCGTCGAAAG
          GTCCCCTTCAGAGCACACGGGGCACTCAACAAGCTCCTTGGGCTACTTTTGCGCTGAACG
          CCATAACGTAGTGCTTGTACCTAGACTCAAGTGACCCCCGACTCGACGTTAAATGGGCGG
          TGGCCATGAGACGCCCGCGCGTACAGTTGAGCGACCTTCGACCTAATGCTGAGTCGATGG
          GACTTGGTAGGTAGCAATATTGGGAGTCAAGTGACCAAGAACTAACGCTTATCTCGGAGA
          GACCCGGTAGGCAGCAATATTGCAGACTAAGTGACCAAGAACCGACTCTTATTTCGGAGA

          TTGAAACATACATAATTGGTGGAGTCTGTCAGAATGGCGTCGGAGTTGGCACCACGCTCA
          CGGGAAGATTAGGTTTCCGCGAAGTAAGTCCGAAAGGATTCAAGAGTAGGAGCTCGATTG
          AGTGGAGAGTCCGCTTCAATACAGCTATACGGACTGGTGATGCGGTTGGCAGTTCGCCGG
          AGTGGAGAGTCTGTTTTCACACAGCTATACGAATTGGCGATGAGGTTGGCAGTTTGTCCG
          CTTGAAGGCATCGCTTAGACCGAGAATGTCTGACGGTAGCCGAGCTTGGGGTTGCAGGTG
          AACAAGGGAAACACTGGCGTAGCACGTGTTTAACCGTAGTAGAGATTGAGGAGCCAAGAG
          ATTGAGAGGAGCAATCGAAAAGGACGTGTCGAATGGAAGCTGATACTGCGGCCGTAGGTA
          ATTGAGAGGAGCTTTCGAATAGGACGTGTAGGAGGGGGGCTGACACTGGGGCCGTTGGTG

          CCCACAATCTGAAAGTTACCATTCTTTTACCTGTACTGTACCTTCCATAACTCTCGACCT
          AAGACAAGTTGAGGGCTATTGTTTTTTACGGAATCCCGTGGCTCCGTTTATCGTTGACCC
          CCTTCAGCCTACAAGCTATCATAGTGCCCAGAAAGCCATATCACTGGCCATGAGCGGCCA
          CCTCCAGTTTATAAACTATCATAGTGCTCAGAAAGCCATACCACCGGCCGTAATCGATCA
          ATGTCGGGGTTTAACACAAGATTCCGTTCACAGCATTGGGTTAAAGAAATTGCCTAGGAA
          ATGTTAGTGTACAATTAATCGTCCCACTCAATGAAATTGAATCAAGACATTGTATAGGGG
          GCGCCATCATTCGAAGCAAGACATTAATTAAAGATTCTTGCTACAGGTATCGCATGAAGG
          ACGCCACCATTCGAAGGAAGGCATCAATCAATGATTGCAGCACCAGGCATTGCCCGGCGG

          GAAACGGAGTGTAACTGAAGATCCTGAGTATCGTACACAAACTTTCAATCACGTTTCAAC
          GAAATAGTGCGTACCTGATAACGCAGAGTGTCGAAAGCGGATACAGTCCAAGGCCTTTGC
          TAAGGGGAGCGCCTTGACTGGGGCGCAACCTGTATTTTCTACCGTCTAGTGGAACTCTTA
          TAAAAGGAGCGGTCTGAGTGGGGTGCAACCTGTGAATTCTACGAACTATTAGAACTCTTA
          ATCGGAGCGAATGTTATAATAATCTCCATCTATACGCCGCCTCACCTGAGGGGCTCGATT
          TCCGATGTCGGTGTCATTATAGTTCACATCTCCTGATTAAGTTGCCTTATAGGCGCGGTA
          CTCAAGTTGTCTGTTACAACAGGTTTCATGTCGTTATTGAGTTGCTCGGTAGGTACGGTC
          TTCACGTTGTACGATGCAAAAGGTCACATGTCGTTATTAGGTTGCTTGGCAGATGCGGTC

          TTGAGCGCATCGTGAACGGCCATATAGCCTTAAGAACTGCCACGTCAATGTCGTGAAGAA
          TTGAAAGTTCCCTAGCCTGTCATTCTCTTCTCAGTACTGGCCTGTCAAAGTGGGCAGAGA
          AAACGAGTGCGTAAGTCCAGCGCTTTACGCACGTACCCGGGAAATTACTGCCAGTATGCT
          ATCTAAGTGCGTGAGTCCACCGCGTTACCTACGTAACCGGGAAATTACTGCCAGTATGCT
          CTCGCGATTACAACCCTTTCGGATCATATGCTGGATTGACATCCTCAACCTAGATGGAAA
          TAGGTGGTTGCGGCCCTCACGGTCCCTTTGACAGATTGATCTACCCAAGCTTGGTAAAAC
          CCTGTAGGGGTAACTACCGCGGCCCTCAGGATGGTCCGCCATCCACCAACGTGGGGGAGT
          ACCGTAGGGGTAACCACCGTGGTCTTCAAGATGGTCCGGTATCCATCAACTTGGGGGAGT

          AGGACGCCCCGTAATTCCAGTCTTTTTTCCAAATATTCGCTTCCAACGACCCGGTCTGCC
          GGGATGCTTCCTAATCCCAGGCTCACTTTCTAACATACACTACTAATCATCCGCTCTATA
          GGACCCATTTATGGCACACGTCTAAGTTCTACACAAGTCAGGTGAGCATAATCGGCTTCC
          AGACCCGTTTATGGCACATGTTCAACTTTTACACTAGTCAGCTGTGTATAATCTGCTTCC
          GGCTCCACTCGTACTATTCTTCTAGGTTCCACGTGTACTGTTCGAGCCACAGGACCGGTT
          GAATCCGCTCGCAGCTCTCTCCCCGTTTCAATGCATACAGTTCGCTCGCCAAGGCAAATT
          GGGTGTATCGGCAGTACTTTCCCAGCCTTAAGGTAAGTTGTCTAAATCTGCTGGCCCATG
          GGGTCTATCGGTATTACTTCCCTAGTCCCCGAGCAAGTTGTCTAAACCTGATGGCCCATG

          CTAATAAAACCCGAGCATAGGTTGCAACGAAGCTACCTACGGTCTCAACGTCACCGGTCA
          GTGGCGGAATCCGCGTAACGATGGGAACACAAACAATGCCGGTCACTGTGCAATCGGATA
          GTTCTGGTATTCGGGTTCCCGACTAGGCTAAAAAACCCCCGGTCACGGTGTTGCTATGAA
          GTTATGGTGTTCGGGTACCGGGTTAGGTTAAAGAACCCCCGGTCACAGTGTTGCTATGGA
          ACCCTGGACTTCAGGTATCGCCGCTGAAGCGCGAATCAGAACTGAGGAGGGGATCGATCC
          GCTTCAGACACGAATCGTCGCCGGTGCGGCAAAAATTAGGTATGCCCAGGGAACTGTCAA
          ATATCAGACTTTGGACTACGTACCCCGCATGAAATGTAGGCCATAGCCGGTGATTGGCCA
          ATATCCGGCTTTGAACCACGTCATCCGCGTGAAAATTAGACCATAGCGAGTGAATGTCCA

          CCGCGGAGTGGGTGACAGGTTCTGGGGATCCAGCGGTAAGTGGACAGCCTTATTCTGACC
          CCATGAAGCGAATGAGAGTAAATGCGATGTTGTAGGTAGCCGGAGGTTCATGTCCTAGCC
          CTAGTGGCTAGACCACTGGCCACGGTTATCAGTCAGTGATTGTTCGGAAGAAGTCCGTCT
          CTAGTAGGCAGCCCGCTGGCCTCGGATATAGGTGTGTTTTCGCTCTGGAAAAGTCTGCTT
          CGAGATTACCAGAGAATAGCTATTATTGAAAGTGGCTAACAGAAATACTTGCGCACAACA
          TGAGCGCGCTGGTACAGTCTCACCCGTAAAAACGCGAAGAGATACGGCCCCACCATGGCC
          TGGGGTGTTTAGCACAACGCTATTTGCGACAGTGAACATGGGTGAGGTTTTGACATCGCT
          TGGGGTGTTTAGCACAACGTTATCTGCGAACGTGAATATGGGTATAGTCTCGACATCGTT

          ACATTCCGGACCTGTGAGAAAAATCGACATTCACACTAGTAGGAATGATACAGCTCCTTA
          AGAGACCCCATCTGTAACGAAAACGAACCTTAAAACTAACACAACTGAAATAACTATCTG
          GATGCTGGGAGCTCAACGCGGGTCTTATTCCCCTGCTCCTGGGGGTCATCTGCATGCCAT
          GATACTGGGAGCTCAACGCGGGTTTTTTTCCCGCTTTCTGGGGGATGACCTGCACGCCAA
          CGTGTGGGGAACCTCGTAAGGGCTGCACTTTTCATATATGCATCCTGGGGTAGAGCCGGC
          CGTGCAGAAGGCCTCCCAAGGGCCGCACATATTCTCGACACCCCGCAGGGTCCAGTTTGT
          TGCGCAGTGATGCTCCTCAGGGTCGCTCTGTAACTGTACGCCTCCTTGCGTATTCTTTGC
          CGGGCAGTGATCCTCCTCAGGGTCGCACTATCATTGTACGTCTCCCTGAGTATTTTTTGC

          GAATGGGGACCCTGGCTACGTCCGACGGAATCCTATCTCTGCGCCGAAGGTTCAGATTGA
          AGCCGGGGACGCCGCCTCAATTCGACTGAAGCTTGTTCCCGTGCCGCCAACCTGGAGCGA
          AGCGTGCGTCCTTAACTATGGACGCCAGTACCTTTAAACCATACATTGGTACCGGACTAA
          GGCTTGCGCCTTTGACTATAGACGCCTGTACCTACATACCGTATATTGGTCCGAGACTGT
          TTGCTGTACCATTATACAAGGCGCCTTAGACGCCACGTAATCGCGAAAAACTGCGACGAA
          TTCGGATGCGATTAGGCATGGATCTTCGCACGTCACATAGCCGCGAACTGCCGCGAGTAA
          AAGCGGCGCTCACCTGCACGGTTTTGCCAATGTCTCATAAGTGAACAGGTCCGTTATTTA
          AAGCGATGCCCGCCTGCATGGCTCTATCAACAACTTATATCCGAACAAGTTCGTGACTTA

          CAGTACAACGCTATAGGGGTGTAAGACAGGATGGGCGTTTCAGCACTCTGGCGAGCAGTA
          GTGTAATACTCCCCGGGCAGGCATGTTAGGATCGGCAGCTTAGCGGCTCGGCGGACATAG
          TCAGAAGATCGTCTCAAACGATCCAACATGATGTGATGCCGTCGGTATTAATACGTAAGA
          CCCGAGGCTCCTCCCAAACGATCCAGCATGATGTGATGTCGTCGGCATTTATACGTAGGA
          CGGCACCGCTAACTTGATGTCAATGAAAGGATGGTAAATATCAAACCTAACTGTATGCGA
          CTGTAAAGTACAACTAGCGATAGCGGAGTGATGTCGATCCTGATGTCTAGTCGCGCTTGA
          TAGTGCCGTACCTCAGATATTCGCGGACAGAAACACAAGCGTATGCATAGTCATGGGCAA
          TAGTGTCGTCCCCTTGATATCCCCGGACGGAAATGCAAACGTAGGCATAGATATGGGAAA

          TTTCATGATGAGTCTAGCAGTATCCTTTCCTGTCGTACAACACAGGGTAACCAAGGGGGT
          GCAATTAATGATTCATGTCGTCCCCCTACCTATCATAACACCGAGGGATACCGAGGGTAC
          TAAATTAGTGATCTCGATGGAAACGCACCGACTTCCGCCATAACGATAAAATAGGAGACC
          TAAGTTAGTGATCTCGATGGAAACGTACCGACTTCAGCAGCAATGATAAAAAAGGGGACC
          CTTGCAGAGTGGCTGTTCGGGAGTTATCAGCACTAGGCAATAATGACCGTTTACGCGGGC
          CGTACTCAAAAGTCCCCCGGATATCAATAGCGGCACGTGGTACTTATCGATCAAGATGGT
          CGTGCACCGTAGCAGCCCCGGTTGCTGGAGCCCTTGGTGACAATGATCCGCCAGGTATGG
          CATGCAGCGTGGTAGTCTTGGTTGCTGGAGCCCTTGATGACAAAGATCCGCCAGGTCTGC

          GTTCAGCATTTCCGGAGTCCCGATGAATTCGCGCAGTGGTCTTGATAAACACGATCCATA
          GTGCAGCTTGTCCGTCACTCCCTTGGAATCGCACGGTGCACTTAACACGTGAGTTTCGCC
          ACGCCATACGCACGTCCCGCCCGAGGATTAGTCCCCAACCTCTGACCAGTAGTCTGCTTT
          ATGTCTTACTCACGTCCCGCCCTAGGATCAGCACCTTACCTCTGACAGGTCAACTGCGTT
          TATTAATAACCCGGCAGGTTTCATAGTCAATTTCACCATTTGCTCCATCTGATGTTCTTA
          CTTTCAGCATCCAGATCGATTTTTGATCAATTTCTAGAATGAGTACCTAGAGTGATCCTA
          CTCAAATCATCCAGTATTCTATCTGGGCAATTTTTCGTCTTCTCTTCGTCGGACAGCCCA
          CTCAAATCATCCAGTATGCTGTCCGGCCAATTTTCTGTCTTTCCTTCGTTAGATAGCCCA

          CCCTAAGCATCGAACTCAATGTAGAATCTATAGCATATCATTAAGTATGCCTCTGGAGGT
          CACTAACCGCGAAACTAGATATTGCGTTAGATATATGCCTTCGATACTGTTTAAATGAGC
          CCTCGAACTCTTTAACATTTATTCATTTGAACCTATCCTTTAGAAATCATCCTTCCGGGC
          CTGCAAAGTCCTTGGCACTCACCTATTAGAACGTATCCTTTAGAAATCATCCCTCCGGGT
          GCTCTATAGCCCAGTTATCAGGCGCGGGTAGCCTATGCGATGGATGGAAGTTTCATGGTG
          GTCTCATCTCGGAGCCAATAGAAGTCGGTGCTGCCCAAGATGAACCGAAATATCTAGACC
          GTTCCTGTTGCGAGCTATACGAATTTTGCACAGCGCAAACCAGCCACTAGCATCGAGCCA
          GATCCAGCTCCAAGCTATACGAGTTTTGCGCAACGCAAAGCCGCCGATGACCTCAAGCTA

          CAGGGCGCTTGGCCCTGCACCGATCACTAAACGTGGGAGG
          CAGGACGTATGGCCTTGCTCCCACAACTAAACGTGAGAAG
          CGTTCTATGGGCTCTTGTATTAACTGCTGGACTAGGTGGG
          CGATACACGGTATCTAATATTAATTGCTAGGCTAGGCGGG
          GACAGCGCACAATTTAAACCCGGCTGCGTCGCATTGCACG
          GGCGATGCAGGATGCCGTACTGGTTATATCACTCGGCATG
          GAGGATATAAAGGCCTAATCTGGGCTTGAACTGCGGCTTG
          GAGGGTATTAAGGACTAATCTGGGCCTATAATGCGGCCTG

