 8 1000
t1        TCCGTTATGACGACAGTATGATAACTCGCGATTGGGCCGCCTTCATTGTGACTGTGTGAA
t2        GCCGTTATGACGACAGTATGTTAACCCGCGATTGAGTCGCCTTCATTGTGACTGTATGAA
t3        TTTGCTACGGCGGCGGTGTGATAATGTGCGAGTGGCACTTCTTGACCGCAGACGTACAAG
t4        CTTGCTACGGCGGGGGTGTGAAAACGTACGAGTGGCACTTCTACTCTGAGGACGTATAAG
t5        CTGAGCAACATAATTCGGCTAACATTCGTGCATCACTCGCGCATGTTAAATCGACGAATG
t6        CTGAGCAACATAATTCGGCTAACATTCGTGCATCACTCGCGCATGTTAAATCGACGAATG
t7        TACGTATCTCGAACTATGTTCCAGTAAATGGGTTGGAGTCCATAACGGCGTTAGTATAGC
t8        CACGTATTACGGATTGTATTCCCGTAAATGGACTGGAGGCCACCACGGCGTTAGTATAGC

          TTGAAAAATATGCCTACCGCCGCTCATTCCTACGAAAAACTGATTCATACTAATGGTACA
          TTGAAAAATCTGCCTACCGCCGCTCATTCTTGCGAAAAACTGATTCATACTAATGGTACA
          CAGAAAACTCCGCTTCCTGGTGTTCTTTATCGCTAAAAGTTACTTCATCCAATCGGTGTA
          CCGGACGGTCCGCCCCCTGCTGTTCGCTATCGCTGAAAGGTACTTCATCCGATCGGTGTA
          CTGTTCACCCTAGCCTGAATGAGGCTTCCTTCTAACGATCCAGACATAGTGTCCGAGAAC
          CTGTCCACCCTAGCCTGAATGAGGCTTCCTTCTAACGATCCAGACATAGTGTCCGAGAAC
          TGAGAATCCTTAATCCACGCCACCGTGTCCTTGTAAGCCTTTTTCTACGTGTCCGAGTGA
          TGAGGATGATCATTCCACACCGCCATCTCCTCGCAAAATTATTTCTTCGTGTCCGAGACA

          CAGAGGAAGCCGTGCGCCTGCGATTCTTATCAGACGGCACGAGATCGTACCGTTGGTTTG
          TAGAGGAAGCCGTGCGCCTGTGATTCTTATCGGACGGCACGAGATCGTACTGCTGGTTTG
          TTGGGGAAGCCGAGCGTGTGCTTATATTTTCGGACGGTCTATGGTTGGACAGCCGGATAA
          TTGGGGAAGCCGGGCGCGTGCTTTCATTCTCGGACGGTCTGTGGTTGAACTGACGGACAG
          CGTTAGTACTAGCTGATGCGCGTTTCCAGCACGTTTCCACGAACTTTGGTATGACTCAGA
          CGTTAGCACTAACTGATGCGCGTTTCCAGCACGATTCCACGAACTGTGGTCTGACTCAGA
          CGGACTTTAGCGCTAAAGCATTCTCATTTTGTAGTGGACGCATGTGATCTAGGGAGAGGG
          CGGAGTTTAGCACAGAAGCGCCTGTATTCCGTTATGGACGCATGTGACATAGGGACAGGG

          GCGAATAGCGGCTTGTGACGCTCCGCGGTTATGAACAACATCTCTACGGGGTTACCGTAT
          GAGAATAGCGGCTAGTGACGCTCCGCGGTTATGAACAACATCTCTACGGGGTTACCGTGT
          GAAACTTGCGCCTAATTGCGACCCGGTGCAACCTTCAACATACATCCGGGGTTTCCGCGC
          GAAGCTCGCGCCTAATTGCAACCCGGCGCCATCATCAACGTCGATCCGGGTTTCCCGTAC
          ACGGGGGACAACAGTCGACAGCCGAAGCCAACCAACAAAATTTAGCTGTAGCCTATGTCG
          ACGGGGGACAACAGTCGACAGCCGAAGCCAACCAACAAAATTTAGCTGTAGCCTATGTCG
          ATGCCGAAGGCACGGTAACGAGACATGACGAGAGAAGGCCCATAGGAACTATATCCGCCT
          ATGCAGTAAAAACGGTAACAAAACACGACGGCAAAAGGTACTAAGGAACTACTTCCGCCT

          CCACACGATGTGACTTCATTTCCTATTAGACATAGCCTGGCTCGATCGCGTAAAACCTTT
          CCACACGATGTGACTCCATTTCTTATTAGACATAGCCTGACTCTACCGCGTAAAACCTTT
          CCACTTGGCGGGTCTATGTTTCCGATCACACACAACCGAAGCTTATCAGATGAACTCTGT
          CCACATGGCGGGTCTTTGTTTCCTATCAGACACAACCGAACCTTATCCGGTAACCTCTCT
          TTGTGCGCGTCAGCTTTGGTCACGATTTAAGAAAGCGAGATCCTGTTAACTGGTGTGCCC
          TTGTGCGCGTCAGCCTTGGTCACGATTTAAGAAAGCGAGATCCTGTTAACTGGTGTGCCA
          GCAAAAGGGATATTTTCGGGATCCATTTAAACAGACCAGTTAGTAACACGATGGTCACAT
          GCTAATACAATCTCTGTTAAACCCGATTTTACGGATGGGTGCGTATTAAGGAGGCCACAT

          CAATTGGCGGCCGTGCTACACCATACTTGATTGTCACTTATAATGTCATCACGACTTAAT
          CAAGTGGTGGCCGTGCTACACCGTACTTGATTGCCACTTATAATGCCATCACGACTTAAT
          CAGGTCATGACTACGCGACACTCTGTCTCACTGTCACTTGATATATCACTAGGATTTACA
          CAAGTTAAGATCAAGCGACACTTGGCCTGACTATTGCTTGAAATATCGCTAGGATTTATA
          GGTAACCAGACTCTGTATCCGTGAGTGCCATCCGCAGCAAGCATGGGGGTGCGGCAGTTA
          GGTAACCGGACTCTGTATCCGTGAATGCCATCCGCAGCAAGCATGGGCGTGCGGCAGTTA
          ACTGACGTTAGTCTGTGCGTCCGAAGGCCCTGGTCATCGCGCGTTTTCTTCGGACAAACT
          ACTGACGTTAGTCTGTGAGTCCGACAGCCTTGGGCATCGTGCGTCTTCTTCGGACAAACT

          CTGTGGAGGCGTCGGGCGATAGCTTGCTAGATCATAACATTTAGTGCGTAGAGATATGGT
          CTGTGGAGGCGTCGGGCGATAGCTTGCTAGATCATAACATTTAGTGCGTAGAGATATGGT
          CTCTAAGGGTGACAGAAAACATCATGCCCGGTTATGACACTCGGAGACTAGGGTTTTGTC
          ATCTAGAGGTGATCGGCAACTTCCTGCCCGGTTGTAACACTCGGAGTCTGGGGTTAGGTC
          TTGTACGAGCAATCAGCCTCCTTTTGATTATCACATAAAACCGGAGATTGTCTATAGCAC
          TTTTACGAGCAATCAGCCTCCCTTTGATTATCACATAAAACCGGAGATTGTCTATAGCAC
          ACTAACGAGAAAACAGCCTGTTCGCAGCCCGCTCCCCCCACTGGTATCTGGAGACACTGC
          ATTAACGGGAAAGTAGCTTGAGCGCAGCCCATCTCCCACACTGGTACCCATAAACGCTGT

          ACTGGGCCACGCTTGGTCGCTTTATTCCTGGGTGCCTACGGTCATCAACAGCAGACCCTT
          ACTGGGCCAGGCTTGGTCGCTTCATTCCTGGGTGCCTACGGTCATCAGCAGTAGAACCTT
          TCTGGTACCGACTGGGTCGCTCTCCTCCTGTTTGTCTGTGGACATCAACAGTCATTCCCT
          CCTGGAACCGATTGGGTTGCTCTCCTTTCGTGTGTTCACGGACATTAATCGTAATTCCCT
          ATCCGAATCACAGTGCACGTGAGTTTATTATCCCCACAGTAAACTGACTAGCGCATACAT
          ATCCGAAACACAGCGCACGTGAGTTTATTACCCCCACAGTAAACTGACTAGCGCATACAT
          CCAGAGGCACCGGCGGGGGAAAGTTGCTTACTACCTGACAGGGCTCAAAGACCTACAATC
          GTAGGGGTACCGGCGAAGGAATGTGGCTTACTACTTGAGAGAGCTCAGAGACCTACAATC

          TCGTGTATTCAGGGGAGGTTATATACATGGGCAGACCCGCCCAGACACAAGACTTGAGAG
          TCGTGTATTCAGGGGAGGTCATATACATGGGTAGACCCTCTCAGACGCAAGACTTGAGAG
          CCCCATACTTACAGCAAGCTGTGTACGTGGGCAAGGCTCATAGGAGGAAAGACCACTGAG
          CCCCGTACTCGGGGCAGGCTGTGTACATGGGCAAGCCTTGTAAGAGGAAAGACTCCTGAG
          TCCAATGGATTGGGTCAACACGCGATAGAGTGAAACCCACTTGGCCGCAAGGAATGCTCG
          TCCAATGGATTAGGTCAACACGCGATAGAGTGAAACCCACTTGGCCGCAAGGTATGCTCA
          CTCTGGAATTAGGTTAAGCTCGATATCTCGAGGAACACTCACGCGCAGCACAGCTAGAAG
          CCTCGGAATCCATGTAATCTCGATACCTCGCAGGTCACTCAAGCGCTCCATAGCGAGGAG

          CGTTCTTGCCACGTCAAAACTACCGTAAGAAGTTGCCTCAGACCGCGGGTGTGCGGCATT
          CGTTCATGCAATGTCAAAACTACCGTAAGAATAAGCCTCAGACCCCGGATGTCCGGCATT
          CGAGTCATCAATCCCAATACCATTGTCAGATATGATCTTAGTCCTCGGGCGGCTGGCTTT
          TGAGCCCGTAACCCCCATCCCACTGTTAGATATGACCTCAGGTTTCAGGTGGCCGGCTCT
          TGAATAGACGGTTTTAAGGCCGAGCTTATGGAGGAAAATACACCCTGAGTGATGGGAGCC
          TGAATAGACGGTTTTAAGGCCAAGCTTATGGAGGAAAATACATCCTGAGTGATGGGAGTC
          TGCCCACACGATCATAGACCGTCAATGAGAGGTTCCCGTATGCTATAAGTTTGAGGTCTG
          TGTTCACACGATCGCAGACCGAAAACGCGAGGTTTCCAAGTGCTATGAGTATGGGGTCTG

          ATAGGATGGTGCGAGCCTTCCGGCAAGAGAATAGGTCAGGCCAGTGTCAAAGGTTAATGG
          ATAGGATGGTGCGAGCCTTCCGGAAGGAGAATAGGTCAGGCCAGTGTCTAAGGTTAATGG
          ATATAGAGGTGTGCAACTTGCAGCAAGGTACCAGGTCGAGACAGAATGAAATGTTGGCGG
          ACATAGAGGTGTACGACTCACAGCAAGGTACCAGGTTGAGACAGCATGGAATGTTAACGG
          ACTCCCCGGCGTATGGAGCCTCGAACGGGCCTTCGCCGCTCTCGAGTTTAATGTATTAAG
          ACTCCCCGGCGTATGGAGCCTCGAACGGGTCTTCGCCGCTCTCGAGTTTAATGTATTAAG
          GTTCATCAGCAAGCGATGTGTTACGCTAGTGCCTGATTTGACCGCCTGTAACATTCCTCC
          GTCCCTTAGCAAGCGACATGCCACGTAAGCGCCTGATCTGTCTGCCTGAAACAACCCTCC

          TGTCTGGAGTGCTTACCCTCAAGGTCGCACAAAGGTCTGGCGGTAGAAGCGGTGTAAAGA
          TGCCTGGAGTGCTTACCCTCAAGGTCGCCCAAAGGTCTGCCGGTAGAAGCGGTGTAAAGA
          AGCTTGGTGTGCTTCCCCTAATCGTTGTACGCAGGTCTGCTGAAAGTAGTGGTGTGAGGC
          AGCTTGGCGTGCTTCCCCTAATGGTCCTACGCAGGCCCGATCAAGGTAGTAGTGTAAAGC
          GATCGGAACTACTTACGACGACGATACCAAAGAGATCTGACCACATAAGCAACTCAGTAC
          GATCGGAACTACTTACCACGACGATACCAGAGAGATCTGACCACATAAGCAACTCAGTAC
          ACTTGCCAAGGCCAACCAAAATGATCACGACATTATCCAACCCTATAAGTCTTACGGCAG
          ATCCGCAAACGCCACTCGGTATGTGTATGACTCCATCCAACGCCATGAGTCTTATGCCAG

          AGCTTGTTGAGGCGAATCACAAATCACTGAACCAAAGAGCTCCCACGTATGGGATATAAT
          AGCTTGTTGAGGCGAATCACAAATCACTGAACCAAAGAGCTCCGACGTACGGGATATAAT
          AGTATATTAAAGCGACCGTCTCGTCTTTGCAAAAGATAGTTTCGAGGAGCGAGGAGATAG
          AGATTGTTAAAGCGACCATTTCGTTCCTGCGAAATATAACTCCGGGGGGCGAGATATAGA
          ATATATCCAACATTGCCACCGCATTATTGTTCGAGAAACTCTCAGTCAAACGGAAACAGA
          ATGTATCCAACATTGCCGCCGCATTATTGTTCGAGAAACTCTCAGTCGAACGGAAATAGA
          CCATTATTGCAACTACCCGATGCCTCTCCCATCGAGCGCGCCAGGCTGGTTAGGCAGGTG
          ACACTCTTGCCATTACCGGATGCCGCCCCTACCGAGCGCACCAGATTGGTTGGGTAAGTG

          CGCGACCAGATGCAATACGCTTTTTAAACTCCCATTGTTCTCGAAATGAATTCGGGGTGC
          CGCGACCAGATGCAATACGTTTTTTAAACTCCCATTGTTCTCGACATGAATTTGTGGTGC
          CATGCCCAGATATGATATGTTCCCCTGTCCTCTATTGTTCCCAACATAGACTCGAGGTGC
          CACGCTCGGACGCAGTATGCTTCTCTGCCTTTTTTGGTTCCCAATATGAACTCGGGGTGC
          ATCACGTGACCAGTTGTGGTACCAATTGATCCAAATGGGCCGTGAACGTCAGAGTATTGC
          ATCACGTGACCAGTTGTGGTACCAATTGATCCAAATGGGCCGTGAATGTCAGTGTATTGC
          GTGCAACATCCTATATTCGTAAAAACGAACTACTTAACAGGCAGCTGGGATATAAGCCGC
          ATACAACACCCGATCTTCAAAAGAACGAGCGATGTCAGGGTCCGAGGGGATATAAGCTGT

          GAGGGGATCTTGACCTTGTGTGATTATGCATTTGGAGCTAATACGGTCGCTATATGCTCG
          GAGGCGATCTTCATATTGTGTGATTATGCATTTGGAGCTAATACGGCCGCTATATGCTCG
          GAAGAGGTCCGAATTGTCTGCAATTCAGGGTTTGAAGATAGCTTAGATGCTCCACGCTTT
          GAAGAGGTTCCGATCGTGTACAATTCAGGGTTTGGAGCTAACCCAGTTGCTCCATGCTCT
          TTCCACGTTCCTCCTAGGGCCATTCGAAATAATTCAGTGGGATTTAGTGCCCAGCATCTC
          TTCCACGTTCCTCCTAGGGCCATTCGAAAAAATTCAGTGGGATTTACTCCCCAGCATCTC
          GGACGTTTGATTTCTTGTTATCCCTGTAGGCGACTCTAAAAAATAATGATACCCATCCTA
          GGGCGCTTGACTTCTTGTAATCCAGGTAGGCGGCCTTGCAAAATGATCATCCCCGCTCAA

          TCGATGAATGTACGTCAGACATTGGACATCTCATCCCGGTGCCATCTGTTCAACATCAAT
          TCGATGAATGTACGTCAGACATTGGACATCTCATCCCGGTGCCACTTGTTCGACACCAAT
          TTGACGGAAGCGAGCTCTAACTTGGACGCCCACCCCTAGATTCATTTCTCTAGCTCTAAT
          TTGATGTAAGTGTGTTTTAACCCAGACGTCCATACCTAGATTCCCTTTTCTAACTCTAAT
          GATTAATGAATTCTCCATAAGCGGGACTACTTCATTCCTCGTACTGTGTTGTTTCCACAA
          GTTTAATGAATTCTCCATCAGCGGGACTACTTCACTTCTCATACTGTGTTGTTTCCACAA
          AACGAGAAACGGTCGCGTGATCCCGTGTCCCACCTTCAGAAAAGTTTGTGCCATGCTCTT
          AACCAGGAAAGCTCGCGTGCTCCCGTCCCTTACCTTCAGGAGAGTCTGTGCTCTGCTACT

          GACGTCTAACCGGAATCACCTCCTCATTACTGGCACTGGG
          GACGTCTAACCGGATTCACCTCCTCATTACTGGCACGGGG
          AATTTCGCGACGGACCCACTACCTCCCCGCTGGAACTTCA
          GATTTTGCGTCGGATTCACTAACCCAACGTTGGAACTTCG
          TTCCGTACGTTGATATCTAAGTAAACAGGGCGAGGTTAAG
          TGCCGTACGTTGATATCTAAGTAAACAGGGCGAGGTTAAG
          GACCCTGGATTACAACTAGCGCTCGCGGGGAAGGAGAACG
          GATTCTTGATTGCACCTAGCGCTTCCGAGGAAGGAGAGCG

