 8 1000
t1        GGAGCATAACAGGATACCGCCCTGAAGTTAACTTGCCCGATATTAATCAACCCGCGAAAC
t2        GGTACAAGAGAGGATACCGCCCTGATGTCAACTTGCCCAATACTAGCCAATCCGCCAAAT
t3        GGTGTACGGTAGCATCGTAAGTCTAGGCGCACTTGCCCAACGGGTGTCGGCTCCATGAAT
t4        GATACCAAGCAGCATAGTACCTTGACCCGGACATGACCAACATGACCAATTACCACACAT
t5        AATGTGCGGCGGACTTGTGAAATGCGCTGGGTTCGTCAGACTCCTTTTTTCTCGCTAAAC
t6        CGCATAAGGCTGTATTGTACATCGTGGGGAACTTGTCCAACATGTTTCACCAGCAATGAT
t7        CAAGCCAGTCTGCTGTACGCTCTAGGAGCAGCCTGGTGGCCCAAGTTTACTGTCAGAGGT
t8        TAGACGAGCCAACTTAGAGAGGTTCCGAGATCTAGTCCAAGTGAGCCCGGTGCATCCCTT

          AGCTCGGCACGTGTTACGTAATGCGGAAGCAAGCCCGACCACACACACGGCTCGTCGGAC
          AGGTCGGCACGTGCTACATTACGCGGAAGGAAGCTCGACCATATACACGGCTCGTCGGAC
          TGTCTGATCCGTGTTGCACCCTGCAGTAGCAAGAGCGAAACTGCCCACAACCGGTAAGAC
          TGTTATGGATACCCTTTGGTGTATAGTTGCCCAAGAAGCGCGACTCAGGGGGTACCGTCT
          AGTTTGGTATACACGCCATGGTATGATTGCTTAAATGACCAATCAGATGGCTCGTACGGA
          AATCTGCTAGGTACTACGCTATGCAGCACCCTGCAAGACACAAAGTGCAGTGAATACGGC
          GGGAGGTATGTTAGTGAGTTGACCGGCTATCAGGGGGAATTTACTTATAACGCGTCTCGC
          CATCGGGAGAGTCGCCCAAGGACCAGCAGTTCGCATGACCCAATCTAAAAGGTAGACGGG

          CACGATGTTCCAGGGCCGGGATTCGGGACGCATAACTATTGCCACGGACTTGCCCGGAGT
          CGCGGTACTCCTGGGCCGATATTCGGGACACTGGACTACCGCCACGGACTGGCCTGAGGT
          CACAGTACGCCCGGGACGCGGCTTAGGCCCCTGGGATATGCCCTCTGATCATGCTCCGGA
          CACGGTTCGTTTTAGCTACAAACTGGGAGACAAGACCACCCCACTCCATCGGCCCCAGGC
          TGCGGCCTATTGGGATGGCTACTAGAGACACTAGACTGCATTAACATACTGGCCTGCAGA
          TCCGGCACCCCTGAATCGCCCCCATAGTTACTCGTTTGTCATACCTGATGGGCCAGGGGG
          AGCGGCTGGGGATCTCTGAAACCTATTCCGTTGGGCCCCGGTAGCAGTCCGGCTTCTGAC
          AACGTCATGATGAGTGTGCCTCCAGTTTTCCCCGGCGACAACTGTAAACCTATTTGAAAA

          GTACTAGGGTAGTGTACTATCTTTCTGCTGCATCGCCCTGTTGAAATCTCCCATAACTCT
          CAACTAGGATAGCGTGGTTTCCTTTTGTCGCGTCGCCCTGCTGAAATCTTCCATCACCCT
          AAAACCAGATTGCGTGCTAGCTGTTCACTGGGTAGCCTTCTTGGCGATACTCAATACCTT
          CATCTTGGAAAGTGTGCCAAATGTTTATTATACCATCATTTTGAACGTACCCAATTCTTT
          CTGATAAGGCACGATGACGGCGGAATACCGTATCGGATCTCAAAACGAGTTTGATATTCT
          ACGCTAGAACAACAGGTCGCCGATTGACACGGCCGCCTTGCAAAGAACGTCTGATACTTA
          AGTACTATATATGCGTTACCAAGCCCCCTGTTCCAGGTCGTCACCAACCTTCCGAGCCTG
          TCCATAAATGGGCCTACCCCGACCCTAATGCATGCTCGTCCTATGGTCAGTTGCCCCCAT

          ATGTTGTGGACGATTATATCATGCCAGACAGCATGTAAACATATGTCAGTTTACATCCCG
          ATGCAGTGGACGTCTATGTCGTGCCAAACAGCATGTAAATATATGTTGGTTTACACCGTG
          GTATTGCAATCAAATTCGCCTCACAACCCGGCAAACAGATTAAAGTAGGTTTAAACGGCG
          ATGCTGCAGATAACTCTACTATACTAGTCGGCATAAATATACATGTGAATTCGGACCCAC
          AGCCTACGGGCAATTGGCTCTTGCCAGCTGGCGTTTAGATATAGTCTCGTTCTTGATATG
          ATGTTGAATACGTGTGCTTTTTTTGAGCCCGAGTATTCGGACACATTGGCGTCTTTCGGG
          AAATTCTGTTTCGCAAAGTCATATTAGGTGGTGCTCAGGTAGATTCTAGCACCACTTTCC
          GGACCGTACCTCAGATATACACTAGCCAGTTCGCCATGTTGGATGCGAGTCTGGTTCATG

          GAGTTGTATGCGATGTTGTGTATAGCCTGGGGCTCCTTAACAACCACATAATTGACAGTG
          GAGATGTATAAGATGTTGTATCTAGCCTGGGGCTCCTTTACAACCACACAAGTGACAATA
          GAGCTGGCTGTGACGTCGCTTTCAGCTTGGGGCCTCTCCCCGTCAGAACGGGTAACAACG
          AGGCTGGACGTGAAGTTGCATACAGGCCGGGGTTCTACCCAAAGCGGGCACGTGACACTG
          GGGGCAGACGCTCGGCTGTCTATCGCTTGGGATCTTTTCATAACGGAACAAATAGCAATG
          AGGCCGAACGTGTCGTCTCTTATTGTCTAGTGCTCTTTTCCATTTTGCCTAGCGACAATA
          AGGTTAACTATAAATACTTCCGTTGTTAAGAGTCTCTTTGCTACAGTCCGGATGGCCCTA
          TTAACATCCGTAGACGCATTCTTGGTTGCGTCTCGTCTCATAAGCGGCCGGGCACGTACA

          TAGCTGACCTCGGGGGTTCAAAATACTCTAATGCAGCTGATGCTCTCCAGATCCATCATC
          TAGTTGACCTCGGGGGTTCAAACTACTCTAATGCAGCTGATGCTCTCCAGAACCATTACC
          CTGTCTGATCATCTAACCCAGGCTAGCGTAACTCAGCCGGTGCGCCCCAGTCCCCATGAC
          TAGTTCAAATTGCAGGATCAAAACTCCGAAAATCCGCGGCGGCCCCCTAGCCCTTCCATC
          CATCCTAAATAGTGGGTCCGAAATATCATAAGCATATCGTTGCTCTTTAGTTCCTTAATT
          CAGGTCAAACTACTGGCTACGCTTACAGTCACCTTACTGTTGCCATCGGGTCTCACCACC
          CCGTCGCGAAAACGAACTCGCGCTACAGAGCTAGCTTGGCTAACTCGATGTTTTCAATCC
          TCGCTCCTATTCGATGTCTATAATCTTTCAATTAGCTTCCTCCCAAGCTTGTACGAAGTA

          CGGGTGCGCTCGGCGGTCTAAAGATGATCCGATTTCCGCTTCAGGGCACTACGCCTTGAT
          CAGATGCGCTTGGCGGACCAAAGATGATTCGTTTTCCGTTTCAGGGCACTTCGCCCGGAA
          CGGGCGGTGGTCGCATGCCAACGTCAAACCAATCCCCGTCTGAAGGCACGGCGCTGTAGT
          TGTGTGAGCGTTGAGAGCCGATAATGAGCCAAATTATGTTTCTGAGGAGTATGCCAAGGA
          TAGTCAAGGGACTAACACGAAAGATTAGACGACTCCCGCTTTAGCGTGCTATGCTGCGTC
          CAATCGAGGCGTCCGCGTTAAACGTAAGCTGTTTATCGCTCTAGGGAACTAGGAGAAGTC
          TGATAAAGGGAAAAGTTCCGCGAATACAGTCAAAATTGCAAGAAGTGATCGGCCAATGAC
          CCATGCAGGAAGGTGCATTAGGGATAACCCATTGGTATGTTGGGGTCGGTGCTCCAAGAG

          CCGCGGCTTAGTGGGCATGGTGAGTTTCTATTACCTTTGGACCCAACTAAACCAACTTGG
          CGGCAGCTTAACGGGAATGGGGAATTTCTCGTATCCTTAGACCCAGCTAAGCCAACTTGA
          TCGTGTCGTAGCGAGCCTAGTTAACTTGCTGGGCTCTTGGATGCGACTAATGCGACCCGA
          CTGCGTCACAGTGAGGTGTGTAGATTCATTACGGTCTTGTCCCTGACGAACGCGATGCCC
          TCGTGTCGCAGCGAAGTGCTTGTAGACACCACGGTCCCGCACACGAACACATCAACCCGA
          CTGTAACACGGCAAGTAGAGTGGGCCTGCCGTATGTTTGGGAATCATGGACCCAACCCCA
          GTCTGACACGACGTGTTGCATAGATAACCGGCAATACGTCAGTGTATCTCAGAGAACCAT
          CGAAACTGGAGCCTGGTGCGCTTACAGGCCATATTTGTGGGAGGAGCTTATAGGTCCTGG

          CGTACATGACGATGTGGCTCTGTCCCTTCCTTCAGGATTTTGAAATCCCATCAGCGGTGA
          CATTTATAGCGATGTGGATCCGTCACTCCCTTCAGGATTTTGAAATGCTACCAGCGGCGA
          CATTGCTAATAGTCTGGCACTGTTCGGCAATTTCGGAGCTAGAGCACCACTTGGAAGCGG
          TATTTCTGGGATAATAGATCTGTAACTATCCGTAAACATCTGGGGGTCCTTCGTCGGTGG
          CCTTTATGGTGAGGTCGATACTTTCACACCACGGGGTATCTGGAAGTCCGCTAGCGACTG
          CCTTAATGTCACAGTCGATCTGAATCATATCTGGGGGGCCTGGAGGATCGGTGGAGCGGA
          TATCACTGACGATGGTCCCCGTCACTTTTACGTGGCGCTTCGTATTTCGCGCAGGCGAAG
          CACTGCTGCCCTTCGACCAATAGACGCCTCGCGAATTACCTGGGTAAATTTCAGCACAGT

          GAGACTCCGGTTTCATCCTCTTTGCATTTAGCTTCAGTAGTAGGAGGCTGTGCCGGACGT
          GAGACCGTGGTTTAATACTCTCCGCGTGTAGCTTCAATAGTAGACAGCCGCGCCGGGCAT
          GATACGCCGGTTCACGCTTCATTGAGCCTAATCTCGTTGGCGGATTACCGCACTCATCCT
          GACAAGCCGCGTCAAGTCTCCTTGACCATGACCTCATTAACAGCTCGCCTAGCTAGACGT
          ATCCAACCGTCCCGAGTTCACTTATCCATGATTACATTGTCAGTCGGCCATGCAAGTGAT
          GACACGCTGGTTCATGTTTCCTTCCAATTCATCGTAGCAAAAGATTCCTGTGCCCGAAGG
          TCTACCTTGGAACAAAGTACAATGAGTCTCGCTCTGTCCGTAGCTGACTGTGCACAAAGC
          GCTACACTGGCTTAGTTGTTTTTCTAGGCGCCGGTAGCTACGTTCAGGTATGTCTAAGGC

          CCATGACTGTTTGGAAGTGCACACGCATGGCAGGCCCTCGAATCGGTAAGTGACGCTCAT
          CCGTGATTTTCAGGAAGTGCAGAACCACGGCAGATCCCCGGATCGGTAGGTGACACTCGC
          CTTTGGTTACTGGGCATGATTCGAGCGTGACTGGCTCTCGGTTAGCCAGGTGCGACCTAT
          CTTTGGTCATTAAAAGGCACGCATGTAAGACCGGCACACAAACCGCCAGCTAAGAACTGA
          CTTCAGCAAATCGGAAGTGAACCAGTGTGACAAGCCCATTCGTGGGTGGGTGTCCCTGCC
          CCTCGTTCACCAGAAATAGGGTGCACATATTGGACATAAAACAGGGTGGCTGTTTCCCCA
          GATCCGATGCGGCGCAGCAAAAAGGCCTCGACGCTCGACAGTCGGGTAAGCGCGACTCGA
          TGTAGGCCGCCATAAGACGAACACATAAGGTTAACTAGAGGCTGTTTGGGGGCGGGTAGG

          CAACAATCAAAGAATGCTGTCAAGGGGGTTTCCGTGCTCACCCCCCGATCTTGTTTCCGA
          TACCAATCAGCGGATGCTGTCGAGGATGTTTCCGTGCCTATCCCCCAATCCCGTTTCGGA
          TCAGCTCTACGCAGTGCATCTAGGGGGGTACATGCACTAGCTCCCGACTTTCGCCCGTAA
          TGCCCAGTAAACATCGCTGCTAGGGGGCTGTTTCTACTAAATACTCAACTTTCAGCCCGA
          TGCTAACTAGCCATCGCGTAAAGAGCGCTCGGGATACGGACACACCAAACCATGTATCGA
          GTAAAACTCGCTACCGCCGCGAAGCGGTTCTGTGTGCTTATAAGACCACCGACGTCTCGC
          CACCTTTGAACAGACGTTGACGGGGGAGGATACTTGTCGACTTTCTCGCCCGCTGTCCTC
          TCGTTACTGGAGAACGCGTGCGGGGCTTAAGAAATGACCGTCCAGTAGTAATCCCCGAGT

          AAACGCCAGCACCGACATTTTTGGAAAAGTGTCATCTTACTGGTTCGACTTATGAGCACA
          AAACGCTAGCATCGACTGTTTTGGAACAGTGTCATCCTACTGGATCGATTCATGAGAACA
          AGTCGGCCACATTGTTGGTCTTGATTCAGTGTTCTCCGACTGAGTCCTCACGTTTATACA
          ACTTGCTTTTCTTAATGGTCCTAAATGACCGTCCCCCGGAGTTATTTTCTCATGTGTATA
          GGTCGCCTATACACCCTGCGCTAGGTCCATATCACCGGGCTGCTCCTAAACGTGAGATTA
          TATTGCATAAGTAACTGACATTGCACCGATGACCTGTAATTGTATTGTTCTATAAGAGTA
          CAAAGTTCGCCACCATAGCTATAAGCCTTTGTCCTCTGAACCCGCCATCTAGTCAGCGTA
          AACCGACGAGGCCAGTGAGCGCCAGCCGGCGTTCATTCGGTTTCTTCATCCACGGGTCTG

          CCGACACCCACTATCCGGTTCCAATAACTATCAGGGCTGGCGAATTTTAGCGTCACCCAG
          TCAACACCCCCTATCCAGATCTAATAGCTTTAATGGATGGCAGATTTTAGCGTCATCCAG
          ATATCATCCACTATTTGGCTCCAGTGATCACACCGTGCAGTCCATTTTAATGCCACCTTG
          GCGCTACCGGTTACTCGGTCCCGCATCTTATGGCGTGTAGTTTATTTTAGCCCTACCCAG
          TTAAATCACACCATTAGGTTCGGGGAATTAAAGAGTGTGATGGACATTAGGGCTAACTTT
          GTGTGGGGTATCATTCAGTTCCGGGAACCCAGGGGTGTGGCAAGCGGTGGTGTTCCCTTT
          CTGTACAGCTCCCAGAGACTTCTTCAAGTATGTGCCATAACAAGGGCCGGTGCGAACAGG
          GGGAACGGTCCCAGGTGGCCAGGATTGACACAGAGTGCGAGACATGAACACATGAAGAGG

          AGGTATTGCTCACCAGGGTCGTAAACCGTATCTATTCAAGGCTGCCGAATCGTTTTCTAT
          AGATGGTGCTCATCAGGGTTGCAAACCGCATCTACTTAAGGCAGCTGAATCGTATAGTAT
          CGGTGGTGCCCTCCAGAACCTCTTACTGCATCTTATTAAAGTTACCAAATCCGCCGATAG
          TGGTGATCCTCTTCAGGCCCGCCTATCGTACTCCCTTCAGGGTACAAACTTGATCGACAT
          TAATCCAAATCTTCGAATCTAGTTAGTGTGCTACTTTGTGGCCACTAAGTCACGTCTCTA
          TGGTGGTAATTATCCAGATTAGTAAGCGTACTTCATCACGGCAGACAAAGTGTTGAACAG
          AGGAGGCAAATCATGAAGCCCTTATATGCATAAGTTCGCAGTCCCGCAATGGTACTTTCA
          CAACTCCAACGGCTACGTCTCTTTCTCCTACTCTCTGCGGGTTTCACACTTGGCTCTCCG

          AAGAAGTAGGTGATGAAATGCATTAAGTGGGCGCATCATC
          AAGAGGTAGGAGATGAGACGTATTAAGCGAGCGTTTCATC
          ACCATTGACGATATGATATGTATTCAGCGTACGCATCCTC
          ATCAGTTAGGAGATGCGGCGAACTTGACGTGTGTTCCTCC
          AGCGCTCGGGGGACTTTATGCGTGCCGCATGCCAACTATT
          ACAGCTTAGTAAATGTGAGGCGCGCTGCATTGGTAAAATT
          AGGGTCGTAGCAGTGCTTAAAGCGTACCGCACCGTCCGAC
          AGTGCCCCCGGCCCTCGAGGTAGCAAAAAAAGGAGCCACT

