 8 1000
t1        CCCTCCTATAGTCGCTCTGGCTCGCAAAGATACATTCTAACGACTGGGTAGGCTGAGGCA
t2        CCCTCTTATAGCCACTCTGGCCCGCAAAGATACATTCTAACGACTGGGTAGGCTGAGGCA
t3        TCTTCCTATAGCCGCTACGGTGCGAAAAGATACATTTTAACGACAAGGAAGGTTGAGGCA
t4        CCCTAATATGGTCGCTCTGGCGCGCTAAGGTTCATCTGAAAGACAGGGTAGTCCCAGGCA
t5        CTCTCCTTGGCTAGATCGGGCGCACAAGGAAGTTTCCTGATGACACGATAATCGCAAGTG
t6        CTCTCTAAGGATTGAATCCGCGATTGGAAACGTAAGCTTGTCGCAGGATAATATCTATAA
t7        GAACCTCTCTATGTGGTAAGAACGCAATCGTGCTATCTTGCGACGGGGTACGGCCGGGTA
t8        TGAGCTTTAATTCAAGACAATACGCAGACACTCCTCTAGGTTGAAGGCGACCAGTCAGCG

          AAATTTCGGGGTCATCAGCCCCATTCACGAATACCCCTGCAGCCTCGTACTTTGCTAGCG
          AAATTTCGGGGTCAACAGTCCCATTCACGGATATCCCTGCAACCTCGTACTTTGCTAGCG
          AAATTTCGGGGTCAACTGCCCGGTTCACGGACACCCCTACACTTTCGCCCTTTGCTAGCG
          AAATATTGGAGTCAGCACTGCATTTGACCGAAACCCCAGCAGTCTCAGCCTCTGCTCGCG
          AAATCCTGTAGCGAGTGGCACAAATCACTGCCACCTTCGAGCTTTCTCAACGTACCAGGG
          AAATACTACATCACACAATGCGAACTATTTTTGCTCACGGACCCCTTCCCACTATCTTCA
          GGACTCTACGCATTTCCACGCCAGTTGTAGCTACTGCCTCCGCTTTTTCATTCATCGATA
          AACCACTAGGAAGAGCCGCTATGGCCATCTCAATCTTGGCCGACCCACTTAGTGACGCAT

          GGATTTTGGACCCGTGTAGGAAGAGCGGTAAATACAACTGTGCGGAGTCACACACTTCAG
          GGATTTCGGACCCGTGTAGGAAGAGCGGTAAATACAACTGTGCGGAGTAACACATTTCGG
          AGATTATAGAGCCGCGTAGGAAGAGCGATAAATACGACTGTGCGGCGTCACACAGCTCAG
          AACTTACTGACCCGCGTAAGAAGATTGCTAAAAACAATCGTAAAGATTCACATAACACAG
          ATACTATCAACCTGTACAAGGAGGTTTGTAGTTACAACCATACGTAATTACTTGTGTTAG
          TTATCATCTAATTATATACGGTAGCTAGCGAGGACTATTGTTGGTTACCGTTTATATTGG
          CGGCGGCACGGCTGCACTGGGCAATTAATGACGTCAACTTTACACTGACGCTCGCGTCAG
          AGGCTATTACGTGGAACCGGCGGAGCCGGAAGACACTCCTTGTATCGCAGTGTAAATGCG

          GAACGTACTAGGACTTCTCTTCGTTAAAACACCTGCGCTAAAGGCAGGTCTGCATCGCTT
          GATCGTACCAGGACTTCTCTTCGCTAAAACACCTACGCTAAAGGCAGGTCTGCATCGCTT
          GATCGTAATAGGACTTCCCTCCGCTAAAACACTTGCGCCAAAGGCAGGTCTCCATTGCTT
          GATCGTACCAGTACTACACTTCGCTAAAAGTCCCACGCTAGAAAAAGGTCTGAATTCATT
          CACTAATTCAGTCTGATATATCGTACAGAGTGTAGTGCTTTAGGCAGATTGCGACTCCAT
          GATAACGTTCGTATCGACACTTGGGTAGGGCTCACCATTATAGGTTCATTACAACAACCC
          AATTGAGATAGCTCTTAAATTGAGATAAGGTACACAGCTGCGAGTTGAGTGTGGTCATCT
          GCTTGAGCCTCCCCAAGCCATGTTGTTTGGTTTTGTCGTTGAAGTGGACTCCGACAACTC

          AATTAAGCCCGAGGTTGTAGGAACGACGTAGAAAAGGAGCGTGTGTTCGGATGCACAGGC
          AATTAAGTCCGAGGTTGTAGGAACGACGTAGAAAAGGGGAGTGTGTTTGGATGCACAGGC
          AAGTAAGTACGAGGTTGTAGGAGTGACGTAGAAAAGGGCAATGCGTCTGAATGCACAGAT
          AACTAAGGCCAAGGTTGTAGGAATAACGCGGTAAAGTGGTACGTGTCCGTATGTTCAGAT
          AAGTAAGGCCAACTTTACAGGAGCGGTGGCGAGGGAGAGAATGTGTGTGATATACCAGAA
          AATCTGGCCTAACGCATCAGGAAGCACGCGCCACTTAGGGGCGCGTTCAGTAATCTAGTT
          ATTTGAGCCTAGTTCTATGCAAGAAGTGAAGGGAAAAAGCACGTACGTGGTAACCCGGCG
          GATAGAGATCAGCAGAGTGCTTGAGTTGCAGCGCTTAGACCTCTGCGGGACTGCCTTGTG

          ATATCTAAGTGGTCCTTCGGCGGATTGCGGCGAGTCTTGGGACTAGTGGAGAGTGACGAT
          ATATCTAAGTGGTCCTTCGACGGATTACGGCGAGTCTTGGGACTAGTGGAGAGTGACGAC
          ATTTCTAAGCGACACTTCGACGGATTGCAGCGATTCTTGGGACTAGTGGCGAGTGAACAC
          TCATGAAAGTGCCACTCCCACAGATCGCGGTGGGTTCTGGGCCTGGTGGCAGTAGTGGAC
          ATATTGCCATAATAGTCTGTTACATTGAAGCCGGCCTTATATCCTGCGGTGGGAGCGGAG
          CTGTTAGGGTTACGTCCGCTCGGCTCTGCGTAAGCGGTAGACCCTCTGATGGGAGTAGCG
          ATACTGTCTCCATGATTTCTTGGATTGGTACGCAGTCTGCGCCCTACGGAGGGAGAAAAC
          CTCTCGGCGCAACATAACATTAGCAAGGTATAGAATCCGCCTGACGGGGGCCAACCAGCA

          TGCCCTCCGAGTCCGCTGCTCAATAGTGGGCTACCGTCCCCTCGGGCGCAGCATCACATG
          TGCCTTGCGAGTCCGCTACTCAATAGTCGGCTATCGTCCCCTCGGGTGCAGCACCACATG
          TGCCCCACGAGTTCACTATTCAATGGTCGGCTATCGTCCGCCCGAGTGCAGCGCTACCTA
          CGTCCTTAGGGCGAGTTACATAATGGTCGGAAGGCGCTCTCTCCGGCGCAGAGCCATCTA
          ACTTCAGAAAGACTGCATCCTCTTAGCTCGCTGGTATCTCAAGAAACTGGAGATCACACA
          CTCCCTGAGAGGTCGCCTTATCCGTTTCGACCGGCCGCTCTTCATGAAGGTGGATCCGTC
          TTGTCGACGGGACCATCTCATTAGTTCTACTATGCGGTTACTTATTCTCTGGAGACCTCT
          ATCCCGCAGTGCCTATTTTACCGTCCTGTAACTACGCCTCCACTTGGCTTCAACTCTCAG

          AGTTGCTAGTAGGGACGGACAGCGAAGGTCTAGCTTTATATGAAATATTGCGTTCCACAA
          TGTTGATAGTAGGGACGGACAGCGAAGATCTCGGTTTACATGAAATATTGCGTTCCACTA
          AGTCGGTAGTAGTGATGGACGATGATGATCTTGCTTTATATGACGAATTGAGCTCCACAA
          AGCGACTAGAGATGAATGGCAGCGACGGTCTAAATTTACACGAAGACTTGCGTTCAGCAA
          AAGATACAATGGTTCAGCAGAAAGTTAGTCCAACCGAGATTGAAAATTTGCTTTCTCACT
          AGTACATAATCACTGTAGAGAACAGTGAGGCGATTTTTTTAAGCGACCTATGCTACCTCG
          AATACATCTCAGCGAAAGAAATCGGGTGTCCACGGTAAATTGCCAAACTAAGCGATTTAT
          ACAATGCCGAAGACTAAATGGTCAGTTGGTCCAACTCATACAAGGTATTACGCAAAGCGG

          ATTAATCCTCATGGTGCCGACTCAACAATCCGGACAATTTGGTCAGGCCGAACCGCGTTA
          ATTAGTTCTCATGGTGCCGATACAACAATCCGGTCAATTTGGTCAGGTCGAACCGCATTA
          AATAGTCTTCATGATGCCGATCCAAAAATCTGGTCAATTTGGTCAGGTCGAAACGCGTTC
          GTCGGTCCTCGTAGTGCGGATTCAGAAATTTACCCAATTCGCTGAGGTCAAAACGTGTTA
          TATAGCCCCCTCATAGCTACGTTAGAAGCCGCATCAACTAGTTAAATTCGGGCCAAGCCA
          AACAGTTGTACGAGGGTAGTCTTAGAAGCTCTTTGGCCTAATTAAGCCCCCATAGCGTAT
          ATTTGCACTGCCGGTGCGGTACCCTAAGGCCGGTCCGCTTAATCGACACGTACTGAATTG
          ACTTATCTTGTCATTGCATTGACGGCAGCGGGACCAAACTAGTCGCCACCTCTAAGCTCT

          GTCACTACTTCCTGGATACCGTCCTATGTCACCGGCCTTGCATTGCTTGCATAACACGAC
          GTCCCTACTTCCTGGATACCGTCCTATGTCACCGGCCTAGCATTGCTTGCAGAACACGAC
          CCCCCCACTACACGAATATCGTTCTATGTCACTCGCCTAGCATTGCTTATAGGACACGTC
          CCCTTCATTTCTCGAATGCAGTCCTATGCCACCGGCCCAACATTGCTTTACGCATGCAAT
          TTACGCTCGTAACACAAGCTTTCTCATTTAACGGGCACAGTTACAATAATAACTCGTTAT
          CTTAGTTCGCAACGCGAAGTCTTTATTTTCACGAGGCTTTCCTCGTAAGCATAATAAATT
          TCTTTGTCACAGTGTAGGGACCGCCATGATATAGCTCCGTGTTCGTCGGATGTACATTAT
          GGAGGAGCACACCTCTGGGTTCCTGATCTCGTACCGTCTTCCGCGCAGCAGTTATCGCTG

          CAGACGTTCCTGTATGTTTGCCGTGCCGGCCTTTGTTCGGTTCTCCGTCGGGGGAACGCC
          CAGACGTTACTGTATGTTTGCCGAGCCGGCCCTTGTCCGGTTCTCTGTCGAGGGAACGCC
          CAGACCTTACTTTTTGATTGCCGAGCCGGCTCCTGTCCGGTTCTCCGTAGGGAGAACGAC
          CTGTCGTTACTGTATGACTGCGGAGCGGCCCTGTACTCGTATCTCCGGCCAAGAAACGAC
          CAGGCGTTGCGACATGATCACCGCGTCGTCTCTTCTCCGTTACTGCGGTAGAGACGTAGT
          TGGGCGCTACAAAATCTTCGCCAAGTTGCCTCGAGTCCGGTGGTCAGCAGGACAAGTGCC
          GAAGTGTAATCCAATGGTTGTTGCGGCGGCTCTGACCTGGGATATCTACGGAAGCGTGCG
          TTCACGGTCTAGCTGGCCTCGGGATCTCATCTGGGGACGTTGCTTAAACTGACGGGTCTA

          TACATTAGACCGAAATGCTAATCCGATCCTATGGCACTTCACTCTGTCAACTTATGTGGT
          TACATTAGACTAAAATGCTAATCCGATCCTATGGAACCTCACTATGTCAACTTATGTGGT
          TACATTCAACTGGAATGCTCATCCGATTCGTGGACATTTCACCCTGCTAACCTAAGTGAC
          TCTATTAAACTAAAATGTAAATCCGATCCGCTCCAACTTGAGTTTCTTAACGTATGTGTC
          TTCATTAGACTCAAACGTGGGGCTGATCTCTTCCGGTTCAACCTTGTTGCGCTGTCCTTT
          TCTACTTGATCCGGACAGGGGCCCGACCGTGCGCAACTCAGACCGACCTGTCTATCCGAC
          TATATCAGGTGTACAACCCCCGTTGGTTCTCCGCAACACATTCACCGTGGCTTGCACCGC
          GGTCCGTCTGTTCGACGTGAGTTCTGTTTCCCGACGTCCCACCTGTGAAGCCACGTGAGG

          GCGCACACGCAACCCCTCCACGTAAGACGTTTCCTCTAGTTAATAAGTGTCGGCTCGAAC
          CCGCACACGCAACCTCTCCACGTAAGACGTTTCCTCTAGTTAATAAGTGCCGGCTCGAAC
          CCGCACGCCTTACTTCTCCACGTAAGACGCTATCTCTCGTTAATAAGAATCGGCTTGAAC
          CTGTACATCACAGTTCCCCACGTTAGGCGTTACACTTTGTTATTAAGCGCCGGCTTGATC
          CCGTAGCTATCAGACGTCTTTGCCATTTGACACACCTAGTTGCCATGCGATGGGCTGAGC
          TCGCTTAGCTGAGATAACAATGAAGGATGCGGACTCCGAAATGCCAGTAACAGTATAAAG
          TGACGTGAGTCAAACGGTTCAGCGAGTGGCAACATCCCAGACATCGGAAGCTGTCATGAA
          AGATATACGATTACAACGCTCTGAAGGCGCAACATTACACTGCTCCCGGTCGGTTGAACA

          CCGGACGGTCTCGCAGAAGATCCAGCCAGGAGGATTTGTGATGCGAGGTCTGTCTTACGC
          CCGGACGGTCTCGCAGAAGATCCTGCCAGGAGGATTTGTGATGCGAGGTCTGTCTTACGC
          CCGGACGGTCTCTCAGAAGGTCCGGCTCGGAGGGTTCCTGTTGCGTGGTCTGTCATACGC
          TCGGACGGACCCTGGGTGGAGATGGCTAGGAGGGGTTCTGCTGCGCGGTTTGTCATACGC
          TTGTACAATAAGCGCGAGATGCCTCCCCGGGAAGCCCTTGATGCTCGGGATGTTCCATAC
          CCGCCTTCCGCCCGTGCGGTGTCAGCGATAGGAACTAGCGATGTGTGACATGTCTTATGT
          TCGGACACTACTTGCGGGGGGGGGGTTCAAGGGACTTATGTAGTTCGGTGTGACCTCTGC
          TATGTTGACCCCCAGGTGGGAATCACTGGATAAGCGCTTAATAAGCGGTCGGGTTCAGGT

          TTATGAACTACTAAAGGAATCGGGTCCATCGCGTAGCATTATAACTTCGAGGTATTGCCT
          TTATGAACTACTAAAGAAGTCGGGTCCATCGCGTAGCATTATAACTTCGAGGTATTGCCT
          CTATGAACTACTGAAGGAATCGGATCCAATTCGTAGCATTATCACTCCGGGGCATTGGCA
          CGACAAACCTCTGTAGGGATCTGGCTCAACCGGCAGCATTACCACTCCAAGGCATTGGCA
          CTTCGAACTGCCCCTACCATCTAGATCAACTGACCTTGCTACCATCGCGAGGCACTCGCG
          CCTTCTCATACTCAAGGAATCTAGTCAGGTTAATTTTAAATCTGGTCTGGGAATCTCGCT
          GCAGGGCGCCTAACGAAATAAATGCCAGGCCTGTCGAATATATCTTCGAGAGTTTGTCCG
          CCCTGCTTAACCGATGATTTGTCCATCGACTATCATAGCCACATACTTGGCAATTGGGTG

          GCGCCAAAACCTCAGGCGTCCACACTGAGGTGAGCATCCCTAGGCGTGCCAATAATAGAC
          GCGCCAAAACCTCAGGCGTCGACACTGAGGTGAGCTCCCCTAGGCGCGACAATAACAGAC
          GCGCCAATACTTTGGATGTCAACACCGAAGTGAGCATCCCCAGGCGTGACAATCCCAGTC
          GCGCTCCAACCTCAGGCCATAACGCCGAGGCAAGTATCCCTAGGCGAGACAATACCAGTC
          TAGGAAGGGCTTCGGGCGCCAAAAGCGAGACAAGTATACCTCCGTTGGAAAATTTTGGTC
          TGACACCGGCCCCCGGTGTCCGCTCTGAGATTATGATTCCCATATGGAATTGTAAAGGTC
          GAGTATGCACCTTCGACACCGGGGCCCAGATAAGACGGACCTTGTGGGGGAACGACGGAC
          AAGCATTGACCGAGGTACGCCATCATGAGACATCTGGCGTGCGAATATACATTGCTGGCC

          CCGACAAAGGAGCGGATTGACAATCCAGATCGGCCAGGCA
          ACGACAAAGGAGCGGATTGACAATCCAGATCGGCCAGACA
          AAGACAAAGGAGCGGATTGTCAATCCAAACCGGCCAGACA
          AAGACCGGGGTGCGGGTTGTGCTTACAGAACGGCTGGGCA
          GACCCACAGGGAAGCATTGGTAACGCAGCTGAATTGGGGA
          GGGTTAACGGAAGATACCCTCCGACCTGCGTAGTCGCTAG
          AGTCCGGGAGTGCACAGCGGTCGCACGGAAGCGTCCTACG
          ACGGTTTAGCCGGCGGTTTCCCTGTATTGTCTTACAGAAA

