 8 1000
t1        CAGCTTCCCTGCTCTACACTGTGTACAGTTTATTACACGCAAAGAATGAACGCTGTTAGA
t2        CAGCTTTCCCATTTTACTCTGTGTACAGTTCATTACGCGCAAAGAATGAACGCTGTTAGA
t3        CAGCTTTCTCGTCCTCCGAAACGCACAGACTATTACACGAAAGGTGTGAGCGCTGTGGGA
t4        AAGCATTGTCGCTCATTGCTATACACTCATTATTATACGTAAGGAGAGAGCGTTTTTAAA
t5        TTACTCCGCCGGCTTCCCAAGTGCCCTCGCCATTGGACGTAAGGAGCGATCGTTCACGGG
t6        TTACTTATTCGGCGGCTGGTAAGCTTCTACGATCGTCGGCTGCATGCGAGCGTTTTTGAA
t7        CTACCGCCGCACTAACCAGAATACCCACACCGGAATAGGTAATGACTGAGTTTCCACGCG
t8        CTACGATCCCGCTCCTCAGAGTGTCGCTGTCGAGGTTACTTCCCCGTGAAGGACTGACAT

          CTAATACCATAACTTGCGGCCTCTCAAGGAAATTTGGTTCTCATTTGTATTACCAGTCCG
          CCAATACCTTAGCCTGCAGCTTCTTACGCAAATTGGGTTCTCGTGAGTATACCCAGTCTG
          GCAACACCTTGCTGTGAAGCTTTTTTCGGAAATGGAGTACTTGCTTGTACCACCCGTTCG
          ACGCCACATTGCTTTGTGGTTCTTGCGGGTAGCTGCATCATCGCATGAATTTTCAGTCAG
          ATATTTTCTTGCTTCGCGGCATCCCCAGGGTGTTAATCTTCCGCTCGATTTAATAGCCCC
          AGATCACCTTATTACATGATTCATTTGGACACTTGACAGTCCGTTCACGCCAATATTTCG
          TTCGTACTTTGTTTTGGAGGTTCAGAAGAAGGCTGACTAGTCGTCCGTATCCATTTCTCG
          TAGTTAATAGCTTCGAGACGGAGCCGCAGGGTCTAAATCCATCCGAGTCTTTAACAAACG

          TAGGCGCTGCGGGCGGGTTCATACGCGAGTACCGGACCTAATCTTAGAAGAACCATCCTC
          TAGGCGCTCCGGGCGGGTACATACGCGAGTGCCTGACCTAATCTTAGAAGAATCATCCAT
          TAAGTGCTTCTGGATGATTCATACGCAAGTGTCAAATTAACTAATGGAAGGACCACCTAT
          CAGGCGCCTCTAAAAGGTTCGTATGTGCGTATCAGCTATGCCATTAGAGAGCGCGTCTAC
          CAAACGCCTATTTATAGTTCTTACGCGCGCTCCAGTACTGTTATTGGCGAGAACATCCAT
          GCGATGGCGAAAGACAGTCCGTGAACACAATGTAGTTCATTCACAGGGGCAGCCCTACAT
          CAGTCTTATTCGCTGATGTCCTATGCGGATGGCCACGATAATAATAGGATGCTGGCCTAA
          TAACCGTAATCGTGTGCTTTGGCCAAGCAAGGTTCGCCCAGAACCAGCAAATACGTCCCC

          TAGGTTGAGGCAACGGCGTCCTGTTTTGCAGCATCGGGAACTACCTCAGATAGCGGCGTC
          TAATATCCGGCAGCAGCGTCCCGTTTTGCAGTGTCGGGAACCACCTGAAATAGCGGAGTC
          TAACATGAAGTGGAGGTACCCTGTTTTACAGCATTTAGCACTACTAGAGATAGCGGAGTA
          TAGCACGGTATAGCTGTTCCTTCACTGACAGCTCTCAGAAGTACCTATAATAGTGGGGTA
          CAATATGGCGTGGCTGAATCTCGCTCTGACACACTCACAACATCCTAAGACAGTGGAGTA
          TACCGCGGAGTGACTGAAATGCATCTGACGACACCTAGAACAATCTGAGAAGGTGAACTA
          TATTGAATAGCGCATTCACTCTTTCCCATATAACCAACGGACGCGGATAGCGGGTGAGTG
          CCAGGCCGGTCAGTGATCTCCCATATTTATCAATCTCTGGCTCTGTGAGGAAGCCGAGAG

          ATACGATGGAACGTTCCTTGAGGGTCCGTTTTACTAGGGACAACCCTCTAGCTTAAAGGG
          GTCCGATGGATCGTTCCTTGAGAATCCGTCTCACCAGGGGCTAGACGCTAACCTAAAGGG
          ATACGATAAATATTCCTTTTGGGGTTCGTTCCACCAGCGTCCACGCGTTGGCTCAAAGCT
          ATCCGGCGAATTTCTCCGAAAGGGTACGGTCTGCCATAGTTTATGTCCTCAGTTAGGGGG
          GTACCATGCACTTGCTGGGGAGGGCAAGTTCTACCAAGGTTTATGCATCGGTTTACGAAA
          TTACCGCGTAGTTGTCCGCATGGGCACATGCTATAAGTGTGGCCGCCCCCAGTCCCGGAG
          TGACCCCGCTGCTCCTTGTGTCAAGACACCTTATGATGGCTGACGATGGCACGCCCACGA
          CTTTTCTGGTACCCAGGGGGGGAAGATGTCGAACCTCGGTCAGTGATCGCGTGCTCTGAG

          AGAGGAGGCCCGTCCAAATGACCGTCACTTTCAAATTTGATCCAACGGGAAGTGCAAAAG
          AGCGGAGGCCCGTTTAGATGACTGGTACTCTCAAATCCGATCTAACGGGAAGTGCCAAAG
          AGCGGATGCCCCTCCCAATGACCGCCATTTTCTAGACTGATGAAACGGAGAATGACGTAG
          AATAGTTGCCCCCCCAATCAACCGTTACTTCCTAGCCTGGTTTATCGGCTATGGACCTAG
          AGACGATGACTAACTAAATGGCAGTTGGTCTTTACCAAAACTCTATGGAAAGAAGCACAG
          AACGGACCAATTTCTCGACGACAATGACTATTCATGACAACTAGACAGAAGGTGTCAAAC
          AGTGGCCGTTACCCCAACTATACAATACACTGTGCTAGCGTCCAAGGAACGGTCAAGTAA
          TAAAGATGGCATCAATACCACCCGCGACTCTCTACCGGCACTCGTCGTGGTGGGTGCGCG

          GCCGCTGATTGCAGGGACATACTCTATCGTGTTGAACAGGGGAGAAAACGCAGATGCGTC
          ACCGCCGATTGCAGGGACATATTCTATCGTGTTCAACAGAGGAGAAAACGAAGATACATC
          ACTGCCGATTGGAAGATCATCCTCTATTTTGGGTAACTCTGGGAAAGGCCATGATACACT
          ATTGCCGACCCTAAGAGTGAGCTTAGATACTCGCGACCGGGGAAACGACAATCATACACC
          ACGGTTGGCGGGAAATACATACTTTGTCGCGCTCAGTGGCAAAACTAACGACCACTTACC
          TTCGCCGATCAAGCCAACACCCACGGTACTGGTGCGTGGGGGGTACACGATTGAGGCCCA
          TCTACTACTCATATGGAAACCCACTTCCGCGCCACTGAAGGGTAAGCGTAACTACGCATG
          CATACAAGGAAGGCACACATTTTGAGTTGTGCCTGTTTGTAGGTCTGATAGTGGGTCCCT

          CGCGCACTCCCAGTGAGCTGTGCACTTATCTCAAGACTACCCCTTTGACCCCTGGTCCAT
          CACGCCCCCCCAGTGAGTTGTGCACTAATCTTCAAACTGTGGCTATGACCACTGGTCCAT
          CACGCCCTCCCACTGAGATGTGCATTGAGCCCTAGCCTATTGTCTCAGACACTGGTAAAC
          CGCGTTGCCACGGTGAGTTTCACACGTTTCTACCGACCAGAACTCTAAACATTGCTCCCT
          GACTCTGCTTTCGAGAAACTTCCTTTCAAATCCGGAGTATACCTTCAGATATTGGGATCA
          TTCATTGTCCCGGTAGCATCCTCTCTCGTCTCTGGCTTACAGCTGCTGATCTTGAAACAC
          TCCGCTGCCCCCATCTGAAAACACCCTGCGTCCCGCCTAATAATCTCAGCCTTGACATTT
          TGTTCTTCATCCGCAGGGAGATAGAGACTCCCCACACCCTGACTTCTAAACTACGCGCTG

          AGGCGGACAGAGATACAACCCCGACGGACAGCGTAACTCGAACACCCAATATGTTGAATC
          AAGCGGACGGAGATACAACCCCGACGGACGGCTCAGCTGAAACACCCAATATGTCGAGTC
          AAAAAGACAGAAATATAACCTCGACGGATCGCGTGACTCAAACATCCGACACTTCACTTA
          AAACGAGCAATGGTGCAAGTCCGACGGACTACGTGCTTTGGATATCTGCTTTTTAGCTTC
          AGCCTAACAGCAATGCTAGTCCAACGGATCAAGCGGATTAAATAACTAGCGCTTAGCTTT
          GAATGACTAGCTATGCCTGCTGTACAATTTATGTGACTCGACAGCGGGGCACCTGGCTTC
          ACCCGTATGGTAATGAGTGACGACCTATTAATGGCTCGTATAAGACAAGTAGACTGTTCT
          AAATGTATTCTAGGGACATTAAATGGGTCTGCACGAGCAATGGGTTCCGAATCAGGGTTG

          CGCGCCCATGCCGCTCGATGGCCCCGAGCTGGTGACAATTTTGGTCTGTATCTACGGATT
          CGCGCCTGTGCCGTTCGACAGCCCCGTGGTGGAAACAATTCTGGTTTGCATCCGCGGACT
          CGATCCTATGCCGTCCGACGGCCCCGAGGTGGAAACAATTCGGGCCAGTTTCCATGACTT
          CAAGGTTATGCTATCTGGCCGACCCCAGGTGGAAACAAGCCTTCAAGGTATCCACGGTTT
          CATATTCACGCCATTCGGCAACCTCGATGGGGAATTAGATCATCAAGGCTTCCATGACTC
          GTTACTCACGGTATTCGGCAGTTCTGGCGCAGAACTGATCCCCTACGGCATCATCGGCTC
          CGTCATGTGATTGCCATATCGCTCCGTCCTGCGTCTAGTTTCAAAAAACTTCTTCGGATC
          TGGGGTACAAACACACCGGTACGAGGATCTTTCTCTCCTGCTACATGCCATTCAAGGCGG

          CGGTATCAAAGGGATCAGGAACGAAGATTTTAGCCTAGTACGCTCTATACCGACACTTGA
          CGGTGGCAAACAGAACAGTAATGGAGATTTTAGCTTAATATGCTCTATCCTGGCACTTGA
          CGGATTCAAAGGAAGCAGGAGGGAAGATCTTAGCCGAATACGCCCCATACCACAAGTTGG
          TAGAATTAGCGGGACTGGGAGGGAAGAACCTCCCCGATTACGCATTATCCTTACACGTGA
          TGATGTCAAAGGGGTCCCGAGGGTAGTGTTTGCATGAGTTTGCGCTGTCAGGCTCCATGC
          CGGGGCTGTATGGCCTGGAACCGAAAACATTAGGTATCTCTGTACAATTCAACTTGAAAC
          CGGGGCCTACACGGACTCGAGATGTGGTGTTCGATCTTCCGGGACGGCCCCGTTATGTGC
          TATGGAATGACGTAATTAACAATGGCGCTCGTGCTGGTACAGTCGAGCTCTGATCCAAAG

          GTCGTAGTTCGGCCGTTAATGCCGGTTCTGCGTGCGGTCGATTCCTCATCTGTGAAGTGA
          GTCGTAGCTCGACCGCGAATGCCGGTACTTCGTGCGGTCGATGCTCCATCTAGGGTGTGA
          GTCCCAGTACTATTACAGACGCCGATATCCAGTGCGACCGATGCATCAACATTGCTATGA
          GCAGTTGTCCTACCGCGAAAACGGGCATGTCTCGTTGCGGGTGCACCAACGATGACGTGA
          GTCGATGTTCTGATGCGATTCCTCGTATCTGTTATGTTTGATGTTTCCGCGGTAATATGG
          ACTTTTGACTTGCCGCATATACCGGCGTTTACTGTATTCGGTGTTTAGGTAATGCCGTAA
          TTAATTGCTCAGCCTTAGTTACCATCGACTTACATGGGCAACCCCAGTACATTAGAGTGG
          CCCCGGGCTGCAGTTTTATAATTGTTCAATCACCTGGTTTGCGCGAGTACAGAAATACGC

          ACCTCCGTGAGTGCAATGGGAGACAGACTCCGAAAGGGCCATTCATCCCACCCCCACCCA
          ACCTCCGTGAGCGCAACGGGAGACAGATTCCAAAGGGGCCATTCCTCCCATCCACACCCG
          TCCTCCGTGTTCGCGACGGGAGACATACTCCGATCGGGCTATTCATGCCAAACTCACCTA
          TCCTCCGCGTTCGAATAAAGAGAGAAGCCCTGAAGAGGCTACGCCTCCTAGTTTTATCCG
          CATACCGCGCGCTCGGAGGAAGAGAGGTTCCGAGGCGGCCAAGCTTCTCAATTTAACCAG
          ACTATGGTCCTTGGGACGGAAGAAAAAGCCCGAGAACCGAAGACTTACCACTCAATCGTG
          CCGTCAGCGTAGAGTGCGGCTATCTGCACCCTAGGGGGGTGCAGCCTTGGCTCAAGAGCG
          CCTCCCGTGCGAGCCTTTCGGATCCAACTTTGTGGGGTGCGCCATTCTCGTTCACTCGTA

          TTTAGGATAAGAAAGGGCAGCCGTCCCCCAACTGCTTGGCATCGTGCACCCAGATGGTTC
          TCTAGGATAAGCAAGGGCAGCTGTCCGCTAACTGCTTGGAATCGTGTACCCAGATGATTC
          TTTAGACTGAGTGAAGGCAACTGCTCGCTAACCGTTTGGAACAGCATACCTAGACAGTTC
          TTCAAAGCCAGGAAACGGAACTGTCCGTCAACTGCTCGGAACAGGGTAGCCAAGTCGTTT
          TTTATAGCGCGCGCAAGTACCTGTCAGTTGTCCGTTCGGAAGGGGCTCCCAATATGGTGT
          ATCGCGCCAAAACGGAGCACCCCAAACTTAACAGTTGAGAATAGAGTATCTAGGTTAGTC
          CGTCAGTTGTAAGTACGTGTCTACTCTCCAATGACCATATACCGGGTATCGTGGCCGAGT
          TGGCCGATTGTAGTGGGTGGACGGGCGTCGGGGTATCTCCACCAGAAAGGGCATCGGAAA

          CCCTGATTAAAGCACGAGCATTGAAATGTACTCGGCAGCTAATTCTGTCCTCCTCTTTGC
          CCCTGGTTAAAGCAAGAACAATGAGATGTAATCGGCGACTATATTTCTCCTCCGCTTTGC
          AACGAATCGAGGCGTAGATAATAAAGTGTACTTGGCGGTTAGTTCTTTTTTTCCCTGTCT
          TTCAGGTCTCAACCTAGGTGATAGTATTAATGCGGCGGTTTTATTCGACTATCTTCGTCA
          CTACGATCAGAGCACAGAGACTGACGCGCGCGTGGCGGGTCTGTGTGCCTAGTTGCGCCC
          ACCAGATCAACGTAAGGATAATGAGCTGCTAGCGGCGGGTTAATCTATTTAGTACCGTCC
          TTATAACTACAGTCATAGTACTGGGCTGTGAATGTCGGCCCCATACGGTCGGACTGCTTA
          CATCCATGAGTGTTCGAGTGAGGTATTGTTTGCGTTCGCAATATCGAATCCGTTTGGCTT

          AAATGTACTATCCGCACAAGTATAGACAAAACGAGCGGGGGCAGGAGTGGTAGGAGCTCC
          CACTGCAATACCAGCGCAAGTATAGACAAAACGTGTGGGGGTGGGAGTGGTGGAAGCCTC
          ATGAGTACCGACACCACTCGCGTAAACAAAGAGTATGAGGACGGGAGTGGTAAATGACCC
          AAGCGTACTAACAACACGCACATAGAATATGTGTTCGTGGACGGGGGCAATGCTAGACTC
          CACCACACGACCTCTTCATGAGTAGACATACAGTGCGGGAAGGGGTACGGTACAAGACTT
          GGGCAAGATATCCGTACCCTTAAAGACTAATGGGGGACTGGCGGGAATATCAAAAGGTAT
          CACGACGTCACTGGATCACCCTATGAGAACCGTGCATGGCATGAATCTAGTGGTAGACCT
          CATCTTGTGATAGATTGACAGAATGAATAGAACCCGAAGTGCGGCTGCATCGGCGGGGAT

          AGAGGCGCGGCAGGGTGTTGACAATGAGTATCGCACGGGT
          AGGGGCGCGGGAGGGCGCTGACAATGTGCATTGCACTGGC
          AGGGATGCGGCATCGCGCTGAGAATGGGCAGGGTACTCGC
          AGATTTGCGGCAGAGTACCGACAAAGTGAAACAGATTGAC
          CGCCGTGAAACAGGGTGCCGATATCGTGAATCACAACGGC
          CGTCATCCGACAGAGTGCAGAGAATATGGATCCTATCCGC
          CCGGGTTCAGATGGGACTCCACCGAGTTAACTACAATTTC
          AAGGAATCGGAGGAGTGAACTTGCAGTCTACTGGTCTTCC

