 8 1000
t1        TAGGGTTGTGTATTGCCACTGCGCATCTGAGGACCAGAAAGACTCAGGTTCAAGTTCTTG
t2        TAGGATTGTCCATTGCTACCATACTTCTGGAGACCAGGAAGACTTAGTTACATGCTCCAA
t3        TAGAATGGTTCGGAGATGGAGACTCTTAGATCACCCGGAACGTCCAGGCGGGTGACCGTC
t4        TAGTATCGTTAAACGTCGTCGTTCCCCGGGGGGTCACGTCGGTGTCAGGGTCGATCCGCT
t5        CCGCGCCCCCGACTGTTGTTGGCTTCCTCCTATGGTGGCAGCTGTCGTCTTCTGCTTTTA
t6        CCGGGCTTGCGGAATCTACGCCTTTCGGGGTATTCCCGTAAGGATGACCCTATGGATTCG
t7        TGGATTAAATGTGACCTTTCTTCGCCTTGAGATTTGCTAATCAATAAAGTTTAATACGCG
t8        CAGCGCCCGGACCCACCTCTACCAGCCGGAGCCTCTGGTTCTAGGCAAAAAGGAATCCGC

          TGGGAATTTTCCCTTTCCGGTAATTCACCGCCTGGGAACGCAATCTGAATCCGTTGTTCA
          TGGGAATTTCCCCTATCCGGTGGGTCACCGCCAGGGCACGCAACATGAATCCGGTTGTCA
          TGGCGGCTTCACGTGGAAGGAAGAAAAATGTCACGATGGGCTATAGACGTCTCACGAGCG
          CTGGGCGCATCTATAGTTCAAAGCACACTGTCATCGCGCTCAGGTTCCTGCTGGAGGGTG
          CGGGGCCGATGTGCAGCGACTGAAATGTCAACTGATAGTGCAAAACGTTATCGGATGATA
          AGGAGAGTAGATGCGTACAGCGGACCGTTGTACCATGACGCGGTTACAGACTAACGGGTC
          CAGTGAACGTATGCTTTCGGTGAACTACTAGCTTATCATCCGGAAGTAACATGTTGGAGA
          CGAGGCGTTCACCAGTGTCTGAAAACCGTATTATGCAATACACGCGTTTACCAGTTCATA

          TCCTAGGCCAGAGACGCCGTGGGTCGTGTCTGATCACTCAGGCCTCTCAGCTGTCGCATG
          CCCTAAGCTAGGGAAACCGCGGGGGTCGATTTAACACTTAGGTCTCTAGGCTGCCGTAGG
          GTAGAAGATTGGATAGATATGCAGATCGCTCCCGCTCGCAGGGTTCTGAAAAGCAGCCGG
          TCTAAAGATTGTTTCAACACAGAGAGTATTGCACATTGTAAGCACCTGGAGTACCATGAC
          TCTGAGGTTAATTGGGACACTGAGATAGTCGTGAGTTGCAGGAGCAAGCAACGTCAGAAG
          AGTAACCACGTTCTTGTCATGGCCGTTCTCCTTTAACGCGATAAGCGGTAATACCATACC
          TCTATCGATCGGAGTGTCAGTGATGCCGAGGCAATGAATGAGCGTTCGACAACTCGCGAC
          TCTGATTGAAAACAAGCTGATTCGTCACTCGTTACGTGATGAAAGACTAAATGCGTGTAG

          CCTAGGCTCAAGAAGGATCGGTAGGTGAGAAGCTGCTTGTCCTTCCAGGTACGCATTGAT
          CCATGGATCAGAAAAGACTGGTAAGAGTGCAGCTGCAAGCATATACAGGTACACACCTAT
          ACTGCGGTACAAAAACTAACACATCTGTCGCACCGACCATCATCACAGCCCTCTTCGAAT
          GGAAAAATATAGACGAGAATCCATGTGTTCTCTTGATTACATCCTTAGGTATGCTTCAGG
          ACAGGTCTCGTCACCACATATTACGTTCCATAAACGCCACTCACCTCGCTTCATGAATGG
          AACGGCGGTAACTTGACACCCATGCTTCTAGTTCGGACTGAATTAACAGCTGTATTCATT
          ACAATATTTTCCGCGAATCTCCGCCTAGTCTGACGTTTGTGCTCTGGGGAGTACGTATGC
          AGACAGTGCGGTAAGAGCACTTCGCTCGCAGATCCTAGATTCCCCCTGCGCCTGTGGTTC

          GATTTACAGTCACTTTAACGTAAGAGAATTCCTCAAGGCAGTCTTGAGTCATCTCCACTT
          GTTTTGCACTCACTTTAACCAACGAGGTTTTTTTAAGGCAGTACTGCCCCATCTCCACTC
          CGTCAGGGGCTCGTCCGGCGAATGGAGATCCAGTAAACTCGTGTTGCCTTACGATTATCC
          GAGCCGTGTCTAGGTATGCCTCTACGTCAACCCACACTTTGTGTTACCTACCGGCGGAGT
          GGCTCTCGGACCGTTTTGATATAACCAAGCGTTCTAGCTGACACTATCCTCTAGTCCTCC
          GACACGCGGATATATTGCGGCCCTATCCCGTACAGGGTTAATGGATGGCTACTTACCACA
          TGCGGCTGATGTCCCTCGTCCAGCTCAACTCCCGTGGGCATGCGGGTTCCAAACCTGCGT
          TTTCGACAACTGTCTTTGCTTCTACAAAGCCTTGAATCTCGACCTCGATTATCCGCACGG

          AGGATGGACCTTTGCATGAGTCCGTTTTCGTATCAAGCGCTGCTCGGCCCCGAGCATTAG
          AAGATGGAACTTTGCATATGACCGTTTTCACATCAAGTGTTGCTCGACTATTCGCACTCG
          CATTCGGGGTCTTTGAAGGAGATGCTAAATTACTCGGGCTCTCGGTATTGTCTGTGTTCA
          AGGACTGTGTGTTTGAGGCCTTGCCAAGCTTATCTTGCAATTACTAGACGGATACATCCA
          AGAATAGATTGCTAAGTGCGTATGCGCCGGCGACTTTCTCACGTTGCCTCCCCCCTATTT
          ATGCAGGGATATTTGCTCTAATCACAAGGTCACCCCGATAGGGCAGAAAGTTTGGGTAAC
          ATGTTGGTGCTTTTGCGGCGGCGCTGATGCCCTAGGCACCACGCACGAGTCCCAAATGTA
          GCTTGTGAGGACCTAGTCCGCTGACGAGACCCTATTGCCGCCGCAGTTGGCTTGTTCGCG

          CGCCGTCGAATTCCGATGATTTCACTTGGGTTCAGAATGGGGCAGGATCGTTAACATCAG
          AGCCGTCAGCTTCTGAAATTCATCTTTGGGCTGAGAAGGGGACAGGACCGTTTATATCCA
          AACTGTTGTGAACAGCGGAACTGATCTGGGATACAAGCGAAACTAATCCCCAAAAACTGG
          TGTCAGGAGAATTAAACACCGAATCTGAAGTCAGATGAGAAAAATAGCCTCACCAGTTTC
          CGGTGGTATGGCCGGATATACACCTTCGAGGCAGAAGTGCAGGGGCCCAGCGTTGGTAGT
          CACCGATACAACTAAGGAGCGTATGCCAAAGTATAGGAGAGGTGCCTTCTAATGCGAGAT
          TGTGAACCCCCTTACTTGGTTCATATGTGCTAATAAGCAGGGAAGTCTTGACTTCGAGGT
          TGCCAACTTGAATGATTTTATCTTTTCGCGCGGTAGAGGAGCGAGTCCCGAAAGATTCAT

          CTTTTATAGCCGTCCGACGCGAGAGAAAGCATCACGTCCAAAGCGATTACAATGCTGCCT
          CATATGAAGCTGAACGGCGCGCGAAAAGGCATAACTACAAAAGCGAGTACAATACTGCTT
          TCTGTGAACTACGCTAGTACGGCGAAATACGCCACTACACAAGCAAATACCGTATTGATT
          TAGGTGGGAACGAATAATGCAAAAGGAATTTATTGCATGATTGCGAGTTCTACAACGTTT
          TCCACTTGGCTGGTTGGTGAGAGACGAAAGGTTTCGTTTAAGATCTTCATCGCCTCAGGT
          TAAGATTATATTAGTGCTCGCCGGATACAAATATCGTGCGATGCAAAGTAAGTCCGTCGC
          ATAGCATAACTGGCTCGGCTAGAGGCAAACGTTCAACCCAGAGCGCGCAAGCTTCTGTAA
          TTTGATCGATGTGTTAATCTCCCTTTAACGCCTAAGCTAATAGCAAACGGAACTCGGTGC

          CGGTACTGAACTTAGCCACTTAAACACAGGATAGGTATATTAGGGCACTGATGTCGAAGT
          CGTTAATGAACCTGGCCATTCAAGTACGAAAGTAATATAATAGAGCAACGACGCGGGAGT
          TGGATACGGTCCCGGCCATTCAGGTATCGGATTGGTTCATTACCGTGACACTGTTGGGTT
          TGCACGCGCAAACGCGCTTCCCGGAGCGGGGTAAATTGCTTGCAAACCCAACGGAGCAGG
          TGAATGCCGATCTATCCACTAGCCATAAGGACGTGTAGCCTTGTAGCTTGACGAGCTAGT
          ATGTCATGCTGGCGAAGATTTAGCCGAAGGGCCGGGACCTTAGTCATTCAGCGGCGCGGC
          TAACTATAAGCGTACGCGGACAGTGAGTGGCAGTTTATTGCCAACAGTCCAGCTGAAGAC
          CGCCTAAGAGGATGAGCTTCTACTAGCCGACGTGATACCACAGGGGTCTGGCATGTTGTC

          AAGTTATCTCAAAACTTCCCTTTTCTAGCTGATTAACACATGATCGGCGTTGGAAACGTT
          ACATTACCATAAAACTTCCGTTGTCTAGCTGACTACCACCTGCTCGGCGATGGAAATGTT
          ATGTTAAAACAGGGCCGTGCCTTTCCAATCAACAATTGGATGGTCAACCTTTGAAGTGCT
          ACGTTATTGTAGAAATACCTTTATCCAGTTATCAGCCGCACTACTGGTTTAACCGCCGAT
          ATGACATATATAGGGGGATGGCCCACGAGACGCTGTAGGTTGCGCCTGGTTTCCGGGGCG
          TCGACACCAGATAATCACGCAGTTTCGGCCTCAGGTAGTATGACTGGATTTATTGGAACC
          AAGTAGTGAAGATAATTGTCATAGCACATTTAAAGTTATATGGGTAGACCAATTGAGGCT
          ACGCTGTAGAGCCGTTCATCCGTCTTGTAATTCGGTCGCAATCCTCGAACCAGGGGTAAA

          GATGGCCTCCTGCCAACGATGGGAGGACCCACTGAAGAACCGTTACCGGGATAGTGATGA
          GGTGACCTTCTGCCGACGTTGGAAGGACTGACTGATGAACCGTCACCGGGGTTGTTACAA
          CACGATCTTCTACCACCACCGGGCGGATCAATTTGAAGACCCCAACTAGAGAAGTGATGA
          GCCCATAGGCTTCTAACCGCGAGGACGTAAGGCACCGGACCTCTGTAGACGGCAACCTGG
          AACGCCTTTTGATCATTGGGACAGAAGAAGTCTCGGACTCCCACTCCGAACAGCTGACGA
          ATTGAGTCTGAACAGTTGCCATGAGAGCAGACCTAAGGCGTCTCACGGGTGCCGAGTAAG
          AATGCCCCACGGGAGTCCAGGAAGGTATAGAACTAGCGCGTCCCACGGCAGCTACAATCG
          CTCTTTCCTCAGATTGCAATATAAATGGAGGGTTAGCGTCTTTCTTTGCTAAACGAGCGG

          TAACGAAAGGGATCATTTCCTCACGAACACGGACATTATGAGTGAAGAAGCTCCGGCGGT
          CAGCGATGGGGGTCATTTCCTAACGACCGTGGACATGATCAATACAGAAGGTCAGCAGGC
          CGTTCTCAAGAATTCCGCTCTCGCGATAGCGTCTCATTATGATGTAGAAACTGCGACGAC
          TGATAATCTGGATTGTTGCCTTACGCTAGAACCTAGTGTTGTTGTAGAGAAACATGACAT
          AGTTAAGAAAAACCCCTATTTAAGGCTTGAACCCGACACTGAACGAGGGTAACTTGTCAT
          TCAAAAAAAAGGCCTCCATCTGGAGCGTGATACTGGCTTTCGCGTCAAGTTAGAGGTCAA
          CATCCTAAGGTAGCTGCCCTGGGCCCAGGGTTGACATGAGGGTGTAAGATAGTTCGCTGC
          TATAGGAGGGGGGCCTTTCCATAAGCCCGATCGTCATAGGATGGTGAAAAAATCCACGCT

          GGTGAAGCAATTGCGCACGATCCATGGACGGCCGCACTCACCTCGAAAGGCCATGATACC
          AATAAGGCAACCGCATGCGATGTAGGGACTGCTGCATTCACCCTGAAAGTACAACGTATC
          GGCAAGGTGTCGGTGCGTCTGTCGTGTACGGCTGCACTTATGTACAGCGAATAATTGACT
          CGTTTGTTGCCGCTACTGTCCACGTAAGGCCATGCCGCTACGAATGAAGTAAAAGCGAGG
          GCCTGGGTGTCTGACCGTCGCTTGTGGATCCCCGTACTAATTTATACAAGAGAGTAAATC
          AGCCCTAGCTCGAAGAGCGGCCGTTGAATTACTACGCTCCGCTTTACAAAGGTAGTAGAC
          CATACAAGGTCAGCATGCCATCCGTACACGTCCGCACCCCTCTGAAAAGGGTAAAGTTGT
          TATCGGAAGTCGAGAAGGCCTTATCGAGATTTTGTATCCTTCGTCACGGGAAGATATGGT

          CTTACGAGAAGACTGCCTGGCAAAGGGGTCAGGTTATGCGACGGGGGCTTTCTTTGTGAT
          CTTAAGAGAAGACTGCGCAGTCTAGGAACACAGTTCTCTAACGGAAGTTCCCTTCATGGT
          ATAACGAGCAACCCGCAGAGCTTGCGCACAGGAGTCTGTCACGCGAAGTAATCCCATGAC
          TTAATGAGGCCGATCTACGGCTTCGCAACAAAATTAGGCCCCGGGGGGTCCTTAGGTCGC
          ACCATTAATGAGGGCCCAAGACATGGAGCGGGTAACTGCAATAGAGTCATAATTGATCGT
          CTTGCTGAAACCGGATGGGACCTCGCTGAAGATTTATCCGAACAGGTCTACGTTAAAGTC
          CTTCTTGGCTGGATATGGCGAATATGGGAAGTTTTCTGTTGGTCGAAATATAGCGACGGC
          GGAGTAGTGTGAACCTACGGCTCAGGCGATAGGAGTCGCTATTGGAGTTACACCCAAATG

          AGGTTTTTCGGCTGAGGCAATTGTCAATCCCGTGGGACTTTGTCTACGCTTGGACCTTGT
          GGGTTTCCCGGCTGAGCCAACTTTTCATGCCGTAAGAAAACATTCGCGCGGAGACATTGA
          AGGCCAATCTTTTGCCTGAATAATCGACGACGTGTAATGACCGCCACGCCTTCCTCATAC
          ACACTGACTCGTGGGCACTCACATCGCCCGCAACAATAGACTAATATTCTTAGTTTTCAT
          GAGCTCACCGATTTGGCCCGCCATCCCCGGCGGGAGACAACTCTACCTCTCGATTACTGA
          GGTCTCTATCATTTGAATACATACTAGCACCGTAGGATTGATCCCGGCCTTGTCTTTCGC
          ACGCATCAACGCCGCAACGACCTTTCGCAAAGCACATCTGGCCTCTATCTTGACCGTTTC
          CGGCCTTTAGGCTTGATTCCCCGATCTGCGTGGGTATCCCTCTAGCCTTCTGACCCCTGA

          AGGGGCGTTGGCAAATCGTGTTCGTCAAACTTAGGGACGCGAAGGTCAAAGGGAAGTAGC
          GGGCGTATTGGTAAATCCCGTGCGTTAAATTAAGTAATGCATGGATAAAATGAAAGTAGT
          TGGGGAGTCAGGGCATCACGTACGCCTCGTCAAGAGATGCTAGGTAGTAATGGGAATAGC
          TCAAGGCTTAGAGCACCTTATGTTTTATAATTAGAGGACTGAGGTCACCGCAAGACTTGG
          CGGCATGTTATAACGTAGTCTTAGTTCCAGCCTGCTACCAAACGACCCAGTACATTGCGT
          ACGAGCGCTAGTGCATTCGTTTGACCCTCGCCCGTGTCCGAGGGGTGCCAAGGGCTTCCC
          GTGAACGCTAGAGAATTACGTACGATACGCTTAGGGCTTAAGGAACTTGGCGCGTCCCCT
          CAGGGGAATGGGGGGGCGTCCTAACGCCATTTCCAAGCTATAGAGCGAGGGTGACAGAAC

          ACAAACAGTCTATCGACAATAGGAGAGATTAGCGCCCACT
          ACACGGGGCCGCTCGTCAGGAGGAGAAATTACCCCCCACT
          ATGTGCGGTCTCCGAAGATCGAGGAAAGTTAGAAAACGTA
          AGCCGCTTTCCCTGAGCACTTTAAAGGGATGATTCTTACG
          AACGGTGGACCCCGACTAATCCGAAGGATTAACGCGGGTC
          CCAAATGCATTTCGGAGATGGCCAATGACGCATCTACCCC
          TGAATCACGTTACAGCAACCGCTAAATAGGAATTCCCTCG
          TGTCGTACTTCCTTGTGACAACGGGAGGCGAAGCCGCTTC

