 8 1000
t1        TGATTAACACACCTACAGGGCGCCCCTCAGCCGTGAATATATCACTTATATCACATTTGG
t2        TAAGTAACACACTTTCAGGGCGGCCCTCGGCCGTGTATAAATCACTTACATCACATTCGG
t3        CAATGCAAATCACTCGCATCAGTGCTTTGGTGCATTGAACTACCTGTCGTTAACATCTAA
t4        TCTCGAAGGATATTGGGGTGCGTTCTTGAGTCTACCGTGCCATTGGCGCAATACAGTTAT
t5        TCTATAATTGTGCTACGCGTTAGTCTCACGCTATTGCACTCATTTAATTCGGTCCTGCGT
t6        TTTTAAAGCATTCTTCGGGTTGGTTTCAGACTACTACTATCGTCGATTTCTGTCGACAGT
t7        CTACTTAGACTACACCCAAGCAGTTTCCAGCTGGAGGCATTTATCGTCTATTATGTTTGC
t8        GTAATTAGATTACATCCTAACAGTGTCCAGCTGGGGGTATTTATCGTTTATTATGCTTGC

          TGATCTGTACACACAACCATATATCCCCCACAACCCATACACTCCCGACAACCACCTATG
          TGATCTGTCCACACAATCATATATTCCTCACAACTCACATACACCCGACAACCACCTATG
          CCGTCCGCGTGCATGAGGAAAAAGTTTCTGTCCAAACGACCTCGTGGGTCATTGTTCCGT
          TCGTAACCACATGTAACGAGCAGACTTTAATCCCCAGAATTGAGCGAAAGCCCTCCCTCA
          CAATAAAATTGGTTCTTCATAGAAGGCTAGATGTTAACTCCCGGCTGAGTCCCACAACGG
          CCATGAATTGACTTATTAATAAGGCCCGTAACGTCGGTTTCCAGCCGCCTCTCGCACCGG
          CGGGTGGATTTTACTCTCGTAATGTGACAATATCTTACTCCTTTTTGAGCCCTTCAATGG
          CGGGTGGATTTTGCTCCTTTAACGAGATACAATCTCACTCCCTTTTGAGCTTCCCAACAG

          GCAGTCCTACTGTGCGTGTCAAGCTCTAAGTCCCAATACTACATTCAGCGACCTATACAG
          GCATTCCTAGTACGTGTGTCAAGCTCTAGGTCCCAATACTACATTTAGCGACATATACAG
          ATGCGTTAACTAGGCAAAGCAGTTGATGGATGCTTTCTTCTCGAGCGCTGAACCGCAGGA
          ATGTCCCTATTGGGTGAGATGGGTGATGGATCCATAAACTTCTGTGAATGGTGATTCCGA
          ATTCTCCGAAAAGACGAGATACCGGACTAGCTGCTCGTACCCTGCAAGTGAAGTCGAGGT
          GTTCCTCGAGCAGCTGGGCCTCAAGACCAATTGCACATTAGCTGTTAGTGAAGTCAAGGT
          GTCCCCCTTGTGGGTAACCTAGGGTAGGAATGAGCCTGACCCCGCACATGGCGGTGAATG
          GTCCCGCTCGTGAGTCACCTGAGGTGAGAATGAGCCTGATCCCGCACATGGCGGTAATGG

          AAAATGTTAACTTACTATCCTTTTATATAATTATCGGCTGCCACGGTGTAGCGAAACTCA
          AAAACGTTAACTTATTATCCTTTTATACAATCATCGGCCACCACTGTGTCTCGAAACTTA
          CTCGGGTCGTTCTACTTTAAATAAGTTCAACGGCTGGTCGTGTTGCAATTGCATATTCTG
          TTAGCGGTGCCCGACCTTGTCTTCATCGAAAGAACCGCCGCATGGCACGAGTGCTGGTCT
          CCAATTAGGAGAAACCGTTATCCGATCTATAGCAAAAATCTAAGCCTCGAACGCAACCCA
          ATAATTGCCATAAGTCCCCATTTCGACTCTAGTTAACAATAAAACTCCAACTGCAGCCCG
          TCCACAGCCGTCAACCTCGGCTCGCCAGAAGTTCTCTATTTTCCTTCAATACGCGCGCCA
          TCTACGGCCGTTAATCTGGGCTCACCGGAAGGATTCTACTTTCCTTCAACACGCACCTCA

          CGAGAGCGGAACAATGTGAATTGGACTAGAAATCTGCAGTCCGTTCAAACGTCCCAATCT
          CGAGATCGGGACAATGTGAATTGGATTAGAAATCTGCAGTCCGTCTAAACGTCCCACTCT
          CACATTGAGTTTGAGTCCGTTAGGGCGAGATATTAACAGAATCATCCGATGTATGTCTAT
          CAGGCCGAGGTCGCGCTCCGTTAGGGGGGTTATCAATGTGCCAACACGCTGCGTGCGTAT
          TACGTGCAGGGAAACCCAAAATGACCCGGATTTAAGTAGGTAATTAAGCTCCGTATTCGT
          CGCGTCAGAGGAAACTCCGAATTAACTGGATCCCACGAGGTATTAAAGCTGTGTATTAAA
          GGCGCTTAAATACGGGCGTCAAGGGCTCGTATTCTCTGGTAGGCCTATAAGCGTGCTCAA
          GGTGCTTAGATACAGGCACCAAGGCCCCGTACTCCTTGGTATGCCTATAAGCACGGTTAA

          ATTTGAACAGTGGTGCAATTTCGAAGAGTAAACGCTCCGCGATTGATGACATAGTCAATA
          GTTTGAAAAGTCGTGCAACTCCGAAGAGTAAACGTCCCGAGATTGATGCCACAATCAATA
          TGTCAACTAAGGGTGAAATCCTACGATGCATGGAAATTGGGATTTATAATACGCCTTACA
          CAGCGAAAGGCGACGAAACTTGCAGACACAGGGAAGTTGGAATCAATCATGGTTTAGGCG
          TCCGGGAGTCGGCCAATTTTTTACCCATAGATCGACCTGAAGCCGCCGACGTTTCCAGCC
          CTCTGACTCGGGCAGATTTTTTAGGTGAAAAACGATCTGAAGCCACCGACATATCTAGCC
          TTAGGGATAGGAGCAAGGTTTCTATTATCAAGTAAATTGGAAACGAATGCCTATATGCTT
          TTAGGGACAGCAGCAAGGTTTCTTTCATAAAGTAAATCGGAAGTGAGAGCCTAAATGCTC

          GATTTCTGGGACCCTGTAAAAACTGCGGCTCCAGTTATGCAGAACATACCTACTTTCAAC
          GATTTCTGGGACCCACTAAAAGCTGCGGCTCCTGTTGTGCGGGAGATATCTACTATCAAC
          ACCCCTTCTCTTACTGTAGTTGATTGTTACACCATTGTGGAAAATACGTCATCTGGCGCC
          GACCACCGATTGATATCAGTCATTCTACTTATTACTACAGTGAAAGCCCAATCAGCGACT
          GGAATTCATACGGCCGAGGATAATATGTTAATTATCTCGAATATGGGACATGTCGCAGCC
          GACATTTACACGGGCGGGGACACTACGTTATCTATCCGGACTAAAGGAATACTTATGGCG
          CACGCTTATGAGGATACAGCTACTACGCCTCCTCAAATGGGGATTAGGGTTTTTCCGGCC
          AATGTTCATGAGGATATAGCCACTACGCCTACTATAATCGGCACAGGGTTTTTTTCGATC

          TAACGAGCTCGCGGGCATCGCAAGCTCGGTGCCTGCCAGCCCTCCTCAACGGGGTTTAGT
          TAGCGAGCTCACGGTCATCGCGAGCTAGGTGCCTGCCATTCTTCCCCGATGGGGGTTAGT
          TAAAGTGACGCGAGTCATTCGAAGTAGGGGAAATACTACTAACACCAAGTGCCAGCTCAA
          TGGTTTGTCGCGAGTATTTAGTATTTCGAAGCAAGGTAATTCTATTGCACTCGTGCCCAT
          GTAAAGATAATCGATGGTCACATGTCGGAGACGTTTTAACTTTCTCTGAACAAGCCTGAT
          TCAAAGGTAACAACTCGACTCGCGCAGGGGATGTTTTAAATCTTGCAACCTAAGTTTAGA
          GTCCGAGATGTCGTCAAACTTATCCTGACGGTTTCGTCTCCCCTATGAGTGACACATATA
          GCTCTAGATGACGTCAAACTTATCCTGACGGTTTCGTATCATCTACGTGTGACGCATATA

          CCGTGCCTTCGGCTTGTCTCCCATTGTCAACGTTTCGGCACCGTTTCCCATCTAGGTACG
          CCTCGCCTACGGATTGTCTCCTATTGTCAACGTTTCGGCACCGTTTCCCACCTTGGTATG
          ATACACACCTCTGTAAGCTGGCAGCGTTTTCGCACTAGTACGATGTTTTCTAAATAGTGG
          GTTCAGTCTCGCATCATGAAGTTGTGCCGCTGTAAAGGCGGGTTACTTTACATCCGGAGG
          ACACGCCCCAACACTGCTGTGTAGTAACGGATTCCTAGTCCGCTCCTCCGGCTCCCAGTA
          ATACACATTCACACAGATGGCTAATGGCGATCTTTGAGTCTGCTTATTCTGCCCCTGTTA
          ACTTTCATGGGCCCTAGTAGGGAAGGTCTGTAGCTCAGTTCCCTCTCCCCAGTTCAGGAA
          GCTTTCATCTGCCTTGCTAGGAGAGGTCCGCAGCCCAGTTAACACCTCCTAGTCCAGGAA

          GACTCCTCTTAGGCGTCTGAACGAGTGGGCAGAGGCAAACGAGTTTCCCGAGTATCCAAG
          GACTGCTCTTTGGCGTCTAAACGAGCGGGCAGAGGCAAACGAGTTTCCTGAGTATCCAGA
          ACCAATATTCGACAGAGCTTGTAAACTAGTCGACCGGACAGCCGAGATCCCCCAACTAGC
          ACAACTGCCCAGAAGCCCCCGTTAGATGGCAAAGTAAGATATTTTTCCCACATAAGCCGT
          AAACCTCGACTAGATCAATCGTTGAAGGTCCCCAAGGGTATAGGTACCAGTGCAGTGCAC
          TAAACTCCCTTAGGTTCACTACCGACGGTTTATAAGGATGATCGTATCAGTGTCATGCAC
          ATGCCAGTATCAGAGTTCTCGCTTACCGGCATTGGCGCGGCACTTCCTGGTGAGATGAAA
          ATGCCAGTCCCAGAGTTATCGTTCACCGGCAATGGAGCGGCACTTTCTGGTGGCATGAAA

          GATTGACGTTGGCAAATTTGCAGAGCACTTAGGTGAGCCACGCGACGCGGATAGTTAGGC
          GATTGACGTTGGCAAATTTGAAGAGCAGTTAGGTGAGCTGCGCGACGAGGATAGTTAAGA
          AACTACGGTGGTCCTGACTATTGCCCAGCGGAGCTTCTTCGAGTTGCCTGACACATTAAC
          TGCTTGCTTGACTAAAAGCATAGGCCGGCAGGGCCGTCCAAGCCTGTATAACTGTGCACT
          GACTGGCCCTTGTATAAGCACCAAGCTGCTGTCTTGAAATCACAATCTTGTCCGTCAAGC
          GGGCGCTCACGGCATAAGCCCGAAGCTGCCGAGTTGAGATTACAATTGTGACCGTTGAGC
          GGTTAGTACAGAAGTATATATTACAAAGCCGAGATATGATGCCGATCGGGGCAAACGCGT
          GGTTGATATGTGAGTATATATTACAAAGCCGACATGAGCTGCCGATCGGGACAATTACAT

          CATCAAAAACACGGCAGGCGTGCGTGACCGGTCGGAACAGTACTGTTATCTTGGTATGGT
          CATCAAAAACACGACAGACGTGCGTGACCGGTCGGAACAGTACTGTTATCTTGGTATGGT
          TGTGGTGTAGCCAACAGGGTAACTTGGTAGACAGTCAGCCTCTTGCCGTCTTGACGGTGC
          TAATGTATACACACAAAGTTAACGCGACAACCAGGCCACGTATTGCTCTTGTGAAATGGC
          CAACCCTTACAATTTAGGACAGCTTCGTGCGCAGACCCAGTGTAGCCTTCTTTACCCGAC
          CATTGTTAATAGCTTAAGAGAGACTGGCTGGCAAATTCTATGTAGTCCATTTCGACTAGC
          AATAGGGGCAGGTGTGGAGTCGATCCAAAGGTCAGGCAATTTCAATCTACCTAGACAGAC
          CATAGGGGCAGGTGCAGTGTGGATCTGTAGGTCAGGTAATTCTAGCCTACTTGGATAGAA

          TAGACCCTTTGATCACTGCGCTGGTTTCCGTCATGAACTTTGTCTAGTATCATTATCTTA
          TAGAACCTTTGACCATTGCGCTGGTCCCCGTCATGCACTTTGTCTAGTATCACTATCATA
          TTGGCATACTAGTCGCGGTTCGGGCGTCTTGCCAAGTTATTGTTGCGCGCTTTACCCTTG
          CTGGACCACTGGTCTCCGTTCTTAGGACCCGCGTAGCAACTGTTTGACGTTTCTATGACG
          AAATGGCGTCGACTGCAATTTTGGTGCCCACGGCACTGGTTGTTTAGTGTACTTGCCATC
          AAAAGACGTTGATCGAGGGTTAAAAGTTCGCGGCACCCGCTGACTAACTTATATGCCATA
          CAGGCTCGCAAAATTATATTTGCTAATCTCCTACGCCCACCTGTCAAAACATATGATCAT
          CAGGCTCGCTAAATTATATTTGCTAATCTGTCGCGGCTACTTTTCGAAACATATGATCAT

          CCACCTGAATTTCGCGGTGACCTCAATCTTTTCGGGTCAATGGCGACCTTTCCGGATACT
          CTGTCTGATTCCCGCGGTGACCTCAATCTTTCCGGGTCTATAGCGACCTTTCCGGATACT
          TTGGAGGCCTTCGGTAGTACGGTTTATTTTTACGCGTAGCGACCGCTTTAGTCTGACACG
          CCACACACTCACTCCCTCTCGCTACACGTTATTCCGTGAGGGCCGCCTTTTCTCAACCAT
          CTTTGCATTGCCGCTTCGGTATCGTGTGCCCCTGAGTTCTATGAGTTCTTGCATAATGTA
          ATATGGATTACAAGTTTCAAAACTCGTATGCCCGGCTGCTGAGAGTTTTAGTGTTAAGTT
          TCCGTGATCTCGTATAGCGCTCTAAATCCATGCAGGTCAGCATAGTTACAGTATATGACT
          TCCGTGATTTAGTGTAGCGCCCTAAACCCATGTATTTCAGCATTCATGCAGCATGAGACC

          GGCACGCCAGGCACTGCCCCAGTAGACCCATAGGGATCTACAGAGCACGTATCCATCATG
          GACATTCCAGGCACTGCCCCAGTAGACCCGTAGGATTCTACGGAGCACGTATTTATTATA
          TCGGCGACAACGGAGAAATTGACGGTACTCTAAGAGCTTGACGTGTAAATTTAAGATACG
          ACGGAGATAACGAGGAAACCAACAAAGGGCTGAGGTTGAATAGAGCATAAATGAGGCAAG
          GAGAAGCTACTAGAAGTTTCGCTACGGTAACAGTACCCTTCAAAGGCTAACAGCCCCACC
          AGGAAACCGCTGCAAGCTGTACCACAGTAGCACAACTCTCCAAAGGGTGGTAGCCTTACA
          GGAAAGCACTACAGGAAACCGCTAAAGTGAGATGTCTATGTGAAGTACAAGGGCGGCATT
          GGAACGTTCTGCAAGAAACCATTGAGGTGAAATGGCCAGGTAAAATACAAGGGCGGTACC

          TAAAATTATATCGTAGGAAGGGCGCACCCGGACGGGCGGCTAGCATGCTTATATTCCCTT
          TAAAATTATAAAGTAGTATTGATGAACCCGGAGAGGCGGTTAGCACGCTTATACTCCCTT
          CTAAAGAACACCCCACAGGATGTGCACACAACTCATGAATTGACAGGCTTCCATTGGTCT
          TAAAAGACTCGTATATAAGGCGCAAACCTGGTCCCCGAGCTACTGTGTTATCATAGATTA
          ATCTTACGGCTCCTGGACGGAGATAACCCGACCAACTCCTTTAGGCGTTTTTACTCACTT
          ACCTAAGGGTTACTGGACGAGGATTGTCCAACTGACCTCCCTAGGCGTCTTTATCTATTT
          CTAGACAATCTTACGCAAAAAAGCCGTACGCACGGCCCGCCCGCATGCGTTCAACCATAC
          TTCTACGATCCTACACACACAAGCTATACGCATGGCCCTCTCGCTTGTGGTCAACTATAC

          CCGCATACCCCTAAGGCCATCGCGGCATATGGGCAATATG
          CCGCATACCTCTAAGGTTATCGCGTCACATGGGCAATATG
          CCGCTTCATACTATTGTGACGGGAACTACCCTATTGTCTG
          ACGATCGATCTTATTGGCACCGGAACTTATGCTTCATCAC
          CGACGCACTGTAAATGTTAGGGATACCACCACGGTCCCGG
          CCGCATATTATAAACATCATGAGTACAACCGTTACGCCGA
          TTTATAACTCGTGAATCGTCAGGCTACGACTCCAGAACCC
          CTTAAAGCTTGCGCACCTCCAGGCGCCAATCGCACAACCC

