 8 1000
t1        AGTGGGAACCAACGGTGGCGCGGCTCCCCCGATTGCCGGGAAAGGTAGCAAAATGCCGGC
t2        TTCAGGCACTGTAACCGACACGATCGATGTAATTATCCGCGTACACTAGGGTCAAGTGGC
t3        TGGCGATCCCAAAGCTGACATCGTATCTAGGACAGGAAACCTCTACTAAGGGCAATCGGT
t4        AACACAACGTGCTGCTTAGTTAACCCCCATGACCATTAGGCCGGACTTTTGTAAATAGGA
t5        CTCATACCAGTGCAGCTGACCGACTCCCGACAACTCCCAAAACGAGCAAGGTTATCCGGT
t6        ATTATACTGCAACAGATGACCGATTCCCGTCACCGACAAAGATGAACTAGGTAATCCGGA
t7        ATTTTATTGTGGCGCTGACGTATAACAAGTGGCTCGTAACGATGTTTAGGGATTTTCGGT
t8        AAAGTTACGCTAAGCCAACATCTTAGGTGTGACTCCCCGAGAGGACCAAGGCAGCCCGTT

          ATCTTTCTTAAAGCATTTAGCATATAAGTCTGGAACCTAGGTGTTAGTTTTACATAGTTG
          GCTGCTTCGGAGTCGTTTTACAACGGTGCGAGCTACGTACGCCTTCCCCACGCGAAATCG
          GTCTCTCCCATTTACTCTTCTAACGAGGTAGGACCTAAATGTTTTGGCATCACAGGGCTT
          CACACACCACATCGCCCTGACGTAACACTTAGGGACGGCCATCCCAGGCTCGAAAAGCAC
          TTACCTTTCTCGCGGCACTATACTAAATCAGATGTAGTAGGGGTTACAGATATGGTTCTG
          ACTCCCTTTTCACCGCACTCTACCACTTTGGGAGGGAACGGGCTCACAAATACGAAACCA
          GTTCTCCCTAACACCCTAAACGCTAAAGTGGGAACAGTCTGCACGACATACATCAGACCC
          ACGTTCATCGAGACTCCCCTCACCGAAGTCGCAATAGTTGGACAAATGTCTGCGGGGCCA

          CCACAATGGGGAGATGTTCGCTTTTTTGTGATCGACTTAGGGGTTTTCCTTAACGTTATG
          TCCTAGAACTTATTAACTTGTTGGCGTCCGACACTTTGAAAGAAGGGCCTCTCAGAAATG
          ACCCCTAGATAAGCCATTTCTTCAGTTGTAATCTTTCCCAAAAGACATTCTGTAGCAGTA
          CTGAATCAGCAGTCAGGCTGACTGCTCATAATTCATACTAGCACGGACCACGGCGTCACG
          GTTATAACAGGTTTGGATTGTAGTTCCACAACTATCGACGTGTAACGTGTGAAAACCGTT
          TACCTTGCTCGGGTTGATCATACCTCCAAAATGCTTGACGAGGGGTATCTTAATACTCCT
          CGCTTCCCCTAGGAGGGTCGCTAGGCCATGACGTTCTATGAACAACGGGTTTACATCGTG
          CATCCTCTCTAGAATGCTTTTACGTCCAATATTTTTAACGAGGAAAGACTCAACGTCTTG

          TTGCCTTTCCCCGGCTGCTAGCAAATGAACCTGCAACATACCACCTTTGATTCACCGCCC
          TTGTCGCACATATCGTGGGCACCTAAACTCATATTACCCATGACTACTGGCGCGTCGACA
          CCGTCTCCTACGACCCTAAGTACTCAATTCATTCTATAAATATGTATTCAAACGTCAAAC
          GCGTTGCCTTGCGCTTGCATACTCAAGGCGCCGGCACCAACTAAAAGTATATGGCTAGAA
          TCCCGGTTTAACACGAGTGGCTTTTTCTCTGCGCTATCCATTTTCAGTATTCCACGAGAA
          TACTTGTTCAAGATGGACGGACTCTCCCCTGCGTCGTCCATTATGAGGATTTCATGAAGA
          ACGTTACGCAATAATCACAACAGGTTCTTCTCGCTCCGCAGCGTAGACAAACCTCAGATA
          TTCCTCGAATGAACTTGTACATCGGTCTCCTTAATAAGACTTGTAGTAGCACCATCAGAA

          GAGATGAGGCCTCGGTCGTCACGGATTAAGAGTGGTATCGGATGGCATTATGATCAATTT
          TAGGCAGGCGTGGAGTCTCATCTGGACAACAGTGAGTCCGGGTCGGACCGCCGTGGTCTT
          AGGTGATGTCTGGAGTGGGGGTCACTGCACCGTAGCACAAGACCATGTTAGGACGTCAAT
          GATGTGATACCATAAGCGTGTCGAGTAATGACTGACGCAGGTTTAAGCCTTATCGAATCC
          GAAGCTGAGACCCGATGTCGGCACCTTGGGTACGGCGCCAAGCCGTGCGTGGCTGTTCAT
          GGTAACGTGACCCCATGGCAGTGATCTGGGACTGAAGCCAAGTAGTGTACGGCTGTCTAT
          AAAAGTAAGACCTGGTGCAGGCGAGCTCGGAGTGTCTTTTCCAAATGTAGATGTATCCCT
          AGGAGCATGCATGAATGCGAGCGAATTCACTTCGTACCTTGGGCGGTTGAAGATTGACCT

          AGCCATCCCCATGGTCTTTCTCCTTCTAAACCATCTGTCTTCTTCGGGTACGAGCCGTCA
          AAGCGTGACTTAGGCTAACTTGGGTGCATTCTACCTGAATCCGAAGATGTTGAGTTGTCC
          TGATAGGGGTGCGACTATATTTAGCATCCTTCGTCGCTTAGCATGTGCGGCAAGTTGCGA
          TTGAATTGTCAGGAAACACTTCGATTGTATGTATTCGCTTGTATGCATCGCAGGTAGCCC
          AGTCACCGACACCATGGATCCTTCCTCCCACATGTTGTGCCCAGTCGCTGCTCTCGTTCT
          GGCGTTCGCTCCCAAGGAACCTAACTCCCTCGTGTTGTTTCTGGGCGCTACACTCACCAC
          AGTGGTAGCTATCAAGGCCGCTAACTATATTGACACCATTCTCAGTTCCACAAGGGGCGT
          GGCGGCTACCACCACAGACTCTCTCTGTACAAACCCGTGCCTGTGCTCAATCATTGGAGT

          GAGGTCTGAGATGTCTCATTGAAGACTCCACTCAGATCGACAAAGACACACCTCCGGCCA
          TGTACCGTTAATACTTCATTTGGTAGCGTGACTGGCCCTTTGATACGCTAGACCTGTGCG
          CAGGCCGAGAAAATCCTACCCCCGGACTCGAAGGAGTCTCTAGAGAGCGCTCTGTCGGTA
          GCGACTGAGGATATGTCATCGAGGAATCAGTACTGTTTTCGTGTCTGCGCTGTTTGGGCG
          TAGGATGCTGGCGCCTTGATAAAAGACTCGGGTGAATCTCTTTTGGGTACTCTCTGATGA
          TGGATCGTCGGCATCTTTTCCAAGGACCTGAGTGGCCTTCTTTTGGATACTCCGCGAGGA
          CGAATCAATGAAATTCAATCTAAGCGCTTGGTAGGCTTCGATATAATCGCCTCATTGGAG
          CGGAGAGAACATGACCCGTCCACGGGGGCGATCTGGCATGTTGCGGGTGTCTTGTTAACG

          AAACCCTTGCTGATACGGAACTCAGTTCCTTACAAAGTGCTTCAACCGACTCACTTTGCG
          GCATGCCCTTAGACAACCTTCTGGGACCTCAATACGGCGTAACTGTCGCTTCATTAGGAG
          GAATTGTCCCGTAGTAGCACTCTACGAACAGGGTAAGCGAGACTCTAAACACACAACTGA
          TGGAAATTGCCAGTCATCGCTCTATATTCTCCGATGGTAGGTCAAGTACTGTCGTACCAA
          AGGCAAGCGAGGGCGGAAACCCCGGATCGCTAGCTAGTGCTATAGCGGTTGAGGTTCGGG
          AGGCGACTGAGGTCTGAAGTCTCGAATTGAGAGTCAATGAGGTGATGGCCGGGACTTTGC
          GGATGCTCATCGATATTAACACGACACGGTTTGTGTCCGTCACTTCACCCGCAGGAACGA
          GGATCCTCGCAGAAATTAATATCTACGGGGTAACATAATTATCGACCCTTGTAGCGAAGC

          TTCGTCTGGTGACGGCAATTGAGTGGGCGGTAGCGCCTAAAAAAGGTACAGCGATATACC
          CGTTTTGGACCCAGGGCTTTCAAAGCGAGACAATGCCCGGCAAAAATATCGTGCTGTTCA
          TGAAATGACCGATAGATGTGGCTTACCTAAAGAAGAGACTCCTATCACGAGTGGTTTAAT
          CGAGGTAGTCGTGGGACACAGGGAGAGCAATAGACGGATCTGTCGACCGTAACCATTTAC
          CACTACAGGCGGGGGACGCACCGGAAGCGGCGTGGACTCGTATCCCTTACACCGATATCG
          GGCCACGGGTGAGGGAAGTATCGGAAATGGCGTGCACCCTCACAGATGGTACGGTTATCG
          TGCACAGTGGACGGGCCAAAGCCGAACTACGGCGGAGTATTACATCAACTACGTCCGTAT
          GGTAGTGGGTGAGGGAGTCATTTAAACCGCAATGGAACCCTCGACCACCTGCACCCATTA

          CTGGCATGCAACGCTCGCGCTCCCGCCGGCTTAAGGATCTAGACTCTGAAGCGTTCATAT
          CCTATATACAGTAGGTTTCTGCACATCGGGGGGCGAACGAGGTCGCTAGTGCGTTTCAAT
          CGATCACCCGATACTCATCTACCTGCTCCGAGAGTTGAGCTGGGAAAAAGATGCCTGCAC
          TCGCTAAGTATTGCACGCCCAGATAACCGGAGAGGAACTGCTCAAGCAGTAGTTCCGCGA
          TTCTTACTGGCGGTTGATCTAATAGTGAGATCCGATAGGCAGTGACTACAGTCTATGTGT
          TCCTTAAACGCCGCTTGAGCTACCGTCCGGAGTAGTAAGCCGAAATTGAGGCCTTCGCGT
          TGGCCCCCTACAGCCCGACCCAAAATTGGGTGAGCATAGTTGCGACACAAGTCATCGTTC
          ACATCTTAGTTCGCTGGACTCAATGTTAGGGGCCAAATACTGCGATGGAGGCTCAGGTGT

          TTTCTAGCCAGCACGAGGGGGTTCCCGTGAGATCACCAGGTCGCTACTACACAAGCTAAC
          GCTATTATGGACCAGCAAGAACTTGTCTGGTTTGCTGCCATGACCACCCTGTCGGCTGTT
          TATATAATAAGGTCTTGGAAATCTGCTACGGTCCCATCGCTCCACTCAACGGTGGTAGAT
          AAACCTACTCAAAAGCGGGAGTCGGTGTTGCGCTTAAGAACAGCCTGCCAAACCTGCGAT
          CCATCGACAGGAAAACCCTAGTCTATTCCAACCATGGGGTATGCCCTAACAGTAGTTCTA
          TCCTCTATCAGACAACTGCACTCTGCCCTTGACTTGGAATACGCCCTTATGTAGATTTTA
          GCTCCCACCCGATTCCTGTGGTCCGTGACCGTTCTACTACTTACTTTTTCCATAATACCA
          CATCTATTCGGGCAATTAGAATTTGATCTCAATCCATAGTTGAATTCAAATATAGCTTAA

          GAATCCATCATGTGTAGTCACAGTCGCTTAATTTAAGGCTGCGAATACGCGAACGGACAG
          TCAATGGAATTCGAGAGACCGCTAGGAACTCTCTCGGCCCACGGCAAGAAAGGCGATCCA
          CGACCCAGCCTTAAGAGCTCGGGAGGCTGCTTCTTACATCCCGCCCGCGCGTTTAAATCC
          CAAGCTACTACCCGGGACCTGACAATTCTGGCATTCAATAACGACCTGATAAGTCTCCAG
          CAACAATGACTGTGGAGTCAGCCGACGTAACTGTATGACCTAGGCTTGGCCTTTTGCCTC
          CAACAATTGACGCGAAGTTTGTGGATGCCATCGTTTTACCTAGACCGGGTCCTAGGCATA
          CTACGCGCGTATTGAGGTCCGCCAGTCCCATCGGATAGTGACCACACCGTCAATCACATT
          CAATCAATGACGTGTGGCCGGCCGAGCTCGCCGAACCGTGACGCCCCTGCATCCGGCATT

          TCGCTCGGCTTGATCCACTCCATTTAGAAAGCGGATCCAGGTATCCAGAATGTTTATAAT
          CGGTGATCCTGGCCGTTCTTAGATTAATGAGCAAGACCCAAAGCCCAGGATGCCCTAGAT
          CGGTACCTTACACCGTCCACTGGCCTCGCCCTCTCGTTTTCAGTTCGCGAAGTCGGGAGT
          CGGCGGAGCCTCTTCCTTCTTACTTGGTATGTCCCATACTACGACGAGAATTCTGGAGAT
          TGCCCCTATCCGCACCTAGGCATCCAGTCGACGGCCCGTAAGTCTTCGAGCGCTAGAGGC
          AGCTTTCATCCGCCCCTAGGAACTTTACCGGCACCCCGGCAGTTTTCGACCGTTAATACC
          GGGACACGGAAGTATAGCTACGCTGTGTTGGAACCGATCTGGCTTTGGACTATCAGTAAT
          GGCGCCTAGAAGCGTGATCTTTTACAGGTCCCAGTGCCCACGTTCTGAACTGCAATCGAA

          GTTCTAAGTAGTATTGAGTGGTGCGATTCTTGCGAATTCTCAGGCCAAACCTGTTCATAA
          GTCTTCAATCGTCTTTGATGTTATCATTTCATTATCAACATGCGCCGGTTTCGACTGCAA
          CTAGGCGAACGTATCTGGCGGATTGGTTTCTCTGTTGGCGCGCCTCCTACTACTACTTGG
          CTCATTTCTCCTTCATAATGGCGGCCTACTTGCACCAACACATCCTGCCCTCCAGGATGA
          CGTAGGTATCATACATAAACACTCGGTCTTATGGATTGCGCGTAACTTAGTCCTTGGCCC
          GGTAGGTACCACACTTGGGGATACGTCCTTTAACTCCTCACGTAATACAGTCGTCGACCT
          GTTAAATTGGATCCCTAGGAACTCAAGTCTAGTTCTCGCATTAATTGCCACCACCCATTC
          GTCAACCTTGTCGCTTATGAGCCTGACTACACACTTGATGTTCGATAATGTACTGTAGGC

          TGCTCTGAAGTGGCTAAGGATAACAACACCACACTTATGTGGTTTCCCTCAACGAGGCCC
          CTAGCAGCGGAGTTCTAATGTATCTGTACGGCTGTATAGTGATGAATTATTGTAACACTG
          CACGATGGAATACACTACCACAGTAGGACGCGTCGAGCGTGCCTCGTCCGACGGGTGTCG
          TAAGCTGGGGTACCACGTTTCGAAAAACGGCAGGTATAATACTCCAGATATACCGCAACG
          AATAAGGTGACAGGGCCCTGCCCCCTGGTCCACGGTTGTCATTGACTTTATACCCTTCTG
          AATACAGTGCCAAATCCTTGCTCTAGGATTAGCATTTATTGTTATGTCTATCTCATTTTG
          AGTGCAACGTAGACGGCTCGCTGCCAGATATACGAACCAGGTAGCAATCATACCACGGCG
          CGTAATACCATGTTGAACAGTTAGGAGGCGCATGATTCAGTTACCGTATATTTTTCGGCA

          TGGTAAATAAAGCGCGAGCTCAGTTGACAACAATAGACCTAAGGTAGCTAGGCTTGCTGT
          TGGGCAACGAAATTCCCCTCTCGCCCACAACTCGGGGCCTATGTAGGCTTAGAGCACTGT
          TGGACACAGCGGTTAGTCTCCTGCTTGGCCCTTGATGCCTGAGTCCGCTTAGTGCTCTCT
          CTCAAAATATAGTTCTTCCTGGATTATGGGGGGGTGGTTTAAGTTTGTCGGGGCACATCG
          AGTGCAAGTAGGCCGTGCTTACAATTCAGATAAGGGGGCTGCACATATCAGAAGGCCTAA
          GGCTTAAACAGAATACGCCAATGTCTAAGGCGTACGGACTACGCACGCCTAAAGCTCTAT
          AGCTTGGGGAAGCGGTTTCGCACCCGTGCACGCCCGAGCTGAGGTCGCCATTCTTACTTT
          GGGTCAACCAGAAACTCTTTCCCCCCTGGCAACCCGAGTTACGCCCGGATTACAAGGTTA

          ACTATGAATCGCGTTCATAACCCGTCTACCGTCACACTAT
          TATGCGGGTAACGTTTTATGGCGGGAATTCACTGATGTAG
          CTGATAGTGCGCATGGTTAAGCTCAAGCGCTAAGTAGCGA
          CCTTCAAATTGCCCCAACAAGATACGGATGGGTGTACAGG
          CCGTCGAAGAAACCCTACGTGCCACAAGTATGTACCAAAG
          TCGCCGGAGAGCGTCTACACGTCTCATATACGCCATACCA
          ATAGCGACTGACGTGGAGAACCAGCAGACGGCTAGCCCTG
          ATACTGCGCGATGCCCCCAAGCCGCAAGTATTCGATATCG

