 8 1000
t1        TCTCTCGAAAAGGCGATTGGCTAAAATTATGTCTCATGACAACTTAGACGGCAGTGCCCC
t2        TTTTTAGAAACGGCGATCGGCAAGATTTTTGTGACATGATAATTTAGAAGAGAGAGCCCC
t3        ATGCTTCAAAGGGCGATTAGATATATGTTCGGTACACCACACTTCTGATAAGAATGCCTT
t4        TCTCAACGAAGGATTAATAGGTAGTTGTCCACTCCACGACACCTCTACTAGGAATGCATC
t5        CATGATTGATTCGGAGGCGAGATTAAAGGGAGGTCAGGTTAATCTGCCGATGATAGCTAT
t6        AGTGCCTAGGGACGGGTTGAGTTTCCGCACCAACCCGGTAATCCCGACGGTAACAGGCTC
t7        TCGCTAAGAGCTGAGCCTAGACATGCGCGAGGCTGAAGTGGGTCACATCGGGATGGAGGT
t8        TCTTCCAGAGCCGGGCCTACACACGCGCCAACCCTAAAGGAGACATAACCAGCTGAACGA

          CACACCCTCAGAGATTGCAACCCCGGAACTGTTGAAGGATCGTCTAGAACGGCTCTTACT
          CCTACCGTAGGCGATTTCAATACCAGACATGCTAAAAAACCGTACCAAGGGGATCCTATC
          CATATTACTAAGGTTTGCAATACCAGAAAAGATAAGGAGTCGGTGTAACAGAAACCAGTA
          CATATCACTAAGGATTGTGAAACCGATATCGTAGATGTGCCGGGTTAAAAGAAACAAATG
          CCCATGGCTGTCGACTGACATTGCGGTAACACGGCGGTTGAAGAATAGTTACTAGGCCGA
          GGAGTCATCCCTGCACACAACCCAGGCACTGTCATAGCGACTGCGTGGCTAAACCGTCGT
          TAGCTTGCTGATGATTGCTGCGGTGTCATAGAACAAGACATAACCCCGTGATCTGTCGGT
          TTGTTCAGCTCAGATTACAGCGAAATCGTTGCTCCAGAGATGACACAGTGCCCTGACAGT

          GCGTGAACGCTGCACCGAGCTGCATGAACAAAGCCAACTACTACGGTACACTCATACGGT
          GCGTGGACGTTGCCTCGAGCCGCGTCAAAAAAGCCAATTATTGCGTATCTTGCATACGGC
          GAGCTGGCCTCCTACCGTAACGCGCTCAATAGAACAATAATTACAGAATACTCTACCGCC
          AGGCTGACGTCCCGTAGGGGCGCCTTCATAGGGGCTATTATTAAGGGGCTCTCCGCTGAC
          GCCGCGACGCTTTTGTGTGTAGTGCCCACACCATCAGCGATCCGGTACTCACAGTTAGAG
          CGAGCGGACTTCATATGAAAAATGTCGTTACTAGTGAACTCTGGACACTAGTTGTGGGAG
          TGCGTGATCTACTTCTCGACGATGTGCACGAAAACTACCTTGGCGTCCCCCGTGAGATCC
          TTATCCAACTGCCTCCGAACATTGTTCGCAGAACATGTTCGGACATGTCCTCCCGGAGGG

          GCTCCAGGGGCCTAGGAGCATTCACCATCGATTAGTTGAGGGCTGCACTTTTGAGCTTTG
          GGTCTAGGGGCTTATGCGCACCGAATATACATTAGATGTGGCCCGTGCATCAGAACCCAG
          GGTTCATAAGCTTACCTGCACACCCTTAATATTAACCGTAGGATATACCTCTAGCCAATG
          ACATCGTGGGTTCAACGGCACCTCCTCCACAGCAACTGTGGGATTTATCCTTGGGTAACG
          TCTTCATAACTTTGGTATTGAGTTCCTAAAATTGCCCGCTGATCTCGACACTTGGCAATA
          AATTTCAAGGTTCCCTCCTTAGTTCGCAAAAAGCGTTTGTACTCGTACTTCTTAGCCGAC
          AGTTCCAGGGCCCATCTCACGTCACTTGCAAATTGTGGTGAGATCAGGGTCCAGATATCA
          AACTCCAGAGCTTATCACCCGTTACACGTCAATTACTTCGAAAACGCCATCTTCAACTAG

          AAGAAGGGTGACCGACGACCAAGCCCTACGACTACCGGGAGGAGAACTAGAGCCAACCTA
          AAGGGGGGTGATTGACGATCGAACTCTACGACAATCGGGAGAACAATCAGAATCAACATA
          AAGTAGGTAGGATGTTAATTGTGTGCGGAATCAATGGCTTAAGTGAGTAAAGCACATATA
          AATTCGGCTGAACATTCATGCTATTCAGAATTAGTGGGCTAATCGAAAGGAGTGTAGGTA
          GAGCAGAGCGCCCGTTCCCAGACTCTGATGTCGCTGATCAACCTAGATAACTGTTAGTAG
          GGACTTGGCTACTGTGGGCGGATTATGCTGAACCTCAAACGATAACTTAAATTTTGCATC
          AAATTAACTGGTTGTGAGACGACTCTTACGGCAACTGGATAGTACTCAAGTATGGATTTT
          ATATATACCGGTTGTCACGCGACGCTCGCGCCACATGGTAAGCATTTAGGAATTCGTGTC

          GCGGATGCTGATCAGGAGGCACACCACGTTGAACTTGCCCCGTCGTTAGTGTCACGACAT
          TCGGACGTTGTTTGAGAGACCTACAACGTCCTTTTAGCCACGTAGCATGCGTCACCACAT
          TTGGATTATAAGTCACAAGATCACGACGTCCAATGAGTACTTGCGTTGGTGTAATTGAGT
          TCGGATCGTCAGCTACAAGCGCATGACATGCAATGAGCCATTGAGTGGGCGTCATTGTGT
          TCCTACAATAGACCTTCGAGAGTTAATCATCCGAGATAAAACCCGATGTAGGAGCGAGGC
          ATCTCTGGCGGGCCTCCCAAAGTTGGAATACTAACCTAGTGGAGCCGATAGACGCAAGTG
          AATAATGGCGAGTTATTGCTCAAACCCCACGTCTTCCTTACGAGACAACAATAGCTATCG
          ATTGGAGGCGGACTGTTGCCTAATCATCTAGAGGTCCAGATGTACCGCTGGTCACTCGTA

          GCCAAGAAGTCCTAAAAATATCTTGATATAGTCCGACGGTGACCTTGTGTCATGATGGGT
          CTAGCGAAGCCTACCGAATAACCTGTTATAGTCGAGCGGCGAACTTCTGTCATGAGTTGT
          CCAGTGATCCAGAGAAAGCAATTTGATGTCGCCTGGCCACAACGCTGTTCCAGGAGTCGT
          CCAGTGGACCAGCCAACGCGATTTCACGTCGCCTGGTGGTAACGCCTATTCCGGAGTCGT
          AATTGAGGCACTCAAAGTGTTCCAATTTTTCCCAGGGAATGTACGGAAGTCGAGCTTGTA
          TCACTGCGCAAGCTGAGTCACCACCCGGCTAGCTAGGTGGGCACTGCTGCTGAGAGTTCA
          CCTACCAGCCAGTCAATTTACCAGGTCAGAATACAGTCGTGAACAATACTTCGAATTCTC
          CCCTAATGACGGCAAATCCAACCGGCTTTGATAGCATCGCGAACGCCCAATGGGATCCTT

          GCCTCGTACCTCAAGCCTACCTACGACCGCAAGTGAATAGCCCACAGAGAGGGCTGCTCT
          ACCTCGCATCTCAAATTTACGTATTACCGTGAAAGAATAGCCCGTTGGGAGGGCTGCTTT
          GCACCGGAGGTGGTGTCCCCCGAAGGCACCATAAAACAGACCCATCGAAATCGTCACAGC
          GCGTTAGAGCTGGTGCCCTACCATGCCCTTTCGGCACGGACCCACTGCGATCGCCAACGC
          ACCTCTTAGATGCGGCGACACCTCGCAATCAGCGGAATGACGTGACGAAGTGATGTACTC
          AATGTGCACACGCTATCGCACTCTGACCTTGGTGTCACGATGTGCCGGAAGAACAACGTC
          GCAGGTTATGAGGTGTCCTACAGCGGACATATCCCAGCTATATACTGAGGGAAATGTCTA
          GCGATTTAGGAGGCGTTCCACCCTACCTATGGCGCTGCGTCATACTATAGGAACTGTGTC

          CGCGACATCTTTTATGATAGAGAGTCTTTAAAAAGACGGTTTAGTTTTAGTTCTCATTTA
          TGAGGCAGCTCCTATGATAGCGAGTCTTTAGGAAGTCGGCTTGGTTCTAGTACTCACGCA
          TAAGAAGAATTATATATTATAGCGTACTCCTACTGTCGGACTTGTTCCTCAGACCCCATC
          TAAGAGGTATTTCACGATATAAAATCCTAGTGATGGTGGATCTGCCCTTGCACCCACACC
          TCGGTTGCACTCCGACTAATAGTCGTGCTAATGAGTAGGATTATCAAGTGTATTTGTCTT
          CCTGTGGGTTCCGGACGGATGAAAACCCTGCAATGCCAGTTTGTTGCTATCGCCTGCCTT
          CACACGGTGCGTTCGAAGTTGTAACCTTGAAAGTGGAGGATTATAGCATAGGGTTTCCAT
          CATGTGGTGCCTCCCAATCCATAGTGCCGAAAACAACCGATCAATGTCTCAGTCTACCGC

          GTGTTAAAGTTGGATCATTAAAAATTAAAGGATATGATACACTCGCAGCGAATGTCACCA
          GCCACGACGGTGGATCATATAAAAATAGAGGCCATGTTGCACTCGCAACAAATGTCATTA
          GTATTTGGACTGAACTGATGATCATTCGAGGATGTGATCCACCAACAATGGACTTAGCGA
          GCTTTCGAAGTAAACCGTTAATTATTTGAGGATATGCCCCGCTAAGCATGAACGTAGCGA
          CCGTATCTAATGTTCCGAATGATAAGGTGAGCTAGAGTCTTTAGATTGTGGGAAGTCCGG
          GAGTTCCCAGCGAGCTGGCTAATATGGCAAGCTACCGTCTACATCGGGTGAACAACGTCA
          GGAACCGTGAAATGCGTCGCGGCGTGCTTGACCACGGCCCAACATGCACGGCGGACCCTG
          TGATAATAGAACCGCTTTGCTACGTACCAGATCACTACCCTCCATGAGCGCAGGCCCTCG

          CAAGAAAACAGCTCCGGGAGCCCCGAGAAAGGTGGTCAGGGACGCGTTTAATGATCATCG
          CAAGCTAACCGCTCCAGGCGATTCGAGGAAGGCGGACAGAGACGCGTCTACTGACATTCT
          CAGGACAGGACGTTCGGGATACCCGACAAGGCTGTTCAATGGTGGTCTCATTGTTTCCGT
          CCGAAACACACATTATAGAAAACCGTTAAGGCTGATCAAAGATGGTTTTATCATCTCCGC
          CGATTACACTGCCTCACTTGATTGGGGAACGCGGATAACAGATGAGGGCCCTTTCATAGG
          TGTGAGCATTTTATTGCAACCTCGACACTTATACACAGCAGATGGGACACCTATGTTCGG
          CTTGATAGGACTCGTCGGTACGTTGGCGCAGCTGATCGGGTCTATTTTTGCAGCTAACGC
          TGTGTAGAAATACTACGATACATTGGAACTATCGTGACTGGGCATTTTTGCTGCATGTCC

          ATACCCAATGTTTTTGAATAATCAGGGCTTAATCTCCCGTTTCATGAAGACGCTGAGTGA
          GTATACCATGTTTATGAATGATCAAGTTATACCCTCTGGTCCCCTGGAGATGCTGAGCTG
          ATAAACGGGAATTTTGCGCCTGTGTCGGCTACCCCTATGGTCGCTACACGCATCGCGTGG
          AAAAGTGACAATTTCGGGCCCGTAACGGCTACCCCCACGGTCACTATGTGTTTCGTGTGG
          GGTCTGGGCAGGACCCGACATTCATCTCCATCTATCTCTATGGCCGAATTTGCGATATCC
          TGAGCCACCGGGTTCTGCTATCCACCTTTCGCCGCCGCATCACTCAGCGATACAATGAAC
          ACATGCGACTTTTTAAAGCACATGGTGCCCAGCTCGTTAATGATGTTAACTTCCGGCTGC
          TTAAGCAATCACATAAACAGGATAACCACTAGAATTGAAAAGGTTCGAAATTACAGGCAG

          ACGTTATTAGTATGAATATACACTATCCACTCGAAGGCTACAAAGCGAACCCCCGTATGG
          GCACTATTCTCATGAATGTAGACTATCCATCAGACAGCTGTAAAGCGAACTTAGGTTTGG
          TTATAGTTGTCGGGTGCTGAGGTCGTTTATTGGGGAGCCCTAGAGCAGGTCTACACGTAG
          CCGTACCGATCGGAAGCCGAGACAGTTTAATGAAGAGCCATAGAGTAGGACTAGACATGG
          CGAAAACACGCGCATACGGCGCATGTCTGACCCGATGATCCAAAATGATCTCTGACGTCT
          AGCAATGTACCGCCGGCAGAAAACATCTGTCTGTACGCGTTAGGTTATTCCTTGGCATTG
          AAGCGGACTTCATGCCATTGGGCCCCGTAACCATAGGTGTGCAACTCCACAACGCTGCGG
          GAACGGGTAACGTATATGACGGATTTGTTGTCGTAGGTGTACAGACCCACATTGACGCGT

          ATCAACACACTGAACGTCCTCGGAAGGCAAATCCTGACTTAGCAAACGTGAGAGCAACAT
          CTCAGTATATAGGATGTTTGCGGAATGCAAACCTGGACTTAGCAAACATGCGGGCAATAT
          CTAAGTACATGTGCCATCCATTGAATGTGTACATTAAGCATCTGCGGCTGATTCTATGGT
          TTACACACACGCATTGTTACTCGAAAGTGCACCTCGAGAACGTGAGGTTGATTCTATCGT
          AAGCAACTCTGTAGCACACAGGGAGGCGCTTCCAGCGTGATACCACGCGTCGCCATCGGC
          TAGCATCTAACCCGTACTTTTACTCCAATTCCACCAAAAGAAACGACCCCCTATGTACGT
          CGACGAATTGCGCGCTTCTCCAATCGTCCACTTGAGAAACGGCCGTTTATCACCCCCTGA
          TGATGCATACAAGTTCCTTTTGTTAGACCTTTCTGGTGATAGGTGACCACCCCTCCCGGA

          CTCGGTTTTCTAAGAAATGAAGTCAATGTAAATGCACTGGTCTGCGGAAGCTACAAAGCA
          CTCGGTCTTCCACGAAGTGGTGTAAGTGCATATGCACGGGCCCACAGAAGTTATCGAGCC
          CTCGGTTGCTTAGGGAATGATATCAACGTTCTAGCATACATTTTCGGGGTCGAGCAAACA
          CCTGGTCTACCAGGGAGCCATATTAACGTTCAAGGGTTTATCCTCGAAAGCCAACGACCC
          CGAAGTAAGCTAGGGGTCGGGGGGAGATTCACAGCAACGTACTCTTAAGACCAAGGTCCT
          TGATGTAGCTTCGCGGCCTGAGTCAGGTTCGGCTCGTTAAATTTAGCTAGCCGGGGACAG
          CTTCGTACGCTACGCACTGAGTTCTACGCTAGTGCCTTGAGTTACGGAGTTAGTAATCAA
          TTCCGTCACTTTAACAATTTGTTCCCCGCCGTAGACTCAAGTAGTGGATATCGACAGTGC

          CTGAGCGACAAGCCCAGGTAAAAGAGCTGTGTCATGACGCCAATGTACTTCCCATCCGGA
          CTAAATCTCAGGCCGAGGTAAATGAGCTGAGTATTGGTGCGTTTGCACCTCTCATCCCAA
          TATTTTTGTATATAGGGGATAACAGGCTGAGCTCTGGAGCAGCTTAGTCCTCGCTTTCGC
          CACATATGTATAGAGAGATTAACAGGCAGTGCATCGGTGTACCTTGGTTCCTGCTTTCAT
          CCCGAGAGCTTGTAAAGGATGTTGCCGTGAGCAAAAGGACTCGGTTATCTCGGCATTTCC
          TTAAGTTGTTAGTATCGACCATTACCATGAAACCATGTGCCAGGTTGAATCGATATGTAT
          CGCAGCCATCAGTGACGATAAGTGCGCGGTTCCAAAACGTTTCGCTGTTCCCGCTTGCAG
          CATAGACCCATGTAACTTTATGCAGGCAACCCCAGAACACTCGGCCATTGCGGCTGGTAG

          ATACACGATTCAAACCTAGCCTTAGTTCTAAGACCGCGTA
          CTATACGACGGACACCTAGCTTCAGCATTACGCTTGCGCC
          CTGCCTTATTATGATAAAGTCCTCATTTTAAAAGAGGATA
          CTGGCTTGTTATGATACAACCTTTGTCCGCGACATGGACA
          AAGCCAGGCCATCTTCCGAACCCTAACATCTGCACATATG
          GTCTACGCATCTTCTTTCTATTGTATCCGCGGCGTATCTG
          AGGTATGATTCTGTCCGGGCTTCCAACCCGTTCCTATACC
          AAATAAGCCCTTATTTCGCATTAGTACCTGACCTTGAGTC

