 8 1000
t1        GATGGCTTTTAAACGAAACTAATGAGGCATAAGTATTAGCTATTGGTCACACTGACGCAC
t2        GATGGCTTATTCATATAATAATTGAGGCCTTGGAGTCTATCGTTGCACTTGCCGTCGGAG
t3        AGCCGCCCCCTGATGTAACAAACGGGTTATCGGAACCCCTTGTTGGGCGTGCTGGGGTAT
t4        CATGGCTAAACAACGTAATAGGTAGGGTACAAGGTCTAGTAAATGGGCATGCTAGTGCAT
t5        AGCGTCTATTGACCCCTACTGACGCGGTGTAAACGTCGGTCATCGTGTTTCTTTACGTGG
t6        AGCGTCCATTGACTCTTATTGACGTGGAGTAAATGTCGGTCATTGCATCTCATTCCGTGG
t7        CGCGTTAAACTACTTTTTTAGTAGAAGAATAAGCAGTCGTCAATGTTATTTTGGCCGGAA
t8        CACGTCACGATAAATCGAAAGTTGGACTGCTGGTACGGGTCGTCGCGTGTTCTTCCCGAG

          TTCCCTGCAAGAGAAGTTGTCGGCAACCTAAGAGCAGATTAAGTACCTGATGCGATTATG
          CTCCGAGCAGGACGTAACCACCGCAGTCCCAGGGCAGATCCGAGAGCGACTGTGCCGATG
          CGTATAGTGGAACATGAGCTCTATGGAATTGTGCGCAGCGTGACATGCGAGGCTCAATTC
          TACCCTATGAAACATGATCCCTGGAGGCTCGTAGGCGAGAATGCACACGCGGCGCCGGAT
          TAACTCGTAGGGGAACGCACCTGCGACTTACTTAGGGGCGAGCCACCCGAGGTCATAGAC
          TAATTCGTATGGAGCCGCTCCCGCGACTTACTTGAAAGCGAGCCATACGGGGTACCAGAC
          CACTCGGCAGCGACCAGTGCTTATAGGTCTAGAGTCGGCCACGCACCCAGGATCGAGGAC
          TAAATAGTCACGTACGCCTCATGCAGCCGCGTGGAGGATAAATTACTCAATCTGCTGGAT

          TTAATTCTCATGGGTTAGCGCCCGAGTGCGCTCTGAAAGCTGCGTTCGTATCCTCCGCAC
          TTGATATGTACGCGTAGCCGTAAAAGACCGCTGTGACAGACAAACGCGTGGCCCCCATCA
          CTGATATGTTTGCATTACCGTAAACGACCATTGGCAGCATTGGTTTTGTTTATTTTTCTA
          CTGAAATACGTCTTTTGCCGTGCTAAATTCTCACGAGCGTTCAGTCTGTATCCTTCATCC
          TTCTCCCTTATCGCTCGCTATACAACACATCTAGGGCTATCCTGACCGTATGCTGCACTG
          CTACCGCTTACCGCAGGCGACACAACTTATCTAGGGCTATCCTGCCCGAGTGTTGCACTG
          CAGCCGCGCTCATACTGGAATAAAGAGTCGCTCCGGCTAATGCATAAGGGGGCCGCAAGG
          ATGCCGGTTGCTCGCTTCGTCAGACTGACTCATCGCGCTTTTTGAGAGCGGCGCGCCGAG

          CCTTTCCAAGATGGCTCCCCACTAGGTCTACGTAGACATATTTTAGCATACTAAGGATCC
          CCTCACCACGGAGAGATCACACTCCATCTGTGTCGATGTACCCCGACGTACCGAAGATTT
          CTTCTCCATCAACAGTCCGTGATCCCGATATGTAGACATACCACGGCACGCTGTGCGTGC
          CTCTTTTATTACGGACATGTTGGTCCCGTGCGTGGATATACCATAGCATTACGAGGTTGG
          TTTTTTCGTGCCCCTTTCTTATGAACCCTCTCCACATTGCGGCCGGAACATGGCGAACCC
          TCTTTCCGTGCCCCATTTTCATAACCTTTCTCCAGATTGCGGCCGGAACTTGGCGTACCC
          CTCGGTCACGAGAACCATCTCTCTTCTCCCGATAGGTGTGTAGTGACGCAATGATGAAAC
          GATCGGCAGGTAAGTTCCCTACCCACCCAGAGTAGATAGATAGCGTTTCAGGTAGGACTC

          TGTGACTGTCTGTTTGGAGCCCAACAGGTTAGGATAACTACTTCGCCTTCTTACGATTCT
          GGCTTACGCCTGTCGCAAGATCGGTGGCATGGTGCGCTCACATGGCCCTGTCGCGGTGCC
          CCCTTCAAAGCGTCTCATGGAGAGTTGTACAGGACAGCATCTTCACACCTCGACTATGTC
          CCAGTGCCGTTGTCGGAGGACTACCACACAAGATGCACCCTATCGCTTCTTAGTTATGTT
          TACTGTAACACACAGTGAATCCCGCGGCTGGCCCCTATATACGTAGACTCGAACTGTACC
          TACTGCAACAAATATATAACCCTCTGGTTGGTCCCTATCTCCGGAGATTCGAATTATACC
          GTCCTATCGAGCTGGGACTGTCAGAGCCTAGGAGTAGATTCCTTGACGCTTGGGTATCCA
          GTTCCTCCGGAATAAGAATCCCGGAAGTCTGAGTAGACTACCTGAAAACCCGAGCACATT

          CCTGTAAACAAAGCCTCCTTCCGGTTGGTCAACCGTTGTACTACGATGTGGCCGCCGGAG
          ACTAAAAATGGGGCTGGCCCAAGTGATGTTCAACGACATTTTGTGATATAAGTGTCGACG
          GTAAAAATTTTAGTCGGGTCACAGTTAGATAGCCTGTAAGTCATGAGGCAACTGTTGGCG
          GCAAAAAACATACTCACTCTACGGTCAGACGGGCAGTACATCTAACCGCGCATGCAAGTG
          CCTGGATCCAGCGCTGACCAGGTGCCATGCGAACGGACTTTGTTATTACGCGCCCAAGTG
          CCTTAATTTAGCGCTAGCTCAGTGTCATGCGAGCGAACTTCATTGTTGTGTGCCCAAACG
          ACGCTGTCCACAAGTGCCACGACCCTAAAGGTATGGCCAAAGCCTTCCCGTTACAGAATT
          GCGGAGATCGTAACCACTCCCTAGTCACAGAGTTGTCATAGTCTATACTTTGGCCAGGCG

          ATCTAATAGACTACTAGTCTTAGTAGACGGCTCCTCTCAAACATCATATGGACAGTCGCT
          GCCTTGCCACCAAACCGGCCGAGGACGAGATTTCCTTTACACATCGTGCGGACTCTTAGC
          ACTTTGCGGTCAACTAAGTTAAGGAGATTCCTCGGTCTCAGAACTACCTAGGAACACTAG
          GCCTCGAAATTTTGAAATCTTTAGAGACGATCTCTTTCACATATCCCCTGGCATGCCGAT
          CCGTGTCTAACGACCGCAACTATCGAATGTTACATCGTGTATGCCGCGCGGGGTGCGACC
          CCGTGTATGAGGAACGCAACCATCGAATAATCCAGTATGTATGCCGTGCGAAGTACGATC
          CTGCGATCTCAATGGGGGCGCAGAGGTATTCTATGTATAGGTGGTAATGTGTATTCCTTC
          GCACATCCGCTAAGTAGACGTTGAGCTTGTTGCACAATCGGAGCCACCCAAATCCGACTG

          ACCATGTCGTTTTTTCAGGAGGACCGTCATGTCTCAGCAGGAATCCTTCCAAGGCTGACG
          TCTATGACACCCATCCGGGCGTATTGTTGTGACCTTATGGGACTTCCTATAATACCGGTG
          TGCACTTTACCTCCTTGCGAGTACTACTAAGTTCCCGTCGCACTCTTCCCGACTCTGACC
          TCATGACCAACTCACTGAAAGAGGTGTTCTGGTCTTGGAAAACCCTATCAAAGGCCTGTG
          TTATCGCTTCCCGTCAGGCTGTATTTAATCACTTCAGCGAAGGCTTCTTCGGGACCCGTT
          TTATCGTTTCCCTCTAGGCTGTATCTAGTCATTTTAGAGAAGGCCTCTTCTGGATCCGTT
          ACTTGCTCAATTTCGCGGAGCGATTGACACCCTCGGGTGAGAGCCGAACTAACATGGAAT
          TTAACACGCGTCTTCCGCATAGATAAAAATGCAAAAACGACGCTGCTCTCCAACCTGATT

          CAAAGCCCCTGCCGCACAGCCGGCTCGAGCCTAGTTGAATGGACTTTCTATATGCGCCAT
          CACGACTAATGCCGCATAGCTAGATCACGTCCTCTTGAGTGTACTCGTAATACGCGACGC
          CCAGACTCGCGGCGCACGGAAGGATTCAGATTTATGCGATTGGTCCGTTGTCACGGAAGC
          CCACAGTCTTGGAGTACAGTTGGCACGTGCCCTAGATGTCGCAGTAATCAAAGACTATGT
          CCCGAAATGTCGAGTACATACAATGCATACCCCGTTGCGAGCGCACGCAGCAGGGGTTGT
          CCTAAAATGTCGAGTCAATACAGTGCGTACTCGGTTGTGAACACAGGCAGCAGGGGTTGT
          TAGGTTGTGCCCCGAAGACTGGCACCAAGCTCACCAGACCGTGCGCAATATGGGTGCAGC
          GCAGTCCATTCACGCGTCTACGTTCCAAGCAATATAGCGTCCGCGTGCTAATAATGGGCG

          TCCAGTTCATAGTGTACCTTCCAGTATGTCACGTGAATCAACTGCCGAGCACGCATCTAC
          TTCCTCACACATGCTACTCTTCAACACTCGTGGTCCGTAAGAGTCCGAGGGCGCCTTCCC
          TTCATTCCGCAAATTGTTTTCTAAAACACGACGTTCATAAACCCTTGAGCGCCCAGCCAT
          ACGATTCTGTCGAACACTTTCTGGTGCGTGTCAAGAATAGACCTGCAAATGTCCATTCGT
          CATTCTACGGGCGTCGGTCGTCTGAGTGATATGACAATAGGTTCATAGTTGGAAGATGAG
          CATTCTACGTGGGGCGGCCGTTTGAGTGACATGACAATAGTTCCACAATTAGGTAATGAG
          TCTTCTTCGGCGGGTGCCTCACTATGCACTATGAAGAGCGCTCTCTACGCTTGTGCAAGT
          TTATTCTGGTTAGACGGCGAATCACCTTTGACGGACATTGGCAGCAAAATTAGTGTCCAT

          GTTCCAACCGATTCAGGTCCGAATGTACGGCTCTGCCCTTAAGAACGGTGGCGCTTAAAA
          TACTTTATCGTCAAAGGCCTAGAGATGGGGCTCTGCACTCAGGAAAGGCTTTTCACTCAT
          TTTGCTGTTCTTTTAAGCCAGAATAGAAAACTACCTGCTCAAAAGAGGCAAACTCTAGCT
          GAGTCCTTTGATTAGGATCCATACGTTCAGTCACCCCTACAGTCGAGGTGACACCTCGCT
          AGGGAATTATAATAAGGTCTAGACATTGAGTTGCTGGAGTGAAAGAGCCTTTACTAGAGT
          GATGGCTTTCAGTAAGGTTTAGATATTGAGTTGCCGGATTGCAAGAGTTTTTACCAGAAC
          GACCGCCCTTGTTGGGCTTTAGCTAGCCTCTCCGACCTGGACAATATTCACGGCGTGGGC
          AGCTGTCTTTGTTGCGGCTTGGTAGACTTGCGACGTGGGCGGGAGATATTCTGTACCGAC

          GCCACGGTACTGACTCACATCATGCTCTCAGCTCGTTCGAGACATTAGTCCAAAAAAAGG
          GTCTCTGTGCCGATCTACACCACCCCTTTGGTTCGTTCGAGAGACCTGTCTACGAAGGGG
          ATACTCGAACCGACCTCAGGCACGTTCCCAACCTGTGTAAGTAGCACGCTCAAAACAGGG
          TAAACCGCACCAACCTATACTTCGCCGTTAGCTTGTGTTGATATTATAGACAACCTGGGG
          TAGCTCGAAAAACCCTATGTTTTGTCGTTAGGCTTGACTGGAAACACGCTTTACCTATAG
          TCGCTCGAAATACCCTATGTTTCTCTGCTAGGCTTGACCGGTAGCACGTTTCATCTATAG
          CTGGGAAAGAGCGACTGAGCTTTATCTGCGTTCTCGGGAGGAATCCCCGTCAGCTGTTAT
          GACTGAGGGATTGAGAATCTTATCTCCGCGTATGGGATAAGTGAGTCGACCAAGCAACCC

          AGAAACGACAGTCAGACTTCACCACTGACATAGTGTAGCCTTATACTGTGTGGCTTTCAT
          TAAGCCAACAGTGTCGTATTATTTCCGAACAATGGTTGTTTTAGAGCGTGTGGGTACCCC
          ATTCTCCAAAGTGACACCTCATCAAGAATGGACGATGGTACTACTCAGCGTAGTTCTCCT
          CCATTCGGTAGTGAAGTATGGCACCCAACACAGAGCGGCTCTTCTGGGTGTGGGTATTCT
          TCTCACACTACCGACTGCTCAGACTCAGAATGCGGGACCTACGTCCAGTACTGCTGCGTT
          CCTTACACTACCGACAGCCTATACTCAGGATGTGAATTTTGTGTACTGTACTGCTGCGCC
          CGGGTTGATGGAAGCGACCAAACCCATAATTTTGGCAATATGGTTTGCTTCAGCGATGAG
          AGCATTGTCGTACTTATCCTAGAGTCAATCTGCGACATTTTTGCCCACCCCGAAGACCCA

          AAAGTCAGCCCTTGCCTCTGATCATAGGCCACATTCCGGCGATGTGTCTTAGTTGCTACG
          GAGGTCGGAACTTACCTATGCTCGTAGATCGCGCTCCCGCGATATGTCTCAACATTTACC
          CAAAGCTTAACTCGGCTCAAATCGTCGTCTGAATTTTTGAGCCGTTCCAAAAAATCCATC
          CTGGCGAAGACAGAACTTCCACTGTTAGTCAATCCCTAGAGACGTTTCAAATGAATGGCG
          GGGAAGAATGAACCATTTAGGACAACACTAATGACCCCGAGATATACGAAATTTACACGC
          GGGAAGAATGAACCATCTCGGACGACACTAATGGACCGGAGATATATGAAACTTATACAC
          CAGGTGAACGTCACCCCTAAGTTTTGGATCCTATAATAGGAAGTGTGCCTGAACGTACTT
          TCTCTGACGTTTTCAATAAAATTGTAAGTCACGCTAATCTCCTTCTGTGGAAACTCACCT

          AATGTAACACTTCCCCGGTATGGATGAGTCGTCCAGTTAGGGTCCCAAGGCAGAATATGA
          GATGTAACTCTCCCCAAGAATGAGCGCGCAAACAAGTAAGTCGCCCAAGCTAAATTACGA
          GTCGTAACGCTATCCAAGGCGGAACGCGCAACTTGGCTAGATGCTTAGTCCGCATTATCG
          GGTCATGCCCCACCAACACTTGCTCGCAAGATGTAGTTAGGCGCGCGAGACAAATTGCGC
          GGCCCACCATTTGACTGCCTTGAGGGGGCCACACAGATGGAGGTGCAAGCAATCTGGTAC
          GGCTCACTACTTCACCGTCTCGAGGGGCCCACACAGCTGGAGGCGCAAGCACACCCGTAT
          TGCCCCCGGCGGAAACGATATGAAGGTAGTACCACGTGAATCGCAAAGACGAGTCCAAGT
          CATTCCATGTGGGCCACTACTTCTCACGGTATGCCATTGGATACCTTCCCAAGTCACTTG

          GAGTGTTGCCAGTTCAAGAACGGCAGTAATGAGTGCGCCAGCTAGTTTGTGCTAATGCAC
          GTCCGCCGACCGATCAAGAATAGGGATTATGTAAGGCTCGGTATGGTTACGCTAATGCAC
          GAGTCTCGGCAGGCACCGTATGGGGGAAGAGGGAAGGTTGGTAAGTTCACATTCCCATCA
          GCACACCAACTGATTGTGCGTCGAAATTGCGGGGAGAAAGCCGCGTTCTTATATACATCA
          GCGCATTCCCTGACGTGATGTTACCGTGATATGCCAGCAGCGATATTTACATCCCTCAAA
          GTGTGCCTTCTGATGAGATGTTACCATGACATGCCAGTAACGAAATCAACATCTTCTAGG
          AAATCTTCCAAAAATGGAAGACTGTACAGACAGAGTCCGCAAAACGTAGAGCCTACTTGA
          CAGTTTCGGTTAATGGAACGGTAACGTGGGAAGTAGACCTGGAAATATTCACCTATTGAA

          CCATGTGGATCTAACTCCCTAACGGCCACCTTGTTGGGGC
          GGTCGTAAATCTAATTTTCCGGTGTCCACGCTGCCGGAGT
          CGACATAGGACCAGTCTAACAGTACTTATTTAACCGAGGC
          ACCGATGGGGCCCATTTTCTGGCAGCTGTTTTGATGAGAT
          CCCCGTAGTGCAAACCCATTTCTACGAACATGGCTAGAGA
          CCCCGTAGTGCATAACCATCTCCATATACACGGCTAGTGA
          CAACGCTGGGTATGGCGATGGGTATACTTTCAAATGAGAA
          GGAAACGGCTTAGTTCCAAAAGCGCCTTTCAAGTCTAGAA

