 8 1000
t1        GAGAAATCATTATTAGAGAACCGTGCGAGGTGCACTGCGCGTGTGTTTTATGCCAGGAGC
t2        GAGAAACCATTATTAGAGTCCCGTGCGACGTGTATTGCGCCTGTGTTCTACGCGAGGAGC
t3        GAGAAACAATCAATAGACTACCGCGTGAGGTGTACTGCGCGCGTGTTCTGCGGGAGGAGC
t4        AAGAGATAATTTCTGGAAAACCACGTGAATTGTACTATGGGCGTCTCCATCGCATGAAGT
t5        AGGTAATTATTATGAGATTGTAGCATGTAAGACGCTGTACACCCTATCATTGATCGGGGC
t6        GCATAGATTCGTTCAAACAGTGGTATATGAGCTGGTGTGTATTCCCTCCTCGAATGCAGC
t7        GGCCAATTACTATCATGTTGAAACACGCTCTGGACGTCCAAAACCTGTTTAATTACAACC
t8        GGACATACACCCTTGACCTGTAACGGGTGAGCTTCAGGGCGGTAATATACAAACACGTGT

          GAAATTGCCCGCTATAGTTCTCTGGGTCAAGTTTAGACAATTTGTCGAACGTCCGCTTAC
          AAACTTGCCTGCTATAGTTTTCTTGGTCAATTATACACACTCTGTCGAACGTCTACTTGT
          TATCCTGCCCGCTGTAGCGTTCTTGGCCGATGTTAGACAATCCGTTGGCCACCTACTCAC
          GGATTTGCTCATTATAATTATATGACCGTATGTTAAGTGCTGTTTCAAACGTTTACTTAC
          TCTACTGCGTGGTGTCACTGACGTAATAAATACTGGATGATTTAGAGAGCCCTAGCATTG
          GGTTCTGTCGGGAGTAGCATTCTTAGCCACTATTGGGTTTCCCAAATCACCAGCAACAGG
          GTATCCCCGGGATTCGTCGAAGCAACGTAGGTTTGAACTGACAGGAGTCCCTTCTTGGAC
          AAACGAGCCTGCCAGTGCCTTTTGGAAAAAATCCGGTCGACCAAACTCGAGAATAAGAAA

          GGGGGTTCTGCTCGCCGGTACCTCTCTGTTACCCATGTTTAGTGTCCTGAGTAATCTTTG
          GGGGGGTCAACTCGCTGGTACTACTCAGTCACCCGTGACCAGAGCTCTGAGTATTTTTTG
          GGGGGACAAACTCTACCGTACTACTCAGGCACCTCTCTTTAGTGCCATGAGTAAACTTCG
          AGGGGTTAAACCCTCCGGTGCTACTCAGCCACCCATGTTTAGATTCCAGAGTACTCTTCC
          TGGGCTCAAGTGGATCGCAACAACTCACCTGCCGTTGCCGCGGGCCCCGACCCAGGCATC
          AGGGGAGTAGCTACTTTGCCACTCTTGACCGACCCTTTTGCGGGGGCTGATTAATTTAGT
          GGTATCGGGTCCCTCGCCTTCCTCGGTCAGTTGCTTAACGCAAACCCCGGCAGAACATTC
          ACACCTGGTATACTCCGGCACTATTCACGAGCAGCTCATGGAATGAGCGTTTGTTTATGC

          AGGGAGGTAGCATCCGACGCCCGCTTCCCCAAACCCATATTGTGATATAATCATTTCGGG
          CGTAAGGTGGCATTCCACGCCCGCTTTCCCGGATTCTTATTGCGATATAACCATATCAGG
          AGGGAGGTTGCATTCTACGCCCACTTACCCGGATTCTTATTGCAATATAACCGTCTCAGG
          AGTGCGGTTATGCTTTACGCTCACTTTTCTGGGCTCCTACTGTAATACAGCTATATCAGT
          AGAGAGAGTACAATTCATGATCGACACTCCAATAAGTTACAACCATGAAATAATTCCAGA
          GTTTTGACTATAATCCGCGGCAGGCTTGCCGAGTAATTGCAACCGTAGTATAATCGGCGG
          CATCAAGACATACTTACTATTCGTCGTAATACGCTCACGACGTAAGGGAAAACGGACCGT
          TGTGAACTCTTGATCGGTTTTTGTCGCAGTACCGCATTGTAGGAGCAAAATGCATCCTTC

          CTTCGGTGCCACGACCCTGGGCGTGGAAACTGCTTGGCCTAATTTCTTTCGCCTGATTAA
          CTTCGGCGCTACGACGCTTGGCGTGGATGCTGCTCGGCCTAATTTTTTTCGCTTGACTAA
          TTTCGGTGCTACAACTCTTGGCGTGACTGTTGTTTGGACTATCCTTTTTCGCCTGACTAA
          CTTCCGTGATACAATTCTTAGCAAGGATACTATTTGAACTGCTATCTCTGGTAAAACAAA
          GACGAGGAAAATGCCGCTTCTCAGAGGTAACGGGTGCACCTCTCCTTGTATCGCTACTAA
          CATCAGTATAGCGTCCATCTGCCGTAGAACTGACCGCATTGTCGCTGGCCCCGCCATGTA
          CAGCGCACTCATACCCGACGATGGAGGTCTGCCAGAAGCCACTGAAAGTGACACCGCCCT
          AGGGATTGGTCCGCCTTAACTAATGCACTTAGTCGTTACCCCTATGGCCCTGGCTGACTC

          CTACTGCGGGGACTGTTAATGGAAAAGCAACGGCCCTGTAAGGACATATTCGTAGAGACA
          CTACTGTGGGGACTGTTGATGGAAGAGTGGCGGCCCAATAAGGACATATCTATAGAGACA
          GTACCGCGGGGACTGTCGATAGAAGAGTAACGGTTCTGTAAGGACATACCTACAGGGGCA
          CTATTGTGGGGTCAGTCGTTGGAGGACGTACGGCTCTATGTGACCACACCCAAATAGACA
          TCACCGCGACATTGATGAGTGCAAAGGATCCTGATTTAAAGGTTCACATCCACGGAAGTG
          ATAATGCGGTCAACATGAAGGAATACGGTACTATTCTGGCGCTACAAATTTCTCGGAGTG
          CTCACACGTTATTCATATAAGACAGACCAAGTAACGCCGTATAGCACTATTAAGGAGCTG
          AAAGCATAGCAGATGGTACTAGTAACAATGTCACCACCAACTACTACGATCATGGCGGTC

          TGTCGTCACAACCGAGGAATGTTTCCTGTTTAGGGCCCAAGTTAAGACCTAACGCGTATC
          TGTCGCCTTAAGCGAGGAAAGTATACCGTATAGGACCGGAGTTAAGACCTAACGTGAACC
          TGTCTCCCCAAGCAGGGACTGTTCTCTGTATGGGGCAAGAGTTAAGACCTACCGCGCATC
          TGTCGAACAGAGCAAGGACTGTCTACTGCATAAGGCTAGAGCCAGGGCTCTACGCATGCA
          CACCGCGTCAGACGTGGAATATTTCGCGCGGGTAGTCTGGTGAAGGACTTAACGGAATCC
          TAGAGGAATGGCAGAGGGTTATAGCCTGCGACTAGCTTGTATCAAGTTAGTGCGATATCC
          CTTGTAATTAGGGAAATCTATGGCGATGCATGGAGCCAAGGCGGGTCCCCTCCGAGGCAA
          GGCTACCCCAGTACAGGTTATGGTGGTGAACGGTCTAAAAATGGTAACGCTGAGGAACGA

          CGTGCCTTCGGACATTTATTTCTTATAGAAAGGATAGTACTATCTAGACCGCAACATTTT
          CCTGCCTTGGGGCATGTGTTGCGTATTGAACGGGTAGAACTATCTAGATTGAAACAACTT
          CGTGCCTTGGGGCTTGCATTTCTTGTGGAAGGTGTAGTACTATTACGATTATTACAGTTC
          CGTGCTTCGGGGTATGTGCATCGTACGGATGGAGCAATATCAGCAATATTGCAATCATTT
          CGTTAAGTACAGTCTGCTTGTCCCATATGCAGCCTAGCACCTCGTTGATGACGGTGGCCT
          CAGACAACCGAGTCCACGCTCATTGTGCGCATTACAGGAATATGAAGACTGTAATGGCGT
          AAATGGCTAAATCTCGTGATGCTCTTTCGTGCGGCCGTACCTCTATAGTTACGTTGTAGT
          AGAGCGTGGACGCCCGCTCTGAGGATATATGAGACAACACAGTTGCGGTTATCTTAGCAA

          AAGGTAAGTAAGGTCGTGTTGGCGTGGTGAAAGCTAAAGAGTGGAATCTTTCCTTTCTTT
          AAGGCAAGCAAGGTAATGTTCGCATGGTGGAAGCCCAATAGCGGACTCCTTACGTTCTTC
          AGGGCCAGCAAGGTAATGTTTGCATGATGAAGGCTAAGTACCGGACTCTTTCCGTTCTTC
          GAGGCCTGCTAGGCAGCTCTCACGAGGCGCAGGCTCAACAGCAGACGTCCCCTGCCCTTC
          GTATTCGTACAGGGATTCCCGGATGGCCATATCTGTTGTTGTGTGCCTTTTTTGCTATCC
          GAGCGTCACGAGACGCGGGCCGTGGGCTATGAGTGCTATTACGCGTCCGTCTTATCCAGC
          ACTCGGGCCTTAGAGCGACTTACTACTTGACGGTGTTATCACATTCCCCCCCTGCTCCCA
          CCGCATGCTGGTGAGTGGCTACTGTAGTGCCAGAGTTATTGCGGGCTCTCGTTATGTATC

          CTTGGTATAACCGAGATTCGGCCGCTGACTGTCCCCTACATGAACTATCGATAAGCGTGA
          TCAGGTGTAATTGAGGTCTGGCTGTGGAGTGTTCCCTACATAACCTACCGATACGCGGAA
          TCTAGTGTAAATGGGATTCGGCAGTTGAGTGCTCACTACATGACCCATCGATACGCTGAA
          ATAGGTACTACCAGGATTCGGACGCTGTATGCTCCCAACAGGACTCACTCATAGGCTGTT
          CGAAACATCTCTAATGCCATGTAGGCGATAGACCGTCACGTGACTGCTTCCTGCGCGGGG
          AAGGATGTCTCTGATCTTTCGCAACTGGGAGGCCCCAGTATGAATTCTTTGGGTATAGCC
          TTCAACATCTGGCGGTCCTCATCGCGGGGGTCCCTTCTGTCGACGGCTAATGAATTACAT
          CTAAATCACTTATTCAGCAGACGCTCCGAGTACTCCTTATCAACCTCCGGCCAAGCCGTA

          GGATGTGGCGCTACTCAGGGAATCTATGTAGAGACACCGGTTTTCGGCACCTTAGGTCGA
          GGATGTGGCGGTACACAGGGCGTCTGTATGGACACGCCGGTTTTCGGCACTATATGTTGA
          GGATGTCGCGGTACGCAGGGAACTCTCATAGAGATGCCGGTCCTTGGCACTATATGTCGT
          GGACGCAGCGGAGCGCAAGCAATCCACATCGAGTCGTCGGTCTTCGACACTCCACGTTGA
          TGACGCGTCAGGATGCTGGCGATTTGCGTTGAGATACTGCTGTAAGGCGACTGTTGCGTC
          GGACAGATGAACACACAGAGGCCTTGCGCGGTGATTCCTGCATGTGGAGAAATAAGTACT
          AGATGTAACGGCCGTAAAGAGAGCCCCGTGGTGCGGCTGGCCCTCGATAGAGGACGCGAT
          CGAAACACACGAATGACTGCGACCATTCTGACAAGTCCCATATTTGTTTAAGCAGGCGAT

          GTAAGGACGTGAGCTTGACGTATGTTTCGAGTTGCGCGAGAACAGGTGGTCGTACTTAAT
          GAAAGGATGTGAGCTTGACTTGCGTTTCGAGTTATGTGAGAACAGGTGGTCGCACATGAC
          GAGAGGATAAGAGCTTGACTCGCGCTTCGAGTCATTCGAGAATAGGTAATCGTACTCGAT
          GACGGGATACAAGTGTGAACTGCGCGTTCAGCTATGCGAAACCAGGTGGTAGAACTAGAT
          AGAGGAATCTACGAGCGCGTTGTGCTTCTAACCGATAACAAACAGCTGGAAATGCCACAT
          GATGGAGTATAATCGGAGATGTTGCCCAGGATTGCCCTAGAACCCTCGGGTTCATAGCAG
          CAGGGTCTGTCATGGGGAAGTCAATACAGCTCGATGGCTGGCCTCTAAGACCCGGAGGCT
          TTTAACCCTTAGGCACGGGCTTAGTGATGACCCTCACTTCGGGTGTCGATTACGTGAAGC

          AAGGTAGTTATGGAAAGTCCCTCACTTCAAAATGGGTCGCTGAGCTGGCACCCAGCGCAT
          AAGGTAGCTATCGAATATCCTCCAGTTCCAAACGGGCGGCTAGGATGCCACCAAGCACCA
          AAGGTAATCATGGAATGCCGCCCACTTCTTAATGGGCCGCTGAGTTGCGACCTAGCGCAA
          AAGGTAGACAAAGAACCTCCCTCTCTATCCAATGGGCCGATAGCCTGCTACATAGTGCGT
          GTCATATTCTGCGTAGGGACCTCCCCATGTTGCGCTCCCACCAAGCTCCACCCTGACGAA
          GCCGCAGTGATTCGTGGGACCCTGCCAATAGGCGGATCTACGTCTCTCTTATCAGGTCAG
          AATGTATACCAAGAAGTATAGTTATATGTTAGGCGGTTAGTTCTTTCAGTGTAGGACCAA
          AGAGGTCATTATGTGTGCCAGCCGCACGCCCGTCCGTCACCAATACCTTCCACTGACCTA

          CCCTGAATCGCGTCAGTCGATAGGGCTTAGCAGGGGGAGGCGGCTCGTAGAGGTCAAGAA
          CCCCGAATCTGAATAGCTGGTAGAGCTTGGCAGGGAGAGGCGCCTCGTAGAGGATAAGAA
          CCTTGCACATCAATAGCAGGCAGGGCTTTAAAGGGGGATGCGCGTTGTAGAGTTTAAAAA
          CCCAGAACATCGTCAGCCAGTGGGTTTTAGTCGAGGGATACATCACTTCGAGGAGTAGAA
          GCCTGAACGCTACCCTATAAAGTGTCCGAGTCTAGTAACGCGGCCTATGGAGTAGTCGGT
          TTCCCCACATCGCAACATAGAAAATTCTTGCCTGGGAGTGCGTCTCATGAAAGCGGTGCT
          CCTATAAGATAGTCCCGAACTATCCAGTCTAGGAGTGGCGGGTAAAGGTTGGGAGCAGGG
          CAAACCACGATGCCCTATGGAATACCTTAGTCCGAAGGTTAGTGTCGGCCAACTCCTTTA

          AAGTCCAGATATGGATCCCGCGTTCGGCGCCGTCCAGAGATCTAGAATCGTCTTCACGGT
          AAGTCCTGATATAAATCCTGCGTTCCGCACCGCCCAGAGATCTGGATTTGTCCTCTGTGC
          AGGTCCAGACATGCACCCTGCGCTCAGCGTGGCTTAGAGGTCTAAACTCGCCTCCGACGT
          TAGTCCGGATTTGGAGCCGGCCTACGGCGAGGCCCTCAGACACAGACTAGCCTCTAGCAG
          AAGATTCGTTGTCATCTTGTCGCCCGGCATAATTCATATAGCTAAGCTCATCAAAGGCCT
          AGGTTTTGACGTTCAGGCGTTGCTCAGAGTGATGCCGATATTCGGGGCGGCGTAAAATAC
          ACGGAATGTCGTCGGTCCATTTTACACGCGGCCGTGGACGCGCAACGTAGATGAGACATC
          CTGATTACACTTGGTTGCGCTAAATATGCCCCAATTGGTCGGCTGTCTAGAATATGGGGC

          CACTCTCTCACCCTTCATGCCCGGATCCCAGTGCACTTCGCATGAGTGGAAAGTGAGAGT
          CACTCCCTTACACTTCTTGCTCGAATCCCAGTATGCTTTGCGTAAACGACAATTGAGAAT
          CACTCTCTTACCCTTCTTGCACGGGCCCTACTATGCTTGGCATGAGTGAGAGACGAGAAT
          CACTTTCATGGTCTTGCTGCCCGGACCTAGCAATGATTTGCAAAAACGAGTAATGGGAAA
          CTTCCTTTTTATCCTCTTGGTTGGCCCACGCCGTGCCAGACATGGATGAGGTTTGGGATT
          TCCACTTTCGATCATTACGCTCATCAAGCGACAGGTCAAACATGTACCACACGCGATAAG
          AATGAACGTATTAGGGCAACATTGTCGACATCCTGTTATGCACGAAGGGGCTACTAAAGG
          CCCATTGCCTCATCTAGTTTATGCGCCTTACTTTAACCTGAATGTGGTAAGGTCGGAAAC

          ATGAGTTAGCTGGATGTATGCGAAGGATGTCCGGGCAGAT
          ATGAATTAGCTGGATGTATGCGAGGACTGTCCGGGCAGAA
          ATGAAATAGCTGGACGCACGCGAAGGCTGTCCGGGCAGAC
          ACGAGCTTGCTGGCTTTATGCTAGGACCGTTTGAGCAGAC
          CTATAAGAGTTACGCTATAGCGAGTTATATTCGACTTGAC
          CTCGAGAGGTTGGGTCAGCACAAACGACTTCTGAGCATGG
          TCAACTGTGTCAGGCTCATATGGACGTATTCCGGCCCAGG
          GCTGTGCTCAGTGGTTCTTACTGCGGAGGCCCGGTCGAGT

