 8 1000
t1        AAACCAATAATCCTTGAACCGACAGTGGATTGTTCATGATAGGCTGCTATCCTCTTGTCA
t2        AAATTAGGACTTATTGGACCGGCGGTGATTTTTCAATACTGGTCCGCAACTTTATTACCA
t3        AAACCAGAGGTTCCCGGTTTGGTGATGAACCGTTGATAATGGTCGGTGGTATCATTATCA
t4        AGAGCCGAAGTCTTTGGACGGACAATGAGCCATGGATACCGGTAAGCGATCCGGCTGTAA
t5        AAACTTGGAGTGTAAGGAACTACAGCGATTTATAGATGCACGTCAGTGCACCCGTAGGGG
t6        ATTATTATTGTTCTGGGGCCTGGGGCGGCCTGCAAATACCGGTTGATCCCATTGTCGCCG
t7        CGTCTCAGCGATTTTCTGCGTATCGTGTATTATGGATCCCGGTTTGGCATCACATTACTA
t8        CCCAATCTAGTCTCGGCTACCAGACATAACTGCGGGTATGTATCGCTCTCCTCGCGGTTC

          GTTATACATCGAGCTACCTTTAATCCTGGGTCCACGGGCTAGCCGCCTGTACTCTGCGAT
          GCTTTACATCGCGCTATTTTTGACGACGGGTTCAGAGGCTATCCACCTCCTTACTGCGAG
          GTTATATACCGTGCAACTTTTTATAATGCGCTTAGGGGTGACTCACCTGTATAGTACGCG
          GTTGTCTACTGTACTACCTCTTATGTCTACGTCAAAGGCCACCTGCCCGTAAACGGCTAA
          ACTACACAGCGTGCTATCTTTCAAGCTGGGGATAAAGGTTGTTATTCTTTATACTACGAG
          GTAAGTCACCGTACCGTGCTATGTGTTGTGCACGGAAGTTTATTGCAAGAACTCTGAGAG
          TTTAACCTAAGCACTGTGTATAGTGTTCGAAAAGTAATGTTTTAGGGAGCGTTCTTTTAG
          ACTTGATTCTGTCATTTAAACTATTCCAATGTTTAAGGTTCATCTGCTGCGGATGCGGTA

          TCGGCATTGTCTGTCACGACCGCCGCGGAAAACCGACTCAGTACATGATACACCAAATAG
          TTGGCATTCATTGTTGCAGTCACCGCTGGATATTGACTGACAACTAGGTACACCAATTAG
          TTGGCACTTATTCTCACGATCGTTGTTGGCATTTAACTAAGAACATGGCAAGCCAATTAA
          TGGGCGGCTATTGTCACGACCGCCGGAAACATCCTTTCCAGATTATGCTATACCAATTTG
          TCAGGTTATACTAAGGCAAACGTTGCGAGAACCCTCTCCAAAACTTAGGACATCAGTAAC
          TAAGACCCTACTGGTGCGTTAGCCGTGGTAGTGTTCCTTAATGCCTGGTGCATCGATAGA
          CAGGTCATTGCCATTGCGTCCAGTGTAGCGACGGGTAGCAAGTCTGGATTAGCGGCGTAT
          TCGGTCTAATCCCTTCTGCAGGCTTTGAAGGAGCTTCATCGTAACGCACAACCCGCCCAA

          AAGAGGCCATTCCCACGATGGAAACGACAGCATACGTCTTCGATGGTTACTGAGGCAATG
          ATACAGCCCCCTTTATAATGCGCACGATGCCAAAGGCGCCCGTCAGTCGTTTGCACGACG
          GAGCATCCCACCTCATGGTGAAAACGATGGGATTCATATGCGATCGTCGCTAAGTCGGCG
          AAGGAGATCCTTTCATGGCGGATACGAAGGTACACGCCCGGGTTGGTCGTTGGGCGGCCA
          CAGTAGGGTTCCTTAAGACGCACGCAGCCGTATCTGCTTGCGTTGGCTGTTAAGTTGGGG
          CAGTCGCACTTATTATGGGAGTACTGCCGGAAACTGTTTGTCCCCCATGTTGAACCGGGT
          AAGCAACTTAGGCAACAAGGAAACCACTTTTCATCACCTCCGTGCGTTATAGAGCCAGGG
          AGGAGGACGCGATTTTACTCACGAAGTTTGAATATATCCTCGCTGATGAACAAGCTAATT

          AACCTTCCAGTCGTCGGGGGAAGATCATTCTTCCTCAAGCCGGACGGGTTCGCGAACGTG
          TACTTTTTGAGTGCTGACAATAGCTTACCTTTCCTCAACCAGGACAAGCTCAGAAGCGTA
          CACCCTCTAAACGTTGAGAGGGGCTCATCTATCCTTAATGTGGACAAGCTCCCAAGTGTT
          AACATTTTCAATGTTGAGGGGTGGTTGTCCAGGATTGTCCTGGCTTATCCTACACTCCTA
          AGTATTCTCAGCGCAGACACGAGAACGCTAACTCCTAGCCTGGATTGTCTTGCAAGTGTA
          AGAACTGACCGGGGCGTCGGGCAGCTGCAACCCTTTCGCTTGAAATGACCTCACAGTAGA
          TGCGTCGCCACCAACGGGCGGCTATAGATGTCTCCTAGGGGGCCGTGTCTGGATACTTTT
          AGCCTGATCAAAGCGGCCCTTAGTCTCATATCCCCTGAGTAAAAACAGATATCCGTAATA

          TTGAGGACCGGTGGTAGTCTGGTAGACTGCACAACCATATTACACAACGCGCGCTTCGAG
          GTACGGATCAGCGCAGGTTCTGTAGACCGCGTAGCCCTACTACATACTGAGTTTTACGTG
          GCCAGAAACGGCATGAGCTCGCAAACGTGCAGAGCTCTTGCACATAATGCGCTTTGCGAG
          GTTATGATCGGCGTAAGCCCGGTAGCCAGCACAACTACTCCACATAAATCATTACTCGTG
          GTAACAAACGGTTTAGGTTCAGTAACGTACACGTCTATTCTAGACGAATCATTTTATCAC
          GCAACGACTTAAGTTAGGACTGTATTCTGCCAGCTAGTTCAAGCCGTGATGACGCGCGCA
          GAGACGTTCTCAATCAGTCCTGCTGTTTCCGCCGTCGCTTCAGACAATCCCTTTCGAGAA
          AAAACCGGAACAATGAATCCTACTGTTTGCACCGCCGAGTTGCCTCAGCCTGATGGCGGA

          CTTCTGGCAGTACACAAGACATACTGAGACGCCACAGGCCCCCGCGTGCGTACCTTGCCG
          CTTCCGACAGTACGCTAGTCACGGTGTGAGGCCCCAGGTCCTCGTGCGTGTACGATGTTA
          CGTCTGGCAGTAATTAAACCGCACCATCAGGTCACGGGTCCTTGTATGTGTGTGATGTCA
          GTCCCGGTCGTACATAGAGCACACCGACCAGCTCGCGGTTCCCGCGCACATGGGTGGTCG
          CGTCCAGCCGTACAAAAAATTCATCGACACACAAGAGGCCATGGGGTGCGCATGTACTTC
          TATTCGGTGGCACACATGATACTCGATCGAGATCCCGGCCTACATTATTGTGTACATCTA
          TGCTTTGGGAAGCACCGAGGGTACTCGTTACGTGTCCAATTTCGTCGATGTCGCTGAGTC
          CTTAGGACCGCACGTAGAATCCCATGCTTATGTAGAATGCGCTGTGTAAGCGAGTGTACG

          CTATCGCAGTCACTTGACTGATAATGGTAAAATGGTCGACAGTGTTTCACGCTCTAGAAA
          TTGTTGAACCTATCTAGCCGATTATGGTCGGATGGATGATTGCGTGTCGCGTGCAAGCCA
          TGATTACAAGTATTTAGCTGATAGTGAGTGGACGGCTAACGCCGTTTCATGCTCTAGTCA
          CTATTGCAGATGTCCAACTAATAATGAATAAATGCACAACAGGGTCTCGTGCACTAACCA
          TGGTTGCTATTAGATGGTTGATAGTAATTGTAGGGTTGAACATGTTTTATCCTCTAGTTA
          ACATTACTAATCTTTACGCTGCATCAGCTCAAAGGGTAATCGTACTCACATGCCCATGTC
          TCGTCAGGGCTCTACCACGGACATTAGTCCTGGGCTTGTGTGTCTTCTTCGATCCGCGGT
          TGGTCGTGGCTGCTTTGCTCATATTCAGGTAATGAACACGCGTCTTTTTGTGTTGCCCGG

          ACAGTTATGTAGTATCAGCTATGACGTTTTCAACGTATGAGAACTGTTATCTTTGCACGC
          GTGACGCCGTCGATGAAGTTTGGGCGCTCTAAACGCCAGGTAGCTGCCGTGCGTGCACGC
          GCAGCGATAGAGGTTTAGCCTGGATATTCCCTACGCGAGAAATCTGATATTATAGTACGC
          GCACTGTTGTGGGCTCTACTCGGGCGCTCTCCTCGTTTGGTAGCGGGTGTGCCTGCATGC
          GCAACGGCGCCATCTCTGCTCGGTCACTATAAATCTCGGAATGCCGGGACGACTACGCGT
          AGGAAAGGACATGTATCGTCCCACTGACCTTACTACTGTGGATAAGCCGTGGCTTCAGAT
          ATGACAAGGTGCGTTCCGTCTAGAATGCTTTTTTGGTGCGGTACATTTACGTCCCCGTAA
          ATGGTTAGGTGACTACGGGCCAATTAGTTGGAGATAAGCAGAGCCCCCGCTACCTTCATT

          GTTCAGCCACGCCAGCGTCGAGCCGGTACTGGCCCAGGCTCAAGAGCCCTAGTAGACAAA
          ATTTAGACGAATGTCTGCCACGGCGGTTCTGGTCCAAACCCAATGGACATTGGAAACAAA
          GTTGACCCGCATTGGCGCCGTGCCAGTAAAGGGTCAAGCGCTCCCGTCTCAGATAGCAAA
          GCTGAGCGTCATCAGTGTCGTACCGGTACTGTTTTGGACGCAACCGACTCAGAGACTGAA
          ATTGAATCCCGTTAGCGTCGTGCTAGCATTGGTGCAGGCCCAACAAGATCAGAAAGCAAT
          GTCGAGCATCGCGGAAGTCGTACCGGTACCGGCCTTAACAGCTTCGGTCGGGGAGGCCGA
          ACTATATCAATTTCGTATCAATTTTACTCAGCTCCATGGTAGCAAGGATTAATGGGCTAA
          CTACTGGACCATCTCCCCCCTCAATGGGTCCAATAAGGGCATCGCTCTTAATGTACTTCA

          TGCGTGCGGGATTTATTTGAGGATATTGTCTCCTTTCAGACCACCCTGGTCCCGTATTGT
          CGTGCGTTGGATCCATCTGAGGATATTAGCCTCGTCAAGACCTGCCTGGTTTTGCACTGT
          TATGTGATAGATTTACTTGAGAAGCTTAATTCCGTTTAGACCAGTTCGGTCTCGCGTTGT
          TAAACCTCGGCCCCATTTGAACGTCCTAGCCCCGTTCCGACCGGCTTGCCTTCGTCATAT
          AGTACCTTGAAATTACTCCAGACTATTAGCCTTGACTCGACTAGCTAGTTTTCGTAACGT
          TGTTCGGAGGCTTAACTCGAAAATGAGAGGCTCGTTCAAACGAGCTTAACCCCTTGAACA
          AATAGGGCAGGTCGTCTTTCTTGCGAGATTCCAATTGTGTCTGCACACAGTCCATTCCTC
          TAACTGACCAGTCTTCCTGGTCGTCAGATGCGCTGATGCAAGATCACCAACTGTCAGTGG

          ATCCTTCGCAAAAAAAAACCTCAAGGGGTCAGGGCTCGTTCTAGAACCGCAGCGACATTA
          ATACTCCGTAAGTAACTATATAGCGGGCTGAAGGCGCATTCTTGAGTCATGGCGCGACAG
          GTCCTAAACCAGTAAGGGCCACCTAAGGTGGGAGCACATGCTAGAGTTATAGTGTAACAG
          CTCTCTTGTAAGCAGAGACCTAAAGAGGTGGACGCTCATCTTCGAAATGAAGCGAGATAG
          TTCCTACCTGAGCGAAGAGCTGGAAGAATGTATGCGAATTCTTGACTTAACACGGAATAG
          ATTCTAGGCGTACAAAGTCTGCGGGGCGTACCAATGTAGATCAAACTCATCCGCCGAAAC
          GCCCAGCATATCTTTTAGATGCGCGACCCGCGAGGGTTCGAGCCGAACACGGTTAGAGTG
          AATCCAAGAGCACCTAGACTATCAAGTGAAATTGAAGTTGTAATACGATGCGTACAGGTT

          TCAAGTGACACCCGCGAAAGAGGCACGATATTCAGATTAATGGGCGTGGGCAAACCATTC
          CTTGGTAGCGCGCGCGAGAGAGACGAGGAATTCAGAGAACAGGGCATCGGCTATTCTTTG
          CCATATCACGCGCGTGAAACAAGATGAGAGGTCAGCGGTCCGAGGGTTGTTCAATCCTTC
          CCACGTAACGTGCGCAAAAGAGGAACTAAATTCAACGATTCAGGTGCTAGTGAGTCTCTT
          TCAAGAGACGTGAGCGACAGGAGAACGGGACCAGGCGGATCAGGCGCCCGACAAGTTTTC
          CCACGACGGTTGTCAGACAGTGTGACCCAATCCCGCTAAGTGAGCGCCGAAGTACCCTTC
          CAACCCGGGCAGTGGGATAATCTAATAGCTTACCGCGAGTATACTGCCGCCGACTTCTTA
          CTCCGTACAGGTAGATACAGCGGTCCTGCTTTCCCCGTCCCACTTGACGGCAATTACACC

          TTCCTAGGAGACGAGATTGGCATACGTGGGGGGCTGCGGTCTCCATGGCTAAGTTATCGT
          CTATTAGGAAACAAGGCTGGAGCATGGGCCGGGGTTGAGTCAACTTAGCCAAGCTTTCAC
          TCATCTGGAAGCGAGGCTGGCCTACGTGGGCGAATGGTGTGACCTTGGCCAGCTATCCGT
          TCCCCGGGGAACGACGTCGGCGAACGTGGGGGACTAGTGTCATCATGGCTAGCTCCACGC
          CGATCTGGTATAAAAGTCGGCGTTAGATAGGGAGAGGGGTCATTTTGGCTGGGTCGTCGT
          GCGACGGGGACGATAGCTAGCACATATGTGTGCGTCATATCTCGTCGGCCAGGCCTGCCT
          ATAGTCGATGGAGGAGCTGCGGCGCATGGGCAAACGATACTATCTTGTTTAAGCACTTAT
          GTGGTGGGCAATGCAGTTCTCGCGGATGGAGGCGCAGAGTATTCCGGATGAGACGAGCTG

          TGGAATGCCGAATGAACCCAAGCATGTCGAGAACTTACACGCCTGGCTGGGGGCAACACT
          TGATAGCCTGCATAAGCCCAGGCACGATGAGTACCCGCGCGCTTGGATGGGGATAGCGCT
          TGACATGCTGAATACATCCAGGCCTGATGAGCGCCCTTGAGCCTAGACAGGTACCTCGCT
          TGACGTATAAAATATACCATGGTCTCGCGAGGACCCGTGTTCTTGGGAGGGGTCAACATC
          TGATTAGCTTAATGTATCTAGGTCTAGTAAAGACTCGCGTACTTAGAGGGGGACCATATG
          TGGAACAATACACCCACGCACGCTCTAATACGACTCCCGTGCTTGATCTGCGGCAGACCT
          TCGGTAGTCCGCTGAATACTAACCTGATAGCGAGCGTGGCGTTAAAATGGAGACGGCATT
          TAACACACGAGCTTAGAACACGTCACGTGCCCTACGGTGCGCTAGACGAGGCCATGTCTT

          TTCTGCTCAAATCGAAGTGTATGCAGCACTCTTGTCCTTTAGGATATCGCGATACTGGTA
          TCCCGGCTAGATCGTAGTGTATACAGCTTCGTTGTCCTTTGGAATAGTGTGTTACCGAAC
          TTCTGGCTAGGTCAGAGTGGAATCAGCCCTCTTGGCCCGTGGAATAGCACGTTCTTGAAT
          TCTTGACAAGATCGAGGTGCCCTTCATTCCTCTGTCCTTTGGAGTAGCGCCTCTCTGCAT
          CACCAGTTGAACTGAGGTGTACCTCCTGCCCCTTGCGTATAGATCAGCACAAATTTGAAT
          CCACGTCTGACCCGGGGCACTCAGTATCTCTCCGTCCCTACGTAGTCTGCGCATATACCA
          TTCGCCACAGCCTGCGCTGTATAATGCACATGGAATCGTGGGTGTAGAGTGCTACTATCA
          CTTAATCCAGACATGGGCAGAATCTCCTCGTTCAGTCGACTGGTCACTGTCATGTCTGTC

          AGTTATTCCCCTGAAGGTCTTGCGCTAGGTGGGAGGGCCT
          GAACATTCCTCCGAAGGTTTCGCCCTAGGCAGATGAGCCG
          GGCCACACCCCCGAGGGCTTCATGTTCGTCAGGTACGCTA
          GGTCATTTCGCTGAAGTTCTTGTGCCCGGTGGACGTGCTG
          AGTCAATCCTTCGGAGTTTCCATGCAGGGTGGGTATGCCA
          CCTTAAACCGTTGCAGACTTTGAGAATTAGGGGGTCAGAG
          CGTTACGCTGGCATCTAATTGACAGCAGTTAGATGAGCGG
          AAGTACCCCAAATTTAGTCACGCGCCTCGGAGCCATCCTT

