 8 1000
t1        AGCGCTGCATTGCCACGGGATTGTACGGTCTTTACCCGAAATCGAGCCCGACAAGCACGA
t2        AGTATTTTACCTCCTCCAGAGGGAAGGGTATTTATACATCCCCTGATTTGGTCAGTACAA
t3        GACTCTGTTTGTAAAGCAAAGACTGCAGACTCCGGTTAAGACTGAAGGCTACGGCTCCAT
t4        GCCTCTGTTTATAAAGCAAAGTATGCGGAATCCGGTTGAGACCGAAGGCTACGGCTCCAT
t5        GAGATTGGATTATTGCGGTGGAGGGATGATGACACAAGTGCCACAATTTGGTCCGAACCA
t6        AGGGATGGCCTGGAGCAGGGTGTTAGCGCTGCGACTGGTGAGCCAGTCTAGGTAAGTCTC
t7        GAGATATCGCTATCGCGGGTGTACACTGCCCCCTGGGTGGCCGCGCTTCGGTCGGGACTG
t8        GAGTTATCAATATTGCGGGTGTACACTGCCCTCTGGGTGGCCGCGCTTCGGTCGGAACAG

          AAGAGATTACGCACAAGAAATGTTCTTAATCTCCGCGAAAACGAGATAAGTGTGAGCTAC
          GAAGACTCTGCTAGATGTCGTGGGCTAACACCACGCTAGATCGAATTAGACATATGCAGG
          GCGGTAGCGTACTTCTACCGTGCGTAAAGGTAGGGGACGCCAGATAATCGGCCACACTAG
          ACGGTAGCGTATTTCTACTGTGTGTAAAGGTAGGAGACGCGGTACAATCGGCCACATTGG
          CAGTAGCCATACCCATCCTGTGTGCCAGGGCTCAATTCTGGCTAGCACAGGAGTAACAAG
          GCCTAGTCGTTCAAACATCGTTCACATATCCTTCTGACCCCTAATTGTAGTCAACCGACA
          GTGGCGCCCTCGTCGCCCCTATGAAATAGTTCCTGTTAGGCTAAACGATCCTAATCAAGA
          GTGGCACCCTCGCCGCCCCTCCGAAACAGTCCCTGTTCGGCTAAACGATCCTAATCAGGA

          CCAGGTGGACACCCCGCCCAAGATCGGTGGCCGAGATTGAATCTAAAACTCCATCTTGGA
          ATGGTCTAACGGTTCGCCAGGGGGAGTCAGATTAGAACGAATATTCGATATTCGATCGTA
          AACAACAGGAAACCAGCTCGGGTGGGTCGGCTTAGGTCCAAAATTTCTTTTCTATTCGCG
          GGAAACAGGATACCAGCCAGGGCGGGTCGGCTTAGGTCCAAAGCTACTTTCTTAACCACG
          GATGCCTTCAGTGTTGCCTGGGAGCGTGAACTAAACAGGAGCTTCTGTGTCCCGATGGTG
          CATGAGTGCACAGCCAATCCGAGGTGCCTGTCCAGAATGGAAACGAATGTTATGTCTACG
          CGAGGTCAAGTAATAGCCCAAGCTGACCACGTTTGGATAAATATGATTACTAAGTATATG
          CGAGGTTAAGTAATCGCCCAAGCTGATCACGTTTGGATGAATACGATTACCAAGTATACG

          TGTCTGGAAGGTTAAAACCCAGCGTCCCGAGTTGATTCAGTGGGGTATACTCCGTTAGTT
          AGCACGGCTGACAGTGGCTAGCGGCTGTGCTCAGACATAGCAGTGCTCATCTCATTCGTC
          GGGGATGACAATACAATCTACTTCCCCCGATCCCAGTAATAGAAGTTGCTCAAATATACT
          GGAGATGACAATACAATCTGTTTCTCTCGATCCAAGTCTTGGAGGTCGCATAAACATGCA
          TGAACGTGTGTGAGCCGGACAGCTCCGTGCACCAGCTCGTGTGGACTTATAGTGAACGCT
          GACAACCCGGTCATCTACCCAGTCAATTGGCTCTACGCACTAACGCTCCTAATGTATAAC
          AGTACATATGTTAAAACTGGGCTGCTTGATGTTCATCTGGTGGTGGTCATAAAGTACAAC
          AGTACATAGGTTAAAACTCTGCTGCTTGATGTTCATCCGGTGGTGGTCATAAAGTATAAC

          TGTCCTTTGACCGTTACCCTTTCTCGCACTGCATCCAGCGATGGGTCCCGAGTTAGTGTT
          ATCTACCTAATCACAAACAGCTTTCACTTCACACCAACCGACGGTTTCAACGTGTACGTG
          AGAGCCGGTCGCGCAAATTAACCCAGTTCTGGGTTGTATCCCTTTGCCAGCTCTCAGCTG
          AGTGACGGTTGCGCAAATTTACCTAGTTCTGGGTTGTATCCCTGTGCCAGTTTTCGTATG
          AGCACGAACGGCGTAACTTTCTTTGTGTTAGGTTCCATTAAGAGATATTGTCAACACTCA
          AGCGCACCGAAAGTATTACTTTTGTCGCCTGGTATATAACACGAACCTTGGTGCCGCACA
          AGAATGTTAAGACCCATCTTATCTAGTTTTTGGCGAAGGGACCCACCCTGGTTAGATGCA
          AGAGTGTTAAGACCCATCTTATCTAACTTCTGGAGAACGGCCCCATCCTGGTTAGATGTA

          CCTGTTAGCATAGTGGAAGACTATGGTCAACTAGTACTCCGAATCGTGTACGGACGCCCA
          CTTGCTGATCAAGCCAATAGTTTTGGGTTCGTCTCATTATCCATAATGTCCGAAGGTCTC
          CGCGCCCGTTGCGCACGAGTTCGGGGGTTAGCCTTACGCCCGTTCTTATAGAAATTTGTC
          CGTGCCTGTGGCATGCGAGTTTGAGGGTGAGCTTAACTCCCGTCCTTACGTAAATTCGTC
          GCGGTCGTATAGGAATGACGAGCTCGGTCGGAGTGGAGTTAAGCCTTGTTCGGGGCTTGC
          TAAGTCGCTTAGGTGAAAGGTTATAGGGCGTGTTGCAATTTCTTTCGAGGTGAACCCCTA
          CCTACCAACTCCGTAAGAAGCACTAGCTGGGCGAATTGTTATAACCTGTCCGGGATCCCT
          CCTACCAACTCCGTAAGAAGCACCAGCTGGGCGAATTGTTATAACCTGTTCGAGATCTCA

          GGTACGACCACCTTCCCACGATTCGAGGTCGAAATCTATCCGCAATAGACTTCGGTAGAA
          GTCATGCCTAGTTTTCTGAGTCTTTAAAGGGATACCGGACCGCCGCGCACTTAATAGAGA
          GAAATCGTCTACCTCCCGAGGCGCCGTATAGGGGCCTTATCAAGATCACCGCCTGAAGAG
          GAAGCTGCCTACCCCGCGAGGCGCTGTATAGGGGCCCTATCACGATTACCGCCTGAAGAG
          GGGGGTAGATACCCTGTGCCCTGTTCTCCGTAAACAGTGATGTCATCGTACCGAGCGCCA
          AGGGTGACACGTCCCACATGGTGTTAGTAAAAGGCCTCGACGATGCCACTCCGAGTGAAT
          ATACCCGTCCAATTTCCACGACGTATCATGTTGGGTTCCCTGTTGAGTATTAGATCGAAC
          ATACCCAGCCGATTGCCACGACGCATCATGTTGGGTTCGTTGTTGAGTACTAGATCGAAC

          GTTTAGCTTTAGTCTCCTAAGATGCACTATAAGTGCTGAGGAAGGGCAGAAGTTGGCTCG
          ACCGCACTCTGCCGTTGTAAGTTAGACTATGAATGCGCGCATCTGGTAGAAGCCCATTCG
          GATTAACCCCCCTGAACAGCGCAACTTTACATCAGCGTTAAATGGCCAAGAGGTGATCTG
          GATTAACCACCCTAAACCACGCAACTCTATCTCAGCGTTGAACGGCCAGGAGGCGATTCG
          GGTTCGTTCTGAGTGTCCGGTCAATCGAATCGGTGCGGTGACAGGAGCAGAGTTTTTCCG
          AGTTCGCCGTTCACTCCCGTGAAAGGCAGTAACCGCGGACGCAAATATGAGGCCTCCACC
          TACTCGACTGATTAAGCAGTGTTTGAGTGCTCTAGAATCACTGGGGAGAAGACCCAATAC
          CACTCGACTGATTAAGCAGCGTTAGAATGCTCAAGAATCACTGGGGAGAAGACCCCACAC

          GTCGTCTAAACGACATTCTCAACTGAGGGGTCAGACCAGCCACGCGTTTCCCACCCTCGT
          GATTTTAGGACAGCAATCACCCCAGCGGAACGGACCCTTACAGCTTCCACTACATTCCCC
          TTCATCTAATATACCAACCCCGTAGCGCACCCGAGATAAACCCGAGTCCCCGTGATCCTG
          CTCCACTAACATCCTACCCCAGTAGGGCACCCGAGATAGACCCGAGCCCCTGGGATCTTG
          GCTGGCGTAAGCGTTTCTATCGCCGCCATTCTAAATCTGATGGATACCGTTAGCAGTCTT
          GTGTACAGAATCTTCTTAAAACGCACCGTCCCCGGGATGGCAGTGCCTTATCACCATCTC
          GCTTCCTGATATATAGTCGCTAACGCGTAATCTGTGTAGGCTGAATCCTCTGTTTATCCG
          GCTTTCTAATATATAGTCGTCGACGCGTAATCTGTGTAGTCTGGATCCTCTGTTTATCCG

          TGCTGCTAGATACCAATCCCTTGGCTACACTTATCGGTGTCCTTCCTGGATAAGAGACCA
          AACCGCTTAGTACAAGTTATTAGGTAATACTTTTGGGCGTTATTTCTGGGTTGGAAGCCA
          ATCTATAAACCTGCAACCTTTTTAGAAGACCCGGTGTGGACAGATCCGTGCAGAGTCCAA
          AGCCGTAAATCTCCAACCTTCTAAGGAAACCCGCTGCGGAAAGAGCCGCGCAGAGACCAA
          TATCGTGTCGGTCTCGCCATCGGCTATTACTAATAGGTGTCGTTCTAGTACTGAAATAGT
          AATTGGCACGTCTCTACGATTAACTGTGGCTATTACGCGGTTTCGTCATTCAGAGATCAT
          GGTGGTCCCGTCTGTGTTGTTAGCCGTCATGCGAAGACACGAAAACCTAATAGGAGAGCT
          GGTGGTCCCGTCTGTGTTGTTAGCCGTCATGCGAAGACACGAAAAACTAATTAGAGAGCT

          ATAGTGACGTTACCCAACACCAGCGTATACACGCTGTTGGAAGGCAGTCACGGAAACCAT
          CTAGGGTTGTTACCAACCTGTAACGCACCCGGGTTGGCCGATGGTAGTCAGGAGCGCTGG
          ACTCAATGATACCACCACGGCGGACGGACCGATGTAATTGTGGGCCTCCACATGGTTCTC
          ATTCAATGATACCACCACAGCGGATGATCGGGTGTAATGGTGGACCTCCACATTGATCTC
          CTCAGAGTGTTGCAAGACGGGTTGCCCATAAAGTTAATTCAATATTGTAGCCACACGCCA
          TGTTAACCGCCACCATACGGCTAGAGGAGAAGACATCATGCAGATCATTCAAGAGATTGA
          CCAGGGCCGAGATAGGGTGGTCTGAGGGGCGGTTCTTCCACGGATGGCTACGAAACCCGC
          CCAGGGCCGAGATAGGGTGGTCTGAGGGGCGGTTCTTCCACGGATGACTCCGAAACCTGC

          AGCGCACTAAAGCTTGAAATTTCTCTTCTTGTGTGGTCGTATACGACCCAGGTGCGGGCA
          GGCAGTTCGGGACTCGGAACCCCCTTCTTGGCGAGGATGCACCTGAATCGGACGCGGAGA
          CTCTATTAATAACCTGTCCAATTGCTAATCATACTGATGTACACAAGTTGGACGCGGGGC
          CTATGTTAATAACCTGTCCAATTGCTAATTACTCTGGTATACAAAACTTGGACGTGGTGG
          CCTCACTATAAGTTCGAAACCGGGTACCGGGCTCGCGATGAGTTTAGTCGCGGGTAATAG
          TATCGCTTCAAGCGGTCGTTATGCTTTCTAGATCGCACAGAGCTAGGGCTGGCACGGCGA
          TCTCGTTTGGATTCCGTTGCAAAATTCCCCATGTGTCAGCGTCGCGGACTTAGGTAGTTC
          TATCGTTTGGATTCCGTTGCAAAATTCCCCATGTGTCAGCGTCGAGAACTTAGGTAGCTC

          GTTTGAGTACTACAACGCACTCAAGCATGTACCAATCGACTTATCACACTTTATGCAAAG
          ATTGGAACATAGTGACACATTTGAAGAGGTAGAATCTGCTGAGCCAGATCTCACGACACA
          GCTGCTTAAAGGCGCGACTGAACGCTTAATCGTGGCCGCTCGGCCACTGCCTCCCTACAG
          GCTGTTTAATGGCGTGACTGAACACTTAACCGTTGCCGCTCGGCAATTTCCCCCCAATAG
          AAGGGATACTACGAGCCATCATAACGCCACTCCAGCAGTTAGGCTCTGACCAACATCGAT
          GTTAGATGAATAACATAGCTATCACCCGTCACCAACAAGTTAAACACCTTTAAAACCGAT
          GCCGGATGTCGGGCACCGTCATTGCAACTTCGTGAAATCTAGACCTTGACACGCTCCAAC
          GTCGGATGCTGGGCACCTTCATTGCAACTTCGTGAAACCCAGACCTTGACACGCTCCAAC

          CTATCTACCCCTCGAGTGCAAGCTGTAGAAACTTTCAATAAAACCGCTGTGTAAATAGCC
          TTCCTCATCGCACGCGTCCGCATAAGTGACACCCTTATCCAGTCACATACTCGAATCGCT
          TTACTCTGACTACGTATGTTAGTAAGAACCTCCGACGATATTCTCTACCCCTCACTAGGC
          CTACTCGGACTGCAGACGCTAGTAGAAATCTCCGACGATATTCTACAGCCCTGATACGGC
          CGCAAAAGTCCTCACCGACATATTTCACAAATTCAACATCACATTGACTGCCAAGCGGTC
          TTCGCCATTGTTTAGGCCTGAATCCTAAATATCCATGGTTTACCGGCCGAAGACGCTATT
          CGATTCTGCAATTGGGTGCCCCCAGCTTAAAGACAGCCGTAGCTTCCTGTCTGGGCACTG
          CGGTTCTGCAATTGGGTGCCTCCAGTTAAGAGCCAGCAGTAGCTTCCTGTCTGGGCACTG

          AACCGCATGTTCTGTACGCTATAGAGAAATGCGCACCTATACAAACCGGAACTAGCTCTC
          ACATCCTTTCCTATTATGGTGGTAAGATTTGAGTTATGGCATTAACCGAAATGAGCTTCG
          TTCTCCGCTCCGAAACCTTCAGTTAGGAAGGTTCCTTCGTACGATGCAGCGTCAGCCGCG
          TACTCCGCCCCGAGCTCTCCAGTTAGATAAGTTCCCTCGTGAGATGCAGCGTGAGCCGCG
          ATTCTAAACGTCCTCATGCAGCTTAAATAAATCCTCTGAGTACTACTGATTCTAAACCTC
          ACCTCTCGGTCTAATAAGTTCCCGGGCTAATTGAGCTCTAGATTTTATTAAGGAATACTA
          GCTGCAAGCATCACGGAACAACTTAGGGCAGTCGCCCTACGGTCACTTGTGACACGTCTT
          GCTGCCAGCATCACGGAACAACTTAAGGCAGTCCCCTTACGGTCACTTGTGACACGTCTA

          GCCGCGAAAGTCATCCGTTGAGGTCTCCAGTACTCGTACTCAATGGAGCTTAGCCTGCGT
          GATTCGATGTCCAGGTGCAGGGTCTACCGATCGCCGCACGTTCGCGAATCCGGTCTGTGT
          GGTCCCCAGTCTACTGACACCGTTGTATTTGGTATTGCTATAGCGGAATCTAGCCATAGC
          GGTCCTCAGTCCATGGACACCGTTGTATATGGTATTGCTACAGCGGAATCAAGCCATATC
          TGACCACCGTCCGTGCGCACAATTTCACCAAGCGCTAATTAGAATTGATCAATGTTTGAT
          AGAGAGACCTCTGCCCACCTGTTTTTGTTAGAGAGTATTTCGACAAGATGAGTTCGTAGC
          AGCATGAATACGGCGAGGGTAGATTTCCCATCGGTATCTCAGCATAGTACTGGCGTTAGT
          AGCACGAATACGGCGAGGGCAGATCTCCTATCGGTATCTCAGCATAGCACTGTCGTTAGT

          CACCATTATATATGCTTATGCGAATTTGGGAAAATTACGT
          TGTCGGCGTTTGAGCTAACATGAAGTCGAAAAGACTACAC
          TAATGAAGTCGGAGATCAATCATCATCGGATGAATGTGCG
          TGGCAAAATCGAAGATCAATTATCATCGCGTAACTGTGCG
          TGGGTGCCTAAGCACCTGGTTGGCGCGAGGCGAGTTTTGG
          TAAGGATAAGAGAGACTCGGTGAGGTTGAGTAAAGTGCCG
          CGTCGGTTAGAGGGTTTTGAAGTAATGCAATGGTTTGCAA
          CGTCGGTTAGAGGGTTTTGTAGTCATGAAGTAGTTTGTAA

