 8 1000
t1        CCGGCTACTCAATACTTTCGGCTCCGCAGACTCATTAAAAGACCCCGGCTCCCGTCCTTC
t2        CTATTCTTACTAGACGTTTCAGCGCGCAGATCCATTAGTTACTCAAGGGGCGGGTTCCTC
t3        CCTGTCTAGAAATTATCCTAGTAGTACGGATTTATCTCCCGGCTCCAGTTATGAACTCGT
t4        TCAGTTTGTTGAGTCGTAGTTGCGTCCAGACTCTTAATACGCATTAGGCCGGGGACTAAA
t5        TAAATTCATCGCGACGCAGTTGCGGACCGACGGAACATGCAGACTAGGCCAGGGGTATGT
t6        TAAATTTATCGCGCCGCAGTTGCGGACCGACGGAATACGCAAACTGGGCAAGGGGTGTGT
t7        TCAATAAATCGTGACCCAACCGAACCTAACGCCATAAAGTACCCTGGTATAGGACTTCTC
t8        TTATATTACTTTGGAATTGACATATCTGAGGTCGCAAAGCTGTACCCCATTGGTATTTCT

          TGATCCCCGCCAACCGCAACGTCGCCAGTCTGAAGACGTCTCTCGAGGGGTGTCCGGTAG
          TGGAGCCCATCAGCTGTTATGATGTTGGATCATGCGCGAGCATCCCGTAGGGGTTGGTGA
          CGCTGCTAGCTATTAAGCGCACCCTCGGCCAATATATGAGCTAACCGGGGTGCCTGGCAA
          CGTAGCGCACTCCGTCTTCAGCCAGCGCGTAATCAATATATCGCGTGAGGCGCACCACTA
          GGCTGTCGTCTGACCGGCTCACTGTCGATCTATATATAGGACCCGTGAAAAAACAGGACT
          GGCTGTCGTCCGACCGGCTCACTATCGCTCTATATACAGACCCCGTGAAAAACCAGGACT
          CGTTCTCTGCCCGTTGGTTCGTAGCCATCATACATCAGAACCACGCGTAGGCTTCTGGTG
          TGTAGTTCGTCCGTCGCGATGTTTCTGCTTCACCCTTGGCTGAGGTGTGGACGTGACGAC

          TCCTGACGTCATAAACTGGGTCACGGCCATTAATTATGAAGAATGTCTCGTGCTGTAAAG
          TTAACGCGCTGAGGAAATTTTAGCAATTCTCTATAGTTGAGGGAGTTTTCTGTCGTAAGG
          TCCAACCGCATAGATTAGGCAGGCGATCATCCCCCAAAGCGAACAGTTAACGTCGTTAAC
          CCGGACTGCCGAAGTTCTTCGAACCATCAGACTGAACGAGGAAAATCCCCCATTCTAAGA
          CTCTCCCGACGTGGATTTACACGCGCCTGTCGGCGGATACGAGGCTTACCGTAAGTCAAA
          CTTTCCCGACGTGATTCTACACGCGCCTGTCGGCGGCTACGAGGCTTACCGTAAGTCGAA
          CCGACCGAGAGGGGAAATAGGTGAGATGAACGTCAGCTCCCAAATATCCCTGTACAAAGG
          CCGAACGGCCGGGAGATTAACATGGACCAGAATCAAATTGTATGATTTCTCGCATTATGC

          CACTTGATTGTTAGATAGGTTGTCTTGCATGATAGGAGGTATCTTGCAAATGTGGGTCAG
          CAAGCGATCGTCAAATTGCACTTTTTGCCTATTAGGCGCGCTGTCATCGATCTGTGAGAG
          TCCCTGATTAACCAACCACGTTCCGTGGCCCCCAGGGGCTTTATAGAGGTTATTAATAAG
          GAATAGAGAGCTAGGCCGGGTTGTTCGTGCGATTACTGCGACACACAGGACATTACGACG
          CGCTCGAACGACGGGTTGGCTAATAGGCTATCCCAGAGTCTCATTAGCAATACTAGGATA
          CGCTCGATCGATGGGTTGGCTACTAGGCTCTCCTGGAGTCTCAACCGCAATACTCGGATA
          GACTAGGCATAGCCCCAGGGCGTTGCGTCAAGCTCGGGCGAACCAGCATCCACTCTTCAG
          AGCTAAACCGCCACTTGTGCGAAATTTCCGTGACAACGCCCCGACATGGTCAACCTCCAG

          ACGTGGATATAGGATAGCTACTAGGATTATTCAATGGTGGGTATGACGGCGTGGGAGGGT
          GCTCGTAGCAGGGGTGGATGCATCGTCGCTTGCCAGCTAAATATAATGGCCCTGGTAGGC
          CTGTTGTCATATGAAACCCAGTGCGTATTTAGAGTAAAGAGCACGGCTGTCGGCTTCGAT
          TCATGAGCGCTTAATCGTTATGGAGCGCTCCGACCGGAGTGAATTGCCGTCCGGACCGAC
          GCGCGCTCCCATACGAGGCCATGCAAGTTGCCCTCGCAGTCGTCCTTTTTTTATATCGAG
          GCGCGATCCCATACAAGGCCATGCATGTTCGCCTAAAAGTCGACCCTTCCCTAGATCTAG
          AGACGACGAGGTATGGAAAAACTACCGATGTTGATGAAGAATCCCTTGGTTTAGTAAGGT
          AAGCGATGATGGTGAGATCGAACGGCGGCTATAGCATCGCGAATCTCCGTGTAGTGAGGC

          ACAAAACATACACGTATCGTAACAATCACCGTCCAGGAGGAGTTAACGGTGCACGATCTC
          AAGGTGCGATTAACTCACGTACTAATTATAGCTCAAGCAAGTTCAAGTTTGTCCTACAGG
          ATAATGCGTTAATCCAAAGCACACGGGTTGACACGGGAGAAATCAGACCAATCAGACAAC
          ACACTCATTTAGTCTAGTTACCTGACTCGAGCCAGAGAGAAGTAATAAGAACTATCGATA
          CTCCGTGAAGACCTTGGGGCTACAATTAGCGGTCTGGAGCGAACTGACTGGCAGAAAGCT
          CTCCGTGGAGACCCTGGGGCTACAAGTAGCGACTCGGCGCGAACTGACTGGCAGAAAACG
          AGATCCCGATGGACAACCGCGATGACCAAAGCTTAGAGACCCTGCGGCACTCTGAGAAGT
          TGAGTAGGAGCGGTTTTAAATTTGTCCAAAGTCTAGGCAACCTACGCCAGCTCAAGGGCC

          AGTGCCCGGGAAAGATGTGAATCTATCCTCAAACACTATATGAAGCCCGTCACACTCTAG
          GACGTCTGATGAAATCCTTAGTCTATGAAACGGATTCGCGCGACGTCCAGAGCACTCTAG
          GTAATCCACCAGAATCACACGAGCCTACTAAAAGCTTGCAAGGTACTTTACGCCCCGCGA
          GTTGTTTGCGGAGTGTCCGATACACTGTGTGGTGGCTGTAAGTAGCTGCACACCCTATAA
          ACCGTTAGCTACCCCCCTCAAGCTCAATTCAGGCGGCCAACGGCGCGCCATCTAAGAGAG
          ACCGTCAGCTGCCCCCCTTAAGCTCAATTCAGGCGGCGAACGGCGTGTCACCTAAGAGAG
          TATGTTTTCAGGTCACACCAACCCTTGTCCCCGTGACTAGTAGGCGCCCCCATGCGCGGT
          GTTGTTAGTCGGATCCTAGAGTTCTCCTCCAAGCGATCAGTGGTCACTCGTCTACCTATC

          GACAGCACAGGGAGTAGGCCATGGGGCGTTGTTCATTGCGATCGAGATCACCCTAAGCGT
          GAAAGGCCAAGGAATAGTTCGTGAGGAGTATTTTTATACGATTGACAGTTGTCCAACCGA
          GATTTGAAGAATGTCAAAGATAGGGAGTTTTCGTACAGTGAAGGATTTTAGAATCTTTGC
          AAGATTGCGCAGTGAGGGTGTTGAGAGTTTATTATAAGAGACAGGCATTCATTGGCCTAC
          TAGCGAAAGCGAACCGAGTCTAAATAGTCCCACTAGCCTAACAGAAATAGTTCTATACGC
          TAGCGAAGGCGAAACGAGTGTAAATAGTCCCACTAGCCCAACAGAAATAGTCCTACCCGA
          GAAAGCGTCGGCAAGAGGGCGGCCGTGTCTAATAGGTTGGACTTGCGCGGTCCAATCCTC
          GAAGCAACCGAAAGGAGAGCTGAATTGCTCGATAGTTATAACCGGCCCTGCTGAGTGCTG

          TATCAATGATGCCTAACGCCTTATTTGCCATATCCATTAGAAAGGGCTTCGAAATGATGA
          TTCAAATGATTCCTGGCGTCTACAGCGTGCGACTTATGATGCAAAGCGAAGATATGTTCG
          TACCTGGGCCCGCGGGGGTTTTCTTTAGACGAAGTTTAGGTGGGGGCATAGGAGTGCCCA
          TACATGATAAGGTGGGCCCCTCCATATTCCGGCACGCAAAGTAAACCATTGGTACAGGGC
          CTCGGAGCTTAGCGGACGGCCCTAATGGTTGAAAACATGGGATCATTGACGCTGTCATGG
          CTTGGAGCTCAGCAGACGGCCCCAATGGTTGAACACATGGGACTATCGACGCTATCATGG
          TAACGCCATCTGACAGTGAATACAGCCCGTAACCCTTGCGAGACGGGCCCAGAACGCCTT
          CATCCGACTACGACAGTGGGCACAGCCTATAGATTTAGTGATATAATTGGGGCATTCCGT

          CAAGTATAGTCCGTGTGTCGTGCCCCGCCGCGAAGGCATGATAGCCCCCGTTGAAATCGA
          TAAGCATAGTGCGCTTATTGTATTCCGTAGTCGCGTAATAGTAGAGCCCCTTTGTCTAGT
          CGAGGATAAGTCGGCACTAGCAGCCCGGCCCGGGGCGTCGTAGGTACCTCCTGTAGACGG
          CGAGCGTGACCTGTTCTGCACAACTCGCTTCAGAATATTGCACCTGCCAATGAGAAATGG
          CAGGACTAGCTCGTCACTCTTATACGAGCTTTGGATGCTGTGAAATCGCCCGGCTAACAA
          CAGGACTAGTCCGTCGGTCTTATACGAGCTTTAGGTGCTGTGAGATCGCTCAGCTACCAA
          TTGTCACTTTTGGGAATCCTCCCTAAGGGTCTAATTTTTCGTCACGCGGTTGGATTGTGA
          CAGGTAGAGCCCGGATTTCTCACACGACCGCCAGTTCTTGGTTTGGCAACCGGCAAGCGT

          TGCGATAATTACCTGTGACTATTCTCTTGTTTCTAGAGAAGCGAAGTCCAGTAGTACACC
          ACCGATGGTTTTTTGGGTCCATTTTATAGTCAATTGCGAGAACAAGGACTTAGACATAGT
          AGTAACCATAAGTCACGCTTGTCTATCGACAACAAGGGACGCCGAATAAGGAGCTGAGTG
          TTTGATATCTCGTAATGGCTATAGTCCGGATGCAGGAAAGAATAAATTCACTACTGAGAA
          CAGACATACATACCCTTGAACCCTGTGGACCATTAGGAGGATAGAATCCCTCTCCAAGTT
          TAAACATACATACCCTGGAACTCTGTGGACCATTAGGGGGATAGAATCTCTCTCCAGGTT
          TGGGGTGCCATCCTATTCTAATATTTCTTGAGAGCACACCGGTAATTCCGGACTAAAGCT
          TTCCGGGTTGTATTACATCAACAACGCGACGATTCGTTGCGATGGCTCAACAATCAAGAC

          GGGACTCCAAGGCCCCATGCAAGCCAATGGCGCTCATCGGCGAGTATAGGGTTGCACGGC
          GGAATTGCTAGGCGCCACGCAAGCTGAACATGCTCAACGGTGGAATACTGGCTAGATGGG
          AAGGTTAAAAAGCGTCGTCTCGGTCAGAGACGCCGACTCTAGGGTCCAAAAATAGATGAG
          ACAGTCTCCACGTGCTACGTCTACCACTCCTAGCTAGCTTCGCGGTTACGACTAAGTAGG
          GGTATCTCGCGCGTCCGATCACACAGCCCTCAAAACGCCCACGAATTAAAACCACAAGAT
          GGTATCTCGCGCGTCTAATCACACAGCCCTCAAGACGTCCATGACCTAAAACCACAAGAT
          GGCTCACTAAGTCATGTTGTCTGACTTGTGCAGTGTGTCACGACGGTACGGCTTTGCAGC
          AACTCACTCATCGATCAGATAAGTGGCGGGTCGTCAGGTATGGCGCCGCAATGACGTAGT

          CACATCGCCCCATTCTATGATTACAACATGCAAATAAAGCTTCCGAGTGATGGCGACAGT
          TCTGCTGTCCCGTTACGTCAACATAGGACAGAAATGAAGAATATGAGGAGACGTGACGGT
          TGCGCAATTTAATCATGTGACAGCCGTCTTAACGTAGAGACTGTTAATTCCAGCAACCCT
          CTAGTCGTCTGTATTCCTGGCAGCGGGCGGGGTAAAAAGCATCCAAGTAATGGCGGAACC
          GTTGTATATTGGTTTCGCGTACATCGCAACGCATTAAGGTTCACGGGCAACGTAGCTGGT
          GTTTTATCTTGGTTTCGCGTACATCGCACCGCGTTAAAGTTCACAGCCAACGCAGCTGGT
          ACAGTAGTTAAACAAATTGCAATGGGTAACCGCTTGGTGCCTTCAAGAGGCCGTGCTCGC
          ATCGTCACCCCATCCAAGTAGCTTGGTCATCACCCATTGCACTCGAATAGCAAAATAGGT

          GCGTCTACGCCGGGAAGGGTGCAGCCGTGCTGCAAGTCGTACTAACTCTCCGTCGTTGTG
          AGGGCTACATCACGCGGGGAGTAGATGTATTCGAACTAAGGTTCCCTCCGTGCCACCGTA
          AGGGCCAGGTTAGCTAATCAAAGTTCTTACAGGGGCTTAAACCCGCCAGCAAATACCCTA
          GGGGTAAGGTTAAGTGTCCGCCGTTTCCGCCCTGCGTACAGCGAGTTCTACAATATTTCG
          GGCATTAAGACAAGAGAGTTAAGTAGGCGCGGAGGTCAAAACTCGTATTACACTATGACA
          GGCATTAAGATAAGAGAGTTAAGTAAGCGATGGGGTCCAAACTCGATTTACGTCATGACA
          CCCCCATGTGCAAGTGAGTCAAGTCTGAACTGAGAACCACGCTTAGAAGTGAAAGCCGTA
          TTAGTGCAAGAGGGCGCGCCAGATCTATTCCCAGGGTCAGGCTTTGTATCGGGTCCTACA

          AGAAGCAGTTCGACACATGCGGCCGTGACAGCCTGATGAGGGTTGCGTGCAGTTTAGCAG
          TGTGTCGGTCGCACACCCTTGGCCACACATTCATAGTATTGTCTGCAAACACGCTCGGAA
          CACTACTGCCCCACGTTTCCGGGGACCCAAAACTCGCAGGCGACGTGTGACACCCTATAG
          AAACTCGACCGAATGCTTAAAGCGAGGAATTCCTCGTACCGTCTACAAACATTATTGCAG
          ATGTACGTCAGGATATGTTGAGGAAAGTGGTCGCCTTACAAGCTAAAACTATCACAGGGT
          ATGTACGTCAGGATATGTTGCGGAATGTGGCCGCCTTGTAAGCTGAAACTGCCACAGGGC
          GGAATTAAAGAAGCAGCTTATCAGCCGTATCGGTCATGCAGGACTTCAGTTCCGCCGAAA
          CGTATACGACAGATGTCCAGACAGCTATATGACCGGCGCAGATCCTAAATTTGAGCGAAG

          GACGCGTTCCAGACATGGGAGCACTTACGAGTTTTAGTTACCAGATCAGGAGACACTCCG
          GCCCCAACTTATAGTCAGATGCTCAACCGCGTATTAGACTTCGGATCTAGACGTAACTAG
          ACCACAACGGGTTCATAGGCATCCGCTCGGTGATTGCCCTTTGAGCTTAGATGAAGCATT
          ATCCTAATTCAGAAATGAGCACCCATTCGGCGACTGCACCTCCGACCTCATCGCATCAAG
          CCAATACCCTAAACTTTAGCTCTCTTGTGGAAGGCGCTCCCTCGCTACAGGCGGTATCGC
          CCAATACCCTCGACTCTGGCTCTCTTCCGGACGGCGCTCCCCCGCTACAGGCGGTACCGC
          CCCCATTTCTGGGTACGGGTATACAAGCGAGGCGCGTATCCCTACTCAGACCAAATTGCA
          CCGCGTCTGCAGGTAAGGACATTAACACGGGTCAAGCGGTCTTGGTCTCCGGCATCTACA

          GGAACATGGATGTGTCATGACAATGCCGTAGTACTGTCAG
          CAAACCTAGATACGCCATTGCAGCGCCGCGGCAACGAATG
          AACGTAGAACTGCGTCTCCGCGGCCTAGTCGGATCGTTGC
          TACGCCGGGACACGCGATAACTGCGGGGAAGGCCTGCTCC
          CCCAGCACGACAGAGCGCGTCCGCCCAGCAGGCGCAAGGT
          CCCAACACGACAGGTCGCGTCCACCCGGCAGGCGCAAAGT
          AGAAGCGCAACTCCTTTTAGCAATGCAGGACACCCGAGCC
          ATTGGCGGATACCAGTCCGGTGATCCGGGGAGTTCAGTTT

