 8 1000
t1        TGCCTCTGTCCGAGGTTCCGATGCGACCGTTCAAAGGTTAAATACCCTCGTTCATGGTCG
t2        TGCCTCTACCCGAGGTTCGGACGCGACTGTACAAAGGTTGGATACCTTCGTTCATGGCCG
t3        TGCCTCCATCCGAGGTTCCTACGTGACGGTGTAAAGGATGATAACTTCGGTTTAGGGTCG
t4        CACTTTTGCGCAGGACCGTTGCATGGATGCTCACGGGCAAATAGTGACCGTTCACGGCTG
t5        TACTATTATCCAGTCCTTCAGCATAACCCTAAGGGTGCCACAAATTACGCTCCCTAGTTA
t6        TACTGTCAACTGATCAACATCTTTCGGAGTTTCTGAGCTGTTATCTCCCGCTCCGGGCTT
t7        CTCTTATATTTGTACGCAGCTTCCTCAGACAACCGGGCCCCGCTCTCACGTCGTGAACCT
t8        AATTCATATTAGAATAAACGTAATACTCGTTAATACATGATTACTACTCTCTGAAAACTC

          TTACCACATGCACGGCGCCTTAATTGCGCGTGTCCTGGCGTGTTCGATCTCGGAAATCCA
          TTACTACATGAACGGCGACTTATTTGCGCGTGTCCTGGCGTATTCGAACTCAGAAATCCG
          TTGTTACATGAACGACGACTCAATCGCGCGTTCCTTGGACTGCCCGACCCTACAAGTCTT
          TTGTCCTTCTAACGGCGTCCCAACTGAGCACGCCCTGGACCGTTCGGCCTAGGGGTTCTC
          CCAACCCGTGAAATACATCCTGGCCGCAAGCGGTCTTAGCTATCCGAACATTTAATTGTG
          TTATACCATCAACCGTATAGTACCACCGAGAACTATAGTCAGCACAACCATAGAGCGGTA
          CTATTTCGGAAGTTATTTATTAGCCGCGAATAAACGGACTAGCGTAGCCCTAGTACCGTA
          TAACCCCCCGCTCTATGGTTTTGGAACGTGCCACTATCACGGATGGACCCAGAGATTGTC

          GCGACACGATCACGTATCGCGGGTCATACCTCGTTACGGAGCGGTTGAGAGGCACAACTT
          GCGACATCATCTCATATCGTGGGCCATATCTCGTTATGGAGACGTTGAGAGGCACAACTT
          ACGCCGCGACTCCCTTCCGCGGGCTACGTCCTTTTCGGGTTTGGTTGAAATGGACAATTT
          ACACCGAAATCCCCATCCAGGCGCTATTTACCTCTCATGGATGGTAGAGAGGTTTTTCTG
          ACTTTGGGTACCTTCTGCGCGTACCGACCGACTGTCCTGAACGGCAAAAAGAACAAATGT
          TCATAAATATACCGATTCCCCAAATTCCCGTTGTACTATCGCCCTATTTTGGATCGGCTA
          GCGCGAACGACCACCCGCATGGGGCGTGTACCTATGCTTCTTAGACAACAAATCCTACCA
          GGACCCAATTCATAAAGTTCGGAGGTCGCATCCGAGACAGCCATCAGACAGGCACCACTA

          ACTCTAAGACAGGTGCGATGGTGTGGTCGTTATTGGAGACGTAAACAGAACGTGAGCGTT
          ATTTTAAGACAGGTGCGGCGGTGTCGCCGATACCGGAGTCGAATGCAGGACACGAGCAGT
          GCGTTAGACCAGGGGTAGTGGAATGTCCCAAACTGGGTTCAGAAACGGTGCATTTTCAGG
          GCCATATTATGGGGGTACTGGCGCGATAAAATCTACACTTGGAGATGTAATACAGCCGGG
          ATTCTAAGATACGGGCGCTGACGTGGTTGAAAGTAGCTTCGAGAGTTACATATCATTAGC
          GCCACTGGTATAAGCTGTTATAACGCCCTCAAACGGATTAAGCGGCGAACTGCATTTGAC
          GTTGTGAGGTAGAAGCACTTATCCGAGCGGGGTGATGTCGCCCCTCGGAGCATGTTTCAC
          GCGTACGCTAAGAACCATCCGTGAAGTTAAAAATTATCTTCTGTATGAAGCGTCATCAGT

          AATATCTCTATGCTCTTATAAGGCAATACGCTATAGGTGCCTATGGGGGCAATCGTATCA
          AATATCTCTATGCTATTATAAGGCAATACGCCACAAGTGCCTTTGGAGACAATCATATCG
          AGTGTGTCTGCGACTCTATCCGGCAACACGCTACAAGTGCCCTTGGAGACAACCTTACCG
          AATCCGTCCGGGCTTTTATGACGCTACCCACTATATCTGCCTCGAAAGATGCAGGAAACA
          AGTACGTCCAGGCCCCCGCGCAAGAATCGGTTAGATCCATCCTGGTGGGCAAACACTTTC
          AACTAACATTGTCGTAAGGGCAGAAATTACACGCCCCTGATAGTCAGGTCACATCCCCTG
          CATGGGCGCTGCCTCGATGCCAATGGTTCGCCAGTTGTTTAACCTGTAGGGCGACAGTAG
          GAGCTGTACCAACGTTCACTCCGGTATCCGAACAGTCCACATTAAGGCCCGGTCATTCAA

          CCACCCGGCGCCGGCAGAGGTTCACTGTGTCGGGTCACACACAGGTGGGGTCGCCAGAAG
          CCCCCCGGCGTCGGCAGAAGCTTGCTGAGTTGGGTCACACACAGGTGGGATCGCCGGTAG
          CTATGTTGTACCGGCGGGGGGTCACTGTGCCGGGTCACCCATAGGCGGGCCCGTTAGAAG
          TCCTAAGGAGCCGGTCGAGGGTGCTGACGCTAGGTCACATATCGGCAAGATTGCTCTTAT
          TTTAAGTAAGTCGGAGAGGGGTAGTGACATTATGCTGGACATTAGTAGCAGCGTCAGCGC
          AGTGGGTACTAAGTCACGGGACAATGTGTCGGTGCGACAGATGGCGGACAGCGACGGTCA
          ACAATTCGTCCCGAACAACAGACAGGAAGTTACTTTAGATACTGGACGATCCTCTCGTCG
          ATATGTGATGGCAGTGCTAGCCTTTAATGCCTCAGTCCGTGTTGATAGAGCTCTCAATCA

          GCCCTTTGCCACACGAACCTCCGATCGAATATGAGTTACAGAATGAGACCGATTCTGCTC
          GCCCTTTGCCACACGAACTTCCCATTAAACAGTAGTTACAGAACGAGACTGATCTTGCCC
          GCCTTTTGCTTAACGAGTCCCCTATTGAGCGTAAGCCACTGTATGAGAGTGGCACAGATC
          ATTTCCCGTCACTCGAGTCTTCCGTCGAGTAAAGGCCATTGTTCGAGGGTGGTATAACCT
          GCCCTCCACTCAACGGGTTTCCCCTCGAATACCACAGTCCGTTCAAGTGTAGTACAACCA
          GCTCGCCATCATACGAACTTCACGCCCAGAAACAAGGGAGGAACGCACGCTGGGGATCCC
          TATCCTCGCTCTATAAGCCTCAAACTTTGCCATTGATTTTAAATGTCCCGACCGAGTTGG
          GTTCCGCCTCTCCGGTGGTCGCTACATCGCGTGATACCTAGGCCGCGCGCGGCACGGACA

          CCTAGAGAGAGCCTCTGAATGACGGCCCGATCCTGTAATGAGGTCAGTCTGCTCGGATAG
          CCCAGAGATAGCCTCTGAATGATAGCTCGATCCTGAAATGAGGCCAGCCTGTTCGGACAG
          CTTAGGGTCAGTTTCAAACAGGCAGCTAAATCATGCGATGGGCCGGACCTGTCTGGCCAA
          CACAGACACAATCTTGCACTGATCACTCAATCATACGCTGAGGTCACACCGCCAGGTTAC
          TCCTTAAATTATCCGGCAGTGAAAGTTTGACCACCAGCCGAGCTCACTTCGCTCGATTGA
          TTCTTAATGTACTCTGCTGCGAAGGCCGGATTTGATCCCGGACCAACTCCGTTTGATAGG
          AGTACAGGCGATACCGATCGCAAATACTTATTAAATAGCGAGTCGCCGCTGTATCGTCGG
          ACTAGGATTGGGTTGAGGGCGCAGACTCAGAAGAGGACCTACCACATCCCGTCAGGGTGT

          TAATCCCCGAACCATAACTGGCACTATGTCACTTGCACAAGGAACCCAGTGCTCCACCGT
          TAATCCCTGAGTAATGACTGACACTACGCCATTTGCCCAAGAAACCCAGTGCCTCACCGT
          TAATTCTAGAGCGAGAGATGGCACTATTGCATTTGTAAAGGCGACACATTCTTCCACCGT
          GTATCCCACTGTGACCAACGGTGTTGTGGAACTCACACAAAGTGTACTTTATCTCTCAGT
          AACTCTCAGCCCGGCATCAAGTGTCACAAGATCCACCTAACATATAGGTCGGGTCCTAGG
          TGCTTTGAGGGCTAAGATATGCGAGATAATCGCCGAGCCCGTTACGGAGCCAGCTATTGT
          TGTATATAAACATCTAGGCCGATAGATGAACCTCAGCTGCGTTACAGGTTATGGCTGAGT
          TTATACTGGTAGCGCTGCACGTTGTGAGGTTAACTGCCCGCATCAATAGCATCGCTAACC

          ACCACTCGTGCGTCTTTGACGCCCGGCTTTGCCCGGTAGGAGTGAGAACGCGTGTTTTCA
          ACCACTCTTGCGTCTTGGATGCCCGGCTTTGCCCGGTTGGAGTGAGAATGAGTGTTTATA
          AACGCTTGAGCAACTTAGAGACCAGGTTTTGCTCGGTAGGAGTGAGTTTGAGGGTCCAAG
          GTAGTATGCAGAACCCAGTGACGTCGGTGCACTCAACGGGACTGGTAATATGAATTGGCG
          ACAGCTAAAGGCATCCAGAGTTTAAGCTCCGTCAGGTAGGCACCGAGGCACTAGCAGCCA
          CCTCTCCCTTGTGTTTCTCGCCCAAGTGGGACTTTGTCACAACCAAATCTAGAGATGGCA
          ACAGTCATTCACGCTCTTTGGCAGGGCACTGCCCAGAATCTGGCAATGACGGAGCTTGTA
          GTCCTCTGTTTAAATCCCCGCATGGGATCGGCCTCCTTGTGTACGATGCGTTCCCCGGCA

          AGCACTTCGAGGAGATCTGGGTCTTAATCAGATACATCATGGTTCTCCTAGCGGTGTGAG
          AGCACCTCGAGGAGACCTGGGTCTTAAACAGAGACATGCTGGTTCTCTTAGCGAAGTAAG
          TGCGCGTCCAGAATATGTGGGTGTAACAAAGGTCCAATTCAGCTTCCCTAATAGTGCGAC
          AGTGTCCTCAGCGCAGTCGGGTCAGAATAAGGCAAACCGCGTTCGTTCTAGTGGCTCGCC
          CGCGCCCTCAGAGCATTCGGAACAAAGAAGACTAGATCTCGATTGACGTAGTGGTACCTT
          TACCCGCAAGGATTCTCATAAACCGACTGCTTGTTTATATGGGTAATTCAACGGCATCGC
          TCTCCGTTTACAACTGTTGAGCACACCCGCCTAATGCCAGCAGGTGCCCTATTAAATCGG
          TAGGGTAATGGTGCACTGAAGGCTTTATCGCTACTGCCCTTGTTGAGTTAACGAATTGTG

          CTGTTACACCTGACAAGGACACTATATAGAAGGTCTCTAACATGGCTACGACGGGCAAGC
          CTGTTATACGTGGCAAGGACACTAAATAGAAGGTCCCTAACACAGCTACGACGGCCAAGC
          CCATAATATGGGGCGAGTCTCGAAAATAGACGGTATCTAATGTAGTCACGAGGGGTGGGT
          CTATTACCCGGGACGAGCATGCTAAACACCCGGCGTCTAATGCACATGCATTACGAGAGC
          CCGCTACCCGGGGCGAGCATCTTATGACCATAGTATCCACCGTAGTTACGTCTAGCAAAT
          TTGCCGTATGTCACGCAAACCGCGCAGATACATCGTCTGTCGTCAACGCGCTAAGTGTAT
          ATGGAAAGCAGGCCGAGAATCCTAACTCAGTCACGAATCCAGAAGGCATAGTAACTCCGA
          GCGACATTAGGATCGGATGTGGCTGACTCTTTTTAACCATGAGATGAGTTTCCGTTTCTG

          CTCCAAGGCGCCAACGCTGCGGCCGAGGGTTCGGTAACCGATGTCTACGCGGAAACGGCT
          CTCCAAGGCGCCAACGCTGCGGCCGAGGGATCGGCACCCGATGTCCGCGCGGAAACGGCT
          AATGGAAGCTGCTACACCGCTACCGAGGGACCGTCGTTTGATATTCGCGAAGGAACGGAC
          ACCCGGGGAGGAGCTTCCGTGCTTGAACGGTCGACGTTTGATGTGCGCGAGGACATGGCT
          CAAAGGGTCGGATGAGACGCATTTGGGGGAATAACCTATGACATGCGGGGCGTGCTGGTT
          ACCCAAGACTCTCCTCAACCACCCGGACACGTGCCTTAGCGCACTTGTTAGGACTTGGAT
          AGAAAGGGCCAAATAGACACACTGGTAAGGACAATTTCTAACGTCCCCGAAGAGTTGGAG
          CAGACCGAATACAGGCACGCGGTGACGGGCTTGATTCTCAAAACCTACGGCGGGTACTAA

          TGGAAAGCTCGCGTAGGGGGCTCCCGATCTACATAAGTATTCATCCATCTGGCTATGTGT
          TAGAAAGGTCGCGTAGGGGGCCCTCGATCTATCTAAGTATTCATCAATCTGGCTATGTGT
          TGCAAGGTGCGCATAGGGGGTACTCGATCTACTTATCTCACCATAAAAATGCCTGAGTGT
          TGCATGGTCTGTTGCGGGAGCATCCGAAGTCCCTTTCTAATTAAGGACTTGACTATGCGA
          TGTAAGGTTCGCGTCGGTGGCACGCAGGGTTCCTAAACTATCGTCTGCTCGGCCATGAGC
          TTCTGGTATCGAGCTGGCGGTATTAAAGGACTCAGGACCCTGGTAAGCCTCAAATTCTAA
          GACGAACTCAGCTATTAGGAAGAGCGGCAGGTCGGTCCAATCTGACACGTGCTAGAACGG
          GAAATTGACAAGGCCAGGGAACATCAGGCCGAGAGCGCAGACTCGTGTTGAGACTCCCAA

          CTTTGGACTTTGTACCTTTATGCGGTGTGGACGCCGCTTGAAGAGTAGGCGCGTCCTGCA
          CACTGGATTTGGTGCCTTCATGCGGTGTGGACGCTGCTTGAAGAGTAGGGGCGCCCTGCG
          CGCCGGAGTCAATGCCTTTATGCGGAGTGGCCGCTAATTCAAGATTAGGTGCGAGCTGCA
          CGCAAGACGGGGTCCCTATGCTCGGTGCGTTTGGCGAGTGACCAGCCGGCGCTCCTGGGT
          TACTAAAAGCACCGCCATTGTGCGGCGCGGCTGCTTGACGAGAATCAGATGCTTATCGGG
          GGCTGGAGAAAGCGTTCCTACGCAGATTTGCCGTGACAGGGGTCACCTCCCGAGTTACTA
          GAGGGGGATGGGTGCGCCCGTGGTTTCGAACTACAGGCCGAAAAGCTGTTACGTTGGTAT
          AGTCTGTGACTTTAATCTTGAATCGCACACACGAGGGGTGAGCAGTGGAGACTGCTCCCC

          TCGTTAATATATCCTGAGTTGGCTCTCATAATGTGCGACCCGACTAACTACACGGGGTAC
          TTGTCAATATATCCTAAGTTGATTATCATAATGTGTGACCTGATTAACTACACAAGGTAC
          TTGTCAATACATACTTAGGTGGAGCTCATCACGCCTGACCGGACTAATCATACGGTATAT
          TTGCGAAAATGAGCTAAGTTGGCGCCTGTCATGCATGACCAGACCAGATGCATAGTGTAT
          ATGCCAGTATTAAACGAGCCTTCAGCGGCCGCGCATAGCGGACGTCGTCCAATACGCGAC
          TCGCCCCGACAACCTGGGTCAGCGGTCACTGGTCTTAGCCGTGTTGACGAGATTCCAAGG
          ATCCCCGTCCAGTCCAAAATTAGAGGCATAGAGGTCAGTTCCTGGCATTCAGTGAGGGAG
          ACTACCCCCTAGCTCATGAAAGTACACTACTTAGATCTTCGTCACAGTGGTCCAACGCAA

          GCTAATGCATCTCAGCATGGCACGCAAATACAGACCAGTC
          GCTAATGCGTCCCGGCATAGCATGCAAATACAGAACAATC
          ACCAATACGTCTAAGCAGTGCGCATGATAACAAACTAGTA
          GCTAATGCAGTAAAACAGTCCTCCCATTTATGGTCTATAT
          CCCGAGATGGTTGAGCGGTTCGGACAAAAATAATTTAGCA
          TACTATCCCACAACACTGCTAACAGATTCACAGCTCAGCT
          TGCGTTGTAACTCAACGTAGAGGCAAAGTGCGGGTTAACT
          CCCAGCACATATAAGCCCAAAGATTATAAGGTGTTCCGGC

