 8 1000
t1        TCAACCCGATATGGTATTTGTACGTACGCTGCCTAAGGGCACGACCTTTTGACTCTGATA
t2        GCCACCCAATGTAAATTACGCATGTCTAGTGTCCAAGTACAAGACATTCCTACAAATCTA
t3        TTCACCCAACATTCGCCCGGTGGCCGCTTTGCTAGAGGATGATGCCTTTCGGCACTATTT
t4        TCGGCCTCTCATCGACCTTGTGCCTAGCAAGTCAGAGGTACCTAATCCCGCCGGGCGTAA
t5        TCCACAATTATCGAGCTACGAGCCTAGCAGGATGTCAGAACCCGTATCGCAGTCGTTTTT
t6        CCTGATCAGGACGAGTGGCGAGCCCATCAAAACGCTAGGCTCTCATTAGCATTCGTACCG
t7        TGCGTTTCTGACGATTCCCGCTACCGATGAATTGATCAAGTCTGTCTCGCAATGTCGCCC
t8        CCCCTATTTGATGAATTCCGTTTACGATGAATTGTCCAGGTCACCTTCGCGATATCCCTC

          CCAAGATATAACAGTAAATGACCTAATTAAGCTCTCTCCCCACAGGTCTCGTACCTCCCG
          AGAAGTCGTATCGATAGACACAAAGAGAGAACTCAAAAATCGTCGTCGCCGTCGTTGCTG
          CTCAGCTATAGACCGCAGGACCCGACGAGCGAATTTGGTGTGTCGACCTTATAGTTCTCC
          CCTGGACGCACACCTCGACGACCAATTTATATAAGAAATACGCAGTTCTCGTAATTGTCG
          CTGGAGAGAACAACCAATCACACCTGATATTTACGTGTCTGTCCAACTAAATGTTGACTG
          CAAGAGGGTACATCTAATTATCCCTGGTTCGAATATGGCTGCGCGGCTAAGTGCTTACTG
          TACAGGATGCAATTCTACTGAACTAGACCCACCCGTATCTGAGGAAATTAATGTTCGCCC
          TATAGAATCCAACTAAGTTGAACCAGACCCAACTGTGCGTGATGACATCAACGCCTACTC

          AACGCAGTAGTCCAGCATCAATGATCATAAACGGTCGGCGTGGAGCATGCCAGACTCTTG
          GCCGAGGAAAGTTGATGACAGTAATAGCGCGTAGTCAACTCAGCAAATATAAAAATATCG
          ACCGTTGTTAGGAAGCGCTCGGGGTTACCATATATCTACTTAGTGTATGCAGGATATATG
          ACCGCAACAAGCGCATGGCCGTAGTAGTGGTACGTCTCTTTGGTGTACGCGAGATGTGAG
          ATGGTGGTAAGCCAGTGAACTTGGAACCACCACATCGGGTCCGATTACGTGTATTACCCT
          GTAGTGATGGGTCAGCGCCCTCGGAGGCTATAAACCATCTCTATACCGGCGTAGTAACCC
          ATAGCGGCAGATCAGTGCACACGAAAGTGAACGATGGCTTCCATACACAGGCGATACACA
          ATAACGGTCGACTAGCGCACACCAAGGCGACGGATCGACGTCATCTACACGCGTTACTCA

          TCGCAGTCATTTTTCATTAGATAGAACAACTTGCCCTACTCTTCCCGAGTTTCACTTTAA
          GTGTTCCAACGACTCGTCAGCCGCAAAGCCCCGCCAGGCAATGCCGGGATCTTATCTTGA
          ATACCCCACTCACAGCTTATGTTTTACTCACCGCCAGACGCCGTTCCGTGCACGGGATTA
          ATTCACCTAACGCAAACTGGGTCTTACACCGCGCTGTTCAGCTGCCCATATGGATGATTG
          GTTATGTTGTCTCCCCTTCCAGTCGACCAATTACCATGTCACTCCGGCGGCCCACCACCA
          ACTTTATCGTCTCCCTTTCCGACCGACTAGCTGTTAGCTTATACTAGAGGCCCATCACCA
          CTTTCTCCCTCTTTCCTCACAGTTTTGCGGCTTCAACAGTTTATGGAAGGTACATCGTCC
          CTGTCTCCTTCTTTCCTCATGCTTGAGCGGCCCCAGCATTAAATGGAAAGTCTTCCGCCG

          AGGCGAGGAATCCGGACCAGCGACGAAAGCCAGATCGCCGACGAACACAGCGGATGCGTT
          ATGTGGAGATAGTGCCCCGATGTGGGTTGGTAGATCGTTATATGACTAGACCAAGATACC
          AAGTCAAGATCTCAAGATGGCGCCATAGCGAAGGACGCCTACCCGGGTGCCGGGAGCATG
          AAGTCAAACCATCGGGCTGATCTCGAGTGACTTGGCGTCTCGCGCGGTAATTACAACCCT
          TGTCGGACTAATAAGTGGCGGACAGCTCCTTTGGCCTACGTTAGACGGGGTAATTGAAAA
          AATCGGCCTTATCCGCAACGAGCAGGCTCTTCCGTTTACTTCAGACACAATAACTGGAAG
          TGCTGATTGTAACGGTATTGTGTAGACTTCCAGGTTCACGCCTGCTCCGCCCGCAGGAAC
          TACTAATTCGATCGGTGTCGTGTAGGCCTCCTGGCTCAGGCTAGGTACGTCGACGGGAAC

          GTGTCAAGAGACATCCGTCTATTCGTTTATCTGCGGATCTGTGTGACTTACCGAGTGTAT
          ACTCTGCGAGATATCCACTTGGTTATACATACTAGAACGAGCGAAAGTCTTTGAGGTCAC
          AACGCGCCGACTGTCAGACTTGTCTAGCGCTCTTCCTCGGTCATGAGCCTCCGTCCGAGT
          CCTATACAAAACGCCAGAATTGTCATAAGTTCCAGATTAGTTGTGCGTCTCTAGGTAAGG
          ATTTCACGTGCGAATTGGCATGCCGATTCTTACCTCGTGATCACCTAAACCCAAGAGAAT
          ATCTTGCGTTCGGATAGACATGCAGACCGTTACCCCGTGAGCCCATATACCCGTGCTAAA
          ATTATAAACGCGTACAGGGTTACAGCTTATTTTCGTTCATACGCTCATCCGAATGCTCAC
          ACTACAAATGCATGCGGATTTGTCGCGTGCCGTCATTCGTTAGCTCAAACACGTGATCAC

          TTTTTTTGTGCAAGAAAGCCCTTTGTCGTAGAAAATCCGTTCTTTAATATGAAACAGCGA
          TTCTCTGCTTTCGTAGATTTATCCGCCGTTGGCGACCCGTTTCCCCTCAGGAAGTTAAGC
          CGCACTCACTAGAGCTGGCGGTGGCAAGCTCGGCAAGTGCGGCACAGTTCACATCTATGC
          ACCTCTGAGTGGTGACAACCTAATGGCACCCGGCACCTAAGAATCAGCCTATAGTCAGGC
          CCCCACTTCCTATACGTCAATGCCAGCTCCGCCGGCGTGCGCCTACATTCCAGGTCGCGT
          GCTTACTTTCCATACGTTATTGCCACCTCCGTTAGTATATTTCCCGATAAATGGTTGAGC
          GTCTCTTCCCCATACGATCAGGCTTTTGTCTGTCTTATGCGGTACAGCTAACAACCGAGT
          GACTCCTCCACATACCACTCTACTCTTCCTTGTAACGTGTGCTATAGGACACGCCCGAGC

          GTGGGTTGTCCAAATATCAAGGGATTGATCGCTCTGGCAAGGGGCAGGGCTGTCCGACGG
          TCAAACTCTATGGGCAGAACGGGTTAAAGCGACTCTGTGAAGAACAGGCTTGCCTGTAGC
          ATAATTATGGTCAGTGCCACGTGTCTCACTGCCTCGCTGGACCCGTGGCCCGTCAGTCGA
          TCCGTGTCAACAAACGGTGCGCATCTCATCACCCTTGCAGACCCTAGGTCTACCCGTTGG
          TTGAAAGGGCCATCCGACGATGGCAAGCTAGAGCACGTGAGGGTTTTGCTGACTATCTGC
          TTTGGAGGATCGTGTGAAGAGGGCGAAGAGGGGAACTTGAGCGTTTGGCCATGTGATCGC
          CTAAATAGACTAAGTAGCAAAGGTCGGCTGAAGTACGCAAGAGTTTGCCAATATAATTGT
          CCAAATTGACTGAGAAGCACAGGTCGATTGGAGCACGCAAGGTCCCGGGTCAGTAATTGT

          GCAACATAACTCAACTAATTGGCATAAACTGATCGCAGTTTATCCTCATCCTGCTCACAG
          CCGAAACAATTGAGCCATTTGGCGTAATTCAACTAAAGACTGCAAAAACCAAAGCAAGAG
          TTGGAGCGCTACCGATGAATTGCGATGCTGAGCTTTGATTATATCACGGGCTGATCGGTA
          TCGATATACCACAGATAGAATGGGTAATTGCGTTGGCTATATAGGACGATTCACCCAGGG
          ACAAGATAAGCAAGACGCCTGATGATGACCTGCATTAGTCGGCTACTAACGAGAGCATGT
          ACAAAATATGCACAACTCCCGGCGATGACCTATACCAACCCATGCCTCCTGAAAAAGTGC
          TTCGGTTACCTTGTGTAACTGGCTCCGCCTCACACAAGGCGAAGACTGAAACACTCAGGA
          TCCAATCACCTTGAGTAATTGGTTCCGCCTCGCATGAAACGATGATTATTGCACACGCGT

          CCGTACTTGGTATTAATCTTCTAGCTAAACACCCCTCGCGCTCTTCTGGTTTTATTACTC
          CAAAGGAGGATTCCGCCCCGGTAAATATCGTGCCATACCTCCGGTTCAAAGTGAATCTCT
          CGGCGTAAGAAACTTTTCTTGTAGGCACGCAGTCCTCGTAGCAGTGGTGAAATAATTTTC
          CAATATCAGTCAAATTTCCTGTACACACTTGGCTCTCTTGGCAAATATGGGTCGGTATTC
          CGGCGGCCTGCAAACGCTGGTCCGACCATATCATTCTATTAGAACACAGAACCGGTCGGA
          TCCTGGCATTCAAAGGCCGATAAGATTATACTATCTTTACGCAATACCGAATCGGTGAGA
          CCGCGGGATTTGAAACCTACGAAGGCTGCGTAGCGTCCTCGCACCATTGAACCCGTCAGC
          CTGCGGGATTTATAACTCACCAATGCTACGTAGCGACCTCGCACCGTCGAACCCGTTAAT

          GCGACTTCTAGTCAGTCCCTGATATAGGTGGATTTCGAAGTTGCTGAGCCTATTCTTATC
          TTTACTCTAATTCTTAGCTCACTCTAGGTACTCTATGAATTGGATGGAATTGCTGCTACC
          TTATTATATACATAATGCTCCCATCAAGGATCCTGTGAAACCGGCGAAGCCCATTGATAT
          TTGGTCTATACCCAGCTATCCCATGAGCGAACTTGCAAAGCTAGCGGAACCCTCTACCAT
          TTGTCGAGCACTGCACGACCTCTTTGAGAGTTTCGTCGAGCTAAAACGGTTATGGTAGGC
          TGGCGGAATACCCCACCACTCCTCTGTGCGTTGCGCCGTGCCACCAAGGTCCTAGTAGGC
          TCATTTAACGCACCGCGCTCCCACCGCGGGTCTTAAGTAATTGAAAGGGTGATGCTGAGT
          TCGAATAATGCACTGCGTCCTGTCCGCTGGTTTTTTATTGTTGAAAAGATACTGATGGGT

          AGCGTCGTGCGGCCGTTGGAGCGTGTAACGAGGATGTTCTTGCTTCCACGCAGAACCATG
          GGGGTGCTGAGGCTGATCGGGAGATTGTCAAGAAAGCCTTTAATTCATTCACTTGTCACA
          CAGCCGCTGTTAAAAATAGCGGGGGTGCAGAGAATACCTTTATATATTACCCACTGCAGA
          CAGCCACTGTGGACACTATTGGGGATCCTGAGGCGCTTTCTTACTTGGTACAATTCCAGA
          TGAATACGAGCGTTGACGGAGAGGCTGCCGAGGCCCATCCCACCACATCTCGATTTTGGC
          TAATCACTAACACTGACGGAGAGGTAATCAAGGATTATTACGCGATACATCGATTTCGTC
          ATGTTATCATAATTCGCTGAATGGCTACTGAGGCCAATTACATTGTACTACGACTTTGTC
          ACATTATCGCAGATCACAGAGTAGCTGATGAGGCCAATGACGTTATACCTGGATCTTGTT

          CTAACGAATCCCTTCTGGTGGCTACCCGTGCCCTACTCTATATGGGTTGATACGGAATAA
          TCCATAATTTTTGTCTCGAAGCGGCCTGTATTCTATCCAACGTCGACGTAAAAGGTAGGA
          CCCATAACTTTTTATGGGCGATGAAGTATGGCTAATCCCCCGTCAGCGAGCATGCCCCAC
          TTCGAAAGTTTGCATGCGTACCGATATGCGACCAAGACCGTGTCGATATGAACGTTCCAC
          CCTTACAACCCTATAACTTTGGTCCGCATGTCCTGTATAGCGCCGTGATCCGCCCACCGG
          CCCTACGACGTGCTCACTCTGATCCGCGGGCCTTGTTGGGCGCCGTAATCCGACTACCGG
          AATCAAGAACCATGTGGGTCACTTAACATGTTCTACCGGGCGCTGCGATAAACATAATGA
          CCCTAAAAATCTTCCCAATTACTTAATGTGTCTTATCGGGCGTCGTCATAAGTACAATGA

          CTAATTAGGTACTCCTGGACACCTAGGTCGTCCCGTTAGACGACGGCCGCACCTGCCTAG
          CCTATATAGTGTTACCTGGCGCTCCGGCGTTTCAGACTGGCTACATCGGCACAGGATCAG
          CTATATCTAAGCCGTAGAACGCGCAGACATCCCGCGCAGGTGCCAATCGCGCCGTCCTGG
          CACAACTTTTGTACTCACCCACATAAGTACGTCAAAGGCTGGACTAAGTTGTCGTCTAGT
          CTGATCGCGTTTCTGCGAATGTCTTACGAATCGAGTTGGCTAGCTACTATGCTCTTTCAA
          CTGATTGTGTGTACTCGCATGCGTTTCGGTTCGGGTCTAGTGGCTACGATTCTTTTGCTG
          TTGGGTGCATTTTCACGTATTCGCCACGAACTAAGCCCAGCGTTTATAGTCCTGTTTCTG
          TTGATTGCGCTCCTACGTATGCGCGACAGACCAAGTCCAGCGCCAGTAGTAACGTTCCCA

          TCGCACCCTGTAAGGAGGGCGGAAAAAACCCCTCCTTTCTGGCTCTGCATTCTCCATCCC
          TCTCAATTCGTGGCAAGCCGCGGGGAGACCTTTCGTTGAAAGATCTGATCCAAAGCTCCA
          CTGCGTTTTGACAAGAGGAACGAGTAGGCCCATCACGAATTCACATGTTCAGCGCCATTC
          GTGAAACAAGGCGGGAGAGCCGAGTGAGCCCCTTGACCTCACTCCAGTTTATGCCAGCCC
          TGGGACCTTAATAGAAGACATCGTGAATTTCGCGGCATTTAGTTCCGACGCTCTCCGCCA
          AGAGATCTCAACAAAAGACACCGCGGGCATCGTGGCGCCTAGCCCTGATGTTCGCCGTCG
          TAGTCTTTTGACTAATAACACCACAGGTTAAATAGACTTCGATTTAGGCATGCCCCATCC
          AGGCTTATTGACTAATAGGCTGACAGATGTAGCAGACTCCGTTTCCAGCACCCCTCCTCA

          GTATATTTATGATGACAGAAGATTCAGTGCGACTGTTGGACGCCGCAGCCATTACCATGC
          CAACAATTGGTCCGACAACTGCTCCTAAATGATTATCAACGCATGTAGCCGTCGGGATAG
          TGGCGGTTAAATCGGTGCCGGACTTGAAGTGCTTGCATAGGCGACCGGAAAAATTACTAG
          ATACATTTGTATCAATGCCTGGTCTGGACTGACTGTTTAGAAGACTGACTAAAGCATCAC
          TAACCTCTGCAACCGCTATAAGCAGTAGGACAATAGGATACCCACAATATCGCTGCTTAG
          TTACCACCGCTTTAGTTGTAGGTAGATTGGTGTTAGTACTTCTTCAACCCGGCAGCTTAG
          CAACCACTATGATGGCAGCGGGAAAGAGGACGATATCATCTCTTCAATTTTCGTAATCAG
          GAGCGGTTACGGTGGCCTCCGGCGATAGCGAGATACCATTCCTTCAATCTCCGTAGACAA

          CAGGCAGCGATCAACATAGCTTCCGTACAATGTGAAGTCA
          TACGTAGTGATCCTAGCGGCATACCCAGGGTAATACGCAG
          AAGGTGACACAGGCCTCGTTACCACAATAATTGACCGCTG
          CGGGTGTCGGTTCTTTAGTTACCCGCGCAATAGGTAGTAA
          GAAACCACGATTCGAACCGCATCACAATAGAGGTGCACAT
          GAAAATTCAACTATATTGGTGCCATAGAAGAGGCGCACAT
          TGAGGGTTATACGGGAAAGTATTACAACCATGATGCACGT
          CAAGCGTTATGTAAGGTCGTCAAACAAACGTGCAGCTCGC

