 8 1000
t1        AAGTGTCTGCTGTAGGCGGCCATCAAGGATTCTTTGCGGCGCTAATCAGCGTGGATTACT
t2        AAGTGCCTGCTGTAGCCTGCTATCAAGGATCCTCTGTGACTCTAGTTGGAGTGGAGTGTC
t3        AGATGACCCCGCTAACCCCTTACGCGCGTTTTAGAATCGACAAATTGAGCATCATGCGCT
t4        GAGGTTTCGTGTCCCGGTCTCACACATTGATAAGTAACTCCCTACGAGGTTTATGATGAG
t5        AACCAAAACTTTTCACTAAAGTTCCATATGAGTCCGTTGCGATGTATGCGCTTGAGGCCG
t6        GACCGCCAGAGGTAGACTAGATACTACGTTTCGCCGTAGCAATGCACGGATCTTAATACG
t7        TGACGCCTTGAAATGAATATCGAGCACGGAACGAGCCGCAGATGTACGACCACCAAAAGG
t8        ATCCGTCAAGCGGCCAGCCAGATTCTCGACATGTGGCCAAAATGATTGAGGTCGAGGGTG

          GGACGTGTCTCCCCCCGCGCTCGGAGATTGGGAGAAAGCCAAGGGTCTCAAAGCATCAGC
          GGCCGCGTCCCCCCCCGCCCTCGGGGTCTGGTCGAAAGCCAAGGCCTTCCAGGCATCAAT
          TGATAAACTGCGGCCTCCTCCAGAGAAAGAAGGAGAGATACAGGCCTCTTATGTGCTCTG
          TCCAGACGTACACCCAGCACTCTTCGAATCTCTTGGGGTTGAGGTTGCTTATGCTCAACC
          TGTTGCAGACTGGGATAGCCTCGTGTCATTAGGGAAAATTCAGGCTGCTCTAGCGTGCTG
          AGTGGTAATTCACCCCGCTACAATGGGAAGATTGGCCCTTGCTATCGTGTCGATCTGGCC
          AACTGTTTCGGTGCTCGCTATAGCGAAGAAAGCACCGCCCGAAATCATTCAGGCCCGTCT
          ATGGGGTCAATAGGTAGTTATAGCGGCCAGAATCGGCAACGTAGTCCGCGAAGTGAAACA

          CGAGCGATTAATAACTTCGAGTCATCACGATGGCAGATGACTGGTGCTCGGCTGTCGTAA
          TAAGCGATTAGTAACGTCGATTCATCACGACGGCCGATGATTAGTGCTCGGCTGTCGTAA
          CGTATGGCCGTTCGTCTTCCTTCATAGACTCGATCAAATGACAGTACTTGCATGCTGGAA
          CACGAGGGTGTTCGGCACAGATCTTAAGAGTGGACATACGCTACTGGCGGCATAGAGAAT
          GTACATACGAATAGGCGTAAAGTTCAAGTTCGATATCCGATTAAACATTGCCCGGTGATA
          CAAGGATTCACCCGGAAGACCCTATGATTCTCATTGTAAGCCATAAAGCGTACGCTTAAA
          TGAAAAACTGATCGGCCCACTGCGTTCGTTTATCTTTTCGATTTCGCCCTCCTTTTGTAT
          TCCTTGATGGTTTGGTGTACTCCACCCGCGCGGTCAGCTAATGTAGTTCGTCTCGTTTAC

          ATCGGGCGACAGAGACCCTAACGATCACACAATCCGATAGTTTATTGGCCAGCGACACGA
          ACCAGGCGACAGAGACCCTAATAATTACACAATCTAATCACTTATTGGACAGCGACACGG
          GCCGGATGGCAGGGATCCAGTTATTCCCGGAGTCTATCTACTAAGTGAACACCGACGCAT
          CAAGGACCTCAGGTATACCCACGATGCCTCCTTCTGATGAAACGCGGAAGAGTCGCACAT
          TGGAGTCGTCCGGCATAAAATCCATCATATTTCACAGCGGTACTCTAGACGGCCAGATGT
          TGAAGGTCTACGGGATGGTATCTCATCTAGCAACGAGTGATAATTCCGACTGTCAAACAC
          TGCAGACCGCGAGCCTGGGAACAACCACCGTTCCTAAACGCATTGTGACGTCTAGTACCT
          CTGGAGCTTGATCAGAAGTCGTACTGGCGGCAATTTACAAGGTCCTAGAGCGCCATATGA

          AGACAGACAAATAGTACCAGGAGATCTATGTATCCCCCCAGCATAATGTGGCCCTCGGTC
          AGACTGACGAATAGCATCAACGCATTTACGACTCTCTCCAACCTGACGTAGCCCTCGGAT
          TTACCGTTGTGGGAGTTTAACCAGTGTGTGATTTGCCCAAGCGAAAATGGATAGACGGTT
          AATCCGTTCCTGAGGGTCCTTCACCTTACGCGTTATCCCGGGCGTCTCAAAAATTTGTAC
          AGCACAACAGGATGGCCTGGCGGCTAAACATTTTGCCTCCAGGATTGGAGGTTTCTGATT
          AGTTCGCAACACGGCCCCGGCTGAAACGCTAGCTACCCCTGGGGTCTAGAGCCCTGCTGC
          CGTTGACTGATAATGTTTAATACCATTTGACTTCGCCCCCCGGATATGTGGTCTCGCAAT
          AGTTGCTCGTTAAAACTGCATACGTACGGACCGAATTACCTGGGGGGCAAGATTAAAGGC

          CGTATGATCACGCGTGCGTGAGCGTGCGCGGTTATGGGCACGTAGGTGACATCGGATGGG
          TGTATGATCACGTGCGTGTGAACATGCCTGATTATGGGCACATTGCTCGCACCGACTGGA
          AGTACAACAACGAGCGCGAGGGCAAGATTAGAGATAGGATCAATGTTGGAAGTAGGCGAT
          GACGCGCGTGAATTTTTACGTTTCAAGACGACGCTTGGAGTCGTACAAAGTTAGCGAGCA
          TGTGTTTTTCGGCGCACTAGAGTCAAGAGGAGGGGTTACCTACCGTAGTTATTGCGGGTG
          AGTACATATGCCTACACCGCGATCGGTGTGGATGTTTAGTTAGCAATGCTCACAAGAGGC
          TTTAAAAGTGCGCAAACGGGACCCCACTTGATAGCAAACATATTGGTTGCCAGCTGCCTT
          CGTAAAAAGAGAATTTTCTTCGCTAATGTGTTGAAAGGTTTCTTATGGGTCTCAAGTGCG

          TTATACACTGCATGTGCGCACTGGTGCCGAGGATCCCGCAAAGTTTGGCGGGTGTTGTCC
          TCAGACACTGCACGCGCGCACTGGTCACGCGGATCCCATAACGTTTGGCGGAAGTTGTCC
          TCCACTAATTCGCGACCGTCTTATTTACTGAATCGGTGCAGTGCTCCCCAGTTACCCCTG
          TCCGCTAGCTCAGGGACGTCTATAGGGTTGTTGTCTCACGGTACTTAAACGGCATAGTCA
          CCGTCTATCTCTGGTGCTCAATGGCCATTAATGTCGCCCGGCCCGTAATAGAAATCCCGT
          TGGGTCAGATCTCGGACCCACCAAAAACCCCTGCCGTTTAGTCATTTCCAACAGTCGGGT
          TTCTCCAATACTCTATTCCAAAGCGGATCTGCTCTGCATTGCGTTCTGCGTCCATGAAAG
          CCGCTCAGATAAAATACACAAGGGAGAGCATCCCCGTCCGGTTCTTCACGGATGGGGTCA

          GAGGGTGTGGAAATCGCTGCACAGGACTGATGCCTTCCCAGTGATCCGATTCTTTATTTT
          GAGGGTGTGGAAATCGCTGCACGGGACGGAAGTTTTCGCAGTGACTCGATTCATAATTTT
          AGAAGAATCACGCCCCAAGAGCCACGTCCTGCCCACCTCGGGGGCCGAGATCTGCATTCT
          TGCTATCTCAGATGCAATCTTTTATCGAACAGTATTGATATCCCTCTGAGACTATTCCCG
          TGTAACCCTGGGCTAGGAATCCCAGGCAAGTGCCATCCCGCTGCTCCGTCATTCTAATCT
          TAGTGGCTCCAAACTAAGACCATAAAAAAAGACAAATGTAGTTTTTCGACAACCGGTTCT
          AGCCCAGGCCCCCCTCGCGCCCATTATAAGCATGACCTTGTTGTATGGGGCTTCCATACC
          CCAAGCGAGTAAGCATGCCCAAGCGCTTAAAGTAGATTTCTTGGATTGGCACCCCTTTCT

          GGCGACCGCCAAGGAATGGCCAACTGTTATGGCTCCATATTGCGTTTCATAGTGGAGCTC
          GGCGTCCGCCGAGGAATAGCCTTCTGTTGTGGCTTCATAGCGCGTTACATAGTGAAGTTC
          GTGAGCCGCAAGCAGGCTAACCGCTGCCACGGCCTTATGTCGTGTCGTACTACTGAACCG
          CAGCACCGACTGGTAAGACACATTTCGCATAGTCTGCTGCTCCCCTGTCTAGCAGAGTTC
          GTATCCGGTCCATTCCTAACTGCGTTCAATGGTCAAACGTTGAGCCAATCTGTGGGGGCT
          CAAGCACGGCGGGTGTTACACACCCAGGATCGAGTCTTACCGCCTCGATATCTATGGTCC
          GAGGGCCGCCGGAGGCCGACCAGCTGGCTTACGTTCTCGATTACTTCTGTAGGGAGGCAG
          AAATCCAATTCGCGGTTCCTCGATTAATAGGGAATTGTGGACGAGTCACTTGAGGAGCCT

          GTCGCGGGGTATTCCGTGAATGGTACCAGATATCAAACGTTACCTGATTGTGATGTGATA
          ACCGCGGGGTATTCCGTAAATCGCACCAGATATCAAACGCAATTTGCATGTGGTGCGCTT
          CGTGGGGGGTGTTACTTGGGTCCAATAGGTGGTGCAATGGGGTCTAAGTACAACTCAATG
          AGGTGTAGTTATCAACCTGATTAAAAGAGTGATCACACAGTACATAACTATGCGGCAGAA
          AGCATGGGATATAGGTCCACCCAGTCCTGGTACGTGCTTACGAGCGAGCGACCGAGCTCG
          GAAAGAGTCATTGCTCTTGGCGAAATGGGCTAGCTCATGTATAGTAATCGCTGTATCCCA
          GTTAAGGGGCAGTAGCTGAACGGCGCTCGCGGCACGGCAGTACACCACCGCGGCAGTCTA
          GGTAGGGAGAGTCTCATTGTTTGAAGTCCCTGTGCGGAGTGAAACTACGGGGGTTCAACG

          CTGCCTCATGGGACGAGACCGGGCCCTTAACTAAGGCATGACTACATTAGCCCGTTCCCA
          TCGTTTCGTGGGACGAGACCTGGTCCTCGACCAAGGCATGACTACGTGAGCTCGCCCCTC
          TCGGTCGAGACAACGTGACCAGGCCTTTAGCTTTGGTTAAAGTCCGTTCGGCGAAACTTG
          TCGACCGCTATATTGGTACGACGGCTACAACCCTCATTATAGCTTGGCAGATAGGGCCCG
          CTGTGAGTCGGATCGTAGTAAAATCTACATCCCTAAGGGCTAAATTCTGGGCTGGACCGG
          TGACTAGCACAACCACTTCGATGACCTTAATTATCACAACCAGTTGATCCTCTGACTAGT
          CGGCTTCATGGTTCCAATTAGGATTCCTAGTTTGAGCGGCAGCCGACTATCTAACTAAAC
          CAGCCCCCTGACTCCTAAAGTGAGCATTAGCCTCTGAAGAGAGCAAATACACATGTCTCG

          CAAGGGAAACGCAACCTGATCACGCCACCCTATCCTTTAGGGGTAATAGGTGACAAACTC
          CAGGGGAAACGGAATATGGTGGCTCAACCCTAACATTTGGTGGCGATAGGAGACAATCGC
          CATGGGTCGTGAAACGTGATGGTACAACACAAATCGTTTGCGGTGACTGTAATACAGGGT
          TGGGATTAGAATGAAGGAGAGGTAGCGCCTTACCACCCTGCGTAAATTGGCGGAAAGCAT
          CAAAGGCGATAAGGTGTAAGGAGACGCGATTACTTATCCGAGGGGGGCAGAGTACGGAGC
          CCAGGGTACCCCCGAAGGGGGATCCTTCTTTAACCGCATACTAGGGTCGATCTGTACTGC
          CAAGAGTAGCCTCACGAGGGGAAGATGAATGACGACCCCAGGGGTGTCGTATAGCAGTAT
          CGTTAGAAATCCAACCGTAGAACCGCCTGTCACCCATGTAGGGTGGTCGAGATATTATTG

          AACAATTGGAAAAACACTACTTTACGGGTACGGAATCGCAAGAACAAGGAGTACGAAGAA
          AACAATTGGAAAGACACTACTCTACGGGTAGGGTATTGGAAGAACGGGGAATCTGAAGGA
          AGTGTTCGAACCTAAGGTTTCTCAAGATTCAAGTACCGTAATGGGGGTGAGGGGGTGAAC
          AAGGTCCGAGAATCCATCTTTTATCGGGTGGAACTCTATATAGGGTGTGGGTCGGGTCTG
          GAGAGTTGGGTGAGCCGTTCTCAAGGTATTGAACCCCCCTAAGTTAGAGCGGTTTTTTCG
          AAGGTTAGAAAGTCCACTTGTCATCGGACATGCTATCCCCCAAGACGCGAGTTGGAGCAG
          AAGGTGTGAGTAGAGCCTGGTATTCAAATGTGAGTCTATTAAGGGGGTGAGCATGCCGAT
          GAGATTAGCCGATTTCCCCCCGTAGACAAGAAACAATATTGGAGGGATAGGAATTTTGCG

          CTGCAACCTTCTGACAATCTGAAAGCAAAGCAATGTAATTATGACCGTGCTAAGAGGCGG
          CTGCGTTCTTTCAACAATTTGAAAGCAAGGCGATGTAATTATGACCCTGCCAATATGCGG
          TTACAAGTCACGACTGACCTGAGAGCCCAGCGGCGAAGGCGGCACCGAGCTCATCTATGG
          AGTCAACATGTTGCATACCCGGATGTAGCTCGACGCAAATAGCGATGAGCCCCCACATAA
          GTCGTATTTAATCGGGACGGGATAGTGTTAGGATATAGGTTGGTCTTAACCACAAGGCTA
          CTCACGCCGCCCGCCGATCTGTGCACATATTGTGAAATATAAGTTTGGGCCTAAATGTAG
          GTTTACGCGACGGCCTATGCGGGAGATTCATTTCGCAGGGAACGTCGCATCTATTTCCAT
          TATTTGCTAACTGTCCACCTTGGCAGATTATCAGAAAGATGAAACCGAGTCTACCTGTAA

          TGCTAAGTGTCACAGCAACTTGAGCTGACCGCCTCGATTGTCATGGACCGCTATCCAAAA
          CGCTAAGTATCACGGCAATTCGTAATAACCGTCTCGATTGAGACGGACAGCCACTTAAAA
          TACCAACAAGCCACTCAGTGCAGACACATAGTCCCGACCTTGGTTCCACATTTTTCAAGA
          CTTTGTATAGCTGCGCCACTTAGGATAAAAACGCTGTCGCCAGTAAGGTCCCCTAGAACA
          CGCTGAGTAGTTAATGTAGTAGAATCGTGATACACGGTGGACATAGACTCTTAAATTGAC
          TGAGGTCCCTAAGGATAAGCCCCAGCAAGCGAGTCGCCCATGTTGGGATCCGTTACAAAG
          TGCCGCATGGTTAAAGTCACGGCGCTCGCATCTACAACGAAGCACAGTCCCACAGCCACG
          TAGCGCGTGGAAGGAGCATTACCTCTTCCCAAAGTAAGTATGACTTATTGCGCCTCAAAA

          GCAGATATGCTTTCGTCGTGGGGAACCCTCTTGTCTACTCGTCTGTTTGTACAACGCCAA
          GCAAGGAAGCTTTCGTCGTGGGGGTCCATCTTGTCTACTCGTCTGTCTAGACAACGCGAA
          GAGGGGGTGATGGAAAGTTACGGACCTGATTAATCACCCGGGCTGCCGACAATGTGCGGA
          GACCCGCGGTGGCGGCTCCGTAAGCCTGCTGAAGTGGCGCAATGGCCCACAGGTTTGTAT
          ACAGACGGGTTGTTGGACTGTGGATCGACTTGAGTTGTATAGTAGCTTCTCATGCGCGAA
          GTAGGAGGATGAGTCGTACAAACATCTCCGACAGGGCCCCCATTAATCACAGTCCGCAAA
          GCGGGGTGAACGTAGGATAGAAGGCCAGGTCGCGGACTGCGGTAAGCTCTCCGTCGCTCG
          AGGAAAACATAGTCCCCTGGGATAGGCACCTAACCGCTATGGCAGCAGTTTATGATAATC

          AACACGTCTCTCGTAATCAGCTCCATATAAGCCTATGGAT
          AACACATTTCTCGCAACTCGCTCCAGATAAGCCTATGGAC
          GGTCCGTTCTTAGTCACACGTACTAGGTATACTTGCGGGT
          AACCCCACTTTCGGGATCACCTACAGATGTGTTTTCGATG
          GTCACGTACTCCGAAATGTCATGATGGTACGACCTTGGTG
          GGTCAAAAATCTGGCCATCCCTAACGGTATACTCAGGACA
          AGAGCGCATTCCGAAGGCGCGATCGGCAACTTACGCGATC
          ACATTGTAACCCAGTTCCCTTCATGTATACGTACATTGCT

