 8 1000
t1        TGGTTAGGAGTAGTAGATCTCGGGACGAAGGAATAACTATCCCACATGATTTGGGGTTGT
t2        TGGTTAGGAGGAGCAGATCTTGGGACGAAGGAATAACTATCCAACATGATGCGGGGTTGT
t3        CGGCCAGGAGCAGCAGAACGAGGGACGAAGGGATAACTACTGGGAATGATTAAGGGTTAA
t4        TGGGCAGGAGTAGCAGAACTTGTGACGAAGGAACTGCTATCCAGTACATTTCAGGGTTAA
t5        CCTACGAGGTGGGCAGAACATCGGGCCAAGCAATTATTCCTCCTCTCGAACTAGGTCTAA
t6        ACGCAGACTTAGACTGAGCATCGGATTACAGGATTACTGCCAGTCCTCAACCAGGTTCAA
t7        CACAGGAAACAGCCAGTATTACGCGTTTCGGCTTTACTGTCACGTTTATATCGTACATAT
t8        TTAGCGTAACGACTAGCGCGTTACACCGGGGGGTCACCACGAATCCTACAGCCAGACCAG

          ACAAATGCAACAAAGTGCATATCCTCAATGCAACAATAGGATGGACGATCGGCCTTACCC
          ACAAAAATAACATAATGCATGTCCTCAATGCAACAATTTGACGGACGATCGCCCTTACCC
          ACAGATGTAACGTAACGCATGTTCTTTATGTAATAATATTATTGACAATCGCTCTAACTC
          ACCGACATAACATAACGCATGTCCTCAATATAACAACATTACATACAATTGCCCTAACTT
          GTGACTCCCACAGAGCTTACGGCCACGACGAAACACAATTTCAGTTTTCTTTCTTCCGAT
          ACGCTTCCGGTCCAGTATACGCCGTTGACGAAATGCTAGCTTAAACAGTGTACCAAGGGT
          TCGCTACTGGGATCACGTATCCCGTTTGAGAAACGGTACACAGCGCACTGAACCCGAGTT
          TCAACACACGTGCCAAATTCCGCGTCCATGGAACACATCCTTACCACTCTTACTGAAGCT

          TAGTGTGAAGACGCAAATATCGGATCCTATCGCAGGTGCATTGCATGGTAAATGCAAATG
          TAATGTGTGGCCGCAGATATCTGATCCTATCGCAGATGCACTGCATGGTAAATGAAAGTG
          TAATGTGTGTACCTAGCTATCCGATTTTATTGCAGGGGCATTGTAAGGAAAATGCAGAAG
          TAATGTGTGGGCGCAGGTGTCTGAACTTATTGCAGGTGCATCATATTGAGAGTACGAAGA
          CCCTACTGAGACACAGCTGCCAAATCTGGCCGGAAGTGAATTGTAAAGGACACATCGACG
          CAACGATTGAACGCGGTAGGCCCGGACCAGCAGGGCCATCTCGTAAAAACCAGAATTAAG
          TGATGCACCCGCAATAGGTCCGATAAGCGTCCAGCAAAGATCATTTAGAGTATAGCGGCT
          AAACGATTAGCCAACTGGGTCTGCACTTCGTGAGAGCGGTAGATCTGTTTAGAAGAATTG

          CGTCGATTAGTAAGTTGATGCAACTTACTTAATAAGTGAACTTGAAAATCGGAAGCTGCG
          CGCCGATGAATGAGATAATGCAACTTACTTAAAAAGTGAACTCGAGAATTGGAAGGTTCG
          CGCCGATCGGTGAGATCATGTAACTTTCTCATAAGGTTCACCTGAAAACCGGATGGCGCG
          CGCCAATCGGTAAGGTGGTGTAACTCGCTTATGAGGTATACATGAAAATTGTAAGGTGCA
          TGCGGTTTAGCGGAGGGGTGCACCTTCCTTGAAGGTTATCTTGGAACGTAAGATAGTCCA
          CGACGATCGCTGGATTGATCGACATCTCCTGAAAGTCGATCCGAATTTAAAGGGCGCGCG
          CGTTGGGATGTCTAGTCGCCCATCTAAGCTCACGACTTTTCTAGCACCTGTACCTGCAGG
          TGGAGCTCCATATAATCTTTACCCTCTGCAAGCTAGAGGTCTTTAACTTGTGATTAGCCT

          CCCTTTTACTGTTCTCGCATCTATCACACCCTCCGATGTCCGCACGGTTCAGCTCACACG
          CTCCATCACTGTTCTCGCATCTATCACACCCTCAGATGTACGCACGGTTAAACTCACGTG
          TTCTACCACTGTTGTCGCACTTACCACTCCCTCACTTGTCCGTCCGGTGCAAGTCATACG
          CTTTACCATTGTTTCCGCGACTATAAAAGCCTCAGACGCCCGTCCACTGTACCTCGCGAG
          CCACATCCCAGTACCTGTGTCCCACGTATGCGACGTCGCTCGATCGGCGTAGCGCAAACA
          CTTAATCACTACATCGGCGACTGGAAACTTCTTTTGCGTCTCTCCGCTATGACCTACAAG
          CGTTCCGCCCAACTCCGTATCCCGCATTTTTCTTGTTGGTAGGACGGCATAGCTAATCTA
          TGTCTTCTATTCGCCCACTTGCCCAGGCCCATTCGCGGAGATATTGGCAAGTTTTTTAGG

          AGTCACGCATCGGACTCTCCATTGGTAAAGGGACCAGGGACCTACCCGAGGATCTATGGC
          AGTCACGCATCGGACTGTTCATTGGTCAAGGGACCGGGCAACTGCACGAGGTTTCATGAC
          TGGCACTCAATGGTCTGTTGACCGGTAAAGGGGCTAGGTAGCTGCCAGAGCACTTATAGC
          AGACACTCATCGGTCTCGTGATCAGTAAAGAGACTGGGCAGTTGACCGAGCACCTATGGC
          TGGGGCTCCTTTCAATTATGATCAACCAGGCCTGCAGCCAGTCGTCCGAAAATTCGTAGT
          CAAGACCCCTTAGACCAGTGACTGGTCAATGGCACAGGAAATCGACTGTGCACCGTTGGT
          TAATTCGCCCATCTTGCACATGCTTGCAAGGGCCCAGATGGATGACCGGGACCCTCTCAC
          CACAAGTCCTTGAGTCCCCCCAAGAGTGTGGGACTGTCAACCACGGCAGCTAGTACTACC

          GTGAAGTACTCGTACAGAGTGTAGTATTAGGTGACCCTTGGGGATAGGGCCCAGAATACG
          GTGAAGTCCTCATACAGAGTGTAGTATTAGGTGACCCCTCGGGATAGGGCCCGGAATACG
          GTGATGTATCTGTACAAAGTCACGTCTAAGGCCCCCCGTGGTGATAAGGCCCGGCATACG
          CTGAAGTATTCGTACCGGGTCTCGTCTTAGGTCACCCCTAGCGATAGGGACAGGTATAAA
          GTGAGGAATCCCTACGGAGTATTCGTACCGGAAACGCCGGGCTTATAAACACGGTCTATG
          ACCAGACATTCGTAACGTGTACATGTTTAGCCAACATCAGGCCGCGCGACCCGGTGGGCG
          CTCGGGTGGCCACGTGTCGCAGCTCACCGAGGAAAGATGGTTTGTTACCCATAGTGGTTA
          GCCGGCTATATGTGAAACGTGCTCATCCGAGAGTTTCACTGTTAGATAAATCCGCGAATG

          GAGCGGATGCCGGGGTACCTAGCCTCTTTACGATTCCCTGGCCTGCGTCATGTTGGAATT
          AAACGGTTGTCGGGGTTACTAGTCTCTTTACGATACCCTGGCCTGTGTCATGTTGGAATT
          GCACTGTTGTCGGGATCACACGTCTTTTATCGATAACCTTGACGGCGTCACGTTGGAACT
          GCAATGTTGGCTGAATTACTAGCCTCTTTCCGACAACCTGACCTGTGCCATATTGGAATC
          ATTCATTAGGGGGTTCACCCAACATCTCTTAAATTATCAAGTGAGCGTTATGTGAGCGGT
          ACGCCCATGTCTGGAGTGTTAGGATCCTGCTACTTACACAGCCGAAGACACGTGGGCCCA
          TCGTCTGCCAACACGCCATTGCCACCACACTGGTCATTTGTCTAATACACCGTTGGCTCT
          ACACGATAGGCCGTGTTGCTGCCAAGATCGTGGGGGTCACGTTCACTACATATTTGCTTG

          TCAAAGTCCTGGGCTCCGCCTCATAGTTGAATACCCGCCATACCGATAGGGCAAGGGAAG
          TCGAAATCCTGGGTCACGCCTCCGAGTTGAACGTCCGCCACTCCGATAGGACAAGGGATA
          TTAAGGTCCTGGGGTCTCCTTACGAGTTGGGTGTACGCCATACCTACACAGTAGGGGAGA
          TCAAAGACCTGGGTCCCGCCTCCGGATCGAATGTTCGCCATATCAACAGAAAACGGGGTA
          TTCGACCCACTGGGTCTCTACACTGGCCAGATGCTCTTTATGTGTTGTAATACAGGGATG
          AAATAACCGCCGGCACCGTGTATGAATCAAATCTCCTCCCTGCGCGCAGACACAAGCATG
          CACACGATGTCGGTATCCCGCTTAGTCCGTGTTTAATCTTTGCCCACATAGGAAGGCGAT
          CGTAGCTTGACCAGCCGTCGGGGAAGATGACAGTTATTAACGCACGAGTCGATGGGGTTT

          GCTCTAACGACTGACCTCCTGGAATAGCTGCTCTACGCGTATATGCGTCGTCTGAGACGT
          GTTCTAGCGACTGACCTTTAGGCATATTTGCTCCACGCGTAGACGCGTTGCCTGAGACGT
          GTGCAGGCGACTATCTTCAGTGAATGGCTGTGCCACGCATACATGCATTGTTAGGTACGA
          GCGCTAACGACTCACCTTAGGGAATAGCCGCACCAAGCAGAAACTCACCGCTCAGTACGT
          GTACCGGCACCTGATTGGAGCGTCTGTCTACCTCATATGACATCCAACAAATTAGCAAGC
          ATGCAGGCGACTGCTTTCGGAGCCCGGCAGTTTGATATATGTATGAGCCCAAGGGTATGA
          GCGCTCACGCCCCAGTTTAGGGTACTTATACTTATGTCAACACCACTCATTGAAGAAGCG
          GTACGACGAACTGATCCCGGCGCATGTTTCCCCGGAGCCCGTCGGAGTTATAGGGGAGTT

          AGTTGTGTCGTCCGGGGGCACTCAAGGGTGCCTCCAGGGTCTCTAGGCTCGGTAAGGCCT
          GGTTGTGTCGTCCGGGGTCATTTAAGGGTGCCCTCAGGGTCTCTAGGCTCGGTAAGGCCT
          GGTTGTGTTGTCCCGAGTCGCTTCAGGGTACGATCAAAGTCTCCAGAGCCAGTGAGGTTC
          GGTTGGGATATCCGTAGACGATAAGGGGTACGCTCAGAATCCATAGAGTCAGTAAAGTTT
          GCTCGTGATATCCGGGAAGGATAATGTGAATGCCTAGGACCCCCAAAACCCATCACGTAA
          ATTCGCACGGTCTGAAAGTAGGTGTGGGCGCGATGCGAACTACCAGACGCTAGATCGCAT
          GCTTCGGCTCACTCGTAGCATTCAGAAGCATGTTATAGATAAAGGAAATTGGTTAGGCTT
          ATGTATATACAGCAGTTGAGTCGCAAGGCACCTGATACCTTACGACAGGCGTTTTCACAA

          TAGTTTCTTCAGAGGGCCATCAGTAGCCATCTTCTGACCGTATTTCACATGGATGTAGAA
          TAATTCCCCCAGATGGCTATCGTTGGCTCTTTTCCGACCGCATCTCGCATGGAAGTAGAA
          CAGATTCACCAGAGTGTTAGCGGTAGCTTTCTACTGACCGCATATCATAAAGATGCAAAA
          GAGTTGCCCCACGGTGATACCGGTGGCTCTTTATTCATCGGCTATCTCATGCATGTAGAA
          CCACGGACCTAGAGGCCTAGGAAAGCCGCTCCGCCGAATGCTTATCACACCGCCGGTGAG
          TAAATGACTGAAAAACATAGGAGCTATCCTCCGTTGCTCTACCATATCTAGCACGAAGGG
          ATGTTAGCTGTAGTTCCAAGGGGCATATTATCTAGGGATCGACGCCTCCTTACGCGAGGG
          TTATTGCGCGTATTCGATGTGAGTGTAGCTCTTCGGGTTTACTTTCCCCTGGATGGATAA

          CAATTATTTCTGCATTTGATGAGGTCAACCCTGTGCTCTCCTACGGAGAGAACGTTCCCA
          CAATTATGTCTGTATTTGATGAGGTCAACCCTATGCTCACCTAGGGAGGGAACGTTCCCA
          CAATTAAAGCTGCGTTTGAGGTGGCCAACCCTGTACTCACCTGGGGGAAAAACGTTCCCG
          CAATTAACACAGCACTTGAAAAAGCCAACCCTGTTCCCACCTATGGGGAAGACGCTCCCG
          CAATTGTCATAGCCCTCATAGAAAGTAATCCTGTGCTACTCCGGGTAGGCGGCGGGATCT
          CAACACCCAAAGTATTTCAGTGGACCGAACTCGTTTTCAACCAGTTTGTGAGCCGTACTC
          TCCTTAACATATCCACAGTCAGGACCCTGATTGTTCATTCCTACTTGGAACTCGAAGCTG
          AGAAAAGGATAATGTCAGGTATTCTGTACCCCGTATCTGGTCCAGAGACCGTCGCATTCT

          GAATAGTCCCTAATGTAGCGCTCGCTTTCAGGAGAATTCTCGGGTCCCACCCGAAACCGT
          GCATAATACATGATGTAGCGCTCGCTTTCAGGAGAATGCTCAGGTCTCTCCCGGCATCGT
          GCATAAGCTCTGGCGTGGCGCTCACTCTCATGGGAATTCTCAAGTTTCCCCCGGCTCCGC
          TTAAAATCCCTGACGCGGCGCTTGCTTCCAGGAGAAACTACAGGTCCCCCCCGACCCCGC
          AAACAACCCCCCTCCCAGCACGACACCAATTTGAAGTTATTGGCTCCCCCAACCAGCCGT
          AAAACATCTCAGATCTAGGGCTACCCACAAGTGGGGCTATATGACTCTCCATCTTCCTGC
          GCAAGCCATTTGACCCCGCGACCAATCCCTACGTGGCTATCATGCTACTATGTCCCCTGC
          AAAAGAAACTTGAAGGTACGCTTAGTCTGCCATCCATCGATAGGTGGGCCTTTTCTAGCT

          ATAGCTCACTTAGATATCACGAACCATTTATTTAAGGTCGCGCCGTGACTGTGCTCTTAC
          ATAGCTCACCTCGATACCACGAACCTTTTAATTAAGGTTGCGCCGTGGCCGTGCTCTTAC
          ATAGCTCATCTTACTACCGTGAATCATTTGACTAAGGTCGTGCCGTAGCTACGCTCCTAT
          ATAGATTATTTGGCTAACAAGAACCGTTTAACTAAGGTCGTGCCGTAAACGTGTTCTTCT
          GAATCTGATCAGAGTAGCGCGGGCTCTCTACTTATAGTCATATTATATCCGGGTCAGATT
          ACAATTCACTGCACAGCCGAGCACTGTTCGGGGTAGGCCGAGCTCAAACTGAGCCAATTT
          ACTGTTCTCGAACATGTCTAAGCTCGTCTGTATAGCGCCGAGCATAGATCAAATCAACAC
          GACCCTAGTATTGTTGTCACAGGGCGTTCTCCAGCGGCTAGGTCTTAACTTGTTTATTAC

          TAATACGCGTATCTCGTTGATTTGCCAAATTACTGAGCGGGACCCGTTCGGGGCCTGCTG
          AAATATGCATAGCTTGTTGATTTGCCAAATTACTGATCAGGACTTGTTCGGGGCTTGTTA
          GTACCTTCCCAAGCTGCTGGATCGCGAAACTACTGAGCGCGACCTGCTTCGTGCTTGCGG
          AAACATGCATATTCCGTTGAAATGCGAAACTATTAAGGGCGTCTCGTCTTAAGCTTGTCG
          AAATTTATACGATGTGTCGTAGTAGGAAAAAAGTGCGTCCATCGCGTTTTGAATGTGAGG
          TGGTTTCTAGATTTGGCCCTGGCGCGAATGCAGGGTGTCTGAATCATCCTGAGGTGGCCG
          TGACCCACAGCCAACGTAGCAGCACGGCGTTAAGATGCGAGGCGCGTTTTGAGTGCGATA
          CGTTACAGCCGTAATGCAGCTGCACGTCACCTGTCTGTAAACAGTGCCGCGGTCACATCC

          ACGTCTAATGAAGGGAGAGGACAAGGACACCTACTCCACC
          ACACCTAATTAAGGGAGAGGACAAGGGCACTCACTTCACC
          ACACATTGTTCAGGCAGAGGACGAGGGCATCAGATTTACC
          ACACCTTGTTAAGGGAGAGGGTAAGGGCATCTATTTCGCC
          TCCCCTCCTGAACGATGACGGCAAGCAAGGTTACTCCCCC
          ACAGCAGTCCCAGGGTTAAATTGAAGGAAGGCACGTTCTT
          TATGATTGACAGCGGAGCAGACAGCGAAGATTATGGTGCC
          TATTGCAGCGTTAGTTAGAACACGCTAGAGACATTCTAAC

