 8 1000
t1        TGTCAGTGTGACAGTCGTTTGTTGCCTCAAGCTTCCTATGAACGCCCAGATCCATAACTC
t2        TGCCACTGGGAAAGTTGCTGACATCCCCAAGTTTCTTGCAAGTGTCCAAGTTGAAAAGTC
t3        CGGCATTGCTAAAGTGGTTAGTCGACCTACGCTGACTACTAATGCTCTGGTGGGGGTGTT
t4        GGCATCCCCTCTACTTGCCCACCTCCTGGGGGCGCTCTCAATTGTCTTGATTGATAAGTC
t5        TGTAATTGTTCAAATTGAAAGCCACCCTCGGGCCTCTGCTAGTGCTGGGGTTGAAATTAA
t6        CGGCTCTGCCCCAACAGCGGCCCTACTTCTGCATCCCATGGCCGCCGAGAGTCATACTAT
t7        TCCCACAACTCGAATTGCGCGCCAGTCCGAACTTCCCACGAGTACGCGGATCAACCCGCC
t8        TACCAGCGTCCATGTCCGAGCGTAGGCTGTATACGGAGCGTCCCGTTTAGCTGAAAAGGC

          GTCAAATTAGTGGAGGCGGTGCTACACACGTCGAAAAGAAACGCGGATAGTGACGCCGAT
          ATTAAACCAGCAGTAATAGTGCCGCAAAAATCGAATAGAGGTCCGGACTGTTCCGCCGAC
          ATCAAGCTAGTCGCGACGGTGATATGCCGATGAAAAGAATGCGGCAAGTGTTACGCCATC
          ACTAGGCCAGAAACGTAGGTTCAAAAAGCAATAAACAGACGCACCGATTGTTCCGCAGTC
          CTTCTTTAGTCAGCGGCGGAGCAAAATACCCTAGCGCCCGGCATCGCTTTCACATCCCCT
          GCTCACCTTGTCGTGACCATGTATTAAGGCATGATCTGCCCTCTCATATAGCTTCCCACT
          AATAAGCCTGTTTCGAAACTTCGATAACGATCCGTGGGGGGGTTCCTTTGCACCTTTGAC
          CGTACCAGCGTAGTGTTATGTCTACATAGTCCAGAGTGGGGAGGCGGTCGCATCTATTTC

          CAATAATCTAAGAAAAAAAAACCGCAGTCCTCCAACGAATCAGACCCCTCTCTGGTGGCC
          TACTACTTTAACAAGGAGTGAAAGTGGTCCTTCCACGAACGAGCCACCTGTCCAAGGACG
          GACAAGCCTCAGAAACCGAGAATGCGCCCTTCCGGTGAAAAGGACCTTTTCTTAATGCCG
          AACCGATGCGGGCGGAGAAGTACGTGCGCCCTCGAAATCACCGCCGCTTCCCTAATGAAA
          AGCCGACAATAGAACTATTTCTCAAAACTCTCCGGAGTACTATTCGCCCGTCTGGCACCC
          AAACCGAACGCAAAGCAGCGTGAGCGTGCCACCCGCCCCAAAACCGCTTTTATAGCCTTT
          TCCAGGCATAACAAACGATACGGCCAGACCAGCGGCAAGACACACACATTCGTGATCCCA
          TTCTTGCATCAGAGGGGATGCAGACGAGAGGGCGAGGAACTGTCCATCGCTATGCTGTGG

          AAGTTTATAGCCGGTTGATTCTTATGAAACGAATGTATAGCTGCTTGAACACCGCTCACC
          AAGCCAGTAGTCAATAGGTTCTAATGCCTTAGACGCTTTGTATCGTGAGCCTAATCGCTA
          GGGTAAGTAACTGGGTGATCTACGAGATTCAGCCCACTTGCGATAATAGCACAGCGTTCC
          GAACGCGCAGTTAGCTAATCCATGAGATCCAACCTCCCCGCGGATAGCGTTCCGGAGCCA
          GAGGTCCCAACCAGTCGCGTTCAGAGGCGGGGCGGCAGCGCAACAGTAGCCCGGCCCTTA
          GAGCCTGTAACTAGGTGATCCCTAAAACCCAACCGTCTCTCGAAACAAGGTCCGTAAGGA
          CAGCGGCGATTCAGCCGGACTCCTTGGCTACTCCTTAATCCGAAGAATGGGTGTTCCGAT
          GGACCTGGTCTAGGCTAACCGCATCATAATCTCTATAACTCTACGGATATATGATGGATG

          TCTTAGCAGGGCTGCTGCCCTTATTCTGTGGGCGACATGTGATTAGTCATAAACGCGTTC
          TGTCATCGGGGCTGCCTCTTGTGGCCTGTGGGGGTCATGCAACTTGTCATAGATTTCTTC
          CGTCGCCGCAACCGCACTCCGTTATTAGTGGGGATGATGTAGCTTGTGGAAGACGCCTGT
          CCTCGCTACGGGTGCTTCACAGGTTCGCCTGGCGCTCTGAAGTACGACATGAACCCTTCC
          GGACCACCCGAGTGGTCTCGGATATTGGAGGGGAGCACTTAGCGCTTAATGGATCTTCGC
          TGCGGTCTACAAGTTTTACCAGGCCCGATTGGCGTCAGGTTGCACAGTATCCATTTTTAT
          ACGCGTTACAAATGCTCTGCGGGCTGACGCACAACGACGTCGGATGCTCCGGACCTTCCC
          TGTCACATAAACTCGAGTAATAAGTCATAAGCGGTGAGATAATTAATAATAGACTTAGCT

          ATACGGGAGGCAGTCCGCCTCGTTTCGCATACCTTAAGCCAAGAGTGGATGGACGTGTGT
          GCACGAGAACTCTTTAGGGTCGCCCCATATGTTTAAAGCCAACGGCGCATTGAGGGCTAC
          GAGGGGGTAACTTTTAGTCTCGCCCTCAGTGCTCTGTGGCTAGAGACGACAGTAGAATGC
          GTAGAGGGGGTCTTCCGTCCTGTTCGTGCTGTTCCCAGCTACAGGTGGGTGCGAAGAGAA
          TACTGGGAGACATTATGCCTCACTCACTTCGGACTAAGTCGCCAACTCGTGTCAGGGATC
          GCTCAAAGATACATTAGCCCCCTTCTACTCGTTCTCCGGAACGAGCGGGTGGTTGCGTGT
          CCGGGTTAAATCCAAGATCTTCTCCTGATATTTACTAACTACGGCTGCGTAACCGGAGGT
          TCAACACTAGCCTTTCTCCTCGAATAGACTGATCTAATCCTCGCATGAGCAATGAATTAT

          CTGGCCTAAGTCGTACTATTGGCCAGGCGCCGTTCCAATATTTTCACCAGGAGTAGGGTA
          GTGTGCCAAACCCCGATTATGCCAACACTTCCTTCTTACATTCCCACGAAGCCCAGGGCT
          TTCGACTACGTGACAGGACTCCCAACCCTATGCCCCAGTTCCTTAGCCGGGCATAGGGTT
          TACGGGCATATAACAAGATCACCCTTAATTTTTTTCTATACACTAGCCAAGTACAGTGTG
          TTTGGTGGTGGATCGAAAGTACTTGCATAACACTCTTGCATATTGGCCGGAAACACGGTC
          CTAAGAAATTTGTCGAGCTACTATTCGTCACATCTTTTCACTTTGGTGAAGGATAGGCGA
          CCCGGCAGCACAACGGAAGCCTTCAGTCTCTACCTTCGGCGTATGTGCGAATGAAAGGGA
          TCAGGGAGAGTACAGGTACTATTTGTGTAAAAGAATTGTCCCATGGCCAGCATTCGGAAA

          GGAGTCCCGGCTCAGGCTGTACTATCAATGTGAATAGGCCCGATAGCGTTGACGCGCGGG
          GCTTTTGAATCTCACGCTGAGTGACCGATACGAATCGACTCGCTATCATACGCACGTGAG
          AGCTACGCGTTTAGCTCTGGACGAACAATATTGAATGACCAACATACGCACGCGAGTGCA
          GGTCTTGGATTGTAAGTCGGAGGCACGAATCCTTTTGCCAGCCGTATATAAGAAAACGCC
          GGTCCGAATTTGCCCGATGGCATTCTAGGATAAACTGGTTCGCAAGCACATGCCCGCGCT
          GCTTAGAGAACCACCACTGGGAGTACAAGTTAAGTACCCTGCTACGTATATTCGCGAGCT
          GGCACTAAGTTGACGGCAGGGAATACTCGTTACACTTCTCATTGAATCCTCCTCATCAGT
          GAGTTTAGCGTTACGATTGAGGAGTGGCATGGAACGAGATAAGCCTTGGTCAATGACGTA

          ACGTTCCCTCTGCTTTCTTGATTGCCGAGTGTACCGTACCCCCTAGCTCGAATGAAGCTA
          GGGTATTATTTGCACTTCCGATCATCGCTTGTACAACGCCCTCTGTTAAGAATGTGGCTG
          ACCTATATCCTGTTTTCTCGATCCGAACTTGTCTCATGCCCTAGGTTTAAAACACCCTTG
          GCGGAGTCCTGCTGCATTCCGTCTTCGCGCCCGCCCCGACGCCTACCCAGACGGTGACTA
          GTGCTCCAAGCGTTATTAATATCAACGCATGAGTTACGCCATTTACTTACATAGAGATTG
          GACTTTACATGGGTATGTTGTTGTCCTCGCAAACCGTGTCAATCAGCTAAATATCAGATG
          ACGGACTTGTGCTACTCGCGGCGTTCGTGCACACCATACAGGGTGTCTCTCAGGGGACCC
          CTAAATACTTGAAGTACTCCACTGCAGTGCAAATCCTCAATGTTCGCCCGGTCTGGATTA

          CATCTAAATCGCTCGCTAGACCCTTGAGCCTTAGCGCTTCACTCGATTAGCGGGTCGAAC
          CTTGGCCATTACCTTTTTAAGTTATAAGCCCTAGTGTCTATCCAAAGCAGGAGGCGGCAA
          TCCCCTTATTATCTACCTAGCCTCCAAGGTTTGGCGTACGATAGGAGCGGCACGTAAGAG
          GAGCCGTACCACGTGCACGTCTTCCTGGGGTTCTCGCTTGGATAAAGCGCCGGGGAGTAA
          CGTCCGCGCTTCCCGCTAAATATCCGGACGTGGTCGTTTAAACATAAGGGCGCTCGGCAT
          GGTATGAATAAAATTCTATGATCTAGAGATCTGCTGTTGGCTTATATGAAAGCGTGCTCG
          TGTACGAAGCTTTGTGAAAACACCCGGAATCGGTCATCCAACTATAGTAGTTGGCGCCGA
          ACTATTCGTTTAAGCCCAAAAGCGCAGGGGACGACGTAAGTGCTGTGCACTAGGTGATAG

          GAGTGAGTTTTGTTTAGCAAAGTTACTATTCCCGACGCGCGGAGTTCTCGATAGGTTTAC
          GAGTAAATGCTATTTATCAGAGCTGATATCACCGGGAAACAGAGCCATTGACAAAGTAGT
          GGGTGGTTTTTTTTCATCAGTTATGCTTTTTCCGGTGTGCAGAGTTCTTAGTAAACATTC
          GGGCGGACCCTATTTCTTGGCTCTACCACTTCCGGCAGGCAGAACCCCGTGCGAGGTCCC
          GGGGAAAGACTGTTTATTAAGGACATGATATCAGGTTGGCATAGTGTAAGTTGGGGACGT
          GATGCAGAATTATGTGGAAGAAATACGACTTCTGGTAGCCGGAATCTTCGACGGAGGCCG
          TGGGAGGGAGCATCCCGGGAAGATGTCGTTGGCCGAAATCAGAATCGATAGTAGACTCGA
          TTGATATGGTGTTCCACCGGAGTCATCGGCCCCGGTGGTCATTTTCCGTGGGGGTGGTGT

          TCGCATATTCGTTCTAAAATTTATGGCGCTGAGCGATGTAGCAAGGGCCCGACGGATGGA
          CTCCATACTTGCCTCAATGCCTTTGGCGCTGCGCGCGCGAACAGGACTTGGGAACAGGGG
          AAACACATGAGGTTTAAGGCGTTCAGCGCTGTGCGCTATAACGAAGACCCGGTATAGATC
          CAACGGGTATATTCCAACACCGCCTGCGTTGCGAGTGGTCATCAAGCCCCCGCACGCGGT
          CGATTCTCCCATTTCAATAGATGCAGCCCGTCGCGAGTCTACTGGCACCTCGTACAATAC
          ATACAAGGCCGAACTGACACCCACATTGTACTGAGCGTTAGCTGGGAGCTCGCCCAAGGT
          AAGATAAGACAGTTTGCCAGAACGGCTGTTGCGCGAGGTAAAACCAACTCGACCCCCGGT
          GATTACTGTTGTCTCGGTTCTCTATGTACAACGCCGGCTGCCTAAGATTAGTCAATGACC

          TCAGAAGGTTAGGACCATCATTAACACATACGCGGGGTCTTAACAACTGGCGCTTGCGTG
          TTCGCCAGGCAGGAGATATGCTTATGTATATGCGTGATGGTGGCGGAAGAAACGCGCGTG
          TCTGTCAGCCGGAAAATACATTACCCGACATATGAGGCGAAAATATAAAGCGACTGTCTG
          TCGGACGGCTAACAAGTGCACTACTGAATGTGAGAATCTAAAGCGAAACGTGGACGCTGG
          TTGGTTGGGTAGAGAATGTGCCCCTCAACACGCGGGGTTAGGGCGAAAAGTAGTTGCCTG
          TCTTCTGGAGATATAAAACCCTTCAGGCTATGTGAGTTGACGACAGCTCGCAGCCGCCTG
          CCGAGCTGACAGATTCCGCAACGTATAAAACGCGACGGGAACACGGAGTGCCGCTGCGAG
          TTAACAGCGAGGGTGTCAGCGCGTCTATCGAGTGAGTCAGATGCGGCAGCTAGATGCCGG

          GAGAACCAGATGCGCTCATGGATTTGGCTATACGGGTAAATCCGGCTTTAGGAACTGGGG
          TCTAACAAAATGCATTCACGGAAACGACTTACCGCGCTATTATGACCTCAGCAGCAGCGT
          ATACATGAAGCACGATAAAGGCGCTGCGTTAACGGACCTTTGTAACATCAGGTGTTAAGC
          AGTTGTAAAACTCGATCTGGAAAGAGAAGCTCCGGAAGGTTGGGGCATCTCGGGCCGAGC
          GTGTATTAGCTGCTACTGCAGTCGAGACTTAGCAGATGAATATGGCTTTCGGTACCATGT
          GTGCGTGAGACAGGCACGTTTAATGGATCTGTAGGCTTATCATAGAACAAAGGGTCATTG
          ATACCTACGTCAAGCCCCTGGAAGTAGCTTTATGGCTCATTTAACTGTGATGATTCCGTG
          ACGCGCGTAAGCGCCTCATTGATGGCGCTTCACGGTCACTCTTGGTACGAGAAAATTAGA

          AAAAAGCGTCGCAGCTTCCAAATTAAGCATCAAACAGGCACCGGAGAGTTTTACCCAGCG
          AAAGATGGCAGTGATTAACTAGTCGAGAGCCGAGCGGTTGGCGGAGAAACTTACCCGACA
          AGAGAGAACCGCTACCCTCCATACGAGCATTGGACGAGCGGCGAAGGACAATGCCGATTA
          GACGACCGGTGCCACCCCTTGGCCGAGAATTGGACGCCTGGAAACCAGCTTAACCTAATG
          GGAGGCGAATGATACCACATCTCCAAGCGCTGGATGGTTTGTGAAGGTGTACTCTACTTA
          ACGTTTTAGTGCCATTACTTGTCCGAATATCGGGTGGTCGGTGGAGGGCCAGTACCGTCT
          CAAGTTAATCCTTGGCGATCAACGCGACGAAGGATGGGTCGTGGAGAGCTTCGGCCCTGG
          GAGAACATAAGTCTCAACGTTAGTAACCGTTGAATAATCATCTCAACCTTATAGGACCAA

          TGCCGGCGCATTAGAACCGCACATTTTGCAACAGATCCGTACACGCCCGGTAGGTACTGC
          CACTGGTGAAGCCGAACCAAAGGCTTTGCAATTGATTTGCGCAGGTCCCGTAAGGAGTGC
          TGTCGGCGTGACAAAACTTCAGGCCTAGCAATGAATTCGCACAGCTTCGGTTAATAATGC
          TGTTAATTTAGAAATTCTACTGGATCTGGAACGGCATCGCGTGGGCACTCTACGTAGTAT
          CGTCATGGTGGGCTAATTGCGGAGACTATAACCTCTTAACTCTGGTACAGTAAGTACGGG
          CGCTAAAGTAAGATATTGGAGAATGTCACTACGGACCCACCAAGGCGTAATGAGCAGGGG
          CGAGGGCCAGATATACTTGTGGTAGTAGCGTTCAAGTCGACGTCGCACAGTAAATAAGGG
          CACTTGGCAGTTTCGCAGATCGTAAGGATGCGCAGTTTCCGTAGAGGGTGTGAGTTCGGA

          CCCGTGCCAAGTCGCGTATGGAACCAACACGGGACCGGAC
          ACCATGCCACACCGCGTATGCTACGCACAGGGCACGGAAC
          TCTGGGGCAAACCGCGCACGCAATAACCGATGGCTGAGAC
          GAAGAGCCGGGCCGTTCACAGACTCAGCCCGAGCCGAGGG
          TCCGGGTTGAATCATACGAAGGACCAACGAAGATAGGGTT
          TCCATGAAACGGTCAACATATCGCGAAGACCAGAGGGCTA
          TTCTGGTCAGGGCGTATACACTACTTGTATCCGAATATGG
          TCCGGTTTAGAATATGCATCGGGTTTACGCAGGCGTGGAA

