 8 1000
t1        CAGGGGTACTGTTGGCATTTAGAGTTTAGTGGGATGTTTCTCACCCCGAGGAGTGACCTT
t2        TTCAAATAACGTCGGTTTCCGTAGACTAATTGTGATAGTTCCCCCCGGAAGCATGATACT
t3        TGGGATTCTTAGCGGTGTTCGCACCGGTGACGTTTATTCACACCGTCCATACCAAAAACA
t4        TCGGAGTATCACCCGCGCCGGTGAATTTTGTGTGTATCTCTGTTGTGGGGACATAGCGTA
t5        TGAGTTGGCTGTCTATGAGCATTCTTTAAGCCTAGGGTACCTCTTCCGGGGAGCATCAGC
t6        TTGACCCAGTGAATTCGTAAATGACTTGAACTCGCAGCCAACCCCCGAGAGAGTTGCAGT
t7        GGAACATGCAGTTCATCTCACGGATCAAAGGGAGCTACCCGATTCGTTTGATGCAGAGCC
t8        TGGTCATGTGGATCTTGTATCAATTCAAAGTGAGTAACACGTTCCGGTTGTTACAGAGCG

          GTGCGGACCGAAGGTCTTGTCTCACCTGTGGTACCCAACAGCGACGAAGGGGACGGGCTC
          TCGAGCGCTGTGACGCGCGTATTGGCTGCGAAATCGTACAACGCCCAGAGGAACTGGTTC
          GTGCCGGCTTGAAGAAATATAGCTACTTCAGGACCATGGAACGCTCAAGGGCGTGGGCAA
          TCGCGCATCTTCGCGCATATTACCGTTCTAGGTGCACGCAATATTGGAGGAAGGAAACTG
          ATATGGATGCGTCTGAGGTTCCAGATGACATTACTCCCTAGTGCACAGCCGAGACCATTG
          ATATACATTCGCTGAGGGAATTGGGGTTCAGTTTTAGGAAAGATACCTTCACATCAATCT
          ACGTCCTTATCATAAATTGTTCCGAGTCCAGGACGGAGGGTAGCTATAAGACACAGACTG
          CCGCCCTTGTTACATATTACTACGCGTTCAGGACAGAGGGAAGCTATACCCCCCAGACCA

          CTGACACAGTAGTTCACTTACCACCACGCATTACGTAATAGGAGCGTAACACCGATTGAA
          TTAGTTCAGTGCCCCCCTCGTTTCGGCCGAGCAGGAGCTGGGACAGTAGCACTGATGGCT
          CCTATTCGGGATATGTCATACCGAGGCGTAGTAAATGCTCGGCCTATCGTACTTACGGAC
          TCAGTAATACTCGTCCTTTCTTGCAGTGTTGCAGAGGCTATGATGGTGGGGTTGTCGGCC
          CAAATTCTGCCCGTTTTGTGAATCAACGTTCCTAGCGGCAGGTTGGCTGCGCTGGCGAAT
          TGGAATTCATGCCCGTTGCAACCCAGCCCTCTCGAAATCAACTCTGTAGCATGGGCGACG
          GCCACGAATCGTCTTACATACCACAACGGAGGATATACTAGAACTGTGTCGCCGCCACAT
          ATAACATAACAGCATTCACACCTCTGAGGAGCAGGTGCTAGAGTCGGGCAACCGGCAAGC

          TGAAGTTTGCTACAGGGTACGTAAACGCTGCTCGGATTGCCTCTCCATCGATACTTGTAG
          CGATGAGGGCAAATAGAACAGTAGGCGACGCGGGAGACGTATTTTTGATGCCTCATGGAG
          TTGCGTGGGTTTTCGGGTTTCCAAGTGTCGCCGGGGTAATAGACACCCCGTTCCTTACTG
          GGAGGCTCACACGTTTCTACGGCGGCGTCGCAATAGTACCTGGACTAATGTTTCAATTTT
          GTAGATTGGCTTTTGTATATATCGGAGCAGCTGGATTGGAGCAGACAGAGTATTATAATG
          GTGTATAAGTGTCCCTATCTATCAACGTCGTATGAGTGGCGAATGAGTAATCCTATGCTT
          GGTCGCCGAAAACTTAAACTATTGCTGTTGGGCGTATAGCTTATTTTGCACCCCGAAAGA
          AGCTGCCAAGAACTTTGGACCGGGACACTGGGCGCGATAGTTACGTCGCATACAGGGAGA

          GACCTGACTGGTTTCAAGCGCCACCTCACCGAACTCGTGCAGCCTTACTGACTAAGTAGG
          CGTCTGAAACGTCCTAGACTGCCCCTCTCAACATCTCTACTGACCTACCTCAATGGTGGG
          GTCCCATATCGCCACACGCGTTATCAACGGACTTACAGGCTTACGTACTATTCCAGAAGA
          GGCCCTTGCGTTCCTTAGGATTAGCCCGCCAGATTGATGCATGCGTGATACGATTATTGC
          AATGCCGGGTCCGTGTGATGCTATCCCATTAAGCCCTCGACTACGACCCCAACCGGAGGG
          GGTGATAACACGATTTAGTATAGGCCACCACAATGAGACTACACGAGCTCCTCAACGGGG
          GGGTCAGCTACACTTAAGCATCTAGAGTTCATACGTACCAACGGGGGTTCCGCCCGAAAA
          GGGGCTGGTAACCCTTCACATCATATGCTCATGATTATATAAGCGGTTATATCCCGTGAA

          TGGCTGTTTGAGTCGCGAACTGAGTAAACCTGCTGGCCCAATGCTGACAAGCTAAAGAGA
          GGGTCGCTGTAATGGCGGGACGATTAACCAAGCTGGTTGGCTCAGAACCAGCTAGAGGAT
          GGACTGACATGACCTTCAGTCTATTTGCTCCGGCTATCCGAATCCCTTATCCTACAGGCC
          AGATCAACACAACCGTAAACTGAATAGTCAAGCGGATGTGTTATGCACGAGTTGGATAGC
          TGAGCATTGTGCGCACAGCCAGGATCGGTTTTGCAAGCTACTACAGTTAACTTTAGGGTA
          GGACTATCCTGTACCCGGCAAAAACAATTCCTCTGGGGCGTTATAGTGGTTTCTAGGGTT
          GGTCTAGCTTAGTTCGCAGGTGATTGAGCTTGCAGATCCGATGCGGACACTTAAGGACAT
          GGGTTAGCTCAAAACGCAGTTGTATATGCTCAACGAACTGCTGGGGGCACATTAGCATGT

          CCCTCGCGCATATCTGTAAACGTCCGTAGTTTGGCCTGCGCATAAAGCCGATTTTACGCA
          CATGCGGGTCTCTTCTCATATGGCCGTCATCAGTCTAGTTCACCGAATCGGCACCGCGAC
          CCTACAAGTTCGGTCTTTAGTGTTCTAGAACCGTTAACCACTCCAGATCGGCGTTACACT
          CCATCGAATGATATTTCGAGCCTCTGTAGGTCGCTGAACGTAGTGTGTCAATATCGTCGT
          AACCCAACCCCGGAGTTTGTCGATTGTAAGACGGTCCGTCGGATGGATAAATACTGGCGG
          TGCGCATTTCTGGAACATACCATGGACGAGCGGATCTATGGGGATTACAAGATCCGGGTC
          TTTAATTCCCAAACTGTGAAAGAAATCGTAGCAAACTTTGGGCCGCAATATCGGTGTATG
          TTTTCCCCCGCACTTATTGGAATTCTTGCTACTGACTCGGGGCCACATTAACGGCAACTA

          ATTCTTCATGACTTTGCTTAGCCATTTTGTTCTCCTTAGGACTCCGCAACGGCGTCGTTC
          CACTTACGTGCTGTCGCTCTCTCATACTCCTTTTTGTAAGACTCCGCCCCGGTGGCCCAA
          TCTCTCCGTAACCTGATACACAGGTAGTTCTTTAAAGGCGATCTCGCTACATTAACAGAA
          CATCATCGATTCTGAACGCCCCGTCTTAAGCACTCCTCTGAGCAAGTGGAGAATTTGCGC
          CCTCTAGCTACTATTGTCAGTTAAGGTTGAAATAATGTGGTTTCTCATTTGGCTGCCTGG
          GGCAATGAAAACCTATAACTTTAGAAGTGAGGTTACCTAACTTACGGCGCGCCTCCACGA
          TTCGATAGACCTCTAATATGCGCGCACGTGCTTCACGGGATCGAAGAAATGCTTAGAATA
          TCAGTCAGACCTCTTGTCTTCGGGGCTGTGCTTCAAGGAGGCAAGGGGATGCTCACATCA

          GCTTGAGGCTGCCTTCTGAGGCAATTCCGGATGGACACAAGCCCCGAATACGCGTAAAAT
          CCCTGGAGTTTTTCTCTAGAGCGCTAGTGGATTCTCCCAAACCCGGCATATATTTGAAAC
          TTCCGGCTCTAGATTCCGTTATATAAAAGTAACATCCCGAAACTAGTTCGCGCTGGTCAC
          CGGCGGCGGATTCTTTTGGGATACAAACGCGCCCTTTCTGTCACGACTCACAGTAATGTA
          ATTGAGGGTTGTAGCATCTACGATTCACGGCCAGATATCGATCTGGTGTAATGCAACGAT
          ATCGGGGGCGTGGATACCTATAGCGAACAGTCCACTCCCACCAGGGGTATCAGATGCGAC
          AATACGGGCAGACGTAAGAGCGAAGGAGCGCCCCAGACGAGAGGTTTGTTCCACAACGTG
          GAGCCGGGGACGTGTAAAAACTAGGAAAGGCTCTCCACGGAGGGGATGCTCAGCTACGCC

          GAAGTCCATAACCCAGAGAGCGTAGCGAGACGTGGTAAGGGAGTGGTTAGGTATTATCAC
          GGGGCGCTTTGTTCAAATGGTTAGGTGTGAAGTGGCCGCAGAGCGGTCAGAGATTGAGGT
          TAAGTCAGAAGCCTGGACCATAGACCCGTAATTCACTAGGCTATGTCTACAGCTTTCGGT
          TAAATAGCAGACCTGGACAATAGAACCAACGGTTGTTGAAGAGCCCCTGAGAATTCTTAC
          TGAGGACGCTCCATGGTGATTAACGCTAGCGGAGATCGTTGGGTACTTACGCTAACCCAC
          TTTGCTGACGTCCCAACATGCAGTTTTCTAGATGACCGCTGGGCTTGTAGGCCCGTTCGA
          CGAACGGACGATCACACTTTCGCCAGAAGATTTTGTTGTTCGGCGGGGCTGTTCTCAGTT
          CGGGTGAACAATCTCGACAGCCCTACAGGACTTTGGCATTGTGCGACGTAGTAGTTGATC

          AGCGGATGCGATATGTATGGCTTTAATACATTCATCGGACCCGCCAGCCATCTGCAGATA
          GGTAAATGATATGTGCCCAGGCATCACAAGCCGCTCAAATCTGTTTGACATTAGCGGGTA
          GCTGAGAGGTCCATACTTAGCAGTGATTTAGTGGCCCGGTTTGCAAGACGGTCTCATCTG
          GGTGGGTGATTCATGCTCGCCGCCGATAGCCTGCATAGGAATGTTAACCGATAACGCTTA
          ACCTGGCGACTTTTATATACCTCCGTAACCACATTATCAGCCTTTATCCGGCAGCTACGT
          ACTAAATGGTATTTATGCACTGTCACTAACCTTCTCGCGAACGATAATCGGCTAGCCCGA
          GGTGTATTAACTCCGAACCTAGAGATCGCTACACCGATGAATGCGGGCCAGCTTATACTA
          AGCCTATGAACCCCGAGTGCAGAAAACGCCCCACCACCAGGTGCCAGCTGGGTTTAAGCG

          GCTAAATCCGGTATCGTGTAAGGCTACTATGGCGGTAATCAGGTCTTAAGTTACCATGCC
          ACACAACCTGGTACATTCTAGCTCTACTAAAGCGAATACAGTTACCCAAGATGCCATTAC
          GCTACACGCGGACCCGAGAGGACAAAATGGCTTATCGCAAAGCACTAGTGGCGTTACAAA
          GTCACCGAGGCGATAATATGTTGGTGGCAAATGCACGGATAGCATTTAAGACGCTACTCC
          GGCACTACGATTTTCCTGCGGCGCAAGCAGACCAACAATACAGCTCCGAAACTAGTCTTG
          GATCGTAAGAATATCTCGCAGCGACAGTAAATCGAGAGCAGGGCACAGGGCACCTACAAA
          GAGCCCCAGGATAATCTATTATCCTTACTAATTGATCTGGAGCGTCTGAAGACTTCATTG
          TGGAACCAGTGTAGTTCGCCACACCAGCCAACAGTCCGTAAAGGTTTCAGGATTTCGTTG

          TCCTTTTTCCGGGTCGACGTCCAAAGCACACACATTTGGGTATACTAAGCTTGATGTAGT
          CAACCTTACGGGGTAAACGGCCAAAGTACGAACATTAGGGTGGACCAGGATCGATATCGC
          TTCAACCGCCCGAGTGGCGGACAGAATGTGATAATCCCGATGAGTCCAATAAGATTTCGA
          CACACACTCCAAAGTAGCGGTCAGTCAATTTGCGCATTGTCCACTCAGACAAGCGATCGC
          GCCTACTCCCGTGAGGGCGTCCTATTCGCCTGAATAGGATTCTGTAGGTCCCAATAGCGT
          GCGGTTCTTTATAGCGGTGAAGATCTCATGAGGTCGCGATTGCGGACGCAGTGAAATCGT
          ACTTTTCAATACGAGAACAGGATGTTCACCAAACTCGTAGTGCGCCTGTCACGGTCACGT
          TTCATTTAAATAGTGGGGAGGATGTCCATGAGACTAGAAACGTGCCCGTCAGGATGATCT

          ACCGCCTGGACGGGTTGGAAACAAGTTCTTGGTTTTAGTATTTTAGACAGGCTAGTCGGG
          TTCTCTAGGGCGAGCCGAGAACTTCTAATTGCTCCTAAGGGCTTTCACCAGCTAGACAGA
          TGTAATTATACGAGACTAAGTCTTATGACAGCGCTCAACAACTTAAATTAGTTAACCGCC
          CATGTAATAGCTTGGGACAAAAAGTTGTCCCGCCTTTATAGTGGCAGCAAGTCTAGAATT
          TTTGACACGCAAAAATTACTACGCGCACTTGCTCACTTCCATCGGGTTAAAACTGGCGAC
          CTCGGTTCGCCAAGACAGACCTCCGTGCTTTCTAAAAGTAAGCTGCTGTCGACTAATGGC
          CTTGCACATCCGAAGCACGACAAAACGTCCACATTAAATAGAGATTCCTGCGCTAGCCGA
          CTTGCGCAACCGAAGACAGACTGCGCATCTCTTGTAAGCAGGGTTTGCCGTGACAGCTGT

          TTTGGGTACAGGAACTCAAACACGCTCTCCTCTTGACGTTTGATTATACCGCGAATGCGC
          AGTGGGTACAGATAATCACGCGCGTGCAACTTCTACAGTATGATCGCACCGCGGGTCCGC
          GTTCGGTACAGGCCCTTGAGACCAGCCGTTTAAAGACGGATAGTTGTGCAGGCCTTGTGA
          GAGATACCCACGGCAAAAAATGTGCCTAAACCAGATCGGTGGATGGGACACCGAATGCGA
          TAAGCGCCGTCGGTTAAATGTGTAAAGAATCTGCAACGAAGAGGCGCGTACTACTCAGTT
          CGATTATGCTAGTGCGTTGATACGCTAGCTTCGTACGGGACTAGCGGGCTAGCTCCATGT
          GGTGTGTGCAGTACTGCCAATAATCCAGATGCGCCAAGGATAAGTAGTTAGGATAAATGG
          AGCCTATCACGTAAGGATGATATGTCAGAATCATAGAGATCAAGGAGGTAGGATATATAG

          GCCTAACCTAGCGTGTTTACTAATGAAACGTTTCTTCGCTCCATGACTTGGTTGGTAAAA
          GCATCGCCCTGCGCGTCAAGCTCTGAAGCACGGCGTTAACCTATGATTAGTCGTTAGAAG
          CTACAAAGTTCCACGTCGAGGCTGAATACAATAGTCAGACATTTCAGTCCGGCGACTATC
          GAGCAGGATCACGAAATAAGAGTCGGTACCTCACTTACCTTCACTACTAGGCTTAGAAAG
          CAAGCTAACCTCGTGAAAAATACTAAAATAACAACCATTATATGCCCGACATCACAACTA
          ACACATACCAGTAAGTAAGTAGCCGAGCCAGTTTTAAAACATACTCTTATATTCTTATAG
          ACTTTGGAACCAGTCATGACGCCGAACCAATCGTCTCTGTTCGATTAAAAGGTCTAGTAC
          GCTGTGAAACCAGTATCGTTATTAAACGTGTCGTCCAGGCCCGGTACTATCTGTTGGGAC

          CCCTTTTCACTCGGAGCACCCAAAATTTGTCGTCAGCATG
          CACCGACTATTCGGGACGCACAGACCGTGTAATCCGAAAA
          CTGTGCACATCCGGAACGCTCTAAACACCTGGCCTGCCTA
          ACATGACGAAGTGGAGTGTATTAAGTCTTTAACCCGCGAA
          CTCAATTTTGTACATGAGTGATCGGCTTAGGAATTATACT
          CCCCAATCAATTTGAGAACACGAAATTACTGGGTAGAGCG
          GATAGATTAAAGCGATCGCTTTCACCGAAAGTCGAATAAC
          TATATATCAAAGCGGTTGGTCTAACCGAAAGCCTAGATCC

