 8 1000
t1        CTGCGCTCCCTAGAATAAGTGCTCAGGTGCCAAACGGATGCAGTGAATACGAAAATCTAG
t2        CTGTGCCCCTATGAATAAGTGTTTAGGCGCCAAACGGACGCGGTGAATATGAAAATCTAG
t3        CGGGACGCTCCCGAACAAGTGAACAGGCGTCTAAGGGATGCGGCAAATGGGGAATCTCTG
t4        CTGCGCTGAAATGCACAAGTGTACTAGCGACAAAAGGCCGCAGCGAGTAGGAAGCTCCCT
t5        TTGTTACCGCGAGTACATGCGAAAATGGGCAAGGCGGCTGCCGTGAATACGAGAAATCGG
t6        TGCCGGCTGGGTACGTAAACGCAGAAGACTGGGAGGAGTGTCCCGAGTGAGCACTCCTGG
t7        CGGTGTCCCACGTCAGGAGTAGAATACCTCGTGGAAGGACTGGATTGAGGGACAGAAACG
t8        CGTATTTACAGCGCATATAGCCATTGTCCCGCGTAGAGTTTAAGACCCAAAATAGTGGTA

          AGTCGTCCGGCGGCTCTAATTATTGCCCTTAGGCGTGTGCCATAGGAGGTGACTTCGACA
          AGTCGTCCGGCGGCTCTAGCTATTGCCCTTAGGCGCGTGCTATAGGAGCTGACTCCGACA
          AGTTACTTGGCGATTCCAACAATAGACTTTCGGTGGGTGTTACGAGATATGGCTCCGGCT
          AGCTTTCTGCCTATTTCAATAACAGTACCTCGGCAGAGGTGATAAGGCCTGTATATTACA
          GGCCCTAAGAGGATTGTAATCACAGCTCATGGGGGGAAGTTGATGGGACTGAAATCGACG
          GGTTATCTAACGAGTCTACCTAGGGTCGCCCGCTGATGAGAGTTCGGGTTGTGTTTGACA
          AATTCGACAGCAAATCTGATTGCAGCATATCCTTAACAACTGACGGTATTGAGCCGGGTA
          TTGCTATTTATAACGCACTTTTAGGAGTGTTACACTTGAAGACGAGCAGAGCTCCATTTA

          TCCCGGCTTGCCCTGCACCACGACACTAATTGCGAGATCTGTAGGAACCTCGCGTGGTGG
          AATCGGTTTGACCTGCTCCTCGACACTAGTTGCAGGATCTGTAGGGACGTCGCGCGGTGG
          TACGAGAATAACCTGCAAGCCAACGCCCGATATGGTATCTCGAAGATCCTCGCATGCTGG
          AACGAGTATAAACCATGAACTACCGTCCGATTGGGAACCTCAAGTGCCCTCGCGCGGAAA
          GACAAGTAACACCTAAGAACTATCGCCAGCTCGGGTGTGTCTAGAGACTTCGCGTGGTAG
          TACTAGTGAGACTCGTAAAGCACTATCTGATCGTACTTCACTATGGCGCACGCGCGGTTG
          ATTAAGAACTGCTAACGGACTGACGCTTGTGGAGTCCCAGTCACGAGTCCTGAGCGCTAT
          CCAAGGCACTTTACCCTGACTCAAACCACAGAGACCCTTCCGACTGCTTATGAATACCTT

          GGGGCGCAGGGAGACCTTCACGTATGTCAGAGTGTCTCTCTCTTTCAAGAATGCGAGACG
          GGGGTGCAGGGAGACCTTCACGTGTGTCTAAGCGTTTCTTCCTTTCAAGGATGCGAGACG
          GGAGTCCAGACAAAATTTAGCATGTGCCAAGCTATGTCTTCTCCTCCTTGTAGTGAGATG
          AATGTGAAGGAGAAGTTTAACATGCGTCAAGGCACTACTTGACTACAGTGCAGCGAGATG
          CGGGAACGGGAGAAATGCCACAAGCGCCTAAGCGTAGCTCCGTTACTATGCAACGAACCT
          GGAGGGCAAGATTAGCCTAGTGGACAGTGGGATGCCTGCCGACAATCTAGCCAATCGCCG
          ATCGCGGTGGGGTACGCGGGTACTCGCCATGGCCTTTCATTCTCGCAGGGCTGTAGCCCC
          AGTGCGTTGGAGTTAGTGGTCGTCAACCAGCGCGCTAAGACTTTATATAACCCAGCCTTG

          ACGTTTAGCAGATGGCGAAAAATGGCGATCCACTTGTTCTATTCATAAACACGGTATTTT
          ACATATAGCAGATGGCGAAAAATGGCGATCCACTCGTTGTACTCATAAACACGGTATTTT
          ACATACCGCGCGGTGTAAGCAGTAGTGGACTCATCCAGCTACAAGCAAATACGGTTTTAT
          TAACGCCGGCGCCTGGGAACAGTGAGGTTGTCTCCTTGACAGACGCAACTGCGGCCTTCT
          AGATGCCGGAGATTCAGAAGAGCGGTGGTCCCCTCTTGCATAGCGAAAACATGACCTTTC
          TGATGCGGGGCAGAGGGAAATGTAATAACGACCTTTCGAAATACGAAAATGTGGTCGTAT
          GCGACTCGCATACCCTAAGGTCGAGTGACGAATACATGGTAACTAGTAGCGCGGCCGCGC
          GGATTCCAAGAGCAGGATGACGGGGTCCTGCTGCTTCAGGCTCCTTGGACAAGACTAATT

          CTGCTGTTTAAGTACACTCAATACCGCTAAGACCTCAAAGTCCCGGGTCAGATGTGTATG
          CTGCCGTTTAAGTATACTCAATACCGCTAAGACCTCAAAGTCATGGGTCAGATGTGTATG
          TCGCTATTTGAGTAGACACTATATAGCCAAGACCGTAGAGTGTTAAATAGGACGCATATA
          CTGTTGAACGAATACGGACTAAATAACTGTAATTGAAAAGTCCGGAGCAAGCGGCACCAA
          CCGTTGCCTAGGCACATACTGGACAAGAGTGACCGCAGAGTCCAGATCGACCTGAACCAG
          CTGTGAGTAATGTGCACATCGAACAGCTTCGATTGGGGTACTCACATCCGGACGCAGTAG
          CTTCCGAGTACATGTACCTCTAACCAATGCAACTCCAAGGTCCACACATCGACTCGACTG
          CTCCGAACGATGCAGATACTGACTTGCGATTGCTGTGATTAATCCACTTGTCAGAGCCGG

          AGTACTTAGTTAAGGGAGGGCCGAGAACAAGTCTACGGTTCGAGGATGTCCCCCAGGGTC
          AGTACTTAGTTAAGCAAGGGCCGAGAACAAGTTAACGGTTCGAGGATGTCGCCCAGGGTC
          AGAACTTCGATCACCGACGAGCGAGATAAAGTCCTTTGTGCAATCCCATAGACCACGGTT
          TGAACTTCGACTACCACTGGTTGCAACAAAATCACTGTCACAGGTGCGTAGTCCGAAAGT
          AGTACCCCAACCAACGATGGCCGCGATAGAGTCCTTGCAAAGAGTGCGTGACTCACAGTC
          ACCCTGATCACCAAGGGCGAGCGGGGTATGCGATTTCCTATGAGTCGATGATCAAAGGAG
          AGTGCTATGACTAGCCGAGGTCATGTAAATTGCTTTTTTTAGTGAAAGGCGAACAAAGCG
          GGGCTTGTGGCCTGGGTAAGCGGAGATAAGGTTCTTTTAGGACAGTGGACACTGGCAGTG

          TTTATTTCACTTCGGAATTCCCGGTGGTTAACCGTTTCCAATCCTTCGTGTAGTCAGTCG
          CCTAGTTCGCCTCGGAATTCCCGGTAGTTAAGCGTTTCCAATCCTTCGTGTAGACAGTCG
          TCCCTCTCGGGGCGAATTTTAAAGTTGTTATCTTTTTTAACTCTACCATATATAGGGTTG
          CTTTTATCTACGCAGAATCCGCGGAGGTCAACCAATTTCACGCAATAATGTATAGAGTCA
          TCTTCATCGTCCAAAAACCCAAGGCGGTTAACGTCTGACAAGTCTCCATGCGAAGAATTG
          TAGCTAGAGCCCAAAAAGTTATGACGTCTAGCCCCTCCGGGGACCCTCCTAATAAAGTAA
          CGTTCGCCGGTTCATAGCGCGGGACGCGTGTGGTCAATTCACCTACTGCACTGGCGGCAC
          AGTCGCCCGGACGACGTCCACCCGCAAATGGGGTATATTCGATCCACCCGGTCGGCATTC

          AGGTTGCCGCTCATGCTATCTGTCCCAGATTCAATTGCGTTGATGATTGGGGTTGCTGGA
          GGGTTGTCGTTCATGCTATCTGTCCCAGATTCGATTGCGTTGATACTTGGGGTTGCTGGC
          AAGACGTTGGCGATGCTAGCCGTTTCGAGTTTCAGCGCTTCCCTTTTCGGAGGTGCCGAA
          CGGTTGTCTATCGCACTAGATGACCAAAGATTGAATGATGGAGCGTTTAGGACTGTTAGA
          AGATAGTTTGTCATAATCGATGACGAAAGTTCAATTAACTTGTTTTAGGGTCATGCTAAA
          TGGCTATACATGCACAAGGGCGTCGGAGGTTTAAGTGAATTGATTTTAAGGGGGCCGTCA
          GGGTCCTATCCGCAGGGAGTCGAGTTGAAATAGGTGAACTGGATTCATGTGAGTCTAGTT
          AATTGCTGAACAGCCTCTGTCACCAAGTTCCCTTAATAGCTCTCCTTTAAACAGCTTCAC

          ACGTTTTCTCAAACGAGGGTGTGCCGATATCCGTAATATCGCTATTGGTACACGCTCCGA
          ACGTTTTCACCAACGAGGGTGTGCCGATATCCGTACTATCGCTATTGGCACACGCTCAGA
          ATGTCTGTTCAGTAGCGGACATGCCGATATCCAGGGTAATTCCATATGCACTGGCTCTAA
          AGGCATTTTGTGGGGTGCGAGCGTCGGGGTCTCTAATATCTCTGCTTGCCTATACTACCG
          CCGTCTGCCCAAGTGTAGGCGTGTCATTATTCTTAAGATTTCACTACGTGCCCCTCTCCG
          ATTAATACCTAGGTACGGGTGTACCACCATTTTGAGCAGTTGCACACGTACCTTCCGCTA
          TTTGCTATTCCTGAGGGAGCGTGTTTATCTTCTTAGTGTCACGGTTACCATTTATTATCA
          CGGATCGGTACTGTCTGGGAGAAAAAACTCTCGACGGACTTCTGCCGTAGCTCGATGCAG

          AATCGCAACGTTCCTTGGCCCGAGCCAAAGCCGAATGCTCCGCAAGCTAACGCCGTAGGA
          AATCGCAACGTTCCTTAGCCCGAGCCAGAGCCGAATGCTTCGTAAGTTAACGCCGTAGGA
          AATTGCCAGGTTGCGGGGCCCGTCCCAGAACGGATTGCCTAACATGCTTACGGCGTAGTC
          GGTAGCAGCGCTGCATGGCCCGCGTCGCTACTAGTTATTTTGCATGCCATCACTATAGGA
          TGACGCAACGTCGCACGGACCAAGACAGGATGGATTGACAAGCTTAATAACGCAGTTAGA
          GAGCGAATCAGTACATGGGGAGCGCTAGTCTCCGCCTTCGTCAAAGCTGCCGCCCGAAGA
          GGATGAGGTGCAGAACGGTGCAGGCTTATGCCGGCCACCCATTATTCTACTACTGTAACA
          AACCGTATCATAGCGACGCTGGGCACAACTCTTATTAATCTCCGTCTCGTGACAATCTTC

          ATATCATTCTGTGTCCCGGGAAAAAATCACCTGGTTTCCGTGCGTCGCGGAGGCAAGCAA
          ATACGATTCGGTGTCCCGGGAAAAAATCACCTGGAGTCCGTGCGTCGTGGAGACAAGGAA
          TGACTCTCCAGGAGCCTGGACAAAGATCACGTAGCTACCACAGGGTTGAGCGATAAAACA
          CTGTTTTTCAATCATCAAAAGAAATCTTACTTAGTTTCCATCCGACGGTGAGACGATGCG
          CTACCCAACAATTGCTCGGATGAATCTTTCCTGCCTACGGTTGGATGGGGAGTCTTCTAA
          TACCTTATTACGTGTCCAGATAGTGGTTTCCCGAGTCCGCTATAAAGGCGGGCTGAGAAG
          AAGGCTACCCAGTAATCAGACGCGACGTATTAGGTTCATAGGGGACTGGAAGGTGATTAA
          TTTCTTGGCAGATACGTAGATTCCAAGGAGATAGACTACCTGGAATCGATGCGTAGATGG

          ATTAGGGCATGCTTCCACATTCACCAGCCTACTCCAACTGTATTGCGTGAGGCCGCCTCA
          ATTAGGGCATGCTTCCACATTCACCAGCCTACTCCAATTGTTTTGCGTGAGGCCGCCACA
          CTAGAAGCATGCCGTCGACTTCACCAGCCTAACCAGATCGTTTCATGTAAGGCGGTCCAA
          ACGGGGACACGCTCGCGTGTAAATTACCTCATCCTAATTGTTATCCAGAAGCTACCCCTA
          GGTGAAGCGTACAGATGTAGTCACTAGATCTGTACAGTGGAACTACATAAGGTAGTTCCA
          AGCCGTGCCTTCATAGGCAGTAATTGGGCTAACCCGACGGCTTTCGTCGAGGCTGAACAA
          GTAGAGTCATGTCTATCGGTTCTGGTGCAACGTTTGCCTGATGCTGAAGATGTTGTTACA
          ATCATAGCCTGTAGAATGGTTTCCACGTTCCCACTCACTCCCTCGCGCTAAGGCGGTTTG

          CACTAGGTCCTCCATCCAGATGATATCAGGTGCATTCAAAGTAAATGGGGGAATTAAGTG
          CACTAGGTCCTCCATCCAGATAATATCGGGTGCATTCAAAGTAATTGGGGGAATTAAGTG
          CTGCAGGTCCCCCCAGAAGGCACCACTCGCTACATTTACTGGAAACGGTTGAATCGTTTG
          TGCCGGATCCCTCAACCAGGTGTTTTTTATTCCACTAAAATTAATTGGAGGTACTAATTG
          TACAAGGTATCTCTCAAGAGTGCCATTAAGGGTATCGACAGCAAATGGGTGAATTGTTCT
          CCCCCTGTATCCCGCAGGGGCAGTACTCGATGGTTTCATAGTCCGCAAGGACGTCATCTA
          CGGTGCGTTCCTGTCATGGATCCTCTTACACGCCTCGATACTGAGTGATGAGACGGACCC
          GTCAGCTTTTTTTATCCCCGCTCCCCCAATTGACTCTTCCAGATCAGGCGTATTTGATCC

          AGACTACAAAATGTATGACGTCCCTTTCCGCAAGAACAAATTTGATCGCGTGAACGTCCC
          AGACTACAAAATGTATGACGTCCATTTTCGCAAGTGCAAATTTGAACGCTTGAACGCCCC
          AAACCACAAAAAATGTAGGCCCCGGCTCTGCGAGCACAAGTTCGAACACCTGTATGCCCC
          TGACGGTGAAGTGTGAGCCATTCGTCTTCGCAGGCACCAGCCCGTAAAATTAGTTCTTCC
          AGTTCGCGGAACGTGGGTCATCTACTCGCGTACGCGCAAGCTTGTTTATTCGAACACTCT
          ACACCGCGTGCCACGCTCCCACAGCTTCCATACGTATAATCTCGAACACTTGGACGATAC
          GTACGGCTCATAATTACGCGACAGGTTCTTTACGTACGATTAAGGCTCGTTGAACTCTGT
          GATCGATGGCTTGTAGCCTTTTGGTTCACCGTTGGATTATCTTGGACGCTAAATTTAGAG

          TTCATTGCTGAGTAGAGGTGCGAAGATCGTCTGTCATGGGCCAGGCCCGGCCTCAACCGA
          TTCATTGCCGAGATGAGGTGCGAAGATCGTCTGTCATGGGCCAGGCACGACCTCAACCGA
          TGCACTGCATGGCGTTGGCGCGGAGGCTAGCAACCATGGTTTCGCAATGCCACTAGCTGA
          CACGCCGTAAGGGAGTAGTGCGAAGCTTAGCTGTCGTGCATTCGGAACGCCATTAACCGT
          TCTACTGTCAGATAGTGGCGTGCAGCTTCACCGTGATATGTTCAGAATCCTACTGCTCGA
          CTTCTTCTTCAGCGGATGTGAAATACCTGGCGACTGACCGTCATGTCTCTTCCCGTTAGG
          TCAGCCGTGGCGTAGTTGAGGACAGATAGCTAGTTGAAGGTCTTAGTTTACGCTCGCAGG
          CCTATCGCCGAGTGACATAGTGCCGACAAAAAAATAAACGCCAGGCGTCGGTTCGTATCG

          CATATTTGGAGGAGTAGACGCCAAGGGCATCTCGTGCTTA
          CATCTTTGGAAGAGTAGACGCCAAGAGCATCTAGTGCTTA
          CATGCGCGGTAGTTCATTTGTAGACGCCAAAATCGGCTCG
          CTTGTGATGTAGGTCAGCCGCTGCAGCTAAGTAGAGTTTG
          GCTACGTGGTAGATCAGACATCGGAGTAAAGTTGGGTTTA
          TGTGGAAAGCTCATCGGGCGTCGAAACCATGCCGAGACAA
          AGTATATGGTATCCAAATACATACTGATTCGTCGATTTAA
          TACGCTGCGGGATTCTCATATTCGATTCAGCCTGACGTCG

