 8 1000
t1        TGCGTAATGAGAGGCAGGCTTTCACGTTTTGATTGTACAAGTCAGCGAACTCCCTCAATG
t2        GGCGTAACGAGAGGAAGGCTTGTGCGTCTTGATTGTACTAGTCAGCGTACTCCCTCAAAA
t3        GACCCCATGTATCGCAGGCGCGCAGTCCTCACTAGCGCGGGATAGCGCCGTGGCTAGGTT
t4        GACCACATGTATCGCGGGCGCGTAGTTCTCACTAGCGCGGAATAGCACAGTGGCTAGGTT
t5        AGTCTCACGTATACAAGGCCTGTGACTTCGAAGGTCCCGAGTCTTCGATAAACGAGTCAA
t6        GGTCTCACGTATGGTAGACGTATAAATCACCTCGACCTGAGCCCTTACCACCCTGAGATC
t7        GGTCTCATATATTGAAGGATAGTACGATGGAACGCCATGAACCGTTACTGGCCGCGGATT
t8        GGTTTTTTATATTGAAAGGCAGTACGCTAGACTGCAATGAAACCTTGTTGTCAATAAATT

          TCGTACCAACTTCACCAGCTGAGAAGAATATGATACCGAGTAATCGTACCCACCTGGCAC
          TCGTACCAACTTCACCAGGTGAGAAGACTATGATGCCGAGTCATCGTACTCACCTGGCAC
          TTCGGCTGTAGCTAGTGAATCTGAAAGCCAAACACCCTCACTATTCATGCCCTTTGGTAC
          TTCCGCTGTAGCTTATAAACCTGAAGACCAGATACCCTCCCTGTTCATGTCCATTGGCAC
          GGTCGACACATCCGAATGATTTTACTTTTAGGTATTGAAGTCGACCGAATTTAGGAGTCT
          GAATGACTCAACTATTTAGCATGCTTCTTGACTAACACACACGTCAACATTTTCTTCTGT
          GTACTTGGTGCTCCACGGTTATGGTTCGAAGATGATCGAGCAGGAGGCCCTTCGAGGGAT
          GTACCTGATGCTCTATGGTCACAGTTCGGGGATAATCGAGCTTAAGGGCCCTCGAGCGAT

          ACTATTGGAGTTCGAGTAAGCTGCCCATCATCCTAGGTTGGACACCAGCACGGTAGCGAA
          ACTATTGGAGTCGGAGTAAGCTGCCCATCATTCTAGGTTGGGCACCAGTATAGCAGCGTA
          ATATCCTATGCTGTTACAGGGGTAACCTTGTGCATGATTCGGTAATCACGCGGGCTAGAT
          ATATCCTATGCTGTCACAGGGGTACCCCTGTGCATGATTCGGTAATCACGCGAGCTAGAT
          ACGACCTGCATCGAGGATATCGAAAATTTGATCCGTGCTAGATGGTCAAAAGGTGTGAAT
          CCAGATTGCGTCAGCGACAGAGTACCTCCGTTTTGTTTCGTTCGGAGATACGGCGTTGAC
          CCAGCTGGCGTAGAAAATTGGGTGCTTTCGCTGAGCGGCGGCCGAGAACGCGATGTTGCA
          ACAGATTGCGTTTGAAATAGGGTGCTCCCGCTGAGCGGTGACCGAGTACGGGGTATTGAA

          TTACTACACCAATCAACAATATTGTCGCAGCTACGTTATCAGGAAAGAAGGGGCGCGCTC
          TTACTACACAAATAAACAGTATTGCCGCAGCGACGTTACCAGAAAAGAAGGTGTGCGCCC
          TTGATGCTCATGGCGGGAAGAAAGATGTCACCAGCACGACTTATTGGGGAGACGGGGCGT
          TTGTTGCTCCTGGCGAGAAAAGAGATGTCACCAGCATGATTTATCAGGGAGACGCGGCGT
          ATCGCTCCGGAACAGCGAACATAAACATGACTTGGGTAGCTGCACAGCAAAGCCGCATAC
          CATCACCTGTAACGTAAAACTCCGTTACTATAAAGGCGACTCGACAGCGGGGCGGTTATA
          AGCAGATTCAGACAGATAATATAGCTGCTATCTCACGAACCCGAGGGGGAAATAGGTTTC
          AGCTGATCCAGACAGGTAATATCGCTGTTACTTCACGAACCCGAAGGGGAAGTAGGTTCC

          GTATAGTCAATAAACGCCGTTATCTTCAAACATGTATCGCCCCCTTGTGAATCTCAGTTC
          GTATAGTCAATAAACGCCGTCATCTTCAAACATGTATCGCCCCCTTGAGAATCTCAGTTC
          CCCGCCCTGCTTCATGTAATGGTGCAGGTGCGTCAGACGAACCACCGTGAGCCAATGTTG
          ATCGGCTTGCCTCGTGTAAAGGTGGAAATGTGTCAGACGAACCACCGTGAACTAATGTTG
          TTAACGTAGCTAAGCATAATCCTGGACTCTTCGGGGTCGCACAACCGCGGCTCCAGGCCG
          TCACGGTCGACATGTGATTCTTTATAAGACTGCGGTTTGATCGATTACGATTTCAGGACG
          TAGCAAACGCTAAGTAGAGTCCCACCTGAATGGGATTTCCGTCATTGAGATATCAAATCC
          CAACAGACGCAAAGTAGAGTTCCACTCGAACCGGAATTTCGTCAGTGAGATAGTAATTCC

          AGCATCTACCGTTTTGGCAATGTTAAGAGCTGCTCTATAGGCTGCGCTGAGATAGCGCTA
          AGCAACTACCGTCTTGGCAATGTTAAGAGCTGCTCTGTAAGCTGTGCCGAGGTAGCGCTA
          TCTTACCTCCACCGCGTCAGTACCGTGACTAACCATGTGTGGCCCGGACAAGTCTTCGGC
          TGTTACCCCTACCGCTCCAGTACCGTGACTAACCACGAGTAGCCCAGACAAGTCTTTGGC
          GTGATCCGTACCCCCACACCCTCGAGTTATTAGTATGTCAGCGGCGTCACAGTATCGTTG
          AGATCCCGTAGCTTTGAATTCGACGTATAACATAACCCAAGATGTAGGGCGGTACCACTC
          CGTTACTACGGCCCTTTTGTGGCCTGTCTCCCCAGTAGATACTAGCTCATAGTAATGTTT
          CGTCACTATGGCTCTATTGTGGCCTGTCTCCCTAATCGATAATGGCTCATAGCTATGTTT

          CAATCCCTTGCGTGCGTAGTAAAGTATCACCCCTAGATCCCAACACGTATCCGTTTATCA
          CAATCCCTCGTGCGCGTTGTAGAGGATCATCCCTAGATCCCAACACGTATCCGTTTATCA
          TCGTCTGTGCTAAGCGCGTATACCGGTAATCAGTAAAAGCTAATAAGTATGGCTCCAAAT
          TCGTTCGCGCTAAGCGCGTACACTGGTAAACAGTAAAAGCTAATTCGCATGTCACCAAGT
          CGTATTGATGCAAAGTAGATCACGAACGTTTGCGACCGCATTCTCTGAACTGGGCCGATG
          CGAGACGACATACGGAAATAAATTAATGCTCAACGTTGACTTTTCTATATAGGGCTCAGA
          GAGTTTGCCACAAGGACGAACGTTTGCCCTCAGTCCAATATGGCCTGGACACGTCGGGGG
          AAGCTTGCTATACGGACGACCGTTCGCCCTTAGGCCTTTATGAACTGGGCATTTTTGGGG

          CCAGCTATTTCAAGGTTTATGAAATATACACCAAATCCAACACTTCAGAACTATGGCCCG
          CCAACTATTTAAGGGTTTATGAAATACACACCAAAGCCAACACTTCAGAACTATAGCCCG
          ACTCTCTAACGAAAAAGTGTGGGAAACCTGACTACAGGAGTAAATGAGGCGAACTAATTT
          ACTCTCTAACGAAGATGTGGGGGCAGCCTCACCACATGAGTAAATGATGCGAACAAAGTT
          TCTCGAGTCGGTGGCTTGGTAGAACGTAGATCAAGCAGGCCGTAATAAAGGTGCCGTAAT
          CTGTAGATAAAGAGCCAGGCCGGGGATTATCCAGATCTGGTTATGTGGGGCAGGCCCATC
          CTACAGATAAGATCCCAGCCATGTAAAGGTCTCTACCCACTGCACCAAAGCTGCCGGATC
          CTTCACATAAGACCCCAGACATGTAATGGCCTTTACCCATTGCACTAAGGTCGCTGGACC

          CAGTCATGGGAGTGCCGAGCCCACACGCGACATAACGAGGACTCTACGCTTTGGGGATTC
          CAGTCATGGGAGTGCCGAGCCCACACGGGACATAACGAGGACTCTACGCTTTGGGGATTC
          TCACCGAATGCGGGTCGAAGCCCCGGTAGTCTATCCGTAAGTACCATGCGTTGATACCAA
          TCACCGAATGCAGGTCGTGGCCCCGGTAGTTTATCCGTAAGTACCATGCGTAGATATCAA
          GTTCCGGACGAGAACGGGACTCTTGTAGGGTACGCCGTGGGAACCGCATATATAAACCGA
          GTAACGGCTGAGAACGGCGATTTTACTGCTAATCCAGGTAGTAATGTGACAGGGACTCAT
          CTTCCGGGCAATCACGGCACCATCGTTGGCCAACGTAGTAGCTCTCCCCCAAAAGCTGTA
          CTGCCGGGTAACCACAGTAAGAACGTCAACGACCACAGTAGCTATCCGCGCAAAGCTGAA

          ATCGAGTGGTTGAGCGTCGTGTTCAGCCTCGACGCGAAGGTGGGATATGTAATCAGTGAT
          GTCAAGTGGTTAAGTGTCGTGCTCAGCCTCGACGCGAAGGTGGGATACGTGATCAATGAT
          GCTTTGATGTTCGGTACATGCGTCGTTGCAAGCATACAGTTAGGCTAAAGCTTTAAATGT
          GCTATGATGTTCGGCACATGCGCCGTTGCAAGCATACAGTTAGGCTAAAGCTCCAAATGT
          AGTCGCCGAGCGCAGAGGTATACTTCAGTCAAGGTGCGACTGAACTTGGCTGCCCGAGAC
          ATCAGTAGGTAATTCTCGAGAGTCAGAGTTGGTAGGTAAGCCAGATGTGACACCCAAACT
          GGATGTACATGAGACTTTGGAGCCATGTTTGATACGGAACAGGGCTATAAGATTTACGCC
          GGGTGTACATGGGACATTGGAGCTACGGTTGATTCGTACAAGGGCTATGCGGTTTGCGCC

          GCTATCGCACCTCGTCAACTCACTAGCGATTTCCCCTGCTGTCGCTAAGGCAGGAGAATA
          GCTATCGCACCTCGTAAAATCATTAGCGATCTCCCCTGTTCTCGTTAAGGCACGAGTATA
          ATGGGACTACATGATCGCCACGACAAATCCAGACCACGTCCCTATTTAGCTTGGACCGCT
          ATGGGACTACATGAACGTCACGACGAATCCAGACCACATCCTTATCTAACTCGGACCGCT
          CTACGGCCCCACATCAGATCAACCGGCCTCCGATCTCTATCTTATGCCAGTACGAATACC
          ATTTGCATTGACTATTAATGGGGTGGTGTGTGAAATCGGGTCTATCAAAATTTCGATAGA
          CGAAGACCCCACCTCTCATACGAAGACAACTGTCTCACTTTTCTCTCAAGTACTGACGAA
          CGAAGACCCCGCCGCTCATACGATGACAAAGGCCTCACCTGTTTCTCAGGTACTGACTAA

          GTGGGAAACGGTTAGTCACTAGAAATAAACTCATAAGAATAACGCCTCCTCTCACAGCGC
          TTGGGTAACGGTTAGTCACTAGACATAAACTTACAAGAATAACGCCCTCTCTCACAGCGC
          GGTGAGAGTTCACCCCTAAATTCTGCTTGTTGGCGGTAAGTATGTTAACCTCTTTGACCT
          GGTGAGAGCTCACCTCTAAATTCTGCTTGTTGGCGGTAAGTATGTTACCTTCTTCGACCT
          GGTATAGGCACGCCACTGCGCGCTTTCTAACGAGGTACAGTCTAGTGATTGCTGTAACGC
          AACATGCCCGTGCAACCAAGTGTCTTTTGTCGATGTACGGTAACACTAGCCATCCAGCGC
          GCCAGAGCCATGTCATTTAGCGGTATTCGTAGACGTTCAATTCGCTTGCACTCTTACCGT
          GCTAGAGCTATGTCGTTTAGCGGTATTCAAAGAACTCCAATTCGGTTGCACTCCTAGCCC

          CGACTCGGCGTATGAGGATCATTAGACCTATTGCGTGCGGACCCACCAAGACGCGTGGCA
          CAACTCGTCGTGTGAAGATCATTAAACCTATTGCGTGCGGTCGTACCAAGACGCGAGGCA
          TAATTAGTCATGCGCAACTCGGCCGTGCGGAACCGCGAGGTTTAGATGCCGCACAGACAG
          TAGTTAGTTAGGTGCAACTTGGCCGTGCGGAACCGCAAGGTTTAGATGTCGCACAGGCAG
          CTTATAATTACCAGGCGTGTGGGTCGCTCCTGTTACTAGGTTTTTAGTTAAATATGGCAT
          ATGGAGGCTATCTGCCACGAGGTCGAGCTCTGTCGTGGAGTACTCACGATACCCTGGCAC
          GTTATTATCCATAGATATGCGATTCACTCACTGTAGTCTATCCCCGAACCACCAAGGCCG
          GTTATTTTCCACAGATATGTGATTCGCTCACCGTAGTTTGTCCTCGGACTACCGGGGCAG

          CCTCAGCGACAGACCCCTTTTAATCTCTCTGACCTGACTCGTCGTAAGTTTGAATCTTAG
          CCTCAGCGGAAGACTCCTTTTAATCTCTCTGGCTTGACTTGTCGTAAGTTTGAATTTTAG
          AACAAGAGCCGGGATTCACTCAGTCACTCTATTTACACCCGCCTATAGTTTGGATCGGAG
          AACAATAGCCAGGATTCATTTAGTCACTTTATTTAGTCCCGCCTACAGTTTGGATCGGAG
          ACGGCAAAATCACGATTACCCGGTTGTTCTGGTTTGTTCTACCAGCTGATAGGAACACTT
          AACACCAGTTTTCACCCAGCTACAGGTTCTGGTCTGATCAACCTAAGAGCACAGTCGCGA
          CGTGCAGTTCTAGGCGTATCTATTCGCCATAGTTTTATTTGTCAGAAGCATTGGACGTTC
          CGGGCAGTACTAGGTGAATCTATTCGCCTCATTTTCATTCGTTAGAGGTCATGGACGTTT

          ATGCAGCCTGGGGAGCGTTAATACTATGGGAACTCCTTGCACGTGGCCAGCTCTCAACAC
          TCGTAGTCTGGGGAGCGTTAATACAAAGGTAACACACTGCACGTGGCCATCTCTCAACAC
          ATCAGGATAACTCAGCCCCAGCGCAATTGTTTTGACTTTCCCATACACGCCTCTTACACG
          ATCAGGATAACTCAGCCGTAGCACAATTGCTTTGACTTCCCCATACACGCCTCTTGCACG
          AAAAGACCGGATGAATCAGGGTCGGCAGGGTGTAGCCAGCTTAGAACCGACCACCATACG
          CCGTCACTCGTCGATCTCTTCCCTACCGATTCGGACCCACTTGGGGTCGGCCAACGCGCG
          CGGAGGGCGAAAGAACCGGTGATTCGTCGGCGTGGGTCGAGTAGAGCCGGCTACAGCCAG
          CGGAGGACGAAAGAACCGGTGATTCCTCGGGGCGAGTCGGGTACAGCCAACTGCAGCAAG

          CGCTATGAGAGTGCAACATATGTCCATAGCTAAACATGAAGACGTACAAACTGCGGAGCC
          CGCTATTAAAGTGCAACATCTGTCCAGGGCTAAACATGACGACGTACAAACTGCGGAGCT
          TATGGTCTAGGTTGGGTGTCTACGCAGCGACGTCTCTGGCACCTCCCTTCCTAGGAAACC
          TATGGTTTAGATTGGGTGTCTACGTAGCATTGTCTCTGGCACCTCTCTACCTAGGTAACC
          TTCGTAAGACGTATGGCGCCCTACGGCGGCTGTTTCTGCTGATTGACAGCCCGCCTCGTA
          CCCGAGTCCTGTCCAATAGCTATTGACTGTTCGCGTCCGCGGCGGGCAGTCATACGCGCC
          TGAGGGTACTGTTAGCCGTCTGGAAACTGTTCTCGTCCACTACCCGTCACCCGTTGGATT
          TGAGGATACTGTTTGCCGGACATTGACTGTTCCCGCACACTACCTGACGCCCGAGGGACT

          AGTACGCCCAAACTCTCATTTCCTGTTCATGTGGCTGCGA
          TGTACGCCTAAATTCTCATTTTCTGTTCATGTGGCTGCGA
          CGTACATCAGACCTCCGAATTCCAAAACAAAGGCCCATGT
          CGTGTATCAGACCTCAGAACACAAGAACAAGGACTCACGT
          TATAGGCGCGATGGATTGGTTGTCGGGACGAGGTAAGAAC
          GATCGGTCAGGATCGTAAACTGTAGACCCCACGATTGAAC
          TTCTGACCTGGCCGGCATAGAACTCCGTGCGTGGCGACAG
          TTCTGACCTGGCCCACGTAGAATTCCGTTCGTGGCGCCAA

