 8 1000
t1        AACGTTACGATTGACCGATGGACCTAATGGAGTGGAGACCGAGGGGCCTGAGGCGATTCA
t2        AGCGTTTCCATTGATCGACGAACCGGATGGAGTGGAAACCGAGGAGCCTGGGCTGATTAA
t3        AGCCTAGTCGATAACCATAGGATCGAAAGATGTGGTCTCTGGGGAGCATAGGCCGAATGT
t4        AACCTGGTCGCTGTCTGAAGAATTGCTTGTGATGGAATTTGCGGAGTTTTAACAACCTAA
t5        CGCCCGTCCGGCACACGAAGAACCGAAAGGAGTCGAATTAGACGCGCTAGGGCAAACTAG
t6        CGCATGCCCCTTAACAGCATGAGTAATTCATTTATACCCAGGCAAGCGAGGACCACTTAG
t7        CACATGACGGCGCGATGTCCAGTGACTTGGAGCGCCCATTCACCCCTTACGCCCTAAGGC
t8        CGCGTGGACGTTTGCTGGTTTCCCCAGATAGATGATATTTGACTTATCTGTCTACTATAA

          GATTTGGAATATTCCAAGAGGTCGAATCTGGGAGAACTCGAGATGTACCCAATCGGCACA
          GATTTGGAGCAATCTAAGAGGCCGGACCTGGGCGAACCGGTGATGCAGCAAATGGGCACA
          GACGCGGAGTGAACTAAACAGGTCCGTCTGAGCGAACTAGCACTTCCCTTACTAAGTCTG
          GATACTGAATAACCTAAAAACCCGAGTTTGAACGACCTCGCAAAGCGCTCGGCGAGGCTA
          GATTTGCAGTATACTGCAAAACTGAGTCTGGATGGCTTCATAATCCCCTTAGCGGAGCCA
          AAATTTCGAAACCGTTGCAAGCTTTATCTGCACAGCTCCATGACGTGCCGGACCGAGACC
          GCGCCCGAAGGATCCAGCAATCCCATTACGCTGGTACCTCTGATGACCCAAATGCTGCTC
          AACGATAGGGTCGCCTCCATAACGCGGTAAATTATACATTAGCTTCTTCCAGCGGCTACG

          AGTCACTAACGAAAGCCATATAGCTCTTGTGTGATTGTGTCCGTGGTGCTAGTGAATAGA
          TGCCACCGACGAAAGCCATACTGCCCTTGTGTGTATGTGTCCGTTTCGCTAATGAATAAA
          AGCCACCAAGGTGGGGAACATTGTTCCCATATCAAGGCGTCTGCCTCGCTGGTGGCAATG
          ATCCACCATCGTAAAAAACATTGTTCCCAGGTGAATGTGTCCACGTCGCTGGGGAGCGTA
          AACGGCCATCTCGAACTATATCACCCTAATGTGAACGGATGTAAGTCATTTGCGCGTGTA
          CGGCTTCAAAACGGCTCGTGCTGTTCTAACAACGACATCAAGTTCTTGCCCACAGCGTAT
          AGGATCGTGCCTGTCTCACGTATTGGGGAGACACATACCCGACCATGGACAAAGTTCCTA
          AACCGCAATTCGGTCGAGAACTGTCAAGTCCCACATACCCAACTTCGCCAAGTGGCAAAA

          TTTCCGCATGGTGGATAACCGCAGCACATACCCTGGGTAGACGCCAGCATGATCATCGGC
          TTTGCGCTTGGTGGACTGCACCGGTACATACCCTGTATGGGCGACGGTATTGTCATCGGT
          ACCACATAAAGCGGAAAAGCGCTGCAAATTTCCCGTAGTGGGGCCAGCACTGCTATTGGT
          ACCACACTCGGCAGGAGAACCCTACACATTTCTTGCGACGCTGCCAATGATATAATCGGT
          TCCACCTACGGTTTAATATGGAAGGTATCTCTGACTGGCAACCTACGTGAAGCCATTATT
          CACTTGGACCTCACCGCCAGGATCAGATTTTACCGCAGCGTAAGTGGTTCAACAAGTTGT
          CCTAAAGGCAACACTAATTAAACTGCTTCGTCTAGCCAGTGTAAAACAAGCGATGTAGTC
          TGTTAGGAATTTACAACCACAACGGTTGGCGTTAGGCGGTCTTAGATTCCAGGCACTGCG

          AGGAAGACGTAGGCTACCCAGGATTCGAATTGGGCAATTACCTTCCATTCTAGCTTTCGT
          ACGAAGGCGTTGGCTATCCTAAATTCGAATTGGGCCACTACCTTCTATTCCAGCTTTCGT
          ACAGGGGTGCTGGCGACCCAAAGGTAATCTTGGGCAATTGCCGTGTCCACCGGCCTTTGT
          ACGGTACCGCCCGGAACCCTAATGCGGATTTGGACAATTACGTTCATCACCGGGTCTTGT
          TCGGATGTACTATACATCTGGGGGTGCAATCAGGTAATTACCTTACCCCGCGGATTTAGT
          CTGGTGGAATAATACTACCCGTAGTAGCGGACTGTACACGCGTCCCACGTCGGCGTAGGT
          TTTGCGTCGTATTTAATCATAGAGTACTGCGGGTTACGTGCCCGACGCCGCGCAATCACT
          GCTGCGAGAGATCCCCCCTCTGTCTTAGGATTGCCCTTTATATCATAACACGAAGCAGAG

          GGGCTTCTCGGAAGAAGTGGCATGATGTGTCAGCTGTATGAGGTGGATAGGGCCTCGAGT
          GAGTTTTTCGGAGGGGGTAATGTGATGTGTCAGCTGTATAAGCTGGATAGGACCTCGAGG
          TGGATTTTCAGGAGTAGCGGTGTTACTTGCTCGTTGTGTATGTCATGTAGGCACTTCCGT
          TGGTATCATGTAGTACGCAGCGTAATCTGTGTGCTGTATTGGTTGGTCAGGAATTGACGT
          TCTCATTGGGCAGTGGGTCGCACGAGTCGTGAGACACATAGGACTGGTAGAAACCAGTAC
          GCGCGTAGAGATGTGGGTACCGAACCCCATCCTTAATGCGCGTGAGGCAGCAGCCGTTGA
          TTGAGTACTCCACCCGGCACGCTGATTGTAAGACGCAACTAGCCGGATGGCAGACTAAGT
          GTGGAAATGAAACTCAATCGTCAAGTACGGGCATCTCCCCAGACTAGTCAACGGTTGTCA

          ACAAAATTATCCTTATTTTATCCAAAGAACGCCAGTCCTGGTTTGTGCAGATGATTTCGG
          ATAACATTCTTTCAGTATTATTCAATGAACGCAAGGCTTGGGTTGTGTAGTTGGTTTCGG
          ACAGCCTCCTGCCAATATTATCCGAATAAGGCGTGACCATCTTTGTACGAACGACCTCGA
          GCCACATCAGGCCCGTCGCACCCTATCCACGTGAGGCTTACTCTGTGCAAAAGAGCACAG
          ATTACTTGGCGCGAATCTAACCTGACTACAGCAAGGTCAAATCAATCCAACTGGCCTCAA
          ACAATGGCGCGCAGGGTTTGCTGATTCGGATTTAGGTCTCCATTAAGACATCGCGTCTGA
          ATGATGATACGTTTGTATTTTGTGTTTGTAGGGGGGCTAGGGTTAAACCAACAACGCCGA
          CTTTTACCGTGCTTACATCAACCAAGGGGTGCCCGATCCGTTCTCTACAGTTAACGATAA

          ATTTCCTGACATCAACTCGTCGCTAGGCGATCCGTCGCCCTATTTCCGAAGTATCTGAAT
          AATTCCTGGCGCTGACCCGTCCCCGGGCATTCCGTTGCCCTGTTTACGAAGTATCTGATC
          ATTCCCTCCTGCTGAGTCCTCGTTACTCAGATCGTCGCATTGATCTAGAAGTTTCAACAC
          GTGCTATCATGTTGTGTCTTTCTCTCGCTGGCCTACGTCGTGTCTTCGGAGCGACTGGAC
          GTTCCAACATTCTGCACCTTTGTCGCGTGAATTGACGTATTGTGACCGAAGCATCCAACC
          ATTTCACTTTGCCGGACCCGCCTATACCGAGACGGGTTACCGGGGGTAGGAGAACAGTTT
          AATCCCATCATACGAAACTCCATGTAATATGTAAAACTAAAAGTATTGCAGGGCCAACAC
          ACCAATGGAGAGCTGGAAATCTTGAAAGGAATCGAGACCATTATGCTGCGGACAAGAAGA

          CGTAGTTTGGCAATTCCGCGGATACAATTCCAAACGTCCGACGTCATCGACACAGCAGTA
          CGTTCTTTGGCATGCTATCAAATACAACACCATACGATAGACGTCGCTGATACAGACGCA
          TGTTACACGGCACAGACGTAATTACGATGCCATACGTGATAAGACGCCGTTACAGAAGCC
          CGTAGTATAGCATTTTTACAAGTATTATATCATAGGTTACGGGACACGGATATAGAAGCC
          CGTCGCACGGCGTGTTCGCGGGCGTAATGTTATGTGTAAAGCGTTCTCGATTTGGATTCC
          TGCGGCTATGGCCGCTCGGGGCTTCGGTGTCCCACACCATATGATCTAAATATGTAGCCT
          ACCCCTGCGGAACGGTTAGACTCCCGACTCTATCCGTTACAAATGCAAAGAGATGAAGCA
          AATTGTATAGCTTAGTTCACGACCTGCTCTAGTACGTGCAACTACACAGTTATGTACACG

          GGTACATTGAGCACAAGCGAAATTCGAGCAGCAGACTTCAGTGGACGTATATGTTGTGCC
          GGTATTATGAAATCAAGCGAGGTTCGAGCACCGGTCTTCCGTAGACGTAAGTATAGTGTC
          GGCAGGCCGAAGCCAATCGAGGCTTGAGTAGCAGATATCGGTGGACATACGAATCATACC
          GGCACACCGAGACCAAACGAGGTTCAAGCAGTGGTACTCGGACCACGTCCACATCGTGCC
          TATAAGCGGAGATCAAGCGGAGCCCTACTTTTTGAACCAGGGGAACAAATGTACTGTAGC
          ACTCGGCTCCGACACAACTGTTTTCTGGATTGTAACCCTAATGGGTATTCACCCCTTTCG
          CGTTAATTGAAAAAGCAAGCGACTCTCACTTGAACTTCCGACGGACACAATAACGACCTA
          TTATCGTCGAAGGGGGGAGGACCATCCGCGCCAAGCGACCGAAAGCGGCCAATCGGACTA

          CCAAACCTAGGTACTTGGGGAATTGGCCCAGTTCTACGAACCAGCCGCGGTGTAATCGGC
          TCAAACCTAGATGCTTGGGGAATGGGTCCGGATCTACAAACCAGTCGCGGGGTAATCGGC
          TCGATCCCTGTTACTTGGGTACTCGTCCAAGAATTGCAGACCAGTCTCAGCGTCAACAGC
          TTAATCGTAGGTACCTGGGGACCGGGTTTAGGACTATGAGATAACTTCGGAGCTACTTGC
          TTACTGTTAAGAATATGAGACTTAGTTGAGGGCCCGCGAAGTAAGGACGGACTGTTTGGC
          TCGGTGTGTGAGACGCGGGGTTCAAATGGAAGGAGTTAGAATGAAATCGGTTGAGATATA
          CTCTTGCCGGAAAGATGGGAACAGGATAGCCTATCTCAACACGACTATATGTTAGCCGGA
          ATTCTCTTTCATGCCCGGGTCCCGCAGCAAGCACCGCCACGTGTTAGTCCGCCGGTGAAA

          TTTCCTACGGTTAATAGGGCGCCCCGTGTATACAGGGGCTGAACGTGAAAAGATTTTCGG
          TCACGAATGGTTAATGGGGCACCTAGTGTGTACAGGGGTTGAACACGAAAAGACCGTCGG
          TTCTGAAAGCTTAGTAGGCCATTCAGTGCATTTAGTGGCCCAAAATTAAAGGACCGTTGG
          TTTAGTATAGTTGGGAGTGCGCCAGACGCGCTCAAGGGTTATACACGACAGTACTGGCAG
          CTTACAATAGTGAGTGGGATGCCCAGTGCGCTCGGGTGCGTAAAACAGAGGGCCCGTCGA
          CTAGGAGATGATTACTAGTTGTGATAAGAGTTCGGGTGGGAAGGCTCCAGCGAGTCTTTT
          ATTAATAACGCCTATCGGAAGGCGGTTGACTATAGTCATACCACTTAGGAAACGATTTGC
          CCTCTGATAGTTCGTAAGTTGGCCCTAGTTTCTTTCTGCCACAGCATAAAGCAAATGTTT

          ACCCTTACTGTCCAATGCTCAAAGGGCGTCGCCGGACTGAAAACCCGGAGTAAGCAATTT
          ACTCTCTTTGTGTCATGCATAGAAGGCGTCACTGGACCGAAAACCCGGAGCAAGTGGCTT
          ATTCCCATTGTTCCGAGCCCAGGGGGCGGAACCCGGCCGAAAACCTGAAACAAGTCACCA
          ATACCAACTTTTCCAGGTCTATAGGCCGTGAGCGGGTTGAATACCAGAGGTAAATGAATG
          ATTTCGATCATATCGATCTTGGGAGCCTTTGCCGGTCTAAAGTCCCAGAATGAGGCACTG
          ATTATCCTCGCACTTTACTCAAAACCCTTAGGCCGGCCGACAACTGTAAAACGCGATCAG
          CTCTCTTACCTATTGAGAAAGTATATATTGCCCGAGGCTACCGAATTAACCCAAAAGTGA
          TTCACGGTTGAGCCGGGCCAAAGAAACCTGGCGGGGCCAACAGCCTATAATTATGTATGG

          TCTCTTCGGATCGATTGTCAACGTGATAAGGTGCAGCGCATCCTTATAAGAAGCGAACAC
          TTTCTTCGGATCGATTGTCAGCGTGACAAGGTACAGCGCAGGCCTGCAAGGAGCGTACAT
          TCTCTTCACATCGACTGTCCGAGTGGTAAGTACCAGCGCACCCCTGTACGAACTGCGCAC
          GCTCCCCTAATTGACAGGAAGCGTAGTTAGGAATAGTGCAGCTCTGTAAGATGTGTACAC
          GTTCTCCAGGTAGATTAGCAATGTAGCACGGCGTGGCAGAGGCCCTCACGAGAGGACTCT
          ATACGCCAGGATGAACAACACCGCGAAAACAGGCTCCTCCGACATGCTCGAGGGGTCGTA
          ATTCCTTCCAGTCATTGCTAATGATTGTCAGAACTAAACATCGCTGCACCACGAGTCAGG
          GCCCATTGGGGCGAACCCTACCCTGATTATAAATACAACATCCACGAATTGGACGTTATG

          GAGCTTGGGTGGGGTGGGAGGCTGCAGAATATTACGGGGTATCCTTGGTGGACGTAGTCT
          TAGCTCGGGTGAGGTGGGTAGCTGCAGCATATTACGAGGCATTCTAGGTGGGCGTGGCCT
          CAGCTTGGGTGAGGCGGTGTGTTGCAATTTTCTGCGGGGCACATAGGACGCGCGAATTGC
          TAGCTTGCGCGAGACGGTGTATGGCCGTTTCTCGCGAAGAATATGAGGGGGACGCACTTT
          CCACTTAGGCGATGAGGATCGCCGCGACGTTTTTCGGGGCGTATGGGAGTGGCGAATAGT
          TCGTCAGGCCGTACAAGATGATGTCGTTTTCCTGAGACGTACACGAACAGTTCATATGTC
          TGCTATCTAAGTGAATGCTGGCGACATCCTATGAGGAACGCACTGGGGAGGCACCTTTTC
          CTGACCAGGCTTGTGGTTCACCGGTGAGCAACTTGCTACTTAACAAACCCCGGACAGTCT

          CCATCAATAGTGATTAAACTGTGATAGAGATCTGCATCCGGCCGGAGGTCAGGGGACCCT
          CCATCAATAACGGTTGAACCGCGATGGGGATCTGCATTTGGCTGAGGGTTAGGGAACACT
          TCATTACGAGGCACCGGTCCACAACGCGGCACCGCATGTCGCAAGGGGTCAGCGAACGCT
          CCATCAATAGGGACTGATCTGTGCCTAGCATCCGCCTGTGGCTAGGGGCCGGAGAACGTC
          CTCTTACCGGGGTTCCTCCCGCGTTGTTGGTCCTCATGTCACTCGGGGTCTGCGACCATG
          CGGTAGCGATAGTCCCATCCAGGTTTAGTATATACTTGTGAGTGACGATGTCCTTTTGTT
          TCTTGCAGGCGTCTGTTTTCGCTGAGGATTTGAGATAGTACATCCGAGATAAAGAATGCA
          GCGCCGATAAGTCCCAACCCACAACCGTTCCGCCGGCTATGAGGCAAGGGAGCTAGACAC

          TGCGCGCTGTCGAATAGCATTTGGGCTATCCTATTGACTG
          TGCGCGCTGTCGAATAGTATAGGAGCTTTCCTATTGACTG
          TGTGCGCCCTTGTTTAATATTGGAGTTAACCGCCTTACCG
          CGCATGCTGAAGAATATCGTCGGCGTAATCCCCCCCACTG
          CGCGTACTGTCTAACGGTGTTGGGGTATCTTTACTCATGG
          CTTGTGCTATTGTATAATGTCTAAAACTTTCCACACGGTC
          CGTATTCTGTCGAACAATAATTAAATCTTCGCACCACTTA
          CGCGCCTCGATTGGCTACATATGGGTCAACTGTGCCGACG

