 8 1000
t1        GCTGAACGACTTAAGCCAACATGGGCCTACGTTTTCTGAGAACTATGCGAGGTGGGTGAG
t2        TCTGCATGACGTAAACTACCACAGAGTTACGCTTCCTAAGAACCATGCTTGATGAGCGAA
t3        GCCACACATTTTTGACTAGCATAAATATTCGCTCTTCAAAGACAATACCAGAGGGAGGAA
t4        TCCGGATCTCCTAGACAAGCTCGTATTCCCGTTAATTAAGGAATGCTATAGGCTTGTAAA
t5        GCTGTGCTCTATTGACCCGCTTAGGTCTCCACACTTTAAAAGGAGTGAAAAAGGAGTCAG
t6        GCTACGCCTTATTGACTCGCTTAAGCCTCCATAGTTTAAAAGGACTGTAGCAGGAGCCCA
t7        CTTAGCCTACTTTGGGAGGGTCATAGTGTTAATCCATGCGGCGCAGCCCGCATTAGTAGC
t8        CTAGGGCTTCTCCCGTCCCCCTACACCATCAAACTCCTTGTACCGCATCGATCCTCAAAA

          ACGACACTTCATCGACAACTTGAAGTGGCACTCAGATCATTGAGAACGTGATCCTGGTGT
          ATGAAACTTCATGGACCACCTAGAGTAGAATACGAATCACTGTGAACGTGATCCCGGTGC
          TAGCCGCCCAATAAAATATCCGCAACAATCTCGAGGCCACCGCGGGGGCATCCCTGGCGT
          CAGTGATGCCATATGTAGACCGGGACAGTCCGGACCATTACTATAGTATACTGACTCCGT
          CAGCGGAGGTACATGTGGTCTATGGCGCCGTTGATGATAGCGCATTAGTACCATTTTCGT
          CAGTGGAGGTAAACGTGGTCTGAGGAGCCTTTGACGACAACGCATAAGTATCATTGTTGT
          TTAAAGGATGGCCGACGCTGAACTACCTTACGACACTAGTCTAGGGAACGAAGTCAACGC
          TGGAAAAGTCTAAGAGATTTGATATAACCACCACCATCAGTCAGATCGAGTGGGGCCGTA

          TTGAATCGTACTGGTCAATACTTATCGTAATTCGTGTCGTCCAGGAGTTGTAATTGCGAT
          CTGTCTTGTACTGGTTAATACTCATCGTAAGTCGCGTTGTTCAGGCGTAGCAATTGTGAC
          CAAACTCGTGCTGGTTAAGTACCATTCAAAGATCCTCCTTCCAGGTAAAGGAATTGTATT
          TTGCTTTGGGTGAGTTGCCCCTCATTGCGAGCTACGTCCCTGAGGAGAGAAACTCCTGGG
          CCATGCTTTACCGGTTAATCGTTAACACGTACCGTGTAACTATCCAGAGGTCAGCCCGGT
          CCACGCTTTACCGGTTAATCATCTCAGGATACCGTGCCACTATACAGAGGACAGCTCGAA
          TTATAGAAGTAAGCCTCGCTGATCTCGTCAAGTACCTTATTTGGCTATGGTTGACTTGAT
          CATTGGAACACAGTCTGGCTATCGTGACAACGCCCACCGACTAAGAGAGACTGTTTAGTA

          AGAAACAAGTATCTGAGAGCCCCGGACAGGATTGCGCGAATCCACTTTACTGGATACGCC
          AGAAACAAACACTTGAGAGCCGCAAACAGGAGTCAGAGAATCCTTCTGACTGGTTATGTT
          AGGTACAGCCATTCGATCGCCGTGAACAGTAGTCAGTGCCTCCACTCTACTGGAAATGTT
          CTTGATCAATGTATACGAGATAAGCGTACTAGCCGGAGGGCTCGTATATGTAGCTATTCT
          AACTATATTTGCCAGCGCGCCGGATCTACAAGTCGGTGGGCGTATGTCAATGGATCTGCA
          ACCCATATTTACGAGTGCACCGCATCTACAAGTTGGCGGGTACGTGTTAATGGGTCTGGC
          CTCACTCGCTACCGAACGGTTGCTTGCAGTACTCGACCAACATACACCGTAATCAGTTTA
          CGCTGAAGTCATAGGCAATCGGATTGGCGTGTTTGGCTTTCCTCCCCCAACAGTTCTACA

          TTGATTTGCCTAAGCGATTCCCTTTTCCAAGACAGCCAATATGACGATTCCCGCTCCGAG
          TTAATACGTTTCAGCGGTTCTGACATGCATGGTACTGAATTTGATCCTCCCCGCTCCGGG
          TTGAAGAATTTGTGCGAATGCTCACTGCGTATCAGTCAATATGGTGCACCGTGCCCCAAG
          CTGGGGCGCACTGAAGAGCTTCAATTCTGTCGTGGTTGTTGGTCCGCCTTCGAATTTAGG
          TTGGGCCGTGCCGTCGTATCCCCGCTTGGTAGTGATCAAAGCATCATTACCGATGCTAAT
          TTGGGCCGTGCTATTGTATCCTAGCCTGGCGGTGATCAAGCCATCGTTACTGATTCTAAT
          AACGGAGGAGCTGCTGATCAACGGTCTGGTTGCCGCAGGTATGCCATTATACGTCCGATA
          GTGGAACTAAGGTACGCATTTAGTGCTAGTGGTTACAATAATGTTACCCCAGGCACGACG

          TTAAAGCTCATCGTGCTTAAAGAAAACGAGCTCGGTCGATATTGCGGTGTAGGTCTAGTT
          ACAACGATCATCGTGCCTAACGTCAATGAGCTCGATCCATACCGTGATGTGGGCCTCGCC
          GTAAGGCCTGGCGCGCCCAAAATCAATAATGGAGACCGCTACTACGATGCGAGTCCACAC
          ATAGCCTGCTTTGTGTTACATGCCGTCAATCATAAATACTCTTGACAGGTGCATTCAACC
          GTAGACATTTTCGAATCCAGCGCCAACACTTCTCACTCCGAAGGCAGAGCCGGCCTGGTT
          GAAGACACGGCCGAGTCCAACGTCAACATATCTCGCTCAGAACGCAGAGCCGATCTAGTT
          ACGAAGAGCCCCGCGATACGTGTCATAGATTGTCGATGTAGTTGTGAGGCGATACATGGC
          TAGATTCCTCTCGCATCACGAGCTGCGGACTGTATCCTTTATGGCGCCGCGGTATTCGCA

          TTTTAAACACAATTTCCCTCTGCTCTGTTAGCGAACTCGACCTTTCCCAGGGTAGACCTA
          TAAAAAAGTTAATCCCCTCATTCTCTGTCAGTGGACTCAACTCCCCACAGAGTAGGCCTG
          AACTGCATCCACTCCACTATTATTTTATCAGTGGTCCTCCGCATAACTAGATTAAGAATG
          GGTCGCAAAAAGTGCCATTACCCTTGGCAGGCGGATCTCCAAACCCTCCGATCAGTACTG
          AGTCTAGCTTAGACACCGACAACCCCGTGATCTGCGCCCCGGGGTCATGCTTTAGGTATT
          AGTCTAACTTAGTCTCCAACAAGCTTGTGTCGGGCGTCCCGGACTTATACTTTAGGTTTT
          GACCTGCCTTAGATTCCCATACTCCTCGTGTTCGAGAACCCTTCCTTTAGAAAAGAGCGT
          TGCCCGCTAAGGTCTTGTTCTGATCCCTTAAACAAGTTGCTGTCTCCCGTCCTAAAGTGT

          GGACTGCGGATCGGATTCTTAGGCCCACTATTCCTTTACTCGTTGCCCTCGCTCAATCCA
          TGACTGCGGATCGTATACTTAGGCCCACAATTCCTTTACCTACTACTCTCGCCCGATTCG
          GGACCACAGACTATATCCCTAGTGCCACTACTGTCCAGTTTGCTGCCCACGTACGACCAA
          CGCCTAGAGTTAACTTTTCTTCACTGATTGTTCGAGGATCTTTTATCTCTCCACTATTAA
          AGACCGAGGCTGCCGCTTTGATGACTCCTGTTTTCAGAACCTATGCCTATTCCCGCTGAC
          AGACCGCGGCTGACGCTTCTATGTATCTTTTTCTCAGCGCCAATACCTATTCCCACCGAT
          AGTACATGTATAACGCTGATGCTCACACTGAGGCTATGACTACAACCTTCTATCTCGCGT
          GCTTAACAACACGCTTTACCAATCAGCTTGAAGTAAAGGCTAGGACAGTCTATCGTGGAA

          AAGCGTTAAGATAATGGCCTTCTCCCATGTTCGTACGTATCGTTTCGGAACAGATGACGC
          GAGTGTCAAGATAGCGGCCTTTTTACATGCGCAAACCCGTCGTTCAGAAATAGTACACGC
          AAGCGTTCAGAATACGGCGTGAAATTGTGCTTGCCCCCTGTGTTTAGGTATATACGTGGG
          AAGCTATCCGAACGCTGACCTCCGTGGCACTCACCATAAGGGACGAAGAACCAAAGACGA
          GTGTGGTCCGATTCCGGCCGTCTACGTCTCCTACGCAAATCTAGGAGAAACGGGCAGGGA
          GTGTGGTCCGACCCCGGCCATCAACATGGCCTCTGCTCAGCTAAGAGAAACAGACAGGGG
          CCGCAATCAAGGTACGCGTCTTGCCCCAGCAGCTACCATATACGGTACGCCTGTAGTACA
          GCGGTACCGTGGGTGGAAGCTAAATTCTGCCCCTGGGAATTGTTGGGCATATAAGAAGCG

          TCCAGATCCCACGGGGTATGGAGGGTGTTCCTTATTCCAATTGGTATTGATAGATACGTC
          TCCAGGTCCCATAGGGTACGGAGGATCACCCTGATTGCGGCCAATATTGTTCGAACCTTT
          TCCAGATTCGCTGCGGGATATAGAAAGGCTCTCACTGTTGTCGACAATAATGGCAACGCT
          CTCGGGGGCATTAGGGTGCGTAACCCTGTCTTCTTTAAGGATACCTACGATAAACGCGTC
          CCTCCGGTCGTCGTGTCGTATAAGACGGCGCTCGTCATTGTGGACCTAAATCTACAAGGT
          CCTCCGATCGCCAAGTCGTATATACCGGCGCTCGCCAGCGTAAACCTAAATCTACACGGT
          CCAGTCCTTACCGTGTCGTGTATGTTTGTCGATTTCCACGAGAATGTCGAAGGCTCGACT
          CCTGATTCTCCAGTGTCATGTTTCGCGAGCGCCTCTCGTACCTCTTCCAATAACCCGCTC

          CGTTTTTGTAACTGCGAGATCACACGACCAATGTCGCCTTATTAATGGTAGTCAGGTTCG
          CGTTCTTGTACCTGCGCATCCCCATGACCAACGACACCATACCTGTGGTAGCTAGGACGG
          CGTCCCTGTCATTACGCAATCGCTTAACCGCCGATCTCGTACTTACCAGCATTTGGGATG
          CTCTTCTATGTCTGCGCATCCGCGAGACCGACCCCGCTAAACTAATATGGTTTCACAGTG
          TACTCTCGCGTTTGTGAAACTGTTTCATTGACTTTACATAGCCAATGGCTGGTTACTTTG
          CACTCTCGCGTTGGTGAAACCGTTTCACCGACCCACCTTCGCCATTGCGTGACTGCATTG
          CTAGATCACTCATACACAACGGAATGGCGCTATCCATCTTGCGTGTCGAAAGCCGCGAAG
          AGCAACGAGCATGCCAGAGATGTCCGCCCAACGTTGCTGGGTGAGATGTCTTAATCAGTA

          TGCGTATGACATACCTCTATTAGATCGTACCGAGTCACCCGCAATCCCAAGGCCGACCTG
          TGCGATTTACATTACGCTACCGGGTCGCACCAAGTAGCCCACAATTCCAAAGCTGACCTG
          TCATATTCACTTTCTTGTAAAAAAACCTAACTAACACCCCGCGCTCACGAGGTTGAACTT
          TGCTACGCACGTACATTTCAAGGAAACTATAGAGCAGCACAACATCCCGGACCGAACCCC
          TCACACGCGCGTATACCCTCAAGAGTTTATCAAGACGCGCGTAATTTTAGGCCTAGTCTC
          TCTCACGCGCATATACCCTCCAGGGTTTATCAAGAAGCGCGCAACTTTAGGCTTAATCCC
          CTTAATTGCAATTCAGCGCAATGGGTTATCCCGATATCTCACAGCCTGCTATTGATATCT
          CTCGATCAATGTCGGTCACGCTAGGCCCTAGGATCGTGGGAAGACTAACAAGCTTTATCA

          ACTCAAGTCGTGGAGCTCTATTTGAGCTATAGTCGTGATAGATGTCACTGCCCTTACCAT
          GTATCAGTCGTGAGGCCCTATATGAGTTATGTCCCAGATAGACGTCACTGCCCCTTCCGT
          CTGCAGACAGTGGGGCTTTATTCAGGGCATGTAGGCAATAGGTGCCCCGGTCCTTTCCAC
          CCGCATAAAGTAGACATAAACTACAATCGTGTAAGGGGAGGCGACCGCCGACGCCTCGAA
          CCGCAATCAATAAGGACCGGAACGAAATAGACGACAGAGGACGATTGGTAACACTTTCAT
          CCATAATTCATAAGGACCAGAACAAAATGAACAACGTAGGGTGACTAGTAACTCTTTCAT
          CGGTAACGGATCTCGCATCATACGGCGCGTTCATACGGGTGGGATCGACACCATCACCGT
          GCACAAGGTGCCAGAAATATTATGATGATAGCCTTGGAATGCGGTTATCGGTGCTTTCAC

          CACTCCCTAAGCTTTGGCCATCACCTACCTTGACCCGACAATCTATCTGGATGGGCTCGA
          CACTCCTTAAGCTTTGACTACTACCCACGTTGGCCGGATAGCTTATTGGGATAGGACCGA
          CGCTTTTAACGCCTAAACCACCGTCCGACCTGATCTGACGGTATACCTAGACAGGCTCGA
          CAATCCTGGTAATTTGATTACACTCCGTTTTGGTTCTTCGGAACGCTGATACAGGGATGG
          CGCTCTGCATCCTTCGAACACAGCTCATTTGCGCTCGGCTATTCCTCGGGATCACTATCA
          TGCCCTGCATTCCTCAAGCACGGTTCTTCCGCGCACGGCTATTTCTGGGGACCAATATCA
          TGTGGGTCACAATTAATTAACAAACGACTCCTGCATGCCGGTCTAACCCCACGGGTGTAT
          AGAGTGCGCGTACGACACCATAGAACTATCCTGTCAATTCTTCAATCTTACAAGGCAGTA

          GATAGCACACTCTAATATGGACTCATAGCCTTGCACGGCTAGATGCTTTATGCCGATCTG
          GACAGCAGACCTTAGCATGGATTTATAGCCTTGCGTGGTTAAACGGTCCATACTGAAAAG
          GACAGTAGACCCCAATGTAGACATACAGCTTTGTACGGGTAGTCGCCCGATTACGATGAG
          GGCGGCATATAGGCTTTTTCGTTTATAGTCCAGAACGGTCGACTATTTTGTATTAAAGTC
          TATGGAACAGATAAACGACAAAGCACGCGCCTGTATAGTCTGTTGTTTTACATTCTTTTT
          TACGGACCACATGACCATCAACGTACGAGCTTGTACTGCGAGTTGCTCTACCTTAAGTTT
          CTCGGTTCATGTGTAGAGCACCTCGGAGACTTGCTTCGCTTTATCCTATGCGAGCAGCCA
          TCTGGTGATCGGGCCTCCTAATATGTGGATCCGCTAGGGTTCACTTTGATGAGCCTTGTA

          AATATATGCAAGAGCCTCTGCTTCGATTGCGGTCAGTAGCGCATCGGTACCATATTTCTT
          AATAAATGCTCGAGCCTCCGCCATGATTGCGGTTGCCAGAGCTGTGGCACCATGTTTCTG
          ACAGTTTGCTCGAGCCATGACTCCGGTTGCCAACAATAACCCACCAGCGCGACAATTCTC
          TTTCTGCGATATCGCCTTGATCGTATCCAGGTTCTATTGTGAAGCGAGGTCGAACGCCAA
          TTCCTGTGTATGAGCACCCAGCCTGTTTACGACGAGCTATCCACCGACGTAAATCCTCCT
          TTCCTGCGTATGAGCACCCAGCCTGTTTACGATGAACCAAACCCCGATGTAAACCTTCCT
          GCAACTCCCTCGTTCCACGCCCCGCTCATCCATTGTTCCTGTACCCATAAGGCGAGGGTT
          CCGTGTCAGCCCGCCCACGCCACGTTAAGCACCCGCTGCTGTAGTTGGAAATTATACACT

          AGCATAACTTGATGCAGATTACCAACCGCTTGCCTGCACA
          GGCATAACTCAACGTAGATTGACGATCCCCCGCCTTCACA
          GGCCCGCTCGATCATCAACTACTCGTTCCTCGATCCCACT
          AGTGAGATAAGATGTGGATTATTACTCGCTCACCCTTATC
          GGCACGCTCTAGCTCACACCCCTAATTAATCGTTCTTTCC
          GGCACGCTCCGGCTCACACCCCTAAATAACCGTCCCTTCC
          GGTCCGGTAATAATTGGCCAGTTTGTATTCAACCGACGTT
          CGCACGGTTTCAGCCTGAACAACTAGTTAGCACGACAGGA

