 8 1000
t1        GGACTACTGTTTCACAGCGCGACTGAGTTCATTCCAAAAAGAGGCCTTTTAGTGACGGTT
t2        GGACTACTATCCTATAGTGCGACTGAATTCATTCCAACACGAGGCCTCGAAAACACGGTT
t3        GGGCTCGTTTTGCGCTCTATCCGAGACTCTAGGTATAAGTAGAAATACTATGCAGTATTT
t4        TGGCCCGCTGTGCGTTTTATCCGGGACTCCGGATGGTAGGCGGAATACCACGCAATGTTT
t5        GAAGGTACTCCCCGTTTTCTATTGCGCGTTAGCTCTTGGAAACACTTCGATGTAGCAGTT
t6        GGAGAAATCTACCGTTTACGGTTGCGCGTTAGCCTTAGGAAAGGGTTGGTTGTGGCGGTC
t7        TCGTGAGCGCCTCGTTCCCCTATGGGCGTCAGCCCGTAGGGACAGTTCTCGATAACGATC
t8        CTATAGGCCCCACCTTTCTATTGGAGTACCGGCTTCTGAAGCCGGTTTTTCTTAGCGGTA

          CGGAAGCATGTTCATTCGCCACCATGGGTCGTAATCTACTATCATTCCGGAGCTCGGACT
          CGGATGCATGGTCATCCGTCGCCATGGATTGTAATCCACTATCGTGCAGGAGCTCGGCCT
          AAAATGTACGCACATGGCCCTACCTCGTATGACGCCGTCGAGTGCGCGAGGTACAACGCA
          AAAGCGTGCGCATATGGTCCTACCACGAATGACGCAGCCGAGTGCCCGAGATAGAGGCTA
          TTAACGTGCTCTTAGCGCGGCCCTTCGCCTTGCTTCTTACTGCGCGTGGGAAATGGAATA
          CAGCCGCACTCGCAACGCGGTCATTTGTCTTGCTCATGACCGCGTGTGAGAAATAGGGTA
          TAAATGTTCACACAGGGCCCTTTCCTAACCGCCGCTCGTGCCTGTGAGGGAGACAGGATT
          AAAACGCCGACGCAGAGCTCTATCCCGACCAGTTCCTGAGTCTGTGTGGCGCATAGGCTC

          GAGGGGATTCCGAATCGGCGAGAAAGTTTAGTGCCTCCTGCCCGCACAAATCCCCGGAGG
          GAGGCGATACCGAATCGGCGAGAAAGCTTAGTGACTCACGCCCGCACAAATCTCCGGTAG
          CGGGATGCAATAGTGGAGCCTGAGGCCCCTGGTATGTTGTTCCTGATGAGTTATCTGCTG
          GGGGGGGAAGCAATACCGTCCGAAGACCCTGACACTTTGTACCATCCGAATTCCTTACGC
          AAAGACTTGATGACCAGGTGACAGAGGCAAGTTGTATCACATTATAAGAGTCTCAGCCAC
          TAAGATCAGATGAATAAGTAAAAGTGTCACGCTGTTTCAGATTGTAACAATATAAATCAC
          AGGGGAGGGTCGAATCGGTAGGTGAGCTCTACGATGTCAGCCTGCAGGCCTTTCAGATTC
          TCGTGAGCGGCGAACTATTAGGAGGGGTGATCAATCTCGGCTTGTAACAATCCCAGCCCT

          GTTAGGGGTGTCCTTTCGCGATGCAAGGGGAAAGGTTGTAACATCTGTGACGACGAATTG
          GCCAGGGGTATCCTCACGAGATACGAGGGGAAAGCTCGCGACATCTGGGAAGACGAATCG
          GCTAGGCATAAAAGAATAGGATCTATAGGGGAGTGTTCCGGTGAACGTGGTTTAGAACTT
          GCCAGGTGTAGATGCATAAGGTCTACGAGGGGGCAGTACGGTGTGCGCAATCTAGGACTT
          TGGCGGCATGCCCTGTATGGACTCGGGTACGTCTTGGGAAGAATCTATACCGTCGTGGAT
          AGGAGAGGTGTTTGGTCTGTGCCTAGGCGCGTCCTGTACGATATCTGAACTCTCATGTAC
          TAAAGGAATATCCGACGTAGACCGGTGCGGTCGCCATTTAGTAAATGTACTGTTGTTCTC
          GCAGGGTATTCGTGGCTTGGACTGGTGCCGCTGCTATGCCGCATGTGCGCCCCCATGTGC

          TGTAAGAGCAAATCAATCCGCCCCGATAGAGTTCTGAAGATGCTAGAGGGACTGTGACCT
          TGTAAGTGCAAACTAACCCGCACCGCTAGAGTTCTGAAGAAGCTCGAGTGACTGTGGCCT
          CGCAATGAAAAGACTCAGTGTAATGCGGTGACTGGAGAGCTAACCATGGTTTTCTAGGAA
          CGCAACCTGAAGACCCTGTGCCCTGCGACGATCGGAGAACTACCGATGGTTTCCTTGGAA
          TGTGAATTCGCAATATTTTGTGCAACGGCGGTAGAGAGGGCCATAAAAGGACAAACACGC
          CGTGAGCGAGTCATGTTTTGTGTATCACAAGTGGCGAGGGTCACTTCAGGAAAAAAACGC
          TCAGAATCGGCGATCATTCGCTATGTGGTAATCGTGGGGACTACCAAGGAATGTTGGTTC
          TCAGACTTAGCGCACACTTGCCTTTGGGTAGGCGCGGGAGGAGCTAAGGAAAGTAGGGCC

          ATGGGTATTTAAAAGTGAACAGCAATCAAGGCACCCTGAGGTTGGATTCTATAGCTAGAG
          ACAGCTACTTAAGAATGAACAGCCATTACGGCATCCTGAGGCTGGTTTTAGTACCTCGAG
          AATACATAAGCAAGCCCGGTCTCTGTCGCCACGCCGCAATATCTCTCTGAGCTACACAGG
          AGCATATGAGCAGGCTCGGTCGCTGACGCCATACCGAGCAATCTTTCCAAGCAGCACTCG
          AGTCTTTGACCGTACGAAACTGTTACCTAGTTATGCTTGTTACCTCGCTTAAACAACTCC
          AGAACTCGACTGTATGAAACGGCCTTTAAATCATAGCGGTCGCCTTATTAATCCGATTTT
          CGATTTTCACTGGTCCGAGCAAAGACCGTGTGATCGGAGACGATACTTCTAGTTAAGAAC
          AGGCTTTGCTCGCACCTAGCAGTGGTCTCGTACTTAAAGGAGCGTTAATTACTTAACTAG

          CATATATAGCAGCGTCGCGTCCCGTACGAACAGCAAGCTTAACGTTCCAACCCGTGTAAC
          CGCATATCGCAACGTCAAGTCCTGTATGGACAGTAAGCTTAACGCTCCAACCCTTGTATC
          TGCCGTCATTTAGATCTATTGTAATTACCTAAGCAGACCATATCTGTTCTGCTTACATCG
          CGCCATTGTTAGCATCATAGGTAATTACCTATGCAAGTTATACCTATTATGCCTCAGTCA
          TTTGACTGATCACATGACGAAAAGTCTATCGGAACGAATCCTCCATATTCATGCTGCCAA
          TTTAACTGATCACACGACCACAAATCAATCGAACGGACTCCTCTATAATCATATTACAAG
          ATTTAATCGCCGCTCACTAAGTGGTCTACCCCGGGGTGTACATAAACTTCGCTTTGTATC
          ATCCTTAGGTCAAGCCTGTGCAGGACAACCGCGGGGCGAATCCCTCATGAACCTAGTATG

          TAACCTCGACGGTATGGTGGTACGTCCTGCATCGGGTGTATGACTGTCATTCATAGCCAG
          TAATCCCGACAGTTTGGTGGTACGTCTTGCATCGTGTATATGACTTTCGTTCATGGCCCG
          TGTCTGCAATGCTACCGAGTTGAACTACCCGTTATGCTTAACACGCAAGTTTGTGACAGG
          CGCATTCAATGCCACTGCGCTGGATCCCCCGTCCTGCTCACAACGCACCTTTGCGACCGG
          GATTCTTCACGCTACCTTACCGGTGTCCCACCGTCGCCTGCGGCGCCCGACTATGCTCCG
          GCAACTCCAGGCATCTCTACTGTTGTCACGTCGACGCTTGCAGCGCCGAGCTGTGAGCAG
          CGCCGTCGCTGCTACTGTGTTAATGTGTTGTCTGCGCTAATGAGGCCCGCCAGGGATCAA
          TGCTTTCGATGATACTTTATCGTTGTAAAGATCGTGTCCGTGAAGGTAGCTAAGGATTAG

          AAGTTGCGGATTTAATGCGAGTAGATGTGCCATTCACCTTCCTAGTGTTTTTTATCACAC
          GAGCTCCGGATTTAATGGGAGTAAAAGTGCTATTCACCTCGCTAGTGTTTTTTATCGACC
          AAATTTGGAGCGAAACATCCATGAACGGGGTTTTCCCTATACCAGCGCATATATCGAACC
          AAGTTTGATGCGCAATACACCTGAACGTGGTTTTCACTACCCTCGCACATACGTCGAACG
          CTCCGCTAGGTTAACCTCACTCCTTACAGACACCTTTTTATCTGTAACACCACGCCTTTT
          CTATCCTCTGAGAACTACTCTTCATAGAGACACCTCTAGTTCCGCAGTATTACGCCGTTT
          GTGCATCACGTTCAACACTTTTAACCGAAGTGTGTTCAGATCTGTAGCATTGCGCCATCC
          CCGTGTTATGAAAAGAACCTTTATACGGGGTGCCCTCTAGCCTGCCGTGTCGCGCAGTTA

          GGCCCATATAGAGTGGGCAACGCCCGTTAGAACGTCAGTTCGAGGTTCCATGCCCTTGGT
          GGCCCATTTAGGGTGTGCAACACCCGTTAGAACGTCTGTTCGAGATTCTATGCCTTTAGT
          GCGAAGGACTGGGATTGATGAGGAGGTGAGATCACTAGCTTAGTAACTTAGAACATCGGT
          GCGAAAGAGCGGGACTGATGAGAAGGTAAGATCACAGACTTAGTATCTTAGGCCAACAGA
          GTTACTTTAGGTATTAGATGCATCGGATGGCTCCTACGTCCTTTACCCTACCATAATGTT
          GCTAATATGGATATCGGATACATCGGACAATCACCACGTCACTCATCCCACTATAATGTA
          GCTACCGCAGTTGCAGGCCCCTACAGCCAGTAAGCTTGTATTCAATTTTACTCGATTATT
          GTCAGAGTAGGCGCCAGAGTAGTTAGTCGGAAGCTCCGTATTAGGTAACATTTCCAGATC

          TCCGGGCGGCCCTCGAGCCGGCTCGGTATATAGTGGATCCGTGCGTTCTAGGAATATTAA
          TCCTGGCGGACTTAGAGCCGGTACAGTATACCTTGGATCCGCGAGTTCTAGGAATTTTAG
          TATAGCCGTCTCCGGACTCGCATACTCCCGAGCTAAATTTCCATGACTTCTCTTTTGCTT
          CGTGTCTTTCTCCGGACTGAGTGACTTCCATGCTGAACTTCGTTCGTTTTTCTCCTACTC
          CTGTGCCCCTTTCGGAGCTGCCGCCACATAGCCTAGAGGTACTAAACATTTGTTATGATA
          TTTCGCCCCCTATGGGACTACCATCAGACAACTAGGCCTTGTCTAGTGTTTGTGGTGTTG
          CCTTGACCCCCTGGGACCAACGTTCGCACAGCAGGGACGAACATTCTCACCGCCACATCG
          CCTAGCATCTTCTAGACTCAGCTCCTTGCAACAGAGACGAATGTGACTTTCGTTACATTA

          TTCACATTCACCGCCGGATGACACATAGTCAGGAAGCGCTGGATCAAACTTAAAATATGG
          CTCATATGCACCGCAGAATGGCATACAATCAGGAAGCGTCGAATCAAATGTAAAGTACCG
          CTTAAGGATATTAGAAGCAAATCCGCTTATGACAAGGGCACGGCCCCGCCCGGCGCGTCC
          TTCGTATTATTTAGAAACAAAACCGTCTATGGCGAGGGCACGACTACGCCCCACGCGTTT
          CACTTGTCCCGCATATCTGAACTAGCGTTCTGAAGGTATTTTGCGTGGTGCGTGGAATGA
          CCCTAACACTGCCTAACTGGTATTGCCTTCCGATCACATATCGTATGGTACATGGAGAGC
          TCCTTCCTACACCTGAATGAGATCAATTCCCGGAATCACCGAGTGTGCTACATCGCATGC
          ATCGTAATCAGCGCAATTAAACTGCCATCCCGGGATCAACAGGTCTGATATCCTGACTGC

          GCAGTTAGCGACTGAGATAACTCCAGATGTTATCCAAGCATTGGTCTCATGCTCGAACTA
          GTAGTCAGCGACTGAGATAGCTCCAGATGTCATCTAAGTACTGGTCTCATGCTCGAACTA
          TCTAGCATCGCTTACGATAGGATCCCAGAACGATCTTTCTATTTAATACCGCACACGTCA
          GCAACTAATGCCTAGGATACGATCGAAGGATGTCCCTTTTGTTCAATAATATGCACGTGA
          GAATTCAACGTTCCTGACAATGCCCTACGTCGTTGCCATGCCATACCAATATATAAGAAA
          GTAAATCACGATCATGACAGTATCTCGCGACGTCGCCACAGCATACCCACATCTCGCAAA
          GAAGTTTTTGGCCACGACAATGTCGTACGAGGTTGTATTAGTGAAACGGCACTATAGGAA
          CAAGTTCTCGGCAATAACAATATTGCGTAAGCTTTTAGTAGCGAAATAAAAAGTTGGAAT

          CAACATTTCCTACTGATCTGAGACTCACGGTGTGTTTAGTGACACATAAGTACGTGATCG
          CACCATTTCCCAGTGACCAGAGACTCAGGGTGTGCTTAGTGACATATAAGTACGTGGTCA
          CGCCACCTCATCTCGAGATAAGAGTAGCGGTATATTGCGGCATACAGCGACAAGCTAGCA
          CGTTACCTTACTACGAGATGAGAGTAAAGGAAGCCTGGGGCATACGAAGGCGAGTTAACG
          AGCAGCTGCTTGCCACGAGAAAATCCGGGAAATATTTGAGCGTACGACTGCCACCGTATG
          AAGGGCTCCCTACTAAGAGAAACTCAGACAATGGCAAAAGCGCACGCGCGTCACTGTTTG
          CACTGCGTTTTACCGCAGGACAATTTTGGGATCACTGGGGCGTGCGTGTGAGATCGGCAA
          CGCCGCTGTCAATTGCAAGAAATTTGAGGGGACTTCGGGACGTGTATGCGTTATCGGCAA

          CCGTGACGCCGTCGCCCTGCGTCTTGCGAGCAAGCCAATACACCTTTACGGCGCATCGCC
          CCGCGATGTCGTCACCCTGCCTCTTGCCAGCAAGCTAATAAATCTCTCAGGTGCATTGCC
          TTATGTTCCTATCCTTGAACGCGTCGTAAGGGAACAGACACCCCTCACGTTGGGCTTCAT
          TGTTCTACCCGTCCTTGGATGCGCTGTGAAGGAACAATCACCCATCATGTCTGGCTCCTC
          CTCCCAATTCTGGACCAGGCCCCTTACACCAATAACAAAAATCCCCGGGTACCCGGTACA
          CTCAGCATTTGGGACCGGGCTCCTGACAACGCTACCGAAAGTATCCATGAATCAAATAAA
          TTAACAAACCGCCATTAGATCGATTTGAAGCTTATACCTCCTATTTCAGAGACGGCTGTA
          CTCGGTCCCCGTAACTTAATGAATCCAAAAAACAGGGGGTGTCTTTAAGAATTCTTCACA

          TTGTAAAAAGATCTGAAATAACTTCCAAGTGTGATGTTTAAGGGCGTTCCGTCAGACGCT
          TAGTAAAGAGATCTGAAATAACTTTCAAGTGTGATGTTTAATGGCGTTCCGTCAGACGCT
          TCCTAAAATGTCATAGCCTGCTTCTACGACCTCTTTACCGTGTTCGCGCGATAAACACTT
          TTATAAGATGACGCAGACCGCATTTTGGATCTATTTTCCGTATTGGCATGATAAACCCCT
          CCAATGGTCTTCCAGTGGCGTATCATCGTTATAGAGTTCGAGAAGAGAACGTTCAGGCGT
          CCTGTTGATAGCCAGTGGTGAATTTTCGCCTTAGAACTCGATAGGAAAACGATCAGGAAA
          TCTAAAGCTGCCCAGTGCTAGCCCTACATCGTGATATCCTAAAGAGGAACGCTTAATCAC
          CCTAAGGTTAGTAAGCGAAGAAATTCTCCTGGAGTATTCGCGAGAGAGACGCCTGCTCAC

          ATAGCTTTACGTCCAGAAGTCGTGCTCTCGATTGTCCGTT
          ATAGCTTCCCGGCCCAAAGTTGCGCTCCTGATTGTCCATT
          TTCGTCTTATGCTTTAATGCTGCATGTACTGCCCTTTCAT
          TTCTCTTCATGCCTCAAAGTTGAGTGTGCTGGCTTTCTGC
          CATGCATATGAACAACGAGACTGGACTGTTGGAATGGGCA
          CATATATATGAACGACGAAACTGGTCCGTCAGAATGCGTG
          CATGAATAGGCGTTTAGGGATGAGACCGCGAAGCAGGGCG
          GATCCACGAGAGCCTGGGGATAAGGCCGTTAAAATGCATG

