 8 1000
t1        ACGTTTGGACGATGTCCGTTCCACTCCAGCTCAAGATCGCTCGATGTTCCACCGAGGGGG
t2        CCTTTACAGAATGATAAGCAGACCATCATGCTTGCGCCCTCTCATGCTCCTTGTCGGGAG
t3        ACGTTGAAGCGTCGTAAGTGGGATCAGAATCTAAAGCCGATTCTTATGTGTTGGAACGAT
t4        ATGTTATCGTGTCGCACGTAGCATACAGATCCAAGGTCGTGTTATACATCTCGGAAGGAT
t5        AGTCTTAACTAATCCGCGCAGAAAACGTCTCCAGCTTACTACCCTGCTATTAGCAGTAAC
t6        CATTCCAAACAAGCCGAGCTACCACTGACTGCAGCATTCGTAGTCTACGCGACCTGCTAC
t7        TTGCGCAAATGGTTTAATGCGCAAATCTTGCCCACTGGACTCGACATCGGCCACGCGTGT
t8        CCGTGGAAGTGACACAAAGCGCCAATAATCTCTACCGTTCCCGATATTGGCAACGTAAGC

          AGGCGGGGGATCGCCGCTAATGATCTGACTGAGAATGCCGGCGGGCGAATCGATGGATCC
          GGAGGAGAGGTTGTTTTTATAAATCAGCGGGAATTATCCGGTGATCATGCGGTTTCATAT
          ACGTAAGATACTGTTTCTACTAGTCTATTGAAGGCCCTTACCATTCAGGCCGTTTAACTC
          GTGTCGGACACTATTTCTTCTGTTTAATTGGAGGCTCGTAAAGGTTGCGTCGGATAATTC
          CTAGAGGAGATCTCCACCTATAACACCTAGGTAGCGATTAATACCTGCACAGACCGGTAT
          CGGTAGGATGTTTCAATCTCTAGTCGCTTGGCCTTAGTCAATGCGTGTATTATTTGGCAC
          TCGGAAGAAGTCTTAATTATCGGTCCACCAAATGCACTCAGCCTACTTGCCGCCCTAGAC
          ATGACAGAGGTCTCAATTGTGGGTCGATTTATCATATCCAGTTCGCTAACCGTCTTAGAC

          CGTCCCCCAGCACTCCGCTCTGCATTTCCCCCAGACCGTATATTGATAGCATTTGGCATA
          TGAGACCTACCGTCGAACCTTGGGCATAGGTTGGTAAAGGTTCGAGCAGCACGAAGGTGA
          AGCAGTTCGCAGATTCGAGGTGTATGGTGATCCACTGGTATGCCGCCGGCATATAATCAG
          TGTAACTCTAAATTCTGATTTAGAAGGGGATCCGCAGCTATGCGCAGGGCAAACGATAAG
          TGGAGAGCCTCCACAAATTTTAGTCGGTCTGTCCTCGAAGTGTGTGCAACAGCACTTGTA
          CGGGACTACGTCCCATGTTTTGCGACCAGATTCGCCGGTGTTTACGCAACACTCGTAGGA
          CATATTAGGTTCGTCCGCTGCGCATGGTGCTCCGATGGCACGAGACAGGTCTCCAGCTAA
          TACACCGGGTTCGTCCACTTCATACGGTCTTCAGACGGAAACCTAAAAATGTCAAGCTAA

          GATTTGATGCTAGGTTATCTCAAAGAGCGGCTGTGGAAGATTCACCATGATTACCCACTG
          TACCGCTCTGCGGCTCGGGACATAGATACTCGGTCGTTCAACTTTTAGGCCCTCGCGAGG
          GTAGGGTGTTCGGTTCGAACATTAACTAGCTCCGCGAGGTTGAACCTCGCTTGACTTGCG
          CAAGACCACCCGGCCCGCCCGTCGGCTGAGAAGACGTTATCAGCCCTCACGCATCCATGG
          CGTTCCTACTAAGTCACTACGTTTGTCCAAACCATTATTTGTGCGTGCGCACTTCTGATG
          CGTTAATATCAGACCAGTGCATTAATGCAGCTGTTGATCTATACCCGCGGATTACCACAT
          GCCTACTATTATTGGAGTGAGTCCATACATCTATCGTTGTATAAACGTCTATTTCATTAC
          TCCTGTCGGTAAGGGAATGCGTCTGTACGTCATTTGTTGTACGGACATGTACTCTATTAC

          TAAAATTCGGGCCACGCAACAGGAGAAGGCCAAAAAAGTTTATCGGTTAGAGGTAAATCG
          TTAGATAACGACCACATCGGTCGTGACGGGTAACAAATCGACGTGGACGGGAACAAACCG
          TTCACCTTCGGTCCATCGTGATGAGAAGGCACCTAGTCTACACCGGCGGAGGGTTAACTG
          CCAATCGTCGCGCGCGTCGAACAAGTGGGCCAAAAGCCCACATCGGTTGAAGACTAACGG
          TATCATCTTCCTTCCATTTCACAGTTATATTCGTGGACATCGCGGGATAATGGGTTGGTG
          TGCCCCTTTGTCCTCACTTCATTGTCGCTATTGTCGAGTGCGATGGAACTCGATTCTCCT
          CAATATCCTGGTCCCTATACAAAGGAGCAATCAGGGCTTTCCCTAGGGTACAGACCGTTA
          CCGCATTTTGGTCGTTGCCACAGACAACTGTCTGTGCTCTTTGTTGTATATTGTCCGTCG

          GCGAGACGGGACCGACCATTAGATCTGCGCTCCAAACGGTGTCTATTAACTGTTCCTGTT
          GCTATACGGGAGGACCTGAGAAGCTCGAGCTCAAGTCATTGCTTGCTCTTACTGTTTGAT
          GGCGGGGGGAAAAGACGGCGGGGCGCCGGCTTGCAATAATACCTGTAGCTACCATTGTAC
          GCATGGACAAAAAAGCCCCGGTGCATCAGCCTAAAACGCCACTCCCATCTAGGACCGAAT
          AGGTATTAGCGACAATTTTTGGGTGCCCTATTCCAGCGGCCCAGATTTTATTAGTTTGAC
          GGGAAGGATATAAAGTGGTCTAGCGTCCCACAACGCCAGCGTTGTGTGAACCCCTTTGAC
          AGGCAGCCGAATAAATCGCGAGGTCTTGATTTATGATGGCACCTGGACTCGTAACCTTTC
          AGCTAGCCGGACAGATCATGGAGTGTCGATCTACAATTCTACCTACTCTAGTTATTTTCT

          AATCTTACGGGTCTTCCACGCGATGCGCTAGCGCCCGGGTGCATGCATTCAAGCTATAGT
          AGCCCCTTTGTTTCTTTTAGAAGAGCCTCAAGGGCCTATTGAGTATACAGGGTTAAAAGT
          AATATGCCGAGTATCCAGTGGCCTGGTCTGACGGCTCCCAATATGTTGGTAATTTTCGCC
          AGCCTTTCGAGCAATTAGAGGCGTGTCCTGGTGCCCCCTTACCCACTCATACCGTTCTTT
          ACTGCCCTCCAGCGGTTGTCGTACATCTTGTTAGTAGGAGGTCTACACGCAACACGCGGC
          CTCATGATGCTCAGACGGTTGTATGCTGTGATTGTTAGCGGTCTGCGTATATTCTTTGGG
          AGAACTTGGAATCTTTTACCATAGGACAGAATGGTTAACTGCCTCTCCTTAGTGATTGTT
          AACTTTTTGGATTTAAGGCCATGGGCTAGAATGGCGATTTCCCTGTTCTCGACGTTTGAT

          TGCGGCAACGGAGATTATGCGCGGTCCGCTTGACACTCTCCCAAAAGCAGAACTGGCTGG
          TGTATCAACAAACGATTCAACCCGCTCTCCCACGCCGCTGACGACAGCTGCCCTGGCTGG
          CATGGTATTAGACAACTCGCACTGGCCATCCTTCGTAACGATAATATGCACCCGGTTGCC
          CATGGTAACAGGCGACAAGCACGGGCCATCTCTCGTCGTATTCGAACTCGTAACGATGAG
          GAAAATAATCGGGCAAGTAATTGATCCGATCACACCGTTCCCGAAAATTGCATCATCGCG
          TGAGGCAAGGGAGTAATTGATTGGTACGGCGGGTCCATTGTTTCGAACGGCCCTGTCGAG
          AGAGGCAGTGGGTGGTATGGTCGAACCCCAGATCTGATCGGTCGGAGTAGAGCTGACGGA
          AGAGGTGGCGAGTAGTGTGGCCGATTTGTAGGCCTGAATAGGGTAAGCGCAGCCAATAGA

          AATACGGATGCCTGTCAAGCTTAGCCCCGGCGAATACAATCCCACACCAACAGGGCAAAC
          CGTACGATCCATCGACAACATACGGCGCGGGGAAAGGGATCTATGATCGATCAGGGACCG
          GCCAAAGCAGATGGCTCATGCAAGTCCCGACGAATATGACCCTCGGCCTATGTCGGCATG
          GCCATAGCTATGGCACCATGCAAGTGCAGGCGAACATGTCCCTACATCCCTCTGGGTCTG
          GCTTAGGCTGACGGACGGTGCTAGGCCGGCCTAGTTAGAATTCTGATGCACATTCGCTGT
          TCTCAGGTTGGCGCCTTATGTCACGTAAGCTAAGCAAGTTTTAACCGACACCCAGGAATG
          ATTCGAAAGCTTAGTAGACCTTCGAGAAGGGCGTCGTCGGTGACAAAACGCGAGAGTTCT
          ATCTGGACGCCTAAAAGACGTTCGGGCAGGGAATCGCGAGTAACAGGCAGTGTGAGATCT

          TTGGCGAACGATAGCGCAGGGAAGGTACGCCCCACGACTTCACCCATGCGGATCTGCCTA
          CAACTGGCGAGCAGCTTCGGTTGGTCCGGTTCGACGTTTTCTGTCTTATAGTTTCATGTT
          TGATAGGACTATAAACTAGAGATGACGCGTTAAGTACTTCCTATTTTACAGATAGAAATG
          ACGCAGGATTCTAACCCAGAAATGATAACTTACGTAATTCTCGATCCGTCGACTGTTACA
          CAAGCGATGACCGTTAGGCGATAGGTGAGAGGTGTGCCCACCCCTAAGCAGAGGGGCTTA
          AAAGCGCTCACAATTTCAGGGCAGGCGAACACCCTTTCCAACTCCAATTGGACCTTCCTA
          CGAGCCGTAACGGATCTATGGTTCACGGAAAATGCTATTGCCACAAAACAAGCCGGTTTT
          TGCGTCTTGACAACCCTACGGATGTTGGACCGTGAGTCTGCAATACAATGCGGCGATTCC

          CGTGCTTGTCCAGAAATCCACTCGGCTTCAACGTGACGTGGGGTCTCCCTACAGTTTTGC
          CCTTTCTATTGCCCAGGTTGTTCTGGTCACAGGGTATGAAGGGCCACAGCAGTGCCACCT
          AACGATCTACGACAAATGTGATGCCGGCGTGTCCTTCGCAGGCTCCCCTTTGAATTGCTT
          AGTGCTCGAAGACGAATGTGACGCAGATTTGTCCTAGGTCGGAACATCGTCGAATCGCCT
          GGACGCTGTGTGGGAGCTGGTCAACCTGTTCAGCAGCGCGGGAAAACTACTTTTCTTATG
          GAATATTCTTTGGTGGCATAAGGATATATCCAAATGTGCAGAGTGTTCGCTTTCTTGTCG
          AGCCCCTGCTAACAAACACGCCAGTCATACAATTCATGTAGATCACCCTCTTCCTCGCCG
          AGCCCAAGCCGAGAAATGCGTCAATCACTCAACCCGTACAGAACACCTTTCCCCCAGCCG

          CGTATTTCCACGTTTAAGTGTAGCAAATCCATTTTATTTGAAGTAGTGTCCTTGTCTGAA
          CACTTCCAGTTAAACTGGTAACGCCTTCGCGATCTGTCCTAACGCGGCTTACACGCGGGG
          CGCGTACTCAATTATCCGTTGTGCGAACGTGACCTGTTCTAGACCATACCTTACCTGGCG
          CGCGCGTTACGATTTCATTCGTACTCGTGCGGCGTATTCTAGATCATTCCTTACCCAGTT
          TATGTAGCGAGGACTCAGTCAGGGGCCACTTGTCCCCCTTGGGAGGTCCCCTCGTCCGGG
          TATTTCCCAAGCTTAGGCCGACCCAGAACTACTCTGCTTAGGGTGGTTGATACACCCGCG
          TAGTTACTCAGACACTGATTATTAATGACCAAAATGTTGATGGTAATTGTATCCTCTGCC
          TAGCTAACAAGTTACTCATAAGTATCGTCTGGATTGCTGATGGTATATGTATTCTCCGTA

          GATATCTTCTGCCGTACACACTCCCGGATCTTGGTCCGAACTTATGTCACTGGTAGGGTT
          CAAGCTTGCCGATGCCTGAATACTCGAATTTCAAGTTACCAAATTGTGAGAACTCAGGTC
          AGGGTCTACCAATGCCAGAGGCTGTGACCCCCGGGATACGTGATCACGATCCCAATTGCC
          GAGGATTCTCAATGCACGATATCGTCGGCACCGAGATGTCAAGTCACATGTCCAGTTGTC
          CGGACTAGAGCTTGTCTGACCACGTTCGTGCCGACGTCTGTTACCCTTTATGATAGAGCT
          TAGGCTAACATTCATTCCAGTGAACGCAATCTGGACGATACAATCCCATACGTTTCCACT
          GGAGCTAATAGGCGAACGCAACCCTACGTTTTTCATCAGTTATACTGGTCCTTTCGGGCT
          AACGTCACTGCTCGTTTAGAACCACGTGACCTACATTATCCGCATCAGTGCGCCAAGGTT

          ACTGTGCCGTGCCCGCACGCCGGGACTACAGAGCTAGCGTAGGTTGCCCTTGCAAGGATT
          ACCCCCAAGAATAAGCCGGCTGCGAACGCAGGCATAATGCGTGTTAATATAAGACGGGTT
          CCTGCCTCATGTCCCAGCGCTAGAGTGAGGGATATGGAGAGGAACTCTACTCTATCCGAT
          CCTCCTTTGTCTTAGAACATGCGAAAGAAGTAGATGGCAAGTAAGCCTAGTTCACCTGAT
          GCCTCGCCAAAAGTGTGCGCAAAGAGCGCAAATAAGGTTGAAATCAAAAATCTCTCAGAC
          ACATTGGTGATGGCCTCAGTGGAGCGCGCAAACAAGGTTGATGATATGCACTTACAGGCG
          GCGTCGCGCACCAAGCGGGTTGTCACAATTATTAAGTTCGGCAATGCTCCTTTCTGTAAT
          CTAATGTGCACTTAGTAGGTCGCAGTCATTATCATGATCGACTATCTTCCTCTGTTTAGT

          TCTCCTCAGCCAGCCACTCCTCCCTCGAATGTAGTCTTCATATCTGGTACACACAACTCG
          CACTGTTGGGTAAATCCCTATTACCCAAAAACAGTTCTACCGGAGACGCTGCAGGATTAT
          CATTGCAACTTAAATGATCGGTATCCCAATGCGGATCCTGTGATAAGGCTCTCAAAGTTT
          AATTGCGACTTCAAAGATGATACCTTTAGTGCGGACGTCGAGACGAGGCTTTCAGGGCGT
          GCACGACTGACACGAGTACAGCCCAAGTGTGTGGAATCTCCCTTGCAGTGATCACTCAAT
          ATCACCTTGACCCAAGTGCATGCCCTTTGCGCACGGTCCGCCCAGTGGCTTCTGCGCGTT
          CCTAATCTCACCCGAACGTCCGTCGACGTGGCAATGTTCCGGACGGGCCGGATCCAGACC
          CCTGAACCCTTTCGCTTGCTAGCCACCGTTGCGACGTCTCCGAAAAGTTGGAGGCGTACC

          TATGGTGATCCGTAGTTCCGAACTGCCAGTTCAACCGGCGGTCGGCCTGTTCTCAGATCT
          CATGGTGCAATAGAGAAACATCTCGTCGGCTGTAATGCCGATCTGTCTTATGCTGTCCTA
          CAACTAGCAACGGCAAGGTGCCTCACCGGGGGCGCCCCTGGTTATGAGCGGAACCAATTC
          TACAGACCAGTGGCGCAATGCTCCACGCGGTGTGTCCTGGGTGAACTGGGTGGTTGAGTC
          AGTTGCACGAGAACCACTATCCTGGTCATGTGATCTAGAACGCTGCAGATTTATCGACAC
          CGCGGCGAGCGCATTAATGTAGCCAGAGGATCACCTTGGACCGTTTGAATGTATTCGCAA
          CTCGGTGCTTCAATGCCAAACTAGATTACGGCAGCCGGGTGGTTCTGGGACCATTCGTTT
          CGCGGTGTCTTCATGCCGGGTAACATTGTGGCGGCAGGGTGCCGTCTGTATCAATTCCTC

          CCCGACATTTTCGCGCAGACTCTGGAGGCTACTTAGGCCC
          TCGGGCCTGTCGGGACTGCATCTGGAGCACACTTTCGAAT
          GTCGGCGTTTAGACCATGCGCTTGATGGATGCTCGGCAGC
          TTGGATTCTACGATTAGGCACTTGACGGACAATCGTCATT
          CTCGTATATCAGATCCGTCGGTCCGAGGACGGTCGATGTT
          ACTAGATCCTCGGGCGAACCAACGGGAGGCGGTCTATTGT
          TACAATATTGGGTCTTTGTAGCCTGAGAATGTTTAGCTGT
          CTAAGTATTGGGGCAGTGCTGCCGGAGGACAATTAAGTGT

