 8 1000
t1        CCAGAGAGTGCACAGGTAACAGCGGACTGTCAAGACGGGTCACCGCGGACTATTTCCCTC
t2        TATGAGAGTGCACACGTAACAGCGGACTCTCAAGACGGGTTACCGCGGACTATATACCTC
t3        CAAGAGAGTGCGCAGGTAACAGCGGTCTCTCCGAATGGGTCATTGTGGCATATTTCCCTT
t4        CAAGAGAGTGCGCAGGCAACAGCGGCCTCTCCGACTGTGCCACCGCTGCCCATTTCCCTC
t5        CAGGCAATTGTATAGATGGATGTGGACTTACTATACGCAAGACAGTGCGCCGTGATCTTA
t6        CAGGCAGTTGTATAGATGGATGTGGATCTACTATACGCAAGACAGTGCGCCGTGATCTTG
t7        CGGGCAGTTGTATAATAGGAAGTGGACTCTCTATACGCAAAACAGTGCGCTGTGTTCTTG
t8        CACGCAATTTTACAAGAGGAAGTGGACTTTCTATAAGCAAGACCGTGCGCTGTGTTCTTG

          ATAAGAGATCGGTTAATAGACTTGAATTATCGCGAGTTTCTTAACCGCAGACTGTGATCG
          ATAAGAGATCGGTTAATAGACTTGAATTATCGCGAATTTCTTAACCGCAGACTGTGATTG
          ATGGAAAACAGGTCAACAGACTTGAATTATCGTGAGTCTCTTGCCCGCACACTGAAGTTG
          AATAGACACAGGTTAACAGACTTGAATTGTCGCGGGTTTCTTGACCGCAGATTGAGATCT
          CATGTACACAGGGCAATGGAAGGGCCCATTCCATCGGTTCAAAGCGCTTCAAAACAACCA
          CATGTACACTGGGTAATGGGAGGGCTCATTCGTTCGGTTCAAAGCGCTCCTAAGCAATCA
          ATTGCAAACAGGATAACAGAAGGGCTTTTTTCATCGGTTTGAAGCGCTTTACAGAGCTCA
          AACGTAAACAGGGCAACAGAAGGGCCCTTTTCATCGGCTTGAAACGCTCCACAGCGACCA

          TTCGGACATCCTAACATTTTAAAATCCATCACTGTCTGGCCGCCCCATGTGAACAACACT
          TTCGGACACCCTTACATTTTAAAATCCATCACTGCCAGGCCGCTCCATGAGGACAACGCC
          TTCGGACTTCCCCACATTTCGAACGCCATCACTGTCTGGCCGCCCCGACAGGATTATGCT
          TTCGGATATCCCCACATTTTCAACGCCATCACTGTCTGGCGGCCCCGTGGTGACTATACT
          CCACTACACTTTTCGAGTTCACAAACGTTTCGCTTGGGGTTGCCTTCTAAGGTTTACCTC
          TCACTGCACTTTTAGAGTTTACAAGCGTTTCGCTTGGGGTTGCCTGCTAAAGTTTACCTC
          TCACTACGCCTTTCGAATTCACAGACGTTTTGCTCGGGGTTGTCTCCTAGGGTCTACCTC
          TCACTACGCTTTTCGAATTTACAAACGATTTGCTTGGGGTTGTCTCCCAAGGTCTACCTT

          GGTGAATACACCACCCCTAGGCGTTCCCCATGCTAAGGAGGATCCTTTGACCCAGGATCT
          GGTGAACACGCCACTACTAGGCGTTCCCCATGTCAAGGAGGATCCTCTGATCCAGGACCT
          GGTGCATACGCCACCACTATGCGTTCGCCATGTCAAGTACGATCCTTTGACTGAGGTCCC
          GATGCATTCGCCACCACCATGCGTTCGCCATTTCAAATACGATCCTGTGACTCAGGACCT
          GACAACTGTGGAACTCGTCTGTGACCGAGTGGTTGTAAGACAGCCCCGTCATTCGGATGG
          GATAACTGTGGAGCACCTCTGTGATCGATCGGTTGAGGGACAGCCTCTTTATTAGGATGG
          AATAACTGCGGAACCCGTTGGCGATCGAACGATTGTAGGACATCCTCTTCGCTCAGATGG
          GATAACTGCGGAACCCGTTTGCGATCGATCGGTTGTAAGACAGTCTCGTCGTTCGGATGG

          CGCCTAACGAATTAGGCTAATTACGGCGAGCCCTACGGAAGCTAACTCTAAAAATAGCAC
          CGCCTAACGACTTAGGCTAATTACGGCGAACCCTACGGAAGTTGACCCTAAAAATAGCAC
          CGCCTAACAATTTATACTACATATGGCGAGCTTTACAGAAGTTGACTCTAATAGTAACGC
          CGCTTACCAATTTCTACTATATATGGCGAGCTTTACAGATGATGACTCTAATAATAATGC
          TTCATCCCGGATTTGATCAGCACCACTGATACTGCCACGCGAGAGTTACTTGAATGGTAA
          TTCATCCCGGATTTGATCAGCAGCACTGATACTGCCACATGAGAGCTACTTGAATGGTAA
          TCTGTCTCGGATCAGATCAACAGCACTGATACTGGCATATGAGCGCTACTTGAATGGTAA
          TCCATGCCGGCTCGGATCAGCAGCACTGATACTGGCACATGAGAGTTAATTGAGTAGTAA

          ATGGGATCCCTTCTCCAAATGGCCCGTCTCCCTGAAAGCGGCAGCTGTCATGATTATGAT
          GTTGGACTCTTTCTTCAAATGGCCCGTCTCCTTGAAAGTGGCAGCTGTCATGATCATGAT
          ATTGAGTCATTTCTCCTATTGACCCGACTCCTTGAAAGCAGCGGCTATCATGATCATGAT
          GTTGGATCCTTTCTTCTAATGGCCCGGTTTCTTGAAAGTGGCAGTTGTCATGACCATGAT
          ATGGCCTTTCCCTGGCGGTAACTCGGAGCATTTCTTCAGGGCGTCACTGTACGCAAACGC
          ATTGCTTTTCCTCGGCGGCACTTTGGAGCATTTCTTCAAGGCTCCACTGTCCGCAAATGT
          ATCGCCTCTCCTTGGCAATAACTCGGAGAACTTCTCCATGTCTTCATTGTCCACAAACGT
          ATCACCTCTCCTCCGCGGTAATTCGGAGCACTTCTTCCAGGTTTCAGCGCCCACAAAAGT

          CAATCATATCCAATCGCTTTAGGTTGGACCGTACTATGGAACACGCAAGCCGGCACGTTC
          CAATCATATCCAATCGCTTTAGGCTGGAACGTACTATGACACAAACGAGCCGGCACGTTC
          CAAACAAGTCCGATCGCCCTGAGTTGGGACGTAGTACGCAATAAGCCAGCCTGTACGTTC
          CAGACAAAACCGATCGCCCTGGGCTGGGACGTAGTACGCAATAAGCAAGCCGGTACGTCC
          GGTGCTCTAACCTGCGCGCCCTGACGTTACTAAATAGGATACGGGGACCGGGGTAGATAG
          GGCGTTCGAACCTGCGCGCTTCGACGCTACTGAGTACGATACGAGGACAAAAGTAGATTG
          TGTATTCGAACCCGCGTGCTTCGACGCTATTGATTACGACCCGAGGATCAAGGTGGATAG
          GATAAACGAACCCGCGTGCTTTGGCGCTATTGCTTACCACCGGAGGATCAAAGTAGATAG

          TTCGACCATTCGTCCCGCGCAGCGTGCCGTAGTACCGCGCAAGCGTTGACTTAAATAACT
          TTCGATCATTCGCCCCGCGCAGAGTGCCGTAGTACCGCATACGAGTTGACTTAAATAACT
          TTTGACCATTCGTGCTGCGCAGTGTCCCGTAGAACGGTATACGAGGCGACTTAAATAACT
          TACGGCCATTCGTGCCGCGAAGAGTCCCATTGTACTAAATATAAGTCGACTAAACTTACT
          CGCTTCCCGCCGGTAAGTTCGTGATCTAGCGACGCACCATCGGCACATGTGTCCCCGGCC
          CGCCTCCCGCCGGCAAGTTCACGATCTAGCGATGTGCCAACGGCATATTTGCCCTCGACC
          CGCCTCACGCCGGTAAGTTCACGGGCTGGCAATATATTACCGGCGTATGAGCTTCCGACC
          CTCCTCCCGCCGGTAAGTTCACGGACTGGCGATATATTATCGGCGTATAAGACCTCGACT

          GCGAGGTACCGCAACCCATGATATCCGATTTCGAATTTTGCTTTTCGTATTATCTGATAG
          GCGACGCACCGCAACTCATGTTTTCTGATTTCGAATTTGGCTTTTCGTATTATCTGATAT
          GTGAGGTATCGCATCCCCTGTATTCAGATTTCGAATATGCCCTCTCGTACTTTCTGATAC
          GTGAGGTATCGCAACCCCTGATTTCAGATTTCTAATATAGTTTTTCGTAGTTTTCGATAT
          ACGTGACATCACCACCGCCATTATTGGATGTTATGCCGACTCCAGCGTATATTCAAATAT
          GCGTGACATCACCACCGGCGCTATTGGATGTTATGCCATCTGCAGCGTACATTCAAATAT
          GCGCGACGGCACCATCGACACTATTGGATGTTGCACCGTCTACAGCGGACAATAAAGCAT
          GCGTGACATCACCACCGACACTACTAGATGTTGTGCCGTTTCCAGCGCCCAATTAGGTAT

          ACTAATTTTCCGTTGGACACATGTAACAAATGCGAAACGGCTACGTGTAGCAGATTGCAC
          ATTAATTTTCAGTTGAACACGTGTAACAAATGCAAAATGGCTACGCGTAGCAAATTGCAC
          TCTGATTTTCCTCTGAATACGTGTTACAGGAGGCGGATAGCTACGCGTAGCATGTTACAT
          TCTGATGTTCCGTTAAACACGTGTTGTAAGTGGAACGTTGCTATGCGTAGCAAGTTGCAT
          CGCGGCTGCGCTACCAGCAAATCTTGAGACTGTGCGAAACCCTCAGGTATAAAATAGTCT
          CGCGGCTGCGCTACCAGCATATCTTGAAAGTGTGCGAAATCCTCAGGTATAACACAGCCC
          CGCGGCTGTGCTACCAGTAGATCCTGAAAGTATGCGAACTCCCCAGGTACATGACAGCCC
          CGCGGCTGTGTTATCAGCAGATCCTGAAAGCATGCGAACTCCCCAGGTACAAGAGAGCCC

          AGCTAAGCAATGGAATCACCTTGAAAGTGATGTCGGACCGTATGATTTCGAACCAGCCAG
          AGCAAGGCAATAGAATCACCTTGAAAGGGATGTCGTACCATATGATTTCGAACCATCCAG
          AGCATAGCGATAGAATCGCCCTGAAGGCGATGATAGTCCGTATGATATCGAACCATCCAG
          AACATAACGATAGAACCACCTTGAAAGGGTCGTTAGACCATATGATCACAAACCATTCAG
          TACATCATGACATAACGGCATCGTACTAGAACGCATAGTATCAGAAATTATATTTACAAG
          CACTTTATGACACAATTATTTCGTACTAGAACGCACAATACCAGAAACTAGCTTTACAAG
          CACATGATGATTAAACCACCTAGTACTAGAGCGTATGGTATCAAAAATTAGCCTTATAAG
          CACATGATGATAAAACCACCTCGTACTCGAGTACATAGTATCGGAAACTAGCTTCACAAG

          TAAGGTATCATCATCGATATGGGCGACCATGGTTAGTGGGTGGCATGCTTAATTAGGAAC
          TAAGGCACCATCATCGATATGGGCGACCATACCTAGTGGGTGATATGCTTAATTAGGATC
          TCAAGTTTCATCATCGATATGGGAGACTATAATTAGTGTGTGGTATGCCTAATTAGAAAG
          TAAGGTTTTATTATCGATATGAGAGACCATAATTAGTGGGTGGTAGGCTTAATTAGGAAG
          TCTCGTTCCTGTTCGAATACGACGTACGGCGCGAGTCAATCGATATCTTCAGCGGGACCC
          TCTCGTTCCCGTTCGAATGCAACGTACGGGGTGAGTCAAACGATACCTTCAGCGGGACCC
          TCTCGTTCCTGTTTGAAGACAAGGTACGGCGGGGGTGAAGCGTTATCGTCTGCGGGTCCC
          TCTCGTCCACGTTTGAAGACAACGTACGGCGGGGGTTGAGCGGTACCGTCTGTGAGACCT

          CTAATCCATGCTCCTCCGGCAGATATACACGGGGTGTGTTTCGGTGTCAACGAGCGAATG
          CTAATCCATGCTCCCCTGGCAGATATACACGGGGAGTGTTTCGGTGCCAACGAGCGGTTG
          CTAATACAAGTACCTCTGGCAGCTATGCGCTGGCGGCTTTTCGGTGGCAGCGAGTGATTG
          TTAATATACGCGCCCCTGGCAGGTATGCACTGGGAATGTTTTGGTGGCAACGAGCGACTG
          ACAACACGAGGTATTGCACTTACTACACGCCTCAACCGTCATAGTGGCGAAAGGCTTCCG
          ACACCACGAGGAATTGCACTTACTACAAGCCTCAACCGTCATAATGGAGAAAGGCTTCCG
          ACAACATAAGGACCTGGACTTACTACGTGTCCTAATCGTCATAGTGGAGAAAGGCATCCG
          ACAACATAAGGACCTGCACTTACTACATGTCCCAATCGTCATAGTGGAGAAAGACATCCG

          CGGCGTAAACCTAATGGATTCTAGTCCCGTATCAGGTCTCAATCTTGTTGGGGAATGAGA
          CGACGTAAACCCAATGGATTCTAGTCCCATATCAGGTCCCAATCTTGTTGTGGGATGAGA
          CAGTGTAAACCCAATGGATTCTAGCCCGATATCAGGTATTAGCCCTGTTGTGGGATACGG
          CGGCGTAAACCCAATGGGTTCCAGCACGGTCTCAGGACTCAGCCCTGTTGTGAGATAAGA
          AACTAATGCAATGTACCGAGATAGTGCGCTATCTTTTGCCGGGGTAGATTGTCTCCAAGC
          AACTCATGCAATGTACCGAGATAATGCGCTGTCACTTTCCGGGGTAGATTGTTTCCAAGA
          CGCTGATACAATGTACAGAGGTAGCGCGCTGCCTCTTCCCGCGGTAGATTGTTTCCGAGA
          CGCTCACACAATGTACCGAGATAGTGCGCTTTCTTTTTCCGGGTTAGATCGATTCCATGA

          GCCGAACACTTCGGGGTCTATGCAACCAGCGAACGCAACGTGGTGAGAATGTGAACTACG
          GCCGAACACTTCGGGGTCTATGCAACTGGTGAACGCAACGTGGTGTGAATGTGAACTACG
          GCCGGACACCTCGGGCGCTATGAAACAGACGAACGCAACGCCGTGAGAACGTAAACTCTG
          GCCGGACACCTCGTGCCCTGTGAAACAGGCGAACGCAACGCGGTGAGGATGTAAACTCCG
          ACAAAAGACGAACAACGCTGTAGGTTGGGAGTAAATAAGCCCTCATCTTAAGTAAGTCTT
          ACAAAAGACGAACAACGTTTTAAATTGGGAGCAAATAGGCACATATCTAGTGTAAAACTC
          TCAAAAGATGTACAACGCTGTAAGTTGGGAGCAAATAAGCACGAATTCTAAGAGAAACCT
          ACAGAAGACGAACAACGATGTAGATTGGGAGCAAATAAGAACGTATATTAAGGACAATAT

          CATTGTTATGGAGTACTCGCGGTACCAGGCACGTTGGAAACCACAGTCAAACTTTCCTGG
          CATTGTTATGAAGTATTCGCGGCGCCAGGCACGTCGGAAACCACAGTTACACTTCCCAGG
          CATGGTTATGGAGTAGTCGCGGCGCCAGGCAAATTGGAAACCACAGGTCGGCCTCCCAGG
          GATTGTTATGGAGTAGTCGCGGCGCCAGGCAAGTTGGAAATCACAGGTCGGCTTCCCAGG
          TACTGAGCCAACTTCTGTGTATCCCTAGGTCGCGGAAATGATTAAGCTAGCGCACTCTGG
          TACTGAGGTAACCCCTGTGTATCCCTAGATTGAGGAAATGATTAGGCTTGCGCACTCTGG
          TACTTAGGTAACGCATGTGTATCCCTTGGTTGTGGAAATTATTAGGTAAGCGCGCTTTGG
          TACTGAAGTAACGCCCGTGTATCCTTAGGTTGTGGAAGCTATTAGATTAGAGCTCTCTGA

          AACCACACGAAGACACTAGTCGGCCCCGAATACTCGTTGC
          AACCACACGAAAACACTAGTCGGCCCCGAATACTCGTTGC
          AAACCCATGAAAGCACTAATCGCCCCCGGACACTTGTTGT
          AACCATATGAATGCCCTGATCGCCCCCGAACACTCGTTGC
          GACTCTATCATGTGTTCGGCTCCCTCAAAGAACTTATGAA
          GACCCTATCATGTGTTCGGCCCATTCAAAACACTTATGAA
          GACCCTATCATGAGCTCAGCCCCTTCGAAACACTTATGAA
          GACCCTATAGTGCGTTCCGCCCCTTCAAATAACCTATGGA

