 8 1000
t1        AAATTCGGGCTATACAAGGCCATGGACTCTCACCACCTCATGGACGGCCTCAATTCCCCA
t2        AGATTCGGGGTATACAAGGCCATGGACTCTCACCAACTCGTGCACGGCCTTAACTCTCCG
t3        TAATTCGGGGTGTACATGGCCACGGACTCTCACCACTTCATGGATGGCCTCAACTCCATA
t4        CGTGCGTGGATGCCCTGCCCCTTGGGCCATCAACGCTCCACGGTAGATCATAGTACTCTC
t5        CGTTTGTAGATAGTTAAGATTTCAGATTTACGTTTGCCATGCAGCGAGGATAAAATGGCC
t6        TATAAAATAGTGATCTAGCGTTTCGAGACACATTGATATATAAACGACCACAACGCCGTA
t7        TGCGTAGCGTAGCGACAGTCACCCGATCCCCACTGTCAAATAATTGTGCATAGTCCCAAC
t8        TATCGGAGGGCCGGCTGGGGCATATACCCTCGCAACTATTTGGTCGACTTACGATGCCAC

          AATCGAAGGAGGTTACGTCGGGTCTGACCGAGCAAATGCTCATGGCTTATATGCGCGCCT
          AATCGAAGGAGATCACATCGGGTCCGACCGAGCAAATGCTAAAGATTTATATGCGCGCCT
          AACCGAAGGAGCTAACACCGGATCCGACCAAGCACACTCTCGTGGCTTATATATGCGACT
          ATTCCCGGGTACCTAGATTAGGCCCGATCGAGCGATATAAGGTGATTCGTATATGTGGTC
          CTCTGCGGAGACCGGCATTACGCTAGGCCAAACAAACTGAATAGGTAATCCCACAACATC
          TATCGCTTGGTGCAATATTGGGCTCTGACCAACGTAGTCAGATCGGGCTCTTGCGTGGCC
          GTCGACACCAACTCTTCGCAAGATGACCTGATCGTGAGCGATTCGCGTATCGTGGCAACC
          ATCTGTCTGCTACCGACATGTGCAGACAGGGGGCTCAAAGGCTAACGTCCCTAAAGGGGT

          CTGCTAAATAGAAATTGAAAACTTATCGGGTTCTTGCTGCCATTGGACTGCTTCTTGATT
          CCGCTAGATAAAAATTGAAATCCCATCGGGTTCTCGTTGCCACTGGACTGCCTCTTGATT
          CAGCTGGATAAAAATCGAAAACTTAACGGGTTCTCGTTACCACTGGACTGCCTCTCGATT
          GTCCGGAACAAGAATAGAATGTTCGTTGAATGACCGCTCCTATCAAGTGCCTTGTTAAGC
          TTTCGAGTCCCAAACAAAGTATCCCCCGACGGCTTGTCCTTCCTGACGGGCCTGCGAATC
          CGCAGCGACGAGAATAAAAAATTGTCCGGTTGCCTTTCTCCGCGGGCTGGCGCCAAGATC
          CCTGGGGTCCTGGTATATAACGCGTTTGATCTTTTGGCCTGTCCCATAGACTCATAAGGT
          TCTTGAAGTCACGCCTGTACGATCTTCTGAGGTCAACCATGTTCCGGCAGGCGAACATTC

          TTACTATTCACACACACAGGGGACGAGTACATAAAAGGTTAATAATCGGCGTCGATGTTT
          TTACTATCCACACACACAGGGGACGAGTACATAAAAGGTTAATAATCTATGCCGCTGTTT
          CTGCAATACACACTTACAAAGGACGAAGACATAGCAGGGCAATAATCTACGTCGAAGTTT
          TTGTCGCCTTAATAAGGAAGCGGGGAGGACACATGGAGAACACGCGCCGTTCCGGTGTCT
          CAGCAACCATCATACTCCATAAGAGGGCGGGGCAGAAAAGAGTAGACTTCTTGTATGTTA
          TCGCAACTTTATCACGATGTGTGCAAGAGTTCACGACTCGAGCATGTTACTCCGGCGCAC
          AACTAACCTCCACTATGCAGAGAACTTGACGTCCACTACGTTCATGATACGTCATCTAAT
          GTACAGTCAAGCTCTCGTGACAGAACTGGCGGACGAGATGCTCAAGTTCCTAACCTAAGT

          CTTATAAGATTATTTGGCTGCGCGTCCACCAGCTTTGCCCTAAGCAACTGCCGGGATCCG
          TTTAAGAGATTATTAGGCTGTGCGTCAAACATCTTTGTCCCAAGCAACAGCGGGGACCCG
          TTTAATAGGTTATTAGGCTGCGCGTTCAACAGCTCTAACCTGAGCAGCTATTGGGGTCCG
          TCCAAAACGATAATGGGGTGTTCATTGTTCTCCGTTAGTGAAAGCAGTTATACCAATCTG
          TTTCTCGCGTCCATAACGAGCGGCTTGACCCCCATCAGCTGCCACATTACTAACCAATCG
          TCCAAAGAGTTAATAGGTTAGTCCCTCACCGGTCCTAGCCAACTCGGTTCCCCGAACCAT
          CCTGTAGGGGAAGACGAATGGCTACTGCTTGGTAAGTGCGCGGGCGATTTTCCGAACATA
          GCTGGAGTCACAACTCAATGTTACCTCTCGTCCGCTAACCAGAGTGGTTCTCCGCCATCG

          CGAGGCTCGCCCCCGAAACCTTCTTTCGAGCATGTTCAGGGGCTACCCGATATGAAATCC
          CGAGGCTCGCCACCGAAACTTTCTTTCGAGCATGTTGAGGGGCTATCTGATATGAAATCC
          CGAGGCTCGCCGCCGGAATTTTCTTTCGCGCAAGTCGCAGGGTTATCCGATATAAAATCC
          TCATCTCGGCGTTTCTGAACATTGGTCGCTCATAGCGATGAAGCTACCGTGCTTGCGTCT
          CTAACAGGTCTCCCGAAAACCACTCTTACACGCCACGGTGCGTTCAGGCCGTCCACACGC
          CCGTATCATTTTCTACGTCCTACCCTTGAGTCAGACGATAGGTGAACCTCGACTAGTGCT
          CCCCGCCTCGTTCAGGGGGGCTCCTGAGGATGCGGCGCACGCTCCAGTGTGATTGGTATT
          TAAGAACACTTTACGAAGGGTTGTAGTGTATGGTTCTGACAGCGATCCATTGATCTGCTC

          GCCCGGAATTTGTTCGACTAGCACCTAAGATAAGTGTCACTCGAGGTTTGTCTTTCCCGT
          GCGGGGAATTTGTTCGACTAGCACCTAAGATAAGTGTCACTCGAGGTTTGTCTTTCCCGT
          GCGAGGACTTTGCTCGACTAGTACCTAAAATAAGTGTTATTCGGGGTTTGTGATTTCCGT
          GCGACAATGACGCTAAATCGGTTTGCGAGGCGGATGCTTCACTGGGGCTACAAATCCTTT
          ACAACAATACTGCACGAACGGCACCAACCATAGCTATCCTTTAAAGTCAGCAGTGCAAGC
          GTGAGAGCATCTACTGGGTGCCTCGTGTTATAGCCACGGCTTACAAACCGTCGCTTCAGG
          GTAACAGTTCTTTGTAGGTGAAACTTGCAAAAACTTCGCAGCCACGGTTAGTGAGTCTTT
          CTGGAGCGCCGCTTTGGATCCTCGTAGTGCACGCCTCACGTCGTAATCCCTCGGACCTCT

          GCCAACGCAAGATGAGCTCGAATTTACTCGTCATCATTTTAGACGCACAACACAATTCTA
          GCCAAAGTAAGATGAGCTCGAACTTACTTGTCTTCATCTTAGATGCACAACACAATTCTA
          ACCAGCGTATGGTGAGCTCGACCTTACTTATGATCGTTTTAGATGCATAACCCAATTTTA
          GCTTGGCGACAGTCGAGTTGGCCCGATATGCAGTTTTGTTAGAACCCTAATAACATGCCA
          GTCTACGGATAATAGACTTGGTACGGCCGTCAGTACGATCAGACTTTAAAAATTCTTTCA
          GATAACTCACTTCGCTCTAGGTCTCATTCGTCGCTGTGCTTAATTCGTACCGACCTGCGA
          ACCCGTGCGAGATCATTCCGACTACAATCAAAAAGTTGGTCAACTCGGAGATAAGTGCTG
          TCTACTGCGGAGCGACCGAGTTCCGACTCGGTAGCAAACGTCACTCGATGGAGCATGGTA

          ATGGTCGATCGCTACCGGACTGTTCGGCGGCCCAAGATTCGCTACGGGACAATGACTGGG
          ATGGTCGATCGCTTCCGGACTGTCCGGCGGCCCAAGACCCGCTACGGGACAATGACTGGG
          ACGATCGATCGTTACCGGACTGTTCGGCTATCCAAGATTCGCTATGGGACAATGACTGGG
          ACCGCCGACTGCCCGCACGTTGTCCAGGGGCCTCAAACGAGTTGCGAGGTAGTGCCAGAG
          CGAACCCCCTGTCCCATTACAGTGCGGCCGCACTAGCACGATACGACGTCCTTGTTAGAC
          GCGGCTAATTGGGCTTTTACTGCCTGGAGTTTCGAGATACTTCACGCGTCGACGGCACCG
          AACGCAAATCACATTTCCACGCTATCTGAAATCGAGCCCGATTCGGAGTGAGATCCTGTG
          GGCGTGAACTGCCCAATTGTTGCCCTGATGTTCAGTGCAAGCCTTGTGCTTGAGTTTGAG

          GCACGTGCTGGGAAGAATCAGTGCTCGGCCCATAGTCAGAATTTGAAGGGGGCTGGAGAC
          ACACGTGCTGGGAAGAATCAGTGATCGGCCCGTCCCCAGAATGTGAAGGGGGCTGGAGAC
          GTACGTGTCGGGAAGAATCAGTGCTCGACTTGTCGTCAGAACACGGAGGGGGCCGGAGAC
          GTATGAGTCAGAGAGGACTGGTACGAGTTACAACGTATGGGCTCCAAGGGGACCGAAGAA
          GCGGGCGTCGGCGGAAGTACTGGTTTCGATTAACCATGGAAGTCAAATGCAACCCCAGAA
          ATTGTCTCCGTGCTAACACCGTGCTAACTACGTTCTACGTGCGTATCAGGGGTCACAGTC
          CTGCAACCCCGGGTGAATCTAGGTACGGCTTGAACAAGGAGGTAAGCTGGGATTGGGCCA
          CTATGCGAAGTGTCCGACATCAAGAAAAATCTGTACCCATAATATGATAGCATGCGTACC

          ATCTACCAGAAACACAAGCCTTACAGTCTGCATCGGCGCGTTTCGTAGGCACCCACTGGC
          ATCTACCAGAAACACATGCCTTACAGTCTGTGTCGGCGCATTTCGCAAGCACCCATCGGC
          ACACATCAGAAACGCACGCCTTCCAGTCCGCGTCGGCGCATTTCGTAAGTCCCCACCGGC
          TCCTACCGGAAATAAACGCCCCTCGGTCGATACTGACGCATTCCGCATTTACCCTATGGC
          ACCTGATCAGGACATGTTTCTCACAGCCCACAGTGCTGCAACTATAGTTGGTCTACCGGT
          AACGAGCTCTGACAAAGTCCTTTCAGCTAGCCAGGGTTCACTTATGAGCTGTCTTTTTGC
          CGTACGGTCAGGCAAACCAGTTCTGACGTCTACTGGCAACACCTAATCCGCTGTCCTCAG
          GTAGATCGAAGAGACATCCTCTGTGGACCGCTCCGACGTGCGTGGGGGCCGAACCGGCAC

          ACTCAGTCTTGCACCCGACATCAGGAGTGGCAGGGAGCAGCAACAGATCCCACCAAGGTG
          ACCCAGTCTTCTAACCGTTATCAGGAATGGCAGAGAGCGACAACAGGTCCCACCCAGGTG
          ACTCAGCCTTGTACCTGATATTAGGCGTGGCAGGGAGCGATAAGAGTTCCCACCCAGGTG
          ATATCGGTTCGAACGTAACACAGTGAGTGTCAGGGTATTAAAAGGGATATCATATTCACA
          GCCTGACGAACGCTCTCCCGCCGTAAACGAAAGCTTACCTGATCATATGCTACCTCATTG
          CCAGTATTCAGAGTCAGACTCTGATTGCTATGGATCGTCAGGGTGACCGTCGTGTCGGTG
          GCCGAGTTTAGAGAACAGTCTAATAGATCGAGAGCCCTGAATCCGGCTGTCACAGAGGAT
          ACCGCCTGAGGCGCTCATTGTCAAACATAACAGGACACCACTTCCTATAACGCCAATCTG

          TTGTTTAATCGTGCGGGGAGTTCGACCGCTTCGCACGAAATCATGAGTGGGTGCCAGACC
          TTGTTTAATCGTGCGGGGAGTTCGACCGCTTTGCACGGAATCATAAGTGGGTGCCAGACC
          TTGTTTAATCGGGCGGGGAGTTCGACCGCTTTGCACGGAATCATAAGGGGGTGCTCGGTT
          GTCATCGGACACGCGGAGAGGTGAAACGTCTTGTCCGATGGTTCACCGAACCGCCCGTGG
          CCTGTGAGCACTGTGGCACACAGCGCTTCTCTCCACGTCTATATATACAAATCTTTTCGC
          GCAAACATCAGTGCGGGGAATTATGCCAACCAACCTGCTAACGCAAGCGACCGCCTACGC
          CTCGACTTGGGCTTCGGCAACAGCCGTACACAATAAGGAACCAGCGCGCAACGATAGAGC
          GTCGGCCATCTTGTGGGGCAGCCAGACGGACTTTTCCCATAGAAACTTGAACACGGATCC

          AACTACCTTATAGGATCGATGCTAACTATAGTATGGCAATAGACTTAAGTGCGAGGACTC
          AACTACCTTATAGGATCGATGCTAACTATCGCATGGCAATAGCCTTAAGTGCGAGAAATC
          AACCACCTTATAAGATCGATGCTAACTAGAGTATGGCAATAGGCTTAAGTGCCAGGACCC
          AACGATACTCCAAGATCGATACCTATTAGAGCACGGTACCTGGATAAAGATCCCCAGTCC
          GACAGCCCAACATGACGGACACCGTCCACTGCGGTTAAAAATGTAGTGCATTGTGCGCTT
          GCTCATTCTACTTAAACGCTCTCGATCGCCAAGTAGGTACACACTAATTTAACGGCCTTA
          TATGATGATCTGATACCAACCCCAGCCCTTATTTGAGTGTTCGCTGAGGTTACCACGCTC
          GCTTGTCTCATATGACCAGGTCTGATTGTTGCGCAACTACATACTAGGACCAACAAAATT

          ATCAGGAGGAGCGGAACAACACTTACCACAGTCGTGTTCTGGGGTTTGACAAAAGGTGTC
          ATCAGGAGGAGCGGAACAACACTTACCACAGTCGTGTTCTGGGGTTTGACAAAAGGTGCC
          ATTAGGAGGTGCGAAACAACACCTATCACAGTCGTGTTCTGGGAGTTGACACAGAGTGTC
          ACAAAGCAAAGAGGACCGGCTCCCTCCGACCCAGTTCTGTGGGACTTGATAAAGAGGGAA
          AACCAGTAGAGTGACTCTACCTACGTTCGACCAGTGAAGTGGTTAATCGTAGGATGCATT
          ATGAGGGGATTAGGTCTAAAACCCGCTATGATGTTGCATTGGTTTTCGACAAAGATCGAT
          GTTTACTTGGGATAGGGACCACCTGCCTTTTCATAGAATTTGATGAGGACCGGGCATATC
          GCGGTGGTGCAAGAATTACCCGTTCTCGTAGGGCCGACTTGGAACCTAACAGAGATAGCT

          AAGGTTCTTAATGCTTCGTCGTGCCGGGTAGTATGAGTCGTTACGACAGCGGAACAAGCG
          GAGGTTCCTAATGCTTCGTCGAGCCGGGTAGTATGAGTCGTTAGCACAGCAGAATAAGCC
          TTGGTCCTTAATGCTTCGTCCCATCGGGTAGTATGTGCCGGCACGACAACGGAACACGCG
          CTGCCTGTTAACGTGTCACTAGGGCCGGCTATCACGGTCCCTCCCATTGTGAACGGGAAG
          TTACTTGTCTAGGGATTTACAGATTCGTTGACCTAGCTCATTACGTAAGCAGATCAAAGT
          CCACGACATCTGTTTTCACCATGGCTGCTTCCCCAAAGCGCTAACACAATTGACCGTACG
          CCGTAGGGCCCAGCTCGTTTTTGCCTGCTGCGAATGGTCAGCATAACCGAGGTACGCTTG
          CCATGACCGCCCACTCCCACTTGAATGCTGTCTTTGATTCGTGCCCCAGCGCCTCGTGTA

          TTCTCTGCGCATAAGGTCCGAATTTGCCCGCTGAGTGGCA
          TCCTCTGAGCATAAGGTCCGAATCTGCTCGCTGAGTGGCG
          TTCTCTGCGCATAAGGTTCAAATATGCCCGCTGTGTCGTA
          TCCTCTTTACACAAGAATGGAATTGTTGAGCAAAGCGTCC
          ACTCATGAACACATAGGTTGAACTGATCAATTGAGCGCCT
          CTTTAAGGGAAAACCCTTTGGACTAGGTGACCGAGGATTC
          TTTCATAACAGTGCTGGTCGCGTCAGGAGATTAGAGGCTC
          CGCCTCGAGAGTGTGACCATTCGAACGGGGTTAATAGTTC

