 8 1000
t1        ATCCGGCAGTGTCCACTCGTAAAACCCTACGTGAGCTGCTGTATGACGTAAGGCCAGTTG
t2        ATCCGGCAGTGGCCACTTGTAAAACCCTACGTGGGCCGTTTTATGACGCAGGGCCAATTG
t3        TTGCGGCTTTGGCCACACGCAAAACCCTGCGAGAGCCGTTGCATAACGCAGGGCCAATTG
t4        TTGACGCATTAGCCAGACGTAACACCCTGCGAGAGCCGCTGCATGGCGCAGGGCCAACTG
t5        TTGTGAAATTGGCCAGGCGCAAAGCTCAGCGAGTACAGCTGCACGAAGCGGAGCTAACTG
t6        TAAGGACACCAGTCAACCGTAAGGACACCTAATATTAGTTCTGAGGTTCAGAGTTCATTG
t7        GCCGGAACAGCGCTATTGGTGGGGGGCTCGATAAAAGGGCGCAGCAAGTGGAGGACCGCG
t8        GAAAAATTTTCCGCATAGACAAGCCGCCATGATGACACTGGATTATGCCAAGGCCGCGTG

          TTCGCTCCAAAGATCCGACTTGACCCCCAACATGTACATTGAATAATCACAGAACGCACG
          TTCGCTCCAAAGCTCCGATCTCACCCCCGACATGTATATTGAATAATCACAGAACGCACG
          ATCGCTCTAAAGCTCCGAATTGAGCCCCAGCATGTGTATTGTACCATCGCAGAACGCACG
          ATCGCTCAAAAGCTCCGAATCGGGCCCCAACATGTATATTGCATAATCACAGAACGCATG
          TTCGTCCAAGGGCGCCCAACTGAGTTCCAATATATATATTAATTAATCCATGATCGGATG
          ACTGCTAAAGAGCCGGTCACTACGCTGGGAACTGACAAACAGATAGCAACAAGATCACGG
          TTTTGTGAACGTCCCGGGATCGTCCCGGAGCGCACGCGCGGAGCCGATCGCCGTCTATGA
          AGCAATTATTCTATCGCTAGACTGATCGAGTTTGACGTCAATCTTATCATGGGTGGTGCA

          TACGAGGACAGTTCCTGCACAATTGACTGAAGGGATAGTCGCTACATAAAGATTTTCCTG
          TACGAGGACAGTTCCTGCACAATTGACTGAAGGGATAGTCACTACATAAAGATTTTTCTT
          TACGAAGACAGTTTCTGCACAATTGATTCAAAGGGTAGTCACTACATAACGATTTACCTT
          TACGAGGACAGTTCCCGCACAATTGACTGAAAGGATGGTCACTACATAAAAATTCGCTTC
          AACTGGGATGGTTTTTGTGTGATTTGTCATGGTTATAGTCGTCGAACACGAGTTACTCCT
          CACAGGTACTGTCTATCCACGCATACTTAAGGGTGTACTTAGTAACTGAGCGCTTCTACC
          TGGGGGATCGGTCATTTCACAATCCACTCCAGGGCATTAGAGCAGACAAGGGATATCAGA
          TCACAAAACGAAGTCTTTCCATTTGTTTTGGAGTCGGAAGAGTACGTGGGAAGTAGTATG

          TGCAATTCAAATCCACTTTGGTGTACTCCAGGCGTTCCGTGGTGAGGTATGTTGGATAAG
          TGCAATTCAAACCCACTTTGGTGTACGCCAGGCGTTTCGTGGTGAGGTATGTTGGACAAG
          AGCAATTCACACCCACTTTGGTGTACTCCAGGCTTTCCGTGATGAGGTATGCTGAATAAG
          AGCAATTCAAACCCACTTTGGCGTCCTCTAGGCGTCCCGTGATGAGGTATGGTGGACAAG
          AGCACGTCAACCTGACCCTGGTGCACATCAGACGTATCATGACGTGGCATACTGCCTAAA
          CGTCATTTCGAACCACAACGGGGTACAATAAGGATGACCCTAAGACAATCTTAATTTGAA
          TCAAGTGTCAAGTTAATGCACGGTATGGCACGCACCAAGCACCTAGGCCTGTCGGCTGGA
          CCCCGCCAACGAATCCCGGAACATTCCCAATGACCAAAGGCAGGTACAAGGTCTCTGCCA

          AGATACATACTAAGACATAGAAGTTTCACGGAAGCGATAATCGGGCGTCATCAGCTCGGT
          AGATACTTACTAAGACGTAGAAGTTTCACGGAAGCGATACAGGGGCGCCATCAGCTCGGT
          AAACACTTGCTAAGGCGTAGAAGTTTCACGGAAGCGATACTTGGGCGCCATCAGCTCGGT
          AGACACCTTCTAAGGCGTAGAAGTTTCACGGAAGCGACAATTGGGCGCAATCAGCCCGAT
          AATAAATTACTATAGAGTAGAGTCTCTATGGAAGCGATAATCAGGTGTCAAAAGCCCAAT
          AAAAGCTCCCAAGGTTGCAGAGCTCCCACGGACAGGGCGGCATCGTGCTAGCGTTCCCGT
          AATGTTTGCTCGAATAGAGGACAGATTATAACAGCATAACTCCTAAACACGATCACCAAG
          AATCTTCCTACAAGACACCGATTGGTAGTAACGTTTACGATCACCCTGTCACTGCTCGCA

          TGTGATCTCATCCCTATGGGTCTTACCGTTAACTGTGCGAGAAATGGCGAAGGGCGTCCT
          TGTGAACTCATCCCTATGGGTTTTACCGTAAACCGTACGAGAAATGACGAAGGACGTCCT
          TGTGAACTCATTTCTATGGGTCGTACTGTAAACTGAACGAGATATGGCGAAGGACATCTT
          TGTAAACCCATCCCTATGGGTCTTACTGTAAACTGCACGAGCAATGCCGAGGGGCGTCCT
          TGTGAGCCCACCCCGAAGGGTGTTCTTGAAAACAATGCGAGACGTATCTAAGGGCGTCTC
          AGGGCTTTAACCTTTGGCACTTTTGTTGATAACTGTACGGTTGGTGGACACCGGCCTCCT
          CCACCGAAGACAATCAATGGTGCATGGAGCTTCCGCGCGTTCGCTGAAAAGCGATCGGAT
          CAATTACAGACCTCTGTGGGCTAAGGTGATAATTTAACTTTCCGCTGTTAAAAGTATAAT

          AGGGCGTTTATCTATCGCCTGTGTGCCGTTCAGGGCACTTGCCGCTAGGGACACGCTAAG
          AGGGCGTTTATCTATAGTCTGTGTGCCGACCAGGGTACTTGCCGCTGGGGATACGTGCAG
          ACGGCGTTTGTCTACAGCTTGTGCGCCGTCCAGGGCACTTGCCGTTGGGGATATGCTCAA
          CCAGCGTTTGTCTACGGCTTGTATGCCGTCCAGGGCACTGGCCGCTGGGGATACGCTTAA
          CCGGTGACTGTCCCCAACTCATGTACCGACCAGGGCACAAGCTCCCGGGGGCATCTCCGA
          CCCGGGGCTGTCTCTCGCAAGTTCGGCCGCCAAGGGATTGACAAACAGTGTTACGCACTG
          AGGAAGTCGCTATTTAGAACACTAACTGGCCGAATCGGGAGCCAACAAGATAAGCTCTAA
          AAGGGTACGGTAGTAGACACGCAAACCGAACAGGATACGAAACTGTACGACAAAATCAGA

          CGACAAAACGGCCAGCCGCGGCGCGGTTCTCTCCTGGGCTACTGCGGCTTGGAGTACTGA
          CGACAAAACGGCCAGCCGCGGCGCGGTTCTCTCCTGGGCTACCGCGACTCGGAGTACTGA
          CGACAAAACGGCCAGCCGCGGCACGGCTTTTTCCCGGGCTACCGCGGCTCGGGGTACAGA
          CAACAAAACGGGCAGCCGCGGCGCGGTTTTTTCTTGGGCTACCGCGGCTCGGAGTACTGA
          TGACATAACGCCCAGCCACTGCGCGATTTTAACTAGGATTGCCGCGGCCCGGAATACTGC
          AGATAAAACATCCAGTCGTAGTGTGATTTTACCTTAGGTAATAATTGTCAAACACAACAG
          AGACTGTACTACTGTGCGACACCCATCCTCAATCCAGGTTGTCGCTCCGGGCTCAGTCGG
          CGATAGGACCCCGAGTTACTGAAGGTTGTTGACGCGAACTGATATGGCTGTGCAACCGGG

          TACGGTTATAGGCCAAGTACCGTGACGGCCCGTATCTCAAGCAGGTATGTGCGTCACATA
          TACGGTTATAGGTCAAGTGCCGTAACGACCCGTAGCTCAAACAGGCATGTGCGTTACATA
          TACGGTTACAGTTTAAGTACCGTGAAGGCCTGTAGCTCAAGCCGGCATATGGGTGACATA
          AACGGTTATAGGCTAAGTACTGTGACGGCTTGTAGCTCAAACAGGCATTTGCGTGACATA
          TACTGTTGAAGATCAAATACTGTGAGGGTCCATAGCACAACGGGGCATCCGTGTGTCATA
          GGCGATTGTGCCTTGCATAATACGTTGATCTAATAACCACCAGCGAACATGTGGGCTGTA
          TGTGCACGCGACTCAGGTGATTGAAAAGACCATAGTTCGAAGTCTCGCAGACGTCTAATG
          CGCAGAACTCAGACATGTTGCGCGGTAACTCTGCACCCCCTTGGATAGTCTAGGTAGCCG

          CATATCACATTTCTCCGTCGCCCAAACCCTATTTGTAGGAGCCTGTAGAGGGGTAACTTG
          TATATCGCATTTCTCCGTTGCCGAAACCCTATTTGTAGGAGCCCGTAGACGGGTAACATG
          TATATCATATTTCTCCGTGACCGAAACCTTATTGGTAGGAGTCCGCAGAGGAGTACCATG
          TATAGCAGGTTTCTCCGTGACCGAGACCTTTTTGGTAGGAGACTGAACAGGAGTAGCTTG
          TATATTAGATCCCTCTGCGACCGATACCCTACCGTTATAGGCTTGCAGGAGAACAACCTG
          CGGATCGGCTTACAAAAAGATGGCAAGCTTACCTTACTGGCACCGTGATGGACCTATACA
          AGAGACGGATTGTATATGGCAGGTAAGCTTTTACCATCGTGCTCATATAGATATGTCGCG
          CGTACTTGACTTAGTGGCATTAGGGTACCCCATCCAACAACCAAATCAGTAGGTATTGCC

          TGGGCGGCGATTACTCTGTATTATTAAGACTATTCTGGAACTCCGGATGACGGTGAATGC
          CGGGCGGCGATTACTCTTTATTATTAAGACTATTCTGGAACTCCTGATAACGGTGAATGC
          TGGGCGGTGATCACTCTTTATTATTAAGACTATTTTTGAACTCCTGATAGCGGTGTATGT
          TGGGCGGTGATTACTATTTGTTAGTAAGACTATTCTGGATCTCCCGATAGCGGTGAATGT
          CGAGCGGTGCTTACTCCTTGCCACTTTGGTTAACCTGGGACTCTCGGTCGCGGCGTAAGT
          CCACTATGGCCTGCTCCCCCTCAATGGGGGAGGACTATGGCTGCCTGAAGGGACGGCAGG
          CTTAATCTCTTCGCCATTAGGTGCCCCAGAGCTCAATACATCCATTATTAAAATGGAGGG
          TTGATCAAGTCTTCCCCGTGTAATTAGAAGAAACTCAATGCGCTTACTAGTCGTTATGGG

          AATATCCTGAATATTGTCCCCTTTGAAAATGGTCTCTCCCTCTATACCGAACGTACTTTT
          AATATCCTGAATATTGTCCTCTTTGAAGATGGTCTCTCCCTCTATACCGAACGTACTTTT
          CATCTCCTGAATATCGCCCTCTCTGAAGACGGTTTCTCTATTACTACCGAATGTAATCTC
          AGCATTCTGAATATTGCCCCCTCTGAAGACGGTTTCTCCCTCAATACCGACCGTGCTTCT
          AAAATTATGGATAGTGCCACCTCTGCAACCGCTTCCTCTCCCTATACCGAGCATGCCCTT
          TATGCATTAGATATTATCGCCCAAAGAGCCCATCCTTTCCTCCCTGGTGGACGCTACTCT
          TTTGCCATCGTATGTTGAAGGCTCTTAGGCCACCGTTGCTTCTCCTTACATCTTCATCCA
          CCTAGTTTGCTTGAGCATTCTAGGGGAATTCACTCCCCCAGGTGCTGGTGTCTTACCCTC

          AGCCAGATAAGCGCATACGGGGCCTCGTACCGACCTTGTACCCATAGCCAAGCCATTATA
          AACCAGATAAGTCCATATGGGGCCTCGTACTGACCTTGTACCCATAGCCAAGCCATTACA
          CCACTAATAAGTGTATACGGGGCCTCGTACCGACCATGTATCCGTAGCCAAGCCGTCACG
          CAACAGATAAGTGCATACGGGGCTTCCTGCCGATCTTGTAACCATAGCTAAGCCATTACA
          TGAAAAACAAGTAAACATGGTCCCCCGCGCAGACTCTGCACTGATAGCTGGGCCATTATA
          GAGTTTGCCCGCTAATATGAAGTGAGATACGGACTATGCCTTGGTAGCTTGGTCTCTTTA
          CGTTGGACATGTATGGGTATATCTTAGTCGTATTTGCCCGCCCAGCACAGCGTTGTCACT
          CGAGGAGATAACACTCCCAGGAGCAACGCGTGGTTAAATGCAGGATAGTGAGTCGTACTG

          CGGTCGTCCTGAAGCGTGATTATGCGGTCGCGTATAGAGTACTGAGACAAATTACTAGAT
          TGGTCGTCCTGAAGCGTGATTTCGCGGTCGCGTATAGATTACTGAGACAAGTTATTAGAT
          TGGTCGCCCTGAAGCGTGATTATGCGGCCGCGTATAGATTAATGAGACAAGCTACTTGAT
          TGGTCGTTCTGAAGCGTGATTATGCGGTAGCATATAGATTACCGAGACAAGCTACTTGAT
          TGCTCGGTCTGAGGTATCCCTCTGCGATTGCACGTAGAGCTCTGAAACAATTTACCTGAT
          CTATCGGCTTCTAGGGACTCTTCATAGGTACTCTTACTAGTGTTCGACAACCCTGCAGGC
          TAACAATATGAGGCATCCGGTTAGTTCCCACGAACCCATTTCCCAAACAATCCTTTCATT
          TGTAACTTAAGGACACCTCAGTCACGCTAAGGTGGGTGGGTTCACGCCGGCGACACTGTG

          GTAATCAGCGCTACGTAACGATCCTCGACTACTAGACGATGCAACGACATACACGTAAAA
          GTAATCAGCGCTGCGGAACGACCCCCGACTACTAAACGATGTAACGACATACACGTAATA
          GTAATCAGCACTGGGGAACAATCCTCGACTACCAGACGATGCAACGAAATACACACAAAA
          GTATTCAGCGCTGAGGAACGACCCTCGACTACCAGACGATGAAACGACATACACGCAAAT
          GCGAGGGGCCCTGAGGGACGATTCAGGATTATCAGTCGTTGCAACGACATGGACGCCAAA
          ATGCACAACGTCACCGCATGTTGCGAGATTATCAAGAAGTACCCCAGCACAGATGTCAAG
          TAGATATGTATCACGACCTGATCAGTCTCCACATCGCAGGCACCATGTACCAGTGAAGAA
          AGGTGACAAAGTAGTGATTGGTGGCTTTTATTTAAGCGGTTAACATTTAGAGACACGAGA

          AAATCTTGAGGCAAACAAAATCCTTGATTTGCAAGCCTTGCTTTGGTGTAGAGCCTTGCT
          AAATCTTGAGGCAAACAAAATCCTTAATTTGCATACGTTGCTCTAGTGTAAAGCCTTGCT
          AGATCTAGAGGCAGACAAAATTCTTGATTTGCAAACCGTGCTCTAGTGTCAAGCATTACC
          AGATCTAGAGGCACACCAAATCCCTGATCTGTAACTCTTGCCATAGTGTAAAGCCTCATT
          AGATATCTGGACAAACATGACCCTTGATTTGTATCCCTTGCTCTGCTGTCGGACTCCAAT
          AGTTGTGGAGCCAAACATGACATTTGACACCAGTACCCTATCCTGCTATCCATCTTCACA
          CGAACAGAGCTCCTAGACTAGGTCGGACCCGCACTGTCAAATATTGTGTCGCCCCCAACA
          GCACAATCGAGTACGGACCTCTCAAAATCAGCAACCCCTGATTAGCGTCCTACACTCACT

          CTTCGTCGACAACCCTAGGTTCACATGACGAGTTCGTATT
          CTTTGTCGACAACCCTAGGTTCACATGACGAGGTCGTATT
          TTTCATCGACAACCTTGGGTTCACATAACGAGATCGTATT
          CTTGGTCGGCAGCTTTGGGTTCACATAAGGAGGTCGCATT
          TTCAGTTAGCAACCATGCGTCAACATAACAGACATCCATA
          TCTCGTCAACGATATTGCGGCAAGCAATTAATCCAACGCT
          TTCGACAGAGAACGGTGGGTCCTTTGTGTGCTGTAGAAGT
          TTCCTCGGACGACTCCGGATCTGGCCAGCAGGTGTATGCT

