 8 1000
t1        GCAAGACCACATGACAAAAAAAATTTTTCTGGTAGCTGCCACAGTTGGGATATTCAGTCG
t2        GCGTTTTCACCTGACCAGAATAACGCAGATCGCAGCTACTACCATTACGTATTTCCACCG
t3        GTGTCCCCACTCAACCAAGCAGGTCCCTTCAGTTCGTCTCAACGCCTCACATTCTAGGGC
t4        GCGTCATTAATCGACCGAGATGGTCTCCAACGTTGGACTCCATGCCTTCCGATCTAGGGC
t5        GCATTTACGCTGGATGTCAAGTACTCCTAATGGCGTCACTCAAGCCATGGGTTCCGGCAG
t6        AGTTTGACGTGCGACTTGAGTTATTCAGAATGTCGTTCCCCTTATCTGGGGTTAAGGTTA
t7        ACACACCTACGTGGTGGGAGTCCCCCTATATTTAGCCTCCCACGCTTGAGGCGTCGGTAG
t8        GCATTACTATGCATTGTGAGTACCCTGATCTATAGCCTTAAGTCCTTATACTTCAGAATG

          ATATAGAAGCCTTTTATGCCTCTCTCGACTCGGTAGTCCTCTAGGTTAGACGACTGGAGC
          CCATAGCCACTTCCATAGCGTACCTCCTTTGGGGGCCGTTTAGCCCTAGACGCCCTCCGC
          TAGAAGCAATTGAAAAACTGTGTACCACTCGCGCAAGCATGCGGGGATGATCGCGGTCCC
          TAGCCGCAGCTGAAGAACTGCGCCCCCCTTGCGCGTACACACTGGGATGATCGCGGATCA
          GGGTTGTCGAGCTGGTGTCAACAAGAAGACTCAGCACGGCGGAGTTTCGGCAACAGGAGC
          GTGCCGTAAGGGCGGAGTCATTACTCGCTCGTTGTACGGTAGAGTATTGGTCTTCATCCT
          GCGGGATAGCTTTGAAGTGTGTACGGGGTCATTATGCGGTTTGTCCGGGGCGTTAGATGC
          ACGCTGTGACCATAACCTCACTGTGTGGCCACATGTTGATTAGCGTGAAGCTAGCGGAGC

          TTCAGATCCGGTCCCTTTTGACAGATCGACGCCTGCAGGGCGTATCACACTGCAGACTAG
          CCTACCTATTCTCTGCTTAACCGAGATGGAATACTTGGTGAATTCTCCGGCGGCGTTCAG
          AACCAAACAACCCCCCTGGGTAGGATTCGGGTTGCCGGCGAGCCTTACCACGCTGGATAG
          AACTGAACTACCTCATTGCGTAGGGTTCAGGCTCCCGACGAGCCTTTCCTCGATGAATAG
          CAGGGAGTCTGGTTGGATCGTGATGTTTACTTGCTACATGACTTAGTCGCTGCCCAAGGG
          CGACAAAGGCAGCCGCATCATCGAGTCAAAACGGTAGGCAGGGCTCCTGCTCTTCAAGAG
          CAGAAAGTCTAGATCGACAGTCGATGTTAACTAAAAAATGCCACTCTTACTCCTAGACGA
          TGTCAAACTCAGAAAGTTAATCAACCTGGTTCTTGAAATTAATCTCTCAACCCTGTATAT

          TAATTAGGCGTTGTCGGTCCGAGTTACCTCTTTCAATCCGAGAGAGCTCCACCTCAAAAT
          CCTTCGCACATTGAAACTCGGTAGCGTTATATTTTACGAGACAGAAATACAATGACGGTA
          CCTAACTGTACTTGTTCTCACGGATCCAACCAGTAAGAAAGGGCATTTCCGACATGCCCC
          CCCGACTGTCATTATTCTTACGTATCCAAGAAGTAAGAACGAGTAATTGCGATACGAGCC
          CCAGTGAGGGATACCTTGGATATGACTACATCATGGTGACACCACACTATATCGATAGCC
          TCCTCTAACTTTACCCTCGTCCCGACCGAGATACACTTACGACATATTTCATCGCAAGCC
          CTGCCGGAAGTCCGTGTCCTCATCTACTAGGATGAGCTCTGGCGGTCCGAAGCGGAGAAC
          TTGCCGATCACAAGCGCCCGACCGTGTCAAATCATATCCGAACAAACCGTATATAACTGG

          TGACACGTTACACCGCACATGCGAACCGTGTGCTAGTGACGCTTGACGCATCGTCGGCGG
          CTTCGTGACCCCTCTGAACGGCAGCTTTTGTAGTCCCAGTAGTATGTGAGTGTCCGGCGG
          ATTCGGGAAATCATACAGATGACGCCAAAACCTCACGGATGCCGGGAAACTTAATGGTGC
          ATTCGGGAAATCATACAGATGCCGTTAAAACTTCACGGATGCTGGGAAACTTAATGGCAC
          TCAGTAACATAACCATCGATCTTTATAACGTGCTATCTGCTCCGACCGACATTTCAATAG
          TCAAGATCGATGCTATCCATCCGACTCTAGCTCAACAGTATTTCAGTGGTACTACTGCAG
          ATCGAGTCCTAACCACTTCCGCTTTCTGAGCCTCAAATATGTCGGGGAATGAAGTAATGC
          ATTCCCTTTGTGCGCCAAATGATCCAAAGCTGCTACACTTGGTGGAAAAGTTAACGACAG

          AAAATGAACGGGGCAGTATGGTACCTGATGATCAACTGTGGGCTGACATGGTGTAAAGTG
          GACACGCACTGTCTAACGCGATGCGCTCCGTTAAAAAGCGTGTAGTTAGACTGATCGGTG
          GGTCAGGTGCGAACCATTTCACGCGCTTATTTCGTAAGTTGGCAAAATCAAATCCTCAGG
          GATTAGGTAAGTGCCATCTCACATGTCTACTTCATAAGTTGGTGGCGTCAAGTTGTCAGG
          GGCCTGCAAGCGGTGTTGCGATCCATCACAACTGGACATCATAAGAACGTGCGACACATA
          GCGCGGCAAGTAATCGCCCGGTGTCCGTTGATCGGATGTATATGTTTCAACTATCATGAG
          GCTAACAAGGGGGTTTTGTGTCATGGGTCGACAGGTGGAAGCCAGGATGACCGCTTGTCG
          GGGAACGTGGAAGCTAAAAGAGTCGCGCCGCCCGTCAATAAAAAAGCTGGCTGTTACCCG

          CTCAATTAGTTTGCTTCGCTACACCCCGCTCCGCTGACTAATCGCACACCGGCCGCAGAA
          TATGATATGTCCCCACCGGAGGAATGTTTCTCGCATACTCAACGGAAATACGATGCAGCC
          CTCAATCGGGGATCCCCACTCATAATCTAGCCGCTGACCTTGGAGACGCCGGCTCCAAGC
          CTCAAGAGGGGATCACCACTGAAAATTCAGCCACTAGTGTTGGAGGCGCCCGCTCCAGGC
          ATGGAATGTCCGCCCCAGTAAGGAACGGTCTTGTATGTCCAAACAACTATCGGAACTGAC
          ATAGAACGAACATCGACACTCAAAACAAAATAACCTAATTTATCAGAGCATGGCACTGAT
          CTAGAAACTATGCCATCCATGTGAACGCAACCGTCATCTTCCTCTATATCTGATTATGGA
          GTTAAATGTGCATTCCCGGTGATAAGCTAATCGACCCTTACACCGGCTTGTTATACGCAC

          AGGCATTAATCAACAAAGATTTTGTCATGTGCCCTAGATCCAGCCATGTACCTTAGGCGG
          TAGACCTTTTCGTAATCACCCAGATAAAGTGGCCATGTTAGGACACTGAGATCAAGGACA
          CTGGCCAACTTCTGAAAGCCCGGGGCCGACAATCGTGGGAAGTTGAAGGAACATCGCCGG
          CCGGCTAACGTATGGACGCCTGTAATCGACAGTCTTGGTGGGTTGATGGTACTAAGTTGG
          CGGGGGATCCCTCTGACTTCCGGGGACAATTTTCATAACGAGTCGTAACCGAACCGGCTG
          CAGGGGACCGTACGGACTTGGGCAGTGAACTCTTGTGCTGAACCGACACAAATTCGGAGA
          CCGGTTAACTAGACCAAGCTATGGGTTTGTCGATACAGTGCCGCAGTGGGGCCTAAGGAG
          CCGGATACTGCTTCACTGTTACGTGCCAACTCTAGCCTCACGGCAACGAGGACCAAGAAG

          GATATTTGTATCCGCTGAACCATCCGAGACATTGAGGTTTGAAATAGGTCCCCAAGTGGC
          GTCCCCTATTATGGCCGTAACTTAGTGAGTCCTAGACCAGCCTCGCTGGATCAGAGTGAC
          GATGCCCATGTTCGCTGCGGAAGCAACATCCTTGCCACGCAGGGCGTATGGTCCGGTAAC
          GACGCCTGTGTTTTCTGCGGAAGAAGTAGTTTTGCGACCCAGGGCGCGTGGCCCAGTCGC
          TGTTCCTCTCTAAGGCAGAGAACTATCCATCGGGTAGCCTCAGGCGGTTACCTTAGCGGA
          CAGCTTACATTTAGGTCCCTTTCCCCCACTCGTGCCGCCCTAGACACGCGACCCGGTGAA
          CGAGTTAGTAAGTGTCCGCGAAACACTTACGTTAGTTGGCCGATTGAGTGTTCCTAACCC
          GGATCCCACTTATCGTTTGGCCCGTGTAACTAGGGATGTCCTGACGACTTCGTTCTATGT

          CTCAGAATTACACCAAGATTTGCTGACGTCTGCTATCGGCGACGCAGCCAAACTGCACAT
          TCCAGGGTCTCGATATACCACGACTACGCATGCTGGCGGCTCAAAGAATATATTGATTTG
          GACACAGTAAACCCGATGACCTGCATGAAAGGTCCATGAGCCCGGGTGTGGCCATCTATC
          GACACTGCCACCACAATGAGCCACACGAGATGCTTATGAGACCGGGTACGCACATCTATT
          ATAGACGGTAGTGTTGACGCCAATGGATCTTGATATGATTTACGTACAAGTGCTGTTCGG
          ACAGACATTGGTTTAGATCTTGAGACCCATTGCCCAAATTCCACTGTGAATGTTGCCTCC
          GCGACGGGGGACATTAGTACGGTAAGTGCTAACTCGGGGAATCACGTATGCGACCTTTTT
          CCATGGGGTAATATCGATGTCTGCGGAGATCTCATTCAAACCCGTGTTCGCTAGGCCTCA

          ATCAAAGGACTCGATACTCGACGAATTTGCTTTTCCTTCCCAGCTGCCGCAAACGATCGA
          AAAAAGATGACTGATCCCTTCTGGCCGTCGTTGTCCTTCTCCACGCTGAAACTCTACCGT
          ACCTAGCCAGATGAGAGCCATTAGTCTGATCATTTCGCCTTAATTATTCGCATTGCCCAC
          ACCTAGTTAGCTGATAGTCGTTAGTCCGATCGTTCCGGCTTGCGTAACCACATTCCAGAC
          GGCCTCATATACGATAGTCCCGAGGTTATTTGCTAGCCTCAGGACTCTGCTTCCATATTG
          GGCTACCTTCGTAATGCCATCGAACCCACTTATAGTTCTGCTGATTTTTCTACCGTGCGT
          AGCAGATTATGATACATTCGCAGACCCTTCGTAACATAATTAACCTCTTGAGCCGCATGG
          CACGAAACATACGCGAGCTTTAGGCTTCTTTTCCTTCGCGAGTCGTTCTGAATTATTAGC

          CCGTCCTGGAGCGTCAAAAATACGACTCCGGGGCCTACTCCCAAGCTGAATTCCAGTAAT
          GCATCTTAGTCGATCATAACGACGCTGCGAGAATTCATGCAATGACCGCTCTCTGTCGAC
          TCATTTTATCGGGCCAGGACGAAGCACCGCGGGGCTATAATGCACTGTATCGTCGGTAAT
          CCAACTCAGCGCGCCGGGAGGAAGTACCGCGAGGCAGTTACGTACCACATCGTCGGTGAT
          TAGCCATTACGCACACCCCATAGGTATGGTATGTACGCAGAAAAATGGGCACCAGATCTG
          TTCTCATCACGGAGATGCCACGGGGGCTGCGGGTACGTAGGATCACAGGCTGACGGCAGA
          TGGTCACCGCTCACTCGAATGTAGACTTTGGGCCTAGTTGTGAAGGTAGTTACTACTGAT
          ATACCCTATCTTGTGCGAAGGGGTCGGAGTGGGTTCCTTGTTTCGTCGGACGCAGGATTT

          AGCGCACACACTTTTATTTCGAGAGTTAGGTGGTTCGACTCGACAGCGCTAGAGAGGGGA
          TGAGCTTGTTAACCTGTTTTAGAAGGCTAGTGGAACGGTACAGCGCCGCTGAAGAAAGCA
          AGCATATACTTACTTTGGCCAAATTCTCCATAGCACCAAAATACCATCGAAGTAGGAAAA
          AGCATGTATGTACCTAGGCCTACTCCTTTAGAGCATCAAAGCGCCCTCGTAGTAGGAAAA
          TGTTTCTGCTACCCTTCTCTGAGTGAGTGTTTCTATGGTGCTCTGTCAGTGTCCAAGGAG
          TAGCGACATTATTCACAATTCGGTACTGCCTAGCTCCGTAGGCAGTCGGTGGAGGGAGTG
          GCACTATGTTAGTTGGTTAAGAGAAAACGCCACTTGATCACTTCGCTTAAGGAAAGAGAA
          GGATCATTCAGGTTAGGCCGGGGAGGATACTAGCAGGCGGACGTATCTGTAAAGACAGGG

          GCAGGGGCTGGTCTTCACACTGCTTGAAGGGCTGAAAAAGCAATTGGGTCATGGGGCTCT
          GTGGGTGTCGATCCTCATGATTCTCTTTTGGGTAACAATAATATTAGCTGCAATTATTAT
          TTTTGTATCTATTCTAAATGCAAGCCTGCCCCTCCTAGACCAAATCGTCAATACGTCGCA
          TTTTGTATCTATTCTTGATGCAAGCCTCGATTTCCGAAAGCAAATCGCCGATATGTTATA
          TTGAATACCGACTCACATCGTGTCCCTTCTGCTTATAGTGTCAAAAATTAATTCTATAGT
          ACAGCAGTCGATCCCCACCGTACACATGCATTCCACGCCCTAAGTCACTGATGTTAATAT
          ACCGACAGCAACGTATAAAGTGCTCACTTCCACTGCGGGAACATTAACAGACGAAGGCAT
          ATGAGCCGCGGCGCTACCCGAGTGCTTGCTTCTTATAATCCCGTTAACCAGCACCGTAAA

          TGTCTGTTTGTTTCCCGGAAGGCTTCCGTGTCTTCTGTGAAGCGAATTTGATGAAGTCTT
          GGTAGATCAATTTAATGGAGCGTCCCTGTGCTTCGTATAGATGCAGTATTTTGAGGCTTA
          CGTTGTACGCATGACGCAGGAATCTCTGCACGTCGCGGGAAAACTGAAGGGAGTATTATC
          TGGCGTATGCATGATGGGGAAATCCCTGAGCGTTGGAGGGAAACTGAGGTGGGTATTCTC
          GTTTTACTGAATCGTCGAACCGCTTTTTTCTACGGCGCAACGTTGCCATAATAAGCTAGA
          ATATAATCGACTCTCAGACGGGCCTCTATATGACACCCGGCAAGGGCACAATAAGTTCCA
          ATTGAGCGAACATAATATGAGGTCTGCAAACGATACGTAGCGATCGGGAGATGATTCTAA
          TCCCAAAGGATACAATAAATAGCCTGTTTAGATTGTAAGACGTAGGCCAATCAATAGTAC

          TGGCGCAGTTGGGCCCTTCATTCTTCACCCGACAAACGCTATAACGTTCTACTGGACTGC
          AAAAACAGAAAGATTTCTAGATCACTACGTAGAATCGGACTCAGAATTCTATGCAACAAT
          ACGCCCTAGAGGACCTTCATTTGAATGCATCGAGGCGGCTTCGTAATATAATATGCGGGG
          ACGGACCAGAGGGTCCCCGCTTGAATATATCGAATCGGCTTCGCGACATAATACGCGGGG
          ATGCGAGGGGGCAATGACAACCGACCCCCAGCACTCGCTCACGCTCCTCTAGGGCGACCT
          ATACAAGGACAAGCTCGCAACCGATGATGCGATGCCAACTACTACCACACAAAACAAAGC
          GTCCCGGGGAAGGAACCTCCCCGGGTAGTAGGTAGCACACGCATACGCACGTACCAAATC
          AGGCCCGGGAGGAACCTGCCTTGGTCAGGCGGCAGGGGTTATATGCGTGCGCAGTCAGAC

          TTGATGAACCGAGTCAAGGAGGACATTACTATGAGAGCTC
          CCGAACGACTGACTATTTAAGGGCGCTAGTACGAGAACGA
          CTCAACCAATCCGTATCGGGGAATGTCATCTTTGTGAGAC
          TTAAATTTATACGAATCGGGTGGTGTCATCTTCGTGAATC
          CACGTCACACACGGACTTCAGATTGTTAGGATCGAGGGCT
          AGAATGATATATCTCCACTGAACGTTAAGTATAACAAGGC
          AAAATTCAAAGGGCGTATAAAGGCTGTATCGTCCTAGGTA
          TAGAGCGGATTGGGGAATACTGGTGCGAAATGATGACACA

