 8 1000
t1        ACCATCAAAGACAGAATCCTAAATTGGAAGATTTTGGAATAAGGAGTACGGTACTCACTG
t2        ACCATCAAAGACAGAATCCTAAATTGGAAGATTTTGGAATAAGGAGTACGGTACTCACTG
t3        CGCGACAAAGGAAGATCTCTTAATAGGATCACCTTAGAATAAGGTGAACGTAACCATCTA
t4        AGCGATAAAGATACATGTCTAAATGGGGTGATTTTGGAATAAGGAGAATGGAACTCACCG
t5        TTAGCTAACAATCGTCACGCACACAATTTCTCTCGTCTCAAGTAAACAGGTGACTCGATG
t6        TCAGCTAGTGATCGTCATGCACACAAATCTTCCCGTCACAAGTAAGAAGGCGACTTTTTG
t7        ATTCGGATACGGCGAAGTAAAGTCGAACTCTTTTGCTAACAACTCATATACGACTCAAAT
t8        AACATATTAAAACGGCAAGTGACTTGCATTTATTTCAACTAACATGAAAGCTGAATCATG

          TTGCCAGGCCGTGAATACCCGTGCATGGCTACCGAGATTTGGAATGGTGGCGTAATCTGA
          TTGCCAGGCTGTGAATACCCGTGCATGGCTACCGAGATTTGGAATGGTGGCGTAATTTGA
          CCGTCACGCCGTGAATGACCGGGTCTGGCCTTTGGGACTTGGAACAGCGGCCCATCTAGA
          CCATCAGGCTGCGGTAGCCTGTGCCTGGCCGCCGAGATTTGGAATAGTAGAGCAATTTGC
          CTGCCGACGCGTGATTACTTAAAAGAGCCACCCCAAGATCCCGGTGGCTGCGAGACTCTT
          CAGCCGCCCCGTGACTATCTAAAGTAGCAGCCCCAAGCTCCTGATGGTTGCAAGACTCGC
          TTCTCGCCTCAAATTTACCGAAACCATGTACTCCAGAGCTAAAGCGAAAATGCGAATAGT
          TTGCCGCCTAATACCTGTCTAAATCGTACTTTAAAATCCTTATATCGCAGCGAGTATTAA

          CGACGCGACCCCCTGTGCCGCTGACATATCTGGTCCACCCACGACACCCAGCGGATTAAC
          CGACGCGACCCCCTGTGCCGCTGACATATCTGGTCTACCCACGACACCCAGCGGATTAAC
          AGGCGTGACTCCTTGTGTATACGACAATTTCGGGCTTCTCATGAGGTCCCGAGGATAAAT
          TGAAGAGGTCCTGCATACTAACGGCATTTCCATCCTAACAACGGGGTCCAGTGGTCGAAT
          GAGTTAAGCTTGTCACTCCAATGAAGTACCTATCTTAGCTGCGCGAACTGTTATACCCAC
          GAGTTAGGATTGTCAGCCTAATGCAGTACCTACCTCAGTTGCGCAAACTGTGATATTCAC
          CTGCGAGCAACACTAGGACTACTAGTCAATCAAACTTTTCATTCGACTTAAACCCTCCAC
          TAACGAGTCATACTCGGCCCGGGAACGCCCTAGGTCTACCGTGCTCCCTACGCTATCCAT

          CGCAAGGAGATAGATCTAAGCGCGTACTAGGTACGAGTCGGACATAATTTTATTCAACAT
          CGCAAGGAGATAGATCTAAGCGCGTACTAGGTACGAGTCGGACATAATTTTATTCAACAT
          CGAAAGATGATAGGTTTGAGGGCGTATTGGCAATGAGTCGGACATAATACTACTCATCTC
          CGGGAGCAGATAGATCTGGGAGCGTACTGTCAACGACCTGAATACAACTCTATTCGTTAT
          CACAATCGACTATATCCGGGGGAGATCTGGTAATGGCCCAGGAGGGGCACTAACCATTGT
          CGTAATCGACCATATCCCGGGAAAATCTGATAATGGACCAGGCGGGGTACAAAATATTCT
          CCGTGTCACATAGATTCTAAGAAGCAATCGATCCATCGCCGACGCAAAGTCTCTTGAGCA
          TGGGATCCATCAGGTTTACGGCAGGGATTGTTGCGTTCCGGCCGAACTGTTGTTAGCCCC

          AGTTCGAGTTCGATGGGACGTGAACAAGGAAAGTGTGACTGATGAACGTCTGGTCTATAT
          AGTTCGAGTTCGATGGGACGTGAACAAGGAAAGTGTGACTGATGAACGTCTGGTCTATAT
          GGATGAGGCATCATGGGACACGGACATAGAAAGTGTGCGTTACTCAGGTTTGATTTGTAT
          CGGCGAAGCGCAATGGAGCGTGAACACAAAAGGCGTGCTGTACGGACGTATTGCCTATAC
          ATAAACTAAGACAAGAGTACCACGCAAGAGGATCGTAAGCAAAACTTGCCTCGCGTCCTG
          ATAATTTTAAATGAGAGTATTACGTAATAGGCTCGCAAGCAAAGCTTGCCCTGTGCCCTG
          CCGTAACCACATGAAGGACTACTGAAGTTCGAGTGTGACTACCACATGCCTGACGCACAA
          CCGTACAGCACCGCAGAATCCAAGCAGCCAAGATATTATCACCACATGCTTCGGAGTCAG

          CCCTAAAGACAACACTGAAAGAAGGGTTCGATCCTGCCAAAGTGGTCTCATTGCTATTTT
          CCCTAAAGACAACACTGAAAGAAGGGTTCGATCCTGCCAAAGTGGTCTCATTGCTATTTT
          CCTCCTGGACAAGGCCGGATGGAGGGCTCTACCTTATAAAAGTGATCTCATCGATTCACC
          GCTCAAGATCAATGCAGGAAGGAGCTTTTAATACTACAGAAATGATCTGATTGTCACACA
          TCCACGAGGCTGTATAATAGAGTAACGGCTAATTGGTACAGTTGATTTCTTGGGACAGCT
          TCCGTGAGGCTATATTGCCAAGAGGCTACCAGTAAGGGCTGTTAAATTCCTCGAACAGCC
          GACGCTCATCCCTCTCAAGAAGACGCTTCCGACATTTAAGATCCCCCGTGCCTAAGATAT
          GGACTGCAGCTCAGTCGCAAGGGAAGATCCAATACATTCGGTTACCGATCCGCTGCCTAC

          ATCATAGATGTACCTTCCCACGATCCATTACAAATGTTGTGTTACAGACATCGGAAGAAT
          ATCATAGATGTACCTTCCCACGATCCATTACAAATGTTGTGTTACAGACATCGGAAGAAT
          GCAATTGAAATACTTGCTAAGGCCCTACTACAATGACGGCGGTGCTGGCATCGAGGTAAC
          ACCCTAGAAGTACTCTCCGAAGACCCAGAAAAATTGCTGTGGTTTAAGGATCGAGAGGGC
          ATTATCGAGGCGTTTTGTTAAAAGCCACCATAGTGGCGTCGCCATAGTTATCAAGTAAAA
          ATTCTTGAGGGACGTTCTAAAGAGTTCCCATGGTGGCGTCTCCATAGATGCCAGGTAAAG
          ACAAGTGGTTTGATCGATCCGATACTCTACCTCATTTTTCATACCGGCGAATACTATAGT
          ACTGTCAAAATGATCAAGCCGGATACGTCCCATGGCCTTCGCGCCATAAGACATTAGAGT

          CGTTCGCCTACGCTATCTTTAAGCGGCATCCGACCGAGTGCAGGTTAGTACAGGTTCAGA
          CGTTCGCCTACGCTGTCTTTAAGCGGCATCCTACCGAGTGCAGGTTAGTACAGGTTCAGA
          CGTTCGCCTATGACATCTCTGGGCTGCCTATTAGGGACTGCAGGCGCGGGCAGCATCAGA
          CCTTCGACTATGTCATTCTCAGGCAACCCTCGATGTAGTGTAGGCGAGGGCATCCCATGG
          GCCCGGTAACCAGAATTCCCGGCACAATGCTTGCGGAAGGAAGGAGAGGGTAGCCGTGGG
          GCCCAGTAACTAGACTTTCCGGCATTATGTCTGCGGAGAGCAGGATAGGGTACCTGTCGG
          GTTACTCAACTACTATCAGCTGCCGCTCGTCCGACTTCAGTCAGATCCACTAGCCCCTAC
          GTTCCGCGGCCCGACTACGCAATTCGCCGTCTGACAGTGCCGAATTCCGATTCGATTTTG

          GCGCTAGAGGTGGACCCTTGGTCCTGTACAGGCACGGCGGATTTCATTGCGAAATGAGAA
          GCGCTAGAGGTGGACCCTTGGTCCTGTACAGGCACGGCGGATTTCATTGCGAAATGAGAA
          GCGCTACGGGTGGTCGATCGGTCTCTATCAGGCATGGCAGTGTTCAATGCGATCTGAGAG
          GCGCCCGGGGTGGTCCCCTGGTCTTGTGTAGTTACTGTGGAGCTCAGTGCGTTCTGCGAG
          CGGTGATGCGCCACAGTGAGATGCACCTCCAGCTTGGCTGCATTCCATACGCAGTGACTG
          CCATGCGGTACTACAGCAAGATTTACCTCATGCTAAGACGCATACTAAACGGAGTGACTG
          TAACGTGAAGCTTTCTTTCGAACCTAGTCCACTTAGGCGGTGCTCGTATTGGCCAGGTCT
          AGGCGACATGTCATTCTTAGCTTCAAGATAGATTAAGGGACGTATCGAATGGCGCCGGTC

          CAGGATTAGCAGTTTCAAGGTCTCAGGAGAATTGCAACATCCCTTATAAAGGGCAGAATT
          CAGGATTAGCAGTTTTAAGGTCTCGGGAGAATTGCAACATCCCTTATAAAGGGCAGAATT
          TGGAACTAGCATTTTCGAAGTCTTGGTAGGTATGTAGTGCTAATTATAAAGGGTGGGTTG
          CTCTATCAGTATTTTCGAGGTCTTAGCAGAAACATAACGCTCCCTCGAGTGGTTGGGTCG
          CAAAACGAGTTATTATATCAGCTATCCCGTACTGGCGTGCGCCTGTAGGGAATACGCTAT
          CAAATTGAGTAAGTATAGGAACTGTCCCGGACTCGCGCGTGCCTGTAGGGATTCTGCTAT
          AAGCGGAAAATACGCAGGGAGAATAGGGGTCCTCAAAGTCACCCACAAGAACCACGCTGT
          CGGGACTAATCATGGTGTAATTCCGGCGCCAATATGAGCCACCTAATATCATCGAGTCTT

          GGTGGACAATTGATGGAAAAGAGCGCCTTTGGCACGCAATTCGCCTACGAAAAGGTTCTC
          GGTGGACAATTGATGGAAAAGAGCGCCTTTGGCACGCAATTCGCCTACGAAAAGGCTCTC
          GGTGGACAATTGATGGAGCCGAGCGTCTCCGGAACGTAAATTACCTTTATAAACGGTCTC
          GGAAAACTATTGATAGAGAAAGGAGCCTACGGTACGCAATATGCCGACATAAAGAGTCTC
          GGTGATTTCTTACAGCGAACTAGTATACTCGACTCTTGATGTACGACAATCGGTAATGAT
          AGTGCTTTTTCGCAGCGGACTAGTATACTCGAATCTTAATGTCCTACAACCGGTGATGGT
          CGTGGCAGCTCTAAGTGGACGGTTGCTTTGGACCTTGATCTCACGTGAGCAGAAGGTGTC
          AGTAGTTCTCCTACGAGGAGGAACTTAATTGGCCTCTGTCGCATACGAAGAGAGGGCTGG

          ACAGTGTTATTTCTAAATTCTCAGCCAACCCTAGTAGGTTATAAAAAACCGTTGATGAGG
          ACAGTGTTATCTCTAAATTCTCAGCCAACCCTAGTAGGTTATAAAAAACCGTTGATGAGG
          AGTGCGTCATCCAATGACTCTCAGCTAGTTCAGGCGGGCTGTAAAAAACCATAGATGAGG
          ACTCCGTTATCCAATGATTCTCGGCCAGTCTTAGTAGGTTTTAACAGTGGGTAGACAAAG
          CTGGCTATCCTTCACGTCCCTGAACCGAGGCCTGTCGAGCGCCTAGCGTCTTGAACAAGG
          CTGACTATACTCCCCGCTCCCTGACCGAGGCTCGCCGAGGGCGTAGTGTCTTGAACAAGG
          GTAGCATACTCTAGGGTATCGGTATCGTAGCCGACTAGGACTGTTAGTCGCCAGTTGCGG
          GCTATGCGCCATTAAGTATTAGCACAAGAGATGGTCACAGCCGTAGATGGCTTAAGGAGG

          TTAAACAAATGGAGCCGTGCGATGTTACTCGATCGACAATAGGAAAAGACGTTGATGGAA
          TTAAACAAATGGAGCCGTGCGATGTTACTCGATCGACAATAGGAAAAGACGTTGAAGGAA
          TCAACCAACCGCAGCCGCGCGACGCTGACAAATCTACGATAGGAAAGGTTTTTGATAGAA
          TCAGATAATTGTAGCTGCGGGGCGTTGGTTGACCAGCGATAGGATAGAATGCTGTCAGAA
          GCGCCCGCTCGTCGCCGGTCCCGCACGACAGGGTAAAGTAATTCCGGAATTACAGCGGTG
          ACATCCTTTTGTCGCTAGTCACGGATGATAGGGTAAAGAAATGTCGGACCCACAGCGGCG
          ATTGGACTCTTTTACAATAGTTTGTCGGTACAGCGATGCTGGGACAGTGACCTTCCCACC
          AAAGAGTTCCTTTGCCATTCAGAATTTCTCTTTTAGTGTAGGCAAAGAGACTTTCCGACG

          ATTCTGGGGGTTGTGAGATCAGAGCAGGGTGGGTTAGTGTTAGGGTAACGTGGGACAGCT
          ATTCTGGGGGTTGTGAGATCAGAGCAGGGTGGGTTAGTGTTAGGGTAACGTGGGACAGCT
          GTTCCCAAGGGCGTTGGACTAGAGCAGAAGGCACGGGTACTAGGTTAATGTGGGCAAGGC
          ATACTGTGGATCTATCGACTCAAGCAGAATGTGCCGGTACCAGCATAACGTGGGCAAGCT
          CCTCCTAAAATCGAATATCGCTAGCGTCACAGCCTAAGGAGGAGGAACTTTTGCCAGGTT
          CTTCATAAGATGGAACACAGTTAGTGTCACAGCCTGAATACGAGCAAATTTTGCCAGGTT
          TACGGAACACAGACTTTGAGTGGCCCATTCATTTCGCACTCAAGGCGTCGTGCGCATGTG
          TCGTGGATGGAATCTTTGACCGGGTGCACTATTCGGAATTAAGAGCAAAGTCGGATGTCC

          CCCCTCAAATATCGTCAACGCGACCACAGTACGTCTTTAAAGCCGTTCGAGCGTGAGAGA
          CCCCTCAAATATCGTCAACGCGACCACAGTACGCCTTTAAAGCCGTTCGAGCGTGGGAGA
          CTCCTTCTAAACGCACAACTCGTCAATAGTATGCCTTTGGTGCGGTTCTGGCGTGAGAGA
          CTCCTCGTCAACGAACAACGCGCCAATAGTTTGCCATTGGCGCGGCTCCGGCGTGAACGA
          TCCACCGGGTGTGTCGAATGCGTTGCTTGCATATTTTTGGCGGGCCACAGCTACAAGTGC
          TTAGCCATGTGTGCTGAAAGCGTTACTAGCTTATTTTTAGCGCGCGACAGCTACAAGTGC
          CTTCACGAAACTAAACGAAGCATCAACAGGCCCCAGTAGCAGTCTGCTAGTCGCAGTGAC
          CTTCATGGTAGTGACCGTAGCAATGCCTCATGATCGTGGTGGATCAACAGTTGTGCCGAC

          CGACTCTACGTCAATATGCGGAGCGTTCGTTACGTCTCCAGGATCCGGCACGCCCGGCGG
          CGACTCTACGTCAATATGCGGAGCGTTCGTTACGTCTCCAGGATCCGGCACGCCCGGCGG
          CCGCTCGACGTCAGTGTGAGGGGCCTGCACACTGCCTCCAGGGTACGGCATGTTCGGCAA
          CTGTACACCATCCGGACGCGAGGCCTTAGCACTTTCCCGCGGGTACGGCACGTCCTGTAA
          GGGTGTCTTACCACGGAGCGGGGCTACAGCGCAGCAACGCAGGCATAATGAATGAAACAC
          CGGTGTTTCTCTAGGAAGCGGGGCTACAGCGCAACAAGGCGGACGGAATCAATGAAATAC
          ATGTGCTTAATTAGCCGGTCCGGGTCCCATGTAATTACTCGAACCGTCCGTCATGGATTA
          ACGTATTCGGTATAACGGCAACGCCGCTAACTTATCTAAAAGATCAACTTCTAAAGCTAA

          TACCCTGTGGCATTTGGAGTGCCGAGAACTCGAGCGAAAC
          TACCCTGTGGCATTTGGAGTGCCGAGAACTCGAGCGAAAC
          TACTCCGTAACATTGAGAGTGCAGAGAACTCGCGCGAAAC
          TACCCCGTAAATACCGAAGTACAGAGAACTAGCGCGGACC
          GAGATCGGAGGTACGGGAGCGTAAGACACTACTCAGGGCT
          GAGTTCGGAAGTATGGGAGCGTGAGACACTACTGAGGGCT
          GACCATGGTGGACCAGAAGTGTATTGATCCTCGATGCAAG
          GTACTTATCGAACTAGGACAATTGCGGTCCCCAATATACG

