 8 1000
t1        CGTACCAATTAGGGTTGAACAGCCCCGAGAGGAAGTGCCTTTATGTCAAAACCCTACTGG
t2        AAGCCGCACGAAGGTAGCTCCTAGGTCGGTACAGTCGTCTTGGACTCTTATTTTCCATCG
t3        GGTGGCTGAAATGAATACACCATCCTCGGTCGACACATGCCCAAGCTCAGTCTTGTTTGA
t4        GGTCCCTAAGAGGCGTGCCCCTAGTCGGGTGGTCCCCCGCTTGAGGCCGGTGCCCCCTGA
t5        ACCTTGTTGATGGTGGAGTGCAGAAACACAAGCCAGGACTGCGGAGATAGATTATCCAGA
t6        ACCTTGCCGATGAAGGGGCGCCGCAGCGTCAAACAGGATCGCTGAGGAGAGTCATCCAAA
t7        ACCTATCCTTCAGAGCCTTTCCGGGAAGACTAGTTGAATTTTTGGGCTCGGCTATTGAGA
t8        ACTTAAAAACCGGGGGCATTATCGGACGACCGCCGTAATTTTTGGGAACCTTGATCCCGA

          ATGTAGATACGGTATATGAACAAGGAGTAAATGCGATCGTCTTCCGTCGTTCAGAGGAAA
          GCACCGACCTGATGGGAGGGGGAAAAGTACAGACCACTCTTCCCGGCAGCTGGATCAGTC
          GTCAGCCCTTCTCTAGTGGAGGGTTAATAGTTAGGTCCCATTTGGACCGTGGAGGGGGTT
          ATCAGCCACTTCTACGTGGAGGGGTTTCACTCAGGATCCCTCTCGGTAGTGGAAAGGGTC
          GGGGATGCCGGCTACGCAGTGGCAACGCCTTAAACGCCGCGATCACTAGCAGGGTCGATC
          TGGTTTAGTGGTTACCCAGCGGCAGCGCGCTTGATGCCTTGATCCCTGGCAGCGCTGAAA
          ACATACGGCTGGTGCGCGGGGGCAGTTGCCCTGACGCCCCAATTCTAAGTCGTACTGACA
          GTATATGGCAGGTGCGCCGAAGCAGCTTGATCGGAGCCCCAACCTTCAGTCGGGTAGGCA

          GTAGGGTTGTCGTACAACCCAAGTTTGGTCCTTATCAGACGGTGAATACTTCGTAAACCT
          TCTGATAAGAGATAGTGTTCGACTGGAAACAGTATCACGTTATACGTGAAGTGCTAACAG
          CAAGAGATGTCTTCATTACTGCGTCACGTGTTTTCCGAGCACTGGTTGTCGCATATTCTA
          TAAGGAATACCCACACTCGTGAGCTAAGTATCCCTTACGTGCTAATTGCTGTGAACCATA
          GAGAAGCCGAAACCAACTACGATCCACGGAGGCGTCGTCCGCTCTCGGTCTGGTTTGGGC
          GGGCAACCGAAACCAACTCTGATCCAGGGAGGTGTCAATTGTCATCGTTCTCGTTTTGGG
          GAAAGCTCTTGCTGAGCCACGGATCGCGGTGGTAGTGCGAGATCCAAGCTGCGTGTCGCG
          GGGCAACCACACCACGCTATGAATTGCGGTAGGATCGTGTCCCTCGGAGCGCGCCGAGCG

          CGCAGTGCACATGCGGCGCATGAGCGCGGTGTGAGATTGTCGCAGTGTGTGGGACCGCCA
          AGTTCAGCCGTAATGATTAGCAGCCCGGGCACCAGTATTCGAACTCTCGCAGGTACGGAG
          AGCCCCGTTCGTGGGATACGCGCCTCGGGTCAGAGGTGTATGCTTCGCAGCAGGCCTATT
          AGATTCGTTCTAGACATATATGGCCAGAGCCAGGGGACTATGCCAGGAGAAAGGCCAGTA
          TTTGCGATAGTATTCGTTTCCAGCCCGAGCCGAGGGACTACATCACCCGTTTTGCTTCTG
          ATTAAGATTGTATCCGTCCGCAAGCCGAGTAGAGGGTCCGCATCAATCGTTTCTCCTCTC
          GGCGATGGAGCGGTCACGCGAGGTATAAGAAGGGGGTGGACGCGAACCCCTAACTATTCG
          ATCCGTGCAGCTGTATCCCGTGGACCCAGAAGGGGCTGTACCCCTGACGCCCTATCGTCT

          ACTGGGCCCGGTGATTGTATTATGAACAATAGTACCTAAGCTGATCTGTAAGCTCCCCAC
          ATCCCACCCAGTTGTCGCGGCCCGTTCACACACATCTAAGCATTATCAACAGTCCCATGT
          TTTACTCACCTTATATGTGGCGTGTCAATAACCTCCTAAGCTATCTTAAAAAAGGTATTT
          CCCTGCCTTTCGATCAACGGCATCTCCACGATGTCTTAAATCATACCGAGCGAGAATAGC
          ATGCGCACCAGCAGCCACCGCTATCATCAGTTTGCTTCCGAAGTAAAAAGTGAACCTAAC
          CTGCGCATCAGTAGCCACCGCTACCATCAGTTGAACCCCGGAGTACCGAGTACGCCTCAT
          TTCCGCGTTGCAGGTCACACTAAGTATAAGTTACGCCTCGCGATAGCGATTATCCTGCAC
          CTTCGCATCAATGCTCAGATCCATTGCAAAGCTAGCCCCGTGATGTTGTATATATCGCAT

          GCTGTGCGGCTCTAGCTCTTCGGGCTCGAAGGACACGTATATTACAACAGCCGGATGTGC
          TCAACACTCTAATCACCATGCAGGTAGGTGGGACTTCCAAACTTTGAAACAAAGATGAGG
          ATTTTTTCAGACGTTTGGAGTGATCTGGCGACAATTTGTAGTTACAACGACTGGGCAAGA
          ATCTCTTCAGATCTGCGAGATTCGCTGAGACCGCTCTGTCGTCACAAAGAATGGGCAAGG
          TGATTTCCTTCCTCTCCGTGCCAGTTTGTATCCTTCTTTCGTTATGGTAATTCAGGTCCG
          TCATCTCCTGCCTCACTGCGCTAGTTGATATCCTTTTCTCGTGAGGATAGCTCAGGTCCG
          CAGAGCCTTACCTTGGTGCCTTGACTCGGATACCCCTTATGAGACGCACGTCAGGGAAAA
          TAACATTTCGCTATGTAGAACTGGTACGAACCTCGTTCTCGCGATGACAATCACAGTTAT

          AAGGTCAGTGGAAGCTGACGAATGACTTTCGCTGTAGAGGGCTCTTTCCAGCTTGCTTCG
          TGGGTGAGCTTACATTAATGGCTACCCCAGGCCGTATGGGACATTGTGAGGCTCTTTTAG
          TGGGTCGAGTTGGACCGCAGAATGTCACTCGTTGGGGAAGTACTTTCGTGATCCTTCCGC
          TGGATCACTCAGATTCGAATAATAATGTTAGTGGTGGGGGCATGTCCATAGATATCTTTA
          CACTTCCTCCATACTCGTTCATCATTACTGCAAGAGCCGGAAAGCGGTAAGATCTGCGTA
          TACCCACTCTGCACTTGTGCACTATCTTTGCACGTTTCGGGGAGTGATTAGCTCTGTATC
          CTGGGAGCTTCTGGGTGCTAGGTACTGTCACGGACACATGACATACTAACATTCTAGCCA
          CCAACCTATCTCGCGCGATAGGGGTCATCGCGGGAGTGGAAAAATCTAAGACTGAACTAA

          TTCTGGAAGGCCAGTAATACTAGTGTGCTACCTACTTAGGCGAGAGGAGTTACGGGAGAA
          TTGCTACAGGCAAACGCCGCTTGCTAGCAGCTATACCGGCCATCGGCGCTTGTGGAAGAG
          CTGTGATAGTGTTGTAACCACCGAGAGCCTCATTTCCGACAAGGGGGAAATTCGGTTAAA
          TCGTGATGGGGCGGGGCATTTCGTGCGCTCCCACCTCGAGTCCGGGCGACTACGGTATAG
          TCGTATTATGGCAGTACTGGACGCGAACCTCATTGTAGCTGCAAAACAACCATGGCAAAC
          CCGCATTATGGCAGAATTGACCGCGTGCCCCCTCATAGTTGGTTGACACCCACTGTACAT
          CTATACTGCGGAAATATAGACTACTCGGTATAAATCCGGCCAAGCGCAGCTAGGGCAGGC
          CTATGCAACAATGACACCGAAGGAACGTAACAGTTTCTGCTGCGAGTATTTAGGGCGGTC

          GTAACACTGTAATTGGGACCCCTTTCAGAACAAGTATAGCTCGTGTTGGTACCGGTCGCT
          GTAACACGATACCCGTATTGGGCACTAAAACATGTATCTCATGTATCGGTCTGGCCCACT
          TCTAGTCAGTGGTTACGTTGTTCCCCGAACTTGGGGTAGGTGACATCAGTGATGGGTATT
          CTCGGACGATGTCTAGGACGTTTCTTGAGGCTGGAATCCGTCGCGCCTTAACTGTGCATC
          GTAGAATAGTATTAATAGCACTCCATTCAGTCGGAACTGCTCACACCGCCAGGGCGTTCT
          GTGCAACAGCACTCATAGTACCCCATTCGGTCGGAATTGTTCATACTGCAAGGGCATGCT
          ATTAGTTCGCACCTATAGTACTCTTCAGGGAATCAGCCTGCCACACTGAGAGCGCTTGTT
          TCAGATTTGGAATTACACCGCCCCGAAGGGTCCAGGGTAAGCGCCATCCTAGTGTTTGGC

          GTTTTAAGCAAATTTACTAACACTTCCACGGATTCCGAGTTCCTGAACATGGCCCGTACG
          TTGTAACGAGCGTTCTCCCACATTCCGAAGCGTTGCAGCCGATGCGGCCTGGCTACTGCG
          CACTGGAAAACGCACTTCCCTACTGCTACGGATCATCCACGAATCGGCTAGGTCATGTAA
          ATTCAGGACACGCCATTCGTTGCTTGTGTGAGCTATATTCGAATAGACTCGGGTTCGTCG
          GAACTAAGTTCGGATTGTGTCGGCGTTGAGAGTCTTACCAGACTAGGACCAGCCTCCTAG
          GGACAATAAACAGATTGCGCGAGCAGTGGGAGCCGCAGCAGACTAGGTCTAGGCCTTTGG
          GCACCGTGTACGCATAGCATCACTATTACGGGCCTTCCTCAAAGTACCTTAGTCACGGGA
          CTGCCGGGCACACACTATACTAACATCGTGGGTCAAAGTTCATAGGACCTCAGTATTAGG

          GCATGTGCTACCTAAGGCAACACAGAAAGCCATCGTGGAAGGATGTTTTACCTCTTTTTA
          GGGCAGCTTACGTGATGCAATGAGGCGAACATACCGCGCTGGAAATTTCCGTACTTCTCC
          ATCCAAATTCCAGGTACCCTCTGATAAAAAATCTTGTAGAAAAGATCCGCTTAGCACCCC
          ACGCGAAACATATGTACCGTCCGTGAAAATGCTGTATAGAAGATGCCCGTTTCCCTCACC
          GCCCACTTGGTTCGGAAATCTGAGTGGAACTCATCCTAGTCAACTCTTAGCGTCACTATA
          GCCCGTCTGCTTTGAGGAGATAAGTTAGATTGATCTCAACAAACATCTAGCGTTTTTACA
          GACCGGCGTACCTGATGGAATGAGGGTGACTTATGTTAACTAACATCCAATAAAGTTATG
          ACTTCGTGAAGTTGATGAAATAAGAGAGACTCCCACCACCCGACTTCCGGCGCTGACACC

          TCGCCCCAACACTGACAGACCCCTCGACGACCCCGCACCAGCGTGTAGAGTAGATATCCG
          CCGTCCCGACTCTGGAAGAATTTTGAATAACTACAGATCGATGCCGGAGGTAGGCGCCTT
          GTGTGGCGGTATCACCAGGCTTTGGGATCCCCTTGCCCTGATCAGCAATGCGGACCATAA
          TCACCGCGATACCGTCTGGTTTTAGGATCAAGGTGCATTGATGCAAACGGTGGAACAGTG
          TTTATTTGTTTATTGTAGGCCTTCTCACAATCTTGGGATCAACTCTTTCGCTGGTACTTG
          CATACTGGGTGACTGTAGGCTCATTCACCATTTTGGGATAAGACCTTGTGCTAGTACCTG
          CTTCACAGGCTCGAGTAATCCCCTTTCTTATTCCAAAGCCCAGTGCCCTACGGCTACTTG
          TGACTGACGTTTTAACAGTCTTTTTTATAATCTTACGATCAAGTGTCACTGTGCGATTTG

          TTTACCTTTATCGGATCAGGCGTCAGCGGGTGAGCGCTTCTCTGACAGATCCTTATCACC
          CTAACAGCTCCTGGGTTAGGAAATAGAGAATCGGCCCCCGAGTCCAATGCTCTTTTCATC
          ACTCCCCCTATGTATCTACATAATTCTGCACGACTTAATTGGCCCCAAACTCAATTATCC
          CCCAAACGTGCCCTTTTGCATTGTTGCAGAGAATAAACGTTGTTCGAGTAAAATTTTGTT
          CCTTATACAGCCGGAATAGCATTTTCTGGCCGGTTTGATCAGTTCAACTGCATTGTCAAT
          CCCAAACCAGTTGGAATATCAGTCCCTGGTCGGTTAGACCGGCTTACTCGCATTGTAAAT
          CAGTAACTTGATAGGTTACCTAACTGTGATAAGCCTCGCCGGTCGAACTGTCCATTCGGA
          ACGAGCGGTGCCAGTTTATGCAGCGAAGAATGATCAGGCTGGACCGCTAGCTGGTCCGAT

          GAGTCACTTAATTGGAGTACTAACACGTACACATTAGCCCAATACAGATCGGCTTGAGGC
          GTGTGCCCTGACCAGCAACGCGGTGCGCTTAAAATAGTTCACCGGGGGCCGGGATTTAGG
          AATAACTTAGCGTTGTGATGTAGAGGACCTTACAGAGCTTGCCAGATAGCGGCTTGAGGC
          AATTTTCTAGCGTTATGTTGTAGATATCACTCCCGAGTTTAACAAGTAACAGCTTGAGAT
          GTGGATACCGCACTCCGCAGATCTATTCATATCACATTACGTTGGAAGCAGAGATGTGAA
          ATGGTTATTGATCACCGATACTCAATTTATGTCATGTTAGACTGGACGCGGAGTCGCGAA
          GGGAACGCTGGTCATCGGACACCTATATAAACCATAAAGCAAAACTAATGTCATTGCAAA
          GTGGACATTGAGTAATGAATCTTTATTAGAGTCCTCTGGCAAAAGTAGCGGAAACGTGAA

          GCTAATAAAGATCTAGCCCCTAGTTTTATGCTGATGTTACATGCCATGGTTTTTGTTCCA
          TACCGGATACAGCCGACTCCCAAGGGCCTGTACAATATGACCGCGTCGGTTTTAATTGAC
          TCAAACTCGAGATTAATTGCCCACCACTTCGGAGTTCTGGATACTTAAGACATGCCTACA
          CTAGGTTAGACACTAATTTTTTACCGTTTGAGAGTTTCGGATATTTTGGGAACGTCCAGG
          CAATCAGAAGGAGCGGCACCTCATGCCAAGTGTGTATTCTCTACAAGTTTGTCGTCCCTT
          CAATTAGAATGGAGGACACTCGACGCTAGGTGTGTATCATCAACGAGTGAATTGTCCTTT
          ACTTCGGCGGGAACGGTAGACCATCTTAGGTATCTTAAACTCACTTGAGCTCCGTCTGTG
          CTTAGACTAAGGGCCATATTTGATGCAATGTCTCCTACGCACGTCCAAGTATTGTTCCAC

          GTATGCCGTCGGGTTGACTAGACAGTAAACCATCGGAATTGCAGACTTTTCGGCTTTGCT
          GTAATAAGTGGTATCCGTGTTTCCTGAGACAGCATGAATAGCAAATCCTTAGCCCTCACT
          GTAGGTAGGTTTTATAGTTTCCCAAGTCTCTGTTAGAGCGCCGGATCCTAAAGTGCCTGT
          GCGAGCAGCGTTTCTAGGGGTTTAGATTATCGTTAGCATGCTGATGATTAGGTTATCCCC
          AGAGATAATCCCAATTTAGATTTAAATAGATGGCTCGACATTTTACTCTCGACTTCGTCT
          GGAAGCTACCTTAAATTGTATTCAAGACGATGGCTGGACAATTTCCTCTAGACCTTGCCT
          ATGCCCCGCAATAGTCTTTCTCGAGACTATTGAACAGGCGTCTCAACTTCGCCTGCTTTC
          AGAAGTTGCAATGAATTCTATCGGAGACTACTAAAGACCACTTCTAGCTCAATCATACCT

          GTGTTCCTCCAAACAAGACTGACGCATGGATAGTGATCCG
          CAGATCCTGATTGGAGGCTTGGAATGTACACATTCTGTGG
          CTGTGTTTATATAGCAAGATGGAGAGAGTTAACTCATAAT
          TAGACTTCTAATGGCAAGCCGAGGAGTGTCAGTTCACTAT
          CTGCCCTTCTGCAGGTAAGCGAGAACGACTCACACATGAC
          TTGACCTTCAACAAGTGAGGGAAGTTGGTTCCCGCATTAT
          TTGCCTCCTTACAAGAACGTAGTACCAGCATTAATAGAGT
          TCGATGCTTCACGGGATGGATAAAGCATCACAAACAGAAA

