 8 1000
t1        CATCACCTACAATAATGCAAACTTAGGACGCTTTTTGGCTTGACGAGGCCAATCACTTCA
t2        GCTCCTATAGGCCTCGGTGGTTATGGTAAGAAGCACAAACTGATATACTGAGTCAAAATA
t3        GCACAACCCAGGGCCTGTAATCGTTCTGCCCCCGATAAGTCTCTAGGCGCCGTCAACAAG
t4        GTAACCCTAAGAGATTACTACCATGGGGCCCTTCCAAGTGTGTCGGGGCCGGACACTAAA
t5        GAAATGCTGAACATCGGAAACCACGAGGAGCTAAATTGCTCACCGGCTGGAATCTAAATT
t6        GCCGTTCTAAACATCGGGAACCATGAGCAGCTAAACTGCTCGCCGGCTGGAATCCGAATT
t7        GACGACCAGAACACCTGAGAACACGGGCAGCCACATTGATTGCGGGGCCCAATCAGTGGA
t8        GACGATTCAGACACTTGGAAGTATTAGAAGCCATGCTGATTACGAGGCTTCAACGGAGTA

          AGTCCGCTCAGCTTCTTCTCAGACAGCGAGAGTTCCCTGCCGCTTTGTCCGCGCAATAGC
          CAGGCCTGACAATATGCTCCAGAGTGAGGAGGTCCCCCACCGCTCCCCGCCCGCGAAAGC
          GCGGTGATCGACCCTACCTCTTGGGCTGGTAGGACTCAAATGCGCCCGCCCCCTCACAGT
          CGAATGATCGTTTGCACCACTGATAGGTGCAGTCCTCCGCTCAGCCCAAATGATCAACGC
          AATATGATCTTTCATCCTTTCCATTGTAAAATCTACTTTACTTGGGCTGTTCGCCACCTC
          AGTGTGATCGTTCCTCCTTTCCTTTGTGAAATCTACTTTACTTGGGCTCCTCGCCAACTT
          GGTATAAATGTTCTGTCACTATTTCAGGTGTTGGACTAAACTCCCACTTTTTGAGGGCGT
          CATGCCGTAGCCCTCCCGCTATCCTTAGTGACAAATTAAACCGACGCTTCCCGAGACCGC

          CACTAATGCTGGTAAGAGACGGGCAATTAAAGACTCGCCTGACAAACAAAACATCTGTGC
          CGCTTGGTTAGGTTAAATCACACGGATCCATTGCCAAACTGGCGAACTGGACCGAGCTTC
          CGGAGGCGGCCAGCTTATGGCCCATATCAAATTCCATAACATTGTTCAGAAGAATTCCAG
          CACCGACAGCGGATTTACTATTAAAAACAAATGGTATATTTACGTCGAGAAACTTATCCG
          CAGCGATGAGAGTAATGCTATTCTTACTTTGTTTCACCGGCCTGTGTACGACTTTTACAG
          CAACGGCGAGAGTAATGCTATTTTTATTTCGATTCACCGGACTGCGAATGCTCTTCCTAA
          CTCTAGTTAAAGTTCGGGTTTTTACGCTTGGCCTCGTTCGAATTCATACGGTCCCTCTTA
          CGCAGATGGGGATGACGTCATTGAGGCAACGTTTGTTACCAACCAAAGAATCGTCCACCA

          AGTATGCGAGCGGCCATGGTTATTATGCGTGTAACGGGTTGCTTGCCTCTAGGGACCTTT
          TTGCTATATCAAACTTACACAGCGCCACTCGCAAAGGGCCACAAATGGGTAACAACAAGG
          GGTTCAAAATTGGCTGGACTCATTTGGTGGGTATAATGGCAAGCACAACCCCAATCAATG
          AACGAACAGTAGGCTCGACTAACGCCAGACATAAACGCATACGAAGCTATACGAACCAAA
          CGTAGCCAAGGCTTCTACGGCGTGTGGTGGTACCTGGTAACCATAGCAGAGTGGGTCGCT
          CGTATCTAGGGCCTATACCACGTAAGGAGGTACCTAGCAAATATAGCAGAGCGGATCAGA
          GCTACAGAGCAGCTTAGCGATACGGCGTGAGAAGCAGCAGGTGAAAGAACTTGAGCTACA
          AATACCGAACTCTTCAGCGATACGAAGTGAGAATAAGCAGACGAAGTAACTTGGCTCATA

          TCCACCAAGCTACAAAGCACGTCCTTCGGCAGCCTCCCAATCATTGTGACAGCGCGCGGT
          TATTTTCGGGTGACTCATTCGTCCTGTGGCCTTCACTTATATACTTTGGCAGCATATTAC
          AAACTATCAACCGTTTAAGCACTACCCCCCCTCTGCCCACACACCGCTTTAGTGGGCTAT
          GAGTTTAGAGCCATCACAGCGCATGCCTGGTACCGCACATGTATCACCGCATGGAATCAT
          CATACTGCGATCGGCCGTGGACTAGTACGATGTCAGTCGAGCAGCGCCATGGAGAATGCC
          CACACTGCTATCGTCCATGGACTAGTACGATGTTACTCGCGCAGCGGCAAGAAGAATGCC
          AGAGCTACCATTCCCTGCAAGATCGTCTGCTCTTAGGCAAGAAACACTGCTGAAAATGAC
          TCCATCGGGTCCCTCAGCGAGATCGCTCGCCTTGGTGAATACAATGTTGCGACGGATAAC

          AAAACACGGTAAAATCCGACTAGGCTGAGTATTATATCGTCCTTGCCGACAGATTTATGT
          CTAATTTGTATATGACTGTGAGGTGTCCATTATACCGTGTCTAGTCGGTCCAAGGTAAAG
          TCGACCTCGTACCAACCAAGACACCTGGCGAGTCTGGAACTGGTTTAGGAACGTTTCAAT
          TTATCGCACATTTTATAGAATAGCTTGGTCGTTCAGAAGCCTAGCCAAAAACAACTCCGC
          CTAGTGGGATCCAAACGAGTCAACCTGGCCCCCCGGGGACCAGTTAAGTAAGGTGACCGT
          CAAGCGGGATCCAAACGAGCTAACCTATACCTTTCGGGAACAGTCGTGTAAGGTTATCGT
          CAATAGTCGGTTATTTGAATGAACTTGCCCTCCAGGGGACTACCTAATTATGGATGCCGG
          CAACAGCGGGCCTAGGGAGCTACGCTACGGTACGGGGGGTCATCATGCGGTGAATATTGG

          TGGAATTACGAATGGTGTCTAAGCTTATCTCGACTCCCCAGGAAGTTAACGCGAAACCAC
          GGTGTCTTCGGCCGGGGTTCAGGGTCGAGTCCTTTTTGTTAGACTTTTGTTGGCAACTTT
          CAAGACAACTGAGGGAACCAAATAGAATTCCCACCTTTCTAGAACCTAGTCCATTGCTTC
          AAGGTGGACAGGGCGAGTTGTATTTTGCACTGATTCGGCAGCCCTTCATTCCACTACCCC
          ACGTATCGCTGTAAGTGCACATCATTAGGCCCACGTCTTTGCTCACTTGTCTGTTGTGTT
          ACAAATCGCGGCATATGCTCATCACTAGGCTCACATCCTCGCTCACTTGTCTACTGTAAC
          CCAGATCGTCGCGCGCACGAATTCCAACGTTAACATCCTTCGCTAGAAGTCTGATATGTT
          TCGGGTCGCCGCACGAATGGATCGCTACGTCAATTCCTTTAGATAAAAACCTGCTATGTT

          GTCGTTCAGCGCTATCCGAGCAGGCCGTCGGGCCGCGATGGGGTCGGCACTTGCGTAGCA
          GATCCGCGACGCCCTTCGCACAGGTTGTCTCAAGTTGAGGAGTCCAGCGCTGAGTTTACG
          GTTAAGTGGCAGCTTCTACGAACGACCGCTGCGTCCAAAGCGAGCAGAGCCGGGGGTGGA
          GGCACGTTACTTTCTCTCATCCGGTAAAGCAACTACCGTGAGAACGGCCTAAAGCCGGAA
          GCTAACGTATCGTATCTAAGGTGGACGCTGTCTTGGCGAGGGCATCGAGATAGTGATGGA
          GCTGACATACCACTTCTACGGTGGACGCTGTCAAGGCGAGGGCACCGAGATAGTGATAGG
          CTTAGCAACTTGGTTCAGAGGAGGACATACAACTGTCGTGTAACTCTAGATGATGACTGG
          CATAACAAGTTATTCTTGCGTACGATGTGCAGTTGCGGTGGATTCTAAGTTGGTGACGGT

          GGCCGAAGACTGGCGCGCTCTGTGTTCCCTGATACCAGCCGGACTGTTCAGCAACGATAG
          CATTGACGACTGCGCAATATGTTGGATCCCGGCGGATGGAGTGAAGTCCTCCTAGAACAA
          GAAGAATGATAGGCTGATGCTCTATTCGCTACCGCTGAGAGGGTAAGCACTTTTGTGCGA
          ATTCATCGCTTAGTTTATACTTTATCTCTCCACGGTGCCAGGATTCCTTACCTAGGGTAA
          AACTTGCGGGGGCCCCGTACCCCAAACCCTGTATATGTCGGGCAAAAAATGCCGGTCCGA
          AACTTGCGGGGGGCCCGTGTCACAAACTCTGTATTTGGCGGGCAAGAAATCCCGGTCCGA
          ATTCGGCAGGGAACCCGTATCGTTGGCACCGACCTTCCTAAACATGCAACCTTCGACAGG
          AAAGAGTGGAGAACCCGTGTCGTAAACTCTAACGTTCGTAGCCAGTAAGCTACGGACAGG

          GGAGTCTGACGAGAGCTAGCGCTGGATCCCGTTCGCTCTCTTCTAGTCAGCGTTGATCTT
          CATACTGAGTGAAGGACAGCGTACACTTCACCCACCAAGTTTTGTTATGACTTTCTGGCT
          CATCTACAGCAAACAGCGACAAGGGCTATTACCCTTCACCCCTTCAACAGTGTGAACAAC
          AATCTAGTGTGCATGGTAGCATAGCTTGCTAGTACCCATTCCTCGTACAATTACGTCTAT
          TGGGGTGAGTGAACAGGCGGGCGGGTTGCTAGTTCTTCCCGGATAGGGCTCTCCACTAGG
          TAGGGTGAGTGAACAGGCGGGCGGGTCGATAGTTCCTCCAGGATAGGTGCCTCCACTAAA
          TACCGCTAGAGCGGGGGGGGTCAGGTACTCAAGTCCTCTTCTGTGAACAATACAATTTGA
          TGCAGCAAACGCAGAAGGGGATGGGACTGCAGGGCCTTTACTATGGGTAATACAACTTGT

          TATGGTGATCCTCCCCTCTTGATTGCTGGTGCGATCGGTCACAACCTACGAACCGCGGAT
          TGTAAGACAATTATTGATCAGGATGACACTAAGACGATTATCCGATGACGTCAGCGGAGC
          AATAGGTCTGCTGTCCACTTAATGCGCATTTGGGCGGACACACATAGACGCAAAGGGTCT
          CTTAATTTATAAGCTTACTTAGAGTACAAGCGGTCAGTTATTGGTTTTCGGGCAGCTTGC
          CTAAGCGGTAGATTGCATTTCGTACAAACCCATCGGGATATTAGCTAGATATTGGGAGTT
          CTAGGCCGTAGATTGCCCCTAGGACAAACACATCGGTACACCAGCTAGATTTTGGGAGTA
          TTCACGTTGGTCCTGTACCACGGCGTGGACCAGCGGGGCAACGATTAGGTGTTCCGACCG
          TCAACATTTCACTCGGATCCATCCGAAAAATAACGGGAACGTAAGTACTTACTACGCGTG

          GCAAGTTGGTTTAAATGCTCGGACCCCTACGACCGGATTAGTATGCCGCGGATTCTGCTT
          GCTGACTCGACTTCGTGTATGAATTTGAGCGGGTGGAAGGAAATGCAGTATTGCGTGCCT
          GGAATAGAGCTAATCCGCCCGCCGCCACGTGACTAGACTTTAATGACGGCTGACATTTCT
          ATGCCGACGCTTAGATGCCAGATTCTATGCGGAAAATTAAAAGCGTCATCGCACCTTCTT
          GCCGTGGGGGCTCAAGGGTTCCTATCGCTCTCCAGAGAATGGTGGCTTGTGACATCACCC
          GTCGGGGGGGCTCACGGGTTCTTATCGCTGTCTAGAGAGTGGCGGCTCCTGAAACCACCC
          GCCCTGGGATTTTAAGATGATCGATTGAGCGCTAGAAACCGAGGGAGCCCGTGTCCGATT
          GCAATCGGACGATAAGGCTTCCCATTGAGAGTTTGAAACTGGGGGAATTCGTGCCCGATA

          CATCAGAAACATTCTGTCGATGTACCGATCGTGTGGCGGCCAGGTAGCTAATGTCTCTCG
          CGACTTAGGGACGATGCCGTTGCCACGCCAGTGCGGCCCCAAGGGATGTAGTATCTTTAC
          GCCCGAGGAAACGATCTTAACGTCGCGCGTGATTAGTCGGGTGAGGTGTTGTAGATCAGG
          GCGCGTAGGTTCGTTAGTAACAGCGCGGCCGAGCGACAGGAGTACGAACGATGTGCCAGG
          GTACCTTGGGCCGCGATTCACGTTGTCCACTGGCGACAGCGGAATTCGGAACGTTAATAA
          GCACATTGGGCCGCGATTCACGTCGTCCTATGGTGATAGCGGGAATCGTAACGTCAATAG
          GCGAATTAGGTTTGTATCCGTGCCACCCACGAGTTGTGGGGGGCACTTCAGCACTAATGG
          TCGCATCAAGTTTATGTTTATGACACCCCCCAGTAGTTTCAGACATACTCGCCCTAACGG

          CTGCCCTATCGAAGGGGCCCAGACGAGCCATAAGCTAGGTTGAAATGTTTGTCCCGCTTT
          TATCCATCTCGTTTCGGTTTGGGCTTTGCGTGAAAAATCTCCGAGCGTGAGCGAGACTTG
          GACTTGAAGGAGGTTGATCCCGGCACCCTTCATTTGGGTATGAGAAACGGTTACTAATGA
          CATTTGATGCGGGTCGGTATGAACCTGTCCTAGCAGTGGATGGGATATTATCGTTATCGG
          TGCCCGAGTTCGGTGGACGGCGGTACAGTCCTAGCACGATGTGTACATGACCGCTGTCCC
          CGCCCGAGTCCGGCGGACAGCGATATGGTCTTAAAATGATGTGTGCACGACTGTTGTCCA
          TTTGTGAACGGGGTGAAGTACTATCTGTCCTCGACACAACGGGTATATGGAGGGTGGGGC
          TTCATGAACCGTGCGGGTTATTACCGGGCCTAAACATAGTAAGTAAAAAATTGCGCGCTC

          TCGTCGTATTGAGCCCTTGACATCTACACATACACCTCTAACGGAACAGTTTTCAGCTCT
          CGGATGCCTCGAGTCAACGTTTCGCCTCTAAGAGTAACGCCTGTTGTATTATCTGCCTTT
          CGGTGGCACCGAGCACCCCTCTCGTTCCTACACTGGACGTGCCACGTCTCGTAAGATAGA
          GAAGCGAGCGGAGCCGCCTCCCTGTATATCCACTCCGGCCATGGAAGCTTAGATAACAGG
          AAGTCTCCACCGATCAACGTTACGTATTTATTACTAAATAATAAAGTTCGGATCAGCCTT
          AAGTCTCCCCGGATCAACGTTACGTCACTATTAGTAAGTAATAATGCTTGCATCAGCCTT
          CCGTCCGCCCGCGTAACTGCCAGTAACCCACAAGTCTTGAATTGAGCTGTTTTGGTCTAC
          CAATTCCAAAGGCTCATCGCCATAAATCCATATGTCTCGGGTAATATTACTTACGTTTAC

          CAGAGCGAATCAATATAGCGAAGGCTTCACGCTATCCAACTATCGAGTACTGTTTAACTG
          AATAAATTCCAGTAACACTGTACGCGTAAAGTTTCTATACCTTAAATTGGATGTCATCGT
          AATTACTAACGAATGTGGTTTGTTACCAAAGTACGTATAGCTCCGTCCTCTACCCATCAG
          GTGTACTACATAATAACGTACGGCACTTTTGTGTTTACAGTTTCTTACCCAATTTATTTA
          GGATAGCTCCCGGTAATAGGCGGCAGTAATGGATTAAGCGCATTGGATTGGGATCACCTA
          GAGCAACACCTGGAGGAAAGTGGTAGTAATGGATTATGCACACCGCGTCGGAATTATTCA
          GAGTGACGCCTTGAAAGCTGTGGTAATGTATTATTTCACATTCTGGATCCGGATTATGCC
          AAATGCCGTCTGGAAAGCTATAGTCATGATGTGGACACTACCCTTGCCTGGGATTATAAG

          CAAATTCTCCGCGGACATCTTAGGCGCCACCACGATTGGA
          ATGCCTCAGAGAGGGGGGTTGCGAGGTATCTAGCGTGGCG
          CATTAAACCAACGATTGCGCGGATGACTGTCGAGGGAGGT
          TAATGACAAGCCGAACGTGCGGCGTATGGTTACTGCAAGC
          TGCCCATCTAAGGCACGTGAGCGGCTTACCCATTAGAGAT
          TGGTCCTCTAATGCCCGTGAGCGGGATACTCATTACAGAT
          CGATCCTATGACCGAGGCAAGCCGACTACGTCTAGCAAAT
          AGATCCAATGACGCATATGAGAAGGTAGCCCTTAATAAGT

