 8 1000
t1        AACTGTGCGATAATCAGTCTTCCATAGAACACGGAGCTTCATACATACTGCAAGTCTAAT
t2        AGCTATGCGATAATCGGTCTTCTATAGATCACCGGGTCTCGTCTGTATTGCAGTTCTACT
t3        ATACACAGGCTAATTAGTTTTCCACGGACCGCCAGCTTCCGGATGAACCGCAGGTACATC
t4        GGCGACACGGCGATCAGTTTACTGTGGATTAACTGACTCTAAGCTATTACTACGTGAAGA
t5        AGTATAACAGATCTCGGCAAAAGCTTGACTCGGGGCTCGCGTGCGTTTAACATGTGCGTA
t6        CACCATCCAGGACTTAGTCTTTTACTGACGTTTAGATAAGGCTCCTTTAACACGCAAGTG
t7        AGTCATATGATCTCTAGATCTCAGTGAACTCTGAAGCTAATCCGGTCGTGCCAATTCCCC
t8        TAGCAAGAGGCGATTGAAAGCTGCTTGGGTGCAGACTTCAAATGGTAATTTGAAATAGAG

          GGGGCAGGAAGTGAACACCGCCTAGTATGAAATACGTACGACGAGGTGGATTGGGCTTCA
          GGGGCAGCAAGTATACACCGACTAGTACGAGACGTGTTCGATGTGGGGGACCGGGGTTAA
          GGGGAGATAAGTGCACATTGATCCATAGAAATCTCGCCCTATGTGGGAGACCGACTTTGT
          GGCGACGAATATACTCGCCATCCCCCATACGCTTCACCCAGCCCAGGGATTTGGAGTCAA
          TGGACTGAACTCGTACGCGAACATATCTAAGTTCCCCTTCGCCCCACGATACGGAGTACG
          TGGGCGTGTTTTGCCGCACCAGTCGTTGACTCTCTACTTGGTATACCACACCTGAGGGTG
          GGGAAGGAGCTCACTTACCGTTCCCCAAGCGTCTCGGCCAGGTAGTTGGCGTGACAATTC
          GGAAAGTAGCATTAGTGCTGTTTCGATTACGTGCTAATTAGTACCCCCGTTAGACGCTTA

          AGATTGAGAGCTTCAGCTAGCTATAAACCATAACGCGGAAGGCGTCCCGGTAAGATCTCG
          AGATCGAGAGCCGCTACTACTTATAAGTCGCTACATTTAAGGAATTTCGGTTAGATCCCG
          CGACTGCGATTGACTTACATCTGAAAGTCAAAATATGTATGGGGTCCTCGGAAAGTACTG
          TAGTCCAAGGGCCCAGCTTATGGTGGATCGAAGATAGCATGTAGCTGTGGTAACACCTTG
          GTGTGGAAGTCCATTACCCTCCTACGATTCAACGACTCGCTGAATCCCTCTATGATCCCA
          GGATCTAGCATCGTTACCTCCTACTCGTCTCCAAACAGGCCCAGTTGCGACAGAATCCTT
          GGGCTCTGTACACTCGAATTGCATCTTTGTAATCAAATGGCGGAACTCGTCATAATAGGG
          GGACCTGCGTCCTCGGTATCGTATTGCCCCCTGCATTGATGTGGACCCTGTAGACTCAGA

          ACTAGCCTAATTAACGTGTACAGAAGTGTGGCCCATTCCAAGCGCCGAAAGAATGTGTCG
          GCCACTTTGAGTAACTCGCCCAGGGATAAGGTCCCTTCTATCCATTCAAGGAACGTTTTG
          CCTAATATTGGTAATGTATCGAGATATTCGGTTTGCCCTGCGTGTTGAAAACACTTGGTG
          ACTTATTATGGCAACGGACGCGTGGGTGCGGTCCCTTGCTCGTGTCGAAAGCCTATAATG
          TAGTACTACAGAAGCGGGCTGCGATATTAGATTACCCCAATTCGTGAAGGGTACTATCTG
          GATCCTCCCCGATGTAGAGTCTGAAGCTCGTTCGCCGCCCGACTTTCACTGTACCCCCCA
          TGCAATAACAGAGGCGGCGTTTACCATATGTTACCTTCTTGATGAGTCTGGGACAAAACG
          CACATTCTACACAGGAGTACTTCACTTTCAGACGTTTTCCGTCGTCAGTCGTTTAAGTTT

          ACACCTAGCGTCTTGTCGGTGCCCGGCAACGTCTCTTAGAGACTGACGAGGTGTATACTA
          ACTTCCAGAGTTTTGTTCGTATGCGGCAATGCCCTTAACAGACCGACCACGAGTCTACTA
          TCGGTATGTGCCTTGCTTAGGGGCAACCTTGCTTATGAGAGGTTCTTAAGGATCACGCCA
          TTCTACTGCACCCAGTCCACAAACTCTCGCGTCCTCAAGAGACTCATAGGTCGAGAGCCT
          ATTCCACCGGGTACTGCTGGGAAAGGCTCTAAGCAAGTGACCGCCGCCGATTGGGAGTTA
          GCACTAACTTACCGGCCCTACAGTACCGGCGTTGATGTTAGAGTGAGAGAGGGTCAGTCA
          ACCGGGAAGCCCAAAATTGCGAGTATAGTTTACGCAGATAGCATGACCGGGTGTAAAAGA
          ACCACATGGACTGTGTATACGGGCGTTTCCACTACTACCGGAGCATCAGCCAGCGAAAAT

          TTCAGCCGATATACTTCATTAATGACAGAATACCCACACCATAGGATAAGTAAGTCGCAG
          CTCAGCTACTATACCTTAAGAGCCAAAAAATACACGTGCCCCATGCTGGGTAAGCCGTAA
          ATCAGCTGAGATAGTTCTGAAGTATAGGAACGTCTGCGTCGGCAGACTCGCAAGAGGTAC
          CCGAACTGACAGACACCCTAATTACGAAATCATCCGTGCCCGCTGACAGGTTGGAGGGAG
          ATTTACTCCAGGACTACCGGACCAGGAAAGGAAGGATGTAGAGGAGTACGCCGTCCATAT
          ATGGATGCATAGCCCGATGGACAAAAGAATTGATCCGAAAGGGACACGAATCCACGAGCA
          ATGAATATGTAGGTTCAGGATCAGAAGGTGTGCATGTGTCATAGCTTGAACCGGTGGTAC
          GTACACGATTGTTCCTCCAAAAAGGCTGAACGTCCGAGTAGAAATTTCAACTGGGAGATC

          CGTGCAGGCCAGCGTAGGAAAGAGATGGCGGGCTACAAGTCTCAGCAATCGTGAGCACAC
          GGCGCAAGCTCGCAAAAGCGAGAGTTTACGGGCTACAAGGCTCCGCGATCGGTAGTACAC
          CATACACCCCCGTACAGGCGGGAAAAGATGCGGCTAAAGGTCCTTCGGCCCCCAACCTCC
          AGCACAGGTTCACAGATGCGAGAGCTCCGAAGGTAAAACGTTTTCTTGTTATAAGCGAAT
          AGTCTCGAAGTCGATTACTAGCCCTGCGGAAAGTATCCAAGTTCGTCATCGTTAATCACT
          TCCTCAGAAGCGGACTTCTGTACAAGCGGGGTGGAGAATAGGGTCTAGGTGATATCTACG
          GTTATGACTGCAGACCAGCAAAAACAGCGGCGGTGAATCGCTTGTTAGCTCTCAACCATC
          TGCATAGTGGCTAACAGGCCTCAACCGAATCTGTGTACGCTTTCTTTGTCGTTAGTTCCC

          CGCGGCTTAGGATATGCTGACTTGGCGAGCTACAACGATGCTTAGTAAGCGAACCGTGTG
          GGTGGTTTAGGACATACTGGTCTAGCGGGCTACAACGACGCATGATATGTGAATCGCGCG
          AATGGCCCAAGAATTACCGGGTTGGGGGGTAAAGATGGAGCCACGTGGGAGGTTTCCTCA
          AGCGGCTTATGGGATATGCGGCTGGGGGATCAGGTCGAGGTTAAGTTAATGATCGTTTTC
          AGCATCTCATAAAATCAGGAGCCGACATGCAAATCCGGCTACTTACATCACCTAGACGAG
          CTGGAGGTGGGTACTATGACGTTAATGGGGAGCGGTGGTCTAACCATAGAAGACGGCTAT
          CGTGGCCTAGGGACTCCGACGCTGGAGCTCCTCAGTAACTCTGTAAATGGTGTCGACACG
          GTCCGCTCAACGATCATGTATGTCGCATAGCTTCGTGTCCCATAGCATGATATTGCCTTG

          AAAACATGGAGAGTACTGTCTGGAGTCCGCCTCGTAGAATCTTTCGGTATATGATCTTAG
          TCAACGTAGGGAGTCCGTTGCGGTGCCCGTTTCGTAGTATTTTTCGGAGGATGGTTTTGG
          ACAGCCTAGCAATCTCGGTCTTGGGCAGGCCCCGTGTCTTGATCCGACATAGGTTTAAAG
          TGCCCTACCCCGGTCCAGTGTTAACGACCTTGTTAAGTACCTTATAATCCAGGCCCAACG
          CCAAAACAGTCAACAGTATCGATGATTTGCGTTGGAGTAAACTATGCAACGCACACATTA
          CTGATTCCACTTGTCGGGTTTGCGACATGCCCAGGGATAACTTATACCATGACGCAGTAA
          CCCGGGTTTAACGGCCCCGGTCGGCTATATTGTGGGGTAGCTTCCGCTGTCGCCTCGACG
          TTCATATTTAGTGCCAATGGTTCCTCACGCTCGGGGAACGTTTCTAGCGACCATTTGTTC

          TGCAGCTGATCTCCGCAAATTTTATTCATAGCCTTTTCGAGGACAGAAAGAGCGATTCCG
          TGCGATCAATCTCCAGGAATCCATACTATAGTCCTTGTGTGGACTGTAAGAGCGACACCG
          CGTAGTTGGCATCTGCTCACTTCCATCGCACGCCTCCTACTATTTGTCTAAGAGCGGCCG
          TTCAGTTATGCCTCTTCCGATAACGGCGCGAGTGGTTTATCGGCGGGAAGGGTGGGGATC
          GCTAGCTGTAAACCTGTGATTGGGAGTACTTACTTCTGGCCGCTTGGCAGTTAATGGCCG
          GGTTTATGGCCGTCACCGCCCGGGAGAGATCCCTATTCGACTCAAACTCAAACAAGGTTC
          CATCTCTATTCGCGCCGCACTAAGCAAGCACATGCAGTGCCGACTGTCGCACCCGGGTCA
          CGCCTTTGCGATCGTCCTTGATAGGGTATGCACATCACACTGGGCGGTGTCATCCCGCAA

          CCATAACCAGCCCAGCCAACTACAGGGTGCGCGGGTTATAAGGATAGCTCGTTGGATTTA
          CACTGAACAGGCCAAATAACCATAAGATGTGTGGGCCTATAACATAGCTCCTTGGAATAA
          TCCTGAAAACCCTAATTAGCTCTAAGCTGCCAGGGCTCCACAGTTGATTCATCGGGATAA
          CATTAAACACGCTTACACAATCGTTGAAGTCTTGATATCATAAGCCCGCTGTTCAGTCAA
          ATCTCAGTAAATGCATGGAGGGTCTACATGGCAAACCTCAAACACGAATAATCGGAGTAG
          TCAACGGGTTAATCATTAAGACCTTAGACGGTGGCATTTGCATGGGTGTCATAAGGGCGG
          CCCTAGAGCCTCCTTAGAACTCCGGGGTATGTACACATCCCGAATGACTGGTCCTACGAA
          GCCGAAACTAATCCTCAATGACCGCACCGTGATAAACTTACCTCGGGGACGTATGGAGAG

          TAAAAGGAGAGGGCAAGAAGCCATATCCGTAGGATTCTATCGATTGGTCGATTTTTCGCT
          TTACAAGAAAGGGCGAATAGTTATATCCGTTCGGTATTATCGATTGGTCGAGTTCTCGCT
          ACCTATGGCAGGGTTACCGTTAGGGGAGTCAGGCGCCTCACGTCTGGACGATTCTACACA
          TCCCACAATAGAACAACTGCTATTAATGTCCGAAGACTAGCGACTAGACGTTACTCGCTT
          CCCGTGGATAGCAGAATGGCTTGTGGCGCCGGATAATGGGTGAACGTCCAATCCAAGTTA
          CACGGCGGTAGAACACGTTTAAATAATGTAGGACGGTTCATAGTCGGAAGACGCAGGGTT
          CTACCTGATCCCGTAACTGCAATTCGCTGTTTGAGGGATTTTGCCGGCCGGCTCGGAGCG
          TCTCCCAAAGAGGCATTAATCAGCGATAGCAGGAGGGCAGCGGCTGCGTCTGTTGTCTCT

          CGGGACTTTCATTTCCAATCTCACGAGCGACATATATCCATCTTCTAGTCCTGGAAGCGC
          CGTGCCAATCAGATCCTACCTAATAAGCGATGAATACCTTGAAACTAGTTCTAGAAATGC
          AGCACTATAAAGATCAAACCGTACAATTGACGTGGCTTTAGTTCGAAGTCACCGAGCCAT
          AGAGTGCACTGCCACTTTCTCGATTAGCGGAAGGCGTTTGTTTATGAATATAGAAATAGT
          CTGAGCGTTAGATGCCTCCCCCGTCGAGATAACGGAATGAGCTCATCTCGTTATAAATGA
          GCTAGTGTTAGTAATTTACTCCCCCCATGATATGACAAAAGCGACCCTAGCAGGGAACGA
          TGCCACGGTTGTCCTACATTTTGTAATCCGGTTACTCTACTACATCCAGATCAGAAGCGC
          CGGTGATCACGCAAGCTCTCTCATAAGCGCTGCGTAACGCGCTGGTGAGTCCTGTAGTTT

          CTGGAAAAGCCTCTAATGGGGGGCAAGTTCGCCCCCCCACACGTACAATCATATCATGTA
          CTGGGAAGCTCTGTGACCATGGGTAATTTCCGTCGCTTGTACGTGCAAACGCATCGTGCG
          CCATAGAAACCCCTAACCGGGGGTATACTAGGACTTTCGGAAATACAATTGCGCCATGCG
          CGGCGATGACCCCCAGCCCGAGGCATATTAGTAAACTAGTGGGTTTAATCGTTTCGCAAT
          GTCTAGCACCAACGAATAGGGTATTAGGGGAGTAATACACAAACGGGCCTACCCTGTCGA
          CTACAACACCATTGTACAGAGGGCACAAATAGGTTCATTAGCGTAGGTCGGTGTCACGTG
          TCACGGCCTGTGAGTGCGGAGAGTATTGCGAAGCCGGCGCCATCGTAGAGCTCCAATAAG
          TCCAGGAGACCTATGTATACTAACCACCCTGCATGTTAGACACTAAAGACGCTTAGTTTA

          CCGACCAGCATACGTCACGTCAGCAAATCGAGGATAGTTTAAGTGCTACACGACAGGCCT
          CCGCCCGGTATACACCCAGTGGGTAAACCATGGACGGTTTACACTCTTCTCGATGGCCCT
          CCAGCTTGCGCCAGCATTTTCCCTAAAATGAAGGCTAGTTGAAAGAAATTTGAGAGGCTC
          CTATTCTCTGCTAGTCCACTGCAGTCATAGGAGACGCGCCGAGGAGTACACATCGGTCCT
          TTGTACGGTACGGACGTAGCCTATGTAACGGATGGGAGGAGGATCCATTCGTCGAGTTCC
          CCGCACTTCATTGGGAATCTCTAACTACCGAGGGCGCACAACGGTCCGGAATAGGGGATC
          CCGCACCAGTCCGGCACGAGTTATCTGTTGGAGGCCCCGGAAAACACATTTGTGCTACTC
          GAGCACAGAGACCGCGGTTATTACGTTCCGAAATCGCCTAGGAATCTGCAGGAGAGTATA

          AGCACTGAGTTGTCTCGGCGTCTACAAAGAAGGTAAGCGAATACTTCCTGCGAGGGCCCC
          TATGAGGGACTATCTCGCCTTCATTAGTAAACGCACCCACGCACTTCCTGTGAAACCTCC
          TGTGTGAGGATGCGTCAGCACTTTTAGTGAGCGTTCGCCTTTGTCTCTTGCGACAGAGCT
          TGCCCTGCGAGAGTCTTGCAGACTTACCGCGAACTAACCAGTAGCTCACAGGACAACCTT
          GGAGCGGAGATAAGTTCCGCAACTCCCCGTGCCCTCGATCAGCAACTCGACGACCTTTAC
          ATTACACCAGCACGCCTTCGGTATCTTGTAGTACCTAGTTGTACATCCAACCAGCGTCTT
          TGCCTGGCCGACGGCTTGTCATCTTCTAAAGTACAGCTTCCGATGATTGATCAGAATCCA
          CCTTTGCCGGCAGGCTTATCCGTCCCCTCAGCCCTGCTCTGTAGCGTAGGTACGGGCTTT

          CGCATAATACGCGTCGATCCAGTGCAGGGGGCTACAAGAT
          CGCATAACACGCGTTGATCCAGTGCCGGGGGCTCCAAAAT
          TGTTTTGTTCTAACTGATCCAGCACCGATGGTCCCGGCAT
          TGCCGGACGCAAGCCGCCTTTGTACTGAGGACCCCGCGAG
          GGTAAAGGAGGGGATGTCCGAACTTTTCAGATTTGGAAGG
          ATCTAAGATCATGAAGGCACAGGGTTAATGACTAAGAACC
          GTCTTAGAGCATAAGGTTAAGGAGCCAGATCTTTGGAAGA
          TTCTTAGTTAGCGTGATTCGGAATCTGTAGAGTCCAGTAC

