 8 1000
t1        GTGGCAGATCTCGCGAATGAGAGCCTCCACTGCGAACTATAGTCGTGAGGTACATTAAGC
t2        GTGGTAGGACTCGCGCATGGGCGCCAACAATGCGAACTACCATCGTGAGGCATGTCAAGG
t3        TCGGTAGAATTTGAACTTCGGACTGAGCGGCGAAAGCTAAAGATGCGAGTCACCGTATGA
t4        ACAATAAAATCGTTGACCGAGTGTGGACGCAGGACACTAAAGCCGGGCGGCGCCAAGCGC
t5        CGATTCAACGCCGCGCGTGGGGGTGAAGACAGGATTGCGAAGACGTGAGTTGTGATTAGA
t6        GTGCTAAAGCTTGAGGACGAGGGTGAAGAGAGGACTCGGGAGCTGAGAGGAATCTTAAGA
t7        GATTTCGGCAGCATGTTCGCGCGGGGCGCCGGCGTACCGCAGCATCTCAGCTCGAGTAGC
t8        TATTTCGGCAGCATGCTAGCGCGGGACGCTGGGGTATTGCGGCAGTTTAGGATGAGTAGC

          AGGTAAACTTTCTCTACTTCACATGGACCCTTTGTTGACACACCCATCTGGAAGGAAGGA
          TGGTACACCTTGTCCCCCTCACGTACACCCATAGCTGACACACTCCTTTGAAGGTAAGTT
          TGATGCCCTTCCTTTGTTTGCCATAGGCTCAAGGTTAGTACATCCTTCTGGTGAAAAGAC
          TCGACCATTCTAAGTACCTCACAAGGCACCGTGGTTAGAACCTGTTTTTGGTGAGAGCTC
          CTTTGCGCTTCGCCAATACGACGACGGCCCCAAGTTAACATATGACTTAGGCATAAGCGT
          TCATGTTTTACGTTTGCTCCATAAAGCGGTTCAATTAACACATAACTCGGGTGTAGACGT
          TGCCGACCAGCTTCCTCCTCTGAAAAAATTCCCTTCCCCATGTTTCTAGGAGGACAACGC
          TGCCGACTAGTCTCCACCTCTAAAAACCTTCCCTTCCCCATGTTTCTAGGAAGAAGACGC

          GTGACTTAGTGCCGCTGTTTACCCGTCGTCAAGGGTGTTCGCCATATAGCGGTTGTTGAC
          GCTAGCAAGTATCGCTCTACTCCTAGCGACCGGGCTGACAGTTACGCGACGGCCGTGGAC
          ACCAGTTAGTAATTTTTTCCGTCACCCGTCATACGCGGCACTTCTACAGCGAGCGTGGCT
          ACAATTTAGCGTTACTTTTCATTCTACGCGTAGCACGGTTGTCGGTCGGTGAGAGTAGTA
          ACAGATTAGGCTGTCTTTATCCCATCCTTCCTGCTCGGGTGTTGAGAAGTATGTACAAAT
          ACAAGCTAGCATGTTTCTTTGCCTCTTGCCCCGCCCGATGGGGGGCGAGTGCGTTCGAAC
          AAAATACTGGCACGGAGCTTAAAGCCGATATTACTAGGGAGTTCGCTCAGGATCACTGCC
          GAGATATTGGTGCACGTCTTAAGGCCGATATTCCTAAAGAATTCGCTCAGGATCACTACC

          CAAGGCTACGAGCCTATTACCTTCGCATGCAAAGATAGATCGCAGATGACTCAGCGTACA
          CAAAATTGCGTATGCATTACCTTCACATGTACCGAAGGATTGAAGTGGATTTGTTGTACG
          CCATATCGAGAACGATTCATCATTGAATGCGTAGTTGTAACGCAAATGCTCCAGAGTATG
          TTAGCCCGTTCTCTCCTCACCCCTAGCTACGAAGATCCGGTGCAAATTATGTCAAAAAAG
          CCAAACCGTCCGCGGTATCTCATCTTAGCCGTTGATAGATTACAAAAGACATATAATATA
          TCAGACTGTCAGCGATTCCAAATAAGATGCGGAGACAGACCGCGAATCCTGCAGAAAGCG
          CTGCATTTCGTGCGGAGAATCTAACAGTGAGTAATCCTATCATGCATTAGTGTGCCCGGA
          TTGCATTTTGTGTGGAGGATCTCAGGGTGAATAACCTGATCAAGCGTTAGTTTGCCCGGA

          GTATCTCTAGCCTTAAATCATCTCGACGCAGCATTCTTGATGCGACACTCTTACCCCCCG
          ACATCTCCGATCTAACATCGTCTAGGCGCCACAATCTCCCCGCGCTACTCTCGCCCCCCG
          ATACTTTAATCCTCAGACTATCTGGGTGTCGTTTACCCGATGGAGCACCTGTATTGCCCG
          GTGATTCTAGCCTACGAATATCACAGCCATCACTTCTCGAAATAACACGTACCTCATCTG
          GCTATATTGACATCACCTAATGTATGACCTATACTCTAGATATAATACCTCAACCGTCCG
          ACGATCTCAGTCCCAGCTTCGTTTCAATGCCAACTCTAGATTTGAAGCCTGTCTCGTCTG
          AATTGTCCAAGCCCGACTCGTAATGGCCCCGAACCTCCGTCGCAACGCCTGTCTCCCGTA
          AGGCTCCCAAGCTCGACCCGTAATGGTTCGGGACCTTAGTCGCAACGCTTGTCCCGCGTA

          GGTCCGAGAGATCAGGCGACAGCAGTCGTGTAGTATTGAACTTGGCGTAGTTAGCGGGGT
          AGTTCCATAGACCCGGTGAAAGCGGTCGCCTAATATTGAACATGGCGCGGTCAGCCGGGT
          GGACCCATGGACTCGATGAAATTCGAGAGCTAATATCTAACATAGCGCACTCCCTGGCTG
          GGCCACGTACGTTTAGCATGAGATGGAGCAATACTTTCAACGTGATATGATCCAAGGAAT
          AACTGTCTAGTCCAAGTATTCCCAGGCGCCCGAGAGAAAACACGACACGATTAGTAGAGG
          AGTCTTTACGACTGAGTAGTAATAGCCATCCGCTACGTCCAGTGACATTCATAGCGGAGA
          TGACCGAAAGTGTACAAGTAAGCAGCCGTATTATCAACGCTCAGCTACAATTCGAGATCG
          TGACTGAAGGTGTGAAATGAAGTAGTCGTACAATCAACGCTCAGACACAATATGGGATCG

          TGATTAATGCATTACTGACCGCGAGTTGTAATCGGAGTGCCATGTTGCCCCGGGAGGCAT
          CAATCAAAGCTCTCCTGGCTCCACGTCGAAGTCGGAGTGCCTTAATGATCGGGGAAACGA
          TGATCGCTCCTATCCTGGCCGTGAGTTAGAATCGGTGTTTCATATCGATTTATACGACGT
          CGGTGTGTGACTCTCTTGCCTAAAGTTACGAACGGTATCAAATACCGACTTAGGAACGTT
          CGGTAAGTCCTCTCTCAGTCTCGAGCAATAAGCGGAAGTATATATAGATCCGGGAGATGT
          GAATGAGCATCATCCTAGGTCAGGGTTAAAAGCGGTAACGCAGATTATTTCGGGAGAAGC
          CGTAGACGGTTCTTTTTACTTTCGGCTATGATTGATAACACAAGCTTACGGCCCAGCGAC
          TGTAGACGGTTCTTTTCACTTTCGGCTATGAATGATCGTATAAGCTTACGGCACAGTGCC

          GTCCCATACTTCGGGTGCATTTTGGAAGTAACAAGCCGCCAGCCGCGGTTCTCGGCTGAG
          GACTTAAACTCCGAGCGTATTTGGGGGGCTACAAACGGTCCGTCATGGTTCTCGGCTCTG
          GCTACAAAATGCGGGCACGTATGTATGGCCATAATTAATCCATCGTGGCTCGCGACCCGG
          CTTTCGAACTGCGAGTGGATTAGGACGGACATCAAAAGTTCGTCGTGGTACTGGGCTTAG
          GTCATAAGGCGTGAATGCATTTGGTTGGACACTAATACCCTACCACGGCACGAGCCAAGC
          ACCACAAATCGTTAGCACATTTTAACGGTGAGGTATGAGCCACCCCGCCTTGCGCCCCAA
          TCTCCCATCTGTAAGGCATTAGAGGCAAGCATCTTAACTCCATCTTTGTATTCGGATCAT
          TTTTCCATCCGTGGGACATTTATGACAAGCACTTCGATCTCATCATTGAATCCGGTTTAT

          ATAAATAAAACCCACTATCAGGCGGACCGCGCTTTCACTCTATGCGTCGTTTGCATTACA
          GAAGATACAATTCACCATCAAATGTACCGCGAAACCATACTACCTGTCGCGTGTCCTAGC
          GGTTACATCAATTAGAATTAGGAATACCGCGTGCATACACGCAGCATCACCTTGCTCGGC
          CGCAGTATAATTCACGATTAACAGTTCCGAGAAGAAACACTCATCGTTGTCTGAATTAGC
          GTCAATCTATCCGCCATCTAGATGCATAGGGAGACTGAGCACATTACGGTGCGTACCATG
          TGCAATGTAACCGGCAATAAGCTGTAAGGGGATACCGTACACATCACTGGGTGTCCTGGC
          CCATGCGTGAACGACAGTTAGGGCCCTTGACATCAGGAACGAGTAATTGGAGATTTTGTG
          CCATATGTGGACGACCGCCAGAGCCATTGACATCACGCACGAGTGATCAAAGGCTTTGTG

          CTGCCCAGATTGAGAGCGTCACCAATCCTGGCGCCCAAGTCTGGGAACGTCGCCCGCAAG
          CTACCCCGCGTGAGAGTGCCACAAGCCCCGGTGTCCGAGTCTAAGGGCGCTGTGTGTGAG
          CGTTCAAAGTTGAGAATGATACGAGCCCCGGAGTTCGACTCCGAGTACATGGCTTGCTCG
          GTACCCACAGCGGGTGCATAACGGGCCTTGCTACTCGATTTTGGGGACATGAACGGTGCG
          CTCCACACGGCGGATACATGGCGACATCAGTCTTCCGATCGCAGGAACGCTGCATGTGTT
          CTACCTCAGGTGGGGGGATAGCAAGCTCTGCTGTCGCAAGTTGAGGACATGGTCCCTATC
          CAGTAGATTGCGCGGGTCCGAAAAAATGTACAGTTAGATTGGCTAAGGACTGGCCTCGTG
          CAGTCGATTGCGCGGATCTTAAAAGATGTACAGCTAGATTGACAACGCACCGGCCCCGTG

          TCTAGAGAAGCTGCTTCCTTCACGTTCGCCCGCCCGTTCTTAAGTTAGAAATTAGGGGAG
          TCCAGTAAGACTGTTTCCTCCACTTTCACACGCGGGTTCCTGAGCTAAAATTCAGGGGCA
          TTGAGAATGAGTAATCCCACCACCGTTGCTCATCCGCTCCTCAGGAAAGATTCGATGACG
          ACAAGCGGGCGCGTATTCCTTATGAAGGTCTACCCCCTACTGAACTAAGCCTCCGCGGCG
          CCGTGGGCAACTTTTTTCTTCATAGAAGCAGGTTGCATCACAAGTAGAGACAAGTATATG
          CCAGGTGCAACTGTCACCGCTGTAGGAGCTCACCCTTTGTCGAATTAGAACAGGGAAGCA
          TTTGGCGTCAAGTAGCATGTCTCTGTCATACGGGGGTGAACTTTAACACGTCGGGATGCG
          TCCAGCGACAAGGAGCTTGCCTTTGTCATATGTAAGCGAATTTTAAAATGCCGGGATGTA

          TATGGGGGCAGTGGAGGACAATCACGAAAGTGAGCGTAACCTGCGGAGGGATTTTCAAAC
          TGGGTGAGTAATGGGGAACAATTGCGTATGCTCGTGTAGACTGCGGAAGAATTTCGCAAT
          CACGGGACAAACAAAGGCCGACTACGGAGGCTCGCGTGGACTACGTCTTGACTCCGCACT
          TAGCCGCCTGATAGAGGACAATTTCGGATGTAACAGAAGACTGCGCGTAGGCTTCGTTGC
          TACGTCCACAAGGGGGTAAGAGTTTGAATATTAGTATGTTTTATGTGTGGAATCTGTTCT
          CATGCTATCGCCATAAAACGATCGTAGTTGTCTGTAAGCACTGTACGTGAATTCTGTCGC
          CGGTATGGCGAATTGAATGACTTGAAGGACTATACGCTAGTCGTTACAGGCCTGTGATGC
          CAGCACGAGGAATGGGATGATCCCTAGCTCTAAACGCTGATTGTGACGGGCCTGTGGCGT

          TTGTTATGGCCTTTGTCTCCACAATGTGAAAGTGTCCACAATCGTGCAGGGAACGCGCTA
          CGCTCAAGTCCCGCAGGTTCAAAATGTGTAAGTGCCGACAACAACACAGGGACCGCGCTA
          TGCTTAGGACAATAGCACTCACAGTGCGTAAGTATTGTTTATCAGATAGAAACTCTGCTG
          CGACGTGGCTCCTTGGATCAGTACTGCATAAGTAATTATAACGACTTAGTTACTCCGCTA
          CGTTGACGATCTTACAGCTCTTATCGTGGAAGCTGTCATAATACTGTGGGACCCGCGTTA
          GGTTACGAATCTTTCCGTTTGTATTGTGGACCCGGTTATGCTGCTGCCGGATCCGTATTA
          AACGCATTGATACAAAGTGAACATAAATCTTGTGACATCACACTCTTCAGTAACCCCTGG
          AACGCATTGATTCAAAGTGAAAAGAAAACTTGTGAAACCATACTTTTTACAAATCCCAAG

          AATGAACCGGGCCTGTATGAGAATGTCGCGAGTCGCCCACCTGCAGCTGGGCAAGCATGC
          AAGGATTTGAGCTCAAGGGAGCTCGTGGCGGCTCGCCCGTTTGCATATGGGCAGGGACGT
          AATGCATTGGGTTCGAATCTGGCAGTCGTAAGCTGTTTGACCGTGGTCGAGAAGGGGCCT
          AAGGATTTACAATTAAATAACATAGTAGCATGTGCCTCGTCTGCGACAGAACAGGGAAGC
          AAGCAGCCTTAACTAACTTTCAAGGTTGCGAGTGCCTTGTACATGGTCGAGTCGCGACGC
          CTTCACCACCAACTAATCCGCTAGTTCCACACTAGCCTACCCGCACGCGAGAGGAAGGGA
          AAAAAATACTACCTGGACGCGCAACCCAGGACTCGACTGATAAATAACGCGCAGAGCGTT
          AATGAACATTACTCGGACGCGCTATGCGGGACTCGGCTATTAAAAGCCGCGCTGGGCGTT

          TGACGATTATTCCACAGACTTATACTTTCTACCAGTTCATGCAAGTAATCCAGAAACTAA
          TGATGAAAATTCTACCGACCTGAAGTCTCTACCAGTCTATACAAGCAGTCAAGGCACTCA
          CGCCGAAAAACCTACAACACCTCGATTTACTCCAGCCCATATGGAGAGTCAAGAAATAAA
          TCCTTAAAATTCATTAGCACTGCGGAGTCGACAAGCCCACCCTAGCTGTTAAGCACTACG
          TTACGACTAGGCAATCGTTGGCTCCCCTCCACCATCATATTCGATTTATTAAGCACCTCG
          TCCCGAACACTCGACGGTGCTGTCATCCCGATCGTCCCAATTGAGCAATAAGACCACTGA
          TATGGAACATGCAAGTATATTAATTGTCCGGCTGAACGTGAAGAATGGACGCTCGAGATA
          TAAGTAAACTGCAAGTATACTAACCGCTCGGTTGAACGAGAAGATCGAGCGCCCGAACTA

          TCTGACGTTACAATTCCTTCGGACGTACTTCGCCTCTGATCATCGCAGAAGTTGGTACAA
          TTCGACGTTACAACTCTCTCGGACAGACCTTGTCCCTGATGACCGAGCAAGTCGGTTCAA
          CCCTACGTAGTACCATCTTCGGGCGGCAATGGTGGTTAGATAACGCGCATGCAGATACGT
          TGCGACCTCGAACTTTTGTTGTGCGGAAGTACCTGCTACAGGTCGAGTGAGATGGTACAG
          CTTCACATCGTACCCATCTTGTATTAGGGCAGATGCTAAACATCTTGCACGGTTGCATGT
          CCACACTTCGTATACTCTTTGATTGGAGGTAGTCTTCACTCGACTCACCCACTGGTAAAA
          CCCGACTCTTCATTTCGCCTTACAGGGCAGAAAAGCGACATACTAGGGGAAGGGTGAACG
          ATCGACGCCTTAATCCGCCTTACAGGCTAGCAAAACACCCTTTTAGGCGAAGGGAGAACG

          TCATCAGCGCCCGTTATATTTCCTTAAATTTTTTCGTGCA
          TCATGAACACTCGCTTCTCTTTTCTAGATCTTTCCATGCA
          AAGCTCTTGTATGGTCTTTCATCTCGGGATATATTGTGCT
          TCGTCAGTGTGGGGCTTATCCCACGAGATTTACCTGCGTG
          ACCACAACGTCCGTCTTGCGGCTCTAGAGTTGCTTACGGG
          CCCATCTTGGACTATCCTCTGGACCAAAGCCATTCGTGAT
          TTTGATCGATATCCCGTCCAGTGCCGGCTACTTCTCCGCG
          TTTGATCGTTATTCCGTTCAGTGTCGGCTACTTCTCTGCG

