 8 1000
t1        GAAACTCATAACATGCTCGCTGCGCGGTGGGTCGTTCAAAAGCGCTAGACGGTTTGGGCA
t2        GAAACTCATAAGATGATCGCTGCGTGGTGGATCGTTTAAAAGCACTAGACGATCTGGGGA
t3        CCAAGGTACGATCTGGAGCCTGCGCCTCGAGCCGTCTGGGGGTGCCATTACTTGTAACCA
t4        TGAGCACGTATCACGAGGTCCTTGCACCGGGTCATCGAGGAACGATGATAGCTACGAGTA
t5        TCACCAAAAAAAACAATACCCATACCCCGAAGACCCAGATGGCACGCCGCACAAAAATTG
t6        TGAAAGAGGGTTCATACCGCCACACCCATACCACAAAGGGGGCACAAACGGAGATCAATA
t7        CGCGTGAATAACCGAATTGTTGGGATTCGGTTCCCCTACCACCAGCCATGGGTGTTTCAG
t8        CAACCTCAATGAACCATAGCAAGGACTTAGCAGACTTCCAGGTACCCAAACTCACGAATG

          GCCCGATAGTCCAGGTGTTTTTTCCACGCCTAACCATGTCCTAGTACCGCATCACCTCAA
          GCCCGATAGTACAGGTGTTTTTCCCACGCCTAACCACTTCCCAATATCGCATCTCCTCAA
          GCGCCGCAGACCTCGGACTTGCTTGATACACAGTTTCGACTAAGTACTCCGCACCATTGG
          GTATGCCACATTCGGCGGCAGTTAAATTTACAATCAAGAATAAAGTCAACATAATAGGTA
          ACTGGGCGCAGAGAGCGCCTGACCTTTTGGTAACCAGTGCGGAGATAGGTGACAGCCCAG
          GGTGGGTAGGCACAGTGTCTGTTCGACTCGAGATCATGGAGGAAACTTGCACCAGCTGTG
          TCCAAATCATCTGAGTAATTGGACAAATCTTTAACAAGACTAAGGATCGTTCTGCGCGGC
          TGCAAGTGGATGGGGTCTCTGCGCAGCTCTAAAACGAGGATAAAAAGCGCCTCCCTAGTA

          CTATATAGGTCCTGACCATCTATTCGTGCCGTGTGAAAGTTAGGAATGTAGGTAATCTAT
          CTATCTAGGCCCTGACCATCTATTCATGCCGTGTCAAAGTTAGGAATGTAGCTAATCTAT
          CGGAAAATGGGCAGATAATCCCATCTTGACGAGTGCCCCCTCAAAAACTCTATGATTGCT
          TCGCGAAGGGACTAATCGTTCCCTCCTGCCACGGTCAAGCTCGGATCCTAGTTGTGTCAA
          TCGTGTAGGGATCCCGCTTTCTGCTTCACGACGTACGTCATTCGCAGAATGGCGTACCGC
          CTGGGCGATCGGCGCGAACTCAATATTACTACGAATAAGCTAGAAATGTCGAGGTTTCGA
          CAGTTAAGGGATTACGGGTTTTCTATCGCTAAATATGTGCTTGGTTTCACGCCTAGATAT
          CTATGAGGGGACCGTGTGTCCCATGCTACCCTCTACATGCTATAATCGTTAATAAGATAT

          AGGAGGCTACCCCAGATTACTGACCAGTGGAGAAGCCCTTTCAACCGCGCGACCAATATA
          AAAAGGCTACCCCAGATCACTGACCAGTGGAGAAGCCCTTAAAACTGCGCGACCAATATA
          GGGGGGACGTGATAGACCCTCCGATAATTTAATTAACCTTCGTTGCTGGCCACGACTATT
          GGGAAGGCCTTTTAATCCATGTGTCGGATAAAATATTCTGTTCAACGCGTAGCTATCCTT
          TGATCACTTATGCTATTTTTACCTTCCGAGCGGCATCTTGTCAAGAGTGTAGAAGTCGTT
          TAGATGAAACATCCCTTCCTGCAGTCAGGGCGACTTCCCACTAAGCGGAAGGACGCCCGT
          CCGTAGGAATCTGCATTACTATTACATCACAAACAAGCTTCTGCATTTCACAATGTCCGC
          TAGTGGATATGCGCTCTTTACTGACTGTGACGGCGTTAGACTAGGAGATCAAGTAGTGGT

          TATCAGGTACGTTAAGACTAGACCTTCTATATACGTTTTTGGGGGTCGGCCGTCAAGGGA
          TATCAGGCACGTTGAGACTAGGCCTTCTATATACTTTATTGGAGGTCGGACGTCGAGGGA
          AACTGCTGGCTCGGAGAATTATCGTCTAACAACCGCTTCTGGAGATCCAAAGTTAGCGAG
          CTCCTGCCACTACGATTATCCTTGCCCTACTAGTAGATCTGAAAGCATGAGGTCATGGTT
          CCGTAGCGGTCGAGATAATAGCGGCCTTGTTTGGGCAATTCGGGGCCGCAGAATTTATCC
          ACGCATCGGCTCGTATCAACAAGACACTTCCCACGCTTCTGAGAACCGCGACTTCTACTT
          TGGCAGTGGCCGAGAGATTTGAGATATTCCTTATGGCCATCTGGGTCGGGGGCTTCGGCT
          TACCATTAGCCAGGCTGTTGAATACACCCGTTATGTACTTCAAGGTCGCGAGCTGAAACT

          CTTCTGCGCAAATTTGTTGCGACCGGGGGGTTACAACGTCTGGGGGAGAAACGGTGAATT
          CTTCTGCGCAAATTTGTCGCGATCGGGGGGCTACAATCTCTGGGGAAGAAACGGTGTATT
          TATTCATGTGCCATCCTACCGGGCGAAAAAGCATTATATTTATGAGAGCGTCGGTTTATA
          CATTCGCGTGAATTCATCATTAGTGCGATGTTTCCACGTTCAGGGGATTGTTGAGATGAG
          GGGTCAGAGACTCATAACTGGCACTAGTGGCAGAACTGGACGCCATAGAACTTCGAGTGA
          AAGGGGGCTGTTCGGAAATGGCTCTGTAAGGTGCGCCGCCCATTGGAAACTTTAGCGGGG
          AGATCAGCAGCCCTCAAACAATATGAAAAGTTACGAAGCTCCATAGCGGGTTTGAATTGG
          AAGTTGGCGCCCCGCGAAAGAAGTGTGAAACTGGGCCGCTTCTCAGAGTACCTCAATGGG

          TGAAGTTAGTATCTACTGCTTTTCGTTAGTCTTGGTCGGTTATTAACTTTCCATTCAGCT
          TGAAGCTAGTATATACTGCTTTTCGTTAGTATTGGTCGTTTATCATCTTTCCATTCCGCT
          CGTAGTTGATCTGCCTGACCTAACGAAACTGATTGCCCGGACGTTTGTCCACAGCCCTTC
          AGATTTTCACAAGTTCGGATCATTGCCACTATCGGTCAGTTGTTACCTTTTTGCAACCTT
          TTAAATTAATTTCTGATCATGAATGTCGGGCTTGTCCTGCCCTCCTTCGTACAGGACCCA
          TAGTCTCGACTTTTGAGATCTGGCGCAGGTGCCAGTGCGCCCGAATCTGTCCTGACCTCG
          TTGCGTGGGTACAAGAGCGTGGAATTCTAGACCCGCTTATACCCCATTCGTCTGTCCTTA
          TAAAATTGGTTTAACAGAAATGACGCTGCCACCGACCGGTACCTTTTTGCCCCGCACTTA

          TAAAGTCAGGAGTTGGGAGACGATGCACATCAGAGACCTGGTAGGAACATTGGAGTAAGT
          TAAAGTTAGGAGTTGAGAGACGATGCACATCAGAGACCTGGTAGGAACATTGGAGTAAGT
          TAGAAGCAGCTTCTGACGAGCAGGCCGTAACATGGATTCAGCCAGGAAAGTTATGCGGTT
          AAGTGCAGCCATTCCTGAGTTGGCCCGTCCCCTAAACCCGAAATGGTCAACAGGGAGGGC
          TTGGTGGGGTAGCCCGTGGATGGACCGGAAGGTCGTATCACCTCTGCGGTCCATGTGGTT
          TCACGAAAGTGCCTAATCGTTGGACTAGCTAACTTCCCATGCTAATGGCTCAACGTCAAG
          CTGGCGTGTCGTCTGCTAGTTGAACCATACGACAATAAAGGCCAAGGAGTCTTCTCTGGT
          CCCGAGAAATCTATGTCAGAAGATCCTTTTGAGCCCCTAGACTTCGGAGCCAGCGACGGG

          GTCGTGGTTCTCGCATTAACATACCTACGCAATAAAGCCCGCTACTTGAGTCAGGCCCAT
          GTTGTGGTTCTCGCATTAACATACCTACGCAGTAAAGCCCGCTACTTGAGTCAGGCCCAT
          GCTATAGCCGAAAAGACGCCATCCTGAAGCTAGAAATGCTGCTCGATGCCTCAAAGCCAG
          GTTGGAACTGCGGAGATTTTATACCAAAGTAGAAGAACTCCCAGCATAGGTCTCAATCTC
          ATCGGAGTCCTTGTGTTGCGCCCCTCAGTTGAACACCCGAGCAGAGCACACAGAACTACG
          AGCGCAACCTCAATGATTGTACATCTGATCCGAACTCGAAATGGAGCACGCGTGAGCGAA
          GTTACGTCGGTCCAGCGGATTTTTTGCAAGGGGGTCAAGTCCGGAATATGCCATAGTGCA
          GAACTAGTCGTTGAGTTGATGACGCTATGTGGGATGGGGCACGGTGTTTGCATTACTGAT

          ATCTTATCGGGACAAGCAATAAGGGCTCAGTAGTAGTTTGCTCCATTTCTGAGCACGCAC
          ACTTTATCGGGACAAGCGATAAAGGCTCAGCAGTAGATTGCTCTATTTCTGAGCACGCAC
          TGTATGTTCGCAGACAATACTGGGGCAGCGTATTCGTAAATTTCGTATTCTTCGACTTTT
          ACGGGATCCTGAATTAAATTGTTGCTCCCATAATAGCATACCTTGTTATTGTTTATGCAT
          CTTTTGGTTGAGGATCAAGTGTGACACCTGTAGTAATCGAGCATGCCGCGGAGAATACAT
          CTCCTTGTCTGCAACCAGAGATCCTCCATGCAGTACTATAGACTCAAGTTAAAAACAGTC
          AGTCTAGGTGCGAGCGAATCGAGAATCTCGTACTGGTTTAGTATAATGTCAGTGTCGCTC
          ATTCAGTTCACGCACCAATGATATACGCCATAGCAGCACTTTAAGTTACCAAGGACCTTC

          TTCAACTCCATGTAGTGCCCGTTCCTCGAGGATATGCGCTTCGCTCCGGCTGACAATCCC
          TTCAACTCGATGTAGTGCCTGTCCCTCGCGGAGATGTATTTCGCCCCAGCTGACAATCCC
          TCCATGCTGAAGCAATTAGGTTTGTACCAATCACTGGTTTCTGAGCCTTCCGGCTACGCC
          CATCGGCCAATGTAGCTATTGTTCCTCAAAGTAGCGCTTACCGTGTCCCCCGTTCAACTT
          CTCAGATCATCGTGTCATCTGTAGGCCCTAGGAAGGAATCTTGTTCAGTGTGTCTGTGCA
          GTTTAGTTACCGTTATCGTGGATGACCGTGAGCTATAATACTGCAGACACTATTCACGCC
          AATGAGGAGCCACAGTCCCAGATTACAGCAGAAGTGCATTTGCTATGCCCCCACAGCGCC
          TCTTTGGCGCACCAGTGCTAGTAAGCATTGGAACCGAACCGCGAATACCTCGACTGCGCC

          AATCTCCCTGACGTTAGGCCTGCAAGTTAAGACGCAGGGCAAGGTCTAGTAGAGCATTTG
          AATCTCCCTGACGTTAGGCATTCAGGTACAGACGCAGGGCTAGGGTTAGTAGAGCACTTG
          GGACATTAGTATTATAGTCATATACTTATCAAAGCCACAGTCCCAAGATTGACTCGCACA
          AGACCTTTGTATTTCAACCCAGATTGGGGTTATTTGGGGGACAGCGGTCTGATTAATCCA
          CAACTAGTTAGTGGTTATCACTTACGTCTCTAAAGGGTGGATTGATGGTCGAACCAAAAG
          AGGATCCCTAACGTCATCCATAACCGTCTCTTGGTAGTGACCTGTCTACTGAACTACAAG
          GGCGCCTTCTGCGCCGATATCAAGTCTCGTCCCCTACAGGGGCTCCGGTTGGTCCTTGAG
          CGTGTCTAGAACCCTACAGACCAATACTACTTGATAGGGTTTGCTCAACTTCCTTATAAG

          ATATGTATTTCGCGACCCAGGACAGGCAAGATCGGCCCAGCCGGCCACAGCATTATCTAC
          ATATGTATTTTGCGACCCAGGACAGGCAAGATTGGCCCAGCTGGCTTCAGCGTTATCTAC
          GCTTCGCTCCGGGGGTGTGTGTAAACTCAGATCTGATGCTTGAGTCTCCAACCTTTTCAC
          ACGCGCCTGAAAGGATTTAAAAAAGTATAACCTGGGTGCTAGGGCGTCGTCGCGAAATCG
          GTTCCACCGCGAGGGGTCTTCAATGACCGCCTTTATAGCTTGCGCTTCGAACTCCACGCT
          GGCTGCCTCCGGAGGACCCTTCTCAGCAATGCCTAGTGCTTGTTCCACCGCCTTTACGTA
          GCCTACCCTTCGATAATCTTCCGAAACCGGTCCTAGCATCAAAACTACGGTTGTTCCGCG
          GTTCACTTGGTGTTGTATCCGCGCAAAAGCGCACGACAGGAGAGATCCCGCGGACCCGTA

          TTCTCTTAATAGTATATCTACCAATTACCTTTTCGGGATGAGAACGGCCTTCCAACATAA
          TTCTGTCAATAGTATACCTACCAATTACTTTTTCGGGATGAGAACGGCCATCCAACACAA
          TGAGAGTACCCTCTTGCGCGTAGCTAAGCACCGCTACGCAACAAAGGTATGTAAAGCTTG
          GGGAGTCAGTGCCTACAGCGGCGCCCTTCCGGTTAGGGTGCCTAGAACACGGTTAAATCG
          GAACACCAGCCCCCAATGACGTTCCGAAGCTACAGGGATCACTAAGGTGAGCTGGTCTTA
          AAGAGTACGAGTCCCATGACGGCAGTCAACTCTCTCCGGCAGTACAGTGGTTAGGTTTTA
          AGAAATTAGGGTAAAGCTAAGTTGGAGATCCACTTTCCCTACCTGCCCAGATTCGACTTT
          GGGATGTAGCAATTAGAAGCACAAGGACTCCACTGATAGCACTTTGTTAAGCCGACTTCA

          ATCAGACATTCTTGGTTGGGGTACCTACATTGTGGGGCTTGGGCGGAACACGCTTCCAAC
          ATCAGCCATCCTTGGTCGAGGTGCCTACGTAGGTGGGCTTGGGATGAACGCGCTTCCAAC
          CTGACGAACTTTCTGCCACTAAATTAACACAGCGGGAAGCCTACGAAGTGACCCTGCGGT
          CACGGTACCGTCTAGCCCCCCTAGCATTCCATTGTGGAGCTTATATGATGCAGCCTCAGT
          CCGCATGACCGCATGCAGTGTGGTTGTAGTGGACACGGCCCGGAGTCACGAGCTATTCAG
          TCGTGCACTAAAAGGATGAGTTGCTGCACAAAGTAGGATCCCAGGTTCCTAAATCCATAG
          CAACTTATACAAGTATTTATTCATGACGTCACCTTCAGGCTCAAACTACGAACAACGAAC
          TCGACTGACCACGCGCTTGCCGGCTGGCTTGACCGGGGGTCTAGACAATGACCTACGAGG

          AACCAATAACGAAGCTGTCCTTCATATAGTTGCCCCCTAAGAAATGAGGATGCACTGACT
          AACCAATAACGGACCTGTCCTTCATACAGTCGTCCTCTTAGAAATGAGGATGCACTGACT
          ACTTCTTTCTGATGTCGACTATTCGAACCTGATTTCCCGAGGACTGTGAATTGGCGGGAT
          CGTCTAATTTTCTGTACATCGTTCGCTGCTGGTCTGCCCCGGTATCTGGATGGCCGGATC
          TTCAGCCGTTTTCAGAATCTGAATCACCTTCCACCAATGTAAGCAGAGAATAGATACACC
          GCTGGGCCTTGAATACAATTGTTCCATTTTTTGGTCGAATACGCGATGGATTGCCCCATT
          ACAAGGTTGCGTCTCTTACCAGTCTACGTGCATTTCAAATTAAACAAGGATAGCCGGCGG
          AACGGTTTCTGTGTCGAGCCGCTAGACATTATCTCCGCGTTGAATAAAGTTCGACGCAAT

          TGCCGAACTTCATCCGGTGAGAGCTATGATTGTGACACAG
          TGCGGAACTCCATCCGGTGAGAGCTATGCTTGTGATACAG
          TGTGGTACTTCGCTCTGTACGGTTCACGCGATTCGGAGCT
          TTGCGCAACCCACCCTGCCGGTATGACGTCCTTGGGGTTC
          CGCTATAGTCTGATACGCAAACACCTAAATTTTGGAACGT
          CAGCATGACTCAGCGCGTGAAAAATTAGCGCACGGCCAGA
          CGAACCGCCTCCTTGCACGAAACTAAAATACTTCGTGCGT
          TGCAGTACCTATTCGCAGAGAAATTTAAAGTTTGGCTTGT

