 8 1000
t1        CCGCGATGCTGCGTTCGCCGATTTTCAATAGCCTATTCCAGTCACCGCAGGTTGGTAGAA
t2        CCGCAATGCTGCGTTAGCCAAAATCCAATGGCATATTAAAGTCATCGCAGTTTGGTAGAA
t3        CCGCAAAGCTGCTTTCGCTGGTTCACAAGAGCACGTATCAGTCCTCGTCGTTTGGTAGAA
t4        CCGCAGAGCTGCTTTCGCTGGCTCACCAGAGCCAGTATCAGTCCTCGCCGTTCCGTAGAA
t5        TTGCCGTGATAAAGCCGTAACTCTAGGCTAATCCGGTATATCGCGGGCTTGCTAGCGACT
t6        TTGTCCTGCTAGGACTGTGATACTCGGCCTATCCGGTATGGTGCGGGATTAGTTGCGATC
t7        TCTTGTTATCAAAGCTCACATCTTCAGCTTTCATGCACCAGCTATAGCCAAGAAGAAGTA
t8        TCTCGCTATCAAACCTAATATCCTCAACTGTCGTAGTGAAGCTACGGCAAAGGAGGAGCA

          CTCAGTTCATCTACCCCACTATACTCACGCCTTGCCAACCGGTCCGAACCACGGGGCCTC
          CTTAGTATATCGACCCTCCTTAATTCACCACCAGCCGATTAATCCGAGCCACGGGGCCTA
          CTTAGTACGTTAACACCACTTAATCTGTGTCCCACGTGTTAATTCGAACCACGGTATCTT
          CTTAGTACGTTGACGCCACTTAATCTATGTCCCACGTGTTAATTCGAACCACGGTATCTT
          CGTGCGCTACGCAATATAAACGAGCGTGTGTTGATCCGTACACGGGCTCCTCAGATGGCT
          CGTCCCCCACACGACGTTGGCACAGAGGTACTGGCTCGCTAGCCAGTTTCATAGGGTGTT
          CTCCCCATACGCAAGGACGTTATACAAGGGCCGATCTATTCATCGACTCTTTGGTATCTC
          CCCCCCGTATGCCGGGCTGCTATATACGAGCTGCCCTATTCATTAACTTTTTGATATCGC

          ATATTATACAGGGCTACTTTAGCTGGCAGCGTTCGGCCGGGTCAAGGGGCAACGTGAGAT
          ATATTATACAGGGCTGCTCTAGCTAGTAGCGCTCGTCCTGACCCAGGGCCAACGTGAGAT
          ATATAACCGAGGGTTGCGTCTACTAAATTCGTCCGCGTGGATCTGGAGCCGACGTGTTGT
          ATATTACTGAGGGTTGCGTCTACCAAATTCGTCCGCGTGGATCTAGAGCCGACGTGTTGT
          GTATTCTGTGGTGCTAGATCCGTGCGAGATGTCCCAGCCACTCTGAAAAGACGGTTGGGT
          GTACGACATGATGTCACAACCCTCCGAGATGCTCAACTGACCTTGATAAGGCTGCTTCAT
          GCACGGCTTCGTCCCCCATATCCCCGTAATAGTTCTGCGACTCTAGAAGAGCTCGGGCAA
          GCACCGCTTCGTCCCAGATACACCTGTAATGCTACTGCAACTCTAGGAGAGAGCGAGCGA

          CTATAATCCCGCGCAAAGGGCGCAACACCCCGCATTACTGTGGTAAGCCGTTTCTCGTTG
          CCATAATCCCGCGCGAACGGCGCTACACCCTGCATTACTGCTGTAATGCGATCCCCGTAG
          CCGTAATCTCGCGCAAAGGGCGTAACACACTGAGTTATTGTTGTACCGCACCCCCCGCGG
          CCATAATCTCGCGCAAAGGGCGTAACACACTGAGTTATTGTTGTACCGCACTCCCCGCGG
          ACCCGACTACTTGTAACCCAGGAACACCAGGGGCGTGTTCATATGGAGCCGTTTGGCCCA
          ACCTCATTATGTGTCATTTAAGAACATCAAGGGGGTGTCTCAGTGGAGCTGTATAGTCCA
          TCCCGACTACGTGCTATCCAAACACTTCAGAGGGGCGTTACTACGAAGCCGGTTAGCTAG
          TTATGCTCTCGCACTCTATGGTTGATTCAGAGGCCTGTTGTTCCAAAGTCGGTTCGCAGG

          TGTGGCAGGTAATTCTCCACCCATGACTTAGAGGTTTATTTGTCGTGTAAGCCCCGTTGT
          TGTAGCGGGCGATTCTCCCACTGTGACTCGGAGTACTATTAGTCGCGCAAGCTCCGTTGT
          CTTGGAAACAAGTTCTCTACCTGGGACTTAGGGCACTGTCAGATGTGCAAGTCCTGTTGA
          CGTGGAAACAAGTTCTCTACCTGGGACTTAGGGCACCGTCAGATGTGCAAGTCCTGCTGA
          TAAGGAGTAAGATTGCCAATAAACCATGTAGGCAACCATCCAGTTTGGGCGCGCGGTCGG
          GAAGTAATCCCATTAAATCTTATCTCTGTGGACAACTACCTAACTTGGGTGCTCAGTCAG
          CGAGGAGCTACAATTGTTTTTGCACTCACCAATTATTATTCTCCATGGGTGACCTATCGC
          CGGAAAGCTACAACTTTTTTTGTACTCAATAGCAGTTAGGAACCGTGAGTGCTCTATCCA

          TGTAATGTTCGCCAGACCATTGTGCATGCTGTAGGCAGAATATCGGAGGAATAACCCACG
          TGCGATGCTCCTAAGGTAATTGTGCATGCTAGAGGCAGAACATGGGGGGTAGAAGCGAAG
          CGCAATGCTCGTGAGGCCACTTTGGACGCTGGAGGCAGGATCTAAGACGAAAAATCTATG
          CGCAATGCTCGTGAGGTCACTTTGGACGCTAGGGGCAGGATCTAAGACGAAGAATCTATG
          CGTACCTCTACTCTAACCAACTAGACTTAGGCCAATGACGTAAGCGACCAAACGGCTGCG
          ACTGCATTCGCTCTAATACACCAGATACGAGTTAAAGACGCCGGCGATCACCCGGTTGCG
          AGCACATTCCTCTACGTGCACATGCTACGAGAAAGGGAGGCAGGTGCTTTCTTACCGGTG
          AGCATCTACCCTTACATGCACATATTCCGAGAGGGGAAAGCAGGTGTCTTCTTGCTGGTG

          CGGACATTCTACGTGGTGCCGAGTACGATGGTGAATTCGCCGTATTAAATTTCACGATTT
          CGAATATACTACGTGATGCCGACCACGGTATTGAATGCGCCGCATTATATCTCAGGATTT
          CGGTCATACTTGGTAATGCCGATCATAATGGCGCGTTCTTTGCATTACGATCTGGGACTC
          CGGTCATGCTTGGTAATGCCGATCATAATGGCGTGTTCTTTGCATTATGATCTGGGACTC
          ATCTCAACAAAACTCTACATTTTCAAGGCGGGCAGTCGAGAGGATGCCAACTTATAACCT
          AACTGCGGAAAATCCCACGGTCTCAAGTTCTCCAGCCGTGAGGTATGTGAGCTATAGTTT
          GCTTTTAGCGATTCGCACCTTCGTAAGCTCGAAAGTCGCCAGGGATGCAGACTCTAGTTC
          GCTTTTAGTAGTTAACACTTCCGTGAGCTTGAAAGTCGACAGCAACGCTCATTATGGTTC

          GGTGGAGCGGCACGGTCCGAGCCGTATCACGGGTGCCTCTCTAGTGGCCCTGAAATGATA
          GGTGCGACGGCACGGTACAAGCCGCATCACAGGCATCGCTCTAGAGGCCCTGAGATGATA
          GGTGAAGCAGTACGGCACAAGTCGAACATCTCACATCAATATCGCCGCCATGATATAACA
          GGTGAAGCAGTACGGCACAAGTCGAACATCTCACATCAATATAGCCGCCATGATATCACA
          AGCTTAGCCGCTAGTCAGCCGCCTTCCTAACATGCTCTCTTACAGCGGTCGGGAAAGGTG
          AGCCCAGTCGCACGTTAAACGCTTACCGGAAGGAGTAACCTACTATGGTCAAGCAAAGTG
          CTCCTTACTCTAAAGTAGCCGCCCACCGGAGCGGCGAGCTGCCTGATCCCGGCAGCTACG
          TTCCTTGCTGTAAAGTAGCTCTCTGCTAGAGCGGCGAGCTGTTTGATGGCGGCTGTCAAG

          AGGCCTGAAATACCGCATATCAAATTTAATGGGTGCTCCCACCTGAGTTGTTGGGAACAC
          TGGCCCGTAATAACGCATATCAAATTCACTGGATGTTCACACATGAGTTTTTGGTAACAT
          TGGACTGGAATAAAGCCTACTCCATTCAGTGAGTGCTCACACCTAAGCTTTTGGGACCCA
          TGGACTGGAATAAAGCCTAATCCATTCAGTGAGTGCTCACACCTAAGCCTTTGGGTCCCA
          GCCGCAGGAACGGAGGACAACGCGAGCACCCATCACCATTGACTCTGCACCGATGAAAGG
          ACCACCGGGACAGTTGGTCCCGACTTCGTCTGTTACTATCACTTTTGCGCTGACGCATGA
          CCAAGCAGAATGGACACAAATATGCCCCTTCACCCCTATCGCCTAGACCTTGCTAGTCCT
          CTGGCTAGAATGGTCAAAAACATGCCCATTTTTTTTTATCGCCTAAGCCCAGCCTACCCT

          CATTGATAAGCCGTTAGATAAAGCAATTGGTCTCTGACTCAAACTGCCGTATGTGATTGG
          CACTGACCAGCTGTAAGACACAGTTATTGATCTCTGCCGCAAATTGTCTTATGTAATGGG
          CACAGACACGTTGCTAGACACAGCCTTTGGGCTATGGCGTAGACTGCCGTATGTCACTGA
          CACAGACACGTTGCTAGACACAGTCTTTGGGCTATGACGTAGACTGCCGTATGTCACTGA
          ATTTAACAACGGATTCAGTTGAACGTTTGTCTCTAGGGACTCGGGCAAGCTCCAGGCAAA
          TTTCACGCACGCATCAAGATGTCCGTTTGATTCAGGGGGCCTGGTGAGGCTCTGGGCAGG
          GATCACCATCGAGCCCAGGCAACACACGGGTTTTGGAGATCCGGGATGCCCGAACTTGCA
          GTTTACCGTCGCGCCTAGTTACCCTGCGTGCCCTGGAGAACTGTGATGCTCTCACGTGTA

          CAGACCCATCTCATGCCGTGAACGATATACCAGCTCTTACCCCTCTCCTTGCTATCGCTC
          CTGGCCCATCGCATGCCGTGGAAGATATACCGGCCCTTACCCATAAACTTACTATAGCTT
          TAGACTCGCCACTTGCGGTGAGAGGTGGACCATCCCTTATCTCTGAACCTACCATAGCAT
          TAGACTCGCCACTTGCGGTGAGAGGTGGACCATCCCTTATCCCTGAACCTACCATAGCAT
          TCTGTGTGTGAAGTGTAGATAGGGGTTGTCACGCGAAAATCGCTTGGTCTTGGGATAGGA
          TCTACCCGTACGACGTACAGGGCAATCAAGCCGCCCTTACCATTTGACCTCCCAACGAGA
          TTTGATCTTAAGCTCATATTTGAGGTCGTCCTACGTCAATCCCTAAGCTGTTCGGTAGAC
          CTTGACCAATAGCTCACGATAGGGGTAGCGTCGCCTTAAGCTCTAAGCTAGTCGATCGAA

          CTTCAAAAAAGGGGATGCTTACAATTCGCATAGGGTTGTCCCGTGAGTGCCTCGCGGGTC
          CTTCAAGAAAGGGGTCGTCCACAACTCGAATAGGGTTATTCCTTGGCTAATTGACGGGTC
          ATCCAAGAAATGGGATTCCCACAGCTCGAAAAGGGTTGTTCCTTGGGGAATAAGCGGGTT
          ATCCAAGAAATGGGACTCCCACAGCTCGAAAAGAGTTGTTCCTTGGGGAATAAGCGGGTT
          CAAGGTCAGCTTCACGTCTCGCCTCCGCGGAAGGCTTGACCGCCCAGGGCTCTGAGGGAA
          CAAGGTAACCGTGACGGGGCACCTACGCGGAGTCCACGACCTCCGAAGGCCCCGAGACAA
          CAAAGAGCGCATCGTGTCTCGCCGCGGTGCAAGAGTTAGCGGCCAATGGCCTATGGGGAC
          CTTAAGGCGTGTGCAGCCTCCCTGCAGTCCATGAGTTTGTGGTTAATGACCTGAAAGGAT

          AGCGGAAATTAGTGGAGCCTTGCTGTCCGGGAGGCAAGCATAGGTGGCTGACGCTGCCGC
          AGCGGATGCTAGTGGGGCCTCGTTGTCCGTGAGGCAAGCCTAGGTGGCTGACGTTGCCGC
          ATCGGAAGCTAGAGGAGCTTCATTGTCCGCGCGGTAAGCTTACGTGGCTAATATCAACAC
          ATTGGAAGCTAGAGGAGCTTCCTTGTCCGCGAGGTGAGCTTACGTGGCTAATATCAACGC
          CCCGCGACTTAATACAATCGGCTCAACCGTTCTTATCGACACATTTGACGGCGCTAACGA
          CCTGAGATTTAGTAAAACTCAACCATACGTTCATGACGATACATTTGATAACGCTATTAA
          CCGACAACTTAATGGTTCTTCGTCACCAGATCTCGCCGGATTCCCGGGTAGTGTTGTTCG
          ATGACAACTGAGTGCAGACTGGTTATCGGCCCCGGGCGGAGTCGAAGGTAGTGTTGATTG

          GGGTTCACTAGGTGCTATATAAACAGAGTTGTCTGCCGGTTCCACGAAGGTAGGATGGAC
          GCGCTCATCACGTGCTACATATACAGAGTTGTCGCCTCATTTTATGAAGGTATGATGGAC
          GAGCTCATCACGTGCTAAGCATACAGAGTTGTGGACCCATTTCATGAAGGTGAGATGCAC
          GAGCTCATCACGTGCTAAGCATACAGAGTTGTGGACCCATTTCATGAAGGTGAGATGCAG
          GGCCACGGACGAGGCCGTAGATATACAGAAAAGCTCTACCCCCACGAAGAGATCTGTAAA
          GTTTACGGCCGCGACCATGGATATGAAACAGAGCTACATCCGTACCGAGAAGCCGGCACC
          TAGGTCGTACTAGGATCTGAACACAAACTTGTCATGTACTGTCATACAAAGGTCAATGAT
          TAGGTTGTACTAGGCCCCGAATACAGACTTGCACCATACTGACATACAGATGTCGAGGTT

          TGTTAACTAAAAGGCTCAGGGTACAGGAAGCCGCGCTGCGTAGTACTCACTTTCAACCTA
          TGTTTACTAATAGTCTCGGGATATAGAAAGCCGCGCTGTGTAGTACACATTCTCAACCTA
          TATTAACTAACGAGCCCAGGATAAAGAAGGGTGTGCCATTTAGTATGGATCTTGAACCTT
          TATTAACTAACGAGCCCAGGGTAAAGAAGGGTGTACCACTTAGTATGAATCTTGAACCTT
          CACCGATCTGAATATTCAGGCTCGACCTAAACAGAACTTCGTGCTTGTGCTGCAAACCCC
          TGCGGGTAGGTTTACTCGGGATCGATTGAACAAGTACCACGCATTTGCGGTGCAATATTC
          TGGGCGGAGAGACACCCAGGCCGCTTCGGACAGACCGCAACTGTTCTATTAGGAAACTAC
          TAGGCGTAGAAACACTAAGGCAGCTTCGGACAGATTACTGCTGCTCTGATTGGAAATCTC

          GTACAGTTACGAAAGTCATTTTAAGTGGGAGCTGAGTCTGATTCGCGGATCCAAACTGTA
          GTACACCTACGGAGGGCGTTTCAAGTGGCAGCTGAGCCTGGGATACACATCCAGACTATA
          GGGTAGCGACGGGCGTCGTTTCACGCGGGCACTGAGTCTCCATCTCGGATCCAGAGAACA
          GGGTAGCGACGGACGTCGTTTCACGCGGGAACTGAGTCTCCATCTCGGATCCAGAGAACA
          GCAATTTACGAAAACGTCTCATCGCGTGACGCCGTGAACATTTCTGGAGGTCTCTGCAAT
          GCAACCTTGGGTACCGCCACTCTGCATGGTGCCGAGGACATACCGGGAGAACCCGGCGAT
          GGTGTGTAAGAGATTAGTTCTCGGTGCGCGGATGCGGTCACTCCGGGGAGTCCAGATAGT
          GTCGTCGAAGAGAGCGTCTTTCGTTTCGGGGATGTGGACACTCCTGGAAGTCCTGATAGT

          TCAACACAGTAAAAAGTCCTTAACTGACTAATCGACCGCC
          TGAACGTTGTGAATAGTCCATAACTGGGTAATCGACCGCC
          CGATCGCTGTGAAGTGTTTATAACTTGGTACTTGGCTGCC
          CGATCGCTGTGAAGTGTCTATAACTGGGTACTTGGCTGCC
          TATCTTGTGTGGTTCGTCTTTGTACGAGTACTTGATCATA
          TATCTGGTATTGTCAGCCCTCGCAGGTGCGTTTAGTCACA
          TTTTTGATGTGATACGCTCTTATATAGGCTTTTTGCCTCC
          TATTTTATGTGATTCGTCCTTGTATGAGTCTTTCGCCTCC

