 8 1000
t1        GAGCGTGGGCGCGAGTGGTTTGCGCTTCGCTATGTGAGTTGCGCCGTCAACCAGACACAA
t2        GAACGTGGGCGCGAGTGGTTTGCGCTCCGCGATGTGAGTTGCGCCGTTAACCAGAAACAA
t3        GAGTGTGATCCCGAATGGTTTATGCATCGCTATGTGAGTAGCGCCGTTAACTAGACACCG
t4        GCGGAAATGACAGGGTAGACTACGCTTTCCTACGAGAAGCACCTTGATGACTACATATAA
t5        GCGAAAAGGACGAAGAAAGCCAGGTTTTTGTGGCAGGCTATACCAGACGATCGCAGTCGA
t6        GAAAATTAGGATGGGTAAACCGGGTCGCCCGGTGTGAGTCGTTCAGATGTCGGCCCGTCA
t7        GCGTGATGTCCAGGTGCGCCGCTACATTAGGGCCTGGTGTCCTTAGGCTAGCTTGCCTTG
t8        CTGTTCGGTTACAGCCCCACTGGTTTCAACGCGGCGTGGTAACTAAACTTTCAAGTACAA

          ACAATCAGTTCTACACCGTTTCGCGTTGCCTGGACGATACCGCGGTAAGGCCGTCTTACG
          ACGACAAGTTCTACACCGTTTCGCGTTGTCTGGACGATACCACGGTAAGGCCGTATTACG
          ACGATCAGCGTTACAGCGTTCTGCGATGCCCGTACGGTACGATGTTAAGGCGGTCCTATG
          ATGGTCATCTGTGTTCCCTCACGTACCACCCGCAATATGCGCTGGTGGGGTGGCCATACG
          ATGGCAATTACTACGCCTTTGAAGAGCACTTGTACCATATCACGGTTGACTACCAACCTT
          AAAACGACTCTTAGGTCCTTTCGAACCACCGGTACACTACCCCGCCTGGGCCGGTATACG
          TCCCTCTGGCGTTATCATTCGTGGACGATGAGGTCCGTGTTGTAGGCGAATGGCTGTCTG
          CTAGCCGGCTTAAGATTTGTTTGAACGTCACACATATAGTAACTGTTTGACGGACGATAG

          CGAACAACTTTAGCTATCCTGAGTCCGCGGGGCCTGCCTGGATTTCACGTATTCGCTTCA
          CGAACAGCTTTAGCTATTCTGAGTCCGCGGGGAATGCCTGGCCTTCACGTATTCGTTCCA
          CGAACAACTTTAGATCTTATGAGTACGCGGGGAGTGCCTGGACCTCACGTATTCGTTTCA
          CGGATACCTCAAGCCCCTATTAACCCGTGTATATTACCTGAGTTTTTTGCCTTGGTCCGG
          GGGTCATATCTAGATTCTGGAAACTATATCGGTGAGCCTCGTTCTCTCTCCTTTGTACTC
          CAAAAGCCACCTGTACCGAGCAGTCTATCCAGTATACCTTATGCTACGGTTCTTGCCCCT
          ATAGAATCATTCCGTCAAGAACCGTCGCGCGTCAAATTGAAGTAACGAGTTATCCCTTAT
          CAGACCCCTCGTAAAGAAATATGCGTGGTTGGCGTATATCTTTGCCCTTTATTTTTTTTT

          TAGGTTTCCCGCACCCACACTGTTTTAATTCTGCGTGTGCCATGCCCCCCCGCCACTTGA
          TAGGTTTCCCGCACCCATACTGAATTAAGTCTGCGCGTGCCATGCCTCCCCGCTACTTGA
          TTGGTTTTTAGCACCCACACTGCTCTAAGTCTACGTGCGCCATGCCCTCCCGCTACTTGA
          CTAAAATTCCGCTCCCACGTTGTCGGAGAGTCTGGTAAGCTGCGGCCGCACTCAACACGT
          CGGATTTTCTAATCCAGGAATGGGTTAATAAACGAGAAGCCGCGTCGCCAGGGGTTCTCC
          CATGAGTCACGCTTACAACTTATTTCGCGTTGTGGAGGACGGTAGTTACGGGCTACTCGC
          ACGGTCTAACCTTGCAAACCCAGGTCTAATAGAGACGGGTCCCACACAGATACAATTGGA
          TTGGCTAGTCATGGTCCAACTTGAGATTGTCAGAGGTAACTGCGCCAACTCACCCCCAAA

          TTCTCGCTACCTTATCAATGGTTTGTGCATGGCCCGTGCCATATCGCACCGTTCGGCCCA
          TTCACGCTATTTAAACAATGTTTCGTGCATGGTGCGTGCTATATCGCACCGTTCAGCCCA
          TTCTCGATTTTTTAACCCTGGTCCGTACACGGCCTGTGTAGTATCGCACCGTACGGTGCG
          TCCTTGCTGTTATATTACGGTAATCTGATCGGGACATGCTGCGTCGAGCCGCATGGTCTA
          CTATTGATATTTTGTCAGCGGACTGTGCATTTAAGGTGGTGTGCAGAACCATATGACACA
          TTACTGCTTTCATAGTGCTGAAATACTCCTGGCATACGTCGGATTGTACTACCCGGTTAA
          CTACCGAGCTTCCCCAGCTAATCCCTATGTAAAAATCGCCACGGAAAACAACCGGGCCTG
          TCTGGAGGGGTATATTATCGGAGTGCTTGGAGCTTATTTTGTCATTCTGGACCAAACCCG

          GCCCACCAGCTGGAGAACAAGATGTATTATTCCGCTGACCAATCACCAACTACCTGGGGG
          GCCCATTATCTGGAGAACGAGATGTATTATTTCGCTGACCAATCACCAATTACCCGGGGT
          ACCCATTAGTTGGAGAACAAAATATATTATTCCGCTAACCAATCACCAACCACATGGGGT
          GGCCGCCAGCCAGGAATTATGATAAGCGGTTTCTCTCAACCATCGACAATGATTTTGCAT
          GACTTCCAGTAAAAGCCTAATTTGTACGGCGCCGGTTCTTTTTTCCCACCGTTACGTGTG
          GATGGCCACTTGACACGAATGTTGCGCTGCTCAGCTCACCATGTCCCAAAGATATGGGAT
          CAGAAACCGAAGGTGATCGTCGCGGACAGTGTCGATCGGTCTTCGCCGACGCTGTAATTG
          AATAGATAGCGAGAGAACATACCGGGAATTCACAAACGGCGCCCGTAAAAGGCAGAAGGC

          CCTACCGTACTCATAAAGGAATGTATCGTCATCGTAAGGCGTATTTGAGAAGTGGCTTTT
          CCCACCGTACTTATAAAGAAATGTATCGTCATCGTAAGGTGTATTTGAGAAGTGACTTTC
          CCCACTGCACTTATAAATAACTGTATCGTCATCATGGGGGATTTTTGGGAAGTCGATTCT
          CCTCCCGCCAGCATTAGGCGTTTTGTTACTGCCTCTGGGTGAGTCCAAAATTCGGGCACT
          ATCCCCTTCCATACACGAATCCCTGTAACCGTACCAGACTGAGTACCCAACTCGGAGACC
          CTAACCTCTCGGATTCTTAGCTTAGCATTCATATTAGAATGTGTCTGGGATCCGGGAAAT
          GGCATTGATTGCTTGATTGAATTGATGTGGAAACACAGGTGCGGACGGGTGGTCTGGACT
          AGTACGGCTACCAGACAATGCATTAGGTTTACGTCATCATGCAGGGAGAGATCTGGAGAA

          GTGTGTGATCTGTAGTCGACTGACGATTTCGGATTGTTTTAGCAGGAGAACCATTTAAAC
          GAGTGTGATCTATAGTCGACTGACGACTTCGGATTGTTTCAGCAGGATCCCCTTGTAAAC
          GAGTGCGATCTATGGCTGACTGCCGCTCTTGGATTGTTCTAGCAGAGAACCCTTGCAAAC
          ACGCACGATCTAAGGCTAATCGGTGGTCCCGAATTGGCTTAGGCAAAGACAGGGTAAAAC
          TTGTGCAGTCCACGGTCAAGTGGTGACTGCAAACTGGCCTAGCAAAAGAGGTGAATTAGG
          AGGCACGGCCTAAGTTTGCTTGGAGATCTCGAATTGTCCTAGGGTAGGGACTGGAGCATC
          TAGTTGGATCTAGAGGGGATCGAAAGCCCTGCTGAACTGGATCCAGGATACATAATTTTA
          CGGGTAGGACAACCGAGGACCGTCGTTTCGACAATGTTTGTGCTGAGGGTTCCTAACGAT

          GAATCAATCTCTGGCCGTCTTCCCGTACACTAAATGATTAATTCCTCAGAACTAAATCCC
          GAATCAATCCCCGCCCATCTTCCTGCCAACTAGGTCATTAATCCTTCAGAAGTAAACCCC
          GAATCAATCCCTAGCCATCTTCAGGCCAGCTATGTCATCAATCGCTCAGAACACACTCCC
          GTCCTCAGCGTTTACCTATCTGCGTTTGTCCCAGCTAAGACACAAGAGAGACTCATTGTC
          TGATTTGATGATAACCTATTACAGGCCGTTCGGATGAACAATCAAACAACAATACATGTC
          TGGCGTGATGTTAGTCTATCTATAATGGATCGGATTCGCAGCCCGACAGGCCCAGTCTCA
          TATTCTGCTACGGGCTGCTCCGATGCCGCCTCCACGAGCAAAGGAATAAATCCTACTGGA
          GGCCAGACTTACAAATCGATCGCATATCTTAAACAGGTCAGTCTAACGCAACTACGGAAG

          ATTCCATAACTATCGGAGCGGCACTCGCGTTTATTTCCCTAGTCATGAGGACGTATGTCC
          ATTCTACCGGTATCAGAGCGGCACTCGCGCTTGTTTCCCGAATCATGACAACGTATGTCC
          ATTCCATAGGTATCCGAGTGGCACTCGCGCTCGACTTTCGGGTAATGCCAACGTGTGTCC
          ATCTTATAGGCGTTCGACCAATGGACGGTGGAGTTGTCAGCGATACGGACACGAAAATCG
          ATACCAGCGAGGGTCTACAAGAAGTTAGAGAGGATTCTCGTAACGTGACCTTGCGTAAAC
          GTACAGCTGATGCTCAAGCAGTAAATCGGGTAGATGCTAGAGACGCGGCGGTGCCTGTTT
          ATCTCCAATGTATCGGTACTACACCTGGGATATTTCCTTGCCTGGCGCCCATGTAGGTTG
          ATCCTATTCGCACCGGAGTGGTACCCGAGACCTGCCTTCCGCACAGTGCTTTTTTGATTT

          GCTTTGGGCAGTGGATCTGCCCTTCTGGAAACGTAAAATTAGGAACACATGATAGATGTT
          GTCTGGGGCAGTGGATCTGCCTTTCTGGAACCGTAGAATTAGGAACACATGATAAATGTC
          GCCTCGGGCAGTGGAGTAGCCCTTCCGGAACCATAGAATTAGGAATATACGATAGAAGCT
          AATCCGGAGTACATACCAGTTTTATTAAAAGCATCGGATCAGGCCTCTACGTAAAGCGGT
          GGCCGGGACCCCTCCTTGGCACGTCCAAATCTATAGAATCTGGTCCTTATGTGCGATGTC
          GCCTTGATTTGGAAACAAGACTCTCTGAGACTGTAAAATTAGGTCTCCCTGTCTAATGTA
          ATCCCGGGGTGCAGACTGGGATATTTGGGATTGACAAAGTAGGCTGGTACGTTGAGAGTT
          GTCATTGGTCACAGATGAGTACTCCTTATAATAGTAAATTTTGATGACATTGTGTGAGCC

          TAACTTACGCAGCCGTTCCTACCTGCATCCAAGACCCTGAAGGGGGCGCAGTAAAGTCCC
          TAACTTACGCGACCGTTCCGACCTTTATCCATGATCTTGAAGGGGGCGTAGTAAAGTCCC
          AGACTTACGCGCCCGTTCCCACCTGCATCCACGACATTGAAGGGGGTGCAGTATGGCCCC
          GAATCTACGCATTGGCGCCAATTCGTTCGAAGGTCTCCTATCAGTGTACGAAACAATATC
          CGACATGAGTGTCAATGTCCCCGAAATACATAGGCTATGGAAGGTGGCCAGTATTGACTA
          TAATCTAAGTGTTAAGACCTTTGAGCTACAACGAATATGCAAGGAGCTTTCCATTGATAT
          CGTGCGGTAAGGCACAGTCTCTTTATCGGCATACACTCGTGTGAACGTTTCGACAGCCCA
          CGTCTTTAGGACCGGCATGTAATACTATATACGATTACCGATGAATACCTGAATAAACGG

          GACCACACTAGGCATAAGAGTCCAGTAGGGTAACTGCGAGCGCTATCAGAGGAAGATATT
          GGTAACACTAGGCATAAGAATCCAATAGGGTAACTGCGAGCGCTATCGGAGGAAGATATT
          GGCAATACATGAGATAAAAGTCTTACAGGGTAACTGCGAGCGCTATCAGAAGAAGACACT
          AGCTATGACCGGGGCGGAGGTCAAAGAGCTCAACTGTGAGCATCAACCCACATAAACATT
          GCTATTAGCAGAGATAAAAGTCTCGAAGAGTGGCCTCGGTCATAAAGTTATGCACACAAC
          GGAGCCTAACGGGGTCACGTCTTAGCGAGGTGGCCCCGCACGTCAGCTAGCGTAACCATT
          GAAGACAACGAGTTTGGCGCTAGACGGAGTCGGGCCCGAGAGGCAGTCTTGATGGACCCA
          GACGAAAACCGGGCATCACGTCGCGGACACGTGCTGTCAAGATAGTCTTAGGCTTACTCC

          TCGAACTTAGGATAGTGCACGGACCAACATTATAACATAGGCTGGAGCAGAGCTTCAGCA
          TTGGAGGTAGGATAGTGCACGGACCAACATTATAACATAGGCTGGAGCAAATTTTTAGCA
          TTGGAGGTAGGATAGTGCACGGACCAACATTATAACATAGGCTGGAGCAAAGATATAGCA
          CCGAAGGTCGCTTGTTTAGTCGCCCATTTACCCAATATGGCCCGATGTACCGTACTAGAA
          CTGAGGGCGGCAGCTAGCGTGGTCTCGTACCTCAACCTACACTGCCAGCTCAGACTAAGT
          CTGGAAGTTGTATAATACGCGTAGCAAAACCACATCTTGGATTGCGACAAAACAGTGCAT
          CGAGTGACGGATTGTGACTTAAGTTTGAATTGCAATCGAGGTAACGGAACCCCAGTGACG
          TTGCTTGTGGTATAATTATGGCGATCCCGTCGATATTAGGATTAGGTTTTAATGGGAAAT

          GCATCGCTTTGTCGTTTCAGAAAAGTCCAAGGCTTGGGGAGCGATAAAGACTTGCAAAGA
          GCGTCGCTTTAGCGCTTCAGAAAGGTCCAAGGCTTGAGAAGCGGTAAAGGCCTACAAAGA
          GCATCACCTTGACGTTAACGAAAGGTTCAAGGCTCGGAAAGCGATAAAGATCTACAAAAA
          GTAGTGATTAAATAAGTTAAGATGCAGACGGCGTTAGGCTGCGGTAGAGTGTGGAGATAA
          GAAGAGGTTACAAACTCTAGGATGTACGCATAGGTGGATAGAGATACACGGTGATAAGAA
          CTACCCGTTAATTGGCAAACGATGTATCTAAGGGTAGGCGACGACAGCTGGCCATAGAAA
          TAGGAACCCGTAGCACAAGGCCCGTATTCGATATTTATCGACAGTATGACACCTGGAATA
          TAGGTGCAAGCGTGGCCGCGGCAGCGTTTGGCGCTCATCGGCGCCGCTGCTCGACATGCG

          TCATTGACAAGGACATGTACTCTCCTACCTACTGCCCATTTTGTAAACCCTGTTACCGGG
          TCATTGACAAAGACATGTACTCTCCTACCTATCGCTAATTTTGTAAACCCTGCTATCGGG
          TCATTGGAAAGGACACGTACTTTCCTACCTACCGCTCATTTTCCAAATCCCGCTATCGGG
          CTGCCAGCAAGGCCGTGTACCTCCCTAGTCAATGCCAAGCTAACGTACCTTGATACCTTG
          CCATAGGTAAGGGCGAGGAGCTCGTTACATAATGGCAGGCCCACAAACGCAACCACCCCG
          TCAATAGTTTGGGTAGTCACCTCGTTACTTCATCCCCAGATTCCAAGTATAGGGGACCCG
          TCATTAGTACGAACGTATACAATGGACTGATATCGATCACAGGCAGGTACAACCTCTATA
          CGACTTGTCAAAGAGCACACAACGCTGTTTTTTAAATCGCTTACGCGTTCTACGGCAGCT

          AGGCGTACAGAGCAGATGGGCCTGAAAACAGATCGTATGC
          AGGCGTGCAGAGCCAATGGGATTAAAAACAGATCATATGC
          AGGCGTACAGAGATGATGTAACTGAAAATAGGTTGTACGC
          ACGAAAGCCGCGGCAATATTTCCGCCCCTGGATCGCCTAC
          AAGCCACGGGAGTCGGTACACCAGAGGTCAGATGACTAAC
          TGGGACAGAGAGCGGATGTGACAGAGGCCGGGCTATGTGG
          CAGGAGGCGGCCTTAGTGTAAACGAGACCGGACTGAGCGG
          GGAGAGCGCAGGAACATATAGCCAATGCAAAGACCGGTAT

