 8 1000
t1        ATAAGCCAGCCACGAGGATAGCTCCACGCTGCCCTAAGAACCGGCAGACTTCGTTAAAGG
t2        ATAAGCCAGCCACGAGGATAGCTCCACGCTGCCCTAAGAACCGGCAGACTTCGTTAAAGG
t3        ATAAGCAAGCCACGAGGATAGCACCACACTGTCCTAAGAGCCTGCAGGTTCCGCTAAAAG
t4        ATGAGCCTCCCGTAAGGACAAACCCACACCTCCCTATAATGCGGTAGATTTCGTCAAAGG
t5        TAAAAATATTCGTACGGACAATTCTATAGTCTATCAAACCGTGTTAGATTCGGGTAGTAC
t6        CTGGGCCAGGTCTAGAGTGATCCCCGCAGAATCCCAGCCACTATCAACTTTCACTGAGAA
t7        CGGGCTTACCAATACACTAGCTTCTCACGCCCTCTTACGGTCGAGGGATAATGCAGAGGG
t8        GCGAATACTCGTTCCTAGCATGTAATAGGCGACCTTATCGGCGCAAGACCCAGACAAGCT

          GTGCCCCTGCTTGCAATTGGGACGTTGTTTACTCGACTTCTGTGACGTCTAAATGAGGAG
          GTGCCCCTGCTTGCAATTGGGACGTTGTTTACTCGACTTCTGTGACGTCTAAATGAGGAG
          GTGCCCCTAGATGCAGTTGGGACTATGTCTACTCGAGTTCTGTGAGGTCTTAATTAAAGC
          GTGGACCCACACATAGCCGGGACGATGTTACGTCGACTTCTGTGGGGCGTAGACTAGAGG
          ATGCGCTTGTTCTTCAGGAGGGCTTGGCCTGGTAGAGTCATTTACTGTTCACAGCGAAGA
          ATGCACCTGCGCATAGCTGGAAGTATGGTGGTTCAAGGCCTCTCCAACCTACCCCATAAG
          CAGCGACCATCCGTAGCTAAAAACTAGGTATCTAGGACTACTTGCGCTCCCAAATAGGAA
          CTGTGTCAAAAGATAGCCGGGGAGAATCTCCAGTCCATACACTTATGCCTTTTGGGAAAT

          GTACTTCACTATGGTGGCGCTCTTAATCATCAATGAGCGAGGCAGTTAATGGTATTCAAG
          GTACTTCACTATGATGGCGTTCTTAATCATCAATGAGCGAGGCAGTTAATGGTATTCAAG
          CCTCTTCACTGTGACGGCGTACCAAATCTTCAATGAGCGATTCAAGTAACGGTCTTCAAA
          GACCTACAATGAGGCAGCGAACCAAATTATCGATGCGCGAGGTAAGAAATGGTAGCTAAA
          AGCTTCCCGTGAAGGGGTGATCCAAGCCCCAGACTAGGCAAGCAGGCAACAACGATCACA
          AGCTGAGAGTACATCTCTACTTCTAGCCACTGCGTGATTCTACGTGAGAAGGCCCCCGGA
          AGCTTTGAGCGTGACATTGTAGCAGTTAATTGGCAAGCGTAGGGGGCCAAAGAGCAAGAC
          GCTTTACCATAGTGCGCCTCTCTAAACTATAAGTCGGAGACGCACGCCACGTGCCCAGAT

          GTCGAGCCTCAAGAAGACACACCCCCTATCACTTAACTGTAAGGTGCAAATGGCTCTGGC
          GTCGAGCCTCAAGAAGACACACCCCCTATCACTTTACCGTAAGGTGCAACTGGCTTTGGC
          ACCGAAATTCAAGAAAACAAACCCCCCATCAGTTTACCGTAGTCTGCAAGTGGCTTTGGC
          GTCGGAGCTCAAGAAAAATGACCCATCCTTAGATTACTGTAACTTTCGAGTGGCTCCGGT
          ACTTAAATCACAAATGACCAATCCCTCGTTGACTTATTGGGACACCCACTCTATTCTGGG
          ATTCACGGCAGGGACGATTAGCACTTAAACATGTACATGAAGAGTTGACCAGCCCTCGCA
          ACCTGAATCGATGACCAATAGCCCTTTCATCTCACAATGTTCTCTAGATTGAGCATCTGG
          ATCGGGTCCAAAGATGACCAGTCTTGTTCCCGCGCGTTTCTGGTACACACCTACGACAAG

          GCGGCCCCTCCTGATGTGGACCCCTATGGTTTCTCCTAATGAAATAAGGCAGGTACTGGT
          GCGCCCCCTCCTGATGTGGACCCCTATGGTTTCTCCTAATGAAATCAGGCAGGTACTGGT
          GCGACCCCTCCCGGTGTGGGCCCCAATAGTACCTCCCCATGAAATTAGGTGAGTACTGGC
          GCGGCTCCTCCCACTATGGATACAAATGGGCCCTCGTCATAAAAATTGCTAGGTATTAGC
          GGTGTCTTCCGTTCCCTGAGTACCACCGTGTGCTACCCATGAAACTGGGCAGAACTTTGC
          GCAGCGTCTCCCTTCCGAAAGATTAATGCGCATCACAGACGCAATAAGGTGGAATTCGAA
          GTGATTGTGCGGAAGCTACGACTTAAAGTACAGTTGTTGTCGTTGGACCCGAACTTAGCT
          GAGGTAAACTGGCTCTGGTAATTTATCATGCTGTTGTTGCGAGACTGTGCGAAAGCCGAC

          CATGTTGGTATATCAGCGAACTAAGAGACACTTTGCCAATATATAAGATGCTGCTTTATT
          CATGTTCGTATATCAGCGAACTCAGAGACACTTTGCCAATATATAAGATGCCGCTTTATT
          CACCTTCAGTTATCAGCGCGTTCAGCGGCACTATGCCAATACAGACGGTGCGGTTTTATT
          TGTGCTAGTATATCAGAGTGTCCGGGACTAATTACCTAACACAATAGGTGAAGTATTATT
          TCTAGTCGCTTACCAGCATAAGCTAGAGCACTCTAATACCACAGTCGGGGGGGACCAGCT
          CCCGTGTTTTTGTAACTCCTTCTGATGTCTTTTCGTTGCTAGGAAAGAAACGCCGCAATC
          ATAATAAGGCTTTTGGTGTATTGCCAATAAGTTTGGTCTCATACTTGGCCGGGAAAGCCG
          CGTTTGCACTCGATAATGCCTCCTAGGGCCGATAGTCAATTTTGCGAAGGACGCAGGATA

          CCTAAGAGGCATTCTCGATTATTACTGACTCCATACTAGAGCAGAAATGTTTGCTGGGAT
          CCTAAAAGGCATTCTCGATTATTACTGACACCATACTAGAGCAGAAATGTTTGTTGGGAT
          GCTTTGAGGCCTTCTCGACCACAACTGACTCTATAATAGTGTAGAAATATTTATGGTGAT
          CCTATGACGCCATCCTGCTTACAACTGAATCTACAGTAAGGCGAACGTCTTTGTGGCACT
          CGACTGCAGCTCTCCTGTGTACAACCGGATTACAGATGTCGCGAGCAGCCCTGCGACCAC
          TCTCAACGGCCCCCGTAGTAACAATTGGTACACCAGGGGTGTTGGTAGCCCTCCAGGAAC
          CCTGCGTGCCTCATTTCACCGGAGCCGCTTACCGATAAGAACAAATAAACTCGCGGCGGA
          TATTTCCGAGCTTAATGTGCACAGTAGGGTTTCGATAAGTGAGAGGGTGCGTGCAGCGGG

          TTGCGGGGTGCGAATTAGCGAGAGTATAGGCTATGTTCTGAGGACTGCATGCTGTCAACT
          TTGCGGGGTGCGAATTAGCGAGAATACAGGCTACGTTCTGTGGACTGCATGCTGTCAACT
          TTACGGGGTGCGAATTAGCGCAAACACCGGCTACGTTTTAAAGACTGCATGCTGTCATCT
          CTGCGGGACTCAAATTAGCGCGAACACCAGCCAGGGTCTGAGGACTGTATGCTGTCAGTT
          TCGCAGGGAACGAGGTGGGGCCCGGTACTGCAGTGGGTCGGGGGTTTCATATTTTCGCTC
          GAGAGCCGCGCAGGTAACCGCGAACACATCCTTTCCTGAATAAAGCTCCCGATTTCACTC
          ATTCGTATGATGTACTCGCGCACGTTGGAGTGGGTACACGGGGGATATACACTAAACTTA
          TAGCAGGGGAGGGGCGCGCGCGCGGTCAAGCTGCAGCTTGGCGATACCCCGCCGACAACA

          AAACTGAACATCGTCCCACTTGCAATAGCTAACGATGTACTAGCATCCTAGGCAGACCAA
          AAACTGAACACCGTCCCACTTGCAATAGCTAACGATGTATTAGCATTCTAGGCAGACCAA
          TAACGGATAACCGAACCACTTGAAGTAACTAACGACGTATTAGCATCCAAGACAGACTCA
          TAGCAGACGACCGTACCATTTGCCATTCCTGATAGCGAATTCGAGTCCAAGACAGCTAAT
          AAATAACGAACGCCTCGTCAAACTTAAAATGACAGCGTACTAGTGTGCATAGTAGGCGAC
          TCACTAGAAACGCCACTATCCGCCTACGACTTCAATACTACGGACTTTGGCCTACCTGAT
          TCACAAGAGCAGCTATTTTACCCTTGTACATTACGACTGTCCCATCCTGTGATGGGAGGT
          GGGATGTCGCGATTTTCTCAACATGCTTATGTCATGCCCCTCATCATCGCCGAAAGCAGT

          CGGGATGATGCCTCGGGTGGCTCCAGCCATATTCGTCCGTCGGGCGCTATGCTGTACTTC
          CGGGATGATGCCTCGGGTGGATCCAGCTACATTCGTCCGTAGGGCGCTATGCTGTACTTC
          TGGCCTGCTACACTAGGTGGATCCAGCTATATCGGTCCGTGGGGCGCTATGCTGTACATC
          TGACTCGACACACCCAGCGGATCTAGCCAGACCTGTCCGTGAGGCGACAGGTGGTATCTT
          GGCTTCTTGCTACTTGACGGAAACAGCCATGGTTATTAGCATGATGGCACAGAACAAGTC
          CTGTATGGGCAACACGGGTGACATAGCAACGGACGCCGGTATGTCACTACAGGATAGTAC
          TCGCAAGAACTCCTCGGAGGCTTCGGTCGGCACCCCATGTCTACTAAGTCCCGATTCTTC
          TAGCCAGGCACCTACCACGGATTTGACAGATATCTTCGAGGCAACGGTCTAGGAGACGTT

          GTGTTATTTCTCTCTCGGTGTCCCAGTAAAGTTTGGTTTAAAGTATGGATCGGTCGTGTC
          GTGTTATTTCTCCCTCGGTGTCCCTGTAAAGCTTGGTTTAAAGTATGGATCGGTCGGGTC
          GTACTATTTCCCCTTGGGTGTTCCAATAAAGTTCGGCTCAAAATATGGCCCGATTGCGTC
          GAGCAACTTCCCCCCCGGTGTTCCAGTAACGTTAGGTTTAATAATTGGGTCGACTGCATC
          ACACCTCTTGCAACACGATGCACGGACAGTGTTTGGATCATCGCTTAACCTGGCTAGGTT
          GTCCTGTCCATTGCCCAGCGCTTAAGCAAGCGCTGGATAACTGAGGGCACCAATTAGATA
          TTCTCGCTTTCAGTTACTCGATTGAGTAGACTTGGCATGAGGTTCGCAATCTATTAGAGT
          ACTTAATTGGATCCGCTTAGGGCCCGACAGCCGTCTACTGCATGGAGGTCCGAGAAAAAG

          TCCAACGGTTATGGGCTTCTAGAGGGGTACGTTATACTGTGGTAAAGGTAGATATAACGA
          TCCAACGGTTATGGATTTCTAGAGGGGAACGTTATACTGTGGTAAAGGTAGATATAACGA
          TCTAAAGGTTAGCAATTTTTAGAGGGGTACGCTATAAAGTGGTAAGGATAGAAATGACGA
          TCTGACAGTTAGGAGATCTTAGATGACTTTGTTATACTCTGTTAAAGGCAAAGGTAACGT
          CCCGAAAGCTCGCGGATCCCCAGTGGTTATAGTATAGAGTGCTTTATGCCAGAATCTAGA
          TTCGTCGGCTAGTTGTTTTCCAACGAACTCTACAAAGAATCCGCGACGTCGGAAAGAGAG
          CTTGGCGAATACATATTACCCAACAGCTGTTATACTTTTCGATATAGGTAGGCACTTAAT
          CGAGTGAATCGAAGTTGCCCTTGAGTTCATCACATCCATATTTGTGTACTGAGCCTTAGG

          GCGCGTTTGGGCCAGTAAATAACACATGCTAGTGCAGATATGGACGTACGGATAGAAATT
          GCGCGTTTGGGCCAGTAACTAACACATGCTAGTGCAGATATGGACGTACGGATAGAAATT
          AAGTGATTGGGCCAGCAACTAACACATGCCAGTTCAGATACGGACATGCGGATAGAGTTT
          GAACGCGTGGGTCAGCAACTCACACACACGAATACAGATATGGACGTGCGCATAGAATTA
          TGGCAGGTGCGGGACTAGTCATTCTGATCTAGACCTCGCAAGGAAATATGAAATGGACTC
          GACTGCTCAGTGTAGCGATTCTACGAGAAAGCATATGATTACAGTTCAGAAAGATCTCCC
          TTGAGGATGGGGTAGAAGAGCACTCTAGCTCGTCGGCTTGTTCTATGAGAGTAATAGCTT
          CGAGACGTAATGAGGCAATTCGCCCACCGTGAGCTCGCCAACCATACGGAGAACACTCCT

          TCCTCAGTGGATACATGTGGGTCAGAGGCTACCGGTCGAGCTTTCCCGCAATACTTAGGT
          TCCTCAGTGGATACATGTGGGTCAGAGGCTACCGGTCGAGCTTTCCCGCAATACTTAGGT
          TTCTCAGTGGACATTTCTGGGTCGGAGGCTATCGGTCGCACTTTGCTGCTAAACTGAGAG
          TCTCGGGTGGACACTTATACATCAAGGACTATATGTCGACAACTAACGCCGTACTGAGAG
          CTCTGTGCAAACTTATATACATGGAGGACGTTAGTCAAATATTGATCGCTCTGCAGGTGA
          CTATATGTAGAAATCTACTCGTCTATCATTATAGGAACGTGACGCCAACGATACCGCTGG
          CCCTGTAGACGCATACCTGTGAGTGGTAGTCTGACTAAAGGCAGCGTGGCCCACCTCATA
          TCCGAAGGGTGCGCCCACACACCACGAGTCAACCGGGGCTGTCATGCAGACGATTGGGAT

          TACTAAAGTTCACGGAAACGATCAGGAGGTAGAAGGAACCGGGGTTTGGTTAGCAATCCC
          TACTAAAGTTCACGGAAACGATCAGGAGGTAGAAGGAACCGGGGTTTGGCTAGCAATCCC
          TACTATAGTCCCCGGAACCGCTCAGGTGGTGTTTGAGACTGGGGTTTGGCCAGTAATCTT
          CACTATAGTCCCCCGAAACGGAAAAGCGGTGTGAGGGACTAGGGGTTGGCTGCCAACCAC
          ACTCCCGACTCTAGGAGCTGTAGCGGCAGGGTCCGCCACCTTGGGGTGGCCAATACTACC
          TGCCGTGCTCGGTCCGTGCGACCAATCGTAAATTGCTGCTACAGGTCGGCAGCTGACGAC
          CAAAGCCCGCGACAGTGGATGTGAGCATGGGCATGCAATAGGGCGCCACTCTCGGACGTC
          TGCACCCTAATGTTGGAGAAGGACCCTCAGATTGGCGACCTCGCTATGGATTCAGCCGCT

          TCGTCCTATGGCCACCATCTCCGCCCTTCTGTCAAGTACTAACTATGGCCGAGTTGTAAG
          TCGTCCTATAGCCACCATCTCCGCACTTCTGTCAAGTACTAACTATAGCCGAGTTGTAAA
          TCCCCCCATAGCGGTTATCCCCACGCTCCTGTAAAATACTAACAATGGCCGAGCTGTGCA
          TCGTCTCGTAGCCGCTATACCTGCACTCCCGTCAGGTATTTACAACGGCTGAGCGCTAAA
          TTACCCCATCGCAGCTATCTCCCTACCCCTTTAAGACATTACGTGTGGGTGTGTGTAGGG
          TTGCTCTACAGTTGCCTGACTTTTACTTCGGCGAAGTACGACTAAATGTACTGGGTCAGC
          GCCTGGCATACCAAGTCCTTTCCGGTAACGAAGGTTGACGATTTTAGATTGAGCGACAGG
          TGTTCTGGGAGTAGAAGACTCCACACGTGAGCTGTTCGCCGCTTGTGTTTATCAACGATC

          TTCAAACCTGGATAGCAATAGGCGGCGTAACGTGTAGAGC
          TTCACACCTGGATAGCAATAGGCGGCGTAACGTGTAGAGC
          TTCACATCTGGATAGCAATAGGTGGCGTAATGTGTGGAAC
          TTCAAATCTGGATCGCTATAGCTATCGTATAGTATGGGAC
          CACCGAGCTCGAGGTTCTAAAGTATTATTAAATCCGTACG
          TCCCTCCCTTCACCCCTGCAGACAGTGTGAAGTTCTGGTA
          ACAACATTGAAGAACGACAATGTAGCACTGTTTGCCGAAG
          TAAGGACATCGGCGGTATTTAATCATGCATCGGGCGTAGT

