 8 1000
t1        AGCATATATAATAGGGGAAAGAGGGTATCCAGTTAATTTTGCCTTAGGCCTTGCAGCGAA
t2        AACGTCCATGACGGGGACTAGAGTATCTTCAACCAATTCTACATGAGACCCTGTAGCGGT
t3        TGCGTATATTATGAGGATGACGGGGTGACTAGCTTGCTCCGCACTATGAGCCGGGGCTAG
t4        TGCGTATATTATGAGGCCGATAGGGTGATCAGCTTATTCTCCACAGTGCGTCGGGGCTAG
t5        TATCTAGGCATCTAGGTCGTTGAAAGGACAGAAAAATCATGATTCATTCGCTGAGTGGGT
t6        TCCAATGGTATCGGGATATTGTGGACGACGGGAAGACTATCGCTCACTCATCGCATTGAC
t7        AGGCGCATCCTTTGGATTGCCTGCTGGACAAGAATCCCGGGATTGCTATTCTGAGCTGGC
t8        AGTTGTACCCCCTGCCTCGTTAGCGGAATAAGAAGCTCAGGATTCCGATCCTAGGTCGGC

          AATTTGATGGCGGATCACATGATCAAGACTAGTACAAGTGGTGCGTACTAGCGCGCGGTC
          AAGTTGACGACGGATCATCTTCCCACGCAGAGTATGATTAGTGCGGATTGGTGCGCCTCT
          ACGTTGGGGACAAATTCTCCGCCTATGCAGTGCCCGAGCGGTGCGGAACAGGCCCCCATA
          ACGTCGGCGACAAACTTTTCGGTTATGTAGCGTTTGAGCAGCGCGAACCAAACCACCGCA
          AAGTAGAATCAGCCGTGGCTCGTTCAAAAGTAGATGGCGGGGCCGTTTTAGCACACTGTG
          CAGCGAAATTAGCTGTAGCCCGTTTACAGGAAGATGACAGTGTAGAATTAACACACCGCG
          TAGCTCCGATCAAAGGAGATTGTTCGAGTGGGGATAAAAGTTGGAGATTAACTTACTGAG
          TGGTTCTAATATAGGGCGATTGGTAGTCAAATGATAGAAGTTGCAAATGGACTTGTTGTG

          GCAAAAAAAGTCGGGTAAATACGTTCATTGTCCAAGTATACGCGTTCTTCGGTGCTAATA
          GGAACAGTAGTCGCGTAAACCTGTCCACTGTGCGAGTTACTCCGTACATCAGCGTTAGCG
          GGCACAAAAGTCGCGCCAATACGTCACTCGTGCACATGGGCTCAGTGATAAATATTATTA
          AGCCCACAAGTGGCACCGATACGTCTTTCGTGTAAATGGGTTTGGTCATAAACACCATTA
          TTACTTTAGACCGGAAGGACAAGTACCCTAGTCCGGCTACTCCTTTTGTCGGTACGGCCG
          TGAACCACGGCTGCGATACCCCGTACCCGAGCCAGGCTACACCATCTGTTAGACTAATCG
          CCGAACCAGCCTGCAAAGAATAGCACCTAGGGGAGGCCGTTCAGACAATAAAAGCGGTAC
          TCGATTCAGATCGCACGAACTTACACTCGGGGTAGGCCCCCAAGGCAACGGAAACGCCCC

          GATTTCAGCAAATTCCGGGGCTCTCATAAATAACGTGATCGTCATGAGGTGTCTGGGGTC
          GACTCTCGTAGATCCCGGGGTTACAATTGATTACGGGAACATGATGAGCCATTTGCCGGC
          GATCGACGTGAACCCATGTGCTTAAGCGCATATCTCGAACGTACTGAGCTTTTGGAGTGC
          GATCGAAGTGAACCCCGGTGACTCAGTGGATAATCCGGACGTGCCGAGTTGTCGGAGTGT
          GGACTCGGAGGCGCTACGATCGGTAATAGCTCACGAGAGTCTCGCCTACCCCCATAGTAC
          GGTCTGAGTGGTGAAACGTGAGTTAATAGATCCGGAGAGTCCTGTTCCCCATCACAGCGT
          CGCTGGACGCGTCTTATGGGCGCTAGAGGAAGCCGTAAGCCGCGTCCATCCCTGTGCTGC
          AGTCGCGCGAGCCTTACGAGTACTAGCGCAGACCGTTGACCCCCCCTATCGTCATGCTGC

          ATTTTATAGGAAGGGTACGTCCTTCCCATACCTGATACTAGTCACCGGCTCAAGCAGCGG
          GCTCTACAAATAGGGTTCGCCCTGCCTATACCTTATACGAATGACTAGCTCAAGGAACGA
          ACTATCAGTCTAGGGTAGGCATTCCTTGCATACGACACCACTCACTAGTTCGCGGAACGA
          ATCATAACACTAGGGCAGGTCCCCTTTAAACACGTCACTCCTGAATAGTTCGTGGAACGT
          AGAACACAAATAGAACCTGACCTAGTAATGAGGTATGCCATATGATAAGTCGTGGAACGC
          GGACCAAAGATAGAATCTGCTCCTACTACACTGTTTGCTATATACTAGCCCAAGGACCGG
          AAATGACAGGTGGATTACATCCATCCCTGACAGGGGGGAATATGCCCGTCCGCGGGTGGG
          AAACAACTGGTGGAGTGTATCCAACCCGCAAGGGGGGACGTGTACCTGTCCGTGGATGAA

          TCTAGGAGTTAGCATTCTCCCGTCTTACCCACACGAGATGACAACCTCCTAGAAATAAAC
          TATAGGAGATGGCGTTCCCGCGGTTTACCCATATGAGTTAACTACCTCTTGAAGATGAAA
          GCTAAAGTACAGTGGTTTGCTGTCCTATCCACATGAGAAAGATGCCTAGTGGAGATGACG
          TCTTGGAAACAGCAGTTTGACGTCTTCATCATACGAGACACTCCTTTTTTGGCAACGTCG
          CCTGATATCTGAAGCCCCCCCCCTGAACTTAGCCAAGACGACTACTCCCCGGAGACGTTA
          CTTGGAATTAGACACTTTCCTAATGGACGCAGCCACCACGATTATCCCCTACTTTCTATA
          GATGAACTCAGGTGCTTTTTCCGGAGTATACCGTACCGTGATTTCCTCCTAGGATGCACT
          AACGAACTTAAGTCTCATTCCCGGGGTTTGTCTTAATGCAAATCCTGTCTCGGTTTTGCT

          AGACTGTGCCACGGTCGTACCCACGAGAAACGATGGGGTCACGTTAGCAGTACCAACACG
          TGTCCGTGCTACGGACATACCTATGAGGAATGCCGGGGTGTGGGCAACAGCACGAACATG
          GGACTGTGTTCAGGCCGTTTGTACGAGAAAAGTTAGGACCCGGTCAACGATAGCAACATT
          GGGCTATGCCCAGAATGTTTATACGGGAAAAGCCAGTATCCGGACGGCGGTAGCGATACT
          GGAGTGCAATTCTAGTTTCAATCCTCGGCAGGTCTGGCTTCGGCTGCCGGAAATACTAAC
          GGACTACTACCCGAGTTTTTGTAATTGCCAGGCCTGGGTACGGTCGCTGGATCCATTTAA
          GGGCTGCATACGCAGTCGCAATGTAACACAGGTCCGGACTGGGTGAACCAAGGCATTTAC
          GGGTCACACCTTGAGTCCAGTTGATGGACAGGTCCAGAGTGGGCCGATGAAGAGAATTCC

          GATACACTGGTCTGAGACACTGACCCCCAGAAATTAAAGGAGCAAGAAAAACTCGGCCAC
          GAGATATTGCTCCGAGACGTTAACTCACCGAAATTCAAAGCAACAGAAAAACTCGGTTTT
          ACCAATCTCATCTAAGACGGCATTACTCCCGGACCAACTCCACATAGACGGCTTAGCCCC
          ACGTTTCTAGTCCAAAACGGCGATTCTCGAAGACCAATTCCCCAAGAACGGCCCAGCCAG
          GTGAATCCGACACAAAACGCTCACATTGCTGACTCAGCTCCGGTTTCGAAATTTCCTGTT
          GCGAACTGAGTTTACGGCGCTTATACGGTTGAATTAGCTAAAGTGGGTCATTTTCGGGAT
          GTAATTCATACTAAAGGTTATGACCCCGACGCTGCCGTTACGACTCTAAATAACGCCAAT
          ATGGTACGGGTATTGGGCGTTGATTTCAACCACACCGTTATGACCGCAAAATGCGCCGAA

          ACGCATCTGCCGCGTACCCTCCGGGAGTTAACCAGACTAGGTAATGCGCTTCCCAGGTAG
          ACTCACCAACTACTCAGATGGCGGAAGCTATCCAGGCTAAGTAAAAAGCCTTCCGGGTAG
          GCCCATAGACTGATTAGATAGATGGAGTCATTCTGGCCAGACAACAAGCCCTATAAATAG
          GACCATAGGCCGACTAGAAGGTGGGAGACAGTCCGGCTAAACGGCAAGCCTTACGAATAG
          GCCTTTCGAAGATGGAGGGTTCAAATCAGCCACAACTCCTATGATCCTTCCCTCGTAGGA
          ACCTTCCAGGAAAAGGCGAGCCGACACGATTATGAACTCCATAACTCGCCCCTTGCAGAA
          TCCCCCGGGAAGAAGTCGGACGAACACGGGAACGATTCCTGTAGCCCTTCGCTTGCGTAC
          TCTTCCTGTAAGAAGACGGATGGACCCAGTCATGCATTCTAGAGCTTGTCTCTTGCACCC

          GTCATGCACGACTGCAGGCGCCCATTCTATCGTCGCATAACCCGGGCTTCTGCGAAAGCC
          GCTACATGTGATTGAGAAAGCTCACTCCGTTGCCGCATAATTCAGGTCATTGTCGGAGCT
          GTTACGTGTGGTAAGGGACGCTCCTACGGTCGCTGCGCGAAATCGGACATCGCAAGAGCT
          GCTAGGTGAGATAAGGGACGCTCACACGGTCGCTGCGCAACATTAGACACCGTAAGAGTC
          GTCGCCCACGGTAGGAGACGGTTAAGAATTAGAGGAAAGTGAGAGTCATCAGATTGACCC
          ATGATGCATGCTAGGAGGCACCTGAAACCCGGGGGAAAGGCAATCCCACCAGTTCTAACT
          ACCCAGCACAATACGCTATGGTTAAGTACCGGGTGCAGGGTTGACCCTGGAGCATGATTC
          AACTCGCACGAACGATGATGATTAGGTCCCGGGTGCAGGGTCGATCCGAAAGCATGATTT

          GATTAAGACGCTATTCGACATTTTTATCATTCAATGACACCCAGTGCACTGTTGCTAGCA
          GAAGAAGGCGCTATAAGACATTACTGCTATTCAACGACAGCTAGTCTACCGTCGTTCTTA
          GTTTCAGACGTTACGGGGTATTTCTGCCATCCGTTGACGACTAGTAAACTGAGGATTTCG
          GCTTCAGACGTTACGAAACATCTCTGCGATTCGTTCACAACTAGTTAACTGAGGATTTCG
          TTCCGATAAAAACGTACTAATTCTACTACTCGTGTCGCTACGCGAACCCGAGGTATTTTC
          TCCCTATAACCAATGTATTGTCTTTATGTCTGAACTTTCCTGCGAATTTTTAGTGCCTCC
          ACTTCGCCCCGAGTTTCGTACCTTTTCAGGGGGGTTCTCTCGGGTACCTCTGGCTTACTC
          ATTTACCCCCAAGTTCCATACCTTTTTAGGCGAGTCCTTGTGAGTTCCTCTGGCTTGCAG

          CTCCGTACATACCGAACGAAGCTCCTGATCGCTAAATGACGGAAGAAGAGTACACATAGG
          CCTGGAGTATCCAGGATTGAGGCACTGCCAGGTCAGAGCCTGAAGATGAGCGTCCGCGGG
          CACAGGCTCCCCGATGCTAACTTGTTAACAACTTGTTGTGGGAAAACAAGCATACGCGGA
          CACAGGTTCTCCGACGCGAAACTGCAAATAACTTGTCGCGGGTGGACGAGCAGACGTGGG
          CGTGTTTTCCTCCGGTACTAGCGGTCCGACGTTTAACCCAGTGCTTAAGCTATCGTGAGG
          TGTGGCCCGCTCGTGTCCAAGTAGACTAACGTTCAACCCAGTGCTAGACGCATCCAGGGG
          CTCACGCATCAAGAGCTCCAGCAGTGTAGGGTTTGGTCATAAGCGGGAAAAGACGGGGGG
          CACAGTCGCTGAGAGCTGCAATGGTGTAAGGTATGGTCAAGCGCGGGAAAAATCCAGGGG

          GTGCAACGCCCGGACGTCTGTAGCAAAATAATATTCACTATATGATCTTTGTTGGATGCT
          GAACAAGGCACGAACATCAATAACGGTATAATACCGAATACATGCTCTATCATGGATGCT
          GAGCAGGGTTAGGAAGTCCGTAAGGGATTGATACGGAGCGTGCGTCCCACGTCGGATGAC
          GAGTTGGGCTAGGATGTCCGAAAGGGATTAACACGGAGCGCACTTCGAACGTCGGATGAC
          AAGTAGGGGTCAACTATGCCCAGCCGGGGGAGGTGAGACACGTAACGGACCCCACGAGCG
          AAGCTGAGGGCAAATATTTTTAGCCTGCACCCCAGGAATATGTCGGGAACGTCACGAGTC
          TAGTGAGGGACACAGGTGCGTGGTAGGAGTGATCGAAATATAGAAAGTGAGTAACAAGCT
          GAGTGAGGGACACTGGTGCGGAGTGGGAGCTGCCGGATTACAGAAAAGGATCAATAGTCT

          GCCGACCTCACCCGCGGGCGTAAAGCCGCCTGTTACACCTTCGTCGGGGGGGGTCTGTCC
          ACCGACCCTGCTAGCATGCGTAATACCACCTATTATAGCTTTGCAGGGGGGGGTCTCTCT
          ATAAACTCTGCACGCTGTCACAACGCAAAAGTCCCCTCGCTCCTAGGGAAGGGGTTCTCT
          ATAAACTCCATGGGCAGTCGTAACGCAAAAGCCTCTTCCCTACCAGGGAAGGGGTAATTC
          GGGTTGGTCTAATACCGGACCTTAGCTGAGCCCGTTTTTCCTGGAGACCTTGCGGCACTT
          GGCAAGCCCGAATATGGCGTCACAGCTGAAGAAAGTTTCACCGGGGCTGGCGGACCAGTG
          GGACAAGTCGTGTACAAGATCCCCCTAAGGTATAGCTCTCCCGAGCCCTATAGAGCAGAC
          GAACATGCCATATGTAAGGTCTCTCTAAAGAATATCCTTCTCGGGTCTTGTCGAGTAAAC

          ATCGTAATACTCCAATACAAAACATCAGTCTGGCTAGCGTACCTACGCATCAAAACACGA
          TTCAAATTCACTCAAAACCGAAAATTTACCGGCCTACTAAGGATCCGCTTGTAATCGACA
          TCGTCACACACTCGTGTTTGCAAATCCGTTGGGTTAACATGAGTGCCCACCGAGCCACTA
          TTAACACCCACCTACTTTTCCAAATCCGTTGGGTCATCAGGGGTACCCACCGACTCATCA
          CTCATCCCTTATCAAAAACATCACTTCACTCCCCTCAGGTTGTCGCCCTATGTGCTACAG
          ATCTTCCCTGCTCAGATACTTCACCCGGCCGGCCTGGAATTACCGGCTTCAGTGCCATAA
          CTCATACCTCCCCGTAGTGAACATTCTGCTCCTATTGGATAGATGTCTCAAACATACAAA
          CTCTCATCACCCCGTAGTGACCACTAGTCTCCTTTCAAGCTGGTGTCTTAAAAGTATCAA

          AACGGCCACTCTCAATTTGTTGGCCGACGAAGACGTCTGGCTTAAGGTGGGAGACTTTTG
          CCGGACCCCTATCACCTGATTAGTCGTCGAGGATGTCTGGTCTGAGGTGCGGGATCTTAG
          CCGGTTGCTTGTCTATCTTTTGATCGTCGAAACTGTTGGGCTGAAAGCGCCAGTCTTTCA
          CAGGGTCCCTGTCTAACTTCTGGTTGCCGGAATTGTCAGGATAGAAGCGCCAGCCCTTCA
          CGTTGTCACCGTATCGTCTACACTTGCCTGAGCGATTACTCTTAAAGCCAGGGATTCTCG
          TATTGCTAACATAGTAACTATGTTTACTGGAGATCTGGATCCCAGATCAGAGGGCCCTTT
          TGAGGCTACTATGATATCTAAAATTACATGTAAGATGACCCTCAAAGTAACAGGCTGTGT
          CAAGGCTACCATGCTACATAAGACTCATTGCAAGCTGTCTACCAAAGCGAACGGTCATGC

          TCCACATTTAGCAAAGTCCTGCCCTTGACTTAACGTAATT
          CTTACTTACGGTAAAAGCTTCCTGCCAGCTAAAAGTACTA
          CTCCTATTCGGACAGGCTTCACTGCCAGTTAAACGCAATT
          CTCCTATTCGGCGAGGCACTAACGCCAGTTTAAGTTATTC
          TTCGTTTTCTTACCGCTCAGCATGGATAAATACATACACA
          TCCGCTGTGTAGCCACTCCGGGAGGCTATGAAAGTTTGAA
          GATGCCGTATAGTCATTCTTGGCAGTCAATATGATAGGTA
          TCTGCCGTATCGAAGTTCTTGGCGATTAGTATGATAAGCA

