 8 1000
t1        GTTAGCTCCGGCGGGATCATTCTGACCCCGCATCGTTCCGTACATCCCCAGACTCACCAT
t2        GCTAGCTTGGACGAAATTATACTGACTCCGCTTCGATCAGTACTTATCCGAAAAATCCGT
t3        GCATATCCCGGCCTTCCCGACCTACTTGTACTCTCAAACCCACAAACATGAATTCGGTAT
t4        GCATATCCCGGCCCTCCCGACCTACTTGCATTCCCAGACCTACAAACATGAATTCGGTAT
t5        AAGTCTTAGGGAAAAACCAGATTCCTTCTCGCTCCAATAGTGCAAACATCGGATTCCAGC
t6        CTAATTCAGTACGAATCAGCGTTGCCACCTCCTTAAACTCGATAATCATCTGCCATTTAC
t7        ATATGTCTAGGGCCGATTGCGCTGCTGCCACCTATAGCTATTTATAGTCGAAACTGTCGT
t8        ATACCCCTAGTGCCGATCGCGCTGCTCCCACATATAATCACACTGGGTTGAAGTTGTTGC

          TACTGGTACGTGGGACCTGTTCTAACTGAAGAGCAGTGTGGTTAGAATTAATTTATTCCT
          GATCAATACGGGGGGCCTGCTCCAACGAAAGAGACTTGCGGATACAATTATATTATTGCC
          ATTCAACGCAACGAACAAACCATGGCTTGGGATCCCAACAACGATGGATTTCAATGTTCC
          ATCCAACGCAACGAACAAACCATGGCTTGGGCTCCCAACAACGATGGATTTCAATGTCCT
          GACTCATGACGCGTAGCTCGCTTAGCTATAGTTTTTGTTATTACCTCTAACTTAGACCCT
          GGTACGTTATGCGTAACTTGCCGGAGCATGGTCATTAGTATCGATAGAAACGACGGGCTA
          GCCATACTGAGCGTGGTCGGTCAAGTTATGCCTATTGGTCATTATCGTAATAAAGCAACG
          TACTTATTAAACGTGGTTCGTCCAGCAGTACCTACTGGCTATCGTAGTACTCAAGAGCCG

          ACCATAAAGTTCCCCCCGATGGTGAGGGTATCCAAAAAAGGTATATAGTGACTATAAACA
          ACTATTGAATTATTAACGAGAGTAAGGGGACCCAAATAAGGCATAGACTAATCACGAATC
          ATCCTAAGGATCCTCTACAAGAAGTTACACGGCAGGAAAACCCAAGTCCGTGTTGTAGCG
          AGCCTAAGGATCCTCTACAAGAAGTCACACGGCAGGAAAACCCAAGTCCGTGTAGTAGCG
          GTTGTCAGGAGAACCGGCATGGCCGTCCAGAACAAGGCAGCCAAAGCAGATGCCAAGGAA
          GTAACAAAGCTCATGGTACTGCCCGCTCGATAAGCATCAGTTTCAATATACGTTCATGAA
          ACACCAAAGAGTGCTGTCGTGGCCATACATCGGTGTACAGTCTTCGCTAGCGAATAGAAG
          ACACCAAAGGGCGTTGCGGCGGCCATTCGTCGGTCAACCGTCCTCGCTTGCGGATCGGGG

          AATTCGAGCCTTCATATCTGTCACGTGCGAATCGAGTTTAGGAGGGCCTTACCAAGCTCG
          AGTTAGATTCTCTAAGCGAACCGTATCTGAAACGAACCCAGAACAGCCCTACCATCATCG
          TATCCTGGTCTCTAAGCCAGATACATTTGGAGGGAGACAGGTTGAGTTGTACCCGTCGCA
          TATCCTGGTCTCTAAGCCAGATACATTTGGAGGGAGACAAATTGAGTTGTACCCGTCGCA
          ATAATTTGCAGATGAGTCCCTGACGGTGATTGGGACATCGTGCATAGTCTCCATTTGTCG
          ATTGTAAGAACTGGTGTCTGCTTCCAGCCTCGAGGCTGGGTCCAAGGACACCGGTTTCTG
          GCCGTAAAAATGTAAATGAGATACGTCCAAAGTACGTCGGGTTAATTGCCGCTAATCCTG
          GTCGTAGGAAAGTGAATAAGGTAAGTCCACGATACGTCGAGCTACCTTCTATTAATCCCG

          TTGAGGGGGTTCCTTTTCATGCGAATGGCCCTACCCTATTAGTAATACGACCGGCCTCAC
          TCGGGGGGGCCGTCCATCACGGTAAGGGCTCTATCTCGTTAATATAGCTAGTGGCCACCT
          CTAAGGCAGTTCTGGGCCACATGCGATACGCCTCCGCGGCCTTGGAACAAGGAACGCGGC
          CTAAGGCACTTCTGGGCCACATGCGATACGCCTCCGCGGCCTTGGAACAAGGAACGCGGA
          TAAAAGGCGCCGCTTGTTCTAGTAAATGTATGCTTGTAACGCCGAGGAGGAAGTGTGATA
          GTACGGGGCCCTTCGACGCTGGCTACTGCGTGCCTGTTATGTCAAAAGTGGAATGTAAGG
          TTTTTAGGGATTCTTCCCTTCTCCGCTGGGTCCTTACAGAACCGGATTGTGGGCGCGGCA
          TTTAAGGAGATTTACCCCCTAGCCAATGTGTTCTCATAGAACCGGCATGTAGTCGTGTTG

          ATGGGCCCTGTGACGCTGACTATCTGTTAGTGGACGCCTGTCAACTAAGTTTATCAGAAA
          TCGCGCGCTGTAAATACGTTTACGTGTTGTCGGAGGGCTGTCACTTAGGTCCTGCTATAA
          ACTTTGCTTGTGAGTGTGCTCAGCTGTGAGCAGTTGTTTGGAAACCGAACCGCTAGCCGA
          ACTTTACTCGTGAGTGTGTTCAGCTGTGAGCAGTTGTTTGGAAACCGAACCGCTAGCCGA
          CGTTCATGTTCATGTAAAATTGGTTCTGATTGTCCTGGATCTTTTAGTAATGCGAATTAA
          CGCTTCTATCTCTACCGGATCTGCAGTTCGCGACCACCGGCCATTTGGATCACTCGTCGC
          CTTCACGCTTTTTATGGAATTTTCATGAATAAGCTTTTAGTCACTCAGTTAACTGGTCGG
          CAGCCCGCTTTCTATGGAACAATAGTGGATAAGCCCTTGATCATTCAGCTTATTAGTCGA

          AAATTGCTCCCGATCAGACTACCAACTTCTGTGCTCAGTTGGAGGTTGTCGGACTACTCG
          TAATTGTTTCCGCCCAGGCTACTGGCTGCTGCGCTCAGTGGCAGGTTGTCGGAGTTTTGG
          GAGCTACTTCGGTCCCGTGCCTTCGGATAAGCGACTCATCTCAAGGAGTATCGTGCCCGC
          GAGCTACTTCGGTTCCGTGCCTTCGGATAAGCGACTCATCTCAAGGAGTATCGTGCCCGC
          GGATAGATGCGTCCAGGGTCTTTGGTATTCTCACTACACCTAGGTGCGTCAGAACATCGA
          TAATCACCTACCCCCTGGTCTCTACAATGTTCTACATACGATGGTGAATGAATACGCCGC
          AAAGTGCCATTACCATAGTATGTGGCATCGTAATTCCAGCTTGGAGATCAGGTACCTCAC
          GAATTGCTACCATACTAGTGTTCGACAACGCCTTCCCAGAACGGCGAGAGGGGACCCCAC

          AATTCGGTAATGTCGTGAGACAACACCAAGGATAATCACCGTGGCACAGTTGGTTTAGTA
          CCTTCGATGATGCCGTGGAACCACACTGAGGGTCTGTACAGAGACAGAGAGGGTTCGTTA
          CACTCTGCACTAGTGAGAAGCATACGGGAGGGCCGTTAACATGACATGAAGATTTTGGTC
          CACTCTGCACTAGTGAGAAGCATACGGGAGGGCCGTTAACATGACATAAAGATTTTGGAC
          AATTTGGGCTCGCTTGTAACAGCCCTAGACTCCCGTGTCTGTGCTGAGGGAGCGGACTGT
          TGATAACAACGATTCTCGAACGCGCTAAACGGCCACACTCATGTTGGGTGCGCCCGTCGG
          AAATTAAGCTAGACGTTCACCGATCTAAAGGGTTACTTACTTTGAGCCGGCATACGCCCT
          ATATCAGGCAAGATATTCGTTGCACTAAGGGGTTGTTCACTTTAAACCGGGATACGTCCA

          AGACAGGTTTTGACGATACGGCAATAGGCAGGCGATTGTGTTCTTTGTCGGATCCGGGCT
          AAATCGTTCTTAATGCTGCAGTACTTGAGAGGTGTTTGCGGTCCTTGTTGGGTCCTCGCT
          CAGCGGGTAAGAGTATCTATATCATCACTGTATGCTCTCGATCGCACCGAATGCTTAGGT
          CAGCGGGTAAGAGTATTTATATCATTACCGTATGCTCTCGATCGCAGCGAATCCTTAGGT
          CGTTGGCCACCATCAAATTATTAGTAATTACACGGAGGCTCTCATAAGTACGCGTCCGAC
          CGCCTAGCTCCATGCGTCTGCTTCTGACAGTATGAAGACAATTCCTGGCACGCTTCGTGG
          CGGCATGGGTGACTTAATTGGCACAGGAGGAGCTGCTGCTGCTATACCTCTGAGTTGCTT
          CGGCTTGGTCGACGAAATTGGCCCCGGTGAGGCTGCTACAGCTATAACTCCGAGCTGTGT

          AAGCTGCCTATGCCAGGAGTGGTGATGTCTGAACACAGCTGGAATAGGGTGACTGTTGGT
          TACCCGTCTCTGCCGGGATTGGTGTAGTTAGGACACAGCTCGTATAGGGTGATGATTAAC
          AAGCAGGCATATATAGCTCCGTAGTGCTTCGTGCGGGCCTAAGCCACACCGAATGCTTCT
          AAGCAGGCATATATAGTTCCGAGGTGCTTCGTGCGGGCCTAAGCCATACCGAATGCTTCT
          GTGGGATTTTAGGCAGGGTCGATACCCCTCGGCTGTGCGTCATTCAAGCCAGCAACAACC
          GAGCAGCCCTAGACAAGGTCGTCTTTTTTGCGTTCGGTGTTGTGCATCCCGGCCAACATC
          AGACCTTCACGCTCGTGAGTTCAAACTTTCGTATCTAATCTGCTTCCGTCGACAGCTCGC
          CGGTAATCCTGTTCGGGGTAAGGATTTGTCGTGTCTTCTCTATTTCTATCGACGGTTTAC

          GTCATCGCATAGGGACATCTTGATCAACCTTGATCCCTAACCGTAGAAATCTACGTATGT
          GACATTGATGGAGACCGCCTTACCCAGCGGCGGTTTCTAACCTAAAAAGTTAACGTGTGT
          GACCTTGACGGGCGTACCTCAAATTGACAGCTGCTCGGAACGGCCGTGGGTTATTAGTAT
          GACCTTGACGGGTGTACCTCAAATTGACAGCTGCTCGGAACGGCCGTGGGTTATTAGTAT
          CATCATGCCGGAGACCCCGCCCGCAAGCGTCTAGCATCAGGTCTCTCTGTCAAAGCGTGC
          CATTACTACAGAAGTGCAACCACTTGCCATCCGGCTACTACTCATTTTTATGGCATACAA
          TATTAGACCGGCGAACTTTACCATCCCCGTAAGACATCCGTAATTACTGTCAACCTCTAC
          TAATATACTGGCAAGTTTTACCATCGCCGAAAGACATCCGTGTTTGCTGCCCATTTCTAC

          GAATTAGGTCAGCGGCCCGGCGGCTCTACATTTTAGTTTGACCGCGTATGGCGACGGCCA
          GAATTGGGTTATTGGAAAGGCGGGTTCAGACCCTAACTTGACCGTGCGTCACGCCGGTCA
          TGTCGATATGAACGCTATCCCGGTCCTTTATTTTGACCGGGGTATGGATTCGCTGCGGTC
          TGTCGATATTAACGCTATCCCGGTCCTTTATTTTGACCGGGGTATGGATTCGCTGCGGTC
          CGCTACAGTCGCCACACCGCTGGTCTGTCAGTACGGGAATGCTACTCCTAGATCATGTTA
          CACCGATACTGGCACGAAGACGGCCCTTAAGCTTGACCACGCGAATCCTAGGTTGGGTCT
          CAGAGCGGGCGACTTGTTGCCAGAACCAAAGTCTGGCCATAAACTAACCACGGTAAGTCG
          TAGGGCAGCAGACAAGTCGTCGGGACCAAAGTCTAGCCATGATCCAACTACGGCAAGTTG

          TAAATGATCTAAAAAACCCTAGGCTATTCCGACGGCAGGATTTCCGACTATCCAAGGGTT
          CAGACGATATCTGACCCGCTGAGCTATCCCTGCGGTAGCATTTTCGCCCATTCCAGGTCC
          TATATTGAAACTAATGCTGCGGGCTGTACTCTAAGTCGGCGATCAAATTCATTCCGAACC
          TATATTGAAACTAATGCTGCGGGCTGTACTTTAAGTCGGCGATCAAATTCATTCCGAACC
          CTTACCACCAGAGATACTGCGTTCCTTAGGCGTAGACCTCACACTCCTCCATTAGTGAGC
          TCGTCCACCACAGTCGTGAAACTCTTTATGAGCAGCGCTCGTTTCGACACGCTGCGAAGC
          TAGCGCAACATCTTCGCGGAAGATAGGTGAGGCAGTGTCACACGCGCTTACTTATGGAGT
          TAGTACACCATCCTCGAGGTGGATGGGAGAGGCAGTGCTATAAGCGCCTGCTTATGGATT

          TCAACACACACTGCGAAAAGAGCCACCTCATAGCCTCGCCAACACACTAGAACCCCGGGG
          CCCGTACGTACTATTAACGGATCCTCTTCCTAGAATGGGCACCATATTAGGATGCCCGTG
          AATTGACTGATGGCCTGTCTGGCTACCCCATAGCGAGGGCCGATGGCCAGGTTACGTGAT
          AATTGACTGATGGCCTGTCTGGCTACCCCATAGCGAGGGCCGATGGCCAGGTCACGTGAT
          CCATTAGGGATCTATGAACCACTACATCCACTTCACGCCAGAGAGGTCGTGACTTTGCTC
          TTAACGCGAGCTGGGGAGCGTCCAACTATACATCCAGGCTGATATGTCAAACTGTGGCTC
          ACTTTGGAAGTCGAGGGCAGGAAGCGTAAATTGTATACATTGAACATAGTACCACTGCAT
          TCTCTCGAAATCACGGGCAGGGTGCCTAAAGTGTACATGCTGTACACAGCAAAACTGTAT

          GACCAATTACTAAGGCCTGAGCTTGATGTTGCAGCATGTAACGATTCCGATGTAGATCTG
          GGCCATCGGCTTAGGCCTGCGTTAGACGTTGCAGAATGCTCGGGCCTTGAAACACCTCTG
          ATTGACCGATGAAAAAGAATATATGATCTCGTTATACCCTATCTATCCACGACTCGTCTG
          ATTGACCGATGAAAAAGAATATATGATCCCGTTATACCCTGTCTATCCACGACTTGTCTG
          ATCCGCCCAACGACTAGCACTTTCGAAAAGATCACTGGAACGGGCTTGACTACGATGTGG
          GGGTGCTGAGCGGATCTCATCTAGGGAAGGTATACATACATGGACATGGCTAAATCGTCC
          TGGTATCCAGCGGACGTCATCTATGGAAGTAATATATGTGTCGGTCTAGTTCATCGGTTG
          CAGCATCCTGCGACTTTAAACTACGAGGGTAATTTGTCTGCTAAGTTTGCTAACCAGTTA

          TATTCGGTATTACGCTTGCCACACAATAAAATGTAAGTACGTGACTTCCAGAGCGGAGCG
          TCTTTGGAGGTAAGCCTGCGGCACGATGAAATGTTGGCTGGTGACTTCAAGAGCGGAGTG
          ACTTTAAACGAACAACTGTGGAATTTCCCAACTCGGCCTGAAATGCCCAGGAACACATTT
          ACTCTAAACGAACAACTGTGGAATTTCCCAACTTGGTCTGAAATGCCCAGGAACACATTT
          ATTCCCCCAGGCCGCTGGACAACTGTCCTGGTAAACTTTGGCCATTCCGGGAAATCATCC
          TCCTCTCCGGTTTGTTAGAAGAACATATCGTCGAACGAGGGAGACTGTGGGTAGCGTTCT
          ACTGCATTAGTACGTTGGAGTCGTGTGTCGACCCAATACAGCGTTTGACGAGTTTGCATT
          ACGTTACCAGTCCGTTGGGGTCGCGCGTTTCTCTAATATAGCGTTTGATGGGCGTGCATG

          ATCAGAAACGTGATTCACCCCAGAAATAGTCACTTTGGAG
          TTCAGAAACGTGACTCACCGGAGACCGTGCTAGTATGGAA
          GGCCGTTCGAACCCTTGTTATCGTATTTATTTATCCGCCG
          GGCCGTTCTAACCCTTGTTATCGTATTTATTTATCCGCCG
          ATACGAAATATGACTAATTGCAGGATATGTTGGTCAACAG
          CGCGGAGTTGCAATCAGTCGTTCGATTCGTCATACACCAT
          AGCTGGAAAGCAACACCAAGCGAGATGGATCGATCTATAA
          AGTTGGTAGGCAGTACAAAGCCAGACAAATCGATAATTAA

