 8 1000
t1        ACAATCACGTGCTCGACCATCTCCGCTTGTAAGTTCTAAGCGCGGTGAGTCTTTGGCGGG
t2        ATAACGATGTGCTCGACTATCTGGGCCTGTAAGTCTTAATGGTCGAGAGTCCTTGTCGAG
t3        ACTAGCCTCTGTCCGCCCCGTCGGATTTGCGACCTTAGGTGGAACCCAAGAGCCTGAGTA
t4        AAATCCCTGTGTATGGACTCCCCCCGACAGAATTTTTCGCGCCAATTTGTTGCTGTATTA
t5        GGATTCTCGCGATTAACGGACTGCCTCAAAAACTCCGTTGAGTTGCTGCTTATTAGTTAA
t6        GGACTCTCGCGATTATTGGAATGCCCCAGAAACTCGGCCGAGTTTCTGATTATTAATTAA
t7        CGTGACCCACGACCAGTCGAGTGCATTAACAACTCAGAAGAGTTAGTACTGACTAGTCCA
t8        GACCTCTTAAAATAACCTGAGTACATCGTAAACGTGGCAGGACTCATGTTGATAACCTCA

          CCATTGCACGATTACTCGTGGGTAAATTAGTGCGCAACACCAGGATATACAAATGAACCC
          CAACCGTACGATAGCTCGTGGGTCACTTCGTACAGAAGTCCAGGCTACGCAAATGATTCA
          CAATAGTTTAGTTGGTGCGGCGTAATTCCGTGCGGCCTATGATATTGCGCGAAGGAAACA
          GTAACGTCTGGTATGCGTTTTGTAATCCATCATGCGATCTGAACATGTTACGCGGACTCA
          CTTCCTCCCGATGAGTGCTAGTTATCCGTTTGTGCAGAAGGGCTTTTGCTACCGTGATTC
          CTTCCTCTTGATGAGTGCTGGTTAACCGTCTGTGCGGAATGACTCTTAATAACGCAATTC
          TTCTTTTATGTTGGGTGCTGGGTGTTTGCTAGTGTGGTATAGACTTTGCCGACACCATTA
          TATCTTTTCGACGAGTGCTGAGAGTCTGGACGCGTGGGGTAAATCTTGCCGACGTCATTC

          CGACCCACACGACTAAAGCCACGGATGGGCGCTACCGCACGCATTGGCGGTCAAGGCGCG
          CGACCCGCACGACCAAAGTCACGGACGGGCGCTGCCGTACACACCGGCGGTCAGGACGCG
          TGCAATGCACTTATAAGGTCAGGCAAAAGAGACGTTATGTCAGGTGGAGGAGACGCGTTG
          TAGCGCTGACCTATACCCTCGCGGAATAGCGGTGCCACACGAGCCGATGATGTTAGACGG
          TATCACGTGCGCGTAGAACGGATATCGTAGATTGTCGTACGTAGCAATGACACGAACCAG
          CATCGCGCGCGCACAATGCGGAGATCGTGAATCGTCGCACGTAGCAACGACTCGAAAAAG
          GAACGCGCTCACATGTAGAGGGATCTATAAATCATCGCACGGAGGAGCGATACGAGCCAG
          TGCCTCGTTCACGTGAAGCGGGGAGTTTGAGTCGTCGCGCGGAGCAGTGGCATGAGCCAG

          TATTCGAGCGGTTCCATGTTCTTCGTTGTACGCCGCTTTAGATTTTCTAGCTCCACGTGT
          TATTCGAGCGGTCCAATGTCTCTCGTTGTACGCCGCTTTAGATTCGACAGCTCCATGTGT
          TATGCAAACCGTTTCAGCCCTCTCGCTACAGGTTGTTCGGCATATTACTAGTCTACAATC
          TATTCATAGAGCTCGGGTCCTACCGCAAAGCTCCGCTCTACGGTATGTGGCCCGGTGTAC
          TCACGCGGCGATAGATATTTTTCTGCTCCCAATAACTTACCGTCCTTCTGATTGATGCAA
          TCACGCAGTGATAAACATTTTTCTGCTCTCAGTAACTTACCGTCCTCCTGATCGTTGCAA
          TATTGCATTGATATATACTTTTCTGCTTAGGCCAGCTTATTGTCTTTACGCTACACGCAT
          TGCTTCATTGATATAAACTTTTCTTCTGGAACTACCTCCATGTGTCTCTGATTCCCGCAT

          GGGAGACAAATAGAAGGTAAGCCACGCTGCCCCTGCTGGATTCACGCGGTATCCGGTTTA
          GGAAGACAGATAAACGGCTAACCACGCCGACCCTACTGGATCTGCGCGGCATCCGGTTTA
          GTGTCATGAAAGATCTGTAAACCGATTTGGTTATGATGACTTTAATTAATCTAAGGCACT
          GACGGGAAACAGATTTTGCAAGCCAGCAGATCCCCTTCCCCCTACTCTTCCCCTGGTACC
          GGGCGACAAAGACAATGATGCCAGAGAGAAATCTACAATTCCAAATCGTTGCCCACTATC
          GGGCATCAGATACAGAGATGCGAGAGAGAAGTCTACGGCCTCGCATCGCTGCCCACTACG
          GGGCTACATAAGTATTAATGTCAGAGCTGACATTGGGGTATTAAGTCGCTGCCCACTATG
          GAGCGAGGTAAAATTTGGGGACAGATATGACATCATAACCTTAAAGTGTTGCCAATCATT

          CGGAGGGAACGGACACTAAAGGGCCTATACCCCAAGGGACCGGTTCATCGGGCGACAAGC
          CGGAAGGGCCGGGCTCTAAAGAATCCGTACTCCTAAGGATAGGCTTATCGGGCGATCGAG
          AGATTGAGACAGGACTGACGGATTTCAGACACGCGAACACCATTCTATCAGTTGTTCGAC
          TAGTATGAACAGGGCAAGCGTGCCCCACGCCAGCAACGCACGACGAATAGAGGATCGGAT
          GTTATAGCTCAAAAGTACTTCTAGCGAAGGGCCCGTAAGTCCGGAAGGGGGGGAGGAGTG
          GTCATAGTTCAAAAGTGCCTCTACTGAATGGCTTGTAAGTCCGGTGGCGGGAGACAAGAG
          GTGATAGATCGCAACTACGTTATCCGTGGGGCTTGTAAAGCAGAAGGCGAGACATTGAAA
          GTTATAGATCACAGGCGAGTAATCCGTGGGGTCTGTAATGTAGATCGTGGGACACTGAAG

          ACCAACTATCAGGTAATGGAATGCGCTTATAATACACCTTTGCTAACCCTAAAGGCGTGG
          ACTAACTATCAGGTAGTGAAGAGCGACTCTAATTCACTTTTGCTAGCCCCAACGGCGAGG
          GTACATATACGGGTGGTGATTCTTACCCGACGTGGTCCTATGCTAATATCCTTGATGAAG
          GTCCACTCGAAGGTAATAAGGCCTGCTTGTTCATGATCCTTGTTCGCCTACTAAGCACTG
          GTTTTTCAGTAAGTTGCAGTTGATATAATGGAATCTGTTTCTACAGAAATTCGCGTCCTC
          GTCTTTCTGTACGTCGTGGTTTATTTAATAGAATCTGTTTTTTCAGAGATTCGGGTTCTT
          GTCTTCCTGTCAGTCGAGTCCACCCTGGTAGAGTCTATTTTTATAGAAGCCATGGTAGTC
          GTCCAGCTATACGTTATTACCGACCTTATGGATTTTACTCTTAAAGAAACTAGGGTAGTC

          TTAGTCTGTCCGAATCCGACTAAAGAGATAACGTTTCACCCGCGCACCGGAATTGCGGCT
          TTAATTCGTTCAAGTGCGAATAAAAAGATAACGTCCGATCCGCGCACTAAGCCCGTGGCC
          CGGCGATGAGCCAATCTAGCTCAGAGGCAGACGTGTGCCGTCCGCGTGATACATATAGCT
          CCGGGCTGCCGGATTCCAAGTAAAAAGCTTGCGTAGGCTCTGCACATAACGCCCCTGGGA
          TCGTGCGGACAGACGGCCCATCCCACCCCTGTCCTAGGTTCATATCTTGTATGGATACAC
          TCGAGCGGACACACACACCATTACACTCCGGCCCCAGGTTCGTATCTTGTATGGATAGAC
          CTGGGCCGGTACGAACGTGATCAAGTGGTCACTTAGGGTGTTTATTCCGTTAGTCTAGAC
          CCCGCGCGATGAGCTCGTGATCAAGCCCTAGCTCTGGGTACGTATTCGCCTTAACTAGAG

          AACCTAAAACTGTATAGGCTCCTTTCTAGACGTCACGCGAATTTGTGACGATTCCGAAGG
          ACTCTACAGCTGTATAGGCTCCCTTCTTGATTTCATGCGAGCATATAACGAGCAAGAGGG
          CAATTAAAGGCGCCTAGGTCGACTCGCAGCTCCGAAACTACAACATTTTACTTACACTGA
          ATGCTAAGGCCATCTAATGTCACGCTTAGCCTTCACCCTACCTTGTACGATACTACACGG
          ACACGGCGGTATCTTCCCTCTTCAACATATCCCGACCTTGAAGAGCAGGATAGATCCATA
          ACACGGCGGTCTTTTCCCTTTTCGACATATTCAGATCCCGAAGCGCAGAATGGGTCGATA
          ACTTAGCGCTTTCCTCTTTTGGCAATTGATCCTTATTTCTAACTACCGAACGGGTCCCAA
          AGCTATCGGCTCTTTCATTTCGCAACTTATTTCTATTTCGAAGTACCAAACGGGTTCGGC

          GTGCAATCGGCTTGCCCGCCACGTAAGGTACCCAAAGATGGGAATCCTTGTCCCCAAGCC
          CTGCAATCGGTCTTTTTTCCACATAAAGTCTCCAAAGATGAGAATCCTGGTTCCCAAGCT
          GTGGTACTGAATGTCCGGATGAGCAAAACCCTCAACGAGCAAAATTAGAGCGTACTGGCC
          GACCAATCGGCTGTCGGAGTGATCTAGGCTCGCATCACTCGATGCACTTTGCTATAAACT
          GTTGAATCAAGTAGCTCGACGGGACATGAGAACAATTATAGCGGACTTCAATTACAATTG
          GTTGAATTAAGAAGCTCGACCAGTGATGTGAACAGTGATATAGGATTTCAACGTCAACTG
          ATCGAGTTAATAGAGCTGACGAGAAACGTGAACCCTGGCAGAAGATTATAATGTCGAATG
          ACCGGGCTGAGGATGCTGTCAAGACATGCGAGAACCGGCGGAGGACTGTGACATGGAAGA

          GTTGACTATGTATCTTTCTTGGCCCCCCGCAGGTTCCGCGATCTCAAGATAATACTGAAT
          GTTGACTACGTATGTTTCTAGGCCCCTCGCAGGTTCGGCGGTCTCGAGGCAACACTGGAT
          GTGGCTTGCTTAATTCGCTCGTTAGCCCGCTGGGCCTGGGACCCACCAATGCAACATATT
          GCTTAGTGTTCCACGTCCCTGACCTTCTGTGGGGTCAGGGATCCCATGGTAGCGTGAATT
          TCCTACTGTTCACGCCTATTAGACGCACTCGATACTTGGTATCGCGACCGAAGATAAATT
          CCCTACTGTCCACGTCAATCTGACGCGCCCAATATTCGGATCCGCGACTCAAAATAAATT
          CCCCACCGTTCACACCTATCAGACGCATTCGGTGTTTGGGGTCGCGACTGGACAAACATC
          CCTAGCTGCTTTTAATTATTAGACGCACTTAACATTCGAGAGTTCGTCAGCGGAAATATC

          TATTCTCAGGTGCAAATCCGAGATGTAAGGGCAACTTCCGGCATAACTAAGCCCGACCTC
          TAGCCCCTTGTGAAAATCCGAGGTGTACGGTCGGTTTCCGACGAAACCATGTCCGCCCTC
          CCTCGTTCGCTACAAGCGTGCCAGCTATAAAAGACAAGCGGTGTGAGCAAGTGTGTCTTT
          TCGTGACCATTCTTCCTGGACTATCTCGCTTCAAACGGCAGCATCGGCAAACCCAAATTC
          TCTACCTTGCCGCCGCCGAACCACCCGGCATCGGTTAGGAACGCGCTGCGATCGTTATCC
          TCCAGCTTATCGCAACCGAACCACCCAACATCGGTTAGGAACGTGCATCGAACGTTTTCC
          TTGACCTGATCGCAGACAAGCGGTTCAATATCGGCCAGAAATGCGCACTAATCATTCGAC
          CCGACGTTCTGACGAGCACGCTGCCTAGCATCGTGTGAAAGTGAGAACTAACCGATGACC

          CCATTCCACCCCTCAGGACGCGCGGATTACGGCCAGATGTCGCCGTCCGCATGGTGGGCG
          CAACGCCGTCACTCATTACGCGTGGACTACAGTCCACCGTAGCAGTCTACAGACCGGGCG
          CACCAGAATCAGCCTAGTCGTTCACCTTGCCGTCTAATATAAGGTCCCGCTGACAAAGAG
          CGATGCCGCTCACCCCAATACATGTTTTGCCGTCGGACGGCACCTCCCACACAACACCCT
          CTTGGTGGCTGGGCCAGATGGCCATCCCGTGTTCTGAGACTCCTCCGTTCTCATACTCCA
          CTAGGTACTTGGCCCGGATGGCCATTCCGCGCTTTGAGACTCCTCCGTTCTCACGTCCCA
          CGAAGCAGCCGTCTCAAATGGTCGTTCCATGTTTTAAAGCTCCTATATTTATTTATCTCC
          CAACACAAGCATCTTAGGTGGCCGATTTGTGTAAAAAGCCTCCTCTACCCCCTTATCCTG

          AGCGGTCTGGCGCGAGCTCGGACTCCTCAACAGGACGACGAAAAAGGGTGATCTGAGAAG
          GTCAGTCCGGCGCGAGTTTGAACTTCTTAACAGGACCACGTAGAAGGGTGGTCAGGGAAG
          CATCTCTCTACATGGTCTGGTTTTGCTCACCTCGGCAGAAGCCGTGACTTGATTCGGATA
          GGTGACCGTTCTTGGATAGGCGCGACACGCCTCCTCCGAGGTTAAGGAGTGACATTATAA
          TCTGGTACATTAGGACATCTCACGACCTTCACACTATACAAAGTAGATGTATCGAGGGCG
          TCTCCTGCTTTTGCCCGCCTCACGGCCTGCATCGTATACAAAGGGGATGGACGGGGGTCG
          CTTCCTCCGCTAGGATGGCCTGCTGACAGCCCCGTAAGTAAAGAGTACTTGTCGAGTGGG
          CTCTCTCCGTTGAGATATCCTAGGACCCGTTACGAACGTAAAAGGCACCTACTGAGAGAG

          TGCCCTCCGAATTTGAGGATTAATGTCTACGGACCTAAGTCCAAAACGAGCCTCTGTGGG
          TGCGCTTCAACCATGAAGATTAATGCCTACACATCTGAGCTTAACACGAGCCTCAGCGGG
          TGCTCACCAGACCTGTTGTACGTAGTTCCGCGGACTGAGCCGAGGACCGGCCGAAGGAGT
          CGCGCATCAGTCTTTGCACGAAGAGTCTGTTGCTCTGGATTGAAGACGTGCCGTTGGAGT
          CCCGTGTACGATGCATCATGTGCGAAGGGGAAGTTAAACGTAGCAGGTGCCGTGGATGGC
          TCCGTGTAGGATACATTATGTACTAAGGGGAAGTTAAACGCAGTAAGTGCCGGGCATAGT
          CCCGTACAGCATGCATCATGCATTTGGTGAAAGTTATAAGAATTGGGCACCGGGGGCAGA
          TTCGTGCAACATCAATCAAGTAATAGGTAAACTCTAAAGAGACCGAGAGTCGGGTGTAGC

          GCTGTAGTCCAAGATTAAGATACATGACAATAGGGATTGTCTCTACCCCGATACTCGAAA
          GCTATAGTCCAAGAGTAAGCTATATGATACTAGGGATTGCCCCCACTCTGATACTCTAAC
          ACTATAAGGTTTGCGCAAAAACCGCGATCCTATGTACCGTTCATACTGTGAGACCAGAAT
          ATTTCGAAGACCCCACAAAACTTGTAGATGTATGGCCCATCGGTACTACGAGACTAAGAG
          CCAGTATCATCTAGCTGAACTTCACCGTGGACTATATTGTACCACCTGGCTAGCTCCCAA
          CCAGTATCACTTCGATGAACTCCACAGCTTCCTATATCGTACCCTCTGGCTACCGCCCAA
          TCCAAGTCATCCGGATGAAATTTAGAGGAGCCTAGATTGTACCCTCTGGCTGACTTCTAA
          TCAATACCATTTGGATGGACCCTAACGAAGCCTGGATTCCACTCTCTGGATCATTCCTAT

          TCAAGTTTTTGGCCAACCTTATTAAGGTGCAGATGGCTTA
          TTATGTTCTCGGGCAACTTTACTAAGGTGAACGTGGTCAA
          GGGAGATCGCGTACAAGCGGATCAGGATGGGTATAAATCA
          AAATATATCTTATTCTGTGGAGCTAAATAGACCTTTGTCT
          GACCCTCAGCAATTTATAGAGTCATGATCTGCGGGAAACT
          GGCCCCCGGCAATTTATAGAATTATGGTTTGCGGGCAACT
          AGACGCTTACAATCCATTAAACTACGTTTTGCGGGCAATA
          CGCCGCCAGCGCCGTATTCTACTACGTGTCACGGGCGGCC

