 8 1000
t1        ACTTGATAGTCTTGTAGAATGGAGCTTTATTTAACAAATCCCTACACCCGGCGGTTGGTG
t2        ATGTAAGGGCGGAGTGGAATGGAGCACTATTAAACCAAGACCGACACCCGACGATCGGTG
t3        ACTAAACGGCAGCGCAATATGGAGTTCTCCTTAACAAACCCCCACAACCGACGATCGGTG
t4        AATCTATGGCTGTGCGGATAGGAGCATTCCATCTAAAATCCCCACCTCCGAGGTCCAGCG
t5        AGCTTATAACGAATAAGGATGAGGCAACAGCTGGCTAAGAGTCGATGCAGAGGAAAAATC
t6        ACTCAACAGAAATTGAAGATGACGTGGAGATTCAGTAACTATCTCTATTGAGGATAAGCG
t7        TGGAGATCAGGATCGAGGGTAAGGTGTCAACCGTCCAAGTTTTGTTGATGAAGTATGGCT
t8        TGGAGATCAGGATCGAGGGTATGGTGTCAACCGTCCAAGTTTTGTTGATGAAGCATGGCT

          GAGGCGCGCTCCATACCGCCCCCTCGGTTAGAAAGTAATAACCTGGTTTCACCTGGGAGC
          AAGACGGAGCTTTTGAGGCCCCCTCGGTTCGAAGGCACCAACAACCTTCCACGTAGAAGG
          GTGGCGCGCTTTTCAGAACCTCCTCGGCTGGAAGGTAACACCCGTGTTCTCCGTGGGAGA
          GGTGCGTCTTGGCTAGAGCACTTTTGCAGTATAAGTGCTTACTTGGATTCAAGTGCTGGA
          TCGGAGTCCCAACACGAGCAATAACTGTAAGAGGGTTACACCCACGTAACTGGTAAAAGT
          TTAGGATGATGATGGAAACGTTTACGGCCGCTGGGAAGCGACCGCTTTACAGACACAACA
          CCCCTGTCACCAACAAAGTGCTCAGTGTTCGACGGCATCAGAACCAATATCGCCGTGGTA
          CCCCTGTCACCAACAAAGTGCTCAGTGTTCGACGGCATCAGAACCAATATCGCCGTGGTA

          AATCTCGAAAAGAATCAAGATGGATTTGACCTATATAGAGATCAGACCCGCCATAAGGAA
          AGTCTGAGAAGGAGTCGTGATAGATTTCGTCATTATGAAATGCAGAACTGCCGTAGCGAG
          AGTCCCGGCAGTAATCTAGACTGAATTGAACACTCTGAAGCGTAGAGCTGCCGGAACTCG
          AATCTCAGTTAGACTCGTCACAGATTTGATCTTTATTAAATACAGTATTGCCGCAGAAAG
          ACCTTCAGATGGCAAAGTCACACATTCGTCCGCTATAAGACAAAGAACCGTATTCCCGAG
          GAGCTCATTTGGTTTAATCGTAGATTTGTCCGCTACTTGACGAAAAATCCATCTACCGTA
          AATTCCATAGGGCCATCATATATACGAATCTACTGTGACAACCTAGGCAAACTCAGTGTG
          AATTCCATAGGGCCATCATATATACGAATCTACTGTGACAACCTAGGCAAACTCAGTGTG

          AGTCTAGGAGGTGTTAGTTGTATGGCTCTGCTCCGATCGTCGTTTGTCTTCGCTGAATGC
          CACCTAAGAGGTATTAGTTACGCGGCTTTGCCACTATCGAAGCCTGCATTTGTTGATCGT
          CGCTCAGGAGATGTTAGTCGTCTGGCTTTGATACACTCAGCGTCCGGACTAGCCGATTGT
          CTGCCAGGAAACGCGGGCGTGCGGGTATTACCTCAAGGGATGGTTGCGTTGTCTGATTGT
          TAGCCATGTTCCGACGGCGGCCCGGTTTTGTTGCAATTGTTGTTTGGTTTCAATGTGCGC
          CAGCAAAGGACCGTCTGTCGTTCGGTATCGCTATAGCTGCTGCTTGAATACACTGAGCGC
          GGGTTGGCAGCAGCCATACGTCCGACTTTATTATAATTTGGGTATGGGGCAACCGAGTCT
          GGGTTGGCAGCAGCCATCCGTCCGACTTTATTATAATTTGGGTATGGGGCAACCGAGTCT

          ATACTTCCTATGACCGTCCGACCCGAGCCCTCTGTTAAATTCTTCAGAGAAGGCCCCACC
          TTACTCTCTACGACCGGATGGTGCGACCTTTCTATCAGATCCCTTACAGCAAGGCCTTCC
          TTACTTCGTATGACCGTGCGCTGTGATTCTTCCATCCGGTCCATGGCAGCAGAACCCACC
          TCATCGTTCGCCCAAGTGTGGTACAGTCCTTCGACACTCCATTCCATGGCAAATCTTCCT
          GCTCAGGCCTTCATCGCACAAGGTTACCCTCTTGCAAGATATTTGACAGTCAGACTTACC
          CGATCGTCTACGATAGCACAGGTCTACACGTTTGGAGTCGGTTTCACGGCCGATCCCACT
          TGACTGGGGTCAACAACGTTATGTCACCTAGTCGCGGACCACTTGGCAAAAAGTTCTGCC
          CGACCGGGGTCAACAGCGTTATGTCACCTAGTCGCGGACCACTTGGCAAAAAGTTCTGCC

          GTACCTCTTGGCCATTAAAGGGGGGTGTGTTAACAGACTCATCGATCGGGTAGACCTACA
          CTCCCCCATGGCTGTTATAATAAAGCGTGTCACTAGACTCATCGGGCTGCTGGACCTATG
          CAACCCCACAACCTCCATGAGGACATGTGTTACTAGATTTATCGACCCGGCAGACTGACA
          ATATTTAGGAGCAAATACGAGAGGGGGCATCACCATATGCCTCGATACAGCAGAGTCCTA
          CTGGCTCCGAGCCTGTCGTACGCGATGTCCCATTTTATCAATAATTCAGGTTGATTCCCG
          TAGGTCTATACCCCAAACGTCGAGGCGTCTAATTCTACTGATTTATCAGGTGGACCTCCA
          AGACTGTACGCGAATCGCTGGGATATTGACTCGAGTTAGCATCCACTCTCTAACCACAGG
          AGACTGTACGCGAATCGCTGGGATATTGACTCGAGTTAGCATCAACTCCCTAACCACAGG

          TCCCAATTGCGATCAAGTGACGGACAAAATGCTAATATACTCCCGATCGGTGTGCCCCAC
          TTTCTTTTGCTACCAACTGACGTGTAGAATGCAGAGATATTTTGAGTCGGTATGCACCCA
          TCTCGTTCTCGAGCAACTGACGGATGTAGTGACAGAATACTAAAAGCTAAAATACGCTTA
          CCGAATCGACCATCCAGAACTGGATGACGTATTGGCAGACTTAGAACCGGTATACGCAGC
          CCGCATGGTATATCGATTCTTGGGCGGCAAAACGGGATTTCACGCAACGATTTATGCCTT
          CTGAATAATTGGTTAATCTCAGAGCGATCCGTGAGGGTAACCCGACATGGTGTATGCCCC
          AAGTGTACGAGACCTCATCAATTGGGGCCCGCTAGCAATTACACGGGCAATCCACTCTAG
          AAGTGTACGAGACCTCATCAATTGGGGCCCGCTAGCAATTACACGGGCACTCCACTCTAG

          GTCCTAGAGGCGCTGCCGCAGCTTGACTGTCGATATTGTGAAGAAGATCTCTCGGGTCAG
          GTCCTTATTGTGTTGCGGTAACTTAACAGTAAATATCGTCGGGAAAATTTCACTGGCGAG
          GTTCGTACCGCGCTGCGATATTTTCACCCTTAACTCCGTGAATAAAGCTCCTTAGGATAG
          GTACTCGTCCTGGCGGGTCAATGCCATAGATGCCGATTACTAGAGAAATCTACAAGTCGG
          ACGCCGCCTGTGACGCAACTGCCTAATTGCTGTAACCATTTTGCTTGACCTTCGGGCTTG
          GCGCCATCTAAGCCGTTAATAACAGACTCTCATAAATGCTTTGTCTGAGTCGCAGGTTTG
          TGCCTTTATGTCGGACAGCACGGGGCTTGTCAAGTGTAAAGGCTTGAACAGGCACTCAAG
          TGCCTTTATGTCGGACAGCACGGGGCTCGTCAAATGTAAAGGCTTGAACAGGCACTCAAG

          CTTACAAGCGGGAAGGACTCTACGCAATGGTAATTTTCAAGTGCTCACTTTTTGAAAATG
          AATTCAAGCGAGAACGAGTTAACGCTCCAGTAATTTTCGAGTACCTTCTTTTTGAAGCCA
          ATTCTGAGCGTATGGGTCCCTACGCATTAGTAATTTTCGAACGCTCTTCTTTTGAAAGTG
          GGTCATATCAGGCAGGGCTTCACACGACAGAAAAACGCGATTATTCTTATCTGAGAACTG
          ACCCGACGTAATAAAGGCCCCTCGGGTGATATGGCCGTACGCGTAATTTTGCAAGACGTA
          GTATTACGTGTTAAGGGTACTATGCGTCATTAACCCGTGGACGCTCTTCTTCAAAGGGCT
          ACTTAATTTGTTCACCGCCCAGAGAGCCAGCCCGTGCGTGTTACCTCTCTACGGGAGCCG
          ACTTAATTTGCTCACCGCCCAGAGAGCCAGCCCGTGCGTGTTACCTCTCTACGGGAGCCG

          CAGACATTGTCCGTAAAACACCGAATACGTACCACGAATTATGTCATTAGAGTTTCACTT
          CAGACGTCGCCTGTGAAAAGGTGGGCGGACGTTAAGTGTTGTGCCGTAGGAGTTCAACTT
          ACGGCGTTGCTCGTATAACATCGAGCGGATGCTGAATACTGTGCTATCGGAGTTTTATGC
          CAGAAGTGGTATGTATAACATTGAAAACGGGCTCAACACCGTGACATAACTGATCACCGC
          CCGGCACCGCCCGCTCCATACTGATAAGAAGCTCGGTCTAACTCCGTGACTGATCAATGC
          TCGAAAATGCCTGGTCGGTATCAATAGGGAGCTCTGTCTGGTTCCGTGGCTGATTAACGT
          CTGTTGTCGTTTCAGCCGCAGGCACTCAAGACTAAAGTCTATCTTACGCGTGTTCGAAGA
          CTGTTGTCGTTTCAGCCGCACGCACTCAAGACTAAAGTCTATCTTACGCGTGTTCGAAGA

          TAAGCGTACCCGAGACATGCCCATTCTTAAGGCCAGGATTGTTATCTAGGGCCGCATAAG
          TCAGCGCACCAGATTCAAGCTAACTTTCATGTCCGGTATTGCTGACCTGGACCGTCTTAC
          TCAGGGCACCTGATTTAGGAAAACTTAAACGGCAAGCTTAATTCGCCAGGGACATGTGAT
          GTGGCGACATTGAAGCAGTTTCCCTTATACGATGCATATAGATCCCTAGGGTCGAATTTA
          TCCACGATTATAGTCTGGAGAGCAATCCGTAGCCAATTCGGAATGGTAGGGCCGTATAGT
          ACCATGTTTATGCTCCGAGAAATAGTTCTTGATGGCCCCGGGATATTAGCGCAATCCCTT
          GTTTCGTAAATGATGCCGGACGACTCGAGCGATTGCTCTTGGAGGGCTGGCGGTCAATCC
          GTTTCGTAAATGATGCCGGACAATTCGAGCGATTGCTCTTGGAGGGCTGGCGGTCAATCT

          CCAACGTGTGCGACCCATTAGGAAGCGTCGACTTTAGGGGTATCGTGGTGTCTTGACTAT
          CCAACAAGTGTGACCCATTAGGAAGGGCCCACCCCATAAATATTGTCACGACTCGACTAT
          ATAGCGGTTGCAACCTCTCACTAAGGGCCAGCCCCGTAAGTGGTGCTGTGACTGGACCAT
          CTGACCCCAGCCGCCGCTCAACAAGAGTCAACCGCCTAGGCCTCGTCGACCTGATACTAT
          GTGGTGCCCTTGGCTCCCCAGACAAGGTCGACACTCTAGGTTCCATTCAACCTTAGCTAT
          TGGTAACATTCGGACCTTCAGTTAGGGTCGATCCCCCAAATCCAATTAAACCTTCACCTT
          CCGAGCCTTGTGAATCTCTAGATCGATGCAGCTTTCTGCGCCATACTTAACCTTAAAAGT
          CCGAGCCTTGTGAATCTCTAGATCGATGCAGCTTTCTGCGCCATACTTAACGTTAAAAGT

          GTCTGCGCGTTTGGCAATCGGCGAGCGAGACCACCGGAGTTATTCAAGACTTGAAGGAAT
          ATACGCGAGTCTAGCAATCGGCGTGCGAGAAGATTAGATTCACTCAAGGTTTAAGTGGAA
          CTACGCGCGTCTGGCAATCGGCGTGGCAGACTTTTTGACACACTCATCATCAGATTCCAT
          GCGTGCACGCCCGGCAATTGGCCTGTGGGACCCTTCACCTGAGGTCAGATTCAAATGGAT
          TTTCGGATATTTAACAGGTGGTGGACGAGGATGCCCGCTCCGCGTTAGTTCTGAAGGGAT
          GTTCGGATACTTTGTAGATTGTAAACGAGACCCGCTGCTTGGGGCACGACCTCAAGGGAC
          GCGTGAACCTTCGACGGGCACTGCGTCAATCATAACGTCCTTTGGCCGGTTAGGTAAGAT
          GCGTGAACCTTCGACGGGCGCTGCGTCAATCATAACGTCCTTTGGCTGGTTGGGTAAGAT

          GTCCGAAGACGTGTGCGAGGATCAATCTTGGTGGTGATAGCTGCGATACGCTTGAAAGTA
          GTGCGATGTAGTGGCTGTAGATCAATGTCAGCGGAGCTCGTTTTAACTTATTAGGAAGTT
          ATTCGGCGTGGCGGAGATCGATTCCTCTCCGCAGAATTAGTCGTGATTTGCTTAAGAGCT
          ACGCGCTATAGAGCACATTGAATATCACCATGGGAAATGGATCAGACATGTCCGCCCGCT
          ATGTCAGGATTTGTGATTAGACCAACCCGTTTGAAGATAGTTAGGGCATAACCTCCAATT
          ATGTACGGGAACGCGATCTTACCGACCAGGTTGCGGGCAATTCAATCGCAACTTTTTCTT
          ACTACTCGCATCGTACTTGAGATTGAAGGCGGAGCGCGCGTTGCGAAAAAAACGATGGCT
          ACTACTCGCATCGTACTTGAGATTGAAGGCGGAGTGCGCGTTGCGAAAAAAACGATGGCT

          AGCAGATATTATATCGAACCAGGTTGCATGCTGAAAAAATGTTGCACGCATCACAACATA
          AGAGGGGATGGTGTATAATTACGTCGGCAACAGAAAAATCGCCGCGCACATCACCATTCA
          AGCGGACACAACATCAATCTACGTGGCCTGAGGAACAACAGCCGCACACATCGTTGCACT
          CACGGAGATAACACTAAATTACTCCAGATCCAAACCGAACGTCACTCTTCTGGGCACGTA
          CACGCAGTCTGCTGGCCATTCCATTACCTAGTATTCGATGATCGCGCCTCTACATGCGTA
          TACAAAGTCCTTTGGTCTCTCCGTTGTCTGGTCTATTGAAGTCGCGCCTTGGGATGTGCG
          TACAGAGAAAATACACCCCTTAAATATGCGTGACGCAAAGGCCTCGCCGTACTGCACATC
          TACAGAGAAAATACACCCCTTAAATATGCGTGACGCAAAGGCCTCGCCGTACTGCACATC

          GACTGACGACGGGCCTTCCTTAGGCGGATGGACTTGGATCCATACCCTGCGTAGTACAAC
          AATTGACGACGGGCAACTGTTAAATGTAGTTATTTGGACTTATATCCTGCGTACAACGCC
          AACTGATTAGGGGCTGATGTTAAGTACGAGCCCTTGCATCCAAATCCTGCATAGTATAAC
          TATTAATGGCTGTCAACCGTTAAGGGGATGCGCGTGGGATTGGCCTTTACGTAGCGTTCC
          GAACGCCGATGGGTGACCATTTCGGATATAACTACGGGCTTAAACCTCTCCACATATCAA
          AGGTGCCCACGGGTAAATGCTGGGGTTATAATTACGGGCCCAGTATTCTTGATATGCCGA
          GTATTTAGATAGTTCGTCGGCCGAGGTAAGCCCGTGGACCCCTCCTTATCGCCATATCGT
          GTATTTAGATAGTTCGTCGGCTGAGGTAAGCCCGTGGACCCCTCCTTATCGCCATATCGT

          TTTGCGTTCCGCTCTCAAGCAGATATCAAATGACGAATGG
          TTTTCGCTCCTTATACGAGCAGACTGCCAATGGGGGACAG
          ACTATACTCGTTTAACGAGTATATATCCAACGGAGGACAG
          CTGACATCCAGCTACCCTCGGAGTGCCCGCTGACGACCAA
          TAAACTCTTACCCATAATGTGAACCGGCTATCAATTCGAG
          TTAAAACTTACTTGGGATGTGCCCGTGTAGTTGAACTGGG
          CGTCTGCCTGGATCTGTCAAGCGTGGGTACTGGCATACTG
          CGTCTGTCTGGATCTGTCAAGCGCGGGTACTGGCATACTG

