 8 1000
t1        GATATTCAAACCATGAGCCCCTCTATGGTCTGAATCGCTCAGGTCTACCCGATAAAGCAC
t2        TTAAACGGTAATGCGGGACGCTTTACGAGTAGTGTGGCTTAGAGCTGGATCTCAACGTTC
t3        GCATCCCAGGGCGAGTCATGGTATCAGGGTGTCTGCGCCTATAGCAGGCCGTCTGCACGC
t4        GACTAATGGGTAAGGCCTCAATCTTTACGCACATTCGCATAAAACCGACATCTTACGTAT
t5        TAGCATCAAGTTGCCGGCTTGTATCTATTCCTCAATGTTGGCTTGTCAACGCCTTTACAC
t6        GATCGTTAACCCACGAGTCGGTGCTGTGGATTTACACTAGATATTTAATCGCATACACTT
t7        ACGCTTCGTCCTGGCAGTTGAATATCATTGCACCAGATACGGAGCTTGTCATACGCACGC
t8        AGATCTCACGTCGGCAGTTGAATCTCATTGCAGCTCATAAGAATCTGGCCTTGTGCATAG

          GTGTGTGCTCCACTGAAGGCGCATCGCGATCAATTTTTATGCGAGAGATCATTCTTTGAG
          CTGTCCGCTTGTCCTACGAGTTATTGCTTTCATCACGGCGTCGCTATGGCTGGTGGCCAG
          ACTCTTTTACTACCAGACGCAAGTCCCACTCGCCCCTATGTTGTGGAACGCCGGTGTGAT
          CCAGAGTACCAATCCGGAATCGTTCGGCCTAACAGCTCAGGCACGGTCTCACGCCGTCTC
          AAACTCACAAAAAAAGGGGTGCGATATGTCTTTCTTACCGACCTATAACTCCATTTCATA
          TTAGTCCTTCATGTGGAAACCTGGTGACTTAGGTCTTTCGACGAGCAGCTCGACATTGCT
          CCCACGCCTCAAACAAAGACCCATCGGGAGCTTGATCATCACATGAGGTTACGAACTTCA
          TCTTCGCCTTAAGTTAGGATCGACGGGTTACGTCTCTGTGACGCTAGGTAGTGAGCTTCT

          CATATGAGTTGATCATACTAATTGATATAGGGTGCCCCATTCAAATTAATCTCATAGCCA
          CGTGCTGGATAGTGAAGCGGATACGCGCGAAGAAGCCAGTTGTTACTAGTGTTACGCAGG
          ACTCCTAGACCACCATTTATTATCCCGCACTACGTCTCCCATTCATTAGTAAGTTATAGT
          CGCTCTAAACTATCTAGTACCTATGGATGCTTAGTCCTACCTTGATCAGTACTCTATCGC
          ACGGCCATACGAAGAGGTAAAGATATGTACTCACTCTCACATTGATGGTGTTACATGAAA
          GGTCTAAGACCTGTTGGCACGGGTGTTCGCCGCGTTCCGTGTAGCCGGCCAATCAGACGG
          AGTGTTACATACCTAAGAGCGGATGCTCGATGATTTCCCCATCGCTACACTCTCAATTGT
          GGTGTTGGTTGACTTAATGATAATGTATGTTGGCCTCCTAAACGATTAGGACTCAAATGT

          CCGCGGGGGGCACGGACGGTGAGAAGAGTGAGAGGAGGCTTGTAGATACCAATCCTGTAA
          TGGGGGCCATTAGGGGTTTTCAATGGCGCGATTTGTAAAAGGACTCAAGTCACCTGATGA
          CCAAATTCGCGAGTGGTCGCTCCTGAGACACTGACTGTCAATTTCACATACACATCGACG
          AGTTAACTATGTGTGGCCGTGAAAAGTTTATGAAATGCAGACCTTGTCTTAGGTCTATGA
          TTATGCGGGTGTGAAGTTTGTGAGGGTTCTCAGAATAGGAGACCCCTCCCCTTTTCGTGA
          CCAGTCAAGACGTCCAATAATCGGGGGGCAAAAGGTTACAGGTTCCAACTTAAACGGAGT
          TAACATTTATCTTATGCTACTCTATGTCCGAACGGGTAATGGAATGTGATATTTATATGC
          TTACATCCGTTCTCGGTTACCCCTTGTCAGAAAGGATGACAGACTGTGCTCTTAATATGA

          GGCACGGCCACTTAGTGGGTTCGTATTCCTCTTAAGAGACATCCCTCTGTATCGCCCACG
          GCAGTGGTCCAGCTGTTGTCGTAAGAATGGTCTCAGGGGTTCAGAGACAAGCTATTGCCG
          AGGGCTAAATTAAGGAAGCCAGACATAATTCGAAGCCGGCGCCCGTGTGTGTCGAGAGTA
          AGGACTGCTTAAGAGGAACACCATTCCTTTAGAAGAGCCCTTTGGGCCATACGGCAGCCA
          GCAAGGGGCTCCCGAAGCTAGTGCAATCTCTTAAGTGGGGTAACTTTGCCACCACCGATG
          TAACAAGTCCAATCGAGTTTGAGGATCTCCCCGTGGCGTCTAGGCACGCCAACCTCTACA
          GGTACGCCCTCGTCGGATTTATGTTTGCCTTCGATTGACTCAACCCTTGCTCCAAGCGCA
          GACTCGTCCTGGTCGGTTCTATGTTCACTTCCGAGTGACTTATCAATTGCTCACTGCTCG

          CAGGAGGTGGTATCCCTTGCTTCTACTACCCGTTATGGTTGTAGAAATGACCAGTACTTG
          TAAGGAACTCTGTTTTAGACCTAACTGTCCTTTTCCGTTAGGTATATCCCCTGTTCTTAG
          TCCTATGTATGATCAGTAACGTGGTCGTCATCTTAGTATCATGATTGCGCGTAATACGAG
          TCGGTATGTACTCGAGTAATTCAGTTGCTTCATCTCCACACTGACGGTATGTGGCATGTG
          CACGATATCCCATGCTCATCACGACGGAGTATTATTGCCGTTCCTTAACCGGAGCCATAG
          CGCGGTACTTAATGATCGGCCGGAGTCGCCCCTCTGGGTAATGGCGTCGTGTGATGATCC
          AGCAGAGCTTTCTGAGTAGTATGAACGAACTCTCCCGACTGTGCTCAGGAAGAACTCATA
          TGCAGAGCCGCATGAGCAGTGAGAGTTGTCTATTCTGCCTGGTTTCGCGAAGCAGATACA

          ACTTGTCATTATAAAACCCCAATCCGCTGGTATCTATCCCGAAAGCGAAGAATAACGGGC
          CCCTGTCAAGTCCCATGCGGCTGTTTTTTGTAACAGCAGAATACGGTCCACGCTTTAGTC
          TCAATATCGGGACCGAGATGGGGGGTCCGGTGATAAGTTTGATCGCTCTACCTGGTAGCC
          TCTTCCTTTTATCTGAGTCATACATCGCCCTGATAATGGTGTCCGACCAACTCGGTGGGC
          TCTGGGTGAGATCTAAAAACGTGGTCATTCCGAGCTCTCAGGAAAGCCTACAAACCGGCT
          TCCTAGTGCAGTCATCCATGTATCTTGTTGTAATCTTCCTTACCCATACAGGCGGCGCCT
          GTATAACGGGCTATAAGTTGGTCGATAACAGAGCTTTTCTGGTCGAACAATACTTTGATT
          GTTTGGCGAGCTATAGGTCGGTTATCTCCTGAGAATTCTTAACCGCCTTACACTCTATCT

          TTACGGTACTTCGAATCGCTCCTTAGCCCTAACAGGATTGATCTCCCGACTGGACATTCG
          CTGGCACTATCCGGTTAGATAGCCGTCGCGGGACGGTTAGTTTTTATATACGCAGACCTT
          CTATAGGTCGACGTGGATTCGCCGGTTCCCTGTTGATGCTGTCTATCCGTTAGGATCCTA
          GTGTCGCGCCCCTCAAGGCAGGCTTGTATAGACTAATTTCTCATTACGGTTGCTCACCCG
          GCGCTGCTCCATAGAGACAGGTTTGGGGTCAGTTGATACGGTCATGTCCCTACTTGCAAC
          TCGTTCAAAGGGCGGTCGGCGCGCAGATTCGAATTGCTTTGTCGACTGATGATACAAGAC
          CTGCGAGACAGCTAAAGAGCACTCGGGGTGGAACGCCGTGGCACCCCGATCATACCGTTT
          CTGCCAGCCGGCTAAGATGCACTGGGGGTCGATCATCCCGGCACCCCGATCACACTAACA

          TTTCATGTTTTGAGTTGGGAGGGAACATGCGGAGCTATTCTTAAGCTTCAATGCCTGCGC
          AATGGCGCCGTGTGACCGGGGATTGGATTAGAACGTCCTAAACGCAGCAGATCTTCGAGC
          GTCCATGTACTGGGTTTACGGACTACTAGAGAAGCGAATTTATATGCGCAATATGTATGC
          GTGGGCGTACTGCGCTTTATGATCTCAGATGGGCAAACTATTCATTTTCGACTCTGATAT
          GTACAGGTCTCGTTTTCCACCACAATAACTTAGTTTTCTACTTGACTAAGTCACCTCCTA
          AGCCGTGTATCATGATCCTCGCTCGTGACTAGTTCCAGCTACCGAGCCTCTTTCCTGTGA
          ACCTCCGAGTCCCTGCCGAAAATTTACCCCCGACCTGTGTTGTTAGACAAATATTTACCG
          GATGACGGATTCCCGGCCACAATTTCCTCCCAATCTATCATTTCGAGCACATACCGGCAG

          AGATACTTTGGGGGGTTATGGTGACATGGATTGGCTACATACCCACCGAAGCCGTGTAAG
          CAGCTTGGCTTAGGCTCCTACTGACTCGTCACGCGCGGCCCGCTACGGTAGCCTTTCACG
          TGGACAGTTGAAGCAGTTTAAGTCCAAATGCCGGTCGTCTCAATGTATGTCACCAGACAG
          AGAACAAGTGAAGGTCTTCGGGCGAAGGTACAGTACAATTGCGCGCGTTTAATCAGATTA
          TGGTTGAATCTGGGGCACTGGTAAAGTGAGCCGAAAGCTTCGGTCAAGTCGTATCGCACA
          TGGTTAGGTTTAGGATTCTGAGACGTTTTGACGAACTCCCATGGGCATCAGGGATCCGGG
          CAATCGAATACGGTGCTTTACATAAACGCGCCCCTGGGATCCGTGAGGTCGCTCTGTAGC
          CAATTAAACACGAAATTATGCATAAGCGTGTCCTCAGGTCCCATGAGGCCGTCTTGATGG

          AATTTTCGGCTCGCAAGAAATTACCAACGTAGGCGCATGCGGACAAGAGAGCTTTCCGAT
          TACCTGCAACGTGAGCGTCACTACTAGTCCGCTTTGAGACGAGCCATCAGTCTCGTCAGC
          CCTCCTTGAAGCCCCAAGCATGTAAGGTTTTCATTCCTATCAGTTGTCAAGATCACCCAC
          CGTCCCGGGTTTAATAAAGAGGACTGGCAAGAGTGAACATAGACGAGAAAATACGCTGTC
          TCGGCGGCGTCTATAGCCCACCCGTGATATAATGATGTACATGGACTTATGTTTATCATC
          TATCCGTGGTTACGCTGTCTGACACACAATAGGCCCGCTGGACTAACGCAGTTCGTAAGT
          TCGCCATGGTCGGGTTATCAAAATAGGTCCTAGCTTACATGATGTATCTATGTTGCTAGA
          TCGCTTTGGTTGGGTCGTCGAAACAGGTCCTAGCTTACAAGATGTGTCTCGGCCAGGAAT

          CTCTGGTCGAAGCATAACGCGGGCCACGCACAATGGCCGACATCTAGGACGTGGATGATT
          CTTACAAGGCCGTCTATCGAAAAATAAATAGACTTGAGAAAGCCGTGAATCCAGTTCGTA
          TCCTGGAAATAACCGACGGACGACTAAAGCCAACGGAGTATTTTGGGAGTCCTGATTTCA
          TCCCGTAGAAGTATCGCAGGTGGGTAGACAGCACTGCGAGTACTCTAGGCCAGGAGTACG
          GTCTCGTACTCATACCCCGGTATCTGAGCCCTATTACAAAACGGTCAGGGGGGGGTCTTC
          CCCCGAAACATCAACGTGGAAGGCTGAAAGTGCATGAGCGGACCACCGTTTAGGGACTTA
          CCCTCAGTGGTTTACAGCGTTGGTTCTGAGCCGTCGCGATACCTGGAGGTTATGGCTCTA
          CCCTGAGTAGTTCACAACGGAGCCTCTACGCGGTCACAACACCAGTGTGTTATCGCCCAA

          AAGGCGGGGGGCGTTTAGAAGTAGATGCGTTTGCGTTACATCGGATGACCTCATACCCCT
          ATCTCACAGGCGGTTTATATATAGCCAAGCTTGTTCTCAAATACAGGATTGTGCATCTGA
          ATCGTAAGCGCCGACATAAACGAATCGTCGGAGCGATATAACGGGAGGCTTTCGCGCCGC
          GCCACCGGCACGGACCGGAAGAGCTCACCCTCGTGCTACGATTAACAGCTCCCGGGAAGC
          AGTTTAAGCACGGCCTTGGGTGCATTACATATCAGCGATGGAGAGTGAATTCCTGGCTGC
          ACATCTGGAACGGCTCCGAGGTTAGCAAGCATGTGTTACCCCTGCAGGTCTGCTTACCGG
          TGTGCTGAGGGGAATAACTATGTCCCGGGTCAGAGCTATTGTCTAACTCTTTCGAGGTTA
          ATCGTCGAAGTGAACTAGACTGTCCCGCGCCGATGCTATGAAAAAATTTCTTCGAGTTGA

          TTCGGCATATCGTGCTTTAGATATGCAGAATATCGCCCCCCACGATGGCAGTCTGAGTAG
          TCTAGTAATTGGTGTGACGAGCGCGGTAATCTAGACGTCCGCTATTGTCCGCTGGACGCG
          CCAAAGGTTCGGCGCGTGGCGCACTCTAGTCCACCCCACCACACAGTCTTCTTTGCTGTG
          CAAACGTCCTGGGGCGGAAAGTATGCGGGTTCACGTATTGTAACCCAATCTCCGGTGGCA
          TGTGGAAAAGACGGCGCCACGGATGTCGCTCAATATAATCTTATCAGAGTGATGCCAGTA
          TAAGGGTCAGCGTCCATCCCGCACCCGCATTGATGTTCCATCGTATGCTATTAGAAGGGG
          TCTGGGCGTTGTGATGCCGTAGATGCACGTTGTAAACCACACTGTCGCCCCTTAGTCGTA
          GGTGAGGACCGATATGGCGCACATGAACGCCGAGTTCCGCCACACCATTCATTAACAGCG

          GTTGTGGTTAAAGCAACTGTACTTCGATCTACCTTAGCCTCTGGGGACTTGTTGCATTTT
          TACTCAGAGGATTCCAGAGTAGCCTTGCCAGCAGAGTAGGGAACGGATCAAGCGTGTACC
          AATCCGGAGCACTTCTTAGTAACCGAGCCAATAGCGAAGGCTATTCGTCACTGCCGCGAG
          AACTGATAACAATCCTGTCACGCCCCACTGGCCATATCATAAAGCACCCAACAGTACGGC
          CTAGCCTGTGGCCTTTCGGGTGCCTTGCGCACCCCCGTACACCGGCGTTAGTAATTCTAA
          ACTTTCCGAAGTAGCACCGTTGACTCCCTAAGCTCCTTGCTCTAGCGTAAATATCTCGAA
          AGCACTACAAAGCCCTTCTACGCGGCGCAGAAATTTCTGAGCAGGCCTGGATTTAACAAA
          AGCCCTTTCAAGCACTCTAATGCGGAATTGATCTCTTTCTATAGGCGGAAATAGAAGGAG

          AGTTCTAATCGAGGGAGGCTTTCTAATTGAAATGACCGCGGGCGTGGCTTTCTGCAAGCA
          TCTCGATCCCATTTGTATAAGTAAGGCTGGCATCACAAAGTGTGTGACACCGTGAAACCC
          CGGCCTCTTTATGAAGAGTAGGGTAGTCAGTCATAGGACGCGAGTGGCTTGATATTCGGG
          CCGCTTTATCGCGTAGAAAAATCTCACTTAATTGGCGGAGTACGTTACCCTATATGTGGG
          AGTCCCCGTCCCTTGCTGATGGCTGAAATCGGGTGTACGACTTTGGATACGACGCATGAA
          CGCCGACCATGTACGTTTTTCCACAACAAAATACGTACTGCGTGAGATTCGCCGAAAATA
          AATCATTTTCATTCGGCGCAACCCGGTGCCTTTATTATTCGGCGACACTGATTATCTGCA
          AGTTAATGTCTTGTAGCGACATGTGGTGGCCTTACCGGTGGACGCTACCAAACGTGAAGA

          TATTTAGTCACGGAACTAGATACAACGCATCTCAGAGCGC
          TCGTGGGGGCACGATCTCTCCGAGGCCCAGCCATAGCTAC
          CGGCGGATAATAAACCTCTTTCGGGTTATATCCTGAACGC
          TGCCGGGTAGCGGGACCTTCCAAGATGTCGCTTGGAAAGG
          AAATCGGTGCTCAGACCCATCGTGGTGCCGCTTCCCCCAA
          TGTCGGGCGGTGGAGCTGGTTGGGCCGCCGGTTTAGTCGA
          AAGCGGGTCGTCAGGTTCAACAAAATGGTGCTTGGGTTTC
          AAGCGCGTAGTGATATCTGACGAAGTCCTGCTTGAGCCGA

