 8 1000
t1        CATGCACGTAAGCGAGGACGCATCGGCTTAGGACGATGCATCCTCGACGTAAATTGGCCT
t2        GAAGCTCGTGAGTGAGGATGCATCGGTTCAGGACAATGCATCCTCGACGAAAACAGGCCT
t3        GGTACCGATATGTGAAGGTGTATCGTCTAAAAGACGAGCCACTACGATGCGAACTGCCTT
t4        AAAACCGATGTATCAGAGCGTATCGATTCGCGCGCGCTAATCCCCGGCATGAACTTCACC
t5        AGATGTGATGCATCATACCGTAGGTAGTAGAAAGAGAATACGCATACCCAAGAACACTAT
t6        AGATGTGATGCATCATTCCGTAGGTTGTAGAAAGAGAATACGCATACCCAAGAACACTAT
t7        GAGTGTCATGTATCATGGCGTAGGTAGAAAATAAGGAGTACGACTAGCAAAAAACACTTC
t8        GAGTGTGATGTATCATGGCGTAGGTAGAAAATAGGGAGTACGACTAGCAAAAAACACCTC

          TCACCGTCGCTACTAGTCAGATAGAACTAATCCGAGTTTTTAGCGTCTAGAGACCGAACC
          CCACCGTCGCTACTAGTCGGATAAAACCAGTTCGACTTATCAGCGCCCAGAGACCAAACC
          CGAAGAATACTGCCAGTCAGATCAAAGCGCTCCGCCGGACTAACTAACGATGTCAGTTTT
          TCAACTATGTCGCACGATAGATCAAAGCGTGTAGCCTTGCTACTGATCGGGGAGCGTCTC
          TAGGTGCCACCATAGAAGCTACAGGAATCTCTTCCCGGATCAACATTCAACAGCATCCCT
          TAGGTGCCACCATAGAAGCTACAGGAATTTCTTACCGGATTAACATTCAACAGCATCTCT
          TAGGTGCCACCATAAAAGCTAGAGGAATCGGCTTCCGGATTAACTTTCGGCGATGTCTCC
          TAGGTGCCACCATAAAAGCTAGAGGAATCGGCTTCCGGATTAACTTTCGGCGATGTCTCC

          CTCAGAGTTTGGAGTCGACTGAGGACTGTCGAAAAACCTCTTTGGTCTGCTATTAGGCCA
          TTCTGATTTTGGCGTCCACCGGGGATGGTTGTAAAGTTTCTGTGGTCTACTGTCGGGTAA
          TTAGTAATTCTCCCTAGTCTCCAGTTTATTAATAAGAATATTCAGTCCACTAGCACATAA
          CACTGAATTCCCTGTGGCTTCAATTCTAATAATGAGGCCGTTCAACTCGCTAGTATTTAA
          CCAAACGGCTTTAACGATCGCTTGTGTACGTTGGCAAGATCCGCGGATGGGGGTATGCAA
          CCAAACGGCTTTAACGATTGCTTGTGTAAGTCGGCAAGATCCGCGGATGGGGGTGTGCAA
          CCTATGGGCTCCAACGGTTGACTGTGTACGCCGACAGGATCTGTGGTAGGGGATATGAAT
          CCTATGGGCTCCAACGGTTGACTGTGTACGCCGACAGGATCTGTGGTAGGGGATATGAAT

          TTCGGCATGAGGGACTATCTTCACTCGGGAAGGACATTAAAGTGACTCCATGAGTGGACT
          TCCGGCGGAAGAGCCTACCGTCATCCCGGAGGATCCTTCGAGTGCCTCCATGAGTGGACT
          TGACACGACGTAGATGCCCTGATATTGGAGACGTTCCCTAAGCACGTCCGCAAGTTAATT
          CGCCATGGGTGCATTGCCACTAACTCAAGCGAACCACATAAACCTTTACTCATGTTAATC
          GGGCTCTCATAAGGATATACTACCCGTATTAGCCCCTTTCCCACCAGCGGGTAATCAGCT
          GGGCTCTCGTAAGAATATACTACCCGTATTAACTCCTTTCCCACCAGCGGATAATCAGCT
          GCCATTTTATACGGATATACTATCCGTTTCGATCCCTTTCCCGACCGCGGAGTATTAGCC
          GCCATTTTATACGGATATACTATCCGTTTCGATCCCTTTCCCGACCGCGGAGTATTAGCC

          ATACGGACAAAAACGCGCACTGGTGAGCTTCCGATTTTCGGTATCCTAGAAGGCTCTTTG
          AAATGGCTGAAAAGGCGCACTGGTGAGCCTCCGACCCTCAGTATCCGAGAAGGCTCCTTT
          AAATGCCTAAGCTGGTGTTCTCCTGAATTTAGGAATATGGGCGTTTGAGTAGGTCCCAAA
          GGTAGTCAAAAGCGACGGACAGACGGTTTACCGAGACCCGACACGTGAAAAGGTTTCTAT
          AAACAAGGGTAAATGCCCGATAACGAGTCAATTCACCGACGACCATTAAAGGGTCGCAGG
          AAACAAGGCCATATGCTCGATAACGAGTCCATTCACCGACGACCATTAAAGGGCCGCAGG
          AAACAAGATGACATGCTCGATCGCGAGTTGATCCATCGCCGAGCATTAAAAGACAGGCGG
          AAACAAGATGACATGCTCGATCGCGAGTTGATCCATCGCCGAGCATTAAAAGACAGGCGG

          ACCATCGACATATCCACTACACTACCGCGAGATTAGCAGACCTGTGGTAGTTTGTCCATA
          ACTATGAACGCACTAACTACACTACCACGAGACGAGCTGACGTGAGGTACTCTGTCCACA
          AATTCGGTTCCGGCCACAATACAAATGCGTGATGAGCTGTTGTTCAGTAACCCGTTAGTA
          AACATAGTCAACTGTATAATATCTTAGTGTGGTTCGCTAATTCTTGGTATCTTGCTACTA
          CGAAGTTGTCTGCGTCGCGTATGCTTACCCGGCGGACAGCTTTGTCGTATTCCGTCACGT
          CGAAGATGTCTGCGTGCCATATGCTTACCCGGCGGACAGCTTTGTCGTATTCTGTCACGT
          CGAAGTTGTCTGCCTTGAGGATGCTTGTCCGCCGAGTTACCTCATCGAATTATGTCACGT
          CGAAGTTGTCTGCCTTGAGGATGCTTGTCCGCCGAGTTACCTCATCGAATTATGTTACGT

          CGCTGCGCTGCAGCTAAACGAAGTTGGAGACCAGTCAGCAGGTGTCAACTCACTTAGGTA
          TAATGCTCCGCAACTAAATACAGTAGGAGACTGGGCATCAGGCATAAACCCACTTAAGCC
          TACCGCACGGAGTGTCTACAAGAACAAAGGCGGGAACTGAGAGGCACAAATCTCTGCTAG
          TACCTTGCTGAGCCCCGGTAATAAATGAAAACAGGACCAAGAGGTGCAAATTCTCGCGTG
          CAAAGCCACCTGGCATAACGTATCCCAGGTTCGAGAACTGAGTGCATGCATGTCCTGCTA
          CAAAGCCACCTGGCATAACGTATCTCAGGTTTGTGAACTGAGTGCATACATGTCCTGCTA
          CAAAGCAGTCAGGCTCAGTGTAGTTGAGACCCGTGAAATGTGTGCATGGGGGTCCTGCCG
          CAAAGCAGTCAGGCTCAGTGTAGTTGAGACCCGTGAAATGTGTGCATGGGGGTCCCGCCG

          AGGCTTGCAAGCCTGTTCCGCTGACCAGTATGATTAGTCAAGATTGATAAAGATTCCTAT
          AGACTTGGAAGCCAGCTCCACCAACCAGTATAATTAGTCCTGATCGATAAAGATTCACTT
          CTGTCCGGAGGCTAGCCTTAATAGCCAGTATATCAAGCACACGCCGATGAGGGGTCTCTT
          GGTTTTAGCGATTAGCCCTAGCGAACGGTACAATAAGTACTCTTCGACCAGGAGTCACTC
          AAGCACAAGCCTAGATTATGGTGTCGAGAGTCGTTGGTGCTCGAATGGCGGCGTTAGAGG
          AAGCACAAGACTAAATTATGGTGTCGGGAGTCGTTGGTGCCCGAATGTCGGCGTTAGAGG
          GAACAAGAAGCTCGATTATGGTGTTGCGAGTTGTTCGTTCCAGATTGTCGGCGTCCCAGG
          GAACAAAAAGCTCGATTATGGTGTTGCGAGTTGTTCGTTCCAGATTGTCGCCGTCCCAGG

          TCAGGATCTTGATCGTCCCTCGGTTGATCAGCTGTATGGCAAAACCTAAATGCCGGGCTG
          TCAGAATCTAGATCACTACTCGGTTGACACACCGTATGGCAAGTCCTGAACGCCGGGCTG
          TTGCCATTTATATAGCCAATCAGCTGGTTCATTGTTTCTAAAGCCCTCGAGAGTAACTTA
          TCACCGTCTTTACACCTGCCGAGCCAATTTAGCACTTATTGAGGCATGAACATCAGAAAA
          GTGAATGACGGCGCGTAGTCGTGCTGTGCAGATGTCGAGTTAGGCGAGCGTAACCCGGTG
          GTGAAGGACGGCGCGTAGTCGTGCTGTGCAGATGTCTAGTTAGGCGAGCGCAACCCGGTG
          TTGACGGTTGGTGCATCGTCATGCTGAGGAGATGCCTGACTAGTCGGTCCAAACCCCGTG
          TTGACGGTTGGTGCATCGTCATGCTGAGGAGATGCCTGACTAGTCGGTCCAAACCCCGTG

          CCCTAATACCTTATCCAGATTTGCGGTGGGTCAAATTATTGACCCCGTTGGAGCTGAGCA
          CCCTAATTTCGCAACCAGATTTGCGGTGGGTTAAATCAATGACCCCGTTGGAGATGAGCA
          TCCCATTGTACCTCTAAATCTCGTGCCAAATAGAACTAAAGGTGCCACTCGGGATAAGCG
          CCCCGACACCGCACTGATGTTTGCGTTTGGCGGATTTTACGAATTCGCAAGGAGTGCGCA
          TTTCTTTGCGGTTACAATCCACGTGTCCAACATGCTCTCGCTACATAATTGGACAAGAGG
          TTTTTTCGCGGTTACAATCCACATGTCCAACCTGATCTCGCTACATGACTGGACAAGAGA
          TTTTCTTATGGTCACTATCCTCACGCCTAGCCTGACCTCGACACATAATCAGGCAAAAGG
          TTTTCTTATGATCACTATCCTCACGCCTAGCCTGACCTCGACACATAATCAGGCAAAAGG

          AAGGGCGGAAATATCATTTTAATTGGGACGAGGGTCACGTGGACATATACCCACTACGTA
          AAGGGCGTAAACAGCATATTCATCAGGGTGCGGGTATCGTAGACATATAGATACTACAAG
          AACGGTGAAAGTTTCGCACCAGCTGGTGTGCGGGTACCACCGTTACAGACATCACATGTC
          AAAAGCGACAGTCGTATATTAGCTGGGGTGCGGGCATTACAGAAACATTTGTACCACGTC
          AGCGTTATAGGAACTCAATTTGTCGCCCTACATACGTTACTGACATACATCGTATGGGTC
          AGCGTTATAGGACCTCAATTTGTCGTCCTACATACGTTATTGACATATATCGCATGGGTC
          AGCATTATGGACCTTTAGAATGCCGCATCACATGCGTTTCTGGTTTATATTGCACGGATC
          AGCATTATGGACCTTTAGAGTGCCGCATCACATGCGTTTCAGGTTTATATTGCACGGATC

          TTTGACCCTAGGAACTAGGCAAAGCATCACATTTGCGATGTGGCTTACCAGGCCGATAAC
          TCTGAACCTAGGAACCGGGTAGAGCCGAATATTTGCGATGTAGCTTGCCAGACCGATTTC
          ATATTGGCTGGATACTGGGATAAGGCATTCGTTTTCAATGGGGTTCTCTCAGTCGATCCC
          CCGACTGCTGCGGGACCAGAAACAGGGAATGCCCATAATACAGTTCACTTAGTAGTTACT
          CGGGGGCCCACTCCCCGAGGAGCTTGGAAAAACGAGTGTGTAAGGCGGTGGCTATTCCGG
          CGGGGGCCCACTCCCCGAGGAGCTTGGAAAAATGGGCGTGCAAGGCGGTGGCCATTCCGG
          CGGGGGTCCGCTCCCCGAGGAGCTTTGGAAAACAGGCATGCAGGGTAGTGGCCATTTTAG
          CGTGGGTCCGCTCCCCGAGGAGCTTTGGAAAACAGGCATGTAGGGTAGTGGCCATTTTAG

          AACACCCGTAGATCTATGCCTCGAGTTGTATAAAGCAATGCTATGTAGTTCAAGGTAGTG
          AACAGGCGTAGACCTACTCTCTCAATTGTAAAAAGCAGCGCTATGTAGTCAAAGCTAGTG
          CGTGAAGATCCGATTATATGACGGGCTGGGAAAAACCTAGCCGGGTGGCTGAATCTGCTC
          CGTAGATGCAGAACAATTCGCTGAATTGGAAAAAACAGCACCACGCGGCTGATCCTGTTG
          AAGAAGCCCAATGTAACGGAATAAACGATGTTGTTGATTAGCAAGTAGACGAATACCTGA
          AAGGAGACCTATGTAACGGAATAAACGATGTCGTTGATTGGTAAGTAGACGAATACCTGA
          AACAAGATCCGTGTAACAGACGGAACCATGTAGTTGACAGGCAAGAAGACGAATTCCCGT
          AAGAAGATCCGTGTAACAGACGGAACCATATAGTTGACAGGCAAGAAGGCGAATTCCCGT

          ATTATTGTCCAATGCAAAATGATCTCGCCATTGTGCGATACTCAGCGGGGCTCACTATCA
          ATTACTATTCAAGGCAGAATGATCTCACCATAATGCGATGCCCTGTGGGGCGAACAGTCG
          ATTGTCGTGAAGGATAATATGCTTCCCCAATAACAAAGTAGTTCGTGCGCTACTCTGTTG
          ATCGCCATCATTGATCGCCTACTTTGGCCCAGGTGAGGCGCTCTTTGCGCCACCCTGAAT
          CAAGCGCTTCATTGTCGCAGTTTCCCGTCCTATCGGGCCACGACCCGCCAGGGTTCCCCG
          GAAGCGCTTCATTGTCGCAGTTCCCTGTCCCATAGGGCTACGACTCGCCAGGGTTCCCCG
          CAAGCGTTTAACCGTCGCATATCCCGGACTAATTATATTACCACCCGCCCGCGTTCGACG
          CAAGCGTTTAACCGTCGCATCTCCCGGACCAATTATATTACCACCCGCCCGCGTTCGCCG

          TGAGATTGACCAGGGAGTACGTCCCGGTACGAATTCCGGGTTGTCGTTAATTTTGCGCAT
          CGAAATTGATCAGGGAGCGGATCCCGGTACGAACCCCGAGTAGTCGTTAGCTTTGCGGAT
          AGGGTCACAATATGGTCCCCGCGGTGGTGCGGATGCTGAACAATATACGACTATCTAGGT
          CAGATCTGATCCTAGTTTTCATAGGGGTGACATACCTGAACAGCATAGGATCCTGGAGAT
          TCGAAGCGGAGCTGGGTCTGGTAGTAACGACAAAGCCGGGCCGAATCCACATCGACAATC
          TCGAAGTGGAGCTGGGTCTGGCAGTAACGATAAAGCCGGGCTGAATCCCCATCGACAGTC
          CTGAAGCAGTGATGGCCCTTATAGTAACGATAATGCCGGGTTAAATCCACACCTGCAGTC
          CTGAAGCAGTGATGGTTCTTATAGTAACGATAATGCCGGGTTAAATCCACACCTGCAGTC

          AGTTGTAACTCGCCATATTCGCTCGGGCGGGCATGGACACTCTATCGTTCTGAAGGGCGG
          AGTTGCAACCCGTAAGGTTCGCTTAGATAGGCTCGGACACTCCCTTGTTTCGAAGGGCGG
          AATCCGCATTGTTAGCTGCGACTTCATCGAACAAGGTTGTACTTTGGTGACGAAGGACAT
          GATCGACATAGTCAACCTAGGGTCAAATTATCGAGGTGATTCCTCATTTCTGAAGGAGTG
          TGATTGTACGCATGACCAGAGGTTGGAGGTGGCCCATCCCAACCCTAAACTAATGGATTT
          TGATTGTACGCACGACCAGAGGTTGGGGGTGGCCCATCCCAGCCCTAAACCAATGGATTT
          CGATTTTACGCACGGCCAAAAGATAGACGTGGCTCTTTACTACCCCGGACAAAAGGGCTT
          CGATTTTACGCACGGCCAAAAGATAGACGTGGCTCTTTACTACCCCGGACAAAAGGGCCT

          CGTCGTGAACATGCCACGAGCTCCTTCACAGTGTTTGATA
          AGCCCTCAGCAAGCCACGGCCTGCTTCAGAGCGTTTGATA
          CGTCGGGTGCATGTACCGGCCGTACTAAAGCCGTTTGTCA
          CGTTGCGGGTGAAGTGCGGTCTTCTTAGAATCACCCGCCC
          GATTTTCGAAATGGCGAGTCTGAGGTGATGTTTCTCACCT
          GATTCTCGAAATGGCGAGTCTGAGGTGATGTCTCTCCCCT
          TTTATTCGCGATGGCGGAACTGAGATGATGCCTTTCCCCC
          TTTATTCGCGATGGCGGAACTGAGATGATGCCTTTCCCCC

