 8 1000
t1        TCTATGACCGTACGTGCACGGGATACCCGGGGAAAGACGAGTACGCAACAGGATTACACG
t2        TCCAGAGTATCGCACGAACGGCACAATTGCGGATACCCTCTTCGACGACCCAGGCGCACA
t3        TTATCAACTGAAAAATAGGCTAGTAACTGAAGCGCTCTCGATGTACGACGTGGGCCCCTG
t4        CCCTGACCAGTATCCTGAAACCGCAACAGTTGCATATCCTTTGCATAAATACAGCTCGCG
t5        CTATGCTCGGCACATTGCCGCATGGGTTAGCAGTGGCGTGAGTCGTAACACTGACCGATT
t6        TTACGCTGGGTAAATTGACGCACGTATCGGATGTAGTGTGAATCGTACCACTCCCTGATC
t7        ATTTTGTTAAATCATCCGGGTTGAGTTGGTACACAACCCGTGCTAAGGCCTAATCCAGCT
t8        GTTTTATTAAAGCGCTCGTGCAGAGCCATTACTCGACATGCGCTCTGGCCTTGACTATCC

          GGTCTATTATAACGTGCGTCAAGGCTAGATCCTTACCGTGAACTATCGCTGATCGGACAC
          GAGGGGTTTTTGCACTCCCTTCGGGTCGATAAGGCTCGCAGGGCCTTACTTACTAAAGCC
          GAGTGGCTCACGTGTCCGTCGCTGCATAATCCGGACTACGTAATTTTATTGGCCTAATCC
          GGATAGCGTATGACACTACTATGCTATGGGATGGATTTACTACCCTTGAAGGCTTGACCG
          GTATCACTAAGGCACCTCGCGGTGTGTAAGGTAGCTCGAAGATGTGTCAAGGCCCTTCAA
          GAGCCATAAAGATATTTTGCGCTGTGTAAGCTAGTCCAAAGCGCTGTAATTGCCCTGTGA
          CAAAATCTGTGACTTATGTTCCTGCGGCGTGTATTCGTGCAAGGACCGGTTGCTCTCCTC
          GCTACTCTGGGACATATCCTCTCATATGGGGGATCCGCGCTGGTCTCAAGCAACCTGTTC

          GATGGTCCAACAGGCAAGCCCGGGAGCGCACGATCCTAACTAAAGTTGCAGCCTGACGTT
          GATAACCTGAATGGCAACATGGAGAGGTCATGCAGCAAAATAAGGCTGGTACTGGAAACT
          ATCAACACGACGAGAAAGAGAGAGAATCCATGTACACGGATATAGCCATAAGTATACGTT
          TGCATGCATATTCGTGGGAAGACATGCTCAACCATTGGTTCCATGTTGCAAGTGGACACC
          GGGAGTCTGTCGAGCTTGATAGACCGCACATGGCTTAAAATAGAGCAGAGAACGGCTTTG
          TACAGACAGTCGGGCTCATAGGACACCAGACAGCTTAAAGCGATACCATGTATGGATGCG
          GGTGGTCGTGAAAATACCCCGTCCCGCGCCCTGACCCTGATAGTCGCACAAAGCTCAGCT
          GGTGGCCGTGTAGACAACCTGTACCGTTCGCAGGTCCACATAATCGTACGGGCCGCCGAC

          TGTGTCGAACCCGAATAATATAGACTCAAAACTTATTCACCGGCTTAGGGTGTGTCATTC
          ACTGTAAAGGCTATATGATCCATATTCATGACTCTTGGTTCCAAAATAGGGCTGTCTTTA
          ATCGACAAAGTAGCATGCGGTGGATCCGCGATTCTCGGTTCTGCTATAGACAGGCGACTT
          CTAGTCGACCACCACTGCCACGAATACATAGCTTTATGCCCGAGCATGGGAATGTAGTTG
          ATCGTTGGGGCAGTTTAACTTAGCTCTTAGGGGTTATGCACGGCTAGTGACATGGACTGC
          GTCTCCGAGGCAAATTATCTTGCTGATGAGGTGTATTGTTCAGTCAACAACCCGCGGCGC
          CCTGCAAGGCGCGGCTGTATGCTCCCGACGCCTGCTGGTTCAATTGAAACAAAACTTAGT
          CCAGCAGGGCACGGGCATGTTTTCTTAACGCCGCACGGTTGAGCCGATTCACTTATGAGA

          GCCGTCGGGGCGGATATGAAAGCTCCGCTTTCCCGACCAGGGCAAACACAGCAGAGAGGG
          TAACTCAAAGCGCCCATGATTGTCGACTCATTTTGACCGACATCAGAACATCAGTATCGT
          GTTCTTGAAGAATTAGACGATGTTGGACCCTTCTATCCGAAACTTACACTGAAGTTACTT
          GCGACTGGGGAGTAGGGAATTCGCGGGTTTGCCGTACCGAGGGCGCCACAGCAGTTCGTT
          GAGAATGAGGGGTGACGGTACTTTGAGCCGGTCAAAACCTTGCAGGCGCAATCATTCGTC
          GAAACTGGGGTGTGACGGCGCACCGGAACGACCAAAGCTCGGCAGACACGGCCGTCCGTC
          GACCCCGGGGTATTGTCTCTCGCTGGTATTATCCGGTCCGGATTGACACTATAACGTTGC
          GGGTTCTGCGCGATGTCGCACGTTAAATCCTTTCGATTAGCACCAACGCCCTATCCTTGC

          GCTGTCCGAGTATTGTCACGTCAGCCTGGAGTCGCGACGAGAAGTCAGTAATCCACACAA
          GCGCGCCGTGCACACGCTCCACATCCGGGATTTGCGGAGGCGCGACAGTTATCGTCGTGA
          GAACTATGCGGGTGTAGCTTCCAGCGACACCCTGGTGGGGTGGTTTGAGTGTCCCCGAGG
          ACGCCTTACTTGTGATTGCCATACCCAGTATTCTCGTAGGGATATCCCACCACACTGTAA
          GTACTAAACGTACGACCGCCATCATTGTCATTTACCAAGCCCTTTTGTCACTGGTTGAGG
          ACGCTCATTGTACTACTACCATCGTGGTCATTCGTCTCGATGCTGAGCTAGTAGGTGCAA
          GCTCTTCGTGAACTCTTTCCCTTGCTTAGCAACAATCGATGACCGGGCTCACCACTGACA
          GCACTCTATATTCCCCGCTTCACGGTCTCCCATAATAGAAGGCAGGGCTTACCACTGAGC

          ACCCTGTTCTCATTGTTTGTATGCTCGCATAATTTATCGATAAATAAAACCTACGCCACC
          GATTTACGGTGAATTCCTACTTGACGATGTATGTGTTTTTCAGATAGATCCGTTAGAAGT
          GGTTATTGGAGATGCTCCCACGTTAGCAGCGTCGATCTCACAGCTGGCGTGCGTTGGAAT
          TACCCGGGGAAATCTTCTACGATCAACCAGTCTGAGCTTTCAGGTGGATCTTAGTATGCC
          GTTTAGCGAAATCGTCCCATGATCATATCGGGGAAGTAGCTAAGACGTGCACATCCTACC
          GTTTAGCGATAGTGGGCCACGTGCGAACTGCCAGAGCGTTTACCACATACACAATCGGTA
          TCCCCGTCGGGAGTCACGCCTGTCCTCCGGGTCGTATATTCAGGTACAATTCAGCAAATG
          CTCGCGCAGGATCGGGTACCTCGCTAGCGGGTCCCGCGTTTAGGCGAAATCCTGCAAATA

          CGTGCACCTCCGGTATCCTTGGATTAGTGCTAGACCGTCAAGGATATCACCGGTTGCGTT
          AGAGCGCCCTACGCAACCCTGCTTCGGGGGCAACATATCGAGAATATCATCGCTCCTTGA
          CGAACTTAACCTACACGCGTGGTGTGGTAGTAGAGAGCTATGGATATCGGTGTTCACACT
          TGTGCGCTCCGATCACATGTGAATAAGGGATTGACCGTGATGGCTTCACCGGTTCATGGA
          TGTGCCGCTCTCCTGCTCAGACACAGGGGTTGGAAGAGCATGGTTGATAGCAGGCGTAAG
          TATACCCCTCTGCCACGCTGAAACCGGAGACGAATCGCTGTGGCTGCTAAGGGACGCAAG
          TACGCTTTACCCGAAGCTTATGACAGAAGGATACCGTCAGTGGCAAAGAAAGATTGAATA
          CACCCCACTTTCGAGCCCGGCGGCAGCTAGAGGCTGTCGTAGGCATGTAAAGACCGAACG

          GGTTAGCAAACACGCGAAACCGGTCCTCCGGGGACCTCACAGTAAGACAGCCGCAAGCTT
          CGATAGCGACAGATCGACTATCGCCTGTTGGGATCCTCATTGGTAAGTAACGCCAAGGCT
          AGTTAATAAAAGAATTATCCCGACATATCAGGAAGCACGTCATGATAGGATTGGCCTGCC
          CAACAACGAGTCGCTAGACCTACCCCTTTCTGCATCAAATTGATGGATTGGCCTTTAGTA
          CGACAAAGAACAAGCAAAATTTGCCCGCTGGGATACATGCAAACGGTGCGTCAAGTATTC
          CGACGTAGACCAAGTAAAAGTAGCGCGCCAGGGAACGTGCGAAGGGAGCTTCGGGTATCC
          GGCCCATGGAGAGGTACGTTCAGCACGTCGACTTTCACTGTTACAAAAGGCTGAGCCGAC
          TGTGAATCGAAAAATATACTCGACGCGCTGGCTAGTGTACTTCGGCTAGGCTGAGTCGTT

          CTGCCGATCTCACAGTATGCCCACGAGCGTCAGGGAATGATAGACCGCGGAGCAACCCTC
          ATTTCGATACTATGGCATGCCTATGAATAGACAGGAATGACGTACTGTGGCGAGAGCTTT
          CATTAGCACATTAAGCAGATCAATAAGCGCACGATGCGGCCGAATTTTGGAGTTTGTTAG
          CTCTCGGCCTACAAAGATGTACGGGTGTCTACATGGCCGTCGAGCCACGATGGGGCGTGA
          TTCACGACCCAGGGGCGTTCTCAGGGTCACCTCCGCCTGCCGTGCCTTGCCGGAGAGAGG
          CTTTCGACCCTGGAGTATACCCAGATTGGCAACCGCCCGCCGTGCTCTGCCGAAGAGATG
          GTTGTTGTCTTAGAGAGATAGAATAAAAGCCCCCCACCCAAGTCCCTCAGCGAAATATAA
          GCCGTTGTTCTGGAGGCGCAGACTGAGAATCGACCGCTGGTGAGAATTCGCGAAACGTTA

          GCCGTTTTCCTAACAGAAAGTTCAGCAGCTTTTGTAGGCATTTCCGGAGTTGAGGCGCTA
          ATTTATTTTCCGGGGGAGGGTACAGAAGTTAATCTGGGTTCTATGACATATCACGCGTCC
          AGTTATAATGTTGTATATGTCTAAACGGAGGTGGCGAGTGTCTCTGGCTCCACTGCATCA
          ACTCCAGTTCATCGGTTGGCCCCAGTGAGCATTGATGGACCCCTGGTCTCGGGAGGGTTA
          GTTCAACCTTTAGTGAAATGCTCACCCGGTGATTTGTGCGTTTCAAGCTCTGATGCGTCC
          GGTTAAATCCTTGAACGCGACTCGTTTAGTAATCTTTGGGCACTAGGCTCCAACGCGTCG
          GTAACGATAACTGTCATGTGTCCGCTGAGACGAATGGTAGCTCCAGGGCCAAAGGATGTG
          GCATTACTGTCCGCCATGTCCCCGCTGAGTAGGATGAAAATTCGGGGGTTACGTTGGATG

          CTAATAGTCAAATTACAATCGCAAATAATCTACGGCGCGGTGCGGGACGTGTTTAAACCA
          GTCACCTTGGAGAAAAGGTCGCTGCCGGAGCAGCGCGGGATCATGATCAATCTTAACACG
          CCAATACTGGGGTTTCAGCTGCAAATGGAGTATATTAAACAACAAGTCAACCATGCCCTA
          GCACCACCTGGACCGATACCCAAGCAAGAGTCCGATATGGAACGGGTTGTCTTCACGGTC
          CTATTGCCAGATCTGTCCGTGTCGTCGGAGAAATGTATGTAGCGAATAATCATTGGTTCA
          CCGATGCTGTAATCGTGTCCGCCGTCGAAGGATTGGGTGGTGATCGTAGTCCTTGTTACA
          ACCCTAAGTTTTGAAAACTTCACGATGCGGTGGAACAGGGTTTAGACTACGTCAGTACAG
          ACCTCGCAAGCCGAATAACTGGTTCTGCAGCGAGACAGGGTTCGAGTCATGCCACAATTG

          TATGGGGGTGTTGTCATAGACAATATACTATGGGCGCGGCGTTCGATCATCTGTGCGCCA
          TATGCGAGCGTGACAATACCCGGAGTGAGCTCGGAGCGTTGATGCATGACTAGAGTGGCA
          AGTGAGGTCGTGGAGTTGTTGGAAGCCGCGAACATAGTACGCTGGACTATTCTGCCGCCA
          CACCGGGTTATGGACGCGTGAGAGCCCTCGGAGACGACGACTTGAATTCTTCAAATTACG
          CTTGGACGGACGACTTTATGCGGGACTTCATCGAACCGACACCTGCCTACCCAGTTGCTC
          TATGAGGAGCCAAATGTCTGCGGGCCTCTCTCGAGCCGGCATTTATTCACCAGGATGACG
          TGGATAAAACTGATTGCACTCAACCTCTTGATCGTGCGGCGTAGAGTTTCTCCTCGTATG
          TGCGCGAACCCGACCCTATTTAGCCTCTTGCACCTGTATCGCGGAGTTTTTTGTTGGTTG

          CGGACGTGTTACCCGATCCCCCTTCGAGGTACCCCTTGTACTTTACCGACACCCCTCAGA
          ATCATGTGTCTCCCGATACCGTGAAGGGGCCCTTTTTGTGAATGACTATTAATTGTCAAT
          CTGGCGGATTCCTAAATCTTTGTTGCGTCCCAGTTTTGTAGATCACCAACCATAGATGCT
          GCAGGGCACTCTCCACCCTCTTTTAGAGTAAATAGCAGCATACCTGTGCTGATAAGCTAT
          GCGCAACGTTTTACAATTATCCTCAAGGAATCGTCCTCACGCATTCTCTTCCAGGACAAA
          GCATGGCGTCCGTCAATCCTCCCCAAAGACCCGCCTAACTAACCTCCCTCTTCGGATTGA
          CCGACATATTAATCATCAAGCTGCAAGATCGCGCGGTGCGCTCTATTACCCGTTGATAGC
          CTGATGGACTATCCTTCAATCTGTCAGTTTGCGCGTTGTGATTTACAGTTAGTGGATTAC

          TGCCACTACTCCTACCCTCGCCGCAACAATGACTCGCCCCTTTCCTAGTCGCTTTCCCAA
          AGTCGCAGCGATTGCTCCTGCTGTGCCATTCCGACGTTTTCCCCGTGTTCAAGTTTATAA
          GTCTACCACGACCGTCCCCGTGATATCATAGCTTGGTTCGCCCTGAACTCGGTTCTACTA
          CCCAATAGCAGCCATTTTTGCGTAGTTCGAATCTTACACTTGCCCATTTAGTCCTTGCTA
          AGTAAAGGTGGTTGATTTTAAGATAACGAAATTTCTCTCTTTAACTTTTTCCTTATGGTA
          AATAAGCGAGGCTAATGTTACGATAACCGAACTCTCTTCCCTTTATCTCTGCAATCGGTA
          CGCAAGTATTTGCATGACTGTAACACCCTTACTTCACATAGCCGAACCCTGCCATGAATA
          CCTACGCATCCGCGTGCCTGTGTCCCTGAACTTTCACAGAATAGTCGTCCATGAGGGTCA

          GCGGAGGAAAGTGCTACTAGTACCCTGCCCAAAAACGCATACATCTGGGAACCTCCGGCA
          GCAGGAGAAAGGGTCCCTTCTCTCTTATTACCCATAAAATATACTTTCTAACATCAGGTA
          CTCAAGGGCAGACGCGATATTCGCCTGCAGGACGTAGGGCAGTGTTGGGAACACCGTAAA
          GTCGAAGCTTAGGCAGTCTCTACTCTATTGTCCTGCAGTTCACCTAAGATACCTCAGCTA
          GAAGAGGAGCATTTCTCTTCTGCTCACCGGCCCGTGTGATAAGTACGTAGGCGTCGAGTG
          ACAAGGGAACACCTTTGCTCCACTCAATTGTCCCTGTGGTTGATTTTGTAGCCTCACACG
          GTTAAGGGCTCAGCGGTCTATATCCGGTAGGGGGTTAGCCTAAGCCGAATACGTTGGATC
          GTATAGGGAAAAGCCGTTAGCATACGATTGGGGAGCCGCCTAATTTGAGTCCATTCGTCA

          AAGTCGTCACCCTGGCCCTTCTACGGACAGACTTTGGGTT
          ACGGCGCCAGCGTAGTCTCATTCCGCGTAATCGCAACGTA
          TGAAAAAGAACTCGATTTCTCCTGGTATAGTTGTGGTGCG
          ATCGCGATAAGTAGAGACCACTACGTGTGTCTGCTAAGCG
          CAAATAGCGTCATAGATACGAACCAGATGCTATCGAAACT
          CGAATGGCGCCTTAAATACGACCGGAGTGCTGTCGAAACT
          TATGCACTTACCGTCTCCCGTCTAGGGCATCACCTGAGAC
          TCTCCGCTTACTGCATCTCTACCAAGGCATCAGCGGAGTC

