 8 1000
t1        AAACTATCCCTGCATGTTGTTTGTGGAAGCGGTCTCATCGTTCAACGACCGCCAGAGAGA
t2        AACTTATCCCCGTATGTCCGATATGAAGGCGGTCTCCCTTTCCGTCAATTGCCGGAGAGT
t3        GAGTCAACCTCGAGACTCCGACTATAGTGGGCTCACTAGGTTCTACAGTCGCCAACGGTT
t4        TTTTGAAACTTCGATGAACTCTTATGGTGAGCGCTCAAGGCTTACCCTTAGCTAGGACGC
t5        GCGGAAGTTTACAAAATCCTTTTCAATAAATTTCTCTCACACATACGGATTCGAAGGTGT
t6        CCGGCAGTTTCGTACATCCTTGTCGTCAAATTTCGCTCACACACGCGGATCCGAAGGTGT
t7        CCGTCCGTCCTAGACGCCATTGTCGTAGAACTTGATGTCGTGGTAAGAATGTGACCACGC
t8        CCATCCATCTTAGACGCCATCGTAGTAGAACCTAGTACCGTCGTAACAATGTGCTGGCGC

          GCTCAACTAGCAGGGAGTATAAGAGACACTGCATCGAGACGATGGTAGGTTGGACTATGC
          GCTCAAATTGCAGAGAACATAAGAGACACTGTGCCGCAACGATGGCCGAATGGGCTAGGC
          TCCTGAAGCTGCGGGACAGAAAGGGCTTCTAAGCAGGCGGGTCGGGTGCTTGGATATAAA
          ATGCAGACCAATGGAAGTGGCATGAGGTCTGGATTAACGAGATGTGAATACGGGCCTCGC
          CAACGGAGATAACGGGGCGATGTAGGTGTTCTGCAGGTTGGCAAAAGAACGTAACCTGGC
          CAATGAAGGTAACCGAGCGTTGCATGCGTACCGTAGGTGAGTAAGTGAACTTAATCTGGC
          AACTCGGGACCAACAAGATTTAGTGTAGCATAGTAAAAGACGAAGATAGGTAAGATAGGA
          AACTCGGGAGCAACCAGGTTTACTGTAACACAGTAAAAGACGAAGCTAAGTTAGATGAGA

          GACTCGTTCTAGCTTCCCACCGACATGGATCACAAGGTTCGACGCAGTTGTCCCTGAGCT
          AACTCTTTTCAGCTTTATCTGGTACTGGATCACGTCATCCGAAGCGACTCCCTTCGAGTC
          GGTCCTCACGAGCATCTACCATCACCGCGCCTCAATCTCAAAGGCGCGTGTTTACCCGAA
          GGGCTCCCCTACCACGATCGTTTAGATCGCTCTCCTCTATGGGGTGCATTCTAATAATCA
          AATGACTCATGGTGTTCCACATTGCCGAACTACTATGATCTGGGCTATACTTAGCTTTGC
          AATGACTCACGGTGGTCCACACTGCCGAATTTTCAAGATCCGGGATGTACTTAGTTGTAC
          CGTTACACAAAAGGTTTTAAGCTTTTGACCATACCCGCGCCGGTCCTCGACCGCTGTGCT
          CGTTACACATAGGGTTCTAAGCTTTTAACCATGTCCGCGCCAGTCCCGGACCGCTCTGCC

          ACTTCCTCACCTCGCCTTCTTTTTTTGAGCACAGCCACAAACAAATCTGCAGGCTCGCAT
          ACTCACGCACCTCGTCTACTTTGCTCTAGGACAACGGCTGACCGCCTCGTAGGCTTACAT
          ATCACCTCGCCATGACCTCAATTTTTCACACCGGGGACAAAGCTTTCTTCAGGTAGATCT
          GTTCGTCGGTTCTATCTAGTTTCTAATGTTACGGTGTTCGACGAACTAGAAGCCAAGCGT
          TCATGTGATCTTCCGCGTAGGTTGGCTGCGCGGCCGTCTGAACGTTTGTCGCGTCCCTAC
          TCTTCTAACCTACCCCTTGGATTGGCTGCGCGAAAACTTGAACGTTTGACGCGTCCCCAC
          ACGTGGTCGCGTAGTTGCCTTTTAGACATGCAAGAAGTTGTCAATCCAACAGGGGGCCAC
          ACGTGGTCGCGTAACTGCCCTATAGCCACGCAGGAAGTAGTCAATCCAACAAGGGGCCAC

          AATCCTCCGTGGTCTCGTCAGTAAATTAGCCTATCCCAAGGGGTGTATCGGCGGGGGGTT
          TCCTTTCGGCGAGCCTGTCAATTAATTAGGCTCCTCCCTACGATGTATCGACCGCGGCAT
          TTGTACCGGCAGTTCACTTTGTAGCACGTAGAATGACACGGAACGACCTAGCTATTGAAA
          TGTTAAAAGCACGTTTAGTCAGGTTGCAAGTTCCATATCCCGATATTCAGCCTACAAGCC
          TTCCCAAGGCAGACGGTCATGAATTTTAAATCGGGCCTCTACGGCCACCCATTATAAGTA
          TTCCTATGATAGCTCGCCATACATCTTAAAGCGGGCCTCTACGATCTCCTATTGTATGTA
          CAAGTCCTTTAGGTCAGTTTTCTGTACATAATGGTCGCTCATCTGTTGTGCCTACCGACT
          CAAGTCCCTTAGGTCAGTTTACTGTACATAATGGTCGCTCGCCTGCTGTGCCTACTGATT

          GATGCCTAAAAATTTGCTCTGACTCCAAGATAGAATTGCCAGGTAACAGCAACCTTAATT
          AATGTCAAAGAACTGGCTTCGACTCGGAAGGATACCCGCCCGAAGACGGCAATCATTTTA
          CCTCTTGAACTAAGTTCCCCGGACTAAATGTTCATCTCTCGGATGATATCACTCACATAC
          TGTGGCGGAGATATGCCTCAAGTCCCAAAGTGCGTCCAGTGAGTGTTACTGTCTATATCA
          CGGGCTCCCCGGTTGATTTTAATTTCGCCGTTCCCGTATTTGGCGTAACCCTACTAGTGC
          CGGGCCCCCCGCTTGATTTAAATTCAGCCGTGCCCGTACTTGGCGTAACCATACTTGTGC
          CGGTCTGACGCCTAGCCTTTCGACCGCCTCGGCGTCTCTTCAGCGTGGGACTACACGTAG
          CGGTCAGAAGCCTACCCTTTCGACCGAATCGGTGTCTCTCCAGCGTGGGACTGCACGTAG

          GATAGCTGAGACGGTGAGCGTGTTTATCCGTATAACCCTTCCTGATGGCTTAGACACATT
          GAAAGCCGGGCTCGCGAGCGTACTTATCAGTACACCTGTCCTAGATGGATCGGACATAAG
          ACCGACCACGTCCCTTCGAGGCCAAGCTTGGGCTTCGGCGGCTACCGAGAGGGAGGGTCC
          ATTCCACAGAATCCCGGACGCATTAGTTCGTTCATCAGTCGGAAGCTGCTGGGACAACTA
          TTATTTCGAAGTCCAATTGGATGTCGCTCGTAATCCGACTATGAACGTGTCTCGAGCACC
          TCATCTCGAAGTATAATCGGGTGTCGCTCGTGTTCCGGTGATGAATGCGTCTCGAGCAGC
          GTCTTACAAATCTTACTCCATGCTTCTTCGCGTAAACTACAAGCGCACGAGGAGACCAAC
          GTCATCCAAACCTTAACCCATCCTTCTTCGCATAAACTACAAATGCCCGCAGAGACCAAC

          CGGGATATAGGCTTCCAGGGTTACCAGCACATACGCACAGTCCAAGTGGTAAAGATGTAC
          CAGGATATAGGCTTACAGAATTATCAGTACCAACCTACAACTCTAGTGGTACAGATGTCC
          CAATACACGTATCGCCCGACAGATCTGTCCGCCGAAAGTGCACGCGCGAAGGATGGTCCC
          TCTGACATGTTCCCCGTGGTCTCCTCGACCTGTGCGGGAGGTTGAGTGCCGGAGCTATCC
          ACGGACGTCAAGCACAGATGCCCGCTGCCCCCAGAGACGTTTCTTGCCGCTATATGCCTT
          ACGGGCGGCGAGTGCCTATGCCTTCAGCCCCCAGCAACGTTTCTCGCAGCTATATACCTT
          TTTGGGCCAGCCAGCCTAGTCTGTAAGTCGCCAGTCCAACACTATCTCACGATAGTTTGA
          CTTCAGCCAGCCAGTCTAGTCTGTAAGTCGGCAGTCCGATATTATGGCACGACAGTTCGA

          TGGGACGAAAGCCCGCTCAACTACCGCCGTGTGTAGTTTGGTGCAGAAGGACTCTAATAC
          TGGGCTGGAAGCTACCCTGACTCCGGCGTCCTTTGGCCTGATGCAGGGGACTCCCCACCC
          GGCATTGGTGCACTCGCCCGTTTTTGGCAGCTATGGATCAACCAAGGGGGCCAATAATTT
          GGAGACGCAAGTCACTCTAATCAAGATAGGCCATAGCCCGGCGGGGCCTAGCTAGTAGCT
          GGAGCCGGTAGTTTTTCGTATTTCAACTCTTCTCGGCTCTGGTGTCGAAGTCCACAACTT
          AGGGCTGGCAGTTTTCCGTGCTTCAACCCCATTCGGTTCTGGTGTCGTAGTCTACAACTT
          TACGCATCTGATACTCATATCCTTGGCTTTCACCCCCCTAGGGGCCAGGAGGTAAAACGT
          TAAGCAGCTGACATTCATATCCTTGGCTCTAGCCCCCCTAGGGGCCAGGAGATGAAACGT

          GTATCTCTCACGGGGCCACTGAACCATCTGGTTGTCTGGTCTCGGGGGCTGGTAAGTTCT
          GCTCCTCCATCGGGGCCAATGATTTATAGCGTAGTATGGTCTCAGGAGTTGGTAAGCTTA
          GCATTCTGTCCGGGGTCGCTTAGCCATTGAAACGCCTGAGCATCAGACCGCGTACATTGA
          GTGTCGGGTCAGAAGCCACTACAGGTCTTTACTGCCTTGGCCCCTGTATGTGAGTATTAA
          ATTTCAGGCCTAATGCCGCGAAATTTGTGGGCTGAGTAGCCGCAAACGTAGACATATGAC
          AATTGAGGCCTAGTGTCGCGATATTCGTGGGTTGTATAGTCCCAAACATAGAAATATGAC
          AGTATTCGGCCAGCGCCGTTCAATCCATATAATGACCGAAGTAACAAGTGTGGGAATAAC
          AGTTTCCGGCCAGGGTCGTTAAGTCCATAAAATGACCCGAGTAACAAGTGTGGGACTAAC

          TTTCAGCTTGGATAATCACATTTCAAGGCGATGACCTGACAATATAAAGGAATGGAATAG
          ATTCTGTTCAGGAGGTGATATTTCGGGGCGGCGAATTGACAGTTTATAGACATCGAGTAG
          GGGGCCTATGGTAGACACTATCGCGGGCCGACGGTTAAGCGACATCCGATAGTCGGGCTG
          TTGAAATCCTGCTTTTATAGCCAAAGGGGGTTGTTGGTGCCGGTTAGGAACATTGGGACG
          TCCGTCAATTGACGATGAGGTAATAGGAGAATAAGGAAGAAGTTTCTGTAGATATGGGCA
          TTCACAAGATTACGGCAAGGTAATAGGAAGATCAGGTCGAAGTCCCTGGAGATACGGCAA
          CGTACTGATTGCACGGACTGCCCCAGTCGGTTCGTCCAGCCTAGCCTCGCCATGCGGACG
          CCTACTGACTGCACGGACTGTTCCAGATAGTCCGTCCGGGCTACCCCCCTCATGCGGAGG

          AGGAGCGCTACTAAAAGGTACACCGGAACGTGTGCGCCACTCAGTTATTAAGTTTTTAAG
          GGAAGCGGTGCTTCGAGGTACATAGGAACGTGCGTGCGTCGCAGCCATAAAGGTTTCAAA
          CCAGGGTGTAGTTTCAACCCGGAAGTGACTTTTGTTTGCCACCAAGATCAGGATCATATA
          GAAAGCTGTACTTTGAGGTGACTCGAAATGCCCGTTCAACACATCCCTTAAGGGAGTACT
          GACAGGACCAGGCAACGTCGCGACAACACGCCCGATGATTGCGCTCTTTTGGCAAAGGCG
          CACAGGACCAAGCAACGTCACGACAACACGCCAAATAATTGAGTACTTTTGGCAAGAGCG
          GTTGATGCCGTTAACCTCGAAGACGATGGACACGCCCACAGCAAGTCCTTGGCCTACCTT
          GCTGATGCCTTTAACCATCGAGACGATGGACGTACCCATGGTAGGGCCTTGGGCTAACTT

          GGGTAGAGAACTGTCACGGGGATGAAACATATTGACGGTCGACAGAATATTAACGCCAAC
          CGGAAGGGAACGTTGAAAGCGATGCAGTTCCTTCACAATCATTGGAATAAAGACGCCGGC
          GGTTAGGATAGGGGGCCTTAGGCGTTGAAGACAGAGTGCCAACGGGAAAATGGTATCGCC
          GGGCGGAATGCGTAGGGGAGGGTTCTTAGAACAGGGCGTTATCCGATTCTTGCCGCCGGT
          TCACCACAGGCATAGAACCGAGCGCTGCAGCGGGAAGTACAAAAGTGTGCTCCCGTCACG
          ACACAACGCGCACAGAACCGGGCGCTGCAGCGGAAAGTACAAAAGTGTGTTCCCGTCACG
          GGGCAAGATCCGAGATGCCGTGCGTTGTAAGACACGAGGAATTGATATATTTGTCTCACC
          GAGCCAGACCCGTGATGTCGTACGTTGCAAGACACGGGGAATAGACATATTTGTTTCATC

          TAGCTCTGCCAAATTGTTAACTACGCTGCTCATACCCATCTGCAATTTCTTGCTGCGGCG
          CAGCTCAATTGGAGCGCGTATTGAGCAGATCCTGTCTATCCGGAATATCTTGCTACGCCG
          TGTTCCAGGAAGTTAGGCGACTCCGCCGACGTCGTCTATGTGTGTACACTTTTTGGACTC
          AGCGTACGATAAAGAGGTGGCTGTGACGACAAGGCGGACCCCTGATTCCTCACTACAACA
          GACTTTACGTGGAGAAGGGCAATCACCACGATCCTCAACTCCGGTTAGCCAGTTGGACTA
          AACTTCCGGGGGAGAAGGACCATCATCAGGAGCCTCGACCCCGGTTGGGCATCAGCACTG
          TACTTTTGCAAAGGCACAGACAGTGTTAGGGACTTGGACGCGGCTGTCCGACAAGAACCG
          CGCCTCTGTAAGAGCATTGATAGTGTTAGGGATTTGGACGCGGGTGTCCGGCACGAACCG

          TCTGCTAACACCCAACAAGTTTCGCGAGACGCTTGGGAAAAACCCGACGCAATGTCGTCG
          TCCGCCAATAGTGCTCAAGTTTCGTGAGGCCCTCGCGAAAAATATCACGCAGTACCGTGG
          CCGGGTACTGCTACAATCCTGACATTGGGATCTCTTGGAGAATTTAGTGTGCAGTTCTGG
          GTCGATGGGGCCACATGGCGGACGATGAGAAAGCTAGAGGTGACTACCGGCCCATTCAGG
          CCGTGCGTCACGAGACCACTAACGCTTGGCGTGTACGAGGGTACGGACATGGCGTTCGAA
          CCGTCCGTCACGAGATCACCTACGCTTGGACCGTACGAGGGTGCGGTCGTGGTGTCCGAA
          CCGAACGGGTTTCATTTTCGACCGTTTGAACACCCGGTGGGAACGATTCGCTCGCTGAGA
          CCGAACGGGTTTTGTTTTCGACCGTTTGAAAACCCGGTGAGGACGATCCGCGCGCTGAGA

          AGAAGACCATATTAGTAACCCAAGAGAATTAGCAATGGGACCGTACTTTACCCGTTCTCG
          GGCTGATAAATCAAGTACCCCCAATGTCTCGGCACCGGGCCGGTGCTTCAACCATTCTAG
          GTGCGACTAGTTGGATCACAAGCAAGTTTTTCTGCTAGTTCTCGATACGACCGGTTTGCG
          CGGGAACAACTCCAATCTTGAGAACAAATAAATACCAGGCTCGGCTCCCACGAGGACCTG
          GAGAGCTCGCATTGACATCGGCTGCGATCGCACTTATACTCTGGACCACGTAAAATGACA
          GAGAGCTCGCATTGATATTGGCTGCGATAGCGATCCTACTTTGGCCCACGCAGAATGACA
          GTGGGGCATTAATCATTGAGATAGTGGCTTCTGATTACACTTGGCCTGCAATTGGGATGG
          GTGGGGCATTAATCACAGAGATAATGGCCTCTGATTACATTTTGTTTGCACCTGGAATGA

          GATACTAGAGGGCACCCCAAGTGCTGGGATCATACGCTGG
          GTAAGAAAAGGTCAAAACGAGTGTTGGTGGCTTATGCTGA
          ACCGATACCCTAGGGGTCAGCTGTTGCTGCGGTCCGCTCA
          GCGGAACAAGGGCGAACTGACTGTTGATGCTGCTAGTGGG
          TCAATTACACGGACCACTAGCCGCTGATACTCCATGCCCA
          TCAATTCCTCGGACCACTAGTCACTGCAACTCCACCGCCA
          GTCCGAAGTATGTGCAAATATCGTCATACCTCCCCTTTAG
          TTCCGCAGTATGCGCAATTACCGTCATACCGTCTCCTTAG

