 8 1000
t1        CGCAGGAGCACTTCCGACGGTGAATCAACGTTATGCCAGCTTCCGGCTGGCTCCACCAAG
t2        TCCAGCAGCACTTCCGACGGTGCATTGACGTTATGCTAGCTTCCGGCTGGCTCAACCAAG
t3        TCAAACAGCTCCACAGCCCGTGAATAAACGTTATGCCAGACGCAGGATTGCTTCTTCAAG
t4        CTCACCATTAGCACAGTCCCAGATTGAGTGTCGTGCAAACAGAGGCTCTATTCTACAAAG
t5        CTTACAGGTTGCTGTGGGAGATATTGTGAGTAGCATCAACAGCTAGTTCGTTCCATGGAC
t6        GTTTCTCATCGTACAGAACCCGACGAACGGCCATGTTGAAAACGCGCTGATATTAGGCGT
t7        ACGTTCATTTATATTTATGAGGACTAATTGCACCATCCCAAGTAGGTCACTCTCCCGGGC
t8        TACTCTTGCGGTGCCCCAGCTGACGCTGTACTTCATTGAAACAGGATTCAGCTAGTGGAT

          CGACCATAGTAGATAATTCGAGGCACTAAACTATATTAAGCTCATACATAATTCCGCCTA
          CACTCATAATGGACAACTTAGGGTACTAAATTATATGAAGCTCATTCATAATTCCCCCTA
          CGTTAAAGGCTTACAATCTGGATTAATTGCTTATACGAAGCTTATTCGAGGTTTCTTTGA
          TGCGAGTAGGTCGCAGTAAGGCATGAAGAGCTATAAGCAACCTACGCCTGGATAAGACGA
          CTCGCATGGCTCACATAATGATATGGTTTACTTAAAGCAATGGACGCACGGCCGTGCTGA
          CGGTCCCCTGTTACTCCATAGTACGGCAGCATGCGCGAGGCTAAAGCATGCACAGGTTGG
          TGTTTATAACCCACCGTCGAGCACCGCCGGGTGTAGGCGCGACACGTTTAAAAGCGCTCG
          ATACGGAAGAAAACCAAACCGGCAGTCTCTAGACCAAGGCTGGCCGGAAAGTCCTGCCGA

          GAGCTTTACGGGGGAGGATTTCTGCGGCCTTCGGAGGCGACCAGCTTTGACGTACCTGAG
          AAGCTTTACGGGGGAGGTTTTTTGGGGCCTTCGGAGGCGGCTAGCTTCGACGTACCTGAA
          AAGTCTCTTGGGGGAGATCTTCCGCTCCTTTCGGGGGCGACTAGATACGGTGCTCCCCTG
          TATTTATTCGTAGCGATCCTCCTGCATGTTCTAAAGGTTGCTATGCTCTAAGCACCCGTG
          CCTCTTATCGAAATGTGTTTTTTATGTAAACTATAGACGACTCCCACCTCAATCTTTGCG
          CGACCTCGCAAAGCACGCTCCGTGTGAGTTGCGCGGACGGGCCTCCCTAAAGCTTCCCAG
          ATAGCCCGCGATGCAAACCTCCCGCTCGTGTGAAGCCAAGCTCTCCCCGCAGCTCCGGCA
          TCTTCAGACTTAGTCTAAAATCAAAGCTAGCTCGTGACTCCATTTACCGACCCATTGAGG

          GTCTTTACCCTCGATATCTTAGTAACGGGCATCGAATCCATTGCGCTCTATGTCAGTGAT
          GTCCGTATCTTCGGTACCTTCGTAGCGGGCACCGCATCCACCGCTCGCTACGTAAGACAT
          GGCTCCATTTTTATTTGCCCCGTGCCGGGCTTCATATCCGCAGGCCTCTACGCCAGTGAT
          GCCTGTAATATTGATACTCTTGCGCCACCTAACATTACAACTTCTTAGAATATGTGCCCC
          CACCAGTCCACAGCCTCTTCATGATTTTAAAACATCTCGACTGACATCAACCTTGGAGGT
          GTTCGTTCTACTCGACCTCCTGTGGATACCCTTTTATCGAGTGCATCAAGAGTGGAACTC
          AGCAGTGCGGACCAACCTACTACATTGTCTCACATAACGACTGCCGAGAACGTCAGGGCT
          TACCAAACCGGAATCCTCGGCGTACTTTATTCTATTCCCAATCCTTAAGAGATTCACGGC

          TTCTTCACAACAGCGCCCGTTACTCTCATCTTGCAGCGCGTTGTAGACCAGAGGAAAATT
          TTCCTCACAACGGCGCCTGTCACTTTCAAGTTGCAGCGTGCCGTAGAACAGGGGGGAAAC
          CCGTCTTTACGCGCCGTCTTGATCCATGACTCGCAACGTGTCGCAAGCCGGAGTTGAATC
          TCGCTTGCTCGAGCCTGTGCTGGTCCCAATATAAGCTATATAATACGCCATGGACGGAGT
          CTACGTACATGCGTAGAGCGGCGTATCAGCATAATGCGTTTCGCGCGTAACAGTTAAACT
          TCGTGTACCCGTTCCTGTTTGATCAGCACCCTGACATATACCAGACCCTAGTGTCCGACT
          TCACTGGTATGATCTGCCTTGAGTTTAGATCCCACGTAATCTGAAACCCGGAAGAGCCTG
          CTGTTGTCGTAAACCAATTTACATACAGAAGAGAACCACGCTGCCAAATGGTACCCACTT

          GAGAATCTATACCACTGGGCGAGCTACACATGACACTACCCGTCCTATTCGTAAGATATT
          GGGAATCTTTAACACTGAGTGGACAACACCTGATACCACCCGCCCTAGTCGAAAGATACA
          AGAAAACATTAACGCTGCGTGAGCAATGTATGATACGGTATGTCCCGGCCTTGAGTCATA
          AAGAACCCCTCAAATTGCGAGAACTGCGTAGGGAGCCGTCTTCTCGGGCCTAAAAACAGG
          GAGTGCTCGCCATGCGATGTACCTAGTATGTGACACCATTGGTCATCGCTCGGTATCAAG
          GAGTATCAACAATACTTTGCTATACGCATAAGTATTCGTTGAACCTGGTCTCAGACCAAG
          CACGTTTGGTTGTATTGTCCGAGTGACTTCTGAAGCGCTACGCTTTGATTTGAATGGCTA
          AAAAACTGTTCATATTAGATCAGAAGCGATGGCACCACGTCTCTCTACGGAATATGACCG

          AAACCCGTTCAACGACTGGAACGGACTCTCTGCACGGTGGCACCCTAAAGGGCGTGTGTG
          AGTCCACTCCATCTACTCATACGGAGTACGAGCACGCAGGTTCCTCGAAGGGCGTATGTG
          ATATATTTTTATCTACTGGTTCAGAATCCGTACAGGGCGTCTCACTAGAAGGCCCATGGG
          CATTTTCCCTGTTCGCTGGCACCGAGCGGGTACGCATCATGCCCCTAGGGGACGAACCGA
          GTACCCTTATGTCTACGGTCACCTAGTGGGCGGCCAATGTCATTTCATCGAGTATACAGG
          ACACCACCCCGTCACACAGCCTTGATCAACTGCGCTTCCTTATAGTAGCGGAGGCTAACG
          GTACCCGTAAATTGATACGTTCTAGGTAGGAGCATACCCTCTTTTTAAGAGAACGCTCGA
          GTAACAATTTACTTTTGAGGTTCAATCGATGACTAAAACACACTTTAAGGAAGACGCCAG

          ATCCCTTCGAAATTCTTGTAGGCCGTTGAGCTACAGTAATAGAACAGCACCAAACACTCG
          ATCCCTTCTAATTCCTCATAGGCCGTTAAACTACAGTAGTCGAGCTGCATCAAACATTCG
          ATCCCTCTTACTTCCCCGCTGGGTACTGACGCACTGTAATTAAACAGCGTCAAACCCTCA
          ACCCTCATTAATACATTATCGGCGCCCGGTATGTCCCAGATCGGCATGGTATTATGTTCG
          AGTTTTTCTCGGTACTCCCGGACGGTTGACTTACAGTAGTTAGTTCGACCTTCATAGTGA
          ACCAGTTCTGGCAGTCCAGCTATCGTCGACCCTTCAAGAGTGAACGGAATGTCGCATCAT
          AATGCTTCCAACTTCATCCGAATGGCACATCTTCTGTATTCAGTCGGAGCGCCACGTTGT
          TAGATTTACAAGTTTTACTAAAAGACCAAGCCTCCAAATGTTAGTGGGGCGCCGCGTCGT

          GAGAGAGGGCCACAACCCGTAGAGCGCCGCATCTTACCGGCAGTTAACACATTAAATAAG
          GAGAGAAGGCCACAACCCGTAGAACGTGGCGTCTCACCGGGACTTAACGCATTAGATAAG
          GAGAGGGGACTGAAAACAACAGAAGGTCGCGTCTTACCGAGGATCTACGCGTTCAACCGG
          CCGCAGTGGATATTACTGACTTTTCATCACGTTGCGTCAAGAGTCAACGTTTCCAAGATG
          GTGTGGTCGTTGCCCGCGATTGCTCTCCACGGTCCGCCAAGAAATAGTCTATGCGAGATG
          AAGCAACAGGAGCGCGTGATTAGTCGCCGTTTGCTGAAGAGCGTTAATTGTCACTACATA
          GTGGATCTGTTGCTATCGCCCGGTCCCCTCAGATCTTTGAGAATCAAACCATTTAACGTG
          TAGTATCACCATAGTTCGATTGGCGGATGGATGGTATTTGGAAATCTAATAGACAGTAAA

          GTTTTCTGGGTACAACTGCCCCCCTTTCAGCCTCCTCAGACCTTAGCGGTCCCAGGTAAC
          GTTTTTTGGGTCCAGCTGTCGCCCTTTCCGCGTCCTCTGATATTGGCGGCCCCAGGCAAT
          AACCCACCGGAACCAGTACCCCCTCTTCCAAATCATCCGCCCTTAGCAGCCCCAGGACAT
          CCCCTACAGTTGGGCGAGTTTTTTAACCCACAATAACGGCCTTTGACGGTCCAGGTCCAT
          CGTCCATCGGCTTGATTGCCGGTTAAGAGAGGTCAGCGGCGTCCGCCGGTTCCAGGTGAT
          ACTCCAGAGGCGTCCCCACGAGATCATCTAAGCAGACACTCCGCGGTGCTATCAGCCCAA
          GCTCTTTCGGGTAAACCGGCCTATGCCACTAATTGTTTGTTTGCGGTGGTTCTCGTCCAC
          AGCACACCAGCAGGATTAACCCATGACGTGATGAGTGGCCACAAAAGACTGCTCTTCTGC

          AAAAACAACAGACAGGTTATTGATTGACCGTCATCCTTCCTCGGTATATATGCGGGATTC
          ACAATCAACAGCCAGGCAATTGATTGACTGCCATCCATCCCCGGTATATATGGGGGCTTC
          ATACGAGAGAGCCTAGAGGTTAACTTCTCGCCACCTTTCCCTGAAATATACTGGGTCCAT
          CTTAAGAAAAGACTGTTTGCTCTTCGGCCGTGCTGCTTCCGAAGGATAGCTTAGTGCAAC
          ACCACGTATCACACGATCTTTATTAGTCCGTCCACATAACGTGAGAAACAATATCCCAAC
          GAGTCGAAGGAAATAGGCAAGTATCGTTCGTACCGTTCTTATGGCGTTTATAGGCTGGTA
          GCGGAACATGACTCGAGTGTGTTCCGCATGTTCCCCTTTCTTGAAATGATGTAGCACAAA
          GACCGGATTGCCGCCGGGAAGCCTTGTTTGCACTACCTTTATCAGATACTGTAGTACGAC

          GACGACAACCGGGTATGGGAACGGAATGCTTGCTATCGACTACACAACAGGCCCCACCAT
          GACGACCATTGAGTATGGGAACGGAAATCTTGATATCGACTGCTCAACAAACCCCACCAC
          GGCTACGATCGGGTCTCGGAACAGAAACCCTGATGCCAGCCGTAACACAGACCCGCACTG
          GAATCCGGTTGGAAATCGATAACAAGACGTCGACCCTGGCCATTTCACAGATACTGTATG
          GACTATACCTCGTAATTGCCCTTGCGAGTTTATACATGGTCGTCTCGCCGAATTCATCTA
          GGTTATGGGCCAAAGCACACAGCAAAAATTTATCTTTAGTTATTTTCTGGGCCTCCTCCA
          CAGAGTGGGTGTAAACCGAAAGGCAAGTTGCACATTTGAAGATGACCCTATCCCCGACTA
          GGGGGTGGTCTCAAGTATGTATTGTAGATGAGCATCTCCTTTAATTCCGCCTCGTATCTC

          CCATTTATTCCCACACTGTTCGTTTCAGCCGAGAAATAACTAACCAAATTTCCGAAGGCG
          CCATTCAATCCCAGATTGTCCGTTTCAGACGATAAATATCTAACCGGAGTTCCGGAGCCG
          GTTTCCGGCCCTGGACGTCCTGTTTTCGACAAGTAATAACCAGCCAGGTCTCTAAGCTCG
          GTCTTTGCTGCCAGGGGACCCGTTCTGAGCGGAATAGATTAAGGACGATACACAACGCCC
          GAACCCAGTGTCCGATAACTCATTCTTACCGAGATAGACTTAGGTCAAATTCTAATGATA
          GCGTTCAGTACAGGGCGCTCTAATGTTGTGAAGCGTGGATTGGATGAACTCCCGTTATGT
          GTACCCGAAATGGTTTAAAGCACGCAGGCAGAGACAGAACAGGAACGACTCACATTGATC
          GAGCTCAGTTAGGGGTGGCTCGACGTGGTCAATATAGGTCCGGACGAGACTTCTATCGCA

          TCGGTTCGAAAATATTGAATATTATCGCATGTGATAAGATGTCCAGATTCACTGGTAATC
          CCGCTTTAACAATATTGAATGTTATCGTATATGATTAAATATTCGGGCTCACTGGTGAGC
          CTTCGTAGAAGGTAATGGTTCCTATTATATTTAATTAGGTGTCCGTGTGCACTGATCCAA
          CTCTGCGACGAAAATCCTCCGTTACGGCACTTGACTATGCAGATGCGTCAATTGAATGAT
          GAATCGGCAAACTGTTCATTGCTCCGTCACTCGATCATATCTTTAGGTCAACTGACCCGC
          ACATGAGGAACGCGTTCAGTGACACAAGTACTGCCTCAACGAGACGGTCAACCGGGCCTT
          ACATCTGAATTGACTATAACAGCATGGAAGTCGATAATTCGTATTCGTCGATTGGCAGGT
          TAAACAAATGTTGCTTTCATGCAGAGAAGTAAGATGATGTAACTCAGCCTATTTGACAGC

          ATCCTATTGGCCCAGCACGCTGCGTTGTGTTATGTTGCACGGGTCCGCTCTATTCTTCGA
          CTCCTATTGGCCCGGCACGCTGCATAATGCAATGCTGCCCGGGTTCGCATCATTATTCAA
          ACCTTCCGTGGTAAGGTCGTTCCGTTGTGCATCATCCCGCAGGCTCGCCAAGTCCGTCAA
          CTCTCACCGACCAATCTTGGTGAGTCGTACATTAGTGCTAAGATTAGGTCCCATATTCAA
          GCCCCGCCTATCATGCCATCAATCATGTGTCAGACCACCGACGCAAGGTATGTTACTTTC
          GACTCTCTAGCATGGGTTGCCGGGAAGTAGGGCTAGAATTGGGCCACAGCCTCCATAATA
          GCCCGAACAATTCTGTCCGATAATACGTGCAATTTCTTCAACCCAGGAACTCATTAGTGT
          GGGCTGTCCGCTCTATGCTCCGCTGGGCATGCCAATTCCCGAATCTATCTCTGATCGCTC

          CACCGTAGCCAAAACAAGTCACCGGGGACGAGTACCCAACTGCATGTGATGAGTGCTATC
          CTCCGTGATTAAAACGCGTCATCGGGGATAAATACTCCACTATACACGAGGGGTGCTATA
          TACTACAGCCAAATCCCGCCATGGGGGGGTAATGCAACACAGTTTACGCCCAGTGTGATA
          CTTCGGAGCGGGGACATATAATAGGAGAGCAAAGTTGCGTTACCTAACCTCAACGTGATG
          GAATGAAGCCGAACTACGTAGTAGAGGAATTCAGCTTGCCTGTTCAGAGCTCAGGTGATA
          TCCTCTGGCCGGGGCGCGTGACCGACGAGTGATTCATCAAGGCCTATGATCGATGCGACA
          CACCTTTGTCGGATCGTGTGCTAGGAGAGCTTTCCTGAAATCCACTGAGTTGTTAATGCA
          CATTGCGGTTAAGCTGTACGTTTTACGAGACGTGGGATACCTCTCGAATTCATTGTGGAA

          CTATAAGGGTGGAGATCCGCCCTCCGACCTCGAGCGATTC
          TTATAAGGCTACGGATCTGCCCTCTGATCTCGAGCAACTA
          ATTCCTGGCAACGAATTCGCCCCTAGCCATCGAGCCATTC
          TCCACGGTCTAGTTCCCCACGCTCTGTCTGAGAACGAGTC
          TGCCTGGGTTGCAGACCAATCAATTGATTTCGGGCAATTT
          CTCCTGGCTGACATGTTCTCCTCAGGTCCGGGGCTAGCCC
          ATTACGGTCCTTGAATCTCTCTAAAGCGCTCGCTTGATCT
          CATAGGACACGTGGAATGTCCCCTTGCGTTCGACAAATTT

