 8 1000
t1        GCCTAAGAATGGCTCTCCGGTCCAAAAAGTCATAACAGACTGGCTTCCCGAAAGCGTTAT
t2        GCCTTAAGAAAGCCCTCCGGTCCAAAGAGTCGTAGCAGATTGGCTTTCCGAAAGTATCAC
t3        GCTCGACAGACGTCTTCCGATCTGAGGATCCCTTACGAATTAATCCTTCGGAGTTTGTGC
t4        CTCTGTCGGGAGCCCACAATAACCCATATGCGTAGTTAGTTGATCTTACGAAGATGATTC
t5        TCTCAGGAAGGGTCTTTTGGTACGGAAGCCAAAGACCAGAGCACTCCACGGTGGGGACAC
t6        TCTCAGGTGGACCCCAGTAATACGAAGGACAACACCGAGATCTCCTCACGAAGCAGGTGT
t7        ATTCTCAGTGAATGTCCAAGTTTAAATCAAAGGCGCCCATTCGCGCGAGGACATCCCATG
t8        GCCCGCAACCTGTTGTACTGGCTGTATAGTAGGCGCCTCCTCAGTTCGAAAGGGTAGCAT

          TTTTGTCATGACTCATTATCCAGGTAAGAGGCGGCGTTATCAACGCAGCACTCGAAGTTG
          CTTTGTTATGACTCATTACTCAGGTTAGAGGTGGTGCCATCAGCGCAGCATTCGAAGTTG
          TCGGGGCACAGACTGTCGGCCAGATCAAAGTCAGCGACGTAAGTGTAATATCCGAGGTCG
          ATCACTCGCCCACCGTTCCCCCAACCAGGGGTCTCATTACTTATGCAGTCGCTTTGCTCA
          AAATCCTCCTTTTGACTATGCAGGGGAGGCGCCCGCTAACTAGAGGATCACCTGGATTAA
          AATTGCTACGCGTTCTACTTGAGGAAGCATGCCGAATTAAAGGTATTGCCTCTTGAGTCC
          CTAATCAGTCGCCGTTCTTGCCGCTAATAGGTCGGGCCGCGAGAGGATTCCCGGTCGCAG
          TTAACCTGTTCCTAAAGTTGCATCCCGTAGAACCCGTCGCAACAAAAGTTGTAGTGGCGG

          GATTTAGGCCGCTATCCCGGCTGTAACCTTCAAAGTCGGAACGGGATCGGACGCCCTCGT
          TATTTAGGCTGGTACCCAGGCTGTAACCTTCAAAGTCGGGACGGGGTCGGACGTCCTCGT
          GGTCGAGGTCAATTTCTAGCTTGACGCTTATGGTGTTGGGCTGAGGCGAGTTGACCCGGA
          TGGGTGTATCATCATAACCGCAATTGTCTTCCCTGCCAGGCCGGACCTGGAAGGCCTGAC
          GTGCAATGGTAGTTCACCGGTATTAGGTAACTTAGTCAGGTCGGGGCGCGTCAGGCTTAA
          GAACGGCGTTGGCCTGCTGGCCATAGAGTAGTCCATCGGGCTCGAGCGCGGCGGCACGAG
          CATCGAAGTCGTATCGTTGCGCGCGGGTCGTGCCACCGGCGTGCTGCTTACTGGTGTGTG
          GGATAAAGATATATCACCGAGCATGAATCACGACGCCAGAGAGCACCGTCTATACGCGGG

          CGTTCTAGCGCTAGCGAGTGTGTGCATATGACAGCCTGAATTTTGATTCAACCGTACGCT
          TGCTATAGCGCTAGTTAACGTGTGCACGTAACGCCCTGAATTTTGATTTAACCGGAGGCC
          TTTTATGGCCCTGATGAGCATAAATAAGCCAGACTCTGAGAACCAACACGACTAAACAAC
          CGGTAACTTTCGGGTAAACCCCAACCTAAAACGCTTCGGACTTTCGACGGGCAGCAGACC
          CGGGATTGAACGGGAGAGTTCCCGTACTTCGTGCTCGAAAGATTTTCTGGCCAGCAATTG
          AGAAACCTTACCAGGGAAACCGGACGACCACTTTCCGGAGGACTTGCACATTAAGGGATT
          TCGTATGACATTAAGTGATTCAGCGATTTGACCCCCTTTAACTTCACGGACCAGGAACTC
          CGGTACAATACTACGAGGCATACCAATACAGATTCCCGAATTTCGATTGAGTAGGGGGTT

          AGTTTCATGATGACACAGCGGAAGTCATGCGACTTTTATAGGTTAGAGCTTTACCTTTAG
          AGTTTCATCATGACATAGTGGAGGCCATGCATTATTCATAAACTGGAGCTTTACCTCTAG
          GGTCTCAGGCCAGCACCAGGCGGACTATACATCGCTTGCACCCCAGGACTAAACTCCTTG
          GGTACCATCCTGGCATCTTGGCTAGAACTTGATGCGCGAGGCCCTTAACTGACCTTCTGG
          AGTCTTACGACGTCCTAGCAGCAGCTATCGCATATACTCTGGTCCGGAATGATTAACCAA
          ATCTCTCCACAGTCGCCGGCGCATAAACTGGGTATACGCTTCTGTGGGAAGAGACTCTCG
          GGTCCTCCGGTCCCATAGTGGGGACTGCCTGTCGTTCTTATCGACGGAGCGGCCCTTCAC
          GGGCCATAGGAATGACTGCTAGGACCACGGGTCCTCTTCGGATACACACGAGTTACTTAG

          CAGTGGGGTGCGATCTAACACCATTCCGACCGTAGCAATCGATCGCAATAGGGAGCTACG
          CAGAGGGGTGCGATCTAGCGCATCTACGACCGTAGCAGTCGATCGTAATAGGGAATTGTG
          CAATGTAGTGATCCCAAATCCCAGTAGGGTTGCGGCACCCGCCTGTTCTAGGGCAGGCCA
          AGCTTTTACTGGTTACGATTTCGTTCCGGCAGGCGCATCGAGAACTTCAAAGAGAATCCC
          ACTCTCTGTTAGCCTACCCTTGATAAATGCAGGGCTAATACATATTTTGGACGCGAGCCG
          ACACGCCGAAGCCGCGAGACTAACTATGGTTGCAGTCATAGTTATCGTGAGAGCTGGTTA
          GGAACTTTCAGATGCCACGCGGGTCGAAACGCTTGATGATGCAGATATTTGGTGGCTCAT
          AGAGGCTCCTCCCGCGACGCCGGTAAAGGTACCAATACTGACAAATAATCTGAGATGTGT

          AATTAGGGAAAGACTGGTATGTCCTGCCTACAGGTGGTAACGGTAGATATACATAACCTG
          AATTACGGACAGATTGCTACGCCCTCCCATGAATTGGTGACGGTAGATATACATATCCTG
          ATAGCGGTACGAAATGCTACCTCTTACCTAATTGCGGATATGAGAGGCAGTCATATCCTG
          TCGTCACAAAGATTAGGCACGCTCCCTTTAAGAACGATTAGAGGCATTTATAGTGCTGTG
          TAATTAACGCGAATCTATGTGTTCCACACAGGTGCGATCTAGGAGGCCCCGCTCCTTTTC
          TTGACCGGAAGGGTATACACACTGTACACGGCCGCGCCGATGGCGGGTACAAATCAGCTG
          TAATCTTTTAAAAAATGTTCATCTTATGCCATTTCTCTGGCTCTTGCTGTACCTGCGAAC
          CGATCCTATCGAGCGAGCATATCACAACGAGTGCTTCGGGAGGTTGGCGTACCTGTACCA

          GCGCGGACTCATTATGACCATTCATCTGTCTTATGGCGATTTCCGACTTAGCATTTTTTG
          ATGAGGATTCCTGATGACCACTCATCCGTTTTATAGCAATTTCCGACCTAACATTTTTCG
          ACCGAAATTCGTGTCAGGCTTTCGCTTATTCAAGAATAACATGCATTCCGTCACAGTCCG
          GTCAGGAGTTAAACCCGTAACACGTCCACGTACACGTAGCCTTCTGCACGATGCAATTTA
          GCAAGGAACGTGATCGGTGATTAGTTGGGGCTAATGCGATGCCTACTAAAATGTGATCTA
          GCAAGGAATCTGACTGGCAGTCTAATAACGTTCGCGCGGTATCTAGAGGGATATAGTTTC
          GCAAATGTTTGTACCATCCACCAGCTCGCACACTTACGTGTATCACACCGGCGCACCCTC
          ACCAGCGTTCAGACCAGTTGCCAAATCGCTCAAATCATCGTATAGATCCTGCGTTTTGTA

          GTTGGGAAATCTACGCGAAAGAGGAATAGGTGGCGAGCCTTCTGGTACCACCGGCGGGTG
          GTCAGGAAGTTTTTACGGAAGAGGATTAGGTGGCAAGACTTCTGGTATCGTCGGCGAGTG
          GCCAGGGGACACCACCTGCGAGGGACTAGATGGAGCTGTCTCTGACCGCATCCGAAGGCT
          GTTTGGTGCCTGTGTCCGAGTCATAATTACCGCCATAATCAACAGGGGTGCATGAAATTC
          GCTCAGCTTTGTATTTTTCGACTCAGCAACCGCTGCGGCCCAAAGTCGTACTGGGGAGCT
          GTTGGGGGTTTTATTTTAGGGTGCACCGGCCTTCGTGGAGCAGAGCTTCCCCGGCGGTCA
          TGTTGGGTCTTGTTCGCGCTGAACTGTGTAAACCCCAGCTCGCGTTCGCATGCAATTTGT
          ATTGTAGATGTGTGCACGGAGCACACAGAGCGAGTAGGTTTACGATCGCACATGTGGCCT

          AGCGCGGGATGGGTGGCAGATAGATTATCCCGAAACTTTCCAGCTGCCTACGCCCTAATG
          AACGGGGGTTGAATACCGGATAGATAACCCGCAGACACTCTGGCTCTTTCTGCCCTAATA
          TGTGGGGCACAAGCACTAAGTAGTAAACTCCCGCCCGCCGAAGTCGCCTACTCCCTAACT
          TACGGTACATTAGCGGTGGGTCCAGGTCCGCTAGCCGTTTAAGGTGCTTCTCTCTAGGCT
          AGGAGGGTTCGAAATTAGGGTAGTTTTCTGTCTGTAGCAGCGCCGGCGTGTTTTGTGACG
          CTAGGGGACCTAACCTCGGGACGTGCGCTTCCCGAAGCTACAAAGATCCGCCTTTGGCAC
          ACGGAGCATCCATACCCGGGATGGCTGATATTGAATCCTCGCGCAATCTAGGTGTAGATC
          GAGGGGGCTCTATCCAAACGTATGTCTTTATCTGGTGATAGTCCCGATCATCTGACGACC

          GGTTTCCTGCCCGTCCCTAGGGACTTTTGCCTGGATGGGACATCGTGATCTTTGCGCTGT
          TGTCTCCCGCCCGTTTTTAGTGACTTTTGTCTGGATAGGACGTGGTGATCTTTGCGCTGC
          TATGTTTCAAACACAGTTAGTGACAATTGACTCGGCAAGTTGAAGTGATTCCCCCAGTGG
          CATACAACGCCCCCTCGCTTTACCGTATACAGGTATCGTTAGATACGATACCACGGGTTG
          CGTACCAATCCTCTATCTACAAATCTATACTTACTTAAGCGGAGTTAAGGTTTCGGCTGG
          TGCTCCCAATTCCTTTGCGGTATTAACCGCTACCTCAAGCTACTATGCCTTCATGACCAG
          ATTGCACCAACTATGTCTGAGCGAGCACACTACAATTCACCGTTTAGAGTCATGGGGTGG
          GCGACCACGGTAACGTGCGACTGGGTACGTTTCAGCCGGATGAGGCAATTTGTAGGACGA

          TATCGACTGCATTGGGATCGACTGAAGAAGTCCCCGACTTCCGGCCGTCAAAATTCAATG
          CTTCGACTATATAGGGATCAATTGAAAAAGTCCATGTCGACTGGCCGTTAAAATTCTTTG
          CAGCGTCCGAGTGGAGAATGAGCGAGAATCTTCGTGGCGCAAAGCTGTAAAATTTCAATG
          AAGAATTTGGAAAACCTTTGGGGATTAAGGGTTCCGACGATTCACGCTGTAACTGTGACG
          GATCGGTTGGGGGGATCCTGTGTTAAAGCGGGTAAGGCGACTTACACTTAACTTTGAACT
          GATTAGCTCACACAATCATGCCTCCAAGCGGCTGTGGCGCCGGTCTTCTAGAATTATAAA
          TAGATGTCGGCAATGCATCGACCGAGACGAGACCCATCAACTGGGATCCAGCTCAACCCA
          GCAATATCCATTTAGATCTGTATGCGACGTGTCCTACCAACCGATCTTCAATTTAGCTCC

          GACGACAACGAGCATTTGTGCTGACCTGTTCCGTCCTTCCCGGTTGCTTAGGCCAGAATC
          GCTGATGGAGAGCATTTGAACTGATCTAGTCGGTCATTCCCGGTTGTTTTGTCCAGAATT
          TACAATATCGAGTACTTGACCCCGTTCCCGCAATCGCCCCTTGCCCGCTACGGCGGACTC
          ATGGTATAAGAGGAATCGGACCGAGCTTCGCTCGCCTCACCGCCCCACAGTACTGTGTGT
          TCGTATACGGAGTGATTAAACCGAACCTAATTTTCCCGTTCATACCCTTTTACCGAATCA
          TCGCACTCGAAGCAGTAGGTTCGGACGTGACATTCTGTATCAACGGTTTGTACTAGGACC
          TTGAAGACTATTAGGCTAGCCAGGTTCTCATGCTCTCCTCCGAGCCCCTGGATTCTAATA
          CCGAAAATTGGGTATCTGACTCGGACCCCCCGTCTTTTCCCAAGCTCTCACACTTTCCAA

          GTGTTTCTGTCCTGCGGATACAATCCACTAAAATCAGATTTGCATGATTCTATAGGGTAT
          GTGTCTGTCTCTCATGGATAACATCAACTGAAATCAGAATTACATGATTCCATAGGGAAG
          GTGAGTCTGCCTTACCGGCGAAATCCATTACGCCGAGGCTTACTTAAACCACCTGGGCAG
          GTTCTTCCGGCGTTAAGTCAACGGGAGAAAGGCACACAATTACACGATTTCAGCGGGCCG
          GTATTTTCGCCGCTAGAGTCAGTTGTGCCTGGTGCCGAACCACTACCCGTACGCGAGGTA
          ACCTGACCTTGTTCAGTCCGGTCCATAAGAAGCGCAGAACCACCCACAATAGGGGTGGCC
          ATGCGTGAATCGTAGAGGAGGACCCCAAGGAGTGCCGCCCCAAACGGTACGCATCGGCCG
          AGATTCCATTCGCCGTGAAGTTAGCCAAGGTGCGCAACATCATCTGGAGTTCATGGAACC

          ATCAGGCCGGGAGTCTGTTCAAAATATTGCTGAGTTACTATATTCGTTCCCTGTGCCGAT
          ATCAGGCCGGGAGTTTGTTCAAAATGTTACGGAGATCTTATGCTCCTTCTTTGGGCCGAG
          ACTGGGTCAAGTGTCTGTCCATAGTGCCATGGACCTATTGTACCGGCTACTGGGGTTATT
          CTAGCCTAAACAGTCCGTCTGTAACCTTGCAGATGCTCGACGTTTATTGTCCTGGCGGAC
          ACCAGATAGATTATCTGCCCGGCTTGCGAAGTATTCGACTTAGCCATCCCACGTCCCGGT
          ATTAAATAGACCGCCCCCCTACCCTGTCCATGATCTTGAGCACCCAACGCCTGGTGAGGT
          GATATTGGGAATGAATATCCATGGCGTCATTGTACCACAACCCGGGGTGCCCCCGACAAC
          AGTGGAGGTCGTAGTAGTCGATGATGCCGTCACATCGTCATTCGGGCGTGCTAGGTGGCA

          ACCTTGGCGTTTGTGACGACGTGGCTTGCGAGGTCGCAATTAATACACAGGATGCAACGG
          ACCTAAACGGTTGTGACAACTTCACTTGCAGGGTCGCAATCAGTACACAGGAGGCAAAGG
          GGCAAGTTGCCTGTAGTCACATTAGACCCAGTGTCGAAATCGATGCGGGAGATGTAGTTG
          ATCTTTCCTATTCTTATATTTGGTCGTCCTGAGTAGAGCGACATTGGCATTTCGCATGCT
          AATGCATAGGACTTGATGTCGCAGATATAAGGGTGAGGTTAAGTAAACCACGTCCGACTG
          ACCACACCGGTGGCATTCCTTTATGCTATGAGTTCAGCTTACTTATCCTAGGTTCAGTCC
          TCATCCAATACTAAACTATTTCGAGTTATGTCGCCCAATAGTACAAACAGGACATCAACG
          GCCACGGATGTTATGCCATACCACGGTCTGATCATTACCCAAGCAAACGCTATATAACGT

          GGCGGGCAAGATAGCCACATACCTGTGGAATTTCACAAAT
          GGTGGGCAAGCTAGCCACGCACCTGTGGAATTTTACAAAT
          TCCGAAGAGGTTAAACATGTATTCTCACCGGCCGAGAAAT
          AAAGTCTCGAACCGTGACGGGAGGGTACTAAAACATGATC
          AATTGGGATCGCGGTTTAGGATAATTATCAAGCAACGTTT
          AGTGGGCATAACGACTAGAGGCCCCAATCACCCAGCGCAG
          AAAGCTCTTCCCTAGTACCAGTTTCCATTACTTCTCGCCT
          TACGTACCACTCTGAAGCTTACTTTCGGCACTATATGCCA

