 8 1000
t1        TACAGGAAGGATAGACAGCTAGATGTACGCAAGGTCGTAGGAACTATAACTATACCCACT
t2        ATCCAGAAGGATAGGCAGCAAGAAATTCGCAAGCTCGAGAAAACTATAGTCGTTTTCTCA
t3        TAACAGGAGGATAGAGAGTGAGACATACGCGAAGTCGAACAAATCATAGCCGGGTCCAGA
t4        CTTCAGACGGATAGATAGTGAGATGTACGCTACGTCGAACAAACGAAAGGCGGACCCACA
t5        TATTAAAGGGATAGCCAGCGAAATGTATGCTAGGTCGCAAAAGCGATGAGCGTATTCGCA
t6        TTTTAGAAGGAAAGTCAATAAGATGCATGCGAGGCAATACAAATCATGATCGCATCCACA
t7        TTCTAAAAGGAAATCCCATAAGATGTACGCTTGGTCGGACAAACTGTAACTTTAACTGCA
t8        CTGTTGGGGGTTGCTAAACAAGGGATACTTCCCAATTGGTGTTTTGAAACAAGCATTCTG

          CCAGGCAGTCCGAGCCAACCAAGATGTTGGCCAGAGAAGAAGCACAAAGGCATCGGCCTC
          ACAGGCAGATCGAAGCACACAAAGTCACGGCGATTGAAGATGCATTCCATGATCTGCCTC
          ACAAGCAGCTTGAACCAACTAAAATTTTGGAAAGTGAAGAAACAAAAAGAAATTGGTCTC
          ACGGGGTGACTGAACCTATCAAGATCTTGGCGGGCGAAGAATCACAGAAAGTCCGGTATC
          ACAAGCAGGCCGAACTCAAGAACATCTAGCTAAATGAAGAAGCACAAAGGAGCTGGTTTC
          ACGGATAGACTGAAACTATTAAAATCTCGGCGAGTGCAGAAGTATGAAACGGCTGGCCCC
          TCAGACGGGCTGAAATTGTCGAACTCCAGGCAAGCGGAGAAATGAAAAGAAACAGGTCGC
          TCCGGATTACAGTGGCTTCTTTAACTCGGATAAAAGCGCAACTTCAAGATGACCTTGGTT

          AGTATGAACAATGATAAATGATTCGCAAAGAGACCGTAGTGGGGGTGTGTTAATGGGCTA
          AGCGTGAACTATAATGCGTAGATCGTATAGAGGCTGTAGCGGAGCCGTGTTCGCGCAACA
          GGCCCGAACAACATAAAAAGATTCGTATAGCGGCTGTGGCGGAGCCGGGTTCGCGCACTA
          AGCGCGAATAACAAAATATGATTTGTATTGGGGTTGCAGTGGAGGCGGGTTTGTACGCTA
          GGTCTGTATGACCAGATAAGATCCGCATCGGGTCTGTAGCCGGGGCGATTTCGTGTGTTA
          GGCACGAACAGTTAAATAGTATGCAAGCAGAGGCTCCAACGGAACTGAGTATGCGTGTGA
          GACAAGAACAACATCGTATGATTCACGCAAAGGTTGTGGCGGCGGTCTGAACGCGCGATA
          GAAACGAAACCTATAGTTAAAGTAATGCAAGACCTTCGTGCCAAAGCCGATTAAGAAATC

          AGAAATAATGATCTACCCGTAGGTGATAACATCAGCAAGCGTACCCATACGGACAAACGT
          AGAGAGTGCGACCCGATTTCGGATGATGGCATTTATGTGTGCACGCGTACGTATAGACGT
          TGGGTTGACGACTCGACCGTAAATGGTGCCCCCAACACGTGTAGCTGTACGAATAGACGT
          AGAGAGGACAACCCGGCAGTAGATGAAAGTATCATTAATCCCATCCACACGAACAAATGT
          AGAGAAGACGTACTGACTCCAGATAGTGGTAACAACACGTGCTCCCATATAAAAATATGA
          AGAGAGGACGGTGCGACTGCAGAGAAGAGTTTCACTGCGCGCACCCGTACGGAGAGATGA
          ATAGAAGACGATCCGGTTGCAGACGATTGTGTCCATGTGTGGACCCATACGGACGGATGA
          AGCACTTATTGTAAGACCAAGCGAGGTCACACATTCTAGCGAGAAGCCAAGGTCTAGGGC

          ACACTTACAGTAACGATCTATGACGAGCAACAGATTGTTGCGTCCAGCAAGTGCAAGGGC
          ACGCTCAATGTATCAATCTATGAGGAGAAAGAGTGGGCTACGTCCAGCAACTGTAAGGGC
          ACGCTGAAGGTTCTAGTTTAGAACGAGAAACAGCTTACAATACTCAGAAAATGCAAGGGC
          ATGTTCAAGTTATCTATTTGTGAGGAAAATCAGTCTGCTACACCCGGCAAGCGTAAAGGC
          ACGCATAAGGTGTCCACCGACGAGGAGAAGCGGCTTGCAACACCCAGCACCTGTTAGGGC
          ACCCTTAGGGCACCAATCTACGAGAAGAGCCAGGCCGTTACACTTGGTATTTGCAAGGGT
          GCGTTCAAGTTAACTATCTTTGCAGAGAAACAGCCGGCCATATACGGCGCATGCAGGGGC
          TTAATTTGGCATAATGTTAGATCTCCAATTCGGTTAGCGAATGTAAAACTTTGATAGTCC

          AACGAAGGGATTGAACCCAATGGCATTAGAGACTTAGAAGCCTCACGGCGTAAGGCAATG
          AACGAAAGGGTCGGATCAAATGGCATTGGGATCTTAAACTCCTCGCGGCATAAGCCATTA
          AACATAGAGATTAAACCCCGTGATATCGGGAATCTAAACTCCTCGCGGCGAAAGGCATTG
          GACGAAATGACTGAACCCGATGTTCTTGACCGCTGTAACTACTAGCAGCGATCGATATTG
          AATGTAGTAAGAGAACCCGTCGACATTAGGACCCTGGATCTTCAGCAGTGCCAGATATCA
          AAAAAAGGGACGCAAGCTATAGGCATTAGGAATCTGAGCGTCTCGGAGCGTCGGGAATCG
          AAAGAGGATATTGAACTCATCGGTATTTGGATCTTAAACTCTTTAGAGCATCTGATATCG
          GAAAAAGGTTCTGCACCACACTTATTAACTTACGTCAGTCTATCGAAGCGTTGGACGTCG

          TGGAGGCTACTGACGATCTAAAATTGTGGCACGGGTATAATTCTTACTAGCGCCGTATCT
          TCGAGGCTACCGTCTACTTTAGATTACGGACTAGGTACTATCCTTATCGGCGTTTTGTTT
          TCAAAGCTCCTGATGACAGAAGGCGATAGGAGAGGTGCAATCCTCGTCAGGGTCTGGCTA
          TCGAGGCTGCCAACGATACAAGACGCCAGAACGGGTGCAACCTTTATTAGCGTCCTGATA
          CCCACACTACCGTTCGCATAAAGCTACAGCCAGAATGCGATTTCGCTCAGCGTTATGTCG
          CCGAGGCTGCTGACGATATAAGGCTGAAGCATAAGTGCGAATTACACCGGTGTGTGGTAG
          CTGGGACTACCGATATCTTATGACTGCAGAATTAGCGCATTACTTATTGGAGCAACGTTG
          ACAGCCTAATTGATGGGTGAGGACTGATCCGGACTCGTAGCTCCTCCCCGATAAGAGTGG

          TTTGAATACATCACGGGGCTTTATCAGAGCTCTATTTACGACAGAACTCGTCGTCAGGGT
          CGGGATCACACTGCGGAGTCCTATCAAAGCCTTATTCAAGACCAATCCTAATGTCAAGTT
          ACGAATCTTTTCGCCGGGTTCTGTCGGAGTCTTTGCCATGACGAATCCTAACACCAATTT
          ACGAATCATACTGAGGCGCTCCGACAAAGCCTCTTTCACGGCGCATCTCAATATCAAGCT
          GCGAAACTTATTGTGGAGTCCTATCAAGGCTTAGCTCTTAACAAGTCCCAACAACAAGTT
          ACGGACCTCGTCGGAGAGCTGTATCAAAGCCTCATTCATGACAAATCTCTAAGACAGGTT
          ACGGATCCCGTCGCACAATCCTATCAGGTCTCAATTTACGACAAAATACAATGGTAGACA
          ACATCCCGCTTTATGGACGCCTTTGTGGCACCGCCTACTGAAAACTGTGGCCCAACTACT

          CTTTTGTTATGCAGGGTTAACCCCGTACCATGCGTCCCAAATAAAAGATCTTCATTCTAT
          TATTTTCTAAGAAGGGCTAGCTCCGCTCCCCGACTCCAAGGTAAATGATCCTCGTTTTCG
          TTCTTGCCAGGAAGGGCGTACCTCGTCCCGTGCCTTCGAGACAAAAAATCCTTCTCCCTC
          TTGTTGCTACGATCGGTTAGACCCACCCGATTCTTCCAGCATAAATGATCCAAATTCCTC
          TTCTAGCTGTGAAGAGTTAACCTCGTCTCATCCTTACAAGACACAACTTCCTCTTCCCTT
          TTCTTGCGAAAGAGGGCCAACCCCGTCCCCCATACACATAATATAAAGAGCATAATCCAT
          TGCCTGCTACCAAAGACTAAAATAGTACCCTTTCCACCAGAGAAAAGGTCCTTATTCGCT
          GTTGCGGAGCTCCACGCTATTGGTACTACGTGATCTCAGTAAGACTAACACTTTGTGGCT

          CCCTAGGTAGCTAAATGACGTTACGCACAATAACGGCGTAATCTTAGTTAATATCTCGAA
          CCTTAGGTAGCTAAGTGATGTTTCGCAGAACAACGATGTAATTAAAGTTAAAATCCTGAA
          CCCTAGATAACTAAATGTTGTCACGCAGAGTAATGGCGCATCCATAGATAATACCTCGAC
          GCTTGGATCGCCAAACGAGACTGTGCAGGATAACGAAGTAGTTATGGTTAATGTCTTGGA
          CGTTAGGTGGCCAAAGCATGCTGCGCCGAATAACGGACTTATTAAAATGAATAGCATGTA
          AGTTGGGTTGCTACATGATGCTATGCAGATAATCGGGACACTTAAAGTTACGTTTTTGAA
          AGCTTGGTTACCACATGATGCTACCCAGGATACAGGTACAGTTAGAGTTGGTATTCTGAA
          CGCCGTGTTGAAAGAGGATTCAGCACCGGGGTACCGGTTAATAGAGTCATACGATATAGA

          CTCCCACGTTCGCTCCTTAATTCGGTCCCTAATGCCTCCACGATCACACAAAATGCGGAT
          CTCCAGTGTTTGTCCTTCAGTTTTGCCACTAATATCCTCACAGACAAACCAAGCCCAGAT
          CCCAAATGCTCGTTCTTTAATTCAGTAATTAATATTCCCCCATACACACAAAATGCGGAT
          CCCTAATGTTCGCTCTTTAATACAGCCATCAATATCAACACAGGCACCCAAAATGTAGAT
          TTTTAGTTCTCATCACGGTGCTCTATCATGATTAACGCCACAGAGACGCAAAGCTCTGAC
          GCCGAGTACCTATTTATTAGCTCTGTCACTAACATCTCTATGGATACACAAATCACAGAT
          ACGTACTGTTGATTACTTAAATCTTCGATTAAAATCAGTACAAACACACAAAATGCGGAT
          CGTGCATACACGTTGGCAAGTTCATTGATTACAGATTGCTAACATGTTTGATTAGGGGTA

          TCAAAAGGGTTAATATATACTACGTACGGTCCCTGCCGTTTAGCGTTCTACCATTTGCAG
          TTAAAAGAGTAAACACACATTCAAGACGGTCCCCTTCGTTTAGCGCTTAATGACTTTTAA
          TCAAAAGCGTAAATATATATTCAAAATGGTTTTCTCAATTTAGCGTTGAACCGCCTTAAG
          CCGAAAGCGTGAACAGATATATAGATCGGTTACCCCCGCTTAGTGACTCACCATTTTTAT
          TTTCAAGCGTAAACATACCTTCTGAGCGGACCCCTTCATATAGCACTATAACAGATTTAA
          CCAAAAATGGAAACATACACTCAGAACTGCCCACTTTAAAAGGCGTTTTACCACTTCTTG
          ACAAAAGAGTAAAAATTCACCCAGATAGGTTTCCCCCAAATAGCGCTTTAACACTTTTCG
          GTCAGCGGGAATAAAAACGTTCGTGCAAAGCTCGTCTCGGAAGCATCCCGACGGCCCTAG

          CTAGTCTGCCCTAAAGTATGCGCAGGAAATAGCCGGGGGGAAGTGACCATCCTCAAGATC
          CCCCCCTGCCCTAAAATCCGCGGCCGGAATGGCAGAGGCGGGATGACCATTTAACGTATT
          CCTGCCTACCCTACACCCCGTGCCCAGAGTTGCCCAGAGGAGGTAACCAATTACGAGATA
          TATGCCTACCCTAAAATTCGAGTCCGAACCAGTCAGGGGGTACTGACCATTTACCAGTCC
          TCTATTGACGCCGCCATTCGCGCCCGGAGTCGCCTAGAGGAAATAGCGATCTACCAGAGC
          CCCGTCTGTCCCGAGATCTGTACCTGGAATCGTCGAAGGACGACGAACCCTAACTAGATC
          TGTGTCTGCCCTAATACTCGCGCCAGAATTCGTCGAGGAGAAACGACCATTCACTAGATC
          ACTGCACGTATGCGACACTACGTCAGCGGTTGACTCACGCCTCTTGCTCTGCATCAGTGT

          ACTGTATTCGGTTATGTTGGTAATCGCTTATCAGCTCTCCCCATAGCCGAGCCCGGTCTG
          TTCATATACAGGTATGTGGGTGGCCACTCACTAATTCTTTTCACAATTGAGCCTGGTCAT
          ATCGGATATAACTATGCGGGTAGCTGTTAACTAGCTCCCTTCACAGTTGTGTTTGGTCTT
          TTCACAAACAGTTTTGCGGGCAGCTGTTTATTGGCTTTCTTCACAGCCGAGCCAAGTGTT
          TCGGCACATGGCTTTGTGGGTGACCACCCCCTGGTTCTCTTCGTAGTGGAGTTTGGCACT
          ATAGCATATAGATGTGTGGATAGCCGCGTGTTAGCTCCCTTCACAGCTGAGATTGGTTTT
          TTGTAGGACAGTTGTGTGGGTAGCCGCTCATTAGCTCTCATCATTGTCGAGCTCCGAGCT
          TTCGCCCGAATTCAAACCGGCCAAGGCTCGCATACAGTTCTGGCCTCCAACGAACGGTAC

          AGCCATGATACAAAGGTGTTCAGGTACGACGCTCCCCAGTAGAGCGGGGCGCTGATACTG
          AGACAGCATACGTAGGTGTTAGGCTACAACGTTTCCCAGAAGAGTGCGGCGGAGGCATCG
          AGCCCACATATGAAGATGTTTGGGTATAACGTGCCCCAGTAAAGAGAGGTGGAGACACTG
          AGTTGACACTTAAGGGTGTTCGGGTCTAGCGCCCTCTAATACCGCGGGGCGGAGGCATCG
          CTCCGACCAACAAAGGTGTGCGGGTAATAAGTTGCACAGTAGAGCGAGGCGTAGGCAACA
          CACCGACACACCAAGGTTTGTGGACATGACATCCACCAGCCGAGCAATACGGAAACGCTA
          CACTGCCACACAAAGATGGGCGTGTAACACGCCCCCTAGTAAAGCGGAACGGAGACAATG
          GATGGAGCGAATGAGTCATGCTGCGCTAATTCGGTAGACCGACGAGCCGGTCAGGCCACC

          GTACTCTCCTACCGATGGGGGTAGTGAATTCGAGCATGAGAAAAGACACCAAAGGGTGAT
          GCGCTCCCCTTTTGATGAGCGTAACCTCCTAGTGTCCGAGAAAAGACTCCAATGGGTGAT
          GCATACCCCCACTGCTGAGTGTAGGCAACTCTAGCCTAAAAAAAGATTTAGAAGGGTGTT
          GTAACCTCCTACCGATTAACATGGCCAATTCGAGCCTGGGAAGAGACCTCAAAGGGCAGT
          GCATTTTCTAACTGCCAAGAGTAGCAATCCAGATATCGATAAAAAACCTCAGAGGATAAT
          GGAGCCTCCGACTGCCGAGCGTAGCTAATCTAAGACCGAAAAGTGACCGTGAAGGGTGGT
          ATATTCCGCGATTGATGAGCCTCAAAAACTCGAGATTAAAGAAAGATTCTAAAGGGTAAC
          ACGATAAAGGCCACCCTGGGGAGGCCCAGGTGTAATTGAAAAGAACTCTGACGTGATTAT

          GCTCAAATGAGGCGATGGTAGTAAGGTGAAAGTCCTTGAG
          CCAGCAATGTAACAGTGGTAATAAGAGGCAAGTCCGTGAG
          TCAATAAAGAGGCGGTGGAAGAAAGGAGTAAGTTCTTGAG
          TCAGCATTGAAGCGGTGGTAGCAAGTTGCTAGTCCTTGAG
          AAAGTAGGGAATCGGTCGCAGTCAGGCGTAAACCCGCGAA
          CTCGTAGTTAACCGGTGGCAGACAGGTGCAAATCTTTGAA
          TGAATAGAAAACCGGTGGCACGCAGGTGCAAATTCTTACA
          AGCGAGTCGGACCGCCGCTGCCTCGGCACTAGTCTGAGGG

