 8 1000
t1        AAGGTTAGCGAGACATCATCACATTTGATGGGCAGCTATTACGATTATAGATCTATTTAA
t2        AAGGTTAGCGAGACATCATCACATTTGATGAGCAATTATTACGATTATGGTTCCACTTAA
t3        AAGGTTTGCCAGCCGTCATCACGTTTGACGGGCAGTTTTTGAGTTTGCGATTCACCTCAA
t4        AAGCTCGGACAGTCATCATCACGTTCAACGAGCCGTTACTGTGGTTACGGCTCAGCTTAA
t5        TAGTTGAGGTTGCTATGTATGCACTTGTCACCCAACTAACGTGGTTGATGCCCCACTCTA
t6        GGGGTAAGACCGACTACCTTTCTTTTATTCACCAGTCGTAGCGCTTGCCGACGTGACTAG
t7        CTCAAGAGTCAATTAGATTTCATTCCTTTGCCTTCCCACTCAACTCGTGCCTCCCCTTGT
t8        CCAATGTGTTGGTTCTTATTTTGAACTCCGTCACAAAACCGAACCGGTGGCTGCTTTGTG

          GTGCCTCCTCCAGTACCCATGCAGCTCAACCACATTTGCATGCAAATAACTGAGGCGAGT
          TAGCCCCGACAAGAACCCAAGTAGCTCAACTGTATTTATAGGCAAAAACCCGAGGTGAGT
          CAGCTAACATAAAAACTCAAGCAGCTCAATCATATTTGTATGCATAAACCCGAGGTGTGT
          TGGCTATTACCAGTGCTCAAACTGGTTACCCATGAACGTACGAATAGAGACGAGGTGAGC
          CAGATGTTGTAAGATCTAATACGGCTAATTTGTCGTCTTACGTTCCAGCACGCAGGGAAA
          TCTCCCTGCACTTGAGTCGGCTATAGTAGCGGCGCGAATGCACTGCCACATGTAATATCA
          ATTGACATTCACCAGTTCAGACCGGGGATACCACTCCTTATTTTCTAATGCTTCGTCTAT
          GCTTTCCCATCTTAGTCATATCCGTTGGATCGTCTCTATGTCTCCTTATGTGCAGAACTA

          AATAGACAATGAACTAGGCGATATTGACCCCCGGTATCAGCGAGGTCGATGTAGGTATAT
          AATAGACAATGAACTGGGCGATACTAACCTCCGGTTTCAGCGGGGTCGTTGTAGGTCCGT
          AATTGACAAAGGACTGGGCGGTACCAATGTTTGGTAATAGCGGGACCATTGTAAATATAA
          CATAGACAAAAAACAGGGCGGCACAAACGTAAGGTGTTAAAGGGGTCGTAGTTGATATAT
          CACACACATATGGCAGGAAAGTACCAGCGCGTGGAACGATCAAACTCGAAATTCATCCGC
          CATACATCAAAACCGGGGCTATAATCACATGCGAATCCGTTCGAGCCCATGAGCATGAAA
          TAGACCTAATAGAAAGTCGAAGAGTGTTGTGTGATCGATCAACTACCGGAGTGGACATCC
          TCCTTACGCAGAACAGGAGACCCGTTCTGACTACACGCATAGTAGTCGCCCCGGACGCAT

          GCCACAATGCCCAGTGGCCGCAGCAGATGCAAGCGTCACGATGACTACCTCCTGTGGACG
          GCCCCAATGCCCAGCGGGTGCAGCCGATGCCAGCATCACTACGACTACCCTCTGTGGAAA
          GCCCCGATGCTGAGGGGGTTCAGCAGATGCCAGAGCTACGATGAGTATCTTGTGGGGACG
          GCCAGAGTGTCGATAGGGTGCAGCAGACGCCAGTGCTAAGACAACCACCCTTTGCGGAGT
          CCCAAAGTGCCGAGAGAGCGCAGGGGCGGCCTGCCCCTCGACTACCGTCCCTCGCGAGGA
          AGACAACTGTCCGGGGGGTGCGTCATGAACAGAGTTGGCACAGATTTCCCAACGCCCGAT
          GCTTAAGCGCAGGTGCGGCGTCCGTACAGAAATCACCAGAAAATCCTTAGGTTTGCAGGA
          GGAAAGGCTTGTGTGCCTTGAACCATCTTCGAATATTTCCAATGTGTGCACGTACGCAAG

          TCGCTTTGGAGAAAGGGGAATACGAATACTGCCTGCTGCGGTTTTGGCACACTGGAGCTC
          TCGCTTTGGAGAGAAGAGAATATGAACACTGCCTGCTGCGATTCTGGCACATTGGTGTTC
          TCGCTTTGGAGAGTAGGGGATAAGAGCACTGCGCGCTGCGGCTCTGGCATACTAGAGCTC
          TCGCCTAAGTGGGGTCAAGATCTAAGTGTAGCGCGCGGCGGTTCTAGCGCATTACCGCTC
          TCGCTACGAAGAGTTTCACACTCAAGTCCTCGACGCGGCGTCTCAAGAACGCGAGTTATG
          TCAATTCGGTGATCCGAGAATACAACAGTTATGCTCCATATTACCAAAATTTGTGTAGTC
          ACAGCGCGGGTAATTGGGAGATCAGATACGAAAAGGCAAGTGTCTGTCGCCTGATCAGAT
          AAGGTAAACCAAAGTGGCAGCCCGTGAGCTCCAGGTAATGCGCTCGACATACAAGCCTAT

          TTGGAATGTCGTAGTAACCAGGTTGCCCGTACCGCCTTGAGGTGTTACGGTCTTGTGCAG
          CTGGCCTGCCGTAGTAACCAGATTATCCGTGCCGCCATAAGGTGTTGCGGTCTTGTGCAG
          CCGGTATGTCGTAGTAACCAACTTATCCGTACCAAGTGTAGGGGTTACAGTTTTGTGAAG
          CTGGTATGTCGTTGTACCTAGCTTAAACTCATCAACTCATGGTGTTTTATTTTTGTGTTG
          ACGATTTCACGCCGGGAGTAGTTTAACAACATCGGCTTTAAGTATTAAGGTGCCACACGG
          GCCGAACCTCGCCGTAGTCAGTACACGATTGATGATACCCGATGTCGGCCCGTTGCTCCC
          GTTTCATTTCGGCGTATGCCGAGCTAAACAATGTACCCATAGCATCAGCGCAGATTAATA
          CGGGTGTCACGGGCCAAGGGCTGTTGGTTGTCCAGGTATGGGCGTTGCTATCACGCAGGT

          ATCCCGAGCGATGAAGGCAGGGTTCCCCTAACAATTTTAACACAAGGAATAATCATCTAT
          ATCTAGTGCGATGAGAGCAGGGCTCCCCTAACAACTTCTTAAGAAGGACTGATCTGGTAT
          ATCTGGGGCGATGAGAGCAAGGTTCCCCTCACGGTTTTTTAAAAAGGAATCCTCTAGTAT
          AAATAGCGTTATTAGGGCAGGGTCCCCCTGACGTTTCCTCGGCAAGGAATACCCTAGCAT
          ATCTGCGTCAATGAGGGCGAGGTTCCTACATAGATTTCTTAGGAAGGGTAGATGTAGCAT
          ACCTAGGGGAGACAGGGCAGGGAACCACTGCGGAGACCGAGTCCGGCGAACACCCATTAT
          AACCCCGACGCCCATAGTTGGTTACCATGGCGGCAACCCAGACTGGGAAGTGGCTGTCAC
          GTGCAGGTGACCTCGTAGACGTTCGTCCTGTTGCGTTTGAGTTATGTACCGGTAAGTCGC

          AAGGGTCTCACAACTTCCCACAACGGTGAGCCGGAGTGTGGTTAACTAGGCGAACTCTAA
          GAGGGCCTAGCCACTTTCCACATCAGCAAGCCGAAGCGTCCTTAACTAGGCGAATTCTAG
          GAGGTCCTCGCCATCTCCTATGTCGGCGAGCCGAATCGTGGTTAACTAGACGAGTGTTTA
          GTTGTCCTAGCAACTTCCGACATCGCCGAGTCGAAGCGCGATAAACAATCCGGGCGCTTA
          AAGGCACTCGGACTCGCATCCACTGGCAAGCGGGTTCGCGTACCGCTGTCCGCGTGGTTA
          TGATATTATAAAAACCCGCTTTATAGCAGACCGCAGTCTGATATCCAATCATTGCTCTGT
          AAATCTAACTCCGTTCAACTTTGCGGCACCCTACAGCGCAACCATAAAGTATCAAATAAC
          GATAATTTCTGCTCCCCAAGATGAGGCACTCTCCACCATCCTTAAGCAACATCATATCTC

          GACCGGACTTTGGGGCTACCCACAGGTACTTACAACGCACTAACTACTCTACGAGTGCTT
          TCACAGATTCTGGGGCCCTCCATAGGTACTTACAACGCACTAACTTTTCTACAAGGACTT
          CCAAGGAATCCGGTGTTGTCCGCAGGTACTTGCAGCGCACTAACCACTCCACAAGTGCTT
          GCACGGTAACCGGGGAACTTTCGGGGGACTCTTAATGCTCCAACGATTCTATAAGGCATC
          ACAGGGGGCTAGGGACCCACCGTAAATACTCAGAGCGAGATTGCCGGCCAATAGGAGTAT
          TCCCGGGACCAGGGACTCCCTAGTGGCATACACAGGCATCCAGACAGTAGTTAAACGATT
          GTCCCAGATATCGTGATCTCTACAAAATCCTGTCGCGAGGAATGCGCTCTCTAGGGGTCC
          CAATCGGCCTAAAATTGCGCAGATAACCGTAACGTTGAGGTAGATATTCAAGAATAACTT

          TATCTACTAACTCAAAACCCCGCTGTTACCTGACATAGAGTGCAGCTTAATGCAAATATG
          TATCTACTAACCCAAGACCCCGCTGTTACCTGGCATAGGTCAAAACTTCATATAACCATG
          TATCTACAAAATCAAGCCGCCGCGGTTTCCCGCCGTAGAGTGAACCCCCATATAATCGTG
          TCCCTATGGACCCAAGTCGCCACTGCTTTTAGCTATAGAGTCCGATTCCGTATGGTTATG
          TTTGTACGTACACGAGGTGTCAGCATCCTTTGCCGCAGAGCGAAACCGCATCTGAGTTAG
          TACCGAATAATCTGGAATGACGCTGTACGCCGAGTCAAAGCGTAGCATCGTCCACCTGGG
          TCCCTACCAATCGGAAGCTTGATTGTAAACAGGTACAAGAAACAGATCTGTACGCGTGAG
          AGCTGGCAAGCCAAATGTGCCCCCATAGGACGCCATAAAATTTTATCCGCTATCATCATG

          ATTGATCTTTCTCGCGATTAGCTCATGGTAGGCGGGTCTACGTCCTCGCGGCGGAACGCA
          GTAGACTCTCCTCGCGATGAGCTTATGGTAGGCAGGGTTACGTCCCTACTGCGGAACATA
          ACAGGCTCTTTTCGCGACGGGCCGCTGGAAGTCCGGCTTACGCCCCTACCTCGGAACATA
          ATAGACCTTCTGCTCAATTCGGGTATAATAGGTAGGTTCAAGTCCTCTCATCGGGACTTA
          TGACGCGTTGTTCAAGGAGTACTTTTGTAAGTCAGGCTGGTCATCCCAATTAGAGGCGCC
          AAGAGATCCATCTCCGGCGTGTCATTTTGATGCCGAGCAAAGACCCCGACTAAAGAGCAC
          TGATGCTGCCCTACCAGGATGTTATGGTTAGCGGTGAAAGTCACCCTCGCCAGCAAATCG
          CAACCTCTTGCGAGGACCAAGTGATTAATAGGCACCAAATGTAGCCTGCTTCGGTAGCCG

          TTCAGGCCACTTTCCCTCTATTAGCAATCGGCTCCATTGTGATACCTCGCAAAGAGCGTA
          TTCCGGCCACTTCCCCCTTACTTGCAATCGGCTCCATTGTCCTGCCTCGCGAAAAGTGTA
          TTTCGGCCACTTCCTTTTTATTTGCAATTGGCTCGATCGTGTTACCTCGCAATATGTGAA
          GTTCGTCCACACCTGCTTTAACTTCAGTTCCCACCATCCCACTGACTTACGAAATACGTA
          AAGTTATCCATTCTCTTACGTCTGCAACCTACTTAACAATACCTAAGATTGCGACATACG
          TTAGCAGTGCTCCATCATTGCTCGTAGTAGTCTCGAATGCGTGAGCATACTACATCCGAC
          CGGACCACACGCTGTTTCATTCTGTATCAGGTTCATCTGTTGTGTTATTAGACACGATTA
          GTCCCGTGTTCTCACTTTTGTCTGAACTTATTCCTTGCTTAACTATTTTAAAGTCATGTC

          GCGGAACATTCCGTTCCCACTAGCCGTTACGGAACAATCAAAGAAGCGCTACAGTCTACC
          GAGGAACATTCCGTTCCCACCGGCGGTTGCGGAACAATCAAAGAAGCGCTACAGACTATT
          GAGGAACATTCCGTAGCCACCCACGGTTGCGGAACAATCACTACAGCACTATAGCCCACT
          GAGGAACTTTCCGTTGCCATCTACGGTAGCGGAACTATTATAGCAGCGCTATAGCGAATT
          GAGCTCAGGACCGTTAGTTAGTACAGTTCCGACGTATTTATAGATGCGCTGGAACTCGGC
          ATTGACCTTACCGTCAATGTGTGCAGATCAAGGTCAACAATGAAGGCGTTAGAGAATGTC
          CTGACTCTCTCATTCACAACGCTCCTTCTCTGTTAAGTCGCGTATCTCTCGACACCGGCG
          ACACTTCTCAATTCGTGCGTCCCCGGGAACGACGTTGCGTCAGACTTACTACGGTCTTAT

          GTAATGCGTGCCTCCTACTTCCCGAGGAAGAACATTGATACTGACTGTAACTATTTGCCC
          GTAATGCGCACCCTTTACTTTTCGAGGAACAACTCTGGTACCGATTGTAATTATTTGCTA
          ATTATGCGTATATCTAACTTCTCGAGGAATAACACTGATACCGACTGTAATTACTTGCTC
          GTAGCGCGCTCTTTCTACCACATGACGACTAATACTGACACCGGCAGTAACTACCCGCTC
          GTAAAAGCCACCATCAGCCTCCGGAAGTCTAGTTCTCGCACCGACTCTAACTATTGGATT
          CGACTCCACGTTGCTATCCAAAAGGGGATGAGTATCGGACACCGCTACTTACCTGCGTCA
          CTTAAGCACGTGCATCATGCATGCAACGCACCCATCAAGCCCACTCGTCGCTGCTAAACT
          GTATATAGAACAGCCGAAATATTCATGATAGCCAATGACTAAGATCGCCTAAGCCTGCCA

          GCCGAGAGCACAGCCTGTGCATAGGCCCTTCGTGCAAAGTTGTACGAACACGTTCATGTA
          GCCGAGACCACAGCCTGTATATAAGCCCTTCATGCAAAGTTGGACTAATACGCTCATGCA
          GCTGAGGCCACACTCTGTATATTGGCGCTCGGTGCAGAGTTGTACCGAAACGCTCGTGTA
          GCCGAAGTCGTAGTCTGCAGACCTGGCCCACGTGTATCGTTGTACTAACACACTCGCGTA
          TCTGAAGCCGCAGTTTGCAAATGAAGTCCTCGAGACGAGCTGTATCAGCACGATCGTGCC
          GAAGAGCCCCGCGTACGAAGACACGGGCGTGAGGCCGGGCTGCTTTGATATGCCCGTGGG
          GAAGAGATGTCCGTCCACACGTCTTACGCACGCACGGAGGTGACTTAATAGGCCTCTCAA
          AGGACAGCCCGTAACGGTGTGTCAAGAGCTAACGAAATGGCATAACGCTATAATCCTATT

          CAGGTGCCTTGGTGAACCCACGAAGCAGTCGATGCAGACGGTGGATGGGAGGACTTGGAT
          CAGGTGCCTTGGTGAACCCACGAAGTTGTTGACACTGATGGCAGATGGGCGCCTATGGAT
          TAGGTGCCTTAGTGAGCTCACGACTCAGTTGACGTAGGCGGTGGAGGCGCGTTATCGGAT
          CAGGTGGCTTGGTGAGCCCACGGCACAGCTGATGCAGGTGAAGCAGAGGAGCCTTTGGAT
          TAGAGGTTGAAATGAGGCCACAACGCCATCGATGGGGGCGATGTATGGGAGCCTAGGGGT
          GGGGTCCTAAAATCCCAGTACAGAGTTATCGACACTGGTGTGGATAGGTATAACAGGTCC
          TCAGATACGCGGGCAGCTTACCCCAACATCCATGCCGGTGCTGTAGGTTAATTTCATGCT
          TCCAGGGCATGATGATCTGGCACAAGCATGAGAGCTGGATATAGCAGGCGATCCGACAGT

          TGCAGGGTTAGCGTCGTGGCGACGTTGTACTTAGGTGCAA
          TGCAGGGTCAATATCCTGGCCTTGCCGTACTCAGGTACAA
          TGCGAGATTGATGTCCTGGCATTGTTGCATTAGAATACAA
          CACGAGGCCAATGTCCCGGCGCTGACGTGCAGTGACCCAA
          TGCGGCGTCGACAGCACGGTGGTGAGCTAGTAAAGGATAC
          TTCTCAGCCAATGCTTCGGGGCTGTTCTACACTGACACCC
          CGTCTGTCCAGTTTCCCCGCATCGTCATTGCCACCTGCAT
          CGCCTGTAAATTGCCTCCGTGCTAACGCATTTTAGTACGC

