 8 1000
t1        CGCACTGTTCCTGATTTAGTTCCCAGTGTCCCCTTTCGGGGCGAATCCGGCCCAGCGGGA
t2        CGAACTGACCGTGATTAAGTTACTGGTGTGTCTCTACGAGGCGAATAAGGGTCAGTGGGG
t3        CGGGTAGTCGGTTAGTTAACAGTCACTACCATGGGGCACTGGTCACAATAGCCAGATGGC
t4        CGAGTATTCGGTGGATAGACCCCCGTTGTCACCGTACTTAATATGAGCTTATAAACTCGG
t5        TGCGGTTTGGTAGAGTGAACAGGGCGTCCCGTTTGGCACGATCTGCCGGGCCGGATCTGA
t6        CTCAATGTAATAAAAGAAGTTGCCTTTTCCGTTCAGCGCCAGCCACGGTCCACGGCCCGC
t7        TGAGGCACTGCCGGGTGTTCTCCTATTGTATCGTCAGGCTCTCCATCGCCGTCGAATAAA
t8        CCATCTATTGTCTAGTGAACGTGTAACCAGATTACGAGCGACCTGTAGATGCAGCTGAAC

          TTTTTAGTATAAGGATGGAGGAGAGTTAGTAATTGTCAACTTTTTACGTAGGTCTAGGTG
          TTTCCAATGTATCGACGGACAAGAATTCGGAATGATCACCCCCTTATTCTTAAACAGATG
          TCCTTTTCTTTTCGAGTGAAGGTGATCCGATTTACTAAATCCCAAAAGCGCGACACGGAG
          CCAGGACAGTATCAAGACAGGAGTCCTCAGCCTCCACACTTTCTAAAGGATGTTATCGTG
          GCTGCGCTAATTTGACGAGTGCCAACCTCGGCTACCGAACTCCTAGCTTTCAGCTCCGCG
          GGTGATCGAGGACGACGTGTGACTGATCCGGTGCATTGCTACCTAGGGCTTAGTTGCCCA
          CTTCATGCAGTTCATCGATAAAATGAATACGTACATCGGCTTCAGAAGTTTGTCTCTCCC
          CATACATGAGTTTGTCAGGAAAATGGCTGTCGTTTTTTACTTCGAGGGTATCACCGGTTG

          ATTTCACCGTACGTAGGGAGACTCATACTAGCCAAAGAATTAACACTCCAGCACCCCCAC
          AGCTAACAGTAAGTAAAGAAACTCATGTATGTCGCAGAACGGACACCCCAGCACTCCCAC
          AGATTCCTGGGGTGCAAGCCGTCCACCTTCGCGGAGCAACAGTATCCTTACCTGCGTCAT
          AGACCTTTGTAGTCCATCTGATTTCCGTCCTTGGAAGACCCGGTCTATTACACGTCTTAT
          ACTCTTGGGTTTGAGTGGCGCCGCTAGTACGTTGGCTTTTAATAGTTTTAGTATGACTGG
          TGCTAAAAACCACCGGAGTAATATATAGTTGGGATAGTCTCGCTACCCCACCGAAATAGT
          CCGTTCAAACTGGGCCTCCTATTTGCGTCAGTTCTAACCAGAAAAACGTGGACCGCTTGC
          TAATCAAAGTTAGAACACTACAACGATTCCAATGCAGAAACTGCGCTCGATTGCTGGGTT

          ACGTTAAATGCGAGGATTAAATCACTTTGAATGGTTATTCCATAGGTTACTCGGCTGGGT
          ACGTAAAGTGCGTGCATATGATCATTCCGAAGGGCGCTCAGTCCGGCTATCCGGAAGGAC
          CAATATAGCTTAGTTCGCAGGTTTTTTTAGACATTAATATTGGTGGTGCCGCGACATGGC
          TAGGCTTTTAACACCCACTAGCATTCGCGCTGTTTTACCTCTCGGTCGGCGCGGATACGC
          GCACCTTGATCACACCTCCCGAACTTACCCAATGCGCCCGGCCAGGTGACAGTACATAGG
          AGGCTCTCAATACCTTACACGTCCGCGTAGAGAAAGGTTAGGCGGCTATAGACGGTCTGG
          AAATTCTACACTTCTCCCGCGTAGAGATAAGCTGTGACGACTGTTATGGCGTTGGTTTAT
          TTCCCTACCGAAATCGTTATTTTTCTGCTAAGTGTCCTTGTGTTTGTAGCTCCGGTAAGC

          AAAGGGCGCGGCAAACCTCTCGTACAGCAAAATAAGAAAAACAAATTGTACTTGAGTTTC
          TCAGGGTGCGTCAGAAATCCTGTACAGTTAAACGCGCAGAGCCAGCTGCACTCGCGCTTA
          TGATGGATTGCGTTACCTTCCTTTGAGTGAGAGATGAAGAGGCAGTACTGGCCGAGTCCC
          CGATAATGCGCCTACGCTTACGAAAGACGAAGGGTTGGCTGACAGCCTTGTACGAATGCA
          AACGAACACGGTGGTAGCAACGTGGGTTGCACGACTCGGAGAAAAATATACACGCGTTTC
          CAGTAGACCCGTGTACATATACTGTACCACAATCATGGATGAACACCCCAAATGTGTCTC
          TTTCGGGTCAACGATAGTGCTCTGGGCCGCAATACACAGTGGACGCCTTCTGTATACGGT
          TTGTGACTTCCTGATTGTATTGTGATAAGAAAAATAGGAATGATACCTTAGCAATGCCGT

          AGCACGCGTGAGGTAGTAACGCGACTAGGTGCCCGGTGGCACTGGTTCAACGCACATCAG
          AGCACGCGTGAGATAGTAAGCGTACTAGCCGCTTGGCGACCTTTGCCTGGCGCATGCTTA
          GGCGTGTACGAGGGAGGTTTTAGTGTAGCCAGCCGGCGACGCTGGTCTAGGAGATGAAAA
          AGAATATGCGGGGGGATCCACAGCGACACCATAAAAGGGTGATGACTTGGTGCACACATG
          TCCAAATGTAAGGGAGGAATCCTTGCCTAAGGTGTACAGAACGTCCACGGCTTTCAAATG
          ATCAAAAACGGTGGAGGGGATCGTATTTTGCGGTGCTCGCAGCACCTTTCCTTATAACTA
          TAGATGTGAGTGGGTGCCGTCCGCGCTTAGCCCTGCTAGTAACTCATTGATGCCCGAAGA
          AACGCGCGTGATGACACGCAGCAAATTCAGTGAAATCGGTACCCCAGTGGTGAACGAATA

          TGCATGAATGTGATTATATTCTGCCCACGAGCTGGGGGGCCTGTAGATATGCTCTCTCTT
          GACCTGGATGCGTTTGTGTCCTATCAATGCACTGGGGAACCCGCTGATAGGGTCCCTTCC
          TATAAGGGCGGTATGATTCGACTGATACAAATTAGGCAATGGACCTAGGTGGTACCATAT
          TATACCGATGGTACCGCGCACTAGCAACGTAGTGGAGCCTAGGTCGAAGCACGTCCTTTC
          AACTTTTGCCCAACCGCTTGTCGGGGGTGCCATAATACATGGGCCGATGGTAGCACCCCG
          TATACGGACCCGGCTACTTACCGCAACTGTAGCAATTTATGAGTTAACGGTACCAACATT
          ACCTACGACATGTTCGCCCACGCTGCGCCCTGTAGCACATAGGTTCGCGAAATTCTTTAC
          CATAATGAAACAGACGCCTTGCGCACGTCTTGTATAGCCTTAGTCAGAGGTACTCGCCTC

          AAGTAGGTCAGATTTCCAGTGATATATCACTTAGTTCGGCTTCGCAGTATAATTCGGGGG
          ATGTAGGTTCAATTGCCCATGAAGTGTTGCTCAGCACGGCTTTGAATCACATATTGGGCC
          TTGCAGGTTTGTTAGCTTCTAACATCCAGATACGGCCAGCACCGATGGACATTTTGGGAG
          TTGTCGTTCCGGCTATGCGTGCGAGACAGACATTGGGGTAACTTAATAACATACGGCACG
          CCAACAGCCCCTTCGTGTGCAAGGCCCATGCGCTCTGTCGAATGACAAGCGCACTGAGTA
          ATGTGAAATCTTCACCGTGAGACCCATACGACTGTCGTGCAGCAGGCGATACACTGGGCA
          ACAAGATTGTGTCTATGCTCCGATTCTAATTATCATCAGCAGTGAGTGGCGACGTCAGCC
          GCCTGAGTTTTCTCGCGCGCCGGGAACGGGTGATGTGGACGTCCCGAGGCATCTTGGGCA

          TCTGTCGTATAGTTGCCTCCCAGGCCCCTGGGCCCGCACGCGTTAATTCTACCTTCCAGT
          CCCGTCGCACAGCTGCATTTCGCGGAACTTTGCCTTCACGCAAAAACCATATTTTTTTGA
          TAAATCAATTTATCGATCATGACGGTGACAGTTCCTGCTAGAGAACAACTGTATGTCGGT
          TGAATCATACCGCTGATGAGCACGAGTGGGATTCCCTCCTTAGAAGTATCTAGTTTGGAG
          CACATTGTTCAGAGTCTAGCGGGAGGCTCCTTCCCGCCCGTGGAGACTTAGTCCGCAAAA
          CGTGTCACCGAGATGTCATCCTAGGGGTATATCCTGTACGCCAGGCCCTTACTCGCAAGC
          TACCCAACATGGGAGGCGATCATGGGTTCCGTTCCATGACTGCAGGTACTATTCGATAGC
          CGTATCCTAAAGATACCGACCAAAGGCTTGGTATGGTACGGCGGATTATTTACCACCGGG

          GCACATCCTAGTATCCCATTGCGCACAAAAGAAGTGTCACCGCTCATGTTACACAAATCG
          GCACACTCTGGTGATCCATTGTGTGCAAAAGAACATATCTCCGTTATGGTTCGTCAATCG
          GCAGCGGTTTACATGCATTCGCTCGTACGGGGGAAGATGACCACAATACCCCGACATTCC
          GCAGTTGCTTACGTGATTTAACCGACACATGTGGTGGTGATCGAAACCTTCTGAGACTTC
          TTAGCTGGGATCCAGTTGTCCCAATCGACAGGTCACCGTATCGGCATTCTCTGGGGCGTT
          CCAACTCATAGCGAATAGCAAACTATAGACTTTGGCAACCTTATTCTTTCCCGGAGCGCC
          GTACCGTCTAGCGTGTCTTACGCACCAATACACGCGGCGTTCGGCGTCTTCTTGTAGGGC
          GCTGTGCACTGCAAATTATCTACCAAAACTCCTATGGCGATGGTGACATTCCACAGTCTC

          GCTGGGTAGGTAAATGAATGTGATCTTGGATTTTTAGTATCATATTACGCCCTCAGTTTC
          GCTGGGTATGTGAAGAAACAAGAGATCGAACTCTTGATGCCTCGTCTTGTCTGGTGCTGG
          GTCAAGTAGGCTGCAAAGCTCTTCATAGGGTTCTTAGGTCGACCGTCCTTTGACCACTTA
          GCAGCGTAGGAAGCAGTCGATCTTACTGGGCGCCTGACGTAGCGACTCTTATAGTGTTTA
          GGGGTATTGGTGTCGAAACATGGGAGTGAAGTCTCGAGGCACTATACCTAATGCGCACAG
          AAGGGAGTAGCATCAGGTTACGGGTCTGCAGCACCAAAGAGGTAACGTCGTTTCCAGTCA
          AAGGGATCTATACAAGCGCGAGCAACAAGGGGTACCGTGCGATTAAGTCAGTATATCCTC
          TGGGGATTGATAAAGGGTTCCGTGGTCAGAAGAGCGAAGAAGTGTAGTATCCTCTCTCAG

          GTACGATCCAACAATTAAATTGACCCCTCGCGTGCATCAGCGCGTAAGGGTCGCAGATAC
          GGCTGAATCGGCCACCACTCAGATCCTTTGTCTGTCTCTGTGCCTAGGGGCCGCAGTTAT
          GTTCGCGATATTCCGTTGTCAGAATTATCGGGATCGCCCATGCGCAAGGACTGCAGCCTT
          GTCACAGCTAACCACTGCTTGGGGAACTCGGCACTTTCCGCGCGTATAGGAAAAGGCCGT
          GTCGAAGCCAACTAGTCTCTTGAAATTTTGTTTCTGCCCCGGACAAGGTTATGGGCCGTG
          TTCGATGCGTGTCAGTACTTCGGCTTTGCGCCTATGTGGAAGCCTAAAGCGCGCGCCGAG
          ACAGCAGATAGCGGAGCGAGACTACTTCTGCCTTTGACAAAGCAAGGACCATGCGCCGAA
          GTTCGGTATCGTTGTAAACCTGTACCTGAGGTACAGGCTAAGCGTAGGGAACGTGATGGA

          TAAGGTCGCCTTCAAGCCTTATCCGAAGGGCATTTAAGTCTTCTCTAAGCAAGCGCGCCG
          CATGGATACGTTCGGATCCTTTTGCAAGGGAGGTACAGCCTCCTGTAAGGAAGCGAGCCA
          TACATAAGCCTTTAAGACTCAGGTCAAGCGTACTTTAGTCCCAGCCCAGGAAAGGTCCCG
          AGCGGCACACCAGATGCTTTGCTCAGGGGAAGGTACAATCAGTACTTGCGACCCGTATCG
          CCTCACGCACTACTTACTGGGCAACCTGCATCACCTACTCACTACGGACGACGCATCTTG
          TGCTGAGCACCAACCGCCCTCCTATGTATAGAGCCCGTCCTCTACAGCCCGTACGAGAGG
          TACCATGCATCACGGGGTCTGGACACCCAATAACCCATTCTGGGTGACTGGTAAAATTCG
          TTAGGCGCGTTATTGATTACACACTATTGCTAACCGAATCCTAGTAGAAGTCACGTACGG

          CGTTACGACGACACTAGATGACCGTAAGCCATTGGCTCGCAAGCTTTTTGAAGAGACAGA
          TGTGGGAACGGCATTCAAAAATGATGAGGCAATCGTTTGAATGTTTATCAAAGGGACCGA
          AAGCTGGACGTGGCCTATCGTCTATGCGAGACAGGTCAGCGGGTGCAGTTAGAGGGGCGC
          GATTTGCATCCGTTCTGTACACTGGAAGGGACGGGTCTGAGGGACCGATACGGGGACAAC
          ACTCAAGTCTCGACCTTCTGCGTAGGCTATATCCGTCTGAAATCATGAGGTGGGGACCAT
          ATATACATTATTGTCCATTAATTTTATGGCGCTATACCGCCAGCAACATAGCGGCATCGC
          ACTCGAGTCTAGGTTTGCCAGCAGGGAGGTGCCGGTCGGAAAGAATTTGAGGAGACACGC
          GCTGGAGGCAGCATACTCCAACTAGGTAGCCACTGTTGATTAGGTCACCATTAAATTCAC

          AATAGGTTTGTTCTCAATACCAAATCAACCTCAATGTATCCACTCGGTTCTACGAATCAT
          ACCGGGTTCAAACCCTGTGTCATATTCACTGTAATGCACGTGCTCGCTCGGACGCTATAT
          AGACTTTCTTCCCTTTGTGCGGGGATGATCGCAAACAATCTTCACGCATAAAGCCGCTAC
          AGAACTTTCGCCCCGTCTGCACAGCGGATCTTAAACACGCCCACAGCTTCTTGAACGCTC
          GGCTTTCCAGACAAATGCGCAAGCCTATTCACTATGACATCGTATGTTGGTCCCTGATGG
          GTTTAGAGTACGGGTCGCGCTTTGTCTGCAGTTGTATTGGCTCTAGTTCATATGTAATCA
          TAAGATCCCGTATAATGCGCCAGGACTTCTCACCGTTTGATCCAAGCTTCCCGGGGACAC
          TGATAGCTGTCCCATCGTGCCAAACGCTCCACAAGTTTAGCACCCATCTTTAGATGAACA

          TGCGCGGCCGGTCGCGGGGGAACTTAACAGATCGTTGCGAAAAGATATATGCGATTTCGA
          GAAGCGATCGGCTGCAGGGGGTACCGCCACACTGTTGAGAATGCTCTCCCGCGATGCCTA
          AAAGTGGCTGAATGTGCGTGCAGTCTGAAGCACAACCTGCCCCGAGATATATGATTTTTT
          ATGGTAGCCACCCGTGGGCGCAATCCGCAATTCGCCAGGGCAGGGTTTAAATAAAATCCT
          GGGGTGGGCCATGGCCAGCACTTGTTACGATCCGAGCGTCGTAGCTTTCTGCGGCAACCG
          AGCGTAATTACTTGACAGGACTCCCCATGCTTCGACGGTCACAGCATTCAACACTGTCAT
          AGGTTATTCGGTATTTGGTATCCTCAGCGCTAGTGCGGGTAGGATCATATACAATACGCA
          ATAATGGCCGCTACAGAGGCACCCTCGGGTCCCGTAGGTTGATACCTGATAGGTCGTGTT

          CGCCCGCGACGTTGGTCGATGTCTCTATTACACTGTGAAA
          AGCGCGTAATCTATACCAAGGAATTTTCTACACCGTAAAG
          CGTGTGACACGATTGTCCAGGAACACTGTAATTCTCGCAG
          AGCTCATCACGGCCAATCGGGTTCCCTTCTATACTCGTAC
          CAGTAGTCTCACACGAGCAGAGTTGCGTTTACACTAGCCC
          GTCCGCCCACATCTGGACTAGTATCCCTATCTCTTCACCT
          TTAAAGGCCAGCTTTACTAGGCTACTCATCACTTTCGTTA
          CCAGAACGACCCAGAGCTTAGTTTACGGCCATCGGTCCTC

