 8 1000
t1        CTATGCAATGCTAACATGTACGATATGACTTGCCAGAGGTACCCGACTCACTGCTTCGTC
t2        TCATATAACGCTGACATACTCAGTTTGACACGACACAAGTATGAGGCAAAGTGTTTGGTC
t3        TTCAGTCAGGCTAACATAAAAGATAAAGGTCGCTACAGGTACCTGGTGCATTGCTTTGTC
t4        CACTGTAGAGATGGGAGAGGCGGTATAGCAGGTCGTAAGTGTATTATGCCTTGTAATGCC
t5        CTATATAGCGTTGACAGATGCGATGTGATTTCACGTAAGCGGCTGATCCGTTACATCGTG
t6        TCGCCTAGTGTGAGCAGATACGAAACCCCTTGCAGCGCATGACTGACGCCGAACTCGCTA
t7        TCACGTAGCGTTAATAGTCATAGTCCCGCCCATTGCAGGTGCTCGAGGTATAGCATAACC
t8        CAGTAAACGACTATCGGACTAACAATTAGTCCTATCAGGTGTTCACCGGTCCGTTTCCTA

          TCGTTGCGAGTCCGATTTCCGGAAACGTTCATTCGTCAGTGATCTAGAGTGAATGGCCAG
          TGCCCGTGGGTCCGTTTGGCAAGTACGTTCGTTCGCTAATTATTCGGACCAGAGGACAAA
          TAGTTGTGGGCCCAGTTTGCAGGCAGGACCTCTTCCTTACGATCCGGAGTAAGGAACGGG
          TGCTCGCCGGTCCAATCTACCAGAACAGTTACTTGATAGTGAACTGAGACAAAAGAAAGA
          CACTCGGAAGTCCTGATTATGTGCACGTTCTTCCAATCGCGTACCGGCTCGCAGGAGGGT
          TGCTCGGCGGGCCGAAACGGGATCACCCTGACCTGTTGACTAATCGGGGTGATGGCGGGA
          TATCTTCGTAGGCAAATTGTAACCACGTATAGCCGGCGGTCAAAGAGAGTGACGGAGAGT
          CTATTATTGATTCAGTCTGGAGATCAGCTCCAATCCAGTTAATAGCATGCGTTGGCGGGA

          TCGTAGAGAACGATCCGATCCGCGACGCTTTGCGCACATGCGGTGTCCTCCGCGTCCATG
          ATCCAGAGAATAGGCCGACCCGCGACATTTTGTCTACACAGATCGCTCTCCGTGTCCATA
          TCATAGGGCTCAGACCAATCGGCCACGTTCTGTTTGCACCGGTTGTTCCCAGAATGCACG
          CCCTTGGCAACTGAATTACTTACGGCATTTCGTATGCACACGCGGCTTCTCGGACGCTCA
          GTGATGTAAGAGATGTAATCTACTACACGCCGTCTGCGCATGCCACTTTCCTGGTCTATA
          CCACATAAAATAGTCTAACTCAGTACGCCTTGTGTGTGCGAATGAGTCTGTGGGTGAACA
          ACCTCGAGGGGGGCCCGATCTTTAACATCTTTCTTGAGCATCCGCACTTGCGGGTGTAAT
          TGATAGCAACCAAAACAGTCTATTAAATACTACCGATTCTTTATGTCTTTGTAGCCCGGA

          CCCGAATCACTTACCAGTTATATCCTAGAGTAAAAAGAGCATTAAAAAGTAATATTTTCT
          CCCGCACCACGTGATGAGCACATTGCGGCGTGAAATCTGCGCTAAAGACTTATAATCTCT
          TCAGCACCATGTGAATAGTACATTCCCGCGTACAATGTGCGCCACGGGACGGTTTTATAT
          GTAGTATCAGCTGATCAAAGTGTTCTCGTCTGACCTATTATCAAAACGATGGCGTTTCCA
          TCCGCACGACCTGACGAAGATCCACAGGCGTGAACCGTACTCTGAACGACCGCTTTCTAG
          TCGGTATTACCTGATAACTATTCTTTCCATTGCATAACGAGCTAATCGAAGAATTTATTA
          TTCGTACTAGTTGATAGCCATACTTAGGCATTTACTCTAAATCGTCCGACGACATTTTCT
          ATTGCAGATCAAAGTGTTCGCGCCCGGACTCACTCGATGAGTGTCCGGAATCTTCAGATA

          CCGAACTGATGAATTCATTGGATGGACGATCACACTGGCAACTGAAAAACGTCAGGCACC
          CCAAGCAGGGAGAATTGTCAGGAGGAAGATTTCACTTGCAATTGATAAACGCCAGATCCC
          TCGAGCTGCGGAAACTGTCGGGTGGATGATTACCCTCACAATTGTTCAGTGCTCCGCATT
          CTGAGCCGTGGGTATAATCCAGCGGCTGGACACACCTGCAATTAGAAATGGCCAGGTACG
          CCGGGCTTAGAGAGTTACAACGTGGCCGACTCTACTTACAATCGAAAAAGGCCAGGTACC
          CCGGAGTGTGCGACCTATCCAGCGACTGCCCATCGTCACGTTTCAATCTCGCCAGAGAAC
          CTGGGTTGAGGGAATCGTTAAGGGTACGACCCCCCCCCTAAATAGATTGGGCACTGTGCT
          CCATGATCCTGATGACATCAGGCTGCCTGTCGTATTTGCTATCTGACCACGCTGAGCAGA

          TCGGGACGCTCGACGTTTATCCGGTGGTAGGGTATGGCACCACGATGTCCGATAACTTAA
          ACAAGATGCTCGGTGTTCAACTAGTGGCAGAGCATCACATCACCACGCCTGGCAACTTGA
          ACGGGGCGCTTGGCATTTATTCAGTAGTATTGTAAGGCCCAACCATGATTGGAACTCATA
          ATCGTTCGCTCGGCGTTTATTTAGCACCATAACATGAAACCATGATGGTCGGTATCCTCG
          GGGACCCGCTCAATGTCTGTTTAGTGATAGAGTATGACACAATCATTTCCGACATCCCTG
          ACGACCCGTTCGGTATCTATTCAGTAGCATGGTACGACAGCACGACATTTGGGAAGACTG
          GTAGGCAGCCAGCCGCCCAATTAGTAGTTGAGTTCACTGCCATCTCGTCCAGATTATCCG
          GGGCCATCTCGGATGGTTGCGGTAAACTAAGGCAGTAAACTAGTTTAGAACCTTTATTTA

          ACAGAACTTCAAATCGTGGACCGAAATGACTAAGCCAGCGATCTGAGAATCGCGTGAGAC
          GGGAACCCCCGAGCTGTGAGCAGTAGAGGGTAAATCGGAAACCTAGAAATCGTGATCGCT
          GAGGACGCCCGAACTATGGAAGAAAGCGACGGGGCTGACGATCTGTATGGCGCGAGTGGT
          GCCATTGTCCGAAATGTAGTCTACAGAGTCTAGGTAGGCAACTTGTAGGCCGTAGAAGAC
          ACCTACGTCCTGGCCGATGATCGTAATAACGAGGTAGGTTGCTTGTAAGTCGCGACAGAT
          GCACATGCCCAAACTGTAGACTATCATGTCCAGACGGTTGACCCGGAGGTTGTCAGCCGT
          ATAGCTGCCTTAGCCCTGGATAGATGAGTTTGGGACGGCGACATGTCGGCCGCAAGGCGT
          TGTGTACAATGTAATGCGATGTAGACGGATCGGAAATACACTGTGCGATCTGCTGGAGAT

          AACCTATTATGTCGTCACCTTCTAGGCACTGTCGGATAAACACTTAATAACGACGGCCGT
          ATTGTATTCAAGGGTCAATTTGCCCTCGCCAGAGTTAACACGCTCCCAGAGAACGGCAGT
          AATTTATTTAATGGTCAGGCTAACTTTGCTGCCGACCGTACCGCAAAATACGACGGCGAC
          AAAGACTCAATTGGGTTATCTGTTCCCGACGGGATGTGTATACTTAGAGCCGGAAGTGGT
          AATGCACCTAGTGGCTTTTTCTGTTCCCTCAAAAAGTACACATCTAAACACGATGTCGGA
          CAAGCACCTAATAGTTTACTCACCCCTGTCGCCTTACGAACACTCAAAATTGATGACGGT
          AGTACATCTAACTGTCCGTCCGCTATTACCGGTGTGCACTAGATTTGAAGCGATGGCCTC
          AATAAGCCTGTCAGTTTGATTCGTTATTATGTGCCAAAGTGAGTTCTTAGATGGTTTAAC

          CCTGTTAGCTGCATTGGGCCACCCGCCACCCTTCAATAAATCTAAGTACCGCTGTCATCG
          AGTGTCAACGACATGAGGATGCTTGTCTCTTTCTAATCAATCTAAGTATCGCTACGTTTG
          TCCGTCAGCTACATGAGGAAGCCTGCCTTTCCCCAATAGATTTATGCATCGCTACGATCG
          TCCGTCTCAAATTTAACGATATCATTTTCCCTCCAGTGAATCCGAGCATTACTATGTTCA
          TCTACCCAAGACACGCGGATGCTAGGCTCCCCCAAGTAAACCATCATTTTTCTACGATCG
          TCTGTCCGAGGGATGAGGATGATAGTACTACTCCAGTGTATTCGTGTCTTGCTACCGTCT
          TTTTCTATAGCTATCAGGACGCCGGTATTACTTGACTGGATCCATGTCTCGGTAGGGTCA
          AATGATGTGAACGCGCCTGTACCAGGACCTTAGCTGTAAAAATCCCCGCGTCTGGAATGA

          TAAACGCTCGTGCAAGCCTAGATACAACCGGTACACGCACGTCCCCGGGTACGACACAGG
          CGGGAGACCCCGCAGCACTAGATACCAGTGGTACAAAAACGTCCCAAGGCACGGTACAAA
          CCTGCGACCCTGTAAGACCGGACCCAAGTGGATCAGGAACATCCGATGGTACGATCCAAA
          CGGATAAACCTAAGAGGACACCTAGATCAAAGACCGGCGGATCCGAGAGTAAGATCTACG
          TGGTTGACAGTCCGAAGCTACATATAAACTGCACTGGCCATTGTCCGAGTGCGCTCCGGC
          CGGTGTACCTTACAAGAAGAGGAGCAATTAGCACTGGCAAACCCTTAAGCACCAGCCGCA
          CAATGACCCTTACGTGACCACAGCCCGACAGTACTAGCAAGCTTCACAGTATGATTCGGG
          CAAAACATAGTATGTACTGAGTCTCAAATAGGTAGGCAGGCCTTCACCACATCGTAGGGG

          TGAGCCGCCAAACGGGGGAGATCTACGTAAGCGGGACGCAAATCATTACACCAAGTTGAT
          CGTGCAGCCATGGGGGGATACCCTCCTTAATCAGCAAGCCAGCAATTATGTAGTGCTGAC
          TCTGCCGATAAATGGGGGTGCACCTCGTAGGCCGCACGTCAGTAACTATGCAGAATCGAT
          AGTGATGCTAAGCACAAGTGTGCACAATAAGTGGTACGCTAGCAGGCATGCAGCGCTTTC
          CGTGTTAACAGAGAGGGGCGCGCTTAATGAGTCATGAGCTAGTGTCTATGCGTAGGCGAT
          CGTGTCGTCCCAATGGGGGACGTTCGATAAGTAATACGTCAGTGGCTAGTCAAAGTTTTC
          TCTGGTGCCCCAATGAGGCGTGCCCATTAGGCGTTACGTCACGGGGTCTCCAGAATCGCC
          CAGGCCGAACCGGGCAGATACGGATCACATGCATCGAATAAAATTCCATGTAGGAAAATT

          GTTGTCACTTGTCAATTATCCCACCATCGCGGTGTGTGACGCGCGTAGTGCCACGACGCA
          ATTAACAGTTGGTGTCTGTCCCAACGATGCAGTGCGCGATTCATGTGATGCGATATTGCA
          ATCAACACTTCCCAACTATCTTATTACCGCAGTATGCGACACGCGTGTTGCGGGAACGCA
          ATCAACGTTCGAGAAAAGTACTATTATCACAGCAGTCGACCCATGACATGCGGTAGTACA
          TACATCATTTAACTAAAGATCCCCCAACGCAGTCTCCGCGTCGGGCCGCGGGACAGTGTA
          GTAAATCATTGCTAATGGTGCCACAGACAGTCCGTTCGTCTCATGAGAGGTGATAGCGCA
          GGTGACAACCGTTCCCAGAGGTGCTTGAGGGTCGACCGATCCCAGAGGTGCCATAATCTG
          ACCACCAATGTGTATTAGAACCATATCTGGTTCATTTGCCGCTATCCTCGCTATAGCGTG

          CAAGCCGCTAACCCACGTCCCAATATAGCTCCGTTACCTTAGTCCGTCATCCTCTTCACA
          AAAGCCCCCACTCCAAGTCTTGACATTGCCCCGCCTCCCTCGTCCCTTACTCTCTTTACT
          TAATCTGCCGCCTCGTGTCTTTACATCGCCCCGTTGCCTCTGTCCCTTACCCACTTAGCA
          CCACTAGCCCCTCCAGGCGTTTAGACTGCCCTAATATCTCTATAATCGATCCCGACTAGT
          CTGATCGCCACTCTGCTTGTTAGCGTCGCTTTGCTCCCTCTGTTAACCGTCCTATTTGCA
          CGTCCTGCCACTACATGTGGCGTCATTGCACTATTCCCAATGTTCTGTCTCCCCCCTATG
          CCTTTTATCGATTCAATTGTCGATCTCGCTCCGTTGTTTACTTCTACAATATCCCCAATA
          TCACACTTTAGACCACATCGCAACTTCAGACAGTCAGCCCCTCAGTCAGAGCAACTCATT

          GGATAAGACTCATAAGTACTCCGGGCTGCACCGGCACGTCCACGGTGTCCGCCTTCCCTA
          TGACAGGATTTAGAACCCTCTCAGGCCTTACCGGCCCGTTCGAGTGAAAAGTCTACTCAA
          GGGTAGGACCCGGGATCTCCTCGGGATCTGGCGGCCCGTTCGACTGGTTAGCCACATCTT
          GGGTGGGGCCTAGAAGATCCCCAGGCTCCAGTGCCTTGCCGGACTGGTGAGACTTATCAA
          GGGAGGGGCTCAGACCCTCCATGTGCCACAGAGACCAATTCGAGTGGTTAGTCTTTGCAT
          GGATTGGATTGAGAGCCTCCTTGGGTTTTTGTGTTCAGTTGGAGCGGCTGGACTTGCCAG
          AAATTGGAGTAAAAGTTCGTTTGAGCCTAACTGGACCGCCTATATGGCGTATTTTTCTAA
          GAAAGTGACACACATATCTTTCCAGTCATAGCGAACTATTGAGATGTCTCGTAATCTCAC

          CCTCGCGAGAGGTGCTTGTCCGGACAAAACATGGAATGACGTAAGGTATATTCTTGGTGG
          CTTTGGAAAACGTGCTCATCGCGATTAATTTCGGGTCGTCGCAACGCAGACCTTTAGTGG
          CTTTGGAAAAAATGTTTATTGTGACGAACTAAGGAACGACGTACCTTAGACTCTCAGAGG
          CTCTAAGTAAACTTATATGTATAACGAACCGTGGAACGACTCTGCGTGTACCGTGCATGA
          CGGAAGACGATCCGTCCAAACTATGGAACTATGGGATGCCGCTCTACAGGCTGCTCGGGG
          CTATAACAAATAAGGCCATTGTGACATTCCTTGGAATGGTGCTTTATAAGTCAGCCTGAA
          CGCTGGAAAGCCTGTCTACTTAAATGAGTTTAAGAACACGGCAGCGCGCCTCTGCAGGGG
          ATTTACTTATAGCCATTCTTGGGTTGACGAATGGAACTGCTTGACAGTCATTAAGCGGGA

          GTTAAAGACCGCATCGTCGCCTCACCGCCGCTCAAGCGACATCCTGCCACTCCATTTTGA
          GCTAAAGACCTCACCATTGTACTCCTGCACTTACCAAAGCACTTTGCCACTCGTTCTCGG
          GTGCAGAAACTCACCGTAGCTACACTGCAGTTAAATGAGTGATCTGCCGCCCGATTTTGG
          GTGAAAGTGTTCTCTGTAGCTCCTCGAAAGTTGAGGAAGCGTCTTGCAGCTAGCATCACG
          GTCATAGACCTAACTATTGTCCCATTGTAGTCAAGAAAGCGTTTTGCTGTCAATCCAGAT
          ATCTATAACTAGATCGTTGCTCTGGTGCATTCCGAAGATCACCTGGCGGCTCACTCATGG
          GCAGAGGATCCTAGCTTTCCTACGCGGGAATTCGGACGGCGCTATGCCGCTCGCCCTTGT
          GTCAAGCACTCCAATGGTATTAGCGGGCGGTAAGTACACAGCTCGACCGCTACATTTCGA

          TCAGACGGTTCGCCCCATCTACCCGTGGTACGATCTCGAT
          TCAGAAGGATAGCCCAGTCATACACTGATTCAATCTAGGT
          TCAGACAGGCCGCTCAAGCCGTCAATAGTTCCAACCGGAT
          ACAGCCGGTGCGTTGGATTTACCGGCAATATGACGGGGAC
          TCCGTCACACCGCTTAGTCTGTCAACGGTGTCATCTGGGC
          GCAGGCAGACGGTTTGACCCGTCAACAGAGTAAGGTGCAC
          AAAACGGGACTGCTTTACCAGTCCACTGTATAGCGTAGCC
          CCGACGGAATCGTGATAACCTTGACCAAGACCTGACAATA

