 8 1000
t1        CCAAAGAGCGGCTTAGGGTTTGTGTCGTAAACTCTTTAGCTACGCGTATGCCTGCAGCAC
t2        CCAAAGAGCGGCTTAAGGTTTGTGTCGTAAACTCTTTAGCCACGCGCATGCCTACAGCAC
t3        CCGGAGAGCGTCTTAAGGTTTGTGTCGTAAACTCTTGAGCCACGTGTATGCCTACGGCAC
t4        TCACAGAGTGTCTCAAGATTTGTGTTGTAAACCCTTTAGTTACGTCTACGCCTATTTCAT
t5        TCAAACAGCAACTTCACCCATATTAAGGAAATAACTCAGCAGCATGCGCTTTTATCGGGT
t6        TTAAAGTTACATGCAATTTATGTCATGTCGATTCCTTAGTAGGCTGCAGGTAACCTATGT
t7        CAATCAAGAGATCATTCGACCGGCTAAAAGCTCCCGTTTGGGTGATACCATATATTGCAT
t8        GTTATGTGACACTGTAGATCGAATGATATACGTCAGTAAAGGCGGACATACTGCGTATAA

          TCTACACGTGGACGCTTCAGGACACATCAATATCCAATATCCGTACTGGTATAATAGGTG
          CCTACACGTGGACGTTTCAGGAAACATCGATATTCAATATCCGTACTGGTATAATAGATG
          CCTACACGTGGACGTTTCAGGACACATTAATATTCAGCATCCGAACTGGTATAATAGATA
          CCTGTACGCAGACGTTCCAGGACGCATCGATCTGTAACATTCCCACTGGTTCGATAGATG
          CTAGCGCGTCGGAATTGCAAGATGGTCCGCCGTATACTGCCCGTAGAAGTGTTTCTGATG
          GCAGCATGCGGTTATACCAGGATCTTACAATGTATGTCACTCGCTCTAGTATCTCTAATG
          CACGAACATTGGTTTATTCCTGTTGGGCGATTGACACTATGAATGTGCCATATGTCGTTT
          TCTGCTAACATAGTCATCGTGTGCAGCCGTCTTACGAGAACTGAGTGCGAACTTCCGTTG

          GCTTTGACGTATTCCTTGTCTAGGTCGACTCACTTCGTTAAGGAAATCAGTCCTCTACAC
          GCTTTGACGTATTCCTGGTCTAGGTAGACTCGCTTCGTAAAGGAAATCAATCCTCTACAC
          GCTTTGACGTATTCCTGGTCTAGGTCGACTCGCTTCGTCAAGGAAACTAGTCCTCTTCAC
          GTTTTGACACATTTCTGGTCTAGTTTGTCTTGTCTCGTTAAGAATACCAGTTCTCTTCAA
          GATCCAATGCATCTCTGGCCCAGTTAGCCCGCCATCCCCAGGAGCGCTAGCCTTTATAGA
          GCTTGCCCGCACTCTCGGTCTGATCCGTAGGTCCCTGTCATGAGTATTAGTTCATATCAG
          CTACTAGTATAACCCAAACGCTTATGGCCTGCGCTCGTAGGCGGTCCAACTTAGTATGGG
          ACAAAGCGAAGGGTTGACCTTTGTTGTGGGATCCCCGCTCCCGCCGGTACATGAAACCAC

          CATGATTCATGGCCCAAAAACATCAACCCCGCTTACGATGCAGAACGGCAACTGTCTATG
          CGTGATCCATGGCCCAAAAACATGAGCCCCGCTTACGATACAGAACGGCAACCGTCAATG
          CGTGATCCATGGCCCAAAAACATGAGCCTTGCTTACGATACAGAACGGCAACCGTCTATG
          CGTAATTCATGGCACAAAAATGTGAGCACCGATGACGATACAGAACGGCAATTATCTACA
          CGCTAGCGACTGTGATCCGACTTAAACATGGGTATTAATGCTAAATAGCAGTAATCTAAC
          CGTTATCCACGATATAAATATATGAGCATCGGTTACATTACACAACATCAATTGCCTGTG
          CCAGGTTTTGACCCACACGAAGAAATTACCAGAAAGAGCATTCGCTCGTACTTACGGCTA
          TCAAACTCCCCTATACAAAACACGGGTGGCCTAACGCGCCTAATTCCTCAATTGCTACTG

          CCGCAAGTGGGAGGACGATGGGTCTCGGCTGGTGGCATACGAACGGCGTCACTTAGCTAA
          CAGCAAGTGGGGGGACGATGGTACTCAGCTGGTGGAATACGAACGGCGTCGTTTAGATAA
          CAGCAAGTGTGGAGACGATGGTTCTCAGCTGGTGGAATACGAACGGCGTCACTTAGTTCA
          CTGTGAATAAGGGCCCAACGGTTCCCGGTTGGTGGAATCGTAGCACCTTTACTTCGTTAC
          TAACATGATAAGATTCGATGGTTTCTGGCCGGCGGAATATTACACCTTTCCTCTGATCAC
          CGACGAACAAGATTTTGAAGGACTTAGGTCGGCGTTAAATCAATACCCTCGCCTAGTCAC
          CCGTAAGAGATGGTCCCAATGGGTTTGTCCAGCTCAATTCGATCCCTATGGCTTAACCCC
          CCGTAGTGAGCTTTCTGATGAAGCCCACACTACGGGTGATTTGCTGACGCAATCTTAATC

          GTGATCCCGCGGAAGTAACCAATGTTTGCATTCCCCAGGTAGCTGTAGTCCTAGTTATCA
          GTAATCCCGCGGAAGTAACCAATGTCTGCATTCTCCACGTAGCTATAGTCCTAGTTATCA
          CTGATCCCGCGGAAGTAACCAATGTCCGCATTCCGCAGGTAGCAGTAGCCCTAGTTATCG
          GTGGTACCGCACAGACGCCCAATGTTCGCGTCACCTTGATAGCCGAAGATCTAGTTATTG
          ACAATCAGCCGCAGGTCCCACATTTGTGAGCGAACCGAGTCACCGAGGTTTTCTTCTACG
          GGGTGTGCGGTACGACCTCGAACATCTAGGCGAATCATTTCGTCAGGACTTGGATGCGCA
          GTGAGTTGGCCTACATGTTCCGTTCCTGGTGCTCGTCCATACCTACGGGTCTTCGTGGTG
          TGATTGGGGCTCGAATCTCCTGCACTCAGACGGAGTTTATTACCAAAGTTTTTAAGCGCG

          ATTCGCTATTCCCGGCCATGCAACCGCTGGAATTCATGATATCCGGAGCGCTTGGGCCCC
          ATTTGCTATTCCCGGCCATGCAACAGCTAGAATTCATGATATCCGGAGCGCTTAGGCCCC
          ATTTGCTATTCCCGGCCATTCAACTGCCAGATTTCATGATATCCGAAGCGCTTAGGCCCT
          TATTGTCGTTCCCCGCCATATGCCAGCCTGAATTACCAATGTTCGGGGCGCTCAAGCCTC
          GGTCGCAACCTGCGAGTACGCTACGACCCGTATATACGAGGGCGCAAAAAACGCTGTGCC
          TGTTGCGGCTCGCGAGCCTTCGACACCCTGAGTTCGCGACGTCAAGGCGGGCGTCATTTG
          GGACGTATCTAGCGACTACTGCACAGCAAAGTATGTTAGAATCCCACGAGGTGCTCTGCT
          AGTAGCGTAAGGCGATTGGTGGCCGCTTCCTGACTGGGTAATAAGAGGAACTCTATTACT

          GTGACATTCTGATACTACTGCGAAAAACTAGAATGTAGTGGGCTCCGGACACGTAAACAG
          GTGATGCTCTGATATTACTCCGAAAAACTAGAATGTAGCGGGCTCCGAGCACACAAACAG
          GTGATACTCTGATATTAATCCGAAAAACTAGAATGTAGAGGACTCCGGACACACAGACAG
          GTGATACTGCAATATTATTTGGAAAAACCAAAGCGCAAGGGGCTCCAGACAAACAATCAG
          GCATTGGTCTAATATGATCCCGGGAAACCCAAAAATAACAGAGCACGGTGAAACGATTGA
          ATGTGAGTCTTCTGTAAATGTGGCGAACTAGGAGGTAAGTGACTCAAGCCAAATTGACAG
          GCACTAATCCATCACTCGCCCTTCAACATCTAAAGCTCAAAGCGTCGGTGACACGACTAT
          TAGCAGAGATTACGCTATCTCACGTAGCTTTCTCACTTTCAACACTGGTGATGTAATAGT

          CATGCCTCCGCATTGCCAGCACAGTGGCCGTGAAATCTGGGACCCACCCAGGCCTGTCCT
          CATGCTTCCGCATCGCCAGCACAGTGGCCGTGAAATCTCGGACGCACCCAGGCTTGTCCT
          CATGTTTCCGCATAGCCAGTACAGTGGCCGTGAAATCTGGGACCCACCCAGGCTTGTCCA
          TTCACCTCAGCACTATCAAGACAGTCGCTGTAAGATCTGGGATCCACCCAGAACTCTTCT
          TCCATCTACAAACCTTCTGCACCGGTCATGGGAGTCATTTGAACCCCACATGGCTACGGT
          TATACTGTTAAATCGTACACACTGTCTACTCATACTCTGGGAACCGCTCAAAGTTACGGT
          AATGCCTCTTTCTAATCTATCCCTCCCCCGCGGAACCTCCAGAGCTCCATAGTGTAAAAA
          TTTAAATTCCCCTAGTCGATCCTCTCCTCGCCTAGACGAATGGACTATAAAGGTTGATGC

          GACGGTGTCGAGCTCACATGTTTCAGTCGCGACGCTCGTGTCCTTATGCCAGCGAATCTG
          GGCGGTGCCGAGCTCACATGTTTCAGCTGCGACACTCGTGTCCTTATGCCAGAGAATCTA
          GACGGTGCCGAGTTAACATGTTTCAGTTGCGACATTCGTGTCCCTATGCCAGAGAATCCG
          TCAGACTACGAACTCGCACGTCCTTGTAGCCACACTCGCGCCCCTTCACTAGAGATCCCG
          AAAGACGCCGACACCCCACGCCGCAAAGGGTCCATTAGTGTCTAGCCATAAAGGTGACTA
          TTTGGCGTGATTGTCGCACACCGTAGAGGCGACGTCCGTGGGCCTCCGCGTGGCTGTCCG
          TATGGTACCAATCTTTAACGCCATCGTATGTATGCTTTGAATTTGGCTGGATGATACCTA
          AGATGATCCGCTGAAGGCGGGTGCTCTAAAGGAGCCCCAGTTTTACTGAAGGAGCTTTCG

          AGTCGTGAACTGAACGTTGATGACCTCGTACAGATCACCAAATTGGGCCCAATCATCCAC
          GGTTGTTAACCGAACGTTAATGACCCCGTACAGATCACCAAATTGGGCCCAATCATGCAC
          AGTCGTGAACCGAACGCTAATAACCTCGTACAGCTTTCCAAATTGGGCCGAATCATGCAC
          AGTCATGAACTGATTGTGGGTGAACTCGCTGGGACCACCCAACAGGGCCGAACCGTGCCC
          CGTCACGTATCGAAAACCTTTTGGCCAGCTCAGTTCAACTAATTGTGACGTACTAAGCTT
          AATCTTGCATCGTGCGCGAATAGCACAATACCGACGATCAAATCAAGTTGAATTCAGCTC
          CCTCTATTATCCAGTATCGATGGCCATCATCAGACCCGTGACCTACGTTGGTCCGTACTC
          TGCTAGGGTGCGAGGCCCTGGATGATCGTGCAGAATATCCGAACATATTAGGCCGAACCG

          GTCGCCTGCAGTTCCGGACTTTAGAAAGGTATCGACGATTTGACGTATGCCCGTCCAATT
          GTCGCCCGCAGTTCCCGAACTTAGAAAGGAATCGACGACTTGACATATGCCAGTTCAATC
          GCCGCCCGCAGTTCCCGACTTTAGAAAGGAATCGACAACTTGACATATGTCAGATCAACT
          GCCACTCGCGGTCCCTGGCGTTCGCCAGAAATCGCCGGCCTAACATATGCTAGCTTAGCT
          GTAGCGCGGCGGCTCTGTCATACGCGAGAAGCAAACAACCTACCGTATGCTAGCACAGTT
          GTATTACGCCGGATACGCCATCCAAAAGGAACTGACAACTGGACCTACGATAGTTTTACC
          GCTAGGCACAGTGTTCGTTCTTCACAAGGATTTCAGGGCCGCTCGGGCGTATGACAAAAT
          TGCCTACCCAGACTGTATCAGCGACGAGGAGGTGACGCTACAATCGACAACATGCATACC

          TCATTCATCGGGGAGCAAAAAGTGACCCAAGACGGCCAGCTCGCAGGGGCGTAATGAAGG
          CCACTCATCGGGGAGCAAAAAGTGACCCATGACGGCCAACTCGCCGGGGCGTAATGAAGG
          TCATTCATCGGGGAGCAAAAAGTGACCCTAGACGGCCAACCCGCAGGGGCGTAAAGAAGG
          TTATTTATCAGAAAGTAAAAAAAGACCTACGACGACTAACTCGCAGGAGCGCTATGGAGG
          TTACCTAATAAAAAATGAAAATAAGCTCGCGACCAGGATACCGCCAGTTCGGAGTTGAGG
          CTCTATTACAAAAGTTACTTACAATTATGAAAAGATTAGGCTGTAGCCGTGATGTGTAGG
          GCTGGCAACTAGACGGAAGTACAGGAACGTCCAGGCAGACATAAGGATATTATACAGGGG
          AACTTGTAGAAGATCACGCCGCAAATTCGTTGGTGCGAACCCGGAGAACTGTTGCCTGGA

          GAAAGCTTTCTACTCCTTTTCCGGCCCGTCTCCAATGCTCGTACAACCCATGTTCATTCA
          AAAAGCTTCCCACTCTTTCTCTGGCCTGTCTCCAATGTTCGTACAACACATGTCCATTCA
          AAAGGCTTTCTACTTCTTTTCTGACGCGTCTCCAATGCTGGCACAACCCATGTTCATTCA
          AAAATCTTTTCACGCCCCTTCTGGCACGTGTCAACTGCTCATACAATTCATGCTCATCTG
          GTAAGCCATCCAGTTCATTTCGCCTACACATCCACAATTGATACACTTTTAGTCTCTCTG
          GTAAGCCATGTACCTCTATTCACACTCGTAGCTAATTCGGACCCAACCCGTACCTATCCG
          ATGAACCACAGTTGCGATCCAAATTGCCATCCGTATGATAGCCCTTCCCTAACTAGAGTA
          AGAGGTTATCCATGTGGTCGAAAAATGGTCGTTTGTAGAGGTAATGACTTTTCCAGCGTT

          AGTGATCTCAGCTTGGGTTGGATGTGTGTTGCCCTCATGTGAAGAAGTGGTTTTCACTGC
          AGTGACCTCAGCTTGGGTTGGATCTGTGTCGCCCTCATGCGAAGAAGTGGTTTTCACTGC
          AGTGACCTCGGCTTGGGTTGGATGTGTGATGCGTTCATGTGAAGTAGTGGTTTTCACTGC
          GATTGCGTCAGTTTGAGTTTGATGTGAGTTTCCCTCATGTAAGGAAGCCGATTTCATTTC
          CCTGACCTCAGAATAGGCTAGTCTAGCGCTGTTGGCATATATGGAAGAGAATGAGGCGGC
          GTTAGCAGCATCACAGCTTGGCCGTGGTTAACTCACGCATGCTGAACCACATTATACCGT
          GTTGTTCTCAGGTTACTAGCGCGAGACAGTTGCTAGGGGCACCCGCGTGCGTCGCGGCTA
          GTTAACAGACCCTCTCCCATGTCCTTAGTTATCGATGTAGAAAGCGGGGTCCCGTCACAT

          AAATGCCCATCAGATGTCCAACTGAGCTCACCGCGTAACAAAGGCATGTATACCCGCATA
          AAAAGCCCGTCAGATGTTCAACTGAGCTCACCGCGTCACAAAGGCATGTATATCCGCATA
          AAATGCCCGACAGATGTCCAACTGAGCTCACCGCGTAACAAAGGCATGTATATCCGCATA
          AAGTACCCGTCAGGTGTCCAAACGAGTTACCTGCGTACCACAAGCGTGTAAATCCGGATA
          AAAAGCCAGTCCGATGATTAGATGCGCTATCCGCGTAAGGGAGGCATAAAATCTCGGGTC
          AGATGGACGTCCAGTGCTCGAATGAACTACCAATATGGTAGATAAATTGGGTGTCCTATG
          ACATTGTGGCGTAAACGGCACACATGGCGTACGTGCTGTAGGCGTCCCCAGTCTAAAGGC
          CAACTGGCGAATGGGAGCTCATCTGTCCACAAGTGGTGTCAGGCAGACGAACTTTACACT

          CCTCGTTGACGGTCGGCCCGTCGCCTGCGGGGGTTGTCGA
          CTTCGTTGACGGTCGGAACGTCACCTGCGGAGGTTGTCAA
          CCTCGTTGACGGTCGGCCTGTCGACTGCGGAGGTTGTCGA
          CCTCAGTGGCGGTCAGCCCTTCATTTGGCGAGGTTGTCGT
          TCCCTAAGAAGCTCGCTCTCTAATGCCAGCTGCTTATAGT
          AACCAGGGGCGCTCGGCCACTAATAGTAATTGGCCTCTAT
          CCACGGATCCCATTTTTACTTATCGAGAGATCTTTGGAGT
          AACCCGAGAAGCTTACTCGTTGAAGGTAGGTCATAGTACG

