 8 1000
t1        AGGTCGTGGCAAGTGCCTAGGTTGAGGAACCCCGCCACTCGGGAGTTGACGAACCAGCGA
t2        AAGTCACGGTAAAAGCCTAGGTAGAAGTGCCATGCGACCCTGGAGTTAACGAACTCGCGA
t3        TGGTACGGAAAGCATTCCGAAGTCGGGGAGCTCGTTACTCAGGAGTAATTGACTCGGCGG
t4        AGGCTATCAAAATACCCCCGATCGTAGAGCCCGCCGGCTCGGAAATCAACAACCGGCTGG
t5        GTGGTGGTAAAGGATCCGGGTCCATGTCGCTACGTAGACCTTGATCTACTCACCGCCTGC
t6        GGGCTGGTATAGTACCTAGTCTCGTGACGCTATGAAGGCCTTAATTTGATTACCACTCAC
t7        CTGGCGTTTCAAATTTCACGGATGTTTTTCCTCGCTACATTGTCCCCTCAAACCTTTAAG
t8        GGGGCGATTCGAATCCCATTGCCGTGCCATGTTACTACCCTGTGGCGACGGACCCCTTGA

          TCTAATTTCTGCTATTACGGAGACTACACTACTACTGCTCCTGGTCTACCATATCCGTAT
          TGAACCCTCTGCTATCCCGGAGCCTACACTATTACCGCGCCCGGTTGCTTTTAACCGTTT
          AACTTGCTTGTGGGAGAAGAATCCGGCCACAGTAGCGCGCCCGGCCGTCTCCACTAGATC
          TAGAGACTACGACATGGTGGTTACTGTAAGTCTAGCGCTCCGCGCAGCTTAAGCTAGATG
          AACTGGCACTCTTCACAAAACTTGGAATATTAGGTCGCTTTAGGCATCATGATCCAGACC
          AATTGCCAAATCCCGAAAGACCCGTAATTCTTCGGCGATTTAGGCTTAATGGTTTTTACT
          TTCAACAATTGAAATACCCAGTCATATAAGTAAAGCGGATCCCGGGCCTCGGATCGAGTC
          CCCGGCAATTGTGCCCCTGTCCAATACCAGAATTGCGACTCACGGCATTTGGATTAGATT

          AATAGTGAAACGGGCAGGGAATACCGTATCTCACTGATGGCAATGCGTTCGATCGAAATA
          CAAAGTGAAATACACTGGTCGCTCCGTATCTCGCCGGTAGCTATGCACCTGACTGAAAAG
          TTAAAGGAAGGTCGTCGATTCTCGGGCATTCTTCCGATATTATCTTGCTCTACCGAACAG
          TCGGATAGAAACTGATGGCGAAGTTATCCGTCTCAGCCGATGCAGCTCCTCGCTGAGCAC
          AAAAACTCAAAATTGAGACGAGTTCGTCCATGGCTGGCCACTCATCCGATCGACGAGGCA
          TAGGGCGGATGTTTTAAGCACGGCTTTTCGTGTCTGGCCGCTCACCTCGCCCCCGAGGCA
          CCGGTCGCGGTAAACGGGAGGGGCAGACGAGCATAGCTAATCGTTCGTTTCTAAAAGCAG
          CTAATTGTAGGACACGAGAAGGACAAACGCCTCTAGCTAATATACTGTTTACGAAAGCCA

          GGTTTACATAGGCTACGGAAGATAAACCGTGTGTATAAGGTACTAACTCTGGTTTGGGAG
          GGCACACATCAGTTTTCTAAGATATACCGTGTGCAGCAGGTACCATCTCCGGTCTGAGAA
          GGACGTTACGGTCTTTCCTAGGATAGCTCAGCGTGCTAAGTCTCGTCCCTAGGTAGCTGG
          GATCTTGGTAGACCTGCATTGGTTCACTGTGCGGGATAGGGTCCGCGTATAGGTTATGTG
          GGGTGGCTCATACTTCCCCAAGAGCGCCCCGCGACATGGTTTCCCCATTGAGTAGGCGCA
          AGGTGCTCTGCATTCCTTCAGGAAACTCCAGCGCTGAAGGTTCCTAATTTGGCAAACATA
          GTCACCGGCAGGCACAGTAAGAGCCCGTTATCACGAAAGGTTGCATGCTCGTTTAAAGCA
          ATTGCAGGTAGGCTTAATCAAATCCAGTCGTTACCAAAAGTTGCGCACTATACTATACAG

          TACACTTCGTACAACGCCCTACTGGTATAAAACACGAACTACTGATAATTCAAGCTTACG
          CACACTTTTTACGGCGCCTTGCTGGTATAATGCACGAGTTATCGATGAATCAAGCTTATA
          CTTAATTAATCGCGCGGACTGCTATTACGACATCAAGCATATAGATGGCCTGCATTCTCG
          TCCGATTCCTACACAGATAAGCCAGGATAACATACAAAGAATCGTTATATGACATTTGTT
          GTAGCCCACCTCTGACTATCGAATGATCCTTACAAGCCCCTTTGGACGTCGAACGGGCAT
          CCAGCCCACTCGCTGCCACTGTCTTATTCCTATATAGTGGCTCAAACGGCAAGGCACTAA
          CAGGCACGAGGAATTGCCCGGTCCCGCCGCTGAGGTATGTACGGTTATGCTATCACAGAT
          CTGGCTTGTTGTAGCGGCCCGCTGGAGCCCCGCGGTATAAATTGTTGTTCAGCAATCGAT

          TTATATACATAGAACGCGTAACTAGAAAACCGCAATCCTTTTCTTGTCCAGAAGACCGCT
          TCGTAAGCATAGAACGCGTCAATAAAAAGCTGTACTCATCTAATTGCCCAGAAGACCGCT
          CGGTAAGCTCAAAGTGCGCAAAAGGGGGGCTAATTCCGCCCCTCTGGCCCAAAGATCAAC
          GCGAGACCCTAGCTAGCGAAGTCAGGAAGCTGACCGCCACTCCTTGCACGGGTGTACACC
          GGCTGCATTCATGAGGATCGATAGAGGCGTTGGTCCTTAACCTGGACCCAAGAGACAGCG
          GGTCACATTCGCTGGGATTGACAGGAGGGCCTGTCCTTACTTCGCTCCTAGGAGGCCGCG
          TTATCAGAATAAGGAGACCTTCGCGACTTCTCGCAAATAGCTATTGCGTCCGCCATAAGA
          TCATTCGTTGAAGCAGTTTTTCGTGACCCCTGGCCTACAGTTAAAGCGCAAGCTACCCTT

          ACGTAATAGCGGACGAACTCGTGAAATGTTCCTTGAAACGCACATTACAGAAGCGCTTTA
          TCGTAAAAGGGGACGAATTCGTGGAGTGTCCTTAGATAAGCCCATCAAAAAAGCGCTTTA
          TAGCGAAAGGTTCCGATTCAACTTTTTACACCAAGTAACACTTGTAACGATACCGACCCG
          ATTTTTTCTGGAATGGATTCACACCGTCCTATCTGCTTCACACGTTAAAGGGCCGGCCCA
          ATCATACGTGCCCCGCCTCGACGCAGCATCATTTAGAAAGGGAGTCCGAATACGAAATCC
          GTCTTCGATGCCCTGTAATGACGTTGTGACATTTAGCAAGAGAGTTCCAATGCGAAACCT
          CTATAGAGGCGCATATCTGAAATATGAACCGTTTGCTGGCGACGACTAAACATGACATCA
          CCATAATAGCGTGTATCTCGACTACGTGCCACATGCTGGCGCAGACCAGATATAGCACTA

          GGCTCTCATCGTTGCGATTCGTCCCTCGCGCCTGCTTACGGTGTCGTGGGCGCTCATCCA
          TCCTCTCACCCTCGTGATACGCCGCAAGACTCTGCTTACGGCGTTGTTGGCTCTCATCCG
          CGCTTTCGGCCTTGTGGTTCTGTCCCAGTTGAAGCCTTCGGCAGTGCCAACCTTTATATG
          TACTCCAGACCATAAATACCGGGTTTCCACACTAGTAATGGGGTCGATAATCCTTCTCTT
          AGTTTCGGCGTCGTTGTGATTATATAGGCAGCATCTCGTGACGCTGGTATTCTGTAGACG
          AGTTTCTGCGACAGCGTTGGTCTGCAAGCAGCGTCTTGTGAAATCGGCACTTCGTAGGCG
          TTCTCTATGTGCGATAGCCAAGGGGTAGCTCCTGCCTGTTGCCTTGACGAAGAATCATTG
          TTCTCTGTGTGTAGCGAACGAGAGCTAGCCCCTCCTTATCGCATTGGTGCACCATGGTGG

          CATTCTAAGGGGAAAAGCAGGAGACCCCTGACTCAAATGGAGTCATAGCCGCTATGCGAC
          CACTCTGAGGGGATAAGCGGGAGACCCTTGCCTCAAATTGCCTTCTAACCGATATGTGAT
          TGTACTAGGAACGAATGCCTGAGGGGTACGCTTCGGGGTAGTTTTCGATTGTCCCGTTGT
          TTTAGCGAGGGGGAGTGCGAATGAACCATATCCAAATGCAAGGCTCTGTCGCGAAACACC
          GGAGCTGGGAAGGATGGCGTTTGTCCTCGATCTTAGGGTTGATCGTCGCGATTTCCCACT
          TCTGCCGGATAGGACGGCGCTTGATATCGATCTTGAGTTTGCCTACTGCCATCTTGCACT
          CACGACAGAGGGATAAGCACTTAGACACCATACAGTAGTGCGCACTTGTTGTGCCTCACC
          CACGACAGAGGCACACGCAACTAGGCTCCTTCCAGCAGTCAGCACTTCCCGTGCCGCGCC

          AGCTTGCCTAGTGGCTCATACATAACTCAACGTCGTTCGAGGCCTTAACTCATACTAGTC
          AGCTCGCCCAGTGACTCATGCATCTAACACCATCGTGCGGAGCCTTATCTAGTATTAGTT
          GGTTCTCTTAACAGTCGACCCAAATGTTATAGCCGAATCGAAAAGTTACAAGAACCAGCT
          GGGTCGTTAGCTGCCCTATTCGCACCGCGAGATTCATCTCCGACTTGACAGGTCCGCGAT
          GGTGCCGTTACGGACCTACCTGAATAGTTCAATTAAACAGAAACTTAATCAGCACAATCT
          GGTGCAGTTTAGGGCCTGCCCGCCTAGATCAATTGAGCTGAAGCTTTATTAGTACAGTCC
          AGCTCGCCCGCTGACACACTTAACCAAGGTGTCTCAGGGAGAAGTCAGGCCTGAACGCGT
          CCAGTACTGGCCGGCGCATTTTACGAAGGAGTTCGGGCGAGGAGTCAGATCTGAACGTCT

          AGTTCTGTTGGGCACGTGCCCCCTAGTGCACCCGCTACCCAACTCTAGTGACGACGCCGC
          GGCCCTATTGGGTACGTACCATCTAGTGTACGCGTTACCGAGCCCTAGCAGCGAAGCCAC
          GAACGGATTGGAATTGTAGCCTGTGGTACCATGACCATCTAGGTCCGATGGTCTGACCCC
          GGCGCTCGTTTTCGTGCGTACTGCCGCATCCTATCGACGCCAATTTTGTGCATGGCCTGC
          GATAAAAGGGGCGGAGTATCGAACCAGAGATCTAACACAAGGTCCTAGTCACATGATCGG
          GATAAAAGTGGAAGAATACCGCATCGAAGACCGAATCCACGGCCACAGTCACCTGGTTGA
          TATGACACTGCCCGTGCTCTACACCTTTGGCGTCCTCACTACTCGTCACAACATGACGAT
          AATGCAACTGTCCGAACCCTACACCATAAGCCTATCGTACATTTGAGGCAACAAGTCAGT

          CCGGTAAAAGGGCACTTCATTAACGACTCCTACTCGTTGAAAGCGCTAGTGTCGCAGGCC
          ATAGTAAAGGGCTGCTTCCCCAATGCTTCCTACTAGCTAAAGGTATAAATATCGCAGGTG
          TTGGCAGACAGGTGCTCATAACGTGAACGAACTACGTGCGCTTGCTTGGCCCCGGTGGCG
          TCGGAGAATGGGTACGGTAACCGCGCTTTCATTCCGTAAGATCTAAAACTGACGAAGATA
          TCGGTCTCGGAATATTTTAGTGACGCTTCCTCTAAGCGGAACCCGTGTGTGTTTCTAATG
          TTAGCCTCAGAATATTCTTGTAGCTCTCCTTTTAAGTGGGAACCGAATGTGTTTTAGACG
          GTGCAAAACAGGAATGCTACCGACGGAGAACCCCAGAGTAGTCCGGGGGTGGCGCCTACT
          GTGAGGATTAGAAACCCTGTTGTCGGTGCGACCAAGGTTAACTTGAAAGCGGCGTTCACG

          GTTACGTACGTTGCTGGGGATGGCACAGACACCTTATGTTATTCGAAAGTGAACCAATGC
          GTTACGTACGTTGCTGGGCATGACAGAGTCCCTTTACGTGCTACGAAAGCGTGGTAATGT
          ATATCGCTCATTGCCAGTATCGATTAAATATTTTTACGCTCAAAGGTGTCAAAGATTAGC
          ATACCGAACGCTGTTGGTGATGTCAAGGTTCTTTTACTTCCTAACACAGCATCGTCATGC
          GATTAACCAACCGACCGTGACGCCTTAAACAATACGTTTCTGAAAGGAAGGAAACCTTTC
          GGTATGCCAGGCGATCACGAGGACACAAAATTTACATTTCTGACAGGGTGGCATCTTTTT
          CTCAATGATAATACTCGGAGACGGATTAGTTCAGAGTCTTATCTACATGTTATGCCTGTT
          CCGGCTGAGAAGGCCGGGAAACCAATTGGCACAGAGTCTAATACGCCCCCTCCGCCCGTC

          TGGCCGGCCCAGTGAACCCTTCTTTACTCCCTTGCGCGGCGTGTTGATAGGGTCCGCCAA
          TGGCTGGCCTGGTGCATACTTCCCTACCTCATTGCGTGGCGCGATGAGAATGCCTGCCAA
          TGGTTCGTCCGGTGCGCGTACAAATTACGTTATAAGCGGCGTAAACTAGAGAACTACTCA
          CGGCAGTCTTGTAAAACGCAATACTGCCTCCTAGCGACGCGCCACGAGAAGATCTTGAAG
          TAGCTCCGCCCATAAAGCAATCCTCACCGCGCCTCGTTTCATAACGCCAAGACCTACTTA
          TAGTCCCGCTGATAAACGCATCGACATCACGTCTCGTTGTGTCTTGCCAAGGATTTCTTA
          TGCAAGCTTACAGACGAAAGTTGGTGGTTGTATTTGGGGTGCGCTGGTGAGATCCTAGGG
          TGTTTTCTTACAGATGAAGGGAGTTGCCCGCCTACGCTGCGTGCTGGTTAGACCCTAGGG

          GGGGTTCGAGCGATTCCAAACACGCGGGATACTAGTTAATCTTGGTGCAAATCAATTCGG
          GGCGCGCGCGCGACACAAATTATGCCGAATACTTGTTGAGTTTGCTACAATTTGATGTCG
          CGACCGTAATCTTAGTTAACCGTGCAGGCTACTGGGCTATAGAGACGCCGATCGCCTTTA
          TAATAATACGTACAAGGAGCTACCCCGGACGTAATGTTTATCTGATACATGCTGGGATCG
          CATAGTTCATCACTAACGTAACTAAATACTAAAGGTCGATTGAAGAGCCGAAGAGAGGAG
          TATGCTTTACTCCCGTCGTAGCTTGATATCAACGGGCGATCGCGGACAAAAAGAGTGCAG
          TGACCGCTGGCATCGCTCGGTGGGATCATGTGCCGTCTGGTGGCATGTAGCTCTATAAAC
          CGAATGTCGGTATTGTACGATAGACACGTGAGGCGACTGACGCTACACAGCATTCCAAGA

          TCGGCGTGAGAGCCAGCGTCCGATCTATGTTAGCCTATCTGGAAGTGAGTTACGCACGAC
          TCGGCGTGAGGGCCAACATCCGACTTATGTCAGCCTACATGGAAGTGCGGCCGGAGCGAC
          TCGATGTGAAGGCCGGCACAAGATTCGTATCTCACGACTTGTACGCGCATACTGGTCGCC
          CCGGATGTCAGCCCAAGTGCTCACTTACACCTACCAATCTGAATGAGAGTCGTGGCTGAC
          GACATGCGGTTATTTTCCAGGATCTCTACCTCCCGTGCCCGCATGCCCGGCGGATTCCCA
          TCTATACGAGGCTCTCTCAGCGACCTTATCTCTTGTGCCCGTACGTCTGTTGGTAACCCG
          TAACCGTGGCAGCTGATATGTGATGGGAATCTGCGGGTAGGAAGATGGGGTACTGCCACC
          CACTGGTGAGAGTCGATACGCGATGCGAATCATTGGGTGGGATACTCCGGCAGTATTACT

          CTTTGTCCCTTCATTCGTAAAGTACCGTCGTGGCCTGACT
          CTTTGACCCTTCTATCGCAAGGCACCGTCGAGATCTTCTA
          GCTTTCTCTTTGAAGTGCACGGATTCACAGCGTATAATTA
          TTTGAGTTCTCTACGGGTAGGGGCCCTGCGTCCTTTCACA
          TACCATATTTCCGGGGGACCAATCGTAAAACGACTGACCC
          AACTTAACCTCCGAGGGATTGTTCGTGCAACGATCAAATC
          ACTTATAAAATTAATGAAGTCTCAAAATATTTAACTAGGG
          GTTGTTAAAAGTAAAGACGATTCGCTACATTGTAATAGGG

