 8 1000
t1        GTGGCAGAAAGACTGTAACTACACCTCAATCCCCCAGAGAACCAATCCACATAATCCATG
t2        GTGGTAAAAAGATTGTAACTACCCCTTGGTCACACAGAGAACCAATTCCCATGATCCATG
t3        GTGGTAAACATATTGTGGTTGCCTCTTGATCCCGAAGAGAACCAATTTACATAACTCATG
t4        ATGGTCAAAGAATTACGGCCACTGCTGGGTCTCAACTAGTTCGCGTTCGCTTAGCTCATG
t5        ATATGGAGAAAAGTGCGCCTACCGAAAGGCTCCAACGCTTGTAAACCTCATGAGTCCACA
t6        CCGACATGGGGCGTATGACTATCAATACATCCGCAAGACAGTACGTTGTGCGCACCCTCA
t7        CAGGATGAAGGAACACGATAAACAGAGGGTTTACGCAAAAATAACCGCGAGTATTCATCG
t8        ATGCTCAAATGCTTCCAGCGGCACGACAGGTCCTAATAAAACCAGTCGCGCTGCACCATA

          GCCCTGCCCAGGTCTCGATAACAGCTGGCAGCAATAGCTTCCCTGGATAGCATACTATCA
          GCCCTGTTCAGATTTCGATCACAGCTGGCTGCAATAGCTCCCATGGTGAGAATCTCCTCA
          GCCCGGCCCAGATTTCGAACACAGCTGGCCGCAATAGCTCCCCTGGCTGGCATACTTTCA
          GTACAGACCTGCTTCAGGCCCTTGCTGGCCGCAAGAGACCCCCTGGCTAGCAGGTTCCCC
          GTCTTACCAGGCCTCCTGCCGTAGCTGAGCATGATGGCTTCCCCTACCAGAAGATGTCCA
          ATGATCTCCGGCCTCCCGATGTAACAGGTCGCATAGATACCCCATATAGGCAGATCCCTG
          GTTGCGACTTGTCTTCTGGTGCTCCAGGACGTACTTGTAGCCCACTTCTATTGTTGGATG
          GATGTATTCCGCTCTACAAAGGCACCCGGCTACCATTTCGCGGCATTTGGTCAACATATT

          GAACGCGTCTCCGCCAGTCAGAGGCTAGATTGACGCTCCAGCGCACCGCGGGCTCCAGGG
          GAGCGCGTCTCCGCCAGTCGGAGACTAGGTTGATGCCGCAGCGTACCGTGGGCTCCAGGG
          GTACGCGCCCCCGCCAGTTGAAGGCCTGATTGGTGGAGCAGCGTACCACGGGCTCTAAGG
          GGACGTGTCCTCGTCGATCTGTGGATACACTGGTTCCGCAGAGAACCGGGGCCTTCAGGG
          GAAAGTTTTTGCCGCGGTGGATGGCCACGACCTCTATGCAGCATAACATAGACTTCAAGG
          AGACGCGCCCCTGGTGGCCGCACGCTCTATCGAGCACGAACTGCGATTAAACTTCTGAGG
          GGACGTGTTCATGCCCGCCCAGAATCTCTTAGACAATGTACTCAATGTCGTGCTCTGGGC
          GATCAAATCGGAAGCTGAAAGAGGGTCTAGACGACGCGTTTCAGACCTAAGTCACGATGC

          CATTAGTACGTGTAGGTACTAACGCGTAGGGACATTACGGACAACACGAATGACCGAAGC
          GACTAGCACGTATTGGTACTAACGCGTAGGGACAACACGGACAACACAAATGACCGACGC
          GACTAGAATGATTCGGTAATAACACGTAGGGACGACACACACTACATGAATCACCGAAGC
          GGTTAATAATTTTTGATGATGGTGCATAGCGACGACCCGGAGTCAGGGAGTTCTAAAAGC
          GACCAACAAGCTGTCTCACTAGCCCGTTGGTGCAATGTACAGTTCAAGCACTATCGAAGC
          GCATTGCAGACTTTAAAAATCACACGCTGGATAGAGAGGAGGCAAAGTCATCCATGAAGC
          AAGCCACACGTATCGGATGGCAGCGCCCAGGACAAGAAGTAGCAGACTCATCCCGGGACT
          CATGCTTAATCCTCTAAACCACCGTTTTGGGGCGCAGAGCGGACAGCGCATAGTACAGGT

          TACCTTGACTCACCAGCGTGTGCCAAATTCTAATAAGGGCCTGGTAGGCGGCCTCTCGAT
          TATCTTGCCTCACCAGCGTGTGCGCATTTCTCATAAGGGTCTGGTAGGCTACCTTTCGAT
          TACCTTGGCTCACCGGTGTGTGAAAAATACTCACTAGGGCCTGGTAGGCGACATGTCGAT
          CAAAATGGTCCATAAGTCCGCGCACGCTTTTCATCACGAGAGAGTCGGCGGCACTCAGGT
          TATCCTGATCTACTAAACCGCTCCAGGCTCCCAATAACAGCGCATAAGCGACATCCAGAC
          TAGTTTGCCTCACGACTCCTCGTACGCTTGTGGATAAAACCCAACAAGCCATATTTTTTG
          AAGTCAGGTTGGTCACTCTGCAGTCACTTTATAATAAATGCGAACGGGTGGTATTTAATC
          GTACTTGTGGGGTTACTGTTTAGACGCCGTTGGGCTGCACAAGAGCGGGACCCCAATGCG

          GTACCGTGGCAACACCAAAGGGACACAGCGTTACAATGTAACTTCACTAGCAAAGCGAGG
          AAGCCGCAGCACCACCACAGGGACACAGCGCCACAATGTGACCCCATTAGCGAAGTGAGG
          GTACCGTAGCAATACCAGAGGGACACAGCGTTACTACGTAACTCCATAGATAAAGCGAGG
          GCGCACTAATAATACCAAGGGGTCCGAGCATTTCAACGCAAGCTCGGTAGTAATCTAAGG
          GTGCCTTAAAACTTTCCAAAGTGTATGACATTTCTACGCACCCTCGGGAGCGATGCGGGG
          AATTCTTGACCATCTTTAATGGTCATGTCACTTCCATATCCTTCCGGCAATGGCGCGGGG
          TCGCACCTAACACGACGAGGAAACACCAACCTCCTCTGTGAAGCTAGCAGGGCTACGGAG
          GTATCTCCCGGGAGTTACGGGGGTACCGTAGCCGCGCGTGTAGAATGTAGGAATGCGCGA

          CTACAAGTGGTAAGGCCCGCTGGTGCGAAAGGCGGATTCGTCGATGCGTACGGCTCCGAT
          CTATAAGTGGTAAGGTCTGTTAGTACGGAAGGCGGATTTGCCGACGCGTGCGGCTTCAAT
          CTGCAAGTAGTAAGGTTTGTCGGCACGAAAGGCATATTCGTTGATGCGTACGGCTTTGAC
          TTATACGTCGAGCAGTCCGTCTATAAGATGAGTAGTTCCGTTGAAACGAGTAGCACTGAT
          CCCTATGTTGTGCAGGTCGGTGGTAAGGGCCGCAACCCTGACAAGTAGTGCACCTTCATC
          TAGTGTGGTGGACTGACTGCTAGTACAGAGTGTAGTCACGTTTAGGGGTACGGTCCCTAA
          TGCGATATACCATGCCCCGGTAGCCTAGGGCAAAGGTACAATCAAAGTTGAGGGCATGAC
          CTCCCTACAAAGCATTTAGTTGGGTTACAACTTGTTTGTGACTAGTCAATCGGATTCTCA

          GCAGCAACACTCACGCTTCGTGGCTATCCGCCATGCGCTCAGGTTAATTAGGGTCTCAAA
          GCAGAAATACTTACGCTCCGCGGCCAGCAGCCTCGCGCTTGGGTTAATTAGCGTCGCGAA
          GCATAAATTCTTATGATCCGTGTTCATCTGCCTCGCGCTTAGGTTCCTCAGGGTCCCGAA
          ACTTTAACGCTTTCGTTCCGTCATCATCCGCCTGGCACTACGGAGATTTAGGGTCCCGAA
          GTTAAACCGCTTCACTCGTGCGATCAGCGATTTCATACTCAGTTGGGTTGCACTTCCGGG
          CCCGTAGAGCTTTGATCCTACGAACGAAAGTCACGAGCGGAAACCGTTAACGAGTGAGGG
          GTTGGAACACCTAGCTCCTGCGCCGGCCCGTCCCGGCTGAAGGTTGGTTAGGTGGAGGAG
          TACGGATCGCAACATCTCCTAGATCGCTTACTTCAGCCAAAGCTTGCTTGCACGCAGGGA

          TGCAAGCCGTCACTGATCGAGACACCGGCGAATATGCCACTCCCTTAGTGTCATACATCA
          TGCAAGCCGTCGTTGATCGGGCCGACGGGGAATATGCCCATTCCTCAGTGCCAAACATCG
          TGGAAGCTGTCGATGATCGCGCCACCAGGGAGCATGCCATGTCCGCAGTGCCATACACCA
          TGTAGGTTGTTATTGCTCCTGGTATCGGCTAATATGTCATCCACGAGGTGTCATCCCTGA
          GGTAGGTCGCTTCGGTTATTGGTACGCGGTGGCATGCTCTTTCCTGAGTCTCATTAATGC
          CGTTGCTTGATATAGGCGCTGGTATGTCGTTGAATGTTCACCTCCAGAAGCTAGTCCAAT
          CAAAACTAGACCCAGATGTGGGTGGATGGTGCCACGTCCAGTCTCGATTGCCACGCGTTC
          CGCCACACGATACAGGGGTACCCAGGCGGGAACACCGCTAGTCACGGGTGCAACTATCGT

          TAAAGTTTATCGTTAAGATGCCCGCCTTATCGCCTTGGATGGTCGGAGTCCTCGTTTCGT
          TTAAGTTTGTCGTTTGGATACCCGCCTTAACGCCCCGGATGGCCGGAGTCCTTGTTTCGT
          TAAAGTTTGTTGTTTGGATACACGCCTTACCCCCTCGGATGGTCGGAGTCATTGTATGAT
          TAACGTCTTCCGCTCGACTATTCCCCCCAGAACAGCGCACTATGGGCCCCACCGTTACCC
          TATCGTATGCTATTTGAACGCTCGCCCCCAAGTAGGGAACGGCTAAAATGGTCGTTTTGC
          TTGGCGGCCTTGCTTGTAGACCCATTACAGGGCAAGAGCGAATCAGAACATCAGTTCGGA
          AACTATTTACTATCGGCGAGTTTCTCTTAGCCTATGCTTTGACTAGCATCACAGGCTGGT
          GGCTGTATGCTGTCTGGTATAATTCCTTAACGCACGTCCCGGCGAACTGTAACCTAGTAG

          AGGAGATGTCACTATGGGCATTAGCAGGTAGCGTTTCCAGTTCGTCCGGAGCCAGCCCGG
          AGGAGATGCCACTATGGGCATCAGCAGGTAGCGTCTCCGGCTCGTACGGAGCCAGCCCGG
          AAGCGATGTTACAATGGGCATCGGTTGGTAGCGTTTCCAGCTGGTATGGAGCCAACCCGG
          AAGAGTTAGTTCTTTGGGACTAGGCGGGCTGAGCATGTAATCTGTACGGAGCTAGTCAGG
          CATGAGTACTACTGTGTATATTGACAAGCCGGACCCGTAATCCTCATGAAACACGTCCGG
          TAGAAGTCACGAGGCGAGACTACCCAAGCCGGAACTGCCTTTCGAATGGGTACACTGATG
          GGCAACCACTAAACGGCGCAAAGACGAGTAAGAGTCGATCGACGAATGAAGATGCCTGGG
          TATGTGCGATAGCACAAGTCCTTCCGGGAAGGATTTTCACGCTGTATGGCTTCGGCAGGC

          GAAACGATCCAGAAAATCGGCCCCATCTCTTGGGAGCCGTTCAAGTACCCCTCCACAAAG
          GAATTGTTCTCGGGAATTGGCCTCCTCTCTTGGAAGCCGTTCAAGTATTCCCCCACAAAG
          GAATTATTCCGGAAAATCGGCCCCACTTCTTGGGAGCCGTCCAAGTACCTCGCCACTAAG
          CACTCGTCCCGGCGGCCCGGACCCTCATCATGGGATCCGCTCGAATGCTTCCAAGTAAAG
          ACTCTGTCTTGGAGAGATGGGGCCATCTCCGCCAAACCGTCCTTGTGCCCTTAAATCTGG
          CTACCGCCCTAGAGAATGAGGATTTTCCTACGCGTACCTCCCGGACTCCCCAGAGCGAAG
          AAATTGTCATGGGAGAGTGGCTGCCCTTGGAGGGGAGTGCTAGAGCATCTTCGCGAAATG
          TTTCCCTCGAAGCCGCACGCGTGCACATTTTAGGGACAGAGAAGGAGATCTTAGAGGTCT

          GTATAGCGGGTCAGGTGGGTTATTCCAATATTGAGACGTGTTAAGCAATGCTAGTGTTGC
          ATATGGCGCGACTGGTGGGTCATTTCAATATAGAGACGCGTTAGGCACTGCTTGTGTTGC
          ATATAGCGAGTTTCGTGGGTTATTCCAGTATTGAGACGCGTTAAGCAGTGGTAGTATGGT
          ACACGACGGGTTGAACTGGCCTCACCGGCATAAAGAGGTGCTGAAAAGTGACACCGGATT
          ATGTGACGGTTTGCATGAGCCCCTATAGTATAGAGCTGTCTTAATCTCCGGCCTCGAAAT
          ATTTTACTCACTAGCCCGGTAGTAACAGACCGGTTCTTCACAATGACGCGGTGCCACGAT
          CCTTGCCATACTTTAATCCTCATTATGACATCATGTGACGTGTAGCAGGAAGGTTGCAAT
          GTCAACATGGTCACAGGGGATATAACAATTAGTGAAGGAGTAAGGGGGTGGTGTGACTCC

          GTAGGAGTTCCTTTCAGATGGCGGACTGTCCTGATGCCGTTCGCAGTAAACGCTATGGAC
          GTTACAGTTCTTTCCAGACGGCGGACTGCCCAGATGTTGTTCGCAGTAACCGCTACGAAT
          GCAAGGGCTCCTTCCAGGTGGCGGACTGCCTAGATGATGATCGCAGTACCCGCTATGGAC
          GTATGACCGGCTGCTACGCGACGAATCGCTCAACTGATGCTCGTAGCAGCCTCTACGACG
          GGAAGAGTCTCTCATACGTGTCGAATCCCCTCGACGGTAACTTCAATAGTTGATACGGCT
          GTGCGAAGTATTTGCGTAGCCTGGATCGTCATGGCGACGCCATGAGCCGCGGTTGAGATA
          GTAAGAAAGCCCTTCACAGTGCATATACTATTCGTTACCGTCCTCGTCCCTGATGTACCA
          GGGAGACCCCCAGTCTTGGTTCAAGTATCGTAATTGCGAGTGGAGACATGTGTCACGTCT

          CGATCACCACGACTTCATAATTTGTTGTCTTAACGTGTCTACTAACAATCCTGGCCCAAG
          CGATCACCATGACCTCACAATTTGATATTATAACGTGTTTAATAGTAACCCTGGCCCAAC
          TGTTCACGACGACCTTATGATCTGATGTTTTAACGTGTCTAATAACAATCCTGGCCCAAA
          CGGCTGAAACCATCTCATTACTTGAAGTTCCAATGAGCCCCAGATGAATCCCAAACGAAC
          CCGTTACAACGCCGTAACTGGCTGTTGTTTTAAAGCGCCTCAGATGGATCCTCGTCCTCT
          CAACAGGAGCAGCCTGACGACCTGGTGCTCTGATGTATAACCTGGAAAGGCATTTCTTAC
          CGAATTCAACGGTTACTCCATTTGACGTTTAAATACACCGAGAGCAGGATTTCGACTCAC
          GACTCCTAATGCTTCGATCAGCTACCTCTTATCCGCTTTCGTCCAGAAACCAAATATTGG

          ATATGGGAGCCAGGGTTGGGTAGCAGCCTAACAAGTAAGTTACGAAGGCCTATCGACCTC
          ATATAGCAGCCAGGGTTGGCTAGCAGCCCAACAAGTAAGTTACAAAGACATGTCGACTTG
          ATATAGCAGCCAGGGTTGGTTAGCTGTCCAACAAGTAAGTTCCGAAAGAATACTGGTCTG
          ATGCCGCAGCATGGATTGGTTAGTTATTCCGCTAAGGAGATCTTAAGGTGTCCAAACCCA
          TCGGCACTGGCAGGATTTACTCGGTACTCCGCCCGCAAGATTCAGAGGAGTACTATCTTA
          ATACGTCTGTCCAGGGGCGCTGGTTGTCAAGATCGCACGTATTGGGGGGACATTAATGAG
          GTACGGCCCGGTAAACAGGTATGCCGGAAATCATAAAAGTCTGGCGAACCCACAAGGTCG
          GTAGATCCTCTATTATGTAGTAGGTGTAGTAGATTAAGAACCTGCAGGTACCTCAGCACA

          GAATGGATTCGGTGAAACCCCTTTAAGGTAGCGTGGGCGA
          GGATGGGTTTGGTGAAACTCCCTCAATGTAGCGTGGGCGA
          AAACGGGTTTGGTGAGACTCCCTTAAGGTAGAATGGGCGA
          GCACAGGTTCGGTGCAGTTTTCTCATGGAAGCGCGGGGAA
          GATTAGGAAGGATGACCTTTACCCACGGCTACATAGGAAC
          GGAACCGATTGGAGCTCCACCCTAACGCAAGTGTGGGCAG
          GCGGCAAACCCGTGGCGTTTCCTAATCGCTGGGTGGGGAA
          GAGAAAGCTTTGGCAGGTCTCCAAGCCGAGTCATAGGGTC

