 8 1000
t1        CTCCCCTGGCTGCAATGATCAATTAACATCATTAGCTAACGCACATGGCTGCCAAGCACA
t2        CTCCCATGGCTGCCATGAGCAATTGACATCATTAGCAGACATGTACGGCTGCGAAGTACA
t3        CTCTACTGGCGGCCGTAAGTAAATGGCACCAATAATGGACACATATGGCTGTTAAGCACA
t4        ATCCTCTGGCAACTATTCATGATTGTTATAACAAGGGGTCGCATCCGGACGTTACGTGTA
t5        TATCGCCGGAAGCAGCGGGCGAGTGGTGGCACTAACGACAAAATAGCGCTTTATCGGGTC
t6        ACCTGTTGGGAATGCGGAGCGCGTGGCAACACCTAACCAAATACGCAGTCTATGCGCAAT
t7        TATCCATGGGACTCATGCGCGTATAGGTCGCCCTATAAGGATCTTCTGTCTTTAACTATG
t8        CTTCTCTACAAACTTTATGATGGCAGTTCTCGTTTTGAAATACTCTTCCATTTAGGTAAT

          ATGCGTAAAACCCTACTGTCACAGCCCTTATATTTGGCATGTAGAACAGGCACAGCCATA
          ACGCATAAAACCTTCTCGTCACAGCCCTCATATTTGGTATATAGAACACATACAGTTACC
          ATGTAGAAAACTCTTTTATAATATCCAGCATTCTCGTCTTATAAAGCCCATAAAAATGTT
          ACGCAGAAGATTCTCCCACAAGTCCCCGCATACTCGTGACCTTCTATAACCCCAGTCACT
          ATGCTGGAAAACCTTCTTATGTACACGAACCAACTGAGGCGTTCCACGGATTCAAGTCGA
          ACTTAACATACACCGGCCTCATATGTCGCTTAACACCGCTGTTTCACCTCCGTAATCGCT
          GAACGCGATTGCTCCCACTCGCCTTTCACCTATCGGCAATACCCCCGGAGTGGGACTGGA
          CGAAGAAGAGCGTTCTCTGTGTTGTGTGCCCTTTATTGGTATGGTATTGATGGAACCGGC

          TCGCGGATCCGACAGACCCGAACAATGGGCAGGCTTGTTCGTGGTCGTCCTAGAACAGGG
          TCGCGGCCCCCGCAGACCCGAACTACGGCCAGGCTTGTTCGTAGTCGATATAGGTCTAGA
          TCGCGGCCCTGGAGGTCTGGAACCACGGCCAGGACTGTTTCTCATGGTCATGGCGTCGAA
          TCGCGCAGCTGGAAGGTTTGTGCCAAGACCAGATCCGTTCCCAAACGCATCAGCGTATGA
          TACCGATTTCGGCACCTTCACTGATGACTCACGGTATCGACCCACTGTGTGAACTCTAGG
          GCGTGGCATCAGCGGATCAGAGGCGGCATCATGCCCTGGTGAAGATAATCGCGCGTTAGA
          GCTTTGCACCTGGAGATTCGAAGACCCATCGTGACGTTTCAGCACCGCCACGGACCGGTG
          ACTTCAGGGCTGCGGATCAACAAATGAGTCCAGCATTTTTCCCGCTGGCTCCATGCGCGC

          TCGGCTGAGGACGCGCATTAACAGCCGACAGCCCGCATCGTGATGGTAGGAGGCCAACTC
          TCGGCTTGGGGCGTCCATTAACAGCCGACAGCCCGCACCGTGATGGGAGGAGGCCAACTC
          TTGGCAGTGGGTGAACATTAACCGCCCTTTACCTATACCATGATAGTGGGAAGCCAATAC
          TCGTTAAGAGGTAAGCAGAAATAGTAGCACGACTATTATGTGACGGTCGGCATGATTTCG
          CCGAGTAATAATAGGAGATGGGCTATGCTTGCCTCCCCTATCATCCACGGAGCATTATGC
          TTGTTTACGCTCCGGCCGAACTGTTCCGAACTCCATTGCCTTCTCAGTGGAGATCAATCT
          CTAGTAGCGGACAGGAGATCAACGCCTCTGTACCGTAGTACTACAACCAGCTATCAACTC
          TAACACGCAAGCAAGTGGCGAACGCCGCTGCCATAGGTAATCGATGTCGGGGAATCGCCT

          ATGAAGCGTGACGGAAAGACATCACACCCGGATCCAAGCTGATAGGAAGACTAGTCACAA
          ACAAAGTGTGGCGCAAACACTTCACTTTCTGAACCGAACAGACAAGAAGACTAATTACAA
          ACGTCGAGTTGACAAGACCATTCATACTCTAATAATAGCTGACGAGGTGACTAGTTTCAA
          ATAAATTGTATCGGAAAAACTCCCCGCTCTGGTTAAACTTGACATGGCTACTACCTTTAT
          GCGTCCGGCGGCATTCAACCTACCGGTTCCTACGTGAGGCGGGGTTTTCGCAAGATGTCA
          CCTAGCTACGGTATTCTTAATATTCTTCCTGCCGTTAGCGGGAGAGGTTGTCAGTCGTAA
          TGAAATTGTTACTGATTTTTCCCAATTTTTCTTATAATGCGGGAGCATTAAATGTAAAAA
          CGGGACGATAGTAAGTCTTGGTCACTTATAGCTACGGGCTGGGTGGTACGCCACTTAGTA

          ACTTGCTAATACGAACTTCCTGTAGCACAACCGTCGGCGTTGCACAACCTCCCCCTACGT
          GCCTAATAATACGCACTTCCTGCAACACAATCTTCCCCAATGTACCACCTTCCCCTACGT
          ACCTAAAAGTACAAACTCCTCGTAATACGACCGTAAGTAAAGCGCATCTTTCCCCTAGCC
          GCCTAACCGTCGGAAATTGCCGTAACAACTGTGTTAGTGGCACAGAGTCTTTCCTGAAAC
          GGTCTTCTGATGGTGATAACTGCGATTATACTCCCGGTGATACGCAGTAAAGCTCTAGCA
          GACAGTTGAGAAACCAACGCGGCAATCAGGAAACCATTGTCCCCCTCTTATCGCCTGTTT
          CACAATCACATGGATTTTAATGTGCTTTCACAAGTTGAGGGTCGGAATTACCCTCTGGTT
          GTTTACCTCGCCGAAGGCGGATAAGATGGGTGGCAAACAGCTTCTGACTTTCCACTAGTT

          GCTAAGGTAGGCGACAAAAGAGCTTGGTTGGATAGGCGCACATGAGAAATCCAATTACAT
          GTTAACGTAGGCGACAAAAGAGCTTGCCCAGATAGTCGGGTGGGAAAAGCCTAATTACGA
          ATTATGGCTAGCGTAGAGAGAGCTTAGCTAGATTGTTACGTAAGAAATTCCCAACTGCTT
          CCCCCGGGGGACGCTAAACGCTATTAGCCGGATGGTGGCGAGGTAACGGCCATACTATCT
          ATCAAGAAAGGCTACCGGCAGGTGTAGTCAGCAGGGGGTGTAGTTCTGCTCATACTGCCT
          CTGAACTAAGGGACTTCACAAATGCGGTGGGTTAGAAACGAGACTGAGGATACACGCGGG
          TTAGGTTAAGGACATTATTAATTTTCTTCGATCATCCATACGGAAGCGATTATAATGCAG
          GACAGGGAATTCAACAATTAAGTGTAAGCTGATAGCGACCTTACAGAGAGTACGTGGCCG

          CAACGCGCCCGCGCAACCCACGTTGCCATATTTACTGGGTTAGCTAGCTTTTGAAGTGAC
          TGACGTGTCAGCGTAACCCAGGTTGCCGTACTTACTGGGTGAGTTAGCTTTCGATGTGAC
          CGACGTGCCAGCGTACACATGGGTGACGTACTTACTACACGAGCTAGCCTCAGTTGTGAC
          CACCGCATGAGCGTGAACCGGCGTGGTTAACATACCGGGCGGGTTCATTCACTGAGAGAC
          TATCCCGTTTGATCAATGGGGGAAGACGGAGCTGCAGAACGTCTTGTGGATGCCTACATC
          CAAATTCGTAGGGAGATACGAAGTCATAACAATCCCAGTCTACTTAATTTTAACTGAGCG
          TATCCCGATGGCAAAACCGGGAGCCGCGGCTTTTCTGACAGATTCAGGGCCAGAAAGGAT
          TAGATTTGTAGCGCGGCGCGAACAGGAAGAAGTTCCCAACAAATCGATCTTCACACAGTC

          GGTTTATCGACACGGAGTATCCGGTTTGCGATGTGAATAGTAATTGATTTACCAAGGAAA
          GGTTTACCGACGGGGAGTGTCTAGTTCGATATGCGAATAGCAATGGCTTTACCAAAGAGC
          CGTTCGCCGCCAAGAAGCATTCATTATGACGTGAGAATAGTAACCGATCTGGTGAGGAGA
          AGCCTATTGCTGGAGACCCTGCATCTCAAAGTGAGAAAGCTTCTTCCTATGACATGAAAA
          AGTGGGCCCTGAGAGAAAACGCTACTGGGCAAGTCTATAGTAAACAATTCTCCAAACGGT
          GGAGGCTCATAGAAGGCACAGGTTTAGGGCGTGGACAATTTACCATACCTGGTAAGAGGA
          GCTTCGCTACGGTGACGGGAGTTCTTATCGGTGCGTACAGCAACTACTCTTGCAGTTGGA
          AACGGATTGGGGAATGGCCCAGTATAGGAAATGTGCACCGTGCATTTTGTCCCCTGATTG

          TTTTTCCTCAAATCCAAATGTTGTTCTTTCATTTGTTAGATTGGGTCAAAGTGACGACCT
          TTGTCGGTCAAGCCCAAAAGTTGTACTTGCATGCGTTAGATCGGATCAAAGTGACAACCA
          CTTCTCATCAAACCCAGATGTCGTCTATGCACTTACTAGTTCGTACATAGGTGACCACTG
          TTCCCTATCTAACCAACTTCTTATAGCGACGTTTACGAAGTGAAACCAAGGTAACTAAGT
          AATGCAGTTAAGCGCGATACAAATCGAGACGATCTCCGGCTTGAATTCCCGCACCTAGAC
          AATGCAATTTAGCTCCGGCCTGGTATACGTTAGTCCGGGATTAGAGATGATTAAACGGTA
          TTTTTTAAGAGGTTAGTAGCATTATCTGGCGAAAGCGTGGCTTAACACGCGCGAATGGGT
          CCCGGAGGGTTGCGGGGGTTAAGTCGACTCGATCCTAACTCAAAAATGGGGTAGTAGGGC

          ACGTTGGAGTCCCTGGGCGTGCACGATAAGCCGCAATATAGAAGGCGTAGACCCCAAATC
          ACGTAGGAAACCCTGGGCGTGCACGAGAAGCGGCAGAATAGAAGGCGTAGACCCCCAACC
          ACGTAGGAGTCTACGGTTGAACACGAACGGTGGCAAGACAGCCGACGTAGACCCCAAAAC
          GAGCAGTGATATATGGACGCGTACGACCAGTAGTAGGGGAATTTGTGCCGAACTTAGATC
          GTGTAGACATAGCTGTTCGAAACGCAGGCATGCCGTACGCATCGGTCCTGAGGATAAGCG
          GAGTAACCGCACCGGTTTGGAAATGCAGGCCCTTTAAACAGCTGATAGGCAGATCAAACC
          GGGTTGTAGTCACCCCATGGGGGAGAGGAGTGCCAGAGTCGTTCACCGACTGAGCCAACA
          CTCCGGTTAGTACTCAATGTGACCGGGGATTATAATCCCCAGTAACATAGTCCTCCCGTG

          GACCGCTCTGGTGGATGCTGCAGCTCCAAATGTAGGGAGGTCATGCAGTGAAATCGTGCA
          GACCACTCTTGTGGAGGCTGCAGCTCCTATGGTAGGGGGGTCATGCAGCGAAATGGTTCA
          GATTCCGCGGGAGGAGGCCGGTTCTCTTATGATGGGGGTCTCATGCAGGGACGACGGTCA
          GCCCCCGTTCCTGGAGATGATATCCCCCGTAGGAGAGCCATTCTAAACCGGAACTGTTAC
          CGGGCAAGCGAGGAAGGTAATAGGACGCTTAGGGAAGTCTTCTCTCGGTGGGACCGTTAT
          GGCATATCCCGAACGGGCTGTAGCAATTCCAATTGCCGCTATCTCTTACAGTTCAGCCCT
          TGTTAGAGATGTGTGGGTCTCACTTACTACGAGCGAGGCGACATCCAGTAGGACTATTTC
          AGTACCCCCCACAGGAGATTTATACACCACACATGTGGGTTCATCAGTTTGACTAGGTAA

          CCGTCAGCACGCCTCAGATCTTTTTATAGTGCGTGTAACGATTCGAACACCACTTGTGCG
          TCGCCAGTACACTTCAGATCTTTGTCTAGAGCACGTCGCGATTCTAACACCTCTTGTGTG
          CCACCCGTCCGCCATTGATCTTCGGTCAGAACGTGTTAAGATTCAGGTGTACATAGTCTG
          ACACCAGCCTACCGCCTGCTTCGCACTCGTACCCTTAATTGCTTTAGAAACCGCTGGCCG
          AAGCCAGTCGGCCACTGAGCTGTTATTAGCACCCCTAGCCGCTTTCGTATAGATTGACGG
          GATTAGGTCGGCCGCACATTGCGCCTCAGTGCCCTGTCTCCCCTGGCTGTTGGATGCTAG
          CATCCTGTCAAATATCGGAAACCTGCCGCCACACAAGAACCCTACATTACCGTACGCTTC
          AATTACGTCCGCCATTTCTCACAAGCTAGATGGCAACAGTCTTGCGAGATTAGATGCAAA

          TTGCACACTGTCTGCTCGGCGTGACTGGAACCATTAGTAAGTAAGTGCAGGGATGCGACG
          TTGCATACTGTCTGCCCGGCGTAACTGGATCCATTAGTAAGTAAGGGCCTGGATGTCTCG
          TTATTAACGGTCTGCCCAGAGTGTCCAGCATTATTGGACAGTCAGGGCTAGACCGTCACG
          TCGTAACCTGTTGAAGAACGGTGATCCTGACTACGGGCAAAGTGGGGCACAAGTAATATT
          CGGTAGGCTATTTCTGCAGCGCGTCCTGGGGTCTTCGCAAGATGCCCGCAGAGATCAACG
          CCATTTGCTTCCTACCAGCAGTTCACTGTGCCGACGGTGCTCACATGCCTGGTTCGGGCG
          TCGTCGTTAGCCAACCGACGGGAGTGCGGGTCATGTTCCCGACACGGGCTGAAGCAGACG
          TTGCCTCCTTAGTCCGCAAACAAGCAAGGGTGCATCTCGGGCAGAGGGTCGACGTCACGA

          ATACTGCACTGGCCCTCATAGACACAGGGATTGCCATCGACGGAGTCGCAGCTAACGTAC
          AGACTGCTCTGGCCCTCTTAGACACAAGGGATGCCAACGAGGGTGCCGCAGTTAACGCAA
          CCAGTGCGCCGATCGACAGGTACCCTAGAATTGCCAAGGCCCGGGTTGCAAATATTGCTT
          TGTCAACGTCGGCCCGCAGGATAGCTAGGGCAGCTTAGAGTGAGATCACGGCAAACTCGA
          ACTTGGACACAGACCACGATGGCGAATGGCCTGTCTAGTATGTGATTGTAAAAATAACGG
          CATCGGGGATAGTAAATAGACAGGCCCTGCTGGATCAATTACCGGTCACAGTATTGTCAA
          CGAGGGATCTGACTGACGGCGCTGTGGATAAGACTCGGCGAGGGACCGCTCTCATCACAA
          TAATACAGCCACCTCACACGAAGCGGCGCTTAGTCTAGAGTACACATAGGCTAGGGGTAG

          GCGGGATCGCTGCTGTAGGACACACCGGGATAGGCATGTCGACAATCCCCGGGCTAGAGC
          GCGGGATCGCCGATATAGGACAAACCGGGAAAGGTACGTTGACAATCCCTGGCCCAGAGC
          AGCGGATTATTAGTATTGGGCATACCAGGACCAGCATGTGGACGATCGTTGGGCTAGGGC
          GTGCCGCTCCAAAGGTCCGGCGGGTCATGGCATGGGTGTCGTGAAAACGTGGGTTTGGGT
          GGTCAATCACTGGTAGTCGCCGGTAACAGGCATTAGCGATGACTACAATAAGGCTAGGGT
          GCCCTTTCTCCGAGACTCAAGGGCATACGGTGAGGATAGTGCCGACACTCGTGCCTCAAC
          GGCTTACCAAGCATAACGGCCAGTGAAAGGTAACGTCAACCCTCCCCATACTAGTTGAGC
          GTCTTCTCTCAGATACCCGAACGCGCAGGGGATTGTGTTCGAGGAAGACGCCTCTCTCAC

          GGGTGTCTCATTTGTCGTTCATATCGTATCCGCTCGACTT
          GTGCGTCTCATTTGTTGTTCATGTCGAATACGCCTGACTT
          GGGTGTTCAACTCATTCTTCGGGTAGGTCACGTTCGACTT
          GGATGCCCAATTCATAATTCGGACTATCCGTGTGCGAATC
          TGACGCATCATAAATTTTCCGGGCCAAAGGCACTAGAATC
          ATACGCCCGCATTGGTAAGCACACACGTCCTGACGCAAGT
          GAGTAAGCAGCGTTCAATCTGTGTGGCATGCTCAGGAGCC
          GCAGGCCTAAGGCACTCAGCGTTCCCTACGCATCTTAAAT

