 8 1000
t1        TCTCCTGGTCCGGCCGGATGCAATAATTGGTTTTGCTATGCTATGATACCGTTATTAGAT
t2        TACCCAGGCCTCGTCGATCCCAGCGACTAATTTCGCCACGCCACGGTAACGATATTAGAT
t3        GTCCCAGACCGGGCCGCCAACAGTGTCCTGTTACGTCGTAACAGGCTAGCGTAATTAGAC
t4        ATTAAAGGCCGTGATAGAATGGATAAGTCCGGACATCGTCATGTGATAACGAAGACATAT
t5        GCTGTTGGTTCACAATAACAAATAATTGAGTCACGTAGACGTATGACCACCTCTGATTCC
t6        TTTACAACGTCACAATAACACACAAATGCGTTATGTTGACGTGTGATCGTTGCCGATTAC
t7        AAGCGTGCCTTGCATAGCGATGGAGGGCTAAGACTTCAAGTCATCACGACAGATCACTCC
t8        AACCGTACCTTGGTTAGGGGGGGACGGCTTAGGCCCCGAGCTATCACGACAAATAACTCC

          GTAGATGGATTCTAAATGTGCAGCTTTGTAACGACTTGTTGCCCTTCCGAGCTTTGGCCT
          GCAGAGAGACTTATGACGTGCAATAATGAAATGACTGCTTGTCTTCGGCAGCTCTAAGTT
          GTAGACAGACCTTTGACATGTGTGTAAGCGAGGAGTGACAGATCCCCAGAACCTCAATGC
          ACCAACAGCCTAGTATTACATTGGTGGGTGGTTGTGAAGAGTCATAAGCGACTCTGAGGT
          ATCATAAGCCCTTTACCGCGTGCACGCAGAATATGACTACCATCCGTGCGATTAGTATGA
          GTCACCTGCCGCTCATGACACACTGCCAGATTGAAACAACTACCCGCGCATTTAAGATAA
          GCTACGCACCTACAGTTACCCGGAAGCGCATGCAGAGAAACATTCTCCGTAACACGCCAC
          GTTACGCATTTTCCACTCTTCGGTGGAGCATGCAGGGGAACAATCACAGCACTATGCAAC

          AGGTGAACCTGAAAATGAGGTGTTTTACGCTTTATCGTGCGTATTTCCAAGGAATCGGAA
          GGTTAAATTTGGAAACAAAGTGATATACCTTCGACCGCGAGTAGTTCTAAGTTGCCGGGA
          CCATTTATTCGGACATGAGGTTAACCCTCTCTCTCTGCGAGGGTTTTAAAGGAGACGAGG
          GCGCAATTTGGAGTCGACCGTGTTATCTGCCGTCAGAATCACCACCATGGCGAACCGGAC
          GTTTATATGGTGGCCTTAGATACATTATCTTACAATCCCTGTGACTATTATCGGTCTGGA
          GCCTCCATGGCAGTCTCAGCCGCTCTATCCTAAAAGTTCAAAGACCATTACCGGTGTGAG
          GCAAGTCTCAGAGGTTCGCCTAGCGTCTTTTCTAATATCTGCTACTATAAGGACGATGAT
          GAATGCACCGGTGGTCCACCTAGTGTCTTTTCTAACACTTTCTCTTATAGGGGCCATGCC

          GGGTCTACGCAGAGAAGTTGGGACCACCCGTCGGTGTTTTCCAGCTTCGTTGGATATAGC
          GGATTTGCGTGCGGGAGTTGGGATCATCTATTGGAGTTACACAGTTATGTTGAGTAGTAC
          GTATGCTTCCGCAGGGGAGAGTCTGATCTGTCGTAGCAACACGTCCACACTGGACGCCAG
          GGGAATACGTGTGGGCCAGGGGTCGCTTCCCTATGGTAACAAAGCGGACGGAAGCACTGA
          AGGTGCACGGGCGTGTGTCGGGCCACGCTACTCTGGTCCCAGTATGACACGGTTCACCAT
          AAGGGTGCGGGCGTGTGCGGGGCCACGTCGCTTTGGCTTGAATATCATACGCAGTGCGAG
          TGCAATACGAGGTTGCGACGGACTGTTATAGGGTAGTTAAGAGGTCGGTAAGAATATTGG
          TGCGATACGAGATTGCGCTGGGCTGCCATACTATAAAAAGGGAGTTAGTGAGAATGTAGG

          ATTTCTCCGGCTTAACATCCGTTGGATTGATGCTCAGCTACCATTTTTAGACGGCGCACA
          ACTCTTTCGGTAGGGCCCCTGACGTGTCACTACTTAATAAACATCTCTAGATGAGGTACG
          AACCTTTCAGCTGGACACACACCGTGCTCTAACCTAGCAAATATCTTTTGTTGACATACT
          TACAATGTCATGATGCTTCCCACTCGATGTGATATAACTAGAAGCAATCGGTGAGTCCCA
          ACCCCTGCTGCCCTTCTGTTAACAAGCTATTAGTGTTCAAGGTGCGTTTGAAGGAACCCA
          ACTCAGGCTGCTCTTCCGCCCTTGAGCAGCAATTGTTCAAGACTTATCTGGATGGGCCAA
          GTACGTGTAGCTAAGTTGCACGTATCTTATGGCTCTGAAAACAATGACGTGTGAAGCTTA
          GTACACGAAGCTATATTGCACGCATCTTATAGCCCCGCGGACGATTATGCGTATTGTTTA

          AGCGTGGTCTCATTTCCATCGATCATTGCGTGGAGGTGAATTTGTATGTGGGATGTCGTC
          CAGGTAGTCCTATCGCAAATGACCATTGTGTGGGCGTGAGTTCGGTGGCGGGATGTAACT
          AAGGCGGTCCGATCTCCAACAAATGCTGCGTGTGGGAAAGCATGACTGCGTGTTGCGGTC
          TGCGTAAGCCCGTGTGCAGTTTTAATCGTAATGGAGTTAGCCCCGTAGAGGGTTGTACAT
          GGCGCGCGCCCCTTTTTGGGGTCGGCCGCTCCGCAGCGTTTCCGGTCCTGGGTCGAGGCA
          AATGCACGCTCCTTTCCTCGATCAACCGTTTGACAAGGTTCCCGGTTGTGGGTTATGGCC
          ACACAACCTATGACCTCAAAGCCCGTCAAAATCCGAACGGCCACTCAGATACCCACAGGG
          ACACAACTTTCGACCTCATAGCCGGTCAAAGCCTGGACGGCCCCTTGGAGACTCGCAGGG

          CCAGCTATATCCCTTAACTAGCTAATGACCCTATTCCATGACCCAAGCTCGGGGATGTTA
          TCAATTAGATCTCATCACCGGTTAATGGTCCTATCCCATGGTCAAAGCTCGGGGACGTTA
          ATACCTCGATATCATCCCCGGTTTGTGTCGAATTTTCACGGTAGGGGTTTGGAAGTGCGA
          CGACATGAACGGCCATCAAGGTCGTTCAGTGCAATATCCCGTTAGTTAATCGAGGGAGAC
          CTCAGTCGGTTGCAGGCCTTACTAGCGAATTAAACCTTAGGATTGGTCCCAGGGATGGTT
          CTAAATTAGTGACTGGTATGTCTAACGAAGCCGATACCCGGGCGGGGCTCAGGGCTGGCA
          ATCCTAGAGCAGGAATTCAGGCCCGTGCACACATTATAGAGGAGGGTTGAGTAGACGACA
          CTCCGCGGGAAGCTCTCCGGGCTCGTGCCCACTTTTTTGGGAAGGATCGAGTCAACAACC

          TAATCACGTTCAGTACACCTATGCAAAGTAGTGGCAAGCCACAACATCCGCTGGACCATC
          AGGGTACGGGCGGTACGTGCACGTGCAATCGTGCCAGATCATTCCGTTCGCAGGATCTGA
          GGGACAATAGTGTCTTATTGATTAAGGGACGCGTTTGACCAAGCAGTCCGCAGATTCTAT
          GGGTTGCATATATAACAACAGTTGAGTGTCGGGGCCGTAAATTACTTTATTCCATACTGA
          AACTCACGGATCATCTGTCCTTCCGTAGCTGCGCTTGCTCTTAGTGTTCGGTCGGAATCA
          GAATTACGGACTTTTTGTCTTGTCAGAGCTGAGAAAGTCTTGAGGGACCGGTAGGATTCA
          AGTAGGTAGACCTAGGCATTCTACCAATCTGGGAACGCATCCAGTGTCCAGGAGTCGGAG
          AGTCGCAGGACCTGTCCACCACAATAAGTCGGGAACGCATCCAGAGTCTCGGGGATGCAG

          TTTTGCTATTTGTATTAAACGAAGCGCTCTGGAATTAGGCGTATGCCCGGTTGAATCCCA
          ACTAGCCCCGACCATTAGACGACGCACGCCGAGGTTAAGCTTGTGCGCGACAAGATTTGA
          CCTTGGATCTTGTATCTGACGACATATGCTGGAATGAGGCCTGTGCGCGACAAGGTATGA
          TCAAATTTGACTCCCTCGGCCCCCAACGACGGATTCAAGCGTCCGCTCAGTGATGAGCAG
          TATAACGTAAAGTATCCCATATTCTGCGTGGGTCTCAAGCGCTAGCACACATAGATCGGA
          CATACTGTCGAGTATTCTACACCCTGCGTGGGATTCAAGCGCTGGCCTCAAGAGGGCGGC
          TCCGACTTAATTTGACGTAAATGTCCCCTCAGCCATGAGCGCCGGCGTTCTGAGCACCAA
          TCCGGATCGAAATAACGCAACGGTCTCCCCAGTTATGAGCGCTAATGCTCTGAGGACCGA

          GACGTCCTCGGAGATAGAACGAGGCATAATGTTCCGTAGTTGGATTACTTTAGTTATAGC
          GGCGGCCAAGGGCACGGAGTATGACACAGCGCTTTGTAGCTGGGGCCCCATGGCTTTGGC
          GACGAACACGATAACGGTCTTCGTTATAGTGCATCATAGAGGCTCGATCACACCCATAGC
          CATGATTATCTAGCGGGGATCAACCGTAGTCCTAGGATACCTTAATGCTATATTAGCGTG
          TATTAATACGGGGATGGGGTTCCCTACAACCTCTCACAACCGCCTTCTCACATCCGCTAA
          AGCAGTAACCAGGAGGGAGTGCTCTACCACCGATTATAACTGCCCTAATATATCCGTTAA
          GGTCACAGTTGCGATGCAGTTCAAACAAATGAGTGTTAATATAACTCCGGGACCAGTCAT
          AGCCATAACTGCGATGTGGTCCCAATAAATGGCGGTTTATAGAAGTCCGGTACCTGCCAT

          AATAAAGCCCACTATACCCCACTGGAGGATACACGGCACCTAGTGGTTTGCATGAGCCGA
          GAAAAAGCCCATCATGTCATTTTAGCAGACATACAGAACCCAGTGGTATACGAGAGACGA
          TACACGCCCCATAACTCAACAGCAGCATGCGCTGGAAACTAAGCGGCATGACAGAGACGG
          GAGGTATCCTTGTCTTCCGTAGTGATGAAGACCTAGACCTACGAAAACTGCAAGGGGCAA
          GGCACGTCTATGTGCCTCACCAAGAAAGCCCTATAAAGGACATGAACGAACGACAGGCCT
          GATATATTCATTTGCCTCACTATGATGGCCCTATAAAGGACAAGAACCTATGACGGGCTG
          GGTGGTCTCGCGTCCTAATTTGAGGCCAGTTCCAAAGACGGAACAGTTCGCCAACCTTGG
          GATGTTCCTCCGTTTTAGTTTGAAGTTAATTCCAAGAACGGAACAGTCCGCCAACCTCGG

          TGGATCGGCCGAAACAGGGGGCTGCTCCCGCACGCGTTGGCCGACATTAGATTTCAGAGG
          TGGATAAGCCGAGACAGTGGACCACTTCTGTCCGAGCCAGTTGACATTAGGTTTCAGGGG
          TGGCTTTATCGAGGTACCCGAGTGGTCATACTCGAGCTTGCCAACATTCGGTTCTAGATG
          GTGTTTTGCAGGAACTGTATGTCATACGGTCAGGAGCATAGCTGTTGCCCAGACCGGGTG
          AAACAGAGTCACGACAATAGAGAAAAACAACTGGAGCTCGACGAACGCCGGCCTCATAGG
          AAAGTGAGCCATAACAATAGAGAAATCCCGCCGGGGTCTGACGATCGTTGGTCCAATAGG
          GCTTGATTTTGCGACTGCAGCGACAATGCCAGCATGACTAAATGTTGTGAAAACCGGATA
          GCTCGAATTTACGTCTGTGGTGACTACGCTCACACGGCCATATGCCGCCGTGACGGAGCA

          ACACCACTACGCGCGAGGACTGCATCGGATACTCAGTAAGTCTACGGAGCCCAATCGTCC
          ACTATATTATACGCGTGGTTTGCATCGGAGACTTAATGGGCTTCTGAAGCACAATTAATC
          ACCCCTCCACCTGTGAAACTGGTATCACACCGTTAACGAGGCCTCGGTGAACGGTTAATC
          AAACCGCCTCCTATAACAGTGCTTCAAACATCCAAATCGGATAATGGGGTGACACTTCGA
          AAGGCCGCTGCCATGATTCGCTCTCTACATTTCCAGACAGCTTCTGGGGCGATGCGAAAA
          ACGGCTACCGTCAACATTCCTCTACTACACTGCGAGTCAACCTCTGGGGCGACGCGAAAA
          GCACTTAAAGCCCTACCGCCTCCTTCAATTAATAAGAAAGCCCTTCAGACAACGTCGGGC
          GCACCCTGAGCCCTAGCAAGCTCATCAGTTAATAAGGAAGCATCTCAGACATTGGAAGAC

          CCCGTTTGCCCCCAGTAAGCTCCATGGTATATTAGCCTAATGTTTTAAGTGGTGCTGGTT
          CCCCTTTACCATCAGCAGGCTTCGCGGTGTACAAACCTGGCTCTTCCAGGGACGCTGGCT
          CCATCTCGCTTTCAGTAGCTTTCGAAGTGCCTTTGCATACCTCTAACTGTAGGTATGGCT
          CCCGTCTACGTCAGGTAGAGATCTTGACATTGAGAGAGGTCGAGGTCCGTGAGAACGGCT
          TTTCTCTACGCCCTATAGTTCCGCGAATACCGCGTAAGGCTCGAATTTGTGAGCCTTGTC
          CCTATCTACGTCGCATAGTGACGTGAATTCTGTATAAGGCTCCAAACCACGAGTCTGGTT
          CGCAATAGGGCTCGGCTGACCCGAAGGGTATCAGAGGAGTCCCATTCCGAAAGATTCGCT
          CGGCTTTGGACTGGCTCGATTCGAGGAGTACTACAGGAGTCATATTCTAAATGATTCGCT

          AGTAGGAAGTGCGCCAGGTGCATATACCGGTACAGAGAATTTTGGAGGCAGTGCTCGCCT
          TGAGGGGAGTGTGCCAGGTCTGGAAGTTAGTATCGGGTTACCCGAAGGCAGCAACCGCCA
          GATGGGGTGTGTACGTGGTATACTTGTCGGTCGGGACTCCCTTGAGGGGAGTAACTGCGA
          TCAGGAGTACAAAGTAACTCTTGTAGGCGGGTACACTTCCCTCTAGAGAAGTGCCGGTTG
          TGCAGGGCATATAGTAATGCTTCTTCCCTGAATCGAAATGCACGGCAGGTGCGCCCACAA
          TATGGGGAACGTAATGCCACTTCTCTTATGAACAACGATCCAAGGAGGGTGTGCTAGTAA
          TATACAGAACTAGACGATTTCAAAACGTATTGTGGAGATCGTAAGGACTCGTCACTGTGA
          TATACGGAATGAGACGGCTCACATACTTCCGGAGGAGCTAGCAAGAACTGGATTCAATAA

          GAATTTGACTTGGACAGGCAGAATATTTATATCTTTCTTCAAGTGTGACAGCTAAATATT
          GAAACTGACTAGAGTGGGTGGAGCATCTTCATCTCTTTCTAATTGCGCCCGCTCAATACT
          GGCCTCGATTTAGTCGGAGAAGATATTTGTACCTCCTTCAACGCGCGCCGGTTAGACCCC
          ATGCCTGTTGCGCGCAGATCGTGAGTTGGGTCCTTGCCTGTAAACTGCGCTCATAAATGC
          TATGTCGTGTTATATTGGGCAAGGAGGTCCTACTCCTCACTAGGGCGCTAACCTGGAACA
          CGACTATCGCCGGATTGGTCGTGCTAGCCTTTCCCGCCCACAGGGCGATCATATGGACCG
          GGAAACCACGTCGTTCGATCTAGAGATTACCGTCTCAGTGTGATAAGCAGAACTCTACTA
          GGACGCTACGTCACACGAATTAGAATCCATCGCCTTATTGAGATATTCAAAACTTTACTA

          CGAAGACGCCTAAAGACAGGCAAGAGTTCTGCCGTCCTGT
          TGGGAACAATCAGAGGCGGGTAAGAATACTGACGCTCTGC
          CGACAGCGGCCCCCGGTCAGTAACTGAGCCGCCGCTCTGC
          CGAAGTCGCTACAGTGTGGATGGTGTCTCTCACCGCCTGA
          TGAAGACGTATCCGATAGTGCGCCTAATACCGCAAGCTAT
          TATGGTCTTATCTGGGTGCGCGCTTTTTTTTGCTAACCAT
          GGACCGCGAGTAGGTGCGATCAGAGAGCACCGCTGCGTGC
          GGACCGCGATTAGACGCAAGCAGCGGACTTCGCTGAGCAC

