 8 1000
t1        GTAGACAATAGCTATCTATCAACCAAGGTTAATAATACGTTAGATTCGAGAAGTCCGCTA
t2        TTGACCAATAGCGGTTCCAGAGCGCTAGTTGACAGTACGCAAGACACGTGATACAGGTCA
t3        GTCGTCCACAGTGGATTCAGATTAATAGTAATTACTACGTTTAATTAGTGAAGCTAATCG
t4        GTGGAATATACTGGTTCCATGACGCCAGATATTAGCGAGCTCGTCACGTTAAGCGTCATA
t5        TTACACTGTATTGTTCGCAGTTCTAGGGTCGACTACTTGTTCGAGGTGTAGTCTTGGTAC
t6        TTATGCCGTATTGGTAGCAGCTCTAGGGTCGCCTCTTCGTCTGAGGCGTAAACTTAGTCC
t7        AAGATCTGTATCAGAGAGGAGGTGTGAGAAAATAATATGTGCAAAGGGAGACAATCGTTA
t8        AAGATCTGTTTCAGAGAGGAGGTGTGAAGAAATAGTATGTGCAAGGGGAGACAATCGTTA

          TTAATAATCCCTAGAACGTACGTGGTTGGTCCTAGTGCGCGAGTCCGTATTTGTTACCGG
          TTGAGACTCCCTGAAGTGTCTGCAGGTTGTCACAGTTGGTAAGCCCTACCCAAACGACTG
          CTAGGAAGTGCCGAGATGCTAGAGATTAACTGACATACGCACGCATCGATCTACTGCTTG
          CTTGAAGTACATGAAAGCCTTCCTTTCGGCCATTCTATGCTGGTGCCGTTATGTGCCTCG
          CTGGAAGCGTTTCACATATCTATCATGTGTAACAACATGTCAGGAATAAACTCCTGTTAG
          CTGGAAGCGTTTCAAATAAATATCATGTGTAACAGCACGTCAGGAATCACCCACTGTTAG
          CGAACTAACGCTGGAGTGTCTCCTGTGCGCAATAATGCGCATATCCTAATCAGCAATTGG
          CGAACTAACGCTGGAGTGTCTCCTGTGCGCAATAATGCGCATACGCAAATTAGCAATGGG

          CTGCCCAAATACCGGGGGGAGCGTAGCAGATTAGAATTTTCTAGCCCACGTTGTGATACT
          CGAGTAGCTCGCGGAGGGAAGCGCCGCAATCCAGGCCTCTCGAACTACTGATGTAACGCT
          CGAACCGCATTTCACCTGAAGTGCATTCGCTTGAGTCACCCTATGCCACGATGCATGATA
          TGAAGTGAGTACCAGAGGGAGTGCGATAAATTTGATCACTTTACATGTAGACACATCCAG
          ACACTAGTGGAGCTGGAGCCGCGGCACGTTCTCAATACACCAGATTTATGATACATCATT
          ACATTTGCGAGGCCTGAGCGACAAAAGGCCCTTAATATCTAATATTTATGATACATAATC
          TCAAATGATGTCCTCGGTAAACAAACTACCTTAGATCTTTTCAACTTCGGCCCTTCTAAT
          TCAAGTGATGTCCTCGGTAAACTAACTACCTTAGATCTTTCCAACTCCGGCCCTTCCAAT

          TGTTCAACCAGCAGCGCTGGGCGACTGTCCCTGACCCGCCATGATTAAGTTTAGGACCCT
          TGCCTGCTAAACATCGCCAAGGAGCCGGCATTACAGTGGCGGGGTAGGGCTTGCAGTATT
          TCTGAGTTCGCTCGGCCCGAGGGCCCGCTCGCGATGCGCTATTGCTGAGGTCGTGGCACC
          TGTCAGCTTTGCCACTGCGTAGTTTGGCCCTGAGCTGGAGTCAGTTAAGATAGTTGTATC
          TACTAGTCCAGCCCGGTGGGTGGTCTGTCCGCAACACCAAACCGGCGGGATATTGTGGCA
          TCTTAGTCTTGCCCAGCGGAAAGCCTGGCCACGAAACCAAATCTGCGGGATGCTGTCGCA
          CGATGTGGTTGCTTAGCTGACCACTATACCATAGTGCGGACTGGCCCAGAATGTAGGGTG
          CGTTGTGGTTGCTTAGCTGATCATTATCCCATAGTGCGGACTGGCCCAGAATTCAGGGTG

          ATAACGCTCCAATCCTTAAATGAACTTATGCTGCACTATGCACAAATGTCCTTAGGTCGG
          GAGTTACTCCATGCCCTTAACTAACTTATTACGCATCTCGTGCACGGAGGAACAGTTTGG
          GCAAACCTACTATTCACTGATCCGCCCTTTGTCGGTCTTGAATTGGGTGTACCAGCGTGG
          GCCCGCTTCTCAATCCAGAACTAACTGGCCGCACTTCCTGTACTGGCGGAATTGGCCTAA
          ACAATTTTGATGAAATTGGATTTGAGCACCACTGAGCCAATGTTAGTCTCAACCGTTTAA
          AAAATCTCGATGGTACTGGGTTTGGACACCCTTGGGCCTGAGTTGGCCTTAAGAGCTCAA
          TAGCCATTGCGGTGCTCCGAACGGGACTCAGTTATTTTGCGAACTTACCTGCTGTTTTAC
          TAGCCATTGCGGCGCTCAAAACGGGGCTCAATTATTTTGCGAACCTACCTGCTGTTTTAC

          ACGCACACCAGGGCATGTTCGTCCGATAACCTAGCTTAGTCCGGGAAGCCGTTGATCGGT
          GTGCACACTGGAACACATTCGTCTGGTAAACCAAGCTCTAACTATAGGCCATAGACTAAT
          CCTTCTAGTGAGCGGCCGTCAACACACTACCTGCCAAGAAACAGAAGGGCCCGAGCACGT
          ATGCGTGATGGCAGACAGTCGATTTACCATTAAGTAGCACGCACGCGATTTTCCACTCAA
          GACTACATTAGGCGACGGCAAACACCCGTCTAAGTTTGTTCCAATGGGCCATGCCCCCTT
          GTCTAATATCTGGAGCAACCTACAGCCGTCTAAATTTTACTCAAGAGGCCACCTGCCCTG
          TGAAGTCACAACGCCTGAGGGAGTATCGTCTTATTATGATGTCGAAAACGCCGGGCCCCA
          TGAAATCACAACGCCTCAAGGAGTATCGCCTTACTATGATGTCGAAAACGCCGGGCCCCA

          CTAATGGTTCCGAGACAATAGCTTTCCGACTCCTTCGATCTCGACATAGACACTTTGACA
          CCACTAGTAACGTGGCCCTGATGCAGTGGCGACTCTGACAAGGCCGCAGTATCCCGGAAG
          GAATGGGCCTGGACTTTGAGGCGATCTAGTAGCGGTAAGCTGAGCGTCATGTTTAAATTT
          AAAAAGGCTGGGCGTCCGACGGTCGCTGGCATTCGCTGCGGAATCCTCGTTCCCCGCCTC
          TCATTGTCCGCACAGTAAATTATTACTGGCCCGAGTAGGTAGTCCAGTCTCGGGAGGTCA
          CCATTGTCCGCCCAGTAAATTACTCCCGGTTCGAGTAGGTTGTTCATTCTGGTCAAGTCG
          GAGCTAAGTTTGCCCTAAGGCTATCCTGCCCACTTTGTTCATTTTAGTGAGAACGGTCTA
          GAGCTAAGTTTGCCCTAAGGCTCTCCCGTCTACTCTGTTCATTTGAGTGAGAACTGTCTA

          ATGCCCCAGCCTCGCCTGACACCTTTTAGTGGCTGGGCTATTGCTAGCGGACAGAACGCA
          ACGCTCCAGTTTTGCAAGTCGCTTTCTGGTCGGTGCGATTCACTTAGTGGCTCGGCCTTA
          GAGGTATGCCCCTGTCTAACAAATCACTGTCGAGGAGCCTTGGAAAGTGGTCAAACCATA
          GCGCGACCCTCCTGTCTAACACTCTTCATTCGAGGCGCCCACTCAAGCGGACGGACTGGA
          TCATTCAGCCTTAGTGACTAGATTATTCATCCAGAAACAATTCATGGCGCACAGTCTGCT
          TCGTCCAGTCTCGGCGTCTCGATTATTCATACAGAAACCATTCATGGCGCACAGTCAACT
          GTGGGTAACTCTAATATAATAGCTCTCCGCGTTTAGGGTTTTCAGGACGGTCCCGGCCTG
          GCGGGTAATACTAATATAACAGCTCTCCGCGTTTAGGGTTTTCAGGACGGTCCCGGCTTG

          TGCCAAACTCGGTCCCCTTCCTACATCCGGTTGCCCGTGGCACCTTAAGTCTGGGGATAC
          CTTCAACATTTCTGACTTTGGATCACCTGGATTTCTCGAATAGTACAGTTTTGAAGATAC
          TATTAATAAATCGGTCTTGTCACCAGCTCGTCGTCCCAAACTTTCCGCATTCAAGGATGC
          GATTCACATATTAGCCTTTGCCTCCGTTCACTATTCCAACAAATACGGGCCGTAAAGTGG
          TTCCATTTGCCGGGTTTCCGTTTGGTCCTGCTACTCTAGCAGAATCACACGCGATCGCGA
          CACTATTTTCCCGGTTTCCGTCTGGCCTCGGCACTCTAACAGGGTGAAACACGATCGCGA
          GGTTCTATGTCTAATATGAGCTACGAATGATCTGTCCGTCCGGCTCACTCCTAATAATGA
          GGTTCAATGTCTAACATGAGCCACGAATGATCTGCCCGTCCGACTCACTCCTAATAATGA

          AGTTCGTTAGGGGGTGTAAGTTATTACTCATGAGATGTCCTAACGTCGATTCGTTGAAGG
          AGTTGCTTACGATGGGTAAGTTGCCTTGGGTGGGGCGTTTACACGCGGGCGCGTTGAGTG
          ACAGGCCCTAATGGAGGATATTAGTCCTGCATGAATAACCTAACTCAAGCTAGGGGCTTG
          AGCGGCATAGACGAGGTAGGCCAACTTTATCTAGTTTCCCTTGCGTCAATACGAAGACTG
          GCTGGCAAGGCGGGAATCAGCGTGTGCGGTTGAAGAATGGCAGCATCTGAGTATTTGCCC
          GCCGATTAGGGTGGAGTCAGCGTTTATGATCGTAAAATGGCAGCATCCGAGAATTTGTCC
          TCTACATAAGACAATGAGGGTTAGACACTCCAACGTATATTGTTATTAGCATACGGACGA
          TCTACATCAGACAATGAGGGTTAGACACTCCAACGTAAATTGTTCTTAGTATAAGGACGA

          CGGCTCTATCTAGCTGGAAGGGGATTAATGATTACTGGATTGCTTCTTTTCCCGTTCCCG
          CAACATCATCTAATTCCATTAGGATTGACAGTCGCTAGATTGCTAGCCTAGCCCATTTCG
          AGCAGCGGAGTTGTTGCAATCGACTCAGCAATCACCAGATGGCCACTCACATCGTTTGCA
          AGGTACAGTGTCTTAGCAAATGACTTAAGAATTTTAAGCCGGCATTCAACTTGCTTCTTA
          AGTCCTTGAACTGCTGTAACTAATCCCAAAATTCTGTTGTGAGAGTCTGAGGCCCTACTT
          TGTCCTCGAGATACTGCGTCTAATCACGGAATTCCGAAATGACCATTGGAGGCTCTCCCA
          CATTAATAACCAGCTACCCTCAATCTAAGTTCTACAGAATACTCCTTTACCCCCATTGAG
          CATTATCAACCAGCTACACTCAAACTAAGTTCCATGGAATACCCCTTTACCCCCATTGAG

          GAGCCGTCGATAGGACCGTCACCGGATTCAGGAAAAGGACCAGAGTAATTGTGTCGGACG
          GTATCGTCAACGAGCTAACCATCCAACCCGGGAGAAAGATGGCAGAGACTGTAGCAACCG
          ATACCGTCTCCCAATCATTTGTACCCTCCGGTGCAGGGCACCCAGTCGCCGAACCATTTG
          TCATCGATTCTACCACTAACATCTGACCGATCATTAGCTCTTAGGAGGCCGGGTCGCCCG
          ACGCGGGAGTCCTGAATATGAGCCGTGCGGCCACTCGGCTCCCCACACCCGATCTGCAGG
          ACGTGGCTGTCTTGAATGTTAACAGTACGGCCACTCGACCCTCCGCGCTCGATTTGTGGG
          TTGCGACCAACAAAAATTAAAGCTTAGACCAGGACACGTTTGAGACATGAGGTCAATAAG
          TTGTGACCAACAAAAATTAAAGCTTAGACCAGGACACGTTTGAGACATGAGGTCAATAAG

          CCCCGCTTTCGCGAGGTAAAGCCTTTGTAGTTCTGGAGAATAATAGAGTAAATCACGAAC
          ATTCGCTCCCGTGACGCGAAATCTTCCTAATCCCGGCAAATTTTAGTATGTTGCACGGAT
          AGCCGTCCTACCGCTGCTAAGCCCTAATGACCGTTGAGCGCTTTCGACTATGCACCAAAA
          GGGCGCCCTAGCAATGTAAAACTCTAACAGTAGCAGATTACTCTGGTTTCTAGTGTAGTG
          CATGAGTACTCACACGTCAAAATCTAATAGCTGTGTGCGGTTCTAAACATCATGTCCTTT
          TACGGGCATGCACACGTCGAAACCTAACAGCTTTACGCGATTCTAATCAATACGTTGCTT
          CACATACCCTTGGATTCCGGCTCCTAACTTCTAGCGGAGGTCTTCACCGATGCCCTACTT
          CACATTCCGTCCGACTCCGGCTCCTAACCTCTAGCGCAGGTCATAACCGATGCTCTATTT

          GCATGTGAGAAGAGAGCGCCAAACTAGACGAAACGGCGCTGACCCGGTCAAGAATATACG
          ATCAAGGCAGAAACAGCATCAAGGAATACGATACAGCTACGCCTTATCCAGTAAAGAATG
          ATCCTTGGTGACAAACCAGCCGGTTAGCTGCTACAGCTCCGCTTCATTTAGTGGAGAGCG
          ACTTTCGAAGGAGAACAAAACAAATAGGCGATTTGGCCCCGGTCCGGCATGTACAGCCCG
          GACTATGCGCGTGGACCAAAGAGTATTATAGCCCGGTTCCGATGCTGTCGCTAGAACGCA
          CACTATGCGGGCGGACCATCTAGTTGTATAACATGGATCCGATGTCGCCGCCAAACCGCA
          GACCAATTGGGAGGCTGACTACATTAGGCCACCTGGACCATGCCTCATTAACAGTACACT
          GGCCAATTGGGCGGCTGACTCCACTAGGCCACCTGGACCATGTCTCATTCACAGTACACC

          AACCTTGCGAATAGACTAGACATGTCCTGCGCGCTGCCATTTGACCTGCGCTCCATACTC
          AGCCTTGTGAGTGATCTTATCATATTTGGTAAGTACCAACTGGTTTTACGCTTCATGCTC
          AACCGTGCGGAAATACCGAACATACTTTGCAAGTAAAAGTCCGCTTCGCCCCCTAAGTTT
          AGCTCTGCGAAGCCACTGAACCTGTCTCTACCGCTTCAGTCTCACGCGCGCCCCCAGGCC
          TCACTGCCCTACTGCCTGACGGAATCACAAATGCCGGTTCGCAATCTACCTTCAAGCCTA
          TCACTGCCAGCTTGCGTGACGGAATGAAAAAAGTCCGATCAGGATGCGACTTCAAGACTC
          TAGATTTTACATGGTAGAATGCGTCCTCGGAAGCTGTGTTTTGGGTAACTAATTGGCTTT
          TATATTTTACATGGTAGGATGCGTCCTCGGAAGCTGTGTTTCGGGTGATTAATTGGCTTC

          TAGATAATTCACCCGTCACACTGCCTGCGCTTAAGTAATCATATGCAGATGCATCAGCAC
          CCCAAGACAACTCGGAAATATCGCCCACGTTTAAGAAGATACGCTAATCCTTAATAGTTG
          TCCAGGACCCTTCGTATACCTGGCGGGCAGTGAAGAGTGCACCCCTTCTTGGAAAGGCAA
          TACGAGGTTTGTCGGCCCCTCCGTGCGCTCCTACGAAGGTACGAGCTATGACGCAAGATA
          CACATGGTTCAATCAGTACGTCCCAAATGCCGAGGAAGGACGCCGAAGCTGCGCCTTTCA
          CAATAAGTGCTATCAGTACGTCCCCGATGCTGGTGAAGGACGCCGAAGTAGCGACGCTCA
          GCCCGCCAGTCGAATCCAACTCGCCTGCGCTTGCGGACGAGCGCGGATCACCAGGAACTA
          GCCTGCCAATCGAATCCAACGCGCCTGCGCTTGCGGATGAGCTCGGGTCACCAGGAACTA

          AGACAGTCCCCCAACATGTCTCCGCTTCTCAATCTTTTCG
          TCTCGATATTATTACGTGGCTTTGTCGTAAGACAACAGCA
          CTCCAAGCTCTCCAACTGTTCCTGTCTCACGCGCCGACGC
          TACTATATCGTTCTATTCTTTCTGCTAGATGAACTCACCT
          ACCGAAATCCTATATTTCTTTTCCAACCGTAATCCCAACA
          ATGGATATCTTATGTCTATCTTCCCACCTCAGTCCCAACC
          TACAAACCCCCGTGTCTTACCACAGGACATACTACTGTTG
          AACAACCCCCCGTGTCTCACCATAGGACATAGTACTGTTG

