 8 1000
t1        CAGGCCAACACTGTTTATGATGAAAGTGAATTCAAGAGCGTGTGTTCCCGGATGTACTCG
t2        AAGGCCAACATTGTTTATGATAAAAGTGAATTCAAGAGTGTCTGTTCCCGGATATACTCG
t3        GGAACTACCATCCTGCATGGTGGGCTTGAAAGTGCAAAAATATACATCCGAACATACTTG
t4        CCCGCTGCTGTCGTTAGAGTAGAGAATGCAGGCTCCAGAGCTTGTACTTGGATGTAACCG
t5        TCGACCAGCGTAGTTTAAATCGAGCCTGTAGACATGAAGCTTTTTCCTCGGGTCTATGGG
t6        TCGGTCTCCATTGTTCAAGACGCGCGCGAGGGAGCAACGTCTTGGTATGGCTATTGATTG
t7        TAAATGAGCCATGCACAAGTAAGGCACTATAGCGCGAGCGCTTAAGTTTGAGAGTGAGTT
t8        CGGATGTCAATTATACGAATAAAAATGTATAAACCACAGAAAGGGCTCTCGCCCTACGCA

          CAGAACATGATTGCGAGGACGCTCCTTAGCTTACTCATTGTGTCGTGGTCAGATTTACGG
          CAGAACATGATTGCGAGGATGTTCCTTAGCTTGCAAATTGTGTCGTGGTCAGATTTACGG
          CAGACCCCCTAGATGAGGGAGTTCTCCGGCTCGCTCGTGGTGATCAGGTAAGATTAACGG
          TAGGAAGCCTAAGCGAGGGCGATTCTCAGCTTGCTCTAAGCGATCATCTTACACTTACGG
          AAAACCTTCTTATTGGCGGCGTCCGGCTGCCTACATATTGCGATCATGCTAGAACCACGT
          TAGATCACACGTACAAAGTCAATACCCCCCCTGTTTATTCCGAATAGGCCTGGTTCGTGT
          AACATATCGGTACTGGGTCAGACGCCCTCTGCCTACCTTCTTATCATGTTACATGTTCGG
          CAGCTATCACTAGAACATCCGGCCCCTGCTCCTTAGGATAATAACGCTTTTCGTTTGACA

          CCCCTCTTAAGCTGATACTTGTTCCGGTAGAGCCAGATAAAACAACTGTTGCCGGTACGG
          CTCCATTTAAGCTGGTACTTGTTCCGGTAGTGCCAGATCAGACAACTGTTGTCGGTACGG
          ATCCTCCCGCGTTGTTACATCTGCCAGTCGACCCCGGCCCGCTTAAGGTTCCCGGAGAGG
          CTTCTTCCATGGTGATATTCCTGACAGCGCAGTACGATGGGAGACGGGTTCTCGGAGTGG
          CCCCTTCTCTGATCATTCAACCGTTATCCAAGCGTGACCGCGCAAAGCCGCCCGGCGTAG
          CCTAATCACAACCGGCATCTTGTTTGGTGGCTAACTAAAGGATGGAAGATCTCTGTGAGG
          TCTTTTTTGAGCTAGAACTCCAGATGGAGAGGCTCCGGGGGAGACAGGGAATCGGGATAA
          TCAGTAAAAGGCAGTCACTCTTGTCTGCCATAGTCAATGTACATGATAAGGCGAGGTCGG

          TGGTCTCAGACCCAAGCGCCCGCTGGATCGGCCCTCCAGGAAATGTACACCCCCCTGGTC
          CGGTCTCAGACTCAAGCGCTCGCTAGATCGGCTCTCCAGGAAATGTACACCCCCCTGGTC
          TGATCCTTAACACTAGTACTCACTCGCCCGTATACCCGGGAGGTCCGCAGCTCTCTAACT
          CGCTCTAAGACAGAAAAGCCCACTCGTCTGCCCTCATGCAAAACGTGTAGTCCGTTAGTG
          CATTCCCAGGCACAAACGCCAAACAGCCAGTCTGTGTAGAAAACGTTTAACCTCTAGATT
          CGCTGGCGAGGACACGCGCTCACCTAATAATTCCTCTAGAAGATGAGTAAGCGATTGGAC
          CGTGTCGGTCCATAAGTGTCCGCTCGCCCGCATTTGCTGTGGATCGGACGGTCATTATAC
          TGACCATCGCAGTGTATGTCTTATAGCTTTCGGTGCGCCTAACGTAATCCGTTCCTCCTC

          GCACTTGCAACTCGTGCCTATTAGTATATCGTACTGAGCGTTACCAGACACCTCTGAAGA
          GCACTTGCAACTCGTGCCTTTTAGTATATCGTACCGAGCGTTACCAGACTCCTCCGAAGG
          GTTAATAATTCCGGTGCCTGCTCGTATCACATAGTATAAACTACCAACTATCTCCGAAAA
          GCTATTAACCCTTATGCTTGCTCACATATCATCGAGCCAGCTGTCAATCGTCATAGGGAA
          GCTAATCTGGGTCGCCCGCATCCATTCATTGGTGAGGCAGCTATCAAACATTTTAGAAAT
          CTCATTGCAACTCACCTTCTCACACCTCTGGCAGAGAACCTAGCTGGCCATCCTAGAGGG
          AGTAATACTCTCAGACTTCGCTAACGAGTCGCTAGGCATAGTCCTCAGCTGCTCAAAACC
          TACATCCCTTGTAGACCTTCTGGGCCGATTTTAAGGCGCGTGGCTTGGTGTTGGGGATGT

          CACAGCGTGTCGTTCTACCACCGTTGTAACCGATGGGAGTCTATGTAATGGACGGAGATG
          CACAACGTGTCGTTCTACCACCGTCGTAACCGCTTGGAGTTTATGTAGTGGACGGAGATG
          CCCACTGCCCCTATCAATTTCCGATGTAAGTATGAGGCCCCTATGCTGTGAGTCGAGACG
          CGCAATGCGCCTTTGGGCTACCGACGTAGACGCTAGGAATCTACGTTGTATGCGGGGGTG
          CACGCAGCACCGTACTACCGTCGTTGCAGGATCCGGGAATTCTTCCTCTGTGCAGAAACC
          ATGGTTCTATTAAGTTATCCCCAACGGTAGCGTTAGGCAACTAGGTTTCGATATGAGCTG
          CTAGGCATGGCGAATTAGTGCGGATAGCGGCGACCAGAGTGGCACCAGTGAAGCGAAAAG
          CCCCGGGTGGCGCATCACCAATCCTCCATTCGCCCAAAAGGTCGATGATGAGTTAAATCC

          GAACTTACGTAGGCTAGATGAGAGTTCGAAGGTATGATGGAACATCACAAACTATCTACT
          GAAGTTACGTAGGCTAGATGAGAATTCGAAGGTATGATGGTACATCACAGACTAACTACT
          GAAGCTGCATAGACCGGTTGAGGACTCACGAATACGGGAGTATGTTCCGAAGTATCCGCC
          GGAGCGGCGAATGGTATTCGAGAGCCTGAGAGTGTGAAAGCTCATCGCACGGTGCCCGAT
          GATCGAATGCATACCTGGTAAGTTATTAAGTGTAGGATAGTGCGTAATGAGGGGCTGATT
          GAGGCCATGCGTAGCAGCAAGGATTTTATGTTTGAGGGAGCATTTCACGAGGGACATTTC
          AAAAAAGAGGATACCTGTAGAGAATCTGTAAGCGCTAGATAGACTCGTAATTATCGTTTC
          GGATCCTTGACGGTCCACTTCAATTTCAAGAACGTTCGCGTACACCGCCACCATGGATAT

          ACTACGAAGATACTTCACAAAATCCAAGTCATGAACCGACTAACGGAGAAGGCAATACAA
          ACTACGAAAATACTTCACAAAATCCAAGTCATGAACCGACCAATGGACAAGGCAATGCAT
          CCTACCGTAATATCTCGTACAATCTTAGTTGGGGCCGAAGTCACGACGAAGGCGTTGCGC
          ACGTACCCCCTACCTAACTTAACGTAAGCAATGAACCGCCAAGCGCAGAAGGTGTTGCGA
          CCACCAGCACGTTCTTACATAACGAAAGTTACGGGCCTACATACGGAAGAAGCGGTGCGG
          ATCCCTACGATATATTCGATCATTCAGGTCTCAGTCGGCCTGAAGGACTGGGGGGTGTGA
          GTTACAAAACTCCTACGTCACACCTGCTCTGCGGCCCGGCGATCGAATCAGGGCACGCTA
          ATATGTGCTGAACCTACTACTCCTTTGGCCCCAAGTCCGTATGTGGGCAGCGACGTGCTA

          GACCGGATGCGAGCATCTGATCTCTTAGCACCAAAGGCCATAGACTCATATCTCACAATT
          GACCGGATGCGAGCATCTGATCCCTTGGCAACGAAGGCCAGAGACTTATATCTCACAATT
          GGGACTACGCGGGTCTTTGCTTCCCCAGCGGTATAGGCCACTGGTCCCCACCTTACAGCC
          CACCCGTTGCATGCCTGTGCCTTCGTGACGACACAAGCCAAAGGTCAACACTTCCCAATT
          GGAAAAACTCAGGCCAGCGGCTTATTGACTACATAGGCCACGGAGCAAGACGTCTCGACT
          GGTCAAGAGCGGGCGATCGGTCTTTCGGCCATCTAGAATTCGGACCTGGCCCACTAGACT
          GGCCTGTCAACGGGGGTAGATTTTTTGGTGTTGTCGGACTGGGATTTCGTGATCTTTTCT
          GTCTCGATCTTGGAAACAGACTTCGCAGATACGTAAGCAAGTCGGCTGGGCGCATCGTAT

          GGTGAGCCGAGTTTCTGTTAGTAAATAGCGTTTAATGGATGGTGCTCTCTGTTCCCAGAC
          GGTGAGCCGAGTTTCTGTTAGTGAATAGCGTTTAATGGATGGTGCTCTCGGTTCCCGGAC
          AACTAGTCGGGATTCTGTTAGTCAATCGGATTCAAATGGAGACACTCGCCCCTACTCGGC
          AATCAGCTCAAAACCCGACAGTGAATTATCATTGATGTTGCCCACCCAATACTTCTAGGT
          AGACAACCGACGTTCTGTTAGCGATCAGATCTAGATGACATACAGCTGAAATTCTCAAGC
          GTTAAGCTGAGAACTTATTTTTGACATATACTCGTTAACGCGCATGCGTATCCACATAGC
          CGTTGGTCGAAATTTTGAGCGATGAACACGCTCCATCCCGCTAAGTTCTGATTATAAGGC
          GGGTGGTCGTCCCTCAGCGCCCTAATCGACATAAATTGAGCAAGCTCGTGTGCATTCAAC

          GCTTGCAAGTATTAGGCACGGTGTTCTCATAGTGATGCTTAGCTTCTGTTGGAAAGATTT
          GCTTGCAAATATTAATCACGGTATTCTCATAGTGATGCTTAGCTTCTGTCGGAAAGATTT
          CCTTTCGATCTACGGGCACGATGCGTTCGTATAAACACCCAATCATAGTCGGAAGGGTCC
          ACATTTACTCAGAACACACGATTCTTCTATTCCATTACCACACAATTGCCGAAAAGCTCC
          GCTTCCGTCTTTAAGCAATCTCTTCTCTATATCAGCAGCCAACCAATTTTGTTAAAATTC
          ACTCTAGCCTCAAGCAGGCCACCTTTTCATACTGTCCCTCCTTAGTCCCCGGAAGTCCTC
          GGACGCTAGATGTATATTAGCCACCCTAGTACCAACATTGATCTAGCGGTTGAAGGACTT
          GCCATTCTTCTAATGTCCGACGACTACAAGCTTAACGCTTTACTCGAGATAGTTAGTATA

          AACACGCAAAGCGTGTACCTATATAAGCGCGGGCTAAGAAATACATTTCCTTCAATCCCA
          AGCTCGCAATGCGTGTACCTATATCAGCGCGGGCTAAAAGATCCATTTCCTTCCCTCCCA
          AGCGTGTAAAACCGGCATCTTCTTTCGCGAGGGTCAATGTTTACATTCCTCCTTCCCAAA
          AGAATGTAAGGCGAATACTTTCATACGGAAGTACCAACATTAGCCTCTCCTCTATACAGA
          GTAATGCAGAGTGTACATCTCGCTTCGGGAAGGTCAACATTAATATTTCCTAGTCACAAA
          ACGATAAACAACGACCACCTCTCATTTCGTGGCTAGCTCCATGCACAATCTTTCCTCGTG
          ACTAGGCTGACTATCCGTGCACTCCTAAAGATTCTACCGAACGATCACCACGGAGTTGTT
          CCGGAAGTAAGATAGAGACTCTCTTCAGCCTTACCGAGGTACGTCGCTATCTGCGACACC

          CAGGCCTCTCTTATCCGCACTACGTGCCACTTCATTCTCTTAGGGATCCCGAGCGCCGTG
          CAGGCCTCTTTTATCCGTACTATATGCCACTTCATTCGCTTACGGATCCCGCGCATAGTG
          TAGGTTCCTCTTCTTTATCCTGCACGCACCTTCATTTGCTTGTGACTCCCACACATTAAA
          TGATCCCCTCTTCTAAGAGTCCCCTGCCTTTTCATTTGATTAATATTCCCATATGTTGAA
          TCTCTGGTTCATAACAGATCTGGAGGTTTTTTCATTTGGTCGGGGCCTTCGTACTTCGCG
          TCGATGATACACCAAGACTTCGGTGGACGCTTTACCCGGCTACAGCTATCACTCAATCAG
          ATGTTGGGTACTGTCGTGCTTGCTTAGGGCTCTCCAAGCCATGAGCAAATGCCTGCCAGA
          CTATTGAGCACATCCGCCACCGTATATCTAATCCAATTCTTCTAATAATCCGCTCTCCAA

          GAATAAGTAGTCTTGTGTAGCATTCGTTGCCCGCTCTAAATCCTCGAAAGTCGGCCTTAG
          GAATAAGTAATCTTGTGTAGCATTCGCTGCCCACCCTAAATCCTCGAAAGTCGGCCTTGG
          CAGCAAATATGCCACCGAAGGGCTGGATGCTAGTCTTAAATCATTGAGAGCTAGTCCTAA
          AGGCATAATTGTACAGATAACGCCGGCTACTAACCTTATCCCCTTGAACGCCGGTCTTTG
          ACGCACGAGTACTCATTTCAGGTTGGTGGCTCCCCCTCTATCTTGGGGAGCTAGTCCTGC
          CACCGTGGTTACGAACTTCCCGACGGATCCTCATTCGCTTCACAGTAAATTCGAGCATGG
          AACAGCGAGCGTATTCGAACCGATGGGCCTAGGTTCCCTTTCACGGTAGAGAGATTCTGG
          GCTTTTAGACGTAATAACAATCTCGATGGTACCTTCCCCGTTGCGCCAATGCAATAACGC

          CGACAATAATACACTACAGCCTGCAGTTGGATTAGAGTTCGGCGCCCGCGTCACGTTGCG
          AGACAATAATACACTACAGCCTGCAGTCGGATTAGAGTTCGGCGCCCGCGTCACGTTGCA
          AGACGACCATGTACTGCATTTTGTCTTCGGTTTCACGAATAGCTCACACGCTCATCTGGG
          AGGCAGCTTTCCTTTGGATCCCGCGGTCGGTCTGACGTAGAGTATTTGTACTGCGTTACG
          ACACGCCCATATGGGACCCCCTTCAACCGGATCAACATACGGTACGTGTGGCACGCTGCT
          GGAGAAATAAATACCATCCTTCCCAGTTAGGCATGCGTGAAGTATCCTCTTGCTGACGTG
          GTATCCTGCCACCAGACCATTTCTACAGTCTATGACCGGCGCTACGGGTAAGTCGTTGCG
          TGAAAAATTTGCGTCACACTGACCACAGGGGCAAACTTGCACTCTAAACAACTCGCTGGG

          ATGCTTAGGCACTACTCCGTTCGCTACATGGCATATCTAATGGTGGTGAATGCTACTTGG
          ATGTTTAGGCACTACTCCATTCGCTACATGGTATATCTAATGGTGGTGAATGCTACCTGC
          GCACTTACGCACTGCCATGCTTATGTTGTGGCACATCTATCGGGGGTGACCACCGCCCAG
          GCTCCCGTACGCCCTCCTGCGTGCATTCAGGTGTATATGATTGTGGTAGCTGTCGGTTCA
          GAGTACGCGCAGTACCCATCTTCTACAACGTCATATCCAATGGCAACCGCTATTGCCTAG
          AAAACTACGCGCCTTCTTGTCCGCGACGCGCCACAGTATACGGTGACTAGCTACGTTCTG
          GAGGGTATCCACCGCTCCACAATCATCGGACTTAATCAGGTGACAGTTAACTCCGCTTGC
          ATAGGAGCGCTCAAAGTTAGGGAGACTAAGAGACGATTATCTTGTGCCGGTTTAATAGAG

          CAAGACCGGCACTAACTACGTATTTACAGGGACCGGTGTT
          CAAGACCGGCACTAACTACGTATTTACAGGGACCGGTGTT
          CAAGATATCTATACACTACGATCTCATGAGGTGGTGTGCT
          TGACACCTGTCTCAATCGCGAGTCCCCGTGGACGTATGTC
          CAAAATGTGCATCAACCAGGTACCTATGGGGACGTGAGTT
          CGTTATCGGCATTAAGACGGAAATAGTCAGGGGGTCTATT
          CTTACGGTAAAACAACGGTGACGCCATCGCGAGGTGTGAG
          AAGGTTCAACGTCCGCAACGAGAGCGCGGCGATTTGGACG

