 8 1000
t1        ACGGGGTCGAAACGGTCTCAGTATGTGATCGTCTGGAACGGTCAGCTAGTACGCATGTCC
t2        CCGCTGTTGGAGTGGCTTCAGCATGCAGCCGCTCGGGACGGACAGGCAGCACCCATGTCT
t3        CTGCCATTGTAGTGATTTCGATATGCGGCCGTTCAAGGCACGTAGGCACAAGATATGTTG
t4        CTACCAGGGGGGTGGTTCAAGCATGTGATCTCCTGGGGCGGACATGCTAAACCAACGATC
t5        TTGCTAACTGATTCGTTAGACCGTCTAAAGCGTTTAGTCGTGTGATTTAAATGCACCCTC
t6        TCATTAGCATTTCCGCTTTCACGCCTATAGCGTTCTATAGTTTGGCTTGGACGTCCCCTA
t7        TCGCTATTTGTCCTGACCACGCGCGAGGCGTGCTCTAGTCCACGGTCGAACGTCTTGGCA
t8        TACTCAAGTGTCACGGCTTAATGTCAGGAGTGTATAGACATGCGATCTAACTGCATTGCT

          CAGTATCTTGCCGTAGTATACTAATATGGAGTGCATCGTCGGAGTTTTCTCGAGTCCTCG
          CAGTCTGTCGTCGTCGTATACTAGAACAGAGCGCACTGTTGAAATTTTCCTGATTCATTG
          CTACGTCCATTTCCTGCATGCCCGGAGAGACCAAATAAGCAACCTTCTCTGGGGCCATCG
          CTGAGCATAGTGATGGTATGCGCAGATAGAGGATGCGTCTAGAGCTACCCGGGGTCCACA
          TTGCGACCGGGGACTGAGACCTGAGGCCAACTATAGCTGTGGAGGTGGGTCGCTGGGCTA
          CTGCGACCGGAAGCTCAAGGTTGAAATGAAGACTAGTTTCGGCAATGGGTTGACGCGCAA
          TTGTAACTGGCGAATCAGACCAGACGTCAGGTCAGACCCTGAAAGTAGGCTGCAACGCCA
          TCGCGACTGACGGATCAGAGCCGGGGTTAAGAAAGGAACTGTACGTGGGCCGTGACGCCA

          TTTTCGTGTTCATCGTGTAAGGTGTCGAATGGCGGACCCGCAGGCTTTTGCCCTACATCG
          CTTCTGTGGACGACTCGTGAGGTCCTGGACGCAGGAGCTGCAGACTTCCGATTTATACCG
          ATACTGCTGCCATGGCTTGTAGTCCGATCTGACGGATCTGCGGAACTCTGACTAGTGGCT
          TCTCTACTGCCGTAATATGGCGTCCGATTTGGCTGCTCCGCACCACTCCGAGCAATGTTG
          AATCTGTGGGACCGTTAGCCTACATCTTGCGGGGGGGAAGAGTGCCGGCGAGTCAAGTGA
          ATCCCGTACGGACATCAGACCGAGTATTGTGATAGAGAAGTGGGCCATGGAGCCATGCGG
          ATCATGCTCAAACTTAAGGCAATGCATTCGGAGAGGGAAATGCGTCGCGGCTTCAGGAGG
          GCCGTGGACAGAATTTAGTAAACGCTTTGTAAGAGGGAAGTGAGCCGTAAAATTAGGGGA

          CTTCCCAAATCGAGGCAGTCACAAGAGACAATCTCCTGTCAATTTACTTCTGATGAGCTT
          GTTTCCGAATTGAGGTAATCCCCCAAGCCACTACGCTGTCGACGCACCTCTGCTGAGTTT
          ATCGCCGAATCGGAGAGGCCCCTCAGTAAATTATCCTGTTGGTGTACCTGCGTTAAGCTT
          CTCCTCTACCCGGAAACGCTTATCAAAAAGTCCCCGTATTGGTTTAGCCTCGCTAGGCTC
          GCGTCTGGACCCCGCCTGAACTATAGGACGTAGTATGTGCTACGCGTTCTATGAGAACTT
          GCGTCTGCTCTGCCCTGGACCTTTGGGCGGTCGCGTCAACCCCACAGACGGCTAGATCCT
          GCATCAGGACCACACGGAATTATATGGAGTTTGCGGTCCTTCCACGTCGTATAAGAACCC
          GCACCTGAATTATACGGACTTGAATGAAGGACGCGCACTTTTCACGGTTTGTAAGAATTC

          AATCGTCCTAGCGAACTTGAATTATCACGAGCCCGCAATATTTGTGCGAAAGATTCCGAC
          TTTTGTCCTAGCTTATTTGAATTAAGACGAATTTACATGGTTTGCAGGAAAGCATCCGAC
          CATTGATTTCGCCAGAAGGGAGATCAAGATGTCTATAAGGTTTTTCATTCACAGTCACAC
          TGCTGATCGAGCGCGGCAGAGTTCTGGCGATCTTATAAGTACCTATCGAAACACTCACCT
          GACAGTCTGCCGCAGAGTGATTTCAAGAGTTGCCGAACGAGTCCTGTGACGGCCGGGGTT
          ATCATTATCTGTATGTGAGGCGTCTAGGAGGGCCCAATGCGACTAGGGATGGCTGCGCTT
          TGGAGTTCCTGCTGGATGGGCATTTTTACAATCTAAATCAGTCTAGTGGCGGTCACATTC
          AGCAGTTTTTGACAAGCGGGCACTTTGAGAAGCCAAATCTGCCTCAAGATCGCTAAAGTT

          AGGACGCACAAAGTTGTTTTCACACAATGTCACCGACCGACTTTGAAATCAAACAGTCGA
          CGGTCGGACAAACTCGTTTTTACAGAATGCCGCCCATCCGCTTTCAGATCAGCCAGACGA
          ATGTCAGTTTATATTGTGGCTGCGCGAGATACCATAACAGTCTCCACTTGGTACAGGTAA
          ACACCAATCGATGTTGCCATCCTTCGATACCTATTAATAGTCCTCGCCTCTGACAGCTAA
          GCGTGATGATCTCAGGCTTTAACCTTGCGCTTTCAGGACGCCTCGCCTTCGGGAACCGGA
          GCGCGGCGATCTCAGGATGTTGCATTGTACTTATTTTAAATATCGCTGATTGGCCTGTAA
          AAGCAGCGCTCTAAGGCCGATGGCCTGTGCATCCACTATACAACGCTCGCGGGCCGGCAA
          ATGAAGCACTCGAAGACTGTTATATTGGGTATTCAAGTTAGATCAATCATGGGCCGACAA

          CACGGGATAGGAAGAATGCGTAAAGCCGGGTGTTATGGGGTCTGCATGGTGCGGGTGCCA
          CCCGGAGTGGACAGAATGCGGAGTCCCGGGTGTTAAGGGTGCTGCTTGGATCGGGTGCCA
          CTCGTTATTGCAAATACCTGATACACCGTGTAACACGGGGTCAGCGGAGATTGCTAGCCG
          CCTGCTAGCCGGCGTAGCTCTTACTCCGTGCGGCGGGGGCTTAGTAGGATCCGTGTGTTG
          CCCTGTATCCGCAACAGTGCCCACCCTAAACGCGATACCAGCCGAGAATTACTGGTGAAA
          ATCGAGAGCCGTAGTAATGTGTAATTCAACCGCGTTGCAAACCAGAGATTACGCGTGTTA
          ATCAACAACCGTTATAGTACCCAGTCTAAAAGCGACACGATCCCAGAGCTGCGCAAGCTA
          GTCGACACTTTTGGAAGTACCTAGTCCAGAAGGGACGCGATCTCAGGGGTTAGGGTTCTA

          ACCGGAAATATGATCCCACCAGGCTACCAATCGAGTACGCAGACTCACTGGGCCGCTGGT
          ACCGAAAATATGGCACCATCCGGCAAGCACTTGAGTACGCAGAATCATGGGGTTGATCGT
          ATTGATACTACGACACCAGCAGAAACTAATCTGACTGTATAGCGCAATCGGGCCACGGAT
          GATGTAAACCCAACACCAACCAGCATATATTCGACTATATAGAGTGACCGGGTTATGGCG
          AAAGTTATTGATAGAATCACCTTGAACAGCCCATCCTCGCTGAGTTAAAACAGGAAGGAT
          CAGGCCATTATTATAATGGACGGCGATGATACACATCCTGTACACAAGAACAAGCTTTAA
          TATAACGGCATTAGGATTGACTGTGATCAGCCACATTCGCCGCGCAAGGACCAGGGCTAG
          TATAGTGGTTTCGGACCGGCTTGCCCTCATCCACATCCGTCGTGTGAAATTAGGAAGCAT

          ATTTGATCTAGCGTCGGTAAATCCTCTATAACGACGCGCCTGGTTTATCTCGTGGTAGGG
          ATTTAACCCAGCATTAGGCAAGCCTTTATCATGACGAGCCTGGCATATCGTGTAGCAGAC
          TATGGGCCTGGCGCGGGTAGAGCGTATATTATTGCCCACCCGCTAACCCATGCAATCGTT
          AATGGGCATGGCACCCATGAAGTTTACATCATCCGACACTTGGCGATTCATGCGACAGTG
          TTGTCTCACGGGTCTTGAAAGCGGCATAGGGGTGGATTGTCACGGAGTAATGTGCCAAAC
          TCGAACCCCAGGAAACGATCGCGATATAGTCTCGCTTAGATGGCTTATAGTGCACCGCCC
          CAGGGCATGGAATTATGACCATGATATGGGCTGACCATCTTGAAATATAACGTATCACGT
          TGGGGGCCCAAGTCTTGATTATTACACGAGCGTATCATGTGGCAACGAAATGTATCAAAC

          GACCTGTATTGCCGATGTTCTATCGGCCAAAACTAACCCTACAGTAATCAAGGGCAGACC
          AACCAGCGGTGCCGCTACTTTTTTGATCATCATAATCTCCACTATCACCCAGGGCAGATC
          ATTCAACGTTACGCGTAATTTGTTGGCCACCATAACCCCTTCGGCAATTAGGAGCAGGTA
          ATCCTGCGTTGATGATAACCTGTTGCCCAATGCAATCTTAGCATCAATCTGGAGCAGGTG
          TATAGGACCCGCTCCCGCATCGCTGGTTAATGTTCTTCTAATGGCGATCGACGGTAGGTT
          TTTAAGGCCGACCATCGCACCGTCGGTTTGTGTAGTTTATAAAGAGATGGATTGTAGGTT
          ATTAAGAGCTATATCCGTGTCATTGCTAAACGCATTATGAAAAACAGTCGACAAAAGCCT
          ATCAAGAGTGGATTTTGTGTCAACGGGTAATACCACCTAAACTATAATCGACAAAAGCCC

          GCTTAACAGCCGATTGGCCGTCAAAACTCTCTTCTGACGTCCAGCAAGCTAGCTGAACAA
          GGTAGAAGATCGATTAGTAGTGGATACTCCCTTCTGATGTTTAGCAAATTGACAGAAAAA
          GAGTAGAGATGGATTAATTGTTGCAACTAGGACCCAATATCCGGTATGCTGGTAGGGTCA
          GGATAGAGTCACATTTGCTGACAAAATTTACCCCCGGCTCTCGGAATGCCACCAGAGTGG
          GCCGACAAAGCATATTGCTGTCGAAGTATCTGATAAATGCGTCCCTAGAGGTTAGCCATA
          CGTCATCAAACGTGTTTCAGCCGCAGGCACTTTTAGTCACGCAACCAGTGCCCAACACTG
          CTTGACAATTAGAACTGTCGTTTCACCCAGATATACTCATTTCATAGGCGGGCTGGATCT
          CGTTTTCAGAGGAATTGTAAGTGGAGTCACCACTACACATAGTATAGGTGTGTCAAATCA

          TCTAAAGAAACTATATGAGTGCTTTGTATCTGTTAGCTCAGCATATCGGAATCTTTGGCG
          TTCGAAGGGCCTATGTCAGCGCCTTACATCCGTGAGTTCGTTTTACTGGAGCCCTAAGTA
          TCTGAAGCAGCTCAGATCATGACTTATATGCGTCGATTCGTATTGATGTAGTGTCGTGCG
          TCGAAACCACTTAAGTTCGTGATCCACATTTGTTGAATCGTGTTGTTGTAGAATTCCGCG
          CTAGACATTGCCTTTCCGTTCCCGCACTAGCCCCCGCCAAGATTGATACGCTGCCTCGCA
          TCCGTCATTGTTATTCAGCTTGAGTATAAGTGCCGATCTAGGCCAACATTTTGCGTCTCG
          GTTGACACTGCCATTTTGAGTTCCCGCGCACTACATCTCATAACAGTACAGTGGGCTTAA
          ACTGCCGCTGCGATCAGAGGTCAACATATGTTACGCACCGGTAGTATACAGTGGCTCCCA

          GGAAACACGCCTTTTGGTCGCTTGTTAACTAACAACTGTATACATGTGAACTTTAACAAT
          AGGAACACGTCTTTAGGTCGCTTGTTCAATTCCGACTGTATACGTGTGAATTTTAACATT
          AAACACCCGTTTATGGGTTGTTGGACCCACCCTTTTCGGAGCCGCGTGCACTCCCTACTA
          GAATGTAGGCCCGTTAGTCAACTGACTCTAACATTCTGAAGCTTCGCAGGTTATCAAGCA
          GAATGCACCCTACCTGGTTACTCAGGGAAATGACCGTAGGGTCCTTCCTACCTTGATGCG
          GAACTCTTGCCACTTTGTTATCAAAAGTAATGCCCCGAGAGTCTTTCCATCTCTGTTACG
          AAAAATACACCGTTCCGTCATCTTAAGAAGTGCCTCGCCGGCCCAACCAATCTTGTGGGG
          AAACACATATCGTCCTATTACCTAAAGGAGTGTTCTAGGGGCTCAATAAATTTTGCTGGG

          CTTAACTGTGTAAGTGCCACAATTACAGGAGTTCACATAATGTCTCTCCTCAGACATATG
          TTTGACTGTAAAAGTCCCGCCACCGCAGGAAAATCCATAATGACCCTCTTGTAACATATG
          CCTATTTACGGAGATTTTGTAGGGGCAGGAGTTCCACTCAAGACTATGTCGAACGCTTTA
          CTCATTGGCGAAAGTCCCGCGGAGACTGGATTTGTCATTCCGCTTTGGTTGGTCGCTTCG
          TCACAGTACATGCCACGTGCAAGGAAAAACGCCGAGTTAATCCTCTCAGAGCCAGGCTTC
          TCTCCCAGTATGCAACGCGCAGATACATCCGTCGTCCTACTCAGGTCGTTGACTGGCCCG
          TTCATCCTTAAGCCATTTGTAAGGGTATAGATTCTGTCTTCCATCCCGGTGCTAAGTCCT
          TTCACCCCTGAGAAATCTGCAAAGGCATGAGACAAGCTCTCACTCTTGGTGTCCAGATTA

          TCAGGAACAGGAGCGGTGCCCGTGGATAACGCCGGCCCGTATGACCAATGTCGCAACTGA
          CCTGGAGGGGGAACGGTACCTGCGGGGAAAGCCGGACCGGGTGACCAAGGTAACACCTAA
          TTAGGAAAAAGCATGACGCTTGTGGGAGTAACGCGTTGTAATCCTCTGGATGCTATAAGA
          TTACGAAAAAGCCTGGCAGATCCAGGAGAAACGAATTTTGGTGCCCCGAGTGTCATCCGA
          TCTAACGTGGACGGCACACGAACCGAGGACACGCGCGCGCGCATTGACTGTATCCATGTG
          CCTGATGTTGTCTAAGCGCGCACGAAACTTACTCGCGCGTGGCTCGAAGACGCACACGAA
          TCTTAAGTGGGTGCTGCGTGGACAAAAGATACATGAGTCTGATCCGAAGGCGTCGACGTG
          TCAGGCGGGGGTGTCGTATGGTTCGACGATACAAGCGTGCGAATCAATGGTGCTGATCTG

          ACTAACACCTTGGAGGAGTCTATTTCTAAGAAATAGGAATGTAAGTTTCCGTGCAAAGGC
          CTTAAGCCCTTGACAGAGTTTATTGCCAGGAATTAAGTGTGTTAGCTTTTATGTTAGAAT
          TCTGACTTTTCGGAAGTGTATATCGTTTAGCACCCCGAATGCAATTCTGCGCGCTGGGAC
          CTTGATCTGTAGCAAGCATTCACCGTTTAATATCCAGAATGTGAATATCGACCTCCGGTC
          ACAAATACCCCGGATCACCGTAGAAGTAAAGGCCTTCGCCCCGTGGATTACTATGCAAAA
          TCCTACACTCTGGATCGATGTAAAGGCTAAGACCCGTACTCTTTGGCACGGGACGCAGAC
          CGGTACTCCCTGGCCAGTCACAGCGGCCTGACTTCATGATAAATGCCTCGTTATCGGAAC
          AGGGGTACTTTAGCCGGTCACAGTGGTCAAAGCTTCTGTCCCACACCACGATATGGGCGC

          CAACTAACTGGATAGTTCTAACAGGTCCCGTAGTACACAT
          GAACCGGCGGGATGGTCTTAATAAGTTGCACAGCACACGC
          AAACCCGCGCAAACCACCTAATAGACTTCGTCACATAAAC
          CAACGTCCACCAACGACCCGATAAACGGCGGAATGCACGT
          TATGTAGCGTACCAATCCACACGTACGATCCATGCTTGTC
          AACGCGGTGCCCTCACCCAGCCGTACACAGCATGACTGCT
          TATCGGGCGTACTGATCCACCCACTTCTGGCATGACGGCC
          TATTGGACGTACTAAGGCGTCTACTTTAGGCATGACCGTT

