 8 1000
t1        AAGGAGCGGGGGATTGTTACGTTCGGTCAGGGTAAGCTCCGTTGGGGACAAGGAACCTCG
t2        AAGAAGCGGGGGACTGTTACATTTGGCTAGGCTAAGTTCCGTAAGGGACAAGGGATATCG
t3        AAGGAACCGGAAGCAGTCACAAACGGACAACAGAAGTTGTCCTGGGGACAAGGGGTGCTG
t4        AAGATACTGGGGGCTGTCACATTCAGAAAGGGGAAGTTTTTCCTGTGACAAGGGATCTCG
t5        CCCCTATTGAGATCTCATTCACCAGATTTAGGAACAAAGACATCAGTGAAGATCATACTG
t6        ATCGTGTTGGAATCGTCTCGTATCGGTTGAGGAGACTGGCTCTGCGAATAAAGACTATTG
t7        CAATAACTAGGCTCCCCCTTAACGGAGAGCGGGGGTTTGCACTAAGGGGGAGAGGCGTCG
t8        TATAGACGGAGGATCCCTCATTCAGGTTGGTGGAGAAATGACAGAGCGAAACGCTTGTCG

          TTCGAGCAGCTGTGGACACAGCAACGTTTAAACAGGCTATATCCATACCGATTTATGGAA
          TTCGAGTCGTTGTAGATTCAGTGACGTTTAACAATGTTATATCTATACAGATCTATCGAA
          TTCAGACATCGTCAGGACCAACGCCTCCAAAATAAACTATATTCTTACGGTTCTGTGGGT
          TTCAAATAGTCGCAAGGATCACGGCCCTAACATAAACTACATCCGCACGACATTGTAGGT
          GACATTTCCTGGGACGGAGCGCTCCAACCATGAGCGTCACTTCTTCCTATCGATCCAGTT
          TAATCCCTAAGGGATGGGATGTGCTCTATCAATGAACTAGCTTTTCGTACCTCCGCGAGA
          CCGGCCTATGCGAAAGGAGGACGCGCACCCGAGGGAGAGAGTTCATGCGTATATTCGGCC
          TAGGATCAAGCTCACAAAGCATACCTTTTATGTGGATAGCGCCCGTAAATGAGTATAGAT

          TTGAGGACTAATCAAAAGAGTTTCCTTTCCCGAGAAGTACAAAGGTGGCACTGAAGTGTA
          TTGAAGATTAATCAATGGAATTTCCTTTTCCGAGAAGGAGAAGGGTGGTCCTGGAATGTA
          CAGCAGAATAACCGTAGAAGTCATCATATCTATGAACTTCCAAGGCGGCCCCGGGACCCT
          CTGAAGAACTACCAATGGAGCTATTGTAACCATGAATTTCTAAGGTGGACCTGGGTCCCC
          TAAGACCACTTTCCTCTGACCGCCTTCGCGCTCGCAGTCTGATGTTACGCGCCACGACTA
          CACGACCCTGACCTACTTCAGCACTCTGGTGTTCATGCCCGAGCAGAAGACCCACATACA
          TGCTACCGAAATGCTGCGACTCATTATGCAGTCAACGTGTAAAGGCAATTGCGAGCCCCT
          CTAGAGTGTGATTCATAGATTCCATTTATGGCCGCCGTGGGAGGTCCCGCGCAGAGTCCT

          TCGAAGGTTGTAGGTAGTCGTACCATATTAGCTACCGTCGAGAATGAAGTCGCCAGCAAG
          TCGAGGCTTGTAGGCATCCATGCCATACGAGCTACCGTCTAGAACGAGGTCGGCAGCTAG
          TCGACTTTAAAAGGTAAATGTACAATGTGAACTAAAACATAGAGTGCAGCCGATATCAGG
          CCTCCTGTAAAAGGCGACCGCGCTGTGTGAGCGATTACTAAGAGTGTATTCGACACCAGG
          CGCCATGGGATCTACAATGGCTATACGCTGCCAAACCGTTGGGGCGAAGTCTGTTGCTCC
          TATTCGGGACAGTAAGCCAAGGTATCGTACTGACGCACTCCGGATCCGGACGGTAGCTCA
          TGGATCAGGTAAGACGACGGCGCATTGTCGGCTGGTGCACAGGAAAGCCCCGTGTCCTGC
          CGGGCACGGTGGGTGGACGGTATACTGCCGGTCATGTTTTGGTGACGGAACAGCGATCCC

          GCCCAAACGTTATGTCAAGATGGTTTATGGGGCGATAATACGCGTATCTGTCGCCATTGC
          GCGCCAAGGCTATCCCGAGACGGTCTGTCGGGCGACTTCATATGGATCTTTCGTCGGTCG
          GCGTAGCGGCCACCCCAGAACGGTTCATATGACTACTATCCGTAGATTCATAGATTGTTA
          ACGCAGGCGTCACCCCAAAACGGTATATATGACAGTTATACGCAGATCCTCCAGTAGTCA
          GTGTATGGAGACCACAGTGGAGTATCCGCCAGCCACTGAGAGTCGATATCCCAAGACTTA
          GTGGAGGGGGTATAGTGGGACAGACCCAGTATTTATTCTCCATGAATATCCACAGACACA
          GGGAAGACGTCCTACCCGGGTGTGGCCGTCAGTTTTAATCGGCGACTACTATATATTGAC
          GTAAGATGGCCTTCCTTGATTAGTCCCACTTACTATCCGGTGAGAGCTACTCCGAGGGTA

          GTACACAAGATCCTCAGGATTCCTTTCGCTTGGCCTTGCGTCTAGCACTGGTTGGCACTC
          GTACACTTGTTCCTCTAGACTCCTTCCTCCTTAGCTCACGTCTAACGTTGGTCGGCACAG
          TGAAATTAACTCCATAAAACCCCGTGCTCCTCATAGTATGCCCAGTGTCTGTTAACAAAG
          TTACATTCACTCTCCACAACCCCGTGCACCTCATTGCATGTCCAGAGTTAGTCGACAAAC
          GTCCATGCATGTTCGTCGACACCATGCTGATCCGATGCAGCCTGGGTTCGCAACCCAGAA
          CTTTCCAGATTTTATTTGTGATCATGTTGATAGGGTATTGAATGAGATCACGTGTTGAAC
          ATGTAACGTTCCACCTTGGAATTGCATGGATCAGACATGGTAATTAATCCATTGCCTAGC
          AAGTGTTTTCGCGCCGAGACTTTATACTGTCTGGGACCGGTCAGTACTCGTTCGCCGACG

          ACGGGGGACGTGAAACTCTGATAGGTCGAAGCACACAGCCTCACTGGGCTCTTGAACCTG
          ACGGGGCATGTCAGCGTCCGATAAGCCGAAGCATACAGACCAACTGAGCTCTTGAACCCC
          ACGGGGAACATGATCACCCAGGGGGCAACAGTTCAAAACTAAGACGCGCTCCCGGACCGT
          ATGTAGGATATGAGGTTCCGGGGAGCCACGATTCACAACCAAAACAGGTTCTCAGACCGA
          GTACACCTCGCAAGTCAACGGTAAATCGTGAAATATAGTGAGGATTGGCGCTCGGATGTC
          CACCGCCAGGGTGAGGGCCAAATGATTATAAAAATTAAGCTAGCCCTGCGCTCAAGAAGG
          ATTTGAATTGAGTGTGATAGGTCGAGCGTCGGAAATTATATAGTAACAATTCAATATTAG
          GTACACCTAACAAGTCCCGGATTGACTTACGAGCAGGTTCTTGATTGATCCTATGACCTA

          GTGCAATCTGATGGGTGCTTAACGAGTCGCCAGGTTGGTCAGAGAGTTTAGACCTTTTAG
          GTGCAAGTTGATAGGCGCCTAACGAATTCCCAGGGGGGTAAGGGAGTTTTGACCTACTTG
          GGGACATTCGATCGTTACACACTGGACAACCAGGCAGGTGAGTGAGTTTATGCTTTTACG
          GAGAAGCCGGATGGGCACACACGGAAGAACTAGGCAGACTAGTGAATTTACACACGCACG
          GGTCGCAATGACAACAAAACTGTTCGAATTAGTTCGGGTGTAGTGGCGCTCACCCTCCCG
          GAGTACTTTGCTAGGATTTTGGCAAGCCGTAGCACTAGTGTGGAAGCGTACAAAAACTTG
          AAACAAGACCAGCGCAACATGCCCAGGACCGGAGCAAGCTTGAGAGCGAACTAAACCATT
          CAACGGCTTGGTAACCACGTCGTGAGTCTTGCGTTGGGTTTGAGGACATTCAGTACCTTG

          GGGAGATTAAGTCAACTGATCGTTTCCCTCGACATCGATGCGGACAGCAAATGTTGTTCT
          GGCGAATCGTGATAACTGATTGTTTATCCCGACATCGACGCGTATAGTAAACGCTGTTGC
          GGATCATTGAAGCACAGGATCGTTTGATTTAGTGACGAAGAGTTCAGCAAATGCCGCAGG
          GGATGGCTGTGGCCCACGATCATTAAATTCACTGTTGGTAAGTTCAGCAAGTGCCATGGC
          GGAGTAAAAGGGTGGCTCACTAGCAGGTCCTCTGGCCAAAGAGCGGCCAAACTTTCTCGT
          GGAAAAAAGAATTGGCTCGGAGATGAGTTCCGTGGAAGACGGTCGGGCGATCCACCCCAA
          AGAGAAAAAAGATCTCGGTACGATGCACGCAATGAAGAGTAGGGGAACTGTCGCCGTCTT
          GACCAAAAAAAAAGCGTTAGAAATGCAGTTTTAGGAGATATGTTATGTGGTCATTGCTGA

          CGACTCATATTTAATACTTGCAATAGTCTATAGTAGTTTTATACAAGTTGCCTACCTGAG
          CTCTTTCTATTTGGTGCTTGCAATAATCTGTAATCGCTGGACACGAGTTGCCTACTTAAA
          CCATTTGCAGTAAATGCTCGCGACGTTCGGTATGGATATGGTACTAGAAGTTTCCCAATA
          CTATTTGTATGAAGTGCATGCAACGTTCCATATTATTTCGACGCAAGTAGTTTGTTTCAT
          CTTTTCTTCATTGAGACTGCCTGGGTGGCGCGTTGACCATGGGGAGACCATGTTCCGTCC
          CTTTTTAATGCCAATGTCGGTTAGTTCAGCTAATACACATCTAGAAACCTCATTCAGATA
          ATCCTCGTCTAATACTTCGTTTGAAAAACGCTCTGTGTCACGATAAAGTACGCCAAATCG
          CTTAGTGATTTGGCCCTTGGCAGGGGTCCATACTAGATCACGGTAAGTAGAAAAGAAATG

          AGTGCTTAAAGGAATACCAAGTACATTGACTTCGTAAGATTACAATCTCATCCAGGAATC
          AGTGCTCAGTGGAGTATCAAGTGCACTGGCGTCGAAAGATTACCATCTTAACTAAGAATC
          ATTGCCTAGTGGAGAACCCTGTTTGTCGGCTACGCAATGTCACAGTTTGGCCCTGAAACC
          TATGCTTAGTGCAGTATCAAGCTTACCGGTCACGCACCGTTGAAGTCTAACCCAGAAACC
          TTTATTTCATCAAGTTTATAAATACTCCAGACCGCCGAATGCTGACACAGTCCAAGGACT
          AGCTCGCCGTTAGGTCTATAAATCCTGCACATTGTCGAGTCCCAAGCCCATCACGCGGCT
          TCTATTGCGAGGCATGTTCCCCACATACATAATGCTTAAAATTCGCCCCTTCCGGGAACT
          CTAACCTGACCGCGCGCAACCACGGTATATTTCAGCCGGAATTTCAACAGTCGAGCACTC

          GATGACGTCCGTTTTCTTATTACCTGACTATAGAGCAGGTCATAATGCTGCGTCCAGATC
          GATGTCGCCCAATTCCTTGTCGCCAGGCCATAAGGCAGTTTATTTTGCTGTCTCTAGATC
          TCTTCCGACAACTGGTCCGCCGACTAACGACCAGGTCGTTCAGCGTGCTGTGCCTAAAGC
          TCTCTCGCCTCTCAGCCCGCCGACTACTTACCAGGTAACTCAGTGTGACGCGTCCGGATC
          CACCACGCCTAGCAGCCTATTGATTAATGCGTGTGGTGACTGCGGATACCAATTGTAGCA
          CTCTTAACGTACCATTGCCTGAATCGAATCGTAAGTCTCTTGCAGGCGTCGACTGCCGGA
          CCTTGAGGTCGTTAGAGGGCCAACCCACCTACTAACGGTTGTTGGGGTCGCCGCATTGCT
          ATCCATAGTCGCGAGCCGGCCATTTTCAATACAGGTTACGAAACACGAACTGGCGTTGCA

          GATATTCCCTGCCAACGGTTCCTGTCTAACAGGTCGTATGATTCTTGAAAATGTCCGTAT
          GATATCGCCTGAAAGTGTTTCCGGACTTTCACGTCGTATTATTCTTGAAAACGTTCGTAT
          GAGATCATCCATACGTGGTACGGAGTAAGCAGGTTGTAATGCATTTGATGGCGTCCATAC
          GCTATCACATGAACGCGGTACTGCGCAAACAGGCTGTGTCATGTCTGGAGACACCCGCAT
          AAAAACCACGAGATCCAATACGGGGCGACTTCCCTGGATGTCATGTAAGAAAGGAACCGC
          AACTTTCAAAAATTGAGGTCCAGAGGCATCTTCAGTGGCCTCCTGGGAGGACAGTAGTTC
          GCAGCGATTCGCTAACAATTTGGTGCAACCTAGAGTAACATCCATTAGGGGTACCCTTAA
          ATTGCCTTCGGTGTGTGTCCCGGAACCCTTCGGTGGACGTTTCTGCATCGGTGAGCACCG

          TCTTTATTACAGAAGTACGGCAGATGTCATGGTGGCTATATACGAGCAAATACGAATTCT
          TATTTACTACAGACGTACGGCAGATATGATGGGTGCTCTCTACGAGCAAATACGATTTTT
          TCTTTATCAATGCATTTTGGTAATTTTCCCGCTAGCTAATAACGAGGGGTTATGACCTCC
          TCCTTAACAAAGATGTTTGGTGCTTCTCCCGCTGCCTAACAATCACAGAATATGATAGCC
          CCCCTTGTGTTGGTATCAGTCGGCTCTCTTCTCAAGAAAAGTCGCAAACCCACGGTCCTT
          AGTCAATTGTTGGAATTCACCCGGTTCCTAGATATCCAGGAACGCAAGGACTTGGCAGCT
          TTCCGATAGGGGTCTTCCAGTGGTACGTGCGTCAGTAATGACAGAAAAACCAGTACCGCT
          ATTCAATAAGAGTTATAAGGTGATTTTCACATCGACAAAATATACACATTAATGTTTTTT

          TAGGCATAAGTCAGTCATACATGATGCTACCGGAGGACAGACGGCAGCCGCACCTGGCTC
          CAAGCACAAACCAGCCATACATGACGCTGCCGGAGAACTTATGACAGCCGCAACTGGCCC
          CAAGTATACACTAGCCATAGAAGACGCTACGGGTTGATCGAAGACGGTCGCGGCCGACCG
          CAAGTCTAAACTAGCTATAAAAGACGCCACTGGACGACCGAGGACGGCCTCGGCCGGTTA
          TGGCTTGACGTTAGATGTCAAAGCCGCGAAGATACTGCTCCAGATAGCTGCACTAAACCG
          CCGGTCCACGCAGGACATCTAGGCCGAGACAATAGCCCCGTCCGCGGGAGTACTGAGTTC
          CAACCATGGGTTACTAGGTCTGGACACAGTAATTCCACAGGCTGCCCTTATTACCCGGTC
          CAGGTTCAGGTGAGACTCGTACGTTGTGCCGAAGCTTCGAATAACCGCATTCCCGAGCTC

          TTAATCAAGTGCTCGAGCGGCTGGGATAGTATGACTCCCTTCATTTTGTGTGCCGTTTCT
          TTAACCGAGTGCTCGAGTGACCGGAGCAGTCTGAGTCCCCACGTCTCGCGTGTCGTTCCC
          TTGAACGAGATCTCCAATGGCCGGTGCAATCAGATGTCCTTCTTCTGGCGTGCCGTTACT
          TCGATCGAGGTTCCTAACGGCCGAAGCAGTCTGGATTCATTCTCCTGGCGTGCCGCTACG
          TTAGGTACAGTGGTGGCCGTGCTAGACTCTGCGGGTTTCCTCTCTAGGTTAGTCCTGATC
          TGAAGATTGACCGCAAGTATCACATATCCTCATAAACTTTCAACCCGGCTCGCTATATTT
          TGTGGCCACATCATCCAGGTCCACTTGTATTCGAACTCGGCTCTTTGGATCTCACCTCTG
          TGACACCCCTCCGTGAGTACCGAAGGACAATTGGTCCTGGAATCTAGGACAGCACGGCTG

          GCTTGAGGAAGAAGCGTACTGAGGCGGGTCCAGTAATATT
          GAATGCGGCAGAGGCGTCGTGCGGGGGGTCAAGTAGTCCT
          GCTTATGGAGAAAGTGGCGTTTTGCGGTGCAGATAATCCT
          GCTAATGGAGCAGGAGGCATATTGCGAACTCAATACTCCT
          GCATCCAACAGAAAAATAGCATTACAGCGCCTGAAACCTT
          AGGAATGGTCTGAGCGGTAAACGGGACAGCTGTCGAACAC
          GCGAACCGTATAGACACCCTGCACGGGGATTGTTCAGTCA
          GAAGGCAACACTGAGGTCACGATCCGGATACGACAACTAC

