 8 1000
t1        ACTTACTCTAAGGTTAGTGGGGTGAGAGTTGCAGACACTCGACGCCACACGATGCCCCAA
t2        GTTAATTGTGGAGTTAGTGGAGTGAGAGTTGCAAATAGCCGGCGCTGTGCACCCACCGTC
t3        ACCAAATCATAAGTTGATGCAGCCATAGTGCGATTACATTATAAATGCTCACTGGGTCGG
t4        TTATTCTCACGCGTAAATATAATTTTTAGTGGACGTCATTATCTATGAGCGCTGGCTTGT
t5        ATACACCCGCGCACTAGCGCGGTCAAATTGGTAGGTTTCCATAGATATGTGTTCAGTCGA
t6        CTACAGTCCCGCACTTGCGGAGTCGAATCGGGAGGTTTCCACAGGTATGTGCTAAGCCGT
t7        GACCTCCCTAGCACGATCCTGATTACCCTTCAACATCCTCCTGGAGGAGCGATGCTACGT
t8        ATCTTCCTGTACGCGCATGGAATTAGTGTTTAAAATGCCTGCCGCACTGCACAGACTCGC

          GCCTTCCTGTTCAGCTTCGGAGAAATAGAAACCATCCTATTAATACAGTACTCCCATAAG
          GCATCCCCGTTCCGTTCTCCGGAAATTGATACTAACTAACTGACAAAACGACCCAATGAG
          TCATGCATAAAAAAAGGTCATACATTTGGTAACTAATTAGAGCCTATCTTTCCGGATGTC
          GTATGCGTATCTGGGGTACACAGCTACGGACGCTGAGTGCAGCCACAGTTTTTGTAGGCT
          TCATGTATTTGGACAACCGTTGTTTGTAACTATCAGCCATTCGCCTTGTGCCCCCCTGTG
          AACTGTATTTGTAAACCACCTGCACGAAACTTGCGGCTATTACACCTGTGTCCGCATGTG
          GTTTACTTACAAAGAGCTAGACCGGGAAGGGGCGCCCGAACGGTAACAACCCAGTGTGCG
          GCCAGTTATGTAAATATTCGCCGATAAAGCGGTTGAGTGTTGGGGTCGTCCCTGTTTGTG

          ACGAGGTCTATATAGACCCCTCGAGATCCCATCATCACGACGGATCTGCAACTAAACTAA
          CTGACAACCATAAAGATGCATTGGGATCCCATCCTTATAATGGAGCTGGGTCTAATTTAC
          ACAGGCCGGCTGCTCAATATGCAAAAACGAGGCGTTTCGGGGCATTTGCATCTTCCTTCC
          CCGGTGGAGCTGCGGAATAATTTTGGTTTCTATGGGATGATGATGTTGCGATTACACGCC
          ACGAGGTGTAAGTAGATTATCCCCGAAAACCATATGGGGTAGTCGTTGTAATAGGGCCAC
          ACAGGTCGCTCTTAGCTTATCTTTGATACTTGTTAAGGGTGGACGTTGCAATAGGCCCAT
          GCGAGATATTTTCACACCGCTAGGGGACTCGAGCAGAGGCAGAGGTCACAGGGTTACGAT
          GCGAGTTAGGCTTTTCTTATTTGAGAACCGGTCCCAATTCACCACAAATGGAGCTTTTCG

          GTACAATAGATGGTCGTGCCTAAAACAAGCTGGAAGATATTGTCCATATGTATTAATCCC
          GCACCATATGTGGTCGAGTCCTGACCAAGCTAGCGGATATTACCCGCTAACGTCATCCCC
          GTAAGATAGATAACCGAATGTATCTCCGCTCGACACCAGCTCGGACTCCACGCCCACTTA
          GCGCAGTCCACGACTAATTATAGCCAGGGTAATAACTATCTCGGTTCACAGATCGTTCGT
          ATGTTCAGGCTCGTGGGTTCCCCACCTGATTCGAAAGCGTTACAAGTGAAAGCCCCCCGA
          GCGCCATGGTTTCTGGGGATCTCACATGATCCTAAATTGTTTCACATGCGAACCCCTCCC
          CTCCAGTGTACTACCCTGGACCACTTTATCTCGATGACTGTTAACCCGCGTGTCTTCGTT
          GTAAAATAGGTTTGCCAGCCTATGGCTGTCTAGCAGGCGGTTAATATATAAGTACTCTAT

          TATAGTCTAGCCTCCGGCGGAGTCCTTGGCGCATACCGGTCGTTGTCTAACTGCGCGATT
          TATATTGCCGTCCCCGGTGAAGCGCTTGGCCCAAACCAATTATTATCCAACGACGGCATT
          TAGAGACCCGGTCCAGTTAACACCAGAGGCTTAACACGATAGGACCTTAAGGATGCCGGA
          TAGGGATCAAGTATGGGCATGCCGCGAAGACTTAACCGCTACACTCTTCAGGACGCCAGT
          TTTATTTCAACAGAGGTCGCGGAACAAGGGGGAACCCCAGTAATGCCGGTCAATGTGTTG
          AGCGTTTTACCAACCATCGTAGAGTGGGAGGGGACATAGGTGGTGCTAGCCGGGCTGGTG
          CAGACGTTTACCCTCGGTAGAGTTGAAAAGCCAGATGTATAGCCGCAGGGATATACCACC
          CGAATGTATGTATTTGGGGGAGCACCAATGAGTGCACTGTGATTGGCCGGCAAAGGTACG

          GAGGCAATTCCTAGTGGGTTCACGTTGGTGGGGTACTAACTTCCGAAGAAGATATCGGCA
          GGGCCAATCCCGGACGGGTTTTTATTGGCGATGTGATAACTTTTGCAGAAGCTATCGTCT
          CTAAATTCTGTCAATAAACTCAATTCGGTCATTCTCCTACTTTACAAACAGACACTCCCT
          TCGGAGCTTATCTGCAGATGAATATTATCACCGCTGAGTTGCCCAGGATAGACTGCTATG
          AGCGCTCTGACCTAACGGAGGAAGGTAAATGCAGGGTTCTCCCCGAGTACGATTCTGTGT
          AGACAGCCGGCCTAATGGCGAATGGCATACGCTGCGCACCCCCTGAAGCAGGTGCTGTAT
          GCGACATTGGCCTGTACCCTCAAGCTAGTGGTGTAACGTATATCATGGCGCAAATTGTTA
          GCGGAAATAGCTTATAGGCATATGACATCGGCGAGGCGCCTTCTGAGGGTAGAGACACCC

          AGGCGACCCTCAGTTCGGCTCTCTACAGACATCGCGACCCCTTTAGCACCAAGCGGGCCT
          GGGTCTCCTCCAGCGTGGTTCGATCAATGCTTTCTTATCCTCTCAGTATCAGATGGGCTT
          ACAAACACTCTGGGAAGTAGTGTTATGGGGGTTCAAATCCGTTTGGTACGGGCAGTAAAC
          AATAAAAGCCCAAGTGGCTGGACTGCGGGGACCCTGGCCTGTATAGGTCCAAGGAAGCTG
          ATCGAAGAGTTAGGTTGAGAAGGCGTAGCTATCTCTGGTACTCTAAAGCCAATAGCGGCG
          AGCGTCACGTCTGGCGGCCGGAACGCAAGCATCTCGAATCTTTTAGAACCAACGGCAACT
          CGAGCGGCTAAGGCTAGCCACGTTTCAGACAGAGCGTTGACCTTTAGACGAGTTTCAATA
          TGCATCAAACTGGACGGATAAGCTCTAGGTGGCCTGAAAACCTTATTACCGGCAGGGCAA

          CGGATGACTCGTGACAGCATTTGCCTGTAGGGGCACGCACCGTGTTACATTCGGCCGGGT
          TGTTTCACACATGGCAAGACTCGTTTGGAGGGGCCAACGCCACCCCGAATCTTAACGAAC
          TGAAACACATGAAGGGCACGATTCCATATACCGTGATAGCCAGAAGACACGTTGTACCAG
          CTTAATGTTCGGAGGATGACGGATTTTTTGTCACGGGGGACTCAACATTCGTGTCAGGCG
          CATATGCGTCGACGAATGGTAGGTCCCCCGTCGGGACAGTGAGCAGGAATCAGTTTTTCG
          CAAATTAGTAAAGGGGTGACAGGTTCCAAACCAGGGCAGACTGTAGAAGCGAATCCTTCG
          AGCACGTCTGGACGGAGGGAGCACATCCTCTTGGCAAAAACGCCGAGCGGAGAGCGGTAA
          AAGTGAACTCTGAAGGGGACCTGAATGCCCTTGAGCGAGGACATAAATAGGAAGTTGTGC

          GACATGCCTTAAGCTACTCTGATACCTTTGCAACTGCAATCTAGGCTAAGAATCGGTAGA
          GACGCGCCCCGAGCTACTCCAATACCTCAACAGCTGCAATCTAGATCGAGGATCGGTAGA
          TGCGTATGTCTGCGTGGGACGTGTATAGGCAGCGAGAGGGCTTGATCGAGGACGGGTGGA
          CACGCGTAAGGGTTGCCTAAAGGACGGAGCCGATAGAAAGCCTGATTGGAGCCCGGTGTA
          CATAGAAGCTGGCTGTACAAGAGTTAGACACAGCCGAAGGCAGAAGCGCAACCTCGGGAC
          CGCAAGCTTCGGCTATGTAGGAGCTTAGCTCAGCCGAAGGTGGGAGTAATACCCCGGGGT
          GCCGAGTGACGACACTCTTAGGTCCAGACGTAGGTGTAGACCTACGTAAGCACAGAGTGG
          TGACTTTGTCAATTCCATCTAGACTTATAACGGAGATCGCTAGGAATGGGGATCAAGGAA

          GTGCTACAGGGCCACGATACGCTTAACAGCAGTATCTTCCTTTGCATTCCGCGTGCAGTG
          ATGATATAGTGCTACGCTGTCCTAAAAAGCAGTGTGCCTCCTCGCAAATTAGGCACAGGA
          GAATTCGGATATAGGGTACCTTCTGGATATATCATACATCTCTACTGCCTGCCGGTCCGG
          AAACTTGTGTTCAGTGTTCCTCCAAGACAGCCAGAAGATCTCTTTCAACCCACCACCGGA
          GCATCGTTACGTCGGGTACTGTTCAGAACTATTCCGGACCCATGAAGCCGCAGTCAGATG
          GCGTCGTTACGTGGGGTGCTGTTTTGTACTATTTCGCCTCCATGAAACCGGAGTTACATG
          CCTCGTTTGCGCAAGAGAAAGCTTCGCAGCCAACACGGCTCTCGCAGATTGAGTACCGTC
          TAGAAAACAGTTGAAGTGACCCTATACCAGTCTCTGCATTCCTCTAAGTTGAGCTTAAGT

          CTCGTTTAATGGAATTATGAACCGTTGACAGAGAACGCCTCGTCTGGGGGAAGACTCAAT
          CAGACTTACTAAAATTGGAGACTGTAGCTATGGAGGGGTTCCACTGATACAAAAGTTCGT
          GAGGCTGGCTGCCATTGGGGTTCGTCCTTGGAAAATGGTCGAAGGTTCAGGTAGGGCTAT
          AGGCCTATACGTAATTACGGTTCGTACTTAACGAGTAACTGATAATACACGTGAACTCCC
          GAGCCCCAGGGTTACTGTAGGTTGTGGCTGGGGGCACAGTAACGAACTAAAGCAACTCGT
          GAACCTTTAGAGTAATGTAAGTTATACATGAGAGCCTAGTAAGGTATCAGGGCAACTTGC
          GTGCAGTCCCTTCGCAGGGGTTTGGTGCCAGAGGGCAGGTGGGGTGACTACGGGGGCATC
          AGGCCACTTTCTTAGGGCAGTTCGTGGATAGAGGATCAACGCGACAACATGGAGATATGT

          CTAGAACCAATGCGGTTTACGGTACCCACTAGTTGGATCAGTCAGCTGACTATAGGACTA
          CTTTTACTGAAGTTGTCTATGGTACCTGCCAGTTATATCAGTCGAACGATCATAGCTACA
          ACTAGATGGAGATTCAGACGGACATTCACTGAGCGGGACCATTGGTCTGCTTTGGCGACA
          ATCAAACAATGGCCCTACTGGACTCCCGCCTATAGCAGTTGCCAGTGCTACTCATTCACA
          GGAGGATAAATACTACACGCTACCTCCGCGAACGGCGACTCCTGCTCGGCCCACACGGGG
          AATGGTTAGACACTACAATGTACCACCGCTAACGCCAGTCCCTGATAGGATAGAACCCAG
          ACGCATTCACCACACTGGGGACAACTTATTAACGAACCCTGAGAGTCGAGACCAGTTGAT
          AAGTGGATCTTGTCATGCACGCTCCGGGTTAGGGGGAGCTGCGAGATGAACCAATTCACC

          CAGATGTAATAAAAGCCAGAAAAGCCCCTTTAAACGCTCCGTACAGCGACTGGATCTATT
          GGGATGTAATATGAGCCTGGGAGGTTCATATAAGTGTTCCGGAGACCGACCCGTTTTAGC
          GCACAGCACAAAGTTTCCGCACGAAGCTAACGAAATGTGTGCCATAAGTTCTGAGCTCAT
          ATCAAAGAGGGACTTTTCGGGGCTTTTTCGCGTATTTGCCGTTATGGAACCATGATCCGC
          TACAAAGGGGGTTTATACCTGTGCGGCTGATGTATTTTATGTTCGAATTCTTCCACGGAT
          GACACGAAAAGATCCCTACAGTGCACGTGATGTATCCTGTGGTTGTATTCTGCTCGGACT
          GAAACGGAAAGACCTAGAAGTGGCGACCGCTGTCCTACACGTAATTGAGACGGGGTCAGC
          GAGACGACGTGATCTGAGTTATGGGACAATCGCGGATCAGGAAGTTCTTGCGGTGCCAGC

          CTATTATTCCGGGTTTGCCGAAGGAGCCTATATCGTCAGAAACTCATATTGACTTGCTAT
          CAAATAACCCGGGTCTACCGTAACGGCGCACACTGCACGTATCTCCGGTTTACTTGTCAC
          GCGTTTATTTGGGTGCCCTGTCCGGCAGTATGTTGTACTGATTAGAAGTGCGTAAAACGT
          TAGCTCAACAGGCTATACCATTGATCCCCGCCCTGCGCCTGTTACGAACTTTCGCGTCAC
          CGTCTTTGCTGAGGCGAGTGCTTCTCATCACGACATACACAAATGGAGTAAACCAGTGTT
          TGTCTCTTACGGGTTGGGCGTGATTTCTCACGGTACGCACAAGTAAAGTGAGTCCGCAAC
          CCGTTCGATTCCGCTCGACGTGAGTTGGGGTAGTATACCCAGACCGCTGCCGCTGGCGTC
          CCGCTCAGCCGAGTTTGCGGCATGCAGGTGGATCGTACTTAATAGAAATCCATGTGGCCG

          TCTACTGTGACCGCTCTCGCACCTAGATCCTTCGACAATAGTGTACGGGAGTACCCAGAA
          TCTAGCGTGACTGGTTTTTCATTTGGATTCATCGACACCATTTGGTGTGTGCACCACGGT
          TCCGCTGCATATACGTAGCCAAGATCTTTCACCGAGAACGCGGGGTTCTAAAATTAACTA
          TAAGTGGCCTATACACTTACAAGCCGATCTTACGGCGGCAGTGCGCCCTAGGACGTCAGG
          AGCTACATGGTTGCCGTCCGTCGTCCAAGTACCACCAAACGCGCGACTGATAAATCAGGA
          AACTACATGGATGCCCTCCACCGCCTATCAGCCATCAAGTTCGCGATCGAAAAATCAGGA
          CGGCGTCGAGGGGAAGAAACACTTGTGTTCCCATTATACCGTGTGCTCGGGCCGTCACTA
          CACCGCCTGTACGGCGCCCTATATGGGTCTTGCAGCGACAATGACCATTAGGTGTCTCCA

          TTGAAAGTCTGTCTTCTGAGAGTGCACTACCGTTTGCGGCCATCGGGAAACATCGGCAAG
          TTGGAGGTCTATCGGAGTGTAGCATATGTTCGCTCGCGGCAACGGGCAGGCTTCAGCCAG
          CCGAGGCATTGACGAAATTCAGTCCGTAATCCGTCAAGATTTCCGGTACGATCAGGTATA
          CTGAAGCTCGATTAACTACTTAGCCTTCGTCACTAGATGTTACCAATGACTCCGCCCTCA
          TCGTAAGCTTTACTGCCCCGTGGGCATGCGCTCAAGAAAGTTTTCAGGGAAGCTCGCCGA
          CTGTAAGATCCACAGCTCTAGACCTAACCATACAAGAAATCATTCAGTGAAGTTTATCGA
          GGAGAAGCGCTGTATTGTTTCGCTGACCCGCTTACCCATCCCTTTGCGCGGATGTAAATA
          GCGGGCCATGGGTGCAACAGCGTACATTAACTACATGTCGTTGTAGTGAACATAGACATT

          CCGTTGGATCAAGTGACATAACCAATGCTATCTTTGATTA
          TTGATGTATTCAGTAATTTGCCTAATGCTATACTTGACTA
          TCTCCGTAATTGAATCTAAAGCGCACCTAGTCTTTGACTA
          TCCTTGTATCTTTAAGAGGGACCTTAATAGTGCGTAATCA
          CCCTTGAGCCGCTGAAATAATCCTTTGAAACTGCGGCACA
          TCGTTACGTTGGTACACAGCTCCACCGAGGCCACAAGACT
          TCGCTACACTTACTGGTGCCGCATTTGAGGCACGTGCCTT
          TTTGTAGGTTCGTACACGATTCATCCGGACTGCCCGACTC

