 8 1000
t1        CTTACGAACAAAGATATGTGTCAGAGCATTGTGCGACTCTCGCTTTCGCGAAGGTTTGCG
t2        CTTACGACCAAAGAAATGTGTGAGAGTATTGTGTAACTCTTACTTTCGCGAACGTTTGCG
t3        CCTCTACCTAAAGCCCCTTAAAACATTAGCACGATATGACCGAATGAGAAAATGCATGCG
t4        ATCTCCAAGATCGTTATTCGCAATATTGGAACGAATAAGTCGCACTGACTGTTGCCTGGT
t5        TCGTGGTGAAGTTATGCGTATCACGCTCTCCGAGAATCCTCGACGTAGCAGGCCCCTGCT
t6        TTCGTGTTGGACGTTGACACTCGAGCATGACGGAGGTACATGATTCGTTAGACTCCGCAA
t7        ACCTGTGAGACCGACCGTTGCCCTGTACAGGGTATCTACTTGAATTAGAAGCCTCCTGAC
t8        GCCGACCCAACGACCAGTTGCAGCGACATCTGGAAGTGCTATGTCCTTTGGAGCCCGAAT

          CCCGTTACTCAAGTTTCGTTGAAACCTTATGACGGGGGAGTATATAAATAAAACGAGTAT
          CCCGTTGCACGAGATTCGTTGAAACCTTATGAAGGGGGAGTATATAATTAAAACGTGTAT
          TGCGTCAGGGCATTCACCTAGAGTATTCAAGCAGATGGGCTTTTTATCCGACAGGCGTGT
          TGATATAGGTGTACTAATTATAGCTTTTAGACAGCAAGGTACTACAATAAGAAAACGTGT
          CCAGACGCGGAGGTAAATCCTTAATTCCTCCTACCCGCGGACCGCCACCAGCAGGTACGA
          TTCGGTGGTTTAATAATTCAAGGATTGTTTGTAACTTGAGGTTATGGCTAACGTATGTTC
          ACGATCGGATGGGCCAGCTCGGATTTTCGCAGGACCGGGTGGTTTCAACAGGTAACACGT
          CTCCTCTTGAGGACTAGCCATGACTTTGATTCAACCAGTTGCCGTAGGTAAACGGTGGAC

          CTACTGGATACACGCACAGTGTCAAATCCGACAAATGTGACGACACTCGGGCGGTTCGTC
          CTACTGGATACATGTATAGTGTCAAATCCTACAAATGTGGCGACGCTCGCGTGGTTCGTA
          TTATGACATGTAGACAAGGTGCCATACTTGACAAACAGCGAACTCCCAGAATGGATAGCG
          CGTACAGATGAGTATATGGTAGTAGATTGGACCAGTGATACGAACGCGGAACCGGTGCCG
          CACCAATACATGTGCATAACGAAATGTCAGAAAAATAAATAGATCGTGGCTTGACTACCG
          TAGCGCCATCTACGAGTGATGGCGTGTCAGCGAGCGCAGCCAAGTGCTGTTGGGCCACTG
          GGCGAAAACGGAAACATTGGGAAGTGTTATAAACCACCACGATTTAACAAATATAGACCG
          CCGCGAATGGATTTCTCGGGGGTATCGGGGGTTAAATCCTTCTTATTGCAGTTGACACTA

          ACCTGCAGGCTGCATGCGATACTGGTTATTTCCCTACCTTATAGCCTTTAGGATTCGATC
          ATTTGCAGGCTGTACGCGATATGGGTTATTTCCCTACCTAATAGGCTTTAGGATTTGATG
          TCCCCCGTGATGCCCATGTAGAAATTCGCACATCTATTTACTTGTCACCTCCAATTTAGG
          GTCCGCAGCGTATCGGTGGTGCCACAGGAGCCTTTCGCTACACAGTTTCACCCAGCCGGG
          TTGTATAACTCAACAAAACCATTCGAGCAGCTCCAGCCCACACGCACCCCGATAGTTGCG
          AAGAATAGACTGTTCGCGCCGCAAGAATTGTCAATGCCTACCCCTGTCCATACGGCCGCG
          ACAAGATGACGGACGTCCTCGTAGTGGCGGCTACCATCCTGCTGAGGACACACGATTTCC
          CTGTGTCGGATGCTAGCAAGGTGCAGGTGGGCTCTATTTACGTACGGTTAGCCGGCAATG

          TCGACGATCTGAGCTTAACGGCAGGCGCAATCACGAAAATAAACTGTCTACCATATGAGC
          TCTACGATCTGTGCTTAACGGTAGGCGCAATCACGAAAATAAACCGTTTACCTTATGAGT
          CACCCGGTCCACAAGCAATGACAGACGGCCCCACGGATGCGTACCAATTGCCATATGGGA
          GAATTTTACAGGGTGACTATATTAGTACAACCGCCTAAATTCCCTACTAGTCCTCCGAGT
          TGTTAGGAAAGGACCCAACAAAACTTAAGACTGCGCTGATTCGCACTTCGGCGCTCGGCC
          AACTTGCGTCTAGAGTGCTGACCGATGCGACTGTGTGGCTACCATAGAGGGCGTTTCGCC
          ACTTCCAGGAGGGCGCAATGTTAGGGCGGACCGTGAAATTGTGTGGTTTGAACCCCCAGG
          AGTCAGGGCACAGCGCTATCGCCGTGATCATCAGGCAATTGAATCCACCTGACAACCAGT

          TATGGGCTCCTAGTACGGGGCCCATAGACTAGAGCCCATTCTGAACGTATATTGGGTGTT
          TATAGGCCTTTGGAACGGGGCACATAGACTAAACCCCATTCTAAACGCATATAGGGTGTT
          TGCAAGCTATAGACTTGGGGGCATCAAACCTAAGAACATCCTAAATTTGGGGTGTGTGAG
          TATATGTCCTATATTTGTAAGAATCTAAATTGGGAAAAAATCAGGAGCCGTCAATGTAAT
          CGCGTGTCCAGAATCCTTGGGCCTCATACCCGGATTACCCTTGAAAGATAGTATCCCGTC
          AGCAAGTCTTTTACCGACTGATATCAAGCTCGAGAAAGTTTAGAGGTCAAGCCGTGTCAT
          CTACCGCTGATCCTCGTTAGATCCGCGCTCGAAGCTTATCTGGAAACTGAGCTGACGGAC
          TGCTCGTCCCTGCGTAACAGATCTCAGGTTTAGCGTAACCGAAAAACCGGATTGTATGAT

          TCGATAATCTCTTACATCATCTCCAGTTTGTAAAGAGAGACACCGACCCGAAGTAGATGC
          TCGATAATCTCTTACATCATCTCCCATCTGTAAAGAGAGACACTGATCCGAAGAAGATGC
          ATAGAAACATTAGCTTCCGATTCATAAGCTAATCGAGGGTCGCAAGCCCTACATAGTATC
          GCGGCAACATGATTCTTTCAATCGGGTTTGAGAGTAGCCGTGGGACAGCAGTACAACTGT
          GAGGTATTATCCAGCACAAGTTATAGTCAGGCTTAATAGACGAGGATTTAACATAGGTGC
          GATTAGATATCTCTATGAACAAGCAGGTAGATGTGGAAGAAATCCCCTTAAGCTAATTAA
          GCTGTTATTCCATATCCCGACTACTGGGTGTCTAATAAGAAACGGGTTTACCGCGTCCGG
          ATGGTGCCTTCGTCCCCAGGATGGCGCCCAGTCTAAACCATGAAACCAGCCCCCGCTAGC

          TGAACCCAGTGAAGAGAAATGCAACCGCAAGGAATCACTGTCCGCGGAAGGCTGCGCATA
          AGAATATAGTAAACAGAAATGCAACCGCAAGAAATCGTTTTCCGCCGAAGGCCGCGCATA
          AGCAATCATGTTGCATGGTTTAAACTGTTGACTGGCATTTCGGGCGCGCGGATGACCCAT
          GGAGATCGCGAGACAAAATTCATGCCACAATTATTTGTTCTCTAAAGGTAGCTGAGCAAA
          ATCAACCGCTAGGCCGGTCTAATATCGGGGGAACCCCCTACCCTCATGCAGATCGGCGAG
          CGGGCCAGCGTGCTCGATATAACGTCTTAAGGGACCATCCCGCGTAGCCGGTGGAGCACT
          TTAACGTACGAGGTGGGCTTAATACGTTAGGGACTTGTTTTAGATAGACGCCCTAGGCAC
          GTCACCATTACCGACATTTTAGCGCTAGTGAAAACTGTTTGACGGACAGTGGAGGATCTG

          GACACCCCAGATTTGGCGATATTCGACGACAATACCAAAACCTGCAAATCCATCGCCCAC
          GACATCCGAGCTTTGGCGATGTTCGACGGCGACATCAACACCTACTTACCCATCGGACAC
          AGAAGCTTGTGCAGGGCGTTGAACAGCGCAGACGTCTGTCCATGTATACTTGCCGGACTT
          ACAAACCAGGGCTTGACGACGCGCGCTGGAGATATGAATCTATTGACGTGTATAATCGTC
          TTGAGCCCCTGTTCACTGCAATGTAACTGATAGTTGGGTTCTTGTCCCTCTCCAATTCTT
          TAAGGGAAGGGCTTAGAATTGTGGATGTGCAAGGGGTCATCAAGTGCTATCAGTGGCACT
          AAAGGTTAAGGATAGGTGACGCCAGGCTGTGATTGGCAGTTCCGTACCCCTTGGATAATC
          TAAAGCCCCAACAGGCCGCTATTTAAGAAGGGCGCGATTTTTAACCCGGGTAGGGAACAG

          GGTTCGCGAGACTTCGTGCAAAAGACTCAGGACGACGTGAGTCAAGATGGCAAGCATCCG
          AGCTCGCGAGACTTTGTGCAAAAGTCTCAGGACGACGTGAGTCAAGCTGCCAAGCTTCTG
          GCTCCATGAGTCTTTGCACAGAGATCCTCCCGATTTGGCAGTCGCCCTCAGAGGCCCGGG
          CGCCCCCGTACGTGGTCATTCCTGACTCGAATTGGTGTAAGCACCGTGAGAGGGAAATAG
          AATGTGCGGGACATAGAACCGGTATTCTAGCCTTATGGCATCTACATGAAAGGGTTAGAG
          GATTTACGGGTAACTGAGTCAAAATTCCACATTGTTCGGATTCTGCTAACGCTCACTCTG
          GACTCAAGGACCCTTGACATGTTCTTTCAGTTACAGATCGCACAGAGGGAGGTCTATATG
          TACATACTAGCATTCGAGCCAAGTACTAATGTAGGTCGCTGTGAGATTCCGGAGCTACGG

          TAACGCATCTGGATATATACACAACGACTGGGTGTAATTTCCCCCGTCACGCACGATGTC
          TAGCGTATCAGGATATGTGTACAACAACTGGGTGCAATCACCTCCGTCACGCACGACGTC
          TAAGCGATACGAATCCATATGGGTTAATCGCACGTGCTTACCCCTGTGCTGCAACGTGCA
          GAAGAATCATGCACTAATGTAGGTCAAACCCTCGCATGCTTTTACCATCTAGGGAGGGTA
          CAAAAACTATCAACACTCGTACTCCTATCTGACGCGTACACCCTTGTACCGCGGGGGGAG
          TATCCACAACCCAGCTGCGTAAGTCGCCCCTAGACTTTCCTCTCTACAACGCGCTGACCA
          TGATGGTCACCCCTTTGAGAAAAAATGGTTCATATATGCGTTTTTGCCCTCCGTCAGGGG
          CGTATGTGTCCGGCCATCAACAGATGTGTCCGTAATCATACTTAATGCTCGCATCGGGTA

          AGGCAATGTGGCAATGCCACGGTGTAGTTCCGAGACGCTGCGTAAGCACCACTCGTGAGG
          AGGCAATATGGAAGTGTCACGGTGTAGTTCCGTGATGTTGCGTAAGCACCTCCCGTGAGG
          AGCCAAAATACCAGCATTGCGATAAGTGTTTAAGGAGGCCCGAAAGTGCGGTTTGTAAGG
          GGGGACCAAGATCGACATGCAGAACGGGTTTTAGCAAGCACGTAAATGTCACCTTAACGA
          ACCTAACATAGTAGACGCGCTTTACATACTTGAGCTGGGGCATTAGTGTCACCCACAGGT
          ATGACTCAGAGTGCCGAAACTACCTGGCCTTAGGAAGACGAACACAGGGTACTTATTCAA
          CAGCATTATGGGAGCGTACCCTCAATGGTCGAGGTCGCCATAAATAAGCTATTTTCCGTA
          AGCTAGAACTGAGGAGCCACAACTACAGCCCGAGGTGTCGAGTGAAACTACGCTACGTTG

          ATAGACCGTGCGAGATGTGTAGAAGATATCACTAACACGAGGAACAGTCTCACCCATCGC
          ATAGACCGTACGTAATGTGTAGAAGATATCACTAATACGAGGAACAGTCTCGCCCACCGC
          TCAGACCATATATTGCGCGTTGGGACACTTATCTGCAGGAAGGGCAAGTTCGCCCTTCGT
          GTTTCCTGTTAAACATCCGCAATGCTGCATTTATGCGACAGGCTCAATTTCGTCGTCCGT
          CCACCGCGTAGGCCGTGTGTTAGGGCCCTTACAAACAGTGACTACCTTTGTGCCTATCAC
          TGGCAACCCAGGCCAGTCGCTAGAGGACTCATGGATAGCGGGTTTCTCCTTGGGTCCTGC
          TTATGGCGAGGGTTTTACGCTGAAGTTCAGAGAATGAGAATAGTCTTTGCCAGCTATTGA
          CATTTCAGCAGGATACGAATTTAGGAAATTACGAGTCGTACAACTCGATCTGTCTTGCAC

          CTCTGCACCCTGCTTACTCGGCCAGAGAGTAGACCTAATACGCAAGTCCGATTGCATTCT
          CTGTGTGCCCTGCTCACTCGGCCAGAAAGTAGCCCTAATACGCAAGTCCGGTTGCATTCT
          CCCTATAGCGGCTTCTCATAACCATGGGGCTAGAGAAATACATAGGTTGAATAACTCTTC
          CCCCTTCCAGGCCTCACTTTATCACGGGGAAAATAGAGCTTCCATGACCTAACGCTCCTC
          GCACGCGCCGAGTTTATTTAGCCGAAAGAAGCGCCCAACATAAAGGTGCGGAGGACCACC
          GTCTTGACCGTTCTCGTCTCGTCCCACGGAAATGCCAACGAGCGTATAAGGGCATTCCTA
          CTACCCTATAGAGCCGCAGAGCTTATGGAAAGGTTCTTTAGCCGCTAAGGCAGAAGCTCG
          TCCTCCGCTCGAGATCACCGGGCACAGTGCGAGCAAATCACCCGTGAATGATTGTGTTGT

          AAAGGTTGCCGTGTGACCTACTAGCATAACTTTGCTCACTACTTCATGTAGGCCCCGACA
          AATGATAGCCGTGTGCCCTACTAGCATAACTTTGCTCCCGACTCCATGTAGGGTCTGCCG
          GGTAGAGATCGTCTGGGTTCTTTGCGTAGATACACCCCAAGCGAAATCTCGCACCCGTCG
          CGGGCGAGGCGTGTGAAACCCCAATAGAACTTTACTCTTCGAGGATCCTCTTGTCCGACG
          AGTGAGAGTCACTCATATCTCTGGCACAGCTTCAAATCTAGTGGGCGGGTAGGCCTGAGA
          TAGCGCAGTTTTCAGCACACCCCTTCCAACTACCCCATCAAGGGATCCATGCGTGTATCC
          TAAATGAGAAACGGGTCCCGTCAACTTAACCCTCATTCCGAGGGATTTATGTGTGTGATT
          TGTTCCGGCATTTACCCGCCTTGCATTGTTCACAAGTTAAATGGTCCCTAGAGCCCAAAT

          CATGATTTTACTAATAGGTTGACTGCTTGTCTTCTAGTCGTGGGTGTACAGTACGTCTAG
          CATGATTTTACAAATAGGTTGATTGCTTGTTTCTTAGTTGTGGGTGTACAATACAACTAG
          GTAGGCATCTGTGACTGGTTGATTCCATATCCCCCAGTAACGGGTGCTCCACGATACCTG
          GTAGATACCCGCCTCCAGCAGATCACCCACTCACTAATATTGCGTCTCTGCCAGTTGCGT
          TCGGAATTTTTTTGAAAGTTAATCCACTCCTCCCCAGTATGGGGCCCACCGAGGCAAGGG
          CATGACTGTGACCAGCATCGGTCTGCCCGGTTTCGGGTATTGGGTGATGTGTAAGCTTCG
          TATGCTGCCCACGATCAGATGATCCAGTATTTCTCAGTCTTGGGAGCAAAACACCCGGAC
          CCGAATTCTGGCGCATAATCGACCCTGAAAATTCCAAGGATGAGGGTATGAAGACCCCGG

          TCATCCGTAACCCGGATGACCCAGGCGAGTTCGAGCTTTG
          TCATCCGTAACCCGGATGACCCAGGGGACTTCGAGCTTTG
          TTACGGGGGACCCAGAGAACTGGGGGGGTATTAGACGCTA
          CGCGAAATCACAAGGAAGGCTCCGAGAGCCTCAGGCTTTA
          ATCCTAGAGTGATTGAGGATTCCGCCGGTCTCAATCCTAA
          CTACGATAGGTTTCGCATTCGGAGACAATCGCGATCGACT
          CAGACAATGATGTTGTAGAGACTAAGAACAATAGGTTGGC
          TGAGGGTGAACATTGATTGGCCTGAAGACACAGGGACCTC

