 8 1000
t1        AGTTAATGGCCGCACAGAACTCTAAATAACGCCTAGTGCGGGCGCATGCGTGTCATTTGT
t2        ATTCACGCTCTATATGGGAACAGCCATCCTACATGAAATCCGTATACCAGTACCGTTTGT
t3        GGTTCGGCGCCACTCGATAGCGATCGCACCGCCCTATACCTGTTTCTGCGGAAGACTTGT
t4        GTCCCTGAACTATTCAACCGTCACCGTATGATTCCACACCTGTATATGCGAGCGCCTTAT
t5        GATTAAGTACTCTCGATTTCTATAGGGCTATTCTGACCCCCACTGATAACCTCTATATAC
t6        GCAGACATACTAAACAATTTTTCACAACAATTTAAATCCTTAGTCACAACCTTCAACCAC
t7        GTTCCCGTCCTTCTTGGACCTTGAGGTTCATGGCAACCTTCCGATAATGTCATCGTGCGC
t8        GTTTGCGTTCATCCAGGACCTTGAGTTTAATTGCACTCCCCTGATAGAGCCATCGTGCGT

          TAGGTTTGGGACGTCGTTAAGTTGTTTCCCATAAGTTCTCCACGTATCGCTGACTTGTGC
          GACATCAGAAACTTAGCTCAGACTTATATCGAAAAATATACGTGTACTCTTGCCAAGCCT
          GAGTGCATAGCGACGAGCCAACCGTTATCTAAAAATGGCCAATAGTTACTAGGTTGGGCC
          GAGAACAGAGACCCAGGTCCGCAGTAATTTAAAAACAGCTACTGGTCTGCTGATCTACCA
          CTGATAAGTTATAAGACCCAACATTATCTGCGAATCAGCAGAGTCAATAGCGGGTTTTTT
          CCGAGCAGTTATACAGTTCAATATCATTCGGTCAGCCGTACAACCCGCTGTTGACGTTCT
          CGGACCAGTCCCACTGTCTAGTCACCCCTCACTGTCTACGATTTGGAAGGCGCACATTGT
          TGGACGAGCGCCACTGGCGGGATGTCCCTTACCACCGGCGATTCTGAGGGTACACACCAT

          GCGCATGGACAGGGAGAATATCGAACGAAATCGTTGGGACACTGCGGAGATGGGTTCACC
          GTCTGAGTTAGTGAAGATTATTGGTAGAGGTCCCAAGAACCTTGGGTTTCTCGGCCTACG
          GATTTAGCAAGAGGGGGGTATTAATAGGGATGGTTAGGATCTTTAATTGATCTGGTTACA
          AGTTAAGCAAGAAGCGGATCTTAATAGAATTAATTATGATGTTGAATTTATTCGGCATCA
          ATAGGCGAGTCGAGGGCGGCTGATATGGCACTGGCGAGTCACTATTCTGCTGCTAAATCG
          GGTGTAGGATTGAGGATGGTTAACATGACACTTTTGGGTTACCCATATGTAGCTAAAATA
          AGATATAACACTAGAAAGCCCAAGTTGATATCAGTAGCACTTCTTGGTAGACTAGTAACG
          ATATAAGGGACTGAGAGGCAAAAAACGGTCTAGTCGGAACGTTTCACTTGACCGGTATCC

          TATCCAGGCTAGACGATCTGCGAATCTACAAACGTCGTGTCATTTAAAAGGTAACTGAGA
          CCTCGTGCTGAGCACCTCAGAGGATTGAAAGGCGTTGTCGCTGCTAGTAGTCGTCGATGT
          CCCCCGGACGCTTAGCCTTGCGGGCCCATGAACTCCACAGCTGCCCGTCGCAGCGGGAGC
          GCCCAGGACATAGGGCTACGAAGGTTTATATACGTTGCCGCTACCCGCAACAGCCGGAGC
          GAATGTATAGGAGGGCTCCGAAACTTTACTTGTACAGTGGTCACCGGTCGCCTCCCTGTT
          TTAAATATAATCTGACTCCGAGTCTTTATCCGCGTGGCGGCAGCCGGTCAGTCTCACGGC
          CTCCGTACGGGATCTCCACCAGCTTCTTTGTGTATTGGGGCCGCCGGACTCGGCTTCAGT
          CAACCTATGAGGTCATAACAGGCTCATTGGCGTATTGTGGCTGTTGGAAGCGGCTTTAAA

          CTTGTACAAAGTGGCGTGACCTCTAGGCACCTATATGCATCGGCCGGTAATGCACGGGGT
          GCTGTTTGATCCGGCACCAACCATTGCTGGCGAACCAGGGGGGTTAGGAATCAGTGGGGT
          TGTACACGAAGGGGCGTAGACTCCCGATGCGACTGTGAGTCGTCAGATGCTCAGCGGGAC
          TCCATTTGAGGACCCGTTGGCCCGTGATGGGATTGTAAGCCTCCAGATGTTCGGGGGGAC
          TGATCTCCGGCTCAGTCCAGATCCCAGACAGTGTCATCCTCGGCACAAAACCAGAGCAGG
          TGCGTGTTGGCTGTGGCCAGGATCCAGAAAGTGTTACCCTCTACTCCAAACCCGGGCCAG
          GCGGCTCTACCTATGACAAGTATACCGACATCACTTCATTTTTTTTCCAACACAAGGTTC
          CATGACTCACTTGTGGCATGCTTTCTGGCTTCATTACATTTCGCTTAAGAAACGAGGTCC

          TGTTGAACGACACAAATGGGCGCAATAGATCAATTAAAGGTAAATGTCAACGTAACGTGT
          TGTCTAAAGAGAAGATCAGGGGGTGAGGATCAACTGGAGACCAATTCCAAAGTAACGCGT
          CTCGTAACGGAACCGTTGGGCTAGGTAATACAAGGGGAAGTGGTCCCTGGGGTGTAACAT
          TGCTTAACGGCATTGTTAGACCAGGCGGCACAAGTAGAGTCGGCACCTACGGTGTCACAT
          CAGGCACAGGCGCTCACTAGTGTCTGCCGGGCGATGACCCCCCCCCTGACGACTATGCGT
          TAAGTACAGGAGCCCTTAAGTTTCAGATGAGCGCGGACGACTTTAATGCCGACTTCGCGC
          CAATTAGTAGAGCATTCCAGCGTGAGCCAAACGCAAGTGGAGTACCTCATCGCGCCGCGT
          CAACTCGGGGAACGCCCTATCGTGTGGCAAAAGTAAGCGGTGCAACCTATTACGATGCGT

          CTCAATATAGTTTCAAAGGCGTGTCATCTCCCCTAAATAGCCTAGATAGCGACTCACCAG
          CTGGAGATACCCTTAACACTACATCTTTCCCCACCGTGGACTTGAGATCTGCTGTTGTAG
          ATTCAACCATAAACTGCATTGTACGGGTATACACTCGCGGCCGGGGCCGCGGTCCCCCTG
          GTTCAGTTAGAAACTGCAGTGCGCTATTATATGCTCGAGGCCAGAGCTACGTTCTCCCTA
          CTTGACCTAGCGCCTACGTGGCATTGCTCGCTCCCGTCTGTTGGGTTGTAATCCTTAGAA
          CCTGGTGTGGCGCCTACGATGCACTGATAGCTCCGGCATGTTGGTTTATGATTAATGGTA
          TTTTTTGGGTCAGGTGCATTAGAAAGTATCCTGCCGTACGTCGAGTTTCAGGCCCTGACG
          TTTCTTGAAGTACGCGCGTGGTAAAGTCCTTTGCTGCTCGCAGCTTCGTAACCGCTGCTA

          CATTGATGTAACTCTGCCGCCGAAGACACGAGCCTGAAGGCCCAACCTTTGCTTTCAAAC
          TAGTGAAGTGACCCCTTGTTGGGTACACCCCACCCGATGTGTCAACGTCAGTGCTAGCCC
          GGAAGATGTGACGTCTTCTCTACAGGAAAACACCTGAAGGGCCGCTGTTTGCATTATAAT
          TAAACGTGAGTAGTTTCCCCTTCAGGGAAACTCCTAGAGGGTCGTTGATTGCGCTACAAT
          CAGTAGCGTCCGATTGTTCCAAGGGTGATTAGTCGGTAAACATGATATAAGGATTACGAC
          TAGCTGCGAACGGTTATCGCCAAGGAGCTTTGAGTCCTCGGTTAGCGCCACGTTTACGGC
          CAACTGTCCGATGTTCTTTCAGGACGGATGTCTCCGTAAAGTTAAAGTTCTTCTAACAAC
          CAATTGCGGGATGTTTTCCCCAGATTGGCTGATCTACAATGTCAACGCCCTGTCAACGAC

          ATGAGGTACACAGGGCCGAGCTGTGCCATATCTAAATGTGGGGACGAGCGCTAAAATCAG
          ACGGGCAGGCCTCGCCTCACCAGCACCCCCCTCGGGTAGAGGCTCCAGCCCTAGTATATC
          GCAAGCTTAGTGCGGACATTTTGCATCAGTTGCGAGTATGGTGCCTGGCCTCGGCGTAGA
          GCAAACACAATGAGCCCACTTTGAGTCAACTATGTGAGTGGAATCTGATCTTGACGCAAG
          TCACGGCGGTTAAGGTGACGTGATGCAGACGCAGCTTGCACCGTCCGCAATCCGCGAACA
          CGACAGCTTTTGCGCCGATGTGAAGTTAACCTAGATCGCACGAACCGTGATCCGGGATCG
          CTCACTTCGAAGCGTCGATACGACGCCATCTAGAAGCACATATTCTTAGCACCTAACTCG
          CCAGCGTCGATATGTTAATATGACGGTACTCCGAAGAGCACGTTCACAGTCCCTAATTCG

          GATATTTTATTCATTATGCGTGATTGCTTGCCCGTAAAGACCCTCAAGGAGCAGCCGCCG
          TCTCTCAAGTCTACTGCGCGCGGCTACTAACTACCGAGCGTTTACCTGGAGCAGGAACTT
          ACCATACTTCTCTCCAACCGGGTCACATATTCTTAATGAAGCTATAAGGGAATTCCGTTT
          CGACTACTCCTATTGAACGATGTCCCATACCCCTTGGGCAGCTTTAAAAAGAAATTGTTT
          GCGAGCAAAGCACTCTCCTAACTGTTACGGACACTAGATCTTGAGGTGAAGCTACCATAC
          GTGAGCAAGGCACTTCTCGATTAGTCACGAGCACTAGTTCCCTGAGTGGAAAGACTACAC
          AAGAATCGAGCTGTTCTCTACCCGATTTAAATCCCCAGATCTGAGCGTGAGAGGTCACGC
          GAGAATGAAGCTAATGTCCACCGCGTTTAACCTCGCAACTCCGAGGAAGAGCGGTCACCT

          ACCGATCCTATGGTGAAGGCGTGTTGAAATTGGAATCTAGGTAACGGGTTTATTTGATGA
          CCCATTGCTCGGGTGGAGGCGGATCCCGGCTGAAACTGAGCCTGTGCGAATAGACGAGGA
          ACTATCCTTGCGGTACAGATGGCATCGGTACGAATCATAGCATTAGTGACCAGAAATTCG
          AAACTCTGCACGCTGTAGGCGCCATCGATCCGAGAATTAACAATAGGGTCTCGGTTATCG
          ATCATCACCGGGATCCGAATGGGCCAATGCGGAGTGCGAGGGCTGGAGAACCGGCAATGG
          GGGACCAACAGGGTCCGAATGAACCTACGAAGGGCGCGGGGTCGTGGAGATCGGCCTTGG
          AATGTGGCCAAGACCTACCTAAGCCTGCCAGGGGTCTAGAAGACCCTGATCTAAAAAACA
          ACTTCGGCATGGAGTTGTATAGGTACTCCCCGAGTGCGGGATCCTCCGGGCGAACAAATA

          TCCCTTAGACCGGGCAAATGTGTCCGTGCTTCCTCTGCGGAAGCGAAGGCTTGGACAACG
          TCTCGTAAAACGATCGTCCGTACATGCTGGAGCTCAGTAGCAACCATAATTTGGTTAACT
          TCCCACCGATCAGTAGCGAGTACGCATATCGACTCGGTACAGACAATAGCTCGGATAACG
          TCTTGCCGATCAGTATCTAGTACGCATCTCGCCTTGGTAATAATGATTGATTGGCTAATG
          ATCTAAAGGTGGGACGTCTGTGCACATGACCCTTCGGTCAGCCTCATCCTGCGCATATCA
          TCCCTACAATCGGACACCTATTCGCACAACCTCTTGATCGAACTGGTAACATGAATACCC
          TGTTTGGGGATGTAGATATGTATATGTGGTTTCCTAGTCAGGCTAATTGCTTAGATCCAT
          TTTTTAGGATTGGGGATATGCTCACGAAGTTACCTGGCCGAAGCAGCTGCTTGTACACTC

          TTTTATTATACGCGCGGGTTGTGCAGTGCCATACAGTCCAACCATACGCATACATAACGT
          TAATGTCGAATGAAACTCAGGGCCACTGTCTATCTTTGACACAATAGGCACGCATATGGC
          CGGTAGCATATAAAGCACGTACCCTCCTTCTTCTTTTTTAGAGAACAGTGAGCAAACGGT
          CGGTAGCACGTAAAGCATGAAACCACCTGTTATTTTTCTCTGGAGATGAGAATATAAGGC
          CAAGCACTTTTGTGCCATCAGCTGGCTATCCCTTCACGCGTGACGTAACTGCAGCCGAGA
          TAAGGTTTTCCGAGCGAATTGTCAGCCATCTTCCCTAGCACTGTCCAATTCACATGGACG
          CAGCGTCACCCCTGTCACCTGTACTAGGCTCTTATACCTATGAGCTAACTCTGGGGGGGC
          TAACGCCATTCACGTCTCTTGTTCTCGACCTTATAAACCACGCCCTAGACTCAAGGGGAC

          TAAATCAACACGTAGTGTGTTACTTGCGTTAAGTAGTGGCAACTAGCGTCTGAAACTCCG
          TGGGACTATAGGCAGTCTCTTGCTCAGAATCTACAATAAAGAATAGGTCTTAGTACCATG
          GGCACCTAGACGTTATAGTATACTTGATACCGAGAGGGGCGCTTCAGTTAAGGGCCTTTG
          GATACTTACGCTCAGTATCATTCATGGTGCTGACAGCGCTGGTTAAGTTAAAGGTTTTTG
          AACAATGGCGCAAAAGAACTGAACTTGAGTGAGCGGTTCAGGACAGGTTTATGGAAAGAA
          GTTACTCGTCTTCCAAAATTGATCGCGAGTTTTCGGCGATTGATTAACTTATGGACGGAA
          CCTACGAATACATCAAAGACCACCTTGTTTTGCTCAGAATGAACAATCTCAACGCAAGAG
          ACTATGAGTCCACAAAAGTTCACCTTGTCATAACAGGAACGGCTAAATTTAAGATAAGAG

          CCGTAGCGTTTATTTAACAGAAATGCGGATGGTAGGTTAAGCGTGCCGTAGGGCGCCGTC
          CGTCAAAACCCATGCTGAGGAACTATGACGAACCGTACAGACACGTGGCTGGTGGCCATT
          CCGTAAGGGCCCCGATAGAGAACCACGATCAGTAGGGTAAACTCGCTGTTTGGTAACCCC
          CTGTAAAGTTCAAGACTAGCAAGCGCGATCGACTGCAAATATACATCGCTCAGAGTTCCC
          GGGAGGCGATTGAGATGCGATAACGTGAGGCGATGCTAGAAATACCGGCCTGCGGGAACG
          CTGCGGCAACTCAGATGTGTTACCGTGAAAGGCCACTTGGAAAGATGGGACGGGCGCACC
          CAGTGGTGATTAGCGCGAACTGTCTTGATAAATGGATTCACAGCCTAATTTCTAGAATCT
          CAGTGGCGAATAATGCTGATGACCGTATCACACAACCTTCGAGTCCGATTTTCGGAGTAT

          TTATCATTGCGATCGTAACACCGGACGTGCTCCTCTAACATACCTCATCGCTTCGAAGCT
          TTATCTTCGCAATCTACGTGTCGGGTGAGTCACCACATGCGGCGTAATCCTCCGCCACTC
          CTGTTTTCATGACACCAGGGAGATAGGGACCACTGTGCCAACCAGGCGTTAGTCATGCCC
          TAGTCCTTACGTAGTCGGCGACAACTGGGCGACCGTGCTACTTGGAGATTCATCACGGTC
          AAATCTCGAGCATATATACAAGTCGCGCGGCATTGGAACACTTTTCCCATCTCGAATGAT
          TAGCCTAGGACATATGTGAAATTTGTTCGATGCTGGGGCTTTATTTGCCCACTGAGTCTA
          GGGCTCATAAGGACCTAATCACTTGCGTGACACTGGGGCCCCACTCATTCTCTGAGAAGA
          TGGTCCACCAACCCCGGGTCAACTGCGTGATACTGGGGCGCCACCGACTCTCCGGCTGCG

          GAGAGTCTTTGCTTGCACATCGTATGCCCCCAGGCATCGT
          AAACAACCCTAACCATAACTTGCCTGGACCATGCTGATTG
          AGGTACCATTGGTCGGAACTAACACGCTCCCAGATGCCCG
          AGATCAAGTTGGTCTTCTCTAACTTGCTCACTGAGAGCAG
          GCAACGCGTCTACCAAGACGAGCCGGAGGTACGTCTTGCA
          TAACCGTCCCAACGCAGACGAGTGGGCCTTAACGCCCTTG
          GCCCGGATCTGGCCATGCCAACTCGCTCTTCTCGGTCCTA
          ACCCGGACCCAGCTATGTCGAACCGACCTTTTAAGCCTCA

