 8 1000
t1        CCTTATCTATATCGAAGATGCCTGCGTAGCACACTGCAATGAGGTCCGATCGAGGGCCCT
t2        CCTAATCGGTAGAGGAGTTGTCAACCTGGGACCCAAAGGCGAACCCCGTCCGATAATTGT
t3        TCTAATAAGTAATCGGGATGCGAGCTCAGGACCTAATAGCGAACCATGAGTGGTAGTCGT
t4        TCCGATCAGCAAGTAGGACGCCAGACCAGGACCGAACAGCAATCCGTAAGCTGTAGATGC
t5        AGTTTCTAGCCAAGAGTGCACGAGGTGGCAACACCACTCAGGCTTACCAACCGGAAGCGA
t6        AGATGGTGGCTAAAGGCCTGCGTGTCATTATTCCTATTTAAGCCCGTTAGTGGTACACGA
t7        CGGTGGCGGCGCATGGCCTACTTGTTGGAATTCCTATTTAGATTTATTCGCGGCACTAGT
t8        CGGTGGCGGCGCATGGCCTGTTTGTTGGAATTCCTATCTAGATTTATTCGTGAGAGTAGT

          GCCCACAATGGCGATGAAATTTGATTCAATTGTTGGGCTACTAACAGTATACTTTGATGT
          AGCCACAATGGCGAAACCGCGTGGCTCACCCGTCAATCTACATCGAGAGCACCATGGAGG
          AACCGTAATGATGGTCTGGGGAGCTCCACTTCTTTGACCATGACAAGCCTTATCTAAGAC
          GCCAGGAGTGGTAGCCCGGGATGGTCCACCTACTAAACTAAGACGATGCCGACTTAAGGC
          TAGAAGCATTCCGGATCAGTCACAGCTCTCGCCTCGGCTATATCGGCGGCCCCTCCGACC
          AGAATGAGAACCAAGGCGAATAGCGGTCCTTTATCGGTGACCGCCATGGCCTAGCTAGCC
          ACATGGTATATCGGGATAATTCATGCTCCCAAGATGGTGGCTTCCAAGGTTTTCTTGAGC
          ACATAGCATACCGGGATAATTTGTGCTCCCAAGATGTTGGCCTTCAAGGTTTCCTTATGC

          TGGGCCGGCTAGCTGAAATTCCGACCCTGCAGGTTGATTGGCACTTAGGGGGGAGTCAAT
          CACTGCGGTCAGCCGAATTTTCAAGCCTCTTAGTTATTTGGCTTTGCGGGGGGTGTCAGT
          TCCCACGACTAATTGCAACACCCCGCCTCTAAACTACACGAGCCCATAGGGGGGGTTTGC
          TTCTGCGGCTAACTGACGTACACTGCATCCAAGTTATATGGGTCACCAGTGGCGGGTATC
          TCTTTCGGCAGTGTGAAACATCGAACTGGCCGTTCGGGAGATTTGGTGTGGGGAATCATT
          TTTTTTGGACCCGCGGAACACCGTATCCCGCGTGCAAGAATTATGATGCGGGGGATCGTT
          TTCTACAGATTCGCTAGACATAGAACACTACATATAGGATACTCGTTGAGTGGAGCTGCT
          TTCTTCGGATTCGCTAAACATAGATCACTACATAAAGGAGACTCACTGAGTGGAGCTGCT

          CATTGATCAGACACGCTCTAGGATTGCATAGTAAGGTCAAATGTGTGGAAAGCGTACGGT
          CGTAAACCAAAGGAACTCGGGGACCCTGCAGAAACATCAAATATGATAGCCTCACATGAC
          TGTTAGCTAGAGGCACTCTAGTACTCGAGCGCAATATAGAACTAATTAGGTACTTATGGT
          CACCAACCAGACATACCCTGAGATTCTGAAGCCGTACAAGACCGGTACAGTTCGTATGAT
          TGATTGCCACTGACAAGCTAGCCCTATGGGGCGCAACACCAATTCAAGGCTCACTAACAA
          CGAATGCCACTGGCTATCTACGTATTTGAGGCAACGTGGCGATATAAGGCTCAATACGAT
          TGCATGCAACTAGCTATCAGCATTATTGCCGAGTACTGATCGCGAAAGTCCCATTATGAG
          TGCATGCAACTCCCTACCAGCATTACTGTCGAGTACTGCTCGCGAAAGTCCCATCATGAG

          TCCCAATAGTTGAAGCTTAGGAAACCCAGCCGTACGGGCCGGCTGCCAACACCATGCTAT
          TCGAAACAGATGAAGCTGGCAGATCGCAGTTATCTGGGACGGCTGCCCCCAAGACGCTAT
          TCGTAACTTACGAAGATAGAAAGCTCCAGTCATGTGGACCGGTTGCCCTCCGGATGATAT
          GCGGATTAATTGTAAATAGGGAATTTCTGTTTTACGTACTGGTTGCCTACCATATAGTAC
          CTTGTAAACCTGGACCCAGGAGCGCTGACTAGAGGGACCAGGAAACTCGGGATTCGATAA
          CTGGTAGACGCGGATCCGGACGTATTGGTTTGTCGGCTCAGAACACTTCAGATTCAACCG
          CCGGTAGCCCTGGGGCTGAATGTTGTGGTTAGTGGGTCAAGGATATTCAAAAGTCTTCCG
          CCGGTAGCCCTGGGGCTGGATGTTGTGGTTAGTGGATTAGGGATAACCAAAAGTCTTCGG

          AATTCTCTACGCTGGGAGCTGGACATTGCTCCCAGGCCCGAGGCGTTGAGTATACAGCCC
          AGACCTACAAATTTTCAGTTGGAGATGACCTTCGGGACACAGACGCTGAATACATACGTC
          AGTTGGCTATATAACACCTTGGAGACAGTCGCTGGGTTGTTCGAGCCAAGTCCCTATTTT
          AGTTTGCTGAACTAGAGCTAAGACACATTCCTCATGGTGTACACGTCGAGTACCTGTTTC
          CGGTAGACATTCTAGTACATGAACACATGCATTCCGAAAAAAGCTGCACCTACCCGGTCG
          TGTTAGTCTCCCTGGCAACCGAATAAACATTTTTTGAACGGTGCTACATAAACTCAGCTA
          TGCTAATCACTCTCACACTAACGCTAGCGAACTATTACAGGGGTGTTACTCGCACGCCCG
          TTCTAATCACTTTCACATTAATGCTAACGACCTATTACAGGGGTGTCACTTGCAAACCCG

          TGTCGTGTTTGATCGAAGACGTGGAGGACCCAGGGAGATCGCAAGCTGGTGCCGATTCAC
          ATTCATGCCTCTTTTCCGAAATAGGGGCTCAAGCAGACCTGCGTGGTCTTAGTGGTCCTG
          GTCCTCACCCAAATAACGGGCTTCATGCCCCAGGCAGATTATATCCTAATACCGATTCAT
          TTTGCTATCAATAAACCAGGATGAGGGCTGCAGCTAGATTCCATGCACATACTGAACTAC
          TTTTTACTTATTTATAGCAAAAGAAGGGCTGAGAATTTCAAACAAATGTAGACCTTTGAT
          TCTTTCATTTTCTAAAAGCACAGGCACATACACAGTCTCAAAGGATTGCACGTTTTTAAC
          CCTTTCGTTTCCAAAATGAAAAAAAGTAAAGGGAGTCCCAATGGTTTGTGTATACGCCAT
          CCTTTCGTTTCCAAAAGGAAAAAAAGTAAAGGAGGTCCCAAAGGTTTGTGTATACGCCAT

          GGTGCACTAAGCCAAACGTCTAACATATGTATAAAAACTCACGACAGCTTGTCATTCAAT
          CGCACATTGGAACAAAAGTTCGGCGCGTGTGTCGAGGCATTAGCTTTCCTGTCATTCCCC
          CACTCCCGACGGCGGTTGTGCATCGCGCAGATAAAGTGTTATGTATAGCAGCATAGCTAC
          AAAACTCGAGGGCGGCCGCGTAACACGTGGGTAAAGTAGGAAGTATCACCGCGATACAAC
          TTTGGCAGTTGTCGAATCGGCTGTACTTGAGACAAATTCCAAACAGCCATTGTCTTGGCT
          TTCGATTGGAGTCGAATATGCTGCAACTGAGATGGACTCCAAACAGCGAAAGTCCTAGCA
          CTCACTTCAGGTAAAATCCGTAGGACCAGTGGCGGATTTTAAACAACTTATGTCTTGGAC
          CCCACCCCGGGCAAAATCCGTAGCACCAGTGGTAGGTACTAAACAACTTATGTCTTAGAC

          CTGGCATTTACATGATTATGGCTTTCGGCTCGGGAGGATGAGCCGTGAGTGTTTAACGAA
          CCAGTCCTGGTGCTCCCACTGTTCTCGAACCTGTTGACGCGGCTGATATCCCTTAGAGGA
          CTCATGCCAATATACAAGTCGGTGTCGGCCGAAAAAGCTGGGCTTTGAGCTTTCAAAGGC
          GCAACTTCAACGCGAGGGTTCAAGACTGCCGAGAAAGCTCGACTTTAAACCGTTAGGGGT
          TACATAATAGTGCTGTCAATATAACGGATCGTAATAATGTCATACATAGGTTATATGCTA
          CCGATCAAAGCTTTCGCGATATAATGGAATATAATAATGACGACGACAGGCCACGGACTA
          CCGACACAGACGGTAATGATATGATTGACAATAGTAATGCGAGTAACCTCCTCCGGGATA
          CCGACATAGATGTTAATGATATGATTGATAATATTAATGTGAGCGACCTCCTTCGGGATA

          TCTGCTCCAAGAGCGTAGTATGACTGGCTTTGATGACTCCCTCAGTGACGCCCAATTCAC
          CGCCTTCCTAGAGTATAGCAAGATTGGTGATTGCGGCAACATAATTAAGTTTTGCCTCAT
          ACCCTCGTCAGTGCTTAGCACGATTGGGTACGTTGCACAATTAATAAATTCCTACTTCAC
          TCCTCTCTTAAGGTACTGAATAGCTAGTTATGGTGCATGATTGATGAACTCTTATTTCAC
          TCAAGGTTTGGTAACTACTGTAGGCTATTATTCAAAGGGCTAGGTGATCCCACCAACTTG
          TTAAGGTCCCGTATCTACTATAAACAGTTAAGAAGTGTACCAGGCGAAATCCCGAGTTCC
          TCTAGGTTTGGTAACGACTATGAGCCATCATGGAGTGTATTGGATGTAATCTAGATCTTC
          TCCCGGTGTGGTAACCATTATGAGCCATCATGGAGTCTATTGGGTGTAATCTAGATCTTT

          CAAACCCCTTAACCGGCTTACAGAGCTGTATCGCAAGGTTCTTGGACAGCCATTTCGGAA
          TGAACACCTTGAACTGCCCACACAACTATTCCACCAGGCCCGTAGACAGCCAGTTCCAAC
          AGACCACTCTGATCGATTTATAGGGCCATGTTACTAGGCTTGTAGGTGTCTAGGACAAGG
          CGATAAACTGGAGCGGCCCATAGGGGCCCTTCACCAGGATCGTAGGCGGCTAATCCAGAG
          CGGCAATTTTCGTTGATGTGCAGACAATTTTCCTCGGGCACCGTCCTGGAGTGTTGCAGA
          AAGCAAAACCCTACGACGTTCTGACCTTTGCTGTACGGCGCAGTAATGGAATGTCGCGGT
          CGGTGTACCTAAATAACTTGCGGATTTCTGTACTACGGTTCCATACCGGAGCGTTGCGGT
          CGGTGTACCTTAATAACTTGCAGATTTCTGTACTACGGTCCCTTACCGGAGCGTTGTGGT

          GCTGCGTCGTCGCCCTCCAATTAGGCACGCCTTGCCGCAGAGGCGATCATTTATTCCGGT
          ACTGTGGCGTTAGGCTTCTACATAAGCCCTATTGCTGGCGAAGGAGCGATTACCCCAGGC
          GGTGTCGTGCTGGGTGGTGGCACGTTGTATATTACAGCCGTGTAAATCATTATCCTCGTC
          TTTAGTCCGCTAACCGTCAGCATGACGTGAACTGCAGATGCATACAGTATCATGTCCAAT
          TCAAGGATTTCGATTTTTTGCAGTACGTATGGGACGTGCAATTTTGACCTGAAGGAGGTC
          TCAGGTCTGCTGACGTTCTTACATCCCCACGAGCCCTCTGACCTCGACAAGCGGCAGGTC
          CTAAGTGTCCCAATGTTGTTCAATATGCATAACATTTACATCACCCGAAGGGAGGCAGCC
          CTAAGTGTCCCAGTGTTGTTCAATCTGCATAATATTTATAACACCTGAAAGGACGCAGCC

          AGCCGGGGCTCCTTTTGCCAGCGGATTAGCGGTCTATTGGTCTGATAACTCCGGGCCAAC
          GTCTGGTACGCTTTCTATCTGAGGATCGATAGCCCATAGGCTTGTTTGGCCGGGGACACT
          AAGCTGAACCTCCATTGTCGAAAGGCGGATGACTTATTGGTCAGACCTGTGGGGAACATC
          ATCGTCAACCTCTGCTACCGTGTGCCGGATGGCCTATGGGTCTGACCGGTGAGGGGCATC
          CGACTGAATTCCGCTCTCTTATAGGGGGATCATGACCGTGGCTCGTGGGCGGGCGGCACA
          GGATTGGATCACACTCTCCTGTCGAGGAAGCATAACCGGAGGATACGGGCGGGCGACATC
          GGTCTAAGCCCTCTTCTTTTATAGGGCCAGCATGGCTGAGGCTGCAAACCGGGTGACATC
          GGTCTATGCCCTCTTCTCTTATAGGGCCGGCAAGGCTGAGGCTCCAACCCGGGTGACATC

          AGGGGTGATTGCCGCTAGGACTGAGAAGCGTGGTCAGATCGAACTCGAGACTTGGTGTAC
          TGGGAAAAGCAGGGCCAGGACTGTGCAAAACAGGGCGACTGATTTCGGAAAAAGAAGTAT
          AAAAATGATTGTGGCCATAATTGGTGAAGGCAATTCGAGGGAGTCCGGCATAATGAGAGT
          AGGGATATTTGTAGCCAACACTCGGCAAGGTAATTAAACGAAGTCCAGCACATGAAAGAT
          GGAAAGAGATTCAGGTTAGCTCTCACCATGGTGCGCGGGAGCTTTCGGCATTTAAAAAAC
          AGAAAAAGGTCCGAATTCGCTCTAAGCTCGATCTGCAACCGGTCTCGGGACCAGAAAAAT
          GAAAAGAGGCTTGCCCTTGCTCTGGGTTTGACTCGAAAGGGGCAATGGAACCTGCGGAAC
          GAAAAGAGGCTTGAGCTTGCTCTGGGTCTGACTCGAAGGGCGGAATGGAACCTGCGGCAC

          CCTAGTAGCTCACCAACTGGGGGAACGCAAACTAAGGGATGTATTCGGTCGCTTTAAAGG
          CGATCTGGCCACTCTACTAGGTGCATGTCAACTAGAAGCTATTCACGGATGCTATGGCTG
          TGTAGTAGAGGATCAACAGAGGAGATGCGAACATAAAAAACTTCCCGGTCACTTTCTTAG
          CCTTATAGCCTATCTACCGTGGAGCCGTTGACATAAAGAACTATTCCGCTATTCCCTAGG
          TGGTACGGCTAGTTGATTTGGGACAAAAAAAGGAGAGGCGGCTTATAGGACAGCTATTAG
          CGTAAAGGAAAACTCATTCGATTCCAAGAAGGAGAACACGGCCCCTTGGAATGTCTTATG
          CGTAACAATCTATTGGCGCGAAGTCTTTAAAGAAAAAACGCGCAACAGAACAGACAACAA
          CGTAACAATCTGTTGGCGCGCAATTTTCAAAGAAGAAACGCGCAACAGAACAGACAACAG

          TCTATGTCCCCTCTTCGCGCCAGCGCGCGTTGTACTTGGGGTCCGGCGAAGAACGCGCAC
          CCCAGGCCGAAACATTTTATAGGAGCGGGTATCACCTGGGTTGTGGTGATGAAACTCTCT
          TTCAGTTTCACACACTGCGTAAACGTGTGCGGTTTTTGAAATGCGATGTCTGGTGTGCCT
          CCCAGGTCTAAACGCTCCAAAAACTGGCACAGTTCCTGGAATGCGATGCAGGATGTGCTT
          TCCGGGTAAATACGCCCGGGAGTTTCTAGCCGGATAACATACGCAGCTACTGATATACCA
          TTTGGGTACCTGCGCCCTGAAGCTTCTAACGGTAAATTACATATATATACTGGTTTAATC
          TTCGTGCAAGGACGCCCTGGAGTGCCGGGCGGAGTGATCCACTTGGCTATTAATATACCA
          TTCGTGCAAAGACGCCCTGGAGTGACGGCCGGAGTGATCCACTTAGCTATTAACATACCA

          GGGCTTGAGTTAACGCCGAAGGCGGAACTGATGAGAGGCA
          ATGCCCCAGACGAAGCTGAAGACAGAGCTATTGAATGGAA
          GTGCTCCTGGTTACGCAGGGGGCAAAGCAGTCGAAAGATA
          GTGTCTATGATTCTATCGTAGGCAGACATGGCGATTGGTG
          TGACCTGTGTCCACGACGTGAAGGGCCCCCTCCATTGATG
          CGGCGTATGCGCAAGTCTTAAGAAGCATCCCCGTACGGAG
          GGACGTATACCAATGACGCGGGGTGTATTCTCGTTTATCG
          GGACGTGTACCAATGTCGCGGAGTGTACTCTCGTTTATCG

