 8 1000
t1        CCTTAGCCGATCATGCTGGGTAATTCATATTGCTACTAGTTGAAAGGCTGTGGTCTCGAA
t2        CCTTAGCCGGTTATGCTGGGCAATTCGTATTGCTAATAATTGAAGGGCTGTGGTCTCGAA
t3        GCTTGGCCGTTCATGTTTGGCCATACACATCGCTGTCAGCTAATGTGATGTAAACGTAAT
t4        TTCGCGGCAGCTATGGCCCACGAAAAAAATCACTGTACATTATAGCGCAACGGCCCAACA
t5        GTCTCGCGGACCATGATAGATGCGTGGAACATCTGTCCGTATCTGCATTTCTGGTTAAAT
t6        GCTCACAGGCTCGCGCGAGGCAACAGAGACGTGCGTGCACTACGGTGTAATGGTAGATGA
t7        CTATCACTAGTTGTCAATTGCGGATGAGGGACTCCTCGCGAACTACGCTTTGGATCACGT
t8        ATGTGGACAGTTGGGTTTGGCAACAGTAGCTCATTCCCGGACGTGCTGCAGGGTACAGGG

          TTCTAGTTCACCTTGCCTCTCATATTGTAGTGAGATAGTGGATCTACGGTCCCACTTTGC
          TTCTAGTTCACTTTGCTACCCCAATTGTAGTGAGATAGTGGATCCTAAATCCCACCTTGC
          CTCCCAGTCACCTTGCTACCTTTATCGGAGAGAAACGGAGGACCTCAAATCTCATCCTGT
          ACCTTACGCATGCAGGAAACCGTACCGCGGTGAAGACGTGGAAGAGGGGATATGCCCTGT
          CATTTCTCCTTGCGTCAGCTGTTACTGCGAGGGGATGACGGAGACAAAGCCCTGGTATCA
          GTCAGACAGACCCGGTGCGTATTAAGGCGGAATGACAGCTGATGCCTCTCCCTAACCTGA
          TCCCGACTTAGGCGGCAACTTTTACCTTGGCGTGGCGACGATAGGCCTAGTGGGCCCAGA
          CTCTACATCGTGAGAGGGCCCCTTATCCTAAGCGCCAACCCACGAATACTCCCACTCAGT

          CTGGCCAATACTACGCAATTGATCACACCTGGTGATATCATTATCGTCTATAGGCTCCAA
          CTAGCCACCACCACGCAATTGATTTCAACCGATGATACCATTATCGTCTATAGGGACCAA
          CTGGCCGTCACCACGCACTTTATTACAATTCATGCCTCCATTATGACCCATAGAAACTAA
          CTGGCCTTTCCCACGCTAAGAGCTGTACCTCTAGGTTCTATAATTGTCGATATAGTTAAT
          ACGGTCTCCATAATGCACCTGTTTGGTTTCAACGGCACCCTTTCCGTGTAATCACAACAA
          TCGATTGTAATCCTACGCCACGCTGTAGTCTGGTGACCTGTCTATGATTATGGACATTAA
          CTTATAAGTCCGTAGTCTCATGGAATGGTTCGGAGTAACAGTCTCGTTACCAGACGCCTC
          TTGGTGCTAACGACGACCCTCACAACGCCCGGTTGTACCGCTCGTACTTATCGACACGAC

          TGAACGGCAATATGGTTTCTAATGGACCAGACGAATGTGACAGTGAGCGCAACTTTCTCG
          TGAACGGCAATACGGTTTCTAATAGACCAGGCGAATGTGAGAGTGAACCTAACTTTCTCG
          TGCCTGGCAGTGCGCTTTATACCGGATCACATGAATGCAGTAGGGAACCCAATTTTTTTC
          GGCGCTGTGGCTCAACACCGATCCGTCCTTATAGATATAACGGAGTACCCAGCACTCACA
          AGCGTCGCGGCTCCCCGCAGAACGACTATCAGACCAGTACCTCAGAACACAGCCATCTTC
          GGTAGGGCGTCGCGCGTTTCACGCGCCATAAAGGATGTCAGAGCAAATTTAGCTTTACAC
          AGCACACTGGCCACTCCTTGATCCACTTCGTGAGGCGCGTCATACAACACAGCCGTCCCG
          AACGCCATCGCCCGCGTGAGGGCCAACTACGTAGGAATAATACCCAATAGTGAACTTTGC

          AGGTGCACGGAGCAACTACTACGGCTCTAGGGGAGAGCTAGGCACGCCTTTCAATGAGAA
          AAGTATACGGGACAACTTCTACGGCTATAGGGGAGAGCCTCGCACGCCTTTCAATGTGAG
          GCTTGCATGGTACAGTTGCTACGTCTCTAGGGGAGTGTCAGCCATGCCTCCCAATCAGGA
          AGTTGCACCAGGCAGCCGTTACGCCTTAATTCCGGAGCGATGCAGACCCCTCAGTTAGAG
          AAATGCCCACAGCAATTGCCAGACTCCCCTAGACGAGCCCGTTTCGCATTCAAAAAGGTA
          GGGCGCATAGGGAACTCGTTACGAGTCCTGGGGTATGCCAGGTACGTACCGTGCGGAGCA
          CGGCACACGGGGAAATAACACAATCAGCATGCGTCAATCAAGCGTCTGATGGGAGGGAGA
          GTGCAGAATCGAAACACGGCGTCAACTTAGTAGTCAGATAGAATCATGGGCCGCTTAGGG

          TCGAAACTGACGTCGGTTACTTGCGTGCGATCGCTGATGAACACGGGTGAGCTGGTCCGA
          CCGAGACTGACGTAGGTTACTTGAGTGCGACCGCTGGTGGACACGGTTGAGCTGGCCCGG
          TGGAAATCGAAGTCGGTTACTAAAGCGCGGTTGCTGACGACCAGAGTTGAATTGACCCGG
          TCGGATATAGGCATGCATACTATGGGACGATTGCCACCGCACGGAGCAAGAAAGACTCGG
          CCGCTGCTGGTCAGGCCAACAAGGTCGACAACTCCGACGAACAAAGTGTGATTGGCGCGA
          ACATCATGGTTGGTGTTCAGGATGATGGTGTTGTCACCGCACAGATCAACACTGAATTAT
          TCGTCACTAGAATAAGGCAGTAGGGTATAGCCGTAATTGGATGGTGTTGGAGGGGCCTGA
          CAGTAAGTTGACCAGTGAATGGGTACGTAGGCGTGGGCAAACGGGCCAGGAGACTTTCGC

          TCAACGCCAAATACTGAATGGTCATCCCCACGGAGAATAGAGAGCTTTTCGTCTATGAGT
          TACTTGCCACATACGGAACGGTCATCCACACGGAAAATAGAACGCTTTCCTTCTATGAAT
          CGTCAGCCATATACTGCATGTTCATCCCCAGGGAAATCAGAGAGCTCTTCGTCTATGTTA
          TTTTTGCTTCACGGCCTGCGATCTTCACCTCGGAGGATGGAATGTTTGTTCTCGCTAAGT
          AATTTGATCCACATCCCATAGCCATCGCCACACGGCATGGACTATATCTTATCCATAACG
          CACATGTTGTACACTAAGGACTTATCCACTCGGGGTGTGCCTTGCCCTCCGTACGTTAGA
          AATGCTATTGACAGTACATATTTCCTTTTACGAAGTGTGGACCAAACTATGGCTGAATAC
          AATTAACCACACAATTTACAATCCCTTTGACAGTTTTTGAATTCTCTATGATGTCCGGAA

          TGGTGGTCAATACTAATCATAGCAGGAAATCGCTCCCTACTAACTGCCCGGTTCCCGTTC
          TGGTGGTCAATACTAGTCACAGCAGGAAATCGCGCCCTATTAACTTCCCGGGTCCCGTCC
          CACTAAGGCGTATTAGGCTTTGTATGCGATCGCGTTCTGATAATACCCTGGCATGCGTCC
          CAATAGGGAATGCTAGTCGTTGCAAATGTTATACTGTAACTGTGTTTCCAATTTTTGTCT
          CGGTAGGAACCGCTAGTAGCGGTGAGCGATATAACGCTGTGGTCTCTCGGACTATCACGT
          TAGTAACATTCGTTAGTTATAGTTAATGTTAATTTGGTTCCACTCTGCAGACCATCACAA
          TAATAACGTATAACTGTGGTGACCCGAGGCGTGCTGGTAAAACGCTCCCGAACAACGTCT
          AGTGGAGGTAGATCAATAACAGGTTGTCACGCAAAATGGTCGTCTGCACATGTCATTCCT

          CCGTTACGTCTCCCGCGAGAATGAGGACGTACACTATTCACCCCATCCACGACGTCGGGC
          CCGTTACGTTTCCCGCGAGGATAAGGACCCACACTATTCACCCTACCGATGGCGCCGGGC
          CTATCACGTTTCCCGGGAGGATCGAGACATACCCTATTCGCGCTACGCACGACGCCGGTT
          CTAGCGAGCTCTTCGGGCGGCCCAAGACGTGGAACATTTGTCTTATGCGGAGTGTCCGAG
          TGATAGTGCACCTCAAGCGGTAATGGCGGGGGCTTTCGGGTCGTGTGCGCAGTGTCCATT
          CCTTGAAGCGCATCCAAGACGCTTAGACGCCGCCAAGTCAGCCCCTGAATGATCCTTGAC
          CGGTAGTTCACACCAAAAGGCTTAAGACCCAGATTCAGGATTTCACGTGAAAAGCGTGAT
          AGCGTCAATCGTCCGGTCGGCACTCGGAGGGTTGGACGTAGGATTACCGTAGCGCTCGAA

          TCTGTATCTCTGACCGGCCGGCCAGGAACGTACGTGGATATACAGCCGTAAAGCATACCA
          TCTGTATCTTTGACTGGCCGGCCAAGAACGAACGGAGATATACAGCCGTAAAAAATACAA
          CCTGTACCTCTGACAGGCCAACCAGGACTGAACGGAGGGCTTCATGCGTATAGAAATCTA
          ACTATGCACATGCTTAGTAGTCCCTAGCTTAAAACGACAGCACCTCCGTTCAAGGAGATA
          CTTGCGCGGTCGGGTGTTTGACTTGAATGGCAACGTGCGCCAATTTCGGCCAAAGGCATA
          GCCCCAAAGGCAGTCGTCCGGATAGCTTACTAAGGGGTGCGAGCAGCAACAGACACTCTG
          GGTGGGCGGACGCTTGACTACGTCAGTTTGAACGAACCATCGTCAGCGCATAGTATACAA
          AGTTCTTGCCAGGTTCCCCGCACCTTTTTGCAAGGACCGTAGTGCCTCGCCCTCCAGTTA

          AAAAGTAAGTAACGGGTGTTCCGGATGCCAGGTCCTGATCGGTTTCTGCATTTTACCCAG
          ACTAGTAAGAAACGGCTGTTACGGATGCCAGGGCCTAATCGGTTTCTGAATCCTACCCTA
          AATAATAGACAAAGGCCGTTATGGATGCAACTTCCTGATCGGTTACCTTAACATGTCCAG
          GTCCGCGGACGACGGCTGCTTATCATATAGAGTCTCGACCGGCTACCATGTCCAATTGCG
          CATCGTAGGCGTAGGTTGTCGGAGGTAGCAGGTCTCCTACGGTGCCCACATCTAGTTGTC
          AATCACGCGCAGAGTGTATTATAACCACGGCGTATCAGTCTCAAATTCCATTCAGCTACA
          AGCTATGCACCCCTTGCTTCGCAGAGAGGGCGCCCCTGCCAGAGACTGCATCGGCTACTG
          CACCAAGCTCTGAGCGGGAAGCTGATATTGTGTCCATTTCGGCGTTCATGCTCAACCGCA

          GCTTTCTCTCGAAACGTAGCCGGATGCACTTTCGTCGTTCGATACTTTAGGGATCAGGTC
          GCTCTCTGTCGAAGCGCAGTAGGATGCGCCTTTGTCGCTCGACACTCTAGGGATCAGATC
          GTCTCATGTCGGAGTGTGGAAAGAACCGCTTTGATTTCTCACTGTTCAGAAGCATAGGTT
          TCGTCCTGACATGGTGGGGCCGAATACTTATCAATCCTCGAATGCGCCGAGGGGCTGGCT
          GCCCCTCGACTACGCGTCAATCCAAGCTCCTTCTAGCTTGATTCCTCTGAATAATTGACC
          GTCTCGCGTTGAAGCATTTTTGTATGCATTCTCACACAACAGTCGTCAGACGTGCGAAAC
          CTATAGCGCCGCAGGGTAGAGCGCTGATATCACGTTCCCTAAATTCATAAGTAACTGACT
          ATCGATAGCAGAAGCTTCAACTAGAGACATTGGGGCACCTTGACGTACACTCCGCGCTTG

          GCATTCCTGAGTGGGACGAGAATTGTTCGTAAGCACTGTACTGAGCGGCAGAGTAACGAA
          GCATTCTTGAGTGATACGAGAATTGTTTGTAAGTACTGTACTGAGCGACAGGGTAATAAA
          GCACTCATGAGTGGCAGGAGAATAGCATGTGCGTACCGTACAGAGCGGCAGTTATCCAGC
          GCCCACTGAGGTGATTAGGAAGATACGAGAACTTATCGCGTCATGAGGCTGCGCCTCGAT
          ACCCCACGACAAGATTGGCAAGGCCCGCGGGTGTATTGCTGTCAGGAGTTACGCCCCCAT
          TCCCCATAGAGTTGCTAGGGTGCTGAGAAGGTGCACCACCCTGGGTAGTTTTACGCCAAC
          CTTCTACGGACCCACCTGCGGATTACGCGAATATTATGCACTAAGTGATTGCGTTTTCCG
          CATCGAGAAAGCTAATAACGAAAAGTCATGTGGATGGAGAAAGAAGCATCGCTCGCTGCA

          TCACCGCCGTGGGGCGGGTAAGATGGAATACCCGAGGCCAGATTAATACCGTACACAAAC
          TAACCGCTATGGGGCGGGGAAGACGGAATACCCGAGGCCAGTTTGATACCGTCCACATAC
          TCACAGCCATCGTGCGGGAGAGGCGGGGAACTCGGGGCTAACTTAAAATAGTCCACACAC
          ACACCGTCGCCAGGCAAAGGAAATAGAGGACCATGATCCGGACAACTGCCATTCACGTGG
          GCACTCCCGTCAAGGAGAGACAATTGAGGTCAAGGAATCAGGTAAATGCTATATATTAAT
          TCATTGACGCCAAGAAGGTGGCACCAAAGTCGCGAGATTCGGTGGATCGCTTACCAGGTC
          CTATTATAGTCGGAAGGACACAACAGCCGACGGAAGGCTGGGCCGCTCCCTCAAGTGGTG
          TCGCTAATGGCCTGGTGGAGAAAGAACGGATTTGGGGTAGTCTAGACCTGTGAAAGGATC

          TTCCTACATTTTTTATATAAGGTATACGACGCGCAGTCATGAGGGTTCCGACGCTAACAG
          TTCCTACAAATTTTATATAAGGAACACGACCCGTGGCCATGAGGGTTCCGGCGCTAATAG
          TTCCGACAATGTTTACTTAAGGTTCACGAGGCGGGACCTTTAGGGCTCCGGGGTTAATAA
          CTCTAAGTGGATTTGTATAGGATATACGCGCTGAGAATTCCAGTACTTCAGTACTGAATT
          ATAAAAGAGGGCCTTCATAGGATTTACGAGGCCTACTATCTAGGGCTTAGACGATAATTA
          GCATAGAATGGCACCTGCCGATCCACCAAGCAGCAATGTTTTGAATAAAGTCTAGAATCC
          GCAGTAGAGACGCCATGCAGTATCCCCGCTGCGTATTGTCATGCTTTTGATAAAAGATCA
          AAAGTCGGTGCTTTACACGATCTCAGGGTTGCCCACCATGGAAGTGTGGGCGGATTATCA

          TGGTTTCACAACGAAGGGTCTTGTTCGGCCGCGCCGTTAACACCGGCTGACCGGCCTCAT
          TAGTCTCACACCGAAGAGTCTTGATCGGCCACGTCGATAACACCGGCTGACCGGCCCTAC
          CAGCCCAACATCGATGAGTCTTCATCGCCCGTGCTGTCATCACTGGGTGATCAGTTTTAC
          TGCTTCGCGGGCCATCAAGCCTGACCACCTACGCATTAGCTTTCACTCAACAGACTAATC
          TGGGTCGAAATTGTATCCTTCTATCTCTCTATGTTTTCCACGCAGACTCATTAGTCTTAC
          TAGGTTGGAGTTGGTTGGTTTTGACTGTCTATCGGCCCACCCTCCACCCTCTGGCAGAAC
          TAGCTTGGAGCCGGGTATTCTCAACAGGAGATACAGTCTTCCGGTACCCCCTGGAATCAT
          GGGCCAACAGCAATCTAGCACGACCTCCACATACATTCCCATACGCATCACAAGATCCAC

          TCTGTAGCCCAATGGGATGCCTGCTCAGTGCAAGAGGAAG
          TCTACAGCCTAATGCGGTGCCTGCTCGGTGCAAGAGGAAG
          TTTATCACCTAATGCACCGTCTGCTCCGATCTGGTTAACG
          CCTGCCGGCTAGTACAACACACGCTCCGTGAAACCGGATT
          GGTGCTATCAAGGTTACCGACTGTCTGGCGGAAGCAGTAT
          TCTGCCGTTCGGCGTATTGAAACTTGAATGGACGTGAAAC
          TTCGCCAGCCCCCGCACTGAATGATCTAGCGATGCAGAGC
          GCAGTAATCCGGCGCATGGAACGTCTAAACGGTACAACAG

