 8 1000
t1        CTGATCAAAGCGAATCCGAAGGACACGTGGGTCATATAGTGAACGCGGTGAGCATTACCT
t2        TTGATCAAAGCGAATCTGAAGAACACGTGGGTCATATAGTGAACGCGGTGAGCATTACCT
t3        TTAACCAACGAGAATCTGAAGGCTATATGGGCCATATAGCGAACGCGGTGAGCATTACCT
t4        ACTCATTCCGAACGATCGGGATATACCCCGGGTACACAGTGTCCGCTGTAAGTACTAATC
t5        CCCCACAATTTGTGGCCTAAGGACAATGCAGGCTTTAAGCGTACAGCACGAGTAATTAAA
t6        TTGGACTTCACATGATTGGGGGCTATCCTCTGGGTGTTACGGGCGAGGGGGCTAACCGCT
t7        GACAGTGTCACCAGACCACTTGTAGTCTGGTAAACTAGGAAGGCGGTGCGGGTGAGAATG
t8        ATCACAAGGATGTGGCTAAGGGAAACGACGGGAGTCTAGCACCTGGCCCGTGTCGAGATA

          ATTCCGCAAGGAGGCATATCACCTTCGAATGTACCCTGCGCACAATGACTTTTCTGTTAT
          ATTCCGCAAGGAGGCATTTCATCCTCGAATGTACCCTGCGCACTATGACTGTTCTGTTAT
          ACTCCACAAGAAGGTATCCTACCTACGACTGTACGCCGCGCACTATAACCCTCCCTTTCT
          GGGTTGCAGATTGCGAATGTAACCATAAACATAAATTGAGCCTCGAGGTCTCTGCGCCAA
          CCTTCCTTTATGGACGGCAAGCCCTTTACCGTGACGTCTGCCCCCTAGCCCGCTTACTCA
          GTATTATAGGGGAACTGTACGCCTTCCAGAACAGCACGTGCTTCCCAACATATCCGGTAA
          ATAGGTTGGGTAGATTCATCGGACCACACTGACCTATGGACCACCCTTCATGTGAAGTGT
          GTGACTGACCTAGTGTGCGCTCCTAACAGAGCGCCATATTGTCATCGACATACTATGACG

          ACGGGCGCGCTTCTCACAGGAATATGACCTCTTGACGCCCCAACCCCGCGTCGCCTAGGA
          ACGGGCGCGCTTCTCACAGGAATATTACCTCTTGACGCCCCAACCCCGCGTCGCCTAGGA
          GCGGACGCGTTTTTCACTGGAAAATCACCTCTTAACGCCCCAGACTCACGTCGCCTGGGT
          TTAGGAGCCTGCCCTATTAGCCGTAACTACTTAGACGCCAGATCCCCCTTCGACACAAGA
          AAGGGGTGGCAAGGAAGCCGGGATGTGTTCCAGCGAGTCCGTCGCCCCGTTTGCCTGCGC
          GCACAGACCAAAATGACGGAAGACTAGGGCTTTGATACATGCTCGCCTCTACGCACAACT
          GTGAAGGCGAATCCGATAGGTCGGTACCGTTGTGACATAACACTAACAGCTCGTATCTGA
          GACTACGCAACCTTGAGCAGGAATCGGCGGTTCTCCTTCTTGTAGCCTTTGTTCCTCTGT

          TGGGCATTGTTTTACAGTTAGGAGCAATTTGCTCAGCACACTAAATGTGCTGCCGACTCG
          TCGGCATTGTTTTACAGTTACGAGCAATTTGCTCAGCACACTAAACGAGCTGCCGACTCG
          TTGGTATTGCTTCACAGTTAGGAGTAAGTTACTCGGCATACTAAGCGAGTTGTCAACTTG
          TTGCTGACCCTCGCCAGTAAGGAAAACGGTGGATGGGATTATCAAGTGCCTGCTAAGCGG
          TTGGTTCGTTTTGACTCAAGGATAAACGGCGGTCAGGGTAGTGCACGGTTGATGGGGATG
          CAAAAGCCAGTTGAAAGAGGGAAGAATAACCGTAAGGTTGTTGAAAGGGTAGCTGGGGGA
          CCTATGATTTCTAATGATATGGATTATGATTTAAAGGGGGCAGAACGCCCACAGGGAGTC
          CCTTAGTGCGTTTATGTCGCCAGAACTCAGTGCACAGGACTCAAACGAAAGCCGGAGCGG

          AGCGGGGTATGCCGCCAACTTCGCCTAATCTGGCATCGAACTCGTCTGGTTCTTCGGCTG
          AGCTGGGTATGCCGCCAACTCCGCTTAATCTGGCATCGAACTCGTCTGGTTCTTCGGCTG
          AGTGGGGTATGCTACCAAGCGCGCCTAATCTGGAACCGAGCCCATCTGGTCCTTTGGCTG
          GGCTGTGGAGCCTACGGATCGTTCGCCACCTGGTACTATAGCTAACTAGTCACTTGGACG
          CGAATGGAGCAGGCACCTGCATTCCCTAGTTAGCGCCAGAGTCGTATAACCCCCTTACTG
          ACAGACGAGTACTGCTGCACAAACTTAACTGGGGATTGCAGCAGACCAGCTCGCTGGAGG
          TGGATTAGTAGCCGAAGCAGACTCTCCTCGGTGTGTCGACGCTTTTCGATTTTCTAACGA
          GACCGCTGGTACGACGGATGAATGAAATCCGGGGATCCCTGTCATCGCCCATTCCGATAG

          AGTGTGCTTCTATCACTCCCTCGCGTTAAGAGTTGGCGACACTTACCACCAGGGATTACG
          AGTGTGCCTCTATCACTCCCTCGCGTTAAGAGTTGGCGACACTTACCACCAGGCATTACG
          ACTGTGACTCTATCACCCCCTCCCGCCCAGAGCTGGCGACACTTACCACCAGGCATTACG
          AGTTGGCTTTCATAATCGTTTCATAGTCGGAGTGCGAGAAAGTCATCGAAAGTCGCCGTG
          CGTAAGCGTGAAAGGCGGCATATTAGCTGGCGCCGGAAGCAGTCATCCAGGCCACCCCCG
          GGAGAACTACTGAGATTTCTCGCTAACTAGAACGCGGGACGGCTATATTGGCTCGCCCCC
          GATCTGTCGCTACGGCGTATTTTATGTTAGGCACATGGAGGGTCCTTTCGGCAGCCCGCA
          GTCGTACCTTCATGGACTCTCTCTGCATTGGATCTGAAGCGTTCGTACTATCACGTCCTA

          CGCCATCTATTTCTAGAATGGCAGATACCTTCGAAGGGAAAGGCTTCAGCACGGTCGTTT
          CATCATCTTTTTCTGGAATGGCAGATACCTTTGAAGGGAAAGGCTTCAGCACGGTCGCTT
          CAAGATCCTTCTATGGACTGGCTCACACCTTTGAAGGGTAAGGCTTTAATACGGTCGTTT
          CACCACTTCGTCGTCTGGAGGATCGCATATCACGAGGCTAAAGCAACATCCATGAGGTTG
          TATTAAGCCGATATTCTACCGATGGAAGGATGGAGAGGCAAGATAGTGAACAGCGAATGG
          CGATATTTTCCGGTTCAGCATCCCGTGAGTCCAGGCGGCGTGCATTTAATCTCTCGGAGA
          CGTTTCAATGACCTCCGGTAGAGTGCCGGGAGTTCGGCTACCGGCATCGGTCTTAGACCA
          CCTCAAGACGGCGGTAAAGGACACTCACGGCTGGATAGCAAGGGAGCCAGCAATAGAAAC

          TGAATGGGCACCCACCCCGGCACACTGCGCTCTACCCTAAGAACTTTGGCGGCCTAATGC
          TGAATGAGCACCCACCCCGACATCCTGCGCTCTACCCCAAGAACTCTGGCGGCCTAATAC
          TGAATGGGCACCTACCCCGACATACTGCCCGCTATTCCAGGAACCCTGGCGTCCTAGTGC
          CAAGTACTCACGTAACCTACTAAGCTGCCTGGTACCCCAGGCCTTGAGATGGTCTCGGAT
          ACCCAAGGCACCTATACAGCCAGACAGTCTGACCTCGTAGGTCTCTTAGGGGCCCGAAGC
          AATTCTAATGTCGCTCAAGGAAGTCACGACATCCTCCCAACATCTTGAGAAGCTCTATGT
          CTACCCAGGGTCCCGTCGTGCCCATTGTGTTGCGTCCGAACGACCAAGGAACTCTAGGAT
          TGACGTGGTACGCCTTCTGACCCAAGGTTGCAAGCCCTTTAAAGTGGTCGGTCTACACGC

          GCCTCAGTCAGAGGGATTTCCCTGGACAGGTCCATCGATCGCGGTCTGGAGACGCAAGAT
          ACCTCAGTCAGAGGGATTTCCCTGGACAGGTCCATCGATCGGAGTCTGGAGACGCAAGAT
          ATCTCAGTAAGGGGGAACTCCCTGGACAGGTTCATCAACCGCGGTCTAGAGACGCGAGGT
          CCTTCCGTAAAGGGATAGCTCCTGGAAAGGAGCGTTCTTCAAGGATCAGTGACGGAAGAT
          TTATTTGTGCCCTGGAACCGGCTGGTCTATCCCGGCGTCAGTCACGGACTGACGAAGGTT
          AATGACATAAAAGGAATCTCCCTGCAGGGGGGGATGGGTTTTGGACAATCGATATAAGGC
          CGGTAGACCACCATCAGTTACCTCAACGACCGGATTTGCTATAGAAAATGGGTGTAGGAC
          AGACAACCTGATAGCTACTATTGGGCGGAGTATCCTTTCCATTGCTTATCACGACGGTAC

          TCCTCCTAGGTAATAGCGACCTATCTGCGAGACCAGAACGACCAGTCAATTTTCCGCGGT
          TCATAATAGGTAATAGCGAACTATCCGCGAGACCAGAACGACCAGTCAATTTTCCGCGGT
          TTATCATAGGTAACAGCGACCTATACGCCAGACCAGATCGGCCAGTCAATGTTCAGCCTT
          CCAATGACGAAACAAGGGACCTGTTCGCCGGGTCGGATGATTCGCCTGGCGTCTCGCGGC
          TTAATTAGCGATCTGCTAGTCGGCCCGACCGATGGGTGGGCCCCTGCGCTCTTTTATTGC
          TTCAAAGTGGTCCAAGCAGACCACACGAAGGGCGATAGCCTTCATATGACGGTTTTAGGC
          CCACCGGTAACTCTGACGATCGAAATGTGACCCTAGGACCCCTACCTAACACCCCGGGGT
          TCAACGAAAGCACCTTAGCCACCAGCAGTGGATGGGATACTGTAATTTGTCTTACAGAAC

          TATACTAGCCGGATTGCTATTGTGGACCGAGAAGGTAAGAATCCGGTGAAGACAGGTGCT
          TATAATAGCCGGATTGCTAATGTGGACCGAGAAGGTAAGAATTCGGTGAAGACAGGCGCT
          TATTATGGCCGGATCGACATTGCAGCCCGAGAAGGAAAGAACCCCGTGAAGACAGGTGCT
          TATATTGACCAAAGTATCCTTGTGGTCAAAAATGAATAAAATCTTGTCAGGCGAGATGTG
          CCTATTGGCCACGCTGTGATTGTGGCGCAAGATTGGTGGATAACGTGCACATCAGTCGCA
          GATGCTTTCTGCCTTTAAATTTATCCTTACAGCGGATATGTACCAGTCGGATGACACGTG
          CCTTCTCGCCCACAAACCGTGTAGACACAATGCGGAAGAATGTCGCACAAGCAGATACCC
          TACGTCGACCTATCGGTCAACCCGATTCGCGTACAGTTGACCCTGCGGGGCCTCACGGCA

          GGATTACGTGATGTATTGCGACGCTGTGCTACCGTTTGCGGGGAGCATTCATATCTGCGA
          GGATTACGTGATGTATTGCGACGCTGTGCTACCGTTTGCGGGGAGCATTCATATCTGCGA
          GGATCGCCTGATGGATTTCAACGGTGTGCCACCGTTTACGGGGAGCATCCATTTCTGCGA
          ACCCTGTTTGTAGTACCGTAGTTCTTCGTAATCGTTAGGGGGGTCCCCCCCTAACAGCAC
          GATCTCCGGTTTCTATTCGGATCGTCTACTCTTGTCCTACGGGCACTTTTATGGTAGTGA
          ACTCGTCAGGGTTCACTGAAACGCTACGTTGATGGTAAAATGCGACCAAATTTCTAGAGT
          CATCTCTACGAGCTGTTGCAGGTCCGTGAGCCCTAAAATCGGGAGTCTTTATTTGAGTAC
          GAGACTCAGCCTATGCGACAGAAAGTCGCATCTATTAGCGGAAAGTCTCTGATAGAGTGC

          CCCCCTCCGTATTTCCCCCTATAGGCGTATTAGTACAAAGTATGTTAGCGCCGTTTTGAG
          CCCCTTCCGTATTTCCCCCTATAGGCGTATTAGTACAAAGCATGTTAGTGCCGTTCTGAG
          CCCCCCCCATATCTTCCCCAGTAGGCGTACTGGTATAAAACATATAAGTGACCTTATGTG
          CTCTTCGCGCCTTGCCCTATGTGGGAGCCCTTGTCCAGTCGAAGCCAATGCCATGGAGTA
          CTATCTCCATCGATCTTTTTGCATGACTCTATAGGGGAAATGGGCTAATTTCGCCTGGTG
          CTTTACGTCTTTCTGCTCTGATGAGGTTCCTAATATCAACCAAGATAGGACCGCGAGAGA
          CCCTCCCCCCCTTTTTTGATTAAGGAGTATTTGCGCAGATTAGAGCAGTTCTGCTAGGTC
          ACTTTGAACTCTGCGTAACAATGAAATCCCATGCTGTGGTAACTATAGGATCCTCCGGGG

          ATCCTTGCACCTACCTGAGTACACGATCCAAAAGAGTATCCCGTGCCAAAACGTTTTATT
          AACCTTGAACCTACCCGAGTACACAGTCCAAAAGAGTATCCTGTGCCAAAACGTATTACT
          AACCCTGTACTTACCTGGGTACACAGACCAAAAGCGTATCCCGAGCCAAAACGTATTATT
          AATTATCCACTTATTAGATTACATTGGTCGACTGGGGACGGCCCGATTACGCGCTCCGCG
          GTTCAGACCTTTCCGTTAGTCCGTCGCCTATGATGGTACAGTATGCCTGAAAATCCCCTA
          AACACCACCCTTAACTGGGTGTACGATAGATAACAATACCGTCCGCCTAAGCCGCTCAAA
          GGCCATGCTCTATGAGGGGGCTGTCGACCCACGTAAAGTGGTTGTACCTCGTTTTTTACG
          CAACCGGGCGTCAGCCCGCATCAGGACTAGCGTCGAGCCCCAGGGACAAGATGCCCCTCA

          CGGGGCACTGCATTGAATTCCTACGAGCCACCCTTTCAAGTGTGATCAGCATTTTCCCCG
          CGGGGCGCTTCATTGAAGTCCTACGAGCCACCCTTTCAAGTGTGATCAGCACTTTCCCCG
          CGGGGCGCCCCCCCCAAGTCTTACGAGCTACCCCTCCTAGTATGATCAGCATTTTCTCTG
          CGGGGCATTTTACATCAGACACCAGACCCAGTCGTACACATGCGGCCAAGGATTTTCCAG
          TGAGGAGCGGCATTATAAAGCTCCAGGCCATACATACCATTCTGGACGAGGTCCGTGATA
          GGGTGACTATGGCACTAGTTCTCTGCTGTTACCAGCCTAATCTCGCCGGGGACTGTCGAG
          ACGGGAGCGATTTGCCTGACGTCAGTACATCTCTGATTGATCAAGTTAGGCGTCAACACA
          AGGAGCAAGCCATGGGTGGGTTCCGTCCAATTTAGATACCCCGAGTCGGGTAGCACTGTA

          TTGCTAATGGTTCTAAAGTTAGATAAGTGAGGCTTTGCGATCTATAAGGGGTGCATGACA
          TTGCTAATGGTTCTAAAGTTAGATAAGTGAGGCTTTGCGGTCTATAAGGGGTGCATGACA
          CTGCTAATGGTTCTAAAGTTGGATGAGTGAGGTTTTGCGATCTATAAGGGGTGCATGACA
          ATTCTAGCTATGCCGACGCCCAATAAGAGCGGGTCCGTGTTTTACAGGTGGAACTCGGCA
          TTTGTCACTACCGGGCATGCGGGCAGGAGTTTCAGAATGTTTTCCGTACGGCGACAGACA
          TCCGTCGTTGCGTCCACACTGCAGGGGAAAGGCGCTGATCTGTCTTATGGTCAAAGCATA
          GTACAGATGTTGCCCAAGCTAAGCCCAAGGAGCCTGTTGACCCTTATATGACGGTGAACC
          CGGATAATCGCCCTCGAAAAGGGTAAGTGAGGTCACATAATTCGGGTTAAGCCCGAACCT

          CCAGGTGGACTGCGGATTTTCCGAAGAGGACAAACCCGGC
          CCAGGTGGACTGCGGATTCTCCGAAGAGGACAAACCCGGC
          CCAGGAGGACTGCGCATTATCCGAAAAAGCCAAACCCGGC
          GAACAATGCCTGCAGAATGCGCGAAGCGGAGGGGTCGAAT
          AGCATTTGCGTTTGAAAATCTAGACGAAATTAATCCTATA
          GTGAACGGTATACAGAACCCCCACTAATTCCGATCCGGCG
          GACAGCTACTTGTTGTGCACTTACGGAGCACCGCCCGGCA
          GGCTACCGCCTGGTGAATGTCTAATATAGACAAGTGTGGA

