 8 1000
t1        GTCTTATGGTATTCAGTAACCTTTATGTGGAACATTCGACCATGTTGGTGTCGATCATCC
t2        GTCTTCTGGTATTCAGTAACCTTTATGTGGAACATTCGCCCATGTTGATGTCCATCATCC
t3        CTTCGCTGGTGCTCAGTAGCCTCCAAACGGAATGTTGGTCCATGATGATGCCGATTGGCA
t4        GGTCGCCGGCAACCAGCAATGTACAAACGGAGCATACGGCCGAGATAAGGTCAATTATTT
t5        CGTTGCCGATCTCCAGCCGTGCTTAGGCGTAGTGGTTTTCCGGGATAATGACATTTAACC
t6        CGTTGCCGATCTCCAGCCGTGCTTGGGCGTAGTGGGTCTCCGGGATAATGTTATTTAACT
t7        CATTGCTTGTGTCCGTGCGATTCACTCCGACGGACCTTGTCTGATGAGTCTTATAACTTT
t8        TTTAACCTGTGACCAGGCGGCTCAGGCTGATGAACGATTTCAAGCGAGTTCCCTATACCA

          GCGGCAGAAGTATTACAAGACGTCCGCGTACAGTGGCTAGATCAGGTAGCGCCCCTGTTT
          GCGGCAATAGTATTACAAGACGCCCGCGTACAGTGGCAAGATCAGGTAGCGCCCCTGTTT
          GTAGCGAAGGTATTTCGCGATGTCCGTGTACAATGGTTGAGCTAGATAGTGTTGCTACTT
          GCAGCTACGGCGTTATTAGACGTAAGCGCTTATTAACCGATCCAAGTAGTAAGCTCAATC
          GAAACATGCGTATCTACAGGTGAACGCGTTCATGATTGTTCTTAGCTTGTCCGCTCAACC
          GAAGCATGCGTCTCTCCAAGTGCACGCGTCCTTGATTGTTCTTAGCTTGCCAGCTCAACG
          TTAATAAGAGTCCAGTAAGGTTTCTGCTGGAGTCAGTAGGACTCTTGGGCAAGCCCCTGG
          ATAATTTGGGTAACACAAAGATATCGCTGGCAGTAGTCACACAGGTAAGTAGGTTCCTGG

          ACCATGTCTAGAGAGGGTGACTTAAAAGCTGCCACCTTTCCTCTGTTCTCAGGGCTTGCT
          ACCATGTCTAGAGAGGGTGACTTAATAGCTGCCACCTTTCCTCTGTTCTCAGGGCTTGCT
          GCCATGCTTGGCGAGAGCGATTTGAAACCTGCCACTTTACCTCAGTGTATAGGGCCTGCG
          ACCATGCACGGAAAAGTCAGATCACGTCTTCATTTCCTTTCTCCCTGTACAGGTCCAATT
          ATATTGGAAGACGGGCAAAGGCTTGAGTACCGCGACCGACTTCTGGTCACATAACTCTAG
          ATACTGGAAGACGGGCAAAGGCTTGAGTACCGCGAGCGACTTCTGGTCACATAACCCTAG
          AATAAGCCCGAACGACTCACAAACTCCTCTAAGAAACCTCCAGAGAGAACCTCGCCCTCT
          TTTAAGACGCCATAACCGACAGATCCTTCGTAACTAGGCTTGTGGGGTACGCACCTTTAG

          AAGTGTTTGTTGAATGGCTTCCGGTTGTGGAAAGCAGATCCTCGGGATGCGTCCCGATCG
          AAGTGTTTGTTGAATGGCTACCGGTTGTGGAAAGCAGATCCCCGGGATGCGTCCCGATCG
          ACGTGCTTATTGAATAGCTCCTGGCCACGGGAAGTAACTCTCCAGGAGCTGCCCCGATAA
          CAGTGGCAATTGGACCACTACCGATGACGGGCAGCAGATGCTTGCACATCTAAAGCTCCA
          TCTACTTTGACTGGCCCTTTTCCGCACGAAGGAGGAAGCGCTAGGTGACTATAATATGTA
          TCTACTTTGACTGGCGCTTTCCCATACAAAGGAGGAAGCGCTAGGTGACTTTAATACGTA
          CCTCGTTTGCGAAACCGGGGTCCATCGTTGTCTTAAAACCATTGGTAGACGGGACATCTG
          CTCCGTTCAGTAAACCGTTGCTAGCAAAGGAATGCCAGTGTGTGAAAATCTGGACCCTCG

          GAATCATGAATTGACCATTCAACTGACGGGCACAGATTGGACCTATGCCAACACGTACCG
          GAATCATGAATTGAACATTCAACTGACGGGCACAGATTGGACCTACGTCAACACGTACCG
          GAATCAACAGCTGACCATATTACTAACGGGCACAGGTTAAACCAACATCAATACAGATCG
          GTACCATTTATATATCGTCCTTCATACGGGCGTAGACCGCATTTACTCTACTATGAACAG
          GCCCTAAATACTGGTTACCCCCCATTTGGGGATGAGTAGCAACCACCGCCCCGCATAATC
          GTCCTATATACTGATCACCCTCCATTTGGGGATGCGCAGCAACCACTGCCACGCATAATA
          GCGCAAAAGCCCGGCTGACTTCGGACCGGTAGCGGGACTCTTCCAAATTTCTCAACGTGG
          GAGCCTAGACCTAATTACCCCGAGAACCGTAACGAAATATCTATACTCCCTAGCGAGCCG

          ACGAACTGCGGAAGTCATAGGTAAGTTCCTTCCTGAAGTGGCTAATGGAAACAACCACTC
          ACGAATTGCGGAACTAATAAGCAAGTTACTTCCTGAAGTGGCTAATGGACACAACCACTT
          ACGCACTGGAGAGCTTATAAGTCAGGTACTCCCTGAGCTAGGCAGCGAAAATAATCGCTT
          GTGGTCAGATGACCCAATAAGTATATCTTCTCGTGAGCTGGCCTACACACACCACCACTT
          AAGTCCCAAAGTGGTGACGGGCATGTCCGGGAACGAGGATATTAACAATCTCCATATTTT
          GTGTCCCAAAATGGTAACAGGCATGTCCGCGAACGAGGATATTAACAAACTCTACGTTTT
          TTGAGTCTACACACGAGTGGATCTTGTATATCTGAACGTCAGCGAATTATGATAATTCTC
          GTCAATTGAAATACAGGCTAGTGGCATTGACATGGAAGTCACCAAAATGCACAATTTTCC

          ATTATCCCGGCGTGCTGACTATGTAGTCGCCAGAAGCGTTCCGTTTTTAAGTATGACTAT
          GTTATCCCGGCGTGCTGACTATGTAGTCGCCAGAAGCGTTCCGTTTTTAAGTATGACTTT
          ACTGTTCCAACGGCCTAATTATACCGTTCCCAAATACGCCAATCGCTGAAGTATGATTCT
          TTAACAATCGCCATCCGTCTACGCCGATATCAAATGCGTGAGATGATTTAGTAAACCCCT
          TCAGCTTTAGGTCTTTCCCCAAATTATGGTTCATGAGGAGAAGAAGACCATCTACGCTAT
          TCCGCTTTAGGCCTTTTTCCAAGTTATGGTTAATGAGGAGAAGAAGACTAGCTACGCTTT
          ATATTCCTACCTCGACAGGGATATACGGTTCGATGGCACGAGGCTGATTTGCGCGTGACC
          TTGGTCTTGGCTCGCAAAAGGCACTACATGCATGTGTGTGATACGAAATCGTAGGGTCCA

          GGGCTCGTCACAAGTCGCATCTGAGGAGCCCGGAGCTGTAAACAATTCCACCCGTAAGCC
          GGGCTCGTCACAAGTCGCATCTGAGGAACCCGGAGCCGTAAACAATTCCACCCATGAGCC
          AGGTGCGTCGCAACTCACATCTGTGGCATTTAGCGCCGTAAGCAATCCCATCCGTGTGTC
          TGTCGAGCTGAATATAACACCGCTGGTCCTTGAAGCCAAAAGCAGCCCTACGTATAAGTC
          CCCCGAGGGCAACGCAGCATTCGCTATGCTAGCTGAGAGAACCGCGGCCTGAGGAACGAC
          CCCCGAGAGCAGCGCAGCATTTGTTATGCTAGCTGAGAGAACCGAGGCCTGTGGAGCGAC
          GTTTGTGACACGGCTAGTCTCAAGTGCTCGCGAGGTTCAAACGTGATCCGTGTGTGGGCT
          ATCCGCGGAATAACTCGTTCTCCGCGATCGTAATGCTAGAGCGTAGTTTACACGCGCGCC

          TATGTCCTGACGAATGTTAGTGTATACTAGCGGTGCTATTGTCCTCGCCTAGTCTCTGAA
          TATGTCCTGACGAATGTTAGTGTATACTAGCGGTGCTATTGTCCTCGCTTAGTCTCTGAA
          TACGTCCTGACGTATATTAGTTTATACCGGCGGTGCTATTCTCCTGACCGAGTTTCTACA
          AACGTTACGTCGATCCTAAGAGTGTATTGCCGGGGCCTCGATCTCCGTGTGACCTTCAGA
          GCTGTTCAGGTAGCCACGGCGGTACAGCGCGGATAGCCCGCCCCTCATCGAATCCCCTGA
          GCTGTTCGAGTAGCCACGGCGTTACAGCGCGTATAGCCTGCCCCTTATCTAATCTCCTGA
          GTGGGGCGAGTGATTGCCGGGCGTCCAACATGAATCTTAAACGGACCACTGGATATGAAG
          CGCGAGCACGAATCTCCCGGTATAATCTGATTGAATTTATGTTGATAAGAGGAGCATGAA

          TCAGATGCCACCTTACATATGTTACAGTGAAATACACCGTAAACACTCCTACGAAGGGCT
          TCAGATGCCGCCTTACATATGTCATAGTGAAATACATCGTAAACACTCCTAGGAAGGGCT
          TCAGACGTTGCCTCACGTACTTAAGACCGAAATAGACTGTACGCTCCCGTATGAAGAGCT
          ATGGGTCAAGGTTGACGCTGCCGAGATTGAGCAGCAACGCATTCCTATTTGGAGGATATC
          ATAACCGGTGGCTTCCAAAGCCTGGAATGTTTTGACACGACGACAATGACGTGCAAGAAC
          GTTACCGGAGGCTTCCAAAGCTTAGAAAGTTTTGACACGACGATAATGACGTGCAAGATC
          GTCTGTGAAGTTTCGCACATCAATGATGGACCCCGGCCCTGCGTAGTCTGGATGACGGCC
          GCAATCGACAACTCGTGAGTAATGATGGGAAACGAGTCGAGCGAGGCTGCCCTGGGCATT

          GCAACTCTTACTACCGTCTGCTTCTTTGGTGAAGGTTCTGTTCGTGACCTAGATACTGGA
          GCAACTCTTACTACCGTCTGCTTTTTTGGTGAAGGATCTATTCGTGACCTAGATACTGGA
          CCGACTTCTTTCGCAGGCCGTTTCTTCCGTGAAGTTCCTATTCACGATCTACTTCCCGGA
          CTAATTCAACGCGCTGTCTGCATTATTGGCCAAGTTTCGGCTAGTGTACACTTTTATGGA
          CGTACCCGCACCGCCCTTTAAGCCATCGATGTGATCTAGATTCGTTCATCTGCGCCTACA
          CGTACTCGCACCGCCCTCTAAGCCATCGATGAGACCTAGATTTGTTCGTCTGCGCCTCCA
          GTGGGTGTTTACTTTTCTTCGATATCCAATAAATTTATCTTCTACACTTCTGTTCGTGGA
          TCCGGACATAACGCACCGTTATTCTTTAGTACGGCTTCTGCTTGTATTCATATGTTCATG

          TCTTGCCGCGATTGTGAGTCACGAGACGAGACACTTACACAGCAATGTATTAGACTCACA
          TTTTGCCGCGATTGTGAGTCACGCGACGAGACACTTACACAGCGATGTTTTAGACTCACA
          TTTTGCTAAGATCGCGAGTAAGGAGACGAGCTAACTAGACTGCGAGGCTACCGATCTACA
          TTCCGTCGATAATGTTAGTCCCCTGCAGCACTGTTTCCTTAGAGAGGTCTAAAACCCGTG
          TAGAGCCTGTACGACAAAAATCTGGTGGCATCATTCCACTCGGCAAGATTAGAACCCACA
          TAGTGCCTGTACGGCAAAAATCTGGTGGCACCATTCCATTCGGCAGGCTTAAAACCCACA
          CGATTCCTATCCTATAACTATTCGGAGGTAACAATTAAAGACGTGTATCTCCAGGCTTTA
          CTCCGTCATGATCCAGACGATATAATATGACCAGTTAAAAATACTATACAGGCACCTGCT

          CCTGAGTCGCATTAGGCAAACGCAATGTTTAATGAGCGTACCTCAGAGTCCGCGCACCCG
          CCTGAGTCGCATTAGGCAAACGCAATGTTTAATGAGTGTACCCCTGAGTCCGCGCACCCG
          TCTGCGTCACATTAGTCGTATTTGAGATTCACTAGGAACGCGTCGGAGCCCACACGTCTG
          ATTGTAGATCGTCAGTTACACCAATGGTCCAGTCAAAGTCAGTCAGCCACCGTCCAATCG
          TCTGCGCGCTGTTAGCCTAGTCCTATGTTTAAATAGCGCTAGGCGTCCATCAGTAACCCG
          TCTGCGCGCTGTTAGCCTAGTCCAACGTTTAATAAGAGCTAGGCGTTCCTCAGTAACCCG
          GACACGGGATATGAATTAAAAAATGTTCTGCCCCGGCATCAAGTAGTCGCTACTGGGTGC
          GCAGCCGGGTACCGACATGGGTAAATCATAACCGAGCGGTATACGAACCTTTCTTAGGTC

          CAGATCTTAGCGTGCCTACATCGCTAAAACCTGGTACCGAATACAACGAATATACTGTTC
          CAGATCTAATCGTGCCTACATCGCTAAAATCTGGTACCGAATACGACGAATATACTGTCC
          TAGAAGGCAGCGTGCCCCCACGGGCAGAACCTGGCGTTGTATGATGCGATTCTATTAACT
          CAGATGGTAGCACATCTCAGTGGTCGGAGCCTCGCTCCGCGCACGCCAATTTACCGTCCA
          TCGCCGTTTATAAACCCTCCTGGGTCTTACTCAGCCTTACCACCGGGGACCTATCAGCAC
          CTGCCGTTTGCAAATCCTCCCGGGTTTTACTCAGCCTCACCATCGGGGACCTATCGGCCC
          GCACTGGCACACAGAGAACGTCAGAGGCACACTGCTCACCAAACTGTGCAGAGGTTCTGC
          TGACTGATATTTGGGAATCGTTAGCCAGACCTAGCCCCGTTAACTGCGAATCGCGCTTGA

          GGTGGATCATCCATCTGAATGGGACACACCCTGCGCCTCGTTTAACTGCAAGAATAGGAT
          GGTGGATCATCCAATCGAATGGGACATATCCTGCGCCTCGTTTAATTGCAAGAATAGGAT
          AGCGGATCAATTACACGAACGGGACAGACTTTGTGCCTCATCTAGTTCTACGAGCACGAT
          ATCGGGTTGGCTGAACGCCCGTGAGATATATCGCACCCACTCTGATCGAAAGACGACGAA
          TGTGAACTCTCCTGCTGTACGTGAGATGTTCCATGTGCATGGGGTTTAGAAGGAGGCACG
          AGTAAACTCTCTTGCTGTACGCGGAATGTTCCATGTGCATGGGGTTTAGAAGGAGGCTCG
          AGTTTGTCGTCTGCGTTCCGCGTTAAAGAATAGCGCGACCCTGAGTCCGGCAGTTGCGGA
          CGCGCAACCACACAACATTCCACAGGAATTGTGTCTCGCCCTGGGTTGGACGGTCACGGA

          TCCTCAACCATCAGGCATTGAAAACTATATAAGTAATCCGCCATGACGCCCGGCCTGACC
          TCCTCAACCATCAGGCATTGAAAGCTATATAAGTAATCCGCCATGACGCCCGGCCTGACC
          CTCTTCAACATCCGGCAAAGAAGGCTTCTTAGGTTGCCTGCGATGACCCCCTGTTCGACA
          CTTGCAGTTCTAGGGGAGCAAAAGCCAACTAGGTAACACTGCGTGACATCCAGTTTGACC
          GTGTCAGTAGTTAGGGAACTATTGCTGGCTGAACGTCAACTCCAGATACCTGTTTCTAAC
          GTGTCAGTAGTCAGGAAAATATTGCCGGCTGAACTTTATCTCTAGAAATCTGTTTCTAAC
          AATTCAGTCTTACAATCACGGAGCTCTTTCCTATCGTTATTAAACGTCCACCGCATAAAA
          ATTTTCTGGCAAAGACCATTGACGCACCGACATCTTCCCCCATAATCTCCCGATGCGACA

          AGGCTCTTAGCTTGCCTCAACCCGCAACTCATTGCGATTA
          AGGCTCTTAGCTTGCCTCAACCCGCAACTCATTGCGATTG
          TGGACCCCGGCCTGCTACCATCAACGGCACGTTGTAAGAG
          AAAATCTTGCCCCGCGTTCATCAACGGTGCAATGCCTTTG
          CGGATTCTATTTTGTGTAAGCCAAGGATTTAGGGCAAATG
          CGGATTCTATTTTGTGTAAGCCACGGAGTTAGGGCAAATG
          CGGTTTTCGCTGAAAGTTCGGGATCAAGCGGCATCGCTGA
          CAATCCAAGCAGGAAGCATAGGCTAGCTTCAGCATTCGGG

