 8 1000
t1        CTGCACCCTACCGGGACGCAAGAGGTAGCGAAATGCATCAGGGAACGTGCCTTTGAGCTA
t2        GCGCAACGTTCTGGCAAACTAGATGTGGGGAAATGCAACCGCGAGAACGGGATTGCACCA
t3        GCGCACCCTATCGGGATATCAGAAGTCGAGACAAACAATATAGAACACACCTTTGAATCG
t4        GTGCGGTCCGCTTGAGTCCTAAAGGTAATGGCAGGGAACAGAGAGAGCAGGTATGCGTAA
t5        TTGTAGCCCACCGATCTCATTAGGACCATGGGATACGATTGAGGATTCGTTAACGAAACA
t6        TCGTGCCCCCATAATATGTTATGTGCGGCGGTGCCCCACAAGGGATCCGTACACACTTGC
t7        TTGATACCCTCCTTCACCCGCGAACCAATGGCGACCACTGACAGATGGATTTGGTCGTAG
t8        GTCCGGAGTCTCGAAATGTCTCATCTGCTAACACAATTGAACAAAGTGGTCTGGCTGGCA

          AAGAGGCTGTACGAACAGTTCGGACAGAGTCTAACGTGCACTTCCGAATTATCCATAAAG
          CGAAGGCTGGTCGCTTTATCTGAACAAAATTTGAGGTCCATCCTCAGGTTTTAGCTTGAG
          CAAAGGTTGCTCGATTCGTTTGAACGGAACCTAACGTGAACTTTCAGACCTTACGTCGAC
          CTGGCGTTGTTCGAATCATCAGAACAGGATCTGCTGTGTACCCTCTGACAGAGCAAAGAG
          CCGTGGCAGCACCTACGTTCCGAACGGATTTTGATTCACCTACTCTAACCTCACATTGAC
          AAATCATCACCTGATTGCACGAAGATGAATGCCAGATAAGGCGACGATCTCAACATTGTA
          CGACGCCTGTGCATCTACCGGGTTCACCGTCTACTCTAAGTCGACACACCCCGAATATCA
          CTACACAAAGCCAAACGCTGAAACCTCAGGTTCCTGTAAGATGGAGTGCATAGTGACGGG

          TTTTCTCGGTATCCATCCTATAAGACATGGGCGCGGTTCAGGCGGACACACAACATAGTC
          TTTTCTCGTTCTCTATGCTCTAGTCGATGGGTGTTGATTAGGTTAATATGCAATAAAATC
          TTTTCTTGTTATCTACGCTTCAGGCTAACGGTGCTGTCTAGCTGAGCACACAACATAGTC
          CTTTCTTGTTGCCTCCGCTCTAGGCCCGGTGTACCTCCTAGATGGATTAATGATGTCGTC
          CTTTTTTATTGTCAACGCTCTATACGACGTGTGCTGCTTCGATGGGCGGAGAATGTGACT
          GCGCCTTGTTACCAGTGGCTTCGGTTCAATGCGATGCGGCGCCGGAGACCCGGTGCGGCA
          TCATTTAGCATCCACCGAGCGGAATACTGGGAACCGACCAATAATATAAGGAACATGACA
          CCGATTTAGGCCAGTTGCTACAGAATTTGCACGGTGTTTGGTGGCACACGTGGCAATAGA

          ACTTCCTTCGAAACCTGCCTCGCTATCTCTCACGCGTTTGCTGCAGTGTGAGCCGAAACT
          CTTCCACATGAAGCCTGTCACGCTCCTACTTACGCATTAGCTGCCGCCCGCGCAGAAATA
          ACTTTACTCGAGACTTACCTGGCTTCCACTTAAGCAGTAACTGCCGTGTGAGTGGGAGTT
          GTCTCATACGGCTCATCAGTTGCTCTCACTCACGCGCCAGTCTTCGTTTAAGTTTCCGTA
          TTACCACTTCGGTATCCCACTACGCTTATTCAAGTATGCGGCATCATCTGAGTGGCAATA
          ATAGTACAGAGATTTGCCCGTGACCCCTGTCGTGTGGGCGTCTACATTTAGAGAATGTGT
          GTACCGTTCTCATTTTACTAATCTTCGGTGAGTTAACTCTTCAATGAAGGAGGAGACTGC
          TTTCTGCTCGGTCCCCGCTTTAGTCTTAGTTAAGTCCCGGCCTATTCTTCGAGCCTGCAT

          ATTAAGAGACGGTCTGGCACGTGAGAGGGTTAACTCTGTCAGGATCTGTTAATAATAATA
          ATTGAGAAATAGCCTAACATGACGAAGGATTACCATTTCCGGGACTTGCTATGAGTAATT
          ATTATGAGAAGGTCCATTGCGAAAGAGGGCCACCTTCTTCAGGACCTACTAATATTAGTA
          GTTAAGCTATGGAGTTACTCACAAAAGTGTTACCTTCGTTAGTAGTGGCTAACCGTAACA
          ATAAAGAAATCGCCTAACTCTCGCTTAGCGTAGCTATTCCAGGACCGGTCAATAATGTCC
          ATAGAGCGACGGCAACAATTTGTTGCGGGTTGATTCACCACGGACTAGTCGGACACGCGC
          TCAGTAGTCGTCTGCCACGTCGTCCGGGGGCTAACTCGTCCTAGGGAAGGCCTGATGTTT
          ATTCGAGTGTTGACATTCTTTGTAGAGGATTCTGTCTACCTGACGTCGCCGTGAACTCAG

          AGCTTTCCATACACCATATTAAAAGTCGTACCATTGTTCTATCTTCAACAGTAATCGCTT
          GTCTTTCCTTACAACACACTCAACCTCATGCAATTATCCTATGATTAGCAGCCAATAATT
          AACGTCCCATACACCACATTGGATGTCCTACCACATTCCTATAATAAACAGTCGTCACCT
          GGAGTTCACCACACTGCGATAGGGCTAAGACTCTTACCGTATAATTCCTCGTTACCGCCT
          AGTGTTATTCGTACCACGGTAATAACGGAATCGCCACCCTATGATCTACAACTAATACCT
          CTTGTGTCCGCAATAAGGCTGGACTACACCCTCCTGACTCGTGCAGCTTTAAAATCGTTC
          AACAACGTACGCACAACGTCTCAGGCAGGACATAAGTTCTAGACAGAAATTTCGTAGGCC
          TGCAAACTATTCGCGTAAGAGGCACTTTGCCAGCCTTCACTTGATACATCGTTGTCCTCC

          ATTTGGCTGTCCCTGTAGCAACTTTCCTCTGAGACCATGGGCACGGCAATCACACAAGTC
          GATTTGTTGCCTCTGTAGCACCCTTGCCGTGAAACAAGGAGTTCGGTAAATACACGGGTC
          GTTTCGCCGTCCTTATAGTAAATTCATCTTGAGACCACGAATATACAAGATACACCAGCC
          GTCCACAGGGTCGTGTAGCGCAATCATTCTGTGACAAAGAGTAAGATAGTCGTAACCGCA
          ATTTTCATGCACATGTGGCCTGATCGTCCTCTGGCGAAGGTCATCGTAGGTACGCCTGCC
          AAGGATCCCGTCCTAACTAGGCTTCCGTCCCTAATGACATGCTTAGCTGGTCGAGGCGGT
          TCACACGTGGCGCATAACCCCCGGCATTCTGCGATGATACGCGAGCTGGAGGGACCCGTG
          ATCCTCCCAGACTCACGTCGACTGGAATCTTTGCCGGCCAGTGCAAAGCTGTTACCTGGT

          TCAGGATATTTTAGTCACACCCGGAAGGGATCATGCTGACCGGCTGCGAGACTAGTGTTA
          TCAGAGTCTCTTAATTATGTTAGGGCGGGACCACGCTGACCGGCAGTATGGCAGGTGTTA
          TCGAGATGACTTGGCTACACTTAGGCGGGAGTGCACTGATCTGTAGGGTGACCGGTGCGG
          TTTTAGTAGTCAAGGGGTGCCCTGCCGGGTGTACGCAAATTTGCAACGCAGCAAGTATTG
          TCACGGAATTCCTCTGGTGTCCCCCCGGTGGATCGCCGGTCGGCAGCGAGGCTGGCGGTG
          ATAAGTTGTCCTGAGAGCTCAACTTCTCGTGTGGGCCGGGTGGCCTGGTGATATATTTCG
          CCAGAGCCTTGAAAGTAAACCCTCCTGCGCGCCTGAAAGTTTATCACATGCCTTCCAATG
          CCTTCGGGTCAAGGTTCTCTCATTACGGGATATTGCTAAGCGAGAGTGGCGTGCTTAAGG

          GCCAAGGCAGTACTCTGTGATGTGATCTACCAGCAATAAAACACTAATACGGATACACAT
          GTGGGCGCAGAACTTTGCGATGTATAGGCCCAGCTTTTATTCAGCAATGTGGATGCAAGT
          GCCACCGTAAGGCCCCATGATGTGTTCGCTTAGCAGTTGCACAGCAACTTGGATGTCAAT
          GTCAAGGAAGGGGTTTCCGATATGATAGTTTAGCAATTGCAGAGTAACGTGAGTGGAAAT
          TTGCAGGCATACTTCTCCGTTATGGAAATACAGCGGTCATATGGCCACGTGGACGTAAAT
          TTGAGATGGACTACTCCCAACCAAGTAGCATTGCTGACGTACCTCTAAGACGGTAGAAAG
          TGGTGGGGGAGTAATCCCCACATGACGGCCCAGTCCCTGCTTACTAACGATAGCACACCC
          TTCTGAACGGGCTCTGCTGCCGTAACTGAACTGTGACTCACGGGTCCTAACGATGCTGGC

          TATTTTAGCCTATCTTCGGCCTGAATTCTAGTGCGGGTAAATCTTCGCCTGCTTCATGGC
          TATTTAAGCCTATCTTCGGCTACAATCGATGTGCGGGCATCGGTCCGTCTACCCAACCCC
          TATTCTAGCCCATCCCCGGGAACAATCCTCGTGTGGGTCTGTTTTCTAGCGCCCCATTTG
          TACTTTTGCCTGTCTCCGGTTGCTATATCGCTGTAATTCTGTCCTCGACCATTTTACCCC
          TACGGTGGTTGACGTTCGGCCTCTCTTTGGGTGCGACTATCCTCTAGGTCAATTGGGACC
          CGCACCGCTCATAACCAATTTGCCTTCCAGGCACGGATATGTCTCTAATAGCCTCATATC
          GATACCAGTCCGTACCAGCCCACTCTTAAAGCGCGGACTCAGTCTGCATAGCTCTATAAA
          CGCGTTTTTTAGAGGATGCCAGAGAAGTTAGTATGTAGGTCTATTGAAAATCCCAATGGT

          GCCGTCACTGACAAGTGCCGCTGATAGTGCACCAGCATACCCTGAGGATGACGGCGTCCT
          ACCGTCAGCTGAAGGTGCTGTCGATTGCGGACCTATATGGCCCGGAGACCATCGCTAATC
          GCCGACAACGGCAGGACCCGCTAAAGGTGGACTTGAATGGATGGAAGACGACGGCAAACC
          GTTGCCGACGGGTAGCGTTGCCGACGGTGAAATTGTATGCCCCGACCACGCCGGCTTGCT
          TTTGTCACCAGGTAATGTTGCCTAGGGCGAGCCAGAACGGGTCGTAGACCGCGACCCACC
          GGTCATACCAGCCCCGGCCGTTGATAACTGATATAACCGAGTCGAAAGCTACGGCGTGCG
          GTTACAACAGCTCGACATAACCGGTACTTAAGATGCTCCGAGTGTGCTCGCCCATGTGAG
          AGTACCCGGGCGTACCGCTGTAAGTGGTTAAAACATTTAGTCCGTGGTTAACAATGTGGT

          CGGATTGGCAGAGTATCTACGTTCACTAACGGAGAACTATTGTGTGATCCAAGTATGTCT
          CGGACTGACAGCGTACATGCGCCGACTATCAGGCAACAACTAAACGTCCCCTGTATACTT
          TGGTTTGGCCGTGCACCTATGTCGACTAACGGATATCTACTGAATGACCTATATATGCTT
          TAGGTTGGCAGTGTATCGACGTCGGCAAGCGCGCACTTACTGGCTGGGCCACGTCCCGAT
          TAAAGTGGCGATGAACTGTTAGGGAATCAGGTTTACGTAGTGATAGCGTCAAGTACGTCA
          AGAACTCACGAGCTATTTGCTACTAGGGACGGCCGATTGCCCGCGAGGGTAGCTACGTCT
          AATACGGAGGCTGGGCACGTGCTGGCCATCCCATGTACACCGGGGCTGACTGCCCTACCG
          CGTCTTCGAGTGATGGCCACATTTGACCTCATGCTTACACCGGCCCAGTCTCTATTGTAG

          GGGAGCCTAGCCTGAGGGCGGAGGTTCGACGATTGACCATAATGGAACGACTGAGCTATT
          GCGATCATCGCCTGCAGGCGGCGGTCCGATGATCAATTATAATAAAACATCTGGGCACCT
          ATGAGCCCCGCCTGAGGGAGGTGGTCCGGTGATGGCTCCTAATAAGCCAACCGAGCACCC
          GTTAGGCAACTATGAAGACGGCGGCTTGGAGACTGATAATATTAGCATATCTAGGCAGCC
          TTGAGACTCGTCTGAAGACCCCGGCTTGAAGAAACCCAAGAATAGCACTTCTGAGCGCCA
          AAGGTTAAAACTGAGAGTGCATGACTTGTGTACATGGCACACTACTCTTAAAGGGTACGG
          ACGGAGTTTGCTTGGAAATGTGGGGTAGTTAGTTTGTATTCTCGACTGTATGGCGTATCG
          ATAGACCAAATAGTTGCAAGTTGCCCCGCAGAATTAGAGGAACGATGCGCACACGTAACA

          GGCATCTTCACCCCCAACTGTAGGTCCCGACCTGCTGATGATCTCAACGCGGGTATGGTT
          AGCCTCTGCACCTACAGTTGCAAGTCCAGTCTCGGTAGTGACTTCGATGCGGGAATGGTT
          GTCTCGCGCGCTCACAACTGCAAGTCCTGTCCTGCTAGCCGATCCGACATGGGAATTGTT
          GGACCCCATGCCGATGATATTGAGCCTCGACCTTCTAACGACGCTAACGTACGACTTGCC
          TTTTTCTGCGCTGAGACTTACAAGTCTCTGTCAACTTGAAAGATCGAAGCTAAAGCAAGC
          TGCAACTGCGCTGCTTATGCAAAGCCCCGTCTTCCTCAACATTGGATACCAACAATCGGC
          GAAACCTGTATAGTTTGGCTTAAGCGACGTAGTTCGCGTTTCGGTAACTGCCAAGCCGCC
          AGCGACTGCATTAAAAACCACCAAAAACTTTCTACCCGCATCAATTATCTCAAAGGCGCC

          ACGATAACCTACGGATCCAGTAGACGAGGTTTAGTAGCGATCGTTAAAGTGTAATTGGGT
          GCGATGACCCTGGGATTCGGTCCATGGCGTTTAGCTGCAGCCGTTAACGTGCGGCCGAAC
          ACGATAATCTGCGAGTTCGGCGAATGAGGTCCAGTAGCGACCGTTCAAGGGCGCATGAAC
          TGGACAGAATCGGGACTCGGTTCATAAGGTCGAATAGCGACCGAGGATATCCGATTGGAG
          AAGAGAGTGCAGGGTTACGTTTCGCGGGAATTAGTGTTGGTTATGGGCGAGTCATACGAC
          TCTCATGTATGACAATCCGATCCCCTGCACAAGTCAGCAATTATGGAAGTGTAGTAGCGG
          TATTCGGGGTAAACACTCCGCATCCTGTTTAAATCAGCGTTGGGGTAGGAATATGAGGTC
          TAGACACGCAAGCCTGCTTAAGATCTTGATATGTTTATGCCCATAACTCTGTCGCTCATG

          AAATAAAACGTGTCGACGATAACCGCCACGAGTTAAGCTCAGTAAAGCCTTGAATGCTCC
          AATACGTATTTGTCGACGGCTAGCGCTATGAGTTAGACTCCGTAAGGCACCGAATGCACT
          TAGCTGATTGGGTCGACGACTAATGCTACGAGTTCAGTTACGTAAGCAACTGAACGTTCC
          AGTATACATCTCTACACGACCACTGGTAGAAGTTAACACACATTAGGAGTCAAAGCTTTT
          GGACTAAACTTTCTGACGATTCTCATGACCAACAAAGTCACGTTGGCAGCTGCTTGTCTT
          TCGTTCAGTCGCCCAGAGAGTAGAAAGGACATTCACACTGTGGGAACGCTGAACCCCTGT
          CTACACTTTTCTCATCGGGGTGAAAAGACACCATGCTCCATTTCAACGCTCGCTGCCTTT
          TTGATGGAATCTTTTTTGTGAGTGACCTTAAGAATTATTGAGCGAGGACAGGCTGGCCTT

          CGTCAGCACTGAAGAGGATTCATCGGCGTCCTCTTCTATC
          CTCCAACACCGAGGAGGATCTAGCGAAGTCTCGTTTTCCA
          CTCCCACACCGAGGGGGATTTCGCGAACTCTTGTTCTCCC
          CGTCGTCACGTAGAAAGATTTAGCGGAATTCCTCCGTCCC
          GAACGTTAGACACAAGGGCCTTGGCAAAACCCATTGCCCA
          TTACACTCTATTTGATGTATTAGTCAAAGGCGGTTCAGAG
          CACGCCTCGACCAGATGGCGTGAATTGCATGAGTCAAGCG
          ACTTGTCCCATAGCAAGCGCGTCTTAGATTGTAAAAGTCA

