 8 1000
t1        CGCTGTGACTACTGTAATGTGTACCAGCGAAAAGCTTTGGGCCTTCCGGGAGCGTTAGAC
t2        TGCTGTGATTACTGTGAAGGGTACCCGTGAAAAGCTTTGGGCCTTCAGGTCGCGTTAGAC
t3        TTCTGCGATCACTGTGAGGTCCACTAATAACAACCTCTTGATATACCGCTGGAGATAGAT
t4        ACCTATCACCCCCGTCAGACTCGCGACTGAGCGTGGTTTGCGAGAGTCGTAGGAGTAGCT
t5        ACCCAGGCTTAACGCGGGGATCGCGAATGCAAACGATAGGTCTAACCGTTATGGAAAGTC
t6        ACCCGGGCTTAACGCGGGGACCGCGAATGCAAACGATAGGTCTAACCGTCACGCGAAGCT
t7        ACGCGCGTACATTTTTAAAGTGGAAACTAAATACTGTATGCACCCTCGGATTACACGCTA
t8        AGATATGTGTACCTTTAAATACATCGGGTATAGTAGAACGACTCAATCATAGACGGTCCC

          GTTCCCGAACTTTCTTGGGGTTAGATTTTGACCGAGCAATGGAGGCGGCCTACTTCTCCC
          GTTCTTGAGCCTTCTTGGAGTTAGATTTTGGCAGGGCAATGGAGGGGGCCTACTCTCCCC
          GTCACTGGCCCCTCTTGGTGTTAAATTATGGTAATGCATGGGGGGTGGTCCTCTTTGTCC
          GCCCCTTAGCCTCCTTGGCGTTAACGCTTGGCAGTCTAGTGGGGTTGGAGCAATTCCTTC
          GCGTCCTGAATTGTTGAGTGTCAATATTCGGCATACAAATGAGGATGGTTCACCCACGCA
          GCGCCTTGTCTTGCTGAGTGTCAATGTTCAGCATACAAGTGAGGATGGTTCACTTACGCG
          AGGACCGGCTGCATCTGTTTCGCATGTCTGTAATTGAAGACGAAAAAACAGTATACCCGA
          CAACCAAGTCGTGTCGGTGATTAGCGCCCGTCACTGCAACGAAAGAGCTCTACGGTCCCT

          CTGCCAGTGACAGGGAGAAATCAGCATAACTTCTACGGAATCAGCCTGGTATCCAATCCT
          CTGACAGTAACAGGGGGACTCCAGCGTAACCTCTTCGGATTCAGCCCGGTGTCCAGTCCC
          CGGATCGCAATGGGGGGATATACGGGGAACCTTAGTGGAGTCCACACGCGATCTATTCCA
          TCCCTCGCTTGCAGGGGACTTGAACGCAACGCTCACGGACCCACTCACGAATTCTATCCT
          GTACTCATCTGCAGGGTACAATACTACAAGATTTGTCAGTCTACCCGGAGAACCTACAAT
          GTCGCTAACTGCAGGGTAAAATAATGCGATATTCAGCCGTCTACCCGGGGAACCTACAAT
          TCGTTCGTCCGGAGGGTCACATAATACAAGTTATCAGGATTCACCCGGGTCCTTCGGTAA
          TAGATCGGAGGGATCTCCGGATCTTCTGATCCGTGAGCGGCTGACCTGGAATCCAGAGAT

          TGCGCAGCTTGTCACTTGTGCTGTCGAGAAGGGACTAATGCCCCTGGGAACCCTGAGCCT
          TGCGCTGTTTGTCACTTGTGCTGTCGAGAAAAGACTAATGTCCTTGGGATCCCTGAGCCT
          TGCGCCGTTCCTTGCTAACGGTTCCTAGTGAGAACTGGCCCCTCTAGGGAATCTTTGCCC
          TAAGCTGCGTACGGTTCACGTTTTTAGGAGTAAACACGGCCTCATTGAGTGACGAGGGCA
          CCCGCTGTTTATTGCTAATTCCTGCTAGCGGAGACTGGTCCATCCGGGAGGTCACTACTC
          TCCGCTGTTCATTGCTAGCTCTTGTGAGCGGAAATTGGTCCTCCCGGGAGGTCACCACCC
          CTCCCGGACCCTGTTCCCATTATTCCCGCAGCCATCGAGTCCAGGGGTCAACCACCAAGC
          CTTACCGGCCTGGGCCCTCTTTCCTGCTACGAAAATAAGTAGACAAGAGCGCCAAAGTAT

          GAGGGTCGAGTCCCGCGAGTCGGTAAGCCCTACTCGTAGAACATCGCTAGATTTCCACGG
          GTGGGTCGAGTCCCGCGAGTCAGTAAACCCTACTTGTAGAACATCGATAGATTTCCACAG
          AAGGGCCACGTCTCATGAGTCTAAAGGCTCTACTTACAAAACGACGATAGGTTCCCATGG
          TCCGGCTGCAACTTGCGGGGTTTCCAACGAAATGTGCGGTAGACGCCATCATACTTACTG
          GTGGACTTACTCCTCAAAATCTTTCCACCAATAGCCCGGCGTCTCTTATCATTCTTAAAG
          GTGGACTTACTCATCACAATCTTTACGCCAACAGCCCGGCGTCTCTCTTCCACCCTAAAG
          GCGGTAACGCACCCGCCGCTACATTATTAAAAACGCCACGGCACCTCGTTACCCTCGCCG
          GTAACTCTTGCTCAGAGAACACGCTGCCCAACGATGAAGGGCGTTTTCTCTTAATCTAGG

          TTCTGTGAAGTTTCCTACCTCCTGACGAAGTTACGCCGTTGACAAAGTGCAAGACTCTGT
          TTCTGTGAAGTTTCCTATCACCTGACGAAGTTACGCCGTTGACAAAGTGCAAGACTCTGT
          TTCAGTGCAGCCCTCGATCACCCGCCGAAGTTCTTCGACTTCCATAGCGTAGGGGCACGT
          CCGAGTAGAGATCCCAATCTTTTAATGTATACTCTCGCTTATCAAAGCTCACGGCCATGT
          TCCTTTGAAGCTTACACCATCCAGTCGGGATCTCCCGCTTAGCGTAACGCCAGGCCCTAT
          TCCTTTGAACTCTACACCATCCAGTCGAAATTTCTAATTCAGCGTAACGCCACGCCCTAT
          TCAAAAGGACCCCGTTGCCGCTGGCATTTTCGGGGGGCACGAACGTCTAATTTTCATCAA
          CGTAACGGATCCCGTTACTTTTTAGTACAATGTTGGGATTGATGCATCCACATTCATAAT

          GATAGTTAGTGCCCGGGGACCCGTCTTTTCCCTCCTACTAAGCGATATAAGCCCGTGGTT
          GATAGTTAGTGCCCGGGGACCTGTCTTTTATGCCCTACTAAGCGTTATAAGCTGGTGGTT
          GCTGTGCAGTGCATGGGGACCTGTTTTTTACGTCCTCCTAAGGGCAGTAAGCTTGTGGTC
          TGTGGTCGTTATCCGAGACCTAGTGTCTACATTCCAGTCAAATGACGCGAATATGAGGCC
          GACGGTTGGTTACTGAGCGTTCACGTTTAAAGCGGAGCCTAGGGGTATTGGCCGGTGGCT
          CATGGCAGGTAACTAAGCGTTCATGTCTAATGTGAAGCCTAGGGGGATTGGTCGGTGGCT
          GATTCCCACACCCCAGGGACCTACAAGGGGCAACCCAATTAGGTATGGAAGCGTGCGCCG
          GAAGGGCCCCACGCACAGCACCGAACATGGTTTCGCGTGCGGAACTGGTAGCACGAGCTC

          TGTTCCCGAAACAGCAGGTATGATCTTGAATCGATAGTCTAAAGCCCTAAACAACGGTTT
          CGTTCCTGAAAAAGCAGGTACGATCTTGAGTCGGTAGTCTGAAGCCCTAAACGACGGTTT
          CATCCCTGCCTAGGCAGGCAGGTCTCTGAATAGGTAACCTGCACCACTAAGTGCCGCGAT
          TCCTCAGAAGGAAACAGGGAGGGTCCCAATTTGCACAACGGTATCGTTAAGTAGTATGGT
          AACTCCAAGTGGGGCGAACGGATCCCCAGTTTTTAGGTATTGTTCCCTAAGCGAGATGCT
          AACTCTAAGTGGGAGGAGCGGATCCCCAGTCTTCGGGTATCGAGTCCTAAGCAGGATGCT
          AGTCCTGGGACAAGAAGGTGACCATGTGAGATTTTGGTACTGTTCGCTACAAAATAGAAT
          GTTCATCGAGGAGGTCTATCAAGTATGCGTCCTATAGCACCATCGGCTATAATCTATACT

          GTTCCGGGTGACGCTCTCCCACAGGTGCAAACAACGTATTTTGTCCGGCAAACAAGTACG
          GTACCGGGTGATGCTCTCCTACTGGTGTAAACAACGTATTTTGTCCGGCAAACAAGTACG
          CTATGGAGTTATCTCTTCCTGCAGACGCAAGCAGCACATACCGCCCAGCTGATTCTTGGC
          TGCTCGTACTCTCAGACCTCAAGGTTGCACCTACTTTAGCACCGTCGGTGCAGGCCAGAA
          GTACTATGATGTTAAGACCGCCATCGACAGTTGTTCCAGACCCCCTGAGGAAGACTCGAG
          GCACCATGATGTTTAGATCGCCGACCATAACTGTTGCGGACCATCTGGCGAAGACTCGAG
          AGGATCCCGTTTAACTCTTGACGATCGCGATCACCAGCGATAGAATAGTAAGATAGAATT
          TCACTGTGCCTCTCCCCACGTCGGTCTGGTATGTTTCCATTATCAAAAAAGAACCCAGAG

          GATGTGCCACAGGCACAGAAACCCAAAGAATAGATTCCACCTCGAACAGGAAGTAAACGT
          GATGAACCCCATGCACAGGGACCAAAAGAACACATTCCACATCGAACAAGAAATAGACGT
          GATGTATCACACGTTCGGGGGTCTCGAGATCATATCTTACACTGAGTGGGAGATCACTGT
          CACGCGCAATAAGACCTGGAATTCTGAAGTCAGACCCCTGTCTGTACCTTAATTAAATGC
          TGCGTTTTTTAAGCTTAGGTCTATAGTTCACGTACTCCGGAATGTGCCCGCGTCAAGGAT
          ATCGTTTTTCAAGTTTAGGCCTATAGTCAACGCAATCGAGACTTTGCGCGCGTTAAGCGC
          ACAGCCCCGACTTCCCGGCCACCCCAACACCAGACTCAAAACCGGTTAAAAGGAAGGTTG
          CGAAACTTGGCACATCAGATACGACACACAGGGATGCGGAGTTGTATACGCCGCGAGTGT

          GTGAATTCGAGAAATCCTCGAGATAAATTCGGAGGCATACCTGTCGAGAACGGCGTCCGG
          ACGGATTCCAGAAATCTTCGAGATAAATTCGGAGGCCTACCTGTCGAGAATGGAGTCCGG
          ACAGAGTTGGGAAGCACGCGTATTAAGTCTGGAGGGCTAACCGTCGAGAGTGACGTCCGG
          ATGGACACAATAAGCTTTATTGTTGCATTTGCAGGCCCAGTTGACGATTGTAGCCCCCAG
          ACAGATCAGACAAGCTGTCGAGTCAAGTCTGGGGGCTTATCAGCCCGACAGAGTTTCCAA
          GCAGATCAGACAAGCTGTTGAGTCAAGTCCGGGGGCCTATCAGACCAAAGGAGTTTCCAA
          TTGAGTGCGGGGCCAGGCGGCTGTTTGCCTGCATGCCTAGGGGTAATAAGCATATGACGG
          TAGCCACTATGACGGTAAGTGGGTGGCTTATTCCAGTCGCTCTAGTCTGTCATAGGCTCC

          TACCAGCTCCGAAACAAGTGGGGAATATCTATTAAGTCAGCCTTTTGGTTTCGGTAAAAG
          TACCAGCTCCGAAACAAGGGGGGAATATCTATCAAGTTAGCCTTTTGGTTTCGACACAAG
          CTTCTTCTCCGAGATAAGCGGAAACGATTGATCAAGCCAGTCACTGGGATTCGGCCAGAG
          TCTTCACTCTAAGCCATGCGAGACCAACTTTTTACGCCGGTCATTCGAACTTGACTGTAG
          TATTTACGTTAGGCCTAGGGTGACGTTTTTGCTAAGTAGTCAGTTGGGATTTGGGAGAAA
          AAACTACGTCAAGCCTAGGGGGACGTTTCTGTTAAGTAGCCTGTTGGGATTTGGGAGAAC
          CGACACAGTAAGGTCTGATGAGATAGTCTCGTCACTTCACCTTACAGGGCCTGGGCGCCC
          TACGGAAGATAGACCTGAAGGGGCGAAACGTACAATAATGGCGCTGCACCACTGCCTGTT

          CGCGCACGTACGTGGTTATTAGGAGATGAAGCGTGAACGATCGGTAAGTTCCAAGCATGA
          CGCGGGCGTATGTGGTTATTAGGAGATGAAGCGTGAACGACTGGTAAGTTCCAAGTATGA
          CGTATTTGTACGTGGTTATCAGCAAACGAAGCGTGCTCGATAGGTAAGCGGCGAGATTGA
          CGTGTGGGGGCATGGTAATTCTGACAGGATATGGGCGTTGCAGACCTATTGTAAGAGCGA
          CGTGTGTGTGTGTAGAAATCGGGAGATGAGGCGGGCAAAATAGACTGTCCGTAGGTATGA
          CGCGTGTGTGTGTAGAAATCGGGAAAAAGGGCGGGCCATACAGACCATCTGCGGGTATAA
          TCTAACTCTACAAGGGATCTATTAATAAGAGCATCCTTCCCAAGACGCGTGGAAGAACTA
          TTATTCATCAAGTAGTCATCAAGTGCAAGAGGAACTATGGCAAATTGATGGAGCGGGTCA

          GACGTCCTATATAGAAGGGCAAGTTGTTCTTTGAGCTACCATAGCCCGGAGGCGACACTC
          GACGTCCTATATAGAAGGGCAAGTTGCTCTTTCAGCTACCTTAATTTGGAGGCGACACTA
          GAAGTCCCGTTAAGAATGGGTACACGTACTTCTAGCTGCTTTGTTTCGCAGGCGACACTC
          GACGCGCAAAAATCAATTGTTGGTCGTTTTTTCAGTTGCCATGTCCTGGACCCGGCGGTG
          GAGGAATCGTACAGGGCTTCTGGCCAACTTTTCGGTTGCCGTGCTTTAGAAACGGTGTTG
          CAGGAACCGTACCGGGCTTCTGGCCAATTTCCCGGTTGCCCTGCTTCAGAAACGGTACTG
          GATTCCTAACGTGGAATAAAGGGTTGGCATGCTAAAAAATAGAGCCCGGTGAGTGGATTA
          AGCCTTTAGCATGGTGTCGTGGGCCAATATACCAACTACAACGGTCACGCTACCGATCCC

          CCCAATACCTGCACATAAGGATATGTCGAGTTTCTGCCGAACGGCACACACGAAAAACCG
          CCCAATTCCTGTAACTAAGGGTATGGCGAGCTTCTCCCTAATGGCACACATGAAAACCCG
          TTTGATACCGGCAAATAAGAACACAACGCACTTCCGCTAAGCGAACCACGCCAGAGAACC
          TGTCATGCTGATCAACTAAGCTCTGTCGAGTCTTCGGTTAGCGCAGTGTACATATGCTTA
          TCCGGTCTTGATACATGAAGGCAATGCGATGCGGAACCCACTGCTCTATGCAAGTCTTCG
          TGTGGTCTTGTTTCATGAAGACAATGCGAAGCTGAAGCCCCTGCTCCATGCAAGTCTTCG
          TTGCCTGACGATTATCCGTAGAGCATTCTATCTCGTTCGGAGGATCCAGGCCAATCGAGT
          TCCCGTAAGGACTAAAACCAATAAATCAAATTGCGTCCGGGCGAATAAGGCGAGTTGCAA

          CTTTTATGTTCGTTGTTTTCCGGTGGGTTAAAACTTCTCCTACCCCTGGAGCTAAGCAAG
          GGTCTCTGATCGTTGTCTTCTAATGAGTTAAAACTTCTACTACGCCTGGAGCTAGGCAAG
          ACCACACGTTTTATACTCTCTACAAGGTCAGAACTTCTTTAGCGTCCGGGGGTTTGTAGG
          GTCTTATCCACATTACTAGCTTGCGGAGTGTAATTGCCCCTGCGAATGTGTACTAATCAG
          ATCATCCATACATGGTCTTCCAGCAGGGCGATACTATCCCTGCGGCTCACGTTATGCAGA
          ATCATCCATACACAGTCCCCCAGCATAGAGACACCGCCCCTGCGGCTCACATCGTGTAGA
          GTTTTATGTCTCGTACATCTCAGGGCGACGGACTTCCTATCCTATTTGGCAAGAAGTAGA
          GTCCCGGCCTTTTCTCGACCTGGACTTGCACATTGTCCTTTTCATTCGACGTGTGGTAAT

          CATTGGTCTCGTTACGCGGACTGGGCTTACGTTCTCTGCG
          CATTGGCCCCGTTACGCGGACTGGGCTTACGTTCTCTGCG
          TATTGGACTAATCACACGTACTTGGCACCCATTCTTTATT
          TAGCAACTAATCTTAGCGGAAGTTGCATCAATGTATCATC
          CATGCTAAGTCCTGTCCGAATTAGACCTCTACCTGTTAGT
          CATTCTAAGCCTTGTTCGAATTAAACTTCTACGCACAAAT
          GTAGCGATGTTCAACGCCCAAGGACATCGGTCACATAGAT
          ATCGCAATTGCCAGTGCGGTAGATTATCCAATCTACGACT

