 8 1000
t1        GCGCGGAAGACGGATCAGCCAACAGAGTACCCTTTGGCTGTGTTCAGGATTCCAGACTAT
t2        GAGCGGAGGACTGTACAATCAACCGAAGCCCGTTAGGCTGTGCTCAAGGTTCCCTTTTAT
t3        GGGATCGGGAAAGATCAACACTCGGGGGCTCTCTGACCTGCACTTGTGGTCTCACGACGC
t4        AGGCTAAGGCTAGGTCCGCCTTGAGCCACCGCCTAAAGCGCGTCGGATGTAGTGGATCAC
t5        ACATGGCCGGCAAATATGTTTATTAACACGTTATTCATGGCGCATAGGGTCTAACCTCGA
t6        ACATAAATGAGAGACGCGACTTAAGGTCCGTTCACTGTAATCAACGTTGACTTGCCCAGG
t7        GCACGCAACGGAGACTATTACCTAGACGGTGCCGCCGGGGTATGAGAAGACCGATACCGC
t8        GCTCCCATCATCGACCAATCCAAGGGCTGTCATGTTAGGACATACTGGGCTCAATATTAC

          TTTTCCCTTATCCTACTGACATTCTTCTTATTTGGTCTGCGTCCCTGCAGACACTGTCGG
          CGCTCCCTCATCTTAACGACATTCTTTTTATTTGACTCGAACCCCAGCAGATACTATCGG
          CATTGGTAAGATTGCGACATTCAGCTTATAGGTGACAGGTAACCGAACGGGTGACGTGCG
          CATTTATTTACTTAAATGTGCCACTTTACATAAAAGTATCAGCTCTATACCAATTACGTA
          CAGAGCCACACTCAGGTAAGTCTATTCGCACCAGGGATGAGCCTTTGGCACTACAAAGCG
          CAGTGATACCTTCTGGGTAGCGAGTCTGTAATGCATATGAATCCTAGGTGCTCTGCTGTA
          CTCCTATACAATTAATTGAACCGGGTAATATTGCACGAGTCCTCTTAGGGATATGGTGCA
          CATCGACCCGATCTACTAAGTGCGGTTCCGTTGTGTGGGCTCTCTTAGGGATCTTATCCA

          CCACCGACGGGGATAGCTGCGTTTATCCGTTCCTATTTATTAGCGCCTTGAGAAACCCTT
          CTCCCGCCGGGGATCACTGCGTCCACCCATGCTTAATCGTAAGCAAGTTCAAAATCCCTC
          CATCAACCAGCAGGTGTTGTGTTGAAAAACCATTAGTTTACATCATAGCTCTGAATTTGC
          CTGGCATTTGCAAATGCGGTGGAAAGTTAACTCCTGAAGTGGACACATCCCGAACTACAT
          TTGCTGCTGGTAAGATATAAGCCCTATCTCCACTCGTTTTGAATATCTAACGGGTTATAG
          TTCTGAAGGGTGGGCTTCGTGTCTAAACATCTCTTATTGCAAGCGCGTCATGGACCGACG
          CCGTAGACACCGACTCTCATAAGGGCAGATTATCCCACACAGGTGCATATCTGCGTGCTA
          CTATTTACTCCGTCTTCAACACGAGTGAGCTATTTAACACCGTTACACACTGGTAAGCTA

          TGGGGTCGAGCCACGGGCGTGGAGTTTCAATTATTACATTTTGAATCTCCGGGATCGCGG
          TAGAGTCTGGCCCCGGACGTCGAGTTGGAATGATTACATTATGAATTCTCGGACTCGGGG
          GTAGGCACAGCTTGAGCCGTGTAGTAAAAGTAGTATTGCGGTGCACTCGCGATTCCGAAC
          TCGCCGCCATTCGCGGTCATGCGTTCCTATTTAGTTAATGGTGGAGTCCCGACGCCGGAT
          TAGAGTTAATGTCTACTCGAAGCCACGCCTTCTTTGGACTCAGCTTCACCTAATGTGACG
          CAGGAAACGGATTCACCTCGGAGATCGGAGTCTTTTTGCCGAGGGCAGCTTGTAGAGCTA
          TCGGAAGTAATGTCCTGATAGACACTGTGAGTCTCCACCGGATACGTCTGAATGCCGCCG
          TTGAGTATATCGTGTTCTGAGACATCCTAAATATCTTTAGGGGAACCGCGAATCGTGTAC

          AACTTTTTGATCGCGAACGCTTAACCACGTGTGGAGGCATGTGAGTTTCGAAAGTGGTTG
          AATTTTTCGTCCGCCACCGCCTAACTACACCTGCAAGCATGAGAGTTTCAAAAGCTGTTG
          ATCTCACCGACTGTGGGAGCGTTGGCGATTTGGCGAGTGTCAACGCTCCAGGAGTAACTA
          GGCCACTCGATAGCGGATGATATGGCTACTCAGGGGGCTTTTGCGTCTCGGAGATGGTCC
          AACTCGGTACAGGTATGTTACCACGTCACCCGCGCGTGGAATTCATTATGGGTATCCTAG
          GCGTTCGTGTCGGTAGACTGGCGCCCGATTGGGACGCGATATTGACTCCAAAACTTCCGC
          ATCTGCGTGACCAGAAAACGACCTGTGTTTCAGAGATGGTGATTTGCCAAGAATGGTTTT
          ATCTACGTCACCAGGGAATAATCCGTATATCCTTACTTACGACTAACCAAGGACGTAACT

          AGGGCCCGGTAACCACTACCCCGTTCAGAAGAGGGGCGGCAACTGACGAACCGATTTTAG
          GAGGCTCGGTAACTAACACATTGTTTAGAAGAAGGGTGGTATCTGTCGATCCGCTTCTAG
          TTGGGTTAATATAGGCTTCTCTGCCAGGCACGCAGATAGCCCTCTTCAAGCTGATTTCCA
          TCTAGCTGATATGTCCCTCGTGAAGCAGAATAGGCACTGCTGACGTGTGTGCTATTACGG
          ATAAGTAGACATGCGTTTATTCCATCAAGCAAGAAGAAAAACCCCCAAGCACCCTAAGCG
          TCTGCTTTATGTGAGCTTCCTATATTAAGCACGAGGACGCTACCTCAGGGATCGCTTGAA
          GCTAGTAGGTAGTTGCAAGACCATTGGGACAGGGAAAGACCCCACCGGGACCGCTCACAA
          CTATTTTTGAACTTGAGTTTCCTTCGGGATCAGGACTGGCCACACTAAGTCCGATTATTA

          TCCGACATCGCAGTTACGGTACTAAATGTCAGATGCATTCATAAGCGCCTGTGTACGACC
          TCCAACATCCTAATCGAGGAACTATAGGTTAGATGCAATCATGGGCACGTGTCTATGACC
          CGAAGTCATTCAGTTTAGTGAGCGACGATAGGGCAGTGGTATTAGCACACTCTCATAACA
          CAAAATATTTAGTTTTCGAACAATATATGGGAGCAGCCTAGCCACCTCACCGCTGTGACA
          CCAACCCCTCAAGCCACGCACAGGAAGGCGTGTAAGCACCTAGAGCAGACACCCCGTCCA
          TCGAGCCACCTAGTTAACTACGATTCGGGGCAAAAGTACTGTTCGCCGGCGTTCAGTGCC
          CAAAACACTTCAACTGTCATAAAGCCCATTAGGTGCTTAGGCTACTGCAAGCGTGTAACT
          AAACTTACTTCACTCGCTATAAAGTTGTTCGCGTACTCCCTTCATCACAAGTCCGTGGCC

          CTCAAGGTCCGACGCCTTGAGAGCACAGATAGGTGTTCGCGCCGGTGGTGCTATCAAATG
          CGGAAAGTGGAATGCCTTGAGAGGGTAGCTCGGTGCTAAAACTGACAGCGCCACAAACTC
          CCGGACGTGTGAGGCCCCAAACTGACAGATTCCTGAATACGAACGTGAAGCCACCCAATT
          GAGAGTCTGTCACAGCAAGCAAGTGCAGTCTAGGTCCCGTACCCCCCACGATTTATAGCT
          GAGTCAGCGTTAGAGCAGAAATGAGTCAAAAATCGTCGATCCAGGAGAGATCTTGTGTTC
          CCGACGGCGCTATGGCCGTAATGGGAGAGGGTAAGCGCGTACAACAGAAATTTTGCGCAC
          ACGTGAATCTGAAGCCCGCAGTCAGACGTCTTACGCCGTCGCACGTGAACGCCCGTGTCG
          ATGCCAAAACCTCTGGGATGGCGTGCCGAGCGTTAGCCTCGCGTGAAAAGGCGCGTAAAA

          GAGAACATGGTCCTATGTACCCGGAGTTACGGTCATTGTTAGGGAGTACTATTGTCTAGC
          GAACACGTAATCCTACGTATCCAGAATCCTCGTCACTACTAGGGGATACTGTTATTCATC
          GCGATTTAATACAACTTGATTTGGACACACCATCGCTTGCCGTAGGCGATGTCACGCTTA
          TGGCCCGGGAATACAACCTCCCGGAAAGCCGTCTGTCTCTGAGGAGAAGTACGGTGCTCG
          GCTGTCTGCTGACTAGTCCATTATTAAATCGGTCCTAACAGCCATCTTCACACGTTTCCG
          TAGAACAAATGACTCACATACTACCAATTAGACTCCGATTATAGAGGAGATTCGCATTCA
          ACAGTGTCATATGCCTGCGCCAGGAACCCTGACCGTCGCCGCGAGGAATTAGTGCCTGAA
          GTTGTGCTGAATGATCTCGTCAGGGAAACGGATCGCCACGGGCGCGTAGACGTGCCCCAA

          TCTTACACTACGAATCCTTCAAGATTGAGTTGGAAATGCCATCCGCACCAAAACTAGTAC
          TACTAAACCATCAATTTAATTAGGTTTAGGTGGTGCTGTCACCCGTACCAGAGCAAGCAC
          TGCAAGCTCGACGTTTTCTCTAACGTGGGAAGTTATTGCGATTAGCAACAACGACAACTC
          CCAGGATATAACATTTTATTTGTGCCTGGATTCTCCTGGCCCCAACCCTAGACGGTTTGC
          TACCGTAGCATCCCGGTGTCTTACTCCGGCTGCTGTACCAACACGTATCGTCGGAAGTGG
          TATTGTACCGTCGCAGTGGGTGATTCCGGTACCGTTCACGACTAGCATAGACGGCGGGGC
          CAATGTGATGGTGTGCCCGACGATAATTGCAGAGCCGGCAACCAGCTAGGATCGGAAAGT
          CAGCCCACCGGTGCGTGATTCGATGTTCGCCGACGCGGTTGTTGGTTTCGATGCGGATTT

          CCCATGCGCCTGTCACAGCCGTATCTACGTCCTTGCTGAAAAGTATACATAGCTACGTGA
          CTCATGCGTGTGCCACATACATATCCTCGTTGTCGTCGCAGAGAACACAAAGAAGCGTGA
          TTGCTGGGCTATCCGTGATCCCGCTGAGGCTCAGCTGACAATATATGCAGCTGCCTGTGG
          TGTCTGGAAGCCCCTGTTCCTTGTCCAAGCTGCTCCTTTGGCAGGCTTGGTCGCCCGTCA
          CCTTATAATTGCTTTCTGTATCGTACCCAACGGATTCGGAGTTAGCATACACGGCCGCCC
          TCCTCCATCCGCCTTCGTTACCAAACTCCACTAGCTTACAGTCAACGTAAATGGCTATCG
          TGTGTGCAAATGTTAACCAATTGCAGCCGGATGCTCCTCGATTTGCTATATCGTATGGTA
          TATGTGCGCTTCTTGCTTTCCTGCCGCTGGCGTAATATCGGCCCGCAATAAAACTTGGAC

          TTCTAGTAAAGGTACGTAGCGACTCGACGACCGCGAAGGTGTTGATGTCTAGCGTAGCTC
          CTCCCGGGAGGGTCCGCAGCTATTCGGCGCTGGCGAAGCTTTTGCCGTTTGGCATAGCAG
          TTCCCCAGTGGGCTCGAAGCTTTCTGAAGCGAGGGAATCCCATGCCGCTGGGCGAAGGTG
          CATCTACGTGAAGTCAGCGACCCCAAATAATGGATGTAGTTCCACTGAACGGCTCGGACC
          CGTTCTGTTAGGCCACATACGGCAAATTTCAAGAAGTCATTGAAAACTTGCATACAAATG
          TCTTCTAGGAAAACGCCCTCAGCAAATAGCAAGTAGAGCTTCGCGTGATGCGCTTGGCTG
          TTCAGCGCGAAATGTGCACTTGAGGCTCGAAAACGGGTGTAGCCGCGATGGTCGTAGGTG
          CTCTTTGCGCCAATTGTGGTCCAGTCACGCTGGTGGACCCCGTTATATCGTCCATTTGTG

          GGGTAGGTAGTCCGGAATGTGAGAGTCATGAATGTAACCCAGTCGGAGTCAAATATGACT
          AGGTAGGTAGTTCGTCATATGGGGATCCCGAATGCAATTCAGGGGGGGTTAAATAAACGA
          AGGCTTGCTAGACGAACCATGTCGTTTGGGTCCGGAATACTCCGAAGTACTCACTGTTTG
          AGATTGGGGTAGCAGATCATATAAGTTGGGGCTGATGGCATAAAGAGGACGAGTCACGCA
          AAATAGGCGAGGATGATTACAAATCCCAGACGCTATACGGAGGAATGGGCCGGAATCGAG
          CAGTAGGCGGCCTCGTAAGTCAATTCCAGAGCCGTCACGATCCGGGGAGCAAGTCTACAA
          ATGAATGCAGGCTGGTGCGTGACACCAGTACAAAGAGGCGTATGTCGGCTTTGTTTTTCT
          AGAAATGCCGACCACTCTCCATGTAGCTGACGCAGCTAAACATGCTGAGTCTAGTCCGTT

          GTGTAGCAGGTAACTTGTATTACCGGTCGGTATAGAACCGGAACGCGTCGTGGCTTATGC
          GCACTGTAGGTAATATGAATAAATGGTTGGTACGTAATAGTAGAGCACCCTGATGAAAAC
          GGGCGGAATCGGCACCCCTCAATCACTTGATATGTCTGAAGGTTCCTAGATAGCTGACGG
          ATGTGATGGTCAGTCCACTGCAGCATCCGACACATGTATGAACAGTACAGTGTCATACAC
          GTATTGTCGGTACCGTCAGAGCTCAACTTTCTGTTGTTTGGAGAATGACGTAGGATATAA
          ATACTGTCGTCGTCTCTGACTTAGAGCCCTCTCAAACCTCTGAGCAGGCGTAACACTGAA
          GTTACGTTATCAGTGCAGTTCATCACGCAAGTGCCGTAGACAGAAGGGTGTTATGGATGG
          ATACCACCACAGAAGCGACCGTTGACTGGACAACCCTACCATGGCGTGAGCTACATATGT

          ACTACGTTACTTATCGGATGGTCCTCTAGTCCCCGGGTGTTAAAGGGCTCTATCGAGTTT
          ACTACGCTTTTTAGTGGGTGACTGACCGGTCCAGCGGTATTAAAGAGCTTTTACGAGTTT
          GGTACACATGATGACCTACTATTGAACAACCCAAGAACGGTAAAGTACGCCATTGTCTTC
          GCCATTCTGGTTAACGTAAGACGGGTTTGTGAGTCTGCATTAAGGCATGCTTTGGGTACA
          ATTTCTTCCCAGTGCACACGCTGGTACGCCCCCATAACGTGTAGAGCCTCGTGCGCTTAC
          TATTTCTTCCATGCCTACTAATGGCATATTTCAGTCGTAAGAAAAGCTCCCAGGATCACT
          CGCACGATTTATGATGAGTGATTGCTTATGCCAGAGAACTGGATGCACATCCCGACTATC
          CGCACAATCACCACCGGGCATTTCTTGGGCTCAGAGCTGGGGAAGAACGCTTGAACTACT

          AGACGCCGCATGGTGACAATTAATGCACTGCTCCTCTGGTTATCTTAACACCAACCCATC
          AAATGCCAGATGGTGATGACTGATGCACTCTTCATCTGGACATGCCAATACGGGGCTATT
          GTCTGCTCTGCGGCGCTGACCGTACCTTTCCACGTCCATCAAGGTGATTCTGACTCGCCT
          CATCGGTCCTCGCGTTAGATTGGCGCTTACCGCATCTAAAGGTGAAGGTCTCCTCTTCCT
          CGTGAACTAATTGCGTCAGAGGATGTTCTTTACGCCCCATTCTGGAGTTACTCATTTGTG
          TGTGACTCTGGGCCGAAAGCCAATTGACCTCCCGTCCCAGCACGAGGTCCTACGTCCATG
          CACAACACCGAAGGCATAATCAGAGAGCTCCGCAATTACTTGTAGGCTCATGTCCTCAAC
          AGCTATTCTGATGCCACAACTGAACTGATCCCTGAAGTCTGATAGGTTTATATCTGTATT

          GAGGCTAAATTCATACTGTGAACGCCTGTGAACATGCGTT
          AAGGACAGACCCATAATTCGAATATCTGTGAAAACGTGCC
          AAGTTTAATCTCGTACTCTGACCACACAAACCTGTGCATG
          AAACGTAATAGGGCATTCGGACCATCTGTACTTCCGCCTG
          ACTAGCGTTTGGTAGAATAGCATTTTACCGGGTTTAAGAG
          ACACGGGGTCCCTGCTTTTGCATTACCACATGGTTGCGGA
          GAGTTAATCCGTCCTAATTGAACCCCCGCCCGCTCGTTGC
          AAGTGTCCGTACTGCGGATGAACCACGGTACGCCTTAGGT

