 8 1000
t1        CTTCCGAATAGAGGACTTCTCACTTACAAGCCTATTATGGACAAGTGCGGGTTCTACAAA
t2        CGCGCGAGCGAAGGACTTCGTGTCTACCTGCATATTACAAATAAACAGGGCAGTTACCAA
t3        CTCGCGCGCATAAACCTTCCCCCGTGTACGCCTGTTAAATACCAGACAATCAGATCTTTC
t4        TGCTCTCGCAAACATCTTTCCCTGTGTGATCTCGTTACATACTGGTTTCCTGGACCCTAC
t5        TTCGTAAGTGTACACTCTTCATTCTACCCGTCCTAAATACGAAGAATCGACACTTCAGCG
t6        TCCGCGCGCGCAAACTTATTAGCCTGTAGATCTGAAGCCGGCTAGCTGAGTATTTTCACA
t7        CACGCGAGCGCTATCCAAAATGCTGCCTCGCGCGGAGTACTTCGGGTGGTTGGGTCCGCA
t8        TGTGCGCGCGCAATGCCTTCAGTCTTTTTACGCAGTGTAACACGTATGGACGAGTCTGCG

          GTAAGTCCTAACGTACCTTTTAATTACTAGAGTTCGGGCGAAGCGCCGGGGATAACTATC
          CGAAATTCTAACGTACCCTCCGAATCGTAGGATTCGCATACCGCGGCAAGCGTAGGTATT
          GCGGCTGCTATTACGCCTGATCTCCAGAGGTTCAAGAAGAGACTGTTACCGAAAACGACC
          GCGGGTGTCAATACGCCTGACTTCCAGAAGCGTAGTGAGCGAATACTTACAATAAGGGTC
          GTTCTTGCCGTCCAGGTAAGCGAACCATGGTAGGCCTGATGAACGTCAGAGGCCGAAACC
          AAGGCCCCTGATAGAATAGCCGAAGTGACGCGCTTCCAGTTGGCAACTAAGCTGGTTGGT
          TCACCTTATGCACAAGCAGAGGACGGGAGGCTTCTTTCAGAGGCTACTATAACAGTGACT
          GGGTCTTACGGCGAGGAAGAAGACGATAAGTACAACTTGGGACCTTGAACGGCAGAAGTC

          CGACGTAATTAATCCACTGTTACAGGTCTTGTCATGGGATTGACCTGTCACCGATGTAAG
          CGCCTTAACTTAACTACTGTCCTGAGCGTTGCCTTAGCACTGTTCCGCTAGTAATGTGAA
          TGCCAAACCAGTCCGGTCACACGATATCTTGAATCTAGCCACAGATTTCCGTCCTACAAA
          GGCGAGGGCGATTTAATCTTACCATATCCTGGTTCAAGCTACATATCACCGTGATATAAA
          CAGGCCGCAGATTTTCTGTTGACGTTTCCTGCGGCCAACACATTGGGCTAATCATGCTCT
          GACGTTACCCGCTAACGTCTCCGGGAATTTTTAGCTGCTAGGTTGCGCCAGAGTTGTACG
          TGTCGTGCTTAAGGATCCTACGCAATAGGCGAAATGATCCAGTAGTGCTAGGTAAGTGTA
          TGTGGTGATTTTGCACCTTTGGTAACCCGCGGAGCCGATCGGAAACGCTAGATGCAGGAT

          GGAAAGGCTCTACATGTAGTCGAGAAGGAAAATCCGCAGGGTGGAATCAAAGGCCTTATG
          GGTAAGGCTATCCACTAACACGGGAAGGTAAATCAGCAAAATGGGATTAAAGGACTTCTG
          TGTGAAGGCACTTCATAGTACCAGCAGGGTGGCAAAATGATCGGGCCTTACTAGATATCC
          AACGGGTGCATTCCATGTTGCCGGCCGGATCGCTAAATGACAGAGACACAAGGGATCTCG
          TGCAAGATCAGTCCACCATCTAAGAGTAGGCTTAAGCCAAATGGATACAAGCATGCAGTT
          TGGAAATATGGTCCACAATCAATAAGAAAGCGTGAGGTAAGTTGACCCTAGAGGACTATC
          TAGCAACACCTCGCCACTTCGGAGCACGAACACAACGTCAGCAAACTGTCGCAGCCTTAC
          TGGCATCAAGCACCTGCATTGAGACAAGAGTGTACAACGCGTGGGTTACGAATGGCTACC

          TACTGTCCATTATATCCAGCGAAACGGACGGCCCGGGTCACCCACTCGCCAATGCTAAAC
          TAATCCCCAAGTTATCAAGAGACCTGATCGGGTCGGGTCACTGAATCAGGAATTGACTAC
          GACGTCAACGAACAGTTAGTGAATTGGGTTAACTGCACGGGTTAGACCTCTATAAAGCCA
          GACCTTAATGTAAGGTCAGTCTGGCCTGCACACTTTACAAGCTAAATACCTGGAAAGTAA
          TATTGTCAAGTACCTTGGACATGCAGGACTTCCTACGACCATTACATTCCCAATCAAGGT
          GGTAGCCACTAGTTCTCGGTGCGTCGTACGACTTCCGGTAGTCAGGTTTCGCGCAGTCGG
          GCTCGACAGTGTCTCTTGCGCCGCTGAACCGCTCAAACTTCTTATGTACGGTGGGAAGGT
          ACTTCCCACTGAGTATCGCACTGTCGTCCACCCCTTGTCAAGCAAGTATGGGTTGGGTAC

          AGCCAGAGTATACACCGGATGTGTACTTTCTGGTCGTAAAATACAAGACATGCCTACTGT
          AGCCCAATCGTACACCGAGTGCGTTCTGTTCGGCCCTAACCCGTGGGTCATGTTCATTAT
          CCCGTGATAGAACGGTGAACGCACCGTCCTCGGAAATAACGCCTAGTTTGCACCTTTTGT
          TTCGCGATCAAAGGGTACATGTGTCATCCTTCGGTTGAATACCTAGTTTGACCACTTTAT
          GACAGAAGAGCGAGGACCTTGTACTATGTGCTATTACATTGTTGGGGGTGTCTTATCTCT
          TACCTGGAAAAGGAGTATCACTATCGTTTTTAGCTACCATGCTAAGGTTATGCTATATGT
          CTACAGGATAAATCTGCCTTCATACAGCCCCGGTTTAGATGCAAAAGACCCAGTGTCTAA
          CTTAGAACAGAGTCGAGATCAACAAGATTCGGGTAATTATGCCAGAGCCCTAGCATTTAA

          CCCGGGTCGGTCTTGTGGTGCGTCGCGGCATGACTGGGTCGCTAACCCCATTTGATCAAG
          TAAGGGTGGACCGTGTGTTGAGCCTGGGCGTGACTTATTTGCCAACGTAATAAAAACATA
          ATGATTTATGGTCCTCAGTGACAGGTTGTCTGACCCACCAGTGTAAAACATTTCCGCGGA
          ACAAAACATGGTTTTTCTCTTCATGTCGCTAGGCATACCGGTGCCTATCAATTACAGGAA
          TCTAAGAATATCCCCTTATGACTGACCACGTGGAGGCGTGAAGGACGTTATTCGCTAAAG
          ATTAAACTTATACACGCTCGGGATGCAGGATAGAGGAGTAGCAGATGCATCTTGTCAATT
          CGCGGCGATTTTTACCCGCGTCCTATGAGGCCCTCGGGTACAGGGTGTGATTCAACACAA
          GTTGACAACGTATCTCAGCGATCTATGGGACATTCGGATGGCGGCAGCGATTCTACTACA

          ACTGAAATCCAGCACTTGAAACATCCCACTGTTTCCTCAGCTTCTTGGCGCGGATGCAGT
          ACCGGGACTCAGCATCGGGGGCTTCCGACGATCCCCTTAACATGCTGGACCGTACTGAGT
          GAAGCAACGCGAGACCCGTGAACTTCACAGTTCATGGGTGGGTAGCGTCGTGTTCATCGC
          AGATAAGTCTGGGACCGGTGAGTTGCTCAGTTTACGAGAGAGTTGCGTCGCGTGTGTCGC
          ATAGTAACTCGGGTTACGCGGTACACCAGTGTTGGTAGGGAACAGAGTAGAGAAAGCAAT
          AAAGCATTCTGGTTCCTGCACTACCTTCGCCCTGGTGCAAAGCAGCCCCGTGACTCTAGC
          GAATAAACTTGGCTTTAGCCAATTTGTTCTGGTATTGGGGAGTGGCGCCGCGTTCGTGGT
          TGTGGAACCCCGCTTTTGTAATTCCTTCTTACTACTGGAGGGCATTGTTGTACATGTAGC

          GGAGTCCTGGTGTTACTTCCCTTACAGTACGATCTCTTGCACGTTGACATTTGCTGACCA
          GGGACCTCGGCATTGCTGCGCTTCTGCCAAGACCTCCGGAGGTCTTCCGCTTGTCAAGCA
          AATCGACTGGTTTTAAAACGGCTGAGGCACGGTGAAGCAATCCATAAAAGCCTCGGATCT
          AATAGACTGGTCTCAAAACGGTCGTGGCCCGGCGTAGCGCTCCTCCCCACCCGCGAATGT
          AAGACAAAGACGTATTATTAACCATAGCTCGGTATTGGGATATTTCTTGATCCTGCTATC
          AGGCGGAAGAAATATTCGTGTCCCAGCCTTGGCCCTGCGGCACCTTACGATAGAGACGAC
          ATACACATGGTAGATCGTTGAGCTCGTATACTCTCAGTGTCGGTTCGCCTAGGTGAAGCA
          ATAAGACCGACATACCGACAGGCCCTATTAGGTCTTGTGGAAACTTCAGTCAGACCAGCC

          TGGCGTAGGTCTGGTCTACGTATCCGGGACGCGAGTGTGATGCTTGGGAGCCTCTCATAA
          TACCGTTGAGCCGCATTATCTATTTGGATAGCGAGTGCGGTGCTTGGTGAACAATCAAGC
          CGCTGCGGGCATTACTTAAGCTATTGCATGGGGGGAAGACCGAAGGTCGGGTCTCGATCG
          CGCTGCGGGCCTTATTTAATCTAATGTACTACGGGTTCAGCGACTGGCGGGTTTTATTTT
          CGGCGTGGCCGTTAATCTAGTCAGCACAATTCAAACAGCATTAGTGACGTCCATCCGCCA
          TGATGTGAGCCCCAACAAGACCCCTGCGCTGCGAACTAGGTAAAAAACATGTATCTATGG
          TGCTGCGGTTCTCAATTAAGTGTACACACCGTACAGCTTATGATAAATGCAGGCTCATTA
          CGTTGCGAGGCCAGACTACAACGCCACGCTGCAGGGATTACGCCAGATATGTAGCTTCTT

          TCATATCAATATAGTGTGGCGGCGCGCTTATAATCTGTCGGATTGACGATGTTTACCGTT
          CTACGATGACAAAATGTATCGGCATGTTCACGATTTCCAGACGTGGCGACTTTTAACCTT
          TCGTGGACTCTTTTGCTGATATATAATCCTGGGTGAATGCAGTCTCCTACAGTCGATATC
          TTGCAAACTTCTTGACTGGTGCACGTGCTTAGGGGAGCGCGATCCCCTATCACCGGTGTC
          TCTGGAATCCTGAGGTAATTAATCTGCTCGCGGCTTCAGGGATATAAAAGTACTCGATTC
          TTTCGAACACGGGGGTAATAAGCTAACCTGACTAGGTTGAGCCGCCGTCTTCCAGGACGG
          CCTTGAAAGGGTTAAGGGATGGCTTGACCAAGTGCTAGGAGAGGAGCAGATTCTAGATAA
          CCTCGAATCTGCTAAGAATCACCCTGCCCAAGTGATGCGGTGTACGGAATTCCAATATTG

          TTCGGGTGAATAGGCAGTGAGTAATAGATCTCAATATAATCGACTTGCTCTGTATTTAGC
          TTTGGCTGAGTTGGCCGCGGGAACCAACTCTCAAAATAACTGCTCAGGTTCGTTTCAATC
          TTTACACGGACGGGACCAGAACAGAGGTCCGCTCAGTAACCGCGCGAGTCCAAACAAACC
          CCTACATGGACGGGACCAGAACGAAGGCCCTTCCAGCTATCATGCGCGCTTATCCATCCT
          GCCAGATGCACAATCCTGCCACAGGGGTGCCGCGTAGAATCGTCTGAAACGTTGAACCTA
          TTAGGCTGCGTGGCTCCAGAATAGGGGCTCTCTAGGGCAAGACCCGCCTTCACGTTACCA
          GCTACCTGTTCTAGCTCGAAAATGGGACGTTCCCGCTAACTGCTCAGACCTTTAGGACTT
          TGTACCTTCTTTGTCTTCAGAGAAGGGTAGTGCCAGCAGTGGTCCAAGAGCCTGTATCTC

          AGGTACTTTCAATGACTTAGCCTGGAATTAACTAGACTGCGAACGGGCATGGCAAACAGA
          GGGAGTTAGCAACAGCTAGGCATGCCACCAACTAGATTTCGTATGAGCGTGCTAATCAAA
          GATGGTCGTATTCTGCGCGTGGAATGGCTACCGGGGGAACTCCGGCCTCAGCACATTTGA
          GATGGCCTTATGGTGTACGGGGAAGCGAAATTGAGGTAACTCTAACGTGTTCATATCTGG
          GAGGGTCGGGTTTTTAGCGACTAGTAACGCAAAGCAGCAAGAAAATGCTTTATCACCAAA
          GGGGGCCTCCCTTAAGGTAAAGAGCATCGTGGGGAGTTGTGATTATATTACTGTGCTCGA
          GAGCATTCCGTCTCAGGCGAAAGCTGGCACGGGGGGGTCCAGGAAAGTTCACTGTCGGAG
          GGGGGATACACCTTACATGGGAAGCGGCGCCGTCTGCTTTGGGAATATAGCCTCCCCTAT

          ACAAAAATTACCAAGTCAAGGCTAACATCACGAGATCCGCCCATGATAATCCCTCCATGC
          AGCATAATCACGAAGTCAAGGTTAACACGATGAGGTTTGACTCTTATAAACTCTTCACGC
          CTAATGTCCAATGTATTGACGTCATATCGATTGGGGACAACCGTCAGCCAACCTGTATGT
          CGATTGGCCAACACTGTGGGGTTATTTTGGTCGGGGTCAACCGCTGGTCAGCCTGCCTAC
          TCGCTAATTACTAACATGACATAGCTTTGCCCGCATGGGTGTCGCCCGCACTTCATCTTG
          TGATGGATATCCAATACATACCCCTCGCAAACATACGGCTATTTAATGCACTCGGACCGC
          TGGAGGGTTATGGTAGTGGGGTACCGCCGTCAAGTTTAACTTGAAATCCGACCCAGCTCA
          CACAGGATTCCTGGAGCCTGGCAATATCGACCAGCTTTGTGCGGTAAGCAACGTAGATTT

          AGGGATGATCGTAGAACTGGGGGTATCGAAGTAGATCCTGAGACTTATTACGGTGGAATA
          TAGAACAACCGTAGCATACGGGGTGCCGGCCGAGGTTTCGAATTCTCTTACGGTAGAATG
          CGGACCTTAAGGGATATTAATTCCCATAACGCAAACCACCTTACATTTTATCTCGGTTAA
          CCGCCCTTAAGGGGCATTGACCGCGCAGAATCCGTCTTCTCAATAGTTCATCCCCATTAG
          CGTACTATATGATAGTTCTCGGTTTGCGGTGAATGGAACATCTATCCCGGCCTGCGCAGG
          CGAACACTATTACTGTCATCAGCTGACATAAGTTGGAACGAGTAGTCTAGTTCCAGCCTG
          CGAGCGCCTTAATCGGTTGGTGCTCTAGGTTTAATGCGCTATTTACGAGGTCAAGTCTAG
          GGACTATCATAATAGAGCTGTAGTGATGGAAAAACGGCTTTATTACCAAGCTTGTCCTTA

          GATGTGATGGTCGACCCACAGGACGGAATACAATATCGGTTGCCAGTTTAACCTGTTATT
          CACATGATCGAGGATTTACATGACGGATTGCAACGGCGGCACCCAGCCTGCCTAGCCATC
          TATTGAGTATACGAATCGTCTATCGGTACCAACTAGACACCACGAACGCCACGGGCTACG
          CGTTAGATGTTTGAATTTACCGTTGGGACTAACTAGATACCACTAATGCTCCCAGCCACG
          AACTGATGAGTTGGGATTTTCCTTGGTGCTGGACCTTACTGAGCAGGGTATCCGGACACG
          GCTTCTCCGATTATGGGTTATCACGGCACTGAAAGGGCTCCAAACCGGAGCCCGCGTCAG
          AACTCCCCGTTCTGATCATGCCATAACGCCCTCTGAGGAACTTGGCTGCGTCTGGGCCCG
          ATGCACCCGCGTTAATCATGTCACAATGCTCAACGAAGACCGTGGATGTATTCACGCCAG

          GTTGTAGCCAAGCCAAGGTCAAAGCTACGGTGCGTTGCGA
          GTTGATGCGGAGCGAGTGCCAAGGTTACAGCGCGCTTAGA
          ACCGAAGCCCGCACAAAACTATTCGCAAAACGTGTGCCGC
          GCTGAAGCCCGCTTATAATCGTCCGTAGAGCGTGTGCCAC
          GATGGGGGCGAATCAGTGTACTCTCCGCCGACTACCTTAG
          CCTTCGGGTCGCCAGCAAGCGGTCGCGTCGAACGCTTCCG
          CACGAGAACCTCGAAACAAACATTGTATCAACCGCCCCGG
          CGCAGGGACCTTTAAACAGTCGTAATTTCAACCGCCTTTA

