 8 1000
t1        CGATAAAGTTGAGGGGTAATTAGACGCATTGTAAGAGGTGACACGATTTGCCCTCAGTCT
t2        TGGTCAGCACAGGAGACAATTAGACGCACTGTAAGAAGTGATCAGATTAGGTCTCAGCCT
t3        CGGCTAAGATCGGATGGAGTAGTTATCTGGGTGGGGGATTGCACTACCTGGGCTTACCGA
t4        TGGCTATGAATGTTTAGAGTCGCCAACTGAGCAGAGGATCCCTCTTTCCGGTTTTGTCTC
t5        TCTACGCGTATGTGCCGAACTGTAAAGTCGATGCAAGTGTCACTTATACACGTCCCTGAG
t6        TCTACTTGCATGTGTCGAATTACAGAATCACTTCGACCCTAAGCCCTACGTGCCTCGGAG
t7        CCCACAGGAATAAATAAGCTCACGACGTCGACCAAAGACTCATCCATACTTGTCCTTAAG
t8        CCCACAGGAATAAACAAGCTCACGACGTCAACCAAAGGCTCATCCACACCTGTCCTTGAG

          GCATTGTTGAAGGGTCTCGACTTGCTACAAGAATCAGCACATACTCGTTTAGTCAATGAA
          CGGATGTTGAAGGGCTTCGTTTCTCTGCAAGAACCAGCACATATTGGTCTGATCATTGTA
          AGTCTGGACTGTAGATGTGTACTATAATAAAGATCGTGATACTCGAGCCGGGCCATTGAA
          GGGTAGGAACACAGAAGTGTTTGAGGACGAAGATCCCACCACTCTTGATGAATCATAGAT
          TCAGTGTTCAGATGTTTAGACCATGGACAAATTCACTATCATGTCCACTTGACTGTCGGG
          TTAGTGTATGGTTACTTAGGTTAATGGCAAAAACACCATCACGTCTCTTTGGTCGACGGT
          ACAGGGTGCCGGAGCTCAGCCCCAAGACTAAATCTCTCTCACTTTCATTCCGCCGCTCGG
          ACAGGGTGCTGGAGCTCAGCCCCAGGACTAAATCTCTCTCACTTTCATTCCGTTGCTAGG

          TCCTTCTCGTGCACGTTGTGTTCGTCTAGACCAATTTATTCTGGTTATGTCCTCTGGCCG
          TCCTCCTCGTAAGAATTATGTTCGGTCGGACCCACTTATTTCGGTTAGGTGCTTTAACTG
          CCATCGGCCGAGGACCGGAAAGCAATGTCCTCTATCAAGTTCTCTTGAACATTCCAGTCG
          TTACCGTCCGCTGGCTGGAACGCAGTTTACTTTACCGCGCTTACCAGTGCACCCCAGTCG
          CTTCAGTGTTCCTGCCATTGACAGCCATTGTAATACTTGAAGTAATTTGTTTCCCAATGG
          TAACTATTCTTCTACGGTGGGTCGTCATAGCATCCTGCACACTAGCTTGATCTTCAAGGG
          ATCCCGTCGCACAGTGATGGGCCGCTTGTATGTTCTATTTAGTAACGCCGTTACCAATGG
          GCCCCTGCGCCTAGTGACGGGCCGCTTGTATGTTCTATCTAGTAACGCCGTTACCAATGG

          GTGTCGATTTCTAGACCACACAAGCCCGTGCCGTCGTCGGATACTTATCAATTCGCACGT
          GTGTTGATTTTGAAACTACTCTATCCCATGTCAACGCTGTATACTCATGTACTCCTACGC
          TCTTTATCTTAGGAACATAAAACGCACGTAATGCTGACGTATGCTAAATAATTCGTATAT
          TCTTAGATCCGGGGATACAAAAGACGCGTTTCGGCGCGGATCGTTCACCGGTACGTCAAC
          CATATGGCCCGTAGTCGTCTGGTGGTTGCGCTCTTATTGCACTAAAACGTAGATCGTAGC
          CGTACGCTTCAAAGTCGGCAGGCGACTGCGTTCCAATTGTATGGACAAGTCAACTGTCGC
          CGCTAGGTCTAAACTCCGTGGGCGACAATGTCTTTATCGCATGGGCGATTTCGCCGCCCC
          CTTAGGGCCCAAACTCAGTGGGCGACCATGTCTTTACCGCATGGGCGATTTCGCCGCCCC

          TGACTACCTTTATATGGGCGCGGGGGTTGATTACGAATTGTCAAAATCTGGGAATTAGAG
          AGGTCCCCTCTTCATAGTGGCGGGGACCGTCTATGGGACTTCAAATGTCCGGAATCAGGG
          ACGATTTTTTAGTAGGTCCAAAGCGATCAAAAAAGGGCCCGTCATAAATGAGTCTCAAGG
          ACCGTACTGTGGTTGGGTGGTAAAGATTAAAAACGGGCCCATCGCTATCGCGATTTAGAA
          TCCACGATCTATCGTCAGAGTAGTCAGTTAGATTCAGACGCGTGTTGCTTACGCACAGGG
          CACAGGATTTAACATACGGTCCTGAAGTTAGATTCAGATACGTGTTGCTTGCGCACCGGT
          TATAGTATATAAAGTGAGTCCAGGAGGTTAGATTCTGATATGTGATCCTCATCTACGAGA
          TATAGTATATAAAGTGAGTCCTGGAGGTTAGATTCTGCTATGTGATCCTCATCCACGAGA

          TAGGCAATATTGTTGGGTTTCGGTCACAGCATGAGAATCGAATTGGACAGTCTCAGCACA
          CAGGCCATATTGTCGGATTTCACTCAAAACACAAGAATACACTCGGACTATCTCGTTAGG
          GAGAGGGAGTCACTAACTCGTCGGGTCGAAAGCGGACCAGAGTCAACTTGCCTAGTGCAG
          TAGGTGACGTTCCAAATTCTTTGAGGCAGTAGGGGATCGGAGTATATTTGTCCTCAGTAG
          GAGCAAAGGCTGCCGATTTAATACGCTGCGTAGACACCAAAGTCAAATCTTGCGGGTTCG
          GAACTAGAGCCGCTGTTTTAACACGTTTCGTAGTGACTGAAGTCAAAATTCGCCAGTCCA
          AACATCGAGCTGCCTACTTAGCACGCCCAGTCGTCAACGAAGTTATGCCAGGAGAATTTT
          AACACAGAGCCGCCTACTTAGCACGCCCAGTCGTTAATGAAGTTCTGCCAAGAGAATTTT

          TTGTTGTCCGGTACGGTCGGGTGATTCAAAGTACTGCTCAAAACCGCTCAGCCTGCGGTC
          TGGCTGTCCGGTAAGGATGTTCGATTCAACGTGCCGCTCATTACCGCTTATTACGCGATT
          ATATCATTCGTGCCACGAAGCCGAGACGAGTTATCGGCTTGTCGCGCCAACCTAGCGCTC
          ATATCCCCAGAGTCTTAGAGCCGGTCTTAGCAACTGGCTCGGCCTGATTAGCAGGTGTTC
          CTCCGAGTCGGCTCGGGGGATAAGAAAGTATAGTTGGTAAGGGCCTTTTACCCAACGCTC
          CTTCGACTCGGCTTGGGGGCCAATACAACGCTCTTGTTAATGGTCTATTATCCCTCGCTA
          CGCCGACTAAGCTTCGGGGTACGTATTACGTCCCTGGTCATGGCCCCCCGCCTCGCGTCG
          CGCCGACTAAGCTTCGGGGTACGTATTATGTGCCTGGTCATGGCCCCCCGCCTAGCGTCG

          CAGGACAGAACGTTAGACGACGTTATAAGGTTCGGCGAGCTTGCCGCATACGCTCAGAGT
          TAGGAACGTTCGTCAGACGGCGTTATATGCTTTGAAGGGCTGGCTGTCAACGCTCAGAGT
          ATGAAACGGGAGGTCGGAGTTATAATGGGCTGGATCCGGCACAGTGCATAATCCCGGACG
          ACAAAGAGTGGACCCAAAATCATATAGCATTGCGCCTCGGTTACCCCGTGTAGTCGGTGG
          ATGTAATGCACCTCCGGGGTTATTGATGGCACTTTTATACCCGATAACGACAGACTACAT
          CTGACATGTACTCTCGAGGTTATTGCTGACACTGATGAGCTTGGCAACCATCAATCACGC
          AAGAAACACGTCCTTGTGTTTATTCCTATCGTCACCCTGCCCGATAGACATCAACGGTGC
          ATGAAACACGTTTTTGAGCTTATTCCTATCGTCATCCTGCCCGATAGACATCACCGGTGC

          AAGGCCCATTTAACGGCTCCTCGTAATAGCGAACGCTTCCTCAACGGTTTGTCCCCACGA
          AGGGTACACTTATCCCCTCCCCATCACCGTCCCCGCATTCTCTATGCTTCGCGCTCACGG
          TTGATCGTTTTAAATGCGTCAGGCCTAGGCGACTTAGGTCAGCCCGCACCTCTCGTGGGG
          ATGACGGTTCTATGTGCGCTCGAACTAGATACCTCACGTCATGCCGTACCACTTGTTAGG
          ATGTTGCATCCAGATATGCCATACTCATACGGACAGGACCAGATCCCCTTGTACGGCGGG
          ATGTTTTATCCAGATATGGTAGGCTTAATTGGATAAGGTCCGGTATCTCCGTGCGCCGGT
          ATGCCGCTTTCAGGCGCGCTATACATAGACGGACAGTCCGGATTCCGCCTGAGCGCTAGT
          ATGCCGCATTCAGGCGTGCTATACCTAGACGGACAGTCCGGAGCCCGCCTGAGCGCTAGC

          ACATTTATGTGAAATAACGCGTAGTAGTTAATTTTAAGATGTCTGACGCGATCGCAGTAT
          ATACCTATTTGTAATAACGCATAGTAGATAACTTTATGATGTCCCACGAGCGCGCGGAAT
          GGAGTTAGATTAACTCTCACTAAACGGTCATTTCAGTCAGCAATTTTGCAACCCCGGTGT
          AGCATTTGATATAGCTCCGGAAAGCGGCTTGGCTAATGAGGAATCTTGCGGCTCTGACAA
          GCCTCATCTCGCAGTCGTACGCAACGATTACTTCAACGGGCTCCTCGATCGAACCGGAGC
          GCCGCATATCGCAGTCATGCGCAAGGACTCTTCCTTAGGGATCCACGTTGGCTCAGAAGC
          GCTACTTATCGCAACGATACGCAATGTACATCTCTAAGAGTTCTTTGTCTGATCAGATTC
          GCTACTTATTGCAGCGATACGCAGTGTACATCTCTAAGAGCCCTTTGTATAATCAGATTC

          CTCGGTCTCGTGTGGAGCCGCTGTCGGCTTCATTGAGATATCAGTGGAGCACGCCCGAGG
          CCCGGCCTTGTGTAGCTCCGCTGTCGGGATCACCAGGACATCATTCAAGCCCATCTGAGG
          TTGCACTCCTCAGGCTTGCATCGAAGAAAATTCGGGAGGTAATGTCAAACGTTTCCAAAG
          TTTCGGTCTCTATGTGCCAACCTAATAATCCCTAGTCAGCACGGCCCAGCGCTTCTGAGG
          ATCCGCCCTCAAGGCTACCCCTGAGTAGCCACTTGCGCCAGATGCGGAACGCGAATTAGT
          ATACATTCCCAAGTTCATCTCCAAGCCGTTACCTGCGTCAACTGCGTGACGTGAATGACC
          AACTGTCCTCTAGACTATTTTTATGTCGCTTTTTGCACATTTAGTATAGCATGATTAATG
          AACTGTCCTTTAGACTATCTTTATGCCGCTTTTTGCACATTTAGTATAGCATGATTAATG

          GGGAGAACTGTGTCGTCTGCAGTGCTGACAGAGCAGATGAGAAATAGAAACTAAGATGCT
          GGGATAAATATGTAGTTCACAGTGGTGGCGGAGTTGGTGAGAAGTATACACTAAGATGCT
          GTAAATGTCTGCCAGTATAGAATGGTGCTCTAACGATTCGTAACCCGCTATTGATATACT
          GACGATTTTGACGAGGCTGGACTGTCGTACTGATCTATAGCAAATCGTCCCTGCTATCCT
          AACGTCTCCAGACGATTCGACGTGGAGGGTCGGTTAGCGACACGCTGTCACTTAGCTATA
          AGCGCCCGCCGGCGACCCGGTGTAGGAGGCAGGTAAGAGGCACGTAGACATTTAGCTATT
          AGCTTTTTCCGGTGGTCCTGCGTGGGGGGCAGAGGGACGACAAGTTTACCTTCAGATGTT
          GGCTTTTTCCGGTGGTCCGGCGTGGGGGGCAGAGGGACGACAAGTTCACCTTCAAATGTT

          CAGTTGTATGAGAAAATGGTTACGAATGGGGAAACAGCTGGGGTGGATTTATGTGTCTAA
          TAGTTGCTTGAACAAATAGTCACATCTAGGAAAAAGGATAGGGCCGAATTAGAGCCCTAA
          CGTGGCTAAGTGCAAATAGTTGTGCGTACGGGGGGTTGTCGCTTTCTCTTCAAAGCTCCC
          GGAGACCGATTAAAAATGATAGCGACAAGGAGGGACCGTAATCTCGAATTAAGTACCCTC
          AGATCCAACGTGGGGGAGAACTACGACGGGATCGCTCTTTTGACTGATATGCGCCCCGTG
          CGACTCGATGAGGGGAAGTTGTCTGACAGGGACGTAAGTTCGATTGACTCGCCCCCCGAA
          CAATACGACATTCGGAATGAAACGCACATAGTCGTAAGACTGACTGACCCGCGCTCCGTA
          CAATACGACGTGCGGAATGAAATGCACATGGTCGTAAGACTGACTGACCCGCGCTCTGTA

          AGGGGCCACCTCCTGAGGTGAAGGGTTATAAAACTATACCATTGCGAAGCGTCATTTACG
          AGGCGCTACCCTCAGGGGCGAAAGCTTATAAAATCGTCGCATTACGAAGCGTTATATATA
          CCGAGTTCTGCTTCTGATTAAAAATTAGGGGAGACATCTGCTGGTATCATAACCCCGCTG
          TTAAACTTCGCTCCAAATTATCGACTAACGAATATCTTCACAAGTATACTGTTCTTACGA
          TCGATGCTGAACGCAGGCTGCCTTGCGCATGCGTTCTCTCAGCGAGGCAGTCTGCGTAGG
          TTGCTGCTGCACGCAGGCTACCTTGCAGACGTGCTCTCTTATCCCTGACGTCCACACAGG
          TTGATCTTAACCATAGGCCTGTATCACGCGGTCTTTTTTCGTTGGGGAAACCCACATAGG
          TTGATCTTAACCATAGGCCCCTGTCATGCGGTCTTTTTTCGTTGGGGAAACCCACATAGG

          TTAGTCACCCCGGGAATTTCCGCAGGACTAGAGGGATCATCCAGTTGCAACTTCGCTCAC
          TTAGCTATCTCGGGAAGTTTCGCAGGACAAGAGGGAAAATCCCGTTGCCATTCCACTCGC
          AATCGTGTCCACGCAATCGATACGTTATTGGGCGGTTTCATCGTCCCGCGTATCATATTT
          AACCTTATTCTCACAGTTGTTGATTTACCGCAAGGTTGTTTTTGCCATCATTCCAGATGT
          TATCATACTACAACGGACACAGTGCGGACAAGTTCACTAGTATGTTAAAAGTCCGTTGTT
          TCTACTACCACCACAAACAGTACGTGGGCAAGTCATCTTGCCTATTAGGCGTCTGTTGAT
          TATCTTACCAATACGGTTAGAGTGCGGACGACCTATCTTGTCTGCCGGGTACCTTCTTTT
          TATTCTACCAATACGGTTAGAGTGCGGACGACCTATCTTGTCCGCCGGATACCTCCTTTT

          TCGGCAACACGCGGACATCTTCTGCGATAACGCGCTAGACGTAGCCTACGCATACTTATT
          TTGGTAATACGCGAACACCTCCGGCAGCTACGCGTCAAGAGCAGTTTACGCAGACCCATC
          GCCCGAACGTATCTACTTTCTCGTCAAGGAACAGTGGAGAGGTATTCCTTTGTGTTTATT
          GTACAAAAATACCTACGCTTTTGCTTGCGGAGAGTGGTTAGCAGTCCAACCCCACTCCGC
          AGGGCAGCATATCTCTCTACCGCGCCGCGTGTAACACCGGAGGTTCAACTGTCAGTAGCT
          GGTATAGCGTAAGCCCTTGCCATGCAGTGTGTATCTGCAGAGGTTATACTGTTGCTAGCT
          AGGACCGAGTGTGCTCACACTGCGTCTCGTGTAACAGCGGAGGTTAAATTGTCTATGGCT
          AGGACCGAGTGTGCTCGCACTGCGCCTCGTGTAACAGCGGAGGTTAAATTGTCCATGGCT

          TCTGGCGCCGTAGGGGCTCAAATGGAGAAAACGGAACTCA
          CTAGGTGTTGTGGGTAGTCGAATGGAGAGAATGCAACCAA
          CCTGGTGTAGATAGCGGCTCTATGGTTTCAGTAGCATCGG
          TTAAGAGTTGTGAGCCGTTCCTTGGTTTTACCGGTAACAG
          CGATATACTGTGGCAATTTCAAGCGGTCATCAGATGCGTC
          TGATATACCGCAGCCAACCCTACAGGTCATATGGTGCCTC
          CGACACACTGTGGTAATTTCCCCGGGATATGTAGTGTCCT
          CGACACACTGTGGTAATTTCCCCGGGACATGTAATGACCT

