 8 1000
t1        AAAACGAGGAATGACCAGCGAGTGAGAAACGGCCCGTTATTCTAAGTCAATGGCGTTAGA
t2        AAAACGAGGAATGGTCAAGGAGTGGCATACGCCTTGTTATCCTAAGTCAATGGTATTACA
t3        AGAACAAGGAATGCACAGCAAGCGATAAATGCCCAGTTACCGCATCTCGACATTGTAAGA
t4        AAAACACGCACTGGATGCCAAGTGGCTGACGTCCCGTTATCCCAGGTCTATACCGTTACA
t5        GATACCGTTGTCCAACTACGAGCGTTTCAAAACTCACTATAACAGTAAGTAATGGCCAGA
t6        GAACCCCTCTTAGGATTATGAACATTTGATGATTCGCTATTACAGCTAATTGTAGTCGGG
t7        GTGTTCGGTCATAGAAAAAAGGTGCCCAAAGGCTTGACGTGCAGCCCATTTATCATTAGA
t8        ATGTCTGGACGCGGAAAAAAGGTGCCTAATGGCTTGACGTACAGCCCATTTATGGATAGA

          TCAAATTTTGATATGCGCGAGATTAGACGATTGGACTCTCCATGATTTATCGGGGACGGT
          TCAAATATTGATGTGCGCGGGGTTAGACGATTGGACTCTCCGTAATATACCGGGGACGGT
          TTAAATTATAATATGCGCGGGGTTAGACTATCAGACCGTCCGTGATTTAAACGGGAAAAT
          ATAAATAACAAAATGCGTGGGATAAGAATATCGACCTGTCTATAATATGTGGGGCAGCGT
          TGAAGGACCGACACACGCGCAATAGGGCTTTCGTCCCGTTTATAGTCTCCAGGAGTGAGT
          CGAAAAATTGACATCCCTGCAATGGGTATTTGTCACCGTGGATGGTCTCTGGAGACACTT
          AGTTTAAGCGGTATTGACGCTAGGGATCCTGTCCCCAGACCCTGTGCAATGGAGACTGAC
          AGTTCAAGAGACATCGACGTTTGTGATCCTGCCCCTAGGCCCTGTGGAGTGGAAACTGAC

          CATACATGTGCTCATGCTGAATCAATACACCGAGCGACCCAAGCCCACATAACAACTGTG
          CATACTTGCGCTCGGTCCGGATTAATACATCGAGCAACTTCAACCCCCATAATAACTGTG
          CATAGGCGCGTTCAGATGACGCTCGTCAACCGTGCAAGTCTCACCCACACTGTAGTCGGG
          TACACGTGAGACTAACCTAAAACAATCTACCACCCAATACCACCAGACACTATAATCAGG
          GAGACGAAATGTCCATGGTTAGCTTTACACCTTTTTGCATCGGATTGGTAAATGACCCAG
          GAGACTAGATACCCCTAAACGATTACCCGACGTTCCATATCAGCTCGCACTACGGCCCAG
          GTTTACCGATTTCTGTGTATCACACTGAGGCTGTAGCTCAGACATGCATCATTGTCCGGG
          GTTTACCGACAACTGGGTACCATATTAAGGCTCTGGCTCAGACATGCAACATTGTCCGGG

          GTAGACAAAATCGACCTGTACATTGGTTCTCACCCGATGCTCTTTCTCGGCGTGACTTCT
          TTGGACAAAATCTACCTGTACTTTGGCTCTCATACGACGCTCTTTATCGGCATGTATTCT
          TAGGAATATATACACATGTACATTGCGTTCCGCCCGACGTATTTTAACGGGACGACCCCT
          TGGGATAAAGTAAAGCTGTATGTTGGGTCATGTCGGACGAAAACTCCTGGTACGTCTTTT
          TAGCGCATCATGCTACCCCATAACGGCGTACATCTCTCGAGATACTCTGGGACCACCGTT
          CGGCAATTCCCACCACCCCATACCGGGCTTTATCCGTCGCAGTACTTCGGAATCGCCGTC
          AAGAGTACCTTATAGTGCTGATAACGGTATATACTAATTCACAGTTGTGGAACCGCGGTC
          AAGAGTACCTTATAGTACCGATAACCGTATATACTAATTCAGAGTCGTGGAACCGCGGTG

          AAACTACTCCCATTGCCGATCTACTCCAGGGATATGTACCGGTAAGAACAATCGAACCTC
          AAACTATACCCATTGCCCATATGCACTAGAAATTTGCACCGGTAAGGACAATCGAACATC
          AAACCACTCCCATCCCCAATCTGCATCAGAGATATAGGCTGGTAGGCGCCATTAAGACTC
          AATCTATTGCTACTGATAACCCGCTCTGGACATTAGTGCTGGTATAAGCGGGCGAATCTT
          ATCGTACTGTTACAAGGCATCTCGGTTGGGATCAAATGCTTGAGGGCTACAGAAAGTACC
          ACCTTACTCTTACCAAAAAGTCGGGGTGAGATCGTATATTCGTAGGTTAGTGGGATCTCT
          ACCAGATAGAGGATGAAATAGCGATTCCGGACTGCGAAGTTATTGTCAAGAGTGGACCTT
          AGTAGGTAGAAGATGAAATAGCGTTTCTGGATTGCAGAGTTCTTGTCAAGTGTGGACCTT

          TTGCTGATGATTGTCTCGTTTCCGCTCAATAATAGGTCTGCGCAAAATGCCGTTCGCCAG
          TTGCTGAAGATTGTCTTGTTTACGCTCAGGATCAGGTCTGCGCAAAATGCCATTCACCAG
          CTGCCGATCATCGCTTCATATACGCTCAAAAAAGGGACCACGCAAAATGCCATACGCCAG
          CTGCTGACCATTGCCTTGCCTAAACGCAATGACGGAACCGAGTACAATGCCAGTCGCCGG
          GGACCGATATACCACTCAGCTGTGCCCGATTACGGAGGTGCTCACTGCTAGAAAGATTAG
          CACCCGAAACTTTGCTTAGTCATGTGCAGCTAACGGGTTGTTTAAAACCATGGAGGTTAA
          TCTTTAATGAGCTCTCTGCTTCCCCATAACACAGGCACTGCGTGGGTTCCTGGCGTTCAC
          TTTTTGATGAGATCTCTGCCTCCGCATAGCACGGGCACTGCGCGGGTCCTTGGCGTCCAC

          TGTTATATCTAGTTCAACATTGAGAGGTTACCTAGGGTGACCATTAGAGCGTTCATGTCC
          TGTGACATCTAGTCCAGGATCGGAGAGTTACCTAGGATGATCATTAGTATGCTCATGTTT
          TATTATACCTAGTCCTAACCGGAAAAGTTACCCAAGACGAACGGCTGAACGATCACGATT
          AGCTATATCTAACCTCCAGTGGGAGAATCAATTAGTATGAAAGTCAGTCTGTTCATGCTA
          CCTTGACCATGGGTCTGCTGCCGGCAGCAAATTAACATGTCTGAACGGACCCTTAAATTT
          TCTTGGATATAGTCCCCATGACCAGTGCTGTTTAATCCGTTTGTCGGAATACTAAAGCTA
          CGGTGCCACTCCTACCCAAGTTGAGGGTTAAACCCAGCGACACGTTAGGGGCGGTGAGCG
          AGCTGCCATCTCTTCCCGAGTTGAGGGTCAGACCCAGCGACGCCTTAGGGGCTGTGAGCG

          GTTGTAATTCCTCTACATGAATGGCGTATGCGCTTTGAACCAACGTGCGCCCGAACACAA
          GCTGTAGTGCCTTCATACGAATGGCACATGCGCTTTGAACCTACGTGTGACCGTAAGCTA
          ACTGTAGTGTTTTAATATGAATGGCGCATGCGCCTCGAACCAATATGAGAACGAATACTA
          GTTGTTGTGCTTCAATTCGAAAGGCGTATGTGCTTAGAACCAATATGAGGACCGGTGAGA
          CTTTCAATAACCCCACATGCTGTGTATGTGCTGTAAGGATTAACCCGAAAGTAGGCGACA
          CTACCCACAGTCTAATACGCTGTGCGTCCTCAGAAAAGGTTAACTTGAAAGTGGACTATT
          TTCTGAATCCCTCACGGTACGGGATTCACTTCTTTTGACTGTACGTAGTACAGGGTTTAA
          CTCCGAAACTCCCAAAGTACGGGATCCACCTCCTTTGACTGTACGCGTTACCGGGCTTAA

          CGCTGGGACGTTCTCAACCTAGATGACATAGAACAAAATGCGCAGTTCCCTAGAATTCTT
          CGCAGCGACCATCTTAGCCTAGACTGCATAGAACAAAATGCGCTGGTCCCTAAAATTCTT
          TGCAGCGGCCTTCTCGGACCAGACTTTACAGAACTCAAAGCGCTGTTAATCAGCGTTGTT
          CACTGCGACGCTTTTGGTCATGAACACATTGCACAACGTGCGATACATCATTGCATTCTT
          CGATAACGCACTCCAGGCTTAGGTCACTCACATCCCCTCGACCCAACACATCGTATTCTT
          CATAAAAGTGATTTAGGCTCTGGTCATTCACATTTCTAGAGCCCGGTATTTTCCAATATG
          ATTCAATGGGTCATAAGTCCCTCTTTAACTTGAGCCCCACGTCCCTACCCCGTCGCTGCG
          ATCCAATGGGTCACGAGTCCCTCTTTAACTTGAAACCTACGCCCCTACCCCGTCGCTGCA

          GCACGAAGTCTATTTAATTTTAGCACTGCCGGCTACACAGACCATTCCTGCATAGGGAAC
          GCATGAAGTCTACTTAAATCTAGCATTGCCGGCCAAACGGACCATTCCTGTATAGGGAAC
          GCGTAGGGTCAATTTAAAACTAGCATTATCGGGTACCTACTTCATTCCCATATAAGGGAC
          CCATGGGGTCGATTAGGGTCTAGTATTGACGGATAAGCAGTCAATTTCTGAATAAGGGAC
          CTCTGAGAAAACGCCAAAGTAAATAGCTTTGCCTTCGGCAGTTGCTCCAGTAAAGGCAAG
          TTCTAGGCATACGCCGAGTTTATCCCGCCTGCTTATATGTACCGTTACCGTGTGTGGAAA
          GCGATGGTTCTCGCAATAACGGACACAGGCGGGCGCACGACCAATGTCAGGCTGCAGCAG
          GCCATTGTTCTCGTGACAACGGACATATGAGGGTGCACAATCCAAGTCAGGCTGCAGCAG

          CAGAAGAGTCGACAAAAGATCGGTTAGGTTAATACAAAGCGAGGGGCAAGGAGAAATTTG
          CAATGAAGTCGACAAAAGATCGGTTGGCTTAATGCAAAGCGAGGGGCGGGGAGAAACTTG
          CAGTGGAGACGATGAAAGCTCAGCTGGGTTGATACAGAGCGAGGGGCTAGGGGAAAATTG
          CGGTCAAGACGGTGAGAGCCCAGAAAGGATGACGAAGTGCGAAGGGCAGGGCGAAATGTA
          TAGTTCGGTACTCACCGGCCTGGGGCAGTCCATAAATGACTCTCGGCGCGGTGTAATTAG
          CGGTCCGGTAGACGACTGCACCGGAGGGGGAGCAACTAGTTAGAGGCGCGAAGAAATTAG
          GGAACGGGAGGGATTCGGTTCGGGGGGAGACGTATCTTGTCCGTCGCTTGTGGAAGTTGA
          GGAATTGGAGGGATTCGGTTCGGAGGCGAACATATCTTCTTCGTCGCTCGTGGAAGTTGG

          TACATCCTTCCAGCGGATGATGAGCGGTGCATGAGACGGATAGCATGGTGGTGCCCATTT
          AACTTCCCTCCATCGGATGAAGAACGGTGCGTGAGATGGATAGTATGGTGGTCCCCATTT
          TATTTCCTTCCATCGGGCGAAACGCGGTGCCAGAGCCGCGTAGTACGGTGGTGACCATTT
          TATTTCCTTTCATCGGGTGAAGAGTGGTGCTAGAGCCAGATGGTATAGTAGTGCTACCGT
          TACTTCCTTCCAGCGGGCGAGCATCGGCATGCGAACTAAATTACACGGTCGTGGCACCTG
          CGCTTCCGTCCAGAGAACAGGCATCGGCCTGCACATCAAATCGATCAGCTGTGCCAACTG
          TTGATCCGTGCCAATCCTGGGCGCGGATCGCGGGGTTGAAAGGTATGCTTGATCCGAGGC
          TTGATACGTGTCAATCCTGGGCGAGGATCGAGAGGTTGACTGGTGTGCCTGGTCCGAGGC

          ATTTCTTACTGGCGGCAACTTTGTAATCACGCCACCCGCAAATGTTTGTCGAGACGTTGA
          ATTTTTTAATGGTGTCATCTTGGTAATAATGCCAACCGCACATGTTTGTCGAGACGTTGA
          ATTTTATAATGGAGCCATCTTGGGAATCAATCTACCTGCACAGAATTGCGGTGATGCAGG
          ATTATGTAATGTCGCAGTCTTAGCACTTGTATCAACCGCATAGGAATGTTGTGACACAGA
          CAGTTTTTATAGTGACATCCTCGCGACTAGATCACAAGTCTAGTGCTTTTGCGCCGTGGG
          TGTTCTTAGTTGTAATCTCTCCGCAACCGGCTCAAATGTCCAGTATCATTGCGCCATGTG
          GACTTAATTACAATTCGGCGTTGAATTCAAGTTAGTAGGAAAAGAATCCTTTACTCTAAC
          GACTTAAACACAATTTGGAGTAGCCTTCGAGTTAGTGGAAAAGGAGTCTTGTACTCCAAC

          CTTAGGCTATAAAGCCCGCACGATACATCGTTTCGAGGGGGTCTGTCGAAAAGTAACGCA
          TTTAGGTTATAAAGCCTGCACGATTCAGTCTTTCGGGGGGGTCTGTCGGAAGGTACCGCA
          CCCAAGTGCTAAGCCCCGCACGATTCGCCACATTGGGAGGGTCTGTCGAATAGCCATGCT
          TTCTTGCTTAAAGACCTGGGTGCTTCCCCATTTCCAGTGAGTCCGAAGGGTAATAATGCA
          TCTTCTTTAAGAGCCTCCCGCGCCCGATATATCCAAGTGTATCGGTCGGCAGCCAACGTG
          GTTCATTCATGGGGTTACCAAGCCCTATCTTTCCACGTGTATCGGCCGACGAACCCCGGG
          TTCCCTTCGATGGATGCATTATGACGTCGTCGCCTCCTACCATCATTCGGCCATGACATG
          CTCCCTTCGGCGGATGCATAAAGACGTTGTCGCCTCCAACGATCATTCGGCCATAACATG

          CCTTACGGATTAATGGACAGTTGATTTAAACTGTCTTGACATGACACTTGCCTAGTGCCA
          TCCCACAAATTACCGGATGGTTGACTTGAGCTCTCTTGACATGATACTTGCCTAGTGCTA
          CCATACAGATTACTGGATTAACTATCCAAGCTCTGGGAACCTGACACTTGCTTAGAGCCA
          CCTTATAAATTTCAGGGCTACTGCTTTAAGCTCTCGGAACATAATATTTCTTTAACGAAA
          CACCCCAATGTGTTCGAGTGTCTACTCCCTTTTGGGGAGAATAACCAGCAGCCGGCTGCA
          TACCCCAGGCCGCCGGAGTGTCAATTTGGGCAATGGGAGCGTAAATCCCGGCTGGATATA
          CCTTACAACAGGGCAACGATGCGATTTCCTGTAAATGCGCGCGAGCTGAGGCGCTGAAAG
          CCTTATAACATGGAAACGTCGTGATTCCCCGTACATGCGTGCGAACTATAGCGCTGAGAA

          CGCAAACACAAAAAGGCGTGGGAGGAGGGCTTCTGAAGTCCGTAGCTTCACTCACGAGGA
          CGGGGGCATTAAACGGCGTGGGAGGAGGGCTTCCGAAGTCCGTAGCTTCACTCACGAGAA
          CGCAGGCTTCAGCCGGGTCGAGTGGAAGGATTCCGCTGTCCGTTGTTTCATTCACGAGAA
          GACAGGCACTAAAGGGCGCAGGGGAGGAGGTTTGGAAGTCTGCAGTATCAATCACGAGAG
          GAGTAGCGACGTGGGATAGTTGTGTGAGGACCCCGTCGCGGGTAACTATTGGTAGGTGAG
          GGCAAACGGGGCAATCCGGTAGTGTGTAGGTCTTGTCGTAGTTAGATCATGTAGGAAAAA
          GTCCTGTCTAGTTCCCCGAGGTGAGCAAATGAGACCTATATATCGGAAGTATGAGAGGAC
          GTCTTATCTAGTTCCCTGCAGTGAGGAATTGGGACCAAAATAATGGAAGTACGAGTGGAC

          TGTTTAGTCTCAGCCAGTCGAAGGCTATCCGTGTGACCGA
          AATTTAGTCTCAACCGGTCGAAGGCTACCTGTGAGACCAA
          AACTTAGCCCTAGCCAGGCAGAGGTTACCCGCGTGACCAA
          GACCTAGTTCAAGCCATCCGGCGGTCACGCATGCGACCAG
          CATCTAGTATGAGTTACTCGATAGCTATCCGTGCTACCGA
          CTTACAGTAACGGTTCCTCCGGAGTCGTCAATCTTACCGA
          CCCGTATCTATATTCTACAAAAGAGTATACGCCCATCTTA
          CCTGTATCTACATTCAATCAAGGAGTATGCACTCCTCCAT

