 8 1000
t1        TATCGAAGAGCTTACTTGGACCATGGGTAATCTGTTCTCCTTCTTTGTTCCAGCGCGTAC
t2        TATCGAAGAGCTTACTTGGACCATGGGTAATCTGTTCTCCTTCTTTGTTCCAGCGCGTAC
t3        TATCGAAGAGCTTATTTGGACCATGGGTAATCTATTCTCCTTCTTTTTTCCAACGAGTAC
t4        CATCGTAGGACTTGCTTTGGTCATTGGCACTCTGGGCCCCCGTTTCCCTTAGGCACGTAT
t5        CAACAAGGGATCCACTCTTGCAACAGATACTATTCTCAAGCTCGTATTAAGAGGGCGGAC
t6        TCCTTAAGGACACACTCTGCTGTCGGGAGCTACAATCTACTGCGGGTCATTAGCGGCGAT
t7        TCACAACCGGCTGACTTTCTTAATAGACTTAGTGCCTCGGCGTTGCGATTAAACGTGTGC
t8        GACCTATAGTAGGATATAAGTCGCAAACCTCTTGTGTTATCCATGGAGACGAAGGTTTGC

          CTATTCTCGATCACTCAGATCAACCAGAAACTCACCGTCTATATGGTGGTTATGTCGCGT
          CTATTCTCGATCACTCAGATCAACCAGAAACTCACCGTCTTTATGGTGGTTATGTCGCGT
          CTATTCTCGATTACTCAGAGCAGCCAGAAACTCACTGCTTTTATGGTGATTATGTCGCGT
          GTTTACCTGGTTACCCGGATTGAACAGCAGCTCATCGATACTGAGGCGACTAAATGGTAT
          GCTTACTTCCTAGCCAGAGTACAAGAGTTGTTCCCCGTAACTCGGCCTGCCGTGCCTGAT
          GTTCACCTACCTGCTCGAATGAGAGCCCAGACCTCTGCAGATTGGCTAGCGGTGTAGGCT
          TTGGGTTGAACCATACGATTGATAACACCGTTTGTTGCATATATGCGGCCTGGTGCACAC
          CCCTTTCCTCACGTTCTAGGGAGCGGCCCGCCGCCTTTTGGTAAGATAAACGAGCCACCT

          ACACCACTATATCATAGGCCACTGTATTTTCATCTCTTCTTTCCCGTAGATAACCCGGAT
          ACACCACTATATCATAGGCCACTGTATTTTCATCTCTTCTTTCCCGTAGATAACCCGGAT
          ACACAACTATATCATAGGCCACTGTATTTTCATCTCTTCTTTCCCGTAGATAACCCGAAT
          TCGCTTCAACACTACTGCATCCGGGAGCCCGATCAAATCCTCCCCGAAGCTAAGTTCCAT
          CTCATCTCGTCAGTACAGGCTTTTCACTCTCCCCTGTTCTTCTCCGCTGCCACGCTCTAT
          CTTACTACAAGTCCGGGACTTCGCCACCTTTATCAAACTCTCCGCCGGTTAAAGGTTTGT
          CCTATATCCCGCGTTTACATGGTGAACTCCTGTCGTTTGTTTTACGAGTTTAAGTTTAGT
          ATGTCACCTAACCCCTAGACGCAGTGTACGGACTCTTGTTTCGGTGAACAGGTGTCAGAA

          ACGTGATAAAAGTGTATAGGGTGACCACTATTGAACAACCAGTATTCAGTCGCCATTGCT
          ACGTGATAAAAGTGTATAGGGTGACCACTATTGAACAACCAGTATTCAGCCGCCATTGCT
          AGGTGACAAAAGTGCATAGGGTGACCACTATTGAACAACCAGTATTGAGTCGCCATTCCC
          GCGTCACAAGAGTAGTCGTAATGGCCATAACTAAAAAGTTAGTTAGGAGTCGAAATTATC
          TAATGATGCTAGTGCACAAGATACTTTCCACTGACGTACTGCTACTGGGAAAGTGTATCG
          GAGCGAAATATGTACAGGCAAGAATTGTTAATAGACCGCGACTACCAGGGAGGTTGCGTG
          CTGAACTGCTCGCGCGTAAGTCTTCTGCAAGTGTAAGACATATGTGGGAGTACCGGTACG
          CTATCACTCGTGCATAATATACGTCCCTTGCTACGATACTCAACTGAGACCCCCCCCAAA

          CGCTTGTCATTCCCGCAGCCGGGCATGTCAAGACAGAGCAGCACCACCTATGTCTGTATC
          CGCTTGTCATTCCCGCAGCCGGGCATGTCAAGACAGAGCAGCACCACCTATGTCTGTATC
          CATTTGTCATTCCCGAAGCCGGGCATATCAAGACAGAGCAGCACCGCCTATGCATGTATG
          CCTTTAACATCCACGTAGCAACGCGAAACAGCACAGAGCAATGTTGCATAAGTTTGGGTA
          CTTCTGACAGGGGCACAATAAGTGAATTGAGAATAGTGGACCGTCGCGAGTGCGGATGTC
          AGTCACTTGCGAAGATGGCATTGTGCTGTGGACCGGCGGCATGTCTGGCGCTCACCGGCT
          CAGCTTACCCATGTCTGGCGCGAAGAGTTGAAGAAGTAGGGCATTTTCGCTAGTTAGCAT
          TTAGCAAGTTTTACCTAACGAGGACAATCTCAATAAAAAAGTTGTGCTACAGCGTAGATT

          GAGGGAGCTCGACCCTGCAGGAGGTGTTCCTGAGCCCTGCATAAATATGCAGGCACCGAC
          GAGGGAGCTCGACCCTGCAGGAGGTGTCCCTGAGCCCTGCATAAATATGCAGGCACCGAC
          GAGGGAGCTGGACCCCGCAGGAGGTGCTCCTGAGCCCTGCACAAATATGCAGCCACCGAC
          GAGGGAAACCGATTTCCCGGAAGGCTTTTCTATTGCCTCCATAAGCCTGCGACACATGAC
          CAGTGGGCGTAACCTAAGCGTATACGACCGTCGGCGCTGTGCAAACATAAGCTGTTCAAT
          AAACGCTTACGGCCGTGGCCGCCGCGCATAATCGGGGTGCATAGCGACAGTTTGCTTGAT
          CTCACGTGAATACCTCGGGGAATGTCGCACACCCCACTTGCTAGCAACGGCACACTTTAA
          GCACCTGTAAAAGGTTGGTGAACATGTGTGACAGGCCTGGTGAGCAGCGAACAACGTCAA

          TAGGCTTCCTAAAAAGGATGCTGCATATACGCGGTCTTCGAAGATATGCAAGGGGGCGTC
          TAGGCTTCCTAAAAAGGATGCTGCATATACGCGGTCTTCGAAGATATGCAAGGGGGCGTC
          TAGGACTTCCATAAAGGATGCTGTATATACGCGGTCTTCGAAGGTATGCAGGGGGGCGCC
          CATAATTTCTCAAACCGACACCGTAAACACGTAAGTCGCAAAGTTAGGGCTGGAGGCCCA
          CAGATCTCCTACGAAAGTGCCGATGCAAATAATCCGTCAGGCGTACCGCACCGCGGTGTT
          AGGACAGGTAGGCACTGTCTCCAGCTGGAAATCGGCCATTAGAATGGACGTCAAACACCT
          CCTGTAATGAACCAAAGTCTCCTCACGCTTCCCCAAGATCTCACCCGACGGTCTGAAATA
          AGTGTCCTTCATAATAACTTCGATACCCACCTGTGTATAAACGTGCAAAATCAAGAGACT

          CCCGATAGTGTGCCGGACCTATAGTTATGTGCTACCAGTGCAACCGACACTTGTAGCGAC
          CCCGATAGTGTGCCGGACCTATAGTTATGTGCTACCAGTGCAACCGACACTTGTAGCGAC
          ACCGATAGTGTGCTGGACCTGTAGTTATGTGCTACCAGTGCAGCCGACACTTATAGCGGG
          TCCGGAAGCGATTTGGACCCGTGGCCACGTACGTCCAGCGCGGGTGGCACTTGTGCAAGG
          CCTTGTAGCAAGGAGTCATCGTCGCGACGCACCTCTCGTCTCGGTCGTCCGGCCAGCGAA
          CCCAACTGAGCAACTATTTACCTGCCAACCGCCCCTTGTATGGGAAGACCTCGTCGCGCG
          AGGGGTAGGAGACTTTCCTCTCCGTTAAGTAAATCTAGTATATATTCGTGGAGAGGATAG
          GACTTTAGTAGGTTCATGGTAGGCCAGAACGCACTGGCAGCATCTGTATCGCCAAGGACA

          CAACTTTGGCACGTAATCTATGGATTAAGCGGAAGTGTGTCTTTACTTTACTACTACAGT
          CAACTTTGGCACGTAATCTATGGATTAAGCGGAGGTGTGTCTTTACTTTACTACTACAGT
          CAACTTTGGCACATAACCTGTGGATTAAGTGGAAGTGTGTCTTTGCTTTACTACTACAGT
          CCATCATGACGTGTCATTTACTGCTTACATGGAGGCACTGACTTGTTTCATCGGTCCATC
          GAGCAGCGACGAGTAGACCGGTGCTGGTATACAGGAGTGCGCCTAGATTGCAATAGAATT
          ACCAAGCGGTGGGTAAGCTCATTATTGTTCATTGAGTCGGTCCTAAGTGTCCACAATAGT
          GCACAGCAGAGAGAACATTGACCCCCATTAATAAGAGCCGTCTCTGTTTCTTGCCCTCTT
          AGCCCCCGCTGTGTCGAGGGTTTAGTATCTAGTCATACTGCCCCCGCCTTTCCGTGTGTA

          CCTGGCTCGACGATCAGCGTCTGGAGGGTGCATTATACGAGCTAGAGAGACCGATGAGCT
          CCTGGCTCGACGATCAGCGTCTGGAGGGTGCATTATACGAGCTAGAGAGACCGATGAGCT
          CCTGGCTCGACGATCAGCGTCTGGAGGGTGCATTATACGAGTTAGAGAGATCGATGAGCT
          TATTACTCGGCGACAAGTCTCCTGAGAGTATATTGGGCGAGAAAATGAACATGATGCCGT
          GTCGGTCTGTAGGCGTATGTGAATAAACTGCTGAAAATGAAGCTGGGAAGTCCACGAGCC
          TTAGAAACCAGGGATCAGCCCGGCAGTCAACGTTCACCAAGTATGGAAGCTTCTTACGCT
          TTCGGAGTGCGGTTAAACATGTGTGAACCGGCGCGAATGGCCGCATGCACTCCCGTTTTC
          CCATCTCAGTGTGCGCGACTGTCTTAAGGAAGGCATATGAGGTCGAGTGCGCCTGGTGAG

          GGTAACTAAGTTAAGTCAGAGGCTAGGACTGGAGACGCTGGTACAGAGTGAGGTGTCATG
          GGTAACTAAGTTAAGTCAGAGGCTAGGACTAGAGACGCTGGTACAGAGTGAGGTGTCATG
          GGTAACGGGGTTAAGTCAGAGGCTAGGACTGGGGACGCTGGTACAGAGCGAGGTGTCATG
          GAGAACAGCAGAAGGTCCGGGATTTGGAATGGAATTGTAGGGGTCGATCGAGGCTCCATG
          GGGGGTTGGACAGCGTCCATCATCGGACAGTTAGAGACACGCAGTAGGGACAATGAAGCG
          GTGCGACGGGAAGATTCGGGGACAGCCCCCGCAGCTGTGCACGGCGAATATGGCGTCGGG
          TCCATTAAGCTAGGATAAAAGAATAGATCCGAAAGTGGGGATAGCATGCCAGATAACCAG
          AAGAAACGGAGGAATCAGTATATTAGGCCCACGACTTATAGAAGCAAATAAGGTAGAGCG

          AATGCGGAATGATGGGTTTATATGCTACGCAACCTAAACGGCATCAACCTCGGGGGCAAG
          AATGCGGAATGATGGGTTTATATGCTACGCAACCTAAACGGCATCAACCTCGGGGGCAAG
          AATGCGGAATGATGGGTTTATATTCTACGCAACCTAAGCGGCTTCAACCTTGGGGGCAAG
          GCACTGGAGTTACGGGCTTATATTCGTTCCCCCATACGTAGCGTCCACATGAGTGGCAGG
          AAGGGAGTTAGATTAGTTTCCATCCGTGCTTCCGCCGCTGAAAATCAATTTAGGCCTTCG
          GCGGAGATCCGTTAAAGTTTTACTCACCCTCTTCCGTCTGTCGCCCCATTAGGTGAGCAG
          AGGGATTTTGTACCGAGCCCCACAACTCCGCTTTAGCCTGCTGCACTGATCGCTTATAGG
          GGGGGTATCTCATAAAATCTTTTCCCCGAAACTATGTTATTTATGTCCGCCAGCAAACGT

          TTTCCGCACTATAAAGTAGGATGACCCGGAAGTTTGGCCGTCAGAGTAGGTATGTACTCG
          TTTCCGCACTATAAAGTAGGATGACCCGGAAGTTTGGCCGTCAGAGTAGGTATGTACTCG
          TTTACGCTCAGTAAAGCAGGAGGTCCCGGGAGTTTGGCCGTCAGAGTAGGCATGTAATCG
          CGTGTGCGCGGTGAAGCTGAATTTCTCGGGAGTTCGGACGCGAAAATATGGACATAATAG
          TACGTTTGTAGTTGAGGTACTTTTAACCGTTGTCCGGGCCGAACACGTTGAGCGTAGAAG
          CTCCTGCACAATGGTATTGGATTACAGCGGGCCCCGGCTTCACAACACTTGTGGCGGAGA
          GTTAAACGTGGGGGGTTTACACCGCCGCAGAACAGACGCCGAATGGTCGGCAAGCTAGTT
          GCCCGACACGAGGGGGGTGAGACTCGATAAAACTGCTGTCAACGGGTCAACCCACTGGTG

          ATTGGAGGAAATAGGGAGATGATAATCCTCACCGTTAAGTGTGAAGCTCCCAATCAGGCT
          ATTGGAGGAAATAGGGAGATGATAATTCTCACCGTTAAGTGTGAAGCTCCCAATCAGGCT
          ATTGAAGGAAACAGGGAGATGATAATTATCGCTGTTAAGTGTGAAGCTCCCAATCAGGCT
          ATAAAAGAGGATAGACAGATAAGACTCGTCGTCGTTAGGTGTCACGTCCAGAATTGGGAT
          GGGAACGCCTGAAGGAGGATAATGATTTATCCTGTTATGGACGCAGACCTAGACAGGGCG
          ATGTGGGCTGACAACAAGATGATCCTTGTTCGTAGCTGGTACGTTCGGTCTAGAGCGTGT
          CTATAGCGCAGCGTGAAAGTAATCCCCGTTTGCTATAAGTGTCATGCGCTGGGGAGGGCC
          GTCGGAATTTATTCTGAGCTAACACTGATGTCCGAGGCATCGAGAGACTCCCGGAACTGT

          TAAATCAGTCCTGAGTCAATAGCACGAACACTATTATCCAAGTGGCTTCTGAGGTCGCCC
          TAAATCAGTCCTGAGTCAATAGCACGAACACTATTATCCAAGTGGCTTCTGAGGTCGCCC
          TACATCAGTCCTGAGTCAGTAGCACGACCACTATTATCTAAGTGACTTCCGAGGTCGCCC
          TACCCCGTAGCGCGGTCAACACTATGGCGCCCAGTGTATAAGTGGTTCTTAAGGCCGTTC
          CAACACTGGGCCCAGTAAATAGCATACCGTGTAGCACGTGACACTTATTGATTAGCGGCA
          TCCTTAGAATTCATGTTAATAGGGCGGCAACCAAGCCATGGAACTCAACCGCAACCGCTG
          CGTCTGGAGGTAAACCGATAAATGCGGCTACCAGGCCCATGAAAACAACGAAGGTCGGAG
          CCCATAGAATTTAGTCCGACAATTTCGTAGCTTAGCCAGGTAAGGCAACAGCAAACTCCA

          GCCTAGTAATTAGCTACCTTGGATGTGCGAGCTAACATGGAATACGTCTACTTGCATAAT
          GCCTAGTAATTAGCTACCCTGGATGTGCGAGCTAACATGGAATACGTCTACTTGCATAAT
          GCATAGTAACTAGCTGTCCTGGGCGTGCGAGCTATCATGGAAAACGTCTATTTGCATAAT
          GTACGATGCCTTGACGTCCTGGGTGTGCGAGATATTGCCAAAAAAGTCGGCCTCCGTAGT
          AACAACTACCATGCTATACTGAATGCCTGGGTTAAAATTAGCATCGCGAGCATGCAGCAA
          ACTATCCATGCCAATACAAGGGCCAAGTGCTCGGTAATCGAGCTGGCATATCCGCCCTCT
          CCAGGACCCATCGTATAGTTAGGTAAGTGCATAATCATTAGATCTTCTAAAGCGCGCCCT
          AGAGACAGCCACAAGGTATTCCAAGAGAGAGTGGTTGTCGCTGCTGTCCCAGCAGGCATT

          GAGAGTAACGGTCCCGCTCGTCTCATATGCGTCTCCGGGG
          GAGAGTAACGGTCCCGCTCGTCTCATATGCGTCTCCGGGG
          GTGAGTAAGGGTCCCGCCCGTCTCATATGCGTCTCCGGGG
          AAGAGTGAAGGTCCCCCTAGTGTCGTCTGTAGGTGCAGGG
          GAGCGTGAGGGGGCTCCTTGCGTTATATACGCGCATGAGT
          ACATAAGAAGGACCTGCTCCAGAGTCCCACCTATACAGAG
          GAGCTGCCGGGAGCTCAAACTGACCTGTGTGGTCCCAGGG
          ACTATGAGATCGTTTCTCAGCGTTATCTCGGACTTGAGGG

