 8 1000
t1        ACTCTCGTCAGGATCTCAGTTCTACTGAGGGCGCTACGTCGATGACGAACGCAGTCTGAA
t2        ATTTACGGCCGGATCCCAATTTTACTGATCACGCGACATCGATGATGAACGGAGCCTGAA
t3        CAGTCTGGCTGGTCCTTTATTTCGATCATGACGTTACGTTGGATTACTCGCGAATATCAT
t4        CAAAGCGGCCGAACCGGGTCCCGACCTTAGCCGCTGTATTATACCTGCCAGGAGCAAGTG
t5        CAGAGCATTAAGGTCCCTTACTTAAATGTAGCGGTAAGGAGCTGGTGGCAGGAAACTATC
t6        CAACCAAGCCGAGCCATCTTTACTGTTGCGGTGTTCTCTGGCCTTTGGAGAGCGTCTGTA
t7        TACGTAAGCCGACGTGTAACTGTTGAGGTGATGCAATGTCTCCGTTGTTCTATCGGTATT
t8        TATAAAGGGTGTCCAATTATTGTCATCGCCGAAACTTCCTGACTTCAGTGGGAGAGTGTA

          TGCAGCCGTGTTATTCGCTCGCTTCACGCAGAAGATAGAGGCTCTGTACGCAACCCCAAC
          CGCAGCCGTGTCAATCGCTCGTTACCAGCAGACAATAGAGGCCCCGTATTTTACTCCGAC
          TACACCGAAGGCGGTTGCTCGCCTTGGGACGATGACAGAGGTTCTGCACGGTATCCCGCT
          CTTACTGGCCCACATCGGCCATTACGAGACTCAAAGAGAAGTGCCGGCAGGTTTCGGAAC
          AGGAACCGTTGCGGCAGTGCTTGACAAGTCGATTAAAGGGGCCTAGGTTAGTGGCGTGTT
          CCTGCTGGATGTCCTCTCCGCCAATATGCAAATTAATGAAACCCGAGCCAATGTCGCTAG
          CTGACAGGGTGTGACCATACGCCATGGTCGAAAAACGGCGTATACGAGCAACGCCTCGGA
          CTTGAAGATCTCGACCGGGGCATAACGTCTGCAACTGGCGGTCCCGATTGGCACAGGTAT

          AATTATGGGAGAGTCTACTGCCAGGGTCTGCACGCTCCAAGACCGCCAAATGTAGGTCGG
          AATTTTGGGCAAGCAGACTCCCCGCGCCTGTACAACTCAAGGCCGCTTAACGTAGGGCGG
          GATTCTGGGAGAGAACTACAACTGGGGTTGTGCACGTTGGGAGCACCAACTGTATGAAGA
          GGCGCTGGATGTGCAATCTACTCGAAACCCTAAACTGCAAACCCACGAATTACGCAGTAA
          GCTGCTAAACCCAAAGCCCACTTCTGCACGAGCCCTATAGGGTCTATGGACGTAGAGTTG
          TCGCTCAAACGTGATGGACCGCTGGGCCCACGTGGTCTGAGACGGACAAATGTCAATCGA
          GAAGCTCGCATATAAAGATCTTTGAAATGAGACCTGGCATGGCTGGCAGATCAGGAACGA
          CGAGTCAGACCTTTAGTCACCTCGTCTTCGACCCACGTATGCCCGCCCGTCTAGGTATAA

          GAAAGGTAAATAAGTGCAACTAAAGGATTTTACTTAAATGCGGTCACCGACAGATATGAA
          GAAAGATAGGCACATGCAACCATAGAATCTCACTTAGGTGCGGTAACGGACAGATATGAA
          GTAAAGCCACCACTCGAAATCGAAGGGTTTCCCACTGGTGTGGTCGTCGGCGGCTACAGA
          AAATTTCCGTTCCAGCATTTTGTGTTACCTTGCAGAAGAATGGATTCGTGATGTTGTTTA
          GAATAACATTAAATTTACAGAATCTAACTAAACCTCCGAACACTTCATGGGAGACATCGC
          GAACGGCGGTAGAAACACGGCATGAGAGTTAAACCCAATTCCTGCGCTGAGTCCTACCTT
          GCGCGCTGAAAAACTCGCCGTTTAAAACTTCTTTTCAATTCCAATGCGGCTAGCTCCTCA
          GTGTGGTAACTAAGCTAGAATAACCTACGTGCCCGCCGTCAGACCTGGAGGAACCCTCGT

          TGATAACGCGTTTCTCAACACTGTATCCTAGCTTGAGTCGGAGAAGTTGTGTTAAGGGCA
          TGACCGCGCGTCTTCCAATACTGCCATCAAGCTTGAGTCGGGAAAGTTGTCCTCGGAGCG
          CCAGAGAGCCGTTTCTTATATGGTACTCATGATCGGACCTGGAACCTAACGCATAAGGTA
          TGCATGTTTTATCTTTAGTGGGGAATATTCAGTTTCCTCTCGATTTCCAGATCTTAAGTT
          TGCCGGTGCAGACGTCAGTAAGACTCTAATGTACAGGAGGGACTACCTAGTTCCTAGAGG
          ACAGTGTTGAGACCTTGAGATGGCTATACCAACCCGATTCAAGATCCCGAGCGCGAAAGC
          AGAGAGCGCGGAATCCCGCTGGGTGTGACCAATTGATCCAGCTGTCCGCCCTGTGCGCGA
          TGCGAACGCAGTCTTTGATTTGTACCTCGTACACTTGTCGGATACTAGGAGTGTTTACAC

          CCTAAGTGATCATATTGCGCCGTGGCAAACTAGGTAAGGCGCTTCTTGTATTAGACGTAC
          TCTGGGTGATTCCATTGCGCCGTGGTAATCCTGGCAAGGTGCTTTTTGTATCAGACACGT
          ACTGAACAAACGTCGAGCATTGTCGCAACTTTGGCAAGCGACATGTTGGCATTCACTAGT
          GTAGCCTAGTGGCTGGGCACTGCAGCTGGCGGGGCAAACGTTTTGTAACAGGCAGGCCAA
          CGAGAATGACTGTCGGCCGCCGAAGACCTTTACTCGGGCAACACCTTTATTATGGTTCAT
          GCTATATTATTGTATGGGGAGTTCGGTACCCCCTACTCCACAGGTTCACCCAAGTTCCGC
          TTCGTTTCTTCGAACGAGAGTGTGGCTTATTGTGACAGATACAGATCTGTCCCGATGCGC
          CTAACGTTGCGTACCAGAGCGACTATAAATCAATGCGCCGATACTCTAGTGCCGGCGTCT

          AAGGCGCGGCTTCTTCGCAACGTCATGACTTTGGCTCCGACGATTCTAACCCATTTCTAC
          GGTGCACGACTTTTCCGCCTCGGAACGCCCTTGGCCTCGACGCAACTACCGGATTCCTAA
          AGGAATTACCCATCTTGTCCCGTGAAGCCCCAGGTCTTCAGGGGAGAACCCGATTTTACA
          AATCAGCCACCCCCTTCGTCGGACAAACACGCTAGCGCGCCGGTTCTGTTGGATCTCGTA
          CCTTGATGCCCTTTCTTATAGGTCCGGTCCATCAGTGTTAGTGGGCGCCGTGCCCCTTTT
          AGGCGCGGCTTTTCTCGCGTCGATAGGCCTAGGAACCCGACATCCGACCGGAATTTTCCA
          ATTCGCCCCTATCTGTAATTAGACAGCGATCCAAAGCCGACCGTTAATCCCAGGCCATAG
          GTTTTGAACGTCCTCCAGCTCGATGGTGTCCTAAATCCTACAGATTGTCTTACTCCCGCG

          TGATGTGAGAATGCCGTCAGGTGCTATGGGCCGGATTAAAGTGCATACAAAGATGGCAAT
          TGGTGTGTGATCAGCGCCAAATGTCACAGGCCGGATAATAGTGCCTGCAAACATCGCAGT
          GTGAGCGAGAATGTGTTCATGTGTATTGCGATAGTTAACAGTGCCAATAAGGAGCAACAT
          AGGGCTTACTCTGCATTATAGCACCAGGGGGATGGTAGTAGCGCCAAGGCTTAGAGAGAC
          TAAAATGACTTGTCGAGATCGTATCCTAAGCCCAGTCACGATAAGTAAAGTAGCTGAGAT
          ACCATCTGGGACGCGTTGTTGTCTGTAGCGCCTGGTCATCAGAGGTAGTCCAAGCGGAAA
          GCAGGCAGATCTAAGTTATTACGTTGCAAGAATGGGGATGCAGGGAATATCGTGAAGAGA
          AAGTAACGAAGTGAGTAGCCAGACGACCGCTCCTCAGCTGGCGTGCCAGCAGAGCGTGGT

          CAGGTCTTCCCTACAAACCACCACTTTCCTTTTCATCCATGGCGTCGTGGTTTGTAAAGA
          CAGGTACTCCCTATCAACCACCATCTTCCTTCTCGTTCATGGCGTTGTGTTTTTTAAAGT
          CCGGAATCCTATATACATACTAACAACCTTTTTCGTATACGAAGACGTGTCTTTGTAGGA
          CCGTAAAGTTTTTGTGACCTGCATTCGATGCTTTCTCTGTCACTTTGCGCCATCGCATGG
          CAAACACGCCCAAGATGTCTTGCCCCGGGTTCCCACGCACATGCGAGCGCAAACGCAGAA
          CAGATTAGCCACAGATAACTGGACATGTTCGTTTATATGCAACCTTATGCCTCTGTGACG
          TAGCTACGCCTCTCAAGCTCCTACCTTTGTATTGGTCCCCAACTATGTTTCTTAGTTGGC
          GTCCAATGTATCAGATGACTCGACTTATATCATCGTCGGTAGCTGAGTACCCCCGTAAGC

          GCGTGCACGCAGCTAGGGTATCGGACATGGCAGATATGTTCGATAATATCAGTCGCGCGA
          GCGGGCACTGAGTTGGGGTATTGGACTCGGTAGCTATGTTCAGTAATATCAGTCGTGCGA
          ATGGAGTAGGAGCCGGAGTATAAAACACACCGACTACGTTCGCTCAGACCTTTCATAAGA
          AAGAGATATGAGCCTCGGGACTGGTGAGGGTAAAAACCGCTCGCCACGAAAACACGGACA
          ACGAGCGTACATTCCTAGCGCTGACTGTTTGTCCTCCGTTGGCGATTGGGTCAGGTGAGG
          GTGGACTGTGAACCGTAGGCGTAAGTATTCCAATGGTGAACAACCACAGATAATGCATGG
          TTAGCCAGAAAGATGCAGTCACCGCATTGTTCAGTGCTACATGCAGTTAATATAGCACGA
          GTAAGAGTTGTCTCGCCAATACGGCTATTTCACCAGATACTGGTGTCGTCGTCTGTCCGG

          TTCAGCCTCGTCATGACGGTCAGTCTGGACGCTCAGAGTGCGTGCCTAACCACTAACTCC
          TTCAGTGTCGTCATGACGGTCAGTCTGGACGCTCAGAGTGCGTATCTAACCAACAACTCC
          GTTCACTTTGTCATGATGACTCATTGGCACACTTTCAGAGCGTGCCTATATGACAACCTT
          ATTCGCTTTATCCCGCTGGTCTCCCAGGCCACATTAAGAGTGAACCAGGAGTACAATACT
          GTCTACTTGGTCTTCATGATTTCTTTATCTACGGCGAAACCGCGGATCAAGGAGAAACCA
          TTATACCAGACCGAAGTGAAATTCTAATCTCCAACCAGCCTGAACATACGTTTCGTGTGT
          AACTGTTAGGTGCCGAACCCTGCCTGGTCTACACACAATCCCAGTGTACGGAGTGTATCC
          ATCTTAGTAAACCAGGGCAGCCCTCTAGTTTTATGTTGTCGGGGTGGATATTGTATGCAC

          GGATAGCAACGGGCATCACCGGAGCGATCTAGGCCGTCGTTCAAGTCAGGAGGGGCAGAT
          GAATAACGATGAGCGCCACGGGAGTGATACTATCAGTTGTCCAAGTCGAGCGGGGCAAAT
          CGAGAGTGACCGCTGTCGAAAACTCGCAACTAAGCGTCGATCGTGCCAAAGGGGGTGGAT
          GTCCTATCCGTGTACTAACTAAAAGGGAGCAGGCCATCGTTAGTGCCAAGGGGGCTGATA
          TAAGAATAAATGCCCAATCTATTCTGTGGCAAGCAATTGTCACCGCCGGAGAAGATGGGT
          GAGCAATAAATGACGCCTATGAGACGCTTCTATTCGTCTATTCCTACTATTCGGGGTGAG
          GGACGACCACTTACGCAGGCCCAAAGTAGATAGTTTCCGGTTATGCTAAAATAGACACGT
          TAATAAAATTTCCCGGAGCATAGTCGTAGAGAACAGGCAGTCGTAATTTAGGAGGGAGGT

          TCGGTGCGGGGGCGTCAAACTCATCTAGATTGCATAGCCCACCTGCTATATGAAAGTCAG
          CTGATGCGGGGGTGATTAGCTCACTTAGATCGCAAAGGTCACTGATTACGTGAGAGTCAA
          ATTGCGGGGGAACACTAAGCCCGGCCACTCAGGATGCCCTATAGACATTACGGCGGTAGA
          GCCCCCGAGAGGCGTGAAGCGTCTCCGGCATGTGAACGTGGTGGCCCTACTGGCCGAGGT
          TTGAGAATGATTTAAGGTACCTTCTTAAGCCTCGAGGGCAGCGGCTCTCCAATCTGATGG
          GCTGGTTTCGCGCAAGAGCGACTTTGGCATCGCGCACGAGGGAGCACTATCGGCCTTACC
          GCGATTTGGCTGATATGCGTTAGCCGGCGTACCATCCATAGCAGCTTTACTACCCGTGCG
          ACGCGAGTAATGACTACGATCTGGAGGATTCGTAGAGGTTATGGTTTAATATGTTACGGG

          CTGATACTCTCTTCTTACAGAATCATGCTCAGAATCCGGTTCGAATCTTGTCGCGAGGGG
          CTGCTACTCTCTCCTTACAGAACCATGCCCCGAACGCGGTGTGAATTTTATTGCGAAGGG
          CCGATGTCCAGCTCCCACGAGATCATTTTGCCAATTTGGCGTCCCTTCTACAACTCGATA
          CTGCCATCACCATTCTAGAAGAAACTACAGCAAATCCCGCGTACACCTCAGTGCCCCCTG
          ATGCCGTTGGAATTCGGGTAAAGCATCAGACAGCGCAAATGCTGGTATCTCGTCACACTT
          TAGATCTCCTGCTCACAGGATCTCTAGTCGCAAGCCTCACATACGAATAGATCTCGGGCG
          TGGCCTCCTCACCGATTGGAGGAGTCGAATTACCTTCCGCGGACACCCACTACCTGGCTC
          GAGCTTCGCGCCAGCTAAACGTTGATAAGCATCCCACTACTTATAATGTGCATTCATTTA

          CGTTTCGCTCGAAATCGCGGTTCGTACACTCTCATAGCGGACGCGAAATCATCTCAAAAC
          GGTTTCGTTCGACATCATGGTCTGTACATCCTCATTGCGAACGCGTTATTATTTCAAAAC
          TGATCGGATTGATGCCGTGCCCTGTCCGTCGCCTTACGGAACGGGGAGTCACCACAAAAC
          TCGTCTGTCACCCAATACGGTTGCTACATCGATATGTCCGAAATATCGACACTTCGCAAG
          ACTCTAGCCTGCCGTCGTCTCCAGTATGTAATTGCATGGTATACATGGCGTCTACGCAAG
          TCTTTGTATTCCTGTTGTAGCAAGTAAACTGAGCTTCCGAATAGGATGTTCTTGTTTGAG
          TGTCCTACTTGTTTCCATTCTTTGCACCCGAGCGTATAGTGCATGTCGCGCAACACCCTC
          GAATTTATTTAGGCTTATCCGAGACTCACCGCTGCGCAGAATAGTCCCTCCTGCCATGCA

          GCGGCATTTGGCCAGATCGATTGGAACTGTTGAGGCGCTGCACGCCCAAATCCAGGTGAC
          GCGACGTCGGGCCAGATCGATTGGAACTATTCCAGCGCTTCACGTCTAAGTTCAGGCGAC
          ACGTCGTTTGGCGAGACCCTGCTGATCCGCTGTTTTGCTTCCCGGCCGGTTTTGTCCTAT
          GTATCAGCTGGTTAGAATGCTTATAATTGTCGTAGGGAAGAGAGTTTGCATTAATATGGT
          GTTTCGGGTGGAACTCTTATACTTAGTCATCTCACCGACTCCCTTCCGGTCCTCCCTACT
          ATGGTGACCGAATGGGTTCTCTTAGTTTGTTCTACCAATATGGATCGAGAATAACGGACT
          CTATCGGAGCATCCGAGTGGTCATATCAACCCAAGTGCTCTCTAGTCGGGGCAGCGCGCC
          GAGCGAAACTGCTGAGAGGTTTTTTGTACTCCTTGCACCTTTATCCGACATCTAGACTAT

          AGTCCGCTGTATTTCCGTGACACTAGTAGTTCGTGGAGAC
          GATCCGTTGTATTTCTGTGACAGTAGTAGTTTGTGGTGAC
          ATTTTTGGCTATTCTTGCGGGCCTGGTTGTCCGCGGACAT
          TCTTCTCTGCATTTTTGAACAACTATGTTTCCCTGGTGTC
          ATAAGGTGGCATTTCCGAATTCTTACCGATACGAACTAAT
          ACGTTCTGACTTCTACGGACCTTTGCCAGCACGTAACGGA
          ATATTGTTCTAGTCTCGATTCCCTTCTAACACATGGTGTT
          TATCCTCTGTGCATCCGTAACCCAGAAATTTCGTGTTGCC

