 8 1000
t1        AGTATGCCAACCCTGCATACTTGACAGACCCAGCCGCTGACCGCTAAAGGAATTTGTCTC
t2        TGTAAACTTGTCCTGCACCCCTGTCAGGCCGAGCAGTTGTGCTCTCGAGGCAATTCTCTC
t3        TGTAAGCATACTCCATCTTCCGGCTTACTAACGTGCCGACTAATCCCGGACACATGTTTT
t4        GGCGAGGTTACCTTAAGTATGCGACAGGATGGGTCACCTCCGTCCTACCAAAAATGTGTT
t5        TTTATCGGGTGGTCCGAATGTAGTTGACTTAGAAAATCATTGCGTCCAAGTGCTAGGTTT
t6        TCTCATGTGAACCCTGTACGCGGTTAATCATGTAAGTGACTTCGTTATGGAGGTCGGGCC
t7        CATGTGAGGGATTGCGAACGGGATTAAATTCGGTGAACGCTACCTAGCAGAACTCGACTC
t8        TATGTGGCCGTATTCTAAACTGATAAGCACGGGCGTAAGTTGCGTTACGGACACAGCCCT

          CTATACAGATTGTTGGGGCGTAATAGCCCTGTATCAGGCCCCTAGAAACGGCTACAGCTC
          CTGTTCCGGTTGTCGCAACGAAATTGCGCCGCATTGGACTTTTAGAGGGGACGATAACTC
          CGACGATTCTTGCTATTGAGGGGCTTCCCAGTCGTAGCGTTCTGTAGCAGGAGACAACTA
          TTATGCGCGTTATTTAAAGGGCATGAGTTTCTTATGTAACCACGGCAAGGGGTAAAGCTC
          CAAACCCTATATGTGCTCAATAACCGCGAGTTCAGTAAGTGCGGTACAGGCACCTAATGC
          TTAAACTCACTCACACTCAGGAACCGTGTATCCAATTGGCTCGGAGGAGGCATTAATTGC
          CCTTCCGCTCCTCCACGCGCGACCTTCCACAATTCAGAGTATAAACCGGCCGATGGGTTT
          TGAGCTCCTCGTGTCCCAGTGGCTTTTCTTGATTTCAAAAATGTACCGCAAGATGGTTCC

          GTTCCGTTCCAAGCGATCGGGCTAAACACAAGGCAGTGAACCGTAAGGTCTTATGGCATA
          CAACGGATTAAAGCCAGCAAGCTCGACGCGATGTCGCGAACAATAAAGTCTTACGGCGTA
          GTAAAACCATGATGCCTCATATCTGCCAAGGGAACGTTTACTACCGGCCCCCCTGGTCAA
          GGATACCTGCGACGTGGCAAACCACAAGGGTGCCCACGGAGTATACGGTCTAGTTGCACA
          AATCGCCCGACACGAAGTTGTTCATGCATCGAGCCATGGATTTTCGGGTTTTGATACTAG
          GATCGTCTGACGTGCAGTAACCCATGAGTCGGTTCAAGAATCCTCGGGTCCTGAAATTAG
          CACCGCTCCATGTATTAAAGACGCTTCGACGGATCAGCGTATAATGAATTAAGTGGTATC
          CCTTTTCGCACGCCTGGCAAGTCACGGGACCGTCCAAGGCATCATGAGATTCTTCGAAAG

          GGGTTGAGGTGAGGCACAGCATAACGAGCTTAGAGGACATTTTAAGAGGGAAGAGGTGAA
          GTGATGAAGTGGAGCACAGTCTAATGAGTTCGGGGGACCCTTTGCCAGATCAGAACCACA
          ACACAAAAATGCAGTGAAGTCCCACAAGACTGTGGGTAAACAAGGAAATACGAGAAGAAA
          GCGCCTGAGGGCCCCAGCTTCCTGCAAATCCGAATGATGTCTTCCGGGAGATTTTGTAAA
          TTGCTGACAGCGCATGATCAAGAATGGAGCTCTGAGTTAGGTCTAGTGGAGCCTTAGCAG
          CTCTTAGCTACGAATGATTAGGGATAGCGCCTCGAATAATGCCTAACGATGACTCAACAT
          AGGACGAGGATGGACCGCATCGGATAAGGACGATCATCACATCCGTGAATGAGAAAACCG
          GGAACAGGGACGAATCGCTTCGGGTGGCGATACTCTCTACCTCTCGTGGAGTGAGGGGCA

          GGTAGGATATAGATATCTATCAAGTACCACCAGCAGATTACATATGTCTAAATCTTATGT
          GGCGGCATACATACTTCAATCGGGTGCTGCATAGACATACCCAATACCCCCGCTTCCTGC
          ACCGAAGACGGCATGTGGGCACATCTGAATAAGCCTGTCTAATGTTCACTTGCGTTGGTT
          GACAGCATGGTCATACCAGTCGTACTCCGGTGACGAAGATTAAATTTACCCGATTCGGTT
          AGAGATGCAGTTGCTTCGAAAGCTCCGAAAGGAGACGTCCCCGATTAGCTGATTAAGGTC
          AAATCCGCAGTAGATCCACTAACTGCGGAACGTAACATCCGCGATTAGCTGAATTGGTGA
          GCGCTCAAGGCCGCTTCTCTAACTCTCGACCCCTATTTGGGACTTTGACTTATTCGGGCC
          TAATATATGGTCATTTACATAGTTTTCGAGCGCCATACCACATCTAGGCATTTCGGGGCC

          AATAAGAGAGGAAGTCCTGTCTTCGATGATCCGAACGCCCGGACACTTCATACCTCCTAG
          AGTAACTGCGGTGGTCTCGTCTGTGCAGATTCGAACGCCCAGCTACGGCACACCTTGTCG
          AACAAGCACAGCGGTTCAGAATCTGCTATCTAAAACTGTCAACACCGGCCTATCTTCCGG
          ACGAGCCGTAGAGTTTGGACACACATGAATCGGAATGACTAATAGTCACGTCCTTCATAG
          CCGTTAAAGCATAACGCGGTTGCTACTGATCGATGTAGGACACCTCCCTACAACTCCTAG
          GATATAAAAACTGTAGCGGTTGTCACAGCCTGAACTGGGGGACCCTTCCCCAGTAACAAG
          AAGACGCGTCCCGGTTGAACTATCTAGGAATCTATATATCGTCTCACGCTTGTCGTGGGG
          GAGAAATGTTAAGAGTTTGCCATGGCAGACTCGTCTTGTTCCCCCTCACTTATTACGAAC

          GTTCGTGGGGGGAACTAGGGGCGAGCTATTGAGCGGCTGGCCATTAAAATGCTGACTGCA
          GCCTGCGGAAACTCCTTTGGCGAAATAAACCTGCGCCTTACTACTCAAAGGTTCCCTAAA
          GTACGCGGATATGTTTTTGCCCGAGGTAGAGAGGGGTACAACCACAAAACCACACGTATT
          GCAGGCCAGGTTGTTCCAGGGGCGGTATTTGTGTGGCTTCTTTTAGAATTATCGTGCCTG
          ATAAGAGACTGATACAAGGTCAGGGTGCGTGACTTCACTGCTGTCACGGGTTTCCACAGC
          TCATACGACAGAAACCGGTATAGGGCGAATGACCTTGCTGCTCATAGAGATTTATGCATC
          GCACAAATTTAAAATTGGCGCAGGGTCAACAAGGCGCATGTTACCGAAAAGGTTTGTGGT
          GTCCTGGCATGAGCTTCGGACCGGTCCAGTGAAGAGCACGATACCGGAAGACCTGACTGT

          ATTCACGTCAGGTGACACCGATCTTTTCTAAACCACACGCACCGGCCCCACTACTCGAGC
          GCCCACGTCAATCGCCCCTGGATTATTTTCCCAGATACTTATCAACTCTGTCATCATGTT
          GCCTGCTTTGGGGGTCACGGAGAGCAGCGCGTCAGCACATTTCCAGTTCACAATTCCTAC
          CTCACTACTATTAGGCACTAGACCGGCTACTTGAGCGCCCCTTCGCGCCCACAAGCCGGC
          CTCATTGGAGACTCCGACCTATAGAACCTCATAAATGCTCTCCCGCAGCAATCCTTGAGT
          TCCAATTGTGATTAAGATTGCGGCGATCGTATGCCCACCCATTCACATGAGGCCTCGAGT
          TGCGCTGGTAGCGAAGATGATGAGGGTGTTGGACCCGTCACCGTGCAGGTTTATTGTGGT
          CACGCTGTTCCCGTAGACTATAATGCTGCTATATCGGTAATTTTACAGGTTTAATATGGT

          CCTAGCGGCATAACCCGTTAGCGGATAGGGTGGACCATCGGTTATTCGTTCGTGGTTCCC
          TTTCTTGGGGTAACTCGTGAGACGGTGCGAAGGGTTAATGGTTACCCATGCGTGATGTAC
          CCTCCTGTGAGGTTGTACAGAATAGGGGAATGCCCTGTTAACGACCCGATCGTGGACTGA
          TTTCATGTAGGATGAAGCGAGGAGCGGGGATGTAGGATTGGCGAATCTTATGTGGCGAAG
          CCCCAAGCGGGGTTGCTCCAAGAACGGGACAAAGTCAAGGGTCAGCTGTCCGCAATCTCC
          CTATAAGTGTTTCAGTGCGATAAACGGGATCGAGCCATGGGTTAGGCGTTTGCAATTCCG
          GCCCGATCGGCAACCCCTGTGGGAACGGACGGAGTCAGAAATTGTCTATTTATGGTCATT
          GCTCGTTCGGTGACATTTGAAGAAAAGGTTGGGAATAGTGACTATTTCTCTTGGGTTCAC

          GACACGGCCTTTGTTTGAAGACCAAATAAGTTGAGAACTTTTGCGCTCGATGTGCCTACA
          AATTCGACCAGTATTTATAGCCCGAACTAGTAAAGGACTGCTGCGCGTGTCGCGCATGGA
          CGAATACTCTTTCTGCCTAGGTCGAGCAGTGCACTGAACTCCGAGCACAACTCAGCAGGC
          CGCATGCTCTGGTGACGCCGGGAGCCCATATTGTAGATCTACTCAAACGATCACCAGCGC
          AGGCCAGATCAAGATGGAATGCAGACCAATCCGTGGGCGGTTAAAAATGGATCATTAGCT
          GGCGTGGTTCATGTCTGTATGCAGAGGAGTGAGTAGACGGTTAAGTGTGGCTCATTAGTC
          AATGAAGTCCACCTTTAGAGGGATAGTAAGTATCAGGCATCGACGTGTGATACCGCTAGG
          AACGCTGTATCTCTTTACAGGTACAATATGCATAAAACGCTGGCTTCTGGCGCGTGAAGG

          GCTACCTAGCAACTTATACCTAGAGTTACGCGTCTAGAGCAAAGCGTTACGTAGCGGTCA
          TACACCTAATAGCTCGCGCTTAGTCTTATGACCATGCCGCACGGCATTAAGCAGCGGTAG
          AAGAACGAGTGTCGCATCCCTAGGTCTTGGGCCCTTACCACCGGAACGACTCCATGTTAC
          TCGGCCCTGTGCCTCGTGTCCAGAATTGTAGGTTCAGCGGATCGCATGTAACTAAGGAGC
          ACACTAAATTGCCCCGAACACTAAGAGACGGATGTAGAGAGGGACATAGTTGTTTAGCAG
          CTACCCGATCGATTTAACCACTGGGCTATAGATGCACGGCGGGGCGAGTCCATTTAGAAC
          TACCGTTGAACCCCCAATCCCCAGACGCTACATGCAAGGGAACATCTCGTCCAGCCGTAC
          GTCCGTCGTCCCCTTATGTTGCAGAGACGACAAGTTTAAAATAGCCCGGCCCGCCCAGGA

          TATGTAACTTATCGGTAAGTGCGAGATCACGGGCAGCCACTGGAATGGGTCGTCCATGGA
          GTCTCAACTTGCACCTAAGGGCGTTGGGATAGGCAGTGCGTGGAGCGGGACCCTCATAGC
          AACAGAATGCAGCATTAGTTACGGCCCTATAAGGTGCCAGCGCCGCATGTTTCGCAAAAC
          CCTCGCATGTACCCTCGCGTGCAGAAGCTGAGGGAGCTTTTCCAGTTCAATCCGTGCGGT
          CATGCATTTACCCATATTAGTCGAGGCCCGGCAATAGGCAGGTATAGGGTCCGGGCCTGT
          TAACAAACAGGCCAATGAGTTTAGGGATAAGAGAGGAACAGGGTTCGGGCCTAAACCGGC
          CGCACAGTCCCTCAATGTTTACGGAGCAATATGGATACCGAGAGATGAGTCCAGCCGAGA
          TCTACAGCTCAAACTTGGCTGCAGAGCTACATGGGGTCTGAGAATTAAATCGAGTTCAGT

          GGCTGTTCCGGGTGTCTCATAGTACCCCCTGGCCGCGGTCTGAAGCCACGAAGCCTACTT
          GGCCCCCCTAGGAGACTAACCGTACTCTCTGGAATTCATTTAGGGCCGCTAAGCTCGCCT
          CGTCCTACTGCGTGTTTTTCCGTACTATCCTGTATGGGAGTACAGACTCCGGTGCGGTAA
          GTTCACTATTTATATCTATTAGTACGATTTAGTATAGAGGCATTGTTCTCGAATTGGATT
          TGCAGGCTAGGACTCTTTAGAAAGCCCCTTCGCGGTCAAATATTCACTCGGAAACGGCCA
          GGCAGCTTTAGACTCTTCAGATCTCCTTTCTGACTTTAAACATTCTCTCCGAGCCCGCCG
          GGCAACTTAGGGAAACCCCTGGCTTCATGAAGAGCTTGGATGCACGTTTCAGGTACATCC
          CGCGATCTCGAGTGTTATATAACGCGGCCATGATCTAGAACACCCCCGCAGAACATTTTC

          CTTCTAACTACCGGTATGGGTTAAGATGTCTGCGCGGTTCTAGTGGGCCTCTTTTAACCG
          TCGCTTGCTACCAGTATGGGCTAAGACGTCCGACCGGTTCTGCTAATACATCCGTCATTG
          GCTCCAGCACGAATGACAAAAGATGGAAAGCAAGCGGCAAATCCCTATCGATTGTTACGC
          CGACCAGCGGGGAGGACCGAACAGATAGTAGGGGTAGCTCTGACCCGGTGCCTGCTATTG
          TCTCTCACTGCCAAGTCTTGCTATTAATACCAGGTAAACAGAGGTAATCCGCCGGACTCA
          CCTTTCTTCACGAGGTTCAGCCGCGGATCGCGAGCTGCCACACGCGATCTCCAGGGCTCA
          CCTACCGACCCGCTAGACGACCGTGGACGGCTTCTGGTCCTGATCCTTTCCTCGGACCAA
          CCTTCCGTCATAAGAGCTACTTGAGGACGATTCCCGGCTCAACCCCTTCCCTTGCGCTTT

          TGAGGAAACTTGGCAAAGACCTACACGCTTCCGTAATTAATACGTTCACGTGGATGGCCC
          GGCTCACGAATGAAACAGCCTTCCATGCTACGGCAGTGAGTCGGTTTCTATAGTCAGTCT
          AGACAAAACAAAGTACGACTATACGCAAATGTGCAATTGATTCGTATGCGGGGCAGGCCG
          CGGCAAAATGACTTGCTGGTCGATGTTTGGAGCTATTGAATAGGTAGATGTGGCAAACTT
          TGATGGGACATAGCAATCAAGAAAGCATTAAAACGGTCTAAGACTGTGAAAGATCAGCGC
          TGAAGACACGCCGAAATCGGCAAACCCAAAGTGTGGTCTAAAGCTGCAGGAGACTTACCG
          CGAAGCAACGAGACTGATACCAAAACGACATCGCAGATGGAGGATGCAAAAGACACACAC
          TGCTATCACGGGGCAGGAAACTCGACGCTTCTGATGAAAGAGGATGTGATCTTCAGGAGC

          TAATTACAACGTTAGCCCGAAGTCCCGAGGTTTTAAATAAAGTTAGGGCCCCGCTTTAAT
          TTATAATGACCTGGGTTCGACAACAGGGGGCTCTGACGTGAGCTTGGGTTCCGGATTAGC
          GACCCACAATTTTAGTGTTATGAGCCGGCGTGTTTACGTTGGTCCAGACCTTGTGCCACC
          TAAGAACGAGTTAGGTCTATCAAGACAGGACTCCGTCGTATACTCGGGCCCAGTTGTATT
          TCGTCGTAACTATATCTTCGCGAGCTGGCCTTTAACCTATGGCCTAGACGAAACAGATTA
          TAGTTGCGGCCGAGTTTTCCCGAGTTCGTTTCCGTCCTTTGGCAAGGAATACGCAGCTCG
          CCATAGTTGAGCGTGCCTACACTGTTATGCCCCTGCTTCTCATACCGTCCAGCCCGGTTA
          CCGCGATTATGCGCGCCTTCCCCACAAGATTACGGTTGCCTGTTTTGTCCATTGGGGCCA

          TTACAAACTTGGGCTACGCACCTGCCTTCCTTACGCCTTG
          TTACTAAATTAGTCTTTGCACGCGGTTTATCTGGGACTTG
          GTACAGTCCTAATTTAGATCCGAAGATTATCTTCATTTTA
          GGACAGACTTAGATTGTCTTTAGGGTGTGATTAATCGTTG
          GTAAAGTGTCTTCATAACTATTTTAGTCAATTCGCCTAAG
          TAAAGGTCTTAACATGATCCTTTGAGGGGTTTAGCCCAAG
          TCCTTTTGATTGCTACTATCCGTGATCTGTTTGTACTGAA
          TCCGTATCGTTGGTGCAATTTGTGCTTTGTTTATACCGGA

