 8 1000
t1        GGTTGACAGCAATGTCCTATCTAAACGAACGGTCAGAGCACTAAATCGGTATGACCTCCC
t2        TATGATCATGCCTTTTGCTACCAGGTAGACGAGCGATGGTAATCTAGAGGACACCCCTTT
t3        CATGTATAACGGTCGCTGCAGTGGGGAATGGGCGGGGATGTTACAGCAGACTAGCCCTAG
t4        TCCATCCCGTGTCTGCGTCACTAGGTCTTACTCCGGGAGTTCTCTGTATTGTGCGCAGTA
t5        CAAGACCCGTACCCGCGGACATTGGTCCATGATTGCTTACAATGCTGGCTAAGACTCCCG
t6        CATGACCCGTACTCGCGGACATTGGTCCATGATTGCTAACAATGCTGGCTAAGACTCCCG
t7        CCTCCGCTGCATCGGTATTCCTGGACATTCTATGTACACACGTTACTCTGAGGGCAACTA
t8        CATCTGTCGTATTGACATCCACGGGCGCTCAATAGGCAAGCTGGACTATTACGGTCCCCA

          CTAAGGCTAGAGGGAAAGTGAGGAGCCTGAAGAGTTAGGCAAACGTGCAACGGCGTGGTT
          GAACGACCAAGATGAGATGTGGTGGTTTAGGATATTAAAACAAAAGGCAATCACAGGAGC
          GAGTAAGTCGAGTGGCACCAGTGTAAGCAGTGGAGAGCCATAACACAAAACTACAGGTGT
          TAAGTACCCGAGTGAACTTAGAGAAATTAATGGATGGGCAATAAGTGCCGTTGCAAGGGC
          AAACGACGTGGATTTAGACGCCTCAACATGATCGTTTATACATTCAGATACTACGAGCGC
          GAACGACGCGGATTTAGACGCCTCAACATGATCGTTTATACATACAGATAATACGAGCGC
          AAGTAATGATCTATAAGAAGTGATAATAAAACCATCAATAAAGGGGGCCAACTGAGGTGG
          GAGCAATGTAGTCCCAGACGGGAGAGTATAGCGATGAACGAAGACAACCAAGGTCAGCGA

          CCGTCCACGGCGCAGATATCTCAACGGTTGGCCTAGAGACGTCTTCTATTGTCAGATAGT
          CTCCTCAAGATTCGTATCGACCTTCACATCACACCTTGCTTCATGTCTGTGCACAGTATA
          TGCCCATGTAATCATCCATTTGCCCAGTTGGTTCCGGAACGTCCGAAGACTGGAAAACGT
          TAGTCTACCTCGGACGGGTGCTATTAATCACGCGATAGCCTACCCTTAGCGGGGGAATCA
          ATGCCTAGTAGGCCAGCCGATGTGCGACATATAGAAAGTCAGTCGAAGATCCTTAAATAC
          ATGTCTAGTAGACTAGCCCATGTGCGACATATAGAAAGTCAGTCGAAAATTCTTAAATAT
          CGCTTAAACTGACTCATTCCTGTTCTTCGCTGTCGCAGTTGAGTGGAAGTCTTGGTAGAC
          TATCCTAGTAGACCCCTTCGTGTAGTACTCGGTATAAACTGCCTGAAAACCCCGGTAGGC

          TGGCAAGCACCAGGCAATCAGCACACATATAACAAAGAGTCACTGTTGTAGCAACTGCAT
          GGTGAGGCCTGGACTACCTCAGTGGCCGCCCAGTATTGACGATACGTTCGATCACTCTGT
          AATATCGGGCCGAGTGGCAAGGTGCTGAAATGATACAGGAGATATGACCTGAAACCCCGT
          AGTATTAGGAAAGGCATTCCACGGGCTAAGCGGGAGCGAGCGTCAGTACAGGACCCATAA
          AGTACCGGGCTGGGTAATTCTCCATCACGACGGCATCGGAGATGAAAATACTAATCCTAA
          AGTACCGGGCTGGGTAATTCTCCATCACGACGGCATCGGAGACGAAGATACTAATCCTAA
          GATATTGAGGCAAATACTCTTCTGTCAACACTATTTTGCTGTTTAATACGCTAACGCGCT
          AGTAGATGGCTGAGTAATTTGCTTCGAAGAAGATATTGACGATCATTACACATATGTCAC

          TCTCGCATTTACCTAGCAGCGAGTCACCCACGCCTGCAGGTGACTCTTCAATCGAGGCTT
          CTCACCTACAAACCAGCTGCAAGCACCGTACGCACAGAACGGTTTTCAAGTTCGCGATCC
          CTCGTATTTACTGTCGGAGAGTCTGGTTCTGCCTTCAACATGTCTGTGGATCCCGGCTTA
          ATATGTACGATCGTAACCCTTAAGGGCCCCCGCTCGGACCCCCCCCTACTTCGAACTTCC
          TCCTACCTGACCGCAGAGGAGTGCAATTTAAAGACATTCCCTTCCGATGGTCTATATCAT
          ACCTACCTGACCGAAGGGGAGCGCAATTTAAAGACATTCCCTTTTGATGGTCTATATCAT
          TTCTTCCCTATGGCCATGCTACGAAGTTTCACCCTCACTATTATGACTGCCGTATGTTAT
          TTCACCGCTTATGTGGTAATGTGAAGCCTCACTAACGTTCCCTCTTTCGGTCCACGCCAT

          TTGAATGCTTCCTGCAAAAGATGCCCAGGGTGAGGTCCTATCAAGCGCAACAATCCCCAT
          GATTACACATTGCCCGGGGTTATGGCAACGATAGTACTAGCTAGCCACGTTGTCTTTTAG
          AAGCATACCTTGGTCAGAGGATATAGCGGCTACAATTTTCCCGGGACCGGCACGCTAGGA
          CCGAACCAAATCACTAGATTATGCGCAGGGACTACCTATTCAACACTGGGGACGCTATCG
          ACAGGATAGTTTCCAAGAAAGAGCCACGTCAAGACCCGCACCGGGATTTAATTCAGCCAC
          ACAGGATAGTTTCCAAGAAAGAGCCACGTCAAGCCCTGCACCGTGATCTAATTTAGCCAC
          GCGGAATGGATCGTGGCGTTAAGGATTTGGACAATATCTGACACCGCGGATGTCAAACGC
          AAGGAAAAACTCGTCGTGCTAACTCAGGGTCTTAGCTTCGACGTTATGGATATTTAGCAT

          TAATCGGGTCTCACCAGTATGATCCCGACCTCGGCATAATTCATCGGGATGAGCAGTCGC
          TTAAATAAGGCGTGCGGTGTAGGTTCTCACATGAGGCACTGGGCATGAGCTGGTTGCTTT
          CCGCGCACCTAATGTAATCCAAACCCATTTACAGGATACTAGGACTTTGCAGGGAGTCGC
          CTAGTCACCCAATTTAGATTTAGGTTAATTTTAGCGTGTGGGGTGAATGTGGATAATACC
          CATTAAACATTTTAAACATCCGTCTTCCTTTCAGTAAATCGACTTTCAGCGCGCGACTCC
          CATTAAACATTTTAAACATCCGTCTTTCTTTCAGTAAATCGACTTTCAGCGCGCGACTCC
          TATATGACTTACCGTAGTCCCAAACGATGCCCGGAGTCCTCGTGTCGAGCAAGTGATTAC
          CACAAGATTCCTGGAAGACGTAAAAAGTCCACGTGGGTCTCGATATGGCCGGGCGACCGC

          TCAACACATTATCGCGACAATGTGAAACCGAATGAGAGACACTCGCGTTAAATCCCCGCG
          AGAATATTTTCCCGAACAAGTTACAATGCGCGTGGTGGATAGCTATGCGCAGCTCCTGCG
          AGAAAGTACCCCTGCAATAAGTCACTGGCGCGCGCTAAATCGACACGTCCCGTGACCATA
          GACCCTTTTTTTCGAACGCACTAGTGGGTGTACAGTCCATGTAAGAGCCAAGCACCATTC
          TAGACGTATGCATGTGATAAAATCGAGGAGGGTTTGAGAACTCCAAGTCTGGCTACCCCA
          TGGACGTATGCATGTAATAAAATCGAGGAGGGTTTGAGAACTCCAAGTCTGGCTACCTCA
          CAACGGAGCATATGTAGCAAGGTCCAGGGAAGGTAGGGATACTCAACCCCGTCACTTTTG
          GAATAGTGTACACGTAGCTAAAAGTAGATGAGTAAGGAGTATTCAAGTGCGGCACTCCTG

          TAGGGGCTCGAGATCAGTAGTTGAGCCAGATGCCCATTTCGGAAAGATCCGACTTTGGCT
          GAGGGACTGAAAATCTGCAATCCGACCGATCGGACAGCCGAATCCCTGCTGTTTTTGAGA
          AGAAAATTACTCCTACATGGCAGTATCGATCTATTAGGCCACACGCTATTAATACCGGGT
          GAGAGAACGAATAACTTCATTTCGACTGAAGTAGTAGGTCATCTGCCGGCGGTACCAATC
          ATGGGTCCGGCGGCTCTTAAGAATGGCGGCCACATATTCCGCAGATGGGTGTTTCTTCAT
          ATGGGTCCGGCGGCTCTTAAGAATGGCGGCCACGTATTCCGCAGACGGGTGTTTCTTCAT
          GTAGGTTCTCGGTCCCCTAATCACGATGGTCACGTTAGCAGTGACCGAGCGTTCCAGGAC
          TTAGGTATTCAGCCCCCCTCTCAACATAGTCGTGCTGGAGGTGAGCGGATGGACCTGATT

          CCCCAAGATTGCGTCATACCTGACCACACTTATTGGATTTGTAGTGATCAGCTCCGGGAG
          CTGTAAATTTGGTGGATGTTCCGACACACCACGCCACTTTCTGCCATCCATTCCCTGGTA
          CGTGCGGGATATCAGCTGTCCTGTTTAAACGGACCGACGGCTTGAGGGGGATCTTCCATC
          TGCTTCGGTCAGCCACTATATCCGTTAGAATGGTGGGATTATGAACATGGGGGGCCGCGC
          CTTCCTCGCTGCCGTCCCACTCAGTACAACCATAAATTTTTGGTGTAATTGTTTCGAACC
          TTTCCTCGCTGCCGTCCCACTCAGTACAACCATAAATTTTTGGTGTAATTGTTTCGAATC
          CCTTTTCGACGCAGACCCCTCGAGTTAGACTAACAGTCAAGCGTGCGGTACTTGTCCAGT
          ACTCCCTGCTAATGACCTCCTCGGCAAGATAAACAATAATGTGTGCCCCAATGGTCACGT

          ATGTTAGCGCATTTTCCTGGGGGAGCTAGTCGTTGGCACCTGCCTGCGCGCTTGCAATGG
          AGGTTACAATGCTGTGTTTCGACCTACTTCCTCTGACGTACGGAGGTTCTCTGGATGACC
          TCAATAACGTTCGACATCAAGAGCGTCGGCCGCCACCACGCGGAGCCTGGTCACGAGAGT
          AGGACTGGGTGGCGCAGCCCGCCTTTTGTCGGTAGTAGAGGAGTCGTCCGTCCAGCCAGC
          AGACCTTAGCACTGTGCCCGAAGGGTTAACGGCTGAAGTGGGGTCCCATGTTTCCCTCAC
          AGACCTTAGCACTGTGCCCGAAGGGTTAACGGCTGAAGTGGGGTCCCATGTTTCCCTCAC
          AAGCAGGCGTCCTTTGATCGATCTATTAATACCGGAGTAGAACTTCATAGCTGTCATTTT
          CGGCCAGAGTCCGACTTTCAATGCGTTTGCATAGAAAGAGGGGCCCCTGGTCTTCATTAC

          GCTTAGACGGCATTACGCTTTAACCATTTTTTCTTACCTGAGCTCACGCATCATTATAAA
          GCCAGCTCCAATTGAAGCCACATCATAGTCATACATTTCCAATCGATCTCCTCACATAAT
          CCACAGGTCCCACCCAGTATATCCCCTAAAAAGTTATTTAGAGATGCCACCACCAGTCGC
          GTTGCTCTAACCATACGCTCAACTTGCTCGGGCAGGACCTAAGTTTCAGAGATCCACCAG
          AGTCAAGTGATTCAAGACGTTTGCGATTGGTTGTTATGCTGGTCGGTAACTAATCGACGC
          AGTCAAACGGTTCATGACGTTTGCGATTGGTTGTTATGCTGGTCGGTAACTAATCGACGC
          GGTGGACTAGCTAGCGGTATCTCCGACGGGCCATTGGGCTTACTAATTGCCAATTGTCGA
          TCTCTCCTAGCCCGCTGGCCCTTAAGCGCGTGATTGGGCCTGCTAATGGGTGAATTTTAT

          ATGGAATTGCGGTTATTCGCTCCTCTTCCTAGTAGCGCAACTGCGTGTCACCTGGTCTGT
          CTACAGGAGTGACATCACTCGCATCCGAGCACGAATGCGGCCGTCCTGTAGCTTAAAGTT
          GTGTTACCGCGTTAGAACTTTCAGGCTCGTGACGACATACTAAAAAGAACACTGGTTTCT
          TATATTCCATTATTAAAAGTTTTACCTAGTAGTGCCGCCAACGCATGGAGTTTGCTCTCT
          ATATGTTTTTGATAAGGCCCTCTCATGTGTGACAATTCGGGCACGTATAGGTCCCTACTG
          ATGTGTTTGTGATAAGGCCCTCTCATGCGTGACAATCCGGGCACGTGTAGGTCCGTACTG
          ATGTAGTTATGACAGAACCCTCACTTCTGAAAAGTTCCGAATCACAGTGGGCCGGCCTCG
          CTGACCTGTTAATAGAGCCTTCTCTCTAGATCTCGATAGCTTTCCAGCGTACCCATTCCG

          ATTAAATACTACAATGCATTTCGAGCCTCGATTCGTTATATGCTTCAGTAGTTATTCTGC
          TAAAAGCCATATATCCGACCCGTAACACAGACCCACTTTGGGTGGCAACCGGTAGGACGG
          CTTGGAACTACAATAAATGTCGGGGATCCGCGCAGCCGCGGGCGCCCCCCGGTAACGGAT
          TTAAGCTTCCGCCCTATATTGGGGGACTGGCTACCTGGGGGGTAAAACGGAGTTTGACCT
          CCCAAGCACAAGGTAGAATTCGGCCATTCGGCACGTTCCCCGTTTTTGTGTAATTCAAAC
          TCCAAGCACAAAGTAGAATTCGGCCACTCGGTACGTTCCCTGTTTTAGTGTAATCCAAAC
          TCAGCATACATTAGGGAATACAGGAATCCGGTACGTTCACCCCAATGCCGACACTGTAGC
          CCTAGACTTAATCTAGAGCAGAGAGTATCGCCGTACGCAGTCCTATGGTAACTATCTGGT

          ATACTTGTCCTACCCGTGTTCGACAAGACAGCACTCTTGCCAAGCACGGCTTTTTCGCTC
          GCCCTAATAAAGGGTAGCCCGAATGGGGTGGAGCTCACACCTATCACTGGTTCCCCGCCC
          TCCTATGTATCAGTCATCCTTTAGGCAAAGGGAGGTCCTTCAGGCTAACGTCGTATAAGC
          ACTATCGGCTCAGCGCGACCCAATGCATAGATGTGCGTCATAGTGACAGTATTACCGCTC
          TTCACCACTTTAGCCGATATATTCGTGGTAATGTCCATTCCAGAAAGCCGTGGCCCTTAC
          TTCGCCACTTTTGCCGATATATTCGTGGTCATGTCCATTCCAGAAAGCCGTGGCCCTTAC
          GTCTCTGGCCATATGGACATCTCTGAGATGCCGCGCTCCCTTGGTGTTTGCTGCGCGTAC
          GATTTTGGATGGGGGGATTTATGGGCTCCCATGTGCCTCCAATGTGCTTGCCGTCTGTAC

          ATGGGGGTGTCCCCTCTAATTTTTTGGCCCGAAACTGGTCGTGATCGAGTGTGCGGACCA
          TCGGACGAGTCCTACTCGAGTCTTTCCTATTACGACTATTGCCGCGATCAATATTGGTCC
          CTGGTTCTTCCTAGTATAATACACTCCCGATAGGCTTCCTCCAGTAACTCGTTCAGGAAA
          ACGAGAGGGCCATCCTGAATGGGGCCCTATTACGTTTACTGGGCTACTGCGTGAGAGAAA
          ATATCGGATCACCATTAGATCCTTAGTCTGGTAGCTCTGCACCGCGGTCACTATTTAATT
          ATATCGGATCACCATTAGGTCCTTAGTCTGGTAGCTCTGCACCGTTGTTACTATTTAATT
          ATGGCTACGCTCTATACCGTCCATCTCGTGGGCGTCATCCATTGTGGTTCCTGTGAGCTT
          ATAGTATAGTCCTGGTTGACCACCATTTTGACAAGCTACAACCGTAGTCCGTGTCAAGCA

          GATCCGTGCACCACATGTCGATACCGCGAGTAGAGGACGT
          TACGCCGGTTTCGGACAAGGTATCCCGATGCTGAGGGGAG
          GACCGCCATTGCCGTTACTGCGTGCATGCATGCCTATCGC
          TACCATTGCTCCGTCTGTTGGGATCGGTCGCAATTGTTGG
          ATGTTTCATCCCCAGTTTGCCATACAGGTGTATCAAAAGA
          ATGTTTCATTCCCAGTTTGCCATGCAGGTGTATCAACAGA
          TGCCCCAGTGTTTGGTCCGAAACGCAGGTGCACACGCCGA
          CGCACATGTCTTTGATCTGAGAGGCCAGCGTATTAGCCGA

