 8 1000
t1        GGGACTAACTTAACCAACTTGGGATCCTGGTCGGCGGAGGGGGCTGCCCTCCAACAATAG
t2        GGGATCGATTTTTTCGACTCGGACCTTTACTGCTTGGGTAGGCCAGTCTTCCTGTAATGC
t3        GGACTCAGATTCGTCGAATCGGACTCTCTGTCTCGGAGGTGAGCGATCCGCCAACCACCG
t4        GGAGCAGTTCGTTCCTATATAGACTATGGCTCTCAGGCCTGGGCCATCCGTTCCTAATAC
t5        GGGTTTCCTACGGTTAGTTTTAAAATCAACCGCTGAGACGGCTATACTTGAACCTGCTGA
t6        GGGTCTCATACTGTTCGTTTCAAAGTCAACCACAGCAACGGGTATACCTGAGCCTACTGA
t7        CGAACTGGGTCATCATGCTTAGGCGAGAGCTACCGGGGCAAGACTGCCCGCCAACGTTCG
t8        TAGTATAGTTTATTGCAGCTGGGTTCTCGGTTTTGAGTCAGGACTACATGCTCGTAATCA

          AAATTGTGTGCATGAATTCGATTCCAGTTGCTGTCGTTGTAATACCCTAGACCTTGCAAA
          GAACCGCAGATAGGGGATCAATTCGTCCCGCTGCCGCTCTCCCCCACTTGACGTTGTAAA
          TGGCTGTTTAAATGAACTTCCTCCTTACTCTTACTCCCCCCCCGGGTTTGACTTTCTGAA
          TTATTACTAGTGGGTATGTGACTGATGATACCGTTGCCACTCTAAGCCTTTCTTTGCAAT
          TCGTCCGATGCTTTAGTAGTGTTCGTTACAAAGTACTTTTTCCGCTTTTTACTTTGATAC
          CCGTCCGATGCTTTAGTAGTGCTCGTTATAAAGTACCTTTTCAGCTCTTTACTTAAATAT
          ATACTACCCATTTACCGACGACCTCAAGCTTTGTCCACGCATCGTATACCAACTTTCAAG
          GGACTAACCGTCTACGGAGGACTGTGAAATTTGCATGTGCTTAGTAAACCAACTCCAAGG

          TTTATTTCGACAGATTTCCCTAAAATCGGGCTTAATTGGGTGGATAGTACCCGCAGACTC
          ATGTACCTGCCGCTCACCTCTCTCAATGATGCTATGCGGACGAATCACATTAATTGAGGG
          GCCATTAACTGGCTCACCCCATAGAATGTGACCTTCGAGCCGAAAAACACGGATGACGTA
          ACTGGTTGGTATTCGTTCCCCTGCAAAGAAGCCGACCGCTTATTTAATACGAGTGATGTT
          TCTACTCGGGAGAATCATTAGGAACGTGAGGACGTTCCGCCGGACGTTCTACGTGCCGAT
          ACTACTCGAGAGAACCATTGAGAAAGTGGGGATGTTCCGGCGGACGTCATACGTACCGTT
          TAGGCGTTGCTATGCAAATATTAAAACAAGAGTGCCCAGCTAATACATTACCTCTACATT
          AAGTCGTCGTGAACTAAGCCGTCCGAAGTAAATGCTCAGACAAACTAGCAGTTCAATATA

          GCACCTATGTAAGCTCGGAAGAATCCCCGTAACCTTTTCTAACTCCAGTCGCGTCTGTGC
          GCATCCTTATAAGCACAGTGGGCGCCTGTTACCCTTTCCGTGCCCGGACCGCATTTGAGC
          ACGCACCTAATGGTGCGACGCCATGCCGACCCCCCCTTTTAGCTTGGGATTATCTCAGCC
          ACGCCCTCGCTGAGGTGGTGCCGGTCTGGGATGGCCTCTCAGTTCGAGCGGACTACGTCC
          CAGATCCACTAGACGTGGCTCAAATTCAAACATGGGTGACAATTCGCAATAGCATCGACC
          TAGATCTTCTAGTCGCGGCTCATACTCAAGCATGGGGGACAATTTGCACTAGCCATGACC
          CTGGCTCAACCTCGCCCGCAGAGGCTTAGAGTTGTACTAAACCCTGATTGCGTACGGAAT
          CCGGCTTAAAATAGTTAGCAGAGGTTCTGAACCATTCTAAATTCTGTTTTACAGCAGAAT

          CTACACTGCGATGTGACTCAACTGACCAGTCGGGTGGGGGATACGTGATGTTACACCATA
          CTACCTTTCGATGTGTTACAACCTTCCTGTCCGGTACGCGTTGCATGACTTATGCCCACA
          CGCCCTGGCAAAGAAGTACGTTTGTACACTCGGGTGGGTGATGCATTCCATATTCGCATA
          TAACAGGGTAATGCGGTTTGGGCGAATGGATGCCTGGGCGCAGAGCAAAGCATCATCACA
          ACAGATCACGGTACGGGATAATTGAACGACAAAGTGGCTATTGCGGAACGAGTCGACACA
          ACAGATTCCGTTACGGAATGATTGAACTGCAAAGTGGCCACAGCGAAGCGAATGGCCACA
          TTCCAAGGCCCCAGTGTCCCGGGATACGCAACAAAAAGAGCTATAGAATGCGTTATTTAA
          TGGTATGGCCTCAACGTCCCGGATTGTGCAAAAGACAGAGTTAGAGCATGCGTTATTAAG

          TGAGGCCGCAAGGCCGGTAAAAAATTAATCCAACGGGAATAGGTTTCGTACGTGTGTAGA
          TGGGGAAACGAAACCGCGCTTGGCATAATTTAATCGAACCAGACCGGGTCCAAATATAGA
          CAGAGTAGTGGACCGATGTAGCGCTGAATGTGTCCAGAACCGACTCAATCAAAACATAGA
          CGATTGAACGAAATCGTAAATTAATATAAATAACAGGAATTGCTCGTATCTACAGTTAAA
          CGATGAGGCCAACCTACAGCTGGGACACCGTAATACATGATGGCTATGGGCTTATCCAGA
          TGGTGAGGTTAACCTGAAGCCGGGACACTGTGATACATGATGATTGCAGACTTATCTAGG
          CCTAGCCATGGAATCCCGCATAAACGTGTGTGGGACGCTCGAACTTACGCGAGAACCAAG
          TTTTGCCATCGAGCTACGTATATACACCTGAGGGGAGCTGGTATATAAGTTAGGGTTCAG

          TCCGATTACGTTGGCTTGCTGTGGAGGGTTAAGGTTGATCACTATCACAGTAGTAAGCTT
          CACGGCCATGCTGATTTGCTGGGAAGGGTAAATACACGTCAACGATAGTGCTTCTCGGCC
          GCTTCCCTCGTTGCCTTCCTGAGGCCGCCGAGTGCTAATCGATGACTGAGCATAGAGGCA
          CCGCTTTCCACTGAGGTGCTGTGCAGGCCGAATTTTAACTTGCATTTGGTCTTCAGGATA
          TTGCCTCCCACCCAATTTCTATGGGGAATAACTTTTACCTGGCCCCGGCATTTCTAACTA
          TTGCCCCCTAGCCAAATCCTGTAGGGAATGAATATTAACTGAACCCGGCATTTCAATCCA
          CCTGAGTATACTGATTAACTGTAGATGCAGACCGTTGTTATATTATGGGTGCTCTACATG
          CGTGACTAAATCGATCCCCTGTAGACTAAGATCAGTATTAGCCGAAGTAGGTCTTGCATG

          TGACATTATAACTAAGGAGGCCCAGTAACATATGTGGGGACATTCTCAAGCCAAATAACT
          CAATGGGATTACTACGGAACTTCTGCCAAATACTTTTTTACGTTCTCAAGTCGGCCGAGA
          CCGTACTATCCTTCAAGTTGCGGTGAGATACATACGTACAGATTACCTGATAGGACAGGA
          TAGTGCCTCGGTCGGCGTTAGACAGTGGCAGCTCTGTAAAAGATCCAGCTTCCACCGGAA
          CACCGTATGAAATATGGTCGTGACACGCCGTAACTATGACAACCATAAGATTCACTGTGA
          CATCGTATTAAACATGGTCGTGGCACGCCGTAACTATGAAAACGATCGGTACTACCATGA
          TAGAACATTGATTGATGTTACGCTGTGGACCAGTGATAAGTAATCACCGGTCGCTCGCTC
          TAGCCAACTAGCTAAAGATTCGATCCGGAAGCGTACCTACTAACCACAGCGCGCTCACGC

          ATGACAGGTAAAGTGTGGGTCGGGTATGGTGCCTTCGGGACGTTAAGCCGATGCGGGCCG
          CCGGTGGCTAGCGAGTGCATAACACATGGTATATGCGTAGGGTTGAGCCTACGCGAGCGA
          CCGAAATGTGAGGCGAGGCTTATCCGAAGTATATTCGATCAACCAGGTCAAGGTATGGCG
          CCGTTGCATGAAACGTAGTCAAAACGCGGCATAGATGGTGGGCCGGGACAACACGCGGAT
          ACACCTTAGTCTGAGTCGGAGACCCAGCCTACCTCAACTGCACTTAGACAGGGGAACACT
          ACACCTTTGTTTGAGTCGGAAACCCAGTATACGTCAGCTGCACTTAGCCAGGGGAATACT
          TGGTTGGACTGCACAGGGCTAACCATGGCTGTGCCTGCAAGATAGATTTGGCAATGAGCC
          TGGTCGGACTATATAAGGGTAGTCTAGGATGTGCTTCCAGGATAGGTATGGAAAAGGCCC

          TTCTCAGGTCGATGTAGCCTAAATTGGTGGTTTCTCGTGTGCCTAAACTGAGACATCACC
          TACGGAGAAAGACGCTGCTACATTCGGGAGTCTACCGTCCGATGAGACAAGGCTACTCCT
          TACGGTCGTCGAGAGCGCCCGATTTGAGGGTTCCACGAGTGTTTAGAAGGGGGTGTCGCT
          TATCCAGATAGCCGAAGTTTTATTTAGACACTTGTTATGAATAGATAAAGGGGTATTAGA
          TGTCGACGCATTCGATGCTTGAATAAGGAGCCCGGTGTGTGTTCAGAAACCGAGTACGCA
          TGTCGAAGCATTGAATGCCAGAACCAGGAGCGAGGTGTGTGTTCAGAAACCGAGTACGCA
          ACTGGCGTCCAACAACACCGTAATTGAGAAGAGGTCATCTGTCAAATAGCGCAATCGTGC
          AAAAGAGTGTAACTGCATTGTGTTTAGGCCTCCGTCACCCGTATGTTAGAAAGCTAGCGT

          TCTGCTAAAAGCGCTAGCCCGTTCCCGACCGTGGGTTGCAGTCACTTATTGTCCATTTTA
          CCTGTCGTGGATGCTAACCTTGTTCCACCCATGGGTGAAGGTCAGTTATGGTCTCCTTCA
          CCTCTAGTAGATGTTGATGCGTCCTTGCCTATGGGTTTAGCGCACTTATACTTCACTTTA
          CCTGTTGGAGGCAATTGCAACTTCATGCTCGTGGTCTAGATGTTCTGGTGTTTCCCGCTT
          TCTGTGTTGCAGTCCGACGCATCGAAGTTCGTGTCTTACAACCCGACATTCACGCGCCAA
          TCCGTGTTATGATCTGGCGCATCGAAGCCCGTGCCTTGCAATCCGAAATTCACATGCCAA
          TATGGTGCACAGTATGCCGTCTAAAGACCAGCGTTGAAAACGCTCATTTTGCAGGCCCGG
          CTTGGCTCCCAACAAACAGCCTATAGACCAGCCATTCGAATGCCCGCTTTGCATGCTCGG

          TAATTGCTCGCTCTAAGATCTCCCTTTTTAATGACGATGAATCATCCTCACGCCTTGACC
          TAGTTTTTGCTTCGTCAGTCGCCCCCCTTCGCGTTGACGAATTCCTTCCTTTTATGGGCT
          TGAATGTTGGTCCAAGAATTCTCCTCCTTCACAATGGATGACTCTGCTCATATGCGAATT
          TAATTATCGCGTCAGGAATTCTCATCTTTAGTAATGTCCGATTTAACCTTTGCATGGACG
          CAACCGTCGGGATGCTAACCCCTAATCAAAGTAACCATGGGTCGTGTCAACATTCGAATA
          CAACCGTCGGGATGCTAACCCATAATTTTAGCAACGATGTGCCGTGATAGTATACGAAAC
          TAGAGGTCGACATGGTCACCCTCACGTACCTTAGTGGTGGGTTGCACCATTGATTCGATT
          TGGAAGCGGATACGACCCTCTTTAAGTATTCCAACGGCGGGCCGCACCGTCGATTTGGCA

          AACATATCCTCGGACTCATTTGGCCTAGCGTTGGCATGTAAAGCAGAATCTACATAAGAG
          AAAAACTCCTTAGGCGGATTTGAGTTGGCTATCGCTTGTAAGGTCCACATAACCCAGAAG
          GGCATCCACTTGGCTCGTCTCAATTCGACTAGGACGCGTCCGGCAGATATAACCTCATCG
          GGTATTCAATTGGACAGAGGAGTCTATGTTATAAAGTATAAAGTTTACTCCGCCCAGTTG
          AGCACGTGCCACTGCCTGTTTAGCCCTGTTGTAGATGCTCATATCGCAGCAATATAGTAG
          AGCATGTGCTACAGTCTTTTTAGCCCTATTGTGGATGCCAGCATCGGAGCTACATAGTAG
          CGGGCTAATCATGATCTGTGGGATCGTGCTGCGTAACATTCGATTCATATTGCTGCCCTT
          AGCAACAAGTGGGCATTGCGAGATTGCACAGTGGAAAATTCGGCTTCTGATGCCTCATCT

          CCTGGGATAGAGCCTAGAAGGACAATCCCCCAGATAACAGAATGGTCAACTAGTGATATT
          CTTAAGACGAGGTCTAGGGGGGCACACGCGGGGTTGCCAAAACGATCAGCTAGCGAAGCT
          CTAAGAGCAATTGCGGAAGGCGGGGTTCCCTGATTATTTGCACGACTCAGTAATGCTGCT
          CCTTGTAAACACCCCCGGAGCGCCACCAGGTCGTCATCTGTATGAGAAAACTACTTAATC
          ATTTGGGGAAATACCCCGCTTGGAGCCCAGCAGGCATCTGTACGTACATAGGTGACACTT
          ATTTGAGGAAACACCCCGTATGGAGCACCGCAGGTACCTATACGTACAAGGTTGAAACTT
          TTAATCGGAAATACCTGGGGCGTCCTTACTAGGGCGCCAAGCCCACTTCGGAACAGCGTA
          TTAACAGGAAGCATGTCAGGCTTACACGTTCGGGTGCCTTCCCTAATTCAGAACAGGACA

          GTAACACGGGAAGTCGTCAAGGAGATCTATCCCAATCGAAACACAACGGTTAAACAACCT
          AGCTGTTACGATTCCGTTGAAGAGATTTTGCGTGATCTAAAGGGACTACTTAGTGATTTC
          GTTCTGCAATGGGGTTTACGCCACATCAATCTCATTTCAGAGCGGATAGCTAGGCAGCGT
          GGATTATGCCAGGTAGCTCCGACTCCCTATTCCTCCAGAAAGAAAGCAGCTTTCTAGCCC
          GAGTTGAGAGCACCGGCCAAAGCGTCTAGCACAATTGCAACGTACTTCGCTGATCCACTG
          GAGCTGGCATCATCGGCCAAAGCGTCTAGCATGATTGTAACGTCCTTAGCTGTTCCACCG
          GGGCCACGGTGAATCGGTCCATCTACCAAGGCTGCTGCAGTGGAACATCCAAGTCTACGT
          GGGACATTGCAAGTCATCCCATTACCCAAGAAATTCACGCAGGACCTGGCCTGTTTACGT

          TAGCTGCATTAGATCGACACGATCATGGGACGAGGTTCGCAGTGCTACTGAAGCTGCGGT
          TAGTGCCGGTCGACTAGCAAGGCCCGGGACGAGTGTTTGCAGAGCCCCTGATCTCACGGT
          CAGCAACGCCCGACTGGTAGCCTCTAGAGACAAAGTTCGTAAAACTTCTAAACACACGGT
          TCGCAGCGTTCAACCGACTACATCCGACGCAAAGGTATATGACATGACGGAATTTGCGGT
          CCGCAAGTGTCAACTGGCGAGGTTAAGTGACGAAGGCTGCGGGCCTTGTTAACCCGCACG
          CCGCAAGCCTCTACTAGCGAGGATAAGTAATAACGGCGACAGGACTTGTAAACCTGCACC
          CACTTTCACTAGTCAGGCGATCGTTCGCTGTGGCCTTCTCAGGATCATCGGATGCGGGAT
          GACGTTGAATCGGCAAGTTATGGCACGTCTTCGCCTACTTAGGTTTACCGGCTACTGAAC

          GGAGGTGCTTGATAAAAATGCGAAATACAGAAATTAAACC
          GGGGATGTTTGATAGAAGCGCTAAAAATCAGTCTCAGGCT
          CAGGATGCTCAGGACAAAAATAATGCAATGGATAAAGGCT
          AAGTGTGTTCGATGTCCGTGTGACAAAACAGTTACCGTCT
          AAAGCCCCCGTACAAAATAACATTTACGAGGGTCTAAGTT
          AAAGCCCCCGTGTAAAATCACATTTACTAGGGTCTAAATT
          AGCTTAATTGGGCATCAATTTCACAGTCCGGAACCAAGGT
          AGTTCAGCCAGATGCAATTGCTCCAGCACGGAACTGAGAT

