 8 1000
t1        AGCCTAGCCCGGTGCGAATCGGGGCATAGCCCACTCCAGCCCATAGTCCGGTAAGTGTGT
t2        CGAATGGCATAGTGAAAATTTGTGCTTTCCCCTAGCCAGCTCATCGTATGGTAAGTGAGC
t3        AGACGGCACTATCTTGAGACGGCTTCTTGTGCTCACTAGACACCGACGGGATCCATACAG
t4        GTAACAGTCCCATGAAGTACGGTGCCGTGCACTCGTTGAAGCACTACCTGAGACAATTCC
t5        GATACAGACCATGCCAAGAATCATCCCTGGTCACACGGGCCCACAATACAACCAATGAGC
t6        GTTACAACCCATTCCGAAACCGATAGCCGACATTGTGAGTCCGTTACAATATTAAGGACC
t7        GTTCCAGCTCTCTTTGGGGGGCTTGTCGAGCGACTCGGGTGCACTACGGGTGGGATGAAC
t8        TTCACAGCCTACCTGATATAGGGTTCCGTTCCATTTTAAAGTATAACAATCGCAGCGTAT

          ATAGACTGATTGAGGCTTCAGCAACGGAGCAGGGGGCTGGATTAGCAAGTCTCCTTATCT
          ATAGGTCGGTTAAGGTTCAGGCAGTGGAGGGTGGGCCTGGGTTAACAAGCTTCCTTATCA
          AAGGTCTCTGTGGTGCCCCAACAGCTCAAAAGAAACCCGGGTGGGTTATTTTCCTCCCTA
          GCTGTCCACACCGATCCTCTTATGCACTGTACTAGGTGAGAATGGAGATCCTATAGGTCC
          GTGGGGCGTCCGAATAATGAAAGGCCTAGGAAGGACTAGGAATATGTATCGCCCCCTCTC
          GAGGGGTCATAGACCATGAAAAATCTTAGGAGAGGCCAGGAGCGAGCAACGCATCCCGCT
          GAGTTTCCCCTGCTTCTTCGCGGACGTCACGATGGTTTGCATTGGTTTCCACTAGTGACC
          GATTGCGATCGAGGTCTTAGAATAAATAACGATGGTATGTATCGGACCTGTCTAGTTACT

          GGGCACTAGGGCGAATTGCTTGCGCCAAAACAAAGCGGGTGGTACAACTTGCGCAATATA
          GGCCGCTGGAATGCAATGCCTGAGCCTAAACAACGCGGGTAATACAGCCTGTGCAAAATC
          GGGTCGTGAGGCGAATGGGGAGAACTCCTTAGAGCACAGCAGTGCTGCTTGTTACCAGGG
          GACGTCGATAGATGATAAACTGCTTCTGTCTACAGTAGCTAGGTGAGCGCGTGCTCTGTC
          GGGTCATATCGAGGAACAGGCAACACTTGATGATGGGGGTAGGTTGACTCGAAACGCGAT
          GTGCTCTACTAAGAAATAGATAATATCACGCTGGGACCGCAGGGGGGCGAATCTTACGGC
          AGATAAAGACGGTAATTTGAGAATATTTGACTAATAAACCGGAACTGCATGCGTCTTCGC
          CGGCGAAGTTGGATTCTGGAGGACGATCAACTAACAGAACGGTACTGGTAAGATGCCAAT

          AACAATGACTTGGTGCTAATCACGCAGACTAACCGGACGCGTTATCCGCAGGAGGGCGGA
          AGCAATGCCCCGCTGCTACTTGAACAGATTAACCGGACGAATTTCTTGCAATTCGGGGGC
          GATGGTGTTCATATGACAAGAGTACAGTTTCGGCCGACGAACATTCTCCGAGCTTATGGC
          GTTACTCTAGCCGTAACGGCGAAATAAACCATTCGAGTGAGCCATGTAGTAGACAGGAAA
          AGTTGCGCGCCCCGCGTAATGGGGCAAAAGTCTCCTCGGATTGTATTGCCGGATGTAGTA
          AGTCGTGTGTTCAGGACAGCGGCAGGGATCTATCCCTAGTCCGTATCCTTGGATGTCATA
          CATCTTGTTCGTACGGCTGTGGTAACACAGAGTTGGGCTTACCCACCACGAGCCGCCATA
          GCTGGCGCCCATGCATTTGTAGCATAGAGCAAATAGGTGGATATTGTAAGAAACAAGAAC

          TTTTGAGACCTATCACCAGAGTTACGAAGAGCAAGACGAATACGTCATGCGGAACTTATG
          ATTTGAAACCAATAATTAGTGCTATGAAGAACCTTTCGAATAAGTCACCAAAAACTTACG
          AGATGACAGGTATGTCCAATTCCACGTCCGGAACTTGAATCTGGACCCGCAATACTCGTA
          AAATCTGTAGCCCACCATTCATTTAGGTTAGTGAACGGTCGGCGCATACTCCCATGCTCT
          AGACAGGCGGATAGAATGTTTATGCAGTAGGTAACCGCGATTAGGCAATAAGCCTGCCCA
          AAACAGGCGGGTAAAGGAAATGCGCAATGGGCATCCGCGCCTGATCAATAAACTCTCCCA
          CGCCACTCCGTGTAATCTGCGACCTCGTAGTCGAACCGACCAAGCTTACATTTAACCTCG
          TGCTATTCAGGCAAATTGACAATCCTGATGTTAGGCGCATCTAGTATGCTGCCAACCTTA

          ACGGTGACTCCTGTACGTGATCGGCGGAATCGTAATCAAGCGTATAGGAGCGCATGTGCT
          ATTGTGACTTCTAAACGTGGTCCACAGGATTTCAGGCGAGTGCGCAGGAGCGCATGCGCT
          ATTGTACTCTTTTCTTTTGAGCGCCGGGACCTTCAACAAATCTCCCGTAACAAAAGCAAT
          GTGCTTAGAGCACGGCTACGCAGACACAGTAAAAAAAACGAGCGAGCAACGAAGTACGAG
          GCAGAAAACTACGGGGGTTCATGGCAGCATCCACGCTGTGTGCTGTATGTCAAGACCGGT
          GTAGTAAATATCACGCGCTTGCCGCAGCACACCAAGTGTTTGGCGGCAAGCAGGACTAGT
          AGATACCGCCATCAGTATCCCTTAAAGACGGCAATCAAACGTTCCTGCAGAATATTCGTA
          GTCTCAGGCTGCTTAACCAGACATTTATTCAAGACCAACCTAGTTCGCGTAGCTCTGGGA

          ACTAAAGCACGTGAGACCACACAGCTATCGTTCTAGCGTTAGAAGGAACGGGATTGGCAA
          AACAAGCCAAGCCCAGTCATACCGTCGAAGCTGTAGCGTCTGAAAAGACTAGACCGGAAA
          ATCATAACAAACCCGCTTCTAGACCAATCCTCGTGGCGTAGCAGTCAACCCAAGCGGCAA
          GGTGATATCTGCTGGCACCTACCCCCCCCCATAGTATACCAGATTTAGATGGAGTGATGA
          ATCGCAGCGGGCACATGATTAGGGCCTATCGTGAAAGGAACCGATTGATATGGATGCTCG
          GTCGTAGTGAGTGCATAATCATAGTCAATCGCGACGAGATTCGAATAAGATAGATGCTCA
          ATCGGAAGATACTGGCGTTCGAAGTAATCCGCCCTGCGACGTAGTGTAGCCGTCTGTTTG
          ATCGTTGTCAACTAATGGTCGATGTCGTTCGCGCCGTTATGCGGCGTATTCGCAAGCCCG

          GTGGACTTTGAGTAATCAGCTACGGGGGTATACAGATGGATAATTAGTTTCGTGAGTCTT
          GTGCATTCCCCGTAATGGATGAAGGGGGAATCCAGATAGTTGATTAAACCTGGGAGTCTT
          GCTCAATTAACAGGTTAGGTAATACAGGCGTTCGGGCACATGCGAGAACTCACCAGGCAA
          TCCTAGCACGCACGGTATCCTATCACTGAAGCGGGACCAATGGAAGCATGGCCCGACAAA
          ACATATTGTCCGCGCGCGTTAGTACATTTGGTCGAGTAGATGATGCCGTCTCAATGTAGC
          ACATACTTTCTCCGCACGTTGGAACACTAGGTAGAGGAAAAACTGCCGTCCCCACCTAAC
          GGGGAAGATCCCCGTCTGCCAACGAAAAGTCTTGCCTGTATGCTGACGTTCCCATCAAGC
          TAAAATCATACTTGTTAACTAAAGGAGAATTATCCGGACTTGCTGATGCTCTAATTCGAC

          TAATAAGCCTCATATAATAATGCAGCGTCGTATTCGCGCGACGTTCTACTCCCGAGTCGA
          CATTATATCCTACCTAACGATACGGATCTGTTTCTCCGCGCCTTAATACAGATGGAAAGC
          TATCAAGGCCATATTTGCAAACTAATTAGGTACTCCGACGACCTTCCGTATCCACGACGC
          CTCCGCTCCTTGTTACTTGTGCTGGCCCTGGCAACCGTTGGTCCTTCAGCCCGGTATTGG
          CTGTACCGATATCCCTACTAGCAGGCTCGTAAGTGGCGCGGACACTTATACATACTTCCC
          CCGTGTCGACCACTCCGGTAATAGGTTTGAGGGTGGTGCCCGGCATGCCACATTCAGTGC
          CGCTGGATTGGTGACTTAATGCTTAATTTAACTGCCGCTGACCCACGACGTTAAATGTCA
          CGCCGGCCTCGTAATCGATGGCTTCATCTCGCTGATAATGGTTATCGTAGTCCCTAGTGA

          ATGAGTTAAGATGTTGTTGATTTAACTTTGGCCGGTCTGTCCATCCTGAGTCACCATGAG
          GTGAATTCTGGGGTTCATAAATAGCTTCTGGCCGGTGCGTCTATCTTGGAGTACCATGAG
          GCGAATGCAGGTCTTGATAGACGCAGAACGTCAGCCATTACCGCTTAACACTTCTGTAAT
          CCGAACCTGTGCGTCACTGTCGAACAATGACCGGGTGTACTCGCTTTCGGCCGGTAAGTG
          ATGAACTTGGGCTTAGGCACTTGTCTGGCGGGAGGCCCGCGGACACATACTTTTAACAAC
          GAGTGCTAGAGTTTTGGGACACGTCCAACTTGCAGTCCGTTCACTCGCACTTCTTGCAAC
          GAACGTGATCGACCGGACACTCCCCTAGTTGCTGGGTAGCCCGCCCGTAGCTCGAGCACT
          ATGTACGGCCGATTCTTAATCTATCTTGCCGGCAATCATCCCGCGCATAGTAAGAAAGTC

          GACCTCCACCGCTCATAGAATTGGTACCAGCGTAGATGGCCCGTCCAACCGTTCGCTCGG
          GACCTCGTCTATATATCATATTGGTACCAGTCTAGATGGTGCGTTTAGCCGCATGATTCG
          TCTTCAGACTTCTCGTCGTGCCGACACCTGAGTACATGTTCTCAAATTCTGGGAAGATAG
          GCATCGAACAATGAAGTACACTGATAATCGACAGAGATAACTTCGCGCTTGCGCGGTCAT
          CGATTATGCTATTAAACTCATCACTACTAGATCTGAGAACCCCTGCGTACGGTAGACCAC
          GTGTCGTGTTAATGGGCACCTTAATACTAGACCAGATAAGCCATGCGAACAGAAAAACCC
          ACTTCGTATTACCGGAAACACCAGTGTCTATTGGAGCAATCAGTCCAGTGCCTCCATCCA
          GATCCGTGCTACAAGATCCCCTGGTATTTGTAAGGGCGATCGACCTAGTGACGTAAATAA

          TTAGCACAAGCACCGGACAATAATCCTATTGTAGTTTCGTCGACGCTTGCACTTCAGAAT
          ACAGCGCAAGTATAAGGCCGTGGCTATATCGTAGTTCCGTCGATGTTTGCACCTCATCAT
          ACGGCGTGTGTAGAAGATCACAGATCTGTCGCCGCTTCATGGATGTCTAAATCCCACCGA
          TGGGCTCGTGTTATACGGGGTATCCCATCCAATTTGGTCAGCTTGGAGACCGTCAAAAGC
          AGGATAGACGTTGCCCGAGACAGCGCTGTTGTAATTGCGCCTCTAGTCCTGCTTAGTGAC
          AGGTTACGTATCGCGGGAGGATGCATGTTTGCAACTGTACCCCAAGTCGTGGTTACCGAT
          ATCGTTTGAGTCAATGGGGGCATTCCTTGTGTAAACTATTCGGGAACTTAGACTGGTAAA
          ATTGCTCGTGAATGAGGACCCGTCCCCAACGCAAACGGCGCCGGAACCAGGACTCGTAAA

          GCCCTACCAGAAGGTTCTCTTGTCGTTAAAACCCAGCAGTACCCTTTCCCTTGTGTCCAA
          GCCCGGCCGTATAGTTCACTTACCGTTACAACCGCATGGTGACGCTTGTCTCGTGTTCAA
          GAAAACCCGAATGTCGGTTCTAGTGGCCACTCGACGCGAATGGTTTTTTCCCGCCGAAAC
          GAATGTGCACGCACCTAGTCCGCTGGCCCTGTGCCCCACAGGCTTCCCAGTTGACCATTT
          GTACGATTTATCCCTGTCCTTACCGGTCGGATATCTGGTAGTTTCGGCGTTTGTATCTAA
          ATGGGGTCTATTGCTGTCTTTCTCAGTTTCATGTCTGGCAATATTGGCTCCCAAGCTTAA
          CTAAGATAACACATTCGGTCGAGGGACAGCTTACCCTGTTCACTCCCCTATCCACTGTGT
          ATTCGATAACAAAATTAGCCAGTCGCCAGCTTCGCTGGGTGATATTCACTATAGCCTTCC

          TACAGCTAGAGCACATCCTGGGAATTGGTACCTGTGGAAGCCAAGATCCAGTTAGCTCAC
          CCTAGCAAGAACATAGCACGAGGATTGGTACCAGTGAAAGTAAAGATCCTGTCGGCTGAC
          ATAGGCTTACGCGTAAGACTACAACTTTTGCTAGCATTGACATAGTACGCGCTAGTTATA
          GCCCATTTCGATGTAACGCTTTGTTGAGCTTTATTAACGTGAGTGAACACGTAGAACAAA
          CAACGGCAGGCTCAACGTTGACCGCGGTCCCAGACGGATGTGACAGTCGCGTTAGGCTGG
          TGACGGCGGGTGTTAAATCTATCGCGACCCGCCCCGAGGATGACGGAAGCGGTGATCCAG
          GTAAGACCCTACCTCTAGCTTAGACGCAACGCAGAAAACGAGAAAATCCAGACGGCCAAG
          CTATGGTCTTACGTACCGCCGAGATGGGGGCGAATGACTAAGGAAACCCACACTGCAAAG

          GATATCCTTATCGGTCAGGCGGCATCTATTCTGGGCGGTTAAAGGTTATTTGCAGCGGCG
          GATTGCCTTACAGTTTATGCGGCATCCCTTCGGGGTAATTCAAGGTTGGTAACAGAGGCG
          CTTAAGTTATGCGACCGCGCTGTGCCCTCTCAGGGCGCCATATCACCAATGAAAGAGAAA
          GTTTGGCTTCCCGAAAGAACGAGACCTTGCGAAAGTAGGATATGGATGCACCATGAGATG
          TCCAGGTATACCTATCACCCCCAGCTTTTTGGCTGCGCCTAAGGAATGACAGCACAGGAG
          TTTAGGTATACATAACTCTTCCATCTTGTTGAATTCACCCCTGGAAAACTTAAATAGACG
          CGTGAACAGGCAGTCTATGTGCCACACCCTGTAGGGACCATTCTCACGGCTAGAAAGTGA
          CTTGGTTATCTAGCGTTAGCTATACTACTAGTAGGCAGCCCTCGGATGGCTGAACAGAGG

          GTTTAGTGTATATTCATTCCAAACTGCACGCCCCATACTGCTTTATCCGCAGGCGCACTT
          GTTAGGAGTCAATTTGCGTCCATTTGCACGCCCCATACTGACACGCCAGCGGACGCAATC
          GCTTTATTGCCAATTAGCCCATATCGTTATTTCCGAAAAGATCCTTTTACAGGGGAGAGC
          GCATGATGTTCTCTCCGCACCCGCAATTATTTCGATGTGCGTTCTTTATCATTGCTCCGT
          TTGCTGTGTTTATCTTCCCTCTCCTACCACAATAATTTATTGCGTCAAACTGAGAAGAGA
          GAACCGAGCTTCTCTCAACTTTTCTATCAGCAACATCTACTCCCCTCAACAAGGACGAGA
          GCAAGGTGTCAATCCCATGCACATTATCCCATACGCACGGCCTTGTCAGCCAACGAAGTC
          GCGCGGGAGCTCGCACACGGGAAACCCTTCCCATCTGTAGCTCTACCGCAAAACAAGAGT

          CTAGGAGTCGCTGACCGAATTGTCCCCGGTATGGCCTTGC
          TCAGGAGTGGCTGACAGGCGTATCCCCGGTACGGTCCGGC
          TCCGGAGCCCCAGCCAGGTTCGTTAGGGGCTCCAATTTGC
          CGCCAGGACGCGTACAACTTATCGGCTGGCACGAATACCT
          TACCCGCCAGCGAATCAATCCCTGTCTGACGTGTACGTAT
          TATTGGCCAGAGGGGCATTCTTTGCTAATCGCTTCTGGGT
          AAGTGTCTCGTCGCTTGGCCTGCGTCCTGAACCAGTTCCC
          ACTAGACTAGACGTACAACATATGTTAGGTTCCTTTACCC

