 8 1000
t1        GTCGGCTACTCTACCGGAGCCGAATGATGTTCGCGGAGCTATAGATCGGTTCACCGGCAC
t2        AGCGGCACGTTTTCCGGAGTCGAATGACGTTCGCGTATATATAGATTACTACACCGGCAT
t3        TACGTAGCCGTAACCAGGGACGATTGGTAAGCAACAATATACCGGTCATTCTTGCGGCAC
t4        CGCGCCGCGATCTCGAAAATCCGCCGATGGCTTTGATACTATAACATTTCTCCCCGATAA
t5        CAACGTTGATTTGGAGCAGCCGATACACATCTGCAATCATGTTCGCCGGTATACAGACGC
t6        CGCGTAGTCCACTCAGAAACCGGATGATATACGTGGTATCGTTAGCCGACTAACCGGCAT
t7        GAGGTAAAATATCCCTAATCAAACTAAACATCGGTTATTATTTGGCTGTGCCATTGGCAC
t8        TGTGTGACGTTGTATCGGAATGAACTGTCTTCTGGATCTTTTAGACTGGGCCCTTCCGCC

          AAAGTACTTCTGAACTGGATAATGGTACGTGTGGGATCAGTTACGTGTCCTCTAGTCGGT
          TGGGAGCTTCTCTGATGGATACAGGTTCCTGCGAGATCCGCTGAGGGACCTTTGGCTCGT
          GACGAATTTTACGAACCAGCTAAGGCATCCGTGGCATTAGCCCCAGGCCCTTTAGCAAAA
          GTCTACCTTAATTAGTGAGCAACGGTACTTCTAGAACTGGCCGGGAGTACTTCAGCTGAT
          GGACGACTTCTTGAAAGAGGACCAATATAGGAGAGAATAGTTATAAGTTCTTGACGTATC
          TCTTCATCTCAAAGGAGGGGTACAGTATACACAGAGCCAAGTCTTGGTTCCTGAGATGGC
          GTGCAACGTGATGAAGGGGCAATCGAGTATTAAGGACTAGACGTACATGCCCCAGTTGTA
          ATTTGACACGCCGACATGCCTAACCGACATGGGGAATAGGCCCGCAATTTCCCGGAAGCA

          ACAGGTGCCAGGCTTGTATCCGCGTAGCTGCCCTGCTAGAGATCTGGGGCTTCCATAAAG
          ACAGGTGTCAGGAGTTTTTCGGCACTCCAAGCCTGGCACGGGCCTTTGGTCTCCATCTAA
          ATAAGTACTAGAGTAGTGTGTCTATATCTACTCCACCACTGGACTTTATTCTCGTTGTAG
          ACTGATCTCAAATTTACGCGCACACGCTGGCCTCACCAGGGGATATATTCTTCCCCACTG
          ACAAGAGCCGTGAGTATGACGGTATAGCTGCCACATCAGAGACGCCAGTCTCCGACTTTA
          ACAAGAAGCCCGATTAAGACTGCCAGGCGGTTCTGCCAGACGTAATAATACCTGACGCTG
          GTAAGCAATAGGTTCGACGTTGTGTGTCGTACACACGAGCCGGTCCCGGCCGAGTAGTTG
          CTCGAAGTCCTGGGAGGACTTGTCTCACTCTTGCTCAGGGAGCTATATCGACCGTTACCA

          CAATCGACATTGCTTTATAGTGACTCGAATATACTCCTGTGACCATGAGCAATGGTGAAG
          AAACCTGTGTAGCCATGTAGTAACCTGGACCCCCACTTGTGTCCAAGCGCTATGATCAGG
          AAATTCATACAGTGATACCGTGGCGCGAACCTGCAGCCGGGTCTAGGTGGGATAGCGACA
          CAGTCTGTAATGCAATGCGGCGACCCAAACGCATCGGCGCACCCAAGCGTGCCGCCGAGA
          GACCTGAAAGAGCGGCAGGCCGTCTCGGATAAGTTACCGAGCTTCAGCGTAGTGGTGAAA
          GGCCTCGCGCTACACTCGGCGGATTCACGTTAGGCGTAGCTCTTAGGCCTAGCGCCCAGG
          GACGTTACACAGCTAGAACTGGGCAATTCTACCCCAATACTAATTGATCTCGCTGCTGAA
          GGCGTGATATTGCCCCAGCTGAACTTAGAGTTAAACCAGATTCTAATCGAGGCGGTGGCT

          CTCATCGACAGGGCGTTTATACGGCCGATTTTCGTCAATACGTGTCATGACCGCATGGTT
          CTAGCCGACAAGGCGCTTATACAGAATCTTGTGATCAACTAGCTTCGCAGTCATGCGTCT
          CTTGCTGACTGATTGGCTGTGCAAAACCCCCTCGCTCAACAGTCCAACAATCCAATCCTT
          TTTGCGGACCGGGCGCCAGTAGCAGAACCGCTTGTCTAATAGACTAATAAAACTAAGTTC
          TCTAGGGAAAGACTACATGTATCTACAGTCATTGCCCACTTGCCAGGGAAAATCTTGATA
          TTTACGGATCGGATGTTGAGGTCAAAACTCTCCGCTTTCCCGTCAAGGAAGGCCAGATCT
          CATGCGGTGCGTACGCGCGCGGACAAACCTGGTGCTTGCTAGGCTACAAAGACTTTGTTA
          ATCGTGATTATCAAAGACACGTGAGCAGTCTCCAGAAATTAACTTGTAAGGCATACCCTT

          TCCGCAATGCCGATAATACCGGCCAAGCCCCTCGAGAAGCAAACGTCCGGTTGTCGAGAT
          CCCGCGATGGTGTCAATACCGATCTACTCCCTTGACAACAATTCGTTCGACCTTCAAGAC
          CTTGAAACAAGGGCGAGAGTCGCTAACTTTTACGAGGGAAAAATATCCGCAGGTTTCGCT
          TCCTTAAGTGAGCCATGCATCGACCGACCCTTCCAAGGGCAAAAAGCAAACTCCACAGCT
          CTCATGGTTTTGCTGAAGACTGCTCCCCTGCTCGGGAGATACATGAACGACCACGTAAAG
          CTCAGGATCGGGAAGAAGTTAGTCCATCTATTTGTTGGGAATCTACCTGAGCCCTCAAAT
          CTGACAATTGTGGGGGAGATGGAGGACCGCCACTAGCGACGGACGTCTGAGCTAGCAGAC
          GAATTCTCCCTGGCGAAGGTGGATTTTAGATGTGGCGGTGAATCAAGATGCATATAGGAG

          ATGCGGAGACCACGAAAGAGGCTGGGCCCGAAACCTGTCTTAGGGCTTCGGGTACATACG
          AGGCGTGCGCCACGGAAGGGGCCGGACCCGCTATCTGTATCTGGGTATCGGGTACATACA
          ACGAGGGTGCTACGCAGGAAGGAGGCTAGGCTTCACACGCCAGGGTGTCGCGCTTATACG
          CGGAGGGTGCGAGGAAAGTAACGAGTTCCCCTCCTTCGGTCGGGGCTCCGGAAATACATG
          CGGTGGATTTCATGATGGGCGCTGGACCCCCAACCCGCATCTGAGACAACGATGATTACC
          ACGGGGGTGCTATGGGGAAAGCAGAGCCTTCATCGCGTATTGGGCTGATCGGCCCTTCCA
          TGTCGACGAACCAAAGCGCCTCTCCACCCCGCCCCCGTGTTGCGGCGCCCGATTTATAGG
          CAAAAGAGAGTATGTATGGCAGACCAATCTCTTAGCCGCCCGAAGTCCGAGGCACAGACG

          GTCAGGCACGGTACCTCCTAAACTGTTTGCTCTTATACCATCTCAGCTCCATCACAAGAT
          ACTGGGTGCGATATGTGATCGATTGCTTGCCTTCACTCCGTCCAAGTTCTCTCACCAGAC
          GCAGGGGCCGGTACCTGGTTGGCTGTACGTCTCAACATCGGCTAAGTCCCCCTGCCGTTT
          GATGAGATTTGTGCGCGACCCACACTCTGTCTCCTCAATGATTAAATTTAATTAATCAAT
          GCCACGGATGTTTACTGAAACGTTCTCGGGTCACGCCTCGAATGAGCTTCGTTGCTGAAC
          GTCGGAGAAATCGTATGCCAGGTAGCCCCTCTCTGCGTGAATTCAATGCCACCGATTTGA
          ATTGAGGTCACCAGTCTGCCAGTCCTCCGACTTGACATCGGACTACTACGGTAGAGGCAC
          CCCATAAAGATGGTTCTACAGGATACAAATGCTGGCCTCTGCGGGCCTTCATGGACGGGC

          CCCTACAAAAACGAATCGAGTGTCAAAGTTCGACATCTCTCGTTCTACGCTTATAATGTT
          CCTTAAAAAAAGAAATTGAGTGTCACAGTTTAACATCTCTCATCATACACTTCCAATCCT
          CCCAGAAAAAGCTAGTTTAACTCCAAACTAAGACTCTTATCAATCTATACCTCTGATTTT
          CCTCAAGACAAGAAAACCAGTGGCGAGGTTAAACCCCTTTTAGTCTGTACTCTCAATTCC
          CCGAAAAACGGCATATAGTGTCGTAGCAACTACGTTCTGTCGTCTTATGCAAAAAGCTTC
          GATGAAGAAACCAAGTAGTGACCCAGTAACCAATCATTAACATCGTACATTAATGATTTA
          ATTTCATGAGTCAAGTACCGCCGTGCACCACCTCACGTGTAACTTCAGGGTCGCGTTTCC
          CGATATATAATGGGCTAAGGCTTAGCCCCTGAACAACCGTGTGGGACGCCCTTAAATCGA

          TGAACTTGGGGTGAGCGCGCTTTGCGATGAGAGAATTGGTGGCCGCCAGGAGAATAGGGA
          TGCCTCTGAGGTGAGCGCGCCTCATGATACGAAAATCTTTGGCCGATGGGCGAGTAGGGC
          TCAACACGGCGTGAGCGCAATTATTGTTGATAGAAATTAGAACCGGCGGACCAATTGAGA
          TTGGCGCGGGGTGAACGCGCTTCAAGTTGGCAGAATCAGTCGCCGGCGAACCATAGAGAA
          TGTCACCATTTAGGGGGCACTCCGCCACAGGTGAACTTCAATTTGCAGGTCAAATCGACG
          TGAGCGTGGCATAAAAGCGGTTCGCATCGTGGGGCTTTAAAATTGGCGAGCCCATAAAAA
          GGGTTGTCGCTTAAACCTCGTCCGCGTTGAGGGAACCTGAAGCCGCCGGATCAAACCGAA
          CTAAAGTTGCCAGATGGGGCCGCGCGGCTCAGGGGTTTCGGGCAAGGTGAGATGTAAAAT

          TGGTCGAGAGTTCTACTTGAGCATCACACCGCTGTGGGAAACTCCGTGAGAGTTTTGAGC
          TCACCGAGTCACCCGTTTCAGATTCACTCCCGTGTGGGTATTCCAGAAAGAGCCCAGAGC
          GTGGCGTATGAACCCTCTTCGCGCCACGTCCATGTGGATAGCCATGGAAGAACCCCGAAT
          TTACCAACACAATTCGTTTTGGTCTTTACTGGCGCGTGCAGCCATGAATAAACCCTGGTT
          CCGGCGAAGGCGCCCGCCTGGTGTGAGGTTAGATGAGGTAATAAAGCAAGCATCCCAAAT
          ACCCTCAAGGTGCCCATATTGCCTCGTCAAGTTGCTAGCGGCTACACATGTATTGTGGAT
          GAGGGCGGGATACTTTATCGCTGTTACATCGTCCACGATATTCTTTCGAGAGATTCGATT
          CAGACTAAGAATATGTTCCAGAGGTTCAACTATGTTGCCGATTCTATATCCATTCTGAGT

          TAAGTTTTATCCCTGACTATGTTCATATCAATCTTTCGGCTAAGGACAATTGTATGTTCT
          TGACTCTTACCCTTCACTGTATCCACGTCGATCTTCAGATCAAGGACAACCGTCTGCTCT
          AAAGTTCTTTCCCCGAGGACATTAGAGTGACCACCTAGGGTCAGGATGAGTGTACGCCTA
          GATGCCCTATCTCCGAGTATACTAATGTGACCCACCGGTGCATGGTTCACCTTATATTTC
          AATGGCACAGCCACGATAACGGCACCACATACCGTTCGGACATAGAGGTTAAAAGCCCAT
          CAAGTTTTCCTACCGCGTTCAGTGATGTGCCTAGTCTGGTAAGAATAAGCAGCTTAATTT
          CTGCTACCAACATAGAATTCATCGTTCAACTCTACTAACGAACTGTGACAAGGGCATTCT
          TGTGTTGGATATACATGCTAGCAGATATTTCCCGGGTGGTCGTCAGGAGCGCCGCGCTAT

          GTCCCCACTATCTACCACTTGAATGCAACCTGATTTTCAACAGAAGCAGGAGAGATTGAG
          ATTCCCGACACCTACCTTCCGAATGTGAGTGAACTCACGGTAGACGCAGGGGGACTCGGG
          GTTTGCATCCTTTATTCGCCGAATGCAACTAGGTAAATCTTAGCAATATGATGGTCCCAT
          GCTCCAATATTTTCTCAACTGAATTCAACACGGTTCATGTTAGAAACAGTAGGCCCCCGG
          ACCTCTGTTCTACATCCTCAGAATTCGTCGGATTTGACATTGAGACAAGAGGGACTAAAG
          CTGATGGTTCCGCTGCGACAGTGTCCAGCAGGGTTAATACCAGACATGGTGGGTTTTGAG
          GGCTCGGTCCTGTCCTAGTTGAATCCGTTATCATAGAGGCGACGACAGACAGGAATTGAG
          GGCGATGTTCATTCGCCAGCGTCCCTGATGCGCCACGGGTAGAGCATTGGTAGGAGTGAG

          AAGCTAATCCAGTTAGATAGTTGAGCGGTTTCTCTAGCGAGATTCCTCCGAGCGCCTGAC
          TTGCCAATCCAGATAGATAGTTAAGAGGTCACTGTGGCGATATTCTTCCGATCCTCTCAT
          TTGTCGAATTAACTAGGTTCTAAAAAGATTCCTGTAGTCAACCACCTTGGACTGCTTTAT
          TCGCCTGGTCAGTTAGGTATTTAATAAATTCCCATGGTACATGCTTTTTCATCACTTTAT
          TCGTCATCGCGGTCATAAACAGTGAACGTTTATAAGTATGGCTTTATGCTAATGCATCAT
          TTATCAAGTCGGTTCGATATTCTATTTATAATTGCCCTGAGCATAACCCAGCCACTCCGC
          GGACCAATCCCATGGGCTCACCGATTCGCACTCTCGATGTGCATTATCGCACCGAGTTCA
          GTCACAAGTTACTCGTACAACTGTGGCGGTCAAGTAGCGACTTCCGACTGCCGTTCGAAA

          CGTAATGAACTAGCCTACCGATCTACGAGTCAGTGCGCGTCGCGGTACCAAAGTAATGCG
          CGTTGTGAGCTAGCATAACAACTTACGCGCATCTACTGGTAGCGGTATCATAATAACGCA
          TGATCTGAAGTAGCATAACGACTCGCGTGCGTGCCCGCCTAGAGGCACCATATGACATTA
          TGTTCCTCGGTAGCCTCTCGGATCACGCGGTAGTATGTCTGCTAGTACCTAAGCGCCCTC
          GAATTCGTAATTTTCTTACTACAAATGCGCGTGATTCCCTATCATCTTCAGAGCGCTACT
          TGCTAATTACGGGCAATACCCCCCTGGTACAACTTAGCCCAGCAGCACTCAACTACGACA
          TTTGACGCAGAGGCATCTTAATATTCGTGTCCTTCCTGCGTCCAGGAAGAATGCCTGGTA
          CGACACTAACTATTAGTACAATGAGTGCAGTAGAACCCCCGGAAGTTCGAATTTTGGCAA

          GCGAAGATACCAGGTCCACGCCCACTAAGAGTAAGCGGGAGGGTAGTATGCACCTAATGT
          GTGAAGGCGCTAACTTCGCGCCAACCAAGAGTGCACGCGAGGGTAAAGCGCCGCTATTGC
          ATGAAGGTGCCAGGTCTCCGATTCCCGGGTGCGTGCACGAGGACTGAATTCTTTTGCCAC
          GGGAAATTATTAAGTTTGTGCTCACGGAAAAATTACGTGTGGCTAGAGTGCACCTGACGC
          TTGCAAATGTTAGGTATGCCGCTGCCATGAGCATACCCGGAGGTGGACTGCGACGATAAA
          TTGGGGGCGTTAAGTCGAAAACTTTTCGGAGCGTACACGTAGGTATAGCTCACACGCAAC
          TTGAAGACAGTCCGTCTTTTACCTGTTCCGGGTCGCCTGCGTCTATAGCCCTCAAGCACA
          GACACGGCTGATGTGTTACCCTACGTGTTTGTAGTGGTAGGGATACGCCTCTTTCCAAGC

          GTCTTACTCTCCATCCAAAGTGATTCGATCTCGGTGAAGT
          GTCCTACTCGCCATCCATTGCGATTTGACCTTAGTAAAGT
          CTTCAGCTCGTCGTTCACGGTACTGCCTGTTTAAAATAAC
          GCACTGCGGGCGACCGCTGGCCAATGAAATCTAGTGCACC
          GCATTAGCTACCATAGAAGGCAATACAAGTACAGCGTTAT
          ATCATAATTGGTCTCCACCATAAAATAAGCTTCAAATGTT
          ACCTCAGTAGACCTACGCGGCAATAGGACCGCCCGGTTGC
          TTCGCTAGGATTTCAGCTGCCTGAGTTTATGCTGGATAAT

