 8 1000
t1        TGAACGACCAGATGATTCTGTCGGCTAATGTCATTAAAGATCCCCTTGCTTTCTGTCAGG
t2        TGAGCAGCTATTCGATGCCGTCGACCAGTGTTATAAAAGATCGTCTTCTCTCTCGTCAAG
t3        GGACTGATGTGCCAAATTACATGAATTATATTTTCGGGAGGCGCTTGTTCTCCGGTCAAA
t4        CGTCTTGCCTGCCAAATGCAGTGGACCGTTTAAGGAGCTTAGGTGAGCATCCGCCTGAAT
t5        GGCTCAAGCGACAGAGGGAGAGGCGCTACATCTTTAGGCAGGGTCAGTTCTCCTTCTAGG
t6        AATGATATCGGGGGACAGGGTTTTCTAGGATGGCATGACCGCCTCTGCCTTCTTACCTGT
t7        GGACCCCCGAGTGGAAGGGGTTAAGTGCCAGCAACGGTTCACGGTTTACCTTCTCTCCGG
t8        GGGTAGAACCTTGGAAAAGATTGATTAATATAACTTCCGGGACGCCGCTTCTTACGTCGC

          CCTCGTTCGAGAATCCGAACCTTGGGACGGCTATAACCAAGGGTTAGGAACCACCCGTGA
          GGCCGTTCGGCTAACCAGGCGATGGCTCGGTTACCGCTAAGGGTCAGTGCCCAGCTGTTA
          GTCACCTCGACTACTCTTAGTCTAGACCCATCGAAACTAACTGTAAGCTTTGATCCGTAA
          GCGCGCTCGCCTAATTCCTGGAATAAACATAAATGGGTAGCTGCGGGCGAGAATGAGAGA
          TCTCGGACACAATGTGCTGCGCGTTGTTTATAGTGAATTACCGGTGACGGGAGCTACCAG
          GCCTAACAGATTGGCCTGTCCTCAGCTTCACAGTATCCGTGCGTTCGAATGACTCGGTGC
          GCCACATCGACAATCTTCCGCACGGTTTTATCATGTATGGGCACAAGTGTGGGGTGTTCG
          AGCAAATCGGGAGATGTTGTTGGGGAAACACTTAGATGGGTTATTGGATACGCTTGCTTG

          GCCCCGCCCACTTTGATGTATATTATCGACGACGAGTCATACTTCTCCAGAATAGCCCTA
          GCTTTTACCGCTCTGATTCTTAGTGACGATGACGAACCAAGCCTCTCTGGAATTGCCCTA
          TTTAAGTCGATCTTGATTGAGAACATCGACGTGTGTCGAAGCATCTCCAGAATAACGCTA
          TCTACTTTAGAATCACTGCATGCTCGCGTCATGTAGACGAGGCTACTCAACAAAGCCCCT
          TTTGTCCTCCAGTCGAAAAGCCCCATCGGCTCGAAGGTACGCGAGTCTAAAGACGTCATT
          TCCCAACCAGTCTTAGCCTAGATCTCTGATGGGTATCACGATCCGTACGCCCGATTTCAT
          TACGGACCTTATTTGAGTTAAATGACCGTTGAGAGAGTATGCTTGATAAATACAGCCTTT
          GTCACTAAAACCTAGGTACCCATCTGCGTCGTTTAGACTTGGCTGCCCATTAATAGCGGT

          AGGGGGTGGTCGTCCGGATATCCAGGCATGTGCGCTAACCAACGGTGGCTTATGAGAGAA
          AGAATGTGGTCGCCCAACTATTCTAGCATACCCGGAGCCGAGAGTTAGGTGACATGACTT
          CGGTTGAGGAACCTGGAGTAAACCGATCTAGCAAGAGGACTGCGGTGAGCTTCAAATGAC
          GGGAGTCTAGAGCTTGGATCGATAAGTGAGGCAAGCGAAGGACGGCTAATTAGGAGATTT
          GAGGAGCGAGGCTTAGGAAACTTCGAAGAGATCAACGACGTGTGGCTGTGCCTCTCAGGC
          GGGGGGTATCTAACGGTACGGGACCGTCAGGTAGGTTGCCTGAGATCGACCATGACACAT
          TCGGAGTAGGTACAGTATGTGGACAAACGTTCAAGTCCCTGAATACTCTGCAAGTTGTTT
          TAGACCGAATTATTTGGCTGGCCTGGGTATTTCGTCTACCAATAGCCAGCTATATTGAAC

          ATCGGTCTGGGACTTTGTGTCCACGAGCCCAGTGAATGCCTGGAACCATTCCATGTCCGC
          GCCGGTTTGATTCCCATCGTCCATGAGCCCAACTATTGCCCGAGCCCATCTTGGGCTCAC
          TTCGATTTGCCGACGATACTTTACGCTTCCCGACGATGCCGGTGTGGATCCAGGAGTGTC
          ACCGACTTTATGCTTATTGTCTGGCGACCTGTTCGCCGTGCAGAGGGGTGTCCGGATACT
          CCAGGTTGGCATCCGATCGGAGACAGATGTCGTTACCGCCCGCACTGGACAGCAGGTGGG
          TATTGGTCGGTGAGCCCGAGCAACGGGCCTTGTCCTCACACAATGCAATCTCCAGTTAAG
          GATCGGCTGGTGACGAGTGACCGTCGAACCTTTTTTGGCTCGGGCACGCCCACGAATAAG
          GCTTGTACAATCTCACACAACTGCGAGTTCTAAGTCCGCCTGAGTTGAAGATTAGAAAAA

          CCCTGCATGATCTGTGACCAATCATAGCCCCAATTTCCTGGCTTCATAAAGTTCATAAAA
          CTTCATCCGACCCGCATGCCTTCAGAACTATAGTTTCTTGACAATACAGAGCTTACAGAC
          CTCCTTGGGAACCGCGACCAAATCGAGGCGTTATTCCCAGGCACTACAAGGGCCGTGGGA
          TTCCACGCGGCACATTACCTAACAATGCGTTGGTCATTAGGTACCCTCTAGTTCGTCTAA
          TTTTCTCCCGCCAAAACCCAGATACAAATATGACTGCTCGGGCCCATAGGGGGCGTTCGG
          CTGCCTGCCGCTCGGGGCGCCATTATAGGGTATTCACCTATTGCGCCGAGACGTCACCAA
          CCTCTTGAGGGGTGAGCTCTCACCAAGAACTTAACGTTCGGTGATTAAGCCCGGGCCTGA
          CCAACGATGGGTCGACCCCCCAACAGGGTAAACGCAACCGGCACCACGAAAGGCGGCCGA

          GGCATTCATTTCAGGGCAGGCTCTAGATTGAAATGCGTTGGAAGTGAGATTCCCGTGGAC
          AGCATGCATAACAGGGGAGACCCTCGTATGAGATACGTTGAGGCTAGAGAACCTATAGGC
          GGCAAACCCAACAGAGTGGGCTTCTGTTTCACACTCCAAGGATTCAGAAACTGTACATGA
          GTAAGGAACTACAACGAACCATTTCCTCCCCAGAACATCCGTCCGAGAAACCAGGTGTAC
          TTTGGCTGCAAGCCAGGGAACTCTCGCTTTGGGCACCCCGGACGCTGCAATTCCAAATAT
          GCTCCAAAAGGGTACGAAGCTCTTTATCTGATAAGCGTGATTTGTGATGGTCGGGGGTCC
          TTCTATAAATACCGCACACTCCTTTCGGTCAGCCGCTAAACATGCAACGATTGACAGTTC
          GCATAAAGTGATCGCGTAATAGTCAGCTTGAACTTACTTAGCCATTCGTAATGTTTATAT

          ACACTTAGCTTTTTTAAACAATCGAACTGTCGCAAATGAATAAGGTCCAGTAGTTTACGC
          TTATATAGCTGTTCAAAATTACCTAGCTGTCGCTCTTAAGGAAAGCCTAACCACCCCGCT
          GGGCGCATCTTATCTCAATCACCCATCTGTCGCAGGTAAGGGGGTCTCAGCGACACCCCG
          AGTACAGGCTTTTTCATGTTACACGAATACCGCACTTGGGGGGATTTGCGCCGTCCGTCA
          ATGCAAAGCGATTCAAAAACAACTAATCCGTGTCCCTGGGGCCGGTCAGAACGCTTACAG
          GGCATGGGGACACTTCGGGTCATAAGCGGTCCCCATTAGTCCCGGCAAGTACTCTTTTCA
          AGGGTAAAGACTGTCAGGCAGCGCGGAAGTAATTAGTTTACCCGCGTTGGCTTTAGTCGA
          CATCTTAGGACCTTCACACTAACAACTGACCATGTCCCGACACAACTCGGTAGTATACAC

          GTGCAGGTTCTTACACAATAAAACCAGCGCCTATCTAGACGGTCCTCTAAAACACGGTGC
          CCGTATGCTCTCTACAACCAGGACTCGCACTCGGCCGGGACCTCTCGCGAGACACGGTGC
          TTGTAGGTTCATCTCGTCAGCAACCGAAGAATACTCGGGCCATTCTGCGAGACACGGCGC
          CTGCTAATTCCCGCCGGGATGCAGTGTTCTCTCTACGCCGCATTTTTGTACGCATGCGGC
          CGACATTCTTATCCAGGCCAACGTCGGCAGCTAATTTCGTTCCCTCACCTTATTCGTTGA
          TATTGTACTACTTGTGCCCGAATCGTAGCTTTACGTATACCACTTCTTTAAGCTGGGAAT
          TCTCAAAAGGCATCTGGTAACTATTAACTTAGAGTCAAGGACCCTTCTTGGATGCGGGCT
          GGTCGTAATTGTCCCGGTAACGTCGAGGTACAACCCGTAGTTTTTCTCGGAGCGCTAAGA

          GTCATGTCCGGCGAACCCGTGTCCTGTCCCCACGTATGCTAACAGCCGCACTGTGAACGA
          GACGGGTCTGTCGAGCCCGCCCTCTGTTCCAAAGTATTCCGATCGCCACATTGAGAAAGA
          GGCGGGGTTGGTAGCTTTAGTCGCGGGTCTAGCGTACTTAATTTGCCTAACGGCGTAAGA
          GATCGGTCTGGCAAGTACGACCCAAGCCACGGCGCTCTTCATTAGTACAATGGTCGTGGG
          GAAGAGGATAAGACCTACGCATATAGTCTCGAGGCATCTTAGTAGTGATACAGCACAACA
          GCAAAGGTAGTTAATTATGTAACCCGTCCTAGTGCTCACAGATAGTGACGCGGACTTAAT
          AAGCTGAATGTGAGGTTTAGAACCGGGCCAACGACACTTCGATAGTACCACGGTCTGGAC
          TCGGAGAGTGCTAACGAGAGGGCAGTCGCTGATGATATCTCGCGGTCGGACAGATTCTCA

          GGAGGTGACTACACGCCTTGATCGGAGTGGCATGTTCGCATCCGTTGTCCCGAAGTAAGT
          GAAGATATTTATGAAACATTACCGGTGTTGAACACTTGTATCCGTTCCTTTAAAGTAATT
          GAAGACGTAGATACAATAGAAGCAGCGCGGCGAAATGACAGCAGTGTTTCGGATATAAGT
          GTAGAATTTATTCAGCGGTAGCTCGAGTAGTTTACTGGCGGTGGCCTCCTAGGGTCTTGT
          GAGAGTACATTTCTCTAGTACTTGATCAACACCGTTAAGGTACGTACTTTGGGATGCGGC
          CGCAATCTCTAACCGTTGCGCTCAGAGTGGGGCGCAATCAACAAAGGTTCGAAACACAGA
          GACGGTGTCCCCTCGGCAGCACCCGAGAACCCCTGATTCGGACTAAGTTAGAATGGTAGG
          GTATGTATTCCCCTTCCCTCACCATCCCAGCCATATGGCTCCCAAAGCTCGGCACAAAGA

          GCAGCGAACAAGTCCATAGCGCGATTTCATTCCGATACAGAGAGTAAGCCGCACGACCAC
          ACGTCGAGAAAGTCCGTCGTACGCCTACACTCTGACAACAAGAGTGAGTTGTATGAACAG
          AAAGTGGGGGAAACCGCACCCTGATGTTATGAAGAAACTAAGATGAATCCAAACGGGTTT
          ATAAGGGGGCGATCTGCCGAGCCCGCACGCCTCGGTATTCACACCAAGGAACTAGATTTT
          ACGCAGGCCGGAAAAGCCTGCCTTGTGGATGTGTAAGACAGTAGCAGGGTATTAACCTAA
          TTTGGAGAAAGATATGTTGGTCGGAGGCGCCTTAGCCGGCAAATTATGTCACACGAAAGA
          TTTCGATGGCGACATGAAAGGCAGTACCACTCCTAAGCCAAGAATCGACAATGTGATGCT
          CCTGAAGGGTGGATCATTTAGGAATCCTACCATCGTACCGAGATGAGATCGAGAAGGTGT

          CGTCGGATATTTAATGAAGACCGGTGAACAGTGCCGCGACCAACATTGCGGGCAATATTA
          CGTCGTACACTCAATGAAGGTCGGGAACAGGTGTTGCGGTGAGTACAACGGGCGATATCC
          CACCGGATATCCGGCGATGAACCGCATATGACTACGCGTCAAATACTATAGCCAGAATCT
          CGCGTTAACTTTGGCACTGGCACGAACACCGCATGGGGGACAACTTCGTAAGTAGTCTCG
          TCCCCGCTGCCGGATGTAAAATTGCGCCCAGTTTCGTGTCGTGAAGCATAGCATGTTTCA
          TGCTCACTTCGGAATGCCACCTGGAGCACGGGGCCTCGTGCTATGTTATAGTCGCGTCAT
          CGTCCGACCAAGGTTCCCAAGGAAAGGATGGTTTAGCAGACTAGCCTGTTCCATGATCTT
          AGCTCGGCGAAAGGCAATGTTAGTTGATTGCTTATACTTAAAGCTCAGACCTCAGGCTCC

          TGCAGGCAGCGTACCTTACTATCGGTCAGTCTTCGAAGCAAGGGTTCTTAAAGGCGGAAC
          TATGGAGGGAATGTTTCGTTGTTGGCGTCTTTTCGAGCTAAAGTTTTTTGGAGATAAAGC
          ACCAGGCAATGTACCTTTCAGCCGACGTTTGCATGGATTTAGTTTCAAACGCTACGCGTC
          GGTTAAGAGTGCAACGAGTGAACGGCATACGCCAACTTGCACGTTTTAGGCTGGAGAAAA
          CGCCAATGGCATAGAATTCGGATCGCCTATCGCTAATTTCCCGTCCCCCGGCGGGCGAAT
          TGGCGAAAACTTTGCATTGTTCTGCCCCGCTCTAGTCTTAAAGACCCGCAGCGACTTGTA
          CGTAGGCAGTAAATTGGAGGTCAGCTGTGTTCCCACAGTGGCGCTAGGAGTCGGACGAGT
          CCCGGTCCACATGACACACTATTATTGCATGCTGTAGTTGTAGCTTTACCATAGCCACTG

          TTACGACGGGACCCACATAGAGTGGGCGAGGACCCAAAGCCACCCCAAATGCAAGTGGAA
          AGATGAGGAAACCGACACTGGGTGAGTGAGGAGACTAGTCCACTGCGATTGTAAGCGGAA
          AGATATGGACGTATACACGGGATAAACGAAAGTCCTCGGGTTCCTCCTAAGCACGTGACC
          TGGTGAAAGCAAATATTTTAAACCGTTCGGATCCCTGTGCAACCCGCGACGCTTGCACAG
          TAGTCAAGGGAGGGCCATTACATAAGCGTGGCACTTGAAAAGCTGAACGCCCGCATAGAG
          CAATCACGGGGCGGGGACCGCGTTGGCGAACACTCCAAGGGACCAAGACCGCACATGGAG
          TGGTGGAGGGTTGAACAACCAGCCACTGCACCCCTCTGGTCAGTCTGTTGGTACTTGGTC
          CCTAGATAAGTAAGAAACCAGGTTTCCCAGTCAATCGCGTAGAATTGTCTACTGGCGTAT

          TCGCTACTACCTCGTGGTGCAGTTGCGTTCGGAGGACGAGTGGTTAACTGATACCGGGGA
          CCGTTGCCGCTCTGTAGTGCATAGGCGGCCGAAGGTCAGGTGGCTAATTGATATACGGGG
          GCGTTATAGTCTTTGGGCACAAACATTGTCGGTGGACTGACGTACGAGTGATACTGAAAC
          GTGACAGCGGTTCACCTAACGAAAGCAAACGAATGCTCGGTGCCGATCCGATGGAGGGGA
          CAGTTAACGTTCTATTACGTGAATGTGACTAGAGATGGCATATTAAGATCTTACAAGTGA
          TCTCTCCTGTCCCGTGGCGTAAGAGTAAGCGGGGGTAAGATCACGCAGTGCTGCACGGAT
          TCCTTAGGGTTCAGACCAGAGGCGACATTAAGGGTCAACTAGCGGAGATAGCGGCGCACA
          TCTGCAACTTTTTACGTTGCGCGATCTCAGGTGGACTAGTGGCAGAGACGATTTAGAAAA

          CTTCCGGATGGGACTTTACAGCTACGCTTAATATGCTCTG
          CTCCCTGGCGAGATTCTTTAGGAACGCTTCATATGCCATC
          GCTTCCGATAGCTTATTATTACGATGCTTTGTGTTCCCTG
          CAGTACCGCCAAACACAATTGCTGTACTTTGTGGTTTTAG
          GGCCCTCACAGCTTCTTTTAACGACGACTTGTACCCATTC
          TGTTTTACCACTACTTTTCGATATGGGACTGCAGCCTTTG
          TAAAACTTTTTTTCTTCTAAGCATGACACTAGGGTTTGCT
          TACATTCCTCTGTCTTGCGTGTGTCAATTTCTAGTTCATA

