 8 1000
t1        TGCAGTTGAAACTCACCGGTCTTCCGCCTTCGGAGGTCCGATAGTTGGAGCGCGAACGCT
t2        TACAGTCGAAACACTCCGGTCTTCGGCCTTCGGAGTTCCGATAGTTGGGGCGCAAAAGCT
t3        TACAGTCGAAATACTCCGGTTTTCCGCCTTCGGAAGTCCGATGGTTGGAGCACGAACGCT
t4        CGTCGTTGGAGTTCGCTGGACTCCTGACTCCACAGGCATGATAGTAAGAGATAGACTGGT
t5        CGCTGCTAAGATTATGCGGTTTTTTGAGTTCAGCGGCCCGTCAGATGAGGCTCCGGACCT
t6        TCCCTTGGAGATCTGCACGCGCCCAGACTCACGCTGCTAGTAAAAAAAAATGGTTACGAT
t7        TGCAGCGGGGTTGATCCGCGCCGTGACCGTAAGCAAATTTAGAACCCGTACATAAAACTA
t8        TGAGGTGGGCAGTGCATGTTCATCCTTTTCCTTCCGCCGTGATGTCTTTTTACAGGCAGG

          TATGAGAACCGTATGTCCCCACCATCTCCATGCCCCCTTAAACGTTCCGTGCAAAACTAG
          TTTGAGAATAGTATGTCCCCACCATCTCCATGCCCCCTAAAACGTTCCATGCAAAACTAG
          TATGACTATAGTATGTTTGCACCATTTCCATGCTCTCTTAAACGTTCCCCGCCGGGTCTG
          TACAAGTAAGATTTCTTTTCATCTTACTTGCCGATCCTTACGTGTTTCTTGCCGGGCTTT
          AATAAGCGCGAAAACCTTCCACATGCCTTGCGACTAAGCCCATGTCTCGGGGTGGGCCGG
          CGTAATTATTACAAACCCTCCCACTCCCCATGATCGCGCGTACTGTAACAGGTGAGACAA
          TTTTAGCACACTATTCGGCCACCTATCTCCGAGTCCTGCGCATGGCGGTGGTACAGCCTT
          CGCACTGGCGCTAAATATTTTTTGACGGCTTCCTTTACTTCACGAGATGATTGGAGTGTC

          ACCAAGCAGTAATAGGGGCGCTGTGACCGTAGGGTTCGGTGACTAGAAGGTGCGATCAAC
          ACTAAGCAGTATTAGGGGCGCTGTGACCGTAGGGTTCGGTGAATAGAAGGTGCGATCAAC
          ACCAAATAGGATTGGGGGCGCTGTAATCGTAGGGTTCGGTGGACAGAAGGCGCAATCAAC
          CCCACCCTGCACTGGAGGTAACTTGATTACAAGGTTCGGCGGTCTGCGGGTGTGAACACT
          TCCATCCAATTTAGGAGGATCCGTGGTCATATGGCCAGGTAGACAGGAGGTACGACTAAC
          CTCGTTCCGCGTGAGGTAAACCAAGGAATTAGCACTCGCTGGCTCATGGGTAAGAATAAA
          TACGTCCCACTCGGAGGGGACCACGGCATCGGGATTTACCGGGCGTTACGTGAGGCATTA
          CCCGCCACAAGCTGGTGCTCTAGAACTTGATGTGCGTCAGAGTTGATATGAGAGGTAGCC

          TGAGCCTTGACTACGGCGTGTACGTCAGGATGTTGGAGACGCCCATCTTACAAACTGTCA
          GGAGCCTTGACTACGGCGTGTACGTCAGGATGTAGAGATCGCCCACCTTACAAACTGTCA
          CGAGCCTCGATTTCAGCGTATACATCCGGATGTAACGGTCGCCCACCTTATAAACTATCA
          GAAATCTAGACTACAGCGTGCATGCACGCTTGTAAGAGCTACCTACCGCATAAATTCGCT
          AAATCCTCAGCGGCCACATACATGCACGGTTGTCTCAATAGCCTTCTGTGCCACCTCTCA
          TGTGTTTTAACTGAGACGAGCACAAACCCACATATATCTCAACCATCAAGTAAACATTGG
          ATATGATTGGCTATGTCGAGCCTCCTTCCAGGTCCCCAGTGCCCCCTAAACCAACACCGT
          GGAGATCGTGCGTGGGCGTGCACGGACTAGGCGGAACGCCCCCGTGCGAGTGTCCTTTGA

          GATTATGTACTTTTAGCCTGACCGATAGAATCTTAAGATAACGGACCATACTAGCCCTTC
          GGTTATGTACCTATAGCCTGATCGACAGAGTCTTAAGATAACGGACCATACTAGCCCTTC
          GATTGTGTACCTTCAGCATCACCGACAGACTTTGAAGGTCACGGACCATACTAGTCCTCC
          GGCTGAATACTTCCAAAATTTCGCATAGCATTTACGGATCTCGGGAAATACTAGTCCGAC
          GATAGCTCGATTACGTCTCATCGCGTCTGTTTTGGAGACCTAGGAACCTGATGCATTGAT
          AACCAGGACATCTTTACGTCTTTCGGAGAACACACTATTACCTGCTTCAACCCGCTAAAC
          AAATACCCTGTTACCCGCCATCTAGAGGTCCATACTGGTATTGGTCTCGACCCCGACAAC
          GATCTCGTTTAAGAGAGGCTTGCCATTAGCCTGGCTGACCTCGTTCCGCGATTTTGCGAT

          ATCTACTCTCTCACGCGACTGCGCTGCCAGTAAATGAAGAAAGCCTTGATTGTTAGCGTA
          ATCTACTCTCTCACACGACTGCGCTGCCAATAACTGAAGAAAGCCTTGGTTGTTAATGTA
          CTCTACCCTCTATCGCTACTGGGCTTCCTGTAACCGAAAAAAGCCTTGGTTGTTAGTGTG
          GATCAATCTACGTCGCTAGGACATTGTTTGTAATCGATAGCAGACCCGGCTATTAATAAA
          AGCACATCCTAGTTACTATTTAGTTGTTTACTAAGTAGGAACGGTTCCGATGTTGATAGT
          CTCTCCTGATACCTGCTGCAGAGCTAAATGTAGCAAAGTTAAGGTTTTAAAATTCATGAC
          GGTCTTTCTAACTAATCAGGAAGTTGAGGGCTCTGTGGGAATCCACTACTGTACAATGTC
          AACGTTGCGAAGATGGACAGAAATGGGATACACTGCAGGTCGCCCTCGCTTACAGTCACT

          TCGATCCGCGAATGATCACGTTGTCTAACAGGTTTACCCTTGATGGGAGGGATCGGTAAA
          CCGATCCGCGAATAATTATGTGGTCTAACAGATTTATCCTTGATGGGAGGGGTCGGTAAA
          TTGACCCGCGAATAATCATACGGCGTACCCGATTTATCCCTGACTCGAGGGGTCGGTAAA
          TGATCCGGAAAGTCTTTAAGTAAACCTATAGGTTTATCCGTTGTGTGGGGGCGTGGCATT
          TGAATAAGTATCTATTAATGTTGTTCACTAGATCACTTACTTCCACGAGGTGTTAGTTTG
          TTGACAGGTTTGGCACGGGCTGGATAGTCACATTAATCGCTCGTTGCGCGGGTGGGTTGG
          GGACATCGTGGGTAATGACACTGTTGATGACGTCCACTGCCCGGAAGGGGAGTCGCCCCG
          CGATACTGTGGAACACTCAATGCCGAACATATTGGTTTACTCCCAAAGGAGATTGGTCCG

          TCTGTATCAAAATAACTCCACCATTTTTCTCGGACCTTCCCTTCTGCAGATGCGGAGATT
          TCTGTATCAAAATAGCTCCACCGTCTTTCTCGGACCTCCCCTTTTGCATATGTGGAGATT
          CCCGTATTAAAATAGGTCCTTCATCTTTCTCGGACCTCGTTTTCTGAAGATATGAAGATT
          CCGGTGAGTCTGTAAGGCTATAATATCTTCTCGACCTAGACTTCTGAAATTATGAATGTT
          GCTGTGATTACGCAAGTTTCGTATATCTCAATGACCTAGATTTCAGACTACCGGTATATA
          CGTATGAACACGATACTAGCGCCCATACAAACATGACACCTCTCAGACTCTACGGTGTTT
          AGCATACTTGAGAAAATCTAACTGGTATTTACAACGCAGCCCAAGAATTATATGGGACCT
          GTGCTACCTATATGACTCTAAATGACCACTTATTTCCGATTGGCATACTTAAAGGGCCTT

          CTGAATATAACGGAGCGGCTTTACTCGATGCATCCTATAGAGGGTCACCAAAAAGGCCGC
          CTGAATATAACGGAGCGGGCTTACTCGATGCACCCTACAGAGGGTCACCAAAAAGGCCGC
          CGGAAGATAGTGGAGCGGCTTCACTAGGTGCCCCCGAGAGAGGGACACCAGCAAGGCTGC
          CTGTAATTGTCGAAGCGGCCTGCTTTGACATACTCTGAGGTTAATCGACAGCCAACCCGC
          TCGACAACGTGGATCTGTCTTACTCAACGGTGTCCTAAAACCTTACGTCAGTCAAATTTC
          CTTACGTTAGTGAAGATTACTTGTCGCCTAGATTTCGAAACTGAGATTATCAGAAGCCGC
          GTTAAATTAAAGAAGAAATCTGGCACTCAAGTTTCACCCCGTTCACCCCCAGGGCGCCGA
          CAGACCCTCGCTAATAACCAAAATCCTTTCTTTTATGCGGGGGGGAGCCACACAAGGTGC

          CAAGGGCTCAAGTCAGTTATTGTCGCCTACCAACATAGCGGTGAGTGGGGAAGCATCCAT
          CAAGCGCTCAAGCCAGTTATTGTCGCCTACCAATATAGCGGTGAGAGGGGAAGCATTCAT
          CAAGCGATCAAGTAAGCTATTATCGCCTATCAACATAGCGGAGACCGGGGACGCATCCAT
          CAAGAGCCCTTACAAGCTAGTCACGCCAATCAGCTTATGTGTGTGTGAGGATGCGTCTTC
          CGACCGGTTAGATGCATTATCGAGGTTTATCGACTCCTATGTAAGAGGCAATGCACCCAT
          TCAGTAACTTATTGAAACATAAGTATTATCTGAGATAGCTGATATAGGGTACCTGCCCAG
          AAGGAAACTCTACGAGGTATTAATGTCTGGTAATGAATAAGTGAGTTGGGGCATATATGA
          CTTATCACCACGGGGATTATTTCTGCCTCGCCCCAGAGCGAAGTGAGTGGACGCCAAAGG

          CACACGCCACCTATCGCGGCTTATAAGGTGTAAATTAGTACTAAGGGTCCGGAGAAATTC
          CATACGCCACCTATCGCGGCTTATAAGGCTTAAATTAGTAAAAAGGGTCCCGAGAAATTC
          CATACGTCACCTATTGCGGCTTATGAGGCCCAAATTTGTAATAAGGGTCCCGGGAAATTC
          CATATGTTAGCGACTGAGATTACTCCGGCTTAGATTCGTGATAAGGATCACGAGAACCTC
          CTCACGTCATTTGTCAGCAATAATAGGATCTTACCTAACGACACGGGGTCTGAGAAACTC
          CACGTATAGTGTGCTGGGCTGACCAAAGCCTCGACTATTTATTATAAGACGAAGAAAACT
          TACACATCTGCAGGTTGAATCGCGGGGGCCTTTATTGAAGCTGAAGGGTCGTTACATGAT
          TATCCGTCGGATAGCTTAGTCAGAGGGATTAAGTTCTGGCTGTGCGCGACCAGCACTAGA

          CATTGCCGATCGCATGAGCCTCATTCAAATCGTCAGACACTTTACCGATCACCGCAGGCG
          CATTGTCGATCGCCTGAGCCTCAATTAAATCGTCAGACACTTTACCGATCACCGCAGGCG
          CATTGCCGATCGCCTGTGTCTCACCTAAGTCCTCAGACACATTACCGATCGCCGCAGGCG
          CCCTTGTGATAGTCCTTGTCGTGTCTAGACTGTAATACTTCCTCTCGACCGTGCTGGGGA
          ATCTATTAATCGATCCGAACTGCTTTAAATCGATAGATAATTTCCGAAATGCGATAGGGA
          CTTGCCGGTGCCTACTAAACTTGCTGTGAATGTTACACGCTCCAACAGAGAGAGTATTCG
          CGCCTTTTTGGGTTTTGACCTTTGATAATAAAGAGCATAACAGTACGGCTAAGTCGTCTA
          ATACTCGAGTTGTGTAACTCCATTACTGGGTTCATTGTGTCTTTCCCATCGTCGCATCTA

          TCCTTACTCAACGTTGTCGAATGAGACTACTAGTGCGGAACCACTAACCAGCTCCTTTAG
          TCCTTACTCAACGCTGTCGAATGAGACTACTAGTGCGGAACCACTAACCAGGTCCTTTAG
          TCCTTACTCAACGCTGTAGAACGTAACTACTAATTTGGGACTACTAACCAACTCCTTTAG
          CCCTTACGTAACAATACTGAGCGGCATCACCAGTATTGAACCTTCAACCAGTTTATGATG
          CTCAAGTGCAATGACGCAAGACGGAGCCACCGAAGCAAAATCGCTAGGTGGTTTCTTCCA
          CTTTAATGTAACGACGTTGCGTAACAGCACCGTAGTAGGCCGACAAACAGGTCTTATATA
          TTCCTCTACAGATACACATGTCGGGTATCTTGTTGATGATTCTCGTACCGCAGTTCCTTT
          TCATTGTGATGGCACGTTAAGTGCTTAAACTCATGTGAAACTTTTGTATGCTCTGCCGCT

          AGCAGTGTACGTTTGACCCCACATAGTTCCCTAAGGAGCCCTGTTTCGTTCCGCTTCAAG
          AGTAGTGTGCGCAGGACTCCACATAGTTCCCGAAGGAGCACAGTTTCGTTCCGCTTCAAG
          GGTTGTGTGCGCTGGGTTCTACATATTTCCGTAAGGAGTTCAATCTCATACCGCTTCAAG
          AGTACTATCCGGTGGATTACACTTAGTTTCATAACCCGCTCAATAGTGTTTAGTCTCCCG
          AGTCCCATGCGCCGCCACATCATTAGCCCTATTGGTAAGTCATGATCGTTCAGTTCCTAT
          AGCCTCAGGCCCTAGTCTATTACACACTCTGACCTCTGCTCGTGCGTGGGTAACCGCTCG
          AAGGCTCTGTCGAATATCGCAGTGAATCTCGTGTGGTCTTTATCGAGGGCTCTACTAGCG
          TAGTCTAAACACTAGGGTTTACCCGCCTTGACGAGTTTTTTGATGGTGGTACTATACCAG

          TCTTTGTCATCGATTCGCGTCAGTCGCCCATATGTTAGCCTGCCCAGTACGGCAGTTCTT
          TCTTTGTCATCGATTCGCGTTAGCCGCCCATGTGTTGGCCTGCTCAGTACGGCAGTTCTT
          TCGTTGTTATCGATTCGCATCAGTCGCCTGTCTGTTGGCCTGCCGAATATGGGAGTTCCT
          CCGAAATGACGAGTCCGACCCAGCTGACCGTCTAATAGTTCACTTAATATGTGTGCCCCC
          CCCAAACGACCAAATCGATCCAGCCCAGCGTCCAGTGGAATACCATGTACAGTAGTCCTC
          TCTACAAGGAAACCTCGACCGAACCTTTCAGTTCGATACGTATCTTATATGAAGACCGCT
          TCTACATGTAATATGTATTAAGAACATCCGAGCCTTAGCTTTGCTCCAATGGAGATACTA
          GTTTATTGTGAAATCTGACCCAAGTGCCAGATCTACTAGCTCCTCCCCTTGAACGTCCGG

          GACCGTGCTCCTCCCTGTGTTTAGTTAATGCGAGGGGTCTTATTGCGTGAATAACATCTA
          GACCGTGCTTCTCCCTGTGCTTAATTGATGCGAGGGGTCTTGTTGAGTGAATACCGTCTA
          AACCGTGCTCACACATGTGTTTAATCGATGCGAGAGATCTTAATGAGTGAATTCCATCTG
          TACGGTGCCTCTAGCCGTAGTGTTCGGGTGTGAGGAATTTCGATAAATGAATCCAATCTG
          ACTCGTGGTGATGATCGTCCTCCGTAGGTTTGAAGGATTTATAGGGGCTATAACAATACG
          ATCTTTCACATCACAGGGAGCCCTTCAGCCGGTGGGTTACCCATAAATGAAGACCGTGTA
          TTCCCCCGAGACCTACGTGGCGCCATAAACGGTCGGGACACTTCGGAGGAGCCCGATGCA
          GCCTTTTAACATTCCGACAGTGTTGTCAAAGGCTGTGTATACTCAGAGTAAACATATGAG

          GATCCGGCCCGAAGTTCGGAGTAGAAGGAGCCGAGGCCAC
          GATCCGGCCCGAAGTTCGGAGTAGAAGGAACCGAGTCCAC
          GATCTGGCTCGAATTTCGGAATAGAAGGAGTCGAGACCAC
          GACCCGACTCGAGATTTGGAATGGACAGATATGAGTTAAC
          AGCAGGGTTGGAATCCTGTCCTAGGAGGAGGTGAACTCAT
          AATCTGCATTGTTGAGCAGAAATGAAGGGGGACAGTCCCC
          AGCACGGCTGGCTAGTCGTGAAAGGAGCAAACTAATCCGC
          TCGCCGATACGGTCGCCGAAGCAGTAGCACAAGTGTAGAT

