 8 1000
t1        TAGTGCACCTCACTAGACAACGCCCCTATGCTCGACGTTTCGAACAACATCCCTGCATGT
t2        TGGCGCATGCCGAAAATAAACCTTCTTTTGCTCGACGCAACGAACAACATCCCCACACAT
t3        TAGTTCTTGCCACCCGAGTAAGTTCCGACGCCCGGTATAACGGCCAACACCTCTGTCTAT
t4        TAGTGCAAGCCGACCGAGAACGTTTCTTCGCCTGGTGCACCGAAAAACAACGTGAACTGC
t5        CCAGAAGGGCACCTTAACGGCCATACTGGACTTGACGGTTTCTCTCACCATCTGGCACCA
t6        CAAGGAGGATACCTTCACGTAGCTTCTGGGCTTGGAAGCGCTCCCCATGTTCTAGCAATC
t7        TGAGACGGATTTCTCCACGACGCACATGGGTCGTACAGCCATCCCGCCATTCAAGGGCCA
t8        TAAGACGGGTCATTCCACGACGCACATGGGACGAACAGCCCTCCCACCATTCAAGCGTCA

          TACCCATCAAAGGTATGGTGCAACGTTAAACTACCCACCCTATCCTATTCTTTTCATTCG
          TATCTACGAAAGGTATAGTACAACATTACAATACCCTCCCAATCCTATGCCTTCTAGTTT
          CGCCTAACGGAGATGTTGCGATACGCTACAATACCCTATCTTTCCTTTTCCACCAACACT
          CGCCTATCCTAGGTGCTGAGCAACTTTAAAGCACCCCACAAAGCCTAGTCCTCCTACACT
          CACATGTTAACACTTCGCCATGAGAGGATACCCTTGCGCCCCAATACTTGATAGAGTGTT
          CGCTCATTAAGATTTGACTATGGTGCGGTACTTTAGTGCTCTAAATCTTCTCTTTATACC
          CGCCTGTACGGACGTGGCAGCATCGTGGTTGTTATCTGTTATAACGAACGCAGGTTAGTT
          TGCCTGTATGGACGTGGCCGCATCGTGGTTGTTTCCCGTTATAACGCACGCTGGTTAGTT

          AATGCGACTCCTGCCCCCGAGCAGGTGTGCTTGCTTGTGCTGTACCTCACCGCATGATGA
          TACGCGAACCCAGCCTCTGAACAGACATATTTGCTTATGTTGTACTTAACCGCATGAAGA
          AGAACGAATTTCACCTGTTATCAAACAATTTTGCTAGTACTGGATCTCTCTGTTTAAAAG
          AAAACGACTCCTACCTCTTGACAGGTAAGTTCATTTTCGATGTACTCCTTCGAATAATCA
          GCGTCGGAGGTGCTTATCATCGGGGTGATAACTCTTATCACGGCTATAAATGCCTATCGA
          GTGACTAAGGTGCTCAACAATGGCGTAAAGTTCTTTATCACGGCCGTTAAAGTTCATACG
          GAGATGAGAGTTCCTATGAGATGGATAGTGACTTTTGCCATGTCTAACCGCGAGAACCAG
          GAGATGAGAGTACTTATAAGATGGATAGTGACTTTTGCCATGTCCAACCGCGCGAACTAG

          GTCATCAAATTTTTCATTCGGATAGAACGGGTGGCGTCTTATGTATCGGTAGATTGGTGA
          GCCGTTGTATTTTCTATTTAAAAAGAACGAGTGGCGTCTTATGAATCGATAGGTTGGTGA
          GCAGCTGAGTTTCTCACTTAAAAAAAATGCATGATTTCCCCTGTTCTGATAGGGCAGTAA
          GTTGACGTAATGCTCCTCGGTGAAGATCGGGTGGTTTCCCTTATAGTGACAAACGAGTGA
          ACTATTGCTTCCTACGATTAAAGGAGCCTGGTGAGTCACTCCGTGGCAATAGAGGGGAGA
          AACACCGCCTTCTATGTTCGCGCATGCCGGGTTCGTCGTTCTATCGGACTAAAGAGGAGG
          TTCGTGGGGCCCGCTGACCTAACAAAATTGTTAGGTCGTCTTCGAGCTGTAGGAGGGGGA
          TTCGCGGGGCCCGCTGACCTAACGAACTTGTTAGGTTGTCTTAGAGCTGTAGGAGAGGGA

          GTGGCATCTTACTTAAGGAGCACGGATTCACCGACATAGCGGCCAGCAAGCGCTGGGTGT
          GTAGCAGCTCACTTAGGATGCACGACTGCAGGCACATAGAGGATAGTGAGAACACGGTGT
          GCGGTACCTCACCTGTGGTGCACGTCTCTAAGGAGGGAACGGACAACATAAGCTAAGTGT
          GTGGTACATCATCTAAGGCGCACGGGGTAGAGGTCAGAACGGATAGTATGAGCAAGGCGT
          ATGCGACTTCATTCAATCTAGGTAGCACCGAGAAGCGATGGGCATGCACCCCAGAAGAAG
          ACGTCGCATCGTTTGATCTGGGTAAAACCAAGGAATTAAGGACACATGCTCAGAAAGTAG
          CTGTAACGTAATTCAACGCAAGTTACACAAAAGATTCGAGGGCATAGACTCAAGATAGCA
          CTGTAACGTAATTCAACGCAAGTTACACAATAGACGAGAGGCAATAGACTCAATATAGCA

          CTCCGGAGGGAGCGCCATGCCGACCCCATTCCTACGATTCGTCGAAGGAGTCTTTATAAT
          CTCCGAAGGGAGCATCATGCCGACCCCATGCCTTCCACTCGTCGAAAGAGCTTTCAGAAC
          CTTTGAGGGGAGTGCTATTCCGACCACACGCCCACGGCTCGACGGAAGAGCTTATGTAAC
          CTTCGATAGGGGTATCATTTCGATCCCACGTTAACGAGTCGCAACAACAGACTATGCAGC
          CCTAGTAGGGAAGATCATTGCGACATTTTGCCGGAGAGTAGATCTGCCGCAATGCGCCAT
          TCCAGTGAGAAACATCATTCCGATACTCTACCCTACAGTCGACTCGTCTCAGTGTGCCCT
          ACTTTTGTGGACTTCTACACCGTTGCGTTGCTAATCTGTCGAACATCTTCTTTGCGATGT
          ACTTTTGGGGACTACTACATCGTTGCGTTTCTAATCTGTCGAGCATCTTCTTTGCGATGT

          ATTGCTCGCCCAGCGCGCTGGGATCGTGAAAGGTAATAGCAATTGGCCGTAAGTCTGCAT
          ACTGTTCAACCAGCGCATTGGGATCGCAAAAGGTATCAGAAGCTGGCCGTAGGCCTGAAC
          ATTGCTCGACCAGAGCAAAGGGATCGCGAAAAGTGGTAACCGTTGATCCGAGCCAAGGAA
          ATATCTTGACTAGCGCAAAGGGGTTATAAAGAGTGGTGACATATGGCCGTAAATAAGGAC
          CCCTAATGCGTCAGAGCCGTCGACCGCTCGCTATATGTTTAATATCTTATCGGGAACTGC
          CATCATTGTATTGGCGTCGCGGACCGTTTGCCCTATATTTAATTTTTCTTAGACTATTGT
          CCCGGTTGGGACCCAATTGCCAGCTGCTCCCCATGAGGCTGCTGACTTGTCATCCCAGCT
          CCCGGTCGAGACCCACTTGCCAGCCGCTCGCCATGAGGCTGCTGACTTGTCATCCCAGGT

          GGTGCAGGGGCTGTCGTTCCTGGACAGGTTGTTGCCCGCTTAATAACGTCGACCGTTACC
          TGCGAAGGAGATGTCGTTCCCACGTATGTGATTGCCCGCCTTATAGCATCGACCCCTACA
          GTTGAAATGGTCACTGGCCCTGAGCGGGTCTTTGCCCGGTTCCCGTCGTCAGCCGTTACG
          GGCTGAAGGGGTATGCGCCCTGGGCATGTCTCTGCCCGCCCCCCAGCCTCGACCACTTTC
          AGCACTGTTTACGCAACCGGGGAGCAGTTAATTGATTATATAATTACCGAGATTCACTTT
          AGCAATGTTTGCGTTATATGGGAGTGGCCGATTGACTAATATATTGCCGTGTCCTTTCTT
          ACTGAAGTCGCCGTTGTCAGAGGATACACCGTCACTTTGACGATCGACGCAACTTTCGTT
          ACTGGAGACGCCGTTGGCAGAGGATAAACCGTCGCTTCGACGAACGACGCACCTTTTATT

          CTATGGAGAAAAAACTTAAATAGTGTCCCTATCTGGACCCACTACTCCAATGTGCATTTT
          CTATGGTTAGATAACTTATAAAGAGTTTCTATCTGGACCCACTATTCCAATGTTCACTTT
          GCTCAGCCCGATCAACCACACATCGCATCTATCGATATCTTCTATTCTAACGATTCACTC
          CCACGATGTGACAACCCAGCAGGAGAATTCATTTAGATCCACTTTTTTGATGTCTGTTTC
          TACGGATAAGACGAATAGGACAGGGCTCGATCCCAACACCAGAATTGCGACCATCGGACC
          TACAGACTTGACCAGCAAGACAGAACTCAACCTTAACGCCGAAATAGCGACCGGCGAACT
          CACATGGTTAACCAGCACGAAAAAGTTTCATCCTCATTTTGCACTTTCGAGCAATGCACA
          CACATGGTTAACCAGCACGAAAAAGTTTCATCCTCATTTTGCACCATCGAGAAATGCATA

          ACCGATTGCATGCAAATAAGTTACCCAGACAGTCGAATCAGGTCACAAAAAGTTTGGAAT
          CCTCCCCGCAAGCAGAAAAGTTACCTAGGTAGCCGATTTAGGTCAGAATATGTTATGTAT
          ACTGTTCAGGGGCAACAAAGACACTCAGGTAACGAATTTGGAGGGCGCAGCGTTTTCTAT
          ATTGTTTACGTGCGGTGACGTCACTTAGGGTGTTATTTTTGGGTACAAACCATTTGGGAT
          ACGGATTATACTGGCCAGATTAATAAGGGACTAGTTACAATGCGGCACCTTATTCGCATG
          ACGGTCTATAGTGGACAGATTAACCAGGGTCCATAAAAGGTGCGGCATTCGCCTCGAGAA
          ATGAACCACATGGAGCAAGGAAAGATTGGCCTATTCTACCTATATCACCCAGTTACCAAG
          AAGAACCACATGGAGCAAGGAAAGATAGGCCTATTCAACCTATATAACCCAGTTACCAAG

          GGAACGGGTTAATAGAATGATTTTACAGAGCGCGCGGCCATTACCAACAGCACAACTTCC
          GCAACAGGTTTATGAAATGATCACATCTAGCGCGCAGCCATCGCCAAAGGCGCACCTTCT
          CAAGCTAATTAACGAAACGAATATACTGAGAGGGTAGTCATTACCGGAATCGCCGCCTCT
          GAAGACAGTTGGTGAAACAACTAGATCGAGCGCCTCGTCGTTGTCAAGGTCGCTCATTTT
          ATCACACCATCGTATTGAGATCGAACTCTCTGTACGGCATTTAGCGTTATCGCGATGCCC
          ATGCTCGAACTGAATTAAGGGCGAACAACACACGTGGCATCTAGTGCTACGGCATTACAC
          TCGGCCGTTCCGAGCAGCCTGCGCTCTCATTACACGGCTTCTATTATTGCTACACAGTAC
          TCAGCCGTTCCGAGCTGCTTGCGCTCTCATTACACGGCTTCTATTATTGCTACATAGTAC

          GCAAGATTCCGATTTGCAAACGGTATATTATCGTAAGCATATCGCTGAGTACTGTACGCT
          GTAAGATCCCTATTTATAAACGGTATATCAATATAAGCAAATTGATGAGTCCTGTAAGCC
          GTAAAGTCCGAGTTTATAAAAGGTATGTTCCTATGGGCCCATTGATGAGTACCCTACGCA
          ATAAGATCTGAGTTTTTAAATGACATGTCAACATAAGCCCACTAATGAGTTCTCTATGCC
          ACAATTACCTATTTCTCCCCACGATCGGTGGGTAGGACCACCTCGTGCGGAACCTTTGGT
          CTAATCTCCTGACTTCCCTTAGGGTCGACCCCTAGTGCTGCCTGGTATATATTCAAAGGT
          GTAACCTCTTACCTTTCCGTTGGGTCGAACGCTGGATAGACTCGCTAAACCCCCGAGAGT
          GTAACCTCTTACCTTTCCGTTGGGTCCAAAGCTGGATAGACTCCCTAAACCCCTAAGAGT

          TGGAAGCATAAATGCTCTGGTACAGTTCTCCCGTCTTAAGTATCTCCTACTCAAGAGGGT
          TAAAACCTCAGATGCGTTGGAAAAAATCTACCTTATTACACTGCCTCTACCCAAGTGGGT
          TGGATCCCCAGATTGTTTACTGAATATTTATCTTCCGTTGTACTCTCGCCCCAAGTGGAT
          TGCAATCACGGATGGCTTGCGAGAGGTTTATTTTTCGCAATGGTTTTCGATCGGGCGAAG
          GGCTGGCTCTTTCCAATTTGGGAAGTCGAATTCGTTGTCGCCACCGTACCTTTGAAGGGT
          CGCCGATGGCCTGAAATTAGTTGGGCTAAACCCGTTGGGCCCTTTGAACCATTGATCGGT
          CTGCAACTTTGTGAACATAAGGGGGTTGATAACGCCGCCCTCATCGTAGCTTAGGGAAAT
          TCGAAACTTCGTGAACCTAAGGGGGCTAATAACGCCGCCCTCACCGTAGCTTAGGGAAAT

          ACCCAGCCGTTCGCCGTCGATTTGCGGGAGTCGTGAACTACGGTATGAGTATCGGATGAC
          TTCATACCGGTTGCCATTGCTTTGCGGGTCTTGGGCACTATGGTACGATAGTACGTTGAC
          GTCTGGGCCTTTGACTTCGGTTCGCAGTTCTCAGACACTATATTAAGGTTTCTCGTAATA
          AACAGAACGTCCGCCTTCACACTGCGATACACGGACATTGCTGTAAGGTTTCCGTCTGGT
          GGTTTTTTCAACGCAATTCTCTCGGGGTGCAAACAGTTGTTTGACGTGATCATGGTCCGG
          GGACCTATTAACGCGTTGCTCTCAAGCTATTAGCAGATGTCCGATGTGCTCATTGTCCTG
          GGTTCTCCTAGTATAATATCACCAAAATACATGCACAGGGTCGAGAACCTCGCGGGTTAT
          GGTTCCCCTAGTATAATACCACCAAAATACATGTACAGGGTCGAGAACCCGGCGGGTTAT

          TGAGAGCATTCGCCGTGCGCTTGCAGATTAAGGGATGCTTCTTACACAGTCCCGTCCTGT
          CGAGAGCATTTGCCGCGCGACAACAGATCAAGTGATGCTTCTAAGAGAGCCACGACCTGT
          TCGACATATCAGCGGTGCGATATCAGACCAGGTAACGGTATTTTTACAAATCAGGCTTGC
          TGGGAGCATTTACCGTGCGAGAACAGACCAGGTAATGGCTTATTCAGGACCTTACCCCGC
          GTTTACAGCATCCATGAGAGTCAACTTTTTCCGAGCTGTTTATACTGGGAAAATGAGCTA
          GCCTATTTTCGGCTTGGGACCCTCCTGTATGACGCTTGTTCATTCTGGTTAGTTTAGCTA
          TCAGTTCTTGTCAAACAAGACATCATTTAGGTCTGTCGCTGGCACTAGACAACCCAACTA
          TCAGTTCTCGTCAAACATGACTTCATTTAGGTCTGTCGTTGGCACTGGACAACCCAACTA

          TCCGTGCGGGGCATGCGAGCCGGAGACATCTCACGACACGTGAATTATCATCCAACAGAG
          TCCGTAATGAGCATGCGAGCTGATGACATCTCGTGTCACGCGTATCACCGTCCGTCGGAG
          TTTGCGCTGGGCACTCGAGTTGGTCAAATCTTATGCCACGACATTTCCCGTTGGTCAGTA
          TCCGTGCTAAGTGTCCGAGCTGGTATCATTACATATCACTTGAATTACCACCTGTCAGTC
          CCAAAGTTGAGTGCCGTGGAGGTTTCCTGCACATGTCGAGCCTCCCACCAAAAGTCTATG
          TCAGTGTTGAGTACTCCGGAGGTCCCCTTGACACGTAGAGTCATTCACCACGAGCATGCT
          GTGGCGCAGAGTACCTTAAAATATCTCTCCATGAGCTGCTCCTCCTATCAAAGGTCAATC
          GTGGCGCAGAGTACCTTAAAACATCTCTCTATGAGCAGCACCTCCTATCAAAGGTCCGTC

          GACTTCCGTCCTCCAACAGACCCCCGTCATCGGAATCAAT
          TACTTGCGTTCCCCAATCGATCTCTGTCATCGGATTAACT
          GACTCCCTTAGTTAAATAGAGTCTACCGCCCATGACAGAT
          GACATCCGTCGCCCTGTTGTATTCAGTCTTCGGTGTGAAG
          GTTTCCGCGCCTCACGTCACCTTAGCAATTTAACACGGAG
          GTTCTCATGCCGCATGTCGCACTAGACCTCTAATACGGGG
          GGTAGCCGGTCTGATGCCGTCTCAAGACTTCCGCTTTGAC
          GGTAGCCGGTGTGATGCCGTCTCAAGACTTCCGCTTTGAC

