 8 1000
t1        CCCTAGCAAGTTGCTTCTCGGCGCATGGACCTCCCAGGCTGACGGGAAGGCGGGTGCTCA
t2        GTCTAGGGAACAGGAATTAGCTCGGAACACTTTTTATGTAGCATATATCACAGGTAAAAC
t3        TACATACGCACTGGGACGTAGCCTCCGTTTCCGCACACCCTACCGGCCCATGGTTGGTAC
t4        CGCAAATGCCTTAGGCTCTAGCGCCCTTTCCCCCACAACCTAGTGGCGCATAATCATTAC
t5        TCATATCAATTCATAATCCAACGCGGGTACGCCCCCAGGAGGTCAGGCTGTGAAGAGTCA
t6        TTCCACCGCGCAAGAACTCGCTGTGCTTCTTCTTGCGCGAGGATTGGAAGTGGATGCCAA
t7        CTTCAACGCGCTGGTGATTGTGTACGCCGCCTTCCGAGAAAAAGTGGCGGTGAACGGGGA
t8        TATTAAAAAACTGACCTCACAGTAGGGTTAAAGTACAGGCGTCTAGAGGACAGACAAAAT

          CAAAAATCGGGCCCAGGAGTCAACTTGAAACTTTGCGCCAAAGATAGTTTTTGAAAACCG
          TATCCTCCACGACTCCGACTTTTGCTGTAGATCAACGGCACGCTTAGGGGTTCAGCTGTA
          CGGAGCGAGCACCCGGGAGTCGTTCTCAGATTATGAAGAGATTTCCGGAAATCAGATGTA
          GGAGGCATACATCCAAGAATCACAGAGAGGTATCGATAAGTCTCCAGGAATTCAGTTGTG
          ACGAGTGCGTGCGCATGTCCAAATCGTCAAAGTTCTAATGTAGTAGGTAGCTTAAGAGCA
          CGGAGGGCATCCATGCGCCTGTTTTAATAGTGTCCGAGTATGCTAGGATATCGGGGCCTG
          CGAATGTGGAGTGCACGTGTTTACCAAAGGCTCATCCCCCTTCCGGCGAGAGCGGGGTTT
          CGATGCGCACGTTCTAATCTTTGCCACCGCTAGATAACTCACTTCGATTCCCTGGAGGTT

          GGGATATACATACATTGTTACGATCTCAGTAATCGAGCGCTACCGTACCATTAGCAGACT
          GGGATAGTTCACAATAGGTATTTATTTAGGAGTCGATCGACGCTACTCTAAAAGTCAACT
          CGCGCCTGAGGTCTCGGCGGTGGCTTTTTAGATGCGTTAAAGCTGCAACGCCAGCCGATC
          AGTAGCTGTAGCGCCAGCGGGAGCCTTCTGATAGGCCTGACTCTGCCAGGAAAGCTGTTC
          GATGCATCCGGAAAGAATTCCAGTCTGAGGTGGTCCGCGAATTTGTCACACAAGGAACCC
          TGTCCTACTATCCGCAACTTTAAGCCCAGCTGACGAATCGACGGCCTATCCTGTGTAATC
          AAGTCGTACATTAACCTCGATAAGTATCCGAAAAATGTCTTCCCATCCAACTAAGATGAA
          CGTTGGTGGGAACTCCCGTGCGAAATACAGTTGTGGATGGTCTTCCTGCGATTAAGAATT

          ATACATTCAAGGATATGTCGCTGGTTTACCGAGGGCGTATTGACAGTTCGAGTTAGGCGT
          GATCCGCATGAGAAAAGTCGCGAACCATCCTTAGAACCAGTAGCAGTAAATCCACCACGT
          ACCCATTTCGGGACTTCCCGACGATAATTCCTCAAATCAGCAGTTTCCCGCATAGCTGGT
          GCCCAACTTAAGACGCTCCGTCTAACAGCACTAGAGTCTGAAGTCATTTGTCAACCAGGC
          CTTTTCCGCGGACCACTCGTCACATTATCTTAACGAATGACAGCCGTGACGAGTTCCGTG
          ACCACCCGTTGATAACATCGATCGTCCGCCAGTAGGACAGCGGGCGTGCACGTGAAAGCA
          CCCCTTTTTGGGTGGTCGTTCGGGTCGTCCTTTGAGTCGGTGGCAGTATAAATGGTTACG
          ATGCCGCCCAAAGTATTTTCTGAGTTGACCCTAAAGACTAAGCTCGTGTTCTTTATGGAG

          CATGCTCAACTGGAATACTAGCCGCGGTTGCCTGATTGCTGCCTAAGGCGACGGGTCATC
          GGAGCGACAGTATGGCAATGTTCTAGATTATGTCTCGGCTACGGTATACCATGGGTAACC
          ACTCTCCGGCCGGCGGATCTTGCCCTCATCTGTGTCTGTTCCCGTATCGCCTTCGCCATG
          ACTGTCCACTCGACAGGTTTCGACCTGCTTTGCATCAGCTGACTTATGTCCCCGGCCATG
          ATGAACTTATTGAACCATCTCCGTCTCCACGGTAGTAATCACATCCGGTCTTAGGTCGTT
          GCAGCCTCATTTCATCGTTACACTAGACCTTGTATGCGCCATCTTAAGGTATAGGTATAC
          CCAGCCTTCTCATGCAAACAACACTGATATTGTGCTGGTTATGATAAGTCGTCATATAGG
          AGACTACTAGCGTCACGTTAGGATCGAAGTTGCAACAGGACCTATACGCTCTAGATCGCA

          AGGACAGCTACGTCGCTGATTTTCGGACCGGGGGGAGACGACTCACCCAAATCGCCTTCA
          CGTAGCAGCATGTACTTTACCTTTGGAACGAGGACGCAATAACTTTTTGCACATTGCTTA
          CATACGAAGTCTTTGGTTATACCGGGTTCTGGATGTGTCAATATGAAAGGAGTCTGTGTG
          CGTACGAGGTATCCAACTTTAGCGGGTCCTGGAACCATCAATCTAATTGCAATCTGTGCG
          TTACAGTGTAGATAACTTATTCCCCGGACTCCACGTGATAAAGCATGCGATCGGAACTTG
          AAGCCGCGCATGCGAGCTTTGTCCCGAACCAGCTGATCCGGTCTCCGACCCTCGCGTCTG
          TGTTTACGCTCCTCTGAAGCCTTCCGATTCGTTAAACGTGACAAAGAAGGAGTGTACCTG
          CCACTGTATTCAACGTATGTTCCCCAGGCTGGACGATGCGATTAACATACCTCGTGTTTA

          CTTGATTATTCCGGGGCAATATGGCCGGGAATATGCGGCAGAGCGATAAACCTACCTAAT
          ACTAAAAAGGTCAAGCCGATATCCCCGCAATGCGTAAGCAGCTGTGGATTGTACTATCGT
          ACACAAGAAATGGAGCGTCGCCCCCAAGAGTGTCCTTAGGGGGCGGACTGATTTTTACGA
          GGATAAGCAACAGGACAGTGCCGTCCCGACTGTCTCTCGGGGGTGGATTGGGAGTCCAGA
          CTGACTAGTGTCTGCCTGCCTCAATGACACTCGTTATGCACTATAGGATGTGACAAGTTT
          CTAAATAATGCACGCCGGTCTCGGTCCTGTAACTGAAGAACCGTGGTGTGAGCCCCACAA
          GTCCAGGGAGTCTGCTATACACGAGAATGCGACGTACCACGTATTCGACATGTCTCTCAG
          CTTCCCTGGGCCATTGATCCTAGATCGTAGAGCATGAAAAGAACGGTGACAGGTCCACGA

          CCGACCCTGGTCTGATGTTTAAATCCAGAAGTTCATTTGTCACTTCCTTGGGCTCAGTAG
          GTGAACACGTTTTCATTTCCCAGACCGTGCGCCCTTCACTGAATTCCCAGTAATTAGTGG
          GCCTTAAAATGACTACCTTCCTGTCTATGGGCCGCCAACATTAGGGTCCTCGATCATGTG
          ATTTTAGAGTGCTTACTATCCTGTCTACAGATCGCCATCAGTGAGGCCTCTGGTGAAAAG
          CGGTGAATGATATTATTAACCCGTAGTAAGGTCGATGAATAACCGACCCAACATTGTGCG
          GGACGAGTGTCCTCATTCTCCCGGGTTCTAACTGTCGGGCGAGACTTTTGCGATAAGGCA
          CCACAGGTTATTCTCGATGACAATGTGTTAAACTTCGGATGTGCGAGCCGCAATTAAATG
          CATTTATGGTGCCGTCTAATGAGTCTAATTGTTAAAATGCTCCCCCGTCACTCGCTGTCG

          TAGGACGCGCTAAGCGTTTACGTGCCGTATTGTTTGAACTCTCGAAACTACTAGGAACTC
          GTAGTCGGACCTAGTCTAAGACTGTGTGATAGATCGTGACTATATAAGTGTTCAGCGCCA
          TACCGGACACAATGCCTCGACACTAATGACAGACAGCCTCCATGTAACTTTTTGCCGTAA
          TGTGCGGCGTAAGGCCCTAATTCTATTGCTTGATAGAGCCAAAGCAATTGTTTGCCACTA
          CATTACGCAATCAGTAACCAGGTTTTTCATTAAAATTGGAAAAGCAACGGAACGTGGGTA
          TGTCATATAACGAGCTCGCACGGCCATACCTGGCCGTAGTTATACGTCCATCCAGAGAAC
          TTCCCAGAAGCCCGTTCGACTGGTATTGCTCGGGAGCGATACACTGCCCTTCTATAGACA
          AGTATCTTACACAGGCGTGACAGCACCGCGAGGGCTGAGCAGGCTATCTGCCTCGAACCG

          ATTGGGTTTATATTGCGCGCAGTTCTAGCTCCTTTCGGACGTTCTTACAGTCACGAGGAG
          ATTTGTATCGCGACTAGTCATACACTGACCTTTTTTGGACTACTTGCTCCTCCTTAACCG
          CCCAGTCCGAGCTTCACTTAAAGCTGGGGGAGTAAGACATTCGTCATGGGCAAAGAAACG
          CCCAATTCGTACTTTGGTCGAGTACGGGGGTGCGGAACGCTCGTCAAACGGAACGATTTG
          CCTAATATGGATGCGCAGAAGGCGCGCCAATGCTCCATGTCTTTGTCACGTAAAATGGCA
          CCGAAAGCCGGACTCAGAGGCGTTGAGTGTTCCTCTGTGTGCGTAAAATATCGGCGGGTA
          CCCATCATCGGGTTTAGCGACGACTGAAGAGCACCACCGACCGCACCCAATCTATGTATG
          GCGAATTCTAGAAATGGAACGATCAGAGGGCACCGTCGAATCTGGACATGCCTGTGACTA

          GTGTCCACAACTTCTGCTCAGATGAGAGTTTTGGCAGGCCTACGCAAAGCTTCTCTTGTC
          GCGTATCGCACTCCTTCTCATGAGACCATAAGGGTGACGCTGCGGTATGCTCTGTCCGGG
          CCGACTCTCGTCTTCGTAGGCATTGTGATACCAGAGTAGTTTGATACCGCTTCCTCGTCC
          CCGCTCCTTATTTACGCACGGACAGTGGTCATAGCGCGACCTGATACTGTTATTTAGATA
          AGATTCTCATTCGCCGTCGGAGAAGTTATTTTGGCAAAACCGCGGGGATCTCGTATAGAA
          GTATCCTTTATTTCTGTTAGGATCCGTACTCTTGTTAAATCCAGGAGTACAATAAATACC
          GTACTGTCGTTTGCTAGCAGGGCCCCCCTCCTTGTGGGGCCGTAGGGCAACCACACAGTC
          AGGTTGTTAATCTAAGACTGGGTAGTGTTTTCGGTGATATAGTATGATACCTACATACAC

          GCCCGCATGAATAAAGACAATCTCCCGACATGAGTAGCTTCCCTTGGGACTTATACTGCT
          ACCTGAATGGAACTACTAGGTACTATGCCAACTATAGAGCTGGACGGCATCGTCCATCGC
          AGTCAGTCAAATTTGTAGACGGTGCCTTTATGGGCGGCGTCCTGTAGTCGCCATCACGGC
          GCCTGCTTAGACTCGTAGACGATATCCTTATGAGCAGTATTTTGTGTTCGCTAACACGGC
          AGTCGAATGCGTCAGGAAACTTTTTTATGATAAATGGTATTTATCGAAATACGAATTAAC
          GAGTAAACTGTTTGCTGGGAACATCCATTGCATATATCACTGGCAGGTGTACACATCACC
          TACACTACCAGCGGATGATGCTGGATATAGCCAGCCGCACTTGTCTATCAACACTACGTC
          GGCAGCAGCGATTCGCAAAATATTCAGATGTAGGTAGCTCTTATTGATGTAGGCGCCTGT

          TACCGAGATAGAATCATGCGCGCCTGGATGATGTGAACTACCATCTGAAGGTTACCTTTT
          TTTCCAGAATATGGAATATGAAACACAACAAAGCTGCGTGTTACCAGTAAAATGTATATC
          TGTCTACATAAGGCAGAGAGAGCCTGGGTGAACCCTCACACTGAGTATGGGCACCCTCTC
          CGCTTCTAAATAACACTGGGAGTCCAAGCGCACCCTCATGTTGAGTGCGGGCTCCGTGTC
          TACTAAGATTATGGAGAGCTACGTCAAGAGAGTTGCCCGACTCGAAGCCGGCTACTCAAG
          CGTCGTGAAGTCACATAGAGGGGGTTGTTGTGCCCCGGGGTTATACATTGGTGTCTCAAG
          TCTCGAAGGCTTTATAGCCGTACTAAGAGGAGTGTTCTAGCTAGGTGTAGGCCACTGTGC
          AGCCGAACAGCCGTGGCGTGGATAGGGCTGGGACGCCGGGTCATAATTAGGTCGCTTCTC

          GGCTTCCTATTTTAAATGTATTACCTTGATAAGCAGAGGACCAAAAAGTTTGTGAGGACT
          AACCGATCATTACACGTGGGGCGACCAGGCAGGGAAAGGTCTAAATGTTCGATCGCCACT
          GTCCGCACATGTCGATCAGTAACCCTTGTCGCACGAGGCTCTCTGTACATTGTGATTTAT
          ACCTGTTTGAGCGCGTGGATGACCTCTGATGAAGGGGTGTCACTATGCACGCGAACGGGT
          TTATATATTTAGTAAAGTGCGGTTCGTTCAGGAAAGTTGATCATAAATCTAGAAAGCGCT
          ACAGCTTCACAGGATCACAGGAGAACTTGCGGACAGTAGCCATGCAAATCGCCTGTCCAT
          GCAAGCCACCGCAGTTAGGTGGGGAATCTTGTGGAGTCGCCAACAAACCAAGCTGATCTC
          ATTGGTGTGAGGTAGACAGTGAGGATCCGCATGGAGGTGATAGAATCATCAGATGCTAGA

          CTCTACTCAAAATTAAAAGTTCGTGTCCTCAAGACCCGCTTCTGGAGGACGGAGTGTCGC
          CTCTTGCTGGGACGCGAGGCTATACACACCGAAGCTAACCCTCAGATGCATATGAACCGT
          ACTGGAGACGTGGACAAGAATAACTCCTCTCGAACATATTACGGAAGAGGAGACCTGCAC
          CCCGAAGATGTGGGCGGGAACATCTCTTCTCGTACAAGTTTCGGGAAGGCGGAACTGCAC
          GCACGTAATGGAACACAAGATGCCTCCGGGAAGAGGGGTCTTTGCGACCGAGGACATAAC
          GTGCGTACCGAAACAACTGGTGCCCCTTTGGGCATAAATTTCAAGTCGGGCGCCGCCTGT
          ATGTAAATACTGCCGAGGACTATTCGTTCAGCAGTCTGCCTTCGCGCGAAGGGACGTCGC
          CCCCGAATCACGCGACAGGGTCTATAACTTGGAACTAGCATCAGTGCCGGAAATGAGTCC

          ACATGGTATGGCATGGATTTCACCCAGTGTAGAACTTTAGACTCGAATACTCCGTAGTCC
          AGCCGGGATTATACCGCGTTTGTTTGACACTGTAACCTCACCCGGACCGGCTAACTACTA
          CAAAGACACACCACATTGCATGGAAAATTTTGCCTAAGCACCCTGGTTAACCGGTGTTTA
          TAATGATACAGTACTGTGTGCCCTAGAACATATCCAAGCAGTTAGGTCACCGGATCCCTT
          TACGAATCATGCATGTTACGTGCATATACTAGGACTCGCTTCTAGGTTGCTGCTCTGTGG
          TACGGGCCAGGAGTTTTACACATAGACCCCTACACTCGCGCTCAAAGCACAGCTCTCTAT
          CCTTGCCAAAGTTTAGCATATGTCTCTATCCTTACGTGTGTCCAGAACGTTGCTCTAGAA
          CGCAGACACTATGCAGGATATATCGGTCCTAGAAGGCACAGCAGCGTAAACTATCTGTAC

          TTTGTCTCTCCTATCAGCGATTATGTGAACCTTCTACACG
          GTTATTTTTTCCGAGAAGCTATAGGGGATCCGCTGGAGCA
          CGTTATGGCGCCAATGGGTTAAACGGGAATCAGTACTATG
          TCCTAAGTTGCCCACAGGCTGAACAACATTCGACATTTCA
          CTCAACGCACATCTGAGAGAATAAGGGCGTTAATATTATT
          CATCCCACACCCCAAGAATCGTACCCGGGTTGGCTTTACA
          CGTCATGTTTCTCCGGTTTAACCCAGAACTTAACACTATA
          TTAGGCATACACGCGGGTCCAGTTGGGAGAGGGCACCATA

