 8 1000
t1        CAGGTATTTAAAGCGGATCTCATATGGGCCGTGTCTGGTCCGTCCCCATAATCACTCCAC
t2        CATGGATGCGAACTAGATTCGATATAAACTGTGCTCCTCTAGCCACCATGTTCTCTCCAT
t3        GAAGAATCCACACTAGATCCTGTGTGCATAATTCTTGTCCAGTTTTTATGTTGGCCCTGC
t4        GATTAATTCCCGGTTGAGTACGTGCGGGCTATGCCCCCCTAGCCTCTGTGGCTATTTTAC
t5        AATGGCTCGATTTTACTATCCGCGAGGACTGAACTCTTACCACTATACTGTTCGTCCTAC
t6        ACTGGCTCGATTCTACTACCCGCGAGGACCGAACTCTTACCACTATACTGTTCGTCCGAC
t7        AAATACTCAGTAACTCAGCATATGGGGTACGCACTCCGTTCTTCTGGCATCTCATTTAAC
t8        ACGTGGTATACGACTCACCATACGTAGCAGATGTCCCTTTTTGCCGGTTCCTCGTCTAGA

          CAGAAGCCGCCGTAGCATTATGAAGGTTTGTTGCGGGACAAGACTCAATTTTTCGCCCCG
          CGGAAGTAGTCAGAGAAAAGCGGAGGGCCGGGGTCTGGCGATCCCTAGTACATGGTACGA
          CACGGGTAGTCGAAGAATTCCGGAGGGCTGGTGCGGGGGCAGCCTCAATGTTCGGACCCG
          CGCAACCTATTTCGGCACGTCCCACGCTTGGAGCTGGACGATACTTGGGACGTGATGCTC
          AGGTAGCAATCAGGAAATGCCGGCAAAGTAAGGTGAGACGTGATGTGATTCTTCGACGTG
          AGGTAGAGGTCAGGAAATACCGGCAAACTAGGGCGTGACGTGATGTGATGCTCCGCCGAA
          TAGTAACGACAAAGGAGCCCGCGCTCCCTAGAGTATGAAGTGCCTAGTTTGGATGCACCC
          TAGCAACGACGAGGGGACCAGACATTACGAGGATTTGGATCGCCTCATCTAAGGGCTCTC

          GAGAGCCAGGAGCCAGCTATTCGGTACGACGCACGCAAGGCGGTCGGCTGAAATGCCAGA
          TAGACCGCCGCCTGTACTATTTACTGTAATAACCGGAAAGTAAAGGGCCAAAACGTCGGG
          AAGAGTAAGAGATAGTCCACTTGTTATAATTCACGGAACGAGTACTGGCGGAACGTCGTC
          TGGAACCGGGGCCGGAGTAGCAGCTCTTACACAAGATTACATCACGGGCGGGATTACGGC
          ATCGCACCAGAGCGAATTACATGCCGCAGCATTCGCATGACAACTTAGACGCGGCCTGGG
          ACCGCACCAGACCGAATTACATACCGCAGCATTCGCATGACAACATTGACACAGCCTGGG
          AGGCTTTAACGTCAGGTCCAGCGTTTAGTCGGCAGAAATCCTGGTACCAAATTAACTGGG
          AAGTCTGAATGTTAGGTCAGGCTTTTCGACAGGTGGATCCTCTATTTGAGATTACCCGGA

          CAAGCAATTGCATACCTATGGCGTAAAGTCGTGCGGCTTGTGTCGACACTATATTAATAC
          CGAGGGATTACGTATTGATTACATAAAGCTTTACAGCTAGTCTCATTGTGATACCAATAC
          ACGGAAATGGAGCTCCTATCGAATGAGGCTCCATGATAAGTCTCGTCTCTATGTCAATAC
          CGATCAAGCGTCCTCTCACGACACAGTGTTTTGTAGACATCTACATCCCTGTATCATCGC
          AGAATAATTTGGCTGCGTTCACGGGTCGGTCAACAGCTCGGCCAACAGCTACATGCATGG
          AGAATAATTTGGCTGCGTTCACGGGTCGGTCAACAGCCCGGCCAACAGCTAAATGCATGG
          CTCTTGTTTTAGGCCGGTGAGTATGAAATTAGACGATGGGGTTCCTTTAACTCTCCCTAA
          CATTTGCCCCAGACCAGATAATACAAACTTGCACGATAGCGCTCTCCGTTATCTTTCTAA

          GCGCCTAACGTACCTAGCAGTGCTTCGAAAACCGGATCGGGAATGACTTATCCCGAGAGA
          GGGCCTGCCGCTTCAAGTGGCGCCTGGCCAAAAGACCCGGGCGACACTAGTTCAGGGAAT
          GCGCCTGACGCCCCAAACGGAATCACAACGCCAGAACCTGGAGACGTCGTTCTCGGGGAA
          GTGTCTGCCACTTACAGCGGTGCTCGAGGAATGGAAACGGCAGACGCAAGCCCCGGCAGG
          CCGCTAGGCGTCTTCAGAGGTGTTTGCAATATAGAAACGGAAGGATATTGTACAGGCCGA
          CCGCTAGGCGTCTTCAGAGGTGTCCGCAATCCAGAAACGGAAGGGTATTGTACAGGCCGG
          GGTCCTGTGGTTTTTCAGGGCCGAAATAAATTCAAAGCGACCTACGTCCGACAGGCCTGA
          GTTCCTGTCATAGTCGAGGACTAATATAAAGATGAATCGTATTTAGGCCAATAAACCGAG

          TGATTAGTGCTCTTGGTGACGTAATTAGTCTGCGATCAACATATTGACACGGGAGGGTGC
          CGGTTAGGGCACTTAGTGATGGAGTCAGTCTGCGGCTAAAACATTTAATCGGGGGCAGGC
          AGGCTAGACTGGTTAGTGTCGTAATCCGTCTGCATTTCGCGACTTTACTTGAGAGCAGGC
          TCGTTAGAGAGCTCGGTGGGGTAAATTGATTCCGACCAAAGTCCCTCCTCAGAGAGGGAC
          CGACCGCCACGCTTAATGGGATAGTTGGTCTAGGGCCTAAGTGTTTCCACGGAACCAGGT
          CGACCGCCACGCTCAATGGGATAGTTGGTCTACGGCCTAAGTGTTTCCACGGTACCGGGT
          CGTCAATAATCTGAGGAGGGGGTGTGTGTTACTGCCTACCTCCACCCGTTAGTAATGAAC
          CGTCACGAAGGTCTGGTGGGGGGATGTGTCACTGCTTAACTCTCACCTTTAGGAGCAAAC

          CTAAAGGTTTGTTCTTCAGGCTGACGCTGACTTGTAATATCACTTCGTGACAATAATCTG
          GTGGAATTCCAGTCTCTGGATTGAGTTAAACTGACGAGGTAGCCCTGAGCTAATGCTTCT
          CCGGAAACTTGTGATCCAGGATGAGGCCGGTCGATAAGGTTACGCTAAGTTGATATTTTT
          TTGATCCTCCGGCTAGCTGATCGAGGCTGCTCCACAGGGCAAAGCCGTGTTGAGATAATC
          CAGGTAGACTACGCTGCCGACCATAGTGGATTGACATACTCACATACCACAAATACTCCC
          CAGGTAGACTACGCTGCCGACTATAGTGGATAAACACACTCACGTACCACAAATACTCCC
          GACGTAGGAGATCTGTCGATACCGCCCCTTCCATCCCAGCGTCCCTCGACCCGTCCCTTG
          AAAACAGTTAAATGTACGACATTGCCTCTCCCATTACGGTGTCCCTCCATCGGCGCCTAG

          AGAGGGCCCCGTCTTATGCGAGACACACTTGCGGTCAATAAGTTATCATCATCAACATTT
          ACGGGTTTTTATGCCATCTGAGACAACGGCGCGGTCATTCAATTCTAATCCTCAACTTCC
          CAAGGTCCTCGTGGGATCCTAGATAATTAAGCGGTTATTTAACCCTCATATTCATCTTTC
          AACGGATTGCAGTTGCTCCGTGGTAAGACTGCGGGGTCACAGTCCATGCCCTTAGGCTAC
          ACATAGCCGAGGCTCACTTGCCACGTTCCTGCCAACCTTCAATAGCTACCCTCAATACCC
          ACACAGCCGAGGCTCACTCGCCATGTTCCTGCCGACTTTCAATAGCTACTCCCAATACTC
          TTGAATCATGATTATATGCGTGATGATACCGTAAGTGGCAACATTTTTCGGATGTTACCT
          TTGCCACGTGATTTCTCGTGTGAGGACATTGTTGGTGGTTACATTGTTTGGTCGCTCATT

          CTGGTGTGCAGGTGCATAACCTTCAGACAGTCCACTGAACATCTGCCACAGGCCGCTCCA
          AGAGTACATAGGAGCAATACGTGTAGCCGGTCCGCTGCACATACTCAACAGAACGACCTT
          CTAGTTTGTAGGATCAGAAGCAAGAAGTGGCTCACTAATTGTCGTCAGGAGAGTGATCTA
          CAAGAACATAGTTGTCGTAGTAGCAGGCAATCGATGGTTGACCCTCGGCAGAGGGTCCCA
          TGTAGGCGCAAAGGCAACAGTTTCTGGTTATGTGTTGCTTGTCCTTAGAACCTTATTCCA
          TGCAGGAGCAAAAGCAACAATTTCTGGTTATCCGTTGCTTGTCCTTAGAACCCTGCTCCA
          GTGGCGGGCGTGCGAGTATTGCGGTAATCATGGGGTCCGTCTGGGAACTCTCACGCGCCC
          CACGGGGGTATGTGCGTATAACGGTGGCCATGGAGTCAATCTTGCCACCATTACGCGCAC

          TGCGTACTGGAGGGATGGGCTAGCCGATAACCACCCCTTCCCCTTACGAACCTCGTTTCG
          CGTTGACCGGGGAGCTGGGCAATCGGCAGCCTACTCCCTCCCCCTACGAGACCCGACGCG
          TATCTACTGGAGAGGCGGAATGACGCATAGCTATTGATTATTCGTACTAAGTCCCACACG
          CGTTAGTCGGCGCTACAGGCCAATAGAAAGTCATCCCTTCCTCATATACGCGACGATGTG
          TGCCGTGTGAAACTGCATGCCGACGTTAAGGGCTTCCCAGTCCCGATAGACCTTGACGTA
          TGCCGTGTGAAGCTGCATGCCGACGTTGAGGGCTCCCCAGTCCCGATAGACCTTGACGTA
          CGCCGGCCGACAAACAGCACACATCTTCCTTGTCAATTAATTTCACGAGACCGCGATCGG
          CCTCCGTCGAAGAACAGTACGCGTCCTGCATTCTTAGTAATACTGCAATATCCCGGAAAG

          GAATCGCGGTACCAAGCGTGCCATTACGCTATGAAAATCGCGAATTCACCCGGAGCGAGA
          GTTATTTGGGATTGGGCGTGCCGTTGCCTAGTGGAGACTCCCGCTCTGCTCGGTATCCGT
          GAAGTTTGACATGGGATGTGCTATTACTGTTTGATGCTCACGAATTCACTCGGTCTTGAT
          GGGATTAAGTATCGCGCGTGCCACTACCCCTTGCTGAACACTAATTTCTCCGGTTTTGCT
          GAGGTACAGCTTCAGGTGAGCTGCAGTAACCTAGGAATCATGAACTCGCTTGATTTTCCA
          GAGGAACAGCTCCAGGTGTGCTGTAGCTACCTAGGAATCATGGACTCGCTTGATTTTACA
          AGCGAAAGATATTGGCCCACCCGCACTTAAACAGTAAACTTAGACCTATTCGGCCTAAGA
          AGCCAAAGATAGTGGTCGTCCTCTAGTTAATGGAAAGAATCAGACCGACTCGGCACGGAA

          CGTGCGAGCTGAGCCCCATTTTCTCCATGGGGGCTACTACGGGTATCGGACCGAAGGGGC
          CACAAGATCTGGAACTCCATTTTTATGTGAGCGTGATTACGGGAATTACACATATGGAGC
          CATCAAACTTCAGGCCTTTACCTTCCTTGAGCAGGATCACGAATATCGATCAGACTGAGT
          TATGGGCTCATATCCTCCTTTTCTTTGCGGGGACGACTATAGGAGGCATGCAGAGAGCGC
          TCCAGGTTTTCAAACTTTCTATCGGTGAGGATATCATCACGGGAATGGGGCAAATTGACT
          TCCAGGTTTTTAAACCTTCTATCGGTGAGGATATCATCACGGGAATGGGGCAAACCGACT
          GGCGCGTTTCGTTTAGAATTCTCTAGGCTGATATGTTCTCGAGTGATGCCCGCAGTCCGT
          GACGTCTATTGGTTACGACTTTCTCCGTAGATACGTTCGCAAGTAGAGCCACCAGGGCGT

          GCATTAGAGTTTGTAATTTGCACGTCTACGCGGTTGCGCCCAGGAGTCATACGCTGGCTC
          GCCATGGTCTTTGTAACCTGTACGTGAATGCGGTTCGGATCAGCTGGTATATGAGGGTCG
          ATCTTGGGAATCGCAATCCGCAGGCCTACGTGACCACGCACATGTGTACTGTACTAGTCT
          TTATTGTAATTAGGAATATGGATGAGTACGTGGTTATCCTACAGTGCCATGCGCCAGTTT
          TAACAGAAGTCCGTAATGCACACTCGACTCTGTCTGTGCCAAGGCGCTATGAATCGGGCC
          TAACCGAAGTCCGTAATGCACACACGAATCTGTCCCTGCCAAGGCGCTATGAATCGGGCC
          GATTTCGCGTTCCTACCGGATACTAGAATATGTTTATGCGGAACGTACGAACGTTATCTA
          GACCCTGCCTTTGCATCTAGACCTGAGACATGTCTACATGGAGCCTATGGACGTTAGTCA

          CTATTTGATCAAATACCCGTGTCATCTCTGGCGTCAAGTCTGGCCGACGGATTCGCTCGG
          CCCATAGATCCCCTATTCCCATCATTGTGCGCGTTGATCACGAACGTTGACTCTTCTCCG
          CCAGTTCAGCCTGTGCTTATGTAATAACTGGCGCTACGCGCGGTCTTGGGCCACCTTCGG
          CACATTAATTTCTTGTGCGCGTGACTACTGGCGTCAAACATTGCCATTAGCCAGCTTCGA
          ACGGGTGATTCTATGTCCGTGATATTGTTGGTGTCATGCAAGAACGACGGAGCTCACTGG
          CCGGGCGATTCTTTGTCCGTGATATCGTTGGTGTCATGCAAGAAGGACGGAGCTCACTGG
          TCTGATAGAATCACGGCCCCATCGCTGCCAATGTCTGGCTTGAGATTAAACCTCTCCACT
          TTGGGCGGGATTACACCTCCACTGTTGACAACATATAGTTTGCGTACCAACTCCTCTCAC

          TTACTGACGTCTATATGATTTGAAACATGTTAACTTGCTCCGATAGGCACACGGAGCCCG
          CGCACTGCGTTTGCGTGCATCGAGACACGTTAGCTCTCACTGAGAGATGCTCAGTAGTTG
          CCCCTTGTTCTTCTACGTATGAGGAGACGTTGATTCTCACCCAGACGCGTTCGGTCTTCC
          CGATTTGTGTCTCAATGGATCGAGACAGGTCGCCTCTCTATGAGTTGCGCGCTATTTCTG
          TAATTTAAGTTTGTTCGCATCAACGCTTTTGAACCCTCTTTGAGCAAAGTGCCTCCTCCC
          TAAATTATGTTTTTTCGCATCAACGCTTCTGAACCCTCTTTGAGCAGAGTGCTTCCTCCC
          CGCCGTTGATGGTTAAATACGGTGACAGCGGAGCCATCTCTAATTCACGCGTTTCCCTTG
          TGACGGATTCGGCAGTGTATGGTAACGGCGGCATCGTTTTGACTTCACGCGCGACTTCTT

          CCGCGGTTCACGCCCCCAGGCGAGACAAGTGGGTGTGACCTGCACAATCGGCGTATTTCG
          TCACGTTTACTGCCCCTGGGCCGGGCTAGCAGGTCTAACCAGCACATTCGGCGCAGTTGG
          TCATGATTACTGTCCCCGGGTTTCGTAAGTGGGTGCGACCTATAATCCAGGCATGCTTCG
          TCGCATGTAATGACTTCGAATCAAGAAAACGGGTATAGTCCGTAGTTTCCGCGTACTTGG
          TTCGGATTTATGGTTCAGGAGAGGAAGACGAGGTGTCTCACGGAACATCGGTGTATTTGG
          TTCGGGTTTATCGTTCAGGAGAGAAAGACGAGCTATATCACGGAACATCGGTGTATTTGG
          GGACACCTACAAACCTAGGAGCTGCCCAGTCGAAGAATATCAGAACCACGCTGCAGTCGA
          CGGTACCTCCCAACTCTGGGGCTAATCCACCAACGTACAACTGCATTATGCCCCTGTCGG

          AATCTAGTACTATGTTCACAGAAATGGTCGGTTGGGGCTA
          TACTAAGTGTACTGTTCCGAGTACTGGCCCGTTAGTGGTA
          TGCCTGGTAAGTCGCATTGCAGCACAGCTGATAAAGGCAA
          TAACTTGTATGCACTTTCATGACACAGGCATGTGAGAATA
          TACCCGATTCAAAGCGACACGACATGGCTGCTCAGGAATG
          TCCCCAGTGCAAAGCCACACGACATGGCTGCTCAGGAATG
          TGAATGATTATTCACTTTATGGCGCGGTTTATTGGGGCTC
          AGCAAAGTCCTGTACCGTCCGGTGTGACTAATTAGAGGAC

