 8 1000
t1        AGACCTACGCGGCGTTAACGTTGCGTCTCGGGCAGTCTGCCTGAAACTATGACGGAGACG
t2        AGGCCCGCGCTACGTTATCGCGGCGTCTCGAGCCGTCCAACTGCACATTTGCTAGAGCCG
t3        AGGGCCGCGCATCGTCAAAGCGCTGTCTATGGTAGCCCAGCTGTATTTACGTTTGAGTCG
t4        CGCCCTATTCGATGATTGTGTGTAAACCTTGGTAGACCCATTAAACCCTCACTGGTAGTG
t5        GTCTTTCCGCTGTGGAAGCGCGGCGGGCTTGGTAGATTATCCAGGCACTCTTCAGGGACG
t6        GAACGGGCGTTGGATAGGCGGGCAGTGGTTGGAAGGTCAATTCGCCGTTTCTCCGGGGTA
t7        ATACCCGCCTTGTACGAGTGCGGATCTTCACGCATACTAATATTAGTTCCTCCGGGGGTT
t8        ACTTATGGGCTGGCTAGTTGCGGCATGTTCCCCGAGTCTTACAGGCCTTTCATAGCCTCC

          GCGAGCGAGTCGGAGACAGGTGAAACATGTACGGAGTTGTAGGACTAGCGTGTCGAGACC
          GTAATGGTTGGAGTGCCGCGAGGGGAAGGCGCTAAGTTATGGGGCCAGCGTCTTGAGATC
          GTTCTGGATGTAGTGTCACGTGGGGCAAGCCTCGAGAGGAATGGTTAGGGTGTTGCGACC
          TTAAAGGATCCAGGAAGATGTGTGATGTGCAACATAGTGAGGAGTCTGCCTATTGCGTGA
          GCCAGAAACATAGTGGAGCGATCAGCAGGACTCTAGTCATATAGTTCAGGTGTTTCGGAC
          GTATAGAACGCGGCTGTGAGCGGCGAGAGACTCGAGCTATAAGGAACAAGACCCCCAAGC
          ACCAGAAACACCGTCGAGTACGGGGGGGACGATCACACGCGGGCGTCAGGCGTCGAAGCA
          TTAAGAGGCAATGCGGAGGACGGGTTATGGGAGAATCGGCTTGCGAAAAATTTTATGGAT

          AGTGCCGGCATTTTATCGTGCCGGTTGGCTGTATTCTTTCTGGATTCCAAATTGACAAAA
          AGTGCCGGCCTTATATCGTGTTGTGTGCATGTACCCTTTATCAGTCTCAAATTGAAAAAA
          GGCGCTGGCATTATATTATGCCCGACGGACGCCTTCCTTTTCGGTTTCGCGTTGGAAAAA
          GGACCTCGTACTGTATTGTAACTTCAGATTGTATTATCATTCGGCCGTAATCCAGAATAG
          CCGGTAGGCACTTTACCGTCTTAATCGGTACGCCCAGAACGGGACCTTAACCCTGTAACA
          CGGGGAGGTGCGCCTTCGTGCGTTTCGATAGGTTGAAGCCCTAATGCCCGAATAGCTACG
          TCCGCTGCCGCGAAGCAGTCATATCCGGTCCGATTACATCTTCGTCACACCCTCAACGCG
          TGACATGGTGTCACCCCGCTGTATACACTAGAACGAGTGACCTAAAGTACCTCAGTTATA

          ACGCAGGAACTGAGGTCTTTGAACCCGACTGTTCCCGTTGTGTGTAATTCGATCCGGGAC
          TAGCAGTGGCCGAACTATTCGGATCCGACCGCTTGCGTTGCGCGTGACACGGATAGGTGC
          TCGAAGAGCCTGAAGGATTCGGCTTCGACCGCTCTCGTTGTGCGTAATCCGGTCGGAGGT
          GTACCTAGCATGGAGTGCTTCGTTTCCGTCACTCTCGAAGTGCGCAACCTGATCAGGAGG
          AGGTTCGATTAGGGGTGCGATGCTCTAAACGCATCTGGCTGGTTAGGTCCAAATAGGCGT
          AAGTCTCTCCTCAGATAGTGAAGTTCAAATAGGTCCACTGAGCTTGGCGTACAACGTGGC
          GCACTTGGGTGAATGACGTGTGGACCAAAAACCCTCAACGCGCTGAAAATGAAGGTAAGG
          TCATTTGGGTGGTAGAACTTCTGAATCAATGGCTGTACGGCGTAATAGGCGAACTCTGGG

          CGCGGAGTATTCCCACCGACGCAAACGGCTAACGCCTTGCCTGGCCGTCGCGTTACTACG
          CACGGGTCATTCCCACTAGCGAAGACATCCAGTCTCCGAGCTGATTGTCGCGTAATTAGC
          TTTGAGCTATTCCTACTTGTGAAGATTCCTAATCTCTGGGTAGGTAGGCGCGTTCAAACG
          GGTGGGGACGTGATACCCCGGCAGATTTATACACTCTTGAGTGCTCCTCACGTTCCGATA
          CAGCAGGGTGTCTAACCCTCGTAAACATCCCTCATTGCCGCGATCCCTAAAGTTAAGACA
          GTGTGACGAATGTAGCAAGCATAGATTACGCTAATGACAACTTTAGGATAAGTTCACCGT
          AAAGAGGCCGATTAGTGTGTGGAGGCTGCTACCCGATAGATAACCGAAACCACGGGGAAT
          CTGCGAGCCGTTCCGACTGGGCGAATGCCAGATTTGCGGTCAGTCGGAGCTTATACGGGA

          CTCCGTGCCAGCTTGCCTCTCCAAATTCACTAGGGAACTGACCTAGGACTCATTAGTCGC
          CTTTCTGGCAGTTGAGCTTTCCATATGCACCAGGGGACTGACTTAAGAATCGTTAATCGT
          GCATGTGGCCGTCCATCGTTCCCGATTTACCTGGGGATTGATATAGGTCTTCCTAAAAGG
          CTATGCCGTAGCCCGCCAATCACAATCGATTCAATGATTGGCTTTGGACCTACTGCCTGT
          TACCGTCCCAATTAATTATAATTTCACAATCGAAAGGTGAATCTAGAACGCGTACTCTAT
          TCTCGTTTCGTTAATCTAACGCTCTCCTAAAGCGGGTGTGGTCTATCACAACTAAACCCC
          CTCCACAAGAGTTGCCCATCATTCTCCAACCTTTGGGACTGGTTGAGGCGTGCATTCCAC
          CCTCTATACGATCCGTTAACTATTGTGCGACATGGCCCTAATAAGAGGACTAACACCGGC

          GAGAAGTACTCAGCGATGTCGAGCGCACTTTTAGAGAGCATGACGCCTCAACGAGGAATT
          AAGAAATGCTTCGCGGCGTCGATTGTTCCCCTTGGGGACGCGAGACTTCAACGGGGAATC
          ATGAAGTACTTCACGGAATTAAATGCTTGTTCTAAGAACGGGGAACCAAGACTGGTACTC
          AATCCTCGTATACCGCACGCGAGTATATTTCTTAGGGACAGACGATATCAATGGAGATTC
          AGCGGGCCTCATAAATAACTGGGCGGAGTGTCGGGAATGGAAAGACGCTCTTAGCAGGAT
          CGCATGTCGTTGGTACTCACCGATAGTTCCTAAGACGTCGCTAAACAAAAGTTACGACAC
          GGCCGGAGTTTAAAACATGAGTGCGGGTCTTCTGCAGGCACCACGCAAGGAGTCAGAGAC
          AGCGAAAGTGCGTAGGCCACGACAGAACGCTCAACATACCCATTACACCGTGGATGGAAC

          AGATTTGGTTCGTTTTGACATCACCCGGTAACTATACAACTAGCTTGGAACTGGATGACA
          TGATTTGACTTGTTTCGACGTTCTCAGCTAATCCTGCCACAGTTCCGGAACCAGATAGCG
          TGATTTGGTTCGTTCTGACGTCGCCGGATAAGTGTATCATCACCTGCGAACTGGGTGGCG
          AGATTTGGGCCACGCCGGTATGATCAAATAAGCTTTGTATTGACAGGCGACGGGTTGGTT
          TGTTTCATTCCATCCCGACGTCGCCGCGAAAGGACCTCACCTGTGAGGGACAGGACGGCT
          GCCTCCACCCCGCCTTGACGCCGCTTAACAGGTTTATAGCTATCCAGGTTTAAGACCGTT
          GGAACCGTCGTACTTCGGAGTCAACAGTCAGGTTTGTTCATTGCAGGTGATCGAAAGATT
          GGGATTGATCCATAGGTGGCCAGAGAATTAAACAGACTGCATGTATTGATTCACATAGTC

          GACCTGCGACAGACCCCAGCGAAAGTATTGCATCACATTGGTGACTCTCACATTTTATGA
          TACCTGCGACGGACTACGGCGAGGGTGTCGGATCACGCTGGTGTTCCCCGCTTTTTAAGG
          GATCTGCGAGGGGCCCCAACAAAGGTGTTGGATCACACCGTTGGTCCTCACACATAAAGC
          GCTGCGCGAAGAAGTCCACGAAATAATTAGGACCTCCCTGATAGACTCCTTACTCACTGG
          TTATATTGGTAGCTTGTAGAGTCACGCCCGGATAGAGCAACCAGTATGCGCGCTCCCGAT
          CGACCGTGGCAAGTTGAAATGAAAGAGTTGATCCATACTCATGAGCCGTATGTGCATACG
          ATGGTCTGTAAACTTTCGGAAAAAGTATTGCGCTGTGTTTAAGGTGCGGGCAGATAGTGG
          ACGCTTCAGCAAATTCAACTAGGAAGGCCAAACCGCATTCACTTCCTCAAGCTAGCTGGG

          GGTACATTTTAATTATTGGCCATTCAGCTTGGGCATCCATTGACAGAGGCGTGCGAGGGT
          GTCACGCTCTTGTTGCTGACTACACAGCTGGAACATGCATCAACAGAGGCATGTGAGATC
          GCCACATTCTCGTGACCGGCTACTAAGCTTGAACGTCCGCCGACGGAGGCATAAGTGACC
          GCGACACTCTCACGATCGGCCGTTGCGTCTGGCGGTGCAACGTCGAAGTTGGGGGGGACC
          GATGCATCCTCCGAAATCACCGTCCCGCCGAGGCGCCTACCTTTGGATCCTGTGAATAGG
          CGTGCGTCAAAGCAAGTGGCGACCACGTACTGGGCTATGTCATTAGAATTACGCAACGCA
          GAAAGTTAACTAATGACGGTTTATGAACAAGAAGCTCTATCGACCCCGATGCCTGAGGTT
          ACTTAAACCTAAGAACCATAGGCCTTGCGCCGGAGTTTAAACGTCCTCGAACGGAAGATA

          ATGAGCTCACGTTTGGATCTTCGCCTCCCCTGAGGAAATTCGACTCTCTTTACCATTACA
          GTATAGCCAGATTCCGTTGCTCACCCTTCCTGAGGAAGTGTGACTCCATATATTATTACA
          CTCCAACCTAGTTTCGTTATCATCCTGACCTGAAGGAATACGATACACTACATTAACCCG
          GTGTGACTTACTTCTGTCTTTTGCCTCTCCTGAGTTCTTACCACTTTCTAAACTTACACC
          ATTTGAATTTTCTGTATCTATTGTATGGGGCGCGAAGCAGTCCCTGTCCGTATCGTAACC
          GCCTCCTTATCAGCCGTCCCATAGACGCCCGAAGTGATTCCCATTGGGCGCATTAACTCT
          TTTTTTCTGCCGCCTTGTATTCTCGCATTCCAAATAGTTACGCCTTTATAAACCACTGCC
          ACTTTTTACGCTCCGCATTTTTGCCGAGTCCGAGGGCGCGTGATTCCACCTTTTCTTACT

          TCGGAGGTCATCTATATGCGAGGCCTATGCGCCTTACTCTCAGAGGGAACTCTTACCTCG
          ACGGCTTACATCTCAATGTGAAGCTTGTGCGCATTCCAATCGAAAGAGCTTCCCTCCTTG
          TGAGTTATGATTTCTAGGTGACGCTTGGGTCCCTTTTAGTCGTAAGAATTTCCTGACTTG
          CGGGCCATACTCACCATGTGAAGCTTGCGGACCTTAGAGTCTTGAAAATATCTCGACTGG
          GGTTTTATAATCAACCGGAAAGCTCCAAGCCTTGCTTAACTCAACAAAAACTTGCGTTAG
          AAGCCTCCTGTTTTTGAGTGGTGAAATGACGCAGCAGAAGAGACTGATGACCTTGATCCA
          CTCCTTCGATTGACAGTGAAACGTTGATTTCCTTTCAATCAAAGCTATCATCTAGTCGAA
          TCCGTTAGAGCTTACTTCCACTTGAAACCCCAAAGCGGACCTCGCCGCTCCACGCGCTAG

          GTAGGGCAACTTTAGTGTCGCGACGGCCAGTGGAGTAGGCTATTCTTGGCCACAGAGTAT
          TTGGGGCACGTCCAGGATCGTATTTGCTAAGGGAGTTGGCAGTTTCTTCCTACGGAGTAG
          TTAGGGCAACTTCAGTACCGCCAGAGTCAATGGAGCTGTCAGCTCTCGCCCACGGAGTAG
          CTTGGGTAACTTTCGCGTTGCGCCAGACGACAGAGTTGGAGGCTGTTACGTATAGGCAGA
          GTCACTCAATGGACAAATCCTGCCCGTCGACGGCGACGGTCGTGCCGGTGCTTAAACGCA
          TTATAGCTTTCGTCCTGTCGGGTTGATCGGCAGTAACGAATGCCCCATTGCGTGGACGTT
          CCGGTTACACGTACACGTCGCAGTGGCTAGTCACAGCGGCGGTTGCTGAACGGGATTCTT
          CTACGGAAGGACAGCGAATGGCCGAGTCGCATGTGTCATCTACTTTCTCAAGCTAGAGAA

          TCCTCGTCTAGAGGGCGACAGCGATCAGCTTGGTTTGACACATTGCTGGGGTCCCTCCGT
          TCTTTAACAGAAGAGCGCCAGCATTTGACCTGGCCTGTCATGTTGCTGGCTCCTCACCGC
          CTCATAGCTCAGAGGCGTTAGTTATCGACTTTGTTCGCCCTTTTGCTCGGCTCTTACCGT
          TTTTCGGATCATAAGCGCCAGTGTGTGGCGTGACTTGCGGCACAGATTGGTCTTCTTCAT
          TCGGAGGTCATTAAACGTAGGCTACCTGTTTGACTTGCTAGATCCCCGAATTTCTATGGC
          ATAATAGTCGCGGATCGCCGAATCGATGACTAGATGTCGGTCTCGTCGTGCACTTACATC
          CGGACATATCCAACACGTGGGTGCGCGGTGAGGACAACGGTGATGATTAGTCTTTCCCAG
          TGCTTGGAGATCGCGTCTCTCAACCAGCCCTGGCTCCCCGCATCACTATCTGCCCATCGT

          CTGCGCACATGTCAACAAGATGGTTAAACGGTTTTAGGCCTCGGGAATTATATCGACTTT
          CTGCGCGCGCGACGCCAATGTTGCTGAACGGGTTAGAAACTCAGGAATTGTCGTGATCTC
          CCGAGCGCGAGGCGACGGTATCGGTAAACGGTTACAGGACTTAGGAAAAATTGCTATTTT
          CCGGGCGCGGGGTGAAAGTTTAGCCAGATGGCCAAAAGACTTGAGAGCCATTACGCCCTT
          TGAGGCCGCATCTGCCGAACCATCCGGATGGCTTATGGGATCATGAGTCGTCATACTCTC
          CCGCATTCTTGGAAAGTCTGTGGCCGGGTTCTGCCTTGATCCGAGAATAGCCATAGTTTT
          CGGCCAACTTAGGACTGTCGTTCCTCTCGAGTCCTCAATTACAGGCCCCGTACCGAGTCT
          TCCAGATGCTTAGACTGTTAATCTCGTTGTCTCTCTGTGTGCCTGAGTTGCAGAGTTTCC

          AACGTGAAACAGCAACACTGGTATGAGGTCCAATGCTGGGGACACGAAATGCTAGGTCAC
          AGCGTAAGACTGCAATACTGGTAAGGGTCCAGGTGCTGGGGACAGAAGACGACTGGCGAT
          CGTGTGAAACATTTGTACTAGCATGACACCAGGTGCCGGGGGCGGGAGACGCCAGATGAA
          GCTGTGAGGCATGGTCAATAGCAAGCAACTAAAAGCTGGAGTTCGAAAGCGCCGGACCAC
          AAAATCGGATCGAAATTTGGAAATTAGCCAACCCCCCATGGCACGGCGATGTGTCAATAA
          GAGGTATAGCCTGCAAACGGACTTCCGAGCAGTCGCTAGGTGTTGGGATCAAGTTACTTC
          GAGACTCTGCAGAGACTTAGACCCGTGGTTCATCACCCAGACTCAGCAATGGCCACCCGT
          GAAGATGTGGGTTGATATTGAATCGTGAAAAGTCTGTAGAGGCCGACAGTGCTAGGGGAC

          GATGGGAATGATATGCCTATTCCGTCATAATTCTTCCCTA
          GAAGGTTACGGTCTACCCATTTTGTCAAATTCCCCCCGTA
          GACGGCTATGTTCTGCCAAGTTCGCCACAACCCTTCCGTT
          GGCGGCTATAATACACCGCTTCTGCCGTACCATGTTCGCT
          GTTAGCTAAGTCGTTGCACTATAGTAACGTTCCGCTCGTC
          TATGGCTCCGAATCCACGTTTCTATGATCCCCTGCCCGCC
          GGTGGGTATAGGAACGATCTCATGCTCTTCCAATGCTGAC
          CCCCGCTACCAATTTTTGTCTCCATCCCGCACTCAACGGA

