 8 1000
t1        GCGGTAGATGTCACTTACCTCCCCTCCCCAGGTCCGTGTCATACGCGCGCTAGTCCGTGA
t2        GCGGTTGATGTCATTTATCTCCTATCCCCAGATCCGTGTAGTACGTACGCCGGGCCGTGA
t3        GAAGTCGGTAATTTCCTCTATCTCCCCTTGGGGTCGACACAGGTGTGCACTAGCGCGAGA
t4        TTGGATGGGGTCTTCTTCCGTCGCCCCTCCAGCTTGCCTCCTACAAATCCTGTAGTCTAA
t5        ACGCACGATGACCCACGATACGAAATTTTGTCGCCCGCGACTGCTAGCCCCGAGGAAGGC
t6        GTAGCTGGCTTTCCATGGCATAACCTCTTAGGCTTCCCAGTGGCCTGTCCAGAGGCTGGT
t7        TCTGCTTGTTTTTCCCTACATTTTATTGTAAGGCCTTATGGTGGTAGTCGTAAAGCCGGA
t8        TTTCTTTCTTTCTCACTACGAGCTAAAATAAGGCCACATGCTGTAAGCCGGTAAGTCGGA

          GGTGTTCGGTTGGAGTACCTAGTATAAAATACGAATCAGTTGCATACGGCACCTTAAATG
          GGGGTTAGGCTAGAGTACCCACTATACAATGCGAATCAGTTGCTTGTGGCGTACTCAATG
          GAGGTTTACTCAAAGTACCCACTGTAGTCCGTGGACGGCTATCGCGCGCCCGACCAGAAG
          TTGGAGCGACTATGGCTTTCAATACAGGAGATGTCTCGGTTCCACGCGGGAAATAGGTTG
          AGAGTCCTTTTCCCGCAGTATCAACAGCAGGTATAATTCTTTGATGGAGTTCCTTCGTTA
          AGTGCTTTCGTTTAGTAGCTCCACCAGCGGGAACAATCCTTTGGAGTAATTCCTTAGGCG
          TCTGTTCTGGTCTAGAGTATGACGACGGAGAGTAATAACTCCGGCGAAGTATTTTGGTCT
          CTTCTTTTGACCTAGGATGCGACGATGAAGAAAAATGGTTCCATCAAGGTATCCCGGTCG

          GAAACGCCACATGGTTTCAAACGTGGAGACTACAGTCTCACTCGGCAATCGATAAGAATC
          GAAACCCAATAAGGCCTCGAACGTGGCTGCTACAGTTTCTTTCGGGAAAGGGAAAGAATC
          GCTAGCCGATGGGTCTCTTAACGTCTAATTCGCACACACACCTGCGATCGGGCGGGAAGT
          GCCACCTAATTGGGGCCAGTCCGCCTAATTAACACTACCACCTGAGACTTGTTGGTAGCT
          TTATTCTATTGTCAGTTTATACGCCAGCCAACTAGCTTGGCTTCGGCCTACACCCTCTGT
          TTCTGCTACATTTAGTTTTCATGTTTGCTAGACAGTCTGTCCCCGGACTGAGCCCTATGT
          TTGTTGCAAGTCCAGGTATTGAGTACGGAACTCACGCTCGATCAGCGTATTGAGCCAGAA
          TCGTAGCAAGTGCAGACATGTGGTATGGGACTTACACGAGTTCGGCGCAGTGTAATAAAG

          CAAGCTAGCTCTGTGAGGGAGCCCCCTGACGACTGGAGTTAAAACCACATTTTGGATGAG
          GAATTCAGCTCTGCTGGGGAGCGTTGCGGAGATTGGAATTGCAAACTCATACTTGTTGAG
          AGGCTCGGCTTCGCAGGCATGGCTTTGGTAGAGCAATAATCCACAAGTCCCTCAATAAGA
          GAAAAAGCGTACGTCGGTCATCTCTTGGACGACAGCTTTATTGCGTGCATACTAGTGCAG
          CGATCCGCTTACATAGATCAACTAAGGTGGATGGGGGACACAATGGCGATCTAAGGTTGA
          CAGTTCGCTTATGCAGGACACTAGTTGTGGATCGGACATACCTAGCTAAGCTCAGGCTCA
          GGGTTTGAAGGCTATGGTTGTATACTGAAACGGGGAGTGTACGAACAGGTTCCAATACCA
          AAATCGGACAGCTTTGGTTGTCAACCGGAAGGGGGAGCAGACGGTCAGGTTGTATTACTC

          ATGGAGAGTCTATTCACTAGAGTCATATCACCATAATTTTTCTGGCACTGAGGCTCACAT
          TTGGGAAGTCTACTCACTCGAGTCATAATACAATTCTTTTCTTGGTACTGGCGAACACAT
          ATAGAAAGCACCATTGTATGGGTCCTTTAACCGCTATGTCTCCGGCCTTATGCGGCATAA
          ACCCAAAACCTTCCCACATAGGCTAGCCGGTCACTATCTCTGGGGATCTGTTTTGCAACT
          CCCAACCTCCGACCCGCCTGGATCTATCCACTCATAACAATTGCAAGCTAACCTATTCAG
          CCTGTCGTTCTACCTGCTTGTATATGCTGATGTATAAAAATACCGAGCTAGTCCACCTAG
          CCGGTTCCCCCTGCCAATTGGCTCGGTCCACTTGTAGTCCACGTTTATCATTCAGGGTAA
          TTGGGTCTCTCGTCCAATTGCTCCACTCTACATGTAATGCCACACTACCACTCAGGGCGA

          TGAGGTTCCAGATCCCTGTTCCGCCCGTTTCAACCGACAGCGGGAGTTCGGGCAGAAAGA
          TGCGGTACCAGACTCCTCATACGCCAGTCTCGACAGCCAACGGGAGTGAGGTCGGGAAGT
          TGAGGTCCTCAACACCGTATCCGCGTGTAACAATGGATAGTAAGCGTCCAGTTGGTGAAT
          TGGATTTGTCAACCGCCCTATGTCCCGATAGGATAAATCGTGTCAACCTGGGCTGTTGGC
          TCTGGACTTCGGGTTTTTAGAGAACCAAAAGTATAGATTGGGAAAAACTAACTCGTCTCT
          ACCGGCATTCGGCTCCTAAGTGAGCTGACACCACAGATTGAGCAGATCCACCTCGTCCCT
          CCGAGGTCGTCATACAAAAACCGTCTGTTCGATCATGACGCAAAGGCTGTAATAGGTTAG
          CTAGCGTTGCCACACCAAAATGGTCAGCCTGATCACGCCGGCGGGTCTGCAATACGTTGG

          TCTAAGCTCAATGATAGCTCCGAGTAAGCTCTTATTGGTTGGGTATTCCAAAGACATCGT
          TCTAAACCCAATGTTAGCCCAGAGCAAGATCCCACTGGTTAGGTATTCCAAAGACACTGT
          ATAATTGGAGAAGTAGGACTCGAGCCAAATTTTAACCATTGGGTGTCCCAACGATTCTGA
          CCGACTCCAGCCTTAGGGCCATGGACGGGGATTATTTGGGTTGTGCTCACACGTGCACGC
          AAGCGGTGAGCCGACAGAATGGAACCACAAGCCGTTCGGTTAGTGAACGCCCAATGTCTG
          CAGTGGTGTGCCACTCAACTTGATCCGTAAGACGCTATATTAGTAAACTCCCCATCACTA
          TTTTTGTGAAGAATGAAATATAGAAAGTGGAATACCGGAAGGGGAAAACCCTAAGAACAC
          CCTTCATGGTGAGTGATGCATAGGGAGTCGAGCATCCGCAGACGGAAACCCTCAGAATAT

          TCGTCGCCGGTGTCATGTGTTAGACGTACCGCGTTAGGTCCAGCATAAAGGTAATATTTC
          TCGTAATCCGTGTTAAGTGTTAGATGGACCGTGCTTGGTCCAGTGTCAAGGCGAAATATC
          CTTCAGCTCGCGTCATGTAATTGGTGTATTGCGCTCTAATGACTACGAGACCGTTATACC
          CAGGAATCGAAGCTATATGGTAAGAGTAGTTTGCCATCGCCAGCGTAGAGTTTGTCACGG
          TTATGCTGGACCTGAGATCGAGAAGACCCTGTAGTGATCTGAAACAGGAGGTAGTAATTA
          CTCCGACGGACGTGAGATCGCAGGGACTTTATTGTGGTTCGGTATAGGGGATTACATGCA
          GGGGAAGTGGGACTAGACAGCGGCGCTACTGGTGGACCAGAAGGGTAGCATGTGGTCGAT
          CGGGGAATTGGATACTGGAGTGAAGCCTTTACCGGACGGCAAGGGCAGCATCAGTCCGCT

          CTTAGACTCCGGTAGCACGGTTGAAAGTCGCGGGACTCGACTGTTCGCCTTTTTCGAATC
          CCTAGACCCCCGTAGTACGGGCGCAAGTCGCAGGATTCAAATATTCGTCTTTTCCAAATC
          ACTAAGACATGGCAATGTTCGCACTAGTTGCAGGCTCTGGCCATGCGCCACAAACCGTCA
          CCTACAACTCGAAATTGAGACCTAGGGTTACAAACCTAGACCGTGCGTCCTGCCAACAGT
          TGTGGCATGGCCTACCGGCGACTCTTGCGTTAGACCCCGCAAAACGTGCACGTACGGACT
          TGTGGCTCGTCGAACTGGCGGCTCCCGAGCTAGAGCCGGGAGGATGAACACACTCGGATT
          TTAATCACGGAGCGCCGAGGCTTAGCGACCTGTCCTCCGTGAATGGAATGTCGAGTAACC
          TCTGGCAGGCAGTGTCGAGACCCGACGTCACACCCCAGATGTATGGATTGCCAAGAAAGC

          ATCTAGACCACTTGAAGGTGCATCAGTCTTCGCTCGGCGCCAATAGAGTCTCTCAGCCGA
          ATCTATGCTAATTTTAGGCGCATTAGTCCCTAAGCGGAGCAAACAAAATCTCAAAGCCGA
          GTTTGTGGGCTATTGAAGTGTATTAATTTACAGCCGGAATCAGCTTATCCGTCACTCCCC
          AACTAGACGTTAGTTGGGTGCATCGGTCTTCGATAGGAAGTAAACAATTCGCGTTGTTAC
          GGAGCCGAGCCGTTCCGTTCACCTCGCTCCTTAATCTGTTTGAAACACCCCAAGTCCTAG
          GAGAAAGAGCTCCTCAGTTGGTCCCGTTGCTTAACGACTCGAAAGTATCCAAAGTCTTAT
          GTTCGAGCCCAACAACAGGTTGGCTGATTGAGCTACCAATTAATCAACTGACGTCTAATC
          GTTAGGGAGCAGCGAAAGTCCGGCTGGTTGAGACCTCAATTGGTCGATGGACATCCACTC

          CAATATTGAAAGGATACTCGAATGGTACGGAACGGTACCGACTGCCCTGGGATTGTTAGG
          AAATGTTGAAATGATACTCGGTTGGTAAGAAACGGAACCTATCGGCCTGGGGTTGTTAGG
          AGTTTCTGAAAGGGGGCTGGGGAGGTTATTAATCGTTGCTATTGACCAGTGGTACGCATC
          ATCCCTTGGACGGGATAGGGAGGGAACTTTCACAGTCCCCGCGCCAGGGAGATAGGTCTG
          TTTCGCTTTCAGTCCGTTCGCATAGCTTGTCGTTCCATTTGTTGAAGAAGAGGAGGTGAG
          AGTCGTCTTTAAAGCAAGCATTGAGTTCCTAGAAACAATAGTCGAATATTAGGAGGTGCG
          GGTCGTGGAGCGGTTGTTGTGGTGCTTAACGCCTTGGTTTACAAGTTGGTTACCAGCTAG
          CTTCGTGGTGGAATAACATTGGTGTTTAAAAACCGGGTCTACTAGTCGGAGAGCTGTTAG

          TGTAGATTGCAGAGGGGCCGGAGCAGTCTAACTGGGAAACTTTTTGCTATCCACCTACTC
          TGTTGACTGCGGAGGGGCCGTGGCAGTTTTAGCGCGCGCCTTTATTGTACAGATCTGCCC
          CGTCTAACGGAAGTGGAGCCTGTCAGTCAACCCGCGAATCTCTCATGCAAGCGTTCACCT
          AACGGGTTTAGACAAAACTCAGTCCGGCGATTTTCGATCCTCTTCGGGGACCATCTACGG
          AACGACCTTGGAGGTTCAATAAAATCATAGGACCTGATCTCTAGCGCTGACCGTCAATTT
          CATGCCGTGGGCGGTTCATTCAAGCGCTTAGGTCTGATTTCCCGCGCTGGCTGTCGACTT
          AATGAGGTTGGGACAAATCCCGTCTTCCTGTTACGGAGCTCCATGGCATGACACCAGACG
          AGTGAGATTATGGCGGATTTCGTCTCCCCACTCATGAAATCCCCGGCACGCTATCCGCCG

          ATAGCTTTAGAGCATGCAACCCTTCGTGCTCCACCTGAATTTGCGCCGTGAGTATGATAA
          TTAGCTTTAGAATATGTAGCCCTTCGCGCTCAATCTGGGTTTAAGACGCAAGTATGCTAA
          CCAGTTTTGAGACTCATGGAGTACTGCGGTGGAAAGGTATGCGTGCCGAGTAAAGATTCG
          CCACCTCTAATCCTTCTAATATCCAGAGTCTGATATGAATAGCCGTCATGACGCCGGTAG
          TCCGGCCGAAAAGTGCTATAAATAACCGATAGGAAAGTCCGACGGCTGCTCTGGGGGCGT
          CCGGGACGGGAAGCATAACAACTAATCTATAGAAAAGCCAGATGGCTATCAGGAAGACCT
          ATTGATCCTGAGCACGTAAGAATTTAAGCCAACTAGGTTCCAGAGTTCCGAGGATGCTGC
          GTCGATCCTAAGTATACATGACATTACGTTAGCTAAGTTCCGGGGTCCGGAGGGTTCAGC

          GGGCGCATTTAACCGCTAGCAACGCGATGCTTTGCCTCCTCCCCTGATGAGTCCCAGGGA
          GGCCGTGTTTAACTGCTAGTGTCGTGAAGTTCTGCATACTCCTCCTATGTGTTCCAGGGA
          GACACAGCGCTCCCGCTTTGTCCACGATACGTTGCCCGCTATTATTGTCGGCCCAACTGC
          GAAAGGTAGGCGCCGATCTGATCCAGGAAGACAGACAGTGATTTTTGCAGATTTGGCAGA
          AACTAACTTTCAAGGCTATATACTAGCTACCCATATTGTCTTGGTTGTTGAAATGGTGCT
          AACTCATTCTCAGGGCTATGTACTAACCCCCAGTGTTGTTCTGAACGTAGAAATGATACG
          AGAAGCTCGTTCGTAATGCAGCCCCAACATGTATTCGGACAAATGAGAGGAATGAGAATA
          AACAGCCAATTAGAAGTGCTGCTCGAGTAATTATTTGGATACATAAGAGTAACGATAGTA

          TCGTGAGTTACCCTCTGGTAGGCTAGTTTGGGATGTGCCGAAAACAGTTTCCTAATTAAG
          TTGTGAGTTACTAGCTGGGAAGTTAGTCTGAGCCGTGTCGAAAACAGTATCCCAATCGAG
          ACGTAAGTTGCCTCATCAGCGGTCACCATGGTTCGCGCTAGAAAGCATTACGCAATCCAA
          TTGTGAGATGCCTCGGTAGTCGTGGTCCTTTACGGAGTCGAGAGGTAAAGTGGAGGCTAG
          CCAGGATCAAGTGACTTGATAGAGTCCGGGGCTTCACTTGGGAAGAGTTCTATTAACGTC
          CCGTGAAGCAGTGAATTGATAGAGCTCAGGGGATCGCCTGGGAAGCGTTCCGTTAGCCTG
          TTTCAGGTCTTTTCAGGAGCCGTAAGAATGGGCACACCCGCGTAGCGCCTTACAGTGCAC
          CCTTCGACCACCTGAAAGATTGTAGGAACGGGGAAATGCGTGCAGTGCACTATTATGCAC

          TGGGGATAAGACCATCAGCTGCTGCCGACGATTTAGTGAAATTATGGTCAGTATATCATT
          CTAAGGAAAGACTCTCAGCTGCTGACGACGGTCTTATGAAACTATGGTCAGTTCATTATT
          TATGGGCCACCTTACCACCAGCTACCCATTGGACGATAGGAATTTGATTTATACACTAAT
          CTCGGATGACGTTGATATTTGGGGACCATGTGGAGATACGTGTAAGTTCGTAAGCTCAAA
          TATAGGTTGTGCTAATTTTATGAAGTCGCATTCATTGCGCGCGAAAGCCGCTTACGTCTT
          TCTATTTTGGTACAACTTTATTTTGTTGGTAAAGCCGCGTGAGTAAGACGGTAGCGTTTT
          CTAAGATGCCTCTATTCCCCTGTAATCACGTCAAAATCAAGAGACGTTCACTAGGGCATA
          CTAGGGCGCCTTTGATCTCCTATGACGACGTCGCGAATGAATGTCCTTCACCAGGACATA

          AGGTGATAATCTACGCGCAACCCATGGGCGCGGAACATGA
          CAGAAAATACCTCCGTGTAACGCATGATTGCACAACATGA
          GAGACAGCCCTAGGGCCAAATCTAAGGCCGCGCACAACGA
          AAGTCGGCGTCAAGGACAGGTCTAATCGAATGCTCTGTAA
          AGAGTTAAGCCGACAGCCGAAACGCCGCTGAGGACAGCTA
          AGAGCCATCTAGGCGACCGAAACGCAGCGACGGATCGTTA
          TGGCAGGTGCGAGTTACCGACTGAAGGGCACGAATCGCTA
          CAGTTGGCATCACTGACTGACCTTAGAGCATGAATCGCTA

