 8 1000
t1        GTCCTGGGATAGAACGCCCTCGGGAGGTGTGTTGGATATGACCAGTCTCTGCACAAAGTT
t2        GAACCGGGGGCGTGCTGGGCAGGGCAGCATATCGACCATGACTAGATTGCGCAATCGGCA
t3        GGGCCGAAACCGCGCTCCGCTCGGTCTGGGACCAGCTTGGAGTCTATTGGCGACCAACTG
t4        GGGTAGACACCGCACTTCGCGCAGCCTGGCGACAGTACAGTGTTCACGGCTGGCCGGCCG
t5        TCGTCAATAACACCTGGTAAATCGTCCCCATACAGGGTGAGTAAACCTGTTCAACCATGA
t6        TCGTCAATAGCATCTGGTAAATCGTCCACAGATAGGGTGGGCAAACCTGTTCGACTATGA
t7        CTGCGTGATAAGTGCCCGACTTGGTACCGTACCGCGGTAACTGAGAAAGAGCACCAATAC
t8        GCCTTGGAATGGAATCTGACGCGGCATTGGAACGTGATATAGTAAGAATTAGCTCAGGTT

          TGTGAGGTGTTGCCGCAGCGCTGTGGAGGGATCTATACTGAGATCAATTGGACCCCCTAA
          TGGCAGACGTTTTCTGAACATCGGAGCGTAACCAATCCTCGGATCCCTAACCCCTCACGT
          CGTCAACCTCGCCCCGTCACTTAAAACCGATGCGTCCCACGGGCTTGTCGGGACCCTCAG
          TGTTGGTCTTGTCTTGTCACTCAGATACGAAGTGTCTCTCGGGCCTATAGGACACCCTAG
          CGTAAAATACCTTTAATGTGTCAGCAAAAGTTCAGTGATTTAGTCGGGAGAATAGCGTAA
          TGTAAAATACCTTTAATGTCTCAGCAAAAGTTCAGTAATCAAGTCTGGAGGATAGCGTAG
          GGCGAATCCTTCCTCCTAGGATCCGGTTATACGAATATATAGGCCGATGGGATCGCAGAG
          CTTGAATCACCGTTTGTAAGCTCGGGATTGTATATACCACGGATCTATCAGATTTCAGGA

          TAGGATCGTATCGAGAGCCGTAACAACGCTTCCCAAATCGTTTCGTATACCTGGGGCATA
          TAGAATGGCCTCGAAGGCTGCAACAACGCTCCCGAAGCTGTACCCCGTAACAGGGGTTTT
          GCACCGGCTCGGAAATGGACCAATGGCTTTTTCAGTGTTGTTAGCGGCTGATACTGTTTG
          TGAAGCGTTCAGAACGGGACCAACAAATTCTCAAGAGTTGCTATGGGCTAATATAGTATG
          CCATCCGAGTCAAAAGGTTTCTCTTGCACTCCTAGGTTCTATACCGTGAAAATGTGCCTG
          CTGTCCGAATCAAAAGGTTTCTCTTGCACTTTTAGGTTTTATACCGTGAAAATGAGCCTG
          TTATACGATTGTTTCAGCGAGGCACAAATTCGGGTGGTCGTCTATACATATTTAAACGTC
          CTGGATGATTTACCAGGTTTGGTTCAAGCTTAAGAAGTTGCTACATGTAGTTCCGCCATT

          CAGGCAGGCAAGGGAGCAGCGTCGCGAATGGTGACGCGCCTGCGTCGAGTTAGTCATCTT
          CGCCGAGGCAGCCGGGCAGTGTGGCGAATGGTGGCGTACCTTTTTGAGGCTAACAAATTT
          TACTGAACTACGGTGACGGCATCTCTGACTGTCGCGTCCCGCCACGCATCCGCTGTATCC
          TTATGAGCTACGGTAACGCAGCACCACATTGTTACGTCCTGCTGTGCAGCCGCTATCGCC
          TCCGGTCACATGATCGCGACGTCACCACTTAATGTGGCTAGCTTAGACAATATTATGGTA
          TACGCCCGTATGACCGCGACGTTACCACTCGAGGTAGTTAGTTTAGACAATATTATGGTA
          TATGATCGCGAGTTAGAGAAACGATTTGTCGAAGTACCAAGATATGGCGATTGGCAGCCA
          ATCGAAGGTAAGCTAGAGAAGTAAGCAATGGGATTGACCTGTCGCCGTAACGAATGCTAC

          ATTGACTAAACCGGTCGAAACTGACGTGACCTGTAATGTACAGTGGATGAATTATATCCA
          AGAGATTAGATTATTTAGGTGAGCCGGATCCTGGCCGGAACCGTGTAGGCGTCACGACCC
          GTATAGGACGAAATAGCAAGTGGTCAACATTCGAAGCGTCCTACTAGAAAGCAATGTTCA
          GTCCAGGAAAGGGTTGTAGATGGTCGATACTCAGCGTATCCTATTAGAAACTGATGCATA
          GTGGGTGCCGCTCATGGGAGGAATCGCCATTCCGTATGACTTCATACAAAAGACTGTCCT
          GTGGGTGCCGCTCATGGGAGAAATCGCCATTCCGTATGACCTAATAGGAAAGAGCGTCCT
          ACAGCCACGAAAGGCAAGTCTTATTGCAGCCCCGTGGGTCCCAATACAATAGACCAATCG
          GCAGTTAAGGTTCGTAAGATTTGTTAGTGGCAATGTCCTTCCTTCGCACCCGAACGGATA

          CGTCTCCCTGGTGCCGTTGGTGAGCGGCCCATACAGTGGTTAGAGAGAAGTGAAAGTGTG
          CGTTTTGCTGGTATCGCTGAAAATTAATTCATCAGGTAACCGGAGTGAGATGTAGAATCG
          AGGCTCACCAGGATTCCCGGCAGGCGCAGCATATCCGGGTCCGTATACGATTCCCACCTG
          AGGCTTTCAAGGCTTCCCGAAGGATGCAGCATATGCGGCCCTGCAAACGATATTGATCTG
          GGACATAGTTGCGGCCCGCGTCATCGGCTACGCTATAGATGATAATAACCTCCGAGTTTA
          GGACACTGTCACGGCCGGCGTCATCAACTACGCCATAGACGATAACAACCTCCTCCTTTA
          TGGTACGTGTACCCGGTGCAAGACTGGTCTAATAGGCAGCTTGAACACCTTTTACGCTCA
          TGGCTTAGTCGCCGCCTGTTGGATCCGGCCACCGAATGGCTTGGGCATACCAAGGGTTAG

          TCACCGCCATAAAGCTTCGTCGTCGATGGGCCGTTCGGTCTCGTATTCGGCCTCTGAGCA
          CCACCGTCGGAATACTTTTTCGACGATTTGCTGTACAACCCCGTATTTGGCCTTTAAGAG
          CTATTGGTGAAAAATTCACTCTTCCAAAGACAGTGTGCGCATTTATGAAGGTGTCAGATG
          TCATTGGTGGGAAACTCTTTTGGATGCAGGCTGCGTGCGCCTCTATGTGATTCATGGGCC
          ACGCATTGGAGAGAAGTTCTCACCGACGCTACGGGCTGAGCACCCCCGGGGCTAGAGGCC
          GCGCATTGGAGAGAAGTTTTCATCGCCGCTACGGGTCTAGCACCCTAGGAGCCGAAGGCG
          ATCTAGCTGGTACCGACCGTCGTAACAGGCACTGAGGGACCTGTATACCATTTGTAGACG
          ACGTTAACAACAGCTATTCCGGTGGCGGTTCCTAGTCAGATCGCAGCCGGTTCGCAACCA

          ATCCACACTCCTTAGTTTCGAGAGGTATTCCTACGCTAGTCCACCAGTCCAGGTGTATGC
          ATCTATTTTCCCTCGATACGAACACCGATACTGCACTGCTTCACTCGGTAGTATGGACGT
          CCGTACTTAACTAGGTAGCGCAGCCATCTATTGCAGAAAACACTGAGATTCCTCCTGAAT
          TGGAATCTGTCTCGGTTTTGCGACCTGCCCCTGCAGAAAGCATTAAGGCCACCCCCGGGC
          TTCATTGGCCTGTTGTTAGAGGAACAGTACCGGTTACAGGATCAGGGGTTATGAGTTTGG
          TTCATTGGTCTGTTGTTAGAGGAACAGTACCGGTTACTAGGTCAGGGGTTATGAGTTTGG
          TACGATGTCCTGTGACCACGTCACCATTCCCAGCCCTAAGTCATTCAATCGAATGCGTGC
          TCTGTCAACATGTCGTCCTGGTGCCCGACTCGGCCGCGTTTGCTGAGGTCATGAGTCGGC

          TTAGGATTCAAAACCGAGTTCGTTTGAGCTTCACCACTGGTGAGTCTGTTTGCTCTGTGC
          CTAGGGATCATATGCGCGCTCGTTCGAATACGATAATAGGGGATTCTATATGTCGGGTAA
          TACATACCTGGGGGGGGATTCGTCTGACCCTTGTCCTTGGAGCCCCAACACGGTCCGTAC
          AGTTTGATCGAGCGTGAGTCTGACTGAGTATTATCCTCGAAATTCTAACACGCTGCACCC
          AAACGTCCCGGTTGGGCAGCCAACTACCAAGCGCTCCTATGCTAGGACCATCGTTCGCCG
          AAACGTCACGGTTAGGCAACCAACCACCAAGCGTACCTATGCTAGGACCATCGTTCACCG
          AGCCTCGTTGACCCGCTGCCTGCAACGTATCCCTTACCAGGGCTCAAGCGCCTTAAGGGT
          CGCAGTGTCTCCCACAAGCCAGTCGTAATGTTATTCTCAGACGACAGAGGTCCCATGCTT

          GACTAGCGGACAATGAGTAGGCGGCGCGACGCATGGATTTCCACAAGCAATGATCATAAA
          GATCGGGAGCCACTGACCAGGAGGCTGGACGTACGGACACTCACAAGTAGTCTTCAAAAG
          GTCTGAGATGCGGCTGATAGCTAGTTTGCCATTTTCCTTGCACAAGGTACTTTATGTTAG
          GACAGAGGTGCGGTCGACGGCGTGTTAGCCCCGTCTCTCACATATTTCAGGAGGCATAAG
          AGATCGGGCGCGAGTTCCGCGACACCTAGTACGTTATCCGGAACCACCGATACTAATGAG
          CATTCGGGCACGAGTTTCGCGACACTTAGCACGTTATCCGGAAACACCGATATTCATGAG
          GGTATGTGCTGGGTCCATGAAGCGGGTGCTTAACCGTGAGTACAGCTCCGCCCTCTCGTA
          GCAAAGAGCAGGCCCCACGGGGCACCCCAACCAGGTAGCGTCCGGTTTTGTCTTCTCAAT

          AGATCCGCCAGAGGACCATATCAGCTTTGCGGCCGAAGTCGCACACTCGTCCAATCAGTA
          GTTTCAGCCGGAGACTTTTCACAGCTCCGAGCCCGAGTTTTGGTATCCTCTTGATCCGGA
          CGATGCGCTATTCAGCGACTCACGGTATGAAATTATAGGCGTGCGCTCCTTCGTACAGAT
          CGGTGGGCTATACACTGGCTTATTTTCTGCGGTTATAGACTTTTGCTCCTCTGTCGCTCT
          TAGAGCGCTACGGTAGGATTTGCACGAGTTGACCCATGACCGCCGTGTTCACTCCCAGGA
          TAGAGCGTTGCGGTAGGATTTGCATGAACTGACCCATGATCGCCGCGTTTACTCCCAGGA
          AGACGTTCAGAAGGCACCCGACTGGCACATAGTTTAATTTCTCCGCCTATTCGGTCACGA
          AGGCACATAGTACATCTAGGACTGCGACTACACCGGGGGTACCTGCCGGTCCGTTTTCGC

          CTACATTACCTCCAAGATGCCTAGGCTGCATGATAATCCTCACGATAAGCAGTTGGGAGA
          TATCGTCCTGTCCAAGAGGTACATGCCGCGTGTATCTCCGCACGATCAGCTATTGAGGGA
          AATTTCCGTGTACGTGTTAGATGCACGCGGTGCCGCTTGAGTTCATGAAACATCAAGTAC
          AATTGTAGTGTTCGGGTCGACTACGCAGGTTGCTATTTCAGTCTGCGAAATGCTAGACAT
          TGCAGTGACGAGCGTTCTGAGTAAAATACGGTTGCTAAGGGCAGATAAGGGGATAAAAAG
          TGCAGCGACGAGCGCTCTGAGTATAATACGGTTGCTCAGGGCAGATAAGGAGATAAATAG
          CACCTGGGTAGATCAGTTGAACTAGCTAGGAACGCCTGGGGCCACCTGGGAGGTGGAATG
          TTATATCGCGGATGAGTTGACTCCGGTGTGGTTCGCTGCGGCCGATACGGAGGTGCACGA

          CTATGCAGTGGATCAAGAAATAAGCTAGGAGCGCAAATATGGAATGAATCGGCTAGGGAA
          GTCTACAACATGTCGAGAGATAAACTTATATCACGGATATGGAAAGCACATCTCCGGGCA
          TACTCTAGGGTGGTCGGACTCGTGTCTGTGGTGTACAGACACGTCCACAGCCCCTCGGGT
          TGTTTACGAGGGGTTGGACTTGTGCTTGTTGTGTAGAGACAAGCCCGCTACGTCTCGGCC
          TAATGTGTGGGAATAGGCACCAAAACGCCATCGAAGAGGTGCGGGAAACTTGACAGAGAT
          CAATGTATGGGAATAGGCACCAAATAGCCATCGAAGAGGTGCGGGAAAATTGACAGAGAT
          CCAGTTAAAGAATCCAGAGTCGGGCCAAATTCGTAGAAATGTGGTATTTTCTATTGGGTA
          TTACAGAGAGGACTAGGAGTTAAACAGACATCTCCCAAGCCCAGGGCTTCTTGTAGAGCA

          TCTCGGAGTTGTCATATTCCATAGTACCTGGCCGTACGACCCAATATACAAGAGATTGAG
          CTCCTGGGCTGCCACATCCCATAGATCCCGGCTGTACGACCTGATAAACGAGTGTACGGC
          GCTCTGGATATCCAAAAACCGCCCACTGCCTCCCTCCTACTGTAGACCCAGGAGAGCGAT
          GCGTTGGGTGCCCATCATCGGCACATTATTTCTCTCGTACGTAAGACCCAGGAGAGTAGT
          ATGCAAGGTCCTCGTTTCCCGCGTAACAAAACGGCTGGGCGGCGCCTACGGACGGGTTAT
          ACGGAAGGTCCTCGTCTCCCGCGTAACAAAACGGCTGAGGGGCGTCTGCGGACGGGTTAT
          TTCAAGTATTCCACGAACTTATGCAACTGCGCAGATTGATATTGCGTCGGGTTAAGTCAT
          TTAAAAGTTGCTATGCTTGATCGATCCGTCACTGCATAACGATGCGTGTGGGAGGGCTAA

          CTGTGTTGTTGAAGATCGCGCCACTTGGGTCTAGGTTTTGGGGGCGAATAGATAGTATCC
          CAGTACTACCGGGGGTTGCGTAACTTTGGTCAGGGATTTGCCGGCGGGGTAACGCCGGGT
          TTGTGTACAGAGGTAATGCGCCAATTGAAAGTAAATCCTGTTATCAGGCCGAAGCCATTT
          TTATGCAGGGATCCCAAGCTATACTTGAACATACACCATGTCATTGGACTAGCAATATTC
          GCGTCTGGTCAGTCGCCGCGACTGGTGATAAAACACCCTCGTTATGTGTTTACACAGCCC
          GTGTCTGGTAAGCCGCCGCCACTGGTGATAAAAAATCCTTGTTATGTGTTTACATAGCCC
          TTCCCTCTACAATTGTCACGTTTGTCTGGTGAACACCCAGGTCGGAGGTATATGTTTTAA
          TCACGAGTGCGACAGCTACGTTATTGAACCGATGGTCTAGGCAAGAAGTCTGTAATGCCG

          ACCCGCTTTGATAGCTTAAGATTGTCAGACCTTAAGTTCAATGACAATTACGACGACATC
          GTTCGGCCGATCAACTTAAGGTTGTCTGACTATATGAGAATTGGCTCCCTCTGGGCCCCC
          GTCTGGTTACCTAAATCTAAGCTAGATGTCTATGGGAACAGCAGCGATAACGGCGCCTTT
          GTCTTGTCAGCTAACTCAAGGCTGGTTGATTATGGGTGCAGCATCTGTAACAGCGTCTTC
          GTCGCCCGAATTATCCTAAGCTAGATGCCCCGGTGGTGCATAACAGTTCCTGAGGACACC
          ATAGCCTGAATTATCCTAAGCTAGATGCCCCGGTGGTGCATAACAGTTCGTGAGGATACC
          GCTTATTTTGTCAGCTTCAGCCGGGAGACCTGCACGCGAAATGCCGACTCGGAAGTCGCT
          AGAGTCTATAATCACCCAACACTGGTAATCTATGATCGAAACGCAGGCCCGGAATCCGTC

          TCACGAGACGGACAATATGTGATATTCGAAGCGCAATGGA
          AGACGAAGAAGGTCGTAGGACATAACTCACATTCGATGCA
          AAACGAAGAGGACCAAAGATGGTAACGCGCACCATATGGA
          AGACGGAGACGACCGGAGAAAGTGACGCGTAGGGAATGGA
          GGCCGAGAAGAGATATGGGCGGCAGCTTGCTCGTAGAAGC
          GAACGAGACGAGATAAGGGCGGCAGCTAGCTCATAGGAGT
          GGGGGGAGAAGGACATGGGCTGGACTATGCGATGGGATGT
          GGGAGGAACCAGGCGTGGGTCAAGTTCCACTCCAAATTGA

