 8 1000
t1        GCGTATACCCCCTTGTTTAGTTGCGCAATTGTGTTGGCGCTGCGGCAGGTTGTTCCCCAT
t2        GTAATTAGCGCCATGCTAAGTTCCGCTCTTGCGCTGGTCAGATGACTGAACGTTCACCAT
t3        GCCTCTGACATTTGCAATAGACGGATCATCGTAGTCGTCACTTGACTCAGTTCCTGGTCC
t4        GCTTTCTACATTTGCGTCGGACAGGCCATAGTAATCATCATATGGCCGACCTCTTGGTAC
t5        GTCTTCACCGCTGTAATAGCTTAGTTACGTACAATAGCCTCTAGACCCCTGCTCGGGCTC
t6        ATACAAACCAACACTTCAGTCAATCTGGTAAATACGTCTATCAGATCCTCGAGATGGCGC
t7        GTCCTCACCAATAGTGGGCCTCACAACAAGGATTTGGTTCTCAGATTGAAAATCCGGCAA
t8        TTACTGATCGACAGGGAGCTTGTTTTGAATTTGTTCGAGCCCCGGCTCCAGGCCCAGCAT

          GCTTATGCTGTACAATTTGGATGATACCTGCGCGGTCAATCAGTTCTCGTAGGTCGAAGC
          ACTTAAGTCGATCAATTACGATGTTAGCCGGGATGTTTAATGGCTCTCGTACGCGGCAGT
          AAAGATCTCCCCTCTCCGTAACGAAAGTCTAAGTTCCTTGGCGGTAGTACTTTGCACGAT
          AGCGTTTCCCTTTTTTGCTGACGAGAGCTCAAACTCCTTGCCACTAGCACTCTGTGTGGC
          AAGGCCTTCGTACTCAGTCGTTGCATGGCCCAATCCATTATAGCACGAAGTCTAAATGAT
          GAAGTAAATGATCCTTGCCCTCGCGAATTTTAGCCCGGCACAGGGCTATATCCAAGTGGT
          AGTTTACTTCATCTGTTCTACCGTCTGCTTGCACACCGAGTGATAGTACCTACATGATAA
          CACGTGTTCGTCCTCTTCCTCCGCGGAGCCAACGTCCGAGAGGAGCCGACATCCTGTGGC

          GTGTTATCTGATTTATCTCGGTTCATATGCGTAAAATCTACAATCTGGGCACAGTCCACG
          ATGTAATTCGTCTAACCTCGGTTTTGACACGCAAAACCTACACCCTGGGGGCAGTCGATA
          ATGCAGTTTACTAAGCGCAAACTCCGAGAAGAGTATCGTCCCGTCGGGAACAGGGTCACA
          ATGCAGTTTTCAAGGCATAAACTTCGAGCCGCGCGCTTCCCCGTAGAGAACCGAGCTATG
          GCGCAGAGTTGTCGACTTTTCCCCGAAGGCCAATGTCCCCATGCCTGGCCGTGGCAGGCA
          GCTTGAAGCCGCCAAACCAGACTCTTATTTTGAATCACCCCTCATTAGCCTTGGCGGTCA
          AAGTGGACTACCTAGTGCAAGGCCGAATATTGTTACGTCACAAAAAGGCTGAGGTCCGCG
          ACGTCGGCCCATTAGCGCAGTATCGAGTCGGAAGACGTCATGGGGAAAAAGCCCTGAGCA

          CTTCCTCAGGAATCGGGTAGTCGTAGTCTCCGCCCCTCGCGAAGCGCCATACTTCCCGAC
          ATTCATAGAGAGCCGTTTAGCCGTAGTTTTCGCCCCCAGCGTGGTGCTATACCGCTTGAT
          AGGCAGCCCATTGCTGAAGATCACGGGAATGGTTCACTCTTTGACGCAGTAAGCTCACTC
          ATTCGCCCTTTTATTATAAATTCCGCGAATAGGCACTCCTTCAGTGTGATGAGCCCTATC
          ATCACTTACGCCTCTCGAATGCATGAGGTGTTGATAGAGTAGAATATAGGAACACTCACG
          GCACTTTACGCGTATCGATTTCTTCAGAAGTCGAAACAGCGGAGAAAGATAAGCTCCAGG
          ACCTTCCAATCCAAATAGTACTCTGGGCTGACTACCCTGAGGGGCATGGTGAATATTGAG
          ACCTCCATACCTTCCACATCTTATCGGACGAGGACATCGGGAAGCGCGATGAATGCTGAC

          TGCAGTTACATTAGTGAGATTGCCCTTTGCCATGCTGCATGAGAGTCCACACGCCGCAGA
          ACGAGTTGCGTTAGTGAGGCTTCTTGTTGTCCTGTTGTGTAAGCGCTCACACGCTGCAGA
          GAAGTCTTCGATATGAATGCCGTTTTTTGTGAGGGGATGTAGTGACTTCTTTATGGTCGA
          GTAGTCCTCGTTTTAAATACCATTCTGTGTACAGAGACAGGATGACTGCTTTGGGATCGA
          AACGTACATGTCCATAAGGCCGCCCCCTCGGAAAAACGCCGTTGGGTTTGTTGTCGATGA
          ACTGTACGCGTATAGAAAGACGCCCCCTGCGCTGATAGCAACTATTTTTCTTGTCGGCGA
          ATTCGTTCTGCTCAGTAGCCCGCTTCCAATTTAAGCCAGGCTGAACGACACCGTGGTTGC
          CTAGCTTATCCCCAATCAATCGTCACCAATAGAGGCCGGCATGAATTCCATTCATGGGGA

          CTTCTTCGACACAACGCGTCCCATGGGCAATTAACTATCGTCAGATGACAACGGCAGCTA
          CTTTATTGGTACACCGCACACCTCGCGCTATTAATCATCGTAAGACTACTACGGCAACTA
          TCTACTATAGTCTAGATGCATTTTTTGTCGGACGACAGATCGGCCGCAATGCCCAAGGCG
          TTAACTGCTAACTTCGTGTACACCTCGTCGAATGACAGTTTGGCCAGGTTAACCTAGGCG
          GGGCGCCCCCCTGTTATGCATCTGTCTCAAAATGGTGACGGTGGGGCATTACTGCATCTC
          CGAGGGTTAGACGTTGTGTACTTTTCTGTACGTACTGATCATGGGCTCTACTCGCGACAC
          GCTTGGACGATAGTTGCGCATTATTCTCCACCTACTAGCCATGGGCGTCCCCACTTGCTT
          GATCGTTTATCTTCAGTACACCTTATCCCGTCTACCAGTCGCGGGCCCCACTAACGCCAG

          CCAACAGCTGGCCTCAACTCTCCTAAGAGAGGAGGACCGCACTAGAAATGAACACGACTG
          TCAACGACTGGTCTTAATCCCTCAGTGAGAACCGAAATGTGCAAGGAATCATCACAATTG
          TCAAATTCTTTATCTAGCCACGTTGCGATGTCGCTTGTGTAATAGGCCCACTGGCGAATT
          TCAAATCCTGGATCCCGTCAAGTTGAAAAGCCCGCTGCGAGGTAGTCTCACAGGCGGATC
          TCGTTAATTAATTCGCGCTTCCATAAATAAGATGAAACGCCCTGAACAGTTTTACAAAAA
          TTATTACCGGGGCTTGACTTCCCCAACTAAGATGGCATGTCACCGTTAGTAAGTCGGCAA
          GACCCGTCATTGCTAGGGTCCTCCTTACGTCATGAGCCGTGATGGGTTCTTGCGCGACGG
          CCGTCGCCCGGACCCAGCAGCCCCCGCCGCGTTAAGCTGTGATGCGAAGGCATCAAACAA

          AATTCCAGGCGGCCGTTATTGTCGCAGTATTCGGCCTAAAAGCTGGTATGGTTCCTCAAA
          AATCGTAGGCTGATATTATTGTTGTAATATATGATTTAAAAATTCCAACAGTTCTACGGA
          TCTCGTAGGTGAACGCTGTTGGGGATTAAATAGGCCCATAGACTAAACAAACATTGCAGA
          TTACGTAGGAGACTGCTGCTGGAAACAAGGTGGGTCTACAGGCTAGCTGAACACTACCGA
          CACTGTTGGGGATCATGGAGCTGCCATAGGACAACCCAGGGCTCTGATACACTAAACGAG
          AATCTAGGTTGGACGCACACTAGCTGTGCCACGATCCTAAGACCGGTCTTGGTGCATGAA
          GATGCTCCCTTGGAACAACTTTGGCGTAATGTGACTTAAAACTCAGCCGAAGGATGGAGA
          ACCGGCTGTTAAACACTTCCTTGATTCAATACTCGCTCGGAAGTGATTGTAGTGTCGGGG

          ACAGGTATCACTTACCGGGACTACCTTCGGTCCGTTACATTTGATGGTGGCTTGCTATCA
          ACGGGCATTATACGCCTGGTCCATTCTCACTCCATTATATTAGTAGCTAGCATACTTCAT
          ATCACTGGTGGGTTGACCGTGTATGGTGTCCTCGTGTCATTAAGTGGTGGAAAGATCTAT
          ACCATCAGTGGATTAACTGCCCGTGGTACTCCTGTGTTATCAAGTGGTGGAACACTTCAT
          TTGACCTTTAGGTGTACGGTGAGACGCCTACCTTGAAAACGTAGAGGAGATACTGCCCGA
          TCGAGCCCTAACGCACCGATGTAGCCTATTCGTGCGAAAACCGAAAGTGGCATCTTCCCC
          TAGGTATTGAGATGCTTAATGGTTGAACCTATCAGCCGTAATGGAGGAGACTCCTTTCGT
          CGGGCCGCAAAGTCCTCATTGGACCTCTTACCCGTACGGACTGGCAACGCGATCCTAAAA

          GGTCCACGTTCGTAAGCCCGTGGGGTAGTCTATACGATCGACTCGTTAAGGAGCTGCTCG
          GCTCAATGGTTCTAAGTATGAGAGGCAGTCTTAAGCAACGAAGCGATAAAGAAGTGCCCT
          GCCGTGGACCCTTAAGTCAATAGACGCGACTCCTGACAAGGTCGGGCCTAGAGCCCGCCT
          GTCGAAGGCTCTGCATTCTATAGACGCACTTCCTAACAAGGTAAGCCTTAGAGACCGCCT
          CGAAAAAATCTTACCTCTCCCCAGGACGCATCCCGCCACCACCCGGATACGACGTGAGTC
          CCGAAGGGCCCTTCTATTGATAAGAGCGCGTCCACCCACCAGCTCGTTAAACCTCATGTA
          CTACGCGATATCCTAGCTTCAGAGCGTGTTTTTTCCCAGACCTATCCTATGATTAATCAT
          CCGCAAGAAACCCCCCTCCACGGACGCGCCCTTGACCTTATGTCTCTAATGATCTCCCGC

          TTCTTTCAGAATAGTCAGCTCGCTTATAGTACACTTATTACCGCGCGCGGCCTACTAGAA
          CTCTCTTAGAATGACGTTCTTGCTTATTGCACACTCCCTACCGTGCGCGGCCCACGATAG
          GTCTAAATTCCAGACATCCCCGAACGTTGTCGGGGGTCTTTTGTGCCTAACCATCCCCGG
          GACTAGATCCAAGCGATCACCGCATGTTACATAGACTATCCCGCGCGTAACCTTTTTCGT
          TGCCCCTGCTTTGATGTCACTCATTACTATATCGTTGGAGCCGTTGTCGGTGTCGAGGAT
          AACCGAAGCACGGGGCTCTACTACCATTGTAGCGCATACAATAACGTCGGTTTGAAGCGC
          GACTAGCATTACGATTACTATGTCCAGTGTGCAGCTCCCAGCACCGCTCGTCCGCTGTGC
          CATTGGTACTATTAGCTTTTTTTCTAGTGTGGCGCAATCTGTGCCTTCGGTTTATAGGGC

          CTGTCGGGGAAGGAGAGATGTAAATTCGGTCAGCTGGTGAATGCCATCTCAACGGCCGGT
          CAGTCGGAGAAGATGAGGTGTCAACCAGACCGATACGTGAATATCCGTTTGTGAAAGGGG
          GCGTCGTTTCTGATCTGTCTTAACTAAGCTCCTGACATACACGTGCTTCCACCTCCTGTT
          GCGCTACATCCGGTGGTATCTAAGTAAACCCCTAACATACACGCACTTATACCCCCGGTC
          TTAAAGAAAACCGCACAGTCGAGATCATAACCACTCCGTAGTAGATCTCTAGCGACTAAA
          ATGTCGAATCTAATCGGACCGGGACTTGATTGTCAATGTAAGAGAATTCCTGCAATTACA
          CGGCCTACGTCTATATTATTCAATTGAGATCCTTATCACGACAGTCTTACAGTGTGCAAA
          ATGGAGGAGACGGTCGAACTGATAGCGGTACTCTACTAAAGCAACCCCTTGATGGACAAA

          CGAATCTCACGAAAGCTCACGCATGTCGTGCGCTTTAACTCCTCGGCCGAACATTCACGA
          AGTAACTCATAACCACTGAGGTACTCCACCCGATTCAACACCTAGGCCGCATAACCACGA
          ATAATTCTATTGAAATAAGATTTTTAGCCGCTCTAGGGCCTATACAACGAGAACGCGAGA
          ATGATTCTACTGAACGAAAATTTCTAGGGGCTTCTGGGCCCCTACAGATAGAGCGCGTGT
          AATCTCCTGCCTGTGTCTGGGTGCAGCCCATCATGATGCATATAGATATCGCACCAGTAA
          TCACTCACCCTCACGCTTCGATGGACACCACGCCTCCGGTGATCCACGCCCAAAATACGA
          GCATTCTTATCGGCCTACGAGTTTAACGCATCTGTCGATTTGAGTGTGCAAGCGGTTTAC
          TAGATCCCTAAAGAGCATGGGTAGGCCGCGTCTCTCTTCAGACGAAGTTCGGCTCTATGG

          AACGCACCCAGGAGCGACGGGGCTCAGGAGGCCACGTAGCTGCACACACTCCCAGAATGG
          GCCGCGCAGACGGGCGAAGGGGCATAAGAGTCTGCGTACCTGGACATACTCCCAGCACGA
          ATTAATGCGACGGGAATAGATGCGGTTGTCGTCGCTTACGTGGATATGTCCATGGTTCTG
          CCCAGTCCCATGCGGACAGAGGTGGATGTCGTGGCCTGCGAGGACCTATCCACGGTTCTT
          AGCAGACGTCCCAGCTAAAGCACGCTCGGGGTTGTCCGTCCTGAAACTTCCTTTGCACTG
          AGTAATGACCCCATCACAGACGGGCCCAGGGGGGCACGTGAATCAACTTTTCATCCCGTA
          TCCAGTCCCTGCAGTATAAGTGTGTATAGAAGGAATCTCGACGACCTCGACGCAGCACAG
          ATTATTCCGTTTGGTGGAGATGCGGCTAAGGCGACTCTTGTAGAGTTCATGATACCGCTG

          GTTATTAAGTCACATTTTCCGAGCGGGAATCTGGTTCGTTGGTGACTGGCCCTCTTCAAT
          ATTATCATACCGCCCCAATCGAGTGGGCACACTTTTTGTTGTTGAGGGACCCTCTCTACA
          ACCACGAGTCCACATAATTCCAATAGGAATCCCACGTGCGAAAGAAGGGCTGCTCTATTG
          GCCGTAAGTCTACATTATTCCAACAGGGCTCCTATGCGGGAGAAAAAGGCAGCATTGTAG
          CGCTCAGTCCTACACTACTTACAGGTGAAAACCCCGGATTGAGACTCGCATGCTCCATAA
          GTAGAAGGGGCACAATCCAAACTGGCGAGGGCTCATGTCAGAAGGGCAGCCGATTCCCAC
          AGCGGTGGTTCATGACCCTGCTGCAGGATCGGTCATTGTACACGGACGCCTGCAATCGCT
          GGCGGGAGCCCGGCTTTTATCCACGGGGAAGGCCAGCATGACGGGGCGGTTATACCCATT

          TTATAAGCCGGGCGTACCGCGGACCTTTTTCAGGTAAACCTATACAGATATACTAAACTC
          TTATAATCCGGGCGTATCGCACACCCTCCTTTGGTAAACCTTTACAGACGTACGAAACAA
          CTATTCCCTAACCCCCCGACTTAGCTGCCCCTCCGGCGTCGCCGCACCTGGATATTTTAC
          TCGCACCCAGACACCCCGTTTTAGCCGACCCACGGACTCCGCGATATGTGAACATTTTAT
          TCTGCCTCCGAAGATTTAGTGAAACTCCGTGGTCAGAACATATGTAAGCGAAGCCCACAC
          CGAGTCCCCGGTACCGCCCTGCGTCTTTCCGCCGACGGCGCTCAGGGTTATACGTGATAC
          TTCGGTCCCGGGGTCCTTTTACGCTTTTCCCAAGGGAGCGGTAGCGGAAATATGTCAGCA
          ACGGATCTTGAGGACCTATCATCACTCCTTTCCGTGCGAACTAGCTGACGCACGGGAAAA

          AACGAGATACTAATCTGCTCGTGGAGAACCGGAAACCCCG
          AACAAGATACTGAATCATCAGTGGAGGCGCGGATACGGCG
          TAATGAAACTTTGAGTGTCTTTACTGGGCAAATCAGAATG
          GAACAAATCTTTGAGGGCCTTCACAGGGCAAATCGGTACG
          AATAAATGTTGGCTTCATCTGGAAAAGACCGTCTCACTCT
          AGTTGTGGGTTGCCTCATTGTGGGAGAGCTGACGGGGTGC
          CACCGGGGCTAGTATACCCAGGGAGTGGCAGGTCGCATCG
          AAGTATGCCTAGTACTCGCCGGGGAGGATGTGAAGTACTA

