 8 1000
t1        TTAATAGCAGTTTCGGACTACACGATGGGTGCACATGCTTGCGAATCGTTCGTAGTGCTA
t2        AATATTCAGACCCCGGGGTGACACATTACCCGGTACATATACACGTGGCTCGAGGCGATC
t3        ACCACATATGTCATGGGTTTTATATTCGGTGTTCGAGGACGCAAGCCACCCGGAGAGCTG
t4        ATTTCTTAACGGTAAAAAAATGCTGGTAGCGCTTTTAATCGTGCCTAACATATGTCGTTT
t5        GACTGATCGTGGCGTAAGGTTTAGGCAGCCCTCCCGGATAGTTTGTAGCACGAAACGTAT
t6        TACTTACTCCGGCAAGGGGACCTTGTTGAGCTCCGTGTTCACTCTTGGACGGCTATGAAT
t7        CCCGCGAATTGGTAGCCAACAATTAAAAGTGGGAGTATTCGCTTGGATCGGGACGGACCT
t8        ACTAGTTAAAGTCTGGCGACCAAGGGTGTTGTATCCGCGAGCAGGGAGCACGACAGAGTT

          AAGTTACCACGCAGCCTGTATCCTAGCATGGTGGGATCCCTGCTTACGAACCGCGCGGTA
          AAATGTCTATGCAAAATTCGTTGTATTCCAGCGAGACTCCTGTCCGATAAAAGCGACATA
          GAGCCTTTACGCAGACTGCACGATATTACCGGGGTGTCCATGTTAGAAAATATTGTTCAG
          TAGTGCTTATTTAGCTATTCCTTTGCCACCGCTGACGCTCTGGTTGTGGAATATGTTGAA
          AAGCGTTCACGAAAAAAATGGCTTACTTCGACGTATATTACAATCGGGGGATGAATACTC
          TAGCCAATAGACAGCAAGTACGATTCCCTAACGCATGCCAAGGCCAAACGGTGTATCTTT
          AATCGTCTCGGGAAGATATGTCCGTGCATAGTATTGCCCGGGAACACACGAAACATGCTA
          TCCCATCCGTCTGCATTGTCTGGTCTTTTGGTGAGGTCTTAAGCGGAGGGAGGGCTCCCA

          TATATTGTCTAATTCTAGGCATCGCGTTGGCAAGGGCTTGTGGGCTAAGGCTACATGGCT
          AATTCTAGCTTAAGACAGGCCGCGTGAGGCTAAGGACTAATTTGTATCGGTGGCGAGACC
          CGAGCTCTCCATAGTTTGGTGGTGTGCGGTTGGGGAGATACCACAGTTAATTATGCGGCT
          CCGGCCCCTTCACGTTGTTCCGTGGGTGTCACCAGATATATAAGTTTTTGTAGAATGTGT
          AACACCTCTCTCTCCTGAGCGAATTCCAACTTTATGAAGAGCCGATCTACTGAGATGGCA
          ACCACCTACAACAGTTATGGCGGATCTTTTTTTCAGCAACAATGCCGCTGTGGGTCGGTT
          TCCACTTATCCGCAGAGAACACGCTGAAGCTTAGACTCGAGTGGTGTTGACCGCACGGTT
          CATGATATCTACGACCACGCGACCGAAGGATTAGGCATAAGATACATTAGTCGGATGGTC

          TAACTGGGACATAGCCATACGCAGCGAACTACTTCGAGTTCATACGACGGTTCATTGCCT
          GGGTCAGGACTCGCCCCTATGGATCAAATAGCTGTGTTGTCGACTGTCCTCGTGACGCCC
          GCGCTGAAGATCTGTCATACTACTCGCGCTATTTCGTGGCCGCACAGCAGATTAATGCCC
          ATATTATCAATTTATCGCCTTGATTTTTCTATTAGTTAATCACATTGCGGTCTAACAGCT
          GAATAGTGAGCCTAATGCAGAGATCCTGCTGGCGATCCACTGCGTTTCAAATCCTTGGTT
          GTTCTGCAACCTAGGCACACATATCGCACTAGTGAAGAGTTTCATTGTCGTTTCCCTACT
          ATGCCCTCAACTAAACTTACTACTATTGTGTACGTGAGGTCACTTTATGGTCCATGTGTC
          GCATCTCAGATTCGTTGGGTAACGATCCCGAGAGATCGATCATGCTGTGGCCTCTCTACT

          TTGGTTTGCAGGCGATCTGAAGTAACACTTTCCACAAGACCGAGGGCTCGCCTATTCTAC
          TTGTAGAGTAAGCTTTCAGAAACACCACGCATCATAACACAAACGGCAGTACTAATACAT
          CTGGCACACTAGTTACTTAAGATCATACCAACCGAAAGGTAGATGGGCATACTAGCACTC
          GTGTCCAGCCGATGGTCCGGTACACAATTGATACGAGAATGGCTTAGGTCCGCTGCGTTC
          ACAGCGTGTCGGGTCTAAGATACTCTCCAATCGAAGAGAAGGATAACTTCTCGGACCGTT
          ATGATGAATCGGGAAACGGGGAGACAGTACGATATAAGAGGAATCGCTGACTTGAAAACT
          AAGTTAAGCCAGACTTTAGCCATACTGTACACACTATAAGAGGCCCAGTCTTCGAGACCA
          GAGTTCCGCCGCGTACTTCACCCCCCCCGAGATAGAGACAATTTCATTTTCATGGAGTTT

          TAAGAGAATTCAGTCTTGACCGAACTCTCATGTTATCCAGGTGAGTCACCAAATGCTGGG
          GCAGACGTCTTACCTGACTCAGAACTCCCGCTCGATCGGGGCCCGTGATCGAATGATTGC
          CTGCGAAGCTGTTACGCACTGGGGCACAAATTTAATTCAGCCCGACGAGCACATGCTCGG
          TGACGACATCAACCCATAATTCAGCTTTTGCCGGGTCTGGAACAGTGAGCCATTGACCCG
          TATCCGCTTAGATTCGTCCGGCGTTTTTTATACAAATTGGAATGGTGCCAGGTCGTCTAG
          TAGATGATTGCATGCGCCCTGCAATATCTTTGTAAAAGGACGAGGCAAGCAGGTTCAAAA
          CCACTGCATTAGTTCGCCCGTTGGAACTTGCCCAGCAATGGCCTGTATTCCAAGTTAAGG
          CATCATCATTGGTTCACATTCTGCCATGTGTTTACCCATGACCGGACCATGACACCTAAG

          AGCACAACTACTCGCGTAGTTATAGCCGACGCAGTATCTATAGTGTCGCTAACACTTAAA
          AGGATTAACCTTATTCGTGATACCCCCGACCTGGCTGTTACTAAATCGGATATATGGAAC
          AATTACAATTCTTATGTATACTCGGTGGGATAGGCGGTTGTGAACCGGGGAATGTGCGAA
          AGCACCGTTCGATAGTAACATACGAGTTACAGTGAGTAGATTACTCGAATAGTCGTTGCG
          GTGAGTAACGACCACTTGCGTAACAGAAGTAGAGACGACGATAATAGGGTCAAAGCCGGT
          GCGTACTAGCTTATCCAACAGATCGGTGGTCCAGAGAATTCATTGTAAACCCGGGTTACG
          CCTAATCGTAAAACCCATGGTACTGTCGCCGTAGAAGGTCGAACCACTATTGTGATTCAA
          ACAAGTCAGTGATAAGAACGCATCGTGAACGCAGTGAGGACTACGACGGCCACGGCTACG

          TCCTCTTAAAGAACTGGCAGGACTCTGCGTCAATAACCTAAACCCGTGTTATCAGGGTGT
          CACCACAGAAGAATTTCCAATAATGACTGCAAGTCATTTACACCTTTGGAGATGGGATGC
          GGCTTTGGAAGTGTCAGTCAGAGTTTAAGTACAACGTTTACATTCAAGGAGATGGGGTGC
          AATACCGGCTGTACCTGGACTATTGGACGCAAGAATTCCATTCGAACCACGGTGCGGTTT
          ATTATATGGAGGAGCACCGTCGCTCAGGTCTGTATAAATGACCTCGCTGAGTAGGCGCTA
          GTGTGCTGGCGGATAAACATTGCACCATGTCATCCGGATAACTATTTTGAATCAAGGTGT
          TGCTTCAACAACATCTGATACACCTTACCTGACAGTTCTTAGCTGATCAGGGCTCACTCC
          TGGATCCCGCTAACAGGTATTCCCTATCTTTAGATAATAGGTGTGAATAACAAAATTATC

          TGTCAACAACTTAGATCATCTCCCCACGAGCCTAGGACTCCTTATCTTACCTTCGAAGCT
          CGTTAGACATCTAGCACGTCTTTTTTTGCCCTCGTCATGCCCGCGCCCACGTGTGGGGCC
          AGTAAATAGGTAGGTATCCCGCAGCGGATCCCTGTTTTTTACCACCTTTTACGTAGAGAC
          TACGACTGAGCTGTCCATCTCATCCGTGCGCACGATCTTCATTGAGTGACGGATATAAGT
          CGTTGGTCGGGCGACTCCCATATGCATCGCTTCGAAGTTTTGTACCCTGCGTGTAAGGAA
          AATAGATTATTTAGTGGATCCCAACGCCACCTCGGGACCGCCCCTTTTACATGCAATAGC
          CGATACACACCATGTCTGTCCTGATCAAGCCACCACATTTCGGAATTATTTAGCGTAAGA
          TAGGTGGGTTTACTCCGATATGATGGTGGGCTCGGTACTTTCAACTAACTGGGTAGATTC

          TGGACTTGATCGAGAGGTTACACAGTACTTTGTTGACTCTGATCATTGGACATATGATGG
          CTGGGCAGCAGGAGAAGACCTCCAGGCCTCTATTTCTACCGTTAACAAAACTTAAGGTGA
          TAAGGCTGCTCGCGAGGACGCACGGGCTATTGCCTCCCTCTCTAATATGACCAAAAACGG
          CTCACACCTTTCGTACAGTCCACAGACAAATGCCGTTCCCACTCAGACCTTGTTAGACAC
          TCAATTTCCTCTCCATGTCATGTTGTTAGATGCAGTTACTGTAGAAAAGGGGAATGGTGG
          ATGCGCTCTTATTCGAGCGTGGCCCGCGAGAGTTGTCCGTGAAGTAAAAGGGTATAATGA
          GCAAGGGAGCTGGTAAAGCTCGCGGTACCGTCCACTCTATCGGAACTGGAATCGTGGTGG
          CCGACGTGGGCTCTAGGACTTCCTTGACGGCGGTCGTACAAACAACTAGCTTAATTCTAA

          CTCCGCTTGTGCGGAGGAGTGATCATGAATGAATATATCGATAAGGACACAACTTCTATG
          ACCTCGGTACGTGAGGCGATGACCTAGGGTAGATAAATCGGCGAAGACAGAGATTGAATA
          GCCCCAATGCGTGGTGCAATGCTTGTAGGTGACAGGTTCTGTAGGTATGAGGATCAAGTA
          AAGTAGCCCAGCCTTTAGATCACCCCGGTAAATCTTGAAGGATAACAGGCGGGTTTGGTG
          ACGTGTTGAACCGGAGGAATATTTGGACCGCTAGGAACAAGCTCGCAGGAGGATCGTTAG
          CTGTGTCAAGATTGGGTGCTGTTAGTCTTTGCAAAACCTGCCAGAAACGCGGACGCCGGG
          GCCGAATGGATCTGTGCAATACTCTTCCCTATGATATTTAGTGTTCAGGCGATGTAGGGT
          TGCGAGATACGCGGTGCTTCACCGGCTTCTATCAGCTCAGGGACCCATACCTTTTCTGAT

          CACACTTGGGTATAGTCCACCACTGGCGACGGCAGCAATGCTGTCATTAGGGTTATTCTA
          TACTCATAGATACGGACTCCCAACGGTTAGAACCATGCGCGCGCTACCCGGCTCTATCCA
          TCTCGCCACGTATAATCGTTTTTCGTGAGGAGCGCAAAACTCTTGGGCAGGTTCCAAATT
          TGATGATGACGCCGACTTGTCAAGGGTAGGGTTTATACCGACCACACTTAGCTACGCACT
          CCCTATCACAGACCTTGTTTTGCAAACAGGAATAACCATGCAGGCTCTTGTTCTTATGCC
          TTCGACTACAACCAGTTCATTAGACATAGCCACACAAACGGATCCCCTCAGTTTCATGGT
          TCTCCTTCAGCAAAATCTCCTCGAAGTGGTTACAGCAGCGAATCGTCTTGGCTCTGTCTC
          CCGAAATGATGTAAAATTTATTGCGCCAGCGACGGTAGAATAGCCACCTTACTGCGCAAT

          GTCTCACTGTTTGCCCCTCGGGGGCGCTACGCTCCAGGGTATCTGAAGGCTCAGTTAAAG
          CACTCAGCCTCTATCGTATGTACAGGAGAGGCTTAGGGCATACTGGAGGGCCAAGTAGGA
          ATATGACCACTTGCTACTTATGCTGAATGAGCCTTAGGGATCTTGGGTGTTTAATTGAAG
          AAGGGAGGGTTGACAATTGTTAATAACTATCATTTACCCCTTCCGGATATCGAAATAGAA
          GATAGCAGGCAAGTTGACTGTACTTCATGCAGCTTGTTATACATGGGAAATAGACTGCTG
          GATTACTGGATTACAGTTTATTTCGGGTGAAACGCGACAGTTGCTGGCGAATGCCCTCAG
          GTACGCGTCCATGACGCTCTGCTGGACCTAATTACGGTAATTCGCACGACATGCGAATGG
          TCCGGAGAACTTATCACCTCTCAGATTTCTTTCCAGGTAGCACTCCTAGGGAGTTAGGCT

          TCGACCAAAAGCCCAATTTAGGCCCACTAGATCTAAAGAAGTTTAGAGGACGAAGTTTTG
          ATAGTCATAAGACGAACCCGACTCGTATAAGGACGGGCGACCTCGAAGCGAGCGGACTTA
          ACGACAACCGGCCCTGTTAGGCTTTGGTGGGAATAGGAAATGCCAGAAAAGACACATACG
          GTTGTGACTAGATCGGCTTGTATCTGTTGTGGATCACAGACTCATAGGTGACCCAAACAG
          GCGGGCAAAGTGAAATCCTGCGCAGACCGCGGCTTACACACGTTCGTAACACTTGGCTGA
          GCTTCTGCCGTGACGCTACAGACACGTTGCAGAATTAGAACATCGGAATAATCGGAGTAA
          CCAGCTAGCAACCTCCCTCAAATCGGATGAGCCTTGAGAGACCCGTACACTGCGCAGGAA
          AGTGCTAGAACACTGCTCTGCGCGTTCCGTCGTTTGAGATCGACTTCGCGTACGAAGAGC

          GAATGCGGCGAGCTCTCTTGAAAAGAAGTTGGGTGCTCCGTAGCCCGGAGCGTTATGGTG
          GGGTGAGGTATGATACCTTTTGAAGTAGATCAATGGTTAACAGCCCAAGACACAGTGGCG
          GTGAAAGTAGTGCATATACGAGACAAGGGCCAACGGCTGACATTCTGGGGCTTAGTGGTG
          GATTGCCGTGTGGAAAGGGGAAAAGAGAAATGGACGTATGACCTTGGGTGAACACTTATG
          GGATAGGGGGCACATCTCGAAAACGAGGGCACAAGAACAGCAGCTCAAAGCAACGCTACT
          AGATGTGCGTCATAGCTGAGCAATGAGTTCAGGGCAGTAGCAGCGCAGGAATCTGCCATA
          TCTATTGACTTACACCACGGGGTTGAAGGATGCGCACCTCAAGTTTGAAAATGCGTGAAG
          GTAACTGAAGAGATGTATCAGGGCGCAATCTGCTCGTAGAGAGTTTAGGGATATGAGAGG

          ATGTTCTTACTTCAGTGCGTAACGTTACTGAGCTGTTGAGTGTTGACGAGATCCCCCCCA
          AGGCAAACAATACGGTAATCGTCTTGGGCGTACTATAAGAGGATGAGGTGAGATTACGCT
          TTGTTTGTTATTCATTACTGAACTTGATTATCCAGCCAGGCTGTATAGAGAGATCTCCCT
          TTATCAATACCCGAGCGCACGTTCTGGACGGCTTGTTGGACGATCTACGACCAATTTCCC
          CAAGCGTCGAGTCCGAGATCGGGCCAAACGAACAATTAAGTGACGCTCCAGGCCTCCGAC
          AGGTTAGCAGAACTAGGTGCAGCTTGATGGGGCATTTGCGTGTGGTACTGAAGCCTCGCA
          ATATTATAAGGTTATCGCACCGCACTAACGTATGGTGCGGTGGAGTTAGAGAATTGTAGG
          AACCCGGCTGACTAGAATGTTGACCGACCTGAAGTTCTAGCAGTGGCAACGAGCTAGTGA

          ACGAGCTGGGGTCAGAGGTTCTCCGGTGTAGACAAACACC
          CCGAGCCTCAGTGGGCGGAAACTTGGAGAGAACTGCCGTT
          CTGCGGGCATAAAAGCTGCGACCCAAAGAAAGTTCCTATC
          CCGCAGCACTGAGTACGGCGCACTATAGACGCTCACGCCT
          CCTGAGTCCATCATTCAGGTTCCTACAGTAGTCTGTGCTA
          TTTTACTGCTAAGAATCGGGTTTAGGAAGAGATCGCCCTC
          CCCCAGTATATCCCATGGCCCCTTCGATGTAACCTCTAAT
          ACGTCCAACAGAATAATGGTATTCAAAGGTGATTCTTATG

