 8 1000
t1        TTGGGAGGAGGTGAGCATTGCCAAATCGAATCGTCCTTGTGGAAAACCCAATTGAAATAA
t2        TTGGACTGAGGGGAGCACCGCTACATTGTATACTATTAATGGAGAACTCCAGTGCTATCA
t3        CTGCATGGAGGGGAGCACTGCTTAATTATATACTATTGAAGGGGAACCCAAGCGAAATCA
t4        TTGAAAAAGTGATAGGATTATTCCAATGTATGCTCCTAATAGGTAACATGCCCGCAGAAT
t5        TCAAATGACGGGGGCTAATACCGAACTCCAGCCAAATAACGGAGTGCCCCCCCATCGTTC
t6        TTAAACCGCGGGGAGTATTGCCGTGCTAGTTGCGACTACCAGGGCACCTACCTAACGCAC
t7        CTCGGCTGGAAGCCGTGTAGACAGACAAACTGCGGCGACTGTAGAAATAGCTTAAGATAC
t8        GTTACTTGAAAGGCGGGTAGCCAAGATACAGGCGAGCGCCGCAAAGACAGTTCAAGACGT

          CCTGTCCTGTTGTCTACGAGTACCCCAAACACCGTAGTGGTCACTGTTGCTACTACGGTG
          CTTGCTCCGCTCTCTATGGGCAATACGAATACCGTAGTCAATTCTTCCTTTACAACGCTA
          GCGGCTCCACTTCTTACGAGTACTATAAATCTACTAGTGAACCCTTACTTTATCGCACTC
          CTTACCCTAATCGCCATGACTGAAATTAATCTCGCAGTAGATCCTCTTTTCAGCGCGTTA
          CTCGTTCAACTTCTTATAGGTGTTATCAGTACTGACATGGCCCCTTTCTTCACCACGATA
          TTGACGCCTTTTGTCGAGACTGCCAATGCCGTAGTAGTGGACCCAACTTTCGATACTACG
          TCTTACTAATCATCCGCCATCAACATAGGCGCAGTCGAGATGTCCGATTCAGACGAATAT
          CCCCCCCGGCTCACTGCTGGTAAACTGGTCATATTGGGGATGACACATCCAGGAGTGCCT

          CGGCCTATTACTTGGGCGTTCCGTCTAGGAAAGACTTGCTGTTGGACTGATGCGTGATAA
          CGTCTGGCTGCATGTCTGTTCCGCTAAACACAGCCATGTCCTTGAATTGATGACCCTTGA
          CAGCCCACTGCCAAAGCGCGTCACAGGTCGTAGACATGTCCGTGGATCGTTGACTCAAGA
          TCGCCGACGAATTGAAAGTACTACGAAAAGCTCATGCATGCTTGAGCTAATGTCTTATGA
          CGGCCATTTAACTGGGCGTCAAGCGGGGGTTTGGTAAATCTGCGAATTCATCCTCCAGAA
          CGGCCTATAAAGTGAGCATTAACCGTGATGTAGATACCCCTGTGATTCTATACTATAGAA
          CAAATGCTCAACATTTTGGACTATTGACATTGATGCGACAGTGGCACGGGTACCATAAGC
          CACGGATCCAATTGGCTTGATTGTCGGCACCCGTAACACCCCCCAACGAGCGCCGCGCGA

          TCGAGGACTGAGGTGTCTGTATTGAGTTTACATGTTCTAGGGCGTAGATGGATATGCGAG
          CTGGGGGCTGAGATGGGGATATGGAGACCATTCGTTCTAGGATGTAAATCACCGTGCGAA
          TTGAGGGCTGCAATGTAGACATTGCGTTTGCGACCGTAAAGATGCGATTGGCCATGCGAG
          GCGAGCTTTAAGATACAGCTACTGAACATATACATCTCATGATCTGGTAGGTCGTGTTGG
          GGATGGAACGGGCTATAGATGATCGCTGTGCACAGGTGGCGATAAAACGCGCAATGAAGG
          GGATTGATCGAAGCATGGACGTTAAAAGCGCGAACGCGTCCATACAATGCACAGCGCTGG
          ACGCCGATCTCTTCAAACCCAGGACAGCTCCTCTTGACTGCAACTTGCGAGCATCTCGAC
          ACGTGGACTTTTCTTCACCAACGCGACCTCTGCTCGATCGTAATCTGCGGAGGTTTCAAA

          CATGTGGTGATGACTCTGTTGCAACTAACTGCGTCCAGTTGAGCTGTCGGAAGCATCTGT
          TTAGACTCGGTGGCTTTGCTGGACCTCGTTGAATTTGGTTGAGATGCTTTAGGCTTCTAT
          TCAGCGGCGATGGCTCCGTTCAGTCTTGCTGTATTCGGCTAAGACGGCTGAAAAATCCGT
          CACGTACCGATGGCCCGCTCGCCCCTAGCTGTATCTGGCGGTGGTGATCCAAGACTCAGT
          AATCCATCGATGGCTTCCGCATATTTGGCAAGGCGAGACTGCGATATTTCCGCCCTAAGC
          CCCGTGTCTATGGCTCCGTGACATTCAACCAGGTCCGACTGGGATAATTGCGCCCCGGGG
          TGACTCCGATTGGCAGGCACGTCGTTTAAAATCGATATTCGCGTATATATGGCACACACT
          CATTTCCAAATAGTATATTTGTAAGTAATGCTCGATCGTTGAGATTATTTATTCCACATT

          AGAACATCTGAGAGTAAACAAATGATACTCGGTCGGAGCTCACCAAGTTGTAATTCACTG
          AAGATGCCTGAAAGCGGACAAATGATCTCTAGCCGCTGCCTCTCAAGCGGAAGTTTACCT
          TTGACATCCGCTTACACACGTATGATCTGTGCTCGGCACCTGCTAGGCAGAAGTTTGGCG
          ACGACTTCTGATTACAGACGAACGATTTCTAGCTGGAACTCGTCAGGCATTAAACTATCG
          ACAACAGTTGAGAGTGTTCAAGCGGTATTCAGTTGTCGCTCGTTAAGGCTAAGTGTACAA
          TCGCCAACGGCAAGTAACCAGAGGGGTCCCGGTAGCCGCAAGGTCGACTATTGCCCACCA
          GGACGAACCCAGATCAAGAAGTGAGTGCTAGGCGGGGATTACAAGCTCTTGGTATTATCC
          ACACGTATTATACCCAGGACCCACGCGACCGACCGCACTTACTATTATTCAGTATTATAT

          GTTTCCACGTAGAACGAAAAAACGCACTGTCGAACGGCGACCTTGACACCAGTCCGGCCT
          TTCCCCGCGTACGATACATATAGGCCATCTTGAATGGCGGGTCTAACACCGTTACTCCTA
          CTCTCCGCGTGAGATAAATCTGTGTGGTGTAGAGTGACGGTCATGACGCCGCTACGCCTC
          CTACCCCAGTAATACATTAGCACGAGGCACCAAGGGTACAACTTATCAACAGTACGCCTA
          CCTTTAGCGTGAAACGAGAGCATAGGGTGCCGGGTAGGGGGTCAGCAATCAGTACGCCGC
          CTTTTCAAGCAAGATATGGAGATAGGGCGCCGCGAGGGAGCCCAGAGAGCAATTCGCATC
          GGACTCGAGTGGGGAAACCGGCAGGTCTGGCGAAGGCTGGCTGTAAACATAACAAATCTT
          CATAATGAATAAAGGAACTGATTCTCTCGTCAAGGGGGGAATTAGGAGACAATACTATCT

          CCAACACTTGCAGACGGACAAATCTTTGCTTCGGCGCGCTCGCGACATATTCACCGAGAC
          CGAATAATTGATCGCGCATAAATTCATGCCTTAGGGTACTCATGACACGTTCATAGGAAC
          AGGCCAGTTGAAGGTGCATAAACCTATTACCCAAGGCACCCGTGACATATTCATAGGAAT
          AAATCAATCGAAGGCGCAAAGACATATTTTTCGAGGTACTTGTGGTAGGTTCATAAAGAC
          TAAACAGTTGGAACTGTACAAGCTCCCGATTCGAGGTACCCGCGATTTACTAGATGGACC
          ATAATGGTCGGTCCTGCTCGACTCCCCGAATCGGGGAACTCGTAGCGAACTTAACAGTAC
          GCCACTACTAACGAGATGCTAGCAATATGGTACGTTCGCATAGGGGTTAAAGGCCGGGCG
          ACCACAGCCGACTCCATGTGTCCGGACCGGTTCACCTGAACGAACAGTTCAGAGTGGCGG

          CTACCATCCCAAAACTTACCCCCAGTAGGTGAACGGTTTGAGGCCCTTACTTAAAAAATA
          TGATTATTTCTGAAGTCGCCTCGACCGGTTTAGAGGTTCGAAGTCGTCACTTTTCGGCCG
          TGACTATCCCAAAAATCGAACTGGGTGGTTTAAGGGTTTGAACCTATCACTTTTCAGCCC
          AAACCGGTTTTGACATCGGCACTAACGCCTTAAAAGATCAGAGTCGCTTATCTTTGGCCG
          TTCACGTTTCCGGAGCTGAGCCCATCAATCTAACGGCTTGCGAGCTCACATTGTAAGCCA
          CACATGCCCTTGAAAACGGTACTACTGCTGTAATGGTTTGCGGGCGAACATCTTAGTGCA
          CCCCACGTTGTGCTACTGCTCTTAACCACACCCGATAACCTGCGAGGTCCCCCCTAGACG
          TGCACCGTTGCACTATCGCTCGTAATGCCTCCTACAGTGCTAAGCATCCTTCGCAAGCCG

          CCGCGGACGTCAAGTCCTATTTGTTTTTCAACTATCCTCGTGTGCGTGCACTGTTTACAT
          CCGCGAACGTCAAATTCCACATGCTTGTGGACCGTTTCGGTGTGCGTGCACCGCTCTTGT
          TCGCAAACACCCGTTTTCATATACTCGCAAAATTTTCTGGAGGGCGAGGATTGATCGTGT
          TTGTGGGCGCCAAATTACATCTGATTACGAACATTTTGGTCATGCGTACACTGTAAGTAT
          CCGCGAACGCGAGGTCGCTTAAACTTGTAAGCCCATCTGACGCGTGCCCATCATTAACGC
          CCGCGAGCGTCAGAGTTCATAGGCGTGCAAGCCTTCTAGCGGCTTGTCCACCGTCAATAT
          ATGCGAAAGCATACCTGCAAACCTCCGGGATACGTCCGAGGGAGAACCAACATACCTAAC
          CTGAGAATCCACATATGCGAATGACAAGAATCGATCCCCATGCAAGTTACTTAATGTTTC

          GGTATTGTAGGAGCTGCGCAACATTCTGCCTCGAAGCCAGGAACCTACCACAAAACAGTA
          GATGTGGCGGGTACAACGCCTAATGCTAATTCGAAACAGCGGACTTAAGAAGAATCGGAA
          GATGTGACGAGCACCACGTTAAAACATATCCTGGCGCAATGGACCTACGATGGTCCAGAA
          GTCGTGTTGAGTACTACGACGATGCCCATCACACGGAAAAAGAACACCAGTGAATCTAAA
          GGAGAGATGGGGCCCGCGCCAAATATCCTTCAGCGGTAGGGGTTACACGACGATCCAGCT
          GGTGTGGAGGGGAACCAACCGTATCCAACCTTGTAGCAGTCCGTTTTCAGCGAACCCATT
          AGCGTGAAGCTTCTGAGGTAATCTCATGCCCGTTAGCCGAAAGCATGCAGTGCTAGAATA
          GGCCAGAGGTCATTAGCCTAACCTCGTGCTCACTAGGTGGAGGTTTACAGTACTTGATTA

          TGGGCTCGCCTCGTGTCTATGTACACTAATCCATCACCGTGCTGAGTCGGTAATGACAAG
          GAACCTTGCTTTGTGGTCATGGAGTCCAGTCAACCTCGGCGCTAAGCTGCACGTGACCAG
          TGGATACGCTGTGTGGTTGCCCACTCTAATCCTCCGCGGTGCCAAACCGACGATAATGGG
          TCAACCCCCCTCGTGGTTGTGCCATTCCCTCTGTTAAGTCATTGAGCTAGCTATTTTGTG
          TCAGCTGACTGAGCGACTAGGTGCCTTATTCCGCTGTATCATTAGCCAGGGTATGCCAAT
          TGGGCCTGTTAAGAGGATAGGTACTTTACTCTGCTGAGTAAACCGCGCGCGTACGTCTAA
          GGCACCCTAGCCGGGGCGACGTTTGTCACTCAACATCATTAGAGACTACAGCACACCACT
          TGCACACTAGTTAGGACGACGGGTTTCGCCCAGTGCAGCTCCTCGCCACGGCAAGCAGCT

          GTCGGTCGTTTAAGCACCGCTAATGCGCTCCAAGATCAACAAAGCTCCTTCAATGGACAG
          GCTAGCAATATATACACCCCTAGCGTGTCAGAAAGCTATGTAATCAGTCGCAATGTACAG
          GCCGAAACTATAAGCACAGCCGGTGTGCAGGACGTGCACTACATTAGCCACAATAGGTAG
          ATCGGAAACAGGAGCTCAGAAAGAGTGTTCGAGAGACAGTATGCTATTTGTGATGGTCCG
          GTCGGCAGTGCCTAATCAGTGGTCGTGCGAACGTGTCGTCGAACTAGCAGCAACAACCGG
          TTAGGCAGTGGATAACCAGTGTTCCTGACAAAGCGTGCACGTACTAGCTGCGATGACCAG
          GGGAATTTCACCAACGTAGCAGGCCCCAAGCTGCATCGTCAATGCCGCATTACAGGTAGA
          GGGAATCTCGCACGTGTTGCCGGTTCGATAATGGATTGGTAAAACTGTTGCTTCAATTGA

          TCTACATCTAAAAGGACCGAACGCAAGCAAAAAAGTCCGAACGCGGCTAGACCGTCCGCT
          CAATCACGCAAATGGGTCGAATGTAAACCGAATAGCGAGAATATTAGCAGTCCGTTCGAT
          TGTATACCGAAATTGATCGATTGTAAGTCGAATTGTGGCAAGGCTGAGTGTCGGGTGACT
          CCTACTCTAAGAGGGGCCGAATGCAGACAAAGTCGCTACACCGCTGGTAACTCGTTCACT
          CTAGCGCTAATATGGGTCGCGGGTCAGTGGAACGATAAAAACGCTGGTGATCTCGCTATG
          TTTACGCCTATATGGGCTGCGTGCCGTCAGAACAGTAACAACGTTGGTAGCTTAACTACA
          GCTGATTTAAGATGACCTCACCTCTTGCGAAGTTAGGATAACTCAGCTAGTTCCACTTTC
          AATAACTCCAGGCGGCCCTAGCGCTAGTGTGCAGAGGGCGGGACCGTTTGTTTCGCCCTG

          CTGCAGTTCACCGACTATTACAACGAAGCTAATCGATTACAGTCAGTCACGCTCCGCTCC
          TTGATGGCCATTAGTCGCGCTATCAAAGCCGGTAGATTTTGATTAGTTCCGTCCCAATCC
          CTGTTGTTAACATACTATTTCATCGGAGCTGGTCGATTATGACTTGTCGTAGCCCTAGCA
          CTAGCGTTCACGGAATATTTGATTGAAGCTGATCGCTCTCAACCTGCAATGTCTTGCGCC
          CTGCCGCTCTTAGACCTTTCAGTTGAAATCGATTAACGCTCAATCGCTATGGCTTGGGAT
          TGGTTGCTTACCATCTCTTTTATTGGAGCAGGCTCACTTCAGCCTGTATTCCCTTAAAAA
          ACGTTCTTATCTAGCCTTTCTCACTATTAGAGGAGTCCTCGCTTAATGGTCTCCCTAATG
          ATGCCGCAATATACCCCAGAACAATAATCCTGATGCGTTTACCTATTTGTGGTCCCAGAC

          TAAATGATACGACATTCATTCGGCAATTTAATGTATCACGCTTTCCGAGAGCAGCATGCC
          TAGGTGATACCATCTATACCTGGTAATTAAATTTACCGCGCCTTAAGAGGGCGACGTATG
          TAGATGCTGCGGGTTCCGTTATACACCTAGACATTTCGCACCCTCAGGGTGCGCCGTCTC
          TGAACGCCCCGGCGTCCGTTACACAACCGGGGTTACCACGCATTTCAACGGCGACGTATC
          CGAACGCCCCCGTTTCCACTGAAAAGCGGGTGGCATCACAGTCTAAGGGGGTGACGTAAC
          CAAACTCTCCCAACTGCACCAGGCAGCTAGGACCACCAATATTCAACGGGATGATGTGTT
          CAGGCGTCTTTTACCCGACTGGGTAAGTTGTGGATATCTACGATTAAGCTGTAGAGCAGG
          CAAGCATCATGGTCTCTATGGGACCAACTGTAGTTGTACACTTTCAGTTTACATAGAATA

          CATTGGCTAAAAATCCTCATTTGATGAGAGGACGCTACAA
          CATTGGTGGGTATTCCACGTTTGGTGAGAGAACGCGGCGA
          CTTTTATGAAAATTCCCCGCTCGATGAGGGAACGCGGCGA
          CACTAGTAAAGTATTCGGATCTGGTTAGAGAATGCTGCGA
          ATAGCATGGAAATCGCGCGTACAGTTTGAGGATGAGGTGA
          CGAGGGAATAAATCATGCACGCAACTAGAGCGTGCTGTGC
          CCTTGGTACAGGTGTGGCACATGCAAGGAGTTTCCTCACG
          CCTCTGCAAAAGCGTAATGGGTGTTTGAAGCATACGAAGG

