 8 1000
t1        CTCTCACTGGGTTGAAACCTTACCCTCTTATCCACCACTGTCCTGAGCTAAAGGCTTAAC
t2        CTCTCACTGGGTTGAAACCTTACCCTCAAATCCACCACTGTCCTGAGCTAAAGGCTTAAC
t3        CTCCCACTGGGTTAAAACCTTACCCTCAAATCCACCACTGTCCTGAGCTAAAGACTTGAC
t4        TTTCTAAAGGGCTGGAACTTTATACTCAGTTGCATCAATGGTTTGGGCTTAAGACTTGAC
t5        CTACAGTAGGGTGGAATCCCCATGTTCATAGATGTCTATGAATTGGAGAAGACGCTTATC
t6        TTACACTAGGACGGGAACCCCAAGCATACAGGTGATTTCGATTTGAAACAGCTGCCTACT
t7        TTAAAGCGGGACTCACCTCCAAGTCTCAGCAACGGAAAAGGGCCGGCATAGCAACTCCCC
t8        TAGCTTCGGGATACATATTGAGAATTTGCCACCAGAGGTGAACCGATTACGAAGTCCTAA

          CTTTAACGCCTCCTGTTTGATTCGCATGCCCAGTCACGAGATTTGCTACACCGTGAGATC
          CTTTAACGCCTCCTGTTTGATTCGTATGCCCAGTCACGAGATTTGCTACACCGTGAGATC
          CTTTAACGCCTCCTGTTCGATTTGTATGCCCAGTCACGAGATTTGTTACACCGTGAGAGC
          CTCTCACGCTGCCAGGTTGATTCGCATGCCCAGCCACGAGATTTATTACACCGTCAGCCC
          TCTAAACGCTATCGGGCTTAGCCGCATGTATGGCTGCGCCAGCCGTCGCGCTGACCGAAC
          TTTCCACGTGATCGGGCTCATCTGCACACCCGCCCGCGACGATCGTCGAGGCATCAAGAT
          CTTTCCCCCTTGGTACATAATGTACACATCGCATGGTCTTATTCGTTATGCTTGCGACCC
          CCTCCCCTCCGTTCGACGCATCTGGACGTCGAGTGATGGTACCTGATATGCCTGTTGCCC

          ATCCGGGTGGAGCGCGGGAATCGTTCTGCACTGCTGTGAGAGGCGGGGTCAAGTTGTGAC
          ATCCGGGTGGAGCGCGGGAATCGTTCTGCACTGCTGTGAGAGTCGGGGTCAAGTTGTGAC
          ATCCGGGTAGAGCGCGGGAATCGTCCTGCAATGTTGTGAGAGTCGGGGTCAAGTTGTGAG
          ATTTTGACGGGCCGCAGGAATTGTTCTGCATTGAAATGAGAGTTGGAGCTGAGTTGTGGT
          ATTGTAAGGGGTCAAGGTAAGCCTCAAAAACTAGGCTGAAAGGTGGGACTAAATACAGCG
          GCTGTGGCGGGCCGAAGCTAGCCTCATAAACCAAGGTGAAAGGTGGGATCGGGTATAGCG
          GCTTAGCGATGCTCTACCATGGGCTTAACCCGAGTACCACTGGTGATGCACGGCCCAGTC
          ACTTAAGGAGTATTTTGAACCTTTCCCGTGCGATTGTATCTGGCGAGACATGGCTCTCCT

          CCATGCCTGTGCCTCGTGGACGGAGACAATTTGACGATTACGGTATTCCAGAGACACTAT
          CCATGCCTGCGCCTCGTGGACGGAGACAATTTGACGATTACGGTATTCCAGAGACTATAT
          TCATGCCTGCGCCTCGCGGGCGGAGACAATTCGACGATTACGGTATTCTAGAGACTTTAT
          CCATCCTCACTCCTTGAGGGCACAGACAATCCACCGATTACAGCATTCCAAAGACTCTGT
          TTACGACTGGACCTGATGTGGACAAATCTTCTTCATGGTGTAGGATCTCATCGACTTGAG
          ATACGGCTGGTCTTGATATCGACAGCCTATCTCTAAGGCGTGGTGCCTCATTGGCTTCAG
          CGAGTGTCGTTTCTGATACTATATAGCACCCTTACGACCCTAACGCGTTTTAGTGGTTTT
          CAATTGTTGAGATAGTTCCCATCCGATGGCTGCTTGATTTTGACGCCGTACAGGGTCCAT

          TCAGAGGCGTGGAGATGCTTAAGAGGTTCCGCCGGAGGTGGCAATTATAGATTTGTCGGC
          TCAGAGGCGTGGAGATGCTTAAGAGGTTCCGCCGGAGGGGGCAATTATAGTTTTGTCAGC
          TCAGAGGCGTGGAGATGTTTAAGCGGTTCCGCCGAAGGGGGAAATTATGGTTTTGTCGGC
          CCTTAGGCGCGAAGATCCATTCGTGGTACCACGGGCGAAGGAAGTTATTATTTTGTCGCC
          CGAAGTGGGTGAAGGTTCTTACGTAACGCAAAAAAAATCAAGAGTGATTGTCTTGTTGAA
          AGAAACGAATCACACTCCCTACGAAAAGCCATATAAATCTAGAGAGAGAGCCTCGTTGAT
          TAAAAACTTCCACATCGCTAGCCCGCATCGGTGCGATGGCCATACTATAATTCCGCATAC
          CCAATTGTTTTATAGCAATCACGCGAGATATTGCAGTTACTAGGTGGCTAACGGATGGAC

          AGGTAACCTGGAGCGGGACTCTGGGGACTGGTTAAGAGCATAGGATTCCAGGTAGGCGGC
          AGGTAACCTGGAGCGGGACTCTGGGGACTGGTTAAGAGCATAGGATTCCAGGTAGGCGGC
          AGGTGACTTGGAGCGGGACTCTAGGGACCGGTTAAGAACATAGGATTCCAGGTAGGCGGA
          AGGCAACACGCAGAGGAACCGTAGGGACCGTTTAAGAGCAGAAGCGTCCAGGCAGGAGCC
          GACCGGCTCGAAATGGGCTTGCTAGAGGCGCCAAGGAGCGTCCGAATGATGAAGCGAGGC
          GGACATCTCCTAATAGGCTTCTTAGAGGCTTCAAGATGCTTGCATATGATGGCACGCGGC
          ATGCCTCTAAGAGACGAAAGTGAAAACCGATTACATATTGGTTAAATACCAATCAATAGG
          GAGCTTCACGGAAAAGGGTTCAGGAGAAGAGTATAGAGAGACCTAGAATCGATAGTGGTC

          CAAAAGGCTGGACTCGTCTCATGAAACGCAACCGATCTCTCAGTGCCCATTAATACAGCA
          CAAAAGGCTGGACTCGTCTCATGAAACGCAACCGATCTCTCAGCGCCCATTAATACAGCA
          CAAAAGGCTGAACTCGTTTCATGAAACGCAACCGATCTCTCAGCGCCCATTAATACAGCA
          CAAAATATAGATCTCGTTACATGTAACGCAACAGATCTCTCAACGCTCATCCATTCAAGA
          TCAAGGATCAGAATCATTAAACAAGGTTTCACCTAAAACTCTTGGTAGATTCCAATATTG
          CTAAAGACAGGAGTGGTTAAGATAGGTGCCGCCTGAAACAATTGGCTGAATCAAGCAAAG
          CAAATGCTGTAGCGGCTGATCCCAACCATTGCCCGATAGTACCGATTATAAGACCTTAGT
          CAAAGAATGGCGGCGGGAACATAGCCCCACTCTAGCCGGTGTCGACGTTGCAATCTAGTG

          GTGCACTGCCCGGTGAGCCGGCCAGTCAATACGATAAAGGTACCGCGGATTTCAAGCTTC
          GCGCACTGCCCGGTGAGCCGGCCAGTCAATACGATAAAGGTACCGCGGTTTTCAAGCTTC
          GTGCACCGACCGGTGAGCCGGCTAGTCAACACGGTAAGGGTACCGCGGTATTCAGGCTTC
          GTGCACAGACTGGTGGGCTAGCTAGTCAACAGGACAACGATACCGCGGTTTCCCGGCTTC
          GTATTCAGACAGGCGCACAGGAAAATGTTCACATTTCGGGCGTAGCGATCATTGAACGTG
          GTATTCCGGCTGGTGTATGGGAAAGTGCCCACGTTTCGAGCGCAGCTGTCTCGAAATTCG
          GTCCAAAATCTGGCTAGTAGGACGCCAAATCCCTAAATGATATGGTTTCACTCGTAGATG
          ATCTAGGATCCTTCGGATGGTGGAGCACGCCTTCAGTTGTAGCTGCTTAATTTAAATTCC

          TGGTTCACGAAATCTCCTGTGTGCATTAAGGGTTGAGTGCACCAGAATTTTGAGTAATTC
          TGGTTCACGAAATCTCCTGTGTGCATTAAGGGTTGAATGCACCAGAATTTTGAGTAATTC
          TGGTTCATGAAATCACCTGTGTGCATTAAGAGGTAAATGCACCAGAGTCTTGAGTAATTT
          CGGTGCATGAAATGTCCTGTCTACATCGAGATTTGCGTGTACCAGAGTTTTGAGTAATTC
          TGGTGATTAAATGGCTGCGCACCCGTTGAAATTGGAACGTATAAGCGCTTTGTCCACGGC
          GGGTGTCTGGCTCCCAGAGCACTCGTTGAAATTGACACGTGTGTGCGCTTTGCCCACGGC
          TGCCCTTCGCAATACTAACTATCGAGTAAATCTCGAGGGCAGTGGTGCCGCTCGCGTCAT
          TGCCGTACGTTATTTTTATTGTTACTTAGTACTCGATCGCTGTGGTTCCACGCCTGTCAT

          CCGCAGCTAGCCAGTTGACGGAATTCAAAATGAGCAACATACCCCCATTGCCCATACAAG
          CCGCAGCTAGCCAGTTGACGGAATTCAAAACGAGCAACATACCCCCATTGCCGATGCAAG
          CCGCAGCTACTCAATTGACGGAATTTAAAACGAGCAACATACCTCTCTTGCCGATGCAAG
          CCGAAGTTAGCCTATTGACAGAATTGAAAATATTCTGCATACTACCCTCACCGGCACCAG
          CCGCTGTCAGCTTTCTGGTGGACCAGATAACCTACATTACCTAACTCTTTCCAATGTAAG
          CCGCTGCTAGGTTAAAGACGGATCAGACAACTTACAATGTGTTGCTCTTGCCAAATCAAG
          GTAAAGTTCGAACAGTTGTCTTAACCAAAACGGATAGCACATCTTACGCTCACATTCGTG
          GTTCAGCCCGCATAGCTCTCCAAGCTTAGTCCGGTAAAAAATTAACGATGCGCATCAGGG

          GTACTGTGCTTAATAAGTAGGTGTAGTTCTTCGTCGCCCATGAACAAATACCATGAGTCG
          GTACTGTGCTTAATAAGTAGGTGTAGTTCTTCGTTGCCAATGAACAAATACCATGAGTCG
          GTTCTGTGCTTAATAAGTAGGCGTAGTTTTTCGTTGCCAATGAACAAATATCTTGATCCG
          GTACCGTGATTCATTAGTAGATGTAACTCTTTGTCGTCAGGCAACGGATTCCCTGGTCTG
          GCATGGTATCCCCTAAGCGGCTCCAGTCTACTATCACTCCAAGACAAAGGCGCCAGACGG
          GAATGATGGATACTACGCGACTTCAGCCTATTGTCATTGCAAAATAAGGGCGCTAAACGA
          GTCGAGTAACGTTAGGAGAGTCTTAGTGTCTACTCACCCCCACTCCTTCAGGCTGGTAGG
          GCCAAGCGATATTCGGACCAAACTTGCATCAACATAACTCTGATTTGGGGACTCGGCTAA

          AGATTTATGATCGTTCGTCCGTATGCATCCAACCGAGCCCTGCCCAGTGAGTTGCGGTGA
          AGATTTATGATTGTTCGTCCGTATGCATCTAACCGAGCCCTGTCCAGTGAGTTGCGGTGA
          AGGTTTATGCTCTCTGGTCCGTATACATCCAACCGAGCCCCGTCCAGTGAGTTGCGGTGG
          AGATTTGTGTAACTTGGTCTGTTTGTATCCAACCGGGCGCAGTCAGGCGGCTAGCAGTGG
          AGATCCATCATAACAGATGTATACCTGACTAAACTTATACGATCTGGTTACAATACACGC
          AGAACTATCAAGTCAGATGTGCATATGTCTAACACTACGTGGACAGGTCACGGCCTGCGC
          TATTTCGAAGCAGAACTCAGATGCCGCTCCTATAATCCCTGGCCCGTAGTCAACATGAGA
          TGTAGCGACGAACTCTCCAGATGCCACCCCAAAAGGCGCCAACACGTAGTCGATATAGAA

          GCATCAACAGCCTATTCGGGTATAACATCGAAAACCAATCCCTTATAGCAAGCATCTAGC
          GCATCAACAGCCTATTCGGGTATAACATCGAAAACAAATCCCTTATAGCAAGCATCTAGC
          GCAACGACAGTGTATTCGGGTATAACATCGGAAACAAATCCCTCATAGAAAACATCTAGC
          ACATTAGCGGTTTACCCAGGTGTAAGATTGGATACTAATCTCTCGTAGCCAACGTCCAGC
          GCCACATCAGGAAGCGCGGACACGACGCTAGTAAGGCATTCTTTAAAGCCTGAGTCCAGG
          GCTCCGCCAGGACTAGTGGGCACAGTACCAGTAAGGCACTTCACGCAGCTTAGACCTAGA
          ATAATTAAATGTCTTGTAGTCGGCACGGGGCGGCCGCACGCCGGAGTATTTGTGCACCAA
          GCGAGCACAAGCCCGGCGGATCAGGCCCCCGGGGTACTGGCTAAATAGCTGGTGCAACAC

          TTATAAATTGTACCCCCTTGGGTTACCCTGTACCCCGGGCTGTGCTCTCATGGGTTGAGA
          TTATAAATTGTACCCCCTTAGGTTACCCTGTACCCCGGGCTGTGCTCTCATGGGTTGAGA
          TTATAAATTTTACCCCCTAGCGTTACCCTGTACCCCAGGCTAAGCTCTCATGGGTCGAGA
          TCATCAAATCTAATTCCATGGGTTTCACTGCACTCCGGGCTAAGCTCTCATTGAATTAGA
          TTTTTAAGCTTAGCTGCTGGGGTTTACTCGTTCTAAAGGCTTAGATATAGTGTGCAGACG
          TGCTAAAGCTAATCTGCGGGAGTTCTGCCATATTAAGGACCTAGAGATATCGAGTCGATA
          CTCACGTGTAAAACGACCTGAGGCCTAACCAATCCCTCTAGCGCCGTCAGCTGGGCAGAG
          TAGATGTGCAGTATTAATTGCGTTCCGGTCTGCTCCACTAACGACGACAGTTGGGTATTG

          AAGAAATTACAATTCAGGCAGCCCATTTGCTATGAACCTCCCTCAGTTATTATTTTCAGA
          AAGAAATTACAATTCAGGCAGCCCATTTGCTATGAACCTCCCTCAGTTATTATTTTCAGA
          GAGGAATTACAATTCAGGCAGCCCATTTACTATGAACCTCCCACAGCTATTATTTTCAGA
          GAAGAGGTTCAATTTAGGTGGCACATTAGCTATAAATTACCCTCTGTTAATAAGCTGGAA
          GAGGGAGCACGACCAAGGTAGCCCGTCAGCTAGGTCCCCCTCCTAGTCTCCCCAGAAGAG
          GAGGGACCAAGACTTAAGCAGCTTACCTATAAGGCCACTGGCCTCACATCCCACGTAGGA
          TAGCAAGCCAAATCTCAGAAGCCTTAATGTCGTACTTCCACATCACCTCTTAAAGCAGAT
          CCATTCGCATACCTCCGGTGAAGCCAGAAGGGGTCATTAGCGGAGCGTTCGATTACGTGA

          CGGGAGACTTATTCTCCCTATCAAGTTTCACTCAGTAGACGCGTAGACGGATCGGTATGT
          CGGGAGACTTATTCTCCCTATCAAGTTTCACTCAGTAGACGCGTAGATGGATCGGTATGT
          CGGGAGTCTTATTCTCCCTATCAAGTTTCACTCAGTAGACGCACAGATGGATCGGTATGT
          TGGGTGTTTTACTCATCCTACTAAGGTTCACCCTATAGAAGAGGAAATGGATACGCATGT
          TAGGAGCCTCCGGCAATTCTCCAGTTTGTGGCTCGTAGATATAAAAATGGATACATATCT
          CAGAACCCCTAGATACAGCTCTGGTCAGATTCTCACAGATATATGGGCGGATACATGCCT
          ACAACGGATCCTTTGTTGTGCGGGCCTATACTTTACAAACTACAAAGGTGATGGTACTGT
          GCGATGACTACTGAAAAAGCCGGGATTATACACCAGCGACTCTTAGTGCCACAGCAATCT

          GTCTTGCCATCGACAGTTAGATAGCAAAGTTTAGGTGCCC
          GTCTCGCCATCGACAGTTAGATAGCAAAGTTTAGGTGCCC
          TTCTTGCCATCGTCTGTTAGATAGCAAAGTATAGGTGCCC
          CCCACGTTATCGGTAATTAGATGGGGAAGTTTGGGCGCCT
          CTCCAGTCCATATTTCTGTTTCGGGCACAGTCACAGGCCT
          TTCCAGCATCAAATTGTACACCGGGCACAGTCGAGGACCT
          TACTGACTCGAGGCGGCCCGGCGGCCTCTTTAACAATTTT
          TAGTCATCGTGTGTGTATTCGCGGTAGCCTCAGTAGTTTT

