 8 1000
t1        GTTTTACTTGAATAGGACCCCGTCCGAACAGGCGGCTACTCCCAACAAAGGACTTACACA
t2        GTTCTCCTTGGGGAGATCAGCACCCGAACATGGAAATACCCCAAATAGAGGTCACAAAGG
t3        GTTGTAGACAAGCGTGCCACTACCCCGACGCGGAGACTCTCAGAGCAAGGGGCCCAGCCG
t4        GTCTTGGTTAGGTCAGTCAGCATTCAGACAGGGAAGTACATCCAATGGAACACTTAGATA
t5        GCTATACCTAGGTGAGAGGCTAATTGAATAGGATGGGACTCTGTACCAAATGCGTCTGCT
t6        GTTTGAGTTAGATGTGAGATTAATCAAATAGGATGACGATCCGTACTTAATGCTCCCGTT
t7        GTTGAGGCGGGCCAAGCGCACAGACCACAACGCAGACATAACAATCGTGCGGGTCGGCTC
t8        GCTCGGGTCGGCCAAACAAACAGACTCCAAGAATGACGCGGAAATCCGGAGGCTTGAATG

          CCGATATTATGTATTAGGTTTACATAGCTCCAATTTCTTTTTTCGGGAGTGAATGCGATA
          TTTTCGAGTAGCATTAGGTTTAGCCGGTCGCAGTGGGGTCCTTTCGGGGAGGTAGAGGAG
          TTGCCGGTGAGCACCAGGCCCAGATTGGCCCGATGGAATTTATTCGAGAACCTCGTGGGT
          CACATAGTCTGTAATCAACTCGAGTTGACCTAATCCGGTTACTCAAAGAATAACGCCGGC
          AGCATGGCTCAATGTTACCTGGAAAATAGTAGCCACGTTGCGTACAGGGACATCGGGCTT
          TGCATGGTACGATGTCCGCTGGTGAATAGTCTCCATGTCGAGTACAGGGGCATCAGGCTT
          CTCCATGCGTGTAGCCAGACAAACTGAGGTTTTGGGTCATAACTCCGACGGGCAGGGAGC
          ATCCGAGGGTGTTGAAGTCTCCACCGACGTATCTTCAGCAGAAGTGGAGGCGTAGGAGAC

          GATCGCGGGGCAAAATTGCAGTAAAGGCGACTCACAAAGCGTTTTGGGTCTCCTCAAACT
          GATTTGTGGGGTTGGCCCGAAAGTAGACGCCCAATAAGGCGTCCTGGATGACCTCGCATC
          GCTCTGTGGGAGATGCTTGAGCGTAGGTGTCTCAACAGGTGTTTCGGGTCCACTTATCGT
          AAACTGTGGATGCACCCAGTTTATGCGCATCCCGTAAAGATGTCTAAAGTTGTTAGCTTT
          CTTGTGTAGACGCTATCTTTTGTCTGTAGGCTTATCAGTAGGCCTAGGGTCTTAAGTGAT
          CTTGTGTAGACGTCCTCCTTTGTCTGTAGATTCACTAAACGGCCTGGGGTCTTCAGCGAT
          GGGATTTGGACGCTGCGATCCTATTAGCGCGAAGATTAGCGGTCGGGTTGGTATTTTGAT
          AATTGCCGGGTAGTGCTATCTTTACGATGTCGTGAAAACCAGCAAGGAATCCGTTTCACC

          TCTAAGAAACCGGTGCTGACGCGGAATGCGACCCCGTGGTGGGGGCGCTCAAGTGCTCCA
          ACAAAAATATCGACGCCGAAGCAGAATGTGCTCCCGCAGTGAAGGCGCTTCGAATTATCA
          TATTGGAAACCGGTACGGACGTCAGGAGTTCTCCCTCGGTGGGGGAGTTGCAAGATCCCG
          TACGAGCAATCAATGTTGGGGTCCCGCATCCTGCCTTGAATGCAGTGCTTTATTGTATCG
          TTGCCATAGCTTAGAGAGTAGCCCAGCAAGGGAGTGCCCAGGCGGGACCCCGAGACCTCG
          TTGCCGTAGCCCAGATAGCATCCCAGTAACGCACCGCTTTCGCGGGATCCTGAGTCCCCG
          CTATTTCTTACGCGCAGGGAGATGAGCTATACGCTATAATTACTAAATCTGGCCAAGATG
          CTTCTCCTCTTTTAAAACGTGGTCACTTCTGAGCTATAGGGACCGGCTTCGGCCAAGGTG

          GCCGTTGGACCGAACTACGTGCACTGCTAGGCTATGTGCAGGTAACCACCGGAACTTAGG
          GCTACCACAATGAATCGCGCATAATTCTAGGTTATGCGCACGTGTATAAAGGTTTCCGGG
          GTTACCGCACCGTATCGTGTATGTGGCCAGGCAATATGCGGGATAGAAAAGGCCTTCAGA
          GCAATTGAGTCATAGGCTACCTGTTGACGCGACGCGTAGAATCAGGCAGATGCTACAAAT
          CCAGCCAGTTCTTGATCTTCGTGGTCTCGGGCAATGCGGAGGAAACTTAAAGTGCGTATA
          CTCGTTAGTTCTCGATCCTCGTGAACTCAGGCAATATGGAGGGAATCCAACATGCGCCTA
          AAGGACGTTTTCTGCGACACGTGGCGCAGGATCCTAGTCTAGCGGTAACGGGCAGTTGTG
          ACGTACGCACAACACCACTCGTGGTGACGTACTGCGACCCACAGGCCACGGCTACATGGT

          TGACCGTGAGCTTAGTGTGTTGTTTTTGGTTGTAAAGCGGCTTTGAGTTGATCCATACCC
          TACCTGTCGGCCACGTGTGTCGCCCTTTGTTGAATAGACGCTACGAATCTGTTTGATCGC
          TGCCTGTAGGGTGAGTGAGTCGTTTTTGGTTGTACAGAGGTCTTAAGCTTATCTCTACAC
          TATTAGTTGGCCCGGTAAATCGTTTCCCGCCGCTAGGGAGCGCTAGGTCTACCCTCACAT
          TGCATTCAGGCGCGAGTGGGGCTACTGTGCTACAGTGCAGCTGTGAATAGCCGCTCCTTC
          GGTACTCGGGCGTAGTTGGCGCCGCCGCGCCACAGTGGGTCCCTGGGTGGCTATCCCTTT
          GATATCATGGCCTCGGGGGCGGAATCTTGTGACGCTGAAGGCCACAGTGCCTATCCATGC
          GGTTCAAGGGGGTCGTAAAAATCACTTCGTTACGCTGAGGGCCACAGCGCGTCCCTGTGA

          TCCCTGGCGAGTGTTCCAGCTGCTCGAGACCTTAGGCAATCCAGTCCGCGAACCATTCGG
          GGCCAAGCGGATGCTCCTGTGGCCCAATTGCTTACCAGATCCGCTCGGTGCGCCGTTGGT
          TACTGGGTGAAGGACCCTATCGACGGGGGCCCCGTAAAGCTCGGTTAAGGTGCCTGACGT
          GACCGAGCCAGTGACACCATTGATCGAGCCTGTGAGAACAATAGCTGGGGTGGCTTCATG
          AGCTGCAAGACGCGCGCGAATGATTGAGTAGTCATTGTGCCATGGCCACAATTTGATCGG
          AGCTGCTAGGCCTGCGCGAATAACTGAGCAGTCATTGAGTCACGCCGGACTTTTAATCGG
          ACCTCAACGGAAGATACCTGGCCCCGAGCGTCGACGGTCTTGGCCCAAAACTATTCCAAG
          GACCGGACGGTCAACGCTTGTTATCGACTGGTAACGAACTTTTTAGAAAGTAACTGTGAG

          TGACAATAACATGTCGAAGACGCCTAGCGCTGCGGCAAGTCGGACGGGCGACTTGGCGGG
          AGCTAGTGGTTTGATGAAGATGACTTGTGGAAAGGTACGCCGAATAGACGGCTTGCAGCA
          CGTCGAAGGCTTAACATTACCACCTTGCGAGAACGCGAGTGAAACAGTTGGTCAACAGTG
          AATTAGAGGTCCAACTTATGTGGCTGACGAAATGGCGAACTAGATGAGTGCTTCGAGTAA
          GGTCCAAAATGAAAATTCGAACGCGACCGAATCGTTCACGTGGAATCGTTTTACAATAAG
          GGTCAAGGTCGAAGCTTTGAACGTACCCTAACCGTCTTCGTCGAATCATCTTGCAATGAG
          ATAAAAGATTACTAAGTTTATAACTGACTTATGCGGTGGATAGCCGGTATCTCTTCCGGG
          ATTTAGGACTGCCAATATGGAGGCATGCCAGCTCGGTGGCAAGTCAAACCTTATTTCGAG

          CTCTATCAAACGTTGCATTAAGCTACCTGAGCCAAGTGACCACCCCTCGAGCTAACCTAG
          CTCTTCCAAGCGATCTATCGGACCATCTATGGTTTGAAAGGACGCCTACCGTCAATTTAT
          TACAACTGAGTGTCTCATTGGGTCACTCGAGTTCAGAAACGGCTCTTATGGCTACCCCCT
          TGCCGCCAAGTGTTGCGGCATAATATCTGCGCTCAAATTCCATCTCCATAAACCTTACCT
          TTCACCCAGGCCTCGTGCGGCATTAAAGTTGACAACATGCAATTTGCACGGTTGGCAATC
          TTCAACTAGGCATTGCGAGAAACTAAAGATGAAAATATGCAGTTTGCGCGGTTGCCGATC
          AACTGTCTGGCGTTGAGGTCTAAGCACAGCTGCCTGTAGACACCATAACTACCGGTTAAT
          GTCTATTTTGTGGTGGAACGTAGGCATTGTGTGTATTAGGGATTTAGTTCCTTGGGAGAT

          AGTGCTGATTTGTAAAACGTCCGGAAGAATGAAGAGGGGACAAAGTTATGATTGGCTAAT
          GGAATACATTTGTCGATCCCCCGGCGGCTAGACTAGCGGACGCAACTCCGTCTGGTGACC
          CTCAGTGCCTCGTTTCCCCTTTGACAGCGTTACGTATGGATGAAGTCACGTTATGCTGCT
          CGCACAACCTCCCCTACGTATTGGCTGATCAATGGACGGACCTAGTTCCGGCTAGCACCT
          CATGGTGTCTCATCTAGATTTCAGTCGTAATACGAGCGCACCCAGCGTTCCCCGATAGTC
          AGAGGTGCCTCATCTATCCCTCGGCCGTAATATGTGCAAGCCCAGCGTTCCCAGATGGTA
          TGGGCCTTCTGATCCACTACGCTGGGGTCCCTCACGAGGATGGAGCCTATTACGGGCAGC
          TGATGCGCTTAACTAGCTCTCTTACAGCACTCGCCGTGGAAGGAGGTGAGAACGGCCTGC

          CCGAGTAAAATCCATGTTCCCAAAAGGCTCCGGGCGCATAATCAGTTAAGATCGGCAACG
          CCCCGTAGATCCTACACTTCCCGGATATTTGAGATCCGTTGTTCGCATCGGTTGAAAACG
          TTTGTCCCTATACCTATCCTTCCAATACTTGAGGTGCATCATCTGTTCTAATCGGTGAGG
          CCACGCAACCTGCGCATGCTGAAATCGCTTGCGGGGAAACTTTCCCCCTAGTGAACAGCC
          CTCAGCTACATTGAGATCCCGTAGCTGCCCTAGTCGTAACAACGCCAACGAGTGCAACGT
          CCGAGCTGCATTCAGATCTCCCGGGTGCACTAATCGTTATAACTCCATCAAATGAAATGT
          CGTCGCAATTCCATCTATTAACCGACCACACCAAGGTCCTCGTTGCTTCCTCCGGAGACG
          CGTTGTCATTTTATATCCTAAATGATACGGTTGTTGTCCTAATCACTCCTCTTGGAGAGG

          TACCCACTTGCTAGCTGCATGTGAATTGCGCCCAGAGGCGGGTTCTTCGCGGCCGTAGCT
          CGTCCGCTTGGTTGCTCGAAGTAGTGAACACCTGGGAACGGCCCCTCTCCGACTCTTGCT
          CCTTCCCGTGATTCCTGTGTGCGGTGAGAACCTAGACACACTTCCTCCGAGCATCTTGCA
          TCTTAATCTCATCAATGAAAGCGATGTATGGCTAAAAGCGACCCCCTCACAGATGTCGTG
          CTCTCATCCCGCAACTACACACGGCACGCACTGTATTATGATTCCCGACCATGGGTTGCT
          GTTTCCTCTTCCGGCGATACACGGCGTGTACTAGATCATGATTCCCGACCATGGGTTGTT
          TCATGATTTAGCTACACAGGGCAGAGGGGCACTAAATAAGCCGCAACCGTGAGGGCAATG
          CATTAATCCAGCCGCTGGATGCGACGCGAGCTTAGCTAAGATTCACTCGAGAAAACCGCA

          AGACGTCAGTAATATTTCATTGTGGTTCGTTTTAGCCATATCTGTCGACTCGGGAACAAA
          AGTCGGTAGTAGTATTTTACCATTGTTTGTCATTATAACTGGTATTAGCTCGGAAGAAGC
          AGATGGTTGCAATAATCTACCGTTGCCCGTCATAGGGATCTGTGTTAACGCCAAAGAGCA
          AGGGAGCTGCACACTCCCAACGGGACCCGAATTAAATATTCGAAAGAGGTCACACTGAAT
          CGTAATATGCGGCATTCTATCCCCACCCGCTTCAGCTAGCCGAGTTGACTATAAGGATTC
          CGTTATACGCTTCACTCTGTCCATACCTGCTCGAACTAGCCAAGTCGTCCATACACACGC
          ATTCGTCCGCTGTACCTCGTTAATAGTCGATCTGTGGCACTGCGCCTCTACTCGTGTAGT
          TTTCGCCAGCAATACCCTGTACATACTTGGTCTGTGATCTTATGTACCTATTTGTGTGGC

          ACACTGCATGAGTACCGCCGAGGATTGGCCGATGACGTCACTACCCCACAAAAAGCTTTC
          CCACTGAACGAGGGCAGCCGCTGTTTTACTGACAGTGTTATCTTACAGCAGAAAGGTTCT
          CCGGAACTTGAGGCTGATTTCGGTCTGGTCAACGATGTTATTGTACCGGAAAAATTCCCT
          CCACTGTTTGAAAGTGGCCTGGGTGCGTAAGATTTAACCACCTTCTGCTATAATGTTGCC
          TGCCGGTATCAGCGTAGAGTAAGTTCACGCCTCTATCATTACAACGGATGAAATTGAGCA
          TGCCAGCAGCAGCGCAGAGTAGATCAACGCATTTACCACGCCAGCTGATGAAATACAACA
          TGGTGAATGTTGTTTAACGACGGACACGTATCTTATTCCTGCGGTCGGTAAGACGATCTG
          TTACAGCCCTGCTGCCATGGCGATCACCGACTTGACTTCCGTTGCCAACGAAACGATTTA

          TGCACGGGTAACTAGCGTCCTGCCGCAATGTAACCCCTCTCGTGCACACCTCGCGCATAT
          TATACGGGCAACTGACGTCTCGCAGCCTTGATCCCTCTACCGTGTGCAACTCGGGTATTG
          CATACGGTCAATCGACGCTTTGTCGGTGTGTTACCTTCTTCGTACGGACCAGGAATCTAA
          TATAGAAGCAATTGCCCACCTAACGATATGTGACTTGCTTGTTGTAAAACCCCCACATTA
          CCACGATGTGGTGTTCGATACTACGCAATGTGACCATCTTGTGAGATAATTGCGCTGCTG
          CCTCAACATGGTGTCTGACACTGCGTAGTGCACCGACCTTCTAAGACAATTGCGACGCCG
          CTGCGGAAGCGCTCCGTATTTAACGAAAGGCGGTCGTGCCGCTTTTAAACGAAGTGGACC
          CCGCGGAGGTGCATCATTTACCACCTAAGGAGTTGTAATTGATCAGACACCCAGTGGACG

          TTCACTTCCGTTCCTTACTGCCGCCACCCTCTGTACCTGGTAGTGGCCTATTTAGTACCC
          ACCATTTTCGCAGCAGATTGCTGATCCCTGTCACGTACGACGACGTTTCCTTTTAATCCC
          TCTCTATCCGTACTTAAATGCTGTCACCATTTGTACCCAATGATAACTCGGCTCCTCCCC
          TCCGATTTCGTACCCGATACTCGTCACACTATTGTTAAATCGAAAAGTCATTTCTTTCAG
          TTCGCCCTCTTCGTTGGTTGCTGCCCAGCTAGGGCTACAGTTATCGACCGATAGGGTTTG
          ATCGCTTTCTTTGCCGGTTGCTGCCAAGCTCGAGCCAAAGTCTACGGCTTTTAGGGTTTA
          CCCAGACTTATGGCAACTTGTTTGCGCAGCCTCCGAGGGACGGTCCTCCGAGTCAGTCTC
          TTCAGATCTATGATAATGCGTTTACGCATGCAGCAAGGGAAGGCCCGTCGATACAGTTTT

          GATCGCTGGCCGAACAGATGCATTTCGGGAAGGTTTATGT
          TAGCGGACTTGGCACTCATGGCTTTTCGGGAGGTCTACGT
          CCTTGCTAGTCGCTCACAGATTTCATAGGGAATATTATTC
          TAAGGACAGCTGGACCGTTCAGACACGTAAAGTGTTAGGC
          CAACGCTAATTCCAAGCCAGTTCGCTTTTGGGTACGACTC
          CTACGCCAATCCCAAACCAGCTGGCTTCTAGGTATGACCC
          TAATACAATTTGATGCTATGACTTTATATATGAAGAGTAT
          GAACGCTATCTCGTTCTCTACGTGTTCACACAATTAATGT

