 8 1000
t1        CGGATACAAACCAGGGGCAGTTGTTTGGTTGTGGGCCCTTCGGAAACTAACTCAAAGAGT
t2        CGGGTATAAACCAAGGGCTGTAGATTGATTCAGGACCCCTTGGAAACTAACTCAAAGAAT
t3        TAAATATGTACCAGGGGCCGTTGTTTTATCTTGGGGCCCTCGGAAACTACTTTAAGGAGT
t4        TGGATGTGAACCAGGAGCAGCCGTTTGAGCATGAGGCCCTTGGAAACCAATTTAAAGAGT
t5        AGGAGACCCCCGAGAAAACGACGTCCTTTTTCAGGGCCTTCATGGATGACCTTAACAAAT
t6        CTGACACCATTTCAGTTGGGTCGTCATGTTCCTAGGCCGCAGGAGTCAGTTTAATAGGGA
t7        GGAAATAAGACAGTGCGCTCCTATATCTCCTGAGGATCCGCGGAGCTGATGAGCTTGGAC
t8        AAGGGCCTCCCAGTACGCTAGAATTAACGCTTGATATCCACGAGAACATGATCCAAAAGT

          CGACGGGAGTCGAGCTAGGTTTGGCATGATGGCGTCAGGACATTTGCGATGCAGTGCACT
          TGATGGAAATTGAGCTAGGTTTGGCATGATGGCGACAGGCGATTTGCGATACAGCGCACT
          TGGTTGGATTTGACTTAACTTTGACATAATGGAGTTAGTACATTCGTGGTGCATCATACT
          TGACGGGAACCGACCCGAATTTGACATGATGGAGTTAAGACATTTGTGATGCAATATATC
          CGGCGGAATTTGATCCTGAAGTGAAGTAACGGATCAAGGGCAGTGGTAAACTAACACACC
          GATAAGGAACGGGTTAGCAGTAACCCCAATGAACGGAGAGTACTAATGCCATAATAAGTT
          CAGTCGTAGTCCACTTAAGGATAGTTCGAGTATGCGATACGCTTTGGCGAGTGAAAGCCC
          TATTTGTAGCTCTGAAACGTCCAATGTCTTTGCAGGAGCACGTCAGCGTGGTGGCACCTA

          TTGATACGGTTACTATTTTGAGATGCCAATAGAAAGGCACGACCGGGCATACATTTGTAG
          TAGACACGGTTACTATTCGGAGATGCCACTAGAACGGCACAACAGGGCACACATCTGGAG
          CAGATACGAATACTATTCAGAGATGCAAATAGAAAAAAAGAAATGGAAACACATCTGGAG
          TAGATACGGTTATTATTCAGAGATGCAAATACAAAGGGATGGTTGGGCACACCTATGGAG
          TAGCTCTGGTTAAGGTTCAGGGGATCAGATTATTAGGGCCCAACGCGAATACACCCAGCA
          TCACGACAATTTTTTCCTTGGGACGTTTGTATTTAGATAGTACTGTGCGTATTTTCGGGC
          TATCCATACCTCCAAACTTCGAACTCGATGCTCAAAGGAAGGCACCACACATGTGGTGTT
          GTGCACTTGTTTCTGGCAAAGGGGATGGACTATTATACCATCAACGATGCGATAGGGCCC

          TGAACTGCGGAAGTACGGTTTGCTACCAAGTTTTGAGAATACCGTTCGCGCTTTTCAGGC
          TGAACTCTGGAAGCACGGTTCGCTACCAAGTTTTGAAGATTATGTTCGCGTTTGTCAGGT
          TGAACTTCGGAAGTGCGGCTTACTAATAAGGTTTAAAGACTCTGTTCTCGCTTTGTGGGT
          GGAACTTCGGAAGTATGGCACGCCACTAAATTTTAAAGACTCTGTTTTCGCTTTATAAGG
          AGAACATTTCAAGAGAGACTCGCCACATCGTCCCCCGGACACCTTTTCTGCTGCGCGGTT
          ACCATCGTAATAGTGCTGGTAGACCCTCTGGTTTTGGTCATTTGCGTATGCCTCACGGCG
          GGAATTGTCGCGATTCGGCTAGCTCTGGTGACATTACGCCCACGTACTCGTTCCGCAATC
          ATAATCCCGGTAGCCTGGGCCATGACAATGACGCCAGGCATATGCAATTTCATAGTCCCG

          GTAGCTGGATCTACTCTACCTCGCCCCCTCAGTAGGACTAGATGGCCCGACATAGGACCG
          GTAGTTGGATCTATTCTACCTCGCTCCCTCAATGCGATTAGATGACCTGACGCAGGATCG
          GTAGCTAGATCCACATTAACCAGGTGCCTCAGTGCGAATAAATGGCTCGCAGCGGGATGG
          GTAGCAAGAGCTACCGTTCCTAGCTCCCGCAGAGCGAATGGACGGCCGGACACAGGACCG
          GCGTCCAGTCTTACCTCGATTCATACACCCAGCCCGAACCCATGGACCGATACGAGAGCA
          TCACTTAAGTAATTTTCAACCCTTTCAATCTGTACGAATCACTGACTGGAGTCGTAATTG
          AGATGAGCGGGGTTCTTACTTCACTCCCTCCGAAGTCCCCAATAGTTGCACACAGCGCTA
          GGGTAGACAAGAACTTGATTGTTTTCGCTCCATCCTAACTCAACCCAAATTCGGCTGCGT

          TTAATATCCGATCTCTTTAGGGACTTCTCACTCCATGTCGATTGATTGTCTTCGACTGTC
          ATAATATCCGATCTCTCCAGGGACCTCTCACTCTATGTAGGCTGATTGCCTTCGACTCCC
          TTAATATCCGCTTACTATGGGGGGCTCCCATTTTATGTCGACTGATTGTCTCCGACTGAC
          ATAATAGCCGTCAATTCTAAGGGACCCCGACTTTACATTGACTGATTATCTCTGACTCCC
          CCAAGAACTGACATCTCATGAAACATCTAGCCCTATGCCCGCCGGGTAGCTCTGTCCGAT
          TGATTACTCGCCTTGTCACAGGACATCACCATCTATTCTTCCCTCGCATCCTACACTAAT
          CTAATCGTCACTAATACGCGGTGTATATTATCTTAGTTTTACAGGACCGTACTGTCCGCC
          TTATATGGACCAATCTTGGCGTATTTTCCGGTTTCCATTCACCTGTCGGTCGTAGGTTTT

          TTGTGTAATAACACATTCGTATGTCCTAGGCAGTGCCCCCCTATTAACGCGAGTGGCGAC
          TTCTGTAATGACACTCTCGTGTGTCTTAGGCAGTGCTCCCTTACAAAAGCGAGTGGCGAA
          TTCTGTATTGGCACATTCGTTTGTCCTGGGTCGTGCCTTCCCACAAACGCGAGTGGCGAA
          TTCTGTATTGATACGTTCGAGCGGCCTGGGGTGTACCCTCCCACAAGTGCGAGTGTCGGA
          CCCCGTAAACTTTCATTTAAGTAAGTTAGGCACTGCGCATCAATCGAGGTACGTGCCGTA
          CCCTCTAATTTCGTTTCTATGAGTATCAGGCGCAGTGCCTCCATAAACCGCATCCACGAG
          TCCAGAATGATTCCGACCATATTTTAGATGCGCCTTATTCTAAATACCGCTTGTACCGGT
          ACAAGGTGAGGGAGAGGAGTGTAAGCCGGACCCCCAGTTGAAATCGGTTAGTAAACTTCG

          AGTATAGCGGAACCTCCCTCATTAGGATATATCAAGTTGCAGAACAAGCTTTTACTGCGA
          AAAAAAGTGGGATCTCCTTTATTTGGACGCATCAAGTTGCAAAACATGCTTATATCGGGC
          AGGATCATAGAATCTCCTCCATAAAGGCATGTTGAGCTGAAAGACATGCCTACAACGGGA
          AGGATCATAGGATTTTCATTATCAGGAACCGCCAGGTTGCAAGAAGTGCTTACATTGGGA
          GAGCCCACACGCTCCTCGTTATCCTGGTACACTGAGGAATAACACGTGCCACCATTGAAA
          CCAGCCACAATACCTATTTCCATGGGGAGTTCAGAGTTATCGAACATCGTTATTCCTGTA
          GGAGTGCTTGCTCACTCTGAGTCGTAACGTTCTTCAGCAACATCTTCGTTTCCCACAGAC
          AGTAGGTCTCATCCTAAGTCATGACTACGTAGCGGAGCACCTAGCAAACATAACCCGGAG

          TGGATGATTCGAATATAATGGAGGGATGCAGCCGCACGATATTAAGGGGAGCCGCCCTCG
          CGGATGTATCGGCCATAATGGAGGGAGGCAGCCGCACGTTATTATGGGGAGCCGTCATCG
          CGAATGATTTGAGAATATTGAAGGGATACAGCCGCACGCTAATGGGGAGAGCTGCCATCA
          CGGATGACTTGGGTATATCGGGGGGGTACTGCCGCACGTTAATAGGAGGAGTAGACAGCG
          CTAATGACTCGGTTTTAATGGTAAAATGTCTCCGCCCATAAATGACGAGACTCGGGGGCG
          GTTATATACACATCATCATGGAGACGCGACACTGTCCATGGAAAAAGGAAGTCGTTCCGG
          CACACAACCCTATCAAACCGTACACGCGCTGCAGTGCGCTAGCAGGCAGAGTTAATGTAG
          GACACGAGATCATCACTCATAATGACCGACCCTCTTCTTACACTAGACGCGATAAAATCG

          TGAACTATAAGATGGGTTGGCGCTGACCCTCGGGGAGCTGAGGATACTCCGTGCATGTTT
          TGAACGTTAATAAGGGGCGGCGCTGCCCTTCAGGGAGTCAAGGATTCTTCGTGGCTGTCT
          TTAATCGTAATATAAGGCGGCGTTGTCCTTCGAGGAGGTCAAGAAACCACGTGCATGTCT
          TGAACGGCCATATGAGGCGGTCCTGCCCACTAGGGAGCTGAGGAATCTCAGTGCATCTCT
          AGAACGAGAATACGTGAGGGCACCGTTTGTGCAGGCGGTGCAGTAACGTCATGTATACTT
          TGAGTATTGAGGCGAGTAAGCGACCATGTTAGTGAAGTTGCGTAATCACGGAGCGTGACC
          CCCAAGTAAGATAGTTACGGAACTCTCCACCGGGAGATCGTGTAGAAATGACGTAGGGGC
          TAATTGAAGGAGCATGGTGACTCATAGCCTGTATGGGTCAACGGGAGGTCGTGGCGGCCA

          TCAGACGTGTCCCTAACTTGTGTGATACTCTGCACGCCCAGGGAGTGGGTCCCATATTAG
          TCAGACTTGTCCCTAATTTGTGTGATCTACTGCACGCTCAGGGAGTGGTTCTCCTACTAG
          CTAGATTTACCCTTAACTCATGTGTCACTTTGCCAGCCCAGGGGGTGGAAACTCCATTAG
          ATCGGCTTGTCTTAACCTTATGTGATATCCTGCACGCCTAGGGAGTGAGAATCCTCCGAG
          TCATTACTGTTTCCAACATGTGTGCTAGCATCCACTGTCAGGGTTACCCATGGTCACCAG
          CCCACTTTGTCGTTAGCTAATGTCTCAGACATTGTAGCGCAGGTAGAGCAGTGTAACCAG
          GCGATATTTTAGGAAGCTCTCCCCTCATCATGTGGGATTTGGGTCTCAGTTCTCAGGGAG
          TCCGTTCCCGTGTCAGCTCGCTCACCGGTAGAAAAGCTCATTGCACAATTAATTCATGCC

          CCTGCTCTTCCCTATCCAGGCACCCGGTCCCGTCGTCTGGCTTATCTCAAATTCGGCTTG
          CCTGCTATTCCCCATCCACGTATTCGGTCCCGTCGTCTGAATTTTCCAAAAATTGGCTTA
          CCTCATATTACCCATCGAGGTATTCGATCCGGTCGTCCCGTTTTTCAAAGATAGGGCTTG
          TCTTCCGCCTCTTATCACGGTATTCGGTTCGCTCGTCTGGCTTTTTCAGAATTGGCCGTG
          TCTCTACGTCGCTGTTGAGGTGGCCGGACCGGTTGCTCGGATTACCAAAGATTAGGCCTA
          TCTCGAGATCTACACCGAGACCCCCAGTATGATCCTTCTGTCAAAGTAAACCCAGGTTCG
          CCGTCTATCTTCATTAGAGATAGTTGACCTCAACTCACCGGCAACCTGTAACCAAGTATG
          TTACTCGTTCGGTTGATTGACGCAGCGGTTTATATTTTCTGTACTATGGGTTTCGGCTCG

          TAAAAAATCTGCAGAGATCTAGAGCCATCGCGAAATACATCCTATAGAGTGGCGTGCGGG
          TTAAAAATCTGCAGAAATCTAGAGCCATCGCGTAATGAATCCCACAGAGTGTCGTGCGGG
          GTAGTAATCTGTAAAGATCCGTCGCCTTCGCGAGTTTTATGCCATCGGCTGCTGGGCGGG
          TAAAAAATCTGCAAATGTCAATAGCAACCGCGCAATGTATCCCATAGAATGACGGACGGG
          TTCACAATATACCAAGGCCATCTATCGTCTAGAAATGCCCCTTCTTGGACGGCCGATATG
          TTGAACACTTGACGGGATTCGTAGAAATGTCAAAACGATGCGCTTCGGGCAAGGGTCGAG
          ACACAGATCAGTCGACCTTAATGATCTGGTATAATAGGTCCTCTTCAGGTATAAGGTAGC
          CTGGGGATCAGGTAGTCTGAAAGGAAAAGAAGGTTACGTCTTATCCGGAGGTTGAATAAA

          TCACGGAACAGAGCGCTTGAGACCCAAAGTAGCATCGTTTCTTAAGATGTTGCTCCGAAT
          TCACGGAACAGAGCGTTTGAGACCGAAAGTAGCAATGCTTCTTAAGACGCTGCCCTTGGC
          ACACGGAACAGGGTGCTTGAATCCTCACACAAAATCGATTTTCAAAAGGCTGCTCCGACT
          TCACGGAACAGGGTGCTTGAGTCCCAAATCAAAATAGAGTTTTTCGAGGTTGCTCTGAGC
          TGAGAGAGCAGCGCGACTGACTTTAATAACGAACCTGATATCTAAAGGATTACACTGAAC
          TGTGAGTGCTGGGTGAAAGTGTCCTTTAGTAAGGATGACCTGAGTGAAATTGATATGGTT
          TAATGAATTAGGGAAGTCTCGTAAATTCGTAGCAGATTGTCCCCAAGCGTACGTTACGGT
          AGTGGGATCATGGCGACTCAACCCTTGTGGGAAAACTATCCTACCTAAGCTGAGTGTACT

          TACGCCCCACGCCGGGAGAAACGGTTCGATACAATCAATTATCATCGAGCCATCTATAAA
          AACGACCCATGCCGGGAGAAAGAATTCGGTACAAGTGATGAGCCTCGAGCCATTGACAAA
          AATGAACCATGCTGGGAGAAAAAGCCGGATGAAAATGACGAGCCTCGTGCCGTTTCTAAT
          AACGACCCTTGACGGGAGAGGATGTCAGGTTCTAATGACGAACCCCGGGCTACCTGTAAT
          GAGGAGTAGTGGAATTATAGAGGGTAAGATGGTAAAGATGAGCCGCGAACCGGAGCCAAT
          GAACGATGGGCAAGAAAAAGAAAGATTGATGGTGAAGATGGGTGCGTGTCCACGGGTGGA
          ACGGCGCGTTGGGACTGGGATGGCCAGGGCGGTGGGCACGCGCTAGAGTCCAATGTAAAC
          TAGCAGCAGACTGAATTGAGACGGACGGACACCATTAGAGATTCGGAACGTGCCAAATTC

          GCCTGAGTCGCTATGAGCCTTCCAACAGCAGGTGGCATTCTTTTTGTATGTGATTCTGCC
          GTCCGACTCGATATGAGCCCTCCAACAGCAGGTGACATTTCTTTCGTATGTGATCGTGTC
          AACAGACTCGTTACGCGTTCTCTAATAGCAGTTAGAATCTCTTTAGAGAGTGGTCATGCC
          GACCTACTCTCTATGCGTACTCAAGCAGCAGACGGAAAATCTGTGGTATCTGGCCATGCA
          TACCCGATCGTTGTTCGCCCCTTCTCGGCCAGTGGCACATCTCTTGAATACTACCATCAC
          GCCCGATGTACAATACTCATAATGAAAACGTATGGAATATACATAAGATGTACTCCTCTA
          TTCCGGTATGTTCCACTTATCATACGGATACGCCCGAGGCTTCACGTCTGACTCCACCAG
          TACAGGCGGGCCTTCTCCACGGCGAAAGTAACATCAGTGTTCCGCGGATGCCCCAATTTG

          CGGCCGAATATGTTCCGAACAGAGTAAAGTAATATGAGAG
          CGGCCCAGTACGTCCCAACAAGTGTAAAGTAACAGGAGAA
          CGAGCCAATATGTTCTAATCAGAGCCGTGTCTTTTGGGAA
          CGATACTATACGTTCTTACCACAGCAAAGTGAGTTGCGGA
          TGGACTCAGAATTTTTGACGGAAGTAGGATATACTCGTAA
          TGACTTAGTGATTTGGAACTAGGGTCAGGTGGCCTCGCAA
          TGGCGTGCTGGATCGTAGCCAATGCCATGAAATCTCATCA
          CGCGGTCGCGTGTTAGGCGTATATCACGTTGGCTCTTGGA

