 8 1000
t1        CCGCACGGAGAAATCAGGCATACGAGTCCACTAACTTACTGGCCGGTTAGCGTCGCTTTT
t2        CCGACGGTTAATACCTGGTAGCCTGGCCCCCTAGTCTTACTCTGTCTGACTACCTTTCTT
t3        GCAATAAGATAGATTTCACAAAGCATTCCCGCGAGCTGGTTTTAAGTTGGATCCTCCTTT
t4        CTGGAGGGCAAAGCTACCTGGCGTAACTCTCTAGCTCAATCTTGTAGAGGCGTGTTGCAA
t5        CCGCAAAGTCACACTTTCCCGCAAACTCTACCGTAATTGCAGTGGAATAGCATATGTCCC
t6        CCGACAGGCCATCCCTGTTTGTGAACCCCACCTGTTTCACCATACTAGGTCGTGCTCTCG
t7        TTGCAAATGGTATACGCCCGACGTAGCCCGCAATCTGCAACGAGCGCGAATACTCTGCTC
t8        TCAGTAGCCTATTTGATTCGACGGGGGCTCTTACTGTCAATGCTTACAAAAAAATTCTCT

          GACGGATGATCACTTGACGGCCCCCAAGTTGTGTTGTTAAGGTGCCCCGCAGGCCGTGCC
          GGTGTGCGAGCAGGGGACTGGGCCTAAATCGCGTCCCCATGTAGCATATACGCCTTCAGC
          AACAAGGGGCCAATTGATGGGCTCTAGGTCGTGACGTCAAATTACCTCACCGGAACGTGT
          GGCCGGAGGCGGTATGACGCAGTCTACATCTTGCTGTCAAGGCGTCCCGCTAGCTCCGGC
          GATACAGGGCAGCTTTTCAGATCCCCGATCGGGTCACAGGGTTACTTGTAAGGGCTTGCT
          AATAGACGGCTGCGAGGATCACGTCCGTCCCCGCTATAGAGTCGCATATATAAATTAGAC
          GGGCCCGAGCCACGCATTAGATCTTAAATCGGATAGCCAAGCTGTCGTCAAAGGCAGGGA
          GAAGGAATGACCCTCCCTGAACTACCGACCGTGTTACTCCACGATCCCCGTTGAGGTGAT

          GTAGCCATTGCTGGTAAGAATCGACACGTTGACCCCGGGAAATCCGTGCGTGGCTAGTGC
          TGATCCCTTATCGAGCACTATCACCGCGAGAGGTCTTGAGACTTTGCATCTAGCAGGCGC
          AGAGTGTTGATCGACACTTCCTTCAGCGGGCGACTCCGAGAATCCATTCTCAGCCAGAGC
          TACGCCAGCGTAGACCATAATACACGCGTGAGGCCTCTAAGGTCGCGACTTGGCTATAAT
          TGAACCGACGTGGAGTCTCCCGAGTGCGCATCTCTCATCCAGTTTAAATCTGCCCTGTAC
          TGAACCATAGAGAACTATTGATTTTCTGCCGAGGTGCTAAACTCCGTCTGTGGCTAGCGT
          AGCAGTACCGCGAGTGAACAGGAACAGATAGGGCCATATTACAGTGACCTCGGCACGCGG
          CGAATAGTTTTGGTGGTCCTCAAAAGCGTAGTCACAAACAGCGACGGATCACGTGTGTAG

          ATTCTATGCTTGGTGATTCAGGCAACTTTTTCCGACTTAATAGAAGTACTTATTCGCCGG
          ACCCTATCCTCGACGATTATAGCGGTATTTCTGTAACAGGGAGAGTTGCTCTCTCCAAGG
          GTCAAAAGCTCGGGCATTAGGTCCTCAACTCCTTAGCAAGAAGAATCATCCACTGGTCAG
          TGCCCGAAACTGGTGTTCAAGAATTTGCCTTAAATGCTGGGAGGGCTATCCATTCGACGA
          AGCTTACTACCGATGATCGAAGCGGTATTCCTCGAGCAGGGCGACTAATGTCTTCCGTGG
          AGCGGACGAAGAATATCTAACACAACATCCCCTAAACAAAATGAAGTACTCTCTCGATGT
          AGAGCACATCTGATGTTAAAGGCATTAATTGGTCGGCTGGTCACGTCATCACTTTGCAAG
          GGGACATATTAGTGGATTTCAGGCTCGTGCTCAAGCTATAATAACAGCAGATCTAGATAA

          TTTCAGTCATCGGGCGGATTTCCCTTCTGGTCACGTTTAGTATTGGCAGGCTACGATTGC
          TCACGGTTAGAAAGTGGGTCTCATACCCGGCGTTACTACGTATTAGCTATTCAAGAATAG
          TCGCGGAAACATCATTAGCTTTACAACCGGGGATGTTTTATTTTGGATGGCCCAGAGTTC
          ACCCGGCGGAGGTGCGGGTCCAACACCTGGCATTGTGCACTACTGACTGACCCGGAATAT
          TCGTAATAATATGTCAAGAACTAGACCCGCCGTTGTGTGTCAATGGCCGGCAGAGGTCAC
          CTGTGACAGGGGAGAAGGTACCATATCCGTCGTTATCCCCAGCCGGTTGACTAGCACGTC
          CCGTCGTCCAATTGTGAGCTTTACACTCGCCATTTAGTGCTACGAGCTGGCTCCGTAGCT
          ATTTGGTAGCATCTCTTAGAGTGACAGTCACGGTATATTTTGCCGATCCATCTATTCCAT

          GTAAGAGATTACGCAGTACACAGTTCATATTATGCCACCTGAGAATCAAATCCTTGCTCC
          GGAAAATATCACGCAGAATGTAAGATATCCCATACTCTCTGAGAGTAATCCGACCCCTCT
          ACAGGGAACTACGCACAACACGAACTACAATAAGCTTCCTAACAGGACCCAATCTATTCT
          AAAAGGAATTACAGGTCGCGCGGGCTAATACGCGCTTATCAAGGGGTTGCGTGTCGAATC
          GTCAAGAACCTCGAGACCCGCATGCAACTCTAAGCTTTCACTGTAGCCACTTTTTCCTCC
          CAAAGGTGTAGTGAAACGAGCGGTTTAGTTCGCGTACCCACGAGTGACACCCTTCGTATC
          AGAAGGAAATAACAAATAAGTCAATCAATTCAAACTTTCCGCAGCAAAGTCTTCATATTG
          GTATTAAGTAGAGAACATACCCGTCCTAGGTAACAAAACACGGCCAATCCGATCGATGCC

          GTACAGTGCAAGGGCTGCCCCTGGACCAATTGACTTGTTCAGTTATGATTTCATCCGAAT
          CCTTAACCGAGGCCTGGGTCATTGGTCAAATTGGCATGCCGCGTTTGATTGCGCCCGAAC
          TAATATACACGGCCTTGGTCTCCGGCCAACCTAATAATTAGCGTTTGATTACGCCAAAAT
          TCATTGCCGTGACACCAGTCTCGGTCCGTCTTAACATCCTGCGCCGGCCTGAACCCATTC
          ACTCTCACGAAACCTCAGCCACCATGCTCGTCTTTGCCCCACGCTGGATTGTATTTCGAC
          GTCTTCTCGTTCCCTTGGTAGACATGCTTGATAATATTCCGTACACAAGTTCACGCGGAC
          CCAGCATTGACACCTTATGAGAATCATTGGTTATTGTTTTGCGATCTCGTCTTTTCGAAC
          CTTGTTGTTTTCCTGACCCTGCCTTACTGCCTCGCGGGCTGTGACCGAGATCGCTAGAAT

          CTTGCGTGCCACTAAAACGCCCGCGTTCTGATTAATAGTGTAATTATGAAGGGCCAATGG
          ACTACGATCCAATATAACGTAGGTCTGTCAACGGAGTAATGGATTGTAATGGCCCCAACC
          GTCGGCATCCCCTACAGTGCGCGTGTGCTGGCCAAGTATTGGGACATGCAGAGCCCATCC
          ATTACGACCCAGGATTTTACAGGTATTTCAACGTAGAGTAGGACTAAGCTGAAACCATCC
          GATGAATTTTTCCTCTGGGTACGCGACGCGGTACCACAACGCATTAAGGGTGATCAGGCG
          GGAAAGCTCCTCTATCCTACATCGCGAGTCATATAGTGCTGGCCTGCCATGGTGCCATGC
          GCGTAACACACGTATAGCGCACGCTCAACGATGGCGCGTTCTTTTGAACCGAGGTCGCTC
          ATGTGGCGACATGACTACACACGTTTTTAACCGTGGAATTGGCAAGAGGGAAGGCCACTT

          AGTCTGTCACCCCTCAAAGGGGCTGATCTACGGAGAAGCACCTGCGAATTGCGTCCCGTC
          GTCTGGTCGGCACCTAACGGCGCACTCCCTCCGAGACTCAGCTACAGAGGACGTACTAGT
          AGTTTGCCGCCCCTCAATCGATAAGCCTTTTTGCCATTTTCCTGAGGGTCGCATTGCGTT
          TCCTCGCTGCCTCTCAAAGGGTCACCACATCTGTCCCCTTTGTACAGAACGGACTATGCA
          TCTTTGCATCCGGGTAAGGGGATGTCTGCCTCGCTTCTCATCTGCAACACGCGACCCTAA
          TCTCTGCAACCGTATCGCGGCAAACCTACTAAGAACCCTGCCTACAGTCTGCTAATCGGA
          TGCTCGAATCCGCGAGGGGGCATGCGCCCTTCGCCCCCCCTCTGCGGTTCACAATCCAGG
          TAACGACAGCTCTTCGTATCGGAGCTGCATTTACCTTCTGATCACGGTCAGGGACATGAG

          TTTTCCTCTCCCTGGCGCCGATAAGCGGGGGACTTCGTGGGCGTCTTCAGGCATACAACG
          TTTTCCCCTTTACAGTGCTAACCATCGGAGTGTCTCGAATATGTATCCGTGACCTAACCG
          ACTTCGTCTCCGTGGTGCTGTTAATAGGAGGGTCCGAAAGGTGCATTTGTAACAACGCCG
          TTGGTCATTCCTGGGCGCTGCCATTAGAGAAGCCTTGCATGTGTTCCGGTACCTACACCG
          TTCGGTCTTCGATACGGCGCAAAGCAATTGAGTAAGAGCGGTGCGCCCGCATCCACCGCA
          TTGGCTTTTCCACTAAGCCAGCAGCGGGAGTGCTTAAAAGTCTAAGACGCGGCATAAGTC
          CTAACAGCAACACGCGGGTATAGGCGGGTGACTACGAACGGTAAGATAGTAGCCAGCATG
          TAGGATCCCCCAAAAGCAATTGTGCGAACGCGCCCTATCGTATACTCAGTCACTTGCATT

          TGGACAGGAATCAATTTGTATTCTTCAAAAAGTGTCAGGCCAGCCCCACCGCAATCGGTA
          TGCACTGACATTCGTTAGCACTTTCTCAAAAGCACTGGCGCAGCGCCGACCTCCTCAGAA
          CGTATAGCCGACGGTCGGCATCTGCTCAGAACCCTCTGTATCGCTCTGACACATTCGGCG
          TGTATAGACCGCGCTCAGTATCCTTCTCAAAAATTGGGTGCAGCTCCAATGGATCGGGGA
          CGTTTTGAATGCATTCGTCGCGGACCGACTATATACGGTACTGCACCCATGTACCCCGTG
          TGCTATTTACCCAGAAATCCTTGTTGCGGAAACCCAGGTGGTTTCAAATAACATGCAGTG
          TGGCTTGAACTCTGTAGCAAACACCCAGGAAAGATTAAGATTGTCCCGCCGTACTAGGTA
          TCGCAGAGGTGCGTGGGGGATCAAATGGTAAACTTGTGTATCACCCGAGAAAGAAGGCCA

          TTTCTTTGATCGCATGTGCTTACATAGCTCAGGGCTGTGATGCCTTTGGGCACTCTTCAC
          TCTCCATAGTTGCGCACGTCTACACAGATGGTGGCTACAACGCCTTTGAGCGTTCATTGC
          AATCCACCAGTACGTTGATCAGTATAGAACGGTGAGACAATGACCTTGGGCAATACTTAC
          TTCTCCAGGTATGGATAGAGCATGCGTAACAGGGATGTCACGCTCTCAACATATTCCAAC
          GTACTTTAACCCAGACCCTGCCTCAATATCAGGTGTACGCTGTCTCTCATCTCCGTGAAT
          GCTTCACAACAGTGTCGGCGCCTCGAGAGCAGGTCTGAACTGGGCACGGAACATCTTGAC
          ACCTGATGAACCGGCTTGCGAATGGGTAGCGGGCATGGACTGTTGCCGGGGTACCAGGGT
          AAAAAAATATTGCCCGTGTGAGTACCCTTCAGAGCCGGATAGAGACGACACCCTGACGTG

          GCGAGCCTCCGTCACCTCGCTAAGTGATGACCTTCTGCCCATAGACGGAGCCTACACCTA
          CCACATTCCTCTTTTTCAGATATGCGGTAAACGTCCGACTCTTGATGGAATCTCGTATCG
          GCTTGCTCAGCTTGTCAGGTCGTATCTCGATCATTTGCTTTTCGACGTGATCTCGATCCG
          GTCGACCACGTCCGTTCCGCAGCACGGTGATGGTGCGTCTACAGTTAGTATTCAAATTAC
          CATTTCATTCGTTACCAAGCAGTGTGACTATTATCCGCTTTTCGTCCGATTTGAGATCCG
          GAGGGGAGTAACCAGTTATTTACGGGGACGTCACCCGCCTCTCGTTGACAGTCCAAGTAA
          ATGCGCTGAGCACAAATAACAACGCGGTGGTCATCAGCGCAATGCCGTCATGGGATGTCG
          GAGGGCGACTTTAAGTCGACCACAGGAGAACGGCGTGCTTCACGGTGTTGATGGGATGCG

          CTTCTAGTGAGTACCATTGGGCCGCCGCCTCGCAAGTTCAAAAGTCGTATTCTCTTAAGA
          GTTTGACTGATAATCCTTCCTTTGCTATTTTCAGCGTTTCTGGATAACACTTTCTGAAGG
          GTAGAATTGTGCGCACTCGCGCGGCTGCTCCTACAACTCGAGGGTAATTTTCTAAGGAAG
          ACCTATGGAAGTCGCACTTCGTCGCTGACCCGAGAGCCTGAGAAAAGTTTAATTCGAACC
          GCTCAAGTGGACGCATGGACTTTGCTTCTGCTCGGGCTTCAACTTAACCCCTAATTCAGT
          TTATAAGTGGATACCACTACGTTGATGAGGCCTAGGTTCTTGGGCGACTTGCGTCACAAC
          CCCTGTGCGAGAACTCTCGCTAGGTATCCTACCTAGCTAAGGAACACTGTCTTCAGATTG
          ATGTTTGCGGAAGCTACCAAACTATCATTGACTCTGACCCTATGAATTCACGGACGAATC

          AGTTTACATCGGAGAGGCTGGCGCCTTTTGACGATTGCTGATCAATCCCCACAAGGTGGT
          AATCTACACATACAGAGCAGAAGCGCTAGAACCTTTACTACACAGCTACAAAGAGCCTGC
          GACTAGTATACTAAAGGCAGCTGCGTCAGGGACAGTATCAAACAACCGTCAAGACCTGGC
          AACTTCCGATCTAAGAGCCGCGGTAATACATCTAGCGCCGCGCGTATGTCAAGCGTTCCC
          GAGCCACGACACGTTGGATACGTTACTATGTGAAAGGTCAAATCCACATTGAGCTTTATT
          GGCACAGGGCATGGTGCTTATGTCAAACTGAGTCGGCTTTTACAAACACCAAGTAATGGC
          GCTCCTTGGCGAAACGGCAAAATCTGCACCTAGGGAAAGGTTTCAATGCAATGCACTTGT
          ACTAGACATCGCAGGCAGCGTAACAATTCGTTCATTCCGGCTACAACGCTGGCGAGAGGC

          GAATCTTCTACCCACGATCAATAAACCGGGGCTAAGACCACTACCCTTTTACCCCGATTG
          TAATTGGTTACTTGTAGGTGTCAAATTAGTAACGATGAGTGTAGCTTCAAACCTAAGTTA
          TCACTGCTTACATGTGGTCACCGTACTTTGGACGTTGCGAACGACCACTTCTTCCAGTCA
          AGGCAACTCACTTGGAGCTATTATACCTAGGCCTAGGTGCAAGCCCTTTTAGCTCCACCG
          CGATGACTTACGTGGAATTACAAACGTTGCGCAATATTGCAAATATACCCAGCGAAGTCG
          AGGTACTTCTGCAAGTCTTGGCGCACCCAGGTTTAGTTCTTCATCGTTTAAGCTTGCTCC
          TGTGATCTTCTTGGCTATCTACAATGATTGACCCAGTCATACCGCTATTAGGCTCCATGC
          TCTAATTCAGTAGGCCCCGGGCAAAAGGAGGCTGAGTCTCACATACTGGCGTAGCTAAAA

          TTTCGCGTAATATACGTCGTGAGGGGAGCGATACACGACA
          TGCCGCGTGATGTGGCCTGTGAGCAGATTGAGACACGGCA
          TTTCGCGTGATATATGTACTGAGGGCGCTAAGACGCGGTA
          TGTTGTGATATACCCGTTACGTTGTACCCGCTGTATGGCA
          TCCCGCGTAAGCCTCGTCACGAGATCGTTGGTAGACGGCT
          ACACGTTTGGTCCTTGACAAGTAGTAATAGAGACATGGTG
          CATCGAATCGTGTCTGTAAGCTGAAAACTGGCGTTCTCTA
          GTTAGTAACAAACTTGCTATTTCCCAAGTGGTGATTGAGT

