 8 1000
t1        AACCTATCGATGTGCAATGAATCCCTAATTCCCCCTTCCCGGCGTCTGAGAAAACAACGG
t2        AACCTATCGATGTGCAATGAATCCCTAATTGCCCCTTCCCGGCGTCTGAGAAAACAACGG
t3        AACCCTTAACTGCTTAGAGAACTGCCTGATCCCTATCTTCAGTGTCCCGCGGTGCGGCGG
t4        AACTTTGCAATGTGCGGAGTCCCCCTAAACCCCCGCCTTCAACAATTTCCCATTTCTAGA
t5        ACTCCTTACCTGCAGCCAATACCTACTGCTCCTTATCCCCCCCGTAACGAGATGCGGGGA
t6        ATCTACCCGGCACAGGGAGCAACTCTCTGGTTTCACTTGGGGCGCCCCCGGACATGGCAG
t7        TATTTGGTACTTAGCGGCTAGTCTAATGGCCCGCGCCCGCAGTGTCCAGCGACCTAGTGA
t8        TCGAACATTCTAATTACTCTAATCGGATGCTTTTAACTCAGTCCTTATAGGCAGCAGTGG

          TTGAAGAGTTATTCTCTGCCAGCTTGTCGAATTCGTACGAGGAATCTCTACACGCCTGAC
          TTGAAGACCTATTGTCTGCCAGCTAGTCGAATTCGTACGAGGAATCTCTACACGCCTGAT
          CTGGTAGTTCATTATCCGACTATGCGGGTGTTAGGTTCAAGGGACTACAATTCGCCCGTA
          GCGGTGAACCACTCTCCGGGTAAGTTGTGGTTAAATAAGGGGAGGCTTCGGTCGCCCGTA
          CTGATGAATTTATCTTAATCATGTTAGAGGGTCGGCACCGAAAGGACCTACATACCCCCA
          CCTACTAGATCGTCGTCCAGATCAGAGCCAGCTGTCGAAAGAGGGACCTTTATGGCTATG
          CCTCTCGCCCACGTTTATGCGGCATGACGGTTCCTCCGCTAGGGGGACCCGTGACATGCA
          TTAACAAGCAATCGCCGGGCACCACAGTGAAATAACCTTACTCATGATTAGGGGCCCACT

          TACGGACATCGGCAACAGCTGCTTATGTGCAGCATCGCTTCAATGGTCCAAAGCATCTGA
          TGCGAACACCGGCAAATGCTGCTTATGTGCAGCCTCGCTTCAATGGTCCAAATCATCTGA
          TTCAGCCAGCGGTGATTGCTGCTCTCGAACCCTACTGCTTTATGCTACAATTGCGCCCCG
          TTTGGCAATGGGTGAGTACTACCCCCGAATCGTACTGCGTCACTAGTCAAGTATGCCCGC
          TCCGATCATCAGCGGGGTCTATCACTCCACCGCAAACTCCTATGAATCGACCTGACCCCC
          CTCAATTCGTGTACAGCTTCGTCCCCAAAGAGCGCCGAGACACGGCTTAAGTGGGTCTCT
          CGGGAATCATAGAAACGCTTGTCTTAAGAAGGCTCATTCTCTTAAACTAGGCGCGGCCTA
          TTCTGCTGCGGAAGTCAGACGCTCTCCACTATCATGATTTCGCCGTTTGCTTCCTCCCTG

          TTTCCAGGCCATCCGCCTACCGAACTCCCATTCGCTCAATCAGAATCATGAAGTCCAGCT
          CTTCCAGGCCATCCGCCTACCGAACTCCCATTCGCTCAATCAGAATCATGTAGTCCGGCT
          TCTCCAGGCTCTCAGTTGAGCGCCTATCAACTTGCTGAGCCAGTGTCTTGTACTCCCGCA
          GTTTTCAGCTCCTCACCGATCAGGTTTCCATCCGCCCTATTAGCACCCCAAGTTACCGCA
          GCTCTATGTTCTCCCTGGTCCATTAGTTCACTCGTTAGACGAGCGGCCGTAACACAAAAG
          GTCTTTTAAATTCTAGTGAGAGAGTTCGAGCTTGCCACCTCCGCGTACAACACTAGCGCA
          ATCCCCGTCGCTCTTATTATTGCTCGTTGATATGCTATGAGCCCGTCTCGTATACTTTCA
          TCGGACAACGGCATTTCAACCATTCCGCTAACTGAAGTCTCTTCGTACTAACCTCTTTGG

          AACCACGACACGGCGCTGACCCGCCTTTACTAGAGAGAGATCTGCGGCAGTGAACGCTCC
          AACCACGACATAGCGCTGACCCGCCCTTACTAGAGAGAGATCTGCGGCAGTGGACGCTCC
          TACTGTGACGCAGTTCATCAGCGCCTAAATTACAATCAGTATCATGTTTGGGCACGCACG
          TACCGAGACGCAGCACGCTAGAGTTTATATCAGCATTTGTCTCGCGAGAATGTGTATGTG
          CATCGTGGTGGAGGCCGCGGGTATGTCTGCTGGCACGCGTCGTGACAAAAGGTTATCATC
          GACTGTGTCGTCGGTTATAAGTGAATTTGCCAATATAAGCCTTAAGGAGAAGCCTTCAAG
          GTCAGCCTAATTAACCGGGTCAATGCGTAAACGATCAAGGCCCACGCAGGTGTGGCACCC
          CATTGCGAGAAGGCCTAGCCAAACAGGCATTCGAGCAGAATCAAACCACAGATCAATTGA

          CGGCCTGGAATGCGGTTCTGCGAGGTGTTTTAAGTACGTCATTACCCGAAGTTGATGTAG
          CGGCCTGGAATGCGGTTCTGCGAGGTGTTTTAAGTACGTAATTACCGGAAGTTGATGTAG
          TAGCGTCGAGCACAGGCCTGCGTGATAATCTATGAATGCCTCTACCCATCGGTAAGTTCA
          TAGTCTTGCTCGCGGTTCATCAAGACGTCTTTCGGCTGTCAATGCGGTACACGAGTTTCA
          AGGCCATGCGCAGTGACTAGAGAACAGTTCTCTAGCCGCTACTTCCCGCCGCCCCTTCCG
          GCGCATAGAGGACGGTGCAGTGAAGTGATCTGTCAGAACATTATCCCTGTGTTAACATCA
          TCGAGGAGCATATAGTTCCGTGAGGAGGTTGGTACCGACTCGGCTCTGGGTCTCTTTCTA
          TAATGTGGTTAGCGAGATACTGGGCCCTTCTCACATAGTCCCCTTCCTCCTCTAGCATCT

          GCGTCGACGTCTAACTGCTGCTAGTATCTGCTATGCGTAATATCTATACCTTGTGCCTGC
          GCGTTGACGACTAACCGCTGCTAGTATCTGCCATGCGTAATATCTATACCTTGTGCCTGC
          GGTCTGGCACGATACCAGTGCTATCATCTGAAGGTTCTCACCTACGAATTCATTGCCGGC
          AGGACGACCTCCTCTTTATGATCGTATCTGTTGCTTCTTATCTGATCGTTCGCGCTTTTC
          GGGTCGGCACTGTTCTGCCAACATTACTTGCAGTATCTAACCCTAACATTGGTTGCCAAA
          GAGTCGGGATAAATTTCTTTTTCTTAGTTGTAGGCTCCGATAGGCACGCCCGCTACCATT
          CTGCTGATACAATCCGGCTAACCGGGCCTACTACGATTTGGATGCAACCTATTCACTCTC
          GAATTGACGTTTCTAATCCAGTGGCAATTGCGTTGCTCTACACTTGCGTGTTCATCCAGC

          TTCGTACGGCAACGATACTAGACTACGAGTCGTCGCCGGTACATTCGAATCGGCATAGAG
          TCTGTACGGCAACGATATTAGACTACGAGCCGTCACCGGTACATTCGAATCGGCATAGAG
          TTTGAGCGGAAGCGCTTGTGTGATGTGAGCTCTAATCCGAAGTGTTCCAGTCGCACGAAG
          CTCACACAGCAGTCCAGACGAGTCACGCGCTCCAGGCCCAAGAGTAGTTACATCGAAAAG
          TTCGGTTGGCCACGCTCGCGCGCCACGAGCTATCCGCCGGGAGCTTATAGTCGCGCATGG
          CTTGCAAGAAGTCAATAACGGGTACGAGATCTTTGGCCGAAGGGTGCTGCCCATGCATAG
          GTTGCACAGTGATGTCTGTGTACTTCGAGTTCCAAGCCGACAGGCCGTATTCACGGAGGG
          TGACTATGGAAATACCAAAGCGTAATATGGAGGAATGTGCAGGAAGACGCCTGTGTACGG

          AAGTTTCGCTTTGCTGGCCGTCAGATCGGGGAGTATTACGTTAATGAGGCCTGCATATCC
          AAGTTTCGCTTTGATGGCCGTCAGATCGGGGAGTATTACGTTAATGAGGCCTGCAAATTC
          AAAGTTTTGAACGAAAACTAATGGTACGAATGTCCGAATGACATTAGGGACGGCAAATCT
          CTGGTTCTCAGCAATGATAGTTGGATCCAAGGCAGGTATGACCTTGAACGACGCTGGGTC
          AAGGAACCCGATGTCAATCGATGGCGCGGGGGGATGAGCAATAGCGAGGTCTGGCGCTTT
          TTGATTTACAGTGCATACTGACGGTGTGAGGGTAAAACTAACTCTACGGACTGACGGCAT
          CGGTTTGGACACGTTTCATGAAGGCGAGGAGCGTGGACCGTTGCTAATGTTCATTGACCA
          CCGCCTATTAGCCAACGTTGACGTGGCGGAGTATAGCATGCATGTAGTATTATACGCACT

          GTGTTACGCATAACGATACATGTCGTGTACGTGACCGGGCTGGCTAAGTGATATCCTAGC
          GTGTTATGCATAACGATACATGTCGTGTACGTGACCGGGCTGGCTAAGTAATATCCTAGC
          TTGTCTTCAACGACAATACGTGGCCGGCGCATGAATGCAATGGCCATGGCACCTCTGTTC
          GTATTGACCACCGTATTGTTTATCTTGTGGACAGACTGCTTCGACAGGGTATCGCCTTCC
          GGGGAACATCCAAAACTCCAGTTTCAGCGAAGAGAACTGTTGGATATGACATCTTCTGTT
          AATGTATGCGATATACAGTGACACCCACCTGCATGTCGTTCGGACCGGGACCCTTCCCAC
          GTGAGACACACGGGAGAACAGCACGAATGCATGCACCTTCTTGACCGAGCACCTTATACC
          TAGGGCAATACCTCCCTACAGTATGATTTTAACGTCCAGCCACAACGTGCATCACCTTTA

          ACTTCGGAAGACTAGAATGGACCATTACCCTGCATCGGTAATTAAATAGATATCAGCTAC
          ACTTCGGAAGATCAGTATGGATCATTACCATGCATTGGTACTTATATAGATATCAGCTAC
          ATGCCTATCTCGCGTGAAGGGATCTCTGTCTGTGTAACCGGCCGCGTAGTTAATTCTTGC
          GTTGTTAAGGTGTGGTCACGCCATTTCTTTCGTAAGATTACAGAGGTAGATTGCTTCTAA
          GTTCTTAAGAAATGCCAGTGCAGCTCACTCTTCGAGGTTCGGTATGCAGACAACTGCAGC
          ACCTCCTGGTCGTGGCGGGTGTCGTTTTCTCATAAGACTGCATAAGTGCGCATCATCCTA
          CCTCGAGAATTCAAGTAAGAGTGGCTTTATCCTCGGTTCAAACAGTCAGCCAACAAGAAG
          GTTCCCTAGTTCCAGTATTATTGTCGTTACTCGGAAACTAAAAGGGCAGTTGATAGCTAA

          CCTGTCATCTCCGTTCGACTGTATGTCTCGGAAACACCCATTGTGTCCTCGTTAAATGTG
          CCTGTCATCTCCGTTCGACTGTATGTCTCGGAAACACCCATAGTGTCTTCGTTAAATGTG
          CTTCCTGACTAATAGCGGCTACTTCTCGCGTTGGCACCTACCGTAATTAAGCCAGCCATG
          CCCCCGGACCCCATTAAATGCTACGTCATGTTGAGATTCGATACGGCCATGCTATGTGAG
          CTCTTTAGCAGCACCTGGTCGGCTACAACATTGGGGTCTCCCGCTACCGCGTTACGCGCG
          TACTTGAATAACATTAGAGTCCTTGTGAGGCGCAGACACACCATGATTTTGTCTGATGCG
          CCAGTGGTAGGCGAGTACCACCCTGCTAGTTCGCTGGCCGATAGGCCCTAGTTCATTGAC
          ACCTTAGAACACATCTCGCTGTCTGCCACATTGATAGCTGGCATAACCCTGTCACATCGA

          AAACTGGCATATTCGGCAAACGGGGGCGGATCAGGGTACTATAAAAAGTCACCTCCGAGC
          AAACTGGCATATTCGGCAAACGGGGGCGGATCAGGGTACAATAAAAGGTCACCTCCGAGC
          AGATAGGTACGCTCCATAAAAGGGGCAGGAGTAGAGTAGGGTATAGAAGTTCCCTCGGGT
          CGACCGTCATGCTCGCAGGTGCTTACGGAATATGGGAAGGACAGTGAGGAGTATCTGGTT
          TGCTCGGTCCAATCAATATAAAAAATGGAGCACAAGGCGTATGCAAAGCTTATTTTAAAA
          AGATCGGCGCAACCGATGAAGACGATTGAACCAAAGATCTATACCGTAACTTCATTAGAC
          GGCTAAGCAGACTTGAGGAAGGCTGTGTCATATCGGGTTACGTCTTGCGTGCCTATGGAG
          ACTCCTAAAAATTTAATTACAGTCGCAACCATCAGTACGAGTGCAGGGACACCTTTAACT

          GCGGATGCTAATAGTCTCTAGCGTATTAATATTCGCGGCCGATAGTCACATGATGGCAGG
          GCGGATGCTAATAGACTCTAGTGTAATAATATTCGCGGCCGATAGTCACATGATGGCAGG
          ATGGAAAATAGGGGTCCCCTGTGTGGTGGATGCCATGCTTGGTAGCAACGCGTCGGCAGT
          GCGGAAACCAGTGGTCTCCAACTAGGTGAATGTTGTGTTTTACAATTCGTTAATGCCAGG
          GCGGGCGACGTCCGTCACTGGGCCAGTGACATATGTGTTCAATGCTAGCGCGTTGGCAAG
          AAGGAGCGCACATGCCCCTGGCCAGGTAAAGTGCGTTACCATCGTTGACGCGCCAATAAC
          AAGAATAACACGGGTTTTTTTTTTGGGGAACAACGCGCGCTACAGCGCCGAGACGGGTAA
          AAGCCCACCATGGTCAGCCGACTTCAGGATGTTGGGAGTGAACTATAGCGTAGTTCCTGG

          AAAATCCTAACTCAGCATTAGGGAATTATAACTCCTTGTAGTTCGGCGATGCTGATAGAA
          AAGGTCATAACTCAGCATTAGGGAATTATAACTCTTTGTAGTTCGGCGATGCTGATAGAA
          AAAATCGAGTTTCAAAGTTAAGAAATTTCCGGTATATATATGGTATTTGTCATGGTATGT
          AAGGGAACACCTGTAGGCCCAGGGAGTATTATTACAAATGGGCCAGCTAGCATGCGGCCA
          ATGTTGATGAATCACAGCTGAGACTGGAATATAGCTTACCCAGTAAGTGTTGTGACAGCA
          GGGGTGCTGCTGTAAGGGCAAGGGATAACATTTGTTCGTGGATGAGATGCGATGGGATTG
          GAGACTCCGAGTCATGCGTAAGGGGAGCCTATTCTATAACATACCGGCCTTACGAATGCA
          AGTGCACTATTCTTAGAGGATGTATATACTGTGAAATGAGGACCTGCTGTCCCACTCACG

          GAATGCGGTCTCATCTGTACTTATGGGGTCCGCTGTCGAGACCAATTCCACGAGTGCGAG
          GAATGCGGTCTTCTCTGTACTTAAGGGGTCTGCTGTCGAGACCAATTCCACGAGTGCGAG
          AAAAGAGGTTTTATCAACTTGCAAGGTCCTTTGTGTCGCGGTTGGTACCGTAAGGTCCAC
          GACTGAAGCTCTATTCTTCTAACAGAGGTTACATGTCGGGATTTCTATAATACGTCCTAG
          TGTAAGAGCCCTACGTACCGACATGGTATTATATGTCGAAGTCGAGTTACTTAGCCGCAA
          GACCGGAGCTCCGACCTGCGGGGCGCCACCTTATGATGATATAATGAATACCAGTCTTAT
          GTGTAAAGCTCGCCCCAATTATGTGCAAATTATTGCCGGTGCGAATCCAGGTAATCCGAG
          GAGTGGCCAAGAGAGTACACAGGTAATACACCGAGTTGAAGCTAAAGTTACCTATTTAGA

          CTGACTTAGATAGCGAAGTATTAGCCCATTTCCTAGGTGC
          CTGACTTAGATAGCGAAGTATTAGCCCATTTCCTAGGTGC
          AAGATCTAACTGATATCGCATTGGATTGACCACTTGGCTC
          TAGACTGATTTCGCGTGGCGTAGGACTGTTCTCTAGCCTC
          CAGGTTGGTCCGGAGTCACGCAATTCCCTCTTTCTGACCT
          TGAACTAACTTTGTGCGGGATTAAGTCATCCTCGTAACCA
          TAATCGGAAACTACCTGGGAGAAGTATGCTTCTTAGCCCC
          CGGCTAGACAATGTTGAATTAGAGTCCGCGGACTAGACTT

