 8 1000
t1        CGATAAAGCAGATTTGCTCCGCCACATATGCTTACGAGTGAATGTTCAATCCTCGCCTTC
t2        CGATAAAGCAGTCTTGTTCCGCCATATATTCTTACGAGTGAATGTTGAATCCTCGCTTTA
t3        GGATATAGACGTACTGCTTTGGGAGGCATGTTTACCAGTAGATGCTGAATTCCGGTCTTC
t4        GGATAGAGTTACCACGCTCTTGTGGAAATGTTTATGCGTGAATGCTGCATTCTTATCATT
t5        AGATGGAGTGAGCAAGACCTCCTTAAACCCCCTTTAAATGTCTGCACGCCGCATTCCTTG
t6        AGATGGAGTAAGCAAGACTTCCTTAAACCACCTTTAAATGCCTGCACGCCGCATTCCTCG
t7        CAGTGTAAACGACTTAACCCTGCAGTAGTGCTTCTGTAAAAATGTCGACTACTTAGCCAC
t8        TTACGTAATTGAATCATTTCTGTAGGGCCGCCCCCGCGTGAATATAAGTTACCCAGTCAC

          TTCAAGTCACGTATCGATACTATAAACATCCGTACGAGAACCTGTGTTTGGTACTCACGA
          TTCAAGTCACGTACCGATACTGGAAATATCCGTGCGAGAATCCGTGTTTGGAACTCACGA
          TCTAAGCCCTGTACCATGGTTATAAACATCCGCCTGAGAATTTGTGTTCAGTACTAAAGA
          TTGGAGACATCTTCCAAGATTTTAAATATTTGTGTGAGAATCTATGTTCAGTACTTAGGA
          ACGGAGTCATGTTCTCTAATTATTAATACCCGTACGAGACACTGTGTTCACCACTTAACA
          AAGGAGTCATGTTCTCTAACTATTAATACCAGTACGAGACACCGTGCTCACTACTTAGTA
          AGAAAGTTACGTGAACAACACCTTTACAGCTAAGCGAGGAGCCGCGACCTTTATTTCCCG
          CTGCGACCATGTGAACAAAACACTCTCGATTCAACATGATGCTGAGGCATCTCCTGCACG

          CAGACCACAAGACTGCTTAAATAGACCCCGGACGGATTCCCAACTCCCCTACGGACCTTA
          CAGACCCCAAGACTGCTTAAATAGACCCCGGAAGGATTCCCAACACCCCTACGGATCTTC
          CGGGCTCAAATACTTTCTAAATACGCTCCGGTCGAGTCTTCCACCTACCTGCAGACTTTA
          TGGGCCTTAATACTACGTGCATATACTATGTAAGGATAAACAGCGTACTCGACGGCCTCT
          TGTGCTCGATGATGGCGCCAAGTGTGTTCCGAGGGAGTAGGAACGACCTCATCGGATTCC
          TGTGCCTGATAATGGCGTCAACTGTCTTCTGAGGGTGCACGACCGATCTCAGCGGATTCC
          AGTGCGAGGATTCTCGGAACGGCAACTCGGCCGAGTCATCCGAATTTACTTCCAGGTCCC
          GGCGTCGGCTCCTTCGAGACAGTAACCCCGATGAAATCCTCTAACTTTCCTTAGTGTCGT

          CAGGCTCAATTAAGCTCTGACGGTGTGTGCTGTAGCCGCTCCCCGGCCCCTTAAAAGTGC
          CAGGTTCAATTAAGCTCTGACGGTGTGTCCCGTAGCGGGTCCCCGGCCCTCTAGAAGTGC
          TAGGTTAAATTCAACTCCAACGGTGTGAGTCATATAGCCTCACCAGTACCTTCAGAATGT
          TGGGCTTAATTAAACTCTCTTAGTATAGGTCATATAACCCCCTAAGGCGGTTGGTGATGT
          CGGGTTCCACCAACAGCTTACGGTACTCGTTATGCTGAACTACCAGTTGGTCAAGCAGGT
          CGGGTTCTACCAACATCTTACAGTACTCGTTCTGCAGAACTACCAGGGCGCCAAACAGGT
          CTGATTTCCGCGGTCTTGTGCAGTGTCGCTAAGGTATGAACCTTAGCGTCTCCAGCGATT
          TAGGTTATCGCGTATGCCGGAAACCGCGATTTTGTATGATTTCCGCCAAGCCAAGCGCAT

          CAGTGGAGGTGGCTTAAACGTTGGTCTTCCGTAGCATAATGAACTTCATCAGCTCTCATA
          CAGGGGAGGTAGCTTAAACGTCGGTCTTCCGTAGCATAATGAAATTCATCAGCTATCATA
          AAGCAGAGGTACCTTGCGAGCTAGAGTTAAGTAGCATATATAAATTTTTCGGCTGCCGTA
          CTGCTGACGTGGTTTGGGCGAAAGTGTTCGGTAGATTCATGAAATTTATGGCTTGGCATA
          CCGCACCGGTGGTATGAACTTTACTCTCCGAGGAGAAAGTGATACTTACGTGCTTTCATG
          CCGCACCGATGAAACGAACGTCTCACTCCGAGGAGAAAGTGATACTCACGTGCTTTCATG
          ACGCTCGCGAAAATAGCGATACCAGCCGTAGTCTGAAGAGCTTGCTTGCTGGCAATGGTC
          GTTGTAGAGTTAAGTTTCATCCGCATAACAATGCGAAAAACAAATGTGCGGGGTACCGTT

          TTTATCAGCTCCAACATTGAGGCTTACCGGGGGTGGGCGATGGTATAGGAATGGGAACGC
          TCTATCAGCTCCAACATCGAGGCTTACCGGCGGTGGGCAACGGTATAGGAATGGGAACGT
          TGTATCACTTCGGGCACAAAGGCCCTACAGGGTTGGGTGGTGACATAAGAATAAGAATGA
          CGTATCACCAGCAGGACTGAGGCATAGTAGGGCTGGGAGATAATGTAAGAGCGAGGATGC
          CATGCTTGTTTTAATCTTGGTACTTAATGGGGCAGGAGGAAAGCCCAGAAAAGGGCAGGT
          CATGCCTGTTTTAACCCTGGTACTTGATGGGGCAGGAGGAAAGTCCGGAAAAGGGCAGGT
          CGGCGAGGCATAAGCTCTTAGGCTGAGAACGGAGAGGGGGAGACTCCCGGATTCTGGCGG
          ACGTGGGGTCTAGGCTCATAGGAGTAGAGCAACGCGGGGGATATTCGCATCCACCCGTGG

          TCACGAGCTGCATGCAAAATACACGTGCGGAACCTTTCTCCGTGCCGCCTGAGTCCCTAC
          TCACGAACTGCATGCAAGATACGCGTGCGGAACTTCTCTCCGTCTCGCCTGAGACCCTAC
          TCTCTAACTGCGTGATGGGAACGAATGCACAACCCCCCCCCGTGTCGCCTGAGACCCAAC
          TCGTTTATCACGGGAAACGGTTGGATACGCTATGTCACCTCGTATTACCCGAGCTTTTAC
          TCGCAATACGTGCGGCTTCTCCGAGAGCGTGATGCGGCCGCGGTTTAACGGCAACCTGAC
          TCGCAGCACGTGCAGTTGCTCCGAGAGCGTGATGCGGCCGCGCCTTGGCTGAAACCTTAC
          CTAACGTAAATAAAAATGCCACCCTTGTTGAGAGTACGCATACACACTCCAGGAGGATAA
          ATACCATCACTGTGCCCGCTACGGGTATTAAGAAAGCGCAGCCATAGCTCAAAAGATTGC

          ACATGTACTGATGTAGCCCAAAAAGTTGACCCATTAGCCGTTACCCGGTCCTACACCCCC
          ACATGTATTGATGCGGCCCAAAACATTGACCCATAAGTCGCTACCCAGACCCACACGTCC
          ACGTGTCTTGGCATGGCCTAAGACGCTGACCCATTAGTCGTTATCCGGTCCCACCCGTTA
          AAATGTACTTCCGCAGCATATGATGCGGGCCCGTTAGCCGTAGTCCGACCTCGTCTGTAC
          GGACCCAGCGCTGTAACTCAAGTCGGGGACCCTCTAAGCGCCAATTGGCCACCTACCTCT
          GGATTCATTGCTGTAACCGAAGTTGCGAACCCCCTAAGCGCCAGTTGGCTACCTATCTCT
          AGCGGTAATATTGTAAACTGAGGATATCCCTCATAGGACGCAGTTTAGCAAAGTCTCTTG
          CGACGTCTTTCTGGAACTTGAGAACATACCCGGCAGAACATGGTCGAGGCACTATAACCG

          AGGCGATACATACTATGAGAACCCAAGAGACGTGACCCCAACCGTGTACGTGCGGCCTAC
          AGGCGACACACATTATGAGAACCTAAGAGTCGTGACCCTAACCGTGTACGTGCGGCCTAC
          AGGTGATTCACAACAATGGGCCACACATGGTGAGACCTCAACAGAGCAAGTACGGTCTTT
          GGGTGACGACCAATGATAAGACCTATAGAGAAGGACCACGGTTGCGTAGCCCCGGTCTTC
          GGGTTGTTTCTGTCCTTTAGATCCGTAGGATAGGTCGCCGACCGAGCTCGTCCGGTCCTT
          GGCTTGTCTCCGTCCTTTAGATCCGTAGGATAGGTCGCCGATCGTGCTTCTACGGTCTTT
          ACATACTTGCTCATGTCCAGCCTCAGCGACCGAAGGCTTAGCCGCATTGACTCCCCGTTC
          GGATACCTACTGATGTTAAAGAGCGAAGGACGGGGCCTCTACCATGTCGGCCTCCTTTTT

          TGGTAAAGCCTACCTTCGGATCGCGCCAGCAATTTGGTTAGGTTCTCTTTTGCGTGCGAC
          TGGTAAAGTTTCCCTTCGGGTCGAGCCAGCAAATTAGTTAGGTTCTCTTTTGTGTGCGAC
          CAACAATATTACCCTCCGCGTCGGGCTAGCAATTGTGGTAAGTTCGTATTTGAGCGCGAC
          AGCAAAGGCCTGCCTGCGCATTTAGCTAGCACTTCCATCAAATTCTTACCCGAGAACGCC
          GAACCGGGTACCTACACTAGCGACGGTAGCACCACGGAGAAGACCCTATTTGTCCGCACC
          GAGCCCGGTACCTACACTAGTGACGCTAGCCCTACGGCGAAGACCCTATTTGCCCGTGCC
          ATGTAGAACGTCGTGAATCACTAAGTCTGCTCGATAGGCTCGCTTCACAATATGCGTGGA
          GTGGAGGACTGTCTGTTAATTTGAGCCTACTCGGTCGATACCTTTCGTCCTTTGCAACGA

          TGTTAATGGGCATCTTCACTGCAAATGAACAGAAGTTTATAGACTTATACCCTCGGCGCG
          TGCTAATGGGCATCTTCACTGCAAATGGACTGAAGTTTATAGACTTACACCCTCGGCGCG
          CGCTCGTGAGCATTTCCACTGTAGGTGGATAGGGATCTATATACTAACTACCCCGCTACG
          AGTTTATGGGCGCTTTTACTGTGGGTAGACAGGAGTTTATACAGCACAACCCCCGCTGTG
          GGTGAACGGGTATTCTCACGATGTGTAGATGGGATTTTATACTTAGAACGGCGTGGTGCG
          GGCGAGCGGGTACCCTCACGATGTGTAGATGGGATTTTATACTTAGAACGGCGCGGTGCG
          GACCGATAAGTTAGTGCGTATCAGGTTAGCCATACACAGTACTTTGGTGGTAGTATGTCA
          AACTGATAGAAAAATAAACTTCGTGGCATCCACAAGCCGTTCCTCAGCGTTATGAATAGA

          CTTGTTGTTCGTTGCACAGTCCTAGTTCAGTCACGTTCGTTCGCTTATTTCTATGTGCCT
          CTTGTCGTTCGTTGCACAGTCCTAGCTTAGTCACGTTGGTTCGCTTATCTCAATGTCCCT
          CGTGTCATTCCATGTGCAGTTGTAGTGTACTTATGATCGTTCGACTGTTCATGTGTCTTC
          CCTGTGGTTCGTTGTAGGGACCCCAGCTACTCGCGACCGTACGTGAATCTCCACTATTAT
          CCTGTTGTTGGGCGTGTGACTCCAAGGTGGTAATGTTAAGTTAACAAATCATACAACTAC
          CCTGTTGCTGGTTGTGTGATTCCAACGTGGTAATGCTAAATTAACAAATCATACAACTCT
          TGGGGCATCATTTTCTGGTTCGGACTCCAAAAGTGTTTGGTTACAGACATGCTTGTTTCC
          CGAGGCGCCACTTTTTGGGCTATCCTTTCAAAGTGTCTGCTCACATACCCGTCCAAATTA

          ATAGAAGGTACAAATACTTAACACGGTACTCTTGGCGTCACCGATTCCTTTGAAGTGATC
          ATAGAAGGTACAGATACTTAAGACGGTACTCTTGACATCACCGACTCTTTTGAAGTGATC
          AAAGATGGTACACCTACCTAAGAAGGGACTCTTGGCAACTGCGATCACTTTCAAGCGACT
          CAAGGTGGCAAATACGCGTAGGACGGAACTCTTGACGTCTATATATTGGTTGTAAGAAGT
          AAGGGCACAACTCCCTTTTTGGTCGACCCCCTTAGCGCTCACGGCTTCGGCAACACTGGC
          AAGGACACAACCCGTTTTTTGGCCGACCCCCTTCGCGCTCACGGCTTCGGCAACACTGGC
          TACCGCACATTGCGCCGGGTGGCCACAACTACCGGTGATGCGGGCGCCGGCCAGGTTATC
          GATATAACGACCCGCTAGGATTTTTATACTCCTGGTGTACTGTGGGTCAGTTAGGATAAA

          TTGCAACTCCTGAGCGAAGCAAGGTCGAGGGTCGATACGCCATCGACTGCTATCGCAGTC
          CTGCTTCTCCTAAGCGCAGCAAGGTCGAGGGACAATACTTCATCGACTGCTATCGCAGTC
          CTGCGCTTCATGAGCGACGCAAGGCTGAGAGTTGGCACACCATACATTGCTATCGGATTC
          ATACCACTTACGTGTGAGGCGAGGTCGGGAGTTACCAATACATATATTGTTGCTAGTATA
          CAAGCTCCTCTGGCCATGGATATGTTAGTTGGTCTTAACCCCCATATATCTATCTGAGTG
          CAAGCTCCTCTGAGCACGGATAGGTTAGTTGGTATTAACCCCTAGATATCCATCTGAGTA
          CTGTAGCCAATCAAAAGGCGGAGCTTCTCTGGCCCCCATGTACCTATCATGGTACAGGCC
          TTGTACAATAGGGTCCAACGATTTTGGCACCGCCCGGGGGCTCCCTGTGGGATCCAAACT

          TGGTTGATGCCAAAGAGGAACTTCGTGACAGCGTTGCTGCCCGTTTGATTGCTGGTGCAA
          TGAATGAAGCCAAAGAAGAACTTGGTGACAGCGTTGCTGCCCGTTTGATTGCTGGTGCAA
          TAGTCGAGGCCTACGTAGAACCTTATGACAGATTTGTCACCCATTTGAACAGTGGAGCCA
          CGGTACAAGGCGTCGCGAAACCTTTCGAAAGTGTCCATGTTTATTGTGCTAGTAGAACGA
          GGGGTGTAGGGTAGAAAGACCCCTTCCGGAGCATTTTCTTTGATCGTAGCCGTGGGACGT
          GGGATTAAGGGTAGAAAGACCCCTTTCGGAGCATTTTCTTTGATCGTACCCGTGGGACGC
          CTAGCTGTCAGTACGAAAACCTAGCGTGCAGGTCTGTTGTATAAGCTTCTTGGCGTACAC
          CAGAATCGCAGGATGGACACCCGAGAATGAACACATCTGGGCAGCCTTCATGGTGGCGGA

          GAATGTGTCAAAGGTGGTTATAGGACGTAACTCGATGTAGTCACCTTCGACAATCTTTCA
          GAATGTGTCATAGCTGGTTATAGGATGTAATTCAATGTAGTCACCTACGACAATCTTCCG
          AAACACGATACAGCTGACTATAGGACATCGCGCCATATTGTCACCACTAATAATCTCCCA
          AACTACACTAATGCTATTGTTGGGAGGCTAACTATTGCAGTTCCTTTCGATAATTTTCCA
          CGATACTCCACAGCGCGCTCTAAAGCAGTAATTATTCTCATTCTCCCCAAAAGATAGTTC
          CGATACTCTAACGCGCGCTCTAAAACAATAACTATTCTTACTCTCCCCAAAAGATAGTTC
          GTTCAGCTTCCAACCCGTTGTAAGACACACGCCGGCAACTGCATCATGGTGGGCCCATTA
          CACAGTTTGCTGTTCTGCAAGGCAGCGCTCGCCATCAATAGTACCATTGACTGCACGTGA

          GTGGAATGGTCAGATATCTCACTACTCAATTTGAGGGCGA
          GTGGAATGGTCAGACGCCTCATTACTCAACTTGAAGGAGA
          TTGGAACAGTTAGATACCTATCCGCATAACTTTAGAGTGA
          TTGGTATAACCAAATTTTTGTCAATTTGACCGCGGGGCCA
          GCGGGACAATTCTACACCCATGCATATACGAACTGGGCGA
          GCGGGATAATCCTACACCCACGCATATACGAACTGGGCGA
          GCGCAATTGCCTGCTTTTTGCGCACGCGAGATCAGAACTA
          GGGGAAGAGCCTCACCCTTGTGGACTGGGACTTAGATCTA

