 8 1000
t1        ACAAATAGGCAGATTAAGTACTCGTAGCGGTATACAATTGTGCGCTCCGGCGCATAAATA
t2        ACAGATGGGCAGGTTAAGTATTCGTAGTGGTGTACAATTGTGAGCTCCGGCGCATTAATA
t3        ACAAATAGGTAGGTTAAGTAGTCGTAGTGGTGTACAATTGTAAGCTCCGGCGCAAGAATA
t4        ATAAAGAGACAGGCCAAGTAGATGCGGCGGTATTTAATCGTAAGCACCGATGCAAGAATT
t5        CAACTAGGAAGAGCCGTAACCTTTTAGTGGACCACATACACAGGTCGCGATCCTAGTTTA
t6        AAACTGGTATGGTTTCTGTCGTTCCAGTGGGATACCGACGAAGATTATGAAGAAGAGACG
t7        AGTAACGGGGGAGCTATCTTCTGTTTAGTGTCTGTGTTCAGTCGTTCCTCTACGATAATT
t8        AACTCCATGAGATTCACGCATCTTCAGTAGCATGTTTCCAAAAACGCCTTCAAGGCTGGG

          ATGGCGATAAATCTTGCCTACTCCAACACCACTTGCTAAAACAGGCTTAACACAGTCTAT
          ATGGCGATAAACCTTACTTATTCCAACATCACTTACTAAAACAGGCTTAATACAGTCTAT
          ATAGCGATAAATCCTACCTAATCCCATATCACTTACTAAAATAGGTCTAGCACAGTCCAT
          ATAGAGGCTAGACCTCCCCAAGCTAGTATTCTTTACTAGATTAGATCTAATCTCGTCTAT
          AGTACAGCCCCCCATCGTCGTACTATCAGCCGCGATAGCACGGAGACCCGCATAATTTAT
          TTTGTCCTCTGTTGGCCATCATACACCGTTCGTCTGCGAACGAGAGCTCACGTAGCCATA
          ACGATCGTATCTAGGGTCCACTCCAACCTTGGTATGTATATTGGCATCTAAAGTGGTCTC
          CGATTTGAATGCCGTGTTCGCGTAAGACGCGTTCGACGCTATGGAATGTCGCCGGTCGCG

          TTAATAGTGTGGAGCGACTCGAGCTATTTTTCCTGGTGGCATCCTATGTATAGGTTCCGT
          TTAATAGTGGGGAGCGACTTGAACTACTTTCTCTGGTGGCCTCCTATATATAGATTTCGA
          ATAACAGTGTGGAGTGACTTGAACTATTTTTTCTGGTGGCATCATATGTACAGATTCTGA
          CCAATGGTGCAGAACGACCTGCGTTGTTCATCACGGTTGTGTTTTCTATATAAATTCCGC
          ATGTAAGTACTATTTGTCGGACACGGTCTATTGTGATAGCTATTCTCGTCCAGGTCATGG
          CAACAAAAATGGTAAGTTCAATACAGTCCCCTGCGCGTCTATGCTACGCTTTGGGGCGAT
          TGGGTAAAGGGTCGCCATTCCCTCTGATACGCGTGGAGCTAGGTTTTGATCAAGTTTAGC
          CCGACAAATTGGTGTAGTGCACACTACTGTGGACGGTCTTTTTATCCTGCGGCGACTCGC

          ACTCAGCTGTTGAAGTTAGCGTACGCGATGAAGTAGGGAAGGATACACGATTTGGGCATT
          ACTCAGCTGTTGTAGTTAGCGTACGCGATGAAGTAGGGGAGCATACACGATTTGGGCAAT
          ACTCAGCTGTCGAAGTAAGTGTACGCGGTGAAGCAGGGGAGGATACACGGTTTGGGCATT
          ACTTAGCCGCTGCAGTAAGTGCACGTAATGAGAAACGACAGCAGATACGATTTGGTCCTG
          ATAAAGCCTACGTTCATCGTGAAACTAACGGGGGGCAGTGGATCATCCAATTTTCGGATT
          AGGGGGGTGTAATCGTATACGCGTGCGATGAGCTGCATACTGATTTCCGTTTCGATGTTG
          AAGAAGTCGGTGGCGTCAACGTTTGTCATGGGAAAAGGGCGGACCGCCTGATCAGGAAAG
          AGGACCAATATACTACTACTGTATTTCCCATGAGGGGGGAGGGTAGTTAACCCTAGATTC

          GACTACACAGCACGCTATCAATACTTTACCTCGGTGTTGGTCAATAGACGTTTTAAGTCT
          GACTACGCAGCACGCTATCAATGCCTTACCTCGGTGCTGGTCATTGGATGCTTTAAGTCT
          GACTCCACGGCACAATACCAACACCTCACCTTGGCGCACGTCAATGAAGGGATCAAGACA
          GGCCGCCCAGCTCAATTACAGTACCCTTCCTCAACGCGGTCTAGTCGAGACGCTCAGCTG
          GCGTGGCCAGTGTCGTACCAGCGCTCAACATCTCCGCAAGCAGGCCGAAGTGACTCCTCG
          CTATGTTCGGCGTTAAAACTGGGTCTCATGATTGGATTATTTCACGTATGTATTCGGGTG
          AGGCACCATACATAGCCATAAGGCATTATCCTCGTCCGGGTCTAAGCATGGTTGTTGCCC
          AGGCGACTGGTGCTGGAGCCGTGCATGGTGAGCGAGAAGGCTCGTGTCTCGACGGCGTCC

          GGTGTATGAGGCTTTGTGACATCCTGTAGAGGGTCTGAACGCGGTTAAAATACCTCGATC
          AGTGTATGGGGCTTTGTTAATCCCTATAGAGGATCAGACCGCGATTACAAAATCTTTATC
          GGTGTATGAGACTTTGTCATCTTCTATAGAAGATCAGATTACGATTAGAAAACCTCGACC
          GTTGTATGCGGCTTTGTTTTTTTCAATAGCACACTGCATAGCGCCAACATAATCTTTACT
          GGGGTCGCTGGGTTAGTTCGCCTTTTCTCGCCATCCCACAGGAAGTAAGTAATGTTATTG
          AGCCCAGACCTGGTAGATTACCTCTCACCGTGCCCGTGCAAGTTGCCAGATCCGTCTATA
          ACTCCAGAAGGGACTGGAAATCCGGATAAGTTATTTCATGAAGATGGAGCTATACGCGGA
          GATGCAACTCGAGCTGTGTGCATTTTAGCTGAAATGAACAAAAGCCCGAAAGCGCTGGCC

          GTTCAATCCTGATAGGATGATTCTTTCGGGAGTAGTCGGTATGTTTGTCCATCAATCCAC
          GTTCAGTCCTAATCGGCGGATCCTTTCGGAATTAGTCAGTATACTTGTACACCAATCCGC
          GTCAAGTCCTGATCGACGGATCCTTTCGGGATCAGTCGGAATGCTTTTTCATCAAGACGT
          GCGCAGTCTCGATCAACCAATCAATTGGGAGTTAGACGGTATGATTCTTCGCAACCGGGA
          TAGCACTTATGCACATACTAGTTCCCGTGTTTGGGTAGTCACGTTGGTATATAGGTCTCA
          CAGTAGTTTAAAGTGGGCCGTGCACTCTCTGTGCGATAAAACATTTGTAAACGATCTACC
          GCTCGCAACTCGCGGGTTGTTCTTTTCAACCTGGAGAGTCCTGTCCCTATCTGATTTTAT
          TGGCACTCTCGCTCGACTGGACTTTATGTCTACCGGCGGCCCCCCGTAAAATAGTAACAG

          TAATGTCAGAGCATGTTTAGATTAGGATGTTGTGCCCGGGGGACACCCGTAACTTAATGT
          TACCGTCAGAGCATTTTTAGATTGGGATGCTGTGCCTGGAGGACATCCGTAACTTAATGT
          TTACGTCAGAGCCTGCATAGATTAGGAAGCTGTGCTTGGAGGAAACCCGTAACATATCTC
          TCATTCCATAGAATTTATAAATCTAGCTGCTGTGATTAAGCGGAACCAGTAATTCACAGT
          ACATGATATAGGACACGTAGTCCCGGTAGTGACCCGTCGGATACTCTGCCGGATTGCAGT
          ATACGGGATTGCCAACCTCTGCTAAACACCGGCGTCTATGGAACTTCAGTAACTCGTGGA
          TTACACGTTAGGGAGCGTCCGTTTACGTAATAATGCTGAGGAGGTTTCAGGGTTCCGGGA
          AAGTATCGCAACGAGCACCTGTTCAATAGCCATATCCGAAGGCACCCTGGGGGCGGTACT

          TAAAGCCTAGCGTGTTTTGTGGTCCTTAAAGTACCCTCGGCTGCTGCATAACCAGTCTCG
          CAAAGTCTAGTGTGTCTTGTGGTCCTTGAAGTACCTTCGGCTGTTTCATAACCAGCCTCG
          TAAAGTCTAGCGTATATAGTGGCTCTTGAAGTATCTTCGGCTGCTTCATAACTAGCCTCG
          TGAAGTCCAGTCCGGCTTGTGGTTCCTGATGTATCTTCAACTGTCTCACCAATGGTTCTA
          TTAGGGAGCGTACGTCAGGAAGTTTACGGGGTATCCCCGAACTCATGTAGAGGGTCCTCC
          TGTTGGTTAATAAATTCGTATGCCTGTTTCCCTCACCCCGGCGCATACCGCGCCCCCCTA
          ATTTCGTGGGTTAACTTCCTGGTTTAGCCGCATACCCTTGATGGACCTCGAGTGAGTTTC
          CACGCACCATCGAGTTAAAGGGGATCGATGTCGAGTCGTCGTTCTTTCCCAGGCCCTGAA

          CGCTAGAAGGTTGTTGTTATCGTAGCCCCCCTATAAAATGTCAAATAAAAGTCACGTCAT
          CGCTAGAAAGTTATAGTTACCGTAGCCCCCTCATAAAATAGTAGATAAGGGTCACGTCAC
          CGGTAGAAAGTTTTTGTTATCGTAGCCCCCTAATAAAATGTCAGCTCAGCGTAACGTCAT
          CGGTAGGGAGCCCATGTCCTCATAGACCCTTAATAAAATACCAGAAAAGAATTATATCTT
          AGGAGAGCAACGCACGTGGAAATAGCTCTTTCTTGGGAATATAATGTCAGTCCAAATGTA
          TAGCGGCCGATTTTTACGGTCGCCAGATTTCATGTGGACCAATTGGAGCGTCTGCCTAAG
          AAGAGTCTGATAAGCGCCAAATCTTTCGATTCCGGACACCCCAAAGTAAATCTGTGTACT
          GTGCAACCGATTTGCCCCATGGTCGATCTGGATAGGATACCAAATCCAGATATATCGATT

          GATTGGATCATCGCGCCATAACTGCTCAACATTGGTAAGTTCTCGGGTCTCCTATTTACG
          GATTAGATCATCGCGCCATAACTGCTCACCATTTGTAAGTTCTCGGGTCTCTTATTCATG
          AATTGAATGGTCGCGCCATAACTACTCCGCATCTGTCAGTTTTCGGGTCTCTTATTCACC
          GAGCGGTTGATCGCGAGACAGTTTCTCCGCATCCGTAAGGCTAAGAGACCTCAGTTTACG
          AATCACTCATCTTGGCACCCACCGCTTGGCCGCCGTAGTGTCTCTCAGTCAGATTTGACT
          TTGATCGCCTGTCATAATTGAGTACGGCGTCTTCAAAGCTATGACGATCCTAGGGCCCGG
          TTATTTGCCTCACGGCAATGGTGGTGGGGCCCCCGACTGTTGGAACCATGCACGTTCCAG
          TTTCGTGCACGGTAGATATACTGTATTGAGCGACAGAAGCAAGCTCGGCATCAGCTCGAT

          AAGTACTCGGGAGGCGGCTCTATTAGAATCGTGCGGCGTATCTTGCGTTCAAACCAGCAT
          AAGTACTCGGGAAGCGGCTCTAATAGAATCGTGCGGCGTATCTTGCGTCCAGACCGGCTT
          TAGTACTGGGGAATCGACTCTAGCAGAATCGTGCGGCGCATCTTGCGTTCAGTTCAGCCT
          ATGGGCTTGGGACGCAACTCTTCTAGGGCCTTAAGACATGTCACGCGTTCAGATTGGATT
          GACCGCGAGGATGACAGGGCTCTTGAAACCCCTCCAGGACCTATTGTGAAGCTGCCCGCT
          ATGGCATCGGGAGGCTCTTCTTCTTGACCCTCGTAACTGGTTAAGTATAAGGTTCAACTT
          CTTGGGTCGGGGGGCTGTCTTCTCCAACTCTCTCGGAGCTTAGAGTACCGGCAGATCGAC
          CACGATCGGGACATCGACTTTCTCTCTTACTCTCGCGTTGCGATGCTAAGGACAGGAGCT

          CATCTGTCGGGCCCGGCCCCCCTAAAAGGAATGCCCCCGTCCTGTGGGCTCAGCGCTTAG
          CGTCTGTAGGTCCCAACGCTCCAAAAAGGAATGCCCCCGTTCTTCGGGCTCAACGCATAG
          CATTTGTTGATCTCGACGCCCTAAAAAGCAATGCCCCTGCCCCTTGGGCTTAGCGCATGG
          CGAGATATGATCCCGCCGCCCCGGAGAGGAATGCCCCTATCCCGTGGATACAGCGCATGA
          CGAATGCCTAGTTCTCCATTTGTATTATACACACTTTCATGTTCCACACCAAACGGACGA
          CTTCCAATGTGCCGTTCGACTACACTCGGTGCATCGGTGCCCTCCGTGAGACTTGCCTGC
          CGATAAGCCGCGTACATTATCATGACTGCTCTACCCGTAAGTCCTGGATGACATAGTTCC
          CCAAAGGCCCGTTGCTTTTGCGAAATCGTGCTCCCGAAGCTCAATGCACAGACCTAACGG

          TATCCCTTGCGTCGCGGAGCCCAGAGAGTGCACGACCATATTGTAATCGCTCAACCCGAG
          TGTGCCCTGTATCGCGGAGCCCAGTGAGTGCCCGACCATAAGGCAATCCCTCAACACGAA
          TGAGCCTTGCATCGCGGAACTCGGTGAGTGTCCAATCATAAAGCAATCGCACGATACGAA
          TGTGCTCTACTTCATTGAACGTAACGGATGCCCGCTCAATAAACAGTCTCTAATCATAAA
          AATAGACGACATTAACGAACATGCTTGAGGGTTGGCGACCACAAGATACCTCTTTCATAG
          AGGAGTCCACCCGATTGAAAATGGGTGAGGAAGGCTTTTCACATTACCTCTTGTCCAGAA
          ATGAATTGATAACATTGTAGGCGGCCGACGGTGATCCTTGACTTTTTCCCGCCACACCTT
          AACATTGAATACCATAAAGAAAGATTGAGGTTAGTACCCGGGACTATATGTAGACTATAC

          ATTAGCCCGTTGCAAACAGACATATGCAGCGGTACCAGGCATATGAACGATTCCAGGAAC
          ATCAGCTCGCTGCGCAAAGACACATACAGCAGCGCCAGGCATATGAACCATTCCAGGAAC
          ATCAGCCCGACACAAACAGACACATGCAGCGGTACCAGGCATATGAACAAGCCTAGAAAC
          GCTAGATGCTCGCAAGAAGCGACATAAAGCGGCCTTAGTAATACGGTTGTGCCTAAGATC
          AATGTACACTAGTGGTATAGTGCGAGATGTGAGTATTACTAAGCGATTCGTTCCCAGGAA
          GCCGTGCTCCAGCAGCACTATTTGTTATGAGTATTGATGTTCGTGGTCCATTAGCCAGAG
          ATAACGTTTCTCACGTAGGAAACATAGAATTACAATGACGGAGTGATGTAAGCCCTGAGC
          GTTGCATCCCAATCGTGAGGTGCGCGAGTGAGACTAGGCTATTTGACTAGTCCCATGAAC

          GCCAAAAGGACTGAAGGACACCAGGAAGGGTCCGTAAAACTTGCGAGTCGGCTTTAGTTA
          GCCAGAGGGACTGAAGGACGCCAGGAAGGGTCCGTAAAATTTGCGAGTCATACTTAGTTA
          GCCTGAAGAACTAGAGGACTCCAGGGAGGGTCCGTAGAACTTGTGAGTCGTACTTCGTTA
          GTTAGAGGAGCGAGAGGATATCGAAAGGGGCCCGCAAATCCTATGACTCTAACCCAGTCG
          GTAAGGACCATCATGAGGGGCCACCAGTAGATCTGGGTTGTTTGAGAGAAGCTCTAGAGG
          GGGAGACGACGCAGGCGACATAATACGGCGGTTGGAGCCAACAAGTCTCGAATGGTTGGA
          GTTCAGTCGTCGTATCCGCGGTGTATCTTTGCTAAGATCTCTGTGCACAGATCCTAGAGG
          ACATGACAGCCGTAGAAGTAGTCCCCTGATATCTCTGAACGGAGTCACCAATGAAACAAG

          TCATGTGGGGTAATTTCTAACGCGGGCCGAGGTGTGCTTC
          TTACGTGGGCTAATATCTAACGTGGGGGGGGGAGTGGTTC
          TCATGCGGGCCAATTTCTACTGTGGGAGGGCGAGTGGTTC
          TAAAGTAGAATTCCTTCTAGCTTGGGAGAGGCAGACGTTC
          TTCTATGCGCCAGCTATTCCTATCGGGGATGGGATGGATC
          GTAGTGGGCTCGTCCTTTGCCATCAAACGGGGGGCAGTCT
          TCGCACACAAGCGCTCCTTGCGTTAAAGACGAGACACCTT
          TGGTCTAGACCGATCTCCCCCACCGAAGACGGTCGCGGTG

