 8 1000
t1        ACTATTTGCGGTTCATTGACGCGTTCGGAAGCCGTATACACCCAACTGTTGTGATATAAT
t2        GTCACGTGCGACAATTTTCTGTACTCCGGTGCTTAGTATCCACGGCTCGTACGGTATGTT
t3        ATTTTCCGCCATAGACCACCCAACTTCATCGCGCTCTATTCACATCTGCACAGTCTAACC
t4        ATTCTACGTCATGGGTCACGGAGCTCCACCACGCTCTACTCACATCTGAACAGTCTAGCC
t5        GTCAATCATCAACGGCTTTTAATCTTAAACGCTTTGCATCGACAAATGCCCCGAGTTGAT
t6        GTCTGCCACCGACGATCATCAATTCTAGACGCTCTGCATCGGCGACTGCCCCGAGAGGAT
t7        GTCCTCTCCAGCTGATATTAAAGCTCGGGGGCCTTCTGTTAGCCTACGCCGAAAACGGCA
t8        GTCCTCCCCAGCTGTTACTAAAGTCCGGGGGCCTTCTGTCAACCTTCGCGGTAAAAGGCA

          GGCATTCCGAATTCCGGGACAACCCCGAACACCACCAACCATTTCCGTTCATGTTTTCTA
          AGCTTCGTTCATCCCGAAACGCTCACGGTTGGTACAGCCTCATTACTATCGCATTCCTCA
          GGCTCCTGGCCTGACGAGGTAAATGGTGACACCGTTGTCATCCCGTACTCACCGTTCATC
          GGCCTCTCGCCTGGCGAGGCCAATGGTGGAATCGTCGACATCCCGTAATCCCCGTTCGTC
          GCCCATACACAAAGCTCGTTACATACCCGTACCATTGCTCACCTACGTCTCCAGTATCCA
          GACTATAAGCCAACCTAGTCACTTATCTGTACCACTGCTCAGCCACACCTTCAGTATCTA
          AGCGATATATTTTATGAACATTCTCTACGCAAGATTCCTGGCACATACTTCCGACTCTTC
          AGTGTTACATTTTACGAACCTTCTTTACGCAAGACTGATAGCACATACTTCCGACTCCTT

          CCATGTGGAAGTATCTCTAGATGTTTCAGCCGAAGAGTTCCGATCTAGTTCTCAGAGTTT
          TTTCGTGCAAGTTGTACGCGAAGGCACAGTTTAGAAGCATAAACCCAGTTATTGGACTAC
          TGCTTTGCGGGCTTCTTGGGTCGCACCCGCTTATGGGCGAAAGTCCATTGAACTAGTTCT
          TGCCTTGCGCGTTTCATGAGTCGCACCCGACTGTGGGCAAAAATTCATCTAATTAGTTCT
          TTTCGGGTTAGTCAGGGAGGTTGGAAGCGCTTTCGGACGATCAGTAAAGCCTTGAACTCC
          CCCCGAGTTAGTTAGAGCGGTTCGAATAATTTTCGGATGACCAGTAAAGCCTTGCACCGC
          CCATACCTAGGTTAGGAATGAGGAATGGGATTACCGCTTAGGCCTATATTTTTCCCCTCC
          CCACACCTTTGTTAGGAACGAGGGAACAGAAAACCGCATAGGCCTGTATTCCTTCCCCTC

          AAAGGTCTGCCGCATGTGCCATAGCTAAATCCGATGCGTACGGAACAATAAACGCGAGTG
          CGAAGTTATAAGTGCCCCCCGGGACCATCCCTAAGGCGAAAGTTTTATCAATATCAGTCG
          ATATGCAGGACATACTTATCTAGACCAGCTACGCTGCGGTCGAGGACTGGACTTAATGCA
          ATATGCAGGACATACTCATCTAGATCTGTTACATCGCGGACGAGGAGTGGGCCTAATATC
          AGAAGCATTCACCAAAATTGTGCGCTAGGCTAGGTGCGTTTATGCCCTGCCCTTACTCCG
          AGAAGCAAACACCAAACTTTTGCGCCAGGCCTGGTACAGATATGCCCCGCACTTGTGTCA
          TGGAAGTCCATCAAAGAGCCTGTGCTAGCCATGGTGCATGAGCGTGGCACGTATGCGTAC
          AGGAGGCACATCAAAGAGCTTGTGTTGGCCATGGTGCATGAGTGTGACACGTATGCGCAT

          ACATCGCGTTTAGACCTCATCCGGCTGTTTCACACTCTCTCTGGTCAAGTTGTGTTTAGG
          ATGTGAAAGCTTGGCGTGGTAGTGCCGTCCTAAATATACGTCGGAGCAGGTAGGCTAAAT
          AGGTAGAAATTCTTTTCCCACCGGGCGAGGTGTAATTTCGATTTAGTAGGCCATTTTAAC
          AGGTGGGAATTTTTTCTCAACCGGACGAGGTAGAAGTTCGATTTAGTCGGCGATTTCAAT
          AAGCTAGGGTTCGTTACTGAATCCTTTCTCCGGTCCCTTGCCGCTCCTTAACTTATCGAT
          TAGTTAGGGTCTCTTACTGAACCATCTTCCCGGTCCTCTGCCGCCTTAGAACATGGCTGT
          AAGCGATGACCTGAAGCTAAACATAACCTGTGTTTTCACGCTGTATTGGACCGCGCCAAC
          AAGCGATGACTCAAATCTAAACATAAACTGTGTCTTAACATTGTATTGCACCGCGTGAAC

          CCTACCAGGAGAAGCGAAAATGTGGAATCTCGCTGTGACACGCTCACTGTGAGACCTTTC
          ATTACAGGGCGGCAGGATACGATGGAGCCTGGGTGAAAAGCCTTCCCGGCGAGATCGCGC
          CTTAGCGCGTGATGTGGATGGGACGGTTCGTAGCGTCACATCATTCCGGTGCGGGGCAGA
          TTCAACACGAGGTGTGGACGAGGCGGCTTGTAGCGTCACATCATTCCGGTACGGAGCGGG
          TCGATTTCCAGACGTGAGCTCATCATACTTTCTGCTTAGCTTTTGTAGCTGAGGTATCGT
          TCAATTACTGAATGAAAGCTAATTATACCCACCACATGGTTTTTGTTGCAGAAGAATCGT
          TCCTCAAACAAACGAAAGAACACCGCATTCATAGATGGGTGCCAGTTGGCAAGAGCTCAC
          TCCTCAGACAAGCGAAAGAACACCGCATTCACGGAAAGGTGCCAGTTGGCGAGAGCACAC

          ACTGGAATACATTACAACCGTGCAAATCAGTGTAAGTTCATGGGGTATTTTACGCACCCC
          ATTGACACACTATGCGACCGGATACAGCAATGTACGATCGAGGGGTAGATTGTGGACCTC
          ATTTCCGTGCGCTAGGTCGCGAAGGAGTGACGCCAATTCGATGCGTCACTTCCGTGTGGT
          ATTTCCTTGTGATTAGTTGCGAAGGAGTGACGTCACCTCGATGAGCGACTCCGTCGTGGC
          ATTGGGTAACCGCGGATTCGGGGCGAGAAGACCGGGTCTGTGTGATAAAGCACGAGAAGT
          ATTGGGTAACCACGGGCTCGGGGCGAGAGGACCGGGCCTGTATGATTATGGACGCGAAGT
          ACAAGGTCGTCTCCATTCCGAGGTGTTTGCGCAGAGATCGTGGGGCTAGAGGTCAACAAG
          ACAAGGTCGCCACCATTTCGGGGTGTTTGCGCAGAGGTCGTGGGGTTAGAGACCAGCAAG

          GTTCGATCCCGTCTCCGAGATATTGGTACACCCGTCGTGTAAAGTCCGTTTCGTGGCGGG
          CCCTGACGTAAGGTGCGAATCACTGCTACTTCCCATTGTACAAGGCTGTCCTGTGGAAGA
          ATCCGCTTCTGTCCGCCAACCATCGATCGTGTACATACCAAGAAGTAGCATTGGAGTGAA
          ATCCGCCTTCGTCCGTCAATCACCGACTGTATTAGTACTAAGAAGTAGCATACGAGTGAG
          AGTCACAACGTGTATTGGGATAATTGCCCTCATGAGGATCATGGCCTGCCAAACTGGCAG
          AATTGTAACGTATATCGGGATGATAGACCTCATGAGGTTTAGGGCCTACAAGACCTGCGG
          GCTTGAATTTCTCGCCGATAGAACGGTAGTTTCGACGTGCTAACAAAAAAGCGACACGGA
          GTTTGAATTTCTCGCCGATAGAATAGTAGTTTCGACGTGCCAACAAAGAAGTGACACGGT

          TAGGTGGCCCAGAAATCCTAGATCCTCGCCGGATTCTATGTGGCGCGTCGCGGACGTTTT
          TAAGTGGTGCAAGACATCGGAACACCCATAGTCTTCCTCATAGTAAGCCACCGAGGCCAT
          TGAAGGGTACCGGGAAGCCAATTCACTATAACCCTTGATCATGCCCGCTGAGGTCGTCAC
          TGAAGGGTGCTGTGAAGCCATTTCACTATAACCCTTGATTATGCTCACTGCGGTCGCCAC
          TGTATGGCTGACTAAGTCAGACCCGCTGTCGTTAACTGTCTCACGGTACGTGAATGCCAC
          TAAACGGCTAGTTAACTATGATCCACAGTTGTTGCCATTTACGCGGTACGTAAATGCCAC
          CCTTCGACAAAATAATTCTATACTCTCGGTGATAACCGCCACATGCCCCATAATCGCCTA
          CCTGCGACAAAATAAGTCTATACTCTCGGTGACAACCACCACACGCTCTACAGTCGCCTA

          CGCGTGTACACGAAGATTTTGCAAGTTAGAAGGGGGTAACTGTCCTACGATCAGGTGGGT
          GGGGTGTACGGAAAAAGCCTATAGTATATGAGGGGGTAAAGGTTGTATCTCAGGTTGGAC
          TGGGAGTACAGTTCGATACCGACTTGTGGAGTGAGGCAGTTGTAACACAACATGCTGGGA
          CGGGAGTACAGTCCGGTACCGATTTGTGGAATGAGCCAGTTGTACCACGACATGTTGGGA
          GCCCAACTGCAAGAATTTCCGGGGTGTACGAAGAAAAGATTATCCCTAAATACGTTGCCA
          GCACAGCCTACATGCTTTCTGAGGCGCACGGAAGAAAGAACCCCTCCAAGTATGTTGCCA
          AAGGGGTAAAGACGAACGTTCCCCTTCACGAAAGTACGAAATACTTGTAGTTCGTTGGCC
          AAGGGGTAAAATCGAACGTTCCATCACACGAACGCACGAAATACTTATAGTTTGTTGGCC

          TAACACTATAAAGGGTGGAGTAGAAGGTAGCCTTGCATCTTATAAGCCCCTCCTGTTCCT
          GGCCACCAATAAGAATAGTAAATGAGGTGGTTATAGTTCCAGTACTACTCGCTAATTTTT
          GGAGACTATACGCTAAGAAGCTGGATATGATCCTAAACTTTACTAAAGGGTCCACGCGTC
          GAAGACCATACGCGATCAAGATAGATATGATCCTAGACTTTATCTAAGGGTCCACATGCT
          TACATCCATACGCCTACGCGGAGAATAAACAGGAGGGCGTGAATCGCGCTCACAAATGAG
          GACAACCGTAAGCCTTCATGGAAGACAGAACGGAGGGTGCGTAGTAACCTCCCAAATGAC
          GATTTAAGCACTTTTGTTAACTAGCACTGCCACCGGCTCAGAGAGTAACCATCATACTCC
          GACCTAACCACTTTTGTTAACTAGCACTACCATCGAATCAGAGACTAACTATCGTACTCT

          CTACCGGCGGTTTGGGCCCCGCGGCGGTTTGCGACTGACTTTATACTTTTAGATTTTGGT
          CTGTTGAGGTTCTGGACCGCGAGGAAACTAGCAAGCGTAATCATAATCTTCGGCCTCAGA
          CCACTGATTACAGGAAGTGCTGGGGTTTTCGTCACGTTACTGGATTGGAGCGGCTGAAGA
          CCATTTATGACGGGAAGGGCTAGGATTTCTGCCCCATTACTGGATGGGGCTGGCCGAAGA
          CAATGGAGGCCCGGCGGCGCTAAATACTTCGCTAATTTGTAGAACCTGCTTTCACACAGA
          TGATGGATACCACGCGGCGCAAAATACTTCGCCAATTAGACTGACATACTTTCATAGAGG
          CTAATAACACTTAAAGACACTGGGACCTTTTACCCCTAATTGGTGGGTGTTATCCAAGTG
          TTAATAATACTTAGAGACACCAAGATCTTTTACCCCTAATTGGTGGGTGTTATCCTAGTG

          CCGATCGATAAGCGCTCGGGGTACTGGCTGTACAACACAGTTGGCAAGGCAAGCACACAA
          CTGGCTGCTATTCGTAAGAGGTATTGGCTGCCTCGCGCAATAACCACTGCAAACATGCGA
          GCCACCGGTCGCTATTCAAGACATGGACTGACGAAGACAGTGTTGATCGCCACAATGCAT
          GCCCCCGGCGGCTATTCAAGATATAGAATGATGGAGACAGTGACAACCGTCACAATGCAT
          GTTCGTAAAGAACCGAGGCAGGGTTACAGGACAGACTTCTCGTGCCCCATAGTATCGCGT
          GTTCACATAAAGCCGAGGCGGGGTCATAGGTTAGGTCCCCTGTGCGCTCTAGTCTCGATT
          ACGACCGAGTAACTGGTGCTAACTCAAACAGTTGGTGCGATTCGGGATCTTGCTGCATGG
          ACAATCGAGTAACTGGTGCTAACTCAAGCACTTGGTGCGATTCGGGACTTTGCTGCGAGG

          AGCCAAATACACTATTATCGTTGGAAAGTTCTACAGTCCTCGCAATGCAGACCTGCACAT
          GATTTCATGTACCATCAGTGGGAAAACGACTATTATTGGGGGATACCGTCGACAACTTGG
          AGCCACACAAACCAGACGAGCGCCAGTGCGACTCAATGGGTGCTTACGAGGTCAATTAAT
          AGCTACACAATCCATATGAGCGTCAGTGCAAACCAGCGGGTGTTCACAAAGTCAATCACA
          GACAAACATTTCGGTCCAGGAGAGAATACTTTATGTCCTTTGATCTTTATTGTAGCAAGG
          GATAAGCATTTCGGTCCATGTCGGCGTGCTTGGTATCGCTTGATTTCCAATGCGGCGAAC
          AACGCAACTCGACTATTGGATGCGATTTATTTTCGCTATCTCTCTCCACGCACAGCTAAA
          AACACAACCCGACTAATGGATGTGATTCATGTTCGCTAACTTTCTCCACGCATAGCTAAA

          TTAACATACAGAACTATACTAGGACCGTTGGCTTTCTACTCGCGACGAACCCCCCCCCCT
          CTAGCGTATAAAAGCGCGCTAAGCCTGATGGTCTAACACTTGCGGCGTACCCCTCTTCAT
          CCCCCTAATGGTCCTAAATGCCGATTCCATGCCACATTCGACCTATGGCGTTGTACAAGC
          CCCCCTAATGACCTTGAATGCTGACTCCGTGCCACATTCGACCGACAGCGTTGCACAAGC
          CTAGTAATCAGCTCTGACAATAGTTCGTAAGTTATGTCGGTCAGTCCGGCCCCATGAAGA
          CCAATTTACAGTAACAATAAGAATTCGTAGGCCCAGTCCGCCAGCCTGAGTCCGCCGAAC
          CGGGCGTGCAATGGGCAATTCGATGTGCAAAGACTCTGTATCTACTGGCCACGTCTAAGC
          CGGGCGTGTAATGGGCAATTCGATCTGCGAAGACTCTACATCTGCTGGACCCATCTAAGC

          ACACCGCCATTAGGCAGTTGCGGTGATAGGTTTGTCGTGTTCGTAGACCCGGGCGTGGCA
          CCGTTGTTAGACGGAGGTTGTGGTGAGGAATTACATATGCTTGTAGATTTGGTTATCTCT
          GGGCTGCACGGCGACTGCCACAGTCGTAACTCCGGCTAGTCTGAGCACTCGTTAGTGCAT
          GGGCTTCACGGCGAGTGCCACGGTCGTAGATCCGGTTAGTCTGGGCACTCGCTAATCCAC
          GGCAATGTGTTTCGTCTGCATCACGGAAGCTCCTACGATGTTACAGAGGCGCCCGGTTTT
          GGTAAAGTGCGTCGCCCGTACCACGAAACTTAAGAAGAAGTTGCGAAGGAGCCTGGTTTT
          ACGTTTAAGTAAGGTATTTGCGACGGGTTACGTGACTTTGCACTAAATGCGATAGGTACC
          ACATTTACGTAAGGCATCTGTTACGAGTTATGAGACCTCGCACTAAGTGCAATATGTACC

          CCGTGATTAGACTCAAGAAACAGTCAACGACACCATTTGG
          GGTTAATTACATCCAGAGGACGATCCAAAACAATCCGCGA
          AATCAATCTGATTCAAAAGATAGGCAGTACTCTAACGTGG
          AATCAATTTGCTTCAAAAGATAAGCAGTACTCTAACGTGG
          TCGCAGTCAGCCGAGAGAGGCGAAAGCCTATATGCGCGGG
          TCCCAACAAGTCTTGAGAGGTGAATGCCTATTCCCGGGGA
          GTCCATTTGGACCCGAAAGACAGGGGGTCCTCTCAGTGAG
          GTCCTTTTGGACCTGAAAGACAAGGTGTCCTCCTAGTGAG

