 8 1000
t1        GTGGACGTAACCAATCCGTCACTGTTAAAACGCCACTGGGCTGATCTAGTCCGCCGCTGT
t2        CTGGACGTAGCTAATTAGTCTCCGTTGGAGCGCCACTGGGCTGATCTAACGCGCAGCTCC
t3        GCGAGAAAAGCCAATTGGTCCCTGTTGAAGTGGCACTGGCCTGATCTACTGCGTTGCTGC
t4        GCGGACATTGTCAACCTGTTCCCGTTGAAGCGTTATTTGCTCGACTAGCCACGTTGCTGC
t5        CCCAGTAGTATCAACACATATTTGCGGAGACTTCATCCCCGGGCTTTTATACGTCGTAGT
t6        GCCAATAGCATCAACACACATGTGTGGCGATTTCATTCCCGGGCTTTTAAACGTCGTAGT
t7        TCGGGTCCATTCGCCGTAAAACTTCAGCGGGGCGCTTCACTCGCGGAGAACTGTAGCAGA
t8        GTCATTAAATGTGCTTGAGGTAGGTATGAAACCCAGCCGTTTGGTTTGGATTGCAACAAA

          CTGCCTTAACTTATTGTCCGGGCCTCAAGGTACGCGCAGAGCTAAACGAAAGTCAAAAGT
          CTCCCTTAACTTACTGTCCGGGCCTCAAGGTACGCGCAGAGGTAAACGAAAGTCAAATGT
          CTCCCTTAGCTTCTTGTCTAGGCTTTAAGGTTCGCGCAGCGCTGAACGAGAGTCAAAAGT
          CCCTTATAGATGGTCAGTTGGGCCCCAAAGCCCGCGCAGTGTCGGACGAAAGTCAAAAGT
          AACACTAAGGCGGACTCTTGAGTGTCGGAGACTATTAAGTATCGAATGAATGGCTAGAAC
          AACACTAAGGCGGACTCTTAAGTGTCGGAGACTATTAAGTATCGGGGGACCGGCTAGAAC
          GCTACACCTTAAAGTAATTACGCCACGTCATAGGTCCGAGCGAGGGTCAGGACCCAGCAA
          ATTTCTGTTCACGGTACTTCCCACGCGTAACCAACGAAGAGTTGAGCAAAGCCAGGATGT

          TTCAGGGCGAATGCCGTAGCTAACTAATACTGCAGTGAAGGATCTCGTGAAGGCGCACAC
          TTCAGGGCGAATGTCGTAGCTAACTAATAGTACAGTGAAGGGTCTCGTGAAGACGCACTT
          TTCAGGGCGAATGTTTTAATTAACTAATAGCGCAAAGGAAAGTATGGTGTAGGCGTATAA
          TTCGGCGCCAATGTTATAGCGAAGTAATAGTGCAGAGAAGCGGATGATGTAGACGAATAA
          CCCTGTGTAAACGAAATAGCGGGCTGGTATTTCATAGGCGTGTTTGGCATCCGTGCATGT
          CCCTGTGCAAACGAAATGGCGTACCGGCATTTCATAAGCGTGTTTGGTATCCGTGCGTGT
          TTCTGCGGTACCAAGACCGCCAAGTATTCATGCCAGGAGTAGCCCGTTCCCAAGAGCATG
          CCTCAATGTGGTGTAATCACTGACAATTGACTGAGAGGCACGCCCGACGAGGCAGCCAGT

          TGCAATAACACCATCATCCTCGAATCGCTATCGCAGTGTACACCCGACTACGACCATAGA
          CGCAATAACACCATCATCCTCGCTTCGTTATTGCAACGTACACCCGACTACGACCATGGA
          CGCAATAACACTACCATCCTTGCATCTTTACTGCAATGTACACCCGAACACGACCATAAG
          TGCAATACCCCCAACATCTTTGCATCGTTATTGTAACCAACACACGACCTCGACCATAGG
          CGTTTTACCACATCCGCTTCTGCATTGCTATAGGAGCATACTCATGCTAACCACTGCTTA
          CGTCTTACCACAACCGCTCCTGCATTACTATAGGAGCATATACATGCTAACCACTGCTTA
          TACATTGTCCAGTTGTTTGACACCCCATCTCCCACATCCAACCCCAACATTGCTCGCTGG
          TTTGGTAGATCATACGATATTTTATCTTTATCAATGCCCGAGTACGACAGTGCCTAGACG

          TCCGATGAACGACGGTGTGTGTTCGGGAGTGGCTTCTACTTCAGGCTGCCTACGTCGAGG
          TCCGATGAACGACGGTGTGTGTTCGGGAGTGGCTTCTACTTCAGACTGCCTACGACGGGG
          TCCGATGAACGACGGTGTGAGTACGGGAGTGGCTTCTACATCAGGCAGCTAACCTTTAGG
          CTCGATGACTAATGGTATATATACGCGACTTTTGTCTATGTCAGGCCGCCAACGTCTAGG
          TCCTGTGAACAAAGGCGACACCAGGGGGGTGGCTCCTTTCTCGGGAAACAAATCAGTAGG
          TCCTGTGAACAAAGGCGACACCAGGGGGGTAACTACTTTCTCGGGAAACAAATGGGTAGG
          TGTAGCTGCGAGCTGGACGACCAGAGTGGCAAACTTTCACGCTGTGAGTTCATGTTTGGA
          TAGGGGCACTGATAGAGTGGAGAAAACTGTGGAGATGATCTTTGATTCTAAGGGCCCAGC

          AAATAATCCACCCACGCTCCGGTTAGCCGGGGGGACGCGCACTTAGCGTAACGTGAAGCC
          AATTAGTCCATCCGCGATACGGCTAGCCGGGGAGACGCGGACTTGGCATAACGTGAAGCC
          AATTTAGCAATCTGCGATCCGGTTGTCCGGGGAGACGGGGGCTTATTAGAAACTGGCGCG
          AATTTATCTATATATGATACAGATAACTGGGGAGACGAAGGCTCAGCGGAGTGTGAGGCA
          GGTCTTACCGGTCACACCGAGGCCACTCGAGAAGTCGGGGACTAACCCGTGCATGATAGT
          GGTCTTTCCGGTAACACCGAGGCCACCCGAGAAGACAGGGACTAACCGATGCATGATACT
          TATGATTCAATATCCGCTGTGACTGAATGTCTGAGACTCAGTTATTCCGGGAGCAAAGAG
          GGCCCTTAGTCATCAGCCTCCACCGATCATTCTAGCCTTGGCGGTTCAAGTAGTAACGCT

          GGCAGTGACCCAGAGACGCGTCTCAAGAATGGAACTCTAAAATTCCCTCTGCTGTCAACT
          GGCAGTGACCCAGAGACGCGTCTCAGGAATGGAACTTCAAAAATCCCTCTGCTATCAATG
          GACAGCGACCCAGAGATGCGTCTCGAGAGTGAAACTCCAAAACTTTCCCTGTTGTCTGTG
          AGCAGTAACCCCGAGACGCGTCACAGGAGCGGAACCCTAAAACCTTCTCAGCTATCAATG
          GGTAATAACTCGGAGCGGCATTATAGTGGTGTGACGCGAAATTATCCCGCGTTACCAAGT
          GGTAGTAACTCGGAACGGCACTATAGTGGTGTGACGCGGAATTTTCCCGTGTTACCAAGT
          GATGGTCAGCTCGGGGTGACCCGAGACCACTGAATTACCGTATTCTCGGTAGAGCTACTC
          CGTGGCACCCTAAGCACAAGCCTTTAACAACCGGACAATGCGCATTAACCAGAAAGATTA

          GTACTATTAGTACATCCTTTTACGGGCCTTGAAGCTCATTGAAGTACTTTCGCTATTGAA
          ATACTATTAGTATATCCTTTCACGGGTCTTGAAACTCATTGAAGCACTTTCGCCATTTAA
          GTACTGTTGGTATATTCTTACATGGGCCTCGAAGCTCATAGAGGCAATTTCGCCCTTTAA
          GCACTGTCGGTATACTCTCTAACGGCCCTTGCAGCTAACCGAAGCACATTCGCTACTTAA
          GAGACACTTACTCGCTCATCACCGAACCCTGAAACTCGGACCAGATCTTCTACACTGTGA
          GAGACACTCACTTGCTCATCACCGAACCCCGAGACTTGGACTAGATCTTTTACCCCGTGA
          TTGGAGCACTTTTGTTGCCACTCGCTTAACGTGCTGTACTGCCGTACATATCCTGCCTTC
          CCGACGTTGTGTCACTCTTATCCGGGATATTAAATATTCTGAGGCATACTCGTCGTCCCA

          TTTAATATGTAGATTTCGATTGATTTCACACCTTATATGTCAATACATTTTAGCGAGGTG
          TTTAATATGTAGATTTCGATTGATTTTACGCCTCATATGCCAATACATTTTAGCGAGGTG
          TTTAGTTTGTAGATTTCGATTGATTCTAAATCTTAAATGCCAATACATTTTAGCGAGAGG
          TTCAACTTGTAGATTTTGATTGATTTCAAATCGTATATGACGATACAGTTTAGCGTGGGG
          CTATATCACAGAATAACCACCGTTTATAACCCCGGCTTGCCCCCATGGTTAGAATCGACG
          CTATATCACAGAATAACAACCGTTCATAACCACGGCTTGCCACCACAGTTAAAATCGACG
          TATCCTCCTCAGGGCGCAGCCCAATCCATGTAACCATCCGTATAACGTTTACGCTTGCTA
          TACCGTATCAAGCAGCCGGGACAACAGATGTTTCAGAATGCACGATCATCAATATCAAAG

          TCCTGCGTCTGTCTCATGCATAGCTTTAAGTGGTACCCCTTCTCGTTTAATAGCCGATCG
          TCCTGTGTCTGTCTCATACCTAGCTTAAAGTGGTACTCCATTTCCTTTAATACTAGATCG
          TCCTCTTCCTGTCATATACATGGCTTTGAGTGGTACTTCTTTTGCTTTGACATTCGACCG
          TTCTCTTCACGCTTCATGCACAGCTTTAAGAAGCATCACTTTCCATTTGATACTCGACGA
          TCCCTGCATTACTACGTACGCTCTACCGAGATAATCCACCACTTCCTTCATGTACGATTG
          TCCCTGCATTGCTACGTATGCTCTACCGAGATAAACCACCACTTCCTTTATGTCCGACTG
          TGACCGTGTAGCGATATACACCCCGTTTCAGTGGGCCCCCTTTTCCTCCCCACTTCATGA
          CATCCGGGCAACGACATTTACATAATTGTGGGGGCGTTACCTTTCTATGACACGCCTATT

          TGGGGGGGGCTATGCTCGGGTCTTGCCATTCCCTCGATATATTAGAATGCGCGCCCCGAG
          TGGGGGGAGCCTTGCTCGGATCTTGCCATTCCCTCGATATACCAGAATGCGAGCCCCGAG
          TGAGGGGAGCTTTACTCGGGTCTTTCCATTCTGTCGATATACTAGAATTCGAGCCCCAAG
          TGGGGAGAGCTCTGTTCGGGGCCCTTTATTCACTGGTCATACTCGCATTCGAACCCTAAG
          CGCGTACAAGGTAACTCATGACTCTTCCCGGTCAGGATTCTCCTAGATTCGGCTCTCATA
          CGCGTACAAGATAATTAATGGCTCCTCCCGATCAGGATTCTCCCAGATTCGGCTCTCATA
          GCGAAGAGGGATTGGGCAGGGTTGTTTAACGCTCATGTCGGATCGTGTCATGCCATCCGG
          ACTGCGTAACGAAAGGTAAGAGGAAATAGCCTCGTGATGAGGACACGGCGCCATCTCCAG

          CAGACACTCAGCAAGCGGTGGTCCGCATGAGAAGCCAGCGAGAGATGCGATTAGAAGTAC
          TAGACGCTCCGCAAGCGCTGGTCCGCATGAGAAGCCAGTGAGAGATGCGAGTAGAAGTAC
          CAGAAGCTCCGTGAGCGACGGTGTGCGTGAGAGGCCAGTTAGAGATGCGAGTTTGAATAC
          TGGAAGCTCGGCAAGCACTAGTCCGCATGAGAAGCCAGTTAGAATTGCGAACACGGTTGT
          TAGATGTTCCCAAACTGAGCAGCCCCGTGAGCCAGCAGTTAATACCCCGTACGTCTGAGT
          TAGATGCGCCCATACTGACCAGCCCCGTGAGCCAGGAGTTAATACCCTGTACGTCTGAGC
          TGCGCGTTGGGGAGCGGATCGCATACGATGTAATGCATTCACACCATCGGACTTCGATAT
          AAGTTACCGCGGGACCTGTAGACCGGGATAATACGCCCAACTACGATTGTCGCTGACCGT

          GTTGTCCCGAGAATTCACACGAATGCGATAGTAGATCCTTGAATACTTCGTAGCAGGCCG
          GTTGGCCAGAGAATAAACACGAAAGCGATAGTAGATCCTTGGATACTTCGCAGCAGGCCA
          GTTGTCCCGCGAACTAACACGTACGCAGTGGTAGGTTCTCAAATACTTCGTAGCAGGCGG
          GTCGCTCCCAGAGTGAAAGTGCACGTGACGGAAGATCCTTCAATATCCCGCAGCAGATCG
          ATGATTGTGAGGACTCGACTGCTCGTAGTCGAAAGACATTAATTATGAGGTTCACGACCA
          ATAACTGTAAGGACCCGACTGCTCGTCATCGAAGGACAATAATTACGAGGCTCACGACCA
          AGTGTGCTCAGGTTTGCAGGCCTTACGTATGTACGAATGTGTGAGATTGTATCAGACACC
          AGAGTACTGAATTCAATAATCCTCCGACACTCCACCTAGCGCCAGGGTCTGCAAGACAAA

          CGCTCTCCACCGCATTACTTACCCATCGGTAAAGGTGTGAACAAACCCACTTATAGTTTT
          CGCTCTACACCGCATTGCTCGCCCATCGGTAAAGGAGTGAACAACCCCACTTTTAATTTT
          AGTTCTTCAACGCATTACTCGCTCATCGGCAAAGGCGTGAACAACCCCAATTTTTGTCTT
          GGTTCTCCATCGCATTTTCCGCTAATTTGTAAAGGAGTGACCAACCCCAATTCCAGTTTC
          TACCCTTCAACTCGGCGCTCCCCTGTTACTCTTGCAATGTTCAGATTTGATCACAGTATT
          TACCCTACAAATCGGTACCCCCCTGTTACTATTGCAATGTTAAGATTTGATCACAGTATG
          TGTCTACGCGTCCTCCCGCTGGCAATTTACGAGCACATGGGCAGCGTTGGTTGTGTCGAG
          CAGCCTGAGATGCCTCCCTCACCCACGGAAGATGGGCTCCACGGTGTATATGAATGCAAC

          TCAACCCATATCATTCTAGCTTGGGTCAGCTCTTTGGGGTTATACTGACGAGTATCGGCC
          TCTACTCATATAGGCCTAGCCTGGGTCAGCTCTTTGGGGTTATATAGACGTATATCGGCC
          TCTACTTATAGTGACCGCACCTGGGTTAGCCCTCTGGGATTATACTGACGAATCTAGACG
          TCTACTCTTAGCGTTCCCATTTGGGTTAGCCTATTAGGATGATACTAACGACTTTCGCCC
          AATGACCTCGGCTCTTTCACCGGGATCAGACCTTAGGGTGGACCTCGGCGCCTACAGAGC
          AATGATCTCGGCTCTTTCACCGGGATCAGACTCTAGGGTGGACACGGACGCCTACAGAGC
          CAAAGCCTCATCGTTCGAGTTGGGCACACCCCCCAGGATTGTCTTGACTGCACTGCGATA
          CAGAATATTAAGGGTCTCCTAATTAGCAAATGCCGGGACCGTCTTCGGAAGTCGTCGTCT

          ATCGTTGGTAGGGGCAATTAGTCTGTCTGCTGTTTAATGATACCTTACCAAAGTCGAAGT
          ATTGCTGTTAGGGGCAATTAGTCTGTCTTCTGTTTAATGACACCTTATCAAAGTTGAAGA
          ATTGTCGGTAGGGATGATTAGTTTGTCTTCTGGTCAATGATCCTTCATCAAAGTCGAAGT
          ATTGTTGGTGGGGCCGATTAGTCTGTCTTCTGGTCAACGACATTTCATCTAATTGAAAGT
          ACGTTTAACGGGGACAGCACGTTCGTCGCCAGGTCTCCGTCTTTTCGTTGACGACGGATT
          ACATTTAACGGGGACAGGACGTTCGTCCTTAGGTCTTCGTCTTTTCGTTGACGTCGGATT
          AGTCACGATGTGGAAGGGCGGTTAAAGATCAACTGCGATGGCATCTTTAAAAGCTTCGTC
          GATCCCGACAATAGGGCAACTTTAGGTACAAGGTACCTAGTCACTATCTAAAGACGCCGC

          AATGCATGGTCCAGAAGTGTGTATCTCTTTGAGAGCAGAG
          AATGCATGGCCCAGAAGTGTGTATCTCTTTGAGAGCAGAG
          AATGAATGGCCTAGGAGCATTTGTCTCCTCAGGTACAAAG
          ACTGTATGGCCCAGAAGCGGCAGACTCCTAAACTGCTGAG
          GTTGCTAGCCCCATTGATTCTAGCTACTGTATATGCGGAG
          GTCGCTCGGCCCATTGATTCTAGCTAATGAAAATGCGGAG
          GTTTCTGTCTTCTAGGCTGGCCGGTCTATAGATCGCAGAG
          GTTGCCGTGTCCACTCTCTCTATCCTTCTCCACGATGGAC

