 8 1000
t1        CTTGGGCGTTACAATCATGTAGCGAATGTTATAGGCTAGCTGCGCTCTACAGTTCGCGAG
t2        CTCGAGTGTCATCATTTCATAGCGCGCCCAACACGCAAACCGCGCTCTGAGGTAAGTGCG
t3        TATTAAGCCTTCGTTAAGCCCACGCTGGTGGCATGGGAGCGTCACGTGGCCGCACGAGCA
t4        TTTAACCGCCCCTGTAAGAATGTGCTAGTGGCATGCGAGCGCCTTGTGGACATTCGAATA
t5        CAAGCTCGGTATAGCTAGTCTACAGCTTTGTTGTCCCAGCAATGTGTTGTGCGATGCGTC
t6        CAAGCTCGGTACAGCTAGTCTACAGCTTTGTTGTCCCAGCAATGTGTTGTGCGATGCGTC
t7        CAGTCTTAGTACAGTCAGCTTCCGTACTTACTACGGGAGATATCCACCGAGTTCTGTGCC
t8        TAACCCAGGCACGGTCCGCTCCCGGCCCCACTACAGGAGTTGTGCGTCGTCGCCAGTGTT

          CGTTTACAGCGCGACCGCGGCGCCGAGGTATTTTTGGGCTGTATAAGTAGTGGCCACCCC
          CGCTTATGAAATAACCGCGGTTTTGATGTTATCTTGGTCCGCATGAAAGAACACATCCCC
          CGCTTTCGGGACGCACGAATATCCCATGTATGAGAAACCAGTTTATGAGGCGGTACTATC
          TACTTTTAACGTAGTAATAAAACCTGTACTTCAGAAGCTTGATCATGAGGTAGCGTTGCC
          TTTTTCCGACATGGGTGCGCTACCAATGCAACAGAGGTCAACCAGTTTGCTAACTCTGAC
          TCCTTCCGACATGGGTGCGCTATCAATGCAACAGAGGTCAACCAGTTTGCTAACTCCGAC
          CGCCCCCGGAGCTATTGGTTCGCTATCGCGCCTGGGGACGACACGTGTTACAGTTCTAAA
          CGTGCTCGAAACTGCCGGTCCGATACCGGACCTTGGGACTATCCGTATAGCAACTTAGAC

          TGCAAAGAGATCGCTAGCAACGCATTTAAAAACACTTAGGAGAGGAACGCGTGTGTCTCA
          CGTGCAGCCTGTGACTATAATGCAATCTGTAAAGCTTTTAAGGGAATCGACCTTGATCCA
          CCTGCCCTGGCTTTATCCAATGTAGCGAAGCATTTTACAACGCAGCTTACCCAGGACACC
          TCTGTTCTGGCTCTGTGCAAGGTTACCAAGTACTTTAAGGGGTAGCGTTACTACGAAGTC
          AATGTGGCCACTAAAAGGACAGATATCGACTATGTTAAGTAAAGCCTCAAACATTAACTT
          AATGTGGCCACCAAAAGAACAGATAGCCACTATGTTAAGTAAAGCCTCAAACATTAACTC
          ATTATGAATCCTGCGGTGGCTGACATCTTCATTCTTTATACATGGCTTGCAACAGGAATT
          GCTATGGACAATGCGATGCAGAGCATCTACGACCATCATCCAAGCTTAGGGCCTGTATCT

          GTCAACGGGAATTAGGCGCGGCGACAGAGCTCACGCGGGTGTGTAGACGTGAAGGACTGT
          CTCCCGGAGTACCGGAAGGGGCGTTAGTCTATATGCGGTCGTGCCGGCGAGAATGATATA
          TACAATTCGCCCGGGTTAGTGCGCCAGCATCATCAGAGCTCCATCTAGGAATGCCACCCC
          GCCAACTTGCGCGGGTTCAGGCGCCACGATCACTGGATGCTCGTTAAGGGACGACACCCT
          CCTAAACGATAAAGCTGCACGCTTCGGGCTTCTCCCTCAGTTTTTTGGCAGGTAGATCGC
          CCTAAACGATAAAGCTGCACGCTTCGGGCTTCTCCCTCAGTTTTTTGGCAGGTAGATCGC
          GTTCGACGGAAGGAACAGTAATCCGGGAGTATTTATTCGCCCGGCAGCTGAAAGGCGCAA
          GCACGACGGAATGAACCGAGACACAAAAGTGCCCGCCCGCCGGTCAGCTAGGACGCCGGA

          GAATTTTGAAATTACTTGCGGAGGACTCTATTTGATCGGGTAAGTACGCGGATCAACTCA
          GTGTCCTGGATTCTTTTACAAAGGACCGAGCTAGCCCGGGCCCGGTCGCGAATGGAGTCC
          GAGTTGATGTGTATACTGACGGGTGCCGACCCGGTATAGACTATCGTGTCAACCGATTGC
          GTCCCACGGCGGCTCCCGACGGGTGCTGACCCTGTTTGGATTCCTATGTTAACCGATTGC
          CAGTATGAACCTATTGCGCCTTCGCCCTACCCGGTTTGGATCCTGTTTCTCACTGCTTAT
          CAGTATGAACCTATTGCGCCTTCGCTCTACCCAGTTTGGATGCTGTTTCCCACTGCTTAT
          AAGTATAAACGTCTAACCGTAACGTCGTCCCCGATCGATATTGGCGCATGCAGTGGTCGT
          CGGACGAAGTGTCGAAGGCCCAAGGCGAGCCTAACCTAGACTGGCGTATAAGGAGGCCCC

          CCTGTTACGCCAGGACATTTTTCCGGTGCGGGTACCTTGCTATTACTAGTCAGCCCAATC
          ATCGTTCAGCCTGTACAGCTCTCCGCCAGGAGAAAGGGGTCATCATCGGTCGGTGCGCTG
          CGAACTGCTTGTGGAATCCCCCCACATGTAACAACAATACTCGTTACAGAGGCTTCGCTC
          CGTATTGCTCAGGGGGATTCCACACCAGGAGTAAGAGTCTTTATCATAGAGTCTCCGCCC
          AAATTCCAATAAATACCGCCTCCGTGTCAGGTCACCTACACCGTTTCGGTATCTACGGCC
          AAATTCCAATAAATACCGCCTCCGTGTTAGGTCACCTATACCGTTTCGGTATCTACGGCC
          ATCGCCCTGCGGAGACGAATTCCACTTAGTTTGGCATACATGACTACAGGAGCTATCGCT
          ATTGACCCGCGGAGATTGACCCTGTGTAAATTGGTATACACGCCAACGGGACTTGTAGCC

          ATAACTAGGCCTACGTCCGTGCTCGGGTCACGATTTGCCAAGGAAGTTCGCGCGGGTACC
          GTGACTCGGCCCTCCCCCGCGATCGAGCCTGCGGATGAAGAGCAACTCCGGGCCGTCACC
          CGGTTGCGATTTTGCCCGGGGTCCTGATGCTCTTCATGCATAATCGATCGTATTAGTACC
          TGGTTGCGTCTCTGTCTGACGCCTCGGCTCCCATCACCCAAAGTTGATCGTATTGGAATC
          CACAACGGGTACTCTAGCTGGCACGTGTACTGACAAAGACAAAATGTACCTGCGAAGTCT
          CTCAACGGGTACTCTAGCTGGCACGTGTACTGACAAAGACACAGTGTACCTGCGGAGTCT
          CGTCTACGGTTACCTTCTAGTCCCATGCATAGCCCCCGAATAAATATCATTGGTGGTACC
          TGTCTAAGTTCTCACATTCGTTATCCGGACCAGCATCGTAAGAATATTCTTTACCGCACC

          GCTAATGTCGATTCCTATCCTGGTTTTAGAAGCTCGAGCCTTCCCCATCCCCTTAGGCAG
          GGAAAACAACGAATAGATATAGGCTATAGACTGTAGAGTCTGAATTGTTGGTTAAAACAG
          ATCCGGATACTAGCAAATCCAGACGTGTGGCTCGTTCCCCCCCGTAAGTAACCGATGTGG
          ATTCGACTATTAGCATGTTCAGCCGCGTGCAACGCCTGTCCCTGTAACCAACCAATATAG
          GCTCTTTTCTTTATCGGTGTGACGTTTCCACTCACAACACCGGATAATCGGTCCTAATGA
          GTTCTTTTCTTAAACGGTGTGACGTTTCCACTCGCAACACCGGATAATCGGTCCTAATGA
          GGGCACTTTAGAGCAGAACTCGATTTCACAGTTGCGCTTTAAAGTCGCAAGGCGGAATTT
          GTGTGATCTGGGTGGTCGCCCGACTACAGCTGAGCACTACACAGTCCCATGTCCCAAAGC

          CATCTGTGATCAATTAAGTTGGCCACATTCAGAAATCCCGTGTGTACCGTGACACTTACA
          AGCCCTACATGCCATTCGTTAATTATCGTCAAGCGTTATGTAATCCACCAATAGTCTACG
          CAAAACCTGTGCCTAAAGAGTTATTGGGGCCTCTACATCCCTCAGTTCTTCTGTCGCGAA
          CAGCATGAGTACATACAGCGACATTGGGGCTATTATTCTTCTTGGTTCTTTTGCAGCGCA
          CCGATTCAGATGAGCACGGTTCCTGTTGGTCAGTATTGGGTTTTACAAGTACGCCAAGTT
          CCGATTCAGATGAGCACGGTTCCTACTGGTCAGTATTAGGTTGTACATGTACGCCAAGTT
          CTTGTGCCGAGAGCCAGGCGACCCGCTGGACAACATGAATATTCTCGTTCCCACCGTAAA
          TCTACGTCGGGACCCGAGTGCACTGGTGGACAGTATAAATAGCGTCATTTCTGACGTGTG

          CCAGATGCACACTTAAAGTATGACTACACCTGGGACTAGCTAGCTATGCCGGATCAATCT
          CCGAGACAAAATAGCGGATCTGTCCCGTCTTGGGACAAACCTTTGACACTTAAACGACTC
          CCGGGTGAGCTAGCATAGTTCGGGAGCACTAGGCGAGTATATCGAAAGGTACGTAAAGCC
          TTTGGCGAACTCGCACAGTCCGCTCTCACTTAGGTAGTATATTGAACGATACGTAAAGCT
          CCCTGCGCGCTCTTCACGCTTGCATGCGTTAGAAAGGCTGATGTGGCGGATATTGACTCC
          CCCTGCGCGCTCTTCACGCTTGCATGCGTTAGAAAGGCTGACGTGGCGGATATCGACTCC
          TCTTGAGCGCTCAATGAATTTACTAGACCATTTGAGGTTCACATGCAGGTGAGGAAGTGT
          CTTCGCGCGCCAGTTGCATCTGCTAGCTCCCTTGAGGATCCTATGTCGACAAGGAGGTCC

          TTGTGTGCGCCACAACGTCTGTTTGCGTCACCTGAAAAACGGTGCTTCCTGCTTTGGCCG
          TTAGACGCGCTCGGACGTCTGCCATCCTTGCGTACAGATCAATGGCGTCCACATCGATAA
          ACGATTGCGAAAACGCATCAACGCGACAGGCGCAGCAACCTACACCCCTCATATAAAATA
          ACGCTCGCGCACGCGCACTTACACGACACGCACTATAACTTGTTCCTCGAACATAGAATG
          CAGGTTTGATACCGACCTCATTGACTAGAGAGAGAGCAACAATAAGGTCTGTATGACGCG
          CAGGTTTGCTACCGACCTCGTTGCCTAGAGAGAGAGCATCACTAAGGTCTGTATGAGGTG
          CGCACCCTACATAGAAATCGGTGCGTTGTGCGAGGAGATTAACACGGCACTAAGATACTT
          TGGATCCACCACAGGCTCTCATGTGCCGCGAGTCGAAGCAACCATGTCCGGGATGACGTA

          CGCACAATTTCCGCCCTCTGCACGAGGTTTATCGAGACAAGATTACTGCATTTCATGGAG
          TTAGCGATTTGCGTGCTTTGCAACAGCTTTTGTGAATCCAAACTCTCGCTGAATCGGGTA
          AAGGGGACAAGACACTGGCCCTGAAACCCCTCTTTTTCGGAATCGCTGGGGAGCCGGGGA
          AAGGGGACATCATGCCGGATCTGAGGGCCCGTCTCTACCGAATCGCTGAGAAAACGGAAA
          AGTGCCATTTCGTTCTGTAAGATCGCACTCCGAGTGCGAACGATGGTCCAAGATTGGAGC
          AGTGCCATTTCGTTCCGTAAGATCGCACTCCGAGTGCGAACGATGGTCCAAGATTGGAGC
          ATAGCTGCCTTAATGCTGGTGTTCTCCCCACGCTCTCATCGAAAAGCATTTCTTTAGTTC
          GATTTGGTCACGCTCCATGTGCTAATCCTGCGCTATCACCGTATATTATATAGTTAGGGT

          GCAGCTTATCTAATGAGCATGACAGACAGGCTTCCATAGCTTAGATGTTCTAAGTCACGT
          GTAATATAATTGATCCGGTTGGCTACCGTATTAAGATGGCCTCAGCAGTCTAGGAAATAT
          CCCAGGTACTTGCTGCCTTAACCCATTAAACTTATTCAGCCTAGTCACCGGCCGCCACTT
          CCTACATACCTGTTGTCCTAATACCATAACCCTACTCGGGGCAGCTAACGGAGGCTATCT
          CCGGATTATCCACTACACATGAGAACGATGTGCAAGCATCATAGCTGTCACAGCTCGCGC
          CCGGATTATCCACTCCAAATGAGAACGATTTGCAAGCATCATAGCTGTCACAGCTCGCGC
          AAGTCCAGTAACGCAATTGGGGTATTTTTGCTAAAATACTGCTACCGTTCGGCGTCTCAT
          ACAAACGACAACGCGACCGCTAAATCAGTGCTAAGAGACTAAATTGGGTATGGGCCTCGC

          ACGCACCCCGACGAATTTCGAGCCATTCTTGTGTCAGCGGGTAGCTGTTGCCTTTCTGTG
          GGACATTCTGTTGTTACCTCCACTAATCGCGCGTTAGCGAATTCACGCCGCTTTCTAGTA
          CGCTGTCCTGGGCTGTAACCGACTCTTTTAGTGTCTGGAACAGTCTGGAGTCAATCAGTG
          CGTCGACATGAGGTGCAATCGACCCTCCTAGCGTTCGGAAGGGATCGTAACCACACAACT
          AACTGCGGTGCTGCGCCTACGAGCATGCCTGCGTTAGGTGGCAACGACGGTGACGATACG
          AACTGCGGTGCTGCGCCTACGAGCATGCCTGCGTTAGGTGGCAACGACGGTGATAATAGA
          AACGGAGATATCGCTCTCATGCACATTGTTGAGCCTTATGTGGACGACGGTGATCGGGGG
          AACAGCGATATCGATCCTTCATTAACTGGTGCGATTTATGTTGCTGACCGTAATTAGATG

          ATCCTATATATATATCCCAAATCCCCACTTATCAACGCGGACATCTCGTAGCTGCCAGAC
          ACCGCATACATCCACACAACATACTTAACCCTTACTGCGCGCCACCGACACTTAGCAAGT
          GCATCACGCGGTGCGCCCGCAGGTGCAAGGAACCCTGTGCGTCCTCTACACCCTGATGCG
          CTATCACGCCGTGTGCTAGCAGGCGCAATGAACCCAGTACGAGCCTAACGCCCTGATGGA
          TCATAATAGTAGACCACCACAAGCCTCCTTAGATCGATGCATCGCTGCAGTCCTCTCAAT
          TCATAGTAGTAGCTCACCATACGCCTCCTTAGATCGATGAATCGCTGCAGTCCTCTCAAT
          TACAGCATATTCCCTGTAACTTGCAAACGGCACTCCGCATGCAAACTCCGACAGATCGAG
          TCCTAGATTTTCTGTCTAATCTACATATGACACTTTGCGCACGGATTCCGCCCAGTTGAG

          TCTAATCGCGGACTGCGCGCCAATTGGCCTGGTTGTAGGTACGAACTTTTATGCGACGTA
          TGAGACTGTCACGCTAAACGTAACTTGAACGACAGTAGGCACGTGTCTCAATGCAATATA
          AACGAAGGGCGATCTTAATCGGAGTAGATGGCTGGACTTATAATGCACCAGAGTGAGAAA
          TACTAAGGGCGCTTTTTCCATGTGTAGCCGGCCAGCGCCGTAATGCACCAAGGTGTGAGA
          TTTAATATCCGGACACGGCGTAATAGGTAGCACGCGGTTCACTGAGATCTAAGGGGTCTG
          TTTAATATCCGGACACGGCGTAACGGGTAGTACGCGGTTCACTGAGATCTAAGGGGTTTG
          GATTATGACCAGATATGTCATTATGAAATAACCCGTGAGTAAATCGACCTCGTTGCAGCC
          ACTCCGGACCGTATCTGTCACATGGGATTAAATGGAGATCTTCCTAACTTAGATGCAGTA

          TATGCCCGTTCTCCAAGATGCCGTATTCCACGGGAAAAAT
          GGGTCTCACAGACCAGGATCCAGCATTCAAAGGGGATTAT
          GCCGACGGCACTTCACGAATGTGTGATGCATAGCCAGCGG
          ACCGGCAGCACTCCACGTATGCGTAATGTATAGAGAGTCG
          ACAGTGTATTTGTGTGGGGAGTGCAGCAGGCACTGGGAGT
          ACAGCGTATTTGTGTGGGGAGTGCGGCAGGCACTGGGAGA
          ACGAATCGTCCGAACCCGGAGTGATCTCTTAGCGTAGATG
          GTTAATCACTTCTAAATGCAGCGCTCTTAGCACAAAGACG

