 8 1000
t1        ATCTCGACAACTCAGGAAAGCTTTACGACTGCATAGGTATCGAAATAAGTGAGCTCACTT
t2        ATCTCGACAACTCAGGAAAGCTTTACGACTGCATAGGTATCGAAATAAGTGGGCTCACTT
t3        ATTTCAATGATTTATGAGCGCATCACGTTTGCGTGGATGCAACAATCGGCGGGTTCCTAT
t4        TCCCCGACGGTTATTGAGCGCCGCATTACATTTCCGGGATTGTAACGGGTGAAATTGTCT
t5        ACCTTGATGGTCCATGGGCGTCAAGTATACGCCCGGATATCAGTGCAAGTAGGCTCATCT
t6        TCTTCAGTGGTCTCATGATTCCAGTTCAATGAAAAGTCGTCAAACCCCACACATTCAGTA
t7        TATCTGACGATGATTTAACGTTTTTTAGTACGTAGAGTCTTGCCACTGATGATACTGTTT
t8        TCGCCAGTGATGGTTGAGCGCCGGTACGTTGCTAGTGCATAGGGGATACAGAGTTCGTTC

          CCCGCTGACGAGTTTATGGGTCTATTTTCCGCGTTGAAGATCCGCGCTTTGCTGTCCTAG
          CCCGTTGACGAGTTTATGGGTCTATTTTACGCGTTGAAGATCCGCGTATTGCTGTCCTAG
          TTAGCCGACTAGTTTTAGGGCTTTCCTATGCGGTCGATGACTCGCATATAGGCATTCTGG
          CTGGAACATATAGCGATACGTGCGACACTGTTATCTATAAACAGCGCCTCGCTTAACGGG
          CTGGGAAACGTGGTGACGGGCCAATCACTGACATCCACGATTTTAATACCGGAAATTGCG
          TGTGGATACCGGTTAAAGGGATACCTGGAAACGTTTCAAGTGACAAGGTGGGGGCTTGTA
          CCCATTAACCAGGTAGTATTTTTCATACTCTCTACCGCCTACAGAAGATCGTGAATGACA
          CCCGAGCCTGGGGAGATGCGAGCCGCTTTTCCGCTTACTAGATACCAATTACCGTCCATC

          CATAAACGATAAACTATCACTTATAGAACAAGCAACGTAATGGGTTTAACCTATATGTGA
          CATAAATGATAAACTATCACTTATAGAACAAGCAACGTAATGGGTTTAACCTATATGTGA
          CATAAAGAAGAAGGTCTCACTTATGGCAAATGAAGTCATTCGGGCATGACTCGCATCTTC
          TACACAATTATTGAGACTGCACGCAGAATGATATACCAAACAGGGCTAAGTCAACTACGA
          TATAGGACACAGACTTCCACATGCTAGCTTACCGCATAAATGGGCATAATTTATTTAGAG
          TCCAAATCCGATCGAGCAGAATGGAGATCAGCGAAAGAGGTGAAAGCTCTGTCGCAATAA
          TACGCGATCCTGGACCCCTACCGGGGCACGCGGGCCCGGATAACAAAAGGCTCCCCACGG
          CGCGTTCAGACGCAACACGCACAGGTACAAATGACGCGTGCGAGTACATCTTATTGGAGC

          AGCTCCGTACCCTACCCGGTGCCGAGGTGTTTAGCTAAGGGCCTACGAGCGTTATGCTGC
          AGCTCCGTACCCCACTCGGTGCCGAGGTGTTTGGCTAAAGGCCTACGAGCGTTACGCTGC
          ACTTCCGCAATTCACTTGGCATCGTAGGACTAAGCCAAGGGTGCACCGGACTTATGCCGC
          GCTTTCACGGCTCACTGAAGATCGTACCCTTCAAACAGAGATGGTTTCGTATTACATCTT
          ATCTCATAAATTCACTCGATGCCAGGCTACTTATTCACGGCCGTACTAGTTTTGCGGCAC
          GCCATAAGATATAGCCTGTTAACGAAGAACCGTTGCCGTCGAGTTATGAACTCACGGAGC
          GATCTCGAAATCAACCGGCGGCCACACTAGCTAGACCTACCCCGTTGTACCGAATGTTGC
          ACTCCCTGTACTGACCCCGCACCGAGCGTCGAAACTGCGCGTGTGCGTAAATTAACTCCT

          ATGATGAACTTTTGCTGTCCAAAGTTAGACGGGCGAGTGGTGTATGCATCGACTCCTCGC
          ATGATGAACTTTCGCTGTCCAAAGTTAGACGGGCGAGTGGTGTACGCATCGACTCCCCGC
          ACAACGAACTCTTACCGTATAATGTAAGACTAAAGACGAGTGTTGGCAAATATTCGCCAC
          TTAATAAACGTCTGATATACAATAAGGGAGCGGAGTGCGGGCTTGGCAGGTATTTCTTGC
          ATCATGAGTTTTCACGATTAAATAGCGGGCAAGTAGGGGGCCCAAGGATATCTTCACTAT
          GTTATAAGCTTTCATCCCATCCGGAAGACTACACAGGCTAAAGTTGGTAAAATCAGTTGC
          TTGCAAAGCACCCGCTACGGTCACACTGAGGTCGATGTGATGTAGCCCCAGATCAGCTGT
          AGCACGTGAGGCAACAGCATGCAAGCTCAGTACTAGGACTAAATTATGGAAACCTATGGA

          CGTAAGTTGTGTCGGCGAGCCCCGGTGGTGCCGGGGATAGAAGTCTGGAGTTCTACTTGC
          TGTAAGTTGTGTCGGTAAGACCCGGTGGTGCCGGGGATAGAAGTTTGGAGTTTTGCTTGC
          TACCAGCGCTGTGCTCAGCACACTGCCCTGTCGGAGACTGCCGTTCAGGGTCCTATCCGG
          CGTACGTAGCGTAAGTGTGGTCTAGCCCTGTCGAAAATGACGGTCAAGGGCCTCACTTAG
          CGTATGTGGTGAGGGTTGGTCTCATTATTGCCAGTATCATCAGGTCTCTGCTCCATCAGG
          GATGTGCCGTTCGAGTTGATTATTGAACAGCTAGAGGTTATGGTTGAGCCTTTTTTCTGG
          AGCCCGCAATAGGGACAGGTAACTATTTTGCGAATTATGATGCGTCAGAGTCACCTCTGG
          GGGACGAGTCTAAGGCAGGCCCGAGACCTGTAAGTATCCAAGGCTCAGATGTAGTTCAGG

          GTCCGATTATCAATGTCCTAATCCTCGTGCCAATACGGATCAGGGCACATGCCTTATCAG
          GTTCGATTATCAATGTCCTAATCCTCGTGCCAATACGGATCCGGGCACATGCTTTATCAG
          ATAGAATTCCTACTGTCTTAGTCATCGTGGTGGTACAGCCATAGGCACTCGATTTATCAG
          ATCCCATAATCAACATCCAAACCTTGCCTTTGGTGCGGGTCTAGGTATTCAACCAGACCG
          TCACTACGTCGGGTATCTTAGCTCGTGCGTTAGCATAACATAAGGTGTGCGTTTTAAGTG
          ATCGTCCTCACTAGGCATGCGTATTGGTTGTATCGCCAATAAAGTGCGATTCACCTGAGA
          TACTTATTTTCGACATGCAAGTCTGCGTCATAGTTCCAATCACACCATCAGCTCCCGGGC
          CTAATGTCCATCGCGTTAACAACCAAAGTGTCCCATTGACCAAGAGACGGAAAATCGAAG

          CTTCACTACGCGCAAGGCCAGCCCCACGCACCATACGGATAAGCCGAGAGAGGCAATTTG
          TTTCTCTGCGCGCAAGGCCAGCCCCGCGCACCGTACGGATAAGCCGTGAGAGGAAATTTG
          TTTCCCCATGCACTAGGCCTATGCCACGCACCGCACGCATAGGCCGAGGAAAGACAATTG
          TGGCTTCATGAATTGAGTCCACCCCTTGTGCCGACCGGGTGAGATGTAAGCGGAGCGCTG
          GCATCCGATAGGCAAACCTCGCATAGCACGCCGGCTGGACAAGTATCGAGCTGCATATCG
          CTAACAATTACGTGATGTCCATGCGGCATGTCGCATAGACGTCACCCAACACAGCTGTAA
          TCGGTTCCGAACCCAGTGTCGTCTTTCCAATGGCATGGGATGAGGGGCCAATAAATGGTG
          GTTAATCGTTAAGCATAATCGAACGGTGCCCAGTACAGGGTGAGCTGAGCACAAAAATTA

          GACGGCGTTCCAGTCATATGAGCGACGACGCAGTCATTTAATTCGTTGCTATGTACAATA
          GATGGCGTTCCAGTCATATGACCGACAACGCAGTCATTTGGTTAGCTGCTACGTACAATA
          GGAAGTCTTTCGGATACCTGGCAACTGATGCGCCCGTTTAATCAGCCGCTATGCGTAATT
          ACGGATGTTCGCCATTGATCACTACTAATGGACTTCTACGGACCACGGCCCCGCGAAGTC
          CCAGGGATCCAATAAACGAGATTACCGATGAGACTCGTCGACTAGCCGGCGTGATAGTGA
          TTCTGCAAATTAGGTCTAGATTAAGAGAACTAGTTGCTTACGCAGATGACGCCAAGAGCA
          TCCGGCGCGCACTGGGTGACGCTACAGATCCATGTGTATGGTTCGCAGGGCATTAGATCA
          ACTGGTACTATCGATATGGGAATATTTCCGCCCTTGCCCGCTTCGTAACTCGCTGTGGAG

          TTGACCGATATAGACAGCGATTAGTTGTAGAATTTCCCGCTCCATTGTAGCACCGATGAC
          TTGACCGATATAAACAGCGATTAGTTGTAGAATTTCCCGATCCATTGCAGCACCGATGAC
          CGGACTGTCGCAGATAACAGTAGTTTCCGCAATTTACCGTTACACCATGCTACCGTTGAA
          TACACAATCGCACAAAGTGACAAATCCTAGAGCTTCCCAAGTCGCTTTGACACAGTAGGA
          CAGCCCGCTATAGCAGCCGTGTTAGCGTTGAATCTCACGTTACCCCACAGTTCAGTCGCA
          TGAACTGGTGTGAGTAAAGAGTGCCCAACACCAGTCCGCCAGCCTCCTTTACACAGCCCA
          CGACGAAATGTGGTGGTAGCTCGAACAAGGACACTTGTGCCTTACAGCGACCCATGTGCA
          GGCCTAGGTAACGAAGAACACTCAGAGATGTCGTTCATGCCACAGAACGGGCAATGAACC

          GGCTTCTCGTCGCTCGCAACGACGCTGTATAATCACGCCGCGGTCTGTCGCCCGATTTGT
          GGCTTCTTGTCGCTCGCAACGACGCTGTATAATCACGCCGCGGTCTGTCGCCCGATTTGT
          GTCTCGTTATCGCGCGAAGTGGGGAGGCACTACTATTACCCAGCTTGTAGCTCGGTTCAT
          TGTTATTGGTCGAGCGTATATGACATCCGCGGTTACATAAAGCTCCACCTCTATCATGAT
          TGTTTCTTAAAATGTGCAACCAACCGCTGCGAGCACCTGATCATCTTTGGCATCCCTTAT
          CATTATATCTTGGGAGTTGGTTCTCGCTAAGACCACTACGGGATCGAGCAGACATCTTCT
          TTCCGCCTACTGGTAGATTGCGTTTGCTGAAGACCTTTTGGTCTGAATTCGTTACTACCT
          ATCCCTTTATTGGGAATCAGCGATAGTCTGACTATATTTATGACTCGGAACCCGCCCTTT

          GTACCAATTAGAAGCGCGCGAACCGGTCTCTGTTCCTCTTCCTGTACGAATAAAGAGGGT
          GTACCAATTACAAGCGTTCGAACCGGTCTCTGTTCCTCTTCCTGTACGAATAAAGAGGGT
          GCGCTCGTCGTGAGAACACATGCTGGTCTCTGGACCGAACCCAGCGGGGACCTTGGGGCA
          GTTTTCGTTATACAACTATACTAGGGTCACTGGCCCAGCCCTTGTGAGGGCCGAAAAGGT
          GTGCGCGATATCCGTGTAAGGTCAAGTTACTCATATATCCCACGCGGGGCTCGAGCGAGA
          GGCCTCATCGAGCTACCTAAGGCCGACTATTTGCTCCTCAATACCGTGAGCTCAGTGGAG
          GTCAAGAATATAACTATCGGCCATAGTTCGTACCCACCTCCGAGCGCAGAAGGGCAGGGC
          GTTTGCCATACGCTTATCACGCACCAGCGTCAGGCTCCGGTCAAAAGGGCTGCGCATGAG

          CTGCTATAGGTGAGCAATGAATTCATGGCGTGCTGCATTATGGCTCAAACTCAGAAAGTT
          CTGCTATAGATGAGCAATGAATTTATCGCGTGCTGCATTATGGCTCAAACTGAGAAAGTT
          CTTCACCAGGCAAGCGCTGAAAGTATTGTACGTCAAGCCCTCGCTCATGTACAGCTAAAC
          CTCTGTCAAGCGAGCGCTAAACTTCTCATATGTCGTTTAAGAATTCGCGTAAGTTTGGTG
          TCGCAATGGACAAGCGCTTGCTTTATCAGACGCCGTTTCCACATCCCCAGGTTAGGAGCT
          TGACGACTGGGTTACGGCAAAACAGCCGCTCTGCATACAGCCACCCGAACCAGTTGAGCT
          TTCCGACTGCCAAAAGACACCTGGGGCGCACCCCTATCCCAAGTGGAACGAAAAAACGCT
          ACTCGGTCATTAGCCTTTCAGGATATAGCGCATCAGACTTCGACCCACAGCCATTTACGT

          GGTTCTATTTGCAAAAGAGCTTGACGGCTATACCCTAAACTTATGCAAGTCGAGGGGAGA
          AGTTCTATTTGCAAAAGAGCTTGACGGCTATACCCTAAACTTATGCAAGCCGATGGGAGA
          CAGTGTATTTGTGGCAGTTTCTGACGGTTCTTTTCTGAAAAATCGGAAGAGAAAAGCCAA
          GTTCACGGTAATGGCAATGCGTGAAGCCCTTTCAATAAGTATTTGTACGACAATAGTCGA
          GTTTGTATATGGAGCAGTGCTCGAAACATTTTCCTGAAGTATTCGCATTACAAGTGTAAA
          TTTATCACATTCACTCGTGGCTGGAACGGTCGTATCTCGAATGGCCCTGTTGTTGCCGAC
          GCTTTTACCCATATCGGTGATCCGTTTGTGTCCCTTAACCCCTCTTACCGTTGAAGCTGG
          TTATAGGCGGTGAACTTTGGTGAAAAGGTACTGAGAAGCCGTCTCCTAAGCGAAGGAGTA

          GACGATGAGCGGGATCTGACACTTCCGCCAATAAAATCGACCCTGAGCTTTGCGCGCTGC
          GACGATGCGCGGGGTCTGACACTTCCGCCAACAAGATCGACCCTGAGCTTTGTGCGCTGC
          GATACCGCACAACATGAGGCAATTCCAGAAATAAAATCAGGATAGTGTCTGGCGCGGGAC
          AGACATGTACGGGAGTATGCATTATCGACAGTGTAAATAGAATCGTGAGTTGCGTGGTAT
          GGTTGAATGCGAGTCAAGGCCGCCCCTCCCGTAGGAGTGGGTACATGTCCTGTACAACAT
          AGCGTCGCACGGAATCTGAACACTCCAACAGTACGGACGCATTTGTGGCTTCCGTCAATT
          AACTCCGCGTATGAAAAAAGATGCAACAGCGACAGTATCGATTCGTGCCTTACGTGAAGC
          GGCTGTAAACGTGGGCTGGTCCTGTACCCGCACGAAGCGGCTTCTTGTCTTGCGATTATT

          AAAGAATCAGCTCGAAATAATTTTGAGTGAAATGATCCCGGCAGAAGGGAAAATGAAATT
          AAAGAATCAGCTCGAAATAATTTTGAGTGGAATGATCCCGGCAGAAGGGAAAGTGAAAAT
          AAACAACCAGCTCGAGACACCTATCAGTGAGCTGGTTTAAGGAGCGACGGCAGTGTATAG
          GTGGATTCAGTCAAGATGTCCTGATAGTGCAACCGTTTAGAATACAGCAACAGTTGGAAC
          AAGCAGTCGGCCCAGTCCATCCATGGATGATACTAAATAGCTAGACTTGTCAGTGCGGGA
          AAGCGATTAGTTCTAGAGTTTCATGGGGGGGTAGGCCGCACATTCTTTGACTTCCTATCG
          CAGTGACTAGGGCGGCACGTCAAGGATTGGTCTTAAGGCTAGACGACTTCATACGGGGAG
          TAACAGTAAGTGCGGAAGGTCCACCGACGAACCCTAGAATGCGGTGGGCGACGCATAGGG

          GGTCGGTACCGCTAGTATTCGAGAACATGTTAAGATAAAT
          GGTCGGTACCGCTAGTACTCGGGACCATGTTAAGATGAAT
          CGTCGGAAACCCCGACCCTCGAGCCCGTATCGAGGATGAT
          AGACGGCACCCTGGATACGCGAGACAATGTTAGGGTGGTG
          GGTTCGCCCTACAAATAGCAGGTTCTTTGGCTCGACGGAC
          ACCCCGTCCTCTGAGAGTCCAACTCCGTGTTTAAGTGGAC
          GCACAATTTCCTAGATGACCGATCCTCTAACTGACCGGGT
          AGTCGTCATTCGAAGGAACTTACATCTTATTTTGATGGCA

