 8 1000
t1        GCCCTAAGTCACGGATCGATCCGCAGCGGGGAGTAAGAGTCCATGTACCACGCTCCCAGA
t2        GCCCCTAGACATGGGTTGGCCCACAGCGGGTAGCGAGAGCCCATGCAGCACGCGCCTAGA
t3        GTCTGGCTATACACTCCGCGATGCGGGTAAAACGGAGAGTCTGCGCTGAACGGATTGAGA
t4        GTCCGGATTTGTGATAACTTTCATGGCAAAAACGAAGACGGACTTTAAGATGCGCTTGGT
t5        ACCCGGCAGTAATACCACTTAAGTATAGGTAACAGAGACTTTTCTCAAGAGGAGCCTGAG
t6        ATTCGGCCACACCGGCTCTTAGGCGGGTGGAGGCGGATTAATATTTCACGCGCAACCAGT
t7        TTACATCAGCCAAGGGCCTCGACTTAGGCGAGTCAAGTGCCTCCCTGGCACGACCCACTA
t8        TTTGAGCGAAGTCGGAGCGCAATATGGTGATATTGGGGATTCTCGCAGTTCGAACCCTAT

          AATAGTGTACGAGTCTTGAAGCTCTTGCGGCTGCCCGATGCGCACAGGCCAGAAATCTTC
          AATAGTGTACGAATCTCGAAGCTCTCGCAGCTATTCAATGAGCGCATGTGAGAAGTCTAC
          ATTGACATTTTAGCCTTAACGACTACGTGGCGTTCCACCGGATAGGGGTCCGACCCGACT
          ATTGACATTCCGGCTTAAGGGATTTCACAGGATTTCATTGGCGAGGGGCCCGAAGCGTGC
          GACTTTGACCGAGATTCAGGGACCTCGACGATTATCCAATTGGTAGCGCCCGCACCATAT
          TATCGAGCGAAAGACGTCGCGACGTCGCGGAGCGCCATTTATTGGGGGAATGGCCTGTAT
          ACTGGAGCCAAAGTATTGAACCAATCATAGAAACCCACAGTCCGTTGGGATACCTTGTAT
          GATTGCTCGTAACTAAATGATTAAATGTGGGAATCTGTAGGCCAGCGCATCGTCCCGCCC

          CTTCGGATTGTCGACTGACACCGCTTACGCTGCCTCACCCTTAGTCGCGCCACATTGATC
          CTTCCGATTAACACCTAACACCGTTTACGTTGTCATACCTCAAGTCGTGCCGCGGCAATC
          ACAATGACTTAAGTGCTCAGAGGCCCACTTGACCTTACCCGGGGAGGGTGAGAAGTCCTA
          CTTCCGCATAAAGTTCATTCCGACGAACGTCGATCCGCTCTTTGGAGCGGAAATGCAGCC
          ATCTCACGTATGTTTGCTCAAGATAAAAGCGTCCCTGTTTCTTCCCAGGAAAACGCGTGT
          CACAAGAGGGAGACCCTCCAGAATAACATCTGGGTCGTCTTTCTTCGTGCATTTGTACCC
          TCCCAGTAATTAACCCCTGAAAGCACGCGGTACATAATCCTGGATCACGGATATAAGTTA
          AACATATATATAACACTTAATGTATCTACCGTTGCCTGCGTTTCCAGTGCGAACATGGCC

          TAGGTGGGCCGGGGAGGCCACACTCAGTAAGTGCCTCAATCGAGGAAGTGTCGATGTATA
          CAGGTGTGCCAGGGAGATCACTCCAAGCGAGTCCCTCAATTGAAGAAGTGTCGACGTGTA
          CCAGCGGAATTGGGCCGGTACCGCCAGTGAGAGCCGCAGTTTAGCTTGGACAGATGTAAG
          GTGTCGAGGTGGTGCGGACACAACCGGCAAGAAGCCTTCCTCAGGGCAAATTGGCACACA
          TCTAAGAATTGGGGCGGGCACAGGTAGTAAAGTACTTAGTCGAACAGGAGCAGTCTTACC
          CCGATGGCACGAGGTGAAATTACCGGGTACCACCCCCCGCTCTGTAAGGAATGGGGTAGG
          CCGACGTTGCACAGGAGGAGCGAAACGTAAGGGTCCTGACTCAGGAGATGGTCATGCTAT
          CGACCATTCAGAGTCGCGAACATACAGCCAAAGAATTCCGCTGGGATACGCTGGTACGGC

          TCTACACCCTATAGTAACTTAGTCCAAACGGAAATCGATTAAATCGCCGGTTTCTTCGCG
          CCTGCACCCTACAGTAACTCAGTCCAAACGGACATCGCCTGCACCGTCGGCTTCTTCGCG
          CCCATGATGATGCTCGACTCACCTAAGAGATCACTCGCCTGATACAACGCGATTCTCTAG
          CATGGGATGCCTGATGACCTAGAAAGAAAACCCGCAGCCCTAGATCTAGCTTCCTTCGAG
          CCTAGCGTGCCTGAGAACTTAGACCCGGAGTAGGCAGCCCGACGCCTCGCTAAGCTTCAG
          CACCTTGCAGCCCGCGATTTTAACGTAAGGCGCTTGAGCCGACGTAATGTCTACCGACCG
          TACAGAAGATTAGATTAATCGCGTACGCGGGCCAAAATAGGACGCTAGGAGCGTGCCCTA
          CATAGAGTGACGAACTTTTTGTTATACTGATGGATAGCGGAATATAAAGGGTACGGATTG

          TATTTCCCGAACAAAGGGACCGAACGAAGGTATTGAGTTCAGCATGTTTTGACGCTACGG
          TATTTCCCGACTACAGGTACTGAACGCAGGTGTTAAACTCAGTGTGATTTGACCGTGTGG
          TGCACGTTATATACAAAGGCTGAAGGACATGCCCGATTTGAGCGCACCGAGATTATCGCG
          AATGAACCGTCTACAGGGAGTGGGAAAGGCGATTAGACCATCGGCGAGTATACACTTGAC
          CACAATGTGTGTCCAGGCACGGGGGAGCGTGCTTAGACCAATTCGGGGTAATAGTCCGGA
          ACAATGCCATAGAGAGAGGACGAACAGTCTTCACGACTGCTCCCAGTGTATGCACTAAGT
          CACGTAACATCCACAGAGATCAAAATGCTCGTCAAAAGCACATAAGCCGGACTATCTAAG
          TAGGTATTTAGATAGTAGAGTGCTAGGCTAAAGTAACGACTTGCATAGCGCGCGCCGGGG

          TGGAATGTGCCGACTGTCCATAGAGAGAGTTTTTTCAGTGTTCCACTTTGTCGAATATTT
          TGAGATGCGCTGACAGATCAAAGAGAGAGTACTTCCAGTGTTCTGATTTATCAAATGTAG
          CGAAGCACGGCGTCAGTCCGAAATATCTATACCACGGCCACCGGACAACACCCGTCCCAG
          TGCATCCTAGCAAACGCCTGACAAGCTCACACTTTTGGCGTCGTATTCTAACTAGTCTCG
          CGCCCCCTGGTAGCTACCTGCATGTTGCACCAGCCAAGCATTGCCCACCATTCCACCCCG
          TAATTTCTGGATGACGTCTGGGAGTGGGATGTCTCTAGTAACGAACCCTATATTGTTCCA
          ACCCTAACGGCAGTCATCCGTGGGTGCCATATACTGTGCTCCACGCGAAATCTGACTGTA
          CTCTTTGACATTTTTGGCTGAGGGTCTCATTACATCGCTATAGTCTCTAAGTCGATTCCC

          AGGTTGTCCACGTACGACTCCGCCATCGCAAAACCGAGTTGAACGCCGTACATACTGGGC
          TGGCCGCGCACGTAGGACTCTGTCATCGCAACACTGCATTGAAAGCCGCACATACTGGGC
          TGACTGTCCATATACGCCCTCGCCTTAGAAATGTAGAGCTACAGGCCGCGCCCTAAGAGT
          TGCCCGATGTTCCACGCCACCGATTCTGGAATGCCGTTCAGAAAACTGCTGGTACTGAGA
          TGGGCGTTTTTGATTGGCTTTGCCTCTGGAAGGCTGTACTCAGGAACTATCTTTCTACTC
          TGGGCATCTGTGATTGACTCCGTGCCAGGGCTGCAGTATCATTAGCGGGGTTTGCTTAGC
          CGCCCGTTTGCGACTGGATCTGCTCCTACAATATTGGGTAGAGGATCTCCTAAATTTAGT
          TTCCCGGATATTCCTGTAACCGCCCGTGCAACACTGTGGTTACGCTTCTGCACATTTATT

          TGATCAAGATATCTCACCGCGTGGAAGCTAACCCGTCGCGCTGTCAACCACGGTTGCGTT
          AGACCAAGATATGTCACCGCGCGAAAGCTAACCCGTTGCGCCGTTAACCACGGTTGCATC
          ATATCAGGACACATTGGCACGTGGGAGCTTACAAGCTACGCTCTTTTCCACGATTGTTGT
          ATATCGGAACTCTCCGATCTGCAAAAGCCTATGCAACGCGTCGTCGATCACTGTCGCTCC
          CTGGGGGATTCCCTCAATGGGTTAAATCGTTCGCGTTGGGCTGCTTGCCACAGATGTACC
          AGATCCGTGTCCGATACCGTATCACGGCTTGCTCGCTACATTGGAATTTACTTTTGTCTA
          TTTCCCGTGTACTCTATTAGGACAACGCTTACTTGACGCGTTAATGGCGATCGTTCCTTA
          GAGCAACTGTACTTGCTCGGCCACAAGCCATAATTATCCTTTGTTGATGCAGCTCGTATA

          GAGACTCTTCCAGGATGTACCTCATGGAAAACGTCTTGATGGGTTCGTCCCTGGCCTTAC
          AAATCAATTCCAGGATGTACCTCATGGAGAGCACGATGATAGATTCGCCTCCGGCGTTAC
          GGACCGACCTACGTAAGGACCTTACGTGGAAGACGAGGATGGAATTATAACAGGCGCCAT
          GCGTAATCATCAGTCGAGACTGTTCAAAAAAGTCGGTGACCGTGCCTCACCCAGCATTAT
          GTGCGAACGATGGCCTCGACTGGCTTGGGGATACGGTCAGAGAGTGATTCTCGAAGTGGT
          TACCACAACATAGAGTATAGCTTCCTGGAAGAGAGATTGCCGTGTCCCACCCTTCGTCGT
          GGGATAGCAATAATCTGGATTCATCCGGAGATTCGTTTAGTTAGCGGCGCACCCTGACTC
          CCGCTAACCGTCGTGCCAAATCGCCGGGTAAGTCAGCTACCGCAGTATGATTAGTGGCCT

          TACGGGTCACGCACGGTCAACGTCACACTTGGAGATTTAAACAAGCGAGGGGAGCCGGTT
          TGCCACTTAGGCGCGGTTTGCGCCACCCCTCGAGACTCATACAAGCGAGGGGAGTCGGCC
          AGTGCACCAGTCGCAGTATCCGGCTCACTTAGTGAACTAGCTAGGTCAGGGGAACTGGTG
          TACGAGCTCGATACACCATATGTCGTATTTTACGAATCATCTAAACAAGCGAAACCACTA
          GGTGAGTTTTCTATAGACAATGCGGTCTTCTGAATCTTGTCTGAGCGGGTGAGACGGGGC
          AATGGCCTAGAGCCAGCGTTTGAGACCTCTGAGGTATTTACCAAGCGGCTGGCGTTTAAC
          TAGAGTAGATATGTAGCGTATACTAGCCTAGGCTTATTTAATAGAAAAGCGAATCCGGTT
          ATCAAGCGACGCACTCCTCAGTCTGCCTAAGAAGCGCTTCTTGAATGCATGGCTGTAGTT

          TTGAAACCACGCTTTAAGTATACATTAGTCGGGCATGTCCGTATGCTCTGTCGCTTGAAA
          TTGAGCCTCTGCTTTTTCCTTACATTAGTAGAGCATGACGGTATGTTCTGTCGGTTGAAA
          CTCAAAACTTGTTCTACTCCCTGATTAGTAAGGTCTGCCAGTTAATTCCTTCAGCCGTAA
          CAACAGTGTCGTCTTCATACTTCAATGGCTGCACCTTCCACCATACCCACTCCGGCCTAA
          CTGAGAGCTTGCCCCCAGCCTCAATTGGCTGAGAATGCTAGCTCACCTCTTAATTGTGGG
          GCGAGCTCCAGCCCCCCCGATCAAATTGTAATGTGCGCCACCGCTCTTCACTCGACGAGA
          CCATGCTTCAGCCCCTATCTTCAGTGAGCGGCGCATGTCATCTTGAGTTTTTAGCTACGA
          ATGAACACGATTCACACGGTTACCGACACAGCACATACGCGTCTTGTACGTCTGTCAAAA

          AGCTGACAGGGACGTCGAACAACATCGTTGAAAGGTGCTTAGGCTGTCGCCGTGCACGCC
          ATCTGACCGGGACGTTGGACAATATCGCTATACGGCGATTAGGCTGTCGCTGTGTGCGCC
          TGTAGCCGGGTAAGTTGGAAACGTTCAACTTAGTTCGCTTAGATTATACCTATGTAAACT
          AGTCGACGGAGGTACCGGATCAAACCGAGGTGACGTGAACAAGCCAATACATCATCCTCG
          CATATTTCGGGTGTCCGTTTGTCAGAACTGCTATACGCGACTATAGAAACACACGTGGAT
          CCTCGAAAGGAGCAAAGACCAAGTTCGACTCCGTGGAAGATGGCAAACACGCGATCTGCC
          TCCCAAAGGTGCAAACAAAACCACCGGACCAAACGCCGTGCATCCAGTATAAGGACCGCC
          AGACGGGGTAAATAGTTGATTCATATAGCTTGATGTTTCAGAAAAGAAACGATTATTGCC

          AGAGTATTGTCCTTGGGTGGAGCTGACCGGCATCTGGTGCCAGGTCAGCGCTGGTGCCGC
          AGATCCTTGTCCTTGGGTGAGGCCGACTTGCATCTGGTGCTACGGCAGCGCTGGTGCCGC
          AGCAGTTTGGTACAGAGCGATACAGGCTAACGCCAGCATCTATCTCGGAGATACAACCGT
          AACGGCTAGGTTTAAAGAGGAACAATCAGACGTGCGGCAGTAAGATGGTAGCGATGTTGT
          TATCTCTTACTGCAAATCGGCAAGAATTGATACCTCATGCCGGTTTCATCCCGAGTGCCT
          AAGGGTACGGTTCTTTGTGGTGCAAGCCACGCTCTTTCATTTTACCACCACGGGGGACGG
          GAGCAAATGGCGCTAACCGAAAGGAACAAACATCAGCCATCACTGTGCCACGCGGCATGG
          GATAGATTGTAGGGATCTACCCGCCGTTAGTCTTGGAGGATGTCAATCTTAAGGACCCAA

          TTATCGGAGTCGATGCAAGTTCTACACGTGAGGGCTGGCAGGTCTGGGAACGGCGGGACT
          CTATCGAAGTCGCTATAAGTTCTCCGCGTGAGAGCCGGCGGATCCCGGAATGGGGAGGCT
          GCAGCGGCGAGGACGAAAGTCGTCCAACAGTGCCAGACGAGGCCTTAAAAAGAAGCCTCT
          GCACCTGAGTGAATTAAGGTCAATTATATGCGGCGTGTGAGGTAACGCCCAGGGGGGCCT
          GGAATGGGTAGCGTCACAGTCATTTCAAGACGGTTTTGGAGGTTTTGAAGACAAGATATT
          CCATTGGGCAGAAGGATATCCGTCGGCAAGCGTAGTATAGGCTCTCAAAGCGGCGGATTT
          ACCGCGGACAAGGTAAAATTCGTATTTGAGGGGAGTAAACGTATCCCGATTGGAGGTTCT
          TTCTAGATCGGTTGCGGAGTCTTTCACTTATACAGTGAGTCGGTCTGCTATACGGGAACT

          CGTCTCATTAAGTTCGTGGTAAACTAGAGCGCTATACTGAGATTAGAGTTCCGCGTACCA
          TGTTTTATTATGTTTTTGACAAACTAAGGCAGTGTGCTTGGATTTGGGAGCCGCGTAGCA
          ATTCGTTTTATGGCCTCGTCGAACTATTCCGGTCTAGTCGGATCAATGCATGTTGTATAG
          AACGCCACAATGTCCGAGCTAGATCTCGTCGATTTAATGGAATAAGGAATTGCTGCTACA
          GGCTTTTTGATCGCAGCGTTTAATTCACCTTGCTTCATATTACTTGAGCCAAGTCGTTAA
          GGTATCGCCACGCTTATCAAAAGTAACGTAGTCTCGGGAATGTTAAAATTGGCTTCTCCG
          GGGACTGATAAGCTCGATAGCTTCTACGCTTGTCTAGTACCGACAGAGCGGGCTGCACAA
          ATCCCTCATGCGTTTGAACTCAGCTAAGTTTACATAGTTAAGTTTGCCGCAGTAACTTCT

          TATCTCGCAGGCGACATCAGTCCCTCTCTGTTATGGCATA
          TGTTTCGAAGACGACATCAGTCCCTTACCATCATGTCATA
          AACCTTCTGGACGATACCAATCGCTCTGTAATAGTCTGGT
          TTTCGCTAAGATGCCGTCAACCTCTCTTCAATGCCACAGG
          TATCTGTCAGCCAACTTTGTCCCTCATCGGGAGCGTCCGA
          TACAGACTAGCAAGCCTTGTTTACTAGTAAATTGACAGGA
          CTTCTCTAAAGGGGCCCAGTCTATTGGCTACCACAACTAG
          AGGGATGAATGCAAATGTGCATAGCACGTTCCGTGGCCGA

