 8 1000
t1        TGTAACATGCTCGTCGAAGTAACACCTATAGACAATCTTTGGGAGGAGCCACAAGCGATA
t2        GGTAAAATGTCAGACGAAGTCATACTCATAAACGGCCCCTGGGGCGAGCCCCAGGCCATG
t3        TGTAACCGAGTAGCTCGTGTTATACTTTGGCGCCAGCTCATGAGCGTGCCCTAGAGGACA
t4        CGTGATATGCTAGTTAAGGTCGCACATGGCCACAATTTCGGAAACGAAGGGTATACAGAG
t5        CATAACGCGATGATCGGGAAAGGACTTCGGCACATTTTCGCGCAAATGCTTAAAGGGATG
t6        TATAACGAGACGTTTGAGGAGGGCCTTAGCCATACTTCTGTAAGAACCCGTAAAGAGTCG
t7        GGCAACGCCTGGATGATGAGCCCGGATAAGCTTGCGCCTGAAAGTAAGATATGTACCAAG
t8        GGTAACGCCTGGACCATGAGCCCTGGTAGGCCTGCGCCTGAAAGTAAGATACGTACCAAG

          CCGTTAGCCAGTCCCACGAGAAGGCGGTTACGGACTACACAGAGTCAGTTCGCAGTAAGT
          CGGTTGACGAGCTCCATCGGAAGGCGTCCACGGCCTATATGCGGTATGGTGCAACTTAAT
          TTGGAGACGAGCTCTTTAAGAGGGCGGCTACGGCTTATATATAGCCAGCTGCGGGACCCA
          CTGACGACAAATCCTCCAAGGGGTCTGCCGCGACTTCTGCACGGGCCGGTGGGAGTCTCC
          CCGCTGTCGAGCCTCTCTGAGAGGTGCAGTTGGTCTGCCCGAGGCTAAGCGGATGTCTAG
          CCGACGGTCAGCGTCGCTAGGAGGTAGGTAAGGGCTGCCCATGGCCCGGCGAAGGATTAG
          CCGGCGATGGGCCTCTTACGGTGGAGACCACAAGGCATCTTTGCACCGCAAGTGGGTACT
          CCGGCAATTAACCTCTTACGGTGGAGACCACAAATCATCTTTGCACAGCAAGTAGGTACT

          CTGCTGAGGCACAGGGGTGACACCGACGTGGGGGGGGAGATATGAGGTGTATTGTTCTCG
          CTGCTGAGGCATGTGATTGACATCGACGTGAAGATGAACATATAAGGTGCATTGCCTTTG
          CAGTCGAGATATGCAGGTGCCGTCGTTCTGGAGTCGTGTACACAAAGTGTGTCTCTCTTA
          GGGTCGAGTGTCGTAAATACCATCAATTTGGTTGAGACCCTATCAAGCGTCTTGATCTAG
          TAACCATGGCCTCTGAGTGCCACGGAACCGAAAAAGTACACGTTAGGTGCGGCATACTAT
          CAGCCGTGGACTACGGTTCCTACGGAATCGGAGTGGTACACATTAGGCGAGGTACGATAA
          AATGACACGGTCCTGGCCACGGAACTGCCGGATGTACAATAGACAGGAACCCTACTTATA
          ACTGACCCGGTCCTGGCCACCGAACTGCCAGATGCAGGATAGTCAGGAACCCTACTTTTT

          CAGGCTGCAGGAAACACCGAATGAAACCAGGGGATCCGCGCGGCCCTAGGTCACCAGAAT
          CACGGTGCAAGATTGACGGAGTAAATTCAATGGATTTGCATGGGTCTGGACTGCCCGAAG
          CCGGGTGTGGAAGGCACCGGGACCAAAAAGAGGGTTCGACTAGTCCCAGGCAGTCCTGAG
          CGGGGCGCGGGAGACGTAATGCTCAACCAACGGATCTGCTTATTCTAGTATCACTGAGAG
          CGGGCTGTTGGGTGTGCGGACATTGATTCGGAGACACACCCATTCCAGCAAAGCGTCGAT
          CGGGCTGCTGGGTATGTGGAGATTGCTCAGAAGATTCACCCGTCTCCGGAAAGTGTCAAC
          TAGGGTAACATAGTTGCGTAACTGAAGTAGGAGATTTACGAGCGGTAGGGTGTCCCGAAG
          TAGGGTAACATCGTTGCGTAACTGAACTAAGAGATTTATGAGTGGTAGGGTGTCCCGAAA

          ATAAGTTGGACGACGCGCGTCAGGAGTGTCACCTCTCAAGAGCGCGAATAATGAGAAGTG
          GCTGGCTAGATGGAACGCGTCACCAGTATCACCTTCCAGGAGGGCGATTTAGGTAAGGTA
          TCTGACCGGGTAAAGTACGTCAAAAGCGATACATCCCGGGAACGCTACTCAAGTAGGGCA
          CTTGGTCGGCTGTTGTGTGTCAAATGCATCGCTTTGCAACGCCATCAGATAAATGTGATA
          ACGAGACGGACCCTGAGCGTATCAGGTTCTCTCCTCCTGTATTACTATAACAGTAACCGG
          ACTATACGAAGTCTGTGCGTGACAGGTTTTCTTGCGCTGTATCGCTTCAACAGCGACCGA
          GACCCCGGGATTCCATCAGGTGCTTCCTTACATTATCGTTCTCGCTCTAGGCGTAGAGCG
          GACCCCAGGACTCCCTCAGGTGTCTCCCTGCACTATCGCTCACACCCTAGGCACAGAGCG

          CGTTACGAATTCAACTGCGGGTTACAGAATTGAGAGCCCTTTCACGATATTGATGCTACA
          CATTGAGAACTCAGCTGCGGGTCTCGGCATTAAAAAACCTCCTGCCGTGCTGCTAACATC
          TGCCGAGAAAAAGCCTGCACGTCCCAGCATGATGGTGTTGCTCGCGATGTCGACATCGCT
          AATTGAAGCACCTGTTTTACACTCTCGTACTGTCCCCCATCCCACCAAGCCGACATTGTT
          TACGCAGTCAGAGGTCGCCCATTCTGGAGCGGTAACCGCCCCAGCAATTATGGGGTTGAA
          AGTCTGGGTATTGATCGTGCGTCCTGGTGGGGTAACTGCCCTAGTAATAAAGGGAACAAC
          GTACACTGCCCGGATTGCAACCCTCGAGGACTTCATCACCCTAAATTTTTTGCCAATGCC
          GATAACTGCCAGGATTGCAACCCTCGAGGACTTCACCATCCTAAATGTTTTGCTAAGACC

          AGTCCGCCACACTCCGCAATTATACTATTTCTTCGGCTAATCATTAGTTGCATACGCAAA
          GGCCAGCCACATCCCGCAGTCATATTATCCTCTCGGCCAATCACTTGCCACGTGCACTAG
          GATCCGCCGTACTTAGGCGTCATTTTATCGCTTAAGCTAGCTACTCATCTCAACGTCATG
          GACTGCCAACGATTTGAACCCTGACCACTGCACAAATTTATCGACTGGCGCACACCAGGA
          CAGCCGACGGGACTACGAGGCACACTAACCCTCTGACTGCGAATCGGTCGAACATCCAAG
          CAGTCGATGTACCGACGTCGTAGACTGCCCCCTTAGTTTCAAGTTGGACATATACCCAAA
          GATTCTTGCCCCCACGGGGCCAAGGGATACACCCACATATTTCACTCCGACCTCTTAAGA
          GATTCTTGCCCCCACGGGGCCAAGGGATACACCCAACTATTTCACTCCGACCTCTTTAGA

          TTGTCCTTTCAAATGTGCCGAGTGTTGTTTCAACGCCATGATCGGGCCTCCGTCTTAGCC
          CCGTCCCTCTGAACGCGCTGGGTCTTATTTCAGATTCAGGATCGGACCGTCGTCATAATT
          CTGTGCTGGTGAACTCGCTGATCATCACCCTAGCACTTAGATTTGGCACCGTTGCTAACG
          CAGCGTTTTTAATCTCTCCGAATCCTGTTTCAGATCTAAGACACGGTCGGGTTCACGTTT
          CAACACATATGCACTCACCAAGCACTATTATACTGCATCGCCGGGACCGGCACTACCCCA
          TTAGGTTTATGGCCTTTATGAGTACTATCTTAACGCCCCGGCACGTCCGGCTATACTCTA
          GGATCTCGGTGTGCGTGCGTAGCCAGGGAACGGCTTTGAGACACTGCCGTTCGCGTGGCG
          GGATCTCGGTATGCGTGCCTAGCTGGGGAACGGCTTCGAAAGACTGCCGTTCGCGTGGCG

          ATAACAGATGATCTCTCTGGGTATACAGTCGATCGCCCCCTTTTCAGTGAAGAGCACTGA
          ACAACCGCGGATCTCTCTGGGTGTACAGCCGCTCATTCCGTCACCGATGAAGTGTACAGT
          AGGATAACAAGCGTCTCTGGGAAGACGGTGGATCCCGTTCCGATTAATAGGGCGGACTGA
          TTAATAGAGGATGTTTTTGTGTACACAGTAACCCGGCCAACTAAGAATACAGTGCTCGGA
          GTACTGCGTAAGACCCCCGGATTAACGGCGCTTCGCACCATTGCTAACGGCGAGCTCTCC
          GTACTGGGCTACGTCCCCAGACTAATGGTAGGCCATACCACTACCAACGGCGAACTTTAA
          GTTTCCATTGGTCTGACCGTACAGAGGGGTGTCATCCAGATCGCACATCATTCGTTCCAA
          GTTTCCATTGGTCTGACCGCACAGAGGGGTGTCGTCCAGATCGCGCATCATTCGTTCCAA

          TCCTTAACATCTCCGAAGTTTTCCCAATACATAGCCACAGAATGTGCGTTGGCTTTTTCT
          CCCTTAACATCTTCAAACTTTTATTAGTATTCAAATACAAAATACGCACTGGCTGCTTGT
          GATTTGATATCCATAAAGCTACTTCGCTGCGCGCGAACAGTATACATCGTGTCTTCTTTT
          TAACTCACATCTCTACCCTCCGCTCGTTACGTATTCACCGTGAGAGTAGTGGCCTTTACC
          CTTTGGATATCTTCGGGGTATCGCGAATCCATGAATCCCGGTCATGCTGCGGCCTCCCCT
          CCTACGAGACTTCAATGATTTGGCGGCTTCGTGAACACTGGCTACTCTGCGGGTATTCGA
          ATATGACTAGTGCTGTTGCCAAGCTTACGCAATGGCGTCCCTACCGCTGTGATGGACACA
          ATTCGACTGGTACTGCTATCAAGCTTACGCAATGGCGCCCCTACCCCTGTGATGGACACA

          TATGTCGGACAATCACTAGAGGTGCACATTCTGCACTCTCCTACGAGGGACATATCTCGC
          CGCGCCGGATAATCCCCTAAGGTGCATATTCACCACAACCCTACGCGGGAGGTATCGCGC
          CGTACCTGAGAATCCCTCAAGCTATAAATATGTTGGGTCCTCGCGAGGGAAGTCCCGCAT
          CATTTCCTGTGGCTATCCCAGGTGTACTCTAATGACTGAGTCACAAGGGCGCTCTCACAT
          AATGGCGTCCAATACTACAGAGCGAGCCCGTGTCAATACCCCAGGGGGGTATTCTCGCAC
          AATATTGCGAAATGTCATCAAGTGAGTTATTGTTGCAGCCCGAAGAGGGTGTTCTGGTAC
          CTCGTCTGGATACCCCCAGTCATCAGAGCTGAGTGTCAGTTGAGGTCCGACGCATTGGTT
          CTCGTTTGGATACCCCCATTCATCAGAGCTGAGTGTCAGTTAATGTCCGACGCATTGGTC

          TGACTAGACTGTCGTGGTTTTAATGAAAATTCACTAGCAGTAAACATGCTCCAACCGCGT
          TGATTAGATTGCCTAGGTTTAATTCTAAATCCACTAGTCGCAGATGCGGCCAATTCGCGT
          TAACTTGAATGCCCACCTCCAAACTCAAGTCAACGGTTCGAGTAATTGACTTAACTCTGC
          CCGATAGTTTCTAACGATTGGAATTCGTGTGGACAGGTCGTACATATTAGCAAATTGGCC
          CGTCGAGACTTCTACAGAGTCAACATGGACGTTCTCTTCTTAGACTCGGAGATACAACAT
          CAGCAGGTTTCATCAAGAGCCTAAATGAACGTTCTCCTCTAATATTTGGGGGCGTTACAT
          TAACCAAATGACCAATAGTCGTATGGGCCACTGCGGTCAGGACGGGCCACGATCTCAAAC
          TAACCAAATGATCCATAATCATATGGGCCGCTGAGGTCAGAACGGGCCACGATCTCAAAC

          GCCTTAAGGCGGCAGGCTCACTGACACTTGCACGGGGGACACCGGCTAGGTGTCAAATCT
          ACGCTAGAGCGCCGATTTTACCGACACTTGCTCAGTGGACATCGGTCAGATTTCCAACTC
          ACGTTAGTGTACAATCGCAGGTAAAAGTGCTCGAGAGCGCCCCGGGTGGGTCTTTTATAC
          AAGTTGATGATCCAATGCTATCGATACACGTTCGGACATCACTAAGCCGACTTGGCCTAT
          AGCTAGGCTCGACTATTTCACTCACACTAACGGAGGGCTCGATTTCTAGTCTCACCTGAT
          AGCTTGTTTTGACTACTACACTCACACGAACTGAAGGCCTCATTACTTATTTCACCTCTC
          ATTTCGACTAATTTCCGCGGGGCCAACTCGTTTGTGAAGCGACGAAGATAGCGCGGACAT
          ATTTCGACTGATTTTCGCGAGGCCCACTCGTTTGTGAAGCATCGAAGATAGTTCGGACAT

          TGTAAATCGCACCCGAGCCAGCTTATGCGTAAGAGCCACCGTATGAATACTACTTATCAA
          TGTACATCGCAACCGACCAAGCCTAAGTGTAAGAGTCAGTGTATGACCATCACTCTGTCA
          TGAGAGCCATCAGCAACCCGGTCAACTTGCAGGTGCTAGCGCTTAAACTACGCTTAGTAA
          CGTGAATCGCCAGCAACTTGGGCTATGCGTGCGTATCCCCTCACGTATACTATTTCGAAA
          GACCAGACGTCAGTGGTTGATACTTCCTATGGATTCTAGCGAACGAGTAACCGCTCTCAC
          GGCCAGAAATTAGTGATCGTTCCTCCATGTGACTACAAACGAGAGAATGACTGTTCGCAA
          CTGATACAGCTGATAGTACGGTTTGCCCCCAATGTCGTAGGCCATGACTATAACTCTCTG
          CTGATTCAGCTGATAACACGGTTTGCCCCCAGTGATCAAGGCGTTGACTACAACTCTCTG

          AGAATTTACGATTTAAGAATTAACGTCGAGTGCTATTGTCCTCATCACATGGATGGCCAA
          AAAAATAGTGGTCCATGACCCTAGGTCAGGCGATGTGGTTCCTACCAAGCAAATGGTCGG
          AAATCACCTACTGCGTTGAGTCATGTCTGGTGTGGTGGCCTTTATATCTTTAAGGGCTGG
          TATAACCGCACTTCGCCAATTTGCGCCACGTGCCACACCCTATGGCTCATGCGAGATTGA
          CGACGCTGCTATCCGCTTACCTATGACCGGGGGCGGGAGTTCGGTCGATTTGGCTGCAGA
          AGACGCTTTTATACATCTATATACAACCGGGGGTGGGGGCCTTGGCGGTCTAACTGCGGA
          TAAGAGCGCCCGTTAGAAGAACGGATTGACGCCTCCAGCCAATGCCGAATATATGAACGG
          TAAGAGCGCACATTAGAAGAACGGATTGACGCCTCCAGCCAATGCCGAATTTACGAGCGG

          GGAAACACTTCGAATTTTGTTGTGATCCCGATCCTATTAGCGCACGTGGATCGTGTCTGT
          GGAAACACTCTAAGTATTGCTATCATGCGGAGCCTGCTAGCATATGATGATGGTCTTTGT
          CGATTTCTTCTTAACTTTGTCAAAAGGCTGATACCGCTAGTACATGCGTGTGGTATCCTC
          ATGGATGCTCCCATCTTCGTACTGAAGCAGCCCATCCCAGCCTATGCAAACAGTTCCTTT
          CTGGTTGTACCTACCCCCACTTCTCAGTGATTTTTGCGGGGCGGTCCTTGTGGCGTTTTT
          TCGGGCGTACCTGCCCCGATTTCTCAGTTATCTTCGCAAGACGATATGTGTGGCGTCCAC
          TCACCCCTATCAGGTAATGAATAATTGCAGTTCTTATTAATCACAATGCCCTTAATCTGA
          TCATCCCTATGAGATAGTGAATAATTGCGGTTCTTATTAATCACAATGCTCTTAATCTGA

          CGCGGCCGTTGGTGGACCGTCTAGAAGCAGACTGCCCGGC
          CACGGACGCACAGTGACCAACCGGCAGTAAATCGCACAGT
          TGTCGCCCATGGAAGCCTCTCTCGTCATTCTGGGCGCGGC
          GGCCGCCACCAAGAGTCTACATAGTTGTTTACTGTGCGAG
          GGGAGCCAACGATAACTCACTTCTATCACGTCTTGATGAC
          CGCAGCCGACGAACACTCGCTTCAGCCCCAGCAGTGTGAC
          TGCAATGTGTTGGTGTCTGCTATCGTCCACTACGAGTAGA
          TGCATCGTCTTGGTGTCTGCTAACGTCCGCTACGTGCAGA

