 8 1000
t1        TACCTCAATACGCTCATTGTGAGTCTCCCCTGAAGCACAATTCAAGTCGGTTTCTGCGCG
t2        CACTACAGTATGGTCTCTATGAACCTCATCTGAAGCCAAGTAACGGTCAGCCACAACGCG
t3        GATCACTGAGTGTTCATTGTGACTGTCAACTGGGGCAAGCTTCCAGTCATTGCCAATGTG
t4        TACCACTGTGTGTTTATTGTGAGCGTTACCTGAAGCAAACTCTCAATTACTCTCAATGCG
t5        AGCTGTTGTCAGACTGGGAAAAAGCCCAGCTGGGTCAATACCCTCGGCGGTCAGGGTGTA
t6        AGCTGCTGTCCGAACGGGAGAAAGCCTAGGTGGGTCAATATCCTCGGCGGCCAAGGCGTA
t7        GGCCCCGACTCGCCTTGGACCTCGTCTGGCCGTACCGCAATGCCTGTTGTCCAAGTGATA
t8        TCCTGCTATATGACTGCCACAAAGCCCTACTAGTTGAATGATCCAGGAGTGACGGACGAA

          GTGACGGCGTGCACTGAAGCGGACATGGGCCCCGTTTCTGAAGACCGGTTCATTTTATGT
          ACGGTTGCGCGCAACAAAGCGGCCATGGCTTATGTTCTAGAAGGTCGCCTTATTTCCTGT
          ATAGCAACGTATAACAAAATGCGCAAAGGTTCCACTTATAAAGATAGGTTTACGCTATGT
          TTAGCAACGTTTAACGAAGCGCGTAAAGGCTGTGCTTATGAGGACCAGTTCACGCTATTA
          CTAGGCCTTCCCGGCGGTACGTTCCAAAACTGCACTCCGATCTCCGGTCACATTTTGTAA
          CGAGCTCCTCCTGGCGACACGTCCTAACACTACACTTTGATCGACGGTTACACTCCGTAA
          GGAGTCGGGCAAGGGAACGCAGTTCTGGGTACTGCATTGATGGATTATCTTACCTTACAT
          GGAGCTATGTACGGCAATACGGATTCGCACACTGTAAGGAAGACCCGTCTCGCTTTGGAC

          CGTTAGCGAATGTCAAGAACGGCGCCCGTCGGTCCCGAATATCCGCAGGGTTATATTCGT
          CGCTAACGTATGGCGGGGACGGCCACCGCAGGTCTCGTGTATCGGAAGCGCTGCACCCCC
          CGCCAGCGCACATCTGGCTCGGTGCATGTGAGTTCCATATACTAATAGCGTTTTACCGAC
          GGCCACCATATACTTTGATCAACGCGCATGGGTCCCTTATATCAGCAGACTCTTACCGGT
          TTACTGTCTATAGTAATTCCCGGTTGGGCAGCTCCTTCGTACAGAAATCAAGCGCTCTGG
          TTGCTATCTCCAGTAATTCCGGGACAAGTATCCCCTTTGTACTGCAACCAAGCGACCTGG
          TGCTTCGGCAAGGGTGTGTCAGTTCGGTTAGTGCCATCAAAGTGCCACTGGTCCAAAGAG
          TCGTTGTGTGAAGTCATGGTAGCGCGTCGGGTTGTTCTCTACCGGCGTGGTACAGTTTGG

          GTTCTGGATCAAATCGAACTTCCTATACAGATGGAGTTGTTTCTAACGAAAAAGGTGATA
          GTTCGAGATCGAGCCGAACTATATAGAGAGACGGGCTCATATCTAATAAAACACGTTATA
          GATTCGGATTGAGCTAGACTTCACCAAAAATTGGGATTAGTCGTAGCAGAGCAGGTACCA
          GTTTCGGGTCAGGATGGACTCCTCAGAAAGCCGGGACTATTTCTAACAACGCCGGTTACA
          GGATTGCAATGGGACTAAGATTCTTATGCCGATGGTGGCTGATCAGTATCTCGTTTGGTG
          GAATTGCATCGGGACTAAGGTTCTTACGTTGATGGTTGATGATCCGTATCTCGTTTGGTG
          GCTATCCACGGGCCGCGATATGATTTCCAACTATGACCACCCGAATCCAATTTCAAGGAA
          GTGTCGTACAGTTCTCGAAATACTCGCACAGTGAGTACACTTCTCCTTCCGCCCCAGACT

          CACCCCACCATCGAGTGTTAATTGACACATCCGTTTCTCGGCGTGGCCTCGGGGAAGTGT
          CATCCCAGCGCTCGATGTTAACCGGCATGCCGCCTCTCCGGCACCGTCGTTCAGAGGTGT
          TTATGTGCCCCCCAGTGTCATTCGACCCGCAGACTCTTCCGCACGGCCTACCTGACGTGT
          TAACTCGTCCCCTAGTGTGATTTGGCCCGCAGACTCTCCGGCACAGCCTACAGGAACTGT
          CCGCCCAATATTGCGTATGGCGGCGGTTGAATGTTGTTCGGGCCGTATGACTATCGTCTT
          TAGTTCGACATTGCGTATAGCGGCGGTCGACTGTCGTTCGGGTCGTTTGCAAACCGTCTT
          CTGTACTGAACCCTGGTGACCATCTGTAAAACTTTCTACAGCCTCAAGTGACCTGTTCTA
          CGCTTCAGTACTCCGCTATTCTTGCGCTGGTCGCCACTTGAATCCGGCCGCTGAACCGAT

          ATCTCTTATCCCGATGTCGAGGAACTGCCAGCACACAGTCGTGCATAGGTTTGTAGTATC
          ATGTCCGATCCCTCTGTCGCGGAATCGCCGATATTTAATCGTGTATAAATTTGTTGTATG
          GTTTCCGCGCCTAATTCCAGGTAAACGTCAGTTCCGTAGCGCGTGGGAATTTTTCGTTTG
          ACTTCTGTGCCCAACTCCTGGGACGCGTCAGTGCCTAATCGCGCATGAATTTCTCGTTCG
          TATCTCAATGTCAGGATCGGCCTTACGGTGCGTGTCTTTCCTGATTTGTGTATATAGCAA
          TACCTCAACGTCAGGGTTGGGCTATGGATGCGTATCCGTCGATATTCGTGAAAATCGCAA
          TATCTTGTCACCGAAAATGCGTCCACGATGCTGCCGGGTGAGAAGTCAGTCCGACGATTG
          CACACGAAACCCAAAGTCCGGTCGGTGGAGCTCTGATATTGTGATTGGACCAGATACCTT

          GGGTCGTTCCGTCGTGATAATAATGTATCGTCCGTCACCCTAAAACACTTAGGGACAAGT
          GGGTCGTTTCAATGTGACGGCAGTGTACAGTGCCTCATCCTAGATTTGCTGGGAAGCAGT
          GGGTTATCCCGGTGTGGGGGTGGTGTACCGTACGATACCTTAGATGATTTGGGGAGAGGT
          GGGATTTTTTAGTGTGAGGATGATGTACCATACGCTACCTTAGACGATTTGGGGGGAAGT
          GGGTCCCGATTGTCATCAAACGGTATCCAGTATTGCTTTGGGGGGAAATTAAAGGGGATT
          GGGTCCCGGTTGTCATTGAACAGTATCCAGTGCTACCTCGCGGTGAAAATGAAGGGGATT
          GAGTTCCTCTGGCGTAACCTCTATAGGTTAAGAGGGGACGCCATAACTCGTGCCCCTCGA
          GGGTACTTCTGGGATATCTTATATTCCAGGGCCTGCATTATTGTACGTCCCGAGTTGTGC

          TCATATGTAATTTCTAAAGCGTATATTTCGTTGCGGAAATCCGGAGGTTAGGTCAGTGGG
          TCGTAAATTGGCTATGCCGCATATTTTTTGTTGTAGGGAACCCCAAGTTGGGTTAGAGGG
          AAGTGAGCAGACCTCCACGCATTTTCCTCTCTACAGGGACCAAAGAGTTAGACCGATGGG
          GCGTAAGTAGGTCTTCATGCATTTCTATTCCTACAGGGACCTAAGGGTTAGATCGAGGGG
          GTATGGACTCCTGCGGTTTCCTGGCAACCTGCAAAAGGTGCGACAGCCAAAATTCTACCG
          ACGTGGGCACTTCCAGCTTCCCAGTACGCCATGAAAAGTACGATGGCCAAAATTCCGCAG
          CATTGGGGCCCTGTAACCACTTGCTTGCCAACGTTGTCCGCGACGACCTGACCAAGCGTG
          ATTAAAGATTTCACAATAAGGCATGGAGTTGAGTCGGACACCATCCTTATAGTTGAAGTG

          CAACCTAACAAGATTCAGGGACGTAAAGACGAAGGTAACTACGAATGACGTCGCGAGTCG
          AAAACTAATCAATCACAGGGACATATGGTCAATACTAACCCGGAGTATCAGCACGAGACA
          TAACCTAGCACAGCCAGAACACATATCCGTCTTGATAAACTGGAGGGTTGCACCGAGCCA
          TATTTTTGTATAACTAAGGAACGTATGAAAGTTGATAGATTCGAGAGGTGCTCTGAGCCA
          CTTAATATTGAATGTAAGCCATACCCTCTACACGCTAAATCAGGCGTCAATTAACGATAG
          TCGGATATCGAACGTAATCCATACCCCTCACTCATCACATCGGCCGTCAATTAAGGCTTG
          CAGCGTCCCAGCCCTTGAGCAGATTGGAGCTATCCCTCGCGAAGGAATCTTCAAGGGGCG
          CGAGTTTCCGATTGCCGGCCGAATCACGAACAAGATGTTTTTTGGGCCCTGCCATGTTGG

          TTGGGTTTTATTCGTCAAGTACGTTATTCGAATCGTTATCGATGCACTGCTCCTAGAGAC
          CCGGCTGTTGTTTCTCAGTCACGCCACATCAGTCATCGTCGATGTCCTGTTCGTCGAGAC
          TTTGGCTACGATCATCGATCACGGTACCTCAACCTCCGCCGGTGAATCCTTGTTCGAGCT
          TTAAGCGGAAATCACTAGCCACGATATCTTAAGCACCGCCGGGGCACCTTTGCTCGAGAG
          GATGGGACCAATCGTGGATGGATCTGTGTATTGGATTGCGATTACGTGATGACTGGAGGG
          CGTGGGACCAGTCGTGGATGGATCTGTGTATTGGATCGCGGTCAAGTGAAACCTAGAGAG
          GTTGGAATGATTGGGCGCTTGTGGCACATGTCGAATAGCTTAAGCACATTGTGCTAAGAA
          CTTAGACTGACCCTATTCACGAAGTATTGGCCACGCATTAACCACGAAGTGCAAGACGTA

          TGCAGATATCAAGGTATGTTCTCCGCCGTTAAAAAGCCAACCTTCATGATTCGGTAGCGG
          CGCGGCTATCCAGGTATATTCCGTGCTGACAAGGGGCCGTCTTTTAAAATTTGGTGGTGG
          TGCAGTATCCCCGGCACGTTTTAAGTCAGCAAAGAGCCTACCTTTATGTTTTTGGACCGG
          TGCAGTCTCCCCGGCACATTTCGAGGTGGCAAATAGCCAACCTTTGTGTCCTGGGAGCGG
          CGTACATCATAGGAGCCGTAATCCTCGGCAAGAGAGTGCCGTCCATCAAAGTGGCCGCGC
          CGTGCATCATAGGGGCTGATACACTAGCCAAAAGGGCACCGTTTATTAAAATGGCCGCGC
          TGTACGTCGAAAGGCGAACCGTGATCCATCAGGTGAATACCATTCCTATTCCGGCGGTAC
          TATATCTCGTCAGCTAGGACGCGATCCACCCTATAGTCACAGTACTATGCCAAGAGACTT

          TACTACATGCGGCGGTTGTCCTGCGCCCAGAATGCCGGATCTAGACTATGCTAGACTTGA
          GACTATTAAGAGTGACTGTTCCCTGAGCAGTAGGCTGATTTCAAGTTGAGCCAGACTTAG
          TACTACCAGGGCAGACCGCGCTGCGAGCGGAACGCCGGTTCTGGACCGATCCAGAAGTGG
          TATTGGCGGAGCTGAACGTGCCGCAAGCGGTGCGTCGGCTCTAGACTGGCCTAGAAATAG
          CCCTCTTGCTTACGCTTGCACGTAGAGCAAACCAACGGGTCGGAAGCGGTTTAAGTCGGC
          CCCTCTTGATAACGCTTGCACATAGAGCAATCCAACGTGTCGGGTGAGATCTAAGTCAGC
          CCGTTAACTAACGAAGCGCACTATGGCGGGTTCACTGGCCAAGGACGCGCGTGGTCGAGT
          TGGCAGTACTACGGGCTTCTGTAGGATGAGTTACAATGTCTCGGATTAGCCGCCGGACGC

          GGTGATTACCCCGCCCATGGTCCTCATCGTTACCGTTTGCGTAGCCTCACTGTTACTATA
          GGTTGTTAATTCGTCCATGACCTTTTCCGATACTGCTTGTGCAATCCGCCGCTTCCTAGC
          TGTGGGTAAACTAGTCACGACATTTTCCGCCACTGTCTCAATAGCCACCTACTGTTAACA
          GGTAGTTAAGCTGTTCACGTCATCCTTTGACACTCCCTCCCTAGGAATTCTCTAGTATCA
          AACGAGCTCCCTCAACCATATTTTCCCTACCCGCTACCTTCTAGGTTCAAAGTCAACTTC
          CACGAGTTTCTTCTATCAAACTTTCCTTACCCACGACCTTATAGGCTCGAAGTAAACTTC
          CATGGGAGATGTGCCCGGATTACTATACGCTCATTTGTCCAGCCGTTTCCAGTCCGCGGT
          ACTGATCTCTGTGAACGGACAATATGCCGCCAGTACAGAAGCGACCTCATAGGCGGCAGC

          GCGGCGGGTTTATACATCATACTAGCTCTTTCCGGAATGTTTTTTCCCTCACCATACGGT
          GTAGTAGCTGAGGACATCGTAGGAGCCCTTTTCCGTATGCCTTCCCCTTCAAGATACGGT
          GGAGCAGGCCAGGATATCGCACCAGCTGTTTTCTGTATACTTTCACCTCCGGCGGGCAGT
          GAGGCAGGTCACGACATGACACCAGCTCTTATCTGTATACTTCTACGTCCATCGGGCGAT
          TAACTCGGTACAGACGGCTTCGTTGCTTCGCTCGCTGCGCCCGACCCTAAGCAGCATAAC
          CAGCTGAGTGAAGACTGCTCCCTTCTTTCTCTAACTGCGCCTGACCCTAATCAGTACAAT
          GACTTGGGCAGGGACGTCGGATCCGCTTGATTCCAAGCTTTCATACCCTGGCAATATGGG
          AAGTTGCGCCAGGACATCGATACTGAGACTTTCTGTACCGCCTTGCCTCACTCGTGCGAT

          CATCGGAAAGACCGCAGTATCGGGGGCCAGCCACGTCCTTGTTGTTGGCCGTATATTATG
          CGCTAGGAGGATCACGATATCCGATGTCGGTTGAGTCGGCGTTCCTGGCCGTGCATGACG
          CGCTGGTAAGACCACAAGCTTCGTGGTCATCTGGGCCTGGATTTCTAGCTGACCGCAACG
          TGCCGGAAAGATCACGAGGTTGGAGGTCAGTTGCACCAGGCTCTCTAGCTGAATGCAGCG
          AGATCTCTTACCTGTCGAGGTATCGACAATTGCAGCCGTCCTACTAAATCATATGCGGCA
          AGATCTCTGCTATATCGAGGCATCGAAAAATGCCGCTGCCTTACTAAGTGAACTGCAGAA
          TGTCTGAATATAGCTGGAATAAACTAGCTGGTCTGTCGTCGCGCTCAAAATCCCCTCACG
          TATCGGCATCACTGTGGAATTATCGTTAGACCGCGCAAACACATAAAGATAAGTACGGTG

          CTCTGTCAACATGGTTTGCTGAGATAAATATAAGAGGTTATCTTAACGGCGAATGTCGAC
          CCCTGTTTCCATGGTTGGACTACATGTATAGAAGACATTATTTCAACGGCGTACTTCGGT
          TCGTTTCAATATTGTTGGCCTCCATGGGCAAAAGAGTTTATTTCAACGACAAACGGAGAC
          CCATTTCAACATCTCTGGCCTCCCCAGGTGAAGTAGCATATTTCAACGCCGAACCGAGGC
          CAAACTCGACATAGACAATTTCTCGAGATCTAAAAGCTTATACTACGAAATACTCTTTAA
          CAAACTCGGAAATGATAATTCCCTGGAATCTAAAAGATCATACTACGAATTACTTCTTGT
          TCGGCCCCATCAGACTATGAAAGTATGATGCTATGTCCCTCTTGGTGACCCCCTCGACGA
          ATCGTACCGGACGATCAGGAGTTAGAAACCCTAATGCGTAACTGACGTAACCCTTCTAGG

          GGTGGCAGTCGCAGATTCTAGAATTACAGCAAAATCGGAC
          GGTAGCAGCAGCGGGTTTTAGGACCTCCGCGGAGTTGGGT
          GATGGCCATCCCAGCGTTTAGGATTACTGCCAGATTTGAT
          GATGGCAATCCCGGGTTTTAGGATTATCTCAAAACTTGAT
          GTCCCCAGTAATGTCCTGTAGAGGTAATGGTCCACATGCC
          ATCCTCAGCAATGTCTTGTCGAGGGAATGGACTATATACC
          ACTACTAGAACCGTGCCCTAGGGGATAGAGCTGAATGGCA
          ATTGAGGGCACTAGGCTCTATGAACTGATGCTGGCCGACT

