 8 1000
t1        TTACTATCGAGGAAATGAGGAAAAAGAATTATGAGGGTAGCACAGAGCTAGCATCTCCAA
t2        TCATTATCGGGGAGATCAGGAAACAGTACTACGAGGGTAGTAGGGAGCTAGTATCTCCTA
t3        TTATTATTGGGGGGAGCAGGAGAAAGAATCGTTAGGGTAGCACAGAGCTAGGATCTCCAA
t4        TTGTGATCAGTAAAAACAGGAAAAAGAGTTTCGACGGGAACTCAGGACCATCATCCCAAA
t5        CCGTATGCGGAGAAGACGAAGGCATAGATTTTGACGGCCGTGTGAAGCTAGTAATCACAT
t6        CTGTATGAGGGGGAGTGAATAGGGTGAATCCCGATGGCGATATAAAGCTGGTAATCACAA
t7        ACAGTAGCCGAGAGGTTCAACTAGACGATAAGAGCTAGACTTTGTAACAATGAACTTTAT
t8        ACCGTAGCCGAGAGGTTCAATTGGACGTTAGGAGTTCGATTTTGTAATAATGAACTCTCT

          GTCGGGCATTGGTCGGGATTATAGAGTCGACGGCAGACCAACGAGCGTCCTGCACAGGTG
          GCCTGTAATTGTTCGGGATAGTCGAATCGACGGCAGGTCAACGAGTGTCCTGCTCAGGTG
          GCCTGTCATTGTTCGGGATCATAGAGTCGACGGCAGATCAACGACCGTCCTGCACGGATG
          GACTGTCATTGCACGGGATCATAAATTCGGAGGCAGACCAACGACTGTCCTATTAGGGTG
          GGCTGCTATAGAGAGTGGGAGCAAAATCGCTGTTAGTTTAACGTTTATCCAGTTAAGGTG
          GGCTGTCATCGGCGGAGGCCGTAAAGTCGCAGCCAGCCTAGGGTCTATTCATCAATGATT
          ACCCCTCGGGGCCATTCGGGACATGAACAATGGTAAAGCCACGGCCTTCTTTATAGGACC
          ACCCCTCAGGGCCATACCGGACATGAATGATGGTAGAGCCACGGCCTTCTTTATAGGACC

          AGCACTCAGAAAATCAGCTACCTTTCGTCCCTGGTCTACCATGGCGCGCCAGATTGGCCT
          AGCACTCAGAAAATCAATTGCCAATCGTCCCCTGTCTGCCGTGCCATGCTAGATTGGCTT
          GGCACCCAGAAAATCAATTACTTACCAGCCCCGGTATGGCACGATGTTACAGATTAATTT
          GGCACTTGGAGAGTCAGCCGCGTATAGTCCCGAGTCTACCACGGCGTGCTAAAGCGGCCT
          GTCAACTAATGAAATAATTTTATGCTGTCACGGTTATGTCGCAATCTCACAGGTTGGTTT
          GCCCTTAAATGTAACAGTCATATATCGTCGCGCCTCTGGTGCAGTCTCACTAGCCGGTTC
          GGTACCCCCTCTCGAACCCAAGTGGCCATTTACCTAGCAATCCGAGGGTAACGTTGGCAA
          GTTACCCCCTCCCGAACCTGAATGACCATTTACCGCGCACTCCGAAGGTAATGTTGGCGA

          CTTTAATCGTTGCTAGGGTAGTATCTATAAGCGTATCCCTTTATGTAGCGACAGTTTACA
          CTCGAATGATCGCCAAGGTAGCACCTATAAGCGCGTCTCTTTATGTAGCGACAGCCTGCA
          CCCGAGTGGTCGCTAGGGCAGCGTTCGTAGGCGTGTTCCTCGATGCGGCATGAGCCTACA
          CCCGAATGACCGCAAGGGTAGTCTCCGTGAGCGTGTTTCTCTATGTAGCGACAGCCTACA
          CTCTCCTGATCAAAAGGTGAGGAGTTGACAGTGCAAGTCCACAGGCAGCAACATGCTACG
          CTAGACTAATCACACGCTTGGGAGATGGCAGCGCAATTTCTAAGGCAATAATAGGCGACA
          CAAGAGCGAATTCACCGTAAAAGCAGGGCAGCATAGTTTCTTATGCGGAAGGGTGATATA
          CAAGAGCGGATTGATTGTAACAGCAGGGCAGCGTAATTTTTTATGTGGGAGGGTGACATT

          CAAGGAGGAACTCGGACTCCAGGTGCCGATGTCTCCCGATGCAACTCAAAATTAAGCACT
          CAAATAGGTACTCGGACCTCAGGTGACAATGACTTCTGATGAAATTCACAATCAAGCACT
          CAAATAGACACTTGGATCTCAGGTGCAAAAGTTAAATACCGCAATTCGAATACAAGCAAT
          CACTTATGTGTTCAGATTTCAAGTGCCAAAGACAAATGCAGTAAATATGAAAGGAGCGCA
          CTGTGACGCCCCTGGTTCTTCCGTGGTGAGGCTATCTAGTGCGGGTCCCTGACTAGTGCC
          GAGTCATGTGTCTGGTGCTTCTGTGGCGAGGCCACCTAATGACGTTCCCCAAGCAGCGTC
          GAGTTAATGGACTAGCCGTATGATATTAACAGCGCTCAACGCCTCCCTGGCACTATGACC
          GAGTTAATGGACTAGACGTACGACATTAACAGCGCTCAACGCATCCCTGGCGCTATGATT

          CTGTTTCCCTGTACTGCACCCCCTGTCACCCGCATCGTTTTCGGCTGACGTAGCACGCAT
          ATGTTTCTTTGAACCGTGCCTCTCGTCTCCCGCATCGTTTTCCGCCGATGTCGCACGCAT
          ACGTGTTATTGTACCGTGTCTCCCGTCACAAGCATCGTTTTCGGCCTATATAGAATGAAC
          CAATCTTCCCGCAATGTGCCTCCTGTAGTCTGCATTGCCCTCCGCCAATGTACCAAGTAC
          ACTTTTAATCTTCGCGCGCCGCATGTGACCTGCTTAAGAGGCCAGCATCCTACCATGTAT
          ACTTCTACTCATGACGATCTGCGCGCCCCCCGCTTGGAAGGCCGTAACTGCATTATGTGG
          TTATCCAGTTAACCTGGTGACTAAGCCGTGAGTGCAGACGGACCACCGGACGCCTATTAT
          TTACTCTTTCACCCTGGTGACCACGCCGAACGTGTAGACGGACCACCGGACGCCTCTTAT

          CGGTTTCTCGCTAACGGACTCTAATAGCTCACGCAAGGTGTATCTTTCCACTCAAGGCGA
          CGGTTCGTCGCTGACGGACTCTAATAGCACATGCAAGCTACATCGTTCCACTCGAGTCGA
          CAGATTTCCGCTATCGGATTCTCATCGCTCAAGCATGATGCGCTGGTCTACGCGAGGCGA
          CAGTCTGCCGTTCCCGGGCTCGGACCGCTCACGCATGATATGCTGCCCTAGCCGAAGCGG
          CTGCGGGACGCAAATGGATCATATGAGTTATCTGACAATACACTATTTCAGTAATAGTGG
          TGGATCGACGCTATCAGCTCATAACCGTTTTCAAACAACACACCACCTCAGATAAGGCGA
          CCGCAAGGTTATCCTGACCCCTGGGGGTGGTGGACTAATCCTTTGACTACCTATGTAGCA
          ACGCAAGGTTATCCTGACTCTTGGGCGTGTTAGACTACTTCTACGACTTCCTAAGTAGCA

          GTAGGCCCATTGTCAGGGGACTTAGCAACAGTAAACGGGATCGGATACTGACGTTAATCA
          GTAGGCCTATTGTCATGGGAGTTAGCAATAGTGAATGGGATTGGATAATGACATTAATCA
          ATAGGCTTACTGACATGGGAACTAGAAACAATGAGTGGAACCGGACGCCGATATCAACCA
          CTAGGTTTATTTTTACGGGAGTAAGCATCAGTGAGCAGAGCCGCCCAGCGAGGTGTACCG
          CAAGCTTAGTATGGGTAATTATAGGCGACGTACAATACGACCGGTTAATATAATTGGCTA
          CTATGCTAATAATAGTGAACGCATGCAACGCAAGTTGCGACTGGTCAATATAACTGGCTA
          AATACTTCAGAACGATAAACCACTCGGGACTCCGGACAAACGGGGCCGTGCTATGGTTTA
          AATACTTCAGGATGATAAATCACTTGGGACTTCGAACATAAGGGGCCGCGCTATGATCCA

          TAGTAGCTGCCCACACTCTGAGGGGCAAGCGCGACAGTGGTGCACTTACACCAGCGGGCG
          TAGTGGTTGCCCGCACTGTGAGACGCAAGCGCGACGGTGGTGATCTCGCACCAGCGGGGA
          TAGTGGGAGCCCACACTATGAGTGGTAGATGCGACACTGGTGCTTCCCTACCAGCGGGCA
          TGGTGGCTGCTCACACTCTGAATGGTAGTCGCAAAATATGAGTCTTCGCACCAACGAGCA
          ACGTGGTCATTATTACTAAGAATGGCTGCTGCGACCCCGATACGCGTGCTTCACTTCGAG
          GTGTGGGCGATACCATCTCGTATGGCCGTTGTGATCGTGATACGCGTGCTGTAGTGCGAG
          CAGGGGTGGCTATAGTCCCCGTTACGAGTTACGCCGCCTGGTATCACACTCAGGCTACTA
          CGGTCGTCGCTAGAGTCCCCGTTATAAGTTACGCCGCTGGGAATAACACTTAGGCTTCTT

          GTTTAGGGTCGTTCGCGAGGCTCTGAACTCTCTCCCGTTAACTTCGCGGGTGCGAATTCG
          GATCAGGATCGTTCGCGAGGCTCTGAGCTCTCCCCCATTAACTCAGCGGGTGCTAATGCG
          GATTAGGATCGTTCGGGACGTTTCGCATTCCATCCGGCTAACTCTGCGGACGCCAACCCG
          GACTGGTATCGTTTGCGGAGTCCTGCATTTTTTCACGAAAACCACGCGGATGCCAATCCA
          GTCAACAGTGACGCGTATAGCCCTGACCCCCTGCCACAAGTTATCATCGATGTCCTATTG
          GTCAGCAACCACGCGCGTAATACTGACCCCCCGCTATATTTTCCCACCGATGTCAACTTA
          GAGATCGTGAAATCGCCGGGTGATATACTTCATGGCTGAGACTATTTAACGGTGGCATCG
          GGGCTCGGGAAATCGCTGGGCGGTACACTTCATCACTGAAGCTGTATAACGGTGGCATCG

          CCGGCGTGGATGGCGCCTACCGGTTATCTTTTATAGTCCTGCGCCAATCGGCTTACACCA
          CCGGCATGGATGGCACTTACCGGTTACTTTTTCAAGTTCTGCGCTAATCGGCATACACCA
          CCTGTGTGGATCGCGCTTACCGGATATTTTTTAAAATTTTGTACTAACCGGTAGATACTA
          CAGGCGTGCATCATGTTTCCTGAGCACGTTCCGAAACCTCGCGTCAATCAGCGGAAAGTG
          CCGATGAGGTGGGCCCATACCAGACGAACCTCGCAGTTCTCCGCCAATCAGTACGAGGCA
          CTGGAATGGTAGGCCTTTCCCAAATGATTCTCGCGGTTCTCGGACAGTCAGTTCGAGCCA
          ATGATATGAATCAGATGACTCGCTTTTTTAATCTAGAGTAATTTCGTTTGCGATTGGCTT
          CTTCTGTGAATCAGACGTCTCGCTACCTTAATCTGGAGTACTATCGTTTGCGACTGGCCC

          GGTACGTAAGCTATGCTGTGCGAGTAGGCCGCTGCCCAAACGGCATAAGTGCTCCCCGGG
          GATATGTAAGCTATGTCATGCGATTAGATCGCTGTCCAATCGATATAAGTGCTCCCCTGG
          ACTATGCAAGTTGTGTCATGCGAGTAGCTTACTGTCCCAACGAGATAAGTAGTGCTTTGG
          ATAAGATGAGATACGTCATTCGAGTAGATCACTGTCCAATTGAGATTAGTAGTGCCTTGG
          ACGAGGTGGACCTGACAGTATGAGTAGAGAGGAGCTCTGCCATACTGAACAAACTTCCTC
          GTTTAGTGAACTTGAAAACGTGAACAGGCAGGCCCTCGGCTGTATCGAGCTACCAGCCTG
          GCCTTTGGTATGGGCTAGCGTGGCCAGATAAGGAACAAGCGTTAGCACCAGGCGAGTTCG
          GCCTTTGTTATAGGGAAGCTGGGCCAGATAAGGAACAGGCGTCAGTACCTGGCGAGTTTC

          CTCTTTTAATACCCCCTCCCGCGCCGTACTTGCGCAGAACAGTTGAGCAAGGGGAGCACT
          CTCTTTTAATACCCCCTCCAGCGCCATACCTGCCCGGAACCGTTGGGCCACGGGAACACT
          TATTTTTTATCCGCCCTTCCGCGCCGTCCCTACGCTGACTAGTTAAGCAAAGGGAGCCTT
          GACTTTTAATCCACTCTTCTGCGCTGTGACAACGTAGAGAAGTCGAGCAAAGGGAGCATG
          TACTATTAATACTCCACGTGTAGTAGTGCCAGCGCCGATTGACTGGGTGAAAAGGGCGCT
          TACCATCAATACTTCATTGGTAGTCGTGTCAGTGTAGCCTGAATGTGTCAAAAGAGAATA
          CAAACACTATAGCTCCGCGTGAGCCGTGTAAGCTTGAATTTACTAAAACGAAAACCAGAA
          CAAATACTATAGCTCCGCGTGGGCTGTGCAAGCTTGAATTTGCTAAAATGAAAACCAGAA

          GGCAATGAGTGGGGTTTTCCAATCAGCACCACATTTAAGCTGCTCAAAGAGCTGCAAGGC
          GGCAACAAGCGGGGTCTTCCAATCAGCACCACACCTAAGCTGCTCTACGAGCTACCAGGG
          GACAACAGGTGGGTAGGACCAATCGCCACCACGTCCAAGTAAATCTACGAGCTGCCAGGG
          GGGATTAAGTGGGCAGGTCCAATCGGCAACAGGTCCGAGTCACACTACAGATTGACAGGG
          GGGGGTAAGGATGCTAATGTAATATGTACAATTGCTTCGTCAAGCCATCAGTTAGAGGGG
          GGACTTACGCGGCCCAACGTAATAAGCGTCGTTGTCCCGCCAAGTCGTCAGCTGTAGGGG
          AGCAGGGATCAAACATTTATGGATGTTGATGCCACGCCTTCGCGCATGTTGCCCTCAGTG
          AGCGCGGATTGAACATTTATGGATGTTGATGCCATCCCTTTGCGCATGTTGCTACCGGCG

          GCCCATATCCTTTGTTTGCTAATTTACAACTACTCAGCTCGTATGGAACGCGGAAGGAAA
          GCCAATATCGCCTATTTGCCAATTGACAACGATCTTGTTCATACCGAACGAGAAATGGAG
          GCTAATGTCCGTTGTTTGAAACTTCACATGCACTTAGCCTTCATGGGGCGCGAAACGTAG
          GCGATGGTGCAATGTTTGCGATTTTACACCCGTTTAAGCTTTGCGTGACGCGGAATCCAT
          GGGGTGAAAATGCTACCACCACTTATCCTATAGTTGAATTCTGAGAGGCGAAGGCGTCAG
          GAGGCGATAACACTTCCGCCGTTCATACTCTATTTGAATTCTCCGGGGCTCAGACTACAG
          AAGTCACCGACAAAAAAGCCAACAGTCTAATGTATCGCCATCCGAGGTGCTTGGTAGTCC
          AGGTCACCGACAAAAAAGCCTACAGCATGATGCATCGCCATCTGAGGTGAATGGTAGTCC

          GAGGGTACCTAGGATTCCCCACTTACGTAGTAACCCTTATTCGATCCACTGCAGAGTCCG
          GAGGGTCCCTAGGATTCCCTAATTACGTAGTACCTGACATTCGATCCACCGCACAGTCCA
          GGATGTGCCCGGGATGCCCCGTTCAGGTCGTACCCCGCGCTCGTTCCACCGCAAAGTCGG
          TGGGGCGCCAAGAATTCCCCGCCCATGAAGCAACCCTCGCCTGTTTCCCCGCACAATCAG
          GCAAACGACCAGGAGACGTACTTCGCACAGTCCGTGTTAAATATTCTCCTAAACAGCTTG
          GTGGGTGGGCAGGGGACGCTTATCGTATAGTACGGGTTAATTTCCTCCTTAAGCGGCTTG
          GATGTCTATAAAATCAGATCCTACGGGCAATAATTTATATTTGGAGCGACGCCTCATCCG
          AACGTCGATGAAATCAGATCCTACGGGCAGGCATTTACATCTGGAGCGACGCCTAATCCG

          CATTAACTGTGTCCACGGCTTTGTTTTGCTGGACGTTCTA
          CAATAAACGTGTCCACGGCTTTGACTCGCCGGACGTTTTA
          TATGACTTCCGACACTAGCCCTGGCTTACCAGAGGTTTGA
          TTTTATTTGCGCAACTAGCGCTTACTCACCAGAGATCCGA
          TCCTAGATGTATCCCCTTGAATAATTCATCGCCGGCTTGC
          TGCTAGATGTATCGTCACGCACCCTCCACTGTCGGCTTGA
          CTTAACTTGGGACTGTGTGTCAGCACCGTCGTAGACCAAT
          CTTCACCTGGGACTGTGTGTCGGTACCGCTGTAGATCTAT

