 8 1000
t1        AACAGAAAGATGTCCTCCCCTTGGATGACTGCGTAAATGGCGTCCCTCTGCCCCAGGTGA
t2        GACAGAAAGATGTCCCTTCCTTGGATGATGCAGTCAATGGCGTCCTTCTGCACTAGGTGA
t3        CGCCGAGGAATGCATTCGTCTAATAAGTTCGCGACTGTGCCGTGTCACAGCCCAATGGGA
t4        CCTGGACGGACGCTTGCTCTATATTAGGCCGCGCCCGCGATTTGTATAAGACCAGGACGA
t5        AGCGATAAGTTGTCTTCTTTCGGCCGGTTAATATTCATGATCCGATTACGTGCAGGATGT
t6        GACAATAAGATGTCCTTTTTTGGCTAGCTAATATGTATGGTTCAATTATGCGCAAGATGT
t7        CATTGCAAGACGCTTCTTCCACTGGACCCTACGCTGGTGATCGTCCCAAGTAAAGGCGGG
t8        CTTCGTCAGGCACCCTACGTGTTGGCTACTACGTTTGTCACAAATCCAAGAGAAGAACGG

          TTCAAGCTTAGAAACCGCGCCGTCGTTAGAAGAGCCACGTAACCAGAAGTGCTTGACACT
          TCAGAGCCTAACAACCGCAATATAGTCAGAAGAGCCACGTAACCAGGTGTTATTCACATC
          TTTGGGCTTGCTTGCGAATGGGTCGTGAAAGGGGCCATGCAGCCGGGTACCTTTTGTACT
          CTTCGGCACAGTCGTATAAGGGTAGTAGGATGAGCCCCGCAGGCTGGAGCGCTTCAGATT
          TTTGGGCACAGTCGGGATAGGCTCGCACGAGGTAGTCGACAGCTCGACGTGTTCGGGTCC
          CTCGGGCACAGATGAGTCACGATCGCATGAGGAAGCAGACAGCCCGACGTGCTCGGGTCC
          TTCTGTCGTTGCCTGCGTGGGGGAGTACTGCTCATAGGACGGGCACTTCTCGACAGAGTG
          CTCAATGCCTGCCGGTTCTGCACAGGACTGGGCATACGACCTATGTGGGTCTGCAGTGAC

          CTTCGTATGGACAGGCGTATAAGCTACGCACCAAGAAGCATCAAGTGTTTACGTTTACCA
          CTCCGTTTGGACAGGCGTACCTCCCACGTATTCTGAAGCATTAAGTGCTGATGGTTACGA
          TTCGACCTAGTTGATGATACTATTAGCGCTGGCTGGGTCAATGCATGTAGTCGTAAATGT
          TTTGACGTAGTTGGGGGATTCACGTGCGCTGGCCGAGTAGAAAAGGGCTGTGATATACGG
          ACAGGCACAGATGACTGTTAGTCACGCGCTTGCCACGAAAGAGAGTACTGGCATAAACAA
          GGAGGCCCAGATGGCCGTTAGTCACGCGCTTGCCACGATAGTTGGTATTGACATACATAG
          CATGGTGGAATCACCTGTTCCTGATGCTAAAATTAACATGTGTATGCCCAAAGCAGTATG
          CTTGGGTTCGTTGGCTAGTATTCACGTACAAGGAGAGCTATGATCTCTCAGCGTGGATGA

          CGCCAATCACACTTATTGGCCTGATTACGGACCAATACCCTGTAGACTTCGGCACCCCTT
          CGACAATTACTCCGACTGGCCTGGTTACGGGTCGATACTCTGTAAACTTCAGCAATCCTT
          CAACTACCGTACTTTCCGGCCGGGGCACGAGTCGGTATCTGTATCGTTCTTGCGACCTCT
          CCACCATTAGTCGTCCTGGCTCGATATCGGATCAGCATAACAATCACTCACACCCTCTGT
          AAGTTATTAATTTCACTGGTCTGATTTCAAGTCAAAACCCCCGTAGCCCTTACAATCAAC
          AAGTTATGAATCTTCCTGGCCTGTTTACGTGTGGGATCCTCCCTAGCTCTTACAATCAGA
          TGAATCTTGGCTATTTAAGCGACATAATCTTAGTCCTCTATCATCAATCTAGTACATCCC
          GGAAATCCGGCTATTTAAGTCGATTATTTGCCGGTCTTCTTTGTTGCTCCAGTGCACTCC

          GATATGACACATACCATTAAAAATTCCGTTGATGATTGGTATGTATAGAGGACTCAGACT
          AACATGAAACATCTCCTTAAAAATTCCGCTGATGAATGGTATGTATAGAGGACTCAGAAT
          GACGTGATGAACCCTGCGCACGGTCTTGATGCCGAACGGTACACCTGGCAAACCTTGCTT
          GAAATCGCGCACCCCGGGAACAATCGCGTTATTCATTGGAGTATAGTTTAACTCCAGCCC
          GTCAGAGCGAACCCCGGAGTCAGCCATAATACGGCTTGTCGAGCGAAATAAGCTTAGCTT
          GGTCAAGTGAGTCCTGGAGTTAGTCATGCCTGGGCTTGTAGAACGTAATAAGCTCAGCTT
          GTAATTTGGCGCTCTTTGAGCTGTCCTAACCGCAATTTCATTAGCGCAGATGTACCGCCA
          AGGGGTTGGTACTCTCAACGATGCTACGATGGGAGTCTAACTTATGGGGATGGTTATCGT

          GCTTCTGGTCCGCCTCAGAAGTGAATCTGGCCCACTGAGATATAAATATGTTTCAAACAC
          GCTTCTGGTCCGCCTCAGTAGCGAATCTGGCACACTAAGAGCTAAATGTATATCAAACAC
          ACATATGATCTGCATCAAAAACGACACCGGCCGAGTTAGTCCTGGCTGCCCCTTGAACAC
          CCTAAACCTTTGTAACGTAACTGAAAGTAGCCTACTTTGTGTTGATTGTGCACTGAACTC
          GTCGATGCTCAGGCCCGTAGATGGTAGTGCCACCTCCAGAGCCCGCTGCACGCTGCCGTA
          GCCTATACCCCACCTCGTAGATGATAGTGACACCTTCAAAGTCGGCTGTATGTTGTCGTG
          ACAGACATCTCGGTATTAAGCTGATGGTAGCAGACAGGACTCTTAGTGGGGCCGGATTAT
          ATGTGAATATTATGCTTCCGCAAAAAGCAGCACGGTGGGCTCTTAGCACGGGTGGATTTC

          AAAAAATCAAATTTCGCCGACTTGCGGTCTGAGTGTGGTCCTGAACTGTTAGCCACTTCT
          AATAAACCAAATCTCGTCGACATGCGATCTGATTGTGGTACTGAACTGCTAGCCACTTCT
          AACATAACAGGCGTCGGCGATTCACAGATCGTCCGAGGCTTGTATCTACCATTTACCCAC
          AATATGTTCGATTCCATAGGTTCCCGGCCAAGTTGTCGCGTGGGACGATGAGATGCTCTT
          CGTTCAGGTGGCGTCGCAAATCCACTGAGAGACCATCGGCCTGATTTTATAAGAACCTGC
          CGTTCAGGTGGCCTCGCAGATCTGCTGAGCGGCCATCGGTCAGATCTTCTCAAGACCCAC
          AACGTCGTACAATTTATAGGAGAGGAGGGAGATTTCGGTTCCTCAGCGATGGAGCTATCG
          CCCTGTGTGGAATCAGAAGAGGTATTGTAGGATACCGGCAGCCTAACATTAGTATTTTTG

          ATTTCTCACGACATAGACCAGGGGCAAGAGTTTCCTCACTTACGATGGCTTACACAGACC
          ACTTATCGTGGCATAATCCAGGAGCAATAGTTTCGTTACCTAAGATCGCTTATACAAACC
          GCTTCTAATACTGTAACGAAGGCCCCGCAGCTCTACAACATGCGTCAGCTTCATCAAATC
          CTCACTAATGCCTGACAGCGGGGCGGAGAATCTCATGGCAGAGAACTGTCTATTTAAATT
          GTCTTGGACTTCGTACGCTAGGAGCAAGTGCCCCATATAATTCGATGATCCATATAAATC
          GTCTTGGGTCTCGAGGGCTAGGGGCGTGTATCCCATATAACTTGACGATTCAAATAACTC
          GCTTTGGCCTTACAGCGATGGAACAGGGAGGCGAACATTAACGCTAAACGTTTGGCAAAT
          AATTCCGGTTCACCGCGCCGGAAGTGGTAGCGAAGTACTACAACTAAGCGCAGGTTTTAC

          CCAGGTCGCGAACAGCCCGCCGCTGAAAAGCTTAGAATATCACGACCCACAGGCTGCTTC
          CGGGGTCGTGAACAGTCCGCAGTTGAAAAGTTTGAAATACTACGACCCGCAGGCTGCATA
          TACTATAGCGAATCGCTCGGGGGTTACAAGGCTGAAGTATTCCGAAACAAAGGCTTTATT
          CTGCATTAGGAACGATCCGGGGGTGGCGCGGTTTACGAGTTACGAGCTAACGGCCCCACC
          TCCTGGCGTCGTCGCGTTAGAGGTGAGGATGTCAAAACGCTCCGGGGTAAGAGCTCTATT
          TTGTGGCGTCATCGCGATGGAGGTGCGGTGGTCAAAACGTTCTGTGGCAAGAACTTTATC
          CTTAAGACACTCTAACCTAGAGATGAATGACGAAAACGGTCTCACCACGGTTAATTAGCC
          CTTTAATGACCTCCGTCTAGAAATGCCCGGAGAAAACAGCCCGTTTATAATCAAACGAGT

          CGTCCCTGCTTGTAGGTACCCACAATAACTTGAAGGCAGCTAATAGCCACTCAATCATTC
          CGTCCTTGCTTATCGGTATCCACAATATCTTGAGGGCATCTGATAGCCGCTGAATCACTC
          TATCTCGGCAAACCAGTCTCTGGAATCACGTAAAGTTAGCGGGTAGTAGCTTGACGGCCT
          TACGCTTACATAGCGAAGTCTCTAGTACTTCGAGAGTAGACGGCAGTTGCCTACGAACCC
          TGCGCCTACCTCACAGTGTCCCCAATGACTGAGGAACGGCGAGTAGGTGCTTACGAATTT
          TGCCCCTATATCACAGTGTCCCCAATGACTGAGGGGCGGCGAGTAGGTCCTTACGAACTT
          CACCTGCCCGATAAGGTACTCACGTCGGTCTTGGAGCCCAGGCGAATAGAACCTGATCCA
          CAGCGACTAGATTGCTTGCACACCACGGCTCGAGATTGCGAAGCAATGGACTCGGTTTTA

          CCGGCCAAAGTAAGACCACCATTTGGACGAGATCTGAGGCCCTACAATACTGGGTTTCGT
          CCGGCCAAACCAAGACCAGAATCCGGATGAGATCAGAGGCCCCTCAGTCCTAGGTCTCGC
          CCGGATGCCATGGAACCTATAGTTGAGTTCGTAATGGGATCCTTTAGAGGTGGATCTAGG
          TCAGTTAACATTAGAACGGATTTCGTGTGTGCAACAAGGACCACATCTAAGCGATAGGGT
          CTAATTAACACGTGGTGAATCCCTGGGCGTTGCATGGGGGTATTTGACGTCTAGCCGGAT
          CTGACTAACGCGTGGTGAACCCTTGGGCGTAGAATGGGGGCATTCGGCGTTTAATCAGAT
          CCTGTTTGGCTCGAACTACATTTTAGCTAGGAATTATATCCTTTAGCACTTAGAATGCGA
          CTCGTAGGGTTAAGGACGGGTTCACGTTAACAATCCTGACATTTTAGCCACCGAGCGGGG

          AGTAAGCCTGCACTGTGCTAATCAAGCCACCTGATGAATCCCCGCCGGATAATCAAACTG
          ACTAAGCCTGCTTTGTGCTGATCAAGCCGCCTAACGAGTCCCCACCAGATAACCACCCCG
          TTCACGCCTGACCCGCCTTGTCAGAGCTATGCAACGGATTCCTTTCGATAGATTACCCTG
          GTTACTTCCGTCTCGCTCTAATTAACCCATCCAACGACTTCCTCTCAACTGGCCATCCTA
          GCCTGTCCTGCCTTACATCGGTTAACCCCCATAACGAATGCCTCCCCAAGGGCTCCTTCG
          GCCCATCCAGTCTGATTCTGGTCAACCCTCATAACGAATGCCTCCCCACGGGCTCCTTCG
          GCAGGGCGGGCAGTATGATGGCCAGTTTTTGCCTACGACCCTAACCTCTGAGCGAGTCAC
          ACATGTGAAGTATGAAGGTGCACAACCATTGATACGGATGCTAGCCGATAACTTAATCCT

          CTGTTAAGGCCTGCGATCCTATACCGCCGCTGCGCTTGAATCTTCACAAACTCAGCGGAC
          TTGTTACGGTTTGCGATTTTAAACCGCCGCTGCGCTTTAATCCCCATAGACTTAGCGTGC
          CTACGATGGCCCCTGTCCTAGACACGTCGGAGCGATTGAGTATCAAGAGTATATCCCTGA
          CTATTGCAACTTAGGACTTCGAGATGTCATAGGACATGAATATGAATAGTCTATATGCGA
          CAAATAAGGCTCGGGCACTTTTACAGCCACGGCGCTTTAATGTAAACAGTTGCGGCTAAC
          CCGTCAGAGCTCGGGCAATTCTACAGCCACGGCGCTTTAGTGCAAGTAGTTGCGGCTAGA
          AGTCTGGGTCCGAAGTCCGGCCTGGGCTTCAGAAACGAAGCTTGGGCATAACACTTCAGA
          CACCCAGGTTCCAAAAACGGCCCGGGGTATAGCATCTAGCTTCCAAAACTACGATTATGG

          ACCCGACTTTCGTCGCTTGGCCGGGTGCTTACCAAATACACTGAAGGAGAGTTTGATGAG
          GCTCGACTTTCGTCCCTCAGCCAGGTATCCCCCAAATACGCAGTAAAAGAATTTGATGAG
          GCTTGGCTCCCATTATTCAGCAGTGTCCTACGCGAATGCTCCATGAGTGAATTTAGTGAT
          TACAGATGTCCACCGCTCGACAGAGGGACTGGTAAATCCTCCAAGGCTGCAACTGATGAC
          GCACGTCTTGAACCGCTCAGGCGAGGATCACTCGGACACTACACGGGTGCAATGGGCCGT
          GCACGTCTTGAACAGTTCAGGTGAAGATCACCCGGATACTTCATGGGCGTAACGGGATGT
          GTTTATTGTCATACCCAGGGTTATATAATTACCTTGACTCCAGGGGGCATAGACTACCGC
          GCTTTATTTGAAACCCTCGGTAGCGTCTCGTCTCGTGCTCAATCGGACATCGGCTAGCAC

          CCTGAGCTTATGCGTCTCTCAGAGCTAAACTATTCCAACCTCCCATGCGCCACTGACGTC
          CCTAAACCCATGCGTCTCTCAGAGCTGAACTATGTCAACCTTGCGTGTGTCACTGACGTT
          CGTTAATTCAAGCACAAATCAGAGTTGGACTCTTCAAACCTTGGAACCGATGCTGACAAT
          CGGCAACGAACATGCATGTCGGAACTGAATTGTTCACACTGCGGGCTGGCCTCCGGTAGT
          TGAGCTTTCAGACGCATCTCAGGGCGTGTTCAGCCTTGTTTAATACCTGGCCCCCGAGGT
          CGAGTTCTCAGACGCTTCCCAATGTGGGTCTGGTCTTGTCTGGTACCTGGCTCCTGAGGT
          TGAGAACATAACCGAAGCGCAAGACACCTATATCCTAGTTAGAGCAATTAGACGAGGGAC
          CCTGAAAACATGACCGTCGCGGAATTTGCCCCACGAAGGGGGGGAACAGGCACTAGGGCC

          CACAAAAAACAGTATAGTGGATACTACTTGAGGGAAGGAGGAGAAGTTAGTCCAGGCAAT
          CTTAATAAACGGTATAGTGGATTCCACTTGAAGGAAAGAGGGGAGGTCAGTCCAGGTAAT
          GTTAATCAATGGTATAATGGAGCTACCTTGAATGCAAGGGGGGTAGCTAGCCTAGGTAAT
          GCGAATGCGCTCAATAGTGTTTACTCTGAGATGGTAAGAGGGGAAGCTTATCGAGATGAC
          GCCGTGGAGCGGTGAAGTGGCCGAATTTATAAAATAGACCGGGAAGTTATTCTTATCAAA
          GCCGGTGAGCGGTTAAGTGGACGAAGCTATAAAATAGGCCGGGAAGCCATTTTTATCAAA
          AACCCTAAGTAACAACCTTCAGTCGTTCCACGCACACTTCAGAAAGTTGTTATAGACACA
          ACCCTTCACAGACGATTCTTGTTTGCACACCACACCCTTTGGAACGCCGAAACGGGTAAA

          TTCGCTCCTATATCGTCGCGAGCGTCTACCTACTGAGCGG
          TACCCTCTTATACCCCCGCGAGTGTCTACCTACCAAGCGT
          TCGACGCTGCTGATGTCGCAAGCGCCTACCTAGGACGCAT
          CTCACTAATCGATCGATGCAAGCACCTAGTCGGCACGCGT
          CACCCTCTCCATTTGTCGCAAGTGCCGCTTGGGCATGCTT
          CATCCGCTCCGTTAGCCGCGAGCGCCAACTGGGCATGTGT
          CATAAATCATGATAATCGTCCGTGATCACCGGGGCAGTAT
          CGCATATTATCGTCCCTCCCGGGGAACCCGCGAGCAGCGC

