 8 1000
t1        CGGAGCACTGTCACGATAAATTGGTATACACGCTCCAATATTCTGTGACTTATGTTCTCT
t2        TTGAGTGAAGTCACGGGAAGGTGGTTTCCGGGTGCGAATCTCCTGTGACCCCTGTTCTCG
t3        TGGCATGGCGCTGTCTTATATTAGCTAAAGCTTGCCACCTCGGGCCGACGTTCCACTTTA
t4        CAACGATGGATTACGACACTTTGAGCGTAAGACTATGCTAAATGCACCCCTTATTTACGA
t5        CAGCGAGCGGTTGAGATGGTTGCGTCCCTGCATCCTGCAGCCATCCGCCCACCTCGTGCC
t6        CGAAGGAGAGTTTAAACGAGTCCCTCCTAGTGTGGAATAGCACGTTCCACGATTCCCTTG
t7        AACTAGATACCCATTACACATCCGGCACCGTGACGGGTTCCGAACTGGTCCTCCTTCGAA
t8        TAGTACGGCTCCAGAAGGCATTTTCCGCGTAGCCCGGCAGTTTACCTTGCGAATTTCCAC

          ATACAAGCTGCCGAGCGCAAACGCGCGTGTGGTATGGTCCAGCTACCTCCAGTAATGGAT
          TCGCACACTGGCGTCAACGTCTGCGCGTATTGTTTGGGTTGGCTACAACCTGGTCGTGAT
          ACAAATTATGTGGTTGAAACCAACGCGTGGTGAGCCAACGTCCCGTATCCTGGAGAAGAA
          AAACGCTCTGGGGCACAACAGGCGGGGCACCGTATGATTATCACTAGGCCCACTTGCTTT
          CGACGAAACGGATCCTGTGCTGATGAGTCAGCAGCAAATATGCTATCGGTCAGAGGGTGC
          GCCGATCATTAAACCTAAATGAGCGTGAGATGTGTGAACGTTTCGGAAACTGACTGGCGC
          TCAGGTCGTGAAAATCAGGTAAAGTTGAACAGTGTGGCCCTTCCCCGAATTACCCGGAAG
          CTGGGTGTAAGGGCGAATGTTGACGTAGATTCTGCTACCGTGCCTGGGATACGGTGAAGG

          CGTTCTGACGAGCTTGACACTTCGACAAGTCACCCGGCAGGCTAGTGTATCAGTTGTGCT
          CGTATTCGCGCGACTAACGCTTTAATAAATTGGCTTGTGGGCTCATATATGGGTTGTGCG
          CTGTCCACAACGCCAAGTGACCCGACAAGTTACGAAGCTCTTTAGCAAGCGAGTTGGAGA
          ATCCCGTCCGACCATGTTATCCGGATAGGTTTCAATGCCGGCTAGTAAATAATACAAAAT
          TTTCTTAACATGGCAGACGAACCAGTAGGCGTAATGGCTCTTTAAAGTAGCGGACAAGGT
          ATTATTACGGGGAATCACGACCAAGCAAGTAAATCAATTGGTGCGTATGCACGCGTTGGT
          CATGTACAGGCAATCAATGAACCGGGAGCAAGTAAGACCGGCAGGGGATCTCCTTGTCGG
          CTTTTCACTTTATATTACATAGTTGAAGGTTACCCACTCAGCATAATGTCATCCAACAGT

          CGCGACTAATAATCATACTCTCACAGAGCAGGTTGTTCAGGACATTACACATTATTAAAA
          TTGGAAAGGTAATGATACACTCACAGTTCGACCTGGTTGATGTAGTACAGAGCATTAATA
          TGTTATCGATCAACGTTCAACGCGTAGCGTCGTTGATTAAATGATTATGGTCCAATCGCG
          TGCGGAGCTCTGTGGCTCGTTCGGAGGGTGCGCTGCGTAAGTTTCTTCGGATTGTTGACC
          GGCAATGCGATGCTGCGAGTGAAATGGGCCGGGAACTTGTATAATCGCGGTTTGCTGGTA
          TATTCTGAGTCTCAATCTCTTCGCCGCGAGCGGCTGGTCAATGAAGGTTCTTTATGGGGG
          GACCGCTATCTATCGTACAACCGCGGATTGGGTCTACTGGACAATAGGGCCCCACACAGC
          AATGCTGGGCTTTAGTACAACCCTCTAATATGCCGCCTTTGCTGAAAAGAGGCCGTGACG

          GAAATTTAACGTATGGTCAACCCCTCACACGTCCACTCTCCACTGACTTTACCGGCTATC
          AAGACCTAAACTTGCGCGGTTTTCCTACAACTCTTCCCCGCCTAGGCTTAGTGATCTGCT
          GTGATATTCATGCGCGATAGTCCCTTAAGTGATTTCTTTTGTCTGGTACTGGTCCCAAAT
          GTGCCGTTACCCTGGCACATCGCATCTGGTTACGTTCCTTAATTGGACATGCTACCAAGA
          ACGGCTAAACCCAGCGCGACGTTTGCAAGGGCTCTCCGCGACGCGACTATAGCACCTAAC
          GCACCGTTACCCAGGAAGACCTCCACATCTCCCCCCGGACTCCCGGCCCCCGTGGTTCCG
          GGGCGCCGGCTCAAGCAACTGAACACACGGATACCTCTACGTTAGAGTGTATTGTTTTTT
          ATGGTAACCGGTTGACTACTCCCGTGGCCTACGATTGCGTATTTAAATGCTATGCACACA

          CAATGCCCGGGACTTTGCTAGCCGTAACGGCGCTCCAAATATTGGGGGATCGGTACTTAT
          CAGCGACCGAGACTTCGTTACTCCCTATTGCGCTCAACATTCCGGGGGACTGACGGGTAT
          ATAACGTTAGATTTCCGCTTCTCCGCCTCGCAGTCAAGTCTATTAAGGAACGAAGGCCAT
          AGACAGTTTGCTCGTTGCAAAGGTGCCCAAAATTAAAAGATGTTCGGGGCTGGAGAGTAT
          ACATTGACGCCCCGTTGCATGCCACCCCTGTTCGTGTGGACATAGGAGAACGGCGTTAGT
          TCTTCATAGGCTCTTTGTCCCACTTCCAGGCAGTAAAGCGTGTCAGCGCATCGTACCTAT
          TCACCAGTACCTCGTAAACAGACATTTCCGTCGTCGCGTAGGTCAGGGTAAGTCGCTGCA
          GTGCGCCCAGTGACCCAAGACTCCACCAGACTCGGAATCACGTCCATGAGAACCTATAAC

          CCCGGGAGTCACATTAGACACTCGCAATAAAATCAGGAAAGCTATGTATCTGTAGAAGGT
          TTTGGGGGTTAAATATAAGACCTTTAACAAGGTCAGCGAGGCCAATTATCAGAAGGAGAA
          CTCGACGTCCAGGCATGGTATATCATAGAGGTTCAGTAGAGGCGCGTCTTCACCAGGAGT
          CCGAGAGACACCTTATTGCACGTTCTACTTGACAAGTAAGGGCACATATTCACTAACAGT
          ACTGCAATCGAAGAGCAAGTGTTGTAGATCAATTAGCTAGTACATAAATGCTTCTAAGAT
          CTGGGTACCCGGCCATGAGACCCTACCATTGTCTGGAGGGGACTTACAGTCTTGTGCGGC
          GCCGTGGCAATGATATCGTCAGTCCGACAAGCCAGCTGGAAGTATTGATACCTCACGGTT
          CTTAACACCCTAACACTTAATGTTCTGTATTTACACAGAGGACGTGTACGCATACTGCAT

          TTAGACAGTGCGCATTGTTTAACGACCAACGAGCTCTCGGAACTGGACGATCCTGGCCCC
          ACGGACAGTGCGAAGTATCCATCCAGCAGAGAGCCACACAAATCCAATGATAAAGGTTAT
          GCAGATTATGCAATTAGATTACCTATCGATAGAAACACCAAGCTTCTTGATTCAGGTCCC
          ATGGGTGCCGTAGAGTGGCCAAAAACTACCCGCTAACTTGATCCGCCTCGTTAAAGCTCT
          GAAACTGGTACTAACTACTTATCAAATGCTAAATATCAATAGGCGTCCAAGCAGTGCACC
          TTATAACCTATATAATGTTCTATGACTAACGAGGACGAAGAAGTGGCAAACGAGGATTCG
          ACAGATTGCCTGAAACGTACATTGATTGCTAAGAGGATTTTATGGCCTGGTGCTAGGCCC
          ATAGACGGCAAAAAGAGGCGAGTAGTTGACGACATACCTGGAGCGTCCCAGGCTCGATCT

          TTTACCCATAAGGCTGTCTGCGCGCGTTATAAAGCCATGTACCGCACTCCGCCACAGCCA
          TCCACTCATAAAGCTGCCCATGCGTATCCGAGAATCAATTACCGCATCCCTTGCCAGCTC
          CCCAGCCATGACGCAAACCGAGTACATGACGGTCTTGGGCGCCATACCTTCCGAGTATTG
          TTGAGTCATGTGGAAAACTGGCGACGCAGCAGTTCCGAACGTCGAGTCTACCGACAGCCT
          CTTAAATAAGGGACGAACCCTCTGTTTTACAGATCCAAGGTCCCTATTTTCGGGCCTTCG
          TTCTACCTTAAGGCATAATATTAGTACTCCTGATGTACAGCCTGCGCCGGCTGTTATCAA
          TTCAGCCGTCCAGTAGTCGATAAGCGCCGTGAGCTCTCCGGCAAATTCCCAAGTAGTCCA
          AGTGGTTCTACGGTAGAACCCACGCGTTAGGGACCCACATGCAGTGGTTCCGAGTAACTG

          ATATGCACTGCTGTTGATACTGGTCCGCATGATTGCACACATACGTCGGTAAAGAGAACT
          CGCGGTACTGACGTTAATATCGGTTTATAAACTGTGACACCTATTCTGATGCGGACTACT
          AGCTGAAGAGTCCTTCATCATAATACGTACGTTCGTACTCCTATACTGCCAGGGATAAAT
          AGCCATACCCCGACCGAGCTCACTCCTCGTTCTCGGATAATTGTGATTCCCGAGTTCGGC
          GACTAAATCACCGCCGGAGACGAATTGCATCCCCGTGTACATATGTTAGGAAACCTCGTC
          GGACACCGTCCCGATGATATCAGATCCAAATCATGAACATGTGCAATGTCTAGGCTACAT
          GTCGGCATTACCGCTAGTACCGCCTAGATTGCTCGTCTTAGGTAGGCGTTGGCGGGGCGA
          GACTAAACCGACGTCGTTTACTCGTTCCTCACCGAACCATCGACGCTGTTCGGGCTAAAT

          TCTAACTTGCCTTCATAGGCTAGTAATGATATCGTCGGGAACATGGAGAATCCTCTATAC
          TGTGGCTTGCTATCGCGGGTTGAAAATGGCATTAACGGGATCCTGGACTACCTTCAAAAC
          AATGATTTGCATTTGCGGGTCGCCTAGGATTACATGCAGCGTGAAGTCTACTTCCAAAAA
          ACCTATCCTTCCCCCTATATGGGTCTTCGCTTAACTGTATACTTGTTTCGGCCCCGAAGG
          CCCCCTCTGTCAACAAAGGCTAGTGATGATTTTTCTAAATGGCTTTCCGGACCCCGATAC
          CGCTATTACTAGCCAGCCGCGACTTCCGGCGTTATCTAACTTAGTCTTGAGCTCCCAGCT
          CCTAACCCTACGTACTAGGCCTAGTCCTGTACAACTCGACATAGGCTCACTATTACTTAG
          TACGACGGGGACTGTCTCAACTGCAGCAGTTTGATTACGCGACAAAAAGGCCGATAAAGT

          GTCCCGCATGGGTTGACCATTCCTGATAGTATCCGCGCAGACTCGCGTCGAAGAGCACGG
          GCCTATCATGCATTGACTAATTCCGACGGTCAATGCTTGGCCCAGGTCTGGAGGGCACAC
          GTGTTTCGTGAGAAGGTAACTAAAGGTGTTCCAAGCCGCGTTGCCACTCTGGCCGGGAGT
          GTATGCCGCGCACCGATCTAGTTTGACTATTAACACCGAACCAGTGAGCGCGACGAGGGA
          ACGTTTCGTTAGAAAATATGCACCGAAAATGTACATTGCGCCACTAGTAACGATGGACGT
          CGAAAAAGGGACTAGAGAGACCCGTAGAATGTACGTTGCCTCCCGGTTTCGAACGTCCGT
          ATGATTTGCATGTGAATCGGCGTGCGCATTTCACGATGATACTTGAAGCAAACAGGGCGT
          AAGTGATGCGGCTTTTACGTGACACAGAGTTTATGCAGCGCACGGTATCGAACCGATTGC

          CACTTCGCCTGTTAACGAGGAAGATAGAAGTAATCAGGAGGATTCACTCTAAACTGAATG
          CCTTATACCCGTCAACGGGGACCTTTAAGATAACTAGCAAGTCTCGCTATAAACTGAGTG
          CGGACTTTTGAGAACTGAGATCGGTCGACAAACAAAGCAGGGAGCACCGTAACTTGGAGG
          GAATCATATTGCCGTAAGGGATACACTACGGTATTTGAGTGGGTCACTCTTAACTGTCAT
          CGGCTTAACAGTGGTCGAGGATTGATGATTAAGGCCGAGAGGATCACCCTAATTACGGGA
          CGCCTCGTCGCAGATCCGATTTGGCCAAAATGACTCTTGGAACTTCCCTACGATCGAATA
          CCCTCCCTGGAAGTTCCGGGACGATCACAGTCATACAACTGAGCTATCGGTTGTCAAATC
          TTACTTGTAAACGAGCCACGAGGTACCAGGGCATCCGGGACTATTACCTTGGGTTGAGGG

          GTCTTCCAGGCTGGCGGTCATTGGCACTAGTCGATCAGGTGCTACTTGCGCGTACTGAAA
          GTTCCCTGGACTTATGACCATTGGCATTAGACATTGCGACGCAATTTTAATGCCCCGAGA
          ACTTCACGATTTCCCGACTAAGGTGTTCAATCAACAGATGGATGCCAATGTGTATGGCAT
          AGTTCGTGGTCCTCTAACGAGGGCAAAACAACCTCGTGTTTAAGATGGAGCGATCGGGAG
          GCTACATGAGAACCTGTCACTCTAGGCACAGTGCTTTATTGAGAAGTTCATACGTCAAAG
          AGCACTTGAAGCGGTTCTAGTTAAGACCCAAGACGTCAAGGAAATCAATGCATACATGAA
          TATCGACAAAACCCTGATTAGCGCCGTGTCAAGTGAGGCTATAAACGACACGTGGCGCCA
          ACCCGATCTAGTTCCGGACAGCGTGGATCCTCTTTCTGATGCCGCCCATGCACAGAGACT

          CCCGTCGGTCCGATTGCATCGCCTATACGCTTATAAGTCGGCCGTGAGGGACGCTTCGAT
          GGCGGAGGGTTGATTTTATCGTCCATATACTAACTAAGTGTACGTACAGGAATTCTCGAT
          GTAGTCGGCTTGGCCCTAACGCCTAGCTGTTTACAAAAGTCGCGTTATTGCTTTTCCAGC
          GCAACCAGAACACTTGCGCCCGAAACGTATCCACCTACTTCTCTCGAGCGCCCCCTTATC
          GCGGTCGGCCTGTTTGTAACGGCCTTGTGCACATCTTTCTTGTATCAAGCCCAAGCCAAC
          CATAGTGCCCCGACCGGAACGGGTGAGACCCGGCAGAACTTGTACGGGAGTCGGTCTAGT
          GGGATCGGACCCTAAGAAAAGGACACAAATAGACGAAATCACGTTACAGGTAATTCCAGT
          ACTATAAGGTAGATGGTGGTAACCGACTGACGATACCAGCTGTACAGTCGCCGTTTAAAA

          GACACCACGCCTTTCCGCGAGTGCTGCCTGAGCGGCTGAGTCCGTCATTTAAGACGTATG
          AGTATCGGACGTCTACATGGGCGTAGCCTCCATGGAAAGGCGTGTTAATTCTTATGTATA
          AGTACCGCGTATGTAGGTGGGTTTAGCCCGTGTGGTCCAGAGTTTAAAGTGGGAAGCACG
          AAAACCGTAAATACACGTGGAAGTTGTCCATAAACCTCCGGGTGGTCAGTAGGACGGTTT
          AGAGCAAAACGTCTTCGCGCATTTTAGCAGCCGGAGCTATGACATAGAGTCCCGTTTAAC
          CACGCCGCATGCGAAGCTGCGCCATGTATCTGAGGCGCGGTGCAACAGGGGAGACGCATA
          CAGACCACGAAGTCACCCAGATCACGACTCAGCCCCCGAGAGTGTGTCCTGAGACTTATG
          AGTGTCTTGATCACAGACTGTTAACAGTTTGATGTGCCCGTCCAGCAACACTAGTGTATA

          TCGACGTTGATATTCGCGACGTCCTTAAGAGAAACGAGGA
          CCCATATTGATCTTGTTAATCTTCCAAAGCGCTAAGGGCC
          TCGATCTGAGGATCGAGACTTATGGTCACCGATGGTTGTT
          TATAATACTTCCTCACCTGCCATCCCCTGAAACTAAAACC
          AAACACGATGCGTAGCCGGTGGCCGAGAGCGATCGCTGTG
          TTTAATTGATGTCCGATGGTCCATCACATTAAACACCGCT
          ACAGCTTGAAGTTCCTTAGCTTTTTTAAACGGCCACTGCT
          TTCGGCCCACGCTTTCCCAGATTTTAAAGACATCAACTTA

