 8 1000
t1        TCGACATTCTTAAAAGCCCAGCTGTCTGGTTTGCTAACGACCTGGTGCGAGGTTTGGGCC
t2        TCAACTTTCTTAAAAGCCCAGCTGTCTGGATTGCTAACGACCTGGTGCGAGGTTTGGGCC
t3        AAAATTCGCGTATAGGCTCTGTTGTGAGGCCTACCGACAACCGCGTGAGTAATCCCAGCC
t4        TACTTGCTATCAAAGGTCCCGACTATGGGCTTGCTGCTAACTTGACGACGTGCCGGACGG
t5        TGCCCGCCCGCGAAACGACTATTCCCGGGATTAATGGTGATTCGGCGCGATGACGGACTT
t6        TATAAGCCCGCGAGACGACTATTCCCGAGATTAATGGTGATGCGGCACGATAATGGACCT
t7        TTTTCGCTCTAAGGTGGGCGAACGAGGAGGGCAGCTGCGAAGCGATGCTCAGTATTGGTA
t8        ATTCCGTCCGAAGGCAGTTCAATAGAGGAGACAGCCATGTGGTAGTTTCTTCTGCCATTA

          GCGGACCTTGGACTCCACCATTAATGAAGATGTAATGCAGCGAGAAAGACCCGGGTTCAA
          GCGGACCTTGGACTCCACCATTAATGAAGATGTAATGCAGCGAGAAAGACCCGGGCTCAA
          TCGGGCCCCGAATCAGTGCACAGAGGTGATTGAATGGCTCCGATGGTTTCATGGATTTCA
          TATAAGTTAGAGCTATCTTAATTACGTGGGCGCCCTGCCCCGGGGACCACCGAAAAGTCG
          TACAATTTCAAATTAGATTACCAGCGTCGTTGCGTTTCTCCAGAGAACAAAGAGGTCCAA
          TATGATATCAAATTAGACTACGAGCGTGGTCGTGTTTCCCCAAAGAACAAAAAGATTCAA
          AAGGATCCAGCGTCGCCTCGCACAAGCGCGTAGGCTCATTAGAATATCTCAACGGATAAC
          TGGGGTCAAACATCCCTCCCTGGAAGTAAGTAGCTTCCCTGGGGTGGTAGATAAAGTTAT

          CTAAGAAGGATCTGCAAACCAGCCCGCCTTTTGCCTTGCAGTGAAGTTAAATCCTGGAGC
          TTAAGAAGGATCTGCAAACCAGCCCGCCTTTTGCCCTGCAGTGAAGTTAAATCCTGGAGC
          CTCGGAATGATATCTGCAGTAACACGCCCCACACTTAGCAGTGAGAGTAGCCTCTAGGGA
          CATGGACTGATTCCTGCAATAGATTACTTATCGGACCACAGTGCTGGTAGTCTGCAGGGG
          CCGGCGATGACACTCTGTCAAGCTTATCCTGCGTATTGTGCTGAACGTTGGTTACTAGAC
          CCGGCGCTAACATTCTGGATAGCCTATTTTGTGTCTTGCACCGAATGTCGTTTATTAGAC
          CCAGAGGTGGGGCATGTGGCAGCTATTTTCGTGGACCGAGCTCGTGTGTGTCTCGTACCT
          CAGGAGCCAGTACATGCGATGGCTTGTCACACGTAAAGCATGTGCAAACGTCCCGTGCAT

          TGGTGGTGGATTCGACTTCTACCCCTTTCTGCAAACGTCACACTGTTATTGGTCAAAAAC
          TGGTGGTGGATTCGACTCCTACCCCTTTCTGCAAACGTCACACTGTAATTGGTCAAAAAC
          ACGCTGCGGGGGAGATATTAACCTGTCCATGTTAACTTTATCTCACTTCGTATAGGGCTC
          CCATCGTGGGAGTAAACTTCAGTGCGACCAGAAAGTTTTCTCTTATTAAAATCCGAGTCC
          CCATTGCGGAAGTGACCTTTATTGCCCTCAGCTGCTGGTCCCCCGCCTCATGTGGGGGAG
          CCATTGCAGTAGTGACCTTCTGCGCCACCAGCCGCTGGTCCGCCGCTTCAAGTGAGGAAG
          TCTACATGATAGGGGCAATAGAAACTTTCTGTAAGTAAACAGAGGGGTCAGCCAAAGACG
          TCCCCAGGCAAGCTGCCTCGGCCATCTCTAGTTTATACGTATGAGGGTTGTTCAAGACCC

          GGACTGTGACTAATGTTATTACAGAATAACACCTACGATACGGTTGCCCGGTGTAATAAA
          GGACCCTGACTAATGTTATTACAGAATAACACCTACGATACGGTTGCCCGGTGTAATAAA
          TATTTGTGAAGAGTGTTCCCACAAGATGAACCCCATGATATGGTAGCTCGAAGCGATAGA
          CTCTCATAGCGTACGAACTTTCGTGATAAGATCCGTTCCACGGTGGCTTGGAGCGTTAGT
          CGCCAGCAATGAATGCCGTTATCAGGTGGCATTAAGACCAAAGGAGCACGATGCCACAGG
          CGTCAGCGACGGATCTCGTTATAAAGTGGCGTTTGAACCAGAGGAGCACGAAGCAACAAG
          ACGATCTCCAGGACAGCAGTGTAAACGTATACCTCTGGTATACTGACCAAGCAGGGCCTG
          GAGGTCTCCTGGCTAACAAGCTATACCGAAACAACTGACATCGTTGGCCACCGGGGCTTG

          GGCCCCATGATTGTAATAATATTCAGGGACCTCTTATACCTGGCATAAGATCATACTCAT
          GGCCCCATGATTGTAATAATATTCAGGGACCTCTTATACCTGGCATAAGATCCTACTCAT
          GGGCTCTTCCGAGTAGTAACACCAGGGGAACTCTTTACGACGGGTTGAAGCGACAACCAC
          GAACACCTACCAGCAGTGGCACCTGGGATTACAACAAAGTAGAACGGAGAAGGGAGGACC
          CGACGCTCATGACCACTGGTGTCTGAGGGTGGCCCATAGTTAGGTTGATAAGATACTTCC
          GAACGCTCACGACCGCTGGTGTCTAAGGGTAGCCCATTGTTAGGTCGATAAGGTACCCTC
          GGCCTTGCAAGCGATCTGGAGCCTGGAGAGGTTACGCCAGCGAGTCGATAGGACGCTCCT
          GTCACACCAAAAAACCAGGAACCTGGGCACCCTATATTGATACATCGACAGGAGAACCCT

          GAGACTCCTGCGAGTTCCGCGACGTAGTGGAAGAGAGGAAGCGTCTCCGTCCGGCCTGGG
          GAGACTCCTGCGAGTTCCGCGACGTAGTGAAAGAGAGGAAGCGTCACCGTCCGGCCTGGG
          GATGTCTTCGCGTATTCCGTGCCTTAGGGATAGGAGGATCAGGTTCCTAAAGTGCACTGG
          GAATCCGTACCAAATTACGTGATGTCGGGGTAGGAGATGAATCTGTTCAGGGGGCTCTGG
          AAAATGATAGTCTGTCGAACGTAATCACGATAATGATAAAACGCTTCAGGGAGCGAAGGA
          GAAACGCTAGACTGTTAAACGCGATCACGATAACGATAAAACGCTTTAGATAGCGAAGAA
          GCGACGCACTATTGCTTCGAACTGACCCTGTGGCGCGTAAATTCTCGCACAGGGCAATGT
          CCGACCCGTCTTTACTTTGGATTGACCCTGAGGCGCGCCAGCGTCTGCGTGCAGAATCTT

          GTAGGTCGGATGAACTTGTAAGCAGCGTCTTCGCGAAGTGTTAAACGTTGGACCCTGAAG
          GTAGGTCGGATGAACTTGTAAGCAGCCTCTTCGCGAAGTGTTAAACGTTGGACCCTGAAG
          GCAGGGCGGGCACGCCCGCTAGCGGCTCTTCCAAAAGATACTATACGTTAGATCTTGAGG
          GTCAACTCGACCTCCCCAGAAGCGGTTTAGTTCCGAAACAACAGACTACCGGTTCTGAGG
          GTGGGTCAGGTTTGCTCGCAGACTCTTTTCTTATAACATCTTAGATGAAGAGTTATTCAC
          GTGAGTCGGGCATGCTCGTCGACCGTATCCCTATAAGGTCTTAGATGGAGCGTTCTTGAC
          CTGGTTTCAGCAAGGTGTGACGCAGCCTATGTACGGGAAATTCAATATAAACTGCTCCCT
          GTGGGCTGGGCAAGGCTTGAGGTAGTCTGTGCTCGGAGAACCACCGTCCAATCCTTCTTC

          GTCGTAAGCCTCCCATAATAGATTGCCGGAACCAGTTCGTTTGCACATCATGTGAGCTGT
          GTCGTAAGCCTCTCATAATAGATTGCCGGGACCAGTCCGTTTGCATATCAAGTGAGCTGT
          GTGTCAGCTCCCTCACGACAAGCTGATACGATCTAAACCGTACTACGTTCTGCGCATGGT
          TCTTCTATCTATCGGCTTTAGACCGGCAGTAGTAGCCTCCAAATTACCCTTGGGAGCTGC
          CCTCCGCTTCTTCGTCCAACAAATATCTAGAGCCCACCAGTCTAAGACTTTGACAGAGGC
          CTTCCGCTTCTTCATCTAACAAATACCGAGAGCCGACCGGTCTCAGATTTTGACAGAGGC
          CTTGCAAGTGAACCATTCGCCATCGGGTTGGAGCCATACATGGAACAGATCCAACAACAT
          CAAGCGATCATACCCTCCTCTGTTGGTTAAGAGACATTCCAAGAACAAGCCCGGTAACAT

          TGAAAACGAGCTACATATTGGCGGTGATTGCCTGTTTCGTAAAGACCGTCGGGCCACCTC
          TGAAAACGAGCTACATATTGGCGGTGATCGTCTGTTTCGAAAAGACCGTCGGGCCACCTC
          TGAATGTGAGACCTGCAATGGCTGCGATATGATTTTCAACATAGGAAATTAAGTCTGCAT
          TGAATACTAGGCTCCTACCAGTGCTGAGCAAATTCTCGGTGGGTTGGATTATCTCCTTAC
          AGTGTTCGCTGTCTTCATCGACGTAGGATTTTTTTCAGGTACGTAGGAATTGGTCTGCAT
          AGAGTTCGCCGTCTCCATTGATGTGGGATTTTTTTTTGGTACGTAGGGATTGGTCTGCAT
          TGCAGCTCGAACGTCCAATGATCAACATTAATCTTCCAGGTGCAGAGACGTAGCCCCTTG
          CGTCAGCGGGGTGTCTAGCGACCAAGACTGACCTTTCTGTTGAAGCGACAAAAACTATTC

          CCTAGGCCACTATGTCTTATGACTGTGTTTAAGAGAATAGCAATGCTGCCTTCACCGTAT
          CCTAGGCCACTATGTCTTATGACTGTGTTTAAGAGAATAGCAATGCTGCCCTCACCGTAT
          ACTCTCCCGTCAAGAATCATGCGTGAACTAAGTAGATCGATTGCTCCGAGCCGACGACAT
          CATGTACTTCTACCTACTTTGCGAGCCCTCCGGCGGCCCAGTGTTTTATCTCGACATAAT
          CACGAACAAACAGCAAAGATAATCATCCCTAGGTTTCCGGTTGTTGTGCTACACCTTTCC
          CATGACCAAGCAGCAAAGATAATCATCCTTCGGATCTCGATTGTTATGCCACACCTTCCC
          CCCATGTTTTAAACTGTGCCCGATGCTCTCTGAAGATGTCCAACTGTACCTAGTAGCGTC
          CATGAAGCTTAGACCGACGCTGAGCCCGCCCGGCGATCTACACCTATAGCCTGCAACGAC

          GCTGTGTAACTGAGTTAGCACAATATGCTTTATCCGATCCCAGTGGTACAGCTGTGCATC
          GCTGTGTAACTGAGTTAGCACAATATGCTTTATCCGATCCCAGTGGTACAGCTGTGCATA
          TTCAAATATCTGAACCATATCAAAGGATTCCACACCGATCCCGCGGGCGGTACCCACGCC
          GTGCTCCAATTTTTCCGACGCAGGGCGTCCTTCTCTGCTCTTGTTGGGTGTATACGCGCC
          GTCACGTTATTGACCTCGCACTGGGTGGCATGTCTCGTCTCATTCTGACGAAAATACGCC
          GTCACGCCATTGATCTGGCAATAGGTGGTTTGCCCCGTCCCATCCGGATGTATATACGCC
          CACGTATTCTCGAAAATATACGCAGATAGGCACTTCGTTCCGTGCTACTAATTACGAGAC
          GTGACATATTTAAGTTCATATAAGGAATGGACCTCTGTTCCGTTGCATCACTTTCGAGAT

          ATTGCCAAACGTATTAACTGTTTTCACTCACAAATCCTTAAACCAGACATGTCTAGTACG
          ACCGCCAAACGTATTTACTGTTTCCACTCACAAATCCTTAAACCAGACATGTCTAGTACA
          ATTGTTGATGGTACATGCCGTTTTTACTAGGAATCACACCTATGGGAGCCAATACCCGCC
          GTCGTCCAATGCTTGCAAAACTTAGACCCGTGGTTGCCTCAAAAGGATTTCTTTAGCAGA
          ACCCTCCTGAGCGATAACGCCCTAGACCCGTAGCTGCCCGAGAGGAGGCTAACTCATCTG
          ATCCTCCTAAGCGATCACGCCCTAGATCCGTAGCTCCCCAAGAGGGGGCCAAATAGTTTG
          ACATGCCCCCAATTATCACGGGGAGAACGACGCTCACCAACATGGGCCAGAGATCCGGTA
          GAATACTACAGGTTATAAGGGGTGGAACCACGATCACTCATGAGGGTCAGGGACCTAATA

          CCCGAATCGTCGCAGGCTGGGTTACGCATCAAGTCCGCTAGCCGAGTCAGTTGTTCGGGC
          CCCGAATCGTCGCAGGCTGGGTTACGTATCAAGTCCGCTAGCCGAGTCAGTTGTTTGGGC
          CTAGCCTTACGCTACTGTGGGTATACTAAGAAATTTTTCGAGCGTATTAATCAAAACAGT
          CTCGCACGTGAACACCCCCCGTGCTTCATAAAACGTTTTATTTGGACTCAGCCGCTGGGC
          TGAGAGTCAAGAAAATATGGATAACAGTATAAACACTCTCTCCAGTCAACTCGAGAGAAC
          TGAGAGCCGAGAAAATATGGGTAACAGTACTAACATCCTATCCAGTTAACTTGAGAGAAC
          ATACTCGCCATAGGCTCAGGCCACTAATAAGAACGGTCCTGTCACCATGATAGCGAGAGT
          GAACCTGTGCTAGGTTTAGCTCATCGACAAAAGCGGTCGTTTTACTGGGACAGCGAGGGC

          TTGTACAGAAAGGCATGGTCCCAATGAGAGTATGACATGGATTATAGAGAACTTGCAATT
          TTGTACAGAAGGGCCTGGTCCCAATGAGAGTATGACATGGATTATAGAGAACTTGGAATT
          AGGGACAGACAGACCCGAGTTGGCCAAGAATTCACTCTCGTCGATAAATACTCTTAGATC
          CTATGTCGGGTGTCTGGCCACTAGCGCGTGTACTAAAGCGGCGTCAGCTACTACGGGGGC
          ACATTTCAAGGAATCAATTCCAGCCGAGGGTCGATTCTTGTAAATGTCAACCTTACCGCG
          ACGTTTCAAGAAATCAATTCCACTCGAGAGTCGATTCTTGTTAATGGCTACTTCCCTGCG
          CCGCGTGTGTGGTTTACATACGCATGCAAGTACCATAATCTACCGCAATCCCGCGCACTT
          TTCCGACGGCGGTACGTTTTCGCACATAGGCACGACCCTCCACTACGCCTTCATATATCT

          GGGATATGCAGTAAGGCTATCTACGCTGTGACACATGCTTGTGGCATCGTTGTTACGAAT
          AGGATATGCAGTAAGGCTATCTACGCTGCGACACACGCTTGTGGCATCGTTGTTACGAAT
          ATGGTGTAAGCTAGGACTTACTATACTGAGGGGTGTAATCGTAGGCTAAGTGTCGTGCGC
          TGCACATGACGTACGGGCGGATGGATTGAGGTACATAGCCAAGATGTAAGAGTGGCGCAT
          ACGCTGCGAAGAAAGAGTATCTGGACCGGAGTACCCAACCGCGGTGTTCCAACAGCGGAC
          ACGCTACGAATTAAGAGTATCTGGACCGGTGTTCCCAACCGTGGTATACCAATAGCGGAC
          CGCTAGGGGTTAGTGAGGCATTACTTCATCGTGTACGACCCAAACCTTCTTGCTGTCGTA
          TTTTAGGGGGTCGTAAGACACTACCTCACAGTATATGGTCTGAATGCCCAAAGCGCATCC

          ATCTCTGGCGGCTACTTGACAGACTGTTTGCAGCCGTTTC
          ATCTCTGGCGGCTACTTGACAGACTGTTTGCAGCCGTTTC
          CTCCGTGTTGACTACAGGAGAGAAGATGTCCAGCGGCGTC
          AGCTTTGGAGGGCACCGGTTACCAAGCCCACTGAAAGGTC
          AACTTTGGACGAGACTGACCATCAGATTTACCCTAGATGA
          AACTTTAGAGGAGACTGGCTATAAGGTCTGCCCCTGTTTC
          GGCAGTTTAGGGCTGAAAGCATACAAATCAAATACGACCC
          AGTTGAACAGGGTTTCCAGTACATGATCTCTCTGTGTCTT

