 8 1000
t1        AGAGCAATAAGTCGACTGTAGTACCCCGTTAGCACACATCATGTCGACAGTGCAGGGCAG
t2        AGAACCATGGGTGGATTACAATTGCTAGTAGCAACAAACCCGGTAGACCGTGTTACGCAT
t3        AGAACTACAGGTCGGCTGCTGCATTTTGCAGCAACAAAGTTGGTAGTTAAAGTCGTGTAC
t4        CAAACCTACAGCCGTCAGCAGTACACCGTTACGCAGCACTTAGAAGTTAACGGCGTGTAT
t5        CGGGCATTAGATTAGTGGCATTAGCTTCCAACCTTTTACCAAGTGATCAGGAGTGTATAA
t6        AGGCCATCAGGATTGTGAAGCTACGTCGAAGTACTCTATTTCACAGTTAGTCGTGTATCT
t7        GGGCCCCTAACTCAACCATCAAGCACTGGGTCTCAAAATCCAACGACTAAGACTGACTAC
t8        CAGTAAGGTATCTTGCTCTGCTAGGTCGCGTGGTTAGGTGGGATAGACATACACTAAAAC

          TAATTATGTCCATTCTCATACAGGCGTGCTACAAAACCTACGGCTAGAGTAAGTAAGTGG
          AAGTCACTTACTTTTGAGTAGATCCTCGATGAAAAAACTTCGGTTTCAGTCGTTAACTAG
          CAGCTCCGCTCCTACAAATATCCGTCCGATGAAAAAATTTCGGCTATAGTCATAATCTAG
          TAGTTGTGTGTGTACGAGTCGTTTACTGGTGAGACACTCTAAAGCCTAACCTCCAGTTGG
          GACTTTATCCTCATCAAGTCGTCCATAGAATGGGTAACCGCGAGCGTGGACGCTAAACCG
          GGGCCCAATAAACCTACTAAACCCCGCGGGTTGGTGGGCCTTGACCCGAGTGATAATTTC
          CAGCCCCAGGCTTTTAGCTACGCCGTTTAACACGAGGCTCTGTGTAAAAGCGGCAATCAG
          GATATCGAAGCTTCGCAGTATTCGATAGACCATGGGGTATGGGACGGCACGACCGCGTCG

          GGGTTTCAATCAACGGAAGGTGTAAAGTGTTTCCCTGCACTTAATTAGAATACGCCACCT
          GGGCTTAAACTAAAGGAACACGTAAAGGATTACATGCAGCTAAATACGAATTGGCCATTT
          GGGTTTGAAACAACGGAAGGCGCGGGGAGTTCCCTCACACTTATCCTGAATATGAGACGT
          GGGATTAAGTTGGCAGAAGGACAGCAATATCCACCTTAATGTAAGCCGACTGCGTTGTAC
          GTCATTAAGTAGGCGGTATCAACGCAATGATTTTCTTAGCTTAATCTCGTTACGTTGCTC
          AGGACTGAGTTGATACGCTAGATACAGCACCCTGTGCGATCAGACACAAATTCGTCCCAC
          GAGATAAAATTATTCTACCGAACTGTATACCGTGTCCCGTCCACGTCGTATCTGTGAATC
          TGGCTCATACAGCCATAAGGACTGCTTAGTCCCCGCTAACATAACACGGACTCGTCCCAC

          CCGAAAGGAGGGTGTAGAGAGATATCGGTAAGACGTGTGCTTCGGGAAAAGCAGCTATAC
          TCTACAGGGTGACATATAGGAGTATCCTTGTGGCTGGCGCCTCGGCGGAGATCTCCATAT
          CTGCAAGGCTAACAGAGAGTACTACTCTTACCGCAGGTGCTTTGACCAAGGTCCCGGCTT
          CTGAAGGCGTAATATAGAAAAACGTCCTTACGTAAGATTTTCTAGTGAAGATTTATATCC
          ACAATGGTGTGTCGAAGAGACATGTCCCTGAAGGAAGCGTTACCGTGTAAGTTTCTGACC
          TGCCCGGCCTTAAATCAAGAGCCGCTTCCATGGAATGCATATTATCGAAGAGCCTAAGTA
          TCTTTTGAGTGAACTAAAAAGGTGCTATTGTAAAAAGTCTCCCTACGGGAGTTCAAAATT
          CTGTGTGCTATGTATTACAATATGCTCCTACCCAGATGGCCTCAGTGAAGGTTCGACAAC

          CCCTGCCTCCGGGGTTCTATGTTTATGTGTGGTGCTCTCCAGAATAGCCTTGTTCCTATT
          TCTGGCACTTGGGGTTCTGTGTTTCGGTGTGATGCATGTGAGAGTTGCTCTATGTTTACC
          CCCCCTACTCGGGGCCTTCTTTACCTGTCCGGTTCATATACGCGTGGCTTCGTATATATC
          TCAATACTACAAGGGTTTATCTACTGGCACGGCACCAATGGGACTGAATCCTAATACGCC
          TGGTGCGTGTGGGTGTGGACTCCCTAAGATGATACTGTCTACACCGGTCACGTATCTCAC
          CTCTACTTGGTATATCATGCTCTCTACCACAGTGCGCTCCGGACTAGCCCTGGGTATACG
          CTTTGTACGGCGGAGCTTCTCCTCGCAGGGCATGCACCCCGACTCGTCATAGTGACTACC
          GTACGTCTACGGACGCTTATTCTGCTCCAAGTTAAAACTACGCTTATTCATGTGTAGATT

          CCTAGTTGTGATTTCAGAGGACAGAGAGGAAATACCCTGCAGCGTGGAGGGCACTCCCCG
          AACTGTTATGACCTTCAAGGAGACAGAGCGATTACCGGGTCGCGCAGCGGGCTTTACTGG
          ACTAGCCGCGCCTAAAGAGGACAGAGACAGACCACCCGGCTGTGTTGCGAACTTCGTCTG
          TCACGTCCTAATAATAAAGCCTAGGGGGGAACAGTCCGGCAGCTTGGAAAGCTCGATAGA
          GATAGTCGGAATACCGGAGCCCCCGGCGCGAAAACCAGGGTACGTGGTAGCCCCAACCCA
          ATCAGCCGTCCTCACGGCAAACCCGGGCGAGCCGTTGAGCAGTAAGGTGGGCCGTACCCC
          TCAAGGCTTAATAACAGATTTCTTGGAATATTCGCCGAGCTATTAGCTTGGCTTTGCCGG
          GTCAGTCGCAGAGGTCGGCACTAAGTTTATGTTCAATTACTCTACGTCCAGTCCTGCACA

          CCTTTTGCACTAAAACGGGAAGGAACAACTAGTTAGCTAAATCGGACCGAATTATCTGGA
          CATCCCGCAACAGGCTGGTGGGGGGCGACTACTTAGCCAAGCCGTAATAGGTTGTACAGG
          TATTTTGCAGCAGGTCGGGACGGTGTAACTATTAAGCTCACTTGCACCAAGTTGTCCTAA
          TTGTGTCTCCGAGGTTAACTAGTTTCATATTTTCGGGCGCTCCGGAACGAGATGACCGGA
          TGAGTTATACTGTGCTAAAGATAGACATTTATTAAGACTGTTCCCATGAGGTTGTCCGGC
          CGAGCAGAACCCAGGTGTATAGGGCGATCTGACCTGCTCAGCAATCTTCGCTTATACTGG
          TGGATAGCTCCTGGACTGGAGTAAAAGCTCACGCGGTAAGACGTTATAATTCCACGCTGG
          TCTGCCGTCCCGGCTAGCAAACGACGCTTCACATGATCTGCACACGCTTGATGAATCCGT

          CAAAGGTCGCTCGGAGCTATGTAAGACAGGCGAGTTACGTTGCATGCACTGTAACGTATG
          AGCGGGCAGTTCGAAGTTACCTCAGATTAGTGAATTGTGCGGCACGCACTGCTAAGCTTG
          TGCCAAGAGCTCGGGGTTGTCGCGAATTAGCAGTTTGTATAGCGTTCATTGGCATACGTG
          TGCGAACGGCTTCGGGTCCATGCCAATTAACGAATTGAAAAGCCTTCGGCGCACAGCACA
          CTCAGACGTCATGGCACGGTCCCAAATTAGCGGGCCTGATGGTTTCCAAAACCGCTATTG
          AGTCCCCTGTTTAGGGATTCATAAGAGATGAAAACTAGCCATATTATGGTTCAACGTGAT
          GGACTGTAGCCCGGGAATACACTGTCTTGGCGGGTGTTACAGCCCGTGACAAGGTGGAAG
          CAACGGCCATTTGGGTCATTAACGGGCGAAACTGTTAGCTATCCATCCGAACCCGGTACT

          GGGAGCACACGGAATCACCTTAAAAATCTTACAGATGCAGCACCGTGATCAATTTCAAGT
          GGCAGTATACGGAACTTTTTAAAAGCTTATATCGAATAAAGGCCATGTCTAGTTCTCTGT
          GCGGGTATGCGTAGTATCCTAGAGACATTTGCCGGTCAAGCACTTTGTTTAATCTCCTGC
          TGGGGTACTCCGCGAGAATGAAGTATTTACGCTGTTAAGAAGGCCTGCTGGGTTTTCGGA
          GGTAATCCCAGAAGCAAATTGGGGCGTTTTGCACAGGGGGGGGTGTGGCATGCTTTTTGA
          GCGTGATTGCAGCAGCCTCTGAAACAGGTTACCTGTCGGGAGCCGCTATTTTTTACGACA
          AGGCATTGGCCCAAGCCTGAGAGGCACGGTATCAGCCTGGTGGCGCCACCAGTCTTGAAG
          CGGACAGTATGGCTACCCATAAGGTCCTATAGTCTAGCTCAGACATTGCGTTTGTATACA

          CTTGTTTGTTGGAGACCTAGGTCGGAATCGGGGGGTCGTCTTGAGTAAGCAATCAAATAA
          TTTGCTTAGAGATGATCAATGTCGGAATAGGGGGGGCGTTGAGGCTGGGCAATCAATGTA
          TTTGTTTTTATGTGGAACAGGTCGCAATTAAGGGGATGCTCTGATTGTGTAATCAAGGAA
          GGAACAGCCGGAGAGGACAGCCTGGAATAAAGTTACTTACCCGGTAACGTATGAAAGAAT
          GCAGTCACAAAGACCAGTAAATCGAAATCGGGGAAGCCTCTAAACGATCCAAGTGAAGGG
          ATAAAAGTATGTTCCTACGCCTCAGGGTCGGGGAATTCTGTCGCCACTGTAAGACTGAGT
          TTGCTTGGTAATAAAAACTCCTTGAAATCGAAGAGACCCGTAGCTAATGTGCGGAAGAGA
          AAGGTCGCTGAGCTGAGACGCACCGGGCCAGGGGGGCTGGCGAGCTCCATTTTGTTGAGA

          ATGTGTGCGGTCGGATTGCCGCTTGGACAAGGGTCGCGGCCGTGCGATTCATCTTCTGGC
          CCTTGTAAGATGAAATAGCTGCTGGGATGAGAGAGGTGGACGTGTGCGCCTTCCGCGGGT
          ACTACAGCGGGGAGGCAGCCGACGGAACAGGAAAGGTTCCCATTCGCATGCTGTCCGGGC
          GCCGGAAATATGAGGTAGGGGCAACGCATGGAAAAGGGGCTTTGCGATACAGATTCGAAT
          GCTGGCGGTGCGAGATAGTCAGCGTCATTCGTGCACAAATCTCGCGAAACTTTTCAAAGC
          ATTAGGGGTGTAAGCTTGGCGTCAGGGTCGGTAAGGAGTTACTGTTGGGTGCCACCATAC
          GCTGATGGAGCTGCGACGTTAACACATTGGGGACGGTGTTGCCCGGAGCCATATCGGTGC
          CTACCCTACGCACTATAAGAGACCGTGTATACCAGGTGGTTAAGTATTGTATTGCCAGGT

          TGAAACGAAACCGTACGACTGCCGGCCGATGAAATCCAGTATATAACACTGTAGCCGATA
          CGTATCCAAAACGCACAACGCCTAGTTGACGTTGTGTAGTATAATTAGCTGTAGTTGGCA
          TGCACCAAATACGCTCATCGGCAGACTGATGCAGCACATCATGAACTCTTGTGTTTGCCT
          TTTATCGCAATCGATGGGATGTCGAAAGGAAAAATCAGGTGAAGACTATTAAGTTCGCCA
          GCTGTCATATACGTTTGATAGACGTATAATGTAATGCGGTCCGGGATGTCGCATTCTGAT
          GGTGGGCCCAACGTAAAATAGCCGCCGGTTGATTTAAAACGCGGGATACTGGGTATGGTC
          GACTCTATCCAATACTAGCAGTCGCAGGGCGCAGCACAGCTTGGGTCGATAGATTGTGTC
          CTTGCTATCTGGGAAAATTCATCGATGTGCGAAACGCAACGCGGCAAGGCGGAACCGGTC

          TTGTGTATAGGACAAGCATGAGCGCAGGTACGTACGCAATGGAATCGGGACACGGAGCTC
          ATTTGCTCAGAGTAGGTGTAAATGTAGTCATGTCCGCAATGGACTCGGGGAACGGTGTTC
          CTGCGTTAAGAGTAAATCCAACTGTAGTTATATCCGCAATGGGATTGGGGAGCGGTGTTC
          TTTCGTTCCGAGGAGGCTCCCACGTAATTATGTCCTCGATAGGCCTGCGTAAGGCTGCCC
          TTACGCCATTGGTAGGTACTATAGTGTCTGGGGCGTCATTGGGTTCGCTTTGTGGCGCAT
          TCACAAATGGAACGCGTATATCTTTACTCATGCCCGGAATCAACGCGCGTGACAGACACC
          ATACATATAACATCACCTACATAGCATCTAGGTGCAATATGAATTTTTAGATATGTGCTA
          TGACAGACTGCGAATGCACTTTGGCAGGCATGTTCGAAAGTAGCCAGCGTTGCGCTGTTA

          CCGATGATGAATTCACAGCCATTATAACGTCCTAGGATTAACTAATGCGAGTGAGTTAAA
          CGGATGATGAGATAACGGTAATTATAACAATTTCGGAAAGATTAGTGCGAGTGGATAGCA
          TCGACCATGAGTTGACGGTAACCATAACCACCTAAGTAACCTGAGTGCGAGAAAGTAAAA
          TCAGTGACGAGGTGAATCTAATTACGGGATCGAGGGAAATAGTTGTACCCGTCAATGCGT
          CCGGCGGCGGTGCGAAAGTCCTAATGGGATTCCGAGAGATAGAAGGGCTTGCTCGCACAA
          GTGGGGATGAGGTTGGGACTTCTACCAGAACACAATTAGTTGAGGCCCTCGCGGGAGCGT
          ACGGTGACGGCGTGGAGACAAGGTAGAAAGCTAGCTCTAGAAAACTTCCTGCAAACACCC
          TGCGGTTCAGGTCAACGAACATCTCGATATCCTAATCTACAGATTACACCATGAGTCTGG

          TATGCTGAGGGAACAAGACGCGGACTCGAGCATGCAAGTACAGTGAGAACGTTGAAAGGT
          CATTAAGAGCGAACGCGAAGTGGACTTGTGCGTGAGAGCGTAATTACGACGCAGGAAAGT
          CATCATGTGTGACCAGGAAATGGGCTAGTAATCGTAAGCATAGCAATAACGTGGACAGGT
          CAGCAGAAACGGATGCACAGTAGCTAAGAGTATATAGTCGAGGCGGCATCATAAAGACGT
          TAGAACCATGCATCAGAAAGGGCACCTTTGCACGCAGGCCAAGCGGTAATGCTAGAAGGG
          TGCCATCAGTAGAGTCGAAAATATGTGCCGTATGTTCTTCACGGGTCTCTGCAGAAAAAG
          CTCTGATGTTTAGAGCGATCCAGATGATAAGAACAAGAGCGAAGAACTACGATAGAAGAA
          TAATGTGAATGAATACATGGCAAATTAACGAGATATCGCCCTGCACAGAAGAAAGAGAAT

          GAGTGACCTCAGTTTTCACGAACTGCCCCTATGGATTAAGATAGGGCACCAAGTGAGCAT
          GGGCAATCCCAGGCACTCCTGCTGGTCCTATTGGCCACGTCTATGGCATTTACTAGGCAT
          GAGCATTTTCATACAGAATCAGCGTTACTGATGGGCACTAATACGACGCCCACGCTACAC
          CTATGCTGCGAATTGATACATACAGGGATAGTGAACGCAACGGCTACCTCACCTGGGGGT
          GAGTTATAACAGTCATTATGTATAGCAATCGTGAAATCTGGGATCATACTCAATAGGCAT
          ACGTACAATCAATCTCCCACTATCATATCGGCAGGTGCTAGACCCACATTCTCCGAGTCA
          AGGCTTTATTAGTATGAATCTAACATGGGTCTGGGTTTGGTGACCGGGTTTAATGCGACG
          TCACATTGAACGACTGCTCCCGCCAAATAAGTTCACCTGGGAACCAAGCTCTTTCGGAAC

          TAGCGCTCAGGGATATGCCTTTTCAAGTCAGGCGTTGTCA
          TCGGGTACACGTATCTACCGTCTCAAGCCACGCGTCACCT
          TAGGGTGGAGGCACAGACGTTTCCCTGCCAGGCAATTCCT
          CGGCGTATCTGAGTCGTTAATTTCGTGCCAAGCAACTCAC
          TGGTGTACTATCAGCGCTCGTCTTAGCATAAGCTTTTCCT
          GGGGGTCAAGACGCCATCACTGCTAGCGGGTATAGAGCTG
          CGGGATATACTTGTTGTTCTTTTCGTATAACGTGTTTCCC
          GATGAATAGGACGAAGTCGCCGATCAATTATGTAGACCCA

