 8 1000
t1        AGGCGACGGAGTTTTTTGCACTTAAAGAATCCTGAACCCGATGTATGTGAAGATTAGCAA
t2        CGGCGGGATTATTCCCTGCAGCATACAAATCCCGGATCCGCAGCATGGGAAAACCAGTCA
t3        TCGAAGGGTAGCCAGTCGCTCCTTATGAATCCCGCGTACAAAGTATGAGAGGACTAGTGA
t4        TCGCAGGGTAACTCATCGCTCCTTATGAATCCCGCACTCAAAGTATGAGAGGACCGGTGA
t5        GAATGGTCAACGCGGTCACCCCCGATAGCTATTGACAAGAACATCTAGATTGAACGAGCT
t6        CGACGGGAGAACCTGCTCCCTCACACGATTATCATATATAATACAAGAGGTAAACAGTTC
t7        TGGAGCACGGTTCTACAGTCATACATAGGTACCGGGTGCATTCGCTGCAGGAGTCAGTGT
t8        TGGAGCAGAGTTTTACAGTCATACCCAAGTATCGGGCGCATTCATTACAGGAGCCAGTTC

          CATGACCGAATTCACTTTGGATTTACCACTTCTTCCAGCTTTTGTTCGGGACGGATGACA
          GATAAACGTAGCTTCCTAGCGATAGTTAACCTGCGCAACCCCCCTTCGGGCTAGTTCGTA
          AACTAATGTAGGTTCCACGCATTAGTCAGCTTGTTCAACTCCTGTTGGATTCGATCTTAA
          ACCTCATGTCAGTTCCGCGCATTAACTAGCTTGTTCAACTCTTGTTGGATCTGATCTAAA
          ACTACCGACGGGACAACCGAATAAATAAGCTAGTATGACGCTAAACCGATTAGGTGCGGT
          GATAGCCTGTGTCAGACCCATTTAGCTCGTCAGCTCGAACAAAGGTCTCCTCGGCAACGA
          TTTAACGGAGTTCAATCCTCAACAGTCAGCAGTTTCAGTTCGGCCCTAGCCTTACATGAA
          TTTAACGGAGTTCAACCCTTAACGAGCAGCCGATTCAGTTCCGCCCGGGCCGTATATAAG

          CAACCTCTACAGCACGAACCACTGTCCATCCTTACCTTTGCTGGCCAATGAGGTTTGAAA
          CACCCCCTACGGTTTACTTCTTTCATCGTTCGACTCTTCGGTGTGTTCGGTGATTCAAAG
          CATTTTTGATGGAGTGTTTTGCTATTCACCTTGACCTACCAAGTACCCAGTGGTTTGCAG
          TATTTTTTACGAAGTGTTTTGTCTTTCACCTTGACCTACCATGTACCCGGTGGTTTGGGG
          AGACCCCTAAATTCGATTTTCTAGCCTGGTCCAGTGGTTTGCGTGCCGACATTCTTCCCA
          TATTTCCCACGTTCACCCCTGCGCACGCGCTTAGTGAAGTAAAAGCAAGCCATTCCACGA
          TGCGCGTCGCGCCTTATTCACGGATTCCACTCATTATATTAGCGGCACGCCATTATCGAC
          TGCGCGTCGTCCCTAACTCTCCGCCTACACTCAATCTTTCAATGGTTCGCCCTTATCGAC

          TAGGCTTGGTATGGCCTGGATACTAGCTCTTGTTAGGTGGATTTCTTGAGGTCACTCTCA
          TGGCTCTGATCTAGACCTAGGATTAACTTTCTTTGGGTTGGATCCATGAACTGATCACTG
          CTAGCTTGGTCACCATAGAGGATCAGTTGTTCCTGGGTGGGCTTTGTGAGCTTATCAATT
          CTAGCTTGATCACCATCGAACATCAGTTGTTCCTGGGTGGGCTTTGTCAGCTTCTGAGTT
          TCGACGGGTACTGTAAGAGTGGTTGTATCGATGTGGCTGCGACGTCAAATCTCACCTGCC
          CTGCTCTCACAAGTTGAACGAGCTTTGTCTACCTATGCTAAATACTTATGTTACCCACGG
          CCGATATATGCTATTTAGGTAGTTCCGCCGCTCCTTAGAATTACCTCAAACTCACTTTTG
          CCCATATATGCTGTTTAGGCAGTTTCGCCGCTCCTACAAATCACCTCAAACTCACATTTG

          TACAAGATTTTATAAGGGATACCGAAGACCATATTCCTCCGCTGAATCGCCGCTAACGAG
          CGTAAGATATCACTAGGGATATGAAAGACTATATTCACTCGGTGAACTGCCGCTGGCGAC
          CAGAAAGATCCGCACAGGACATTACAACCAACAGTCCTTCGAGTTGACGCCGTCTGTGAC
          TGAAAAGATCTGCACAGGACATTATAACCACCAGTCCATCGAGTCGACGCCCTTTGCGAC
          TGTACGTTATCGAATAGATGATTTAAGTAAGCTATAAAGAGGCTAGGCGACAACATTAGC
          AGCAGCACCTTCATTGACGGATCGCTGCAACGCACATACTAGCTGCGCGAGACCACCAAT
          CAAGCACCTATAGGCAGAGAGTCGAAAGCGACGGTTCAGGACCAGCGCACAGCTGCAAAG
          TGAGCACCTGCAGGCAGGGGGTCAAAAGCGAAGGCCAAGGACCCGCGTACCGCTGCAAAC

          GCGCCTAATACAGATCCGTAAAATTCTGCCTTCATATGTATACTGTAGAAACGCCTAGTG
          GCAGTTTGGACGTATATCTAAATCTCCGCATCCACTTATAAATAGGAAAGACGTACGGTA
          GGTGCGCGGTCCCGTATGTAAAGTTCTGCCCCTATTTGCGGACAGTATACATGGCCAGTG
          GGTGCTCGGCTCCGTATGTAAAGATCTGCCCCCATTTGCGGATAGTGTACATGGTCCGTG
          AACCCACGCCTCGATCGGCCAAGGTCGGTTCTCTTCCGAAAACTAAGGACATAGTTCGAT
          AAGTCATCTACTAGTTGGCAATACTCTTCTCTTGTCTCTTAGTCGAGAAAGAGGTTCATA
          GGTTATAAACATCGGAGGCAAAGCTTCGCCGATGTAATCGGGCCGGGAGCGAGCGTGTGG
          GATTATAATCATTCGAGGCAAAGCTTCGTCAATGTAATCGGGCAGGGAAAGAGCGTGAAA

          CGACAGCTCAATTGCACATGCGGCTCTAGTCGGCGTCGGGCACCAACTGGTGCAGGGAAT
          AGGGTTTCCGATCACGCGCGCGGATTAAGAAGGGGTGGGCAACCAGCTGTTCCCGTTATT
          CGGCTGATCTATCTCACAAGTCGCTACGGGCAACTAGGGCAGCTCATTGCTTTGGTGAGT
          CGGCTGATCTATAGCACAAGTCGCTACGGGCAACCGGGGCGGCCCATTGCTCTGGTGAGT
          CTATTGCGTATAAGAGACTCAGGCTAATGAGGGGAAAAGCAGCGTGACCCTTAGACGTGA
          CAAGCTCAAGCCCTGGGATAGAGGGGACCTGGGAGTTAGCGGATCATTGCAATGGGGATC
          CGGCGACAGCTGCGCGCGAATACTCATTGCTGTTGACGGGCGTCATTAGACTCGGTATGA
          CGGTGGCAGATGCGCGAGAGTACTTATTACCGTTGACCGGAGTCACTTGACTTGGCAAGA

          TCAAGAATGTATGAGTCGGTTACCGCTCACCGTTTGACCTTCATGTAGCATTAGTGACGG
          CTAAGATTGTGTAAAAAGGTTCCCACGCCAAGCGTAGCTCTCACATGGCACTCTAAAAAG
          TGGAGGATGAGTATAACGGTTACCGCGCATAGCTTCGTTCTAACATGATTTCCTAGGAAG
          TGGAGGGTGAGTATAACGGTTACCACGCATTGCCTCGTTCTATCATGATCTCCTAGGCAG
          CATGGTCACTACAGGAAGGCCTCCCCGTTCGCCTATTTTCCATTTTGACATTGCGAAAAC
          TTCGATCGAGGCGAAGGAGGCGACACTATGGTCTAGATTTCTGGCTGCTACCATGAGACA
          ATCAAGCCATGAGAAAGGGCGTGCATGCAAGACTTAGCCTTTTTCGCATCTATACGCACC
          CTCTAGCCATGGTAAAGGGCGTGCGTTTACGATTTAACCTTTGTCACATACATAAGCACT

          GAGATGACGGATTACGCAAGACCGAAGATAGCCGCTATCGTAAGCCCAAGGAGCGCATAA
          GAGGTAAAGGGATCTGCAAAATTTAAGATAACTGTCAACGCATTCCCATTAAGCGCATAG
          AAGATAGGGGAAACCGCTAGATGGACACCAACAGTCCCACCTAGTCCGTGGGGCGCATAG
          AAGATGCGGGAAACTGCAAGATGGACAACAACAGTCCTTCCTTGCTCGAGGAGCGTATAG
          TCGGTGAGAGCGTTTGCGGTTCCGAAAGCCAGGACCGTTCGATACTTTAAGGCTATGAGG
          TGCATTCGAGCGCTCGAAAGTAGGAAAAACCCCGAGATAAGACGACCGAGAGTAAACAGG
          GTGACGGCTGCGGCTGAAAGCGGACACATCACGGGCCATAGATTCCTATAAGTAGCCTAG
          GCGACAGCTGCGGCCGCCAGCAAGCGCACTACGGGTCATAGATTCCTATAAGCCGCATAA

          CGGAGCCTTTTGCCGGCGCCACTACTAGATAGTGATTTTATTGGTAGGTGACGGTCCATA
          TAAAGCTTCCCCCCGGTGCCACCATTAGCATGCGGATTCAACGACAGGCGACGGGCCCTA
          CACCAGTCCTTGCTGATGTCACTATTGACCTGTCAGTCTACCGTTAGCCGACTAACATTA
          CACCAGTCATTGCTGACGCCACCACTGACCTGCAAATACATCGTTAGTTGACGAACGCTA
          AGGTGTAATTTGAAGAAAGCACTAATGGCTAGACACTACGAAATTGGATGTCAGGAGACC
          TAATCGCTTCCGTGTGCGCTGCTATACATTCTACTCTTTGAAGTGGGCTGATATGGGCAG
          TGTTCCAACACACGGGTATAATCGCTTATTGGTCATCATGAGGTCGTCCGGGAGAAGTCA
          TGTGCCAATAAACGGGCATAGTTTTTTATTGGTCATCTTGAGGTTGTTCGGGAGAAGTCA

          TGTGTGGGAGCTGGCGCGTGACGAACCAGTGGGTGGCAAATGTTGACTATTCGTCATCAG
          TACGTGGGGGGCGAGACGTCGCTGTTTGGCGACAGCTAATCCTATTCGGTTCGCAACGGT
          TGTGTGGGGGGCGGCCAGTCATCGTTTGCGTGCCGATAGACCTAGATATTTCGTTACGGC
          TGTGTGGGGGGCGGCAAGTGATCGTTTGGGTGCCGCCGAACCTAGATATCTCGCTACGGC
          TGTACCGGCGTATACTTACAGTGGAGAAATGGTCGGTACGCTAGGTTAGTGCGAACTACG
          AATGTCAGACGATATCCGTTTAAACCACGCGCATGTAGCCCTTCAGGAGACTCTCCTAAG
          CACGCCAAACGTAATAAGTTGTACAAGATAGAAGGCGGACTATGAGTAGCTCACCTTATG
          TGCGCTAAAGGTAATTGGTTGTACGAGATCGAGGGTGAACTATGAGTAGCTCACTTTAGG

          ACGGAATGATAAACAAGCTGGGCGGAATACACCACTCTATATGAGTCCGACACTGAAGCA
          TGCAGGTGGAAGAAAGGTTGTGACGCTTATACTGCCCCCTTTGACCTTCACGGTGCAATA
          AGAAGGTGATCAATAGGTTAGACATGAAGCCCTCTCCGATTCGAGTCCCAGACTTAAATA
          AGAAGGTGATCACTAGGTTAGACGTAACGCCCTCCTCGATTCAAGGCCCAGGCTGAAATA
          CAAGAGAGCTTCGCAGGGTAGGTAGAAGAATTTACACGCGATCAACCATAGAGCGATATC
          GTAAGGTCCATAGTGGGGCAACAGGCAGGTCTCCCAGCCATCGAGATTCCAGACGCTATT
          ATAGGGCGTAGGCCCGTACGGGTATATACACCCTGCCTTCACGCTCTGCCGCTTTGTGTT
          ATAGGGCGTAGTCCGGCACAGGTATATTCACACTGACTTCACCTTCTTCCGCTTTGTGTT

          CGGGCCTGACTGTTCTATTAAGTGACGGTCATTGCACAGTCGCTGTGCATAATCTAACCG
          CGAATAAAACCGCTACACTACAGGAAAGTCAGTGAATCGTCGACGCACATATTCCATTCT
          CGGGTACCACCACTACAACAAGGGATGGTCACTGGAATGTCACACCGCACATCCCGACCC
          CGGGTATTTCCGCTATAATAAGGGATCGTTACTGAAACGTCACACTGCTGTTCCCGACCC
          AGTACAACGTAGCGTCAGCGCGGCGGTGAAAGCCAGTCATATCTATTTGTTTCTCCGGCA
          AACGCGCCCTGGCCTTTTCGCCATAGGTCGAGCGAATTGTAGCATAGCGAGGCTCGTAGG
          TGTTTGACGCGGTACGGCATGGTGATGGTGTATCACTTTTCTTCGGTCGCAGCTCGACTC
          TGCCCATCGCGGTTCGGCATGGTGACGATGCATCACTATCCTTCAGTTGAAGCCCGGCTC

          AGTGCCTGTAACGCCGTACTAATCGAATTTCATGTAGCGGATGTTTTGATTGAGGAGCGC
          ACTCACTATAGTGCCGACCAAGTTGTTTCTTAGGGAGTGGACGTATAAATGCAAGAGTGC
          TTTAGCATCAACGCGATTCCGGTTGATATATATGCAAAGGGCGTCTGAAAGCAATGGAGC
          TTTAGCATCCACGCAACTCAGGTTGACTTCTATGCAAAGGACGTCTGAAAGCAAGGGAGC
          CTACGCCTTAAGCTCAAACGTGATTTCCACTAAACTGCGGGTACCTTTTGTGCAGGATTG
          TCGTGTCCCGTCCTCTTGTTAACTACTGTGGACACTATGAGGGTTGTTGCTATATGTTTG
          TTCCGATTTGTACCTCAATCAAACTGATGGTGGAAACCTCACATATTCGTAGCAAAGTAA
          TTCCAGTTTGTATTTCAATTATATTAATGGTGGAAACCGGACATATTTGTAACAGAGTCA

          GCCCTTACACGGGGCGTACAGGGAATTGGACACACTGTATTCTCCGTCGGATCGTGTCAA
          GTCCCCATGCAGGACGTACAAGGAATCCGTGGTACTGCGTCTTCCGACAGACTATGTCGA
          GTCCTTACGCGGGACACTCTGGGCATCGACGACCCTCCACTATCCGTCTAATTATATTCG
          GTCTTTACGCGGAACACTCTGGGCAACGACGACCTTGCACTATTTGTCCAATTATATTCG
          CATCTACTACTGAACGGATGGATTTACGGTGGTGAGGCCGGGAATAGCCCCTCGATTAAC
          CATAAACGCATGCAAAGATGAGGTAGAAATCATGTAGACGCACCGGTCGATTACCTCAAA
          GCCTTCTTGATGAACCGACAGGATGGTGGTCACGCGACACGAAACGTCGATGCCTTGCGG
          GCCTTCTTAATGGATCGATAGGATGGTGGTGATGTGACACGATTCATCAATACCTTGCGG

          GGGTAGGAGGGCCTAGCTACCCGCATTCGAAGTAGGCGAAAACAGCGACGCAGTGGAGGT
          GGGTGGTCGAATCGTCCAACACGCTCAGGAAATAAACAATAATGCAGCAGCCGCGGCGCG
          GGGCAGGTGAATAGATTGGTACGCCACAGAGCCGGAGAAAATCGGTGACGCGGCGGTGGA
          GGGCAGGCGTATAGATTAGTACGCCACGGAGTCGGAGAAAATCGGTATCGCGGCGGCGGA
          ACGCGGAGAAGTAACTTAACAAGCGAACCATACGGAAAATATTATGGTTGCTAAAGACTT
          AAACGGTGAAGGATCGCGTCAGGTCGCCGAATGGATAAGGTTCATAGTATTTACGAGTTC
          AGACACTTAGGGAGTTCGATGGGTGGAAAGGTCTGGAGGCCTTGCAATAGACGAGGATGC
          CGTCAGCTTAGGAGTTCGATGGGTGGTCAGGAGAGGAGGCCTTGCAATAGACGAGGATGT

          ATTTTCCTTGACCAGGCTATACACTATTCCCGATAACAGC
          GACCGTCTCGACGAGCACAATCTCAAGTCCCGGTAGCTGC
          CTTGTCTATGTTCAGGTCTAGCCTAGTTACGGATTACCAT
          GATGTCTATGTCCAGGCCTAGCCAAGTTACGGATTACCAT
          ACTGCCCTCGTTTGTAGGACTGTCGTCAATAGTTAAGAGA
          ACCCATTCGGTTGGCGCCGTCTCGATCTGAGGGTGATGGG
          CTTCTTTGCAATGTCGCACGCCTCACCTGCATACAGCTGC
          CTCTTTCGCGATGCCGCACGTCCCGCCACCATACTGCTGT

