 8 1000
t1        AACTGAGGCAGCAGTATCAGTGCTCGCATCTTGGCGGGTGGAGACGTCCTGTGTCAATGG
t2        CACTGAGGCAGCAGTGTCAGTGCTCGCATCTTGGCGGGTGGAGACGTCCTGTGTTAATGG
t3        TCTCGAGCTAGTCGCTTTACTACATACTCTTCTGAATGTGTAGCGAGTTCGTTACCCTGG
t4        TTTATCGTTAGTAGCATTCGTACCGCTCTCCCTGCGGGGACTGGTGCACGGTGCCGACGA
t5        CCACCCCAGCGGTACTGCAATATTCCGCTCACGGGGGGTGACAACAGCAAGTCACGCTAG
t6        AGCCTCGGTAACATATCTACTGCTCCAAGCTGTGCAGGGGAGAACAAGATGCTGAGTCAG
t7        CGCACTAAACTTACGCCCTTCTTGAACCTGCGGCGGTTACCGATCCGGGTGCAGTTCTCG
t8        GACACTTAACTTACCCTCGAATATGTTCTTAGGCGGCAGGTGAACCGTGCGCGGTTCAGG

          TTGGGTGTCAAATTCCCTCAGATCTGGGACTCTAATTTAACTTATCACTACCATGTGTTC
          TTGGGTGTCAAATCCCCTCGGATCTGGGACTCTAATTTAACGTATCACTACCATGAGTTC
          ACAGACATTGCTTTATATAAAGCAGGATAAGTGAACTAAATCCGTGGTGAGTGAGGATCA
          AAAGACTCTGAACCGAGGTGAACGGGGCAGGAAAGCTTTAGAACGTTTGTATCCTAATTT
          TCCGGCTTAACATTGCGCCGACCTGGGCCGGTAACGGCGCGTTTATCTGGCCTTAGGTCT
          TTGCGGCAAAGGACCCTTGTGGCCCGTCAGGTCTACTGTAGTTAATCCGGACCCGGCCTC
          CCGGGCGCTGAGCTCAACCAACTGGAGAAGCTCAGGCTTGAAAAGCCCCGACAAGGCCTA
          TCGCGTACCAAGATCCACCGATTGAAGCTACCCGAGTTCAGTTAGGATAGCCACCGCGGC

          AATGACCGGGCACCTGGTGTTGCTCAGGCTAGTTGATATCATGACTACTATACTCCGGGC
          AATGACCGAGCACCTGGTGTCGCTCAGGCTAGTTGATATCATGGCTACTATACTCCGGGC
          CCTTAGCATTCACATAACGTTGTTTTGAGAACCCGACACCGGGATTTTACCTCTCCATGT
          ACCCGGAGGTTGATTCACAGTTGGAGCAGCGTCTAGTGGTGATGTCCTTCGAATAAGCGA
          ATCGATGAGGCAATTTAAACAGAATAATCTGCTCAACGTTATTGTCCCACTGGTCAAGGC
          ACTCAATCAACTGACTATACGACAACACCTTTGCACTCCCAACACCTCGCCAGTATGCGA
          CTTTCGAAACTGTCTGTCGCTCTGACGTGACCTTTGTACCTTTGACCAAACGCCTTGACT
          AGCCTATGAACGTTCCCGGATTTAAGGTAAACTTTCCGGTCCGAGCTCACCGCCCAGTCT

          GCCAGCTGCCACGCGGACGCAAAACATGAGGCCTTCATATTAGTATCTCAATGATTGATA
          GCCAGCTGCCATGCGGACGCAAAACATGAGGCCTTGATATTAGTATCTCAATGATTGATA
          ACTGGCATTTAGTTAGCTGTCGGAGCTAAGATCATGTGACCATTGCACTTATACCGGGCT
          CTACCTACACGATCGGTCGCAGAGTATGAGACCGTCGACGTAATACATTGTTCAAAGGTT
          TAGAGTTATACGTGGATATCGGAGGACGTGATACCGAGCTGCGAATATTGATGTTCGGTT
          CTTAATTCACGGCAAGGCTGCAATCGAAAGCTCCTTAAATTCGAACATAAGTAATAAGTC
          TCCACCGTGTGACCGCAACTTGGTCATACGCTTTTCGCTCAGGTAAATCTAGAACCAGAC
          TTTGTTATGAAATGAGATGTTGTTCATAAGGTCCCAGATCAAGAGTCTCCAAAACTTGAC

          ATTGGAAGGATAAACGGGCGGAAGAAAACGTATTTGGCAGGCCGCTCCATTGAAACCAGC
          ATTGGAAGGATAAACGGGCGGAAGAAAACGCATTTGGTCGGCCGCTCCATTGAAACCAGC
          ACGGCTAATAGAAATAGCCATTCGCGAGTACACCCCGGGTATCGACAGCAATAGATACAG
          GTCGCCGGGCAAAGCAGGCGCCTCACAACGCACTGCAAACGGACGCGAGAGTAGGCATTT
          AATCTAGGAGGAATCGCAACGTCAACAACGGGCGGAACCCTTTTGAAGGATTGTTAGTGA
          ATCCACGCGATGTTCAGGCACTTACGGGCGTACTGAGCCTGTTTGCGGGATGAGTAGCAG
          AGATTTGATACGCTACGGGTCCAGTCGACCATGCGTTTCTGTCAAAGACCCCGTGAGCGA
          GGCTGTGCCATGATAGATTTCTAATGGACACTATGACTTTGTTCAGGGCCCCGTGTTCGA

          AATGTTAACCTCTCTCAACGGTGCCAACCGAGAGAAACTTCGAAGTCCACTGGCAATCTC
          AATGTTAACCTCTCTCAACGGTGCCAACCGAGAGAAACTTCGAAGTCCACTGGCAGTCTC
          AGTGTCACACACTCAGGACTTAGTAAATTGTGGCGGACAGGGAGAACGTTGTAGCGAATC
          GCTACAAGTAACACGGAGACATACATATCAGAGCTAGACATGAAGTTGTACGGTCGCACG
          TCGATTGATCTCCCATAGAATAATACGCCGCGGCTACCTGTCCAATTGGTATAGTGCGTA
          CTTTTGAGCATCATCGAGTTATAAATGTCGTGAATCTTCACAACGGCGATGTATTAAACA
          GCTGTCCGCACAAGCGTGTAATAAACCCGGCGCGGCTTAACAGTCACTCTTTCCCATGTC
          ATTACCCGCACCATTGTGTGAACCACCTCGCGTAGATCTGGTATCACCCTTTTACATGCG

          TGGTCCTGCCGGGATAATGATCAAAGAAATAGCTTAATTCAGTCCTTTGCCTACAGCAGA
          TGGTCCTGCCGGGCTAATGATCAAAGAAATAGCTTAATTCAGTCCTTTGCCTACAGCAGA
          AGCGGCTCCGGAGTCTAAGAACGACGGACTTTCCAATTGTTGACATCATAGGTAGACCAC
          CACTATCAATGAGGCCGCCTGATATAATTCCCGCGAAACAAGTTGCTTACAGCTCGTTAG
          TCGCCCTGATGGGACAACGTTCCGCAAGAGCTATCGTTGGAGTCGGTCAAGTCCCGTCGG
          CCGTCCTATGTGGTTTACGCATCAGAAGTCTCACGAATCTGATCCCCTACAACTGGGTGA
          TCCATCTGGAGGGTCACTGACTCACAAGGAAGTTGTCAGATACTTCACTACGGCGTTTGC
          TCCGCCCGAAGGGTCATTGCTCCACGGGTTGTTTTCGGGACACTAAATACAGACGGCTAC

          GTACCCGGTATAATGATGTCCGGTAGATGATCGATCGAGTACCGAACATACAGAGCCTAA
          GTACTCGGAATAATGATGTCCGGTAGATGATCGATCGAGTACCGTACATCCAGAGCCTAA
          TTTCCCACGCCCGGGCGTTCGCATACGAGTCGGACGATCTATAGTGTATAATAGGTCCCT
          CTGCCAGAGATTTCAAATCCTAGGAACTGGGGGATATCATTTCATTGATACAGAATGCCA
          GTGCACAATGTTCGTAGTCGAAGAGGTCTACTAATAGCGCACAGCTCAACCAACTGTGCG
          GCTTCGAAGAGCTCGCACTCTTGTGTGCACCGGCAACTGAACGTGACTCCCTGGGAAAGA
          TGCTCGAAAATTCCCGACCCACGCGGCTGCTACATCTGGTATTGTTTATCTTGGTCCACC
          TTCTCAGGCATTCCCGCCTCACGCAGTCATTAGATCCAGTAGTGTTCATCTCGACCAGTA

          GAGCATGCGCTGGGAAGGTGCTTCTCGCATATTGGACACGTATCTTGAATCGCGCTGATC
          GAGCATGCGCTGGGAAGGCGCTTCTCGCATATTGGACACGTATCTTGAATCGCGCTGATC
          GAATATGCAAGCGGTACTCTTGACTCAGGCCCCACATGCACATCTTGAATCTTGGGTATC
          AAGCGCGTGGCTTAAAAGTTATGCTTGTCATCTGGTGGCAGGTCCGATGCCGAACATTCA
          AATATCGCAATTCCTCGATCCCATCGCTCAGAACAATCCAGATGACGGGTGTAAAAGGTC
          TGATCCGCGCTCCGAGAAGTTTTGGCATCCGGCGGATATAAATCTTGCTTCGCGACGACG
          GGATAGCTAGGCATGACTTGACTTAAGCTAGATGGCTGAAAACTGTGTCTAAGGGAGTCC
          CGGCAGACAAAAGACAATTGACCTCAACTAGATGATTGGGAGCCATGACAAGGGTAGCCT

          CGAGTAGCTGACCTACTAGGTGTTCTCATCGGGAATGAAGACTGGGGTGTACTTTTGAAC
          CGAGTAGCTGATCTACTAGGTGTTCTTATCGGGAATGAAGACTGGAGTGTACTTTTGACC
          CCGTTGCTATCATCTCCAGGTCGAGTCGTGTAAGAAGCGATTTGGATAGCCTCATTTGTT
          TCTCAGCTAAGCTTGTTCGCCCAAGCCGACAAAACGGCAGTTCTTGGCTGAGCGCCCGAT
          CTTCCGGCTGCCACCTTACGAGGCCACGCAGGGAGAGCAGATCTCCGAATATTGTCTATC
          CTCTTAGCCTCGTCGCCCGGTCGTCTTAGGATGAGGGCGCGGCTGGTCGTGTCGTTAGTC
          TCTTAGGGCTCTACCCGTGAAAAGCAGCATGTCAATATAGTTGGGCGGGTCTCAACCCTA
          TGTCGGGGCCAGACCCGTGCCAATCTGCGCAAGAGTGTGTTCGGGAATCCCTCAGCCGCG

          ACGAGGGTGGTGCCATTGCTTCAGTAATGCTTAAGCCACAGAGATTGATCCTCGTATGGT
          ACTAGGGTGATGCCATTGCTTCAGTAATGCTTAACCCACAGAGATTGATCCTCGCATGGT
          ACTAAGAGAGCCTAAATGCCCGACACGCGCGCGTGCCGTAGGCTCCATTTATCATACGGA
          TTGGAAGATACGCGGGGCTTGAAGCAGCGCTTTTCGTGAAAAAAACGAATGACATCGCGT
          GCCAATTTGGTTGAACGCACACGATGCCGTCCATGCAGGCAGCCGAAAATGAGTTGGTGC
          ACAGTGCTGGTAGTATCAACTCCCACATAGTGGCGCTTCAAGGGCAATGTGATGGGGCCT
          ACAATGCTAAGCGAAGTTTACCTTGAGAAGTAAGAGCGGAGGGTCTCATTATCTTACCCA
          ACAGAGCTGAGTGACAGATTCCTTGAAAGATCGCGGCGAAGGGCTTGAATGCATAATGTC

          CAGAACCTCATTAACCTCTGAGCTACTTTGCGATGGATGCAATGTAGGTTCAGTGGCGAC
          CAGAACCTCTTTAACCTCTAAGCTACTTTGCGATGGATGCAACGTAGGTTCAGTGGCGAC
          TCGTCATGCACTAACATCAGATTCGTTCCGTAGGGACGTTGATATCAGCCCGCTTGTATT
          CCGACGGTCGCTGTTACCTAAGTCGTTGTTCGACTCGATGCCTTTTAGACCGAAACTGCC
          TCGATATTCATTGGTACGAAGATTACCCTGGGGCCGACAAACTGATAAGTAGTGTGCACC
          CTAACACGTATTTTCACTGGAGTCTAACTCTAGCCAACGTCCTCCCATATAGACCAGTCC
          TGACTGAGTACGGATTTCCGGATTTTCGAAAGGGGTTGTAAGCACGGGATCGTACCTGAC
          AAGCGACATGGCAAGCCTCGGACTCCAAAAAACGGACAAAATTATGAGATCATTCTTGTC

          GAAACCAGCATGCGAGTCGGCTGAGGGATGTTACTGCGGGTGCATTGGTATGACCTATGG
          GAAGCCAGCATGTGAGCCGGCTGAGGGATGTTACTGCGGGCGCTTAGGTATGACCTATGG
          ACGGCGCGCCCGGCCCCTGCCCGCGATGTGCTTACGACAGACTATTGCTTCGTCGCGAGA
          AACCATGTCGGCCATTCCTGCTTCAGATGGGCCCCACTAAACCAGACGCCTAGTAGGCAG
          GACCTTAGACGGGGCCTAGAATTCCGCCCGGTTCGCCTAACATCGAGGTTGGTAACGCGG
          GCCCCTTGCCAGAACCTTAGCCTAAGGCTTCTCTTTCTTGGAGGATGGTCCTACATACAC
          CAGCTCAACTTGGAGGTCCAACGTTAACTGATTTGTCCCATTAATCAGGACAGTATGCAT
          CCGATCAGTCGGGATGTCTGTTGTTTATCAGTCTTCCTGACTATTAAGACCAGCGCACAA

          ACCAGTTAATAGGTATGACACTCATTGCCGGGGGGTCCAATTGCGATAATAGACTCGCGT
          ACCAGCTGATAGGTATGACACTCATTGCCGGGGGGTCCAAGTACGATAATAGACTCGCGT
          TCTGGCCGCGAAGTGGACGACTAGGAAACGAGACGTTCACCGATTGCACCGAAGCGTGCT
          AGAGGCAATTAAACTAGGGTGTAGAAATATGCGAAGCGTGGAGGCGAGACCGAGCAACAC
          GGATCTCAACGGAAAACGCCCCTGAAGCGTGTGAGTCCCTCGTTAACGCTGAAGTCGGGT
          AGTCACTTGTGACTGGATTCGCTGTGCTGGATGCTTTTTAAATTTACACTGTAGTGCGAC
          GCCGGACAGGGCTTAACGTTATTGGAACCGATGAGTCCTCTAATCGTGCGAAAACCCAGT
          AACAGACAGCGGTTTATCCCACCAAAACTGGAGACTTCTACACCGGCGTAAAAGCTTGAG

          GAGTCTCGGTGTACCAGGTGTGCATAACGTGCGAAAGAAGCTCTGTTGACCTCATTTCCC
          GAGTCTCGGTGTACCAGGTGTGCATAACGTGCGCAAGAAGCTCTGTTGACCTCATTTCCC
          GCCTTATAAGCTCGCTGAGGAAACTCATACTCGACAGAGCACGTTTCAATATCACCTTTT
          GCTTCTAGTCATCAATCGAAATAGCGGTCACTGGGTTTAGACTACACGGACTCGTCTCTT
          GTCCATACGTCTATAGGGGTCGTAACGCATCAGTCAAACGCTCATCCCTCGTGGACCAAG
          ACTCCCCGCAACGAGTCGAATGCAATACAGGCGAGGGAAAGTGGTCCAGTACTGTGACCG
          ACATACTGCAATCGAGTAGGTGGACAAAATCGGCGAGGGGGTCTCCTAACACTGTCTGAG
          ATCTTTCGCAATCTATTAGTCGGACCATGTTAGCGAGGGGCCCTGTTGACATTGCGTGCG

          GGGAGTAAATTAATGCCAGGACCCCCCCCATTGCATCTCTTAAAAATCAGTGCGAACTCA
          GGGAGTAGATTAGTGCCAGGATCCCCCCTATTGCATCTCTTAAAAATCAGTGCGAACTCA
          CAACGGATTTCTCTGCTGGCACATCACTGGGTGTATTCTTAGGCTGACGGCTTGATCTGA
          TCGAGAGACTACGTGCCGAGGTAACCTAAGATCGCCTGGTCAGTGGCAGAATCGCGTTTC
          TAGTACCAAGTAGGGTTGTCCCTCTTCCAAGCCCTTTGCCAGACGGCGTAACGGGCCCGC
          ACCGAATTATCTTCAGCGACTTACCGTCCCGTGTGGCTCCTCGCAAAGGACTAGCATCGT
          CGGACCGTGCATCTGTAAGCATAATCGGTCATGAAGTCGTTAATGCGGGGAAGAAATCCC
          TGGAGCGTACACCTGCAAGTATAACATGGCATGACGCTGGCAGCGTAAGGTTGGAATCTG

          AGACAGGAGAATTCTGTTCGAGTGCGTGGTATGATCGGTC
          AGACAGGAGAATTCTGATCGAGTGCGTGGTATGACCGGTC
          AAAAAAGGCTCGGCCACACCGGCTTGAAACTCATACTGCC
          AGATAGGTTAAGGTAACTCCAACCTGAACGAGAGTTACGG
          AGAAAGCATGCGGATTATCCGTTGCAACTAAGAGCTTTAC
          CGAGTAAGCGACGAGGGTCCTGCTGGTCTAATTCGACCTA
          AAAGAGGCTGACAGTACATCGGCACTTATGTTGGCCATTC
          AAGGCGGACTGTAGCCTGCTGGCGCTGATCATCATCTCCT

