 8 1000
t1        GAAACATGGCTGTCGCAGCTGTACGAATCGAACGGGAGCCCGGGAAGGAGCACTGTCTAG
t2        GAAACATGGCTGTCGCAGCTGTACGAATCGAACGGGAGCCCGGGAAGGAGCACTGTCCAG
t3        GTGGTGAGGCTGCTGGGGCGATATGAGCCGAGCGGCGGCCCAAGCAGGTGGAACTTTTTG
t4        GTTACGAGGTTGCTGTCGCGGTACAAATCAAATAGAGCCTCAGGCAGGAGATCCCTCATG
t5        ACTACAACGTCCCTCTGGCGGCCCGCATCAGTAAGGGGCGCAGGCAGGAGAGGTCCCTGA
t6        ACCGAAGGATTGTTTAAGTGGCCTTTGTCGTGCAGACGTCGAAGCGGGTGGGATCGATGG
t7        CGTCCACGGGTGTCACATAATGCTGCATGACGAATGGATATCCGCTGAGCTCACAAATCA
t8        ATTGGCGGGTTGTCAGAGCTGAGGCCAGTATGTAGGGACCGGAACAGAGTTTATTCGATA

          TCGTTGTCGTCGGAGACAAAGCCCTAGTTGAATTAGGACATCCATTAGAAGTCACTATGA
          TCGTTATCGTCGGAGACAAAGCCCTAGTCGAATTAGGACATCCATTAGAAGTCACTATGA
          TTGTAGCCGTCAAGGTCATGGCCATATCTGAGTCGAGATAGCGATTAAAAGCCATTATGG
          CCGTAGTTGTCGAAGTTAATACTGTGGTTCAATAGAGATATCTATCGGGAGTTGCCACAA
          TAATATTCGCCGATTTTATACTTTCAGACAAGGTCGGCCACCTACACTGGGTTATCGCTT
          GAATAGCCGATGAACCACCGCCTGTAATGGGAAGAGGTGGTTCATGATAGCGGAGCATAT
          AGGGAAAGACCGCAGCTCTAATCTTCCCCAAATACCACAGCCTATAGCATCAAACAAACG
          TAAGACACATTGTATACCCGACCTCGGTCGTCTAACAGGGCTTCATGTGGAAATTCCGTA

          CGTGGCTGACTGTTCTCGGGGTGCCTCATAAAGGAGCTGTTATGACCGTCAGACTTCTAG
          CGTGGCTGACTGTTCTCGGGGTGCCTCATAAAGGAGCTGTTATGACCGTCAGACTCCTAG
          CCTAAATTGCTACTATTAGGGTTCCCTGTAGAGGAGATCATTTAACTATAGGACTGTGAC
          CGTGGGTCTTTGTTCCCGAGGCGGCTCATAATGGAGCCTATGTGCCGTTCAGACTTCTAG
          CGGGGGGTGTTGCTTTCGTGAGCTAACAAAAATGTCACAGTACTACCATTGAATATCCCG
          TGGCCCTCGCTGAATGTGAGGGATTATAATGGGGAGGTGGCTTTACCAACAAATCATTGT
          TGTGTGCCGCGACTATCTAGATGCAAGGAAGTGACGGGGGCAGGGCAGCTGGCCACTATG
          CATGTATCGAGGATAGCACGCAAGCAAGAGGAGCAGGCTTAAATATGTTTAACCCCCTGG

          CTGCTAGCAGAGCAGCCATGAGATAGCTGCTTCCACGACGGGGAAAAGAATGTCTTGTTG
          CTGCTAGCAGAGCAGCCATGAGATAGCTGCTTCCACGACGGGGAAAAGAATGTCTTGTTG
          CTGACGTCAGAACCACCCTGTCATATCTTCATTCACGCCAGAGCAAAGGTTGTTATGTCG
          ACGAGTGCGGAGCGAACATGAGACGACCTCTTCCACGGCGAAGCATTGATTGCTATGTTG
          CCGATGGCAGCGCGGCGAGCAATCAACCTGTCTTGTGACGAAACAACGGACACTACGTAG
          TCGGTAGTCATACGATTGAAAGTCCTCTGACGCCCTGTCGTTGAATAGAGTCCTACGCCA
          CATGGCGTGGCGGAGCTCCAGAGCCGTCGGCCCTCCATTGGTGCAAGGGACAAGTCTGCA
          GCAAAGCCATCCGTCGTTCGATGCAAGCTCCCTTTAAATGGTCCGGAAATCGCGTACTAC

          CTGCCACGCCTTGAAAACCTACAGCCTCCATCGAGAACACATACCCCCGGTTTGGTGAGT
          CTGCCAGGCCTTGAAAACCTAACGCCTCCATCGAGAACACATACCCCCGGTTTGGTGAGT
          TTGCTTCATCCCCTAAACCCACCACCTCCGTCGAAAACGCGTAGCCTAGGTTCAGTGGAT
          ATGCTACGTTCCCTGCACCAACTCCATCCGTCGAGAACGCAGATCCCGGGTTAAGTGGTT
          CCGCCCCATCGTATGGACGACTTCTCCCTGGCGTAACCATAAAAAGTATGTACAGTTAGT
          GTTTTAGGTCACTCAAGACACCGATTTCCGGCGAAGGGTTGGATATAAAATTTGGTTTGT
          GTGCTAAGACGTCCCAGCGACGGATTCCTTGTAGCAGCACAACCACTGGCGTTAATGAAC
          AGTTTCTGGTGATCAGGTCGAACTCTTTCGACGGGGTCTTAGATCTTCAAGACGGGACAC

          ACCATACAACTATGCTCGATTAAGTCGAGTGCGGTTGTATGTGATTTGGCTGATCATTTA
          ACCGTACAACTATGCTCGATTAAGCCGAGTGCGATTGTACGTGATTTGGCTGATCATTTA
          ACGGGAAAACTAGGCTGGACTAAGCCGAGCACGGTATGATGCGACCATGCTGACCGCCCA
          ACTAACACGAGGAATCCGATCATCCCGGGCAAGGTGTGACGCGACAAGGCCGAGCACCTA
          AATGTTGAGCGTCTTCAGGTATCATCCGGTCCGGTCAGATGGAATCTGAACGAACAATGA
          TTGGTATGCGTAAAGTTGACTGAGCCCAATCCAACACCACACAATTAATTTGGACATTGG
          GCGACTGGATGCAACCTCATCGTGCTGCGCACGGCCTTGTACGAAGACAATGTAAATTAA
          ACGTGCGACATTTCAATGATCCAGCCAATGTGGTGCAGACATCATCAAGTTCATGGTCGG

          CACTCTTATGTTTTCGCCTCCACAACCGATTTCTCCTCTCGGTCCGCGAATGTACAAGTG
          CACTCTTATGTTTTCGCCTCCACAACCGATTTCTCCTCTCGGTCCGCGAATGTACAAGTG
          CAATCTCATGATTTCACCTCGGCAACCGATTTTCCCTCAAGTTTACTAAAAATACAAGTG
          TGCTCCGACGACCCCATTTGCATAACAGAGCTCTCCTTGTAGATCACGTAAATTCATTCG
          ATAGGGCCTACAATACCCTCCATTATCAAAATTCCGTTACGACTCAGGAAAGTTCATCCA
          TGGTCTGACATAGCCCCCATATAATGTGGCCCTACATGTATGATTAGAGGTTTTCGAGCA
          ATGCTGTTAGGATTCCTTTTGAGTGATATTCACGTCTCTAGTCCAAAGGGTTGTTGCGTT
          GGAATCCTCTGGTAGGATTACCAGGAGATCTGAATTTTGTAGTCCTAAGGCACTCGCGTA

          TATAGAACAAACACCGATAGCCTTATTCACTTCCGGCCGTAGTAAGGACCCTTTGGGTTT
          TATAGAACAAATACCGATAACCTTATTCACTCCCGGCCGTAGTAAGGACCCTTTGGGTTT
          AAGAGGTACAACATTGTTAGTTAGGTAACGTCTTGAAAGTAGGGGTGATTCTTTGACTAT
          CGGATGTCAAACCAAAGCAAGCTCACCGAATATAGAAAGTCGAGGGGTCCCCCTGCCCGT
          CGGAGATAGTAGATCAATCTCCACATTGGGTCTCGTTCTTAGAAGGAAACTTTTGGCGCA
          TAGAGAATTACTGACAGCCACCCTGCTATAGACAATGATTGTTCGTAACCCCTAAGAAAT
          GAGTGGCTGAGAGCGAGCCAAATCACTGGGTTACTTCATTGTGGAGATGGTATTAATTAA
          CGGGGATAAATATGTGTTCATTAAAGCGGGCAACGTGATCGGACAGAGCTTATTGGTAGT

          CACCCGTCATCGACCGTCTCGGGCACGACGAACACGTGCATTGCCTGCCAATATGCTGAA
          CACCCGTCACCGGCCGTCTCGGGCACGACGAACACGTGCATTGCCTACCAATATGCTGAT
          AACCCACACACGAACTCTTCACCCATACCATAGATGTGTATTGCCCTTTACCAAATTGAA
          CACCAGCATATGACCTCATCGTCTGTGGCGGAGATGCGTATTGCTTGCAAAAAAATCTGG
          CGTCTGTATCCTTCCACTCTGCCTGTGATACAGACGTATATTGCCCGTCTCCCAATTCAG
          GTAGCGTACTGCGTCTCCTTTCCTCCGGTGGGGCCGCGAATTGCTTGACCGACAGTCTAG
          AAGGCGGACACACATTTCATAACTGCTATGAGTCTGCTTGCGGTTCCCCATAGTGACGAG
          CACCACCATGCAAGAACACCTCCGGCAACAAAAAACAGTATAGCTGAATAGCAAAATTAG

          TATTCTTATCCCGCACCAGTCGGTTCTACTTTCTTAAGTTAACTTGGTACTAGATGTGGG
          TATTCTTATCCCGCACCAGTCGGTTCCACTTTCTTAAGTTAACTTGGTACTAGATGTGGG
          TTTATTAGTATCGCACGGGTCAATTCAACTTTCTCCAGCTAACTTGGATATAGAAACGGG
          AGTCTTTTGCTAGTACAAGCTCGTACGGAATTCTCCAGCCAACTTCGCGACAGCAGTGGG
          ACTTTTCACTTTATACGGGCCAGCTCTCCTTTCCCGAGCTCGGTCAAGAATTAGCATGTG
          TCTTTCAAACTGGCGGAGGGCAGGTCCATGGACCTCAGTCCGGTAGGGCATAGCTTAAAA
          ATGCAAGGGCTACTACGCGACGGTATTATCCATAGCATAGGTGCATGTCCTGAAGCCTCG
          GTGACCTCCTATAGGCGTCCAGCCTTCTCTCCTTATAAGGCGCCCCGCCTAACAGTGTAA

          CAACCGGGGTATTTGGGGTACTTACGGGTCCGAGTGCCTATCGAAAAACTATGTCTGTAA
          CAACCGGGTTATTTGGGGTACTTACGGGTCCGAGTGCCTATCGAAAAACTATGTCTGTAA
          GGAACGGGATATCTGGGATACTTGGGGGCCTCAGTACCCATAGAAAGACTGCGTTTATTA
          GGGCCAGGATATCCGCGACAATCATGGGTACGAGTACCGCTTGAAAGGCCGTGGTTGTTA
          GGTTGAGGAGACCTAAAGAGAACATAGGTTTTACGACCTATCGCACGACTGTGCTCGGGA
          CAATGGCGATAACTAAAAAACGTATTGAATAGACTACCTACTCAGAGATTATAGCGGGCC
          CAGTGGCGGTGTATTATTTGATACTGGGGACATACACAAGCGAATGTACTTTGCTGGAGA
          CGATCGACGGATACTGGTTCCGATCACGTGCAAGCAGTTGCTCAGCCATGCGGCATAGTC

          CGATGTTTAAGGATTGAACTATATGGCTTCCACCGGTCAAACGGATCTTATAAACGTCTT
          CGATGGTTAAGGATTGAACTATATGGCTTCCACCGGTCAAACGGATCTTACAAACGTCTT
          CAATATTTAGGGATTGAACCGTAGGGCTAACGTCGATCACGCGAACCCTTCCTATGTTTA
          CCGTATTTAAGAATTGAGGCGTATGGCTATCATTGACCGGGCGAACCACTCATACATTCA
          CACTACGCTCTAGCCAAACTGCATGGTATCTATTGGATGGGTGAGTTAGTCCGTAGTGCG
          CAATTTCCTCTATCCGTGTTACAGAGGCAGACAAAGCTTGTTGTACTCCGCAGCCATGCC
          TCACGCTAGCTTAACACGTATAAGGGGAACGAGCAACGTGGTGCAACATCCTTTGGTTTA
          ATACACTTTGAGCCGGCGAGCAAATATCCCCTCTAACCGTTCGTTCAATCACTATAGTCC

          ACCTCATGTACATGCATCGAAGGGTGAACTTAAATAGTCGTCCAGCAGAGCTAAGGGAAA
          ACCTCATGTACATGCATCGAAGGGTGAACTTAAATAGTCGTCCAGCAGAGCTAAGGGAAA
          TCCTACCGCGCAAGCCTCATCAAGTGATATAAACTTGTCGCCCAGCAGAGTTGATGGGAA
          CTCACCTGCACCCGATTTGTCAGGCGGCGCTGATCAGTCACTTAGTAGAATAATTGGCAA
          GTACCCCACGCGTGCTTCGTTAGCAGGGGTTGGCTCACAATACTACTATGCTAACGGGCT
          GACTCCACTGCTTTTCCCGAATGCCGTCTTTATCCTGCCGCATAGCAAGGTTTGGGTTAG
          GATAACCTCACTCACCTAGATTAATACTCCGAACTAGATGGTCAGACGGTATTTTGGATC
          ACGTTTTATTTCAATGTTTCTAGGGACCATCGGATCGGAACGTGGAAGATCCGTCGTAAG

          CAGGCGAAATCACGAGAAAAAAAGCTCCGCATCATTAGGGCTTGATACAGCTAGGCCACT
          CAGGCGAAATCACGAGAAAAAAAGCTCCGCACCATCAGGGCTTGATACAGCTAGGCCACT
          AAGGCGAGCCCACACGAAAAGCAGAATCATAGCCTTCGTGCTTGACACAGTGAGAACGAC
          CAGGCGAGACGACCAGAAAGGTAACGCCGTAACGTTTATGCCTGATATCACAAAGTCAAC
          TATGCGAATTTGTTGATACGACTACCTTGTGGACGTATCCTCCGGTATCCATCAATCACC
          CACGCGATGCTGATGGAGTCGACACTATTCGGCCACTTTCTCGACTTCTAGCGGACGTAT
          TAGGCTAGATTACCGGCGTCGGGGATTCTACGAATTTTCGCATGATATCGCTGTAACCAA
          CGTGTTCCACCCCTGAAAGAGGTGCCAAAGTGACCATATAATCGGATGTCTTAAACGTAC

          ATAATCGCCAAGACTGTATCGGGTAATGCAGTGCAGACGTCAAATCCTAAACTGGTGACC
          ATAATCGCCAAGACTGTATTGGGTAATGCAGTGCAGACGTCAAATTCTAAACTGGTGACC
          AAAACCTCCGGCCATGCTCAAGGTCGTCTAGTGCAGCAGCGGAAACCCACACTGGCGACC
          TAAGTCTCCAGTATTACTTCGGCTAGTTCTGTGGAGTGGTTGAATCCCAAGCTGGGAATC
          ACGGAATGGGAAAATATGCCGATTTTACTAACCCTGTGGATCAAGTTCGAACCAGGCCCG
          ACGGGCCGGAACATGGTCAGGAGTGACATCTCGGGGCGCGTGAAATCTATGCTGGAAAGT
          ACCGGACCGGGTGTCATCTAACGCAGTCTAGAACACCTCATCAGGTAGCTGTCGGATGGC
          ATTTTGATCAATGTAGGGTAAAGTGATTTAGAAGAACGGATTAACGGGCAAGTAGGGATC

          ATGTCGCACGTAACGACACGAATCTCCTTTTCGTGAAGTACGTACCTAGACAGAAATGAC
          ATGTCGCACGTAACGACACGAATCTCCTTTTCGTGAAGTACGTACCTAGACAGAAATGAC
          GTCCAGCCTGCATAGACACGATCCTGGTTTTCTCGACGTGTGTACCTAGGCCGCGCTCGC
          ACTTTGCGCGTAAGGACATGGAACTGGTTTCTTTAACGCAAGGACCTCGGCTAGCCCAAG
          AGCTCCCCCGCACACTGACGGGTTTACTCTCTATACTGTAAAGTCCAGAGCGACTCTTCT
          GATTAACCCGTTAATATAAGAAGTGGTTTGCCATACGGCCCCAACCCCGGCAGCCCCGAC
          ACGGCATTCTCGGGACATTAAGATCGACTGCTCTTGCGTGCACAAGTACAGAGCCTTCAC
          GTCACTTCCGTTGACCCTTCAAGGAGGTGTGCACTACGGATGAACTCCGGAGGTCGAGAC

          TCCTAATAACCTTGGGGAACCTCCGTTCGGATAATTAAAA
          TGCTACTAACCTTGGGGAACCTCAGTTCGGATAATCAAAA
          TACTGTACCTTTCAGAGACCCACAGTAGGGGTAATCGGCT
          CCCTGTTAGACTAGCAGAACCTTAATCGGGGTAGTAAATA
          GAGTGTCATTCCTGTTACACCCCAGGTCAGATTCTTTGAA
          TACCCTCAGTTTGGCCTAACCCTCCCATGCAGCGTCCGTC
          TACGCAAAGCTGGACGAAAGCCAAGTTCCGGTAGTCCCTT
          CGCAGAAGTACTCATGCGTATTATCAAGGGGACAAATATC

