 8 1000
t1        CCGAGATGACTCTTAGCAGAAGGTGTCAGAATCAGCGATTTTGTTTCATACAAAAAGGGG
t2        TTGGAGTTCCAACTGGCAGGAGGGGCAGAAACGGCTGGCGTGGTATTGTAAAAGCCGGTT
t3        CTTAGGTGATATTGATCAGGCCGTATCGCCATCGTTGGTCTCCCCATGTAGAAATCGAGG
t4        CTGGGGTACCTTATAGTAAGTGGCAGCGACTTGGTCGGTCAAGCTACGTAATCAACGAAA
t5        CCGTGGCCTCAGACTATACGCGACTTTTATACAAATGTCCTAACCCTCTTTATGGTGGAT
t6        ATATGCAGGTCAACTGTGACGAGTCTCCAGACTACTTACCACGTTACCTCTGCATCGGCG
t7        TTACCGCGAAAGTCAGACGTGAGTCTGATGGAGAGTGCTCTTGCCGTGTCACTACTGAAG
t8        TCTGGATAGTACCCAGGGAGAAGTGCCGAGAAATACGGCCCTGTTATGATTAAATAATAT

          GCGAGAGCTATTGTCATAGGGGTGCGTGGGGGTATATATCCCACAACGCTTTCGAATATG
          GTGGGGGACATCGTGTTAGAAGTAAACCAAGATATATGACTGCCAATCACATCTAACAAG
          GTGGGGCTTTTTTACGAGGACGACAAAGCAGATATTAAAATCTTTTAAAAGCTCTATGCA
          GAGGGGGATTACGTCAAGAGTTAGTATAGAGCCGTTCAGAATTCGTCTTCACCTAACCTG
          GTGAACGCCGTTACGAGCGTCTCGAGTCTACATATATTACTCCCTCCACCATATTTCATG
          GGGAAGAACCCAGGGAAATAAGCGGGTGTGACTGTCTCGAGACCGTAGTCGTTAGGCAGA
          GGTGATGACCTGGTATATAGAGAAAGTGTGAGTCTCATAGTCCCCCTAACCAGCCAGAAG
          TCGTGAGATCCGGCCGGTTAGGGAGTCCGGACTATCGTAGTACTCCTGGATACCTGTACA

          ACTAGTCATTAACCCTATCCCCAGGTCCGCCCATATTTCTCCATTGGATGGTGCCTACTG
          TCCAGTTGACCTCACCTTTCACCGCTGCGAAGTCATTCCATCACTCGGTTTAGGTTCCAG
          TGCAGTTAATCACTTTGTTTAGGACCATCTCGCCGTGTGATCTCTGGGACCCCATGTGGG
          AGCATTTAGCGCCGACATCCACCTCGGCCCTACTACTGCCCTACGAGGTTCAGGCTCGGG
          TGGTGTTGCCTGTGTATCAGAAAGCTCTGTTAATTCTTTGTTACGCGGAGTTCAAAAATA
          CGTAGGCGACGTGGACAACTAGAGCGCTACAGCAATCCCAAGATATTGCACCATTGACGG
          TCCTCTCGTTTATCTCACTCACGATACAGTCCCACCTTCAGTTCGTGGCTTTCGGGTGGG
          ATCTAATCTAACCGTTCCTCACTGACGGGCCGTTATAGTGGTATATGGCCCATCTTGAAC

          GGCTGAAGTCATTGATCAAAAAGGTTCCCACCGATCCATGAAAATTTCCTGCCGGAGTCA
          GGCCCAAAAACTGCTCTCAGGGGCTCTCTGCCTCTCAAAGAGATCCCTTCGTTTGGATTA
          AACTTGTACTTCTTATCTGAAGTCCTCCTACGGTCTCAGAAAAGCATCTTCTTAGACCAT
          TCTGTTGAATCCACGTCAATAGATCTTTTGTAGCCCCTCGAGAGTTTTTTGGTGGGCTCT
          GGTCTACACTCTTCGTTCTGGTCGTTCTCACTGCCTTAACTAAACTTCCCCTTTGCGTTA
          TGGTTGTAACACCTCTTAAAAAAGACCCTTTGGTTCTGAACAATGATCCGATAAGGCACG
          AGGGGGTATCGTTTATTAACACGGACTCGACATTAACAAAGCAGCCTCGTGTTACATAGG
          GGAGGGAGCGATCCTCCAATACCAATCTCCTAACGTCAATGCAGTTCCATACACGATTGA

          ATCTACAGCTTCACTTGTGCTCTGCAATCGACTTAAGGCATCACTGGCAGAAATGCAGCA
          GTATGCTACGTTATTAAAGGTATTCGTCCTACTTGTGACACGAATGGGTAAATTGCGGCC
          AGATGCATCGTCCTACGAATTATTTATCCCGCTCTGGGTATTATTGGGTCGAGTGCAGAT
          ACAATCTTCATCATACCTACTGTCTACATCATTTTGATAACACGTTTCACAAAATCAGCC
          ACACATCCTCTTACCTGCGCCACATGAACAATTCCGGGTACCCCTGAGAAACATCTAATC
          CGAAGTGCATGAATACGAAACTCCTGCATAACCTAGAGCCCATTCGAAGAAGTTCTATTC
          ACATGGAGCATCTTTAGCGCCACTACCCCAGGGTGTTAAACACTTTGAACGGGCTCAGGG
          AATTTTTACTCATGCTAATGCATGGGATCATTACACTACAAATAAGAGTCGGGCAAGGGT

          GCCTACGTGGAGCTATATTCAAGGAGGAGCTATACTCGGGGTTATTCTGGTTGTAATTCT
          ACGCTCACGAGGCCGAATTTAGGAAGAAAGTGTCCTGGAGATCATCATCATCCCATCTCC
          ATGCCAACGGAATTCCGTGACGGGGGAGGCAGAGCCTCTGCTAACATTGATCACTATTGT
          AATTTTACGAAGCACTGCGAGAGGAATTGCTGCGCTACGGCTGGTTCCAGCCGTTGCTGG
          CTTACCCCGGGGCCCGGCGTTGAGTAACTCGGCCTCGCGGCTTGCTCTTGATGCTCTGGC
          GTCGTCGTGGAGCGTCGTGCCAGCCGTGTTTACATCCCGTTTTTTCACTGAAGCCGCTGA
          TGTTCTATTATCTAGTGAATGGAGGTATCTTTTGTCTAGCATCGCTTGTTCCTTCTCTGT
          ATCGTCGTGTGCTATTATGTGGCAAATGTTTTCAGTTGGGTATTGAAGTGTGGTATCGAG

          ATTAGCTCCGGCCTCGGTGAGCCCGCGAGCAGGGATATCGTTGGGCAGAATGCCACAGCC
          ATTAGTCTCGAACTTAGTCAGAAGGCAGCAGAGGACCACGTTGAGTATAATGTCACAGCC
          TACTGTATTGACCGCCTACCGGTCGCTGGGAGATATTCATCTGTGCATGGTCTTACCTTT
          TCCCAGTTTAGATTCCTACGGAGCTCAGCCACAGCTCGCATCGTGCACAATGCGACACCT
          TGGCTGTCAGGATTCGAAGAGTATGCCTGCGATGATGATGTCACGTCCAATATCACACAT
          TATTGTTATGGAGTCATAATAAACATATAAGAAACGACCGCCTCGAACAGGAAAGCCGCT
          CCCTGCTTTAAGTACACAATCAGCCCGTGGGGACATCCTGCCGTTCATAACAACAGGTTC
          TCGAGTACGGGCTGACTACTAAAGGCCAATCCCGCACATGATCCCACATCGCAGTTACTT

          ATCGAGGGGCTACGGAAGGGATTCCCGTCTTGACCTGTGTAATCAAAGAAGACGGCAATC
          AATAATGCCCTAGCAAAGGGGTTAGGTTCTCGACTCATGCGAATCGCACACGCCCCCCAA
          ATAAATGCGAGGGTCATCAGATTCTATCTAGGTTATACGTCATTTGAATGATAAACTCGG
          AATGCCGAAGTAGGGCAGGGATGTTACCATAGATCTGAGCAATTGAAATGAAACACGCGA
          CATCAAAAGGTACATAGGTATACACATCTTAAACGCGCGTAAGTGGTTTGGCATGCTCCA
          TGCAACGCAGCAAATGAGGAGTGCTTGCTTCTTCGCACTTAGTACAAGAGGAACCCTCTC
          CCAGTTGGAATGGCGGAGGGACAATCTGTTGACCACGCGCTATCTTGACGCTCGCTCTAA
          GAAACTACAGGAGATGACGGACAGCTTCCTGACCATATGGCATTAAAGAACAGCGCTTCG

          ACATGGTCTGGAGCGGCAGTGTGGCTCACTCTTCTGCATGTCTGCCTGGGAGGTCCTATA
          ATATAGCCCAGACTGGTAGAACTGGTTATTCTTTAGTACGACAGACAAAGAGGAAACTTC
          CTTAAACCTATTCAGGCATAGCTAGCTAGTCTAAAGAATGGACAGCCGAGATGTTACTTC
          TGATGAGCTGACCTTAAAAAACTAAGCATGCTCGCGAATTGCAGCTGTAGAGGCCAGATT
          AACCAGCGTACTGAGGCAAAACTAGTACTTCTAAAGATAAACCGGCTGGTAGAATAGCCG
          ACATGGCCTTAACTAACGCTGTAAAGCTATTAGGGGAAAGGACAGCCAGTTTGCTCCACC
          ACGCAGACCTCAGGTCCATCGCTTGTCGATTAAACGTGTGACTAAATTCCTTCATAAGTC
          TCGTCAACGGCCGTCCCCGCTACCACCCTTTGCAGGAATGATCCAGTTCAAGAAAAGACC

          GCGAGTACGAATTGGGCCTTGTGGGTCGAGTATGGCCATGTACATCACAGAATTTTACCA
          GAAACTTGGGACTTGGCCTAACAGATCGCTAGTGACGGCGTGTATTTCGGTTCCTTACGG
          GGAAATACGGGCTAGGTCTCATAATTCGATCATTCCTTTATGTTTCCCCGATGTATTACG
          GGGAGCTCAGGCTAGGTTTTACAGGTTGGATATGAGCAAGTGAATAACTGCTGCTCGTCT
          ACGGGGACATGATGGGTTTCAGCAGCGATGTATAGTTCTACGAACACCAGTGACCGGCTG
          GCGCGATTAGACCCGACTTGATAGGGGGGACCTCGCCGTTCGCCCGTCGATCGCCTTTCG
          GATCACGTCGGTTGGGTTGATTGGACTCCGTTTTGCAATGCGTTCGTCGGCCACCTCTCG
          AAACGCGTGAATTCGGTCTCCTTAGGCGGTGTGCGTTGTGCGTCTTGCAACTGCCACTTG

          GTCAATCCACCCCCGGCGTGAGACTGGTGATCGGTACACTATTTAGGGGATAGGGGGTCC
          GTTGGTGACTCCTTTCTGAGAGAGACGACAAGGGGCCACCTTCTGAGTTGCGGGGGTGTT
          CAACGCAAGACCCTCGCGGGTGTCATGCCGCCGGTCCACTTTCCGGGGGGCGGGAGTATC
          CTAGGTAGACCTATGACAGAGGACAGACCAACAGTACACCCTTTGGTCGAAAGGTATATC
          GTAAGTCTAACTCTCGCTGTACATACCACAAGTGTCTGTCTCGTTAGGCGTCTGCGCATT
          CTTCGTAAGTCAATCGGTGTGGATACGCCTGCGGTGTATCTTCAAAGGGACTGATGTGTG
          TCCTATGCATCTACTGTCGTGAATTGTACATTAAATCGGCGCCTGTCTTGCGGGATTAAG
          TTGTGACGATCGCACGACGACGGCAGTCGGGTGGTACTATATGCTGGGAGTGTGCTAACC

          CCTTGCGTAGTGGCGCCACAGCCCGTACACATCCGGTCCAGATGTTCGGGACCGGAGAGC
          CATAACATGCACATATCACAGAACGCTTATCTCGAATCGAACTGGTCGAGGTCTCGGAAT
          CGTTTAATGCCGATCTACCACTGTCCTTATACTTCCCCTGGTTGACTACGCTCGCAGAGT
          TGCAACACGCTAATCTCATCACAATTTTGCATTCTGTCGACCCGTTAGCGTTTTTAGAAA
          TGGTGTTTGTTAATCTCAAAACCGTCTACTGCCCCAACAAGATTATAAAGTATTGCAACT
          GCTGATAGCCAGGTCACGCGCGCTTTTCAGGCAGGGCGAGGATGATTGAGTGATTCGCCT
          CATTTAGGTCTAAGGGGAACTGCTCATTGGACAAGTCAAAGACAGCCCACTATGCCAAAT
          ACCTAAGAACACGTTCCAAGACTCCTGTGAACCGTCTGGAGCTAGGCTTGAGCGCACGGC

          CGACATTGGCTAGTAAGGACCCGCAATCCCGCGACATGGCCAATGGAGACCTGCCCGAGA
          TAATCACGACTGGAATGGGCCAGCGATACCGCAGTTCGGACAGCAGTCAACTGGCCTCGG
          TGATGACCCGTATAGAGTCCTGACTGTGCCCTTGCATGAGCTTTGCCACCTGGGCAAGGG
          CACTTCTAGCTCTTAAAGGCCGGGCATATGGTAACACAGATACCTGCCGAATGGCCATAG
          CCCAAGTAACGATGAGCCGCCGGATCCCTCGTCGTCCGGGCATGGGCCGAGTAGTTTCGG
          CAGGCGTCACGATCTATACACAAGCATATCGTAGTGTGACTGTCAGAGATTCGATGAGGG
          CTTACGAAATAGCAGAAGGCAAGGCGGGTAGAGATTGAGACCTTCGTCGCTAGGTCGAGA
          CGCGGATGAATATGAGAAGATAGCTAGACCGTGATTCCAACTCTAGACACATGAGAAAGC

          GTAATACCACGATGACGAGCTCGCACTATGTATAAAGTTACTAGTGTAGGATACTGACAC
          GAAGTACAAGCAAAGCGCACTAGTTTAGTCAGCATAGTTGGGCCATTATGGCACTGGAAC
          AGGGCGTTACACCGACGTGTTGGATTACAAGTCAGAGGCGTGCGAGGGCTTAGATGCAAC
          ATAGAAGTCACATTTTATGCCACACCCGCGGCTAAAGATTCACGGATACAGTTGCGGAGC
          GTATAGCATGCGTATCCCACAAGGGTCGCGACGAAAGAAACAGCTGCACGAAACTGGAAC
          ATAAAACGGGCGCGCGACGCGAGACTTATGACCCGAACTGTACACATATTATGGTTCCAC
          GCTCGTCCATTGATAAGCACCAAACGGTTCAGCCGGGCCGCGGAGATGTGAAGGTTGCTC
          TACTGTCGCGATTACGCCATTCTTCTAATAAACCGTGATATGGAAGCACAACAGGCGAAC

          GTCCCGTATTCTCTGAAACCTGATAAGCCTTATTAGTGAACAGTGTTATCTAAATAATTG
          CGCGCGGCTACTCTAAAACCCGATATACCACCTCGGCGGACGACGGTTTTCCGGTTTACG
          TCAAGTGGCTTTCGACAAGCTGGCCTAGTAAGGCCCCGGACGGCAGTTTTTCGATTGACC
          AACTTGCACACTTCGAAGAAGGGCCCGATTACTTGAGGTATTGTCGTCTGTAGATTAATC
          AGCCGGGGTTAACTAAAACTGGGACCATCGGTGCAGCACTTAGGGGTCCTAAGACCATCC
          ATATCTGCTTCCCCGCACACTGATGAACTCTCCATGCGATATACACCATCTTAGCTAACT
          ATTCCACATTACCTGTCGTTCTATCTTCCGCCGAGGTGGGCAGCTTCCTTCCGGCCTACT
          AATTTAGCCATCCCTCCATCTGTCACTCATCCCGGATGGAGACTAGTCTCAATTCCAACC

          ACTAGGATGGCCAAGACGTTGCTATCAGACTTTAATCTGAGAATACGGGAGAAGGTCAAT
          CCCTGGAGGGCAGAGATGTCACTGCGAGTACCTTGATGCAAAGTACAGTATGAGGACGAT
          ACGTGAGTGGCTGATCCGACTCATTAAAATTTAAAGGGAAGTGAACAACGGGTGGGCAAA
          ATCTGCAAGCTCGGGATGTAACTGCAATACCCTTGACGAATGGCAAAGTGTGGAGGACAT
          ATCCGGTTAGGCTGAATGTCATCATGGAATTCAGAAACGCACATAACATCTGAAGGAATT
          CCTTTTATCACCGCGTCACCGCTATTCAGTCCTTGTCAGTACAGAGACAAAAATTGAAGT
          TCTGCGCCAGGTGGCCCGCCCAACCAGCGAGTCACATAGTGGCGACGATCCTAAGACGAC
          ACTTAAATGACTGGCACTCTATCTCACGACTTCGGATACACAGTGCGCCTGAAGCTGAAC

          TGGTTGTCGAACGGTTCGGTAGTACGCGGTTGCGTAAGAC
          TCACTGTAGGGGCACATTGTGGTTAGCAGGTTTGTGTGTT
          CGGCCGTTGCGAGGTTTCGGAGTTAATAGTTGTGTCTAAT
          TGGTTGTGACAAGGTTTTGGAGTGTCCGGATGGACGCGGC
          TAACTGCGGTACATATCTGTAAGCAGTAGGTGGGGGTGGT
          CGGCCATGGCCAGGTGCCGCAGTCAATCATCTTGAGCAGT
          ATTTAGTTTAACATCATGTTAGTTAGTAAGTAAAGCTGGC
          TGCCGACTGGACAGTCCAGAGGTTGTAAGTACTGCGTAGC

