 8 1000
t1        GGCAATCGCAACAATGCTTCCCGTAAATCGACCCGCGGGGCTGTGGAGGGAGGGGCCTCA
t2        GGCGATCGCAACAATGCTTTCCGTAAATCGACCCGCGGGGCTGTGGAGGGAGGGGCCTTT
t3        TACCCCTGCAGCGGCATGCGCGGCCGAGAGCTCTCGGCAATCGCACAGCCTACAGAAACG
t4        CTAATCCGCCACGCCGCACGTGCTCTTGTGCTGCCAACGGTCGCATATTTCGTTGAAACG
t5        AATACTAGTAACCCAAAATGTGGCTATTTGACCAATCTGGCACACAGCCTATACGGTGTA
t6        CATACTAGTACCTCAAAGTGTGGCTATTTGATTAATATGTGACTCAGCTAATACGGCGTT
t7        ATTACCCTTAGCGGGGTCTGACACTGGTCCACCAAAGCGTTATTCGGTCAAAGGAATACA
t8        TTTTCTCCTAGCGCGGAGAGCCGGTCATCGAAAGAAACGTGAGTTATCCCGTCTGATGCA

          CTTCTTGACACCCCATAAGAGTCATAGGTCAGGGGCGGGCTGATAAGGGCTGCCGAGATA
          CTTCTTGACACCCCATAAGAGTCATAGGTTAGGGGCGGGCTGATAAGGGCAGCCGAGATA
          TACTCTCCTAATTCCGGTAGAGCGTAAACTGATCCTACATAAGGATGAACTGAGTATGCC
          GACCCTCCTCACTCTACTGGTTTAAAGATAGTGGGTATACTGGGGGGAACCGGGTATGTT
          CATGATCCGACAACTAAGTGATTACAGGGTATACGGTCGAGCGATCCTATGATCCTCACT
          CATGATCAGACAACTAAGTGACCACGGGGCACACGGCCGAGTGATCCTAAGATCCTCACT
          TACCGCTAGAAAGGCCGGTGACCGTGGCGCGGAGGGGTGTATAGGTCCATAATTGACTAG
          TCCAACTTGACACCCCGGTACTGGTAGAACGAAAGGCGGCGAGGGTCCAAGACCAGTGGA

          GGCCTCTGTCGCAACTGCCGCTCTGCCCCCCAGTGTCGTTAGGATCGTCCGGGCTTTCAC
          GGCTTCTGTCGCAACTGCCGCTCTGCCCCCCAATGTCGTTAGAGTCGTTCGGGCTTTCAC
          GAGGCTTGGTGCAATGAATAGCGAGCAAACCGATCCCTCGGGGATTGAATCTATACATGT
          GAAGCGTAGTGCAGCACCGAGCAATAAATCCAACTTCGCAGGGTCCGATTCTACATATTT
          GGCCGCGTCAAAGGCAACGAGGCCTAAAGGCACCCTGAAAGGGATCGTCAATTTGTCATT
          GGCCGCATCAAAAGCAATGAGGCCTCAAAACACCCTGAACGGGATCATCAATTCGCCATT
          AGCCCGTTTCGACGTTGATCAGAGCCAAAGCCACTTCAATGATTTCTTCTGCTAAACTCC
          AGCTGAAAATGATATCGAAGGCATTCCAATTTATATGCGCCGGAGCGCCTAGTGACCTGC

          TAGTACATGGTTTCTCACGCCAAGGGTCCCCTCGAACGACCGACCAGTGGTACCTTTCGA
          TGTTTCATGGATTCTCATGCCAAGGGTCCCCTCTAACGACCGACCAGTGGTACCTTCCGA
          ATCCACGAACTAATTTATGTAAGAGAATCAGATCTTCGAGTAGAAGGCGCCATCTAACGG
          TTATGGAGACCGTTATCCACAAACAACCTACATGTGTGTGCAGAAAGCACATGTCAACGG
          GTAAGACTGACAATGATCGAAAAAAGCGCAATCGTAGCGAATCTCTGCGCTGTCTAAGGG
          GTAAGACTGACAATGATCGACAGAAGCGCACTCGTAGCGAATCCCTGCGCTGTCTACGGA
          GCAAGTCAAGTATTAACAAAGAGGCGTCCAATCCCAGGGGCGCTCTGCGCGTGTTTAGGA
          TTAGGTCAGCCAGTTGTAGAATGATGAACGCGTGCGGGGAGCCTGCACAACGAGCTCGCG

          ATGTGTCTGGCGAAACCCATTCTTCCGCGTCGAGGACAGGTATGCAGAATACCTATAGAC
          ACGTGTCTGGCGAAACCCATTCTTCCGCGTCGAGGACAGGCATGCAGAATACCTATGGAC
          TCATGGAACACCGATGAATCTCTCGTCCGCTGGCAACGGCTCGGCTTGTCTGTAATTGCC
          TAGTGAAGTATCGATAGAAGCTCTGTACGCCCACTTCGACTTGGCGCGCAAGTGAACCTC
          GTAAGTATTGATAAAAAGCCTCCGGTTCGTTCTGGGCAACTCTAAGTGCACATGCATGCC
          ATGAGTATTGTTAACAAGCCCCCGGTTCGTTCAGGCCAACTCTATTTGCACATGCGTGCC
          GCGAAAGCTACTAGCTTCATTTTAACCTGCCTAGAATAGGCTTGGGGTTATTCGCGTTCT
          GCAGAGGCATGTGAAATGACTTTAGTCCCCCCAAAACAAGTGAGAGAAAATCGTTGTAAG

          GAAAATAAAGTAGAGCTTTATATTCGATAGTAAAGCATTAACGAAGCGCCTGCACTGTAG
          GAAAATAAAGTAGAGATTTACATTCGATAGTAAAGCATTAACGAAGCGCCTGCACTGTAG
          TCGTCGATAGCAGGCACTTTCAACCTAATTAGAAGTTCGACCAGAGTTCATGTTGCCCAG
          TCATGACAAGCAAATTTCTGGGGCCTTACGTAATATCCGACTAACGCAGGAGTTGCCCAG
          TCTAGGCTTAAGGCGTGTCATAACCCACAATACACGCCTATCAGAAACTGCGTCTGATTG
          TATAGGCTTAAGGCAAGTCATATCCCACAAAACGAGCCTATCAGAAACTGCGTCTTATTG
          TGGAGTTCTGCGGCTGCTTGTAGTTTCCACAATAGACCGTTTCAAACGTCTACCGAGTGG
          TGACCGTTGGCAACGTCCCGCGACAATCAGCACGGTTCCATTAAAGTATGCTTCCTACTA

          AACAGGATCGGAGGATAGCCAGCGTGCCGGCCCACCGACTATTACTTCTCCCATAAAGCC
          AACAGGATCGGAGGATAGCGAGCGTGCCGACCCACCGACTATTACTTCTCCCATAAAGCC
          AACCTAATTGTAGTCTAACCCAGTTGCCGGAAAGACGACTAGTATCCGGGTCGTGAGGTA
          GATTGGCTCACGATCAAAACAAATTGCCGGATACAAAATTGAAATAAAAGTCGTGACGTA
          AGAAGAAAGTTGTTCCAGTCGTAATGGATATTTAGCACTATGTAGCCTGTATTAGGAAGG
          AGAGTAAAGTTGTTCTAGTCGTAACGGATACTTGGCACTCTATGACCTGTATTAGGAGGG
          ACACGTACCCATACTTATCTGAAACGCTGGCAGGCGAGTTGGAGTTTTGACTCTAGATGG
          AGGTCTTTTGTAACCTAGCTAAACCGTTCATTGGGAAGTTGTTAGCTTGTGTTGGGTTAA

          TAACTTCAACGCCTCAGGCCTAGAATGGCGTCTGTTGGTGATTCACTAGACAAGCGCGCT
          TAACTTCAACGCCTCAGGCCTAGAATGGCGTCGGTGGGTGATTCACTAGATAAGCGCGCT
          ATTAATCGCAACTTAAAAACCCGCGAACCGGCTTTGAGGGCAAAGCTATCTTCATGTTGT
          ATGCGCCGCAGCAGTCATACAAACGAATTGACTTGTAAGAGATAATCCCCCTTATTCCGC
          ACACTCGACCCCCTCAGTACAGGTCCTTCGTCGCCTATGCAGCGGCCTAATTAGCGTCAG
          ATACTTGACCCCCCTAGTATAGGTTCTTCATCGCCTAAACAGCGGCCTAATTAGCATCAT
          CTGACCGACCTTCAAAAGTCAGGAGACTCATGGCCTGGTCCTATGCTAAGTAAGTACTCA
          CGCCTGGGCTACTCGGACTCAGGGGCCTGATTGGCCGGGAAGCGGCCAGGTCGGAAATAC

          AAATCTAAAATTCCGTTAGATTGGGGAGACCGAGAGCCGTTCTGTGCCAGTTTACGGCAC
          AAATCTAAAATTCCGTTAGATTGGGGAGACCGAGAGGCGATCTGTGCCAGCTTACGGCAC
          TCCATATGCTTGATCCTATCAACGTGCGCGCAGGTATCCCCTTAAGAGGGACTGCTATAG
          GGTTTTCACCGGATCAATCTCATGAGGTGGCATCGACTCCCTATAGCTGTATCGTTTTAA
          AACTCCCAGGCGTTTTAACATTGTTCGAATTGGCCGTAGATTGTACTATGCCAATGAACC
          AACACCCAGGCGTTTTAACATTGTTCGAATTGGCCGTAGATTGAACTTTTCCAACGACTC
          ATTTTTCTCGCGCTTGAATGCTGCGGGGGGGGCGCGTAAGTTATTCTGCGCCGAAGACTT
          AGTATTCAGTTGCCTTACTGTTGCGAAGATTGGGCTTAGCGATCAGCGTGTTTAAGAACC

          CCGGGTTATCCACCTCCCAAAGGGTCACACAAGCTCGGGTCCCCCAGCAACCAGGCTGGA
          CCGGGTTATCAAGATCCCAAAGGGTCACACAAGCTCGGGTCCCCCAGCAACTAGGCTGGA
          ATGACATAAGTTTTTGGGATGAAATAACACAACAGGCTGGCGCCAGGACGTTCAGTTTTA
          ATGACACATCCATTAAGAAAGGCATAGCACGACACGCTGGTAGCTAGGTGTACGAACCTG
          ATGAGTAACATTGACAAAACGAGCTCGCTTACGCTAGACTTCTCCTTAACTCCAGGGTCG
          ATAAGTAATACTGCCAAAACGAGCACGCTTACGCTAGACTTCTCCTTAATTCTAGGGTCG
          GCGAGTATTAACGCTTGAAAGGAATCGCCTAGGGTAGCGATGTCCTCAGCGATAGAGGAG
          TGTGCAAGCCACGATGGTATGAACTCGTAATGGTCAGTCTTCTTCCCAACTCCAGGGGTG

          AGACGGTTTGCGCAGGGTTAGGCACATTAATATTACCGTTGCGCAAGTGGTCGCCAATGT
          AGACGGTTTGTGCAGGGTTAGGCACATTAACAATACCGCTGCGCAAATGATCGCCAGTGT
          GTACCTACGAGATGTTATTCATACGGTTGCCGTGTATGCGTCGTACCGTAGGACTATCAT
          AAATGAATGACTTGTGCTCCATTGCGACTTTGTATATGGCACGAGCGGCAAAGCTGACGA
          ATACGGCCAAGATGTGAGTCCGCCCGATCTTCAATACGAAAGTTAATGGTTAACAGTCTT
          ATACGGCCAAGATGTGAGTCCGCCCAATGCGCAATACGAAAGTTAATGGTTAGCAGTCGT
          AGGCAATTAACACACGAGCCAGTCTAAAGTTAGATCTGGGGCTCGGAAAGTTCAAAACCC
          ACTGAATTAAGTATTGTATCAGTCTGAAGTACAAGTTTATGCTCTGACGGTTTAGGGATC

          CAGCAAGGGAAAGGTTCCTAAGTAAAGCCTGAATAAGCTTGGGTTGCAATGACCCGCACA
          CAGCAAGGGAAAGGTTCCTAAGTAAAGCCCGAATAAGTGTGGGTTGCAATGATCCGCACA
          GACGGAGGGAGGGGTGATCGCATCGGTTCAACTTGAGTAAGATTTACTCGACCGGTCGAG
          GTCGGTGGATGCAGAGACTGCTGCGATACATCTAGAACGGATTTGGTCCGACTAGATAGA
          GAGGGAGAAAGGAGCAGACCGACTATTTTCAAATTGACCCGATCTGCGCTGGCTGGTCTA
          GAAGGAGAGGGGAGTAGGCCGATCATTTTCAAATTAGCCCAATTTACGGTGGTTGGTCCT
          CTGGACGCCAACCGAACCCAGGTTGTTTCAAAAAAGGTGTGAACCCCTCTACGTATTCGG
          GCAGGGGAGAATGTTAGTATGCTCAGTTTAGAACAGATGCTAAGGACAGTCATTCCAACG

          CTCTAGAGACATTGATAGAACTCAGCGGGAGTGTATCCGGTACTAGACTGCGGGTACGCA
          CACTAGCGACATTGATAGAACTCAGCGAGAGTGCATCCGGTACTAGACTGCGGGTACGCA
          AGCATGGGAGTGGCTTGCACTCAAGCTGATGTACGATAGGTCGCATTCGGTGAACTACCG
          AGTATAGGAGGTGTGTAAGTCCTAAAAGTTGCGCGACTGAGAGCACTCGGTGAATTGCCG
          TACAAGCGAGATCGACTGATGACACATAGGAACGCGACTATAGTTATTGCTAAATCATCG
          TACAAGCGAGATCGACTGGTGTTACATAGGAACGTGACTATAGTTATTGCTGAACTATCG
          TGCATGGGGGGTGGGAAACTAGCGCATATTTAACCGAGGATAACCCCCGGTGCGAAGACG
          ACCCGTTCAGACGGCTGCTTCGTGTCCGACTATTTGGCCAAAGCATTGGAGGAAAGTCGG

          ACGTGTAATCCGTAAATTGCAGAACATAGACACCTCCCGTAACAATGAGAAACCCCTATT
          ACGTGCAATCCGTAAATTGCAGAACATAGACACCTCCCGTAACAATGAGAAACCCCTATT
          TCATCGAAACTCGGATCCAGGGGCGATCTCCACTTGACAGAACACTGGCTACGAGAGTAC
          CTACCCACATCTGGTTTTGAAGGGTACCGCTCTCTGATTTAAGGCTAGCAAGACAGGCAT
          CGACCAAAAGTCCTCAATCCAGTCGCGCAGAATGGAACGCGCTACTACTACGTCAATGGT
          CGACCAAGATTCCTTGGCCCAGTTGCGCAGAAGGAGACGCGCCACTACCACGTCAATGGT
          CACACGCAGTGTGACACCGTGGATGAGTAGCACAAAGTGTAGCGTCGATGAATCTTCGTC
          CATTTAAAGTTTGCATCCCTCTATGAGTAGAACGAACCCTGCAATCGCTAGACCCTAGAT

          GCTGAGACCCGCTAATGATAGAACCACTACCATATGGAGGACATAGGCCGATGGGTAAGA
          GCTGAGACCCGCTAATGATAGACCCCTTACCATATGGAGGACATAGGCCGATGGGTAAGA
          TCTCACGATTGCATGGCCTTAGTATCTTGCTTAGGGGAGACGATCAGAGCAAATATTAAT
          CCAGGCGTCCACATAATATGGCACTACTACTCAAGGGGGATAGTATACGTCATAGAAGTC
          GCTGACGATGTTAAGTGGTATATTCCTTATGCTTCGTTGGAACGGGGTGCGTCAGTAGGA
          GCTGACGATGATAAATGGTTTGTTCCTTATGCACCAATGGAACGGGGTACGTCAGTAGGA
          GTACGTAAAGAGATGGGGGACGCCTTTCATACAACTGAGTAGGAACGCGTGGCGGGAAGG
          GCCCATGTCGACAGTGAACCCGCTCCTCATTTATCACCTGTCATGGGCATCCTAGCCGAA

          TAAGCCTGCATGCAATATCCGGAGAGGTAGCCTGGATAATCGCTAGATTAGCATTGAACA
          TGAGGCTGCATGCAGTATCCGGAGAGGTAGCCTGGATAATCGCTAGATTAGCATTGAACA
          AGGTCGTAGGCAGGGGACGTGGCAGAATATTGTGTGACACTGTCCTGGTAGGACCCGAAC
          AGGTTAAGGGTACAAGGCGTGGCTAAATATTTCGAGATACCGTTTTGGTAGCCGTTATTT
          TAATCATAGGCGTTGTAGATGTCTCGTCAGCTCGTGAACTCTTCGTGCTAAAAATTAACT
          TAATCATAGGCGTTGTAGATGTCTCGTCAGCTCGTAAACTCTTCGTACCAAAAGTTAACT
          CGGCAAGCGGTGCCGGATTTGCTAGGACGGTTGGACATACTCCGACATAAGTAGTGTGTT
          TGGGTATGGGTGCCGAGATTGTCGGGCATGCACGCAGGCTCTCCAAAATAGACGTTAATT

          AAGCGGGTTATCCCTATATTCTTAGTCGAGAGCTCAACTG
          AAGCGGGTTATTCCTATATTCTTAGTCGAAAGCTCAACTG
          AGAATAACTAACGCTTCGGCGCCGGACCCGACTAAAGTGA
          GGAATCGTGACAGTTTCAACGTCGGGCTTCTTCAAAGTAG
          TGGTATGCGCAGCCGTCATCGTATATCGGATCCAAGCCCG
          TGGTATGCGCAGCCGTCATTTTATATCGGATCCAAGCCTG
          GAGTTCTCGCACCGCTCCCAAAAGGGTTATTTCAGCCTAG
          CGATTTACCCACTGCCCCCCCCGGAGTAGTCCTGAAGTGG

