 8 1000
t1        GATGTGTATTCTTTAGTAAATTTCCTCCACAGAGCCGTGAAACCAGGCACTTTCTCTGTA
t2        GATCTATATTTGTTAGTAAATGTTTATCACAGGACCGCGCATTTACGAACATTCCCTGTT
t3        GACTTATGTTTACCAGTAAATGTCCTTCATAGACCTGTGCATTTACGCTGATTTCCTACA
t4        GACTCATATATCTTTGTATACCCATCCCTCAGAGTCGCGCATTCCCTCGTCATCTTTACA
t5        GCCATTTATATCTAAATTTTCGTTGTTGATCGTGAATTGTCCTCGTGATTACGTATATAT
t6        GCCATTTATATCTAAATTTTTGTTGTTGACTGTGAATTGTCATCGTGATTACGTATATAT
t7        GCGTCGGCTACCAGGTCACGTGCGGAAAATAATAAAGAGTACCCAGGCTCAATCATAAAG
t8        TTTTCGTCGCTCGCCGCGAAAGCTATTAGCACCGTGATCTCGTCTAACTCGCGACTATTA

          ACACTTAGGCCACCTTTGCCGCTTCCGCTACTCTAGCCCACCAGCGCCGAATCTTAAAAT
          AGACTTAGGCCACCGTTGCCGCTTCCGCTCTTCTGAAGCTCCAGCGCTGAATCTTAAGGT
          CAACTTAGGCCACCGGTGCCGTTTTGGCCCTTTCGCCGTGCTAGCGTTGATTCTAAAGGC
          AAATTTAGCCCATAAATGATCTATCCGCCCTTCCTGGGCATCCATGATGTCTCCTCGCGA
          CAGCAACGAATGAAAGTATAGTAGGTGTCGTCCGGCCATCCGAGATATATTCAGCCTGGA
          CAGCGACGAATGAGAGTACAGTGGGTGTCGTCCGGCCATACGAGATATATTCAGCCTGGA
          TTTTGTGCGGTGTGGGGTAAGTTCTCGACTTTCCGTGAGCTCTTGCATGCTGGGTTAAGT
          GATCCTAACTCAAGTATAGAGACCTCGCACCCGTGGTAATTGATTCCCGACTCATTAGGC

          CCTTCAAGTCACAGCGGCTTGGACTTTATCCTTAAAAAGTACTCTTATGGCATCGATGTA
          TTTACACGTCTTAGCGGCTTGGACATTATCCCCAAAATGTAATCTTATGGTATCCACGAA
          CTTGCAAGTCATAGCGGCCTGGAATTTATCCTTAAAAAGTAAACTTAAAGCACCGATGAA
          TATATCGGACAATGCGGCCGGGGCTCCACCCCCAGAATATCACCCCAGGGCACCGATAGT
          TTTAGCGATCAGGATGGGGTGGGTTCTGCAGTTCTAACGCAAACCCATCGCTCTTCTCGA
          TTTAGTGATTAGGATGGGGTGGGTTCTGCAGCGCTACCGCAAATCTGTCGCACTTCTCGA
          GCAAGTAAACATTCAAAACTGAGAGTTGGTACTTAGCTGTCGTGATGTCCCCTCTTTTTA
          CCATTGAATTGTGCAGAAGAGGGGCTTTCTTTGTGACCATTGGCATGCGATAACGAGTCC

          GGGCCCCGCTGGACGGTCAGAATGGGGGTCTAATCGAGCTAACTACAAATTGCGAGCTTA
          GGGCTCCGCCGGGCAGTCGATTTGGGAACTTAATCAAGCTAATAACAAGTTGCGAGCTCA
          GGGATATACCGGATAGTCAGATTAGGAACCTTATCAAGCGGACAACAAATTCCAATCTTA
          AGCATATGTTGGCCAGCCAAACTGAGGACCATCTCAAGCTGGTGACAAAATCCGAGTCCA
          GACTCGCTACGGTTAACCAGATCGGAGATGACGTGAGATCGGCAGTATTAAGCGGTGTAT
          GACTCGCCAAGGTTAACCCGACCGGAGATGCCGTGAGATCGGCAGTATTAAGCAGTGTAT
          GAGCTCCACCATAAATCCCAGACTGGTTGAGAGCGATATTCCTCCAAGCCGACGGGGCGA
          TCCTGTTTTCAACACATCAGCATCATGGTTGCCCGTCGGCGTGCGCTAGGCGTAGGGCAG

          TATTACCTGCTCGTGGCCAAAATATCTGGACATAGGGTTCCAGAGTTATCCATAGTCGTA
          TATTAACCGCTGAAAGCCTTAATACCCGGACATGGGGTTTTAGAGTTGTCCGAAGACGTA
          ACTTAGTCTCTGAAAGTCGTAACACATAGCCAGGGGATTTTGGAGTTGGCCAGAGTCGAA
          TATTACCTCTTGCATGCGTAAAGATAACAACATAAGACTCTAAAATTGACTCGGGTCGCA
          CACGGTACATTGAATACTATCCCGCCATAAGACGGGACTTTTTATATTTGCAGGGTCAAG
          CACGGTACTTTGAATACTATCCCGCCATAAGACGGGACTTTTTATATTTGCAGGGTCAAG
          TTTCCCCACGAAAGATTCTCTAAGTCGTATCGAAGAGCGCCTAGGAGTTTTATGGGTCTA
          TCTCGTATCGCCATCCTTAACCCGTTGAGATACGGGGAGCGTTAGCCGTCCTGAGTTCGG

          CAGTAGCAGTCCCGACCTAGTAAGGCGTTCTATAAGTACTGACCTGTATCAACATGAAGG
          TGGCAGCTGTCCCGACCCAATGAGACGTCTCACAAGGACTGACCCGTGCTAACAATAGGG
          CGGCAGGAGTCCCGGCCCAGTAGGACGTTTGACAATTACCAAACTGCACTAACAATAAGG
          CTGGTCGAGCCCCGACCTCACAAAACGTTCCCAATAACCCCGCCCGAATATGCGACACGC
          CACCCAGGTTCCAAGCTATGGCAAGTGTCTCAAATATCGCCGAATGTTTCTACCGCGAGG
          CACCCAGGGTCCAAGCTATGGCATGTGTTTCAAATATCGCCGAGTGTTTCTACCGCGAGG
          ACTGCGGTTGTGGCCATGTGGGATTATTTCCAATCCTTTTTGCATGGCTAAACAGTAAGG
          CTCGCGGGGACTTTTGATGACATGCGGCATATAATTTCTGCGCTTGTAAACCCAAGGTGG

          AAAAAATTGCAGTAGCATGTATAGCGTTCTTATTTGCTAGTGTAGGGTTCTTAAGTCCCT
          AAAAAATCGCAGTAGCATGCATAGCATTCTCAACCGCTAGTGTAGGACTAGTATTATTCT
          AAAAAGTAGCATTAATATGCACAGTGTCTTCAATTGCTAGTGTAGGTTCTGTAAGATACT
          AGATAATAGCAGCAGCCCGTATGTTGTCATCCGCTGTTACTGCAGGGTGCGAAGGGTACT
          CAGAGCCTGGGATTCACAATACAACATCGCCCCACTCCCTTGTGAAGGAGTAAGCGTCAG
          CAGAGCTTGGGATTGACAATACAACATCGCCCCACTCTATTGTGAGGGAGTAAGTATCAG
          TTAAGGCTAAACAGTCGTGAAAATTGTCGAATAGGGTAATCAAGGAACGGTTGAAGTACT
          TATCGACTTCCAAAGCCAGAATAGTCATTCCGCGTGTTGTCGCAGCATGAGAAGCGATCG

          TGTACAATCGACCGTCCGGAGCTGTAGTCAGAGCATATCAACGACTATGCGTTCTGTTAA
          TGAGCAACCGACCATTCGAAGCTGTAGTTAGAGTGTATCGAAACCTACGCCTCCTGTTAA
          AGAATAACCAATCGTCCACAGTCGTTACGGGAGTGTGTCAGTGAATAAGCTCTGTGTTGA
          CGAACAAACAACCATCCGAAGCGGTCGCCAAGGTCTGCCGGAGTAGAAACTATGCGGTAC
          GATGCGAACCGTGATTTGGAAATGAATCTCGCGTATGTTATGTAAGAGGATACGCCTAGG
          GATGCGAATTGTGATTTGGAAATGAATCTCGCGTGTGTTATGTAAGAGGATATGCCTAGA
          CGAGACATAGGCTGTTGGTCCGTTAGATCCATTTGAAATCCACGAAAGAACTTACACTCA
          TATTCGATCGGTATTTTCTGAACGGATGTCGTCCATACTTTTCCGGGGTAGCGGCACCAA

          AGAGCACATGGGCTCAGGGTGGAACTAAGCTAGTTTATCGGTCAAAAACGCTGGCCCGCC
          GGGGCAGATGGATTCTGGTTGGAACCAAGCTAGTTTAATGGTCAATAATGCATCCCCACC
          GGAACATTTTGGCCCAGGGTCGAACTAAGCTAGCTTAACGGTTATTGATGTATGCCCATC
          GAGGACAATGGGGACACGGTGGAGCTAAGCTGGCCTAAAGGTCAGTACTGCACGCTCATC
          TATGTGCACGGGCACAAGACGGAGATATGTTGGTTGCACGACCGACGCTATATATCCCTC
          TACGTGCACGGGCATAAGACGAAAATGTGTTGGTTGCTCGGCTAACGCTATATATCCCCC
          TGATACCCCAGGAGGAGATCGAGATTCGTCTGGTACTAGGATGGCACTGGGAACTCTTGC
          CGAAAAGTCCTGCCGATGAAGTATCAGTTTAAGCGTTCTGATTAAAACAATAGTCCTCAT

          TGGGGATCAAGGCACGGATTTCTGGGGCAATTCACCAGCGGTAAGAACCCGTATGATAAG
          CGGGGATCAAAGCACGAATTTCTGGCGTGATTCACCAGCGGTCAGAACCCGTATGATAAG
          CGAGGACTAAGGCACAGACCTCTGGGGTGATTCACTAGTGACCAAAACCGGTAAGATGAG
          TGGGGAACAAAACCCGTCACTCTGAGACCATCCATTCGTGGACTAGACTCGCGGGATGAT
          CACGGAGCGCGGGAAGCAACTCCGTGGCTGTAAAGTCGAGGCGCCAGTCCGTTCTCAGTC
          CACGGAGCGCGGGAAGTAACTCCGTGGCTGTAGAATCGAGGCACCAGCCCGTTCTCAGTC
          TAAGGAGTGACCGTGGCATCGACGTAACGGGGCGGCCCTCGCAGGGAGTTGGACTGTTTT
          TAAGGCACTGAGCTTTGAGGCATGGACTCACTTGAATCTGGAAGTGGTTTTGACGTGTGC

          GACTAAGGTATCCCACCCCACTGGACAATCCGAAAAAAAGCCGTCCCTCATGTCGTTGTC
          GATCTAGGAATCCTATCTCATGGAATAATTTGAAAATAAGCCACCGCTAACGACTATGCC
          CACCTAGGAGTGCCCCCCCACTGGACAATCCGAGCCTCAGCTACCGCTCACTTCGTTGAC
          GGTTAAGCAATTACATCTTCTCGGACAACCCGAAAATGAGCCGTGCCTCACTTTCTTGAG
          GGCCTAAAAACTGTGTCCCCTCCCCAGATCCGATAATGGGCTGCTCCTCAATCTCCTACC
          GGCTTAAAAACCGTGTCCCCTCCCCAGACCCGATGATGGGCTGCGCCTCAATCTCCTACC
          GGACATTATAACTTGTCTCGGTGGCGAATCCAGAGCTATACCAAGGTAAGTCCCTTACAA
          TCCTACGGTACACTGAGTCTGTCACGCTTATGGCACCAGTACAACATAGACTCAGCGGAC

          CACCGAGACAATTAGACTGCCAAAGTTGGTGAGCCAGCGTCTGCCGGCTACAACCATACA
          CAGCGAGACAGTTAGACAGTCAAAGACGGGTAGCCGCCGGCTGCCGGATACAACGGTACA
          TAAGGAAACAACCAGATAGTCAAAGTGGGGAAGCCGCTGGATGCCGGATACAACCGTCTA
          CGCAGGATAAATCAGCTAAGCAACGTTGGGAATTCACTGGCTGCTGGATGCAACTGTCTA
          CACAATACCAGAAGAACTTACCGCACTCCTTGTTGCCTGGGCGTTTTCTACGTTCTTTAC
          CACAATACTAGTAGAACTTACCGGACTCTTTGTTGCCTAGGCGTCTTCTACGTTCTTTGC
          AAGTAAGTGTCGCCAACAATTCGCACTGGATAGCACTAACCCAATTAGTGAGACGGCGTA
          GCAAGAAGTCGTGAATACCCTTGTAGGGCCAAGAAATCCAAAATGGGGTGAGAGAGCCCA

          TATGCTGGAGCCCAGCCAATTCGCTTACATCCCGTTTGTAGATTTTATTAAAAGGGTAAC
          TATGCTGGAGACAAACTAATTTACTTACAGCTCGGTTGTAGGCTTTATTATGAGGGTAAC
          TACGCTAGAGCCGAACTAATTTGCTTACGTTCCGGTTGTAGACTTGGTTATCAGGTTCAC
          TACGATAGAGAATAACAGTACTGCATTTGTTCTGAACGTAGGCTCTCCCACAACGACCAT
          CATGGCATGACTCCAATAATGCGCAGGGACGATCACTCCAAGCAACAATCCTACGGCTGT
          CATGGCATGACTTCAATAATGCGCATGGACGATCACTCCAAGCGACAATCCTAAGGCTGT
          CACGCGAACATCATGCCTAAGCATATTATCCAAGGTATTTAATGTTGACTCTAGCAATTT
          TACGATATAGCCAACCTCACATGAATGATTTTAAGAGCTTTATTCCTCTACGAAAGCTAC

          AGTGGTTGCACTCCTGGCCACTTGAACCGTCCGAAGACGCACGTGATGGATTCGCATGTC
          AATAGTTGCACATCTCGCCGCTTGGACCCCCCGAAGATACTGGAGGCAGAGGCGGATGTC
          GATGGTTGCATCTCTGGTCGTTTACACCCTCCGAAGTCACAGGAGGAGGACACGAATAAT
          AGTGGTCTCGCCCCTAACCGCATGTCTTCTTAGAAGACATTGGCAGCGCACGTAAATGCC
          GGTGATGCTCTTGGCTCCCATAAGCGTAACTGGAAGTTATAGGAAGGAAGGGATCGCGGT
          GGTGATTCTCTTGCCTCCCCTTAGTAAAACTGGAAGTTATAGGAAGGAAGAGATCGCGGT
          TGAGTACCTATCTTAACATGATGCCCCGTTTCCTTTTAGCCGAAGTCGGCTAGATCTCTC
          GCGGGTCGCTTTAAAGTCAGACAGTTAGCTCTGATTCATGGGAGGGTGGCCGTGACCAAG

          TCTCGGAGATACATGACGCGGCCCCGAGCATGCGTTTGATTTTTCAGTCTGTTGACTGGG
          TTCAGGACATACATGACTCGGCCCCGGGTATGCGTATGACTATAATGTCGGTTGAGCGCC
          TCTAGGGCATACACGACCCGGCCCCGAGCACGCGTATGATTACATAGTCTGTCGAAAGCG
          TTTAGAGCGCACGTGACCGGGTCCCGAATAAGCGTGTGATTTCAGAGGCTATTGAGAGGA
          CCGGGGATGCATACGTTGGAGCCCCAATCAGACGAACTAAAACCAAGTTCGACGAGTTGA
          CCGGGGATGCATACGTTCGAGCCCCAGTTAGACACACCAAAACCAAGTCCGCCGAGTTGG
          TCAGGATTGGAATTAGTCTGCTCACGAGGGGGGCGACCTACTCTGGAGTTATTGGGTGAG
          TCAGAGCACTGCGTGTCTCGGTTTCGGGCAGGTGATAGTCCCGTATAATTACTGTTTGGT

          CTTCAAAGTCATTGTAAATCCAGTTGGAATATAAACGCTTGATAGAAAGGGTGCTCATCC
          CTCTAAAGTCGTTGTAAATCCAGCCGGAATTTGAACGTTCATGAGTGGGGGAGCCCATCC
          CTCTAAAGTCGCAGTAAGTCCAGCCTGATTACAAATGCTTACGAAAGAGAGTGTTTATTC
          CTCTACTGTTAATATGGACACCGACAAATTATAAAGATTTAAAGGGAACGGTGCTTCCTC
          ACACATCGACTTTACATTTGAGAACACTCTTAAAGAGTCCTAGGGACGCGACTTCCCGCT
          ACACATCGACTATACATTCGAGAACACTCTTAAATAGTCCTAGGGACGCGATTTCCCGCT
          TGTAATCCACTTACCTGTTTAGAGCACACCGAGACTCAATTTTAGTCATTACGTATTCAA
          CACTAACAAATTCATAGTAACCGGCGCCAGGCCGTTCTCTCCAAGCCGAGCTTCACTTTT

          TCAGTATAGGCCTTACCGAGAGACCCGTTCGGTTATGACA
          CCAGTACAAGACTCAGAGAGACACTCGTACGGTTATGAAA
          TTAGTGTAGGCTTCAAAGAGACATTCGTACGATGAAGAAA
          ACGGTGTAGGTTTTAGAGAGACGCTGGTAATGTTACGCAT
          ACAAGACGGTTCCGAAGGTAGTGAATATAAGGCTACGGAG
          ACAGGACGGTTCCGAAGGTAGTGAATCTAAGGCTACGGAG
          ATGAAACCGCTTTCAGGGGGTTGCATGCAAGGACAAAGAA
          GTAAGGATTTACTATGTAACACCCAATAATGGTAGCGCCC

