 8 1000
t1        GGTACGCGCATGGAGTGCAAGACCCACGTGCAAGTAATCAGAGGATACAGTCCAAGTCCT
t2        GGCATGACCATGTAGTGCCCAAAATACGTGTAGTAAGTCCGAGCGTAGAACCCCAATCTT
t3        AGTACGCTCCTCAGATACACTACACTAGTCCATTCGGCGCTCGCCTCATCTTTGGGTTCT
t4        GATGAATGTGAAACATGCTTTAGACCGGTTCTTGTTGCTAGCTCGCGGCGTGGGAACCCA
t5        TCCAAGTGCTTAGGTTGCGAAGGAAGTCTCTACGATGCTCGTTACTCTATCCTCAAATGA
t6        AATCCGTTCGTACGGAGCGAAGGCGGTGTTTGTCTTGATCGTCGATCCACCGCCAAACTG
t7        AGCAGTGCTGCAGATATAGCTCCGCGTGACCAACTGGTACGCTCGCAAAAGTGCGAAATC
t8        AGCAGTGCTGCAGGAATAGCTCCGCGTGACCAACTGTTACGCTCGCAAAAGTGCGAAATC

          TCCTTCCTGATGTTCCACAGTCCCCATTGACGCCGGATATAGCCAGCCGTTGGCGTCTAA
          TCCTACCCCGTTTTCTCTAGTTTCTATGTAGGCCAGATGGATTGATCCACAAGTACGTCA
          CATTATAGGACTTTTACTCCATTCAACCGATGCCGGGAAGAGTCCCAAACAGCTGCGTGA
          GAACACTGAGCCGATAGAAGTCCCGCCAACAATTAAACAGGACTGATAGTGGGTAGGAAA
          CCATTCGCGGCCTACCTTGGTATGTCGTCAGCGTAATTACATACTATCACGGCCGGACAA
          TCATACACGGTAGGCCTAGACCTCTTCAAGGGTCCGTAGGATACGTACACGGAAATGCAC
          CAATGCTGCGTCTCAGAAAAGCTTAACTGGTACGACATGCGCGTCTCAGCGACAGTGTGA
          CAATGATGCGTCTCAGAAAAGCTTAACTGGTACGACATGCGCGTCTTAGCGACAGTGTGA

          ATCTGCTCGAGTTCCATCTGAACACCCCCGAAAGATGGCGACGTATGAGATTCTCCTTAC
          ATCTGACCGGCTTCCATTTGGATCCAGTTGCCAGATGGGCTGGGCTTAATTCTTCCCTGC
          GACTAATCGGGCCTCATCACTATGCAGCCGATAAATGGCCTAGGTGGAAGGTTGTTATGC
          ATCTGGCCGACTCTCGTGCGAGCCTGGTAGAAGACGGAGTTGGACTGCTAACGCTGTATC
          AGCCCACCGGGTACTGTGTAAGTCAAAAGGGTAGCCGGTATGGGAGGAGGATCTACCTTA
          AGTCGATCAGGCACTGTAAATGTCAAGCAAGCGGCGTGAATGGGAAGGCTATCTCCCTCC
          ATCATATAGTAGGGTGCGCGTACGCGCGCAAAACGTGGATACCGGTCGTGACCGTTATCC
          GTCATATAGTAGGGTGCGTGTACGCGCGCAAAACGTGGATACCGGTCGGGACTGTTATCC

          TAAGGGGCCTGTCAGGTGAATTAGACTCACCGGATGCCCTTTGGATCGCTTACCCGTCCT
          TTAGGCGGCTGTGTACCGTATCAAGCTTACCGGATATCCTCCGAGTTGCTAACCCATCCT
          TAATGTGTCTGAGGGATGTAATCCGCTCATAGTCTAACTACTGGACCGTTCATTCGTTTT
          TAAAGACCGTTGGTGTCATGTAACATAGAGGATATCATCCATGCGTCGCCCGTCAGTTCC
          GAAAATGAGTCAGAAACTCACTGAATCTCGAAGACATGAAGTCTTTCGGCTGCTCTTTTG
          GTATATAAGCCTAAAACACGCTGACTTAAAACGATAAAAAGGGCCTCGGCCGTTCTCTTT
          TAATTTGCGCGCAGATATCGTTAGTTTAAGATTAAAGAACCTGAAGTGTACGCCAGTGGG
          TAATCTGTCCGCAGATGTCATTAGTTTAAGATTCAAGAACCTGAAGTGTACGCCAGTGGG

          CGGTGCTCGACGTGGACGCATAAGACGGTCCGTAGGCATAAAGGGGACTCCCATGTGTGC
          AGGAGCTTGATGTCGGGGCTTAGGATGGTCCGTCAGTGCACCGGGAACTATAACGCGCGC
          GAGAGCCCGGTGCGAGATTTGTAGTCCGCCCGTCGGCACAAGGGGGACAATTGCATGCGC
          AGGAAGCAGACACCGATGTCTTGCGTGGTTGCGGCACACGGGGGGATTAGCCTTGCGGAT
          GTCAAAGCAATGCGAAAACTACCATCGATCCCCTTGTATCATCGAGCGCATCTTTTGCCC
          GAAGATGCAATGTTATCAATACCATTAACACCATTGCATTACCGGGCGCATACCCCACTC
          CGGGTTGGATCAATAGTATCGTCGCCCATTCAGCCTTTCCATAATATATTCCAGGTGAAC
          CGGGTTGGGTCAATAGTATCGTCGCCCATTCAGCCTTTCCATAATATATTCCAGGTGAAC

          GATTTGTTTTGCGAGACGGATCTCGTGGATTGAACGTTCTCATCAGAGGCCGCTCTACGG
          AATCTATTTAACGAGATGAGGCATATATCTCAGGTGTCCTTCCTGGAGGCCGACACACGA
          CACCCATCTAGCTATGCGAGGTTCCTGTTTGTTACGTCCTTCCTATGTATCGAGCTGTAG
          GGTCCACGCAGGAGGCTGTAGCACTGACAAACTGAAATCCTCGTCGAGGCCACAGAAAGT
          TCCACACCCGGTTAGTCAAGGTCCTGACCGACTCCGTCTCTACTTGAGTAGATGATTCGA
          GGCACTTTCTGTATCCCGAGGTCCCAGTCTACAGCCCCTGTACCACGGCTTGCAGCTCGA
          GTCTAATCGAATGTGCCATAGCCAAGATAACATACATGCCTCCTAGAGGCCACGTCGTGT
          GTCTCATCGAATGTGCCATAGCCAAGATAACATACGTGCCTCCTAGAGGCCACGCCGTGT

          ACGGCCTTTTTCGTGGCACCCCGGAATGAAGTCGGTCAAGACAAGGCAGCAGCATATGTC
          CCGGCGCCTTCGTTGGTATCTCGAAATCTAGTCAACCAAAATGAGGACGTGCCACGAATA
          CCATTTCTTCCCGTGTTATCCTGAAGTATACTCAATTGTAGAAGAGGAGCATAACGGGCG
          TTCGTTGCTTTAACGGCCCACGGGTATCCGCTCGGAAGAGACAGAATAGCGGGGAGAATG
          CGGAATGTTTCTGCGATGTCGTTGGAAACATCTTGATTAAACGGCGTCGTGAACAGGCTG
          TCGACTGTCTTAGTAATATCGCTGGTTTCACATAGATTAAACACCATCGCTATATGCTTG
          CGAATCGACTTCGTATCCATGTAGTGCCCCTATATGGGCGGAGGGCAGGTGCAAAAAAGG
          CGAATCGACTTCGTATCCATGTAGTGCCCCTATATGGGCGGAGGGCAGGTGCAAAAAAGG

          GGCAAAACAATTCTTAGGCTCACTTAGTACAGCCGAAAATCTCTTCCTCAATACGCAAGT
          GGCCAAGAGTTTGTCCCATTGACATTGTGTAGATACATATCTAAATCTCAATGCGCAAGT
          GGTCAGACCATGCTTGGGCTCGCTTCGTGTCAATACATATCTACATTTTTCTACATAGTT
          GGACCTATAGACGAGACATCCGCTTTGAGTCACTCGGGATGTTATCTCCCCTACGTACTC
          GCTCGATTGGCCGGTAGTGTCTCTTCCAGTGCTCTGACATCTACACGTTCCTAAACTGCC
          AGACATATAGCTGTACGGCACATTTTTAATTCTCCTACACCTATGCGTTTCCACGCCGGC
          GGCAGTGGCCCCCTAACACTTGTACTAGGGGGTCCTTCGGCAGCGTTTCAGCTGGCTGCA
          GGCAGTGGCCCCCTAACACTTGTACTAGGGGGTCCTTCGGCAGCGTCTCAGCTGGCTGTA

          GCATTACAAATAGATCAGGCACAAAATTGTAGCGTAGGGAACTGGATTCGGTCGACCTTT
          GTACCGTAAATCGTTAGTACAAAAAATCGCCGCGCAGGAAATTGGTCACAGTGACCTTTG
          GTCCGAAGAAAAAACCGACTCTAGAATTGCTGTGAAGGGCTTCGGGCTCGGTCATCACCC
          ACGAAAAACCCGTGCACTATATACGGCACTTGAATAGCAGATAAAATCTGCTCTTCCATG
          GCACTCGACAGGTGCTGAGAATGAAACGAAAGTGTTATCGAGTAAGCGTCTTTCTCCTTC
          GCAACGAAAAAGAAATATGACGGAAGCGACAGCGTAGTAGGTTGAGCTCTCTTTTACTCT
          ACCGAATCGCTCAGCCTGCTAGTCATCTACCGTGCAGTAATCTGGGGCCCCCCACCTTTG
          ACCGAATCGCTCAGCCTGCTAGTCATCTACCGTGCAGTAATCTGGGGCCCCCCACCATTG

          ACCATCAGCATGACTTCTGGAGCCGCTGGAAACATACTCTTTTCACCGCCCGGACAGCCG
          ATTCTTGGCTCAACCATCGGAGTTGAGAATAACGAACTCTCCTAATTTCCCGAACGAGCG
          ACTTTTAGCCTGACGTTTGGAGTTCAGGACCGTACACTATTCTTACCTCCGGAATAATCG
          GCATTCGGTCCACCCATGGAGCTTATTGGTCACTGGGTAGTTCCGGAGCCGGATTGCCGC
          AGAAACAATCCACCGGCTAGCCGCGTAGTCAACAAATTCCCCCTTACTTCGATTGGTTCT
          ATGAGTAGTACCGCCTTTGGAACCGTAGGGTTAATACTTCCCCTTTACCCGATCGTTTTT
          GCGAACCTTTCGAGTCGTAGGTAAGCTTGCCTATCGTTGCGTTAGCCCTCCGGCCCCCCT
          GCGAACCTTTCGAGTCGTAGGTAAGCTTGCCTATAGTTGCGTTAGCCCCCCGGCCCCCCT

          GCGACGTAGGAACCTTCCGTGAGCGCCCGATTATTCTGTCCTCTCAAGGCTACAATTAGG
          GCGACGTTAGCAGCTCCCGTGAGTGAATGACCGTGCTATATCTTCAAATCTACTTTTAAC
          GGGAATTTAGATTCACTTGCCGACGTTCGACAGTGCTCGTCCCTAAACAACACGGTCCGT
          GCGATATAATGGTCGTTTCCGATTTAGAGCTAGTTATTAACCACCGTCGTTAGGATCGGT
          ACAGAATGGGGCACGCGCGCGGGCCTTTGGTAGTCGCAGCCTTGGCACCTCCAAGTTCGC
          ACAGCGTGGGGGACGCCAGCGGCTTTGTGGCGGTCGCGGCCTTAGGGACTCCGGGTTCGC
          TCCGTCATACGTCTGTATATGAACCTCATGCGGCTACGGACTATCTGAGGCGCACTAAAC
          TCCGTCATACGTCTGTATATGAACCTCATGCGACTACGGACTATCTGAGGCGCGCTAAAC

          GTTCGCTATCTGGGTCATCATCCAAGAGACCCTGATTGTCAGCCACCCTTGCGACTCGAG
          GTTTGCTACACGAGCTAGATCTCATGAGGTCCCGACTGCCGGTCCTCCAAGCAACCAGGC
          ATTCGATATATGAGTTCCCGTCCGCGCGGGAGCATTTAAAGGACCGCCATACTATGCGAC
          ACCTAGAACTGGTATCACCACGGATGAGGCTTTAGTCGAAGACCTTTAATAACTCACGAT
          ACACAGTACCTGCGTCGTCGCACACAGTTAACTGTACGGGGATCGTCTACAGCGCTCATC
          AATTTGAATCGATGTCGTCGTGCACGATATGGTCAAAGAGGATCACTTACAGTAGTTGGC
          CGCGGGTATCAGTACGATCGAACAATTGCAGCCGAGTTCGTACACCCTGAAATATTCGAC
          CGCGGGTATCAGTACGATCGAACAATTGCAGCCGAGTTCGTACACCCCGAAATATTCGAC

          TTTGTCCCCAAGGTAGGCGTGCGACAGGTCTGTTCCGCATGAACCGCCGCTCTGTGAACG
          TCTGTCTCCTTGGAAAATCTGCGACAGGTCGGCTCCGTATGAATCCCTGTTTCGCGACCG
          GCCAATCTCGTTTTGGGCGCCCGGCAAACCTACTCCTGCTACACTGACCGATATCATTCG
          TTAGTAGTGGTCACGGTAGTCTACCAACTGCGTTGCGCCTGTAACGTCGAGTGCTGGCCT
          TCTGCCACGATAGTGGGTGATAGCCAGTCATGCACCATATAAACTCCTCGCCGTGAACTA
          CCTAATCCGAGGGTGGGTACTACCCAACTATGCCCCGTAAAAGTTTATCGTCACCATACG
          CACATGCTAGTCTCTGCCTCCATGTGATGAAATCTCTTATCAACGATCCAATACCAACGA
          CACATCCTAGTCTCCGCCTCCATGTAATGAAATCTCTTATCAACGCTCAAATACCAACGA

          AACCTCCTACAACCAAGAATTGCGGACGTAAGGGCACGGTCAAGCCCCATTTCCGATGGA
          AACAACTTGCGGTTGAGATTTGTGGATGTAAGGGCACATTGATGTCTTTTATCCGCTAAA
          CCTCTGTTGCGACGGACACCCGTACACATAAGGATGGGTACATGTCCCATCTCCGCAAAG
          CTGTTCTCACAGGGGGTCTTGCCAAATTTAACAGCGAGTTTCCGCCTCTTTTTCTGGGAC
          TGTTCTGGGGAGCTAGATTTAGTCAAACTTGGCATAGGATCCTATACCATTTCAAAACGT
          TGTTGAGTTATACTAGCGGTAATCGACCACGATCTGCGATCCAAGTGGATTCTAACGGGC
          TACCTGGTTGACTTGATGTCTGTGGCAGACTAAAAACCCTAGTACCTTTCCCTGGTCTTC
          TACCCGGTTGACTTGATGTCTGTGGCGGACTAAAAACCTTAGTACTTTTCCCTGGTCTTC

          CACCGGTCCTATCTCCTAAAGAGTGACGATCTCTCACATCTGCGCATCGCATCCTTTAAA
          CACCGATTCTGACTCCCAGAAAGTGACAATTTCTCGTAATTGCGCCTTTTACTCCTTAAA
          TGATGACTCGGGCCCGTAATTAGTTTCACCTCCTCGCAATTGCGCTCCTTACTTCCTAGG
          TCTCGACAACGCCGCGCTAGATATACCGTTTCCCTTCATTTGAAACTCCTGTTGCTAGGA
          TGAAACTTATGCCTGCTGACAGTCTTCCAGATTCGGCAAGTCTTTCTCCCATAAAGCAGT
          TGACACCTTTGTCCATTGCCAAGTTTGCAGACTCAGTAAATCTACTGCTCATTATGTAGA
          ATCGTCTATCGTAGACTAATACAGCTATGATGAGGGCCTTGGCGACCTACGTCATGTAAG
          ATCGTCTATCGTAGACTAATACAGCTATGATGAGGGCCTTGGCGACCTACGTCATGTAAG

          GACGGGTGCTCGGTTTTGTCATGACCATAGGCGTCCTGAACAGACACGCTTTAGCTACTA
          GACGGGCCCCTAGCTTAGTCAAGGCGCTACGTGTTCTGAACAAATGGATCCTTGCCGTCA
          GACGGACTTTGAATCTTGCCCGGGCACCGGGTTTACCGGACAAGTGAACTCCCGCTACCA
          GAAGTACGCAGCACCACGTTCACAGAATGGGTAAGTTAAAGACGTGAACCCACGTCACAG
          GTAACGTGTCCTACTTGATCATCCTGGCGGGAGTCCCCAGGAACTTAATACGATCTATGA
          CGGGAGTTCGTTATTTGATCCCTACGGTGGGCGACTCAGCCGATACCATATGCCCCACGG
          CAAAATACTCGCAACCCGCTATAACATTCGCGGTGAAAGATAGCTATTCACGGGTTTCTA
          CAAAATACTTCCAACCCGCTATAACATTCGCAGTGAAAGACAGCTATTCACGGGTTTCTA

          GCCTGAACGAGTACTTGTTGAGGGGAAAGTGTCTTTCGTT
          CTCTAATCGAGCATCAGCTGCGGGGAAGTCAATCATCATT
          ATTCGAACGTGATCTTGGTGTGTAGAGTTTAGGCGGGGCT
          TCGCGTACATCTCACAACAGTGATTAATTCGGCTTGGCGC
          ACTGGTATTAACGGTGCCGCAAAAGATCCCGACCTGTATC
          ACCGGCTTATGTGGTGACACAAACGTGCTCGGCCCATATT
          GCTTTTCGGAGTGTGCACGTCGTAGAGCACCGTCCTAACT
          GCTTTTCGGAGTGTGCACGTCGTAGAGCACCCTCCAAACT

