 8 1000
t1        ATATCATAGTCGACCAGCAGTGCACTGCTCGTAGAGTCCGGCTACCTGCGGCTCTGACCC
t2        ATATGATAGTCGACCAGCAGTGCATTGCTCGAAGAGTCCGGCTACCTGCGACTCTGACTC
t3        ACGGCGTCTTCGTCTAGGATCGTATTACTCGACAAACTTGACCACCGACAGCCATGCCGC
t4        CTGTGCTATGAGCATAGTAGTAAATCGCTTAAGCGGCTCAGCTAATTATTTCTCCAGTGT
t5        GTGTGCTTGACGCCGAGAAGCAAACCTACGCAAAAGCTCCTTCCCGCGCTGGTCTGCCGT
t6        ATGGGCTAGTAGAATTAAAGCCAAGTCGATCCGAGGTGCGTAGGGAGGATGAGTACGTTC
t7        ACGAACCGGACACGCAGACGCACATTGACGAGGCAGGCCCCTTCTCCGTAGGCACCATCT
t8        TGGGGCTGGCCGTGCGCATATAGGCTTTTTGCGGAGTCCAATGTCCCGCTCACCCTCCGC

          TTAGCTTCTCGTCCGCACTTAGCGACACCTTCCAAACCGCAACCACGTTCGAGGAAAGTT
          TTACCTTCTCGTCCGTACTTAGCGACACCTTCCAAACCGCAACCGCATTCGAGGAAAGTT
          TTACTACATCATGCATGCCCAACCGGAACCACCAAATTACATCCGTACTCGAGGGAGGCA
          TCAACGTCTCATATATCTGCAACAAGACACTACTAACTGCAAATTAACTCGAAGGCAGTT
          TCGATCACCCTCCCGCTGAACGGAGAAACCTTTTTGCCGTAGACCGACCCGGGGGAGGCC
          CCCTCCGCATGACCTTCCTTAGTCGGTCCGCCAACCCGGAAGCATACTAAGAAGGATCAC
          ATCGACTCATTCCTATCCTTGGTAGATACTAGTGGCACGCAGTCCTCACAATTGAGGGAC
          CTAGTCGCTTACCAATTCATAGTAGTGCAGTCTACCTGGTTAATCGTCCGATCGAAGGTA

          GATGTTCGCAGCGTCGCCAGTCGCGCACGCCAAGGAATCCACTTTTGGACCTTTGTCAGC
          GATGTTCCCAGCGTCGCCAGTTGTGCACGCCAAGGAATCAGCTTTTGGACCTTTGCCAGC
          GACATTCGCTGCGTAGCCTGCCGAGCACATGGAAAATCTAGCCTTCGAGTCTTCATCGGC
          GTCGTTTATGGCAAAGTTTAACAGGTGTGGGCAAAATCCCGATTCCGGGCTCTCCAACTA
          CCCCACCCCCCTGCAACTGATTAACCAAACAGCAAATTTAGATCAAAACTCACATGCCCC
          GCCTTCTTTTGAGCATTCTGCTGCGTTTGTGTGGAAAGCGATAGATTAGAACTAACTCAG
          GCTCCATGCGGAGCATTCGGAGAGGTACACAAGAACGCCAACTTATCAACGCCGATCCTT
          CCCACCCACGAAGCCGCCTGCGAGGCATCCTGCTGACCTGTCTCTTAATGCTTGCTGCCT

          GTCGCATGACCGGTTAAATTGGTACCGATAGATCAGTATCTTGTATAGGTACCGCGCATC
          GTCGCACGACCGATTAAATTGGTACCGATATATCAGTATCTTATCTAGGTACCGCGCATC
          GACATTCGGCCGATTAAGATGGTACTGACAAATCTGGATGATAACTAAACATCGTGTTTT
          AACGCCCGCCAGGTGAAAGTAGTACTGATAAGCAGCAGTGTTACCCGAACTCCGAGTCTG
          GAGCTCCGGTCAAAATCTGTGGTCCCATGGTGTAAAGATCTTACATAAGCATAAAGTATC
          GATGGCGGAAGAGTAAATGCGGTGTCAAGAATTGGTGTCACCTGTTGTAAGACCGGACTT
          TTCGATCGACAGACATCAATAGATACACGACCCAAAAACACAACTTAACCACGGAGGATT
          CACGGCGGGAGGAAGAGCGTAGCTCCGGGGGATCATGATGTTGGTGTATCCCCGCGCTAC

          AGGAACATAGGGCCATGACCCGGTATAGTTAACTTTAGCCCGGAGACGCTCTACGCGAGA
          AGGAACATAGGGCCATGACCCGGTATAGCTAACTTTAGCCCGGAGACGCTCTACGCGAGA
          AGGAGTACATGAACATAAGATGGTATAGTCCACCTCCGTCCAGAGACACCGTACGCGCGA
          CACCAGACCCAACAGTGAATTGCTGCCGCACGCCTCGGGCGGGAGGGACGTAACGCCCTC
          AGCGGGATCGTATCAAGCATCGGCATAGCCTGACTTTGGACAAAAGTTTCGTATGCCTAA
          CGGCCGTGTTGAGAACGGGTGGCCTCAACACGCGCTTGCAACGAGGCTGTCTATCTAGGA
          CGGTGAGACCAGAGGCAGGATGCTAAGCTACGATCACAGGGTGATACCACTAACAATTCT
          CTAAAACGGCTACGACGACACGAATTACCGTGTCAATCGGTTTGGCTTGCGAATTTGTAC

          GGTGCCAGAGCCTCTTACCACGCGTGAGATGACTGACTAGTCCGACGCCGCCCAATCGAC
          GGCGCCAGAGCCTCTTACCACGCGTGAGATGACCGAGTAGTCCGACGCCGCCCAATCGAC
          GGTGCCGGAGGTATTAGCCGTGCACAAGAAGAATGGTGAGTCAGAAGCAGTCCCATGGTT
          GGTACTGGAGCCCTCTGCCGCGCAGGTGACGAAAGGTTATTCTGGGAGAGTGAGGCTGAT
          GATGACGGAACCTTTTCCAGCGCAAGTGTAAGGCGATTATTTTAGACAAATTTCGCAAAC
          GACGGAGGACGCTCAAATTCCGGGAAAAAAATACGTCACGCGTGATCAGCACGGGAACGA
          TATGGAACCTGTCTCCTTTGTTGGCAAAAAGGGCGTTAATTCTAGCAAACTCATGAGATC
          CTCTTCGAAGCCTCTTGGCTGGCAATCGCGTAAAGATTACCGTGGCGTCAGGTTACATTG

          TTGTCTGCTTTTACGATAACCCCGGCCCAGTGGGTTGCTAGGTACCCTCACAGCTATGAC
          TCGTCTGCTTTTGCGATAATTCCGACCCAGTGGGTTGCTAGGTACACTCACAGCCATGAC
          TTGTTTGCCTGTGCCTTAAGCAAGGGTCGGTGGGGAGCGCGGTGATTACATAGGCGCGGT
          CTGCGGGCGCTTTCGTCTATCTCGGCACGATAACTGAAGGGCGGAATTAGTATCTATGCC
          GTCTTCGTGCACGCGTCTTCCTTAGCGCGGCTAGTCGTGAGATGAATCTAAATGCTCGCT
          TCGCGGGGCACCTTTCTTGTAGTGATTTGGATACCGGGAGTGTCCACTCGCATGTTTGTC
          TGCCCCACTCTTCTGCCCATGTGGGATGGCTATGTATAGAACCACACATATTGGTATGAT
          GTCCTTGCGCATCCACTTTTACAGATATACTTGGTATGCGAGTGCCCCTTTATAAACCCT

          GAGGCACATAAACTAGGTAGCACAGCCGGCGCTTAGGCGCACTCGGACTTCAGCTCCCGC
          GAGGGACATAAACTAGGTGGAACAGCCGGCTCTCAGGCGCAGTCGGACTTCAGCTCCCGC
          GAAAGACACGAAGTAAGATGTACAGCCGGCACTCAGGTGGACCCAGACCTCAACCCCTCC
          GAGAAACGTGGTTTGGGCTATCTAATCACTACATGGGTGACATTCGGCGCCTACTCCCGC
          CAGGAGCATACACCGGAAGGTACTATAAGAAGATAAAGACACCCTAACCCTAATGCACGC
          GATGGGCACATACTGGTACGCGAAGTCGGAATGCATATGTTTACAGCATTCGGCTCGGGC
          GGTGACCAGTTATCGGGTTTCTTGAACGACGAAAACGGGTCCACAGAGTGCAAGGTATGA
          ATAAGACGGAAGGCTGACCGGTCCGGCAGTTAGCGCTTGTTCCGGGCTCCTCAGGAGCAA

          TCCAGGGAGGTCTTCACCTGTCCGGCGAACCCGAGGTGTTAGCGACCCGCCCTGGACAGC
          TTCAGGGAGGTCTTCACCCGTCCGGCGAACCCGAGGTGTTAGCGACCCGCCCTGGACAGC
          TTTGACACGAGTGCCTTACGCACAGCGTTCGGAAGGCGGCGGGGCCTCAATCCGGATACT
          CCCGGAGCGGTCATTTTGTGCTTCCCGGCCACAAAGCCATGGTGACCCAGTTTAGAAAAG
          TCCGGGTCGGTAGCCGTCTGTTCGCCGCACCCAGGGCAGTGTATACCTAGATAAGAACGC
          TTGGAGGGAGTCTCCTCCATTTTATCTTGATTGGTCCGAAGCCCTATCAAAATTGACGGC
          CTAACGGTTACAACTTCCTGTTTACCGGGTTTGGTTTGCTGTCGCGCTTAATCTAAGGAC
          CTGGGGATGACTCACCGACGTAGATTACTTGTAGTCTAGCGTCGACCACGACAGTAAAGT

          TTCGGGAGCGTGCTGATGCCCGAAATGGATACTGATTATACCTACGAATCAGCGGTGCAG
          CTCGGGAGCGTGCTGATGCCTCAGATGGATACTGATTATACCTACGAATCAGCGGTGCAT
          GTTAGTAACATGCAGATGCCAGTGATGGCTATAATTTCTACTGATGAACCGGGGTCGGAC
          GCCCGGAGTCTGCTAATTCATGTGGGAGCTACAGTACGCACTCACTAATCGGCGTAAGAG
          ATCAGAAACTAGCACGCGCGTGGAGTACCCTTAGACCGTGCTCGTGAGCCCCGTGAGGAA
          GTATATAGTTCACACATACGCGCAAACTTCTTGGGGCGCCTGTGGGGAGTAAACCCGTCT
          ACTGACCACCCATGGAACCACGCGTTGACCAAGGAAGAGTATAAGCAGACTATTACGGGA
          TCCGAGTGCCTCGGATTGCACACCATGCCCCTAATATTTTGACAGAAGCTTGCCGCAACC

          CTAAATAGCGTAGAGCGAAACCCAGCTACGTAACCCTGGTCGTTGCTTAGAACTTTTACG
          CTAAATAGCTTATAGCGAAACCCAGCTATGCAACCCCGGTCGTTGCTCAGAACTTTGAAG
          CTAATTAACCTTTAGAGGAGAAATTCTACAGATTTTCGCTCGAACGTCTGCGTCTTGGAG
          TTTGCTTGTGCCCGATGAACTGTTTCAACACCCTTTTACCCAAAAACCGGTGCCCTGGTG
          CCTAATAATCTGCTGCCAGGTTTCGTGATACTTATTGCTCGTCCCACTCGGATCTTGGAT
          TTAATCAATCGCTCGTGTCCCCTCACGACGCGAGCCCATAAGCACCCTGGCACCTTGCGC
          CTGTTTTATCTATATCTACATGACCCGATAAGATACAAAACGTATTCTTACATTCTAGCA
          CGCAACACTACGACTGTTAGGAATCCAACCCAATGTTTTTGCCAGAGCGAAGACAGAACG

          CTCTCGTCCAGGACGATTGCTCGGCTATAAATGTTCAAATGCACGAACTAAGGACTTCTA
          CTCTCGTCCAGGACGATTGCTCGGCTATAAATGTTCACATGCACGAATTAAGGACTTCTA
          TTGTTGTTTGGGCTGAACGCTCGGTTAAATAACACCACGTTTAAGGGCAAAAAGCTCCTG
          TTCCAGTCTACGGAGACCGGTCGAACATCCAGACTTCTTTGCAGGGGCAACGCGCTATCA
          CACCCATTCCCGATAAACCGCTGAATTCGAGGGATTCCAAGTCTGCCGGAAACGTATGCA
          CTTCAGTCAATGACAGGGGGCAGAATGTACCGGGTCTCAGGCAAGGGCTGGAGGTTAATA
          TCTGTTCCCGAAATGGAGGGTAGAATAAGATGGACTCCTAATGCTGACATAGTGGACATA
          TTCCAGACAGCACCGAGACTTACTGGTCACTATCCACTTTTAGCGGAAAAAGTCTGGAAG

          GTCCTTCCCACTATATTAAACCTTTCGTCTAGGGATTGATCTTGTAAGTAGAGTAAGAAT
          GTCCTTCTCACTATATTGAACCTTTCGTCTAGGGATTGATCTTGTAGGTAGAGTAAGAAT
          ATTATTCTCATTAACTAGGATCCTTCTTTCACCACCTGGTCTTGCGGACAAAGGAAAGAC
          ATCATCACCACTCACTAGAACCCGCCTTCCAAAAATCACCGTCACACGCAGTGGCAGTGA
          ATAGATCTCACTTAACAGGGTTACCCCTTCATTAGCCAGAATCATTCCCAATGAAGTCGT
          ACCCATCGCACCAATTCGGAAGACTGTGATTGAACACGTATTCAACTACAAAAAAACCGC
          GAAAATCACGTCAATGTAGGCCACTAAGATGATGGCCAGGTACGAACGTTGACCAGGAGA
          GAAAGCTGGGAACGTTGGGGCGAGCGGCTCGACGGTAGGCGCGATATGCAGAAGTTAGGC

          TCTGCTGTAGTAGCCGAAGTCCGGCCTAGCGGGTCGAAGGGGAGACTTTGCTCCCGTCGC
          TCCGCTATAGTAGCCGAAGTCCGGTCTAGCGGGTCGAAGGGGAGACCTTGCTCCCGTCGC
          CCCATTAAAACAGCCAAGCTCTGGTAAAGTGGACTGGAGTGGAGGTGTTGTTACCGCTGC
          TCTCCATTGACAGGCAAGGGCTGGCGGCGAAAACCTGAGCAGAAACTTGGTAACCGCAGT
          GACGCTATGATAGCCCGTCCACGGCTGATTGCGAAGCGCCGGCGGTGTTGTGGCCTAGAC
          TGCTAATGGATAGCTTGGAAGTAATACCACCGACCTGAGCCCTTTATTTTTTGCGGACGA
          AATGTACTATGCCATCGAAGGGGTTGGCGGGGGAATGGGTCATACTCCTCCCCGCAGAGA
          CACTTTCTGGTAGTATAGCCTCATCACAGCGGCTGGGTAATACGTTGCCAATTCAGCGAG

          AGTGGGTATCTGCGCTACTGATAGCGTAGCGTTGAAACATTAATATGTAAATGTTCCATC
          GGTGGGTATCCGGGCTACTGATAGCGTAGCGTTGAAACATTAATATGTAAATGTTCCATC
          GGTGTGTTCCTCTGTTACCACGAACGCCACGCTGTATTGCCAACGTGGTAGCATCATATC
          GGCGTGCCTATATGGCACGATGTAGGCTATGTATGGATACTAATGGTGAGATCCCTCGCT
          GACGTACGATGAGGGCTCCGTGTATGGAGGTTAGCGCACCTTGCCTACAAGTTCTGCGGT
          ACTGCCGGTCAATAGTAACATGTGTTGAGATTCGCGATCTGACCATGTAACGCACCAGTC
          AGCGCAATACCTCAACGGCGAACGTTGAAGTCAAACTTTTGAATTCTTAACCCATGGGAA
          CGTATACGTTGACATCACTATGCACATAGCGTTAAAAGGTCTCCAGGACCGCCTAAGTGG

          GGTTCTGCAGCCAACGGCTTTTGGGGGTATGGAGTATAGCCGTAAGGTCCCCCGCATTCT
          GGTTCTGCAGCCAACGGCTCCAGGGGGTATGGAGTATAGCTGTGAGGTCCCCCGCATTAT
          GTGCCCACCTTTAGTAACTTCCAAGAGGATGGAGTTCGGTTGTGAGGTCCACTGCACCCA
          GGATTCAGGACCTGTAGCTGATGAATGGTTCATGTAGGTCTGTGGGATTTCGTGATTCCC
          GGATACATGACTCGTAGCTGATAGCTGCGTGGTACGTGACTCTGCAATTTCCCATTATCC
          GCAGCCTCGACTTGCAATCGTTCGATGTTTGGATAGAGATGTTACGATACCTAACTTGCT
          CGTTCCACGGTTCGTAGCCCCTTAACAGATGCAGTCCCGCTGTACCTCCTGTTGATTCCC
          GGTTTCATACCCCCGCGCTCTTCGAAGTAAGCGGACGGAACTCACGAGGCATTCCGCATT

          TGGAACGTAACGTAAGGGATGGGCGCTATTAAGCCCATAG
          TGGAACGTAACGTAATGGATGGGCGCTATTAAGTCCATAG
          GGGGGCTCAACCTATGAGGTGGGCGCTACTAGGTACACAG
          GGCACTTCAGTTTATGAGGAGAGGCCCATAAAGTCAACAG
          CGGGCTATAATCTATGAGGAGGATACCTTTAGACGCAAAT
          GGCATTAAAATTCATAAAATGAATGCCATCGAGCCCATGA
          CAGAGAAGGCTAGACTCTGAGGGGACCACAGGGCCCCTGG
          GAGAGTATGAGACGCGAGAACGCTATCCCTTTGCGTATGA

