 8 1000
t1        TTTCCATCGACAGGAGGTAGACCTGGCTGAAGAGTGCAGCCCGGATCATGGCACCCCTTG
t2        TTTTCATCAATAGGAGATCGACCTGGCTGAAGCGTGCAGCCCGGATCATGGTACCCCCTG
t3        TTTTTATGGGTGCGAGGGCATTCAATCCGGAAGCTGAAGACGGTTGACTTGAACTCCCCG
t4        GTACCAAGGGCGGAAGGAGTTTTAATTCGAAACGCGAGAAAACCATACAAACATCGATCA
t5        ACTTTAGCGGAGAGGGGTCGGCTCGTGTGCCAGACAATGATCAAATACCACAGACGTCTA
t6        ACCTCATTGGTGGAAGAGTGCCACAGGTACTAGCCAATGCTTGAAGGCCAGAGGCGTGAA
t7        CCTCATATAGCTGTTGATAGCTCGATATGAAGGTCAGAGCATGAAATTTTGTTTCCTCCG
t8        TTTCCAGTGCAAATTGTCTACGTAGAACAGCCGCGGAGGTCCGCCATGACACATACTCAA

          CCCACCCCTAGGAGAATCGCTTCAATAATGGCTAACCGTCAGGCATGCCCTCTGAGGCTT
          CCCCCACCTAGGAAAATCGCCTCAATAATGGCTAACCGTCAGGTATGGCCTATGAGGATC
          TACTAACCTTGATGAACTGCATTAACAACCTCAGTCGAACAAATCCGCCCTGACCCATCC
          ACCACGCCTATGAGGTCAGTATCAGAGATCCTAGAACAATGCACTTACCTCGATAGCTCT
          CACCAGCCCTATAGTCTAGTCGAAGTCTTTCCGGGTGGGCCGAACTAACGCCTGCATGTC
          TACATTCCTTACAGCCTCGTCGGAATACCTGCGGGTGGGGCGGATCAGTGTCCATATTTT
          TAACTGCCTCAAGGCCGGATTCCAGAGGTGGTGAGCCGGGTAACCCAAATTGATAACCCC
          ATACAGTATTAGTTCCCCACGTCAGTACTCTCTCCCAGACTGCTCCGGTACGTGGGCTGA

          AATCTGCGAGAGGATTGATATAAAGGGCGCTCAAATGGGGTCAAGTACTTCATATTTAGT
          AAACCGCGAGGGGATCGTTGTAAAGGGTGCTCAAATAGGGTCAAGTATTTCACATTTAGT
          TCTCTTAATCGTCTGCCGAGAAAGCGACCTTAAGTCGGGGTCAGGCGTCGCACATACGAC
          TATTTTCATCTAGACTAGCGGTACTGGCCCGAAGTCAGGATCAGACGCCCCTTATCAAAC
          TTCCTGAACGGTATCTAATTAAGATAGCTGTATATAAGGAATTAGACTCTAACTAGAAAT
          CGCCTGTGCAGCCCCTAATTAAAATGAACTTGCAGTGGGAAATAAGGATTAATTATGACA
          CGCCTGTGATATTCTAAACATGACGGGGCGTACCCTGACCGCCGGTGTTCACCAGAAGCT
          CCTGTTTACTTACACAAGTTAGTCTGGCCCCCTCGCGGCGAAGAGCGCAACATGGACATT

          GCGACACATACCCCCTTCTTAATGGAGGCGTACCATACTGATTGGTTTAGAGGCCGTACT
          GCGACACATATCCCCTTCTTAATGGAGGCGTACCATACTACTTGGCTTAGAGGCCGTACT
          GAAGCGGACAACCTAGCTCCTCCGCAGTCGGTTCACTAATTCGCTAGGCTTTGTAGGCCC
          GAAAAGAATTAGCCTTCTCCCTGGTAGTGGGGCCTCACACGCAGCCGGCATCACAGGCCC
          GATGCTCGCCATATCTCCAAACTCCCTTCCCAGGAGGCTAAAGATATCTGGATCGAGGCT
          GTTCCACGCCATGTCTTCAAGCCTCCTTCCCAGTAACTGGAGGGCACTTCCAACGAGACT
          GTTGCAGGCAGGTTGAACCGTTCTCGGTCTGTGGGGGCAACTGCTACTTCTTCCTAGGGC
          CGGGGCATTCGAACCTCACGCGACCCTGTTGGAGGCGTAACTCGCACCTTCTGTCTGGGC

          ACCATACACGACGGTAGCGATATACTTGCGACTGCGCCCAATCTGACTCGGGGCTGCCTC
          ACCATACACGACGGTAGCGATACACTCGTGATTGCGCTCAACCCGCTTCGGGGTTCCCTC
          GTCGATCATGATTCCCGCAAAGTAAGTTAAGTATTATTAGGGTCTGCCCGAACCTCCATA
          CTTGGATGCACTGATGGAAATGTGGCTCAAGCTTCGCTTGCGGCCCTTCAAGCCCCCTCA
          AAAATTGGTTTAGTTAACGCCGAACGGCTGCCCCTTCAGCCTGTAATATGGGCAAGGGTC
          CAAAGTGGGTTAGACGACGCCACATGGCTATTTCTCTAACGTTAAACATCGGTTTGAGTC
          GCTAAGGTCGCAGACAACGCATAACAGAAGGACCCCTACAGCGTCACCTTAGTTTCTGCG
          GGCATTGGTAATATGGGTGTGAGCTCGTTACGCGTACGCCACGAAATATCGAGATGGACC

          TTACCTTCAAATACGTTGTACCGCATCAACCAGATAGGTTGCGGCGGTCTGCGATGACGC
          TTTCCTTCTAGTACGTCGTACCATATCAACCAAATAGGTTGCGGAGGCCTGCCATGACGC
          CACCCGCAATCACTCTGTTACTGAACTGCATGGACACCTCGTTGTTCACTGCTGAGGACA
          CACCCCTAACCGGTATTCTCCCGCACCGTTGGAACAGCTTGATGATTGCTGCTAAAGTGC
          GCTCTGTGGCTCCCGCGGTCCGCCGGAGACTCACATAGTTAATGCCAGTCGCGACGAGTC
          ATCCTGTGGTTCTGGTGATCCCGCGATGACCTACAAATCAATAGTGCATTGTTACGAGTC
          AGCCTAAGGCCTCTGCCGCTCCACGATGCAACGTTACTCAGTGATGTCCCATGCGCTTCT
          GGCCTACAACTCTAGAGGCACCTTGCCACGACATCGGCCCGCAGTCCACCCTGCGGGTCA

          CAACGACAGCTAGGAGCTTAACAACTATGCGGTGTACCGCTGGACCATTGATCCACGCGC
          CAACAACAGCTAGAAGTCCAATAATGATGCGGTGTACCGTTGGACTAGTGATTCACGCGT
          GGGCGGAGATCAGGCCTGCGGTAGTCTAGTCGAAATGTGCTAGGCTACAGTTTAGTCTGA
          GGGGGGGAACCGACCCTCTGGTGGTCCAGCCGAGAGTCGCTAGACGATTTCTTTGTCCAA
          TCTATGTCATCAAGTTTTCTGCAACACAGAACTTTATCGGTGGACTTGAACACCTTGCTT
          CCTATGCGATTCTGTCTCCTGCAACGCAGTTCTTTTACGGCGGACGTTAAGTTTCTACAT
          GTCTTGTGTCTGATCTCATCGCATAGCGGTCGATAGGCGCAGCTTCGGCGACTCAACAAT
          TGCCTACGTCTTACATCGCGACATTGTGGAGGCCCATCGACATACATCACACACGGCCCT

          TAGTGGTAAGACCTGATTTGCCGAGATCGTTAACGTAGCGCAGAACTCTGAAGTATACTA
          TTGTGGTAAGACCCGACTCGTCGAGATCGTTAGCGTAGCACAGAGCTCTGAAGCATATTA
          CTTTTTCAACATTCAGGTTCCTACACGGGAAAGTATGGAACACAGGGGTTGCGGGAACCC
          CACTTGGACCCCATATCCTTCTACACGGGAGAGCATGGTATACCCGGGTGGCGTCGATTC
          TTCCAGCAGGATTCGTACGGGGGTATCGACCTTCCCCATCAACAAACTTATATAAGACCT
          TTACGGTACGGTGCGCACTCGGGTATCTACCCCTCGGTCTCACAGGCGCTAATTTAGTCT
          ATTATGGAGATGTAGGTTTGGAGTGGAAGGCTCCAGGCGGGGGCCGCGAGTACTGAGTAC
          CTCTGATAAATGAAGGATTAACATCGGAGTATCTAAGACCGAGAGCTATCTACTCAGTTC

          GCGCAGTGGCATTTCCTGTAGACGTTCCAGTAGCCTGCTATTAGAGCAGAACCAGCCTGA
          ACGCGGTGGCATTTCCTGTAGACGTTCCAGAGGCATGCCATTAGAGTAGAACCAGCATGA
          ATTTGGCAATCTCAATAAAAAGTCTCTACGCGGCTATGCACTAACGCGGTGCTAAATCAT
          ACAGGGTTATCTAATCATCAAGGATCGCACGGGGTATGCGCCTATGTCTCGCTTGATCAC
          ATACTGTTGAAGAGTCTGAAAGTGTCCAGATCGATACTTATCGGTGCGGCCTTCGTTAAT
          CGGCTGTCGTGTGGCGGATAAGTGCCCAAGCCACCACTAACTGATGCAGCGCTCGAGTAT
          TCACTGGTGCTTTCCCCATCAGTAGACCGACAGCCCTTACCTAGAACTGCGTTGCAGCTC
          CCAAGATTCCCTGCTTCATAGGTGCTCCATCTATTAGCGAGCAAGGCTGAGCGCGAGGAT

          TGAGCCGATAGCAGTGAGGCGCACGTGCCCTCATGTGCCCCTTGCCCGAGCAAAGGCGAG
          TGAGCGGATACCAGTGAGAGGCATGTGAGTTCGTGTACCCCATGCCCGAGCAAAGGCGAG
          CCGTTTTCCGATGGCACAACTCAAATTGGGCTATAAGGATCATCTCGCAAAACTCGTGAA
          GAAGCACGTGATGGAGAGGCATAAATCTGTCTGCATGTACAACTCTGAACATCACGCGAT
          TAGGTGTGTTACTGAGAATGTCGGGGGTGACTTCCGGCCCTGTGGTGATCTTGTCACATT
          TATGTGTGTTGGTAGCAATGTTACGAATGATTGCTGGACTCATAGTAACTTCGTCATGTT
          TTAGTGCCTTGGTGCTCGCTCGACTGGTGAACGTTGAGAATTGAATAAAATTGCCGTGGC
          TGATTGGAGTGCCAGGAACCCCACAGGTGTCTGTGAAGCCTGTAGTAGAGCTGGTGCTTC

          CTTTTCCTCACGGCGTCGATGGGACTTGACTGGGTTGACCACTATTTGGGAATCGGAAGC
          CTCCTCTCCACGGCGTTAATGGGACTTGACTGGGTTGACCACTTTTTGAGAATCGGAAGC
          ACTTTTCTTATAGCGGCCACAGGTTTCCGAGGGTTTTTTCGTATCCGACGCGACTGTGCA
          ATTTTCTCTACGACGCCTACGAGCTCCCGAGGGATTATTCGTACCCCGTACAGCAGCGCA
          GTACCCCCACCGAGAGCCTCTGGCTCAGTCGTGGCCTTCTCAACGAGAAGCAACGTAAAG
          ACCCCTGAGCCAAGAGTCGCTGTCTCCGTGAAGGCTGTCAGAACGAGTGGCTTCGTATCG
          ATTCCTCTTATCAGGTTCATACCTTCCGCCTGCGCAGTCTGGACGAACGGTCAAAAGAGG
          AGCATCATGAGAAAGGTTATAAACTCCATAGAAGCAGTCAGTGCCGAAGTTATCAGTATG

          GAGCACGGCGGCAAAGGTCGTAGGCATAACGTCTCAATTCTATGGATCTTAGCATCTCTA
          GAGGACGACTACAACAGTTGTAGGCATCACATCTCAATTCTATGGATTTTAGCATCACCA
          GGGCACCACGAAGCTGGATGTGCAGGTAATGATACGAGTCTGCGGATTTATGTCATCGCG
          AGGCGTCGCGAAATGCATAGTAAAGCGACTGAGATGAGCGTGCGGTCCCTTGCTAAGGAG
          AAACAAAGTTGTCTTCATCTTGAGTTAGATCTCTAGTGAATCAAGGACAGAGCCGTCCAT
          GTCCGAGGATGGCCTCAACTTGAGATAGACGCTTAGTATACCAGAGTTAGGGCCGTTCTT
          GAGCTCGATAACGCTCCTCGAAAAACACACTCATCGTGTACACCGCCCGCTGTACTCCGC
          AAGCAAACTGGCGACCATGTCCACCCATGTCAGTTGCGCTACTGGACGCGCGCATCCGAA

          GCTATTTAAAATGCTTGGGTCCGAAATACAGGTGTAAGGATGACCCGCCGAGCTCCCGCT
          GCTTTTTAAAATGCTTGGGTCCAAGAAACTGGTATAAAGATGACCCGCTGAGCTCCAACT
          TTTTTGTGGCACCCTATAGCCTCTAACTTCGGAAAAAGCCCACGCTACCACGGAGGTATT
          ATACTGTGTCACACGGCCGTGTCGCAAATTGTAAAACGTTTAACCCATTCTGGGGGCACC
          GCGCTGACGAATGGAGCTGAATCCACAAGGAGCGTACGGTTCAAATACAAGTTCAAAGCG
          GAGTCGAAGCATCTTGTTGAATCAATAAAGAATTTACGGTCCACATACAAAGACAAAGCA
          GGCAAAGAACATAATACTTGAGTCCTAACAAGTAAATGGTTGCCAAGGCAGAAAAACGTC
          GTTTAGTAGCGAATAATCGCATTGATAGTTAGCACATGTCAGATTTGCCCAGAAAGCGCT

          TCAATGGTTCCCGGGCGGGTATTCGCAACCATTGAGTGCCCGAGCGTAGTCGTTAACAGA
          TTAATGGTCCCCGGGCGGGTATTCGCAACCATTGAGTGTCCGCACGTTGTTGTTAACAGA
          CGGCCCTAGTCAGGGATGGCTGAAGCCAAGGTAGCGTACCCTGGTCCGCTGAGGTACCAA
          TTGTCCCTTACAGTAGCGACTGAATCGATTGTAGTATACCCATGTGCGACTGATAATAAA
          TCTTCACCGATTGTAAAGACCACACTCTAGACGGATCCTTTTAACTGGGTCGGTACCTGG
          TCACCTTCGTCTGAAAGGTTTACACCCCAGAGGGACTCACTTGAATAGGTGAGGACGTGG
          CCCGACCTGCTCCATAGAGCGATACCTACATTGGTATTGCCCAGGACTGCGCCCTTCGCG
          TCGGGGAAGATGAAATCGTGCGCTCTTAGTGGGGTCCAGCCCCAGTCGCCGAAAACCTGA

          TATTAAAGTAGCTTCGAGTCCTTACAGCGCACAAAGCGCGTGCCTCGTGCGTTGTGTTAG
          TATTAAAGTACCTTCGAGTCCATAGAGTGCACAAAGCGCGTGCCTTGTGCGTTATGTTAG
          AAATGAAATCCATCTTAGCTCTATTAATAATCAAGGTCTTCTGATAATTTACCGTGATAT
          ATTAGGACACTCTACCAGTCCTAGCGGTAAGCGGCGACCTTGCCCTGTTTGTGACGAAAC
          TGATACATTCACAAGCGCTAGCCACGATGCGCTAGTGTCCCAGCCGCTCACGCGGTAACT
          TGCTACTTACCCAAGTACAAGTGACGTTGTCTTAGTATCCTTGCCGCTAACATGGCAACC
          CGTTGGACCTTTAGTCTTACCTTGCACCATTTAAGACAGAGTGCCCTTAGTCTAGCACTA
          TGCCGCTTCGGCGACCTCTTCCGGAAATAAAACGGTACATAAATTGATTGTTTAGTTCTA

          CTCCACGTTCCTTCTCATAAAAGCATATTCCGTGGTTGCGCATCCCGCCTTACTCCGGAT
          TCCCACGTTCCTTCTCACAAAAGCATATTCCGTGGTTACGCATCCCACTTTACCCCGGAC
          TCATGCGTCCGGTATTATAGAACTGAGTCTCGTGAAAGCAGCGCGCATGTCAGACCGGCC
          CTACCCTACATTTCCCTCAGAGATGATCACTGTCATTGTTCCACGCGCGCATAACCGACT
          TCAGAGAGTCTGCCTGGTATGTCACCATCCGATAAAGTTGAGTTATGATTAAACCAACCC
          CAAGAGTGTTCATCCGGTATACTATCATTGAATAAAATTGAGATATGATTAAAACACACT
          TACTGCGATTTCTTGCCCGACCACCCAATGGATATTATCACAGTTTATTTATGAATCTTT
          TAAGACGACAGCTCCTATTGTATCGCCGAGAGCTGCGCCTAGGTTATAGCCCTATCAGCC

          ATTAAAGCTTGAGCCTGGTAAACTGTGATTCACACATCTG
          ATTAGAGCTTGGGCCTGGTAAACTATGATTCATACACCTG
          GTTCATGCCTGAGTCTCGTGGAGTGTGCATCGTTTGCTTT
          GTTGACGTTCGAGAGTGATGGAGAATGAGACGTCCATTTT
          TTCAAATCTGACGCTCGATGGTGTCAATTCTGTACTACCT
          TTGAAATCACACGCCAGATGGGGACATCTATGACCGCCCT
          AGAAAAGCCTCAGTACAATGCCGCGTCACTAGCGTCCGCT
          TTGAACTCTAAGCCGCAACGGAATGCCGCTTATGTCTGAC

