 8 1000
t1        GTAACCGTATGAAAGGAGGACCTTTTGATAAGAGCTCCACACGACATCAACGAGCGACTG
t2        GTAACCCTATGAAAGGAGGACCTTTTGATAGGAGCACCACACGACATCAACGAGCGACAG
t3        TTGAACCGTATTGAATATGCCTCCCTTATTAAAAGGAAGCACACTGCGGCCAAATCCGCT
t4        TTGAACCGTAGTGAATATGCCTCCCTTATTAAAAACAAGCACACTGCGGGCAAATCCGCT
t5        ATGGCCTTTTACAGATACGCGAAGCTCGATTGGGTTTTAAGTTACGCTGGACAAAAAAAG
t6        AAAGCCTTCTACGAATAGGCGGACCTAGACTGGATCTTAAGTCTCGCAGGTCCAGTAAAA
t7        AGGGTCCTGTACGGCCGGGCGGGCTTTGCGGGGCCTTTGTCTTTAGCCTGCGGACCTGGA
t8        GGGGCACAACCTGCAGAAGAACCCTTACCACGGAGCCCGTAGAATGTTGGCCAGGCACCT

          AGCTTTCCAATTTAAAGTCGGGTCGATGTTCGTACTTCCTCTGGCGGCTCGTGTGCTCCC
          AGCTTTCCAATTTAAAGTCGGGCCGATGTTCGTACTTCTTCTGGCGGCTCGTGTGCTCCC
          CGAGATGACTCACGGTGCATGACCGGGAACTTCACTTCTCCTAGTGCCCTGCGCACCTAA
          CGAGATGATTTACGGTGCATGACCGGGAACCCCACTTATCCTAGTGCCCTGCGAACCTAC
          TTGTTTCTCTGTTGGCGATTTGCCAACGCCTCTATACGAGTCGGCAGGCTTTATAAATAT
          TCGTATCTCTATCGATAGCTTGCTAACGTCCCTATACTAGTCGGGAGGCTTTGTAAATAT
          CGGTCAGCCTCGTGTCCTAATGACACCTACCTCATCTCGCCCCACGGGCTACCCACATCC
          TGACTCGTCCATTGGGCCTACGAACCTCTACTGATGTTCAGCGTCGTGTTTTCCGAGCCT

          TTAGTATTGGTCGGACCGAGCATGAAATCACCAGGATTAGGCGTCCTCACCGTCATATAT
          CTAGTATTGGTCGGACCGAGCATGAGACCACCAGGATTAGGTGTACCCACAGTCATATAT
          GTAATGCTAGCTGATCGACGAATAGACTTTTTGGAACTGTTTGGCTTTAAGGAAATGATA
          GTAATGTTAGCTGACCGACGAGTAGACTTTTTGGAACTGTTTGGCTTTAAGGAAAAGATA
          GTCGATTGACTAGAATTACCGATAAACTCATCCGTGAAAAGCCGGGCAAACGTACTTTCG
          GCTTACTAAGTAGGATTATCGATAGACGTCTATGCAAATAGTCGAGTTAGCATACTATCT
          ACACCTCCGGCAAGTCTGCCGGTTGAACTGTCAGGGATCGGTTGCCGGACTGTCTCACCG
          TTAGGTTTGACTGGTTTGCGGACCTAGGTATGGCAGTCCACCTGCGCTGGGGCTTGATCG

          GCTAACGGCCTCTGCTATTGTGTTCGTAATTAGATACGTTTCAAGGCCATTATAATTCCG
          GCTAATGGCCTCTGCTATTGTGTTCGTATTTAGATACGTTTCAAGGCCATCATAATGTCG
          GAGCTTAAAATTAAATAGAGTACCCGGCCCTTGATGCGTGTACGAAACGGCTTGTCGACA
          GAGCTTGATATTAAATAGAGTACCCGGCCTTTGATGCGTGTACGAAACGGTTTGTCGACA
          GATGGGGTACTTTAGCGTGTTGCCAGATGCAGAATGTCCGTGACAATTGGATATCTTTCG
          AAAGGAGTGCTTTAATATGATGCCCGATGTACAGCATATATGACACCTGGTTATCCTCTG
          AGTCATGTCATGCCGCATGGTGTCCGATGACGGAGGTATATAACGCTGAGTTCTAAGCTG
          GGCAGTTGTGGGCGATACAATGTCGGATTCGGGGCCTATCCGGCGATCAGTCCTACTTTG

          GCAGCTCGCCTTCTGTCCGGTCTCCCTCCTCTGAGTCCGGCCATTCGATCGTAAACAAAA
          GCAGCTCGCCTTCCGTCCGATCCCCCTCCTCTGAGTCCCGTCATTCGATCGTAAACAAAA
          GACTCGACTCTCATGCTCGCGTCCGCATTTCTGAGGTCGGCTATGCGCTTCATAACTGTT
          GACTCGACTCTCATGCTCGTGTCCGCATTTTTGAGGTCGGCTATGCGCTTCATAACTGTT
          CCCGTCTCGCTTGTGCCTACAATTACTTTTCCGGTCGCGAGTCTTTAAGATGAGCAATGA
          GCCGTTTTCCATCTGTCTACGAGCACTAGTACAGCCGCGAGTCATCAGAAAGAGAAATGA
          GGAAGAAAAAATATGTCGATCTCCATCTATATGACCCTGAACGTAGACTCCTACATCCGA
          ATCCTTGGACTGTTGCCGACAGTCGCCTCCTCTTTTCTAAATATGAAGTGATCTATACCT

          CTGCCTCCCTAGCAGATGTCGAAACAGTCCTTCACAGCTCCGCGACTCGTACTATCCAGT
          CTGGCTCCCCAGCAGGTGTCGAAACAGTCCTTTACAGCCCCGCGATTCGTATTATCCAGT
          TTGACTTCCGTGCAAGCGCACTGGCTGGTCTTTGGCCGTCCTTGCTCTACTATCGCAACC
          TTGACTTCCGTGCAAGTGCACATGTTGGTCTTTGACCGTCCTTGCTCTATTATCGCAACC
          GGAAATCACCAGGAAGCAATAAAAGCACTCCCCTGAGGCTTTTCCTATTAAACCTGTATC
          CGAAATCGCCAGCAGGTACCAAAACCATTCTCCTGAAGCTTCTCTTTACCTGTTTGCAAT
          CGTTACTATCTGCAAAGGTTAAAACTAATTTTTCCCATACGACCTGTCGTTACTAGACAA
          GTCTGGTTCAAGCGTGGATCGACAGAGTTCCTGAGCACACTTCGTTCAGGCAGGCACGAA

          ACGCTAATTACGTTCCCATTGACCTTTATCGTCCTTACAATAGCGCTGGAGAGGCGGTCA
          ACGCTAATTACGTTCGCACTGACTTTTATAGTTCTTACAATAGCGCTGGCGAGGCGGTCA
          CCCTATAACATATTCCCCTTGGAACTTCTCGTTGCTCCAAAAACGCCGGAGGAAAGGCTA
          CCTTATAACTTATTCCCCTTGGAACTTCTCGTTGCTCCAAAAACGCCGGAGGAAAGGCTA
          CAACATACAATGAAAGATTATGATTAATAGTTCTTTAAGAGTCAGCTAATAGAAGACTCA
          CAACATACAGTGACAGCCCATGATTAATGGCTCTAGGAGAGTAAGCTAGTAGAAAATTTA
          ATGTTCATGATGAGCGCCGATGGTTGATAGATCTCTGAGACATGGGTGGCCGCGGATTTA
          GAATGCACCGTAAGTGCTCCTAATCGACATACCTAACAATGGTGCACGCTCGGGAGTAGA

          TACGAACCAGCCTTTATAGGATAATGGGGGCGCGTTACACCGGTTAAAAAGTGAGCAGCA
          TACGAACCAGCCTTTATAAGATAATGGGGGCGCGTTACGCTGGTTGAAAAGTGAGCAGCA
          GATATATAGTCCCCGACAGGGTAAGTGCGGACGCGATTTGTTGTGCGAATTGAGGCGCAC
          GACATATAGACCCCGACAGGATAAGTGCGGACGCGATTTGTTGTGCGGGTTGAGGCGCGC
          GGGATCTTCACCTAGACGAAACAAGGGAGCTCTCGTTCTGCAATAAAAGTGCAGAAACTC
          GTGATCCTTACCTAGACGGGATGAGTGAGCTCCTGTTATGCAAAAGGAGAGCAGAAATTC
          CGGTGCTAACTACGGGTTGACCAGGAACGTCCCCGTACGGCGTTAGTAGCGTTTGCAATG
          GACTATTTTGACCTGATGGTGTAAGTGGATTGTCTGGCCCGAGCGGAAGTCCCTCTAACC

          CCTTACGATTGGCTGCCTCCATTTTGGGGGCCGAAATGGACTCTAAATGACGCGTGGACA
          CCTTACGATTGGCTGCCTCCATTTTGGGGGCCGAAGTGGACTATAAATGACGCGTGGACA
          CTTTCAGATTAGCTAACCTATTACCAGGGCCCTAAACAGATCCTCATAGAACTGTGGATG
          CTCTCAGATTAGCTAACCGATTACCAGGACCCTAAACAGATCCTCATAGAACTGTCGATG
          ATTCTCATCAGAACCATCGGCCATCCGGGAGCCCACCCGTTCACGAACTTGGTAGAACCT
          GCTCCCATCAGAACCGTCAACTACCCGAGAGCCTAGGCGCAGACAAATCTGATAGAGCCT
          AGCCTCGTATCATGGCATCGGTATCTGACATTTCAGTGCTGACTCAGCGGCGTGGCAGCT
          ATCTTTTTATGGTACAAAGAGTGCCAGCGATTTAAATTACTGAAAACTTAGGTCGCCCTC

          GGCTACCAGAATCCGAAGTGCGTTTTGAGACCAGAACTTAAGTTAGCCGATCTATCCGTT
          GGCTATCAGAATCCGAAGTGCGTTTTGAGACTAAAATTTAAGTCAGCCGATCTATCCGTT
          GACGGTCACAACTGCATCTGATTTTAGCCGTACGGTTTAGTATTCGACAGTCGGCATGTG
          GAAGGTCACAGCTGCATCTGATTTTAGCCGAACGGTTTAGTACTCGACAGTCGGCATGTG
          AACGTGCTGCGACGCTAACGACATACGCATCTGGGATGCGAGCTTGTTCAACGGGTAGGG
          AGCATGTCGTGACATTAAAGATATACGCATTCGGGATGCGAGTCTGTTTTACGGGTACAG
          CTATGTGTGGGGTGTACGCGTCTCAAGCGGAGCAAATGTGGGTCTATTCGACGATGACGG
          CAGGGATCCAGCCCATGAGACGTTGATTACTCCGGTCGCCTTTGTACATTCCGGTGGTCG

          TAGGCATGAGCTTTTCATCCAGCGCTGTTCGTTGGGGTAAAGGTACGCCTGATCCTGGGG
          CAGGCACGAGCTTTTCATCCATCGCTATCCGTTGAGCTAGAGGTACGCCTGATCTTGGGG
          CACGCTACTATTTTTTATTCGACGTAGATTGCTCTGGTGATGATTAATTGCAACTCGCAG
          CACGCTACTATTTTTTATTCGATGTAAATTGCTCTGGTGATGATTAAATGCAACTCGCAG
          CAAACGACCAGTATAGATTTATAAACCTGGTCCGAATCGGGGGTTGAGTACATCCGTAGG
          CAGACGCCTAGTTTACGTTTATAAGTCTGCTCTGGATCATGGGTTGAATACATTCAAAGT
          CTGATGCTGTCAATCCCTCTAATAGTTTATCCCAGACGAGGATCTCAACATGTCCGTGGC
          CAGCTGTTCGATTGCGTCGAGCAAATCGCCTCCGATCCGGGACTTCATAAATTTGGGGGC

          GAAAGTCCTTTGAGGGAATAAGGGTTTCACTGCTGCCGATGTTTAGACGCGCAACGCTCA
          GAAAGTCCTTTGAGGGAATAAGGGTTTCACTACTGCCGATGTTTAGACGCGCATCGCTCA
          TAGAGCCGATCTATAGTGCCTGTGTTTCTGTGTACCCGTCCTATAATTGCCTACACTCAG
          TAGAGCCGGTCTATAGTGCCTGTGTTTCTGTGTACCCGTCCTATAATTGCCTATACTCAG
          GTAGGGTGTAGCTAGGCGTTGGAAGTGCGTTCGCCATAATAAACCCTGGCCGAAAGCTGT
          GCCAAGCGTAGCTAGGCAATAAAGGTGCGCTAGTCATAATAAACATTGGCTGAAACCAGT
          GGCACATGTTAGTCAGAGTTGAAGTCAGGCTACGCAACGTGCTCTGTCACCGCTGGCTCA
          GCACAGCGTTGTCTACGGAGGACGAGACGTCGAGTCCGGAAATTCGGCGAAGCAAGTTTG

          CGAATTCTTACAGGATATGACCCGCCTTCGGTAACTCCTTAATCGTCAAAGTCCCGTAAC
          CGAATTCTCACAGGACATGATTCGCCTTTGGTAACTCTTTCATCGCCAAAGTCCCGTAAC
          GGTATCTACAGTAAACGGTGCTCATGCCGTATTATTTCTCTATCGTGATAGTTTGTCATT
          GGTACCTACAGTAAACGGTGCTCATGCCGTATTACTTCTCTATCGTGATAGTTTGTCATT
          TATACCCCCCGAAAATATTCTTTATACGCTGTTACTCACTTATTGATCAGACCGAGCATC
          TACCCCGCGAGAAATCATTCTTAATACGTTGCTACTCACCTAACGTTCAGACCGAGCATT
          AACCCCGGCGGACTGTCTAATCTATGCTTCGCGATTTGCTCACCGTTCTGATTGGATCAA
          TACGTCCTCGATCAGGTCGATTTAGTCTTCGCTTCCATGCTTTGCACTGCATCCGCTTCC

          TCGTCTACGGATCCACCGACTCGTTTACAACCGCCCCCAGACTAACCAAAGTTGAGAATA
          TCGTCTACGGATCCACCGACTCGTTTACAACCGCCCCCAGACTAACCAAGGCTAAGAATA
          GCTACGTTAAACGAATAGAGAGGAATTATACGGCCACTTGGCCAGCTAGAGTAGAAGATG
          GCTACGTTAAACGAATAGAGAGGAATTATATGGCCACTTGGTCAGCTAGAGTAGAAGATG
          GTCTAGACAGCTTCCCGTGACGTATGTGAACAGCCGACCTATGCAATCCAAACAGGAGCC
          ACCTAGCCAGCCCCACGTGACTTTCGTGACTAGTCGACAAATGCAATTACAGAACGAGTT
          ATTCAGATGGTTTTTTGGGAGTATTCCTGTTAGTGGAAACCCGCACCTCAGGAGAGGGCT
          ATGCAAATGACTCCGTCCAAACTCCCTACTGTGTAAACTCACTCTCACGAGATGCTGGCC

          AAGTTGCTACACGAGGGAGGGCTTGCAAAGCTCGTCTGCTGGCACGTAACACTTAATTTA
          ACGTTGCCACATGAGGGAGGGCTTGCAAAGCTCGTCCGCTGGCGCGTAACACTTAATTTA
          GTTCGCCGCTCAGTCAGACAGAATTCCGGACTCACCGGAGGTCGTTTGCGCTTCGAGTCA
          GTTCGCCACTCAGTCAGACAGAATTCCGGGCTGACCGGAGGTCGTTTGCGCTTCGAGTGA
          GTTAGTCAACTGTCGAGCCCGTTCCAGCCCGAGATGGACTCCATGGCCTCAAACTGGATT
          ATTTGTCAACAGTTGTGCCCGTTCCGGCCTGGGGTCTACTCCGTGGTACCAAGCCAGACT
          ATTAGTTACTCCCCGTCGCCAACGCTGCTCTAGGGTATTTGTGCACCATCTATCTTGGCT
          CCTAGGTCAGTCGTGGCTATGCCTCTGGCCAAGGGGACACACGATATCTCGACTCTGATC

          AATCATCCAAACGGTGCCCGATTCGAATTAATACGAGTAGCGGGTGGCCCTGTAGATTCG
          ACTCATCCAAATGGGGACCGATTCGAATTAATACGAGTAGCGGGTGGCCCCGTAAATTCG
          ACTCATGCCGCTGAAGTCCACACTGCAGCAGGACGAGCTGGGGACACTCTAATACTTACG
          ACTCACGCCGCTGAAGTCCACACTGGAGCAGGATGAGCTGGGGACACCCTAATACTTATG
          AACGCCGTGGCTCAGGTAGATGCCCGACAGATACACGTAGAGTCTCGATAACGCCTGCCG
          ACCGCAACGACCCAAATAGATGCTCGACGGATACATGCAACGACCCGCTAAAGATTGTCG
          GTCGACATTCGGCGGGAGGGGGTCATAAGTTCTTCTGCGTTATCTCTCAGAGCCGTTTGC
          ACCGCAAGCACATAGGAAAGTATCTGGTATACTTCTCAAGCCGTACAAAGACGTTTCCCG

          CATTATATAGCAGAATGCCTGTGTTGCCGTGTCCGCGCGC
          CATTATATAGCAGAGTGCCTGTGTTGCCGTGTCCGCACGC
          CATTAAATTATGAGCGGCCCATTGGGAACAGCTGGCGTGA
          GATTAAATTATGAGCGGCCCATTGGGGACAGCTGGCGTGA
          TTACCCATAGTGTCCTGCCCAGTGCGATCGTCCTGAGCAC
          CTACTAACCGTGTCCTGCTCAACGCGACCGTCCTGAGTAC
          TAACAGTGAACCTCCTGACAACTGAAGACTATTAAGGAGC
          CCGCAGCATGCTGGGCGCGCAATCCGATTGATCAGAGAAC

