 8 1000
t1        GTTGGAAGTGATGAGTGGAACGTCTACCGAGGGGGCATATGCCAGTTCGGCGACAACGCA
t2        GTTGGGAATAAAGAGCGGGACGTCTACCGAGGGGGTATATGCCAGGTCGGCGCCAACGCT
t3        GTGGGGCGAACTGGATGGAACGCACTCTAGGAGGGTGTACGCCAGGCTGGCGAAAATGCA
t4        ATTCTGGTGAACGGTCGGAGTAAATCATGTAAAAGTCCTAACTTTGCCAGCGGCGATGTG
t5        CGTCGGGAGGACAATTAGTGTTCTTGTCAGTGAGACACAGCTCTTGGTTTTAGAGTTGCC
t6        ACCCAAAGCAATGTCTCGCCGGACTGATACGGATAATTTAGGTACACTGGCGGACTTGGA
t7        AACCAGAGGCTCAACCGGCAGTCCCACCACGTGACATGTTCCCGTGCCCGTGCGGCAGGG
t8        TGCTTGAGGCGCGATCAAACGCTTTATTATGCACACACTGATCCTAGGGAGAAGGATGCA

          AGCGGTGTTTGGACATAGACTTATATCTGCATGTTGGCAATAGTGGCATTGGATTGATAA
          AGCGGTGTTTGGGCATAGACGTATGTCTGCATGTTGGCAATAGTGGTATTGGAACTATAT
          AACGGTGTCCAGGCATAGATACACAACTGTGGGCTGGAAACAGTGGTATTGGGACCAGAG
          AATGGACCCTGAAAGCAGCAATGTACGCTGATACTGCCCACTGATACAGTGGTTCTGTAT
          GGTGTTACCACCCAAAAGAGTCTCCCACACAGAAATCTGACTGGTGCCCTAGACTTGCTG
          AGTAGCCTCCAAGCGCAGCAATTAAAGTTGAGGTTAGTAGTAGCCCTCATGCGTTTGTAG
          AACCCAGCCCGCAGGTGTTTAAGGGACTATGGGCCACCGTTCTTAGGGATGTATCTTTAG
          TTGGTAGTGAAAAGGCGCGCACGCATTCAAATGTCAGCACCGGGATGCCTAACACTTCCA

          CTGCCGACGACGGTAAATCGTCCGAGCGGTTCCTTGGCTGGGTTGGCGATCCCACACCGT
          CTGCCGACGACGGTAAATCGTTCGAGCGGTTCCTTGGCCGGGCTGGTGATTCCACACCGT
          TCCCTGACGGCGGAAGTTCGCCCGCGCGTCTTCATAACCGGGGTGGTGACCTAATTATAT
          GCGTGCAAAATAGTAACTCACCATCGGACTCTACGTAAAGACTGGGTGACTTTACCCACA
          AAGGCGTGAAAAGTGAGCGACTTAGAGGCTGTCTTGTCCATGTCCGTGAATTGATTGTGC
          TAGCAAGAAGAGGTGGCCCATAGCGGATTTCCCCTGTTTGGGCTTGGGATTCTAAGACAA
          GCCTGCTGAGTGCGACGGTTACCTTAGACCTCTATGTCGCATATGGCGATGCTATTCGTG
          ATTGGAGGAATGAACGACGGTTAGGGAAACTTCATTTCCTGTCGGGAAAAGCCTTTCTCC

          CGATAAACCGAAGTAACACTATGATTCAGTGAGTCCTATTGCTGAAATAGACTGGCTATA
          TGACAAACTAAAGTGATAATATGATCCAGTGATTCCTATCGTTGAAATAGACTGATTATA
          AATCAAACGGAAGTTACGACTCGACCTCATGGACAGTTTTACTGAAACAGATCAACCATA
          GGCTGTGAGAGGAAGAAAGAATCTCTCATTGGATAGTGGCAATGCTATAGGTCGAACACT
          ACCCGAGCCAGCAAAACAGCACTTGTGGTTGGTTCATCTTAGTCGCGGAGATTAGGCATT
          AGCCAAACCAAACTGTCGCCTGAGGTCGCCAATTTGTGAGATAGGCTCAGGTTGACTGAT
          AACTACAAGGAATCGCTGGGATTGCGCATTGGTCAAAACGCCCCACGGGGGTAAGCCATG
          GGTCATGTTGGACCCATGGGTCGGCGTAGTGTCCATAACACCCCGTGTGAACCTTCGCCT

          TGCTCAGACCGAGGGGATATACGAAGATCCTGATGGTACCAAGATTAAATGTGCCGAGGA
          TGGTTAGACCGAGGGGACATACGAAGATCCTGATGGTGCCAAGATTAAATGCGCCGAGGA
          TGCTAGTCCCAAGGGCATGTACGGTGCTCCCGCGGGAACGAGAACCTAGCGTGTTCGGGA
          TAAGTACCGCACAGGCTATCAGGTTTGGACTAAGTCCTTGGGAGCTAAGCGGATTCGAGC
          TATACCACCGAGTCGTCCGTCCGTCTATTTTATACCCATCAAATACCAACATGTAGTGTG
          CATCCCACCAAGAGACTCTTCTGTCTATTCCAAGAATTCAAGTGCCAAGTATCGTGTGCG
          GTAATCCCTTAGGTTATGAACCACCCCGCAGTGTGCGACCAGGGCTCAACCGTACAAGCG
          GCAACCAACAAGACGTTAAGCCAGCAATCCCCGGTTGATCAAAGCTTATCCGCGAGAGAT

          AAAACATCTCGGTCAGTCCCGACAAGCGATCATGGTAGGGGCTCACCTACTCATATTATA
          AAACCGTCTCGGCCAGCTCCAACAAGCGATTATGGTAGGGACTCTCCTAGTCTTATTATC
          ATAATGACCTGGCCAGCTCAAATAAATGCATCTGGAGGGAGCTCTACTACTCCTCCCATA
          CTAATAGCGTAGTCGAAAGAGCTGTATAATTGCGGCCATGATTTCTTCGCTAACTCATCA
          TTGACTAATCTGGCGAGGTCGCTTTGCGGTCTTGATCCTCGTTACTTAGACACTTTCATG
          ACAACACTATAGTAGGGGCTAATACAAGGTGTTAATAAAGCAGTTCTCGGCCAAAGATCA
          TCTCTTTGATCGTTGCGGTTCGTGTTTAATCAGTATAAGTTAACTAGTTTTACCAAGTAA
          TAACTTACTCGGTGTCGGCATTCTTGGCCTTGTAGCTAAGGACTCTAAACACTGCAATAA

          TCCGGACTGCATATGTATAGCACCTCCGACAGGTCACTCCTAAAATCCAGCGGTCACATA
          TCTGGCTGGCATGCTTACAGACCCACCGACGGGTCACTCCTAAAACTCAGAGGTCAGATC
          CCCGGCCGGCAGACGCATAGTGACGTCACCGGATCTCACCTAAAATTCAGAGGTAAGATA
          CCCGGTAGACTTCAGTCTTGTCCAACCGCGGAGCTAGTTTTGTATCTTAGGGGGCGGATA
          TTCGATTAATCTACTAGTCGATGTGTCCGGGGGCCCGCTGCCTTACCAATCGATCAGGTT
          ATAGACCCTAACAGTGAATCGTCGGCCTAGGCGTCACACGCGGCGATGATAGGCAGGACA
          ACGACCCCGCGTGGTCATGACCTTACAAGCGATCTAGTTAAGAGACCAACCGGATTGGCA
          AGTGGTGAGGGTAGGAAAGGCACATTCTAGGAGGCGATTAGAGTGGACACTGGCTCATTG

          TTGGTTGCTCCAAGGAGATTTTCTTCGAGTGTTCCCGTTAAAAAGGAAATAATTGGAAGG
          TTGGTTGCGCCAAGGAGATTTTCTTTGAGAGTTTCCGTTAAAATGGAAATAATCGCATGG
          TTAGTTGCGCTGAGGAATAATGCTCTGAATGTCCCCGCCAAAGAGGAATTTAGTGCAAAG
          CAAGTCACATAGAGAGTCGATTTCTGTGGAGCCCTTCGCTAGTGCGGGGACGCTATTAAA
          TTTCCGGTACTATAATTGTCGACCCGGGCAGTCGCCGTTCTGTGCGAGGTGCATTAAACG
          CCCACAAGGTTGCTAGAGGTATCCCGATGTGTTTATGCTCCCAGGGCGCTTAGCATCGAG
          GAGGCAGCCGTAGGGCAACGTCTCCTCGGAGCCAAAAGTTAGGTAATGATGTGAGACAAC
          GTGATGGAATCGAGTCAGACTCTTTGAAAAGTCCTTTTCGCGCGGGTATTCTGTAAGGAA

          TGTTCTGGTGTGTAGCCTGCGTATTATCGTGTGACTGCATCTGGCAACGTATGTATTCTG
          CGATTCGTCGTGTATAACGTGTTCTATCGTGTGACTGCATCTGGCAACGTAGGTAATTTG
          CAATACGCCGCGCAGTAGATAGTTTGCTGCATAGTTACAAACGGCAACGTAAGCACCTTG
          GCTTTAGTCGCCATGCGTGTCCGCAGCTATCTTTTTGTGGAATCGGATGCGTCTAGCCTG
          GTAAATGTGGGATGACAACTAGGCTACTGCCACATTGCGAGTTGCGCAACAAGCAGCCTG
          CTTGATAACAGATTCCGAGTTGACAATTGGTCGCTCAGCTGCAAGGCAGAGGTCGATACA
          CCTTATGCCGGCCGTGATGTGTATCCAGCAACTGTATCTGGTTTGAGCGAGTCTGGGTGA
          AACTGCGTGGTGTGTATGGTAACCGAGTATCCGGTTGGAAACCTAGTTGCGACCGGATGG

          TGAAAAGGGTACTACAAACCACTGTCGCCTCCTCATAATTAAATATTATTCCAAGTCAAT
          TGAAAAGGGCATTACAAATCTCTGTCTCCTCCCCATAATTGAATATTATTCCACGTCGAT
          TAAAATGTGCACTAATAACCGCCGAAGTTTCTCGGTTATTGACAACTTTTACTTATCGCT
          AAGAAAGGTTATTAAAAGTCACAACTTTATATCGCGGAATAATTTCGACTAACCGTTCTT
          AGTTAATCGTCTCAGTAATCACCGCGGTAAGTAGCTGCTAGGTCCGCATAAGTTATTCAT
          AGAGAGACGCCCAGATGTCTTCAAGGTTATGCTGGCGTCAAACAAATAGTACCCGTTTCG
          GAAGGATGGCGTTTATCATTAGGGTCACCGCGCGGTATGAGAAAACCGACGCATGTACCC
          GGGCAAGTCAGTTTCCTATCAAAGGGATCACCCGGCGACCGCCCCGTAATTCTCAATTTT

          GTGCCCCACGGGGATGGAAAGGGTTAACAGGCTGAGTCTACTCGGAATCTCTTACAGTAA
          GTGCCCCCCGGAGATGGAAAGGGCTGACAGGCTGAGTCCACTCCGAATCCCCCATAGAAA
          GTGGCCCACGGAACTTGAAGGACTTGATAGGTCGCGTCAAATCCATACCCCTTATGGCAT
          ACGCTCTTTGTGAAGACCTCGAGCCCTCGAATTTTGCACGCCAGCGTAATGCTATGGTCC
          ACCTTCAGTGCAAGGGCAGGCAGCGTCTTGTTTATGTTATCTCGAAGTTTTTGACGGTCA
          TCTAAAGGTGTACAAGGCTCGCGTCGATAAGTGTTGGTTAAATAAGATGTGCAATGGTCA
          GTCTTTGACGGAGAATACTGCGCCGGCCGGGCAACCGTTGACATGCACGCATGCCGATCA
          AGCTCTGTAGAAGGGTATGCAGGTCCATACGCCGTCACTAGGCAGTGTGTTCAAGACTCG

          GATTACTAGCGAGGCACTAGAAGGGCGGCGGGGTTACGGAGTTGTACCGTCTGGAGACCA
          GATTACTAACGACGCACTAGATGGGCTGCGGGGTTACGGAGTTGTTCCGTCTGGAGACCA
          AAACATTAATACGCCACGAAACGGGCTCTGGGGTCATGCAATCGAACTATCTAGAACCTA
          TCCGACTGGGGAGATTCTGGCTAATTGCCATATTTACAGTAATGAAAGGTTCACAGACTG
          AGGTACCAGAATCGTAGCTAACCGTTAGCGCGGGTTAAGCGGAATAACGGACGCGGTCCA
          ATACACTGAGAGGCCACCAAGAAACCAGCAACGCTCAGAAAGGGAATTTGCAAGCGTCCA
          TCGGACACCGGAATGACTGAGCAAGAAAGGTCAAGATGAGAATTGGAAGAACGAAATTTG
          CTATTATGGCAAACTCTCGGATGACAAAAGCGGGTAATTGAACGAACGCTAAGGTTCGTG

          GTCTGTCAGTATAGATTCCGCCGCGGCAAAGTTCGCTATCTATGTCATGTCAATACGGTT
          GTCTGTCAGTATAGACTCTGACACGGTAAAGTTGGCTATCCATGTCATGTGAATGCGGTT
          GCCAGGTTATATGGTCGTTTTCGCGGTCCAGTTGACTATGGATCCCATTACCACATGAGC
          GATTACTAACGTCGACGACGCGATGATAGTGTACGTGAGCGGACCAGCTATTACCCAGTG
          GATAGAGCGCTTCAAGTGAATCCATACTTAGGGGTAAACCTAGACAGTTGCTCTGCAGTC
          AAGCTCCTGTGACAACACGGGCTTCAATGGGGGGAAAGAGATGGCATCCACGTGCGGCCC
          ATAGTTGAATGGTGGCGTGGGCTCCGCTATCTGAGAACCATTCACATCCCTACCGCGCTG
          ACGAGGGTGGACGAACCCGGTTATAAGCAGCCGTAAAGGACCCACTCTCCTGCCAGTCCA

          ATTTCCGAGTCCAGAGGTCAATGCGACCTCTGTTTTCTACTCCTGTAGGGTAGTATCTTA
          ACCTCATAGTCCTAAAGTCAATGCGGCCTATGTTAGCTACTCTTTTCGAGCAGTATCCTG
          GCTTCCAGGGTTTAAAGTCGAGATGTCGTAAGCTAGTTACTTTCGTCGAGTTGTGTGATA
          ACATTTCGGACATTGAATCGGGGTATCTCAGGATAGTCATCGAACGGGAGCACAACATTT
          CTAGCTGCGATTCAGCTTCCAAATTGACTGGGGTTTTAGTCTCGAATGGGTATACTTTAA
          TGCTCTAGCGTGTAAGCCCGTAACGGTGAGGGATAGTAACCCTGAATCTGTCAGAGCTTG
          TTGTATGCAGTTTAAAATTAGAACGGCTTAAAGAAGTTACCGAGCATCTGTGAAACACAA
          TTGCCCCACCCACAATACCGGGATTGTTCGGAGCAATCGTCACGGATGGAATCATGTTGA

          TTGGAAGCCTGCTTCTGAGTATGGTAACACGCCATTGCAAGGTATTCGCGCACCTTTTGG
          TTGGAAGCCTGCCTTCAAGTATGGTAGCACGCTATTGTAGGGTATTGGCGCCCTTATTGG
          GAGGAAGCCCGCCTGTAATAGCGGAAGCAAGGAAACATAGGGATTTGGCATACCTGTAGG
          TCAGGAGCGCGTACGTCAGCGTGGGAGTCCAGATATAAAAAACCGCGATGCCGTCCACTC
          ATGGAACCGCTAGCGTCGGTGCAGGAGTACCCGGTTGTAGAGGCGCAGTCAGCGTGCTGG
          ATCGAAGGACGTAGGCAGGTTTGGGAGTTTCCAGAAGAACGGCGGTCGCATGGAGATAGT
          ATTGTCGTTTTCGCGACAGCATGTCCGCATGGAGTGGCATGGTAACTATAAGTCCGCTAT
          AGAGTAGCGTATACGAAAATACGGGATCCCGCATCTGTAGGCTAGCGACAAGCTCCTCGT

          ATATACCTCTCCAAGTTCTGAAAGAGCAGGCACCGAGGGATTGGCGTCAGACAGAAACCA
          ATATCCCTCTCCTAGTTCTGGATGAGCAAGCACCGAGGCATACGCGTCAAATAAAAACCA
          AAGTCACCTCGCCAGTTCTAGATGCGCGAGCAACGCGGTTTTAGCTCTAGTAGGGAACCC
          CCATTCTGTACCTGTATGTGGATCAGTGATAATTCGCGTCTTTATGCAAGAAAAAGCATA
          CTTCTTTGCTCCTAATTCCTAGCTCATAGCACCCAATTACCGAGCGCAAGATAGAAAACA
          ATCACGAGATGTCGACTTAGAATCCGTGTCTGCACAGTGCTCAAGAGCGGGAGAGAATGA
          AAGATTTGCAGATGGCATGAAGCCGTCTATGCTCTACTATACACAGCGAAGCGGGCGTTC
          CAATAACGCCGTTAGCAAAACGAGAGGCGTCAGTCCGACAAACCGGCATACAGGTCGTGC

          AGAAAGAATGGCGTTTAGTTCACGGACGGTTCAACTCGCA
          TAAAACAATGGCGTCTGGCTTATGAACCATTCATCTTGTG
          TGGAAAAGACGTGGTAAGCTTACGTCCTGTTGCACACGCG
          TTGCCGGCGGCTAGGCTGCCCTCCCCCGGGTACAGAGACC
          GTCCAAAGTATACGGCTGGATCTCTTTAGTTAAAGGCGAT
          ACCCGGTGGTCCTCACTAATGCTGCACGGTTGCGGCTACG
          TGATGCGGCGTACGTCATAAGATGGTTACGTATAGTTAAG
          TAAGAGGACCATTAGCGTATGGCGTACGTATGAGGTCGAG

