 8 1000
t1        TTACTTATCGCTGAAGTGCCCTATTCTAGCCCTGAGCTAGCCTCCTTTAGCAGCCCAGAA
t2        TCAATTATCCCTAAAGTGCCCTATTCTAGCCCTGAACTAGCCTCCTTTAGCAGCCTAGGA
t3        TGAACTCTTCCCGGAGTGCTTTATCACAGCCCTGAGCAGCCCCATATAAGCGGCGTAGGA
t4        TTAACTATCCTTGAACTGCCCCTTTCTAGCTCTGAGCAAGCCCATTCCAGCGGCCTAGAT
t5        TAGATTACCTCTAAACTGCAGTATCCTAGACCTGAGCAAGCCTATTGCAGCAGCCTAGAA
t6        TTCTTTGGCGCTGAAACGTTGAGGCTTAGTATTTGACAGGTCTATTCTAGCCGCTTTATG
t7        TCGACCTTCCTCAGGATTGAGATGCTGACGACTGGGTACTTAGGATTCGGCTGTGCCAAT
t8        GCTAGGCACGTCAGGATACGGGAAGTAGATTTCGATTGCGCGTTAGAGACCGGCATTGTA

          ACGGCATCCTTGGGTCGATCGCGCTCGCCAGCTTAAAAGAGTGCGATAGGTCACCACTAT
          AAGGCATCCTTGGGTTGATCGAGCTCGCCCGCCTAAAAGAGTGCGATAGGTCACCGCTTT
          AAGGCATTCTTGGGTTGCTCATGGACGTCAGTCTGAAAAAGTCTGACAAGTCACCAGTAT
          AAGGCAGCCACGGGCCAATCGTGCTCGCTAGTTTGAAAAGGTGTGACAAGTCACCAGTAT
          GAGGCGTAGGCGAGCCGATAATGTCCGCTAACTTAGTCAGGTGTGACAAATCTTCAATAC
          GCAGCGAACTAGAGTCGCTCCGGCATGTGAACCCGAAGTAAAGCGATCATCGGTAAGCAA
          GCCGGCAGTTCCAACCTGGTGTCCCATGGAATACGATCGCACGGGGATTTTGGTTACTGC
          AGGGACCGCTTCGGATATACGCCCCACCTGATATGAACGCTTGGACCCGGCCATTGGAAA

          ACGGCCTGGATTGCTAGCGATAAGCGTATTTACTGAGGCAAAGCCGGGACCACCAGCTCC
          ACAGCCTGGATTGCTCGCGATAAGCGTAGTTACTGAGGTTAAGCTGGGACCACTAGCTCC
          ACGGACTGGATTGTTAGCGATAGAAGCAAATATTCGGGCAAAGCCACACCCATTGGCTCC
          GCAGCGTGGATTGTTAGTCTCAGGAGTAGGTAATGAGGCAGAGCCACAGCCGCGAGTTCT
          ACGGCCCGGATTGCCAGTGTAGAGAGCATTGAATGAGGCAGAGCGAAGGACGTTAGTTCT
          CCGGCCTACATCGTCAAGAATGGGGGAATCGATAGCTATATGGCCAGGACCTATGTTCTT
          TAGAAGTGCTGTCCTAAGGACAGATCGCCCTACATTTTCCCTACCTCGACTAACTGTCCT
          CGAGTCTATGTTGTTAAGAGCGGAACGACATGCCGGGCCCATCCCGTTTTCTTAGTATGC

          GGAATGGGAATCCACGACGAAGCAGCGTAACCCCAGATCGTGGTGTTATTATTGGCTAAA
          GGAATGGGAATCCACGACGAAGCCGTGCAACCCCAGAACGTGGTGTTATTATTGGCCAAG
          AGAATGGGAAGCTACGACGAGGCAGTATAATCCTAAATCGGGGTGTTATCATTGGCTAAG
          GGAATGGGAAGCAACCACGGCGCAATGTATCCCTAAATTGGGGTGTTATCCTTGACTAAC
          TGAACCCAAAGTTACGACAATTGAGTGTAACGATAAACTGGGGCTCTATTATTGGCTAAG
          GGCATGGTAAGTTACGACAACCTGGTGAGGTTTATAGATAGAAAGCTGTTATTGACTAAG
          GTAGCGATCAGATACCAATATGTAATATAGAGCTTAGTAGGAAGGAAATGTTGAAGGGGG
          GGAGCTTCGATTTATGCATAGTGCGGACTGCACTTAATTCGCCTCCACTAATTAGCCTGG

          TTGCGTCCCCAGAACTGGTGGACTGACCGGCTAGATGTAGCGTTAGGCTCCCAGGCAATA
          CTGCGTCCCAAGAATTGGTGGGCTGACCGGCTAGATGTAGCGTTAGCCCTCCAGGTAATA
          TTCCGCTTCTAGAACTGATGGGCTCACCGTATAAAAGTAGCGTTGAGCTTCCGGGCCACA
          CATCGTTGCTAGAACTGGTGGGCTGACCGGATGAATGTAGCGCCGAGTTTCCGGACAATA
          CTTCGTTCCTAGAACCGATAAGTTGACGGTATAAGCGTAACGTTTGGCTCCCGCGGGATG
          TTTCGACTCTAGACCTAGCGGGTCGACCGGATAGCTGTAGTATGAAGCCACTCGATTAGG
          ACCCGGGGCGTTAGTCTGGCATCAAACAGGGTGTGTAGGGTAGTGTTAAAACAATCGATC
          GCAACGGCCTTCATCCCCCAAAAAGATTTACTCAGCAGATTGGCTCCCTGTCGGAGCAAC

          TAAGAACCGTGGGGTTGGTGGAGTGGGATTTCCGCCATCGTGAGGTCTTTTTAGCTTTTT
          TAAGAACCGCGAAGGTGGTGGAGTGAGATTCCCACCATCCTGAGGTCTTTTTAGCTCTTT
          GAAAAGCCGTCCTAGTGACGGAGTGAGATTCTTGCCAAACTCAGTTCCCCTTAGCTTCTG
          TAAAAACCGTGGGCGTGGCCGAGTCAGATTCTGGTCATCTTCGGTTCCCGTCTGCCATCG
          TAGAAACTGTGCGCATGGCGGAGCGAGATTCTTGGCCTGCTGAGTTCTCCTTAACGACTG
          CATAAGTTTCGCGAATAGTAGACGATGGTGTCCACTATATCTCATTCCTTTTAGCAACGA
          AGTGTTTGCCTTAGGGGAAACCAAGAGGTTTATATTTACCCGAGGGTACCTATATCACAG
          CAAAAGCCATTTACAGACTGTAACAGGGGATTCGGTACTGGGAATTAATTCGTGTTAGCG

          AGCCCATCAAGCGCGCAATGGCCGAGCCTGGCATTGCCTGTGATCGTATTGTACACCGTC
          AGCCTATCAAGCGCGCAATGGACGAGCTTGGAATTGCCTGTGATCATATTGTACAGCGTC
          AGTTTATTAAGGGCATAGTGGTCGAGCTTAGTTCTCTCCGTGATCGTATTGTACAGCGAC
          ACTTTCTCAAGCGCACAATGGCCGCGGATGGCATCGTCCCTGATGGTACTCTATATCGAC
          AATTTATTGAGCGCATTACGGTCGAGCTTGGCACCGTCCGTGATGGTTCAGTGCAGCGAC
          CGTTCTCTAAGTATGGGGTAGCTAGGTCCAACTCTATCGGATATAGAATATAATGCGGGT
          AACCAATATATCATAGCGTGGTCGACCTCCGTCTCGCTCGTTACTAAACATTACGACAGA
          AACCCCACGAGCGCACCGTGCTCAGAACTCAGTTTGCTTAAGATAGTACCCGGGTATGAG

          CTGCTTAAGCCCTCCTCGTAACATCGCGTTCTATCTTGGCTCGATTCCTCCGACTACAGA
          CTACCTAAGCCCTCCTCGTAACATCGTGTTCCATCTTGGCTGGCTTCCTCCCACTACACA
          CTGCCTACGCTTTCCTCGAACGATTCCGTACTATCTTGGCTCGCTTCCTCCAACTACACA
          CTGCCTAAGCCCTCCTAGTACCACCTCCAATCGTAATGACTCGCTTTCTCCAACCACACT
          CTACCTCAGCTATCCTCGAGCCACCACGTATCATTTTGACTTGCATCCACCAACTACCCA
          CAGCCCTAGTTACCCTCCTACCACTACTTACATCTTGATTAAGTTTCCTCCGTCTACGCA
          AAGGGCAAACAACCTTGGTTCTGCAGTACCCGATTCGATGTGGATGTCTTCATGCATGCA
          GACTCTACGTGGGTTAATCGACGGCATCTTGTGTCCGATCTAAATATCCACAACCATCCA

          ACGACAGCAATAGACTCTGTAAAGCGCCTCACTGTACTATACTGTGGTTGATTCTGCTAC
          ACGGCAGCAATAGACTTTGTAAAGCGCCTCACTGAAGTATACTGTGGTAGACTCTGCTAC
          TCGTTAGCAATAGACTTTGCGCAGAGCTTCACCGAAGTGCACCGTGGCAGACCTTACTAC
          ACGTTAGCAACAGACCTTGTCCAGAGCTTTACTGGAGTACAATGCGGTAGAACCTGCTAT
          AGATTAACTATAGACTTTGCGCAGAGCCTCACCGAAGCACATTGAGACAAGCCCTGCTAG
          ATCATGGTCGCGGTGTTCTGGGAGGACCTTTCTGCAGCAGATTACAGTTACAATTGGCCG
          CCAGCAGTATTACGGTCCTTCTAGTGTTCACTTGGGGCTGCCCTGTATAAACAATGATAG
          ATTACAGGGATGACGTTCGTGACAAACCTCGCGAAGGTCCATTCCGGCTGCCTCGCCTCA

          ACATCACACATCTACCACCAAACTTATGACCCGTGCCTTAATTGTTATATTTGCGCACGA
          ACATCACACATCTAACACCAAATTTGTGACCCGTGCCTTACTTGTTGTATTCGCGCACGG
          ATTTCACACATCAGACGCTATAATTAGGCTCCATTTCTTAATCGCTTTGCACGTTCATTC
          CCCCCGCACGTCTGACACCATACTTAGCACCCGTTCTCTAATTGCCATACTCGCTCACGC
          ATCTCGCGCTCGTGATGGCAACCTTAGGTCTTATTTTTTAGTCGGCAGATTCGCACGCGC
          AGATTGTGCATTTGGTGCACAATACGGATCTCGTCACGTGGTGGTATCCCTTATCAACAA
          TCTATTCACAGTCCACTGCAAATGCTTTCCGCAGGGCTCGAACTCACGACTGCTGAACAT
          TTGCGGTCCCAGCTAGCAATAAGGGTGCTTAAAATGATCAATAGTCGAATCGGTGAATAC

          GCATCGATCGGTGGCGCACGTCACACTGTGACTAACATGCATATCGGAATCGGTAGGAGT
          GCATCGATTGGTGGCGCACGTCACACTGTGACCAACGTGCATATCGGAATCGGTAGGAGT
          GTATTGACCGGCGGCGTAAGTCACACAGAGGATAACCCGCATATTGGAGTCGGTAGGAGA
          GTATCGATTGGCGGCGCAAGACACATTGAGGGTAACGTGCACATCGGAAACGGCAACAGT
          GTATAGATAGGCGGCGGAAGTTACACTGAGGGCAAAGTGCCTGTGGGATTCGGTAACAGT
          ACGTGGAAAGGTCGGGTATCTCATTCATTAGGACACGTGAATCCGAAGACCAACACTAGT
          GCTTTGATTTCTGACACAGGTGACTTCAAAGAGGGGATGCGTACGCCGGGGGACAACGGC
          GATTCACTAAGTGGCTTAGTCGTCAGAGAACAGGATTCGTGCCCGACGCTGTCCTACGTT

          TTCACCGATCTGAGCGGTCCAGGGCTGCCCGGAGCTTAACAATTCTCTCAAGAGCCCTTT
          TTCAACGACCTGAGCGGTGCTGGGCTGCCCGGAGCTTAACAATTCTCTCAAGAGTCCTTT
          CTTACCCAACTGAGCGGTTCAGGGCTGCTGGGAGCTTAGTAACTTTCTCACTAGCCCTTT
          ATCACCAATCCGAGAGGTCCAGGGCTGCTTGGAGCCCGATAACTCTCTCAACAGCCCTTC
          TCCACCGGTATAAATTGTCAAGAACCGTTTGGAGCTTAGCACTGCCATTAAAAGCCCTAT
          TACGTAACATACCGTGGCCCACGGCCACGTAGAGTTATACCCCTTTGTCGAAGACTACTT
          ATCGCGATGGTTAGCAACATCAGTTTTACTGGCCTCGGGTAAGTTTTCCAGCAGATATCC
          AACGCCCTTGCATCAGGGGTCTGATCGTTGTGGCATCTGCAAGGGCGGGAAGCAGCGTCT

          TTTACTTATAAGGGTTTAGAAGTCCCAATGCGCATGTATTCAGACCTTTACTAGTGGGCG
          TTTACTTATAAGCGTTCAGAGGTCCCGTTTCGCACGTATTCAGACCTTTACTAGTGGGCG
          TTCACTTACAAGCGTGAAGGAGGCCCGCCTCGCATGTATTCAAACTTTTACTGGTAGACG
          TTTTCTTATAGGAGTGTAGAAGTCCCGTTTCATATGTTTCCAGACTTCCACTAGTGGGAG
          TTTACTCATAGGCGCGCAGAAGCTCCGTTTCATACGAATTCAGAGCTTCGCTGGTAGGAG
          TAGGCCTAGTAAAGAGCATACGTTGCGCTTCACGCCTATCCGGCGTACGGCTAGTGTGCT
          TGGTTCTTCAATAGATTTGCAGAGATGAGATACTCTAACTTTAGTTCTCAAGGAAGTGTT
          AGGTTAGTAGGCTATCGGGCTTTGTCGCTGGTTACATTCCTGAATTGTGGAGTACAGGTC

          CGTCTTCGAGGGCACATCAAATACTCCCACATAGCCGAAAAGTGGTATACGCGAACCCTG
          CGTCTACGAGGGCATATCGAATACTCCCACATAGCCGAAAAGTGGTGTGCGCAAGCCCTG
          GTTCCACACTGGTATAACTAATGCTCCCACATAACCGGAAGAAGGTGTACACAAACTTTG
          CGTGTACTATGGTTTAACAAATACCCTCATATTGCGGAAAAGCGCTATCCGAGAGTCCAG
          CGTACACCACGATATAACCAATACCCCCACACAACCGACAAGTGGTATAGACAAGATCTG
          TATTCATCACAGTATTCTCAGAACTCTTGCGGAGTATCCGATTAGGATACGCCAACCCCG
          TAGTTACTAAACCTTATGGGACACGTTGTGAGAGAGCCTCTGTGGAGCATGCGGACTCGG
          TACATCCTGTAACTCAAACCAATCTTTACTTGGACCCCTCGGAAAGTCCACTTGGTATGG

          TAGAAACATAGACAGTCAATGAAAACGCACCCGTCCTAATCATGATGCTAATCGGACTGG
          TAGAAACATAGATAGTGAATGAAAACGCACCCGTCCTAATCATGGTGCTAACCGGACTGG
          TAGGCGCAGTGTCAACGAATGAAACCGCAAGCGGCCTAATCGTGGTTATAAACCAACTGG
          TAGAAGCGTAGCCAACAAATGATGCAGCCTGGGACCTAGTCGTGATTCTAACCCGACCGG
          TAGAAGCGTGGACAATGAATGAGTACACATGCGGACTAATCGAGGTCCTAACCCGCCTGA
          TTAAAGTGCGCCCAAAGAAAGAATATGTATCTAGCGTAATGGCAACTCTGACAATATCGG
          TTTGTAGCCAGTCACGGGTCAGAGCTGAGCATGTCCACTGTAGGAGACGAAAGAACCCCC
          ATAAACGGTAGCCGTGGATTGAAACAGCCCTTTCTCGATTCCTTCAAATAGGTGGCTTGT

          ACGTACTTACGCGGTCTATGATCCCGCCGCTCAGCGCACAGTGATCGGCATTCCTGACCC
          ATGTACTTACGCGGTCTATGATCCCGCCGTTCAGTGCACAGTGATCGGCATTCCTGACCC
          AGGTACTTGCGAGGTGCACTATCTTGGCACTTAGCGCGGTGCGATCGTCAGAACTGATCT
          GGATAGTAATGAGGTCTACGACTTCGTCGCTAAGTGCGCAGTGGTCGACAGAACTGACCT
          TGGAACTTACGACGTCTTCGATCCAATCGTTCAGTGAGCCGTGATCGACAGAACGGAATT
          AAACGGACCCGAGGCCTAACCCACCGATGCTTGGCAAATAGATACCAATGATATGGCTCT
          AATTCAGTAAACCTCTGAAGTAGTTGTTGCCAGACAAATGCTCTCCAGTGAGGTTGAGCT
          AGAGATGCTCCTCGCAAGCGTCCATTTTTCGTACTCTGCGATCTTCGGCCCCTAAGCCTT

          AGTGGCCGCGCAGTTAGGTGCGCTCTCGGGCTTAACCTGT
          AGGGGCCGCGCAGTTAGGTGCGCTTTCGGCCTTAACCTGT
          CCTAGCTGCGCCATTACGCGCCCTCTCGGCTTTGGCCTGT
          TTCAGACGCGCGGTGAAGTGTCTCCTCGGTTCAGTCCTAT
          CCTGGCCGCGCGGCTAAGCACTCCCTCAGCTTAGACCAGG
          AAGAGCCACGAATTTAGATTCGCTCTCGGCATTGGCCTAG
          GGGGATAGGGTGTTTTCTCCTTCATCAGCTTATAGTTAGC
          CAAATTTGGCAATCTTACTGACCACTCTGCGTGAGCCTGG

