 8 1000
t1        CCACAAGAGATGGAACCGAGTAGCAGATGACTTGCACAGGCTCATGGGAGTAAGGATTAG
t2        CAACAGGTAACGGAGCCGTGAAGCAAATGACCTGCACATGCCTTTGGTTGTATCGAGTAG
t3        CTACATACAACGAAATCGTAACGCAGACAGCCTGGACAAGCTCTGCATAGAATACAGCAA
t4        ACATGAGAAGAAATTCCGCGTAGATTTTGTCGTTTCTTAGCTTGATCCGAAGAAGCTTGA
t5        TCGTTAGTCGCGGTGTTGTGTGTTGAGGACCGCAGATTTGCTGCAACATCTACGGTTCCA
t6        CGATAGGCTGTCCGGTCGCGCGAGTCCCATTTTAGCTGGCTCTCGTACCCTCAAATCGAT
t7        ACAAGTCCTGGGTTCCTGGGCAGCATGAAATTAAAATTTACAATCCTTAGTACAGTTTGG
t8        CGATCATCGGACAAATCGTGTGGGGGGCGAGTCGGGGTCACTTCTAATGATGCCTCATGG

          TTTCGTCGAACACACCTGTAGGAGGCTTGGCAAATGATGAGGCGTCACTATTATAGCATT
          ATTCGTCAAACACATTTGTAGGCCGATAATCAAGTGATGTGGCGCCTTCAGAAGAGCCCG
          ATCCGTCAAACACAATAATAGGATGCTAGTTAAAGGTATTGGTGTACTCACGAAGCCACC
          CCCATCCCGAAGCGCCCTTGAGAAACGGGACGAAAAATTTTATGTAAAGCTTAGGCCACC
          ATGAACACTATTCAACAACGAAAGCTGTAACCCTTGGAAGGGCGCTTTCATTACTCTCCT
          GCTAGTACAGCATGGCTATCAAGGGTATTTAAAATGACTCACCATTATTATTACCATACT
          GGCTCTGTGGTTTGCATTTGCGAGAGGGTGGGCCTGATTCAACTCCCGCTTAGGATAATC
          AGTGGCACGACCTTCTGCTCATTGAAGTTATATCCGAGACGGCATAAACCTTTGTTGAAT

          TGTGTCATCGACTTTTGACGGCCCATCGGAACACCCCATAGCTACCCAAGGAAGGCGAGG
          TGTGGCATCGAATTTTGACTCACCACCGGGACACCGTATGGTTGTCCAAAAGAGGCGAGG
          TGTTGTATGGACTCTTGCCCGACTATTGGTTTAGCCTATAGCTACATAAGAGAGGTGAGA
          TGTGGCGTTGACCCCAAGCAGACTTAGGCTATATTGTGACGACATTTAGAAATGGCGGGG
          AGCAACCTAGAGTATCATGTGCTTTACACATTGTACCCGCGGTTCCCACAATACGACAGA
          ACTTTCTTTAATCCTTAGCCGACTCGCAGACAACCTTGTAGCACCATGAGAAGGGCGAGA
          CGCGATCCTGACACTTTTGAGGTCCGGCCAGCACGTCGTCGTTATACAAGAGCAACGAGG
          GGAGGGCCGGAGCTCCATGTGGACCCCGTTCTCTTTCTCAGTCTCCAAAGAGGGATGCCG

          TGTCGAGGTGTAGCGACCAGGCACAATTATGAAAGTCCGGTACGGATTAGACTAAAGGGA
          CGTCGCGGCCTAGCTACTAAAAGTATTTATCAGAGCACAAAACGGATTAGACGAAAGGGA
          GGTGGAGGCCCGGCCCTCTGACTCTATTACGTGAGAACGGTAGGGTATAGATAAGAGAGA
          GATCACGGAGCAGTGGACCTTGGTGGTGACCCTTGTTCGCCCTAGCGTTGAAGAAATAGG
          GACGCTCGTGGGGGCAGCCAACTTCACCGTGTAAGGCTGCCTCGAAACGCTCCGTATGAA
          GGCTTAAGGATAACAGGCTTATCTAGGCATTGCACTACATCCCGGAACCAAAAGAACAAG
          CACCCGGGCCATGAAGGACAGATCGCTAATACGAGACCCCCTCCTGACCCGTGAGTACAG
          GCTCAACCCACTGCGAGCGCAGGTACCTCTCAAGGCCAGTAATGGCTGTAGGGGAAAGAA

          TTGTCCTCATAGTCTCGTTCGCGAAACCATACGACACACTGTGTCGCTGGGGGACCATCC
          TTGGCCTCATAATGTCATTCCCGAAGCTAAATGACATGCTGAGTAGCCGGGGGCTTAACC
          CCGGTCTCACACTCTGGCCCCCGATGCTATACCACACGTCATGTTGCTGGGGACTCAACC
          TGGTGCCAACGAAGGGGACACAGTCGCAGTACTAGGCGTCAGCACTCTGGGGGGACAGGA
          CCAGACCTACCAGCACCCGACTAGTCAGATACTCGACTACAGTGGGCCACGGAGCAGAGG
          GAGACAGCTCGAATTCCTTGCTTTGGATAGCTCCGAAGTCAATCAACCACGAGGACTACC
          ATACTCCTAAGGACGTTGTAGTGCTAGGAAAGATTGCGGTAAAGGGCCCAGGTAATAATA
          TTAACTGAGTCAGCGATCCTCGGGGCGTGCATTTGGTACCCAATGATCACAGGACTGGAG

          ATCGGACCAGTTCGGTTGGCCCGACCTTCGCGGAGGCACGACCTTGTCACAATCCGCAAA
          ATCAGGCCCGTTTGCTTGACCTCCGCTCTGCGGAAGCACGGCCCACCTGCACTTCATGGA
          ATCGGACCGGTTTGGTTGGACAGAACTTTGAGGAAGCACGCCCCTAGAGCACTCCACGAA
          GCAGGCGGCGTGTTGCGAATCCGAAATAATTGGACACGTTAACGCCCCACGTCTAGCGTA
          GCACGGTAGCATGTATAGGTGTGGGTTCCACGGGGAGATTAGGTCCTACTATACCTTGAG
          TGAAAAAAGTGGGCAAGCGGATGCCGTTCCCGCGAACAGCCGCGCCTGCGGTCCCTAGCT
          GGTAATTATATAGTACGCGTCAGGGACCTTAAATGTGGGCGAGCAATGGTGGATTGCGGC
          ACGAAGTCGCTAGGGTGAACAGCGGATCGATGGTGAGAACGGCCCGTTACAACCAAGGGT

          TCGACGTCTAGGCATGCACGTCCATATCTACTTTTTAATCTGGTAGGGGAGGCTCAGATG
          TCAAACACTAGACACCCACTTCCGCAAATATTTTTTACTCTGGCGCACGAGGCTCGACGT
          TTAATCACTGGGAGCCCTCCCCCGCACCTCCTTTTTACTCCGGTAGATTAGTCTCAATGG
          TCAATGAGCCTAAGCAGGCAGGCGCGTTTAAGTCTCACCCTGCCGACGCGTGATCAGTAG
          TCTATTAGGCTCTCTTCACGCAGGACAATAAGGTTGTTGGAGGGAGGCGAGACGTCGTAG
          TCAAATGTACCTGCGTACTAGGCACACCTAATTCCAGACAATGCCTGGCATGCTCCGCCC
          CGTGGAAGTAGCAGTACACCCAGTTATCTTTCTTCGGTCGAGGGGGCTCGGGAACAGTAA
          TACGCTTGCGATCATAGGGGAATGTCAACAAGGTCAGCATCCCGGGAACAGTCTGCAGAG

          AAAGCGTTGGGAGAGGGTTTAAGCTCCAGCACTAAAGCTTTCAGTCACCGCACAGTCCCA
          AATGCGTTGGGAGAGGGTTTAGGATCCAACAAAAAGGATAAGAGTCACTGCGTTTTGGCG
          ACAACGTCGGGCGAGCATCTAAGATCAGGCGAATAAGATCACGGACACTGCTCTGCTCCA
          GGGACATACGGACCACAGATATACCACACCGTAGCAGTATGTAATTCGAGTATAAAGAGT
          AGAACTTAGATTCACCCCATACGTCGAACCAGAGCTGAGGCTGCCCCCTGTTTTGGAGCC
          GATACGATTAGACATCGTCCCCCCTCTGGGACTGGAGAAACCTCCACTCGTTCTTAACCA
          GATGTGCGTAAGCATAGCCGGAGGAACAATAGGGAGGGGGCCACAATCATTACTGAAGTC
          TAAATCCGAAGACAACCACCCTATTGCCCCGAAAAGGTAAAAAACATGCGCATTGAAGTT

          GAAATTGGTGAATCTGAGAGGAGTTTGTAGCCGGGCCCCACATGCCGATTATTTGACGAA
          AAACCCGGTCTACCTGAGTGGAGGTAGTAGGTGGGCCCTATCGACCGATCATTTATTGAG
          AAAGCGGGAGAGCCCGAAAGTAGGCAGTATACGGGCGCGTCAGGCCAACCCTCTGACGAA
          AAGTCCCATGGGCTTAGGCGGAACAGGGTACCGGTTACAAGGAAGCGGTCGCTGGAGTCT
          GTTTTTTAAAAAAGACTGCGGTGTTGGGAATAAGCCCTGGCAGGATGGCTCCCAGCTGAC
          ACACCAGATGAATCAGAGCGAACCTACAGGTTACTCTGCACAAGACGAGATCCTATTTAC
          AAATTTCAGGTGTTAATACATCCTTCGGCACCGGGCCGTATAATACACGTGACTGAAGTC
          GTATCTGAAACATCCATCTTGATATTAGTGGCAGTCGGCAGACGACGCTACCTCAACACT

          TCTACAAGAATTCCCCGTTAGAAAACCTCATTCTCTATTGGAGGGTTATAACTCTAGCTT
          TCTACAATAAGTCCGCGCTCCAAAACCTTTTCCTGCACCGGAGGGTTCTTATTTTGTATT
          TCTACGAGCGGCCTGTGCTAAAGACCCTCATTCCCCACTGGAGGGTTCTTACCTTGCATT
          TTCTTCAATAGTCCTGCTGATAACAGCACAGATTCTGTTTGCCGGTCCTCGCGCACTTGT
          TAAGGGATAAGGATTGGTGATACCAACGAACAGCTCCATGCTAAGTCCGTTTCGTATGGG
          AGCGATTACAAACCCGGCAGATTACTCCTTCTATTTACAGTCAAAAATGGACTAGCATGA
          TTCGCCTAAAGTTCCAATGAAACCATCGTTATTCTCGCAGGTCAGCTGGTACTGCATTGC
          TGTGGATTTGTATCAGTTAATGGTAATACCTAATTCAATTATAGTTTTACTCCGACACAA

          CAAGGGAAATCGTGCAATAAGGCCTCGGCGCACTCGCCATTTTATTGGTGTCGTATGCAA
          TAAGAGGAATCCTGTAATAAGAGATCGGCACACTTGTTACCTCACTGTTATCGTTTTTGA
          AGAGGGAAGTCCTGCAGGAAGTAATCGGCAAACCCGGAACATTATTATTAGCGTCCACAC
          GGTCGGGATGCGACGTAGTAGCGACGAACAAGCTGCTCACTTCTGACGTGACCTCCTCGC
          CCTTGAATTGCCATGACAAAGGCGCCAGTGCTTCACCTGATCTCTTCTCGTCTCGCATAG
          TAGCGGACTGTTCCTGGGAGGGAACCCCCCCGCCACCTGGTTCAAATGCGGGTCCGATGG
          CGTGAGTACGCGCTCAAGTCAAACCCGCGCTACACTAAGGTCCAACGGCCCGTCCATCGG
          TACATCGAAAAGACTCAAAATGATATATCGACTCACGATCATGGGAAGGTGATCTTTCAG

          CATACCGTAGTCCTGGCACGCAATGGTACGCACTCCGCGTGTAATCGATGTGTTCGCATC
          CATATTGTAATTCTAGTGCTCATTGGTGCGGATTTTATATGTTGTCGATATATTTGCGCC
          CGTTCCGAGGTCCAGGTGCTTATTGGCGCGGACTTCATCTGTAGTTGATACGTGTTGTAC
          TAAGTGACACTTATAGTATAAACTACAGTGTCAGCGGTCAACGGCTGAGGCGAGCCCGGT
          TTCAGGATGGCCCTAGCCCCAATGGCGGTTGCCTAAAAGCATTTCTGCACGTTTAACAGC
          GACAATCCGCTTCTTTCACGCTTCTGAATAAATAGTACAGATTTTTATCGGCCGAGCTGC
          CGCTCAATCGATCCGCCGTATGTAGGGACTACGCTTAAACAGCGTCGGCAGCTCCATCAC
          CGCATGGAGGTCCCAAAACAGGTGGAAACAAGTTAGAGACGATTAGATCAGATAGGGGGC

          AATCCGTGCCCCGCAAATATCCAATTTAGACTGCACCTATACTAGACTTGCGCTTTCGTG
          TGATCGTGGCCTGCAGGTATCAAACTTAGATCGCAAACATATTAGACTTACTCCATTGTG
          TATCCATGGCCCGCAGATATTGAGGACAGGGTGGACATACGTCAGGCTCGACCCCTCGTG
          CATCCGTAGGTAAAAAGTCTCAATGTTAGTATTTAATTATATTTAACCCACGCTCTCACA
          CAGCCGTGGACCGATCGTGCATCTCCTAGCTTTTGGACTTATACAACTCCAGTGACTGGG
          CTCTGGCAGAATGAATATAAAGGTTTCACCCTGTAGACGAACGCACCAAATGCCCTTGCC
          CGTCCGCTGCCCGGGAGTGCGAGCCCTTGTTCACAATTGCGGTCGGGAGATATTGCTGTC
          AGGGTAACCTTTGTTGTCGAAAGTTCTTAGAGACGTTTGTATCTGGTAGAAATTCCTATT

          AGTTACCAGGGATCCCGACGGGTCAACAACGCCCGGGAGATCCATCGGACCAACGCAGGT
          AGCCATTGGGGATCCTGGTTAGTCAGTAACGTTCGGAAAATCAATTGGACAAGCACAAGC
          AGCCAACAAGGGCCCCAGCGGATCAATGGCGCCCGGAGCACCCATTGGAACAGTGCAGGC
          GTCAATATAGCCTGTTGAGAACCGGCTGCTGGTAAATGGATTACGTGCAAATGTATCATT
          CGACACGTGAACGGAAGGGAAGCGCCCGTCCCATAGAAATACTAACGGGCTGCCTGTTGT
          ACCCTGGTAGCTTTATAAAAAACAGTTTGTGCGGGATGGTTCCGATCGTTTAGTTTTGGC
          AAACTTTTAGGGTGTGGGGGGGCGAATAGTGCTACGGAGTGATCCGAGATCCGACGCAAT
          TCCCGCTTCGAGTATTTAAGTCAGGTAGCCCTGGGGGGCAGATCTCTAGCTCGCTGTAAT

          TACCGGGTTGCGGCCTAACTTGTTGCTACACGCTCGCATTCAACCGAACCGAAGGGCCCG
          TACGGGGTTCCGACCTAACTGGTCGCCAAACTCCTGCCAGTAGCAGGAGTGGATTGCCTG
          CGCGAGATTTCAACCTTACTCGTCCCCAAGTGCCCGCAGGCAGCACGACTGGAGTGGCTG
          CATTAATCCTCAACCAGTGTCGGCGATAGGGACATAATAGCAAAGTTCTGGGCACTGGAG
          CATAGAATCCTTATTGCTTCCGCTGCCCGACGTCTGGCATTACACCATCGGGACGAGGCT
          CATTGGATGTTTGCTGAATACCCAGTATGAGACAGGAGAGAACAATCATAGGGGGTACCA
          GGCAAAGGTTCGTCTTACTTTAGCACTCGACATCGGCTATTGCACACTCAATCACAGATG
          CTTAGGGTAAGCCACGATCTCTGTGTTTGAGATCGCCTAATATCGTGCGCGAGCTCGGAG

          TGACGTCGGTGAGTCCGCGAAAGTCTAGTTCACGCCAAGCGTCGTCAGGCCTGAACGCTT
          CGATGCCATGAAGCTTGCGAAGGGTTAGCTGAGGTACGGTGTCGCTAGGTCCGAACGACG
          TGAAGCCGGGAAGCTTGCGAAGCCCTACGCGAGGCAAGATGTAGTCAGGTCCGAACGTCA
          TGAAATCGGATTGCTTATACTGAACGTCCTGAATCGGAACGATATTACGCCTGAGGGCCA
          CGCAGGGAACACCCCCATATAGGTTGATATAACGGTACTTATATAGGTGCTAGGGCACAG
          TAACGCCCCGCTGCGTGTAAATTTGGACGCGCTTAGTACGGCTCAAATGCCGATCCGTTG
          TCAGGTTCAGATGCTCGCAAAGGTTGTCATGGGATTCTACCAAGCATGAGGTAGCTGTCG
          GCACACTCGTCTACTCTCTCGTGCGACTGAGTACCGCCACTCTCGAGGGCTCGACGTTTG

          TACTTGATTACGGAAAGACTATACCATGTTAAGAGTGCCA
          CACCTGAATACGAATAGACTGTACCATGTTAAGGCTGCCA
          TATTCAAGAACGGATAAACCGTACGACGTTAGGATTGCCA
          CTCTTCGGCGCTGCCGGTTCGCTCAGCGACTTAACATCCA
          TCACTGAGCACTGAGGGGGTATTATACGTTAGTCAAGTTA
          CTCTAGAACCTACGTCGGTAGTGAGCAGTCGGTTCTGCCA
          GGTTCGATTTCTACCGATGACTGATTTGTCGGGAATGCAC
          GAGTTTAACGTTGGACGGTCATTGATTGCGACGGTAAACG

