 8 1000
t1        TGGAGGCGCGGTTTGGCATGCTACTGGAGGTTTTACTAGTAATGTGAGTCTCTGGTCCGG
t2        TGGAGGCGCGGTTTGGCATGCTACTGGAGGTTTTACTAGTAATGTGAGTCTCTGGTCCGG
t3        TGAAAGGGCGATTTGAGGTGCCACCAGAAGTTCAGGCAATCGTTTGACCTTATGGCTCGG
t4        TGAAAGGGCGATTTGAGGTGCCACCAGAAGTTCAAGCAATCGTTTGACCTTATGGCTCGG
t5        TCAGGGGTTGAATAAGCTGATCATCGGTGGGCTAAGCAAAAATCGGTGTACGGTAGGGCA
t6        TCAGGGGATGAATAAATTTATCTTCGGCGGCCTGAGCAATAATCAGTGTACGGTGACGCA
t7        TCAGAGGATCGACCGGACAATTATTCGGGGTTTAGGGAACGACTGATAGAAGCGACTACA
t8        TCAGGGCTTAGACCCATTAAGTATCGGTGGTCTATAAGATCATAGGAATAAGTCCATGAA

          CTGATGTGAGCCCGCCGAGGTAGTGGAAGTACGGTTATCCACACGGCACAAGAGGCTAAT
          CTGATGTGAGCCCGCCGAGGTAGTGGAAGTACGGTTATCCACACGGCACAAGAGGCTAAT
          GTGATGTGCGTCCATCGATTTAATGACAGACCAGTCGTCCGCCCGGCTCAAGAGGCCACT
          GTGATGTGCGTCCATCGATTTAGTGACAGACCAGTTGTCCGCCCGGCGCAAGAGGCCATT
          GATCTGTGCGAAGAACAGAACTGTGCGAACCCAGCGTCCCGGCATGATCTTGGGATTAAC
          GTTCTTTGAGCCGAATAAGACTGTGTGAACCCAGCGTGACGGCATGAACCTAGGGTTAAG
          GGTTCGCTCGGATGACTACTCCACGTTGCCTCAGCACCCTCTCCTCGTGCTGGCGCCCAT
          GACACGCACGGGGGATTGCTCGCGGTGTAGCTAGCACCCTGCGCTTTTTATGAAGTCGAT

          GTAGTGTAAACGATGGCCGACCGGATACGGCGGGGGCTCCCTGGCTCGACGTATCGTGAA
          GTAGTGTAAACGATGGCCGACCGGATACGGCGGGGGCTCCCTGGCTCGACGTATCGTGAA
          GGATTGGAGAGGGCTATTGCCCGGACCTGTTGGGGGTCTCTTGCCTCTAGTTATCGTGTG
          GGACTGGAGAGGACTATTGCCCGGACCCGTTGGGGGCCTCTTGGCTCTAGTTATCGTGTG
          GTAGCATAAAGATCCCCTCAAAAGCCCTCGTCGCGATTTGTCATTCTCGATAGTTCCTGC
          GTAGTATAAAAATCCTTCCAAAGGCCCTCGTCGCGGTCCATCTTCCTCGATGGTTCTCGA
          GTAAGCTAATCTCCCACCCACAAACCATCGTCATGCCTTGTCATTCTCGATAAGTTTTGT
          GTAATCTAACCACCTAAGGCCTAGCCATTGTAAGAGCTTTCCCATCTTGTTGAGTTTTGA

          GAGCAGCAAGGTTCGTCCCACTTCTTTGGAGTGAGACGCCTTCTTCCAAAGTTTCGTCGT
          GAGCAGCAAGGTTCGTCCCACTTCTTTGGAGTGAGACGCCTTCTTCCAAAGTTTCGTCGT
          GAGCGAAGAAGCTTGTACCGCTCCTCGAGAGTGAGACGCCTTCTTCCATAACCCCGTTAT
          GAGCGAATAAGTCTGTACCGCTCCTCAAGAGTGGGACGCCTTCTTCCATAACCCCGTCAT
          GCCCTGTGTAGACAACTAGGATCTAATAATGGGCGGAGCTTGAAACCGGGAAACCATTGT
          GCCTTGTGCGGACAACTAGGATCCAACGACGGACGGTGCTCGAAACCCGGAATCCATTGT
          GCCTAGCGTGCACAATAACAATATGAAAGTGGGCAGGACTCGACGCTTGCCCGTCACTCT
          GTCTCCAGCGTACTATGAGCATCCAAGAGTGAGGAGGATCTGATCATTACGTATCACTGT

          TTTGAGCACCTAAATTCGTTAATTAATAACGCCCAGGATCACAAGGTTACCGCAATAGGA
          TTTGAGCACCTAAATTCGTTAATTAATAACGCCCAGGATCACAAGGTTACCGCAATAGGA
          TTTGAGCCGCCAACTTCGTAAATTAATATCGCCCACGAGCACGAGGTCACCGCGATTGAA
          TTTGAGCCGACAACTTCGTGAACTAATACTGCCCACGAGCACGAGGATACCGCGATTAAA
          GTCGAGCTTGGCGCTTTGTTAACTTATATCTCCTTCAGAAAGTGGGCCAACTGCATAGGT
          GCTGAGCCTAGAGTTCTGTCGATCTAAATCTATTTACAAAAGCGGGCCAAGTACATAGGT
          GTTAAGGCGAGTGGCTTGCCCCTTAAAACCCGTTAAACTACCTAGGTTGCCTACGGGTCA
          ATTAAGCCAAGCGTCCTCCTGACCGGTGGCCGTATACTAAACTGGGTCAACAGCGTGTCA

          TTCCCCGATCGACATTCAGCGTAACGACGATGGCCGAGCCGCTACGGCGGTATTGCTGGT
          TTCCCCGATCGACATTCAGCGTAACGACGATGGCCGAGCCGCTACGGCGGTATTGCTGGT
          TTTTGCATTAGGTAACGGGCTCAACCGCGATGGTGGCGTCGTTAAGGTGGCCTCACGGGC
          TTTGGCATTAGGTATCGAACTCAACCGCGATGGTGGCGTCGTTAAAGTGGCCTCACGGGC
          TCTCTTGCTATACGAGGACTACAGCTCTGACCACCATACGTAAGGAGTAATGCGAGGCCG
          TCTCTTGTTACATGAAGACTATACCTCTGGCCACCATACGTATGGGGTAATGCGAGGTCG
          CCCTCTCCCAGATGGGGGGTATACTCACTATTGCCTGCGACGGGGAGTAGAACAGGGCGA
          CCACCTCCCAAATGAGGATCAAGATGAGGATCGCTAAATGCAGAGGGCAGACCGAGGTAA

          GATCTTTCACAAGGTGCAGCGAATGTAACATCCCCTATATAGCCATCGGCATAGGCGACG
          GATCTTTCACAAGGTGCAGCGAATGTAACATCCCCCATATAGCCATTGGCATAGGCGACG
          GACAATCCACAAGGTGCATTGAATGAAAAATCCTCCATGTAGACATCGACATCGACGGGG
          GACAAACCACAGGGTGCAACGAATGAAAAATCCTCCGTGTGGAAATCGACATCCACGGGG
          TGACCTCTGTGATTGCAAGAATTGAGACCAGTGATCGAGCGGTACATCGTAAAAAACTCC
          TGACCTTTGTGATTACCAGAAGCCAGATCAGCGATCGAGCGGTACACTGTGTAAAACTCC
          CAAAGTAGGTAGGCCGGAGGATCCGGGCTAGCGCTCAAGAAGGTTACCGACGAGTTACAT
          TGAGATCTCAAATTAGGAGAGACCGGAACAGCATTGGCGTGGCATCCTAACCGGTCCATC

          GGGGCCGTTTCGTCGACAGAAAAACGAAACTATCTTCTCAAATATTTCAATTTGGGTTGC
          GGGGCCGTTTCGTCGACAGAAAAACGAAACTATCTTCTCAAATATTTCAATTTGGGTTGC
          ACCGAGGTTTCCTCATCGGAAAAGCGTACCTATTTTCCCTAGTCTATCAATCGAGGCTGC
          AGCGAGGTTCCCTCATCGGAAAAGCGTACCTATTTTATCTAGTCTATCAATCTAGGCTGT
          CCTCATGTGCACCTAAGGACAACAGAGACGGCGAGACCTGGATTCTAGTACAAAAGTCCG
          CCTTGTGCGCACCTAGGGGCCGTACAGACAGTGAGACCTGAATTCTAAGACAAAAATCCG
          TAAGACGCGTCCCTAAGGGCAGCACGCAAGACAAAAATCGCGATTTTGGGAAGTTATCGT
          CATGAGGTGTCACTGAAGGCTGTACGCAAGGTAACGTTCGCGATTCCGAAGGGGGACTGT

          ACTACGCCGTAGCTACGTGAAACACCCAAAGAAATGCCTGCAGGAGCTACCCACACGCAT
          ACTACGCCGTAGCTACGTGAAACACCCAAAGAAATACCTGCAGGAGCTACCCACACGCAT
          ATTAAAGCGTTGCTACGTAATAAACCCAAAGCAATGCCTCCGAGTGTTACAAATACGGGA
          ATTAAAGCGTTGCTACGTGATAAACCAAAAGCAACGCCTCCGAGCGTTACAAATACGGGA
          GTCACAAGTCCGAAATATATTCTACAGTTGATCCTCGGTCCAGTGTCTGCGAAAAAGCGA
          GTCCCGAATCCGGAATGAACTGTATTGTCGACCTCTGGTCCAGTGTCTGAGAAAACGCGG
          GTCCGAGACCAGAAATAGAGCGTACTGTCAGGTTGAAGCTGGGTCTCCGTAAGCGAGAAA
          GAAAGACCCCCAGAACAGAGCGCCTAGTGGGACACCAGCTCCTCCTCGGCAAGAAAGAGA

          TTCAATACTGGAGCAGCCGCAGCTGTGGATTGTCTCGGGGGGAGTAAATGCCTATCCCTT
          TTCAATACTGGAGCAGTCGCAGCTGTGGATTGTCTCGGGGGGAGTAAATGCCTATCCCCT
          ATCCATACTCGAGCGATCGAGGCTGGAGATTGTCTTGAAAGGAGTGGGTGTCTACCCCCT
          ATCCATACTCGAACGATCGAGGCTGGAGATTGTCTTGAAAGGAATGATTGTTTACCCCCT
          AAAATTGCTACATCGCTGGTGTTTTAGGGTCCTCACGAAATTACCGAATGGGCGACTCTT
          AAATTTGCTATAACCCTGGTGTTTTAGGGCCCTTCTGAAATTACCGAATGGGCGACTCTC
          TAATGTGTCAGAACCTTGAGATTCTAGGACGTTTCCGTAACAAATAAATGGATAGTACTT
          TAAACTGTTAGAACATTGAAGCTTCTGGGCGTCCCCCTGACTACCCAAGGGGCAGTCTTT

          GGTGCTAACTTGCTCCGGGCCGGACTCACGCCTTCCGTGGCCAGGTCTGAAGTGATACCA
          GGTGCTCACTTGCTCCGGGCCGGACTCACGCCTTCCGTGGCCAGGTCTGAAGTGATACCT
          TGTGCTACGCCGCTCCAGGCCGAGTTCGCGCTTCCCGTGGGTAGGCTCCAAGCGACGCCA
          TCTGCTGTACCGCTCCAAGTTGGGTTCGCGCTTCCCGTGGGTAAGCTCCAAGTGACGCCA
          GATCTGAGAGTACGCTGAATCCGGTTATTAAATAATGAGAGAGGCGAGAAAACGCAGCTT
          GATCTGAGACTACGCTAACTCTAGCTACTAAATAGTGAGAGAGGCGACGTAGCGCAGCTC
          GATGTGTAGTAACTACGAACGGAACTGGCAGATAGGAACAAAGGTTATAATGAGCTGACA
          GATTTGACGCGACGCCGAGCAGACCTGGCCTAGAGCGAAAGAGGTTAAGATTAAGTGGCA

          TCGGACCGCATAATAAAAACCGGTGTTACTTTGGCCAATACCACTTCCCTTAGTTAGTTC
          TCGGACCGCATAATAAAATCCGGTGTTACTTTGGCCAATACCACTTCCCTTAGTTAGTTC
          TCGGATTGTCCGATAAAATCCGGCGGTATTCCTGAAAATACCAACCGACTCCCTCAATTC
          TCGGATTGTACGATAAAATCCGGCGGTATTTCCGAAAATACCAATCCCCTTCCTCAATTC
          TTCGATAGAGAAAACCTCCAGAGATCCGCCTCCTGTTAGTCGCAATTGACCCGTTGCGCC
          CTCTGGATAAAAAACTTCCAGGGATTCGCACCCCCCTAAACTCTCTTGACTCGTTGTATC
          CTGGGGCGAACGGCGCCTCTAGGATTAACTCATTGCTAGATCTTATAGTGCGATGGAGGC
          GCAGGGGGATTGGCGCCGCCCGGACCCACCTACCGTCTGACTCCCTTGTGTCAGGGAGGT

          GATAATGTGCCTTGGGGTCCACTTTTATCCGAGTCCACTCGAAGATTATAAGCACGTACA
          GATAATGTGCCTTGGGGTCCACTTTTATCCGAGTCCACTCGAAGATTATAAGCACGTACA
          GAATGCAAGCTTTGGTATTCACGTATTTCTGAGTCTCTCTGAAGGTTATCAGCCCGTACA
          GATTGCAAGCTTTGGTATTTACGTATTTCCGAGTCTCTCTGAAGATTATTAGCCCGTACA
          ACCCCTAAGCTGACGCGGTATTTCGCTTTTGTTTTTACACTGGCGATACCGACAATTCCT
          GTCGCCAAGCCGTCGAGTTAATTCGTCTTTGTTTTTACACTGGCGATACCGATAACCCCT
          GCCTCCTTGCCTTCTTATTTTTCGGCCTAAATACTAGCATCAGGGATGACAGCACTTCTT
          GCACCCAGGCCGTTACGTCGATTGGCTGCCGTCTGGATCTCGGTGATTCCAGTACATCTT

          CCGCACCTAGTGGGGGCCCAACGTCGTAGGAAAAAGCCGCCAGCTCGTAGACTCCCGTCA
          CCGCACCTAGTGGGGGCCCAACGTCGTAGGAAAAAGCCGCCAGCTCGTAGACTCCCGTCA
          CCATACTCGGTAGGACAGCAAAACGGTGGACAAAAACCCTAAGTCCATAGATTCCCGGTG
          TCACACTCGGTAGGACAACAGAGCGGTGGACAAAAACCTTTAGTCCATAGATTCCCGATG
          TCTTGATTCGAGACCATATACTGCCGTCCACACCGTCGCAAAGCAGCTGGGCGTGTGATC
          TTCTGATCCGGGAACGTATACTGCCGTTCATACTGTCATAAAGTTATTGGGCGCATGATC
          ACTTAACCCCCATGAGTATACAGTCGACTGCAGCGTTGCGTAGCTCCTAAATAGGGGACA
          CCTTAATCCCGATGGATATGAAGTCGTAGACACGATGGCCTAGTTTGCGCGCGATCGGCA

          AATATCAGCAGCCTCCTCTCCCCGGTCGTAGAGGCGCTCGTTGGAGGTTTAGCGGGAAAG
          AATATCAGCAGCCTCCTCTCCCCGGTCGTAGAGGCGCTCGTTGGAGGTTTAGCGGGAAAG
          ATGGTGGGTAGCCCCATTCATCCCAACGTAGTGTGGCCTGACGGCGGTCTAGCAGGAAAG
          ATGGTGGGTGGGCCCTCTCATCGCAACATAGTGCGGCCTGACGGCGGTCTAGTAGGAAAG
          GCTGGCCTCAAAGCGGGCTAGATAATCACAAATTTCCTTTAGAGCATATTAGGAGGTTTG
          GCTGACCCCAAAACAGGCTTAATATTCATGAATTTCCCTTAGAGTAGATGAGGAGGTTTG
          TCTGGCTACCGAGAAGGTACGTCTATTAGAAATCTCCTTCTGAATACATCGGAGGGACTG
          GCTGGCCACAGAAAAGGTTTGTCCACTAGAAGTATATTTCTGGGTACATACGCGGGGCTA

          GAGGCCTGCCTAATTCAGCCGGGATCTACCTCCGTATGATAGGGGCAGTGGGTTTCAAAG
          GAGGCCTGCCTAATTCAGCCGGGATCTACCTCCGTATGATAGGGGTAGTGGGTTTCAAAG
          AGAGTCCCCCGAGTCCACCTGGGATTTACCCCCGTACGAGAGAAGGAGTGGTTTTCAATG
          AGAGTCCCCCGAGTCCACCTGGGATTTATCCTCGTACGAGAGAACGAGTGGTTTTCAATG
          AAAAGCGCTTCAACTTAACACAAAGTGGTGAGCTTGCAGTAGGAGGTAGTGAGGGGTCGA
          AAGAGGGCTTTAACTTAAGCCAAAGCCGTGAGCGTGCCGTAGAAGGTAGTGGGGAGTGGA
          GTACGTATTCTAAATTAAAGAATACTCGCACGCTTCGCGCACAATTTTGTCAAACGTTTG
          CTTAGGAATCAAACATTGTGGAGACTGGCACGTTTGGAGTACGAGCTTACTGAACGACTA

          ATCGATTGTTCGACGTGTATGAAAAAAAAGAGGGCGGGGG
          ATAGATTGTTCGACGTGTATGAAAAAAAAGAGGGCGGGGG
          ATTGACTGTTCTACGTGTATGAAAAAGTAGAGGGTGTGTG
          ATTGACTGTTCGACATCTATGAAAAAGTAGAGGGTATGTG
          CAACGGTGCTGGACAATTTGAACTACAGTACGCTTCGGGG
          AAGTAGACCTTGACATTTTGAATAACAGTGAGATCCGGTG
          ATCCGGATTGGGTAACGCGGTACATTAGCAAGTACTTGAG
          CTGCGGAGCAGGATATGGCGTTTTATCGCAAGCACTAGCG

