 8 1000
t1        ACGAGGGTAAGACATGGGGAATTCGGATGACGTTGCCGCGAAGAATACAGGCGCCTTTCA
t2        AGGGCGGTCTGGCTTGGGGGATTTGGCCGACGCACCAGTGACGGATGCGTCTATATTTCA
t3        GGGTTAGAATATAATAGGGACCCCGGGCGGTGTAGCTGAAAGCAAACCACGTGTCCTTCA
t4        TAGCAACACCGACCTGGGGTGCCCGACTGACTTCGCAGTGACAGGGAAGCACTTACTTCA
t5        CGAAAGAGCTCACAGGGGGAACTCGCGGGAGACGATCAAACGCGTAGCTGCCGAAACCCA
t6        TAGGCTGAGCAGAGTGGGAAAACGGGGCAACGTCGTTACGGAGGATGATCACGAGCTTTC
t7        TGACGTGGACACCACAAGGGATCTGGTAGATATTTCGCTAGCGAGAGTATACGTTTGCTA
t8        GACCAGGTGGGTCAGATGAAGGTAGGGCCAGACCGCCGGCCATTATGTGTATCTGCTCGG

          CTGTATAAACTGCTGGCCAGCGTAATGCACAGTCGAGACCCGAGACACAGGCGACATAGA
          TCATGCTAACGACGGCTTAGTAACGGGCATAATTGGGATTTCGGCCGTAGGTGGCATCGG
          TCGGGCCTATGGTGTGTTTTCATCGTGAACATCAAAGATTACGATAGCCAATAGTAAAGA
          TCATATTGCCCGTGTGACCATTCTAGGCTTGATCCATTTTTAGCCCGTCGGAGCCAGGAC
          ATATTCTGAACCCGTGTTTGCGGCGGGCCAGACCTTTGTACCAACAGTTGGAGACAATGG
          TTCTACGACGTGGACCTTTGTCGCATCTAAGAACGAAAAAGAAGAACGGAGTACTTTGCA
          TTACCCTTGTCGCTTTTCCGGGGAGAACGCGACCTACAAGACGACATCTTGCATGCCGAG
          TTTCTCGATACACGTGCACAAAACGGCTCCAACTAAGGAGGTACCCCCCTGATCCCGTGG

          AGTATGAATCTTCATCTCTAAGATGTCCGCGAGATCGACCGGATCGCCCACGTTTTTTCA
          AGCAAGTGTCATTATTTTTAATGTGTCTGCGAAAGTTGTAGGACCGCCGGTGCGTCTAAA
          GGGAAGGTTCTCCTGCACTAGCGTTTCGGTGTTACTGAAGTAGCATCCCAGGCTGCTACT
          TGGGAAGTCGCCTACTTCTGGCGTCCTCACGTTATTGCGGGAGGCGTTTAATAAGCTTCC
          AACGTGTGTTCTTCCCTCCGGGGCGCTTGCCTCAACAAAGACGCATGGGCTCCCGCCTCT
          AATCTGATACTATCACTACGACGGACCTGCGCTGTCGCTTTAGTTTTGGACCCCTTTCCT
          AGGGGCGTCCTCCGTAACCGAGGCGTTTGGGCCAAAGACGATGGTTATAACCAGCCTTCC
          CTCTGGCATTGTTGCGATCTGGTCGCATTTGTCAATTCAGGTGAGGTTAGGTCTACCGCT

          ATACCGCCTCTCACTTAAGTATTCTATCATGTTCAGGTGTGCCCGATGCCCTGTATTGCT
          CTCTTACTATTTGCTTGAGGATGCTGTCGAGCCAAGTTGCGTCCGTTGCTTTGTTTGGCT
          ATGTCGTAATCTCTTCATACCTTTAACGATGCCCAGCTACCCCCGATGCCTTGCTCAAGG
          ACCGCGCGAGGCTATTTTGTCTGTCATCATACCCAGTATGGTGCGATGCAGTACTTCGAT
          ACTCTGCCACTGACAGCAAACTATCACCGCACTCTGCTGAGTCCACTTCTCTTTCCGGGT
          ATCATACACCCCCACGACCCTCTAGGCCACCCTTGGCGCCTCTTCACGTTTTGTCATGTC
          CTGTCGCAATTTACGGAACTCCCGAACACAGATGAGGCGGACCTCCACCCATAGCCAGAT
          ATGTTGGGATGCTCCTACAACTCGCTCACTGCCCTGGAGGATTTTTAGTGGTCTACGCAC

          ACGATTGAGGTTACGACGTAAATGATTGGTGAAGTACATGGGATGGATGCTTCACAGCAT
          GCGGTCGCAATTACGATACAGGCAACTCTTAGGGAACGTGGAATGGAGACCCTACGTACT
          ACAAACGTAGTTTTATAAAACATAGAGTCGGAAGTGTGACAAAAGGATCCTACGAGGTAC
          GAACCCGTAGCCACAAAAAGTGCGGTTCATAAGGCTGCTAGACCAAGAACTATTACGGGC
          GTGACTATCGTATCGAAGAGCACTACTTGCAGGACACGTGGGTCGGGGGATCTTTGGAAA
          AATACGCAAGCAGGGTGGTACATGGTGGGTAGAAGAACTACATGGGGCATCGTTTAGTGC
          TTTGCCGAATTGACGTAGAGCACAGCAAACAAAGATTGAGATTAAGAGTCCCCCGGATGG
          GATACGGAAGTAAAAACCCCGTCGACACATTAGTCACGTGCGGCTCACCCTAAGTAGTCT

          ACAGATCCTCAATCCCGTTTAGAAGCCGTGGTGGGTTGTTCATGCGCAACGGAGAACGAT
          ACCGGTATTGCTATTCGTATGAGAGCAGCCTGGTCTAATCTACGCGTTTTCGAATTCGAT
          GCAGGCGTGAATCCCCACCTTGGAGTAGTAGAGCGTGAACCGCATGTAGGCGGGACGGAT
          TCTCACGATCTCTCCCGTAAGATCATTGTGGACATGCGTCTAAGACTAATTGCGAACCAT
          AATTATGATGCATCTTGTCTAACAGACGTGTGGTCAGTACTAGGTGCGGTCCCGGAGAAA
          CCCGCTGAACACGAAAGCACGGCAGGAGCAGTGCGCTAGGTTAACCTAGGTTGGACAGAG
          CAACACCACACTCTCCGTAAAATAACTGGCGGTAGAATTCGGGGAGCGGTTGCAGGCGAC
          CACAGCGCGTCGCATTTATTGCTCGTTGGGGAGATGTAATTGTGCATAGCCGCGGACGAT

          ACCGGGTAACATCAGGTGAACAAAAGTTCCAAAGAGCGGGGCACTCCCAGACGCGCTTAA
          GTAGGCCGACGTTTAGCACCTGGGGCTATTAATGAACGTTGTTTGTCTAGCCGTGATCGA
          AACGGTTAAAGTCGAGACTGGAGGGCTCGCATTGTCAGCCGCTGCCCAGTGCCAGCTTAC
          AATAGGTTGGTCCATCTGCCCGGGGTTCGTAGCGTAGAGCGTTATTTCGAACGCGTAATA
          GCGCAGGTTGGCCCATGGGTTCGAGCCTGCAGTAAACGGCGTTACTTCGGACATCCAGCC
          ACTGGCCTATGCGGCATGTCCAGGCCCCGTGGCACATGCAACCACTTTGCATATGCCCAG
          TGCTTGTAGAGTAGATAGCAAAGCGTCGGGGGTCCACGGTGTAATGTTACCTAGTACGAG
          AGAGGGGACGATTAGAAGACTGGCGCACTGAGCACCTAGAGCTATTCTATATGCGTCTTC

          TGTTGCTCAACAATATGGGGACTAAGGACCGACTGAATGGGATCGACCGACTCCGAGTCT
          TGTCGACCCGCGATGCGGGACCCGAGGATTGCGCTGTTGCGGCCGAGTGATCCTGGATCG
          AATTAACTCTCAGCTTACAGTTCGAGAACGAAACTAATCGGAGTACTTAAAATGATAGCA
          GGTCATTGTGCCCTGTAACGACGGGCTCCGGTAGTATCAAAAAAGCGCTGTTCGTAACCA
          AGTTGTCTTAATGTCCATGGATCCTGGACGGCGATTACAGCTGGTTAAATGCCGTAACCT
          AGTCGCTGTAACGTCACGCTGTAGATGTATCTGGGATTGAATGGACCAATAATTAGACCA
          AATGAGTGCAATCGACACGCGAGAGGGATCGCAGATTGGGGCGCACGACGTCCAAAGTCC
          AATTACACCCGCCCGGGGATTCCACTGCCAGAGGGTTTGGAGTCACAGTGACGAGTAATC

          TGCTTGGAGCCGGAGTGAAGTAAAAATAACAGCTGGACGGTGTGATTGACCAACTCTTCA
          AACGTATCGGAAGAGCATAGAGACAACGACAACTGGGTGGTCTAATCGACGCCACCTACC
          TGTGTATCGAAAAAGCGCAATGTGATCGCCAACTGTTCGGCGCCAAGAACTTTTCTTTTT
          TATGTGCAGGACAAACCCAATGCCCATGCAGAGTAAACGGTACTTAAATTGTCATTCTCT
          TGCGTGTAGGAACCACGGAGTACAGTCCACGCTAAAGCTACGCAGAGGGAGTCACGACGT
          GAGCTGTCGCAAGCGCGGATGTTATCTTGTACTAAGCTCGCATAAGGGTAGTAACCCATT
          GGGGAAGGGGAAAAAAATGACCCGTTGAACTACCGGGTGGCCCGTAAGGTGCCTGATGCC
          GAAAGACTATGACGGTCCGGTACCTCCATTGGGAGTGTGGCCCGTATGGCCTATCCTAAT

          AGCCCCAACCAGCACATGCCGTGGTCGTCGATAACGTACTACCACCATAAGCAGATTGCA
          GGTCCCAAGCAGCCCATAATACAATTCTCCGAATAGTTAAGCCACACCGAACAGATCGTT
          GATGTTCTGTTGTCAGTCTAACAATGCCCTGCACCCTGTTGAGACAAACGTCAGATCGTT
          GACTCCCTCCTACAAACCCGACAGTACCTACGTGTAAGCAGACGGACTTAATGACCTGTT
          AGCTCTCTCTCGGAGACTCGAAAACCTTCCGCGCCTCATTATTGCTGTTAAACAGTCTTC
          GACCTCCTCAAGTACCGGTGATGATTTCTAGCACAAAACATCTGCGAACGGGCGCGCGGT
          TCCTCGTTCGCGTGTGATTGATAGCAGGGCTAGTCGACCAGTTGCTATCGTTAGGTCATG
          TAATCCTTCGTAAAAGGCTGGCAGTGCTATGCTCCAATCCGTCCATGCTACTGACTCACC

          AGGGTTATTGCAAGGCTGAAACATTTACTGAGGGCTCATCATTTCGACCGGCGCATATGT
          GCCATTTGCGTAAACATGAACTACCTAACGGTGGCCTTCCGTCTCAAATGGTGCCTGCTT
          ATGTTTAGGGTAAAGGCCACCCATTCTGAGGTGGACCTTAGTCATGCATGGCCCGTGTTT
          CGCTTTAAGCTATAGATTGATTGCTCGGAGGTGAACGATCGCCATTACTGACGTGCCCGG
          AGGTTCAGCGCAGCGGCTAACTGTTATGTCGTAATCCTACGGTCTGACTGGCGTGCCCGA
          CGGCTGCGGCCGATCAGCAGTTGACTGAAACGGAATTTCTGCGCTAATCGATACATTCAG
          AAATTTATCGCAGAGGTGATTAGTAGGATTAAGAATTCGAGTCTCGATTTATGTGTTTGG
          TGGTTCGGAGAGTGGGATCGCCATCTAACAGCATAAGCCAACTCTGAAAGGCGGGATTTG

          AGCTGTGACTCAGAGATCGTGCCTTTCACCGCTCCACTTCCCCTTCGCAAATCAAGGATA
          TGTAGAGACCGGTAAGTTGCGTCCTCTTTTTCGATTAACACGTTTGGTTATTCGTCGGCC
          TCCCAAGCGCATTATGGTGTGCCTACAATCTTGCCCCAATCGCTAGACCGCTCGGAAGCA
          AGCCGTGACCCGTACGACGCTGCTACCATCCCATAGCTATTCTTGGGGGATCCATGAGTC
          AACCATTATACTTGTGATTAATTAACTCCTCCGCAGAGTGAACGTTGCAGTACTCAGGTT
          AGTAAGGCCCAAAGGTGCGTTTCCTCCGATCCATCAGACCCACATAAGAATAAATGGGCG
          GTTCGCACTACCGGCGAGACGCTCATCGTAACGCCCCACTTAGCTGGACGTCTTCGTGAG
          GGCCGCGACGCCAGTAGGGTTTCCCCTTCTTCACCAGGCTCCTTTAGTTACAGTTGACTG

          GAAACGGCTCCGCCGAGGGCAAATCCTGACAACTAATGGACATCCGAAGTTACGCCCCGC
          CATAAGGGCTTGCCAGCAGTGGACTCCAACATCTATTATGAACCGAAGGCCAAAGCACAC
          CGTGCGACTATATTGGCGCGGTGTGGCTTCTAGCACCCGGCGCTCCAGGGAAAACGTTGT
          GGTACCATTGACCTTCGGCAGTATGGTGACAACTCCACTGGAACGTAGCGTAGCCGTTGC
          GTCATTATTGAATTCCTACGCTCTCCTAACGAAACAATGGAGTGGGAGTGGACGCGCCGA
          CGAACGTTGGACCCTCTGCGAAAACCGGATAGTTCTACGAGCCTATACTAGGGGCACCGA
          CGACTGTTTGAAACTATGTCCTATCTGGTTCATTCCTTGAGCACCAGCGGCGTTTGCCGT
          TGACAAGTCCCTACGGTCCGGAAATCAGTCAATTTATGGGCCATAAGGAGCACGTCGCGG

          TAAGGCGTCTGTCTACTGCAGAGATACCTGAGGCCTACGCTCCCGCGGGCCCATAGCAGA
          TATCGCATTCGATGTTTGAAGGAATAACGATGGTTTTAGTTCCAACGGATGGAAAGCTAG
          AAAGTACCCAGCAGTTCGGATGGTGGGTCGTGAGTATGGCTTCCGGCGATGAAAAAGCAG
          CGACGTAATCGTTGACCAAGGGGGTAAGGGCGTTGTTAGTCAGTGGGAATAGCGTGACGG
          TAGTGTTCTTGCAGAACAGCGGAGGGAGAGGGGCACAGGGCCTTAGGAGCGAGAAGGCGG
          GAACATGCTCATAGTCTTAAATAAGTAGGAGCCTATTTGCGTCAAACGGTAAGAAATCTA
          TCGATCATTTTCCGCCTCATAGAGATACCGTAGTGTACGTCCTTGTTGAAAAGTGCTCGT
          TTGTCTAACTATAGCTGGACGATGGGATTCTGGCTAGGATCCTTTGTATGGGCTGCACAA

          ATCGCATGAGACCGGATCGCGACGTTGATGTACACTCCAGGCATTAATCAATCAAGATCA
          CTAACACAAAAACGGACCACAGCATCAACGCATCATTTGTATGATGCTCTACTCCGGTCG
          CTCACTCTAGAGGGGGTGGTAATATCGTCGTGCATTCTCACCGTTGAATAGGCATGTTCA
          CCCACGCGTGAGCTGATAGAAACGTTAGTTCAGCCTTGACTCCGCAATTTACCATGGGCC
          CCCATCTGCGCGTGGCCCACGTCATCGCAGCTATTTTTAGCAGGTAGTTCGTCTTAGTCT
          TTGCGGTACCAGCAGGGAGAATCTTTGTTACCCGGTAGTATTCTCGGAGCGTTTTCACCG
          GTCGTTCAACGACTTCTGAATATATCATCCTATTTATATCCCTGTAACCTGACATCATCG
          CTGAATTGTCGGCAGATGCCGAGCGTAGCATGATCATGTTATGCTGATGTAGACTAGGCC

          CAGGAGCCGGAATGACCTACTAGAGCTTGTTCATGAGAGAATGGCATCGCCGCACACAAG
          GGGTTGTTTGACTGCTCCGTTAGAGTCCGAACGCGAAAGGATGCTTTTGCCATCGAGTGG
          TCGAAGCCCGAAAGACACGCCAGCCTCTGAAAAATGAGGAGCAGTCTTGTCACGGTCGAA
          CGCCGCGGTAAATGGCCTGTTGAGTGCTTATTGTGGAAAAGCGGTCTTTCAAATTTATGC
          GGAGTGATAAGTCGCCGTATCGAAAGGCTTTAGTCAAAGGGTTGTCCCGTTATCGTCGGG
          GGGGGACACATACAGTTAACGAAGCGTCCGTCTTAGTAGAGTTCTCGCGAATGAAAGCGG
          AGGGACAGCGGGTGGGTAACCGGTAATTTCTAACAACTGTATCGTGATAAAATGTTTAGG
          TGGGGAACCATACGACTGAACGGGGACGGACTGGAGACGTGCTATAGAAACCGCATTTGA

          CCTGGCGGTGACCCGCATCTTCGAGTAAATGCGGCTGCTC
          CTTGGTAGCTATCTGTATTCTCCGACAAACACGTTGACGC
          TTTCGCTAATAGTAGAAGTTCCGGGAGCGAGCGACCGTCG
          TCTGCCTGTTAGTGCTGGCAGTATTCCGCAGCAACTGCTC
          TACCGCTGATAGCGCTACTTCTTAGTTGTTGCACCCAACT
          TCTCATTGTCAATAATAGTTTTGTTTCCCCGCTGCCGCAT
          CATGGGACCTTTTACTAAACTCGCGACATCCTTATCAAAT
          TTTCAGTTTCTACGCTGCTTGTCAAAGACTGATACTGTCC

