 8 1000
t1        GCTGGAGCAAGAGAAGGGATTCATCGGCTTGCGAACTCCTATTGGCCTCGTTACGCCGAG
t2        GCTGGAGGAAGAGAAGGCATCCACCGGCTTGCGCACTTCTATTGGCTTCGTTACGCCGAG
t3        TATGGAGCGAGGGAGGGAATCCATAGGCTTGCGCACTTCTCCTGACTTCTTTACGCCGAA
t4        GCCCTGGCAGAATAAGGAATTATATAACTAAAGTAGCCTTACCAAATTTCCCATACGTAG
t5        AGCGCAATCCGATAAAGAAACACACGTATTGGGCAATCTCGACCATTTGAACTCATTGGG
t6        ACCGCGGCATGCCACAGGCCCCCGCAAACTCGGTAGGCCTAATTCGTTAAGTGCACGACG
t7        TCATGGACGAGCTAACCATTCAAGTGCGGTACGATGTCAGACCGTGCCTGTAGAAGCAAG
t8        CAAGCGGAAGCAGGGTACGATAGGTGACTAGTATGAATTTTGTGTAGTTGTTTCGCCACA

          GAGAGTATTTATACGCAAATTTATGGAGCGAAATGTGTGGCCGTTCGCTCCACCGCATCG
          GAGACTATTTATACGCAAATTCATGGAGCGAACTGCGCGGCCCTTCGTCCCACCGCATCA
          GAGACTATCCATTTTTAAAGTAATGGAGCGAGTTGCGTCGCTGCCCGATTCCCTGCATCG
          GTCTCCCCCAGTTCCCAGATCCGTGGGGCGAATTAAATTGTCGTCTGACTCTTCGTGCCG
          TACATTCCCCTTATTTAACGCTACGGGACGAGCCGGAATACAGCCCGACACTGAAGGTCG
          GCTTGCCCCCGCCTTCAAAGCCGTGTGGCGAACCTGTCTACGGCACGACCAGCTATCTCG
          AACTAATGCAGTCACCCGGCTAGTGGGCGGATCGAGACGGCCTTGCATTTTAATGCACTT
          CGTTAAAGTTGGGCTTGCTTGAAGATTATGCGTACGGTAGCGGCTTAGGTCGATAAGCCA

          TCGCTTGCCCCGGTATCTCGACGGCGTAGTCAACCCAGTGTAATACAAATGAACGCCGAA
          TTGCTTGCCCCAGCATCTCGATAGCGTAATCTACCCAGTGTAACACAAATGAACGCGGAA
          TAGATTGGCCCAGAGTCTCGTCGACGCAATCAACCCAGTATAGTAAAAAAGAGTGCGGGA
          AAGGATGCCACAGCGTCGCGGATCCGGAATTCATACTATGTACTAATTAAGACCGCTATT
          CGGAACGTCCTTTTGTCTCGGGGCCGGAATTTACCCTGCGTAGTGGTAGTGATCACGTAG
          CGTTATCTTCCGTCAGCTCAGGTAAAGTACCCGAATAACGGACCTATAGTTACCGCGGAA
          CGACTCCGGGCGTAATCCCAAAATAGGGACTGGGTTTGCCTGATCGCAGAATTACTGACA
          GTGCCTCTCCCAAGTACTGAGAAACCAGAGTCTCTGTACTCCCCTATTCACGGTCTGACA

          ACGTCAAAGAATAATTCCATGGTTAAACATTCGTCGTTCACCGGGCTCCGAGAGTGTTTC
          ATGTGAAAGAATAATTCCGTGGTCAAACATTCGTCGTCCACCGGGCTCCGAGAATGTTTC
          ATATGGAAGCATTACTGCATGGCCAGGCATCTGTAATCCACTCGGCTCCGAGAGCGTTTC
          ATGTAACTGCGATACCACCTAGCCGAGGTTCGTTTTAGTTTCGGACCCCGACGGTAACCA
          ATGCTAGGGTGATGCCACCTGCCTAACCGCTTGTTTTGTACCAACTTCTGCGATTGATCA
          TCGGGAAGTCGATACCTCGTGTGCAATCGTGTTCATTGTATCAAACTCCGCGAGTGGTTG
          ACGTGGGCAAATCGTCACACATCTACCCTGAATTGCAACAGTCGATGTTACTGATATTCT
          ATGTGGAGGGGGCGTTGCAAGCGTTCGGGTCAATCCCATAGTTGTGCCTGGAGATACCCA

          ACTGTTGTACGTACGGTAGGTGGCCTACAAGTTTCCGGGGGTCATCGGTCTTAAACGTGA
          ATAGTTGTACGCGCGGTAAATAGTTTGCAAATTCCTGGGGGACATCGGTCTTCAACGCGA
          ACTGGAGTAGGCACAGCAATTGCTTTTTACAATCCAAGGGGTCATCGGTCCCCGATGCGA
          TTTGTGGCGAATTAGGCAACAAGTCCTTTTATATTTCGCAATCATTGCTTTCGTATCCGA
          CCTGCTGTATAACTAGTGGTAGGCCCTGACGTCCCCTGGGGCAATTGGCCTGAGTTCGAA
          CCAGTAGTCCAAGAGACCGCGACTCCCAAGATCGCCCAGGGCATTTGAAACCAGGTGTGC
          TATGACGATGCATCGCCCGCCATTATAGGGACTTCTCGGGTAGGGCGGGTCTATCCCTGA
          ACCACCAATCCAGCTACTGTGAACCGCAATGAACAATCGAATGCTAGTGGACCGGTGCGG

          TACTCATGCAGGACCTACCAAGATGGCTAGTGCGCAAAAGAAGATTTTGAAGAGCGTGTA
          TGCTCATGCTGGACCTACCAAGATGGCTAGTGCGCAAAAAAAGATTTTGAAGAGCGTGTA
          CACTACTGCAGCAACTATCACAATGACTACCCCACTGAAGAAGACTTTCAATAGCGCGTA
          TTTTCCGGCGGGATTTATATAAACGGTTACTGTACCAATGAAGATTTTACGGAATGCACA
          CGCTACCGTGCGTTCTATGAAAAAGACTTTGGCGTGGATGCGGAAATTACTGGGCAGGTA
          TACTTCCGTGTGTCGTACACGAGGGGCCACTGCGCACACCTAGCTCTTGGACAACGCGTG
          GTAGGAGGTTTGCAATACGTGAGACGGTGCTGTACGTGCCCGGACACGAAAGTACGAGCA
          AATAGCAAGAAGTGGTTAATGGCGAATTGACGTGTATATTGAGCTATTTAAGCATGCTAA

          CCAGCCATTCCAAAAGCGGGCCATTTTCTGCCCGTTGACCGGAGAGGGAACTCGAGAGAG
          CCAGCCATTCCGAAAGCGGTCCATTTTCTGCCTGTTGACCGGAGGGGGAACCCGAGAGAC
          TCAGCTATACACAAAGCGGTTCATCTTCTGCTTGCTGTCCGAAGGGGGAACCCACGCTAA
          TTTGTAGCTCTAAAAACTACCCATTCTCCCGTTGTTGATTGGGAGGGCAACCCACTTGTG
          AAAATACTTTCGTAGGCAATCTATGACTTGGCTACCGCTTGGAGAGCGGAAGAGATTGGG
          GTCACAACCCCATAAGAAGTCAGAAGCTTGGTCGGCTCATTGTCATGGAGCGCCTGCGGG
          ATAAGAAGACTTATTGTAGCCCGCGAAACAGTTACCGCTCGACGAGGGGTTGGGACCGGT
          CCACTGCCTACGCTTGGATCACTCTACGTGGGTGCCGTCCAATTAGTGATTGTGCCCCAC

          GCCAGAACAAATAGATTATCTCACAACGCTGGAATGAAAGAGGGAACTTCATCAGAGATG
          GCGAGAACAAATAGATTACCTCACAACATCGGAATGATAGAGGGAACTTCATCGGAGAGG
          GCCAGAACAAATTGAATATACCACAAAGTTGGAACGGCAGAGGCAACTTCACCGGAGAGC
          TCCTTCATACCCAGACTGTACTACAGGGCTTTGCTGACTGAAGTCAGCACTCCGGACGAG
          GCTTGGCAGGACGGGCCGAACCATCGGACCGCGTCGGCAGTGCTTCGCCCCCCGAGAGGC
          ACCTGTCGAGATCGGTTTAGCGACTACATGGGGTCAACAGCGATAATTCTTCCGGGTGTC
          GAGAGGACCAATGCGCGGGACTGTGAGATCCGGCAACCGGCCCCAGGGCTACCGGAACGG
          CTCACGTGTGCTAGATCGTCACAAAACCTTGGTCAGGCACTTGCGGGACCCTTACAGGGG

          ACAAAGGATAGGCGTGCTTTGAGGGCGGACCTACCGGGGGTATGCGTAACTTAGGATCCT
          AATAAGGGTAAGCGTGCTTTGAAGCCGGACCTACCGGGGTTATGCGCAACCTGGGATCCC
          ACTAAACGTAGACGCGCTTAACAGGCCGATCTATTGGGATCGAGTGTAACCTCGGATCCC
          ACCGAAGAACGGTAGACAACAAAGGCAGATCTCCTACTGGTGTGCGCAACGCGGGGCTCC
          GTCTCGGGCGGGCGTACTCGGGCTGACGATAAACCGGGGTGCCGTGGAATTTAGGGTTTA
          GTTACAGTTGGAGGTACCCGACTAATTCGTACTTTTGGGTCGTGCCAACTACTGGGCTCT
          GATGCACCCAATAGCGCCTGGACGTCTAGTCTCACTAGAGCAATCCTGTTATAGGAGCCG
          GTCGTACACAAGAGCTCCCGAAAGGGCAGGTAGTAAAGTGTATCGGTTGATCAGGACACG

          CACTACCGGTAGCGCAGTTTGAAGTAGGCTTGACTCTTAATACTTCGCGTCAAAAATAGT
          CACCACCCGTAAGGCAATTTGAAGTAGGCTTGACCCTTTATTCCTCGCGTCAAAAGTAGT
          CACCGCCCATAAGGAAGTTTGTAGTAGGCTTAGCCCCTTATCCTATGCGTTAAAAATAGA
          CTTAACCCATCCCAAAGTGAGCCTCAGGTTTGCCCCTTCATCTTTCTTTCAAATGATAGA
          CCCAGCCAAAGGGACCAGTGGTCTTACAGATGGCTTTCACGTTTCTCTGCCAAGAAAGGT
          AGAAACGCATCGAACTACAGGTTTCTGAATTGACCGATCCTGCCAATTGATATGGGTCAT
          AACACCCTATAGACTCGCATCAACTAGACCTAGTCCACGCTGCACTGTGTCGGAGAAGGC
          AGTAGCAGCCCGTGAACGCCAATCCGAAGCCGGCCAAAAACGCGAACAGTTCACAGTGGT

          GTATAGCGAGTGCCGCCCAGAAACTGCTACAATACTCCGGCCCCAGTAAGATCTTAATTC
          TTATAGCGAGTGCCGCCCAGTAATTACAACAATACTCCGGCCCCAGTAAGATCTTAATTC
          CCTAAGGGACCACAGCCCGGTAATTGTTCACACACCATGGCCCCAGTAGGATCTCAATTT
          GCTCAGTTATCACCGCCGTGTATCAGCGACTACCCCACAGCCCCCGTAAAGGTACATTAC
          GTCCGGCTACCGCCTTGGGATATTCACACCCAAAGTATAGCCCCAGCGAGGTTACACCGT
          GTCTTACTAACACTAAATCATACTTGGCTCTAACTCCAGATTCAAGTAACGGGCTAGCGC
          TTCAAGTCGAAGCCCTCTAAGGTGCACCCCTTGCGCTCGGCAGTGCGGACGGTGTACAGG
          TACTAGACGGCAGTCCCAGGCATGGAAGCCACTTGCCCTGTATTGATCTGGGAGTATCAT

          AACCTCCATGATTATCACATTTAAATCTTACACAAAACGTCTTCAGTGTGACATAGATAA
          AACCACCACGATTATCACATTTGAATCTTACACGAAACGTCTTCAGTGCAACATACATAA
          CATTACCACGATTAACGCATATAAGTTTTAACCATAACGTCTTTAGTGCAGAGTAACCTA
          GAGCGACGAAGCCGGTATATCTCTCCCTCTCGCTCGACCAGATTGATGCATAATAGCTAT
          AAGCATACCAGGCCACGCTAAACCATTTCTTTTCAAGTCCACCCAGTGCAGAGCCCCCTG
          GTCCGTACACGGACGTATTCATCTGGGTTACCCACGACTGACGCGGCGGAACGTTGTTTA
          AGGTGTGTTAAAATAATCACCTTTGATCCCCATAGCGCTCCTATGCAGCTCCGTGAAATG
          GAATCCGTATGGACAATCTATGTTCACCACCGTACCGATGGTTAAACCTTGAGAAGTTAC

          AAGCAACAGATTAAATCGCGGTACGAGGTGCGAGTCTCGTTTCTGAAACCGTAGACTGGA
          AAGCAGTAGCTTTAATCGCGGTACGAGGTGCAAGTCTCGTTTCTGTCATCGTAGGCTCGA
          AAGCAACAGTTTCGAGTGCTGTACGTGGTACCAGCCTCATTTCTGAAATATTAGGTTCGA
          CAGGCAGAGTGTCAATGACAGTATGAGGCCAAGGTTCCCCGACTGCGATGTTGAGCTCAA
          AAGCGCGCGTATTAACTATGGTAAGACGTGTCACACACGTCACCAAGGCCCTGGGCCTAG
          GCGGACCAGCACATAGTGTAGTACGACCCACGGGGTTCGTTACTGAAGCTTGGGGCCAAC
          GCAAACAAGTCCTGATTCCGCCCTAATATACAAGCCTCGCCTAACACACTTCAGACGAAG
          GTGGCGCGACAAGCGATGTGCGGAAAAATCAATACCTTAGTATTGCAAATAAGGGTCGAA

          AGATTTGGGACGGAACTATACATGGCGACTAATCGCAGGGCGTAAGGACTATTGAACCCC
          AGATTTGGGACGGGACTGTAAATGGCGGCTAATCGCAGGGCGTAGGAACTAATGAGCCCC
          AGATTTCAAATGGAACTAAAAATGGCGGCCGATCGTAGTGCGTAGGGTCTATGGTACTCT
          GGGCTTTGGCTAGCGCCATCACTATTCGGCATTCATCATGAATAGGGGTATTCGTAACAC
          ATCACTGTAAGGACGTCACGATTTGCGCTCAACAATCGAGCTTACAAGTAATTGCGTCTT
          CAGACTATGAAGACGATGACCCCTGACGCCAACCGTTGGATACAGATGCTGGTGGGTATC
          CAACTTGATGATATCCAAAAATCGAAAATCCAGTTCCGAACGTAAAGGCCAGTTCGTCTC
          TGCACCAACCCCGATCTGACACCTAAGCCGTTTTAGAGGGCAGGGCCGCCTACTCGTTTC

          AAAGCTAAGAGGCTGCGTTAGTTTAACTTATGGTAATGATTTTGCGAGGATTGTACTACC
          AAAGCTGAGAGGCCGCGTTAGTCTAACTTGTTGTATTGAATTTGTGTGGATTGTACTACC
          AAAGCAAAGAGGCTGCGTTAGTCTAACCCATGGCAACTAATTTGTGCGGCTTGTTCTATC
          GCAGCGCAGCTACTAAGCTAGCATAAGCCATGGGGATACGTTTGCTCGCCTCGTCTAACA
          ACGGCACAGATCCCGTGCCACACTTAGCGATGCGGTCCAATTCAGGCAGCTTGTGATACC
          GTTGAAACACAGTTAGATTGATTCCACCTGCAGAGTCACGCTTACGATACTCCCATCACC
          GCGGCACGTTATCCGTGTTGCTTCCCTTCATGGGGCCCCACCGGGCAGGCTACTATAACT
          CTGAATGAGCGCGGTGTAGAACCTCTACTAGGGGGCGAATCCATCATGGAGTCTTTACAC

          GGTCTATCCGACGAGAGGCCCAAATAAAATACTGAGCGATCTTGCTCTTTTAGATTACTC
          GGTCTATCGGACGAGAGGCCCAAATACGATACTGAGCGATCTTGCTCTCTTAGATTACTC
          GACCGATCCGAAGTGAGGCCTAGATAAAATGCTGAGCGAAATTGCTCACCAGAATCACCA
          ACTCGACCACGCGAGCGGTGTAGCAGCCGATACGGGCGCCCCAGCACCTTTATAATATTC
          ATCGAGTGTGATGAGTGGCATTGGATACCACACCGGCGATTTCATACACTTGCGCTGAAT
          GTTGGGTCAGGCCAGCAGCGAAAGGCACGACTAAAGTAATCTAGTAGATCTATACACTCC
          ACCAATTATGCCCAGTGGAGAAGTTTAAGATTTCTGGGGGTTTTTATTTCATTATCACAT
          AGATAGCAGGGCTTGAACTGTATTCAGCCAGCCCGCGGGTGTAGTAAACGTTCGAAACAT

          ACGAAACAAATCGGTGGCCTGAGAGTGTTCCAGACCAGGT
          ACGAATCAAATCGATGGCCTGAGAGTATTCCAGATCAGGC
          GCGGAACAAGGGGCTGACACGAGAGTGTTCCGAACAAGTC
          GCGTGATAAAGGTCTGACATGCGAGCGTTATGGGTCGGGT
          ACAATAAAAATGTCCGATCTAAGGGAACTCGAATCCAGGC
          ATGCAAGTAGAGCTTGAAATATGAAAACTCAAAATTAACT
          GCGGTAATCAGATCCTGCTGGCTTAAGGCTCACCCGGTGT
          AGTAATTTCAAATCATGCAACGGTGAAGTTCAAGTTGGGT

