 8 1000
t1        AAAGCTTCGTCACTGGATTCTCGAACTACTAGGGTGCGGTTACTTCACGTAATCGAATAA
t2        CCAATCCGCTCATTGTAGTCTCGAATCGCTGAGGTACGGTCATTCCGCGTAATTAAACCA
t3        ATAATCCGGTCTTTGCAGGCTCGGGCTACTGGGATACGTTTACTCCACGTAACCAAAGGA
t4        GGAGTCCAGTCACGCGCATGCCGACTTATTGAGCTACGACCGCGCTATGCTATCAGATAA
t5        AACATCCGGCAATTAGCCCCTGGTATAGCTGGGGTATGAATGCCTAACGTAATCTAACTA
t6        GAAACCCAGCCTTGGGGGCCCCAAATTAGTGGTAGAAGTCAACCTATAATCGTTAAGAAG
t7        AGGTTCTCGTCATAAAGTGCGGGAACGGCTTAGACAGTTCCACTGCTAATTACCAGGCTG
t8        GACCCAGTATCAAGCGAAGCCAACAGATCCGGAGAAGACCTATTAACATCTGGAAACAAA

          CAATGACGCAATGAGTCGAGGCTTCAGGTGTCCGAATTATTCTAATACTGACACCACTTA
          CGGCAACGCAACCAGCCAAGAATTGGGGAGCCTCAATCAGATTTAAACCCTTACCGCTCC
          CATTGGCGCCACGCGACGATACTTGCGGAGTTCTAATTATTCTTCGACACGCGCCACTCA
          CCAGAAAGCAATGAACTGAGACCCGAGAGGCTTTAATTCTCTTCAAGGTAGTATCATCCT
          CGGCCACGCGCCGAGCAGAGTACCTAGAGGTTCCAAGTATCATTAGATACTTGCCGTCCT
          TGTTTCCCTGACGAGCAGAGGATCGAAGAGCTCCCACTTTTTTTGGATTCCGGTGGCCCA
          CGCAAATGCGACTGATCACAGATTGAAGCGTTCGCACTATTAGTGCGATAGCATTATCAG
          CCGATAGAAGCTAATCGCGAATTTAGAGTGTTCGGGCCAGCATTTAGTATATCCCTCGTG

          TAGGTCCAAATCACGACTCCCTCTTTCGGGACAGAGCCGAAAAACATCACGTCCCACCTG
          CGCGCGCGAACCGCGACCCGCCATGTCGGATCCGGGCTCCGGGACTGTCTGCCCCCCTTG
          TTGGCACGAACCGCGGCCCCCTCCTTCAGATTAGTGTATCGGCACACCCCCCCTCCCCCG
          TTGACACAAACCGTGATCCTCTCCCCAGGGTTGGTGCTCAAACGCAATCCTCCACCCTTA
          TCAGCATGAGTTGCCGCACCCTCTCTAGGTTTAGTGCCTTAGTACGGTGCCCCCTCCTTG
          TCGATATGACCTGGGATACCACCTATCGCACCAATTACTCCACATAGTCATTCCCTTCTG
          CACGTCCAAACCGAGGGGGCGTTATAAGGACTGGTGCCTTGGTATCCGACCCGCCCCCTG
          GAGTCCTGCATCACGGTTGTTCCCTAAGGATGGGTGATCCCGCACCGCCCCAGAGTCTCT

          GACCTCTGCTCCCGCACAGGCCTGGTATCCTCGCCACTAGCATGAACTGTAGGATGACCA
          GAGTCCTGCTTTCGACCACGCCCGGGAGCCTCGCCACCGGCATAGACTGTAGGGTAACGG
          CCACTCTGTCCGCGTCCAAGCCGGGGATGCTCACCACTGGCATGGACTGTAGGACGACGA
          CGACTCTGTGGGCTTCCAAGTCGGGGGGCCTCGTTCCCGGCATGGACTGTAGGGTGACAC
          GAGCTTCGTGGGTGTACAAGTCAAGGATCTTTGTTACTGGAATATATTGTAGGTAGCTAG
          CTACCTTGCCGGCACGCGTACGGGAGTCCCCTGTCTTGGGCAAGTGCTGTAGGACCATAG
          AGGACTCCCAATAGCGCATATGAGGGCTGTGTTCCGGTTATATCCAATATTTGTTGGTCG
          CGGCCGCTTTGGTTAGTGTTGGGGTGTTTTGCTTCTCTGGGAGGTACTGTGGGTCTCTCG

          GAATTAATCAACGCCCCCTGCCGGCGGGCTATTGGTTCGTAGCCGAGGGTTGAGCCCGGC
          GGCTCTGTCACCGCCCTTCGGCGACGAGCCATCGGCCTGCAGCCGTGGCTCCAACTTAGC
          GGACGTGCCACCGCCCCCTTCCGACGAGCCACCGGTCCGTCGCCGTGAATCGAGTTTGGC
          CGACTGGTCACCGGCCTATGCCAACGAGCCGTCGGTCCAAAGTTGTGAGTAGCGCCCGTT
          TAACGTGTTGCAGCTCTGCGCCGACGAGTCATCGGTCACCAGCCGAGCATCGCGCTCGGT
          GGACCTGCCTACGTGAGAAGTAAACGCGCTGCTAAGGTACATATGAGCCTGGTGCTCGAT
          GGTCCCCCTGCAGTCTCCATTCAGCTAACAGTTGGGCTGCTACGGACCATTGCCAATATG
          CACCCGCGTCATTCCAGACCTTGGCGGGTGTACACGCTCCATAATTGGATGCCTTATAGT

          TACTAGGAGCAGCATCGAGAACCATGTCCAAGTAGTAGAACGTTTACGTCCACTGAATTG
          AAATAGGAGAAGCGTCGACAGCGATGACTAAGCAGTAAAACGTCTACGTCGATCCAGTCT
          AACTCGGAGGAGGACCGAGAGTTGTGTCTCGGCAGCGAGATGTCTCCGTCAACTGGACTA
          AAAGGGGAGATTCACCGCGAGCCTTGTCTAACTAGTTGAATATTTATGTTCGCAGAATTG
          AGTCCCGAGATCTACATTGAATTATCTCTAAGTAGTAAAAAGCAAGCGCCTGCCGAATAA
          AACGGCATGTAGCAATTTAAGAGATCTTTACATATCCTAACACCTAAACCAGTTAAATTT
          AATGTGAAGCTGGAGTGTCACATACGACTGGATCCTGGTACGCCTTAATCAGGCGAATAT
          AACATCGGGAAGCAGCAAGGAGCAGAACACTGCGTTCACATGCCGCGATACTGCAAACCC

          GATTGTCTTGCAGTGGTTGGAGTTAATGTATCGTTCTTCCCGGCACTGGTATTATCAGGA
          GAGCGCCCTGCAGTAGTTCCAGTTACCGTCTCGCTCACGGCGGCTCCAATGCCATTACAA
          GTTCTTCTTGCAGCGGTTCCAGTTACAGTCTCGATCTACGCGGTTATAATGTGCTCAAGA
          TCTTGTTTTGCAGCGATTACGGATAACGCTTTGCACACCACCACGCCGTTGTTGACAGCC
          GCATGTCTAGTGGTGGTTACGGCTAGCGTTGCACTCCTCGCCGCGATGCTGCTGACACAA
          AGACACATAAAGATCGATACAGTTAAATCTCTGGTTCCAGAAGTGCGACCATTACCAAAA
          CCACCTGTCGTCGCTGATGCAAAGAACGCCTCGGTTCTCGTTGGGCTTACGATATGATAG
          GAGTCTGTAATGTCGGTTGTACATCTATTTCTGACCTATGCTTCACATATAGCATAGTCC

          AGTCACACAAGTCTATCTTAAGCTGCAACGCGGTGATAAATAGAGTTTTCTACTATGGCT
          AGCTGTACGATTCAACCGTAGCGCGGGACGCGGCGATCAAGGGACTTTTCTACATAAACC
          AGCTGTATGACCTCATCGTAAGGCACGACGTAGTGGTCACCAGACATTTCTACATAGGCT
          AGTTGTGCGACTCTATCGAAAGACGTGGTGCGTTGTTCGCGTGTCCTCTTTACTTAGGCT
          TGCCGTACGCCTCTGTTTTACAGCGCGAAGCGGGGATGAAGGGACCCACATCCCCTAGTC
          AGCCGCACGAATTCATCGTATGGAGCGGCGCAAGGACAAAGGGTCCACCAAAAATCGGTT
          AGCCGCTTAATTATTTTGGAAAATATGGCCCAGAGGAGCTTCAGACCTTGGGCATTGGCC
          GACCGGACGAAGCCGATTAGCGAGCCAGCCCGGTGGGCTATGAAGTCCTTGATTTGGTCT

          CGCTTACTCAGGTGTAAGCTCCCATGCGGTTCTTGCATTTAAATATTTAGGTCCGGCACA
          TGCTCATCTGAGTGTGGGTACGTACGCGGATCCTGCCTTTCAGTCATTAGGGCTGGCATA
          TTCTTGTTGATCTGAAGGTTCGCACGCGGTGGATGTGTGTAACTTATTAGATTTGACACA
          TACCTATTTAGACGGACCCTCAGACGCGGCTCTTGTACTCACATTGGTGGGCCCGTCGCG
          TGCCTACTAAGGCAAACGGTCGCATGCGATGCTTACATCCATATCGCTAGGCCCGGTATC
          AACCTACTTCGGTAGATTACCACGTGCGATGGTAGTATTTAAATAAACAGGACTAGCGAA
          TGCAAAATGAAATAATTTATCATCTGGTGGGATAGCATGCAACTTAGTCTGTACAGTGCG
          AACATATGGCATCGGTCCCAATAACGCAGCGTTCTCAGGCGAAGCCCTTTAGTAGCCGTG

          TACGAGTTCCCAGAAGCCCGTGGGGTTACCGAGCCACCTCACCTAAGCCTGAGAACCGAG
          TGCTAGCCCCGAGAAGCCCGCGGGGCTGCAGCGCGACTTTGACCAAGTTTGCACACTATG
          AGAGTACTCCCAGAAGCCGGCGGGGCTGCTGTGACACCTTACCCAATTTTGTGGAGTGAA
          TTAGATCTCCCAGGAGCCGGCTGAGTTGGTGTTCCTCTTGGTCCATGTTAGTGAGCTGAG
          TGAGAAACCCTAGCTGCCTGCTGGGTTGCGGTCCTACCTTCCGTAGCTCCGAAAGTTGGG
          GGAGAGTGCGCATGAGTTTTCCAGGGCGTGTTGTGACTTTATGTTCATTTGTTAACACGC
          TATGCTCTTCTACAGCCCCACAACGCTGCGGCGATCTGCTGCCTACTTTTGTGCTATCAG
          CGAGGGCCCATGTAACGACGCAGGGCTTCAGAAAGATATTTTCTGAACGTGAATCGTTTG

          GGCCCCCCTGGAAGGGTAACCGCCGGATTTCTCAATAGAAACCGGGACGGTAGGCTGGTC
          CGTCTCCCTGGGGCAGCGTCCGCAAGATTATCCGATTGGAGTCAGACCGTCGGGTGGGTC
          AGCCTTCCAGGAGGGATGATTGCAAGATTTTCTAGTTCGAGCCAGAATGATGGGCAGGTC
          CCTACACAAGGAGGGGAATCCGCAATATTCCTGATTTCACGCCAGATCGGTGGGCGGATT
          ATCCCCCAAGGTTGGGAGATAGCACGTTTTTCCATTTGTCGGGAGATCTGTAGGCGGATT
          GACCCCCTAGGAGGGGATACCGTATTACTTCGCGGTGTGAACAGAACCGACGATCGACTA
          GAGCCCTCGTAAGGAGGGAGCGCATCACTGTTCTATTGAGGGCGCCTTGGTCAGTAGATC
          GGCCTCTGAGGGACCCATAACGCTCGAACTACAGATCAAGGCAACTACGACAGTGGATAC

          TCGCCTGGCATGGTACGACGTAAGCATATGCGTTGCCCGCCGGTTATACATAATTCATTG
          TCACCCCGGACGGCGTGTCCCCAGTATGAACAATGCCCGCCGGTCATGCATAAGTCACTG
          TCACTTTTAACGGTTTGACATGAGCCTTTGCGATGACAGCTGGCCCTGGATAATTTACCG
          TCCTGTCGGACGGTTCGACCCTAACACTCGCAATGCCCGTCATCTCTGTAAAACCAACGG
          TCGTCTTAAACAGTCTTATCACACCACTACTGGAACCTGCCACCCCTGCAGAGCCGGGCG
          TTGACTTGCTAGACCTAACCGTAATAGTTGATTCACGTGACAGCTGTGCATAATTGAGTG
          TTGTTTTGTTTGGTAGCATGTCGAGCGAAGTGTTTGGCGCAAGCTCTGCTAAACTAAAAA
          GTTTTTGGAACGAGTCGCTTTCAGTGATAACACCACGAATCTGTCGTCTATCCCATAGCT

          GTCAGGAAGTGCACCGGATCCTCCCGTGAGTGGGCTGATTGATAATTCTCACAAGTTGTT
          GTTAAGACGAGCAGCGAGTTCTTTCGTGAGCGAGCTGAGTGACAATAGATACAAAGTTAT
          GTCAGGAAGTGCTACGAGTTGACACGTGCGCGGGTAGAGTGACAGCTCATACAAGGAGTA
          GCTAAGGAATCTCGCGCACTCCTTCGTGGACGGGAAGAGCGACAAACTGTGCAGGGTGAT
          GTAGTCAAGCGCAGCGAGTTCATCTGCGAGTAGTCGGCGTGTCAATTTATGCGAGGCGAT
          GTCGGGAATGGCAGACTGTATCCCCATGTGTAGAAAGTGTCCCAGGTCCCAGGAGACGCA
          GTCAGACAGTGAAGCGGCCCCGTGTACGAGTGAGCAGGGTATCATTGGAGCAAGAAGGAC
          GTCAGTCGCTATCATGGGTCACTATACGTGGAGGCCTGGTACTCGTATAACGACGCCGGT

          CGTGTCCGTTTCAGATCAGACGGACGATTTGTGTACGACTCCCCGGTTAGCATGCGATTT
          CAGGTGTTTCTTAGGTCTTACCATCGGTAAGTGCACAGCTCACTGGCTCTCATATGGACT
          CGTGCGAATTCCAGGCCAGACCAACGGCAGGTGAAAGGCCATCTGGCTCTTAGACGAATG
          CACAAGGGGCTTAGGTTAGATGATAGGCGGCTGAGACGCTTGCAGGTTTTTCTTTGTTCC
          CCAGTGAGGGTTAGCGTCGATGAACGGTGAGCGTACAACTCGTCGCCCCTTATCCGAAAC
          AACACGAGGCGTAACCAAAACGAACAGCAGACGAGCGGTCCTACGACTATTAACCGCACT
          AACACGAGGCGTAGGTTAGAGAAATAATACGAGCGCAACACACCGTTAAGTTCCCGGCTG
          GCAAAGCGGATCACACTAGGTAGCCGTCCCGCAGGAACCAGATACATTTAACCTTCCACG

          GTACAAATAGTACGTATGCGTGCGGCAAGTTGGTACAGAGTGGTACGCAACCTGTCCACC
          GCACAAATCATACGTTAACGTACGATTAGTCGGTATCGGGTGATAAACAATTTGTTCGCG
          GCACAAGTCGTACAATTGCGTATAGCAACTTGATAAAGGGTGATTCGCAATCTGTTCGTT
          GTTAAGACCGTACATTTGCGCTTGGTGAGCTGATACAGGCTGACGCGTCGCTTGTTTGAC
          GTGCAAATCATACGCTTGCGCCAGGCGTGTCAACACGGGTTGCTACTAGATTTGTTTGAC
          GTGTGAAAAATATGTCTGAGCAGAGTATGTAGGTGCAGGGCCTCGCGTCCTGTGTTAGTT
          AGACAGCAGGCCCGCGTTAGAACCGGACGTCGGTGGGGAGCGACACGCGATATCTCCATC
          GGCATGCGGATATAATGGCGATCGTTTTCCAAGCACAGGCCAGTATTATTGGTGTTAGTT

          ATTCCTTACTCAACCAGTTCGCAGATCCGGCCGACGGTAATTGGGGAACTCGTATCCACT
          TTTCTCAACCTACCCAGTCCGTAGGCCTGGTCATCCGCCGATAGAGAACCCGCACTCCCT
          GTTGTTAACATACCCAGCCCGTTGACCCGGCAGTCAGTCGCTGCAGAACCCGCATTCTTC
          TATACTAACTTAGCCAGTGAGCAGACCCGGCCACCCGCTCCTGGGCGAGTCGCATTTTCT
          TTCCCTAACTTATTCGGCTTGACGATTTGGGCGCCAGCCATAAGGGAGGTCGCGTCTACA
          TTTCCTGGCTTCGCAGGTGCGTGAACCAAGTTGTCAGCTACCGGAGGCGAGACTCTCCAA
          TCTAGTAGTCCAACTTCCATGGACACCCCATTACAGGCTAATGTGCGCGCAACCTTCAAT
          TCCCATGATGTCAGTCCCTTAGGAAAGCCACCGCATGTGAACACAAACACTATCCTACCC

          ATCATTGTCTGGCCACATGGTAGATCTCAAACTCCCGACG
          GCCTTGATCTAACTTCATCGTAGATCCCGTACCTCCATCG
          ATCCTCATCTGGCCTTATGGTAGCTAGCAAAGCCACGACA
          ATTCTGATGTTGCATTTTGGTAAATCTCGAGCTAGGACTA
          TCCTTGAATCTGTCTCATAATAGGTCATTTTTTTACATCT
          ATGCTAGATTGGCCTGAAACAGGCTCTCGGAGATAGACAA
          ACGTTGAAATAGTCTGAAGCCTGGTTCGATAACCAGACTC
          ATCAACAGGGAGCTCACAAGCGTACTCAGAGTTTGATCCC

