 8 1000
t1        TGTTGATGATCGTTCCAAACCGAACCCGTTTTTATTTTCTTGTGGGGTACCGCAGTACTC
t2        CTCCATGAATTGCTTGGTGTAACACTTGCTTCCCTCGCCTCGTTGGTTGCCATCGAACCT
t3        ACTGGAAAATCGAAACAAGGGGGAATCCCTCTGCCCTGCTCGTTGAGTGTGCTCATACCT
t4        ATTGTGGCCCCTTGCTAAAGTTAGGCCGATCGTCTTTCGGCGTGGGATCTTACTTGACCA
t5        ATCCGAATATCACATCCAGGTGCGGTTGGCTCGTCAAGATAACCTAGCATACCAGTACCG
t6        GCTAGCTGATTGCGCCACGGCGGACCTTGCCTCTCAGTCCAATTGAACGAAAACAAACTG
t7        AAAGCAAGCTTCCGGGGCAATGGGCCCGTCCGCACCCTTACGATACCCATCCCCATATAG
t8        GACAGGATCCCTCGGGGCGGTAGGCCCGTCAAAATTTTTGCGTTGACAGCCCTTGTATAG

          TACGTTAAGCCTTCCCTCTCGGCAGGGGCAGTAGTGTGGTCAGCTCAACAGACGTTGAGC
          TGTCTTCCAAAGCGCTGTCTGCTGACTCCAGCTGTAAAGGAATCGGTACTACCACTACCG
          CACCTGGTGTGACGCTCTCAGGTATCGTCAACCGCACCATCAACGCTTCCGATCAGCAAT
          GCCCCGACGTTTATTCATCCCGAAATGACAATTACGAGGAAAACTGAAGTCGATCGCCGC
          AGCCATGTATATTTCCTTAGATCAGATATTATAGTGGCGACAACCATGGGGCGTTTTGAT
          ACTCAACTGTGATGTACAAACAAGGGACTAATCGCGGTTCAAATCGTGCGCCTGTTCTGT
          GTTGGGTTCCACTGAGCCATAACCGGGGTAAACAGCCATCCATTCGCCGTTGCCAGCGGC
          GTCCAGGCGTACAGAGCTAACACCTGGGTGAACGAGCCATCGTTCGTCCTTGATAGCGGC

          CGCTCAGGTTCTATGCATGCCGACCGTCTAAACGTATAGACTGATTTTTTGACCGAAGTG
          TCGTTTGTTTTTCAATTCGTCGAACGCATAGCAGACAGACATAACTTCTAGCGCGTCGAA
          CAATCAGGTTTTGAGATTACCGGTCGCCTCGACACTCGCGGTCATTATGTGTGAAGGGTG
          TCATAATACTCTGTGCTCGACCAACGTTGGGCTCGTTGAATTCACATACTATGTGGCCCG
          TCGTGTAGAAGCTAAGTTGAATATGGTGCTACTACATGATGTGAAGCTATGAGTACGTTG
          ACACAAGGCTACGTATTCCCTTGTTGCCCCATTGAGTAACAGTGCTCTTCGATATTGCAG
          GCGGACCACACTAGTCCGACCTTTGAGTTTACTGCGTCGCTCACTTCCCCCGGCCCTCGT
          TTGGACAGCACTATTTCGACTTTAGTCCTTACCATGCTGCGTAATTAACTCGGCTACTCA

          GGGGAATCCTCCAGTCGATGCTTATCCGGGATGGGACTTCATACAGTTGCGCCCTGTGCG
          GTGGAATTTCACGGACTATAACGTCGAGAGACCAAATCTTGTATAACTATGCAGTGTGGG
          AAGGCGGTCCGAGAACCGTGAAAGCTAGCACCACGATCCCTTATAGCTAAGCGGAGTAGT
          TGAGAGCCTTCCTGCCCTTTTGTGCCAGGAAGGTGCAGGCGCCACTCTATGATCCGCGGA
          GAGGCGCTTCGCCGATCTGTCCTACTAAACAATGTTTGCCTCTAAAATGATGCGGGCAAA
          GAATTATCCTGTGGGATTTAGTCACGAAGTGTACCGCGCCTTACTGTTAGCGTCAACGGA
          AGTGCTTTTTGTCGTGTCCTGACGCTGGAGACACAAAAATACCTTAGCATGCACCCCCGA
          GGAACATCCTTACGCGTTGCAATGTTGGAGACACCAAGTGGTCTCAGCTCCCGCTCCACA

          GAGAGCAGGACCTGGACTCATAGAGCTATCCGAGTGCAAGAAGAGTGCGTGGGTGTTGTC
          ATGGCGTGAGGTCAGTCCAAACTAATTTTAGCATTTCTAGAAGCGTGCACATCTTACGTG
          GCTGGTAGGTCTAGGCTTTCGTGGTTCGCTAGGGTGTCCGCGGACCCTGTTATTATGGAC
          AGTGTCTGGTCTTGATCTCGAACACTGAGTTAGAGATTAACGAGGCCCGGGATCGTACAT
          TGGGTTATGTTCTATCTCTGAGGTTACGTCCAATAGGTGGGATTGTATCCTAGAGAAGCC
          CTGGGCTAGCACCAGCCTTTAAGGAATGGTAGGATCACAGAGCCGTTATGGAGAACAGTT
          TAGACTCACCTTTGATCCGGAAAATATGTTTGTTTAATCGGGGCCCCCGGCGATGCAGTG
          TTATCTCTAGTCTGCCCCATAAAGAGCCCTTAGCCCGTTCGGGATAACGACGCTACGGTT

          TCACTCTATCTGCAATTCTGGCTTCCATTCGCCTAGTAACCACCACGCGACCCTGTTCAC
          CAGGCCTGCGCGTCAAGTAGGCATATATGCTTCCACCACCAGCTTCAAGCGCGTGCTCAC
          ACAACATCTTTATTTGGCCACTCCATCCTCTTCAATCCCAAACGACAAGAACGCAACTCT
          TAACACCCGTAGCAGCACCAGGCAACGATGACGTATTTCCGCTTGTACGCACAAAGTTAG
          ATGTTTCCAGTGGGATGTCGCTCCATATCCAGCAGGGTGTGACTACGTAGCCGATTACCA
          CCAGTCACCATAACGTATCACACCCCAGTGAGATGGATGCGACTGTACGGGAGGGTTTCT
          CTATAACATTCGAAGTGTCCCGAGGGTCTCAATCTGATATGCCGAGATCCGGAGGTTTCG
          TCGAAACGCCCAAAGTGATGGAGTGCACCCATACCCTTATTAGGATATCTGGAGGAATCG

          CGCATCTACCGCTAGCAAATTGCATGGTGATGCACGACAGCCGGCCGGATCCAATACACA
          TGCGTGCTTCGCTAAAACGTCCCACTGCTATGGAATCAGGTTGTCGGTCTTGAACGAGTG
          ATCACAACTTAATGGCGGACCGAACCGTAAAAAAGACAGAATACTGGGACAGCAAAAGCG
          TTTATTCCCTAAATCAGGGGCACACCGTCGAGAAGGGAGGACACAGGAGCTATGCAGTTC
          AATAACTCCCAGTCAGACCAAGGGACTTGGCGACGTGCAACGATACGGTCACTGATTAAC
          AGAAGGCCTCACCCGGGGCACGAGTCGCGGTGGGGTGCAGTCGTCTAGATGCTAACGGGA
          GGGGTAATAGATCCCGAGGTTGTTATGCGACGCTGAATAGTTATCGAGCTCAATTCGCCT
          CGGAGGACAAAACTAGAAACTGCTCTGTGGCATTGAGCGGTCATTGGATTCGTTTCGTTT

          CGATTTCTGCAAGCCCTCTGGATAAAAGCTTTACTTCCTTCCCACGGGCTCATCTAGTAC
          CACGAATCGCAAATTGACTTGATAAGGACTACAGCCTCTAGATCAAAAGGAGTGTACCAG
          GGTGCATCGATTACTTGCACCTTAGGGGACCTTACCGCTCCAAATTCGGGCGTCTTGTGT
          TACGGGCTACACAGTCCCCTAGCATACAACCCATCTGCCCCGCGCGGGCGTGCGAGTGAC
          CGCAACTGTTCATTTGTCGCAGTCTGCACCGTTCATCCTTCTCTCAGATACGCCGCTCGC
          GTCGTTCTGCGCCACGCTTTTATCGAGACCTCCTATCGTTCACTTGGGGCTATATCCTAC
          CAGCTTATTGATCAAGCGTCACACTGGACAAGTTCTAAATTTGCGGTAGGAGTGGCCCTC
          CTGCTTCCGGAAATCGTCTTATGCTGGACTAATCCTCGAACTCAGGTCAGAACGGTCACT

          GGCTGTTTGACCCGAATTTTCGTCCATTTTGGAATTAGGGATACGGGCTCGCTGTTCCGT
          GCCCAAAAATCTCAGATGATTACCCATTGTGCAAGTGTGAACCTAAAATTGCAGTGCAGG
          ACCCGTTGGTGTCAAGACATCACTGGCTTTACAAACGCTGAGCCGCGCTCGCGGTACGCA
          CCTCGTACTTTTCGAGAACGTCTTAAATCTGTGGATCCGAGCTGATCGTTGCATTGAGGC
          GCTTACTCGGATCACGCCACCACCCTCCTAGCACGTGAAGTCGCGGAACAGGAACATGCG
          GGTAGTACAGCTTAGTGCGTCAATTTCGTAGAACATGAGGCAGAAGCGGAGAATCGAAGA
          GTCTGCCAGTACCGTACTCCCAAATGTTGTGCTTAGATAGCACAAGATCCCCGGTACAAG
          CCCCGCGGGGGCAGTATTTTTAACTGCTCTGCGCTTTTGGCTCCAGCCCCTTTGCACAGG

          GTAGCTTTAAACGGGGACCTAAGATGTCGCCCTGACCGACTGCCGTTAACATTGGTCATT
          CCGGTCTGGCAAGGTGGCTCGCCGTTGTATCCCAAGCGGTGGCCAATAAGAGCTACTGAC
          CTAGCCCTAAATTACTAATTGGAGTTTTGTCCTCATCGGTCGAAAACAATGGACCTGGGC
          TTAGCACCAATGACAGTCCAGCGGCCAACTCCGGATCGATCACCGATGGCGGTCTTTGCT
          ACCGAAGCGATTAGGGACCCGCGGTTCCGTATGACACTTTACGCGGACTAGGCTACTTTT
          CCGGCTATGGTTGACGCTTCATGCTTACATGTTAACAAATTCGCGACAAGGTCACTATAC
          CTAGCTCCTAACACGCCACATACGTTGTGTACAGCATCATTTCCAGGGCCGGTCATGATC
          TTAGCTTCTCACCGAGCGCAAACACGATACCGGGGATTGGCCCTGTGGCGATTCAATGTC

          GCGAGAGCTTTCAACGCGTTCGCCAGTCACCACATAGCGCAACATCACACGCGCAGGTTA
          GTACAAACATTAAGACCACGCGCTGATCGCTGCAGGGAGCAACTCCCCCAGCCCCGATCC
          TCGTGGTTGACACGATCACTTCCTTGTAATTACGCAATACAATGGTAACAGTCATGACTC
          ACGCTGGCCCCCAGCATTTGTTCTGCCCATTAATACGAGAATCAGTAACAGCTAAGACCT
          ACGAGGGTGACAGCACGTCGGCGGGGTTAGCTCCTAGCGTAATGGTAAGCACGTCGACTC
          GCACGAACTTCTGTAGCATTGAGGACCCCACTTGTAGTGCAGTCGTATGAACTCGCGAAG
          GCATAACCTTAGCGCATGTTAGTCTGCCGTCTAAGTCGACAAGCGGAGCTTTGTCGCCGG
          GTACACCGAAAGAGCTGGTGACTTTCCCGTTCGAGTAGAAAACTCGGACTTCGCAGCCGC

          GTGTGGTGATTGGGTGTCGCACCCTTGCTTTAGATACTTGTGTTTGCTCAGATGATCTAT
          GTGGGGCCTCCCTACGCCCGTCTTTCGCCCTTTGCTTTAGAGACTGTCTCAGCATTCCGG
          CTAAGGTATTTGATCATAATTCTCGCGTGTTTTCGTTTGTTGTGCTTTAGGGTGATCCGG
          TAGGGATGCCCGGATAACAATCTCGCACAGTCTCAATCGGGGCCCATTTAATAGTCAAAA
          GATGGGTGACTACGCGTAAATCATAAACGCCGGTAGCTTGGGGTTATACCAACGCGCCAG
          GAGAGACGAGTTTGCGAACATAACACGTCTCTCGTCTCAGGGCTCAGTTGAGCTGATGAA
          GACGGTCGCCCCTGCAAGGTTTCGCTGTACTACACACTACGATGCGGTCATGTGAACAAC
          GACGGTCGCTCGTGTCAAGTCCCCTTGCATTCCATAATACTAAGCAGACAGTAGTTACGC

          TGCACTTCGAACTCCATTTGCACTTGGAATTTGACTCTCGATGCTTCCTGGCTATTTAGT
          TTCCCACCTAGCTGAGATTCCATCAAGAGAACACCTTGCGGAATTCCCTAAAATAACAAC
          TGTCCTTCGGGGTTCAACTCTGACAGAAGGCAATTTACAGCGATTACCCGCCCTCTAGGC
          GGCTCAATGGGGTTAACACATAATAGAAAAGTGCGTTATTCGAGTGCGAAACATCACTGC
          TCTCTACCGATACTGATCCGCGTTAGAAGGGGGGTCTCGGTGTTTATGAGGCGCTCCTAC
          TCTCCTCTGGGATTATTGCTCTTTCGGAGGAAATTCGTGGCACTCATAAGGGATTTGTAT
          TCTCTATTGATTACGGTGGGAGTTCCACAGCTGGCCCGGCGCACTGCACCTTAACAGCGT
          TCTCTGCAAATAACGGTAGGCATCAAAGCGCTATTCAGCCTTGCTGAGGCTTAACGTCGT

          CGGTGAATGGTAAATTCCTTTCTAGAAGTGTCGCAGATTTGGCACCTAATCTAGCCATGC
          ATGGTGATGGGAGACTCTCATTGGATGTGGTCGTCATCCCCGCACCTAACCTCGCATCAC
          TGGCGGATGGTTGGAACTCAGCAAGTAGGGCAGTCATGCAGTTGCAAGATTCGGTAGTAC
          CGTACGAACATGTATGCACACCGAGATGGGCGGCTTATTCTGACCCTACTTGTCGACAGA
          TACCCCGTGATGCTAATCCAATACTCGGTGCACCACTTACAACACTCTGCTTCGCACTGA
          AGACGTCGAGGGCGCCCATAAAGTGATGGGCGGCGTCCGTCTCGTCCAGTTTTTTATAGG
          CGAGGCATAGTCTGCCCTCAGCGGAAATCTCGGAGTGTACCGCGCGTAACAGGGAGTCGT
          AGACCTACAGCTCACAACTAGCGAAAACCGAGGTGTGTCTCGCGCGTAATCGCGGGATGC

          TCGAAGCCAGAGACTGCGCCTGATGCCCCGCCCAGTTATTTGAGGACCCGTAGCAGACAA
          CTAAAACCGGAGGCAGCGCTTAGCCTACATACGAGCAGTCTGAGGTTAAGTGGCAGAATA
          CTGAAATTGGAGGCCGCGATTGTCACTTCCTCACGCAGTCTAATCCCGGGTGTTCGGGAG
          TCAGAAGCGGAAGAGTTGGCTAACTTCCTTCCACATTGTTGAAAAACCTGTCGAAGAGAT
          ATGTAGAAGGAGGCTTAGACAGGCCCGTGGTGAGACCTGTCCGTGAATAATTTAGGTAAG
          GCGCTGGGGTAATTTTTGACCAGCCCGAATCTAGGGTGTCCAAAAAGTACACGCGGTGAG
          CCCTGTGTAGCGTAATAAAGTGTATAGGAGCCTCGTGATGTGAGGCATACTTGCGGGGAA
          CATCGAGAGACGCATTCAAATGTGTAAGGGTCTTGTGACACGAAGGATCGTCCCCGAGAA

          TCCAACCCGGTCTCTTAGAAGCCCCATCATTGTCTTTGTGCCCTCTCGTTGCGGAGATAC
          GCCCATCACACGCTGCATATGTCACCTCGTAGTTATTGAGCGCCCAGGTTCCCGCAGGGT
          AAGGGGTACGCAACGCCAGGAAGCTGCCGCAGTGAGTGTACGCCGTCATAATCAATTGAT
          TGGTATGGTATACCGTTGTGATGCGTCTCCTAATATAGAGGCTCTCTGTATTGCTGAAGT
          CCACCTTACCCAGATCGGGGACAGTCCGATTAGCACCGCTTTTTCTGCTACTGTTACATT
          TCGCGCCGTGTGATTTTGGGATGTCTCGAATGGGACAGTCAGTTCCCACTAACATATGGC
          AGGCTCCGTCGACCGTGCCGGCCATTTGTTTGGTACTATGAGCGAGGCCTTCATAGCGCA
          AAGTTCATTGTATTTTGTCGGTCATTCGTTCGGTGCCGTGAATGCGGCCTTCGAAACAGA

          GCATGACATCGTACATACGTGTCACATCGCTCGCTCTCCC
          AATCGGTACGATTAGAATCTTGTATAGTCCACACTTTGTA
          CGTCAATCTCCCACAAGCTAAGCACGACCTACGTCCTAGC
          GGTGGAAACGCGACCAATAGTGAACGCACCGGCCAGCATC
          AACTTAGTTGTAGCGACAGACACCCGATGGACACATTGAA
          GTTCTATTAAAAACGCTGACAAGGCGCCGCGAGTGATGCA
          GCTTCTTAGGTATCGTCCGTTGCACCGAACGGTAGATTTG
          GCTTCCCGCGCGCCGCCCGTCGCTCCACACGGTGGGCATA

