 8 1000
t1        CTTGCCTCCTTAGATCTTTGGCCGGCCCTGCGCCGACAATTGATATCGAAATCCTTGCTG
t2        CTTGGCTCTTGAGCCTTTTGATTACCCCTTCGTGGGCAATCAACACCGAAGTTCTAGCGG
t3        ATCTGACGTTGAACTTGTGACGCGTCGGGGCACTGCCGGCTGATAATTAGACCTGTATTT
t4        GTAAGATTATGAACTAATGAATCGTCGGCTCATAGCTGGCTGATGAGTGGAACAGCACTT
t5        TTCTTCCGGAGAGCCCCCGAATCGATTGCCTGTTGAAGGCACAACAAAGTAAAGTGGCGA
t6        GCTATCCGGAAAAGTTACGATTTGATCATCTGAGGAAGGCTTCGCGTATTATCTGAGCGA
t7        TTCATGCGGTGAGTTATCGGATAGATTGCGACTAGGTTGCGTTACGCAGTAAATGAGAGA
t8        CCCATATAGAGAGTTATCAAATGGGTTGTGACTCGAAGGTGTTCCGCAAAGCATGAGCGC

          AATTTGATCTATAATCTTTGGTCCTCGCGTTTGCTAACCAAGGTATACAGGAGGCACGGT
          AGTATGATCCACTATTTTTGGTCTTAGTAATGATAGTCTACGTTATATCATGGATCCGCT
          GGGCCGTTCAATTGTGCTACTTCCCGGTAAGAATTGCCTAATCTAGGCTAGGGTCTTAAG
          GTGTCGTTCACTTGCCCTTATTACTGGTAAGAATTACCTCACCTATGCGAGGGTAGCAAA
          GGTGTGTTCATTCGTTCATAAACTGGTCAGGGGCAATTATAAACGTGAGACAAAGGAGGG
          GACGTGTTCTTTTGTTTACGACACCTTTAGGAGCGATTGTAAGTAAGATGCAAGGGAGGC
          AACATGCCCATCCGAATAAGACCTATTCTGGAATTATAGTAGGTGTGCAACGGATGCGCC
          AGTGTGCTCTTTCAAGTAAGGACTATTCTAAAACAACATTAAATGAGAAACAGGTGCGGC

          GAGGCTCACAAACTGGGCGCTCGGTCTGTTGAGCCATGCCTTATAGATGGGATATCTGGC
          TAGGTCGACGATCAGGGCCTCCGCTTCACGGCGGTATGTTATTCCGATATGACAGTATGC
          GTTGTTGACAGACTAACATCTTGGTCACCCCAGCTTTCCCGCGCTGGGCGGAAATCTTGG
          GTTGTGGACAGAATAATCTTTTCGCTACCAATGACCTGCCGCCCTGCGAGGTTCTACTTG
          AATAACTAGAGCAAATGTCTACCATCGTCCACTACTTCTTTCTCTATAATGACCTCATAC
          AAAAGCTAGAGGTGATGCTCATCATAGCCCACCACTTATGTCTCCGCAATGACCTCCCAC
          TAACCATAGACGTCGAGTCTACCATCGCAACTAACCTATACCATTAAAACGATCCCTAGT
          TCTATTCAGAGCTCAAGTCTGCCATCGTATTCCACTTGTTCTTCCAAAATGATCTTTCGC

          GGTTGTCGTGGTGGGGATTAGTACTCGAGTTGACAGCACGTGTGTTTTAAGTAAGAGTGC
          GATTACTGTGTCGGGGACTGGCGTCGGCGTTAATAGTACGATGGGCTCCATTCTAGGCGG
          GGATTAACTGGCGAGGAAACCTCGAGAAGCCAGCGCCGAACGCGGGTCTGGTTGTTGTTA
          GGATTACCTGGTAAGGGAACTCAAAGAAGCGCGCATCGAACGCGGGTCAGATAACTCCTG
          TGCCGAACGGATGACTTATTCGTAGGAGGGTGAATGTAAGGACCGGTCGGCGTGGTACAG
          AACCTAGAGAATACTGGTGTCAAATGAAGGTGGGTGTGGGAACCGGTCGATGTGCAATAT
          TAACTACTGGTTGGTCCCTATAAAGGCACTTTAACGCAAGCACTGGGCCAGGCACAATGG
          CAACCACTCGGCGATTGGTACATCGGGCGTCGAACGTAGGGGCCGGTCCAGGCGTCATGG

          CCTGAGAAGTTTCCGGTGTCACTCTGCTTTTCTAAGACGCCACGTAACAACAACAGTTCA
          CCTGTACAATTGTCGGTGTTAGATTGTTTTCATTCGCTTTCTTGTAGGCTCAACAGTTCA
          TCACTGTCAGTTCTACTGACATAGAGCCCTTGGCTACCCTAGCCCACGTCCCACCGCCGC
          TCTCTGTCACTCCTATTGTCCTGGAATCCTTGGCAGCCCCAGTCCATGAATCGCCGTTGT
          CTTTAAGCACCCTCGCAGCATCATAGCCTCACTTATGCTTGACTACTGCCGAGGAGTTGT
          CTTTCCGCATACCCATGGCCTAGTAAATTCTTTTTTGCTTTCTCAATTCCAGAAAGTCGT
          CTCTCAGCATATCCGGAGTATTGCGGATTCTCCCACGCCGTGTCAACGCCCGAAAGTAGC
          TATCTAGCATACCCAGAGCTTCGCGGATTCTTCTGTGTCGTACTAAGGCCGGGAAGTAGT

          GTGACTCGAAAGATTATTGGACAATGCCTAGCACTGGCCGCAACAGAGACCGTGATCGGC
          GCGAAACGAAAAGTTACAGGATAATGCCGAACATTGGAAACGAAAGAGATTGTGACTGAT
          GGGACTCGCTCGACAATTAGCTGATGTAGTCCCCCCGCCGCTAAAAGGAACCTCGTTGGC
          AAGACTAGCTCCATTACCAACTAAAGTCGTCCCCCGGTCGTCACACGGATTTCTGTCGGC
          GAGGCCGGAATGGTGTATGGCCACCATCGAACTTTTTCTAGTCCCATGTACACCACCGAC
          GGGGTCGGATCGGATTGCGATTACCGGCAAATATTATCTAGCCCACTGTACACCACCGTC
          GTGGCCCACTCGGTATCTGAGCACTATTGAACATTAGGGTGCACGCTATCCAGCTCTGAT
          TTGGTCTAGTGAGTACCCGTGTACTGCCGAGCATCACCTTGCGTGCTGTTCGACCCTGTC

          CCGAACAGGCCAATGGATGTATCTGCTCCCTACACTTGTCTCTAGCCTGTGGCAATAGGG
          CTCCGAATCCGGAGGATGACGTCCGCGTCCCACACCCATTTCTAGTTCGCGACGCCAAGG
          CTCAAAGTATGCGCCCCGCTTCGCGAGACTATAACGTATTCTGCACCTTCAGCGAGGCTG
          TTAACAATAAGTACTCCGTTTCCCGAGTCTACCACGGGTTAAGTGGTCCTAGCACATATC
          TTAGGCCTGACGTCCATTTCCCCTGTGAAGTATAGTCTCATCCCGCATTAGTTGCACTAT
          CTAGACTTGATGTCCATTTCCCCCGTGCGGTCCATTCCCATTCTGAACTAGTCGCATTGC
          CCATACCTGCTGCGTCTTCCATTCAGGTGGTATAGTCCCACCCTGCGTTAGAAGTACTGT
          CCATTCTTGATGCCCCTCTTCTTCGGGCAGCACAGTCCTACCCTGAAGTGCACGCCTTGC

          CGTACGCTCGTGTTCCAAGACAGTCAACAAACTATAGGGGTTAACCCCTGTTGGGGATCT
          GGTACGCCCCCATCTCACGCATGCTAAAAAACCGCGGGACACAACAGCTGTTTGGAGACA
          CGTCTCATTCCGAAGCCCAGAAGTCTACATGACAACTGCGGTTACTACTACCCGGCAGCG
          CGTCTCATACCGAAACCCAGATGTCCTCGCAGCGACTTCGGTGATTACTATCCGGCAACA
          TCCGTTGTTAAACTGTCTGTGGGCTGATTTGCTACCCGAGCGAGACACCATGCTGCTCCT
          CTCGTTGTTCAACCATACGATAACTGAAACGTCACTCGAGCGCGACAATATGCCGTGCTT
          CCCACGGCCAAACTCTCTAAGGACGGCTACACCACATGAGCGAGCCGCCATGCCGCTCCA
          CTAATAGTCCAACCCCCCGTGAACCGCTACGCCATATGGGGGAGCCGCTATACCGCTTTG

          ATAAGTCATATGACCCGCACCTCTCACTAGTCGGTCAAAGATCGGATTGGTTGCCACGTT
          CGCGGTTACACAATTCGTACGTCAATTCTGAGAGGTAAAGAAGGGGCTAAGTGCGTCATT
          AATAGTTGCTCCAATTCCCCGAACACATTAAGCGACCGAGAAACGGCCTGCCGACCTGCA
          AACAATAGCCCCAGTTCCCCGATCATATTAAGCGACTAGTAAACGGCTCGCCAACGGGCA
          GCCGTCTGCCCTATCACTGAGATGACACCAGTGGGTAAGCCGACAGGCGCTCACAGCCTG
          GCTGTTTGTTCCAACATTGGGATGCTTGCACTAAGCGAGCCGGTGAGAGTCAACACCCCG
          GCTGCCTTTTTAATTACCGACAAGATAGAACTAGACGAGATGGCGCGGATTCCTCCCACT
          GTAGCGCATTCAACTATTGAGACGACATAGTGGGACGAGCTAGCGCGCGTTCTTCTTACA

          GTGAGTCGTGCGCGAAAACTCCGTTCCATAACAAGACACCGATTATACGAGGTCTATCGG
          GCGAGTTACGTGCGAAAAATACGTACCATACAAGAAGAGTGGCTATAGGATGCCCGTTAG
          GGCAGACCTCAAGGGGGCCGCAAAGGGACGATTGAAGCAGGCCTATCCCGGCTTGGTGGG
          GGCTGACGCCGAGGGTGCTGATGTGGTGTTACCGGTATAGAGTTGTAACGGCTAGGCGGG
          GGAAGCACCCTGACAGAGAGTTTGAATGCCATATCGAACGGCTTGTTTTAACAGGACAAG
          GGATGTACCCTGTCATAGGGAAGGAATGCCGCTCCAAACGGCCATTTTCAACAGACCAAG
          CGAGGCACACCGACATAGGGTAAAGAAGTCGTCTGGAATGCCCTCTTCCCCATGGATCAA
          GGAGGCAGACCGATATAGGATAAGAATGTTGTCAGGAATGGCTTCCTCCACTCATATTAA

          CTGTTCATCAGCACTAAGCACTATGGATGCGCATTGACTGGTAAGTCGGCAGGCTGAATG
          CTAAGTATCGGCTTATCGGGTTACTGAAGGGAATGGGTTGGTAAGGCGTTAGGTTGGTCC
          TGACTGGCGTCGGCCACGGCTCGCAAACGGGCCTGGCGTCATAGCCCGCTCCCACGCCCT
          TACTCTCCGACTTATCCGACTAGCTCGAGCGCCCGGTGTCAATGGCCCCCCTAGAGCCCT
          CTCCTCATCAGAAAAAAATTTCAAGTGGCTCCTGATTATGCGGAGGGACCATGCCTATCT
          CTCATCACTAAAAAAAGATTTATCATAACTCGCGATCATGTGGGCGCATCTTATTTATCT
          CTCCTTGCCAAAACAATACTGCATGTAGCCCACTACCATGCGGGCGTCACTTGTGTACAT
          CTACTTGCTAGAGAAATACCTCATGTAGCTTACAGTTATGCGGAAGTGTTCTGTTCGCTT

          CCGCATCGTTAGGGGAACAACCTCAGAGGCACGGCAGCCAACCGAGCCCGTATCCCTTTG
          CTGTACAGTTAGTACAACCAGATGCGCGACATGGCACAGCGTCGAACTTGCTACACCTTG
          CAACCCCAACACGAGGGAATATACAGGACCTCGGTAGTTGCATGCATTTGCTTCGCCTTG
          TAACCCCGTCGCGAGAGGGAATGCGAGGTTATGGTAGTTGTCAACATTTGCCATTTCTTT
          GTGGCCTCATCGGGAAAAATTCCCTGGGGACCGGTGGTGACGCGACCCTACTGCATTCGA
          GCGGTCTTCTCTAGGGAATTTTTCGAAGGACTGGTGGTAATACGCCCCTACTTTACTTGG
          GCAGTCTCAACGCGAGCCAGGCTTGGGGGACTGATAACGATATGTCCCTAATGCGTTCGG
          GAGGCCTCCACGTAAGGAATGCTGGGGGGACTGGCAGTAACATGTCCCTGCTGCGCTCGG

          ATTGGTCGAAAATATAAGAAATGTTCAAACATACACCGCACCCGGCAGAACGTAGCCCAT
          ACTGGCGTTTAGTATAAAAACTGTTTACAGCTGAGCCATGCCAGACAAGCTGGTGATCCG
          TCTAGTCTTAGGCATGGTCCCAACGCGTGGGATAATCCCACACAACAGCATTCAGAGCTA
          TGTAATTTTTAACTTGATGATGATTCATGAGGTACTTATATAAGACGGACTTCAGGGTCG
          CGTTATCGGCACTTTATATGATAACGTCTACGGACCCACTTCCACCTAGCGGGGGAACCC
          CGTTACCTTCACTCTGTGTGATAACGTTTGCGGGACGACACTCAGCCAGCTTGAGAGCCC
          CGTTGTTCACGCTGTGACCGAAAACGCTCACGGAGCTCAGATCGGCTTGCTGGAAAACGT
          CGTTATTTTCACTGCGGCCGATAACGATTACGGAAACTCAACCAGCTCTCTGTAAAACGT

          ACTGAACTGTCTTCGAGTATCTGTGCCCAACCATAAACTGGGTTACTTCATTATACGAAT
          CTCGAATTACTAACGAGCATCAATGCCTACTCATAGCCCGGGCGACCACATCATACGATT
          GCAGGACCCTATCACAGAGTGTGCACATGATTGAAACATCGAAAATCCGAGTATGTGGCC
          GCGAGGTCCTTCCACGGGCTGCACCCACAATCATAACATCGCAAGTCCTAGTATGTGGCC
          AATAATCTCAGCACCCGAACCAAGATATCGTTTCCATGAAGGGGGTTTCAACTGTTAAAC
          CGCCATCTTAGCTCTCGTCCCACGGTACCATCTTCATGTGGGAGGCTAAACTTATTATTT
          GGTAACCCAAAGCCTAGATCCCCGGCATAATTGTTCCGTTGGTAGCGCGACCTGTGGCTT
          TGCTGCTCAAGCCCACGATGCCGGGCATAATTTTTTCACCGCTGACTGGACTCCCCGCTC

          AGGGAAGACACAAATTTGGTCTTGGCCATGGCCGTCGAGCTCTGCACTTCATACACCTTA
          GGGGGAACGACGACTTGCGCCTTGTTAGCGGCAGTAAAAATCCTTATTTTTTTTGATTCG
          CATGACTTTCCGCCAATTGCTCCGTCGCCAAGAACTGGATCCTTTAATTGTAACGGTTTA
          GCTGACTCCCTGACACTTGTCTCGCTGACAAGAATCGGCTCTTTTAATCCTAGCAACTTG
          ATGAGCCTTACGTTAACCATTCAATTAGAGGTCGCAATGCTCAGAGAGCTCTGCATCTTA
          ATGAGCTCTAGCTTACCCAACCTACCGTGGGTCGCTAAGCTTACGGAGTGTTGTATCTTA
          CCGAGCGCTGTCGTGTTCATCCTCTTATTGGTTGTTAAGTGGGTAGGACATTGCATCTCG
          AAGGGCGCCATTCTACATATTTTGCAGTCGGTCGTGAGGTGAGGAGACATCCATATTCAA

          GAGGATTACAGGTGGATCCCGGCCTTGGCTATGGTGGCGAGTAATATCAGCACGGAGAAG
          CCAGGTGTCACTGGGGCTCTGCTATTCGCGCTGGCGTCTTACATTCATATCCAACGTAGC
          TGCGAATCCCGCCGGGCATGGGGGATGATCACGGAAGCTAGTGACGCAAAGAAGGGCTGT
          TGTAGATATTGCGGAGCATGGGGATTTATCATGAAAACCAGTGACGCAATTTAGAGCCCT
          TCTCTCTCTTCGCAGGCAGTGTTTTTGGCCTTAGCGACGGGCCCGGAAGACGGGCGCTCT
          TCTGTATTTCCAAAGGTGGGGTTTTCGGCCTAAATAACGAGCCCGGAAGTACGACGCTCT
          CGTGGTTTGCAATGAAAAGCGTTTTGGGCATAAGGAATCAAGCTGGGAGGAAGGTGCTCT
          TGCGGCTAGCGTCAGGCAGTGTTTCGGACATCAGAGACCGGACAGAGAGATGGGTGCCTG

          GAAGGCTATTCAATCCGTCGTAAGACGGGAGTTGAAGGGC
          AGAGGTTATTCACTTCGGTATTGGGCGCATGTATGAGGGC
          AACGGCTGTTAAACGAACCACCGGACTAAAAATTAAACAA
          AGCGACTACTGAACGAACCAGCGGATTAAATATTATGTAT
          GCAGGCGCCGCACCGCCCCAGGATTAATCACACTCACTGG
          ACAGGCTTGGTGCCGTCCTAGGATTACCCACACTAAATGA
          GATCGACATGCAGCGTCCCCGGTCATTTAAATCCGAATGA
          CGTAGCTATGTACCGTTCCCAGTCACTTAGGATTGAATGA

