 8 1000
t1        GCGTTGAATTTACCCCGGGGTAATGGCAAGGTTCTCTTTTGGCAAACATTTTCTAGCGAT
t2        GCGTTGATTAGATCCCGAAGGATTGACGAGGCCCTATGTTACCTAACATTTTCTAGTGAT
t3        TTCTTAATTATACGCTGGGGAATCGACAGGGGCATAATCTCGTAGACGTCTTCTTGCTAT
t4        GATTTGTATGTACATTGAGGCTCGGATAGGCGTCCTGGATGGTCAATATATCTATTTCGT
t5        GTGTTGTTTCTAAATAAGAACGTTGATGAAAGTTCTGCGAGATTAGGTTCGTTAAGGTGC
t6        GTGCTGTATATATCTCAGGTTGTCGGCCGGGGTCATAATCAGGCCTTCTAATGAGGGTCT
t7        GCGTACTTTACTTGCAGAGAATCAGACCGTGCTCATATTCCTCTACTCTATTGTTGATAC
t8        GTTTCGGTCGCTAGCCGATACAACAGCAGGGAGTTCAGCCCGATGGGCTGCCCCAGATAG

          ATGACATAACGCGAAATAGGCGCCTGCCAGATAGATCTGGTTAACATGTACACCTCGCCA
          TTGGCATGACATAAAATAGGCGACTGCCAGATAGATTCAGTTTACCTGTAAACCTCTCCA
          ACGGAGTAGAGCGGAGCAGGCGACCACCAGGATGTGTAAATTGGCATGAAGAGCTACCTG
          ATGGAACACCGCGCCGTAGGCGGCCGGAACACAGGCCGAGTTCGCGTGAGGATATTTGTT
          ATGGGACTACGTAGCATAAGTACCAAACGCTAGGGTTGAGTCGCCGCGTAGATCTCGCTA
          ACCGGTCGGCGCCCCGAAGAAGACTGGCGCGAAGGTTGAGCTTTCATGGGGCGATTTACG
          ATACGAAATTGAAACGCAGGGACCATCACAGCAGTCCAAGATGCACGGATGACGATCCGA
          ACAGGCTACTGATCCACTGGAAATTGTCATTTAGTAGAATTTTGCTCACTTATATCGAGT

          CGCCGCCTGAACCATTTAGGTGTCAACAATCCGTTGGGCCGAGACACTGGCAACGCTATG
          CGCTGCTGGAACTATTTAGGTGTCAACAATCCGTCGCGCCGAGCTACTGGTAATATTGCG
          ACCCGCTTGATCTTATGGAGCGCCCCAAATCGATTGAGCTATAGTGCCAGCCTTATCACT
          TATCGCGGAAATTTCTGGGATACCAGTCATCGAACGTATTGTACTCTTGACAACGTCCCG
          TAAAGTCCGATCCTTTAGGGTGAATGGATTAGCTCGTGCGATGGCAGTAGCAGTCATCGT
          TGGAACTCGTGTCCGTGGGAGGACAAGAATCGGGTAAACTACAGTAGCGGCGTCTTTGGG
          ACGAGTTAAAGCCCCAGATGATTATAAGATGTTACCTAACGAACGTGTTACGTTACTTCG
          TCGGCCTATAACACCTAAGTTACTTTAGTGGTCCGATGCTGATGTCTGTGTCAGGGTTTG

          CACGTGTGGCACGGTCAAGGGAACGGCGAACCTAGCTTGTCGGGTGCGGGTCCCACAGCG
          GGCGCGTAGCATGGTCACGGGAACGAGGGACCTAGTTTCTCGGGTGTGGGTCCCATTGCG
          CGCACGTAATGTGATCACGAGACCATCAAACCCCGCCTGTCGGGTATGGCTGCTATAACA
          GGCGCGCAGTACGGTCACGAGTGAAAAAAAATACGGTTGTTGGGTGGTCACCCAATGATG
          TAGGCATGCCACGGGAGCGCGGCTCACACCCGAGCCCTATTTAGTGGGGATGTAGCGTCG
          TGCAAATGGTTACATGGCACGAATAAGAACCCAGCCTCGGCGACACGGGATCCAGTGGTG
          CAGTATCTAAGTACCCTTGTCACATAGAGTTTATGCCTGCCATGGTTTGGTCAAATGACA
          GATGCAGATAACATTCCAGTGGGAGGCGGTCGGTAGTTATTATTTTTTGTACTGATGAAA

          AAGGTTGCACACGCGAGAGTCGCACTCTGGGAGGCTTGTATTGCAACACGGGGGAAACTA
          TAGGTTGAACATGCGAGAATTGCATTTTGGAAGGTTGGCATTACAGGAAAGGGGGCGCCG
          AAGTTTGGGTACGCGGGACTAAACGTCCAGAAGGCTGGCGCCATAGGAAGGAGAGCAGTG
          ATGTCCATACACGACCGACCCGCCGCTTGAACGGGCATCAGTATTAGTATGGGTGTAGCG
          ATACTGGAGTTCATGAAATATGTCATCGTAGTGGTTCCTCCCTGCCGGAGAGAGACTATT
          ATTCCGACGCATACGAGCTTAGCTATTTATCTTGCTAAATATAGCAGGCGGACTGTGGCC
          TGTTTGAAGAACGACAAATTTGCTATCGCCTCCAATTATCTGGCATCGTTTGTCGAATTC
          TGCACGAAGTCCGGCGCACCGATTAGGATGTCTATCAGTTCCATCCAAGTGAGGATCACT

          AAGTGAAATGCGGTCGCATTGCACCCAATACATTATTATGTCAGGAGCGGCAGAACTCAC
          CAGAGGGCTACGGCCGAATGTCCCTAAATACATCGCTTTAGCAGGAGCGGCTGACTCAGC
          AAGACAGATGTTCTTGGATTTTTCCCGATATTAGGCGATGTCAAGTATAGCGGCTGACGT
          ACGAAAGCTCAAATTGGGTTTCGCCTAAACCATAACGATACTGACAGCTATGATATTTAC
          GAGATTGTCTAGCCCATGCCCAATCAAATATGAGCCGGCATTAACGACCATAGATGTGGT
          AACACGGCTCTGCTCAGACCTAACCCAAGACAGATCGCTATCTAGGACTACGAACCTCGC
          GGGGGAGATCGGCGAATAACAGGCCCAAAAAAAATCGATATCGAGGGGCACATTTTACCT
          AATGAAGGCCATTACATCCTTAGCTTCCCGAGGGTCGTTAAGAATGGAAAAAGGAGATAC

          GCTGGTGGCGACCTCACTATAATATGGAGCGAATCTCGTACGATCTAGCTCTGTCGCACG
          GCTTGTGGCCACTCCACCATGATAGGGAGCTAATCTCGTACGATACCACTTTGCCGGACG
          AGCGATAGCGACTTCCTCTGGAAAATGTGGACATTTCATACGACATAGCTTTGTTAATTG
          TTCTGCGCTGACCCCAGGATGGTAATAAGTTTGCTTTGCACGATACGGCACCGAGGCTCA
          CCTTGCCGTGTTTATCTTATATAGGTGCACTTGACTCACGCTGCGCAGTTGCGAGGAATC
          TCATCTGAAGCCTCTCGCAGGCAGGAGCATGCCCGACGCACAGCACCGGTTAAGCGCCCG
          TCACGGGACACGTTCTCCGTTGATGCGTTTATCATTGTAGCTGCACCGACTCGCTGTGAG
          CTTCACACTACTCATCCTATGCGGGTGCGTACGGTTGGAATCAAACAGCTCCCTTCAATG

          GTGTCGTACCTCTCCCTGTACGTATCCAAGACGTTGAATGCGAACATCTAATCGGGGCGT
          GCCCCGTACTTCTCCCTGTGAGCACTCAAGACGTTGAACGTGTATCCTCGATTGGGTTGT
          ACTACACATCCTTTGTTTGGCACATCCGATACGCAGAATGCGGCTATTCATTCGTGGAGT
          GTCGCTTTTGGCTCGTAAGATGTATCCAAGCCTCAGGGCACTACTATATTTTCATGGAAA
          ATGGTCCTTCCCTCGCCTAATGTAACTTAGCCCACGAACATCATGAGTCGTTCGGGGAAT
          GTAAGCGTTTAGCCGTCAGTTGTACCTTATCCGCCGGATTATCTAGCTCGTTCGCGAAAC
          TTCGTGCCTAATAGATCAGAAAGTAGTGAACGATTGTGAGCTATGTTGTTACACGACAAC
          TTATGCTGTGTTAATCTACAAGGTCCCTAGCGGTAGAAGGGCAACGCTATCATAGGCAGA

          TAGCGATTATCCGCTACCCTCGCTGATCGGAATTATCACGACAAGTAGAACGTAACATCC
          TGGCGATTATCGGCTACCTTCACTGCGCTTGATTTGAGTAAGAGGAAGAGAGTAACGTTC
          AATCGAGCCTAAACTACCTTCTCAGCCCCTAGCTATTTGAGAAAGTATCCCGTGCCCTTC
          TATCGGGTACCCTTTTTATCCACTTACTTACGCTTACACAAAGAGTCTCTCTAGACCCCC
          AACCAAGAATGAGGCCCCTTCACTGGCATCTGCTAGGTAGGAGAATCCCCAGGAATATTT
          CTTTGAGCCAGAGCGCTACATACGAACAGGTTCACAAGCTGAACGCTGCCCGGCACAATT
          TACGCAATATCTCTACTGTTCGTTTGCCCGCGTCTCCAGTGGAGGAAGGAAATAATATAG
          GACTCATCCCAGCCCTGGTGTGATCGTTCGTTCCGGCTTCATTAAATGAGCGCAAAGGTA

          TCGGTTATACTGATCCTCTCCGGGGGGCACACAACGATAGGCAATCCGCACAGATGAACG
          TCAGCCATACCGATACTCTAGGGGGGTCGCACAGCGACAGTCTAACTATACAGACGAACG
          TTGGTTATATAGACATTTCCTGGGGGCTGCACAGCAACGAGCTATTTCTTGAGACGAAGG
          TTGGTTACAGCGGGGTTACACAGAGACAGGACACTGTCCGACTGACCCTATCGGTGGGTG
          TTTGCCACGTTAACAGACCATTGGCCCTTTGAATCGGAGTACCGCTCCTGAACCCGTATG
          TATGTGTCGTTAATTAGCTATGGGGATTAAGCAACGCTATGCAGTCACGGCGGACGTACG
          ACGTGAGCCTCAGTATTTAACCAACCTAAATCAGCAACGTGCATAGACCGCAAAGGAACG
          ACCTCCGTAAGAGCATTCCAGAAAGATCGAATGGCAATCGATGATCTCGGTAGACGCAAA

          GAAGGGACAGGGCCAAATAGCTAGCGCAGTAGGGATTTAGCCATATCCAGGAGTGGCCGA
          GAGGGGACATAGATTATAAACGAGTGCAGCAGAGGTCCAGCCGTATCCAGGTGTGCCCGT
          AGAGGGAGCGAGCTAACGTAGAAACGCCGCGTAGACACAAGTTCACCTGAGCACGCCGGA
          GAGCGGGGTGGGGAAGGGAACAACTGCATATGGGATCTAGGACCACAAGGGCGCGCATCA
          GGAGGGCTCGGTCTAATGCAATCCTGCGGATGGGACCCGGACTGATGTTGGTGCGCCCCA
          TGCAGGAAAGGGCCAATGTGATTTTGCGGAAGGAGCTCTCGTAGATGCAGGCGGGCTTTA
          GGAAATAGGGAGCTGACATATAAGTATGAGAGTGATCTGGACTTGAGCGTGCACATCATA
          CGCAAGGGGGCAGTAATACGTCACTCTCATTCGATTTTGGACTAACGAGCGCGTGCCATA

          CCATGTCCGGTTCGTATAACTAGACACTCGGTTCTGCTGTCCAGAATGCCGTGATATACC
          AGATGTACGGCTCGTATAACTAGGCACATTGTTTTGTTGCCTAGAAAGCCGTGACATAGT
          TAATGGATGGTTCGCGCTACAAAACACTCGATCCTGCCTTCGAGTGAGACATGACAAGGT
          TGATGATCGTCTCCCACAGTTTATCATACGGTGTTGCCCTCGCGGGAGAAAAGATAGAGC
          AAATGCATTCTGGGTTAGATTACAGAGATGATCTCAACCCCCTAAGATACGTGGTAGACC
          ATCCGGACGTCAGGCAAAGCTCCACTCGCGGTCTTACCTCCCAGACAGACGCCTTCAAAG
          TAAGAAATGTCAGGCGGATGATCAAAAGTTACACTGAAGGGGTTTTAACTGCGGTGCAGT
          CAACAACGATCTTACGTACACCAGGGTGTAGTCGCTCTTCTTTCTTGGTCGGGATCAGGA

          TACATGATTCCACTTCCAGATTCGTAGATCCTTATTTTCATCCTCTTCTCCCACACACTA
          TTTATGACTCTACTTCCAGGTCAGTTGACCGTTATTTCCATCCTCCTCCCCCAAGCACCA
          TGTATATTTCTGCTACTAGATTAGTTGGACTTCGTCTGGAGTAATCTCCCTCAAGTACCT
          TGCATTAGCTCACTTCTTGGTTAGAAGGCCCTTATTTCGGGACTCTTGTTGTAAGGAAAT
          TGCACGATTCTGACACTAACCCAAGGTAATTACGCCACTATTTACCTCTCGTTGATTTAT
          CGTATGCTCTGTGCTCCACGCTTGCTTAAATACATCGAGAAACCACACCAACTTGTACAC
          GGGTTGATATAATGGTGGTGCGCAAAGAATTTACCCCCAAACTCGATCCAAATGCCATAA
          CAAGTGAATATACCCCCGAATGGTTAAAAATGGGTCTTGATTACGCTTGAGTCTCTCTCT

          CGCCCCAACTAATCGGTATCTGCGCAGAGCGTAGAGACGAACGCCACTCCTCCAGAACCG
          TAGCCTATCTACTCGGCAATTGAGCTGAGTGCAGAAGCGAGTGCCATTTTTGCAGGAACA
          TACCGCCGGCCTTCCGTTATTGTGCTGACAACAGAGACGAGCACATTCACTATACAAGTT
          TACCTTAGCTGCTCGCTAGCTATGTCGTACGTCGGGAAGGGAGGCACTTCTAAATAAACC
          CGCCCCAACCCGTTAGCTGTCGCGTTGTACGCCTGAGAGGAGGATACCAATGTAGATATC
          TGCCTTCGTTTTTACGTTGACGCGTGTCATACAGCGAAAGGGGACAGCGCCGTATCTATC
          CGAATTAGTAAGGCCCCTGTAGTGAGGTATGCGGGGGTGGAAAATCACAAAGTTACGGTC
          TGCATGAGCGAAATATTTCACATGCATTTACTATTAACTTCTGGTTGGTGCTATCAGGTG

          TAAATCTGAAAACCGGGATAAACGTGCAGTTCTTTTACTCTCACTGTTTAGAATTAGATT
          GTACTTTAAATACAGTGACAGACGGGCGGCTCTTTCACTCCCACCGCTTGGAATAAGATA
          TTAGTCTGCAAAACAAAACAGTCGGGTGGTCTTTTCGGCCGGAGCGTTTAGGGTTAAATT
          CCATATAGGAAGTAGCAATGGTTAGGTGCCCCTACTGACCAGACAACCTGCGATCCCAAC
          GATTCCTGAAGAAAGAAACAAACTGGCCTCTCCATTGGCCCTCTAATTCAGAATGAAACA
          GACTGCTGGAACAGGATTCTCTTGGGTACTTTTAGCGGAACAGTGATATAACTCAAAGCC
          GGTGTTCCGAGTAGGACAGCTCGGGGTGAACCCAATTGTCATGAGACAAGGATTCAAACG
          GATCTCCTGTGTAAGGCATATTCGGCGATACGACTGGACTCCGTGAAACGTACGTCTCCA

          CTGAGGCCAAATTTGATACAGAACTCATGCGCCATGAAATGAGCAACGCGACCCGGATCC
          GTGAAGCGAATAGATGAGCTGCACTCACGAGTCATAATTCGATCATCACGACCTACATTC
          TTGGAACGAATAATGTTATAACGCTCATCTGCCATAATCTAACCCATGTAACCCATGCCC
          CCGGGACTAATATTGATAAAGAACGCATCTAACAAAGTCGGACTCATAAAATCTGTATCG
          CTGAGGTAAATAAACTCACACAAGGTATCCTGTCCTCGTTGCAATACCCAATTGTTAGCC
          TTGAGGCAAATAGGAGTACACCGATCTCTCTCGTTGACTTGACCTATGCGACGGGCACCC
          CAGGGGGACCCTGTAGTGTAAGGAAAATCTGACCCGGACTTGCTCACCCTCTTCGCACTC
          TATGGTTGCGCTGTAGCCCGAGGGAGACCGAAATCAACCCAACGTGCTTAATACGTACCA

          CGGTGCTGGGATTGCTGACCCTGCACCCACGTTCTGTGAG
          CTATGTCGGGACTGCTGTTCCTGCATTCGCATCCTGTGAG
          CGCCGCCAGACCTGCTGTCCCCGCCTATGCAACCTGCAAA
          CGCGGCCGGGCCTATTGTCATCACTTTCAATTGCTGCAGA
          CACCGTCGTCATCGTTGACAGTACACTTAGATGCGGAGCA
          TAGTGTCAGCCCAGCTGGCGGTGCATACGGATAATGAGCG
          CGAAATCAAGCAACTTAGTAAACCGACCCCGGGTTAGGTG
          TGCTGGCCGGCTTACGGCCAAGATAATAAGTCGAGATGTG

