 8 1000
t1        CTAAATGTGATTTTTTGATGAGCCACTGCTTATCTTCCAGGCTATCGGCGGACAGAAGCG
t2        CTAAACGTGGTTTTTTGACGGGTTACTACTTATCTTCTAGGCTATCGGTGGACAGAAGAG
t3        CCTGCCGTGGTTTTACACTGATCTTTCGCTTGTTAGTTAGGTTACATGTGAATAGCAGCG
t4        CCAACCGCGAATTTTTGCCTAGCCCCTGTCCCTCTCCCAGGTTATATGTGGGGTGCTGCG
t5        GCGACCGCGTCTGCCCAACTAGACCCTATTCCGAATTTACTTCAGACCTCGGCTATTCAT
t6        CTGGCTCCGGTGCTCCCGTGAAACCTCACTCGAGCCATCGATCAACAGCACGCAGACTGA
t7        CTTGTCACAAAGTCAAGGCGGAATCAGTTTAAGCACCAAGGAAACTAAAAGCTCGGTGGG
t8        CTCTCTCCGGCAACCACAGGTGGCCGGGATCTTCGTGCCGACTCTTGCTCTACCGCCGAG

          CACCACTGCTATGATCATGACCTGTAGAAAAGCGTTCATCCTCGCACGCTGCGTACTCCG
          CACTACCGCTCTAATCGTGATTTGTGGAAACGCGTTTATTCTCGTACGCAGCGTACTCCG
          TACTATTTCTGTTACCCCGCCACGCGCAATTCGGTTCATTCTGGCTCGTTACGTACGATA
          TCGGACATCTCCTACTATGTCACGTGGTACCCCGCTTAGCCCCGTACGCTACGTAATCCG
          GACGGATCTACATCCTAGGTAATGCAGATTCACGTCTGGACCCGTACATCACTCATCTTT
          AACAGATACAAGTTCCCACCGACATAGGTTTACGAAACTTGCGGGGAGACACGACGAAAT
          TCAAGCCCTCATTTACGTCCAGACATGGATAACGGCCGTCTTAGCATATGGCTTCTAAAG
          CGAAAGTATTATACCGGTCGAGTATACTCCTCGAGTTCCCTCGGTTCACGGTGGGAAGTG

          AATCTACTCACCCCTGGGGAGTGTGAGGTTTGGGCTCCTGATCCGCGTCATAGATACTGG
          AATCTGCTCACCCCTGGGCAGTGCGAGATTTGGGTTTCCGATCTTCGTCATAGATTCTGG
          ACATTACCCGCACCTAGGTAGTGACAAAGTTCGCCCGCCGGACGACGCCGAGGGTCCTAA
          CCTCCATCCACCCCTAGGCAGTGGCAAGCTTTGGCCACCGGTCTGCGAAATGACTACTCA
          ACGCTACCTACTCTCCAGCATCGGTATAGTACGGTGATGGACGCGCAACTCGAGCGGTAA
          GTCACAGTTCTCCGTCGACGACGCACAGTTATGAATATACGTTTGTGGTGACAGCTTTGG
          CGCGAGATTTTATGTAAGCGTAGGAGGTGGGTTACTACCGGGTTGTAGCCGCTCACTCAC
          TGTCTCCCATAATACTGTCGGATAAACTCCCTCTAAGCCTGATCGGGGTAATAAACTCAA

          AACGTGCTCCCGGTCAACTGCCCGAGTCTCTTCTGAGTCTAATCCGAGGTGTCTAAGGAC
          GACGTGCTTCCGGCTAACTGCCCAGAGCTCTTCCGAGTCTAAACCGAGGTGTCTAAAGAC
          AATGTCTGGTCAGTAGGGCGGCCGGGTCCCTAGACATTTTAACTCGACGCGTTTTCGGAC
          CATGAGCCTGCCGATAACTGATCCCGTCTTTGCCTAATCTAAAGAAAGGTCTCTAAGAAT
          ATGATACGTATTACACAGTGGCGATTCCTTGGAACCATGTAAAACGTTGTTTATACTCAC
          TCATGATCCGCTGATCAATGAAAGCGATTTTAGGCAAGTCCAAATGACATACTTGCGAGT
          TCATTTTCCAATACTCCAAAGCGGTGTGATCAGCCACTCTGACGTATGATATCTAAGGGT
          GACGAGCTTCAGGTCCATTAGCAGCGTCTCTAGGCCGTACAAGTTGAGGCGTTCATTCGT

          TGACGGGTCCTTAACATTACGTTCTACGGCCGAAAACAACTACACTCATTTCGACGCGGG
          CACCAGGTATGTGCCATTGCGTTCTACGGTCAGAAACCACTACATTCACTTAGACACGGG
          AGCGGGGTACTTACCACCGCACTGTAGGGCCGGAAAGAAGAACGCGCGTTTCGAGGTGAG
          GGTTGGGTATTCGCCGCCGTCTTCCAGGGCTGCATACAATTAAAGACCTTCTGAAAACGT
          GTTTAGGCAAGTGTAATCGCCCCCTAGGATTGGGACCAGTCAAGACACTTATATGGCAGA
          AATTCGCTACCTGTTGCGATTTCCCCGGCCCAGAGATGACCCCAGTGATTCCACAGATAA
          GGCCGCCGACAAGCGAAAGCTTTCCCGGATTCGCGGAGACAACTGAGGCCGCGTGGAAGT
          GCATTGCTGTGGACAGGCGGCTTTGCTGTTAGTAAATAATTTCCGTGGCCTCAGTCATAG

          ATAACGCTCATTATAAACAGGGCATACCGCGTAAAGCCTCGTCTCCGACTGAGATCCCCC
          ATAACACTTATTACAACCAGGGTATACCTTGTGAAGACTCGTCTCCGACTAAGTTCCCAC
          TTAACATTAACTATATACCTGGAATACCGCAAAAAAACCCGTCACCGGATGAGCGTCTCA
          GCCCCACTGAAAAAATACTAGGCCTACCACATGAAAACCCTTTTCTGATAAAGAGCCCCT
          CGAACATCAAACAGATGTTTGGCACACCTGATGACATAACCTTTCCGCTACGTGGTCCTA
          ATTCTTTCCAATAGCTGTCAAAGTCACAACTAGAAAGACGCCTACTCGGGCCGAGTTGTT
          GAGACCCAAATGAGGGTCACGGCTTAATACCTGAACTTCGGCACCAGAAACACAGATGAC
          GTAACAGGGGTGAATGCTGTGCTCTGTCGAGAGCAACTTTGTCTATCCTTCCTGGGCCCA

          GCTGGGCTGGCAGTCACCACACTTCGATCACAGTGCCGACTCTCGGCCTTAGATGCCGCA
          GTTCGGCTGGCAGTCGCCACATCCCGATCACAGAGCCAACTCTCACCCTTAGGTGCCGCC
          ACTGCATGGTTGGGTCACCCAACTCGCAAGCTGCGTCAACTTTCACCTTTGGGTGCCGGC
          ACTGTTCTGTAGGGACCTGTAGCTTGCCAATAGCTCCGGCTATTGCTTTTTGATTCGTAC
          GATGGACCAGCGGGATTCGACCAAGTACGGCACTTGTGCTGCTTATTTTCCGGTGCCAGG
          GATTCACAGGCGGACTCTCGCCTCTCGTCGACGGGCTGCCGGTTTTCCCACATGGTCAAT
          TATGGGCTATGACATCTTGGCTCCTTGCTTAAACTTGGATTCGTTATAAAATACGTTTCT
          TCTGGACCTTCACCACGGGGCGCTCTTCCCCAGACCTTATCCGTTGATCGTGACTATACT

          CACGCTTTTAACGCTGGTATAAACCAATGGGCGCCATCGTCCAATAGTGTAAAGGCTGGC
          CATGTTATTAAAGCTGCTATACACCAGTGGGCGTCATCGTCGAATAGTATAAAGACCAAC
          CATGCCATTCAGCCTGCTATACACCAGCGAGCCCTCTCATTAGATTCTCCCAAGTAAAAC
          CATACTACTACCACTGATCTACATTATTTATCATAATCGTCCGTTTCAGCTAAGGCCGGC
          TACGCTGCAGCGACATATAAACTCCTGAAAGCATCGCCTTGGGTCTGCCACAGTGTTCTC
          TGTGGTGCTTTGATGTTAAGACATCAACCAACATCACTCTTTAGCCTACTTACGGAAGTG
          CCCGCGACCAGGATGCCTGTGTGGGAATAGGCACCAGAGAGTACCTCCGCGAATGGGAGT
          ACTAATGGTACGGTGGTCACCCGATTACAAGCCCCAGCGACAGTTTATACCGTCCCGGAG

          GTGACATTATTTTGAAACAAGATAAAATCACGGCCCGGGAAACCCGACTGATTATGACAT
          GTAACACTATTTTGAAATAAGCTAGGTCTACGGCACGGGAAACCCGACAGATTATGACAG
          GTAGGAATTCATGCGCACCGAACAAGATTAAAGTCCCGAGAACCCGATACGTTATGACAC
          GTGAAACTATTAGCCACTACGATAAGGTCAATACGAGGGATATCCGATCTCTAATGGCTG
          GCTGTCCCACTCCCGGAAGAAGTTCTCTCCTAGTGCTAGCTGGTCGTTCGACTCAAGCAC
          AAGGCGGCATTTCCAAAAAAAATCCTTTTGTGTGCTACTATCCAAGACGGGCTGCGCTAT
          TGGGCCTTACGACCGATCAGAGCTCTCTTTTGAGTCCTAAAAGCTAGTATTGACTGTAAC
          TAGCTGATTCCCCCAGGGGCAAATGTCATAACAGGCTATACATCCGCGAAACTTCGTGGC

          AGCTGCCGTCAAACGAGGTTCGGGCATCGCGGTCCAATGGGGGGTGAAGGCTCCCATCGA
          AGCTACAGTCAAATGAGGTTCGGGTATCGTGGTCCGATAGGGGGTGTAGGCCCCCAGCGG
          CACGATATCCTAATGAGAGGCCGTCTCCGTGGCTGAACAGCGGATATTGGCTCCGAATAA
          CGCGATTGCCTGAACATGCGCCGCATTCGCGGATTAACAGGTAGTGGCGGCCTCCGGCAA
          CACAGCCGCCTAATTCGGTACCGCTTCGCTGGTCTAGCCAAACAAACTAGTTCATCGCGG
          CGTAAAGATTCGATGTGGGACGGGCTTTGTGGTATAGTTAGAAAAGACGGCTCTTAGCAA
          CCCCATAGTCCTGTCAGGGTTTGTTTCGAGAACGTGCATGGAGTCGTGATGACTTCGATG
          CGCCTACCTGATACGAACGGGTTGCGTTACGAGGCATAATGCATAAAAGTCTTGCGCTGG

          TTTGGGAATTAAAGCGGGGACTATTATTTTTGCACTCTCCAAACGCCATAATTATGAACC
          TTTGAGAATTAAAGCGGAGACTATTACCTTCGTGTTCTCCGAACGCCATAAGTAAGAACC
          TCTTAAAACAAGAACTAGGGACGACCCTCATGCATGATTCACACGCTATAACCGAAACTC
          TTCCTTCATAGCGCCCGAGATCGAAACTCTTGCGTTCTTCGCATACCATCACTAAGAGTC
          CGCGATAGCCGTAGCCGACGCCGGCATTCAGGGACTCTTTGGTCGGTATTATTACGATTT
          TATACGAACTAGAGTAGGTAGAAATGCGCGGACGTATTACTGAGTCCAGTTGCGTCCATA
          TTTGTCAATTAGAGTCGAAATCGGCACGCCTGCAGTTCTCACACCCTATATAAGCGATCG
          TCTGAGAACCGCACTTAAAATCGCCCCAGTCACTGCCCCTTAATATCATAGTAGATACTC

          ATGGTGATTGGGTTCATTCAAACCGTGTGTACGTGATATATGGCTATGATAGATCTAGAA
          ATGGTGATCGGGTCTATTCCAACCGTGTGTAGGTGATATATGGGTATGATAGATCTAGAA
          TGCGGAATAGGGACAATCTAAGCCGTGTCCAGGCGACGAATGGTCATGGTACATCTATAA
          TAAGAGTTAATGAGGGCTATTGTTGTTGGTAAGTGGCGTGAGATCATAGCAGACCTTAAA
          GCTTCAACAGGAGGTATTTAAGTCGCGTATTAATTGTCTGTAACCGCGATGGGCCAAGAG
          GCAGCGCAGGGGGGTGTTCGTACCGTCAACGCGCACCGCACCCCCGCATTGATCCGCTCA
          TCCGAGAAAGGACTAGTGTTCAGCGTATGTCTTCGGTTGCTAATAGCGCCGTACAACGGG
          TGCACACTGCATCTTGTAGGGAGGTTGTTTGAGTGGAGACCTGAGGCCCGATATTGGGTG

          ATAATATCGAAGTTTAATGGGAGCAGGGATGCAAACAACCCATTGATTGACCGCAAAGCG
          ATATCACCGAAGATTAATGAGAGCAGGAATGCAAACGACGCATTGATTGGCCGCAAGGCG
          ATATTATTGAAAATTGGCGAGAGTTGGACCGGGAACGGTGATTTCACTAAGCGCAAGGCG
          GGACCCTCAGAGATCGACGGGAGTTGTAAACGAAACGATGAATGGAATGATAACCGGGTG
          TGTGGCCTAAAAACTAGCGCTAGTCCGGAAAGAAGCGACTAATTAATCTAGCCGCAAGCC
          AAGATGGCGTGGTCGAGGGTGCGTTTAGCCAAGGTACCAACCTTAAACGGGAAGCGACCG
          GAAGCGACAGAGGTGACTGTTTGTGGCGCAAGGTGCTACTCCTTAGTCAAGAGACTAGTT
          CAAGTTGTTAATTTGGACATGATTACCGAAAGAAATAAAAGAATAGATAGCCCTTAGGTG

          GGGGAAGACCAGAGCGACTTACAGTAGTGCACCACCCAGCTCGCCGTATCCGACAAGAGC
          GGGGAAGAGCAGAGAGACTTGCAATAGTGCACTTCCCGGGTGGCCGTCTCAGACAAGAGC
          GGACGATACCGAACAAAGGCACAACATTTGACCGCTTAGCTCGAGATCTCAGACAAGAAA
          GGGGAGTAACGTACAGATTCAAAACAATACTTGACCTAGCCCGCCGTCTTAGACAAGCCT
          TCAGAGGTGGCCCCAAGTACATAATACCTAGTTGCCCAGTTCGTCGACTCAGAAGAAGAA
          GATGTGGGATTAGGGAAAACTAAACGACCATTCGAGTGGTTTGGCCAATGGTAAGTCATT
          GAGGAGGGCTCGTAACATGCTACCATATTTAAAGCATATCAAACATTTTCAGAACGAAAT
          AAAGAGCGTTAGAACGGATCTGGGCGCCTTGCAGAGAATACGCTATTCCAGCCGAAGAGA

          ATTCGGACGACGGGTTTGGTACGAACGGTCGACCTGTGTCTACATTAAGAAACAATTCGA
          ATCCAGGCGACGGGTGTGATACGGACGGCCAAGCAATGTCTATGATAAGGCTTAATCCGC
          TTTAAAACGATGGATGTGCTATAAATGGCTGACCGACGTCTCTGTGACGAATTAATTCAG
          TTCACTACGCCGGGTGTACAACGACTGGCCGATTTCTCTCCATATGAGGAATTGATCCGA
          TGTCAGCCAAGGGCTGTCACTTTTGTAGCGCATTGCTGACACTGTGCCTTATTAAACCGA
          TTCAGAGCGATAATATTGCCATCCGTGTTAGGCTGAGGCTGATGCGATGCAACATAAGGC
          TATGGGTCGACACTCTCGTCGCCCGCTCTGACCTATCGGATATTTGAGACAATTACATGA
          CCTACGGTGTTGTCCTCGTTCACTGCATTTGTCACACGCTGATGAGATTGACACACACGC

          GCACCCCCGATACACGAAAGGATCCCCTAGAATACTCCGACCTGGTGACAGGCCGTCAAT
          ATACTTCTGATGCACGCAGACACCCCCCAGAAACCTCCGGCCTGATGAGAGGCCGTCACC
          ACACCTTCGACACTCAAGAAGACACCTCCGGGGTCTCAGGCTCGCCGGTAGGTCAAGACC
          ACGCCTTCAACGATGAAAGTAACTCTTAAAGGCTTCACCGCCAGATATCAGGTCGGCGCC
          ACTTTTACAAAACTTGGGTAAATCGCCAGGGGTCTGTTGCCAAAATGGTAAGTAGTCGTG
          AGACTAGAGGGCCTCGAAAACGCGATAGACGATATCGTCAGAGGTCGGGGGTTAAGAATG
          ATTACCCTTACGCTCTATAAGACGGATAATCACTCGACGCTCTGCTCGTATAGTCTGACA
          AAACTAATGTGCATTCGGGTCATGGAACTCAACTTGGCGCTACCAAGATCATTAGGTACA

          TCAGTCCGAGATTACAGATAAATGTAGGGGTCCTTCAAGG
          TCAGCCCAAGATCGCAGATAAATATAGGGATATTTCAAGC
          TCAGCTTACGATCGCTGACAGATGTAGGATCCCTCTGAAA
          GCGAATTGGGTCCACAGGGGAAGTCAGAAGTCTTTAAACA
          CTGGATAATACCTACAGGAGAAAAAACGGGTGGTCGAAGT
          ACAGTCGTCGTTCCCAGTGGGCAGCAATAACATCCCACGC
          GCAGTAAAGGTGGACAGCACCAGGAGTGAGCTTCAACTGC
          AGAATTCACACACACGACGGGGCGAGAAACTGCCTGTCGC

