 8 1000
t1        GCATTACTTGACTTATGCAGTTCGGGCTTAGGGGCACAGTCCACAAATAAAGGGGTCTCT
t2        AGTTTACTCGGCTCATGCAGCCCGGACCCTGGGGCGTGGAGAATAAGTAAACGGGGTTCT
t3        ACTCTGTAAAGTCCCACCTCCATAAACCAGGGGCCGTCGGACATGTACGATCGAATGGTC
t4        ATAATCTCAAATTGGTTGACTTCTGGCTAGGGGCGGCAGAGCACGGGCGTTCGTTGAGAC
t5        AACTGACCGTGGAATCTTGATATATGCCAGGGGTTCCTCATATGGATCCTTCTACGTCCC
t6        GTCTATCGATCCTCTCCCCCCCCAAGCTGCGGCCAGTAGGAACTATCTATTTCACGTGCT
t7        GGCTGACCCCGTTCGTCTACTTTGACCATTCGTTTACAAGGGGCGACTGTTTGAAGTACA
t8        GGCTTATGCTTCCCACCCAGCTGGGACTGATTGAAGTGACGAGCCACGATTTATTGAACC

          GAAAAAAGAATTGGGCACTTTAGTCCTTCGAGTATTGGTGTTAAGACGCCAGGTACACGC
          GAAAGAAAAACTGGACACCTTGGTTCCTCTATTATTGGTGACAAGAAGCTAGGCATCCGG
          ACATAGTGAGGCGGGCATTTTGGGTACCCTCATACCGTAGATCTGGAATTAGGCAACTAA
          GCAACAAATCTAGGGCGCATCGGTTGGGCGCATCCTCACGAAGTAGGGCTGGGTAGCAGG
          AGGTGAATGATGGGACACATCGTTTCCTATGGTATTGCCGTTCAGGAGATGCCGGGCTTG
          GGACAGAGAACAGAGCAAATTGGAGAATTAAACACTGTTTCGGCGGTGCTGGTCAGTCTA
          TATTAAGACAGCAGGCTGTATGAGTTTCTGATCGTCCACATTAGGATAAGCAGCGCTCGT
          CAACACCATACCGAGACGGTCGATTCTTTGGTAGTTGCCATCTTAAGGCCAGGCACCCCG

          GGGCGCTAGTGACCTATAACCCAAAGTAGTGTTATGGGTTCAATCGTCACTTGGGCGGCT
          GAGAACTGGTAAGATATAACCCAAAGCAGTGTTACGGGTATGATTGTTACTTGCGCGGCT
          GACCACCAATAAACCGCGAACTGGAGGCTTGTCCTCAGCCCAATTGCACCCCAGACGTCC
          GTCTAGTACACTAGTGTGACATAAAAGGTCATCACCGGCTCATTCGCGTACCTAGTGTCT
          AAATTGCGTTGTAGCATGGCTGGGGTCGTCAGAATTGTTTCACTTTCATTCTTAGGATTC
          AAGCTGTGTTGACCTATAACGCTCTGTGCAGTCATTCGCCTGTTCATACTTTGATGTCAC
          GAGCCGGGGAACCCTGTGGCCTAGGTAGGTTGTCTGACTTTGTATGCCCTGTACGCATAT
          TCGCTGGGTGGAATTATAGCACGGCTAGAGGACCGAACCTCGCTTACGACGCAACCAGCT

          TTTCCAAATCAATTCGCGTTGTGCAAGACGGACTCGTCCGCTAAGCTGAGCCGATAAGGC
          CCTCCGCGTCAAAGTGCGTTGTGCCAACAGGGTTCGCTCTCTAACCCAGTTCAATCGGGA
          CCCGGGCTTGAGTCGTTGCTGTCCTGTCTGAACTTGTACACACGACCAGTCCTGTATGAT
          CCTGTCTTTGAGCGTAAGCTAGTATCTCAGGGGACGCTCATCAGCTCGAATTCACTCGGT
          AAGTTCTTGACACGCCTGATGCTCAACCATGCTACACCCCTTCACTCAAAATCTTGAGAT
          GTCTACCTGGCGAGGGTTCTACCTGACTATTACTTATTGCTCCGCCTGAACGGTTAGTGA
          TTTGTGCAAGGGCGTGCGCGGGCAGACCCAAAACTAGCATGTCATTTAAGGCTCCGCGAT
          TTTACTACAGGCTGCGCATCGCCAGTATCAGGCTGAGTTTCTAGTTCAAGTCCACACGGA

          TACACGATTTGGAGCAACGTTCTTGTCACCGAGTGCTACCGGAATTTGAACGGTCATTCA
          TGCGCGATTCGATTCAACACTCTTGTCATCGAGTACAGTTGGAATGTCAACTGTTGCTAA
          TATACGACATGTAACTTCAGCTCCCCTTCAATGTATCAGTGACTTCCGTATCAGAGATTA
          GGCGTTATTTTAACCTGGAGCTACTCCTTCGAATATATTTCCGCCGCGGGCTAAGATTCG
          TTCGGGTACGATATTAACGACATCCCCCCAGCGACTGTCGGTGCCGTGAACGAGATATAT
          TACCACTTCCCCATAGTTGGATACCTTCATGTATTCCCTTGTGTTTCAGATAAAAACCTG
          GGTGCTCTTGCTATCCGTGGCAGCCTTGCATTCAATCTGTGGATGGTATAGTAGGGCCTC
          AAAAATCCACTCTATTACGGTACCATCTCAGTGTCCAGGCGGGTAATGAGCCAGGGGCTT

          GATTGTCGTGCCGACTTGACTAATGCCGTCCCTGTGTGATGTAGTGCCGTCGGGGGCCGA
          GACCGACATGCCGACTTGACTGACGCTGGCCTTGCGTGAAGTAGTGCTATCGGGGGCTGA
          AATTGGAAAGCCAACGGAGTTACTGTTAGTAGCGTATTACGTACTAGGACACGGTGATGA
          GAACCAAGGGTCATGCGCTCCATCGTCCCCACCATACTTTGTACTGTAAACTGACCCTAA
          GACTCAGGGGTGACAGTACGCACCGTCGCCGTTAGAGCTCAGGGCACCGGGCGGCTATGG
          GGTCAGTGAGCTTTTAGGCGCGTCCTTGCGGGCTAAATGCGCGTTAACGCGAGGTCCCGT
          AAACCGTCATTTCTTGCAGCCGGAGCTACAATGAAACTTAGCGTTGATATAGGGTGAAGG
          ATTCCTATGTCCGTTTTTACAAAGACTCTTCTTAAATCTTACTCAGAACGTTGCTGCCAA

          GCACCGTCTGCCGAGCCGTAGCAGAGGAATAACACGTTCGGATAGTTCTAGTGTGCAAGG
          GTAGCGTCTACTGAGCCGTAGCGGAGGAATACTACGTTTGAATAGTCATAGAGTGCAATA
          ACGAAGTCGATTAGGCGAAAGTCACGGGACTGCATTGTTGAATAGGTACGCAAGGCAACA
          GCAGTGCTATACAGGTGGATTAAGTGAGTTTTACTTCTTCGAAGGTTTTGACAGGCAACA
          GAGGTTATAGTCTGAGGTGCCATCAACGATTATACTTCCTAGTATTAACAGTGGGCCAAG
          GTAATGACAGCTAGAAGGTAAAATAAGGCTTATGCATCCCAATCTCATTTGTGCATGTTT
          GTTCAGTCAACCGGATGGTCGCAAAGAGATCGCATGGCGCACAAGGCTGGCCGGCTACAC
          GCGCAGATGGACGACTAACATAAGGCACATTGCATCAGACTCTGGCCCATCGCGGCGTGA

          GCAAAGCGCTTGCGAAGCACTCACTACAAGCATCGGATCGCGCTGGAGGCCCAGGCGTCC
          GCAAATCGTCCGGGAAGGACCCATTACGAGTTTCGGGTTTTGCCGGGGGCCCAGGTGTCC
          GCGGTTCGCTTGGGTGGGAGCAATTATTAAGAGCGAGGACCATCTTAGAGCAAGCCCTTA
          GTGGTACCTGCTCGTAGGCATCCTCGCGTGGGACGGGTTCCGCGCGAGGGTTTAACGTCT
          CTAGATTTCGCGCGACAGACTACATGACCAGAGTGGCTCTTGCACTAGCCTCATGTATTG
          CCTACTAGCACGGGACGTTCCCTTCTGATTGGCTCCATCCAGTTATGGCACATGTCGCGT
          ACGTGCGGGATGAGCGCAACAGCCGCCGGATACCAGTTCCTCGGACCGGTCTGGACGTTT
          GTCGGTAACTGGAATTCAACCACCCGCGAGAAGGGTTTTTTCGACTAATTTACAATGTCC

          TAGCACTGATTCCGGATGGAAGGCGCATAGGCTTCGTGTCTCACCACCCGAAGGGAGTAA
          TTGCACTAATCGTAGACGGAAGCCGTATGGTCTTTATGTCCCCCCATCCAGAAAGAATAC
          TCGCAATTTATTCAGTTAGAAGCGGCGCGTGAAATGAAGACTACACTCGAAGGGGAATCA
          TGCCTATAATCCCTGGCAAGTTACGTGGGCACACGACGCCCCCATCTCGGAAGGAGGGTC
          TCTCCAACCTCCGGGGCCAGATCCACGGACATACTGCGTTTTGTCCCTCTAAGAGAGAAA
          TTCTTATTACTGAATACACGAGTCGGAGCAATGCTACGTCCTTTTTCCCGTGAATACAGG
          CCTTCATCACGAAGGGCGTGGTGCCGGGCTACGGCAAGCATTCATCTCTATTTACAAACG
          GCTTCGAAATTCGGTTCCTGAGAAGCGGCCAACGCGGCTTGTACACCCTGCTGCCAAGCG

          AGAGTACACCATATCCTGACAACCGCGGACGAGAGTCCATCCGTGTATTCAGTCGGAAGG
          AGAGCACTTCAATTCCTCAAGATAGCAGAAGAGAGTCCATCAGTGTATTTAGTCGGAAGG
          AGAGTGAATGACTGTCAACAGACTGGGGAAGAGAGGTATTTAGTTAAGTTGGTGCGAAAG
          AGAGGACCTTAACTTCCTTAGTAACAATAGGGGAGGTTGCCGACGACCTCTGCGGAAGTC
          AACGCTCCTCAGAGCTTGTTAACGTTTGCTGATAGATACTCGACGCGTCCGACACGGGGA
          AGTGCTACGGATGGTTCGTAGAGACATGTTGAGGGGAAGCTGGTACATTGGGCTAGGGAA
          AGGGTGGTCGCGAACTCGCAGCAGTGTGCTGGGGGACTAGCCGAAAACCCGGTAAGGGGC
          AAATTGTTTCAGAAACTACTGCGAGGCGACGGGAGTATTTAAGCGGGCGCCAGGACCGGG

          GCGGAATTGTCGCGCGGGGCTATTTGAGCACACCAGTCGCTGATGAAAAAGGACCTCTAC
          GAGGTATTGTCGCGCGGGGATAACTGAGTTCACTAATCGCCGATGAAAAAGCGATTATAC
          ATGTAATTAGAGACATCAGCTACTCGCGCTCCATAGATGCCGATAGGTAAGCCACTACTC
          ACATAATCACGGACATCAGGCAACCGTAATTCACAGAAGATGATGAAGAAGCCATCATCC
          CTACAATCTAAGAAGTGGTTAAACTGTATTCTACAGTCGTCGGAACGCACGTCATTTGCT
          AGACAATTTGTTCCTCCGATTACGTTCCTTTCGGCGTCATCCGTACGGTAGCCATTCGCC
          GTTATTACTCGGACAACGTCCAGCAGCCCCCTGTATATGCACGGGGATACTGAACTAAGG
          GTAATTCTGTGGTGCTCGGTCCCGCATTTTCTGCATCTGTTTGCAGTCCACACGCCGACC

          TCATTCTGACCTCACGTCTGAGAACTAGGTGATTAATTGTAGACAATGTTGGGACAAAAC
          TCCTTCTTCTCTCATGTCTGTGCATCAGATGATTAATTGTAGATAATGTCAGGTTAAAAA
          TCAGAAGAACTCGCCACCTTAGCTTGCGGGGGTTAGCTGAAAGTTTGGTTGAGGTTACAC
          TCCGTTTAGCTGTTAGCGTGAGTCACGAAAGGCTAGCTGCTCGCTCAGGTAGAATAGCGC
          CCGTCTCAGCAGGTTGCCTTCACTAGTTACACGAAGTTATTGGAACAGCAGGCCTAAGTC
          TCGTATATGTCGGGCATCCTTGTTGGGAGAGCGCTTCGCCGGGCGTGGCAAACCGGGGGC
          CGCGTATAACTGGCCGTGTAAATATCGGACATTTAGAAGCCGACCATACCACACCTAGTC
          TCGATTGTACAGGTCGTATGGGTCTACAGCGCGTAGCTGCGGCCCAGTCCGATCGTGAGT

          TCGTAAATCCCTGACCAGATCCAGGCTGTACAGTTTCTTACTAACCGTCTCCGCCCAGTC
          TCGCAAGATTTCAACCAAACGTAGGCTCTATAGTTTCGTACTAGCCACCATCGCAATGCT
          CCATATATTACTAACTGAACTTGGATTTGATAGGTTCCGCGTCGTCGTAGAGGCCATGTG
          CCGAACCAACTCTTCTACATTTCCGTTTGGCACGGTTCTCTGGGTCCGCGGTACGTTGCT
          TAGTCTCTTCAGAGTCCAGCTCGCGGTAGGCCAGTGAAGTCGATGCAAGGGCGTGACGGT
          TACAATGGGGGAAGTGTTAGCCGGTGCCGGTTGGCTGGCATATATCCAGTAGATGTCTCT
          CATCACTAGTCAACCTGGGTATTGCTCTGTTGTTTATTACTTAATGTTAGGCTAGTCGGT
          TTATGTAGTTAGGACTAAACATAGTGCTACTGTATCTTACACGAAGTCGACACCCCTAGA

          AGCGTCAGCTTCGACCGGGGAGGAAGCGGATACTGCACGGGTCGTGTCGCAACCGGCCTG
          CGCGCCGGTTCTCACCAGAGGGGGAGTAGATACCGCACAGACCGTGTTGCAATCGGCTTA
          GTCTTATAATCAGAGCTACACCGCTGCGAAAGTTGCAAAGAAGGCGCTGAAGTAAATAAG
          CCCGCACACTTATGTTAGCGGCGAAGCGAAAACGAAGAAGGTAGCCTTCGACAGGCAAAG
          CTCATTAGTGCGCTTTGGGGCAGTGGTACCATCGGCGGGGAGCCATTAGCTTGGGCGTCA
          TTCCGAAGCTTGATTGCGTGATATAGCGAGCCTAGCGGGACTCGGCTCGGCTGTATGCGG
          GCAAATTGACCGATCTGGCTATAGCGGCCACTCGTGAATGAGTAAACAGCGAGTGGACCA
          ACGTAATAACCCTATTGCTATCGGGAGGGACCTAACAGGGAGCGCCTAACAGGAACCCCG

          AACTCCAAACTGGTGGCGTTTAATTGCGCGTAGGTAAGGAATTTCGGCCAGTTATGAAAG
          AACTCCAAGCCAACGGCGCGTAACTGCGCGGTTGTAAAGAAACACGGCTAGTTACGGAAC
          CGTCCTACAGGGATGCTATTGAGTTATATCTTGGTACAGAAATATGGCAAGCTATGGGAA
          GACCCTATAACACGGCTTCCGAGCTGCTTGACAGCGGGGAAAGAAGGCTGGCTGAGGGAG
          TACTACACGGTGCAAAGGAATGTGAGCTTAATGGCAGCTGCTCCGTTCAGGATTCACTTG
          CAGCGTATAGAACAAATAGCGGAGTGAGTGATAGTTGGAATCCACGCTAAGACGTAAGGA
          AAAGAAACAGGGTAAGGAGCGTAGTGCCGCACCGCTGCTCACAAGGTCTGGTGATCCAAG
          TCCAGAGTCAGATGAATGGAGATACGCCTCGCGGCATTTTACTCATGGGAGACATAAGTT

          GCACCAAGGATTGACTTACTTTCACGCACTGGCACCTCGAGACCGGCCGGTATGAGTCTG
          AAAACGAGGAATGACTTACTCATGCGCACTGGCAATTCGGGCGCGCCTGGTACGAGCCTG
          ACGTTTCGAAATAGCGCACGCGGTTACATGGCTGGTTCCGGACGATGCAGCAAGACGCTG
          ACCTCTCTAGTGAACATACACTTGAATAAGAGTGTCTCGAGGATGCATAGTAAATCATGC
          GAGACAGGGGTTCGCACAACTCCGGATACTCAGCGATCAATAATATGCTGATTATCTTGT
          CGGTTTTGGAACGGCTACACAACACGTGTGGATACAGTGGCCAATTACTGGATATCATTA
          ACGAGAAGAGCTCATCGTATGCTCTGCGAAAACGAGTGGATGGCCGCGGGTCATTCACGG
          GCGTCATCAACGAGCCTAGCTTCTTGTGCGTGCGAATAATCGTCAAACAGTCCCTTATTC

          CTCGAAGGTATTCGCTCGAGGTCATCACTGTGCCACCCGA
          ATCGTATATACTCGTCAAAGGTCTCCACTGTACTACCCGA
          TCAATTGATTCTCGACCTGGGCTATCACTGCATTGCCCAG
          TTCATCACTTCACATTCGTGAACAACACCGACATAGTCAA
          ATGTGGGTCTCGCATTCACCACTATCGTTTATAAGGGCAA
          AGAGCAACCCCGCGTGCATGGCCACCGTTCACATGCCCCT
          TTAGCGCAATTTCGTACTTAAGCTTCATCGTACAGGCCGT
          AGCGAAAACACTCTAAAACGGTTTTCTGCTCTCCACCTTA

