 8 1000
t1        TGCTTCCAACCTACTTTTTGCCCCTCCTGGGTTCCCGACGCACTCTCGTGCGTGCCGACT
t2        TGCTTCCAACCTACTTTTTGCCCCTCCTGGGTTCCCGACGCACTCTCGGGCGTGCCGACT
t3        TACCTCAGACACCACTGGTATTTCTTAGGAATCTCCGGGATCGCTTCAGGCGTTCCGGTA
t4        TACCTCTGACACAATTGGTATTTCTTAGAGATCTCCGGGGTCGCTTCAGGCGTATCGGTC
t5        CCATAGTGGCGAAGCGCATGCTCTTACGAGGTAATGACGGGTAGAGAACACAGGTCGGGA
t6        AATGCCTGATGTGGGGCGTTATCTTACCGAGCTCTAAGTAGGAGCCCAGACCGGCCGGTG
t7        CGTACCTGCAGCTTCGCATTGTCTCTCGGCTCTTCGAAACTTTCGGCATTCAAGTCGGAC
t8        CGAATCTGCTGCGCTGTAGCTTTTTGGAGCGAGTCAAGAGCAGCCTCGAGCGAAGAATAT

          GCTGTCCCACTCGCCACCAATGCGATCATGGGCCGCGTGGAGCGGATGGGGACGTGACGT
          GCTGTCCCACTCGCCACCAATGCGATCATGGGCCGCGTGGAGCGGATGGGGACGTGACGT
          GTCTTCAATCCGGTTACCGATACGACCGAGAAGCTCTTACGTGGAACGGGGGCATGTCGT
          GTCTTCAAACCGGTTACCGATGCGACCGAGAAGTTCTTACTCGGGACGGGGGCATGTCGT
          GACGTTATGTTGCTTGCGGCAGCAGCCTATGCGCGCTTATGCACGTTGGGGACGACCTGA
          AGTACCGGTTCGTCATTTGAAGCAGCAAGCGGGTACTCGAGACGCTTAGCGACGAGAAGC
          GTAGTTATGTTGAATACTGTGGCTGCGAGTACGTGCACAGTAGGGTCGGGCATCCCGTTG
          CTTCCTGAACTACATATGAAAGGCGGAGGAAGGCATCTAGACAAGATAAGAGTCAACCGC

          GAATACGGAATAAGTGCTTATTGTCTCAGATACGGATTGCGCGACGAGCTTATAGAATCC
          GAATACGGAATAAGTGCTTATTGTCTCAGATACGGATTGCGCGACGAGCTTATAGAATCC
          CCGCAGGAGATAGCTACTTCTTGTTTGACTAAGAGATTGCGCGTGAAGATCATAAAATCC
          CTGCAGGAGATAGCTACTTCTTGTTCGAAAAAAAGATTGCGCGTGAAGATCACAAAATCC
          TCATTCTACCGAAAAACTCGAACCTAGAAGTGAGCCTCGTGCCCATCTTCGGCTTGATTA
          ATACACTGAGCGAAAGACGACAAATGGACGGGAACGCAGTATGGTCGCTCTCATTACCCT
          CTGGGTCAATTTGTAGCCTACGCGTGAAGCATAAGACGCTGTGAAGCGACTGCCCAAAGG
          CTATGCCCTTCGACAGTAATATGATTGATTAAAATGCGCTAAGGACTATACGTTTTCATG

          AGGCTGTCCCCACGGTGCCGGAGACGGTGGCACCATCCTATCAGAAAAGACTCACAAGGA
          AGGCTGTCCCCACGGTGCCGGAGACGGTGGCACCATCCTATCAGAAAAGACTCACAAGGT
          AGGCCGCCCTCACGGCGCCAGAGCCGGGGACGCCTTCCTGCCAGACAGGCCTTTTATCAG
          AGGCCGCCTTCACGGCGCCAGAACCGGGGACGCCTCCTTCCTAGAAAGGCCTTTTTCCAG
          GTGCAGGCATAACGGCGCCCAAGAAGCAGGAGCAGTTCCGACGCGAGGGTTTGCTAATGT
          AAACGAACTCGTTAGTGACGGAGGTCCCGCCTGTCTTTTAACCGACCAGACCTCCACGGG
          GGGCGGAATTATTGACAGCGTGAGTCGAGGCGCTCCTGCGACTTTCCCTTGCGGCGTAGC
          GGGTGGCTATACCGGCTACGACGAAAGGATCGCCCTTCTGTATCTGGGTAACTTCACCAC

          CTAAAGCTGCACGATGAGTTGGTCCTTTCGCAGTGTGGGAATTAGATGCTGCACTTGGTC
          CTAAAGCTGCACGATGAGTTGGTCCTTTCGCAGTGTGGGAATTAGATGCTGCACTTGGTC
          CCAAAGCTGCATACCGAGTGGACCCTTTCAGGGGGTGGTGACCAAACACTGCACATGGTC
          CCAAAGCTGCATACCGAGTGGGCCCTTTCATGGAGTGGTAACCAAACACTGCACATGGTC
          CAGAAGGCAGCTTACGTCAAGATCACCAACGGACTAGGAACCCATAGGCAGCGATCGGCT
          TCAAGAGTCTAACTGAGCGAAATAATCACGTGCATAGGAACGTCAAAATTGTGAATCCGG
          AAGGGCTCGACAGGGTAGTAGTCGATCATGCACAAAAGCTGGTCTGAATGGCAGATGGAC
          CCGGGTTTGAACGTGCACTGGTAAACCGTGTATACGTGCCGGACCAGATTACGAGCAGGC

          GGAAGGGCCCGTGAACAGTAATATCACTCCATTCGAGGGTAGATCGATTACCCTTGCAGC
          GGAAGGGCCCGTGAACAGTAATATCACTCCATTCGAGGGTAGATCGATTACCCTTGCAGC
          GCATGGGTCCGCCCACTGTATTAATGCCGCCCTGGAGACCGGTTCGATTTTCACCGTGGC
          GCATGGGTCCGCCCGCTGTATTAATGCCGCCATGGAGATCAGATCGATTTCTATCGTGGC
          GAGTCGCTAGAGACGATGCGCCGCTTACGGCCCGCGGATTCCATGGACAAGGACCGTCAG
          GCGGCACTCACGAACTTGCCCCACTAGCCTTGCGAAGGCAACGTAAGTAACGGTTGTGAG
          ATTAACCCCGGGTCGCACTAGCATCTGCATGGCCCGGGGTGGAATAGCTACATCCGCGGG
          GCCGTCTTTGGGTGATGCAAATACGTTCCGCTAGCACACCCAGCCAATCCTGATCGCGAA

          GTCTCGAAGTGGGTACGTTCTACAGCATTATCGTGACCGCGCATCGCTGAATCTGAGTTG
          GTCTCGAAGTGGGTACGTTCTACAGCATTATCGTGACCGCGCATCGCTGAATCTGAGTTG
          GTCCCGGAGTTAGTAAGCCCTGCGGAGTGCCCCTGAATGCGTCCAGTAGACCTATTGCTA
          GTCCCGGAGTTAGTAAGCCCCGCGGGGTGGTTCTGAATGCGTCTAGTAAACCTATTGTTA
          GAAAGGGTCTTGATTTGCATGAAGGTACGGAGAATGATAAGCTAAGTTTAAACACGAAAC
          TTACCGTTGAGAGACTAAACGGTCCGGCGAGTTAAAGCAGGTGAAATCGGTTGATTTGCG
          ATTATAGACGTGACCCGTGCCATATTATGAACCTATGGACCCTGACTCTTGCCGTTGATG
          CGAGCAGGGCTCTCCAGAGCATTGAGACGGGCTGTAATACTTTATGTTGTAATATCGCAG

          CTGATAACATGTGAGCTTTCGCCGACGTCATCAAACCGTCGAACCCAGACCGACGCAGAT
          CTGATAACATGTGAGCTTTCGCCGCCGTCATCAAACCGTCGAACCCAGACCGACGCAGAT
          TTGATAATATGACTGCACTAGGCGACGCCCCTAGACCATAGGGCTTAGACTGGGGTAGGC
          TTGATAATATGCCCGCTTTAGGCGACGCCCCTAGACCATAGGACATAGACTGGCGTAGGC
          CGGACCACCGACCTTTACTCACGGAGCGACTCAACGCGTGCCGTTGGTTCGGGTATGGAG
          CGAAACTAACCCATTGAGTTCGTGGACCAGTCCTGATCATGCTCCCAGGAGGAGCCGGCT
          CGGACAGCCGACACACGATTACACATTTTGTAAAGACCCATTGCATTGGAAAACTGAAGA
          GCGGTGCTTGCTGAGTAAGCGACCGGTTAGGCGGAGGTGAAAGTGCTGTAACATCAGGGC

          AGTGACGGGACGATCAATCGTGTGAAGTTATGTGGCTTAGACTTAGAACGAGATCCAGGA
          AGTGACGGGACGATCAATCGTGTGAAGTTATGTGGCTTAGACTTAGAACGAGATCCAGGA
          GGTGACGGAACGATCTAGTGTGTAACATCACGTGATTTGACATTAGGATACCATCCAGAG
          GGTGACGGATCGATCTAGTGTGTAACCTCACGTGATTTGACATTGGGATACGATCCAGAG
          GAAAGGCCAGCATGCCCCTTCAACGAATACCACACGCCTGCGCTTTGTCTTTGTAGCGTG
          AGTAGCTGAACTGGCTGGTACCAGCTAGTTTCCAGCGTCAAGCCAAAAGTCATCACCCTG
          GTTAGTAATCCGCCCCAGCTGTTGAAGATACTTCTGTCACATCTGCAGGATCGCCTTGGA
          AGCAGCACCTACGACCGGTGATACAGGGCACGTGTGCGATCATATATGGGCTCCCTCGGG

          ACCCGATTGCCTGTAAGAAATGTGTGATACTACTTCTAGAATGGATCTTCGGGGTTGGGC
          ACCCGATTGCCTATAAGAAATGTGTGCTACTACTTCTAGAATGGATCTTCGGGGTTGGGC
          ACCCGTCTGATCTTGAGATGCGTTTGGTGCTACTCCTAGCACGGAACTTTGGGATTGGTC
          ACCCGACCGCTCTTGAGATGTGTTCGGTGCTAGTCCTAGCACGGAACTTTGGGGTTGGAC
          GGTAATATGATACGATGGTGAGTCAAAACACAATCTTAGGTCTCGGAGAATGAGACTTGC
          TCGTCGCTGCCGCCCCCGAATTTAGGGAGCGTATCTTAACCGGCACAACACCCGCCAAAT
          AAGCTAATGTCACCACGATGCTCTCATTGTTCGTCACAGCTCACGCATCCCCCGCTGTGT
          ATTAACCGACACCTACATTGGAGTAGACGATTACCTTTGGGTTAAAGTTCTCGGGAGCGT

          GAAAGAGTATTGCCGCTACATAAGAAAGTTCGACAATACCGGCTTCGAGGCAGTCGTTCC
          GAAAGAGTATTGCCGCTACACAAGAAAGTTCGACAATACCGGCTTCGAGGCAGTCGTTCC
          GGAAAAGAATCGTCCCAACACACGCGATTTACATGACACTAGATTGTAGACATCCGGCCC
          GGAAAATAATGGTACTAACACTCGCGATTTACATGACACTGGATTGTAGACATCCAGCCC
          AGAATGCTGCTATAGAATCGTGTCAAAACTCCCATAATTCGGTGTGAAGCCATTGTTTGG
          CGAGACCGACTTCCGCCATAACCAGAGACATAATGGACATGGAGCCCAAACAGTGAACGC
          AGAGCTTTCCCTAGTCGGCCGATGGAAACTTAATGTGGCAAGCGAAGGTCCGATCGCTTA
          AGAGCCTTCCTAAGAGTGCCCGGAAAGGAGCGCTAAAGCCGGCAATAACCCAGCAGTTGG

          CCGGGACGCTTTCCACGGCGCTGGACTGAGCCTTTGTGTGGGTGTAAAACATTTTGTCGG
          CCGGGACGCTTTCCACGGCGCTGGACTGAGCTCTTGTGTGGGTGTAAAACATTTTGTCGG
          TCACAACGTTTTCTACGGTGTTGGGCCACGCTATGGTACAGATCTACAAGCATTGGTTGG
          TCAGAACGTTTTGTACGGTGTTGGGCCATGCTATGGTAGAGATTTACAAGCATTGGTTGC
          TCCGATGATGCATCACAACACCCGACTTAAGGGTAACCCGCAAATAATATGGCGCAAGTT
          GCTTATTATCGATGGTTAGGTTAGACCTTAGCAATAAATTAATGTTCTAGTGGGTTGGTC
          TCACGATTGACGCGACGTCTATCGACACTATTACAGTACTGTTGCAAAGGAAGCTGGAAG
          TCGCACTGGATACGGGCGCAAAAGGACCTCATAGGGCGGGCTCGCAAAGGGACGTTAATA

          GCACTCGTAAGTGAACCTTCCGCATCTACTACGAAAAGCGACTGCGGAGCGTTACGAGTG
          GCACTCGTAAGTGAACCTTCCGCATCTACTACAAAAAGCGACTGCGGAGCGTTACGAGTG
          TGATTCTTAAGCGATTCCACCGCAACTGTCACAGGACGCGACTGCTAGGTGAGAAGAGCC
          TGACTCTTAAGCGAATCCAAGGCAAATGTCGCAGGACGCAATTGTTAGGTGAGATGAGTC
          GGATAAACGAGTGTACACGCAGATCACAAAAAGATGTACACGAGGAGGAAAGGCCCTATA
          CTCGCTGCGTCTGGTCCTATTCCATTATTTGTGACGCGTGATAGGTCGAACAATCCCGTG
          TGGCTTCCCGGTAGTTGAGCCGTAGAATACGCTATGGATCGGTGATGGGGGAGTCATGTC
          CGCTGCGTAGGTCGACCCAATTTTCAGTAAGCAAAATACTGGCCGCAGTAGACTTGTGAC

          CCCTCTTCATTGTGCCACCATACGTCAGAAGCTTCGTCCAACTCACAGACTAGCGGCTTG
          CCCTCTTCATTGTGCCACCATACGTCAGAAGCTTCGTCCAACTCACAGACTAGCGGCTTG
          TTATTTCCACCGATCCTCCATACGTCTAATGCCTCGACAAATCCAGGAACAGGAGGCTCC
          TTACTTCCATCGACCCCCCATACGTCTAATGCTTCGATAATTCCAGAAACAGGAGGTTCC
          CGGTTATTAGAGTTCGTAAACCCAGCACCGGCGTCGTATGAACCGAGGGCCGGGGGTGCT
          TAGACTTTCACATCCCCTTAACCAACTTAAGTATTGATAGAATATCGAGCTTACGTCACA
          ATACACCCAGCGTTATTCAAGTTAATCCCAACCTTAAACGGCCCGCCCACCCGTGGCATG
          CTGTCGTTTTCACTATGTTCTCCATTCCTTGCGTCGGATCGATTGAATATATGCGGCATG

          GTTGTAGATTTGGATTAAGCGGTTTTGGGTAAGCCCTCCTGCAGTGAGAGGAAAATTCTC
          GTTGTAGATTTGAATTAAGCGGTTTTGGGTAAGCCCTCCTGCAGTGAGAGGAAAATTCTC
          GCTGTAATACACGGCCTCGAGGCACTTGGAAAGCATATTCGTGGTGAGGAGAAAATTTAC
          GCTGTAATACACGGCCACGAGGCTTCCGGAAAGCATACCCGCGGTGAGGGGAAAATGTAC
          GTTGTAAACCGAGTATAAATACGTCCATCTTCTTTCCCCTGTTAGCACAAACGGCCTTCC
          GTCGCTGCGTCAAGCAACTTAACACCATATTTCTTTTAGCGTCGGTGAAACGACACTCTC
          CGTGCAGCCCCAGGTTGCTCAGTCCCGATAGGACATTATTGTCAATAATTAAAAACCCCC
          ATTGCAGCGTTGAGCCGGCGATACCCGATCAACTGTTACCTCTCACAAGACTGGAATCTC

          TTTGTCCTAAATTTTCTGCGGTACGGAAAACGCATAGCAGGGACCATGGGGGTGGGGTGA
          TTTGTCCTAAATTTTCTGCGGTACGGAAAACGCATAGCAGGGACCATGGGGGTGGGGTGA
          TTCGCCATAAATTTTGTTCGGGGCGAAAGAGACAAGGCAGGGCTCAAGGGAGTGGACAGA
          TTCGCTGTAAATTTTGTCCGGGGCGAGAGAGACATGGCAGGGCTCAAAGGAGTGGAAAGA
          CTGGATCTCGGCGTTGACCTTCACGGGAAGTACCCACAGACAAACGATCATCACGGGGTC
          CGCGATGTGGAACTAGTTCACGATACTAGGCACATAGTACCGAACGTAGTAAATAGAAGA
          CTAGGCGCCGATGCGCTCCCATCCAAAGGCCCCTCGGAAGAGATTTTTCTGGACTGTAGA
          ACTAACCTATGTTCGGTTCACTTAGATTGTCAATCTAAAACGGTTGCTCGCGATAATGAC

          AAACCTGTGGGTTCAAACACCCAGCATACATAAAATAAAA
          AAACCTGTGGGTTCAAACACCCAGCATACATAAAATAAAA
          AGACCTGCGAGCACATATTCTCAGGATTTGCCAAGGACAA
          AGACCTACGAGCACATATTCTCAGGACTAGCCAAGGACAA
          CGTATTTTGCGATAATGTCACCGCGTTCGGGAACCGGTTT
          CGATCTTGCGGCGGACAGCTCTGTTGCGCACCATGAGCTG
          AAAGGCAGATGGACAGATCCTTGGATGGTTCCATTCTTAA
          CGGTCTCGCCGAAAACCCAGTCAAAAGCCGCTCGCGGCGT

