 8 1000
t1        ATTATCAACGTTTGGCCTACGGTTGTTGTCACCACGGCCTTGCCGGTCGCGCATCACTTT
t2        TTTAACACCGATTGCTGTAAGGTCGATGTCATCATAGTACTGTCTACCGCGCACTACCTG
t3        ACTTAATTAACCCAGGGCATGATTGTCGTCACCTTTGTTCCGTAATTGAAGCATAGGCTA
t4        ATGCAACCCCCCGGTTGCGCACACGTAGCCATACCCGTCTCGCAGTTCAACAACAATCCG
t5        CGATAGCTTGAGATTCCTAAGGTTGTCTTTACGCTAGCGGTACAACAGATTCATAATATA
t6        TGTTAGCTTGCAGTTCCAGCGACTGTGTCCACTCTGTTGGAATAGTAGATGTATGATGCA
t7        CGATGGTACGCAGTTCCACCGGCTGACCCCTCCAAAACCGAATGTAAGAGGCGTGAAAGT
t8        CGGTGGTGTATGGCATGCACAGTGTATTCCCTTTTGATAGAGCTACCGACATATAATAAT

          AGATAAAGTCGCGGAATTATGTTTTCCTTGATTAATGTTCCTGTAGGTGGGTCCCACGAC
          CAGCGGAGCTAGAGAACTAGACTGTCTTCGGATTCTGTACTTGTGAGTTAGTGCCTCAAT
          CGCCGATCCAGCGGCCCTCATGTGATTCGGGGCAGTGTGTTCGTGATTAAGTTCTTCGAG
          TCGTGTGATAGCGGAACCGGCCGGACCTCGGTCAGGGCGACCGTTCTCTAGTCAGTACCG
          GGGTACGACCGTATAAATGATTCACCCAAGCATATGGCGGTGGCTACAACGCGGACAAAG
          GGGTACACACGTATAATTGATCTGTCCGAGCGTTCGGAGATAGTCATCGCGAAAACTAAG
          TGGTAGGTCTTCGTTTTAGGGTTGGCAAAATAGGAGGGGGTAGCCAGTCAGCGCGTCGAA
          CGACAGGCTTTCATCACTGGTTCGCAGAAGAATACGAGGGTGGTTGGTAATCGCTTTGTG

          CGTCTGCTCCCATTCTTCAGTTAGTACCATGAGTAAAGTGCCCGCTGAGCATCCCGGAGT
          CGCCTGTTCTTATCCACCAAGTGGCGCTCTAACCGACATGCCTCTCGAATGTCCAGGATC
          GAACAAACGCTAATAAACCGTTGTCCTCCCATGTTAAATTTGAATTAATGGCTCCCGATC
          GGCTTATATCAGTTAAACAATAGGAACCTTGTGTCCCCCCCTCGATAGCAATTCTTGTTT
          GAACGGCATTTGTGGCGGGTCCGAGTAAAGTAACCACTTATTCGCTGACCCACTTCGCCC
          AGATGCTATTCGCGGGGGGATGGGAAACAATGGCCATTGATCGGCTGCTCTATTTCGACC
          AAAATACATTCGCCGCGTGGTATAAATCACCGGGAATCGGCCCGAAAGTGCCTCTCCTTT
          AGATATCCTTGGCATCGAGGCGGAAGTCCCTATCAATCGATCGGCCGGAACCTTCTCTTT

          AGTAGGGTGCCTTTGGTCGAGAGAGATTTCGTGTGCGCAACGTTGCGCATCAGTATGACG
          ACTAGGAGGCCTGTATTCGCGTGAAATTACGCGGGAGCCACCCCCCGAACTAAACTCACG
          AACTAGGTGTCTTAAGCCTGCCGAGTCTCCGTGCTTAACGAATTCGGTTCCAATTCTGCA
          AGTAAGGCGCTCATACTTGCGCGAGGTCTTGCGCTAGGTACTCTATCGTTCAGTGATGGC
          CGGCACCTGACTCCGACTGTAACGAAATGAACAAAAGTTGCGCCAAGCTCTGGGTCAACG
          CGGGTTATACGTTAGCATGGGCTGAATTTCTAGCAGGTCGCGGCGGGCCCTCGGCTCGCA
          GATAGATTGGGGGTGGTTGAGTTGACCTCCGTGCCGGCCTCATGTTGCTCAGGTCTTTCG
          AACAAGACGCGGGTAATGGATTAGGTCCTTGTCCCAACTTCATCTCATTCGGAGTATAAA

          AAGGGCGTGCTCGGGAACGCGATCTCTCCGCCTGAGACGAAGCAAGACACCGCTCGCAAA
          CAGGGGTCGTCCAGCAATGTAAGCAGTACGCCTGAACATGAGTAAAGCATTGCACGTCCA
          CGAGGGACATTGGGCGTAGCCAACGGAGTCTTGAACTCGACTTGCAGTACAAGTTGTTGA
          CGAAGAACCACCGAAAATGTTAATAACCCCCTCGCGCAGCTGCAGGTTTTGCTTGACAGC
          GGATAAGCCGATATCGACCTACGGGGGATCTTTAAGTTGACTCGGGTTCCTAATCGCTCG
          GGATTGGTTGATATTCACTTAACGGGGCTCTTCCCATGAACCTAGGCCACCAGTTTCTCT
          GGGTAGGCTGATGTAGTCCGACATGGTTTCGTTTAGTAGGCGAGAGGCCCGAAATATTCC
          GAAAATGTGTATACAGACCGCAGATGCCTCGTTAAGAAGGTGACGGCTACCGGCTGTCCT

          AATGTAGAGTGTGCCGTATCACACTCCGGGGACTATGTTAGAGCCATGGTCTTTAGATCT
          ATAGATGAACGTGTCGAACGCCGTAATGGGTGACGTACTGGAGTTATTGTCCTAAGTTAA
          AACTTTTACTGCGTTGGGATTTACTCCGTATACCAACTCAGAGCTCCGACGCTCACCCCT
          AGAGCCTACCGTATCGAAATTTGCCACAGGCAGTGCCCGGAAGCCACGATTACGACTCAC
          TAAGACTATTTAGCATGTGGTCGCTGTAAGTTAGCACTTGTGGCCAAGGGTGCGCCTTTT
          CAAGACTGTTGAGACTTTGGCCGTTGCACGTTAGTACTCACAGTCGCGGGAGCGTCATCC
          CCCACTTTTTGCGTTATAAGCCGTCGCGTGAGAGCATTAGAGGCCGCGACGTAATCTCAC
          AATGGCAATGGTATTACTCGCCCATACACGCAAGTAAACGAAGTTGTGGTGCTAATTCTC

          CGGTAGGTCTCAACGCAGGGCTAGGCCATCTCCGTGACGTCGTTTACTCCCTCTTGTCAG
          TGGCCGGCTCTCATACTGGCTCCGATTCCGCACATTACGGTCCTGGCTGCCGCTCCTCAG
          ACTTCACGTCTCAGGCAGGCCGTGATCACACAGCTGGGCCTCTCGGCTTACGCAGGGTCG
          CCTCCAATCTGTATACTGCTAGATGATTAGCCAGCGACCTGCCCGGTCCCTGTTAATCTA
          CTTAAAATCACTACCCATCTGATTACATGTAAGATGGCTTCCTTAGTCATCGAGATTAGC
          TCCAAAACCCCTACCCTGCTCATTGCCTTTAAGGTGACTTCCTCCGCTCTAGTGATTGAC
          ATCTTACCGGTCAGACAGTCTAGGACGATTAACTCCCTCCGTCAAGCCGCTCCAAATGAC
          CTCATATCGCTGACTCAGCCCAGTATCATCGGTTCCACGCATCGAACAGGTACAAATGGC

          TACCTAAAATGCTCTGAATCAATGTCTAGACACGAGCTCGGGATTCCTATCCGGACGTAG
          GTCCCAATGCTCTTTGAATTAACGTCTCAACACGCCGTTGGATCTTTTATCAGAGTAGAA
          TGGCTATCCTGCGAGCCAAGGATACCCCGACCGTTACACACCTTCGTTAGCGTAATGGAC
          TATCAATCATTCCCATCATTCACCCCCTCATGCCTGTGGGCGTCCTCGATGGGGAACAGT
          GAGCTAACCTTGTTTCTTTTTCCCTACCGGCACATCAAACTTCCATCTGGCGCAGCAGTT
          TTTCCAATCCTGTCACTTTTATTTTACAATCTCACTAAATTCCTACTTAACGCAGTGTTA
          TTTCTGATCTCACTTATCATGGCAAGCAAATAGGGTTTATCGATTTCAATAGATGCCGGC
          TCTTCAACTCCTTTCTTCTCGGCTCACAAAGAAACCTCACCGATTCAAATAGAAGCCGCA

          CGACGTTAGAACTCCGCACCCAGCTGGTTTTTGACCGAGGCTAGGTGGCCAATGAATCTG
          CGAAGGCAGACGATTCAACTCAGCCGAACTTCGATAGGTTTTTGGAGGCTATTGAACCCA
          GTTGGCTCGAGCTTCCTAGTACGTTGGGTTTTGGCAGTGACCTTATAGAAAAAGGGTGAT
          CGGGGACGGGATCTTCTTTTAGATTGGATCCCGACATGTGCGCATGGACGGAAAAGCCTA
          TGTTATTCTTGTGCAGGTTCTAGCAAACGTCGCGTATATTCATCACAGGGGGCACTCTTA
          TGTTGCTCTCATATCCGCCTTTCCGAGGATCGCGTATAAATACAACACCGAGCGCCCATG
          CCAGGACGTGGCCCCGACTACTGCCGGGATACTGTCCAGATGTCCTGATAGGCTACTCTG
          GACGAAATTATCTCGAAATCTTGTCGAGATATTTAGCAGACGTTACGGCAAGCGTCAGCG

          GAATCTACTCTCTGAAGAAAGCTCTGAGTCATGCTCGCTTAGTTCAGAGCGCATCGGACA
          GATGCCGCCCTCTATACAAAGTAGTGCCAAGTGTAGACTCTGCCCTGAGCACACCGCTTG
          GAGCCCGCTTCGCATATCAAGAAGAGCGCCACGAGTAGTCTCCTACAAAAGAACTGCGCG
          GGAATCCGTCCGCGTGTCAAGTACAGATCTAGGTTCCGTCGATTCTATACCCACCGCAAA
          GTCCCCCCTTCTCTGAAGCAATGTGGCTAACTACGCAGCTAAGGCGGCACGTATTTTGTA
          GTTCCTTTAGTTTGTACGCACTGTAGGTTTCCACAATATCAAGGAGGCACATCACGAGTA
          GACCGCATTATATGGGATTTACCCTAAGCTTTACGTTGATCGGCTCGTTGACGCGTCGCG
          GACGTTATTATTCGGATTCCACCCCAGAAATGGCGTTGTCAAGTTAAAACGTACGACGCC

          TGGGAGGGTTCGGAGCTATAGGTGATGTGGTCCGTGCCATGCCGGGAGGGTTGATACCCA
          AGCTGGCGTTCGGTCCTATAAGTGATAAGGTCCGAGTGGTCTAGAATGGCTAGGTATCCA
          GGCGCAAGCATGGGAGTATAGGCGGTAAGGCCCGCACGGCCCAGGTAGTCACGGACGCCA
          AGTTACCGCCTTGGAGCACCGGTACCAGTATCGGATCAATCCTGGGACTCGGTGTTACAA
          AATACGAACTCGGCATGAACGGCGGAAAGACCGCCTGCGTGCCGAGACTGGTTGATACAA
          AATACAGACTTGGCGTAACAGGCGGAAGTTGTCCCCCTGTACCGGCAACCGGTAGTTCAT
          CATCATCATTCGCAGATAAAGCCAGCAGAAATACTCTCTAGTTGAGCTTGATAGCTTTAG
          ATTCGACATTGGCAAACGAAGGCAGCAGAGACACCCGCGTGTTGAGCTTGGAAAATTCGG

          CGGACGTGCCGGCACAACCAATGCGGTCAGGGTTGCTCTTTTCACCGGGGCGCATAATGT
          AAAGTGAAGAGACGCCGCTAAATAGGCTAGGATCGTTTTCTCCCCTAGGGTATGCCATGT
          AAGATGCAACGGCCCACCTTTCACAGATGAGGCTGGCTTTTGCCTAATGGCGCGTGCCGG
          ATGGTGAATCGTTGCCCATCCTTCGACAGACCAGTTTATGTCTTTCGTGTCGAGCATCGA
          GTGACGTAGCGAGGACCTCAGACCAACCGGGGCAACAAAGGGACATACGAGAGGCACCAG
          GTACTGGGGTGAGGATTGGAGGTCAGACGCATTAACACCATGGTTTAGGAAGGACCTCGC
          GCCATGGATCATGTCGCACGTGCCAGATGGGATTAGGATGGGGTCCATGGCCCGTACCAC
          GCGGTGGAACGCCACCTCCAACCGCGGTAGACCTAGGATGGAGCTCATAGCCGGGATTCC

          GATGCGTACTACATTTAGGATCTACGCAGGACCTAGATTGCCGGCGCGGCTATCACCCGG
          GAGATGCGCTGCATGTGGGCGTAGGACAGGACCTAGTGCGCCGGTGTAGGGACTAGCAGG
          GAGACAAGGAGTACCTGGGCATAGCCTAGAACGCGGCTTGCAAGCGTATGAACCAGTTAA
          ACGATAGGTTCCATGTGAGTGAAGTATCGGAAGAGGTTCAGGGGCGCAACAATTGGCTTG
          GCAATTGGTGACCTTTCAGTCATATTAAGGAAGAGGCGCCACTATGCCCAGACTATAGAG
          GTAATCAGTGGCATTAAAGTACCATCAGGAAAGGGGCGCGGCTATACTCAGACTATAGGG
          GTCAATAGATTGAATCCGACGGCGCTAGGGTTAAAGAATGTACGTGCACAAAGCTCTAAG
          ATTACTCGGGCCTATCCGACAGTACGAGAGACAGGTAACGTCCGAGCACAAAGCTCCAAG

          TCACCTGTAACGTTCATATCCCAGCGTTGAGATACGAGCCTCTCTATATTCTCGCTCTCT
          CCTTTAATAAAGGAGGTCCCCCTGCGATGAAGCACGGGCTCAACCGCAGTCACACCCCCT
          TCCCTTGGGAGGCACATCTACCAGAAATGGCTACCGAGTTTCACTACCGCACCATTTCCC
          CACAGTGACCAGTCCACGTCCCAGGGCTATATTGTTGAGTCTCCGGTAACCTCTCCCCGA
          GATCCTGTCGGGTTAATCATGCGATTGTAAGCTTTGTAACGCCGTAGAGCAGCTTTGCCG
          CTCTCAGTCGTGACAGTCACCGAGCTGTAAGCCGCACATTTCTGTAGCGTGGATTTACCA
          GCCTGCATAGAACTTGGTTTCGGCATGAGAGCTTTTTACTTCCACGTAGCAGTTCTGCCC
          GTCACCGTAGGGCTCGCGTTAGTGACGTAAGCCATGTTACTCCAGCAGGTAGCTTTGCCT

          GCCCTCTAAGTCGGCGAGGATAGAGGTTGTGATGGGTGAACCCGAATCGGAAATCAGTGG
          GTCTTCTGACTAAGCGAGAGTGGATGCTGGCAGAAATGAACCCGTAGCGTTTGCCCCAGG
          ACACGCTAACAGGGCAAGGAGGTATGGCAGGAAAATGAAATTCGGGAGGCGGATACTGGG
          GTCCGCTAACGGCGTCGGGATAGAGGAGGAGAACTTACGACCCAGATAGCGTTCACCTCG
          ACTCCTCGCTCGTAGGGTGATAAAACGACTACCCAGGCTTCCACATACATAAATAACTTA
          GTACGCCGGCGACAGGGGGATGTGGCGGTTATACATTTATCCCAGCCCCTAGCCATCTTA
          GCCTTTTCTTAGAACAGGAATGGTGAGGCTGCATCAAAACTTTCAACAACCTGAACCGGC
          GCTTGTGCACCGGATAGATAGGGTAATGTCCTACAAGGGTCTCAAACGGCATGGATGCGG

          CATTAGGGCATGCATGACACGTGTTAGCGCGGGTCGCACACCCTGTAGCTGCCTAGAAGT
          CACCAGGAACTATATAACGTACCTAGGTTCGTGTGCTACACGCTGTAGAAACATAGCAGC
          CGTTGGGATCTATGCAGCGAACGCGGGATCCATTGGAATACCCCGGACCTGTCGCGAGGG
          CATGCAGGACCCCCTAGTGATCGCTACAACAGACGGTTGAGCATGACCGGGCCTAAAGGG
          CGGGAATCCTGGAACACCGCAATTGGAAGACAATAGCACGTCTGGTTGCTCCCGAGGCGC
          TGTGAAACACAGATAACTGCGGTCAGAAGACAATTAGTTATTTAGTTTGCCCCAAAGAAC
          TGCAGTAGTCCGTATGCTGCCTCCCGCTTAAAACCGTATCGCCGGTCGGCCCCTGGGTGT
          TAGGGGGCCAAGCATGCTGCTGCCCATGTTGGACCTCAATCGCACGCGGCCCCCAGACGT

          CTTGCGTCTTCGGTCGCTCCTCCACTCGGATAGAGCCCGC
          TCCCGTCTCCCAACCACTCATTTAGTCGGACATAGCATGG
          TAGGCCGCCACGTCCATCGGTTCATCAGTCTATCGCCTGC
          CCAGCTCGACGGGTTGCCTCCGTCGCAGAATGTCGCTTGG
          TGAACATATCCCATTAACCGTTGTCGTATGCGTTGCTGAA
          CGAGCATACCTGCCTAACTGTCGAGCCGTATATTGCTGGA
          CATGCTTTTGTCCGAACCTGCTCAATTATACGTAGGTAGA
          CCGGCATGAGCCACAACCTGCTTAGTCCTAGATTGGTAGC

