 8 1000
t1        GGGAGACTTCCCGGAGTGAGACATTCGGTGAGCTACAATATAGCCAAATTACTCGTCATA
t2        GGGGGACCTTCCGGAGTGAGATATTCAGTGATCTAAAATTTAGCCATGTAGCCTGTCATC
t3        GGGAGCTTCCTCGAAGCAAGAACATAAACACGTTGCACTATGTTTTGATGATCGACGATA
t4        GAGGGGACACTTAGGGTGAGACTTTTACGAAGCTAGCCGCTGGCACGGTAATCAGCTACA
t5        GGTGGACACTTTTGTATGAGACAACTCGCAAGTCGATCTATGGCCCGGTATCACGTATTA
t6        GAGGGGCTTTTCGGATGGGGGCATTTCTTAAGCTACTACATGGTTCGCTAATTCACTATT
t7        AGGAGCCTTTCGGGAGCGTGAGTGTCAACCGTCCAAACAATGGTCTGTCAAATCTAAGCG
t8        AGTGATCCCGTTTGGGAATCAGATTTAGCTAATCTGAATATAGTCCACAGCTTGGCCAGG

          GAGTTACATCGCGCTGAACGAGCTCGGTTATGAATTCCCAATAAATCTATTGCGTCCGGG
          GACTTGTACTGCGCTGAACGAGCCCGGCCATTCGTTGCTATCGCACTTAATGCATCTGGA
          GAACTGTCCTGCGTTAGTCGAGCTCAGTTATTTCCTGCCATTGCGCTAAACTTATCAGGT
          GAATTCTATCGCATTAAGCGCACCCGGCCCTCCATTCCCATCACGCCTATCTAGTCTGTG
          GACACTTCCTGCACGGAGCTAGTTCGGTTGTGTGATTTCGTAGCGTTTAGTTCACTTGGG
          TAGGTATACTGTATGAGGCGAGCACAGTATTACAGTCTCATCCTATTCACCGCACTCGGA
          GGGTTGTACCTCACGGTATGAATCCTGCCTGGTATGGGCGCCGCGGTTACCGCACATTGT
          GCCTTTTTGCGAGTCGACCCAACAAAGACCTTCTATCTCGCTGTGCGCCAAGCGAGTTCT

          CGCCTGATCCTGCATAAACAGGTTAGAGTGCCCTACATATGAAATCCCAAATGTTACCTC
          CGCCTGATTTTGCACAAGCAGGTCGGAGTACCTTACACCCGACATTCTAGAAATCATCTT
          CGCCCCGTTTCGAATAGGTAGGTTTGGGAACTCTTCGATCGATATCACAAGTATTACTGC
          TATCTGTTCTTGCACAGTGAGTTAAGGGCCCCTCATACTCAAAGCCGCGGCAATTGTTCC
          CTCCTGATTATGCATCTCTAGTTCCGCGTACTTTGCATTTAAAGCGGCCGGAATCGTCTT
          CACCCGACTGTGCATAAGCAAGTCCGGACGTCATGTAGTCGAGGCCATAGGGGTCATTTT
          AGATTGCCCCTGCGTGATCCAACTCGAGTGCCCGCACATTAAAGCCCTAGGAGTTGTATT
          CTGCAGGAGGTCGCCAACTATGCACAAGTGTCCTACATTGTCCGTGAGGGAGATTTTCTT

          CGAGTGTTATGTAGGGTCCCTACGTGGCCAAATTCCGTTGCCCCATTACCAATGTGATTC
          CAAGCATTATGAAGGGTCCTTTCGTAGGTAAAATGTGTCGCCCCATTATCAACGCAATCC
          TAGGCATCGTCCAGGATCCTACCGTATTTGGAGCTCGACGCCCTATTATCAGCACGCGAT
          TAAGTATGGTGTAATGCTGTCTCGTGACCAAAATCTGCTGCCACTTCAACAGCACGACCT
          TAGGTTTGATATAGAGCTTTGCGGTTCCTAAAATCTATTGCTTCGTCCCCAGCATGATCA
          TAAGCATAATGTAGAGCTCTCTCGGCTCCAAGTTCCGTATTCCCACTACCAGTACGGTCT
          TACGGTTAATGTTCAGCCGTACTCCGGGTCTGAATCGGGGCTTTATTGCCACGACTAGCC
          TCTCGTATGGGTTCGGGCGTCTTCCACCTGCGACACGGAACTAACCCATAGCGGATGAAG

          GATGACACTGACCTAGCTCCTTTGATTCCCAGGGTTTACCCATTGTATTCGGTCTGAGGA
          GAGGATACTGACCTGGCTCTTCTCACTCCCGGAGTTTGCCCATAGTACTCAACTTGATGA
          GAAGACACTATCCGAGTCTCGTCACTAACCGGAGTACGTTCGTCGTACCCATTCTGATGA
          ATCGACACTGGATTTGCCCTTCCAATGGTAGAACACTGTCTGCTGTATCCATACTGATAC
          AACGCTACTAATCTAGCTGCCACAATGGATGAAGCTTGACATTTACGCTCGTCCAGATGA
          GACGTCGCTTACCTACCTGGTTCAATAACTAGAGATGTTTCGCCCTTCTCATCCCAGCTA
          ATGAATACGGTTCTCGTTTCGCCAACACCTCCAGATTCCATGTCGCGTAAGTGATGTAAT
          AGAGAAGGAGGAGTTGCAACAACTACAGACATTCTCGTACTGTTATGCTACTTTTCAAAT

          GCAATAGTAGTCCACCGTTGTTGGTCCGACACACTTGATTCTACAAGAGCTTCTTTGAAT
          GTAACATTTATTCACCGCTGTCTGTCCACAACCCCTGATTCAGCAGAAGCTTCTTCAAAT
          GTACAGTTAGTGATCCGGCGTTGACTCGAAGACTCCGATTCTTTGAAAGCCAATTCACAC
          CCATTAGTGGTTTACCAGTGTCGATGTGAGACCCTACGTCCCCCGGAAGCTTTCATAAGT
          GTAGTAGAGGTCTATCAGTGTAGGTACGAACCCACTTATTGTTTGGAAGCGTCATTAAGT
          GTCACAGTGGTTAACCGGTACCGATTCGTATTTATGGATTCCCCGTATGTTTTTTTAGAT
          CTTATAGGGGTTCCCCGGAGTTGGATCGAAATCCTCAATTTACCGGACGACTCTTAATAT
          TATCTGGATCCATATTGGTCGCGGAGTTGTACACGCCCGTCGTCCTCCCGCCATCCTATC

          GTACATTTAGAACTAGGGCCACGACTTCCCCTGACGTACATCGTCCCAGCCTAGTCCCGA
          GTATATCTGGAATTTGGGTTATGACCACCCACGACGTAGCTTGTTCGAACCTACTTCCTA
          GCACGTTTGGAACACGGGCTACGCCTGCCATGTGACTAACACGTGTGAGCCTACCTCTGA
          GCTACACCAGGATCTGGACTGCGACCGTTGCGTCTATCCTAAAACCGAGCCTTCTCCCCA
          TTACGCCTAGAAACTGGGCTCCGGCCGTCGAGCCTGCCCTATGTTAGGGATGATTTCCGA
          GGGCGTTTAGAGAGTAGGCTAAGACTGCCGAGTACCTACTGAGCCCGAGCATGTTTCCGA
          GATCGGCTTGAGGTCGGGTTTAGTTTGTCGAGTGTGTATCACAATAATAGCTTGCCTCGT
          GTAAGCTGATAGATGGGTTACCGTTAATTGCACGTAGGACGAACGTTTATTTTATTATGG

          CATACGCGAGAACACATAGTATGTGCGATGGAGACGTCAATCGCAACGATATATGGGCTA
          CACAAATACGAACACGTGGTTTGTAAGATTGAAAAGTCAATCGCACCGCTGTCTGGTCCA
          CATGCGTTCGAACACACTGATTGTAAGGAAGAATTGTCAATCGTACCTGTGTTGGGCCTA
          CGTGCGCTCGAGGGCCTGATCTGTACGACTGAATCGCCACTCCTATCGACGCCTAGGCTA
          GACACGTACTGTTACATGACTCGTACTACTGTATGCCCAATCTAATCGGTGTTTGGACTA
          CAAGTGTTTGAGCACGTGGTTCGTGCGATTCGGTTATTAACCGCACCGAAGGATGAGCTG
          TGATCGTACGTGCACGTGCCCCCATAGACTACGTTACCAATCGAATCAGCATTTGGTAAA
          CGCAGGGACGAACGATTTGCACTCGAAGCAGAGAAGCATACCAAGGTACCAAATGATATG

          TACCTTCCGATAACGTAGTATAAATTGCCCCTACTCAGGACGGGGGACGACATGCGTCCT
          TATGTTTCGATCTCGTAAAACAAATCACCTTTGACCAGGACAAGGTACGACATGTGAATT
          AACCTTTCCATTACGCTCAATGATTCGCGCTCGGTCAGGATGGGGAACAGCACATGTTTT
          GACCTGTTGATTATGTCGAATCTATCCCTCTTGATCAGGACCGCAACCGGCACATGAACT
          CACCCCTCAACTACGTTCATCTAGTCGCTCTATATCAGAACGAGGAGCGACGCATGGATT
          CATCTGCCGCCTGCGTCATACAAATTCATCTTGATCTGGACAAAAGACGATCCATGATTC
          GAACTGTCGACATCATCGTACTTATTGTCCCTACCTACGATGTGGAATCGCTCGTCCAAC
          TAGTTTAGAACAGTAACGAGGTTGCTGACGAGACTTAGCCGAAAATGCACCATTAGCATC

          CCAGTAATCGGTGTAGAACCCATAATCCGGAATAGGTAGTACTTGGCTATAGTTCCCTTC
          GCGATAATCGGCGCAGCGTTCGTGTTACGGAATAAATGGCACTTGGTTGTAATTCTCCTC
          TCAGTCGTCGAGGTAGCGGCGGTCACTGCACTTTATTGGCACTCTGTTATAACGCTTCCT
          CCAGTCAGATAGTCAGCGGTTGAAGTCCGAGCTTGTCGGCACCTAGCTGTACCTCCCCTT
          CCAGTTACTCAGGTAACGACTGGAAGCCGAATCTATCAGCATTCAATTGAAACTCTCCTT
          TCAGTCATTGCGGTAGCGGTTGCAGTTCGAATTCAATGGCACCTTGCCGCAACTCAACCA
          TGAGTCATCGGGGCAGCAGTTGCACTTCCGAGTTGTAAACATATGGCCGGAATGCTGATA
          TTAGCTGCTGCCGCGGTCAGAGCCCCCCGCACTAATAGATCGCTAGCAGTGTTTCTTGAA

          TCAGGCTCATTGTCACTAGAAGCGTGCGGGGCTACTCGATGGTGAGATTCGACCGGATAC
          CTAGGCTCATTGTCGCGAACGGCGTGCGGAACTAGGCGGTAAAGAGATCCGGCAGAAGTC
          CTAGACTCCTAAACTCAGGCAGCATACGAAAGAAGACGCGCCAGAGGCTCGATAGCAGTC
          TCGCGCTCCCTGCTTAGGACGAGGGGCGGAGTTAGATAATAGGGCGGTTTATTAATAACC
          CCTGAAGCATGACTAAACATGTTCACTGGAGTTAGCTGATGAAGAGATTCGATACATCCT
          CTAGACTTATTCCTTCACGTGCTATGATGGCCTAGGCGGCGGAGAGATTCGGCAGAAAGA
          AAAGCAATCAGACTTGAGATAGTCTGTGGGGTGCGCTAGCAGCAGAACCGGATACTCGTT
          GCAGTCATGATGACGAAGGCAGTCTAATAATTCATTAGCCGGAGCGTTTCGCCATTAACT

          AGGAAAGCGCAGTCCGGGAGTGATTCACAGACTGAAGCCCTCAGACATTATCTTCCGGGA
          CGGAAAGCTGAGTTCGTGAGTGGTCCACCAGACGATGCCTTCAGATACTATACTCCTGGG
          GTGAGATTGAGGATCCTGAGCGTCAAGCGAAGTGAAAGCGTCAGGCACAAGGCTGAGGGT
          AGGAAATGGATGTCCCTACGCGAGACCCAATACAGAGCATCCAAAACCTATACTCCAGGA
          AGGACGTCGAAACTCATGAGTAATGTATGGAACAACGCCATAAGATACTAGGCTTTGAGA
          ACGGTACGGAGGTTCCAGAGCGACACGCAAGGCGCCGTCATCTGACGTTAGGTACCGGGT
          CATCAAGTGGCGTACCAGGACGCGGTAAATAGAGACGACCACGAGTCCTAGGCTGCAAGA
          TAGAACTAACCGGGAGTAAATGGGCTACGGGAAGCTGCCAGTGGAAGCGAGCGATTGAAT

          TGAGCAAATTTTAAACCCTACAATTTGATATTTATGAAAACGACTTCATAAACGTGTTCC
          TAAGCTAACCTTAGACCCTTGAAGTTGTGAATCATGATATTGACTTCATCAACGAGTACC
          CGCATAAGTCTCAGACTATAGAGGCAGATAGCCATGGTGACGACTTCACTAACTACTTCC
          AGCACAATCCTTAGACTCTAGAAATTGATAGCCGTGGGGACAATTCTGTTTTCTAGCTTC
          CGAGTAACCCTTGGATTCTAGTTGTTGATTAGTTTGGAGGCGACTCTTTTAACCAGTTCC
          TGCGGAAATCTTAGACTCTAGGGCTTGACAATCATGGAATCGAGTCTATTACCTAGATTT
          ATCTTGTATCATGAATCTTAGGGGTTGATTACCATCGAGGTGGCCCTGTAAAGCTTACAC
          AGCTTCACACACGTGCAATCCCGACAACGTGTGTCCAGGATAAATCCACTTCGACTAGAT

          TGTAGGTTATTCCCGCTTATCTAGAGCAGCACGCCTTATGAATGAGACTACTAAGGTAGG
          TGGAGATTATCCACCCCTGGCCATAGCAGCACGAGCTATGAACGAGGTCAGAAATGCAGG
          CTCGGATAGTACCCTTTCGACTAGGGCAGCACATATTACCGGTGAAGCCATAAGCGGAGG
          CGTATGGCCTCACCCTCGGAAAGGGGGGGTACGGATTGCCCAAGAGGCCAAATGTTTGGG
          TCTAGTCCTTCTCGTTCCGACAAGAGCAGTGCGGATAATTGGAGAACCCATAAGTATGGT
          CGTAGATTTGGCTCCACTGAAAAGAGCCGTACGTATCCTCAACGACGTTTGGAGTCTGGA
          TAATAAGTTCCGCTTTCCCAATGATAAAGTTAGTCTTCTCAGTCAGACCAAAGGTCGGGG
          TGGTAATTTTACTCCTGCCTAGCATCTAGCTAACAACCTCGAGAATTGCGGTCTGGACTT

          ATCAGCGCGGCGACGGCAGTCCGCAGCGGCATCAAAGGGCGATTGTCGCGATGATGAATA
          ATTAGCGCGGCAACAGCAATTTGTCGAAGCACCGTAGGGGGATTGTTCTGCCGCCGATAC
          AATTGCGCGGTAACCGCGGTCCCCCCGGGCACCCGGGGCAGCTTGCCCCAACGACGTCGA
          ATAAGTGTCGCGACAGAGGTCGGTAGGTGCACTCTAAGGAGGTTGTTGCGACGATGAAAA
          ATGAACTCGGCCATGCCAAACCACTGGAGGGGCTATAGGCGATGATTATACCGCTTGCAA
          CCTAATTCAACTATGGAATGCAGCAGGGGCATCCAAAGGAGATTGTTGCGAAGGTAGCGG
          AATAAGGTGATACCCGTGGTTCATCGAAGATTCAAGAGGACGTTCCTGCTCAGACGATGG
          ATCACTCGGGCATTTTACAACAAGCGATGCAGATTCACAAAAGGGGTGCATAGTCATTGA

          GCTTAATCTGGGCCTGGGTTCCACGTAAGGTGTGGTAACAGATGTGGATATCGGCGATCG
          ACTTAAATCGAGCCTGAGATCCACATAAGGTTTAGAAACGGACACGGAAATTAGCGAAGG
          ACTTAAATCAAGCCTAAGACTCGTGTCGGGTCTGGTACCGGATGCGATGCTTGGCGCCGG
          ACCCAAAGCGAGGCTAAGATCCACGCAACGGTTAGGAACGGACGTGAAAATCTGCGCCGG
          ATTTTGATCGTGACCCTGGCCCATGTAGGGCGTGGAAACCGATGATGACGAAGGCGGCGG
          CCTTGGAACTAGTTAGAGGACCTTGCAAGTCGTGGAAATGATCCTTAATATTAGCATCGG
          ACACAACTTGAATTTTAAAGCAATGTCAGGTTACGAAACGGACGTTAAAGTCAGCACCGA
          CTGAATGAGAGGCAAAGCAGTCCTAGATAATTTCTCTCCCATCGCAGCCATTAGCGCCAG

          AGCTAACTAGTGTGAGCAACCCTTTAACTCAGGGTACATA
          AGCCAATTAGTTCGAATTACCCTTTAACACAGGCTACGTA
          GGCATATGAGTGTGGACAGATCACTAGCCGGAAGAACCTA
          AGTCAACTAGTGCTGATAGCCCTTCGTCCCGGAGTACATT
          AGCTAACTAGCGCGAACTAACCACTAACCCGGGTTATGTG
          GGCCGATTAGTGCGCATAGAGCCATCGCCCCATGTCCATA
          AGCGTTTCAGCATGAGGAAGTCGCCAGCGCGCGGCCTTCA
          AGAAAAAACCTACCGGACCACAGTCGTCTGGCAGCAGACG

