 8 1000
t1        ACAACGTATGCAACCTCCCGCACATTTAAACACAGGGAGGAAGATGGTGAGATAATTGCA
t2        ACAACGTATGCAACCTCCCGCACATTTAAGCACAAGGCGGAAGATGGTAAGACAATTGCA
t3        GCGACGTGTGCAATCTCCATCACGTTGGAGTGCAGGAAGATTGACGGTAAGACAATTGCA
t4        ACGACATCTGCTACTTCTCTTAAGCCAAAATGCCGCGAGTGGGATGGTAAAATCGTCCCT
t5        TCGTCATGAACTACTTGCCTCGAGAACGAGCACATGATACTGGATGGTGGGATAGCCGAC
t6        TCCGATTGGGATATTAGCCCCGGGATGACGTGTTGGGCACTAGCTAGAGCCATCATCCCC
t7        CCAGCATGCGACGCCCAGAAAAAAACAGTTCACAGCTTTTAGAACCTTTCATCGCGCACT
t8        TCAAGAGAAGCCATAGAGCTCAACTATACAGACAGAGCTGTAAGTGGCACCTTGCTCGCT

          CTCACTGTGGTAAGCTATAGGCAATTAGGCGGCCGTGCTTAGGTTGACACATGTAATCGT
          CTCACAATGGAAAGTTATAGGCAATCATGCGGCCGATCTTAGGTTGACCCACATAATTGT
          AATCCAATGGTCAGCTACAGGCAATCTGGTAGTCATTCAGATGTAATCCCATATAATTGA
          TACCCTGTGGTAAGTTACAGGTAATACAGTGTCCAAACGGAGTTTACCCCGTAGAACGGA
          GGACTGCAAGGGAGTTTTAAGCACCCTCATGGTCGCCTGGACACAAGGATGTGTCAGCGT
          GCAGATGTCCCTGAACTCTCGAACCCAGAAGAGTGAATGGAGACTATGATACACCGTGCG
          GGACTGTGATTGGGTACAAAGCAATGAGACTAGTGTACGTAGTTTAAGCCGAACAAGCAG
          GCAACCATCGCAGATTGTAGAGGGATGAGGAACGATGACCGCCTCAAGTCGTTTTATCGA

          CCGTGAATCACGGCCAGACGAGAGGTTCCTACTCCACGAGGGCAACTCCCGATCTTCGGT
          CCGTGGATAATGGCCAGACGAGAGGTTTCTACTCCACGGGGGCAACTCCTGGTCTTCGGT
          CTCTTGACGACAGTCGGACGAGACCCTGTGACACCAAGGGGGCAACTCCTGACCTTCGAT
          TCTCTAACGACGGCCGGGCGAGAACGTTACACACCGCGGCGGTAGCTCCCGATCAACGGT
          TACCTATTGGTTGCAGGATGTGAGTACTTTAGATCCTCGAACCGTCTACTGATATTAATG
          TCGTCATCGACTGTAGCGTAAAGTCGTCTCGCCTTACTGCGGTTACCCTCGGATTCTGGA
          CTCCGGCTGACTATTTGGCGATGATATCTATCCCTGATATAGTAGCTACCAGTCAATGAA
          GACTGGTCCCGCATGTAACGGTGCGATTTTACATTGTTACCGCGCCCTGCGATTTGATAG

          TGCCTGTCAGCACCAGTTAGTGCCCCCAAATTAAGCTTAAAAACTGACGATGAGCGTATC
          TGCCCGTCAGCACCAGTGAGTGCCCCCTAATTAAGCTCAATAATCGACGATCACTGTATC
          TGTTTGTCAGCATCAGTTCGTGCCCTCAAATTAAGCCTAGTAACCGACTATTAAGGTGGC
          CGGTTGTGAGAGCGCGCCCCCATTCCTACATCCAAGTTAGAACGCAACGGTCGGTGTGTC
          TATCCGTCGGCCTCTGTTCCAGTTGGGGAACCCGACGTTTCGGTAGATAAGAATTACCTA
          AATCCGTCGGGTGGACATACGTCCTCTCGAGGTAGTCACGAGACAAGCCGACACTTTGTT
          AGGCTTTCAGATCAGGTCTCCTCCATCGCGCATGACTCCAAGATTGTTACCAGGCGCGGC
          TGTTTGACATGATTTATATTAGATCACAGGCTTTAGTCGGAATGTGGAGCTTAGGGAGGC

          CCCGGGAGCCAGTGCCAGCTTTTTATACGCCCACCTAGGCGCTCCTTACGCAATACCAAT
          CCTGGGAACCAGTGCCAGCCTTCTATACGCCCCCCTAGCCGCTTCTTACGCAACACCGAT
          CTCGGGAATCGGTGCTGGCATTCTCTACACCCCCCTGGGCGCCCCTTACGCAATACCAAC
          ACCGTAACTCAATGCTAGCGCTTGTTGCATCTTTCTTATTACAATTGTCGAACTACTATG
          ACCGGCAATCACCGCCCCCGCTTTACAACCCCCTACGGCCTTTGTCAAAGGGACGCACCC
          TGTGATCTACACGGGCGGGTTCTTCTTATATCTCCCTGCAGTAGCTTGCGACTCTCACGA
          ACCAGTGTGTCCTGGTGACAATGTCAGAATCTTCTTGGTAGTAGCGGAGGGGTTGTATCG
          CTAAGACTGTCTTGACGCTCCCTCCTGGGTTCCCAGCGGGAATGCTGAAACGTTGAGTTC

          AAGCAGGTCATCCAAATCGACGATCTTACTGCCTCGCAGTCAGGCGACGTGCAAGGCGAC
          AAGCAGGTCATCCAGATCAACGATCTTACTGCCTCGCAGTCAGGCGACGTGCAAGGCGAC
          AAGCAGGGTAATCGAATCGATGGCCTAAATGACTCACAGCCATGCAATGTGCTTGACGAC
          AAACAGCTTCGCAAGACAGATGATCCAATTTATACCCTGGTAGGAAATGATTTAGAGGAT
          TAGGAAGCCGACGATCAGGACCCGTTTCACGTCACCGAAGAAGATAGCACTTTACCCGGT
          ACAGGGTTGACCCAACATAATCCTCTCTAGGGCATCCGGCTAACTAGGTCTCTTCGGACC
          GGATCAACGGGACAGTTCGGTTAGGCATTGATAGAGCATCTGGGATTTGTTTCAGACGAA
          AAAGAAGCTGGGAATCTCATTTGTCCGAGAGTGTCCCAGACGGAGGGCAGTCGTCACGGT

          TCCTATAGCCAAGCGCGGGGTGAATCTCTGATACCCCAGCTGAGACGTCCTAGGCACGTT
          TCCAACAGCCAGACACGGGGTGAATTTCTGATATCTTAGATGAGTCGACTTAGCGACGTT
          CCTATCAGACAAGCGCGGTGTGGTATTCTGATGCCTCAGATGATTCAATCTAGTCATGTT
          TCTAATGTCTAACCGCAGTGCGAGTTTCAGTTGCCTAAGCTGACTCATTCCAGCCATGTT
          ACGAGTGGGTAACAACCCTGAGTAATTCAACTGTGAACGAAGGTCTGGTGTAGTATCTGA
          TCGGAGAGCTACCCACGCCCAGTACCTCGGGTGCTTATGAACGTCCACTGGGGTTTCAGT
          TCAAGCCATTTTTCCTGCCGGCCCTCCTTGTTTCAAGTAAAAGCTTGCCACTGTCGCATT
          CCGTACAGGAAAGTAATTTAAGAGACATAATTAGACACATGGTGACAATATGGTTCCTGG

          ACGTATTGTGCGGAGCATGTCTTACTTGGACTCGAGGTGGGTTCACAGAGTGCTGCATAG
          ACGTATTGTGCGGTGCATGTCCTACCTGGACTCGAGATGGGTTCCCATAGTGCTGTATAG
          GCGTGCAGTCCGGTGACTAGCTTATCTGGGCTCAAGATGGGGTTATGACGTATTGTATAG
          ACCCGATATCCGGAGTTTGACCCACTAGGTTTTACGATGGACACACGGCGGGTTGTACTA
          ATTCATCCTCCGCAATCCGGGCGCCCATCTTTGGCAAGGTGGTTACTGTACATCGCTTGC
          AGTAGGTAGCCGAATCCGAGTTCGCCACTTTTAATAGCGAATTTAGGGTCAATTAAAGGC
          ACGGGGCACTCGGCGGGTTAGCAGCTATAAACTGTTTCAGGCCCACAGAATCATACTTGC
          AGTGAACGATTGAAACTCTCCTACTCAAGCGGTAAGGGAGGATAGAGACATCTTTCGAAG

          CATAGCGGGTACTATCGACGGTGGCTGATAGTGCTATCGAAGCCCAGCTTCCCCAAGTGT
          CATCGCGGCTACTATCGACAGTGGCTGAAAGTGCTATCGGAGCCCAGCTTGCCCACGTAT
          CATAGCCGGTATTATCGGCGCTGGCTGATGACACTACGGAGACCCAGCCTGATTATGTAT
          TGCACCTGGTTCTCTCTGTGATATCCGAACACATTATTGACATCAAATCTCAATTTGTAC
          TGAAATCGATTTGCCGACGGAGGTTGCTTGGCCCCCTCTTCGGAGGCTGTGGAATAGACA
          TCATGCTTCTGTGGCTGTACGGATAGTCGGAGGCCCTCGATTTCGGACTTAGACCGGTTC
          TCGCTACTCCTCTGCAATTGATGTTCGACCACGTTTGTCGTTCTCTCCCCGGCAATGGGC
          TCACTTAGGTGGAAATAGTGGGCTGCGCGCGCGGTACTAGTACTAATGCCAGTTGCGCTA

          TTGTTAACAAAAGCAGCTAATCCGGCGTATCTAATGGAGTGGTTTCTCTAGATTGGTGTT
          ACGGTAACGAAAGCAGCTAATCCGGCGCATCTAATGGGATGGTTTATCTAGATTGGAGTC
          GAGGCATCGAAAGCCCCTTGTCCGGCGCATTTAACGGGAGGGTCTATCTGAGCTGGAGTC
          GGCGTGACGGGACTTACTCATCTGGCGTACCTAGCAGAAGTGTTTACCCAGGTCGGACTC
          AACAAACGAGCGCCGGGCTAATCGTGGCCTGGGGTCGATTGGTCTTTCTGAATTAGACCG
          CTAACTCTTGCCTCGAGCATGCTGGAATATCGCATCAAGTCCTCACCTTCGGTCGGGATG
          CGGATCTTCATGCCTAGCGATTCTATGGATTCGGTAGGACCCCGCTTTTGGATCATACAT
          CGAGTCTCTGCGCTCACTAAATCACTACTTGGCGAATATTCGACGTGAGTACCCGAAATC

          AAAGGGCAGAGACAACATATTGCAGCTCTATACATCCTGGTGTCGAGTCTATACGGTGAC
          AAAGGGCAGCAACAGCATGTTACAGCTTCACACATCTTGCCGTCTAGTCTATAACGCTAC
          AAAGTGTAGGGGCAGCATGTTGTAGCTCTAGACATCCAAGAGTCTAATCTGTAAGGTTAA
          GGGTGGTGGATATGGCGAGTCGCGGCCACTCACGCAGTCGTTTTTAGCCCACAAACGTAA
          GAACGGTATACGTGGTAATCTGTCGTCTTTTTTGCGTTTCCTGACTACCCAAAAGCAGTA
          ATACCGTAGGCGCCAGGCTCTGTTATCCGATAGGGGAGCACTCACAGTTTGCAGGCACAA
          GGAACACGGGAGCGGTGAATTACCAGTCCTTGAATAGCAATAAGCCGTCCGCCTGCTTAG
          GCGTCAGGGTCTCGATTAGATACAAAACCGTAGAGATACTCATGAGACTTCGAATGTTCG

          CGAAGTTGAACTAATTAGGAATCAAATTAGAAAAGCGATAACTTTGTAGCACCGTTGAGA
          CAAAGTTGAACAAATTAGGAATCAAGTTAGGAAAGCGACATTTTTGCAGCACCGTTGAGA
          TTAAGTTAAACCAATCTTGAATCACATGAGAAAAGCGGCGATATTGCTGCACTTGTGAAA
          CTAGATTAAATCCGACTGGGGGCGAAAGGGTAAGGTGGCCACTCAGTGGCGGAATTTTGA
          GCAGCTCTGACGTTGGAACATTTGGGTGAGGAAGTAAGCGGTTGTACAGCAGAACTCAGA
          ACATATGGTAACTGGGAGCGAACTACTGATACATACTGCGGCTTCGTGCACTATCAAAGT
          GTCCACTAGGGCAAATGGTACTCCCGAGGAAAAATTGTTGATCCAACGGTAAATGCTCGA
          GTTCGTTTGAAATGATAGCGTCGAAGTTAGAATAACAGTCATTTTACCATCGTACACGGA

          TGTCAAATGTACTACTCTCAAAATTTAGCGGAAAACTCTACACACTCTCTTAAACACGGG
          TGTCAAACGTGCTACTCTCGAGATGTAGCGGAGAGCTCTATACACTCTCTTGACCACGGG
          TCACGAATGTTCTGCTGTTGTGAAGTGGTGGAAAACTCTACACACTCTCCAAAACGAGGG
          CCTCGCGTGTGCTATGGTTACCGGGCGGCGACACGTTTTGAATACACTCTCTGACATCGG
          TTTCGAAACCATCGGTCCTGTCAAAATGTAAAGCAGTCTTAAGGTACAATTTGACCAGGT
          GTTTGAATGAATTAGTGCCATTCGGTTGAGGAGCATTAGAAACGCACTCTTTGTGCTGAC
          AATCGAGTCCAGTTTCTACGCTACTCGGCACTGAAGTCACAACGAACCGTGCGGTAGAGG
          GCATTGTTGAGATAAGGCCATGGGGTAGTGGGATGGATCCGTTACTTTATCAGAAGACCG

          GGCGAATGGTTCCCTCCTATACAGCTCGTTCTGTAGCAATCACAAAAGTAAATACCTTGA
          GGCGAGAGGTTTGCTCCCATACTGCTCGCTGTGTAGCAACCACAAAAGTAAATATCTTGA
          GGCTAGTGGTTTCCCCCCATCTCGCTCGCTCTGGAGCCGCCACAAAGGTAAGATTAACGT
          GCCACGTAGCTACCCCGCGCACTGCTCGCCCCGGTGTGGCTCTAAAGGCAAACTTAATAA
          CACTGATAACACGCTCGCCGTCTGTTGGTATTAGCACAGTAGGTATGACGAAGCCGGCAA
          CACCTGTCACGTAGCCGTGGCTTCACTCTATTGGTACAGTTATGACATTACCCCAATTAT
          CGCTTGCTATACCATTGATATTTGCGGGTACCGGTATGGTTGCTGACGTATTATAATTGT
          CGATTTAAGGGAGTCTCGAGTCCGTGAGTGTTGTTAGGGGGAACTGGGCCGAGCTAGAGC

          TCTACTTAGGCGCCTGCGATCGCAGAACCGGGTTGAGGTCCCAACGCATACCACGAGGGG
          TCTACTTAGGTGCCTGCGATCACAGAGCAGGGTTGGGCTCCCAACGTATACCATGAGCGG
          CCTACCCATGTAACTGCTACCAGAGAATGAGGGAGGGTTCCCAATATTTACCATGGGGGG
          CTCCAATATATAGCTGCTGTAAGAGAACAAGGCAGTCTGCGCGACAGGCTCCAGGGGGGC
          AACCTAACCGTTGACGGCAGCGGTCAAGCGGGACAAGAACGCGTGATGTACTATAGGTCG
          ATTGAACCTATGGTAGCCCCCTATAACAAACGGTGCCAATTCGGCAGAAACACTGGCACG
          CTTACCTGAGCTGCCGCTTTTGCACGAGCAAAGCGCGTATTCGACGCACAGTTCCAAAAA
          ACCGAGCGCGACTCCGTCGCTCGCAGTCAATGTATCACGCCCGCCATCCAAACGGGACAC

          GTGGATCCACGCTAACAAAGGCACAGTCCTCTTGGACAGGGGAGGTGCCTAACGTGCCCG
          GCGGATGCACGCTAACAACGGCACAGTCCTCATGGACAGGGAAGGTACCTAAAAAGCCCG
          GCATGTGTACGCTAACAAAGGGACAGCCCTCTTGGACAGAGAAGGCGTCTAACATGTCCG
          ATTACTCTACTCATATTAGAACACAATTTCTATCAACAGAAAAGGCCCCCGATGCCTCCG
          TGAAAATTATTATAGGTAACAATTTGTCTTCTCGTACTACGAAGCAGCCCTTTGCGGGCG
          CAAAGAATGGCCTGAGGAGGACCTATATTTCTTGAAAAATAGAGAAATCACATGCCGCAT
          GGTTGTCCGAATTCACAGCGCTTGCTTTTAGCCGCACTGAAGAGGGTTCTCATGCGGACT
          GTACCCTCACCTTCAAAAGGCGAAACACACCATAGAGTGGACGAATCGCAAAAGTGGGCA

          ACTAATTGTGCTAGTGTGGCCTTGCAAGAAATGTAAGAGG
          ACTAAGTGTGCTAATGTGGCCTTACGAGAAATGTAAGAGG
          ACTCCGAGTGTTAATGTAGCCCGCCGGGAAAAGTAAGAGG
          GATAAAAGCGGTAACGTAGCCCACTAGCAAGAGTAAGAAC
          GGCACGTGACGTTGCAAGGCCGTTGGGCCGGACTAAGCTG
          GCTACATACCGCTATAAGGGTTTTGAATCAAAGATATCCG
          ATCTAACGGCGTAGCACCGTCCCCAGCGATAACAGAACCA
          GGCTAATGTGGTAGTGGGGTCTTCGAACCAAATGTTAGAA

