 8 1000
t1        ATCCATAAGCAGTGATACAGAATGGAGTTGCAGATGAGGGTAGCTCGGTATCTTACCTTT
t2        ATCTATACGCATTGAAACCGATCGGAGTTCCGGACGAGGGCAGCCTGACTTCTCGCCTTT
t3        ATTCTTACACGAGAAGACGAACCCGTGGTACAATTGAAAGTGGTCCGTCGCATAGCCCGT
t4        GTCAATAAGCTTTCAGACTGGTCGGCACAACAGACAAATTGAACGCGACATTTCGTGTTT
t5        ACTCCTGACCTGCGGAATAAGCAGGTATTACAGACGGTGGCGGGCGGACATCCCGAACCC
t6        ATCACTGCGCCATGAGATGGACGCACGTTGGGATCAATGACAGACCGCAGTCTAGCAGCC
t7        AAGGACGAGACCTGTGGAAGACTACTATTTGGACAGACGGCAGACCGTCGCCATGCCCGC
t8        AACCACAATCTTAATACCACTAAGTCACCACGGGCGCACGCATGTCGATCTCGGACTCGC

          ACCCTATCAAGCAAGACAGGACGAACGGTAATATGTTGTTCACTGCGACCGACTTGTGCG
          TTCCTATGAATCAAGACCGGATGAACGGTGGTATGTAGTTTACTGCGACCGGCGTGAACG
          GTGTTACTAATCGGGATAGTCTGACAAATAATATGTTTTGTATAGCCACGGGCTCGAGCG
          GAGTCATCAATCCAACTACGCTACGAGACGATCTACCGCCCCGCGTTCTGGTCGTGAGAA
          GTGCGATGATCCGAGATCCTTCATAAGCAAATACATGGCGTGGCGTTCTGGTCACGGAAG
          GCGAGTTCGTTCGTTGTAGTCTGCAGGGAGCTATCAGGTCGGCTATTACAGGAATCGACT
          ACTTTGTGAACGGTGTCTGTGTACAGGGAGGTCTTGTTGTAGTGAACTTGACTGGGAAGA
          AAGTACCAAACGGTCATGTGCCACGAGATGAAAAGGTATGGGATCACACGGGAGTTGCTG

          CATGTCTTAATAAGATCAGGCTAGTACTATCGGGCGCACCTCGGCCGTGCGCGTGGGTCT
          TATGTATCAATACTGTTGGGCTAGCGCTATCGGATACACCTAGGCCACGAGTGGGGGGCT
          TAAATATCAGTAGATCTAGGTTGGGATCTTCAGTTGCATCCTGGCCCCACATGAGGACCG
          AATGCGTGATCGGTGTGAGGCCACTACGCCCGGACATATCTCAATTAGGTGTGGGGGTCT
          CTTAAGTCGGTAGGTTAAAGTTACCTTTACTGAAAACATTTCAGATTCTCTCCAAGGAAT
          TCCCTGTCAGGGCGGTTATATTTGCCTTTAAGAAAGATCCTCTGCCACGTAGGAAGGGCT
          TATCCCTTAATGGGGGAGAAATCCCTCTTATAGGTCTCTCTCAACAATTGACATACGGTA
          AACCCGGCGGCAGCGGTGAACCGTTATCTATAGGCATTTCGCAGCCATCGACAGGGCAAC

          GAAGCTGGCTGTAGGGTCTAGCGGATCTGGGTTAAATGCCTTTACTTCTCACGACGCCCA
          GAAGCGAACTGTAGTGTCCCGCGGATTTCATTCGAAAGCTTTTCCTCCTCAGGAGGCTTA
          GAAGCGACCCGTCACGCTTCCCGGTGTTCCGTCAGAAGCCTCCCCCTATCAAGGCGCCAA
          CGTCCGAACCGTACTGTCCGTTGGGTCTCGACGCGATGTCACCATGTATAAAGACATTGA
          GAAGCAGTCCATTACACCTGCCAATCTGCACTGAATGGCCATAATATCAGGGGAAGTTGA
          ATGACTGCCCACCGAAACTGGTGGAATTAGGTCAAAAGTCGCTATTACTCGAGATGCCCA
          ATAACCCACCATAGAATCCGCTGGGTCCTAGTTAAGTGTGGCCAACTTTAGAATCACTCG
          AAAATGCGAGACGGCGGTTACTGGGCTTAAGCCGCTGCCGAGTTTGCCTCCAGGCGATGC

          AAATCTCTCCGGGATAATAAATCGCGCTGGTTAGCGCGCTTCGAACCTATGTCAGGCGGA
          AAACCTTCTTGGGAGATCCAGCCGCTCTGGTTAGAACGTTTCGCCTCTGTGGCGGGAGGA
          GAACATCTCCGACACATCCCATCACGTTGTCTCACGCTCTACCAACCTAGAGAGTGCCGG
          AACTAATCCCAGGACTTTCTATAGCTCTGGCCGATGCGCGATGAACGTTAAGAAGTTGGA
          AGGGCGACTCGAAACCTCCTAACGTGCAGGCTGAAATAACATACACCGTTATCAAGTGCT
          AAACTTTTTGAGGTCATGCTAACGGAGCGACCCGCGCACCAAAAACCCATTGTATGTGTT
          AAACATTGCCCCCAGACACCACTGCGCCTACTGGTGCGTTCTTAATTTACTGGGTGCGCC
          CATCCTCTCCGACGCGCACAATTGCAACTGTTTGTACTCTAGAGCTATATTTAGAATCTG

          AGTCTGGGACAGCGGTCTCAAATCTTAAGACCTGTCAAAAGCAATAAGGGTCACTTATAT
          AGTCTGGGACAGCGAACCGAAAACTACAGGTATGCTAAAGACACTAATGACCATTCCTAT
          AATCCGGGACAACGCCTCTAAAGTTCAAAGCATGCTGCATGCAGTCATATTCATTGCTAC
          AATGGAGGGCACCGTCCCTTAAATTAACGGCGTGCACCAAGCTGCTAGTGCCATTCATAC
          CATGATATGTGCCAAGGCATGAGGTAACGGCAAGTAAAAGCGAATTGGAGATATTCTCCG
          ATTGCGAATCTAAATAGAACAAGCTGAAGGCGCGTATAAAGCTGTCGACAGGGATTCCAC
          TGAGCCCATCGACGTGATCTAGGCTAAAGAATTGTATTAGATTGTTGGGGCCTATTACAT
          GTCATGGTTAGACGTTGCGCACGGAAGAGGCCTGAATAAGATAATGAAAGTCAACTCTGC

          CAGCGATTACTTTGTACGGTTCGTAATTTCGAACTGGGATCCAGATTTCGTCCAGTAATT
          TAACCATGCATTTGAACCATTCCCACCTTTGCATCGAGAACCAGTTTTTGTCCCATGATG
          GAACTAGCCCTTCGAACGTCCCGCATTTTAGCAGCGAGCTCTAGACTTTACTCAGTAATC
          TACCAGTAATTTTGAAAATATCGTTATCTCGTACCGTGCCCTCGCCTCTGTCCAGAATCG
          TATCAATAACTATGATCATTTTACGACTCTGCAACGAGGCCTAGGCACTATCCCGTGCTT
          CGCCACAAATTCTTAACAAACAGACAATCTGTGTAAAGTTCCAGCCTCAGCATAGTAACT
          CAACAATCAACCTTACCACTCTTTAGGCGTGCCCGGGAGTCCTGCTTCCCATCTGCATTT
          AGGGACTGCCCCGAATGGTCCCCTAGCCCTCCCTGGGAAACCCGTCAAGTTGTTCTAACC

          GTGTGTGCCGGGGTTTACGTGGAAGTTGTTTCCCAGCTTACAGATACGCTCCGACTTGGA
          ATTTGAGCCGGGGGCCATGTGGAAATAATTTCTTAATTCACTGATACATTTCGGCCTGGA
          ATCAGCGGTTGGGCTCTCGCCGAAGTGGTGAATTAACCCATCGGTGGTTCTCAGTTGGGA
          GTTGACGGAGGGTCCTGTGTGTTTCCCGAAACTCGAAAACGTGATACACACTAGTTCAGA
          TCTTACGGTGGGGCCCGTCCGGGATCAGTTATTTGAAATATCGATACATTTTCGATTCTA
          GCTATTAGCGGGGTTCAGGTGTACGAGGTCATTCAGTCCGCCGTCGTATACGTTTAAGAA
          ACGTATGGTGAAACACATGAAGGTTTGGTTACTCACATCCTTGATATGCGCGGAATAAAC
          GCGCGTCCTGCCGCCCATGTAGCACACGCTAATAGAAACGGCGACATCCCGCAGTTAGAT

          CACTTAATCACGCGGCCATTTAAAAGCCAGTGTGGATGGCGTTTTGTATTCGGCCGCGGC
          CCACTAATAAAACGGCTACTATGCGATAAGTGCGCATGGTACTCCTTTTGATACCACGCT
          ATACTAATCTAATTCCTACCATGCGATCAGTTTATGCTGCACTCATCATCTTTTGAAGGT
          ACACTAAGTGAATTTTTACAATCTGGTCCGTAACCGATATACACCTCATGCCGCTCTGAT
          ATGTCAAGCCAATCCCTACTGTGCCCCGAGAGGGTAAGAGTCGCACTTTGACATCACGGT
          TAACTAAGAACGTTACAATTGGGCGCCTACAGGAAAATCTACCCATTACGTAAACGTCAG
          ATACTAAGAAGATTTTAAATTATTGAGCACAAGGCGTGATTATCGATATATCACCACGGC
          CTGATTAGAACGGTCTCAAAACGTGACAGGTGTACGTTCTAAACAACGGGACGTGTACAC

          GTGTCCGAACGCGGAGAGAGGCGAGCGCTGCGGGTGGTGGCAAGAAAAAATAGTAGGGCT
          GGGTCTGAACGCGGAGAGCGGGGAAGACTACGTGTGGTCATCAAGGAAAATGCTAGTGCC
          GTGTCCACGGGAGGTGGGCTGGGAGGACTGCGCCTGGATACTAGTAGAAACAGTCCGGCC
          ACATCCGAATGCAACCGCCAAGCGGGGACGTGCGAGGATACAATATGGTCCAGCTATATC
          GTGACTGAGCCCATTCGCTGGAGACCATTGTGTAAGATTAATAAAACAGACGGCTATGCC
          GCACCTGGTAGTAACACCAGAGGGGTTTAAAGTGCGACTACTATACAGCCTAGTTGTATT
          TTGTTCGGATACGGAACACGGAGGGGCTCATATGACGTACCTAATCATCCCGGTTCTCCC
          GAGTCAGTTCATAAAAAGGACAACTGACTGAGGAGGTGATTTTCAACTGTGGGCCTCATC

          TGTACCAAAGATCACAGGTTATTTGCTTCACCCGTACGGTTCTTTCGGTGATCGTTGAGT
          TGCACCGGACATCACAGGTTATTTGGCCGGCCTATATAGCCCCACTGTTGGTTGTTGGGT
          GGTACTGCACATTAACGTAAATTGGGCTTGCGGCTATCGTCCAACTAATTGCCATCGGTC
          CGTAACGCACGTTACGAGAAATCAGGTTCGCAGGTATGGTCGCACCGAGCGATACTGGTT
          CGCTTGTCGGAGGATGGGATCTCCGGCCCGCCAGCACGGTTTCGTCGAGTAATCCTGAGT
          AGTACCTCACATACCAGGGTAGGGTGCTAGCCAGCACGATCCTGCCAAGTGACATAGAGA
          CGAATTATGTTTTCTAGAATGGGAGACCGGTTGGTAGGGACCGACTAGGCATTATTAAAT
          CCAGCAGCCAATGTCAGTTCAAATCTTCCATCCAGGCGGTGGTCCGGTGCACCTCCCAGC

          ACACTCGATGAGTAGACCTTGTGATTCCTCCAACCTGGGCGACCTTTCGTCTAATCCTTC
          GCGCTTAATGAGCAAACATCGTGACTCCTTCACCAAGGGTGACTTTTCATGCAGTCTTGT
          ACGCTTGATCTAGAAACCGTGTGGCTCGTTGTGTCTGTGCGACTATCCACGCAATCCTCT
          ACGCCCACTTAGTATGCCTCGTGAGCTCTTGGATCCGGGTGTTATACGCCGAAGTCATCC
          ATGTATGATGCAGATATCCCTTGATTTCCCGTCTAGCGATGTTACCTCGCATAATTGTAG
          CTGTCTGACGAACGTATCTTCCGGTCGCTTAAGACTAGGCGTCTTATAGCGCAATTACGT
          AGCTTGAACGACCTGTCTGGAAGACAGCACAGGCCGTAAGTTTTCGGCGTGGTACCCTTT
          TGATCTATTTCTCGTTCTCGTAGATTGTAACTCCCTCGATAGACCCCAATATGTTATCGC

          CAGTTTCAACGTACCGCCAGTCTCCGAGACGCACACCACCTGTGGACTATGGAGACGGCT
          TCGTTTACAAGTACTGCTGGACTTCGCGATGCACATCACCAGTCTACTATGAGACCGACG
          CAGGCCCCGGGCGCCGCAAGCCCTCGGGGCTTGATTTCTCGGAGGAATATGGCGCCCACC
          TAACCTCCCGGCACAGAGGCTTCTTTAGGCGTAATTTACCCGAGGAGCATGGGGCCGGCC
          CGGCTCCTGAATATTGAAAGTACCTTCAGTGTGGCTCCCCTGTCAATTATGGAGCTGATT
          ATAACCCGAAAATTTGTAAAACACGGGAGATTAGCCCTTCAGTGGGTCACAGGACCGATC
          TGTACTTCAGGCCGTCAGTCTTCTCGACGAACGGGTCGGCACCGGTTTACAGAATTGCTA
          CTGTTATTAAGTCCCCCAACCCGTTGCAGTATTAGCTTACAGCTAAATAAAGAACCGCTC

          CTACAATAATAGTCTACCCAATAGCAATACTATCTCGTTGGGGTTGCGCTCCGCTTAACC
          TAACAATTGTAGCCTGATCGTTAGCACCGCTGCTTCGTTGGGGTCGCCATTCGTTTAACC
          TTGTAGTATAAACCTTCTGACCCAGTGTTCTGCGTCATAGGCACAGCCCTGTACTTAGTC
          CTATAGATTTTGCTTGAATGTTCGTAGTGTTGTGTTATCCAAGCTGTCATATGCATAGCC
          ACATTGCTAGCGCCTACTTGCCCAATGCGTTATGTCATTTGAATCGACATACGCTTAACC
          TCATTGATTCTGGATGACTGCCCGCAGCGTCGAACGACCTGTATCGCTCCACACCAAGGC
          TCGTTTCAATTGTCAACTCGCGGACATACTGGAGTTCCTTGGGGTCGCGTAAGTATGGTC
          TCTTTTTATGCGCATCCACTCTCACCCTATTACAAAACTTTCAGTGCCATTTCACCGGTA

          TTCCTGCAGGCTCTCCGCCGTTTTCGCGAACGGAAGACTCCCATGGCGTTAGACGGACCT
          CTCTTGAAGGCTGCCGACTACTTCTGCGCGTGTGAAATTCTCCCGGTCTTGGATGGATCT
          CCCTCCAGGGGCGTTAGCAGTTGCTTTGAGTGGAAGAGTTCCACGATGTTAGGCGGACCT
          TTCTTAAAGGTCAAAAGTCGTTCGTGGGCGCGGGGAGGCCCCCCCCTTCAAGGCGTCTAT
          CTTTTGAGCGGCTCAAGGCGTACAAGTGAGTGGAATGTGTCCGTCACATAGGACGAACGA
          TTTAGGTGGAGCGGGATTATTTCACACTACTAAAAAGGTTCTGCCATGTTAGAAATGTGC
          ACGTCATTAGATGAAAAGTGCGTTGAAAGACGGGGATGTTTATGGAGGATGAACGGGCAC
          GTGTCTTCTCCTATCACTTGCACGTGAAAAGCGCCCCGACGTACTGTTCCTCACCTTTGA

          GCAGCAGTAAACACGGAATCAGTAGGTATTAGTCGAGATTTGAACCAAGGGGGGAAGATT
          GCGGTAGTAAGTACGGAATTAGTAGGCCTTGTTCGGGACTCAAACCGGGAGGAGAAGTGT
          TAGGCAGTGGATACGAAACCAGTAGATTTGAGCCAAGAGTTGAAATAGGAGGAGGGGGGT
          GCGTCGGCAAACCCGGTACCAAGAGTACTAAGCCGAGGTACGGAACGGTACGTGAAGACC
          ACAGCAATGATAACGGATATACGCGGCCCTGATAGAGGATTGAATACGATAATGAGGGGC
          GCGGGCACGTGCCGAGGATCGACTGGTTGGGGTAGCAGATAGTGGTAAAGGGTTAGGGGC
          GAGCCGGGTAATCGAAAGTGAAATAATCCGCAATGGAAGAGGTAGCCGGGGGCTGAGGGT
          AACGAAGGGGTTGTGGCGTGAGTAAATCGAGGCAACCAGGAGCCATATTGAGATGCAGTA

          CGAGCGTGACGCCTCGCAGTCTCGACATGAGGCTTGGAGT
          CGAACACGCCGCTATGCGGTATTGACATTAGGTTTGGAGC
          CGAGCGTGCCATTACGCAAGCATAGCATGAGATCTTGCGT
          TGAGCCAGACGTGATACAGTCTGGTCACGGTGGATAGCGT
          CTGGTATGTCGTCACGCGAGATTGACAAGAGATATGGATC
          TGTCCTGGCAAATATGAGACACTAGGGCGAGAAATGCCGT
          TGGCCAAACCGGCCCAATGTCATTGCACGGGTTACGGCGC
          CTGTCGAATCACTTAAAGACCATAATAGGGCGCTAGGCGT

