 8 1000
t1        CGATAGCTGATTGCATGAACCGATTCGACGGCGGACATTGAAAGCTACCTGTCCGCCTCA
t2        ATTTAGCAGGTTAGATTTAAGGATTCAGCTACGGGGAGCGCGGGCTAAGCCCTGATATTA
t3        AAGAGGGATGTTCCATCGACTGTTCCGTTTCCAAGGCTCAAAAATGAGCTGCTAATTTGG
t4        AAAAAACATGCGTGACCAAAAGCTTCGATTACAGGGTCCGGGAATGATGTGTCGGACCCG
t5        CGATAACGATGCCGACCTCCAGCTCCCGTCTTCGCGTCGGAAGATGCTAGATCGATTCCG
t6        CGCGGGCACGCTTCTCTAACCGCGGGAATCACTTGGACTGCGTGTTTGGTATCCTTCTTA
t7        TGATATGATTTCAGGCAAACTGAGGTAATCTCAGCGGCGAACAATAAGATAGTCTTTTTA
t8        CGTCCGGACGTGGAGTCGATCGTATCAGTATCTTAGGCTAAGAGCGGTGCCGTCTCCTTG

          TAGCCTATGGCGGTGCAAATCTATTTCTCCTGCGTGATGTAAGGCTCGTTAGAAGCTAAA
          ACGGACTGAGATTTGAATCTAAACATACATTGCAGTACATAAGTTGCCCTCGGCCCTTCT
          TAGCGGCAATCAGTTAAACCAGGTTGCTTCTTCCCCAAGTCCGACTCGCAAACATCGGAT
          TAACAAGAAATGATTAAACTAGGTTACTACCGTTTCAGGTTCGGCTCGTACACATCTGAT
          CATAAGCACACGTCGCGGAAAGTACGACACGTGTCCTTATTTATTTCATGCGTCCTTATG
          AGACCACACCTAGGGTTGCCTCATTAGGGGCTCTCCAACCCTGGGCAACCGATGACTGGG
          AGGCGTCATGTCGAACGCCTAATGTGTGTTCAATGTCTATATCGGTTGACCTACTGCGGG
          TGTCGTCGTGATGCGTAATTTATTCGTTCGTTCTGCTCATATGGATAGTCGCACCGCGAG

          GATCCGGGTCACGTGATCGAAACCGCCTCGGTGTCCAATCACTGCTGCGACGTGCAGCCT
          GCTTTGGGCCCTCAGTCTGGGGCATCCCCGCCACCAGACTGCCGTAGCATCGTCAGACTT
          TCTCGAGACCAGACGCACGTTTATTCATCTCTGTTCGACTGCCGCGGTGGTATCAGGCTC
          CCTTGAAACCAGGTGTACAGATATACACTCGTGCTCAATTGACCTCGGACAATTAGATTC
          GTCGAGATACGAAAGTACGGCCATACAATCGGGTGTGGCCCGTCTGGGAAGTCCAGTGCC
          GATGCGTAGGAAGTGAGTTTTTGAAGGACCGAGCCTAACGATCGATGTTTAGCGTACGTC
          GGCGATGGCCGCAGCTATGCGCACAAAAACGTACCATAATAAGGCGTGTGTTCCAGGCTT
          GTCGCCGGCCGTTCGTAGTCGGAGGGTATGGTATTTTATTAGGGTGCGCCGGCCATTTAT

          GAGCGACTAAGATGCATCGATAGTTGATTCTCGAGACTCACATTCATATTGCTTAGTTAG
          GATCCTCCCCGTTCCGTGACTAACTGTTCCTAGTCACCCCTTCATCGAGCGACAGGCTGA
          CGACCATGCGTATCAATTCATTGTTTCAACCTACTGTCCGCATTCCCCTCGCTACGATAG
          GGACCATGCGTCTCAATCTGTTGCTTTACTCTGCCGTCCGCTTCCCCTGGAACACGACCT
          GAAGTCGCGATATAAACGGACAGGCATCGCACCGCCCTCAGGGCGCTATGTTTGAGTCAA
          AGTACAACGACACCTGCGTAAAGATGTCCCTTTCCGTTTGGTGTCTCGACAGAGGGCTTC
          ATACCGGAAACCCTTATCTACAGATACTGTTCGCACCTCGGTCCATCGAGGTCTATCGAA
          GATCTCGTTTTTCGCTCCAGCAAGTACTACGTGGCCCATGCTCTCCCAAAAATTTGCCGT

          CCCTGAATGCTATGTGTAGCGCTGTGCATGAAGGTCTTTCGAGATCAAGTGCACGCATTT
          CCTTGTGTGTGACGAGCAGTACACCGTTGTGCGGCTTCTGTGGGCTCATAGTATGCGGTA
          CACCCGTTATCGCGAGGGGTGTGTTAATGTAGGGCGCTGGTGGTATTATGGCCTGCACAG
          CATGGAGTGTCACGACGGGCGCAAGATCGCAGGATATTGGTAGATCCACAGGTTGTGTGA
          TTAGAACCAACTTCTGGCATGTGTAACCATGCGATCTGAAAGACCTAGCGATGAAGGAAG
          CTTGAGTGTACTTGATTGACGGCAAATCACCGATGTTAGTGTGCCCCTTAGAGCGAGAAG
          TATTCTTCGTCAAAGGCTACCCGGGATTGCGGGTCTTGGAGAGCTCCACGGCCTGGAGTG
          CGTCCACTGTCGCGCGTGGACCGGAGTTACGGGATTTAGGCTGTCTCGCCGTTTGAGATG

          TTCACGTTCGGTAGTATCCCCTAACTACGGCTGGACGACGGCTGCCCAATGTTGCACCAG
          ATCACGTGCGAATTCCTTTTGTGCATAAGGCTGTGTGGCTAAGGCTCGTTCCCGTGCTAG
          GTTGCCGGCGCTCATGTATCTTATCTACAGCTACATGGGGATAGCCCGCAGATGCGGTAA
          GTTGCCAGCGCCTTTACACACTGTCTACACCCCCATGGGGATAGCTTGCAAGAGTGGTAA
          CTGGCAAGTACTAACTGGACCAGTTTTCGGTTACCCGGTGAAGGTTGATAAGGGCCTTAG
          TCTCTAGATGCGACCAACTCGAGAGCCCAGCAGTGGCGTGCGGGTTACCTACTTGTTCCA
          TTCGCAGGCTGTGACAGCGTTCGTAGTTTTCCGCTCGGCGGGTGATGGTCGCTTCGTCGG
          CTTGCGGGCCACGATGGCACTTCTCTTTAATCGTGCGGCGATTATAGAGAGCCTCTTCAG

          GTTGCTTCGCCCCATATACTTTACGGGTCTGCACCCGCCAAAGGGGACGGGAGATACTTT
          GCTTCTGGACACCATGATTTTTACCGATTTGGGCCTACTAAGTTGGGCGAAGAATTGTCT
          GCGGATAGAAGCCGCCAGAACCACAGGAATGGATCACCGAAATCGATTTAACGATCATAA
          ACGGACGGCAGCCGTCCGGTCCACAGCACTAAATCGCTAGGTTCGAATCGACGATCATGA
          TCCCTGGGTGATGAGTAGGCGTGAGGAGACGTGCCTCCTAATACGATGGATAACTAATGC
          GATTAAGCCAGTTACCACCCTGGAAGGGACGGGTTCTCGAATTCGCCTACAAGGGAGAGT
          GTCGTGGGGATTGGCCATCTCCCAAAAAGGGACGCGCGGACCACCGTCGGGAACCATACC
          CCTAAAGGAACACTTAGTTCTAGAGAGCATGATCCTCCCATCCCAGTTGGAAACCAGAAT

          GGGGTCAATAAGGAAAGACGAGTCGACCTCATCCCATTTCAAATCCCAGCTGAGTCCCTC
          CAAACATACTCGGAGAGTGGAGTCCGACTATCAATGAACAGACTTCGACTATTATACCAT
          AGTTGCTTCATGGATCGAGGCCCCTAACTAACGGGTAATTGAGAACGGTTTACACGAAGC
          GGTTATTTATGGGATATGGGTGTCTATTCAAGGGGAATACGCGAACGGTATAAACGCCAC
          AGATCTTAGTCGGCTTGTAGCGCTGCTGGCTAAGTTCGTTTAACCCGCTTAGAAAGGTAA
          GAAATTTAAGATTGGAACCGCATACGTTTGATAGCCTGTTTCTCACAGACAAACGAGGGG
          ACGTATCGCAAGGAGGGGAGAGATAGTGAGATAGCGAGTCGCACTCCATTAGCTGGTTGT
          GAGTTATATACGGCGAGGAGAGGCGGCAAGAAAGCGAATTTTTAATAATCAGATGGCTGC

          GTGTAGTGGAGTAATCATAAGATATTGCCCTTTACATCCCTAACAGAAGGTCATCCTCAG
          GAAAGCTAGAGCTAATAACGGGCAGTGAAGTTTAGGCTCTAATCATATGAGCGGTGATAA
          GCGGCGTTATATCGGTGTAAAGCTACGAGAACGATTTGCGTGGTGCCCGACAGGTCTCTA
          CCTCCATCGGATTAGTGATAAGCTGCGCAGTCGGTTCGTGTAGGGGCCGATCGATCCACA
          AAAAAACGCGTACCAGAATGTGCGGTGTAACCGCCACTTCTTCTCTTACTTCTGTGGAGG
          GCTTGGCGTGGGTAGACATGGGGATCTGGGGAATGTGCCTTCCCGGCATGCCACAGTGGA
          ATAAGGGATGGAAGAGGAATGATGACAGAAGCGAGCGTTCCCCAAGCCTGCTGGCACTGA
          ATAAGGAAGTGGTGCTCAATGGCGTCTGGGCTGATACCTCCTTCTACCCACGGATCCGGA

          TATACCAACGCACTGGTCGACCTTATAAAGCCACCAACACATACTTGTATTCCGAGCCGT
          TTTTCGCTGGAAACTATCAATTGGGCAACAAGCCCATGATGTATGTGTTCGATCCACCGA
          ATTTCGTCAGATCTTGCTGAATACGGCTCGTAAGCTTCATACCAGCTGGCTGTCAACTGG
          AATTTTCTAGAATTTACTGGACACGGCTCGTGTATGTCTTATCGCTTAACTGCCAACTAG
          CCTGTGCAGCATGTCCATTGACACAGGTATTAGTAAACATTCTGATTTGCGTCGGACAGA
          GCCTGGGCACTAATCATAAAGTATAGAACCAGGGTCTAACGTGAGCTAACGATATAGAGA
          TGCTCCGACTGTGTCGATTACTCTGCAGCGTGGCACCTAGGCACGCCTCTCGTACAATGT
          TTTCGTGATATAACCCCCTAATAGGGAGTATGGCACTACAGTATACCTAATTCGAGACGT

          GAGGGCAACATCTGGACTTGGATGAATCGAGACGTGGGTTACCCCATGATTGTAGATCCC
          AGGGGCTCTGTTCCAACCCGAACGCCTTTCAAGCTGCCGCTCTTAGATAACGGAACGTGC
          AGCGTAGCGATTCAAATTCGGTTGATCTTATTGCCTCTTACAGCACATCGCTAAATGCAC
          CACGCTGTTCTTCGAATTCGGGTGTCGACATTGAATTCCGCCGAGCATAGTCATGAGCGT
          TGGGGGCGTATACGTGCCGTCCTGACTATTGTACTTAATGTGCGGCACGTCGGTACCAAC
          ATCGGCGCCCTATCGGCGGGATCGCCTCATTGCCTGTTTACTGAGCACCACCACGGACTG
          AGGAGGGTTGCTCGAATCGGATCATCTCTCAAGTGATCCATGCAGGGTACCACACCAGGT
          GAGTGGGCTGGTTGCCTGAGAACACGTTTTACGATCTCCTGAAGATAGAACAGGAAGGGC

          AATTATTACATGGCAAAAAGTAGCCACACGTGAATTCGATCTATGCTATTATAAGAAACT
          ATGTTTACTTTGGCGTACGATCGTAAAACAGAAACGAGGTCAATCTTGTTAGCTGGATAA
          CCTACTATTTAGTTGGATGGAAGGTCCACATGTACAAGGCGTGACCGTTGACGAAGGACT
          GTTGTCGCTTAGCTGGATCGAACATTTTCGTATATAGGATACGTCCGCTCATGAGGGTCC
          CTATCTGTCAAACTCTGCTAACCGAATGCGTGATTAACCCTCGTGGCGCCACTCTATAAA
          TCACCAACCCATTAGGGATATGTGTGCCAGGGCATGAGATCTGCTCCACACTAGCTGTTC
          TCTACAACCGATTTTATCTGTAAAACCGCGCCAATGGCATTTAGTCCGTTACATCTGCTA
          TCCACCGTCAATCTACCTTAGCGGACCAATTCTGTGGCACTTATTTAAACAGGCCAAACA

          TGAAGCCCACCCTTATAGAGGGAAGACCAAAGGTCTCGGTGGATCGACGGCTACGCTGTA
          CGGCTTTCGTTTCTGAGGTGCAGAGTTGAATAATTCGGTGAAGATGATAGATTAATAATG
          CGAGCAAACCTTGCCAGTAACGAAATAGGTACATCCTATCGATCTGATGACTTAGCGATT
          CGCTCAGACCCTGTGCGTACCGGCTTAGATAAGTTTTACCGATGCGATGACCTTGTAATT
          TGAGACGTCCCCTCATGGCCTGTCGCCGCCAAAGTTTGCTTTCCTCATGTCTTGGGACTG
          TGAGGTGTATGTTTCTGAAGTGAAGCTGATAGAATACATCTGTCTCGGGAATTAGTTATC
          TTATTTAGGTATTACCTGCACGCTGCCGGGGATATGTGCGGCTTATACGAACTAGCTCCG
          TATAGTACGTGCCTCGGGAGCGTTGTAAAGGGTATGTGTGACTCTTACGTTAAACCCCAG

          TCAGAAAGTGACGCGTCCCACTAGGCGTACGCTCGGTAGCCGAACTTTGGCGCGCGTACT
          TACAATCGTGATAGATGTTGACGGGACTGTGTTGAATTTTTAAAGCACGAGGTGTACTCG
          TTGCACTGACTTGATCATCCCGGGATATCCATCCGGCCTTTCGCTCATAATCCGTGTATC
          CCGCATTGGCCCGCTTACTGCGACTGAGGTGTCCGGTCTCCCGCTCACTCTACATGCCCC
          CCCAGCTGCTAAGCACGCTTCAGGGAATTTGCTTGACAATCAGATCACATTGTGTCTGAA
          GCTCCGCACTGTCCACCTACTAAAACGTGTTTTGGTAGTCTTGACCCAAGCGCGACGCCG
          ATTATATGCCAACTCCTTAATGCTGGGCTCACCTAGCGTACCGGCCCCATTTTTCCAGTA
          ACGATATGCTAATCCTGCCCGGGCCGGCATATTTGAACTACATATAATGCTTCGTCCCAA

          ACTAAACGCTCTGAAGGTTGTAAGCGCTTGAAAAAGTTAAGACCCAGGAGAAAACACGGG
          GTTTATTACCTCAAAGAACACAAGTACTCTTATAAACTTCGAACAGAGCGCCTAAACGGA
          CACCTGTACAAGGATGCAACAGAGCGCCCTTTAAAGCTCTGTTGGACGTGAGGATTAGAA
          ACCCTGTATTACGAAGCTATCGAGTGTTCTTTAGAGCTCTGTAGAAGGCGAGGGTTCAAT
          CACTTGTCTCGGCGAGTCTCTGAGAAGCTAGTTACCGTGGACCGGTGAAGGGAGAGCTAG
          TCGCTGCCTAAGTAAACCCCCAGCACCTCACAATTCCGGGCTGGGAAAAGTGCCTATTAA
          GGCTAAGTCTTGGCAGTCGGTTCGAGCCTCCACCAGACTGCGAAGATGAGGACCCACAGG
          TTCCGAGGGCTCGCTCCCTGTGGGAGTCCTCACACGAATGCGTAGATAAGAGTCTGTCGT

          GAGGACCAAATTACGGTAGATGAAGTACCCCTGATATACGTACGCTGTTGGCCCCATATG
          GGCAGCCGGGCATTGTCTGTAAAACCACCCGTATCACCGCTCTACTTTATCCAGCAAGAG
          GGCAACAGACCCTACCCAGTTGGAACGCCCGTGGAACTCTAATGCCCCACTTTTCGTGAG
          AGCGACCGAGCCTTTTCAGGTGCACCACCCGTGGAAACGTCATGTTCAACTTATCGTTTG
          TACTTTCGCGATGCGTTAGCGAGTAAATTCTCGACGGATTAATCCACTAGATTTCGCGTT
          AGGTGCTGCTGTACTCAAGTATGAGCCTGCTTAGTTGTAATATGTTTTCGGCTCCATATC
          AACTGTTACACCTGTACACTGTGCAGTATCCCTGAGGATCCCCGTCCGGCCATTCTAACC
          AGTGGCAGGAACTAGCAAGCGTGAGGCGTATTCGAAAAACTGTGCATTAGTATTAATATG

          CATTATAACAATCAGAACTTCCTACACCTTGTGTATGCAA
          ACGCGTGCTATCGCATATCTGATATATCATGTACAACCTA
          CAGCTAAGCAATTTACGTTTAATTTCACACGCTGGCCTAA
          AAGACGAACCATTCATATCTGACCCTACGGGCCCACCCTT
          GCGCTGGGATATAAATGCACTATAGCCGAATGTGATCCAT
          ATTCTCCAAAGTGATGCCCGCCCAATCAACCTAAGCACCC
          GGCTTGATTCATCAAGAATTTATCTCAGGCGGGATGGCAA
          GACCTAAACAACAACGCTCGTACGGTCCACGGCCAGATGA

