 8 1000
t1        GTGTATTCAGTGACCCCAGCAAGATGCAATCTCGCGTGGCAATTCCGGGATCTATTCTGA
t2        GTGTATTCAGTGACCCCAGCAAGATGCAATCTCGCGTGGCAATTCCGGGATCTATTCTGA
t3        ATCCGTCCCTTTACTCTCGTACAACCGAGTAGCGCAACGTCGGCCGTGGAATCGTCCGAG
t4        ATCCGTCCCTTTACTCTCGTACAACCGTGTAGCGTAACGTCGGCCGTGGAATAATCCGAA
t5        ACTAGCAAGGTCAATCTGGCAAAGGCACGCCAGCTGAGGAGCCTGATAATGACAGTTCAG
t6        ATCGGCTGCGTTGCCCTGGCTAGGACATACCAGATCAGGCGATTGACACCCCTAAGTTCT
t7        GCGCGCCCAGGCGTCCTGATTAATGCGGGGGAAGTACGATAACTGGGCACCATAGTTCTT
t8        TCTTACTATAGAAGCTGGATCAAAATGAGAGAGATAAGGCGACCAGGGTCATCAGTCCAT

          ATCGCGGGAACAGAATTGACGAACCGTCGTGACTAACATTTTTACGTGTTTCGTCCCTCG
          ATCGTGGGAACAGAATTGACGAACCGTCGTGACTAACATTTTTACGTGTTTCGTCCCTCG
          GTTCAGTCAGACCCTGAAGCGCTGCGCCATTGCACGGGATGTATCAAGATTCTTTGGTCA
          GTTCAGTTAGACCTTGAAGCGCTGCGCTATTGCACGGGATGTATCAGGATTCTTTGGCCA
          AGACGATAAACATGACTCAGGCAGTTGCCCGGTAGCGGGCATACTTCCGATCCCTATCCC
          AGCCAACGTCAACATACGGGAAAGTGCCGAGACAAGCCATACACGTGAGTCTATTAAACC
          GAATGCCGAATTCCCCCGAGGAGAGTATGCGATGGATAGCTGCCCTCATCCTATTGTTTT
          AAAACCTGCAACTCAAACCGGAAAGAAGATAACGGACCACCACCCTTATCATACAATTCC

          ACGTCCATAGAACGCCAATATGATGCTGTGCTGAGGTAAGTCTTATCGTTAGCAGTGGAC
          ACGTCCATAGAACGCCAATATGATGCTGTGCTGAGGTAAGTCTTATCGTTAGCAGTGGAC
          CCGATAACGGAGTGATTCTTCATTACATTAACGTGGCGAGTATCGCACGTGCAGACGGGC
          CTGATAACGGAGTGATTCTTCATTGTGTTAACGTGGCGAGTATCGTACGCGCAGACGGGC
          CGAATATTAAACTGTGTAATTCTCACTTAGTTGCACTTTGCCTGCTACAAGAGAGTCGGC
          CGGGTTCCAGGGTACATTGTTGTTTCGCCGTTATATATTGCGTCCTTAGCGGCGATTGGT
          CGGGAGAAAGGCTGAAGCATTGCGATGGGGCAGTAACTACCTCCCTATGCGAAAACCGCC
          CGAGTCATAGGTCACACCTTCCCTCCGCTGTTGCTTTCACTTACGTCCCCGAAGATAATG

          CAAATGGAGTTCCTTCGGGCTAGAAGTTTGTTCTATCGCACATTACTTGCCCAGAGCTGC
          CAAATGGAGTTCCTTCGGGCTAGAAGTTTGTTCTATCGCACATTACTTGCCGAGAGCTGC
          TAAGCACGGAACCGTCTTCGTCAAGTTAGGCCACGGGTTGCCTTTTCGCGTCGACGAACT
          TAACCACGGAATCGTTTTCGTCAAGTTAGGCCACGGGTTGCCTTTTTGCGTCGACGAATG
          TGAACTGTACGCCCGCGGCGAAGCTACCGTCACAAGGCTCCCACATATTGCTGTTATCAT
          TGAGCAGCGTGCTCCTGCTGCGAAGTACGTCTCCGGGCCTCCACCAGGAGCCATTATTGC
          CATTCGAAAAGCCTATGTCCCGATGGTGCTCTCTGAGTTGGTTCGAAAGACGGTTGTGGC
          AAATTGGCGTGTTTGTGGAGCGGCTCCCCGTTCCAGGCGACCCCAATGGGCTGTCACGTC

          TTGAGTGTTTGACGTAACACCACTTTGACTGCCCCATTTGCACCCCTTAGCCGACGTAAT
          TTGAGTGTTTGACGTAACACCACTTTGACCGCCCCATTTGCACCCCTTAGTCGACGTAAT
          TTTAAAGCCACGCTCCTAGACCATTTTGGCATAGATTGCGGTGCGGCCGTCCAGACGCAT
          TTTAAGGCCACGCTCCTAGACCATTTTGGCATAGATAGCGGAGCAGCCGTCGAGACGCAT
          TGTAGAACGAAGAACAACACGGTTCCATAGTAAATGAGCCAAAACAGGGGAAGCTCCCAC
          CGACCAGTGGACAAGTTGGCTGTTCTCTAAGCATCGTGTCAAAACGAGTCGATATCAAAA
          TAGCGACCGGGCACACCTAGTGGATCCCAGACCCTCTGCTATGGAGAAGCACGGTAACAT
          CTGCGTGTGTGCAACCACAGCGATTCCCAGAATCTATGCCATGGCAAGGGAAGGCCTAGT

          ATTCCCTGGGACAACACGGTATCAATAGGACTACCGCGGTATAGCACCCTTCGTAACGGG
          ATTCCCTGGGACAACACGGTATCAATAGGACTACCGCGGTATAGCACCCTTCGTAACGGG
          ATGCCAACCGCCGGCCTAAATTCCCCGAGGCTACCCGTACACGATGGCACGCCCCACATA
          ACACCAACCGCCGGCCTAAACTCACCAAGGATACCTGTACACAATAGCACGCCCCACTTA
          AAGTATAATAGTAGTGTGAGGCTCACAGAAACAGTTCCTCATACATTCACAGGGTCCATA
          CAGTTTAACATAAGTCGGGGGTGAACAAGAAGGGGCCCTAAAAAACACCAAGTGCGCATG
          GATTTAATCATAAGTGAGAGGTTAAACAGAGCGACTTTGCATAGGTTCCCAAGCATCTTT
          AAAAAGGATACTTGTACAAGGCCTAGAAGTGCGGACCCCTGCAAACTTCTACCCATTAAG

          ATAATCAAGTCTAACTAGGATCCCTCATCACGGGCCGACTATATAAGCAGGTGTACGTTC
          ATAATCAAGTCTAACTGGGATCGCTCATCACGGGCCGACTATATAAGCAGATGTACGTTC
          CAAACGGGCGTCATTGGCAATGATCCACTGGGCGATAGTCGCGCACGTGGAGGTTAAACT
          TAAACGGGCGTCATTAATAATGATCTACTGGGCGATAGTCGCGCACGTGGAGGTTAAACT
          GTAGTTCGACTCTGCCAGGGACATCAGTTCCGGGCCGGCGGATTCCGCAGTAGAACATTG
          TAAGTTGGAACACATCGAAAGCATTTGTTGGGGGTGGATGAGGTCTTCGGTGACCCCTTA
          TAGGGTCACATACGCCATGAACAACCCCACGGGGCTAAGGGCACCCGCAGTGACGCGATT
          AAAGATGCACTGGGCCCGAAAACACCGCCCGGGACGGGCGAAGCCTGTAGAGACCTATCA

          ACCTTCCGACAAAGTGTACTCAGAATCGAGGGTGCGAGGATAATATGCGCCCAAGACGGG
          ACCTTCCGACAAAGTGTACTCAGAATCGAGGGTGTGAGGATAATATGCGCCCAAGACGGG
          CAGGCCGGTCGTAGTTCATCAAGCATTTAGTATTTGGGGCAACCATGGAATCCCGGTCGG
          CAGCCCGGTCGTAGTTCATCTAGCATTTAGTATTTGGGGCAACCATGGACTCCCGATCGG
          GATTTTTAGAGCGGACGATATCTCATAGACCCAGTATAAAGCACGTGCCATCCCGGGAAG
          CGTTTCCGATGTGGGTAACTACCTGACTGCCTAGCATAATGATCGTGTCTTGCTAGACAG
          GATTTCCAAAACGGACGCTGGCCGATATACCCGAAGCAGCCATTTTGCAATGCGGCGTGT
          CAACTTAGAAAAGCACAACGAACAATATACCTGCTGTATTGACTCAACCAGACCCGATTG

          CTGGGAACCGTGTTCCAGATGTCCCTTCCCCCGTCTGTTGAATAAGCCCTGACCCGGATT
          CTGGGAACCGTGTTCCAGATGTCCCTTCCCCCGTCTGTTGAATAAGCCCCGACCCGGATT
          TCGGGTGGTGTGCTTCAGGCCTAAGCCTAATGGATCGTTGAGCAAGCTTTTCATAAATTG
          TCGGGTGGTGTGCTTCAGGCCTAAGCCTAATGGATCGTTGAGCAAGCTTTTCATAAATTC
          GCTCGCGACGTGGCTTAAAGATCTAGCTGGTAGAGTGGAAAATGGCCTCTACCGGCGGTC
          AGCTATGATGTTGCCCAAGGATCCAGCATGTGGTCTAGCAACGGGGTCGTGCCTCGTAAT
          TTTATAGGCGCGGTCGAGAAGTAGAGCGCGCCGACTGGTGGTAAAGCACCACCACAGGCC
          ATTCAGAGCGCAGTTCAAAAGTAGAGCGCTAAGTTAGGCACTAAAGGTCAGTCATCGGTA

          CGGCCGTATTAACACAACTTCGCTTTTGCCCCTCATCAGTGTTTCTATTCACTTCCACAG
          CGGCCATATTAACACAACTTCGCTTTTGCCCCTCATCAGTGTTTCTATTCACTTCCACAG
          GAACAGCTCTGGCATCCTTACGCGGTAGACTTATCCTGGGCCAGTTATATTACCTCGCTG
          GGACAGCTCTGATATTCCTACGCGGTAGACTTATTCTGGACCAGTTCTATTACCTCGCTG
          CATGCCCAGTATTAGTGTTTCGATTAATATCCCGAGAGGTGCTAAGAATAGAGTACTCAG
          TGAATACTGCTATGATACTGTGCCCAACATCAGGGAAAGTATAAAGCGGCCAGCTATCGG
          CCCAACTAGTATTGTCACGCCACATAAAGTCATGGAAGATATATGGCGATGAGCCTCAGC
          CATCCGTAATACTACCGTTCTCTCCAACGAAGTGGAATGTGAGAGCCGAGGCGTCTCTGT

          TTCTGTATACCCCTACCCCCGCGCTGCCGCACGGTCCGTAGCGAGGGCGAGCGCTGTTAG
          TTCTGTGTACCCCTACCCCCGAGCTGCCGCACGGTCCGTAGCGAGGGCGAGCGCTGTTAG
          TTCCCCACTCCAGTGCCTTCTGCGTGGAGGGGCACCAGCCTTCACGGTTGAGGTATCAAT
          TTCCCTACTCCAGTGCCTCCTGAGTGGAGGGGCACCAGCCTTCACGGTTGAGGTACCAAT
          GCCCAGGCAATCGTATTGATTAGATGTTTGGTTTTGTCCTTCGCCCCCCAGGGTAGCAGA
          TCCCATGTACGTGTGTTAGCAACTCCCCGCGCTCTATAAAACGTTCTTAATGGCATCAAG
          CTATCTGTTCTCCCGGAACTAAGACGCTACGTTTTGCACTTTGTCCCCTTGGCTTGAGGA
          CCACAAACTTTCCCATCCCTAAGTTGTCAGCCCTTGTACTTTGACTTGTGGGGCCGAGTA

          TCAGTGGTTGCATACTATGACCTGAGGCCATGCGGTATTTAGATGTATTGGTTCTGCGGG
          TCAGTGGTTGCATACTATGACCTGAGGCCATGCGGTATTTAGATGTATTGGTTCTGCGGG
          TCGACAAACACTTGCATTTACATGGCTCGCTGCAGTAATTTACTACGGCTTACCTACCGG
          TCAACAAGCACTGGCATCTACATGGCTCGTTGCAGTAATTTACTACGGCTTACCTACCGG
          TGAGCTGGTGCATTGTCCACTACGACCTACTACAGGCCACGAAACAGAAACCAAAGCTGG
          AGCATCGGCATATCGTTTAAGGTACCTCCATTAGAGTCATAAACGAGACAACAAGACTGA
          CGTACCGATTTAGCGTCTGATATAATAGGTCCAGCACCACAAGACCGCATAATAATTATC
          CGTGCTGATTCGTCGCCCGCCGGAGTCAACTCACTACTATATAGTGAACCCCTAACAGTA

          GGTTGACCACCGGCTGTGCAGGCCTACACCTACGCTTTTATCCTGGCGATGTGCATTCTC
          GGTTGACCACCGGCTGTGCAGGCCTACACCTATGCTTTTATCCTGGCGATGTGCATTCAC
          CGTTCCTATCCGGAACGATGAGACGATCTGCTTAGTACCCAGCAGAAACAGCCCGCTTGT
          CGTTTCAATCCGGAACGATGAGACAATCTGCTTAGTACCCAGCAGAAAGAGCCCGCTTGA
          AATATGTGGGCACACCTGCGCGATACTACGACCGTGCCCCCTATGGGACCAACGAATTAC
          GGTTCACGTTCAAAATCGCGTACATTGATGACGTTTTATCATGCCGGGATGGAGAATTTC
          GATACTTTGCCACAACTGCGCACAGCGAAGCGTGAACACTCCTATGAAGCAAAGGGCCGT
          GACGAACTCGTAGATCGGCACGTAGTGACGATCGTACCCTCCACAGAAAGGTTGTACCAT

          AGCGAAGTAGCGTAAAGCCGGGGAATACCCTTTTGTTGAAGTGTACACGGTCTGGATTTC
          AGCGCAGTAGCGTAAAGCCGGGGAATACCCTTTTGTTGAAGTGTACACGGTCCGGATTTC
          TACGTCGGGGCGCTTACAATACTGTTTATTGTGATTCGTTGGACCCTTTGTTAGTGTCAT
          TACGTCGGGGCGCTTACAATACTGTTTATTTTGATTCGTTGGACCCTTTGTTCGTGTTAC
          TGTCCACGTCCGGTGCGAAGTCTGGGCGTTTGTAATCGTGGAGGCCTGCACTCGCCTTAT
          TGTGCTTGTGAAAAAAGGCAAATGCGCATTTGCAGGTACAGAATTCAATACCAACAACCC
          TGTCCAGTTCCGTAGCGGAATGAGAACGCCTGCGGTCGAAGGGCTCTGCGTCAGTCCTGA
          TCTGCAGATGTGGCAGGAAACGGAAACACTCGCGGCCACGGGGCTCAAACCCCGCATAGG

          CCAAGCATCAGCACGGCGCCCACCCGCGAGTTATCTTGGTGCCTAGGACAGTGCTGTTAC
          CCAAGCATCAGCACGGCGCCTATCCGCGAGTTATCTTGGTGCCTAGGACAGTGTTGTTAC
          CCGTATTTTGTTGCCTCGTTCCCGCTAAGAGCAGATAATTGTGCAGTCCTATCCCATCTG
          CCGCATTCTGTTGCCTCGCTCTCGCTCCGACCAGATAATTGTGCAATTCTATCCCGTCTG
          TCGTCTATCGGATATATGATCTCGTGTTAGTGCCCGCGCAGCCCCATTCGACCCTGACCT
          CTGTACATTCTATCGATAACACTATCTGAGCTCCTAGTAGGCTACACTCGTTACTGACCA
          AAGCCTATCATGTTCGCTGTCGTTCGCAGGCACCTGCTGGGCCCCTGCTGCACCGGATCG
          TTGACCATGGTGCCCGCATCTATCAGCCAGCACTCGTGAAATTCATACTAGCTCACAACG

          TGCCCCTCGGAGTGGCAAGTCTCGCATGCCCCATTATTCTGAAAAGTTTCGTGATACTCG
          TGACCCTCGGAGTGGCAAGTCTCGCATGCCCCATTATTCTGAAAAGTTCCGTGATACTCG
          AACTGGATGGGGTCCATAGCTCTGCTCACGTCATTGCACTACTAACTTAGGCATTGGCGA
          AACTGGATGGGGTCCGCAGCTCTGCTCACGTCATTGCACTACTAACTTAGGCATTGACGA
          ACCCGACTGAGATGCGGACACCTGCGTACTTCGGAACGTCGCTGAGCGCCGGGTTCTTGC
          AGTTAGCGAAGACAGCTAATTACGTCCCCCCTGTAATTCTGTACAGCGCTGAGTCCCTGC
          CACCCTTCAGTATACTCATTACTGTCCATCTTGGATCGCCGGGAGCCGCCGTAATAATGC
          AGCATATAAGGATACGCCTGCATGCTTAATTCGTTAGGCCGAAACCTGATACGGGAGTGC

          CAAAGGTTGGCCGCCTACTTCGAACCTGAGAGTGACTCGG
          CAAAGGTTGGCCGCCTACTTCGAACCTGAGAGTGACTCGG
          CTACCATTAATTCTTGTTTGTTGATTTAAAATTCTTGTTA
          ATACCACCAATTCTTGTTTGTTAATCTAAAATTCTTGTTA
          CCGGATTAAGGTGTTTCGGCGCCAGTGAAGTACGTTGTTG
          CCAGATTCTAACGGTCAGGGGTAAACAAACCATGTGCCAG
          TCAAAATGTGCTGTTTTAGCGCAAGTTAGTACCGGTTTGG
          TCCAAGATGGCTGCTTCGACGCAGGCAAGCCATGTCCCAG

