 8 1000
t1        CATCTAAGGCTCAGTGCTCGATAGCCTGTCATGCGTCTGCACACACCCCCGACGCCATGT
t2        CATCTTAGGATCAGCGGGCGACGGTCTGTTATGGATCTGCACACATCCCTAACGTCAAGC
t3        CATCTATGGGTCAGCGGGTGACGGTCTGACCTGGGTCCGCACACATCCCCCACACCAAGT
t4        CGTACAGGCCTTAGCAGAGGACAGTTCGTCATGAGTCCGCAAACACGGGGGGAGTACTAT
t5        TTAACTGGAGCCTCCGGACAACGGACTGCCAAGCGCGTGTAGCTACACGTAACGTCAACC
t6        TGATCCAAAACACGTGGATATAAGTCAGGTCCGTGATCGCGAGCATTTACGGAGTGGGAT
t7        CATCTCACGATCAAAGAATGGGATCTCGTTATGCTTTAATTAGCTCGTGTCAATGTTTGT
t8        GCAGCCTGGATTTGGCTGAGATAGCCGATCACGTTCACATACGCAAAAATGATCGAGAAG

          ATGACGTATAAGCAAACACAAGATTGCAGTAAGAATGCTACCGCTGTTTGTCACCGCTGG
          ATGAAGTATAAGCAAACGCCAGATTGCGGTCAGAATGCTGGAGCCGTGCGTCACCGTTGG
          AAGAAGTATAAGCAAGCACAAGATTGCGGTCAGGATGCCTGAGCTGTTCATCACCGCGGG
          GCGCCCACGAAGTAGACAAACAGTTACATTAAGCTCGTTGGCTCTATTCATACCAGGACG
          TCGAATTTACAGCGGGTGTAAAGCCACTGTAGAAATGCAGGCGGTGTACTTCATCGAGAG
          ACGTGCGTAGAAAGGGTTCTACGTTAGGGTATTAAAATTGGACCTGACCGCTTCAGCCGA
          GCACCGACGAAGACAGCTTGTGGGGATAATAATAAGGATGTTAGCTCCAGAATTTATGGG
          GAGCACAAATAGGCAGCACAAGACGGAAAGCCCAACGACGGGGGTACCAGTAACCAACAA

          CTAGTTGCACCAGATCAATACTGAAGCATAGCCACCTAGTATATTTATTCTCTATGTCAC
          CTAGTTACGCTAGATCGTCACTGAAGCATCGCCATCTAGTATACTTATCCCCCACGCTCC
          CACTTTGCCCTAGATCGATGTTGAAGCATCGGCACCGCGTATATTTGTCCCCTATGTCGC
          TCCGCTATATGGAATCGGCCCTGAACTGGTTCCTGTCAGTATAATTACCTCCCCATTTAC
          CCAGCTGAATCCAGTCGATCCACCAAAGCTTTTTTGCCGCATGCCCGTAGACAACACTCA
          ACAGTTTTATTTAATCGTTCCGGTAACTTTCTTGCTCGGTATTACGTCTGAACATTTTGT
          TACCTCGTACCATGACATCTAGTATTTGCTTCGATCCGCTTTTTCTCCTTCAAATCCTGC
          GGTATATCGACGACACGTCTAATATTAATCCCGATCAGACGCCATGTATAACTTCTTCCG

          GACGACTAAGCAATACGACCACGTATCCTGGGCTTCGTTCTACTTAGTCTTAAATAGCAG
          GACGAAAAAGCACCACGACCATGTATCCTAGGGTTAGCTCCACTCATTTTTAAACAGCCG
          GCCGAATAAACTATACGGTTACGTCTCCTGGGATTCGATCAACTTATTTTTAAATGGCAG
          GGCGAACAGGGAGTAACGTTACATACCTCAAAACCGATCTTGTACGTCCTCATCTTGCAG
          TATCGGCCGGATTCAAAGTCGTGAATTCGAGTCACGCATTTTCCCATACTAGTGCGACGG
          AAAGGCTAGGAATCAAGGTCGTGAGCTCTGGGCATGGTTCCACGCGTGGTCCATCGTTGC
          TGTAAATAGAGTTAGCGGAAGCACATCCGCATCTTCGGTCGAACTGTCATCGCATTTTAA
          TATGGTCAGGTTTCGGAGGAGCGATCCAAAAGCCCTCCCCTATGGGCTGCAATGTATTGC

          TTGGTAATCTAGCGGCCCAACCATTATAATGCTCAACGATGCTCTGGACGAAGAGGATTT
          TCGGAAATCTAACAGCTCAACGGTTACAATGCTCAGCAATGCCCTGGACGATGTTGATTT
          CCGGTCATCTAACGGCCCAACAATCACAATGCTCAGCAATGTTCTGGACAATGTGGATTT
          CTGGATTTTGGTTCACCTCATCGACATGAAGACAGTAAGCGTCCTAGCCAAAGTGGACTT
          TCGGCATCTGGGGCGTCAGCATGTCATGACCTAATCCGGCGCTTGGGCACGTGCGAGTTC
          TTGGGGAAGGGCCTGCGGTAGTGTCAATGTGAGCTTGCTCATAAAAGTAGGCCTACATTG
          CTGGCGTTTAAACTGCCCCATTCCGGTGCTGCTGATTAGTACCAAGGCTACCGCGGACCC
          ATAGGGCCAGAGTTTACGCAAGGCCAAGCCAGTCACGCGGGCCGCGAACACCTTGCATCA

          TGCTAGCACATAGCTCTCTTGCCAAGAAGATTGCGTGCTGACGGCCGAGGCGGATGAATA
          TGACGACATATAGCTCTTTCGCGAAGAAGATTGCGTGCTGACGACCGAGGTGGACTAGTA
          TGCAGGCACACAACCCTCGCGCCAAGAATTTCGCGTGCTGACAACCGAAGCGGATGAATA
          TACAGGTGATTACTCTGCTCTTGAACATATTTGTACGCCGCAACTCGTAGCGGGCGATCG
          CGCAGGCATTCACACTACGCGCCAAGGCCTCTGCGTGCTGATGCATGTAACGAGCTACCG
          CATCCTTTTTTAGACCTGGAGATGAGAGGCGCGCACGCTACTAGTAATTAAGACCTGGGG
          TGTAACGGTTTCGTGAAAGCGTAAGGGAACTTGCGTCTAGTTTACTGCTGGGGTCCGTCT
          ACAGAGCATCGGCACCCGGTCGCCGAGCGTCTGTGTACCCATACACTCAAACGATTCTCA

          TTCGGTCATCCCTATCGTTTTGGATTTCAACGCTTACCGAGGGGCTCAACTCTAGTGAAG
          TTTGGTCACCCCTATCGGTCCGTATCCCTACGCTAGCCGAGAGGATCCGCTCCAGTGAGC
          TTGTGTCATCTCTATCGCCTTAGATTCCAACGCCGGTCGAGAGGATCAGTTCCAGTGAGC
          TTAGGTGTTCATCGTCACCTTGAGGTCCGCCGATCATCGGCCGGTTAAGTCCAGGTGGGT
          ATTGGTCTTTAGTACCGATTTGAATCTCCACCGTTCCCGCGGGACCCAATCCCAATAGGT
          CCCTGTATCCCTCTGTAAATGCGAGATCAAGAATTTTTAGGAAAACGCCTGTGAATATAT
          TATTCCATCTCAGGTTTACCTCAGTTCCACCCATCTCTGGGCTAATCTCTACGCTGATAT
          TTGGATGCTCAAAGAGGGTCCAGGAAACAGGGTACCGATGACCGGGTTGCAAGCGCTCTC

          ACATCCGCATAACGAAAACCGGTCTACAACGAACCAGCAAGGATCGCGTGACGTTTAGTA
          AAATTAGCCTTATAAAAATCAGTCTACAACGAACCAGCAAGGATTTTGCGAAGTTTAGTA
          TGATCTGTATAGCAAAATCCGATTTATAAAGAACCAGCAAGGATTGCGCGACGTCTAGTA
          CCACAAGCACCATATAACCCAGCTCGGAAAAAGTTTGACAGGCCTGCGATAAGCATCATA
          GTACTGGTTCCCAAAGGTGTGGCCTACAAGGACTTATCTAAATCTACGAGGTGCCTCGCA
          ACTGATAGTTAGGCAAGGCTAGACGAGATTAACTCGAACAGACATCCGCGAACCTTCCAT
          ACGTGCTGCAAAGAAGCATCGGTTTACAAAAGTTTGACCAGGCCCGCGAGTAATACCGTA
          CTATACAAACCGGCCGCATTGAGACGCAACAGACGCATCCAGTCGGCGGACGCTTATCAG

          TCTCGGGACAGTCTACAGTGCGTTTCCTTGGGGTTCCTTATCAAATTCGACACATGTCGG
          TGTATGGACAGTTTACAGTGCGTTCCTATGGCGCTCCTGACTAAATTCGACGCATATCCG
          TGAATGGACAGTTTACAGTGCGTTTCCTTGGGGCTGTTGATCAAATTCGATGCATGTCAG
          TATGTGGGAGACTATGCGCTTGATTTGTCAGCCCCGCTGGCTAATCTTGCAGACCTACAA
          TAGCTTTTTAGCTGGAGAATCGAGTTCAAGTCCCGGGCGGCTAAGCGCGACGTATCATGT
          CAGTTGCGCAATCCGTCATTTGCATTCTTCTAACCCTAGCCCAGTGACGAAATGCTCGAA
          TTTCCTTGGGAACCGTAGTTCATTTCTTCATGGTAGCAGGTCAGAACTGCCGGGGGGCTA
          TAGCCTCGCGCTCCGCGGCTCGGTCTCACATTTCTTTAATATTGATGCGTCGCCAGGAGT

          AGTGCAGCTTTTAAGTGGGTAAACGCTAAGCTGATGGTTTAAACGGTAACCAAGGTGTGG
          AGTACAGTTTCTAAGTGGGTAGGCGTTAAGCCAGTGGGTTAAACGATTGACGAATTCTGG
          AGTGCAGCCTCTAAATGGGTAAAAGCCACGCTAGTGGTTTAGACGGTCAACGAAGTGTGG
          AAAACGAACCCTCAGTAGGTAACCGATGAATCGGCTGGATTGCATGTTAACGAGGTTTGT
          AGTACGACCTCTATGTGGATCACCATCGTGCGAACGGGGCCATTAGTCTACGATATCAGT
          CATGCTGTCGACTTATGGATAACTGCCAAGCCTTTCTGAACAACAGATAATGCAGCCACC
          CGCCTTCACTCTGCGAGGACCACTGTTAGTCCGGCCGGCCACGGCGATAACGGATCTCTA
          GGTATTTATCCTTCAACCGCAGTCAATGAAGCACCTGCTAGCGACACAATCGGTGATTCT

          TCAGCAGCACGGCGTATGTATCCCCTTTGTTTGCGTACCCACCCTATATGCTGCTTACCT
          GTAGCAGTCTGGCGCAGGCTTCCGATTTGTTTGAGTGCTCACCCCATACTCTGCCAACTC
          TTAGTAGTCTTGCGTAGGTCTTTGTTTAATTTACGTGCCCGCCCCATACGCTGCCTGCTT
          CTTGGGACACCGGACGGGTCTCCGACCTGACGGAGAGCCCTACTCGCTAGTCCCGTGGTC
          CAGGGAGTTTACGATGGTCCTAAGCCTAGCATGATTGCCGCTCTCATTCTTTTCTTGATC
          TCGGAACCGCGAAGCAGGTCCTCGCCTCATTGCAGGTACAGCACTTAGTGCCATTAAGTC
          TGACAGGAATGGCGTCGACGCGAACCACATCAGCCTTTTAACCAAACACGCTCATCACTC
          TCGAAGGATCGTCACTCATTTCTAACCCTGCCAATTCCGAGCATGGTATGGAGACGAATA

          TTATTTGTCTGAGAGTAAACCCACCATAATTCCAGCGTTATGATGATTGCACCAGTCACC
          GCATCAGTCGGAGCGCAAACTCATCATGATCACTGCGCTATGATGGTTGCACCGGTAATG
          CCATCAGTCGGACAGTAAACTTATCATGATCCCTGCGTTACGATGCTCGCGCTAGTAACC
          AGATGAACGTAGCAGCTGGAACACGTCGTTTCTTATACTAGGACGACTGCGTCGCCGAAC
          AGACTAGCATAATAGTCGGCCTACCATGTCCGCTGTGCCAGGACAAATGGGCTAGGGCTC
          TGACGGCTACCGGTGGCGTCTTTCAGCGCCCTTGGCTGAAAAGAGTTTGCACTTGTGATC
          AAAATCACACATCTGACGAAGTACAGTGCTCCCTGCGAAAAGCGAACTTAATCCACTATA
          AGATTGTCGCTATAGAGCTATGGCGACGCTCTCAACCTATGTGGGATTGCCCGAGCGCTG

          AAGATACGGCAGCGCGGGGTCTGATTGAGATGTAATTGGTCCTAAGGGGGGTGAAATAGA
          GGAACATGACAACGCAGGGGTGGGTGGAGACGTAATCGGTGATAAGGAGGGTGGGGTAGG
          AGAATACGGCAGCGCAGGAGTGGGTTGGGACGTAATTTGTGCTAAGGAGGGCGGAGTGGA
          GGAACCCATGGGCTAAGTCGCGGGATACCAAGCCATTCGAATTCAGACCAGTAAATTCAC
          GAAACACGAAGACCTAACGGAGACTCGCTGGACAACTCGCATTCAGATAAGTGAACAATT
          AGGTTACGAGGGTCCGGTAGTGCGTTATGCTGTAGCACGCATTAACGAGAACGAAAGAAC
          GGGTATTGGGGGTCTAGGGGCGTCCCTAAAACTAGCAGGTGTCTATGTCGAGGAGTGGGG
          GGTGACAACAGACGATGTGGCTGTCTACGAAACATCTTTCACTTGGCTCTTAAAGAATTC

          GGTCAGACCTCACTGTTGTCGGAAAACGATGTTGATAAGTCGACACACTCGGATCAGGGC
          GGTTTGATCTAACTGCCGGCGCGGCACGAGGGTGATATATTGACAAACACGGATTAGCGA
          GGCTAGACCTAATTGTCGTCGGGGAATGAGGTCGATATACCGACAAACCCGAACTAGCGC
          GGGAGCAGTGTGTTGTTGAACTGGCACGAGGTCGATATATAAATAGGTTTTGTTGGTTTC
          AGCTGCCTATCACTCGCAGTCAGGAAAGATAACGATACATGGTTGTACTTGGACTAGATT
          GCTGTGGTTCTAGCGCCGGACTGGATCTACTCTAATATATTAACATGTTAAGAATCCGTA
          GTATGGATATCATTTTTGTACTAGACGACCGACATCAGCCTGGATAACCAGCATAATGGA
          GTGGGGATTAACTGGTAAGGTCGGAATTGCAACGGCTATCCGGTATAGAAGAAGGGCGGT

          CCGCAGGCCCATTCCCTGGCCCCATCGTATTTTATAGGGTGAGGCGTCCCAGCGCCGTAA
          CCGCAGACCCACCCTCCGGCACCATCGTGCTATACAGGATGAGGCATCCTATGACTGTAA
          CCGCGGGCTTACTCCTCGGCACTCTCGTGCATTACAGGATGATGCGTCCGATTGCCATAA
          ACGTATCCTAGCTCCCCGGCGTGCCCGCGATCTATTAGTTATCGCGCTCGTTTGTCACGA
          GCGTGTTCAATGTACTAGGCGCTTGAGTGAATTGGAGACCGGAGCGGCCGATTGCCTTGA
          CCGTGGTCTATGTTTCCGGATTCACTGTGAACCGTAGGACAGGGTGCCCAGAGGTTTCGG
          CGGCTAGATGGTCTCTACGAACCACCGTTCATTGCATAACGAGGCGCTTAGAAAGCTAGC
          GCACAAGAGAGACCCCCAGTTCTTCCGAGCAACGGTGGTAACCAGCAGCTAATAAAGTCT

          ATTACAGGCAGGGCGACTATAGTGATCATCTAGAACTGGAGACCGACTCGCAAATTGCGT
          ATTGCAGACCGGCTGTCTCTAGTGATCATCTAGAATTGGAGACTGATCTGCAAATTGCGT
          ATTGCAGACCAGCTGCTTTCAATGTTCGTCTAGAACTGGAGGCCGATCCGTAAATTGCGT
          ATCGAAGACCAGTTCTTTAAAGCGACTACCTCGTAGCAGCAACCTGTTTCGAGCGTTTAT
          ACAAAGGAATACCTGCCTTAAGCGATTATTATAGTCTGGCGATAAGTCAATACATTGCCT
          ATAGGACATATGTGCCTTGGCCCGACATGCTTGAGACAGTTACAAGCCCGCAGATCTCGC
          GAGGCTGATCGGTCAATTGCATTGTTTCTATTACCTTAGCGGCTTGTACGCACATTGCAT
          ATTGCGGCCAGACTGTCGCAGTCGGCAAGCAAGGGCTGGTATGTTGGGCCAAAGCGGTGG

          CGCATCCACGCAGGTTGGTCGCTACGACTACCTGGCACTC
          AGCATCCAAGCAGGTCGGTCGCTACAACTACCTGGCATTC
          AGCACCCAAGTAGCTATGTCCCAAAGATCGCCTGGCACTC
          AGCGTTTAGGCAGACCTGTCGATACATTCACTCAGTGCTC
          TACAGAGACCTAGGGGTATATATGCAACTATCCGACTCGT
          GTTATTACAGGAAGGCTTCTACCGGGAACACTTAGCGTTT
          GGCCTAGTAGAAGGTTACTCGCAACAAACACCCGGCGCCT
          ATTGGCGTAGACGAACCTTTGTCGTGGGTTATGCCCGCCG

