 8 1000
t1        GATGTTACTCAACGGATCCGTCAGTGGGGTGGGTAGGAATTCCTAGAAGGTACGAACATG
t2        TATGTTACACAACGGATCCGGCAGTGGAGTGAGTAGGACTTCCTAGAAGGTACGAACATG
t3        GATGTTGTTTGACGGATTCGGCAGTGGGGCGAGTGGGAACTTCCAGAACCAGCGAGCATG
t4        AAAGTCACTTCGCGGGCTCGGTCGTGGAGCGAGTATGAACCCCGAAAGCGCACGAATACG
t5        AATGCTCTCCAACGGGCTAACCATTCAAGCGAGTTGGACCTACTTGGGAAAACGCAATGT
t6        AATGTTTTCCAAAGGCCTAATCGTTTAAGCGAGCTGGACCTGCTCGGGGATACGAAAGGT
t7        TAAAATACAGAATTCGTTGAGTTGAAAGCTTTATGGTACGTTCCTGGGTAATGAAGTCAA
t8        CTATTCGTCATAGCTATTGATCCGCGATTTCCAGCCGAGGCACCGCGATGATCCAGTGTA

          AACATGTCACATAATCATGACGTATCTTGAGACTTGTCCCCTGTCTATCTATATTTCCTC
          AACACGTCACATTATCATGTCGTATCATGAGATTCGTCCCCTGTCTACCTATATTTCTTC
          AATACGACACAGTATCGCGAAGTGACATGAGAATCGAACCTTGTCTGCCTATCTTTCTTA
          AACATGACACCCTATCGTGACGTATCATAAGCGTCGCTCCTCGTCAGTCTATATATTTTC
          TAGTCTATAACAAATCAAGCCGGTCTACACAAGTAGCTTCTCGCTTCAATAAACTTCTCC
          TTGTTGATAACAAGTAAGGCCGGCCCGGACAAGCAGCTCCCCATTTCCACACATGTCCTC
          CTATCGAGACAGTATAGAGAGCCATACCGGTAGCAAAACTGTGCTTGATCACGTGATGCG
          AGCCTGCGACCTTACTGCGCCATGAATTCGGCGCTAGCGACGGCCCACCATTTAGTTTTC

          TTTTTAGCAGAGATACGGACGCTCGGTTACCTAACGGATTGTCTTTGCATTGCGACTAGC
          GTTTTAGCAGAGGCATAGACGTTTGGCTGTTCATTGGATTGCCTGTGAATTGCGACTAGC
          CTTTTAACAGGTGTACAGACGCACGGACGACTACTGGATTGACAGTGCAATGCGCCTAAC
          CTTTAAGCTGGGGTCTTAACGCGCGGCTATCTACTAGATTGTCAGTGCATTAAGCCTATC
          AATTTTGCCAGGGAGCGAGAGCATGAAAGATATTTGCCTAGCCTGCAACTAGTGCCTTAT
          GGTTTTGCAAGGGTGCGAGCACACGAAATATGCTTATCTAGCCTGCAGCTAGCGCCTAGT
          CACACCACGGGAAGATTATAATGTGTTGATTTCGTCCCCTTTAGATTTCCCGCACTCATT
          TCCCACATTTGGGCGTCTGTTTGTGATGAATCCAAAACGCTGGGGTTTTGTCAGTACGAT

          CTATAGGAGTATGTAGCGCTCGGCTGGTTTAGTTGGGCATAGTGTGAGGCTTGACTGCTA
          CTGGTGAGGTATGCAGCGCTCGGCTGGTCTAATTGAGCGTAGATTGCGGCTTGTCTGTTA
          TTAATGGAGAACGCAGCCTGTGACTGGTTTAGTTAGGCGGGGATTAAGACTTGTCTGTTG
          TTAGTTATGAAAGCGGCTTTAGACTGTTTCAGTTGGGCGAATGACAGGAGCTGTGTGTTA
          CTAGTAGTGAACAAAGCGCTTAGCTCCTCTAGCCAAACTAAGCCGAAATCCTGACTGTGG
          CTAGTTGCGACCAAGGAGCTAAGCACCACTAGCCGGGCCAAGACTTTGTCCTGGCTGCCG
          ATACAGATCTGGACTAATAAAACGGGCTCAACCAACATGAACCCCATGCGATGGTCGTTG
          GTAGCAGCAAGGATCACAGTAATTCATACTACCCGTTCAGTTTCCTTACTGCATCAGCGC

          CGCAATTGACAAATGGTCGCAGCACCCCCTATGTAGTGAGGTAAAGCAAACACACTATCC
          CGCAATTAACAAATCGTCGCAGACCTCCCTATGTAGTGAGGGAGAGCAAATTCCATATCA
          CACAATTAACAAGTGGTCCCACACCCACCTATGTAGTTAGATTGAGCGACCACTGTATCT
          CGTGAACCAAAAGTCGTCCCAGTACTACTTAAGCAGTTAGGTTACGCAAACATTGTATCT
          TGCAAATACAGAGCTTCTATCCACTGCCTTATGGCGTAGGGTCAAACGAGCACTGAATCA
          TGTAATGACACAAACCATATCAACACCTTTATAGCACTGGATCATACGAGCAAAGAACCA
          CACACTACTCGCTGTCTACCAGCTCTACGATCACCTCGGGACATAATTTACGGCAATCTA
          TTCCCTGCCTGTCCTCCACCGTACACGTTAGCTATGATGCGAAATGTTCAGGTCTCCAAA

          GATTTAGTTACTAATAGTACGCCCAGTTCCACCCGTTATAGGCATGTCTTCAGAAGTGTA
          GGTTTAACCACTTATGGTACCGCCAGTTCCATCTGTTATAGGCATATCTCTAGAAGTGTA
          AATCTGATTGCCATTAGTATGCCCTGTCGCACTCGTTAAACGGATGTTCCTCGAGGTACT
          CACTCGGCCACTACTAATACGCCCCGCCCCATTTATCCTCGGCTCGATCTCGAAACGGCA
          AGCTTGACTATCTCCCGTGCGAACCGATTTGTCGAATTTATGCGCGTCCATACTAAGGTA
          AGCGTGACTATCTCCTGTGCAGACCGATGTGTCCAATTTATGCACGACGATGCTAAGGTC
          AATCTTATTCCAGGTTCACCTTGACAGCCTAGTTCTTTTGAGGGCCCCTATGCCCAAATC
          GATCAGATTACCCTCCATTCAAGTTCTAAAGGATCGTAATAACACGTTCAAGTGCAGGAC

          CATCCTCACTTCTGACATTCACTCCGGTTTTTTAGGGGAGCTCGAACGTAATAAAAAGAA
          CATCCTCACTTTTGACATTCACCCCGGTCTTTCTGGGGAGCTTGCATGCGGTAGCAAGAA
          TACCCTCAGTTTAGACAATTACTTTGGTTTTTTAGGGGCGCTCGAATGCAGCTAGAAGAC
          CAGCTTCCCTTTAGACGGTAGTTTCGGTTTTTTAGGGGCGCTTGAACGCAGTAGGAAGAA
          TAGCTCTGTTCCAACAAAACAATCTGAGTAAGTCCGGGTGATTGATAGAAAAATACAGGA
          TAGCGCTGTCCCAAACAAACACTATGGGTAGATCGGGGCGATTGGTAGAAAAATCAAGGA
          ATGCGACCGTGGGTTTGTGGTTGACCACCCTAACGGCATTTCAGATGATAACAACAAGAA
          CTGCCTTCCTCTAAATTCAGCTAACCTGCTAATGGGCCTGTTGTAGGCTCTAATGAAGCT

          AGTCGCAACCCAATAGACATGAGAACGCCTAATCTTCTCGTCAGGGACGTATATCATAGT
          AGTTGCAATCCAGTAGATAGAGGATCGCCTAATCTTCTCGACAAGGACGTCTGTCATAGT
          AGTCGTAACCCGGAAGACATAAGAACGTCTAACCTTCGCGCCCGCGGAGCCCATTATGGT
          CGATGTAGGCCTACTGACATAGGAACGCTCTACCTCCTTGCCCGGGACGCCCATAATCGT
          TATTGCTAAGCGATAGAGATCCGCACGTTCAATCCCCACGCCCGGGATGACTATAACCAC
          TACTGTCAACCTATAGATATCCGCACGCCCACTCGCTCTGTTCGGGATGACTTTAGCCAG
          GAACCGTCCTTTTTATTGTCAGGCGGGGGCGCTTATCTCGGTCCGGAGAATCTAGGGCAT
          AGGTGGTTTTATCCGATATCGAAGGAACTTGCATGGCTCAAGGTCTAGGATTTGGATTGC

          GTATGCTAAAGGCGGCCCCTGTTCTCATACCGCCTGATTTTACGAGTAGGGCTTCTATCG
          GTATGCTAAAAGTGGCCTCTGTTCCTGTACCGCCAGATTATACATGTAGGGCTTCTACCG
          GTGTGCTAAAGGTGGCATATGTTCCCACATCGCAACATCATGAACGTAGGGTTCCCTTCG
          GTGCGCTGGGGGGGGCCTCTACTCCAATACCGTAATGTTATATACGTAGGGTAACTACCG
          CTAGAACAAGCGCGGTCTAGGTTCCGAGACGGTAATGCTTAGTACGCAGGGTCTTCATTG
          CCAGAATAAATACGGTCTTGGCTCCAATCCGGAAGTGATTAGTACGCAGGGTTTCCGTTG
          TTAGCTTAAGGGTGTGGTTTCTAAGTTTCAGGCAATAGTCGAAAGGGCCCGAAGCCGTTG
          TCAAGATATAGATCCCCTTTCATAGAGCCCGGCACAGATTTACCTGTCAGAGTGTTCCTG

          TAAATCCATCGTGTACAAGACCAATCCCTAAGACCTGGGAGGGAGTCCCAGAGAACCCCA
          TAACTCCATCGTTTCAGAGAACAGTACGTAAGCCCTGGTAGGGAGTCCTAGAGAACACCA
          TAAATTCATCGTTTACGAGACCAAAATGCTGGTTCTGGCAGGGAGTTCCAGAGATCCCTA
          AAAATCAATGGCTCTTGAGGTCAACACGCTAGTTCTGAGAGCGTGCTTCAAGAACTCCCA
          TAAAATGAAAGCCCTTGAGGACACCGTTGTGGACCTAGAAAGGCGTGCCAAGGAATCCCT
          TAAAATGAACGCCCTTGCGGATACCGTCACGCACACGGAAGGGAGTGCCAGGGAATCCCT
          GGCAATGGTAATTTCTTAAGCTGTAGCCCCATAATAAGGAAGCGGCGTCGTAGAATAATG
          TAGGATCATCTCGGGTGAATGCAGAGTCACATATTGGGGCAGGAGTAGGCTGGCACTCAG

          ATGCCGGACGGGGGTCATTCCTCTGAACCCATAATGCGGGACCCTCCCACTATGTTGAAA
          ATGTCAGACGGGGGCCATCCCTCCGAACCCCTGATGCGGAACTCTCCCACTATATTGAAA
          ATGTCAGACGAGGATCAACCCTTCGCACCCATGATTTGGGAGCCTCCCAATATGCGAGAG
          GCGCTAGTCGAGGGCCACCCCACCGCATTTAGGACGTGAGGCGCCTCCACTGCGTCAACA
          AAGCTCAATGGAAGCAACCTCGTTGCCTTTAGTTTGTAGGATATTCCCACCTTCCAGGTA
          AAGCTTAACGGAAGCAACCTCATTGCCTCTAGTTTGGGGGATATTCTCATTCTCCAGGCA
          GAAAAGCGCACGTAAGAGGCCACGTCACACTACTTTTGGAGCGTCCTCACTCCAGAGCCA
          GTAACTGGCAGAAAGAGACCCACCCTCCTAAAGTCTAAATTCGTTATTATTTTGTTAACG

          ACAGAGGGGCTTATCCGGTTTTTCAAGCATTACATATTTGCGGTCTGATGGCCGCATCAG
          TCGGAGGGGCTCATTTGGTTATTCAGGAACTAGATATTTGCGGTCTGATGGCCGCACCAG
          GCGGAGGGGCCAAATTGGTCATTCAAGCATTACATATACACGGTTCGGTCGCCGCTCCAG
          GTGGGGGCACCCAACTAGTAGTTTTAGCATTGCATGTCCGCGGTTCGTCCGTCCCTCCAT
          TTGGAAGTATCCGGCTAGATGATCATGAGTAATTTGTGTACATCTCCACGGTCGTGCCGG
          TTGGAAGTGTCTGGCTAGATGTTCATTAGTAATTTCTGCTCAGCGCCATGGCCGTGCCGG
          TTGAGAGCGGCAAATTCGCAACCTGCGAACGCGTTGTGGCTGGAGCTTTCACTGTCGTTA
          GTACAGCAGAATAGCTAATAAATTACGGTCACCCTGTATCTACTGTAGTAGTTGATCCCA

          GTGGGTGCGAGGTAGGAGTGACTAAGGTAGTAATATCGTGTCATTTCCCCGAGAAAGGAG
          GTGGGTGCAAGGTAGGAGTGACTTAGGTGGTAATATCGTACGATTTCCCCGAGGATGGAG
          GTGGGCGCAAGGGAGGCATATCCTACATAGCATTAACATGCCCCTCCCCACAGAAAGGAG
          GTGAGGGAAAGGAGGGCGAAACATGGATAACAATATCGCGTCATTTCACTGAAAAAGGGT
          ATGGTTGTTATAGAAACGAGGCTCAAATGCTAACGTCGTCTTAATCTCCCGTAATGAGAG
          ATGGTCGAGATAAGAGCAAGACTCAAATGCTAATGTCGTGTCGATCTTCCGTAATGAGAG
          CGCTCTGCGAATTAGGCCATAACAATGTTCATATGATGGGATTGACCTATGCATAACCCA
          GGTTGGGGGGGGAAGAACAAGCCTTACAATTCAGGTAGGGATGACTATACATGTAGATTT

          GAAGAATTAAGGAACTTCCGGCTGCGTCTACAGTACAAGCCGTGATATTCCGTTTGACTT
          GAAGGCTTAAGGGACTTCCGAACGCGTACACAGCACAAGCCGTGAAATTCCGTCTCACCT
          GAAGACTGAAAAGACTTCTTTACGCGTTCAAAGCACAAAACGTGACATTCCGTCTGACTT
          CCAGACCAAAATGACCTTTTAACTCGCCCATAGCACAAAACGCGACATTCCGTCCCACTT
          GTGAATTGAGAAACTTTTCCAGCTGGCTCGCACATAACAATGTAAAGTCGGGTCATACCT
          GAGAGTTGAGAAACCATTCCCCCTGGTTCACATACAACAATGTAAATTCGAACCTTGCTT
          ATGAGGAGACATATATACACTGTGGGGTCGATGGAGGATAAATATTGAACCAGCTGAGGG
          GTGAGAATTTATGTGTGTCTCACTACCTTGACGATACAAAGGCTACACTTTCAAATGTCT

          GCGAGCCCCTGCCAATATAATACCCACGTAACATTCAGACGAGCTAGTCCAGAGATTTCT
          GAGAGCTCCCGCCAACTTAACACCCACGCGACAGTCAGTGGGGCTGGTGCACAGATTTCT
          GCGAGCCCCCGTCAAGATCGCATTCACGTAACATTCAAAACGGCGGATCCAGGGATTGCT
          ACGAGCTCCCGTCAACATCACACTCACCAAACATACAAAGAAACTAGACCAGGGCTTGTT
          GTGAACCCCTATCGAAATTTTTTATAAGGCGTAACACGCATGACTCCAACGGACGTTACA
          GTAAGCCCTCATTGACATTACTTACAAAAGGTAACACGAATAACACCAACGGAGGTTATA
          AACGGTGGCGAACTCTACTTCACACACCGGCTAGCTAGATAAACTTTTCAAGCACCTTAT
          GAGAGCTTCGAGCCTGCATACACGTGAGACCCACCAGGGGAATATCTTCCTGAAATTCTT

          GACAGGATGACGAGAAGCCACTGCCCACTCATACAAATTCGGTGATGTTCACTAAGTTAA
          GACCAGATAGCGACAAGACAATGCCCGTTCATATAAATTCGGTGATATTCACTAAGTTAA
          GACCGGATTAAGTGAATTCACAGCCCGTTACTATAGGTTCAGTGATGTACACTACGTTAG
          GATCGAATAAAGAGAAGCCACGGACTGTTTCTTGAAACTGGGTGACGTTCCCTATGTCAG
          GTATGGCAAGCGGGAAACTAAGGTTCGAATTCACTTTTCTGGAGGGGGTAAACGTTTGTA
          GTATAGCAAGAGGGAAACAAACGTTCGACTTCATATTTCTGGGGAGGGTAAATGTATCTA
          AACTAGTAGCTATTTATGACGTGCGAATCACCTGGATGCCCGCGTGAAGTCACTTGTTTA
          GTACAACGGTAGACCAAACGAAGACACTATTGTATGGCCGTGTTCGGGATTCGCCTCATA

          TAGACTTCCGCAAACTCACATTACGCCCTAAAAGCCTCTG
          TAGGCTTCCGCAAACTGACATCACGCCCTAAAAGCCTCTG
          TAGGCTTACGCACACTCATATCGTGCCATAAAAACCTCTA
          TAAATTTCCGCGAACTTGCATTGTCCAGCGAAACCCTCTG
          CAGCCCCAGGTCAATTCCGACCTCGATCTGACCGGCATTG
          CAGTCCCAGGTCAACCATGACTTCGATCTGCACGGCTTTG
          TCTCTTACCCACTACTGGCATGGGTGCTTGTATAGTATCT
          ATCTTATCGCCTGACGTGCAGTATACCAGGATTTATACCA

