 8 1000
t1        GCTTTCATTTACTTTTTCTCGTATCCACATGAGAAAGTACAGCTGAAAACACACAGCACG
t2        GCTTTCCTGTCCTCTTGATTGTACCCCCATGAGAAAGTATAGCGGAAATCACACAGCACG
t3        GTCTTTCACTCCACCCGACCGCTTCCTTGTACGAGTGTTTGGGTACCTCGTAACCGTCTT
t4        GGTGGCCTGTACATCTGACAGTACCCTCCTGTCATCGACAAAAGAAACCCCGACAGTTTG
t5        GAAAGTGCGAACAGTCGGCTGTGTAATTGTAAAAGCTTTCATGTGAGCTGTGACGTTACT
t6        TAATTTTTATTTGCAACAGCGTCGTTTCGCAAGTGCGCCTAAATTGTTGCGAACGGTACC
t7        GGCCACTTTCAGTCTCGGCCGTCCCCTCGCGAGTTACTAGACGCCACCTCAAATCGCATA
t8        AGTCGACCGGTCATCATCTTGGTCGCACGCGTACACGCTTAAGGCGCGACCTGTCATGCC

          GGAACAGGCTGTCATTTTCAAGCTTCATTCATGTGGTAGGAGACCAAAATCATACGTCCA
          CGAACACGCGGTCATTTTTAAGTTTCATTTATCTCGTAGGAGACCGACATCATACGCCCA
          CAAATTCTAGGTCATTTTTTACGTCCACCGGTGCGGTTGAGGCCCGAAGGAGGACGCTTC
          TAAGCTTAACCCCGTCATGGAAGATCGCCGGACAAGCGGCAGTCTGATAGCGACCCCTGC
          CAGAGTATAAACTATCTCGGATGCTCATCGGCGGAGTTGAGGGGTCAATGCATATATCGC
          TGACTCGCCAGTTGATCCTGAAGCCTATCAGAATACCTGGAGTCCGTCTATGAGTGTTGT
          TGATCCTCAGCGAGCAGGTGCCCTCCTTCGATATGGTCGGGGATAGGAAAAACTCACTGA
          CCAAACGGTAGCCGTAATCGTGTCTTACAGAGTAATACAAGATTCGAACAGTTGCGGAGC

          GGAGACCGGGCGAATTATGCCCATCTAGAGCAGTGGTGAAGGAAGTCTGGGCCGATGTCA
          GACGACCAGGTGAGTTAGGCCCATTAAGAGCGGTGGAGGACAATGTCCGGGTCAGTATCA
          AGAGTTCTAATGTACAACTACTAGGTAGGACTATGGACGTCTAAGCCTAGGTCTGTTTAG
          AACGGCACAACCACAAACCTTTGCCCGGTGACGGGAACTCTGTCGCTACAGTTGGCTATG
          GAAGACCGGCTGACTTATTGATGTTTAGGAACACAAGTGTTCTATTTGAGGTGGGGTATG
          CCAGGTTTGGCTAAGCTCCCCTTCTTCGGGGTGCGACTGGCCCGGCTTCGACGGAGGCTG
          GAAGGTAAAATGAGGCATGTACGTACAGGGAAACGCAAATCGCGGTATATGCTAGCAGCA
          ATAGCTCCCGCAACGTAATACTAGCGGGGGAAGCGCATCCTCTAAACCGTGACAGTGTCA

          CGGATAGCCGGACTCAGCACGGGTTTGGATAGTGAACGTATCGGAAGCGGGATCAGTCTC
          CGAATAGCAGGACGCAGCCCGGCTATGGACAGTGAACGTATTGGGAGCGAGATCCGTCGT
          TGACTAGACGATCGTAACCGCGCGCTTAGGCTTTCACGTGTTCGAGTCAGGTTTAAGCCC
          CATACTCAGGCGCGTTGGCTTGCGGTGGGTTGTGATCGTCAATAAAGCAAAACCGATGTT
          CGAATGCAAAGAGCTTGTTTCCCCGTTGCTCACGAAGCTCCCGTAAGCAAGACCCACTGT
          TGTAAACCGGGGCCTGTCTTCCCGGCGTGTTGAGAGTGCTGTCCAAGAAGGTCTACCCTC
          TTCACTAGGGTCGGGTGATTCACTCAGAAACCATTGATTCTTGGAGGTAGAACCCGATCT
          CGTGCGACGCAACATCCCCGCGCGTAATCATCAGGGGGTCTAACAAGTAATTTGCTCCCC

          GAACTTAGCGAGAGCAACTAATGTGGTAGGCATTCGCGCAACGACAATGAATACTCGTGG
          GAACCTCTCGAGAGCAACTAATGTGGTAAGCGTTAATGCAGCGAGAAAGAATATTGGGGA
          AACTTACGTCCGAGGAGCCGGGGCGTTCGCCTTAAGCGTGGAGGGTATCAGAGTGGAGTC
          TATTCATATGCGGGGTATTAGGACACTAGCCGTACCTGCAAATGGCCCGGGAGATAGAAC
          CAGCCGTACGTGAGAAAATAAGCTTCTAAGCGTTGGTAAACCTCATAACCAACTCAGAAG
          AGTGCAAGTACCAAAGGACTTGCTAATAGGGGTTGGGGAGTTAAGTGATGTTGCCGGAAA
          TACTTTCTAGCTAGCAGGCGTCGCCCAAGAGGTCTCTGCCAGGGAAGACCCCATGTGGAT
          TGGTCGCGCGACAAAACTCTAAATTCGTGAGCACGCGACGGTGATTACTGGCCACCGTTT

          CCATAAGCTTTTGAGAAGCCGGTCTATCGTAAGTATTCTACGAAATACGCGGCCACGGGC
          CAATAGGCTCATGAGAAGCCGGTCCGTTGTAAGTATTCTACGCACCGCGAGGTCATGGGC
          CCATATGCTGCTTAGCCGTTGGAAGACCGACGCGATGCTATTCGCCGCCAGAACATGTGA
          CCACGTTGTTCTAACGTAACGGCGTGCTGACGGATCGCCATGGATCACCCTGCTATTCAG
          TCTCACTGATACAGGGGGTCAGTTGCACGAGGGTCCGCGACATAGCGCCACAGTGGGCTA
          ACTCGCGGGTTACGTGAGTCGGCTAGCGTAGTGGTTCTCGCTTGCAGCCTGACTACGCGG
          TTGTCGAGACTCACTATTACTGTGTATTAAAAGATTGGGCATTAGTAATAGGCGGTGCTA
          AGAAACCACTGCTATGGGCTCTGGGGGCAAAAGGTAGGTACTTCGTTCATCCTAAAGCAG

          GTAGATGATCTCCCTGCTTCTGCAGTAGAACCGGTCGGAAGATGTTTTTAGTGACGCATC
          GTAGTTGATCCCCCAGCTCCTGCAGTAGAACTGGTCGGAAGTTTACTTTGGTGACATACC
          GTTGCTGGACTGCGTGTCCATGTAGCATTACAAGGAGGGTGCCACTGTGACTGCAATAAC
          GTCGATGCTCTAGATGCTCCCCACCCATGGCAAGTATGAAGCCTTTTTCGGACACACAAC
          GTCGATATCCAAAGATTAATTGCGATAGAAGTAGATAAATGCTAGTTACGTTGGTCTACT
          GTTGTAAACCACAACGCCTTTGACGTCGGGACCACGTACCACTTGCCTACTCGGTGACAT
          AATGTTGATCTTTCATCCGCTCCTGTCCTCGCCGGACGGCAACCAAATTAGTGTGATCGA
          ATCGTATATGTCAAGTACGTGATAGATCTACACCCAGGATGTTGGCCGAGGAAAATCAGC

          TGCTCTATCACCTACGTTCCTCTCGGAATTCCAAAACGCCTACGGAGATGTGAGGATATT
          TGCTCTATCACCTGTGTCCGTCCCGGAATTCTAAAACGCCTACAGAGATGTGAGGATAAT
          GGGTCGGTTATCTGTCGGCCCCGTAGAAATCCTGACCTCCCTCTACCGGGCTATGATAAT
          CGTGAGTTAATGCATGCAGTGCATTGAACTCTTAAGCAGTCCTAGGGGCCATCCGGTGAT
          AGGTTCATAGTTTGAGAACCCCAGAAAAATCTTATTGATTCCCAAGGCTAGCTAGCCGGT
          CGGCTGATTACGCATACACTCTACGGAGGTCCCGATGGTTCCCTGAGTCGTTTCACGATC
          TACCTGAATTTGGCTGCACCAGGCAGTGCGGCATGTCACTGCCGGTACCAATGCTCGATT
          CTGCCACCTCCTTCTGTGTTCGACAAAAGCCTAGACCATTGTCCGTGCCGCCTCAATGTA

          GCACCTGGGACTCTTCCTGGGGGGTCCCTTCCGATAATTTTGGTTCAATTAGGAGAAAGG
          GTACTTGGGACTCTTCCTGGGAGGGTCCTTCTGACAATTCTGGTAAAATCAAGGGAAATG
          ACATCTCAGTATTGTCGTGTAGCAGGCCTTCAGGCGTTCTTGAAAAAGCCAATTCACCTC
          TCACCCCGAAATGTTCGTGAAAACGATTTGCCGGCCCACTATACTTAATCGAGTGAAACA
          GGCTCTCTTACAGGGCGCGTAACGTGTTTTCCGATTCAAGGAGCGCTTCTCTGTATAATA
          GTGTCTCGGAGGAACTGAACGCTGAGCATCTAGACATTCCAAGACCAACCAGGTGTAAAT
          GCACTTTAGGCTTTCCGTTTAAGTACCTCTTATACGGCCTACGGGTGATCACACCCATGT
          GGCATTTTGCTCAGCCAACACGCAAACTTCCAGGATGTGACGACCATAATAGAGTCCCTT

          ATCAACAAACGTGTCCATCCTGAGAAGTGGATACGAACAGATACCCGTAACTAGCGATGT
          AGCAACAAGCCTGCCCATCCTGAGAAGTGACTACGAACAGATACTCGTAAATAGCGATGA
          ACAAAATAACGTGTTAAGCCTTAGTCCTGGGCGCTCAAGAAGACCGTTGGCGAGTTATGG
          AAGGAGCTATGCCCTCAGCGCCTGAGTCACGTAGTCAAGCTGCCTCGAGGCGAATTATGA
          TAAACAGGACGCTTCTACTCATAGCACTAATTACCCGGGTCGAATTGCGATGGACGATGC
          GACGTCAACCAAGTTCAGCCCGATTACTGTATCGCAAAACGCAATCGCCGCACGGTGTGA
          GAGCAGGTCTGTAATAAAATGCATCGCAGGGCACTAAGGGGGGGAAACGTCTCGTTACTG
          CGGCTATGAAGCTCATTAAAGATAAAAAGGTTGTATAAGTAGGATCTCTGCACGATATGT

          TGTGCAGTACCCCGCTGCAACGGTGTCGATGATGCCCGAGTACCCAGGAAGTGTCACTGG
          TGCACCTTACTCCGTTGCAACGGTGTCGATAATGCACGCGTACCCAGGAAGTACCACTGG
          ATTTTTTTGGTGCGGCACTGCGCTGCAGCTGATGCTCGAATGACGGAGGTGTGCTGAGGG
          TTCTCCAGATTCGGAGCCTGTGGTGCAGACACCGGCTAGATACTCCAGACAGGTGGGTCT
          CACGTCGGCTTCGGAGCCCACCACACGACAACCGCCCAAACCTACCCGGCGTGAAGAAAC
          ATTCGTAAAACTTAGAGTCATAATCTAGAACATGTTCGCATGCCCTAAACGCGCTTGGGA
          TCCGCGAGATTTTGGAGGTCCGTCTCCGCCAACGTTCGTATAGTAAACGTCTGGCGTTTA
          GCAACACGATTCTGAAACGCAACCAGAGGGATTGAGAGTGCAACATAAGTCTTTCGGATA

          GCGAAGGGATAGTGTGCGGATGCTATTGGATACGGTCTGGGAGGTCTGGAAGGATTTACT
          GGGCAGGGCTAGTGCGCGGATACTATTGGATACGGTTTGGGAGGTCTGGAGGAACTAAGT
          ACAGAGGGCCAGCATATGGAAACTGCCGGACATTGGCCATTCAACCTGGCTGGGGTCGCT
          GCAATGAGTCAGGACACGCTAATCCCGAGATGTGGAAATAGTAAACTTGTCGGATTTGCC
          ACATACGATCAAGATGCGGAGACGTTAGCACTTGCCTAATGTTGTATGGACGGTACCGCC
          GCCGAGGCTAAGCCCGCAAATCACTAAGAAGATGGTTTGAGCGACATCATCGATTCCGTC
          GTTAGTATGTGGTCTCAAGGTTACAGTTCCGTTTCTCCAAGCGTGCTTGTTCATTTCGCC
          TTGTATATGAGCAGGGCTGCCCACTTAGCGCGTGTTGTCTGTGTTTTCACTACGTTATAA

          CGTTCCTAGGCCTAGAAGCAGCCCCGCCGGGTTGAAGATGATGCTGCGGCACTTTCTCTA
          CGTTCTTAAGCCTAGAAACAGTTTCGCTGGGTTGAGGACGGTGCTGCGGCACTTTCACCA
          TGCTACTGTGCCCAAGAGCAAAATGCCCCGGACGAGCATGAATTTGTGACATGTTTATTG
          CCCTTCTACCGAAAGAAGGAACTATTCTGTGTTGCGAGAGATGTAAGAGCATGCCCACCG
          TAGTTATACGTTCTAGCAAAGATCTCTCGCCTTAGGTACCACGATGGTACATGGTCGCTC
          GATGCCCTCACAAGAATGGAGCCCTCACGTTAATCGTGCCATGCCTGTACCCCCCCATTG
          CTCTGCCTGGGTCGGAAACAGAATTCCAGTAAGATCCATACCCTATTGACGCTGACTTGA
          TAGGGATCTGCGCTCCTTTGACTATAGCTTAGCCGAACGGGTATTGGTTCGTAATTTCCC

          TAAACTTAGCATGCACGAGAGCTTGGGCTCATTTAGGTAAGCTACCGTCGAGAATGTAAA
          TAAACTTAGCATGCACGAGAGCTCGGGGTCACTTAGCTTAGCTGCCGTTGAGAGTGTAAA
          TGCAGTCGACGCGTGGGGAAACTCCCGGTTGCCAGGGCAGTCACCTGTCAGACCTATTAA
          TTTAAATGGTTTATAGGCGAGTATGAGGTCTCCATAGTAACTCACTGCTCGACTGGCCAG
          TTCGATTTGTATGCGAGAGAGTATGTAGCTACTGCAGATATTCATGGAGCGAGCCGAAAT
          TACACCCGGTACGTAAAAAAGCACTCGTTTATCAAGTAAACTAGCTGGGGAACAAGACGG
          CACCATATACTTAAGGGGGGCTACAAGCTTGAAGTATAAACCATGTGATTCTCCATCAGA
          CGCTATGTGGTAAAGCACTGGTGGGTATTCGGTGTGATCATGCTTCGTATAGAATATAGT

          TTTATTCAGCCTTCGGAGACTTTTATTTTACCACTCATTCGGGTGGACGACGTAAGTATG
          TCTTCCCTGCCTCCGGAGACTTTTATACTATCACTCATTCGAGTGGTCGACGTCGGTACG
          CTAATTTACCGCTCGGGGAACTCTACCGAATTTTTACCTCTACTTCATGATATCCGTCGT
          CAGGCTTCAGTCGAGGGTCCTCCTACGTTACGCCTAGTTTGCGAACGCGGCACAGGTTTG
          CTCTCCAAAGGCTCGGACATTCCTGCACCACTCCACCATTCCATGAATGGCACCAGTATG
          CTGGTCCCGGTAGTAGACACGTTTATTTCTTCCCTGCCCTCGGGTAACGCCATGCACACG
          CCAAGACAATTAGCGGCCTACGTAATTTTCTCTTAACTCCTTTTGTAGGGCATGAAGGGG
          TTCCAGTGAGCGTAGGCTTTCATCATCCCCTTTTCGCATTCTAGGGGTAGACTGCCCATG

          ATGAGAAGCCGAGTACTCCTAGACTAGAGGAAATGGAACTCAAGTCCTGCCCTAGTGAGC
          ATGAGAAGCCGAGTACTCCTAGACTAGAAGACGGGGAACTCAAGTCGTGCTCCGGTGAGG
          GACGGGAACGGGACAATGCCCGCCAACAGGGTGGCGTGCACAGGGGGTGTCGCGACGTCA
          GGAAGGATCCGAGTATTGCCCGTATCTTAGAAAGTAAGACTACCCCATTTCCGTGCAGCA
          CTTTTGCTTTGCATAAGTTCCAACTACCAGGAAGCGAGCTTAAGTAGGATCTCCACGAAG
          CTCACGAGTTGGGCAAAACTCGTTTGTCGGAAAACTGGCCAATGTCATACCCCTTTGATG
          CGGCGGACTCGAGTAGTTGTGGCGCATTGGTTGTGAGGTTTGAGCAATGGTTTCATACAT
          TTTATGTATCAATACATTTCCGAATGCTGCAGAGCTAGCTTTTGCAAGGGTTAAACGATT

          GAGGCCTTCCCTTGATGACACTGATCGTCTCGGTCTCCAC
          GAGGTCGACGCTCCATGGCACTGATCGTCTCGGCCTCGCC
          GCGTAAGACTACCCTTGATAACGACCATCCTGGTCTCGTA
          GAGAACGCTACGGGGAAACTATAATTACCTTTGCCCCACG
          CTAGCTGGACGACCCGAGGCAACATCCCCCTGGCCCTTCG
          ACGGTTGGCCAATTCAGACAAAGATTGACTTTGCCTCTGG
          TGGGATATATCCCAGGGTCTGTAAGTTTCCTGACTTTGTG
          CGGGGAAATGACTTCAGATCATTTAGTTCACAATTCCACG

