 8 1000
t1        TGCTGAACTGCGGTGATAACTGGTAAAAGACGTTCAATGGTCGGAGCGCATGTCAGACCT
t2        AGTCGTACTACGACTGCACGCCGTAATATATATTCTTTGATTAGGACGCTTACTCCTCCA
t3        TGTGATGCTGCGGACATCTTTAGCCAAAAACATACGTTTACTGGCCAGCGTATCCGGTGC
t4        TGCCACAGTACGGCAGTATTCTTTAAAGAATGGGAGGCGGATAGAGTATGTTCCCCGACC
t5        CGCCTTGCACCAGTTGTATCCCCCTTTTCATTTTCATATAAGGGAAGAGAATCCCAGTGT
t6        CACCCCAGTACGCTTGAGCCATGACAAATGCCTCAGGAGACACACGCGCCCATTATGTCA
t7        CGCATCCTAGCGACGATCTATATATAAAGCCCCTTACGGTTCAGGCTATTGCACCTACTA
t8        AGCCAAGTGGCGGCAACTTGTAGTTCCCACTACCTGTGATCGTGGGCACTACCATCATTA

          GTAAATGTGTTCACGCTCCCAGGCGTCTCAGGTTCAACGATGAAATAAGGTGCTTGAGGC
          GTCGTGACCTTCCTATTTTTGGACATTGTAGGTCTAACAATGAAATAGGGCGCTCGTAGT
          CTGTCGACCTGTTAATTTCAGGTTATTATGACTTTAACACTGAAACAGAGCGTACGCAAC
          CTGCTGGTTATGGAGCGCCAAATAACTCTACGTTTAATACTGAGACAGAGCATCGTCGGT
          TCCCTAGCCTACCACCATCAGTCCTCTCCAGAAATCCCTGTAAGAAATAGTACTCTTATA
          CTGCCGATGGCGCACTTAGAGGTTGTCTCAGGACACGAATTACAAGTAGCTCCCCCGATT
          GGAGAGGGGGAACAAAGCTTTGACGGCGCTGGGATCGAAACTCCCATCGTCTGTCACACC
          CTCGCGCTGGCGCTATCTATAGACATTCTTGGATCTTATTGGGATGCAGGTGAACGGATT

          CGACTGCGGACTGGGCCTTCTCGCCGCCTCCGCTATCAGTCTTGTTGACGCTGGTGCGAT
          CGACGGAGGATAGGGTCCGCTTGAACTCTGCGTTACTATCCCCACTTTTACTTCCGTAGT
          TGTAGGGGATTCGGAATAGCCTGGTGTCCGTACTTCCGGCTTCTTTTTAATCCCACCGAC
          CGATGGGGGGTCGAACCCAGTCGGCATCCGCGTTAACATCATTCCAATAGCGGATTTGCC
          CCGCGATGGACTAATCACTATAATCGTTCATTTTGTGCTATTCACCACTACCGTTACGCT
          CCACCAAGGGCTGGTCAGCCGTACCGTTTGCCCCGCGATACCCATCTAAATTGGTTCTCC
          TAACGCTGAAGTTCCCCTTTCATTATGGAATTCTGGTGGTATTGTGTTTGACGTTGCTCG
          CGAGGATGCGTTGATTTTGACAATCGCGGAACATGATGTGACTACTCCTGATACCCCCTT

          CGGTCTCGGGCAGTCCCGTTGGAGTAGGATGCGAGTACACTACCCTGGCCTTTGGTCCTC
          AGGCTTTGGGGAACACTATCGAAGCTTGCTGAAAGTACATTTCCAGGGTTCTACGCGGTG
          GGGCTAGTAGACGGATCAACCAGGTTGGAAAAAAGTACATTTCTGGTCCCACATTCCGAA
          AAGTCTTCAGCCGGAGTAATGAGGTCCAGTAATGGGGCCTCCTGAGGTCTCCGGGTGGTA
          AGACCCCGGTTGCGACTCATAGGGCTATACGCTGGAAGCTTACGGTCCGCCTAGTTCCCC
          AAATACTAGCTACAAGGTACTTGACTGTGTGGAGGAGAGTTACGGTATACGTGTGCCTTT
          GGGTAGTGGCTACGTGCAGAAAAGTTATGCACTGGTCGCTCCAAGCCCCACAGGTGATTG
          AAATTATTAATACCATCGACAAGACCGGGTCAGAGCCTTTCCTTGGGCCCTATAGTTCGG

          CCGAACCCCTAGCGCGGTATGTTCTGACTAACCCACCCACGTACGGAGACTATATCAAAT
          CCGCGCCTTTAGCCCGACCAAGCCCGGACAACTCACCCTTGCACGGGGACTGAGTCGATT
          CTACCTGCCCACTTGAGCCTGGCTTGGGTGGCCCTCTTCTCCGTACCGACCGCTTCCCGA
          TACTATTATCAAATTCCTCCGGCTTAATCGGACCTATTATCGACATCAGCACATCTATAC
          CGACAACTGTGATTGGACCCGGTCTGGTAGGAATTCCCACGTACGAAAAGGAAGTGGTCT
          CCGTATTGGATACCGGCTCCAATTTGGCAGGGTTTTTTGTGTACATAGGTAGTGTCAGTA
          TTATTTCGGTCTCCAGGTGAAGGTCGACAACTCTCATCCTTTGTGCAATCTATGCAGGAG
          CTCCATTCAAATTGGGACACCGGTAACGAGGCTTTTTCGCGTACAAGACTTCTACAAATG

          TCGGCATCCCTAATACATCCAACTAACTATTCGATCTGGACTCCCCTCCGTGAATTGAAT
          TTGGCATCACTGGCGACACAGACCAGCCACTAGACGTCGGCACTTTTTCTCCTATTGAGC
          CGAGTACCCTCAGCTACGTGGGCTAGATATCCGACGGCAAGCTTTCTCCTCTATTGGTCT
          TAAGTTCTTCTCGTGTCTTGCGCCTCCAATCATACTTCAAGGTTCTTGTCCGTATTGTCA
          AACGCGCCTCGAGGATCGACGAGACTGCCTCCCCGTCTAAGGGTCTAAATTGCTGTTTTT
          GACATGCCTACCAACGCCCTATATAGGCAGCAAATTTCGAGTTATATAAATGCTAGGATT
          TGCTCTGTTACTCGAAAATGGATTCTGAGTTTAATGTCCCGAACTATAATGAGCCTGCTT
          CGGGTAAGAACCAAAGCGCAAGAATAGGACCTAGTGTCCAACTTTATGATACTAGTAATT

          TCTATGCAATCACGTGTCTGCCCACGGGCATGGTTCCTGCCTGTTCGCTTAGACTGATGC
          CCAATCTAAACACATGCCGGATTACAACCTTGATGACCATCCACCTAATTATGCCGACGC
          CTGGGCCTAAGAAGCGCAAGATCAAGGGTTTAAGGCAGCCGCCCCCCCTACCACAATAAC
          CCACGGTGTGTGTCTGGCCGACTCACTACTCAATGCTTAAAAATCAGAAAAAGTCTGCGT
          CGAGAGTTCAGGTCGGCGGAAAGGCCATCTCCAGTCCCCGACGGTTAAGCTCATTGATCC
          TAATCGTAATAGTGGTATAGGGCACGATCTTGAAACATACTCTTCAGTATCTGTGCACTG
          TATTAGGAGAAGATCGCTAGACTATGTATCCAAGCTCGAAAAATTCGACTACATTGATAC
          CCTCTGTACGTTTTCGAACGAACGTATTCCCGGTTGCACTGCCCTTTGCCTCCCTGATGA

          CCCCAAAGTAACATTTCTAACGGCAAGAGTGGCAACATCAGAACTACGCACAAGCCGAGA
          TTTCGTAATAACTTAGCTAGTCGCGAGAATGCTAGTGCCACGATTACCCACAACTCGTGT
          TTTGACCACGGCAATATCCTTCCCGGAGAATGTAAAACTGTCATCATTTACTGACAGCCC
          ACCAGAGTCCCCGGAGTCCATGGCGCGAGTTCTTACGATTAAGGCATATAGGCATCGTCA
          TTAGATTCTGCTATCGTGACACGAAGGGACAGTCCCCAATGCCCATTTCACAAAAAGATA
          AGCGCTCGTAGTGCTATGACTTGATGAGCAGTCCGTAGTCTTATTGTCTCTTGAATGCCA
          GCAGCGCACGACATTCTTATCAGCCAGAATAGCTGGTAATTAGCAACTAGTTCAGCTATA
          CTTCGATACGGCTCTCCGACTGACCAGTGCAACGGTTAGTTCGCTACCTCTGAAGGCTTG

          CGTAAGATATAGCAGCCCCTACTACAAACAATAAACCTTAACTCTATGCCGACTTTAGCA
          GGCCAGATGCAGCAACCACTTCCAGGAGTCCCCAACATTAACCCTTTGTCGACTAGAACC
          AGGGAGCACTGCCTTGCGCTACAGAATATAATTAATGCAAACGTCCCCTGTGTCGTGACT
          GGGAGAGGGAAACAATTGTCAATGCCGACAACCGTGCTTGACTCTGTTCCACGCAACAAT
          GACGGGACTTACCTACTGACTCTTAGTCCAGCTTACACTCATCCCAGATTAACCATCATT
          GGTGACTAAGGTTTCTAAAAACAATACGAAATTGATGCCGGTCTGGTACTGTTACAACAT
          GGGAGAGAACACATGATGCTTCCGCTAGCAACCAATCGTCATGTAGATTCCCCCCAAACC
          ACAGAACTGGATTCGTCAGTCCCAGTTGCCGCCTGCCCTGAGGCGCCTTCCAACAGAGTT

          CCTTGTCTGCTCGTTTATTCGAGACGGTGAGTAAGCCTACCATCATTTACGTCCAGGTCT
          TATTGCCTGCCCGTCCTTTTGAGGCAGTGAATCGGGCCAACGTCACTCATTGCTAGGCCT
          TATTTACCGTCAGGCCGACCAAGGCTGCGACACCAGCAGGGATTCCTAGGGGGTCGGATT
          AGCGCACCATTTGTTTATTCCTGTCTCTACGCCATATCGCCCAATTTTGTGAACTGGGCT
          ATACCCAAGATATTGCATTCGCTGTAATGGTTTGAAACGACTTTTTTTGAGGCTTGGAGT
          CATCTCGTTGTGACCTGACTACAGTCCGGGATCTGATTTTCTACTTCCTAGATCTGCGGT
          TGTGCAGCATTAAGAAAATCACTTGAGCGGTTTTAAAAATCTTTGTCTGCGCCCTAAGCG
          AGCGTATAACCCATACGCCCGTCGGCGCAATGTTCTACGGGGCCCAACAGGACTCGAGTT

          GAACGCCGCGGTTGGGACTTGGATCCAACTGTTTTATGTCCCCCAACAAGGAGGGGCCTC
          GAGCGCTGCAGTTGAGGTCTGGGTCCGATAACCTTGAATTTTTAGACCGGGTAGAGATTT
          GCGTGAGGTGTTCGAGTCCCCGGAGTCGCAAGATGCATTTGAGTCGGAAAACCTTGATGC
          CCACCCAGTGCCTGAAGTTCAGGTTATGCCGGGCCGCGATAGGCGGCGGTTAATCACTCT
          TGACCTTATCTTTCGGCGATCCGCTTCGTGTAAGGTCATCTCAAGGTCGAAAAACCTTAC
          AAGTACTGCCTGCTGAGTACGAGCACAGTATAGAGAAGATTAGTGGCCGGGTAGTTAACT
          GGATGCTGGTTCATTGATGTCGTAGTCGAAAAGCCGTCGACGGAGGTTGATAGTAGACGT
          AAGCGCCAAACCCCAAGCCCTAACACCGCATAGCTACTTTGAACTGTTTAAACGCAACAT

          AGTCCGCGTCTTCGGGCCACCGATAACAGGACACTTATCTGTTCCTAGAGGGAGGGTTTG
          AGTATGTGGGTCACGAGTACCGTCAATAGGACACTTATACGTACTTAATAGGAGGGTCCA
          AGTATACTAATCTTTGTCAATGACTATGGAGTATGATCTCCTCTCCTAGTCAGTGGCTCG
          AATGCGTTGGTCTCCAACCGTGGCTACAGAGAATTATTTGGAACCTCGGGGACCCATCAT
          AATGTGACGGAGTGTGTAGATAACCATTGGAAGCGTCCGCAAGGCCGGCGGATGGTGTTA
          GATGCGGGGGGCTCCGACAGGAACTGCAATAATTCACGCGGAGACTTATAGGAAGCGCCT
          CACAAGCACTTTTGGTGGAAGGATAGTTAGGATCCAGTGTAAGTACTTATGTAAGGTCAT
          CGTGAAATCATTCGACAAATCCGGTCAAAGGGCTCAGCGTACCCAGAATACACCGGTGTG

          AACATCAAGTCGCTCTAAGTACCATGACGTCGGTTATCGCGGGAACTCCAAGAAAACATC
          ATCACACAGTTGCCCAAAGTCTCACCACGGCGAAGTTTTCGGAGAATTTCGGAAGACCCC
          TGTGACTAAGCTACTGGCATTACGTGGTATGATATTTGCCGGTATATCTTGAAACATTAA
          CACACACAGCCGGCCACCAACAGTGGACGCCAACCTTTTTTGCGACGGCTGCAGTGTTCA
          TAGATCAGGCCGTCGACTGGTAACTCACCTCCGTGTTACTGGCAAGTTGGCGAAACGCTG
          CCTGCTTGTTGGATCACTACCGTATAGAACCCCACTCGCCGGCCACTTGCCGGAATTTTC
          TGCGGGAAGGCCGCTCGCGAGGGTGGCCGTGACGAAGTATGGCGAGCCTTTGAACTTCAG
          AGCGAGAGACCCCCTCAAGAATATTGGATGGATTCTGCACGTTGATCCTTTATAAGTTTA

          CTTAGTCGTGCGACTGGAATGACTCACAGATTTATGATTAGTTGGAGGCGCTACCGGTAG
          CTGATTGATGCGACTGGACCCGAACAGAGATCTAGGGCCAGCCTGCGCCGGTACCGGTAA
          TTCCCTAAGTTGTACAGATGCATTCCGACAATCCATACAGGTCCGAATCAACAATAGGCG
          TTCGCCAGGTCACTTAGTGAGGTTAAGTGGTTATGCGGAGATACGTATTAACACTAGCGC
          ACCATGAGATTTTACGACTGTCGATAATGTCCTCCCACCCATACGCGCTAATGCTGGCCG
          GTGCCAGGGTTGTTTACGGGGGCCCGAGAATTCCATGATGGTCTCTTGTGACATTGATTT
          GCTAGCTGGTTACAGAGAGAATACAAGCGATTGCGATAGATACAGCGACGTATTTAAAGG
          GGCGATGAATAAGATTAGAAGCCCTTAACACTTCACAAGTACCAACGGCAAGACTCTAGC

          GCCTTAACCTGCTTGTGACGACCAAATGCTTAGCGAAAGCGGGAGCAATCCAGGACTGTG
          GTATCAACATGCAGCGAGCAAGCAGTTGCTCAGAGGGGGTGAAGCTCGCCAAGCTTAATA
          GGACAAGTAGGCTCGGAACAACCAGACGGTTTTTGGTGTATGGTCTCGTTAAAACCAGTG
          GCATGATTCGGACTAAAGTATTCTATTACTATTCGTAGGAAGGCCGCGTCACGACCGGTG
          GGGCGCACTCGATTTGCAAAAATATTCCTCACGCTTAGTGAGAACTCGCCCATAATGGTA
          GTAAAGCCACCGATAGAAGATGCATGGACCGTGCAAAGCCGGAGCACGTCCAGTTGTGCG
          TTAAACCCCGCATCAAGGTAAAGTGAGATCGTATCGAAGTTGTATCTCTAGTTACTTGTA
          TCGTGGCTCGAGTCGAGCTGGTACAACGGGTTGCGGGCCGCATCCCCGTGGTATTGGGGG

          TTTGATACGTTTTGCTAACGTGTGGTGAGGACTCCGTTTGCGGCACCAAGAATCGATTTC
          TTCTGCAGAGTTAGCCAGCGCGAGACAACGACTTTGTTAACCGCTATAAGCTCCGTAATC
          CCTTGCAACTGGCCCTGCACGACGCTTCGACGATTTCACTCGCAAGAGGCAAGCGGTTTC
          TGTTGTCGGGGCCTGAATCGCGCGTTGGGGGTGTTGCACGTGGAAATAAAGAGCCCACGT
          ATCTAATGCAGATCATATAACGCGACGCGGAGCTAGGTCCTCGAGCGACACCGTGACGTT
          ATCATTCAATGTCACAGCAGCCCGGTGATGGCGTAGTTCTTGGTTACTGGTAGAGTCGAT
          AATTTCCAGTCCAGATCACGATGGGTATGGAGCCATTATTTGAGGGAAGCTATAGTCAAT
          CCGATTCAATGACAATACCAGCTGACATGAGCGCAACACCTTAGGGGAGGCCCAGACCCT

          GTTAGCACTTCAAGAGCCGCAGCGTTTGAAGGCGAGTAAA
          GACGACATTCTTAGAACCGCAGCTCCCGGACGTGAGTTAG
          TTCGCCATTCTTAGTAACGCTGATTCTTGAACTGTGCATT
          GTCGATTGCTCCTGAGCCTTCGCTTAAGAGGGCGGATGGA
          GCCAGCGTGTCGAAAAGCGTGTCGTCTTAAGACACACGAA
          GCGGCGATGCGGAGTGCACCCGGAATTACGGTTGTATTTA
          GATAATACATCTCTAACCTCGGTCCAAGGGCCCTGGAGGG
          ATTGCTATACTAAAGATTCCGGCAACTGGGGCTTATATGT

