 8 1000
t1        GAGGTGCGTTCAGTATACCACTATTCTGCCCGCTGGATGGGCGCGTGTACGGCTGGCCAT
t2        AAAGTACGTTTAGTCTACCACTTATTTACACGGTAGACGGGCACGTGTACGTCTGCCCAT
t3        GCAACGCGTTTAGCCCCCGAAGCCGCTACGCGCTAGTTTGAGAACAACGGGTTAGAACGC
t4        TATGCACTTCGCGTCTAAGTCTCGATTATACATGAGTTGAGCGACTGGAGGAAATGGCAT
t5        TTCCTCTATTCTGTTAGCCGTGCGACTATCTGCCGGATAGACGAATGGTATACCACCTGT
t6        TTCGTGCACGAATCTTGAAAGCCCTTTATCCACCTGGCAGAAAATCGGCGGCCGCCCGGC
t7        TCAATATATCCAGCCTCACTTTTGATATTACTACCTCTGGATCTGTAGTTGCCAGGTAAT
t8        TAAAATCGTGTGTGTCCTCTTTGGGTCACATATTCGGTCGCGTATTGCGGGCTTGCAGAT

          TGCTAGACTGATTTCGAGGATCTACTTTCATGGTCTCTTACGATCCGGGCGGCACGACGA
          TGATAAATCGGTCCGGAGGACACGGTGCGACGGCATCTTACGACTCGGGTGGGATGACGA
          TGCATGATCGGCAGGAAGATGTAAGCCCTTCGGCTTTTTACAGTCCTGATGGCTCGGGCA
          TTCCTGCTTCGTTAGATAGCATTAGCGATGCCCTTCCATAGCACGCACCCGAAAGGAGCC
          GGCGGGGGCAGATCCGCGAGGTTAATAAGATATCGGCTCGCTATATAGTTCTGCCTAAAC
          AAAAGGAGCGCTGAGACCACGTTCAATAAGCGAGCGCTTCGACCCCGCCAAGCCCTCGAT
          ACCTCGATTGGTGGACATGCCTACCCTAGACATTATTCTATTGTGGAATAGTTCTGCGAC
          GGGGAAACATTAATGAGGCTGTTTAACCAGATTAAACTTAAAACAAGTACAAATGCACAA

          CTACCGACGGGTGTAGTAAACTTAGTAAGTACCGAACGTATGCGTAGACGAGCTATTTCA
          TTGCAGACGGGTTTAATAAATTTAGTGAGTACCGAATGTATGTCCAGACGTGCTACTTCA
          GTGCAGACTAGTTTAACAAAGCGAACGTTCCTGTCGAGAACGGCACCTAGTGCCACTACG
          TCAAAGTTACAGTATAGAACCCCGGCATAAATGAGGCACATGTCTGCCTGCGGCTTTATG
          GCTTAATCTGAGTAAGCCTATCCACTGTGTATCAATGGAGCTTTTAACTGAGCCCCAACG
          CAATTGCCTGACCTAGTAAAACGATGGTAAAAATTTCTTATTCCCGCCCAAACTCCGTGC
          ATCTAACAAGGAAACGTCTTCTTCTAGTTCGATTGCTAGAACCGCGGTTAAGGTAAGTAC
          GATCTTTAAGGCCCATTTGTCACGTTTTACTTTTTACCTGACGTTGGCTGAGATGGTTCT

          ACGGAATAGTGTACCACACTGCATCAGCCCACTAAGAATGTCGATCGTGCACATCCATGC
          ACGCAATCGCGCGCCACATTGCATCAGCCTACCAAGATAGCATAGCGTGCGATTCCATTC
          GCAAAACAACGGTCGCTTATGTTTTAGCGCATAGAGTATGCACGTCCTGTATTTCCCCAC
          CAATTTTCGGCTAGTCATAAGTCCCGGCCCACCAACCCCTATCCGAATGTTTTACCGCGT
          CTAAACCCGTAACGCAGTAGCTCCCGACCTCCTGGGTTCCTTGGACGCGTATTGGTCACC
          AAGAACAGCAGGGAATAAATCTTTCGGTCGTGTTCGGTTTAAGTGAGCTTACCTCCAAGG
          GCTCGATAGTGCATCCGTGGGCCCAAGTTCGGCTGGGAAACTAATCGTGACTACCTGAAT
          ATAAAGCAGCGTGTTTAATCACTCCACTACAATGGTTGTCCCACGCGTAAGTCTTTGGGG

          GACCTTGTTAGCTGATTAATTTCACGTCGTAGACCTTCGTAATAGCGTGAGGATTAGGGC
          GACTATGTAAGCTGTTTGGTCTCCAGTCGAAGATCTTCATAATGGCGGGAGGATCAGGTA
          GACTCTGAAGTCTGGTTGGCGTCTACTTTGTCATTTAAGGTCTAGTGAGGGGGAAAGAAA
          AAGTCTCATATGTGATTAACCCCTGCTGACGCAATCGCGTATCACCTCGCGAGTCGGGGG
          AATAATTAAGACCAATATTCCTTCCGTAGCGATATCATGTATGCGAGATGGCGCACCGAG
          GGAGTTTAATGCCGCTTAATCTTTTATTTCGTTTGTACAGGATATCAACACGCCGTGATA
          GGATACAGAGCTATCCCCATCCATCCCCCTAGATCATCGCCTTTACGAGGGAGTACGAAG
          TAGCCGCAATCTATACCAAAACTTACTTAACGACCCAGGAACTTGAGAGGGAATGAGAAA

          TGTCCCTTCGGCTGGCAGAGCACAAGATAAAAAGCGCCATTGGCGAGGTGATGAAACTGT
          CGTTCCTCGGGCTGGCAGAGAATTTGGCACGGAGCGCTGCTAGTCAGATAATGACTCTTT
          TTTTCTACCGCCTAATAGGCGATTAGTACATGCGTATTTTCAGCGACATGATGGAGTCCC
          TATTCTGCCGGCTAGCAGGGTGCTCAATCCGGCGAGCGGCGTAATACGCGTGCACGTTCG
          CCCCTGCTTGCTTCGTGCCATAGAGGCCCCATCGTGCGTCACGCAACATATTCGAGCCTC
          AGCTCTATTAACCGACGCTATCGCGGGCATAGTACAAAGTTCGCGCTCCGTTAGAGGCGG
          AATTCGCCAAGCCGGCAGTTGCTAGCCGAAGAGGCGTAGTTCCGTAATCCATAGAACGTT
          TTCTCAAAATGTCAGTATAAGGTTGACAACACTATGGGCATCAAGATGAAACGCTGCCTC

          TTCACTAGTCAGCCTGTTGAGGACGTGATGTTATATCCGTCAATTATCACGGACTTCTCA
          TCCAAAAGCCACCCTGTTGCGGACATGATACTACTTCCGTCTATTAACGTAGAGACATCG
          CCCACTAGTTGCTCGGTCGCTATTGCACCGTCATATTCGCTGATGTTTGTGGGAATCCAG
          TTTTGCCGGCGGCTGGTCCTCCCCCGACAGTTCTAACATTGGGACTCTTCGCAAACACTA
          CAATGTAGTAAAGTAGTTAATGGTTCACAGCCATACCTGTCGGTCACTCTGGAAAGCGGC
          GTTCGTCATTGCCAACCCGTCGAGGCATCGCGTCGGGTGTGAGTATTTGCGATGACTCTT
          TATAGAGGACGGTTGCAACTAGGGGCGAAGCAAATGCTGAAGGCCACTACGAACACTGAG
          TGATAATGGAGTCGATCCATATGTGTGGCGGCGAGCCTGTGATGTTTCGAGGGTACTATG

          CCTAAATACGCAGGCTAACGGTTACCACCAGAGGGCACCATGTATCGTTCATGAAACCAT
          CCTAACTGAGCCCTCCAAAGGTCGCAACCATAGGCTACGTAATATCATTCATGAGGCTAT
          TACTTAATATTCCACTTACGGTCGAGACCTAGCGGGCTCATACAACACTGAAGGATTTGG
          CTTCCGGGAGATCCCGAACGAACTAATATACACACTTTTGCGCTTTACCCGGGAGACTAC
          TATTTAACTGTCTCTTGTGTACCAGAGCCAAAAGCTTACAAGCGTGGTGCGCCCACCCGT
          TGTACTAGAGCGCCCATTCCAAGAAAACGCCTTTACATTTCGCGTGGTGCGCGTCTATGG
          AAAACCCCAGAGCTATGTTCCTCACGAACGGCCTGTCACTTGCACATCTCGTGCTACTGT
          TGATTGGATTCACAAGAATATTAGTACACCGAATAGTCATTACACCGTGGTTGTCCCTAT

          TCTAAACCATACCTCTCTATTTGGCACTCCTAATTCACCCTCTAATCTTAAGCTTAAAAT
          TCTGGGCTACAGCTTACCATTCGACACTCCTGACTCATATTCTAACCGCAAGCTGAATGA
          TCTAGTTCTAACCCTTCTTCTTAACGTTGATCACTTACATACTAACATCATATTGACAGT
          TGGAGCTTAGATACCCCGAAGCGCCAACCCCGCCTTGTAACATGATTCCAGCTAGCGTGC
          CTTTCCACGGACTCATAATGGTCAAATCCATAATTCATGATGCGATAGTAAATAGTGTCG
          GCCACGCCAAAACTTCCCCAGTAAAACTCTCCGCGTATCCCACAACACCGAACTCGACGG
          CCTGGTCAGAACTCAGCTCATTTTAGCCTTTGTCCAGTGGGACAAAAGCCAAATACCTGG
          GATAGACCCCACATTTTGAAGGAGGCGTTTGTTCAGGTAGCATAGTGGCCTCATGTGTGA

          TCGGCGCTGACAGTCGATGAAGTGATGCCCAATTCTGATTATTGTTGTAGATTGGCTACA
          GAGGCGCTGCCAGTCGACGAAGTAATGTCCAGTTCTAACCATTGTCGTAAAGGGACTACA
          GCAACGTTTCATACTACAGGGGAGACGACCAGTCCCTACCAAGGCTGTAACTCGAGCATT
          ACCGCCTGGTGGGTTTCCAGAACATTAATTATCTAAGGCGCGCGAGGTTCGCCTCGCATG
          CCAGAACCCTGAGCTAATGTACCGAATAACCGCTCTAGCTCCCAGCGCCTACCCCTTATT
          GCGGAGTAATCAGATCAGAAATTGAATATTGGACGCGCTCTCTGTTACGAAACTCCTCGT
          ATCATATAGCGATAATATGGACCCTATCTTCGGTCCAGCATGCACTGACGTCACCTCTAC
          GTCGCAAGCTTAGTGGGCAAGCTATTGACCTAATCAAGTCCGAGTCAGTGCTTGACGCAC

          TGGGAAACGGTGATTCAAAGGGCTATGTTGATATGAAAGGCTGCCTCCAGGCTCAAGGCT
          TACAAAGCGGGCAGCCAAAGGGATGTGTTGTTAGAACAGGCTGCCCCAGAGCTTGAGGCT
          AAGTGAAGGTTCTGTCCAGGAGTTTTGTTACGCGGCGAGGACGTCCGAAACTCCAATGCA
          CGCGTGGCGTCACAATAGGTACTATCTTCGGACGTGCGGGATACCCTAAGGGACAGAATC
          TGTCTACGGGTACGCCATACGCTGACGATGAGCCGACGAACTATTCGGCGGTTCAATGTT
          CCGAGTTAGGCAGAAATAATCCCTGCGGTACAATTCTCGCAAACTTCAAGCCTTGATGCC
          CGAAGGGTATCACGAGCGGGTTGAAAACTGCACGCGCATGTGATCTGAAGGCTCAGAATA
          CATAGGGGTAGGTGACAGGAAATCAGTCAAGAAGTCCGGGATGTTCTTCGACGTTGGACT

          ATTGTCCGCACGGGTACTGAAGCAGCTCGAGGACCAACAGCGAGGTTAGTGAACGCACAC
          AGTGCCTACATGGACACCGAAGCCGCCTGAGCATGAATCGCGGGGTCCGCTAACGTACAA
          AAAGCCCCCATAGTCATTGAAGACGCTCGGAATTGGATTACAGAGTTAGCTTTTTCGTCT
          TCAGTTCGAATGGACTTTATGGTTGTCTGATGATATACTCCGCGGAAGACTGAAGCGCAA
          GCGCCGTGCAAGGACGGTGACGTACTTGGTCAACGGGTTGCAGCGTAAAATGACGTCGTT
          ACTGCTTTGAGAAGCTACGGCCGGGCCCAAGATCGGTCTTGCGCGCGGGGCTTTCTTTTA
          GTAGTTTGCACGGGGCGCGGCAGTGTCCGGACGCAGAGTGCTAGGCGATTCGATATATGG
          GGGGCTTATCTGAGCCTCAGACTTCTTGGGGCATAGACTCTAGCGCATGTAATGGTACTT

          GCGTTCCCTCTAGACCATGGATTATGGATGAACCGTCGAACCTCATTATAATGTGCGGCG
          GAACCCCCTCTAAGCGACGGACCAGGGTTGTACGGTCGAATCTCATCATAGTGCCTAGCG
          GTGCAGATGCCGGCCGTCAGAGGAGGAACAAGCAATTGTCGTCAATGGCATCATCCCCCG
          GCGCCCGCTCGCGATCTCAAAAGAGTGGAGAATGGTAGAAGCCTGCGTAACTCTCTCGTC
          ATCGCCCTGAGCCACAAGTTAAGAATGACACATAGGTGAAGCCTTGGGGTTCACCCTGTG
          CCTCCCTAATAACGAAACTTAGTAGTGGTTGACCGCCATAATTCCGGGAATATTTACGCG
          AATTTCCTATTTGATATTCGGGTCACGATCGGAAAGGACTTCATGAGACATCGTCCGACA
          GTCTCGTTAGGGACAAGCAAGGTGGTGCATCCCAATAATAGACCGAGAGGGTATTCAATG

          AACTGACTTTCTGAAATGCAAGAACATTAGTGCCGATCAGGGTATCAGTTTTCTCCGTGT
          TACCGACTTACTGAGATGTAAGGATATCAGTGCCGATTAGGGTTTCAATTCTCCCCGTGT
          GACCGTAAGCACGAAAAACAAGGAAGCCTGGGTCAACGGAGGAATTGATCTCGTTGGTTT
          CCCTGTTGCCACTCATGGAGTAGGTATAGCGGCAACTGGAAGGACGCGACAGTTTGGTCT
          GAGCGCTATCGGGAACACCAAGTGCAGTGTGGTCGTTCAGGAGATCAGACTACGTGTCGC
          TCCTGCAACCTCGTATCGTCAAGTTCAAATGGGCCCTTGCAATCTGACAGCTCGGGATTT
          TATTTCGGTTGCAGACCCTGTTTATAACCTGTTTGGCCGTGCGTTTAGGGCGCATCCCGA
          TATTGCAACGTTGGTCGACGTGTTCGTATAGTATAATTACTATATTTACGCCTAGAGCGC

          TTATCCCAAAGTATGTTGAAGCTCGGCTGACAAGCCACAGTTAACGCACAACTACCCAGT
          TCAATGCAAAACATGTTCACGCCCGGGTGACATGAAACGGCTAACGCACAACCTGCCAGG
          CTACTACGAAATGCACATAAACTTCGACCGAGTCCCACTTCCGCTACATTATTCAGACGG
          CGTCCCTGCTTTACACGTAACAGAGTCTCCTAAATTACCTGTCCCGTATTAGTGACCGAC
          CAGTCGCCGACACTACATTAGATAGACCATACCATTACCGCACAATCAACTAACGCGAAC
          TCGGCCAGATATTACCATAAGCTAGGCTCCAAGGCGACCCTAAATGCAATGTTTAGCATA
          TTAAAGCTGTCTTCAGAGTTTTTTACTCCCCCAGTTTTTTGTACCGGGACGCCGTGCAAT
          TGTTGGCGAATTACAGAGGAACTAGACCATGTAGACGTACACTCTATTCGTACAGGTACT

          GGGATGCAGGGAAACAGGCCTGACTACTGCGCTGTTCTGCATCAGATGTGCTACGACTCC
          GGTACGCAGGGGAACAGGCCTGATTATCGCGTTGTTTTGCATCAAATATGTCACGATACC
          GGCGATTCCATACCTGGCCTGGACCTCTGGTTTACTTCGTATGCAACGCTTTAAATCATC
          GGGACATTCGTATCCGGACTTCACCAAGGATCCGCTACGTGTATGTAATTACCCGACACG
          AGAGTACCGCCTATCAGATCCCCTCCCAAATCTGCTTCCTTAACTCCATCGCTACCCATT
          TGGAGGCTTACTTGCCACTTTGCACTCTTCACAGATTCGCAACTGCTTTTAACCCACTTT
          AAGACACAATCGATCAGCTCCCCGATTTGTCTCACCTGGCACCCAGTATAGTATGCACGG
          GCGGCTTTGTTGGGTTGACTCCAACCGGAATCCTTGTCATGCTGCACGATAGCCACGAAA

          GCGCAGTCCACGAAGCTCGCGATCTGCGGCATTTATCTAC
          GTGCAGACCAAGAAATTAGTGACCTGTGGCAGAGACATAC
          GTTCAAAGCGTGCCCGTCATTACCAATAACATTCCTATAC
          GTTTTGTTCCTCTCCTTTACTGGTCCGGGCATCACTGCAC
          GGCTATATCAAATCTTCGGCGATCCAAGGAATTCCTATCA
          GTTGCGGTAATGCCTGTCGTCGCTTGGGTCAATACTGTAT
          GTCGACCCTTTACAGACCATCACGTTAGTCAACATTGACC
          ATAGAGCGCACTCGAGTAGCGGGGGAATTTGCCGCAACAC

