 8 1000
t1        TGTTTGGGAACAGGTACTCAGATTGCATCATAGCGCCCAGACGCGTGATCTACTGCATCG
t2        TCTCTGGCCATGGGTACGCGGAGTGCCGAGTGGCACCCAGGCGCGTTACCTATAACGCTC
t3        CTTCAGCACCCTAGCATTCCGTGTATAGTGTGAACAACACGCAGGTTAGTAAGCGGATCC
t4        CTTCTGTCTGTGGGACCCAATAGCGCCGTGTATACTTCGCACGCGTAACTTATCTGACCG
t5        TTACGGTGCTCATCTGCTTGGCGTTGCGAACGCGCGCACCATGTTTCATCGAACAACGGC
t6        TTACTGTGCACATCTGTTTGGCATAGCGAACGTGTGCACCATGTATCATCAAATAACGGC
t7        CTGCCAGCCAGGAATACCCGGCGCTGTTCTCATCAGTGATGCTTAACATCGGGCACGTGC
t8        TTAACGCGTATGCATAGCCAGTACCGAGAATACTTGCGACGCGAAATGCCGGATAACTGC

          AGAAGTAGCATAGCGACAGTCGATTCCGTTGGTTATCGCCGTATGGCACGCGCTGGTAGC
          CCGGGTGGTTTTACGGCCCTCAAATCCTTCGGTCAACACAGCTTAGAGCGGGGCGACAGC
          GGTCGCAACCTTCCGGCGATCAACTAACTCTGTCGTTAACGTTTGGGATGAGACGGTCAA
          CTGTATAGCCTGCTGGGTCTCGTTCATACTTCTTCTCAACGCCGAGGCCGAAGCGGTCCA
          ACAAGCGGCCCGACGACTTTCCTCAGTGACTGCCGCCGGACCGCGTAGTAGGAAATCAGT
          ACACGCGGCCCGACGATTTTCCTCTGTGAGTGCAGCCGGACCGCGACTTAGGAAATCAGT
          GAAGGTAGTCCGGTGCTGTGCCTTCGTAGCTGTAGTCGAATCACGACGCGGGCCATTGGT
          ACGAGTAGCTGGGGCGCTTTCCCACGAGCCGGCAGCTCAACTATGACGAACCTGATAAGC

          TGGATTTCCTTACACCCCCTTGAGGGAGGTAAGAGATGTGGGTAGACGTGAGAGCCATTG
          CGGGTTTCTCCATAGACCTATGAGGATTGGAAGAAGAGTGAGTCGTGCCGACAGCTGTCG
          CGGGTCTATTCCTTATGGCCTTAGGGAGGCTGGAGGACCGGCTGGGTAGGGCTAGCGTCC
          CGAGTTCGCCCACAATGTTACCAAGGCGCTGATTAGGTTAGGTAACTCAGACGGGTCAAA
          TCAGTTACCGTTCTTTGTCGGTGGGGCGGACACTAGCGTAGATGACGTAGCCCTGAATCA
          TCAGTTAACGTTCTACGTCGGTGGGGCGGACACTAGCGTAGACGGCGTAACCCTGAATCA
          GTGGTTTCATCCCGTTGTACTCAGAGTGCGCAACAGAATATGTCACGGGGAAGATAGCTA
          CGAGGTACATCAACTTTCCAGCAGAATGGTCGTTAGAACGAATAATACAGAACGGGGCCA

          TTGGTGCACAAATCATTCGACAGAAATTGGGACCTGTATGAGCTTGCAAAGACGTCGTCC
          ACAGTGCGCGAACTGCTCCACTGGCCGCCGGATACGCATGACTTTATTTAGATGGCGTCC
          ATGACCCTGCTGCTTGTTGATACGCCGGATGACCTGTACAAGACACCGCCATGGACGTAC
          ACGGCGCAATAGTCTGCCGATAGCGCGCAGACTTCTTACCAGGCGTCGCAATGGAAGATC
          AGATCGATAAGGTGCCATCACTGCTTGAAATTTCCGAGCCTAGTGTAACGAACGAGGTGT
          AGATCGTTAAGGTGTCATCACGACTCGAAATTTCCAAGCCTAGTGTAGCGAACGAGGTGT
          GGGCGGCAAACGATCCATTATGGATCGGAGTATTTGTGTCTGGTACCGAGTACGAGGCAT
          AGGCTGGGAGGGCCTTATCGTGGCGAAAAGTATGTATAAGACGCGTTACGAGAGAAACGC

          ACGGTCGGGCATACATAAGATTCAAGTCGAGACTGGTAGATCCAGGCGAATCATCGAAAC
          GCGGCCTGGCACACAGCGGATTTTAGACGAGATTGGACGGGCAAAGCATTGCGCCAAAGT
          ACGGGTGGTCACACCGTCGGCACTGTTAGCGAAGGGCCCGCCGCAGCAAGTTGCTTTAGT
          CATAGCAGGTGTGTTTTCGGCGCTCGTATATAAAGGACGGGTATCTCTATTTCCCTTCAT
          CAAGCTGAGTAGCCCTGTGATGCTGGCAACGACACGCCGCGAAGAGAACCTTATCCGGCC
          CTAGCTGAGTACCCCTCTGATGCGGGCAGCGGCACACCGCGAAGAGAACCTTATCCGGCC
          GTAGGTTGGTAAACATGACGCGTTGGGTTTGGAAGGCTCAGTCAAAACACTAGTCCATCT
          GCAGATGTGCCTTTATTAAATATTGATAACGCGAGGCCGGGCTAGTAAGTTGGAGAGACT

          ATGTCCGGAGCGGTCCACTAATTCGCTTATGTAGGAGTAGTTGGTGTAAGAACATTCGGG
          AAATCCCGTGGACCTGATTAATGCACACGAGCAAGGGTACTTTCCGTCCGCACACTCGGG
          GAACATCATGATGCGTGTCACTACCGTCCTCGTGAGACCATATCATCATACATGGCTGTC
          ACATATCTAAAGGGGTGTCATTACCGCACCTCGCAGGTATTTTCCGCATGTACCACTGGG
          TTGTGCACGAAAATCATTTATTTCATCGTTCGACTGCACATACTCGCACCTGTTGCGCGG
          TTGCGCACGAAAATCATTTATTTCATCGTTCGACTGAACACACTCGCGCCTGTTGTTCGG
          TCATATGGAGGAGTTGAGCGTCCTTACGATTGATCAGCGAGACCCGTGCCGGGGAACCGC
          TTGGGCAATTAGGTCGGCTGATATTAGTTTCAAATTACGGCACCAGAACAGGAGTTCTGA

          GAAGAACAGGTGGGGTAAACCAGACACCTCCCGGATGCTCTATATGAATCACGGAACGCT
          GAAGGTGAGATGGGGTAGCTGAAAAATCTCCCTGAAATCCTAAATGAAATGCAGAGCGGG
          GGGGGGCTAATAGTATAAGCTGGTATCCCCCTGGTTTAGCCATGCGAATTGTTGGGCGAG
          GAGGGGAGTGTGGAGTGAACCCAGTCTCCACCAGGCAACCTATGTGGACCGATAAGACAA
          GTCGGGCTTGAGGCTAGGATTGGACTTTACCTAGAGAAGCTAATTAGATGTCATAAATAG
          GTCGGGCCTGAGGCTAGTCTTAGACTTTACTTAGAGAAACTAATTAGATTTCACAGATAA
          GAATGAACGGTATCACGCGTGAAGTTCTGCCCAGTAAAGTTAGCCAAACCGGACACTACT
          GCAGAAACGACCTAATGAGATAGCTTTTACTTGAAGCTCTGTACCAGAGTCAATCGTTAA

          GATCGCTTCTTTCCACTCGAGATCGACTCGGCCCCTCGGCAGGTGCTAGCATCAACATAT
          GGACACTCCTGTCTAATTGTGCATGATTCGTTATTTCAATACGCGGCTGAACAACAGTAT
          GAGGGTCTCCCCTTGAAAACCGTTGCTGTGGAATTTCGCTAGGCAGCGATTATAATACAT
          GGACGGATCGGGCTCCAAGCCAAAACTATTGAAGTGCGATAGACGTCGCGATCCGTCCTG
          AGCCCATTACGTTGGTGGTTTTAGACACTTCGATAGAATTCAGAGCCCTGACTGACATAA
          AGCCCGTCCCGATGGTGGTTCTAGATTCTACGATAGAGTTCAGTGCTCTGACTGACCTAA
          AGTCCATTCTAATTGAAAATGCACACTCACCGGTAGGGCTCAGGACCATGAACATACCCC
          AGCATCACTCGTCCATGGATATACATTTAGTCATAGAATCTAAGCTGCTACACACCAAAG

          CGAGCACATGGTTGCGAAATCTCGACCAATTACGTGCCCTGTGTGCAGCGTGATATCCTA
          CCCGCACACGGTTGTCAACTCTGAACGAATTCTACGTCCTGTAGGCAGAGCTACACACTA
          TTTCCATAAATACATAGTAGTACATACTTCCGCGTGCATCCTGCGGTGTTTTGCACGACA
          CATTTTCGAAGTCATAGTAGTTCTCGAAACCACGTGCTCCGTGTGAAATTGTACACCTTA
          TGCTACAGATGTCAGCGTAGCTGCTACCAACACGAACTCAGACAGGCGCCCTTCAAGTCC
          TGTTACAGATGTCAGCGTTGTTGCTACCAACATGTGCTTAGACAGACGTCCTTCAAGTCC
          TTTCTCGCCTGACAGAATCGCCGGTCCGCCCGTCCGCCTCATGGGACGACAGTCAAGTGT
          TAGGTTTCATGTCAAGCTTGCCGGCTGGACTATGCGCTCTAGCGGCCATACCGCGAACAC

          AGCAAGCTCACCATGTCATCACGCAATGAAAAGCTTAACAGCGTGAACCTTCGTGCAGTG
          AGTGTGCCCGTCCTGTCACCCTGCAATGATAAAACTGCCAATGTGAACCCTCCTGCGGTG
          CGCGAGACTAGTACACGGATAGCCACTTGAGACGCTAGATGGGTCAGACTATTTAGGGTT
          GCTGCGACTACCGCATCAATACGTATTGCAAAATATTGTGATGGCGGTTTCACCGGAGTT
          CATACCTGTGACGCGCCGATACTCCCACGGGCCAAGAGCTTCGTAGCGCTCAACTCAGAG
          CAAACCTGCAACGCGCCGATACTCCCATGAGCCAAGAGCTTCGTTGCGCTCAACTCAGAG
          GAGGTCCGTCGTGTACTCATGCCCCAATTAGTGCTGGACTACCTTATACTGAACTCGGTT
          CAAATCAGTAGCAGCTCCAAATACTGATCGACGTGGGGTGCCTTGGCACTCTACTAGTGG

          ACGTAGCAACTCCGCGTCCTCTCCCGCGACCCCGAGGGCAGTGTAGCTGTAGTTCGAACA
          GTAGGGCGGCTTCGTAGCCTACCCAACCACTCCGAGGATAGTGGAGCCTTTGCTCGAAAG
          GTGGTGTAAATTAACAACCCAATCGGCTATCCTTGGGCTAACAATACTTCAATATGAACA
          GCGCCGTAGTATAGCTGGCTACCTGGCCCTTTTGGAGATGGCGACATCCCGTGGTGTGTA
          GTGGGATTAGTCGGTGGGCCGTTCAGAAAGAGTACGCACACTAGAGGTCAACCCTGAGTT
          GTGGAATTAGCTGGTGGGTCGTTCAGAAAGAGGATGTACACTAGAGGCCAATCATGAGTA
          GCATAATTACCCGGCAGATCGTCAAGGCCCATTGTGAACGCTGGAGCGTTGCTATCACTA
          TAACGAATATCCGGCAACGTGTTAGGCGACACCGTGAACATTCGGATTCTATTATACATA

          AGTTTTGGGTCTTCGACCCAGACTAAAGAGTGGTTAAGGGTAAGTTACAGAGATGCCATT
          AGTATTGGGTCTTTGACCCAGCCCAGAGGCTGATCAGGAGCAAGCTGCGGAGACAATATC
          CACCCCGGGCCACTTTCCTAGTCATCCGTCTATTGGGAGAGTGACTACGAGGTGGGACCA
          GACTCTGGGGGACTCTCCTGGCTGAACGCATGACCCAGAGATGATTTTGGAGTTAGCATT
          AGTCCTGGGGTTACCTTTTAGCTATTAAATCCCTCGGAGATGACACCATGTGTAGAGACC
          AATCCTGGGGTTGCCTTTTGGCTGCTAGATCCCCTGGGCATGACACCATGCGTAGAGACC
          TATTCTGAAACAGATCCCAGGATCGACTTTCTCTCGGGAAAAGGAGACCGTGCAGCTACC
          CCCCACGATGTAGCTCCCTGGGTAGCCTCACGCAAAAGGAAAAGATTTTGTACGATTACC

          AACGTGCACAGGCTAGCGGAAGGGCCGAAACCAGGATTTCGGCACAAGCATCCCTATGGT
          TACACGTATAGACTTGTAGAAGGGCCAGGGCTAGGATCTCGACCCGAGCATTTTTCAGGT
          GACCCAGTCTAGGGAGCGGGTGAACCACAGTCCAGATCTAGAGATCAGATCTCTTCTGGT
          TATGCAGAATTTTCAGCGAATGGTCCAAGATCCCGCCTTGGGTATGGCATACCCTGCGGT
          GGCGCCCCGTCAAAAGTCTATTGGACCCAATTGAACTCGGCGCACCGTTGTTGTCGAGTC
          GACGCCCCGTCAAGAGTCTATTGGACCCAACTGAACTCAGCGCACCGGTGTTGTTGAATC
          GATAAGTTCAAAGAACTCGCCAACCCTCGATCATAACCGGCATAACGATCCTGGAGTTAA
          CGCGGGCCTTCGAAGCGCATCAGTCCAATTTTAAATTCAGATCACGGATTGCCCTGTGGC

          ATTTATCTAGGGGGGAATACTGTTCATGATCTTACTAATATCTGGTTTATACAACCCACG
          ATCTAATTAGAGAGATGTCTTGCTTTCGATCCTTCCTGCCGTCGGTCGGTACTACCCAAG
          AATCGATAGAATCTCCACGCCTTCTTTGGTAATGCCGGTCAGCGCCGGATCCCCACTCAG
          ATTACAAGGGCCGTCAAGACCCCCTGTGACGTCGCCAGGTGAGCTTGTTCTCGGCCCGAG
          TGGCACCTGTGTGGGCTGTGTGCTGCCAACGACGACCATAATTGAGCTATCCCAACCGGG
          TGGCACCTGTGAGGGCCGTGCGCTGCTAACGACGACTATAATTGAGTTATCCCAACCGGG
          TGACCATAGGACGTTCCGAGTTCGGTTATCGATAATATCGATAGATGTACTACATCTTGA
          TAGTTACCGGATGGGCTGCGCCCCATTAAAGGTGTCGCCAGCGAACATATCCTACATGAG

          TGTCTGCGAAGTACAAAGGGGGGATGCGCACACTTGCCAATCCAAATCGGACAGGTGGTA
          TGGTCGCGAAGTATCAAGGGAGGCTACGAACGTTTGCCACTCTAACCTTGATAAACAGCA
          TACGCGATGGGTGCTAAGGAAGAATGTGGAGGAGCAACTGGGATGATACACTGCAGGGAG
          CGCGGTGCAAGTAATTGTGCAGAATGCGATTGCTCGTCAATTAAGTTACGCCACGCGTAT
          CATGAGGCAACCTTCTGGCCGCGGTTCTCACATTTGACAAACCTGGCCAGTAGCGAATCG
          TATGAGACAACCTTCTGGTCGCGGTTCTCACAGTTGACGAACCAGGCCAGTAGCGAATTG
          CGTTAGGTTAGACTCATGCGACGAATGCAACAATTGATAAGGCTGGCTCGTTTCACTCAA
          GACTAGGCTGATATCGGACAGAGGCTCCATTACCAAGTAAAAGTAGCCTGCTAAGCGCGA

          AACTGTGATTCTATAAGGCCGGTAGTATGCTCAAACACTCAAGAAAAGTTCCCAGAGCTA
          AACTATAGTGCTTCAAGACCGGTGGTGTGCTCTGGCGCCCAAGAGAAATAGCTCGAGACA
          AACTATAAGGCTATCCAGCCGGCTAGGCGCGACGGTGTCTATCAGAGGTTGGACGAGCTT
          AACCGCAACCCCGTTCAATGGGTGACGCGTAAGGACCCTTACCGAACGTTAGATTAGTCT
          TTTCTTTGAAAGAGAGAAATAATGGCATGAGACTTGGCCCGCCGATTGTACTGCCGGTCT
          TTTTTTTGAAGGAGAGAAATAGTGGCATGAGGCTAGGCCCGCCGATTGTACTGCATGTCT
          GATTACCTTGGGCCCCGAACAATTATTCGTGATTAGGTATGTTCGGGGTACCCCGGGTGT
          GTCCGCCGACGATAAAGAATCAAAGCGTCAGGATGAAACTGCTAGCCTTTGTATGGACTT

          TGGGCTCAACTGCGGTCCCCTCCGATCAAATAATTGGTGC
          GGTGCCCGAGTGTAGTCACCTCCCAGTAAATACTTAATGC
          CGAGCGTAATGTGTGCTGTTTCTCGCCTAGTACCCGCTAC
          TAAGTTAAGGGCTGATTCACGCTCGGCCCGTAGCCACCGC
          TAGCTGACGTAACGATTGTTCTACCTGAAATAACTGCTGC
          TTGCTGATATAACGATTGCTCTACCTGAAATGACTGCTGC
          TCGTACAAAATGACATTGTTATCCACAGAATAACCGCTGC
          ACAAATAACCTAAGATCGCTTCCCCCAAGCTAATTATTAC

