 8 1000
t1        GCACATGGGATCGTGGGGGAGAAAAGGCGGCGATAGTCACTCCTTCATCTCGGCGAGGAA
t2        ATAGATAAACCCGTGGAGGAGAACAGGCGGAAATAGTGACCCCCCCTCCTGGTCGTGTGG
t3        CTAAATGGGATCGTGGGGAGGGACAGGCCAAAATTGTGACCTAGTCCCCTCGTCGTGGAG
t4        CTTGGAGAGACCACGCGAGGTAATCGGCGAAATTCAGGGCTCATCCCCATCGCAGTGGGG
t5        TTAGATGAAACCCCTGAGGGGTTACGGCCAAGATTCAAGGTGGCCGAATTTATAACTCGA
t6        GCCGAGGAGCGTATGATGGGGTCTCGGAGAAGATTCTAGCCTGTATCGGTTATCCTGTGA
t7        GAAAACGGAGCGCACGGAGCGCATTAGCGACGATGCGGACTATGTTCTGGCAATGAACTA
t8        TTAGATCGGTCCGCATACGCACTTTACAAAGTATCCATATAAGGGCTCTTCGTAGAGCGG

          AATTCCCCTGCATAGAGATTGTGGGTTATCTCAAGGTCTCTATGCTTTCGCGCTAAACCG
          GACTTCCTCGCCCATTAACTGTGGCCCATCTGAGAGACTCTACGCCTTGCCGCAGAAGTG
          AAATCCGCCGCACCCAAATTGTGGCTCACCCAGTGCCCTCCATGCCTACCCGCTGGATTG
          GACCCCACTGCGCCGGAGTTGCAAATTGCCTTGGGCATCCTAAGTGGTTTCGCCGAATTG
          CCCTGCCCTGCACCCGCGACGTAGACCCAAACGGGAGCCACAAGTGGTCCGGCTAGATGG
          GGTTCCTCTGTACCTAAACTATGAACTCACAAGGGACTTCTACGCGACCTATTTGGTCAT
          CAGACTAGAGAATATGGCTAATCCGACCCGACAGAACTGAATCATAAGCCGGCTGATTAA
          GTACTCCCTGCCTCCCGCTTTAGGCCTGGCGTCGGACCAAAGATCAAAGCTGTCAGTTTG

          GTCGTGGGGCGGACGCCATCCACCGCGCGTTTGCTGTCAATTACGATAAATTGGGGAAGT
          GTTGTGGGGTGGATGCTACACCTTGTGTGAGTGGTGTCAACTGAAACACATTCGGGTAAT
          GTCGTGGGGCGAATGCCATCTGTTCTGAGCATGTTGTCAACAGACGTACACTGGGGCAAT
          ATTGCGGGGTCTGTGCCGTTCGCAGCGTGTACACAGAGTTTCTAGCCGTACGCCGGCCGC
          GGCACGAGGCTCTTGGGATCTATTCAAAAAATGTTTGCACTGTAAACGGCCCAGGTGCAC
          TCCTGAAGAAGTATGGTGTTTTGTAGGAAGATATTCATGTGAACAGCATTTGAACGGTTT
          GCTGTGTGAGAGACTGGTCCTTTTAACCGTATCACAACTCGATAAGTTCCGCGGAAATCA
          ACAACACAGCCTGTGATCGCTCTCGTGCAACCACCGTCCAATGGAACTGCGTGATCCCGT

          TGAAACGTATGCGATGCTGTAATGCGAACACCCTTCAGTCTCGTATCACACACATGGCAC
          TAACACATACGGGAAGCTGTAGGAAGACCAGCCTCTAGCAATGTATAGCTTACTCCCCAC
          TAAACCGTAAGAGAAACCGTCGAGCGACATTTCTTCGACTATTTACAAACCACACGGCGT
          TATCATAAGCGGATATCGCTAATGCGGATATTTTTGAGATAAGTATAATTTGTAAGGCGC
          AAAAGCAAATTCGAGCCAGCACCGAGATTGCACGTCATTTTAGCACATTAAGCCCGGATC
          GGGACCGAATGAGAGGGACCGTCGTGCCCATCTCGCAAGTGTGTATAACATTTTTAACAA
          TTGTACCGAGGAATCAGAACGACAAAACAATTCAACAGGCCCGCGAGCCATCCATGGGGT
          ACCTTGTCACACGAGGGTGTGCTTGAGCTAGACGATACTTCTGTGAGCCAAAGTGCGAAC

          ACCCCGTCCAACCAATGCCGCTTCCCATAGGGTCCAATGGATCCAAGCTTGCCTGGCTCA
          CCCTCGCACAAATAGCGCTGCTCCTCACCAGGTACAATGAAAGCCAGCTTGTCCGCGTGA
          CTTCCGCCCTACCACCGATGCCTCTCATAGGGTCCAATGAAACTAAGCTTCTCTAGATCA
          CAGCCGCCCCACTCCCGAAACTCATCGTAGAATTCAATTCTGCTTAACCAGTCTGGGCCA
          TTCACTCCATGAAACCGTCGCCTCAGATACGTTCGGCCTGATCACAATGCGCTTGAGCAC
          TTCTCTCTCTCGCACCGATGCTTACTACGGAGCCCAATTTGTGTTAGCCCGAACGGCTAC
          GCACCGCACTTACATAGAGCGCCTGCCCGGGACATCTCGGTAACTAGTTCGTTAGGGAAG
          TTCATGTTCATAAGCTACTGGTCTACTTACGCACCCACAACTCTCGTCGTCCGCGGGGGC

          TATTAAGTCCGACACCACAGGGCGTACGTGAACAACTATCTGGTCCAGTGAGATACATGT
          CATTAAATATGTCACTACAAGGTGACTGCGTATTATTACTACGTCTAGTGTAACACGTGT
          CTCACAGTACGACACTACATGGCGCCTTCGTATCAATGTCCGGTTTCGTGCAATATATGT
          CAAACAGTACGCCGTTATGGGGCCCCCGAGAATCATCGACCGATTCTGGGTGAGACATGA
          ATCCTTGTGGATTGTCGCGGAGCCAACGCACGCTCTTGCTCCCCATAGTGCCAGTCGGGC
          AGCACATTGAACTCTCGCGCCGCAGTCACGCACCCAGTGTCCGTCCGCAGAAGCCCGGGT
          TCTTCAATGTCTTCCACCGGAATCGTCCCGTTTTTTAAATATTGACGACGTTAAATATAC
          CACTACGTGCATGACCTCTTGGCTATCTCCTGTGCCGATCCTGAACGCAGTTCTTCGAGG

          CGACCGCTTACGTGAGGAGGAACGTATCTTAAGTCACTGTGCTCCAACAGTGCGGTTTAG
          TCCCTGCCTATGTTGGAAGGAACATATCTTATGTCACTGCACATTAGCTGCGCGAGTTGG
          TACCCGCTTAAGTAGAAAGAAACATTTCAGGGGTCACTGCACTTCCACAGAGTAAGTCGG
          ACCCATCTGATGAAGAGAGAAAGGTATCCCGAGGCTTTATATTTTCACGGTGCAAAATAT
          CGCTGCACTACATTAGAGCTCCCCGACGTTTGCTCAACCTGTCCCAACGACCTAAGAATG
          CGTTGAAATGGTTAACGTCGACTGGCTACTCTTTAACCGTGTCCTTCCAGTGTCGGCTAG
          GGAAACGGTGGCAGCGGTGTGTCAAAAACGATCTGGTCTCATCCGTGCAGCGCTGGGTTG
          CGCGAGCTCGCATTACGGAATACCGATATGTACCCACGATGCTCTTATGGCCACCGATCC

          TGTCTATCCAGTGAAAAGCGGTCGCGAAGTCCCTGTTTGGCCCACTTTGGCGGAATAGAG
          GGTTTATCCAGCGACCAGTGGCTCCATAGTCCTTGCTTGGCCCACCCAGGTGAAGTTTAG
          GGTTTGTCCAGTAAACAGCGTCCCCCCAGCTCTCGCTTGGCTCACCCGGTTGGAGTTCAG
          GGCCCGCGTCACACAAGGGTGTCCCGTTGTCATCACATGGCTCAATCACGAGGATTTAAG
          ATTAAGCTGAATGAAAGGGGCGCTTTTCCGGCAGCCTAAAGTCGGCCCTGTGAAATTAGG
          GGGTACCTAAGCAATGGAAAGTCCTATGGCTGTAACTCAAATTACTTGCCGCGAACTGGG
          ATTCCGTTTAAAGAATAAGTATGGGACTAGCCTCGTTCGTGTTGCTAATGTAGGCTTTGG
          GGTCTTCTGTGTAAAGAGCGGCCCTGCGAAACTTGATTTGACCGTCATCAGGTCGTAGCC

          ATTAAGGTGAATCGGTGCTATAGTAGTCTGAAATGGGATAAACGTCTGGCATTTACTTCT
          GTTCAGGAAGATCGCAGTAGTGGTGGACCGAAACGGGTTAACCGTTGGGTATCCTCTTCT
          GTCCCAGAAATTGAGCGCAGTGTTGAACCAAGCTGGGATAATCGTCCGGTATCTTTTTCC
          AATCAGCAGAATCAGCGTAGTGGTGGATTGGTACGGAATATCTGTCAGTAAGCGACTGTT
          ACGTGGTGGCCTGAATCCAGTGGGGTCTAGACCTTGATTTAGCGCTCGTAAATGCCCACA
          ATTAAAAGACCAGGAAGAAGCGGGAACACGGTACTGAGTTGTGGTCTGTAACTGACCCTT
          TTGAACTGTATTGAGAGCCCCAGTCTGGACAACTTGACACAACGGTGACCATGATTTCTT
          AGAACAGGTCTAGGGCCCACCGGATCACAACTTCTGCCAACATGCTATTGTTTGATGTAC

          TTCTGTTTGGTGCGCCCATCCGTCATAGTTCTACGGCCACAGCGTTCGGGCTATAAGCAC
          ACTTGTCCGGTGAAGCCATCTGTCTGAGTCTTATAGTCATGATCTTCGGGCCAAGATCTT
          TCCTGCTCGGTATGAACATGTGTCATAGTCCTATGACCACAGTGATCGGGCCTCAGGTAC
          CCATGCTTAACACGGTAATCCGTGGCTGTCCCTCGGTACTGGCCATCGAGTCCCCCGGGC
          CTCTGTTCAAAATATGTCCCCACCCCTGTGATACAGTGTCAACGCAATGAACATTGGCCC
          TCCAGTTTGAGCTGGGTATCCATCCATACTTTGTAATGGCCATTTCCCGGTTTATAATCA
          TTCAGGTACCGTGTCAACTTCCGATCTGATGCACACGGATACAGCTGGGGCAGCAACCAT
          TACTATCCGGCAGGTGTTGATATGCCCAGACAATCGAAACCGGGCAGCAACGCCGGAAGT

          CCTTCGGACAGGGCGCTTCATAACGCAGCCATGTGCTGGTTACTCAGGCTATACGACCAC
          TGTACGGACAGGTTATTCTATAATGTAGCTGTGCAGTGGGGGTTCAGGCTCTTAGACCAG
          TGCAAAGGCTGGTTACGCTATAACGGAGCCATATAGCGGGGTGTTAGGTCACTCTGCCAC
          CATGCGCATCAAATAGGCGCTAATGCGCTCATGGCTGAAGCGAAGCTCTGTGCCGCCCAT
          CGGATCGGAGCCATTGCCTCCAACGCAGTTACGAGCTTACTAAACAATCCAAACGGACAT
          CACACAAAACGAATGTCCTGCGGCACAGTTAAGCATTAAGTAGTCAGCTTATCGGCATAT
          TATGCCGAGGCCGTAGAATTTTCCCAAACTAGTTATTGGTTTGTTGATTGGCATGCCTGC
          TCTGTAGACAGATCGCTTCATTTATTTGAAGGGTCTCCTGTGTCCCGTTCGTTTACGAAG

          TTCGGGGTTACGATCTTAGGAACATAAACGGAGCGGCATCCAATGATCCGTGGGCTTATC
          TCAGGGGTTATAATCCTTGGAAAACCACACAGGTTTTACTCAGTAACCCACGGACTTACC
          TCTCGAGCTATAATGTTAGGACAATAAACCGAGTTTTAATCAGTGAGCTGTAAATTTCAC
          TCTGGGGTAATGAGCACGGGAAGCATGAGTGAGCTACCCCTCAACAACCGCGTATTAAAC
          CTCTCGTTAATTCCTCTACGGGAGTTGAATTCGCTTTAGCAAAGCGGCGGCGAATAGACG
          TCTGCGGCGTTGAAGGCACACGCCTTGATGAAATTGTGTACCGAAAATTGCACATTTCCA
          CATGAGAACCTCGCTTCACAGGTAGTGACTAGTCAGTACCTATGCTTGGGATAACGCACG
          CACGTGCTGATCGCGCCAGAACCTTGGTCCTAGCTGTCTTATGTGTGAGAAGCACCAATC

          GTTGGGCAGCTTACTGATACTGATCTTACCAACAAGCAATCTTGTCAACCACACGGCCTC
          GCTGGGTAACACGCAAGTCCCGATTCTACGCTTACGGTATCTCCCTAACCACATGGTGTA
          CTTGAACACCACATTGGTGCCAGTTATAGTACTACGGTACTTGATCGACCACGATACGGA
          CTCGGAGAACCCCCCAGGTCTAACTTGACAATCGCTGCGTCTCATTGGCCCAATGGCGCA
          ATAAAAAAACTCTTCGCTTCCATTTTTTGGCTGGAAACACCTAATCAACTAAATGACCCG
          ATTGTAAAGTATTACAGCTCGGCGTCGTTTGCTTTCAGCCTTTTCTAACGGAGTTGCCGT
          ATCCAGTTGGCTAATTCTTTGGATTTAATCGCTAAGAGGTCCTACGGGCGTAGCGGGACG
          TGTACCGTGTACGGTAACTCCGCCTTCTCAACGACGGCCTCTCAACGACTTAGTGGTGAT

          CAATCGGGTATCCGGGGAAGGTTAGGAGTGCAAGGGTTGACTTCATACAGGGACCTGTCC
          CGTTTGAGGGGCAGGGAGTGGTTAGGTACCCATGGGTTGATCGCATGGAGGAACTCGTCT
          CAACTAAGGGGCCGGGAAAAGCTAGGAGTTCATGGGCTGACAGCATGGAGAGACTTGTTC
          CGCACGGGGGGCCAGGAGAGACGGGGATTTAACAGCTTGGCTGCGTAGCTTCAAAATCCC
          TGTTCCGGGAGAAAGCGGCGAAAAGTCGTGTATAGCTCGTATGACGTGAGGCAGATGGCC
          TAATCGTGGTGGCAGAAAACACATAACATGCGACATCTGGTTGCTTGTACTTGGTAGATC
          TATTCTGGGTAGCTAAAAAACGCGTTAAGGTCAAGCACTTAACCTGTCAAACGCCTGTCG
          GATCCTGGGCACCGTCTGAGTTCGTATACTAGATTCCCAGGTAACTAGTAATACGAAGTC

          GAGGGATTAAACCGCACTGCACTACAGGGCGTACAAGAGGAAGTTGACCCCATAGAGGCC
          AGTTTTCCGGATTATATTTCACTATCGGGTGTACAAATGGAAGTTGACCTCTTCGGGGCT
          AGTGGTTTGGACAATACTACACTATCGGGCGCACACATAGAAGATGACACGCTCGAGGTT
          TGGAATTAGGACGGCGCTGTAAACTAGAACGTATCGGTCGGCGTCGAGACCCTTGACATA
          CGGCCCCCGCGCCCAACGCTGGGCCGCCACGTCCAGACGGCTGCCGAGTATCACGGAATT
          TAGAATCAGAACTAGGTCTTTGCCCAGTGCGGTCAAGGAGCTGCGTTCTTACAAACAGTC
          TGGTGTCAGTACTGGGGCGCGGTTAATTGGGTGTTGACACAAGTTTAAACCTTCGCAACT
          CGGTCTTACGGCTGTATTGTAACCCATATAGGCCCGGTGTTCAACGATGTGTACTTAAGC

          CCAATCCAGTAGATTGTGTTTCATGCACCACGCGCACGACTCCACAAAAAACGTCAGGAC
          CCAACCCACATAGTCCCGCTTCTGCCAGTTCATCCATATGCCCGCGGTAAGCGCCGGGAG
          TTAACTCAGACAATTCTGATTCCGGTGTCGCATCGATACAATCACAGAAATCGGCGCTAC
          CCAACCCACGAAACTTTGTTCATAGCGGCAGATTCTTATGATCTTGGGCATAATAAGTAG
          CGGAAGTCAACAATTTTATCTATCGACCCACAATTCTGCGTCCTGGTAAATCGCAAGAAA
          CCAAACCAGATAATATTCCTGACGGTTTAACACATAACTTATATCAAATGTACTCATAGC
          CCACTGTAAGGAATGTCGTTGGAATCAGTACCTTTAGCTGCTCCCTAAACAAGTAGAATT
          CTGGCATCAAAAGCACTACGGAGCGTCTCGCATGTTCCTACACAGACCTGCTACGGTGGT

          GTCTCCCGTATGTTGGAGTCGCCTTTTCCGTAGGTGTTTC
          GTTCTCGGCTAATTGGAGTGGCCTCCTCCGTGGATGTCTG
          GTTTTCCGCGTATTGGAGTTGTTTTCTCGGTAGGTGCCTA
          GTTTCATGCGTCTCGAAGACCCTTCCTCAGTGAGAGCGTG
          GTGACTCGCAATCATCAAACGCCCTAAAAGTGCACGCCTC
          GTGCACTGGATTGGGCTCTAGCTGGGTCCACGCATGCCTC
          CCGCCTCCGAGAATTGGGGTACCCTGTACGTTCCTGCCCG
          GAACGCGCTACCAAAAACAGGTGACATAAACATGCATTAC

