 8 1000
t1        CCGTTCAAATCAATTCGCTAGTCCACCTCTCAACGTGACTGGGGAATTATTCGATCTGCC
t2        CGGTTCAAATCTAATCGCGAGTGTGTCCCCGGATCTGACTGGGAAATTACCAGGTTTACT
t3        TCATCCAATTTTAGTCGATCGCATACCTTCCCATTTGATTGAGAAGTGCCTAAACCTGTC
t4        ACCTTCGAACCCTTTTGTCTGTATGTCCCCCGATGAGAATGTGTGCTCTTTAACGCTGAC
t5        TCAGTTATATCTTTCTATTCGTAAGCCCATGGACTTAATTGGGCACTGACTAGTCCTCTA
t6        GTAGTCAAATCCCACCATCCACGTAGGCCCAAATCAGACTGGGTTCCGGCTAGTCCCCTA
t7        CCTAAAATCCCGGCTTGACAGGGCAGGCCTAATTATAGGCGGAAGTGCGTTCGTGAAGTC
t8        TCTAATATCTCGGCTTGACAGGGCAGGTCGGAATATTGGCGGAAGTGCGCTCGCGAAGTC

          ATGACGTTTAAGCCTTTGTATCGACATTCGTTTTACTTGTGTTGTTTTTATGATAGTCTC
          ACGATCTTTAAGGCCTCGTATCGGCATTCATCCTACTTGTTTTGTACCTGTGATAGTTTC
          CCAAGGTACCGGCCCTCGATCTCATACTTGAGACATGTGTTGTGTGTCAAGCATACCCTC
          AAAGTAAACTGGTTCTCGCATTGCTGCCTTTTCAGCTAGCAGTGTACCATGGATAACTTT
          CTGACGCACCAGTTCAGAAGTAGATATAGGGTCTGCCCGTCACGCACCGGTGAACGGTAC
          TCAGTGCACCTACCCCATGTTAGAGAAAGGCCACATTGGCAGCGTATTGAGAGGAGCCAC
          AGGACAGGTTAATTATTCGTATCGACCTTATTGCCGGGTAGGCTTGTCCGAGATGGCCTC
          AGGACAGGTTAATTGTTCGTATCGACCATACTGCCGGGTAGGCTTGTCCGAGATAGAATA

          AAGGACGCGCGCCTGTTGAATTAGTCTCTTTAAGGTGAACAAGTAGGTATGGTGACAACA
          GCGGACGCTAGTCCGCTGAATTCGTCCTTTTAGGGTGAACGCGCAGACTTGGCCACAACA
          AGGTACACCACCCTGTCAATCTAACTTCATTGGTTCGTCCGAGAAGATACAGCAATGTCA
          GGGCATATATTACTTTTGACCTAACCTTGTGTAGGTGACTTAATACATTTCCTTGAAGCC
          GGGGCATTTAGCGCGTTAATGCAACTGTGTCACCATGACTGGGGGGAATCAGTTTTGATA
          GGGTGCTTTTTACCGTTACTATAACGGTGCCACGGTGAGTCGGTTGAGGAGGTCGCGTTA
          GTGGTGAGAGCCTATTTCCTGCAACCATGTACTGGTGTGGTCGATGACGGGGTAACGGCA
          GTGGTGACAGCTTAATTCTTGCGACCACGTACTGGCGTGATCGCTGACGGGGTAGCGGCA

          GCGAGACGGACATGTGACTGCTTATCCTGCCACCAGAAAAGCCTTACAGTGCCCTATCCG
          GCTCGACGGATCTAAAAAAGCCTGATCTGCCATTGGACAAGCCTTGCAGGGCCCAACTCG
          TATTGCTGGAAAAGAGGTAAGTTGCCCTGTGCTCGGAGCAGTCAGGCAATTCCCAGTATG
          ATACGAGGGACACGGGACCACTCACGCGGATCGTGGAGTAGGCTCATGATCCTTAAAGTC
          CTCGGAAAAACCGAGGGCAGGCCGCCCCGCTTACGCGTTTAGCCTGGAACTCTAAATCGT
          AATTGACAACCAGAGGACGTGCTGCCCTACCCTTGCGCGTGGCCTGGACTTCCTAGCTTT
          GCGCGACGGAAGGGGGACCAAACTACCATCCATGCGACGCGACCTGGCGGCTCCTAGTCG
          GCGCGACGGAAGGGAGACCAAACTACCATCCATGCGACGTGACTTGGCGGCTCCTAGTCG

          TTGCGGCGTAGCCATCAATTTAATTGGGGCGATGGGATCGAAAGTGCTCTGTCCTCCTTA
          CCGCGACGTAGCTATTAATTTAATTCGGGCGATGGAATCAAAAGCGCACTGTTGTCCTTA
          GTCTGTAGTCCATAGTCTTATGTGGAGCAGATAGTGGCTTAACACGTTTCGTTGTCCTGA
          AAGAGGGGTGTACAGCAATGGGGCGAGTGAAGAGTGGCCCAAGGTTAGACGTTTTACCGA
          ACGCGGGGTGCAGAGCAGTTTTACGGGCGGGTCGTGGTCCAAGACGCATTGTTGCTGTGC
          GCACAGGGCACATAACAGCTTCAGGATCGGGTTGCGGTCCACGACACATCGTAGTTGCGC
          GCCGATAATGCAACACTTCCAACCGAAAAGGACCAGACGGGCGATAGCACAGATGTTGGC
          GCCGACTGTGCAACACTCCTCACCGTAAAAAACCAGACGGGCGATAGTACAGATGTTGGC

          CCGGAATGGGTCGGTGGGCAGCATATTGGTGTTGTGAGCTAAACGTTCCATGTGGTGATT
          TCCGAATGGGTCCGCGAGCGGCATCTTGGTCTCATGTTTTTAATCCCCTATGTGGTGATT
          ATAAGCCGGATGAGTGACCAACAACATGACGCTGCGCTCCCAAGCGCCTACCCTCTCATT
          TAGACTCGGTTCCATGGGCGGTTAGATAGTTCTGGAGGCGAACTCATCCGCCCATTGACT
          CTGACTCAGGTTGGCGGGCGGTAATAAGATGCCCTCTTCATATCGCCCTACTTTATACCC
          TTGAACTGGGCCCGTAAACGACAATGAGATGTCTTCATCCTATCGTCCCGCCTTGAGAAG
          ACGGATAGGGGCCGATGACGACAGTTAGCAGTCATACTTGTAACCTCCGGTCATGAGAGC
          ACGGATAGGGGCTGGTGACGACAGCTAGTAGTCATACTTGTAATCTCCGGTCTTGAGAGC

          CACCAGAACTGCCATATCACCGCTAGTTGCTACCCTGAGTTACTGCTGGTATTGTCGGCC
          CGCCCGGACTACAATAAAACCGCAAGTTGCCCCCTATAATTGGCACTGGTGTCGTCGGTA
          CAGCGCGATTACCACCTCCCTGTAAACCGACCCTCCGGTTTAATGGTAGCGTTGCCGGTC
          AACATCGAATGCCACACCCTTTTAGCACACCCTTCTGAAATACTATGCGCATCGACAGTT
          CACCTCGAATACCAAGCCACCCCCAAACTTATTTCCGAGCTGATACCGGTGTTGTTCGCT
          TGACCCGACTTCCACGCCGCCTTTAAATCTAATCGCGAGTTTTTATCGATGTTGCTCGTC
          TAACCTATATGGTGCCTTTCCACTATACGATTTCGGGGTGTAAGGTTCAGATTAGTGCAA
          CACGTTATGTGGAGCCTTCCCACTATACAATTTCGCGGTGTAAGGTTCAGATCAGTGCAA

          CGCCTTCGTCCAATGTAATAATGATGTCCATTTCGTGGGAACGGATGCCGTCGGAGCAAG
          TACCTTCGTCCAACGTCCATGTGATGTCTATTTCGTGGGAACGGATGCCGCCAAAGTAAG
          AGGTGAAGTTCGCCACAGCGCTAATGATTGTCCTGCGGGAATCGACGGTCCTCGGATATG
          TTTCGTGGTCTAATTTTACTTTGCCGTTTCTTCCACTGAAACACGCGCTATAGAGACCAG
          TATTGTGTGCCACTGCCACGCCAACGTTTAATCGGCGGGAACTGGCATCAATGAAGCCTG
          AGCTTTTTCGCGCTGTTGCTTTGACGTTTCATCCGTGACGAACGCCGGTGATAGAGCGTG
          CGTCAACCTCCTCCAGTCTGTGGACGCCTATGCCGGCCACTATAACATTCCTCAAGTCGC
          CGTCAATCTCCTTCGGTCTATGGACGCCTAGGCAGGCCACTACAACATCCCTCCAGCCGC

          AAGTCACTTTGGTCCCAAACCGAGATCCAAAATGGTTACTCCAACCGGCGGCGATGACGG
          AAGTTCCTTTGATCCGAAACCAAGATCCAATGTGCTTGCTCTAAGCGGCCGCGGCGTCGG
          TAATTCTTTCGCTTAATATTGGCGGTACAAAATATTCACCCTGGACGGGCTCGGTCCTAG
          AGTTTTAATCACTACGTTGCCACGATGTGGATAGACTCTCCTATCGGGCGAAAACGTTGG
          AAAGCCTCTTTCTCGGTATTATTAACGTGGGTCAATTTCCCTCATTGGAAACAGCGTCAG
          AAACCTGTGTAAACAGAACTTGCGACGTGGGTCACCTTCTTCCGTTGGACATAGTGTCGT
          GATCATTCACATCAACAGTCTTTCATACACGTTTATCCCAGAAAACGACCGCAGGCCTGC
          GATCATTCACATCAACAGTCTCTCGTACACGTTTATCGCAGACAACGACCGCAGGCCTGA

          CAAGAAAAACGGCGGCATAGCCTAAGACGTCAGTGACGGCATGGGAATGAGTGCAATACT
          CAAGACAAATCGCGGCATAGCCAAAGACGTCAGTGGTGGCATGGTAACGAGTGCAATACC
          AGGGGCAGCCAGAGTCTAATTCCACGTCACCTGAGACCGCACGGAAACAAGTGAGGAATC
          CGAAGTAACTTGAGGCTATACAAAAGTTACGCGAAATGGCACGGGCAGAAGCAAAAGGCC
          CAAAGTAGTCTAAACCGTAACTTAAGTCGATAAAAACGGCATGGCAGATGGGAATATTAC
          CAAGGCAGCCCAAAACGTAAATCATTTCATCAGCAGCAGCACAGGAGTCGACGTAGGTTC
          GAAAATAACTAGTATCACCCTCTCTGATGCGGGTGATTAGCTGGAAGTAGTCTAAATGCC
          GAGAATAACTAGAATCACCCTCTCCGATGAGGGTGATCAGCTGGAAGTAATCTAAATGCC

          CGTGTCGTGCGGCCCCGCTACGTATCAAGTCTCGTAAGTAATAGGAAATCTCTGTCGTTA
          TGTGTTGAGCGCTCAAGTGACGTGTCAAGGCTCGTAGGTAATAGTAAAGCCCGGTTGTAT
          TGAACCTGACGGCTACTTTAGAACGCACTTTTCGGCGCTGAGTGAAGGTGTTCACCGACT
          TGGATCTTACCGTCACCCGATTTTGTCTGTCTGGTTGTTACGTGGGAATGTCCTCTTTTT
          AGCAACTCATCTCCAACCCACGCCATTCGTCTGCTCGATAGGTGCAGCTTTTTCTTGCCT
          TGAAACTCATGCTCAACTCGTGACGTTAGTCTGGTCAGTAGGCGCAGGTGTCTGCCATCC
          GTAGACCCGCGTCAAATCCTAGAAATGCGGCGCATAATCTGATCGACGCGTACGCTGCCC
          GTAGAACTACGCCAAACCCTAGGAATGCGGCGAATAATCTGACAGACGCATATTCTGCCA

          AATCGAAATCTATGCTCTAATAACAAATCATGCCATTGACGGGCGCTAAGGAGACGTGAG
          AATCGAAATCTATGATCTACTAACAAACTATGCTATCGGCGGGTGATAAGTCGCTGTGTG
          TTTCCGAGTCCACCCCGTATATACAAATTGAGCCCTTGAAAGGAGCACTACAGGTGTTCG
          TATCCGATTGCATGCCTTTCCCGAAGTCCTCGTTACTAAATGTGGTTGAGTAGGCGCGTG
          CGCCAGACTCCGTCGTGTATCTAAAGCTTCTGACATTGTGTGGTCGCAGACGGGGGAGCG
          TATCTGGTGTCGTCCCGTATTGACAAATCCTAATATTGTGGTGGAGTGGGTAGGGGGGCG
          AACCACTTCGTGCGTCGACTTTACATCCGACTCCAAACCTTAAATACCGATAGAAGTGAT
          AACCATTTCGTGCGTTGCCTTTACATCGGACTCCAAACCCTAAATACCGAGAGAGGTGCT

          ATTGGTCGACTGTCCGCGTGGAGAATATTATAATATAGATTTGTATCTTCTGCGCTGAGT
          TTTGGCCGCTTCTCCGCGTGGAGAATATTATATCTTAGATTCGTTTCACCTGCGATGAAT
          CTGAGTGCATCACTGTCGTCAAACTTCTAGCATTATAGATATGTGCAACCTTCGCTGAAA
          CCTAGTTGATCATCGCTGTGGAGGCTACTGCCGTATAGATTCGTGTCATCGTTACGGTAG
          CCGAGATTCCCTTTAGCGCCGATATTGTCGTACTATCGGGTCAATTTGGTAATGTTGAAA
          CTTACACGACCATTGGCATGGATACCGTTCTTTCTCAATTTCATATCTATACTGCTGAAA
          TATAGACACTTCTTTATACGCAATGGGATTAGCATTAAACTGCCCCGCCCCGCATTGTCG
          GATCGACGCCTCTCTATACGCAATGGGATTAGCACCAAATTGCCCTGCCCAGAATCGTCG

          GCCTTGCGTAAATTACCCTTCGAGGGTTCCTTGTAGTGGGAGCTTCCATGTTTCCAGTGT
          GCCTTGCGTTAACTCCCCTTCGAGGGTTCCTTACAGTGGCGGCTTTCATGTTTCCATTGT
          CCGCGGTGCGATCTACTCTCCGGGAGCATCACTTAGCAAAGAGTTTTCTTTTATTGGAGC
          ATGTCGTGTCGCTTATCTTTGCGAGGTGCTACGTAGATGCAATTCCTGCGTTCTCAAGAG
          GCTTAGCGCGCGTTACTTTTCTGTAGGCCAACCCCGTGAACATCTCTATGGTTATGGTGC
          GGGCTTTGCGAGTAATTCTTTGGTAGAACTTGCCTGTGGGCACAGTTACGACTCCGGGGT
          GAACCAGTTCAGTTCCCGCCAAGAGACAATATTAAGATGAGATATTACTGTTGCTGATGG
          GTACCAGTTTAGTTTCAGCCAAGTGATTATATTAGGATGAGATATTACTGTCGCCGATGG

          TGCATAAAACGAATCTATGCTATATTCGCATATCGATTATGCGTGACTTCTGAATCAGTG
          TGCATAAAACGAATTTAGGCCATACCGGCGGATTGATTCTGCGCAACCTATGACCCAGTG
          GGCACAAAGCGAGCTCATGATAAGTAAGCGGTTCGATTCCAGTCCGGTTTTGATCCTGCG
          AATCCAAGTAGGGTCCGGGATACATTCGCGTCGCCGTTCAGTGCGATTCCTGACTCTGCT
          TTCGCACTCCGATCTCGTGGAGGTCGCGCGTCCCGATTCTGCGTCAGTCTTAGGTGCGTG
          TGCCCATCCCGACTTCGAGACGAACATGAGCCCTGATTCTGTGCTGGTGCTGGTGTTGAA
          GCGACTGTGGCGCCCTGCATCAATCTGGCAGCCTGCCATCAATGCTGATCAAGGGTACAG
          GCGAATGTGGCGTCCTGCATCGATTTGGCGGCCTGCCTTCAACGCTGATTTAGGGTACAG

          ATCGTCCCAATTGCGTTAAGGTGCACGTACGGATCCAAGCGCAGAGTCCCGGGTATCCGT
          ATCGTACCTATCACGTTAGGGCGCAGGTGCAGATCCAAGCCCTGGGACGTAGATCTCCGG
          ACTGTTCTTGTAAAGCCCCCAAATAGAGGAGGGTCGCTGGGCCATGATGTAGGCCTACGG
          TTCGTGGGCGACATGTTGAAGCGTAGGCAATGACTCCAGAGCCGGGGTACGGACCTGTGA
          TTTCCTTTTGACTCGTTGGCAAATAGGCACTAACATATGGGGTGAGGCGCGAGATTACAA
          TGTTCTTCTTGTACGTTGGACTGCAGGCACTGGGGTGAAGGCCCAAGCGTCGGCTTTCGA
          AATGCCTTTGAGCTATGGAAGCGTAGGTTCTGCGCTGAGACTTAAAACAATTCTTCATAG
          AATGCGTTTGAGCTATGAAAGCGTAGGTTCTGCGCGGAGACTTAAACCAATTCTCCATAG

          AGCGTTCTGTATGGCAGCGGATGGATAACCGTCCGCCAGG
          AGCGCTTCGAGTGGTCGTGGATTGACAGATGTATATCATG
          GCCGAGTTGCGTGCCCATTGCAGGCTGAGCGTCGGTCATT
          TCCGGGCAGGTTAACAGCGATCCGACTAGCGTGCCTGACT
          AGCGAGCTATATGCACATGGTCGGAACAGCATTAAATACC
          TGCGGCTCGTAAACACACGACTGGCTTTAAAGCCGCCAAT
          GAATAACAACATACTACTAATTAACCTGACATACATTTCT
          GGACAGCAACATACTATTAATTAACATGACATTCGTTTCT

