 8 1000
t1        ACTAGGGGATGGGACAGTGTAGCCTTTTTCCAATATTCCTCAAGGAAGCGCTATGAAATA
t2        ACTAGGGAATGGGACAGTGTAGTCTTTTTCCAATATTCCTCAAGGAAGCGCTATGAAGTA
t3        ACTAGGGAATGGGACAGTGTAGCCTTTTTCCAATATTCCTCAAGGAAGCGCTATGAAATA
t4        AGATTGGAATAGGATCGGATAATTATAATCCAAAGTTGTCTAAGCACGCGATGTAAGAAA
t5        ACCGAGTAATTGTACCAGTTAGATCAGCCTGATGAATGACCAGGCCCATGTAGCAAGGCG
t6        GCATAGGTGTCGGGTTACATGGCACTCTGTCTAGTACGTTATAGCATGTGGCGCGACATC
t7        TTCTGGGTAGTGCGCCACACTTTCTGCCCTAGGGCGTGCCGAGGCATGCGCATGGTGACA
t8        TAACTAAGCGGAGCCAGAAACTTTACGTACTGGGGCTGCATGAATGCGCGATATGATAAC

          CTACCAATCTACCAGTGGCGCCGGAGGTCAGTACGCCAATTCGTGGTGGACTAAATACCT
          CTACCAATCTACCAGTGGCGCCGGAGGTCAGTACGCTAATTCGTGGTGGACTAAATACCT
          CTACCAATCTACCAGTGGCGCCGGAGGTCAGTACGCTAATTCGTGGTGGACTAAATACCT
          TGCGCCATCTCATGCCTACGTTCGTACTCCATTTGCCTAGTTCCACTGGTGCAGATACGT
          TGTTTCGTCAATCTCCTGTTTCCGGGCACCGCATGCTCGCCGATGCTGAACCGAGTTGGC
          TCTCTCCTCAGAGAGGAGTACGTGTGGTTTGCCTCCTCGCAGGTATCAGGTTGAGTCGGT
          AATCACACGGCACTGACGCGTACGGTTTCGTACTGGCGGGCCATCCTCGGTCAAACGCGC
          TGTGGATTGCGGCTGATGTGACGACATCGCTGGCCCGTCTATTACATTTGGCGGCGGTGC

          GGCCTACCACTGGAGCAAGTCGACAATCTTTTTTCATGAGGTGTAGACAAACCCCGGACA
          GGCCTACCACTACAGTAAGTCGACAATCTTTTTTCATGAGGTGTAGACAAACCCCGGACA
          GGCCTGCCACTGGAGCAAGTCGACAATTTTTTTTCATGAGGTGTAGACAAACCCCGGACA
          TCCTTTCTTTTAGAGAACATCTGCCCCCTTATCAGTTTAGTCCCTGCCGAACGTCTTCAC
          GTGCCATTACGGAAGAGCCCTCACTACATGTCTGCTCTGGACCTGGCGGAGACCCGGATA
          GGTCCAATCCTGGAGATTACTGACCGTTCTCTAAACATAGGCACAGCTGGGCTCGAGGTA
          GGCGTGCACCCGTAAGCGAAAATTCATGATGTAGAACATTGGCCTGATTAGGCTTTAACG
          GCCCCACTCTCGGTGTTAAGTGGTTTCCTATAAATCAAAGGATCTTTACATCTCCGAACG

          ATCTATTTACCTTAAGACATGGAACCTTTTTTTGGTCGCTGGCAGAGCGATTCTTGTTGA
          ATCTATTTTCCTTAAGACATGGAACCTTCTTTCGGTCGGTTGCAGAGCGATTCTTGTTGA
          TTCTATTTTCCTTAAGACATGCAACCTTCTTTTGGTCGGTTGCAGAGCGATTCTTGTTGA
          GTGTGTCCGATATAGGATTTCAAGACTCAGCGCAATCAGCCGTATTATTATCTATCTTAA
          ATGGGTTTGAAGCAGACTATTAAAGCTCGATAACGTCCATCATGGGGAGTTTTTCCCAGT
          GTATATTTATCCTAGGGATTTACGACGCGGTGTTATTGGATGTAACATCACGTTTACTGA
          CTATTCACACCTTAGGATCCATGCATACCGAGTAGTCTGTTCCAGACACTCCTTTGTGAT
          AGATGCCCTTAACCGAAGCCTGATGTTGGAGAGAAAGAATAATCGTAGCCCATTCCCAGT

          CTCGAAGCCTCTTGGGGTCTGCCTCTGCGATAACCGATTAGGCGGAGGTTTTTCTCTAGG
          CTCGAAGCCTCTTGGGGTCTGCCTCTGCGATAACCGATTAGGCGGAGATTTTTCTCTAGG
          CCCAAAGCCTCTTGGGGTCTGCCTCTGCGATAACCGACTAGGCGGAGGTTTTTCTCTAGG
          TTTACCTACATTTACGTGGGGATCTAGAGATAACCATTATGAAGATGGAAGATACCAAAG
          ATCACTGTTCCAGAAACACTGTGCATGCAATGAACGCTAAGACCGAGTCGCTCATACAGG
          ATCGCGATCCCAGAGTTTCCGCCCTAGTGTTGACATCGAGCGCCGCATATGTTATCTTGC
          GTTTACACGTTTTAAAGACTGGATATGAGATAAGCGATGGGGGTACGTCTAATTAACTGT
          TGTGATCCCCCCTAAGGTTGTCTCGTAGTGCAACCGCGGAAAAGGAGTTTTTTATACACC

          GATGATTTTGGCTATGCGAGTTAGTCTCCGCCTGTCATAATGGGGGTAGTGCCCAAAACC
          GATGATTTTGGCTATGCGAGTTAGTCTCTGCCTGTCATAATGGGGCTACTGTCAAAAACC
          GATGATTTTGGGTATGCGAGTTAGTCTCTGCCTGTCATAATGGGGCTAGTGCCCAAAACC
          GACCGTTAAGGCAACGAGGGATAGCACTCTTTAGTCTGAGTGCAGTCAGCTTCCATGGTG
          CAAGGTTCTGATAACGAAAAGAGGCGTCAATTAGTGAGGGAGGGGCAGGGGACAAGCGTG
          AACGATCAAGACAACCCGAGCGCGGCAGTCTAAATAACGCAGAGGCCGCTAGTCAAGGTG
          AGCCACGACGGCCCCTAAGGACAGGAACTCCCTTGTCCGCTGATCATAGTTTGCGGCTTG
          GGCAACCGAAGTGATAAAATACGAAGAAGCGTGTCGGCAATGAGTAGGGCGTCCAACGGC

          GGATCGTTTATTCTGAGCGAAGCGACTCAAGCACGGCAAACGTTCCTTTAACAGTAGTAA
          GGATCGTTTATTCTGAGCGAAACGACTCAAGCACGGCAAACGTTCCTTTAAAAGTAGTAA
          GGATCGTTTATTCTGAGCGAAACGACTCAAGCACGGCAAACATTCCTTTAACAGTAGTAA
          AGATGCCCCAGCAACTGAAGGTCTACGTACACTCTATGCCCGCTACTGGTGTAATAGTGG
          AGACCTTCAAGCCTGCGCAGGATACCCTTCACTCAGCACAAGTGAACCACAAGCTGGCGG
          GGATTTTCTTGTCATTGCGAAAGGCGTTCCGTTTATAACTAGCTCACGCTGGGAGTGCAC
          GAACTCGGTACCCTACACAAGGAACCGTGCCGTCTCTGGGTTTTACCTCAAGGCCAACGG
          CACTTATGAAGACGTTGGGTACGCTATCGCGCCCCTGTCCTGACACGCTTGTTATAAGGA

          CCGTACAAATGGTCAAGAGACCTCCGGAGAGCTGCGTATCGTGCCATAACCGGAAGGGCG
          CCGTACAAATGGTCAAGAGACCTCCGGAGAGCTGCGTATCGTGCCATATCCGGAAGGGCG
          CCGTACGAATGGTCAAGAGACCTCCGGAGAGCTGCGTATCGTGCCATATCCGGAAGGGCG
          GCGAATCAACGACGCAGAGGTCTCTGGGGAGACGGGTGTGAAATGACATGTGGGTAGGGG
          TCGCCCTCCGGGTGGAGGCAATCCCTAAAAGAGGTCTGAGATGCGATCCATGGGTTAGTC
          AAGCAAGATCGCTAGGGGTGAAGGTGTTTGGTCGGCTATGAAGTATGGTATAGCACCGCA
          TCTTGTAACGAATGTGCCCACTCTAGGGGCCCCATGTCTCACGTACTAAACATGCGAATA
          ACACCTAGGTACTGCAGTAGATCCCATCCTCCTAAATTTAACGTGGGCCGCAATGGTCCG

          CGGACTGACTCATCGGGTGTTATGTGTCTCAGATGGGTAGCCAACCGCGCACGGTGGCTC
          CGGATTGACTTATCGGGTGTTAAGTGTCTCAGATGGGTAGCCAACCGCGCACGGTGGCTC
          CGGACTGACTTATCGGGTGTTAAGTATCTCAGATGGATAGCCAACCGCGCACGGTGCCTC
          TGGACCCCCCTGACGGAAGCTATTTGCCGTACGAGCACTAAACGTCGCGACCGACTAACA
          CACACCGAATTGATAGACGTTATTAGTTACTAGCGGGCTGATCATCGCGAACGGACACCT
          TGCACTCCCTTGGTCAGAATCTCTTCCTGCTCATAGGGAGCATTCAGGAATCTGTACATT
          AGACATGTACCAAAGGGGGGTTTCTTAAAACTGGAGCCTGATCACAGTGATAACATGGAT
          AGTTCAAATACCGAGAGAGCCACTGGCCATATGTCCAACTGGCACAGGGGGAGGGATAGG

          ACTTCGTCTAGGGCGACGAGGCTCGTTAAATCGAAACTCTAGACGCGAGATATTTATTGA
          ACTTAGTCTAGGGCGACGAGGCTCGTTAAATCGGAACTCTAGACGCGAGATATTTATTGA
          ACTTAGTCTAAGGCGACGAGGCTCGTTAAATCGGAACCCTAGACGCGAGATATTTATTGA
          CCCCAGTGACAGACCCAGTGGGCTATTCGGCCCGGGTTTAGTGCAAGAGGTATACATATG
          TTTCAGTTTCGGTGGTCACGGATGATCCAGCGTGCGCTCAGTGAAGTAGATAACTAATAG
          CGCCGATATCGGACTTTGTAGTTTCTCCCACACGGACCAAGTGGCATAGGTGACTACAGA
          ATTTGGTTTCGATTTTAGCGGAAGTCGTCGTGCAGGCCTATTATAAGCGATGATGGAAAA
          GAAACGCCTGGGGTGATGCAGGCGGTTCAGATTATAATCTTGACGTGCTAACACCGCTTA

          CCGTCTGTGTTACATCTAACAAAGCATATTTAGCACTGCTTTAGCTGGTCCTGATCATAA
          CCGTCTGTGTTACATCTAACAAAGCATATTCAGCACTGCTTTAGCTGGTCCTGATCATAA
          CCGTCTCTGTTACACCTAACAGAGCATATTTAGCACTGCTTTAGCTGGTCCTGATCATAA
          CCTTCAATGTCAATCCTCAAAAGCTTGCTCGAGGACAAGGCTAGTTGTACTCGAAGATAT
          CCCACGACGCCATTGCCTGAGCCACCGTCCCTGCACTATGGACTACACCCCCGATGATCA
          TTCTTGAGCTCACCAATGCAAGAATCATTCTCGTATCTAGACATTTGTTGATGGTGTTAT
          CCTAAAGTCTCGAAGTTCCAAAACACGCATTCTTATTAATACCACTCATCGCGGTATCGT
          TAAACACATGCTGTATTTGAGAGCCTGCCGCAGATTCTGTTGATAAAGTATTGTTTCCGA

          TGGTTTTCTGCCTAAGAGTGAACCTCCTATACAGGTCGACACTGGGATCGGGCAACTACG
          TGGTTTCCTGCCTAAGAGTGAACCTTCTATATAGGTCGACACCGGGATCGGCCAACTACG
          TGGTTTCCTGCCTAAGAGTGAATCTTCTATATAGGTCGACACTGGGATCGGCAAACTTCG
          CGGCATGCAGCTCAGGAACGACGTCCTTCCTATTCACCATCTGGGGGTAAGCCACTCATG
          CAGCCGTTGGTTGCAGGGAGGAGCCTTTTTGATCCAGGGAGCATAGATAGGCAGCCCATT
          CGTCTATTTATTTTGAGCGGTACCCCGTGCGTACGTGGACGACGGAACTGACAGTAAGCG
          TATCCCCTCGCATGGAGCTGATACGGTAATTATTAAGGTTCAAGGGGTGTTACTTCGATA
          AGGAGCACTTATCGCCATTGTAATGACACGCCCTGACGAGTCGACCTTGCGGCACGGATG

          ACTATACGAGTATCAGTTCCGCGTCCGGAAGGCGGACGAAGCTGGTACCACACTTCTTAA
          ACTATACGAGTATCAGTTCCGCGTCTGGAAGTCGGACGAAGCTGGTACCACACTTCTTAA
          ACTATACGAGTATCAGTTCCGCGTCCGGAAGTCGGACGAAGTTGGTACCACACTTCTTAA
          GAAGCATAACGCTAGAAGCAGGCACCTTCAGTTGTAATCCGCTGGCGACAGTCATCGAAT
          CTTTCACGCGGCCTATCGTAACGTATCTGTAACGGGGCGCGGTAGCACGCGCATTTGGAT
          CACAAGTGTTAATGAGCTTGAGGCCTTTAAAGTGGAGTCCGCCGGGCCCATGTTTCAAAA
          GACGTAATTAATAGTGGTCAGGAGCACTTTGTCTTAGTATTGTGGATGCGTATCTCTAGA
          CTTGTGTATAGTCGTTCTACGCCTGTTGTCACAGCGCCGAAGTAGACGCAACACCCCCAT

          TGCATCCAGGTTGCGTGCGCGAGGGACGATGCTTCCCTTCAAGCTTCGCCTCGCGGTCGC
          TGCATCCGGGTTGTGTCCGCGAGGGACGATGCTTCCCTTCAAGCTTTGCCTCGCGGTCGC
          TGCATCCGGGTTGTGTCCGCGAGGGACGATGCTTCCCTTTAAGCTTCGCCTCGCGGTCGC
          CGTGCCAGGATTACTTCTTATTGACGGGAATGCCCACCCCGAGTTCCGAGCCATACCACT
          TGCGCTAGAGGCATGTCCGGAGCGGAGGAAGCCGCCCGTTGCTCTCCAAGTGCTGTTTTT
          AGTGCTGGAATCGCGTTAGGCGACAAAAGAGCTTTTTAAGGCCTCTCGACATAATGCTAT
          CTCGTGGACGTTGTGACTGTTGGCACGCACATACTCAGTGGTTGCACAAGTCTTAGGTGT
          CTCGCTGGGGGCGCAGACGTCGGAAAAAAGGATAAGGACGACTGCAGGTGCTGAAGATAA

          GCGTCTTATCGGAATTGCGAAGCGAAGTATGCCCCTTTAACCCCAACTTGCCCACTCTGA
          GCGTCTTATCGGAATTGCGAAGCGAAGTATGCCCCTGTAACCCCAACTTGCCCACTCTGA
          GCGTCTTATCGGAATTGCGAAGCGAAGTATGCCCCTGTAACCCCAGCTTGCCCACTCTGA
          GAGCATCATCGCCAGGCTTAAGCGCGGCGCAGTTTTCAAATGGTTCGATACCCCATACAT
          ACGTCTCGTCACTTACGTGGAGCGCTGAATACCGCAGGAGTTTATTAATGCGAATTCCCC
          ACGCCTCGCTGGTCAACGGGCGCGAAACTAATCAATGCTACTTAAAACTGCGTACCTCGT
          ACACGACGCATAGAGTTCGGACACCGATTCGTTACTTCTTTTATCATCCTCGGATCCTAT
          AAACAGTACAGACCCACTCGGCGACAGCTAGGTATACTGATTCGCTGCAGCGTTCGGTTC

          AGGTCCACAACCTGCAACTCCGCGACGTTGAGGTGACACGTCTATTCCATCATAGAGAAG
          AGGTCCACAACCTGCAACTCCGCGACGTTGAGGTGACGCGTCTATTCCATCATAGAGAAG
          AGGTCCACAACCTGCAACTCCGCGACGTTGAGGTGACACGTCTATTCCATCATAGAGAAG
          AAAGGTAGTAAGATCATCCCTACACCGCCAACGGCCAAGCATTGTTTACGCATGAAACCC
          ATGGCCTTTCCGGGGAATTACGTAAACTTAGCCATAAAATACCTCCTTTTGACAGACGAT
          ACGTTACTCAAGAGAAACACCGAAATATCAAGGTGCTACGACGGATCTTAACACACACAC
          GCGTCTTTCATAGGGAATAGCGCTCTCCAGTTCTATGATAGTCTTTGCACCGCAGCCGTG
          TAAAGTGCGGTGAGACATCCTAGTGTCATGGTGCCCTCGCTTTGTGTACCAAAGATTCTC

          CCCCAAGGTTTACGGCTACCGCGCTTATAGTGCTGGTGAT
          CCCCAAGGTTTACGACACCCGCGCTTATAGTGCTGGTGAT
          CCCCAAAGTTTACGACACCCGCGCTTATAGTGCTGGTGAT
          GTTGATAGCGAACGGCATCTACGAAGTCGGCGTCGACAAC
          ATTGAGAGGATACGGTATCCGTACGGATGGGATAGATGGA
          CCTAAGAGTCCATACCGTCTACGTGGGTGGCGTGGCCGAT
          CACGGGAGTCTATAGTACTCCTGCCGAAGTCATCAATGAC
          CGGGGGCGCGCAAAGTGTACTGGTCCGTCGTACAAGTAAT

