 8 1000
t1        AGTCTGGCAATACGGGGCTTACGTTCAGAACGCAGGCATTCTCCCAGTAGGCGTCGAATG
t2        AGTCCAGCAATACAGAGCTTACGTTAAGAATACAGGCATTCTCCCACTCGGTGTCGAAGG
t3        AGCTAGGCGATGTGGGGTCTACGTCCAAAATGCCGTTATGGTCCCATTAAGTAACTAACG
t4        GTTCCGGCAATAACGAGTTTATGCAACGATGGCAGGAATTCCGCTACTCGGCCACGAATA
t5        ACTCTCGCGCACGCGGACCCGGGGTCCCATCCTCGAGTTTCTACCGCTCGTGTACGAACG
t6        ACTCTCGCGCAAGCGGACCCGGGGTCCCATCCTCGAGTTACTACCGCTCGTGTACGAACG
t7        GCATGGACAGCAATAGAATGCGGGACCATAACAAATGTCCAAGCTATATAGCACTTAAAG
t8        GGTTGGGCAAACGAGGGTCGAGGCTAGGGTGCAGGATTGTACAGCAACTAGCAACTGATA

          GAGAATATTATAGGCGTCGTCTAAATAAGTGACCGGACCAGAGACAAGGATGTATGGGCC
          AAGAATATCACAGATGTCGCCTAAAAAAGCAACCGGGCCAGAGACAAGAACACATGTTTC
          AAGATTACTACAAGTGTCACCTATCATAGGAATCGGGCCCGAGTCCAAACGGTGAGCCTA
          ACATCCTTGACAGGTACCATTCAGAGTACAACACGATTTCGAGTCGAGAGCATAGAACTT
          AGATCTATGGACGACCATGTAGGCAACGCTGTATGACCCCGAACCGAATGCACGAGGCCT
          AAATCTATGGACGACCATGTAGGCAACGCTGTATGACCCCGAACCGAATGCACGAGGCCT
          GTCTTAACAGAAAGATATGTCCTAAACCGTGAGGTACACTGTTTCACCATAATGGCAAGC
          AGGCTATAGTAGGAGCTTGAATTTGCTTGCTATCGTACTTGCTTGGCGTGCCCCGTGGGC

          GCCTAGCCGACCAACAGCTCCTCACCTTATAGGTTATCACAGTCCTATCGGTAGGTTAAT
          GCTTAGCCTACCAATGACTCCTCACTTTATCGGCCATCGCGATCGTATCGGCACGTTAAT
          ATAAAACGCAACACGAACCCCCCACCTCGACGGTCACCAAAGTCGTTTCGGCAAACCTGC
          ACATGGGTAATTCCTCATCTCTCCGCGCATAGGTTATGGTGATGGTCTCGGCTAACCGTC
          GTATACGAGGCTGCTGACTCTTTCCCTAGTAAATGACGGTGGTGGTTCAGCAAATATACG
          GTATACGAGGCTGCTGACTCTTTCCCTAGTAAATGACGGTGGTGGTTCAGCAAATATACG
          TAATGAAAGTACTCAAAGACTTACTAGCTGCTGTCGTGTGACTGAAACGGTTTCGTCGGT
          GTCATAATGGCGTTGGACTATACGCAATAACGGTCTTAGAGACAAGATTCCCAAGTCAAT

          CACCCCGTGCCTCAAAGGCTAAACGAGTTATTTACTTGGCCATGTGAGGCGAACCTTTAA
          CACCCCGCGCCTCATTGGGCAAACGGGCCATTAACTTGGCCATGGGGGACGAACCTTTGA
          CAATATCTGCCTCAAAGGCCAAAAGAGTTATAAACTTGGCCACGGGGGCAGGATTCTCTC
          TACCTCAAATCCATTATGCGACAGGGGAAGCTGGCTTAGCCATGGGAGGATAAACGTCAA
          TGACACTTGCACCGAAAAACAGACATATTCTTTGCGAGATAATTGATGACTCGCGCCCAG
          TGACACTTGCACCGAAAAACAGACATATTCTTTGCGAGATAATGGATGACTCGCGCCCAG
          TACTACCTCCTTCATCAGCCACATTGAATTCAGAGTCAATTATCAGATGCACCTACCTGG
          CATGCATTAACGCTTAGTTTCCATAGGGATCTGTTTGAACCTCGAGTTGCTCTCACCAGT

          CGGAACCCGGCCTAACCAAGTACACTAGAGTATGACATTGCTAGCCGGACTTAACGAGTC
          CGAAAGCCTGCCTATCCCAGTACATTAGAGTATGTCAACGCCAGCCGGATGTAACGAGTA
          CGGAACCTCATCCATCCCAGTATGGTAGAGTGTGTAGACAGTGGCCCGGTGTAACCACTC
          TTTGATCCCCACGACAGATGTTCACTTAGGCGCAATGGTGCCAGTTAAGCGAAGAATCCT
          GAGCTGTATCCGCGTTAGAGTCCCCTCGGGCGCCGAAATATGATTCCTTTGTTGCGAGCT
          GAGCTGTATCCGCGTTAGAGTCCCCTCGGGCGCCGAAATGTGATTCCTTTGGCGCGAGCT
          CATACGCTTCCCAACGTAGGCTAGCGAGAGAACGGCATTGAAAACAGGCCGCCGAGGATC
          CACAAGTCCCGAAATCTTGGTCCGTGAGAGGGCTTCGATTCGGTTCCAATATTAACATTA

          TCATGACAAGGGACCACTTTCTCTCTTAGTCGCATTCTTATCCGGCCACGAAGATGACCG
          TCATGACAAGGGGCCACTTTTTCTCTTGGTCGCATTTTTATCCAGTTACGTAGATGACGT
          TCATGACGAGGGATTACTTTCTCCCCTGGTCGCATTTACCTCTAGTTATGCAGATGATCG
          CTACAACGAGGATTTATCCCGTCTCCCCGTTACATGCTCACCCGGCTGAATAGTTGACAG
          GTGTGGGTTGGCGTAATTTTCGTGCGCGTTGGAGTTTGCGCCTCGAGCTACAGAACGCGT
          GTGTGGGTTGGCGTAATTTTCGTGCGCGTTGGAGTTTGCGCCTCGAGCTACAGAACGCGC
          GCACAAGGTCCACTGATTGTGTCCCCCGCCAGTGTCAAGGGCTGGCCGTGTAAGGGCGAT
          GCGTGAGGCAGACTGATTTCATTCCGCAATGATCATCACGAACGCCTGTGTAGACGGCCG

          GATCGGTCCGTCGTGACTCGTAGGTGGCACAGAATGTAACTGTGACAGCGTAAACTAGCT
          GATCGGTGCGCCGTGACTTGTAGGTGGCACCGAATGTAACTGCAACAATATAAATTAGCT
          AGTTATTTCGTCGGGACACGTATCACGCATCGAATGTAATTGCGGTGATTGAAATTAATC
          AATAGGTTGAAATTGATTCGGGGGTAACATTGAATTTACCCGAGCTAGTTCGACTTACCC
          CTGGGGAAGGTTATGCATCAGACGTCGCTACACTTGAAGTCGATGCAATATAGACAACTT
          CTGGGAAAGGTTATACATCAGACGTCGCTACACTTGTAGTCGATGTAATATAGACAACTT
          GACAGGTGCACACTAGGACGCGCCTCATGTCGCCGACGACAGCTGCGGCGTGTATTATCA
          GCTCCGCTAACCTGGGGGTGCGCTATAGGGTAATAATGACGTTAGGGGCTGTTGTTAAAA

          GCCCGATATCACGACGTCAGACGTCTAACTGAATATTATGCATCGACATGCCGTAGACTG
          GCGTGATATTACGACGTTTGGTGAATAACTGAATATTACAAATCGACACACCTTAGACAG
          GCCCGATAACACGACATCCGATCTATAAATGAGCACTATGTGTTGCCATACCTAAGTCTG
          GCCCGGCATTAGCTCATTGGATCCTTACGCGAGTTTCGTACGGTGCCATAAACTAGACTA
          GTCCTGCGTCCGCATATGTAGCGTCTCTCCGAGTCCTATAGTTCAATATTTACGAGAGTG
          GTCCTGCGTCCGCATATGTAGCGTCTCTCCGAGTCCTATAGTTCAATATTTACGAGAGTG
          GCTATGCCTTTACATGTGTAACATGCACGCTGTTTGTGTCCGCCGCCATATTGTCGTTAA
          CCCCCGCTCTTAAAAAGGATTTTCGCTGATAGCGCGTCTCCCAGTCTCCGATTTCGCATG

          AACCGCACTCAACTCCTCAATGAGCCCCTTGGACAGTCTGTACGTTGCCAGTCTCAGGAA
          ACTGGTACTCGACTCCTCAGCGCCCATCTCGGACAGCTTCAATATTGCCCGTCCTGGTGA
          GACGGCAATTAACTTCTCATTCTAAAACACGGCCTCTGTAGGAATTGCCAGTTCTGTGTA
          GCGGCTAGGTAGTCCCCCAATTCCACCGGTGTAGATAGCAAGAGTCCCCAGTTTGCGATG
          TTTACGTGTTAGGCATTAGGTTTTAGTTACCCACCTAGCGGCCAGCAGCAACCAGTGGTT
          TTTACGTGTTAGGCATTAGGTTTTAGTTACCCACCTAGCGGCCAGCAGCAACCAGTAGTT
          ACGAGTCTACTTCCGAGCCGTAACCCGCTCCAACCGGTCGGTGCGCACCCCCGTTCGATT
          AGACCATGCTGGTTGTGCCATACTGTGACTTTACTTACCACATAGAATTCCCGGTGACAA

          CGTCTTCCGACAGGTCGCACAAATTTCCGCTAAATCAGACTGTAGCGCCAATTATGATAA
          CATTTTCCGGCAGGTCGCACAAACCTCCGTTAAATCGGACTGTAGTACCAATTACGAGAA
          CGCTTTCCGGCAGGTTATTCAAACCCTCGCCAGACTCGACTGTAGTACCAATTACGACAT
          CACTTTCCAGTCGGTAATATTACACGACGCCAAATGAGATCAGTGCACCCTTCATGACGT
          GTCTTCCCGCACTTATATGTCGCTCGGCGGCTATCCAACCTCGCACACTTAACTTCGGGA
          ATCTTCTCGCACTTATATGTCGCTCGGCGGCAATCCAACCTCGCACACTTAACTTCGGGA
          CGGTTTCGAGTGCACTGATTAGATTAGCGTTATCCCAATTACGAACAAGACGCCTAGGGG
          AGGATTTGAGAGTGTAGCGCTAGACAGTGGCCTACTGTACCACGGCACATCCTGTCCCGT

          GCAGAACCGATTGCCAGTGATATGACACAGCTTTTGCCTGCATATACAGGTAACCCTACC
          ACAGAAACGATAGCCGGAGCTATGTCGATGCTTTTGCGTAGATACACAGGTAACCATACC
          GCAGAAGCGCTATCCGGAGTCACGACACTGCGCTTGCGTAGATACACAAGTACATCCAAA
          ACTGAAAAGCATAGTTGCGCTGCTACATCATAGCAAGGTGGGCACACGTCTGAATCTTCA
          AACGACGAATTTGCAGCTTGCGACGTGGTGCAGGAGCCATACCTCATAATTCACTCATTT
          AACGACGAATTAGCAGCTTGCGCCGTGGTGCAGGAGCCATACCTCATAATTCACTCATTT
          GCGGATGTTCGGGCTGGCCAGGCGGGCCTGCGACATTCGGGACTGGACATTTATAGAACG
          GCATGACGTACGCCGCACCCGGTGACGTGCAGTTAGCTAATACTCTTTAATTCTAGGCAG

          CCCTAAAGTGATTTCGTAGTTAAGCTTCGCTCAGGCAAGGTCAATAGATCCGTGCATCCC
          TTCAACAGTGTTCGTGCAGGTAAGCTTCGCCCAGGCAGGGTCAATAGATCCGTGCATCAC
          CTTAAAAGGGACTCTGTAGTTCAGCCACGCCAAGGCAAGGCCAACAGATTCCTAAACCAC
          GTTAAAAGTGACATTGTTGTACGGCTCTGCCTAACCGGGATTGGTATTCCGACGAAGCGC
          GTTAATAGCGAATCAACCAACAGCCTCGCTTTTATCGCGACGATTTACTGCATGTCGCTA
          GTTAATAGCGAATCAACCAACAGCCTCGCTTTTATCGCGACGATTTACTGCATGTCGCTA
          AGGTAGGGGAATAATAAAGGCGGCCGTTGCTACGGGTCTAACGTAGCTAATAAAGCTTCG
          TCGCAGTGTGGATTTGAATTTAGGTTCCGCCGCGATGAAATGCTAGGATAGAGGTCTACA

          TCACGCAATGACGGAGTAAGGTAGTTTTCACGTGGTTTTTTGTCAGCTCTACACTGTGGG
          ACATGCAATTACGAATTAAGGTAGTCTTTACGCAGTCACTTGTTAGTCCGGCACCGCGGC
          AGATGGCACCATGGAGTTACGTAGTCTTTATGCTGTTATCAGTCAGCCTGACACGCTAGC
          ATATGCGACCACGGACGATGGCGACTTCCTCGCTGAACACTGTCGATTTGCTATGCAGGC
          AAGTAAGAGTGTTAGATGACACAGTTTGGCCTCTATCGGCTACGAGATCGACCAGCCGGA
          AAGTAAGAGTGTTAGACGACACAGTTTGGTCTCTATCGGTTACGAGATCGACCAGCCGGA
          TTACGGCGACGGCGTTCATCTCAAGCATTACGACACCGTCAGCAATACTGTTACGGCAGG
          GTGAGGTTTCGGCGGTCATTGCGATTGCCTGACCATTGGTCGGAAAATCGGCTTGGCGAA

          ATAGCGCGCCGGATTTATCTGAGCCCGCAGATGATCAGCCTTATACTCAGTGGAGGGGTT
          ATAGTGCCCCGCGCTTACTCGGGCCCACAGTTGATCAGCCTCATGCTTAATAGGGGGATA
          TGAGCGCGCCGATTGCCTCTGAACCCACGGATTTTCCGTCTAATGTCTCGTAGGGAGTTA
          CGTGCGCGCCGTATATGTCTGCGACTACGGATGAATTAGTATCGTGTTAATACGGTACCA
          GACACGCAACACCTGAGCCAACATCTCCTTTCGGCGCACCACAACCAAAAGACCTAATCG
          GACACGCAACACCTGAACCAACATCTCCTTTCGGCGCACCACAACCACAAGACCTAATCG
          CTTCTGCTCACGGACAACTCGTGAGGATATATGGGCCACTCAATCTGCGGTGTACGCCTG
          TGCATGTAATGCGAAACCTACTGACCGCTGCGGGGCGGCCCCACCTACGACCTAAGCGCG

          GCTGGTGCATTACCTTTCTTAGGCGCCCGAGGTTGTTTCTTGGCAGCCGAACCTCATCGT
          GTTGGTGCCCTATTTTTGTCTGATGCATGAGGTTGTTCCATTGTAAGTGAACCTCGTTGT
          GTTGGTGCCCTGCCTCAATTCGCAGTGCAAGGTAGTTGCGTGGTAAAGGAATCTCGTCGC
          GTCCCATCCCGACATATGCTCGCTGCACATAAAGGCTACTCGGTCAGTGAGCAACACCGT
          TTTACAAAGCCAGAGCTTATTGGTGATTACCGAGATCCCAAAAGCAGCAAAGGACGAAAT
          TTTACAAAGCCAGAGCCTATTGGTGATTACCGAGATCCCAAAAGCAGCAAAGGACGAAAT
          ATATGATGTCTTCTGACCCTCCTCACGTACACATTACTCTGTAGTACCTAGTAAAGTTCT
          GACCTTCAACTTCCAAATTCGTTTGGACCGCAAGATATCTTCCCCTGTAAGTGACATCTT

          CGGGTGACGGTGGTTGGGCCCGGAAAGCACGGATACGGTTAGTAGCTGAAGTCGGTTTTA
          CTTGTGAGGGCGGTAGGGTCTGGAAAGCAAGGACACGTCTTGTGGTTGAAGGCGGTTTTA
          ACGGTGGCGGCCAGTAGGCTTGGAAAGATACGATACATTCTACGGCTAAGTGCGGTTTCA
          CCAACGACAGTCACCGTTTGACGGGAGATAGAATGTAAGGTCTGACCGAGGATGATTGCA
          CCGACCGTAGGGACGATTTGGCGACGGTAACGGTTTGTAGCTACAGAGGCAGTGACGATT
          CCGACCGTAGGTACGATTTGGCGACGGTAACGGTTTGTAGCTACAAAGGCAGTGACGATT
          TTCATAAATTGAGGTGCCCAGGGAGAACCGTGATGTGATTATGCACCCGTGGCGAGAACA
          TTGATTACGGTTACAGTCCGATGAAGGTTAAATCGTGTGTTTCACATAATAGTGGTCGTT

          TTCTCCGATCTTCCTCCTGTCCCGCTAGGAAGGTTCGGTA
          CTCTCCGATCTTCCTCATAATCTGTAGGAATAGTTCAGCA
          CTTTACGATTTTCTTACTGGCTCGATGGGACGGTTTGGGG
          CCCTCCCACCTTCATCTTTTCTATACAGAGCGGTTTGGTA
          AACCAGCAGCCCCTGCTTGGTTTTACATGGAGTGAAAATA
          AACCAGCAGCCCCTACTTGGTTTTACATGGAGTGAAAATA
          CCTTAATGGTCCCGCCATAATTCTACGGGATGCCCCAGAA
          TCCTTAGCCGTTTCTTTCCCCCATGAGGACGATCGAAACA

