 8 1000
t1        GCACGGTGCATTCTAGAACTACTCGGTTTGATCAACGATTACCGTCTACTTCTTAGGAAG
t2        ATACGTCGTAATCTTGAATCGATCCGTATAATTATCAGCTACCGTAATTCTTACAGGGTG
t3        AGGCGGCTTTCTATCAGCTTCCTCCCCGTTTTCGAAGAGTGCGAGCAGGCCTTAAGGTTG
t4        GCTGACTCCGTACCCGGATCCCGAGCTGCGTTCAATGTCTATTGCAGAATTCTATGGTTA
t5        TAGAGCCCTTCCTTCATAATATGCAACGCGTTTAACCAGTTTGGTCTAGTCTACGAGGAA
t6        TAAAGCCCTTCCTTCGTAATATGCACCGCATCTAGCCAGCTTGGTCAGGATTACGAGGAA
t7        ACCAGTTTCATATGAGGGGTATGCTGCACGTATGAAATGAATATTAAGGTTAGCGGATGG
t8        AGGAGTTCAGCGATCGACTAAAGTGGTGGGTCTGTCGTATGCCGTGAAGCTAGCAGAAAC

          GGGATTCACAGTTTGACTCAAGAATCTAGGGGCAACGTGAGCAGACGTCCGTCCCCGGCT
          AGACCCTCCAGTCGGCACCAGCAAACGAACAGCATAATGGGTGGGGGTTCACTAGTGCCT
          CCGTTCCCCTGCGGACACAAGAAGTATTAGCGCGCCGCGATACGGGTTTAAGCACTAGAC
          TTCCTGATATATTGATCTGACGAGTTCTATAACTATTCAGGATGGGTACTATTCACGGGT
          TCGTCACACGGTAGGCCTCATATGATCAGGAGCTGCGTCGAGTCCCTTTTGGTTCTAGGT
          TTGTTACACTGCAGGCCCCCTGTGATCAGGTGCCGGGTCGAGTCCGTTTTGGCTCTGGGT
          CGGGGTTGTCTTTCGTCTCTACAGCTTTGATGATAACGACTGTAGAAACTGGCCCTGAAC
          CCAGCGTATTTTTAGTTACAGTACATACGGCACTGGGTCGAAGGGATTCCGGTCTTAGGT

          TCCCGATTCAGTATCGGTACTTAAAGTCTACCCTTCTTCTTAGAGTGCGCAAGACGTGAA
          TACCCCATAAGAATTGGTTGCGGAAGTCAGTTGCTGTTTGTAGAGCAGCTCAAAGATCCT
          TCTTTGAAATCGGACGGTTTATCATGAAACACACCACTCGTAGGGCAGGCGGGAAAATTG
          CATTAGCGAAAGCAAGACCCATCGCGGGGGTTAACTCTCGTAGAACATGCCATAAAAGTT
          TTCACATAGTTGAAGATCATATAACAGTGATCCTAGTATGAAGTACATCTCCTAACGATT
          TTCACATAGTCGAACAACATTTAACAGTGATGCTAGTATGAAGTTCACCTCCTGACGATC
          TATCGGGCTAGTTCAGGTGATCCAGTGCAGCCGCTGATTGTAGTGGGGAACTAACGGCGT
          TTGGAGAGAAAGATAAGATACTGAAAGTGGTGATCCTGTATAGAAGGGGTTCAGGAATAA

          AATGCGATTAACGGATGACTACCCGATGGCGGTATACTTGTCCTAAATCACTGCTTTCCA
          GAAGTGACCTATAGACGACTGTCGATCAAACGTAAAGTTACTGTAGCTCGCCCTCATTCC
          AGCATCATTACCGGCGAAAGGACGATGGAACGTGTATTGAATGATAGTACTGGCTCATCC
          ATTGTCGCCCGCCCAGAACAGTCGTTGACCCATCCGACGTTCAGTAATCCTTATCCAACA
          GGAGCTACCCTCAACGGAATAGCGGGGTATCATCCAGTAACCACTACAGACAGTATCACC
          GGCGTTACACTCTACAGAATGACGGAGTATCATCCAGTAACCAACGCAAGCCGTATCACC
          CGTGATATTTGTGCGGTCCCGTCCCAGAAGCACACCCAAACTGTAGCATTACACTCACTG
          GCCGCCAAACACAGAGCATCCCCAGTGAATGACCAATCAATCGTGAAAATAAGACTAACC

          AGGAATTTTGCTACATGAAATAAAGAGCACCCTTATGTTCGGAGGGCTGTATCCCTGCGC
          GGGTTGACTTACCGAAGGGGATATCCTTTCTCCCTCAACTGGACGCCTACAATTCCGTGC
          GCATGTACGGAGTCAGGAAGCGTAGTTTCCCCTCCTCCTATGGTGGCACGTTTCAGGGCA
          GCGATGATAAATTCAGGATGCCCGAGATACTCATCGCATGGTGGGCAGAACTTCGCGGAG
          GGAGGCTGCGTTCTTCTGTGTGAAGGTCGTACACTAACCAGCCCTATGAGCTTCCGCCGG
          GGTAACTGCGTTCCATTATGCGGAAATTGTACACTAACCATCCCTATGAGCTTCCACTGA
          GTGGCACTAGGATCCCGATGCTGGGACATTCGTTACGGTAAGAAGGCGCAACCTCTCCGG
          AATAACTTGTGTTCCCCCAGTCAGCGAAATTATTCGCACAAGTATATCAGATCTTAAGGG

          GCAAGGAGGCACGTCACCAGAAGATCCCAATTAACGGTAGGGCGTGCGATTCGTAAACCG
          TTAGGGGGATATGCAACTGTAGGGTTTTAGATGATGACAGACCTCATTGTCCACGACCTG
          GCCGCGGGAAACGCCACCAAAGAATCTAGCAGGTCTTACGGATTTACTGTGCGATCTCCG
          GCTGCGACGCACGGAACCTTTTAAACTGAAAGAGCCAGTGGAGCAATTAAAGCAAGTCCG
          CATGGGGTGGATGTCATCATACGACTGCAGTTGACGTACGAGCACGTGGCCTAGCTTTAG
          CATGGGATCGATGTCGTCATACGAGTGCGGTTGGCGTACGAGCAAATAGTCTAGCGCTCG
          GCAAGGCCGGTTGATTTCATAAAATCTCGAACATACTGAGACTGTTGCCCTCCATACCTT
          GGAGGGGTGAGTCGCGGGACATTTCTTCAGTATTCTAGGTGGGACGGCATAACCCATATT

          ACCTTCCTATCTATAGAACAACCTCTTAAAAGATGCATTAGTTTGCGTCTAAGCGAAACT
          GCGTCCCTATCTCTGGTATGGGCCATAGTAGGATTCCTGGGATTATGACCAAGTGAAAGT
          GCTGCTTGGCTAATGGTCCTTAGCGCTAAGCAGCGTACGAGTTGACTTCTTTGCACAACC
          GCCATCTTGATAGATATCTGGGACCTTGGGCGATAACTAGATTGATACACATGGAACGGC
          GCTCCCGCGACGGGCAGCCGAAATAACCAGCGACGAGTGGATTCGCGCATTCGTGAGAGT
          GCTCCCTCAATGAGCAGCCGAAATAACTAAAGACGAGTGGCCTCCCGCATTCGCGAAAAT
          GTCAACGTCCCGGTTAATCAGAACGTTGCGTGGCAACGATCTCCGCAATTTCTTGAGTGT
          GTCAATTAAACGCCTGCGCTACGCGGTGATAGATTAACGGACAACTGAACATGCATAGGT

          CGTGATCGCTTCGGTGGATGCGCGGGACGGTATTCTTTCTAATCGGAAGTTGATACCTTG
          ATGGAATGCCCGAGTGGGCGTCCGGAACGATACACTTGTCCATCGGAGGCGAATGTCACG
          CGACTATGCTTAAATGAAAATACGGAGTAACATCCTGCTGCATTTTGCAAGCTGGATAGG
          TAATCCCGCTCTAATTGATCTGTGACATTCGATCTACCATCGGGACTAACGTATGACCGG
          AGTCTCCGATCTTGTGACCGCGCGAGGTACCACACCTGTACGCAACAAGCGACGGGACAG
          AGTCTCTGATCTTATGCGCGCGCGCGGTACCACACCTTAGAGCAAAAAGTGACGAGACTG
          TAATAATCCGTCTTGACGGGCTCGGGGAGGCGCCGTGCCAGGCACTCACCGGTGATCAAG
          GGTGCAAGCCTCGCTGCACATATGAGCTAACGATTGGGCAGTTCGCCAGTTGCAGATCAG

          GCCTTCAGGATTACTCCATATAATTATCTACTACAGTTGGGCGAAGTGCAGAGTATCCCG
          GCCTCCGGGACGATCCTTTTCACCCGACTGTTTTACCCGCGGGATAAGCGGGACCACCAG
          GTACCATGAGAGTCCTTGGATGGCTTTCCACTCCTTACACAGGGGTATCACACACCAATA
          CCTCTTTCAGCTGGGCCGTCTGTATACTTTCCTCTCGCACAGCCAGCATTCATATCATTA
          CCCTTACTGGGCCCCTATGAAAAGCCGCTACGGGTCTTTGAGTACATGCTAATATCTCTT
          CCCTTGCTGGATCCCTACGAAAGGCCGCTACGGGTCCTCGAGTACATGCTAATATCTCTC
          TCTCCACCGGCGCTCCTCCAAACTCGTAAACCTCTTACCGGGGTCGAGACAGCAATGCTA
          TATGCCTTCATCTTCGCCTAAGTTTTTCTTAATCATCCCGGTATCAAGAACATTGGTTTG

          TTAGTTGCGTAACTAAAATCTGTCGGATAGTAGCTATCACTGCGAGTCTAGGTTATGTCA
          TTGGTCGTGTTGTGGCACTCCAACGGATGGGAAATACCCGTCTGGCTCTAGGCTACGCGA
          CTGAGTTTGTAACCCGTACATACGGTATATTAAACTCAGAGCGATGCCTAAGAACTTGAA
          TCGGGCCCGGAGAATACCTACAATGCGAAACTGATCATTTCCAGGGGCCGAGCCTCAGAG
          ATGTATGGGCCAAATACATACGGTATGGCACCCTCTTTCGCCTGGGTTGAGAATCCCCTG
          ACGTGTGAGCTAATTACGTGCCGTATGGCACTCTCTTTCGCCTGAGTTGAAAATCTTCTG
          TCACGCGCCGGAACTATTCCCGCCGGATATTGGGCATAGTGTGGAATAAAATACATCAGA
          CTTAAGACGTACGCGAATTTGTTGGAGAATTAGCCACCGCATCACTTGCGCCATAGTCCG

          GTTTTCGGCCCTGGTATGTGGACCAGTTTCTACATGAGGCCCTTGGTGTTCGTGAAGGCA
          GTTTTAGACTTAGAGACCTGGTCCAACCATTACCCGCGGGACTCATACACCATTCTGGCA
          CGCCACCCCCTAACCCGTACACTGCATACGCGTTGTGCTATATCTATAGCGGCGAGTCCG
          CGCCGGCGAAGGCAAACAAACTATCTCGTCCACCTGACGTTCATGCTTTCTTCACACTTA
          AGCCCCTGCTGTATACCCAAATCCACACACCGTCCAGATTTATTAGATATTCTGGTGTTG
          AGTGTCTGCTGAAGACCCAGATCCACACACCGTTTATATTTATTATAGATTATGATGCCG
          AACCCTGTTCAGTGGTAAAGATAAATCATCTACATCGGCGCCGCGAGATTTTAACAATCA
          CGTCTTTCCGAGGAGGTTGCGGTGATCACCCCCCCTCACCTAGCAGAGGATTTATAGCTG

          CGCTTGACGCTTCAGTTGGCATCTTAGCCGTCTTGCTAGTTGTCATTAAGCCCGCCCTTC
          GGTTCAACCCCGTAGAAGGCGCCTGTAGCTACATGATTAATGACACGTAGGCTCTTTGTA
          GTATCTATGCAGCGTCAAGCGTGCTAAGCTCCTCGGCGGCCATCAAGTTAGCGTTTACTC
          TGATTTCTAGCATAGAAGCTACATCGAAACACCCGGGTGATGTGCCCCTAGTTGCTGGCT
          GGAGCCATAGCACTCGACGTAACCAACTCCATTGGATAAAGGCTATCCCGCTGTCCTGCA
          GGGGTCATAGCAGACGAGGTAACCAACTTCATTGAATATAGATTATGCCGCCGCCCCATA
          GGCAGTGACATATTATAGGCCCCGTTAGTTTGTCACCGGAACTTACTGCCGATGTCTACG
          AGTTTGTCACCCCCCGGAGCGAGCAGGATTTTAAACCGAACATCATTGAAGTGTTTCATT

          AGTATTATCGTCACGGTGAAAGCGCAATACCGACACGTGATGCTTGGATCGTTAAGGATT
          AATATGACTTTCATCGCGGGGTCGTTTCGGTGATGCGACATAATTCGGTCACTGAAGGGG
          GTCATCAATGCTTCCACGAATTGGAGACCCAGTTATGCACCACTGATACGTATTCGACTT
          GATACGCCCGCTGCCGCTCATGCGCGAATGAGCCGCAGAACGTGTAACTGGGTGCAACAA
          AACACAAGCGCTCATGCCAATCTGTACTTCAGACCTGCGGTCTGTGGATTAGGCTGGACT
          AACTCAAGTGCCCATGCCACTATATAACCCAGACCTGCAGATTGTGATTTTGGCTGGACT
          AATACTAGCGTCCATGCGGGTACATCCCCCTGAAACACGGGGCAAGGCCCAAGCCTGCAG
          GATATAGGAGTCACCTTGCATTCATTCCAACGACATGTGATGCGGAGTCCCCCCCAGTGG

          ATAACTAAACGGAATACATTAACAGTATATTCGCGTAAGGCTGGTTTACAACTAGAAACA
          GTCAGGACACTGGATGACTTGCAACGTTAAGAGTAAAAGGTTCGGATCTTAGAGGACTTA
          CTAATGGTATACGCCCATCTGAAGTACTCCTCCCAGAGAAATGCCGGTTTATATCGGTTA
          AACATTAGTTTCGAAAAAGTAGAAGGCCTCTGGCGTAGTGGCGATTGAGCGTGCTCTCTC
          CAATTCTTCTTGATCGTACCTTCCCGACCTTCGGGGGATCGGTGCGACCTTCGCGTTGAC
          AAAACCTTCATGATCGCACGTTTCCGACTTTCTGGGGATTGGTGCGGATATCGCGCTAAC
          TCGACCAAGTGACATAAGTCGATTCCTTTGTGACAGGGTAGGTCAGGACCGCATTGTTCA
          TCGTTTTGTTTAACCGAGATGACCTGTCCACTCTTCGGTTACGGTGAGACCCGAATCACC

          TTCGTGTCCCAATGGGTCCCTGTGCGGAGATCGATTGAGCCACCAACTACTAGAGGTGTC
          TTCAGATCCTGCCTGCCTCCGACGTCGAAACTGCCTGAGACACCCGTGAGAGGAGATTCT
          TCGGCACTTATAACAGCTACAACGAAGGGCGTACAGGTTAACCTGGCATTAGGATATGAT
          CCCATATCTTCGGCAAAGTCTCTATAACCATCTGGGAGCCGATTACCACCTAGAAGTCTC
          AATAAACTCCGAACTTCTCCAGCGTAGAGTTTAGAGGAGGAACTGGGGTATGAAGTTATA
          AATGTACTCTGAGCTTCTCCAGCGTAGAGTTCAGCGGAGGGATAAGCGTATGAACGTACA
          AGATTAGACAAACACAGTCGGAGATAGTCCTCGAAAGTGGGGTCGGTGCGCTCATGCTTT
          TCCTGTGGTAAAACAATTTGGCCACGGGGCGCGACGGCTAAATAGGCGCACGGCTGGAAG

          CCTCAACATCCTCGAGCCTCGAGAGTCATTTCCTGGCAGCTTTTTAGTCTTCAGCCTATT
          CCCCAACGTGCTCGAGTCCGACAGGATGTAATTTGTCCACATTACTACACCCTTCTTACT
          ACTCTGGGGTCCGTGAACTCGCAATACGTATTCGGGGGGTATTCTGATTCACCCTCAGCG
          TACTGGCATTCACTGGAATTAAAGGACACTCTCAGTCAGACCTACTGTCCTGAGAATGAA
          TTTTTACGTCGAATGGGTTAGGAAAGCACAGCTAGTAAGTGCAAGTATTTTCTGAAGCTG
          TTTTTACGTCGAATGGGCAAGGAATGCACAGCCAGTAAGTGCAAGTACTTTATGGGGATG
          GACCCATGAAGCATGACCACGAGGTGAGTTTTTACCCCGCCATATTATAGGATAAAAGGT
          CGCGTCAACGATCTGGGGTCGGCGGCTATCGCGAGTCAACCACACAAGCCAGCACGAGCG

          ATGGAAAGTCCACAAACAGGACCTTGCCTACAAGCGTGTG
          TTGCTAATTCTAAAACGCAAGTCTTATCCACGCGAATATC
          TTGGTGACCTTTTCCCGGCAACAGGTGTCGCAAAAAGCCG
          CTGGTGCGGCCATCTTGACGACAGGCATTACGGACATGTC
          GCCATAAACACACTACAGGGATCAGAGATGATGAGACCCA
          ACCGTAAGTACACTACAGGGATCAGAGGTGATGGGACCCA
          AGTGCGAGTTGATATTAAGAATTACTTGAATGTACGGGTG
          CATGAAAACAATTGACAGAAACCCGTGACCATTAATGGCG

