 8 1000
t1        AACAGCTCGACAGACATCTGTTATAATGGTTTGTCCATTTGATCAGGCAGTCACATTATC
t2        AACAGCCCGACAGACATCTGATATAATGGCTTGTCTATTTGATCAGGCAGTCACAATATC
t3        AACAGCCCGACAGACATCTGGTATATTGGTTTGTCCGTTTGATCAGGCAGTCACTATATC
t4        AGTCGCTCGATAAATACCCGATATGTTGGCTAATATACCTGAGGGGGTAGCTACAACATT
t5        AAACATTCGCCGGGCGCGTGGTGTATTGGCTTACCCATCTGATCGAGTAGTCACAGCGTC
t6        TATCGTTCATACTATCAGTGGCACATTTAATCCATTGTGATATCAGGCAGCCACAAGCTC
t7        GACTAGTTGCCCCACGAGAGAGACCTTACTCCTAGTTCGAAGGAAGCGGACCCTCATTTT
t8        AATCAATCTAGAACTTGCTAGGCCTCCAACTGATATGGGGACTTACGTTATCAGTCTGGT

          GTGTGGTACAGTCGGCACCAGCATTTGTCTTCCTTCGAGAATAGTGAGGCTCCGAAGCCT
          GTGTGGTACAGTCGGTACCAGCATTTGTCTTCCTTCGAGAATAGTGAGACTCCGAAGCCT
          GTGTGCTACAGTCGATACCAGCATCCGTCCTCCTTCGAGCATAGTGAGACTCCGATGCCT
          ATACGCAACAGTCGGTGCTAGCGTTTGACTTCCCTCAAGCCGGACGCGTGCCTGAAGCCA
          ATATGCTACGATCAGAGCCAGCGTCTGTCCTCCTTTGAACCAAACGCATTGTCGAAGCCA
          AAAGACCATAAACACAGCCGCGACGTGAATGATGCTATCCCGGGTATGCTTTTAGCGTCG
          CTCGGCTGAGTTTTGACGCCCTATAAGTCCCTATTGAGGGAAGAGACAGACTTGTGTTCA
          TTCGGTGGGGGTTAAAAGCAGGCCATGTTACACTACTCGCTAGGAGGGGTGCTGACTGCA

          TAGGGCTACTACGAAACCGATCGAGGGTAATCAACGTCGCTGAAGGGTATGGCGAACCCG
          TAGGCCTACTACGAAGCCGATCGAGGGTGATCTACGTCGCTGATAGGTACGGCCAACCCA
          TAGGGTTACTACGAAGCTGATCGAGGGTAACCAACGCCGCTGAAGGGTATGGAGTACCTG
          AAAGACTCCTACGACGCTTGACTAGAGTAAGTAACGTTTCTACAAGGTAAGGCGGCCCCA
          AAAGCCTTTTACGAAGTCTGTAGCAGGCAAACAACGTTGCCGAAGGGTGAAGCAAACCCG
          AACGGTAACTCCAACGTGCATCGGCGGCTTTCGCGGCTGCTGCAAGGCTAGTCAGACTTG
          TATAATAATTCTAGTACCAAACATCGATCTCCATTCCCGCTAAAACATTGAACAGGTGTG
          TTACTAAGACAGAATGTTGCACAGTCTGAACCACAACGATTGATACTTGGAGGGTGTTGC

          GTCATGTGGTAGCTCGGGCCGAAATAGTCCAGGACAGGTGCAACACATCACTTTGTGTGG
          GTGATGTGATAGGTCGAGCCGAAATAGCCCAGGACAGGTGCAACACATCACCTTGTGTGG
          GTAATGGGCTAGCCCGGCCCGAAATAACCCAGAACGGGAGCAATACATCACCTTGTGTGG
          ACAATGGTATCGTTCGAGTTCTAATGGCTTACGACAAGTGTGGCACGTTTCACAACGTGG
          TCAAAGGGATTGCTCGAGTCGGAAGGGCTTAGCCCAGACGCTCTACATTTCATAATGTTG
          GCAGTGCGCTCTATTGCATTTGAGTGTCCCCTGATGGCCGCCCGATCCCCTATAGTGTAG
          AAAGCATGGCCGAATGACTTATAATAGCCAACGGCTGATGTAACGATTTTCAAGACGAAG
          ATGGTCGATTTTAATCTACTTCCGTAACGGTGGACGGACCTAATCATTGCTGCCCTATTG

          GCTATGCCACATCGGGGGTGGACCCCAGCTTTACGAAGACAAGAACGATACCCTCTACTG
          TCTATGCCACATCGAGGGTGGACCCCAGCTTTTCAAAGACGGGAAGGGTACCCTCTACTG
          GCTATGCCACATCGAGGGTAGACCACTGCTTAACATAGACAAGAAGGGTACCCTCTACTA
          CCTATCCTGGGTTCGGGGTAAACCAAAGTGTCATAGCGATGAGAGATATACCCTCTCTTG
          ATCATTCTTGATCGAGGTTAAACCAACGCCTCATAGAGACGAGACGGGCAGCCTCAACTG
          ACTGCCACGACTCGTAGGTTGGTTGAAGAGTGATAGAAATAAGAGTTACACCACCTTTTG
          ACCATCCCGATATCTAAGTCGTCTTATATGCTAAGAAGACACAAACAGTCAGACCCTCAA
          GCCAACTAGGTCTAGAGCTGAGTCGGACAACGGCTTATAATGGATGTATGATCCCAACCT

          CCGCTGACAAATGGGCTTCAGCATCGTTCACCGAGAGAAGATAAGTTAGCTGCTAGCTCG
          CTACTGACAAATGGGCTTCAGCATTGTTCACCGAGGGTAGGTAAGTTAGCTGCTAGCATG
          ATGCTGACAAGTGGGTTTTTGCATCGTTCACCGAGGGAAGGTAAGGTAGCTGCTAGCATG
          ATGCTGATGAGCGTATCCTTGAATCGCTCGTCGAGGAGAAGTGAGTTTTCTGCTGGTATA
          ATGCAGGAGAGGGGGTCTTTGTGTCACTCGTCGATGGGAGATGTGTTAGCTGTCGGCAAG
          ATGCCGACCAGCCATCTCTAGTGTCCTACGCGGAGTAGTGGCGTACCGGTCGGGAGATAG
          GAGTTGCATAAGGGTTCTTAAAGTATATTGCGACCTCGGGCCCCGTAAGGTAGCTGGATA
          CAACTCGATCGTGGTCACTACTGTAACCCACGCTACAAATATCATGATGTGGCCGGCAAA

          GTACGGCAACAGTGAAATCATGTGGTTACCGGGTCCAACCGGGCCCCGCGAAGAGAATCC
          GTACGGCAACAGTGAAATCATGTGGTTACCGGGTCTAACCGGTCCCCGCGAAGAGAACCT
          GTACAGCAACAGTCAAATCATGTGGTTACCGGGTCTAGCTGGTCCCCGAGAAGAGAACCT
          GTACGGTCGTAAGGGATCCAAATGATCGCGATGTTTGACCAGTTCTCATGACGGCATCTC
          CTACGGCAGCAGCAAAATCATGTGACCGCTATGTTTAACAGGCCGTCGTGAATAAAACCA
          GCACAATTGTACTCTATTAATGTGACCATCGCATTTGCTCAGTCATGGAGGGGCTGCTTC
          ACCATGGAGAGGCCGAATCATTCACTTCTAATAAGTATTCAGTGGTTTCAGCGTCAGCCG
          GGGTTGCGGCGGGTATTCCAATTGGATTAAGTATTGGCTGAGATGATCTCGGATCGGAAT

          ACTCCGCGCAAGACGACACGGGGCAAATCGCCCTACCTTCAATAACTGCGGGAATTTAAT
          ACTCCGCGCAAGACGACACGGGGCAAATCGCCCTACCCTCATTAACTGCGGGAATTTAAT
          ACTCCGCGCAAGACGATACGGGGCAAATCGCTCCACCTACATTAACTGCGGGAATTTTTT
          ACCCTAAGTAGGACGACACGAAGTTCACTGCTGAACCCTCGGAAGTTGCGGAAGTAGAAG
          ACCCTACGCGAGACGCCACGAAGCTAAAAGCTTTACACTCTAGAGCTGCGGGCATGAAAG
          CTGTGAATTCCGACGGTCCGGATAATTTTGGCTACTCATAGGCAAATTCGACGACGTAAG
          GTCGCTTCAAATGAGAGTAGGTTCGCCTAATTACACCCAATGAAGGGGTAATAAAGTGGC
          GGGGGGTCGAGGATGATTTGGTAGATACCGTAGCACTGAGGGAACGTCTAGCAGGGTTTA

          AGTCCTTATAAACCATCGGGACGGCGTATACATTGTAACGTACTGCGGGTGTTCTACGAG
          AGTCCCTATAAACCATTGAGACGCCGTATATATTGTGACGTACCACGGGTGTTCTACGAG
          AGTCCTCATAAACCATTGAGACGCCGTATACACTGCAACGTACTGCGGGCGTTCCACGAG
          AGGCCTTATAAATCGCCAAGACGTTGCACACACCGCGATGTCCTAAGGGTGTGCTACGGT
          ATGTCTCATAAATCGCGAGGGCGTTACACACAACGTGATGCACAATGGCTGCCCTACGAG
          AGAATTTCTAGATAACTTAGACGCACTATATGTTGGTCAGTTCCACTAATGCTTTGTGGC
          TGACCTTAGGCGTGAGCGACGAGCGTAGTACTATGCAGCACTCTGCAGACCTGGCGCATA
          GAGTCTAATAAACAGACCCCCGCTAAGCAGCCTTGTGGAACTTTAAGGGCACGCGATCAA

          TAGCCGCTACTAAAAATAACGAAGCATCTCCGGGTGGACCTACTAGCGTATCCGTTAAGG
          TAGCCGCTACTAAAAATAGCGAAGCATCTCCGGGTGGACCTACGAACGTATCCGTTAATG
          TAGTCGCTACTAAAAATAGCGAAGCCCATCCGGATGGACCAACTTGCGTATCGGTTAATG
          TCGTGGCTACTAAAAGTAACGAAACTGCTACAGAAGGACTTATGAGCGCATTCATTAATG
          TGGTGGCTACGAAAAATAGCGCAGATTCTACGGACGCACTTACAAGCGTGTCCGTTGACA
          TTGCGACCCTCGACCCCAACTAGATTTGTTCCAATTTGTCCTAGGAAGGTCCAGTTCTAA
          TGAACTTTATTTCATATAGTGGGGCTCCCACCACTTGCCTCGAATGTGAACGCGCTATAG
          ATAAGGCTGGTATCCTCTGTGACAATTGGCATGCCCTATTCGAGCGGGCAGTCGGCCCTA

          GTATTTTTATCAGGCTCAAAAACATCCTCAGTAGAACCAGATGCACACATCGCCGCAGGG
          GTATTCTTATCAGATGCAAAAACATCCCCAGTAGAATCAGATGCACACACCGCCGCAGGG
          GTATTTTTATCAGATGCTAACACATCTTCAGTAGAACCAGATGCACACATCGTCGCAGGG
          GTGTGTTGATTAGGTGCTAGAGTATTCTCTGCAGAATCAGGTTCATACATTGCCCCACGG
          GTATTTTTACCAGGTGCTATAATCTCTTGCGCAGGTTCAGGGGTACACGTCGCTGCAACG
          GTGATTCTGTTGAGTCTGGACCTAACTCCTGCGTCCTCAGGTGCTTGGAACGCCACATAG
          GCGACCCGTGCGTACAACATAGCTGCAGCAACCGGCCCACGCGCCGATCCCAGCTTGAAA
          TGGGGCCCTGCAGGATTAGTAGAAGTCAACGTGGAACTGACCATCTTTGGCAGTGAAGGA

          CGTAACCTGCTAGGCGTTTACCGTTGCCTCCGAACCTTTGCGTTCACACATTAGAGCGTG
          GGTGGCCCGTTAGGCGTTTACCGCTGCCTCCGCACCTTTGCGTTCACACATTAGAGCGTG
          GGTATCGCGCTAGGTGGTTATCGTTGCGTTCTCACCTTGGCGCTCACACAATAGAGCGTG
          CGTAATGCGATAGGCGTTTGTTACTGCCTCATTCCATCCGCGACCGCACACATGAGTGCT
          AGTAAGGCGCTAGGGGAACGTCTTTGTCTCATCCCCTCCGTGACTGCGCATTAGGGTGCT
          TTTGAAGAGCTAGAATTTGGTCTCGTCACTCTCTCATTTACGATTGCTCGTCCGGTCGCC
          TGGAAAGGGCCCAACCCTCAAGGCAGTCGATTGTTGACTGCAATTACCTATGCGACAGAC
          GGAAATGCGCGAAGCATTTACCAACGAAGCTCGTACGTCATTCCGGCGCAGCTGTTGCGA

          CCCGGAAGGGCAAACACCAAGAATACACACATGAGTCTAAGCCGTCTCCGAGTAATAGTG
          CCCGAAAGGCCAAACACCAAGAATACAAACATGAGTTTAACCCGCCTACGAGTAACAGTA
          CCCGGAAGGGCAAACACTAAGAATAGACGAAAGAGTTTATGCCGTATCCGAGTAATAGTG
          GATGAGAGGGTGGATGCCACGATTGGAACCGTGACCCTATACCATCTCCGAGATGCCCTG
          CACGAAAGGGCAGGTACGACTATTGGACTTATGACTTTCTGCGAGTTTCGAGCAAAAACG
          CTTAGAAAAGTTGCCCTCGCGGTAGGGGCTGTTCGTCTTCACCGTAAGTAGGACGCGCCC
          CCCCGAAGGGTGAAAGGTACCGCCAACCTCACCTCAATGCGCTGTGGCAGACCCGCGGAC
          TGACATAAGTTTGATGGAGCGTCCGGTCGCGTCGAGTCATGATGCAATACATTAGCGGCG

          CCACCCCCGACTAACCAGTCGTGTTTCTGCCGTCGTCGCCTCGGATCTCCACGACAAGCG
          CCACCCCCGGCTAACCAGTCGTGTTTCTGTCGTCCACGCCTCGGATTACCACGAGATGAG
          CCACCTGCGGCTAACCAGCCGTGTTTTTGTCGTCATCGCATCGGGCCTCCACGAGATGCG
          ACGCCCACGATGACCGAGTGGTGTTCCTATCGCCGTTTGGTCGGATCACCATTAGATGCG
          TTGCCTATCACTACCCAGCCGCGTTTCCGCCACCGCGTTGTCAGATCACTATGAGATGCT
          TCGTGCACGTCCACCCGGTTGTGCTCCCCATGTCGTGCCGATAGTTTGCGGCAGAAGGCG
          TCGCGCAAAGGAGAAATGGCATGTCTCCCTGATTATCGCACTAAGTCACGGTTTGCTGTC
          CCGCGAAACTTGATCCTCACACGGGCACCTTTTTGGGATCTCATCAACCGATGGGCCGGG

          CTAAGGCTATCTCCCCCCTCAGTCGCTGTGTTCCGGTTTGAGACGCCCATACGCTGCGAA
          CTAAGGCTGTCTCGCCCCTCAGGCTCTATAGTCCGGTTTGAGACGCCCATACGCTGCGGA
          CTAAGCCTATCTCGCCCTTCCGGCGCTACATTCTGGCTTAAGACGCCCTTATGCTGCGAA
          GTGGGCCCCTCACGCTCCTCGGGTGATGCACTATAGCTTGAGACGCCCATGCGCTCTGAA
          CTGAGTCTGTCACGCCCCTCAGTCGTTACACTGTGATCTGAGACGTCCATGAGTTGCAAA
          CCGGATTTACAAAGCATCTGCGTTTTCCCTCCAGATCTTCTGGTGCCTTTCAGCTGTCGT
          CCGGGAACGATCGCAGCCTTAGTCATTTCGACTAGAATTTCAAACATGTTCAGCTGTCCA
          ATCTGGTCGCAAAGATCGTGTGATTACCGAAAATGGCTCCAGTCTTTCTCATACCTAGAA

          TGCTACTGGATGATGTCTCCAGCTCATGACGAAATTTATTTAGTCGCGGTCGGCGCGGTT
          TGCTACTGGATGATGTCACCAGCTCGTGACGAAATCTATTTAGTCGCGGTCGGCGCGGTT
          TGCTACTGGATGACGCCACCAGCTCATGACGAAATCTATTTAGTCGAGGTCGGCGCGGTG
          TGCCACTGTTTTATATCAGTAGCCTATGACGAAATTTATCGAGTCGCGGTTAATGCGGTT
          TGCTGCTAATGCATATTAGTAAACAATGGTCAAGTCTATCGGGTCACGGCTGGCGCGGTT
          CGCTTCGAGGACACTTGTGTAGCTGGCGCCGAAATGTATCGGACGTTGAATTGCCCGTTT
          CGGAGCCGGAAACAAAAGGTCGAACGCGGCGCACACGCCCTGACACTGGCATGCATTCTC
          CAGCGTTGCCTATTGTCAGCAAAGGACCACCAATAGCGCCAAGTCGTTATCTCTATGACT

          TGTAACGAAAACGATTACATGTCACATGCGCGCTGGTAAT
          TGTAATGGAAACGATTACATGTCAGTTACGCGCTGGTAAT
          TGTCATGATAACGATTACATGTCTGTTGCGCGCTGGCAAT
          TGTACCAAACACGATCACACATTAACCAGGAGCTGGTGGT
          TGTACTGGACACGATTACCGGCTAGCTGTGCGCTGGTGAT
          ATTGCCTAACACTAACATGCCCCAGCTATATTCAAGGGAC
          CTAGATGAGCGGCATAACGCGATGGCTGCGCGCTGGGGCT
          CTCATCGTGTAGCGAAATGCACAATACGCGCCAGGGAATT

