 8 1000
t1        TCGTGCGTGTCAAGTTTTTATGTCATTGGCCTTATCTCGAGGAATACTCAACTTATAGGC
t2        TCCTGCATGCCAAGTTTTTATGTCATTGGCGCTATCTTGAGGAACACTCAACTTACAGGC
t3        AGATGTCTGTCATGTTAATAACCTGTACCTGTCGTTCCGGATAATGTTCAACCTCCCGGC
t4        TATTGTTCTTTACGTTGTCAACACGTCGCCGTCATCTCGAACAACATATGACCTCATGGC
t5        TTCCGGTTTCTGGGATGCCCGACTAAGTGGGCCACGAGGTAAAGAGTCGAGTCGGAGCGA
t6        CTACGTAACTGGGCTCGACCCGCCGGCCGGGCCTCGCCGTGAAGGCCGGATTAGGGACGA
t7        CTCTGACCCGGCATCAGACACGCTGAACCGGTCTCTTCGTAGAATGCCTCGTCGCGAAGG
t8        ATACGTGTTTGAACCAACAGCGCCGAACCGACCACGCCAGAAGAAACCTGATGGCAACGG

          GTTCTACCCTACATCACAAGCCGTGCTAGCTATAACAAGTCCTCTGAATCATTAAGAATG
          GTTGTACCCTACATTACAAGCGGCGCGAGTTCTAACAAATCCTCTAAGTCATTAAGAAAG
          AATACCCCGCACAACGCCGCCGGCCCGAGCTCTAACGCATTTTTTGTTTCATAAAGAAAT
          AATGCACCACACAACGAAGGAGATTCGAGCTCTAAAAGGTTTCTCGTCTCATAAATAGAC
          CCCCTATTGTATGGCAAGCGCGAGACTCACCGCACTCTGTAGCTTCCGATGACCACACGC
          GTCGCATGGCGTAGCGGGCATCAGATTGGGCATAATGCGAAAGTGTCAACTGTTTGAAGT
          CTCACACCGGTAACTCCACGTGCGGCTGGCTGTCCTGTACAGATTAAGTTATACAGGTAC
          CTGACGTCTCGCTCCCCACGTGTGGTTGGATGTCATAGAGTACTTTAGTCAACCAGTTGG

          AAAAAATGAATGCATGCGTGGGATCAGTTATTGCTAGCTTCAATCCGTATCTGCGCAAGG
          AAAAACTGAATGAATGCGTTGAATCGGTGATCGCTAGTCTCCATCCGTTTCAGCGCAAGG
          GAATACTCAACACACACGTCGAGCGAACGGACTCTCGCCTCGTCTCGTAACGACATACGG
          GCACATTGAGCGCACACATGAGGTGGGTGTTCACTCGTCCTGTCACGAGTTTCCGTATGG
          GAAAGATGCACCTTCGACTGGCAAGTCCGACCGATCGATTCACAGTGCCAATTTACGCTC
          GGATTAAGAGTCTTCACTTCAAGTTTTAGGACATATATTTCGCAACGTTTTACTGTACAA
          AACTTGCTAGACTCTCATCAGGAGTCTTACCTATTCACCTTACCACGTTTAGGTTCCCAG
          CAACTTCAAGGTGTTGATCGTCTGCTTTGCCTGTCTGACTTTCTCCGTTTATCTATTTAG

          CCACCATCTAAAGGAGGAGCATAACACGGCCTTGAACATCGAAATAACGCCCTACGTTCC
          CCAACTTCAAAAGGAGGATTATAACACGGCCTTGAACATCGATATAACGCCATACGTACC
          CGGACATCGAAGGATCGCTCAAGTCATCAGTGTAGGCATCCCAACGCCATTTCAAGCATC
          TGGACGCCGCAAGGTAGAGCACGTCATCAGCCTAAGCATTCCAGCGCGGATTTTTACTTC
          GAATTCTTAACACCGTGTCCCCACAGCCCCGCGAGCGTTCCCTAGGGTCGTATTAGGTGA
          AAGCACTCGATCATGTAACTTAACCGTATAACCAAGACTGTGACAGATGGTCCAAAGCGA
          GGGAAGTTAAATCTACGTATCCGCTGGCACGCTCTCGTTACATAATGAAGTCCCAATTGG
          GAGCAGTTAAATTTGTGCTTGAGTAATAATGTTAACATTCCAACGCGTCGTTCGGATCGG

          CGTCCGCGCAAGAGATCTATGATCTGTTGGCGCCTTCATCATTCCTAAGAGACATCCATG
          CGTCCGCGCAAGAGATCTATGATCTGTTAGCGCCTTCACTTTCCCTAAGAGCTATCCATG
          CAGTGGTGAAAGCGCATACGCACCAATTAGTCAATTCCTCTTGTCCGTGAAACATTGATA
          TCATGCTAAAAGTGCTTGATCACCGATTGACGATTTACCCCCGTCCGCGAAATGTTAATG
          GCGCTAAGAAAAGGGATTCTCGATAGACCCTGGACTCTCCGCATTTTTGAATCGGCTGAT
          TTATTGTCGAAGAATAATTTTGCTTGACTGCGAGTTTCCTTGACCTTAAGATTGGTCAAT
          CTAGAGCATAGTGACTGTCCTAGCGCAATTGGTGACTACTTTTCGCAGATATTGGACCAT
          TAAGAACGTGATACTTGTTCTAACAGCTTCCAGGCTTGCCGTTCCTCTGTATTGGTCCAC

          TTTCCTGGCCGCGGACTGTGAACAGTAAAATCGATCTGTCCTGGGTGGGCGATCGCTAGA
          TTTCCTGGCCGCGGACTGCGAACAGTATAATCGATCCGTTCTGGGTGGGCAGTTGCTAGA
          CCCCAATACTACTTGGTGTGAAAAATACCGCTTATATAGGCTGACTGTGCATTTCTCGAA
          TCCCAATACCGGTTGGCGTGAATAATTCTGTCTCTTTGAACCTGCTGTGCACTTGTTGTG
          CTCCTTTTGCTCCCCATCCTAGGGACGTAGTCAGACGGTCGTTCAACCGAGGGCGATAAT
          GCCATGCTATACCCCAAAATACGTAAGTAGCCCAAATGAGACTGCATCATGGCTAGGGAT
          CGACTGCTCTGCCCCGCATGGTGACCGTTGACTGTCTTTATTTGCATGGGAGTGGACTGT
          GGTATCCTCTATGTCGCATAACGAACGTTAATGAACGACTCTTAAGTAGGGGGCGACAGT

          TCCACACAATTATCTCAACCTGCGGTCTCAATATATCCGCTCTCCTAGTACGTCTCTTGT
          TCTACACAATACTCTTAGCCTGCGGTCCCAATCAATCCGCTCTACAACTACGTCTCTTGT
          CCCATACTCCCCACTCGCCTCGTAGTTTCAGGCGGTTTCTTCCACCGGTTCGTATCCTGC
          TCCTTACTATAAGCCCATTCCGTAGTTTCAGGCTATCTGCTCTACTAGTTTGTCCCTTGC
          GTCCTACAACAACTACGATGATCGGAGCCGGGCCTGCTGTCGAATGTGGATAAACTTAGT
          TTGATAAGGCGGCTAGGTTTGTTAAGGCGGAGTGTAGTGCGACAAGAGACTACTTCGGAT
          CGTTATCACCGGCCATGTGTTTCGGGTCAACAACCGGCGTCTCGCTAGATTGGCGGTTTT
          CTCACCCAACACCCAAGTATTTTGGGGTGTCATTTAGCGCCCAAAACGTCAGTTCGCAGT

          ATTGTGTTTACGAACCAGTGCCAGTCCCAGCAACCCTGGACGTTACAGTGTTTGAGATCG
          ATCGTGTTTCCGAGCCAGTGCCAGTCTCGGCAACCCTGGTCGTTACAGTGCTTGAGACTG
          GATACATGTCCGGGTAATAGACAGTTCCAAGAACTAAGACAGGAAAGGTAGCCGTGAAGA
          GATGCCTCTCTGGGTTACCGCCAGTCCCAGGAGTCATGGCAGGAGAGGTGGCTATTCCAG
          GAATTATCTCACGATAATTGCAAATCTCAGCAGGCCAACTGGGCGGTACAGCGGCCCACG
          GCGGTAATATATAGCCATTGCACACCCCCGTAGATTATCGGACTTACGCTACGGCCTATC
          GACGTGCCACGTAGCACCCACGCATTTCCGTAGCTTGTTTGGTTACCCTTATGCCCGGCG
          GAGGTACCCTGCCGCCACCGCCTTATCTTGCGGCATGACAGATTGCCTTTACCCCCAACG

          CTACGCCAAACCCCTGGATCAATACTAGAATGCGGCTGGGGAACACTCGATTTTGAATAC
          CTAAGCCAGACTCCTGGATCACTGCTGCAATGCGGCTGAGAAACGTTCTACTTTGAACAC
          CCAAACTTCACAATCGGATCCTTCGGATGCTAGGTTTGATGAGGTTATGGTGCTTGTAGA
          TCAAACTCCACTATTGGACCATTGGGCTACTAGGATTAAGGAGCACCTGATGTTCATTGC
          AGACGTTTCTGACTTTGATGGTAACGGCGTTCCATCACTGTGAAATTACAAGTAGGTTAA
          CGATGACCCTTGTCTTGACTCTCTCGGCGTTCTCTTCTTGGGGCACCTAAAGTTGATTAG
          CGACGTTCTCTGTTTGGATGTAATATACCACAATATGCTGGGACCCTCTAAGGTATTTGC
          GCTCGTTACCCGCATATAGATTTTAAGCGCTCTCGTCCTGGGGTGCACTGAGCTTGAGGA

          CGCTAGGATATAAGTTGCGTCGCTGTATCCGTTAACCGAAGAGAAGCGGTGCGACAATTA
          CGCTAAGACATAAGTTGCGTCACTGTATTTGTTAACCGAAAAAAAGCGGTGCGACAATTA
          CATCGCCCTAATCGGTCAATCACAGCGCCAGTTACCCTACTGGAGCCAACGGGATATTTA
          CGTAAACTTCAACGACAAACCACAGCGTCTTTTATTCTATTGGAGTGTACGGAATCACCA
          CGCATATTTACGTGGAGGCAATAATGGCATGTGAACAGATGCGTAAGCTGGGTCCCGTCT
          CAAATACCCCAGCAGGAGAGCTACTCGCCTACACGTCAACAGAGAAGTATAGTACTAACG
          TGCATAGATGATGACGTCTCGTCGAAGAGCGGGTACTGACACTAAGAGGTAAAAGCAATA
          TGCTTATTCGAATACACTTTTTCCGAGTCTGCTGGCTGGCCTGAAAAGGTGTAATCCTTC

          CCTTATACGGGCCTGCCTAATTGATTTTCAAAGTTGGCGTGAACCCCTAACTAGAGGCAG
          TCTTCGACGGGTCTGCCTAATTGAATTTCAAAGTTGGCCTGAACACCAAATTAGTGGAAG
          CCCCGGCAGGGCCTGCTTAACGTCTTCTCAAAATTACTTTGCCCGCTAAGTTAGCCTTAG
          TCCAGGAAAGATTTGTTGAGTGTTTTTCTGAAAGAACCTCACTAGTCTCATAAGGTTTAG
          TTTCGAGGAGGTCAACCAAGAATGGCCTAAGACATCATACTTGTCAGTAACAGCTAAAAA
          CTCTGGTAGGGCTAATTTAGGGTTATCAAAGACACTACGCACAAATCCGACAGCCGTACG
          CCCAGGTAGCGGCCCCTTCACAAACCTCAGAACACTATACACAATAGCAACGGGAGGAAG
          CTTCTGTAGAGGCCGTCTCGCCAACCCCAAGAACTCACATATGATATCGACGCGCGTGAT

          TCCAAGTGGCACTAATGACCGTCTGGTTTAACCCAGCTCAGCTTACCAGATCGGCCTACA
          CCCAAATGGCACTAATGACCGTCCCGTTTAACCCAGCTCAGCTTATCAGATAGGCCTACA
          TGCGAGACGCACTTGTGATCGCCCTAATTTGCGTAGCTCGGCTTTTTTTATCTACCTATA
          TGCGAGCCGCAGTTGTGGCCGTCCCAGTGTTCACGACTTGGCTCCCCAAGTAGACCTAAG
          TCCGGGAACCACAGATATTACCCGGAAGGTGCTTGCCCTCCTTGATTAGTGTGATACTCC
          CAGGAAACGCGGAGCGACTGCGTTGACGTTCTTGATTGTCGCTGGTTACAAAGATACTCA
          TGGGTAACGCATAAGAGCTGCCTGGCAACGCTTTACCCTCGACAGCTGGGGTGATAATTG
          TGGGGCGAGCACAAGTCCCATCCGGCTATCCTTTTTCTGCGCCAATTTAAGCGTCAATTG

          CTGTACCGTGAACGCGCAAAAGGAAGTCTCAGTTTACGGAATGAGAAAGAACACGCGTAA
          ATGTACCGTGAGCGCGCAAAAGGTAGTCTCAATTTACGGGATGAGATAGAACACGCGTAA
          TTACCGTGCCGGTGTGCATGTAATCATCATAGCTAAAGCGACGAGCTATAGAACATACCA
          CTGTTCTGTAGGTGCGCAGATGACTCTTTCAGTTCACGCGACAGGACACAGATCATACTA
          TATTCTTGCGTAGCTCAATCCGCTAGTTTTGGCCCAAGCTTACGAAAGGGAAGAATAAAA
          ACGAATGGCGTTGCCCCACGCGTTAGTTCCGACGACAGCTCACGAAAATAAGCAATATAG
          CAAGCCTTCGCATTATCAAATAAGAGACGCGTTTTATGTTGATGAGTAGAAGCGGTGAGA
          TGTGTCCGCGAAGCCCTACACGGTGATCTAGGTTGACACCGGCGAGCAGTTTACGCTCTC

          AAGGGTGGCGCGGATCTCACCTAATCCATGCCTGTAAACCTTACAGCGGGGCGTCTGTGT
          AAGGGTGGCGCGGATCTCACCTAAACCATGCCTGCAAACCATACAGACGGGCGCCTGGAT
          GAGGCCCCGGTTAGAGCATCATCCGTCATGCACGCGTGTGTTGCAAATGTGGTATTATCT
          GAGGCCTCCGTGAATGTACCCTACGTTATACTTGTGCGTGTTACAGATATGGCATCGTCT
          GAGTGAACCAGGAGAGTTGACTGTTCTGCAATATAGGGTGTAGAACTTATGCACCTGCTA
          GAGAGAGCCTAATATGTAAACCTCTGCTCACTATAGTGCGCCGCTCACATGTTATCGCCC
          GACGCATGCTAAAACACGGAATACACCGTAATGTTGTGTGCCTTATACTCGTATAGGCCC
          GGGGCAGTCTAAAATACGTATCGCAATGCACGGCTGTGTTTTGTGCAAGCGTACCTGCCC

          CGAACACTAGCCTCGCGAATATATCCCCGGACAGAATCTGTAAACGCGCTGTATGGACCT
          CGAACATTAGCCTCGCGAATAGATTCCCGGATAAAACCTGTCAGCGCGCTGTATGAACCC
          TATATACCTGGCTGGTAAATGGATCACTCTGCTCCACGTGGATTCCGGCTACTTAGGTTT
          TATACGCGCAACTTGCAAACAGACAACTTCGAACCATAAGAATCGGGGTTGCCTAAGTTC
          TGTATGTTGGAACTATGGACTGCTCATAGGGTCGTATCGTAACAAGAATTCCTCTATGCC
          AGCAACTCGGATTTACAGGTTGCGCGATGGGCCGACGCGTAATGCGTGCTCCGCAATGAT
          ATGACACTCGTCTCGCAGTCAGGACGAAGGCTCACGGCAAAGCTCTAATCACTCAGTGCT
          GTTACATCCACTTCGCAGGAGCCCCGAGGCCCCGCGCTAAAGTCCTAGCCACTAAGTGTT

          TAAATTACACGGGCTTAGGTGAGAACGGATTTGGATGCGTGTGTACGGCATAGGAGGAGT
          CATACTACACGAGCTTAGGCGAGAACGGATTTAGTTATGTGCGTTTGACATAGGCGGAGT
          TACCACATTACAGTACAGGGCAGGAGAAATTGGGGCGGATTTGAGCAACATAGTAGTAGC
          TACCCTATAAATACACCGGACAGAGGAGGGTCAGACGGATTTGACTAACATAGAGGCGCC
          AATTCCCTGTTCCCCCGTCTTAGCCAAGGCTTTATCTTGAGCGATAATCTACCAGGATAG
          AAATCTCCCTCTTCCCGCGTACGGCAGAATCCCATTTACAACGAGTATTTCCCATGTCAA
          CGTTCTCCCCGCACGAGTGTAGGCAAGGGCTTGATCTGGGACCAAAATGTCTCAAGTTGT
          TACCCTCCATCCCTGTGCGCAGGCAAGGGTTTGATCCTTATCTGACACTTCTCACGCGGC

          AGATCAGGGGCCGTCTCTCTTTCGGCTACCGGTGGGCCAA
          AGATCAGGGGCCGTCTCGTTTTCGACTACCAGTGGGCCAA
          GGTTGTACACAAGATACCCTGCGTACCTCCGGCGCGTTAA
          GGGCTAAGACAAGTCGCACTGTGCACCCCCGGTGCACTAT
          ATGTTTAGATTTAAAACGAAGTACACACCTAATCGGCGGA
          CCGCTCGGCACTGAAGCGAAGCACATTCAAGGTTTGTAGC
          ATAGTTGTGGGTGAGCCGAAATATCCGCTGATGTTGCCGA
          GAGCCTAAAGATGAAGTTGCATACCCACAGAGCTTGTCAA

