 8 1000
t1        TAGTTGTGATCACTACGTCTTACTATTGCTTATCTCGTCGGACCACAGCCGGGGTGCGTT
t2        GATTTGAGCCGCCTGCGTTTCAATATCGGTCTCCAGGACAGTCTCGGGATGGAGTAAGCG
t3        CAATCGAGACGTCCCAATCCTACTGGCGCCTCTCTCGCATACTCACAATGAGCATTTACT
t4        GGTTAGAGCCTTACTGAATTTTTATCTGTTTACTAAGTAACTCCCAAGCGGGCTATGATT
t5        AGTTTGAGAACCTCCGGTGAAACTGTCGATTACTACGAAGCCTCCTAGGTGATAGAGGAT
t6        GGCTACCGAAACTCTGCTGAAGGTGGCGACCATCATGAAGGCTCTTAGGAGGTTAACCCT
t7        GGTTGAACCGGCCGCCAATTACTCCACAAACGCAACGTCGCGGACTGCGAAGACCACCCG
t8        ACTGGATTCGGGCTAGAGTCACGTCATGATTAACAGCTTACTCATTGTAGAGACCATCTC

          CAGGAGTGTATTTCCTCACCTGATCTATTACTGTAAAGCATGACTGCACAAGTTGGTTCG
          CGAAAATAATCCCCCACAATTGATTCCTCAATGCAAGTTGCGGCAAGGCAAGCGTGCTAG
          GCAGGACGTCCTTCTGTACTTGAAAACTTCCCAAAAGTCTCACTTGGACTAACATGTTGG
          ATGAACCGTACCTTAGCCGCCATACCCCCCCCCCCGTTACAGTCAGGGCTAAAGCGAGGC
          GGGGCGAGTGCGTCCAGAATAGGATATCGTATTCTTAGTTTACTCGGCCTAGAGCGTACA
          AGGGAGAGTGCGTTTAAAGTACCTTTCATCACCCTATAGTTGGTCGGGTTAGAGCGACCA
          AGATATCGTTTAACGAGAATCGCACTCCCGGTTAGTGTCAAGGATAAAGCCGGACCCTCC
          GATAGGCCATCGATCTGAATCTCGCCCCCCGTTTTCATCTTGAGCGAGTCAGTGCGATTC

          AGTGACGCTTCTGTTTGAAGCTATAAGGAAAACTCTAAAATCTAAGCCAATCGCAGATGC
          AGAAGCGTCTTCTGTTAGAGGCTGACTGAACATTCTACCGACCTATCAATCAGTGGATGT
          GGTGGGATCCGGTGTTGAAGACAATACTAACAGTGCACTAATCTATACAATGGCGGAAGC
          CATGCAGGTCTTGGACGCGATTGACGCGTACTGAACATACACTTGGTCCACAGCCTCCTT
          CGTAAGGCTCGAACTCAAACGTTTCGCAGTTCTAGTTTCAACCCTTCGCGCAGTTGATCT
          CGCGGTGTGCTTATTTACAGGCTACGCCCTTTAATTACCACCTCCAAACACAGCAGACCC
          CCTGCGGGTTACGATAGTAGGCAAGCTGGGTGGAACCGCAAATCGACTCATAGAGTGGTC
          CGCGTAGCCTTTTGTTGAAAGAAACATTGATGGGAACCTACCCTAATTAACAATAGGAAT

          AGTTATTACTGACGTAGACTACTAATCGTACAAGCGATGCTGTTTAGCCCGGCCGGGTAG
          AAATATTCCAACCGTCGACAGATTGTCGTGACTATGATGCTCCTCAGCTCAATTGGGCTG
          ATCTGCCGTTGCCGCGGACGGGTTAAACCGCCAGTGGCGCGGCCTAGAACTATTGGACCT
          CATTTTTGCCCTTCCGGTTTGATCGCCTTGGTAATTGTCGCGCCTAGTGTTCCCGTGCCG
          AACCTCAGTGACCATGGATTATACACAATGAGCATTGTCTCAACCAGCCTCGGCGCGGTA
          GAATTCAATGACTCTGGATTGCAAGAAATCATTGTTGTGCAATTTAGCCCTGGCGGGATA
          CTGTGTAGGCGTTCATACTGGAGTCCAAGGGGAGATGTATCACGAGAGTGCGACTCGGGA
          TTGTACAAGCCCCCATTACGAAGAACTCTGCGGGCTGTATCGCGCGTGTATGCACGCAGG

          GTCCCTACGGCCATTTTCCTCAAATGAAAACCTGGAAGAGCGTGCAATGAGCCGAGTGTA
          GATTTACCGACTAATTCTCAGCTGAGCGCGTCCGGGTGATTAGGAGCTGAGCGGAGTGAA
          AATCCCGTGGGTAATTTTCGGTTATGAGTGCTCGGACGAGCGCGAACCGTACTAGACTTG
          AGTATAGCAAACGTGCGGCTGATCCTGGGATCCAACATAGTAAGGGCCTAGAGGTAACCG
          TATTTTTCACACAATAGTTGTCTGGGAGGTCCTAGTTACATCCCGAGCTACCGGGACTTG
          AACTAACCAAATGGTTCTTGTCTGAAGGGGCTTGGTGGTGCCCCGGGTAGCCAGGTGCCG
          GAAAATGGAAGCTTCACCCCCTTGTGTGAGAACGCCCGCTGCTGGTCGGGCTTAAACTCG
          GATATCGGCAAACACCACGCCCGACAGGAGAATGAATGCTTTAGGGTGGATCCCTGGTCC

          GACTCCTTGAGGTGGCCGTGTTCTCGATATGTTTCACAGGTGGCTCTCCAGTACGGGCGC
          GACTCAGGGAAGTGGTTCAGTTCTAGTCTCGATCCATAGCCGGTCTTCTGGTACGGAAAT
          GTCTACGCCAGGCGGTTATCCATCGGACAAGACCCTTAGGCCGCCTTGCAATACGGCTAC
          GTTCCCGGTGAGTGGTCACAGCCTCCGATGGCACTTAAGGCGGCTCAGACGTATGGGCGT
          GACTTATGAGGGTGGGAGTTGTTCCGACCAAAGTGGAAGTTGCCAGCCCCGCTAAGACGA
          GATACGGGAGGGAGTGTATCGCTTCGGCCAAAGAGGAAGTCGACAATTATGTAAGGATAT
          GATCGGATTTGTTATATACGCTCGAAACCAGATCGAGGGTTGATGGCTTAACAGAAATCA
          GATCGAAACTGCTGTGACTCCAGGTTGCAAGTACTCGAGCAGGCTTTTTAGCAGGCATTA

          GTTAATATAAACGCCCATTGCACTGACGTGTATCCGACTCTCGTACCTATTTAAATTCGC
          GCTCTAACCAATGTCTGGCGAAAATACGTGTGTCCGGGTATCATATTCTGCTCTACCTGA
          AAGTCTTTAGAAGTTTACTTTAACGCCATAAACTCAGGTCCTGTTCCCGCTCCATCAGAA
          GGCTTCATTGACGTATGCATAGTCCGTGAGAGTTACGACCTAGAGACGTATCTTATCCGA
          GACTCCCCTCAATTGCGTTCAATTAGGTTCCCTTTCGTCCTTTAGCGTACCGTGCTTCGA
          GACTCTCTTAAATTCCGTGCCATTATGCTACCCTCTACCATTTAGCACACTACGGTTCGA
          TGTTCTATTCGGGCTTGCCCATATACATGGATTCTCGCCATGGATTTCTCACTGGCTGGG
          AGTTTCATTGCAGAACGGCCACCTACATAGTCCCTCGCAATGGAAAGTCCGTCTCTCCGG

          AGTGCCATAGAAACGGAATATTTGAGTACACCTATACGACCTCAAGTCGGAACTGGTTTA
          CGAGACATAAGATCGGATCCTCTGAGTGTTTTCGTGGTACCTACGTTCGAAGTTGAATAA
          ATGACCACAGGCAGGGATCCCGAGAATCCGCTTATGGCATTTATGTTTTCAATTAACTGA
          TAGTTCACATTGACGCATCGCTGGAGAATGGCATTTCTACGCCTGATATATCCGCCCCGA
          TAATCCGTGGGGGGAGCCAGCATGAATGTGTCGTCACTAATCACAAACCGTTATCGTACC
          TACGCCGAAAGGAAAGCGCCTGGATACAACCCGCCATCAACAGCAAATCGCGATAGCACA
          CAAGGCAGCAATAGAGGTCTCGCCAAGGGATCGAAAGCATCTGTAATCCTTGCATGTGGT
          GGGTGCACCGATAGAGACTCCGACGACAAAGTGGAACCGTCTGCGCTTCTAACGCGCCGG

          ACAGTACACACGTTGTAGCGTCAAAAGGTTTCGTGCCAACGGTGGCCTTACCTACCTGCA
          AGAGCTTGTAGGCCGCTGCGTTGGCAAGTCGTGCGACCTACGTGGCTTAACCCATCAGGG
          GATTCAAATCCGTTTTGACGCCAAAGGGACATGCTGGTACCTTAGATCTAGTTCTTTCCG
          CGTGTCCGCCCAATATATTATCTGTAAGTACTACTCGACACACAGTTTGGTCTAGGTGTT
          AGGACTGACCCGGTGTGGTGCCCAGTTATTTCAGGTGCGACAACGTGTAGTCCACTTCTA
          AGAATTTCCCCGATGCGGCGTCTAGTTGTTCTATTCCCGACTGCATACGGTTTATTTCCA
          TCGGTTGCCTCAACGTTCTGGCTCACAGCTCCGCGCGCGTCACCGCTTGTGATTGATAAG
          GGTGTCGTCTCTGTGCCATGCCTTATGGTTCCTTGCGTGTCAGTGCCCTTTAGTGTCCAG

          AATAGTTCTGCTTCTGACGCAACCGTTTTTGGATCCCTGGTCTGAACAAGCGCGGATGAG
          AGGCGCCACGTCACCTCAATAAATTGATTTGGCACTTCGGTCCTACCTGCCTACGGCGAG
          AAAGGATGTGCCATACGCTCAGCCGTCTCTGGCCCCTTGGTTTCAATTCGCTCCGATATG
          ACAGGCTTAGCCGTGCACGATATTAGTCCTGGCCTCTAGCTACGATTAAGTTGAAACGGG
          AGCGAACGCATTATACGTACGAGCACTACCCAGAGAGTAGGTTTGCTTAGGGACGTCGCG
          AGCCGCTACATTACTAGAACGAGCACTCCCGAGGTCGCAGGTTTGCTTCGAGTTACAGAG
          GGCAGCGCTTTAAAATTAATCGTACCTCGCGGAAAATAGTTACTATCACCCCCAAAAACG
          GCGAAAGTTATGGAGTTCACCCTCGTTACCAGGTAATAGCAGTTGCACCCCCTCAAAATG

          TGCATGGTTAGCTTCAAGACGGGCATATACTGTGTCGCTGACTCTGCAAAGTGTTGATCA
          AACTTTACTAGTATCAACGTGGGCAAAAACGGTGTTCTTTGTTCTTAAGGCAGTCTCTGA
          AGCCCAGCTAGCTCTAAGACGTACCAATGGGGTGGGCTTTAGACTCCCGAATACCGATAG
          TACGGCAATCACGTCTGGACGGGACAAGAGGATAGCGGTCCCTTTCCCCTGTATTCCTCG
          CATTTCGTTAAGGAGATCACAGGGGCAGCAGTCCAGATTGGTAGCCCACACTTCAAATCA
          TGTTTCATTCGTTATATCACAGGAGCAGGCGTCCGGCTTGGTTACGCTTGTTTTAGATCG
          GTTGATTCCTCTGTTCTACCCTCGGTACACGTTGCCGTTTGTTCTCAAAAAATAAGGTCA
          ACTGATGCGAGGGCTTACCCCTTCGTGCGCAACGCCATTTGTCGCCTAGTGTCCAAACTA

          AGTCAAAGTTTGAGGGTAACGGTCCTGGGCATATAGAAATGGCTAACACTTCGTTTAGAA
          AGATGAAGTACGAGGGCAACGGTCCTGGACAATTAAATGACCAAAGTTTACATTACGGGA
          ATTCAATGCACGGGGGTTGTAAACCTGGCCGCCCAGAATTGCCAGTTATAGCGTAGAGGA
          ACCTGAGGCGCATGGACCGCGGCCGGGGGTGATCGGGGTATCCAGCCTACCCGCGTCCCG
          GGCAGGCAAATGGAACCCGTGGGACGCGTCCATCTAATACATTGGCAAGCCCGTAAGCGA
          GGCAGGCAAGCGTAGTCAAAGGGTCGGGCAAATCTAACACGTTGTACAGAACATAAAACA
          GTTAGATGAATCGGGGACACTCTAGGAGGAAATTTAATAAGGCTCTGTAATCTGATTCGG
          GTCAGATGGATCGAGGCCATGCCCAAAGGAAACTTGGTAAACTACTGTTTATCACTAATG

          GACAACCCGAATTTGGACGGATGGGTGTGTCCCGGTAACTAAGTGATGGAGCCGTATCCT
          GACTTCCCGTATTTGGGCGAATCGGTGTGTTCCGTCAATAACGTGATGAGGTTACGACCT
          GGTATTGCGTTCCGGAACGAGGCGCCGAGATCCGTCAACTAGATGATGGCTTGCTATCCG
          GACCTTTAACGCTTGGGTGGGCTAGGTCATGTCCTTTATGCCGTGATTTACTCATACTTG
          GAAAATCTGTTTTTGGACAGATTGGGGGATTGCGAAGTTCACGCATAGAGGTCTCGCACG
          GATAATCTACTTTTGAATGGATTGGGGGATTGCGTTACCTATGTGCGAGGATTTCGCACG
          ACTATTTCCCGTCGTAGCGGGCAGACTAGACCCTGGTGACACGAACTAACATAATCTTTG
          GCTATACTATTTTTGGGTGGGCAGGGCAGACCAAGAGGCGACGAATTAGTATGCTCTCTG

          TCGGTCATCAAATTCAACTTATGACCGGACCAACTCGGCTGTAGCTACATTTTGTGCTCG
          TAAGCAATATGAATTTGGTAGAGAATGGGTTACCGGCATTGTAGGCGCATATCTAACTAA
          TCCGGGACCTGTTACAGTGGGAGGATGAATTGGTCGTATCATAGTGATCTCGCCTATCAC
          CGTTTATACCGACCCGGCTACGTAAGTTACCGGTCGCGCCACTGCGACATTTTCAGCCTT
          TGGCACCTATGTTCAATGGATGCGCGAAGTCTTTCGCTTTAATGCGAGAGATTCTGTTAT
          AGCTAATTATGATCAAGAGACGGGGGAGGCTTTTTCAGCTATCGCACGCTATTTTATTAT
          CAATGGATACGATTTAGCGGGCGTCGGTTTCATTATCGGTACTACTGCCTGCATTAGATA
          TAGTTGGTACAACTTCGTGGTGGCCTACTTCATCCATCGAACGACCATTGGCGTTAACAT

          TTCCGTCTGTCCACGGCCCGTTCGATCATCACTCCTAGGTTACGCTCGCAGAATGCGACC
          TTGCCCACTCCGATGGCTTATGCGTCTCGAATTCTAAAGCTGTAGGGGTACGTGTCAACA
          CCAACGCTATTTATGTCATGCGTGTCCGGAGTGCTGAAATCATGCTACTACGCTGCGATC
          TCTCGGACTATAACGACCTACCTGCTCCAAATCCCAAGAGTGAGTTATTCCGTTCTGACC
          GCTACACCAATCTCAACCTGTTGGTATGGGTCTGACTAACGGCGTTCACTCGTCTTGCCT
          GCTATATAATGATTGGCTTGTCGGTCTCGGTCCTCCTAAGGGTTCCAGCATGTCTTGATT
          AAAGTTGATTCGTTATAATTTGATGCGGGCGGTCCACGGGTACTATTAATCTTCGCGACA
          ATGCTAGTCACGTTGTAATGTGAAGTGGGTGGTCTAAAAGTATTTCGGAATCACGTGCGC

          CATTCAAATATCCGATTACACCGAGAACCAGCCTTACGGTACGGTCTAGTGAGCTGGACT
          ACCAGAAACGTCCAATTCTGCCGCGTGAAGGCGCTCCGGGACTGCTAAAGCGTTAGGTTC
          TGTCGAAAGATACCGTCTCACAGACAGTGACCTTTGCGGGTCCGTCTAGTCAGCAGCACC
          GTGCGATTAACCCTGTTCGACAAGCTACAGATTTTGTAAAGAGGCCTGATTCTATGTGAG
          CCCCGAGCCACCCTATTCATGTATAAAAAAGCAACATGCAAGCGCCTCACCCTCAAAGTA
          TCCCGAAATACCCCGTTTTTGCGTAAAAAGACAATAAGTCTGACTGTGATTCCTAATATA
          CACCGTGGGCACTTTCCTTTGTTCGCGCAGAGCATAGGGGATCGCCTTATTTTCGTAATA
          CTCTCCCGTTATATTGCCCAGTTTACGAAAGTCATGTAGGTCCGGTATGCGATGACGCTC

          CTAACGATCCTGCATGGACACTGAGTTAAAATTTCTCACC
          CTGGCGATTTAACGTCGAGCCTGAGGAGACGCAATTACGC
          GTGGTGGTTACACATCGAGACAAGGACGACGTGACTTAGC
          CTCTTGGTCGGACAGACCAACAGCGAAGAAATACTTACGT
          CCATTAGCCGAGTGACGGAATTAAGGGAATAGCGTGGCGT
          TCACTACTCGAGCATCAACATCACGCGAATCGCGTGCCGT
          TTATCAGTTACGCCTTAACGTAAAGCTCACGTCGTCTCAT
          CCCTGCGTCCGGCCGTCCAGCCCAACTCATGACACCGCGA

