 8 1000
t1        TTTTGCTTTGTGGTACCAACAACTGGGTGGTGCTGTCGTCCTACGACGCAGGTTGAGACA
t2        TCCCATCTTATGGTTCCCATAACTGAGTGGTGCTATCGCTCTTCGCTTCAGGTTAAGTCA
t3        CCCCACTCTAAAATCCGAATATCAAAGTGGTACAGATGATCTATGGTTTAGGCAAAATCA
t4        TGTCATTGCATGGTGCTACCGACTGAATCACGTAAACGACTTGTGTTTTTAGAATCGCTA
t5        CCATATATGGCAGTGTTCACTTCTGAACCCCACAGGTAATCTCTGTTCCAGCCAGCACAG
t6        TCACATTCTTCTGTGGCCCCGTTATAATTCCTTAGCCAATTTCTACGCCGTTAAAGATCA
t7        CCACGACCGTCTCTGCCCCTCGTAGAAATTGGCAGTAGGGTATCTCCGCAGGCGATGGTA
t8        TACCCTCAGTCACACTCTATTACCACGATCATTGAATAATTTCGAACTTCCACATGATAA

          TACGTCTGGTTTAGCGGAAATTGAGGCACAATAGTGAGGTTTGAGAGCGAGGCCGTCCCG
          CCCACTTGGTTTAGCGGAAATCGAGATGCGATTGTGAAGCCTGGGAACAGAGCTATCATG
          TACGTCTGGTCCAGCGGCCATTTTGACATAATAGTGAAGTATGGGAATAGTGTCGCTCCG
          TCCGCCCGGTTTGACAGCAACCTTGGTACAGTGGTGAAGTCTCAGGACAGGACTGCCAAG
          ACTGCTAGGTACCGGGACTGCCTTGTCTGAATTCTAGAGTGACCGATTAGGGACGATTAG
          TTTACTAGGGCTAACCAGATCTTTAAAAAACCCATGGGAATTCAATATCAGGAGGCGTCG
          CGCCGCGCGTTAGGTCAAGGCGGTGAAGAAACCGAGTGACACGATTAATGATCTGCCCTC
          CGTGATAGGCTGGATATAATCTAAATGCCAGCCCAGAAGTCACCGCTTACGGTGGCTGCG

          ACTATACGATTGTTTACCTAGTTCTCCCCACTGTCAGATATCTGAAAAATGATCAAACTG
          ACTTCATGATTATTTGCCTTGTTCTCACCACCGGCCGATGTTTGAAGGACAGTAGGACTG
          AGTCGGTGCTGGTGTCTTTAGGCCTCACCACCGGCCGAAACCTGAGGGATGGTAGGACCA
          TAGGGGTAGTGATGTCAATAAATCTTGTCACCGAGTGATTAGTGAATGAGTGTGGGACTG
          GACTGATGGTGGTGCAGCTGATTTTCGCCATCGAAAGATACTCGAGTGACAATAGACCTA
          GGCCGATCAAGGTATTACCTTCACTCTGCTCTGGCCGCTACCGGATTTGTCACGAATGGT
          CGTTGGTGGCTATACAACTAGCTCCCCCACTTCTACCATACCCGGCCGGTCATTTAATCT
          TATCGTACCCGATGTGCAAGGAAAACGATCCTAGCTGACAGCTGGACGGTAATAGAGCAG

          TTGTGGACTATGTAGAGAAATGTACCGCTGGTGTGCTGGGATGGTATTATTTGCCAACAG
          ATGAGGAATTTGTATACGCATGTCCCGCTGGTGAACCTGGAACGTACCATTCGCTCACGT
          GTCAGCGCTATGTAGATAAATGCCCTGTCGGCGGATTGGGAATGCATTACATATACACAG
          GCGAGGCTTGTATAGAACTGTACCCCACGAGTGAACAGTGAAGGACACATTTATACTCAT
          GCGAAAATTGAGCAGACGACTAACTTTCTCGTGAACTGACGACGTAAGATCCATTTTCGA
          GACTGGTCAGCGTGCATATACAGCCCGCTGCCTAAACGAAGTCGTAGCGCTCATATCTAA
          ACGAATCTTGTGCAGGCGAAGATTAATTGTTTAAACGAGGGAATCATCTTTAGGATTTAC
          GTGGAATTGTGTACAACAAGCCACACTATTATAGGGCCCACATTTAAGCACTGCTCTGGC

          CCTTTCGCTGCGGCTTGGCGTATCTTTTTCATGGACTAGCGTATAAGTGATGAGGAAGTT
          CTTTTCACTCTGATTCAGCATACCCTTCTATTGGACCAGCGAGTAAGTGATGAAGAAGTT
          CCTCTCGCTTCGGCCCAGCGCGTCTTTATTGTGGATAAGCGTGCAAGCGACGGGGATGTC
          TTTCTATCCCCGCCCCAGCGTTTTTTTGTTGTGAAATAAGAAACCCGGGTCGCGAGTGCC
          CTCTTAGCCTTAACGCGGCGTATCACCGTTTTCAATTTGCCTGCTTAAGTCACGCTAGCC
          ATTACAGCCCTAGTCAAGTACGTCGTAGCTCTGCTAATTAAAGTCAGAACTGTGCCCGGC
          GATAAGGTTTAAGATATCGCTGCATCAATGTAGAATGAACGGTCCATAATCGTCGACGCC
          AGGTTTGTCTGACTCGAGAGGATTCTAATTCGAACCCGAACGCGACCCGTCCGAGGTCCG

          GGACTAGCGGGAAACAAACACAAACGTCTTCTTTGTGTAATCTATTAGAGGAGCTCTGAG
          GGCCTAGCAGGCAAGGGACATGGCCGTCATCCTCGCGGAATCTCTCCGAGGTGCTCTAGT
          GGTTCCGTAGGGATCATACATACATGTCATCTTCGCGTTAACTGCCTGACGAGCAAATGA
          AGCCTAGTAGTAGACACAAGGCTGCCTTTCCCCTGCGCAGCGCTTTTATAGAGGACTCCA
          AGTTCTGCAGCGGCCAGGCACGGTCCATTTGCATGTGTAACTTCTACCGGGGCGATCTGA
          AGTTGCGCGACCGCCACGTGCATGCGAGATCCTAGCGTCCCGTCCCGAGAGAGCGTCATG
          GTCTACGCTATAGACAGAGGATCGAACAACCGTTGTACCGGCGGAGCTGGGAGCGTCCCA
          GACGTAGTGGTATCCAACCACTTACTTCCGCGGTACCCTCTGATCGTGGAGAAGGTGTTT

          GCGTAATTGGGCATGGGGAACACTACCAGTGATTGCCGGAATTGTGCGGCGCATCCCAGT
          CCAATCCTGGATGTAGGGAGCGTTACTGACGATTGCTGGGATTATGCGACGCATCCTAGT
          CTACCTTCGGACAGGTGCAACGTTACTGCTGACTGACAGGGTGGTATAATGTATATCGGT
          GCATAATTAAAGACGCGACACAGTATAGCTACGTGCTAATATTGCGCGACCTATTCGAAA
          TTATATTTAGGAATGCCGGGCGGTATGACACCAAACTGGGGTAATGCGAACCATCTAGAA
          AGATCCGAGGAAGTGTAGATCGGTTCGATACAATGTTTGGATTGTGCGGGTCGTCCTAAA
          AAGCATTTCATCCTGTAGCTAAGTGGGATATAGAGACGGGTTCACATTTCTAATCGTGAC
          TCACGTTGTAGGACGCCGGGAAGTGCTGCCTATCAATGACCTTGTATGAGTGGGTCACGG

          ACAAAATGGGCAGCTTTAAATTAACCTGTTTGGGAAATGCTTCCGCTAGAGGGTTATGCC
          ACAAATCAGGCGACATTAGATCAGCCCGCTCGGGACATGCTTCTGATAGAGTGTTATAAC
          ACAAAACAGACGGCGCTAGGTTCGCCTGCTAGGGAAACGCTCGTTTCGGAGAGGTCTTCT
          CTGATGAAGCAGGTATGTGTCAAGCTAGACCCGGCCGGGTCTGGATAATGGAATAGGCTC
          CGGCAAAAGGCGAACTCACCTCTTCCATCTTGAGTTATATGCGAAGTGAGGGGCGACATC
          GTTAATGAGGTGCTATGAACATTTGTCGAAAACATCCTTTACGCATTTATGAATATCATC
          AGGCTCGGCCTTGCACTGGGCCTGTGATCTAATACGCCCTCAAATCCACGAATCGTTTCT
          AAAAGATGGGTACAAATTCCATACCATACGAGCAGTCCTCGAGCACCAAGGGCTCATGCA

          TGAGAGGGTCCTGAAATATCCTCATTTCCATTATCTTCGCACTCTTAAGCCCACGTGTCG
          GGAGAGAGTCCTAACATAGCCTCGATTCTGTCATCTCCATGTCCTTAAGCACGTGTCTTA
          AGAAAGAGTCCCGCAACCTCATTATATCTGTCATTCTCCCATATTTGAGAACATGTATCA
          CAGGGGGATTCTCCAAAGCTCTTGTTGGTGCATATTACTTGCCTTTGTGTTACTGTGTCA
          GGAGGGAATTTTCAATGTTGAGCGCTTCTTTAATACTCTCATCCTGGAACAATGATACCA
          ATGCCGCATTCCCGATAATGTAGGATAGCTCACTTCACAGAACTCCGGGCAACTTCATAT
          GGTAGGAGCTATCCAGCCGAATGTCCTGTGTGGGTCGTTCACCTTCGAGTAAGTGTTTTA
          ACCGATGACACTCCGAGACGTTGCAGGAGCAGAAACGCGGTGGGCATAAAAGGTGACCCA

          CGCGTGGTTTACACTTGTGAGACGTGAAAGTGGACCCCGTAACGGAGCATCATATTGTAT
          CGCGAGGAGTACACCTTTGAAACCTGAAAGTAGGGCCCGCTACAGAGCATCACACGATAC
          TGTGCCGCGGTTTCTTACCAGGTCAGTAAACGGGATAGGTTGCCGTAAATCCAACAGGAG
          TGCGCTGAAAATACTTTTTCGGCCCCTGACAGATATCTACCATTACACATCCCGCAGCGA
          CTTGCTGCAGATACTTCTGAGGGTAGAGAATGGTTCGCGCGGTCGAGGATACCGCAACGT
          ACGGAACAGTTAAATACTGGGGCCCTCCTGCGCACGTAGCCGACCAGATACTGCTCACGT
          ATATGTGTGCTGATTCTTGAGTGCAAAAGATTTTGACAACCGCTCTAACTTAGGTTTCGT
          ATCGCTTTATGAGTTGTAGAATACAAGAAAGTCTGATTGATTTTAAACTCTGAACCTAGC

          ATTGCTACGGGCTCGTGCGGCACCACTCTCACAACAACGTGACTAATACGTATGCCTTCG
          GCTGATACGGGCTCACGCCGCACTACCTTCACAACAATATGACTGACATGTGTCCCTTTG
          GACGGTATGTGTTCTCGACGGACTATCTTCACTACTACGTGACTAACGTATGTACAATCG
          CATGGTAAGGTCTTTACTCCCAAAATAGCTGCGACGATGCTAAACTTGTGTGCGGACACA
          GAAGGCGCGTATTCTCGACGTATGGTTCTAGCTAACATGTCAGCAGTCGGGGGTCTTTTT
          GAGCGCGGCCAAACTTGTAGTAGGATTGCGCTAGATATGCGGGTCACATATACCTCCTGG
          ACCCGAATCCATTTTCGGCGCTTACTCCTTTGACTCCTATGTAGGGTACAAACGCCTTCG
          GTACCCACAGAGGGTTGCCGTTTTCTCCTTCTCTCCGAGGAAGGTATATGGACCTGTTTA

          AAGTAAAAGCCTCATAGCCAGAGTGGCATCTTTGCGTGCACGGCGTTACCACTGTACCGC
          ATGCAAGAGCACTCTAGCCAGAGTGACAATTTTGCGTGCACGGAGCCACCACTGCACCGA
          GGGTGAAAGTCTTCTGATCAGAAAGACAGTTCCCTGCTAACGGGGCTACCCCTGTGCTGT
          GCATGAAGCTCCTCTAATCAGTACTGTGACTTGACTAATGTGAATCAACCACTACGGGTC
          GAGCGCAGGTATGCCACTCGGAAAGTTTGCTTCTCGAAATCGCGGTGGTTACCGCAACAT
          TAATAGACTAACCTGAACGAGGATGCAAGTCCGACAGGGCTGGAACTTATTGTGCAGACT
          AAGTGTTTGGATACGGCCCAAGAAGCAAAATGAGTGGATTCACGTATAGAAGCCAAAAGG
          TGTTGTAAGTTCTAGGAGCGTGAAACCAAATCTCCGGACTGGGCACCAGTAACATGGACA

          TTGAACTCGCCTCCACGCGCTGTATTTTAATTCTCCACGCGGTACGCGCTGCCTTTCGCG
          TCGGATACGTCTCCACACGTAGCCCCTTAATACACCATGTAGTACGCGCTACCTTTAATG
          TTGGACACGCACCCGCATGTAGCCTTTTAAGACCCCGCGGGGCCTACGCTGCGTTGAAAG
          TGGTATACGTTCACAAGCATAGCTGCGTAAGGCTTAGCCTGGCTCGTGCTGCGCTCTGAA
          CTTGATTAACCTTCACCCGTACTTTCCCAGGGATCAGCGCTGAACGGAACCGGGTTCGAA
          CCGGCCAGGCTCCCGCAGGTTGCTCACACAAGACATGCATACTCAAGCCCTCCTCCTGGA
          TTGTGCCAGCGTTATTTCACATACTGCCGAAATTATCTGACAGCTGCGTTGCTACATATA
          GGGGGGGTTTAATTGAACGTAGCCGGGATCGATTACTGGCTGCCCATCTCCTCAACAGTC

          GCCGCCATCACCCGGAGAGGGGTACTGGATGCGACTACAAACCTCTCATGAGTTAGTATT
          GTTGCTATAACTAGGAGAGGGGTATTGGGTACGACTACGAACCACTTATACCATTACTTT
          GCCGCCAAAAGCTGCTGGGGGGTCCCGGCCCCGGATCGCACGTGCCAATACCCCAGCTGT
          GCTGCCGTAGCCCGGCGACGGGTGTAGGCTCCGCCTTACCCCCGCCAGCATCCTAGTTTT
          ACCGCCGCTGCCTGTTGTCGGGTACTGCTTCCACCTTACCCCCACTCCATATATGGTCTC
          GCAGCGTAATGTCGATGTGTTGTGTGGTTACACTGCTCCGCCTAGGCCCACACGATTATC
          AATGCGCCGGCGTGCCGTGGGTTGCGACTTATACCGTCGATCCCTACATATCATAGCCCT
          ACCATCACAGTCGGGAGATGGGCCAAGTGTAGTATAGACACCTACTAGATTCCTATGAAA

          CTTTACGGAACCTGTAAATCAGTTTTTGAATCTCGAACGATCTAACTCGGAACCGGGCAC
          CTCTGCGGAGCCCCTATACCGATATACGAATCTCGAACCTCCTAAATCGGAACCGCACCC
          CTCTCTAGTGTCCCCCCGTATATCTTCAAACCTTGTAATTCCCAACCTGAAAACATGTTC
          CCCGTCGGCGCTCAAGGAGGAAGATATAATTTCTTACCGTCTTTAGGAGACGTCCCGCAA
          CTCCAGGTGTAAACCCCGAAAGTTCTTAACACAAACCATTCCCGCGCAGGTGCTTTGAAG
          TCCCCACGGGTCTACGCATACGCTACCAATTTATTTCGACTTAAAACCTTGACGACGAAA
          CGCCAAGGGATTCCAACGATAGACCCGACCGTTTTCCCACCCACTGTTTGCACTACCGAC
          CATTTGGATCTTCCCGAATAAAGGCCGATTCGCCGCACTCTCACACGCGGAGGCGATTGC

          GTGGTAAACATTTATGTCGGCCTGCTGTCCTGACCTTTAATTTTGCCTTCTATTTCGTTT
          GTGGTAAACGCTTATGCCATTCTGAAGTACTGACCTCTAATTTTGCCGTCTGTTTTGCTT
          ATGTTCACCGTTTAGGTCATTTTGAAGCGCCGGCTCTTCACCTTGTCTACTATCTCGCTT
          GTGTCTACCGTCCCGGGCGCCTCGCAGTTAAGGCTCCCACATGTGTAAGCCACCCCACTT
          AAGCCGTTAATTCAAGAAATTTCTAATTCTCGGCTTTTAATTTTACTAACCCCTATCGTT
          GTAATGACCAACTTATGCCTGCCGAACCCTCGGATTCTCCCTAAGCCATGCATCTCGGTA
          CCATTGGCTGATCACGCTTTGCCGCTAGACCTGGCGCTTCCCCTGAAGTCGATTCCCTTT
          GAGGCGATGCTCCTGGACCCAGTAACACCCTGGCCTTACACATCGTGAATAGGGTCATCA

          GCCTGGCTCTGAATCTCCGGCACTCCTATCGTAGTCTAAG
          GCCTGGCTCCGAACGCCCAGAACCCCTACCGGAGCGTAAG
          GTACGGATCTAGGGACCCGAAACTCTTCACGGAGCAAGGA
          GCGCCGTTCCGGGAGCCCAATAACCTCATAGCAGCGACGG
          ATTCCGCGTCTGAACCCAGCCTTACTCATTGAAACGTCAT
          GTACTACACTGAAAATTTGATGAGTTGCTAGGAGACTGGA
          GCTTCGTTGGAAGACCGAGTCACGATTATTGGTGTCCAAA
          GTACCTTGCCACGACTTTTCCTCTGTTGAGGAGTGTCGAC

