 8 1000
t1        GAGTGTTTCCAATCTACGGCGCAAAATTTTGAGTGTCGTTAGAAGAGCAGTCTACAAGGG
t2        GAGTGTATCTAACCTGCGGCGCAAAATCTCGAGTGTCGTTAGTAGAACGGTCCACAGGGG
t3        GAGTGCTTCCAATCTGCCGCGCAAAATCTCGTGTGTCGTTAGTAGAATGGTCTACAGAGG
t4        GGGCGTTTCCAATCTGCGGCGCAAAATCTCGAGCGCCTATAGTAGAATCGTCCACGAAGG
t5        GGGAATCTGCAAGCTGCAATGTAAAGACTCAGGTGGTGTTCAAAAGCAGGTGCATGGAGC
t6        CAGTACTGGCGGCGAGCGCTAGGATGGCCTGAACGTTGTTAATATCACGGAGCCTGAGAC
t7        AGTCCTACAAGAGTCAAAATGTCACATTTCGATTATCACCCATACTCAAACGTCGGACAG
t8        TAGCGTGCATAACTTAGGAGAAGGTCGCCTGTAAGTGGATTGTCAGTCGATAAATGGGGC

          GCTATGTACTGACCATCTTCCACGATCGAGTGGGATGTTAGCGCGGACATTCCCAGAGGG
          GTTATCTACGAATCATCATCCACGATCGAAAGGGCCTTTAGTGCGGATATTCCCAGAGTA
          GGTATGTACGAACTACCATCCCTGGTCGAAAGGGATTTTAGCGCGGATACACCCAGAAAG
          GCTACGGAAGAACCAGCACCCGCGGTCGAGAGGGATTCCAGTGCAGACATGCCCAGAAAG
          CCTATGCAAGGCCCTTAATTTATGGCCGTAGGGTATTCTAGGACAAACTTATTTAGAGTA
          TATGCGGTTGAGTCGCTAAAAACGACATCAAGGAGAGCCCAGGCAATGGTACTTCAAATA
          GTGAAGACGTGGGACCTGGCCACAGCGAATGGACTCACAGGTACGTGGGCCCCACAGGCC
          CTCCCAATGAAATACCCAGTTACAACGGTCGGGCAATACCACGCGGGCGCATGGTTGACA

          AACGGAGAGGGTGCAAAAGCTAGTCCGCCCCAACAGGAATCTGGTACGCCGCCTGAGGTC
          AATGGAGAGGGTGCAAAAGCTAGTAAGCCCCATTGGGAGATCGGTACGCCTCCTGGGGCC
          AACAGAGAGAGCGAAAAAGCTAATTAGCTCCAACGGGGGGTTAGTACGTTTTGTGGGGTC
          AACAGAGAGGGCGCACAAGCTAGATAGCCCCAACAGGCGATGGATAAGGCCCCTGGGGTT
          CCCACTGAGGGCAAAAAACGCTTCTAGTCCGACTGGGAGTGCTGGTGGACCCTTGGAGTC
          CGTTGAGGAGGCATATGAGGCGACAAACCTTGTCACGCGATTGTGATGTTCATGAAATCC
          GCTAAGGCAATAGGAAAGCGCGTCCCACTCTGGTGGGAGCCCGAATGCTTACCAAATGCG
          CTCATTGACTCACGTATATGCTATCAGTATTCGAGGATAACTTAAAAATACTGTGCAGAA

          CCACTCCGGTGGCGCCTGCGTTGGAGAACGGTAGAGTCGGTAGGTAAGTAACGCGTAGAC
          ACATTCCCGTGGAGCCTGCAATGGAGAATAGTAGACTCGGCCGGTAAGTGTCGCGACGAT
          ACACTCCGGTTGCGCGTGCAATGGAGTACAGTAGAGCCGGATGGTAAGTGTCGCGACGGC
          ACACTCCGGGGACGTCTGTAATGGAGAGCAGTAGATTTGGTATGTGACTGTAGCGACGAC
          GCAAACTAGTAGCATTGGAACCGGATGTTAGCGACATCGGTAGTCTAATATCGCGATTAA
          TTTCTCTGGAGATTCTTATTGCCCCGTAAAGAGCTGCATGGGTATCAGCTGTATGCAACG
          CTGGTGCCATGATCAGCGCCGGAGTACGTTGCACATCACGGATTGTCAAGCTACGATAAT
          CCAGACCTGTGGTTGTAGTTGGAATCCTCTACGATCCTCTCGTACTGACAGCAAGACCGT

          GCGGAATTCCTTAAATTGAAATCATGGGCCGACGCTACCTGTGTTCGTAACGTCAAACAG
          GCGAAAATCGTTAAGATGACGTCATGGAGCAACACTACCCGTGCTCGCGGAGCCGAAAAG
          GCGGTATTCCTCACATCAAAGTCATGGGCCAACGCCACCCATGTTCGCAGCGTCGAACGG
          ACGAAATTCCTCAAATTGAAGTTATGGGCCAACGTTGCTAGTGTTCGTAGCACCGCTTAG
          CCGAGATATTTAAAATGGAGGTTCCAGGTCCACGCTACACGTGCTCGGCGTATCCATCAG
          TTCAAACAATCTCACGAAAAAGCAGAGGTCACGCCTACCCACTTTCCTTAGATTTAGCAA
          CCTGGCCCTTCATGCTACCCGGCAGGGCACACAGCTTCCGGTAATGGCGAAGGCAAGTGA
          TCGAGGCGGTGACCATTTTTCCATCTGGGGTAAGCACGACGAAACACAGAACGTATCCGG

          TCAGGCCCTCTGCCGTGTGGATCGAAGTCCGTCCTTCCTATTCGCGGTGGTCACAATAAC
          TCGGGCTATTTGTCGTACGGACTGAAGACCGTCCTATCTATTCACTATCGTCACCTTTGC
          TAGGGCTATATGTCGTGCGGACTGAGGTCCGTCCTGCCTATCCGCGGTTGTCACGTTAAT
          TTGGGTTATTCGTCGTGCGGACTTAGGTCCTTCCTACCTAGTTGCGGTTGTCGCACAAAC
          GCCGCTTATTTGTCGCGGAGGCCTAGGCTAGTGATGCCATTTTATTCAAGCCCGCCCAAC
          CTATCCGTCCACTCGTATGACCGAATAACCGATAGGGTATCGTGTTCTTGTCGTTTGCAA
          TTTTTTCCCCCAGCGTCTGGTCGAGCCCTCGTGCGATTTTGCTCCGTAGGCACCTAGTGG
          TCGTCGATCAGGCTTCCCAATTGAACGTGGGCTCCTCCGACCTGCCAAAGCCGGGCAAGC

          AGATCGAAAGTGGTTAAAACTCTTGTCGCATGCACCTTCACCAGGGCTTAGGACAGCCAG
          GGATAGGAAGAGACTAAAATGCTTGTGGCAGGGCCGTTCACAAGGGCTTAGGGCGGATAG
          GGAAAGGAAGTGATTAAAACGCTTGTGGCATGGATTTTCACTAGGGCCTAGGGTCGCCAG
          AGGTACAAGGCCATTAACACGCTCAGGGCATGGACCTCCACTAGGGCCTAGGGCAGCCAG
          TGGTACAAAGTGACTAAAACTCCTGCAGGTTGTGGCGCAATTTGAGGTTGTTGCCCCCTG
          AAGCAGAGGATTTTTCAAGCCCTAGTACTATCTTATGTCATTTGGATACCCTCCGGCAAG
          GGTCAGTTAGTGCCAGAGATCAGCTAGATGGAAGGCAGACCCGTAAACCAGAGCAGTCCG
          TCCCGTTAGGTTCCATAAGTTCAGGAGGTGTGCTTTTTCATGAAAGAATAGAATTGTTCA

          TCGACCAGTTCAATGAACCCCCGGCAAAGAACATCACGGCGCCACATAGCGTTAAATTAA
          TCGACTAGTTGAATGGGCCCCAGGCAAAGGGCCCAATGGCGCCTTATAGCATTGAATAAA
          TCGACCAGTTGAACGAGCCTCTGGCAAAGGTCCTAATGGCGCTTCGTAGCATTAAGTAAA
          CACTCTAGTGAAATGAGCCCCAGGCAGAGGTCCTAACGGTGCCTTATAGCGTTAAGTAGT
          GAGAGTCGCTAATTGGCCCTCAGATAGGAGTATTAGCGGCTGTTTGAAGCGTTAAATAAA
          GGGTTTTGCCATACGGTCCCCAGATCGTAATCTGACCCTTGTAGAAAGAGACCATCAGGA
          CAGATCAGATATATGTTTAAGCGACTGCAATTGTGTTGCCCCATCCAGGCGTAACGCATC
          ACGGCTTGTCCACTGTTGTGCACACAGGCGCCCTAGAGGGGGCGCTGAGATCTGCGATGG

          TGCCTTTGAGGAGGAGTTACTAGGGGAACGGCGTTATTACCCGTGTGTAAGTATTCACTT
          CGTCTTAGAAAAGGAGTTAATAGAGGAACAGCGCTGCCACCCGTGTGTATACACTCACGT
          TGTATTAGAGAAGGAGTCACTAGCGGAATAGCGCTGACACCGGTGTGCAAACACTCGCTT
          TGTAGCGGATATGGTTTTACTAGAAGCACAGAGCTGTATCCCATGTGTAAACACTTAGTT
          AATACTAGCCGAAGAAGTACTAGAGCAATCGAGCCATAATCTGCTCGTACAGACATACTT
          TTCGTAATGCTGAGTTTTACTATATGGAGCCTGCGGAAAATCTGCTGTAAATCTATACAC
          AGTATTTTAATGGGACGGACTAAGAGAATGGATCTCGAATTCGCGTGATCAACAGGAGGA
          TCATCTTAAGCTTTAAGGAACAGAAGGGTTAGGTAAGTAACCGAATCACAGCAGCGAGCT

          CCAACAAACAGTCCAAATGAATGCGGTCAGACTGTCGACCATACTGAAACTCAAGATTAC
          CTAACGAAAAGCCCGGATGAACGCGGTTAGACTGATGACTATACTGGAAACTAATATCAC
          CCAACGAAAAGTTTGGACGAATATGGTTAGATTGATGCTTATGCTGGAACGTCATATCAC
          CCAACGAAAGGTCCGGATGAAAGTAATCAGACTGACGTCCATACTGGAACTTAATACCAC
          CAGATGTAAACTCCAAATAAATGCAGTGGATCCACCTAATGCACAGGGGCTCCTACATAC
          CCAATCTGGAAGACGGTCGCTTCGTTCCAGTCAGCCCGTTGTATAGCAATGCAAAGCTGC
          TTCGCGTGAGTCTTGACTTGGTACCACAGAGATATCTGACAAGTGGATACATTATTGGTA
          CCGACTTCGTTTACGAATGGACGAAGTTGTGCCTTTCTTTGAGACAGATTGAAAAGTCCT

          GCCCCGTTTACTTAGTGGCTATCTGACTCACGACTGAAGATGATGACATAGGACAAAAAA
          GCGACGATTTCTGTCTGGCTATTCGATCCACGACCGAAGATGATACTACAAGATGAAAAA
          GCCCCGATTTCTGAGTGGCTATTTGATCTACTACAGTAGATGGCGCCACAAGACAAAAAA
          ACCCCGATTTCTTAGTAGCTATTCGATTCACGGCCGAAGATAATGCCGCAAGACGAAAAG
          GTCTCGATCCCTAGACGGCTTCTCAGTTAATAGCCTAGGATCTCGTTACACGATGGACAG
          GGGTAGGTTCTTACGCAGGCTCTCATTTAACACCCCAGACTCTTGCCTAGTGCTAAGCCT
          ACTTAGGCGCCCCAGCACGCCGCATAGCGATAGTCGGGCTTGTCTTTCACACCATAGACT
          CTTCAACAACGCACTTGCTGTGTCTGACCAGAATCTATCGTTCTGCTCATGGTTGCACAA

          GGCTACTACTGAGAGGTACTTAAGCATTAGTTGAGGAACGACACAAGCCAATTCAGGTTT
          AGACACTACTGAGGCGAACTTAGACGTTCGCTGAGGAATGCCACAAACCCATTCACGTCT
          AGCTACTACTGAGAGGAACCTCGACATTCGTTGAGGAACGCCACAAGTTCCTTCATGTCT
          AGTCACTACCGAGAGGAGCTTAGATTTTCGCTGTGGTACGTCGCAAGGCCATCCGTGTTT
          GATTAATGTCCCGAGGAACATCGACATTCACTCTCGGATTACGTACATCCAATTTTACCG
          CCCTGTTACCTTAACGAAGGCCGCCCCCCTCTCTTGGTAGGAGCCTGCCCTGGAAAGTTC
          GCAATCCGCGGAGGCACATAACGCTGAGCATTATAGGGAATATTAAGGTCGCAAAGAATT
          CATCCTTGACATGACAAGCACTAGTAGTAACAGACGAATACGAGTCGTGCCGCTAGGCAG

          CATTGCCAAAACTACACGAGACATACACTCTGTGACTTATCGGGTACACGTTTGGTTCTC
          CACCGCCAAAATCACATGAGCTAGACATCCTACGACTTATCGGGCCCTCGCCTGGTTCCT
          CATTGGCAAAATCACACGAGCTAGACACCCTGCGACTTATTGGGCCCACGCCTGGTTCCC
          CACTGACAAGATCACACGGGCCAACCATCACACGACTTATGGGGCCCACGCCTGATTCCC
          TACTAGCCCAATTCCTCGGGCTAGACATCTCGCCACCAATGGTGATTGCCGTTGAATGAT
          GTCTGGGGGGGCTTGCCGTGAGAAATCGCCAGTAAATTGCGCCGCACGCATTTGGTTAAC
          TGCCTCCCACACGGCGCGGACGAGGCATTTTGTAATTCGCGCAGTTGATCTGGCCCCCTC
          AGCTGTAGCCACCCCGTCAAACTAACATCTAATAATACGTTACGATAACTCTGTCTCAAT

          AGCTTCCAGAACGCCAATTCATAGTTCTTTAAATCCGTCTATGATTGGGGCCAATCTCCC
          TGCTCCCTACGCGCGAGTTCATAGTTCTCTAAATCTGTTTACGATTGGGGCCAAGCTGTC
          GTCTTCCAGAACGCCCATTTACAGTTCTCCAAATCTGTTTACAATCGGGACCAAGCCGTC
          CGCTCACAGGGTTCTAACTTACAGTTCACCAATTCCATCCCCGATTGGGGTCAAGCTGTC
          TGTCTTAAACCTCTCATTTGGACGTCAGCTTGGAACGTCATTGGTCAGGGCCAAAATACC
          TGCCACGGCCTAGCCAACTGCGGATGAGTGCCGCGCGCTGTAGTTATAAGTTGAGCAAAT
          CACCCCTCGAAGGTCAATTGTTTCTACCAATGTCCAATTGCGTACGAACGTGCGGTACAC
          GATCACAAAACTACTAGGTGCTTGGCCCGCTTCCGCTCCCACACACACGAGCTGTCCAAC

          TGTGCGCTCTTATCGGTTTAAGGACTGTGGACGGGTGCCTGTGACGTGTTAACGTGTCGA
          TATGCGCTCCGATCGGTTTAGTGATTGTGAGCGGGTGTCTGTCCTATATGAACGTATCGA
          TGTGCGGTCAGACCGGTTCGCTGCCTGTGGACGGGCGTCTGTGCTGTACGGACGCGTTGA
          TGTGTGTTCCGATCGGCCCAATGACTGTGGCCGGGCATTTGTGCTGTATGAACGTATCGA
          TTCGCACGGCGATCAGGCCATCGATTGGGGTGGAGCTCTTGCAGGGCGTTTAAGTTCCGG
          TTTCAGCGTTGATTTGGTTATTACTACTGGGGGGAGACTTCCCGATCACAACCTATCTTC
          AGCTCACTTTGGATGAGTTAATAATCCTAGGCGCTGACTTCCCTGTTGTATGTACTAATT
          GACTCGATTAAGCGGGCAGTATAAGGGCCATCCCCATATACTGGCGTATACCCTTAAGGA

          CGGCAATAACCCCACAAGTCTCAGCGCTCTAACTCCCGATACGATGGCTGAGCTGGGCGT
          CGGCGCTACCCTTGCGGGTCTTAGCGCACTAGCTCTGGGTCCGGTGGCTGCGCTGGGTTT
          CGACACTACCCACGCAGGCATTACCGCTCTAATTCCGGGTTCGGTGGCTGGGCTAGGCGT
          CGGCACCGCCCTCAGATGTCAAAACGCTCTAATTCCGGGTCCGCCAGCTGCGCTGGGCGT
          TAAGGCGGTGATCGTAAATCGTGTTGTTTTTATCCTCAGCTCAGTGATCACCCTGGGCGT
          CTGAGTAGTGTCCGAATCTTTTGATGTTGCAGTAATCTGCACGGTAGTTTTGCCAGGCGT
          TTGAACAACAGCTGAGATAGGGACGGTGGTGACTTTTCCCTAAATTGACGAGTCTGCCAG
          CCAGCTGCCAGTATGACGGCAACGCGATGTAGCGTTTCGCCTAGAAATGACGGTTGGCCA

          TAATGAGTCCTCGCCGGTGTACATACCGCTACAATAAGAT
          TAATGAGTACTTGCAGGTGTTTATGCCGCTACAATAAGAT
          CAATGAAGCCTTGCAGGCCTTCATATACCTGCAACAAGAT
          TAATGAGCCTTCGCAGCTGGTCCTACCGGTACCATAACAT
          TAATCAGGACTCAGGTTGCCCCCTCCGGTTATTACGGGAT
          GGGTTACGACGCGGTAAAGCGATCGATGCTGCGGCAGGCC
          GGGTATTGGATGGTCAGGGCGCATCGACCTACTGGGAGTC
          TAGTGCGCGTGCGCGAGGACCTATGCTGATATCAACGCGG

