 8 1000
t1        GCATCAGAACATAAAAGGGCAGCAAGCCGGGGCGTACTCACCTTGATGCCCAGGGCCTGA
t2        GTATCAGGGCATAAGCGGGGAACAACTTGGTGCCGACTCACCTCAACACCCAGGGCCTGG
t3        GCACCAAAGCGTAAGAGGGCATTAAGCCGGGGCGGAGTTATCTCGGTACCCAGGACCTGG
t4        GGGACCGTTAATAAAGGGGTGTTGGGCAGTGGAGGATTCCCTCCGCTTCTTCGCGATGAA
t5        ATCTCGAGAAACTAGGGGGTAAAGGTCTCGGGTGGAAATACATAAACGTTACGATAGTAG
t6        GTCTCGGAGCGCCGGGGGAGCCTAACAAGAGTCTGTCTCACTCGATCATCTTGGGCGCGC
t7        CCTAGGGGTGCCGACTGAGAACAGTGCCTAAGTGGCTTTATGTCAGCGTCGGAGGTCTGG
t8        ACAGCAGTAATAACCGGTACAAGTGAGACATGTCGGTTCAGTCAGACGCGCTCAACGGTC

          AGCTACCTTCAGCCTCGTGGTGCAATATCTGTCAACGCGTCTATCATTTTGGGACTTCCC
          AACTCCCTACGGCGCTGTGGTATGATGTCTGTAAACGCGCACACCACTTTGGGACCTGCT
          AGCTTCGTTCATCCCTGTGGTGTGCTGTTTGTTAAACTGTGTTTCACTTTGGGGCCTAGT
          AGTTCTCTTCAGGCTCGTGGCGAACCTACCGTCAACTAGTCCAGTATAATAGGAACCATC
          AGTTCCGACCGGGCACCTAACGAACCGTTGCTTGGTGTCCGTAGCATTAGGAGATCTAAT
          TTCCTTTAACGGATCTGACCCGGACTGCTCGTAGTCGGGTGAAGCGTTTCCATACTCACA
          GCCCTAGACTGGCATTACGAAGCAGAAGCAGTGCTAATCCGGTGCCCTGAGGGGTGTATT
          GGTCCACTCCTTTGCCGTGGGGAGGTTAGCACAGGAACTCCCATTGTGTCCGGATAAGAA

          CTTGGCACCAGTATAGTCTGAACCCGACCCGGAAACTCGCTAGTGGAGAGAGGAGGGGCT
          CCTGGCTGCAGTATCGTTTGGACTCGAGATGGCAGCTAGTTAGTGTCCCGAGGTGGGGCT
          CTTGGCCCTAGTATAGTCCGGACTCAACGAGGAAACTAGTCAGTGGATAGAGGCGGGGCT
          AATAGTATACAGACTAATCACGTTCTAGACCGAAGGTTCTATGTGATTGAGGCCAGGACT
          CTTGATCTGGTACCGCTACATTATTGGAATGGAACACAATCCGTAATGTGAGGTAAGGTC
          GTTGGTCTGCGAAATTTCTACTCGCAGGCTAGGGAACTACTAGCCACAGGAGGAGGGGCA
          TTCGGCTCAGGTTCATATAGCCTTCAAGGCGGGCGGTGTCCCCTCACGAGCGATAATAAT
          GCCGGGCCGAGTTTGCCTCGTGGCTGAGACTGGGCGGCGCCGGTTATGAAAGTCAAGGAC

          CGGGACGCGATAAGCGTCCGCCATCGACTAGGAAATAAGCAAGTCGAAAGCGTTTCCAAT
          TGCTATGCGCCAAGCTTCCACTACCAACTGGGAAACAAGTGAGTAGTAGGCACTTATAAT
          TGGGATGCGTTTAGCGTCCGTCACGGATTGCGAAAGGAGCGCGCCAATAGTAATCAGAAT
          AGGCACGAGTCCGGTGGTCATTATTGACGATTGGAAAAATGTGTTAAGGCGTATCACGAA
          CAATATGCCTCAGAGCTCGGATTCCGATTATCGGATGCCCGGGTCGTTATGATTTATGAT
          TTCAAGATAATAGGCGCCTGCTACCCGCTATGGGCCTCGTAAGTCGTAGGATTAACTAAT
          CGAAGAACTTCAAGTTATTACTGTCGAACACGGGAGTCGCGCGGCGAGTGATTTCGCTAT
          AGTGCCGTGCTCGGATAACCCGATGGAGCATAGGCCCTCCGTAGGGCCGGGGCCCCCAAC

          TCGTAGGTAATTGGTAGTCCTTCTCTATCGTGGTTTGGGCAGTCGACCAACGTAGGATGA
          TCGAGGATAATTGGTAGTGCTTAAATATCTAAGTTCGGGCTGTCGTAGAGGATAAGACGA
          TCGTGGGAAATCAGTAGTACTTGTCTCCCTAGGTTCGGGCATTCGCAGAGCAAAGTATGA
          CTGACGACGATTAGGAATCCCATTCTACCTGGGTTTGGGCATGCCCAAAAGATTCAATGT
          CCGTGGGGGATTGAGAATATCCGTCTGCCTGTGCTGGGGCGGGTGCGTAAGATGTGATAA
          TTGTGGGGGATCGCTAGCCATCGTCAGCTTATGTCCTAACAACTAAAGGGAATATTGCGA
          TTGTAACGATATGAGAGTTTCCACCAGTTTAAGCTACTGCAATTGTGGAGGACTGGATGA
          CCGCGCGGTACATTAGAATTATAGCTGCCTATGGACAGCCGGTTACCGGGCGTGACAGGA

          ATACTGGAAGGAACGTGGTCGGTAAGCTATAACGGGAATCAGAAGTCGATCCTTGGCCCA
          ATATCGGAGGAATCGTGGATGCCAAGAGGGACCGGGAATTAGAAGTCGAATTACGGCTTA
          TCATTGGAGGGAACGTGGGCGCTAGGCACTTACGGAAATCAGAAGTTGAGTTTTGGCCTG
          AACTTGGGTGGAGTGTTCGCGATACAAATTAATGGGAGCCTTTTGTTCAGTCCTGGCTTA
          ACGTCGTGCGAAACGTGGGGGCTGGATAAAAAAGGGAATCGGCGGTTTATCTTCAGTTAT
          ACCGTAAACAGAGCCCGGACATACTGTGACGGAGCGCGGCACAACTTAAGTCTTCGTTGA
          ACCAAAACTAAATTGCGGATGGCACAAAAAAAAGAGAATTAATTACTGGGCTCGGGTTAG
          ACTTTAACAGGAGGGCAACCATAATGTCGAAAGAGACGCTACTCGTGAATCTGCCACTAG

          TAGTCTTAGAATTCATTACAACCGCTGGGGGCGAGCCCATACCTTTGTGGCCAATATAAC
          CAGTCTTAGAATCAACTAATACTGCAGCTGGCGGGCTCACCTCTCTGTGGCGGAAATAAT
          CAGTTTTAGATTCCACCAACACCGCTTGAGGCAGGCCAACCCCCCTGTAGCTAAAATAAC
          AGGTACTGGGTTGGACCACTTCGGTTATTGGCAGGTTCAACCTCCAGTGGCCAGAATGAT
          TGCCCTTGGGCTCCACCACCACATATCGCGGCTGTACCGAACATCGATGTCTGGAGTAGT
          TGGTTGTCGGGTTCATTCTCTGGTGTTGCAGTAGCTTTATACTCGATCGTCCAGGATAAT
          TCATCCCCGGCTAATTCCATGCATACGGAAACGCCTTCGCTAGGCAGCTCTCGGACTGGT
          TTCTTCACGGTGTCGTTCACGCGGGCGCATTGACTTTAGAACCATAGTATGGGGTGCGAA

          CTTTTGTTGTAGGGGTGCTCTCGTCCTGTCTACTATCCGTCCGGACCGCTCCCGTTTGAA
          ATCTAGCTGGAGGGGTATTCCCATCCTGTTATCTATCTGCTCGGGCCCCTCCCGTTAGTA
          ACCCTGCCGCAGAGGTGCTTCGATCTTGATTCCTATTCGCTCGGACCTCGCTTGCTTGTG
          GTTCGACGAGCTGGTTGTTTCGGGGCTGCCTCCTTTTCACTCGGACTCCTCATGTTTTTA
          GCTTCGTAACGCAGATGTTATAGACATGTTATCCCGTTTCTCTATCTCTATCCTTTTGTA
          CTCGGGATATACGGCTTCTCCGGATGGGTTCCTATATTGCTTTAACTTTGCTCCTCTCTC
          TACCAACTACCTCGCCGTTGCGGATGAGGTTACGCTCGGCCTTCGCTCCCAAATCTACCC
          GCCCGAATTTATTACAATCTTCAGGGTCTTGCCACCCAGTGACACGATTTACGGGCCCAA

          ACCGATTTAATAACTGTCAGAGGCACTGGGGGGTTAGAGGGGGTAATGCGCGCTCCCCTT
          ATCGATTTAATAATTGTCTGAGACACTGGGGGAACGGAGAGGGTACTGCGCACTCTCTTC
          GGCGATTTACCAACAGACGGGGACACCTAGGGGTTGGAGGGAGTCCTGCAGGTTCTCGCT
          TCTGGTGTGACCCCTTATTGGGACACATGGGGTGGCGAGGCTTTTCCTGTTGGTATTATC
          CACATGGTAGCTACTTGTCGGTGTATCTGGACTGTCGAGGAAGGGCCGTTCACTCTCTAC
          GGTGATTCCGCGAACGCTTAAGATGCTTACATCATAGGGATGCCAATGCTATATCTCTTA
          ATGGCCTCCGTCATGAACAACATCGGGTGCGAGAGTGAGGGCCTAGAAGCCCGTTGGTAG
          GCGGACACAACTGGGCTGCTCAAGACTTGTGGCATGACTACGGATGAGCTGGGCCTTCCA

          TCAAACCAGAACTGATTGATCCCCCCAGGCCAACGATTTTCCTCTACCCGAGTGCATTTA
          TCGAACTTGAACTGCCTCATCACTACCACTTGATCGTCCTATACGCCCCCCGTGCATTAA
          TTGCACCTGAGCTGCTCGCCCCCTGCAAGCCATTTACGTTTAACTAACCCCGTGCATACG
          TCTCACTCCAAAATCTCTCTCTCTGTGGGCAGCTGCACCACTACTGGCGTTGTGCGTGTA
          TCCACTTTGAGTTGTTAGCCCTTAGCGTAAAAATAAACCCAGTGAGCGACCGAGAATGGC
          TCTCATCCAAGCTACGGTTCTGCAGCGTCGACATCAGGCGGAATCAACACCAAGCCACTG
          GCTCTTCCCAGCTGTCCTTCTCCTGCGTACGCAGTAATTGCTAGTGCCTCCGTTTGCAAA
          GCTTCCATCGACATCTGATCGTCGACGTACAGAACATTTGTAATATCAAGTACGTTACTA

          ATAAGACCGCATAATCGAAGGTGGACCTTTGTTAATCCGCGTGGCTACTAGCCACACCAC
          ACAGTACTGGGCAATCAAAGGCGGATCTTTGTTAATTTGCATGACAACTAGCTGCACTAC
          CCAATACGGCATAATCGTAGGGGTACACTTGTCAGTCTGCGTGACTACTAATGACAGTAT
          ATAGAGCCGCTTATGCTGGCGCACTTCCTTGTTGTTAAGCAGGAATACTTGTTTAGTCAC
          ACCGGGTAACACGACTCATGACGCTCCCACACCGACAAGCGTGGCTACTTGTCGTAATAC
          ACTAGTCTGCATGGCATTTATTATACGTCTGTCGAAGAAAATATTAAGATGTCTCATTTC
          ATAAACTGGAGATATTTAGGGAATTCACACACAACTAAGGAAACCAACTTGGCACGTCCC
          ATACTCCCGAACGTCCTTATGGCCTGTTCCGTCGGCTGGAGGGGTTAACTACCTCCCGAC

          TCCTATGGATATGAACCCCACTAAGGATGACTATTAGACCATTGAGGGATTCCAGTGAAG
          CCCTCTGGATATGCGCCCTACTACGGATGACCTCTAGACGATTGAGGTGGTCCGGTGAAG
          TCCCATAGACGTGTGCCCTACTACGGATGCCATTCAGACGGTAGCGGAAATCGAGTGAAG
          TAGCGCGGGTAACAGGCATACAGCAGACCCTTCGCGATTGGCGGAGTAAAAGAATCAAAG
          CACGACGAATAATTAATTTGCCACCTATAATGCGCCAACGCCAGAATAGCATGGATATCG
          TCCTCCGGTTAAGTAATCAATTGCTGTAAAAACGGAATTGGAGAAGCCGATGGAATGGGG
          GGTTGAGGCCGTTCTGCTGGCCACTTGTGATATGTAAGCCTCTTCGCAACTAGGTAGAAT
          TGCGCAGAATGGCCAGATCTAACCAAACAATACAAAGAGAAAGGGTCATGCGTCTTGAGT

          TTTACTGCCTTAGACGCTTATGGATTCAGTAGCTATTCTCGCAGCGATTGCAATCTTCTT
          TCCGTTGGCTGAAACGCCTACCGAAACAGCAGTTATTCTCAACGTAATAGAAACATCCTT
          CTTACTGACAGAGACTTCCACGGATACAGCAGCTATTCCCACCGCGGCCGTTACACTCTT
          TCCGCTGGTTGAGACGCCCACAAATTCATTCAGTACCTCGTCCGGCACTATAAGGTCTCT
          GTCGATGGAATAAATTTAGAAGTGGTCGATCATGCCTCCGGTCAAAACCATACAGTTCGC
          TTGGCCAACCCGAAACCAAGAATTCCATCAAGACGCCACGGTCGAAGATGTAGTGTCTCA
          CTTTTCGCGCGGTCCGAAAAAAGAAGCGAGCTGCGCCTCTGTCATCGTCGACAGGCTTCC
          ACATAGGATTGACTATAAACTGTATGGGCGCAGTACCAGGGACTTGTCCAACTCAATCGA

          AATACAGGCTGATGATTCTCGGTCGTCGCAAGCGGTTTAACTAAAAATGATGCCTTCCAA
          ATTACCGGCTGCTAATTCCCCGGAGCCGCAATCAGTTCGACTACCAGTAATGCCCCTAAC
          AGTTAATGCTGATAATTCTCGGTCGCGGTAATCGGTTTGATTACACACAACGCCATTAAG
          CGGGAGAGTTGTAGTGTTTTGGTGGGCACAACAATTATGCATCAACACAACGGTTAAAAC
          CGGCAAGTTACGACCTGCGTGGCGACTGCGACTGTCATGATCACTCATCAGTTCCGAAAT
          AGGCAGGCATGAGGTTTTTCGGTGGTCGTGTTCGCCATGTAGGTAAGTATCGTTCTTTAC
          AGGCTGGGGCAGAAAGTTTCCTGAGTCGAGTTTGTCATGCCCGCGCTCCTTGTAGGAATA
          GACCAGAGGCAGGATTCGAGTTTATTCGTGGCTCTTCGGTATAGTCACTGTACCCGAGAG

          CCCGTGGGACTAGGGAAATCCCTGGGAGCGTTGGTTGTTTCGGGTCGCGTCGCTACGACG
          ACCGCCGTAATAGGCAAGTGCCTGGAAACGGGAGCTTTTCCCGAACGCGTCGTGACGATG
          ACCCTGTGATTAAGCAAGTCCCTCGAAGCGAGGGTTGTTTCGAATCGAGTCTCGACGGTG
          CACCCAGAGTACCCTGCCCCTCTGGAACTCAGGGCTGTTCCAACGCGTGGAGCCACGATG
          TAGCTTAGTTCAAGCACCCCTTTGTGGGCGGTTGGCGTTTCAAGTGTTGGCGTGTCGCTG
          CTCCGGATTTTAACTACTTTATTGTACACATCGGCTGTTCCTGATGGTGTCGGGTTCAAG
          TACGTTAGACACGATCCCGTTTTCAGAGCGGTAGTGTTGCAGAATTATGTAAAGACAAGC
          CTCGGTCGTTCTTCCTCCTCGTTGGGCGACGGGTTAGCTTGGCATACTGTCCTGAGAAAG

          GTTATTATTGAACTCATCTGAGCGAGTTTGGAGTTGGAACACCGCGCTTTAAATTTCCCC
          GTTATTACTGCTCCCACCTGGATTAGCTTCAGATTGGACTCTGGCACCTTCAGTTCCCCT
          GTTGTCACTATACCCAACTGGAAGAGTTTCGGGTTGGAACACCGCACTTTCAATCTCCCC
          GCTATCCTACCGTTCGCCGCACTAATCAGAGGAAGATTGCGTTATAACTCTGGCCCCGGA
          ACTGCTTGCGCTCTCGGCGGAATGAGCCCAGGGTTGGGATTCGACGTCTCATTCTGCTTG
          GCTACCGTGTAGTGAACCGCGACGATTCAGAGGCTGAAACTAGACCCCCTGTTAATCTTG
          ATTAATGTTATGTATTCCGGACTCCGTCAAGGATTCCAACACCGTTTTAAAATAGATCTT
          ATTATCATGAGGATTGCCGAGAGAAGCTGTAGTTTTTCACGTGGCCGTCTATGCAAATCC

          CTTGAACCAGCGGTACACCCCTTGAAACATGCTGTTCTTG
          CTTGACTCAGCTACGTACCCATAGGGACATGCTGATCTGT
          CTTGAGTACGCTATCCACCCCCAACAACTTGCCTATCCTA
          CCTGTCCACGTAGCCCCCTATTATGAGAGTGACGCTCTAC
          TCCGACGCAGCTATGTTCCTCTGAGCCTACGGCAATCTAG
          TCCGAAGTCGCGACGATCTATCCGGGCCAGAATATTCCGG
          TATGGCTAAGTTTCCGACAGGCAAGATCGGTCCGCTATTC
          CTCGTTTTGATGCCCGGCTATTACGTATATGGTGCCACGA

