 8 1000
t1        CTACAACTTTACTCTGCGTGAACCCAAAGTACCTTCTGCGACGGATTGATCTCAAGGTAT
t2        CTACAACTTTATTTTGCGTGAACTGCTAAGGCCTGCCGCGGCTGGATGTTCATCAGGTCC
t3        CAACGGCTCTTTAACACAGAAATCGGGCGGGCTTGTCGGCGCTGTAATGTTTTTAGGACT
t4        CAGTATTTAAAGTTCACGTGGACTGAGTAGACCCGGAGCAGTGAAATTAGTGTCGAGAGG
t5        AACCAACGCCCTCCTGCGCGGGTAGCGGTGGTCGGGTGCAGCGGAATTCTGATCCTGAAG
t6        CAGCAGTGAACCTTCGAACGCGCCATGCGGATCCCATGATGTATGCCTTTAAACACGTGC
t7        TTACGCTTGAGACCTCGGTCCGTCGTTGCGATTCGCTTAAACGGGTCCACCTCCTCGTAG
t8        AACCGGTGGCTGCATTCATAAAGCTGAGGAGTTCGGAGCGGCGGCATTAATGCCTCACAG

          CTCTTAGGTTTGCTAACGAGAGTAATGATTGAGTACCCGGCATTATAAACTCCGCCCCGT
          ACTCCAGGTTAGCTATTGAGGGTAACGGTTGAACAGTCAGCGCAATAGACTCCTCCCCGT
          ACCCAGGAGTACTTATTAGAAATCACACATAAGTAGGAGTTGGCCTACGTTCCTTCCGGT
          CCGCGAGAATCGCCATCGGGAGTTAACGCTGAGGCGTTGATGGAGTATGTACCTATTCGT
          GCTCTAAAAGCATTCATGTAAGAAGTATATTAGTTAGAGGCGATGTAAGTTACCAACCGC
          CCGCGAAACATATAATCGGAGGGGGGCGTATAAAGAATCGGGACAGGAGTACCTCTCGTT
          CGTCGCGGCCGACTGCGGGGGAAACGAGCAATATGAGTTATCTTTCAGCTTAGACTCTGT
          ATCATCGGTGTTTTACCGGGTACTCAGGGAATATAGAGGTGGCACTGGATTCTACTTTGG

          GTGTTAACTGATACTGATTGTGTGCTAAATAGATTTTCCGGTGTAGATGGCCGATTTCAT
          GTGTCATCGGATACTGATAGTCTGCTGAGAATTTCCTCTGTCGTAGTAGGCCGGTACAGT
          TCGATCTCCGAGCCTGCCCGTGCTATCGATAACTGACTTGGTGTCGAAGGTGACCACATA
          GTGGCATTCGAAATTGGTCGTCTTTAGAATTGGATCAGTGTTTTAACCGGTCGCCGCGGC
          GTAACTTCTGCGTTTGACTGTTCCACGCGCGAGCTCCCCAATCCAGGGGGAGGTGAGCGT
          GGGACGCTGGAGACCGGCTATTATATGGACCGACTATTCGTCGAAACGTATCGCGAGTGA
          ATGATATTGGGGATGGTTCGCGAGAAGTCTACGTCACCGGGCGTGGGGGTTCTATGCGAG
          CCGAGGCTGGAGTTTGACCGCCGACGACAACTGCCGGTAAGGTAGGATACGCCTCTTTGG

          GTTGGTGCTAGGGTCAGTTAGGATTATTAACTAGGCACAGGATACCCGGGGTAGAGGCGC
          GTCGGTGATAGAATCAGTTAGGATCTTTACTTAGGCACGGAATAGCCGGGGCAGAGGCGC
          GACAACACCAGAGATAACCAGGGCCTCGAAATAATAATAGAATGTCAGAGGCCGGTAAGA
          GATGGAGTTCGAGATGTACAGGGCTATGACGCACGTAATGAATATAGGGAATCGGAAGTC
          GGTGACACCCGGGATACTTCGGATTCCGAGACATACTTAAGACGTAAGCCGCCGGAGCAC
          TGATGCACTTTTAATCTACACTCCTCTGGACCGACTAGAAGGTGCGCGATTTCAGAGATC
          GGTACAGTTCCGAATAGACGCAACACTATACTAGGACCGGACCACCAAGGCCAGGGAGGT
          TGCCCTTTTCTAGCTCCCAGGTAACAAGCACCCTAGCTGTACTGCAGGCCTATAAAACGA

          AATGTTTTACGAAGCTACCGATCCGGGCTTGTGGTCAGAGAAAAGGTCATTTGTCACAGA
          AATATCCTATGAAACTACCGCCCCGGGATTGTGGTCACTGAATGGCCCATTTGTTACAGA
          ATCACCCTGTGGGTTTACCAACGCGAGAACACAACCACTGACCGGGCCATCTGTCACATA
          TACACCCCGGGAAACTTCGGTCACGAAATTGTAGCCGACGACCGGGCTATTCGTTGAAGG
          CGCGAATGTAGTAACTAGTGACACAATTTCATAGCCTTAGAGAGGGTATTCTGCTCACGA
          CATTACTTGAAACAACACAGAAAACCACCCATTCTCAGCGAGTGTATCACTCGGTTACGT
          AATAGGTCAAGCATGAACCATTTCTCAGGTCTCGCATCTACGCAAGATATTCGCCCCATT
          GATGATCCGTAAAACAGCCAGCTTTATCAAGCCGCTCCCGATACAATGATTAGGACGTAG

          TACCCCCGTTTTTACCAGGCAGTGAAAGAACTCATCTCTGGAGACAAGGTTCTATTCCCG
          TATCCACGTTTTTATCTGGCGGTGTAAGAGCTACCTTCTACAGACAAGGTTGCTTTCCTG
          CAGCTGCGTACTTGGCTGGCGGTAAAGAATTAATCCTCGAAAGTTATGATTTCGTCCCCG
          TAGCAACGTCGCTGGCCAGCGATCATAGCTTCAATCCTCGACGATATGGGCTCGCTTCTG
          TTATTGCGTCCATGGCTGGTCGCATAAGATTTGCAAACTCCTTCTCGGACCCTGATCTCG
          CAAATCCTCATTCATGCGACCCCCAACGGAAAAACTTTAAGTAGTTTATGTTCAGTCATG
          TCGCTCATCTCTTGCGTGGGTGCCGTAGCCGCCTCACGCGGGGGTCTGCGTTCATGCGTG
          TGAAGGTATATCGAGCGGGACAACAAATAAGCAGGAACCACCAGTTCGTGTTCCCTAGCC

          CTTGTAGATGACCGTCTAGTTCACGAAATTGTCTCTATCTTTTGCACATCAATAAGCGTA
          CCTGCAGATGACCGTCTAGCTCATGAACTTGTCTCTATCTGTTGCTTCTCAACGACCGTA
          ACGCTACATATACATTCAGTCTATAAAATCGTACTTATCTATTACGTGTCTACGATTGTT
          CAGCCAGACGACTACACAGTCCATGAACTCGTCTTAGTTCTACCCACGCTTATAACCGCG
          CCGCTAATCAGTCACAGGACCAGTGGATATGTGCTCGTCATGCCCGCGATTACGGACGTC
          GCTTAGATAACCTGGACGGAGCTGAAACCAATATGTTACACTCTTGTGGCGGGAGATGCA
          GTTTAGAGTGGAGGCACAGCCGTCCGGTTTCCGGTCCCCAAACTCGTCTTCCAGTTTGTG
          GCGCACAGCATAGTAAGGCTGAAAAATCCACTTTTTGCAATACCCACGCCGCTATTCGCG

          TCGAGATAATCCCCCCGCTTCTTTTTAGTGATGGACGACCGAACATACACAGCGGCTGTC
          ACGGGCTAATTCCCATGTTCTGCCTCAGAGATAGTCGCTCGCACATGGATCGCTGCTGGC
          TCAGGCCGGCCTCCCAGCCCTCTCCTATCCAGAGCAGCCCCTAAACACTCATACCTAGCC
          TGGGACGAGCAACACAATCTGTCCATCACTCTTGCTACTCGCGAGCAGGCTACCTCGGTC
          CTGGTTTTGTTCTTTCATCGCGCTTTAGTCGCAGCGACCCAAAGACGGAAAACGTCTGTA
          CAATCTCTACACGACTTCTCTCCCCAGTCAATGTTGACTCGTGGGCAGGAGGTCAACTCC
          TTAACTATATTGCATACTTGGACCTCGTGGGTTACTGTTCGTGAGAAGGACGCGGCTTCC
          CCAGTCCGGCCTTGTAAGCTGATACTGCACCGGAGAATGTGGGTCAAGGAAACGTTCACC

          TATATGACCCACGGGATAAATAAACCTGTTGACTTCGATCTCGCATATGCAGTCTTAGCT
          CAAACAAACCGCGGGAAAAATAAACCTGTTGACTGGAATCTCGTATACGCGGTTTCGACT
          AGAATGGCATTCACGCTTGATCAACCTGTCGGCTTCGAGCTAGCTAATGAGATTTAGGTC
          AGAACCGTTTCCGAGTCAAATCAGTCTGTAAACTCAGAACATGTCGTTGCGGTCTATGCC
          ATACTGCGCTTTGCACTCCCTCACCCTGCCGCGTCCGTCAATGAAATCGGGAGACGAGCT
          ATGATATTCCGTCTACATACTGGCTCCGTTGATGTCGTGGACCCGGACACGGCGACAGTC
          GCCTCAGAAGACCGTGATTCGAAGAATTCAGTTTCCGTATCTGCGGGTGTAATTGATAAT
          TAAATTCGTCTGGGGCCAAGTCAGGATGATTCTTTGGGTTACGTGGAAGGAAAGTTAGTC

          GTGCAATACCCTTGTAATGCGGAGCATCTCCCGTAGAAACACACCTGTGACTGATTCTCG
          GTGCATTACCCTTTCGATGCGGCCTATTTCCCCTAGATACACACCCGTGACAGGTTTTTG
          GTGTGCTGTGCCTTCAAGGCGTTTGCAACGTCGTTGTATCGTGAACACAACAGTTCCTGG
          GCGCGCCGTAGTCTAAACTTAACCTCTCAGTCTTGGCTACGTACTTAAGGCAGGCGCTTG
          GCGTGGCAGCCTACCAAAAAGACTCGCCTGTCTGCATGCCATATCCAAGTCGACACTCTG
          GCATACCAATTTTTTATTCCGGGTTATTAGTCCCGATGAACAACCTGTCACGGCCCTTCA
          AGTCATCCCATCGGTGACCTGAGCTTCGCGACAGGGTGAGATAACTGGGGTGCATTACTA
          GAGTGCGCTGTCCCCAGAGAACATCTTACGTAAGGGCTTGCTATTTCCCTAAACATTTCC

          GTAGGGTCCCTCTTCTTCTATTATGTGATTTTGCTCAATTACTGGGGTAGTCACTACTTT
          ATTGAGTTCTTGTTTCTCCATTATGTAATTTCGCCCGGTTATTGGAGTAGTAATCGCTTT
          GCGATGTCCTTGATCCCCTGCCATTTGGTTTCACACAGACGCTTGAGTGGGCACTGTACT
          GTTGGGCTCCTGTTTGCTTTTCCTGGAAATCGGGCCAACTCCTAGATAAAAGACTATATT
          GAGCCTGTTTCGGCCCTATGGCACGTAAGTTCCTCGAGCTGCAGAAGTACTGGCTACTCT
          TTGGTATTGGCCCCCCACGATGCCGTCACTTGTTGAGACTGTTGAAGCAGTCGCCTAATC
          CGGTCCAATCAGGCGGCAATCCCCAAAACACCCCCAAGACTTTGGGGACTACGCTCTACC
          AAAATCACCTACCTGCTTTGCCACCTCATACTGCCTGACTGGTACACCCTATATTCCCAG

          GCTCCTGTTATGAACACGGTTAACTGAAACTAGCGCGCTACGACCTTCTGCATTGTTGCG
          ACTTTTGTTACGGACACGGTCAACCGAAACTAGAATAATACTCTCTCCTGTATAGTTGCG
          ACTGCCATCACTCACACGAAGATCCGAGAGTGACACAGGACACGCATGTGTGTAGTCACC
          TGTGCCGTACTGAGTTTATCCAAATAAGATAGACGCAAGACCGTCCCCCGTGCAACCTCG
          ACAGCTCTCGTATATTCGATTGACTCGCACCGTCAAATTATTTTGTTCTGACTATCCGTC
          GGGGCTGGCCCACCTTCAGCCTCTGCGAATTCATTCAAGGAAAGTGCCGCTATAGTCACC
          TCTTGCATCGTTGGGTTGCGCCTTTCGAAGCGTTCTTAAATACACTACCGTGTAGTCACC
          TTCGAGGAGCCCAAAATCGTATAAACGCATGGCTTAGGAATACACTCTTTCGTGATAATT

          CATTTGAGGGAGAATCCCCTATTTAGACGACTGGCAGGGTAGACACGGCTGGACCCGGTC
          TATCTGAAAGCGAACTGCCCGTTTAGAAGTTTAGGGGCGCGATCGCGGCTGAACTTGGTT
          TATCCCAAGGCATACTCCTCACGGAGGAGCAGAGTAGAACAGGCATGTCTGAATCCAGAG
          TGCTTTCAGGCAGAGGTTCCTCATATGATAACAAAAAAGTAAGTGGGGTTAGATTGGGAA
          CACCTTAAGGCGGGTCACTTACTAGAAGGCTCAGTCGAGTTATTAAGGCAGGTCTTGCCA
          CGGTACAGCAAAAGCCTTTTTTGGGAAATCATAAAGTGCCTATTAACGTTGACTCTAACC
          ACTCTTCAGTTGTATCATGTCAGTAGAGACACCAACTAATGGTTAAGGGTAGCCTTCATT
          GGTCCCAGCCGGCGCTAATCTTACGTGTGTTTGGGCTAACCAGTAGGCATTGTACAATCA

          AGGGATTGAGCAGATTCAATTGACTCATTCGTGCGCCCCGCTTCGACAGACCACAAGGTG
          AGGGATTAAGCTGATCTAATTGGATCAGTCACGCGTCCTGTTTCGACTGCCCATAGGGTG
          TGGGACCACGGTGTATGGTTCATCTCCATCACTAATTCTGTTCCGAGGACCGACGGTACG
          AAGGATCACGGCAACTAGCCTGGTCGATCCGTTCCCCCCAATTCGTAACCGAGTACGACG
          AAGACTAACGTGGCGATGTCAGATTCCATCACCCTTACTACGTTGCCAGCTGACGTGCTG
          GCATCATCCGTTCTCCTTCTATTGATCCCCGGCAACCCCGCACAGGCTGCTGGGCCGACG
          GAGACTATTGCTCCCCGCTTAGGTCGCTAGTGGAGCCACAATAAGATCGAAGGGCTCATA
          GGGGGGCACGTAACTGTTCATGGCACCACACTCTCCGATACTACTTCCAAAAGGGCGATG

          TAACGTAGGAAATAATTTAATTTCCTGCGAGACACCGATCCGAGCTTTATTTACGTTCAG
          TAACCTAGCCAATAATTTAGCCCCCTGCGAGACGCCATAACGTACCTTAGTTATGCTCAG
          AGGTCCTGATAACGTTTTCGCTGCACAAGGGTCACAGAACTGAATTGCATCTGCGCCCAA
          TGTACTCCGTAAAGCCTTCCCTCCCTAAGAAACTCAGGACAGCGTCCTACATAGGTTTAA
          GATACCTTATTCGGAGTCAGTCCCCTAGATGGATCAGAGCCGAACCCTAACATGGCACAG
          TGTGGAATGTCGCGACTGCAAACCCTAGGAAGTCCTGGAGGGACTTCTGTGTCCACCCCA
          TGTCCCATGCTCCGATTTCGACTACCGGGAAGTTCCATAACGATCGTTCACGTTGGTTCC
          CGTACAGACATCCTGCCTCCTTGACCGAAGACGTTTCGGACATGCAACGAGCCAGCTTGC

          TCATAACACGGTTAGGAATAGCAGGAGTGTAGGAGAATGTGCCGACAAGGGACGGTTCGC
          TCCCACCCTCGTTAGGAATTGCAACAGTCTCGGTGGATATGCCGACAGGTAACGGTCAGC
          TTGTATTCCGGCTACCGATTTCTGAGATCCGGCTGGGAGTGCCGCCGAGGGCAGGTCAGT
          CCGTAGTCCAGCCATTGACTTCCGCGAGCCGGTACAAAGTGCCGATGAGGACCGACGAGC
          GCTTACCCCGATTAGGGATTGCAGACGCTTGACGGGGCGCGCCCTAGGGCCCTAATCAGT
          TCGCCTGCTGGTTAAAAATAATCGACGCCGGAGAGGTAAACTAGTTGACTCTAGCTTGAT
          GGAGACACCAAAAAGTAAAAGCAGCGCCTGCAGAATGGGCATTGCTGGGATCGGACTAGC
          TCAGCTTCCGGTTCACGGCGGTGGCGACCAAGTTGAGAAATATGACGGCATCGGATACTC

          CTTTTCGGGCGGCAGGCAATTTCCGTCTCCGGGCAATCCG
          CTCTACGGGAGGCAGGCAATCTCTGTCCCCGGGAAATCTG
          ATTCACAAGTACAAGGGACCTTATGCTATTGGAATTTCAT
          TATCGCAGACACTCGGCATATTGTGTTCAACGGCACTTAG
          GTCTAATGACGCCATTTTTTCCACGCTCTACGGGAAAACT
          ACCCATCCGAACCACATGATTAACATGAGCCGAAACCTGT
          TATTATGAGCGCTGTTTGTTAAAGAACAGTCCAGCGAGGC
          TAGCACATGGGCCGGCCGTTCGGGAATCTCTGACACCAGG

