 8 1000
t1        CTTCACTACACATGGCGGGAAGAGCATAAGTTGGTCTCGGTGCGTTGCGTCAACCTAGCC
t2        CTTCACTACACATGGCGGGAAGAGCATAAGTTGGTCTCGGTGTGTTGCGTCAACCTAGAC
t3        CTATACTGACCATGCTGAGGAAACCGCCAGTCGGGATCGGTGTCTTGTGCCGAACCTGAC
t4        TTGCACGGCCCGTGACTAAGGGCGTACCAGTTGGTGTAAGGGCCTAATAATAAACAGGTC
t5        CGACACTGACCGATAACAAGCGGACCTCGCTTGGGTTCCGTCTCTGAACTTCACCGTGAG
t6        TCACTCCGTCCACGGTAAGGCTGGTTTTAGCCGGCCTCGATTGTCTGACACAATTGCGGG
t7        GGTTACAACAAATATCAGGACAAGACGCTGAAATTAAAAGTTTATCACCTTAGCTATGGA
t8        GGCCACAACACATATCAGGGTAAGGTATTAACATTAAAGGTTTAGCACTTTAGACATGGG

          TGACGTGTTCTAGTCCAGGGAATCTATCACCGGTCGTGTGCCTACGCAGAGCTAAACAAT
          TGACGTGTTCTAGTCCAGGGAATCTATCACCGGTGGTGTGCCTACGCAGAGCTAAACAAT
          AGCTGTATTCGAGTTCAAGATACCTATTACCGGTTGTGTGAAGGCACAGAGTTATGCGTC
          CGTACTGGCTAAGTCCATGGTTTTTACCAGCGGGGATGTGACGACCAGGAGACAACCGCC
          CGTCCTACTTAACGCCCCGTTGCCTATACCCGTTTGCCGACTCCCACAGCGATACACGTT
          AACCTTGCCGAATTCCCTGCTGTCCATGAATTGACCTGTATTGTCGAGTTGATAGACGGC
          CGACTGGGGGTTGTGTACGGCCTAAACCACCAGCCATGCACGCCAGATGTAGGAAAGGAA
          TCTCTGGGAACTGCGTACGGTCTCCACAACCGATCATGCCCGCGAGACGTACGAAAGGAA

          CCGATATACCACTCACGAGGATTGACCTATCTGCTGCCCGCATTCCGAGCCGATCCAGGG
          CCGATATACCACTCACGAGGATTGACTTATCTGCTGCCCGCATTCCGAGCCGATCCAGGG
          TCGACGTGGCACTTATAAGCGTCGACCCGATTGCTACCCCCATTTCAAGCCGACCCGGGG
          ATGACCCTGCGCACACAAGGGTTGATCTGACTGTTATTCTTATTTCGATCCAATCCAGAG
          CCACGACTTTGCTCACGTCTGGGAACCTGGCCTCTGCCTCCACCTTATTTCGCTTCGGAA
          CTGCGACCCTATTTTCAAATGCCGGCCTAGGTGGTACCTGAATATCGTGTCGAATCGGGG
          TCTAAATCCCCCGCCTGAGAGATGAGTTGTCTGCTAACATTAATCCAAAGTTACTTGTGC
          TCTAAATTTCCTGCCTGAGAGAGGAGTTGTTACCTAACATTAACTCAGAGTTACTAGCGC

          TAGAATTGAGAGTCGTCAGCGTCAATCGCATACTAGGCAATCCGCCAGTGCACGTGGTAC
          TAGAATTGAGAGTCGTCAGCGTCAATCGCATACTAGGCAATCCGCCAGTGCACGTGGTAC
          CAGAACCAAAAATCGACAGTACGATCTGTATTTTAAGCCACACGCCTATGATCACAGAAT
          AATAACTAGGAGTTGCCAGTACCTATCGCGTTCTTAGCGATAAACCCGTCCTCATAGAGT
          TGTAGTTAGGGATGTTGTGTGTTACTTGTGTGCTGGGTTACATGTTCAGGGATACGGGAT
          CGGAATCTAGTGCAGAACGTATAATATCTCGGCTGGACGACCCGTTCTTGGGTATGGGAT
          GGGAAACAGTCAGAGCCAATCCGTCCATCACAGCAAACACCACGCTTTTCTATTCTACCA
          GGGAATCAGTCAGAGATACTCCATTGATGAAAGCAAATTACGCACTTTTCTACTATACCA

          CAGAGCCTCTTCACTACGGGAAAGGTCACTTATAGACTAAAAGACTCTCGTGCCCCTTTG
          CAGAGCCTCTTCACTACGGGAAAGGTCACTTATAGTCTAAAAGACTCTCGTGCCCCTTTG
          CAGAAATTTCCGTCTGCGGGAAGGGCTTTTTACAGTCCATACGATTTCCGTATTTGTCCG
          CCAATTCCTCACTCGGTGTAGAAGGTTGCTTTTCGCCTAAAAGACCCCCGTACCCTCTCG
          ACAAATCCTCCAATCAGAGGGTGTATCAGCCATAACTTACAACGGGTTCGGTCCTGGTTG
          TCGACTCCTCCGGCAGCAGGAATTCTGGCACTTAACCTAGTAAGCTATCGAACCCACGCG
          TTTTTCCGATGCGCCTGTGTATGAGACACTGGTAATCAAGGGGAATGCTGGGGCGAACTA
          TCTTTTTTATGCATCCGAGTAAGCGAGACTGGTAGTCAAAAGAAATGCTCGGGCACCCTA

          CCCGCTGAGTTTATTTCAGAAGACAGGATTCGGATGAGCTCTCGAATGGGGAGGCGCCAT
          CCTGCTGAGTTTATTTCAGAAGACAGGATTCGGATGAGCTCTCGAATGGGGAGGAGCCAT
          CACGCTGAGTTCACCTAAGATGCCAGTATTCGTATGAGCTCCTGAATGAGGAGACTCTAT
          TCTGCTGTGTTCACGTAGGATGAATGAACTTAGATGAGATTTCACATGGGTAGACCCCAA
          TCTGTCGTGATCCTCCTAGAAGATCAGAGCCAGGCATATATTAGGCGGGGGGAGCTCTAC
          TCTGATACGATCCCGCAGAGGGTTCAGAGTCAGGTGACAATTTGACCGAGGGAGTTCTAT
          ACTGTATTAAAGCAGCGTCGAGGCCGAAAAAGGACAAGTCTGCCGTTGGGAGGATCTCCG
          ACTGTGTTGAAGCCGCACCGTGGTCGAAAAAGGATAAGTCCGCCGTTGGAAGGGTCTCAA

          TCACGCTCATATCAGACCCTACAGGCACTAATGGTATAGGTACGAAAAAATTGCGCGAAC
          TCACGCTCATATCTGACCCTACAGGCACTAATGGTATAGGTACGAAAAAATTGCGCGAAC
          TCACCTTCACACCGTCATCAATGCACGCGGACGGTACGGGTCCGTATATACTTCGCTAAT
          ACATGCCCCCACTATTTCCTATAAGCGTCGACTGCAGCGATCAGTCAGAATCTCGCGATA
          TCATAGCTCTCAGCTCCCCTATAAAAGGTGTTAGGGCGGGTTCTCGTAAATCGATCAAAA
          TTATTACCTTAGGCCTCTTTATATACGGTATCGGCGCGAACTCACATGAATTTTTCGCAC
          TCGAAATGCGTGCAACTTAATGGCCCCCTTACTTGTCGGCTGTAATTCGTTCGCTCATCG
          TCTAGACTCGTACCACTCGAACGCTTCCATACCTGTCGGCCACAGTTCGTTCGATCACCG

          AGATAAGAGGACATGACTGAAATATCAACATGCTTCCTAGACTAACCTCTGCCTTGGCAG
          AGATAAGAGGACATGACTGAAATATCAACATGCTTCCTAGACTAACCTCTGCCTTGGCAG
          CGATAAGAGGACATGACTAAAATCTGATCGTACTTCCTAGGCTGATCTTTACTTTGCTGG
          TCATACTAGGAAACGTCTCAAGTACGATTAAGTCCTTCGGACCCACATCCACTCCGGCGG
          TGGTCGAATAGCCTGAACTAGGTGCAATCCTTCAATCCGGACTGATGTCAAACCAGAGAG
          TGGTTGAAAGCCCCGAGTTAGGCCTTAGCGTAAAGCCCGGACTGCGTTGCAAGCTGAGCG
          TTATGATCAGTCGAGTATATCCTTTATAATTTTAGTTCAGGCCCGTTCCCGGTTCGTCCT
          TCATGATCAGTGGAGTGTATCATTCAAAGCTCCAATTCAAGCCCGTTCCCAGCTCACGTT

          ACCACCCCTTCCGAGCATCTTATGAAGTGAGAAACACACCAAGATACACGTACGCCAGAC
          ACCACCCCTTCCGAGTATCTTATGAAGTTAGAAACATACCAAGATACACGTATGCCAGAC
          AACACCCCACCCAAGTCCCTCACGGAGACAGGGGCGCCCTGATTTATCTGTCTGGCGGAC
          AAAAACCATCCCAAGTCGCTCACGAAGTGCGGAGCATGTAAAATCCTCCGTGTAAGAGAC
          CACATCATCCTGCAATCGTATGCTAATTGTGACGCTCTCGATACCACCCGCGTAGTCTAG
          TGCACCACCCTCTAGCCACTCGTGTAGTGAGGAGCACGCGGAACTATTCGTTTCATATAT
          GGCGTCGCTGACAAGTTAATCACAAGCTTAGCAGTAGGTCCTCCCCGTTATAACCCGTGA
          CGCTTCGCTGACTATTGATTGTTAAGGTTGACAGTGTGTCTACCCAGATGTAAACTGTGT

          TTTGGGAATCACTTGTTGGTTCTGGACCGAACTAGCGGGCGAGCATCCGATGAATCTGGA
          TTTGGGAATCACTTGTTGGTTGTGGACCGAACTAGCGGGCGAGCGTCCGATGAATCTGGA
          TTAGGAAACTGTTAGTGGACTATGGGCCGAACTAACGGCCGAGCATTTGACGGATCTGGA
          ATACGAGTCCCCATCCCCAGTGCGAACCAGAATAATAGCAGGACAACTGCCAATACTGGA
          CTTTGTGACTCTTCACTGATAATGTACGAGAACAATGTTTTAGTAAATGCCCCTATAGGA
          CTTCGAGACCCTACGTCGGTAGCGTGCAAGACCCGGAGATGAGTATTTTACCCAACTAGA
          GCATGCTGGTCGTCCGGGCCGCCAGACCGGTGGCTATAAGTTGTGCGTACTTCGTGAAGA
          GCACGTTAGTCACCCGGGTCGCCGAACCGATAAATATAAATTACGCGTGTTTTTTCAAGA

          TTTATTTAGACAAGCGTAGATTGATACACGGATATTAACATGCAGTATGGTTGTAGAAGT
          TTTATTTAGACAGGCGTAGATTGATACACGGATATTAACATGCAGTATGGTTGTAGAAGT
          CATGCTCCGGCAGGGGTGATACAATGCGTGGACATCGACATACGCCATGGCTCTAGGAGC
          AATCATTTGGCAGCCATAACATTAAATGGGGACAGTATCACGCTTCACGGTCGCGGATGT
          TGTGCTTCGGTGGGCGCGATATGCTATATGAACACCAATATGAGCAGCGGGTCCCACACT
          TATGATTTGATGGGCACGATAAGCTCCCTGAGCGCCAATGTGGGTAGTGTGTGTTCTAGT
          AACGGCGCGATGGGAAATAGCAGCAGGCTAACTGCACTCGTTGATAAAACTACTCTCAGC
          AACGGCGCGATGGGGGAAAGCCACAAGTAAGCTACTTTTGTTGGTAGAATAACTCCCAGC

          GATAGGAAGGGGATACTCCAAAATGTCAAACTTATTCCATTGGGTACGGGACATTGGACA
          GATAGGAAGGGGATACTCCAAAATGTCAAACTTATTTCATTAGGTACGGGACATTGGACA
          GCTAAGCATGGGACACTCTGCATTGCTAATCTGTTTTTGTCTGGTACGGGACTTCGGACA
          GATTAGCATAGGAGAGTCCACACTCCTCAACTCCTCTCATGGGGTACGAGGCATCGGACA
          GATAGGTATTCCGGCCCTCAAACTGAGCAGCCTCCATCGAGGGGTGCAAGACATCGGACG
          GATCCGCGTGCAAACTTTCCTGCCGATGACACTCTATTGAGGGAAGCAGGGCGTTGGAGG
          TACATCACTATTCCAATACATAACATAGGACCTATTCCCGCGAGGTGATACGATTGTACA
          CATAGCTCTGACTCAATAAAGGATGTAGGATGTAATCCTGCGTGGTAATACGACAGAACA

          TGAAGATGCGGTCCTATGCGCAGCGTGTCCCCCGCGGTCTATTTGTTAGACAGAACATGC
          TGGAGATGCGGTCCTATGCGCAGCGTGTCCCCCGCGGTCTATTTGTTAGACAGAACATGA
          TAAAGATGAAGTCTTGTCTACTGCGCGTCCCCAGCCGTTTATTTGATATACAGTGCATAC
          TGGTGAAACGGGCATGTCCGTGTCGCATTTCGTGTCGTCTTTTCGCCGCCCAGTACATGG
          GTTAGGAGTGGCCATGTTCGCAGTGCGCACAGGGACGCATCCCTCTTGTCCCGACTGTGA
          GGCACCAGCAGCCATATTCATTGCTCGAGCGGCGGAGCTTACTTACTATCTAGTCCGATA
          GACACTATGGCTAGAGGCCACAATGAGCCTAGAAGCTTGTGTTCTGTGGTCTAAATTCCG
          GTCATCGGGGCTAGGGCATATAATGAGCCTAGGAGGCAGTGTGCCGTGGTCTATTGTCTG

          GTTATCCAGGAACTGCACTAGACAGTCACGTGTAAAGTTGTAGTACGGGTGCGGCTCGTT
          GTTATCCAGGATCAGCATTAGACAGTCACGTGTAAAGTTGTAGTACGGGTGCGGCTCGTT
          GATGACCTGGATCAGCTCCGGTTAATCAGGTATGCAATTGTAACGCGGGCGTGATCCGTT
          GAAGATTTGGATTACTACTAGGTAATTACTATTGAAATTGTAATACCAGGTTGTATCGCC
          GATATTCAAGGTTGGGACTTGGGGACTAGGTGGAACCTCGTAGTTCGGACGCTACTTGTC
          GCTGATCCGGACCGATGCCAGGTAATTCCGTGTTTCATTACACTTTGGTCGTTAACCATC
          TGTAATTGCTTCCTCAATTTGGTTGCCAGTTGCATTTGCGTATCAGTTGTATCCTCTATC
          CGTAATTACCACCATGGTCCGGTTACCGGTTGTGCTTGTAAAACTGTTGCGCCCTCGACG

          GGGTGGAGTGCGGCGTAGCTAACTCTCCAGGAAGTGAACTACCCAAATTGCTGCTTCCAG
          GGGTAGAGTGCAGCGTAGCTAACTCTCCAGGAAGTGAACTACCCAAATTGCTGCCTCCAG
          GGACAAAGTGGTGCGCAGTCCACTCCTCAGGAACTGAGCGATTAAGATTGTTAATCTCGG
          GGCTAGAGGGACGTGCAACAGTTTTATCTGGAATTATGTGTTTAACACAGCTAATTCTGA
          AGACAGAACGACCTGTAGTAGTCTACTCCGGTATTGGGCGATTTAAGTAGGGCTCTAGGA
          AGGTCACTCGAACCGCAGTAGCCTATATCGACTATAGATGCCTCCGGTTGGAGCTATGTA
          CCGCCGGATTGGGTGACGATGTGCTTATAGATTCCAGGACGGCGATGCACGGACCTGTGA
          CTGCCGCATTCAGTATAGATGCGCTTACCGAACCCGGGACGGCCATGCACAGAATTGTGA

          GCCGAGTCCCCGGATTGTGTACATTGGCCGTTTTTTTAATGCTGAATAGTGGCGTCATCG
          GCCGAGTCCCCGGATTGTGTACATTGGCCGTTTTTTTAATGCTGAATACTGGCGTCATCG
          GCCGCGAACTCGGAGTATGCAGGTTGGCCGCCTTATTAACATTGAATTGTACGGCCATCG
          GCCATCAGATCGCAGTGTTCATATCGGCCACTTGTCTGATCTGGCATCGTACCGTCATCG
          ACCGTTCGCCCGCAGGCTGCACTATGGCCTCCTGACTAATACTACCAGGGGCGTCGATGG
          TTTTTTCGTTTGCGGTTCGTGTACTGGCCGCCTGGCCAATACTTACGTGGGCCGAGCTGG
          CGTCTCCGCATGTCATCCCGGTAACGTGGAGCAGCCCTGCACCGAGTTCGATGAGGCTCG
          CGTCTCTGCACGATATCCCGGTAACGAGGAGCAGGCCTGCACAGAGCTCGACAAAGCCCA

          CACAGTAGGTCCTGGTGGCCCACGCGAATACAACATCGTC
          CACAGTAGGTCCTAGTGGCCCACGCGAATACAACATCGTC
          TACAGTAGCCCATGCTGTTTCTCAAACAAACAATGTCGTT
          TCGGGCCGAGCTTAGCGACTGCTGTGCAAGCTCCCTCGCC
          CCTTTCGGGTCTTATCGTCGTTAGCGCGGACGACTTTGCC
          CCCTGTAGGTCCTAACATTGCTCGCTGATGCGGCCTCTTT
          TTTAGTCCGCCAGAACCTCACTGTTAAAAGACATTTCGTC
          ACAAGTGCGTCCAAGCCTCTCTGCTACAAGATCCTTTGTC

