 8 1000
t1        TTGGCTTCTTCCCACCGAGGCGTCAGTCCACAGACGATTTAAAGCCCGCGACTAGAGTGG
t2        TTGGCTTCTTCCTACCGAGGCATCAGTCCATAGACGTTTAAAAGTACGCGACTAGCGTAG
t3        TTCAGTATTTTGTGTTGAAGCGCTATCCTGCAGATTATCTGAATGATCCATCCGGGTTAA
t4        CAGGCACCCCCGAGCACAGACATCAGACCACGACCATTAAGAAGGGCATGACTGGAGAAA
t5        AAGGCTTCATGGGGTAGAACTGTGAGTGCACAGACGTGTAGATAATGACTACAGGGCCCA
t6        TTGGCTTGCTTGCGCGGCGTCATCGCACGCCAGGCATCCAGGCAAACATAATCGAAGGAA
t7        TAGTGTCGTTAATGAGAAGTCACAGATACCAGGGTGTCTCAAGGTCGACGGTACGCATGC
t8        TCGAGGCATGTGGGGGGTGCAACTGGTGCCCGAATAACCTCAAGGTCATCATCGGATCCA

          CTCCTTGTCCGATCACATGAAGTGCAAGTTATTCGCGCTGCTTAGCCCTGACAGTTCATA
          CACTTTATCCGATCACATGAACTGTACGTTATTCGCGCCGCTTAGCCCTGACAGTTCATA
          CGCCCCAAGGGCTCGCACGCGCGGCATGCCGTTTGTTCTATATTTCCCCGCTTGTCAGAG
          GAAACTAATAGAGCCCAGCAAGTGACGGTCACGCGCGGTACTAGGTTTGGTATTATCACC
          CGCTCACCGGGGCTTAGAGCGGAGTATGATAGGCACTGCTTTATGCTACGATCGCTCAAG
          ATTTTAGCTGGAACGAGAGACAAGTACGCCGCTATTCAAACCCCCCCCCGGCCTTCCCAG
          CAACCTGGGGGGATACGGCAGGAGAACAACCCTTGTGTTATAACGTACAACGCCTTTTTG
          AGACGCAAGGATCTGATGAAAGCATATTGAATAGACAGTATTACCTCAGACTAGATCACG

          ACCAATACAGTCCTTGTTAACAGTACCGTGTCCTGACATTTAATTGACCAAGTCTAGTGT
          ACCAATATAGTCCTTGTAAACAGTACCTTGTCCTGACGTTTAATTTACCAAATCCAGTGT
          GGTAAAAAACCTTCAGGTGCCCATACAGCCCCGTGATTCTTAACCCTCTAAACTTACTGT
          GCCCATGCAGGCTCCGCTGCTTATCTATCATAGTAGATATCGGACGCTAAAGCCATTCGT
          GACAATGCTCCCCTCGGGGTGCGTACACACTAGTCACCCTCGATTCACCATTTTTGAGTT
          GCCCATGCCCGCTAACACGCCCTTACGTTATCATAGTCTCTGATTAACTAGTTGCCCAAG
          TCCACGTAATCTCCCGAAGCGCATGCGCACCCCTGCACCGAAGAAACCTATCCGCATAGT
          GTAAACGTATCCATCACAGTATAAATCTTATTCCCGTTTATGGAATATAGAGCGCATAGC

          CGGAATAAAAACTGTTTTAATGCATGTACTCTCCTCTGGGAGTTGGAAGTTGTCATGACT
          CGGAATAAAAATTGTTCTGACGCATATACTCTCCTCTAGGAGTTAGAAGTTGTCATTACT
          AGAGTACACGTATATAGAAGCCTACACACGACTCGCCAGTATTCCGTGGATACTGTCATC
          AGAAAATCAGGACATATCTGTACGCACACAATTCAATAGCGGCCAGAGTACCCCATAACC
          AGGAGAGACGGACGCTACCGCAAAGACACTGTCTTTTGACAGCCAGCGCATACTTAAATC
          GGGCGACATATAAACACTGACATCAACAGTCGTGCTAATCTGCCAAACCGTCCCTCGGCG
          AAGAGGAGCGGGCGAATCGATACACCTCGCGTCTGTGGTTGACTTACAGGACTCCCGTCC
          GATCGTTAGGAGTATTTTTATAGTAATGTTTTTCTATCATACCCCACAGGCTTCATCATC

          ATATGTGAGGTTTATGGCCTGACTTTACCACGCACCCCAGAGCACCGGGCAGGAAGATGG
          ATATGTGAGGTTTATGGCCTGACTTTACCACACACCCTAGAGCACCGGGCAAGACGATGG
          GTATGGTGGCCTCTAGGTAGTTCACGTCTAGGTACCCTGGCTTGTCGGGTAGAACACTCA
          GAATGACGATAAAATGGTTGATCTTTGTAAGATGCGCCGACGTATTGGACGGGCTCTTCC
          GCTAGTGGGAGTTAGGACCGCTCTCTGCCACACGTGGAAATGTATCGAAGGAAACTACCC
          ATATCGCCTGATAATGTTCGCCTTTTACTAGAACCAGGAATGCCCTGGGTAGGGTCTTTG
          ATATAGTGGGGATATATCCACCGTTCCTCAACTGCGACATGGTGTCGACCGACTTTGTGT
          GCGTGGAGGACTCACCAAAGCTAATTTAGTACTGTGAAATAGTGTATGGCGAGCAGTTTT

          GTCGGAGTTCATAAAACTCTCTACCAGATGCAAGTTCTGAGGAGATTGAAGTCGAGAACG
          GCTGGAGCTCATAATACCCTCTGCCAGGCGCGAATTCTGAGGAGATTGAAGTCGAGAACG
          GTCGTCATTCGTTCCCTCATGTGTGATCTGTGAAGGCTGGAAGGGTGGAATCCAATAGAT
          GATATAGCTTACCCTTATCCGTGGCAATCCCGATTCACTGATTGATGGTTCCTGGGAACG
          GCATCCGAGCGTTCCCTCCAGCGGGACTCGAATGTATCGGACCAGCGGAAGCCGGGACGG
          ACCGGTGCCCAACTCCCCGTGAGGGAACATTACGACTCAGTGGAACGAATCCAACAAGTG
          GTACGCGTCCGAGTTTTGAAATGCGGGCCGCACGAACGGGGAAGTCGGAGTGAGGTGCGG
          GCTCAATTCACAGCATCTAATTAGGGGATCCCCTTATGGCGCTGTCCGTCCTCCCAACAC

          GCACAGTTCCACCTCCTTGCTCTTGCCGTCCGTCTGGTTGCTGGCGCATCCCTCCAACAC
          GCACAGTTCCACCTTTTTGCTCTTGCCGTCCATCTGGTTGTTGGCGCCTCCCTCCTACAT
          GCTTAGCTGCACAAATCTGGTCAGGCATACGGTGTTGTAGTTTATGTCTAAATAACTCAG
          ATGCAGTAACTCAACTTTGGCTATGCAGTCGACTTGCTTGTGGGAGTACTAGCCGAGATA
          ATGATGTTGTACTTCTCAGATTTAGTAGACCGTATGCGACTTGACTCTCACATCATGATA
          CATCCGTAGATACAGATGGGGCCTCCGCATTACTTGCTCCTCGCAGGTTTAAGTATACGT
          CTGGCTGGATGCTCTATCAGCTCGGCCGATATCTGGAACCTTAATAGCTCCGTCGGTCGG
          GTTGCATTACACCATTCTGGGTAAGGAGATTATAAGGTCGCTGATGTATGCTACTACCAC

          CGATAACTCGACCAGTAACCATATCTTCGTATAGATCACTCGCTTTTCGAAGCCAGCAAT
          CGATAACTCGACCAGCAACCATATCTTCGTATCGATCATTCGCTTCCCGATGCCAGCAAT
          CGGATATTCGACAAGTCTGTGCCTGAAGCTACTGCGCCTTTGACGTTGCTTGTCAAGTAC
          TAGTCCGTCGACGAGCAAGGCTTCACACCAATTGAGTGACCGTTGTTATCATCGTAGTAG
          CGTCTCTCTAGCTAGTGAACATGATTATGTAGTAAACCCCTGTCAATCTTCGTGGACGAT
          CGACCAAGCGGCGAGCAGACATTTTTGCTTATGGGGTCCTTGTTGCCGCACATGATCTCT
          TTACGAGGGACTGTATGTGTGTGATAGTATATTTACCGTACAACATAGTTTTCCACACGT
          CGGCCATGTGGGATATCTAGATGGTCGTACACCGAAATCAGGTCGCACTCCGATGCATAC

          GACCCCTAGAACCCGGGTCTAGTGCTATAGTGGCCCCCAGGATCAGAAAGTTTGGGTCCA
          AACTTCTAGAACCCGGGTGAAGTGCTACGGTGCCTCCCAGGATCATAGAATGTGGGTCCA
          AAGCCATAGAATCCTATATAAGGGTCGCGGCCCCACGCGGATCGAGGATTCCAATGCTTC
          AGGCCTTGGGACATCAGACGAGTGCCATGCCAGGCCGTGGACGGAATCGACCGGTGATCA
          CAAGCTAAGAGCCCAGAATATACACGGTGGTCTCACATAGTAAGGAGCGATCTGTGTCTT
          AAGCTCGAGGGCCCCAGGTAGGGGCTTCGGCGCATCTTATGTTCACATGATCTGTGACTT
          GGCCCCAGGGATTCAGACTAAATGTCTCCGCACTAATTAAGGTTTAGACGCTTGCGACGC
          ACGCTCTTAACTTCTCACTCTGCGCAACGCCACCAAGAGGGACGGAACGAATTTTGTCGT

          GCCCACGGCCAGAATCTCCACTCGGTGTGTATATCTTAGAGGACTCGTCTAGTATGTTTG
          GACCACGGCCAGAATCTCCACTGGGTGTGTATATCTTAAAGGACCCGTCTAGTATGTTTG
          GCTAATGGTCCGAATGTCCGATCGTTGCGTTTAGCTCGCAGCAATCGTCCGCTATGTTGA
          ATCAGCCAGACGGTCCCCCAACCGTCGTGTCTATTTTACAGGGCATAATCGATGTTTCCG
          GATCATTACCCTAACTCCAATCCCCGCTGCTCGGACTACTGGACCCGTATATCGGGATCC
          TCCTACGAACACTATAATGCACCATTACATTAAAGCTGTAGAATCTGTTCGTCGTACTTC
          AACCCGTGGTTGTTCACGTTACCGTTACGACTAAACGCTCAGCCATAATCTCGGACCCGA
          GGACCATGGTTCGCTTCTTGGGCTCTGGCCCCGGAAGCGCTGCCCCATCGTTTTCATGGT

          CTCGAAGCGAGACTACTTCGTGGTGACGTCACCTACAAAAATGCCTCTCAGACTGTGCGA
          CTCGAAGTGATACTACTTTGTGGTGACGTCACCTACAAAGATGCCTCCCAGACTGTGCGA
          CAAGTACTGAGACGACATTTGGAAGGATTTACCCGAACCATAGGCCTTTGTTCAGTGCGT
          CAAGAGCTGAGACTTCACTCTACCGGGATTGTTTCCCTGAGATTCCGTTCAATCGTTTGA
          GCATTTTCGCTATCACAACGGGGTAAGGTTACCCGGCCCAATGTCCTCTGAACAGTAAAC
          AAATTGCTATTACAATGTCCCGACCCAGCTCCTTAACTCCGATTGCTCACGTCCGCCTGG
          CTGAAATTGCGGACATGTTCCAACAAGCAGGTTACGAATCAGCCTCCTTATACTTTCCTG
          GAGTTATCATGATCCCGATAACACAACGTTGCATTGGATTATAACCCTACATTTATACCA

          GCGCCTTTGGTGGCTTAGGAGTCACGCAAGAAAGCTGCCGCTGTTCTCGCCTCAGGCGTC
          GCGATCTTGATGGCTTAGAAGTTTCGCAAAAATGCCGTCGTTGTTCTTGCTTCAGGCGTC
          GTGGTCCCTTTGGATAGGTAGTTAGGATGTTAGGACGCTGACGTAGCTATCCTACGGGTT
          ATATCCAGGGATGATCAAAGATCGGGGGGGCAGGATGGAGTTGTACTCGCCATGTACGTT
          GCGACTCCGTCGGGCCATGGGCAACTGGGGGAAGATATTTTTGCCTCTGTGCTGGGCGAC
          GTATTCTAGGAGACTCAGGGGCTCATCGGAATAGAAGCGCTGGTATATGGTTTGAGTGCT
          GTGTATTAAGGGGATACACGCACATGTTGAGGCAACGTTGCAGTATGTGCCTTCGGTACG
          TCGTACTTGGTTAATCTTGGGCGGCCGGAGTCCGGAGCTGCAGCAAGTTCACCTCACCTA

          TGCCGATTTCGGTCGAAAGCCTACAGGTACTCTACTGATGGTCCATGAGTTTCAACCGAA
          TGCCGATTTCGGTCGAAAACTTACAGGTATTCCACTGATGGTTCATGAGCTTCAACCGAA
          TCACAAAATCGGCGGAGAAAGTTCAGGTGGTCAAGTCATGGATTTAGAGCCGTTACGGGA
          GTGCCATGTATGCGGAAAGGGGTTGACATCTGGCGTAGTGGTTCATAGAAGTCAATACTA
          CTGTATTTTGAGCGAAGGACGCACATGCAGCACCAATAGAGCTTCAGTGATCCTACGGGA
          TTGGACCACTTGGGGGGCTTAAAGAGGTGTCCTGGGATCGGCTCCAGAGCCCAACCAGCA
          TCGCTAGCAAGGCCGAAAGGTCGCAGGCAGGCCTTCACAAATTCCTCTGCACACAAGACA
          TAAGGACCTAGGCGGACCACGCTCGGACTGAGAGTTAATAGTGGGTGATTTACTATAAAA

          CGTCTCGATTTGTAGACAAGACGCGGAGTACGAAGAAAAACTAGGATTATCAAGGATGAC
          CGTCTCGATCTGGAGACACGAGGCTGAGTACGAAGAAAAACTGGGATTATTAAAGATGAC
          CAGCACCGCTTGGCCAAGTTTGCTCGAGTAGAGGTCCAATACGGAGTTACTAAAGTGCGC
          AGATGCAACCCGGTGAAACAGCTCAAGAGAACAGCCTGACCGGGAGGCAGGATAGGTGAC
          CACCGACCGCAAGTGAAACTACCACGCGTACAATCGCCATCTCGGTACCTTGGCCAGAAG
          TGGCGCGACCGTGCGGAGGTATAAGTTGCAAGAGACTAACTTGGTATTGCTGTGGCAGAT
          ATGAATTTTTCCAGGATCGTACTACGTTAAGTAGGGAGACCGTGGACGGCCAGTAGGATC
          CAGCGGCTGATAAACGATCGCCTGCATGGAAAGGCAAGACCAGCGGCAAGTACTATAGGT

          GGGTCACGTCAGGAAGGTTGTATCGATGGGATCAACCGGTCTATATGGGTGGAACATGAG
          GGGCCACGTCAGAAAGGTTGAATTGATGGAATCAACCGGTCTATACGGGTGGAACATGAG
          GAATAAAGTGTAGCGTGTTCGGCAAATTAAGCCCGTTGCCGCCTATGTATTGGTTTAGAG
          TAGCAACGCATGGAGAGATATGTAAGTCGAGCCCTTTGACATATATTGATCGCACATAAA
          AAACAACGTATGGCGAGTTCCGTTGTGCTAGTACGCTGACCTGAATGGAATGGGCGTGAG
          ATGTATCTGCGTGCAAAATATGTTGGTTGGGCTCACTCTCACACGAGGGTTGTCTGGGAG
          GCCTTACAAGTTGCAGGGGGGCATAACCGTATTTATTGATCTGCACGGACAACATCCAGA
          GCTAGGCAGACGGGAACGGGTGGACATTAATCCCATAGTTTTACCTGTGGACTACCAGAG

          AAGAGACTAATATCGACTTGTACGCAACCTGTCTCTTGTCGCGCTATAGGGCAAAAGGCC
          AGCGGATTAATATCGACTTGTATGCAACTTGTCTCTTGTCGCGCTATCGGGCAAAAGGCA
          GAGGAAGGGAGAATGAACCAGTAGTAAGGTAGTTTCTCTCACTTTCTCGGTCTTTAGGGT
          AGGGAAGTTGCATTGAATTTTATGCGAGGGAAGCTTTACTGCGGCTTAGGGCTTAAGGAA
          GGTATGATAGTAGTATCATCTACACATGACTCTGCCCACCTCTCACGTAAACCTTACAGT
          ACAGGCATGTCCTTACCTCCCCCATAGGGGACTGCGCACTGTTCCCAGAAAACCATAAAT
          GCGTTGGTGGGGGTGCCCTTCACGGAGGGGAGATATCACCCGTTTCAAAAACTCCCGCCT
          AAGGTGGTCACAATATCCCTCACGGCGAACCCTCCCAAGTACTTAAGCGGGCCTTCGGAT

          AAGTCGCGCGACGAGATATCTCCGGGAACACATAATAGTA
          AAGCCGCGGAGCGAGATATCCCCGGGAACACATAATAGTA
          TTGTCGCGTAGCATGTTAATCCCCGAGATGCTTCCGCTCG
          CCTCAGTATAGCATGTCATGCTTGAAGGCATCTCTGCCTT
          CCAGAGCGCAGCGAGTTTATCCTGGAATTATCTTTGTATC
          TTACCGCTGTATGGGTTGTCCTAGGGAATCTATTTGCTTG
          ATATCCGACGGCATCACGCGCCGGGCACGAAGCTCGTACA
          ACCTATCGCCCTAGGCTATCTTCAGAATCAAAGTTGTACG

