 8 1000
t1        GCTCAGCTCCCCCGTGGTTTGAAGCTATGCACCGACCAAGATGAGATGGACCCAACCGTT
t2        GCTTAGCTCCCCCGTGGTTTGATGCTATGCACGGACCGAGATGAGATGGACCTAACCGCT
t3        ATTCCGCACCCCTGCGGTTTCTAATTGTTCACAAAAAGTGTCGGTTCGGTCCTACATTGG
t4        AGCGAGCTCTTCGGAACCTAACACTAATGCACAACTCGTTAAGGTCATCTTTCAGATCGA
t5        AATCTGATCGTTTACCTTACGTCCAAGACTACAAGTTTGTCCGAACTGATGGCCAAAAAG
t6        GCCACGCATATTCGTGATAAACGGTAGAACACGACCAGAGTTGTACCGCTACTTACGACT
t7        GTTGGGCCAAAATAAGACCAAATAGTGTATCCATGTTTGGGCGGCGTGATCACTTGTACC
t8        GCTTACCCTGCCTGTCAGACGAAACCGCGTATGTATTCAGCCGCAATCATTCGTGATAAT

          GAGCGTTAGCAATGGCCTCGATGGAATCACTTCCTCCGGTTAGGGTGCTACCAGATCCAT
          GAGCATTAGTGATGGCCTCGCTAAAATCCCTTTCTCTGGTTAGGCTACTATTAGGTCTAT
          TTGTTCTGAATAGGACCGTTACCGACTTTCTCATTGGAATCCAACCAACACGTGTTTTTC
          AGGTTCCTCATAAGACAGGATTCAATTCACATACTATCATCCAATCGGGCAGTAGCCCAC
          CTGTGTTCGGGCCATTTGAGCTGGTCTAGTTCGGGGCGACGCTGACCTGACCTGGTTCTC
          AAACCTTGAACGGTGCGAGATCTGGACATCGGTTATCTATCTATTCCCATCACGGCTAAT
          CGAAGCCCTGTGCGCCATCTTTCGTTTGCGTTCTTGTATTGATGCTCACGGGCGCCTAGT
          TGACGCCCGAATGGGCCATGTCTTAACTTATATGCTTACACTCGCTGCGTCACAGTCCAC

          TCACCTTACCTGGTTCCGTATCCCGACTCTAGCGGTACGGGTATGTTGCGTAAACCGGTA
          TAACCTTACTTGGTGTCGTTTCCTGAATCTGGCGGCATGGGCATATTGCGCAAATCGGTT
          CTACGCCATTCGTGCTGTCGCGCCCTTTTAAACTTAGCTAGAATCTGTGACCTTCTGCTG
          CCGTTGAACATGGTCTACCTTGTGAGCTTAGACTCAACCGGTCCTCTATGTCACTTGATT
          TTGCATTGCACTCAGATACGGGTGGGCCTCGATTCAAGCGTACACCTCCTGCACTCTGAA
          CTGGCCTCGTCAACTTAGAGAGCAACCTGAGCTACGAGAGACTGTCCAACCTTCCCAATG
          AAGGAGAAAACTGCCTAGCTAGTTGGAACTAGTACGACGGGTCGCACGTGCGTCTAAACC
          GAGCCGCCTATAGTTAGTCTTGTCAGGTTAAGCGTCTCTGGATCTTCATATCCAAAACGC

          ATGAAGCCCCCTAGTGTTGAGGGGCACGGTTAATCCCATAATCGCAATCCCTTCGCTGAC
          ATGCAGTCCCCTAGTGTTGAGGGGCACGGTTAACCCCATAATCGCAATTCCTTCGCTGGC
          GGTTTTAAATCTCTTTCCACAAGACGGTGTGAAGTTCAATCTCAAATCGCCCATAGTGGC
          AGAAAACACTACCCTTCCAAAAGCGAAGGCTATCGCCTTTGCTAAAATGGGACTACCGTC
          CAGTGTGACTCTTCTCCAAAGAGACGGCACTGGCTAGTTCGCCTAGGCGCCAATAGAAAC
          GGGCACCTTCCTCTCCTGAAACGTAGCCGGAAGCCCGAACGTCGTAAAGTAGTAGTCACG
          GTCCGTCTCTCGAGTGTGTAGGGGTATACTTCCCGCTCCCGAAGGGCCGATTATAACGGA
          GACAACTGCGCTTCGCTTCGTGGGTATTATACTTCTGACTCCCATAGTGACCGACAGGCA

          ATCTGGAGTTCTGGGCGTAGTTTGACCAGCGGTTCCAGGTACATCATCGTTAAAGTGTGT
          CTCTGGAGAACTAGGCGTAGCTTGACCAGCGGTTCCGAGTACATCATCGTTAGAGTGTGT
          GCTTGTTTCTTTGGACGCCTTCAGCATAATTGCTATGGGGGAAACGCTTTCAAACGATCC
          GCCTTAGGGTCCAAGCGAGCGTCGTCCTGAACCCTTAGGCGCATCACTGTAGATCGGCTC
          CACTGGATGCCAGTGCTACCCCTGCAGTCTCACATATGATAGTCGGACGTCATATGAGTT
          GCTTGAGTGTGAGATCGATTTCTGCTACATTACTCCATCCCAAGCGATGATACTAGGTAT
          GAGTTCACAGTCTAGCAAGCTCTCCCCAGGCGGGCTCACTGCACTGCCGGCGTGACGCTA
          GAATGAATATATTAGCGGGCCTATCCCCAATCCTTCCCAAGGGAGGCTATTATCCGCGCT

          CCTGCCAGCTAGCACCGAAGCGGGTCATGCCTCTTTACTGTCATCTAGAATTTGTGTACC
          CCCGCAAACTAGCACCGAAGCGGGTCACGTTTCTTTACTGTCACCTAGGATTTGCGTACC
          AGCCTCCCTGACCGTGTCCGCAGGCCATGTAAGTCTGACGTTGCGCCGAAACTCGTCACT
          AACGGTTTGCAATGTGGTAGCGTCGTGCGTCCAACTGTGAGGGTGGAGAAGAACTGCGCG
          CCCGTAAGACGATGTAGTTACGCTCTATCTTCTTTCAGCGGAGAATGGAGCAAGTTCGCT
          AACCCCAGTTAGCGCGACTTTTTACCGCGCGCCTTAACATGAACAGGGTAACACCTAGTG
          GGACAGATTGATAACGGAAGATCCCTATTGAGTTCTTATAGCACCCGCAGCACACCTGCT
          GCTGTTATGTCGAGTGGTCTCGCGTGGGCCCATACTGTCACAGCACGAGATCATCTTGCT

          TCACCGCATCACCTTTCGCGCCCACAAACTAGTCACTCAGCACTCAACATCACACTTGAT
          CCAAAGCATCACTTCTCGCCCCTGCAAGTTAGTCATTTAGTAATCAATATCACACTTGAT
          CGAAACCTCGTTGTTAAGGATGTCAGAATTAGACGCGTGACGTTTGAAATAGTAGTTGGT
          TGGAATACCCTTATTAAGGCTATTCGTTATGAAAACTCAGCATTCGCTTCCGTAGACGGG
          CGGTCCTGTGTCCCCCAAATCTTACAACTATAGTGCATTGTATTGCACATCCCAGGGAGT
          TTGAGCTATTCGCTCATAGTCTTACGAGCTGTGCTAGCGGGTACCTTCATTATATCAAGT
          CAATAATCCTCAACCCCTGCTACGGGACTAAGTTTTGAAGTACATGCCCTCAATAATTCA
          TGGGTCACTGCCCGCCAGGCTCTTGGTGCTGGACTCTAAAGGTTCAATACCGGGTTCAAG

          TTCACGACTGCCGGCATTCAGGGTTCATCTCCCCAAAACCATTTGACTCGGCTCTGCAAT
          TGCACGACCGCCGGCATTCCGGGTTCTTCTCCCTAAGACTATTTGACTCGGCCTTGCAAT
          TACACATACGATGGCCATTGGTTTTTTTACTAATAGACTTCTAAAGTTCATCCGTGGAAT
          AACGCCCGTGTAGACCTTCCGCAGTAGACCCGTCTCGATCCCAAGGCAGTTCCGCAAAGT
          CCTCCTTATGTCAGCCCATCGCGTCGCCTTGCCAAGAGTCTCATTATCGAGTCATGGTAC
          ATGTAGAGAACCGGTTTGACGGATTGTTACGATTAGGTTTTTAGCGCAGGAACCACAACC
          CGTATAAACACCGGTCCCCCTACCTATCACTTTTTGACTATGAGTAATGTTGCTTCTTTC
          TACTGGCCTGCCGAGTTCTTTAGTAGTTCCCCCTTCAGTATCAATCTTGTTCAACAGTAA

          ATGTTCGTACTGAAGGTTTTTGGCACTCATAAGCCCTCGGATATGTCCATATTTACGATC
          ACGTTCGCAGCGAAGGATTTTGGCACTCATAAGCCCTCGCACATGTCCATATAGACGCAC
          CGGTCCGTACGCCGCGCCGTCTGCTACCAGTACTCATCGGGCCCAATACATTCATTAATT
          GAGTTCATGTAGTATGACTCCGGTTTCTGGAAACTATTACGTACTTCACTTTTTTTAGAC
          GAGTCTGTATAGAGTGATATCCAGCTTGGGGAAGGAGTAGAAACGTTACTGCTCAGGGTT
          AGGTGTCTATGCAGGATCTTCTCTATGTGGGAGTACGCACGCATCCTGATTCTCTCATGC
          AACTCCGTATGCAGCAACCGTGATCCGAGACACCGAGCACATGAGGTAACCCTCTGGAAC
          GAGCCAGCCTAGAGCGGCTCCGTTTAGTCGCTTTGAGGGTGTTCATCAGTAATTGCGGGT

          AACGTCACGACTTGTGATCGAGACAGGAGCTAGCCCTACGGCGTAATGTTTCTCCGGCCG
          AACGTCAAGACTCGAGATCGAGACAGGAGCTAGCCCTACGGCGTCATGTCACTACGTTCG
          CTTACCACTATAGTGGATTGAATTCGCGTCAAGTCGGGCGCTATTACTAGAACGTGTGAA
          TCCGTGCAGACATAGAATTTAACGGGAAACATTTATGATGACCACTTGACTGTCAGTACG
          TCCACATTAATGTCGTCTCATTCTGGGGTTTACAACAACCGCTTCTTTGGTATAAATCCG
          GCTGCAAGGCTACTAATTGAGGCCGGGAGCTATCACGTGCGAGGCATCGAAGTCTCTTCA
          AAGGCCGTACTACTGGATTAAGCTGAGCCTCACATCCTCCGTGCCAAGGCCGGTTCTGCG
          CGAGTTTAGGAGCGGGTTAAAGAAAAGGGTTGTCAAGGTGTGGCCGCAATCAGAGTCGTG

          CGGACTTCCACTGATGCAGGCCTACTTGAACGTGGCATCAAGCTATTGGTTATTCGGTAG
          CGGACTCCCACTGATGCAGGCCTTCTTGAATGTGGCATCAAGCTATTGGTTAATCGGTAG
          CAAGTCCGCACTGTAGAACGACTGCAAAAACGGGGCAGCCCACTGTCAACCGTGTTTGCG
          TGAGGGATCCCCGTCGTCGGCTGGGGGGCGCGCGGCATTCCACCACACCTGGTGCTAATA
          CAACTTCTCCATGTAGTGTTCTAACGTAACATTGGCCAATTATTATCTCGTGGGCCTCCG
          CCAACAAAAGTTCTACGAGCTTAAGGAGTAGGCGTAACCCTAATATCATCCAGTTCGTCA
          CTTACCTCTACAGGCATGCTCTACGAAGCCTCTGGCACATTACCGTACTACAGTCTAATG
          CGCCAACCTAGTATGTAGCACAGGAGGCCGAGCGAGGTCACCTTCTTCGGAGGGTTGGGA

          GAAATTTCTTACCTAAGGCATGAGCTAAAATCTCAGACCGTATTCACTTCACATTCGAAT
          GAAATTCCTCACCCAAGGCATGAGGTAGGGTCTCAGACCATATTGACCTCACCTTCGACT
          GGGCGTTTTTCCCCGAGGAGTGAAATGAGGCCTTTCGTCTGATAGACCCGTAAGGAGTCT
          AGGATTCTTCGCATCACGCGCTCCGCGCTGGGGGGGCTTGTGGTAACCCTGTATGTGGAT
          GAAATTTTACGCTTCATGCACCATGCGAGGCTGTTGCCTACATGCAAGTCATATAGTACC
          CATATTCTTCGCCCCTCGTATATATAAGAAGCAGAGACGGCATGATTCTCATCCGCGATC
          AGCAGTTTATGGTTCTAGTGACAGAAAACGGCAAATAACTCAAGAACATCGCCCATTTGC
          GAATCCATATTCCTGCATTCGCTGACTCGCGCCCGAGCAGTAATCACGCGGGACATGCCC

          TCAATGAATGGAACCATGGGATATTTGGCTTAATAAGGGAATAATGCGGCCCCGGTGTGC
          TCGATGAACGGAATCAAGGCATATTTGGCATAATAAGGGAATAATGCGGTCCCGGTTTGC
          TTGATAGGCAGTACCTTGAACTAATTTTTGTCTTAGGGGAGAGGCGAAATGAACGTTGGG
          TCATAAATAGGAATCGTAAAACAAATGAGAAGACAAGCGCACGGTCCAGTCTTAACAGAG
          TTTTCGGGCATAGTCGCGCGGACAGTAGTTCGTTAGCGTAGGTGAGAGGTATACGTCGGT
          GTGATAAATCGGGTAGCCGGTCTCTTCGAGGGGCAGGGTGGTAAATAGGTTGAGGTCAGT
          CTGACTAATTACACTGGCGCACTGTTGAGGCTAATAGAGTGCGGTGCACACTCGGCCTTC
          TACTGCGACAAGGGCGGCGCTTGGAAATCCCACGATAGAACTGAAGGCGCGTCGGTCGCG

          ATGCTATATCGCCAACCGGTTTCACACTTTGAAGCTTCACATGTGTATAGAAGGGTTACA
          ATGCTGTATCGCCAAACGGCGTCACACTTTGAAGATTCACATGTGTACAGCAGGGTTACA
          AGGGCGGATAGTAATTTACGGCGAGTTTTATGCACGTCGTCCGCGCGCGTACAAGAGAGT
          AGAACGAAAAGATAAACAAGGAGCTAATACTTATCTTGGGATACTCGGCTAGTTTAAGGT
          TCGTAGGGCCACCACCAAAAACCATTCTCGTAACATTGACTCACCGCTGTGGTAGCAGAA
          CTACTGGAGAACCCGAGGGAGTTAGCTCCTCTCATTCCACATTTACACGTATGGAGGAGA
          GTTCTTAAACATGGGCCCTGGTTATCGGTGGTAGAATAACATGTTTTTGCAATAACAAGT
          ATTCCAAATAGCCGGTATGATAAGCTCTCGTCGGTTCGAAGGGAGTATGGGGAGCCGCAG

          ATGCGCAAAAGTATTCTGCCCACCTGCTAGCCTAGATGCGCACTGTTTGACGCGCATCCT
          ATGTGCAAAAGTATTCTGCCCACTTGTTATCCCAGATGCGCACTGTTTGACGCGCGTCCC
          ACGTATCAGGCCGGGCTGTCAAACGGTCAGTCTGTGCGCTGAAATACCGGCGCGGTTGTC
          CAGGCTGAATGTAATTAGTCGTATGGATGGCCTACTCGAGGGTGGGTGATTAAGCGTATC
          GGGCGCAATGGGGCATCATTATCCAGCAGGTCCATCAAACGTTCATAGAATAGAGAGTTT
          GTCCGTATCGACGTAATGACACATGGATCGCCTAATCGAGAACCGCTTGTCAGTGGTACT
          ATGCGTCTTAACGATCTTAGATTCCTGAGGACGTATTCCGAGCTTATACCAGGGAGGGTA
          ACTCGTCACTTCTGCCCTCCTTATGGTTGGACCTGATCCAATTCTAGCGGGCTAGGGGGA

          CCTACCACGGTACGTTAGGTCATGAGGCGGATGGGCCCTGACAGCTCACACAACTTCTAT
          CTCACTAGGGTACGCTAGGTCATGAGGCGGATGGACCCTGACAGCTCGCATAATTTATAT
          TCTTCTTCCCCAAGTTAAGTGTTGTGATAAATGCGCGCAAACCGTTTGCATAGATTGTAC
          TGTCCTTGTCTAGCTTAATACGTCTGATGAGGGCACCTCCACCACATGAATAAATTCTGC
          TACTAAATACAACCCTCGGGAATCGTGTGGCAGTGCTCTGATGGCCGGTTTATGGGTCAC
          GTGCTAAGCTGGGGTCGTGGGACCAGAAGAGTACACTTCCCCCATTAACGAAATCTTCGC
          ACTCTCCATTATTAGACCAAACATGGACCAAGATAGCAAAACCGCGAGCACAGAGAGTAT
          CACAGTATGTTTAACCAATACATGAGGTACTATCATCTAGAACTTCAGACCAGAATGGCA

          CGAGATTACCACAGCTGCTGAGCGAGTAAGTCATTTAGAG
          CGAGAAAACCACAGCTACTGAGCGAGTAAGTCATTTAGTG
          TGAAATAATCTTCCTAGCCCAGCCCATTACGTACGGCGAC
          TAGTAGCCACAATCCCCTGAGGTGCTCGAGGCTGAATGAT
          ATGATCCGGTATATTCCCCGTGAACACGACATACAGAGAT
          CATCGAATGTGATCACTTATTGCCTGAGCGATGCAACCTC
          TTAGCTGGATATTCAGCCTCGCCCGAAGTGTCATAAGGGT
          TACCCCTAGTCAATCTCTATAAACTGTATGGAACTCTGTC

