 8 1000
t1        GGTTCAACTAAAACGCGAGTGCGAAAAACCACATTCAATCGTATTAAAAGGTACCCTCCC
t2        GGTTCAACTAAAACGCGAGTGCGAAAAACCACATTCAATCGTATTAAAAGGTACCCTCCC
t3        AGTCTGGCTACCATGCGTTCGCCAAGATGTGTCCCCAGTCACATCAAATGTTTAGCGCTT
t4        AGTCGAACTCACCTATCATCGCGTAGAACTGAGTCCGAAACTGTCCCCAGGTCATAGATG
t5        GTCCCGACCCGACCGGAACAGTTTCCGATCACGGTCGTTCTCATTCCCTGGCCGTTTGTG
t6        AGTTTCATTGCGCGGGTTTAGAGTTGTGCTAATGAAGTCGGGGAAATCTGGATTCACGGG
t7        GGTATAAGTGTGTTGGCTCCTCGAAAGGTTTCCAGTTCCAACAGTCCATCACTCCAATTG
t8        ATTAGCTTTGTGCTACTCGCATCATGGGTCGTGGGCAGCCAGAGTGCCCAACCAGAAACA

          TCGTTTACCTACTTAGACCTTGCGCTCCACTGTTACAGTTGACGTATAATGACTTGCGAT
          TCGTTTACCTACTTAGACCTTGCGCTCCACTGTTACAGCTGACTCATAATGACTTGCGAT
          ATGACGACATTGCTAATAAGAGCGCTGTCTTGTTGCCAGTGACAGTACGTCAGCCCCGAC
          ACAGCTGCTTAGTGCTCATGCGGGTTGTTTTATAGTCAATGGTTGGTTTAAGGCGATAAC
          ATTCCTACTGCTCATGGGCTCCTAGATCCTTACAGGCCAAGACCTACAGGAAAGTCTGAA
          ACGGTCTCGCTGTCACCCCAGTCGGTCTTTTCTAGTCAGGCGGATCTTGCCGCCCACAAT
          CCAGTCAAATCAGTCTTGCTATGATCACTCTGTTATCAAGGGTGGATTGTAAGCCGTGAA
          ATGGTGCCGCGGACCGCACCCTCAGGTTCCATTCGCTTACGCTTGGTTCTTAGTCCTGGA

          TTCCCATCTACTGGGGCATTGTTGTCCAAAAAACCTCATCCAAGGCCGATCATTTGTAGT
          TTCACATCTACTGGGACATTGTTGTTCAAAAAACCTCATCCAAGGCCCACCATTTGTACT
          TACCCATACTCATTAACATCGATTTTCACATAGACAGATACGAAACCTGTCGGATGCGGA
          CTCATGCGTCTAGGAATATTTGGTCCTGGGATGAAGTATCTAGATCTAGTCCGTAGCGTC
          CATTAACATTAGGCCGTACCTACCCCAGTCTAGACGCGAATGGGACAGACTTACTGCTTC
          TTCTCCCCATAAGGAGCGCCTCTTCCAGCCCAGCCTTATACAATATTAGTTAGTTACGTT
          TGTGCATATGCATGTATCTTCCAATCAGAAAACCCACTCGTGGAAAACAGTCGCAACGGA
          TTTGTACTATCCGCGGAATTTACCCAGATTAGGCTTTATACCACGCACTATTCCCATGCT

          TTCAGGGCGCAAGAGGATGAAAAATCAAACTAGGCGCGGTCGCTCGGGTGAGAGGGGCGA
          TTCAGGGCGCAAGAGGATGAAAAATCAAACTAAGCGCGATCGCTCGGGTGAGAGGGGCGA
          TCAGGAGCACAAAAGAGTAAAATATATTGCTAAGCGTGATTGACCAGGGGGTTAATGTAA
          TTAAGTGGATGACGGTGAAACTTCTCAAGCCTGTAGAGATCGGTCAGCGGGGCCGATTCA
          CCTGGAACACATTCTAGGAAACACCTGACTTGCTCTAGAGCAGCCAGATGAGCTGGATAG
          ACTGCCTTGATAAGTAGTAGTGCATCCTACCGTCCATAATAACACGGGTGGAATGTGCGA
          CTCAACTTGTAAAAGACCAAAGTCTCAATATTGCCATGACATGTTAAACGACACGGATAG
          AAGTACAAATACCCCAGTGCACTGAAGACTCAGAGATAAATGTGCGTACGGAGGTGTTAG

          TGCCGCCTGGGATGGCGATGTAACTACAAGGCCTTCAAGTTTCGGAAAGCCAGCGGCTGC
          TGCCGTCTGGGATGGCGATGTAAATACAAGGCCTTCAAGTTTCGGAAAGCCAGCGGCCGC
          AACCATCTGGGACGGCAGTGCATTTTGACGGTTTTCGAATTTAGAGTACCCGGCCCCTAG
          AATCTTATCATAGCTGGGCGAAGTTCGAAAATCGTTATATATGGCGTGATCTGCAGCTCG
          AGCATCCCTTAACGGAGATCTCGCAACGGAGCGTTTATGCCCGGGGTACCTAACATGGTG
          GGCGCTACTTTGTCAGGGCTAGCCCATGGCGTTCTTGGAGTCGGTGCACCTAGCGTAACG
          CGCAGTGTTTTACATCCAAGTGGCCCACAGGTCTCAGTGTTTGAACCGTGTGATTAGTCG
          CAACTCTGAAGAGCCTAGCTACGCAAGGTGAATCTTGTGTTAGGGAAGCACAGGAACTCG

          GAGATCACGTAGCACGACCTGATTGTAACTATGGTAACGGGGGTTACGTGAGTGCTAATG
          GAAATCACGTAGCACGACCTGATTGTAACTGTGGTAACGGGGGTTACGTGAGCGCTAGTG
          GATACCGTACAATTAGACCTGATAAGAACTGGAACCACGGGGTCCCTTAAAATGTCAGTG
          GATGTATTATACCCGACCGAAAAACAGGATGTGTGAGCAGAACCTACTCAACACTTGAAG
          GGGGCTTTACTGCCTGAAGTGGCAAAGGGCGCGAAGGGCGGTGTTTTGAACATGGAAGCG
          AATTATTTACGACCGATACAATTCTGCAGCGCGGATGCCGGGGTCATAGTAAATTGAGTA
          GGAACCTTCTTGAGTCTCGCCGTTGGTACTGGGGGGGCTGGGGTCATAAATACGAAAGCA
          ATGAACTCAGTACGTGTAAAGAAGCGTCGGACGGCGCCTAGTTTCTCTAGAAATACAAAG

          TGCCAGTATTCTCCTGTACGACTGATCTCCTTCTACGGCCTTTGTATGCCTCCCAAGACA
          TACAAGTATTCCCCTGTACGACTGATCTCCTTCTACGGCCCTTGTATGCCTCCCAAGACA
          ACCCCGTTTTCCTCTGTTCTAGCGTCCAACTGCCCTGGTCCTCCCATGCCCGTTAAGAGG
          GCTTCATCGACCCGTGGAGCGAAAGGCTGCTGACACAGTCCTTGGGGGGTGGCCAAGAAT
          AATTCGTGCTAATCCGACCTGGTCGGCGCCCAGCATGGAGCTAGGACCACGACCGAGAAC
          AACCGAGGTTGCTGTGTCACTGACGGTGCCCGGCATGGCACTGGGTTGTCGCTTGCGGCG
          GACAAGGAACGCTTGGGTATAAGAGCCTTCTCGCGTAACCCCGGGTAGTCGATCGAGCGC
          TTCAAGCATTCGATCTGTACGAACGAGTCCCGGCACGTGACGGATGCGCGGGGTTCGAAG

          TCAGAGGAATTAGGTGACCTTTCCTAGATACGGTATGCAGCGACATTAGAGGGCAGGATT
          TCAGAGGAATTAGGTGACCTTTCCTAAATACGGTATGCAGCGACATTAGAGGGCAGGATT
          TCACCGTGACTAAGTGTACTTATCGGTAGCTCGGCTGTTACGGGGTAATAGTTCGTAGGT
          GTATGAAAACTAGTCGCTACGAAATAGGCTTCTGGCGCCACTTACCCGTCGCACGTTCCC
          TCGGGGCAACTAGCATCTATCCACTAAAGACCCCCCAACCAATCTTGCTCGTGCGTGGCG
          GAAGTTTCACTTCTCATTGATGTGCTCATTTGACGCGATGGGCAATTACCGCATACAGCG
          CTAAAAATCGTAAGTGCCGTACACTGGGACTGGACTAGGATGCGGTCACTTTGTTCAAAG
          AGAACAGCACTTAGAGCCTTTGTTTGGTATTCGCCCAGGTACGTCAACTGGTTCTTTTCA

          TAGTCGTTCACTCTTGAAGAGGAAACCTTCGCGAATATAATATTCTTAGGTCGGATATTC
          TAGTCGATCACTCTTGAAGAGGAAACTTTCGCGAACATAATATTCTTAGGTCGGATATTC
          CAGATGGGTACCCTTGAAGTGTAGGCTTTTGCGCATGGAGTACCTTGAGGTCGAACACCC
          AGTTAGGCTCCCCCTGGTTTGAGTAACTATGCGCGGGCCACAATCCCACTGTAAATAGCG
          CCTCCAGCCACCGCATCAGCGCAAGTCATTGTATGAGATGTATGATTGCGGATAGTATTT
          CGGCCCGACGCCCTCTATATGGGGATCGGTGTGAGAAAAGCCAGAAAAGGGTTCAAGTTT
          CATTGAGATGCCATTGATGGGCGGGGTTCTACCTCCGGGGTACCTCAATTAATCAAGCTT
          CGCCTGGGTATTTCTGTCGTCGTGAGTCTTAGGAGTGAGTCTAAATGACAACCGTGACAT

          GTAGAAATCAACGAATCACAAGATGTTCCTCAGATATATGTATCAACCACAACAACTCGG
          GTAGCAATCAACGAATCACAAGATGTTCCTCAGATATATGTATCAACCACAACAACTCGG
          GTTGACTTTTATGGAGCATTTCGGGTTCATCAAACTCGAGTACCAACCTAAGTCCCCTGG
          GCAGGGTGACGCGATACGGCCACGCGGGACTAAACCCGTGTCGTTACCGTAACTATCTGG
          GCAAGCGGCCCTTGCGGCTTCATGCTCTGGTAAACCTCATCACCACATGATGCCAAATAG
          GCGAGGCGTACAATAATCTGCCTACTAAACGTACTCCTCCCTTGAAGTAAGATTACCAGG
          GTTAACCGTGTCTAATGTCGTTCGCAAAGCTTTAACCCCCCGCATACTGACATACTAACA
          ATTGAGCGATGCGAACTCCAGGCACTTTCCTCGACCGCCAATCGATCTGGATTTGAATGG

          GAGCCGTCCTCACTCGGGTCCGATTATTTAGCTGTTTCAAAGGGCAGATCTCGTGCTTTA
          GTGCCGTCCCCACTCGGGTACGATTATTTAGCTGTTTCAAAGGGCAGATTTCGTGCTTTA
          ATGCCCAGCGGGCATGGGCAGATTAATTTCACCGCTACAAGGAGCTGGCCCTCTACATCA
          GCCCCACACCCTTCCGGACAAGCCTGCTACTGCGTCCGATTCAGCTTGCCGTACACTCCC
          TCTACGGTCGCCATTGTACCCCTTTGAGTCTGCGGGCCAGGAAGATAATCTTAATTATTA
          CCGTACCCAACCGTGAGGAGAGCTCCCCACTATGCTTAAAGGTTGGTACCCTGGATTGGA
          TCATACTTTTCGCCTGCGCCAGAGTCCTATCGTGTTCAGAAAGCAACATCCAGTATATCG
          CTGGCGATCTGAGCACAGCCTAACTCCTCCTCCGTTAATAGTTAACCATGCTGCACATTT

          CGTTCAACTTAGGAGGGAGTGACCCAACCACGCCTAGATTGCTTGTAGAGTGGCGCATGA
          CGTTCAACTCAGGAGGGAGTGACCCAACCACGCCTAGATTGCTCGTAGAGTGGTGCATGA
          CGTGCAACCTAGGAGCGAATGCTCCAGTCTCGATGGAGTGGTACGCTGCAAGACCTATGG
          TGTCCGAAGCTTGAAGCAAAGATTCGTCCATGCTGAGCGAGCGAAAAACCCTCTGAAAGT
          TGTCAAATTTAGGGAGCAGTGGGATAATAGTAATTGTATGTCGGGAAGCACTATATTCGG
          AAACTGGCCGAGTACATAGTAGTAACCAAAAAACATTCTAGTGAGCAACACGGACCGAAT
          TATTCCACTAAGACGGTAGTTCTTATCGGTTGCCAAGGGTAAGCGTTCGGGGACGCGTCG
          GGCGTGACATGGAAGGGCATTGCCGGAGTTTGATAAACTCGGGAGTAATGGCACACGTAG

          GCAATGCGTACACGGGCAAAGGGTTGGCATTACTGGGTAGCGGCAATTTCGAGGTCTAGA
          GCGATGCGTACACGGGCAAAGGGTTGGCATTACCGGGTAGCGGCAATTTCGAGGTCTAGA
          AAGAGGCGTCTGTGTGAAGTGTGCAGGCGTCGGTTGCTAGCTGGGCCCTTGAGGTCAAGA
          ACCTGTTAGCTATGCTTTCTTGCACGACGTCGCTGAGCACCCGAATTAACGAGGCATCCA
          ATGGATAGATTGCGTGCAGGGGGGCTGAACTGGTTAGGCGCGCAGTCCTTAGGGTCACGT
          TAGCGATAGGATAGCCGAACGGGGCATTATCTACATGCATTAGCATGCCTGTAGATCAAC
          AAGGAACGTTTATTTGCTGACGGGTATGTTCAGCGGATTACTAAGACTTTGTTTCTGAAA
          GAAGCTTGTCTGATTCCCATTGGTTTGCCAGCCCGAACGACACGCCGACTGTTTAAGCAA

          TCGTCAGATTCTTTAGGTCGGCAGTGACGAAAACGCTTACGGCCATTGACAGCCTCCAGC
          TCGTCAGATTCTTTAGATCGGTAGTGACGAAAACGCTTACGGCCATTGACAGCCACCAGC
          CGGATGGATGCCCTCGACTAGTAATGGCGAGACCTCCTAAGGTTGTTGACAACTGGCGAC
          TGAGTGGCTCTATTCGCTTAGCTGTGACAAGAGCCCCAATAATCGATAACAGGTATAAAC
          CGGCTAGCACACGTTGCATGGCTGTTTCTCGCGGACCAAAGCCCGAGGGAGACCAGTGGT
          TACACGGTTCATACCTATCCGTAGGGTCGAGAGTAACCGCGAAAGATGGCGGGACATATC
          CTGTCAAACAAACTCATGCAACAGAGTGGATCGTTCCTTCAATAAGTGGCAGGTAAGAAC
          TCGCAATTCGATCCTGCTACTTCCTATAGAAAGCCTTAGGCGCCGTCGGTTATTCCACAC

          GGTTTTTAAATACTGAGGATCCCGTCGTTTGGCCATCAGGGCACCACTCAAATACTCAAG
          GGTTTTTAAATACTGAGGATCCCGTCGTTTGACCATCAGGGCACCACTCAAATACTCAAG
          GGATCATCAATACGAACGATCACGGCGTAGAGTGATCGGGATGCCTTTTACAAAATGACA
          GGACTATACGGAGCGACGATCGAAAACTATCCGCACCAGAACTGAGCTTGTATCCTCAAG
          GCAGCGCGTTCCCTCCCGCTCGCCCTTCATGCTCGCGTAAGTTGTACTCGAGCTGTCACA
          TTATGACATATTCCGTTGAATACGTCCCTCGTGGCCGGCAGTCCAACTATAGTAGTTCCA
          GGTCTAACAACGGCATTAATCTAGTTCTGGGTTTTGCCCAGTGCCGCTCAACCCAGTAGG
          CTTCAACACAGCATACAGAGTCTGTTCCGTAGTTTCGGATTTGATGGATAACCTTCTCGG

          AATCACACCAGCCGAGAGGTGGTGGGGGTTTTTATGATCTTGGTGGGCCGCCGTGTACGA
          AATCACACCAGCCGAGGAGTGGTGGGGATTTTTATGACCTCGGTGGGCCGCCGTGTACGA
          AATTCCAGGAGCCAGGAAGCAATCGCGGCCTTTATCTCTTCGGCTAGCAACCGCGTGGGA
          CTGCACGTTAGTACGATGTTCCAAACAGTATCAGCGGTACTAGCTTGCAGAACTGCAAGA
          GAACACGCGTATACAGAGTCCGGGACTCATGAAATGTAATGAGTCTAAAGCTACGGGACG
          CGTCGCGATTAGCAAATAATCTAAGGCCTTTCCACGGGACTATCCTGAAACCATACCCCC
          GAACATGCACGCCCGTGGGCTGAAGGTTGAGAAGGGACAGTGCCGTATATGAACCGATTC
          TTAAAGGACTACAGGGTGGCGAAAGGGATTTTAGTTAATTCAGTTTGTAACTCCCAGGTT

          CGTCGCCTAATACCGGCCCAACCGAAAACTTGTTATCAAG
          CGTCGCCTAATACCGGCCCAATCGAAAACCTGTTATCAAG
          CACTTTTTGGTGCGAGCACCACTGGCATTTTGATACCTGG
          AAGTCCCCGTCACGCCCTAACCCTTGAATATCAAATTGGG
          TACTGAGCAGTGAAAAAGTTTCATAGGATGCGACGATGGG
          GGGCGCCTGACCTGAGTCTACACTCTGAGTCTATTAAAGG
          TCATTATTGGAGTAAACACGATTGCGGACATGATGAAGGG
          GCATATTGGCGAGAATCGCGTTTTAGGTATCCGGCACGGG

