 8 1000
t1        TAGCTGGGTCCTAGTAAATTTTCTTATCGCAGCGGGGACAAGGTCCTTTGAATGCAAGTA
t2        CGGTTGAATTAAAGTAAATTTGCCTACAGCAGTGGGGCCATTGTCCTTAGAACCCAAACA
t3        CTACTGGATGATTTCGTCAGCAGAAATCGCGGTGGAGGAATAAACCATGGGTCCCAAACC
t4        ACAATGCATTGTAGCACCGGCGAAAACGACCACATCGACGTGAACGTCAGGATCTGAATA
t5        GCGCTCAAGAGTAGTCTCGGTAAAACTAGCAGAGTCTGCATGAATCTAAGGATCTGATTT
t6        GCGCTTTATAGTAGTCCCGGCGAAAATAGCAGAGTCGAAACGAATCTAAGGTCCTGATTT
t7        TCCAGATATCTAGGTGAAGTGGAGCACAGCAGTATAAGAATAAAGGTGGATCTTCACGCA
t8        TGGGAATATGCCAGTGTAACCAAACGCAGCAGAATGTGCCTGCAGGAGTATCAGTGGCTA

          CAATAGACGCTATCGTGGCAGCGGCTCAAGGTCTAGGTTGTAGACATGCCATCTGGACGA
          CAATAGCCGGTACTGCTCCAGTCGCATACGGTTCAGAATATCGACGTACCGTCTGGATGA
          CAACAACTGATGGAGTTGGGGTGGCTCTCGCTTTCAATCGTAGAAAGGCAACTTGGCCAT
          TTGTCGGCATTGGAGTAACATTTTTTGCCACAATAAACCATAGGACCAGTGTCTAAGCGC
          TTAAAGTTTGTGCCAATTTTGTTACATATCCTCCGCATCGTCGGAGCTTTGTCCGCCCGT
          TTAGTGTTTGTGGCGATCTTGTGACATAAGCTCCTCATCGTTGGAGCATAGTCCACTCGA
          CAACGAGTGATGGGGTTGTGGGCATTTGCGCCGAACTTCGTTTACCTTTTGTCGCCTAGG
          TTACGAGTGGTGGAGTAGTTAGCCATTGCGCCGGACACTGCCCAGTTCTTGCTGCCCAGA

          TCAAGCTCAAGATCCCGTTCATTAACGGATGACCTTGCTCATACGATATCCATTTTATTT
          TGGAGCTCAAGGTCCCATTAACTAACGGATGAACTTACCCGCACGCTACCGGCAACATGT
          GGAAATTGATAAACTGATGAGTTGACAGATGAGACAGACTGTATAAGGCTCAGCTTTTTT
          GTGAACCGGAGGCCCTCTAACCCGGCGGGCGAACTTACCCGCCAGGGACCCGGCTGTTAC
          AAGGGGCTTTTATCCCTTCACCTAGCGATAGTTTCTGCGCGAATAAAATTTTGCCTACCT
          TAGGGCCTCTTATCCCTCCACCTCGCGGTAGTACCTGCACGAATAAAATTTTTCCTACCC
          ACGCGCTCTGAATTTATGTCCTCGCCTTGGTGCTCCGTAAGAACAAAATCCTAGCAGCAA
          ACGCACTTTGGAATTCAGTCCTCGCCATGACGCCCTGGAGGTTCAAAATTTAACCAGCAC

          TACACCTCCCAGAATCGATAAACACTTTGCTTCGTTGTCTTGTCATCAAGGCCCGGGTCT
          TGCGCCTCTCTGGATCGATGAGCACTATGGACCGTTGTCTTGTCATTAGGGCCAGAGTCT
          TGCGTTCTCCCGGGTCCATGTATTCTTAGATCAATTGCTTTGGCATTGAGGCCGGAGCGT
          CGTGTCTATTTGCGGCGGTGGAATCCACAGCCTCCTGCCTCGCCTTCGTGTCTCGCATGC
          TGCGCCCTTTTCGGTAGAAGAATCCCGTCGCAGACTATCTAGATTCTGGTATCAGAAGCT
          CGTGCTCTTTTCGGTAGATTTATCCCGTCGTAAACTATCTTCACTCTGGTATCATAGGTT
          CTCGTCCACTTAGTACGAGGGCCTACGCGGGCCGCCGTTCACTAAGATGAGTCTGTCCGC
          CTCTTCCTCCTAGTTAGGGGGTTTGTGCGATTCGCCGTTATGTAGGATGTGTCCGTTTGC

          GTGTGTGACCGCCTGTTCACAGGCCTGACAAAAATCAGGAGTGGACTATATGAGTAACCC
          AAGAGTGTCTGCATACGCAAGGGTACGACAGAAATCGGCGGTGACTGGTATGAGTTGGAC
          GCTTGTGGCCGCCATAGCGCCGCGGCGACTATGACGGGAGGTACATTATGTAATCAACCC
          GCGCGTGGCCGTTTCACCATAGGGGCGATATAAGCATGGGGTGCATACAATAGATGATTT
          GTTTGAAGCCGCCGTTTCACCGGGGCAGCAGGGACGAGATGTGCGACTTGTAAGCGTTCC
          GTCCGAAGCCGCTGTTTCACCAGGGCGGCAGAGACAAGACGTGCGACATGTAAGCAATCT
          TCGCCTAGTCCATAAGGGGGTAGAGCGGCCACAAACATCCGTCGCTATCATGAGCATCTC
          TTGCTAAGTCCGCAAAGCGGTGGACCTACCGTAAGCATCAGTGTTTGATATGAACATCCC

          ACACCCTCCGCTGCGAGTCGCGCACCCTACCAAGTGAAGGCCCTACAAGTTCTCAGGGAC
          TCAGTCCACTTGGTCAGCCGTGTAACCCACTAAATGGGGAATATACGCGTTCTCAGGCAA
          ATAGTCACCTCGTCGGGATAGGCACTTCAGCAGGTGGGAACCACCTCAGTTCGCAGGTCG
          ACGGTTGCTCCGGTGAGTCAGCTCCTCGGGAATGCAAGAATCACGTACGTCCAAGCTTGT
          AAAGCACCTCCTGCGAGTTATGGATTCTACTTGGTAGGGCCGATTCGAGTCCTCGTGTAC
          AAAGCACCTCTTGCGAGTCATGGATTCTACTTGGCAGGGTCGGTTCGAGTTCTCGGGGAC
          ACACCTAAATAAGTAGTAAGTGTGTACCGGTGGTCTAATTCTGTTTGTGCTCCGGACAGC
          GATCCTATACAAGATATTAATCGGTACCAGCGGGCCATTACTGCTTGCGTTCCCGACAGC

          AGTATCGTTGAAACAGTCGCTAAGGCGTCGTCGAGCGTCCTCGGGGTTGTCAAGGATGTT
          GGCTAAGTTGAGATCGTAGATAGGCAGTCAGTGGGCGCCCACGGGGTTGTCGAGGATGTT
          GGCATTGCACAAAGGGTTGTACTAAAGTCATTGTGCGCCAGGCGTGCTGTCTATAATACT
          GGCTATGCCCCAGGATCCGCGTCCGAGTCATAGAACGTTCTGCGGCTCAACGGAGCCGTT
          GGATACGTTGATGGCGTCGTATTTGAGTCAGTTTGAGTTTTGAGATTCAATACGGCTGCC
          AGTTACGTTTATGGCTTCGCATGCGAGTCATTTTGAGCTTTGAGATCCAATAAGGCTGCC
          AGACAGACACCAACAATCCCGCTAAAGCTGGGGAATGAAAAACGTATGTGTTAGGGTGTA
          TGCCAAACCCTACTAATCCTCTAGGGACGGAGGTAAGGAACAAATTACAACTAGATTGAA

          GGTACCTCGAACCAGCTATCTAAAACGACATGTATATCTCGGATCACCCCTTACTTATAA
          GGCTCCCTGAATCAGCTATCTAAAGGGGCGCGTTAGTCTAGTGCCCCTCCTCATATCCAA
          GATACTCTGTGTATATCTTCAAGAGCAGCGCACCTATGCAGCGTCCCCTGTGGTAAATCG
          GGTATTTATGTCAGTTCATTTAGAGTGGCGCGCCTCTCGTGCGCCATACCCTATAACTTA
          GGTGTTCCTAATATATTATCTGAAATAGTTTATTGCCCGTCCGTGGAATCTTATATCTTG
          GGTTTCGCTACTATATTAACCGAAACAGTTAGTTGCCCGTCCGCAGGGTCTTAGATCGTG
          GGCCTAATTCTTCACGATTTGGATGTATTATAAACCGAGGGTGTTATCATCCTTAATAAA
          AGTCTAACGTTTTATGACTTAGGTGTACTTCAATCTGCGAGTGCTATCACTCTAAATGAT

          TACACAAAGGGCGGCTGTTAGGAACGCTTGCACAAGATGGAAGCGATTGCATGTGCAGCA
          TACACGAGGATCGGCTGCTAGGAGTGATTACATCAGACGCACACGATTGAATACCTGTTA
          TACTCGACAGGTGGTGGCCAGGAATGCTTGTACTAATCAGACATTGTCGGTTCTCCAGCG
          CGCGCGGTGGGAGTGCATCAAGAGCTTTTGCATTCGTCGGAAGTGATTAACCTGCCGACG
          TTAGGGACGGACGGGGAACATCAGGGCTAGCAGTCTTCGGGCTTAGCCAGCTGTCTCGTG
          TTAGGGATGAATGGGGGACATTAGGACTAGCAGTCTTCGAGCTTAGCTGGCTGTCTCGCG
          TGGCCGGTGGCCGCCACCTCAGGCTAATAACCCACGCAATACGCGGCTTTAACCTTTAAG
          CGACAGGTGGTCGCTATTTCAGGCCGATAGTGCGTCCCGCACGTGTTTTCAACTCCGTTA

          CTATTCTGATGTTAAGCCCCCCCAGCCCGGCTCCGCCGCGGGTACACCGGATTACCCCAT
          CTATCTTGACGTCAAGCCCATCTCGCCTAGATTCTCTGCTGGTACAATGCATCATGACAT
          CCACTTAGAAGTTAAGCCCGATTGGTTCTGCTAACATGTCGACATCATGGATGGTCTTAT
          TCACCGCAATGTTAGGCCCATCCATATTTGACGCCCTGAGGGCATGTCGGACTAACTTAG
          TTTTCTCCATATTTCACCCCGTCACTGCCAGCAGCATGGGGACCTTCTGAATGGGCATTT
          TTCTCTCAATATGTGACCCTGTCACGGCCAGCAGCATGGGGACCTTCTGAACAGGCATTT
          CTATGGTACTAACCATGTCACCTAACCCTTGACGCCCAGGTAACTCTAGCAGTCCCCTCC
          CCCTGGCGTTGACCATGGCATCAAACCACTAACGCTGAGCTAACCCCAGCACCGCACATC

          TTTACTCTATCGACGCGTTACCACCATGAAGTAATTTAGGGATCGGGGGCTCCGAGCCTG
          TCTACTATACAGACGCGTTACTACCGTGTAGTCGTTTCGGGACAGGAGACTCCGAGACTG
          CCTACCTCACAGATGCTTCACAACTTTGTAGTGCCTGTAGAGTTGAGGGCTCTAAACCTG
          GCTATTACAATGCCGTCCGATAACTTCGAAGCGGTTTTCGGACGAGGAATCCCAATCCTA
          TGGACTACGTAGATCTTTTCAAATTGTGTAGAGGACACAAGACGAGAGGATCTAATCCCG
          TGGACTACGTTGATCATTTCAAATCATGAAGAGGATATAAGACGAGAGAGTTTAATCGTG
          AACTAGGCCTATAGAAACGCTAAAGACTGATTCAAACCAATCTATATCGATATCGGCCCG
          AGCCAAGTGAACAGGAATGCCAGTGCTCAACTCCGGCGTAGCTAGACCGCGTTCGGAGCG

          TAATCCGGAAATACGCCAGAGCCGCCCTCTACATTTTTTGCCCGTACTTTTCGGCCGAGA
          CGATCCGGAAATCCGTCAGAGCTACCGTTTTCATTCTTTACCCGTACTTAACGGTCGAGA
          AAATCTCCAAATGGGTAAGAGTAACGATTTTCACCCTTTGCCCACTCCTTCCGGTAGACA
          CTAACTGGGAACCTGATCGGGTCGACGTCTTTGGCCTCTACTTAGACCTTCAGGTAGGAG
          TCATTTGAAAACGGGGTAGGGTCGCGCCCTTTATCCTCTCTTCGTTGTTGACGATACTCA
          CCACTTGGAAACGGGATAGGGTCGCTCCCTTAATCCTCCCTTTGTCGTCTCCGATAATCA
          AAACGTGGAGTTGTGTCAAGATGTTTCCTTCGACCTCCGGGCCGCAGGTCTCGATCTGGT
          AAGCGTTAAGATGTGCCAAGTCGTTCCCCCTGATCTCCGAGCATCAGGTTTTGACAGAGT

          GCGTGGGTATTATGCACGATGCACCCGCGTCTCTTATGCGTATGAAGTGGGAGCGTGGCT
          GTGTGGGCAATACACACGACATACCCGTTCTTCCTGCGCACATGAAGCAAGCGTATTGCT
          CCACAGGCGCTACGCGAAGAGCATCTGTGTCTCGTTCACGCTTGATCTAGGAGCGCAGAT
          GCGCTGGCCTTACACGTAACATAAAAGTCACCAGTGCAAAGATAGAGCCGGGGTACCGAA
          CCATAGGCTCTCAGAGCAGAAATTTCGCCCCGCGTACGTGTAAAGGGTACATATATTTGT
          CCATAGGCTCTCAGAGCAGAACTGTAGCCTCGCGTACGTGTAAAGGGTACACACATTTGT
          GGATATCCTGTCCATAATCCGCCCGTAAGTATGGGCTGTTTCTAGGCGGTCACCGAATAA
          ACAACCAAAAATCGTGATATCCGAGCGAGTCTGGGCCCCTTACAGGCAGTCAACAGATGA

          CCGTTCTTCAAATTCTGGTAGCTCCCATCCTCAAGTAATATTGATCGATCATTAACCACC
          TCGTTGTTCGAGTTACTACGACTCCCGTACTTGAGTGACATTAGTTAATTACAAATCAAC
          TTATTGTTCGCGGACCGATATCTCCCATGATTGCGCTCCACGGGTACGTTAATAAACCGT
          TTCCTGCGCTCGTTCTCGTAACACTCACGCGCGAATACAAGTCTTCCCCTGTTGCGCAAT
          CTACTGATTGAATCCCACAGATACCCATACTAGAACAGAATATCCTCGTTACCCACCATT
          TTACTGATCGAATCCCACAGATACCTATAATAGAGTAGAACTTCCTCGTTATTAACCATT
          TCGGTGTCCGGGTGCATTATATACCTTGGCATAATCTTTCCCACATTTACATCCCGACCC
          TCAGTGTTCGAGTAGATTGACTACGCAGACACAATTTCACCAACATTGATATTCCGTCTC

          ACACCGTGAGTTGATCCCCAGAATGTTACGACACGGGTATTTTACCCGGACACTCGGTGG
          CCAACGCAAGCTGGTTCACAAAATGGAGCGTTACGGGTATTTTATCCGGATGCACGGTGG
          GCATTGCTACCCAATATCAGGACCCATGTGCGATGAGCGTCTAACACCAACGTACAGCGG
          GTATCGTGGCCGGGGCTCGAAGCTCATACGGAACGTGCCGCTTATTTGGACTTCTAGCCA
          GCTCTGTAGCGTAAACCCGACGGAAATTCGCAATATACACTCTCCCTGGATGCACGGTCC
          GCTCGGCACCATAACTCCGAAGAAAACCGGTAATATACACCTTCCCTGGACGCACGGTCC
          AAACTGTGGAATCGCTGCAACAAATACGCGTTGAGTGGGCCCTATGTAGATCCTATGTTC
          ATGTTGTAGGCGCACAACAACAAATACCTGTTATGTGGGCCCTATCCGGACGCAATGATA

          GGTCCCGTGAGATCGGTCTGCTCGTCCGTATGTTAGGTTTCGAAACGCCATCAATACGCA
          GGCCCAGTCAGCTGAGTCAGCTCGTTCGACCATTAGGTTTCGAATCAGGATCGACGCGCG
          GCAACGCTAAGCCGAGTCCACCCCTCAGCTCAATAAGTTCTGCGTTGTCATCACCGCGTG
          ATCATGGCTAGTTTTATAGGACCATATATTTATTAGCTTTTTAATCGTCATCCGTTTGTG
          CTTACCACTAGCCTAGTTATCCGATTGATCTTTTAGGTTTAGAGCCATGATCATTCTAGA
          TGCGCCACTAGCCTAGTTATCCGTTTGGTCTCTTGGGTTTAGAGCCGTGATCATTTTAGA
          CAATAATACGATGGAACAAGGTGAATCGCCTGTTCGGGGATGAAAGGTTTACATCGGATG
          CGGTGGTACGATGGCACATAGAGAGTTACTCGTCTGGGGTTGGTAAGATCACTTCGGGTA

          TATAATATGTGTTGTTCTACCCACCTGTCATTTGCAAGAC
          TAATACCCGTGATGTTTCATCTAGATGTCATTAGAAAGAT
          CGTTGGCCTAGCTGTTCCCTTTATGCGTGCCGCGTAAAAT
          CCTCGCTTGAGCCATTGCTCCCATACGTCATTGGCACGTT
          GACAGCATGTGCCGTTCCATCCTCACGTTATTGGTACGAC
          CACCGTATGCGGTGTTCCAACCCCACGTTACTGGTACGCC
          GCTATGTCCGGGCGCTCGGTGCGGCTGGAAACGGTCGGAC
          GCTATGTCTGGGTGATTGGTGTGTCCGGAGATAACCGGAG

