 8 1000
t1        TGTAGTGCTCGAATCACTACTGGGTCAATCATCCAGGTCTGATACAAGTACGGGGGCCGC
t2        TATAGCCAGTCTACCTCCAGTGGGGGATACAGACCAGTGTGATGCCTGTACGAATGTCGT
t3        CACAGCCATTGAAGGTGCCCTGGGGCAACAGGAGCAGTGTGGCATCCGTTCACTTACCTC
t4        TACAGCCATTGAACGTGCCCTGGGGCAACAGGAGCAGTGTGGCATCCGTTCACTTACCTT
t5        CGGACACAGCCGTTCATACTCGAAGAAGGCGCGAGAGTACAATTAGGGGTGGGCAGCCAG
t6        CGAGTGCTGACGATTTTTATTGGGGTAATCGTACATACATGGCTAAAACCGGACGGCCAA
t7        TGTGGTTTAAACACTTCTACCGGGGTGAGTGGTCATTCGTGATTACAAAGAAGCTGCTTC
t8        TGTGCTTATGAGTTTATTTATAGAGATAGTAACCACGCATGAACGTTATTCTGCTGTTCC

          ACGTAAGCTCTATCGGAGCTGTGGAGGCCGTGTCTCCACGCGACCTTAACACACTCGGCC
          TCGCGCGGCGACCGGGCTCGGTCATCGGTTGATCGCGACGCGACTGAAAGGCTTTCGGTC
          AATAGTGCTATGAAACGACTCTCGGTGGGCGATTGCTGTGTGACTTATCCGTGTTCTGCC
          AATAGTGCTATAACACGACTCTCGGTGGGCAATTGTTGTGTGACTTATCCGTGTTCTGCC
          CTGTAGAGGACACCTCCCCTGCTAGAAAGCGATTCCTCCGAAGTCCGATCTCCGCTAAAT
          ACCTGTCGGGGACGTTACTAGTATATAAGCAGCCCATCTCTACAGCCACGGCAGTCCAGA
          ACTCACAGGATATGCAACTCTACAGTTGGTGGTCCAGCCTTCAATCTAGTGCGCGTCAAA
          CATCGTAGGGCCTCCAACTCATCAGCTAATCGCCACTCCTGAATAGTAATACTACCCGAT

          CGGGTCTAGTTTCGCGATCCACTTGCGCTAGCCTTCAAAACCATGTGTAAAGATTATAGC
          CCGGTTTTCATGCCTTACCCGTGGGTTCTAGTAGACACAGTGCACCATAAGTTACGTCGC
          CAACCATTAAGGTGCTGCAGATTGGACCCTCTAAGTACCATGATTAGTGCAGATTAGAGT
          CAACCCTTAAGGTGCTGCAGATTGGACCCTCTAAGTACCATGATTAGTGCAGATTAGAGT
          TGGAAAAAGACGGTTGCACCAAGAAAGATTCCGAGACCAACAGACAGCACGCCCAGCGGC
          AGGCAGATGACGTTTGAACCACTGGATATGCCGACTCACGTGGATTGAAAGTCGCATAAT
          TTGATCTCTGTGCTTGGACCTCGGCGAGTACCGGGCCTAGTCTCTCGCCGGGCGAGCCGT
          TGGGTATAGGTGTTTAAATTATGTCGTACGTAGAGAACGACGAGCTGTGTGGTGTGCCGC

          CTCATAAGCGCGTAGTAGGAGGCAGCGTGTATCAGGAATTCCATTAATACAATTTTCCAT
          ACCAACTCCAGGTAATCGACCCTATCGACGCTGGGTAATATCACGTGTCCGCCGGGGTAA
          CCCGCGTTTAGATAGTTGCGGGCGACGCATGTAGAAGCACTTCTCCTCCTATTGGTTAAT
          CCCGCGTTTAGATAGTTGCGGACGACGCATGTAGAAGCACTTCTCCTCCTATTGGTTTAT
          CCATGATCTGCTAGGTTTCTAAACTCTTATGCCCGAGTGGGCTCCTGCACGACGGGCTAA
          TCACGTTTTGGATCGTTACTAGATAGGTTAGCACGCGTCGAGCCTTCTATCTCGGGTCCT
          CCAAACCTAGACACATCCTCGGGAATCTACTGATGGGAGTTAGCCTTTATAGTAGGCTAC
          CCACGTCCGGAAACATCTGTGCGAGGACCTGACGCACTCCCACGCTTTGTCTCTGATTTG

          CATAGCGTTCGTGAGGGCAAGAATTCTAACGCCGCAAATTTGGGGGATGTGTTACCACAG
          CGTCACTTCACGCGTTTCAGGGCCCTTTGTGCGACTAACTTCAGAACCAGGTTATCATTA
          AGCGGTCTATAGCACGGTGGGCAGCTAAGTATGGCAGGACGATATTCAGCGCTGTCACAG
          AGCGGTCTATAGCACGGTGGGCAGCTGAGTATGGCAGGACGATATTCGGCGCTGTCACAT
          TATGGCTCTCCGAGGTCCGGCCAGTGGTCTGGAATCAGCTGACGATTCGGGCCCCCGAAC
          TAGACCTTATGCGAGACCGGCCAGTAATGAGGCATTAACCGAGAACTCAAACCCTTAAAA
          AGTTGTCTCTAGACGAATTGTTAGCGACGTGCGGCCTGTGGATGATCGCGGGTTCGACAA
          TGCTGACCACGGGAGACTACCACACTGTGGCTCATCAGACGACGAGCTGCGCTCGAAAGC

          GAGAACGAATAAGGGTCAAAGCCGGTGTGCATATTAAGTCGCTAACTAGCCGACGGATGG
          AACAATGGCCGATAGTTAGAGAAGCTATTGCCACTCGATCGACAATTAGGTGATAGTCGG
          CGATCTAAAATAAGTCTGGGAAAAGCGAATACCCAGAGCAGTCGTTCGCGAGGCAGTTGG
          CGATCTAAAATAAGTCTGGGCAAAGCAAATACCCAGAGCAGTCGTTCGCGAGGCAGTTGG
          CGGGAACAATGACCCTGATTCGCTAAATAGATGACTTGTCACGGACTGAGTGAATATGCA
          CGGATAGAGTCGTGGCCGACCGTGGCATCGTGTACGCTATAATAGCCAGGTATCGATCCG
          TAGATCCAATAATGCCTGACTGTGGTTTATACATACAGGTTGCGACTCGACTGTATCAGG
          AGAACCGGTCCCTGGTTAGTTGTGGCGCATGAACAATGGTAACACCCAGGCGGCGGTGTG

          GAACTTTCTTCATATCGGGATCATCCTCCACGAAGGGCGTTTCACCCCGCCCATACAGCC
          GTATCCATTTTAAAGTGTTGTCAGGCTGGGCGGATGGCGCTTATTAGTTTTAGAGGTGCG
          AAAGTATTCTTTGGGCGCAATCATCTAAGGTGACAGACGCCCGACTTGGTTCTTAGTACC
          ACAGTATTCCTTGGGCGCAATCATCTAAGGTGACAGACGCCCGACTTGGTTCTTAGCACC
          GCGAGTACCTACAGTTTTTTCTCAATAAGGTGCACGGCGGGCCTTGGGCTTCAATGAGTC
          CTGTTCCCTCTCGGTCAGAGAGGGTTAGGACAGGAGCGGAGCCTCAGAGTTTAAAGAGGT
          TTAGTAACTACGAATTACGCCCTAAATCCGTAGACAGAGAGCCCTAAAGAGTGAGAGCTT
          CCGCGTCCTCCCAAGCGCTGCATACTGGGAAGGGGGGCGTCCTCTCGAAATCAACGAATC

          GTGGAAGGGAGATCAACGGGACATCACGTTAGTGTGTCCAGGTAGATGCTTAAGCGCACA
          GTCTCGCGGGTCACAACAGAGCGATACAGCCGAATGCCAGGGGCGATTTTTGTGTGCCTG
          ACCAAGTGCATTACACTGACGTGTTTGAATCTCGTAAGGGGATCTGTGCCTTTACACGTA
          ACCAAGTGCATTACACTGACGTGTTTGTATCTCGTAAGGGGATCTATGCCTTTACACGTA
          AGTGGGAAGGGTATATTAGAGCTGTTCGGTCCGGGATCGAACGCGTGGGACGTGCGAGCG
          GCTAGAGCGGGCGCTCCTGCACTGACCACTAATAGAAATGGGTCGTTGGTCACGCACTTA
          GCCGGGCGAAACGTCACGGCGATGCTCACTCTTGGCTAAAGAGCGTGGTTTTAAGGTCGA
          TGTGGTCCGCTTGTTCCGTCACGGCTGTTCTTAGGATAGCGGGAGTACTATCCGAGTAGC

          ATTGGAAGATTTGCATTCCCATTTTAGGGAAGTAGATTACGTAGTCCTGGGACAATGGTC
          ATCATAGGAGATGTTCGGCTGAGATCCGAGTATGGACTAGGTTGGCTAGGGCGGATTGCT
          ACTTCATGAGCTGCCTAAAGGAGCCGCTAGCATAAACCTCGTCGGTCCGGCTGCGCAATC
          ACTCCATGAGCTGCCCAAAGGAGCCGCTAGCATAAACCTCGTCGGTCCGGCTGCGCAATC
          CTGTCACATCTATCGTAACTTAGGCATTGGAGTCACTGCGGTTAGGGGAGTCCAATGTTC
          GGGCCACTCTTGACGTAGATTTGCTGTGGTCGTGCACGGAGTCCGGGCGGATAGGCGTCC
          GATCTTAAAGTGATATGACTAGAAAATGAGGGAGGGTTTCACCTCAGTGCTGAGATCGTC
          GATGTCTGAATTGCATACATCTACGGCAATAGCGCGCTCCGCCTTGCCGGCTGGCGGGGT

          CGAACTTCCATTTCCTGGCAGCAACCACTTCCACTCCTGATATACGCATCAATAGGTTTT
          CGAACCCCCGTTCACATTTGACTGTAGCAACTACTCTTAAATTGTAACTCAATAGGGAAT
          CGAAGTGCTCCCTACATGGGCTAGGTCGAGTTGGCGTTTCCTCGATCGGTAAATTTCATA
          CGAAGTACTCCCTACAGGGGCTAGGTCGAGTTGGCGTTTCCTCGATCGGTAAATTTCATA
          TAGGTCCTGCCCCGTCTACAATAGTAGCGGCCGACTTGCCGTTACACCACTGGAGAAGTA
          TGGGCATTACCGATCCCATGAGTTACGCGACAGTCCACCGGCCATAGATCAACTAGGGCA
          CAGGTTCCCCCCCCTCCGGGGGAAGTATGATTGCAATGTTGTCTGTCTGTCCACGTGGGA
          CTGAGTCCCCTCAGCTCATGAAGCATGGGGTCGTTTCAATGTATCTTTTTGACCATAGTA

          GAGGCCAGCGGCGACGTAGGGCGGCACGTCGGACGAAGCCATGAGGCTAATTTAAGGATC
          GTGGGGTGAAGCTACGAAACATAGCATGCCAGCAAAAAAGATATGTCTTATATCCGGGTA
          CTGGCGCGGGGCCACGCGGAACAGTGTGACTGTTAAGCGAACTCTATTCATCACACGGCT
          CTGGCGCGGGGCCACGCGGAACGGTGTGACTGTTAAGCGAACTCTATTCATCACACGGCT
          TCTACCTGATGTCGTGTGGTCGGGTTCGATAATCTACGCCACGGCACCAACCCGTGGCTC
          GCGACCTGAGGTATTGATGTCTAATCAATCGATCCAGACCACATCGTGAGAATGTGACCT
          ATAGATTGTCATGGACAAGTATCGATCTATAATATCTAGTTCGATTCCAGCTAGGTGACG
          TCAGCATGTTCAAGCATCTTCCCCTAGCGTCATTATGGGTGAGGGTGTAACACATGACCT

          GCGTGAAATTTTATTCAAAAGTGTGTTTCCGTAATACACGTGATATATCATGAGTTAGTC
          CGTAGAGATTTCTTGCCAATATGGACTTCAGTTTCTCCCGTAGGGTGACACGAGATGTCC
          CCTAACTATGTCATGGCGAAGCATACTTGAGTAAAGCGCTGATTATCACGCTCGCCGTCC
          CCTAACTATGTCATGGCGAAGCATACTTGAGAAAAGCGCTGATTATCACGCCCGCCGTCC
          CCTCAGGTTGCTGCTAACACAAAACCGCCCAATTAATCCGTACCAGGATATCCTCCTCTT
          CCCGAAAGCGTTCAAGTACGGACATATCCCAAACGTCGCCCGCCGTCGTATCCTAGGATC
          CTTCAACCCGATTTTACTAGCACCTCGCCAAGAACGCCCGTCCACGCGAGACTGGAGTGT
          TTACACTTGGGTCTTATCCCGCCTCAATTTAACGAGATCGTTATAGTATGTACAAACCGT

          CAACGTAGACTCTTTGCGGCACTATCTCCAAACATTTTTGCAACGTTAGGGCGTTTCCCC
          TGGAACGGACCTGTTAAAGTCTGGTCCTCCGATGTGCCCGGAGAACCAGGGTGTTTATTC
          AGTGGTTATTTGATTAGGTTCCCATTTTTTGGCGTATCGGAATAACTCGATCCTCTTTTC
          AGTGGCTATTTGATTAGGTTTCCATTTTTTGGCGTATCGGAATAATTCGGTCCTCTTTTC
          GAGGTAAGATCTGTGATTGTACCAGACGCCTGTAATTCCGTGAGACTGAGATATACCCAC
          GAGTACATACTCACAACTGTACCAGCCGTTCGTGATATAGTAATACGAGGGTACCCCTAT
          TCGTGCAGGTCCCGGACAGCGTCAGGAGCTTTTGTTATCACAAGTCCATGCTTTTGTGCC
          AGGCGTAGGTATTGGCCAGTGCTAGCCCTCCCTATTAACGCGAGCTTAACGATATATACA

          CGTAGTCACTGCACTCCCAGCAATGGATTTGCAGATTCGTGTCTAATCCTTATCCGGACA
          TCAAACTGTCTCACCACCCACAGTGGCCAGATGGATGATCGTGTGAAGTTGGGCCGTTAT
          TCCTACAACCAAATCACCGGTGGCAAGTAGGTCGACTCACGTTTGATCTTCGGCTGTCAC
          TCCAACAACCAAATCATCGGTGGCAAGCAGGTCGACTCACGTTTGTTCATCGGCTGTCAC
          ATATCACGTCAGGTCAACGCAGTCGAGACCGTTGTTAAATGGCTGACCTTTCGCAGCTGC
          TCAATACGTCGATCTTTCGGTGCCGAGAGCGCTGACACGTGACCGATCTTCAGTGATAAC
          TCACAGCGTCCTACTCTTGATATAGCTTACCGCACACTGTACACTCCTCAACGTAATCGC
          CCATAGATCCGAATTTTGAGGGGCGCCGCTGTTGCTACAAGTCCCACCTTTGGCAAATAC

          TGAGCCTTGCTTTTTAAAATGCCCTCCCCGGGCTACGCTCCCGTTGCTCTTGGCAGTCCT
          GCTACTACGGGCCTTGATACTATTATAACAGACAGGTTTACCGGTATTCATTGCAAACCA
          TGCGTCGCGGTTAATGAACAAAAATTCCAGGACCGAGTTCTTGGGTTTTTCGTCTAGTCA
          TGCGTCGCGGTCAATGAACAAAAATTCCAGGACCGAGTTCTTGGGTTTCTCGTCAAGTCA
          CACTGCCCACATATTCAGTCGGTGCTATGCGAAGACCTTTCCGCAGCGCGGAGGCTTCAG
          GCGCGTCCGTATTTTCGATCAGCGCTGGGTGAGGAGCATGTTGGGCTCGATAGATGCTCG
          ACCTCTCCAGATTCCCAAGCGGAATTTAGCGGGAAAACGTTGGAGCACTGGGCGCGTCCA
          AGTTGCCCGTGTCTCAGACCGACATCTTTCGAGTGACCTTTTAAAGACCATGGGTGTTTC

          AGGGTTCGTCAAGAAAGGAAGGTCGATGCTGGAGCGGGGTTCCTTGCAATCGCTCGTGCT
          CGCCTTTCCAACGCGTGGTGGGCTGGGGTTGATAGTGGGTACAACGCCTTTGCACGTGCC
          CTAACGTTCCCCGAAAGGTAAGATGTTATTGATCAACGACTCTCAGGGCACGTTTTTGCA
          CTAACGTTCCCCGAAAGGTAAGATGTTATTGATCGACGACTCTCAGGGCACGTTTTTGCA
          TTAGCTCCGTCAGAGTGGTGACCCAATGAAACCGTATCATCTAGCGTGTCCAGCCCTGCT
          TAAGTTCTCTTGAGGCGATAAGGAGAGCGTGGTGTAACCGTTACTGTGTTTCAGCTTGTT
          TCAGTTTTTTGGGAGCGCAAGACTACTCCGACCGTGAGGTCTAGCGTAACCCGGCTTGCG
          CGCGGTTCACTAGAGTGGAAAGCCGCTCCGTGCCCGGGATCGAGAACCCCTAGATTTAAA

          TCTCTGCACGCATTCTATAAAGTTTATTAGTGACTCTGCT
          CCTTTGGATATATCGCTACACCACAACTTGCAATTCTAAT
          CGGCTGGTCAAACTAAGGTGTCAAGCCTTGCACATATAAG
          CGGCCGGCCAAACTAAGGTGTCAAGCCTTGCACATATAAG
          TCGCGGGAAGTTCACGAGCCAGATGCACCCGGGCTTAGAA
          TCTCTCGACATTTTAAAATAAAAGGAACTTGGGTCCCAGG
          ACTATTAAGTAGGCTACACGTTATGCTCCGCAACCTACAT
          TTTCCAGGGAGAATCGATCAGGACGCTCCGCAGCCTCAAG

