 8 1000
t1        GCTTTGGATCATGCCATTACATTGCCGTCGAAGCGCTCCAGATATACATTACGACTTCAA
t2        CGCTAGGCACCAGCTCTTACATTGACGAAGATGTGCACCAGCCAGATGGTTCGACTGCAA
t3        GCGTTCACAGTTTCTGCCACCAGGACGTAGGAACACGACTGAAAACCGGCTGCATGGCAG
t4        ATTACGTCAGCCCACTGTACATACAATGAGCGACCCGCCCGGTGGCCAACCTGGTCTTAG
t5        GCTGCGGAAGTCCTTAATAGAAGATAGCAGCGTCGCGCACGCCATCCAGACTGGATTAAA
t6        GCCGCCTCTCGTCCCCGAATAGTTAGGTGGAGAAACGCCGTTTACTCCTCACGATACCAT
t7        GAAGTTAGGGCCACGAGTCTTTACTCCAACGAAAAAAATTTAAGCTCGGAATGGACGTAC
t8        GGTACGGCGGGACCATTTAAAGTGCACCAGGGACGTCGGGTACGCTTCTGTGGGATATTC

          AGTAAGTAAAAACCCAGTGATGTTTCAAACGATGGGATGAGCTACGAGATCAGGCCCTTC
          TGGGATTGTAGGTTCGGGTTTGCCGAGCACGGTAGAGGAAGCTGCGAAACCAGGCCCTTC
          CGGCGACCCGCGTCTACCCCACTTAATTACCTCGGCGTACGCCGGGAAGCTGAGATCTCA
          CAGGGGCACATGTTCAAGTCCACCAAATACCATTGGGCAAGTGGAAGGAAAGGGAGTCTA
          TGGGAACCCATGAAAAAAATTATAACACAACACAGTGTGTACCATGACAGAGACAGGCAC
          CAGGCTCGAGCGCCCAGAGTTACTACGTGACACAGTGCGAGTTAAGAGAGTATATAGATG
          TTCCGAGGTATAGGAGGATTTGCCCCATATCGGGCGGAACCCTCTTAATCCCAGGCTCTT
          GACCGCACCTGGATTTCAGTGACCGTGTAAAGTGGCACAAAGTATGAAGAAGGAGATTCC

          ATGTCTCGTGTCAGCTAGACCCCACGGGCTGTTACTCATGTACTCCTAGTTAGACCCTAG
          TTTACGCCTAACTGCATAGCCCCGCACACTATGCTCTATGTACCTATCTCTAGGCACTAG
          GGCCTTATCTCAGATGGGGCCCTCCGGCCGGTAGCCTATGCAGTCGTCATCTCTGTACAT
          GCCCACGTCACTACATCGGCCCCGTAGACGGAGTCGTTAATAATTTTTGTTTCTTGCAAC
          TCCCCCACAATCGAAGGTGTTGCGTAGATGGTAGATTGTATTGTTCCCGCTCACCGCCAC
          TTCGTTCTGCTCATGAACTTCCTTCAGGCGGGGCTCTGATGAGACTAAGTTCGACTTCGT
          GTTCCTTCGATAGAGGGAGACGCGTAGCAGTGTTATCGCATCGACGTTAGGTGCCACGCA
          GTCTAGATATGAGTCGGTGGTTCGCCGGTAGAATCTCGGTCTCGTTCAGTCGTCTGCGAG

          ATTTGCTTCCAGTCCGCGGTTCGTAGGCCGTACCGGCACTGCATGAGAAGTAGCTCATAG
          GTCCTCCTCAAGAGCGAATTGCGGGGACCGCATTGAAATTGCAAGTAGATTAGCTAACTG
          TTTCACTTACGCCGTGGTCTCAGAGGGCCGTTACATAAGCGGGAGTTCTACGGCAGGTTG
          GAAAAATGCTATGGTGATTCTAGAGATATGGTTGCGAATCACGCACAGAATCGAGTACCG
          AACATTTTCCGGTTCGCTGCTTGAAGTCACCACCAGAGTCTCAAACTGGTCGGACAGTCC
          TATACCTTCAGGTGAACTGCTAAAAAACCATCTCAGTTTTTCCAGCAAAGTTCCTCGCCT
          ACAAGGCTGCGATGCGCCCTTAGGGAGCTGCCCAAGGTATGGTAGGAAACTACTAACTCA
          AACCTACGTTAGATAACTTTTAGTGGCTAGCGTTTACCACACAGGCTCTACCACGGTTCG

          TGCTTGTGAAGAATACGGGATGTTCACGCTGGCGACGATTGACCGGCTTGCGAACAGGGC
          CGTCAGCCCAGGATAAGTGACGCTGCCACTAGCAGCCGATGTCTCATTCACTACCTAGGC
          GGCCCCCGCAGAACGGGGGATACTACAGCCGTCGGACCATGGGGCGTTGAGTCAAAAGCT
          TGCGTGAGTAAGTTGAGCGGACTCCTTAACGACAGAAAATGATATGCCAACAAACAAGCT
          GCTGGTTTTAAATCGTGGGCAGCTCCAATTGCCAGTCAGTGATCTGTTATTGTGCGAACC
          ACCGCTTACAAGAAGTGGTTCGTACCTCCAGATAGCGGGTGAGATACAAATAAACTGTTT
          ACTATCTGTCGCATTGCGGAGGCCATTGATTGCTGAAAACGGATTCTAGATGCACTGACT
          ACTAACCCTCTATTATGGAGCGACCTGAATGTTGGGGGGCAGATTCCGCAACACCCCATC

          AGATAGCCTACATATGGGGGTGATCTAAGATTGTGTGTTGTCGGCAGTGTACGTCAAGCG
          TGAAAGGTTATGCGTGGGGGCGAAAAAGGAGTACGAGCCGAGGGTATTATGAGATAAACA
          TGTTCCTCCACGCATAGGACCGTCACAGGAAAACGTAGGCTGAGAGCTGTCCAACGATTA
          AGATTGAAAGGATGTACCGTCAAACCTGAATCACTGACCGATGACGTCGTGGAATAAAGA
          AAACTACATCTATCAAGATCATTTTATGGAAGGCCCTCTGACGTGCCGCTAGGACGCGCA
          TGACAAAATAAGCGTGGAAATGCTATTAAGTCATACTCCCGCCTCTTCGGGGATGGAACG
          GGTAGGTATCGGACTGGAGGAGCACCCGGGTCACGGGTCAGCATGCTCGTGGATCAAAGG
          TTGCAACAGGCATTTGGGCAAGACTTCCTTTTGAAACCTAACATACTGACTATATTGCAG

          AGCTGGAGAGCTAGACCGGCTCTGGGATTAACTATTATATTCGTCATAAATGTACCTTAT
          TGTCGACTGGAACATTTTAAACCGGGCTTAGCGGTGGCGATAAATCTAATAATGCCGCGC
          TAAAAGCCGGATCAATGAAGGACGGGACTGAGAGCGCCCTATATACCTCAAGCGCCTGGG
          ACAAGCCCGCCCTAAATAGGGCCGGAGTTGGTGTTACCTCTTACGATTGGTGTCATCTGC
          GGCTGTCTAACTTGTTTGAACCGCGACCAAGAAACGGGGCTTACTGGGGCAGTGAATTGA
          GGCAGCACAATTCGTCGAGCGCGCGTCTTTGCGATGACGCCGATGATGTCAGCGAGCCAA
          CGATGCCTATTGACGCCATTGTCCAATCGAGAGGCATTGGTTTGAGTGTTAGGATTCAGT
          CGCCACCTGATTCACAGTAAGCGAGACCTGGAAACATCGGCTGTGATACAAGCATGGACC

          AGTGGCATAGGCATTTTACAGGGCTCGTCGTGCCATGGCTACATGGAACAGGACTGCCAT
          CGTGGTAAACGCGTAAAGGAGACATCGCTCTGCATCCGATATGCGAAGCAAGAATGCTGA
          TGTGGCCGAGGCCCATCGGGAAATTCGTTGTCGTCCGCAGAAGCGAGTCTCGACTATCCA
          AGTGGTGAAGGCATGAAAGGGATGATTTTGCCGAACGAGTGCGCGGATCAAGGGTGACAG
          GGGGGCACTCAATCATTAACGAGCCATTAGTCGCCTGCTTATGCAGAGCTATGGTCCGTG
          GGTGACTTCAAAAGATTGTTATGACCTTGGGAGTAGGGGTGGGGATGGTAATGAAGGAGG
          GGAACCATGAGGTTTCAACTGGCGTTCTAATCACCCTGCTACTTGGAGCAAGAACGACTC
          GCTAGCAACACGCCCACTGTTTCGCTCCTACTACATGATTGGGCGCTTTGAGCGCAGTAG

          TCACCAATGCGGTGACTGTCGTTCGCAACGTGTATTATAATACAAGAGAAAATCGACTTG
          GCTATAAATGGTCACGAAGCCCCGAGAAAGCGTCACGTACTGTAGGAACAGATCGGTTTG
          CCTCACAGGAGGTGAGGGGCATCAGCGAAGTGCGGCGATCGACAATAGTTACTAGGTCTC
          GCTGGCCCGTAGTTGTGATCACCGGTACAGTGCGGCCGGGAATGACAGTAAAACAATTTC
          TTTGTATGATGGCGTGGAGATTCATTTTGGCGTCGCCCCAACCTGCCGTACTTCAGCGTT
          GGACACCTGTGGAGCAGTACAATTCACTTAAGGTCTGCTACTGAAATGAGCATCGGTATG
          GCTTTTGTACGGGAGGAAGTGGCCCGCCCTGGGCACGTAATTCCTGATTGACGCCATTAA
          CCCGATGTGTGGACCGAAGTAAAGATCTACCCAGTTGGAAATAGTCAACGTTGTGGCTTA

          GGAAATATGTGAAGTAACGGCTGCTATCAGTCTAAAGCCGACCTTAGTAAGGCGACCTTT
          AGTATTACATGTATCACCGGATAAACTATACCTGAGGCAAAAGCTAGGGAATCAACCCCA
          GGTACTTATGGAGTGACCGGCTGCTCGACGTATGTATTGAGGGCCGTAGAGTGATCGCTT
          GGCACCCAATGGGTGGCTAGCAGGCGGATGCTCAAAGTCAGAGCATACCAGTCCAAACTT
          CGCATCGCATGAAAAGCTGTCTCTCCTTTTGCTGAGGCTGCCATAGAAAGTCTGCGGCCT
          GGCCTTATAAGAATGGCCGCTAAACTTCAGCCTGGCGCAACCAGAGACACCGGCTACTTC
          AGCATGATCTCTGCGACAACCACATGTAAGGTGCGACATGACCTTTGAAACCCTATTAGC
          ATAACTTTACACATGGCCGAATCGTGTATAAATGTAATAACCGAAGTAGATATATAACCC

          AAAGTGAAAATAATACTTTAATTCCTCCTACTTATCACGTGTCACAGGCTTAATGCACGA
          AATACGAGCGAAACTCCGTACTTCCTTCAACCCGTCCATCAATGGAAACCCAGCGCACCA
          AAATTGTCTACGGCACCTTACTTTTTCTCATTTATCCCTCTCTCTAATTCCTCAACCATG
          TATACGACAGAGCCTTCGTGGTTCCTTTTACTCTTTAGATAGGCCAGTTTTTCGCTGCTA
          GAGGAAATAGAGCTTCTTTGCCGCCTCCAATCGGTCGCGCACCGAAATTCTGACCTCCTG
          CTGCCACCCACGTTCCTGTCCACGTTTCCACTTGCTACCCTCTGACAGACAACTTTTTTC
          ATGATATCACAAGCTATGTCTTCCGTCTTGCCTCACGACTGGTCAAGTTGGTTATGGCGA
          GTGGCCTTAGTGAGCCTGCCTACTCTCACGTTTGCCTGGAAGTGGCGTGCGCGACAGTAG

          CTGGCACGCGACCTTGACGCGGCGTCATGGGAAGATATATGAGGACCTCTAAACTTAAGC
          CAAGTGTGCGAGTCTGAATTGGACTCCTAGCCAGATCTGTGAGGACTGGTGGGATCCCGT
          CCGGCCTATACGTTCGCGGGAGTTGCACGGCCGAGGCCGTAGAATCTATTCTAATGTGGG
          CTGTTGTCCCGGTTTGCAACCCTCTCATGGGCAATTCCGTGGAGACTGGTGTAGTTACGC
          ACACAGCAGAAGCTGACAACGACCTAGCGGGCGGTCACAGGAAGGTTGATAGTATTATCG
          TTACCGCTAAGGTTTAGCTCTAACAGGTAGTAATATCCTCGATTTCCCATGCAATGAGGT
          TCGGTGTCAAATCCTGAACTGATTTCATTGGAAATTTAACGCGGCCTACTACGCTTTACT
          CTGAATGGGTGGCCCTAATCGCTTCTGTGCGAGCCTACCAGAGACGTGCTTATCGTTAAG

          ATTATGAAATACCTGCAAAGAGTTCCACCCACGCACGTACGAACTGAGTACCCACTATGT
          GCTAGAAGTCCCCAGTGATGAACCTCCTCCCAGCTCCTCCGACCCTGCCAGTGACGGCGG
          CTAAGATAATCCCAGTACCACTTACAACTTAGGGAAGGACGAATCCAACAAGATCAAGGA
          AAAGGGCAATGCCGGTTTCGGGTGCTGCTTGGGCTCGTAGGAAGTCCTGATCCACCACGT
          AACAAAATGGCCTCAAGTGGCTTCTACATGAGGCCCATGCACACCCAAAACGGTTGGCTG
          GACGAAACGCTTAATCACCGAGACCCCTCTAGTCCAACTGCCGTTTTCCTAGGTTCCTCA
          GGTATAAAAAAATTGGGCTGACGACCCCCTGCGCACGATTGCATCTACCTAGGTTGGCTA
          ATTAAGCGTTCTTGCCTCAACACACTGTTACACTCCGCGCACCGCTCTGACGGCTAAACG

          AAGATTTCGCTCATATAGGACGCTTGCCGCGGACTTTGTTTTTTCGAACGTACATTACCA
          AAGAAGCCATTGTTGCACATAGTCCCTCGTGTATAAGGTCCTATCTCTTGCGTATTTAGA
          TACTGACCGACTCAGTCGTTAGGCTATACTCAGCGACGACGCATTAGACCCGAATCTGCA
          AAGAAACTCTACCAGGTGTCTGACAGACATTTGCTGGTCTGTGTTGATCGGATGTTTGCT
          ATACATCTCCCCGGGCGGACCGACGGCTGATATTGAAGTCCCACCAATCGCATATGCAAC
          CTAGTGTCTCAGTAGCGGACCGTTTGTCCTCTTTAACTCAGCATCGCCTACATGTGCCTG
          AGGTTGCCCTTCCAAGGGGCTACCCGCCTCGCTTAAGACCTATCCGATCTTCCTCACAGA
          GTGGCCACCATGTGTTTGTCTTCCTCCACACGATAGTGCCCATATGATTATCTCCATATG

          TAATCCATTTCCCTTTAACGTGGGTGAGTATTGCTTGGCGAATGGCATTATCAAGTGGTA
          TAGCTGGGCAGCCCCATATGTAAGCTAATGCCGCGAGGCGGACCCACTCAACAGGTGGCT
          GCCTGAGGTACTCTTAATCGTTCCTCGACGCGGCCAACCGAAGTATCCGCGCCGGCAGCG
          GAGAACTCGGTTCACTACTCCCATTTGACCAGCTCAGAGGAACCGTTTGACCCTGCCGCG
          GTTCTCACACTGACCCCCCATTAGCCAACGTTATGGGCAACCTAATTACGAAGGTCAGTT
          GAATTCAGTGTCGTGAGCAGCACATTGACGAAATAGATGCCGGTACAAAGCGCAGTGCAA
          GTCCTTGGTGACAATGAGCGTGAGCGGCTGTAACACGACCAAAAATGGGGTCTAATGGCG
          GGATTCAACATTTGCGGTCGAGGTCGCGTATGAATAACAGAACGAGTAATAATGTCGGTC

          CGCCAACATCTGTGTGACGCTTGAGGGTTCCTCCATGGGTACGCGTGTCCGCACACTACA
          CGCTAGTGGTTGCATAACGCCGGGCGACGTGTCGAACAAACCGCGCGCCTGCACACTAGA
          ATTGAAAACTCGCGAATCGATGACAGTCTTTTCGAGAAATGTGCCGAGCCCCACATGGGA
          TACTAGCACACGTGTAACCGCGAATTCCTTATGCGACGTGGCGATGCACTCTTAAACCCA
          AGTGAGAAGGCCGGCTAACCCGACAGGCCCACTGTGCGACACCGGAGTCAGCGTATCCTA
          GGATGAAGCTTCAAAGACTCTACACGAAGACCGTTATAAAGCGCCGTAGCTACCACCGCA
          AGAGCTAACAGATATAACCGTACTTAGATCTAGCGGCACTGCCGTGATCGCCTAACCAGG
          GGAGCATTCTCTTGTGCAAGTTAGTAATTGGCGTTCGGGCAATTAACATCCTCTATTAAC

          AATGTCTACGTCATACCCTACTCATGCGTCTTTCCGTTTG
          AGCATATAGCTTGTCCGACCTCGCTGCATTACCTTGCGTG
          CATTACGAGTTCAGACCGTACCAATGCCTGTTACTGTGTG
          CATAAGTAGGTCACATGCCTGTTGCGTGTCCAACCGTTCG
          CCGACTTATGCAACGCACTGCTCAAACACTGTCCGCCTGG
          TACGCCTAAAACCTGTTCCTACCGTTATTCTTAAATACAG
          AGATCTCCCGGTGGAACCTTGTAGCCCACCTCGGGCCTTC
          TAATCTCTAGCTATGAGACTACACTTTACGTCGCTTTACG

