 8 1000
t1        GCAGTGCATTATTAATTTACCTATGACCGCATCCCGATGGCGCGTACAGAGTCAGTATCA
t2        GCAGCGCAGTACCAATTTATCTATGAGCGCACCCCAATGGCGCGTACAGAACAAGTATCA
t3        GCAACGCACGGACAATTTATCCAGGAGCGCACCCGAATGGAGTGTACGCAACCGTTATAT
t4        GCAATGAATGAATATTTTCGCTAGAAGCGCATCTTAATAGTTTGTGCGACGCCGTCATCC
t5        GCTTTGGCCGCACGGGTTTTTGTTTCATGCAGTCCGAGAGCTCGAACCCAATCAGTGTTC
t6        GATTGGGAAGCACGGGCCGCCCTTCCACACAGTCAGAGGAGGCAAATCCAGTCAATGTTC
t7        TCAAAGGACGAAGGCTTCTTTTTGCCGTGTTGCCCGTGAGTGTGTTGAACGAGCGTGTGT
t8        GCATGGGTTAAGCTTCGTTTTCCCTGCTTTCGCTCGTGGCGGAGTTCTACAGGCGGATGC

          AACTGGAGGCTTTTAACGCGCACTACACAGATATCAGAAATTACCGGTTGGACGCCTTGG
          TACTGGAGGCTTCTAACGCTCACCACGTAGTTATCAGAAATTATCGGTTAGTCGCTTTGG
          AATCACGAGTATTACGGTAACCCGGCATAATCACTTCAAACTACCAGCCGGTCGCCCGGA
          GACCAGGGGTTTTGAGGTCCCACAACCTAATCACTTCAAATTACCTCACGGTCGCCTCGC
          CTTTTCAAGCACAGCAGCCTAACGTGTTGGAGCTTACCCATTTTTAGGTTTTATGTTTAC
          GGTTGCGCTTATCTCAGATTCACGCGTAGGAAATTATCGATTTTTAGGTGTGACATTTAC
          GATTTCGGGAATTTCGAACGTACGGGTGGGCAGTCACTGGTCCCTAGTTCCTATGTCTCT
          GACCGTGGGATCTACAGCCAGGCAACCGAACGATCGCTGGTCTTGAAACTTGGAGTCTGC

          AGGAGCTGTATGTCGGTCACTTCAAAATGGCTGCCGTTCGATCGCTGCTAATGTCGTCTG
          AAGAGCTGTATGTCAGTTACTTCAAATTAGCCGCTGTTCGATCGCTGCTAATGCCGTCTG
          ATGAGCTGCATGTCAGTAAGACCAGCATCGCTGCCGTTGGGTGGTTGCTAGCACAGTTTG
          TCAAGCTGCATACTAGCCATCCCAATATCACTGCCGCTCTGTGGCTGCTAACATAATTCG
          ATCAAATAAACTTGACTCCAGGTTATGAAGTTAGTACTCTGGTGCCGGGGATCCAGTTCG
          ATCGAGTATATCATAATTCAGCCCACGAACCGAGTATCTTGGGGTCGGGAAAACCGTTTG
          CTAACGTACGCCTGGTCGCCTATTACGCGATGGGTGAGGGGTGGCTAAAATAATGTACGG
          TAGAAGTCCGTTTCAATTCCTGTTACGCAGTGTATGGGTGGCAGGCACTGAGATGGCTAC

          GCGAAAGGTGTTGAGCTTGACTCACGCACTAAAGTTCTGATAAAAGTGAGCTGAAGAGTC
          GCGAAAGGTGTTGAGCCTAACTCACGCATTAACGTTGTGATAGAAGTGAGCTGAAGAGGC
          GCGGATTACGTCGGGCTTATCCCGTGCCACAATGCTCCGATACGAGTGAGATGAGAAGGC
          GCGAAAGGCGTCGGTCTTGATTCCTACTCCAAAGTTCTAATAGAAGTGGAATAGCATGGC
          ACAGTGTGAATCCGGATTGACTATTTTCTAACTCTTCTGGCGATGTTCGGTACGAGGGAG
          GCAGTTCATATGTGAATCGGCCGTCTTTCGATGCTTGCGGTCATCATCAGTGCGAGTGTA
          GCTCAAGTCGTAAAGTGTTGCCGCCTACCCAGAGCCGCTCGTGGTTCTGGCTAGAGAGGG
          AATTGAGAATTTCGGCATAGCTATCTCTTACAAAGTCGATTCACTGTTGGGCGGCCATGG

          ACTTTTTACTACCGCGGGCTATCGAATTCTCAACTTTGGCAATAATATCGTCTAGTGCGT
          ACTTTTTAATAGAGCGGGTTACCGAATTCACGACCTTGGCAATAATATCGTCTAGTCCGT
          ACTACCTACTACTGTGGCACTCCAAATCGTCGATTTTGGCGCCCATTTCTCCTTGTTCGT
          ACCACTTATTACATTAGCCCGCCGCTGCGTTGATTTTGGTGCCCATTTCCGGTTCTGCGT
          GAGCCGCCAGACGACGGGGGCCTTTGCATTTTACGCTGAATTATCCGTACATTGCGCCTT
          GAGCCGTGTGATGACTGGGGTCCATGCTTGTAAGCCGAAGCGATTTGTCTCACGGAGTGT
          CAGGTACTCAAGGGTGACCCTTTCGGTACTAAATTTCCGCATCATGAGACATTTGCGGCT
          CGAAATCAGAGTAGCCGCCTTGGCAACGTTAGGACACAGTCCCTCGTGCCAGTAGAGCTG

          CTTCCCCTAGGCGTGATTCAAAGGCTCCCCCCCTTGTGAGCTACCCGCACTTGACGTACA
          ATTTCCTTAAGCATAACTCAAAGGCGCCCCCCATGGTAAGCTCCCCGGAATTGACGTACG
          TTTTCCATAAACGCTGCTTCGAGAAACTCACCCTATCGGTTCGTGCGGAAACAAGGTCTA
          TTATCTCTCGGCGCTAATTTGAGAAGCTCCCCCTATTAATTCAGACGGTAACGTGGTCCA
          CGTCTACTACGCTCGTTTCTAAGAGGCCCTAGTCGTTGCTGTGGCTTGAGTCTTGAGACC
          TGCATGCTATAGTCATTCCCAAGAGGCTCTCTTCGTAGTTGTGGCCGGGATCGTACGGAT
          GTTGTATGAAGCTGGGTTGTGAGCGATTTTCTACAATGATTTAACCTGGGCTATATCCAC
          TCTGACTCGAAAACGTATGTACAGTTCCTAGAGTCTTGTCTTATACATTGCCGAGTTACA

          TTGATTTCGGAGAACAGCCTTATGGTTCACAGGCTCGAGTCCTCAGGGCTGCCCAGTATA
          TTGCTCTCGGAGGACAGCCTTACGGTCCATAAGCTCGAGTTTTCAGGGCGGCCCAGTATA
          GTGCCCGCGTAGAACTGTCTTGCGGTTGACAATCATGTACGTCCCAGACAGTGTGGTACG
          TTGCTCGCGTTCGATCATCTTTTGGTTAACGAGCATGAACCTCCCGGGCAGCACAGCAAG
          ACTCTTGCTAACTTTGACCTTGTGAGTCTGGGGCTATGAGCAGCTGCTCAGAGCCATTCC
          ATTCACGATATATACTGTTTTGTACGTCTAGGATAATGAGTACCTACCCAGGGGTATTCT
          CCGAAGGACAAATACCGTCTAAAGGGTCTAGGTATTCCGCTGGCTACTCGCAAATGCAAC
          CTGCATGGCTAATGACGTAGCATAGGAACGAGGTGTTTGCGCTCCCATGCGGAGAACAAT

          CACGCCCTTACCATATTGACCCTATGCATGTCGTACCCCCTACGCGGGACTCTAAACGTC
          CACACCCCCACCATACTGACCCTAAGCATGTCGTACCACCTACTCGGGACTCTAAACGTG
          TATTCAATTACCACCTGGACCCTCTGCACGACGTACCATCAGCTCGCGAATGTAAACGTC
          CACTCCTCTACCGCATTTACCCTGTGTACGTTATACTACAGATTCGGAAGTCGAAACGCC
          CTTAAACATACCCCTGTGAGTGCTTACAAATGTCCACTTCGGTCTTTCTGCGTAGCCGTC
          TTCGAGTCTGTCCCCATATGTGACTGCATTATGTCATTTCCGTCTTTCTGTGTAGTCGCT
          TCTGGTTACGGAGAGAGTGTCACTGTGAATTTGCCCGGATGAGATCCTAATGAAAACTCT
          TCCAAGCGTATCTTGGGGAACATAGAATCTTCGCTTGAGGTGGATGATCTCGCAGAGGGT

          ATGCCAATGAATTCCACTTGTCAAGCAATAGAATACATTGAAAAATGTCCTGGGCTCATT
          AAGCCAATGAATCCCACCTATGAAGCAACAGAGTACATTATAAAATGTCCCGGATCCACT
          CCGTGAATCAGTCCCTTCCCCCAAGGGACAGAATCCATTGTACATTGCTCTGAACCCGCT
          GCGCGGATGGGTCCTTCTCGCCTAACGACAAGATGTATTGTAAAATGTTCTGGACTCGTT
          ATGTGTAGAGACATTGCCCGTGCCTCGAGTGCTCCCATACACTTTCTACAGGGTTGAAGT
          GGATGTAAAGGCATTGAACGGGTCTCGGGTACCTTGACCCGCTTCTTTTCGGGAAGAGTT
          CTGCGAGATTTCATGAAAGAGTTACCAGGCGCATCAGTTGATCGTAACGATCGATGGGCT
          TCGCGTGGCAGCTCCTGGTCCTGATCATCGGTGTCCAGTACCACAAATGTGCCCTTGGGT

          GTCGAAGATAGATCTGTGATCCAAACGGGCGCATCACCTTACCTCTTGGGTACACACCTC
          ATCGATGATGAATCCGTGATCCAATAGGGCGCATCACCTTACCTCTTGGCTATACGTCAC
          GTCAAAGATAAAACTGTGAACCTAGGGGGCGCATCACCCTATCTGTTCGGTATACGTCGC
          GCCGAGGATGAAACTGTGAGCCTAAGGAGCGTACCACCCTACTTCTTGGGCTCCCATCGC
          AGCGTAGCCCGATCCCGTTCATAAACTAAGGTCAGATGTGCTCCTCTAGAGCTCAATCGT
          AACGTGGCACGACCCCGTATACCTACTAGTGCTGGATAAATCCTTCTGATCCCTAACCCT
          ATCAAAACACCGGGGCTCCTCTCAGCACATGTCAGACAAATGGACTGACCTCGGGGCACC
          GATGAGATTTAGGCCTCCGAATGTGCGTGTGCCTGCCGAATTAAGCGCTGTCTAAACATA

          CATGATCCTAGCTTTAAACACCACTACACCCTTGTGATTGTGCATGAACTCCTAAGCAGC
          CGTGCTCCTAGCTTTAAACACCACTACAGCTTTGAGATTGCGCAGAAACTCATAAGTAAC
          CACGATGTTAAATTTGATCACCACTTCAGATTTGTGATCGCAATAAAACCCCTATGTAAC
          CATCATGCCAACTATAATCACCACAAAAATTCCGTGGTCGCGCAAAAACCACAAAGCAAC
          TGCAACGCCTATGTCCCCAATGTCTGTGGAGTATGTCCTGTATAAGCACCGTGGTGCGTG
          TGCAACTTCTATTTCTAGAGTGTCCGTAGTGCATCTCTAGTTTAGGAACCGTGAGACATG
          CACGACGTGAGCGAACCGAGCTACCTTGAACCTGACCCCATCAAAATACACATGGTTAAT
          GCTAGATTATGCCCTTAGCCGATTCGTGGACCCGTATCCGCCAATCAACCGCGAGATAAC

          CGCATAGGAGCCGGGCTTAGATCGCGCAGTCCCGTCACACATGAGTGTCGCTGGTTGCGG
          CACACAGAGGCCGGCCTTAGATCGCGCAGACCCTTCACACATCGGTGCCGCTGGTTGCAG
          CCATTAGAAGTCGGGACTAGTTCCCGCAGCCCAATCATCCATTCATTCCGTTGGTTGCCG
          CCCTCAGGCTCCGGAACTAGTTCGCTCAGCCCGGACGTCCACCAGAGCCGCTGGATACAG
          TTGATTACTCTCGTATCATTGCTCCTTCCCCCGATTAATCATTAGGGATTTTGGACACAA
          CTGATGAATGCCCTGTCAACGTTCTATCTCTAGTTTGCCCACTAGGGGTCTTGAGCACAA
          GCTACTGTTGTCTCGCTTCGGCCACGAAACACGATGCTCCGCCGGAATTGGAAGGCGTAG
          GACACCGCAGTCCCGCTACCCTAGAACTGCGGTTGTCCTAACGACAACCACTGATTGCCA

          AGCCCATCTATATTTATGCGCACACAATATACTCCTTGAAGCACTTGGAAATATGCCGGC
          AGCTCATCTATAATTATGCGTACCCAAGATACCCCTTGAAGCACCTGGAAACATGCCGGC
          AGTTTGTTCTTGTTGACGCACCCACAACACCAACCTCGTTCCGGTTGGAAAAATGCCGGT
          AATTCAACCTTGAAGACACGCCAATATTCTACATTCAGTGGCGGTCGGTAACTTTCGGGC
          GGGGTGTTGGATAAAGTGTACATAGGGTATCCTTATCCTAGATATCGATTTCTCGCTGTC
          GGGAAGCTGAATAACGCGCCCAGAGGGTGACCCTATACTACAAGTTGGTTCATCGTTATC
          GGGACCCCTGAGCTTACGGACACATGACTAACTTCCTATTTCGTCCGAGATCCAGTCCCT
          TGTGCATACCCATTGCTATGGCCGGGATCGTGCCCCCGCACATGCCTAGATTTAACTGCT

          GCACGACTGCACTTTAGATCCGAAAGCTTGCATCTCAGATATCCAATCAAGAAACACATA
          GCACGACTGCGCTTTAGACCCGAAAACGTGCATCCCAGATATCCTACCGACGTACACATA
          GACTACAGTCACTTTAAAGCCAGAAACCCTTACTCTAGATACCCAGACGAGGATCTCAAG
          GGCTGCTGCAACTCTAGGACCTGAAATCTCCACCTCAGGTAGCTGGATGACGAACTCAAG
          GCAGGTGCCCGCGACAAATGAGAGAGCGAATAGATCTGGCCGTCAGTTGACGGTCCCGTA
          GTATATCCCGGTCAAAGAGACGGACACGTGTGGTCTTGGCAGTCATTTGTCAGTCTTGCG
          GTGAGTTGGCGCACCCGTCCGACAAGCCGGCTTTTCGGCTGGTCCGCGGAACGCAGAGGA
          GTAACCGTCTGCCCCAGCCCTTAGGGCGCGGATACACATTGATGAGCACAGCATCGTGGT

          CCAGCTTATTTCGAAGAAGTGGAAATGTCATTCGGCGGGGCGAGGCCCTATGGGACGCCA
          CTCGCCTGTTTCTAAGAAGTTTAAACGACATTCAGCGGGGCGAGGCCCTATGGGACGCCA
          TTAGCTGACCCTTATGAAGGCAAAGTGACTCCAGACGGGACGACATCTCGTAGGAAACAG
          CTAACCTACCTTTACAGAGGTATAATGACGCAGAGCGGGGAGATGCCTTTTATAAAGCCA
          CTCATATCCACGTAAAACAGAGTTGCGAGAGTTTGTACATTGCACGGTCCTCAAATCGCA
          CGTGCACCCATGGAGGATTGACATACGAGAGTTGGCGTGTCGTGTAGCCGTAGAATCTTA
          AGCCCCGCGATTTTATTCGGTGGATGAGAGACTGACTGGAGCATTCGCAGCAAAGCATGA
          TTAGCTCGTTTTGGTGAGGACACTTGGCCTAACAGCACGCGAAGATGCTACGAGCCAGCG

          CATTAAAGGCATTCACTACTTAACTTCCGTCAAGGGATCTTTCGTTTTAGGCCTAGCTTT
          CATTATAGGCATTCTCGACTTAACTCCCGCCAAGTGCGCTTTTGCTTTAGGCTCAGCTTT
          CACGAAAGGTCTTCATTATCTGACTTACGTCAGGGGGGCCCTCGCCACTAGCTCGGCTTC
          CATGTAGGGCTCTCACTATCTGATTAGCGCCAGGGGGGCCTCCGCTATAGGCCCATCTTC
          TGTGCAGGAAGGTCACCGGTTTGCAACCGCCCCACCCGGTCCTAGACTTAATGTACTTCA
          TGTGCAGGAAAGCCGCTGATTCGAAATTGGTTCGAACGGCCCCAGAGTTAACTAACTAGG
          CGTATAGAAGCAACGGCTCAGTATCCTGAGCTACGCAGTTCTCAGCCCTAGCTCCGGGCG
          TGTTCCGAAACGTCGACGTGTTATGTCGAGCTTTGCGGTCCGTAGCAATATCTTAACGTA

          GTGAGTCCCGCTTTGCGGACCTGATGATTCACCAGTGATC
          ATAAGTACCGGTTTGCGAACCAGATGATTCACTAGTGATC
          GTGACCACCAGCCCGAGGACTTGGTGATGGATTGGAAATT
          GCAGGCACCGGTCTGAGAACTCGGTGATCCATAGGCGATT
          CCACGATGCTTTGCTGAGCCGATTGTACTGTTAGATATGG
          CAATGACGTCTTTCTGTGATGACTGCACCATCAGATAAAG
          AGGAATCTACTCGTCGCACTGAGCTGGATTCACGATTACT
          GAGTGGTTCCGCTTTATAATGAGCTCGTTGTAAGTTGGTC

