 8 1000
t1        GGAGTTAGGGACATAACTTCTGCTGAACGTGACGGGGTACTCATCGACCGACAACCTTGT
t2        GGAGTTAGGGACATAACTTCTGCTGAACGTGACGGGGTACTCATCGACCGACAACCTTGT
t3        GGAGTTAGGGACATAACTTCTGCTGAACGTGACGGGGTACTCACCGACCGACAACCTTGT
t4        GTCGCCGGGGTGTGGACTCCTACTGGTTGCGGGGGGGTTGCGACCGAGTAGCATGCGTAT
t5        TGTACGTCGGGGCAAGTTTCTATGCGGATCGAGATAGGGACGTTGAGAGTGTCTTCACCG
t6        CGTATGGCGTTATAGATCTTTACGGCCAATAACCTGGAGACATTGGAATCCTATATGTTC
t7        AGCCCTAGCAATCAATAAGGCCAGTTAGAGGGCGATCAAAACCCCAATCCGCAAACGTAC
t8        GTCATCGCCAGTCAACGGAATAGGTCGGTGAACGCTTAAGTTACCAATATCCGCGCACAT

          TCAGATACAGTCTCGTTTGACCCTAACGCCATTAGCCTAGCATGATCCATGGTACCCACA
          TCAGATACAGTCTCGTTTGACCCTAACGCCATTAGCCTAGCATGATCCATGGTACCCACT
          TCAGATACAGTCTCGTTTGACCCTAACGCCATTAGCCTAGCATGATCCATGGTACCCAAT
          CTCAGTATTTACTCGCTTGAGCGCCGAGTCGTTAGTATAGCTTGCCGAGTGAAACCTTCA
          TCTGATCTATGCCTGATAAGGAACAGGAAGGCGTGCTAGACTCCGCGAGTTAACGAGTCG
          TCAGATCTACAATTGGTAGGGAACCGGACGGCACGTTGGGTTACGCGAATTATTGGATGC
          ATAAACGTCCGTGAGCACAACAGCTCAATAACGTTTAACCATTGTAGAATATCGTGTTAG
          ACGAACGCCCATTCCTCCGACATTCCGTTGACTGGAGAGCATCAAATTATTAGGGTGCGG

          ACATCCTCCTCCGCGTCTTTTTCATAGCCACAAGCCATCTCCTGCCAGTCGCTTCCCTGA
          ACATCCTCCTTCGCGTCTTTTTCATAGCCACAAGCCATCTCCTGCCAGTCGCTTCCCAGA
          ACATCCTCCTTCGCGTCTTTCCCATAGCCACAAGTCATCTCCCGCCAGTCGCTCCCCTGA
          ACGTCCCCCTTAGAGTTCTTGACATTCCCATGTGCTGTCCCCCGATAGTCGCTGATGTCT
          ATCACCATGACGTTGCCCGTTACATACCGATGACTTGTTAGCCGTCAGCAGGTCCCGCGT
          GCTGTCGTGCTGTCATTTTCCAAATGGCGGCTGATTGCTGGCTGCCATCAGAACGGGTGT
          TCCTTCCTTGTAAAATTTTAAACGCTCTGGCAGTAGATCCCTCGCCACCGGCTATCTTTT
          GGTTTCCTTACAATTCTTCCATCATTCGTAAAGCACAATACCCGTCGCTGGACGGCAGCC

          CTGGTCGGCCCACGTAAACGATCACGCACAGTTCACTGTGGGAATTCGACTGGAAATCTC
          CTGGTCGGCCCACGTAAACGATCACGCACAGTTCACTGTGGGAATTCGACTGGCAATCTC
          CTGGTCGGCCCACGTAAACAATTACGCACAGTTCACCGAGGGAATTCGACTGGAAATCTC
          TCGAAATACCTATACCGTGAACTACGCACGGTGGACGGTAGAAGCGCGTCTGGGCGACCT
          GAGGGAGACTCACACGAGGTTCTATGCGAGAATTGAGTTGTGTCTGAACCAGGCTGCGGT
          GAGAGATGCCTGTACCAGACTTTACATAAGAACACGGCTGAACGTAAAATAGGCTTCGGA
          GCGAAATGACCATTTAAAGAAACGTAACGCATCCACCAGCACGAGAAACACGAGTCCCTC
          AAGAGACGGTTATTATAATGCTCCCCCCGTGACCCGCAATGGGCAACGAGCGGTCCTGTT

          AGAATCTTTTTGGAATTTCATAGAGATCATCTGGCGGGGATTGATGCTGCGTGTTCACCT
          AGAATCTTTTTGGAATTTCATAGAGATCATCTGGCGGGGATTGATGCTGCGTGTTCACCT
          AGAATCTTTTCGGAATTACATAGGGATCATCTTGCGGGGATTGATGCTGCGTGTTCACCT
          AAAATCCCATCGGAAGTACGCAACTACCATTTGATAGGGATACACCTCGTTCATCAACGT
          AGAAGTACTTGACATATCCAAAATAATCGGAATAGGTGGGACACCGGCAGGCTCCTGTGA
          AGATGCCCTGGACGCTCCCGGAACGGCTAAGCCAGGTGGGACCTTAGTCAGCTTTTACGC
          AAAGACCTAACAGGGCTAGACCAGCACTAAATATCGGATTGCATCAATATGTGTTTATGC
          GGGAACCCTTCAAGGGCAGTCGAACACTCGAAGGTGGGTCACACGAACGCGAGTATACGC

          TGTGGGTTGACCAAGGATAGTCCGCCTAACGGCCCGCTTGGGCGGGACTTGTAAGAAATA
          TGTGGGTTGACCAGGGATAGTCCGCCTAACGGCCCGCTTGGGCGGGACTTGTAAGAAATA
          TGTGGGTTGACCATGGATAGTCTGCGTAACGGCCCGCTTGAGCGGGACCTGTAAGAAATA
          CGCGCGACGGCGATGTGTGCGACAGCCGCTTATCCGCTTAGGCGGGGAAAACCTGCCCTC
          TGGGTCCCGGGGATGAGTATACTATTCGGTGCGTCTCACCAACATGATCAGCTATGATCA
          CATGTCCTGGAAATGAGAACATCAATTAACGTCTCTCACCAGTGCAATTAGATATAACCC
          CGCGCACTGGGGCTCGAAGGCTTAGCTGACACCTATCGTCTATGCGCCTAGGCAACATCC
          TGTACACTGAGAAGCGACGGTCCGGCCCCTACCCAGCGTCTACGTGACTTGGTAAAATCC

          CTGCTTTTAGCGGAATGTGTTTAGGGCCGAGTGGATACTCAAGAACAGCCGGTCAAAGAG
          CTGCTTTTAGCGGAATGTGTTTAGGGCCGAGTGGATACTCAAGAATAGCCGGTCAAAGAG
          CTGCTTTTAGCGGAATGTGTTTAGGGCCGAGTGGATACTCAAGAACAGCCGGTCCAAGAG
          TCGTCGATGGAGGCGGGTATTTTGGGCCGGCTGGCTTCCCGTGACCGGCCTGTAAAAGGG
          AGCTTACCCAGGGAAAAGTGTCCTGGCGCCAACAAGTCCCGGGACCTATCCGTATGATAT
          AGCTTGCTAATGGAGAAGTGCCCCGTCTCCGCGAAGTTTCGGGACCTTTTGGCATAATAT
          GTCGTGTCTAGAACAGGTATTCCCGGTTTCTATAAGTTTGAGAAGCGGCTGATTAACCAC
          TGGCTACCTATAATTGGCAACTCTCATACGTAAGACTCCCAGAAGGGGTCAGACTACCAC

          TGGTGGACTGTATTCTGAACCATGGTATGGCAAGGGCCGCTTGTTAAATTTAGAACATGT
          TGGTGGACTGTATTCTGAACCATGGTATGGCAAGGGCCGCTTGTTAAATTTAGAACATGT
          TGGTGGACTGTAATCTGAACCATGGTATGGCAAGGGCCGCTTGTTAAATTTAGAACATGT
          CTGACAGCGTAGGTGTGAATTACCGCCTAGAGCGCGCCGCGTCTCAGTAACAGTGCTTGA
          TCATACGGTCTGGGCTCAGAGAGTGAACGGGATGAAAATACGTCTTGACAGAGACAACTG
          TTCTGGGATTTGGGTTCGTAGAATGGACATGGACAGGTAAAATCCGAACACGGGGAATTG
          ACGCAGAGCAGACCGTGATACGACGACACAAACGGACAGAAGTAACCTAGGGCACCGCCA
          ACGTAGACCAGGATACACATCGAAGACGGGAACGAAATGTGCTTAGCTAAAACTTTGCCC

          CCCTCTGACAGGATCGCAACTCCCGCAACATTTAAATCCAGGGACCGTTGCTGGTGTGAG
          CCCTCTGACAGGATCGCAACTCCCGCAACATTTAAATCCAGGGACCGTTGCTGGTGTGAG
          CCCTCTGACACGATAGCAACTCTCGCAACTTTTAAATCCAGGGACCTTTGTTGGTGTGAG
          GCCTTTGTGGGGATCGCGAGTCCAACAGGTATTAACCCCAGGCAAGGTTTCCGGTGTTAG
          AGCATTGTCGGGGTTTCCACTTCTATTATCTATAGTACACGACACCTAGACCGACAATAC
          GGCATTGTAGGGATTAACAGTCGACTTCTACGTAAATCCCCACATCTTCGTCGGTGATAA
          ATAACTGACACAAGTGCTCTCTCTGTCGTGCTAAGGTATTAAGAACCCTATCTGTGCTGC
          ATCCTTTATAGTGCCGCCTTACCTGTCAAGCCAGGACACCGACATCGACAGTCGAGACGC

          AATATAAAAAGAAAGACTATAGTGCCCTAGCGATCGCACATAAACCCCACTCTCAAAGAC
          AACATAAATAGAAAGACTATAGTGCCCTAGCGATCGCACATAAACCCCACCCTCAAAGAC
          AATATAAAAAGAAAGACTATAGTGCCCTAGCGCTCGCACATGAACCCCACCCTCAAAGAC
          GATGTCTAAAAAGACGTTCAGCAGGAATCGAGGCCCCATGCGCTGCTCAAGATGTTAGTA
          GAAGGACGGGCAAAGGCGGTGACCTGGTCTGGGGGTCCCTCAAAGTAAACCCAAGCTCGA
          GAGGGGCGTGCAGGCGTTAGGATCCGGTACGGGGGCACCTCAAAGTCGGCCCATGCTTGA
          TACCTTTAGACACGGAATGTAGGGTAGTCCGGGGTGATCGACTCCTTTCTCCAGCTATGG
          TACTCCCAGGCCAGGGGTAAAATGGAGCTCTGGGTAATCTGTTTTCCTTATGAAAATTGG

          TTGTTACGACAAAACACGGAAAGTTCACACCATAGTAACTCGACTCCACAGTTCAATCGT
          TTGTTACGACAAAACACGGAAAGTTCACACCATAGTAACTCGACTCAGCAGTTCAATCGT
          TTGTTACGACAAAACACGGAAAGTTCACACCATAGTAATTCGACTCAGCAATCCAATCGT
          AAATGTTGATAGGAAGAGTACTATGTATGCCTTCACTAAGGGCACTAGCCTTCATACTGT
          CTTATGTGGTCGACATAGGTAGGTTTCCGTTGATTCATTGGGATTGCTGCAGGAGGTTGC
          ATTGCTCGGCCGACATAAACGAGTTTTCGTTAACGACTTGGGTCCTATTATAAAGGTTAC
          GGGAAGAGACCAGCATTAGTTGATGCTAGGCGCTGCTTCGACTGTACAACGTTCAGCCTC
          ATGAAGCGAGCGAAAACTGGCTGCGCTAGGAATTGTTTCCTCCTCCTGGTACCCAGCCCT

          GCGTCTGTGTTAGACCGATAAGCAATCAATTAGATCTCAAATGTAACTAATTCACTCGGC
          GCGTCTGTGTTAGACCGATAAGCAATCAATTAGATCTCAAATGCACCTAATTCACTCGGC
          GCGTCTGTATCAGACCGATAAGCGATCAATTAGATCTCAAATGCACCTAATTCACTCGGC
          ATGCCTGTGCTGGTCCGTGAGCCGGTGGATCAAATTATGAGTGCATATAACCTACGCCGA
          TTTACCGCAATGCTTTACAAAATAAACTGCTATAATGAGTCGCTCTCTCACCCGACTGGC
          TCTACTGCGATGCCTTGCTAACTGACCCACTGTGACGAGGCGCTTCCCCAAGCAAATAGC
          CTGGTGGCAACGCGACACAAGATAGGGCTTTTGATTAGGGCAAAACCTACTCACGTCGGT
          CAGCCCTTCGCGAGGCGCATTATATGCCCCTGAACTCACCCAGAACGCATCGTTATTGGC

          CACTTAGGGTTTACACCGGAATGTATAAGCCAAGGTAAGCGAGACTGATGGAGGCCCTCT
          CACTTAGGGTTTACACCGGAATGTATAAGCCAAGGTAAGCGAGACTGATGGAGGCCCTCT
          CACTTAGGGTTTACACTGGAATGTATAAGCCAAGGTAAGCGAGACTAGTGGAGGCCCTCT
          CGCCTGCGGCCCCCTTCGTTGAGTAAAAGCCATACAAAGTGGGACACTGGGGAGATTTTC
          TCCGTCCAGTACTTTCTAGATAGCCCTGTCCGGCTACGTGGGTATCACCTTTGTAGTATC
          TAGATCCGGTGATTATTGGATGGTTCCGTCCGATAAAATGGGGACCCTTCCGATACCCTC
          CTCCTGATAGAGTGATACACGAGAAACTGCAGATAAAAGTGGCACATTGTACGAAGTACA
          GTTTTGTGGAGGCGTCTAACGGGAAATCATTGCCACAAAGGGGACATGAAATGAAACTCA

          AGTCCTTCCCGGTGGAAGTTTCTCATTTTGAGAGCATTTAAAATGTCCGGGGTGGGCCGG
          AGTCCTTCCCGGTGGAAGTTTCTCATTTTGAGAGCATTTAAAATGTCCGGGGTGGGCCGG
          AGTCCTCCCCGGTGGAAGTTTCTCATTTCGAGAGCATTTAAAATGTCCGGGGTGGGCCGG
          AGTTCCACTCAGTGGAGGTGCCTAACACATAACGTGTTTTCTACCACGAGGGCATGCGGG
          ACTCACAGAGTGGGCGGGGTATATTGTTAATGTACGTTATTTGCGACTGCAACGGCTGCG
          GGCTAGAACGAAGACGGGATGTATTCTCAACTAGCGCTACTAACGACGTTGGCCGCCGGG
          GATCCAAACTAAGGCTACCTCCTCCTTCAGAATCTTTCACCTCGGCTGGACAGGAGGGAG
          GGTTGGAGTTAAAAGCGGTTTAGTTCTCGGAGTGCTCCATCTTGAATGGATCCGAGGGGC

          TATTTTAAATAGAGGCTTTACCTCTGGACAGGCAACGGGATCCCTGATTGTTAACGTACG
          TATTTTAAATAGAGGCTTTACCTCTGGACAGGCAACGGGATCCCTGATTGTTAACGTACG
          TATTTTAAATAGAGGCTTTACCTCTGGACAGGCAAAGGGATCCCTGATTGTTAAGGTACA
          CACCTTACCCACTTCTTTTACACACGCTAAAGCAGGAATGTTCCGCCTAGTGGATATGCG
          AGAAGATATGTTGAAATTAACGCTCGAAGAACAACACTGATATTTCTAACAAAACTGATA
          AATAGTAGTATCGAACTTGGCGTTCGGTGGAGAGGAGCTATAACCCTTACCATATTGGCA
          CACTCCCATTCGTGATTCGCCGTCGGGCGTCGGAGTTGGCTGACTCTCCACGGGCTAACA
          CTCCTCTACTCGGGACCCTGCGCCACGCTTCTAAATCGGAGAATCTCCCACAGGGTTAAA

          GGAAAACCTGGTACCCTGACCTCTGGCCCGAGCGGAAATACATGTGAATATACGGCCCTT
          GGAAAACCTGGTACTCTGACCTCTGGCCCGAGCGGAAATACATGTGAATATACGGCCCTT
          GGAAAACCTGGTACTCTGACCTCTGGCCCGAGCGGAAATGCATGTGAATATACGGCCCTT
          GCGAGACACAGCGGTCTAGTCTTCATGTTTGGTGGAATAGCTTAGCGGCAAACGCTTGTT
          GGTGGTTGGAGCCACTAACACTACCGGTTAAAAGCGGAAGGTCTTAATTCCGTACTACCC
          GGAGAGGGAACCCCCTTCCACATTTGGTTATGATCGGAAAATCTTCCTGCTGTATTCCTG
          ACTGAGTGTGATAGTCAGTCACTTCGTCCCTTCGCAAACGGACTAGGATGCGGGGGTCTC
          GGTCAACACAATGGTCCATGTTTTTTATCCGCTGCAAAAAGGTTCGAATATGGAAACTTG

          TCCATAAACCACATGTTCCGCCAAGCTTCGCAAAAACGCA
          TCGATAAACCACATGTTCCGCCAAGCTTCGTATAAACGCA
          TCGATAGACGACATGTTCCGCCAAGCTTCGTATAAACGCA
          TCGCTGACACCACAAGTCCATTGAGCCATACCCCCACACG
          TCACAGCTTGGGCCTTCTCATCAAGACGCTTTAAGGCCCA
          TCACAGTACGGGTCTTCTCATCTAATTTCACTTGGCCGCA
          TCGTCCGCCGGTCCCTTCAATTTCCAGTTATGAAGGAGTC
          TGGACTGCTGATTCTTTCGTCCCTGTTCTATATAGGAGTC

