 8 1000
t1        CTGCTTTAGAGCTCAGGAGCGCGGCCGGCATGGGACGCATCTCATCGCCCCACTTGCTTG
t2        CTGCTCTAGTGCTCTGGAGCCCGGCCGGCATGGGACGCAACCCGTTCTCCCACTTGACTA
t3        ACGCTTCAGCGTTCAGGAACACCTTCCGCATGTGCCGTAGCTAGACACGTCAGCTGGCCT
t4        TTTCCCACGAGCTTATGACATACGTCGGCGCAAGGTGCATTTCATCGAGACTTTATTCTT
t5        ATACATTACCGCTAGGCATATCCGTCAGTCAAGGCTTGAGTCCAACATGTAACCTACCGG
t6        ATGTTCTCTCGCCCGGCATTGGGACATACCTAGGTTCGCACTCTGAGTGCGAACTGTTTG
t7        CGCCTCACCTTAATGGCAACGAAGCCTTCCCCGCCTTTGAATTCTCCGGCTACTTGAATC
t8        CCCAAACTGAGGGCTGTGACCAGGTCAGGCCCGCGAATAGATAGATTCGCGGTTCAAACT

          TCCTCCCAACAGCACTGGTGTTACAGTAACGATGAGATCACCGGTTCTTAGTTACATACT
          TTTTCCCAACAGCACTGGTATTACAGTAACGATGAGATCACCGGTTCTTTGTTACATATT
          TATTCCCAACAGCATTGATTTTGTCGACACAATGAGGACACCGGTCCATAGGTATATCCT
          TTGGAGCACCAATATTTCTCTAGTACTGGCACTGGGTCAGTCGTTCCGAAATTTAAGAAT
          TTGCCGAAACAGTATGATACTTGTAAAAACAGCGGTTCAATGGGCTCAGACTACCAAGCC
          TTGTAACAACGGCACAGGGACCGAGACAGAAATAGGCTAGCGGACCTAGAGCTCTGCGAT
          CGTCAACGACAGCACTTGTCTGGTAATCTACATATCATTGGCGGAGCACGATTCTCATGG
          TCGAGACCGTGGTCCAGTGCTGATATAGGATACCCGTTGGGTGACGGGCAGCCCATACGT

          TCCCTAACTAACGCCGCTCGGGCTCTGCTCGCTTGGAAATATGGCCACCTCCCTCCAAAG
          TCCCTAATTAACGCTGCTCGGGCTCTGCGCGTTTGGAAACATGGCCAGCTCCCTTCAAAG
          TCTTTAACCCACGACGCTCGGGGTCAATTAATGCGGACAGGTGGATACATGCTATTAAAA
          CCCTCCCTCTGTGGTATCCAAGGTCGACATTCCGACAGTGACAGCGACATTTAAACCACA
          CTTTTATTCTACGCAACTAAGAATCGGCCCCTTTGAGTCGGTTAACATCTTATGTTTTTA
          CACTTAGCCTACGACAAGCAGGGTCGGGTTTTCGGTATAGCCAGTCACGGTCTAGCAATT
          CCCGCAGCGCCTTCCTTCTAAAGTTGGCCTGTGATCATGCGGGACAATTCCTCAGAAATT
          TGTGCTACGGATCATGCGCAAAGCCGGTTGTCGCGCTTAAGAGCAAGCTCCCCAGTATCC

          ACCCGTGGACGGCCGGGCCACGATCATCAAAACATCCGGATCCAGAGGTGATCGTGGTGA
          ACCCGTGGGAGACCGAGCCACGGTCATCAGAACATCCGGATCCAGCGGTGGTCGTGGTGA
          TTCCGCGGTAGACCCAACAACGATTGCCAGAATAGTCGGCTACAGCGGTCGTGGTGGCGC
          GTACTTGGTAAAGTCAGCTACCAAAATCGGACCGTTTGGGTGGGGAGGACTCGTTGAGGA
          CGTTCCGGTAAAATGGATCAGAGCAACTGGAGTAATTGGATCATTAGGTAAGGTGAGTAT
          ATGTCCGAAATAAGGAACTACTGCGATCGATATGAGCAGACTCGTAGGTGGCGTGGGCGA
          AGGAATCACGAAATAGTTTATCTTCTGTGAGACAGAGCGTATCGCTAAATCCAATGACGA
          CGACGTTACGTACCGTATCGGTGATTTTGGTATGAAGAGGTCTGCCGAGGACAGATGCGA

          GTTTATATCTTGGCCCATCCGTGATAAATTTCGTGGGCTCGTACATGAATCCGGTCATCC
          GTTTGTACCTTGGCCCATCTGTGATAAATTTCGTGAGCTAGTATCTGGATCTGGTCATCC
          GTCCTAATCTAGGTCCCCTCGCGTCAGATTTCACGACATGGTATGTTTATTCGGTCACTC
          TCCTTGACGCAGGCATTTCTGCGTTAACTGACTTGTCGAACCACATCACTTGGGGCGTCC
          TGCTAGGATCGGCTTTATCCGCGATAGTAAACTTGGTGCTACGGAGTCGCCCAGGCATTG
          ATTATAGACCAGACGCTTTCGCGTAAGCTTTGTTGCCACGGCAGCGCACACGAGTTTCAC
          GTACCGGTGTCGGCGTCCACATTGCGCTTTCTTCAATTACTGCGGCAAACGGGTGATAGC
          GTCTGGACAGCCGGTTCCGCACGCCGCCTCCACCTCCCTTGTTATGTAATAGAATCCATT

          CTCGCCTGATTCGTTACCCCAGTTTCAAAAACGACAGATGCTTATGAGAGTTTTATCGAT
          CTCGACCAATCCGTTACCCCAATTTTAAACACGACAGACTCTTATGAGAGTCTTATAGGT
          ATCGCCTAAGTCGAAGATTGCATTCTAAGCGCAGAAGATGGCTATAGGAGTCTCATCGGT
          CTCCCCATAATTTTAGCCCGGATCTACGATATACGGGTAACCCGTGCCCCATCTTCCGGT
          ACGATCTTTTCGATAGTCCGAACTGTAGTGATGGAGGTTGCTTCTGCACGATCCTGAGGC
          ACCGCTTCGCCTATAGTCCTTACCTTAGAGACGTAGGAGATCCCTACTCGACCTAAAGAC
          TACAGAGCGCTATCTGGCCGCCGTGCTGTTAGCACGCCCGCATGTACATTTGTTTGGAAC
          TTGCAGATCATCTTGGGTCGGTTGCTGGCCGACAAGTTCACCTCCCTTTTAGCCTAATAT

          GGACTCGTATGTGCCAGCCACCACGCACGTATCGCCATGGATGGTATGGGGTCCCATATT
          GGGCCCGAATGTTCCAGCCACCACGCACGTATCGCCATGGATGGTATGGGGCCTCACATT
          GGAAACGTGCGTCCCAGCCATTACGCACGTATCGTCCCGGGTGTTATGGGAATCAGTGTC
          GACCTCCCAAATCTCGACCTTTCAGCGTGCAGCTTCTGGAAGATTCCCAACGCCCGTGTC
          GGACCCGAATACCTTGGCTACTACGTATGCCACTTCTCGGACGTAGCGGGATCTTATGCC
          GGATCCGCTTGACTCTGTCATGTCGTGTGCCCTATCTCGGGTGCCGTGATCTCTGGTATC
          GAGGCAGTCCGGGTGGGTACCTTTGTCCACTTAGTCTTAATGGCAAAAGACCTGCAACAC
          GGACCTTTCGCACTAGACGTCGGTTCCTGTTGTATATTGGGGGCAACGGGCATGCCAGAC

          ATGAGCCGCGCTTCTGACATGGCTTATGAAGCATCCCTATCTAGTGCGAGGCTTGTGATC
          ATGAGCCGCGCTCCCGACATGGCTTATGAAGTATCCCTATCCAGTGCGAGGCTTGCAATC
          GTGAGTCGCGTACTAAATCAAATTCATCAGGTACATTTGTGAGAATCGAGGTCCGTAACC
          AGAAGCTGGTCTACTGGAGTATCCGGAAAAGCACCCACATATACGGCCAGTTTTGCGAGA
          AGGCGTGGTCCCGTTAACGCAATCGACGAGATGCTCCCCCACGAGGTGACCGTTGTAGTA
          GGAGAATGCCCAATTCACACAACTAGCGCAATGACCTTACATGGCAAACGTCCTGCAACA
          CGGCGACGCCTAAATATATTGATTGGCGAACCAGGCAAGTTAGTGACAATCGTGGGGAGG
          AAGGGTCTTTTACGAAAAATCCTTGGCAAAACTACCCCCCCATCGGTAAGACTTGGGACG

          AAAGACTAGCATTTGCGATGGTCTAAGCTTCTCACAGGAAGAAGGACTTCCAATTCCTCC
          TTGGACTAGCTTTGGCGATGGTCCAAGCTCCTCACAAGAAGAAGAACTTCCCTTTCCTCC
          GAAGATTGACATTGGCTATCACTAAAGATACTCACAGGGAGCAGGGCTACACGTTGCTCT
          AGGGATGTGGCTCGGTCATGGATCCAGTACCCCACTGGCATCATGACCTACATTTATTTC
          AGGAGCAAGGGTCGGCTGCGATCCAAGCTCCCCACGAGAACGAGTGCCCAATACATACTT
          GCAAACGAACTTCGGCGGCGGTTCAAGCTTCTATCAGAGAGGGGGACTGGAGATTAAGCA
          CCTCATGAAGTCCAGTTGTGGAGGATTTCTCTAGTGAAGCATAGATCTACTTTCCATACT
          AGATATTAGGTTAAGCTATCGCAAGACCGCCAAACGGACGAAGATATTATGTCCCATTTG

          CCGGCATAGTGACCCTATTATATCCGACAGTAGCCAGGATATCCTCACTAGCAGACGGCG
          CCGGCATAGTAACCCTATTATATCCGACATTAGCCTGGATATCTTCACCAGCAGACGGCG
          CCAGTGTAGTAATCCTACTCAATTTAATCGTAGCCTGGATGCCCCTGCCAGCAAACGGCC
          TCGCCGTCTCAGGGTTACTAGATCTGATTATAGTCGGGCGGTCCTAGCCGATGGAGACTG
          ACTAAGTATGAATATTGTCAAACTGGAGTGCGAGCAAGATGGTGCCGCTCGCACGGAGGA
          TCGGTGTCTAAATGTTAACGAATCTGGCAGTCGCAGGGTAGTTCCCACGGACACGGAGTA
          TTGTAAGCAGGCAGTGCTAAGAAATAATGCTGAACGTGTTACTTCCCGGGAAACAGGGAT
          CAGCTGCACACCTTATAACAGCGAGGGTTTCACCGGCGTGACTTTGATCTATACTGGGGT

          ATAATCCTCGTGCCTTAACACATGGGAAAGTCCTTATCCAGGACATGCGATACATCTTCC
          ATAATCCTTGTGCCTTAATACATGGGAAAGTCCTTATCCAGGACATCCGATACAGCTCCC
          AGAATCGCTGTGCCTTAATCCGCGGGATGGTCATCGTACTGGACACACGCCACAGTTCCC
          GCGGACCCGGTCCTATTTAGGAATGAAAAAATTCCGACTGAACTGTGCAACCTATGCTCC
          AGAACCTCTGTGGTTCAACGAAAGGATAGACTTTCGTCTAGCACGCGTATTACGGCTTTC
          ACAACCCCCGAGTGCTAGGACACGGATAGGTCGCTGTCCTGTCTACGAGAGACAAGTTGT
          TCACACACACGGAGCGGGTACACTACTTGCTTAGCGCCGAAGCTGCGGTTTGCGAGCGGC
          TTTTGTAAATTGACGCTGCTTATAGCCTGCATGGCGCTGAGGCTCTTAATGGTGGGAGCT

          CATGCACGCCAGCCGACACAACACGAATTAACTCCCCGATGGGTAATCGCCGGACACGCC
          CATGCACGCCAGCCGTCACTACACGAACTAACTCCCCTATGGATAATCGCCAGACACGCT
          GGTGCATGCCAACCGACGCAACATGAACCAACTCTCTCGTCGATAATTGATGGAGTCGCT
          GAGGAGCGCTAACCGCCGTCAAGGATTTCCAATTCCTGGTTCTAAATCCACGGCGGCGTC
          GACTAGCGGCAGCCCGCTAGCAATCAACCAAACTGTCGCTTTGAAACCTTTGGCCACAAT
          GGAGTAAGCAAGTTGATCACGAACACGCCACACCTCTGGTCCAAGACGCCTGGCTGCGCT
          AATACCAGCATCTTATGAACGCGCCAGCCTCCATATCAAGGCGTCGTATACGGTTGTAAC
          GGTTTCTGTGCATCCACGGTTCATAACATTCCGCACTTTAGGATCGTGCTCGTCTGCTTT

          CACTTATCCTCAACCTCGTTAGAACTAGCCGTTGCCGAGTTAGCAAACAGAAAGGGTTAG
          AACTTACTATCAACCTCGTTAGAACTAGCTGCTGCCGAGTTAGCAAACAGAAAGGGTTTG
          AGTCAATCATAAGCCCAGTTAGAGATACCCGCCGTTGAGCTAGTAAGCGACGAGGATTAG
          CCCCCACGGCCACTCCAACTGGGGACAACATTTCTTGGCAGAAGGAATAATGAAGAAACT
          AATCAGAAGTCACGCGCGTTGCACACAGCCTTGGTTGGGCAAAGGTATCACTGGTGAAAG
          AGCCCATGATCTTGCTGGCCGGAAATCATGACCGTGGGACTAATGCGTATAGGGGATGTC
          CTTGGCTGATCTCCTTTTTCAGGAGGTCCCAGGCATAATTTATGACGGGAAAAAATGTTA
          TGAAGTAGGTCCTCGGTTCCAAGCGCGCCAATGACGGGGTAAGGGCGCGCCGAGCCCTTA

          TGAAGTGTCGGTAATCGATCCTGTTCGAAGAAGTAATAAAGATTAAATCTAGTACAGTTG
          CGAAGTGTCGGTAATCGATCCGGTTCGAGGAAGTAACAACGACTCAATCTAGTACAGATG
          CGAAGTGTTGGAAAAAGTTGCGCCCTGAGGAAGTGATAACGATCAATTGCAGTACAAGTG
          TGAAGCGTTTGCAGCAGTTCCGTGGCAAAGCGATGTCGACGGTCAATCCCAATACTGGTG
          CGGACGGTCTATTGCAGCACTGAATGAAAGCGTTGAGGAAGATTAGAGTCGGGTATTGTG
          CGACAGGCCTTTAACGGTTATATAGCCTAGTGATTACCCTGGTCAGATCTACTACAGGTG
          TGCAGAGTAACCAAACCGTACGTGTTGACGTAGACACATTGGTAATCTCTCTTATAGCTA
          TCATAGGCAACTAAATCAACTGTAACTAAGCGCGTGCGCTAATGAGACCTGAAGTAGTCG

          TCAGTGTTCTCAGAATTCCTACTTTCTACACACAACATCCCCAATCGGATGTGTCACCAT
          TCAGTGTTCTCTGAATTCCTACTTTCCACACACAAAATGCCGAATCGGATGTGTCATCAC
          TTAGTGTTCTCTCAATTCATACGTCCTATACTTTGCGTCCCGAATCGGATGTGGAATCTT
          ACGGTGGTCCGGACATTGCCGGTTTTCATATGCTAGGTGTAAAGTCAGATTTAGCATTGT
          TCACCATTCTGAAGTATGTTGTACTCACCACGCCTCGTTGAGTATCAAAGGCAGCCGGAA
          ACGCGGTTGCATACACTCACGTCCCCTACATTGTTCATTCGATCCAAGACACGCCCCCAA
          TCAGAACCGTGCATCTTAGGGTTATAATCGCGCCTTTCGTTGCATACTACACGGCCATAA
          GTACCCTCCCGATATCTGGTGCCTCGTGGTCGCCTCCTGGTACAATAACCATGGTTGTTG

          ACTCGTGACCGTCAGCTGCGTGCGGACGTTCGGGGCTGAAAATGCAGATCTCAAGCGCTT
          ACTCGTGACCGTCAGCTGCGCGCTGTCATCCGGGGTTGATACTGCAGATCTCAAGCGCTT
          AGCGACGACCGTCTGCGATGCGCCGTCCTTCGGGGTTCGTAGCAATGATGTTTGATGCCT
          AGCCACGCATGGAGACCGTTTATCGCCTCCTGGTGGTCATAGCGGGGATGTTGGAGTCCA
          TACAGCGAGCGACGGTTGCTGGTCGCCCTCCGTCCCTCTTTGTACAGATGATGAGCAGCT
          TAACACGAACGGTGAATATTTGATCATATACGGTCCGTGCAGCAAGGTCAACAAGAGCCT
          CTCCAGAGCCTAGGGTAGTACGTCACCTTTGGGTACTCACCACGCAAGAACGTGCGGCTC
          CGTCGAAATCCGGGGTTTTTTGACACACTCGTTTGTATACTATGAGAGTCAGGGAGGATC

          GATCGCTGTATTGACGCACTATTACAAATCATTGCTAACT
          GATCGCTGAACTGACACAATACTACAAATCATTGTTAACT
          GACGGTTGAAGTGACATAGCATTACAAGTTGCGACGAACG
          GGCGACAGGTTCGATACAGCGTAGCAAATTGATATGGACA
          GACGTAAAAATCAACGTAAAGTTCTTAATTGGCAAGCATG
          GTTATCAGACCTAGCGCAGGATGATAGATCGACGGGGATA
          GACATCAAGCCTGCTGCGGCATGTCAAATTGACGACGAAG
          GCCACTACGGCTGGTGAAACACACCCGATTGAAGAAAGCT

