 8 1000
t1        AGATGGCATAATACACCTTACCGGTTGATCACCCGCAACCTAGCAATTAACTGGACCGAA
t2        TACCAGGCCGACACACCACTCCAGCCACTCAGTGGCAACTTAACGATATACCACAACAAC
t3        CGCTAGGCCGGTAGACTACTTTGTTCTGATCGAAACAATTTAGCCCTGAAAACCAAGGAA
t4        TGATAGGATGGCGATCGGGTACATCTAGTGGCTGGTATAACTGTAATTTAAGCATAGCAC
t5        TGCCCTGCTCCGGCGCGATTCCAGATTCTTTATTTCAAGTTCCAAAACCCTATGAACCAG
t6        TTACGGGCCACTGCACCCTTATAAATGCTCTGCGGCACTTCGACAATCCGGTCAACAGAA
t7        TTCCCTGCTATCACATTACATCGGCCCTATCGCTTTAACAAACTTGCCCGAGAATACTAC
t8        TTCTATACTATTATATTTACGTGACATCATCGCTCTGGTAAATTGGTTCGAGAAAATTAC

          ATGGTACCCACCTAAGTATCTGTTTTCTGCCACCGGACTTATCAGGTCTGCTTCTGAAGC
          ATGGTCTTAGTTTATTCATCCGAAGCCCATAGCTGGGCTATTCCGGGCCTTCTCCGAAAA
          ATGAGAATGATTGATATATCTTACTCCTGTTGGCATTTTAAGAACGCTTCCTCCCGAGAT
          ATAGGATAGACAACCGCACATGCCTTATGCGGCCTCGTAAGTCGGATCGACTCCCGGTTC
          GTAACAAAGACGAAATTACTCCCCCCGCTTGGCCGTGATTAGGAGATCGACTTCCTATTA
          GCGGAGAGGATATCGCAGCGTGTCTCATATGGTCACTGGTACAGGGTCAAATCTCTACCC
          GCGGAAAAAGGCCGATAATTAACTCCGTTTAGTGGTACGAGTTCTTTTGGTAATACCACT
          ATCGCCAAAGGTTCATTGGTCATTCAGCCCCATGGAACCAGGTCTTTTGAAAATACTACC

          AACGCGCATTAAAATGTTCGACGATCCACCACAGGGAGTCGCTCGGTGCGTAAGATCCAA
          ACAGCGAAGCTAAAAGATTGGAAGTCCTCGAGGAGATGCTACCGGGCTAGCGGGTTCCGA
          TCTTTGCGACGGAAAGAATGGCAATTCCCGAAGCAATGCAACTCGCTCCGTTAGACCCCA
          GCTACAACAATCGGGGGCCGCAGATTACCTACTGAATCGAACCCATGATGTGGGAACCGA
          CCAATGAAAATTGGGAAATGGCCCCCCTTTAGGCAGTGTCGTATGTCAAGCTAGACCTGC
          GACCTGAAGTTCGAGGTTTCATCCTCCTCTCTAAAACCTCCTCCGTCAAATGTGCTCTCA
          GTGGCAACCCTAAGGAGACGATACCTCATTGTATAGGTCTACCTGTATCAGGGGGTCAAC
          TTGGTCACTCCAAGGGATCGCCACCTCATTACACAGATCTGCATGTATCAGGGGGTTAAT

          TTCCAAAAATAAGGTCAAAATACCTTGAACTATCCGAGTCACTCCTCGCAAGCTCCGATA
          TTTTACAAGCGATGTCTGGAATCTTCGGGTCGCCCGAGCGACCTATTGTCTGTCGTCACA
          TTTCGCCATTGCTACAATGGATCTTCGGATTTACCCGCTCACTTTTTGGCCCTCGTCCCT
          CTCATTAGTTAGACCCTATCCTGTTAGGGCTGCAAGGTCCATCTTTTGTCTGATACCACG
          TATTATTGTTAATAGGTAATACCCCTGATATATTAGGATCCTTTCCTGTCCAAACCCTCC
          TACCGTAACCAACGTTACAAACTTATATTTAGTTCGGTTCTACATCCGCCAATTGACACC
          GCTCGGACAGAACTCGGAGACGTCTAGATCCAATTAGTAAGTGGAGCGTACAATATAGGT
          GCCGGGACATCGCTAGGAGACGCTTAGATCCAACGTATATGAAAGTCGCGTAGTACGCGT

          CGTCACAGTAGAATGGCTGCCGTTATGGCTATGCCTTACCAATTCCCCTCCATGATAGGT
          TGTCCGTGCAAATCGGTTATTCTCACAGGTGCGCCCTATAGATTGCAGCCGATACTCCAG
          ACTTTCAGCCGGGCGGCCAAGGTTATGCATCTGTTGTTGAAATCCGGACTGAGGTACTAC
          TGTGACCAAAGACTAGTAGACGGTATGGTTCTTCCGACTATATTCTGACTGGCAGTGGAT
          AGTTTCAGCAGATACGGTATCACTACCGAAGAATTGCGGCACTCACGAGTAACAGCGGGG
          GGTTTTAGTGAAATGGGCAACGCCCGGGGTACGTCCGATCGCATTTCGATATCGGCGGAT
          TGTCTCATCTCTGAGGGTATTCCAGGTGTTCTAAATGTGTATTTATGCTCGCCACAGGCG
          TACCTTATCCATGAGGGTCCGGCGAATAGTGTGGGCGTTAAACACCTATCGCGCCAGTCG

          CACACTCCTCGTGTGGGTTCAGTAAGATTCACCGAGCGTCAAGTATAATGAGCTTCGACT
          CATACTGATAGCCTGAGTTTGGTAACACAAGCAGAGGCGTCACTACGGTGGACTAAGAGT
          CACGTTCATAGTCCGAGTCTCGTAAAAAGGATGGAGATATGGATTTTGTATGCTCTGTAT
          AGTCTTCTCGGACTCTATCAACTCAGACAGATGGAGATCAAATTGTAGTACGTTATGACC
          CCTTTGGTGAGATTTGACTCTCCCAAACTGAAGGAGGCTTAAACGGAGTAAGGGATGACC
          GCTACTTTGCGACGCGGGATTGTAAGATACTTGCAGGCACGAGTGCAACAAGACATGATT
          GACCGGAGTTAGATTGCGCTTAGGCGGCTACTTGGAATACCTGTCTTGTAAAGGGTGCCA
          AATCAGCGCAAAAACGCGCTTCGGTAATCCATAGGTGTCTCACACTCGAAAAAGATCACT

          CCGCTCCAGGCCAGCCCTATACCGAGCTTAAGTCAAACAACGAATCCTATCTATGTGTCC
          CCGCTTCTGTCTCAAGTCATACCTAGCTTCGGTGAAACAACGAAATCAGTCGGTGGGTAG
          CTAATTACACCGAGAACATCAGTGCACAGAAGTAAAAGGTCCTGCTTAATATGCGGACCC
          ACGCCCCCGACTGAAGCTCTCGTAATACTCGGAACAACGGTCGGACCCAAACGGGAGTTA
          CAGGTACCCATGAGAGTTGTCACTAACTCATGTGTGATTTCATGCTATGCGCAGGGTTCT
          TAACCACCGCCTAAAACCATGCAACACTTAATGACTTCCATCTCCTCTGTGCATGAGTCC
          GAGCTCAATCCCTAATGTTAGACAGCTTAACATGAAAGGAGTTAACTCGCTCAGTGACCT
          CAACGCAAAGTCTAACATTTGACACCTTAATATGGGACGTTTTAATCGGCTGAGTGACTT

          CTTGCGACGAGCCTACCTCTCGTGTCGGATCAGTTCGACTCCAATGCGTCTAAATGTAAG
          TCAACGACGAATTTACTAAATACGCCGGGGGGGCTCGATACAAAAGCGAGATTAGACTCG
          CTAATGCCGTACATGAGTACCGAACCCGTCGAATCCGAAACCAATGGTCTTGTACTCCAC
          CTCGCCATTACCTTTACTAGTTGGCCGGACGAGTGTAACCCCAACGAGTTTACTGAAGAA
          CCATCCCCCACCTCATTCAATTCGCGGAGGAACCTCAATTCTAATATGTATGCCAAAAGT
          TAAACGATCGTCATATTCACTACGTAGAATCATCTCAATTCTCAAGTGTGTAGAAACCAT
          GCGCTACTTGGCCTTCCTGGCATCCACGTGGGGTGCAACAACTGTAAGTTCTTTCATAGC
          GAACTTCACGACCTTCCCGGCATATACCTGTAGTGCAATAACCGGGTACCAGATCAGGGC

          TGTATGACGGTTCTGGAAACCCATTACTTAGAAACCCCGCAGGCAGAGCCTAGTTTCTCC
          CATAATGCACTCATGCGCAACAGTTAGCGAGGAACCTTACCCGAAGAGCTAAACATTGGC
          TAGGCAGCAATCCCGAATACCCACCAGCGACAAGCCTTGTACGCAGTGCTAGAATCGTGC
          CGGACAGCACTCCAGCCTAAGCATTGCTGAACCCTTTCGGAAGGGGGAGAGCAATATCGC
          CTAATTGCACTTCTCGACCTGTGTTCGTGGGAAGCATTATGCGACCGCCTCATATTCAGG
          AAAACGGGACTCCAAGGGCTGTGCAAACGCGTACCTGTTTACGAACACCCAACCTCTAGT
          CTACTACAATTTTAGCACACCTATGGATGGGGTCCATCATTTTTTTACGAGAGCGCTGAG
          CTATTAGGAATCTAGCAATCCTATGTCGGGGGCCTACTATTCTCTAATGCGTGAGTTTGG

          GTATGCTACAATCAAACTGCCGAAGTCGTCTGCAGCGCCAGATGTAAACCCCAATAACTC
          AAACATTCTGGAGAAGTTGTTGATATGAAATGAAGGATGCGACCGATACTTCTCTGTTTT
          ACGCATCCCTCGGAAGCTGTTGTCGTCACCCATTGTGCCGACGTACGTTCACAATGCCGG
          GTATGCCGCCTCGATATCACCGAGACCACACAGAAATCTGGAATGAAATTACAGAAAATT
          TCGATCCCTTAATAGGGAGCATAAATCAGACATAGAGCCATAGTGGAGCCAAAGGGCTTA
          ATATGACTCAGTGAATCCAGATACTTGTATCACAAAGTCAACACAACCATACAAGCGTCG
          ATGGGGAATTCGGCCGCCCTGGTTTCTCTGCTTGGGCCTGTACCGAAGCCTCAGTGTCTT
          ACATGCAATCCAGTTGTACCAGTCTTCTTGCCCGGGGCTCGTGTGAGGGCATAGAGATCT

          GCCGATGACCAAATACGGCCGAGATACCTTTCAAGGGGCTGCCCACGAAGGCAGATGTGT
          GCGGGCGAGAAGTAATATGGCAGAGATATCACCAAGGGTCTCTCACGATGGCCTCTATAT
          ATAGCCGATAACCGACGTCTCGGTTTCTTTGTCACGGACCTTGTACGAAAGCCGTTGTGC
          GCTCCGGATTGGTCACATCTCAAGTATGGTGACTGGAGTCCTACGAGAGCGATCCTATGA
          ACACCTGGCCTGCGATGCGCTAGGTATAGTGTAAAGGGCCAGTTTAGATTGACGTCGCGC
          AAACTCCATAAGGAGTGTCTTAACTGTAATGACAGGCGTCCCTTGTGAAGGGCGTGGTAA
          TTGGTGTACCACTTATGTAGCGAGCGTGGAGACAGGGGTGCGTTCTGGGTGGCAGCGGAA
          GTAATCTTCCACTTTTGGAGCGTCCGTGGCATTTAGCGCTCCCCGCAGGAGCTAGTGTGA

          ACGGAAATCACTGGGAAGCCGCCCCTGAGATCACGTCTACTATCAGTTGTCGCCAAACGT
          GTGCAGTAGGCTTGGAGGCTGCCCACCTGCTAATGTCTACCACGCGTTATCTCCGAGTGT
          ACAGCGACGATTTGAAAGCTCCCATCCAGTTGGAACCTTCCATGCGCGTTATCAAGCTTC
          GTGGCAGTTGCACGGGAGCCGTTCCTTTGATAAGATTCAAAAAACGCAGCATATCATCTC
          ATCAAAATCGGATTGGTATCAGCCTTCGGTTAATGTCTAACAATCGGTACACGGAATTGC
          GTAAGGTTGAGACAATTGTAGTCATTGTATTTGAGCATGGTATTTATCGCATGCAAAAGC
          CGAGTCATTGGACTTGTGAACATGTATCGTCTACGGAAAGCGGGGCTCGGGTGGTAAGTT
          TAAGTCATCCGATTTAGGGCCATTTACCGTCGACGCCCAGCGGACGCCGGGAACTAAGCC

          AGGGGGCAATGGTTATTGCGTCTAAATGTCTACCGACATATGAACCGACCAAGCAGTAAA
          GAGCGGTCCGTGGAATAGTGCTTGAACGCTCACCGTTTCATAGTACAATATGCCCCTGGA
          CGATGGCCTCAGGCTCAACGTTCTAGTGCCCATCGTCTAACACAAGAACGGGTGACTAGA
          AAGGGCATCCCCGAGGTGTCCTACCAAGCCCCGTCTTCTGTCCACAGATTAGCCACTTGT
          ATCAAACTCCGGGATTTTCACCTTAGTGTCTATCCTCGAGTTGTGGCTTAGGTCAGCTGA
          AAGGAGTCAGAGAAAATACGCTATCGTGTCTCCCCTTGCATTGTTCCATCAGACCCTTGG
          TAGCCGATGTTGAGCGCTTACATAAATGTCGTTTCCCACTCCCCACCGAGGTCAGGCGAC
          CGTGTGCAGCTGGGCCTCTAGGCCAATGACGCTTTCTAGTCCTTATCAGGAACGATGGTG

          CCTGTCATCGGCCTGAACCATGGGTCTAAAAATGTTCTTACCCCAGAACTTCGCCTGTAC
          CAAGATTGTAGATGAGAAAATACGGCCTGAAGCTATCCTTGTCCAAAATCTGTCTTGCTA
          TCCGCCCGTTGGTGCGACTGCTTAGTTAGGCGAGTTTTCGTTTTAACATCTGCCCCACTT
          TTCGTTCAAAGATAAGAGCGTACCTCTGGGAGAACTCTTACAACGCCGGCCACGGGTCTA
          ACTGGATACTAGGAGATTTAAATGTCTATACGAATTTTTCCATAATGGTCGACCCCTCTA
          CTTAAATGCGGGGGGGCTCTAACGTCTAGGATGTCCCTTTTCCCGGCCTGCACATAGCTG
          AGCGATTGCAAGTATAATCAGCAATTAGGCGGTAGTTTCCTTGCTCCCCTAAACTAATAA
          AGTGATTGAATGTGCGAGCAGCAGCTTGCGGGCCTTTTAGGTATCTCCTCTAACTGCAGA

          AGATCACCCTGCACGGTAGAACGGACGAAAACAGATTGCGCATTTACAAGCTACCAGTCG
          CAACCGGCCCGGCTAAGTGTACGGAGAGAAACAGGCTGCGCTCGCACAGCCGATCAACCG
          TAACAGGCATATACTCATGATTGAAGGGAATTGGCTAGTTCTTGTCCCGTGGGCCCGGTG
          TTGTACGCTCATTTGACTGTATATAAATAGACTGCACATGCGCAAGGAATCAGCCCAACG
          TAACAGACTTTCAGATCAATTAGAAGCCAAATATCTCGGGCCCACTCGGCTTTTAGGGCG
          GTTTGAATTTTCGTGGGTGGCCGAACAAAAGCCGTTCGCTGACATAACGCCTGCGGGGTC
          TGATAACCCCTCTCCATAGCATTCAGAGATTCCTTAGGAACAAAAACCGTCCAGTGCGTA
          GGAGAGCCGCTTTCTATGACTCTCAGTGACCCTTTACGACCCAGTATCGCCTATTGGATG

          GTACTCTCGGTGTGAACACCGGGCGTTCTCTGCGTGTAATGGTTCGGCGGAAATGTGGAG
          ATTTTCCTGACACGTATAGTGGCTGCTCCGACTACGTATCGTTCTACAAGGTGTGCCCGG
          CGTTTTCCGGCACGGATAACGGCTGTTTCAGTCACGTACCGCGCTACTGGGGCTGTGGGG
          AATCGCTTGGCGGGTCGAAAGTACGTTCGGCTAACGCGCCGCGCTGTTGTGTTAGCGGGG
          GGTTGTGGGGATAGTCTGGGGTGCTGTCCTATCAGCTGTTACGCTTTCGGGACTTTAGTA
          AGTCACGGGGCCCGTCTGTGAATTTTATTGATATGGTTTCGGGCCATAACAATTACGTGG
          ACGCCTCTAGGGGATAGTGGGGGTGTACGACGGAGAAAGTGAGTAAGTGCCGGCAGGGAG
          GACGTTCGACATATCACCGAGGGTGTAGAATAGAACCGCTGAGTAGGTTCTGATTGGGGG

          TTTTTAATAACCTCAGTAGAATTTCCGCAGCCCAAATCTG
          TCTATCACAAACTGCCTTAAGCCCTCGATGCCCAGATCCG
          GATACAGCGCGGCCCATCACATTAGTGCAGCTTGGAAGAG
          TTTACCATGAGTTGTCTTACCTCCCTGTGATTTTGACGTC
          CTCATAACTAAGCCACTAACCCGTCAGCGCTCTACACTTG
          TTCCGGACTACGCCGCCTACCTCCCCCCGGATTAGATGGA
          CCTAAGGCGTGATAGCCCTCTTCTAAAGGACACAGTCCGT
          TCCAAAGAAGGGGAGCCCGGTATTACATGATAGAATCGAA

