 8 1000
t1        AATCATCAGACTTAGTACAATTCGGCGCCGTCGAGTGATACAAGCTTCGCTGCAATACAC
t2        AGCCACTGAACTCAGCACGATTTGATGCCATAGAGAGCTTCGCAGTAAACAGCCATTTAG
t3        TAACTTTTGAATCTACGCGACTCAGCGCGTCCAAGGTCAACAGGGCCCACTCAAGTGTCC
t4        TAGATTTTGCGTTCACGCGATCCAGTGCGTCCAAGGTCAACAGGGTCCTTTCGCGTCTTC
t5        CATTCCAACCCTGTAAGTGGGTCGACATAGCCGATATTATGAGAGTCGGTCAATCCTCGG
t6        TGTCTCGGAAGAATTACCAGGACAGTGTGTCCGTCAGGTCTAGTCGTGACTAGCCGTCAC
t7        TGCCGTTGGACTACAAATAGCTCAGCATCATCGCAAGTTGAAAGCTTGGTCAATTCCTGT
t8        AGCCGCCGTAATCCTTGTGGCTCACAATGGCCACAAGCTGTAGCTGGAGGAGCATGTTAC

          TATGAAGACCCCGGTCACTCGCGAATTTGCCCATCCCTATCAATTTCCAGCGAAGATCCA
          CAGAAAAATCAATGCTGGTGGCGTTTTTGTCCACTCTTATCCATCTTCCGAAGAGATCTG
          TATGGCATTCCAAGCTGGTCGCGATTTCACGCATCCATAGCAATTGTCGGTGAACATTGG
          TACGGCATTCCAAGCTGGTCGCGAGTTTGCGCATCCATACCAATGGACGGTAAACATCGA
          TGCACGCCCCTGACTGGCAGTTGACTTCGTGAACCGTTACCAACGGCATGTGAGGCCGGA
          TGAGAAACCCCGACACAGCACTATTTTCATTAACCACGGTGTACCGAATGGGGGCACTGA
          TACTAATGCTTGGCCTCCATGCAGCCTTCTCACTTGTCGTACGTCAAATGTGGAAGTCTA
          CACTCGTTTACAGTCCGGATGTAACCACGCGGGCGATTGTAGAACGAACGACGAGCGCAA

          CTAGCACCCGTTCGTGTATGAACTAGGTAACATCGACTTTGGACTGTATTGGGCTTATTT
          ACCGCATAAGTTAGTGCGTCCGATGGGTAACGTACACTTAGAGCCGTATTGGGCGTATCG
          CCCGGAGCTGCCACAGATCGGATCAAGCAGTAATGTCCCCGGTTTTCAACAAATGAGCCC
          CCCGGAGTTGTCACAGACCGGATCAAGTAGCAATGTCTCTGACTCGCAATATATGTGCTC
          GTCGCAAATTGTCTTGAAGAGTTTAGCTGAGATTCCTGAAAAGCCGCTCTCCTAGTATAT
          CTCCCAGCATTAATTCCGAGGAACATTTGAGACAGCCGCAATGCTCCGTTATCTGTAATG
          ACTGTTCACCATGGTCCGCGGATTGATCAAACTGATTTAGAATTTTACCCGTGTACAACC
          CAGGAACCGGCTGCTGATTAGATTAGTTAGCATAGTAACATTTTCATGGCGCTTGCAACG

          TGGGGCCGTCAGTAGGAAAAAAGCATCGAGTGGAGTACCTGGAAACCTGATCATTTAAAG
          TGAGGTCGCGTGTAGGACCGTAGGATCGCGGGGGAAATAAGAATTCCTGATCATTTAAAG
          CGAGACTGGCCCTAGCGCTGTAGGATCGCGGAAACAACTAGGTACCTCCATCTCTCAGAG
          CGATACTAGTCGTAGCGCTGTGGGACCGCGGGATCAACTAGGAGCCTCAAGCATCCAGAG
          CGCTTTTACTAGATTCAAGTCAAGAATTGGGGACTTCGCATCCACAGCGGTCGGGGCACG
          CTCTGTTGGCCCCACCGCCATGCGTTTGGAGGAGTCCATTAAAGAAGGAGTCAAGGGGAG
          TAGATCTAGATGTTGCACGTTTTGGTCGGAAGCGTATGCAGTTGTTGAAAACTAAAAATC
          CGATAGTACACGTTTGGCAGCGCGCCCGCAAGAAAATGCAGAAATAGATACTCCTAAGCT

          CAACACACCGAATTCAGATGATAGGGAAGCCCGGTGATTCCCATTTTGAATTGTTGCTGA
          CAGAACATCGAAATCCTATAACACGAAGGTTTGATGATTTTAATTTTGAGAGGGGCAGCG
          TATAACCTTGAATTTATAACACGGCGACATCCGATGTCAATGATTGCAAGCTGGAATAAA
          TGCAATCTTGAGTTTACGATATGGCGAAATCTGATGTCCGTAACTGCAAACTGGAATAAA
          GGAGATGTTCACTTTCCGCGATACGGTGGCCTGCAGCCACTCGGTCCATATCCGGGCGGA
          GGAAACATTGACTTCGCCGGACCTTGGGGTCCACGCCTATGCTCCCAGTAGAAGCGTGGA
          CGAGCCATTGGCGGCGCATCACAAAGTAGCTTAACCGTTTCCAGATTTTCCACAGACAGT
          AGTGACGCTAACCGCTAGTTATTAAGTATCCTGAGTATATTTTCTACTGAACGGGTTGGA

          GGTCTTGCTGCTCGAGATGTAATGTGGCTATGACGCAAGATCTGCGAAAGGTAAAGGTCA
          GCTGTCACAATTCGTAGCATGCCGTGGGTTTGACGCAAGATCCGCCCAACGTCATTGTTA
          GGGGTCAGTGACAGAGACGCGTCGCGCCTATGAAGTTAGATGTTCCTAACGTGGCTTTCA
          TGCGTCAACGACAGAGACGCGTCGCGCCTATAATGCTAGATGTTTCTAACGTGGCTCTTT
          TTAATCGGTTCCCAGAGTACATATTAAATCGGGCGCGAGGGCGACAAATGCTTATTAACG
          CGAGTTAGGTGCTAGGACACCTTCTGGACGTTGTGGGGGGAAGTCTGTTTGCAATCAATG
          GCAGTTGTCGCGCCGATCTTACGGTATATCGGATGTACCAGCAGTTCGCTGTTACGAGTG
          GCAGCTAGTCTCTCGTTCCCCAGACTGTAAACGGACAGGGCCATTTTTCAGTTATGAGCG

          GCTTGCATTTGAATATATCAAAAGCGATGATCTAACCCGATTATTATGTCAGGAAATGCC
          GTCTGTACTTGGAAAACCCGTCAGCAACGGAGCCACCGGGCGTCAATCACAGGTTGGGCA
          GTTTGCGCTCGAGCGCTCCGTTTTCGAGATCCCGAATCGATGAGCCCCGCATAAAGTGGC
          GTTTGCGCTCAAGCGCTCCGCTAACGAGATCCCGCATCGATGAGCCCCGGATCAAGTGGC
          CCTTGTGGCCTATCACATGGCGGCCGACGTCACGTCTGGGTAGCGTCTGACCGGACCATT
          TCCTGTGGTGGCGTCAGTTCAGGTCGCTATATCACCCAAGTGGCGTCTAAGTGCGCTAAA
          GCCAGCGCTAGGAAGCGCGCTGAGGGATGCCCTAACAGACCGTCTACAAAGTCCATCACC
          GATTGCTACAGAGAATATGCTGACCAGCGATCATTTCGACTGGAGTCGTTATGAAACATC

          AGTGGGGATTTTACCAGTCGCAGCCCTATGTACGGTGAAAAATGACTTGAAAGGTAAGGA
          AATGGGAACACTTCTAGCCTCAGTATCACCAAGGGTGAACAGAGATTCGAGAGGTTAGGA
          AGTAGCGACTTTGGGGAGAGCGGCAACAAACGAGGTGAGTAGTACCAGGGCGGGTCAGAG
          AGTAGGGACTTAGGCCACAGCGGCAAGAAGCAAGGTAAACAGCACCAGGGCGGGTAAGAA
          TGTCAAGCAAGCCCGAGGTGTAATGATAAAAGGAGGCCAAAGCAATCTAGCACTTAAGGG
          TGAGGAACAACCCTGGGCCGCAGCAACATCAGGAACGATGGTGGACACGGGGCAAAGGGT
          TTGGTAGCCTCTTACAGTGTTGTTGACAAGAAGTGGGAGGAACATGCTGGGGAGGCCGAG
          TTTGAGGCTCTGCTAAATCCTATTGATGATGGAGGGGCAGACCGAGTATGAAGGGAAGAG

          GTTACCCGACATACGAGATTCTGGCTCTAGCATGCCGCTTAAGTTTGCGCTTACCTGCAC
          AATGTCCGGCTCACGAGACCCATTATCCAGCCTGTCGCTTCTGACTTCCCCCCTCCGTTT
          ACAAATTAGCGCGCTGGCTTTACAAGTCAGCTTCCCGATTAAAACCCCCTCGCCCCAATA
          ACCAATCAGCGCGCCGGCTTTACTAGCCAGCTTCCCGATTAAAATCCCCTCGCTCGGCTT
          ACTGTTAAAGCCATTGGCCCCGTCAATATGTATAACCACCACGCACTGACAGATGCCCGG
          AGTTCCAAAAGTGCTAATCCCGTAAGGAAGTTCTCCGGGGATGAAGTTACGGCCAGCTGG
          CCTGACATGGGAGCTAAACCTGTTGTCACCAACTCTAGACTCCTATAAGCAGCGCATTCC
          GTTAGCGACGGCACATGCTCCGCTGCTAACCAATCCAGAAGCCAAGTAGTGGCCAAGTCA

          CCGGGTATTGTCAGGGCATCACGTACTGTACTGTGGGGAAGCCGGGCCCGAGTGGGAGGG
          CCGAGTACCGGTAGAACGGCAAGCGCTGCATTGAGGGGTCGCTGAGACTACGCAAGGGAA
          GTGGGCGATGTTAGGTCAGCAAACGCCAAGCCGCGGAATAGCCAGCGCTACATAGGGAAG
          GCGGACCATGTTAGGACAGTAAGCGATATGTTGCGGAATCTCTGGAGCTTCATAGGAATG
          GGGAGCTTTCCCGAGGCGGCACGAGACTCGTTGTATGAGTGTCAGGCGCACTCTGGGAGA
          AGATGACTTCCTCGGGGCGCCGCTTTCTGGTTTTAGAAAAATTGGGGATGTGTTATAGAA
          GGGTGCGCCGATGGCGTGGATTCTTTATCGACTCATCGGAATTGACAATATCAGCTGATG
          GAAACATTAGTTAGCATGAAACATCTTTCGCCAAGACGACGTCCACACTCTTCCACTGGG

          AAATACGTACCGCCAAGCTTGCAGACCCTGCGGGGAGGTATTAATCCTCAAGGTATATCA
          TGCTACGCGGAAGTACGTTGGAGGTTCAGCCAGGCAGGCCCTCAGTCTCAGGGTACCTCA
          AACGGAGTACTTTCACGCTAGGTACCCCAGCTGGTAGGTCCGCTGTTAGAACGTAACCCT
          AACGGAGTACTTTCACACTCGCTACCCCAACTGATCGGTCCGCTGTTCGCGCGTAACCCT
          GGTCAATATCTAACATCTTTTAGGTCTTTGAAAAACTGCGTCTATTACCTCATTATGATA
          AAGCGCGCCCGGACATCCGTAAGGTCTTCTACAACCGGTGTCTTTGTATCCCCTGAATTA
          GCTCGTGCTGAATCATTCTGACCGCGCTCCCTAGCGGATACCTCTGCCGCCAATGAGGTT
          ACTTGGGCTATACCACCTTAGGAGCGCCTCACGCTCGACCCACAAGACATAATCGAGGTT

          AATCCTCCTAAAGAGCGGTGGGGAGCTGATGACCTCAGTTAGACTCCCGCTCCGCGCTAA
          AACAGTCGCAAAGAGCGTTGGGGGGTTAATGACCTCTCCTGAACCATGGCTCCGCGCGGA
          ATATCCGTGTCAGAATGACCGCCGGATGGAAACCACAATAGAATTCCGGTGCAGGGGACG
          ATCCACGCCTTGGAATGACAGCCGGTCGGAAACTACTATCGAATCCTGGCCCCGAGGCCG
          ACCCACGTGGTGGGTCTACGCAGAATAACTGACCACGACTGTACTTAGATTCCAAGAAAC
          TCCCGCGGCATAGCTCGAGATAGGGTAAGGGGGCATAATCGTGAGACTGACTTCAGCCCT
          TCACATGATCCATAAAAGGGTAGATGTGGTAATCTTGGTCGCATGATGATTTCAGGTGGT
          TCTTTCGATTTTCATAAGAGGAGATTTGACAATCACATTCATCTATTGACCACAAGCCGG

          GTAAGAGCATGCGGCGCTAAAACTGGGGTTTTCAACTCTAAGTTGCTGTGAAAAAACGTT
          GTAGCTGCACGCGACACGACGATTGGGCTTTCGATTCTTAAATTTATCGTAAATAACGCC
          GCAGCAGCTCGCGGGGTTATCACCGGGGCCTCACATCCTGCTTCAACCCAAGAAGAGCGC
          GTGGCAACTCGCGGCATTATAACCGGGATTTCATGTCCCGCTTCAACCCAAGTAGAGTCC
          ATAACTTAGAACCGAGTTCCCCTCCGAGGAACCGTCACGATCTGAGGTCAAGAACACGGT
          TCACTACAATGAAGAGCTCTAGTTTGCGATAACAATACAATATCGTGCCTTGAGGACGGG
          TCCCAACTATGGTTAGTCGCTTTAAGGAACAGTAATGGACGTTTAAATCGAGCACCTGGC
          ATCGACGGACAACTTGCTTTCCTCGGATGCGATAGTACGTGGTTTCCTCGAAATGGTCGC

          GTCTGTTAAGGTAACCTCCTCAGCAGGAACACGTAGCAGACTTTCCGATAGTATCTAATT
          GCTTGTTAAAGGATGATGCTCGGCAGAAACGCCTAGCTGATTTGCCGATCATGCTTGACT
          GTTTGCCAAAACGGGGTTTCCAATCGGAGCACGAAGCGCACTCGCCAAAAGTGCTCTGCA
          ATTTGCCAATACGGGGCGCTCAACCGGAGCGTGTAACACATGTGCCCGAAGTGCTCTGTT
          ATCCACGAGAGTCGATTACCTAGAGAAGCAACAAGCTACGCATACCGCAGTCGTAGAAAT
          ACCATTATGGGTCGGTTATCTCAAAAGGAGGGGCTACATGTATCTAGCGCATGCAGTTAC
          CTCAACTAGCGCACACCATTAGGAAGAATGATTATATGTGCCTTCCGGGGTGGCAATAGA
          CCTAACGACTACTCACAGTCAAGAAGCTTTTCTAAAGGAAGTTTTCGGGACCCCAATATA

          CTGTTGACTTTGTTATCGAATTTTATCTTATCTTCCCCTAGCACGAGTGCATGGCATAAT
          CCTTTTGCCTGGTGATTAAACATTATCCTAATCCCCCTCGATACAAGTGGCAAGGACAAG
          ACATTCGAACAATGACAATAGCCTGCCCCGATCCCTTCCGTTTCGAAGGGTTAAAAGAAA
          ACATTCGAACGATGTTTATAGCCTGCCCTAATCCGTTCCGTTCCGAACGGCTAGCACAAA
          ATGGTCAATCCAGGTTTGTATTTCGAAATTGTATTCGTGGCTATAAGCGGTCTATTGGAT
          CTATTCTCGCTATAACGGCATTTGGTCACTGACAATGTTCCTATAAACGGTACGTTAGTC
          GTCCTCGAGGTTTGAACGCCCTCAGGCATGTCCCTTTCAACAACAGCGGGTGCTAAGAAA
          TTGCGGAAGACATGACTCTTCCGAAGTGTGGCTTGAGTTACTACGGGTAGCGTAACAGAT

          TCATGAGATTCGGGATTACGGGAATTGCCAAGTGAGTGACTGGCCATTCGACTCTGCTGT
          CTATAGGATTCACACCCGCGGGGAACGCTAGGACTATGGCAAGCCTTTCAATTCAGCTTA
          CCGTATCATAAGCGCGTGCAATAACAACTGCGTTTTTGACCTGCACCTCTGTTTGGTTCG
          CTGTATCATATGAGTATGCGATAACTGCTACGTTTTTGACTTGCAACATGGCTTGACTCG
          ATCCACATCGTATGGCCGGGCTGATTGCCTGTTCCTTGATTGGAGTTGTTAGACTTTCTC
          GTCTGCCCAGGGTAGCCGTAAAGTCTAGCCGTCTTTTGTTTCGGGGTATTCGGATCCACC
          ATCTGAGTAGCGTTGATGATACGACTGTTAGCACCCCGTCTACATACACAGGGCTTTTTA
          CCAGGACTCGTATAACTTAAGTGATGGCCCATTTTTTATTGGGTTTCAGTAAGTCTATCG

          CCGTTTGTCAAGTCGAGATCGTGAATCGACAGGTGTACAC
          TCGCTGGCTTAGTAGTGTTAGTGGCGTAGCCGGCGTTCTT
          AAGTAGAAAATGCGATGATTAGAACGAGCCCGGTGTTTTA
          AAGTACAAAATGTGGTGATTAAAGCGAGCTCGGTGTTTTA
          CGTCTCATTGCGAGTCAGTATGGGAACGATCCATAATATG
          CGCATGGGTACACGAAAATGGACGACCAATTGATATTATA
          CGGCTCTCGAAGCGGCCTATCGAGTGATATTGAATACATA
          CGTTCAATGACGCAATCCAAAGAGAGCGATCGGAGTCACT

