 8 1000
t1        TATTCATTACGACCCCAATGCTTGATTTCAGTTTCGACGCAGGCTGCGAGGCGCGGAAGC
t2        TAATTATTGCGACCCTAAAGCCTGATTTCAAATTCGACATAGGCTGCGAGACGTGAGAGT
t3        CGGTCACTGCGCCTCAGAAGTCTGATCTATGATCTGATATAACTTGAAAGGCCTGGGAGC
t4        CAATCACTTCGTCTCATAAGTTTGATTTGCGATGCTACTTACCACGAAAAGCCCGGGAAA
t5        ACAGGATACCATCCACACGACGACTTTATTAGCGAGCTGATCCTAGGAGGGCCTAAGAGG
t6        CAGGTAAGAGTACCACAAATCTACTTTGTGAATAAATTGATCTATAGGAAGTCCAAGAGA
t7        TCAGTCGAGTGGCCGTTTAACCCTTCATCTAGCCAAGTGCTTCAAGACTAAGCCGAGCTA
t8        TGATAGTCCCATTGCAGTAACTGCTATTTCGATTAGCTCCCGTCAGTTGGACAAAAGGAA

          GATCCACCGCTACGCGGGCATGCTTGTCGGATTCTTTCAAATTATACGCCTAGCGCTTTA
          AATTAATCACTAGGGGAGCATGCTTGCGGGACTCTTTCAACTCATCTGCTTAAATCTTTA
          GGTTTGTCATCGGATGGGACCACCCCTGGGATTGTACCAACTGACCTAATCGAATCTTTC
          AATACGTCACTGGACGGGACTGCTACTGGAATTCCATCAGCTCGCTAAACTGCCTCCTTT
          CGTTCGTTTTCGCCGGGGTAAGCGACTAGGCTTGATTCGCATTCTATAAGTGGGTCTGAT
          CTATGACTCCTGCCCAAACGTGCAACCGCACTCGAGTCCAGGAGTTCAACCGGATACTCT
          GGGCTGCCCGTAACATAGTACGTCCCCTGATATGCTTTAAGCTATACGGCGGGGCCTCCC
          GGTTAAATCTCGCTAAGAAACGTCTTACAGCGTGGTTTAGGCAGAGCACTCGGGAATCCT

          ACAAGTATCGAACGGGCAAATAATCCCTAACGACGTCCAAGCGGAGGCTGGACAGTGTTA
          ACAGGTATCGGGTGGGCAAACAGTCTCTAGAGACGACCGGACGGGGGCTGGGCAGGGATA
          AAACGTGTCAAGCGGGCCAAAAACCCCTCGAAACGATTAGGGTCAAGATGGGTAGTGCCT
          AGAAGCGCTGGGCGGGTCCAAGAACCCTAGAAATGATCTGGGCACAAATAGGTGGCGACA
          ATGAGGGGCTACCAGGGTGACGGTTTTGCGAATCTGCTAGACGAGTAGCAACAGGGTTCC
          ACGGTGGAATGGCACAGTATGGTTCCGCAAATAGCGGCAGTCTTTTCTTCAAGGGCTATC
          AAGGTTAAGTGATGTACCGTAGGGTTGCCCGTTAATCTAGATAATCTGGAAGGATTCACC
          CCTACCCACTGACAGACGGAGGGCCTGCCCGATGTGCTCTGCCGTTAGCGAAGAACTATG

          TTAAGATTCGCTCAAGCGTCTTTCTACTTGTTAGGCAATCGATAATTATGGCGCTGAGAG
          TCAAGATTGGTCCAAGCGTCTTTCTATTTGCCGGGCTATCGACATTTACGGTGCATAGGG
          CCCCGGCCGGTCTAAGTGTCTTGCATAATCCTGGGCAGCCGGGCACTTAAATGAAAGAAA
          TTTCGATTAGATCACGAGTCTATCATGTTGCTAGGCCGCTGGCTATTGTAACGTTGAGAA
          TCCTGATTCCCTCCAGCGCTCGCACGGTTATCCGGCAATAGTGATACTCAGATTAGGGCG
          CTACAACCAAGTGTGACACCATCTTTCCTATCAGGTAACAGACAGTTCCAGCCTGCGATG
          GTTAATATCCATAAGGTACCAATATCCTTGTTGGAAAGATAAGACACCTAATGCTTAATG
          CAACGGGTCCTGAAACAAAGAACGCGGCGGTCAGATGGATGCCACACTCGGCACCGAATG

          TGACATGTACCGCTTCGTAGACTTCGCTCTTCTCGATGTCCGTACGCATCTTGGCCCCGC
          GAGCATGTGATGATTCGTAGACTTCGCCCTTTTCGATGACCGTATGTATCTCGGAATCGT
          CTGCAAACAACGGTTAGCATCTTTCCCGCTTTTCGATTACTGCGTGAATTCGAAAGCAGT
          ATGCACGCGAGGATTTGTAACTTACGCGACCGCTGACTATTGTGCGAATTCGGGAGCAAC
          GCGCGCTGGCACGTTAATAGCTCGCAACGTCGAATGCTAATACACCGTGTTAGGTGAAGC
          CGACACAAGGCCTTACGCACTCCGTGCTGTCGATGATCAATAAATCGGGTCCAGAACTAC
          TAGCACTAGATTACATGAATTTAGAGATGTTTCATGCTATCCCATCGGACATTGAGTAAC
          AGGTGTACAATCACGTGTATTAAATGCTGTTGGATGCCAACACAAGGGGCCTGCGGGCGT

          TCTGGCGTCTTCGTAGGGGCCTGTCCGTAGAGGTGCAGTAAGAGGATGGCATCGAGTTTG
          GCTAGCGTCTTCGTAGGCGCCTGTCGGCAGAGGTGCTGCCAGAGAATAGCATCGAGTTCG
          GTAGGCGTTTATACAGGTGCGAGTCTGGCAGGGTGCAGCTAGCTCGCAGCGCTGAGCACT
          GCAGACGTCTCTGAATGTGTGAGTTCGCTAGGGTACCGCTGGACCACAGTGTTGAGCCTG
          AGGGCAGCTTATGACTTCGAAGAGGTAGTTCAGTTCCAGAATGCCCCGATAATTAGACCG
          GCGTTAGCCCATGAGTTCGGCGTGGCAGTTAAGCGATAAACGGCTACTGCATTGGGTCTT
          ATAACAGTCCCCCTCTCGGAGGAAGTAGCAATGGATTGAATAATCGTGGCTCTAAAGGCG
          ACGGCCATCTTGGCTTCGGTCTACGCAGCAAAAAACTGGGGACTCACCGCCCCAAGTCGG

          GGTTTAGTTCTCAGCAGGAGCGGCAACAGGTAGTCAAGAGATTCAAGGTCAGCTGCTTCG
          GATTCAGTTCTCAGGGGGAGCAGCGACAGGGAGTTATGTGATAAAAGGCCAGCTGATTCG
          AGATCGTATGTCAGTGGACGCGGAAACAGGCGGGTGTCAGCATGAGAATAAGTAGCTTAA
          AGATCAGTTGTTGATAAATGGGGTACCAGGCGAGCATAATAGATCGAATAAGTTGGCTAA
          TATCTAACCTCAGTCAACAACGGACTGCGCAGAAGATTGCATGAGGGTCTGTAGGAAGCA
          AGAATATAACCGACCAAAACCAGTTAAGGTTAGCGGCTGTATGAGGATCTATAAGGAGCT
          AACCTGTTGGAAGCCCAATACAGGTATTGTCGGCGGTCACCTGGAAAACTAGAGAGCCGA
          GGACTATTTAGGGTCAAGCAAGGCTACTTGGTAAGCCCGGGCAGAGTACCAGAGGCTACG

          GTGACCCAGTTCAAATGATACTTGCAGAATCGGTTCTACTAACGGCTAGGACGGGTCCTT
          GTGACCCAGTTCTCGGAGTATCTGCACAGTCGTTCTTATTAATGGATAGGAAGGGTCCTT
          AACATACAGCTGTCATAATATTATCGCAACTAGTTTCATCAACGGATGGGAGAAGAACGA
          AAGAAGCACATGTCGCTGTACCGCTACAACCTTGTTTATCAATGGATTCGAAGGGCCCCA
          GTGACGAGATATCTGACGCCCCAGCTTCACTAAGGCTATTCTTGCCTTCGCGGATATTAC
          GTGCTAAGATTCATGACTCATCGGCTTTACCGACGTCACATACTGTCTTGAGAAAGTCGC
          GAGACGAGACTCTTAAGACAAAAACCTTCCTAGCGCTATACAGACATCACGGAGAACTGT
          CCGCCGACTTTCTCAACGTATGGGCTCGAATCATATTACTATAATGTCGGGAGGTGGTAT

          AAGGGGATCCGTTGCGTCAAAATTTGGTAAACTCTAGCCATAGAATGGATCTCAATGATA
          TAAGGGAATCATCGGGCCAAATTTTGGTGAACTCTAGTCATAAGGTGGATTTCAGTGCTA
          GATGGATCTTATTGGGACAATTTCGAGAGTAGCTCAACCCTAGGTCGACCCCCAGTGTTA
          TAAGGGCCCCACCGAGCTAACATCGTGAGGACCCCAATTACGGGTTTGACCCCGTCCTCT
          CCCTTAGGACCGTTAACCTAATTTCGTTACGCCCGAGCTGTCGATCTGATTTCAAGGATG
          TCCCTGGGCCGCCACGCCTAACTCTACTATGTTTAGTCTATACTTTAGGCACCGATGATG
          TCTTAACAACACCTGATTCTAACTCATTGCGGCCGATTTACTGACGACACTCGATAGACT
          CCCCCGGTATGGCTCGGACCGTTCTAACGGGACCAGGCTAACATCGGAAACTCTAATGTC

          ACTTGCCTACGCATGACGGAGGTGAAATGGGGTACGACTATAGCTGTGATTGGGCTGTGT
          ACTCGCCTGCGGACGACGGAGGTAAAATAGGGTACGACTTAAGCATCGATTCGCCAGTGT
          GGCTACCTGAGGTGTCTAGCGATGTAATAGTATCCTACCGTAGTTTGGTTTCCACAGCGT
          TAGTACCTGAGATATTTGAAAATGAAACGGGGTTACATCTTAGTGCGGGCATCGCAGTGT
          GTTTTACGTTATGGCTTGACAGTGGCACAGGACCCATTGCCGAATTCAATTTAGCAAAGG
          TCGCAGCACCTCTGCATGGTGGTGCCCGAAAAAGATTAGCCGAGACTCATATTAGAATGG
          CAGTCACGTCAAAAACCTGACGAGTCTCAGAACCGTTTTCCGACTTCAATCCGGCACTGT
          GTAAGCTAACTACCCCTGGCGATAGGGCGGCGCGGCTTATGGAACTGTATCTGGCACTGT

          CTTCGTGGTGATTTGGAGAGCAGGGCGCGGAACACGCCCCGTAGATGCCAACATTAACCA
          ACTAGTGGTGTCCTGAAGAACAGGGCCCAGAACGCCCCCCGTAGATGCCTATACAAATCA
          TCACGGGGAGGTTTATATCACACGATTGGGTTCATCCTCCGTGGACGACCACAGCCATAA
          CAAAATAAGGGTTTACGCTGCTAGGCTGAGCTGATTTGCTATAGGTGGCAGCGAGAAAAA
          TGAAGTCAGTTTCCTCCGTCCATTATTTCGATTCGGTTTGTTAGGTGGGGCCACAATCCA
          TAGAATCAAAAATCGCAGTTCAGTCTATCCAGACTGTTTCATAGGTAAGTTTCCAAGCTA
          CACGACGGTGTGCCATTAACCGACCCGACGTTCTCCCGGTGAGGGCGATGTCCCAAATCA
          AGGATTCATCGAACATACCTTTTGTTCCAGCATAAGCCTTGTGGGACGCGTTAGCCGCCG

          GCTGTTGACCGATAGGTCCTGCGGGCTTAGTGGATCGCTCTTCAACTTCCTGCGTTAGTA
          GCTGTTGATCGCTAGGTCCTGCGGTGCTGGCTGGTCGCTCTTCAACTTCGTCCGCTCGTT
          GCCGCTGATATTCGGGTCCTGCGGACATGGCCGGTTGGTTATCAATTTCCGTGACTGGCT
          GCCACCGAAGGCTGGGTACTGCGGGTTTGACAGGCGGGTCATCAGCTTTCCTAGATGGCT
          CCTACAGAGAAGCAAGCCTAGTGCATTTGATAGTCTGGCCTCACTAATATGCTCGATACT
          GCAAAAGGAGAGAAGACGCATTTCGCTAGACCATCTAGGCTCGCAATTATAGTGCAAATA
          ACTACACAGCAATGGACAAGCTGCGTTTGCGTGAGCGGATGCGAATTCATTTGCCAGGCA
          ATTACGCAGATAAGGATTATTTATGCTTGACCCAATACACGTATTGCTCTCCGCCGCGCC

          GGGCGCGTATGAGACAATCGCTGTGGGCAACGGTGCATGCTCTCAGTCTGTTAACGTATT
          GGGCACGTATGAAACAGTCGCTACGGGCAACGGCGCATGCTGGAGGTTTGTTAACGTATA
          AGCCGTGCTCGAGACAGGCGTAGCAGGCTATGGTATAAGACGTCGGAGAGGTCATATGCA
          AGGCGAGTATACGGCAGTCAAAATACACTATAGCGAGACAACTTGGGGTATCTTCGCGTA
          AGATGCATGTTACCTGTCTATTGCTGAGAGTATAAGGTGGTAACCGTAGCTCGCTATACG
          AGAAGTGCATCACGGAGTCCGACGTTACAGGGCAACCTAGCCAGCCCGGTACGGCATGTC
          AGCCGTGCGCACTGCCATAGTGGACTGCCGTGCCACACAATAGGGCGGCTTAGTACGACA
          GGACAAATGCTAGATGACTGTGGCTGGTGACATCACGTACTACGGATAGTGTCGTCCATG

          CTGATACGCGTTGACAGCGACGTGATGTCGTAAGTACATATATAGCACCGAACAATATCA
          CTGATGACCGTTGACAGTGACGTGATGACGTAAGTACATCCATTACGCTGAACAATATAA
          TTGGCAGATCATTATGCCGACGTGTAGACGTAAGTCCCCATACTTCGCAGATAGCTAGAA
          CTAACGGTTCATCATGGCGACGCGTCATGGTCTATGCATAAATCGCGCAGAAAGTTAAAG
          CCAGATGTACATAGTGGGGATAATATCTTACGGCTATACTTCCGTAGCAGCTAGTGGTGC
          CTGGATGCATACTCTACCACAAACGTAGTGTAGTCGCAGTTGTTTAGTAGCTAGCGGGGT
          CTAGAAATAGGAAACGGTATCAAACCGACGTCGAGGTATTTCCATCATGGACAGTGAAGG
          ACGGGAATTGGCGTCGGAATCGTTTCTAGATTGTCTTATACTTGTCATAATTAATATTCA

          TGCATGTCATGGCGGCGCTCACGCATCGGCCGCTATGAGATTAAAAATCCTAGAGACACT
          TGCACGCCATGTTGGTGTTTACGCATCGGTCGCTAAGCGGTTAAAAGCCCTAGTGATACT
          CGCATGCAATGATCGCTGTCAATTTCTAGATCCTAAGCGTTCAGGAGCGTCAGCAACGCT
          CGCGTGCGATAATAGTCCTCATGCTTCGAACATTAAGGAGTTAGGGGTGCCGGTGACACT
          CGCATAAACACCCGAGTGTTAAATCCTTGGTAGTAGAGGTCCGGAATTGCCTTCAGATTC
          CGCCAATCCATCTAAGCTCTCAACTCCGGGGTGCGGAGGGTTCGACATGCCCACACCGAA
          CGCTCGTACGACCGCCCATTAACTATTAGGGTACAGTAGGACGGACCTGCCCACTTAGTC
          GGCCGAAATAACCCTCTGTTGAGTTTGGGGCCGGATGGCGGCCGACGTACACCCAGAGCT

          GAATCAATAACAATGAGCACATACTAAAGGCCCGGTAGCATTGCCAAATCTAGTGTCCGT
          GAAACAACAGCAACGGGCACATGTTAGAGGCGCAGTTGCATTCACAAATCCCGCGCTCGT
          GACTTTGCAGCGTTGGAGCCGCGTTTGCGGCCCAATCGCAGCGAAGTAGGCTGCCTCCGC
          GTATTAGCAACAGTAAAAGTATGTTTCGGGCACAGTTGTATTGGTAAATGCCGCGCCCAT
          AGCACGGCCCAGTTACAGGTGCACATATCGAGAGATCAACCAGAAAAGCCCAGTGTTTAC
          CTACTGGCCCGTTCGCAGACGTACATACGGAGCCCTCAAGTCGCACAAATTTGCAGTCTT
          AACAAAGCCCAACTTCACATCCCCGTTTACGGCACAATCATGATGCACTGTTGTAAACAT
          GACTTCGCATGGTCGCGGTTTCATGCCGAGGAGTTTCAGAGTACCTCAATCCACGGTTGC

          GCGTCGACGTTCGGCAACACGCTAAGCGATCGTTCAAGTC
          GCGTCGGTATGCGGCACTCGGTCGAATGGTCCCCCAAGTC
          GTGTTGCATAGTGGCTCCTAGTTTAATGGCTAGTCAAGCA
          ACGTCGTTAAACAGCTACTAGTTGAGTGACCAGTTAAGAG
          TTCTCGGGTCGTTGCTTTCAATACCAAGTAACGCGATCCG
          CTGCGGATACATGGCTCGTCATCGAAGGCACTGCCGACCG
          CCCGAAATACGTATTTAAACGTCAATTATTTGGCGTCTTT
          CTCACGACGCACGATCATTCGTCGGACTTCTGACCGGTCG

