 8 1000
t1        ACGGACCGCAGTGCCAATAATATGCTTGAGAATTTCGCGTGAAAATGCCCGGATGAGATA
t2        CCGGAGCGCAGTGCCAATACTATGCTTAAGAATTCCGCGTGAAAATGCCCGGATGAGATA
t3        TCGGAGCGCAGTGCCAATATTGTGCCTAAGAATTCGGCGTGAAGATGCCCGGTTGATATA
t4        TTCGAGCGCATTGCCAATGTAATACTTCAAAATCCTGCATGACAATGCTGGAATGGGATA
t5        CCCGGGCGTGATACCAATGCCGAATTTGAGAGCTCCTCATGATACTCTTATAACGGGGGA
t6        CCGGGGGGCACCAATAAAGTTGGACAACGGCATACTTAACAATACTCTTACGACCGGGTG
t7        CCACCGAACGCCACTAGCAGAAATTTTCAGTAGGATCAATGTGTCTGGCATCAAACCCGC
t8        ACTCGGTGCCCTGCCGGTAGGCACATTCGGCAATTTCGCCCCCACGAGCATGAAACCCAA

          GGAGGGATTTATCTCATAGTACCCGTGGGTTACTCAAGGAGTTGGCAGATTTTTGAATTA
          GGAGGGATTTATTTCATAGTACCCGTGGGTTACTCAAAGAGTTGACAGATTTTTGAATTA
          GGAGGGATTTATCTCATAATACTTGCGGGTTAATCAAGGAGTTGACAGATTTTCGAATTA
          GGTAGGGCTTATCTCACAGTCTCCGCGTGCTACTCAGTATGTTGACCGATATACCTATTA
          GGAGGCGTTAACACCTCAATATCGGCAACTCACATAACGGGTTGAGAGCTTTTCGAATCA
          GGAGGCTACAACACCTCAACGTCCACGCCTTAACTAACGGATTACCCGCGATTCAAACCA
          CACGATCTAGGCGACCCCGTATCTAATCTCTATGCTTTTAGAGCTTTAGCAGCGGATACG
          AGCGATCCGGGAGGCCCACCATCCGACATCTATGATCTTAGCGATCTATCAGGTGGAACA

          GTACCTCTTGCCAAACTGCCCTATAGACTAATTCATACAGGTGAGCAAAATGGCGAGCTG
          GTACCTCTTGCCAAACTGCCCTATACACTAATTCATACAGGTGAGCAAAATGGCGAGCTG
          GGACCTCTTGCCAAACTGCCCTATACATTACTTCATATAGGTGGGCAAGGTGGCGAGTTG
          GGATGTCTTACCAAATTGCCTTAGCTACAAATTCATATGAGTGAGCAAGGCTATGAGGTG
          GTATCGCATGCCGTAGTGTCGTACTCTCAAGCTCCTCGCGAACCGCAAGATCAAGAGTGT
          ATATCACCCGCTGAACCTCCCTACTAGGCAACTTTCCATAGAACGTACAGTCACGAGCCC
          ACGACCTGTGGATCATCTGTATTACCCCCATCTATCAGCAATAAGGACGGGGGTGTGATC
          TCGTTTCGTGGTCTACACGAGTTGCTCTAGACTATCGGTCGCCAAGGAGGAGATTTGGCT

          TAACATGCATGAAATAGCCTGCGATTGAGTGAAAGGGCTGACCTAGTGTCAGTGATTGCT
          CAACACGCACGAAATAGCCTGCGACTAAGTGAAAGGGCTGGCCTAGTGTCAGCGATTGCT
          TAACATACACGAAACGGCCTACGATCTAGTGAAAGGGCTGTCCTAGTGTCAATGGTTCCT
          TCAAATGCACATAATGGTCTAGAATCGTGTAAACGGACGGAGCTAGCGTTAGTGATTGCT
          CTGTCCGTTCTTGATAGCCCGATCCCACGTGGCAGGATTGAAGTAGGGTAGATGCCAGCT
          TAACGCGCTCGTGATTGGCCAGATCCGTGTAGAGGGATAGAGGTACCAGGGGTACGGGCT
          GTCTAAGTAGACCATAGCATGGTCACGCATAGCATGAAATTCTTTGCGAGTGGGTACATC
          GACTTATGGAATCCCCGCATAGCGACGCCTAGGATGAAAATCGTTTTGATTCAGCATAGT

          TTGTCTACAACACTGCGATTAAAGTGCGAAAGTTATCTGCTGAAATTTCAGGGTGGTGGG
          TTGTTCACAACACTGCGATTAAAGTATGAAAGCTACCTGCTGAAATTTCAGGGTGATGAG
          TCGTCCACAACACTGAGTTTAAATTGCGCAAACTATCCGCTGAAGTTTCAGGATGGTGGG
          CCACCCACGATACTGCAATTGAAATACGAAAGTTCACTGTTGAGGTCCCAGGATGGTGTA
          CCGCCAGTACCAGAGCGGCTTTAATACGGGATCCTGTCGATGAGATGCCAGATTTGCTTT
          CTGCCAGCGACAGAGTGGCTGCTCTACAGGAACATTTCTGTGAGGCCCAGGTTTCGTTCA
          TCATATATGCAACAACGCCCATCAAAGTAAAGTTCTACACACTCAGGCATTCGAGGATTC
          CCAGAAATGCAAAAATGTCTACGAGACTGTCGCCCCAATGACAAAAGCTCGCAAGAATTA

          GATATGCGTCGATCACCTTATGGTAAGGGCGACCAGGTGCCAGCGGTATATTCCAGTCTA
          GATATGCGCCGATCACTTTATGGTAAGGGCGACCGGGTGCCAGCGGTATATTCCAGTCTA
          TATGTGCGCCGCTCACTTTATAATAAGGGCGACCGGGTTCCAGTGGAATATCACAGTCTA
          TTTCTGAGTAGACCACTCTATGTCAAGCGGAACCGGGTTTCGGCGGTATACCACTGCCTG
          AGTTTGTGTGATCCCACTGATGGTTTTAGTACTTCGAACTAGGAGCGGGCCTTCCATCTA
          TTTCTGCGCAAGTTATGCAAAGTCACCGGCGTCCGACACTGGGCGTCAGCCTTCTACCTA
          TCGCTTATCGATTTACTCGGTAACTGGGTAAAACCGCCAGAGATTATCTCCCTCTGTAGC
          TGGTTCTCCTACGCATCGGGCAGCAAAGCTAGAAGGCTAATGTAGACAGCTTGTCGTAAT

          CTCACAAGAGCGGCAATTTACTAACTAGATTTAGCGCCCTCTCCAATTTCATTTGAGTAC
          TTCACAAGAGCGAGAATTTACTAACCAGGTTTAGCGCCCCCTCCAATTTAATGTGAATAC
          TTCATATGAGCGCCAATTTACTAACTAGAATTAGCGCCCTCTCCAATTCCGCTTGAACAC
          TTTATAAGAGCGGCAACTTTCTAGCAAGACTCAATGCCAACTTCAATATTATTTGACTAG
          TATCAAAGAGCGGGGATTATCTTCCTCACTCGAAAATCACCTTTGGGACACTGTGACTGC
          TATCGGAGGACGGCGGTTCTTCTTCTTGCTCCAAGGATACCTTTGGTACACTGCGACTGC
          GGTGCCTTGGACGTGCTGCCCCCTCCCACTATAACGTGTTTCTCGGCCCGCTTTGATTGA
          AGTGTCTGGGATGTGTTTCTCATATCCACAGTAGTATACCCCCTAGCCCGTCTCAATTGT

          GGTTCTGATATCTTCGAGCCCTTTCTCGTTTTAGTCGGGGACCGATGGTTCAACAACCCA
          GGTTCTGATATCTTCGAGCCCTTTCTCGTTTTAGTCGGGGACCGATGACTCAACAATCCA
          AGTTCTGGTAACCTTGAGTCCTTTCTCGTTTTAGTCGGGGACCGTCGGTCCAACTACCCA
          GCTTCGGAGAACCACGGAGCCTGTCTTGTTCTAGTCGGGGACCGCTGGATAAAAGACCCT
          ACATGCGACAAACCTAAACTTCCTGTCGGAGCAACTACGGAAACCTGAGTACTATCTCTA
          ACTCCTGCCACACCTTAATTTCCTCACGAGAGGGCAACGTAATCTTGGCTGAAAACGTCG
          GCCCTTGCTACATGATAGACATCCTTAGGTTCAAGAGGGCAACTTCGATTAAGTAATTCT
          GTCCCCTCTGCACACCGGATTTAACCGGTTTTAATGCGACACCGCCGGCCAAGAACCTCT

          ACGGATGGTCTGTACAAGCGGGGGACATTCACTTAGATTCCTCTCCAATGGTATACTGAC
          ATGGATGGTCTGTACAAGCGGGGGACATTCACTTAGATTCCTCTCCAATGATATACTGAC
          ACGGATGGTATGTACAAGCGGGGGGCATTCACTGCGAGTTGTCTCCGATTAGATACTGGC
          ATGGATGGTCTGTGCAAGGAGGGGACGATTACTGTGACTTGCCTCCAATTGGATACTGTC
          AGGAGCGGGTTGTCCAGACGAAAGCCTACAAGGCTAATTTGCCGTCCTTGCAAGAGCGAC
          AAGCGTTGGTTATTCCATCGAAAGTCTATTAGTAAAATCTGCTCCTCTTTAAAGTATGGC
          GTATATAGTGCATGCCAGCGGCGCAGCCACATCCAATGGGGTACGTTCTCACCATTCGCG
          GCATTTAGTGCCTGGCGGTGACTTGGTCTGATTTGATCAGGAATGCACGCAGGACTTACT

          CATATGATCAAACCTGTTTGGCCGTAATCGAGAACCCAGAGATTGTTAAGATGCCTTTAG
          CATATGATCAAACCTGTTTGGCTGTAATCGAGAACCCAGAGATCGCTAAGATGCCTTTAG
          CATACAACCAAACATGTGTGACTGTGACAGAGAACCCCGTGAATGCTGGGATGCCTTTGG
          CATAGGATCAGCCCTGCTCGGCTACAACAGAAAATCCCGGGATTGCTGTGAAGCCCTTGG
          AACGAAACTAGCCTGGATTGTCCTCTAATGAATCTCCGAGAACCATGCTGGCGTTAATAT
          AACGCAGCTAGATTAGTTTGTCTTCACCAGACTCTACGAGGTTAAAATTGGTGTTGACGA
          TACTTACTAAATCTGATCTAGCATGAGTAGGGGGGCTCGAATTAGTTAACCAATCAAGTG
          CACCTACTAGAAATGATATGCAGGCAGCAGAGAAGTCCGATCTAGTTTATGGGATTAGCG

          TTACTGCGATCACTGGATCCCTCTTACTTATCCGTCCGGTTGCGCCCCATTACTGGGTCA
          TTACTGCGCTCACTGGATCCCTTTTGCTTATCTGTCCGGTTGCGCCCCATTATTAGGTCA
          TTACTGCGATGATCGGATCCTTCTTACTTATCCGTCCCCTTGCGCCCCATTATTGTGCCA
          TCACTGCGATCGTTGGATTCCAGTTCGCTATCCGTCCCGTTGCGCCCCGTAACCGAGTCC
          CCGTTACGTATGATGAGTCGTTTCCATTCGCGCATTACGTTGACAACTGTGAGTACGCTT
          CCATTGCCTATGTTAAGCCGCTCTCATTTAAATGCCGCGCTCCTGCCTATAAGCACGGAT
          TAGTCCCGACTGATCGACAGCTAGAACACATCCGGTATAGTTTGGAATGACCCTACGTAC
          TAACCTCAATCCACCAAAGGCTAGCATAGGTATGGACCGGCGTGAAATGTCCCTATGAAC

          ATGCAAATCGTAGTCGTTCGAGATTCCCGTAAGAGTTGCTGTCTGTATCTGAATGAAGTG
          ATGCAAATAGTAGTCGTTAGAGATTCCCGTAAGGGTTGCTGTCTGTATCTGAATGAAATG
          ATGCAGATCGAAACCGCGTGAAATTTTTGTAAGAGTTGCCGTCTTTGTCTGAATGAAGTG
          ATGTAAATAGAAGCAGGCCGAAATCCTCGTAAGATTTGTTGTCTGCATTTGAATGAGTTG
          TGGTAAATAGATTTTGTCCCAAATTTTGGCGCTCGCTGTTGTTTCCGAGTTTACGAACAG
          CAGTGAGGTGATTCCAACCCAACTTATGGCGTGCGCCGTCGTTTATAGCTTAGTGGATAC
          AGAACTGGTGGCAGCGAGAAAAAGTTTGCAGGGCATGGCTGCTTTAAGGCGTTCACGGGT
          GGAACGCATACGAATGAGATAAGTGTTACAGTGCGCTTCTGCTCCGAGCCGTTCGCAGGT

          TCATCGACAGTTATCCTTGGATCGACTTAGTGTGAGATCAGCTCTTCCCCAGATGTTTAG
          TCATCGATAATTATCCTTGGACCGACTTAGTGTGAGATCAGCTCTTCCCCAGATGCTTAG
          TCATCGACGGTTATCCCTGCACCGACTTAGTGTGAGATTAGCCCTACCCCAGCACTTTAG
          TAAGCACCAGCAACTCGTGGATCGACTTGATCTTAGATCAAATTTCCGCCAGATATTTAG
          TCACTGGTAGCCCTCCCTGGATGTCCCCAATGCTGAATCGGCGTTTCTCCGTTAAGTTAT
          ACACTGATAGCGCTCCCCGGTCCTGTTTTGTGCTCATTCGGCGCTAGTGTGCTTGTTTCT
          ACAATCCCATCTTTTCCCCCTTAAGCTCAAACTGGGAGCGCCTATAGATCGGGCACTGTG
          CTAACTTCTTCTTTTACCATACATGCGTAACATAAGAGTGATCCCATGTCGTGCTGCGTA

          TCACGGGGAGGGCCTGAGGGGTAGAGCTCGTGAGATCAGTGATCGGCTCTCCCCGTCATG
          TCACGGGGAGGGCCTGAGGGGTAGAGCTCGTGAGATCAGTGATCGGCTCTCCCCGTCATG
          TCACGGGGAGGGCCTGAGGGGCAGAGCTCCTGAGATCTGTGATCATATCTTCCCGTCCTG
          TGACGGAGAGGGTGTGAGGGGTAGAACCCGTGGGATCAGTGAACAGCTCCCCCCGTTTCG
          CTATGAAGGTGGCCGCAAGGAAGGAACGCGTCAGACAATTGACAGGCCTACTACACCCTA
          GTGAGGAGGAAGCCTAGAGAAAGAAACGTGTGAGACCATTAACAGGTTTTGTCCAGGCCA
          CCAACAACGGACAGGGCTGAGGTGACAGCGCATCGCAGGAAATCGGTTCTAAACTTTACG
          ATATGAGGGAACTGGACCAAAATGGCCAAAATGGGACGGAAATTGGAACACACGCTAACA

          GCATCCAAATCAATCAGTCGTATAGGTCCCATCCGATGTCTGTGGAAGCCTACTCGCCCC
          GTATCCAAATCAATCGGTCGTATAGGTCCCATCCGATGTTTGTGAACGCCTACTCGCCCA
          GCATTCAAATTATTCGGTCGTATAGGACCCTTCCCACATTTGTGGACGCCTACTCGTCCA
          GCAATTAAACAGTACGATTGTATCCGCCCCATGCGACATATGTAGGTGCCTACTAGCCAA
          ACGTCTCAATTTTCTAGCATAGTGTACTTTTCTTATAATTTCTTTGCACTCGATCGAGCA
          TTGTTCTAAAATACTACCAGAGTAGACTATAAACCTCATTTACTGGCGGTTGAGCTAGGA
          ATGTTCTAACGGACTAGTAGCCCAAAAACTAGGTCCCATATTATTCCACTAGGCTGCGCG
          ATATCCACTCAGACCACTGGCGCCATCATTCAGTAGGACATTACCATTTATGGGCGCGCG

          GCGCCCAGGCCGTCCGGTGAGTCTTTGTTTGCTTGTCGTCTCCAAATGGGTGCGGATTAT
          CCGCCCAGGCCGTCCGGCGAGTCTTCGTTTGCTTGTCGTCTTCAAGTGGGTGCGGATTAT
          GCGCCCAGGCGGTCCGGTGAGTATTTGTTCGCTTGTCGCATCTAACTGAGTGCGGATTAT
          GTCACTAGGTTGCCCGATGAGTTACTGATAGCTTGTAGTCCCCGAATAGGTGCTAATTAT
          GACTCTAGTTCGCGTAGTAGGATGTGCCTAAACGGTAATCCCAAATCGAATGCCTATCCC
          GACTCTAGTCCGCGCAGTACGACGCTCCTTGTCAGTCATCTCACAGCGGCTGTCAATGTC
          CCCCCCAGGAGATGCCCGGAGCTTCGCCTAGTCGAATGCCAACGAGGCGTCGCAGGTGAA
          CCCTTCCAGTTGCTCTCTTAGCTATCCTCAGTTTACCGTTACGTAGGGGCCGAAGGCTAG

          CTAACAGGTCCCCGACGTTTCCCGGGTTCCTCCGATCGTT
          CTAACAGGCTCCCGACGTTTCCCGGGTTCATCCGATCGTT
          CTAATAGGTTCCCGACGTTTCTCGAGTTCCTCCGATCGAT
          TCGACAGGTCTCCAACTTTCACCGAAATCCTTCGATCGTT
          ACTACAGATTTCGGGCACCTTTCCTGCTACTTATCTTTTA
          ACCGGGAGTTTGAGGCGTTCCTAACGCTATTTGTACCCTA
          ACTGTGATATTTAGACTGCAGAATCGTCAGGCCCCTTTCT
          GGTGACAATTTGTAGTATGCATCTCTTTAGGCTTCCTTAT

