 8 1000
t1        CCTGCCAGCCACGGGGTCGAGGTTACCTTTAAGTCCGTTTCGCGCCTACTCAGCTATTTG
t2        CCTGCCAGCCACGGGGTCGAGGTTACCTTTAAGTCTGTTTTGCGCCTACTTAGCTATTTG
t3        TCCGCCCCCCGCGAGGGCGAGGTCAACTTAGAGCCCGACCCGCGTATACTTAGTTCGTGG
t4        TATACCAAGCTTACGTCCTAGAGTGACTCTGTATTTAAACTGAGACACTTCGAGCACTGC
t5        GAATCAAGGACATCCGAAAAAACTTAGCTAGGATCTCGGCCAAGAGACATCATTCCCCGA
t6        AGTTGACTGCTGATGGCAGTGGATGAGTGAGGCCTCACATCATGACAGGTTTGGCGTACC
t7        GCGTCGCCTGGACTGACCTCGCTTAACCTACGCAATGAGCTAAGAGATTTGCCGGGTCAG
t8        CGTCCTCGAAGGTTAGCGAAGGCTAGTTAATGACTGTGACTAGGCTTCTCTCAGATTAGC

          ATTGCGGATCATTTATACACATTTGAGGCCGGGCCATCGGTTGGTAGAGTGGCTTGGCGA
          ATTGTGGACCATTTATACACATTTGAGGCCGGGCCATCGGTTGGTAGAGTGGCTTGGCGA
          ATAGCGAATCGTTTACACAGGTTTGAAGGAGCATTGCCGGTCAGTATAGCAGTATGGCTG
          GTCAAGGGCCGTTTCCGGCCACACTCTTCCCGTTTTTAGTACTGATCTTGAGCGAGGCTA
          GCATTAAGCTAGCATTGAAAAACCGGCGTCGGGCACTCGCTGTATTTCGAGGACAAATAT
          ACTATGGACTTCTCCTAGGGAGCTGCAGGCGACCTTTCTCCCTACGTGGAGCCATGGGGA
          TTTAGGTTGCACTTCCACAGAAGAGGCTCTCGCCTCTCGGCTTTACTGGGAAAATCGCCG
          AGCGTTGCCGGTCTAGTTAGCATCGGCGACGACTGCGTACACAACCTCTATTAGTAAATT

          GAATGTTGAGACTGACTGTCAAATGGAGTTAGAAACCTATTCTGACCGCCAACTTTATGA
          GAATGTTGAGACTGACTGTCAAATGGAGTTAGAAACCTATTCTGACCGCCAACTTTATGA
          AGTAATTGACATTATCGGTCCAAAAGACCAGGAAATTCATTCTCGCCACCAGCCTCGAAC
          GGAGACCATGAGGAACGGCACTCCGAATAAAATACGTTATTAAGTCCGCAAGAAGCGTGA
          CGGGGCCGCTGTCGTCAATACGAGGGACAGAGCTCACGAGGTAGAGGGTCTGACCCGCAC
          AAGGTCCAGAGAAGCCCGTGTTGTGTTAAAGGGGCGCTGTTCCTGCAGCTTATTCGGCAT
          GCAATACGTATCATGCAGACTGGTTAATAGAGGATACACTCCGCAGACCAGGCAAAACGA
          CTAGATTGCATTAGTTTGGCTTATGATCCTAGCGGGTTATTTTCTAAGGTAGTCATGCGA

          GTGTTTGTTGCGGGATCTTGACTACATATCGAGGAGAGCGTTTCCTTTACCGATCTATTT
          GTGTCTGTTGAGGGATCTTGACTACATATCAAGGAGAACGTTTCCTTTACCGATCTATTT
          GTGAATGTTGTGGCACGTTGGCTCGACCTCGGGACAAGCATTTTCTATACATGTCTTTCT
          ATAAGTGAACCAGGATCGTGAATGGTCGTTCGAGCGGCACATCTTTACAATGACCTGTTC
          ACCAGCGAAGTGGGAAACACCATTGCTACACAGTCGTCAGCCCCCCATATTCGCGAAAAT
          GTGAGTCAAGAGGAACGGTAGCATCGTCACTTGCCGGGCTGATAATGTGTCGACCAACTT
          CTGAGCGCCATGAAATATTGGCTCCCCATTCGGGCGGCCGGCCATGTGATCTTCTAACCT
          CCAAGCAGGGCAGGGTCAAAACTCTAAGCCGAGGTGGATAACCGCTCCCGACGCCTACTA

          TTTTACTCATTTGTGACCCATTTTCCACACTAAACATAAACCGTGTACATCAGGGCTTTA
          TTTTACTCATTTGTGACCCATTTTCCACACTAAACATAAACCGTGTACATCAGGGCTTTT
          TTTTCCGAGTCCGCGACGTACTCCGCGTCTTTAATTTCAAAAATCAGCATCAGGGCTTCT
          CTAGGTTGAATCGCAGCGGCCACAGTAAATTTGAATTAAGTCCCTGCTGGGCTACATGAT
          GAACCATGGCTCGATTTATATGATGCAGCCAAGCTCTCGAATGCTGCTGAGCACTACACC
          CCCAGTCGGCTAAATCTGGATCTGGTTATCTTTTCCTTGAGTGCCCCTGCAAGGCACGCG
          CTATGGCCAGCATGGGATTACCCAGCACTAGTATCCTAAACTGTGGTTACCAGAACTGTA
          GGGGCTAGACGCGGCATACACACTGGAAACCCCGTGCGATCACAGGCCCTACGAACTGTT

          GCGCGCGCCCTGGCGGACGCCAACGAGTAAGGACTGAGTTACAAATCTTCGAAGTTGCCC
          GCGCGCGCCCTGGCGGACGCCAACGAGTAAGGACTGAGTTACAAATCTTCGAAGCTGCCC
          GTAAGCGTCCTAACAGGCGTTATTGAATATGGACAGAGTCACACATCTCCGACTTTGTTC
          GCGAATTTTATGGGAAACATTCCCGATGAAAGACCATAGCATACTGATCTGATAATTTCC
          GAAGGAGCACACGTAATAGCTCAATTACAGAGCACGCACGAAAGCATCATGTCCGAGCCG
          GCGGCCATATTTGTACTCGTTATAACAGGGAGACTGTATAACTCCTTCTATGCTCAATCC
          GCGGTAGCATTTGTGCAGTACCCGTTGTCTTAAGGCCGCACTAACAAGGCAATCTGACGT
          GCCGTTTGCTGCGCACCCGTCAGCACCCAACGCTGATGCCTTATGGTCGAAGCTAGGAAG

          GGGGAGTACTTCAGCGTAAACTACTGATAGATCGGATGTCGGCCGTCCGTACACTATAGT
          GGGGAGTACTCCAGCGTAAACTACTGATGGATCGCATGTCGGTCGTCCGTACACTATAGT
          GATTTGTTAATTGTTGGAAACGACGGCTGATTCACATGCTGGCCGTTCGCAAGTGATAGC
          GTTGCCACTCACAGTGGAAGCTGATAGCAGATCGCACGTAGGTCACACCATAATCACCGT
          GCTACCGTCCGCCCTGGAGTCCACAGTGTTGTTGCACTCGGGCTGTCCACCATCAACCAT
          ACTGCTGCCGGCCCTCGACTTAGTGGTGGAATCACACGCCGAAAGCTTTACAATAACAAC
          GCTTCTGGGTTCGTTGAATCACTTCGTAAAATCATTCGGCATCTGTACTGCAAGAATCGT
          GCTTTGGCCGTTAGTGGACTCTGCAGGCACGCCTCGCCTTGATTGTCCTGGTTAACTCAT

          TAAGTTACTTCACGCTAAGAATTCAAAGGTATACCGCCCGCTGGAATACAAAATCGGGCA
          TAAGTTACTTCACGCTAAGAATTCAAAGGTATACCGCCCGCTGGAATACAAAATCGGGCA
          GCAGTTACACCCCGTTGGGATTCTAACGGTGCATGGCTTGTAGTTAGATGGGGTTTGGGA
          ACGGCTGACCCATGGGGGGGACCGGAGGGTATAGTGCCAGTGATGCGGAGAGGCCTACGT
          GAACACAGTCTACTGCAAGACGGGGGGGATCTTTTCCCTGATGCGTGGCACGGTCTGTGA
          TTCGTTTCCTTCCGAAGGGGCGCGAGAGGGATGCCGCCTCAATCAATAGAAAGTTCGAAG
          CCCAGCGCCCATCCATTACGAAATTGGGCAGCCTTGACTATAGTGGGATACGGCCAACGA
          TCCAACAGAATATCGGGCGTCCCGCAAGGGACACTTCTTGAGCCGAGGGCAAGTTGCAGA

          GTTGTGGCAGATACCCCCAATACAACACGGGTGATGATTGACGCTAAATCGATGCCTATC
          GTTGTGGCAGATACCCCCAATACAACACGGGTGATGATTGACGCTAAATCGATGCCTATC
          GTCGTTGTTGATGTCCCTAATATATCCCGGGTGAAGCCTGTCAGTACGCCGATGACCCTC
          GTGGAAGTCCGCGGCCTGGTCACTGCGCCTGTGCCAGCTCTGGCTGAGGAGTTTCATAAC
          ATAGCCGCCCTAGTTATGAAATCAAGTCGATGAGGGGTCGTGTTTGGTTTGCTTGAACCC
          TTGATCGTCCACATTGAGAGAATGAGTTGTACGAAGGTTTAGGTTAAGCCGCTGGTATCG
          TTGCGTGTTCTGGTAGGAGAGGCTGGTGGAGTAAACTGCTTCGGAGATGCGCCGTACCTC
          ACGGTGATTCCCGTCCAGACAGACTAATGCGGGAGGGCTGGGATCGTAACGCAAGACTTA

          AAAAACAGCGGCATGACAAACAAGCGTACGGGTAGGGGGACTTTTGAACTATCACCTGAC
          AAAGACAGCGGCATGACAAACGAGCGTACAGGTAGGGGGACTTTTGAACTATCACCTGAA
          GACAAAAGAAATATGTCTAGTCCGTATATGGGCAAGGGGGGATCTAGGCCAGCACCTGGC
          TCCTCAGGAGTTAGGATAGGAAGGCTGGTGGGAACAGTGAAATAAAACCTGCCCCACGAT
          CATTGTGATTCGACCACCACACCTTTTCTAGGCGAGCGGAGAACATGTCCACCTCCGCTA
          CAAAAGGAGGCAAGTGCGAGTACTCCTGCATAAAAAGGAGGATTCGGTTTGACCGCTTGT
          TTCATAAGAAGTAGCGTAAGCTCACATGGGGGCGGTGGAAGGTTCGGTATCTGCTGTCGC
          TCCGAGGAAAGAGGTATACGATGGACCGCTAACCCGGCGGATCCAGATCAACCGATTAAC

          CTCCAAGTAACTTACTTGTAAAAGGAACACGGTCTGACGGAGTCTGGTGTAAGAAGTGTA
          CTCCAAGTAACTTACTTGTAAAAGGAACACGGTCTGACGGAGTCTGGTGTAAGGAGTGTA
          TGTTAAGAAGGCCACTCGTAAAAGGGACACAACCCGATGTAGTCTGGCTTGGGCAATATA
          ATCTGGCATCAGTGTGCGCGGAGGCGTCTTGGCTGGACGAGGCCTACAGAGAAAAACGCC
          TTATGGGGCGGATACATATGTACTCTACATGGTCCGACAGGATCTTTCCTGGAGACTGTA
          TTCTACACCGCCGCTTCGCGTTATCGCCCTAGTTTTCCAGACCTCCCTATTGAGAAGATC
          TACCCTATGTTTTCACGCTTCGGTTCACAGGGCTTGAAATAAATAGATAAGGCAATACTG
          ATTTATCTCGACTCGAACCTTGAGCGACTCAGTTCGGTATGGTGGGTTGCTCAAACCGAC

          GCGCCGGCGCGTGTAGAACGTGTACGTACCTTCGATTGGGCGAAGCTGGTCCTAAAAGAA
          GCGCCGGCGCGTGTAGAACGTATACGCACCTTCGAATGGGCGAAGCTGGTCCTAAAAGAA
          GAGTCGTCACGCATGAATCGTACGAACTGCTCTGACTGGGTGAACCAGACCCCAACCGTG
          GCGTCTTGGCCGACGGATCGAGCTCCTCTATCTACAGAAGTTCACCTACAGCTATGAGTT
          ACTTGATCGGGAGCGTGTGGGTTAACTAGGACGGGACCAACCGGCCAGGGGTTCTATAGC
          TAATCCTGTTCAGTCAGACGGCTCCAGACAAGTGTAGATGTTGGCCTGAGTTTTGACCCC
          ACCCCGTGGCCGATAGACCAGCTAATACCATCTGGGTCCACTGGCCAAGAATCCCGCACA
          GTGGCGTTGACAGTACGATTCAGGCCAAAAGACAGACAGAATCGCCGCGAGCTCGATTCG

          CATGATCGGACTTATGTTCCCATGAAAGGAGTGACGTGGCTCGATCTTGTTGTTGTTGAT
          CATAATCGGACTTATGTTCCCATGAAAGGAGTCACATGGCTCGATCTTGTTGTTGTCGAT
          TGAATACAGGTCCCCGACCCCACGAAGAGAGTTGAATGGATTGATCTCGTAAATCTTATT
          AAGCTGTAAAATTGTGAAAAAAGAGAAGAGGTTTAGTGGACTAAATGTGCCGACGCAGGT
          AGGTCCTAGATGTCTGACGTTGGCGCGGGGACCTGTGAAGCGTGCCCCGTCAGTATCGTG
          AAACTGCTCCTCCATGAACTGGGCACTAGGGGTAACCCTACCTGACCATTCATTGTATCT
          GAAACCGACCCCTGCGGTCTAGGTTATCGGAACTCTAATTTCTGCTAATCCGGCGCCCTC
          AAGATTGGTGGTTGGAATATCAGAAACTGGATGGAAACAGTGCAACTGGGTGATGTCATG

          TTCTTAAATAGCAGATACCAGCTATAACATACATTCGTACATGTCTAACAGAGCGATTTG
          TTCTTAAAAAGCAGATACCAGCTATAACATACATTCGCACATGTCTAATAGAGCGATTTA
          CTCCCGATAGGCCAATTTAAGGAATAACAGAAGTTAGCGCAAGTGTGCTGAGGCGAACTA
          ACCGTGCTTGGTCCATTCTTCTAGAGGTTCATATCGTTCTATTAAGGCTGGACTAATTCT
          CAGCAGCACAACGACCCCATGCTCTAGAAAACTCTGGCGCATGAAAAAAGGGTTGGTTTC
          AGGATAGCTAGTAAGCTCGAATCCTGACGCACAGTGCCACCTTCGGAACTAGTAGATATA
          CGCTCAAATTCTAGTTCTATTTTTTGGAGACCACCGGCACATAAGGGGCCGGATATTCGA
          TGGTGGTCCGGCGCCCTGGCTTCATAGAAAACATGGGAGCATGGAGAGCTGGTTGACTGG

          CTAGGATGAGCACCCTATGAAAACTAAGGCCTGTTGGACCGCTTACCATTCTTGTAGCCA
          CTAGGCTGAGTACTCTATGAAAACTAAGGCCTGTTGGACCGCTCACCATTCTTGTAGCCA
          AAGGGTTTTGCACACTATGAATATTCGAGCTCTTTGTTCAACTCATCACCCTTGTACCTC
          TGTACTCCAGAACCGTCCAAAAGCCTCGACCTGAACTCCAACTAATTTCTACTATTACCT
          ATGGCGCTGAAAGTAAGTGGACTTATGCTAGTGAGGTTGGGCTCTTCGATCTCGCGGCTC
          ACGTCACTTGCAGTAGCAGAGACCTTTGCTCAAGAGCCTGACCTTCGGTTTTAGAAAGAC
          ACGCTCGCTCCTGTAAACCGTGACGCGATTCTGGCACACAGCCTTTAGTTATTCTGAACG
          TTGACATTCGCAGTACCTGTAGAATCGAGGCCGACGGTCACTCTACCAATCCATTGCCAC

          AGCGACACACCTGCATTTTCTGGCTATACACGCGCGTAAGGGATAGCCGGGTTTACTCAA
          AGCGACACACCTGCATTTTCTGGCTATACACGCGCGTAAGGGATAACCGAGTTTCCTCAA
          AGTGAGACATCTATATATTGCGGGGATACGAGCACGTGAACGATCGCTGGGTTTCTTCTA
          AGCGTCGTCCCACGAGATTATATGTGGTTTAGTCCATTGGGAAGTTGCATCCCCTGCTAA
          GGTGCCATCATAGGCGCTTATCCTAGTTCTAGAATGTGAGGAAACCTCAGCGTCAGGCAC
          CGGAACACGCTAGAAGTGTACATAGGCTTCAGATCCTGATAGGCTCTGTCACTTGGCTAT
          GGACCCGCTATACGAAACTCAGATCGTTCTTACCCTAGGAGTAATCTGCTACCTAATGAT
          GGAGCCACTGTCGAAGCTTCCCTTGCCCGTGGACTGCGGAGGATCTCCGTCTTTAGCTCC

          TAAGACGGGCTACGCAGGGCAAGCCCAGATCGCAGTTACA
          TAAGACCGGCTACGCAGGGCAAGCCCAGATCGCAGTTACA
          GATAGCGGGCTGTGCCGGGCGAGTCTCGCATGCCGTTGTA
          GGAGCCCTACAGTGTCCCCTGGATTAACCAGGCCGCTCGC
          GGATAATCGCAGTGTCAATGAAGTTTATATAATCCGTGTT
          CAGTACCGACGATACTGGAGGTGAGTGGATAGTCCTTGTA
          AAGTACCGGTCACAGTGGTAACATCCCGTTGACCGTAGCG
          GAGGATCGACGAAGCCGGCAGGGTCTCAACTCCCCCTACT

