 8 1000
t1        AACAACATAGGAGCCCCCAAGACGCATTTGAGGGATATGTCACGGTTAAGGAGCTTGTAC
t2        AAAAACGTAGGAGCCCCGAAGTCGCATTTGAGGAATATGTCACGGTTAAGGAGCTCGCCC
t3        AACAACATACAAGCCCCAAAATTACATTCGAGGGATACGTCGCGGTAAAGGGACTCTATC
t4        CAGGGGATATAAGACCTTAACCCACGTTAGCGAGCTTCGTCACTGAATTAGAACTCGCTC
t5        TACGAGGCGTACGAACTAGAATCACGTTAGTGGGTCTTGTCAACATAACGGAACACGGCT
t6        CACGACGCGCATGAACTGGAATCATGTAAGCAGGTTATGCCAACATAACGGAACAAGGCT
t7        TGAGCAAGGCGAATAATGGGTTACGCCTTGAGGGATACGCGCGGGGGGCGCAACGCCATT
t8        AAACAAAGACAGATTCGAGTTTTTGTCTCGTGGGATCTCCAGAGTGAGTGCATCCCGACC

          TGGACAGTCTGTGTGCAGTCCGGCAGGTGGTTACTATTGCTACCTACCCGCTTACGTACG
          CGAACAGTCTGTGTGCAGTCCGGCAGGTGGTGACTATCGTTACCTACCCGCTTACGTACG
          CGAACAGTTTGTGCGCAATCCGGTAAGTGGTCACTATTGCTACTTACCCGCTCCCGTTCG
          CGAATACCTCGAGAAAAAATCGGTAGGTGTTCCCAACCGTTACTGACCCGCTCACATCTG
          CAAACAGCTCGTGTGTAATGCGAAAGGCGTTTCTACCTGCCAATGACGTGCTCACATTTA
          TAAACCGCCCGTGTGCACTTTGAAAGGCCTTTCTACCTGCCATTGACATGCTCATATTTA
          GCCCCCCGTCACACGAGACGAGATTGGAAACTCCGGGGGACTTCCCCACGGATCTACCCC
          ACCGACAGGTATAGGCGGCGAAGCGCTCCACGTCGGAGGTTCTCCGTCCCTATCTGTTAT

          AGAGGAGTCCCTGACTTGGCCCGGTGGAGACGTCTGCGGAGTGCACGGAACGACTCGTAG
          AGAGGAGTTCCTGACTTGGCCCGGTGGAGACGTCCGCGGAGTGCACGGAACGATTCGTAG
          AGAGGAATTCCTGATCTGGCTAGGTGGAAACGGCTGAAGTGGGCAGTTGACTATTCGTAG
          AGTTGCGGTTTCAACCCGGCACAGTGATATTATTTGAGGTGGATCTGCACTGATCCATGA
          AGATGCACCTCTGACCTGGCACCGTAACGATATCCATAGAAGGATTGACTGAATACGTGT
          AGATGCACCTCCGACCTGGCACCGTAACGACATCCATAGAACGACCGACTGAATACGTGT
          TAATGCCCAACTCGCAAGGTCATGCGGGTTCATACGGGAGGCTACTGCCCAAATAACCAG
          TAATATAGACCTGGCAAGAGTAAGCGGTATATGATGAATGGTGACCTTGCTAAGAACTCG

          GATGAGTTAACCAGCTCACCACAGGGAGTTTAAAATGCCTGCGTCTTCACGTCCTCGGAG
          GATGAGTTAGCCAGCACACTACAGGGAGTTTAAAATACTTGCGCCTTCACGTCTTCGCAG
          GATGAGTCAGCCCGCTCCCTACAAAGACATTAAAAAGTTTGGGTCTTCACGTCCCCGCAG
          TAGGAGCAAGTTCGTCCACCACCAATGGATAGTTGAGCTCGCATCACCGTGCGCCCATAG
          GACAAGTTTGTCTGCCAACCACAACGCGCCAGTTGGGCCTGCGCCATAGTGTGGTCGTAG
          GACAAGTTTGTCTGCCCATTACAGCGTATCCATTGGGCCAGAACCATTGTGTGATTGTAA
          GAAGTAGCGATACTTTCTAAGTGCTTTACCCACGATGTGTATGTACCTACTCATCGGGGC
          GAGGTACGATTTATCTGCAGAATTTAGCCCTAAAGCGCCTCCGTGACAACAGACCAGTAA

          AAACCAACTTGCTGTTATCACCACCCCCGAACTACGTACCAATTACTACCAGCGTAGGCA
          AAACCTACTTGCTGTTATCACCTTCCCCGAACTACGTACCAATAACTACCAGCGTAGGCA
          AAACCAACTTGCTGCCATCATCACCTCCGTATCACGTACCACTTGCCATTAGCGCAGACA
          GATCAAACTTGTTGCCAATACAACCAACGTATTGCGTGACAAACATCTCCAGCGTATTCA
          GAATGAATTAGAGGCTTGTCCGTCCTAGCAATTACATATAGATTATCGTAAGCGTCAGTC
          GAACGAATTAGATGCTTGTACGTTCTAGCAACTACATATAGATTATCGTACGCGTCAGCC
          AGGACAGTTACAAATGTATCCAAACTGTGCGGAAAGAGGCAAACCGAATAAACCCAGGCC
          CGCTGCGCTCTTGGGAAATTGAACTAGAATGATGGGCGTGAAGCCAGTGTAACATAGGAC

          AGGAGCGTGTTACGTTGACGCTAAGTCATAAGTATTTAGCGCTAGCGCTGGATTTCAATA
          GGGAGCGTGTTTCCTTGATGCTAGGTCGTAAGTATTTAGCGCCAGCGCTGGATTTCAATA
          AGGAACGCGTTACGCGGACACCAGGTCGTACGTATTTAGCGCCAACGTCGGATCTAAGAA
          TAGGGTGCCTCTTATTGAGCCCCAATTACAGGTATATAGCGCCGACGACGGGTTTTAAGA
          AAGGGCCCGCTAATCCTACGTTAAATAGAAACTATACAGTGACGCCGCCGGGTTGCCAAA
          ATGAGCCCGCTAATCCTACGTTGAACAGAAACTATTCAGCGTCGTCACCGGGCTGCCAAA
          AAGTTGATAAGCCTCGCGTAGCCCCTACTAGTTATGTCGTGCTAGCCATCAGTCCACATA
          CAGAAACCCAGCCCGTTATCACAGAAAGCAAATGCCGACCGCCAGCGCATAGCTTGTGTG

          AGGAGCGAGTTGGGGCGACCAGTTCACCGGCGTGCTTCTTCAAAAGCCATATATCTAAAA
          AGGAGCGAGTTGGGGCGACTAGTTCGCCAGCGTGCTTCTTCAAAAGCCATATATCTAAAA
          GGGAGCAAGTTAGAGCGGCTGGTTCACTAGTGCGCTTCTTTAAAAGCCGTATATCTAAAA
          AAAGGCACGTTGTGACGGTAGGTGTGGTGGTAAATTTCCTTTATGCCTATATATACAGAA
          AAAAAGCTCGTTGCGCCGCCAGTACGCTAGTGAGCCTCTTTCAAGGTCATACATACAACA
          AAGAAAGTTGTTGCGCCGCCAGTACGCTCGTGAGCCTTTTTAAAAGTAATGTATACAACA
          CTGAACGGCGCGTCACGGGCGGCGCGTTTGGGCCCCATTTCGGGTCTCGCATAAGTAGTA
          GGGAGCATAGCAATAAGAGAATGACGGAAGCCCCACATTTCAACAGGGTTTTGTGTAACT

          TCCATGTTATTTATCCATAACAAAGAAGGACTGGTAAACCTCAGGTCACGCCAGGCGACA
          CCCATGCTACCCATCCATACCAAAGAAGGACTGGTAAACCTCAGGTTACGACAGGTGACA
          TTCATGCCACTCATCCATTACAAAGCAGGACTGGTAAATTTCAGGTTACGCCAGGCGATA
          TTAATACTACCCGCCTAGAGACTAGCTAGAGTGGCACGATTGCGATCCCGTCTGGCACGA
          CCGCCGGAACTTAACTATAGAGTAAGAAGGCAAGTGGGACCAACAATAGTCCAGACAAGA
          TCGCCGGGACCTATCTATAAAACAAGAAGGCTAGCAGGACTAAGAATACTCCAGACAAGA
          CCGAAGCAATCCACCTAGTCAACAGTCAGTCTGTAAGAATGCGAGGGGCCTCGGGAAAGG
          CCGGCACCGCCGCTCTTAAGAGCGAGCTATTCGTTCCACCTCGAGCAGTGGAGGAAAGGG

          ATTCTTTACCCAAATAGGCGCCCAACTCGATTCTGCTGCGCTGACCCAAGCTAACGGAAC
          ATTCTTAACTCAAATAGGCGCCCAACTTGATTCTGCTGCGCTGACTCAAGCTAACGAAAC
          ATCTTTTATTTATATAGGCGCCCAACTTGATTCTGCTGCGCTGATTCAAGCTAACGGAGC
          ATTCAATCATAGAATAAGCGTCCATGTTGAGCTAGATGCGTTACCTTACGCCAAAGGGGC
          GTTCAACGCTCAGACATACGACTATCCTGATCTGCTCGTGTCGTCTTATACTATTGGGGC
          GTCCAAAGCTCAACCAGACGGCTATCCTGATCTGTTAGCGTCGTCTTACACTACAGGGGC
          TGCTACTCTGGCGGGACCACATCTTTGGTGTCTATCATTATCGAGTCGCGTTACGAGGGA
          TACGACTACGTCGCCTGGCGACCTCTCGGATTTGTGTGCGCTACTCACTATACAGGGTGC

          ATATCGTAAGAGAACCCTCTACCCAATGACCCACGACCGGTAGTTGGAGGTGCCAGCCTG
          ATATCGTGTGAGAACCCTCTACCTAATGACCGACGACCGGTATCTGGAGATACCAGCCTG
          TTATCACGAATGAACCCTCTACACTATGACCGCCGATCGGTTGTTGGAGATAACCGCTTG
          AGATCATGAGTTAATCTTCTCTAGATCGAATAATGGCCGCTCGCTGTTGTCACGAACCCA
          TTCCCGTGACTAAGTAGCCATCTCACCGAACGGCGTCTGTCTATCAGTGAGGAGGATCTG
          CGTCTGCGAATAAGTCACCATCTCACCGAACGACATCCGTTTGTCACTGAGGAGGACCTG
          TCGCCTAGATATTAATCGAGCCAAGCACCGTGGAAATAGTCACTGCGAAGTATAGAAGCG
          CCTTGACAGCCTTCACTGAAGCTAATACAACATCAGCCGCGGTTACTTAGCGCGAGGACA

          TACGCTGTTAGGGTATATGGTGTCGAGGCGGACTCCTACATTGCGAAGCGCATTGACGTT
          TACGCTGTGAGGGTGTATGGCGTCGAGGCGGACTCTTACATTGCAAAGCGCATTGACGTT
          TACGTTGTGAGGGTGTATGGCGTTGGGGCGGCCTCTTACATCGGGAAGCGCATTGGTGTT
          TATGCTGTGAAATGTTACGGCGTCGAGGAGGACTAATATGTACTAGAGAGTTGCGGCGTT
          CGCGTTAGGACAATTTCCGGCACCGAGTCGGACACAGATACTGTCCGAGGTCCTGACGTC
          CGCCTTAGGACAATTTCCGGCACCGAGGCGGACACAGACATTGCCCGATATCCTGACGTC
          TGCCTATGGTTCAACGGCGGGGTACAGGATAGGGTCCCAACACCTGCGGGCCACTCCACT
          AGTTCAGGGGTTATGCCCGGAAAACAAGATCCTTTCGCCGCCCAAATCCACCCTCAAACC

          CTATACTGGCGTATTACTCGCCCACGGTGCAATGTGCCTGGGTGATTTATGGGAACGATT
          TTATCCTGCCGTACTAATCGCCCACGGTGCAATGTGCATAGGTGATTTATGGGGACGATT
          CTAATCTAGCGTGCTATTCGCCCACAGTGCATTGTGCATAGGTGGTCTGCGGGATTGATT
          GTAAACCGTTGAACTATTTGTCAGCTGCCTGATGGGTATAAGTAGTGTATGGGAGTAACC
          CTAAACCAGCGTACCTCTGACCTGCTATGTGTTGCGATTAAGTAGTCTTTAGGAACTACT
          CTAAACCAGCGTACTTCTGACCTGCCATGCATTGCGTATAGGTAATTTTTAGGAACTGGT
          GTAGAAGTATCGTTCGACGGGCGACGCGCTAGATAGAACGTCTGAAGGTCTTGATCAGCA
          AGGGAGCCCTTTCTGGACGGCTGGCGTAGCAAGAAGGACGATTGGTGTGCCAGCACAACA

          AATGCATATCACGCTCCAAAAGCTGGGGACGACTAGTTGACTCGGCTTAACTTCATCTAA
          ATTGCATACCATGCTCCAGCAGCTGGAGACGACTAGTTGACTCGGCCTAACTTCATCTAA
          ATTGCTTCTCACGCTCCAAATGCTGGGGACGATTAGTTGGCTCGGCCTAACCTCCTCCAA
          TTAACATATCCCAGTCCAGAAATTGGCGACGGCTGCCCATTTTGTAATAACACCTTACAC
          CCTACATCGCTCGGTTCGGGAGTCTGGGACAACTGGCCGCTCCACGATAACAGCACGATC
          CCCACATCGCTCGGTCCTAGAGTCTGAAACAACCGGCCGCTCCACGATAAGAACATAATC
          AAGACTTACATTGATGTAGGAATTTTCCACATCTGATCACTCCACGTCATCGACGCATAG
          TACATCGGTATTGCTACCAGGAGGGAAGCGACATTGACGTATCAGCTTTCCAAGAGATGC

          GGAGGGGATTTGTACCCATACGCTGCAACAGTGACGAGCGTGATCATTCAATACAGGAAG
          GAAAGGGATCTTTATCCATACGCTGCAACAGTGACGATCGTGATCATTCAATACAGGAAG
          GGAAGGAATCTGTACCCAAACGCTATAACAGTGATGATCGTGATCATTCAAGACAGAAGG
          AGAAGGAATGCTTACCTAAACGATGTGCCAGTGGTGACCGTAATCATACATCATACAGAG
          GGAAGAAAGCTATATTTATACGTTGGGGCAGCGGCCGCTATGATCCTGTTATATAAAAAT
          GGAAAAAAGCCACATTTATACGTTGGGGTAGCGGCCGCTCTGATCCAGCCATATAGAATG
          CATCAGAGAGAGAAATCCTTTTTCTCGTTGGCGAGTGATCAGATAGTTGGAGTATGCGCC
          ACCAGGTACGCGAAATTCTAACTTCCAGCACTGGAGGCTCAGATTGCGGAAAAACGTGTT

          GGTTCTCTACCTTATGTTTGCAAGTGGTAGCTGAATGCTTGGCGGGTTAGCGGCCTCGTG
          GATTCTCTACGTTATGTTTGCAAGTGGCAATTGAATGCTTGGCGGGTTAGGGGTCTCACG
          AAACCTCTTCCTTACGTTTGCACGTGGTAGTTAAATGCTTGGCGGGTCAGCGGCTCGACG
          GAAACTTCGGCTTGTCCTCGCAAGTGGTGGGCGTGTGCCTGAAGGGTGTGCGGCTACAAC
          AGATCCCTATTAAGACTTCGTATGAGGTAGTTGAACGCTTAGGAGTTGAGGGATCGTACA
          CGCTCCCTATTACGACTTCGTATGAGGTAGTCGACCGCTTAGGAACTGAGAGATCGTACA
          GGTTGATTGTATACATCTTGCCAAGGGTGATCGCGCAACTATAGTAAAGTCGCACGGCAC
          GGTTACGGGTATAATCGTAGCCGAGGTCAGCTGATAGTTCCCAGGGTGGGCTTACTTAAC

          GTTAGGACCGTTGTAAGCATTCTATTTTGTCTTCCACGGCGATTAGGCGTCTAGTTTCAA
          GTTAGGACCGCCGTAAGCATTCTATTTTGTCTTCCTCGGCGATTAGGCGCCTAGTATCAA
          GTTCGGACCGGCATAAGCCTTGTACTTTGTCTTCCACGGTGTTTAGGTGCCTAGTTCCAA
          GTCCGGATAGACATAAGTTTTGTTTCCTGAGTTCTAAAGTTCTTATGCGAATAATTCTAT
          GTGAAGTGGAACGCCAGCTTTGTCATCCGCGCTCCACAGCGCTTAGGCGAACTCTTTAGA
          GTGAAGAGGGACGTCAGCTTTGTCATCATCACTCCACATTGCTTAGGTGAACTATTCAGT
          CGGTCAATGGTACCTACAACGTTCACCAGTGCAAACGCACGTTTACTAGAAAAATTATCC
          GTGGGGCCAAGTGTTGATTTCCTTGTTCGTATTGGAAGTAGAGTATGACAAATATCCTGC

          TAGCTCTGTGTGGGGGGTGCTGGCGGTTTGAAAGAATCAT
          TAGCTCCGTGTGGGGGATGCTGGCGGCTAGATAAAATCAT
          TAGCTCTGTGCGGAGGGCGCTGGTGACCCGATAAAGTCTT
          AGGGTTCGTGTGGGGGCTATTGAAGGTTTGGCGGAGTCTT
          AGGGTGCGCCCAGCCGGTGTTACGCGCTCGGTAATGCCTA
          AAGGTGCACACAGTCGGTGTTACGCGTTCTGCAATGCCTC
          CAGTGGCTCTACAGAGTTCGTGTGCCCAGTGTAGCGTCTT
          TGAGGACACTAACGTATACGTATGGCTATCATAGCGTATA

