 8 1000
t1        AGCTTTTTTTAGAGCACGCATTGATCTGGGGGAGGTACCTAGCATCCCATAGATGTTGGT
t2        AACTTTTCCTAAAGCACGGACTGACTCGGGGGAGGCACACAGTATAATGTGGTCGTAAGG
t3        AACAACATAAGATGTTAGGATCGTGCTGTGGGAGGTACATGGGAAGATGTAATTGTAGGG
t4        GATTATATCAGGAGCACGGGTCGATCCGGGAGAGGTAGGAGGCAAGATGTAGACATAGGG
t5        TACCAGTTCTAAAGTATATACCGGACTGAGAACGGAGACCGACCAACTGAAAATGTATTA
t6        ATCCCCACAAACAGTCTCCATAGGACTAGGGTTATTCTCCATCGTACAACACTACTCCGT
t7        GGCGCCTCCCAGCGGCCGGGCGAGAGTTGGTGAAGTGCGGGGGGCACATCCTCGTGACGA
t8        ACCAGCAAAAATAGTGAAGACTAGATCGGGACAGAGGGTTGCTGAGTGTTGCAGCGCAGG

          GAAAGGGTCTAGGGGTCGGTCGCTTGTCCGCAAAAGGGCAACCCGCGAAGTTTCGATTTT
          GTAGTGGCACGGGAAAGGTCTGCATATTAGCAAAACAGCAACTTGTGATGTTCCGGTTTC
          GTAAGGATCTACAAGTAGTCCATTTATTAGTGACACAGCAAACCTCGTGATTTCGTTGTT
          TAAAGGGTTCGAGAACTGTACACTAGTCAGTAGATTGGTGACTTGCGGTGCATCGGTGCT
          CTGAAAAATCGGCAGACCTCTGCTCATCCGTTACGGTGTGATTCGCGTGCCGTGAACTTG
          GCGACAGCTTACGAGTAGTCAATTAATCAACAAAGGAAGTGAACGCATATGGTGGATTAC
          GTATTATAATGGATCCGGACCACAAGTTAACAAGGAGCCAGTATATATAACGTCACTAGC
          ACCGCGGTTCAGGTTCGTACCGTGGAGGACAGAAAGGGAGACTAGCCAAAAACCTACCTC

          CAGCTGTAGCTGGCTCCGTTTAAATCGCCGTGAACCAGTGGAACGTCGCGATCTGCTTAA
          AGGTCCCTACCGGCATTGCTTGAATTGTCGTAAAATTGTAAAGAGTCGCGGCTTGCGTAA
          AGGCTGCCGCTGACACCACACGGTCTACAGTGAACTCACGGCGTGTCGCGAGCCGCGCCA
          AGGTTTCTACTGACCTTGCTTAAATCACCGTGAACCTGCAAAGAGTCGTGATGTACGCAG
          CGGCTTACGCCGGTCCTGCCTATACAGTCATGCACTTATAATGTGCTGCAACCACCGAAG
          AAGCCCATGAGCGCGTGGCTTAAATAACGGTGAATACATTGAGAGATATCCTTTTCTTTA
          AGCTTCCCGCTAGTGTTATTAACTCAGACAAGCGCACTTGGAGTGTCACAGTGTTACTAG
          TAACCCGTATTGGCCGTGTTACATCCAATAAGAGCGCGTGAGGGGTTTTGCACCTGTTTA

          AACTACTTTAAACACTAGAGCTAACGCGAACGGCTGCCTTGGCGTATCTTTTGGTGTAGA
          ATAGCCGTCAAACACTAGCGTCAACACTCACCGTCGCTCCGGCGTCCTTTACGGCGCAAA
          GGCAACGTCGGGTGCAAGGATTATAGTTATCCGCCACCTCCGCGTATTTTTTCGTGCTAA
          ACCAGTGTCGGACACCAGGATTGACGTTAACCATTGCCTATGCGCATTTATCGTCGGAAA
          GACAGTGTTGGGCGCAAGAATTTCCGAAAATCGTTGTGTATGCGTCATCTCTAGAGTTGA
          GGAGGAGCTGGTTACACAAATAGAAGATATTCGCAGCGTCGGCGACCTACCAGGGGCTGA
          GCTCAGCTTAGGCGACGTGCCCCATGTTGTCTCCGGCCAGGCCGTTCCTACCCCGACAGG
          TGCAAAGGCAGCCCCAAAGGACTAGCTCAGATATCCATGGAATGTTTCCTTCGGAACGTT

          GCCCGTCCCGGCCGATTGCTACGATTTGACACAAGGCCAACCTGACTGCACATAGGACAC
          GTCCGTATCAGGCGACTGTTCCTACTCAACGCATGGGGAATCTAACTACACACTGGACTT
          GTCCGTATCGAGCGACTATCACGATTAGATAGAGGGACAGTCTGTCTATATATTGAACGT
          GCCCGTACCTTGTGATTGTTACGACCAGAACCGGGGCCAATTTGACAATACATAAAATAC
          GTTTGCAACTAGCGACTGATACGGTTGCTCGATGGATTAATCTGGTCTCGCATTTCCCAA
          ACCCGTGCCAACCTACCGTCATCGCCATAAGCGAGGTGGGACTACTGAGACCCTACCTGC
          TCCCGCGCAAACAAACGGCTTTAATTCTTCTGAAACATCATATGACTATTCGCGCAGGTT
          ATCGGCACAGATGGACAGTCGAGCCCTTATGCGTCAGTATCTCGGCGGCTTTCCACAAGT

          TGTCTTGGACGCCCATAAGTTAAATGTTCGAGCGGGCGGCTAACTTTTCCGCTCGTGGAT
          TGTCTTGTGCTTACAAGTGTCGAACATCTGCATGCGCGGATATTTTGTCCTCTTGTGAAC
          TACCATACGCTCTCGCGGGCTTGACACGTGGGTGAGCGGTTAATTTGCCCTCTCACGGAG
          TGTCCCACGCCATCCTGAGTGTAAAACGCGTGCGAGCGACTAAGCTGCTGGACCATAGGT
          TGTCTTGCGTACCCAAGGGTAGAATCTATGGGGTGGCTGTAGGTTTGTAGACTTTTGGCG
          CGAAGTACACAAATAACCACTTGAATTGTAAGTCACCGGACGAACAGGTCGCCCGTTCAA
          GATCTGGCATAGTCGGGAGCTGGACTTTGAATCGTACAGACCTGCCCTTTGGCTATGGGT
          CACCGACTGATATTAGGCTTGGAGCATTCACTGATTCTGCTAGGCTGCCCGCCCGTGGAA

          TTGTCAGTCATAAGATTAGGAGGCAATAGCTCGCGCTTATCCTTTATATCTCATGGAGTC
          TGGGTGGGCACAGAACCTCCGGGTCCTAGCACGTGCCAGTCCCTTTCATCTTAAGGAATT
          TGCAAGGTAAAAGGGTAACAGGGTAGTAGCTCAAAACCACCTTTTAAGCCTTAGATCGAC
          GAAATGTCTAAAGTCTACGTAGACAAGGGCTGAAACCAATCGCACATAAGCTGGTGTCTC
          TGACAGTCGGAAGTGTAATCGGTTAACAACTCGAAGTGATGACATCTCACTTAGGGCTAA
          GGCGTGCTTGACACGCGAGCCCTTCAGATCATTCGTAAACATTTATTGTTATGAGGTCTT
          CAAATGGAAGCAGCAGGCACCAATTAGGGAGCAAATAGATGCTGATTCCAGTGCAGTGTT
          CAGGATGTGAACGGATGACTACAGTATAATTAGGACAAACGGATACAAGCAACCCGCCTT

          TGTCTTGCCCGATTGTGAGGATCCTAACATCTCTGGCGGGGCTTGCGCGAGGTTTACCTC
          CGCCTTATCTGGTAATGAGAGACCTGGTATCCCCGGCACAGTCTACGCGAACCTGACGCT
          CATCCTACATGTCTACGAGAAACCTGGTGCTCTTGGGTCCGTTTGCGAGAATTCGATCTC
          TGTCCCGTCCCACAATAAGATTCCTACTATCCTCGGCACCGTCTGTGGAAACTCGATATT
          CGCTCTGTCCGTCGGTGACAAATCCGCTACTCCTGACTCTCTCGATATAGGCCTAATCGC
          AGTATATCATTATCATGCAGAAAGTGGCATCCCAAGCGCTAAACGGGCTGATCAGGTATC
          TGTCAATACTGCCCCTGGCGGGCACGTTATTTCTTGGGCGAGAAACTTGCACCCCACCTT
          TTGCCCCTATATCTTATGTGACAGCGTGGAAGCTATATTTATAAGCCCATGACCGCGTAG

          TATGCAGTGGTCCTTGCCTGTGGTCATGACCTCGTTGCCCTTGGTCCGGGAGGACGCCGT
          TATCTGACCTTTGCCCTCCGAACACACAATCTTGCTATCCTTAGCCCTGGAGCACGCCGC
          TATATGGCGTTTTATGTTTGTAACCCCGATCAAGTTACCCGGAGCCCTCGAGGGTTCCGA
          TTAGCGGCATTCTTGGCTAGTTAGCTCTATGTACTTACCCTGGACCTCGGAGTACTTCAT
          TCTTTTGTACTTTCGACATGAAATCGCGACCCAACTATTCACAGCACTCGAAAGCATTCC
          CTTGGGCGATCATCGATCTCCCTTCTATCCTCGGGCCTCCGCCGGTCAGGTGAGATTCGT
          ATACCCGCGCCCCCATGAGGTATCCCCACGTTGGATATTTTTGAACCTTGTGATCATGGC
          GTCATAACCTAAAAGTCCCAAACCAACACATTAAATGTATTGCGACTGTGAAATAACAAT

          CCTCGCCGGGTATTCGGGATGGCATCGAACTAAGCTACTTAACGAGCCTACAATTTGGGT
          CCTCACAGGGTACCTGGGATGGCGTGGAACCTAGCCGAGCAACGGGCCCACAACATGGAT
          CCCCTCTGCGTGCGTCGGATGGCATCAAACCAAGCCTAGCAATGTCCATAAACCCTCTGT
          CTTCGAAAGCTGTCCAGATTTAAGTTAAACCCAGAAGGGCAACGCGCCCGTCTTTTGGGG
          TTTTATAGGGCGAACGGGACTGATCTAGACCGAGTGAAGTGTACTCCGCGTATCTTCGGT
          TCCAAGGGGGAGTCCAAGTAAAGTTGCCAGCGGACCGAATCACGTGTCCCACGTATGTGG
          CCTAACCGGGCGGTTGGGCGGGGTGGCCGACATGTTAGGGTCCCGGGGTACTACCTCGGA
          GCATATCTGGCCGCAGAGTTGACCTGCATATACGCCGCGTGACACGAACATGGCTTTGGC

          AGCAGGAGGTCCCGCTAAGGTGTTTAATTCTACTTTCCACACATGACGATCTGTAGACAG
          GACGGGAGATCTCGTTGATGTGCTTACTGCTACTTCTTACGCGCGATGTTCTGCGAAGTG
          TGTAGGAGATCTTGGTGAATTGATGGATTCTGCCCCTTACGTGTGTTCCTCAGCGAACAG
          AATAGGAGGTCCTAATGAGGAACCTAATTTTAGTCCTTACACTTGACGTCCTGGGAATTA
          ATTAAGAAGTTCCAAAGAAGATGCTGAACTCGCCGTCCACATTTGCCCGTTTGGGGAGAG
          CACGGGAGGGCCCTAATGAGTAATTGCTTTTAGTCTCAACTCTAGTCGTCTAGTAGAGAG
          GTAGAGAAGCCTTGGATAGCCCAGAAATTCCATCTAAAGCGCCTAGCATTAATAAGCGGG
          CATCGGCCGTCTGTATGTTGACAGAGAGAATTACATAGGAATGAATTACCCTGGGTCACA

          CTAGTAGGGATACCGCTGACATTTAATGCACGTACTTGCGACTTGCCTGCCCCGTATCCA
          CTAGCTTGGATTTCGTCGACATTTAGTTTGCATGTTAGTATCCTGTCTATCGCATGCCCT
          CCGCCCAGGATTTCGGCAGTTTTTAGCGTACATACTTTCATTCTGCTTTTCCCCCGTCGC
          CTAGCCCGGATCCCGCCCTCCCGCACCACACATTCCCGTACTCGACGTTTTCTTTGTACT
          CAAGTCCGATTTACGTCAGCTTGAACAAAACATAGCCGCATATCGCTTTCCCTCTGCGTC
          GTTACAGGACACACACTACCGTAACTGCCGTAGGCTAGCATACAGATAGTACTTTGGCAT
          TCTGCCTTGCGTTGGACACCCTGCTGAGTTCACGATTACCCCCCGCTTGCCTGCTGCTCC
          TGCCCAATCAACTACTTGAACCTAATGACCAGGCGATAGGTCGATGCCCGCCTTAGTTTC

          GGAGCTGCCGAGTTGTTAAGAACGGTAATATATATACGGTTTTCTCTTCACTCGGTGCAT
          GAAACCGACGGGTCGTCACGACTGGCAGTACAGAGGGGGATCACTAGCCATTTGTTCGGC
          GGGGATGACGCGATGTTAAGATGGCTAGTATAGAGAGGGTTCACTACCTATTCCACCGGC
          GGGGGCGATGAGCCGTTGAGATTGGTAATACGACTAGGTTAAATTGCCTACTTTTGTCGC
          GGGGCCGATGAGCTGGCAATACAGATAACTGTGCTGGGCAATGCAAATCCTTCTATCGAC
          AGGACAACCAAGGCCCGGAGGAGGGTCCTGTTGGTCGGATTCGACACATTTTTCTAGCGC
          GGAAAACAGTGGACTAATTCATGGGAAACATTGCGACGATAAACCTCGCTCCAAGCGGGT
          GGAGTCAATGTACACCCGAGAGGCGCAGCTCATGTACCAAATGCAGCCCCACCAATAAGA

          CAACCGTGATTCAATCGGACCTTAAACTGGTGGCAAACTCGAAAAGGAGTAGTTTTTGTC
          ATATAGCGATTAGACCGTTTCTCGGACTGGTGGCTCACTGAAACCTTCGTGGTTGTTGTG
          CTATAGCGATTCTTTCTTACTTCGGAACGATGGCAAATTGGATAGAGTGTGGGTTCTACG
          CTGTGGTGATCGAGTCGGTCCCAGCGCGGGTAGCGAAGTGGCGGGTGAGTCTTTCCTGGG
          GTATAACGAATGGGTCGCATCTTGGTCGGACCGTAAATTGGTAATGCTGTAGTCAGCGAA
          CAACGATTAGTAAGCTTTGCTCACAAAAAGTGCCAAACTTAAAAAAACCTGCCCCTGGAG
          CATTAACTGACGGATTGAATCCTGAACGTACGCCAAATCGGAATAATCATGAATCTTACT
          TCTGAGGTTCGGGAGTTCGATCAGGCTGTAGTTCACATCGAAGATAGCCTTTTATTTGAA

          CGAAAGCGTTGACTTTATTACCGTAGGAGGTGAGGGTATTTGACGCTGTAAGGCGATACC
          TGAGGGCATCGGCATCATCGTCGAGGGAGGCGAAACTGTCTGACGGTGAGACGGGAACCA
          TCCGAGCACCGCAACCAGCCACGGTTGTGATGGATCTTCTTGGCGATAACTAATAGCCTT
          CGTGAGCATAGCCATTACTGCGGAAAGAGGAAATAGTATTTAGCGTTCATCGGCGAACTA
          AGTAGATCTCACTCTTATCATAGCGAGAGGTGTGTATGACTGGTGCTGAGCGGCACCCCT
          AGAGTACTTGTCTAGCATGGCCGCAGGTGCCCATGGCAACCTGAGGTGGACAGTCACCCT
          GGGCAGAGTGCTATGTGCCGTGGAAAGACGAGCTAGCACTCAGCGACGGTTAATATTCCG
          GGGTTCATTGGCTGGTGCCATTCTGGATGGCGCTTAAACTCAGAAACGTCCAGTTAAATA

          CTGCGCCACACCTAAAGAAACTCCAGTAATGAAGCGTTCTACGCGTCAGGGATCCGTTTC
          TTATTCCATACTGAACGTAAGTTCAATGGTGTGGCACTGTAAGCGTCGGGGACCCTCTCG
          TAGTTCCATATTAAGAGAGAGTCCGCTAGTGAAGCGCCCTCAGCGTCGCGGAGACTACCA
          TTCTCTTTCACTGAATGAGCACCCAGTGGCGAGGCACCTCAAGTGTTAGGGACTATTTCT
          GCTTTCCATTTCGAGTGACGATCCGATAGTGAATAATTCTAGGTTCCGGAAATACCTTCT
          GGGCAGTACATTGAATGAGAAGCCGTTAACGACGAGGGTCACGCTTCGGGGCCCGTACAT
          GCCACCCATACAATGTGACATATGGACTGCGACGATTCTTTATTGTTGAGCCACAACGAC
          AGGGGCAGAATTAACACTGGATCCCGTCTGAACGCCTTTCAGAAAAGGCCATCAGCCCAG

          GTTCGTCGTGCGTCTCAAGTGGACTTTATTATTGATACAT
          GCTCGGGGCCCACCTTTAGTGCCTATTACTATCGGTAACT
          ATCCGCGGTGCATTTCTAGAGGATGCTATTTTCGATCAAC
          ACATACGATGCGATACTAGTGAACGCTACTATTGATCAAT
          CCGAGGTGTACATCCCTCGTTGACGCCACTATCGCTAGCC
          CGTAGGGGCCTGCAACTAGCGAAAGCTACCTTCAGTATGT
          TTGTTCTGCCCATCAAAAAAAGCTGTAGCAGCAAGCATCG
          TGATAAAGAAGACTAATGACAGAAGGCATCCTCGAGTTAC

