 8 1000
t1        AAAACTAATGTGTAAAAGTCACACATTATTTAGGAAGTGAAAGAGCCGGTATCCCTGGGC
t2        AGGGTCAATATGTGCAAATCTCATACAATTCAGGCATTGAACGAGCAGGTATCCCCGGGG
t3        ACGGCCAGTCGGGCGTATCCCTCTGCACTACAATCAATGGAACCGTTGACCTCCCGAATC
t4        GAGAGAGGAGTTGCTGCCTCTTATATATGCCGGATACTGCGCCGAGGAACTACCTTGGCT
t5        CTGCGTTGACTACATGGGTTCCAGATAACCAAGTGGTCGCCTGTCCTGGTTATTCAGGTC
t6        ACGAGCAGACTGTGCGGGTGTCACATGACACGGATATCTCACGGATAGTTTGTTTAGGTA
t7        GCGGCCTATTTGGGGACAGCTTTCGAATCTACGCGACCTTCCGAATAGAACGCTACGGAC
t8        GCGGTCGACTTGAGGATGGCTTTAGTACATAAGGGACCACCTGAACAGAAGGTTATGGAC

          GCGCATCCGTTAATGACGTGGGGCGACCTGCCAAAAAACGGGCGGCTATATAAGAATATT
          CTGCAACTGTTTATAGAGTGCGGCGACCAGCGCAGCAACACGCCGCCGTAGTAGACTGTT
          CTGTCTCTATTTAAGGCGAGCAACAACCAATGGTGCGCAGAAAACCCGTTACCGATAAGC
          TTCTCGATACAAGTTACACATGAAATGTGGTGGTCTTGCCGATATCTCTCGTTGATTCCC
          TTAACGCAGACCGAGACAAGTTGTTTATCATTCAATGCCTACGCCGCAAGGTAGAATTGT
          CCGCCGCCGCCTGAGTTATGCGGTTTTTGACTTGACCTAGACAGTCGGAACCAACGACGA
          CTTCGAGACATAATGAAATGTCAAATCGAGATGGCCCCGAGCATTTAGTGGCCCGTTCGG
          CTCCCCGTCATCAGAGGATATAGTCTCAAGAAGAACTCGCGCATTCGATAGTCCACTGGC

          TGTAGTACGCGTGGTCTCATAACCCACCCGAAGTCGTTTTCTGTAAGATGATATAGTGCA
          TGTAGTACGCGTGGTTTCCTCTCTTATCGGAGGTCGTTTTCCTCATGACGATAAAGTACA
          CCCCGTATACATAGTCGCACTGCCTAGTTGGTGTTGTCAACCTTATATATAAAAATTATG
          GATGAAAATTGCGGCGTCGGATAAATATCAGAGCTATTCCCAGGGAAAAGGCGGACTCCC
          CCTGACACACATGGAAAAGTCTCCTCTACTAGGTAAATTTTTTTCCACCGGCTTACCAGT
          ATTCATACGAGCGAAATCGATATGCGCCTTCCGTTACTATACACCTTTTCAGGTATTCTC
          TTCATCCGACCTACCCGCGGTCAACATTCCCAGCGTCCACACACGTACAGAATCATGATA
          CTTCTGAGACTGACTTGTCGATAACATTTCAAGCATTTAGGCATACACGGAACCAGGCTA

          TAATTCCTTTAATTCGCCGGGCGCTCCCTCTCTGCGTATCTCGTTCAAGTCAAAGACCAC
          GACTTTTCTCAGACGGCCCGGCACTCCCCCTTCGCGTATCTCGTCCACGTCGAAGATCAC
          TGACTGTTACCTACCACTCAGACTTTCCATCCCCGCCTACTCAAACAGATTAGAGATCGC
          CATGCCAGCAAGGGCTCCGATAGATCAGTTTGGAACCGACGGAAGTTCGAAAGACGTCAG
          ATCGCAAGCTTGTTTGTTGAGGGCTGCGTCTATGTATACTGAAGTACTGGCAAGCGTCGA
          TATCTCAGCAGAACTACCAGGCGCTCTGTCCAGATGGAATATTATTCCGACAGGTATAAC
          CCGGGCGCCGAGCACCATAATAAAACTCTATAAGGATGGTGTTTCCCTAGGAGGCATCAC
          CAGGGTGCCGAAACTCACGATAATACTCGCTGACATCGGTGCGTTCTCACCAGGCGTTGC

          TGGAGCACTCTGCCTGTGGTAATCGATTATAATCCCGTCATAATGACAGCCGAAGCCTGG
          TGAGGTACTCCGAGAGTCATAACCGTTTGTCGTCATGTTATAATGACAGACGGAGCCTGC
          TTCGTTTCTCTCAGCTCAGCGTTATATAACAGACGTGTACGTCTATCGGTTGCGATTTGA
          CGCCAGTATCCCTCTATTCCTTTATAGCGTATCTTGTAGACGATAAAATGCCAACACAGG
          CGGTTATAAGAGTCCACTATCAAAGTGCTTAGAAGCACGGCGAAAGCGCATACCACTTGG
          ACGGCGACTTTACACATCGTACCAGCGCACGTGCCTGAGGAGATGGTGCATTCTGCTGCA
          TGGTAAAGCTGCTCTCTCAGACACGAACCGACTGCTGTTGACAAGATATGTAATGGTGGG
          CACTAAGACTGCCCTTTTAGTCATGGGCCCGCTGCCATCGACCAGTCGTGTGGTCTTGGT

          ACCTGATGGGCGCCAATGGTCCCCGCTCATGTTGAACTTTTCTCTTAGTTCTGCTGATTC
          GCCAGATGGCCGGTAATGGTCCCCGTTCATGTTGGCCCCTTCTCTTAGTACTTATGATTC
          GCCGATTGACGTGCGGAGGCCTCTGGCCATGTTAACCTTCTGTTTCGGTGAAGTTGTTTA
          CTCGTATCGCGAAAGACGGCTAGCGAGTTCGCCCTGCTTTCGTCGCTGTAACGCTACATC
          GTCCAGTAGTGCCTGGGAATTCTTTAGCGAGTTCGCTCATGTACAATGCAGATGTGTAAT
          GAGAAGTGCTAATCGAGCGTTCACAACTACACCCATCTCTTTTTCCCGTACAACTATTAC
          ATTTTATATTGAGCGTGAGCCCCGTAGGACATACGGCATTGCATCTCCCCGAACCACATG
          ATCTGACGGTGAGTTAGCGCCTAGACCTTTATACGCCGCCTCTTCCTTCGGAGGTATGTG

          CATCTATACCAGCTTGATCCTAAGCGCCGTGTGCTGCGCTGAATCTCGCTAAGCGCTGTC
          CATCTATAACGTCTTGATCCCAAGCACCGTGTGTTGCGATGAATCCCGTTAGGTGCTGTC
          GTGAAGCGTCAGCTTAACGCCAGGTGCCATGCCTTACCATATTTTGCCCGAGATGCTGGT
          TTTCGCTGACAGCGCAATGTAGCGTGCTGCAGGCAGGTGAGTGGTATTTGGGGGGATGCG
          TTATACAAGCCACGTCTCGTTCGACTCCGTGCCGTGTCGCGTCGTATGGTGAAGCACGAC
          TATTCACTTCTGAGTAGTGCCTTGAGCCCCGCGACCCTGTGGCGAATTTCGTGAGACAAC
          GCTCAGCGTAACTATGTCTCCATTCGCCAAGAGGCACCGTATTATGTCTAGTACGCGCGT
          GTCCGAAACGGCTATATCACCATATATCGAGAATAGCCGTATCATATTTCGAGCGTTAGC

          TCCTGTTTTAGCTCTGCGGTATTTTCCTTCGATAGCCCAAACTTGAACAATATTCTGCAA
          AGCTGTTTTAGCTCTCCTCCATTTTCCTCCGATAACCAATAGTGGATTACCATGTTGAAA
          ACCCGCTCTTGATTTGCCATCAATTCCCTCACCTGTGAGGACAGGTTCGACGTCCCACGA
          GCGCGCATCAGCTGACTAACCCTTACATTCTTCCAAAAAAATTTAGACAGTGGGCCTCTG
          ACTCAACTAAGTCCTGCTGTCTTTAAAACGACTTCAACAAGCGGTAATCGAAAAATCCGG
          GCTTACTCCGCACATGCTGGTCTTACCTAGGTATGACGGGTATAGCATGGTTGACCATGG
          GGCAGATTCAGTTTCGGCGTTTCTGGAACTAGCCGACACTTTAGTGCCCACGATCGACAG
          GTCAGACCCCTCTCTGACTTGTAGGGATCGAGCCGATAACCTAAAGGCTTGTAGGACTCA

          GCCAAGGGGACCCTAGTCGCGGCTTTTTGTAATCAGCCTGGTCACAGGTGAACTCTCCCA
          GCCAATGGGACGCAATTCGTGGCTTTTTGTGGTCAGGCTGGCCGCATGTGAATACTTCCA
          TGCGGCGGGCTATGAAGAACCGCTCCACGTGCCAGTTATCAGTAAGTGTAGCGGCTCAGA
          CACGTTGAATCATTAGATGCGATGATACGTGTAGGCGCTAGTGATTCGTAGTCTGAACCC
          TCTGACAGCGTACTGGAAAATTGTCCGTCCGGGGATTTCGTTAGTGCGAGACCGCCGCAG
          CATAAGGAACCGCCGTAACAGAGAACATGTGGGAATTTCAAAACAGACTAGTAATAGAGG
          CTCCGAGATTGCCCAGAATACGCGACGAGAGAAAAACTCCAATGAATTTGTCAATCTCGG
          GCGTGAGAGCACTCAGAAGATAGGTTGGAAAAGGCACCTTAGGGGGTCCGTGTATTTTAG

          GTGTTAAGTGTCGTAATCCATCATTATAAGTTAGTAGGTAAAATATTATTCTGTTCGACG
          GCGTTTGGTAGCGTAGCCCATCATTTTAAATTAGTGCGCAGAATGTCACTCTATTCAACG
          GGGACTAGAGTACCGTGGAGTAACTCTAGGCTGGTAGGTAGAAACTACCCCCCTACGATT
          GGTTATTTAGTGCTGTCCTAAGAACTCGCGTCGATAGGAACAAGCTTCCGACATGAAATG
          GATACATGCTAGCTCAATTCCGATCTAGGCTTGGTATGTAAGTCCCACGTAGGCACAATG
          GGGCCTAGTACCCTGGAATTCTACCCTAAATTGGCAGATGATTTCTTGCCTTGACTGTCA
          GGCCTTGACTACTCGTTGTCCAGTCCTGAGACGGGCGGTTTAGAGCCACGCAGCGCATAC
          AGGCCAGTCGACTTATTGCCCGGTCTCAGGACGGCGGGTCAAGCGCGGATTAACGTGTGG

          TCAGCAAGAATAGGAGGCCTAAAGCGACCGATAAGGCCGCCCTTTGCCGGCGCACTTGAA
          TAAGCGAGTATGGGTGGGCCAAAGCGACTGAAAAGATCACTCCCGGTCAGCGCCCTTGAA
          GATCCGTGTCCAGGAAGATCCCGGTGAGTGGGAATATTGCATCTCCTCACACCGACGCGA
          AGTGTTAGTCACGGACGGACTCAGCATCAGGGGATATAATGTCCATACTCGGACGCTGGG
          TGTACCGATTAGATGGATAGCAAGTGGCGTATGGTAGCGATTCCTCCCGCAACCAGGGAG
          TCCCCATATCGTAGTACCACCAAGCAATTAAAGTTGCTGTGTGATCTTACAATCATGCAA
          AGCGAAAAATAACGGGGGCTGCGGCGAGCGAGAGTTACCCGCGACGCTCAAGGGTCGGAA
          CGCGCCGAATAACGGGAGCACGGGCATACGAGCCCTACTTACGTCGATGTAGGTACGGAG

          TTTGAAAACTATCGGGCTCTTCGCGGGCACGGTGGGCCAGGCATTTGTCCCGTAAAACTT
          ATGAAGACCTACCGGACTCTTTGTGGGCACCCAGAATTAGGCATGTGTCCCGTCTCATCT
          TTTAGCGGCCTACGAGGCTTCAGGGGCTATTTTCCCTTTCAGTTATGCGGCTCTTACCTA
          CTGCGGTTCAATTTGGGTTGTGGCCCCAGCCATGTTCGCGAAGTGAGCTGTTCTCAATAT
          CTTTGGGGCCGCTTAGGTGATGAGTACTAAAAACTACGCGGTGCAAGCCTCCACACAATC
          CTCTGGACCCACAGGGACTCTAAATGCACCAATCTCTGCGCAGCGAATGCTCTCAGACCC
          CCTCAAGATGCCTGGAGTCCCACCCGCGGTTAACTTAGTAATGCCAACCCTACAGTACTT
          TTTCGAAACTCTCACAGGCTAGCCCGCAACTAACTGCGAAATGCGAACATAGCAACAATT

          CATCCGGCCGCCCTGCCATCATTCATTGATTCAAATTGTCAAACAGCCGGCAGGGCGTGC
          CATCCGGCCGTCTTGTCGTCGCCTGACGAATCTCCTCATCTAGCAGCAGGCGGTGCGGAT
          CTCTTGCTCGTATGCATTCTTTCAACTTGTACTCTTGTTTTGCATCAGATTCGGCTCGCC
          TGTAACGTGGTATCCAGCCATCGAGCAGCTGAAAATGTCCCGACTATTAATCGGAATCCT
          AGTCTCACAATTCCTTAACCTCATGCGTACTCCTAGGGTCTGGCCGCGGGGTTGAGTTGG
          ACCTTGCGGGATTTCCGCACCTCGACACCGATCCATACTTGAGTTACGGCATGGACTCAT
          GGCCTCACTAGCACTCTTCACTGCTTTCATAATAGCGAATCGGAAGTAGATGGAAACCAA
          GACTTTATTAGCACTCCTTGCCGCCCCTACTCCTGAAAATTAGCAATGGACAGGGCTCGA

          TATACAATCCTAGGGGAGCGACGAGAGAGGACGGAGTTCGTAGGCTCCTTGAGCCGAGTG
          TGTACAACCTTCGAGGGGCGACGCTAGAGGATGAATTTTATCGGCACATTGAGCCGTGTG
          TATTCTAAACCATAGTAACGCGGTTGGACGTACGTGTTATTGGGCACCTTGAGTGGGGTA
          CCCACTTGGGCAACAGTTAGCAAAGGTGATTGTATTATCGTACGCACTGGCCTCAGAGTA
          TTCGATAGAGTAATACTGTTGGAGCGCAGCCCAGTACCTACTAATTTTTAGGTCAAGTTT
          CCTACCACGACGACGTCTCCTTCACGCACAGTAGCACCCACGTACCCTTCACTTATAGCG
          TCTTTGACGCCAGTAATTACGTGATGAATACGGACTCTAGTGTGTTCCCTGCGGGTGGTA
          TACCCGAAGACAATCAATAGGAAACGGATATGGGCTTTATTAAGGTTCCTACACGTCTTT

          CTTTAGATCTAACTTGAAATCGGACCAACCCTACTAGTCGATTTTATATAGAACCGCGAC
          CTTAAGACCTCCCCTGAGGTTAGACCAGCCCCTCTAACCGAGCTTAAATACTACCGCGTT
          TCTAATAACATGCCCAGACGGAAAACTGACCTTGCTTCAAAGGCGAGATATTCCTGTGGC
          ATCTAGAAGGAGTATAGATATTGATGGGTCCCTTTATTGTCTCCTATTCCTTCCGGTGAT
          CATAAATTCAAGTTCCGGTAAAAGAGATCTGCCCCACTACCTCACATATGCTACTTTAGT
          CGTGAGCAGGACGCTCCAGCAAGAAGGGCTTCTTGTCTATCCATTGTGCCCCATCGCACT
          AGTTAGTCAAAGGCCATGCTCCGGCTCAAAGTGTTAGTGGATTGTGTACCTAGTGTTCAC
          GTATAGCGTAAGTGCACGAGCCGATTGGAAGTGTTAAAGGATTGCGTATCCGGCGTTTAC

          TCACTGAACACACCTCCAGCTGGACGCTAGTTGTAACGTGAATAGACCCTGGGTAGCTTA
          TCACCGAATACACCTCCAGCTGGTTGTTAGGTGCAATCCGAGTAGAACCTGAGCAGCTGA
          CGACCGGATAGCCGCTTATCGAGGTACAAACCATACCACGGACTGCGGGCCTGCGCTTCA
          GCGCCGAACGTGCTGCCAGCGGTCGGTCGATCCTCTAGCACCTTGTATCCACATGCTTCA
          GAATGGAGCAGGCTCATTATGAATTTCAAGCTACTAGCTATATGCATCGCGGGAGCAGCC
          TCAACGATCAAGCCTGCGCGGCGTTGCAGGCTAACACGAGTATAAATCGGACGGCCCTCT
          CGTTCGGCCGCACCCCGATGAAGCACTAGACAGAGAGGTGCCCCGGCTAGGGCTGCACTC
          CGCCTGGACGCCGGCAGCTCAAACGGTCGACAGTGAGAGGTGCTGAATGGGCTTGTACTC

          TAGGATGGTGCATGGCCGCTTTAGTTGAGAACCTAACTGT
          CAGGATGGCCCATGATCGCTTTAAAGGCGAATCCAGGTGC
          ATGCGCGTGCCATATAGGCGTCAGAGTAACTGACGGGCGA
          CTACACATACACCTTTTATCGTCAAGTCAACGCTAGTCGT
          TAGATAAGCTCAAGGTCATACCGCAATGATCTATGGTCGC
          CCACTGCACAAGTGGTTACCCTGCAGCAGGTTCTGGATCC
          TATCACCATTTGGGGTCTTCCAGAAACCGAGGACTGAACT
          TGACGACGACCAGGCTTCTTCGGAGTTTGAAGTCTGAGCC

