 8 1000
t1        ACCAGCCAACGTGCAATCTTTTCATCGGAAACCGGCAGCCGGACTTCGGAGAGGGACTCG
t2        GCCTGCCAAGGCGCCATCTCATTGATGAAAAATAGCAGCCGAACTCTGGAGTGGGACTCA
t3        CTGTGTTAGTGCGTAGTGCCCTTAGCAGTAACAGGCAATAGGTCTTCAGGGCGAGCTTTT
t4        CTATATTTACATGTAGAATCTCTGATAGTGATACAAACCCGTATTTTAAAGCGGGATTTT
t5        TTGTCCTGACGTGTAACTTCCCCAGCAGCATTAGGTAAACGTGCTTTAGACTCGGACATC
t6        CTGCACTGCTGCGAGTTCGGCTCGGTTGTCGCCGGTGCCCTGAATACCTATTGCAATATG
t7        GTACGTTAACCAAATTTCTCCCCTGTAATATCCAGCACAGGACTCTACAAAAGCAGCGTC
t8        CCGGGTGAACACGTCCTACTGTCTATAATCAATAGTCCAAGAAATCACGTGCACGCAGTT

          AGCCTCGCTGCGCAAGCTCCATCGGAGTCCACCTGCTCGATAGCGTCAGGCCTATTTTTA
          GGCCTTGCTGCTCAAGGTCTATAGGAGTTCATCTTTGCGATAGTACTAGGCGTATTTTTG
          GCCTTCAACACGTGCGCTCAACTGGAGTGCTTACTGTTGTCAGAGAAAGTTTTCGCCTGT
          GGAACCACGCAGAAGGCTCCACGGCAGCTCTATCAGCCGACCGCGAGGCGTCACGGCTCT
          GGGCCCCGTAAGCCGGCCTTCCGAGGGCGTAGACTATTGACAGTGGGAGTCTCCGACTTT
          GGGTTCGCTCAACCGGCTACGGGGGTAATCCCCTTGCCGGATCTAACTTGCTTAGATGGG
          GGGCTCAAGGCTCAATGCCATCAACGTCCACTACAGCATGTAGCCGAAGACCGTCCATTC
          ATACTTGTTCAGCTGGTCCTGCGCCAACTTCAGCCTCCAACAGTGAGAAGTATAGGTTCA

          CTTATTCTTGTTAACTGCAGTATATCTTGCCGCTACATTTCGTGACGGGATCAGGATATA
          CTTATGCCTGCTACTTATAGGATACACTACCGTTATAATTTCTGATAGGACCAGGATGTG
          CATGCGTCAACTAAATTTAAGGCAAGCTGCTGTTACCTTACCTCCCGGGATTAGCGAGTT
          TTCGCAACTATGAGTCTCATGCGTGACAACTTCCGAACTGTCTAAAGGGATAGAAGAATG
          TAGTCGACGACTAATACTAGGAGATATAGCTGTTACAGCACCTTCCGGAGTTGGGAAAGG
          CGTCTAACCGTTGGTATAGCGAGGGGTGGTCTCTTCCTTGCCGTCAGAGGCAAGCCGCCG
          CGCTCGATTACCACTATACGGGGACATTGCTGCAGTCGCTGCTCAGAGATCCGGGACCCA
          TCAGTTCGCGACATTACGTACGAAAGCCCCCAGGTCGGTGTTCTCCGACCAGTGGCGGCC

          CCTCATGGGCCAGCTCGAGGAGCGTGGTATAATGTTGACAAATGCAATATTGGCACCGTC
          CCTCATGAGACACCTCGAGGATCGTGGTCTAGCGTTAACGAATACCATATTGGTACCGTC
          CTCTATGGTCCCAACCGGAGGCCATGAGACGGCGCAAAACGAAGGAGCTCTGGGGACTTT
          CCCTATTGAGCGGACCAGAAGTTGTGCCAGGACGTGAAAAGAAGAGTTACTGGTTCATTA
          CCGCAGGAGCTCAAACCTAGGCCGTTCTAGGGGGCGGAGAAAAGAATAACAAGCATTACA
          ATCTATAAACCATATTTGTGACTTAGCCACAGTGTGGAATGACGAGAGAAGCGAACTTTA
          CTCTCAGGCGCAGCGCGGTCACCTACCTTCTATATCGAGGGCGGCGGTATGAGTACCATT
          CCGTATGAGTTAGGGTACATGCTTAAGTAGGACGTGTCGTATGCCGAAGGGGGGGTCTTA

          TTAGCGACAACCTCCATAGGACATTCATGCCTCTGCGGCGAGTGAAGTGTAGTTCAGTCG
          TTAGGGACTACCCCCATAGGACATTCATGCCTCTACGACGAGTGAGGAGTAATCTAGTCG
          GTCGCGCCCACCCTCTTAGTTTGGTCCAGCCTATGTGTTGAATCAACAGCGGAACGAATC
          CCAGCAATTGCCCTAACAAGGAGGCCACGCATCTGCGAGCATTGAAGGGTAGATGGATCC
          TATGCGGCTTTCTGTAGAGGACAGTTTCGCTTGTACATTAGATGATGTGCGAACTCACAT
          TCGGCGAATACTTTCCTAAGACGCTCGTGCTCCTTCGCAGGTTACAGAGGAACTCTGGCT
          GTAGGGCTTTTTTCAGCGGATGGATCGCGTTATTTCGTCCGAGGGTGGTCCATGTTTCCC
          AGAGTGATGGCCTTCTTGGACAATCCCCTTCCCTAAGAAAAGCTTCGCCCAGAATAATTT

          CCCGTTAGCAATCCCAATGTAGGCTCCAATCGATCGTTGGCCGGACGACGCAGTCCGTGG
          TCTGATTGCAATCTCAATGAAGGCTTTATTGGATCGTCGGCCAGACGCTGCATCCCGTGG
          TTTGTTCGCCTCCCAGATCCAGGGTTTAGTAATGTTCTAACTGCTCCACGCTGTTTGAAG
          TATAACTGTTCCCCTGATGCAGGTCCTCGTTGACATACGTTCACGGAGCGAGCCTTGTTG
          TTTGTCTGTTGCTCTGATACCAATCCTGGCTGGCAGCGTGCCACAGTTAACAACCCATAA
          TCTGCATGCACCCTCAGTAACAGCTAAAATCGACTTCACATAGTAATGAGGCATCAGTGT
          ATTTCACCGTGAGCCCCTACCGGCATTTAGTCTTCTGCTGGCGTCGCGCCCGGTCGATCA
          CAGACCCCTGGCCGCGCTGACACCTTTAATTAGTACTGCATTCAGGCCTGAGTCTGGGAA

          AGCAAATGTCTTGAATAAAGTCCACTCTCCAAATCTCCCGGTTGCTTAAGTAGAATCAGA
          AGCAACTGTCTCTTGCAAAGTCTGCCTTTCAAATTTCCGCGCCGCTTAAATAGATTTTGA
          TGTTTGTCTGCTACATCAGGTGCACGGACTAAATGCCTGCGCTACTTAGGTACGCCCAAA
          GGAGCCCACTCAATACCGAGTCCATGTCTTAAATTTTTTGGCCATTAAAGCATCCCCGTA
          GAATTCCTGGCTACGTCAGGACCACGACGCAGTTTAGTCGGAAGATTATGTTTCCGTGCA
          TGCGACCAGATTATAAACACGCTGAATTCCAAACGCTTGTAGCATTTACGACTCTCGGAG
          TTTGCTCGGCCTGACTATGGCGTTTCCTCCAGACTATCTAAGAAAACTTTGTCAGGTGGG
          TGCCGCCTTATTCCACCTAGCGCACAAACCTTTCTGCCAAATAACGCGCACTAGCACCAA

          CATGCTAACTGCATGTTTGCCCGTCGTGTTCAGAAGAAATCCGGCATAGACACCAGTAAG
          CATGCTAACTGCATGTTTGCTCTCCGTGTTCAGAAGAACCTCAGCATGGACCACAGTAAC
          CCAACCGCCTGATCATATGCCTCTTCCGACTTAGAGAATCCCAGCATAGGTAGATGTCAA
          CCTTCTCATTGGGCGCATGTCTTTTTCGAACTAGATAATCAACGCTTGGATGACAGCCAC
          TAAGCCAACTGGGTCCCTGCTTCCTCCGACCCACGGGAGTCTAGTCCGGATAGTAACAAG
          CCCATCAGCTCGGAATGTGCCCCCATCAGGTCTGGGGAAGACCTTTCCAGCCGGTAAGCA
          TTTGATTCCCCATCCGAAGCGGCTAGCGGGGCACAAATATCATTCAGAGCTAGATCATCG
          TCAGAACTTGGAACGAGATTTTGACTTGACTCAGAGATTTATATTATGGAAGGGGGCAGG

          GCGGGCCATAAATACAGAATGACACGTTCTAACGGCTATAGGCCCATTGGGAGGTAGGGG
          GCAGGCCATAAATACAGAGCGGCGCGTTCTAAGGGTCATAGGCCTACCGAGGAACAGGGT
          GTGGACTATGATTATCGATTAACGATTTTCTAGGGCAAGCAGCTTACCTACTTGGTTGGC
          GAACATCATGGGTACGGGCTGCTGTAATCTAATGGTGGCCCGTTCACGCAGTTGGTTGAT
          AACCAACGCTTCAGTGGATTGCTGTATGTCGTTACTGATTTTTTAGTGCGTATAAATGTC
          GATCATACGATCCACGGAATTGGGCGTACTAGCAATCCCAAGTTACTGTCACTGAACTAT
          GTCCGAAGAAATTACCGGGAGATGCGCGCATGCCGCTACTAATTCAAGACAAGGCATATT
          CCCCGGCTCTAACGCCGGATGCTTTAGGCATCTGGCTACCAATTAGCACTCGTAGCGTCG

          GAGCTTTTATTATACACAGGAAAGCCTTTCACCGTTATTGACGTTTAGTACACATTATAC
          GAGAATTTACTTTACACCGGAAAGCCTTCCACCCTTATAGACGTTCAGTCCAAATCATAC
          GAGCCCTTACACCTGATAGAGCAGCTGTCTGTATCACTAGGCAACTGAAGCACAGAATGC
          GAGCTCTCATATTTCTTAGGAAATTCGTAAGTCCTTTTAAGCAACTATTAGATACCGTGC
          GCGTCTCAAGCCACCGAAAAAAAGCCTTCTACACATCAAGACCGTAAGCGCATATTATGC
          ATACTCTCCGACTTTTAGAGAGGACCAAACGATTGCGAGTGTGGCTCATGTGAAGCTTGC
          AAAACTTGCGTGGCCCAAAGTCCGCCGCACATCCAGGATATTGGGCCCCCTCGATGAAGC
          GAACAGGACACAGCTTGGGGGCAGCCTAGCTTACTAGCGTAACGCTCCTAATGTCCAAGC

          CGGAAGCGTTTATTTTTCCTTCTGCGGAGGCGACGCTAGCGGCGTCCTTACCGCCTAATA
          CAGAAGCGTTTATTTTGCTTTTTACGTCGGTAACGCTAGCGGCGCCCTCACCTCCCAATA
          CGAAAGTGCGAGCATCTATTTTTTCGTGATCGAGGTCAGTAGCTGTTGCATCGTCACACA
          AAAATGCATGGGGCTCCATTTCTTTGTACGCGATTCCAGAGGAGTGCCCTTGGCCGATTG
          TTGATTAATGAACCTTTGCTTCGCCTCGGGCGGGCTTTGTGGGGGCTTTGCAGCCGGTTT
          TCGGAGAGATTATTTATCTCCAGCGAGGAGGACGTCCGGTACGGCGTCCACGATCCATCC
          CCGCCGAGTATCCACACACTTTGACGTATGTACGGTCGCCACCCCCTGCGTGGCCAAATA
          CGACCGAGTATGTTCTTGTCGGGCCGACTTTTTGTTCTGCTTCGCCCGCGCTATCCGACG

          AGACATAGAGCTAAAGGTAATCCTATCGTTAGGAATGTCAGTCCGCCATAACGATATACC
          AGACATAAAGGTAAAGGTAAAGTTTCCGTTAGGCAAGTTAGCCCGACATATTGATACACC
          AAGGACCGGGATAAATACAGCCCTACCGCCGGGCGGCATGGTCTGTTATAGCGACATGTC
          AGAGGTAAGAGAACGGGTAGTATTGCTGTTAAGAGGCTTAGTCCGAGGTAAGGTCATACC
          GGCGGAAAGTTTAAAAATAATCTCGTGGCTAGGGGACTTAGCTTTGGGCGGCAATAAACT
          TAAGATAGAAGCAACCATGGATCAGTAGCCGGGAGGCCGGAATTGTGGCCGTGTATTAGT
          GCAGATAGGGCCAGGGGGGGCCGACCCAATGAGGAGTCCAAGTCGGGAAAGGGCCGTCAC
          TGCAACGGGTTTAAAGCTATTTCAACGGCTGAACAACTCGGATCCGGACATTGAACTTAG

          GGATGCAACACTGAGTTAGCTCCCTAACTTTTGGAAATCAAAAAAATGGGGCATTGCTGA
          GGACGTAACACTAGGTTAGCTCATTAAACTCCGGACCTCAAAATAATGGGTCGTCACTAG
          AGACATGACGATAACTTAGTGCTCGTGGATAAGCATTTTTGATTCCTAGACCGTTTTGAT
          AGACGTAACACCAGGGTCGGTTCCCAAGGGACGCGCCTTTGCCTGCCGGGCCGACGCATT
          AAACCGGATATACTCGCCGCGACTCAAGGATAGCACCCCTTCATACCGGATTGCTGCTAC
          GGCGCCGGGTTTAGAGAAGATTGAGAAGGCACGCAAGCCTGAATTGTGCACCCAGACTCA
          GCGTTCACTAACACAGACCCATCGGTGGGTGAACATACCTGGACGATGATCTGCATCTAA
          GAGCATGAGTGCGTCATGGAACGTCAGAGTGTGCTCTTGCGGCTTTTGGCTCTGCACTAC

          ATGATGGATGCGAGGCTCTGCCCCCTCAAGGGTTGCGGGATGAAGCGGGTCACACTTATG
          ATGATAGATGCAAAGCTCTGGCCTCTCAAGAGTCGCGGGATGGGGCCGGTCACACTTATT
          AAGGGATGGGCACAACGTCCCTATACCTGGGAGTACTATACGGTACTGGTCTTACCTTAA
          CAGGGGAACGTAAAATTTTACCTCGCCAATAGCTACTGGAGAGAGCCGGCTCGACCTTCT
          AAGAGGTGAGCGAAGTATCGCGCCAGCGGAGACCTTCGGAAGCAGTCACCGGGTCATATC
          GAATATATGTCGCAGTTTTTTCGCTCCCGGAACTACAGGGTATACGAAGGGGAGGTAAGT
          GCAGGCAAAGCAATGTTTAGTCTCTCTGCGGCGTACAAGGCAATATGGAAAGGGCTACAA
          GCAGTGGTTGAAAGGCTGACGGTCCCTAGGAAGTACTACTGAAGTAGAGGGGCGTTAAGT

          AGCGAAGTCCGTCCACAATGCAGTTCGGGTCTAGAGCGACGTCTGCCGCCCCCCCGAGGC
          AGCGAAGTCGGTTCACAATACAATCCGGGGACAGCGCGACTTCTGCAACCCCCCTGAGTC
          AGCGGAGCCGGTCTATGATGTAATACACACCTAGGGTATCGCCCGCTACCGCGCCGAGGC
          CACGGAGCCGGTCTACGATGCAGTGCAGTCTTAGCATGCTGCCCCGCCCCCCATTGATAC
          AGTTAAGCCGGTCCGCGACATGTTAAAGACCCAGCCCGGTGCGTGCTCTACTATTGAGCC
          AGGGCGGGTGTTTGATGACGTAGCACAGACTGGCCAGACTATCCCTACTCCCGTCTAGCC
          AATCAGTACTGCTTTGGGTGTAGCCCGGTATGGGTAGGCGGTTTACTTAATGGCTATGCT
          AGGTATCTTTGCACTCGAAGAGGCCCTAACTTGACAAGTCGCCCTAAGCCTACAGGGACC

          GCCATACCGTGTTCAGGGGCTGCAGCAGTAAACGGCCGCTTTCACTCCCCCCCTCGCTGT
          GCTATACCGTGTTCAGAAGCTATGGCAGTGAGTGTCCACTATTACTTCCCCCCGCGCTAT
          GTTCTATCGTCGTCTGAGATAAGCGTTTTTATCGGAAGCGCTAGCTTCCTTCCACGCAAG
          GCCCCACTGCGCATCAGTGCGAGCGTAACCAATAGATAAACCAGCCCTCCTTGATGCGGT
          GCTATCCTGTGCTCTGAAATAACCCAACTTAACGACACCGTCTGGTTCCTTTATGGCAAT
          ATTACAGCGCAAGTTAAAACAATCTAATTCATCAAACGCATCTCTTCTCTCTACTCTATC
          ATTATTGCGTAATTTAGGCCAGCCCTCTGCCTCGAATGTGGTCTGGTGGTCGTTCGCGCG
          TTTTCGGGATACGCATGCGACGGCTCAACTGCGTTCTCCGAGCTTCCGACTCTTCGCAGG

          CAGGCGAGTCGCATGTAAACCGAACCTCGACGTCCCATCA
          CTGGCGGGCCGCATCCAGACCGTACCTCGATGTCATATTA
          GCCGCGAGCGCACGCTCAGCGCAAACCTCGCGCCCCATAC
          CAAGCGAGCGGGAAGTAGATCCATTTCTAAAGCAGTTAAA
          CGGACAAGTTGTTACGGAATACTTTGCCAATCTGCTACAC
          AATGCGTCTAATCAGGAGTCCTACTTCTAAGTGCTTGGGG
          GAGGCGTCCAACGACGTGTCACCAGTCTAGTCGGGTCTGT
          GACACGCATGCGTCCAAAGTACCACATGTATCGCCTCCGC

