 8 1000
t1        CGGCCCCCTAATAAATAGGGCAGGCTGCTCAGCATGTTTGAGGCACGTTTTGTCAGAGGT
t2        CGGCCCCCTAATAAATAGGGCAGGCTGCTCAGCATGTTTGAGGCACGTTTTGTCAGAGGT
t3        CACACCGTCCGTAGATACGGACAGAAGAATTTCTTGTGCGATGTATGTGTCCTCAGGATT
t4        CGTACAGGGGTGAGCCAAGGCGGGTATTCCGCCTTGGAGGAGTCATGTGCGTTTACAAGT
t5        ATTGCTAAGATCTAAACATGAGAATGCTTAACTCCTTATGTTTATCGTGTGCCTCGGTAA
t6        ATGGCTGCGATTCGACCAACGAGTTGTACTATTCCCTGTTAGGATTGCGTGCTCCGGCAG
t7        AGGACCCGCCCCAAAGGTGGGGGACAGTATATAGGCAGGCGGGAACACCTATTCCTTAAT
t8        ACGACCCCTGCCTGTCGGTGGGGGCCAACTGGCTCGTTTACGCCACACGCTCCTTGGATA

          GGCTTCCGCCCGCGCGCTCCCCTGCGTTTTTGCTCTTCCCGTAGGCCGTTTGAGTTGTAC
          GGCTTCCGCCCGCGCGCTCCCCTGCGTTTTTGCTCTTCCCGTAGGCCGTTTGAGTTGTAC
          GATTTCGTCCCGGGGGTGGACGTATGGATAACAATATCATATCACCAACCCGGGTTGACT
          TGGTCCGGTCGGAAGGTCCCCACGCGGTATTCTATACCGTCCTAGTCATTCAGGTATAGC
          CGCTAGTACGCGGGCTACTGAAGGGGCTTGCGGTATCCGATTTTGCCACTAGCCTTTATG
          CCTCATTACGTTGGTCCTCAGCGGGGAAAGTGCTACATTATCCCGCTACCAGCATTCATA
          CTCCAGCGCCTGAGGCTCCACTAATCGTCTGACCCGATTTTGCGGCACTTAACCCTTACG
          CCTATGTGCCTTGAATACCACAGGAGGCCCATCTAGGTTTACCAGTATTAGTTACGCAGT

          TTTGTGTGCCACGGCCCACGAGTATACCTTGTGGGTATCACCTTCAGGTTGGTTAGAAAT
          TTTGTATGCCACGGCCCACGAGTATACCTTGTGGGTATCACCTTCAGGTTGGTTAGAAAT
          TCTAAGTACTGTCGCCTAGGAGCGCAGTCTGATCGAGCAAACAAGAAATTAAAAAGGGCT
          CCTAAGTGGTGCGGTCCAGCAGTGAAATTCGAGTCTGCCCCTATAGAGCTATCGAGAGAT
          CGGAACGAGTAATGCTCTCCAACATCGTACCTGCAGACCCCCATAAGCCTTTTTAAGGCA
          ACGACAGGGTACTGGTGAATAACTTATGTACTATTATGTGTCGTAAACTTATCTAGGGAG
          CCCAGAAGCAAAGGTGCAGTGAGCACGATTAAGGGATCGCATCGACTTTCTGGCTGCGAT
          CATAGGAATCAAAACTTTGCAATTCTCCTTCAAAGGATTCTGGCATATCACACCGGTGCC

          TGTCGTACACGCGCGAAGACACGGAGACTGCCCTTAAGGCGACATTATCCAGGGTTTGGC
          TGTCGTACACGCGCGAAGACACGGAGACTGCCCTTAAGGCGACATTATCCAGGGTTTGGC
          AGCAGAATACGCTAAAGTACCTTGGGACGTCCCCCAACGTGTAACGAGCAGTGGCTCGGT
          CTTCGTTTGAGCGCATGGGGCATCGTGTGCCCCTCCGCGCGAAAGAGTCTCCGGCTCGAA
          CTCTGGGCACCATAGCGTCTCATTAAGCCGCGCCTGCCGCACATTTACTTTCGTTTTAAG
          TCTTGTCCATGGTAGTATATCATAACGTTGTGTCTGTCGCAAGTCAGAATCTCTTCCCAG
          CGCCAAACACGTGCTCACATGACATGGTCGCTACCAACCTTGCAATTCTGGAAGCGTGTG
          CACTAACTTAGTGATTGTATCTAGATCTAGCCCGCAATACGGAATTACGTCGAATTGCGT

          GATTACTGCAGGTTGGAAGCTGTACAAACGGCACAGTTAGCGCTGCAGGAATAACGCCAA
          GATTACTGCAGGTTGGAAGCTGTACAAACGGCACAGTTAGCGCTGCAGGAATAACGCCAA
          CACTATTGCGCGTCGTAAGTTTTATGGTGCGCATAGTAAGCACGCCGGTAATATCCCTGA
          GGATTCTGCACGTTGTGAGCCAAGCGACGAGCACAGGAAATACCGCGAGGACAATCCCGT
          ACGCGATAAGTATTGTAATAGACGGAAGGTGCACGGCAGATGCTGCGGGAACCGCTTCCG
          ATGTGTCAGATACCGCCTGCAGTAGGGGGCGCGGCTGTAGGACTTTAAATGCTGCTCCGG
          TCGAACCTTTACACTGAAGCGAAACTATGCGTAAAACATGATTTGGTTGCACTGTCGGGT
          TTGGGCAGCAAGTACTAAATAGCGCAGCGCGCGTAATAATCTTCTTACGGATCGCACCGG

          GCTAAGATTTATCCCACAAAGCGTGGTCCCGCAACCACGATGACTGGACTTCCATATTAG
          GCTAAGATTTATCCCACAAAGCGTGGTCCCGCAACCACGATGACTGGACTTCCATATTAG
          GCAAATGTCTTCTCTAGATAAGTCACACTCAGGCAGGAAATACTCGCATTACGGCGTCAG
          ACCGCCCCTTCCTTGAAGAAGCTCGCCTAAGGTTGGAAGTTACATACACAACCGAGTCGG
          GCAGATCTGTTCGTGCCGCCCGACCAATTCGCGAGAATTACATGAACGCCATTCAACTAC
          GCTGATCAGCCCATGGCTGTAAACACCTTCTAAAGGACTACACGAACGTCAATGTATTTT
          TCTGAAACGTCCTTTTCACGGCCCTTACTCTTAAGCTCAATTATCGAGTCACCGCCCTTA
          CCAGATTCATTGTCAACGCAGCTAACACATGTCCGCTAGCTTTTCATATTTACAAGGTAG

          CCCGCAAGTCGCTGATTAGGATGTAAGTGAAGACGAATAAGCTTCCGATCGTCTTTAAGC
          CCCGCAAGTCGCTGATTAGGATGTAAGTGAAGACGAATAAGCTTCCGATCGTCTTTAAGC
          GTAGCAAGCGGCTAACCACGAAGTACGCGAGTTGGTAGAATATTACGAGAATTTTGGAAC
          TAAGCCGGACATTATCCATGTGGTTTGCTGAATAGGGCGAATATGTGGCTGTGTTGAACC
          TGGTCATACGGTCGATCGCGACTTGAGCAAGCGTTAGCGTGCCGGTGGAAAGTTTAAGTC
          CAGCTGTGTAGTTCAAAGCGGCCATTGCAAGCCGACCTGTGTCGGTAGACCGCCCACTCA
          TCTTACTGTCGCTAGTCGGGGTACGGACCAGTCATTTCACTTTGGCTGTTCGGTTAGAAA
          CTCTTTGATCAACGACTGTACTATTCCCCAAAGAATAATAGTCGGTGGTCTCTTTAAGCC

          CAAGCGGCAGGTCGGGCCCCCCGCTAACGATTAAAATTAATGCCTCGGAGGCTAATAGGT
          CAAGCGGCAGGTCGGGCCCCCCGCTAACGATTAAAATTAATGCTTCGGAGGCTAATAGGT
          CGAGTATTGGCCAGAAAAACACGTGTTGGTTCAAATTCAATTTATTGGAGACTGTTGAAA
          CGGGGGGCGGTACTAGCATCTTGTGCGTGGCTAATAGCAATGCTTTGGAGCCCGGCCGGT
          AAGGTAACGGTCTGTATGGGAGTTGCGAGCCCCACCATGTCGCATAGAAGATCGTTTTGA
          GCGATACCGGACCTGTTACTAGGTACGGATCCTCCACTAGTATCCCCCGACCTGTGTGGA
          AATCTGGAACTTCACTCGGTGGACGGGGTTTCTATACTGCTATTATTCGGCATGCTCGAT
          CTGTTGACGGTTCAGTGGATGAGCCTGGGGCCCGAGACAACACCCGCATCATCGATCGTC

          GCCCAGACTATATCTTCCTTAAGGGGCCCCTCGCGGACTCTCGTCGCGTCCAAATAAAAC
          GCCCAGACTATATCTTCCTTAAGGGGCCCCTCGCGGACTCTCGTCGCGTCCAAATAAAAC
          TCCCAGACAATGTTCTGCTAGTGGGGCCTTTAGTCATCCAACCCACAGATTTCACTTCGC
          ACCGCCTTCACATTCCCCGTACAGGACACTCGACGGTCTTCCGCCGCGCACCAGCTGCAA
          CGAGGGACAATATTCTTGAAGTATGTTCTAATGTCACTTCTAGCGTGCTTGTGGAATTGG
          GATGGAATGTCAATTTTAGACTATCCTGCAATTATGTTCCAAACGAAGTCTCACACCCAG
          ACACTTCTTCCCAGTGCTCAATACACCGTAAAACCACTCTGGGAATCGTGTTTGTTGGTT
          GATATCGTGCTCCTTCGCTGATTTATTGCAAGCTCCAGCGGCCAGCCAGACGGGTACCTC

          TGATCTTGCCCTCAACATAAAAACGACTGCTAGCGAACCAGCTAGCCCAGTTAAGGGTAA
          TGATCTTGCCCTCAACATAAAAACGACTGCTAGCGAACCAGCTAGCCCAGTTAAGGGTAA
          CGTCCATGCTTTCACTGCCATCCTGTAAGGTCATGAGTGGCAAGTCGAGAATGACCGCGT
          CGGTCATGCTTGGATCTCATAATCACCAGGCAAGGGGACGGGGAGAACGATTGGGGGCGC
          CAGTTATACGCCGGTATGCGACTTGAATTGGACGAATGTAAGGAGTTGCCATAGCAACGC
          TAGTCATGTGTCGAAAAGAGTCGTAAGCCGGACGTATGTACGGCGTAGGTACAGCATCGA
          TCGCAACATCCTACTTGCTCGGCAAACCGGGATGCAAACTAGGGGCGACTTCCGCATCGA
          CTTAACTGTTCTCGCCATGATTAACGAAAGGAAGATGGTCGAGTACGAGACAAGCCCCAT

          GATATTATGCACTTCTTACCACCATTTCATCAGACCACAGTCAAGAGCAATACACCCCAA
          GATATTATGCACTTCTTACCACCATTTCATCAGACCACAGTCAAGAGCAATACACCCCAA
          TGTCTGGTGCACTCGTTTCCACCTGTATTTCAGGTCTGTCTCCGTGATAATTTACTCTAG
          AACCGAGTAAGCATAATTTGCGACATTTTCTGGAGTCTAATGTGGGTTAAACTACTTCAC
          TCCATCGTCGACCCTACCTCCCATTATCCGCTAAAGTTAGTCTATGACCATACGACACAG
          ACCATCCATAATCTTTCCTCCTCTTTTTCGGGAAATTTAGTCCACGGTCGAACGGCAGGA
          CACACTTGTCATATTACCGCCCACCCCACCCACCGAGTATCCCCGAACGAATAGTCATCG
          GGGTCCTCATAATTCACGTATTTTTTCCGCTGTGGTATATTATGTGGCAAAGCACTCCAC

          CGGGATGAAGCGTTAGTTCGCGGGACCCCTTCGACCAGTTGCCCGCACAGCTCCCGCGTG
          CGGGATGAAGCGTTAGTTCGCGGGACCCCTTCGACCAGTTGCCCGCACAGCTCCCGCGTG
          CGGTATGAGCCGCCCCTGCGCGAATACCTCCCTCGACGTTTGCTAACTTAGCCCTACCTT
          TAGTCTGAGTCGTCATCATCCGGTTCACCCCCTTCTCGATGGTACAACTAGTTCTACACT
          CAAGATTGAGTGGCATCCTGTGCCTCTTCGTGCCACATGTGGTTACTTGAGAACCATGGC
          TCTTGTCGGGAATAACCGAGTGCAATCTCGGATTTTATGCACCTATAACCGTATCAGGCT
          TTGTGAAGGAAATTAATGTCACGCTCCATTACCTGTGTATAATTGCGACCAATTTATAAA
          TAATACCAATACCCGAAACGCGATCCTCCCCCGCTCTTACCGCCCTGCGTAGGCTACGTG

          AGCTCACTGATAACTCACGAAAGTGACAAGCTTATGGGTGGGGAACTTAAGTTTTAATCG
          AGCTCACTGATAACTCACGAAAGTGACGAGGTTATGGGTGGGGAACTTAAGTTTTAATCG
          AGATCAATTTCGGTATAGTCTTAATAGAAGATCATTAGCTGAGATGTTAACTAGCCGTCG
          GACCTATTTATGGTACTGGAATGTACAGAGACTTAAGAATGATATAACACTGCCTGGCCA
          GCTCCAGTCCTTTCACGGGCGCGTTAGAAGATCAACGGCTGAATTAAGATACCCCAGAAC
          GTTCCGCTCCTTTTACAAGATCGAGAATAGATCTGTAGACAGATTGAGATACCCCAGCAC
          GTCCCAATTGTGTTGCGACGTTACCGTTAAGAAATAGTACTACCAGTTAAACCATGGTCT
          ACGCTACGTAGGTTCCTGCGTCCTGTAGTACTTGCTTATGATATCGGACAATTTCACGTC

          ATTTATGATCGTACTCCGATGTAGCTTGAGAACGGAAGGGTCATGAAACTTGTTGTACCG
          ATTTATGATCGTACTCCGATGTAGCTTGAGAACGGAAGGGTCATGAAACTTGTTGTACCG
          ACTCTCACAAATTGTATTATGGGAGTGGGGCGTGGGGGGCCCTAATGTACTGGCGTCCAA
          ACTACCGGATATCCCGCGGGGGGAGCGGAATATGGGAGTGCCCAGGAACTCGATGTCTAT
          GTGAGCAGATGTGATTTAGTGGTAACATGGCAGGGTTGTACTTAGGCTTGATCTGAGCCT
          ATGAACAGACGCACATTGGGAGCAAAACGGTCGGGTTTTCCCAGGGGCCGCTATGAATCG
          CGGGACAGACGCGTGCAAAAGGGCGAGGGTCATAGACGCTTCGTGGCCTCCCTCGTTTAA
          GCGGAAGACTCGATTCTTTGTGGAGTGTGTTAGGGGTGTGCCACAGCCGCCGATGAAAGA

          AACGTAAACGGACTCGGTTCTCTTAAACTTTGCGAGCCAACCCCCTTATTAAGTTGATTA
          AACGTAAACGGACTCGGTTCTCTTAAACTTTGCGAGCCAACCCCCTTATTAAGTTGATTA
          AACGCAATCGGACCAGGTTGTTACCCTCAGTCCTGATAGACTCTCGGTCTCTATTGGATA
          GATCCACGAGGATAAGGGGCTCATAAACTCCACTGATTCTTCCCCTCTCCTTCGCGATCG
          CCCTGTTCTCGGTTGGGCATTCCCCAGCTGTGCGCCCAAGCTTCTCCGCTAGTCTGTCAA
          ACTGGCGACACGTTAGACCTCTCCCAGTCGGATACGCTAAATTGGTCCTGAGTGCTTCCA
          GTTAGCGGTAAATTGGATATACACTGTTCTCGGTCCCGATGGATCAACTTATCCCAGCCC
          TCATATAGTATGTGGCTTAATCGTTGGCGACTTCCTCTGAACGTACTTCTCGCTTATCAC

          GCACGTAACAATGTCCGCCTGGCGTTGACTCTACCGATAGATTGGGTCGGCTATCGCTCG
          GCACGTAACAATGTCCGCCTGGCGTTGACTCTACCGATAGATCGGGTCGGCTATCGCTCG
          CCACTCAAAAGAGACGACTTTACAGTGAAGTCTTCGACTAAGACAATCTGACATTGCGAG
          GAACACGACGGAATTAAGTCAACGATGGCCTCACTGCAGGAGGCGGTCTGCCGCCTCCTG
          GGACACCCCGTATATCTCTGGGCGATCGAGCTTGGACTGTGAGGCCTAGGGCGAAGTAGA
          AAACACCAAGCCCGCGCCCGCCCAACAGATTACTCATTGCAAGAGCCACGCCTAAGTTCA
          CCGTTCCATGTACTCCGGCGGGTCGTCACTGACCTGGCTAGATACGTTCTATTGCGTCGG
          ATATACCGCGAACTAAGTTGAGCAGCTCTCAATTTGAATCAACGCGCGCGATGACACACT

          ATGTCTCCGCAAACGTAGAAAAACAGTATGACCGGTTCTA
          ATGTCTCTGCAAACGTAGAAAAACAGTATGACCGGTTCTA
          ACATTTCTTTTAATATAGCGGAATTATACCTACGTCTACC
          ACCCTCTTGGTAACATAGATAAGTTTGATTAGCGACTCCT
          ATGTCGTGATTGAGGTGCGAACTGCCTGGACGACCGCGAG
          GAGTCGCAGACGCCGTGCGTGCCCCCTAGAAGCTGACAAG
          AAGTCACGTTACACATCAAGTAGCGCTCCGAGTCAGGACG
          GAGCTCCCAACTCCTTAATGAAAGACTCAACGTTACCATG

