 8 1000
t1        TGATATACATGGATGGTGGTATATAAGGCCCGGTTCCTAGCAGTTCAGAGACATAAGGCT
t2        TGATATGCATGAATGGCGGGCAATCCGAACTGATTTATTATAGTGTAGGGACCCACGTCC
t3        AGCCGGAGATCGACGGTGGGTGTCGGGTACCGAACCATCAGCCTTCGTGAACTCAGAACT
t4        TGTTACATATTTATGGAAGACGTAGGTCACTGTAGATTTGCGGCTAATGTACTTAGAGCG
t5        TCTTTTACACGAATAAAAGCCGACGGACTTTTTATCCTAGCCAATCACGTGTTAAGGATC
t6        TCTTTGATACGAACTATAGACATGGGGTCCTTTATTGGCGCAAGTTACATGTTTAGAGTA
t7        CGTTACGTTACTGGAGACAGTCGGGAGTTTGATATGGCAATACGCGCAGAAATTACTATA
t8        GTCGACTCTACGTGAGTAGGTCAAGAATTCAGTCTAGTACCACCACAAGCTGTGCATGTC

          TCCTACGCCAGGTTGACAGTCCTAGGACGCATTCTTATTCGGGGGTCCTAAGAGCAGCAG
          TGTGATGATAGGCTGACAGTCCCGTGACGCGTTCGCGTCTAGCGGCCCATAAGGCAGCAC
          CTCGACTCCAAGTTAGAGACCCTTTGAAACTTTCTGGCCAGGTGGTCTCTTGAGCAACAC
          AATGGAGCCGGAGACGAGAGCTAATGTTCTGTATTTGCGCGCCATACCTGAGCCCGATGC
          GTTTAGACCTAGGCACAAGACTATTGCCCCGCGGTCAATCGGTGGTGACTCCCGTGGGCC
          TTATCCGTCAAGGAACATCACTACTCGACTATGTTTGTTGAGTGGAGACCAATGTGGGCT
          CTGGCCATTACAACACCCGCTAAGTGGCCAGTGGGCGAGTAGGCGCCGTACGTGATCCGT
          CCAGCTGTTATAACGCTACCTAAGCGATGAGTAGGTGTGCTGCAAATATATATATGACTA

          GTTGCGACGTTAGGTACTCCTCTGAGTAGTTTCAGGAATCCACCGGATCGCTCTGCCATC
          ACTACGGCGTCGGCTACTCCTCTGAGTACTTTCGGAGATCTCCCGAATCTATCTACCCCC
          ACCGCGGCGTCGATTTCCGCTCTGCGAGCTGTCCCACCAGTGCTGGGTCTAGCCGCAATT
          TCTGCCCTGCGGGTTGCCGACCCGGGTGCATTTTTATGTGAGAGGGACCAACATGGCTCG
          TAAGCGGGGGCCATTACTCATCCGAGATGGCTCATTTGCTCCGGGGTATCACTGACCTCC
          CTTGCGGGGTCTCTTAGTCGTTTGGGTCTGTGTGCGCGCCCAGAAGCTTTACTAAATCTT
          GGCGCGCTGGCCTTTAATAATCAGGGTAACCTTTCGTATTATTAAGATTAATCTGAAGCC
          GGCGCGATGGCATATCATGACGACGACCAATCCACGAGGGACCAAAATTCACCCGATGTC

          AACTGTGAATCTCTATTATTAATAAATGGAAGGCATAAGCGTATCTGGCCCGGACGCCGG
          AACTGTGGATTTCTACCTTAGCTAAATAAGATGCACAAGTGTGTTTGGTCCGCACCTTGG
          CGATGCCGGTCAATGGCGCGACTTGGTAGAATGCAGAAGCTCTTCTGGTCACTATATTGG
          AGTCGTTAGACCCTGCTACGACCTACTGCGTCGTGTAGATTAGCCTAGGTTGAGATACCC
          TGAGGAGGATCATAAGATTTATTTATATCGGAGCTCAGGTACATCACTGTCAATAGAATG
          GTGGGCCAACTTCTATGATCACCTAGGATGAAGTCCAGATACATTTTGGAAGGAGGGCTA
          GTGCCTCGGGTCCTAAATCTAATTGGATTGGGAACTAGGGACAACCGTACCGGTAAGTTA
          GCCCCTTGGGGCCCATCACATCTTAAAGCCGGAAACTGCGCTACCCAGATTTGGGAGTTA

          CGAGATGCTGTCGAGTTGTGTTTTGGGATTCCGTCCGGTATCCTATGAACAGTTGTGTAG
          CGCGAAACTGCCACGACATGTTTCTAAATTCCGTCTGAAACCATGCGTTCCGTTGAGTAG
          CTTCGTTTAACCACGCCATGTTTTCGTGTCACGTCCGGTACCTTACCCTCTGCGGTATCC
          TACAGTACTCCCATGTCATGTCTCTGCCTGCTCCCTAAAACTCCTTCTGCACCATCACGC
          TGTAGAATATGGAACCAAAAAGTGCGGCTTTACGGCGATTTCCAACCTTAACCGAAAAAC
          TGCGGACAGCGGAGGGGACAGTTGAGGACCCAGTTCGGTTTCCATTTTACGCCGGTGCAC
          CAAGGACTGTTGCTCCCCCACACTCGCATTCTGCCCTGCCCGCGGTTCGCCCCGGTATCT
          TCAGGGCCAATGTACCTGCACACCCAGACTTTGCTTAGTGCATAAATGGCACTGAGGTCC

          GTGGCCTCTTCGCCCTATTCAGAATAACGCGTGCGGTAATAGCCGGTGATAGTTTTTTTA
          TTGGCTTCGCCGTCTTCTTCAGAGTAATAGTAGTGGCAATAGTTGGTGACATTTTACTTA
          GTATGTCCTTTGCATAACCCAGGGTCACGTCGGCGTAATTAGTCGGAGAAAATTCTCTAA
          ACATTAGTTGCGTACTTTCCCAGGTAATGCTGGCGCTAGCAGCTGCCGGATCATTCCAAT
          ACCTCTTTTCTACAATTTACAAAGAGCCTTCAGCGAAGCTACAAAACAACGTAATAGCCC
          TCGGTTCTTCCACCATGGAAAAAAGCTTGTCCGGAACAATAACCAGATACATATTGGATC
          GGGTACGCGATGACTCCTTTTTTACGTCAGCTATAGTCACTCCAGCGCGGACTCTGACAC
          GAGTACGCACTGTTACCCCTTCTACATTAGCGATTGTTCTTACTCTACACACATCTGCAA

          TAACACTTCAACAGCGGATCGAGGATCCCGGGCCGCATACGCGCACCTGTCTATCCTACT
          TAACGCCTCACTAGCGAATCGATGAACCCGGGCCACATACATGTCCTCGCCTATCCCGTA
          CAAGGTCCCAGCGCCCAATATGCGGAGTTGACTTGCATATTTGTACTTGATTGCCTAGTT
          TTGCTCTCCTACACTGATTGCATGAATTAAGCTCCTATACTCGAGCCCGTCTTTCGTACT
          TACTACCCTAATACCACCTGAGGGTTCCGGGACGTAATTCAGGACAATAGCCACACCGCC
          ATCCGTTACAAAACTACCTGTGAGACCTGAGACTTCCATCTGGCTGACACCTATACCGTT
          CCACATAAGGGTCACGTCTCCGGGACCCAAACTGCAGTATATGGCATCGCTCCTCCTCCC
          GTGTACGTGATGGGTGCATCCGCAATCCCAACAGCTACTTATGGCATCGCTTATGTCGCC

          TTGGCGCGTCTAATGGTGCGTACGTGTACCTTTAAACGCACAAGGGGGACGAGGCTTGCC
          CTAGTGCGTTTGAGATCGGGTAAATGTACCGCTAAACGTACAAGGAGGACGTGGCCTGAC
          CTAGCATCTCCAATGTTGTCTAAATGTGCTCCCGAATAGACGCGGCTGACACGGGCCGGG
          CTCGTGTACCACTCAGAAAATACAATCTTCTTTAATGCAGCGAAGGTACTACTTCCCGAG
          AGTCCGCGCCCCTTTGTTCGTCGACGCGAGTCAATCTTTGTAAAGGTGACATTTCCCAGT
          CACACATGCTCGTCCGCCAGTAGGCGGAGATCGAACCTGAATAAGATGATCCGACCCAAT
          TATACATACCTCGCTTCTCGTTGAAGGCCGTTTGAGCATAGGGGACTTTCAGTGCCAATT
          TTGGTGCGCTCATGGCTCAATGGGAGGATATACGAGGTAGAGGTAACCCCAGAGTCACCT

          TCGCGCCTAGAGGATCGCGGGAGTCTCACGTGATTCGGCGTTCGCGCATATATGTGCGAC
          TTGTCCCATGAGTACGGCGGTAGTAACAGGCAATCCGGTTACCACGCATCTGTGGATGAC
          TATCCCCACGAGTTCTGCGGTAGCTATATGTGACTCCGTCACCACGTATATGGGAACGAA
          TAGTACTATGACCCAAGAGCCTGGCGCCGCCGGCTTCGTGATCATGAGTTTTTGAGGGCC
          CGAACACTGAAATACGAGTACCGGCCAACATGCTTACGCTACCGTACTGGTACCGGGGTC
          CGAACTCCCATATATGGGGTCGGACTATTATGTTTTCACCAACATATATAGAGATGGGCA
          CATGTTTGCCGATTGAGGGGGCGCACTACGTGATAAGCTCTTCACGTAGTCGTGTGTATA
          CATATCAGCTAGTTGGGAGCGAAAGCTTCGGGGCACGGCGCCGATGCAACCGTGCGTATA

          CCGAAGTAAGGAGACCACTTTGTGTATATGGCTAGGGAGTGTCCTTTACACTATTCGAAG
          CCAACGTTGGGATGCCGCATAGTGCACATGGCTAAGAAGCGTCCTTCATACAGCTCGAGG
          TTCGAATTGAGACGACAATGCGTGCACGTAAATAAGAAGCGGCCCTTACTCCGCTTTAGG
          TTCTGGATTTTTGCCCTTTATGCTATAGGAGTTACGGACGGCGACACTCGTCATTCATAC
          CTCAAACGTATTGAGTAGAATGGGAGCATGCTCTAATACCATAATTCGTGACGGGTATCA
          CTCCAGCGTATACTGCCGCATGGACGCACGCTGTAGCGCCTCGGTACGCGATTGGCTTGA
          CTTGGGTCATTGTCTCTTTCTGCATGTGGGGACACGATCAACAACATGTCTCCTCCGTGC
          TCTGGGCCGGTGGTCCACTTTGCTCATGCAATCCTGATTAATGATGGCCCTCCTATCTGT

          TGTCAGCTCCACACTACCCCATAAGTACGGCTAGTTGGATAGTACGGAAAGCCCCAAGAT
          TGCCTGCCCCGCACAGTCTTGTGAGTACAGCTAGTAGGATAATCCGGACAGCCGCAAGAT
          TGAACTGCCCGCTTCGCCATACGAGTATGGGTAAGAGGACGATAAGGGAAGAGCGGAGGT
          TGCATAAGTCGATGTATCTGACCATCAGGGCTGGTATAGAGACTAGGATTGTTTCGAAAC
          CATTCAACCAGTGTCACAACATCACTATGGCAGATTATTGGCGCGAAATAGCCGTAAGAC
          TGTTTAACTTACGCCATTCCAAAATCATCAGTACCTGCACGATCGCAATGTCCGCAAGAC
          CGTATTGCATGACACATTGCGCGGAAATGATCATGGCTACGCCGACACCCCTTCACCAAC
          CTCGTGGTACGGTACATCGTCCGGAACCGGTCATAGTTATGCCCCTCGCAGCCCCCAATT

          TGACTGGCCATGAACGAATCTTGTGGTATCTTAATGAGCATTTATCCATCACCCGAGATC
          AAAACGGTCACGAACGAATCTTCCGGCACTCTAGTGAGGCTGTCCCCCTAATCCTAGACC
          GTTGCTTCCGCGACTGGCCCTCTCGGGTTTCTAATGGTACCGCTACCCGGCTCTTAGACC
          TTCGCGTTTTTAAAGTGTTCTTCAGGATTGACGCTAGCACAAACCTCAGGCCTCTGTGTA
          GGCCGGTCTTTACTCCCTCTCAGCGGGCGTTCCTACTCATGCGCTGCGATCTTACGATCA
          GGCGAACTCCATAGATTTCTTTATGGAGTTTACCAGTCTTTTCCTCTGAAGATCTAGCAC
          GAACGAATTTTGTATCGCTTCTACGTACCATACCAAATTTAGTTTCATCATTCTTAGTTT
          GAAAACTTTTCGTATGGTTCTCACGAGCACCCACCGGCTTCGCCTTGGCCTTCATAACGA

          GAAAGGTATATACTAGGTAAATCAGTTGCCGATGCGATTATATTTTTCACTGCACCTCTC
          GAGAAATATTCACCTGGTAAATCGACTGCAGATACAGCAATACTTTCAACAGCAGATCTA
          GAGGTGTGCATATTTGGTAATTGAACTTTATATGCGGTAACATCTTTAACCTTTGCCTTA
          CGGGCGTCAATGCCGATAGGTAGGGTTCCAAGTTTCGAATACACTAAACGTCTAGTCGCT
          CGATCGCATGCTATCGGTTATTAGGTTTAGAGATTAGTGCCCCCCCCGTCTCACCCAGAG
          TAATAGTTTACAACAGACAATTAAGTACTGAAATGCGGATCTCCCGTATCTCGACATGAG
          TCGCTACGGGGCAACCGTAAATAAGATTAACACTAGAAGGTGGACTGGGCCTAGGGCACC
          ACACTCCATAGTGCTTAGAAATTGGGCTCGCAATCAGGACAACGTTTAATCTGGAAAGCC

          GACTTTTGAGGTTGCGGTAGACTACAAATTTAGCGTGGGCCGCCCGTCGGCTATAGCGGG
          TATTACTGACGCTTCTGTAAACGGCATCCTAAGTGTATGTCGCCAGCTTATTGTTACAAG
          CGCCGCTAACATGGTAATAATTCAGAGAGCTTGTGTACGCAGACTATTAAATGCTTCTAA
          TGTACCTCGCCCAACTGACGTCTGTGAATTTAGGGTACTCGTTTCACACTATATTCAGTT
          AGCCCTGTCTGCTGGACAAATCTTTGCTATTACACTGTATTGTGCAGCAGGTACGCAATG
          TGTCATTACCGCTGCGGGAGCCTCGAGCATTAAGTTGGACTGTGTGACGGCTGTTACGCA
          CCAACTGCGCTTCATACGAAAGTCCCGGTTCACGCACCGAGATACACGTCTCTAGACAGC
          CCAGCTCGACCACACTCAAGAGAAAAACTCTCGGTATCGAAATACGTAACTATAGCTTCT

          CAGCCACTTTATAGCTTACAGTAATGAGAAAGTGCTGCCGTACGAGCATCCGATTGATAC
          TAACCAACTCACACCTTACCGTACAGGGGAAATGCTAACGTCCGAGCCTCAAATTGTCGC
          CGAGCGATACACAGACTTTAATAATGAGCAAGAGCTCTTGGGAGTGCATCCACCTGCTGA
          TTACTATTCAGTGTATCGAAGGCTCCGTAGAGCGCATTTGAGACAGTTACCGGTAGCTTG
          TAGTCTTTTCGCATCAGTCCAGATCCAGCAATTGGAACCGCATGTCTGACCCTGCGTGGG
          TTATTCCATCGCAGCCAAACTGATTTGGTAAGCGTGGCTCTAGACGTGATCGCATGTTGG
          TTGCTGAGGGTCTCATTTTAGTACAAATTCAGCCGGCCGACCAGTAGTGTAACACCCCGC
          TTAATAAAAGTCACGCTTTAGCGTTAATCCGACGGGACGGACAATAGTCTTGCTTTCCGT

          ATTAACCGTCCTCCTAGAGCGCTCTTGACCAAGGAGCTCCTATGGGCATCCCCAGTTTGG
          CTTATTTATTATCGTAGAGCGCTCCTGACCAATGTGTGCTTGCGAGCATCCCGCGCTTAG
          GTCGTCAGCACCCGTGCTTCGCACTTCAAAAATACGTAACTATACGAGTCTGAAGATCCG
          GTTCGCCTACTCGGCGTTCCGTAGCTAAGAGAAATATTATCGGGGCCCTCTTAAATCGGG
          GTTGGTGGGCACAAATCAGCGCAGCAACGTCCGCCGCCAACGGACTGGCATTTAGCTGCG
          GTTCGAGGTTAGTCAAATGTGATGATGCGTCAGTCGCAACCGCATCGCTTTCACGCTTCG
          AACAACTGGCATACGAACCATCAATAACAGGCGCTAAAGCCGTGTCTACCTGCAAACCTA
          AGCGACGTTCAACCCACCCAGTGACGAGAAGCGCTAGAGCTTCGTCAACACTCAGACCCA

          GCTAGGGCGCAACTAGCTTATCAGATTAGTGAGCTTCACC
          GCTATGGCACTACTAGCTTATAAGATCAGTATGCTTGGCG
          AGCATGATGCCGGTAGTTTACCACCTCAATGCACTCCGCG
          GCAGCTCCAGTAGCATAGGGCCGACTTAGAGCGTCTGGCA
          GCGTTAGCAAACGTTAGCGCATGGGGCAATACATGTCGAG
          GCTGCTGCATCTGCAAATTCATGGGGCAGCGTGCGTCTCG
          ACGCTCGGGAGGTACGTCAAGTGGTATCGAGTATATTGAA
          ACGTTTAGGCAGTCAGCCAGCTGGCACAATGTGCCCTGTC

