 8 1000
t1        TGAAATATCTACCTCTAATAAGACTTATCCGGGGAAGGAAACGTCAGAGCTCGGGTCAGG
t2        AGAAGTATCTATCTCCAATGAAAATCGCCCGGGGAAAGTAACATCAATGGCCACGTAACA
t3        CACAATGGTATACCAGGTGACCTTCTACGGCAAGATATTCGATCTTATTGTGTGGAGAGT
t4        CTGGCCGAGATACTACATCGCCATCTGCAGCAAGACAGTCTGTTTTATTGCGTCGCATGT
t5        GGTATTGCTACAGCGGGCAAGCACCCTAACAGATTGGTGGGTCTCTCTCCAAAGTTTGAA
t6        GGCGCCGCCATGGACACGATGCTCCCATACAAAAACAAAGGCCTTTATCAAAATTCCAGT
t7        CGCGATATTACGTATTTCGCGCTCCCTCACTGAGTCTGACGTAAAAAACACCGAACCAGT
t8        CGCAATACCACGCATTTCACGGATTCTTATTGTTTCGTATGCAACTCGTACCGGAGTAGT

          GATCCCACGGAGAGGTCGTGTCAGGTCAAACCGTCAGATGACTAGGGAACCAGCGGAACC
          TACCTCAAGGTATGTCCGTGTCGGGTCACGGTGCCAATTAGTTCAGAAATCGGGGGAATC
          AGCCTGATTGCAAAAGATCATCGAACGGATCAACTCCTTACTTTAGAGAACAGGATGGTA
          AGCCCGACGCTGGGTGAGCCCTAAAAGAACCAGCCCTACAACCTAGAAAATAGGAGAGCA
          CCCGCAACAATAGCTGAACACCGGACGAAATTATGTCGCGGAAGATGCAGCGTCAGGATT
          CCCCTAACCATAGGTAGACATCAGGCCAATCCACGTAGCCGAAGCTAATCCGATAGAATT
          CGTCCTGTACAGCGGGGAGCCTTGATCAAGTTGCAACCACATTTCTATTCCGGAGCGACG
          CATCCTGTACCGCGCAGAGCCTTGATTAAGATGCTGCAACATGCCCGCTAAGGAACGGCG

          AGGGAATGCACAGATCGGTAGAAAAGTTGTAACCTCACGGGGACCGAAAGAGCCTCTCAT
          AGGGAATATACGTAATGATTGAAATGATGTTCCCTCTTAGAGACCCAAATAACTTGCCAG
          AAGGAACGTCGCTACCTAATGGGAGGTAACGGATTCCCGCGAATTCCCATGGCCCCTGGT
          TTGAAATACCCCTGTACCAGGGGGAGTCACGTCCCCCCACGACATCTACTGCGCTCGGAA
          TGGAATATCGCAGATTGCCGACAATGTCGTGCCCTCTCCCGATAAGTATGGGTCTCGTCG
          TCGGAACGTACAGATTGCCGATAAAGCCGTGTATTCTCCCTGTCAAGGCCCGCTTTCGCG
          GGGGAATGTTTGACTAAGGTTGGGCGCAGTATTCCCCTTTTAGACAAGTAGGCCATCTTT
          GAAGAATGTTCGTCTAAGTTGGGGCGCTTTATACCCCGCATAGATGGGCCCGCAGCATTT

          TGCCTAGGACATACCTGCGTAGGATAGGGTGCTAACTCTAATGCATGGGAGGATTCCGAC
          CACTCAGAATACACCTGTCCCCACCGGGGCTTTAGCTCTAGTTCATGGGGAGATCGCGGC
          CTACTAGGGTAGCCTCGAGTCGACACGCTTAAGGGCTCCAGACAAGGGGCAGGCCTAGGA
          CGCGTGGGGCAGCCTCGGGCCGGCACATGGGATAACCATACACTAGAGGAGGATCTTAAA
          GGCCAAGGTGAACAGCGGAATGAACGTTATGATCAACCCGGTTAATGTGAACACCTTGGC
          AGAATAGATTAGCAGCTGAGTGAACGCTACGATCAATCCGATCAATGAGCTCACCATGAC
          TGCATGGGCCAGGCGCGTGGCGTATTGGGCACTAAACCTAGTCCGCGGCCAGCTCCCGGC
          TTTCTGGGTCCGGCGCTTAGCGACTCAGGTGTCAATCCCAGTCCGCGTAAATCTCCCGAC

          GTAGGATAGCTCCCCTCTGTAGCGCAGAGGGCGTTGACTGATTGTATCCGTGACGCGACG
          GTGAGGTAACCCCTCTTTTTAGCACTGGGTGCAGTGCCTGACCGAGACTGCGAAGAGATT
          TCTGGGTAAACTTTGGTTCCCAATTCAGAGACAGTGACTGCTTGTCATGATGAAGTGGAT
          GCACGGCTTCATCTGAGTGCCAACTCGCCGGGAGCGGCTCTTATTTGCGTTGAAGTAAAT
          TTATGCCTATCTAACCCTAGTTCTCCTAGATTGACGGTATTGCCTATGGGGGCCACGATT
          TTATGATAATATCATCACAAATCTCTTGAACCGTTGGTGAGATTTTTGGGGACCATGATT
          TTAAATCTTACCCGTCCGGTGAAAGCACGATCAGTAATCAAAACGCGTGAAGTAGAGTCT
          TGCAATTTTACACGTTCGATAACTACACGATTAGTAATTAAATCGTACTAGGTCGAGATC

          TTGTGTCGCTTGCGACTTCTCGGATTCGTCGTACTTGTCTATGATTTGGTTGTGTGGCAT
          TCGTATTGTAAGAGCCTTATAGGATGCCCCATATCTGTCTGCGGTTTTGTTACGATGCAT
          TTGGTCCGCTGCCGTCCATACGCATCCTGCAGGGTTATTTCTACGCCTTCAGTGACGAAT
          ATATCTCGACCATGCCTCTGTATACGGTCTAGTGCTGCTTCTGCGCCGCCTGTGTTAGCA
          GTGAGCTGTTGCCATCATCTCGTTGTTCTAAAGCTCGACTTATGCTTTACCAGAAGAGAC
          GTGAGCTGCCGCCATCAGTGCCTTTTGCAAAGGCCCGGCCCTTACTTTGCCACGTGAAAC
          TAAAGTCGCTCACTGATCCCCGCGCGATCGAGTTCTATAGACATTACCTTAACGCGACCG
          TAAAGTCGCTCGCGCCCTCACGGGCAAACGAGTCCCTCTAACATTACCGCAACGTTACAG

          CAACATAATGTCATCTTTTGAGTTTCTTCTCACTGCGGTATAGCTAATCTGAGACGCATC
          ACCATTTGCGCCAGCTGTTGAAGTTCTTCTCATCGCAGTATATCCAGACGGGGGCACGTC
          CTTTTTGAGCAACAGCCATCGAAAGGCTGCACAGCTTTAATGATTACTTATGCAAACGTT
          CTCTTTCGGTAGCAACACTAGAGAAGTCGCACTGCTTAATAGACCAGCTGCACATAAATC
          TGAAACAATTTTCCTCTACTGGGACAACGTTGAGCAGATATTGTTAAGTGAGAGGGAGAT
          TGTTACGGCCTTTCTCTTCTGGGTCACCATAGCGTAGATACTGTTTGGCGAGAGGCAAAT
          CCGAGCAGCTCTGTACAGGGAGTGTCCCGATTGGGTTAGAGGAACAGAGGGGAGATAGAG
          CGGCACTGCCCTATACAAGTAGGGTCTTGATGGGGTAAGACAGACAGAAGAGGGACGGAA

          TTTTGACGCCTTTCTACATCGAGAGAGCGAATAGCTATAAAAGATTTTAACCAGAGTAAA
          TTCCGGTACTAATCTTCATCAGAGGAGAGAATGGTTAAAAACGGCTCCAAGAATCACAAA
          GCTTCGTACCGTGTGAAGGTCAGTGGGAACCTGATTAGTCAGGAACCTGAATTGATCGCA
          TCCTAGTGGCGCGCAGAGCTGAGAGGGGACTTAATTAGCCAAAAATTTTAACTGAAGGAC
          ATTCTGTATCTACTGGTACCAAGAACACGACAAGCCAACCCCAGCCTGTGCTGTACTGGG
          ATTCTGTTTCTACCAGTGTTAAAAGCAAGGCTGGTTAAATCCGGCCTATGCTGTACCGGG
          TGCTTTGCCCAACTGTGGGCAGAACTGCAGCACTCTTGTCAAGGTCTGTGTTTCGCTGGT
          TGCTTAGCCTTATTCCGGCCGGAGCCCCTGTGCCTTATCCAAGGTCTTGGCCTCGCTGCT

          CTGGGATGTTGTGACCGGGGGATATCATAGCAACGGATATCATCGGGAGAGGTCCCATAT
          CTGGAATGCCGTATTAGGGGGGCCCGAGAGTCACGACTTTCATCGGTAAAGTACCCATAC
          ACGGGCTGGAGTGGCGGTGCTCTCGCTTCTATCAGACGCCACTTGGCCGCGCGTCCGTGT
          ACAAACTAGCGAGGCGGCACTTGCCCAAATGCCAAGAGTCAACTGGCCACGCGTGTAGTC
          ATGATGTAAAATTGCTATGTTATCCCCCACTAAAGCGGCCAGCTGCGCGTTAATGTCCGT
          ACGATGCCAATGCGGGATGTTATCTTCTGCTCAAAAGGACAGTTGCGAGACAACCCCCGT
          TCGGAATATTAATGCTCTGCCTTTCCACGGTTGCTAAGTCCGTACATGGGTTTTCAGCGT
          CCGGGATATTAACGCACTGTCCTTACTTGAGTGGGCCGTCCGTGGTTGGGTCATCAGCGC

          TAACGATAACAGTAAAGCGTACCACTGGTCCCGGTTGCAATAGCGTACAAGAAGCAGATT
          TATCGAAAATAGCAAAGCCTATCATCGAGCCCGTGTGTGATAGAGAACTAAGACGTGACA
          ATCCGGCTATACCCGAATATATCTCCAGCGTCAACAATCTCCGGAGACTAAGGGCGCGTC
          GCCCGGCAATGAACAAATGCACCGCGATAGTCGAGAGAGCTCTGCTAAAGGACGTGTGCA
          TCGCTACACTAGCTCCACACTTTAGTTATAACTTGCGCGGATATGCATATCTAGCGGGTT
          TCGCTATACAAGCCCCACACTTTAGTTGTAGCCTGCGCGCTTTTGCATGTTCAACAAGTT
          CACATGGTTTGAAAGAGGACTCCATCTATTTCCAGAGAAGAGCTGAGAACCGGGATGCCT
          CACGAGGATCGATTGGAGATTCCTACAGTCTGTGGAGAAGTAGCCGGAACCTGGTGGCTT

          GGAGATGCCCAGCATCCTTCGTCAGTAAGGACTATCCCAGTCGGCCAGCCTTTTTTGAAT
          GGTGAGGCGTAACCTTCTTTTCCCGTACAAGCCTTTTCAGTCGGCTAGCCATTACTGCAC
          ATTGATACCGGGATTCGCGACGCGTGCGATAGCTACCTGTTCGATAGAACACAGGCGTGG
          ATTGAAATAGGGTTCGACAGTGAGGTTGACAACGTTCCTTACAAGCGAACACTGACGTAT
          AGCGATTCTAAAGCCGCACATGTGCTCAATGAAATCTATTAGGTTGGCAATTTTGTCAAG
          AGAGATTCTACACCTGTATATGTGCCGAATGGATTCTACCAGACTGACCATCTTGCGATG
          CGTGACTCTTACTTTACCATAGGACGTCACTACAAAAAAAGCGACGTGACCCCTTCATGC
          AGTGATTTTTACTTTATCATCGCGGTTAACAACTGCAATGGCAACGACGTCGGACCACCC

          CTATACGGACTCAACAGGACAAAAAAGGGTCAGTGATTCCATGTGTAGAACGACCACCCC
          TCACACGGACCCAAAAGTGATCAGATGGGTTAGCGATTCCAAGTGCAGACAGTGCACATA
          TCGGGCTTGTAAATAACGACTCAGATAGTTACAAAATCAGGTACGTAAGGTGACTTTGGC
          CTGTGCTCGCCAGCAACGACGTAGTTCAAGTTATAATTCGGCCTGGAAAGTAACAACGAC
          GAACCAAGTTTCGCTAGGTAGGATAGAAGTGTACTCGCGTCCACGCATATTGCACTTTGC
          GTGCAGTGTTTCGTAAGAGGGCATAGAGGAGTACCCGCGTCCGCGCTTATTGTGCTTTGC
          TTGAGATGAACACTCGAAGGGTATCAAAATATGTCTATGCAAATGACGGGAGCCAATTGT
          CCTAAACGAGCTCACAAACGGCATGCAAGCATACCGATGGAAATGACTGACGTCCATCCG

          TGCCGAGCAGAAGCACTTTAGCCTACTGTTGACTATACTTCGAGGTATTTGTTAGCGGCT
          TCACAGCCAGCCACACACTAGCTCTTTGTAGTCCATCTTTTGGGGTACTTGTTAGCGGCC
          TACCACGTGTAACCATCCTTGTAGCCCCCGGTTAGGGGCTTTGACTTTCTGCCGGCAGAG
          GAACGTGTGAGATTACCCTCCCATACCCCGCGCAGTCGGTACGGTCTTTTGTTGTCGGTG
          CCACCTGTCGAGCTGAGTCTAAAGTACTGAATCGACAGCTTAAAGGAGTATTCATTGGCC
          CCCTTTGTCGAGCGGTGTGTAGATTACTCTATCGACGGCCCTCAGGACTATTTGTTGGGT
          CGGCGCTCTCAAGTACGTCCGAGCCCCTCAATGAGTGGACAGGAGGTGTCGGCGGCGGGG
          TGGCGTCCCAAAGTTTGCCCGAATCTCTCTATGAGCAGATTGGAGATATGAGCGAGGACT

          CCGTACCGCTTCAGCACGGGATTCCAGAAATGTAGGAAGTAAGTTGACTCCTGGGTGAAA
          TTGTCCGGCTCTGCCCTGGGACTTCAGAACTCCAAAAAACAAGTAGATTTTTTGGTAAGA
          CTGGAGCGACTGAATAAGGGCGGGCATAGTTATGCGAAGCACCTTATTTTATCAGCTCTA
          GTGGAAGGCATCAAACCGGGAGAGCATGGTCATATGAAGCGCTCTGTTTCGTCGGTCGTG
          TGTCATAAATTGCACCAGGGAGAACCACGCCGCAAAAGCCTTACCAGGCTCTAGGTCTAA
          TATGAAAGATTACACAAGGGCAAACGGTGCTATACAAGCTTCAGCGGGCCATGGGCCTGG
          CCGTAGGGATCCAGCGCGGATAAACCGAGATATGAGATACGATTGACGGTGTGGGTTCGA
          CTGCAGGGCCCTAATACGGGCAACCCGTGATACGAGATATTCCTAGAGGCATGGGTTCGC

          ACCTGTGAATGCTATATCTCGAGGGACTCCGTACACGAAGGAAGCCGCAGGACCCGATGA
          TCCTGAGCACATTATATTATGAGGGACACGGTCCAAGAAGTTGGCCATCGGACCCGGACG
          CACCTATCAAATTATGGTACAGATTCATACGACGCAGAAACTATGCCTGGGACACGTGTC
          TCCCAATAAAATTTCATTTTGGATTAGTCCGTTTCAGAGATGTAATCCGGGACTTGCGTC
          CTACAATGCCTGTCTAACTCGAGATAGACGGCCCCGATCAAGATAGGTTGAAAACAGTGT
          TTATAATGTCTACCTGTTTCGAGAAAGACGGCCCCGGGCAATATAAGTTGTATCCAGTAT
          CACTCGGGATTTCCAAGCCTATAGATCGTCATCCAAGAGACCCCCAGCCTCTAACCGGTA
          CGTCTAGGTTTTCCCAGCCTCTGGCTAGCAGCTCGAGAGCCGCCCAGCTCCCGACTAGTG

          CTTTCATTTATTTGTTCACTATTAAAAGGTTATGGGGGTTCCGTTTCATGACGGGTGAAG
          CTCTCGTGCAGTTCCATTCCACTCAAAGGTCAAGGAGACTCCGACAATTGACGTGTGAAA
          TCTCCAGCCTTAGTGCCCCCTGTCTGAGAATAGCGCAGCTTTAGCGCGCGTTAGGGAAGA
          CCTCCGCTACAAATGTCACCGATTACAGACCACGGTGCTCGCAGTGAGTGCTGGCACAGA
          CACAAAAACATGTCCTTCCAAACCGACCTTAGCTAAGGAACTGGTGTTAACCTTCCGATA
          TTCATGATCGTGGTCCTACCAACTAACCTTTACAATGAGATTACTATTAATCATCCGGCG
          CTCCATCACACAGCGGCAACAATCGCAACTCACAAAGGTCGTAACGCGCGCAATGGATAA
          CCCTATTACGTAACGGCAGTTGACGAAACCCTCAAGGGTCCCAATGCATACGATGGATGA

          TTCTTCAGTAGAACGTGAGCTCATCTTAACCGAGAGGGCG
          TCCTGCAGTTGGAAAAGGGCTCAACTTGGCTAAGAGGCTT
          ATACGGCCCGGAACGTGGCTGGCATTGGATAAAGTGGCGG
          AGATTGACTCGGACCAGTTTTGTTTCCTACCAACAGGAGA
          ACTTGTACCCGGAGGTGTCTTGTCCCTCATTATGATGCCG
          GCTTGCACCTAGCGCTAGCCTGTCCTCTAGTATAGCGCAG
          CCGTCCAATCACCACCATGTTGATCTTACTTGGAACAGAG
          ACGTCCAACGTCCCCCATGTAGATCCTCCGCGTGACGGCA

