 8 1000
t1        CACTAAATCAGTAGAGGCGCTGTGTTAGCCGGGAAGCACCTAGGTCAGATTGATACGAAC
t2        TATAAAGACGGTAGGGGCGTTGCGTTAGCCGGGGTGCATCATTGTCAGACGGCCACGAAC
t3        CCATAAATCAGTAGCGTACTAATTCCCTCCCATCAGGCCGACCGATATCCTCATAGGAAC
t4        ACCTGGCGTTGCGGTGTGGCAACGCAAAAGAACGAAAATATCTTCTCAACACGCTCAGAT
t5        GAAGCCGTTGAGCGCTGAGCGCCTCATCTTGGCGTAGACAAAACCAAAATGCCATCAGGA
t6        GCACTAATAAGTAATCGGGTCAAACCCGCAGCTGAGGTCCACGAGTAAGGGCGAGTAGAT
t7        ACTGCTGGTAGTGAGTTGTCATTGCGGTCGAAAGGAACCGAATTCCATGCCCTGGTATGT
t8        ACCACTGATCCCGACCGGTCTCCGCCGTCGAGCGCAACCAAACCTCAGGCACAGGCAGGT

          TGCTGGCTTATATTGGAAACTCTAGCAAACAGTTAATATATCCCGATTCAGTCTCTCTTA
          CGCTAGCTTGTCTTGGAAATTCCAACAAACAGATGTTGTATCCCGCTTCAGCATCCCCGA
          TGTGCGATTCTCCTTGCTGCCCAGGTCTCGATCTTATTTCCCTCGAAATTTATCTCTACA
          TGAGTTCTCCACTTCTGCACGCCCGCTCCTAGTTAATGCGCCGAAATGTCAGATAATCGA
          TCCGATCCAGATCACCGGCTATAGGAACCCACCCTGTTCTACGCTTAGTCTCATCCGCAA
          GAAATACCCCCGCACGGCTTTGTGGGTTTTTGTAAGCACGTCTTGGGGTACGAATAGAAA
          ATGGTATTGCAGGAAACGATCTTGTAGTACACCGAATATATTGAGTTACATGCTCATAAG
          ATAGCGTTTCATGGAATGATCCTGTAGTACATTTATTTTGTTTAATTACGCAATCAACAG

          TGAGCAGCTATCAGCAAACCGTTGCCTTGCCAGGTTATTTAACTGAACTGGGTCTAGGGG
          CGACCAGCCGTCGGTCAACCGTGTCATTGCTAGATTATTTAACCGTACTGGCACTGGGAG
          TGAAGGACGGCGAGCCAATAGAACCGTGGCAAAATCGCTCAGCTGAGTTAAGCTTAGGAT
          CGTCTCCGAGCGCCCTGTCTCTCCCCATTGCACACGGAGATAATGGTTTATCTCGAGAGC
          CAACACGAGATGAAATAGTCGTAAGCCATAGCAGCTGCGATTCTGTTTCGCTTAAACAAA
          TAAAGTGCTGTGACGACGCTCTTTCCACGTAGAGATGTGCTGACGTTTTCAATTGGTTGT
          CGTCAGTGGATAACCTGACTCGCTGGGGTCAGGGTAGTGCGACCTCATAGCTCTACGCAG
          GGTTAGTGCATGGCCCGGCTCGTCTGACTCAGAATTGCGCCGTCGTATAGTTCTACCCGG

          TCTCGGGCTGCGCATGAAGATCATATATATAACACAACCCGGTTTCCCGCACCCCATGCG
          CGCCGGGTCGCGACTGAAAATCGTATGCGCAGCACATCCCGGTACCCCGCTGCTCATAAG
          CCTCTGGTAACGCATGCTAATACCTGACTGACTCTGACAATGTGCTCCTTACACAAGGAG
          CTCGAGTTTCTAAGTTGAAGCGTTGACCCCGGTACGGCAAAGTGGACAACTCGGTAGAAA
          AGCTCGAAAGTAAATTCTGGTATTATAGGAAATGTGGGTAAGTACTTTCTGCAGTCGCCC
          TGTCGGCCTTTGATACACGTAACCCAAACATACATGTTTTTGCGCGTTGGCTTCTAGTAG
          TGCTTGTACAAGCCATGAATTGAGCGAGAAAATTGTAATTAGTGCGACCCGCGCCGAAGG
          CGCTTATAAATGCAATGAACCGGGCAAGGAAACCAAATAGAGTGCGACCGGCGTCGAAGA

          GGTAGTGTTTTTCTCGCTATCGTCGACTCGAGCATTTGATTATTAGTCCATCAAAAACGT
          GGGAGTGTTTTCATTTTCAATACCGGGTCGGGTCTTTAATTGTTAGTCCGCCAAGAACTT
          AGCAGCGTGCCGTTCCTTATCAACTGATGAAATTCATGATCATAAATCTGCCTAGGGCGG
          TTGAGCACTATTGCCCCCCTTAATAAACGGACAGAGTTTCTAATAGAACAATCGAGGAGA
          AGAGAGGCTCCCTATACCTCATTCAGTCACGGACGTTTGCTTAGCTTACCACGGGCGTCT
          AAGACGTCCCTCGTTTTAGTGCCCGGTTTGAGGAGTCCGTCCGGAGCCGGTCTGAGGTAC
          AGGTAGATGCAAATCACTTCGCCAACAAAAGGGCGTTTGCTGTATGCCAGTATGGCCTCC
          CGATAGAGTCAGATGACCTCGGCAATGAAAGGGTTTTTGTCGTACATCAGTGTGGAGTCT

          GCTTATGATCGGAACGCAAGAACCTGCCGACGCGGGCCGAGTGTCAATGGGCAACCGCAA
          GCTGATGATTGTAATACATGATCCCGCTAACGCGTGCCGTGCGTCAGCGTGCAACCGCAT
          GCCAAGAGACAAAACTTCTACCTATGAAAGCCCGGGGTCAATGTCAGCGTGCCGTAACAA
          GCCGTCTACCGGAATATTCACTGCGGAGCATCTACACCGCGCATTATGGTTCCACGGCTT
          GCTTATGAGTGGTATACATATTCGATCCACTCCCTGCCGTGTGAAATGGAACTAAAGCAT
          GCCAGGAAGTTGGGCGCCTGTTCACACGGCTTGGAGAAACTTGAAACGGGATCGCTGTAT
          ACTTATTATTAGACTATTCAGCTGTCCCCATCTCAGGACCGGGCGTCCGCTACTACGCTC
          ACTTATCATCAGATTCTTTAACTGAACCCATCCCAGGGACGTGTGTCAGATTGGAGATTC

          TCTTCTCACATGCTCGCGTTTTACTCTGAACTAATGAGTACGGGAGAGGAGCTCAGCCAC
          CTTCTTCACGTGCTCGCGTCTTGTTCCGAACTGAGGAGTACGGGAGGGGAGTGCAGTTTT
          TTCGCATAAAAGTAAATACTTAATCCTGAACCTACGAACAACGGACGCGGACGCAGCCAC
          CCCGTTTAACTGTCAGGATTCAGTCCAGGATCCAGAGTTGTGCAAGATGGGTCAATTTAG
          TTACAACGACCGTGGGCGTTCGGCTGGTTGCTACAAGAGGCCGAGGGCGCGCCCGCGGCT
          CTGTTTTGTATGAGTCTGTGCGGGTTGGAACTAGCTCATACCGTAGGTACCGGTCTGCGT
          TTGTAAAGAAAGGCAGGACCTTACAGGGGATTGATACGCCTAGATGTTTGGGGCCCATTC
          TCCCGAAGACACGCAGCACCTCCCGGGGGTTTTAAAGGCCAAGATGCTTGGATCCCTGTC

          TGAAGTAGAGCTGAGCAACCTCGTTTTGCCCAGGGATGAATATCCCGAGAATTACTAGGA
          TGAAGCAGAACTCCGGATGTTTATCACGTCCAGATGCGACACACCCGGTAATCACTAGGT
          TGGCGTAGGGCCGGGTCATCTGATTGTATTTTTAGTTAATAAGTCGAGCGTCCGGTCAGA
          TTAGGTGGAAATGGTCCTCCACACCAGGTACCCGTTAAAAGAATAGCCCAGGGCCAAGGA
          TTTTGCGTAGTTGTTCGGCTACGACAGGCGGAGGAAGCTTAATCCAGGTAGGTAGTACGA
          GGGCGGAAAGTTGGGTTCCCCTGACGAGCGAAGCTGTGGATATCTCCACAATCGTCCCAA
          CAGTGTCGAGGTAAACACCAAGGCTTAGAGCTAAATCCCAGTCTTTAGTATCATCCGATG
          CAGCGTCAAGGCAGGTACTAAGGTTTAGAGTTGATTCTCGGTCTTCAGCATCATCCGACG

          GTAGTAACCACAGGTTGGAATCTATATCGCTTGGAGCTACTCCGTGATATGGGATGGCCC
          GCGACAACTAAAGGTTAGAATCTATATCGCCTGGAGATATTTCGTGCCACGGCATGGCTT
          GTAAAAGCCTAGTTCTGTAACACCCGACACGAAGAGAGAGTGAGTGTAGTTGAGGAGTAC
          CAGTCGAAGTATGCTTAGGTGATGTTAAGCAAGGGGCAATCTCGTCCGATAAAGGAGTGA
          GGCATTTATGGGCTCTAGCCGTCAAGGTAACCTACGATTACTAGCATTCTCAAGACGAGC
          GATAGACCTAAAAGGTGGGCTAAAAATGGACTCAGGCTACCCTCGGTAGAATGAATAAGA
          GGGACACTATGAAATTTAGTAGGCCAATGATAGGGTGCAATCGATGCTACTCCAACAAAA
          GGAATGCTATGAAACATAATGGTGCAACGTCCGGGTGGAGCCGACGCCACCCTAATAAAA

          ACCCCCCCATGTTATATAATGGACAGTTCGCTGGCTAATAAAATGCCCTTCGAGTGCCTA
          TCCTCGCCTCACTAAACAAATGAAGGATCGCTGACGACTAAGAAGCCCCCCGGGTGCTAT
          TCGTCACTATTCCTCATGGAAAACTGCAAACTGGTCCACCCAATATCTTGCCGATGCGTA
          TCAACACGAGTCGCAGGAGAGGTGCTTGACCAAGGAACTACGATCGGCCGAGCGTAAAAG
          CTCTTGCAAGCTATCGGAAAGGCACCTTAAATGGGAAGGAAGATGTGGGCAGAGTACGGA
          TTAGTATAGAACAGCGCAGTGAAGTCGGTCTAAGTCATATAGTCGCATACAGGATAGCCG
          ATGATACGGCCCACACCTTGAGGCTCGAACCGGGCTAAAGAACGGGGCATAACGTAGATC
          ATGATACGACCTATGACTTCAGGCTCGAACCGGGCTTAAGACCGGGTCATAACGTGGACC

          ATCATTGGCGATCTACGACCCACCGTCTCTCTATCATTGCCAGTCTTATTGGGGAGGGAA
          ATCATTGGCGTTTTACGACTCACCGTCCCTTTACCAATGCTAGCCTTATCGGGAAGAGAA
          TATTTTGGTTACCTCCCGTCAAAAGTTCCATCTCCACTGTCAGCCGAGCTGTGCAGCAGA
          AAACTTGCGAAGTCGTAGTTATTCACGCTGAGGGCGGTCGGGGCTGATTAAAGCATCGGG
          GCCTTTTCTACGCTTTGGTTTCTTAACGTACATCCCTAATTAGGTGGCCCAAGTGCAAAA
          CCCAGTAATGATCCAGACTCGGTAAACTATCCATCATCGTCAATTGTGTCCTGACCCGAG
          TCCACCAATGGCGGGCCATAGACCCCTGTCGGAGACACAACTATCATTCGAGGACCGCGA
          CACACTAATGGGGCGCCATAGATTTCCGCCGGCGAGACAACGGTCACCTGAGGATCTTGA

          GTGTAAACCTCACTATACCCTAGGGCACCGTTTTGAAGCGTTTATGCCTTAACTTTTGCA
          GCGCAGCCCTCTCTATGCCGGAGCTCATTGCCTTGGAACGTTTGTGGCTAAAGTCTTGCA
          ACGCAGCCTGCCTTGTATCGACGTGCAAGTGCGTGAAGTATTTTTGCTTTCAGTGATAAC
          GGGGTAGTCGACATAGCGTAGTATGCTTACTACTCGATTGCTAGCGCACATCGGGATGGC
          GATAGAACTGGTGCTAAATTGCCCGTCTCTTGGTAGTATATGTGTGTTACCGATCGCATT
          GGACACAAGATCTTTTTAACATGCTTGTCATCCCTCCGTCCTCGCGTTTGGTTCAGAATT
          GTACGTACCTCCCTCTCTTATAGCTAGGCACTCTCACGAATTCACGTCTTCGGAACCAAT
          AAATGCATTACTCTTTTCCATAACTAGGCTCGCGCACGGATTCAAGCGTTCGGAGCTAAT

          GGCGTCTAGCCAACTCGACTTTGACTAATACCAACGAGTGTTTTGGTCAAGCCGTGGTGG
          GAGGCCTAGCCTACTTGATTTTGGCAAACACTATCGGGCATCCCGGTGACGTCGCCGTAG
          GGGGCCTCGCGAATTGGCTGTTCATGGGCGTTCTCGAATATTCCAGAGCTAGCGCGGCGA
          GACGGCTCGCCCCCTGGTCCTCAGTCGGTGCTACGGTGCATTACGCACTTAGCACATAAA
          CAGAAATCTCGTACTTAAACCTGCCATCCAGCTTAGAAGTTATGGTCACTGGCGCGGAAT
          AAGGCTCCTTACATCCGTCCCCCTCGAATCCCTTTGTTTGTTTTAGCAGCGGCAGGGCCA
          AAACACTCGTATAGTCGACGAATACTGGAGCCACCAGATTCTTATGCGCTGTCACAGGGG
          AAGCAGCCGTATAGCTGACCTAGACTAGTTCCATCCTATTTGTCCACGCTGCCATAGAAA

          TGGCGCAATTAAATCTATAGCCTCGACGCGAACCCCCCTGACCTCACCACTGTGATCGGT
          TGGGGTAACCGGATATATACCCTCGCGGTGTACCTCCCTGATTCTACCATGGAGATCGGC
          CGAATGAAGCGTCCCCCTTATAGAAACGCGGTGCACATTGATTGATTCCCGATGGCTAGG
          TGGCCAGATCCCGTTGCCTATATCAATGTACATAGCGCCAATCGCTATTTCGGAGCTCGA
          GACCTAAATTGTGTTACCGTTGTAGCCCTCTTACCTGACGATTCCTCTTCCGCTTCCAGA
          CAACAAACCTGTGTGAGAGAGATAGCACCATGCACAACCAGTTAGATCTACGAGGACGGG
          CATAGGGGACATATTGAAAAGGAGAGAGCCAATGGTGTTCGGCGTAGGGACACGGTTAGT
          CATACGAAACATGTTGGAAAGGAGTGCGCTAACGCTGCATTGCGCTGGGACACGGTTCAT

          CTCTACCTATGGAGTCAGACGTTCGGGTTGCACCTGTGCAGATAATGGCGCACGATGATG
          CTTGTCCAACAGAGCTAGACGTTGGGGACGTGATTGTGCAGACAATGGCACGCTATGTAG
          TCGAGTAGACAGAGTCTGACGATAGGGACGTCATGACGGCACGAGAAGTCCAAGATAAAG
          CGTGCCCGAAAGAACAGGGATGGCATGCTCCGCACTCGAACAGCTCAGCTTGAGAAGGAC
          CACAATCGGAAGCACGATGAGGACGTGTTACGCACACCGAAGGGAAGACCTGCGGTGATT
          CTTCGCAGGAGTAAGTGAGGGTTAGTCTCGCGTGGTCGAGTAGACTGGATGACGAGGCAT
          TGTAAGCAGTGCGGTGGAGGCTTCGAATCAAGCATCAAGAATAGCTGACTTGGAACGAAG
          TGTAAGCAAGGCGGCAGGAGCTCCGGATCAAGCCTTAAAAATGGCTTGTTTGGAACGTAT

          AGGGATTCAGGCAAAGATAAAGCTGAGCCGCACCTGTTGCTGCCGTTCGATACGTGCGGC
          AGAGAATGGGACGAAGACAATGGAGGCCTGAACTTATTGCTATGTTTTGTTCCGTGTGGC
          AGGGAATGGAGCTAGGTTTTAATAAAACAGAGTATATGGCCACAGTATGAACGGGCCGGA
          AAGGAGTCGTGCCGGGGGCAAGACTAGCCGAATGTACGGTTACTCTTGGAATGAATCGCG
          AGGGTGTAAGGCTATTAAATATTGCCTATACTAGTGCGGGTAAGGTGTACTATGGCTATA
          AAGAACGCGGGCTACGGTTTACAATCTGTGTAAGTGGGATTACCGCCTACCCGAAATCAG
          GACACACAGTGCTAGAACTGCGAGCTCAAATGGGGGCGGTTATTGACAGTGTGGGCCGTG
          AACATGTAGTGTTAAAGCCACGAGCTCTTACGGGGGAAGTTATTGACGGTTAAGGCCGAG

          TTTACCGGCTGGATCGGGTGATATTCATGTTCAGGTTTGT
          TGAGCAGCCTGGACCGTGTGATCTCCATTTCTAGGTTAGT
          TAAAATAGCGCAAATAAGTCAGGCCCATCTTCAAGCTCGG
          CGCTACCCAGGCAACAAGGGCACGATATCCAGATAAAGCA
          CTCACCTAGACATCGGAGATGGCCTCAAGACATGACATAG
          ACGCATGGGAAACGGAGGGAGCGCTCGTAGTAAAGCTGGA
          TGCAGTTGGCAAGCGAGGGACAGTTAGCTGCGAGAAGGAA
          TGCCGCTGGTAAAGGAGAGAAAGCTCGCTACGAGTAGAAA

