 8 1000
t1        CGCGCCAGATGTGAATAAAAATTACCATGACTCGAGCCCGTAGGAGGCTATCGGACAATC
t2        CGCGCCAGATGCAAATGAAAACTACCATGGACCGAGATCGCAGGGGGCAATCGGACAATC
t3        CGAGACAGCTGCGAATGAAAACTATCATGGACCGAGTTCGCAGGCGGTCATCGGACAGTT
t4        CAGAACATGCACGGACGGACAATTTCGCGGCTAGAACTCGTACCGATACACCTAATGCCT
t5        CGAGCTGGCCGCGCGCGGCCATATTTGCGTCTTGAACTAGATAAAAATGAACGGGTGCGT
t6        TAAGTAAGTCCTATTCGTTGGTATCCGTAACCAGAACTAGTCAGGATTCCGTATGCGCGT
t7        TAGCGACGACGTGGTGGCAAGCCACTGAGCCACAGTAACATCAGGGCCCCCTATATAGCA
t8        CAGGAAATGTCCGATTCCTGTCCCATGCATGGGGGAATCGTTAGAGGGTAATGTGCAGTT

          GCTGGTTCTGCTTTGCTGTACTCCGCCGGTAACCCACGTGGTCAATATTCTGCGGCGATT
          GCTGGTCATGCCTTGCTGTATTCCATAGGTACCCGACGTGGCTTATATTTTGCGGAGATA
          GCTGGTGATGTCTTCCTGTGCTTTACCAGTCACCGACGCTGCCAGTACTTTGCGGAGATT
          GTAAGCGGTTTCATGCCATGCTCCACCGGCTGGTGATGCAAGGGCAGCTTTTTGGCGATA
          GTCTGGGCTCAATTACTACGTTTTTGAGCTCACCGTCACAGTTGGCCGAATTAGAGGTTT
          GGAAGTAGCTGTTTATTGGATGTCTGTGGTTGGTCAGCTACTGAACTCCTCGCCAATTAC
          GTTTGAGATCCTCCGCCCTAATGTTTCAGCGGGCAAGGACGCAAGCCCCAGCCAGGAATC
          TTCTACTAAGTGATACTGACCTGGTCGATATGACGTTAGCCGTGAGGTCGTGGCCCGGCC

          GAGTTGCTCGAGGTCTGTATACCCAACAAGAATTTAGTAGAATAAGGCCGTAGAAGGCAG
          GAGTTGCGCAAAATCTGTATACCCAATAAGAGTTTAGTAGATTAAGGCCTTAGCTGGCAG
          GAGTTGCGAGACCTCTGTACACCCAAAGAGAATTCAGTTGAATATGGTCGTAGATGGCAG
          AGGCTGATGGGAAGGCGCCACCATCCTAAGAATCAAGTAGAGGTCTTACATCGACGCCAA
          CGGCGAAAGAGAGCGTACGTTCGCTTTAGGTATCTGATAGAACTTCCTAGCGGTAGCCTG
          AGGTGGATATACAACCACTGTATCTTGAGAAAGTTCCCAACACCAATCTCCGATAGTTGG
          AAGCTCGCGTGGGGTTATTCGTGAACCTCGAATTCATCATAAATCTCTTTAGGGCGTTAG
          AAACTTAGTCAGGGTCATTCGCAAATTGGAGGATCATCCTGGATGCCCCATAGCGATTGA

          GAACTGAAGGGTCTCACCACGGAAGCGAATAATCACATGCAAGCTGATGTGACTCGGAGG
          GAACTGAGGGGTTTTTCCACAGAAGCGAATCATTCTATGCAAACCGATGAGATACGGAGT
          GACCACGAGTGTCTTTCTACGGAAGTAAATCATTTACTGCAAACTGATGGGACAGGGCGT
          AGAATGGTTGCCACTGTCCTAGTGGCGAGTCCGACAGTGCGGAGGAAACTCACAAAAGGC
          GAGACCGCTGATATCGCTAGAACCAGGGGTCCACCGACGGCGAATATAATTATTCGATGT
          GCGGTGGTGTAAGCCTTCGATGTAGCACGGTTACCTGCGTAGGGGGAAGTCGGATAAGTC
          GATATGGCCCATTCATCTACGAACATATCACTCGTCGGGCGGGTCGGCCCTAGCCCGTAT
          GGTGGCGCCGCCACATCCAAGCTTCAGGTTTTAGTGGTCTTGCCTGAAACCCCAAAAATG

          GCTACTTTGTGAGCCTGTTCTGCGCTGGGGGGCTGAGGTGTGTAGTGTAAACTAGAATAG
          GCTACTTCGTGAACCTGTCCTGTGCTCGGGGGCTAAGGTGAGTCGTGTAGAATAGAAAGG
          GTCGCCTCGTGAATTTGTCCTGTACTAGGGGGCTGCGGCCAGTCGTGTAAAATAGAAAGG
          ATTACTTCACCACCTACCTCACTAGGTAGGCGTCATGATTGACCGTTCATGGCCGATAGC
          GCCTCTTCAGTAGCTGGCCCCTTAGATAGTGGCTCTGCAGGACTGGGTTAAGTCATAAGT
          GCGATATGGTAGGGCTGATCCCCGGACAGAAACCGCGTTTGTCATTACGTACTTCAAAGA
          GCGCCCTTGTCAGGTGACAGAATGGCCAGACGCAGATTGTATCCCCTTGAGACGGACCTC
          GCCTCTCCATTGGGCCGTCCTTTGGATAACGGATATATCCGACCCGCCAGAGTTGAATGC

          GTCACCTGAAAGACACGCCTGCGCGCTGATAGTAAGTCGCGACACGTATTTTGTGCGAGA
          GCCACCCGCACGACACGGCTGTGCGCTGGTAGTAGGTCGCAACATGCATTTTGTACGAGA
          GCCACCCGCAACACACGCCCGTTCGCTGGACGTATGCCGCACAGAATATTTTGCGTGAGA
          GACACTAGGATAAATTATCCCCGTATGAAAGGGGCGTCGTACCTGATATGTTGTACATGC
          GAAAGCAGTAATGATCTTACGCGGGGTTAAGGGAAACCGTCCAAAGAGCATGGCAACTAG
          TAGCCTAGTTCCTTGTGATTCGGGACATTGGACACAGGGTATAGCGGGACCTTGGCATAT
          GCCCCCTGTCTATGTTAGTTATCTTTATAAGGGACGACGCGCTTAACCAATCGTGGGGCA
          TGGAGCTGCACAATTTCGTCAGATTTTCGAAAGGGGCCAGTAGCGGTACTGTGTACTGTT

          TTTCGGTCATAAGCCGGAGTAGGACGCTTCAGAATTTAATAGCACGGCCTCAGTATGATG
          TAACAGTCAGGAGCCGGTATAGGACGCTTCAAAACTCAACTGCATAACCTCAGTATGGTG
          TTTGCGTCAGGAATCGATGTAGGTCGCTTCAAGATCTGACAACTTGGTCCCAGTCTTGTG
          ACGTAATAGAGAACCGGCCTGGTGCGCGATCATTCCTATTAAAACAGCGAAGGATTGTCT
          CCGTATTTGGACGCTGGAGTAGTACGCGTGTGTCTTGGGGAGTTGCGGGAGTTAATGCTG
          CTATAACCGAGGCCAGGCGCATCTCACGACAAACTTTCACAGGAGAAGTTGAAGACGTTG
          CGTGGCTTAGAACTGGATCCGTGCCCGGTGCTCACCCGGCTGGTTATGAAGGCACAGTAA
          TACCAAACTAAGGCAGACATACTTTTCTTCCAGCATTGATGTCAACAGTAGGCATTGGCC

          CGTGCTGTGCGTTCCAAGGAAAAGCTTCGATTCTAGGCAACCAACCACCAGGTATGAACG
          CCTGCTGTGCGTTCCAAGGAGAAGTCCCGATTATAGGTTACCTACCTATGGGCATGAATG
          CCTCCTGCGCGTTCTAAGGAAAGCTTCCGAATTTACGTTATCTCTCGCCAGACAATAACG
          ACCCTGGCTCATAACGTGTAGGGTTCTAGATCAGAGTCCATTTGTTGCCTGGTTAGGAGG
          CGCTCTGTGAATGCTGCAGGGGAAATATCGCTCGGGGAACTTCGCAGTTTTCATCGGATG
          CGTTCGGCGTTTTAAGAGAAGGGATCTGTATCCACGGTTTGACGTACATTGATTGCGCTG
          TGTCCGGTAGAACCAGATGGGGGTTTCGCACATGGTGACCCTTACCTTCTAGGCCTTATA
          TAAAAGCAGTGCCTAGAACGAGGGTCCACAGCATTATCGTAGCATAAGACGGTTCAGACA

          CCCATAGCCGTAAAAAGTATATGCCGCGATGGACTTCTAGCATCAGAAGGTAAGGAGCGA
          GTCATGGCTGTGGTAAGTATTTGCCGCGGTGAGTCTCTGGCGGCAGAAGGGAAGGAGTGA
          GCCGTAGCAGCGACAGGCCAATGCCGCGATGAATCTGTACCATCCGACGGAATGATGCGA
          ATTGCCCCTGTAGCCCCTTCGCCCATCCAGAGTACCCGAATAATCGAACGGAAGTACAGA
          ATCACAACCGTATCTCACCCGTACGACTAGAGGACACTAACACCCCTGAAAAACAGCTAA
          GGCATAACCGTCGATCAGACCAGGGGACCCCGGTCTCTTCCACCCTAGGGACGGTGCTGA
          TAGCTAGTTATACATTGCTGCCGCGTTGGCGGGTACGTTCCAATTAGATGCTAGACCAAT
          AGCGCGCCAGCATCCTGTACGTCTTGGCAAGGGAATCTTACAGCGAAACTTCAAGCTGAA

          GCGGCCTTGTGAGGGACTCTGGTAGTATTAGGCTTTTAGTGCACAGTACACATCACACCG
          GAAGCTTTGTGTGGGAATCTGTTCGTACTAGGATTTTAGTGAAAGGTACACAACACACCG
          ACAGCCTTGTGACGGACTCCGTCAGTACGAGCTCCCTGCTGAATAGCACAAACCACACCG
          CAATTTTCTCGCCCGTTTCCGTCAGCGTGCGCCATTTTGCTTCGTTCGCAGACTGTACGC
          AGGACGTTATGTTGATACTGAGTAGCGGGTTAAGACATGCAGACTGTACTCACCATATTG
          TTGCCCCTACAGTTGATTACAATTACATGTTCTTCATGACTAGCCGCAAACACTAAGCCG
          AGTATTTTTTGAAGAGCCTTGGCCGTTCCTTTCGTTCTATTATTAACATGCACGTCGGCA
          GGACTTTCCTGCACAAAAACACCAGCCTGTGTAAGACACTCATTGTTACGGACCGGCGCG

          CCCAAACGCTGCTCGGAGCACAGCGGTAGGAACATCGGGTATTAATCGCGTGCCGATTAG
          CATAATCGCTGCTCGGACCGCAGCGGTAGGAACGTCGTGTCATAACCGCGTGCAGGTTAG
          CCTATAGGCTGCTCGGAGCGCGACGGTCAGAACATTGGCCCCAAATCGGGCGGAGGTTAG
          CCAATTCCCTAGACGGATCGATCCAACTATACCAGCGGTCTTAACTTGTGTGCGTGCAGG
          TCAACTCATTGGCCGGAGATTGTTCACAGCAATACTGGTCGATTCTTGCCTTCACGAGAA
          GTTTCTCGCCGATAGTAATAATCAGGAATTAGTGTGCGCCTCCAGTCGTGGCTTTGCAGC
          CTACCACGTTAACGGGTACCGCCAAGAGGGAGGACGGGTAGTGGGGTGAGCTCAGCCACT
          CTTTGAAACCGCTAAGAGCGGATGATTCGTAACGGGTCATACTGTCTGGCTTCCTATCAG

          GGGAGCGCCAAACGTACGACGTTACCCTGACGCTAGTCCACTCATTAACAAAAATACTTC
          GGCGGCGCCAAACGTACGACTTTACCCTGACGCTAGTTTACCCATTGGCGAAAATACTTC
          GGACGGGCCGAACGTACGACTTCATCCTGGCACTAGTTTAGCCATTAACGAAAATATATC
          GGCACCAATAAGACTACAACTGTGCTCTATTCCCGCGGTCTCCACTGGGTTGGGTATTCC
          GGCCACACTAGAGGCTTGCGCCTGATTCGAACTGAAGCTGGTCATCACAGTTATAACCCC
          AGAACTCCTAGCTCGTTTACCCTACTCACGTCTTGATCTTTTCACCTACGTGGCAATTTT
          GGAGTTACCTGATGCCCGCCTCTACTAGCGATTGGTGGCACCTATTGGTACAGAGTCTCT
          GGAGGAACCGCACGGTGGGTCCGGATTAGAGCTGGCATATTCCAATAAAAGGACTACCCT

          GTAATTGTCCCCTAGACGAGCCCTCCCCACCCCCTCGCTGGAGCTGGCCCACAGGTCTGG
          GCAACCGCCTCCTAGTTGAACACTATCCACCTCCTTGGTGGCGCTGGCCCACAGGCTTGG
          GTAATCGCCACTTAACTGAACCACATTCACCCCCTTGGTGGAGCTGGCCCACAGGCCTGA
          GTGCTCATCACTGAGCTGGGCCCGGTCTGCTCGCAAAGTGGAGCCCGTCTTTAAGCGTAT
          GTATTGGACACGAAACCAGATTCCGACTGGAGGTGTATTGAAGCAAACATGTTCGACAAG
          CTTTCCGTAAATGAGTTACGTTCACGATGTCTAATCACTGAAACGGATTGATGCTACGGA
          AAACCTGACACCGCCATGATTGGGCAACAATCTCACAGCGGGACTCGCATATGGCTCTCG
          CATGTTGAGAAAATGAGGTGTGTTTAGACCTAACACGTCTGGACGACCTGTCGATTTCCC

          AGCGTTTGAGACTGATTGACTTGATGAACGCCCCGACGACTGCGTTCAGGGACCGCGACG
          CGCGTTTGAGACTGGTCGAGTTGTCCAACGCCTCGAGGCTTGCATTGAGGGACCGCGACG
          CGCGTTCGAGTCTGATCGGGTTGTCGAACACCCCGAGGTTTTTATCGAGGGTGCGCGACG
          CATGCGTGGCTTTACACGGGTGGCCGGGGACCGCGTGACTCATTTTCGGGGTCTAAGAGA
          CATGTATGAGACCGTCCGAATCGCCGAGTATATAGAAGACCGAATCTAGGGGCTGCTAAA
          CATACTTGATCCGGGATGGGCGATTGATCACGAGTCCCTGAGTTCATGAATTACTTGGTA
          TATCCTCACGCGAGCTCGGAATCAAGACCAACGCCCGGGCGGCCTGCAAAGGACACAGTA
          CGTGATTGCCAGCAAGAGGCCCGGAAGCTCTGACTAACCCGACTAGACTAACCCGTAGCA

          GTGCAGTCATTCTTACCTAGCATACCGCGAATATTTGCAGGCCTGGGAGATCATCCACGG
          CTGCAGTCCTTCTTACCTACCATACTGCGAACACACGCAGGCTTGGGAGATAATCCACGG
          CTGCAGGCCTTCTTACGTAGCGTACTACGAATAAATCCAGGCTGAGGAGACAAGTCACGG
          TTCTTGCTATTTTCACTTCCCCTTTCGCGAACGATTCAACGACCGGCGAATATACCAACA
          TAATACTGTTTCGCGTTTTCTGTTCTGTCGTTGACTTCACGCGAAGGTGTCGCATTCGGA
          CTTCAGTCGTGCGAACTCCTGACAGTGCGGATAGCCTGAAGCATAGGAGATACATTTGAG
          TTGCAGTACGAGGATTCTCCCGTTCTGTCTACGACACCACTTTCGGGTGCAGAACTCGGG
          CGTAAAGCCGGTCACGCCTTCTGATCGTGATACGTCCGTCGGCCGGGAGACATGCCGGGC

          CCATCTGTCGCTGGACCAGGACAATGAGAAAAGTGGAATAAGTTATCTCGGCAGGGGCAG
          CCATCTACCGCTGAACCAGGAGATTGCGAAAAAAGGACTAAGCTATCCCGGCAGGGGCAG
          CCATCTACTAGTGGACCGGGAGATAGAGAGAAATGGACCAAACTAGCTCGGCGGGGGCAA
          TGGTCCACTGGTAGCGTATTGAGCAGGCTTGTGCAGACAGAGTTTCTCAGGGGGACGAAC
          ATATGTCTAAGGGACAATTAGTACAAATAGGAATGTATCGAGTGCGCCCGGGGCAAACAA
          CGACCATGATTCTATCGAAAGAGTTGTGGTTGGCGATAGAAGCTGTTCCCGCCAGGGCAC
          CGGCCTTATAACCACGTGCGAGGCGGGGACCCGCCAGTACAGGTTCTTTTGGGTAAAAAC
          TTATTACATGAGTCCAGAGAACGTACAGGTTGAAGACGGGTGTTCCCCTGGGAGGTTTTT

          CTTATATCCGTACCCCTGGTACCCATTATCTTCTCATTTG
          TCCATACCCGTGCCCGTGGTACCCAATACCTTCTTATTCG
          TCCATAATCGTACCCGTGGTACCCATGACCTTCTTATTTG
          CGAGAATTCAAATTTGCCAACATAATTACTTCTAATTTCC
          CCGATAGTCCTGTTCGTCTTCTATGACCTGCCGCTTTTCC
          GTCATGAACGGGCTTGTAGCAGCTGTAATCTTGTCTGTTA
          GGCGTTACAGAAAGAGCAATAGCTGGTCTAGGGGAGTCGG
          ATTCTTGAACAGTCGTTAGCAGCCACACGTTTCTTGTGTA

