 8 1000
t1        ATTTTTCTCCCGTTGTGAACCCATAGGATATGACGGCTGAGAACACAATTTTGCTCAAAG
t2        ATCTGTCTGTCGTTGTAAGCCCATAGGATATGACGACTGAATAAACATCTATGCCTAAAG
t3        GTTCACATTTTACGTTGCGTACGTAGGCAACGGGGATCGGTAGACTACCAGAGTTCAATC
t4        GTTAATTCTCTATGGTAAGCACATAGTTTATGGGGATCGGTGGACTACTGGAGTTCAATT
t5        ATCTCTCCCGACTCATCAGTGACCGGGTAATGCTAACAGTAGGACCTGGCCAGAAGAGAC
t6        ACTTATCCGAATTCACAAGTGCCTGGGTAATGCTAGCCGTAGGACTTGGTCGTTCAAGCC
t7        ATCTACAACCAGTTATGAATGCTTCGGCGATGCAAATAGGAAACCTCGGCAGCCCGCAGC
t8        ATTTATTCCGGGTCAAATGTAATTGGTCGATGTAGAGAGAAGTCCCTGACAGACCACGGG

          TTATGCTACAGTCATTGATTAAGAGTCGACGAACTCCGTAACAACGTTGTCTAGGAAACA
          ATGTGTCGCTACCTCTGATTAAGAAACGACGAGCTCCCCAGAGACGTTGTTTGGGAGGCG
          CGGCGACATCGATGTCTCCTATGATATGAGGATCTCTCACCTAGTACTATTTCCGAGCAC
          CGGCGACATAGACGTCTACCGTGAAAGGAGGATCTCTCAGTTAATCTCGTTAATGGGTTC
          ATGCAGAAGGGCCTATCATATGGATGGGCTACGCAATCGGCCGGTTTTGCTGACATATGA
          ATGCGGTAGGGCCCTTAAAACGCCTAAGACACGCAACCGACAGGATTCGATTGCGTATGA
          GTAAGACTGTGTCCCCAAATGAGATTCGTCGAGCCACCTGTCCGCCTTCGCAGTGTACGG
          GCGTGGCAGAGCTCCCAGATGGGATAGGTGCTGTCATCCGATAGTGTTGGTTGTATATGG

          CGCTAGGGGTTATCCTAGACCCGGTCGCCTGCGGCCCCTATGCAAGTCCCCACACGACGC
          CGACAGGGGCTATCTCAGACCCAGTTGTCTCTGGCACCAACGCAGGTCACTACGTGACGT
          AGCAGGTCCCGGTCTTTAGCAAGAGTCCTTTAATTCCAAGCCACAGCCTCGGTAACATAT
          GGAAGGACGCCGCCTAAAACATGGATCCTTTTGTTTCGAATCACAGCCTTGGTTATTTAC
          CGGGGAGGGGGATTAATGAGCCTGTCCCCTCAAGTTCTCACTGTGAGACCCGTTGTGTTT
          CGACGTAGGGGATCACTTATCCTGCCCACTCGAGCTCCTACCCCGAGACCCGTAGAGATT
          AGTTACAGCCGACCAGTCGCCCCACCCCCTTAAGCTTAAACCACGCAATCGACTGCCACA
          TGACTCGTACCATCTGTCGTGCCTTTCTATTAAGCCCTAGTAACGGGACCGGTAGTCTCA

          AATTTATTTTAAATGTTTCCGTTTGCAAGCATGCTTTGCAGTGGTCAGGCGAGTAATTGT
          AATATATTTAGAATGCTCCTGTTTACGAGTATGCTATGTGGCGTATCGTTATGTAACTGT
          ACTCAAACAGGTACCATTTCGGAAGAAGTCGTTGTTTGTTGTGAGTTATAACGTCATCGG
          ATTCGAACAAGCGTCATTTCGGTAGAGGTTGTTGTTAGTTTCGACTTACAGCGCAATCGG
          GCCTTCTTCCACCCGGCCGCGTACTCGGAGTTTTCCTCTGTTTTCATCTAGCGAAATGAT
          CCTGTTGCCTCCCCGGCCACACACTCGGCGATTTCCTTTGTATTCATCTAGAGTAATCCA
          TCAGCCATAGACTCAATTACGTGTCTACCCATTTTCATCATACAAACTTCGCGTCATCTT
          CTTACTATTGAGCCGTCGACACACACTGGTGTCTCCCTCATATATATCTCTGCACGCCGA

          TGAGGAACAAGATAAATAACGTTGATATAATGTGCTGAGAATAGGTAGCCTTGCTGACAG
          TGAGGAACAACACAGGTAACGTGGATGTAATATGCTGCGAATAGGACGCGTTGAGGACGG
          TGAGGACCAGATAGGGTTGTAATACCGCTTTCGATCGACTAAAGACGATGACTCAGGGGG
          CGATGGTCGGATAGATCCGTGGTGCCACCCTCGACCAACTACAGATGGTCCCTCCGGGGG
          AGTGAGCGTGATTACCCGAATACCCAGTGGCCTACTACATGTAGGAGCCTCCCGCGAGGG
          AGCGAGGGCGATTACCCGGAATCTCCGTGGCTCGCTGCAGGCTAAAACTTTCCGTGAGGG
          GATAATTGTAATTACCCAGACCTTTCATGTTTTGCTATACAGACAATTTGCCCGTGAGGG
          AGCGTGGGCAACTAACCCGAACTTCCGTGCTCGGTCGCACATATGATTTTAATGCGAAGG

          GGGGGTGGTATCTTCCTGTAGGCCAACGGTTCCACCTCTTCACGCGTCGGGGGTGCGGCT
          AAGGGATGCACCGTCCGGAAGGCGGACGGTTCCACCCCTTTCCACATTGGGGGCACTACT
          TGCGGACGTACAACTTTATGGACTTAATACTCCAGCCCGCTACGTGCGAGGGGCCCGAGT
          AGGGTACGTACAACTTAAAGAAACTACTACCCCAACCAGCTACATGTAGGTGGCCTGGGA
          TACAAATAGGTGCTTTCGCGTACGAGGTATAACGATTCAGTCTGCGGTAAGGTCGGACCG
          TAAAACTAGGCGTTATCGCGTGATAGGTACGACAATTCGGCTTGTCGCAACAATGGAGCG
          TATCACTGGGTCTCATTGCACGTTACATCCAATACATCGAATCGGACCAAGCTTGAGGAG
          TAACATTGCGTTTTATTGCGTGTTACATATAACACTTCGGTCCGGGCTAAGACCGATGTG

          GTTACATTGACTTAGATAAGCGTGGGAAGATGACATCGTAACGCTGTGTAAGGTAAAGCC
          GCCGCATTGACTTAGACTAGCACGGGAAAATGGCATCGTAACACTGCATGAGGCAAAGCC
          TTCGTGTAGGCTTCGTTTACTCTAGAGAAGGGGCGCAATCTACATGTACGAAGTAGTGCC
          TTCGAGTAGTTCTTGTCTAAACCAAAGAGGGGATGCTTCGGTAACGTGCAAAGTAGACCC
          CATGCTATAGTACTACAGAGTCTTTGAACAAGATGGATCGACGGTGCCCGTTTCAGGGCA
          CATGCACCGATGGGACCAAGTGTTCGAACAAGTTGAACCTGCGGCCTAAGTATCAATGCA
          GGCATAGTGCCGGCACACGCCTCAAGAACAAGTCGCATCAGCGACGGGCGTATAAGGCAC
          TCTGCTATGCTGGCACACAACTAGTAGACAAGAAGCGTCAGCGACCTCGGTAATAAGCAG

          AGGCCAAGGTCCTCCCGATGAAGTCGCTCGGTCTGTAACTTAGCCTAATGCTCTTGGGGA
          CGGCCAAGGTCTTCCCGACAAAACTACTCAGTCTATTAATTCACCTTGTGCTCTCGGGGG
          GCGCCTCTGTATTTCAGACAGCATACTTTCATCTGAGTGTTAAATACCTTTCCTTGACCA
          CCGCCCCTGCATTCCAGCAAGTACTCTTTCATGCGAATATTAAATAACCCCTCTTGCAGA
          ACGTTTCGATCTTTTGGCCGATCCCAACTGGCCCGCTCGTAAGGTTTGAATAATTCTTAT
          ACCTCCCGATCTAACGGTCGGTTCCACTTGGGCTGCTCATAAGGCTTGAATACTTCTCAT
          GGGTATCTGCGTCCCGGGTGGTTCCGACAGGACTATCTCTACAGCTGGTAAAATTTGCTT
          ACGCCTCTCTGCACTGAGCTATCTTAATCGGGCTATCTCTAAGGATAACCCATTTCGGAT

          GGATAACCCTAGCACGGCGCAGAGGCACAGGATGACGCCATTATGATAATGAGAGTAGCG
          AGCTAACCCTAGCACGGAACAGAGGTAAAAGCTGACGCAATTGTAATAGCGTGATAAGCG
          GGCCTGACCTGTTTCTGTATACTGCCGTAGACGAAAGTATTCGATGTACTTACGACAATA
          GGAATGGCTTAGTTTCCAATACTCCCGTAGACGGGTGTATCAGAACCGCCTACAACAGTA
          TCAGTGTCTCCTATATCCGAGCTGGAATAGTGAGGAGTCTAAGTTCATCATGTCACGTCA
          TAGGTGTCTTCTATGTCTGGATTGAGATAGTGGGAAGTATAAGTCCATCCTTCCACTTTA
          TTTCTGCTGCGTCGGTGGCAGCTGATAGAGTCAATAGGTCAAGCAAGCCTCCCCACGTCA
          TCATCGTCACGCTTACGTGAACTGGACGAGTGGGGAGGCAGAGCAAACTCTCCAACGAAG

          CGAGTCAGTCCAGATCATTGTTCCTTCTTATTACCTTTTAACAAAGCGCCCGGGACTATC
          TGTGCTAGTCATGATTATCGTTCTTTACTACTACTTTTTAACAAAAGCTCTAGGCCAATC
          TGTCTCAGGTGCGTCTAAGTCTACACTGTGCTCAGTCATGCGTATCCACGCAGGCGCCGT
          TGTCCTAGGTGCATTTAGATCTACATTGTGCCTAGTTCTGCCTGCCCATGCTGCCGTTGT
          CGTGATCGTGGTGACGCGGACGGAGCCGCGTAAACTGTGATCTGCACTTTCAGCTGAGCC
          CTCAAACGCGGCAACGCGGACAGAGCAACATAGACTCCGGCTTGTACTTCAAGTTGTTCC
          GGGTAGTGCCACGATACTGATAGGCCTGCGACAACGTCAGGCTATGCTTTCAGCCAAGCC
          GACGATAGTGGAGCCATGGATAATGCGACGTCGGCATCAGTCCGCACTGCAATTGCTGCC

          TTCCTTGACCCGAACAACCGACAGTGATATCCTCGGGAGAATGACCGGCGCTTGAGCGGT
          TTCCCTAATTTTGACAAACGCTGCCGACATCATCAGGAGCCTGATTGGCACTTGGGTCGC
          TGCATCATGGTCAATAAGTGCCGTCAATGATATTTCACTGGCGAGCTCATCAGTGGTGGA
          TGCGTCTAGACTAATAATGGCCGCCGGTGATATTATACGGGCGAACTCCCTGACGGTGGG
          GTGAAGTGCCAGAGTGGGCAGCATTAGCTATTTCGATACTGTGAAATGACCATTGACGAC
          GGAAGAGGTTACAAAAAGAAGCATAAACAATCTCGACACTGTAGAGCGACCAATGATGGC
          ATCATTGATTCCATTGGGAAATGTCAGTGGCCCCACTCGAGATAGATCGTCACAGACGAC
          ACCAGTAACCCGAACATGTTGCACCAGCGGTTCAAACCGAGTGAGATTAATATGGATGAC

          GGTAGCACTGATACCAGGCTTTAGAGTAGGCTGAGCGTATCTTCCACGTTTAGATGTCAT
          GGACGCACTGATTTCAGAATTCAGAGAGGGCTGAGCGTGTTTTGCCCACTTAGACGTCAC
          ACTCGGACAGGCTGCTAAATTTATAGTGGCATGAATCAAGACGGCGGGCTCTTATGTTTT
          TTTCGGCCATGCATTACACATTACAATGAGACAATTCAAGACCAAGGGTTTTTCCATTTA
          CAGTCCAACAGTAACACTAAAACGGGGCACTATGGAGTGCGTAATCTGTTATATCGTCCT
          CGGTCTCGCAGCAACACTCAAACCAGTCACTCTGGAGAACGTGATTTCCATCGTTGCCCC
          CAGTATAGGTATGTTAGTAGTCCGGGTCTGCTGGGTTGACGGAGTTCAAGATGCTCTTCA
          GAGCATGACGGCTTAATTAATCAAGGCGACCTAGGAGGATAGAATTTGATTCTACGTAGG

          TATATATAACGAGGAATCAATCGGTACCTGGGGCAGGATTCAACAGAGCGGTCAGAACGC
          CTTAAGTAACGAGGAATCAGGCGGGTCCTGCGGTGCCGCTTAACAGAGCGGTCAAACTGC
          CATGCGATAGTCGGAATTGGCCAACTAATAAGCCGGGGTTCCGAAATCCGCCGGACCAAC
          GATGTAATACTAAGAAATAGCTAAGCAGTAAGGCGGAGTCCTGAAATCAATCGGATTATC
          ATTGAGCCCGTTAGTAAAAGCCTAGTCCCGGGGCGGGGAGCCGATCATATTTAAGGTGGC
          GTCGAACAAGATGGCAAAGGCCTCACCCAGGGGTGAGGACCGACATATTCCCAGAGGAGC
          CGCGTGCTACACAGCAGCGGCCCATCTTAAAGGTGCTGGGTTATCTGCACCCAGATCGGC
          CACGACCTAGATAGGGGCAGACGGTTTTTAAGACGCGGAGCCATCCAAACCCCGAGTAGC

          ACTGTTAGAGCGTAACCGAAATAGCTGTAGCCGCTACAAACCCACATCTCGTTCCCGCAG
          TTTATCAGAAAGTAACCGGAATAGTCGTCGAGGCAACCTGCCCACATCTTGATTCCGGAG
          TTTCATGGTAGACATAAGAATTAGCCACTCACCTCATAGATGTAGACATCGGTTCCTCAG
          CCTGAAAGAAGACGCACGAACTAGGCGTTCGTGTCTCAGGTACGGGTATCGGCACCTAAG
          CTCGGACTACTGGCTGACCACTACTGTTCCCCTCTATTGCAACTTCCAGCAACGCCCTAA
          CGCGATGTACTGGCCGATAGTTATTTTTTGTCCTTGTTGATTCTTCAATCAACACCACGA
          GATCCCATACTGACTATCAATTATTCGCGACCTTGGCTAACACTGCACTTAATACCCCGG
          AACGGCCTATTTGCCGGTTGTTATCTATGACTTTCATCGACTCCGCCATAGATAACCCGG

          CACAAACCGAGGGTATCCCACGCGAAACCTGCATTATTCCTCCTTTGCTGGATGGCGTCA
          CACCGATTTAGGGTGTTCTATCGGAAACTCTCATTATCTCTCCACTGTTAGACGAGGTGA
          GCCCATATGCTCACTAATACAAGGGGGCCTCAAGTCTCCCCTACTCTCTTACCGCAGTAA
          GCTTACATGCCTATCTTTCCAAGGAAGTCTCAAGGCTTCCCTAACTTTAGGCCGCCGTCA
          CCCGAGTAGAGTATCCCACACGGCTGGCAATCGCTCCACTATTATCGACCGTCTCGGTAA
          CCTGAGTTAGGTGTCCCGTACGGGTGGCAACCGACGCACTATTATTCACGGATTCAGTGG
          CCTATGATGAATACCGCATACTAGCAATACACGTGGAACTTTAGCGACCGGTTTTGACTT
          CCAACCGTGCCTACCGCACACAAGCAATTTACGGGGAGCCCCAGCGTACAGTCCTGACAT

          GTAGTAAGGCCATAAGTCGGAACCACCGCGGTTAACCAAATGGCTGCCTCTTACTTCCCT
          GCCGTTGGGCCATGAGTCGGAACCACCAAGGCTAATCATGAGGCCGCCTCCTATCTTCCA
          CTCGTACTGTGTTAGAGTGGGTCTCGCCTGGATCACCATACGACCGTTTTGAAGGACTCC
          ATTGTGCGCCGTCTGCGTGGGACACGCCTGGACCACCATTTGACTGATTTGCACGACCCA
          TTCCAGCGCGATCAGAAATGAGTTTCAGCAGGTCGCAATCCAGTCTACTTGGATCGCTAT
          ATCCGGCGCGATCACAAATTAGTTCTAACTGGGGGCCATCCCTCCTACCCGAACCGTAAC
          CTTAACCGCGTTCAAACACCATAGACAGCGGGACGGAATGCGGTCAACTGGGATAGAACT
          CTCAGGCGCGATTAAAGAACAATTGAGGTCGACAGAAATGCGATCCACTGGCGAAGCACA

          GCTATGAGGCTCGAAGGATTCTTAATGCCCTCATCTCGGT
          CCCACGATGCTGGTCGTATTGTGAATGCTTACACCACAGT
          GTATTAGGGTCTCACTCCCTGTCCATGGTCCATACATCTG
          GTCCTAGGGCCTGATTCCCAGTCAATGGTCCTGCTACACG
          TTCGCCGGCCCTGGTCTATGTTGCGTGTGACTCGACGATC
          GCCGCCGGCCCAACCCTGTGTCTCAAGTGGCCCAACAATG
          TGTGTCGGCCCGTTTTAATAGTCTACGAGCCTCGATCTTG
          CTAGCCGGTCGGATTCCACACTCTATGAGCATCGAGTTTG

