 8 1000
t1        TTTTACCGCACGTTGAGACTCAACGTCTAGCAGTGAATGAGGATGTGTGGGGTTAAATGT
t2        TTTCACCGCACGTTGAGACTCAACGTCTAGCAGAGAATGAGGATGTGAGGGGTTAAATGT
t3        CTATGCAGCGTGTTTTGAACCAACGCCTAACAGGGGTAGAGGATTTGTGGGACACGACGC
t4        TTTTATCATTAGCAATAATGCAATATTTCATAGAGGGTGAGGACGCGTTGGATTGCTTGT
t5        ACCTCTTGTGCATTATGGGATATTGCTTGGTTAGCTGTGTAGTAGGCTGGGACAGACAGG
t6        CCGTGTTGTAAATTGCGTGAGAAACACTGGCTACACATCCGTGGGTGTCGAGTCGCTCGC
t7        GGCCGATAAATGTCTTCCTATTATGATCCGCAAAGGCCGAATATTGTCCTGGCCAGCATT
t8        TCTTTGTAATCACCGGACGGCGTTATTTACATAAATGCAGGTCGAGGCCGGGCTATAAGC

          CCATCCCCAATCGAACTGTCGAGGTCCCTACACATAAAGAGTGACGTGTCCTATTGCACA
          CCATCCCCAATCGAACTGCCGAGGTCCCTACACATAGAGAGCGACGTGTCCTAATGCACA
          CCATCCCCGACCGCAGCGTTGAAGCCCTTACATATCAAGAGCGGCGTGTCCTAATGCACA
          ACGTTCGCAACCTCGCCGTTGAGCTCTCGACATATGGTGTGCGACGTCTTCTACTCCGTA
          GTAATCGACCACCTACCGTTGCGACTCAGCCACCAAGCATGTGCTGCACTGTACCGTACA
          CCCACGATTCCCTCGTCGTGTGGAACCAGGCGCGCACAGAATCGCCAACCTTGCCATAGG
          CCCCTTATAAACATGCGTTCGGACCCTGGATCACCGGTGCGAAGCCTGTAATGCTGGAAC
          TTCCTATCTGGCTAGCTATCGGGGACCAGCTAGGCAAAGTCAGGATTAGATTGTTGAGCA

          GTGCCTGACGGAGCGCTAGGAACCGAGTTTTTTCGTGTGCCACGAGACGGAGTATTCCGG
          GTGCCTGACGGAGCGCTAGGAACTGAGTTTTTTCGTGTGCCACGAGACGGAGTATTACGG
          GTGTCTGCAGGAGCGGTAGGTCCTGAGGTTTTCAATGGGCCGTAAAATGAAATGCTCGGG
          ACGGCTTTTGTAACGCCGGGGTCGGTACCAAGGGGCTGGTCACTTAGAGGGTTACTCTGA
          GAAATTTTTGTGTTGATTGGGACAGGGCCATCGGATTGACCGCCGTACAAAAAGCTCCTC
          ACGCTAGCTTGCACTACGAGGTCAGATACCCCGAAACGACGATCAAATTTGATAGCACGA
          TGTACCATCCGGTTCCCTATATGGGAGATCTCAAGCTGGTCAGATGCAGGAACCATCTGC
          TGGAACATTAAAGCAACAGAACGAGTAGAGCTTAGCCAGATGCCTAAAGACATAGTTCGC

          ACCGCATTGCCGCTCAGGTCCGCATTCGGCAGAAGGAAATTGCTGCTATAAGCCCGTGCT
          ACCGCATTGCCGCTCAGGTCCGCATTCGGCAGAAGGAAATTGTTGCTATAAGCCCGTGCT
          GTTGTATTTCCGCTCAAGTCTACGATCCAGAGAAGCATATTTTTGCCAGTAGTTCGTGTT
          ACCGAGCTGCCGCTCCGACCCACCATAAGACGAGGCCAACTTCTCCCATCAGTTAACACC
          AAACTGTAGCAGTTCAAGTTTTGAATGGACTATAGGCTGTATTTTCTAGTTGCAAACGCA
          GGCGGACAGCTCCTTGGAACTCAGGCTTTACGTGCGCTAATACTACCCCCAGCTATACAT
          GGGAACTCGCTGCTCAGTTCCTTTCACACCCGTCAGCCACCTATGCGCACCACAGATATC
          GAACAATCCCCTCACGGATTCTGATTGCCCTTCTTGACCGATCTATTCACCGTGAGTGAT

          GATCAACCATGTCTATGTGAGTCTGTTGTCCGTGTAGTTTGGCGGTTAGACAGAGTCAAG
          GATCAACCATGTCTATGTGAGTCTGTTGTCCGTGTAGTTTGGCGGCTAGACAGAGTCAAG
          GATCAACTATACCTTTGCAAGTCCGATACCCATGTAGTCTGGCGGTTAGAAAGAGTCAAG
          TTCCAGCCATGTCAGTGAGTGGTCCTTACCCGTAGAGACCGGCAATTATACAAGCTCCAC
          GATCAAAGCCGTCGGGTCTGAACTGCCTTACAGAAAGTGGTACCAGTAGATTAGGTTGAA
          GGCTTGTGACACTTCTAATAGTCTATGATGCCTGTGGCCGTTGGATTAGATCGAGTCGAC
          CAATAACTGTCTACACCTTAGTTTAACGAGTACACGAACCAACTCTCACATCTGGCTGAG
          AATGAGGAATATACCCTGTGCCATGTGGTCTGTGTATTCAAGTATTTAGTTAAGGATGGC

          TCTGAGACAGCATCTTCGTGGGTTTTGTACAGATACATGGATAAACTCGTTGCCGGAAAT
          ACTGAGACAGCCTCCTCGTGGGTTTTGTACAGATACATGGATAAACTCGTTGCCGGAAAT
          TCCGACACAGTCTCTATATGGGGCTCGAATAGATACATGGGTGAGGTCATAATCCCATCT
          CTCTGCGCGATCCCCATAGGAGGTTGCCGCGGAAGTAGCGGAGCTTACTAAATTGGAGGT
          TGAAACATAGGCACTACAAAGGACTGTGACGAGTGTCGGGGAAAGTGTTACACGCGGGTG
          ATCCACAAGATCAACGCACATGGCCTCACTAAGAAAAGTGAAGAATCCGGAATACCAGGT
          ACGTCAACGCGCCATATATAGGATACCGAGTAAGCAAACGCTAGGTCGCTAACACCGCAA
          ACATATTAACACAACGGGGTAAACGACATAGAGGGGACGGCCCGACCTGTGATGCGGTGA

          GGTACATCGGTTATCTATCGTGGACTCGACACTCTATGCTACTGTCACTCCGGGCCGTTC
          GGTACATCGATTATCTATCGTGGACTCGACACTCTATGCTACTGTCACTCCGGGCCAATC
          GGCACACCGGTCTTCTGTCGAGAACTCGACTCGCTATATCACCGTCTTTGCGAACTTAGC
          TTCCCACCGATTCATTGTCGGCAACGCGGAACGTCATACTGAGGTCAACACGAGTTTCCC
          TGGCCATTGGCTCTTAGCCGGGTACACAACCCGTGATAAATCGGTCTTTACAAGACGGCC
          CGCCCTCTGGCTTCGTGGGACGAGTTGTCGTTAAACTACATGAATGAGCACGAGTTTGCG
          TAACAGCCTAAGGTGTAACGGATCTTGTCCCCTAGTTATCAGGATAGAGGTAAACTAAGA
          TGCTCGTCGGACCTCTAAGAGGAACACTCCCTCCAATGTTCGGTCGGGCTTGAAGTTGGA

          TGGACTTGCCAGTCATATATGGCTATGCGATAAAAAGCTGAACGTATCTATTGCCACCAA
          TGGATTTGCCAGCCACATACGGTTATGCGATAAAAAGCTGAACGTATCTATTGCCACCAA
          TCAACTGGCTAGTCATCTGAAGTTACACCATATAAAGCTGGACATGTCTGTTATAACCTA
          TCGAAAATTTCTAAACGCACGATTCTCCAGTATAAAGCCGGATCCGGCAGTGAACGTTTG
          TGGATGCGTCGCGACTGTAGGCCTAGCTCTCGGTTAGATGGACGTCTTAGCGATTCCATC
          CTACCCTGGTCAAGATTTGAAATTGCAATAACAAAGGCCTAATTTTCTGACAGTGGGACC
          AGAAACTGTTTGAGGGACATTATTCTCTCATAGCGAACTCTCAACGCCAATAAACAGATC
          TAACGTAGTTCATAAATAATAGTTATAACCCCCAGATATCTTTGTCCCACCGGTCAGCGC

          TGGTGATTGTGGTAGGATCAATGGGTGAGTTGATCCCCATATAGCATCACCGTTAGTAGC
          TGGTGATTGTGATAGGACCAATGGGTGAGTTGATCCCCATATAGCATCACCGTTAGTAGC
          TGGTGATGGTGACGGGGTCAACGGTTGACTTGATCACCATATAGCGTCACCGCCAGCGGT
          TGGTGACGGTTTTGGGGCCGCTAGTGACGGTGTACCCAACATGGGTCTGCCATAAGAACT
          CGGCGGCTGTGATGAGCCTAGTAAACAGGCAGGGTTTTACCAGGGCTTGGCATCCGTGGA
          TGGGGCAGGTCGTGGCGTAGGACGAAACACTAAGGGTCCCATCGATCTGGCTTTTGAGGC
          ACCTGGAAACGTCTAGGTCAACATCTGATGGGTGATGTGTAGTGCTCCGACTTTCCGATT
          CAGAATTGACACTCAAGGCAAAGCCTAAAAAGAATATTTTCGCAGCTACTTTAGCAAGTC

          CCAGCATATGGCTCCCCGTGATCAGCTGGCTTCGTTTTGCAGCCTTCGGTAGTCAACTCT
          CGAGCACATGGCTCCCCGTGATAAGCTAGCTCCATTTTGCAGTCTTCGGTAGTCAACTTT
          CTAATATATAAGACCAAGTGATCATATGATTACATCTGGTAGCCCTTGATTGGCCAGTTT
          ATTGTATGAGGGGCAGGATGGTTCGCAGACGGAAATTAGCGGCCTCCACTTACAGAGTTC
          TAACTATGCTCGGCTAGACGGGATGCCGACTCACCTCGTTGGATACCGCTTGATAGAATC
          TCACCCTGTGATATTACTGGATCTGATAGCTAAATTTGCTTTTTCTCGCTCGTTACATCA
          TCTACATGTGGCACCCAGAGATTCACAGGCTGTGTTGGCCCGCTGCCGCCCATCGCATCT
          ACCCCGAGCAGGCAGCAGCTATTTGTTGCTCAGGCCCGTAGGCCCAAGTTCGCTGAGGTC

          TTCAGACCTGCACCGGCACATTTACGCCGATTAACACGCCGTAGACTTTACTCGCACGGA
          TTCAGACCTGCACCGGCACATTTACGCCGATTAACATGCCGTAGACTTTACTCGTACGGA
          TCTAGACTAATGCCGGCACATTTGCGCAGATTAACCCGATATATACTTTGCTCCCGGGGA
          TACTAACATACGTTGCCTTATCTGTCTAAATAGCGAGAGAAGGCATGCCCTTCCATCAGG
          CGCGAAGTTTAGTCGGCGCACTTGACGAGGCGACAAGAGCCCACGATCGTCCAGCTTCGA
          TGCGAAACGTGACCAGTGCATATGATGCAGAGTCTGAGTTACTTGCTTGTCACGATAGCC
          CGTAGTTCCTGTCTATAACATACGACCAGGTCTCCGCTCCGAGTGCTTGATTTGAACAGA
          AACGTATTTTAAGTGAATCGTCAGGCTATGAGATTGTGCTTTAAGGTTCCTTCCGACGGA

          GGAGATTGGTTGCCTAAGATAGGCAATGATCACACACCGCCAGCGTCCTAGAAACGGGCA
          GGAGATTGGTTGCCTAAGATAAGCAATGATCACACACCGCCAACGTCCTAGAAACGGGCA
          TGATGTTGGTTGCCTGAGATAGGTACTGATACAACACCACCAGCGTTCCAGACCCGAGTA
          GGGCACAGGTTGTCATCGTTAAGTGCCAACCACGTATTATCGGTGCTGTCAGAACTAGCT
          CCGGGCGGGTCAATTGAAATACGTCACGCCACAACGCGACGGTAGTCCTGGTAACGAGTA
          AGGTTCGCGTCACCTGCAATTGGAGGTGATTCTGTACGGAGCAAGCATTTGTGTCGAGTA
          ATAACCCGCAAGCAAGGGAGCGGGTCCTAAGTCACGTTACAAACGCCGCAGTTCCGAGCC
          TGAACCATGCAAACTCAAGCGTTAATCGAAAGCTTGCTGTGGGCGGGATGAAGAAATGTG

          TTTCGCGCTCCGCGTCAGCCGCTCGAATTTGGTGGCATCCCATTCTATTAACCAAGCGCA
          TTTCGCGCTCCGCGTCAGCCGCTCGAATTTGGTGGCATCCCATTCTTTTGATCAAGCGCA
          TGTCCCGCTGCGGACTAGTCGCTGGAATTTGGTGGTGTTACACTCTATTAACTAAGCACA
          CCTCCACTCGCGTATACGCGTGACCTCTTTGCCAGTGCCATATCCCAGTGTGCAAACAGA
          CTCTGCTCCTTAGATTCAACTAAATGTTGCGCCGACCTCACGTCTTTTTAAATACTCACA
          ATCCGGCCTCCCATATAGTAGTCGGTATACGCTGATACTACCCTCAACCCCAGCGGCGAC
          CAGTACCCCGGACGCTCATTTGATCTCTATGTAACCCGCACTTTTCGACCGATGGGTAGA
          TGCCATACACTTGACTCATACAGTAAGGCTCTATACACGGTAATGCAGCTCTCATGGTTA

          GCCAGAGCGGGTGCGCCTGCTGCTCAGGTAGATTGTCCACGAATTGCTGGTAAGACATTA
          GCCAGAGCGGGTGCGCCTGCTGCTCAGGTAGATTGTCTACGAATTACTGGTAAGACATTA
          GTCAAAGCGGGCACACCTGGAGCCTAGGTTCATTGTCTACGAATTGTCAGCAAGTCATTA
          GTCAGAGCGGTTATGCAAATAGACTAAAGAGATTTCACCCAAGTAAATCGTGAGAGGTAA
          GAAGTACTAATCGTGCCAGAAAATCCAGGTGTCTGTATATGATTCGGCAGTAGTACTCAA
          ATCTTAGCTGGCGTGCTACGAGATCACGGATATGGCGGTCGCGCAATACATGAGCCATTC
          GCCCGAACGTTGCTACGCTGGCACCAGGGCGGACGAACGCACATTGCCATCAAATCGTTG
          ATTTTAGCGGTTGCGCCGTGAGGTCAGGTAGATGGCATTAAGCCCGAACATACCCTAAGC

          ATGCACACCGTAGGGGCGCCACGCCCCTCAGAGCCGGTATGGTGCGCTGATCTGCAAATG
          ATGCACACCGTAGAGGCGCCACGCCCCTCAGAGCCGGTATGGTCCGCTGATCTACAAATG
          ATGTACTCCCTGGGGGCGCCAGGTCCGCCAGAGACGGTCTGACGCGCTGAGTAACAATTG
          ATGGTTCTTGAAGGGAGATTGCGCCCGTAACAGACGGTACGGGTCGTGGTATAATCAGCA
          GTGGACCCTAATGGGGTATGCAGGTTGAATACGGGGGCGCGACTCACACTATGATGGTCA
          AGGGATACTAAGGAAGTGCCAATCCTGGAAAAGCCGCCAAAGCTTTTAGCAGGGTGGCCC
          ATATACCGTGTATAGAGGTAAACTTCGCGTTGGGTGTTGTACACCACCGAAGGGTTGTAC
          ATTGTTTACGACTGCCGACCCGCATTGCGATTACCGCCAGATCACGTGGGTACATCTGCT

          GCGTTTCACAAAACCCCTTCAAAAACGGCTATTGTCATCACAGACTGTACCTGAAAGTCG
          GCGTTTCACAAAACCCCTTCAAAAACGGCTATTGTCATCACAGACTGTACCTGAGAGTCG
          CTGTTTCACAAAACCCCCTCATAAATGGCTATTGTCATCACAGATGGCACCTGGGAGCAG
          GCGCGACTTATACCTCTTGCGCAGGAAGTGATCGTGGCCGCAGAATGTATTTCCAAATCA
          AGACTGCGCTGGAACCCCCGAGCAGGTATGAGAGCCACTATCGAGCCTGATAGGGATTCA
          TCACTGTAAGTCACCGTCTGGAGACTAACGGCCACTGCTATGAACTAAGTCTGGATTTTG
          ACGTCACCGCCAACATCTTGGATATACACGACATTCATCATAGGTTAGGCATAGGCTTCT
          CTTTTGAGAACGTGCTTGTAGCCTGCTAAGGCATCCGCATCCACTGCGGACTGATCTTCT

          TTGTCTGACAGATAAAGCCTCAGATCCGGGCGACACACGT
          TTGTCTGACAGATAAAGCCTCAGATCTGGGCGACACACGT
          TCGTATGGGAGGCCAAGACTCAAATTTGGGTGAGATATGT
          CTTTTCACCACGGCAACCCTTAGGTTCGGGTGGGTGCAAA
          TTACCGATGCTGGTCATATTAAGGACATAGTCGTCAATGG
          GCCCACGCTGAGGCCACTCTCTATCTTCGACAGATAATGA
          TCACCCACCAGCGCCCTTACTAAGTGCAGCTGGGTGGCAA
          TCGATTAATGTAAGTATACTTACGACTCGACCGAGTGCGA

