 8 1000
t1        CTCGTAAACTGCGGTGTAATTGATCAGCCGTAGGAATCGGGGTATCTGCGATCCGGGTCG
t2        GTGGCAAACTGCGGTGTAATTGATAACCCGTACCAATCGGCGTATCTGCGACTTGGGTCG
t3        GTAGGCTACTGAGGTATCGCCATCGGCGGGTCGGAATTGGGGTATTTCCTATTCTCCAGA
t4        AAGATTAGGCGAGAGTGTATTGCACGTAGGGAATCAGTGGTGTCTTAGTTATCTGCGACG
t5        GCCGTCGCTCTGTGCGCGGGTGACTATGTGCACTGTATCTGGTTCTCGGTAGTCGGCAGG
t6        GAAACGTCCCGCGCTGTGATTGTTTATAATCTGCGAGGCAGGTGCAAGTTAAACGCCATG
t7        GGGGTTTTTGGAAGCACCACCGTATACGAGTCTGTTACTTATTGTTATCGAAATTCAGCT
t8        GCAGCTTTCTGAAATATAGCTGTTCACGAGTGCGTCCCCAGCGATAAACTAATGTCCATA

          TCGGTATCCTTGACTTCGCAGTCGTGTGGGTGAGTTGACTTCGAAAGATAAATGCTTCTT
          TCGGTATCATTGACTTCGCAGTCATGTGGGCGTGTTGACTTCGAAAGATAAATGCTTCTC
          TCACTATCCCGAATTTCCCAGTCATATGTCTTTCTAGTCTATGTGGGGTAAGACCCCTTC
          TTGCTGTCTTAGAGTTTTAATTCACAGGCCTGCTCAGGCAACGTAGGGCACGGTGCTCTC
          CTAACACTTACTATTTGCATTTACTCAGCAGGTGTTGACGATTTGGCGTCGGATCCTCTC
          TCGGTATCAGGCAATTATATTGAGCGGTACCGACTAGGAGATGTTGCACAGGCCTCCCCC
          CCGTCATTGTGGCGCGGCTGGTAATGAGCGGGGTGAACCGGAGCGCATTCTAGTCGGTCC
          CTGGCGTTTTAGAGCGAGCCATTTTGTTTGGTCCTAGCTGGGGCAGGTTTCCGTTTCCGA

          GCTTGGATTCGTTTCGGGCCTGCGTAGCTGTCTGATTCAATTGTCCCATTAGCGAGTAGG
          GCTTGGATGCGTTTCGGGTCTGCATAGCTGTCTGATCCAATCGCCCCATTAGCGAGTAGG
          ACCCGACAGGGCTTCGGGCCCACATAGTTGGCAGATTCGACCGTCCAACCAGGACCTAGA
          CCTTGGAGCAGTCCCGAATACGCTAATCTGTAGAATTAGATAGTATGAAAAGGGCATAGC
          GTTTATGAGCGCGCCGTGCCCCATGCTTTCTTACTTTGTCCAGCCTGAACCGAGTTAAAA
          GGGTAGGCGCACGTCGAATCACGTTGACTGTAGGCAAGTATCTGCTCAATAGGGCTCAAC
          GTTTCGAATTGCCTTACACTTTTTGTAAAGGCCTCACGTGCATAATCGCTTGAATAGTCC
          TCCTTAGACCACTCTATACCTTTTGCAGTGCTTCACGGTATAGCACCACCCGGTCCAACG

          CTTAGTTAATAGAAGAACAGCGACAATGGACGCAGCGATATGATAATGACTGCTTTTCAA
          CTTTGTTAATAGAAGAAGAGCCACAATGGACGCAGCGAGGTGATAATGACTACCTTTCGA
          TGAGGCTATAACACGACCACCGACAGTAGCCGCGGTGGTAGGCTAGTTAGCGGTTTCAGA
          ATTTGTTACAATTCCAAGACCGATCACACGAGCTGGGTCACGTTTGTTGAAGCCTCTCGA
          ACGCTAGTCCCTCCCACCTATGTAGTCGACCCTGCAGTTTTAACCGTCAGCCGTTCCGCT
          ATCAGTATAATACCTGCCTATTCAGACAGCCTCCTCAGTCTGGAAACTAGACGTGTTTCA
          TTCAAGTGAAAACCAATGCTCGAGGGAAGCCGTAATGTAACCCACAAGGAGGGTCGTGAC
          ATAGTATGTACCCCTACCAATGAACGAAGTCGCGCTATTATTACCACTAATGGTAGATAA

          ATTCTAGTATCATTCTGCAAGTGCGCTCGGTCTCTTGTAGAAATCCCCGACATTATAAAG
          ATTCTAGTATCATTCTGCAAGTGCGCTTGGTCTCCTGTGTAAACCCCCAACATTCTAAAG
          AGTCTAGGATAACTATATACATAAGCGCGGCCCTTTGAGGACACACTCATCTCTGAAAGG
          CTGGTCGTATGAGCACCTAGGTGAATCTCGTATTTAACGGACACCCTTGGTGCGGTTACG
          AAGTTAGAGTAATCATGTTGACACGATTTGCTATTTTGAGATTAACTAGGTAATGCGTCT
          AGGGTAACATAGCTATCCACGGGCGTCTCTCCTTACGGAGATACGCTCTACAAGACGCCG
          TGTCCTCATTTACAGTACGCGTTTGATGAAATTAAAGAGGTTACGTTGTGCAGTCTTAAG
          CGTCTTCCGCTTCCACGTTCGGCTACCGTAAACAATGCGAAAACATTACTTAGTATGAGT

          CGGCACATGAAATTCGGTCGTATCGCGTCCTCTGATAGCCATCCCGTGCAGCCGGTCGCG
          CGGCACAAGAAATTCGGCCGTATCGCGTCCTCTGATAGCCATCCCGTGCAGCCGGTCACG
          CGACATTAGGAACCCGACCGTAGTGAGGTCTCCGATAGCTACGTCTCGTCCCTGGTTGCG
          TGATACAGGCCTTCTATACGTAACGCGCGTTCCCCACGCCGTTTGTCGCTCTGAGCAGAT
          TGCAACTAACACTTCATTAGTAGAGTCTGTTTCGCAAAGTGGTGCCCGTCCCAAGCAGAG
          CGGGGAAAACGCTTCCCTCGCAATACATGTTCCGGCGGACGGCTATCACCTTCGGACGGA
          TGCCATAACTAATCGGGAGGTTACGGCTAAATTGATAGGTGCCGTCCGCCAGTGCATACC
          TGTGACAAATTCCCGGATAAGATCAAGAAATATGACAGAAGCCGATCTTTAGTGAAACAC

          GACATACTACGCTTTTTTTTTGACTGCGTCTACGACACATAAGCCGCGTCAGACCGGACG
          GACTCTCTACGTCTTTTTTTTGATTGCGTCCCTAACACATAAGCCGCGTCAGATCGGACG
          GCCTTTTTAAGCTCTGCTTCTGACCAAGGTTCAGTCACGGACTCCGTCTTTGATGGGTCG
          GCTACCCCTTTCAGCATACCCGCTAGCATCCTAAGCCCGGGTTTCTCGCTAGTCTAGTCG
          AATAGTATCGATAGCATTGCGGGCTTCGACCCATGATTAATCACCTGACTGGAGTGGATG
          GCCGTTTGAAATACCCTCGCTGTTCGCTACCTGACGTCGACCCCCTCGCTAGGGGCGCCT
          GTCACGTGAGCCCCAACTGGCATCTTGAGAACAGGTTCGGACGCAACATTAACACGCTCG
          GCTGTCTGGACTGATACTGCCACATCTTGGTGGGGTTCGGACTCATAACCAGACTGCATG

          GCTTTGTCCATTAAGACTGACACCGGTTCGTCTGAGCACGATTATGTACCCTCTCGCCAG
          GCTTTATCCATCAAGACTGACACCGGTTTGTCTGAACACGATTATGTACCCTTTCGCTAG
          GCATCGTACATGAAAATCCGTACCGACGCGCCCGAGTGCGCTTACGTATCTTTGCGCTTG
          GCTATACGTATCGAAATAGGAGCTCAGGCATAATAGACCGAGAATGTGTCATTTTGCATG
          GCACCAAAATCCGCAGTAGAATATTGAGCATATTGTAATGATGAAATCACTTCCCTGCAA
          ACTATATGAGCCGATATAGATCATTGGCCACCTCGCAAGGACGATGTCCTTCCGTCTTGG
          CTTCCATGCTGAGACATGAACGACAAAAGAATTGAACACGACGAACCGTCACACTCTTCA
          TTTCTACGATGCGAAATGGCAATCTAAGCGTTCAAACGCGACATCGTATTCCTCTAAAAC

          TGTCATCGTAACACGAGCCAACAATCCGCGTTGCATATCGGCTAAGAGACTTGTGCGGAT
          TGCCGTTGTAACACGTGCCAGCAATCTGCGCTGCATCTCGGCCGATAGACTTGCGCGGAT
          GACCATTGCGATACGTGATAGTCACTTGTACTATTAGCCGCCAGAAAGGCTTGTGCGAAC
          CACGACTGTACAGGGCCACGGTAAGTTGCTCTATTACTCGGCCAGGCAACCCGCGAACGC
          TAATTTTGTCAGGCGGGATAGCACTCCGTCGTTGGTCTTGACCCCGAAAGCCATGCGCGC
          AATAATCATCGGATGCAGCCATTGGCCGCTACATCAACGGGTACCGAGGCCTGTCAGAGT
          GACTGCCGCCAGATGCCGCCACTGCCAATTTAGACACGAATAAATGCGAACTGCAAAGGG
          AGCTGCTGCTAAGTCTCTTAACTGCGTCGCCGCGCTCGAACCCCCGTGTATGGCAAGGCA

          TCATGAGATCCTTGAGCGGGCGTGCCTTGCCACCGACAGTTGCGTATGCTCGAGAGGAAA
          TCATGAGATACTAGAGCGGGCGTGCCTTGCTTTCGATAGTTGCGTATGCTCAAGAGGAAC
          ATAACCGGGCCTAACACGGGCATACTCTTCTTATGAGGTCTCTGCGCCTTCAACAATCAA
          TCGTGGTGGTGTCAAGTGGGTTTACTTCTTCGATGCAATTTGCATGCCGACGAATCTCGC
          CTACTGGTGCTTGGAAGGGACCCGGGTTTTTTATGGAACTTGTGTGTTAACCAGCCGCAA
          CGGCTGGTAATTGGAGGAGAGTTTGGTCTCAGTCGAGATCCCCGGGCCCTCGGGATACAA
          TGTGGGATTACCGAACTATGCTAATGCTCCAAACGCAGTTTTCGCCTCTCGCCGTCTCAT
          CTAGTGCCTACTGAGATTTACCCACGTTTCGAGAGTAATCCCTGAGTCTTTGCGCTCTGT

          CAAACAGACTAAAACGTAAGACTACTTGACAGTGCACTAAAATGATTGTGGTAGTGTTCA
          CAAACACACTGATACGTAAGACTACTGGACAGGGCATTAAAAAGATTGTAGTAGTATTCT
          CGAAGGACCTCCACGCTCATGTCATTGGACCGGACACTAGAAAAATCGTGGCGGTGTTTT
          CAGCCAAACCAACACCCAAGGTGCCCGTTTTGGACTTTCAACTAACAGCGGCGATGTATT
          CCAACAGCGATGCGGGCAAGGCCTTGGGTTCAAATAACCAACGAAGAGCGCCGATTTAAC
          TATACGGTGCAGCGACCGGGGTCATCGGGTTACACACCAGTAATGCCATGTCGTAGTATT
          GACGGCTACCGTTTACTTAAAGCCTGTAAATGATTGTCCAGTTGGAAACGTCCACATGTT
          GCTGAGCTTCGCTGCTATACGTCGAGGTTACCACTACCTTGCTGGAATAGTACCTATTTC

          GTCATCCCTGTAGTGTAGGGTGAGATTCCCCATTGTTCTCGATAGTTTCGATGCTACTCA
          GCCATCCCTGCAGTGTAGGGTGAGAGTCCCCATTATTCTCCATACTTCCGATGCTACTCA
          AATGTCTACAGGACAAAAGGGGCTACTCGCCATGGCACTCATCTCTCTGAACCGTTTTTG
          AGCGCTCTTGAGTAACAAGAAGCTTTTACCCAATTTACTTGCCTACCTAAAACTTAGGTT
          CCCGAATATGGGCAGGCCGGCTTTCCATCCTAACAGAACCGCTTCCATAGGCTTCACGAA
          CGCAGCCAGGTGTAGCACAGTGTTGGCCACCACCGGTGCCAGACAGTTTCGTCCCATGTA
          AGATATCTAGGCTACTATTACGATGTCTCTTGTCCGGATCCCCTAGGCCGAGATGTCGTA
          GGGGACTGTAGCTGGTTTCGCGCTGTTTACAGTAAGTACCCTCTACGCCAATCTAGTGCA

          GAGCGATCCACGCGGCATACTTTTCTCCACCCTGGGTATACGTCATAACATGCTTCGATT
          GAGCGATCCACGCGGCACACTTTTCTTCACCTTGGGCATAGGTCATAACATGCTTCGATT
          GAGCGGTTCTCGCGGTATACTTTTCACAACTGTGGGTCCAGAAAATAGAACGTCCTAATT
          AAGCAATTTTTACGACCAAACTTCTTGCACTAGTTCATTGCTGAGACATACGAACTCATG
          AAATAACATTACTGGTTTTCCTCACCCTATCTTTCTAATGAAATCTAAGCTCTTCAAACA
          GAGCGGTGTTTCTGCCCGCTCTGCCCGCACTCGCCGAATGAAAGTAGCAACGCCTAGATT
          AAGAGACCTTCTGCAATTTCTTACATCGACACCCAGGGAAACCACCCCAATAATAATTGA
          TAGGGTTTTTCTGAGGCATTCAAAGTTTTCACGTAATGTCAAACTCGATATAACACCATA

          GACAGATCGCCGGCCGTATAGACAATCTAGACGAAGATAATCGGAGCCTCTGAGGCCGTT
          GATAGATCGCTGGCCGTATAGACAGCATAGACGAAGATATTCGGAGCCGCTGAGGCCGTT
          GGCAAGTCGCAGGACAAATAACCATTCGTTAGGGGGACATCCGGAGGTGCCGAGGCTGTG
          GCTACCCCGTTGACTGTGCGGATATCCGTTAGGAGAATAATAGCCAGACCGATAGTCGCA
          TTTAGGCTGGTTGCTAGTTCAAAGACCCCCGGGATTATGACCCAGACTATGACCAAAATC
          TCGTGACCAATGACTGCCACTGGAATTATTGAAGCCACGGCCACAAGCAACGCTGGTACA
          GCAAGGACAGCGGCCGCTTGCCTGTCAGGTTCTGGTACAACTCGGCGGGACATTGCGACC
          GTAAGCTCGATGATAGCCCCATAGATCGCCCACGACGCGCTCCGACACAGTAGCGTGATA

          GGTATCAACGACAGTCGGGCGTGATCGGATAATCCCCGCCAGACCCTGCCTCAGCTGCGA
          GGTATCAAAGACAGTCGGGCGTGATCGGGTAATTCCCGCCCAACCACGCCTCAGCTGCGA
          GGGACCGGTGACCGCTAACAGTGATAGGGTAGAGGCTGCCCGACTACGTCCACGCTTTGA
          ATTGTCGGTTCTCACGTGAGGCGTTGGGGTGGGCGCTATCCAGCGGCGGTAGGGTCTCGA
          GTGGTTTGGACCCATTCGCGTTGTTTAACCGGGGCCTATGCAAGACGGCTCGAGTCTTGT
          TATGTTAAAACCTCTACAGAAAGATTGATTCGAACTTACGGAATCAAGGTCACGTCTCAC
          CCTACAGCTGCTAACGCGTGGCAGAGCGCTGGGCTACTCGGAGACTCATTTATAGCGTTA
          CACGCCATCGTCTTTGTGGGGACAAGGCTCGGGCGATTTACGAAGAGATCTGCCGCATCC

          CGCGCGATGTAGACACGCCGGTCAGGAAATGAGGCCCGGGCCAAACTAGCTGTGGATACC
          TGTGCGAGATAGACACGCCGGTCTGGAGATGAGGTCCGGGCCAAACTAGCTGTGGATACT
          CTCATGACCGGGAGGTACCGGCCAGGGCTTGAGGACCGGTTCGAACGAATTATTAACACG
          CCCGCGATTGAGACGTGTCTTGTAGAGCACAAGGCTCGTGCCGTGTAAACATCCTCTCTC
          CCCGAGAACCGGAGGTGTTAGTTCGAGTTCGTTGATTGCTCATATCATATCATCCCTCCT
          CTCGGGACAGAAGGAGCGCGGACAGGCCAATCGGATAAAGCAGACTGGAATATGCCCACG
          CCCGCACCCCGGATGTAGTAAGAGGAGCCCGTAGTCAGCGCTGAACTTATCGAAGTGCCC
          CCCATAACGTGGATGAAGCAAGAAGGCGGCGCGCTTTGCTCCAACCTTATCAAGCTCCTC

          AAACTGATGATGATTAGAACTCTGTAAGAGGATGGAGATC
          AAAGTGATGGTGATTCGACCTCTGTCAGAGTATAAAGGTC
          AGTCTAGCAGAGGCTTGAATTCTGTAAGAGGACAAATGTA
          AGATTCGTGGATGCCGAAAGGCTTCTACAGTGCAAGACCC
          GGAAGCTTAGGGCCTGAGAGCGGACGAGTATCCGAAACAC
          GTGATTCCGGAGACTGGAACCCTGCAAGTGTGTAAGCGCC
          GGTCTTTTGAATCGCGCACCCAACTTCCTGTGTTAAGGCC
          AGATTTATCTATCGAGTAATCAAGCATTTACGTCATACCA

