 8 1000
t1        CTCGCGCGGTCAGCAATAGTAGAGGCCTACAGTGCAACGTAGGAAAGTGGAGGAGTGGCG
t2        GTCGTGCGGTTAGCAAAAGCAGGGGCCTATAGAGAACTATAGGAAAGAGAAGGAGTAGGG
t3        GTCGCGCTACCAGCAAAAACAGACGCCTACGAGGCACCGTAGGCAAGATAAGGTGTTGTA
t4        GTCGCGCAGTTAACGGAAACAGAGGCTTATAAAGCGACGTGGGCAAGAGCCGGAGTGGCG
t5        GACTGACCTAACAAGCTGCGAGAGGTCGGTTTCCCGGCTCCTTACCAGAGGTCCAACAGG
t6        GGCTGGTTTAAGAAGCTGAGAGATGTCGGCTTCCCGGACCATCACCCAAGTTTTAATAGG
t7        ACCTGATCCATCGTGCTGGGAAGGCTTGGCCCTCGGGCTCGCTACCTATGTTCCAATAAT
t8        GTCCGACCCAAAATGCTGAGAGGGCTCGGCTTGCCGGCCCGTGACCGAGGCTCCAATTGG

          TTCTTGTAGCTGCGAGCCTACGGGGCACAGTGGACAGAAACCAGTACTAAGCTCGAACGA
          TGTTTGAAGCCGCGAGACCGCGGGACTCAGTGAACGCGAAACGCTTCATTTCTCAGACGT
          TTTATGATGCCGCGAGATTACTGGTCATAGAAGACACAAGAGACTCTTAATTTCAAACTA
          CTCCCGTTGCCGCGAGCTTACGGGCCACGGAGGACACAAAAGGGCCACGAGCTCAAACGA
          CGTGAATCGCGATTGTAGGGGCAGCTCTACTGCCGCCAGAGACGTAACGCGGGCCCCGTA
          CTCGACGGGCAGTGAAAGGGGCTGATTTATCACCTGCTGAGACGCTTCATAGTTCTTTCA
          TCCACTATGCGGCGGGAGGGGCAGTGCCGATGCTGCCAGAAACGTTTTACGAGCCGTTAA
          TTTCGGGCGTAGCAAAAATGGCAATTTCACTGCCGCCCGTAACGCCATAAGGGTTCCCTG

          TCTGCGTTCTCTTCCTTTAGCCAGACCACCGCGGTCAGAAGAGCGCCATGCTTTAGTGAT
          TCTGCGTTCTCTTCTTTCAGGCGGCCACCCCCGGTTAGGAGAGTGCCAAGCCTTAGTGAC
          TCAGCGACCTCGCCCTCTGGGCGGCGAACCACGGGTAGGAGAGTATCATGCCTTGATGGA
          TCAGTGCCCCGATAGCCCTTGCGGGCAACCACGGCTAGGAGGGTGTCTCGATTCGATAGA
          TTTACGTCTGCCGATTCCAAGCGCGTCATTTATGTAGGGAAGTGTTTATGTCTATGACAC
          TCTGCGACTGAGGATCTCGAGTGCGCAACTTTCGTAGGGAGATGTACATACTCATCATAT
          ATCGAGTCTGCGGATTCAGGGCGCCTAACTTATGTAGGGATGCGTATATTAATATGTCAC
          TTTGTGTCTGTGGATCACATTGGTGTAACTCACGGAGGAAGGTGTGTACATATATGACCC

          CGCTCCCAAGCCTCTGCATGGTTATCGAACTGTGCGACATGCTACGCGGTACGCGATAAC
          CGCTCCTAAGCCCCTATATCGTTGTTGAACCGTGCAGCTTTCTGTGACGTGCGCGACAAT
          CACAACTACGGCCTTATATTGTTATCCAACTAGGAAGCTTGCTACATCGTGCGCGGCAAT
          TGCTGTTAAGCCCCTCTACCGCAATCATACTGTGCGGCTTATTACGCCGTGCATAGCAAT
          CAGTCCGACTTTCTTTGCGTTTGCGTTGAAGGTTGAGATTGATGCACGCTCTGTGGAAGA
          CGGTGCGATCTTATTTGCCTCTAAGTTAAAGGTTAAGACTGCCGCATGTTCTGGGGTAGA
          CAGGGCGACTTTATTTACGTGCGTGCTGTTGGTTGAGACTGGCGCTCTTTCCGTGGTAGC
          TACGGCGACTCTGTTTGTGTGTACGCCACAGGTTGGGATTAGAGCACGTCCTGCGGTAGC

          TCTCTATTGCCAACTCGGTACAGCTATTTATATTTCAGAACAACCGAGTCACACCTTACC
          TCTTGAACCGTGATACGAAATAGCCATTTAAATTTCAGAATAACCGAATAACATATCAGC
          TCTTAATCGCCGGCTAGGACTAGCAAATCATAACGCGGAATAGCGAGGTATTATAACAGT
          TCTTATTAGCTGGTACGGAGTAGCCAATCACATTTCGATATAACTGGGTATCATCTCTAC
          GAACCATAACTGGTTTGTAAAAGCGAGGAGTATCCGGGGTGCGGTGAGCCTTAGGTACCA
          GGACCACAATAGGTTTATAGCATTTAGGCGTTTTAGTAGTACGGCGGGTCTTTGCCACAA
          GAGTTATATATGGTTTATGGTATTCATGGGTACCCAAGGTAAGGGAACCCTTCGGCACCT
          GAAAAACAGACAGCTTATAATATTTTTGAGTACTCGAAGCAAGGAGGGCCTCGGGTATCT

          ACTCCTACATTAGCCACTGCCTGCTTCGCTGCCACATGTTTGTGGATGATAATTATGAAG
          ACCCACATTTTAGCGTCTGCCTACTTGTCCGCCACATGTTTGAGGTTGACAATTACGAAA
          ACGTCTACGTTATCAACGGCCTATATTTTTACCACATGTTGGCGCGTGATCAACACGAAA
          ACGCTCAAATTATCAAACGGCTATCTATCCACTACACGTTGATGTATGATAATTGCACAG
          TTAAAGATCTGACCAGCGGACCGCCTCCCCGTTTTGTGGGTCCGACTAGTGATAATTCTG
          TTACAGACCTGTCCAGCGGCCGGCTTCCCTGACTCGTAGGTCTTATTAGTGTCGTTCCCG
          TCGAGTATCTGTCCAAGCGACCGCCCCCCGTTCTCGGGGGATTCATTAGTGTCACTCCTG
          CCGACGAATTGTTCAGGGGACTACTTCCTTTTACCAGGGGTTCAATGACTGCGATGGCCG

          AGCAAAATCAAGGGCATGCTTGCTAGCAGGTTCGGTGGGAGAGTTGCTATGTCTATGTGT
          AGCATAACTAAGAGCACGTCTGCTTGCAGGATCGGGGGGAGGTACGCTATGCTTACGAGT
          GGTAAGTCCTAGAGCATGCTTGCTTAAAGGGCAGGTAGGAAGGACGCCATACTTACGCGT
          AGCAAAGCCAAACGCTCGTCCACTAGCTGGGTCGGTAGATTGAATGCTATACTTACGAAC
          CGAATTATTGCAACCTCGTCTCCAGTTTTAGGTGTCAACTAAGGGAGCTCAAGGCTCGAT
          CCTACAATTGTCAGTTCGTCACCTGCTTTAAGTGTTAGCTAAGACGGGTAAAATCCCGCT
          CGTACAATCATAGGCTCGTCGCGCGTCTAAAGTGCTAACGGCGGTAGTTCAAGCCTCGAT
          CTCACAACCGCAAGTCCATTGTGCCTTCTAGGTGCGCGCCGAGGAGGTTTGAGCTTTGCC

          CCGCAATTGCCCCCTTCATCCCTTGAGCCCCAACCCCTGCGCACCACGGACTCATGGGTG
          CCACGATTGCCTCTCTCATTTCTTGAGTTCCAACCCATGAGCCCTTCGAACTGATGTGCA
          CCGCGATAGTCCCCTTTATGCCTTAAACACCAATTCGCGAGCAACGTGGATTGACATGTA
          TCACGATAATCCTCTTCATCTCTGGGATTATAGTCCGTGAGCGACTTGGCTTGGTGTGCA
          AGAAGCTCCTCTTCCCTTGTCGGCAGAATGTAAAGACCAGGTGAAATAAAAGAGGATCTA
          AGAAGCTCGACTGCCTCTATCGAGAGGAAGCTATCACTAAGTACAACAAAAAAGCTCCCA
          ATGAGTTTGCCTGTTTCCATAGGCAGACTGCAGTGACCAAACACAAAAAAAAGAGGCCGC
          ACCAGCTCCACTGGCTATGCTGGCGGAATACAGTGACCAGACGGAATAAAAAGGGGCCTA

          CTCGAAAAGAGACACTTTCCGACGGGCAATGCGATGCCATTTCTCAGACAGCCTGAGGAT
          TTCAAAGAGAGACGCTTTCCGGCGTCCAGTACAACGCTACTTCTGTGCCAACTTGAGGGC
          CTCAAAAAGAGACTTTTCCCGGTACGCAATACAACGTTATTACTATGTAAGTCTACGGGT
          CCTAAAAAGAGTCACTTTCCGGCGCGAAGTACAACGCTATATTTGTGACGGCTTGAGTAT
          CAGCTAATTGCTCATATCTTCTTAGAGACCCATGCAGTACGATATAAATAGCTTAAACTT
          GATGACATTGCTAATTTCACATTGGAGATCCTTGCAGTACGCTATGGGCTGTTTGCGCTT
          CGGGACATCGCCTACATCCCATTAGAGACTACCGTAGCGCGTTCTAAGTTATTTGAGCCC
          CATGGCCACGCTTATACTTCACGTGAGACCCCCGTGGTTAGAAATGGGTTATCTGAACAT

          CCCCAGAGGATTACTTGAGGCGACGCAGACGATATCTTATATCATTCTAGCCCGTGTGAT
          CCACGGGGGACTACTTGAGGTGGTGCGGTAGCCATATAATATCGTTCTAGCATGCTCGGC
          CTACAAGGGATTACTAGAGGAGGTGTAGGAGCGGTTTCATATTCTTTTGTTGTGTGCGAC
          CCACAGGGGATTACACGGAGTGGTGCAGAAGACGTTTCATATCGTCTTATCTTGTGCGAT
          AGGTGGGCTGGTGACCTGAGGTATACTAAGGATTGACTATAGGGCCCCTAATCGGACAAG
          ATAAGGAGAGTCATTCTGGGATACCTTCAGATTTGATGATAGGGCCTCCAAGCGCGCAAG
          GCACGGGAAGTCAATCCGGGGCACCTCAAAGGTAAATTATGGGGCCTTCAAGAGCACAAA
          TCTCCGAGAGTCGCTTCGGGGAGCCTCAAGGCTGACTAATAGGCCACTCGAGTGCACAAG

          CTCGACTCGTCCTCAATGTGAGGGTGGCACAACAATACGTCAGCAGGGTCGAATTACGCG
          TTATACTACTACACGCTGCAAGGGTGGTACAATTATACGCCAGTAAAGTCGGAGCACGCG
          CTCTACTCGTGCTCATTACGAAGGTGACATAGAAATACGCCAAAACGGTTAAATCTCGCT
          TTCTGCTCCTGCTCGATGCAAGGGTGAGATACCAGTACACCAGTAAGGTCGGCTCTTGCC
          CACCGGCACCGCCTATACTCATGGGAATCATACCTTGCATCAGGACCAGCGCACTGGACT
          CGCCGGTATCGTTCACATCTCTGAAGGCCTGACTTTGCGAGACGATTAACGGGCTGGATT
          TGCTTGTTCTGTTTACACTCACGGAGTTATGGCACTGTGAAAAGACCAGCGGATTGGGCT
          TCGTGACTCCGCTTACGTCTGCAGAGGTCCGTCCTAGCGATAGGGCTTTCGGCTCGAGCT

          GCTTGCCTGACCTGAGGCGAAGCGGGTTGTTAGATAATCTAACAACTTACGCCCTCATGG
          GTTTGCTTGTCCAAAGGTTAAGTAGGCTGTTATAAAATCTCACTACATACGCTCTAACAG
          GCATATTTGTTACGAGGTGAAACGGGTTGCTAAAAAATACAACGGTCTTTGCCCTCATAG
          GTGTCTCTGTCCTGAGGAGAAGAAGATTGTTAAAAAGCCTAACTGCGTACGCCCTTATCG
          CACTCTCGGCTCCCCGCCATTGCGGAGTTTGATGAGTCTCCGCCGCGGCGCTTAGTACAG
          CACTATAATCCTCTAGTCATCGCGGAGTTTAATCCGGCTCAGTCGCAGTACGTGTCACAG
          ACATACAGTTTTGCAGGCATTGCGAAGTTCGATAAGGCGCTGTTATAGGTCACGGAACAG
          AACTATAGTCTTTCAGCCATTACAAAGATTGGTGAAGCTTCGTTTAATCTCCCGGCACTG

          CGAATATAGAACGAGCAAGGATTTCAACCGTCGGATTTCAAAGTACTGTGTCTACCTCCT
          CGGATGTACACAGAGTCAAAATCAGAACCGCCGGACTCGAGAGCTTCGTGACTCCCGAAT
          TGGCAATACGTAGACCACGGGTACCAGCGGTTGGATCGCAACATTTTGAGACTCTCCTCT
          CGGAAATCCTCAGAGCCAAGGCGTCAACCGTCGGATTTCAAGGTTCTGTAACTCACGTCG
          AAGTAAGTCATAGCAAGAGACATGTCTATTTATAAATGTTCATACTTGTAGTCGGCCGTT
          GCAGAGGCTTTGCTATAAGACATGTTCATTTAAGAGATACGGCCCTCGTAATTCACGGTC
          AAGGATGCTACGCCTAGAGACCTGTCCACCTACAAACGATATACCCCGTAGTCCACGGGG
          GCGGACACTACGCCAAGGAACCTGCATATCCACCAGTCCCAGACCATGTGGTCCACGGTC

          TGCCCAAGAAGCTTATGATCTCACACCAATGGTCTCACCCGCTGAATCGGCAGACCTCAT
          CAACCAAGAAACTTACGGTACTGCACTAACGACCGCATTCGCTGAGACGACAACTCGTAC
          TCCACAAGAGGTTTATGGTTGCGCACTAACGGTATCACTTGCTGGAACAGCAGCTAAGAC
          TGCATAAGAAGCGTGGGGTACCGTACTAATTGTTTCATCCGCTGGAATAACAGCTCAGAC
          TGCCGTGGGCGTATTTTGGCCATTTATGCGGATGCTGTTACCTCCGACCGCGGTCCCACA
          GACCGCATGTGGGTCTTGACCATTAACGCGGATGTTGCTATCTCCTACGGCAGCTCCATG
          GGACCTAGGCGGATTTGGGTCCCCAATCCAGGCGTTGCTACCTTATGCAGCAGCACCACG
          GGCCTGACGCGGATTAGGACCATTAGTGTGGTTGCTGATTCCTTTTTCAACGGCCCAACG

          TTAGGGGGGCCAATTTCAAACCCTCGATGAGTTCTCTTTCTCACAATAAGCCGCTGCTTA
          CTCGTCGGGTGAACTTTAAGCCCTGGGCTCGTCCTCAATCTCACAATACAACCCTGCTCA
          TTTGGCGGGGGGACTTTTGACACTCGGCCAGTTCTCATTCTCACGACAAAACGCAGCTTA
          TCAGGCGGGAGGACTTAAGGCCTTCGGCCAGTTCTCATTCTCAAAATAAAATGCCGTTTT
          TACGGGGCGGGGCACTACGTCTAAGGGGTGGATGCTACGCCGAGAAGTTACCTGATGCTA
          TACCGCGCCAGACACTAGGTCCCTAGAGTAGTTTGTGCATCCACATCCTACTTGTGCTTA
          TACTGCGGGAGACAATAAGATCATCGGGCACCGTAGAATCCGATCCATTCCCAGACCCTA
          CACTGCATGAGATATTGCATGTACGGAGCGAATTCTACCCGGACCTCTTTCGTGCTCATA

          TAAGCCTGGAACAATTGAATTCTATCACGGAAATAGGGTAACTACCGCGTGTCCAGACGG
          CTAGTCCGGATCAAGTGAAACTTACCAAGGCGAGAGATCAATTAACGCGTGATCAAATAG
          TCAGCCCAGAACAATTGCATTTTATCGTGCAAATTAGAGAACTACCGTGAGTTAAGATCG
          CCAGTCCGGAGCCGTAGTATTCTATAAGGCAAGTAGGATTGCTACCGCGCGCTCACGCCG
          TAAGATTAACTTAATTTCCTAGTTTTAAGCAGATTTATGATTACTCCAATGGCCCTTTAG
          TGGGAGGTACCTCATTCTTTGTTGTAATGCAGACTTATGAGTAGTCGAATGCATCTACGG
          TGAAACGTACTTAATTCTCTCTCGCTAGGTCGACTTATCGGGACACAAATGGCATTGTAA
          TGAGACTTATATCATCCTCTCTCGCGAAAACAACTTATTCGTAGACAGATGTCCCTGTAG

          CCTGCCATCAAGGGCATACAACGGCTAGAGTGTCGCCTGC
          CCAGTCATCAAGAGTATTCAGCGACCAGATCGTTGCCTAC
          CTAGTTGCTTAGAGTACACAACGGCCAGACAGCTGCCTAT
          CCAGATGTCGAGAGAACACAACGGCCACGCCGTTGCCCAC
          TCCGTAATTAATGTAAAGTTACGGTTGTACTGTTCGTCTT
          TACGCGATACTGGCAGAAGCACGGCCGAACTGTCTGGCGT
          TAAGCAATTAAGGTGGGCGGCTTGCTAAAGTGCTCGGCGT
          TCCGTAACTATGGTAGGCTCACTGCTGAGCTGCTGGACAG

