 8 1000
t1        GCCCACGTAACCACAATGTTATGAGCCTAACCAAGTCTACTTTGGTGTCACTGCCGCGCA
t2        CCACGCAGTGCGGCGTTGTCAGAGCGTTAGCCAAGTTCGGCCCTCGCCAAGCGAAACCAA
t3        TTCGCTGGAACACCACTCTGAACAGGCTAAGCAGGGTCGCAGTGACCTAGTTTTAGCGCA
t4        TTTAGTAAGGCTCCGTCCAGACTCACCAGAGCTAGCTTATGGTTAGATAGACACAGCGAG
t5        TGCTATAGTCGCCCCTGATGCGCCGAACTCTTCGGATAGCCCCACTTGCTAGATTTCTCA
t6        TATTGCGGGGTTAGACAAGACCAGCCAACGGTAAGACGAAGTTATAGGCTAAGTCCGTAA
t7        TCCTACGGTGTTCCTACATTTCAAGACTGATCGGGCCCGTGTACAAAACTTCTTTGCAGG
t8        TTCCCCGGCCTTCCTACGCTTCGAGACCAAGTTGGTCAGTGTACAGGACTGCTTTGCAGG

          TGCCCTCTAGAACCCACACCGCCTTCCGTTTCGATTACCTTATAATATCGCTTCAATAGG
          AAAGTTCTTATTTTTTTGCCCACACTCACTCCTCTCCACTTATGGTTAGTACCAGCTAAG
          TACTCTCCGGTCCCAGTCGCTACATCGTTCGCATGTACGTTGGTGGCGGTGTGAGAGATA
          TAGTTTTTGACCCTAGTCGCAACGTCCGACCCACGCACGCTGATATCAGTGTCGAGCGGG
          ATAGTCTAAGAAGTAAAATTTGTCACGGGTTCAGACATATTCAGATCAACATATATCGCA
          ATAGCTATGGTGCTAGTATCAATTACTCACGTGACGTTACCGAATCTACCTCACAAAGGC
          ATGGCTACTGGGCCGGACTAATTATCCGGCTTAGTCACTAAGTGCCCGAAATTTCTACAA
          CTCGCTATTGCGTTGGACTATCTAACCGGCCTAGTCACTTAGAGATAAGAATTTGTAAAA

          CTTGCTACCAACAGCCAATATGAAGCGTTAAAGGCTCTCAGGTACTTAGGCGGACCCCTT
          TTATTTACCGCGGGCGCGTCCGTAATTTTCAAGCATCCGGGGACCACAGGCTTCAGGCTA
          GCACTCGCCTCGAACACGTTAGAGATTGATGGATATGATGCTTGCGGTGGCTACAACACC
          GAGCTCGTCATGCAATCAATACTAATAGACGGATATGACAGACGTTCTCGTAACAGTACA
          GATTCCCATAAGCGACGTTTAGCGATCAACGGGCATGATAACTGCGTCGTTGTTCCGAAG
          CTTCCTAAGTTGCGCTGGAGGGTTAGTGAGTAACATATTGGTCGGGCCGCTCGATGAATG
          GACATCTTAAGGCACGTTCTCCGAATTATTCAGCACTGTCTTAGACTTTCTTGATGGTCG
          AGCATCTTAACGCGTAGTTTACCTATCATCTGGCATTGTAGTAGATTATCCTCATGGAAG

          CCCTGCGGAGGCGCGCCTTTGGAATCATAACTGACCTCCTTATCCTCTCCTAGTCTGCGG
          TGCTAAATCTAGGCGACCGTGAAACCTGCATAGGCATTTTTTCTTCTTCATCTTCCTGCT
          ACCTGGTTGATTGCACCCGTGGTAACCCACCTGTGTTACTTACAGCATATCGGATGGTTG
          CCTGAGATACGGTCATACGCGGTCGCCTCCCTAAAGCATGAGGAGTCCATAAGGCGTTCG
          CATCCATCAGAGGCACGTTTCAGGTCCTGGCAATACTCTACTTTATATAGTGATCTGTAC
          ATTGCGTTTAATGCATCATTAACATGCCGGTTAAGCCCGTGGTCTTCCGGCAATATTCGT
          AGTGCGGAACAGGCAATTTCGGCGTTCAAAAACAACTTGTTGCTATTCCGCAATACGTCG
          CCTGCCGAGCAGAAGCCGTGGGCGCTTTTAAACTATTCCTCGCGGTTTCGCATCGCGTCG

          TGTTTCCTTCAGTCGGAAAAGTTGATACCTGACTATTATGCCTGCGAACAGTCCCTTAAG
          CACTCCTCGCGGTCGGACTGGCAGATCTCTAATTACTTAATCGGAGAAATGACCCATTGT
          TTGATACTTGATCCAGGACGGCCGGTCTTCCTCCTCTTTGTCAGCTTAGCGTCTCAGCCC
          ACATAACACTAATCAAAATGGCAGGGACCGCTCTAGTTTGTTCGCCCATTGTATTATTTT
          CGATCACTTAATGTGGGTCTGCCGTTACCTTTTCTGCGTGTGCGCGCATTTCATTGTAAA
          CGTACGCTTAAACTAGAACTACCGTTGTACGTCTCATCCGTGTGTAATCTGGATCATGCC
          CAGTCGGCTACTCCAGAGTGATTTCTGTACACGAACGCTGCTCGGACCCTGTCACAGCGC
          CGGATATCTACTCCAGAATGGTTACCGCAGTCGAATGCTACTCGAACCCTGGTACAGCGC

          AGATGCCACTTACTATGGAATACTTCCAATCTAGAAATCCGAACGAACTGCTCATTAGCT
          GGACGCGACCAACACTGAAGTATTCTTAACAAGGAGCTCCATGCCAATTTATCATCGGCC
          TTTCGTGAGCTTTGGCCGTGCGTCAATCCTTCAGTATCCAAAAATACCCTTAAACAAGCT
          ACATGTGAGATGCTGCGGTATACTTGTAATCCGGTATCCAAAGGTACCCGCAAGCTAGTC
          GCGACCGGACGGTCATGCTACGCGTTCAATACACCAGATCCAAGTCGGCGCCGGCTCATC
          AAGATCAGACGAGCGAGGTAGACATCTATGATAGGCGGTTGGCCTGATTTCTTAGTGGGC
          GCAGTTTGGTTACTTTAGCGTATTTCTAAAACAGCAATTACTTTTTGTCCCATTTTAGTG
          GCAGCTTCATAACTTTAAGCTACTCCTAACACAGCATTCATTTTTTGCCCCCTTTGACTG

          AGTACAGGTGTGGGGACTCCTCTGGCCGTAGCTCCGCGTAGTCGCGGTAACTAAAATGTA
          AGTGAGGATAAGAGGCGACTCTTGATTCAACCTCCGATATGCGGCGGTAAGTGCGGTGTC
          CGGATACGCAAGGCGTACCAGCAAGTTTTACTTGCGGCATGTGACACCAAACAAATGGCT
          TAGATCCTGATAGTAAATGATCGAATTTATACTGCGCTAAGTCTTATTCCCTTAGAAGTC
          TGGGGAAGTTAAGCTGAGCTGATGGCATGAAGACAACTGTAAGAATCTCGTTAGGACGTC
          AGGTCAGATGAGCTGTAGATGCCGGAAACGACCTACTTGTGAGATTTCGACTAGGGCACA
          TGCAGACATACAGTGTCACAACCGTCATTCACTGGGAAATCATACCTTGCCTCGGCAGCA
          AACAGAGGTGTCGCGCATCCGCATTAGCGCACTGTGGACTAACGCCTCGAACCGTCGATA

          ACAACGGAGCTAACTCAGAATTGATATTAGACGTAAGAGAAATCCATATGATCCCTTCTG
          AAAATAGAGCCGGTTCCTGGTTCGTTCTACCCGAAACGAGGGCCCCGGTCTGCACTTCTG
          CGAGGCGTATGGACTTGATTGGATCCCTGAAAAAGAGAGGACACCTGGTAAGTTCTTCAG
          CGAGGCGTATTAGGTTGATTGAGGCTCTGAATGAAAGTGGGCACTCTGTAACCCCCTTGG
          GATCTTATTGCGGCTCGTCGTTACACCCCGACGAATGGTTTAAGGTGCGTAGGCATCGCA
          CTGACGATTGCTATCTGTTGCAAGTTTCCGGCGAACTCCGCGGGTCAAGCTCGTTTCATA
          TTCGGTGCCTAGGATGGCCGCACGCTTTACGCAGGTGATGCTGGCTAAAGTGCATTTCAA
          TACGGTGTTGAGACTCGCCGTCAGCTTTGCGAAGGTAATGCTAGCCGAGGTCCATCTCAG

          CGTGGAAGGGAAGGCCTACATGACCTGGGGAGCGGTACGACATCTCCGAATAGGCGTGGT
          TGAGGAACAGGGGGTCTTTGTACTCTGAGGTGTGCATCGACATTCAAACAAGACAACGTT
          TCGAGGACGCGAGGCTCCGTCCCCTGACAGTACATCTTGACATGGTAGCAACGCGAAGCT
          CTAGAGCTTTAATCCCGCTCCGTTAAGTAACGCATCCAGGCACCTCGACAGCGCGACTAT
          TGAACGATGGACACTCTTTACGTTGCGTCGTCAACGGCAGTGAACGATGCTAGCAGGTGG
          CGCCCGATTGATGAGGCTGTTGGCTTATCATTTGGCCCGGCATCGTCGTATAGCAGAAGC
          TTGAGGAGAGTAGGTCTAGTAGTCCTACCAAACCCGGCGACGCCAAGGCGAAGGAATAGC
          CCGAGGGGCGAAGCCATCTGGCACCGATAAAATAGGAGGACACCTCTGCGAAGGAGCTGA

          AACGGTCTCTTAACACGGCTGGTAACGACACTAAGATGCGCGACTCTATCCTCCGTACCC
          AAGGGTCCCTTAGCCGCACCAGCGTTAATACTGGAGCGTGCTCCTCTAGTCAACGCGTTA
          GTCAGGGACGCAAGGACGTGCCTGTCATCCACTGCTGCTGTTACTTCTTTTAATGTGTTA
          CATGATGTAGCCTGAACGTGGAAAGTGATCACGGTCGTCGTTAGTCCCATAGATGCGCCA
          CGTATTCTACTGCCCACTTCTACCCCTGAGCTCGTATTTGTTTCATCTTTCCCAGTGCCA
          CAAGCCCCTTTATTCATTACGGTGGGGGTGCTCGCAAACGAGTTGTTCTATTCGGTGACC
          CTCCGCGCCCCCATTATACGGGCATTGATGGTCATGCACGTAGTTCTTCTATAAGCGTCG
          CCTCCCATCTCTGCTACACGGATATTCGTGGTCATGTACGTAGTTTTTCCTTAAGTGACG

          CTTATCAATAGCTGAAGTGTAGGGACCACCGGAGGGTCCGCACTCCACTCAAGCCAACTC
          CATGCCAACAGTTGATGGATTGTAAGTAAAATGTGTCACACGACTCAATCGGACTACACC
          CCTAACAGTGATTAACGCGACGGAGTCGCTAAATAACCAATGAGCTACGCTATATAGCGT
          CATTCTAAATATTGACGTTCCGCACTTGTTAGCTAGTCTATGGGTAGCACAATACGGAGT
          CTTATCCACAGCTAGGCCTCTCGGTTCGCCACATGCCCCAACACCATCATGGGCTCAGCC
          CTTGATATCGTCTGATACCTCGGGCATTTGGGCAGTTCGAGACTAACATAAGGCTAAACT
          CCTAGCTCAATCTAAAGTCCAAGATGGGTGGGTTGACGCACGCTTCGCCCGTTCTAGGAA
          ACCTGCGCAGCTCAAGTTCCAAGATTGGTAGGTTGCCCATCGCCTTGCTTGGTTTAAGAA

          TAGGATACTCCCGAGTCAGAATGAAATTTCAGCGGTTCCGGACCTTCATTCCGCTTTTGA
          TATTACACTTTCAACCTGGAGTGAAGGCCGGGCAGATCCGAATCTCCGCCCCGACGTAGA
          AAGACCACGAAGGAGTGATAGTGAAGAATAAGCCGTTACGGAGACAAGCCTTTATGTCCT
          AGGAACACAAGGGATATGCGTTAGATGATGTACTTCCTGCGTGAACAACGCCCCCCAGTC
          GGGGTGTGATTAGTACCTTTCTAGAACTCGTCCTATTGAGACCATCCGGGGTACAGTGTG
          TGGAAAATATTAGACCTCCTTCACGATTTTTCCCGATTGGAGCATTTGCGATGTAACACT
          GCGGAAAGGTTCATAATCCATAGCATTACACTCTGTTCTTACGATCCGCTATGGAACCCA
          GCGGCAAGGTCCATAGTCCACAGCAGCTCAGACAGGGCTCAACATCTGCTTCGTAACATG

          AACTCGGTGGAATCTTTAACTGCGCTCGTTCATCAAACTCACCACTCTTAGTTTTTGAAT
          GCCTTACTGGGATCGCGACATGTGTTCGAGAAATAAATCCATCAGCTCACGTTTATATAT
          GTCCTATTAAAGTTCTGAGCGTTGTTCGAAGATGAGGGAGCTCTTACTATGCAGACGAGT
          GTGATTTCAGGACCCTGATGCTCCTCCGATAGCTGTAGGAGACGTTCTCCGCCAACGGGC
          TCGTAAAGCCAACGTCAATACGTACTGGTTAGGCGGGAGATCACGTTGTCGTGGCCTGAA
          TGTTTGGAGGAAGAGAAATGATTGCAATTTTGACAGGACACTGTGGTTCCGTCGGTATCT
          ATCTGATCGTGCGGCTGGTATATGCTAGCTAGTCATGGCGAGGTCGCTTTGGAAGTGAAC
          CTTCGATCGCGAGGCTGGTATAAGCCTGCTAGGCAAGGCGAGGTCGTTTCGGCGGCGATC

          GCTCTACGTGGCAACGTGGTTGGCACCTACCATGAGCAGTGGAAGCATCGGGTCAGCATA
          GTATCGTGCGGTAAATCTGCTCCTGTTTACCTTGCCCCGAGGCAGCGCTTTGTCTACAGA
          TAGTGACGCCGCCAATTGAGCGCGGTCCGTACCCTCGCAAACCGCGGTGATCTCCGTGGT
          ACGGACTGCTACGGTCCGGATGTAGAAAGGACCCTCGCGTGACACAGTTACGCTCGAAGC
          GGATTTCCCTGACGACAGTCAACATGTCTCTCACCTGGGAAGGATTATTACGCGTAAAAT
          TGTCACTTTGGTGAGCAGCCCCCAAATCTCAGTGTATAACAAAGCTCCTGTGTGAATCGG
          TTGCGCACTTGTGCCAGACCCCTGACTTGGGGCAGAGAAAGTTGCTGTTCGGAAACAAGG
          TAGCGCACCCGTCCTAGGTTAATGACATGAGGCAGAGAATCATGCTTCTAAGCAATAAGA

          GGCTCGAAGCCGATGCTTCAGCAGACCTTAGGGTGGACCATGTAGATCTTTGGAAACGAG
          TCTTTGAGCTCGACATCCCACCGAGCCTGAAACTAATCATGGCACGATTATAGACAAAAA
          AAGTAGAAGGCAGAGTCCTATTTTCACTAAGCTCTGGCAAGCCGAACCGCTGGGATAAGC
          AAGTGGGAGGATGTGCCCTCTTTCCGCTAACTTCCTGCGAGCCAGATTCCTGGGCAAGGA
          GGCGGAGTAGTAGCACCTCAGCTGTCAAGCGCGCAGGAGGAGCCCATTGGTGGTCGCATT
          CGTCAACGACCCGCACATTGTTCGGTAAAGATACGTGAGATGGTCCGGTAAAGTTTGGAG
          GCTTAACGATAGATGTCACGCATGGACCTAGCCCTGGGGAGTCATGTTGAAGGCTCGGAG
          GTTTAACCATCGGTTGCACGCGTCCACCTGGTCCTGAAGAGTCACCTTGATGAGTTGGAG

          CACTTGATGGTCTGAGTGCAGAGTCTTAACCCAAGTACCAGTAAATCTACGGAGAGTTCC
          CGCCCCACGGTATGCGAGCAGGGTAATAGCCCAACAAGCCGAATATCCACAAAGAGCTCT
          CGTCCCTTGGTAGACGCGGCTGAGTCTTATGACATAGGTGCCCTAGCCACTGAGATTGCA
          CATCGCCCGGTTGAAGCCTCAGGAGCTGGATCGTCGGAGGTCGCAAATAGTGAAGGTGCA
          GGACGTGGCGCTGGACTTATTTCGGCGACTATACCAGTGATACTTTTCTAGAGATAATCC
          CATCAAACGGCGAAAATCTTTACGTTGGTTCCGTTATGAATCTCGGATATGGAAATTACT
          TGACCTCTGGCAGAAGTTCTGTCGTGGGTTTTGTCTGCAATCTTGGTTATGACGAAATTT
          GAACCTCCGGTTGTGATCCCGTCATGCGTCGTGTCTGCTGACCCGGTTATAACGGAATGT

          TCGAGATTCCAGATTATATCGCTGTTATAATACACATTTC
          TCCTAATTTCGAACCCTGATGCCGAAAAGGTGAACTCTGT
          AATATATTCCTGAAACTGGTTTTGGACCAACGCTTCAATT
          GTCATAACCTTGATCATGGGTTTGGACTGGCGCCTTGCCC
          GGCCCAACAATGTATCAAATAGTGGATCTATCAGCCATCC
          GACACACCTATGGGTCCAGGCAAGAACTCATTGACTCTTG
          GTAGGGCCCGAAGTCAAGGGGTGGGGATTGTTAGTAAATG
          GTCGGATTTGAATCCAAAGGGTGGGGGCTACTAGAAACCA

