 8 1000
t1        GGCCAAGGAAGGTCATGATTACTGTTTATTTCGATACCCAGTCTGCAGTACTATGTTGTT
t2        AACCTCGGAAACATGGGATTCCTGCCGGCTTCCGGATCCGTTTGGCCAGGCCGAGTCACT
t3        AACTTGCGCCGAACAAAGCCTCTGCCCACAGCTGCCCGGTGAGTATAGAATTAGATTTCC
t4        AGCTCGCGTAAGAGGGGGCCTCTATTTGCTATGTTGTATGCATTACCCGCTTACATCCCC
t5        GGTTTTAGCTCAGGCGGAACTAAGTGCGATCCGTGACCTCCTCCAGAAGTTTGAACCTCC
t6        GCTCTTAGCTTAGGCGAACCTAAGCATGATCGGTGACCAACTCTAGATGATCGTATCTTT
t7        GATTAGTGTTAAGATGGTCTAATGTCCGTATTCTCCTAGGCTTCTTTGGGGTATATTGAA
t8        TCAACTCGATATGCAGGCCTCCCGACTGGTCCGCCGCACCGTCTGTCGAACTGCGTTAGA

          GCGACTATTACCAACCTGTTTCGACCCCGGCTGGCTTCTACTTATCGTCACCCGGCTACG
          AGCCACACCAGCATTCGGACGCGACTCTGGCATTGCCGTTTGGGTCCACTAAGCGACGTG
          GTTGCCGCTGGAAGCTATACTCCACTTTCGCTGGCTCATGCAGACATGAATGATAATGCT
          GGCGATGTAAATGGTTAGCTGGGACCTGGGACGTTAATTACGTCACTCGTCTGAGAACTA
          GGCGTTGCCGAATATTGTTCCTAGCTTCAGTGTAACCGTCCTTAGCAAATAGCAAATCTA
          GGCGCCGTCGAACATCACTCCTAGCCTCAGTACAAATGTACTTAGCAAATAGCTAGTCCA
          GCCACCCCTCTCTGCCCACCGCAACATTTCTACTCTCTCGGCGCTAGGGGTTAGCGCATG
          GATGCTACCTTTTGTGGGACTCTTTCTTCTCTAATTTTTGGGGAATAGGTTACCGGCTTG

          AGCCCTGTGGATAAAGGGGCTTACAGTAACAGCTGTGTGAAGCCTTTAATAAAGGCCCTG
          GATTCTTTAGCCTAGGGAGATTGTCGTCCGACATATGTAAAGATCGTACTGGCGGTCGAG
          CTTTTCCCAGATGGGCGAGCGAACAGCAGTGTGTAAAAGGAAACCCGATTACCGGTTACG
          AGTCCCCCAGAAAGGGATATAGACATTCGTCTATTAACCAGTCAAACACCCAACGGCGTG
          AATACGTGGGGCGTAGTAATCGTCGCACCCTTAGACACGAACGATCCGCCGCTGGACGAG
          AATACGTACGGCGCCGTAATTGTCGCAGCTTTCGGAATGAACAATACGTCGTCGAACGAG
          GCCGGATTGTGGAGGGGTGCTCGCAGCCATGAGGAAACTAAGGCTCTACCGTCGCAGACG
          GGCCCACTATTAGGGGATCTCAAAACTCTAATAACAACGGACGCCTCTGTTGTGATTCTA

          GGCTGATTTCACGGCCAAAGTTTGCGGCATCTCAGACTTGTCATACCGTCAAGCACCTCC
          GTCTGGTCCTTTGGCACACGACCGCGACTTCCGAGCCTTGCTCTGTTGGACGATAGAGGC
          CAATGCGTGTATGAAGGATCACCGCGCTGCGAGGGCCCCATTGCTACAGCAAATGGGCAT
          GGGTCTCTAAACGGCCGGCGGTCGTGCTCTCCGAACTTTATAATCCAGATAAGCGACCAC
          GTGACTCGCGTTTGTGGCAGCGGGTAGCCCTTCGGTGTTATCGGGCCAATAGACATCCAC
          GCGGCTAACGACTGTGGCTGCACGTGGATCTGAGGTATTCTCGGATCGATAGACGTCCAC
          TCTTCTACCCACGGTGGCTTGTCTCGATATGCGTGCACAGTAATACTCGCTGACCACTAC
          GACTACGATTGCGGCTATTCCCCGCGGGATTCGGACTGCGGGGGAAGTTTAGGGGGTAAA

          TCACCTAAAATGTTGATGAGTGTCAGCTACACTCTCCGCATTCCGGGCGCTACTCGCGGC
          TCTCAAAATGTCTTTAGGAGCGATAATTAAACCTCCTAGAGTTAAGGCTACATAAGCGGA
          CCATAACGCTTTCTTGCTAGGAAGCGTGAGATGTTGCAAGTCACCGACGATGTCCGCGCT
          TCGCACCAGGTTTTCGGCAGTGATCGTGAAATAACACGACCAAGAGGCGAAGTCCATGGA
          TAATTCTAGCTGATGCAAAATGTGTGGGACATTCCCTAAGCCGTAGACAACGAACGTCTC
          ACAATCTAGGTGATGCAGAATACGTAGGGCTTTCCTTAAGCTGCAGCCAACGACCGTTGC
          TTCTCTTTGGTGTTCAAGAGGATTTCTTCAATCTCCTAAAGTATCGGTGGCCCGAGCAAC
          TTTCATTTGCAAAGTAAGGGACGCCATGATACTCCCCTTGTGGAAGCTAGTGACGGCACG

          TCCCGAATTCCTTGAGTGAAAAATTCTGATCAGACGGATTTTCCGGGAGCAATAGGGAAT
          CACCAATGCCATCGAGTGCACAACGCCAGCCAGAAGAACCCATTTCGTGAATCAACGATA
          GATTGCGACCCTTATGAAATCGAGTCTCATCTGAGGCGATCATTTTGAACTGCACTGGCG
          GGTTGTGATAAAAGAATGTTAGCACCCGAGTGCCCGAACTTCTTCCGAAACGGAACGGCG
          GGCAGTCGTTTTAGGCCTTTGACCCAACCCCTTTGATGACAACCTCTATATGTAGTGGAA
          AGCCTTCGTTTTAGGGCTTCGACCCGGCCCCCTTGAAGACACCCTCTGGGTGCAGTGGCA
          ACCCGCAAATTGCAGTTGTTGATTTTCTAGCGGTTTAATTCTCCATATACTTGGCAGGTG
          AATCGGAATTAGAGGTCGAAGAGTTCACAATCCGGTAGTTCACGCCAATGTCAGGGGAGT

          TTTATCACCGGAGGGCGTGAGGTGTTCGGTGTAATTCTGGAGCGACGTAGAGAAAAGTGT
          CATACCTCAGGGGGGTACGCAGCATAATGTGTAGCTTGGCGGTATCCTTGAATGCACACA
          AGAGTCCGCGCAAGGTCCGGGGCGTTCGGCGAGACCCGGTGTAAGCTATATGAGTAGCCG
          CGATAAACGATTGAGCCTGCAATACCATGCGTAGGACGCTCGCGAGCCACGGCGGGTTGA
          GAAACAGAAGTCGGAATAGAAGCGATTCGTGAAGCTCGGATGTAATCAATGAAGACCCAA
          GAAATAAAAATCGGAGCAGAGGTGATTTGTAAAGCTTGGGTGTAATTAATAAAGATCCAA
          CGCCTTCCTCTGGGACATAGAGGCCCCACCGGGGCTTACATTATGCCCGACATCCAGAGG
          TGAATGGGTGACGGGTGCTGTGGGAATCTTGCATCTCAGGCGCTTTCATAGGCGCAGCAG

          TCCGTGAGGAGCAATGGAATCGGATTATGAGCAGATGTCAGGAATGCACGCAGTATTGTA
          CCAGGGAGCGGCATCTGGATGGATTTAAGCTCAGTTATAAATTAGACATGTAATACCACG
          ACCGCGGGTCGCCAAAGAAGACGTTTATCAATAACGATCATTTGATCACGAAGTTTACCA
          CTTGTTGGCCGCAACCCACAATGTGGAGAGTTAATTGAACGATAAGTTCGCTACGCATTG
          CCTACGGGGCGAAAACCGGACTAGTCGGAATTGGCATCGCCTTGATTCCACGACGCTTCA
          ACCTCGGGAAGAAAGCTGTGCTAGCTGAAACTGGCGTATCCTCGAGTTCACGCCGTTACG
          GCACCCGGGTTCTTAGGAAAGCGCGCGGGGCTAATTTCGGTGGTCGTTACCTACCCGGTG
          ACTGTAGATCAAGAGGAAGTAAGTTCATTGCAAGTACCAATCTTACCGTATAGAAGGATC

          CACTGTTTAGGAAAGGTAAATATTGGAGCCCAGTCAGCGTATGGACCTATAACGCTATAG
          TGCTGTCGGGAATGACGAAGAATCAACGTTTTATTAGAGAACGGCTTCTTACTCGTACCG
          TCCCTTCCTGGCCCCCCGAGTATGCGAGAGCGCACTCACCCTGGTCCCTTCTGTTTTCCA
          ATATATCCACCAAAACCTCGAATTAGCGTAAGGTCCCTACACAATCCCCTAGACGTAAAA
          TTCATCTGAGTGAAGTTTAGGGCAAGACCCGAATCTTTCAATGGACCTTCAATCGCAGTG
          TTCATCTGAGTGAAGTTTAGAGCAAGTCCCGAATCCTTCAATGGCCCCTCAATCGAAGTG
          GACACTTGAGCGCTTCTTAGCACCAACCTTGGACCTTGATGTAAACTCGTGTCATATCCG
          AGCCGAGGGCATTCCACCGTAGTAAAGGTAAGGCTCGTACGGCTTTATTTGTCTCTATCA

          GAGGTCTTCTTGCAGTGTTGTCGTCACCTGAGGTGCAGAAACCAGTGTCTAAAACGGATC
          GTGTCCTTGATGCCAAATAGTTATCACGAGAACTGCAGTAATCACTGCCTGCGGAGGACA
          GATTATCTGACACGGTAAAGGCTCTACGCCGCTAGTAGAAGGCATGACTCGAGATGGGAG
          AACCGAAACGCATGTCACCGAATCCATTAAGGAAACGGCGCGTAATTCCCGCATACAACA
          GTCCGTAACACGCAGCAAGCGCGCCGCCGGCTTAACAGTAAGTCTTACTAGACACAAGAG
          GTCCTAAACACGCAACGAACTCGTCGCCGGTCTAATAGCAAATAGAAATAGATGCAAGAG
          GTTATGCGCGTACGAAGGGGATCTTACCTATGCAGCTAAGAGAACGATTACTTGTGAGCG
          ACCCCTGAATTACAGAGAAATCCCCGCGCTAATGATTGATACAGTTGCCAATCCCGGACG

          GTCGTGCTCCAGTCAGCACAAACGGCCGTGGATTAGCCGGTAATTCCAGTCCGGCCACTG
          GCCGTATTTTGTCGGGCTTCTGTAACAGTGTACTAGTGGTCCTGTCCAACTTAATAGCTG
          GTTAGGTCCCGTTAGTCACGTGTGTCCGCGGATCGCTTGGCTTATGTAAAATGATAACAA
          ATCACACTCCTGCAGGTAGGAGAGATGGCGGACCGGCTGGCAGCTTAGACCTCGTCAGAC
          GTTTGGCTAGTACAACGATAATGGACAGTGAGGTGGCTACTTCTTACAGTCAGGCTGGGA
          GCTAGGCCAGACGGTTACCAATGGGCCGCGAGGTGGCCATTCCTTATGTTCATGCTGGGG
          CCCAAGTTCTAGTCATGTTAAATACTACCGAAAAAGGAAATGCTCCTATACCCGGAAGCA
          GCTAAGTCCTCATAAACTAGCATCACGGTGAAACGGAGAGGTGACTTCGTGTGCGGACGA

          ACTAGCGATCACCATGCCGCGCCGGGCGCGCGTAGTCGCTGGATTACTCCCTAGCATTAG
          ACAGTTAACCGCCCTTTCGCGTCGGTCTTGGCCAGGCGTTGAATTGCGTATTATTTGTAG
          ATCAGCAGGAATCCTCTCGCGTAAGTATTATGTTGTCATAGGCGCCTGTAATAACAAGGA
          AATACCTACAACTTTTTCGTCTCACCATTTCTTAGCTGAAGGATCAATACTCAAAATAAG
          GCCTACTCAGGCCCCACGGTATAAATAGTCAGCAGACTCTATAGAAGATCTCAGTTCCAC
          GCCTACGCTGGTCCAAGGGGATGAACGGACTGTAGACTTTACAAACCGTCTCCGTTCTAC
          GTCGCTTCTTATTGCTCGGTGAGACTAATTCCAATTTTTCAGATGCGTCCATGAGTCCAA
          ATCATATCTCATCTTCTGGCGTCCATATTTCGAAATCGATGTAGCCATCTTAGCTTGTAC

          AGGCGGCTACCGAAAGGTCATTAAATTCGAATTTAAACAATGACAACCATAAGGAAGGAT
          GGTTGTCTACGGAAAGGCTATGATCTCTTGGCTTACATAGTGGTAACTATTAAAACTTAT
          CGATACATCAGGGAGAGCCGTGGCCGCCTGCCCAACATCTAAGTAATTGTGAGGATGAAC
          CGATAGTAGCAAATAGAATAGCGTCTATAAACATACCTGACGACGTGCCCCCATGGGGAT
          CGGTAGATGCGACTAGGACACAGGTATCCAGCACAATGGTCGCGAGTCATGAATCCCGAA
          TGGCGACTACGTCGTGAATCCAGCTATCCAGCACAATAGTCGCTAGTCATGAATCCCGAA
          GAGAGGAAATAAACATAACGCAGTTACTACGCTTTGAGGACGGTTCGTCCACATTTAGCT
          TGAGGGACTTTAACAGATTGTAACCGCTTGAATCTACGGGAGCGAATCGTGCATTTGTGT

          AATGGGGTTTTCGAACCTCATGTGCGGCCCTTGAGTTTAGTGGAATTGCTTGCCCAATCG
          TGAGGGGTTTTCGGACTTCGTGCATGCTACTTGGGTCCCCTCGGAATGCAAGCCTGACGG
          CGAGGGGTACGTTCGGTATATGCATACTATCGAGCCTCGGACGCACTCCCTGCTACATCG
          TCCAGTGCATGTCCAATTTCCACGTTAACAAAGGGAATGACTGTGACAATCGGGCGTAAG
          TGCGTGCCATTTTGACGTCAGGTAATTCAGGGCTATGCGGTCTGATAACATCGTGAGAAG
          TGCGCGCTATTCTTACGTCGCGTAACCGAGAGCTGTGCGGTCCGACAGCATCGTTGGTAG
          ATTCGGCTGTCTCCTCCTTATTGGAATCTTGCTGGTGAGGTAGTGCTGCCTCATTAATTG
          ATGGAAATAACATTGTTCCATAGATATCCTCTATATCCGGCGTGGGTACCTTCTCTTACC

          AGGTTTGGGCTTGAACAGAAGTCGTCGAATCAACCGACGGAGCCTCTTAGGTTCCTGAAA
          AGGTCTGATCTGTATTTCCGGATTAAGGATAGATCGACGGGGCTCTCGAGGTCCCCCGTA
          AAGCCAGACGCTGGTTGACAATTGGTGGTCTCACTGCCGGATTTCCTATCATCCTTGGAC
          AGAGTGACACCTATACCCTATTAGGTCGATGTCCTCACGAGTATCTTCTAAACATAATAG
          ATGCTGAATTTAGAATATTTTCGAGCGGACGCACTCGGAGGACACGTTGTCTAGCCGTCG
          ACACTAAATTTAGAGTCGCGTTGAGCGGACGTACCCTGAGGACATATCATATCGTCTTCG
          AAGCGAGCCCAACGTCCTCCATACAACGATTAACTGATACTGACCCTTGCCCCAAATCTA
          ACGGATGCCACGCCGGAACATATCAAAGTTTCCTCGTTAGAGGAGACTGCATGATTGTTC

          GGCTGACCAGCCCAATTCGGAGAAATGCGGAACTCGACTCGGCCAAACTGGAAGGAAAAC
          GACTGCCTAGACGGATCCGAAGAATTTCAATATCTGACACGTATGAGCACTGGGTAACCG
          GCATGGCTACTGCCGTCCTATCATACGTGATACCTGCTTCAACCAGTTATCGGATAGGCC
          GGGTAATCAATGGAATAGGACTATTCGCAGTGTTATGGATATCCGAGCGTCAATTGGTAC
          GACTGTCAATGCGGTACATAGCACCCGGGATAGCATAGCACGCATACCTGACCTAAGTTT
          GATCGCCAACGGGGCACATAGCATCCGGATTATCATATCACGCATTTCTGATCTAAGTCC
          GGCCATACATAAGGGTGTGGTTAGCAACAATCTCTGGCCGCGGATAAGACCCTCCCAAGC
          GTAACGCTTCCTGTCCCTCTGCCTTCGGCGAATCCGACCTCCCTAAAGTTGGATCGAGTG

          CTCGACTCGGACGATTGCCTGACACCATGGGTTACTGTCC
          CCAATTGCGCTTGGTCGGTTAGAGCCAAGGCTCCTTCTTC
          TCGCACGTAGATGATCTTCTGACATGGTCTGCATCTGCTA
          TAGCGGGCACTTAATCTTGTGTCCATACATACCATGTCGA
          TGAATACTATATTACTACCTGGCGCGGCATGCACCCATCG
          TGAATAGTGCATCACCACCTGGCGCAGTACGTTCCCCTCG
          TTCCAGTTACACAGTTCCATAACGTGACTTAATCTATTTA
          CGAGTTGTACCGATTTACGTATTGCTCGATGTGGCAGCAT

