 8 1000
t1        GTACAGTGGGCTAGATCGGAGCATAATGTAACTGTATGGCACGCGCTATTACGGAGTTGA
t2        TGACGACGGATCCACCCGGGGTATCACGGAACTATTCAGTGCCCTGTATTACGTCGCCCG
t3        TTACGACGCGTCTGTTCAAAGCATTATGTGATTGTATCACACACAGTATAACGAAGCTTA
t4        TGATGACCAGGTGGCTTGCACCTAGGCCGGACCGTGATGTGGTCGGCATTGCCATACCTG
t5        GTATGCATGCTATGGCCGGTCTTGTAGATGGTCGACACGCGATCCACCCCAAATGACCCT
t6        CGATGCTCGACCTCATTGGCACCGCAAAAGACAGGCAAACGGTTCGTCTTAGGAGCCGCA
t7        GCACGTTCTCTACCATGAAGCTGGAAGGTCCCGGGCGGGTAGGCCGATGCGGGTTTATTA
t8        GCACGTTCCCTACAATAGAGCTGGAAGGCTATGGGTGGGTCGGCCGATACGGGTACCTTA

          ACAGGAAGCACCACTTGTACCTAGCATGCAATTTAAGTGAGGAAGCCAACGTGGAAGCGC
          CCAGCTAGCAAAACTCATGTCTATTGTGTAGTCTAAGAGAAGAGGTCGCCGCACGTAGGC
          TCAGCTAGCACAACTTAAACCTACTGCCTCATTTTAGTGAAAAAACTGCCGTGCATAAGC
          AGAACTGCTGCATCGCACGGCTGCTGCTTAGTGCAAGTAGAGATTTCGGGATGAACTGAC
          CTATTCAGCACGACCCCCCCTGTATGCGACACAATCGCAAGATGGTATGCTCGGATCCTC
          CCATCTAGTGACCTACCCCCTCCCCATATCGCTAGGGAAAATGGGTTAACGCAAAGTCAT
          TCGGTGCATACCATATGTCTTTTTTGCATGTGTCTTTGGAGCAGGTTATTCTAATCGGAA
          CCGGTATATACACAGCGCTCTACCGAAGTGTGAGGTGAAAATGGATTGCTAAAATCGGAA

          CTCACCAAGCTGCGGTCCCGCGTACTCGTCGTCATTATTCGTTACCACTACTGGCAGCGA
          CCTGCCAGACTCCAACCTTAGGCACCCATAGCTACTGGCATCGATTACTGCTAGCGGTGA
          TCTACCAGATTGTAGCTCCGCACACTCGTAGTCACCACTGGCGATCTTTGCTGGAGGCGG
          TTCCCACGTCACCGGCCCGGAAACTCGGCCGTCTCTAACAGGGTTTTTTAGGGCCCCTAA
          TCTTATAGACCGGCGCCCCATGCGTCTGCGAGCCGTAGCGAATCTTACTGGAAACGAACG
          CTCTCCAACCCGTTACCCTGTATGTTTGCGAGATACAATGCGCCTAGTTGGAGACTGCTA
          CCCACCGGCTACAAGGTCAGTCTCATTTAGTGTCGCGCTTGAATGTATCGGGATTTCCCG
          CTGATAGGCCCCCAGATATGTATTATTTAGAGTCGCGGTTGAACATACCGGGAACTTTTA

          GCGACACCAGACGGATACACATACCAATGAAGTCATCGGGGAGATCTGCCTTTGCTTTTT
          GCATTACCGGCCTGGTATGTTTCCCGACTGAATGGCGAGGAAGCTTAGCTGACGCTTTTT
          GTACTACTAGACCGATATACGTCGCAATTTAACGATCACGGTGATTAGTTAATGTCCCCT
          GCGGTCTCGGAACAACGCATTTTTCTACTTGGCACGAAGTAACAGCGGCAGATCCCTCCT
          TCCTAAACAGCTTGTCGAGCTCTCCGCCTTATAGTCACGGGGCCTCATTCACTTTTTTCT
          CGACAATTGAACTGACGCGCCTACCATCTATACGCCAAGGGACACTATACCGTCTCTCCC
          CCTCGCTTCAACCGGCTGGATTTCCAACCTTTTACTCTGAATTCAGGGTTGATATGCGTA
          ACCGGCTACAGCTGGCTGGATCTCTAGCCTTATACCCTGGACTAAGGGCTGATATTCGTA

          CTTACACATAAAGATAATTATTCGTTAATGGGTAGTTGACGCGCTCCTATCCTAGGTTGA
          TCTTTGCAAAAAGGCGGTTACCCATCTGTGGACAGCTGACGCGTTAGTATACTAGGTAAA
          TGTCTGCAAAAGAATAGTTGCTCGTCGGTGAGTGGATGACGCGCTGTTACATTAGGTGGA
          CGTGTACACACATATAGTAGTCCTACAGCCAGCGGCAGGCGCGCTACGCAACCAGTTCAG
          TCTTCGCGGCCTATAGTTGAACTACCATGCTTGGGTCTAGGAGCTATCCACTTAATTCAC
          TGGCCGCACCTCGAAGGCAGACCTTATAATAAGGATGCCAGCGCTACTCCACAAGCTACC
          TAGAATGTAGAGCGTGAAATCCACCCTATGTGCAAGGGCGGAAGAAATCTTCCAGCCTCG
          AGTCAAGTAAAGTGTGAAATCTGCCCTGTATGCAAGTGGGGAGAAGATATTCTATTTTCA

          GATCACCAGCTCGCCAGAAGCTCTCACCGCGCTATTCGATATTGAGTCATCGGAACGAGT
          CACGACCAGTCCGCGGGCCAAATCCACGCCGACGTTCGATATGAGGTTCCCCGGATGAGC
          CGTTTCGACCCGGAGAGAGGGGCTTACTCTTACGTTGGATTTTAGGCTACCCGACCGAGC
          AATAGCCAACAACGAAGAAAAATTAAACCAGATGTGTGACACCTAAGTCACGAGATACGC
          ACTACCCGCACGTTAGAGGAGTATCGTTCGAACAATATATTGAACTTCTTTCAGGTCAGT
          ATTTATCGTATGTTAGCTATAGTTCGACCTGGCGATCCGACCCATCTAGCTTGAATAAAT
          GGATGGCGTTCACCGGGATAGGAGACGCGATATGTTCGGCATTCCCATTTCGGCACGAAC
          GAGTGACGCGTACTAGGATAGGAGGCGTGATATATGCTACATATCCTCTTTGGGACGAAC

          ACATCATTGTGGTATATAATTACCCACACCGGACATCATAAACACTGTAGGGAAATAGAA
          GGATCGCTTTGCTAGATATTTTCCTACATTGGAAACCATCAATACTACATGGGCAAGGAG
          AGATCGCTCTGAAAGGCGTTCATCCATTTTGAATACTATAAAGACCGCAAGGACGGAGGG
          GAATCGTCCGAATCCACTTACACCCACGTAAGGTACCTCTATCACTTCCTGTTGGGGCAA
          AAACTGTCCTTAAACACTTATATATAGTTGGGCCGTCTGATATGCTGATTGGCGAAAAGA
          TACCTATTCCGGGACGTTTGCCAATAGCACGGGCCTTTTGTCTGTTGGTTGGCAAGGATA
          AAGTAATTCATAAGAATTGGTATTAGTCTCAGTTACTTCCAGCAAAGTAACGAAAGAGTC
          AACCGATCCGTAGGAATCAGAATAGGCCTTAGTGATTTTCAACAAAGTAACGAGGGAGTT

          TATGGTCATCAGCGGGCAACTCTGTAACGCTGTCGCCGGTATGTACGTTCGCGGGGGATT
          CACGGTCGTACGCGAGCAATCTTGTAACGTACCCGCCAGTACTTACGTTCGTGGGAACTC
          TACAGTAAAAAGCGGGGGGCCTTGTAACGACTTAGCTGATACATACGTTCGCGGTGGCTC
          GACAGCAGTGAGCACCTAATTGCGCTTCGTTATTGGTATTGCGCACGCGCGCTGAAGCGC
          CATATGTCAACGTTAGTACCCATGTAGTAGTCTGGCAGGCGCCGGTGTATACTAAGGTTA
          CTCGCCTATTCATGAATACACCTATTGTCTTTTGAAAGAAGTACGCACCCGCTCGAGTTT
          TTAGCCCATGATCGCTTAAAAAAAATACGGCGTGGCCGGTGCGCACGTTCGGTGAAATGC
          ATAGACTAAAATCGATTAGCCCAGATATGACATCGTCGGCGCGCCCGTGTGCTGAAATGC

          ACCCCTCCGGGTCGTGCGAAATGAATCACTCCAATTCTTCAACGCCGTTAGATTCCCCCT
          ATCCCTTTGGGGTGCCTGAAGGGAATTAATTCAAGTACGTGACCAAATTAGTTTCCCCCT
          TTTTTTTCGCGGAACGAGAAATCAATTAATTTGAGGACGCAGCGAGCTTAAGTTTCCCAC
          GACTCGCTAGAGAATACAGACTGGTTTCCCTAAGTTGTATGGCAATACAAAGGAACCTGC
          GACCTGGTTCGGGTCTCACATAGCACATCTACCGTTAAGGACTGATATTCGTCAGCATAC
          GGCCTCGTAAGGCGGCACACCAGCACAACTTTCGCCGAGGACCAAAGCTGGTCATCCCCC
          CTATTAGCACGCAGTTTATACGGAGCAGCCGTGGCCCTCTGTGGCCGCGCACACCTTGCT
          GCATTAGCTTGAAATTTGTACGGAGTAGCTGCGCATCTCTGTGGTCACGCTCACCCTATT

          GTATCCCTACCCTGCATAGTACTGATCCCATCTTGCAGACACCAGATGGTGAGTTGGATA
          ATATTCCTACCCTTCATAATATTGATTGAAAACTGCCTTTATCGTTCGACGAGTCGAATA
          GGACATCCATTCTTGAGATTATGCAATGAAAAACGCATACATAATACTGTGTGACAATTC
          TTCCCAGCATCTCTTACCCCATCATCAATAATAAGTGTATACGGGATCCGCGATAAATTG
          CGGGTTGTGACGCGGAGACAATGGTCCGATGTTCATTTGACTAAAACAATGAGCCGTTGC
          GCGGAATCGACGAGCCGTCTTTAGGCCGCCGTCGGCTTGCTGACCTTCGCGTGCCGACCT
          GTACCCAAACGCAATAGATAGATCACCGGGGCTCCGGTAATTAAGGGCAGTAGTCCTGAA
          GGATATAAGCGCAATAAATGGACAATCGCGGCTCTAAATATTTATTGTAGGAGCCCTAAA

          CGTGGTAACAGAGAGACCTGATCTCATTTCATAGGAGAAGATCATGCTGTGGCTTACTCG
          TGGGGCAGCTAGAAGGCTTGACCACATTACATAAGAAAGAATCATACTGTTGCATATGTA
          CAGGGAAACCAGTAGGCCTGACCATATTACATAGGATACAAGTACGTTGATCCTTCTGTG
          CACGAAATTTGGATGACTTGGTAGTCACATGAAAGATAAAAATTCGCCGTTACCCTTCGA
          CACGATACTAAACAACTTTAGCACTACCGGCCTAGTGACTCGTATTCTGAACCGCGCTCG
          TTCTTCAACCAGAAATTTCCATAATACGAGCTCAGTAAATCTCTTATAATATTTCCCCTA
          CATTGCGATCGAAATCACGCTGACTATCATCATCACTCACTCTAAACCGTCCTCTTTCTA
          TATTGCAACTCAGACGATGCCGACTTTCATCGTCACACACATTTAACCGTCCATTCTCTA

          CCAGTTGATGACTCGTGTAAGGAGTACATGCGTACTGTGCTAAATAAGTCGCCCGTTCAG
          TCGGGTTAGGAACCGTGTAAGGGTCAACCGCGAACTGCGCTGAGTAATTAAATTGATCAG
          TCGAGCTACGCTCAGTGTTAGGAGTAGCTCCGTGCGGGCCTTACTTAATAGCTAGACCGG
          TGAGGCCATGGTTTGCGTCCGGAGTAGCTGCACTTCGCGTCGCCCAAAAGGTCTGGTTGG
          TTGTATCGCGCTTCACTCCCGAAGAAGTCCGCGATTGCATTGACCCGGTGACGTAGCATG
          ATCCTCAGTGTCCCTCGCCCTGACAGGTTTGTGTTACCACAGATTCGGTGCTAAAGTATT
          CAGAACCACAACAATTATACTTGGGGACAAGAAGCCGCTTTCATCGAGTAGGTCGATCAG
          CTGAACCACGACAATTATACTCGGAGTCACAAGGCCGCTTTTAACGAGACGTTTATTCAG

          GATAATCCTTTTTAGCAGTTCGTTTCTAAAACCAGCTCTGGGTCATCACCGACTGATCGA
          GCCAACCGTGCTTAGCACTCCGTTTCGTAAACTAGACCGGGCTATTCGCCGTTTCCCCGA
          GCCAGCCGAGTCTAGCCGCTATGTACATTCATTAGATCAGGGTGACCGCAGTCTGGCCAA
          CAATGTCGCGCTTAACGACTCTTCAGGGAAATTAAATCCGAATTATCATCGCTTTCAGGA
          CGAACTGGTAGTCTGGGGTTAATCTCGTCAAAGCATTATGGTCAACAGCCGGCCATATAA
          CATACTGGTGGTCCTCAGTTAATATTATCAAGACTCTGAGGCCTAACGTCGCATGGGTAA
          CAGTATAAAGTTGATCTGTCAGTTACAAACGACTATCAGCGACTGTTTACGGTCGAAAAT
          CAGTATAGAGTCAACCAGTCAGTTGCATACGATTATTAAGCACTAATCATTGTTTAACAT

          CGTAGCTACTACAGTCGAAGAACAGGCACAGAGAGTTCCATTACCAAGGCTGTGTTACGT
          TGCAGCGTCTACAGTCGGGGACCCGGCACTAAGAAATTCATCGTCCCGGTTGAGCTGGGT
          TGTAGTGACTACTGCTGCGGAATTGGCACAGCAAAATCCAGCACTATGGTGGCGTTGGGT
          AGCACTCAGTGTACCAGAGAAACGGGGACTGAAGCACCTATACGATCTGTGGCATTATGC
          CTCGCGCATGTCACTGAAAACCCTGGCCAAGAGGTACCCTTCAGTTCTCTCGGGCCGAGC
          TCGCTACAAACTTGCGGCGATACGGACTGCGCGAAATCTAATAGCATCCGCGCGCTGGTT
          AGCTGCCCAAGGGCTCGGTAGGCAGGTGCAGTCAGTTTGGACGGTACTGAAATTAAAAGT
          CGCTACCTGAGATCCGGATAGGCAGGCCCTGCCAAGTTTTCCGATATTAAGATCACAAGC

          GGACCCATCGCGGAAGGGAAAAGTAGCCAAGTTAGGGAGGTGGCTGCTCGTATTACACGC
          GGACTGGACATGAGAGGCCAGTATAGTAAGGTTAGGACCGGGAATGATTCGATCGCACGT
          GGACCGGTCCTGCGGGGTCAGGATGGTTTGTCTTGTGTCGTGATTAACCCTGTTACTCAC
          CGATCACTCGCGGAAAGACTGCCTGAGCCGCTCGTCCCTGCGACACTCAACCTTACGACG
          GGACCATCGTCCCCCGATAGTGAGGGTCGGGTTCGGACTTTGATTATTTATACCGTCGCG
          GGCACGCGTGTATTCCACAGCATGGGGCCAGCTGCGGTCTAGGCTCCCCTCTAAGCCGCG
          TAACTGCTAAACCGCCCCCGCATTGGTTTAGGGAGGTGGTAAGCTCTCTGCTTAGTCACT
          TAACTATTAATTTGCTCCCCAGTTGGTTTAGGGAGCTGTAGCGTTCTCCGTTTGCCTATC

          TCCCTAGAATCGCCTCGAATCGGACCATCTCGCAACAGTGTTGTTCCATGTGATTCAGTG
          TCACTAGGACTGCTAGGGATAGGACTATTTCATGATAGGGTGGTCATACTTGGTCCAGTG
          CCTCTGGAATTGCCAACGATAGGATTATCTGATGATGGGACTGTCCCGTGCAATTGTGCG
          ATCTTGTGATTGAACGGAATGGGGTGCTTTCGCGGCAGTAACGACTGTTAAAGTTCAGTG
          TGTAGATAGCACCTCGGGGATATACCTACCTATTACGAGCATACCTAATGATCCGTGGCA
          TCCGTGAGCCCGCTCGGAAAGGGATACCTTAACAAACTAAGCACCATCTATTACATGGCG
          GAATCCAAGAATCTCAGATGGGCTTTATACCTTGGCTGTGGAATCCAAAGTCAGTTTTTA
          GAATCTAAAAATCTCGGATGGGCTTTGTACCTCGGCTGCGGTAATCAAAACTGGCTTTCA

          AAAATAGTAACAAAATCACTATGTGGGAACCCAGGAGCAG
          CCGAGGGAAATGAGAATTCTCTGCAAGGACACAGAAGCTG
          GGGAGGGAAACGAGAGTATTACGAAAGGATACAGAAGATG
          AGTATGAGGCCGGATCCGCCTTTTGTGATCATCAGATCCA
          GCCGTAGGATTATGACATCACAGACGCCAGGAGGGTTCTG
          AAGCCGGGAATGAGACACCCCTGCAGTCCCGCCACGTCTT
          AAGATCAAGGCCCAGTCTGCTTGACCCCTAAAAGGTACGA
          AAGACCAGGGCTCGGCCTCCCCGACCACAACGAAGTGAGA

