 8 1000
t1        CGACTAATTGTGGAGGGAAGCAGGGCAGTTCGCTATGATCCCGTGACGCGTGGCCACGAT
t2        CGACTGATCGTGGAGGGAAGAAGGGCAGTTCGCTATGATCCCGTGATCCGTGGTCACGAT
t3        TCATTTGACGTGGAAGAAGGACGAATGGGAGATTGGGGTACCACGACCCAAGGCCGTAGA
t4        GAATTAGTCGTAGCATAATACCGAACAGACAGTTATGATACCGCGGGCCTCATCCTGCGA
t5        CCTCGTGCTTTGAGCAAAGGACGGACAGCTCGCTATAACCATCCACGTCATGGTGTAGGG
t6        TAAACAGTTATGAGAGTCGGCTGAGGATTAGCGCTTGTTTTGGGGTATCGCGGGCGCGGA
t7        TAATTTGTGGTGAGAGCAATATGGATACCTGTTCCTCCCTTTACGTTCTCCGAAATATGG
t8        TTAACTGACGGAGTAGTCCAATAGCCTCCGGGTGTCCGCGGTAAGGATCTCATTTTGGGG

          TGAGCCGCAAGGACTACCTTACTGCTAGTTGATCCACTTCAGATCGGGCAACGAGGAGGG
          TGAGCCGCAAGGACTCTCTAACTGCAAGGTGACCCGCTTCAGATCGGGCATCGAGGAGGG
          TGGGGTGATGGAATTAAGCTGGAAGACGAACACGCGATCATGCACATGACCTGCAGCGAA
          TGCGTTGCAAGAGCTCCGTCACATCCACGGTGCTCGATATTGCCCACCAAACGGGGAAGA
          AGAGTAGTAGAGGGCGTGCCAAGGCGGCGACTCACGGTCCCGCCTGCGCAACGAGGAGGG
          AGGAGCGTAGGACTCATCCATTTGTGACAGCTTACGATCCCGATCGTATCACGAGGGGAG
          CGCGTAGTGTAAAGCACGCATTTGTTTTGGTTTCCAACCCCTTTTATGGGCTCATTGAGA
          TGGGCGAGGTTGCCCGCCTGATCGAGGAGGGCGTATGAAAATTCTCTATATGTAATAAGT

          GCGCTGAGCGGGACGTTTCTACCTGATCCATCTTAAACCTCGGCTTTGCCAATTGAAAGT
          ATGCTGAGCGGGACGTTTCTACATGATCCATCTCCAACACCGGTTCTGCCAATCGATAGT
          GCACCGGGGGATGGGCCTCCTAGTAACTATCCTCCATCATGGGCCCGGCTCTTCAACATT
          GTGCCGGAGGACAATTTTGTGCACAGTCTGGCACGTAAACGGGCACTGTAAACCGACCGA
          ACGCTATGCGTTAATCTTGTCCACGATCGGTCTCTAACACGGGCAATATCAATCGCATAC
          GTGTCGGAAATTACTACTCTCCGCAATCGGTCTTCCGTATAGGCCTTACGATCCGAGCGT
          CCGTCATGGCTATCTCTCCTCCGGTAAAGATTGGTTGGGTTGGTATTAAGTTCCCAATAA
          TAATCAAAAACCCTCCGTGCTGACCTACTGCTAAGAATATGTGTATCGTGGATCTTATCA

          GATGCAGAAGTCCCAAATGATGTTTCTGGTCGACGGTAACCTGTATTGTCACCCCCCTAG
          GACACAGAAGTACCAAATGGACTTCCTGGTCGACGGTAATCGGCAATGTCACACCCCTAG
          AGAATGGTCAAGCGGGGCGACCCCTTAGGTCTATAGCCCTAGATGATGATATCTCTCTAG
          CATATAGAGAAGTCTCGAAGATACACTGGTTTAAGGGGGTTAATGATCCAACTGGCTTGG
          ATGATAGGAAGCCAGCATAGTCTATCAGATTCACGTTAACGGGAGGCCCGATTCCCTTAA
          TGTCCAAACAAACTTCTTGTTTTTTTAGGCCCACGGTAGCAATTAAATACAATTTCCTAA
          CAGAACGCTATTTGAGTTAGCTCCGAAGTGCAACGGCGTATCGCGTCGTCACCGTTCGGA
          AAAGCGGAACGCGAGCGAATCGCTCTCGCTTGGTATTGTGTTTAACTATAGTGAGTTGGA

          ATTTTCTCCAGACGTAATCCCGTACGTCGCACGTAGTTCGGTAGATCCCCGGACAGTGAT
          ACTTTCTTCGGACGTAATCCAGTACATCACACGTAGTTCAGGGGATCCTCGAATAGTGAT
          CACGAACGCGAGCTAGCGCCATCACCTGATGGGGGGCTTTCCGAATTTCTGCATAAAAAC
          TATGCCCGGGAGCTTTGATTTGCATTCGATACAGATTCCAAAAGTCCTATGGGAAATGAT
          GCTGCTTGCGGGTGCTATTCCCTGCTCGATTCAGCCTTGGAGCGCGCCTCACATAGCGAT
          CCCATCAGCACGTGCAGGTTTTTATTCATCTCGGCACTTGAGGGGCCCTAAACTGGGGCT
          CCAGAAAATAAGTGTTGGTTGATACTCCCCGTCGGTATGCCCAGCCTACTAACCTACGGC
          AATGTTGGTAAATGTCCATCGCAATAAGGCCTTGGGTTACTAGGCTTCGCTTCCTGTTAC

          TATGCTGGAACCCGATTGAATAGGGGCTGGTTGCAACCTATTACCACTGTGTTTGCTGGG
          TGTGCTGGAACCCGAATGAATAGGGTCTGGTTGCATCTTGTTACCACTGTGTTCGCTTGG
          CGTAATAGATCCCTTACGCACCGAAATGGACGAAAATCTACCACTCTTACGCTTTTAGGG
          AGCGTATTAATTCGTCCGTTCAGGAATAAATCGTCAGCCCTTGCGACACAGCGTGACGGA
          TGCAGTCGGAGACGACCGTTGCTCTGTGTGTAGTCAGATCCAACAACTCTTCGTGCTATA
          CGTTGTCGTACGCGTGTGTACCGTAGCGGACCACCAGATGTAATCACTCCTTATGATGTG
          CATTACCGCCGTGCGCTGTGGTCGCATCGATTGCCGGGGCTCATGGCGCTTCTCGTAAGC
          CTCTGATGACCCCAGGACAGACATTGTAATTTGTAAACTCCATATTCGATTCTCGTTGGT

          CAAGGGCCCGGCGGTGGCATCTGGACATGAGTCACCAGGGCTCCCTCCACGGTCAGTTTA
          CGTGGGCCCGGCGCTGGCGCGTGCAAACGAGTCTTCAGGGCTTCCTCCCCGGTCACTTTA
          TAGACCATTCCTGCTGAAGTGTGGTAGAGTATTTGTGGTGTTACTCTTTCGAACACGCCA
          CATACGGCCGCTCGTGACGCGCAGGGACTTGTTCATCGGGTCGTCTATTGGCTATCTTCA
          CGTATCTCCGCCGGTGATCAATAGTCTCGAGTGCACAAGGCCCACCCGTTGCGCACCCCA
          CAAGCGACCTACGGCGATACGTGGCAATTAGCCCGCCGCAATCCTTTGTTGATTGCTCTG
          TAGGAATATACACTTGACTCTAAAGCGGGAATTCATAAGATTCCTCTCCGAATTCTTTCA
          GGGGCAACCGCACAGCATAGCCAGAGACGCAAATTTGAAGTGCCTTTCCAGCGCACTCGC

          TGTCACGTCATAGAGCACCCGAACTAATGTCAGTGTCATGAGTAACCGTGGGTGGCAGCC
          TGTCGCGTCATAGAGCACCCAAAATAATGTCACTGTCACGAGCAACCGTGGGTGGCAGCC
          AGTCTCCGCCTCTTTTTGAGCAAGCCAAAAGTAACTCACGGATGTCGGCGGATGCCATTT
          AGGCGTGACTAGCTGTACCGATAGACGAGGCGGATACTGGACCTTGCACGAGCGTAGAAC
          GGTTTTACCCCCACGCCTGGCGGACTGGACCGATTTTTTGCACATTCATGGGCACCAACT
          AACCTCTGTACACCGCCCAGCACGCCCAGGTACTCCTCTAAACACGTGTGGGTATCAATC
          AGCGACATAAGGATAATTGTGATATGGTAACCCGGTAGCGGCCAGCTGCGGCAATCACTG
          TGTGGCACACCAGTGATGAGTGTGTTAGGCTCTGCGCTAAGACCTCCTACGTAGACGAGT

          ATCCTGCATGACCGTTTTCTATGCAGCCGTGTAGGCGGTCGGTGATTCTCCAGGGGTCGA
          ATCCTGCCTAACTGTTTTCTATGTAGCTATGTAGAAGGTCGGTGACTCTCCAGAGGCCGA
          GTATCGTATGTTCATGCCCGGACTGTAGCAGTAGTGAGGCAGGAATCGCATACGACTATA
          GTATTTCACGGCCGTCCTTCAACCGTATTTGTTGTGAGGAGGTGACTTAACAGAGGTTTA
          AGGTTGTGTGATTGTCCCCTAAACTGTCAAGTGGGGTGACCGTGGACCTAGATGGATAGG
          GCGAAGTGTAGTTAGGCCATCACTTCTTACATGTAGGGTGAATAGCCCCAAACAACCCTA
          ACGGCTCATGTGTGCGGTATAGCTGCCTATCTCCTAATACCGTGTGCTTAAAAAAATAAT
          GCTTGAATAACTAGTGCTTTTATCATGTGAGCCGCGATACAGTAGACCAGCGTAAATGAC

          ATCGTGTACCCGGGATGACTTACCTTGTGTTATCGCAGATACTCCGCCGAGCCCCCCTGG
          ACCGTGTACTCGGGTTGACTCACCTTGTGTTGTCGCACACACTCCATCGAGGCCCCCTGG
          TAGGTATACCTATATTAATTTGGCCTCCACTGTTGAGCATACAGCGCTGACGTCACTAGC
          CCTGTGTACTCAATACGACTTTGCGCCCACGAAAAAACCTCCTCTACGGCGGATCTCCGT
          CTCGTGAATCTTTATTGACCAGGCAACCATCGGTGAGCACAAATAACGAGCATATTTCTC
          ATCGTTAACTGTTTTTGACCCGGCACTTCTCGATGGAAGGACCTAGATCAAAGCCCACAC
          TACCAACAAGTCGGTAATAACGCCGCATCCGGTCATGTGTATTCCAGTTGAACCGGAAGC
          CATGCGAAGAATCACTGAAGCAACTACTATCGTGGTATCCGGTTGCTGATAATGAACGAT

          GGCAGTATGGCGGTGCCCTGGTATTCCTTCATGGGACACCGAAGCGCACCCCAAGGCTTA
          GGCAGTATGGTCATGCCCTGGCATTTCTTCATGGGGCATCGATCCGCACCACACGGCCTA
          AGGGGGGTTTAAATGTTTAAGTCCGTCTAATTGGAATATAGGCTCAAGCTCGACCGTTGC
          GGCAGCGGAGCGTTACAACGTTACCCTCTCTCTGGACGTGGCCGTACGTTAGGCTATATC
          GGTAAATACGCAGTGTCCGAGTACACTTACGTGAATCGCGATTGGGTGCTCGGACGCTAC
          CGTTAGCTGGTAGCGTCCGAGTGGATTTGGGGGAGATGCGTTTACGCGTCAGTCTGCGAC
          TAGAGGGAAGGCAAGCACCAATACATTCGGGCCGATCGGAGGGGCTATAACAGCCATCCC
          TGTGGAAGAGTGACTACTTCATTTATCTAGGCAAGTCGAGGGCTTCTACTACGGCATAAC

          CCACCATTCACGTCTGATGACTAGGGCGGATAGCTTTAACTGTTGTAGTCTTATCTGACG
          CCACAGTTCACGTCTGATTACTAGGGCGGATAGCTTTAACTGTTGTAATCTTATCTGACG
          CAAGTAATCGGGCTAACTTCCTAGGACGGCCGGCTTAACTCGGTTTAATACTATTCAAAA
          CAGGTATCATCGCCAGACCTGAAGCGTTGTTAGCTTTAATATTTGCAAACTCTATTAAAG
          ATGGAGCCGTCGTCGGGTGTATAGGTCAGCCAGCCTAGAAAGCTCCGAAGCCCGCCACAA
          CAATAGTTAGTGATGCATTAATAAGCAAGTTATTACAAAGCATCACGATTCCCTCTGCGG
          AAGGGACGAGTGCGGGGATGATACATTAACGAATGTTAACCGAGCGGAGACCTCGGGGGG
          TAGGATCGGGAGTGAGTTTGTGCACATAACACGCATTAATAAGCTGAGTACTGCGGAGGA

          ATCCATCTAGGGACGACAACCTCACAAGCATTTCCAGGTCAGAATTCATCTTCGTGTCAC
          GTCCATCTAGGGACGACAGCATCATAAGCGTTTCCAGGTCAGATTTCATCCTCGCGTTAC
          CCTTCCCTAAAAACGGAGACCCGGCGAGCCTAAATAAATCAGATTTCTCCCGGCCCCCCG
          TCTAACCCAGGAGTTGTAAGCTATCTGGTTCAACTTCATCGTGTTTTTACCCTACATCTC
          CACCCCTCTTGGGCCCTAGACTGGTTGGTCCTCATGAACCAGCCCCCTCCCTTATTCGCC
          GCTCATTCTAGGAATGTCGGATGCCAACGGTCGCTACGTCCGGATGGATACCCCCGCACC
          TCTAGCGGAGATTGAGTAAACCGCTGATAATTACCAAACTAGATCCCTCAGCAACACTTC
          CAACGTCCAGGGGCGGTTCTCTGTATCCTTGTGGCGTGACCTACAAGCACGTTGCCTTAC

          AAGCTGAGATAAGGACCCTAAGCAGCATATTCCCAATTAGCGCCGGCACGGAGAAGCGAG
          AGGCTGAGATAAGGATACTAAGCAGCATATTCCCAATTATCGCTGGCACGGAGAAGCGAC
          AAGTTGTGACTCGTCTGTGTAGAATTAGGCACAAAGCCGATGACAGAGCCCGAAACAACA
          CAGGAGCTGCAAGGCTTCAATGCAGGCGACTACGAGCCGGGGCCGGAGAGCCGGGAAATG
          GAGGCGCGGTACGACCACCAAGCGGTAGCCCAGGAGTAGCGATTGATGCATCGAGGCATA
          ACGACTCGAAGTGGTGGCAAGATCTCCGGGCAGAAGCTGGGGGCGAAGAGATAAGCTACT
          GGTGCCCGGTATGACCGTGAAGTAATATATCGAGAAATGACATTAAGGGAATATGGCGTC
          GGCGAGCCGGGCGATTGTTAACTCCACACCCGGGTGCTCATGCGCAGCGATACGGGCGGG

          GGCGAATGTGGGCGTCTTGAGCGCCCGGCTCGTATCTTTAATGTCTACATAAGACAATGC
          GGCGAATATGGATGTCGAGAGCGCCAGGCTAGTATCTTTAATGTCTGCACAAGACGATGC
          AGCGATTATCGGTACCGGGACTGGCCGGTCAGCGCCCACTATACGTGCATAGATGTCCGG
          CGTAGCCTCATGTTCTAAAGCCTCCCAGCTAGAGCCTTTGGCCATACTAAGACAGATTGT
          ATGCATTGCGAGTATAGGGACTGATTGATCGGTGTGTAAAATCCGAAATTAGGAGATTGA
          CGGTAATATGTATAGCGAGAGTAATCTGTCGGCACTCACATAACGAGCTTAGGAGTTCGC
          TTAAACGAGGAGCACAAAAACGACCCGGTCCTTACCCAGGACTTATCTGCCAGGGCTGGT
          TCTGATAGCACACATCAGGGAGGGCCAATCCATATCCCGTCTAGAACGGTTGAATTGAGG

          GACCAAAGGGAATGCGGAGGTTTTCGTGCACCATGGAGCTTCCCGCTTACGGTTTCACTG
          AATCAAAGGGAATGCGGAGGTTTTCGTGCACCACGGAACTTCCCGCTTACGGTTTCACTG
          GTACAGAAGACAGTCGGAGTCCGCCGTGTGGTACGGACGGTGATGTACTTAACAGCACCT
          AAAAAAGTAACTCTTGGTGATTTCCCTATGGAGCGGACCATTTAGTTCTCATCAACATTG
          AAGGTCGCGCTAACCGGATTTTTGCATGCGACGCGGATTATGTCATTAGTAGTGGCTCTG
          GGTCTTGGTTAAACTGGAGTCTCATTTTTACTGCGATACGTGTCGTCCACACCGTCTCCG
          TTCGCGCAGTCGGCTGGACGAAGGTATACATCGTGCACTTCTTCCCCTACAGGGGCGTTG
          TCTTTGGGGGAGACTGAACCACCACCCACGCCGCTGATTATTAAACGTACAGCTATAGAA

          CCCTTTTTCATTACCTACCACCCAGGTATCACACTTCCAA
          CCCTTTTCTATTACTTACCACTCAGGTATAACCGTTCCGA
          CAGCTAGTTATCACTGCCTGCCCAGAGCTCTAAATCATTC
          CTCTGCATTGTCCCTAGCTGCTTAAATGTATCGTTCGCAT
          CGGCTTACCGTAATGAATAGTTTAAAGTCAGTTCTTATGA
          GCGGTCATCGTTGTTCCCGATTCAGGTTAACTATTTGTGA
          ACCTTTTCTCTTACTTTATACTCGAGTTTAAGGACTATGA
          TTATTACTCACTACTTCGGAGCCGGTCCTAGAATTTAGTG

