 8 1000
t1        GATCCAACTAAGCTTTTCTTACCGGTATGGTCTCTTAACCAAAAGATTGGGCATGACCTC
t2        AATCCAACTAAATCCTACTTTTCGTTCAGGCCTCTCAATCGTAAGATAGAGCATGACCCC
t3        GTCCTAACAAGATTCATATTCCCATAATGGATTCATATTCGCGAAATAGGATACGGCCTC
t4        GTCCTGACTAACTCCCTAACCTCTTGATGGGATATAATCCGAGGCATTGGACGTCACCTT
t5        ACGGAAGCAATATGTGAACTTCTCTCACTGACTGTTGGCCGTCAGCAGACTGATAACCCC
t6        AATATGGTTTTTTGTTACCACCTGCTGTCGTCTATCGGTAGTCATATAGGTAGCGCTAAG
t7        GAGTAGGTAAACTCTCAGTGCTTACGAGGGGCACTCCCGTCCAATTTGATAGGTGATCAA
t8        GACTTGATAGCATCTTAGTGCTTACGAGGGGCATTCCCGTCCAACTTAATATGTGATCAA

          TACAAGTCTTCTTATCCTTGCCCGTATTTTCTACTTGCTATAATAATCGAGATCACGGGG
          AACAAGTCTTCTCAGTCCTCCTCGTACTACCTACCCGTTATCACAACTACGATAACGGGG
          ACTCTGTTTTCCTGCTTTAACACCCATCACATCGCTCCACTAATACCGACGGTCACGGAG
          CATACGCCTTTCTATTTCACTACCTATTACTCGACTCAAATCATTATGACGATGACGGGA
          ATCTGGGGCTCTTGGCTCACGCTACATTGCGAGAACCAGTTGTCGCTTGCGAGGGTACAA
          CCTCCGCCCACTCAATTATCCCGTTGCTACGGACAGTTACATCCACCGGCGTGGACTCAG
          TCACGTACTCCCGCACGTCACTCAAAGGGCGTGAACCACACTTCACATTTGATGGCAGAA
          TCACGTAGTCCCCCATGGCATTCATATACTCTGAACCTAACTTCATATGTGATGGCAGAC

          ATCCGGTGAGAATGGAAAGGTACGAAGTAGAAGGACGTAATTAGATTAAGAGCTTCACCG
          ACCCGGTAGGAGTAGAATGTAACGAAGTACAGACGCGTAATAAAATTAAGAACGTCACCG
          CATTAGCTGGACAGATTAGCTACGAAGTAAATACACGCCTAAGGACTAATACCATCATTA
          ACTATAACCAACAGAAAAGTTGCTAGGAACATACACTTATCAGAACGAACAATATCATCA
          GCTGATAAAGGCGAACCCCTGTCCCTGCAAATGCAAGTGGCCAGGGAATGATCACAACCC
          AACAGCATAAAGCGACGCGTGAGTCAATAGATACGCTCGATCGGAATCCGCGGATGAGCC
          GTCCTAAAGGTGTTGAAGCTTTTTGGGAGAAGGTGGTTAACTGGTACGTGCGGTAAGTTT
          GTCTCAGAGGTGCTGAAGCTTGTTGGGAGGACGTGGTTAGCTGGTACGTGTGGAAAGTTA

          GGACGTTGCCACTCTAACTGGCCTCCTCCGCGAATCAGCGGTGTTCATGGCAAAAACCCG
          GGTCGTGGCTATTCTAATTGGCATTCTTTTAGAATCAGCGGTGTTCGCGGGATTCACGTG
          ACGGGTGATGGTCCGAATTGGCGTCTCCGGAAAATTAGGGGCGCCCACGGCGTGTGGGCT
          GGGAGCGACTGTCTCAATCGGCACCCTTTAAGGTTGATAGACTCCTGCGGAAGATAGGTG
          ATCATCCTTTCTAGTTGCCCCGGTGACTCGTAATCAGATTAAAGACCCCCAGGAAGGGCA
          ACAAAACCTCGTTTGCACCCACTTTACTCGTACTTTCGAGTTTGACACGAGAGGAGAGTA
          TTACCTGACCTTCCACACAGTTGTCTCCTGTGGCTAAGCCGTTGGTACGCGTATCTTCTA
          TTTCCTGGCGCTCCACACAGTGGTCTTCCGTGGCAAAGTCGTTGGTACGTGTAATTTACC

          GAATTGTGGCAAAGGTTCATCATCGCTAACATATGCGCTGCCCTCTTTTTCAATTGGAAC
          GGATTGTGGCGGTGGTCCATCGTCGCTTCGATATGTGCCGATCTTCTTTTATATTGGGCC
          GTACGGTAGTAGTACTATACCGAAGACTCAATATGAGTCGACAGTTTAAAGCACTTAGCT
          GCGTGACAACAGCGTTTTATCGCGGATTCAGCATGTGCCAACTTTTTACCGTAATTCGAT
          GAGTGGATGTTCCGACAAATACCTGACGCTAACGGTTCTGTGTTTAGCGAAGCCGCAAAC
          GCGTCCCCGCTATACCAGGCTAAGGCACTTTCCTGCCATGCGCCATACACGACTACGGCC
          GCATACACTTAATGAATCTCTCCGTTTGACCTAGGCCCGGCCGCCGAGCCAGTGCTGAAT
          GACTACCCCAAATGAACTTCCCCATATGACTAAAGCCCGGCCACCCAGCCAGTGTTGGAT

          AGTGATCATGTACTAACTATTGAGACAGACCCAAAGGGATAAACGGAGTGGGGGTCTGCC
          AGTGAACATGCACTGGCTACTGAGATAGGCCCGAGGGGATAAGTGGAGCTGGGGTCTGCC
          GGTGAGTTGACTTTCGCTGCCGTGGTAGTGCTGTAGAGACAAGTAGAGGGACAACTCGCC
          GGTGGAAAAAGTCCGGTTGCCGTGGCAGACTAGAAGAAGTAAGCGGAGCCGCTGTCTGCC
          TATGCCTGCGCCCTAGATGTTGTAATTAGTCCTCTGACTGAAAGTAACAGCTGCCTATTT
          TGTATAGAGTCCACAGTCTTCGGTACGACCTTCGGGTGTAGGTCGGCGCTAGAACTTACA
          ATTGTTTGGACTGTCACGTCCTCGCCAGATTTAGCTCTTTCACCGGGGATCGCCGCAATT
          ATTGTTTGGACAGCGACATCAGCGCCAGATTTAGCTTTTCAATCGGGGATCGCCGTCGTC

          TTCGACGCATGGTGTTACTAGTATCACCATGTGGGTGTATATGTGGCCAATGCGAGCCAC
          TTCGACGAATGGTGCTGCTGATATCCCCAGGTGGGTGTACAAATAGTCACCGTGAACTAC
          AGTAATGCAGGGCATCATCCATATTCATAGGGGCGAACGCAACCCGTTAGATTGAGTTAC
          AGCCGTGCCGAGCGCTGCCCCGACCGATTAGAGGGTAAGCAAACATCTAAACTTATATCC
          CGCGACGCGTGTGGGGGCCCGCGCCACCCGGGATGTAGAATAGAAACCTGCGCACTGCGC
          CGCAACGCCCCGACGAACGTATGGTAAATGAGCAAAAGGCTGATAGATCCTCGTAACAAC
          AATGGTACACGAGGTCGCACATCATAGGCGTAGCGTTTTTGATGCGTTCATATGCTAAAC
          TATGGTCTAGGAGATGGCGCACTACAAGTGTAGATTAAATGATACGTTTCTTTACCAATC

          GCCATCCGATTTATTCGTGTCCACTTAAAGTAGCGAAAGTCCGTGAAAGCACCCTACGGA
          GTCACTCAACTTTTTCGTGTCCACTGAAAGAAGCGAACGTCCGTGAAAGGACCTCATAGC
          TTTATGTGATATACCACCGCTTTCCCGAAATGAGGCGTGGCCTCTAAGGGCCCTCATGAG
          ATTACTCGGCAATTTCCCGATCTTTGGACATGGCGCACGCCCTACAAGGGGCCTTATAGG
          AGATAATCTAAAGCCCATCCACGAAGTGACCGGTCGCCTACCTAGGGAACGGAGCCTGAT
          GCATATCGACATCTATAGTTGTACTGTCACTAGTACCAACGCTAAAGGAACCAGTCGGGC
          GCGGTCCTTTTTTCCTCTTCAATGACTATTCAGAATCTCGACCGCGAAATTGTCTAGATA
          GCCGTTCCTTTCCGCCCTCCAATGACTACCCAGTATTTCTTCCGCGAAATTGTCTAAATA

          GAAACACTCAGGTTCACCATATAATCCGTCTGAGAAGTCTCATTAATTGGAAAGACGACA
          GGAGCCCTCAGGTTAACCATACAACCTGTCCGAGAAGTTTCATTTATGGAAAGATCGACA
          GGAGCCCCCCAGTCGAGAGCACTATGAGTCCGCGAAATTGCATTACTAGGCAAGGTGCCA
          GCAACTCCCCGATTAAGCACATAATCTGAGCCTGAAATCTCCTTTATACATAAGGTGACA
          CCTATTGGCTTGCTAACCACTGGCTCTGCGCGGAAAAACGCTGGATGAGCACAAAGACGT
          AGGTCCATATTGGTCATCATTCTCCAGCCCCGTGCGGGTATCCGAAGGGACTAGTTGCGC
          CGACGTAGCCAACGCGCAACTTAGTTGTTGCGCGACTCGAACTAAGTGTATGATCAGTAT
          AGACGTAACCAACGTGCAATTCACCTGTCGCGCGATTCAAATAGGGTGTACGATCAGCGT

          ATTTCCGCACCCAATGGACACATCCCAAGATGATTGGTTTTATGCCCATCGCCGTGCTGA
          ATCCGTGCACCCAGAGGGCACATCCCAAGGAGATTGGTTTAATGCACATCGCCGTATTGA
          GGCCGTACGACCAGTCGGCATCTTCTTGGATGAATGACTCCCCGCACATCCACATTTCGG
          GCTCGCACGCCCAGCTGGTATATTCCTAGTATATCGATTCTCTGCGATTACACATCTCGG
          GCATGGACCCTATGACAGCTGGCTTACAGATGCCTGCGCCGCAGCATACCTAGTGCCGCA
          ACGAAAGCAGTGCAGTACTGTCCCCCACCCTGTAAATAGTTACGTATGAGCTCCGAGGTC
          ACTACCCCTTTGCACAATCACCTAAATGAATTCCCTCGGTTATATATATCGTAAATCGCT
          ACTACCCCTTTGCACAATCTCCTAAATGGATTTCTTCGGTTATATACATTGGAAACTGTT

          GCTCGCAAGACGAATCACACTTCTGTCCAGTTTGAAAGGAAGCGGTTCAACCTGGGCGAC
          ACCCGCAGGGCGGATTACTCTCTCGTCCAGCCCGAATGGCAGCAACCCAATGCGGCCATC
          ACTCTTTAGTCAGTACAGATATCTGACCGGCCCGAGCGGAAGCAGCCCCTGCCGGCTACT
          GTGCTCCAGTCAGGAGATGATTCTGACCAGCCCGAGCGGGAGCAGTGAGTCGCGGGTAAT
          GCAACTACATGCGTAGAATATTGCTACCAATCTGTTACCGAACGATGTTTCGCAGGTTAA
          GCGTCCTTAAGTGTTAGCATCTTTCATGGTTACGCTGTGGGGCACTATCTTAGAAAAACA
          AGAGACGGTTGATGAGAAACCCCCAGGGTGTCCGTCTCGACTCCGCACCCGACGACTGTA
          ACAGATGACTGGTGAGATACCCCCAGAGTACCGGGCTCGGCACTACACCCTACGAGTGGG

          TGCCCAGGTAGAGTGTATGTTTCGATCTTCTTAAATCTGTGCACATTTGCTGGAATACGT
          TGCGCGGGTAAAACGTATACCTCGTTCTTCATAAGTCTGTGCACATTCGCTGGAAATCTT
          TACGAAGAAGGACTGGAAACTCTCTTCCATATAAGTCACTATACATATGAGTGGCATCGC
          GACGTAGGAAGACTGGAGAGTTTGTCGCTCATAAGACATTACACAGATGCTTGAAATTGC
          TGCAACGGTCGATTAGCTATTGTGATGACAAAGTTAGGTCTATCACTTCTTTTTTGTTGG
          TGCTAAAGCGAGCCGCGTATCACGGCGCTTTTGGTTCCTTCTCCGACTTCAGGTCATTGG
          AACATAAAGGGATTCAGTCTTACGACAGTCAAGTAATTTCATCTACTCTCAGGATACGGT
          AACATAAGGGGATAAAGTCTTACGACAGTTTGTCGCCCTCCTCAACTCTTAGGTCGTGGT

          GTGCGCATGGGATGCGATAAATTTATGTATATAAGCAGTTCCCCTGGATAGTCTAATAAG
          ATGCGCATGTCCTACGATAAACTTACGTAAATAAGCAGTCCCTCTAGATGAGATAATGAA
          GTAACGAATGGCGAGGCCAAATTCACGTATGCCCCTAGTTGTCGCAGAAGGCGCCATACG
          GCGCATGAAGGACAAGAAAAACTTATGTAATAGTGCAGTTCCCGTAGACGGCGTTATACG
          GGTTTCGACGGTGCGTCTGGAGGCATGTAAAGCCCAACTCTATAAGCCTTAACCAGTACA
          GAAAATGCTGGCCTTGACAATTATACAGTTACCCATAGCTTAGGACACTAGAAACCAGCT
          CAACGTGCCAATACGGGTGCGCCCGTATGGTATGGATTTTAATTAGCAACCCCTGATCAG
          CAATGCGCTAATGCTGTTAGGTTCGCATGGTATGGATTTGACCTAGATATCTCTGATGAA

          GGTCATCCAGACTTACGTTTTCAACTTTCCTCTCTTGGCCGCAACGAAAGTGTCGGATAT
          GGCCATCCAGTTTTAATTCTCCAACTTTCCTTTCTTGGACGTAACAAATGTGCCGGCAAC
          GACGACCGTGGCTTTCTATCCTAACTCAAATCAACCGGTCAAAAAGAAAGCGCCGGCCAG
          GACAACTACGACTTCCTGTTCTAACCCACATCCACCGGGCAAGAACAAAGCGTCCACGGG
          ATACACGTAATGTTGTCACCCTACATTATGCTCTCTTAGTGCAGAATTGGCGCCTGTTCA
          AAACTTATATTGGTGCTTTACCATCTAACAGTCAGTGGGTGAGGACTACGTTATTCTGAT
          CATCGCGCCCACCTCACGGTAAAACCCAGGATCGATGTGCAAGAGACCTGGCGAGGTCGA
          TATCGCGCTCCCCTCGCAGTAAAGCCTACGACATACGTGTAGGAGCCTTGGGCAAGTCAA

          TCAGCAGCCCGGCGAGGGAGGTAGATCTCGAACATAGATAGCCCACCAGTCGTATGCCTA
          TCGGCAGTGCCGAGCGAGAGGTACATCTCGCGTATAGATAGCCCATCCGTCATATGCCTA
          TGAGCCGCGCATTAAGAGCGCCGCGTGTCACGTTTTGTAGAGCTACTAGCCGGACGCTTG
          CCAGCCGCACAGCGAAAGAAGCGCGAATCAGACTTAGGCAAGACACCAGCTGAACGCCTA
          ACGTGAGCGTTGCCGTGCTGTAGTAAGTCACGATGAGTCGAGCTATTGAGGGGATGTATG
          TTCAACTGGGTCGTAGGCCATTATATTCGCGGATCAGGTTGAGACTTAGGAGTTACCGGG
          CCGGTGGAGTCGACAGGGATCCGCTCTTCCGGAGCTCCTCGGATGACCAGATTAATCTCG
          GCGGTGGAGTCGACAAGAGTTCGCTCTCTCGGAGCTCCCCGGAGGACGAGATTAATTTCG

          TTACAAATCACATGCAAGTTCGAATATGAGTTTAATTAGCTTCATACCAAAGCGTCCAAT
          TTACAATTCGCTTGCCAGTTTTAGCATGAGTCTGCGTAGTCAGATTCCATAGCGTCCAAT
          TGACGAATGGACCAGGCGGTTCGTTACTGATTTCCGTCATTCAACATCAGTGCGTCCACC
          TGATACATAGACTATGTACCTCGTCAATGATTTACGTTGTTCAACATCTAAGCGTCCATT
          ACCTCAACCCATGTTATGGCTTACGGCGGAGTCCTGACGCTGTTAACATTTGCACTTGCC
          TATCTTGTCAATAGCGTAACTCGGTCTGAACCCTTAGCGATCCGTTCTCACGCTTTCATT
          TGTGCCACTGAGGGTGTGGCCGGAGTTGGGTCAGATAACGCACATTCTCTAGTTCTTAAT
          TGACACACTGAAGGCGCGATCGGATTTAGGTCAAATAACGCACATTCCCTCGATTTTAGT

          ACCACTTGCCGCCATAAAGTCGGTGTAATCGGAGTCCCCT
          ACCACTCACCGTCTCAAAGTTGGAGAAGTCGGAGTACTTT
          ATCGCTGGCTACCTAAATACAGAATTATTGGGGCCACTTG
          ACTGTTCACTATTTGAGAGCAGGTTTCATCGGGGCCCTTA
          GGTATTCGCGTCGTAAGAATTGAGTAAGAGACACCGCCAA
          ACCGGCTCGGCCCTGAGCCCTGGAATGACTGCAGCGCACC
          AATCTCCACATTTCAAGCTGCATTCTGATAATGGAATCCC
          ACTCTCAGCATTTTAAATTGCATTCCGATAATGGTATACC

