 8 1000
t1        GGGTATGCATAACAAGAATAAAATGCGCCAACGTTGCGATCCGGAAAAACATCAAACATA
t2        GGGTATGCATAACAAGAATAAAATGTGCCAATGTTGCGAGCCGGAAAAACCTCAAATATA
t3        AGGTATGCATAAGAAGAATAAAATGTACCAGTGGTGAGAACTGGAATAATCTCAAACTTA
t4        ACGCATACATAGCAGATATCGTAAGCATCTAAGGTCAAAGGTGGAAAGACACTGATCCCA
t5        AGGATTAACGATCAGTAAAAGATCCCGCCGATGAGGGATCGTGATAAGACCCCCATTTCA
t6        ACGCATCAACAGTCGAACTGGACTGTGCCAATGACGGAAAATGCGATGACCCCTAATCTT
t7        GTTTGTAACTAATAGTCGTAGACTGTACCTCGATCGCGATTTGTGACCCGACTGTCTTCC
t8        ATCCATAATCAATTGGGCCGAGATGCGACTAAACGGACGCCCGAACGCATTCCCTACTTC

          ACACTTGATCGTATTGTCGGGTTTAGCGCTGCGGTCCACGATGCCTGCACACTTTAAAAT
          ACACTTGATCGTATTGTTGGGTTTAGCGCTGCGGTCCGCGATGCCAGCACACTGTAAAAT
          ACACTGGGCCGTATTGTCGGGTTTAACGCTATGGTCCACGTTGCCTGCATACTTTAAAAT
          GTGACAAGCCGGATTTTCGAGCTGAAAGCCCCGGCTTATATTATCCGCACATTCTACGAT
          GCGCCAGACGTCATGGTCGAACTCAATGGTAAGCTTGACAGAACCTACGTAGTTTGTACT
          GCGTTTGATTACACCATTAAAATTAACAGCATGGATAACGCAATAGGACCACGATACAAT
          ATGACACGCATGACTGATACCATCAATATCAAGCTGACGTGGGGTCGGGCGCTCTGTCGT
          CTTTAATGTGCCTTGAGCCGAATCGTACGCACGCCATCAACAATCGATAATGTTTAAAGT

          TCACGGGCGACCCGGCCACATCACTGCAGTGAATACTGGACCAAATAATCTGCTGATAGA
          TCACGGGCGACCCGGCCACATCACTACAGTGAATACTGGACCAAATAGTCTGCTGATAGA
          TCCCGGGCGATACGACCACACCACTACAGTGTATACTGGACCGAATAGGCTGCTGATATA
          TAGCGGGCGACCTGATCAAAATATGAAAGTGAAAGCTAGGACGACTTCTATGCCAATATC
          CAGCAGGCGCTTCAACAACGCCACTGAAGCTGCTGGTCGGCCACTTCATTCGTCTGGATC
          TACTGGGTGATCCAATCAAAACGCTTCTGCGGACATTCAGTCAACTTACTTGCCATCGGC
          TCGTACATAGCCAGTTAGTGAAGCCTTTGCACGGAAATAGTCGAATGTCCGTACCGGATA
          TAGTGCACCGTTTATTTAAATAGTCCCTTTTCGCAGACGATAACACCACTTTCCAACATC

          ACCGTAGGGATGCTTAATGCAATAACGCGAGCCCGTCCCGTCTCTGAAGCTTTGTTCTCT
          ACCGTAGGGACGCTTAGTGTAATAACGCGAGCCCGTCCCGTCTCTGACGATTTGTTCTCT
          ACTGTAGGAACGCTTGGTACAATAACACGAGCTCGTTCCGTCCGTGACGGTTTGTTCTCT
          GTTATACAGACGCCAGGTGGGACAACGTAAACCCAGCTCGTAATTAGAAGTCGAATGCGT
          AACGAGGAGACATATTGTGCGATAGCGCGAGCATGGTTGGCCAACAGAAGTTTGATTTGG
          GGGGTAGGGCCGCCTAACGTGACAACGCGCTCCCGGTCCGTCGACCAAGGTTGGATTTTT
          GGTGCCGGAAAGATATGCGCCTCAATGTACCAAGAAGTTGTCGGCAGAGATACCCTATCC
          ACCGAAACGAATTTGAGTCTGGAATCGTCGAAACAAATGGCATTTGCTTGAACGGGTTCC

          TCGCGCATGTATATGACAAGCGTGAACTTTCCAAGCCGCGACTCCTGTGGCTGAATCACG
          TCGCGCATGTATATGACAAGCGTGAACTTTCCGAGCCGCGACTCCTGTGGCTGAATCACG
          CCGCGGATGTATATGACAAGCATGTATTATCCGGGCCGCAACTCCTGCGGCTGAATCACG
          TCGCACATGCACACGGCTAGCTCAGATTTTCCGAGTCTTAAACCCGGCACGCAGAGAATA
          TCGTGCGTACAAACAAATAGCATGCTCCTTCTAAGTTAGCATTCTGGTAGTCTATGAACA
          TCGCGTTTACTTAGAGGAAGTATTGCTCTTCTAAGTTGCAGGTTTGGCAATTAAAGAACC
          TCACGCATAAATCTTAAGGGTTTTATTCGTCGGCCCTAGTATTTATAGCAATACCGGTGG
          ACGGGCCCAGTTACGCCTGGTCTCTCTTTTACAAGCTAATGCGCAAGGCGTAGGTGCCCT

          GACTTCATACAAGTTAGCGTGCCAGCCGTCGCTTAGCCCCAGACATAACAGGTAGACCTC
          GACTTCATACACGATAGCGTGCCAGCCGTCGCTTAGCCCCAGACATAACAGGTAGAGCTC
          GACTCCTTACAGGTTAGCGTGCCAGCAGTAGCTTAGCCCTAGAGTTATCAGGTGTAGCAC
          AACCGCCTCCACGTAAAAGTAGCAATTGGGGCCATGCCCTAGGGTCAACTGATCACGCGA
          GTGTTACTAGTCGTCAATGTAGCAATCACGCTTATGTTCTAGCTTTTGCTGATCACACTC
          GAGTTTCCACATTTTGAAATGGCAGTAGAGCTTATGCCTTAGATTTAGCAGGTAGCGCCT
          CGCTTCCAATAAGCATTTGGAATAATGAAGCCACAGGGCCGGTCCTATTGTGTAAGCTTC
          AGTAACCCACAAGACAAGGTCCCGGTGAAGCTCTAGCAATAATGCCACCGTGTCAATATG

          CTCTAGAGCAATGTCGAGTGGAGAACGAACACGTGTGGCAAGCATATTTGGTATCTTACC
          CTCTAGAGCAATGTCGAGTGGAGAACGAACACGTGTGGCAAGCATATTTGGCATCTTCCC
          CTCTCGAGCAATGCCCAGTGGAGAACGCGCACTTGCGGCAAGCATGTTTGACATTTTACC
          GTCATGGCAAGTGGCAAGCGGGCCATGCTCTCGTGCCGCAAGAATGTCTTACTCCCTCCC
          GTTATGCTCGGTGGCGGGTGTAGGACTTAGCCGATCAGTAAGATTGTCTAAAACTTTGCC
          ATCGCGGTCGAGGGCGGGCGCAGAGTGCACAACAGGGGTACGATCATTCGGAAAATTGGT
          TTTTTAGCCTCTGAAGCAGCAAGAATGACCATGGATAGCCGTTTACTTTAGTCCCGTGCT
          GTCTCGGGGGGTACGATTGTCTGAGATCTCACGACCAACGATGAATGTCAAGCAACCATT

          GCGTCACACAGACGATCAGTCCGCTTCCGATAGGTAATGGCGGGGGCCGACTGGCTCCTA
          GCGTCACACAGACGATCAGTCCGCTTCCGATAGGTAATGGCGGGGGCCGACTGGCTCCTA
          GCGTCATACAGACGATCAGCCTGCTTTCGCTAGGTAATGGCAGGGGCCGAGTGGCTACTA
          CGGACATTTAGGTGGTTAATCACTTTCAATTAAATTTCGGTGTAGGCTGTTTAGTTCATG
          TGAGTACTGGTATGATCTTCCCTCGTCTGCTAGACATTAGCTTGGGCCGTTGAACTCTTC
          TAAGCACTTAAATGGCCTACTCCCTCCCACTGGGCATTGGTGTGAGCCGCTTAGGTTCTG
          TTGTTGTCAAAGTCGTAGTCCTTGCACTTCGGGACTCTGCCCTACTACATATTGGCTTAA
          GGCAAAAAAACGCGATCTGTTTGCCAATAATGGGTTCACAGGTAAACCGTAGGGCCGCCG

          AACGCAATAGATAGATGTGGTCTAACACAAGCCTGCTAGTTGTGGTTCAACTCTTATGGT
          AACGCAATAGATAGATGTGGTCTAACACAAGCCTGCTAGTTGTGGTCCAACTCTTATGGT
          AACGCGACAGATAGATGTGGTCTAACATAAGCCTGTTAGTTGCCGTTCAACTCTTGTGGT
          ACCACGGTAAATTTATACGGGCTTACAAAGACCTACGAATCATGCTCCAGGTTCGATGGT
          ACCTCGTTAGACTAACCTGGTTTAACATCAGTCACTGAATCTTGTTGTAATTTGGATTGC
          AGCGCGGTAGACTTGTGCGGTCAAGTATGTGGCTATGGGTCTTGCTCTAATTTCGATTTC
          AACGAGTATGATTGATACCATCCTGCGCTAGATGGCACTCACCGCGTTTTTTTCCGTTGT
          AATGCAGCGAGACTGTCACGTCCAGGGTGAGTTGGCAGGTCAAGTACGTTTTACACAAAG

          GCACTCGCAAGAGGACTGGTTCTAGATGACTTGAGGCGTTGCACGGCCTCTTATAGTTAA
          GCGCTCGCAAAAGGACTGGTTCTAGATGACTTGAGGCGTTGCACGGCCTCTTATAGTTAA
          GTGCTCGCAAGAGGTCTGGTCCTAGATGACTTGAGGTGTGGCGTCGGCTCCTATAGCTTA
          CTTTTCGTGTGGGAATCAGTGCGAGATACCTAAAGTCGTCGTCAGGACCTTCTTAGTAAT
          ACTCACGTCGTAGAGCCGGTGTTCGGTGACTTGGAACAACGTCAGACCTGTCCTAGTACT
          AGATCTTCTAAAGAGTGGGTGTCCGGTGACCTGGGACACCGGAAGACTCGTCTAAATAAT
          TTCATTATTTGCGCCCAACGATCAGGCGATAATCGATGTGGTGCCACTATGTTCTGTGAC
          GTCACTATCTGAGTTCCGCGCCTGATCTCTGAGTCCCCCAACGTTGCAAGCGGCAGTAAT

          ATGGTTACGCGTACCCTTATGGACTCCACCCACATCTCCGAGGAAACGAGGCTCTCACAG
          ACGGTTACGCGTACCCTTATGGACTCAACCCACATCGCCGAGGAAACGAGGCTCTTACAG
          ACGGCTACGTGTACCCTTCCGGACTCTACTCATATCGCTGAGGAAACGAGGTTCCTACAG
          GCGAGAGCGGTTGCATCCGTGGGCCTAGGCCGTTACGCCAGTGAAGTAGAATTCTTCTAG
          CCAACAATGTTGGAAAGCGTGGGCTCTACACGCCCAGCCGGCGAGGCGAGACTATCATGG
          GCGGTAGTGTTGGCATCATTGGATTAATCTCTTTCCGCCATCAAAGCGAAATCATTTTGG
          ATGATATCGTGAGCTATAGTTAAACTGTCCCTGTACGGCAGGGCGAGTGTATTGAGAGTA
          GTAGCACCTAAGACCTCTGACAGCCATCGCTTTTACTGTAAAGATCGATTACAGGATGAG

          ATTCGGTAATTTTATCTGATGGAGAAATGCCATACACACGCTACGCACGTATTAACGTCT
          ATTCGGTAATTTTATCTGATGGAGAAATGCTATACACACGCTACGTACGTACTGGCGCCC
          CCTCGGCGATCATTTCTGACGGAGAAATGCCATACACATGCTATGTACGTACCAATTCCT
          ATCCGGTTGGTTTTCCTGGAGCGGCCCCGCTAACCGCCCGTACCCATCATACAAATACTT
          GCCGGCCCGGTATAGCAATGGTAAGAATGACTTACTCAAGCAGTGCTGGAACGAACACCA
          ACCCAGACGGTAATACACGAGCGGGAGCGCTACAGCTCCACAGCTTTAGTACGGACATTA
          TCCAATCACAGGTTTCGCGTACACGACTTTCAACACATTAACAGTACAAGGAGGACCTGC
          GCCCACCCAGAGGTAAACTAACGCGGAATCCATTCGACCCCTTATAATGCACGAATATGC

          CCACTGAATTTTGCCAAGATCCTCTGGCCTGGCGCCCGCCAATCGCGTACTTGAAAGTGC
          CCACTGAATTTTGCCAAGATCCTCTGACCTGGCGCCCGCCAATCGCGTCCTTGAAAGTGC
          CCAATGAATCTTGACAAGATCCTTTGTTCTGGTGCCTGCCAATCGCGTCCTTGATAGTAC
          TCACTCAAATTAGGTAAATCCCATCGTCCTAACACTCGCCAATTTCATCATCTACCAGGC
          ACGTTGAAGACAGCCAAATTTTGTTGTACTGGCGCCCGCTCATCGCGGTGTGGACGCGGC
          AACCTGCACTTGGATAGGCCCTGACCTACGAGCGCCTGCCCTTCGTGACGTGGACGTCGC
          CTAAGCTAGAGCCCCGGGCTCTTTCGTGAAGATGCTTGAGGTGGGCGAAGCAACTCAGGC
          GCAAGCAACGTCAATGAGTCCGGGTGCTACGGCCGCTAGCGAGCAGAGAGTGAGTGATCA

          CCCTGAGCACAGTGGCGCAGATCCCATCCTTCCCGCTCGAGGCATTAGTGGACTAGGGCC
          CCCTGTGTACAGTGGCGCAGATCCCATCCTACCCGCCCGAAGCATTAGTGGTATGGGGCC
          CTCTGTGCCCCGTGGCGCAGATCCCATCCTTCCCGTTCGAGGCACTAGTGGCATAGGGCC
          ACTTGTGCACTCTGGTATAGTTCAATCTTTTCCCGAACAACACCCTCGTGAGGTAGGACT
          ACTCATGTACGACGATGCGGACGCCATTTTCCCCGGTATAGATCCCTGCAATATTATCTC
          TACCAGGCCCCTCAGCGCCGGACCCACCTCTCGCGATCTAGGTTCCTGTAATCTCGCCAA
          TTTCTCGATCTCCATCATCGCCGCCAGACTACTCTCTATGCAGCTGCGATTTACCTAGTT
          TTCTGGTACACTATCCGCCGCCGTTCCATTGCTTAGTGCCCAATTCATCGACACCTGATG

          TTGCGACGGGCTACAATCAAAGGGGTGATAACCGGATATGGCCTAACTCTAACTTTCCGA
          TTGCGACGGGTTACTATCAAAGGGGTGATGGCCGGATATGGCCTAACTCTAACTTTCCGA
          CTGCGACGGGTTACTATCAAGGGGGTGGTGGATGGATATGGCTTAACCCTAACTGCTGGA
          TTGAGACGGGTCACTAAACGGGGAGTGACACCCATATTCATTTACTCCGTAACTACTTGG
          TTGGGAAGGGTTACTGCCCAGGTAGTGATTGTTACACTTGACGAGATCGCAAGCGTCAGG
          TTACCATGGGATGCTAGCTACGGAGTCGCGGTCACACGGATCAAAACCACAACAATTAGA
          CTACGCTGTACGAGTCGCATCGGTGAGACCGAAATATATTCCGGAACCGAACCTATCGAA
          GGGATTCTGACGTTTGACATCGGCACGGCTCTTACCCTGTTTGGTGCAGAACGCGCCCCA

          TCCCTGCGAGCTGCATCCTGCCCTGCGGCACGGCGCGCGTTGGTCATTATTACCACCTCG
          TCCCCGCGAGTTGCATTCTGCCTTGCAACACGGCGCGCGTTGGTCATTATTACTACCCCG
          TCCCCGTGAGTTTTACTCTGATCTGTAACACGGTGCGCGTTGGTCATTATTACTACCTCG
          ATTCCGCGGACACCATCCGCATTTAAGTTATGATGCGTAGAGATTATTACTGTCCCCACG
          ATTCACCAGGCTTCGCTCGGTACCCAAATATGATGCGCATCGAACACAATAGTTACCCCG
          ACGTCCCAGCTACCATCCACAATTAGACCGAAACGCGTCCCGGTCGTTACGGCTACTACA
          GCAGACGGTATAAAGTTCTCGAACACAGCCCTATGCGTGCCATTATACTGGAACATGAAA
          ACTATTCCTGTAGAATTCCAAGTTGCATTCATACGCGCGGGGTTCACTACCCATGCCCCA

          CCCAGCATCGTTTGAGCAGGGCCCGCGCTCGTAGTCGAGC
          CCCAGCATCGTTTGAGCAGAGCCCTCGCTCGCAGTCGAGC
          CTCAGCATCGCTTGAGCAGGGACCTCGCTCGCAGTCGAGC
          CTCACCAAAACTTGACATGAGGTCTCGTTCGTAGCGAGGA
          CCCCGTGCTGTCCGTGTGGAGCCTTTATGGTCACCGAAGC
          CCTCGCACCGTTTTTGCTCGGACATTGTGCGCAACTCAAC
          GCCTTAAATATTTATATCGAAAATCCGAGCTTTACGTAAT
          TCATGCAGTGTCCTTACCAGGTTTGCGCACCCGGAACCGG

