 8 1000
t1        GCTAACGTTCAGCGCGATAGGAGTTTTTATACTTTACACGTGACGGTCCGTGCGCAATTC
t2        ATCACCATATGGGGCCGTCAGAAGACAATCCTCTTCCGGATCCTTGCGCACGTGGGTTCC
t3        ATCTAGGCCAGGCATTACGAGGTATTAAACTCTCTTTATGACAATGTGCGACCCATACCA
t4        GCTGACACGCGGAGTGGTGGGGACTTTTGCACCTGACATCTCGCCCATAGACTTCTTGCA
t5        GCTTGAGGCTTGCCCTATAAGGACCCTGGCATGTATGTTGCGGACTAACAGAGAATACCG
t6        GCCCGCGGGGGTGACTTTAACGATCCTTACGCTTGTTGTGTGGATAAGTAGGAGTCGCTG
t7        CGCTAAGACACAGTTCATGGGGCTTTCGACCTCTATCGTTCGGCAGCATGATCCACCCCG
t8        CAGAGCGTCTTAGGTCGCGGGAATCTCGACTCCCGCTGCTCGGTTGCACAGTCAACTCTG

          AGATACTCCGGCTCCTGTGTGCGCAGATAGTTACTCACTTGGGGCCGTAAGGTAGGTACC
          ATCAACTTTAGCCAGAGAACGGGCTGCAAGCTTCTCTAAGTGTGATAGAACGTCAAACAT
          GCTCCGTATAGTCCAGTTGAGAGGAAGTCGTGCCCTGTCGTGTCTCTTGTAATGCAATCA
          AAATGACGAAAGGAACTCTCGAAAAAGGGACTCCACACAACCATTCAAATCTGACCAACT
          AATCGATGTAGGAGATATGCGAGCAGGTTGTATTCCCGCGTGAGATGTCATCCGAGCTGA
          TATTAATGCAGCTGATAAGCGAAAAAGCTGTCCTCCCTGGCTAGATGTAAACCAGGAAGG
          GATTAGGGCGGAATCACATGACATACGTTGCCTGCCGTGATTGGGGTTAAACTAACACGT
          GACTAATGTGGCAACACAATCTACGCATTCCCTGTTGTGGTTCGGGTTAAACTGATACGT

          ATTTGGTTATTGGCTCGTTGGTTGTGCGGTCTGGGATCGATACCCCGGTGCACGCCTGTC
          ATCCACTTATCCGTTATGTGCACCTGCAACGGGGATTCGGCACTCCCAATCAGGCCGGTC
          ACTTAATAGTCTCTCTATCCGGCTTACCATCACGGGCAGGCACTAAGGATTGCGATATGT
          AGTTTACTACTCACTCTCGCCATGAGTTATTAGGTCACGGAACCCGGGGGTACGCAGCGC
          ATCGCTAACGCCACCTATTGTTTCGGCAACCAACGCCAATTACAGCTGGACGATTGGCAC
          GTGACGTCTTCCTCTTCCGGCACCTGAAGATTGAGTCTGAGCAAACCAGTCGGCAAATTT
          GCTCCGTCACCTGGACAGGTCTCCCGTCATCAGAGCTACTCCGGGCAGACCACATAAAGT
          GTCGCGTCATTCGCATAGAACCCCTGCTATCTGGCCTTCGCAGGCCAGAGCAAGCAATGT

          TTAGTATGGACTCAATGAATGGGGAGTAATTCAAAATTGATGTACTACCAGTATCAAACT
          ACTGTCCGCATTATAATATTGGGGTGTGCTAAAAATGGAGAAGGTGTTGTCTCCAGAGTA
          CTCGAGTGTGTTTGTCAGTAAGAAGACGATCCAGATTAGAAGTCCGTACGCTACCAACCC
          GCAAACTTCCGTCTTCCACCGGTGGCTGGCTTGAATAACACGGTTGAACCGTCTAAAATT
          GCTAACGTGACTGGATGGGCCCCGGATATGCTGGATTCTTCGACTACCTCGGGCGCACAC
          CCCAGTTGTGCTGGTCCGGCATGGGGTGTATTGCACTCCTCGTCTTATGTGGACAATCTC
          GTAATTTGCGACCTTTAAATAGGGAGCTCCTATGTCTTTTCATAGGCCCAGAGCTGTGTC
          TAGAGTTAAGACGCTCAAACAGGGAGCGCCTAATTTCCTTCCTAGGACCAGAGTTGTATC

          ACTGCTGAGTTAATCGTGCGGGTATATGACAGTTAAAAGTCTCATGCTACTGAGTGTCCC
          GGGCGCGGTTTTACCGGGAAGCCCCGATTTAGTCAATAGCGTAGAATCCAATAAAAAGTT
          ACTCCGGCTCTAACCGCACGGGCCTGATTCAATAACACCCTCCGCACAGCATACGTGTCC
          GTCACTAACACGAATGTGCGGGACTCAATAGCGCGATATCTTAATACACCTAGGTGATAC
          GAAGTAAAGCTAGTTGTTCGACCTCGGTTCCACGGCTATCTTTGCCCAACACGGATGTTA
          TTATATAATCGATCCGGTTACCCTCGGCTTCAAGCATCTTTTGCGACAAGAAGGATTTGA
          TTTGTGCAAGGTGCAAACTGATCCTGGTTGAACCATCAACATATGTTGATCACCAATCAA
          TTTGTTAAAGTAGCATTCTGAAAGCGGTGCAGCCCTTTACTCGCGACGTCTACTGTCCAC

          GACATGATGACCTAGCTCACGCCACTTACTAAAACCCGACCTTAACCCAGTAACTACCGA
          CACGCATTAGCCCAGATTATCGGGGGCACTTGACCTAAACCCCCAGGCTGTATAATCAGC
          TCTAAGCAGATTGAGACGAGCACTGGCACTGTAGCTAACGTTTCCGGAACTGGGAACGCG
          GGCTTGACGACTCAACTCATTACGAGGGAGAAGCACATACCTATGACAGTTGATGATGAA
          TTCATGGAGTCTTCAGCGAGCGGGAGCGGACGAGACTATTCCCCGTTCCCGGGAAATGGT
          TCAAAGTTCTCTTTAAGAACCTAGAGTTAACGAGCCCTCTCCCCCAACCCAGAAGATGGA
          TAGACGCGGACTATGGCCTGGGTGAATAACTACGTCAAACATACACTACCCTTGGGACTC
          TGGATGCGGACAAAGGAGTGGGTGCATACCTTCATCAGACGCTACTCAGCGTTGGGAGCC

          GAGAGAGTGCTTCAATATGGAGCATCAGCCTCTTCCTAGGAGGTGAGCATCACTAGGTGA
          GACAGAAATTTTAGGCGCAAGTAGTCCTTCCTACTCTGCGCACTGAGCAGGGTCAGAGCA
          GTCGGTTGTCTGAAAGGCGTCGGGACGCCTTGGAGTGAAGCGTTATGCAGTGACACCGTA
          GGGAGATGTCCGTTACACGGATACTCGTTTCTAGTTTAGAGTTCGGACAGCACCAACGCG
          TGGGTGTCCACGCCCAACCAGGTCTCGTCACAAGCACAAAAGCCTGATACATTCGGCTTA
          AGGGTATCCTTACTAAATTAGGCACTGCGCCAAACGCAGGGTCACAACATACTTGGGGTT
          GCCTGCTTGATTGGATTTTGATTCCTATTTGTGCTATGGTTACGGCTTATTCCGAATTCA
          AGTCGGTGGATGAGGTTCCGACACTTATTATTGACGCGGTTACGGTAACTTCCGGGGTTA

          TACTTCGCAGATCCAGGGGATCTTCGATTCGAGCACTTACCCCCTCGAGCACCATCGCGA
          TATTCCTCATATATGTGCGATCTCTGACCGGGCCATATGTTACGTAGAGCGTCACCGTGG
          GATAATTCAGACCACCGTAACATTCCGTCATCCTATAAATACCAAAGCGCGCCACTTTAG
          TTTTACAAGCATTCGTAAACTTTCCTGCTGGGACAAACACCCATTGGCGTGACATCGTGC
          CAATAGCAGCTCATGTAGGACTTCTCCCTATGGCAGCCAATATTTTAACAGCATCCGTAG
          TAGCGGGCGCACTCGTAAGCCAACTTTCCAGATTGCCGCTTACTTTGTAAGCCTTGCCGA
          GTTACCACACGTGTGTAAGGAGCCCCATAGTATAAACAGTCACCCTCTGGACCACTTCGT
          TGCTCCACGCGTGTCGGGGAAGCCACACGGTACCGGTGGCCTTCCCTTGGACGACTTCGT

          GCCTTCAGCGTCCAGCTCGACGGTACCAACTTATCCCGTAGGTAGGATGCGTTCTCAGCA
          GTTCCTAGTACCAGAACGTGAAGTTAGGGCCAACAGCACGTGCAGGTTCCAATCCTGGTA
          GCTCTAAGAGTAGGACCGACGAGTCAGAATCACAGGCAACGGCAGGACTTGGCCTTGGTT
          GACTTAGGTGGTGCCCCAAGAAACTTTAGAGGCAAACAACGACTAGCTCTGGTTGTTGAT
          CCGAAGATGGCGAACTATAATAACCCCGTCCACCATCACCGGTGTGGCACGAGGCTGACA
          GCAATGAGGGCGAGGTTAAACGGTCCTTTACAGCGCCAGGGGTAGGATATATGTCCGCTG
          GATCGCTGGACGAGATGGCTAGAGCCAGACCGCCTCTTTGGCCAGGTCCTGCTGCGAGCG
          GATTGTATGACGGTGTGGCTATATTCAGATCGCCTGTTGGGCCTGGTCCTGAAGCTAATC

          TAGAGGTTTATGGATTAAGATGCCCACTACCTATGACCCATGGGGGGTAAAATCAGAACC
          TAGCGGTCCGCGGGTCTAATGAAGACACGCCAGCGACATACGGCCAGGGACCCATGCATC
          AAGAGGATTGCGCATGCGAGCTAGTGAAGTTTGAATAATTTGCAAGAATCCCTGTGTTCC
          TAGAGGTTTGCTGGTATAAGCCAGGGGCATACGTCGTGAATAGACAGCAGTTATCGTTTC
          TTCAGATTCGTAGAGGTAGTCCAGGGAGTAGCCCCAGACTTTAAAAGCTTTCCCAAGATT
          TGAGGCTCTGTTGATGTAGATACACAACTCACTCTTGACTTTATAAAGTATCCGAAGGCT
          CTAAGCTACGGCGGTGCAACTTCATAATACACCTTACGCATAGAGCAGCGTATCGCAACG
          TCAAGTTATGACGGTGCCACCCCCTTACGCATTTCATATCCCGGGTAGCGTTCTGTTCAA

          TGACGCTCCGTCCAGACGTGGACCGGCCGCGTAGGACAGGGACAGGTGGCACCCACCAGA
          TAACAACATATTAGTTATTGGTGAGGATAAACGCAACGCAGACGAGTGGCGTGCGGCTGC
          TCTCGACTAATTCAGCACTGAGATGGCCGTACGGGCTGGTCATGTCTAACACCCGCCAAA
          CAATGACTTATCGGGACCTTAGATGTTCACGTAGCCTAGATGACTGTGGAGCCCGTTAGA
          TTTCACATCATTGGCTTCAGCATCTAAAGTGTGAACTGGAAGAAGGGAGAACCACTAAGC
          TCCAACAATCTTCGCGTTGGCGTCCTATGCGTAGACCGGTTAGACAGGGACGGCTCGTTC
          TGCTACTCCCGTGGGATCGATGCAGGTAACTTAATATCGATATGTAGAGAGAGCAAGGAC
          AGATGTTCCCGTGGAATCGATGCAGGCGAGATAATATCGCGATGCAGAATGAGTTCAGTT

          CTGGTGGGACGGTACTCGGTTTAAGACCTATAGGAGATCAAGTCATAAAACATAAGTGGA
          ACTGTGGCTTAGCTTTCAGCTCAATACAAGCAGGAAATCCCTCGATAGTGACCAAGTATT
          AGAGTAGCATAAATCGGCGTTGAATATCCGTGGGTGACCGTAGATGAACACCCAAGCGAT
          TGGGTGGCACGGTTTCAAGGCTTATCCCGACAGAACCAGTGTTTTTAACATACATTAGGT
          TTGGAATTCTGATACTAAAGCACTTTTCCGGAGGATTTTTACAAGCCAGAACGTTGTGAT
          TCTGTGATCCAGTACAATAGATGTCACCCGCGGAATGTCTTCGGGTGGTCGAACGGGGGT
          CTTGTGCTCTAAAGAAACAGTAACTCCCCGCGTAAGCACTATAAATACCAGGACCGGGAG
          CTTGCGGCGTAGAATTACAGCAATTACTCCCAAATGTCTCCTTAATAAGGCGATCAGGTA

          CAACGCTGCTCGCTTAAATGGTCGACGGCGCTTCGCAATTCAGCTGGTGTTCCGCTATCA
          TAGTGACCAGCATTCCTATGGAACGTGGCTTCTCACATTGCCGGGCATGCTCTGTTGCTT
          CAGTGTCGTGCACATCTCTAACTAATGGCGCTCTGCAGTTCTGCGGACGTTCAGATATTA
          TGAAACAGGACACATGGTTGCACAGTGGAGATGCATGGTGCCGATACGGCTGATTCTCTG
          CCGTCCTGACTTCCCGTACGAGGCGTGTCTAGTTACGGTTCGACAAGTACCATCGCGAAC
          TGGCTCTGACCCTACGCCCAAGCGGGGCTTAGATGTGACACGAGGAGGGCCGAGACCAAA
          AAGCATTATGCCCGCGGTTGAACGGCATTCTCGGGTGGTTGGAACGGCGCGTGTTCGCCG
          GGGTCATTCGCTCAAGTTCAAGTGGCGTACTCCGACGGCTTACACGGCGTGTTTTCGTCG

          TAACCGAGTAGTGCCAGGGCTCTTCGTAAGCATTTAGGTCCGTCAATGAACCACACAAAC
          GACACGCTCGATGCCGAGGACTTATGCCGGTGCTCAAGTCTATGAAACGATTCCCGATAA
          TGACAGCAGGATGTCGAGCTTTCGCAAGTCGTACTAAATCATCTAGAACGTGTTGCAAAA
          TATATGAATGCCATTATGGGCAAGAATTCCCAGTAACAGCTCGTAAAGCGCACAATTGAA
          CAAATGGAAAGTTTAGACATGTACCTCCAGCCTCCGGTGGTTTAGAATTATATGGCGGTA
          CGTGCCCAAGGTATCGGTGTAGACCTCCAACTGCCAATCCCCACTGGGACCCCGACGATA
          TAGGCATATACGTAGGGGGAGCCCTATTTCTACCCCGGATCATAGCTGGGCACAATGTGA
          TAATTGAATAGATGCACGGGGTACTACTCCTTCTTCAGCCCAAACTGCGGTACATTATAA

          AGCATACAGCTCCGAGCGAGTTGAGCCATGCGCGCCCGTCTCGATGGGCTCCAACCTCGG
          GGCGACCTATTGGTGCGCCCTAGCGGTTTGTGCGCTCGCATCGGGAGGACGCTCTTCTTA
          GGTGCTCAACTGAAAGCCCTAGAGGTCCACGGCTCTGGTACCCAAGGGCGGTCGCTTTTG
          GGTCCTTCAATTCGTACCCTCAATTCTCTGAGAGGCCCATATGGCGGGTTGCATCTTTCA
          ACTGACCCGCTTTGTCTATGCAACGGTTGCACGGTCTGTACCGAGGTGCCACTATCCTAG
          AATGGCTCGCCCTAGCCGCATAGGACTTTTAGAGCCTGTACTTGAGCTCCAATATTCTTA
          GATCAATGAATGTGGGCGTATCTCGACCGATACACGTCTTTCCTGTCGATACCTGACTTC
          GTTCGTCGACTGTAAGCGTGTCATGACAAAACCGCGTACTTTCTGTTGTTACGTGCTTTC

          TTTTCTCGTAGGAGGATGCCATTCCGATATCATCGACATTCCAAGTACCACCCGATCATC
          TCCCTACCTAAGGCCGGGCCGGCCATATCTTGACGACATGCCTCGTCCCCCACGAGAAAA
          CATTAGCGTGTAATTAGAGCATGTGTGGCTTAATAATATCCCAAATAATAGGTTACACAC
          GAGCTGTGCAGGGTCAGGGGAGTGCTTCGACACCGATAACTCATGTAAGTTTACGTTTAC
          CCCGATGGTAGTAGCCGCGCCCAGCCACTTCAGCTACAGGGTAAATTATGCGTTGCCGCC
          CCCGAGTACGGAGCCTCATACGTAATTATTTATTAATTCATCCGATAATCTGTAACCGGT
          AGACCCAATAGCGAGGCAGCAAGACACCGGTAGTGGAACGCAAAATTTTGTTTGATTTCA
          GGACTGAAACGCGAGGGAGCACTACAATGTCAGTGAGATAAATAGCTTCGCTCGAGAGCC

          AAGGCTGGTTCGTTCGAGATAGGTAATATGACTAGTAAAG
          TAGCACATTATGCTTGCTATGGTCGGCGAGGCAGTCAAAA
          AGCAACAGCCCACCGTGCCTAGGCAGAGAAGTCGATGAAA
          TTAATAGGCTCGTTTTAACGAAGTACTGTGTGGGCAGAGG
          GAGATCGACACAGATAGATCGAGAAGAACGATGGGCTGAG
          GGTCATAACAGGGACACACATCAAGGGTCGACTGTTGGGG
          GACTGTAATTTGGGCATGGTAGTCGGATGAAAATCTGATA
          TGGCTTAGTTCGGATCCGCTAGTCGGATGAAAACCTCATG

