 8 1000
t1        CTTTTGAAAGGCCATGTTGCTCGACGAAAGACGGAGCTGAAATCGTCATCACAGAGAATC
t2        CTTTCGAGAGGCCATGTTACTATACTAAAGATGGAACTGGAATCGTCGTCACAGACAACC
t3        TACTCGTACGGTCATACCGTAAGACACTCAAATGAGTTAAGAACGACAGCACAGGCAGTC
t4        TTATTGACGGACCGTGTAGGGGTAACTCTGGCGAAGCCGCGACCTGCCCCATAAACCACA
t5        TCACGCCACGACCGCGTCGCAATGTGGAGGATAGCGGGGAGGGTCTCAATGAGGCTTGTG
t6        TCACACCACGACCACGTCGCAATGTGGAGGATAGCGGGGAGGGTCTCAATGAGGCTTGTG
t7        GTTCCGAAGCCGTGAATTGTAGACAGAATGTCAACAGTGGCCTCAGCCGTACTAACTTTT
t8        GTCACGATACCGTGCATCGTAGATCAGTTGTCCACGGTAGCTTAAGACGCATAATCTGCT

          GCGGCATATAACCTACCGTTATGAGTGAAACTGTCATGCACGGTACGCGCGAGGGGCGCA
          GTCCCACTTGACCTTCTGTTTTAGGTTAAACTGTCATGTACGGTAGGTGCGAGGGGCGCA
          ACGTCGATCGTTCTATATCCTCCCGAGAAGTCGTTAGTTGTGTTCTGGAAAGAGTGTACC
          ATCATATTCCTTTTGTTACTTGGAGCGACATTGCAATCCGCATTTATTATGATGGGCGCA
          GTTCCACCTTACCCCCCACCCAGAACAGGGCCACTAAGACTGTGAAGTAGCCGGGATGTA
          GTTCCACCTTACCCCCCACCCAGAACAAGGCCACTAAGTCTGTGAAGTAGCAGGGATGTA
          CACCTCATTAGGCGATTGTTAACGACTGGCTAGTGAAAACTCACTGTAAGGACGAGCAGA
          CACCAAATTAAGCGCTTGTTAGTAACTAGCTGGTCGGAGTTATCGGTGACGTCAGGCGGA

          CGAGTCATTAGATGAGAGAAATGCACTTTGAATCTAAAAGACCTGGTTCGATGTGCAGAA
          CGAATCATTAGATGAGAGCCATGCTCCCTAGATCTAAAGGATATGGTCCGATGTGCAGAA
          TAAGAAACCCGATGTATGTAATTGTCCTATTTTTCATGTGACTCCGAAGGACGTGCGGAG
          TGGATGATCTGTTGGGGGGTATAGGTTCTAATCGAGTTCGGTTCAGAGCCATGTGCGAGA
          CGGATTGCCTGATATGTGGTGCACCCGGTTACAATCTATCTACTTGGACGTTGCGTGATG
          CGGATTGCCTGATATGTGGTGCACCCGGTAACAATCTATCCACTTGGACGTTGCGTGATG
          CGTGTACTACATTATGGGACAAGCTCCTTCGTTGGGTAGTTGCAGAACAAAACTCTGGGG
          AGTGCACTTAAACACGGGACGAGCTCTTTCGTCGGGGGGTGACAGGATTACAATGTGCGG

          GAAGTGGCCTAAGCTTGAAAACCCCCATAGATTTGCGTGGACGACCCAGAGTAAAGATGG
          GAAGTGGTCTAAGGTTGAAAAGTCCCATGGATTTGCGTGGGCGGTCCAGAGAATAGATTG
          GAGACGGTCTTTGGCTTTCCATACTCACGAATTCGCGTGCAGCGCTAAGGAGATACATGT
          GGAGCGGTTTAAAACTTATTAATACTGGCCTCATCCGTGAGCCTACATGGTTAGAACCGA
          GGGGAAGACTGAAACCTACCGTTGACTCGCATATGCGGGAACAAGCGTCCACATAATTAA
          GGGGAAGATTGAAACCTACCGTTGACCCGCATATGCGGGAGCAAGCGTCCACATAATTAA
          GGAGTGATCTGTAAACGGGCCATATTTGACCTCATCTACCGACAATCTGGTGCTACCAGA
          GGGATCGTCAGGAATCGGAGACCTTTTGAAATCATTTACGAACAATCCGTTGCCATTAGA

          CGACACCGTTCTTGTCCGACGAGGTCTCCTTTTCGGTGATACCGCGAGCCCCAAGCTGGT
          TGGCACCGTCCTTGTCCGACGAGGTTCCCTTTTTGGTGATATTGGGGGCCCCAAGATGGT
          CAGATCACTCCATGACCGCGGTGAATTTGTCTTTGTAGACAGGTCGATACTCCCGGCGGT
          TCGGGCTGCTTTGGATTAAAAGCATCTTGCGTCGTGAGACACCGCGAGCCATATGTTGCC
          TTGGACCGCTCTTGCGCGTAAGCATGAAATACTTAGTGCCACCTTTTGCACTATGTGGGT
          TTGGACCGCTCTTGCGCGTAAGCATGAAATACTTAGTGCCACCTTTTGCACTATGTGGGT
          GTTTGTTTCTGTTAACCGCTTGCCTTACATGTTCGGTTTTACTCATGCGGACGAAGGATC
          GTTCGTTCCCGCTATTTGACCATCGTACCTGGTTCGTTCTATCTAAGCGGGCTGAAGATA

          GCGGCCTTCCTTTTCGCCTGTGTCATCTAGTCTACATAAGTCGGTTACCGGTTATCTTCT
          GCGGCCTTCCTACTCGCGTGCGTCGCCCGGTCTACTTAAGACGATTACAGTTTATCTCCC
          GTTGCTGAGACCACCGGTAACGTCATGTTGGTTGCTTGAAACAGACTAGGTATTCTTCTT
          ACTGATCTATATTTCCCCGAAGCAGAATTGGAAACATTAGTTAGTGCACACCCTCTATCT
          GAGCAGTAACTTTCAGTCGGACCAATGTTGACTTCCTACGGGTGTACAGCTTTTTTTTAG
          GAGCAGTAACTTTCAGTCGGACCAATGTTGACTTCCTACGGGTGTACAGCTTTTTTTTAG
          TGGGGTCAATGCTTCATTAATGCTGTGGGAGGTAACACGGGACGCGCCGGCACTACCTCT
          AGGGGCCGGTGCCTCGTTATAGTCGTGGGGGATATCGCGGGAAGCACCAGCATTTTCCTT

          TCCGGACGAGACTGAGGCTGGCGTGTAAACGATTTTTACGGAAACCGCTATCGCTACACG
          TTAGGACGAGGCCAAGGTTAGCGTACAAATGATTCTTACGGAATTTGCTATGCCCATACG
          CCGGGACTGCAGTAGGGCTTGGACACTAACGGCGATTCTTAAAGTCAGTCTATACCAACG
          GACGGCCAATTCCAAGGTCGGACTGTTAACGGTGAAGACACAAGCAGCGTTCTATGAACG
          TCCGGATTAGTGGCGGGCCCGTTTACCCACGGCGCAGACCCTAGCAACACTACGTCTTCA
          TCCGGATTAGTGGCGGGCCCGTTTACCCACGGCGCAGACCCTAGCAACACTACGTCTTCA
          CTAGCTACACCGCGGGAGTTATAGTCAGGTGGTGCTGCCCGACAAGGCCTTGCTCCAAAG
          TTGGCTGCACTGCTGGACACGTAGTCTGTTTGTGTCACTAGACAAGGTCCTGCTAAAAAC

          CGTCGAGGACATTGATAGAAACTCCATCGCCGCGGTAGTAGGCATCGTCTAATCCGACCA
          CGTCGAGGACATTAATAGAAACTCCATCGCCGCGGTAGTAGGCATCGCCTAATCCGGCCA
          CGTTGTGGTCGTAGATAGTAGTGCTTTGCTTGCATTAGGACGCGGTGGTTGAGCTGACCT
          GATTAGCACGCTCGGTAAGACCTACTCGCTGGCGCTTCGCATCAATATCTACAGCCGCAA
          TACTAACGACTTTAACCGGGGCTCCTCATTCTCGCTAGTACCAGGTGTTTATGGGAGTTT
          TACTAACGTCTTTAACCGGGGCTCTTCATTCTCGCTAGCACCAGGTGTTTATGGGAGTTT
          TGCCGCCGAGCGCCAAACAACCCTAAATCGCAAGACAGATAGTAACATCTGATCCGTCTA
          TACCAACGGGAGCCAAACAACTCTAGATCGCCCAATAGACAGTGACAGCTGATTCGGCCG

          ATACCCAAGCTGGGTACACACGGTCAACCCCCGCTGCACTCACAACACAGGTAGGATGGT
          ATATTCAAGCTGGGCTCACTCGGTCTTCCCCAGCTGAACTTAAAACACAGGTAGGATGGT
          ATCCTATAGACGTTAAGATAACGCATGCCATTTCTGACCTAAGCACCCCATTACGATGCG
          GCGCCCACGCCGACTGCACGAACCCTCTTTCCTAGGAATCGGAGTAACCGCACTGACGGC
          GCCCTCCATTTACGCCTCCGAGACCCCATCCATACGGACTAGTAACACCGAACGATTGAT
          GCCCTCCATTTACGCCTCCGAGACCCCATCCATACGGACTAGTTATACCGAACGATTGAT
          GGCCGGATCATGCGCCTAACTTTGGTTAGATATAGGAACTGGCGGGCCAGTGGGGCACTT
          GTCGGTACAATGTTTCTAACAACGATTCGATGTGGAATTTGGCAGCCCAGTAGGGAACAC

          GGCAATGACGGTGGTGTAATTAACCGTTATCCATGGAGCCTTAGAGTTCAGCGCGAGTGC
          GGCAGGGACGCTGGTGTAATTAACCGTTAAGCATCGGGCCTTAGAGTTCAGCGCGAGTGC
          AGCAGTTGAAGTGGTGTGGGTTGTAGTTTACCTAAGATTTCACGCGTCCAGCACAGGTGC
          CACAATCGGGATGGTCCGGTTCGTGGTCCCCTTAGCAGACACCGCACTCGGCGAGGGTAC
          TTGAGATAACGTGGCGCGAGTCACCGCCGATCTGTCCGACTATTTATCCAGCGCGTGATC
          TTGAGATAACGTGGCGCGAGTCACCGCCGATCTGTACGACTATTTATCCAGCGCGTGATC
          CGCAGCAGTGGGGGTTCAAGTCATTTACCGTTCTGTCGCTCATGAGGAAAGCATGTGCTC
          CATAGTAGACGGGGGTAAAGTCATTATCCGTCCCGCCGCTGTCGCAACTAGAATGAGCGT

          CCAATTCCGTTCCCGCGGTGTCTTCCAATGGTATGCGAATATCACCCTGGCTCCGCGAAT
          CCAGTTCTGTTCCCGAGGTGCCTTTCAACGGTAAGCGATTATCATATTGCCTCCGCGAAT
          TTAGCCACGACTGCAAGAACCCATTGTCTAGCGTGTAAGAACCTCAGTGACCTAGCTTCC
          ATAGCCGTACACGCTAGCCCCCTTTTGGCATTACTCGAGTTTTACTGTCACGACGTTAGC
          GTAACTATACCTGCTCGTCGCATCACTACCGTCTAGGCGCACCGTAGCAGTGACGTTGGC
          ATAACTATACCTGCTCGTCGCATCACTACCGTCTAGGCGCACCGTAGCAGTGACGTTGGC
          GAATCTAAGTCCAGTTTATGTACGTCAATGGTGTATGACCCGTTCCCCTAAACTCTTCGC
          CAACTCGAGTTAGCTTAATTTACTCCAATGGTGTGAAATCGATTTAGCATTGTGATGGGC

          AAGCACAACAGGCATAGACCTTTATATAGGGCCAACCGGTCCATGGTGATGGGCAGCCGA
          ACGTACAAAGGGCATAGACCTCCATATTGGGCCAACCGGCCCATGGTGATCGACAGCCGA
          TTGAACCATAGGTACCAGCCTTCATAATTGACTTGTCTGAGCACGGTATTCAGAGTCGGA
          CAGACTCCTTAACCACGATTTCCTTATGTGACCACACGTAGTGTGCCGGGGAGCCGAAGA
          AGACCTCAAGGTTAGTGGCCCTTGATAGTGGCGTCATTGACAGTGAAAATAGACCACAGC
          AGACCTCAAGGTTAGTGGCCCTTGATAGTGGCGTCATTGACAGTGAAAATAGACCACAGC
          CCGGGTCATGACCTCTGTCCGGTCAAAAAACAACCATGAACAATATTCGTAGGGTAAGCG
          CTAACTCGTGACCCGCGATCGACGCGGAAAGAACTACGCACGATGTCCGTAGAGTAAGCG

          AGATCAAAGATCGGCCATGTGAGGAGTTTGCCGTGACCGGCCTTATACACGCAATTCCGA
          AGATCAAAGTTAGGCCATGTGAGGAGTTTGCCGTGACCGGCCTTATACACGCAATTCCAC
          AGGTTAAAGGTCCGATAAATCTAGCATTGACAAGAACTGGATCTAGATGTAGAACTGTGT
          CGATCAACGGTTTTGTGCTTTCAGAGCCCAGTGAACTTTAACCGACAAAATCGACACTTA
          ACTCCAATGGCCCGCCAAGCCGACGCAATACTAGGGCTGATTTATCGAGAATTAGCCTTA
          ACTCCAATGGCCCGCCAAGCCGACGCAATACTAGGGCTGATTTATCGAGAATTATCCTTA
          TAAGCTAAGATCTGGCTAAATCATTGTCTTACACGAGCGGGTCTATAAATGTTGCAGCGC
          CAAGCTAAGGCCTGAATAAAACACTGTCTGACAAGAACAGGTCTACAAATATTACGACGG

          TATTGTTCAACAAGGGACCGGCTATGGAGGACGTTCTCATTCACGTGTAACGCCACTGGA
          TATCGTTCAACAAGGGACCGGTTATGGAGGACGTTCTCACTCACGTGTAGGGCCACTGGA
          AACCTAATGACGAGTGAGTCGCTATGATCTATGACCTCAGTACGATAGGGAGCAATTAGA
          CATAGGATGTCATGAATACGCCCTTACAGCTAACCCTCGACACGGGGAGGATCAACCGGG
          TTACGTTTAGGGGAAAGGTGACCACGAACCATATATACGACATAGACCTCGGATTCATAT
          TTACGTTTAGGGGAAAGGTGACCACGAACCATATATACGACATAGACCTCGGATTCATAT
          CGGAACAAGATGGCGTAATAGGTACTTGGTATACTATAACGTCATAGAGCATGCCTCCCG
          CGGGATTAAGGGGCGGGAGAGGAACCTAGTCTACCATAGCATCACTGGACGTACACCTAG

          CTTGTCGGCCTTTAGGAGGCCCCGACCGTTGAGGGGCTAGCTACTTCCAATTTTGTGGGC
          CTAGTCGACCTTTAGGAGGTCCCGGTCGTGGAGGGGACAGCTACTTTTAACTTTGTGGAC
          GTCACGTGCCTACAGCAGAGGCCATCTGGAAATAAAACGACCACCCCCCTTCTCTCAAGC
          GTAACACACCGGCTATGGGGCGTACCCAAGCAGCAAGGAGTCGCTCACTCCTTAAAACAT
          GTGATAGGATTATAAAGGGCTTCGTCTGCTTAGCCAGCTGGTTCTGCCAATCTGCTCGTT
          GTGATAGGATTATAAAGGGCTTCGTCTGCTTAGCCAGCTGGTTCTGCCAATCTGCTCGAT
          ACCCGGAGGCGACCGTAGCGGCCCTCCGACACTCTGAACGCACATGCCTGTTTATTCACC
          TTCCTTCTACGATATTAGTGGCTGTCCGCTACCTTGAGCGCACTCGCCCATTTATTCAAT

          GTGTAGTCGTCTGTCAGCCTTGAGACAAGATATGATGCATGATCCTAACTATGCGTGTAG
          GTGTAGTAGCCTGTCAGCTTTGAGACAAAATATGGTCCACGATCCGAACGATACGTGTAG
          GTCTCGCAACACCTGAGGTTTTAGACAAGATCTTCGTCATAGTACGAACCAAGCCCGCGG
          GTACTGAAATCACTATGTCCTGTGACGAGCTCACACAACCGAGAGGACGCACGCACGCAG
          TCAACGGCGCCTTCCAAACAGCAAACGAAATGCCTCCATCGGAATAAACTATATGCACAG
          TCAACGGCGCCTTCCAAACAGCAAACGAAATGCCTCCATCGGAATAAACTATATGCACAG
          ATAGGGCTATGCTTACGCCTGCCGAGTCACTGCGCTATGCATTGTCCCTACAGATAGTAC
          ACGAAGCTATATCAACGCCGTCGGACTCATTACGGCTCGCATTGCCTTTCCAGGTAATGT

          GGAGTTAAGCTGCGGCTGTCTTTACGCCTCTGTGGCATAT
          CGTGTTCAGCTGCGGCTGTTTTTACGACGCTGTGGCAGAC
          CAGGCCATATGGCAATCATCCATGTCTTTTAGTGGTGGAG
          AGGGTGAGGTGATTGATGTTTGACAGCTCGCAGTGGCAGA
          TACGCCAGATGTTAAATAGTCCAATCCATCCGCTGCGGAC
          TACGCCAGATGTTAAATAGTCCAATCCATCCGCTGCGGAC
          CAGCGTACCGGAACCTAGATGAAGGGCTCTCCGCTTAGGA
          CAGATTATCGAAGCATAGATAAGACGATCTCTTATTAGGA

