 8 1000
t1        CAGCGCCGTTGAACGAAGGCAAGAGGAGGATACTCAATGTGTGCCTCTTGGCTGCGCCTG
t2        CAAGGCTATTGACACCAGGCACGAGAAGGTTACGCAATGAACGCCTTTTGGCTGTACCTA
t3        CTAGACTATCGTTAGCAGGCACGAGAAATCAACTCAATCACTGCCTCTTGGTTGCGCCAA
t4        TCAACCTGTCGGATGTAATAGCGAACGGTTCCACAAGTCGATATGTCTTGGATACTCACA
t5        AAACCTCAATAACTGTAAGTGTGTTTAACCGCCCTAGCGGCTACCTTGTGACAGCATGTG
t6        CGTATGCAATAGTTGTGAGTGTGTCCAGCCGCCCTAGCGATTGCCTTCCGGCAGCGTGTG
t7        AGGGTCAAGCTGTACTTGCAGTACTAATTCTCACCAAGGTATAAGCTATGACGGCGCTAA
t8        CGGGCCAGGCTGTGATCGCAGCTAAAAGTATTATCATTAGTCACATCGAGGGGGCGCCGC

          CGTCTACATTTTGACCAAGCGCTAGCCGTGTTCAGAAATTCACCCCTTACATTGCCGAGC
          CATATACATTTCAATCAAATGCTAGCTCTGTTCAGAATTTTACTCTTCACCTTGCCGAGT
          AATCTACATTTTTACCAAATGCTCGCTATGTTCAAGTATCCACCCTTTCCACTGACGGGT
          CTTGACAAATACGACCATGGGTGAGGAGCAAGTAAAGATACCCTTGTTGGGGCGACGAGG
          CCCCCCTCTATCAGCCACATTTCCGAGCTAAGTGCGCTTGGACACACCGTTAGGGTGGGG
          GCTCACGTTGCCAGTCGCAGTTCTTAGGCTAGCGAGCCCGAACACAGCGTGAGGGTGGAG
          CTGCCCGCATTGACCTCTGTGTTCGCAGTGTAAGCGCACGCGTCCCCACAATGCATAAGA
          CTCTTTGCCTAGGTCTACCAGGCAGAGGTGGTTGTTTAAGTGCCTCCAGAGAGTGTATGA

          ATTTTACTGTTCACGTGTCTACATAACTATGTAGGCCCCGCTAAGTGCCCTGTCCTAGCG
          ATTTTGTTATTCATGTGTGTTCATAGCAATGTAGGCCCCACTGAGTGGCTTGGTTCAGCG
          ATTTCGCTATTCACGTGTATACTTAGAAATGCAGGCCCCGCCATGTGCTTTGGTCGAGCG
          AACCCGTTAGCGACACTCCCCTCGAACGATGAGCGTTGCGATCAAGACCTGAGTTCAAAA
          GGTGCACGAGGGCGAACATCTCCGTCTAAAACGCACCCGGAGGATCGCCCGAGCCGAAGT
          GGTGCGCGAGGGGCACAGCCCTCGTCTGGAACGTCTCTGGAGGGTGGCCTGGGTCCAGGC
          GAATCATGGCCAGTCTCCTCGCCGTGTTAAGGGTCTCAGGATGCTGTACAAAGTTGAACC
          GAGCCGCATCTAGTTGATTTGTCACGTCGGAGATTTTAGGAAACCGGATAGCACGGGGCT

          CGGGTCGTCTGGGTCGCGGGGATAAGGGACTACCGTAATACCGGATAAAACGGATACACG
          CGGGTCGTCCGGGTTGCGACGGTCACGAACCACCGTAATACTGGATAGAACGGATACAAG
          CGGGGCGTCTGGTTCAGGATGAACTGGAATTGATGCGATACCGGTCAAAACAGACACACG
          CGAGTTGTCTTGAACCTCATGTCCTGGGGCGGTTTAGTGGCCATGTCGGACTTTAGGGTG
          GAGGTCGCCTCAACCTGCACGATATACGACACACGGGAAGCTGCGACGAACTCTTGACCA
          AAGGTGGGTTCAACCAGCACAATGTGCGACTTATGGGAAGCCGCGACGAAATCTTGACCG
          GGGGAAACTTCAGCTAGTACGGCAGGTCGTGGACTCGATACTGTCTCAATTACTGTGATG
          GCGCAATCCTAACTTAGTGAGGTAGATCGTCGGCACAATACTGTCATGGGCAACCCCAAG

          GCAAGGTTGACGATACCAGGATGCAGAATCGCCACCCGTCCATGAACCTCTTTTGCCAAA
          GTAAGCCCGACGACCCCAGGATGCTCATTCTCTTCCTGTCTGTAAACTTCCCTTGCTAAA
          TTAAGCTTGACCACGACAAGATGCATATCAGCTACCTGTCTATAAACCGATTCTGGTAAA
          CTGCGCCGGATAGCGCGCGTCCGTGCGGAGACGGACTTATCATTTTATCATTAACGGCTG
          GTAAGTTCCATGATCAAAGCCATCTCGAGCGTAGAATACTCACTTCCCTTATACGTATCG
          GTAGGTTAAGTGATCCGTGCTGCCATAAGTGTAGATTAATCGTTTTCTTCATACGCGTTG
          GGCACCGAGAGGCCCAGTGCAAGAGCCATGGGGAACCTACACGAACGCTCTCACGGGACA
          TACCCTCACCTGCAACCTTAACAGCTCATGGGGAGTCATTGTGAATATGCTCGTAGAACA

          CTACATGGTGCATTGCCCTGGGTAACCGTAAGGATCGCTTTTTTTAAACTTCCCTTTAAG
          TTGCACGATTCATTGCTCCGGGTAACCGTGCTAATTGTGGACAATGAACTTCCGCCTAAG
          CTTCATCCAGTACTGTTCTGGATAGCGGGACGGAAAGTTTACAATCATCTTGCGCCTAAA
          GCCACCTAAATATTCCGTAAGTTCTGTACATAGTTCGACACTAACAGTCTCGTGTCCCAG
          GTTCGCGTCCCCACGCCCCGTCTCCTTGTCCTCGTAGCTGTTAATACTCGAACAATTCTG
          TTCCGCGGCCTAACGCACCGCCTACATGTCTCCGGCGCTGCTTATTACTGAACGGTCCTG
          GTTGCTGGGCTTTTTTACTATAAAGAAGGAGGGTTATGTATTACGCTCTTTACAGTTACC
          CCTCTCATGCTATTGTGCCGGAAGGAGGGACAGTATGATAAAACCCCTCCTACATCCTCG

          ATCCGATATGGTACAACTAAACACCGGAATTGAGAGGCGACCGCAGTCTGAGGGAGGGTG
          ACCCAATAAGATACACATAAGCGTAAGAATTGAGAGGCTACTGTGGCCCGGGGCAAGGTG
          CTTCGTTATTGTATAAGTAAGCGAACAAATGGAGAGGACACCAATGCTCCGGGGAGGGTG
          ACTTGGTGGACCAAAGGTATGCACAACAGTTGAGGGGCTACCGCGGCGTAGAGGATAGAA
          TCAAGCCGACGCTGCAACGTGAGACTAATAGGGTGGAGTACCATGAAACGAAGTAGGATG
          TTAAGACTACGCTGCGACGCGTGACGTACGGGGAGGTATACTGTGAAACGCAGAAAGACG
          TGATAACGTCAAGTAGAGCCACGTTGCGGCAACGGCGCCCGCACATCGGGGGGCGGGCAC
          AGACCACGTCGAACTGGGTTGCGCCGGAGTAAACCAGCCGTAGCATCAGGGGGAATAGGG

          TGTTAGATCGTTCATCTCCTGTAACGATCGGCAGGAAAGTTGACTAGCACCGTATTTACA
          TGTTAGCTAATCCGCATCCTGTAAAGAGCATCATGAACGTTGACTAACACCGTTTAACAA
          TGTCGAACGATCCATCTCATGTAAAGACCGTTATGAACATTATGAATCACTGTACATCTG
          CAGCACGCCGACCGATGCTGGATGAGAATATGAGAACCTATACCTCTCTGTACATCAAGG
          TAATCGTATATATGTTGCTTCTGCAGATACGGGAATACACCACCTCTCGTGGGGCCGCGT
          TGCTCGCCTATATACTACCCCCACAGACGCGGGCACACGGCATCTCGCGAGAAGTTGTTT
          CGTCTATCGCTTCTGAGAATGGAGATGTCGCCGCACCAACTGTCGAGTAGCATGATTACG
          CGACCCACAATCTGGAATTCGTAGATACCGGCGCCCCCTCCACCGATTATGATGCTTATG

          TACCAGCTTAAATCCCGGTGGCCAATGCCATAAACAGGAATTTGGGGATGTACTTTGACA
          TACCAGCTTAAATGCTAACGGCCAATGGTATCGACAAGTGTCTGGGAGTTCCCTTTGATA
          TTCCAGCCTAAAGACAAGTGACCGATGTTATCGATAAGAATCTAGGAATGCCCTACGACA
          CGCCCGTTGAGGGGCTAACAGTGTCCCCGATCTACCAGAACTAGGGGACTAACATCGGCA
          CGCTCGGTACGCGGTTCATGCGAAGCTAGGCCCAACAGTATTTGGGAATGCATGAGAACA
          AGACCGTTACGCGGCTCATGAGAAGCAAAGTCCACCAATACTTGGAAAAGAATGAAAGCA
          GGCAAAGCGAAGAGCAGTACGATTGCACCGCGACTTCCCAGGCATCTGTCCCTAATGCAA
          GGCCAAGCGAGAAAATGTCAGAACAAAGCATCACAGGATATCTTGCTGACTCTTTAGGAA

          TCGTGATCGTGATCTCAGTAGAAATCGTAGGGTCCTCGCGCGCTATTTGTCGATGGTATG
          CCGTGATCGTAATCTTAGTAGAGCTCGTAGAGTTCTCGTGCGTCCTTTAGCGATGGTATA
          CCGTGCTCGCGGCCCCAGTAGAACCTGTAGGACCCTGGTGCGTCACTTATTGATGGTGTG
          ATAAGGCGTTGGATGTGTCGTGGTCCGACACCCTCTTCCGTTCCCCCCGCTCGGGTTAAT
          ATAAGATTGTTCGGGATATACGCATCGACTCATCCTTCTACAATCTACCTAAACTAGTAG
          ATATGTAAGTCCGTGATGTGCGCATCCTCGAATCCCTTTAGAACCTACCTAGACGAGAAG
          CCGCAACATTATGGCCACCGCACTAGGGCGCCGTTACACCTGCTCCTTGCGGACGTAGTG
          TCGCGTCACAAGGTGCACAGTAAAGCGTTTCCATCTCTCGCACTCCCCTTCGGCGTAATG

          TCGTCCGACATGGTATAGGATTTTAAGAATCGCGCCCACCTGTACTGCTGTTCGCTGCAA
          CGGTTCGACATGGTATTGGATTTCACGGATGGCGCCCACCTGTACTGTTCTTTGGTGCAG
          CGATACGATACGGATTTGGTTTTCAAGGATAGCGCTCACTTGCATTGATTTTCGTAGCAA
          TGATCATATACTAAAAAAAGCGGTGCCGCCGATATTTAGCCATAGCCGCTCACGATCACA
          GGAGCGGGTAGTCAAATGGACCATAAGGGCGAAGTGTTGCGGGAGTACTCTCCGCTGACC
          CGATAGGATAGTCAAATGGATCCTAAGGCCCAAGTTCTTCAGGCTCCATTTCTGCTAACC
          GAACACGCTTAGAATCGGGATTCATCCACGGCTGTGATGTCACCACCGATATAGATCGTA
          GTATCCGATTCTCTTCCTGAAATGGCGACTGCTACGGTGCCGCCTCCGAAAAGGTCCCTA

          AGGACTTAACAGACCGTATAAACACTGGATCTCTTCATCCCATTACCTATGGAGCAATAC
          AGAACACAACAGGCTGTATAAACGCTAGAGCTCTCCGTTCTGTTGCCTATGGAGCAATAC
          CGGATCCAATAGACTGTACAAACGCTGGCTCCTTTCTGTACATGGAGTATCGAGCGACGC
          AAGGAGCAATAGCTCTCATTAAAGACACCTTCTTAGCAAACCTTGGCCGGCGCTTGGTGC
          AAGAAGCCCTCTCCCGTATTCGAACTAACCGGACTCTCACCAGTAACAAAAAGGTGGTGC
          AAGTAGTCCTCTATTGCTTAAGAAGTAATCAAACCCGTACCTGTAATAAATGTCTGGCGT
          ATGCTGTAGACTTCCACGCGAGAGGCGGGATCGCTTTATCTGCAACCAAACTGTCGACGC
          CCGCTGCAGATAAGTGAGCGAGAGAGTTAGCCTTTTTGCTTATAGCAAAGCCTTGGGCGT

          GCCGCAGGGTTGTATTTAGTGTAGTGGGCGTGTATGGTGGGAGTATGGCGTATCCTGCTG
          GTTGCGGAGTTGCATTCAGTGTAGTGGGCGTACACAGCACGAGCATTAGGTATCCGGCAG
          GCTACAAGTCTGTATGTGGTACAACGGGCGTACGCGGTGAGAGGATTGAGTGTCAGACTG
          GTCGGTAGCCTTAATTCCATATCTAAAATATGTAGGGTGTGACAATAATCCGTCAACTGT
          GCTGCCTGAGACAACTATATCTTTTAGAGAGGCGCCGTGTGAAGCTTATAGATTCCCGAC
          GCGGCCAGAGCCAATCGTATCCGCCAAAGAGACGGCGTGTGAAGCTCATGCTTCCCCTGC
          GCTCTGCGACAGGAATTATCATCATTATGGGACACTAACGATTAACAATGTGCTAATCCC
          GTGCTTTTTCAAGGCCTAACATGGTCACGGCACGCTAACTGCCAACACCGTACTAACCCC

          AAGGCGCTCGTCAAACACACGAATTTCTCGGAAGTACGCCTGACGTGCATTCCCCAAATC
          AGAGCGTTCGTCAGACGCATGAACTTCATGAGAGTACGCCTGACGTGCCTTTCCCAAATC
          AGGGCGGTCGGCAGACACATGAACGTTACGAGAGTTTGTCTGCGGTGTACTGGTCTGCTC
          AAGAAGTCTACGGACTACAGGTCGGGCAGAACATTATATCTGTGAGACTATTTAAGAACC
          GGGGTGATTGTCTCGAAGGTCTTTTTTACGGAGCGGCTGCTGTCGCGGACGTTTCACACC
          AGGGCGGATATCCCGTGGTTATTTTCCACAGAGTGGCTGCCTTCGTGGACATTTCCTATC
          GGGTTGTCCGATAGGTCGATGTATTGTAAGCGACGGAAGACGACCTATCCTTCTGAACAT
          GGGGCGCCCCATGGGTCGCTGCGTGGCGCGAGATCTAAGCCATTCCATCGCTTCGGACGC

          AAACCTGATTGCTGGCTGCCTGCTCATGGTTCATCTTTCCGGTTCGCAATCTCAGGCACG
          AAACACGATCGCGGGCTATCTGCTCATGGTTTATCAGTTCGGTCAGGCATCTAAGACGCG
          AGATACTATTACCGGCCAGCTGTTCATAGCTCATCTTTTTGGCCTGCTGTCTGAGACGCA
          AGAAGTGTTTGTCGGCAAGGTGTTCAAAGCCATTTACAGGAGCTTGGTTGTATTAAAAAG
          TACTGCTGTAGACTATCACTAACACGAAGCTAACTATGCCAGTTTGGTCCCTCTGATAAG
          CACTCCAGTGGACAGCCTTGTACATGAAGCTAACGTTGTCGGTTTAGCCCCTCAGAAATG
          CGGCTTTGTGCTTGGCGGTGTCGTCATGGCCCAGAACGTTCCGCGGTCATTAGAATAGCT
          CGATACTATGTCGGGCATTGCTAACTTAGACAGCGATATCCGTCCGTTGTCCGCGCCATC

          ACATGGTCGTGGACCGTTACAGAACCAGTGGATATTTTTGCGTGCAGGCCCCGTCGCAGG
          ATACGGTCGTGGACCGTCACAGCAGCAGCGAATATTCTAGCATGCAGGCCCCCTCGCAAG
          ATATGGTTATTGCCAGTTATGGTGTCGACGGGCATTTTTTCGTGCAGATCTCGTCCCACG
          CGATGCCTGGTGTCATATAGTACTACCGTGTTCCTCCTTAAGTGTAGGTGTCACTCCGAT
          AGGCGCAAAATGAATGTACGAACAAAGGTATGGAGTCCCCCCTGTGGGTCCTCACTCGTA
          CAATACAAAATCATCGTACGGACAATGGTATGGCACCCCCCATGCGGCTCTTCACTAGTA
          CTATATTTGGCGTCGGTTTAATCAAGGGCGTATTCATCCTATAACGTATCACTGCAGGAT
          CCGAAGACCCAATCCATTTAAAACTAGACACAGACTCTCTACTTCGGGTAGCTCTTCAGA

          CCACAGCTAACTTAGGGGCTTACTCTGCACACACAGCTCC
          CCGCGGCTGACCGAGGGGTTTACTCCGCTTCCACATTTCT
          CTTCAGGTTCCCCCAGGACGCACCCCGCAAACACATTTTC
          ACCCATTTGAGCGGAGGCTCCGCATCGCAATTATATGGCA
          AACCTGTACTGCTGGAACCCTGCTTGGGTGCGGAACTCTC
          CGCCCGCACTGCTGAGCTCCTGTTTAGATGCGATACCTCT
          CGCTCGCCAAGCCGGGCTCCCGGAGAGATGATGCCCTATA
          CACTCGTAAAGTTAAGACCGCGGAACTTCGTGTCCCTGAA

