 8 1000
t1        CGGTCCGCCGCATGCGTAAACGCGAGATCGATTGCGCGGTAAAGATTGGCTGACACTAGT
t2        CGATCCGCCGCATGCGTAAACGCGAGATTGATTGCGCGGTAAAGATTGGCTGACACTAGT
t3        GATTCCTCATCAAGATCCGGGACAAGGAATCCTGACAGTTCAGAACTAGAGCCTGGCCCC
t4        GGTATCGCTGTAACGATAAACGTGTGGGAGACAGTATCACTAGGGTAGGCCAGTGCTGAA
t5        GGAACTTACTAAAATAGTGGCAAGCGCCACATTGCCGGACCAGCGTCAGCGAGTGTCGCT
t6        AGAACTTGCTGAAAAAGTGGCGAGCGCCACATTGCACGGCCAGTGTCAGCGAGTATTGTC
t7        GGCGTCACCATAAGCTCTGTCGTCCGCGAAGGCCTCCCAGTCGGGCTGCTAAGCGCCCGC
t8        CCCGCTATCTCGAGTTCCAACGTCCACTGAGGCATCTCAGCCAGCCTGGCACGCGCCGGT

          GATAGGCGAGCCCCGTGGTAACATGGGTCTCTCCTTCATAGTCTGGGCAAACTTGTTCCA
          GATAGGCGAGCCCCGTGGTAACATGGGTTTCTCCTTTATAGTCTGGGCAAACTTGTTCCA
          CAGGTAAGAGATGTGGACACTTCGTCGTGTCGCCTGTATGACGTGAGCTTGACTGTCACC
          GGTGGAAGAACTGGAAAGAGTCCCAGAACGCTGGCTTGATGCATGTACGAAATCATTCCT
          AAGGGGGAACACATAACACCGTAATAATAAATGGAATGAGGCGGTTGTGTACACCGGCTA
          AAGGGGGCATACGTAAAACCCAAGTAACAAATGATATGGGGCGCTCATGCATACGGGCTG
          GAGCGGCGAACTACGGGGCTACGGTAAATGGCAAGGGTCGCATTGCATGTAAAGATGATC
          AAGCGGCGACGCAAGGAGTGACTCGAAAAGGTAGGTCCCGCATTTCATGTACTGATGATC

          AGCAGAGGCGAGGGATCGACGACTGTCACCAGATTTGATAGTGAGAGCCCATCGAGAACT
          AGCAGAGGCGAGGGATCGGCGACCGTCACCAGATTTGATAGTGAGAGCCCATCGAGAACT
          CCTCGGGGTCGGCGGGAGGTACGTCCACCTCAACCGTCCCTCGGGCGAATGCTGTGACGA
          GGCTAGCATCAAGAGTATCCAGTCAACCCGCGCCTGTGGATTGAAAACTATTATTATCAT
          CTATGGGGTCTTAAGTGGGGCATTCCTTGTTAAATCATAATCGTAGTATACTCATGTCAA
          ACTTGGGATCTTAAGTGAAGCCTCCCTTTTTAATTCAGAATCGTAGTACAGTAATGTCAA
          CCGTGGGTCGCGAGACTGGAGAACATTACCTCGTTGAGTATTACGATTCCGCCCCGAATT
          CAGAGGGTTTTGAGGAAGGTGTATCCCACCTTAGAGCATATTACAAACAAGCTGCAAACT

          TCATGTAAGCGAATCTTTGTTTTACGACCGCAAGCCGCCAAAGTAACTGGCGTACGAAAT
          TTATGTAAGCGAATCTTTGTTCTACGACTGCAGGCCGCCAAAGCAGCTGGCGTAAGAAAT
          ATTATAAATGACCGACCCATCTCGTGACAGCAGGCGATAACGGTGGGAGTTTTCCAAGGG
          CAAAAAAAGCATTGAACCTCGCCATGTCACAGCACTAAAGGCCCGAGACAAATACACATG
          TTTAGAATTCTTCGCCTCGGTTGTTGCCCACGAGATATGTCAGTAGATAATGAATTGACG
          TTTAGGGTTCATCGCTTCGCTTATTGCCTAAGAGACTCGTTGGCGGGTCATGAATCGACG
          TTTAAGAGCTGCCGGTTGGCTCTCAGGTCGTGAAGGTTACCCCAGTGGCATGCACGAAAG
          TCCAAGATAAGCAGGCCAGCTCTCTGGCAGTGGGATGGAAGCCGGGGACGCGTGCGGAAG

          GCTACTGGTAAGTTATCGTTGGATGTCCCTGTAATCATCCTAGACAACGGCAGCGCACAT
          ACTATTGGTAAGTTATCGTTGGATGTCCCTGTAATCATCCTAGACAACGGCAGCGCACGT
          CCTAGAAGCAAGCTGCTTCCTCGCTGCCTTCCAGATGCTCTAGTTTGTAGGTGTCTCAGC
          ACAGACGGCTGATCCCAGCCGAGCCTCACGACTAGCCCCAAGAATCATGCCGACGTGACG
          ATAATTCCCTTGCTTCAAACATGCGAGGCTGTTATAGTTCTGGCATAGAGACGGTTGTGC
          ATAAATCCCCTGCTTTATCCATGCGAAGTTGTCTCAGCTCTGGCATTGAGGCGAGTAGGC
          ATAGCCCGCCCGCTGTAGAAGCTGCTTCTAATCATCTCACAACCAATTAGCATAAAGGGA
          ATGGATCGACGCATGTAAATGCTAATTCGAATCAACATGCTGCTAGTCATCGTAAGGACA

          GGGCAAAGGATTGGGCAGGATTCCACTCATAGACACTATCGGGGAGGCACTGAGGATCGG
          GGGCCAAGCATTGGGAAGGATTTCACTCATAGACACTATCGGGGAGGCACTGAGGATCGG
          TGGCAGAATTTTTTGCGGAGATGAGAACTTAGTGATTAACTAGAGAGGAAAGGATTCTAC
          TGGCACCAACTCGAGCGGGTCGTCGGACATGGAGGCTTACTGGGCAGGGCAGATTTCTGG
          TAGTACAGTACCGCATGGCACTCCGGGCCGGAAGATTATCGGTGGGTCATAGCAATTCCT
          TAATACAGTACCGCATGCCACTACGGGTTGGAAGATTATCGGTGGGTCATAGCGATTCCT
          TTCCCAAATCTTACATTTAGGAGTAGTAAGGAACGGTTCGTGGAAACCGGACCCGCCTAC
          CCCTGAACCTTGATATATGGGCATCATGGGAAAGGGTACGTAGGAATCAGACCCGCCAAC

          GGTAAGAACAATCATCAATTCATGAGCCTACGTCGCCCTCATAATCAGGGACTAGGGGCG
          GATAACAACAATCATCAATTCATGAGCCTACGTCGCCTTCATAATCAGGGACTAGGGGCG
          AGCGAGGCCTAATAGTCGTCAGAAACCTTATTTTAGCCCTCCAGGTTAGAACTCATTTGA
          CGTCGAGACCGGGGATTTCGCTCTGTAGAATAGAATGTTTTTAACACTTGTTTAAGTTTG
          CCCCAGTCTTGCTAGTGGCGAGCTATCGAACCGTACCAACTTAGTAAGTATCTGGCCGCG
          CTCCAGTCTTTCCAGTGGCGAGCTATCGAACCGTATTAACTTCGGAAGTATCCGACCTCG
          TACGATAGGCCCTAATTACGATGAATCCTACCTTGCCTCGCCGAGATGCAATTGTCCTCA
          TGCGATAATCGGTAACCGTAATAAACCTACCAGCGAGTCGCTACGTGGAGACTGCCCTAG

          ATGATCTTATCTCGCGATCTTTTTGCACAGCCTGGTACCTTGACCCCTTACATCACGGGG
          ATGATCTTATTTCGCGATTTTTTTGCACAGCCTGGTACCCTGACCCTTTACATCACGGGG
          TGCCTTCAACCCTGGGGGAGGCGGATATGACATCGAGCCCCGCTCACGCCCCTTCAGTTA
          TCTCGCACCGCTTGGACAAGGCTCGTAAAGCTCGGGATTCTCTGTTTCCCCGAGCGGTTA
          TCTAACCTGTGGTGAGAATGGCACGTATGGGCCGATACTCTGCTTTTCTATGTCCGGCTA
          TCTATCTTATCACGAGAAAGGCACGCATGGGCCGATACACTGTTTTCTTATGTCTAGCTA
          AGAGCCCACCCCACGGCTAAATCAGTTGTGCTTGGTATTAGCCTTGTATTAAAACGTCCT
          GGAACTTCGCCCACAACTAGGCGACACCAGGTCAGGAAAAGTTTCGCTCTCGGGTAGCTT

          AAATTACATTTGGGCTACTAGAAGCCGGGTAGGTTTAGTGACGGCCGTGGGGCCAAATAA
          AAATTACATTTGGGCTACCAGAAGCCGGGTAGGTTTAGTGACAGCCGTGGGTCCAAACAA
          GCCCTAAGTTTTTGATCTACGCAATGGGGCGAGTCATAACGTTAGTCTAAGATACGGTAA
          TCTGGCAGGTGTCCTTTTACGGGGTTACAGGGGCTTAGCTGATAACCTAGAGTGAGGTAG
          TTACGGGATGTCGTCCACGGTTGACACGGTACTCTACTGCGACTGAGCGGGACCAACTGG
          CTATGGGAGATGGCCCACGGTTGACACGGTACTCCACTGCGACTAAGAGGGACCAACTGG
          GCTGTGAGCCGGGACTCCATTGAACCACGATGAGATAAGTGAATGTGCTGTCCAGACGTG
          GTTGGGAGCTCTGATATAGCTAGGGCCCGAAAAAATAAGTGAGTGCGTTGGGCAGAATTA

          AGGTCCAGCTAAGAAACGGGTTCTTTGAATCTACAACAGAGATGGATGGCTTGGTCTGGG
          AGGTCCAGCTAAGAAACGGGTTCTGTGAATCTACAACAGAGATGGATGGCTTGGTCTGGG
          ACTCGGGAATAATTATAATATGGCTTAGGACCACCGTTCAGCGCGGTACTATCTCTTTAG
          CGGCATCCATAACCACCAAGCTCTGCCTTTGCGTAGATAAAGGATTAACTTTGACGGACG
          AAACAAGCATAACGACGGTTCCTGCCAGGGGGAGATTATGGAGCAATTTTAAGACTTAGG
          AGACAAGCACAGCGTCGGTCCCCGCCAGAGGGAGATTATGGCGCGAACTTAGGGCCTTGG
          TAGTTCGCTGTGTACTGGGGTAGCCAGTCTACGCAATTGAAGACAACCGTGCGCCAGTAG
          AAATTCGCCGCCCTACGGAGCGGCCTGACTACCCAGGCACAGGTAAGCCTGTTATAAAAG

          AGGTGATGATCGGTCTTGCTGGCATTCATTGATGGTCGCTCACGAAGCCTGGCAGTTAAC
          AGGTGATGATCGGTCTTGCTGGCATTCATTGATGGTCGCTCACGAAGCCTGGCAGTTAAC
          GCGTTGCACTATGTTACGTGCAGGCTCTTCGTCGCAGGTGCCTGAGCACCGTGAAGCCGT
          ACTCCATATTTCGCTCAAATGGAGATCGCCGGCCTATTCGTCCGAACGACGCGTACATTT
          GGGTGCTCGGAGAGTATGCTTCTCTTCACCCATGGCAGGCGACGGATGCTGCGTATCCGT
          GGGTACCCGGAGAGTATACTTCCCTACACCTCTGGCAGGCGACGGACGTTGCGTATCCGC
          ATGTAACTCCCAATTTTCTCATTGCTCGCCCTGGGAGGGACACACCCAATCCGGGATTCT
          ATATAGCACTACTTTTTTTTAGCGCTTTACGTGGGTGGCACGCGTTCGACGCAAGTTCCT

          TAGGGTGCGGAAACATATACGCCCCAGATAATCGCTACTGTGATCGTCCGATTTATCTCC
          TAGGGTGCGGAAACATGTACGGCCCAGATAATTGCTACTGTGATCGTCTGATTTATCTCT
          ATAGGCCTTCAGAGGCAACCATATTTAGTGCTGAGAATAGCCGCTTGACTCCCCCCTATA
          GGCAGATTGTATCGATACATATGCCTGGCCTATGGCTTAGCTTCTCCGCCCCACATGTCG
          TGAGAAGAATGCGCATACACGCTCGCAATAGAGAGTCATCTCTCCTAATGAACCGCGACC
          CGAGAAGAGTGCGCATACACGCTCGCACTAGAGAGTCATCTATCCCAGCGGACCGCGACC
          GCCCGTCAACATAGGCGGACCCTTGTAGTATTGACTGCCCTAAATTTCTTGCTCAGGCGC
          GACCGCGCACTGTGACAGACGCTCGTGCTATTGGATGCTTGGACTCCGTCTCCCGTGCGC

          TTGCGCTGTGTCCTTGGCCAAAACGCGGTAGGACATCCCCAACTTGGGCGGCGAATGGAT
          TTGCGCTGTACCCTTGGCCAAAACGCGTTAGGACATCCCCAACTTGGGCAGCGAATGGAT
          TCTGAATCACCCAAAGGTCGAGTGCCTGTACAAATCGCGTGTTCTAGGTTACAGAAAAAT
          TAATATTCCCTCTGAGTGCGGGAACTCCCAGGCTCTTGTTGATGTTGGAGGGGGGAATAC
          AAGTAATTAGGCTCGCTCCGGAACCCGTGAGCTAACCCTAGGCTTTGCCTACCGAATAAA
          AAATAGCTAGTCCAGCTCCGCAACCTGCTAGCTAACCCTGGGCCTTGCCTACCGAAAAAA
          AAATGTACATTCAAGGACAAGGCTCGATTAGAAGACAGTGGTCAAAGCTCGGGGGCGCCA
          AAAAATCATTTCATGTGTGGGGCCCTATCAGAAGTTACCGGCCATAGGTCGGAGGTGCTA

          ACTTAGGAGTGTCCGGACCCGTTATAGCCCCTGTATCTCTGAGCTGCCGAACGGATTTTT
          ACTTAGGAGTGTCCGGACCCGTTATAGCCCCTGTATCTCTGAGCTGCCGAACGGGTTTTT
          CTTCCGAGACCTTAGTGGCAGGGATTATCGCATCGCTCTTTAATGAAGGTGCGAAAGAAC
          CATCGTGATGGACGAGCGCGACACTTATCCAGGCATAAGTGAATAACATTAAGGAGCCAT
          ACTTGGGCCTTTTGAGCACTACTTTCATTTTGATTCGTATTGTTGTCTCCATGAGACAAA
          AAATGAGCCTTTTGAACACTACTTTAGACTCGACTCGTATCGTTGTATCTATGATACTAA
          TCTGGCAACCGCCCTGAACGTCAGCTACCGCAGATATAGCGAGCGGTCATAAGTTGCAAT
          TCCTACGACCGTCCGGAGTAACACGTACCGCAAGTAGGTCAAGTGATCATGCGACGTACT

          GGGTCTCTGTTTTGTGAGTAATCACAGGACTACTACGTCAGATAGCTTTGAACAACTAAT
          GGGTCTCTGTTTTGTGAGTAATCACGGGACTACTACGTCAGACGGCTTTGAACAACTAAT
          TACGCTTTATTTTGGGCCCGTGCTCGTTGACGTACTTTCATAATTAGTCACACTGTTTTC
          GGAATTCACTAATCCGTTTCTGGTAAACTGTACGTCGCCGAATACGCGCAGAGTGCCGGC
          CCCGTTTCGTTGTTAGTCTCTGGTCCGAACGTTACCACTGGATAGCTCTCCGTTGTCTTC
          TCTGTCTCGTTTTCAGCCTCTGGCTCGAACGTTACCTCTGGATAGCTCCTCGTTGTCTCC
          ACTAGATTAAAGAGTGTCCGCAGAATAGCATAATGTGTCAAACTGTCTTGCGCTATTTCT
          TACGCCATATATAGAGCCCTCTGAGCAGTGTGTCATACTAAATTGGCATCCCTAGTTTCA

          ACACGATACACTTTCTGCTGGACTCTTAGATCCACTCAGTACTATTCCAATGCCCGGCCT
          ACACAATACACTTTCTGCTGAACTCTTAGATCCACTCAGTACTTTTCCAATGCCCGGCCT
          AAATAAAGGACATTGGGTCACATCTCTCAATGTCGATCTTGCTTGGTTGTGCACCGGACA
          GTGCCACAGTTACCTTGTTGAAGCGTTAGGTACTATCTGCTCTTGCATTGCGATCAAGTC
          GCGCGACTCATAGCCTACTGAACCCATGGAACACCCCAGCATAAGCTCCATAGCAGGGGC
          GCGCGACTCATAGCCTACTGAGCCCATCGAATACCTCCACATAAGCTCAATACCTGGGGC
          CTGAAAGAGGAAACTTTTTAACTCCCCAAAAGCATATCGTTTGCCACCTCCGGACACGAC
          CTATAGGAGGCATCGTCCCCTCCTCCTAGAAACAAATCGCAAGCCTCTCCTGGGCAAGAT

          AAGGCCATTCATGAGACACACCTGGATACCTCGGGATTGT
          AAGGCCATTCATGAGACACACCGGGAAGCCTCGGAATTGT
          TACACCTCTCGGAGGGGTTTACCGGGTCGGATCGGGAAAT
          TAATTTAAACGCTGACTGCGGCTCCGAATCTTAGCAAAAC
          GAGACAATTCAGAAGAATCGCTGGCACAAGTAATGAGAAT
          AAGACAATTCAGAAGAATCGACGGCACATGTAACGAGGAT
          GCGTTCCTATAATAGATCTGAGAAAAGATAAGAGTTATCC
          GCGCCACTCCAAGAGGTATAAGCGTAACTGAAAGGGGCTC

