 8 1000
t1        CTGTGTGAAGGAAGATAGAAGTCCCGTCCGATTTCTACTGGGACGCACATAAACTGCTGA
t2        CTGTGTGAAGGAAGGTAGAAGCCCCGTCCGATTTATACTGGGACGTGCATAAACTGCTGA
t3        GCGTAAGTATCTAAGTGGCGCTTGTTCCCAGCATCAAGGGTGTTGTAGAGGAACCGTGTA
t4        GCGAAAGCATCTAAGTGGCGCCTTTTCCCATCCTCGAGAGTGTCATAGAGGAACCGTGTG
t5        GCGCCCGCAGACCGGGGGCGGTAGCATTCTACATAATTCGGACGTCCGATTCACCTTTTG
t6        CTACTTATGGCTGTGTGGTGGGAGACGCCCATGTGAATAGGACAGTGCTATCGCCTGCGG
t7        GCACGTGTGCTAATATGATAGAAGCAACTGTTATGTACCAAGTAGTGGTAATATCCTTTA
t8        GAACGCGTGCTAATAAGGTAGGAGTAACTCTTCTGCACCAGGTAGTGGTAAAACTCCCTA

          CCCTGAATGTTTACGAAAGCGGTCCAACGGGTGGATTACAATTTAGCTATAAACGGTGAC
          CCCTGAATGTTTACGAAAACGCTCCAACGGGTGGATGACAATCTAGCTATAAACGGTGAC
          GTACCAACGTCTCAATCTTACACGTGGACCAATCAGCGCTCATGACTTATCAGTGGCCGC
          ATCCCCACGTCTGAATCTAACACGTAGAAAAATCAGATCTCATGGCTTAACAGTGGCCTC
          GCTAAAGTGGCTCCTAAAACTAGAAATAAAAAATGCAGGAAAGCTGCAATCTGTAGTCAC
          TCACGGGCGGTCGGTAAAACGGTGGATCAATAGCGCCACCATCACACAGTTCGTGGGCGC
          GCTCGGGGATACTCTGATATCGTTGGAAGCGCAGGGTGGGGTTGAGCTGCTGGCAGACAT
          GCTCGGGAATTCGCTGATATCATTGGAGACATTTGATAAGGGTATGTTCCTTGCGGACAC

          CGATAGATGGGAACCCTAATATCCAAGCTTCATGCCTTTCTGTGGTGGAAGGGTGCCCGT
          CGACAGACGGGAACTCCAGTATCCAAGCTTCATGCCGTCCTGTGGTGGGAGAGTGCCCGT
          TGATTAGATACAGTGGTAGAACCATTTAACGCAGAACCTCTCTGTAGTAGGGAGGAGATG
          TGGTTAGATAAAGTGGTAGAGCCTCTTAACGCAAACCCCCTCTGTAGTAGGGAGGAGTAA
          AGGCCTTAAAACGTGCCAGTCTTTCTCTCTATCCTCTGCTCGAGACGCCCTATTGGATCG
          CGGCTCGATGTCACTCCATTCCCGCGTTTCCTAATTAATAAGGGACGGAGGGTAGAAGGG
          TGGTCTCATGTGTTCTCAAACCTCTGCTGTGACTACAGCCCATTCGGCCGGAACGGCTAG
          GCGTGTCACATCATCTCAACCCCCCGCTGTAACTACAACTCCTCCGGCGCGAACGGCTAG

          CTTAGGCTGTCTGCGCGCCTAAAGCTTGTTCGTGTTTCCGATCGATACACTCAGGGACTA
          CCTAGGCTGTCGTCGCGCCTGAAGCTTGTTGGTGTTTCCGCTCGATACACTTTGGGACTA
          TCAAGGTGTCCCACAACTTCGAGGCTTGAGTAAAGTTTAGGTGTAAATATCTCCAAGGTC
          CCAAGATTTCTCACGACTTGGGGGCATGAGTAAAGTTCAGGCGTGTACATCTCCAAGATT
          CAAGTACTCTCCGAATTCCGCGGGCGTCGACGTTTAGGGGCATACCGCATGTCTGTATCG
          TACGAGCTAGCCATAATCTCCAGCCTTAGAAACATATCCATGCGACCCGTACTCGCGCCG
          TTGGAGCCATGGTCGAATTAAGAAAGTAAATCACTCTGCACACAGCCCGCATTGGCTCTG
          TTGGAATAGTGCTCGAATTAAGGAAGTCTATCTCATCGCATACAGCCCGCATTGACTCTG

          TCCTGGGTATGTTCGACACCAGGCTTGACGTAATGTTCTATGTGCGAGGACTCGCCGGGT
          TCTTGGCTATGTTCAACACTAGGCTTGACGCAACTTTCTATGTGCGAGGACTCGCCGGGT
          GTTGTGTCTGCTGTAATGCGAAGCACACGATCGCGCTTAAGATGGAAGCGTGCTCGGAGA
          GTCCTGTCTGATGTAGTACGAAGCACAGGATCGCGCTTAAGATGGAGACGTACTTGGAGA
          GCGCTCTCATTTACGGGGTGGAACATGTGTAATTACCAGCGTCCAGAAAATCTATTAGAT
          TCCCAATCACTCTCGGAACGGGGCGTCTAGCACTGTCGGTGCGGAGACAGGTTTAAAAAC
          TTTCTTCCAGCTATTATGCACAACGTCTAGCATCGGGTGCCGCGGGTACATCCTCTAAGC
          TTTCTTTTAACTTATATGTTCAACGTCTAGTATCTAGTGCCGGGGGTACATCCTCTAAGT

          ACTTGGTAGTTACAACCTTAACATAGCCTTTGAGTAGCAGATCCCCCATCCGCATAAGCA
          CCTTCGCAGATACAACCCTAACATAGCCTTTGAGTGGCAGATCCCTCATCCGCATAAGCG
          ACTCAATGAATTTAGCTGCTTTTCTATTCTCAACTGTCAGGGTACTTGTGCGTGCGAACG
          TCTCAATGATCTTAGCTGCTTCTCTATTCACAACTGTCAGGGTACTTGTGGGCGCGAACC
          TATTCCCTATATTACCCACGATACAGATCATGAACGTCAAACCGTTTTGGTATACTAACG
          CTACTCCAGTGGCAGCCAACCGAGTGTGGGCCCACGTCGAAATAGTATAGTGTGTGCAAG
          TTTTCGCAGTGCTAGCTTTCACGAGACCTGTCAACAACGAGTCGCTAAACCTCGTGAATG
          TTTCTGTAGTATTAATTTTCACGAAACCTGTGGACAACGAGCCGTTAAACCCTGGGAATG

          GTTATATATCGCGTGGCTTTTTCTTAGGGTTTCGAGGGACTCTACACCTCCCCTACACCC
          GCTATATATCGCGTGGCTTATTCATAGCGTTTCGGAGGACTCTACACTTCTCCTACACCC
          GAAATAGTTTTCTACATCATGTCTCTATCCTGCAACATATGCAATGTCTAGCCCTAGGCC
          GAGATAGATTTTTACACCATGTCTCTATCCTACGACATATTCAATACCCAGCCTTAGGCC
          GTAAGGGAACTGGGCACTAAGTTGGGTTGGTGGGATCCGATGCTTATCAACCACCCAATC
          TTCAAAGACTTGGAAAATGCACCGGAACAGTCTGACGTGCCACTGGAAACTCGCTTATTT
          ACCATAGCCACACGTAATCCGACCAAACGGCGATTCCAGCTTAGCGACACCAGCTGCTGC
          ATCATAGCTATCCGTATCCCGACGAGACGACGATTTCAGTTGTGCGACACCCGCCGCTCC

          AATTTCAGAACTATAGATAGGGACTCATGGTCGAGGTCAATTTGGCGTCACTCTAGAGGT
          AATTCCAGCCCTATAGATAGGGACTCATGGTCGAGGTCAATTTGACGTCACTCTAGGGGA
          CCGAGTAATCACACAGCTATAGAGTCAGTCCGGCGAGAGAAACAGTCCTACGTCGAGCAA
          CTAAGTAGTCACATAGATATTGAGTCAGTCCGGCAGGAGAAACAGTCCTATGTTGAGCAA
          TCTGAACGTCCTTCTGGGGATAGTTTTGCCTACATGTCTTTACGGGGTTACCATCGTCTG
          TCAGCTGATCCGGCTCTATGGGGGCTAGCCAGCCTGTCCGTACGGTGCTATTTGTGCACG
          CTTCCTACACCTAAAGAGAAAGGGGGAACTAGAGAGTCAACCACCAGTTTATTGTGACTG
          CCTCCTCCAGCCATAGAGGAGGGGGGAGCCAGAGAGTCCGCCACGAGTTTACTATGGTTG

          GGTCGGTGCGATCCTGAGATCTTCTACTGGAGTTGTCAGTCAATCCGGGTACTTTGCCCT
          GATCGGTGCGATCCTTAGATCTTCTACTGGAGTAGTTAGTCAATCAGGGTACTTTGTGCT
          TAGTGGTATTCCACCGGAAGTCCAGATTATACTATCGAGTCCGTGTATATCCCTCGGTAC
          TAATGGTATCCCACCGGGAGTCCAGACTATAGTTTCGGGTCGCTGTACATCCCTCGGTAC
          GCCCGCTCGAAGTGAAACCATCTTCTCTCAGATGCTCGCACAATTTTGATACGACTACTT
          ATGGGAGCGGTATAAAGGAGTTACCTTTCCTGTGTCCGGTCAATCTCAGTCCTTGTACCT
          GGCGGACGATCGTGGCACGGCCCTGAGGCTAGTATTCAGCTGATGCTGATACATCTATAC
          GTCGGTCGATGGTGGCAAGGCGCTCACGTTTGTACCTAGCTGATTCTGATACATCTGAAT

          CTTGTGCCTCGCTCTGTATCACAAGACGCTCTCGGGCCTCTCAGCTGATGTGCCCTTTAG
          CTTGTGCCACAGTCTGTATCACAAGACGCTCTCGGCCCTGACAGCTGATGTGCCCTTTAG
          ATAGTGCTAAAAAAGGGTCTTCTACATCCAAGTTCGCTCATCGGCTAATGCGCCTGGCTC
          AAAGCGCCAAAAAGGGGTCTTCAGCATTCAAGTAAGACCACCGGCTAATGAGCCTGGGTC
          TCGGCCCTGAGAAAGCGGTTACGAGCTCTCACCTAATCTCTAAAGTTATGGAGCTCTTAT
          CGCACTTTCTAATATAGGCCTCACGTCCACTCACGGTTCCATGGAACACAGTGTTGGGGT
          TCTGTGTTTGCCCAGATGATAAACGCCATCACAGGGCCTTTGAGGGAATGGGCGAAGCGT
          TCTGCGCCTACGTAGATGACATACGCCTTTACAGGGCCTCCGAGGAGACGGGCGAAGTGT

          ACAGGCACTTTCTCACCTAGATAAGGATTGAAGCACACATAATGTTAGAAACTGTAAACT
          ACAGGCACTTTCTCACCTAGATAAGGATTGAAGCACACATAATGTTAGAAACCGTTAACT
          GTGCAAGCCCCTGATCCCGGCCCGGATGCACGTTAGAGTCTGTTCCTAATAGCACCTATT
          GTGGAAGCCCCTAAACCCGGTCCGGATGCGCGTTTGTGTTTGTTCCTAGTATTACCTACT
          GCGAGTGCCCGCACCAACAGGAAGGTGCCTTCGGGAGGCTCACTCCAGACTCTGTCTACT
          TCACGTAAACGTCTCGACGTTAGGGATACCTCAGACGGTCCGCAGTCCGTGCTGCTGTCC
          GCATCTTCATGTACAATTGGCGAATAGATTCAGGTAGGCTAGCCCCCGGTAAGCGAATCC
          GCATTTGCACGTACAATCGGCAAAGAGACTTAGGTGGGCCTGCCCCCGGTGAGCAAATCT

          GTAGAGAGGGGCTGAGCGGGAGCCTCTGCCCAAATACTAAACAAATAGCAATCAATTTCT
          GTAGAGAGAGGCTGAGCAGGAGTCTCTGCCCAAATACTAAACAAATAGCAATCGGTTTCC
          GTAGGAGGCAATCCGTTAGGTTGAATCGTTGAAGCCTGGTTTGCAGGGCGATCGTCTATC
          GTAGGAGGCAATCCGTTGGGATGATTTGTTGAAGCCTGGTTTGAGGGGCGATTACCTATC
          ATTTATACACACCAGTCCGTGGAAGCAGAGTTAAAATAGAGTAAGTGGTGAGCCGTTTCC
          ACTTACAAATACTAAGCCAGGTAAACAACGCCAACCTCGGATAAGCTATGATCCGTTCCC
          ATTTCGTACCGTTTAGTAGCTTAACTAGCGGCGTAGATGAACTAGAGCTGACTAGCCTCA
          ATTTGAGACCGTCAAGTAGCTTAACCAGCGGAGTAGATGAACTAGAGCTCATTAGCCTCA

          CTGCCTAATAAGTATGCAGCCCCACCATAACTTAGAAGTCCATTAATGTAGAGAGCGGTC
          CTGCCAAATAAGTATGCAACTCCACCACAATTCAGAGGTCCATTAATGCAGAGAGCGGTC
          CCAAGGACAAGTTACCCAAAATGCCAACTCTCTGCGTCTCAGGTCGTGTTTTCTGTAGAT
          TTACGGACAGGTTGCCTAACTTGACAACTCGCTGTGTCTTAGGCCATGTTTCCTGTAGAT
          TTTAAACGCGATGAGGCTTGTGATGCGCACATTATGATGCGGCTGGTCTATAGATGGACC
          CTTAGATGTGATGACGGATGAGCGCGGTTCATTACGGGCCGTCTTGTATACAGACGGGTT
          GTCAGGGGATCGGGAGCATTTTTCTTGGTTATCGTGCCACAGCACTGCATTGAAAGAATG
          ATCAGGGGATTAGGGGCCTTTCTGCAGGCCGCCGTGTCAAAGTTCTGCATTAGAAGAGTC

          CCCTTGCGCGCTTCGCAACATCCACCTGAAAGGCTTGAAAGAAGCATAGGAGGAACCTAC
          TCCTTGCGCGCATAGCTTCTTTCATCTGTAAGGCTTGAAAAAAGCATAGGAGGAACCTCC
          CGGACAGCTGCGTTGCAGTATTTGATTGCCAGTTGTGAAGGAAACAAACGGCCGACACTC
          CGGACAGTTGCGTTGAAGTATTGGATTATCAGATGTGAACGAAACGAACCGCCGACACTC
          TGTATAGCAAAGCGGGAGTCATAGAATGCCTGGTGCTACAGGTACACTCAGCAACCACTT
          CAATCAGTCGGGCCAAAGGTCGTGTGAATCCTTCCCAGGCGGCGCATTCAGCGAAGAGTA
          CGCGGAGCAGGTTGCGGATATTCAAGAACTCGATACGCCTTATGAGTACGAACATCAGTG
          CGCGGAGCAGGTTGCGGATGCTCGAGACCTCGACTCGCCTTATGTGTACGAACACCAGTA

          CGCAACTAGCCCGACTGGTGCCGTGCCCTTGAAACCTCAGTATGGGTATGCTCGGAACTG
          CGTAACTAGCCCGACTGGTGCCGTGCACTTGAAACCTCAGTATGGGTATGCTCGGAACTG
          TGCTACTGCGCCAGTTCGTTTCCCACAGTTAGGCGCACAGGGCCGCGCAGTTAAAAAGCA
          TGCTCCTGCGCCATTTCGTGGCCGAGAGTTAGGAGCACAGGGCCGCAAAGTCAGAAAGCG
          CACAAATTGTTTCGCTTCTATGTCCCGCAAGCGGTCGTGAACCTAGTTATCATGATCCCG
          AGCTTAGTGTCATATTCCCGCCTCGTACTTCTCCTCTCGGGTCCGATATGACTGCCGTCG
          CATACGCGGTCACGTCCTTGTCCCATGTTCGTACTTACGTGTAGGATAAGTCTCCATCTG
          CACACGCCGTAGCGTTTTTCTCCGATGTACGTACTTCCGCGTACGGTAAGTCCCCAATCG

          CAGAACGCACATGCTTTCGTCCCCGCAGTCCTAGTCCGGTGGCAAGAAGGACGCGCCACT
          CAGAACACACATGCTTTTGCTCCTGCAGTCTTAGTCCGGTGGCTAGAAGGACGCGCCACT
          TAGTGGGGGATGGCGTGCGACCCGGTACCTCCACCGTGGTGGTCAGCGACTCGGTACCAC
          TAGTGGGGGATGGTCTGCGGCCCGGTACCTCCATCGTGATGGTCCGCGAATCGGAACCTC
          TAGAGCTACCAAGTCCATCTCTCCGCACTGTTGACTCGGGTGCCGTTGCGCCCGCCCTAA
          TGAAACTGACGGAACAACTTCTTAGTGTTGTTAAGGCTGTGGACATTGTGCTAGTACGCG
          GAAAATAGGCACCTAACCACCTGTGGCGGTCTGGCTGCGCCGCCGAGTGACTGGAACGTA
          AAGAATAGATACCCAACTACCCGTGGCGATCTGGCTCCGTGGTCGATGGGCTAGGACGTA

          TCCGTGTCACTGCCCGCTAGGCGCCGCACTTCACCGGCCG
          CTCGTGTCACTGCCCGCTAGGCGCCGCATTTCACCGGCCG
          GGAGTATGTTTGAACTGTCAGTAGCATGTTCCACCGGTAG
          GGTTTACGTTTGAACTGTCAGTAGCGTGTTCGACCGGCAG
          AGCGTTCGCTACCCTACAAGCTTATGCGACGTGCAGGTAT
          CGTGCACGTTACTCCACGGGGCTTTGCGACGCATAGACAA
          GGTACACGCAACCACGCACGGCTATGCGATGCACTAGAAG
          AGTATATGCCACCTTGCTCGACTATGCGACGTACAAGAAG

