 8 1000
t1        ACCCAGTAGTTACTCATTGCGGTAGGAGCTATCGCTCGCCTGACAGGCCCATTAGGTGAC
t2        TTTCTGTAGTTACTTATCGCAGTGGGGGCTATCGCCCGCGGTATACGTTGTTTAAGCCAT
t3        CCTTCGCAGTCACTCACAGCAATCGGAACCATCACCCATGGTGAACGCTCACAAGGTTAT
t4        GCTGCCCAAGCTCCCATTCCAATCGGAGTTATAGACGGCGGCGTTTGACCATAGGGTAAT
t5        CTAAACCAGACTCCTCTTACGATCAGCGGTAACAGCTGTCGAGAACACACTTAAGGCCAT
t6        TTCTCCCCGACACCAATCATTATGGGAGCCGAGTATCGCTGGGACTACCGTCAAGTCCAT
t7        CTTCTCGTGGTCATCGGCACGCGACAGAACGCTCCACGCTGCGGCTTCTTATACGGCTCT
t8        CGACCTCCGAGCAAAAGTCCAGTGAGATCCCCCACTCATCACATCTGCTTACATTCTCCC

          ACGCCGGTGTCAACTAGTGTCCGAGTAGCACGTAGCGCCGAGCGAAAATCGCCCGCGGCG
          ACACGGGTGTCACCTAACGCAAACATAGGGCACGACGATCATCGAAAATAGTTTGCGATA
          ATGGCGGTGTTACCAATCCTCAATGCAGGCCGTACCGACGCAAGAGAATCGGTCAGTGCC
          GCACTGGCGCCGTCCTCTACTCGCCTACAACGAGAGTCAAAGGGGGTCCCGGTCGTAGGT
          ATGCTGAGCTTATACTCCATTCCCATGATATAGAGCATAGGACAAATAATTTATGGTGTA
          TCTACTGTGTCTCCTAGACCTTCTGCAGTACCCGCCACTGAGGACGGATCCCTTCTTTAA
          GCAGTAGTGTCTTATGCCCGGGGGCTGATATAAAACAATGCACAGAACTCCCCCGGTAGC
          ATAAAAGTGTCCGTCACGATTCTCTGTATGCGCGGAGGTTCTCGAAGAGCTTTTAACATA

          CCACGATGTGGCACTAGGTCACAAACGCTCATCATATCTGCCCCGGCCGTGGCCTAATGG
          TAGCGCTGTGGCACGCACTTACAACCGCCGGCAACATTTGTCGAGGTTACGGCCAAATAG
          CATACGAGTGTTCCTAGGATGCAGTGGTCCTTAACGTCCGCCCTAGTCATAGAGAATTAG
          GCATCGTGATGCGTTCGATTGGACCGACATATCAGGATCCTCGCAGCTATGCTAAATTAG
          GCATCAAGCAATGGTCGCTGGAAGGGGCCAACAGTGATCGCTATGCCTCAGGAGAAATTT
          CCGTCAAGTTGCCGTTGATTGGAGATGCATTCATCGTCTGCCATGGTAAAGGCGTGACGT
          TTAGCGGGCTGCGTGCGGTCAGATGTCCTGTTAACGGACATCACAAAAAGAGAGAAGTAT
          CCCTTATACTGACAACCACGGGACCCATTGGCAATGGGCAATGCTGTACGGACCGCAACC

          CGCTGAGATCAACGTTAGATAATTCAGTAATATCCGCGTGAGAAGTGTCGTGACCCATCT
          CGCCCAGCTCGGTGCTGGATAATATAGGACTATCGTCGCGAGAAGTGTCGTGGCTTACCT
          CGCTAAGATCCGTGGTCAATAACATCGTTTCATAATCACGAGCAGTGTCGTAGCTAACGA
          AATTCAGTTCGGTGTAGCGTACTAACGGACTCCGATTACGCGTCATTCTGAGGCGGACAC
          CTTTTAGATAGGTAATAGGTATTACAGACCAATCTCTATACCCTATATGGTAGCCTGATC
          CCTTCTGCACAACGATAGGTCCTACAGTGTTCTCCATACGCGTAAAATAGTGATACCCTT
          TTCCTTTATGGACACAAGGAAGGTCAGTTTTTACATTAGGTGAATCGTCCTGTACCGTCT
          CGGTCCAATTATCGGTTGCACGTCTTATACGACCCCAAGAATTGGAGTCAGCGAGCGCGC

          GTTCCTCATATCTTGTACAACAAAGAGCGACCCCGGGGGGAGTCTCGCCGGCCTGCCTGT
          CTTCCTAACATCTCGTGTTGCAAGGCGCGACCGCAGGAGCACCCGCGACGTCTTGCTCGC
          GTCCCTAGGGTCTGCTACTGCGTACAGTAACCAAGGGGGGTGTCTCGGAAACACGTTTGT
          TATTCCATCGTCTTAGTTTGCGAAAACCTCGGAGGGGGGGAGCCCAACTGGAATGGACCC
          GCATCTTTAACTTCGGACTAGAAAAAAGTACGGGTAGGCGAGGATCAGTATTCACTTTGC
          CCCATCATGATATTCGACTACTAAAGCTGCCATTACAGGCTACATTGGTGGTGCCTATGC
          TTCAACAATCCGTCCGGCCGACACAAGTCCTGACGGGGGGTGCATCAACAGAGCGCCCAT
          CTACCTATTTAGTCAGTTTCAAGTCACCGACATCAAGGGTAGCTACATTGATGAAACGGC

          GCTCGCGTGTACTTCCCGCAAATGTTAAGCCACGGCGTAGTATTAAGGTGTGATCGACAG
          GGACGAGAGTTCCTCCGGCCAGCGTTGAGTCACGGCGTGGTATTAAAGTGTGGTCGCCAC
          GAAACAGAAAGTTTACAGCCAGCATAGATTAATGGTGAGGTACTAAGGTGAGGACGTCGC
          AATCTTGAGCACCTGCGGCAAGCGTTACGGAAGGGGTTAGCTCTCATGTGGGGCGATTGT
          AGTCCTAGCTGTTTTCGGTGTGCGGTGCAGTACGAGTCTGTCCTAATACACGGAGGCTCT
          GAATCAAAGCGGCTATGATGAGCGATACAGTGCGCTTTAGTTTCGTAATTCGGCGGAACC
          AGACCCGTGTAACCGCCGTCTGGCTTTTAGTTTAGGCCAGCCCCTTAACCGGGATGCAAT
          GTTTACTTTCTGTTCTTTCTATCGCTGTTATCTGACAAAGGTAGAACTCACAGCGGACCA

          CGTTGCCCTGTCTCATATTTAGAGCAGGTTGCGCGGGTGAGGCACTTGTTTAATTTAATG
          AAATGACTAGTCTTGTACTTAGAGCACGCTACGGGGGTAAGGTCCTTGATCGCCTTAATG
          CGCTGACCAGCATCGCACTCAGAGCTTGTCCCGGGGACAGGGCTCTTGCACGAGCTAGTG
          GGGCCATCAAGCTCGAGCTCAAAACTCAAAAATGGGGTATGACACGTGCACGATATATCA
          CGCTATTCTAACCTCTTCCTACTGACTACCTGTGGGATATAGCGCATGCTAGTTTCATTA
          AGCTTGTTAAATTAGGAGTTGGCGCCTGGTGACGGGCTAAGGTGTATGCTTGCTCTCTCT
          GCTATGTCAAAACATAACTAAAAGTCAGTTTTAGAAATGAAATATGCGCCTAGCTCTGGA
          CTAATACGACTATGGCCGCGACCATTCGCGAGCCGAGTGTGATAGGGATCGGATTTGCCG

          CTCTCCGAGCGATCGGCCGGAGGGTGAAATCATCGGCTGCCCAACATTACATGCAAATGT
          TTCGCTGAGAGGTGGGCCGGGGATAGACATATTTGGTGGCTTAACATTACATGCGGACGT
          CTATTCGAGAGGTGAGTGTGCCAATGGCAGATCGGACTGTTCAAAGCCACTTGCGTTCGC
          CCACTTGAAAGGTGGTCAGATGGTCGTTAGCATGGGATGCTCAGATTCACCAGAAAATGC
          CCCCTGGAGTGGTGGACGGTGAAACGCTACGAAGGTAAGCCTAGGTGCATGCGCGAACGT
          AGGTCTAGAAAGTAGGCAACCAAGACCTTGCACACCCGACGCAGGCTTTCGGGCGGACGC
          ACATCCATGGACGGGGTGAAAATCTGTGAGATCGGGAAGTGGCGACACACGCCTGGACAG
          ATATGCGCGAGGTGTCCCTGTAACAACAGGGGAAGGGGGCGCAAAGACTCCACCGATCAC

          GACATAATGAACGTCGGAAGCAAATAGCTAACCATTCATGTCACCAACGTTTGTACGGAT
          CTCCACACATGCATCGGATATCTTCGGCTAGGCGTGCATATCAACAGCGTCTTTGCGGAT
          GCAATTGCATGTATTGGCGACGTTCGGCCAGCGGTGCGTAACAGTAACATTTCCACGTAT
          TTTATGGCACTCATCGAGCTTGATCGTTCAGATGTCTATGGCAGCAGTACCTTCATGAGT
          GCTCCTGCACCCGGTGGAGAAGGCAGGTCAGCGGTGTATAGTGTCGTCACAAGTACAAAT
          ATTATTGTACGCGTTAAACATGATTGATTGGCTATCCCTGAAAACTACCCTAGAGTGAGT
          TTAGAGGTTAGTTTGAACTACACCTACTTTGTCGTTCAAAATACGTTAACCGTTAGTAGT
          CCTGCGAATCGCTCGTGACCTAATTGCATTGACGTACTGAGGCTTCTGAGCCCTAGAAGA

          ATATTTGGAGCTAAAGCCAGGAGGCTTCTGTGGTCTAGGGATCCATACAAATAGGTATTA
          ATGCTTGGAGGTATAGTGCGGGGGCATTTGTGGCGTTGGGACTCTTACGAGTACGCATTA
          ATGACTGGAGGGAAAATTAGGTGGGCCCAGCGGTTTTGGAGTCCTCATCAATAGCCGTTA
          TTGTATACAGACACCACCAGACGGCCCCCATGGTCCCCGGGTACCAGTTAGCAAGCGTAG
          CTGGTCATGGAGAACGCCAAACAACCTCAGCGGTACTCGGGTCATCGTAGGACGATGGGC
          ATGTTTAGCGGTAGTGATGACAGTTTGCCGGCACCGCTGTAAGTTTGCTTAAAGCCGCTA
          ATGACTATGGACCAAGATTGGGGACCTTTGAGTACATCGTCTACTTCCGAGTAAACGCTG
          AAGACCTTGTATGCTCTTCGGGGTTCTCCCAACTCTACCAGCTCGCACGCGTGCTCGATC

          CCTTAATAGACTGCCGTTAGAATTGCGCCCGCTTACGGGAGTGAAGTTGTGGATATCCCG
          CCCTACTAGGCCGCTGCCAGGACTGCTTTAGCCAGTGGGAGTGCGGTTGCGGATTTTCCG
          CCTTACAAGGGCGCTACGAGAATTGCGTTTGCCTGAGGAGACGAGGTCACGGATAGCACG
          TCCAACACTACTGCTGCTAAGACCGCGTTGGTTTACGAAACAATGATTGTAGGGACTTGT
          TGCATACAGGCCGTTACTAGAATCATGACGGATAGCGTAAATACGCTTGTGATTATTCAG
          TGCAGTCCAGTCGATATCCAGCCTACACAACGCTAAGACACTATGGACACGGACAACAAG
          GCTTGCCAGGATGTAACCTAAGCTGAGCAAGGTTTTGAACTTGTCGTCACCAATATGATG
          ATAAACCAGTCCTTCATATTGTCTATGTCGAACTAAGGCCCGGTCGTCCGTGTGATGTTG

          GACCATTGATTAGTTTCCTTTAGTCGGATAAACCCCCTTGGTTCGTACCGTGAGAAGTGC
          AATTATTCATTAATTTGCTTCACTCAGTAAGGCGCCCTTGATTGGTAGGAAGGTTAGTTG
          GACGTATGATTAGTTTGCTTTAATCGTAAAAATGCCCCTGGTTGTCATCATCGGAGATAC
          GAGCGTTGCTAGCTCCGCTCCATCCGGTAGTTCCGTCCCGATCTACGTTCGGTGACACTC
          GACTTTCGTCAAATCTGGTGTATTTAGTGATCTACTCTCGGGTCCTGCTCTGTGATATTC
          GAAGATACATAAGTCTAATCCCCCCTGTTCTTTTTAACCGGTTCGAGCCCGAGTTCATCA
          ATCAACCGAACTGTTTTCAACACACGGGGACTCATAGGCCGTGTAGATCCGCCAGCCTCA
          AGTCCCAATCCAGTCGGGTCAATTTAGCGCCCCCCCCGCCAGCTCTTTTCGTTGGGTGAC

          TGGTTATTAAGTCGACGAGTCAAAGGCAGCATCAAATCAGCTGCCACATAAGCTTTATAG
          AGGCAACCGAGCCGGCCAATCAAATGCTGCATTAGACGAGATACCACATGTACTTTCTAA
          GAAACATTGAGTCGGACTACCACGAGTTACAGCGAATGAAAGGCTATCGGTACTTTCTAA
          AGACAATTGGCTCAAGCTGCAGAACGGCAATCTAAACGATGTTTGTCTTGTAGTACCTGA
          ACATAGTCGAATCGTTTAGACTAGCGCATTGTTGAGGAAGTTTCATTCGCTCATGCCTTG
          AGCCAGTTGGATTAAATGACCAAATGTTACCCTAAATGCACTATAATACGGAACTTCCCA
          CGTTCGTCGGGGAGTATGACAAGTGGCGGACGTATATGAACGCTAGCATCCATCTCCCCA
          CGACGATTAATTAAACCGATGACCAGCCGCCATAAGGGGTTGTTGGTGTGCAATTCGCTG

          GAACGCACAGCCGCGAACGCAGTTATTGTGATTGTACGCAATGTTGTCTTATCCCGAGCT
          GGGCACGCAGTCGCGAACGCAGGCATTATGCCTGTATGAAACGAATGCCCACCCCGGGTT
          GGGCGTACACTCGTGGACGTAGGCTCAATGCTTGTGAATGATGCATATTGATCCTGGGTC
          GGCTCGGCAGTTGCGTACCTACCAGCCAGAGCCCTGAGTGTCACAGCTCTAACTAGGCAC
          TGTAAGGTCGATTTAGATGAAATCCTTACGACTGCAAGAGGGCTAGCCTTAGCCTCGGAC
          GGGTGGGTTCTCCAGAATAGGTTTCTCTAACATTTGAGGGGACGCACCTTAACCCTAGTG
          CGTAGGAGTATATGATAGGAAGTTCCCTGGGATTTGGAGATCACAGATTTGGTTTGGGCT
          GTCAGACAGAAAATGATGGCGGCCTCTTGGACTGTATAAGCTACACGAACAGTGTAGGCT

          GGTGGACATTGTATATTAGAGCCGTTTCTCCCATACTTGCTAAGCAATCAGGTTCGGTGT
          GGTGTACGCAGTACGTTTAGACTATTACCCCCATATTTGCTAGCTGGTTAAGTTCGATGT
          AGTTATCACGGCATCTGAGTACTGGTGGGGTCATATTCCTGGGTTGGTCCCGTACGACGT
          GCTCTGCCTTACACTTAAGATCATGCATTTCGACACGTGCAAGTTGGCCGAGACCGTCGT
          TGTGGTCTTCATATATGGGATATGGTGCATCGTGACTGTTAGGTTGCCCAAGGTCAATGA
          ACCATGCCCTGTGTATCAGAACTTGTGCCACGTTGCGTAAAAATCGATCACAATCTACAC
          GAGAATTATCAATAACGCAGATTGCATCCCCCACAAAACGGCGCTGGTTAAAACCAAAGT
          GCCGTGCATTGCGCTAGTTACCCGCTACCGCGGCGTTAGTTCAAGATGACGGTACAGGGC

          GCCCCAGGATTGCTTTTCGAAATTTCGTGTGCATCGATGAATTATGTCTATACGAATATC
          TGCCCGGGACTGATTTTTGAGATCTCATGCCAGTTTATGACTTACGCCTATATCATAACT
          CGCCCAGAATTGACCAGTGGTATCTCATCCATACCTATGATCTACGCATATATGCTAAAC
          CGCCAACATTTAATCTTTAAAAAGCGATTGTCATTTATGTTCTAATGTCAGTTATGAGGC
          TTCCGAAGACTGGTATCTTACCAGTCGACTTTACCCATGACAAAAATAAATCTGAGAACC
          TGCCACAGATTGATTTTTGCTGGCTGTCCGCCGCTTATGTTCCAGAGCCAAACCTGAGGT
          TACCAGAGGACAACTCTTGACCATTGATCCCCAACCCAGTCCTTAAATTATAAAGGGCGA
          TGCTTGGGGTTAACTAATCGAGGCTAACCATGAAAGAGGCTCATCTTTCATATTGTACGC

          ACCAGTGGGGTCCATATGGGCAGAAATGAGAGCTGGCCTT
          ATACGTGGGGTCTGTATGGACTAATCAGCTAGATAGTTCT
          GCAGGTGGGGTCTATAGGAACGAGTCTGATAGTTGGATTT
          AACAATGTCGCCAATTTACGTCTACCTACTCATCGGGCTC
          ACTGAAGCCCACTGTGTAGGTACATCTACCAATTAAATTT
          GCAAATGCGATCCCGTTAGACCTCTTGAGTTATCGGGCCT
          CGTGCTGCGGCCTAATTTGATCCTACTCGCGTATGGTCAC
          CCCCACGAAGTTCAAGGGTCCCGCCCTAACCCCGTTGTGA

