 8 1000
t1        GTGAGCAGTCTCTGACTTAGCTGAACGCCATCATATGGTACCGGAGGAGTAACGGTCCCA
t2        GTGAGGAGTATCCGCCTGACCTGAATGCGACCATTTGATGCCGGGGAATGACCGGACTCA
t3        GAGAGCAGTCCTCCCTCTACCTGAGTGCTACCATATGATACCAGAGTTGGAACGGATCCG
t4        GCAGGTAGGTCGCGTCCCTCCTAAATGCTAGTGTATCTTATCATATGTCGGAGGGGCGTA
t5        GTGAGGGGTCCGAGAAACGGCCGACTGTTATTATGATCTGTAGGGAGCGCAAAGTGTTTA
t6        ATAGGTGAACCGCACACCTGTCTGGCGACGAAACAATATGCCAAAAAATGAAAAAAATAC
t7        GTGCACGGGGCATGTATCGTCGAATCACTACAGTGTGTTCCCAATGGGGATGGACTCCCT
t8        GTTGTACGGTTGTGCTTCCTCTCAACGTCTAAGCGCTTTGTTAGAATAGACGTGACCATG

          GTTCATTACAGGCTAAGCTGCTGTTTAAATGGCTATATCACTAAGGGCCATACCTCTAGT
          GGGCATTGCAGTCCAAGATGTTGCTCAAATGCCTGCTCTACTACGGTCCTTACAGTTAAC
          GGCAATTACAGGCCCAGATGCGGTTCAGATAGTTGTTCTATTACGATCCTCACAGCTCAC
          GGGCACCGCAGGCTTAGAGTGACTAGACTCCAGCTGTAGGTTCAGGTACCATCCTCTTCC
          AGTTCCCGCTAATCTGGGCGCGATGCTACACGGACATCATAAAAACTCCGCACGAAGCCG
          GGCCACGGTAGGCCCGCATACGTTAGAAGAAGGTCGCCAGTTAGGTTTAATCCTACCAGG
          GGTTTGTATATGACTACACGTGAAGGGGTTTAAATGTCGGATGGAGCCCACTTTATCCCC
          GGTATCAACTGATCTGTCCGTGTTGAGACTCGTTCGTCGGCCAGGGACCACCCAGAGTTC

          CCTCCAGCTTAGTCGTCTTCTCCCTAGCGGGCACTAGAAGCATTTACTCCGTAGCCGAGC
          GTTTCAGCTTAGTCATCTTTTCCCGAGTGGGTACCAGCAGCATTCACTCTGCAGTGGAAC
          GTTTCCGCCCACTTGTCCTTTTCCTAGTGCGCACTAGCAGCGTTCATCTCGCAGTGGAAC
          TTATCGTTTCGAAAGTGCTCACGTCATTACTACTACGGGCAAGTAGTTCCGGGGTTCAGA
          GCGTAGGTACAAAAAAGCTTGTATGAGTACCCCCGAGCGGAATTTTGCGCGCTAACCAGT
          GCAAAGGAATTGTAGTAGGCCTGCCACGTCCTTTTTGAAAGAATAATACTGCGGATCCCA
          TTATGAATATATATGGATTTACGCTAATACTCCTTAGTACACTCGACTGCGGAGCCCGCC
          AGCGCAGTCCCAGGGTGACTATACACCCAGGACTACGGGACATCGTGCCAGCTGCCGGCT

          AGGTACTACGTAACGATCCACAAAATGCCGAAAGAGGCAACGAATATCAGACCAAGTTCA
          AGGTACTACGCAACGGTCCATGAATTGCCGGAAGAGGCAACGATTATGAGGACTACTCCA
          GGACACCGCGAAACGGTCCACGAATTGTTAAAAGACGCAAAGAATATGAGGCCTAGATCA
          GGGCACGTCAGGTTGGTCTGCGACCAACTTAAATTGGGAGCTATGCAGAATCCCCTACGG
          AGGTATGCCAGAAACGGCTGCTTGTCGTAAGAATGTAAAACAGCGGAAAATTTAACATCA
          AGGTTCAGCAGACCTACCCCCGGAGGACACAAATAGTGGGTTATGTACAGGCCTCATTTG
          TTGTATGCTGAATTGATTCACGACTCCAACATGTAAAGAAATCCATAATGTTTACCACCA
          GGATATACCCATTTTCCCTTCGAAATAAGAAGACAGGGGGTTCAGTCGACGGTCCCTCTC

          CCGGACACTTATAGTCCCGTACGTCTAGGCGAATATCATACTTTCGATCTCGGAACCCCG
          TCGGACACCAATAACACCGTACATCTAGGGTAACGTCAGTCCCTCGACCTTGGTGATCCA
          CCGGACATTAGTAACTTGGTGCGCCACGGCTAACTTCATGCTTCCAGTCCTGGAGCTCCG
          CCGGGCACTTATAGTTCCATACACATAATTACTTACGACGTGATTGGACCAAAAACACAG
          GTGGCACATCGACATCAAACATGCACCAACCGATACTCCCATATTTATCCGGCAGTGTTG
          CCACATCTTCGGTGACGTGAAAGTCCGGGTGGTACTCTTTCCAGCCATTACGGTATGCGG
          CTGGGATGTTGTCATGGTATACATATAGGCGATTCCTACTTGATTCTTCCCGGAGCACTG
          ACGGACTTGCTGTCTAATACTTTCACAGCCACTACCCGTGCTCGATATCATCATATATCG

          CCAACAATGCAGTGGTCCGGAAGTTTGGACTTTCCGGGGGTCACCCCACGCAGGGCGCAT
          CCAATAACGAGGTAGTCAGGAAATTTAGGCTCTTCGGGGGTTACCCCCTCAGGAGCGCAC
          CAAACAACGAAGTGACCCGGAGGCAAAGACCTTTCAGGGAACGCACCCCCGGGGGAGCGT
          CTTGTCATGAGACGTTCGAGGTTTTGGGGCCAGCGGGGCTTTATATCTGTGGAGTCGTGA
          CCGACTACGTGAGCGCCGATATGTGTAGGGCGTTGAAACATCACCTTTTTGAGGGTAACT
          ACCAAAGTGGATCTGCAAGTGTACACACGGCATAGGAGTATAGCCATAGTAGGGACACAC
          CGTATAACGTGCCGGTCGGTGCGAGCGAATTATCGGGGTCTAGTTTGCATGGGGCTACAT
          TTCTTATGCAAATGAATGGCGAGCCTGGCGTACTCACGTTAAGCACCCATATGAGTACTC

          GTAGTGCCCCGTGATATCTACATTTGATATGACGAAGACGCAGGCCGAGACTTCCGTCAC
          TCAGTGCCTTATGATATTTACATTTCAAATTACATAGACGTTGGAAGAGATTCCCGTCAC
          ATAGCATCTTGTGATGCCTACATTCCAAACGACACAGGCGTCGGTTGAAACTCAGGCCAC
          GCAACGCTAAGCGACATCAGAACAGCAGGGAGTAGGGGTACCGATGACAATTCAAACTTG
          AGATTACTCATTGCATTTTCCATTTTACGGGGTAAGGACGTAAGAACTGACTCCGACAGC
          ACTGAAGTGACTGTTGCCAGGGCCCACTGGGGCGCGGGTGTTAGCGGCGACTCTGATGGC
          GTAGTCCGGCACGGAGCTTACGCTCAGGAGGATGGCGACATCTGTGAAGAATCAAGCCCT
          GTAATGTCTCTGGTGACGTAGGTCCCTAGTGGCGCGTCAGCCGTTTCCTAGGCCAGTTCC

          CACGTTGTTTAATCCAATAGGATGGACGTCAGCGTTGAGGAAATTTTAAGCCGATCCGCA
          CATGCTATCCATCCCTATATGACGGTTGATAGCGTCCAGGAAATATTGAGACGATACGCA
          CACGTTTTTCACCTCAATAGAACGGATCTTAACGTCTAGGAAGTATAGAATCGATACGTA
          ATAGTTCATCGTGCTGAATAGTGGCACATTTGTGCTAAGTGATACGAGGGCTGACGTACC
          CTTGCTCTGTACGGTGAGGTCTGCAATGGGTACGTATAGCGACTGTAGACCTGGTTAAAA
          CTGGATGTTCACGGCAATGTACGGGTAGATCCCGATCTGAGAAGATAGAGATCATCCACA
          GCACACATTCGTTGCAGTGTGTATGGTATTCTTGCTCAGATAATTTCAAGTTGGTTCCCA
          AGTCCAGGTGAGGATATAGAGTAGGCCGGAGCGGCTGAACGAATATAACGCCGAACCTTA

          CCGCGACAAGGTATTATTCAATACTATGCAGTATTAACTGGTGCCGGACGTCACGCTTCT
          ACGTGACAAGGTATTCCTTAGCGCTATGCAGTATCAACTAGTGCCGGACAATATAGCCTC
          TAGCGGCAAGGCATTCTTTAACATTATGCAGAACTGATTGGGTACGGACATCGCGGCCTC
          CTGCTGTAAGTCATAAGACAGTCTCCCATGGTCCTAGTGTAATACCGACGTATCAGCCAA
          CCGCCATGGCGCATACAGCACTTCTAAGCAATCGCAGTGGAGCATCGAAATCGCATCCTT
          CCACCGTAACGTGAGTTGCATCAATCGTGAACGTTCGTATGGGCCCGACATCAGGCAGCA
          GCACTGCAACGCTTGACACAATTCTCGGGAACCCAGGAGCAGGATTGCTATTTCCGTCGA
          TGCTTGCACTAATTCACACAGAGTGCCACAACCCTAACCAGGAATACAGCCTTTACTCTC

          GGAGAAGGTGACCCGTTACTAAAGAAAAAACCATGAGTTCAACTGGAGGTCGCCCGGTAG
          GGAGAAGGTAGCTCGTTACTAAGGGGAAAAGCATGCGCTGGACAGAGGGTCACCCGGTAG
          GGTGAAGGTGGCCTGCTATTAACGCGAATAGTATGAGCTGGATCGGGGTTCACCCGATAG
          GGTGATGATCGCGAGCAAATAAGAAAACCACTGTACGTCCGATGCCGGCTGAAACGGTAA
          CTAGGCACTCCCCAGTACCAGTGAGAACGAATACATTGAACTGGTAGACCGGACTACTCC
          TCAGTTATCCGCTAGCAGCGGGAACGACAAGTATGCATTTCATGAAGGTCTCCGCCGTGA
          TGATAGATTTGTCAGCAAATAAAAAAACTAGCACGAGCTTCACGCGAATTGTCGTAACAA
          CGGAGTGTCCGTCACGACTCTACCGGTTGAGTGTGTGTCCCAAATGTGATAATGTGGTAA

          AGCCGTTCGCTGCTCTAACGAATATGATCAATAGTTTACGTGCTTTTACGTTAGAAAACG
          AGCTGTTCGCCGCCTTAACGAACCAGATTAATAGCTAACGTGCTCTTAGGTTAACAGGCA
          AGCCGTTCGCCGCCTTAGCGTACCAAATTAACAGTTGATGAGATCATAAGTTAGCGACTA
          AGTGATCCGGGCATATAATGACACACGCTAGTGATGGGATTATACTAGTACAAGAAGGAG
          AGCAGATGATATGTATTTTGGGCCAGGTTGTCGCTAAGCCAGCTAGCCGAATATTTGACG
          ACCAGTATGCTCGGGTTGCGGTCCGAACCAGCGAGTGGGTAAATCCTGCACGGGCAGGAA
          GCTATTACAAACGTGTAATGCAACAGGTTAACCGGGACCTTCGTCCAAGGCAGAAAGAAA
          AAAGCCCCAGAGGTGCGCCAAATTGGGCTATTGGCGAGCCGATACTTGACTAGAACAATA

          TGATGTCGATGTGCATTGCGCCCACCGATCGCCGACCCGCGAGTCGCGTCAATGGGGGGC
          TGATGCCGTGGTGCATAGCACCCGTCGTTCGGCAACCATTGAGTCGCGTATACGCGGGGC
          TAGTGTCGTTGGGTATTGGGATTAGCGATCACCAGTCTCTGAGTCGCGTCCAAACGGGGC
          GGCTCTCCTCATGCATGTCGATTTCTCGTGGCCGGAACTTTCGTCATGCCTATTAGGAGC
          GGACGCCGCCATACGTTGTTAGTTCGTAGCACAGGGAATTACGTACTGACCATCTGGGGC
          GGCTGCAGCTGCGCAGCGTAAATTCTAATAATAGAAACTCAGCATTCCGTAGACCCCTGC
          GAATGGCGCAATGAGATGTGATTTCCCAGGGGAAGAGAATATTCTATAAATTGTTACGTT
          TTGACGTAGGGTAAATTTTCTCGTTTTAAAACAACCCTTTGTGCCCTACCAATTTCCGGC

          GGCTAGGGAAAATAATTGTGAGCAGTTGGCTGTGAATAGAGTGGACTCATAGATAGGATA
          GGCTCGGGAAACTCCGCGGGAGTAGTCGGTTGTGAATGGAGCAGGATCATAAATAGAATA
          AGCTCAGGACAGCAATTCTGGATAGTTGGCTGCGAACGGAGTGGTCTCGTTGGTAGAACT
          GACGTGGCCTAGCCATTATGAACCACCGGCCGAATGTGGGGTATGCCCACAGACTGCACA
          ACATCCGAGGGGCAGGGGGCAATTATCGGCTTTACGTTGAGGCACTTCAGCCATCGAGAG
          AGACCGGGCAAGTAGGTCACAGTTGTGACTTGTGCAAGTAGCACCTTGACAAGCTGTATA
          AGAATGGATTTGTGGGCTCGATGTGACCGCAGGGTAGGAGAAACAAGCATGAACCTACTG
          TTTCTGGAACAACAAGAACGCAAGACCTGCAGCGAATTCAGATCTACCCTGTGCCGTATT

          GCAGCATCCAATAAAACTCTTGACGAATTGTGGCGTGTGGGTCGGGCTGAGCCAACGCAG
          GTAGCATCTAATAAACTTCGAGACGAATTGGGGCGCGTGGGTCGGGCTATGCCAATGAAG
          GTCGCACCCAATTAACCCCCTGACGAATTGTGGCGTGTGGGTCGGACTAGGAAGATGATG
          AGGATCTCTGGTTGGTCGCGACAAGGGCTGAGACCCGCGTAACGGGATGGGCGCGGCATC
          GTTGGGGCCAACCGGCCTTATCATTAGATGTGTAACGTAGTACGCGTTTAATTCGTCGTC
          GTTTTACTTAGCTGGCCTTATGCAGAATCTCAACCCGTGCACCAGATTGTGTTCGTGCAA
          CTCGCATACGGGAGGGTGCGGGAAGGGCGACATTTAACAGGCTGGAGTATGACCGCAGGA
          CCTACCAGCGGGGGCCACTATAAAGGGCAGTGCGCCGTAATGTCAAATATGGACCGGAGC

          GGCTCGTTATGGAGCAAGTCAAAATGACTAAACTAAGGATAATGCCCGTTGTTAACGAAT
          ACTTTGTCTAGGAGTAAGTCATAATGACTATGCCATGGACAATGTTAGTTGTTCACGAGA
          GCCTCGTTATGGAATAAGTCAAAACCACTAAACCAAGGCCAACGTTTCTTGTCCATGAGA
          GTCTTGTTGAATAGTCCTTCAAGATGGTTTAAGTAACAGAACAGGTTTATTCCAGTGACC
          CTTTCATTAGGTCATGACTCCAGGCACCAAGAAACGAGAAACCGTTCTACAACGATGAAT
          AGTTTTTTAGGTACCCTCTTGACATGGTCCGCTATAAAGCCGTATCCTGCACTCGCGAGA
          AATTCAATGTGGGCCGACATAAAGGGGCTAGCGTTACAGCTCCAGTCCGTGTCTAAGAGT
          GACACGCCACGCACTTGCTTGCAAGAACCAGAATCAGCATCCTCCTGTGCATGGAAGAGA

          TGCAGTGTACACGGTGTCGGTTGTGTCCTTTCTCGGGCGGATCTTAAGAAGCAAATCCGG
          CGTAGTATACATGGCATCGCCTGTATCCTCTCTCGGGCGGAACTTGAGAAGCAAATCAGG
          CGAAGTATGCGTGGTGTCGCTTATGTCCTGTCTCAGACCGTTCTTAAGAAATTGGTCCGG
          CGGAGCCAGATTGCAGCACTCAATTCTCTAATTGTCTCGGGCTTTACTAGATAGATGTGG
          CCAAGGAACGCTATTACAGTCCGGCTCCCATCTGTGCCAGCAGTAAAATTTCCGCTACGG
          GGGCGCCAAACATTAATAATTGTGGTCATACGCATATTAAGAACCATAAAACACGTCCGC
          TAAGGTGAGCCCTCTCCAATCCGTTCACGAGTCGTATGTCACTTCGGAAAGCCGCCGTGA
          TAGAGATCAGAGACCCCTGCCGTCATGCTATGTGCGTAAGAGCCCGGTGTGCAGAATGCC

          CTACAGGTCACAAGTAGGGCGCGTGTCGACAAGAAGTCTC
          CTACAAGCATAAGGCTGGGACCGTGCTGCCAAAAGGTCTC
          CCATACGAAGCAAGTAGGACCAGCGGCGCTAAAAGGTCTC
          AACGTGAGAAGTTATATAAGCTCCCTTGTCGGAGGAATAC
          TGCTTGTCAGGCAATAGCGTCTAGGTCGTCAGAAAGTCTT
          CTCCCTTCGGCTAGCAGTGCTTGTCGCCTCAGATAATCCC
          CCTTCATAAGGCGGTGTCTCTTACCCTATACGTTAATGCT
          CCTACGTAACGAGATTGTGTGGATTTAGTCGTAATATCGT

