 8 1000
t1        TTCGCGAGCAGCGGACACGAGTGCTATGAAATGAGCACGGCGTCCCGTCGTCTTACTCCA
t2        TACGCGAGCTGCGGACACGAGTGCACTGGAGTAAGCATGGCATTGCGGCGTCACACTCCA
t3        CGTGTGTGTCTAAAGCGCGGGAGTTTCTCCTCACTTGAAACACGCGGCTGCTAGCTAAGT
t4        CAGGACTCCACAACGTGTAGGGGCTCCCCTCTTAGGGCTACGCGAGGCAGCTAGAAGTGT
t5        TGAACAAGCAGCAGACATAGGCCAGACGCATCGACGTCCGTTCCAGACCTCAAGAACTGC
t6        TGCACAAGCGGCAAACGTGGGCCCGACATTTAGACGTGCGTTTTAGGCTCCTAGAACCGC
t7        TCTACGAGTATCAGCCGGGGGCTCTTTGGACTACGATTTGCCTTCGCACACCAGAGTAAT
t8        TCAACAAGCAATCGCCGCGGATTCCCTGGATTACTGTTTGTTCTTAACTGCTAGCGCGCA

          TCAGGAACCATCACCTTCACATTTCCGATGAGGTCTGATGGTCCTAGCATCTCGTTCAGA
          TCAGGAGTTACCACCTAAGTATGTCCGATGCGGGCCGATGACTCTGAGATCGTGTTGAGC
          CTTTAGGGACTCGCACGTGCATTCCGTGCACTCCCTGAAGTCCCTGGGATCTATTCGACG
          TATAAAAGTCTCGTGTCGGTATTCTGGGTGCTGTCAACAAACCTCGGGATATCTCCAAGG
          ACCTAGGGCTCTGTAAAAGCGCGGCCAACGATGGTCGGGTATCTAGTATACTCGTTCAAG
          ACTTGAAGCTTTGTGTAAGGGTTCTCTTCGACAGCCGGTTATCTAGAACATTCGTGGAAG
          TCTGAGAGTTCTGCGAAACTGCCTTGAGCAACAACCGATCAGTCTGAAAAATTGTACAGG
          CCTGAAAGTTATGTAAATATTTCTCGAGCAGTGACCGGCTAACAAGAATAGCTGTACAAG

          CCGCAGGGTCCAGTGTGTGAACCAAGAGCGTGTGTCTAGGATGCGAGCCTCAGCACCGAT
          TCGTAGGGCCCTGTGTGTGAATCAAAAGCGTTTGTTCAGAATGCTACGTTCAATATCGAC
          GTACGCTTTCACGCGTCCCAGCGAGGCGGAAAAACTAGGGAAGATGCAACTCACAACAAA
          CTACCACATGGTGTGCCCTTATGAGGGGGATAAGCCAGGGGAGTTGCTACTCACGACTAC
          CTGATTAGCTACATATCTAAGCGGGAGCAAAGGATTCCAATAGGTGCCGCAAACCCCGTG
          CCGTGCAACTATACATTTGAGCGGGAACAATGGGCTTTGGCAGGTGCTGCAAACTCCGAG
          TTTCCTACCGACGAATAGCTGTGTTGAGTAACCGTGGCCAGTACTGCCGCGTGCTTAGTG
          CATTCTGCCCACACCCTAATGTACATAGTATGCGTTCTGGGTGCTGCCGTATGATCAGCG

          TGGCGGAAGTAGTTCTAGCTGGGATGCGCGAGGCTGTCATGTAGTCGTGCACGGGAATAA
          CGGCGGAATCAGTCTCAACTGGGACGCGAGACGATGTCGACTAGCTGTGCGCGGAGAGGA
          AACAGGTTTTGAACACATCTGGCCTGAATAAGGACGCGCACCAATTTAGATAGTGATGTG
          AGCAGGTCTTATACTAGATTGGACGGGTTAACAATGCGCGTCAGTATAGTTTGTGGAGTG
          CAGAAGCATCGGAGGCCTTGTCGAGCAGTGTCGACCCTCCTGAGTTCCATATGCGAGTAG
          CAAGTGCATAGAAGGACCCAAGGAAAAGTATCAGCCTTCCCGAGTCCAATAAGCAGTAAA
          AAGGAGCATGAAAGGCCCCCTGGAGGAACGTCGACGGGCGTGACATACATGTGTACTATG
          AAGGGGGATAGAAAGCCCTCTGGAGGAACACTGACGCGCCTACGATAAATGTGTACGAGG

          GGGATTGACTGGACTCTCCACGCGTTACATGTGCCACTAGAATCCACAGCGCTAACGGCA
          GGGATAGTCCAAGGCATCTAAGTGTTATATGTGCTAACTTAACACGCAGCGCTAACGGTT
          TATCCTGACTGGGTCCCTCTAGAGATGTAGGCGCTATTGGCATTCGTCGCGGAGTCTGAA
          ATTACTGATTGGACTGCTTACGAGAAGTGGGTACAATTGGTGCCCACCAGATAGGGGAAA
          CCTCCCAGACACGGTTTTCTTCAATCATCGTTAGACTAGCTCACTTTAATTAATACCACC
          CGTCCGAGACACGGTTTTTTTGGGTTGTCGATAACCTCGGTCCCCATATGCTCTACCACT
          TATCCCGGTTGTAGCATCTACGGTTCTCCATCAAACTCGACCGTGCGTGCCTCGCCTGCT
          GATGATGCATCCGGCTGTTATGGTTTGTTGTTAAGCTTGACCTCAAGAGCCTCGCCCCAT

          GATTGCGTCCGTGAGCGCTTCGGATCCTGGCATTTGGTGGGATAATCCATGTTAGGTCCG
          GATAGCGTCCGAGAGCGTCCCGCACTTCGGCGTCTAGCGGGATAACCCGTCGTAGGACTG
          GACACTTATCCAAGGCCTTGGAGGAATGAATGGTCGACGGGCGAACCTGCACTGAGCGTG
          GCTACAATGCTGACGACTCAACAGGATAGACGTTTAATGGGCGGACACGCGACAAGATTG
          GTGGGCGTCCTTTTCAGTCGGGTCAGTAGGTGTTTAAACGGAGAATTAGCCCCCGAATCC
          TTAGGTGTCTGCTTTAATATCGTTGGCAAGTGGTGCAACGGACGATCAGCTGTCCGCACC
          ACAGGTGACTGTATCGGCATCTTTATCAAACGTTTGGATAGGGGTCCAACTACCAGTTAA
          TTGGGCGTCTCGTTCAACGCCACAATCGGGCGATTGGATTATGGATCCACGGCCGAATTA

          TCTGAACGCATACCTGCGTGAGCAGATGCGGAATACCCATAGGCTAGCTCGGTCTTTTCC
          TGTGAAAGCATACGCGCGTGAGCAACTGCACCAGGCCCACATGCTATTGTGGCTATTTCC
          TGAGGGGGATTGCTCGTCTGTGATAACATTGTTGTGTTACTTACAGCTGCGCATCTTTCT
          GAAGGACGAATGAGAGCTCGCGGCTTTAGTGTCGGCGTTTGCGCAATATCTCTTGCCCCC
          GCGCGTCCCGTGCGGGAACTCGTATTTTGCCCGAGTGGACTTTCAACACTATGCCCTTCA
          ATACGTCCGGCACGGGAATTCGTCTCTCGATTGGGCCGACTTCCAACACCCCGACTCTCC
          GATTGCCTCGTGTTAGATCATGTGGCAAGAAAGGACCAAATTAAATTGATTCGCCGCCCC
          AATCGTCTCATGCCAGACCTCGCGTCTTAGAAATACTACGTTACAGTGTTTCGCATCCCA

          CGCGTACGCCAAGAAATGTCGATGGTTAAAAGCACCTTGCAGGCTCTCCGTCCATAGAGT
          CGCGAACATCAAGAGATGTCGATAGTCATAGGCACCTCGCTGTCTTCCTTAACATAGAGC
          CGCGTGTATCCTGCCACTAAAAGCATGATTCATTCCATTCAGGTTACGCGTGTACCGGTC
          TGCATTTATTGCGACTGGTTAGACACTATCCGCCCCGCACAGGTCCTCAGCGGGTTGGGT
          TGCGTTAACGCCAATTCGCGAAATGAAGCTTGCCACTCTCACCGCTTGATCGCGTACGGG
          TGTGTTCCCGCAGATACGTGAAACGTAGCTCTCCACACACACAGTATGCTCGTGCACGGG
          TGGGCTCACAAGTACACTTGGAGACCAGCTCATTACTGCTCGCGTCACGAAGTGCGCGAC
          CGGCTGCGCGAACACATCTGGAAATCAGTCCCTTGCTTTTCTCATCTCGGAGCTTCGAGC

          GGGCTATGCTGTTACATAAGGCTGCAATCTCTCCTCACTCTGGGTGGGCTACTAAGAGCT
          GGATTATGTTGTCACACTAGCCCATAACCTCTCCTTACTATGCGTGGCCCACTTAGAGCT
          GTTATCCGCAGCTTGTCATCACAGGATCGTTCTTAGATGCCGTAGGTGTATTCTAGGGCT
          AACTTTCGTACTTTTCTATTACTAATGGGCTATCTGAATCCGCGGACATAGCACAAGAAT
          AACCCGTGTTATCTCACACCTTTTAATGCTCTCTCCATTTCACCGTTATGGTCTACTTCG
          AACCTGTGCTATAATCCACCTCCAATTGGCTTTTTATCTCCAACGATATGCTTAACGCCG
          ATTCTGCATTCATCTAGCTGTCCGACTGGGTTGCGACCTCACATAATATAGCCTAGGTTT
          ATTCTATGGTTACCTAGATCCTCGACCAAGTTGCGATCCCCTACAGTACGGGTCAGGTTT

          CCCGTCCCCGCCGTCAACGAAGCTGCTCACGTAGCCGGGAATGCCGCGAAACTAAATGTC
          CCCGTCACCGCGGTCAGCGAAGCCATTAAGGTGGCCGGAGATGCTGTAAAACAAAACGCC
          TCGGGTTACGTAAATCCCGGACCATTTATTCAGGAGGTAAGTCCAAACTGATTTGGCCGA
          CAGGGACAACCTAAGCCCGGCGTAATTACACAGGGAGCGAATGTAGGCTTGTTCGCCAGA
          AGGAGTGGAGACCCCAGAACTGCTGTCCCATCGAGCAGTGGTACGTTCAACGACTCCGGT
          AAGGGTGGGGACGCCAAAACAGTAGTCCCTTTCAGTACCAATACATTTTAACTCAGCAGT
          GGGGACTACCAAGTCATGAAAGCAACACCGCGGAATTGCAATGCGATAAAGGTTAGCAGA
          GAAGATTGTAGAGTAACCACAACAAAACCGCAAAATGGAAATACGTCAAAGGTCTGCCGA

          CCATGCGGAGGGGGGTTCAGCTGTTCATCAGACAACATCTCACTAGGTATTGAGTAAGCC
          CTATGCGGAGGGGAAATTATCTGTTCAACAGATAACACCGTACTAACAAATGACTAAGCC
          CATCACTGAGCGGGACTTTGACTTTGGTCCTGTATGCCCGAGTTGAGCGACTGTCCAACA
          AATAAACAAGTGAGGCCTGGATTCTCATCGATTGTCCCAGTCTTTGGCAGCTTTCGGATT
          TCTCTAATAGTCGCACTAAGCGACCCGCCGCAGTAAGACGAGATCCCCGACTATTGGACG
          CCGCCAGCAGTCGTATGAAGTGACTCGCAGAATTTAAGCGAGATCCTACATTACTGAGTG
          TCTCTAGAAGTCGAGTTTATCGATTCGTCGCATGAGCGCACACTCCCGGATAGATCGGCG
          CACCTAGTGGAAAGGCTTGCTAATTCGTCGCACGAATGCCCAAACCCGCATAGCTAGGCG

          ATATGTCATAAACGTCGGCATTACGGGATATAAAGAGGTAGAGATAGAACTCATCGATCA
          ATTTATCGTAAATTCTGGCATTACGGCATATGAAGCGATAGAGCTGAAACCTTTAGACCA
          GCCGGCAAGGCATTCCAGATAGCATAATTAGAGCCGTCTCGAATGATAAAATCCACTGCA
          GCCGACGGGGTGTCTCGCTAAGTATAAACACAGCTGCTTCAGATCAAAAAATTCACTTAC
          ATGCGAACTTTCCTTTGACAATATGTAGGGCCTTGATGCCAACAATGAGATCTCTCATCA
          GTTGGAATTTTACCTTGGCAATGTATTGGGGCTGGGAGTCAGCGTCGAGTTGGCTCAGTA
          GTGAGCATTCTACCTAGGGAATGCGCAGAAGTTTGAAGTCGATACAAAGCACCCCCCTCA
          ACAAGCAATCTTCTTAAGGCATGCGTAGAGGTCCGAAGCTGACCCTGAACGGCCCCAACA

          TCCACGCGCCGGGCTCGGTGTCTTGCGAAGGATGGCAAGGTTGTGCATGAGAGCCTGGTA
          ACTATACGCCCTGCTCGATCGCTTGTGAGCACTGGCTAAGTTGTACATTGAGGCCCGATA
          GGCTACTCCCTTTCCTAGACGTATGGGGGCACCGCGCAAGTATTTTCGTGTTACTAAGAC
          CCCTACCATACTCTCCCAATGTTTGAGGACAACGTACACAACGAATTAAGTTGACAATGT
          TTTTAGAAGAGAAGCAAATCATACACGAAAGATGGGAACGTTTCAGCTTCTCCAACAAAG
          TTCCAAAGAAGATGCAAATCATATGCGAGGGGCGAAGACGTTTCACCTTAACACGCCGGA
          TTTTAGCAGTGAAATAAAGCCAACACGTAGAACAAAGACGTCCAACGTTCCCGCAAGGAG
          TCCTTGTAACGAAGCAGCAATAACTTGAACAACGACGATTTATAACTCGCCTGCACGGGG

          CGTCCGATCGTTATTTCGTCGGTACTGGCGATCTGAGCCGTTAAAGCAGAAGATATTAAT
          AGTCCGAAATTCATTTCGTCGGTACCCGCGATACGTCTGGTCAACGAGGCATTGAATGAT
          TGTATTGAAGGAGTCAGTGCGACACTAATAGTTTATGCGGAGCGTATGGAACGCCGCTAG
          AACTAATTGCATGTCAGTGCGGCTTCCGATGACCACGAGAGTCTCACAAACCGGAACCAG
          CTCCATCCCCCTTCCCTAACGCCCCTAATGGCACAGGTGCGCCTCTGAATAGTAATCGGT
          TTCTCAATTATCTCCCCAACGCTAGTAATGACACAGGTGCTCCCTGCATAAGCAATCTGT
          CCCGCTATACCCCGCTAAATGCACGCCGTGGGTTAAGCAATCCCCACGATACTAGCTGGT
          TCCTTTGTCTTCCCCTTGTCGAACGTTGTAGGACATAAAATCCACGAGAGAGTAGTTGAT

          CCAGGCAAGAAGCCTTCGAATTGACCAGCTTTTTTGCGCATGCAGACCTGGCCCAAAGTG
          CTGCGCAGGAAGCCATGGGACTGGCTGGTTTTTCAGGGCAGGCTGACTTGGCCTAAGGGG
          GTTAACAGTGTACAGTCGGGGTGCAAGTAACCTTTGCACTTCCCGATCCTGTCAACGAGG
          ACAGCTACGGTACAGTTGGGGTATTCGTACCTCTCGAACCTCCCGACCCTGGGTAGGAAG
          AAATACTACTCTTTGCGGCTGCAAAAGGTAGCGTCCGTCTTCCTATCCACACCCAAGGTC
          GAATCCGAATCGTAGTTGGAACAAGGGCACGCTCCAATTCCCCCATTCACACTCAAGGAC
          AAACATTTATCGAAGCAAGTGCAATAAGACGGGCTGGGGCTATCACCCCTGCTTAGGAGT
          AAACATCCAAGGAAGCGAACGCAGCAAGACTCGGTGATGCTACCACCCCTGCTCATGAGT

          CACCTCGTGGACGAGAGGTCTATGTGCACGTTATACTAATGCGTAGCCCGACTACCCCAA
          CGCCTTGTGGACGAGAGTCCTATGTACTCACCATACTGGCGCGTAATCCAACTGCCTTAA
          AATATCGCAGAGGAGTCCATAATATGTGTAAGAAGGTTTAGTCCGTACCCTACTCGTTAT
          TAATTCGTGATGGTAAGTATAACACACGCATGAACTCCCGATCTGTCACCTACTTTGCTT
          TATCTCGGGCGGACTCCTTTAGACCACCCTTCATTGTATAGGGTTAAAACCTACCCTACC
          TATCTTGAACAGATTCCATCAAACAATCGCTTTCTGAATAGGGCTGAAATCCACTTTCAC
          TCCCACATTGCGATTCATTCAACTTCCTCGCTACCACGGAGTGCTGAGATCCTTTACCTT
          TTACTCGCAGCGAATCCTTCAGATCTCGCGCTGCGACAAAGAGTTGCGATCCATTGCCTT

          GAAGTTTCAAGATGCGAAGACATTGTAGATTTGTCTACTT
          GAGGTTTAAAAGTGTGAAGATCCTAGGGCTCCGGCTGTGT
          GATGCGTCGAAACGGTGGTGCAATTCAGAGCTCGGTGGAT
          GGCGTGCCGAGATGGTCGTGTCATCTGCAGCTCCGTAGGG
          GATCATTCATGGCGCGTTCCGCATATGTCCTGCAGCTTGT
          ACCGACTCTCGGCGTGTCTTGTGTCTGCCCCTTGGCATGC
          ACCCTATCTTCGCGTGTCTAACACCGGTTTAATTGCGCGC
          TCACCGTCCTCATGTGCTTAATACCAGCCCGATTTTGTGC

