 8 1000
t1        AGCGGCTACACCCTCCCCTGCAAGTTAGCTTGACCTTCTAGCATTGACACATTTACGACG
t2        AGCGGCAACACTTTCACATGTAAGCCTGTTCGATAGTTTAATGTTTATACATCTATGGAT
t3        AGTGCGTACCCTTTCACCCGCAAGTTAGTATAATTGTATAAGGATGATACATCAACGGCG
t4        AGTGACTACATTTTTTCCTGTGAGCTAGTTCAATAGTTTGATACTGAATTAATTACGACG
t5        GAAGGATATGTACTTACTTACCAACAGGTTCTTTAACACAGTGCCGCGTTACCTCTTACG
t6        AAGAACGGACTTTTTCCCGGTACTGCTGATTTAGAGATTTGTGGGGCCCTATTAGACAGG
t7        ATAGTCAACATCCATCCTCCCGCGCGGGCGTCCCAGTTTAGTACGAAAACACTAACAGTC
t8        AACGTTTACGCGTTGTGGCGGAATCGAATGCAATGATAGACCGTGTGATCATTGACTCGG

          AGGTCGAGTCTCCCAAGCGTTATCCCCTCCCCCGCGAGTTGTTTCGTACCCGGCTCTCTT
          ATGTTGGGTGTTCCACACGGTTTTCCTACCTTTGCGTACCGTTCCGCTTTCGAATGCCTA
          AGGATGAGTTTCCCATGTGATTTTGGTATCCTCGTGTACTGTTCCGTAACTGATCGTCTT
          AGACTAAGCCTTTTAAGCGGTCTCGCTTCCCTCGGGTACTTCTTCGCGGCCGATCGCTTC
          GAGCTAAGTCCTTTATTCCGTCCGCGCACGCCTGCAACTCGTTGGGCATTCGATCGCGCT
          GATCTTGGCTATTCAAATTATCCATGCATCAACGCGGCGCCGATAGTATCCGTGTAAAGT
          AGAAGCCAGATCCTCATTAGTGTGACTACCAGTCTGGGGCATCCAACCAAAACGTGTACG
          TAGCCACGCTAGGGAAACAACGTGCTTGGAGAGTTATGCCTTCCAGTATAAATACAATCG

          GAGGCATCTCGAGAGCGGGATAACATAATCAGCGATTACCCGTAAAAATTCCCAGCACGG
          ATGGTATTACATCAGCGGGACTGCGTAATTCCGGATTCCCCGTAACAATACCCACTGTAG
          AAGACATTATACGAGCGGCACTATAGAATTCGCGACCCCCCGTACTAACCCCTACTACGA
          ACAGAATTTCAAAAGCAGGTCTACGTAATTCGCGATTCTACGTACCAACTCCTAGTATGA
          AAAATTTTTCTTGAGCGGGCTTTAAGGCCTCGAGAATTTCCACGTTATTTCAAGATATAG
          ACGAATCTTCTTTACCAGCTTTCCAAAACCCGCTGCGCACTAGATTTGCACCTACGTTAG
          GTAGTTCTTCGGGAAACGAACAGGCCAGTTCGAGGCCGCGCGCATCTGGCACTCTCAAAG
          CCATTCTCTTTTAACCGATGCTGTAGAAATTGATAATCCACAAAATGGTTCCTTCGCCAC

          ATGTTGGGCTCTGAAAGAAAACAATTCATGTAATTTGCACGTAGATACCACCCTGATTTT
          TTGTTGAGCTCTGACAGCAAACGAGCTGTGCTAGATATATGAAGCTACCACCTTGATTTT
          GCTTTTAGGCCTAACAGGTGTGGAGTCATGTGAATTGTACGAAGCTACCTCTTTGATCTT
          AAGTTAGACTCTGATAGGAGAGGAGACACACGAGTTGGACGAAGTCACATTCTTGATTTT
          CTTTAGAACTCCGTCTGAACAGGAGTCTAGGGATACGGATGGCGATCAAATGCTCATTAT
          ACATCGTTCATCGTCTGCCACACTATCCCTTATAGGCGGTAAAGCACATTGACCAGTTTA
          GGCACGATATATACTTTCACAAGAGGCCCATTAAGCCAGTGCAGAGTCCCTGGTGGACGG
          TGGTCCGCGTCCTCCAGAGCGATGTTCTTCTCTTACAGGCGTGGTTCCTCAGCAGACTCA

          CGCGGACCCACCAGGCACTGTATTCAGGTGTCAGTGAAGCCGAGCTTGTTTGCATTTATG
          CATGGAACTACCAGGCACCGTACCTAGGCACCACCGAAGATGAGCTAACTAATATACATG
          CGTGGAATCACCATGCATCGTATCGAAGCGTTACCGAAGCCGAGTTGAGTAGTCTTCATG
          CATAGAATTACAAGGCACCGTACTAAGACGTCACTGATGCCGAGCTAACTAATCTTCATG
          TTAAAAACTGGGTGGAATAGCCCCTAAGCGTCAGACATGACCGTCTAATCAGTATAAGTT
          TATCGCGTATACGAGTTTTGACTACGGGCGCGATCAACGATTTGGGAACAGTGGGTGATG
          CAAATTACACCCAGGAATCGATGCCGGGGGTCCAGGTTATACTGCTAATACGCTTCGATA
          CTAAGTCCCGCCGAGACTAATTAGCCGGAAGTAATCCTGACCATCTACGCTGATAACTCC

          ACTAGTATCTCAACTAGAGGGGCCGCAACCCGATTAACTGAGACGTCATACCAGCTCGTA
          ATCATCTCCTCATCCAGAAGGGTCGCAGCGCGACGACCCGGAGCGTCCTTCGGGCCCGTA
          ACTATCACCTTACCCAAAATGGATGGTGCCCGCCAACCTGGAACGCCTTGCAGGCTCGTA
          ACCATCGCCTCATTCAGGAGGGACGAGGTCTGATAACCCGGGGCGTACTACCGACGCCTA
          ATCCGTCCATAGCCTGAAAATCGGGCCATATAACTAGGTGGGGTATTATGTTGCCGCGCC
          GAAATGGTCCAGTCACTTACGAATGACGGGTTGCCAGATGTTATTAGCAGTCGGGCGACG
          GCTCAGGAGTCAGGGTCCGAGTGTGTATGTCAGCTAACCAGCGTTTCACCCTATGCAATG
          GCTCAAGGCCTGTCTTGCAGTGGAGAAGCATGATTGTTCAATGCGTGGTGCCCTCGAGGT

          AATTGAAATCACGAGATAACTCTACCACAGAATTCACCCAGTTCATTGTCGGTGCCGTAT
          AAATGCAATCTCCAGATATCTCTAAAACTAAATTACTCTCGCTATTTGACGGTACTATGT
          AGATGTAGGCTTGTGATAGCTCTATCACTGAACTACCCCGGTTAATTGCCGGTGCTGTGG
          AAACGCAAAGCCGAGACGTCCCGATCATTGAATCACACCCGTCGTCCGGCGGCGCTGAGT
          AAGTATAACCATGAGAAGATTCCGTCACAGTACAGTTCTTGCTGCTTGGCAGAGCCGTAA
          CGAGGCTTTCCTGTACATATGCTCTGGCTCAGCCACGGGTGCTTTTAGTCGGGGTCGTAA
          CCGCGGCATGGAGAAGACTTGTCTTGCTACTGACTTTCTTGAGGGCTTCCAACGTGGTCA
          CCATGTGCACTAGTAAACGGGTGGTGTCACAGACAAGGGCAAATGCCGGCCAACTTGACA

          CTATTGTCGATCAGTGACCACCGACACACGGTAGGCGAATCAACCTCACCCATCAACAGC
          CTGCTGTTGTCTAACCACCACCGCCACGCGTCATGTGCGCCAGCTTTCCCCATTAATAGT
          CCACTGCTGACTAGCTACGACCGACGCGCGACATGCGAACAAGCTTGTTCTATTAGTGCT
          CCACTGCTGCTCAACCGCGACCGACGCGCGGCACGCGTATTAGTTCGACCGATAAACACT
          TCAGGCGGGATACATAGACACTAAAACAATATATTAGAAGTAAGGTGTCGAGCACACGGT
          TCCGCTCAGCCGCATTAATACCAGAGGAATGGCTTCGGCCAACGCCAAGCCATCGGATCC
          CAGGAGCCACCAACCTTGCGCTGGATGGGCCAAAACCATATAAACTAAGTCACGTGCCGT
          CATAGCTGGCCAGAACCGCGCTGATTGGGTATACTCGCGCAGGTTACCCTTATGTAAAAG

          ACACTCACTCAAGCTGATAGAAGTGTGGTGATTCTACAACTGACACATATTGTCATGTCT
          CCAATCACTCATACTGATAGAAGCGTGATAGCCCAACTATTGACACGAATTTCATTGCTG
          ACTGTTACTCAAGCAAATTGAAGCGCGGTAACTCTACTAGTCGCAAGGCATTTTATTCTT
          ACGGCCGCTCAAGCCAGACGAAGCTTGATAACCTTCTTAGTGACTCAGACTCTAATGCCT
          ATCGCCAATGAAAATTACCGGTGCACGACGAGCTTATCACAGACACGGAATTTACCGGGA
          TACACCACGAAACGTAGGGAGTGCGAGACGGGCCTGTCAGCAATGGTGGGTCTAAGCAAT
          TTGGTCATGGAAGGTGGGAGGCTCGTTTCGAGCCGGCTTGCGGAGGGTGTAGTCAGGGTT
          TCGAAAACTCGGGATGCAGGACCGGGGACGGGCGAGATGGAAATGTAAATGCCCGAGGGT

          TGCACAATTGGACCTCGCATCGCTGGTTCAGAGAATACACTTTAGCGTCGAATACGTAGG
          TGACCGATAAGACGACGCATCGCCGGATCCGTGAATCTGTCCTAGCGCCATTTATATATG
          AGGACCACAGGACGCAGCAGTGAGGGGCCCGTGAACATCTCGCAGGCATGAGTATACAGG
          TCAACAATAGGTCGATCCGTCGCGCGCTCCGCTAATTTATACTAGCGCCGAGTAGGTTGG
          TGAAGGCTAGAAGACCGCCCCGTGCGGAGCACGGACTAGTATCCGTTGAAATTATAAAGG
          CAAATGATACGTCTTCAAATTTTGTACCCTGCGCACAAACACTCGAACAGAGTTAGACAG
          CTGAAATTATACTAGTACGGAAGGCGTCAGGCTTAACAGTAACGGCCGAGTAACATGGAG
          AGGATAATACGGCCCTTAACTACAGACTTGACGGATAAGAATGAGTGCGGGGTGTCCATG

          CCTTAGTGAGTGCTGGGGGCTGCGGAATTTGCTGCGGCTTACGGGACCTTTAATTTAACC
          GCTTAGTAAAAGCATGAAGCGGCGAAATTTGTTAGAACATACGGGTCTTCTCCTCTGGCC
          ATTTAGTAGGAGCCTGATACTATGAATCTTGTCAGGGGTTACGCACCGTCTTCCCCGACC
          GCTTAACAAGAGCTCGAAACCGCGAAATATGCTGCGGCATATGGCTCTTTCCACTAGGGC
          GGCAAACAAGAGTTGATAGCTGAAAGGTGCGCCGAGGCGCGGTGACGCTTAATCTATGCC
          ACTAAACGGGTACCGCGTTTTCCTCTTGGAATTATTGAATAATGAGTCTAGTTTTGCCCG
          GCAAGACGGATGCCACAGCGCGCTAACACAGCCGCCATGATGTAACTCTTGATCGAGTCG
          TATCGATTCGAGCACTTGACACCGGATACAACGTTTGCAGTGAGTTCCCAAGTTGTGAAG

          GGGTTACATGTACTGTCAGATGCGGGCGGCTGAGTGCTATCATTAACCAGTCGGGCTCGT
          CGGATAGACGCATTGTCGCATGACGTTGGTTGAGGACCAAGGTTGAAAAGGCGAGCGCGC
          GAGTCAAACGTAGCGTTGGGTGAGGGCGCCTGAGGGCCGCAATGAAACAGTTGAGCCCCC
          GGGTGATTCGCGTCGTCCGGCATGGGTGGCCGAGAACTATACTTAAACTATCGAGCACCC
          AAGTCAGGTGCACTACCAGATTAGGGCAGACGGGGGGTAAAGTCGTTCAGTCCGGGGCGT
          AAGCAACTTTCACTCCAGACTGTGGTACGTCGCGGGATATATGATCTGCAACGGCATCGA
          TGGTCGGCTGTGGCTTAAGATGTGGGGATGCATGACCATTTACCGATCCACCAGGGTCTC
          AAGTCAACCATACTCGGGAGCGGAACTGGGCCAGCGGAAAATATAACTTAATAAGACGGG

          GCAGGTTATCAGAAGCCGTCAATGGTACGTGCCGAGGTAGCTTTCATTCAGCTTTAAAAT
          GGGGGTTTTCCGCCATCGCCTAGGGTCCGTGCTGAGGTTGAATCTAATCAGCATTCAGCC
          AGTAGCTTTTAGAAGTCGTCAATAGTACGAGCCGAGGTTGCTTCTATCCAGCTCCGTGTT
          GGTAGTTTTTAGCAGCCGTTAATGATACGCGTTGCGGTTGCCTCTTTTTATCTTTATATT
          GACGGGCAGAAATCACAGTTAATTGCGAGCGTCGCGGATCGTTGGAATTGGTGTTATGGC
          GTTGGCACAGGGTGAAACATCCTGTCACACATTCTGTTGAACTAGGACACAAACTGTCCA
          GGCGGTGTCTGACAAGTTACCACAGTTCTTGCCTAAGTTAGACACTGGTGGTTTTCCGCA
          AGTGATATCAGGAACGAGGCTAAAGTAACGCTCTAAACTTTACAGCTGCGTAGAGTTGGC

          GACGATGCCAATATTAAACCTCAATTGGCGTGATACTCGCACAGTGTAAGCACTACTGGG
          CACGCTATGAACGTAGAATCAACACTAACGTGTGACCCATCGTCCGTAAACATTTCAGAT
          GGCCATGCCGATCCTGTAGCTCAACTAACGTCTAGCCAGCCTACTGTTCTTATGTCAGAG
          GATGATGCTAATAATGAACTTTGATTTAAGCGGTACCCACATATTGTTGAAACACCCAAG
          GCTCCTGTCCACATCGCGTGTCGGTTAGCGCAGTTATAGAATACTAAAGGCTGGTTAAAG
          GATACGTTATTTGGAATAGGCCCTACAGTCGTGTAAGTGGGCACTGTCGTTCTGGCTCGG
          GCCCCGACTTTCGCAGCGGATTATGCCATCCGGCACACAACCGCTCTACGACGGTTTTAC
          GCTTTGAACCTTTACGTACGTGAGCCATTTAGGTGGTAGCCCGTGCGCGCGAGACCTGGC

          TAAGCGCGCCCTAGGAATACCTAGTTCGTGCTCATCAGGTGGGTCGCGGTTATCTTACGT
          CAAGCGCGCTCCAACGATTCTCAGTTCGCGCCCGGTAGCGGGTACACAGTTGTTTTGCGT
          CAAACGCGCACTAGAGACATTCAGCACGTGCTTGGTGGCTAGGTCACAGATGTTCTGCGT
          TAAGTGCGCTCCAGTGCTAATTAGTTAGTGCTCGGTAGCTGTGTCAAGGCTATTCTGCGG
          AAAGTCCGCCTCATATATACTAGATACAACTTAGGAGACAGGGTTTCAGGTACTGGATCT
          CTGCTTCACCCTGTCTAAATTCATCTTTGGGGCGATCACCCAGAACTCATCTCCCTGTGC
          CCAAGTTACGATATGGGTGCTGTATGTGACGTAGCTGGTTTGGTAGGGAGACGCCTACGC
          CTGTTCGGAGTACTGAAAATCTTCCTTTTTAGGGACATTCTTGGTGCAATTACTTTTCGA

          CCGGGGATGCGGTATCCGACACTTGTGTACCAATTGCACAGTCTGACGTAGAAGTCTTGC
          ATAAGTTTACGGGCGGCGACGCTAGCGTACTCTTCGTCTAGTCAGACGTAGTAGTCTTGC
          CTGGGTTCATGACGGCGGACACTCCTGTACTAAAGGTGCACTTAGATGTAAAGGTCTTGC
          CTAGGCTTACAGGGAAGAGCCTTAGCGTGTCCGTCGTCTTATTAGACGTAGAAACCTTTC
          TCACGACTACGAGGCCAGAGAAGAGTGAATCACAGAATCCCACATAGTCCAGAGTCTCTC
          CGAGATCGGCGTACACGGACATTTTCGTCACTTTAAAAAGGGTAACACTCAAGGACCCTA
          ACTAGAGCGACCAGCCATCATTTAAGCCATACTGAGGAAGTATACCAGACGCGCGGTTCG
          TCGGGTCCGTGAATCGCGCAATCGAATTAACCTTCAAACGCGTTTGGACCGCAAGCTCGC

          CAGATCACTGGCCATGGCCAGCTCTTATGTTCACCTGTTT
          CAGTTTGCAGACCCTTGCCTGTCCTTGTGTTCCCGCGCCC
          TAGCCTGCGAGCCGGTGTCAGTTTTCGCGCTCTCGCGCCT
          CGACTTGCGGGCCATTGTAAATTCTCACGCCCTCACGCCC
          CAGTTCCCGCGACGCTACAGGCCATCAGCTCCTCACTTCT
          CACTTTATCTGGTATCCTTGGTTCCTGTGCATACACCTTC
          TCATTGGCCGTACTCGTTCAGGCGGGCTGTTGGGATCACT
          TCACCCGTACCCTATTGCCTATTTGGGCGCCCCTTACGTG

