 8 1000
t1        GCATCTGTTGCTATATATAGTCTGATACGGGCATCCGGGTCATGGAGGTTGCCGACACGA
t2        GCACCGATTGCCGCTCGCGGGCAGCTTAAAGGATTTAGGTAAATATCGTCGGCGGGCCCT
t3        ATCCCGGTCCTCGCGTGTGGATTGTTATAGCAACCGGGGTGTGGGCCGTGGGAGAAGTAT
t4        ATACTAGCTGTCGCCTGGAAGTGACGAAGGGACGAGTGGCATACATGACCGATACCCCAT
t5        GCTTTCGGGATATTACGTGGGTGGAGCAGGTGGTGGAGGTTCCCGATGTACGGATCGAGT
t6        GCATTATGAGTATTATCTAGCCAAAGTAATAGGTAGAGGGTCGGGGAGCGGGGAACGCTC
t7        TGGAGATTGGACTAAAGCTGAAGCACGGGGTCACCGGCGAGACAGTTGTGTTGACTGCTC
t8        CTCTTGTCGGAGGCCGGCAGTTTGCTCCGGCGTTACGGGTGAATAATTCGGGCAACGCTC

          CCTCCCTGAACTTAATGAGGATTTAGAATCGGGACAAAGTGCCCGCAGACGCCAATGACG
          TCCCTTCTCACTTCCTATCCGTCAGGGATAAAAACGGAGTCCCCCTCAATGCTTAGGACG
          CCTGCCTTTAGTTTATATCCATTCAGTTTGAGACATGAATCCCTTTACGTATTCTTACCA
          CTATAACCTCCCCAAATTACACTCTGTATGTATGATCAATTCATACACATCCTACCGCTG
          CCCAACTGCACTTAATATTCCAGCGTTGTACCAAGTGAGTCTATACGATGAAAACCTACG
          TTCTGCTATATCTAACACCTAGTGGGCATACCGACCGCGCCTAGTCGCCTATTACCTATC
          ACTCGCCGTATTCTGAGCTTATCTGTTTTATGGAGGGCGTCCCATTCCGTAACGTCGGCA
          TCCACCTGCGCGCGTTGGCAATTCGAACCACGGTGAGGGTCACAATCTCTCACACAAGTA

          GGAACAGTCTAGGCGCGTGAGTTGTGAAGAAATGTGTAGGTTATAAACTACAAGAATAGG
          GCCGGCGCCTGCGAAAGTGACCTGTGAAAAAGCGCAGAACCGACTGCACTGAGGTCCAAT
          CCCAAGGCACCTGAGAACGGTTTGATAGGGGGCGCGCCGTCTACCTATTTGCAGGACCAG
          GCCGTTATGCGAAAACCTGACCCTAACGGGAGAGTTTTCTATTTTACTTGACTAAAGGAT
          ATAGTTGGCCACAAGACTGACAACGGAGAGCGTTGGCCGACTCTCTTTCTGTCGAGTAAA
          ATTGCTAGGCATAAGCTAGGCAGTAGATGCAGAAAACAGCCTTTTTTCTAATGAGGTCAG
          GTGGCCTCTACTGTTAGCGTCTCCAGCACAGGAGTACCTGTAACCGTCACAAGTAAATTG
          ACACATGTAAGTTAGTGCGGTCGTCGTAAGGACGGTATTGAGATATTTTGGTGTAAAGTG

          GTTTCGCAATCTTATGGGTGTCTCTCAGGTGAGCTAGATCCTACCTTGAATTCTGCGTAC
          GCCTCGTTTCCCAATTGGCCATTTTGTCCAGGGCTGGCCGCCGCTGAGGATCTGTCTCAT
          TTCTAATACTCTCATGGACCTAGGCGTAGCGCGTTTACGGCTGTCTATGTTCTGCAGACC
          TCTTGGCCTTTGTACGGGTATTCTTACTCTCGGAAGAACGCAGTTACTTACGCACCGAAC
          GTTCCGCAACTCTAAGGGCAGTTAGTTGAGAAGATGTTCCCCAAGAAGACTGGGCCGACC
          GCTGTGTACCTTTGAGAGCGGTCCCTCGGTGTAATAACCGCCGGAGCGTCCACATCGCCT
          GCACCGAACTCATGAAAGAGGCTACCACACGGGTCTCAACTCTCTACAAAGGCGAAGCAT
          GCCCTGGACCCACCATGGTAATATTTTCAACCGTCAAGGGCCTTGTATTCTTCTGTGTCT

          GACCGATTGTTTGGCGCAAAACTAGTTGTTTAGAGTATGGTCCCTGCCCACACTACCTAA
          GGGAAATCGCTTGCTGTCCAATCTACTGACCACGGGTCAGCATACCAGTACACCTCCTTG
          GGTAGACCATCTGTCTCATGAGCCGTCACGTAGGCTACTGCAGGCGCGCACCACGCTCTG
          AGCAGGGCGGATAATGCGCAACGTAAAGTGTAGACCTCGGCGCCAATGCGCTCTACACCG
          GGCTAATTGTTCACCACGAGATTTGAAGCACGGATCTCAAAATATGCGCGTAATAAACTT
          GGCAAAATGTTCACCGCGAAATCGAATGCCTTAGACACAAAACATGCGAACGATAGCTCG
          GAGGAATAGTTTGGAGTATCGTAAAACACGCCGAGTAGCACAAAGACACCGTTCGTTTTC
          GTAATAATGACGGCGCTACGGTTAGGCAAAGGGAGACCATTCACAGCGTAGAGTAGTATC

          CCAGTGGAAGACGATCGTCGCACCGAGTCCCGGATATTCCTCCAACCGTACCCGGGTCCT
          TTATCTGAAGCTCATTGTTACGTAGTGTCTAAGGGACTCCTTCGTAGATTCCGTTCATTT
          CCGGGCTTAGACCCTTGCGACGAAGAGTCTAGGAGCTACACCCTTATGAGAAGGGGGGCT
          ATATCTGCGATAGATTGCGACCTTGAGCTTAGAGATGTCAACCATGAGGGACAGGGAGTT
          CCGCAGGGGGAATATTACAAATCTGGGCCTGGGAGTCTGATTCGTGTGTGGGTGGACTTC
          CTGCCCAGACATAGCTGTCACAGATCGCCCAATAGTTCCATATCCCTGTGTGATTATAGG
          TTGCGTGGTAGTGGTTCTAAACACAAAGCTGTCAGCATGATGGATTGTACAAGAGGTGTA
          CTCGGCGGCAACTGAAGTCACCGTTAATTCTAGTATCTGAGATGCTCCTCAAGATGTGCA

          TATGCCCGGATGTTTTCCCATTAAATAAGAGTGCACACAGGGTAATGCGAGCGCATCATT
          TATATCGGGGGATCTGCTTACTAGAGTGAGGTAAACCCCGAACGACGCACGCGAGTTGCC
          TCTAAAGGTGGGCTTCGATAGTAGATAGAGGGGGACTAGTCGCTGCGCAACTGGGCCTCC
          TCTACAGATACTTTTTTTACTGAGACAGAAGGTAAAAATCTGCAATAGTAGGTAGTCTCG
          TATGTAGACTCGATCGAGTGTACTACATGAGAAAGTAGTAAATTTCGGAAGGGGGCCGCG
          TACGTGGGCTCGCATGGCATTTCGCCATGGGGCATTATCTAGAGACGGACATCTATCCTG
          ATCTCGGGCTCCTTCCGCCCTTAGGCTGAGGTCATGGGCCAGTCTCCGACAGCCACGTTA
          GGCAATGTCCAGGAGTGCTTCTATAAGTTATATACCGCCTACTTCCATGCAGTGCTATCA

          AAGACGCCGCCACCCACCGTTCGTCTCCACAAGATGTGCGGCGAGATGTCGCGGTACCCC
          GCGGCGTTATCCGCTGCTGCCAGTTCAGACTTCATGTATTTTGAGTCGCCGAGCCGTCAC
          AAAGCGCTACCAATAACCATCCGTTCTAGTGCAGTGTGATATACGGTACCGGGGCACACG
          CGGTTATCACTGGTTGCCAACCATTTCAGTGGGATATAGAGCTATATAGCGAGTTTCAGA
          GAGGTATTACAGACCATCATCTGTTTGCAATAGCTGTAAAACCAGACTATGGTTAATGGC
          AAGTTTCGAAGGGTCATCGTCTATTTACAATTAGCATACAACCCGGTAACGGACCCAAGT
          GGAAGACTGCCCGTTCAGGTGCTCCGTAAGTATGTCTCACGGCACAGATTGATCGCGAGT
          TATATGGCACTGCTATAAGCATCTTGCTGCGGAAGGACCCAGAGGATGTCGTTTGGCGGC

          CGCTACGCTGCCCCACTGGAGTAGGTTTCGGGGCCTACCACATACAAGCAATCTATTTGC
          AACCAGACCGAAATGAAAAGGCAACCTACAGAGGCCACGAGACAGCGACACTTTATGAGC
          TGTGAGGTCGTACTTTAGGGGTCGATTCTAATGACCTGCAAACCATGATAACATACTGAT
          TACGAGGCCGCGGATCGAAGGTGGGCCCTTGGGACTAGCGGGTTGTACCCATTTACTGTC
          GATCTTGCTTACATAGTATGGTCGACTTTCGGGACGGGTCCGCTGGGAGATTTTCTCGTC
          GCAAATAGTCCGACAGTAACGAGCTTCGTAGGGCAAAATAGCATGGGGTTCTCTATCATT
          AGATAATTCTGTTAGCGTGAGCCGGAGATTGCTATTTGTGTATTGCAGTATCACCTCGGT
          GGTATAGAAGTTAACTGAATAGGGAAATCTGACCGAAATGAATATGATGAAAGCGCCTGC

          TGGTTCGATAGCACTTACGAATTGGATAGTAATGAAATTAACCCGAATTGGTGCGTTTAT
          AAGTTTGGTCGTACTTAGAAATCGGATATTAGCGGAAATACCCCCTGTTAAAATGTTCCT
          TTGTCTGCTAACGCTTATAGGACACACCCCGAGAAAACTCATCACCTCAGCCGCGTTTGT
          TCGCTCGGTTGTTCATGGGTAATCTATTTTGCGAGAGGACTACTTACACAGCGAACGACC
          TTATACCCGGACAGACAGTGAAGGCACTAGCAAAAGAATCGATTCAGCTAGCATACCCCC
          TTCGGCGTCGATAGCCATTGGAGAGGCGACGGCAGGGCTCGGGTCACTTAGCTATTTCTC
          CGGCGTGCAGACAAACTCTGAATGACTTCCTGGACGGAAATCGGCTCAAGAGGTATCCTT
          TAGCTCTTAAGCACACTAGGGTCGGACTTTTGCGTGAACAACATATCGTAGCGTACAAAC

          CCCGTCTGTCACTGGTCCTAATACACTTTGAGAAACTTGGAGTAAGATACGCTTTCCGTG
          TCTGTCCGTTGCTGCCCCCAACGTTTGTTCAAAGGTGTGTTGAACGACACGTGTCTCACA
          ATCGTCCGCACTGGTTCTCAGTGCACTGGGGACAAATTCGGGTGGGCTATGTCCTCCGTG
          CTTGGCTGCATCAGTGGTTATTAAACAAAAAGTAGCCTGTGGTAAGACGATCTCCCGAGG
          CATACTGGCGGCAGATCCCAAAATTTGATAAATAGCCTGTGGCGAAAAAAAGCTCTGGGG
          CCTACCCGAGGCGGTCCATAAAGCTCAAACGGGAGTCCGTGGTAGGATTAATCTCGGGAG
          CCTAAGAGTATTCTGCGTTATGAAATAATAGGCGAGTCCAAGCTATTTGGCCTTACTAGA
          AGAGCGAGTCCCACTATTCACAAAATGTCAGTCCGAATGTCAGTACCCGGACACTCGCCG

          AATCTAGCGTCTGATCTACTGGTGCACATTTGCACAACTCTAACCGAATATCCCGTTCGC
          AATCTCCTGTGTTATGCACCGGTGAACCGAACCAAATCTCCAGTATACCCCCCTGTCTGC
          GACCCGACATCTGTACTTCTAGTGTTCAGCTTTACAGCTCCTCTGAGTTGTTATGTTCAA
          GTACCACTGTAACGTCGGACGGCGTCTCCCCTTTCACTTTAGGTGGGACCGTGACTATAT
          AATCCTATGGCTTGTCATGAGGCGGCCTGTCACTTGATCTTCCTGGAGTATTCCGCTCAC
          GAGCCCTCGACCCATTAACAAACGACCTGTCCTACGGTCTTGATAGACAATCCTTTCGAA
          TCCTGTCGGTTCTTTCCCACGGGATATACTACGACGAGTCATAGTCAGAGTTCTCCCTGA
          TCCCTTTAGTTTCACCACTTACCTGGTCTCTGTACAATGTCTGCCCACTATCATCCCCGA

          TAATCTAGCGGTCTGGCGGGCCACTAATTGTGCTCTACAAAATCAGTGATTGACGAGTCC
          GGACCTGGAGGGCTAGTGTGTCGCTCAAAGTGTCTTGTAAAATAGGCAGTAAAAGGGTAT
          CGATCCAGGGGCCTAATTTCGACATACTAGTGCTCGGCATGTCGGAGGGCCTACAACTGC
          TGGTTTATTGACCTACGGAGAAGTTATCATTGCAAATCGAGGTTGGACTACGACAACCAT
          CGGTTAACAAAGACGGTGCATAGCCGGCCCTACTCCGCAGCTTATGGTGCGCATAACTGT
          AGAGGCATTGAAATGGCATACCGCTGCCCCTTCCCTCACCGCTACGAGACGAATAATTCT
          ATGTGAGCAGACTCAGCGAGTAAGAAGCTTTCTTTTAGACCTTAGACCGTGATTCTCCAT
          AAGCATACGTATCCACTGTTCGCATATTAATACACCGTTACACGGGTTCCGGATAGGCGT

          CGTGCTGTGGTTTGCCGAAGACCAGACAAAACTATTCAGGACACAGGAATATGTGGGTGG
          CTGTATATCGACCGTCGAGGACCAGATCAGGACATGCCCAAAACTGATGTCCCAAGCGGG
          AATGCTGAGGGCCACCTAGGAGAAGTTTCGCTCGCGGGTATCATCAATCGAGGCACGTGG
          CAACATCAGGGCAGACTGCGCCCCGCATCGGTTTTATCTAGCTCCCTATTGCATGAGGAT
          GGCCCTATTACTTAGTATCTAGTGCTTAGGAAAATAAGCGGATAAGAGTTCCGAGGGAAC
          AACCCGTCGGTTCAGCCTCGAGCGATTGGGAAGAAGAACGGCCTAAAGACTGCAGGGGAC
          GCTTTCTACGGTGAGTAAAGTTTTTCTACAGAGACACGATGTGCCGGTCCGTAAAAAAAT
          TAGTTAGATGCTTCGTGAAGTTTCCCTTTCAGGTTTCCAGGGAACTGCTGATAAAGGAAC

          AAGCGTATACTGCGGAGCATCATTCCCGCAACTAAAGAGTAACGGAAATGCGACGAGTCG
          AAGACTAAACGGTTAAGAATCATTTCGGCATTTAACTTTCAATAAATTGGCGACCTCCAG
          TAGCTCTTATAGGCGGGTATTATCTTTACACCCAGGAGGGAGGGAAATGCTAAAAAACAG
          CACTACACCTACCTGTCTTCTGCAGATAGGTTCCGGGAAGAGCGTAGAGGTATGATTCAG
          TACTCCGTATGGAGGAGTCTCTCCCCTGTGTTTTATTAATAATGAGTCGATCTGTTCTAG
          TCCTCCTTGCGAAAGAATTTCCATCTCAGCTCTTTTCATCAATGATACAACCGGTCCTCG
          CCCACAAGCTGTCGCAGATTGTCTATCGTCCTTAAGTAGTGGTGCCTAGACTCGCATACG
          CATATAACACGACGGTGCGACACCTTCCTTCTTTGCCGACAGTTCTTCAACAGGTTTAGG

          ATTATCTCGTATGTAGAGAGGTGCCTCTAGCAACACACATAAGAGATATCGCCACTCATG
          CTCTTAGCATATATATACATGAGACCCTAGCGCTCTTCCTATAACGAACTGCGTCTTATT
          TTCACTCTATACGTGGAGCTAGGCCCCTTCTAATTACACTGCGATATCCTATGAACTCGA
          TGCAGGGTAAAAGCAAAGCCGGGGTGTTACGACCCGAGTCTCTAGATTTGGTCCGTGACG
          TGAATCATTCAAGCTAATGTTGGATCGCGGAAGTTCTAGTCAGAGGACCCCGTTATGAGT
          TTAGCAGTTCGTGGGTGCATTGGGGCTCGGCAGACGAGACAAGAGGATCTTGTCACGGTG
          ACTACACACCCCGTGAAGAGTTATCCATCAATACAAGTGTGAGGGACTCAAGGCGCCGGG
          CTTAATCCAAGTGAATACAGTTAGCCACTTCGACTAGTACTAAAGGGCAGGGGAGACATA

          CATAATACTGTTAGCTCTTTTAGTTTCATAGTCTTCAAGA
          ATAATCCGAGCCCGCTTTTTTCATATTCGAGATTCCAGCA
          GCCGTCCGAACTAACTTGTATGCCATTATGGCTTCCGCAC
          GAGCAACCGCCCTCCTTCAATGAAGTTTCAATGTGCGTCA
          TAGTACATTACCCGCAACCCCGCCGTACAAACTTTTACAA
          TTACGCCCCATGGGCCCATATGATGCACTACCTTCTGTAT
          ACCACTTTAACCCGCCTGCGAAGCGCAAGTGACTCCAAAG
          ATCTACTCGGTCCGTAATCGTGTTTGTGAAGTCTTTGGTG

