 8 1000
t1        CGGGCGTACTACCTAGGTCAATCTGATTTGGTAGCGTTGTGTCAAATGTTGATAGTGTGG
t2        CGGGCGTACTACCTGGGTCAATCTGATTTGGAAGCGTTTTGTCAATTGCTGATAGTGTGG
t3        CGGATGCAGTAGCCTGGGTCCGACTATCCACTAATATCGGCCAAGCTGCTGATAGTGGGG
t4        CACACGCATCAACCAGGCTCCGACAACTCGACTTGCTTGCTCTGGCCGCTAACAGGACGG
t5        ACCACGCACCACGAGGGTCTTGATATCCCGGCTGGATCTATCTCCTCACCAACGGGGAGA
t6        AATACCCGTCATTTAAAATTTGTCAAGCTGTGATCCTAAATCTAGAGGCCGGTGACATAT
t7        AACCCAGATGAAGCCGGATTTCGTTGTCCATTGCGCCAGGTTAAGCACACGGGATCTCAT
t8        AGCTGTCCTAGACCCGGTTCTGGTGGTTAACTACGTTGGGATCAACGCCGAGGAGGTCTC

          GGCTCCTGGGTAATCGCTCTCACGGGTTAGGCGACAGATACTACTACGATGAACTACTTT
          GGTTCCTGGGTAGTCGCTCTCACGGGCTAGGCGACAGATACTACTACGTTGAACTGCTTT
          GGCTACCGAACAGTCGCAACAATGCTTCATGCTAGATATGTTACTACCAAGCACTAGCAA
          GGCTCTCGAATAATCGTACAAAAGGTTAGAGCGGAGGATAGTAATCTGATAGATCAAACA
          AGTCTCCGGCATCCTATTCAAAGCACCAAACCTTTAGATACTTTCATGATTAACAATCAA
          GAACTTCAAATTAACGCCCGTATGCTAATAACGACAGGGAAGACCATGACTAATTAACGC
          GGACTTTGCAGGTGCCTATTTTAGCTCGGCGGTGAGTATACCATTATGACTAGTCCACGA
          TGACTCTGCAGGATCGTCCGTCTAACTGATGCACTGACTTTCGACGTGGTATGACAGGGA

          TCCTGCAGGCCTATCCACACGACGAAGCCGTCGACGAAACTAACTAACAGGCAGTAGCGG
          TCCTGCAGGCCTATCCACACAACGAAGCCGTCGACGAAACTAACTAACAGGCAGTAGCGG
          CAGATATGGGTGATTCATCCACAAAAGAGGCAGGGAACGTTAATTATTAGACAGTTCTGG
          CCGAACTGCTTGGTTCGTTCAACTAAGGAGCCGGGAACACTAACTTACAGGCAGGTCGGA
          TTGACTAGGCGGAATATAACACCTACCTCGCCAGGGATACTAACAAACGGTCGGTAATGG
          CTGATAGGGTAGATTGGATCATGCAAGGGGTTGGGTATACTGACTAACACTCGGTATCCT
          TTATCTCGGCTCTTTTCCCTACCTGAGCTTTCGAACCTTTTCGAAACTAGAAGACTCGCA
          CGTGTTGATCAAATCTGCTAACCAATGTATCTGAAGGTATCTATCACAAGATGATTGTTG

          CAGCGACCCAATAGCAAGTCCACAGGTATAGGCAGCGGGGCCGTCCCCTGTGTTACGTCT
          TAACGACCCAGTAGCAAGTCCACAGGTATAGGCAGTGGTGTCGTCCCCTGTGTTACGTCT
          CTTTAGATCACTAACAAATCTACCTGTATGGACAGGACGGTACTGTCCCGTTCCATGTTT
          CCCCGACCTATTAACAGCTCAATGGGTGTATGCAGTGCGGGGTCTTCCGACCTTCCGATG
          CCCCGGCGGACTAACTTGGTAGCTATAGGCGGCAACACGGCTCTTCCCCGCTTTGCATTT
          TCTCGATCCGCTCTCTGGACGGTCAACATGTCAAATGGGGCCTTTCACCACACCCCATCT
          TCAAGGTTGAACAGATGACCAACCGTTGCTGATACTCGGGCGAGGGCTCCTAACGCACCG
          TGTAATTACGCACGTTTATTACGGAAAGAGGGCTGCTAAACATTGCCCCGCGTCGTTTCC

          ACAAGGTCAAGAACGTGGGGAGGTAGGGAACGTTCCCCTAGAACAGATACACCCGTCTGT
          ACAAGGTCAAAAACGTGGGGAGGTAGGGAGCGTTCCTCTAGAACAGATACACCCATCTGT
          ATGATTTCGTGTACGTGAGTAGATGAGGCTTATCCCACTAGTTTAGGCAAACAGACCTGC
          ATAAGTCCGAGCACGCGAGCTGGCGATGACCATCCCCTTAGGCCAAACAACTTTATATGC
          AGGACTTTGAGCCCGCGATTTAGCGACGCCCACCACACAAACCTAGGTAACGCTCCGGGC
          CTCGCTTTACTCCAGCGATGCGATCATCCCCAGCTCATTAGGAAAGGTAATGACCGCTGC
          GCCATCGTATATGGGCTAACAGCGGTTGTGTAAGGCTCCCAGTTAAGTGCTGACTACTGT
          ACCGCCCCTGAGACGCATTTGTTAGGTGCTTGCTAGTACCGAGTTTGACCTCTATTCTGC

          GGTATCCAGCGGGGAACGTGTAGGTTCCATAACGGATGCCACCGGGCCAAGCACGTCGTT
          GGTACCCAGCGGGGAACGTGTCGGTTCCATAGCGGATGCCACTGGGCCAAGCACGTCGCC
          AGAATTTGGCCATGAGTGAGCAAGTGAAGTATCGGACATCGTTCGACTCTGCATATCCAC
          ATAATCCATCGATGTGCGTGCGGCCTAAATGCGGCGCGTCTCTCGATTGAGCACATCGAC
          GGTATCGTATGTAGTGTGTGTCCGTAACATACCAGGCGATCCTTGACCGAGATAGCCCCT
          ATCATGATTCTATGAAAGGGACAGGCGGGGATTCGGTAACTTATACGTCGACGGGAACCT
          AGCATTTCACCTCGTGAGCGTTTTCTATGGATTATTTGCTCGTCAAAAAACTGCCCAATC
          AAAGTTTGAAACGGGGTATATTATTGTAAAAGGCAGTCACCTTCAAACAACTTGTTTAGT

          CATGTCACGACGAAACTAATCTCGCCCCAAGGCATGGTGTTGGCGCCCTCTCCACCAAGT
          CATATCACGACGAAACCAATCTCGCCCCGAAGCATGGTGTTGGCGCCTTCTCCACCAAGT
          CAAGTCCCCACATAATCAGTCCCACACTAGCGTAAGGCATTGGTACCTTATCCATCTATG
          TATACCGCCACAAAACCCATTCTACCCAAACTTAAGGTACAAGTCACTTCCTTTGGCACC
          TTAGTCATCAAAAGCCTAATCCTTTCTTAGGCTATAACGTCAGTATTTTTACCGTCTACT
          ACGGACACATAGGATCAGACTACACTTCATTAAACATTTTTATTGCTCTCGATTCAAACT
          TGGATTGTACCTATACTAAACTCACTATGCTTGCCCATATTGGCGGTAACCTCGATAACG
          TTGGTCCGAAGATTTTTCACACTTGCTGGGAGCCGTATTAAAGTCATTTAACTCTCCTCC

          TTCACAATTCTATCAAGCGCGTAGTACGTCTCTTCAGGAACTACTGCGGACGTCGATTAT
          TTCACAATTCTATCAAGCGCATAGTAAGTCTCTTCCGAAACTACCGTGAACGTCGATTAT
          CCAACAATTTTATAAAGTGCCTGGTATGTATTTTGGGGAGAGAGCGCAGATTTCGATTAT
          TCCACTTTTATCCCAAGCGTACATTAAGTCTCCTCTCGTGCAAGCGTAGCCGTTGGTTCC
          ATGCCGGTGACTTCAAAGGATTTTTTAGATGCTCAGCAAACCATTCCACTTGACAGTTGT
          TCGGACGGCGTACCGAGCCGTCCCCTAGCTAGACTAGCATTGGTCGCGGAGGATGTATAC
          TACTGGGTACCAACGGATCGACCGCACGTGCGCCAAGGTAGAGGTAAAGTTGTCGCCACG
          TAGACAGACCTCCGGAATTATACTCGCATCGACCAGGTGCGGTCTGGATTGGACGTGAGA

          AGTACAAGAAGGGTGTCGAGTCTTGAGGAGCTTGATGTAGACTCAACACAAAAGTACGCA
          AGTACATGAAGGGTGTCGAGTCTTGAGGAGCTTGATGTAGACTCAACACAAAAGTAAGCA
          AGCTCACGATGAGCGTGGAGTTCAGAGGGGATTGATGAAGACACGACAGCAATATTCGCG
          CATCCAGGACGAGTATTGAGTCTATGGGAGGTCAACGTTGACAATACACTAGTGCACGCA
          GGTATAGAAAAACCGTGGGGTTCACGCAAAGTCGACCTAGACTTCTTAGAAAAGAAAACG
          AGTTATCCGTGAGCTTCACATTTAAGCGGCACAGACCTTGTCGTGCTGGCGGATAACATT
          AACCCGAGGTTGGGTTCAAGCTAACCGGAGCTCCGAAGTGATTCTACGCTGAACTAGCCG
          ATGGCTCCCTCGGGACCGAGCCGGAAAGGACACGACCCGAGCCGGCCGGTAGGAGTCTTA

          GGTCTATGTTAGCGAAACTATTATCCAGCCCAGGGGCGCAGTCCTGGTTAGTGAACAGAT
          GCTCGATGTTAGCGAAACTATTATCCAGCCCAGGGGCGCAGTCCTGGTTAGTGAACAGAT
          CTTCTCAAACGCCAAAGCTGTCCTCCTATCTAGAGGTGAAATCACGGCTAGTGATCCGAC
          CCTATCAAATAACACAGCATTCAAATAGTTTGGAAGCGCAATCATGGCTAGCGAGCCGAT
          CATCCCATCCAGCAAAGCACTTCTCCTGCCTAGTGGAGTGGCTGTCGCCAGTGGATCAGC
          ACTCTCAGCTCAAGGTGCTGCTAAACTGTAATAAGGAAGAGGTTATAGGAATGAGGACTG
          GTTCTCCGTGACCCCTGTTGCATTTCTGCTACTAGGGACAACTATAGCATGTGGGTCGAG
          ACTCCTATAGGAGTCCGTTGTGTGTGCGCTAGGGACCACCGTAATAACCTGCGAGCGAAC

          GGACAGGTGCGGTTGCTCTAGTGAGGCTCTAAACAGGCGTGACCCTAGCTTTCCCATATC
          GGACAGGTGAGGTCGATTTAGTGAGGCTCTAAACAGGCGTGACCCCAGCTATCCCATATC
          AGTAAGGGACAGTAGATTAACTTCGGGCCAGAAAAAACGTTACGTTCGCTACTCCGGACT
          GGCTAGAAGCAGTACATCCACCGGGGCTTTCAAAAGGCGGGGAGTTCATTACTCTTAGTC
          TCCGACGTACAGACCAATGACAGCTGAATAGCGGGGCAGCGGCGCGGACCCCTCCCCGAT
          AGTGTTAGGCGACAACCGCGTTCCGAACATGATGACACGTGAATACCGTCATAACTCTAA
          CATATAGGACACCAATATTGCCAGAATTCTGAATAGCCACGTCCCTGGTTCTTCAATGGC
          TGTCACGAGCCTGGTTGCTGACGAGGACTCGCCCGGATAGCCTAGTTAGTGCCTATTCAA

          GAACATGGCAAGTCGCGAGTGCCTGAGCCTTCGCAGAAAACGCACTGCTCATTGTTAGCA
          GAACATGGCAAGTCGCGAGTGCCTGAGCCTTCGCAGAAAACGCACAGCTCATTGTTAGCA
          CAGCGGGGTAAGATCGGTCTACTCAAGAAGATGCGCACTGCGCACAGCCTACTATAACGG
          GGCAGGGGGCAGCAGAGGCGACCTGAGCTATAACAGATTATGCATAGAGCACTATTATGA
          CAGTGCGGTCGGACCAGGCATCCTGGGTCACCCCTGGTATCAGATAGTCTGCTGATATGG
          GAAGGAGGTTAGGATACATTGGCTGGATCAATCCTGGCCATGTATAATCTGCTACTGCAA
          TAGGAAGAACGTAGTAGACGCCCTACGGTGGTCCCGGTCACGGATGCGTTTCCACATTTG
          TCGGCAATTTGGCCCGAGTGCTGAGCAACTTCACCAGCTCAAGTCGTTTGGTAACTTTGG

          GCGACGAACCCTAAGCAGCGGCTGTATCGGACTCTAAGCCGGTGCACTAGCTTCGTTAAG
          GCGACGAACCTTAAGCAGCGGCTGTATCGGACTCTAAGCCGGTGCACTAGCTTCGTTAAG
          CGTACCCACATTAAGTCGCAGATTCATAAGGTCGCGAGCTGAAGTAATATCCGTGACAAG
          CCCATACGCCGTAAGTGGTGGCTCTATAAGCCCGTAAATTACGTAATTATTCGCGATAGG
          CTTATCTGCCCGATGTCGGAGTTTTACATAGCTGCAGCTGAGTGCCCTACTTCGAATAAG
          TTACGGAGCTCGGGCTGGTGGTTTCTCACGATCAGCAGTGGAAGACTCCGCTAAGGTGCC
          TCCCTCACCTCGGCCCCACAGGATGTGCTTGTACAGTACATGGTAGGTATGTAAATTCGT
          GGTGATAGGCAGATGAGATATCGCCCCCGCCTTATCACCCCGGACAGTGATTCTGATAGA

          ATACAACAGATATTGTACCCCAGTTGCACTATGGAGGTCCGACAGCACCCACGGTGGGAC
          ATACAACAGGTATTGTACCCCAGTTGCACGATAGAGGTCCGACAGCACCCACGGTGGGAC
          GACCGAAAGGTCTGCTAGTCCAAAAATGACATGGATTGCCGATAGTGTCCGTAATGCGTC
          GCCTGAGGTGTCTAGTACTCTAGTCAAAACGGGGCCGACAAAGCTTACCTGCGGTGCCAC
          GACTGACATATCCAGTAACACAATTCTGGGATGTACAAAAGTTGGTATACGCGGCGAGGC
          TGCGGGAGCACCCCGTATTCTAGGTTGGAGCCGTACGGGAGGAGATCACCACATGGCGCC
          GGTGTGATTTCAAACCGGAATAGACGGTGTTGACCCTGTTGGGGATGCCTGAAGCAGACA
          ATTCTTGGACCCACCCACCCTTGATCCAACTTTGTCCTGAAGGGGCGGGCCTCTGACGTG

          TCTTCTCGCCGAAGACGGGGTATAAGCCATGTCTTTCTCTGATTCTTCCTCCCCATCGTT
          TCTTCCCGCCGAAGACGGGATACAAGCCATGTCTTTCTGTGATTCTTCCTCCCCATCGTT
          ACCTCCCTCCATACCTCGACCATAGACCGTGATCTTTTGCAAGAATGGCTCTTCCGCGTT
          ACTATATGACGAATCTAGGCGAAGGATTACGTACTTCTTCATTACTAGCGCTCATGTGTT
          ATCTCTCATTTAGCGTTGGTCTCTAACAAGATGGTTTCTTTACATCTGGGCCTTCGCATA
          CCGTCCAGCAGAACTTTAACGCTTGCCGGGGAAGCATTAGGACGATATTTCCTACGTACC
          ATACCTCGTACAGGATTGCCGTTTGCGGTCTAGGCGGGTTCGAAATAGCCTTTACATATA
          TCTGTCCCTTACCGCTTGGAAAGCGTCTCCGTTGGCGCACTCCCCTATCCCATTCTTGTT

          ACATTACTAGGAGACTATCCTTGAGAAAATACTGAAGGTCCTCAAACCTAGTTATCCATT
          ACATTACTAGGAGACTAACCTTGAGAAAACACTGAAGGCCCTCAAACCTAGTTATCCATT
          ACGCCATCGGAAATTGAACTACTGGCTTACTTCAATCGCCTCCCTTTCAAGTTGTTTATC
          ATACCTTTGCCAATTCCACTCTGTGTCTAGACTAGATCTTCTTAGCACAGGTCGCATATG
          GCCCTGTTGTGCATTTGGTTAAGAGCGGACATCAAGTCCGAGCACCGTTGCATGATCATC
          AATCGGAGGGAAAAGAACTCAAAGACTAATACCCAGATTTGTGAGCCGTTAATAATGGCC
          CGCGACTGAGGTTCTTTGCCGGGGACCTATTCAGCGTATCGCGATACGGGGTTGATAGTT
          TTCGCCAGTTGCATGAGCCTGAGGTCCTCCGTCTTACGTTGTCTATTGATACAGTAAGAC

          TGTTCTGTGCGGCAGCACGATACAGGGCAATGTAACACGT
          TGTTCTGTGCGGCAGCACGATACAGGGCAATGTAACACGT
          TGCTAATCATGCCAGCCCGTCACAAAGAATTGAAGGGCGT
          TGTTATCTGTGGCGACCCGATTTGAGGAATTATTAGGAGT
          CAGTAAATATTTTCGTCCGGTCACGAAAATGAGCCAGTGC
          TACTATGCGAAACAGCGCGGTCCCAGGGTTGGACGGCCGG
          CGACGCGCACTGCCTGGGGGGCTGCATCGGACCTGTGTAG
          AGCCCCCCAATAACTCTAGGCGCAAGAGGTAAACAAACCG

