 8 1000
t1        TTCCAAAATTACGTGTATCAAACCACGGTGATGATACATTGACAATTCGAGCGAGTCCAG
t2        CGCAAGAGTGACAAGCCCTGCACCGTTGTGGCGATGAAATGTTCCTGCACGCATTAAGAA
t3        AACCAAGATGCTCTCTCACAAATTACGCTAGTGCTATCCTCCCACCGGTGGATAACAAGA
t4        GATCAAGATAATCTCTCACAAATTACGCTAGCGCTATCCACTCATCGGCGGAGAGCAAGA
t5        TCTCTCACGAAGCGCTAAATGATGCCTCTGTCAGTCCATTTGTTAGACATATAGACGATA
t6        TCTCTCACGAAGCGCTAAATGGTGCCTCTGTCAGTCCACTTGTTAGGCATATAGACGATA
t7        AACTTTATGTTCGGATAGCTACGTCTTCCGATGGTCCATTGGTCGTATAGTGATGCCGTG
t8        AGGCACACGGATAGATGGTTACATGATCTGACAGTCCACTGACCGCGTAGAGAATCGATG

          ACTAGGGTTACCCTGATATGGATCCGATACAATCGAATGAGTGCGAGTCTTTCACCGCAC
          GTACCAGCCACTTCGGTGGTGGCTTAATATATTCGAACGGGGACGAGCAACCTACAATAC
          ACGAGAGAGATCCGACCGAAGGTTTTGTAGATAGGGACAGGTACCAATCTCTTATTGCAC
          ACGAGAGAAACCCGACCGAAGGTTTTGCGGATACGGACAGGTACCCATCTCTTCTTGCGC
          AGGCAGACTCACGTAATGGGGGCATAGAGTCGGCACAAATTTGACCGCTAATGAACTGAC
          AGGTTAACTCACGTAACTGGGGTATAGAGTGGGTACAAATTTGACCGCTAATGAACAGAC
          ATGTAGTGAGGTCCTGCGGGGCCTCGGAGAATTACTACCAAGACACATGAGGAGGTACAC
          CTTCTGTGCAGCCCAGAAGGTGCACGGAATATTGTGAAGAAGGAAGTTCGGGGAACGCAA

          AAGTCAGCGCTAAGATTCGGCTAAGTGGGTAAAGTTGCAAACGCATTTTGGATGCGATCT
          TAACGATGTAAAAGATTCTACTAATCAGGCACGGTTACAGACGTCTTTAAGGTGTATTTA
          AGCCAAAACTCCTGGTTCAGCTACATGAGCATGCACGCCGGCGTCACCTGGGTGCGTCTG
          AGTCAAGATTGCTGGTTCAGCTACATGGGCATGCACGCCGGCGTCACTTCGGTGCGTCTG
          GAGCGACTCCTTAACGGGGGGCAAGAAGGTGGGTCATTAGGCACCGGTAGTGAGCCCCGT
          GAGCGACTACTTAACGGGTGGCAGGAAGGTGGGTCATTAAGCGCTGGTAGCGAGCTTCGT
          CGAAGACACTTGGGAGGTTGACGGACAGGTCCATAGAAGAGAGTGGATTATACTTATTGC
          GGGAATGTGCCTGGCGTTTGGCGGATCGGGACACCAGGAAACGTAGACAATTTACACTGC

          AAAGGGCAATGACATAGATGTTATTGAAGAACGAATCGGGTTCTCTCCACGCCTAGGTAG
          ATCATGTGTAGCCAACGATGGCGTTGAAGAATGAATCGAGCATTCTCCACTCTAGTAATG
          ATCTGGTAAAGTGTAAGGAAGCATCGGGCACCAGCACGAAAAACCTTTACTAAGGCCAGA
          ATCTGGTAAAGTGTAAGGAGGCATCGGGGACCAGCGCGAAAAACCTTTACTACGGCCAGA
          ATCTATGACTTCCCATCGCCTTGATAATCGTTAAACCAAGAATTTATAATGCTCGGCGCA
          ATTTATGACTTCCGATCGCCTTGATAACCGTTGAACCATGAATTTATGATGTTCGGCGCA
          GGCTACATACTCGCACTGTCCACCCGACTAATGTTACAATCAGGCGGGTCGCTCAAGGAG
          CGTTATATTCGGTTCTTCTTGTGCTGACTAACAGCAGAAACAGACATCCTGCCGCAGCAG

          ACGGATAGGTTACAGGACCGATCTGGACCCTCTCGGGCGCGAGACAAATTCAGGGCCGCA
          TCGGTTAGACGTGAGAGCCATCCTGAAGCTATCTTTACGAAAAATCAGTATCAACCGTCC
          CTAGTGCTAATTCAACGCCGTAAGGAACTTAGCCAAGCAGGAGAGAAGTTCTAAATCGCA
          CTAGTACTAATTCAACACCGTAAGGAACTTAGCCAAGAAGGGGAAAAGTTCTAAATTACA
          TGAGGCGGAGCTCAAGTAGCCTCAAAAATTACCCGTGAAATGATTAAGTAAAGCTACTTC
          TGAGGCGGAGCTCCAGAGACTTCAAAAATAGTCCGTGAAATGATTAAGTAATGCGACTTC
          AGGGATACATGCTGTGACGCGTGGGACGTTGGTGGAGACCTTTATAAAAAGATGATCATG
          TGACTTAGATCCCATGGTGCCACAAGTACTGCCCCAATCTATCATACGCTCTCAGCAATG

          CCCTTGTCCATAGGTTACTGCATAGCGAGGTATTGTCTAGGTGCTGCTTCACATTAGTCG
          CTCTGATTCATTGGCTGCTATGCAGCGACATATTGTCCTGGAGCTGTAATCGCATAGCTG
          TAGGAATTCCTTAATTGTCACTTTACTTGCTATAGCTTTGACTACTCGCGACATCAGTCT
          CAGGAGTTACTCAATTGTCACTTTACTTGCTATTGCCTCGACCACTCGCGACATCAGTCT
          TTAAGGGAACAAGGCTGACGCCTACCAGTGAATAAGTCCAGATCTCCACTAGGTTAGGAC
          TTAAGGGAACAAGACTGACGCCTACCAGTGAATAAGTCCAGATCTCCTCTAGGTTAGGAC
          TCAGAGGTATATGCGAGGCACCGGGCAGGAGCCCAATGTTATCTTGTATCACCTCCGCAT
          TCAACAATGCATCTGAGTCGACGGACCAAATTCCAATCAGCCATTAAGCTACTCATGCTG

          TCATTCCAAAACACTAAAATCATCTCAATACTACGCCGTGGAGACGTTGGGTCATCTCAG
          CCGCTTCGAGACCCCATTGCCATGCAAGTACGGCATCGTTAAGAGGTTGAATAGCTCACG
          CTGCGCCGGAATTCCAATTCCATGTCAAGTCGGTATCCAAGCAGAGTGGGGCACCCAGGA
          CTGCGTCGGAATTCCAATTCCATGATGAGTCGGTATTCGCGCAGAGTAGTGCACCCAGGA
          TTACGCAGCGACTTTTCGACTGCACTGCGGTGGACACCTCCGCTATACAGTACCCTGCCA
          TTAAGCTGCGTCTTTTTGAGGGCACCGCGGTGGACACTTCCGCTATACGGTATCCTGTCA
          TAACGGAACAAGATATCATCTGCTTCTGTGTGGCCGTTTAAGTACAGTGTGAGGCACTAA
          CGGAGGGTCAAGATACAGTTCGCTCCCCAACTGTTGTTCTAGGTAAGCGCCACCTTGTAT

          GTTCGGCCAAGCCTCTGATTGTTAATGTTGTAGTCTGAGGTAGTAGCAGTGAGCGGAAGC
          TTTGGGGCGCTTCTCTCACCGGATCCGCACAGGCCAAAGGCACTACTAGTTGACTTCGCT
          GTTTACCTGATTGCCCCAATTGCCTGGCCTATTGAAAGAACGGCGCGCTCACCCGTCAAC
          CCTTACCAGATTGCCTCGGTTTACTGGTCTACTGATAGAACGCCGCGCTCACCCGTCACC
          ACTCAGCCGGGACTGCTATTATTATCCTCTTCAAGAGCAAAGATTCGCTAAGTCGTGGCC
          ACTTAGTCGGGAGTGCTATTATTATTATCTTTAGGAGCCAAGAATCGCTGCGTCGTGGCC
          GTATAGACGGATATGCTGTCTCGCTTCTCTCCACTGTAGACGACGCTATAGTCCGTCGGC
          ACACACATAGGTGAGCTTCTCAGTTTAACTTAGTAGTGGTTGGCGCACTATGCAGCCGAC

          ATTCCATTAGTTATTAACGAAGATTTCCATTGTAAGGGTCTCTGTCACGCCCGCGGAAAA
          TATCTATCAATTGTCCACATAGATTCCGATCGCGAGGTGTATCGTGTTGCCCGTCAGAAG
          ATTCCATCTGCCGCAGACAGTGGTCTTTATCGAAGAATACTTTGCACCGTGTCCAAAGAC
          ATTCCATCTGTCGCAAACCGTGGTCTTTATCGTAGACTACTTTGCACCGTGTCTAATGAC
          GTACAAACCGCTATCAACAAAACCTCCTACTGTCTGCGCAACAGGTAGACTCAGCCTGCT
          GTACAAACCGCTAACAACAAAACCTCCTACCGTCTGCGCAATAGGCAGACTCAGCCTGCT
          GCTCTCCAAAACGCTGACAAGGGTATGCAGTAATAGAGCAACAGCGACTTTTACGATGAT
          GCTTCACTACATAACGTCAGGGTTCCACAGTGCCAGAGTAACTTTCATACTCGCAATGAT

          TCTATTGTGCTTAGATCATACACCGGTACCAGTCGGCTGCTTTACACCTCCTTCTGCGCT
          CCTATTATGTCCAACCCGGATATCGGGGCCGGTACGCCGTCGCTCGTCTTCGTTTTAACC
          TTCATCCTGGCGCAACTGAACATTGAAGACAACTTGCCACCGTCTAGTTCTGGTCCGACC
          TTCATCCCGGTTAAACTGTACATTGAAGACAACTTGCCACCGTCTAGTTCTGGTCCTACC
          CGCTTCTTGCACTAGTTGATCTATAATGTGCAGGAGGTATACTGCAAAGGGAAAAAGCAC
          CCCTGCTTTCACTAGTTGATCTTTAATGTGACGGTGGTATACTGCAACTGGAAAACGCAC
          TCCCCTCGGCTCCGATCGTATCGCCATGCGTGGGCAGCGTCATGAATCGCTCCCTGTTAT
          TTTCCTATTCTTCGGTCGCCCCACACTATGCGAGTGGCGCATTGTCCCGAACTCTCTCGT

          CACACATCGCTTCCCGCCGCAAGTGTACATGTTTCACTAGTAAGCCGGAAATAGAATTCT
          CCCAGACAGCCGCCCGCCGCTGTTGCAAAAGTGGCTCAGACTGGTCGAATTAGGAACTTC
          CGCTGATTGTATTCCGTGGCTGGTGCAAAGACTGCCTCTGTTGCTCGTACGCGGATCCCG
          CGCTGATTGTATTCCGCGGCTGATGCATAGATTACTTGTACATCTTGTATGCGGATTTCG
          TGAAACGTGTTATGTAACTTACAAGTATAGGCTTCGCAATCTCTATAAGTTACCCTTCAC
          TGAATCGTGTTATGTAATTTACAGGTATAGGCTCCGCAATCTCCATAGATTGCCCCCCAC
          TGCCACATGTTACGTTCAGCGGGCGTCAACGTTCGTAGTTCCGTCAATACCCCGAGGCAC
          GGCGAAATGTTTCGTGCCGTGTCTGCTGGAGTGCCGTATCCGGTCGCCATTTTGGTTCAC

          ATTCGTGATTAATAGGGGACAATACCATGCCACGGACCGTTGGGCAATATGCAACAAGTG
          GTTCAGGGCTAAATGGGTCCGTTGACCGTCCATTTTGCGCAGTGCTGCGTCCATCACTTG
          GGTCGCGGTTGGCAGGGCGAGCTACTCACCTATCTGATGACACTCGGGCCCTGGTCATAA
          GATCGCGGTCGGCAGGGCGAGCTGCTGACCTATTTAGTGACACTCGGTCCCTAGTCTTAA
          CAGTGTTATTAGCGCGAAAAAATGGCACCAGACTTAACGTCTCTCTGCTCCTCTCCATGC
          CAGTGATATTAGTATGAAACAATGGCATCAGACTTGATGTCTCCTTGCCCTTCTCCACGC
          CGTAGCTTCTAGCAGTATTGAATGGCCCCCGTCTTGATAATGTCTAACTCGATTCCTTGA
          CAAACCTCTTAGTGGGGGAGGATGACGCCGGTCCTCAAGCTGCTTCCCGCAGCACCCCGC

          ACTTCTTAACCATTCAACTTCTCACGACCATATGATGAACAGGCCTGCAAGACGCGACGA
          TGTTCCACAGAGTCAATGTCCACTGGGCTGTTCCACTGTAGGTCCCTAAAGTCCCGTCTA
          GCTTCTCGACAATCAGGCTTTGCTCGGCGAATCACCAGTTCGAAGAGAAAGCCCTGGCCT
          GCTACTTGACAATCAGGTTTTGCTCGGCGAATCATCAGTTGGAAGCGAAAGCCCTGACCT
          GTTGTCATACGTTAAGGCTCCAACTCAATATCAGTCATCTTGAAGAAGACCCCCTGCTAG
          ATTGACCTACGTTAAGATTCTAACTCAACACTAGTCACCCTGAAGAAGACCCACTGCTAG
          TCTTCTGCACCTCATAGGATATTCTGCCTAGCAGTTAGAGAAGTTGGGGTTTACCATGAG
          TTTTACTTTTCTCATAAGCTCTCGCATATATAAGTTAGAGGAGGTGGCACATCCAACTAA

          CGACTCCGACGGAGCACCTTAGTCTTCTGGGGTAATCATTAGCGAACCGAAGTGTGGCGG
          TAGCCCAAATGGACATACGTACTTATTTGGGTTATGCGACTAAAACGCGCCGTGTAGGAG
          CAGCCACCTTAAACGACCATCGATCCGCCGGAGACGGGCTTGACCTGTTCCGTGCGGAGG
          CAGCCTCTTTAAACGACCATCGTTCCGCCGGAGACAGACTTGACCTGCTCTGCGCGGAGG
          GTATGCTGGTAAATTGCTTTGGACGTAAACCCTATCCAACGACTGTGGGGTGATTCGGGC
          GTATGCTGATAAATCGCTTTGGACGTAAACCCTATCCAACGATTGTGGGGTAATTCGGGC
          TCTCGATGGCATTTCGCTCGCAACGTATAGACCAGTCTATGGAAACGACCTGCGTCAGAC
          TCCCGATACGGAGCCGGTCCCATCATGCCGTCAGCTCTAGGACTAAGGAAGGCCCCGGAC

          GTTAGGTTTGTGGCAGAACTACTACTTTAAATGGACCCCTCACGATCCCGAATCTAGCAA
          GCTAACTTCGCGTCGAGATTGCTGTTCTGGGCTGTCCCATCTCGAGATGCTATGCGGCTT
          AGTTACTTTGCCATGTAGTAGTAATCTCGCGCCTCCTCCAATCGTGCACGTACTCGTCCG
          GATTACTTTGCCATGTAGTAACCATCTTGCGCCTTCTCCAGTCGTGCACGTACTCGTCCG
          GAATGGCAGACCGGAGATGCCAGGTCCGGATCCTATTTGCATCGCGCAGACCCCCTGGAC
          GAATGGCACACCGGAGATTCCAGGTCCGGATCCTATTTGCATCGCGCAGACCCCCTGGAC
          AGCTACCTTGCGGTGCATTTTTCATCATTGGTCCCCTTATTCGGTGTGGTCGTCCTTCAA
          GGCAACCTCACAGTAGAATCTTTCCTGTTGGTTGCTACGTTCGGTGTAGCAGATCCTGGA

          TTCTAATTATCTGGCCCAAGCTTTGTGCAGAAAGTTTCAAGAATTCGCAGGAAGCAATCG
          GTATACACTCTCCGCCTTTGATATACGTCGATATCGACGAGAACCTGCAGGAAGCTACCG
          TCGCAGTACCTCCGTCCGCTGCCCCCACATCAAGTAAACAGCTTTCTCAGTGGACCATTT
          CCGCAGCACCTCCGTCCGCTACCCCCCCATTAAGTAACCAGCTTTCCCAGTGAATCATTT
          TAGGGATGGTCCGCGATGCGACCACCATTCACGGATAAGACCTTTAAAACATCTGTGGTG
          TAGGGATGGTCCGTGATGCGACCATCACTCACGGATAAGACCTTTAAAACATCTGTGGTG
          TGACGACCATTCGGGTTGCAACCGGCGGGCAAGGGAAAGGGTTCTATGCCCACGCCTGTA
          TCCTGAGCCTACGGGTTGTAATCAGTGCACAGGTACAAGGGGATTATGGCTGCGTTCGCG

          CGACCAGGGCTTTTTGTACGGGGGTGTGGTCCTGCTTTAT
          GGGCTAAGCTTCTATGTTCTCCGTCGAGGCCTGAAGTCCA
          CGATTGAGATTCTAGACACCCCGCTGTCACTGTAACTTTT
          CGATTGAAATTCTAGACACTTTGCTGTCACTGTAACTTAC
          CAGCCAAGCCCTGTCATCGCCCTGGTTGGACAGTGCGTGC
          TCGACAAGCCCTATCATCGCCCTGGTTGGACAGTGCGTGC
          CGGCCGTGAGTTATCAGATATCAAGTTGGACGAAATACGG
          CGACGGAGATTCATTAAATCTTACACCGGTCGCAAAATGT

