 8 1000
t1        GCCGCTCCTCTACCATGTAGCGTCAATCACTTTCAGAGCCATTGTTCGTTGTTCGTATTC
t2        GCCGCTCCTCTACCATGTAGCGTCAATTACCTTCTGAGCCATTGTTCGTTGTCCGCATTT
t3        GTAGCTAATCTAATAAGTCGTGCCGGCGGTTCCTAAGGCCTTCTACTGCTGCTCTCATTC
t4        GTGGCTCCAGTGTCACGTCGAGCCGGCTGTTTGTTGATATATTAACCGGCAGCCGTAGCG
t5        AGTGCCCTCTCATCGAGCCGTGTCGACGGGTTCCCGTGTCATCCGCTATCGCTTGCACGT
t6        GCGGCTCACCCGTTAGGCAGCGGAGGTAGGTTATCAGATTATATGTTATTAACAAAGGCT
t7        CCAAATAGGTTGTCGTGTCCGGCACATGGTATACCACTCCAACGATTTTAGCACTAGTCT
t8        TCGGATGACCTACTAAGCACGATTCGCGGATCATCGCCACGTTGCTTCCTGTCCGTAGGT

          TTGGTTGTGCCAGGATTACACTATGCGGTCGTAGTGTCCCCCCCTAAATTAATGGTCACA
          TTGGTCGTGCCAGGATTACATTATGCGGTCGTAGTGCCCCCACCTAAATTAATGGTCACA
          CGGAACATGACATGAGCCCCTTTTTAGGATATAATGCCAGCGTTTTGCTACAGCCCTATA
          AACTTTGCGTGGGCCCTGAGGTGTGGGACTATTGAGCTCCCATACAACAACAGGAATAAT
          CGGCGCTCGTTGAGGCTGGCGTTCGGAGGTCGGGCACTCCTATTCGATAAGGGGACCATG
          CCGAGCGTGTTGACCTAAGTGTCTCTTGGTGTGATATTCTGGCTTGATCAGAGGGTTACA
          TTGACAGTGTTGAACTCATAAGACGTTGTATGGGTGCAAAACTATACAAGTGGGGTCTGA
          ATATTGACGTCGAGACGGTGAGACGCCGAGTAGGTGAGAGAAAGTAAAGAAAGGCTCCGA

          CCGAGCGGTTTACATCCCATGTTGCCTAAATTCCTGAGACATCTACCATCAAGGGGCCTA
          TTGAGCGGTATACGTACCATGTTGCTTAAATTCCCGAGACGTCTACCATCAAGAGGCCTA
          TTGAGCATTCCACATACTGTGTTGCGTGTTTTTGAGAAACGCATGAACCTTCCGGATTCA
          CGGGGTCATGCAAGTATTGTCTCGCGCAAATTGAAGCGACGTGGACCGTCCCGAGGAATT
          CCGACGCGAAGGGGTTTGGAGGCTCACCCTGCCCCAAATTTCCGACTGCCAAGAGACTCT
          TCGGGAAGTGACAATATACGGTTGAACACTCTTCAGGGTAGAGACTTGTCAAGGCACTAC
          CGAAGTATTTCACGGATCCTACCTGATACTAACGGGTGGCGTACAATGATGAGCGCACCT
          CTAGACCATCGGGCTCATTCGTGAACTGTTAGTTCATGGCAGCTAATGCTAAGAGGCCGC

          CATCCACGCCCACGGTCCGGCGGTGACACCGGACACAGGGAGGTATATCTCAGATGTGAA
          CATCCAAGCCTACGGTCCGGCGGTGACACCGGAGACAGGAAGGTATATCTCACACGTGAC
          CATGCATATCTCTGGCCTAATCATGGCTCAGGACACGTGATGTCATATCTCACACAGGAT
          TATTTAACCTTAAGGACGGGCAGTGGGTGGAGTATCACGATGTTAAGCTTCGGGTGTGTT
          CGTTCTGCCGCCACACTTGGCAGCAGAAACGAACGAGTAATAATTAATGTTATGTGCAGG
          CATCTCGTACGTGAGCCGCAATACGGGAGGGCGCGCTCCGTACGCCATACCCGGCGCGGT
          TGCAAGCCCCGTTGGCCTACTTAAACAACTGGTAGGTAGATGAGGGAACTTTAGATACTG
          ATTAAGCTCCGGTAGGGGAGAAGCGGCTTAGAGAGGAGGCAGTGAGGTGCTGACACTGGA

          ATGGAGTTCGACGTTTTAGTCCCAAGGGTGAATAGCGTTGTCTCATTGTTGTGGAAACGA
          ATGGAATTCGACGTCTTACTCTTACGGGTGGATAGGGTAGTCTCGTTGTTGTGGAAACGA
          CGGGTACTATACCCCCCACCCCGATATGTGACAAGCGAAGTTTGGTTACGAAAGAGACGC
          TAAAAGCCATGGAGTGTCCTCCATCGCACCATCAGTGCGGCGTGGTGACTTCCGGTATCC
          TTGAACGTTTTTGCCAAAGGCGCATGAAAGGTCGACGGAAACAGAAAGGGGTCGTAGCTT
          AATAATCTAAATGGACAAATTGCTTGCGCCATTAGTACGGCATGAAGGCTGTAGAATCAA
          TTTAGCGAATGCGTACAATATCGACGAGCGTGGAGTACTGTTTACTTATTATAAAGAACT
          CTTCTGATCCATTCACAGCCCTAAGGTGTGTGTTGCTCTACCCAGTTGCAATCGGGCCGG

          CTCATAAGGATTAAGACAGCAAGAGAGGTTTCAACCATGTCAGCATAACTTCCCAGTAAG
          CTCGTAAGGATTGAGACAGCAAGAGAGGTTTTAATCATGTCAGCATAATTCCCCAGCGAG
          CTCGTAAGGATAACGACCACACGCCTAGTCTTTTAGGCTTTCGCATAATTTCCCGGAGAT
          CTCACACTGGATATGGCAGCGAGCCCAATACCTCTGTCTTGAGGATTCATTGGCCGGGTC
          GCAGTACTAACTAATAAGGGATGTAGAAACATAGAGTTTTTTGTGTGCTCACTTACAACC
          CATGCATGAAGCTATGCGGCCATGGACACTCCACCGAACTTCCGGCTCCACCTCTCCGTC
          TGCGGTTCAATTGTAGTAACGTGTGTATCAGCCCCACTACGCGTCCAACTTGCCTACTTT
          CATGCTTCAGCGAACGCGGCATACAGAGCTTCCTCAGGATATGCAGTTTTCCCTCGTATT

          CTCCCGTATTGATCTCGTACTACCGCAGCCCAGTTGACTCGGCTGACATATCGCTGCGAA
          CTCCCGTATTTACCCCGTACTACCGCAGCCCAGCCCACTCGGCTGACATATCGTTGCGAA
          CATTCGCATTTTCCTATTACTGCCGTTGCCCGGTTAACGCGGCAGATGATTCTAGTCTAC
          CTATTACGCTCCGTCAATATAGTTCCAGCGGTGCAAATGCGACTGATGCCGAGACCCCAT
          CCTCAGTGGCTAATAAACGCATACAGTGTTCCGTCAGTGGGCCCGATACATTAAACATGT
          ATCTTGTGCTCAGCCAAATCTGCCCCGGGGACGTTGATGAAGGTAACACTTTTGTTTCGG
          TTCTTTTGTAATTGCTCTCAAAATGCTACATCGCTAACGAGACCGGCGACTAGGAATGAG
          ACCTCTTACCACTTCCACGGGATTGTGACGCTATGCACGTGTTTCGTCCTTGGGTGAAGA

          GGCGGCACCACCGATATAAATGTTAGGCACGTCGTATTGTCGAACCCGGGGTCCTAAGTA
          GGCGGCACCCCTGGTAAAAATGTTAGGCATGTCGTATTGTCGAACCCGGGGTCCTAAGTA
          CCCGGCACCGCTAGTCCGAATGTTAAGAACCCCGCATTGTCGAGCCCCAGGACCCAAGCA
          GTCGGAGCTTCCGGCTCAGGCGCCTCCTCCCAAACACTGATAGATTATGTGGGCTAACAA
          GTCGGGACATTATACATAAAAGATAGACTGCGTTAGCCGGATCACACGTGGGCTTAGCGA
          AGGAACATCACTGGCTCGAAAACTAGCCTCTCCTAGATAGTAGAGGTGCGGGCTCAATGA
          GTTGGAGACACCTGTCCAACTAGCCTCGCGTAGAAGCTAGAGCGCAAGGAAAATTCGTGC
          AACCGATGCGCTTGTGCGAACGTCTTCAGCCACAGACCCATGGATAGCGGGCCTTTGAAA

          TCGGCGACCCCGACTATCCCTGGCACGTAGTGAGACTCTGAGGTCTTTAGGTTGCATTTA
          TCGGCGACCCTGACTATCCATGGGACGTAGTGAGACTCTGAAGTCTCTAGGTTGCATTTA
          CCCGCGAGCGTGAATCTTCATCACAAACAGTGTGTCTCTGCGGCTTCCCGGTTGTCTATA
          GACTAGAACGTGCACATTCGTGGTGCGCAACAGGATCCCAGGTCTACGCGGTCGTCAGTA
          ACAGGGAGTAAGAACAGACGTGGTGCGCACGTGGACCGTAAGGGTTAGTGGGAGTAGGCC
          CTTCTGGGCGCCGCCAGGCGTGACGCACTATGCATTTTCATGGGCAAACGGCTACCTGTT
          ATTCGAACCCTAAGTAGTCACGAAGTTCAATCGTGCCTCGCCGATATGAAAGGGTGTTAG
          ATACGCAACGCGCACGGCCTGCTGGAACGATAGGGTGCTGTTGGCATGAGGAGAGCTTCA

          CCCATGTGGTCTCGACCACGCCTATGATAGCAGTTATTTGGGTGTCGCGCGCAGTATCTT
          CCCATGTGGTCTCGACCACGCCTATGTTAGCAGTTATTTGCGTGTAACGCGCAGTATCTT
          AGCACGTAGATCCGGGCGTTATCATGGTAGTTGTTATACAGGCGTAGCGCGCGGCACCTC
          GAAAGGTGATTCTGCGCGACGCAACGGTATCCGCAACCTCCGCATCTCGCACGACGCCGA
          CTGGGGGTATCCAAAACGCCTTCTCGATTGTGTTTGTCTCCAGAGTCGACAAGCTATCCA
          CACGGGAGACCTTCGACGCGGTAATCGCCCCAGTTACAGTTGTGGCTCAAAGGGCAGCTT
          TTAAAGGGGTCCTGCGGGGCGTCGGGGTATCTGCGCATGTCTAACTCCGCAGAGCAGACT
          TCCATGGAACCGCTTGGGACGTTGGAGGATCAACGCAACACTGTTTATAGAAACCAAAGT

          GTGTCGGGATCACCTCGTTCATACTGAGCGTCTAATGTTGCACGACTCATCTAGACGGAT
          GTGTCGGGCTCACCTCGTTCATACTGAGGGCCTAATGTTGTACGACCAACCTAGACGTAT
          ATGTCGGGCTCAGTCAGTCTATCCCAGGTGCCAAAGTCTCCGTTTCTCCTCCCGGTGGGG
          CTGGAAGGTGTTCACAGACACCCGCCTGGGATGAATCTTCCAAATTTCCCCAGGGTAGGT
          ACAGTAGACTTGGCTGCTCTATATTCTTTGAGGTTTCTTGTAGTTATCGCCATGTAGGAA
          ATGCCGCAATCAGCCACCGTCGGTTATCTATCGCCAATTGCGATCTGTTCGTGAACCAGT
          TTTTAGGACGCGTCTAGCACCAAATCCGGGCTGATATCGGAGCCTCGATTAATGCATAGA
          CCCTAGGATATCCCAGCTACCAAAACTAAATAACGATCCGCAGTTTGTCACATAGGATGT

          GGCGACTTCAAGCTAGGTTTACGGCGTAACTGTGAGGCAGGCAGACAGGCGCCTCTTGTA
          GGCGACTTCTGGCTAGGTTTACGGCGTAACTGTGAGGCAGGCAGACAGGCGCCTCTCGTA
          GAGGAGGCTTAACAAAATTGGAGGCGTAAATAGGAGATGCGCATCCGGGAGCGCCCCGTA
          GGCATCTTCAGCTATGGTTTGCACCGTTACTACGAGGTAGGCATCTAGGAGTGGCGTCTA
          CAGAAGTTTCAATTGTGGCTATAATCACACTGCACCCTACCGAACTTTTCGCCCATGAAC
          GAAGAGTCTCAACCAAATTCGCACTTTATTTGTTCGGTCTGTAAGGCAAAACTCTTAGAC
          CAAAGGACTGGGTTCAGTCCCCACCGGACCCGCGCGACATACAGTTTCGTACGGTCGGTC
          AAAACAACTACATTAACCCTCCAATAAGACCATGCAGCAAGCAGCTATGTATGTCAAATT

          GAAGCTCACACCCCTACTCTACCATACCAAGGTGAGGGCGACCATACCACAATCAATGCA
          TGAGCTCACTCCCCTACCCTTCTATACCAAGGTGGGGGCGACTATACCACAATCAATACA
          GGAGACTCCTCCCCTATCTCTTAAGCAGGAGGAGGGGGGGGCCATTCCATGATGGACACC
          GATATTCGCCTTCGCAGGTAGGTACCTGCTGGGCAAGGGCAGCATTCGGCACACGGAAAT
          ACAGCCCGTACTTCGTGAGTTACATATGCTGTGCGGGGCGGTTCCTCTATGATGGGGATG
          TAAGATTATACCTTCTTCTGTCAGACTCCCGGGCGAGGAGACTATGCCAAGAATAATACC
          GGCACACAAGTCTTGGGTACTTTACCAGTCATACGGCAGGGGTGACATGACAACGAGGCA
          GGCGTATACGCCTGTTGCGCACTGTGCGCCAGATGGGGGAGCCAACTCCGGAAAGGGACA

          TCATTGCACGTCTGAATGACAAAGCACGCGGACCCAGGAGGGACGACTGACTGCAAGAAA
          TGATTGCACGTCCGAATGACACAGCACGCGGACCCAAAAGGGACGACTGACTGAAAGAAA
          CGCTCGCCCGGCCGATTGAATTAGTTCGTGGCGTCAGAAAGAACAAGCGAACGTTAGAAA
          ACCAAACGTAGATCAGTGGATTAAGTTGAGGGTTTAGGGGCCACGCTCAAGGGAGGTAGA
          CGCCCTTGTCGTCGGCGGATTAGGGCTATGAATAGAGGAGTACGATACGAAACCGCTAAC
          CGACAGCGTATCCGGGTGATTCGTGAAAGAAGTCCTCCAGGCACATGAGAGTTGGTAGAC
          CGCGGCCTCGGATGGACAACCCGGTCTGAGAAGGTAAGTGCCGCGTAAAGAATAGTCAAA
          CGCTGGCGCGGCCGACATATCTCGGCGTTAAGAGCAGGCGTCGCGCATTAGCCGCATCAG

          GCTCTTTCGGGCCGGAGACGTGGTTCTGCAGCTCAACTTGGCCATCCAAGGTCCCCACGA
          GCTTTTTCGGGTCGGAGACGTGGTTCTGCAGCTCAACTTGGCTACCACAGGTCCCTACGA
          GCCTCTTCTAAACTGTACTAAGGCCTCACGCCTCAACCCGGCCTCCCGCCTCATTCATAG
          CCCCTTTTGACTCGAAGAGGTCCGCCAACGACCCGGTTCGCTATCTAGTTTGATTTCCGG
          CCTCCTTTGGCCCATATATGAGTAAGCTAGGACCTTCCAGCGCTCCTCGCGCACACATGA
          CTCTTATAGCCTCAAAAATTAGGAGTTACGGTCCGAAAATGCGCTTACTCAATACCAATC
          ATCTTTAGGCTTTAAGGTCGCACGTGCAACAATTCGCATTACATTCAATTGCCTTTAAGG
          ATATCATGGACATTGTGATACGGGCTCGAGTACTTATACAAAGCCCCGTACTCTGCTAGG

          GACGTCTTAACCGGAGCCCCGGTGACAAGGAGGTCTTCATAGCCTAAGGAATGCATTAAA
          GACGTCTCAACCGGAGGCCCGGTGACAAGGAGGTCTTCACAGCCTAAGGAATGCATTTAA
          GCAACTTTGATTGGGGTACTGGTCTCGATTAGGTAGACGCTGCTCAAGGACTCGACCGGG
          GGTATGCCGACTAGAGACCGAACCCCAGCCCGATCCATGATAAATAACCTGTGTATTGCG
          AACGTATTGGATGGAGCGCATCGTTTTAAAGGCTATTTGATAGACTCGAGGGGAGTCGAG
          AGTGATATCACCAGAAGTTTTCCCCCGGGCGGCTGACCGCGAGTTGGGGCGAGCGTAGAA
          ATTGCTTATTACAGTCGATTTACGCTAAATGTCCTTCTACATGTTGGGGATAAAAGTAAT
          TGCACCCTCCATGGTGGACTCCCTCGAACCATTTATCCAAGAATTGAAGGAAATTTTTCA

          AATGGTTGCGTTTATACTCGGCTAATCTGGCGACGCCCTC
          AATGGTTGCGTTAATACCCGGCTAATCTGGGGACGTCTTC
          GACAATTGCATTCGACGCTTGTAAATTAGATGTTGCTCAC
          GCTTTAGGTGTTGGCATCCTATGAACCAAGTAACACTCGC
          GACAACCAGTTTAGTGCACGGTTTGACTAGACTTTACCAA
          GGTTATTAAACGAAGGGCCGGCGTGCTTATCATACTCCGC
          GATTAGAACATTGGCATCTTGTATTCTGAGAGGAACTTAC
          GGACAAGAAACGCGCAGAGGGTACTTCGGGTTTACACCTC

