 8 1000
t1        CGTATAAATGTACGATTGCCAGGTAGGTCGTACCCAGCCGTCCGCACATGTCATAAGACC
t2        CGCATGTGCGAACGGTCTCTAAATGGGCCGTACTTAGTTGCACGCCCGCGGCAATGTGAT
t3        ATTACGATCGAATGATCGAGCAATAAACCAGGCACAGCCTAGCAAATATAGTGAGCTGCA
t4        CTCATGCTTGAACGGTCGGACCGTGCACTAGACACAGACTAATGAACGCAGTGACCCACC
t5        TACACAAATAGCCCGTTACCCCTGTAAAATAAGGCAAGTCGATTGCTAACGCAACGTGAC
t6        TGCACATATATTCAATCATTTCTATAGAATTGCGTAGGTTGACTGAAAATATAACGGAAC
t7        AGTGCGTGTGACCGGCCATCGATACTTTATCATGCGGGTCCACTGGCAAGGCTGCATGAA
t8        AGTGCGCGTGACCGGCCATAGATACTTTATTATGCAGGCCCACTGGAAAGGTTAAATGGA

          CCCACAATCATAGACTATCACCAGGGGGACGCTAAGCGTACTCATGAACGATTCATTAAT
          TATACGATTCTTTATTGCTTGGAGGAGGGTGAAAGGTGGGGACTTGTACGTTTCATCTGC
          CCAGCGTTCTTCCTCCGTCGCTGGGCGGTTTCCAAGGGGCTGCGTGTGATCTCTAAGCAA
          CCAATGAGCAGCCATTGCCGCCGGGGGATTTTTAAAAGGTTGCATGTGATTTTAAACCAA
          ACAGCCTATGTCCACCGAGACCGGGACGATGAAAGGGTATCGGCAGGGCTATCAAAGGAG
          ACTATATATGTCCCCAAACTCATGGGTGATGCATGGTTATTCTCAGGATGATCAAATGAG
          TACATCAACCCCCAGCGGAACGAAGGCGATGAGTGGCTCTTACGAGTAGACACCATTGTT
          TATATCAACCTTAAGCGGAGTAAAAGCGATGAGAGGTCTTTACGAGCAGACACCATTGTT

          TGTAACAAGTTAGTAGGATCTGCTAAACTGACCTCGCACCTCAGTGGCTCAGCTGGCTAA
          TTCGCGAGACCAGCGAGTTCACGCGAGTCACGCTCGCATTCAGGTATCCCAGCTGGATAA
          CTGTACTTGACGGTATAAGAACTTCAGGTATTGCGTCATGCTGGAGTCACAGTTGGCCAG
          TTACATCTGTAGATAAGAGACTTTAAAATCCCGCAACTCGCTTGTACATTAGATGGCCAG
          CATCAGAGAAAAGCAAGTCTTGAACGGGTCTCCCCGTGTCGCTGAAACTGGATCGTACGC
          AACCCAAGTAAAGCAGGTCGTGTGCCCGCCCTCTTGTACGGTCGAAATTAGAGAGCGCAT
          TAAATTAAAGAGGAGACCCATGGGCTTTGCCGCCAAAACATCGGAGTTTGAATTCCAAGG
          AAAATTAAAGAGGGGAGCCATGGGCTTTGTCTCCAGAACATAGGAGTTTGAATTCTAAGG

          CCAGATCAAAGGTTTGCGGGGCGCGCAAGTGGAGATATGGTAGAATGCCCTCAGCCGAGT
          CTAAGCAGGAAGTCTCCGGGAAGTGTTATTCGAATCTTGTTCGGTTGTCGTCGGCATTGT
          CCGCCTAGAGAGTCCGCCACCCGTGTGTTTTTCCTAACTTCAGGTTGTCGGGAGTAGTAA
          TCCGCCAGGGAGGCGCCCGCACGCGCGTACTTTTTATTGATAAGTTGTTAGGAGTTGTAA
          GTTCGCCGCGAAATCAAGATGAATGTGCGTCACACGGCCATAGCCCGTCTCTGGTAGTCA
          CCTCGTTAAGAGGCGTCAATGCATGTGCAATGGTCGTTGATAGGCTGTTTTTAGTGATCG
          TCCCCTTATCAAGTAGTTCTTCAGTTATAAGACAAATATATCGTCCGGGCCCAGCTGCAT
          TTCTCTTATTAAGTAGTTCTTCAGCTATGAGACAAACATATCGGCCGCGCCGAGCCGCAT

          GGGAGTAATATAATGAGGCAAGGCCCTCCCAGCGGTTTGGTCATTGCATATGCAACTGCA
          AGAATCGATCTGGGGTACCAAAGATTTCGGGTAGGCTTGATCATCTCAATAGCGTGTACA
          ATTAAATAATCTGGGATTTTGGTACCTCAGAAGTGTCGCCCTATTTCTTCTAAATTTATG
          ATCAATGAGTGTGGGACCGCACTATTTCACGAGAGCCGCCCTATTTTCTTTATATACATG
          AGCCGTGCCCTGAGGGTCTTAGAGAGCTCTGTCAATACGGGACTCACGATCTAACGCCTA
          CCCGGTGCTCTTAAGGCCCCGGGGAGCATCGTCACCACCGGGCTAACGGTCCAAATCTTT
          ACAGCACGCGTTGGCTGAGCGACGAGCTGCGTTCGGTGAATGCTGACGGGTGTGGTTCTG
          ACAGCACGCGTTGGCTGCGTGACAAGGTAAATTCGGTGAATGTTGACGGGTGCAGTGCTG

          GGTTCTTTACCTCCGGAATGGGTAGGATCCTCTGATCGCGTGTAGCTGTTCCCACCTAGA
          GGTACCCCACCTCTTGGCCAAAGGGGCTTCAGAGATCGTTCGTAGCCGTTCGCGTATAGA
          ATGTGGCTGAATGGCAACGGGAGGAGTCTGGGCATTTACTGGCTATTGTTATTGTCTTAC
          ATATCATCAAATCGTGATGGGCGGTGTTTGAACGGTCGCCGACTACTGTTATTCTCGTAT
          GTTTATCGCCCAGGGGAAGGAGTGGCTGTGACTAGCCGACGGTTATAAATACTCTTTAGA
          ACTCCTCGCCTAGAAGGAAGGGCGGCTTTGATCAACCGTCGGTCACAATTACTTTTACGG
          GATTCCTGACAGAGGACGATAGGAGTTTTTACTAGTCGGTAGTAACTATCTTAACAGAGG
          GATTCCTGGCAGAGAATAATAGGCATTTTTACTAGCCGATAGCAGCTATTCTAATAGAGG

          AAGGCCCTATACGGGTCCGTTGTTTGGCACTATACCTAGGTCCGCGCAAGCTGTTCCACA
          TTGCCTGTAACCGAGCTTGTTGTACGGATACAGCTTCGTGCGCACTAAAGATGTACTAGA
          TTGTTAAACAACAAGCATGCCTCCTTATATAACTCCCAGATGTACACGTGTCGGGTTATA
          TAGTCGATCGTGAGTCTTGCCTCGCTCTCTGGCTTCCAGAAGGACACGGGCCGGGCCATA
          ATATTGACACAAGAGTACATCGTGTCCCTAAATCCCCAGCCGTGATTCGGGCACACTATC
          AGATTTGCACACGGGCAGATCGTGTTCCTCGATCTTCAGATCTGACTCAGAAATTCAATT
          CTGATCAAGCACGAATGTATTCCGTCGCTTAATTTCTAGGCAAAACTTGGAAGTTTTATA
          TTGTTTAGGCACGAGTATATTCAGTCACTTAATTTCCAGCCAAGACTCGGCAGTTTTATA

          ACGCACCAAATGCGACACTCCGGCGTTAATTTCACGCTATGCGATGACTGTATTCGGTGC
          TAGCCCCTCATTCACTACCCGAGTCCTCTCTCCGGGTACGGCAACGTCTGCGCTTGAGGT
          GACCGTCGTCTCCAGTAGGTAGGCCTTCTCTCTCTGTCGATGCACGGCCAAATCAAAGCT
          GACGGTCGACACCAACAGGCAGGCCTACACTCCTGGACGATCCACGCCTGTATTTTAGTT
          ATGTACCGTTCTCGCCACCGAAGCCTTCTGCACTCCTTAACCAGACCAGGTACAGGTTTG
          ACGTGCCGTTCTCGCTGCCTGAGCCACTTCCGCTCCCTAAACAGTCCCGGAGTGGGTTTG
          ACGTGATGTCTTCAGTTATAAAGGCATGTTTGTTGCTGGGTTCGCTCATGTAGGGGCCTA
          ACGAGTTGTCTTTAGTTCTTAAGGAATGTTTGTTGCTGGGGTCGCTTATGTAGGGGCATA

          ATAACAGACCGTCTGCCGGCAACGTAAATAGCTGTCAAGTACACTTTCCCTCAGATTTGT
          ATACCTGAAGGATTGATGTTAGTGTTTAAGTCCCGCAAGTTGCCCCCTACCGGGATTTAT
          TCCACAATTAGACTTTAGCCAGAGAGGCAACGTAGCGGGGGGGTCGCAACTAGGTACTCT
          TTTACGGCTAGAGATTAGTCAAGTCAGCACGACTGAGGGGAGGCTCCAACTAGGTACTTC
          ACGGAAAGTGACAATTAACCCATGTGCAACTTTTATAATAGAGCAACTATCTGAAGCCAA
          CCGATGGGTGAATAGTAGCTTAAGTGCCACTTTTATAACACATAACCCACCTGAAGCCAA
          GTAAGGTGGGACTCATAGTTAACGAGAGAATATGCATAGGAGCATCTGACTGGCGATTGT
          GTTAGGTGGGGTTCATAGTTAACGAGAGAATATGTACAAGAGCACCGGACCAGTGATTGT

          ATGTTATAATCACGAAGTACAATCGACGGGTAATGAGGACAAACTTCAGAAGCTGACGAA
          CTGCCACAGACACAGCGTCCGGACGACATGCAGCGAAGCCAACCTCAAGAGGACGACGTG
          ATCTGAAAATAGACAAGCCTAGTCGGATAGCCAAGTTGTCGACCAGTGAGAGCCTGATTT
          CTTTGGAACTAACGGGGCCTAGACGGGCGATCAGGTGGTCGAACTGTCAATGTTCGACAT
          CTGTGCATGCAATAGAGTCCACCCACCATGAAGCACAGGCGTGCTGCATGGCGGGCTCTC
          TTGTACATGCTACAGCGTCCACCTGCTTCGGAAAACGGGCGGGCTGCATGCACTGCTAGC
          TCATTAATGCCCTAGAGACTCCGTGTCGAGAATCAAGGACGAACCGCAGCATGAGTCTCC
          TTATTAATGCCCTAGGGATTCCGCGTCGAAGATCAAGGTCGAGTCGCAACATGAGTCTCG

          TCCTAATAATGCGTTTACCACTTCGCACCGTGTTGAAGACTTCCTTGGTGGCAGTGGTAC
          TTCGAGTTTCGCCCCTACGTTTTCGCTGTATATTTAGGAGACCCTTACTCTTAGTAGTAG
          CTCTGACGTTTCTTCCAAGGGTAAGCGGGGCAGGGAGGAACCCCTCGTCGACAATAGAAG
          AACTAATGGTGCTTCAAAGGTTACGCGGAGCAGAGGGGTAGCTCACGCCCACATGGGGAG
          CATCTATGGTGCATCACCCGTCACAGGTAATTTAAGGGGTCTGGCAACTCGCGCAGGGAA
          TATTTACGACGCATCACACGGCACGTAATATTTATCGGACCCGGCAACTTGTGCTCGGCA
          CTCTTATTAGGCGATCTGGCTCATATGGAAATTGTGGATTAAGATGGTGTGTACCTTGAA
          CCTTTACTCGGCAATCTTGCTCACATGGAAATTGTGAATCACGATAGTGTATGCCATGAA

          TCGACGTTGCCATATGCGACGGGCTACCGTCCGTGCCTCGTGCCAATGTCAAGGAGGGTC
          CCGGCATTCTTATAGACTACAGTCAATCGCCCAAGCCGTGGTTCAATGAGCAGAAGGCCT
          ATTGAGCTTCTAACGTTCAGCCACAGCGTCGTGGTAGTCATTGCCTTGACAGAGCAGTCA
          TCTGCATCTCCAACCATCTTTTCCAGCGTTGCCACACTTATTGCCTTGACAAAGCAGCCT
          ATCGCTTAGCAACGATCTGCTGTTGACAACTCTGTTGTTGGATCATCGACTGGCCTCCCA
          ATCGCCTATAAGCGATTCCACGTTAACGATTCTGTCCTAGCATCACCGATTGGCCGGCTC
          CTCGACTATCAATGGATTCTAGTAGACAATGTTTCCGCTGGAGTGATGATAAAGCCGAGC
          CTAGACTATCAAAGAATTCTAGAAGACAATGTTTCCGTTAGATTGATGATAAAGCTGAGC

          GTTGAGCGGATGACACCCAATGTAAAAAGGCGAGGGCGGGTCATGTACGCACAAACGAAG
          ATCGAGCAAATAGTACCTAAGTCAACAAGCCGCAGACTGGCTATGTACCCCTAACCAAGA
          TATACGTCTAGTTATGCAGAACAGAGTCTATGGATTTACGCCATCCCCCCTTTATACCAC
          TACCAGCTTAGGATGGTAGAATAGAGCCCATGGGTTTACGTGACACGCTCTTAGCTCCTT
          ACAAAGCCCCATCTGACAGATCTAGGTGCGACGGTTCTTTGTAGGTGGTCCTCATCTAAG
          ACAGTAATCGTTCTGGCCGAGCTAGGTCTGATGGCACTTCATAGGTGATCCTCATTTATA
          GCCGCTCACCCCCATTCGTGGTCGAGCCCGAAAATCAGGATTATGCGTTCATCTTCATGA
          GTCGCTCACCCCCATCCTGAGTCGGGTTCAAAAGTCAGGATTAAGCGTTCATCCTTATGA

          TTGAGAAACAACAGCACCGGCCGGGATCGACCGGATATCCTGAGGACTGTATATGTGACA
          GCCAGCGACAACGGCCCAATCGAGCCGCAGCCGGCTCCACTGTGAAATATGTATATTGCA
          CGATCAACTAAAAACCCGTCCAGGACTCTCTTCAGCCAAGTACGCGCTGTATAGTGCAGG
          TAATGCATTAAAAACTCGTCCATGGTCACCTTAGACCACGTATGTGCTTTATATAGCAGG
          GAAACCGTTTAGAGCTTACTTGGGATTTCAGTGTACGTGTGCGAGGCTAAGAATTCTAGG
          AAAAGCCGCTGGCGCCCTTATGGGTTTGCAGTGTGCTTATTGTACGTAAAGGATTACAGG
          CCAAACAGTGCATGCCCACCCCAAATTGCAACCTGCGCACTGAGCGTCAAGTATCATGAG
          TCAAGCAGTGGAAGCCCATCCCAAATCACAGCGTGCCCACTGAGCGCAATGTATCTTGCG

          ACGCTAGTACTGGATCCTCGGTTGCAAAGCCGACTCTTAGGGTATTCTATTCGCCTGAGT
          ACTTCTAAGCTAGATGTTTGAAAGCATGCGCAGGACACGTCTCATCCACGCCGTGCGAGA
          TACAATGGGAGAATTCCCTATCCTTAATGGTATCATTCTATGACCGCGTCATGCACTAGA
          TGCGATGGTGAGAGTCCCCACTCTCGGTGGTGTCACACTATGATTGCGTCATGCGTTAGG
          TCGACGGAGCCTGTGTTGCCAATTGGCGGGTCCGTAACTGTGTCGGCAAACAGAGAGAAG
          CCGAAGGAACTTATGTTTCCGATCGACGAGTCCACCCTAGCGCCGGCAGAATGAGGGAAG
          GGGCCGAAGTCTACGTCATCGCAGGATGGGCCCCGACCCCCAACAGATCTAAGCGGTTAT
          GGGCCGAAGTCCACGTCAACGTAGGATGGGCCTCGACCCCCAACAGATTTAGGCGGTTAT

          GTGGCATTGTAGTGGGCGGACCGGCTTGGTGGCGCCCGCGTGTATATCTCACCGATCATA
          GTATCAGGCTAATGTGGGCTGCAAGTTAGAGAGCCCTACGTACTTACCGCAGCGGACTCC
          CTGCTGCATGGACGGATCACCTATCTCGACGCAGTTATTAGTTCAGACTCAAGAATCACT
          GTACAGCATCAGCAGTCCGCTTCTCCAGGCGAGGTTTCTAGCCCTGACCCGGGAGTTACC
          GCACTAGGATAGTAGAATAATTCGTTTACATATGCTAAAGGCATTAACGCGGAAGATTTC
          GTGCTGGGGTGCTACTATTGCCTAGTTACAACAGCTAAACATAATGGCGCTGAAGATCTA
          CCATGGTGGCTGTGCGACCATCCGACCGGAATGGTCTCGAGCACCGAACCTACAGGTTTT
          CCATTGTGGCTGTGCAATCATCCGTCCGGAATGGCCTAGAGCACCGAACCTACAGGTTTC

          AGCATCAAGATGATTAAGGAGGGTTCATACACCCGCCTAT
          AGCATCTAGGCGATTAGGATTGCCACATTCATTTCGCTGG
          AGATACCGTTGTAGACAAACCGACGAGCATACACGAATGA
          TGATCGTGCGAGAGACAAACTGATGGGCTTAAACGAATGA
          GGGCTTTACATAATAAATGACGAGCTCGCGCTAGGATAAC
          GGGGTTCGTATAATTATTGGCGAGTACGGTTTAGAAGGAC
          GGGATCCGGACGTCGATCGGTGCGCCGGTTTGACCCGGAG
          GGAACCCGGCCGTTGACTGGCGAGCCGGTTTCACCCGGAA

