 8 1000
t1        TCTGGCCCACGCGCCTGTAGCCGACAACTCCAAGTTAATCGTGGGTAGAACCATCCTGTC
t2        TATGATCTACGTGCTTGTGACCGATAACTACAAGTCAATAGTGGATAGAACTATGCTGTC
t3        TGCTCCTGGAGCGCTACATGAGCATTGTTCTTCAGAGAAGACACACGCCAGTAAGCTTTT
t4        TGCTGTGGCACTGGTTAGTGAAAATAGCTCCTCAATAATAACCGATGAAAGACCGATGTT
t5        TCTCCCCCTGAAGGTATATGGGGCCATCACGTGTATTGTGGTGGGACGGTGTGTAATGTC
t6        TAGGCCCTCGATCTTATATTGGGATATCGCATGCACTGTGGTGGACCGGTGCGTGATGTT
t7        CAGTCCGTCCACGCCATCGGTTTAGGCTATGTGGCTAGCAGCACGACGGTGAATAACGAA
t8        TAGCTTGGCAATGTTATGCGCCGGGATGACGTAGCGTACGATGGATTGGTGCGCCTTGGT

          GCCATCCCTACAGAAGCTGCTATACACATTCATACAACATTGAGCTGTGGCTGCAGCTAT
          GTCATCCCTACGGAAGCGATCATACGCAATCGTACAACATTGAGCTGTGGTTGCTGCTAT
          TAACTCATCTCTGTTCTCGGTAATTGCATTCCTACCTACCTGGTTTGGGTTTCGCCCAAG
          TAACTCACCTTTGCATTCGGCAATCACGTTTACACCACCCCGATTCGGGTCTTGTTTTAG
          CGAGCTGAATCCAACGTGGGCCGATGCCTACAACTATGCTAGCATTGGACCCAATTTCGT
          CAAGCCGAGTCCAATGTGGGCCGGCGCTTACAACCATGCTAGCATTGGACCGAACCTGGT
          AGGTTGGTCCGTACCGATGATAGACACACTTACCGCACACAAGCACTAGTTGATACACAT
          TGCTTTTTCATCACTCGTGGCAAGTATGTCTGCCCCTCACAGATTCGGTCCGATCGCCGT

          AATGAATATCCCGCAGATACGATTCAGAGGACTGTATGAGAACGTAAATTTCGTCGGTGG
          AGTCAACATCCCGCACATAAGACTTAGAGGACTGTATGAGGACGTCAACTTTGTCGGTGG
          ATCTTGGATCCAAGTTTGAAAGATCTCTGGAATTTGTGAAGGCGGGGATCCTTTTGGTGC
          ACTTCGGATCCTAGATAGAAGAATCATTGGTGCGCGTGATGTTGGAGACCCTGCTGGCGC
          ACCCGGGATTTCTGTGCTCGAGGCTATTGGCACTATACCTGATGCAACATGAACCGGGTC
          CGTTGAGTTTTCCGTGCTGGAGGAGATTAGTACTATACTTGAAGCCGCATTGACCGGGTC
          GACTAAGGTTCTCGCGCGTAAGGCAACTCGGACAAACCTCGATCTCGATGTCTCCGGGGC
          AAATAAAGTTTCCGTGCAGGAGGCGATCCTCATCAATTCAGCTATAGGCACTCCCAGGAT

          GAGAGATTCGCCGCTTTCTTGCAAGGGTCACATTGGGAGCTGTAAACGGTTACATATGTT
          GAGAGATTCTCCGCTTTCTTACAAGGGCCCCACTGGGAGTTGCATACGATTTCATATGCT
          GATTGATTGACCATGCTTCCGCAAAGGTGTAATCAATAGTTGCGGAGGGTTGCGTCAACC
          GACTGATAGACCATAGCTTCGGTAGGGCGCTATCCTCGGTCTTGGAGGATTGGGTCATTC
          ATCAGGCCGACCGCGTTTTGCTAGGACAATCTAGCACAGGCGAGAAGCAACCTAAATGTT
          ATAAGGCCCATCGCGCTTTGTTCGGACAATTCAGCATAGGAGAGATGTAACATACATGTT
          CCCTTTGCGGTTACAGCCATCCAGCATCACCTTACCCTGCCGCGACGAGATGGGGCTGCT
          GACAGGCTGGTTACATTCAATGTGTGACACCACGCCCCAACGCGCCGTAACCGGGTCCCC

          ACTAGGAGGCGGGTGATCCTATAAGGCACGTCGATAGACTCCGTATACTCGCGAGCGCTC
          GCTAGGAGGAGAATGATCTTAATAGGCACGTCGATACACTTTGCATGCTCACGATGGCTC
          AGTAGTAACACCACGAACTCATGGTGCTCAGTACTAAACCTCCCAAATCATCAGCCGCAT
          AGCACCAATTCCGTGTACCAGTAGTGATCCTAAATAGACTTTTTGAATAACCGGTCGCGC
          GGGAACAACCGCGTGACTCTACGAGGCCTCAGTCACTAGCCACAGGATGCACACAGACCA
          GGCGGCAACCCTATGTCTTTACGAGGCCTCACCCACTAGCCATAGAACGCATTCAAACCA
          CGTAGATAGCCTCAGTTACATCCAGTTCTGGTAAGTTACCTTCGTGAACTAGACGGGCAA
          AGCAGTCATCTTGTGTCTTAGTGAGGCCCACTCCTCTTCTCGTGAGACAGACTTAAATAA

          AATCCCGTTCCGGTTAGACAGCGCACCGGAAAACTGCACACAGTCATTCCACTGGAGAGT
          AATCCCGTTTCGATTAGACAGCGCATCGACAAACTGCACACAGTCACTTCACTTGAGCTC
          TATTCTGCTCTGGTGTCTGGCCACGTCATCGAGGTCGATACATAAATGTCGCAAGCCGCG
          AACTCCGCTTCGGCATACTATTATGTACTAGAACCCACTTAATAAACGTCACATGTCGCC
          GATTTCACATCGGTCGGGGCGCATACCGGAACGTCAGACATGTCCTCGCCGACGCTCGAT
          GATTTTACGTCGGCGCGGGCGCGTACCGGAACGTCAGGCATGTCTTCACTGACACCTGAT
          TACTCTCGACTGGCTTGCCCTCTTGTCATCAGGATGCACCGATTGTCGCTGGTAGTAGTT
          GGCCTTCCGTTAAGATGATTACACACCCTTAAGGCGCGTCCGGCTTTGCCGACAACAGGC

          ACCTTCCAAGCACCGACATAAACGCGCGGGACCGGCCAGTTACAAGATGAACACCTATTC
          ACCTACCGGGCACCGACACTAACGCGCGGGTCCGGCCAGCACCTAGTCGAACATCTGTTC
          ATGCCTAAAGCGACATTCCAGTCACGAAGGCCCGGTCGCTCATCGGGTAGGGATCTCTAC
          AAGCTTCACACACCCACTTGGACACGGTCAATTGATTTCAAACGGGTCGGGGATCTCTAT
          GAGCTATTTTGTACGACACTTCCAAAATTGTAAAGTCCGGATTAGACTTGGTGGTAATTA
          GAGCTATCTTGTACGACACTTCCCAAACGGCAAAGTTCGGACTAGGTTGGATAGTAGCCA
          CTCCCTTGCGGTTCAACACTGTCAAGCTCAACCGTCTTATAATGATTTTGGCGCCGACTT
          CTTCCGTACATATCGGTACTGCCATGCTCCTGAGCTTCGAAGTAGCTCCGACCTTTTTCC

          AAACCTGGAATTTGAGGCCTTTTGCCAGCGAATCTAGATCTTGTACTAAGCTTCCGAGCT
          AGACCAGAAACTTGAGGCCTCACGTCAGCGCATTTCGATCCTGTACGAAACTTCCGAGCA
          AAACTTGGCGTTTTAGACCTAAAGTCAGCGCCGTGAGGCCGCATACGTCACGTCTGCCGA
          AAACCAGGTACTTTAGACCTAGTGACAGCGGTGTGAGGTGGTATTCGTCACTTAGGCCGT
          ACAACCGGGAGCAAAAGCGATCCATGAATATCAGCGGTCCGGTTCAGAAATCATTAAGAC
          ACAACAGGGAGCAAATGCGTTGTAGGAATATCTGCGGTCCAGTTCAGGCATCAATAAGAC
          ACCACGAGAAGAAGAGTTTTTTTGAGAGCGCCCTCATGCCAAAAACGGTGTACCAGAGGA
          ACCCCAAGGGGAAATGACTTTAGGCACATAACCTCAAACTAGCGCCTACAAGCTAGAGAG

          GAAAAATAAACGGCCGTCGGCGAAGAGGCCGTGATCAATGGAGGGGTTATATGAACTATT
          GAAAAATATACGTTTACCGGCGCTGAAGCCGTGAACAGTGGAAGGATTATACGAACCGTT
          CGCATCACCACGATCGGTAGTTGCGAAGTAGTAGTCAATGAAATGGGCATGCTAACTGCA
          CGCATTGCCATGACCGGTCGTGATAGGGCTGAAGTCAGTGAAGTAGGCGTATAGGCATCT
          TCTGGGTTTACGCTTGTTTGTGGGGGTTATGAAACCGAGGTAATGATGTCCAACACGTTC
          TATGGGCCTACGTTTATTAGTGAGGATTACGATACTGGGGTAATGATGTCTCACACGTTT
          AACCGATTCACAGTAATGGGGACGCAGTGCGTAAGCACCCACATGGACCCCCTTCTAGTC
          CATCAGTGTAAGGTATCGGGTACGTCAAATGGATAAGGCGGAATGGCTTTCAACCGGATC

          TACAACCTGTTCATGCAGCAAGCAAACGACATTCTCATGCCATCACGCTACAGGTTCGTG
          TATACCCTGCTCGTGCAGCAAGCAGACGACGTTCCCATGCCACTACGATGTAGGTTCGTC
          TACATTCGGCGAGAAGGGAGTGTATTACTCATCTTACTGCAGCCGCGAGCTCGCCGAAAA
          CATAAACGGCGAGAATGGAAGGCGCGATTCAACTTACTGTTGTCACATGCCCGCAGAAAG
          CTTCATGAGGAATTAAATAGTCATTGGTGCTGTAGACCGATGTCGATACCTAGGGCCGGG
          CTTCATGAGTAATTGAAAAATCACTGGAGCTGTAGCCCGATATCGATATCTAGGGTCGGG
          TATTTCCGCTATCTCGCTCGAGCTTGTGGTAGTGTGCAGATATTTATGGGCGTATGAGAG
          CATCTTTGTCGAATGAGGCGTGTCAGTGACCGTACGTCAAACGCAGAACCTTTACGATCA

          TTGAAAGATTTGTATTGGCCCTTGCGACCAGGGCTTCCAGCGCTATCACTTCAGTACAGT
          TAGAACGATTTCTGAAGGCCCTAGCGCCCAGGGCTTCCAGCGTCATTACCTCAGTACAGC
          TCGTTACATTGGGACGTGCACGTGTTACTATGGGTCCCGCCCTCGTCTTTGTAACACAAT
          TCCGCACTTTGGGGCGGTCATATTTGGCAACGCATCCCGTTCTCGTCTCTTAGGTAGAAT
          AAACAGAATTGGCTATTGTGCCGCAAGACAAAGCAGTCATTCGTGCCCATAATGAAGGGT
          AAGTAGAGTCAACCATTGCATCGCAGGTCAAAGAAGTCACGCGTGCCTATGCGGAAAGGT
          AGAAAGAATTAACCGTACTACTCGCTACAGCAGGACTCGATACCGGTGTACGCGGACAAC
          AGGCAGGATTAGGAAAAGCCCCTGGCGGTGTAGAAGTCGTTCCCGCTTCATGATGGAGAT

          CGCCGAACTTAATGTCCTTTAGACGATGCGAGCCATTGAATATGACCATGCCCCAAAGAT
          CGACGAGCTTACTGTCCTTTAGACAATTCAAGCCACTGTATGGGACCGTGCCCTACAGAT
          TAAACCGCTCATCAACCTAACTGTGAAGGACGGCTCTACAAACGATTGTGCGGAGTAGGT
          TGACTAGCTAAGCGCATTATCTACGAAGGGCGCGTTTGCAACTGATTGCGCTACACGGGG
          TGCCTCCCTTAAAGTCGCAAGGGTCAGGCACTTCGCCCCGCGCGATCGCTTGCGTAAGAC
          TGCCTCCCTTGAAGGCGCAAGGACCTGGAACTTCGCTTTGCGCGATCGCTCGCGTCAGAC
          TGTGAGACCACGAGATGTTGCTGCTTCGTGTTCGGCTATGCGCGTCTGTGCGCCGACAAT
          TGTTCTGTTCAAATTAGTCGCCGCCCCATCTTTTGCCGCGGGCATGCGTGCGCCACAGGT

          ATTGGGAATTCCAAACGGGCAGCTCAACGTTCCATTGCGACCATCCACTACAACACGGCT
          CTTGGGGATTCTAGACGGGCGGCCCGATGTTCCGTTGTAGCTATCCACTTCATCGGCGCT
          TCTAGGTATCGCATGTGGGTAGTTTAAGACCTCGCAGAAATCTTGTACCATAGGTGAGCG
          TCCGGGAAGTCCATGCCGGTAGCTTGAATCTCCGCGGGAGTCTTGCGCCGTAGCCGGATA
          CGTCCTAGTTTGATGTAGCTGCCTTGAAACTGAGCTGAGGTTTGATTTATAGTGACCGAG
          GATCCCAGTTCGATAAAACTGACTTAAAATTAAGTAGTGGTTTATTCTGTAGTGAACGTG
          AGTCCGACTAAGATGTGTCCTTTTCGATTCACCGCGGTACGCATACCTGCGGCAAGAATA
          AGTTGCCCTGCGATGTGTTCTAATCTATGTCCCGCGGAAATTTCATGCTTCACAGGAACT

          AGCGTGTGTATTCCGCCTTACTATAATCCCTGCGGAATGTATCGTATCGCAAGGAGCCCA
          GGGGTATGTAAACCGACCTTCTATAAGCACCGCGGAATGTACCGTACCGCAAAGTGTCCA
          CGAATTAGGCTTCGGTCGCGCCGTAAACCGTGCAGCACGGATAGTATGACGGCTTGGATA
          GCGCTTCGGCTTCGATCGAATAAATAGTCATGAGACATGGACCGTACCATAAGTTTGTTA
          AGTTCTCAGGATAGATCCAACTAAAAGCCACGTCCAACTCTAGATATCACATGGCGGTGT
          GGTTCCAGGGATAGATCCAACTAGAGGTCATGCCCAACTCTAAATATCAACTGGCGGTCT
          GTCAATGATACCGGGCCAATTTCTTGGCCGTGTTTCGGAATAAAAGCCTCATCACGGGGA
          GCCGGCAATCTCGAATTGGGCCATTTGCCACACTTCATGCCTGATGCAACATGGCAGGGA

          TAGCCGAACGCAAAAGAGGGGTGAGCCAGCCTCATGTGCCGCGTCCTTATGACGCCCAGA
          TGGTCTCATGCTAAAGAGGGGCGCGCCAGCTTCATGCGTCGCGTCCTTATGGCGTCTAGC
          GAGACTAACCACGAGAAAGGTCGGTTGAGATACATTTTTCTTCCGTCAGTGATCACCATA
          GGGGCTAACACCAAGAAAGGCTGGGACAGGTCTACTTCCCACGGGTCTATGATCCCTACA
          CGCTTAAAAGCGTCTAATTGCCTAACTTGCCCCACGCCTTACGTAAGCCTGACCGAGCTT
          CGCCTTATTACGCCTAATTAACCAATTGGCCCTATGCCTTCTGTAAGCCTGACAGAGGTT
          CGTATTCCAACAGTTGGGCAGTCGTTCTGCAGCCTGTCATGTGTGGACCTGGTCGCAATT
          AAGTCTGTCAGGCTTAAGCAGCTGTGTTGTCACAACCTACTCCGGTACTAGGCTATGATT

          TCTGTTTCAGGTTGATGCATGGTACGTTATAGTCCAGGAGGTGTCCCGTCATTGGATTGT
          AAGGTTTCCGGGCAATGCATAGTTTGTCATAATCAAGGTGGGGCCTCGTCATCGAATTGT
          TAAATCTCCGGGCCAAGTCTTGCTAGTTTGCTCTATGAAAGAGTTAAGTCAACACGTAGA
          CGTGTTTCTAGGTTAAATGTCGCATGTCCGTACTAGGAAAAAGTCACCAAAATACGTGGT
          TATACTCCTGGAAGGATAATCACTTGGCGTTTTGAAGGGGAAAGTTCACGCCTAGCGCTC
          TAGACTCCTGGAAGGCTAATAGTTTGGCTCTGTGAAGGCGAAAGCTCTCGCCTAGCGTTT
          TACGGAAATACACGGGACGCCGTTTTACCCCGCTTGAGGGGGGTACAGTGACCGATACGT
          TGTATTCTCGCTCCTCACACGCATTGGTGTTGCTTGGAGGGATGCTTATATCAAGTGCAG

          TTCGTCTATCACGAAGAAAAGCCTACCCGCTGCGTTGAGT
          TTTGCCTACCACGAAAGAAAGCCTATCTGCTGCGTTGAGT
          TCCGCCGCTGCACAAGACACTATAGTTTGACAGGACAGCC
          ACTGCTGCCCTATAAGGCGCCGTGGTGAGGCAAGGCTGAC
          TGTGATCGCTCTGCAACAGAAAATGTTGGATACATTTTCC
          TGTGGTCGCTTTGCAGAAGAAAAAGTCCGATACGTTTCCC
          AACGATCGCTGCGAAGGGTGTGGCGCCGGCTATACTTTCA
          CACGAATGCTCCATAGGACAAAGGATCGGATGAGCTTAAC

