 8 1000
t1        CACTCGTCATGGGATATTAACCCCGCTACATGAAAGATAAAAATCGCCACGTGTCGTAAT
t2        CAGTCGCCAAGGGACACTAACTTCACCACATGCAAGATCGAGACCGCCACACGTCGTAAT
t3        TGCGAGCCCAAATATATCGCACCCGTCAAGGGGTAGATGGAGATCTGTGCGCTTCGTTTT
t4        CTTACGGACGTGTCTCCTGCACCTGCCACGAGGGAGGTGGGGTCGTGAGTATGACCTCAC
t5        GTCGAGCTTGGAATTTGGGCCTATGCTATACACACGGTACGGGTTCGATTGTATCCTTGC
t6        TTCGAGCCCCAACCCTCTACTTCGATTATAGGAAGAGTTGTGAATTGCTTAGGCTCTGAT
t7        GACAGGCTAACTTACACCGTTCAATGCACAGGCAACATAAATTTCCGCACGGTTGACGGA
t8        ATGAGTTTATGCCGCTCCACTTTTATCACTGTGAACTAGAGGTCCAGGACCGTAGCCCGT

          GTATAAACCAAGAGGAGGCTGACCAAAGTAACATCAAATGTGTCCATGACCAGGTCGTAC
          ATATACACTAGGAGGAGGTTGACTAAAGTAACATTAAAAGTGCCCTTGACGAGGGCGTAC
          GTACTTTCCTTGATCGGGAAGGGAGTGGAAATACTTAGCCCGCGCCCCGTTAGGGCGTAT
          GTATTAACCATATGCGGGTTGAGGAAGGCGATGCTTCAAACAAAGCAGCTATTTGACCCT
          GGAGTAGCTAATAACGTTTTGTAAAGCGTGGTGAGCCTGGCGAGCTCGCCAAAGATGCAT
          GCGGATTTCTGAATAGCACCATGTATGCTGGTGACGAATGAAGCTCCATTATGAAAAATT
          TTGGAGACCTAGGAGTCACTGAATCGAATACTGGTATTCATAGCGAAGCCCTACTGCTTC
          GCAGAACAGTACAATTCACCAAGTGGGACTTTGTCTATTGCATGTCCATATGTGTAACGT

          CGGAAGTAGCTCATAGAAAGAATGCTACCGCGGGCACTGCGCTTAAGGTCACTGCCCGAA
          CGGTAGTAGCCCTTAACAGGCGTGATACCGCGGATACCGCGCCCAGGGTCCCTGCCCGAA
          CACCAGTAGGTTTTCCCGCGCGTCTCATCAAGCGTAAAGTGTGTAGCGCTAATGCCAGAC
          CGTTAGTCGGCCCCCTCACAGCCGGCACCAGGGATACCGAGAGACGCGTCTACACCACAC
          GTCCCACAGTCCTGTGTAAAATCTCTGCTATTGACTCCGTGGAAAGAATTACGCCATGAC
          TTCGAGATGCTCTTGCCTCAACAAGTAAAATAACGTGTGGAAGAGTAGTGCCAGCCACAT
          ATGAATCATACGACCTTGATCTTTGTTTGTCCGATATTACGCGAAAGATCACTGCCCGAG
          CTCGGGTGAACTCCCCTAGCCCATGCACCACTGATATCGAAGAAAGGAATATGACTATAC

          CATTGATTTACGTACGGTCATCTAACCACCTGATTTACCAGGGTAGTGCGTTATTTTGGG
          CATTGATCTACGTTCGGTCATCTGAACATCTGGCTTACCAGGCTAGCGCGTTACCTAGGG
          GACTGTCCTACGTTTGAACATCTAAATAAGTATCGTAACAGGCTTGTGTGTTATTTGGCG
          TAGGATTCAACGATTGTGTACCTAGACGATAGGATTGATTAGAACTCGCTCCATTGAGGG
          TACTAAACTCTGGCTCAGTCCCCGTGAATCTCAGGAGTACGGGTAGTACTGTATCGCCGT
          AGAAGATCTAGTGTCTGGATACGGCATATATAAGACTTAAGGGTAGCCCGTCCCCGCGTG
          TGGTGGCATACGAGCTCATTCCGAAATCATTGTAGTCCCTCAACGAGAAACAGCCGAGGT
          CTAATCTCGACCAATCGGACGTTCCGAAACCGAATCGGGCTGGTAGTGGCTCACTTTAAA

          GGAATCCACGCTGAAGAGCTACCGCAGGTCGCCACCCTCAACTGCGCCGCGAGTTCAATG
          GGAAATCCCGACGAAGAGTTAACGCAGATCGACACTCCAAATTGTGCTCTGAGTCCAATG
          GGAGTTAAGCGAGAACTGTAAAAACAGATCGGAATCTACAATTGCACCGGGAACAGAACG
          CGACGTTTCTCTGAAAGGGATTCGCGAGTGCACGGGGATGACTGCGTTGCGGGCCATCTG
          CCAGCCAGCTTAGAAGGACCATTCCAAATCAATCCGCGGCGAAACAACCCTGGTGGCCTA
          ATAACCTTCTGTGAAAAGGCTAGATCTATCGGCGTTGTGACTAGCACTATCACCGGCATC
          TAGTGAAGTTGAGACGGCTAACCACTAATGAACACCCAACTCTTCGACAAACGCGTGGCC
          AGAGATTCTCGTTTAGTGACGATATCATTAATTTGGGTCTCTACATTTCTGGGTGGAGCT

          GGATCGACAGACAACAGGGATACTGATAAGTTTGTCGAGGCATGATCTGGATAGTTCTAT
          GGGTTGACAGACATCAGGGATAGTGACAAAATTCTCGCGGCATGATCTGGGTGGTTCTGC
          GAATAAGCTGGCATTAACGCTAATACCATAGTTGGCAGAGCGCGAACGGGGTGTCCTCGT
          GGACAGTCCGGTGGAGGCGTAATCATCGGATGCAGTACGTTATGTTTGCATGGGACGGCA
          CACCACATTGCCGCTGGAGTTAGATGCAAGAACGCGATGACCCCGTCCTTACGGCTGCCT
          GATTGTATTGCATGTTTTAATATACTCAAGCTTCCGCAAGAACGCATAGGCCAGCCTTAG
          AGCGGGGCGATCTGAGGAGCCCTACTAGGGCTTATTGGTGAATTGAATTAACATTCTACA
          GGGGAGGGTGTCGTTGGGGCCGAAGAAGAGGGTCATCAACACACGTTTTAACGACCAGGG

          GCGCACCTAACCTCTAATAGTCATGGTCTCTGCATGTTGCTTCCCTGTCCCCGTACAATT
          GCGCTCCTATCTCCTGATAATCATGGCCTCTGAAATTTGCCTCCTTGCATACGTACAATT
          GTGGATGGGTTATTCACCAGGCCTGGTGTCTGAATGACTACTCTTCTTCCTCGCACAATT
          TCGTGCGTGTATCACGCATCACACGGTATAGATTCGATACCGCCAAACACTAGCACAATT
          TGGGATGGGTTTCAGGCTCATAACACTTACTATCCAACTCTGATGTACATCGGAGTCATT
          GCAAATGAACCTCCGTCCTACGGCCGCTTTGATTCAGCGCTCTAGCTTGTCGGCCTGATG
          ATGGGAGTCTAAGTAATCTGTCACTACCCTTAATTATACTACCATGATCCTAATTGGCCT
          TTGGGAATCTTAGACTATCGTGGAGCAGTGTACTTAGCTATTCAGCAGAGCGGTTGAATG

          ATACGGCCGTTTGCAATATATCTTCTGTATTCAATTTCGGGCCTAGTCCCCTTGTTCACA
          AAGCAGCCGCCCGCGATTTATCTTCTGTGTTCAATCTTGGGCCCGGTCCGCTTGTTCACT
          CTGCGGCAGTTAACGGCTGGCGTCGCGCCTTACATTCTGAGTTGGTTCTGCCCGCTCATA
          ATGGGACTACTAGTAATTCGCTTCCTGCGTTTAACCTTGGGAAGATCCTTATCCATTGGT
          ATGGAGTTCCCGATGGTTTCCCCCTCGCACTGATTACCGAAGCAAGCTTGCTCATATGTA
          ATCGGCTAGTGGTCGATTATTTACCGCTACCATAGCCGGAGTCAGAGACATAATGATGTG
          ATTATCGGATCGACGGTTCCTAAGTAAAATTTCGCTTAGGGTCCGGCTTACTGTGTAAAT
          ACGAAGCTATTCTCGATGAACCTTCCGGACCTTAGCCCGGTGCAGAGCTGTAGCTACACT

          CTGTCCTCCCATTTTTTTATGGTAGGTCGGAGAAATTTACCCAGACTTGTAGCGGTCTAT
          CTATCCTCCCATTCTTTTACGGCAGGTTGGGGAACGTTTCCCAGACTTGTAACGGCCTAG
          ATCTCTTTACGACCTCTTACGACCGGCTGGGGAAAAATACCTGGAATGGTAGTAGCCTAT
          TCACCGTACTCGTATGTTAACATGAACTAGGGGGCTACGTTTAACCATGTGGCAGCTCGA
          ATTGTTGGACGGCATCATACAGCGAAACGGCGACGCCCCCTTGGACCAATAGCAGTGGCT
          AATCTGACTGGGATCCTTGCAGAACAAACGGTAGAGCTACCCAGAGATACGGTAGCTGGG
          TCCCAGTTAAGATGTTTCGTTGCCGGATAGGCGTGTCTTATGAAGATAGCGGCAGTCGAT
          GATGCGCATAGGCCGGCCTCAGAAGGATAAGAAATCTGACCCCTGGTGATAATCTTTAGG

          AGGCCACCGGTACGCTGAAACAGAGAGCTACTATCAGCCAAGTTAAGTTATGCGGTGATC
          AGGCCACCGGAATGCTGAAATAGAGAGCTGTTATCAGCCTAACTATGTTACGTGGTGATC
          TAACTGTCGGACTCCTAAGGCGGAGAGCTGATATTAGCGAAGCTAAATTTCGTCGTAATC
          TAAGTACCGCTCTCCCAGCGCGAAGGCATGAAATCATTGAGGCAAGCCCGCTTAGAGAGT
          TCATAGCAGCGTTTCAGGCCAAATGTATTGATCTCAGCAAGGTTACGCCATCGAACGCTT
          CGACTCAGAGGCCGTGAGACCGGGTGAGCGAATTCGGCCTAGGTAGCCCCTGCGGCGGGT
          ACGGTCACAAATTTTTAGAACGGGAAACCGACTTTCGCGAGAGTCGTCCCGCTTTTGCGC
          TGGGCGGGAGCCTTGAGAGGGCGAAAGGTGCCACATGCCAGGGCGGGCTTAGTGTGGAAC

          GTTGACTCCTCCAGCTATACTAGGAAATCGACCCACGCCGTCAAAAGGCAACGGTTGTGC
          CTTGACTCCTCCAACTATAATAGGGAATCGACCCATGTCGTTGAAGGGCAACGGTTGTGC
          GACGACCCCTTTAACCGCAATTGGAAAACTAACCGTGTCGCGCCACGAATACGGATATAC
          GGCGTGGAATCAACCATTCAGAGAGACGTGATCCTTATTATAGACGGACGCAAACTTGGC
          GGTGTGTCGGTGTGTAGCCATAAAATAATTCGCGCCGTCGCGAGTGGCACTCGAGCCAGT
          GTAGCGTAGTCCTAGAACTGGAACCAAGACTACAATGTAAGCAGAGCCGTTCCCCACACC
          GTACGGCTGAGTCGTGACCAAAAGATACGTTGTCTTTGGGCAGTGCATGTAGGGCTACCA
          GTATTGTATTACCGTGGGCAGAGGCATTTTCAAAGCCTTGCGACCTTAACCTTGGCTTCC

          CTTAAGCATCCATTACCGTTGCGACGTCGCGGCACTAGGGAACGTGACAGTTAATACACC
          CTTAAGTGTCCATTACCGGTGCGAAGTAGTGGCAACGGGGTACGTGACGATGAACCCGCT
          TTCAGGAGATCGGCTCTGTCTAAACGCACTGACGGCAGCGCAGGCGGCATCAAATACAAT
          GATGAGAGCCTGCTTTCGTTCGAATACCGATTCTCCAGGAATGAGCATTATAACCCTGCG
          AGGCCAGGAAAAGTCATGTTCTAGCCCGCATTCGGGGGATCTATTGAATGAAATTATAAC
          AGTTTATGAGCATTCCGGCCAAAACGAACGCTCATTGAGCCGTACGCACCCGGATATGGG
          GCCAGAACTACGCTCCAGCGGAAATACCCCCCCGATAGGATAGACACGCACACATATTGT
          ATCCCATTCCAAAACTGCCCCAAGTAGGTAAACCTGAAGTACTACACATCTGCTCTGGTT

          ACTCCTGAGTAGCCCTAGAGATCCGTAACGACAATGATCTGGCTTATGCTTTGCGGTCTT
          ACTCCTGAGTAGTCTTTGAAATTCGTAACGTCAATGATCTGGCGAATGCATTGCGGTCGT
          CCTTCCAGGCAGGCCTGCCCGTTCTTAACCATAATGATCTGGCGATCGTATTGAGGAGTT
          GGCCTTAACTAAGGTCCGGTAAACAGAAAAAGGGGGGTTGGACTGCCGTATTGGGTATTT
          TGCTTGCAGTGAGTGCATCGCTCTACTTGCACAATGACCTAACGCCTTTCTGGTCGGGCA
          TAACCAAATTTGGGGTCGAGAAGGGACCACCAAGCATTCCGTCGGCGTAGTTAGAGAACC
          CGCTTTCAGTGAAAGCACTGACTGGGATTGTATAAGGCTAATCGATGGAGACGCGAAACT
          TCAATAGAGTGGATATTGGGCCGAAAATTCCTGTGGATCGACCGATCTGGCCGAGAATTT

          GGAGTCGGAACACAGCCATCCAAATGTGATCCATTGAATTCCCTGAGTTGTCTGCGCAAT
          GGAGTCGAACCGTTGCCATCCCAATGTGATCTGCTGCATTCTGTGAGTTTTCTACGTAAT
          GGCGAGAAAGCACATTCCCCAAGGCGGACTCCATTGCAATCTATGGGCCGCCTATAAAAT
          GGAGAGCGTCCATAGTGCGTTGGACGTGGCCTGCTATGACTTCTGGGGCCACGGCCGGGT
          AGGAATAAACCATTGAAAGCAAAATGCCCTTCGCCATACTTCACTGGCCATATATATATC
          GGGAAGATCCTCTGCCATATCGGGTGCTGTTAAATATTCCTGACGGATAGACAGAGGCAT
          GTGGAGGTACGTCGGCTTATAGCGCATGATCACTCGATCTATAACGTTCACTTCAGCGAC
          GGGAAGGAACAACAGTTAACGGGGTGAGACCTACTGTGTACAGTAGGGTGTTCTCAATGT

          GTTGCTTGCCCCACTCTACTCCTGCACTGTAGCGTACCATATATACGAACTGGTTGACCG
          GTTAATAGTCCCACCCCGCTCCCGCATTGTGGCGTATCGTTTATACCAACGTGTAGGCCG
          GATTATTGATATGTCTTGACGTTGTAAGGAGATATCTGAAAATTATCCACTGGCAGGTCG
          AGCCGTGACTCGCCCTCTTTTTACGATCATCGCACGAGGGATTAATAAAAGGGTTAGTTA
          TTAGCCAAACTGGTCCACCTTTCGCTCACCGTTAGGTGCCAAATAAATCCATGGAACCCC
          GAATTTGATTTCATCGGTGGTTAGTTCTTTGTTCCGGGGGGGCAGTTTAGCAGCTTAATC
          ATGTTTGGCCCGAACCGTGCGACATAAAGCAGATTGAGGGAGAGGGGCCCAAGCTCTTCT
          ACGTGCGGCATTAACTTGTCTATATTCCTAGTGAAAAAGGAAATCCTTTACTATTATCTA

          CAACGTTAGCGTGAACTGGTTATTATATGAGATGGGTTCTTGCGCAACAGAACTGAGTTG
          CAACGTCGAGGTGAACTGGTTATTATACGATACGGGTATTTATGCGATAGGCCAGCGCAG
          GACTCTAAGGGAAAACTATAAGTCATGTGAGACGGGGAACTGTGAGCCTGGCCAGAGCCG
          CACCAATAGGAAGACTCAGTTACAGCGCGAGACAGGCTAATATGCGCTCGGTTCCCCATA
          TAGGACTCAGCCGACAAACCCATATGGTAAGACAGTTTAGGGCGTATCCGGGTCGGAGGC
          TTTTGCTGATTCGGCTCCCTAAAGGGCCCAGGTGGGCGCTTGAATCTCGTTTAGGGGATA
          GACAGAAAAAGACGTTCTCTCAATGTAACAATAATGATTGCCTCCCACCGAATGTGGACG
          TCCGAGGAGGAAGACCTCTATACTGCCCTAGAGGTGGTCATCCATGGACGGCCACTATCA

          CACGCCGTCTTAAGGGCTGGTGCTTCATGTTCCTAGAATT
          CACGCCGTTTTTGGGGCGGATTCTCCACGCTATTAAAATT
          CGTGCCGCCCTCTAGATCGGTGCCGTACCCTGTTGTAGCC
          CACTACGACCTCTGGGTTGGTGACGCCTGTCGTCATAATC
          TGCACCGCTTTCCGGGGCCCTCTTCCTAACTTCCGAGAGC
          CGAGTTCTGCAATCGGATGGCGCCTCCAGTTGTGATGGAT
          CATGGTGTTCTACCGCTCAGCTCGTTGATTTACACCAAAA
          TGTGTTATACTGCGGGTGGGAACAGTGCGTGAGATTCGGA

