 8 1000
t1        AACACCGCCTCAAGCCCCCGTTCGGGTGTTAATCAACTAGTGAGAAGAACACTCGCCGTG
t2        ACCACCGTCATAAGCCTTCGTTCGGGTCTTAATCAATTCGTCAGAAAAACACTCGCCGTG
t3        CCTAAAGCTTCGAGTCTCCATGTTAGTTCCACACCACAAAAGAGCAAGTCACGCACCTCG
t4        ACGATTTTCCTTGGACCCTATGTGCATCATGCGTGTCCAAAAAGCGTAGTATCACACCAC
t5        CCCTCCGTGTCGAGCGGCTACAACAATAACGGGCACGGAGACATCGGCATCCAAACCAAC
t6        TCATTGGTATTGGGCTGCTACGTGGATCACGGTCACCGAGAGAATCGTACCCAAACTAGT
t7        TTAACTTCGCGCGGTTTACCCGACCATCATTAGCCCCACTTGTCGGACGTAAAGTAAGGA
t8        CTGGCTTCGACCAGTTGCTACATCTACTTTGAGTCCCTGGTGGTCAGTCTGGAGCCCGTT

          TTACCAATAAAGATGATTTGCCATATGCAGGCCAACAAAGGTTAATTTTGTCGCTTTACC
          CTATCAATAAAGATGATTTGTAATATGCAGATCAACAAGGGTTAACTTTATCACTTCCCC
          CTCCCGTTGAAGAAATTATGTGGTACGTATTCACACACGAATTGGGTTCGTTATCACTCC
          ATGTAGGCGACAACGATGAACATCTACCGTTTTGACAGCAACCGACTTAATTGCTAGTTC
          CTCGCAGTCCCCGAAATTGACAACTTGTGGTCCGCCATGAGCCGCCTCCACTGGAACTCT
          TCAACACCCTACAAAATGAGCGTCAAGCCATAAGGCATGACCTGTTTTTATTGGAGAGCG
          TCAAGGATCAGGAAAGTAGGGTGGGGTCTATCTCCTGTAGATCGACCTACCAAACGCTCA
          TTTGTGCTTAGGGAAAGAGTGCGGGATGACACTGTATCAGGCTCACCCCGCAAACTGAGG

          ACTCTCCGAATAATTTCCTCGTGGGTTTAGAATCCTTTAGCAAACATTCCCTTAGAGAAG
          ACTCTCTGACTACTTTCCCCATAGTTTTAGAATCCTCTAGCAAACATTCCCTCTGAGAAG
          GAGCGCCAACCCCCACCCCCTCGCCCCTAGGTGACTTTAGTCGACTTTCCTCCTGGCCAC
          GAATGAAAACTTTTTCTTAAATGATCCTACAAAACTAGTGTTGACACCCTCCTTAAGTGC
          GAGTGACGACCACGCTTCTCGCGTCTTTGGCTGTCTAATGGCGGCACGCCCGTAGAGAGA
          GCGCGATAATCACCTTCTCAACGTCCATGGATAACCATTTTCCGCCCGCCTGTCAAGAGC
          AGGCGCGAGTTCGAAATTGTTACAAATTGTCGTTCTCTTTATAATACTCGTGCTACCGCT
          ATCCGTGATTACGAACTTGATGCAATTCGCCGGCTATTAGTCAGTACATGAACTGTCGCT

          CCTTATATTACATCCATCCATAGGAGTGCGCACCGCGTCGATAATGGCAAGCTGTCAGGA
          CTTCACATTACGTCCATCTACAGGAGTGCGCACTGCGTCAATAATGGCAAGCTGTCAGAA
          TTACCTGTTACACCCATTGTTCGGACTGTATTCTGTGTCAGTGGCGTCGGCCCTTAAGAA
          TTTACCATCTAACGAATTGAGATGTAAGTAGAGGATGTTATCAATGTAGAGGCATCAAGG
          TTTCTCCGGGGACGCGTCATAACGGCTGCGGAACACACTAGACACGGATGGTCGATTTGG
          CTCCTCCATGAACGCGATTTCTGGAGGGCGGAGCACACCAGTCACGCAGAATCGCCGGGG
          GCCTGTTCGGGTCTGGTTAATGCACGTGCCATTTATCTAGATGGTAATAATCCACTTTGC
          ATTAGCAGAGGTATGACGTACACGAGTGTGGTCTCTCGAGATGCATAAGGTTTATCCGGT

          CATCACAGCGCTGACATTGTATATAAATCATAGTTTGTATTCCGAAGTAGCCACAACGCA
          CATCACAGCGCTGTCATTGTATGTAAATCATAGTATGTACTCCGAAGAATCCTCAATACA
          TTCAAGATTATTGTCACTCGTTCTAGACCGGAGTATCAACCCCGAGGGTAGCTTACCTCA
          CACTAATTCAGTTTTATTCTTCACAAACGATAATCTGAACGTCCAGGGGGGCGTAGAATA
          TAATCACCTCCCTATTAAGCTCTCCCGTTGCAGTTAGCATCTCGAGCTAGGCCGCATATT
          CTTCGTGTTTTCCTCAGTCCTTGTCCATAAAAGATGGAATCTCTAAGATAGCCAAACTAG
          ACAGGGCGGTTTCTCGTAAATTTCAAACGACGGTCCTAATACAAAGAGGAGTCGGGCCGT
          ACGAGGTGGTCCCCTGTAACCATCTAATGACGTTCCTTTGATGTGGCTAAGTCCAGCAAT

          GACTGCATCAAACGGTTGTCAGAGCAGGCATGGCTCGCAATGCTAATACGGTAGTGAACA
          GAATGCATCGAACGGTTGTCAGACCAGGAATGGCCTGGAAAGCTAATACGGTCGCGTACA
          GGACATAGCTGCCGTGTGGAAAAGCGGACATAGTTTGGTATGCAATTACCGTCGTAAATA
          GGATTCAACACTCGAGTCCTGGCGCGAAACTGGATTACCGCGTCAATTCTGTCAAGAACC
          GGAACGAGGAGCCAAAAGCTAGAATAGAGGTGCTCCGACTGGTCACAGAGGCAGCTAACG
          GACGCCTGCATCGGGAAGCGAGAGCAAAAAAGATCCGGGCAGTCATAGGCGTGGAAGTCG
          GAAGCCTTATTATCGTTGCACAAGGACTGATTACATAGAATGCCCCCGGCGGCAAATCGT
          GAAGTTTTAAAATGGCCGCCTACGGGTCAATGATATTGCACGCCTCCATCAATATAACAG

          GCACATTAGCGACATCCCAGTAGGTCTGGTAGTTGAAGCTACCTTCCGGGCGTACGATGC
          CCATACTAGCGACATCCCAGTAGGTCTGCTAGCTGAAACTACCTTCCGGTTGTACAATGC
          TGATACCATTGACCTGCTACAAAGTCCTGTGGCTGAGGCTACCTTCGACGTGTGTGAGGC
          CCAGGTCGAAGACCTAAGAGAGACACCGGAAGCTACCTACATTTTTGGCATGATTAAAAC
          TCGTACTATCGACCCACTGAAAGATTAACAAGTTCATATGATCCTCGGAGGGCACAAGGA
          CTGTGTTGGCGGAACCCCAAAAGGCGCCGCAATTTCCATGCTTCCTGTCGCGTGTAATTT
          TTACGACTTTTGCCGATCGGTGGGGGCAACTGACTCTTCTTTTAATTGAGCATCAAGGAA
          CCGTGTTTTTAGCGCTGCGGCTGGCGACATTGATATCTCCTCCGCCCGGGAGTGCATATT

          AAAGAGTGCCCTCGTTCCCATGACCATTACGGCTGCTCAGTCATGTGTCCGACTCGGACT
          AAAGCACGCCTTCGTTATCATTACCATTACGGCTGATCAGCCATGCGTCCGACTCGGACT
          AATCAACGTGTACGTGAAGGTTACCGGAGACGCTGTCCGGTGGCGTGTCCGCTAAACATT
          TAACAACGCCTCAGTTACATTGGATGACGAGTTTGCTGTGCTACGTTCCTGATAGCGGAC
          TAACAGCAGTTTAGCGATAATGACATGTGAGGTCATCTTGTGGCGTGGGCGATTTGAATA
          TAACAGTATTCCCGCTATCACAACTGGTGAGATAGTTTTGTACAATGCACGTCGCCGACG
          CATCTTTTAAGCCCGCAAACAGGCGCGCGTGTGTGTACTGTCGCTGAGCCGGCTCTAAGC
          TTCCCCCTATGTTCATAAGCGAGTAAGCGCTCGCATTGCACTGATCAAGTGCTCTTGAGG

          CCCCGGTCATAACTGAGCATTGAGAAATGTAGCCAAGATCATGAGTTTCAATTTACACCC
          CCTCGGTCATAATTGAGCATTGAGAAGCGTGCTTAAGGTAATGAGTTCCAATTTCCGCCC
          GATAAACCTGATTGGAACAATCAAATATCCAGTAAAGATGATAAAACCCGACTCCAGCCC
          GGGGCATCCGGACCGAGCCACTCGCCGTACGGCCCAGATAACGCGGCACACCTTCCGTCT
          GAGCTTGCTAGGATTAATAACTCGACGTGTTGCAGGAACGGCAGCATCTTGCTTGTACTT
          GTCTCTGTTAAGCTCAGTACATTAATGTGGCGAAAAAGCGACAGAGTTTGGTCAATGCTT
          TGGCTACTCAGGTTGTGAATCTCGCCACTTATAAGTCATACAGAGGCCCCCTCCGGGGTC
          GCACTACACCGGTCGAGAACTACAAATATTGCAGCAGGCATCGAATGTCCTCGTAGGGTA

          GTTTTGGAGTTACGATACCCGCTACGCGACCGGCGAGTCATTCTCCCTACTCTTCAATTT
          GCTCTGGAGTTATGATAGCCGTTACGAAGCTGTCGAGTCGTTATCTCTGCTTTTCAATTT
          ACATTAATGCCACGAGGGCGGGTCCATGGTTCTTGTCAAACCGATCCCACACGTCAATCT
          ACACGCTAGCTACGTAAACGCATACGAAGACTCTGTTCTATTAACCTAGCAAATCAATCC
          CATTTATTGTCACGAAGTGAGCGTCACGGTCCAGGACCCCTAGGACTTGTGTATGAGTTT
          TCTCAGCCGACGTGGAGTCGGACAGGTACTCGTCGTTAAGTTGACCATAATCATCAAAAT
          ACTTCAAGCTTGCGTGAAATTATGCGAAGAACCTAACGTAAATGGAGTCGAGCTCAAATG
          GGTCCACAACCAGGCGATGCTCTGCGAGTCGACTGGCATTAGCGGCGTTGACTTGAAACG

          TGTTGTGGGGTCTAGGTAGTAAAACCCTTTACTCGAATGGCGGGCAATAGAAAACCAGTA
          TGTTGTGCGGTCTAGGTTGTAAGCTCCTTTACTCGAATGGCGGGCAATACACCATCAGTA
          CTCTGCGGTATCTAGGTTCTGGATCCGCTCTCCTCGATGGGGGACGAAATTGGACCTATA
          TGTTTCCGAGACTAGGTAGCAATACCCCTCGCTCCTCTGGCAAACGGCTCATGATGAGTG
          CCACGTGAGGCCCGAAGCAAAAGTCACTGCAGCTCTATTGCCCGCCATAGAGAACCGGTA
          TCCTGCGAGGGTCCAATCATAAGGTGCATCAATGTTATAGTGGGCCTTTCAGGACCGGTA
          TCGCAGGTGTCTTAAATAAATAACCCTCTTATTCCCATCTTAGCGAAAAACGGTACAATG
          TCACTACCCCGCAACGTAGGTACTTCATCTACTTTTTTGCTAGTGGAATAGTATATAGGA

          AAGCTTAAATCCAACCCCGCCTAAATCCGGTTTTCTTAGTAACACGGCAATTTTGCAATC
          ACACTTACGTCCACTCTTGCTTAAGCCAGGTTCCTTTAGGAACACAGCAATGATGCAATC
          CGGCCCGACTCCAATCCTATTTCAGTCTGGTAACGCTCGCTGCTTAGCAATTCTGCGACT
          CCCCCCGCGTTCTCTCTCGCTCAAATTCAGAGGCGTCAATAATATGCCCCATCACCAGTA
          TCGTACACGCGCGTTATGACTTTTGCCCCGACGTGTCGACGATGCCGCAATACCCCCGCT
          CTGCCCGTGTCCATTATCGCTCTTGCATAGCCGCGTTGATCACGTAGCGGTACCGTTCTC
          CCGACATTGATCGCTTTTGCTCCAGCTCATCTGTCGTAGACACGTAAGAATTGCGCGCGT
          TTGCTTACGTTCACCTTTGCTCCAATCTGCTCAGCCGGGAATCTCCCAAGCCGTGTTTCC

          TTGTTAGATACGCTCTGATGCGGTCCGTGACCCCCGGAGGGTCCCGCAATCAGGCTCTCG
          TTGTTGAGTACATCCCGATACGGTCCGTGACCCTCGGAGGATTCCGCAATCAGGCTCTCG
          TTGATAACCGCGATTGCACCTGGTCGGTAACCTGTTAAAGGTCCTGCAATCAGGCTTTTG
          GTGATAGGCGAGAGACGATTTATGCTAAGACCCCCGAAACGCTAAGCAATGGGATATTTG
          CACTTAATTTAGCGATAGTTGGAACTACGATCTATGCCAAGCCACACTTGTGAGCCCTTG
          CACGAAGACAGGCTATAGTTCGGTCCCTGTTCTACAGAAAGTGGTCGAACAGGTCCATTA
          TACAATGAAGTAAGCTGGTTACGTAAACGGTATCTAAGCCTTTGCCGATTCCAGCACTGC
          CCGAGATAAGCGGATTAGTTAAGAGAATGCTGTTCGGACCTTTAGAGGTTCTCGTCTTTG

          CTCTCGTGAGACCACCTGACCGTAATCCAGATGAGGTGAAGTCGGTGGAGAGGATGCTCG
          CACTCGTGAGACCACCGCACTGTTATCAAGGTGGGGTGAAATCGGGGCAGAGAATGCTCG
          ACGCAAGGCGTCCACCCTGGTCTAACACTCGTAAGGTTAGCTCTGGGCTGAAGATGGGCG
          TCGCCCAGGTTCTATGGTCATTTAATAGGTCCGGGGATATCTGCTGAACGATGATGGTCA
          AACTCTAATGGTTATACTACTCATGCGGGCGCGAGCGTGTCTTTAAACTGAAGATTTTTG
          ATCCCTACCGATCACTCCCTCTCCGGAAGCCGGAGGGTAGACGCGGACGCAACATTTCCG
          ATCCCAGGAGATTACCTTTCTTTAGTAACTTTGGTGGTAAGACTACCCCAAGGGGTAGTG
          ACTACTGACTGAAGCCCGTTTTCTGCCACTACGAACGTAAGCCTGGCCCCAGGGACAGTG

          TATACCTGAGTGTTCCTTGGACTAGCCTGTTCAAGGTAGGACGTCCGGCAACTATAATTG
          TTGACCTGCGTGATCTTTGGACTAGCCTGTTCCAGGTAGGACGTCCGGTAACTATATTTG
          TCAGTGCGGGGATTCGTTGAACCGCCTCGTCCCAGGAAGGTTGCTTGGTTTCGATCCCGA
          TTGAAGCACGTGGTTGTCCGGTTACTTCGCCCACGGCAGTTCGTCAAGTTTAAATTCTCG
          CGACAGTCGACTGTCGCTGAACTGCTGTGCCTAGGACAGGCTATGGAGCTTTGAGTGCAG
          CAGAAACGGATGTTTGCTGGACTGTTATGCTTAGGGCCGACCGTGTAGTTTCCGTTCCAG
          AAGACAAAACCGCTTGTTAGCCTTAATGCACCGGGGCTTAGTAAATATGATTACCACGTC
          TCGAAATGGGTGCTCCTAAGGTAAGACGAGGTCAGGGTGAGTGGACGCGGTCCCCGTGAT

          CATGCAGCGAATCGAGGGATTCCTTTTCCTACACAAAAGGGGTAAAACCAACCATCCATT
          CATGCAGCGAATCGAGGGATTCCTTTTCCTGCACAAAAGGGGTAAATTTAATTATCTACT
          TTTGAAAGGTACTGAGACGTACCCTATTCTGAAAGGTCGAAGCTGGTTTGGGAACCCAGC
          AATCTGATAGATCAGAATACCGTACATTGTGCGTGGCGAAGGGAGTCATTGATGTCAGAC
          TTTGATCTGGATCGGGCCATCATCTGTTCAGGGCGAAGGGGCCAGCTGCAAACTGAAAGT
          TCCGATTTAGACAGGGTCATCATGAAACCAGAATACTAGGATCAGCTTAAGATCACAAGA
          AAAGTTACGGGTGGGGTAGCTTTGGGCTACGAGCAAGGTTGGAGAAACTGTACGCTGTGC
          TAGATTCGCAATAAGAGTGCTTTTGGTCATGAACTCGGCTAGACAAATAGAAGGCCGCGT

          GTCAAGGTTTGGGGGAGAACCTACGGAGGCATGCTAGATA
          GGCAAGGCTCGAGGGGAGTCCCATGGAAGCATGCTTGAGA
          ACCAAAGACTAAAAGTAATGCTATACAACCGTCTTGAGGG
          AATAAGAACCATGAGTAGTTCGGTGTGCGTGTAGTAGCGG
          GCCCAGCACCAGATGTAATCTTGGGATAGCGTCTTAGGGG
          GGAAGGGAGCAGATGTAATTTTCTGGGTATGATATGGAGG
          GTTATTGATGGAAGGTAACTCCGCGGGAGCGAGTCATGGC
          AATGGGATTGAAGGGCCACCTCATGAGAGCTGACTGCGGC

