 8 1000
t1        ACGACCTCCCAGACAACCCCGACGCATCAGATTCTGACATACAGAAGATATTAATGGCGA
t2        AGAATGTCGCAGATGGTTCTGACGTCAAGGATTCTGGCGTACAGGGGATATTAATATAGA
t3        AACACCCTCGTAACAATTTAGCGACTGCGGACTATTATTTCAGGTCCATTGCGATGCGGA
t4        GGCGCTCCCAGGGCAACCTTAATTGCACCAATAACGATTTGTGCTCTAATTGGGTATGGG
t5        CGAGGGGTTCAGACACCTCTGAGCTAGTACTTACTAGGTTATGAGAGTGCCTGCTCCGAG
t6        CGTATCCTCGATATCACATTGCTCTCCTCGTTCCCGGTGTCACACCTAGTTCAGCTAGGA
t7        TCTTAGCATGGCTCCTCCTCGAGCTTACTGTTATTCGCGCATAGTAACATTTGCTTCGAA
t8        ACAGTAGCCGAATCTGTTCTAAACCCCTCGCTTCAAATGAAATGATATGACGGATCGGTA

          GATGCGCTGATAGAATAGGGGTAGTTCGGTCGATTACGCCCCGCTTAGGTGTCGGAAGAG
          GATGCGACAACAGAATAGTGGGAGATCGGTCATCGGTGACCTTGATAGCAACCGTGAGAG
          AATCAGTGGGCTGAACATTGGCATCCCGGTCAGAGTTGACCTTCCCGGCCGCTGAAAACA
          GTTAAGTGGGTAGATTAGCAGCAGCCCCTCCTCTATTGACCCTCTTGTATGCTGAAATCG
          GGCTTGTGCGGGATTCGACTGCAGGACCCCTCTTGCACTTTCTTAGAACCCCCGAATGCA
          CGTAGATGGCAGAATTGCAAGCTAGGGCCTTCATGTTTCCCCCTTCATTCGTTAGATGTA
          AATAGCTAGGAGGGTGATCAGCGGGCACGTATGCCGCCCCCGTATTGAAGGGTTGAATTG
          GCGATCTGTAGAGCCGAAACGTAATACCGTAGTCGTCGCATTAACTGCCAGCTGTATGAG

          CCAACGGCCTACGGAGCTCTACTTACTACTAGCTACGTGAGAACTTGTCGGAAAGTCAAC
          ACAACAGCCTACGGAGCCTCACTCGCTACTAGTGCCCAGGGAACATCACATACAGTGAAT
          CCAACGACTACCCTGGTTACCCTTGCCAGCGGCGCCTGGGGAATTTATGGAAAAGCTGAT
          ATAACGGTTCAATCAGTTGTTTCTCATATTAGCACGGCGGTCTCCATCCTAACGGTTGTA
          GCGACAGTACACCTAATCATATGTGCCACTAGCATACCGGGAACAACCCTTAACAACGGC
          AGAATCGGTTAGAATCCTGTGTTCAGCAATAGCATAGCAGAGGTCCACTTGTAAAGTGAT
          TCGACCCCTATGGCTGCGGGCTCAGCCAATGTCAACACATGGTCACGTTCCAAGCCTTGA
          ACTACAACAATGGTTGTCCCTCGAAGCGCCTTCAATAGTACGTTTTATTCGGGATGTGTG

          ATCTAACCGACACTACGAGATAAATGCAGGACAATTTTTGGCTATTTCACCGTGCGGTAT
          AACTGAGCGGTGTAACGGTATTAAAACAGAAATATCGTCGGTAATTTCACTGTGCGGTCT
          AACAGAGTACATAAACGGCGCTAACGCTATTCCATTCCAGCAAACTCTACCATGCGACAC
          GGCTGAACTGCACAGACGTAGAAACCCAACCTCATTTCAATTAACCTCGTTGTGCGGTCT
          ACCCGCGTCGCAAAAAAGCAAGTCAGGAATGTACATCTTGTTGGGTGGTCGGTATAGCCC
          CACCGGTGATGACCGCGATATGAACCGCCTGCTATTGGGGTCAGGCCCGGGGTAATGTAC
          GATGGAGGACAGCCCGTCCATTTATGCTTGCCAGATCTGATCCGGGCCAAGAATGCGATT
          GACTGCGCGCGCCACGGATATACTCGATGCTTAAGCCCAGTCAGTCTTTTAGAGGTGAAA

          GGTTTGAGCCATCTGGGGACTATCAGCCTTTTCAGCTCTTTATACTTGAGTAACACGGCC
          AGTCTGGGCCTGCTGGGGATCATCCGTGTTTCTGGGTCCCTGAACTTGAGCGATACAGTC
          CGCCAACGCCGTACCGTGTTTAACGGTACTACTCGTTTTCCGTATCTGAGCACCGTGGTT
          CGTTGAGGTCACTTACGGATTGCCGGCAATATCAATACTCCTCTTCTGAGTGCGACGGTA
          CACCGATGCCAGCCGGGGAATCAAGACACCGTTTGTATTCTTTTCGAAAGGTCTATGTAC
          TGTTTGCATCGATCAGGATTACACGAAACGGGAGATTACCTTCTTTGGAGCCGTATCGCC
          CACACTTTTCCCAAAAGAGTTACTTTATCAGGACCAGGTATCAAACTCCGTCGCGCGTCG
          TCCGTAGCATGCTTATAGCTGTCCTATGCGGTGTGTCTCCTTGCTCGAGCTAAAGCGACA

          TTGCCGATATCGAGTATACGGGAGGCACTGTAAACCCATTCTCCCCAGTTGGCGCAGACA
          TGGCCGATATCGAGGAGACGTGAGGAACTGAAAAATTATTCTACCCACCTGCTGCGCTCA
          TGGTCGCCACCGGAAGGATGTTAGCCCTCTCAAATCCGCGATACACAATTAATGTCGATA
          CACCAGTTAGCGAGACGTAGGCACATGACGGGGGTTTGCGTTATCTGCTTGGGGTAGAAA
          TAGACACTAGTGAAACGATTGAACGCGCCGAAAACGGGTAGAATCCCCATGATGCAGATA
          TAGTTGTCATGAAAGTACCACGTGACTGTTATCACGGGTAGCAGTGGCTTGCCGCCGACA
          CGGCAGTCTCTAAAAATAGCTAACGACACCCTTAGGGGGTGTGCCAACCTGGCCCATACA
          GTCGCGTTTGAGAATAGGTATTGGTTGATGAAAGCGTAGTTCACGCATAAACGGCCTGTT

          CGATGCCAGCACAGGGCGCGGTCCAAAAACTGTCCGAGCTTCACCATAGCCCCGTACTGC
          CGATGTCGGCATAGGGCGCGACATTAAAACTGACCGACTTTCACCGTGGCTTAATGTCGC
          GGTTAACAGACTCCGACGTGCCCTGATGCGAGTACGTCCGTCATAACACGATCGTGTTAT
          CGTAGCCAGACTACGGCGTGATCCGGTAAGCGCACGAGTGCCAATCCGTAACCTTAACAC
          CGCTAATAGACCATCAGGCTACATGACTTGCTCTAGTCCACCGCGATATAAACTTACTTA
          AGTCCGCCGTCTGGGGTCCAAGCAACTCGATGACTGACTGATGCGCCAGCCCATTACTAT
          AGCTGATCGGTTTGGGCGTATCTTAGTTCATATATCGGTATACTGTCATCCTCTCTTACC
          CTTTACGCGACAGTGATTAAGATCAAAGGGCGCAAATTCAACATGCAGCTACCCGGCTCC

          CATCAGTCGTTCGTGCCTATTGTACTCTATCTAAGTAATGCAGCACTGATAGTTGACAAC
          AGTGGGTAGTTCGCTCTTATTGCACACCACGCCAGTGACGCAGTACCGATGGTCGAAAGC
          AGTGAACAGATCGTGCCCGTTCTTAACCAAGAAGGACTCGGGGACCCGTTTGTCAACAAT
          ATAAGCGAGATCTCCTTTACTATACAATACATAAGCCGAGTAGCACTGGTTGTCTCAATC
          ACCAGGCGCCCCGTGTCAATCCCTTAGTGTAACATTTTCGCCACATTCTCTGGGGACTGG
          TCCGGGAGTTTTATGCCTGTATTCCGTTACGGAAGACGCCCAGCAACCTGTGTAAACCAC
          ACAAGCTCTACGATACGCACGTTCGTCCATAACAACCGTGTTTGGTTCTTTCAAGAACAT
          TCTGAGCTTCATACACTCCCCTCCCTCAAGAGCTCACGCATAGGGCCTGCTCGCGACTCA

          CCAAACTAGACTAGCTCTGTTATGGCCTCGGTTCGCGACTCCCCGAGGACGACGAGACTC
          CTAAACTAGACTAATTAAATTAAGCCTTCGATTGGCCTTTTTTTTAGGGCACCGCGCTAC
          TTAAAATTAATTGAATTCTCCAACCCTTCGCATGGCGGCTCCTTGAGTGCGTTGAGCTTC
          CTAAATGTAACCAAGCATGTCAAACGTCTCGGTAGTGTCTCGTTGATGGCGCCACCCATC
          CCGGGTCCCCCTAGGCACTGGAAGAATTCCGATGATTCCCCGTCGATGGCGTCGCGTTTA
          CGTAACCGAGCGACCGTCGCCAGGCATCCGGATCACGCCTTTTTGACGGCGCTTAGTCTA
          CTGAGTGGAGTGTCAGCGAACAGGAGTTCGTAAGGAGACATTCGGGTCGTGTTCAGTGGA
          TCGAATTGTGCTTAGTAGGTCACTTGACTAAAATGTGCCACTTCCTGAGGGACAATTATA

          AGGAGGGCATCAGAGAAGTGCAAGAATACAAGGGTAGGAACAGTTACTGGTCCGTCACCC
          ACCAGCGCACCCGAGAGGTCCAAGAACATGAGGGTAAGACCTGCCGACGGTCCGCTGCCC
          GAAACGACGTCTGAAATTATAACATACACATAGAACAGGAATGACAACGCTTTGCCACCA
          AGAAGGCGCCTAGGGAAGACAAAGTATCCATGAACCGGGAGAGTCAACGGCCTATGACCA
          AACTCTATGCCGGACTAAACACAATACCCAAGCGCGAGTTGGACATACTAATCGGCACAG
          AGAACGGGGATTAGACCGAAGTTACGCGCGTCAACCACCTCTGGACGCGGGTGGTAACTA
          CGTCTGTTACTAGAATTGCTACAGCGGATATGTGTTAGCGGTCTAAGAGGTCGGGCCTAG
          CGGCGACTTCTGAATATACTGAAATGGCGAAGAACTCACGGTCCAAGAAGAATAAGGTGG

          AGGCCCTGGCACAGAGCGGGAACTGGGAATTCACTGAGAGGAACAGTGCTGTGTTACGTT
          AGGCCCCGGCTTAGCGAGGGAAATGTGTGCTTACTAGGAGGAATAGTACTACGTAGCGTT
          TAATTACGGCTTCAGGAGAGAGTTAAGCGCTCACGAGCAGCAACAGTACCGCGTTAGACT
          CTACCTCGATCATGCAAGAGAAATAAGAGCACACTATGAGGAGCACAACGGAATCGGACT
          GAAATTTGTTCACGCAAGGCATCTACGTGGACGCGTTAATAGATGCCCCTGCTTCAGTCT
          CCCCCTGGCCTGAGAAGGGGATTTTGGGTTTTCCCCCTACGCCAGCCTACGACCTAGAAC
          GGGACGAACCCAAAAGAGGCGTTCCAAACTGAGACAAAGACCGAGCATCGAATACAGACT
          AGACTACGTTCTGAGGTAGAATACGAAATTCCGCTGTAAACCCAGCCTTGAACTTGCCAC

          CGAATAGACCTCATACGCAGAGATAACCAATCGGGCCGAACCAAAGCGGCATAGTTGTTC
          CGATTAGACCTCTTTCGCAGAGATAACCAACCGTTCTGCATTAAAGAGACGTAGTTCTTC
          GTGACAACTCTGATGCGGGATCACAACGATACGTGCCGCAACATAGAGGTTCGGCCGCTT
          TCACGAACCTTAGTGGGCTACCCCGTCAAAACCCACAGTGCGGTAGTGTATTGATTGTTC
          AGGTCTGAGACTGTGTATAATTGTGCCAGTAGGTATCATTTTAAAATGATTTGATTCCCA
          AGACTGCATGCTGTGTGAAATTACGCTTACATTTTCCTCTGCTGGCGAGCCCGGCTCTGC
          GCTCTAATTTAAGTAGAGCCGTCCACAGACGCTTACTGCGAGACTACAGTAAACATGTCT
          GGAGAACCTAATGTAAGGGATGAGGCGGATCCTCTACAGGTATGAAAAGCCAGGAGCATT

          CCGGACTACGGTCGGGTTTATCTACTAAAGTAAGGAATGCAAAAGCGAGTAGTCGACAGA
          CTGGACTATGGTCAGGTGTTCCCGTGGAAGTTAGGCAATGAAAGGGGAGTTGTTGACAGA
          CCAGGGTATCACTACGTTTTGTTGATGGAGCTCGTGGCGCAGCCGGGGGACGGAGTCAGA
          CCGCGATCTGTCCTCTACTTTGCGCCGGGGTTAGTGAAGCAAACGGGAATTGACGATTGA
          CCGGGAAATCATTTCGTCTAGTCGCTGAGCTTCACGCCGGAGGTCTGATGTGCTATCTTG
          TCGTGAAACGGGGGAGACTGATTGCTGGGGTTATGCTCGAAGTAGTGTTCCAGCTTCCGA
          ATAGGAGAGGATAGCCCGACGTAGTCGCGGTACGACTGCTCAATGTGACTTTCAATTGCG
          CAGCGACTGTTTATGGATTCAATGTCCTTGACAAGGTAGTCTTGGAGGCACGCAACTTAG

          ACTGAATATAAATCATAATGGAACCCTGAGGCAATTAGCCCCACTAGTCGTTGGAACGTC
          ACCTAATGTAGATTGTAATGTAACCCTGGGGTAATCAGTCCTGCTAGTCGTCTGGAAATC
          TTTCCGGGTTATAAATCAAGGAATCCCGGGCTTAGTAGTCCTATCAGTTATCGGGTGCTC
          TTCAAAGGCAAAATATCATGGAGTGTAGGGGACGCCAGTCCTACCAGACACTGGGCCATC
          GGCCCTGTTAAAACGACATTAAACATAGTGGCTATAAGTCTCACTATGCCCCCGGAGCAT
          GAGCGGGCTTGAGTTTCAGAGCCTAAGGCGCCCCCAAGTCCTATATAATTCAGGGTGTTA
          GGCCTCTTCAGATCGTTCTCGCAATATGATGATGTGGCCTTTACTCGATTGCAGGGAATT
          AATCTTAGTAGGACACTGAAGTGGGACGTGGACGGGACCTCGAGTTAATTATATGGTTCC

          GTTCCACTACTATCGTAGCGATGCCTTTATGTCCGCTTCGGCGCGATTGTTCTACCAGGT
          AATCCGCTTCCAACATGGCGACCTCTTCATCTCCGCTCCGGCGCGAATGTCCCCCCAAGC
          AGACGGCTCTTATCGCAGAGATGACTGGGGGACTGTTTTGCCTCGAATGCTTCAACAGAT
          AATCACCATCACAAACGACGGTGCCATCCTGCGCACTTTGACCAGACCTTCTCACCCGCT
          GCTTCTCCCATTCCAAGGCAAGTAACGAGTAACTGCTATATCCCAGCTGCTTCACCACGA
          GATAGCTCTGCCTTAGGTCAATGACCAAACGACTGCCCCGCCGAGAGAGGCAGTATAAAT
          GGACCTCCGCATCTGCCATTCGGGCTGTATCCTTGGGTCGTTCGTAATTCGGAATCCGGG
          GATATTCCCGCACTGTTGCATCATCAGATCTATATCTCCCGATCCGGTCTAGGGCGTAGT

          TACACGAGTCGCATGTCAGGGCCCTACAATACATGGAACAGCACAATCCGCCTAGGAAGT
          TGCAGAAGTCGTAAGTCAAGACACCACAAAAGAGGGGACTGCACAATCAGCCCTGTAGCT
          GGCTCACGCCGCAAGTAGGGACACCAAGGGTGCAGAGATAGCACCAGTAGTTTAAGAGCC
          CGTATAAGTCATTTGATAGGTAACCTGAAAGACAGAGGTCGCGCCAGTTATCTAAGGGTC
          TAGGCTAACCAAAAGTATGAAGACACCATGCGTCGGGCCCCCTCCGGTGGTCCAAGATCG
          TCTACTCGCGAGGAGCAACTATACTCTTAGGGTGGGCACGACTCTGAACCTCCCACCGCG
          CGCTTTTCAGAACATGCACAGTATCTGGGAAACCCGTGTGGCCCTGCTTGCTCGGGAGCT
          TGAATTCATTTTCGGTTACAGATCGCTTCACGGAGCGATCTACGCAAAAGCCTGGGGGCC

          ACGAGGCGTCTGGAAGCACGGGCCATTTCGGCAGGGAAGG
          ACGAGGAGGCTGCAAACACGGGGCCTCTTGAAAGGGAAGA
          AAGCGGCATTCATATACATGGGCCGTTCAGGTAGGGATGA
          TTGCTAGGTCTGCGAACATGGACTGTCCAACTTAAGACAA
          CGGAGGGGTATTAGGGCGTGCACTCATTAGGTCCCAAGAG
          ATGATGCGCCTCTGGGTTTTGAAGATCCACATGGAAAACG
          AAAAAACGGGCTTTAATGATGCGCCCCCAGCGTGCCAAGG
          GAACCGAGAGCTTGCACTAAGCACTATCCATGATGGAAGG

