 8 1000
t1        GAGCCTTAGCACCGAGATCCCAGAAGTCGGATGTAAACGGGGGCCCCGTTGCCAAGTGCG
t2        TTGCTTCGACACCCAGCACCTGGTAATTGGTTGCAATTGGAGGTCCCGCTGAGAAAGGCC
t3        ATGAATGTGCGACCAATACTTAGGAATTATCTAGTCTTCAACAACAGGTAGTAAAATCAT
t4        ATGAACGTGCGACCAAAACTTAGGAATTATCTAGTCTTCAACAACAGGTAGTAAAATCAT
t5        TTAAGCCGAAGTAGAGGACGCTAAACTAGTGCACAACCGCAGAGATGTACGCAGCGGAGG
t6        TCAAGCCAAAGTAAAGGGCGTCAAACTAAAGCGCAACGGCGGAGGTGTGCGAAATGGAGC
t7        ACCAAAGCTCGCTGAAAGCGTAAAGTTTAACTGCAACTTCGGAATCATGCGTACTGGAAT
t8        GCTAGCACTCGTTGAGGACATAAAACTGTCAGGTGATTGTACAGCCGTGTGCTGGGAAAC

          AACGGTTACCGCGCTGTGACTTATCAGCTGGCTCTCGACGGAACCAGCGCTAAATAGGAT
          GGCTGCTCATATCCTGAGTTTTATCAGCCGGCACACATACGTGCTTGCCCTGGGTCAGCT
          AGCCGCGGTAGTTAGAAATGGGCCTAAATTGGGATGCTCAGAGTAATACTTAAAGCAAAA
          AGCCGCGGTAGTTAGAAATGGGCCTAAATTGGGATGCTCAGAGTAATACTTAAAGCAAAA
          TCTCGACGTTTCGATGACAAGTGCCATCTTGACACTGTGGGGGATCCCATATAGTTACAA
          AATCGATGATTCGATACCACGTGCCTTCTCAGCACCGTGGGGGACCTCTTTTAGGTACAA
          AATCTATCCGCTCACCTTACACGCTAACTCAAATCTGTGAAGAAATCATTATAGGTACAA
          AATTAGAGTATTGACTCTACCCGTCGGCTCAACCCCCTGGGCAAAGTATTTCAGGTAGAG

          AGACTGAACGTGTGGCTGTCGGGGTGGGCCTTGGGGGTTATCTACGGCTACCCCCTTACA
          GGACCAGTTAGCCTATCTACAGGGCAAGTCCCAAATGTTTCTCGCGACTGCCCCCGAATG
          TATTCGAACGCTTGCTCCTTAGTACAAACGCTCTAAGACTGTCACGCGTGCTCCTGAAAT
          TATTCAAACGTTTGCTCCTTAGTACAAACGCTCTAAGACTGTCACGCGTGCTCTTTAAAT
          TCATGAGCATAAAGTCACCTAGGACAGAGTTTGAGGGCAAATTGCAATTCATCACAACCT
          CCATGAGAAGAGAGTCATTGACGCCACGTTCTGAGGGCCAACTACGATTCGTTCAGAAAT
          TCACAGCGGTAAAGTCACTCAAGCTAGGTTCTGGGGGCTAATTATGATCCGCCCAAAATA
          CCCCGGGCGTAAAGTTACGGGCGCCAGATTTAAGGGATTCATCATGATTCGCACAAAATT

          CCGGCAAGATGCCGCCACGCGCCCTACCCTATATCTGAGGATAGCGAACGTTTAGTTGCA
          CTAGCAAGTCGCCATCATAAACCCTGGTTCACGCCTGCAAACAGCGCAGGCTCGGCTGAA
          GTGGAGTGGTATGTCTATAAGTTCCGCTTTTCAACTTCTGCTTGAATCCAATTAGAATTG
          GTGGAGTGGTATGTCTATAAGTTCCGCTTTTCAACTTCTGCTCGAATCCAACTAGAATTG
          TTCTCGATACGTATCGGCTGGCATATCTTATAACGCCGCGGCACAAACTAGTAATCAGGA
          TTATGGTTATTTGGCGGCTTGCATCTTTCCTAATGTCGCGATAAAACCTAGTCATCAGGG
          TTCCAGATCTGCGACGGCCGCCCTTACTCTCCACGCCGCGAGATAAATTGGAAAATTAAA
          CTATAGGCACACGAAAGCCGGCATCAACAACAACGCCGAGATACAAACTGGAGTACAAAG

          GGTCAACGGCAGTGCATCCTAAAGGGTAGCGTGTCTCCTTAAATTACATGCGCTTCCTGC
          CTTAGGCCGGTGTCTCCCCTAGAGGAAGGTGGATCCCCTGACGTCATTCGCGTCTCCCAT
          GCCAAGCGACCACAAACTCTGTACATGCATTGACCACACTCGGATCCTAAGGTCGTGGGT
          GCCAAGCAACCACAAACTCTGTACATGCATTGACCACACTCGGATCCTAAGGTCGTGGGT
          ATTTCGCCACCCTTCCGTGCTTGGATAAGGATGTTACACCCCAGTTTATGGGTCGTGGTC
          GCTTCGTGAGCCTTTCGTGTTGGAACAGGGTTGATAGACTACGGTCCAAGGGCTGCGAGC
          TTGGAGTAACCTTTCCGTGTTGGAAAAAAGCCGTCACATAGCAGGTAATTGATCGTTGAC
          ATTCAGTGACCCTTTCATGTGTGTCTAGAGCTGTCATATCACACCATATAGGTTACTACC

          ATCTTGGTTGCGTCTCGGGGGTAACCAGTGCGACCCTGCCGTGCCGTGGAAGCCGCTACA
          TTCGTGCTTACATCGTGGGGAAAACCGTCGCGTCCATGAAGCGCTGTGGGTGCCGCAAAA
          GTGTAGACTACGCTTGCAGGCTAGATTACGTGTATGCGGAGAAATGGCTGATTGACTACA
          GTGTAGACTACGCTTGCGGGCTAGATTACGTGTATGTGGCGAAATGGCTGATTGACTACA
          ATTCAGATTCACGAAAGGATGAGTTACGCGATATTGATGAGGGCGGTTTTAGCTCGCATA
          ATTCTGGTTCTCGGAAAGAAGAGTTGTGTGATATTAGTTAACGAAGCTTTAATTCGCATA
          ATATAGAATCCCGAAAAGAAGCGACACCTGTCGCTACTAAGTGTTAATTCAATTTGTATA
          ATATTGGTTCCCGATAAGTAGTGTCACACGTCATTTTTGAACGTTACCCCGATCCATGCA

          AGCGAACCATGAAGATGCCTGGAGAGGTCGTGGTACCATCCAATTTCATTGTCGTTAGAC
          ATCACTTTGGAATAGCTTTCGATGATAGCACTGCGCAATGGACTCAAACTGCCTTCGGGT
          ATCGGCCGGAGACACTTTTTCGCAGCCCTAAACGGCGATAAGGACTTAACTTTGCAAAGA
          ATCGGCCGGGGACACTTTTTCGCGGCCCTAAACGGCGATAAGGACTTAGCTTTGCAAAGA
          CTTACTGGGGTGAGTCATCGTGCGATTCTAAGGTACGCTGCTTCACCCCGTTTATACAGA
          TTCAGCAGGGTGAATCATGGTGCGACTCTGGGGCGCGGCGTTACACCCTGTTTACACAGG
          TCCAATGGAGTAAAACTCAATGTGGCTCTGCGGTATCGTGTGCAACCTCGGTTGCATAGA
          TCCAGTGGCGCGGATTCGGCTGTGACTATGCTACTCCGCGTAACACATTGGTTGCACCGA

          AGGTTTCTGTCAGACTATTGTCTCAAAAGTGAAGACCAGTTCCCGGACGTTTTCACCGGT
          ATGCCTTCACGATTTCCCTGTCTCACGAGTAAAAAATAGTCTTCATACGCAAACAGTTCC
          CAGATCCTGCAGATATTCAAATGCATGGGCGAGTCCAGAGCGCAAGCTCGCAGACCTTCC
          CAGATCCTGCAGATATTCAAATGCATGGGCGAATCCAGAGCGCAAGCTCGCAGACCTTCC
          GCGGGGCAACTACTTCCCAGGGAAGCGAGGAAGTCCCCGTCACAGGCAATTTAATGCAGA
          GGGGGCCATTAATTCCCCGGTGGACCGAGGGAGTACCCGTTATAGGCAATTTAACACAGA
          GGGGGTTAACTAGTCCATGGAGAAAGGAGTGAGTCCATGTTACAGGAGACCTAACATAGA
          AGGGATTAACCACACCATGGTGGGGCGGGGAGGTTTCTGTCATAGGTGACTTCACCCAGA

          AAGGTGGATGAATGTGAGAGCCGGTGGATCCGTAGTCGTTGTATTCTTGTTCGCTTCTTC
          GCAAACAACCTACGTCGAGGACATCAGATCTGAAGTCATTTTATCCTCGCGCTTTTTTCT
          CAAGTGGATTGACGCAGGGGATGGTCTGCCGCTGGTACTTTTCTTTTAGCACGTGGCGCG
          CAAGCGCATTGACGCAGAGGATGGTCTGCCGCTGGTACTTTTCTTTTAGCACGTGGCGCG
          TTGGTCTGCGCATGTAGGGGGAGTCGACCCCTTGGGTGCTTTGCCTGAGCCTACTCTACC
          TTGATGTGCGCCGGCAGGGGGAGCCGATTTCCTAGGTGGTTTGCTCGCGCCCACTCCATC
          AATACGTACGTGTGTGAGGGGAGACGACCCCCTGGACTTTTTACTAGCGTATAACCCATC
          AATAAGTACAAATGGAAGGGGAACCGAGCCCCCGGGAGTTTTACTCGCGTCGACCTCGGC

          TAGCGAAATCCTATGAGTTGATCCTGACATTCTTCTGACAGATTGTTCTGCTGGCGTCGC
          TAACTGCCCCGAATACATTGATCCTGGCACTCTCCTAGCGGATTATAGAACTGACGACGC
          CTTAGATTAGAAGCGGTTTGATAGCCATCTGCTCCAAAAACTCCGATCTAATGATATTAC
          CTTAGATTAGAAGCGGTTTGATAGCCATCTGCTCCAAAAACTCCGATCTAATGATATTAC
          GGTGCGTCCATAGAAGACTGGTCAGCATGTAGCCCAGGGTCCATGCGATACACGGAAAAG
          GCGACGTCCATGGAAGTCTGGTCAGCGTATGGCACAGGCTCTTTGCCTTACACAGAAAAG
          TTCACGAATAATAAGGTATAGCCGATGCGCGGCACAAACTCTCTGCACTACACAGAGCAG
          ACACCGCTTGCGAACGTCTGGTTAATGCAAGGCAGCACTTCTCTGACCTACACAGGGTAG

          TTGGTCAACGTACCTTGGATCGTTCGCACCGCCATTAAAGGCCTCGATCCGTTCGATGAC
          CTGGTCAACGTCTCCTCGAGTGATCCCACCACTATTAACGACCTGGTTTCTTTTGGCGTC
          GCGTCCAGGAACCCGTCGACTCACGGTTCAAATGTTGCGAGCTTCCATATCCTAAATGTT
          GCGTCCAGGAACCCGTCGACTCACGGTTCAAATGTTGCGAGCTTCCACATCCTAACTGTT
          TCATTGGAAGCCTTGCCGCCCCACAGGGCAACTATTGATGACTCAGCGCCATTGCATGGT
          CCGCTCAAGGTCTTGCCGGCCCAAAGGGCTACAATTGACAACTCAGCGCTACCGCCCGAA
          CCATCCAACGACTTGTCGATCCATAGAGTCACTATTGGCAACACTGGTCTATCAGATGTT
          CCATCTTAAGTCTTGCCGGTTCAGCGGGCCGCCATTATCACTATTGCCCTCCTAGTCGTT

          CCTAGCTTCTCAGTTAGAAGGTGCCTGTGTCTGAATTCCTTATGCTAAAATTTCAGAAGC
          CTTAGTCACTCAACCGCAAGGCGTCTGCTGGTGACCCTTTTACGTTCAAATTCTACATGT
          AACGGTTCCGTAGACGAGGGACGCGTGTGAGTAGTACTTATAGTTCTTGCATCCAAAAAC
          AACGGTTCCGTAGACGAGGGACGCGTGTGAGTAGTGCTCATAGTTCTTGCATCCAAAAAC
          TACCATCATGAAGACGCCAAGAGTTTAGAAGCTACGTCATGAGTTCCTTCTCGTGACCAT
          TACTATCATGGAGGCGTCTAGAGCTTAGAGGGCACGTTGCGTGTTCATTCTCTCGACCGC
          TGCGATCGCGAGGACGCCTCGCGCTCAGAGATTACGCCACGTGTCCATTTTCCTGAAGGC
          TTCGGTACCGAAGACACCATGAGCTCAGAACGTACGCTAGGTAGAGGTTTCCATGATGAC

          TAGCATTGGTTGCCCTCCCAGTCACAGCCGACATTCTCCATAGGATGTTCTCCATACAGT
          TAGGACCAGTTTACTTCCTTACCACGGTCGCTATTCACAATGCGGTGCGGTTTAAATGGT
          GCCGATCGGCCTTTTTGACTCGATCGTGTGGTCGCAAACGCGTCAGAACCATTCTCCGTG
          GCCGATCGGCCTTTTTGACTCGTTCGTGTGGTCGTAAACGCGTCAGAACCATTCTCCGTC
          GAATTTAGTCTTTATTCGTCCACTTGCACTGCGGCTATTACTTAAGCCTAACGACACGCC
          GCATTACGGCGTTACCCGTCCACATGCATAGCGACTCTGACTTAAGCCTAACGACACGCT
          GAATTACGGTTATACTAGTTCACTAACACCGTCGTCATGACTCAAGACTAACGAAACGCC
          GGCCTATGCTCTTACTCGATCAACGGCATTGCCGTTACGACGGAAGATCAGCGAAATTCC

          GTAGACTGAGTAGGTTCCGGGTGACAAATGTCATCAACGAGAGGAATCCCCTCTATGTGG
          GCAATCTTAATAGGCAAGGGCTGTTGGGGGGTAACATTACGAGGAACTGTGACAAAACGC
          GAATCCCAAATGAATCGGGCGTATCTAGAAGCATTGGTGGGCGGAATTCATCTCTCTAAG
          GAATCCCAAAAGAATCGGCAGTATCTAGAATCATTGGTGGGCGGAATTCATCTCTCTAAG
          GCGCGTCCTTGAACTCGACCATATAGAAGAACGCTGAATGATTAAATTTACCCAGTGTAG
          GAGTGCCTGCGTGTTTGATTATACAGCCGAATACTGCACAGTTAGATCTCACTAGACAGG
          GAACGTACGCGTATTCAACCCTTTCGAAGAATGCTGTGTAACGAATTCTCGTTTGCGGCG
          GATTATTTGTGTATACGACCCCACACGAGAATGCTTTATAATGAGATCAACCTACCGGAG

          AGTTCTGAGATTGGCGCCATCAGCAAACAGGGAGCAACTGCCCTGGGAAGCAGTGTTGGG
          AATACAGCAAGTCTTGCCCGTCCCAGGCTAGGCGCACCTACTCTGGCAGGTAGTGATGGT
          CTTGTGTACCACTAGCTGTGTCGATCACCCACGGCTACTTCCGATCTTGCTGGAGACTTA
          CTTGTGAACCACTAGCTGTGTCGATCACCCACGGCTACTTCCGATCTTGCTGGAGACTTA
          GGTTTTATCTGTGATCCATACAGGCCGTTCATAGCGACTATCGGGGCCTTTAGTTTTGGT
          GGTTCCAAATGTCATACATAGCAGCCCTTCCTAGCGATTATCGGGGCTTTTAGTCTCGGT
          GCTCTTATCTACAATACCTACGAGTCTTTCTTAGCGGTTATCGGGGCTTTCGGTCTAGGT
          GGTCTTGGCTGTAATATCAATGAGCCCTCCTTAGCGGCTGTCGGGGTTCTCAGTCAAGGT

          CCTCCGATCGATTTCAGATGCACTATAACAGCAGCCCATAAATTTCTCTTGTCCGGATGC
          TACTTGATCGATCTTCGATGAAACTGCTCAGCAGTTATTAGGTCTTGTCTACTCGGACGC
          AGGAGGAATCACTAGGGCAGGCTTAGTTCGGTTGACTTGGATCCCAGGTCGCCCGATTCG
          AGGAGGAATCACTAGAGCAGGCTTAGTTCGGTTGACTAGGATCCCAGGTCGCCCGATTCG
          AGATAAATGGTCGGAATGGCAACGAAATTGATTCACATTGGAGTAGCGCGAATTGGTCGC
          TATCATGTCCACGAAAGGGTGGTGAAACCGATTCATTTTAGGATTGGGTGAGTTAGTCGT
          CATTATGTGAACCGGTCATTATCAAAGTTACTTTGGCTTAGCGTAGGGCAGGGTGACCGC
          AGTCACGTAAACCGGACGAGATCAGAACTGTTTTATTTCAGCATAGGGCGGGCTGCTCTT

          AGTACTCTCTGGTTGCGGGGTCAGTTCTCGAAGAGTGCCA
          AGTACTCCCGAGTTCCGGAGTCGCACCTGGATTGGCGTCG
          CGCCCCCCAGCGGGACAGCTGAACTTGCCGCCTGGTGGCA
          CGCCCCCCAGCGGGACAGCTGAACTTGCCGCCTGGTGGCA
          GATAGACGAAGGCTGGGGCGCGGCTATTTAGAAAACGTTG
          AGCAGCCGCAAGCCGGGGCGTGGCTACTTAAAAAGCGTTG
          AAAAAACAAGAACCGGCGCGTGGCTATTTGAAAACCGTTG
          ACCAGACACGCAACAGGGTGTGGCTGCTCGAAAGACGTCT

